:PROPERTIES:
:ID:       160e9a61-da64-4473-997a-d17f1268562c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief des Johannes* -- *1*
[[file:1.Joh_2.html][2]] [[file:1.Joh_3.html][3]] ...
[[file:1.Joh_5.html][5]]

--------------

* 1.Joh 1
  :PROPERTIES:
  :CUSTOM_ID: joh-1
  :END:

Dieses Schreiben wendet sich wahrscheinlich an einen örtlich begrenzten
Kreis christlicher Gemeinden und ist wohl gegen Ende des 1. Jahrhunderts
abgefasst. Nach Stil und Gedankengut ist der 1. Johannesbrief mit dem
Johannesevangelium nah verwandt.\\
\\
Der Verfasser rechnet sich zu einer Gruppe christlicher Lehrer (vgl.
»wir« in 1,1-4 u. ö.), die im Kampf gegen Irrlehrer (vgl. 2,18; 4,1) das
»von Anfang an« Verkündigte (2,7.24; 3,11) einschärfen wollen.\\
\\
Das Schreiben mahnt zum Glauben an Jesus, den Christus und Sohn Gottes,
und zur Bruderliebe. Es ist kunstvoll gegliedert und hat folgenden
Aufbau: Vorrede (1,1-4); Gemeinschaft mit Gott durch ein Leben im Licht,
das heißt durch Einhalten der Gebote (1,5 - 2,17); Abwehr der
»Antichriste« und Festhalten am wahren Bekenntnis zu Christus (2,18-27);
Gotteskindschaft und Erfüllung der Gerechtigkeit in tätiger Bruderliebe
(2,28 - 3,24); Unterscheidung der Geister und Verwirklichung des
Glaubens in der Liebe (4,1-21); der wahre Glaube als Sieg über die Welt
und als Weg zum Leben (5,1-12); Abschluss: Sünde und ewiges Leben
(5,13-21).\\
\\
Der 1. Johannesbrief ist ein wichtiges Zeugnis für den wahren Glauben an
Jesus Christus als Gottessohn und weist auf bleibende Grundlagen des
christlichen Lebens hin (Bruderliebe, Überwindung der Sünde).\\
\\

<<verses>>

<<v1>>
** Vorrede: Das Wort des Lebens: 1,1-4
   :PROPERTIES:
   :CUSTOM_ID: vorrede-das-wort-des-lebens-11-4
   :END:
1 Was von Anfang an war, was wir gehört haben, was wir mit unseren Augen
gesehen, was wir geschaut und was unsere Hände angefasst haben, das
verkünden wir: das Wort des Lebens. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Denn das Leben wurde offenbart; wir haben gesehen und bezeugen und
verkünden euch das ewige Leben, das beim Vater war und uns offenbart
wurde.

<<v3>>
3 Was wir gesehen und gehört haben, das verkünden wir auch euch, damit
auch ihr Gemeinschaft mit uns habt. Wir aber haben Gemeinschaft mit dem
Vater und mit seinem Sohn Jesus Christus. ^{[[#fn3][3]]}

<<v4>>
4 Wir schreiben dies, damit unsere Freude vollkommen ist.
^{[[#fn4][4]]}\\
\\

<<v5>>
** Das Leben in der Gemeinschaft mit Gott: 1,5 - 2,17
   :PROPERTIES:
   :CUSTOM_ID: das-leben-in-der-gemeinschaft-mit-gott-15---217
   :END:
**** Das Wesen Gottes: 1,5-7
     :PROPERTIES:
     :CUSTOM_ID: das-wesen-gottes-15-7
     :END:
5 Das ist die Botschaft, die wir von ihm gehört haben und euch
verkünden: Gott ist Licht und keine Finsternis ist in ihm.
^{[[#fn5][5]]}

<<v6>>
6 Wenn wir sagen, dass wir Gemeinschaft mit ihm haben, und doch in der
Finsternis leben, lügen wir und tun nicht die Wahrheit. ^{[[#fn6][6]]}

<<v7>>
7 Wenn wir aber im Licht leben, wie er im Licht ist, haben wir
Gemeinschaft miteinander und das Blut seines Sohnes Jesus reinigt uns
von aller Sünde. ^{[[#fn7][7]]}\\
\\

<<v8>>
**** Christ und Sünde: 1,8 - 2,2
     :PROPERTIES:
     :CUSTOM_ID: christ-und-sünde-18---22
     :END:
8 Wenn wir sagen, dass wir keine Sünde haben, führen wir uns selbst in
die Irre und die Wahrheit ist nicht in uns. ^{[[#fn8][8]]}

<<v9>>
9 Wenn wir unsere Sünden bekennen, ist er treu und gerecht; er vergibt
uns die Sünden und reinigt uns von allem Unrecht. ^{[[#fn9][9]]}

<<v10>>
10 Wenn wir sagen, dass wir nicht gesündigt haben, machen wir ihn zum
Lügner und sein Wort ist nicht in uns. ^{[[#fn10][10]]}

^{[[#fnm1][1]]} ℘ Joh 1,1-5.14

^{[[#fnm2][2]]} 1-4: Die Vorrede ist mit dem Anfang des Evangeliums
verwandt und setzt diesen wohl voraus. Die Zeugen des Mensch gewordenen
Wortes («Wort des Lebens») sprechen als Verkündiger; sie wollen die
Briefempfänger zu einer tieferen Gemeinschaft mit dem Vater und seinem
Sohn Jesus Christus führen. das Wort des Lebens, wörtlich: vom Wort des
Lebens sprechen wir.

^{[[#fnm3][3]]} ℘ 1,7; Joh 17,20f; 1 Kor 1,9

^{[[#fnm4][4]]} ℘ Joh 15,11; 16,20.22.24; 17,13; 2 Joh 12

^{[[#fnm5][5]]} ℘ 3,11; Dan 2,22; Joh 8,12; Jak 1,17

^{[[#fnm6][6]]} ℘ 2,4.11; Joh 3,20f

^{[[#fnm7][7]]} ℘ Joh 8,12; 12,35f; Hebr 9,14.22

^{[[#fnm8][8]]} 8-2,2: Das Thema «Christ und Sünde» durchzieht das ganze
Schreiben (vgl. 3,4-9; 3,19-21; 5,3f; 5,16-18).

^{[[#fnm9][9]]} ℘ Ex 34,6f; Dtn 32,4

^{[[#fnm10][10]]} ℘ Spr 28,13
