:PROPERTIES:
:ID:       fe032b1f-92ba-4fd2-9181-a21b4e0812c8
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief des Johannes* --
[[file:1.Joh_1.html][1]] [[file:1.Joh_2.html][2]]
[[file:1.Joh_3.html][3]] *4* [[file:1.Joh_5.html][5]]

--------------

* 1.Joh 4
  :PROPERTIES:
  :CUSTOM_ID: joh-4
  :END:

<<verses>>

<<v1>>
** Der Glaube als Weg zum Leben: 4,1 - 5,12
   :PROPERTIES:
   :CUSTOM_ID: der-glaube-als-weg-zum-leben-41---512
   :END:
**** Über die Unterscheidung der Geister: 4,1-6
     :PROPERTIES:
     :CUSTOM_ID: über-die-unterscheidung-der-geister-41-6
     :END:
1 Liebe Brüder, traut nicht jedem Geist, sondern prüft die Geister, ob
sie aus Gott sind; denn viele falsche Propheten sind in die Welt
hinausgezogen. ^{[[#fn1][1]]}

<<v2>>
2 Daran erkennt ihr den Geist Gottes: Jeder Geist, der bekennt, Jesus
Christus sei im Fleisch gekommen, ist aus Gott. ^{[[#fn2][2]]}

<<v3>>
3 Und jeder Geist, der Jesus nicht bekennt, ist nicht aus Gott. Das ist
der Geist des Antichrists, über den ihr gehört habt, dass er kommt.
Jetzt ist er schon in der Welt. ^{[[#fn3][3]]}

<<v4>>
4 Ihr aber, meine Kinder, seid aus Gott und habt sie besiegt; denn Er,
der in euch ist, ist größer als jener, der in der Welt ist.
^{[[#fn4][4]]}

<<v5>>
5 Sie sind aus der Welt; deshalb sprechen sie, wie die Welt spricht, und
die Welt hört auf sie.

<<v6>>
6 Wir aber sind aus Gott. Wer Gott erkennt, hört auf uns; wer nicht aus
Gott ist, hört nicht auf uns. Daran erkennen wir den Geist der Wahrheit
und den Geist des Irrtums. ^{[[#fn5][5]]}\\
\\

<<v7>>
**** Die Vollendung des Glaubens in der Liebe: 4,7-16a
     :PROPERTIES:
     :CUSTOM_ID: die-vollendung-des-glaubens-in-der-liebe-47-16a
     :END:
7 Liebe Brüder, wir wollen einander lieben; denn die Liebe ist aus Gott
und jeder, der liebt, stammt von Gott und erkennt Gott. ^{[[#fn6][6]]}

<<v8>>
8 Wer nicht liebt, hat Gott nicht erkannt; denn Gott ist die Liebe.

<<v9>>
9 Die Liebe Gottes wurde unter uns dadurch offenbart, dass Gott seinen
einzigen Sohn in die Welt gesandt hat, damit wir durch ihn leben.
^{[[#fn7][7]]}

<<v10>>
10 Nicht darin besteht die Liebe, dass wir Gott geliebt haben, sondern
dass er uns geliebt und seinen Sohn als Sühne für unsere Sünden gesandt
hat.

<<v11>>
11 Liebe Brüder, wenn Gott uns so geliebt hat, müssen auch wir einander
lieben.

<<v12>>
12 Niemand hat Gott je geschaut; wenn wir einander lieben, bleibt Gott
in uns und seine Liebe ist in uns vollendet. ^{[[#fn8][8]]}

<<v13>>
13 Daran erkennen wir, dass wir in ihm bleiben und er in uns bleibt: Er
hat uns von seinem Geist gegeben.

<<v14>>
14 Wir haben gesehen und bezeugen, dass der Vater den Sohn gesandt hat
als den Retter der Welt. ^{[[#fn9][9]]}

<<v15>>
15 Wer bekennt, dass Jesus der Sohn Gottes ist, in dem bleibt Gott und
er bleibt in Gott.

<<v16a>>
16a Wir haben die Liebe, die Gott zu uns hat, erkannt und gläubig
angenommen.

<<v16b>>
**** Furcht und Liebe: 4,16b-21
     :PROPERTIES:
     :CUSTOM_ID: furcht-und-liebe-416b-21
     :END:
16b Gott ist die Liebe, und wer in der Liebe bleibt, bleibt in Gott und
Gott bleibt in ihm.

<<v17>>
17 Darin ist unter uns die Liebe vollendet, dass wir am Tag des Gerichts
Zuversicht haben. Denn wie er, so sind auch wir in dieser Welt.

<<v18>>
18 Furcht gibt es in der Liebe nicht, sondern die vollkommene Liebe
vertreibt die Furcht. Denn die Furcht rechnet mit Strafe(,) und wer sich
fürchtet, dessen Liebe ist nicht vollendet.

<<v19>>
19 Wir wollen lieben, weil er uns zuerst geliebt hat. ^{[[#fn10][10]]}

<<v20>>
20 Wenn jemand sagt: Ich liebe Gott!, aber seinen Bruder hasst, ist er
ein Lügner. Denn wer seinen Bruder nicht liebt, den er sieht, kann Gott
nicht lieben, den er nicht sieht.

<<v21>>
21 Und dieses Gebot haben wir von ihm: Wer Gott liebt, soll auch seinen
Bruder lieben. ^{[[#fn11][11]]}\\
\\

^{[[#fnm1][1]]} ℘ 1 Kor 12,10; 1 Thess 5,21

^{[[#fnm2][2]]} ℘ 1 Kor 12,3

^{[[#fnm3][3]]} ℘ 2,18.22; 2 Joh 7

^{[[#fnm4][4]]} habt sie besiegt: gemeint sind die, die Jesus nicht auch
als echten Menschen bekennen.

^{[[#fnm5][5]]} ℘ Joh 8,47; 14,17; Joh 15,26; 16,13

^{[[#fnm6][6]]} ℘ 4,16

^{[[#fnm7][7]]} ℘ Joh 3,16; Röm 3,25; 5,8

^{[[#fnm8][8]]} ℘ Joh 1,18; 5,37; 6,46

^{[[#fnm9][9]]} ℘ Joh 4,42

^{[[#fnm10][10]]} ℘ 4,9f

^{[[#fnm11][11]]} ℘ Mt 22,37-40; Joh 14,15.21; 15,17
