:PROPERTIES:
:ID:       5d338d6c-258e-4f66-9da6-3f8f6e6726e4
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief des Johannes* --
[[file:1.Joh_1.html][1]] [[file:1.Joh_2.html][2]] *3*
[[file:1.Joh_4.html][4]] [[file:1.Joh_5.html][5]]

--------------

* 1.Joh 3
  :PROPERTIES:
  :CUSTOM_ID: joh-3
  :END:

<<verses>>

<<v1>>
**** Das Geschenk der Kindschaft Gottes: 3,1-10
     :PROPERTIES:
     :CUSTOM_ID: das-geschenk-der-kindschaft-gottes-31-10
     :END:
1 Seht, wie groß die Liebe ist, die der Vater uns geschenkt hat: Wir
heißen Kinder Gottes und wir sind es. Die Welt erkennt uns nicht, weil
sie ihn nicht erkannt hat. ^{[[#fn1][1]]}

<<v2>>
2 Liebe Brüder, jetzt sind wir Kinder Gottes. Aber was wir sein werden,
ist noch nicht offenbar geworden. Wir wissen, dass wir ihm ähnlich sein
werden, wenn er offenbar wird; denn wir werden ihn sehen, wie er ist.
^{[[#fn2][2]]}

<<v3>>
3 Jeder, der dies von ihm erhofft, heiligt sich, so wie Er heilig ist.
^{[[#fn3][3]]}

<<v4>>
4 Jeder, der die Sünde tut, handelt gesetzwidrig; denn Sünde ist
Gesetzwidrigkeit.

<<v5>>
5 Ihr wisst, dass er erschienen ist, um die Sünde wegzunehmen, und er
selbst ist ohne Sünde. ^{[[#fn4][4]]}

<<v6>>
6 Jeder, der in ihm bleibt, sündigt nicht. Jeder, der sündigt, hat ihn
nicht gesehen und ihn nicht erkannt.

<<v7>>
7 Meine Kinder, lasst euch von niemand in die Irre führen! Wer die
Gerechtigkeit tut, ist gerecht, wie Er gerecht ist.

<<v8>>
8 Wer die Sünde tut, stammt vom Teufel; denn der Teufel sündigt von
Anfang an. Der Sohn Gottes aber ist erschienen, um die Werke des Teufels
zu zerstören. ^{[[#fn5][5]]}

<<v9>>
9 Jeder, der von Gott stammt, tut keine Sünde, weil Gottes Same in ihm
bleibt. Er kann nicht sündigen, weil er von Gott stammt. ^{[[#fn6][6]]}

<<v10>>
10 Daran kann man die Kinder Gottes und die Kinder des Teufels erkennen:
Jeder, der die Gerechtigkeit nicht tut und seinen Bruder nicht liebt,
ist nicht aus Gott.\\
\\

<<v11>>
**** Aufruf zur Bruderliebe: 3,11-18
     :PROPERTIES:
     :CUSTOM_ID: aufruf-zur-bruderliebe-311-18
     :END:
11 Denn das ist die Botschaft, die ihr von Anfang an gehört habt: Wir
sollen einander lieben ^{[[#fn7][7]]}

<<v12>>
12 und nicht wie Kain handeln, der von dem Bösen stammte und seinen
Bruder erschlug. Warum hat er ihn erschlagen? Weil seine Taten böse, die
Taten seines Bruders aber gerecht waren. ^{[[#fn8][8]]}

<<v13>>
13 Wundert euch nicht, meine Brüder, wenn die Welt euch hasst.
^{[[#fn9][9]]}

<<v14>>
14 Wir wissen, dass wir aus dem Tod in das Leben hinübergegangen sind,
weil wir die Brüder lieben. Wer nicht liebt, bleibt im Tod.
^{[[#fn10][10]]}

<<v15>>
15 Jeder, der seinen Bruder hasst, ist ein Mörder und ihr wisst: Kein
Mörder hat ewiges Leben, das in ihm bleibt. ^{[[#fn11][11]]}

<<v16>>
16 Daran haben wir die Liebe erkannt, dass Er sein Leben für uns
hingegeben hat. So müssen auch wir für die Brüder das Leben hingeben.
^{[[#fn12][12]]}

<<v17>>
17 Wenn jemand Vermögen hat und sein Herz vor dem Bruder verschließt,
den er in Not sieht, wie kann die Gottesliebe in ihm bleiben?
^{[[#fn13][13]]}

<<v18>>
18 Meine Kinder, wir wollen nicht mit Wort und Zunge lieben, sondern in
Tat und Wahrheit. ^{[[#fn14][14]]}\\
\\

<<v19>>
**** Die Zuversicht der Kinder Gottes: 3,19-24
     :PROPERTIES:
     :CUSTOM_ID: die-zuversicht-der-kinder-gottes-319-24
     :END:
19 Daran werden wir erkennen, dass wir aus der Wahrheit sind, und werden
unser Herz in seiner Gegenwart beruhigen. ^{[[#fn15][15]]}

<<v20>>
20 Denn wenn das Herz uns auch verurteilt - Gott ist größer als unser
Herz und er weiß alles. ^{[[#fn16][16]]}

<<v21>>
21 Liebe Brüder, wenn das Herz uns aber nicht verurteilt, haben wir
gegenüber Gott Zuversicht;

<<v22>>
22 alles, was wir erbitten, empfangen wir von ihm, weil wir seine Gebote
halten und tun, was ihm gefällt. ^{[[#fn17][17]]}

<<v23>>
23 Und das ist sein Gebot: Wir sollen an den Namen seines Sohnes Jesus
Christus glauben und einander lieben, wie es seinem Gebot entspricht.
^{[[#fn18][18]]}

<<v24>>
24 Wer seine Gebote hält, bleibt in Gott und Gott in ihm. Und dass er in
uns bleibt, erkennen wir an dem Geist, den er uns gegeben hat.
^{[[#fn19][19]]}\\
\\

^{[[#fnm1][1]]} ℘ Joh 1,12f; Röm 8,14-17; Eph 1,5

^{[[#fnm2][2]]} ℘ Kol 3,4; 1 Kor 13,12

^{[[#fnm3][3]]} Er: gemeint ist Christus, das große Beispiel der
Heiligung.

^{[[#fnm4][4]]} ℘ Joh 1,29; Hebr 7,26

^{[[#fnm5][5]]} ℘ 3,12; Gen 3,15; Joh 8,34.44

^{[[#fnm6][6]]} Mit «Gottes Same» ist der Heilige Geist als göttliches
Lebensprinzip gemeint (vgl. Joh 3,6).

^{[[#fnm7][7]]} ℘ 1,5; 2,7; Joh 13,34

^{[[#fnm8][8]]} ℘ Gen 4,8

^{[[#fnm9][9]]} ℘ Joh 15,18-21

^{[[#fnm10][10]]} ℘ Joh 5,24; 11,26

^{[[#fnm11][11]]} ℘ Mt 5,21-26; Joh 8,44

^{[[#fnm12][12]]} ℘ Joh 13,1; 15,12f

^{[[#fnm13][13]]} ℘ 4,20; Jak 2,15f

^{[[#fnm14][14]]} ℘ Jak 1,25; 2,12.15-17

^{[[#fnm15][15]]} «Aus der Wahrheit sein» bedeutet: zu Gott gehören
(vgl. Joh 18,37).

^{[[#fnm16][16]]} Der von seinem Gewissen verurteilte Christ weiß, dass
er auf das göttliche Erbarmen hoffen kann.

^{[[#fnm17][17]]} ℘ Joh 14,13f; 15,7; 16,23f.26

^{[[#fnm18][18]]} ℘ Joh 13,34; 15,12.17

^{[[#fnm19][19]]} ℘ Joh 14,21-23
