:PROPERTIES:
:ID:       f2ef3d75-4098-4671-bc3d-4aa217831a9f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief an die Korinther* --
[[file:1.Kor_1.html][1]] ... [[file:1.Kor_8.html][8]]
[[file:1.Kor_9.html][9]] *10* [[file:1.Kor_11.html][11]]
[[file:1.Kor_12.html][12]] ... [[file:1.Kor_16.html][16]]

--------------

* 1.Kor 10
  :PROPERTIES:
  :CUSTOM_ID: kor-10
  :END:

<<verses>>

<<v1>>
**** Israels Geschichte als Warnung: 10,1-13
     :PROPERTIES:
     :CUSTOM_ID: israels-geschichte-als-warnung-101-13
     :END:
1 Ihr sollt wissen, Brüder, dass unsere Väter alle unter der Wolke
waren, alle durch das Meer zogen ^{[[#fn1][1]]}

<<v2>>
2 und alle auf Mose getauft wurden in der Wolke und im Meer.
^{[[#fn2][2]]}

<<v3>>
3 Alle aßen auch die gleiche gottgeschenkte Speise
^{[[#fn3][3]][[#fn4][4]]}

<<v4>>
4 und alle tranken den gleichen gottgeschenkten Trank; denn sie tranken
aus dem Leben spendenden Felsen, der mit ihnen zog. Und dieser Fels war
Christus. ^{[[#fn5][5]]}

<<v5>>
5 Gott aber hatte an den meisten von ihnen kein Gefallen; denn er ließ
sie in der Wüste umkommen. ^{[[#fn6][6]]}

<<v6>>
6 Das aber geschah als warnendes Beispiel für uns: damit wir uns nicht
von der Gier nach dem Bösen beherrschen lassen, wie jene sich von der
Gier beherrschen ließen. ^{[[#fn7][7]]}

<<v7>>
7 Werdet nicht Götzendiener wie einige von ihnen; denn es steht in der
Schrift: /Das Volk setzte sich zum Essen und Trinken; dann standen sie
auf, um sich zu vergnügen./ ^{[[#fn8][8]]}

<<v8>>
8 Lasst uns nicht Unzucht treiben, wie einige von ihnen Unzucht trieben.
Damals kamen an einem einzigen Tag dreiundzwanzigtausend Menschen um.
^{[[#fn9][9]]}

<<v9>>
9 Wir wollen auch nicht den Herrn auf die Probe stellen, wie es einige
von ihnen taten, die dann von Schlangen getötet wurden. ^{[[#fn10][10]]}

<<v10>>
10 Murrt auch nicht, wie einige von ihnen murrten; sie wurden vom
Verderber umgebracht. ^{[[#fn11][11]]}

<<v11>>
11 Das aber geschah an ihnen, damit es uns als Beispiel dient; uns zur
Warnung wurde es aufgeschrieben, uns, die das Ende der Zeiten erreicht
hat. ^{[[#fn12][12]]}

<<v12>>
12 Wer also zu stehen meint, der gebe Acht, dass er nicht fällt.
^{[[#fn13][13]]}

<<v13>>
13 Noch ist keine Versuchung über euch gekommen, die den Menschen
überfordert. Gott ist treu; er wird nicht zulassen, dass ihr über eure
Kraft hinaus versucht werdet. Er wird euch in der Versuchung einen
Ausweg schaffen, sodass ihr sie bestehen könnt. ^{[[#fn14][14]]}\\
\\

<<v14>>
**** Über Götzendienst und Götzenopfermahl: 10,14 - 11,1
     :PROPERTIES:
     :CUSTOM_ID: über-götzendienst-und-götzenopfermahl-1014---111
     :END:
14 Darum, liebe Brüder, meidet den Götzendienst! ^{[[#fn15][15]]}

<<v15>>
15 Ich rede doch zu verständigen Menschen; urteilt selbst über das, was
ich sage.

<<v16>>
16 Ist der Kelch des Segens, über den wir den Segen sprechen, nicht
Teilhabe am Blut Christi? Ist das Brot, das wir brechen, nicht Teilhabe
am Leib Christi? ^{[[#fn16][16]]}

<<v17>>
17 *Ein* Brot ist es. Darum sind wir viele *ein* Leib; denn wir alle
haben teil an dem einen Brot. ^{[[#fn17][17]]}

<<v18>>
18 Schaut auf das irdische Israel: Haben die, welche von den Opfern
essen, nicht teil am Altar? ^{[[#fn18][18]]}

<<v19>>
19 Was meine ich damit? Ist denn Götzenopferfleisch wirklich etwas? Oder
ist ein Götze wirklich etwas? ^{[[#fn19][19]]}

<<v20>>
20 Nein, aber was man dort opfert, /opfert man/ nicht Gott, sondern /den
Dämonen./ Ich will jedoch nicht, dass ihr euch mit Dämonen einlasst.
^{[[#fn20][20]]}

<<v21>>
21 Ihr könnt nicht den Kelch des Herrn trinken und den Kelch der
Dämonen. Ihr könnt nicht Gäste sein am /Tisch des Herrn/ und am Tisch
der Dämonen. ^{[[#fn21][21]]}

<<v22>>
22 Oder wollen wir /die Eifersucht des Herrn wecken/? Sind wir stärker
als er? ^{[[#fn22][22]]}

<<v23>>
23 «Alles ist erlaubt» - aber nicht alles nützt. «Alles ist erlaubt» -
aber nicht alles baut auf. ^{[[#fn23][23]][[#fn24][24]]}

<<v24>>
24 Denkt dabei nicht an euch selbst, sondern an die anderen.
^{[[#fn25][25]]}

<<v25>>
25 Alles, was auf dem Fleischmarkt verkauft wird, das esst, ohne aus
Gewissenhaftigkeit nachzuforschen. ^{[[#fn26][26]]}

<<v26>>
26 Denn /dem Herrn gehört die Erde und was sie erfüllt./
^{[[#fn27][27]]}

<<v27>>
27 Wenn ein Ungläubiger euch einlädt und ihr hingehen möchtet, dann
esst, was euch vorgesetzt wird, ohne aus Gewissensgründen
nachzuforschen.

<<v28>>
28 Wenn euch aber jemand darauf hinweist: Das ist Opferfleisch!, dann
esst nicht davon, mit Rücksicht auf den, der euch aufmerksam macht, und
auf das Gewissen; ^{[[#fn28][28]]}

<<v29>>
29 ich meine das Gewissen des anderen, nicht das eigene; denn (an sich
gilt): Warum soll meine Freiheit vom Gewissensurteil eines anderen
abhängig sein?

<<v30>>
30 Wenn ich in Dankbarkeit mitesse, soll ich dann getadelt werden, dass
ich etwas esse, wofür ich Dank sage? ^{[[#fn29][29]]}

<<v31>>
31 Ob ihr also esst oder trinkt oder etwas anderes tut: Tut alles zur
Verherrlichung Gottes! ^{[[#fn30][30]]}

<<v32>>
32 Gebt weder Juden noch Griechen, noch der Kirche Gottes Anlass zu
einem Vorwurf! ^{[[#fn31][31]]}

<<v33>>
33 Auch ich suche allen in allem entgegenzukommen; ich suche nicht
meinen Nutzen, sondern den Nutzen aller, damit sie gerettet werden.

^{[[#fnm1][1]]} ℘ Ex 13,21; 14,22; Ps 78,13f; Röm 1,13

^{[[#fnm2][2]]} «auf Mose getauft werden» ist hier in Entsprechung zum
Getauftwerden «auf Christus» formuliert; es gibt keine derartige
jüdische Praxis.

^{[[#fnm3][3]]} ℘ Ex 16,4.35; Ps 78,24f

^{[[#fnm4][4]]} 3f: Paulus geht hier von der Vorstellung aus, dass
Christus, der ewige Gottessohn, dem Volk Israel auf seiner
Wüstenwanderung als Führer vorauszog und es durch seine göttliche
Wundermacht am Leben erhielt. Weil dieses Leben auch mit der
Wasserspende aus dem Felsen verbunden war, nennt er Christus den Leben
spendenden («pneumatischen») Felsen.

^{[[#fnm5][5]]} ℘ Ex 17,6; Num 20,7-11; Ps 78,15f

^{[[#fnm6][6]]} ℘ Num 14,16

^{[[#fnm7][7]]} ℘ Num 11,4.34

^{[[#fnm8][8]]} ℘ Ex 32,6

^{[[#fnm9][9]]} ℘ Num 25,1.9

^{[[#fnm10][10]]} ℘ Num 21,5f

^{[[#fnm11][11]]} ℘ Ex 16,2f; Num 14,2.36f; 17,6-14

^{[[#fnm12][12]]} ℘ 7,29; Röm 15,4; 1 Petr 4,7

^{[[#fnm13][13]]} ℘ Röm 11,20

^{[[#fnm14][14]]} ℘ 1,8f; 2 Thess 3,3; Jak 1,13f

^{[[#fnm15][15]]} ℘ 1 Joh 5,21

^{[[#fnm16][16]]} ℘ 11,24f

^{[[#fnm17][17]]} ℘ Apg 2,42; 1 Kor 12,27; Röm 12,5

^{[[#fnm18][18]]} ℘ Lev 7,6.15f; Dtn 18,1-4

^{[[#fnm19][19]]} ℘ 8,4

^{[[#fnm20][20]]} ℘ Ps 106,37

^{[[#fnm21][21]]} ℘ 2 Kor 6,15f; Mal 1,7.12

^{[[#fnm22][22]]} ℘ Dtn 32,21

^{[[#fnm23][23]]} ℘ 6,12

^{[[#fnm24][24]]} Vgl. die Anmerkung zu 6,12.

^{[[#fnm25][25]]} ℘ Röm 15,2; Phil 2,4

^{[[#fnm26][26]]} ℘ Röm 14,2-10

^{[[#fnm27][27]]} ℘ Ps 24,1

^{[[#fnm28][28]]} ℘ 8,7

^{[[#fnm29][29]]} ℘ Röm 14,6; 1 Tim 4,3f

^{[[#fnm30][30]]} ℘ Kol 3,17

^{[[#fnm31][31]]} ℘ Röm 14,13
