:PROPERTIES:
:ID:       37c134d0-dc9c-4a2e-8cc8-c5e138d7ccc8
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief an die Korinther* --
[[file:1.Kor_1.html][1]] ... [[file:1.Kor_10.html][10]]
[[file:1.Kor_11.html][11]] *12* [[file:1.Kor_13.html][13]]
[[file:1.Kor_14.html][14]] ... [[file:1.Kor_16.html][16]]

--------------

* 1.Kor 12
  :PROPERTIES:
  :CUSTOM_ID: kor-12
  :END:

<<verses>>

<<v1>>
** Die Geistesgaben und das Leben der Christen: 12,1 - 14,40
   :PROPERTIES:
   :CUSTOM_ID: die-geistesgaben-und-das-leben-der-christen-121---1440
   :END:
**** Der eine Geist und die vielen Gaben: 12,1-11
     :PROPERTIES:
     :CUSTOM_ID: der-eine-geist-und-die-vielen-gaben-121-11
     :END:
1 Auch über die Gaben des Geistes möchte ich euch nicht in Unkenntnis
lassen, meine Brüder. ^{[[#fn1][1]]}

<<v2>>
2 Als ihr noch Heiden wart, zog es euch, wie ihr wisst, mit
unwiderstehlicher Gewalt zu den stummen Götzen. ^{[[#fn2][2]]}

<<v3>>
3 Darum erkläre ich euch: Keiner, der aus dem Geist Gottes redet, sagt:
Jesus sei verflucht! Und keiner kann sagen: Jesus ist der Herr!, wenn er
nicht aus dem Heiligen Geist redet. ^{[[#fn3][3]]}

<<v4>>
4 Es gibt verschiedene Gnadengaben, aber nur den einen Geist.
^{[[#fn4][4]]}

<<v5>>
5 Es gibt verschiedene Dienste, aber nur den einen Herrn.

<<v6>>
6 Es gibt verschiedene Kräfte, die wirken, aber nur den einen Gott: Er
bewirkt alles in allen. ^{[[#fn5][5]]}

<<v7>>
7 Jedem aber wird die Offenbarung des Geistes geschenkt, damit sie
anderen nützt. ^{[[#fn6][6]]}

<<v8>>
8 Dem einen wird vom Geist die Gabe geschenkt, Weisheit mitzuteilen, dem
andern durch den gleichen Geist die Gabe, Erkenntnis zu vermitteln,

<<v9>>
9 dem dritten im gleichen Geist Glaubenskraft, einem andern - immer in
dem einen Geist - die Gabe, Krankheiten zu heilen,

<<v10>>
10 einem andern Wunderkräfte, einem andern prophetisches Reden, einem
andern die Fähigkeit, die Geister zu unterscheiden, wieder einem andern
verschiedene Arten von Zungenrede, einem andern schließlich die Gabe,
sie zu deuten. ^{[[#fn7][7]]}

<<v11>>
11 Das alles bewirkt ein und derselbe Geist; einem jeden teilt er seine
besondere Gabe zu, wie er will. ^{[[#fn8][8]]}\\
\\

<<v12>>
**** Der eine Leib und die vielen Glieder: 12,12-31a
     :PROPERTIES:
     :CUSTOM_ID: der-eine-leib-und-die-vielen-glieder-1212-31a
     :END:
12 Denn wie der Leib eine Einheit ist, doch viele Glieder hat, alle
Glieder des Leibes aber, obgleich es viele sind, einen einzigen Leib
bilden: So ist es auch mit Christus. ^{[[#fn9][9]]}

<<v13>>
13 Durch den einen Geist wurden wir in der Taufe alle in einen einzigen
Leib aufgenommen, Juden und Griechen, Sklaven und Freie; und alle wurden
wir mit dem einen Geist getränkt. ^{[[#fn10][10]]}

<<v14>>
14 Auch der Leib besteht nicht nur aus *einem* Glied, sondern aus vielen
Gliedern.

<<v15>>
15 Wenn der Fuß sagt: Ich bin keine Hand, ich gehöre nicht zum Leib!, so
gehört er doch zum Leib.

<<v16>>
16 Und wenn das Ohr sagt: Ich bin kein Auge, ich gehöre nicht zum Leib!,
so gehört es doch zum Leib.

<<v17>>
17 Wenn der ganze Leib nur Auge wäre, wo bliebe dann das Gehör? Wenn er
nur Gehör wäre, wo bliebe dann der Geruchssinn?

<<v18>>
18 Nun aber hat Gott jedes einzelne Glied so in den Leib eingefügt, wie
es seiner Absicht entsprach.

<<v19>>
19 Wären alle zusammen nur *ein* Glied, wo bliebe dann der Leib?

<<v20>>
20 So aber gibt es viele Glieder und doch nur *einen* Leib.

<<v21>>
21 Das Auge kann nicht zur Hand sagen: Ich bin nicht auf dich
angewiesen. Der Kopf kann nicht zu den Füßen sagen: Ich brauche euch
nicht.

<<v22>>
22 Im Gegenteil, gerade die schwächer scheinenden Glieder des Leibes
sind unentbehrlich.

<<v23>>
23 Denen, die wir für weniger edel ansehen, erweisen wir umso mehr Ehre
und unseren weniger anständigen Gliedern begegnen wir mit mehr Anstand,

<<v24>>
24 während die anständigen das nicht nötig haben. Gott aber hat den Leib
so zusammengefügt, dass er dem geringsten Glied mehr Ehre zukommen ließ,

<<v25>>
25 damit im Leib kein Zwiespalt entstehe, sondern alle Glieder
einträchtig füreinander sorgen.

<<v26>>
26 Wenn darum *ein* Glied leidet, leiden alle Glieder mit; wenn ein
Glied geehrt wird, freuen sich alle anderen mit ihm. ^{[[#fn11][11]]}

<<v27>>
27 Ihr aber seid der Leib Christi und jeder Einzelne ist ein Glied an
ihm. ^{[[#fn12][12]]}

<<v28>>
28 So hat Gott in der Kirche die einen als Apostel eingesetzt, die
andern als Propheten, die dritten als Lehrer; ferner verlieh er die
Kraft, Wunder zu tun, sodann die Gaben, Krankheiten zu heilen, zu
helfen, zu leiten, endlich die verschiedenen Arten von Zungenrede.
^{[[#fn13][13]]}

<<v29>>
29 Sind etwa alle Apostel, alle Propheten, alle Lehrer? Haben alle die
Kraft, Wunder zu tun?

<<v30>>
30 Besitzen alle die Gabe, Krankheiten zu heilen? Reden alle in Zungen?
Können alle solches Reden auslegen?

<<v31a>>
31a Strebt aber nach den höheren Gnadengaben! ^{[[#fn14][14]]}

<<v31b>>
**** Die höheren Gnadengaben - das Hohelied der Liebe: 12,31b - 13,13
     :PROPERTIES:
     :CUSTOM_ID: die-höheren-gnadengaben---das-hohelied-der-liebe-1231b---1313
     :END:
31b Ich zeige euch jetzt noch einen anderen Weg, einen, der alles
übersteigt:\\
\\

^{[[#fnm1][1]]} ℘ 14,1

^{[[#fnm2][2]]} ℘ Gal 4,8

^{[[#fnm3][3]]} ℘ 1 Joh 4,2f; Röm 10,9

^{[[#fnm4][4]]} ℘ Röm 12,6; Eph 4,4

^{[[#fnm5][5]]} ℘ 8,6; Eph 4,6

^{[[#fnm6][6]]} ℘ 14,26

^{[[#fnm7][7]]} Das «prophetische Reden», meint ein Reden aufgrund
göttlicher Eingebung, das in verständlicher Form die christliche
Botschaft auf die Nöte und Aufgaben der Gemeinde anwendet. - Zur
«Unterscheidung der Geister» vgl. 2,10-15; 14,29.32; 1 Thess 5,21. -
Beim «Zungenreden» handelt es sich um ein meist unverständliches
Stammeln zum Lob Gottes, bei dem der Mensch vom Geist Gottes ergriffen
ist. Für die Deutung des Zungenredens war eine eigene «Gnadengabe»
(griechisch: Charisma) erforderlich (vgl. Apg 2,4; 10,46; 19,6).

^{[[#fnm8][8]]} ℘ 7,7; Röm 12,3; Eph 4,7-12; 1 Petr 4,10

^{[[#fnm9][9]]} ℘ 10,17; Röm 12,4f

^{[[#fnm10][10]]} ℘ Gal 3,28

^{[[#fnm11][11]]} ℘ Röm 12,15

^{[[#fnm12][12]]} ℘ Röm 12,5; Eph 5,30

^{[[#fnm13][13]]} ℘ 12,8-10; Eph 4,11f

^{[[#fnm14][14]]} ℘ 14,1
