:PROPERTIES:
:ID:       ff393108-fe4a-4af4-9014-57a5429a9117
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief an die Korinther* --
[[file:1.Kor_1.html][1]] ... [[file:1.Kor_11.html][11]]
[[file:1.Kor_12.html][12]] *13* [[file:1.Kor_14.html][14]]
[[file:1.Kor_15.html][15]] [[file:1.Kor_16.html][16]]

--------------

* 1.Kor 13
  :PROPERTIES:
  :CUSTOM_ID: kor-13
  :END:

<<verses>>

<<v1>>
1 Wenn ich in den Sprachen der Menschen und Engel redete, /\\
 hätte aber die Liebe nicht, /\\
 wäre ich dröhnendes Erz oder eine lärmende Pauke. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Und wenn ich prophetisch reden könnte /\\
 und alle Geheimnisse wüsste /\\
 und alle Erkenntnis hätte; /\\
 wenn ich alle Glaubenskraft besäße /\\
 und Berge damit versetzen könnte, /\\
 hätte aber die Liebe nicht, /\\
 wäre ich nichts. ^{[[#fn2][2]]}\\
\\

<<v3>>
3 Und wenn ich meine ganze Habe verschenkte /\\
 und wenn ich meinen Leib dem Feuer übergäbe, /\\
 hätte aber die Liebe nicht, /\\
 nützte es mir nichts. ^{[[#fn3][3]]}\\
\\

<<v4>>
4 Die Liebe ist langmütig, /\\
 die Liebe ist gütig. /\\
 Sie ereifert sich nicht, /\\
 sie prahlt nicht, /\\
 sie bläht sich nicht auf. ^{[[#fn4][4]]}\\
\\

<<v5>>
5 Sie handelt nicht ungehörig, /\\
 sucht nicht ihren Vorteil, /\\
 lässt sich nicht zum Zorn reizen, /\\
 trägt das Böse nicht nach.\\
\\

<<v6>>
6 Sie freut sich nicht über das Unrecht, /\\
 sondern freut sich an der Wahrheit. ^{[[#fn5][5]]}\\
\\

<<v7>>
7 Sie erträgt alles, /\\
 glaubt alles, /\\
 hofft alles, /\\
 hält allem stand. ^{[[#fn6][6]]}\\
\\

<<v8>>
8 Die Liebe hört niemals auf. /\\
 Prophetisches Reden hat ein Ende, /\\
 Zungenrede verstummt, /\\
 Erkenntnis vergeht.\\
\\

<<v9>>
9 Denn Stückwerk ist unser Erkennen, /\\
 Stückwerk unser prophetisches Reden;\\
\\

<<v10>>
10 wenn aber das Vollendete kommt, /\\
 vergeht alles Stückwerk.\\
\\

<<v11>>
11 Als ich ein Kind war, /\\
 redete ich wie ein Kind, /\\
 dachte wie ein Kind /\\
 und urteilte wie ein Kind. Als ich ein Mann wurde, /\\
 legte ich ab, was Kind an mir war.\\
\\

<<v12>>
12 Jetzt schauen wir in einen Spiegel /\\
 und sehen nur rätselhafte Umrisse, /\\
 dann aber schauen wir von Angesicht zu Angesicht. Jetzt erkenne ich
unvollkommen, /\\
 dann aber werde ich durch und durch erkennen, /\\
 so wie ich auch durch und durch erkannt worden bin.\\
\\

<<v13>>
13 Für jetzt bleiben Glaube, Hoffnung, Liebe, diese drei; /\\
 doch am größten unter ihnen ist die Liebe. ^{[[#fn7][7]]}\\
\\

^{[[#fnm1][1]]} ℘ 14,6-8

^{[[#fnm2][2]]} ℘ 14,3.5; Mt 7,22; 17,20; 21,22; Mk 11,23

^{[[#fnm3][3]]} ℘ Mt 19,21

^{[[#fnm4][4]]} ℘ Röm 13,8-10

^{[[#fnm5][5]]} ℘ Röm 12,9

^{[[#fnm6][6]]} ℘ Spr 10,12

^{[[#fnm7][7]]} ℘ Hebr 10,22-24; Kol 3,14
