:PROPERTIES:
:ID:       8896ca68-c007-464b-81c8-8725d40eb34a
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief an die Korinther* --
[[file:1.Kor_1.html][1]] ... [[file:1.Kor_6.html][6]]
[[file:1.Kor_7.html][7]] *8* [[file:1.Kor_9.html][9]]
[[file:1.Kor_10.html][10]] ... [[file:1.Kor_16.html][16]]

--------------

* 1.Kor 8
  :PROPERTIES:
  :CUSTOM_ID: kor-8
  :END:

<<verses>>

<<v1>>
** Heidnische Opfer, christliche Sakramente, christlicher Gottesdienst:
8,1 - 11,34
   :PROPERTIES:
   :CUSTOM_ID: heidnische-opfer-christliche-sakramente-christlicher-gottesdienst-81---1134
   :END:
**** Die Freiheit des Christen: 8,1-13
     :PROPERTIES:
     :CUSTOM_ID: die-freiheit-des-christen-81-13
     :END:
1 Nun zur Frage des Götzenopferfleisches. Gewiss, wir alle haben
Erkenntnis. Doch die Erkenntnis macht aufgeblasen, die Liebe dagegen
baut auf. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Wenn einer meint, er sei zur Erkenntnis gelangt, hat er noch nicht so
erkannt, wie man erkennen muss. ^{[[#fn3][3]]}

<<v3>>
3 Wer aber Gott liebt, der ist von ihm erkannt. ^{[[#fn4][4]]}

<<v4>>
4 Was nun das Essen von Götzenopferfleisch angeht, so wissen wir, dass
es keine Götzen gibt in der Welt und keinen Gott außer dem einen.
^{[[#fn5][5]]}

<<v5>>
5 Und selbst wenn es im Himmel oder auf der Erde sogenannte Götter
gibt - und solche Götter und Herren gibt es viele -,

<<v6>>
6 so haben doch wir nur einen Gott, den Vater. Von ihm stammt alles und
wir leben auf ihn hin. Und einer ist der Herr: Jesus Christus. Durch ihn
ist alles, und wir sind durch ihn. ^{[[#fn6][6]]}

<<v7>>
7 Aber nicht alle haben die Erkenntnis. Einige, die von ihren Götzen
nicht loskommen, essen das Fleisch noch als Götzenopferfleisch und so
wird ihr schwaches Gewissen befleckt. ^{[[#fn7][7]]}

<<v8>>
8 Zwar kann uns keine Speise vor Gottes Gericht bringen. Wenn wir nicht
essen, verlieren wir nichts, und wenn wir essen, gewinnen wir nichts.

<<v9>>
9 Doch gebt Acht, dass diese eure Freiheit nicht den Schwachen zum
Anstoß wird. ^{[[#fn8][8]]}

<<v10>>
10 Wenn nämlich einer dich, der du Erkenntnis hast, im Götzentempel beim
Mahl sieht, wird dann nicht sein Gewissen, da er schwach ist, verleitet,
auch Götzenopferfleisch zu essen?

<<v11>>
11 Der Schwache geht an deiner «Erkenntnis» zugrunde, er, dein Bruder,
für den Christus gestorben ist.

<<v12>>
12 Wenn ihr euch auf diese Weise gegen eure Brüder versündigt und ihr
schwaches Gewissen verletzt, versündigt ihr euch gegen Christus.

<<v13>>
13 Wenn darum eine Speise meinem Bruder zum Anstoß wird, will ich
überhaupt kein Fleisch mehr essen, um meinem Bruder keinen Anstoß zu
geben.\\
\\

^{[[#fnm1][1]]} ℘ (1-13) Röm 14,1-23; Apg 15,29

^{[[#fnm2][2]]} macht aufgeblasen: Paulus richtet sich gegen eine
selbstherrliche, also falsche «Erkenntnis». - «Aufbauen» meint hier (wie
10,23; 14,3-5.12.17.26) alles, was das brüderliche Einvernehmen unter
den Gliedern der Gemeinde fördert.

^{[[#fnm3][3]]} ℘ Gal 6,3

^{[[#fnm4][4]]} ℘ 13,12; Gal 4,9

^{[[#fnm5][5]]} ℘ 10,19f

^{[[#fnm6][6]]} ℘ Röm 11,36; Kol 1,16f

^{[[#fnm7][7]]} ℘ 10,27f

^{[[#fnm8][8]]} ℘ Gal 5,13
