:PROPERTIES:
:ID:       bf7874ca-47d3-4a30-b3a4-e2904c63cc8d
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief des Petrus* --
[[file:1.Petr_1.html][1]] [[file:1.Petr_2.html][2]]
[[file:1.Petr_3.html][3]] *4* [[file:1.Petr_5.html][5]]

--------------

* 1.Petr 4
  :PROPERTIES:
  :CUSTOM_ID: petr-4
  :END:

<<verses>>

<<v1>>
1 Da Christus im Fleisch gelitten hat, wappnet auch ihr euch mit diesem
Gedanken: Wer im Fleisch gelitten hat, für den hat die Sünde ein Ende.
^{[[#fn1][1]]}

<<v2>>
2 Darum richtet euch, solange ihr noch auf Erden lebt, nicht mehr nach
den menschlichen Begierden, sondern nach dem Willen Gottes!

<<v3>>
3 Denn lange genug habt ihr in der vergangenen Zeit das heidnische
Treiben mitgemacht und habt ein ausschweifendes Leben voller Begierden
geführt, habt getrunken, geprasst, gezecht und unerlaubten Götzenkult
getrieben. ^{[[#fn2][2]]}

<<v4>>
4 Jetzt erregt es ihren Unwillen und sie lästern, weil ihr euch nicht
mehr in diesen Strudel der Leidenschaften hineinreißen lasst.

<<v5>>
5 Aber sie werden vor dem Rechenschaft ablegen müssen, der schon
bereitsteht, um die Lebenden und die Toten zu richten. ^{[[#fn3][3]]}

<<v6>>
6 Denn auch Toten ist das Evangelium dazu verkündet worden, dass sie wie
Menschen gerichtet werden im Fleisch, aber wie Gott das Leben haben im
Geist.

<<v7>>
7 Das Ende aller Dinge ist nahe. Seid also besonnen und nüchtern und
betet! ^{[[#fn4][4]][[#fn5][5]]}

<<v8>>
8 Vor allem haltet fest an der Liebe zueinander; denn /die Liebe deckt/
viele /Sünden zu./ ^{[[#fn6][6]]}

<<v9>>
9 Seid untereinander gastfreundlich, ohne zu murren.

<<v10>>
10 Dient einander als gute Verwalter der vielfältigen Gnade Gottes,
jeder mit der Gabe, die er empfangen hat. ^{[[#fn7][7]]}

<<v11>>
11 Wer redet, der rede mit den Worten, die Gott ihm gibt; wer dient, der
diene aus der Kraft, die Gott verleiht. So wird in allem Gott
verherrlicht durch Jesus Christus. Sein ist die Herrlichkeit und die
Macht in alle Ewigkeit. Amen. ^{[[#fn8][8]]}\\
\\

<<v12>>
** Abschließende Mahnungen: 4,12 - 5,11
   :PROPERTIES:
   :CUSTOM_ID: abschließende-mahnungen-412---511
   :END:
**** Ausdauer in der Prüfung: 4,12-19
     :PROPERTIES:
     :CUSTOM_ID: ausdauer-in-der-prüfung-412-19
     :END:
12 Liebe Brüder, lasst euch durch die Feuersglut, die zu eurer Prüfung
über euch gekommen ist, nicht verwirren, als ob euch etwas
Ungewöhnliches zustoße.

<<v13>>
13 Stattdessen freut euch, dass ihr Anteil an den Leiden Christi habt;
denn so könnt ihr auch bei der Offenbarung seiner Herrlichkeit voll
Freude jubeln. ^{[[#fn9][9]]}

<<v14>>
14 Wenn ihr wegen des Namens Christi beschimpft werdet, seid ihr selig
zu preisen; denn der Geist der Herrlichkeit, /der Geist Gottes, ruht/
auf euch. ^{[[#fn10][10]]}

<<v15>>
15 Wenn einer von euch leiden muss, soll es nicht deswegen sein, weil er
ein Mörder oder ein Dieb ist, weil er Böses tut oder sich in fremde
Angelegenheiten einmischt.

<<v16>>
16 Wenn er aber leidet, weil er Christ ist, dann soll er sich nicht
schämen, sondern Gott verherrlichen, indem er sich zu diesem Namen
bekennt. ^{[[#fn11][11]]}

<<v17>>
17 Denn jetzt ist die Zeit, in der das Gericht beim Haus Gottes beginnt;
wenn es aber bei uns anfängt, wie wird dann das Ende derer sein, die dem
Evangelium Gottes nicht gehorchen?

<<v18>>
18 Und /wenn der Gerechte kaum gerettet wird, wo wird man dann die
Frevler und Sünder finden/? ^{[[#fn12][12]]}

<<v19>>
19 Darum sollen alle, die nach dem Willen Gottes leiden müssen, Gutes
tun und dadurch ihr Leben dem treuen Schöpfer anbefehlen.\\
\\

^{[[#fnm1][1]]} ℘ Röm 6,10; Gal 5,24

^{[[#fnm2][2]]} ℘ Eph 2,2f; Tit 3,3

^{[[#fnm3][3]]} ℘ Apg 10,42; 2 Tim 4,1

^{[[#fnm4][4]]} ℘ Röm 13,11f; 1 Kor 7,29

^{[[#fnm5][5]]} Das «Ende aller Dinge» und das Ziel der Geschichte ist
die Offenbarung der Herrlichkeit Gottes am Tag Christi (vgl. die
Anmerkung zu 1,5).

^{[[#fnm6][6]]} ℘ Spr 10,12; Jak 5,20

^{[[#fnm7][7]]} ℘ Röm 12,6-8; 1 Kor 12,11

^{[[#fnm8][8]]} ℘ Jud 25

^{[[#fnm9][9]]} ℘ Apg 5,41

^{[[#fnm10][10]]} ℘ Mt 5,11f; Jes 11,2

^{[[#fnm11][11]]} Die Bezeichnung «Christ» kommt im Neuen Testament
sonst nur noch in Apg 11,26 und 26,28 vor. Sie ist den an Christus
Glaubenden wohl von Nichtchristen beigelegt worden.

^{[[#fnm12][12]]} ℘ Spr 11,31 G
