:PROPERTIES:
:ID:       4413001d-6163-497f-a21d-29c4a3a0cba9
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief des Petrus* --
[[file:1.Petr_1.html][1]] *2* [[file:1.Petr_3.html][3]]
[[file:1.Petr_4.html][4]] [[file:1.Petr_5.html][5]]

--------------

* 1.Petr 2
  :PROPERTIES:
  :CUSTOM_ID: petr-2
  :END:

<<verses>>

<<v1>>
**** Jesus Christus, der lebendige Stein: 2,1-10
     :PROPERTIES:
     :CUSTOM_ID: jesus-christus-der-lebendige-stein-21-10
     :END:
1 Legt also alle Bosheit ab, alle Falschheit und Heuchelei, allen Neid
und alle Verleumdung.

<<v2>>
2 Verlangt, gleichsam als neugeborene Kinder, nach der unverfälschten,
geistigen Milch, damit ihr durch sie heranwachst und das Heil erlangt.

<<v3>>
3 Denn ihr habt /erfahren, wie gütig der Herr ist./ ^{[[#fn1][1]]}

<<v4>>
4 Kommt zu ihm, dem lebendigen /Stein,/ der von den Menschen verworfen,
aber von Gott /auserwählt und geehrt/ worden ist. ^{[[#fn2][2]]}

<<v5>>
5 Lasst euch als lebendige Steine zu einem geistigen Haus aufbauen, zu
einer heiligen Priesterschaft, um durch Jesus Christus geistige Opfer
darzubringen, die Gott gefallen.\\
\\

<<v6>>
6 Denn es heißt in der Schrift: /Seht her, ich lege in Zion einen
auserwählten Stein,/ /\\
 /einen Eckstein, den ich in Ehren halte;/ /\\
 /wer an ihn glaubt, der geht nicht zugrunde./ ^{[[#fn3][3]]}\\
\\

<<v7>>
7 Euch, die ihr glaubt, gilt diese Ehre. Für jene aber, die nicht
glauben, ist dieser /Stein, den die Bauleute verworfen haben, zum
Eckstein geworden,/ ^{[[#fn4][4]]}

<<v8>>
8 /zum Stein, an den man anstößt, und zum Felsen, an dem man zu Fall
kommt./ Sie stoßen sich an ihm, weil sie dem Wort nicht gehorchen; doch
dazu sind sie bestimmt.

<<v9>>
9 Ihr aber seid /ein auserwähltes Geschlecht, eine königliche
Priesterschaft, ein heiliger Stamm, ein Volk, das sein besonderes
Eigentum wurde, damit ihr die großen Taten dessen verkündet,/ der euch
aus der Finsternis in sein wunderbares Licht gerufen hat.
^{[[#fn5][5]][[#fn6][6]]}

<<v10>>
10 Einst wart ihr /nicht sein Volk,/ jetzt aber seid ihr /Gottes Volk;/
einst gab es für euch /kein Erbarmen,/ jetzt aber habt ihr /Erbarmen
gefunden./ ^{[[#fn7][7]]}\\
\\

<<v11>>
** Christliches Leben in Familie und Gesellschaft: 2,11 - 4,11
   :PROPERTIES:
   :CUSTOM_ID: christliches-leben-in-familie-und-gesellschaft-211---411
   :END:
**** Der Christ im Staat: 2,11-17
     :PROPERTIES:
     :CUSTOM_ID: der-christ-im-staat-211-17
     :END:
11 Liebe Brüder, da ihr Fremde und Gäste seid in dieser Welt, ermahne
ich euch: Gebt den irdischen Begierden nicht nach, die gegen die Seele
kämpfen. ^{[[#fn8][8]]}

<<v12>>
12 Führt unter den Heiden ein rechtschaffenes Leben, damit sie, die euch
jetzt als Übeltäter verleumden, durch eure guten Taten zur Einsicht
kommen und Gott preisen am Tag der Heimsuchung. ^{[[#fn9][9]]}

<<v13>>
13 Unterwerft euch um des Herrn willen jeder menschlichen Ordnung: dem
Kaiser, weil er über allen steht, ^{[[#fn10][10]][[#fn11][11]]}

<<v14>>
14 den Statthaltern, weil sie von ihm entsandt sind, um die zu
bestrafen, die Böses tun, und die auszuzeichnen, die Gutes tun.

<<v15>>
15 Denn es ist der Wille Gottes, dass ihr durch eure guten Taten die
Unwissenheit unverständiger Menschen zum Schweigen bringt.

<<v16>>
16 Handelt als Freie, aber nicht als solche, die die Freiheit als
Deckmantel für das Böse nehmen, sondern wie Knechte Gottes.

<<v17>>
17 Erweist allen Menschen Ehre, liebt die Brüder, fürchtet Gott und ehrt
den Kaiser! ^{[[#fn12][12]]}\\
\\

<<v18>>
**** Die Sklaven in der Nachfolge Christi: 2,18-25
     :PROPERTIES:
     :CUSTOM_ID: die-sklaven-in-der-nachfolge-christi-218-25
     :END:
18 Ihr Sklaven, ordnet euch in aller Ehrfurcht euren Herren unter, nicht
nur den guten und freundlichen, sondern auch den launenhaften.
^{[[#fn13][13]]}

<<v19>>
19 Denn es ist eine Gnade, wenn jemand deswegen Kränkungen erträgt und
zu Unrecht leidet, weil er sich in seinem Gewissen nach Gott richtet.

<<v20>>
20 Ist es vielleicht etwas Besonderes, wenn ihr wegen einer Verfehlung
Schläge erduldet? Wenn ihr aber recht handelt und trotzdem Leiden
erduldet, das ist eine Gnade in den Augen Gottes.

<<v21>>
21 Dazu seid ihr berufen worden; denn auch Christus hat für euch
gelitten und euch ein Beispiel gegeben, damit ihr seinen Spuren folgt.
^{[[#fn14][14]]}\\
\\

<<v22>>
22 /Er hat keine Sünde begangen/ /\\
 /und in seinem Mund war kein trügerisches Wort./
^{[[#fn15][15]][[#fn16][16]]}\\
\\

<<v23>>
23 Er wurde geschmäht, schmähte aber nicht; /\\
 er litt, drohte aber nicht, /\\
 sondern überließ seine Sache dem gerechten Richter.\\
\\

<<v24>>
24 Er hat unsere Sünden mit seinem Leib auf das Holz des Kreuzes
getragen, damit wir tot seien für die Sünden und für die Gerechtigkeit
leben. /Durch seine Wunden seid ihr geheilt./
^{[[#fn17][17]][[#fn18][18]]}

<<v25>>
25 Denn ihr hattet euch /verirrt wie Schafe,/ jetzt aber seid ihr
heimgekehrt zum Hirten und Bischof eurer Seelen. ^{[[#fn19][19]]}\\
\\

^{[[#fnm1][1]]} ℘ Ps 34,9

^{[[#fnm2][2]]} ℘ Jes 28,16 G

^{[[#fnm3][3]]} ℘ Jes 28,16 G

^{[[#fnm4][4]]} ℘ Ps 118,22; Apg 4,11; Jes 8,14

^{[[#fnm5][5]]} ℘ Ex 19,5f G; 23,22 G; Jes 43,20f

^{[[#fnm6][6]]} Der Vers ist die grundlegende neutestamentliche Stelle
über das Priestertum aller Gläubigen.

^{[[#fnm7][7]]} ℘ Hos 1,6.9; 2,3.25

^{[[#fnm8][8]]} ℘ Ps 39,13; 119,19

^{[[#fnm9][9]]} Tag der Heimsuchung: Tag der Gnade, der Bekehrung (Lk
1,68; 19,44); auch: Tag des Gerichts (Jes 10,3).

^{[[#fnm10][10]]} ℘ (13-17) Röm 13,1-7; Tit 3,1

^{[[#fnm11][11]]} jeder menschlichen Ordnung, wörtlich: jedem
menschlichen Geschöpf.

^{[[#fnm12][12]]} ℘ Spr 24,21; Röm 12,10

^{[[#fnm13][13]]} ℘ Kol 3,22f; Tit 2,9f

^{[[#fnm14][14]]} ℘ Mk 8,34; Lk 9,23; Mt 10,25; Phil 2,5

^{[[#fnm15][15]]} ℘ Jes 53,9

^{[[#fnm16][16]]} 22-25: Der Verfasser greift hier auf ein
urchristliches Bekenntnis zurück (vgl. 1,18-21), das in Anlehnung an Jes
53 formuliert ist.

^{[[#fnm17][17]]} ℘ Jes 53,11f; Jes 53,5f

^{[[#fnm18][18]]} Wörtlich: auf das Holz hinaufgetragen; vgl. Apg 5,30;
Gal 3,13.

^{[[#fnm19][19]]} Christus wird als Hirt und Bischof bezeichnet; das
Wort für «Bischof» (Hüter) ist in der Kirche früh zum Amtstitel
geworden; vgl. die Anmerkung zu 1 Tim 3,1.
