:PROPERTIES:
:ID:       c46436a6-70d8-445f-a0de-e9fb02af8f0f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief an die Thessalonicher* --
[[file:1.Thess_1.html][1]] ... [[file:1.Thess_3.html][3]]
[[file:1.Thess_4.html][4]] *5*

--------------

* 1.Thess 5
  :PROPERTIES:
  :CUSTOM_ID: thess-5
  :END:

<<verses>>

<<v1>>
**** Aufforderung zur Bereitschaft für den Tag des Herrn: 5,1-11
     :PROPERTIES:
     :CUSTOM_ID: aufforderung-zur-bereitschaft-für-den-tag-des-herrn-51-11
     :END:
1 Über Zeit und Stunde, Brüder, brauche ich euch nicht zu schreiben.

<<v2>>
2 Ihr selbst wisst genau, dass der Tag des Herrn kommt wie ein Dieb in
der Nacht. ^{[[#fn1][1]]}

<<v3>>
3 Während die Menschen sagen: Friede und Sicherheit!, kommt plötzlich
Verderben über sie wie die Wehen über eine schwangere Frau, und es gibt
kein Entrinnen. ^{[[#fn2][2]]}

<<v4>>
4 Ihr aber, Brüder, lebt nicht im Finstern, sodass euch der Tag nicht
wie ein Dieb überraschen kann.

<<v5>>
5 Ihr alle seid Söhne des Lichts und Söhne des Tages. Wir gehören nicht
der Nacht und nicht der Finsternis.

<<v6>>
6 Darum wollen wir nicht schlafen wie die anderen, sondern wach und
nüchtern sein. ^{[[#fn3][3]]}

<<v7>>
7 Denn wer schläft, schläft bei Nacht, und wer sich betrinkt, betrinkt
sich bei Nacht.

<<v8>>
8 Wir aber, die dem Tag gehören, wollen nüchtern sein und uns rüsten mit
/dem Panzer/ des Glaubens und der Liebe und mit /dem Helm/ der Hoffnung
auf /das Heil./ ^{[[#fn4][4]]}

<<v9>>
9 Denn Gott hat uns nicht für das Gericht seines Zorns bestimmt, sondern
dafür, dass wir durch Jesus Christus, unseren Herrn, das Heil erlangen.
^{[[#fn5][5]]}

<<v10>>
10 Er ist für uns gestorben, damit wir vereint mit ihm leben, ob wir nun
wachen oder schlafen. ^{[[#fn6][6]][[#fn7][7]]}

<<v11>>
11 Darum tröstet und ermahnt einander und einer richte den andern auf,
wie ihr es schon tut.\\
\\

<<v12>>
**** Anweisungen für das Gemeindeleben: 5,12-22
     :PROPERTIES:
     :CUSTOM_ID: anweisungen-für-das-gemeindeleben-512-22
     :END:
12 Wir bitten euch, Brüder: Erkennt die unter euch an, die sich solche
Mühe geben, euch im Namen des Herrn zu leiten und zum Rechten
anzuhalten.

<<v13>>
13 Achtet sie hoch und liebt sie wegen ihres Wirkens! Haltet Frieden
untereinander! ^{[[#fn8][8]]}

<<v14>>
14 Wir ermahnen euch, Brüder: Weist die zurecht, die ein unordentliches
Leben führen, ermutigt die Ängstlichen, nehmt euch der Schwachen an,
seid geduldig mit allen!

<<v15>>
15 Seht zu, dass keiner dem andern Böses mit Bösem vergilt, sondern
bemüht euch immer, einander und allen Gutes zu tun. ^{[[#fn9][9]]}

<<v16>>
16 Freut euch zu jeder Zeit!

<<v17>>
17 Betet ohne Unterlass! ^{[[#fn10][10]]}\\
\\

<<v18>>
18 Dankt für alles; denn das will Gott von euch, /\\
 die ihr Christus Jesus gehört.\\
\\

<<v19>>
19 Löscht den Geist nicht aus!

<<v20>>
20 Verachtet prophetisches Reden nicht!

<<v21>>
21 Prüft alles und behaltet das Gute! ^{[[#fn11][11]]}

<<v22>>
22 Meidet das Böse in jeder Gestalt! ^{[[#fn12][12]]}\\
\\

<<v23>>
** Der Schluss des Briefes: Segen und Gruß: 5,23-28
   :PROPERTIES:
   :CUSTOM_ID: der-schluss-des-briefes-segen-und-gruß-523-28
   :END:
23 Der Gott des Friedens heilige euch ganz und gar und bewahre euren
Geist, eure Seele und euren Leib unversehrt, damit ihr ohne Tadel seid,
wenn Jesus Christus, unser Herr, kommt.

<<v24>>
24 Gott, der euch beruft, ist treu; er wird es tun. ^{[[#fn13][13]]}

<<v25>>
25 Brüder, betet auch für uns! ^{[[#fn14][14]]}

<<v26>>
26 Grüßt alle Brüder mit dem heiligen Kuss! ^{[[#fn15][15]]}

<<v27>>
27 Ich beschwöre euch beim Herrn, diesen Brief allen Brüdern vorzulesen.
^{[[#fn16][16]]}

<<v28>>
28 Die Gnade Jesu Christi, unseres Herrn, sei mit euch!\\
\\

^{[[#fnm1][1]]} ℘ Mt 24,43; Lk 12,39; 2 Petr 3,10; Offb 3,3; 16,15

^{[[#fnm2][2]]} ℘ Mt 24,38f; Lk 21,34f

^{[[#fnm3][3]]} ℘ Röm 13,11f

^{[[#fnm4][4]]} ℘ Jes 59,17; Weish 5,18f; Eph 6,14-17

^{[[#fnm5][5]]} ℘ 2 Thess 2,14

^{[[#fnm6][6]]} ℘ 4,14; Röm 14,8f

^{[[#fnm7][7]]} «Wachen» und «schlafen» beziehen sich hier nicht auf das
sittliche Verhalten wie im V. 6, sondern auf «leben» und «gestorben
sein».

^{[[#fnm8][8]]} ℘ 1 Kor 16,15f

^{[[#fnm9][9]]} ℘ Spr 20,22; Röm 12,17; 1 Petr 3,9

^{[[#fnm10][10]]} ℘ Lk 18,1; Röm 12,12; Eph 6,18; Kol 4,2

^{[[#fnm11][11]]} ℘ 1 Joh 4,1

^{[[#fnm12][12]]} ℘ Ijob 1,1.8; 2,3

^{[[#fnm13][13]]} ℘ 1 Kor 1,9; 2 Thess 3,3

^{[[#fnm14][14]]} ℘ 2 Thess 3,1

^{[[#fnm15][15]]} ℘ Röm 16,16

^{[[#fnm16][16]]} ℘ Kol 4,16
