:PROPERTIES:
:ID:       ef61e220-45bf-4a6e-b054-5fb422889ba1
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief an Timotheus* --
[[file:1.Tim_1.html][1]] ... [[file:1.Tim_3.html][3]]
[[file:1.Tim_4.html][4]] *5* [[file:1.Tim_6.html][6]]

--------------

* 1.Tim 5
  :PROPERTIES:
  :CUSTOM_ID: tim-5
  :END:

<<verses>>

<<v1>>
1 Einen älteren Mann sollst du nicht grob behandeln, sondern ihm zureden
wie einem Vater. Mit jüngeren Männern rede wie mit Brüdern,

<<v2>>
2 mit älteren Frauen wie mit Müttern, mit jüngeren wie mit Schwestern,
in aller Zurückhaltung.\\
\\

<<v3>>
**** Stand und Aufgabe der Witwen: 5,3-16
     :PROPERTIES:
     :CUSTOM_ID: stand-und-aufgabe-der-witwen-53-16
     :END:
3 Ehre die Witwen, wenn sie wirklich Witwen sind.

<<v4>>
4 Hat eine Witwe aber Kinder oder Enkel, dann sollen diese lernen,
zuerst selbst ihren Angehörigen Ehrfurcht zu erweisen und dankbar für
ihre Mutter oder Großmutter zu sorgen; denn das gefällt Gott.

<<v5>>
5 Eine Frau aber, die wirklich eine Witwe ist und allein steht, setzt
ihre Hoffnung auf Gott und betet beharrlich und inständig bei Tag und
Nacht.

<<v6>>
6 Wenn eine jedoch ein ausschweifendes Leben führt, ist sie schon bei
Lebzeiten tot.

<<v7>>
7 Das sollst du ihnen einprägen; dann wird man ihnen nichts vorwerfen
können.

<<v8>>
8 Wer aber für seine Verwandten, besonders für die eigenen Hausgenossen,
nicht sorgt, der verleugnet damit den Glauben und ist schlimmer als ein
Ungläubiger.

<<v9>>
9 Eine Frau soll nur dann in die Liste der Witwen aufgenommen werden,
wenn sie mindestens sechzig Jahre alt ist, nur einmal verheiratet war,
^{[[#fn1][1]]}

<<v10>>
10 wenn bekannt ist, dass sie Gutes getan hat, wenn sie Kinder
aufgezogen hat, gastfreundlich gewesen ist und den Heiligen die Füße
gewaschen hat, wenn sie denen, die in Not waren, geholfen hat und
überhaupt bemüht war, Gutes zu tun.

<<v11>>
11 Jüngere Witwen weise ab; denn wenn die Leidenschaft sie Christus
entfremdet, wollen sie heiraten

<<v12>>
12 und ziehen sich den Vorwurf zu, ihrem Versprechen (das sie Christus
gegeben haben) untreu geworden zu sein. ^{[[#fn2][2]]}

<<v13>>
13 Außerdem werden sie faul und gewöhnen sich daran, von Haus zu Haus zu
laufen. Aber nicht nur faul werden sie, sondern auch geschwätzig; sie
mischen sich in alles und reden über Dinge, die sie nichts angehen.

<<v14>>
14 Deshalb will ich, dass jüngere Witwen heiraten, Kinder zur Welt
bringen, den Haushalt versorgen und dem Gegner keinen Anlass zu übler
Nachrede geben.

<<v15>>
15 Einige haben sich schon abgewandt und sind dem Satan gefolgt.

<<v16>>
16 Wenn eine gläubige Frau Witwen in ihrem Haus hat, soll sie für sie
sorgen. Die Gemeinde soll nicht belastet werden, damit sie sich um die
kümmern kann, die wirklich Witwen sind.\\
\\

<<v17>>
**** Über die Ältesten: 5,17-22
     :PROPERTIES:
     :CUSTOM_ID: über-die-ältesten-517-22
     :END:
17 Älteste, die das Amt des Vorstehers gut versehen, verdienen doppelte
Anerkennung, besonders solche, die sich mit ganzer Kraft dem Wort und
der Lehre widmen. ^{[[#fn3][3]][[#fn4][4]]}

<<v18>>
18 Denn die Schrift sagt: /Du sollst dem Ochsen zum Dreschen keinen
Maulkorb anlegen,/ und: Wer arbeitet, hat ein Recht auf seinen Lohn.
^{[[#fn5][5]]}

<<v19>>
19 Nimm gegen einen Ältesten keine Klage an, außer /wenn zwei oder drei
Zeugen sie bekräftigen./ ^{[[#fn6][6]]}

<<v20>>
20 Wenn sich einer verfehlt, so weise ihn in Gegenwart aller zurecht,
damit auch die anderen sich fürchten.

<<v21>>
21 Ich beschwöre dich bei Gott, bei Christus Jesus und bei den
auserwählten Engeln: Befolge dies alles ohne Vorurteil und vermeide jede
Bevorzugung!

<<v22>>
22 Lege keinem vorschnell die Hände auf und mach dich nicht mitschuldig
an fremden Sünden; bewahre dich rein! ^{[[#fn7][7]]}\\
\\

<<v23>>
**** Verschiedene Mahnungen: 5,23-25
     :PROPERTIES:
     :CUSTOM_ID: verschiedene-mahnungen-523-25
     :END:
23 Trink nicht nur Wasser, sondern nimm auch etwas Wein, mit Rücksicht
auf deinen Magen und deine häufigen Krankheiten.

<<v24>>
24 Die Sünden mancher Leute liegen offen zutage, sie laufen ihnen
gleichsam voraus zum Gericht; bei anderen kommen sie erst hinterher.

<<v25>>
25 Ebenso liegen die guten Werke offen zutage, und wenn sie noch nicht
offenkundig sind, können sie doch nicht verborgen bleiben.\\
\\

^{[[#fnm1][1]]} Vgl. die Anmerkung zu 3,2.

^{[[#fnm2][2]]} ihrem Versprechen untreu geworden zu sein, wörtlich:
ihre erste Treue gebrochen zu haben.

^{[[#fnm3][3]]} ℘ 1 Petr 5,1-5

^{[[#fnm4][4]]} Über die Amtsträger in der Kirche vgl. die Anmerkung zu
3,1.

^{[[#fnm5][5]]} ℘ Dtn 25,4; Mt 10,10; Lk 10,7; 1 Kor 9,12-14

^{[[#fnm6][6]]} ℘ Dtn 19,15; Mt 18,16

^{[[#fnm7][7]]} Der Vers wird verschieden gedeutet: Handauflegung bei
der Einsetzung in das kirchliche Amt (Ordination); Aufnahme von
Taufanwärtern; Wiederaufnahme reuiger Sünder. Die erste Auffassung ist
die wahrscheinlichste.
