:PROPERTIES:
:ID:       fa8b2796-057d-47ac-8c36-1dc7d97eccf2
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der erste Brief an Timotheus* --
[[file:1.Tim_1.html][1]] *2* [[file:1.Tim_3.html][3]]
[[file:1.Tim_4.html][4]] ... [[file:1.Tim_6.html][6]]

--------------

* 1.Tim 2
  :PROPERTIES:
  :CUSTOM_ID: tim-2
  :END:

<<verses>>

<<v1>>
** Die rechte Ordnung in den Gemeinden: 2,1 - 6,19
   :PROPERTIES:
   :CUSTOM_ID: die-rechte-ordnung-in-den-gemeinden-21---619
   :END:
**** Gebet für alle Menschen: 2,1-7
     :PROPERTIES:
     :CUSTOM_ID: gebet-für-alle-menschen-21-7
     :END:
1 Vor allem fordere ich zu Bitten und Gebeten, zu Fürbitte und
Danksagung auf, und zwar für alle Menschen,

<<v2>>
2 für die Herrscher und für alle, die Macht ausüben, damit wir in aller
Frömmigkeit und Rechtschaffenheit ungestört und ruhig leben können.

<<v3>>
3 Das ist recht und gefällt Gott, unserem Retter; ^{[[#fn1][1]]}

<<v4>>
4 er will, dass alle Menschen gerettet werden und zur Erkenntnis der
Wahrheit gelangen.\\
\\

<<v5>>
5 Denn: Einer ist Gott, /\\
 Einer auch Mittler zwischen Gott und den Menschen: /\\
 der Mensch Christus Jesus,\\
\\

<<v6>>
6 der sich als Lösegeld hingegeben hat für alle, /\\
 ein Zeugnis zur vorherbestimmten Zeit, ^{[[#fn2][2]]}\\
\\

<<v7>>
7 als dessen Verkünder und Apostel ich eingesetzt wurde - ich sage die
Wahrheit und lüge nicht -, als Lehrer der Heiden im Glauben und in der
Wahrheit. ^{[[#fn3][3]]}\\
\\

<<v8>>
**** Männer und Frauen: 2,8-15
     :PROPERTIES:
     :CUSTOM_ID: männer-und-frauen-28-15
     :END:
8 Ich will, dass die Männer überall beim Gebet ihre Hände in Reinheit
erheben, frei von Zorn und Streit. ^{[[#fn4][4]]}

<<v9>>
9 Auch sollen die Frauen sich anständig, bescheiden und zurückhaltend
kleiden; nicht Haartracht, Gold, Perlen oder kostbare Kleider seien ihr
Schmuck, ^{[[#fn5][5]]}

<<v10>>
10 sondern gute Werke; so gehört es sich für Frauen, die gottesfürchtig
sein wollen.

<<v11>>
11 Eine Frau soll sich still und in aller Unterordnung belehren lassen.
^{[[#fn6][6]]}

<<v12>>
12 Dass eine Frau lehrt, erlaube ich nicht, auch nicht, dass sie über
ihren Mann herrscht; sie soll sich still verhalten.

<<v13>>
13 Denn zuerst wurde Adam erschaffen, danach Eva. ^{[[#fn7][7]]}

<<v14>>
14 Und nicht Adam wurde verführt, sondern die Frau ließ sich verführen
und übertrat das Gebot. ^{[[#fn8][8]]}

<<v15>>
15 Sie wird aber dadurch gerettet werden, dass sie Kinder zur Welt
bringt, wenn sie in Glaube, Liebe und Heiligkeit ein besonnenes Leben
führt. ^{[[#fn9][9]]}\\
\\

^{[[#fnm1][1]]} ℘ 1,1; 4,10; Tit 1,3; 2,10; 3,4

^{[[#fnm2][2]]} ℘ Mt 20,28; Mk 10,45; Gal 1,4; Tit 2,14

^{[[#fnm3][3]]} ℘ Gal 2,7; Eph 3,1; Kol 1,25-29

^{[[#fnm4][4]]} ℘ 1 Petr 3,7

^{[[#fnm5][5]]} ℘ 1 Petr 3,1-4

^{[[#fnm6][6]]} ℘ 1 Kor 14,33-35

^{[[#fnm7][7]]} ℘ Gen 2,7.22

^{[[#fnm8][8]]} ℘ Gen 3,13

^{[[#fnm9][9]]} Was hier über die Rolle der Frau gesagt ist, entspricht
überlieferter jüdischer Denkweise; es richtet sich aber auch gegen
gnostische Irrlehrer, die das Heiraten verbieten wollten (1 Tim 4,3).
