:PROPERTIES:
:ID:       2c62e619-a010-4d90-a56c-1b4125cfa1a2
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der zweite Brief an die Korinther* --
[[file:2.Kor_1.html][1]] ... [[file:2.Kor_9.html][9]]
[[file:2.Kor_10.html][10]] *11* [[file:2.Kor_12.html][12]]
[[file:2.Kor_13.html][13]]

--------------

* 2.Kor 11
  :PROPERTIES:
  :CUSTOM_ID: kor-11
  :END:

<<verses>>

<<v1>>
** Die Leistung des Apostels: 11,1 - 12,13
   :PROPERTIES:
   :CUSTOM_ID: die-leistung-des-apostels-111---1213
   :END:
**** Die Selbstlosigkeit des Apostels: 11,1-15
     :PROPERTIES:
     :CUSTOM_ID: die-selbstlosigkeit-des-apostels-111-15
     :END:
1 Lasst euch doch ein wenig Unverstand von mir gefallen! Aber das tut
ihr ja. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Denn ich liebe euch mit der Eifersucht Gottes; ich habe euch einem
einzigen Mann verlobt, um euch als reine Jungfrau zu Christus zu führen.
^{[[#fn3][3]]}

<<v3>>
3 Ich fürchte aber, wie die Schlange einst durch ihre Falschheit Eva
täuschte, könntet auch ihr in euren Gedanken von der aufrichtigen und
reinen Hingabe an Christus abkommen. ^{[[#fn4][4]]}

<<v4>>
4 Ihr nehmt es ja offenbar hin, wenn irgendeiner daherkommt und einen
anderen Jesus verkündigt, als wir verkündigt haben, wenn ihr einen
anderen Geist empfangt, als ihr empfangen habt, oder ein anderes
Evangelium, als ihr angenommen habt. ^{[[#fn5][5]]}

<<v5>>
5 Ich denke doch, ich stehe den Überaposteln keineswegs nach.
^{[[#fn6][6]]}

<<v6>>
6 Im Reden mag ich ein Stümper sein, aber nicht in der Erkenntnis; wir
haben sie euch in keiner Weise und in keinem Fall vorenthalten.
^{[[#fn7][7]]}

<<v7>>
7 Oder habe ich einen Fehler gemacht, als ich, um euch zu erhöhen, mich
selbst erniedrigte und euch das Evangelium Gottes verkündete, ohne etwas
dafür zu nehmen? ^{[[#fn8][8]]}

<<v8>>
8 Andere Gemeinden habe ich ausgeplündert und Geld von ihnen genommen,
um euch dienen zu können. ^{[[#fn9][9]]}

<<v9>>
9 Aber als ich zu euch kam und in Schwierigkeiten geriet, bin ich
niemand zur Last gefallen; was ich zu wenig hatte, ergänzten die Brüder,
die aus Mazedonien kamen. Ich habe also darauf Wert gelegt, euch in
keiner Weise zur Last zu fallen, und werde auch weiterhin darauf Wert
legen. ^{[[#fn10][10]]}

<<v10>>
10 So gewiss die Wahrheit Christi in mir ist: diesen Ruhm wird mir im
Gebiet von Achaia niemand nehmen. ^{[[#fn11][11]]}

<<v11>>
11 Warum? Liebe ich euch etwa nicht? Gott weiß es.

<<v12>>
12 Was ich aber tue, werde ich auch in Zukunft tun: Ich werde denen die
Gelegenheit nehmen, die nur die Gelegenheit suchen, sich Achtung zu
verschaffen, um so dazustehen wie wir. ^{[[#fn12][12]]}

<<v13>>
13 Denn diese Leute sind Lügenapostel, unehrliche Arbeiter; sie tarnen
sich freilich als Apostel Christi. ^{[[#fn13][13]]}

<<v14>>
14 Kein Wunder, denn auch der Satan tarnt sich als Engel des Lichts.

<<v15>>
15 Es ist also nicht erstaunlich, wenn sich auch seine Handlanger als
Diener der Gerechtigkeit tarnen. Ihr Ende wird ihren Taten entsprechen.
^{[[#fn14][14]]}\\
\\

<<v16>>
*** Die «Narrenrede»: 11,16 - 12,13
    :PROPERTIES:
    :CUSTOM_ID: die-narrenrede-1116---1213
    :END:
**** Die Leiden und Mühen des Apostels: 11,16-33
     :PROPERTIES:
     :CUSTOM_ID: die-leiden-und-mühen-des-apostels-1116-33
     :END:
16 Noch einmal sage ich: Keiner soll mich für einen Narren halten. Tut
ihr es aber doch, dann lasst mich auch als Narren gewähren, damit auch
ich ein wenig prahlen kann. ^{[[#fn15][15]]}

<<v17>>
17 Was ich hier sage, sage ich nicht im Sinn des Herrn, sondern
sozusagen als Narr im falschen Stolz des Prahlers.

<<v18>>
18 Da viele Menschen im Sinn dieser Welt prahlen, will auch ich einmal
prahlen. ^{[[#fn16][16]]}

<<v19>>
19 Ihr lasst euch die Narren ja gern gefallen, ihr klugen Leute.
^{[[#fn17][17]]}

<<v20>>
20 Denn ihr nehmt es hin, wenn euch jemand versklavt, ausbeutet und in
seine Gewalt bringt, wenn jemand anmaßend auftritt und euch ins Gesicht
schlägt.

<<v21>>
21 Zu meiner Schande muss ich gestehen: Dazu bin ich allerdings zu
schwach gewesen. Womit aber jemand prahlt - ich rede jetzt als Narr -,
damit kann auch ich prahlen.

<<v22>>
22 Sie sind Hebräer - ich auch. Sie sind Israeliten - ich auch. Sie sind
Nachkommen Abrahams - ich auch. ^{[[#fn18][18]]}

<<v23>>
23 Sie sind Diener Christi - jetzt rede ich ganz unvernünftig -, ich
noch mehr: Ich ertrug mehr Mühsal, war häufiger im Gefängnis, wurde mehr
geschlagen, war oft in Todesgefahr. ^{[[#fn19][19]]}

<<v24>>
24 Fünfmal erhielt ich von Juden die neununddreißig Hiebe;
^{[[#fn20][20]][[#fn21][21]]}

<<v25>>
25 dreimal wurde ich ausgepeitscht, einmal gesteinigt, dreimal erlitt
ich Schiffbruch, eine Nacht und einen Tag trieb ich auf hoher See.
^{[[#fn22][22]]}

<<v26>>
26 Ich war oft auf Reisen, gefährdet durch Flüsse, gefährdet durch
Räuber, gefährdet durch das eigene Volk, gefährdet durch Heiden,
gefährdet in der Stadt, gefährdet in der Wüste, gefährdet auf dem Meer,
gefährdet durch falsche Brüder.

<<v27>>
27 Ich erduldete Mühsal und Plage, durchwachte viele Nächte, ertrug
Hunger und Durst, häufiges Fasten, Kälte und Blöße. ^{[[#fn23][23]]}

<<v28>>
28 Um von allem andern zu schweigen, weise ich noch auf den täglichen
Andrang zu mir und die Sorge für alle Gemeinden hin. ^{[[#fn24][24]]}

<<v29>>
29 Wer leidet unter seiner Schwachheit, ohne dass ich mit ihm leide? Wer
kommt zu Fall, ohne dass ich von Sorge verzehrt werde? ^{[[#fn25][25]]}

<<v30>>
30 Wenn schon geprahlt sein muss, will ich mit meiner Schwachheit
prahlen. ^{[[#fn26][26]]}

<<v31>>
31 Gott, der Vater Jesu, des Herrn, er, der gepriesen ist in Ewigkeit,
weiß, dass ich nicht lüge.

<<v32>>
32 In Damaskus ließ der Statthalter des Königs Aretas die Stadt der
Damaszener bewachen, um mich festzunehmen. ^{[[#fn27][27]]}

<<v33>>
33 Aber durch ein Fenster wurde ich in einem Korb die Stadtmauer
hinuntergelassen und so entkam ich ihm.\\
\\

^{[[#fnm1][1]]} ℘ 11,16-18

^{[[#fnm2][2]]} 1-12,13: Paulus sieht sich gezwungen, auf seine
Leistungen hinzuweisen, um seinen Gegnern entgegenzutreten, die ihn
verächtlich zu machen suchen. Da dieses Eigenlob Paulus widerstrebt,
greift er zur Ironie und zur Form der sog. «Narrenrede» (vgl. 11,16).

^{[[#fnm3][3]]} ℘ Eph 5,26f

^{[[#fnm4][4]]} ℘ Gen 3,4.13

^{[[#fnm5][5]]} ℘ Gal 1,6-9

^{[[#fnm6][6]]} ℘ 11,13; 12,11

^{[[#fnm7][7]]} ℘ 10,10; 1 Kor 2,1f.13

^{[[#fnm8][8]]} ℘ 1 Kor 9,12f

^{[[#fnm9][9]]} ℘ Phil 4,10.15

^{[[#fnm10][10]]} ℘ 12,13

^{[[#fnm11][11]]} ℘ 1 Kor 9,15

^{[[#fnm12][12]]} ℘ 2,17; Phil 3,2

^{[[#fnm13][13]]} ℘ Offb 2,2

^{[[#fnm14][14]]} ℘ Phil 3,19; 2 Tim 4,14

^{[[#fnm15][15]]} ℘ 11,1; 12,6

^{[[#fnm16][16]]} ℘ Phil 3,4

^{[[#fnm17][17]]} ℘ 1 Kor 4,10

^{[[#fnm18][18]]} ℘ Apg 22,3; Röm 11,1; Phil 3,5

^{[[#fnm19][19]]} ℘ 1 Kor 4,1; 15,10

^{[[#fnm20][20]]} ℘ Dtn 25,3

^{[[#fnm21][21]]} Nach Dtn 25,3 waren vierzig Schläge das Höchstmaß
einer vom Richter verhängten Züchtigung. Um diese Zahl auf keinen Fall
zu überschreiten, pflegte man nur neununddreißig Schläge zu geben.

^{[[#fnm22][22]]} ℘ Apg 16,22; 14,19; 27,41-43

^{[[#fnm23][23]]} ℘ 6,4f; 1 Kor 4,11; 1 Thess 2,9

^{[[#fnm24][24]]} ℘ Apg 20,31

^{[[#fnm25][25]]} ℘ 1 Kor 9,22

^{[[#fnm26][26]]} ℘ 12,5.9f

^{[[#fnm27][27]]} ℘ Apg 9,24f
