:PROPERTIES:
:ID:       90ab74a8-de65-4dcd-8b1a-e449ef956e16
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der zweite Brief an die Korinther* --
[[file:2.Kor_1.html][1]] ... [[file:2.Kor_5.html][5]]
[[file:2.Kor_6.html][6]] *7* [[file:2.Kor_8.html][8]]
[[file:2.Kor_9.html][9]] ... [[file:2.Kor_13.html][13]]

--------------

* 2.Kor 7
  :PROPERTIES:
  :CUSTOM_ID: kor-7
  :END:

<<verses>>

<<v1>>
1 Das sind die Verheißungen, die wir haben, liebe Brüder. Reinigen wir
uns also von aller Unreinheit des Leibes und des Geistes und streben wir
in Gottesfurcht nach vollkommener Heiligung. ^{[[#fn1][1]]}

<<v2>>
2 Gebt uns doch Raum in eurem Herzen! Niemand haben wir geschädigt,
niemand zugrunde gerichtet, niemand übervorteilt. ^{[[#fn2][2]]}

<<v3>>
3 Ich sage das nicht, um euch zu verurteilen; denn eben habe ich gesagt,
dass ihr in unserem Herzen wohnt, verbunden mit uns zum Leben und zum
Sterben. ^{[[#fn3][3]]}

<<v4>>
4 Ich habe großes Vertrauen zu euch; ich bin sehr stolz auf euch. Trotz
all unserer Not bin ich von Trost erfüllt und ströme über von Freude.\\
\\

<<v5>>
**** Die Sendung des Titus: 7,5-16
     :PROPERTIES:
     :CUSTOM_ID: die-sendung-des-titus-75-16
     :END:
5 Als wir nach Mazedonien gekommen waren, fanden wir in unserer
Schwachheit keine Ruhe. Überall bedrängten uns Schwierigkeiten: von
außen Widerspruch und Anfeindung, im Innern Angst und Furcht.
^{[[#fn4][4]][[#fn5][5]]}

<<v6>>
6 Aber Gott, der die Niedergeschlagenen aufrichtet, hat auch uns
aufgerichtet, und zwar durch die Ankunft des Titus - ^{[[#fn6][6]]}

<<v7>>
7 nicht nur durch seine Ankunft, sondern auch durch den Trost, den er
bei euch erfahren hatte. Er erzählte uns von eurer Sehnsucht, eurer
Klage, eurem Eifer für mich, sodass ich mich noch mehr freute.
^{[[#fn7][7]]}

<<v8>>
8 Dass ich euch aber mit meinem Brief traurig gemacht habe, tut mir
nicht Leid. Wenn es mir auch eine Weile Leid tat - ich sehe ja, dass
dieser Brief euch, wenn auch nur für kurze Zeit, traurig gemacht hat -:
^{[[#fn8][8]]}

<<v9>>
9 jetzt freue ich mich, nicht weil ihr traurig geworden seid, sondern
weil die Traurigkeit euch zur Sinnesänderung geführt hat. Denn es war
eine gottgewollte Traurigkeit; so ist euch durch uns kein Nachteil
erwachsen.

<<v10>>
10 Die gottgewollte Traurigkeit verursacht nämlich Sinnesänderung zum
Heil, die nicht bereut zu werden braucht; die weltliche Traurigkeit aber
führt zum Tod.

<<v11>>
11 Wie groß war doch der Eifer, zu dem euch diese gottgewollte
Traurigkeit geführt hat, wie aufrichtig eure Entschuldigung, euer
Unwille, eure Furcht, eure Sehnsucht, wie wirksam eure Anstrengung und
am Ende die Bestrafung! In jeder Hinsicht hat es sich gezeigt, dass ihr
in dieser Sache unschuldig seid. ^{[[#fn9][9]]}

<<v12>>
12 Wenn ich euch also geschrieben habe, so tat ich es nicht, um den zu
treffen, der Unrecht getan hatte, auch nicht, um dem Recht zu
verschaffen, der Unrecht erlitten hatte, sondern ich tat es, damit euer
Eifer für uns sichtbar werde vor euch und vor Gott. ^{[[#fn10][10]]}

<<v13>>
13 Deswegen sind wir jetzt getröstet. Wir wurden aber nicht nur
getröstet, sondern darüber hinaus erfreut durch die Freude des Titus,
dessen Geist neue Kraft gefunden hat durch euch alle.

<<v14>>
14 Wenn ich euch vor ihm gerühmt hatte, so brauchte ich mich jetzt nicht
zu schämen. Im Gegenteil, unser Lob vor Titus erwies sich als volle
Wahrheit, wie auch alles Wahrheit ist, was wir euch verkündigt haben.

<<v15>>
15 Er ist euch von Herzen zugetan, wenn er daran denkt, wie ihr euch
alle gehorsam gezeigt und ihn mit Furcht und Zittern aufgenommen habt.
^{[[#fn11][11]]}

<<v16>>
16 Ich freue mich, dass ich in jeder Hinsicht auf euch vertrauen kann.\\
\\

^{[[#fnm1][1]]} ℘ 1 Joh 3,3

^{[[#fnm2][2]]} ℘ 12,17

^{[[#fnm3][3]]} ℘ 6,11f.9

^{[[#fnm4][4]]} ℘ 2,13; 4,8

^{[[#fnm5][5]]} Hier nimmt der Brief den in 2,13 verlassenen
Gedankengang wieder auf.

^{[[#fnm6][6]]} ℘ 1,3f

^{[[#fnm7][7]]} ℘ 1 Thess 3,6f

^{[[#fnm8][8]]} ℘ 2,4

^{[[#fnm9][9]]} ℘ 2,6f

^{[[#fnm10][10]]} ℘ 2,9

^{[[#fnm11][11]]} ℘ Phil 2,12
