:PROPERTIES:
:ID:       d9d190d5-08d9-4514-9780-c80aadb5fced
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der zweite Brief an die Korinther* --
[[file:2.Kor_1.html][1]] ... [[file:2.Kor_11.html][11]]
[[file:2.Kor_12.html][12]] *13*

--------------

* 2.Kor 13
  :PROPERTIES:
  :CUSTOM_ID: kor-13
  :END:

<<verses>>

<<v1>>
**** Seelsorge aus apostolischer Vollmacht: 13,1-10
     :PROPERTIES:
     :CUSTOM_ID: seelsorge-aus-apostolischer-vollmacht-131-10
     :END:
1 Das ist das dritte Mal, dass ich zu euch komme. /Durch die Aussage von
zwei oder drei Zeugen wird jede Sache entschieden./ ^{[[#fn1][1]]}

<<v2>>
2 Denen, die sich früher verfehlt haben, und allen Übrigen sage ich
jetzt aus der Ferne dasselbe, was ich schon bei meinem zweiten
Aufenthalt angekündigt habe: Wenn ich komme, werde ich keine Nachsicht
mehr üben. ^{[[#fn2][2]]}

<<v3>>
3 Denn ihr verlangt einen Beweis dafür, dass durch mich Christus
spricht, der nicht in seiner Schwachheit, sondern in seiner Kraft unter
euch wirkt. ^{[[#fn3][3]]}

<<v4>>
4 Zwar wurde er in seiner Schwachheit gekreuzigt, aber er lebt aus
Gottes Kraft. Auch wir sind schwach in ihm, aber wir werden zusammen mit
ihm vor euren Augen aus Gottes Kraft leben. ^{[[#fn4][4]]}

<<v5>>
5 Fragt euch selbst, ob ihr im Glauben seid, prüft euch selbst! Erfahrt
ihr nicht an euch selbst, dass Christus Jesus in euch ist? Sonst hättet
ihr ja (als Gläubige) schon versagt. ^{[[#fn5][5]]}

<<v6>>
6 Ich hoffe aber, ihr werdet erkennen, dass wir nicht versagt haben.

<<v7>>
7 Doch flehen wir zu Gott, dass ihr nichts Böses tut, nicht, damit wir
gerechtfertigt erscheinen, sondern nur, damit ihr das Gute tut, wir aber
wie Versager dastehen.

<<v8>>
8 Denn wir können unsere Kraft nicht gegen die Wahrheit einsetzen, nur
für die Wahrheit.

<<v9>>
9 So ist es uns eine Freude, wenn wir schwach dastehen, ihr aber euch
als stark erweist. Das ist es, was wir erflehen: eure vollständige
Erneuerung.

<<v10>>
10 Deswegen schreibe ich das alles aus der Ferne, um nicht, wenn ich zu
euch komme, Strenge gebrauchen zu müssen kraft der Vollmacht, die der
Herr mir zum Aufbauen, nicht zum Niederreißen gegeben hat.
^{[[#fn6][6]]}\\
\\

<<v11>>
** Schlusswort und Segenswunsch: 13,11-13
   :PROPERTIES:
   :CUSTOM_ID: schlusswort-und-segenswunsch-1311-13
   :END:
11 Im Übrigen, liebe Brüder, freut euch, kehrt zur Ordnung zurück, lasst
euch ermahnen, seid eines Sinnes und lebt in Frieden! Dann wird der Gott
der Liebe und des Friedens mit euch sein. ^{[[#fn7][7]]}

<<v12>>
12 Grüßt einander mit dem heiligen Kuss! Es grüßen euch alle Heiligen.
^{[[#fn8][8]]}

<<v13>>
13 Die Gnade Jesu Christi, des Herrn, die Liebe Gottes und die
Gemeinschaft des Heiligen Geistes sei mit euch allen! ^{[[#fn9][9]]}\\
\\

^{[[#fnm1][1]]} ℘ 12,14; Dtn 19,15; Mt 18,16; 1 Tim 5,19

^{[[#fnm2][2]]} ℘ 12,21

^{[[#fnm3][3]]} ℘ Röm 15,18f

^{[[#fnm4][4]]} ℘ 1 Kor 1,24f.27

^{[[#fnm5][5]]} ℘ 1 Kor 11,28; Röm 8,9f

^{[[#fnm6][6]]} ℘ 2,3; 10,4.8.11

^{[[#fnm7][7]]} ℘ Phil 4,4; Röm 12,16; 15,5.33; Phil 2,2

^{[[#fnm8][8]]} ℘ Röm 16,16; 1 Kor 16,20; 1 Thess 5,26

^{[[#fnm9][9]]} ℘ Gal 6,18; Joh 14,16f; Röm 8,26f
