:PROPERTIES:
:ID:       f983e68f-b5f4-446a-8463-3f4daab10357
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der zweite Brief des Petrus* --
[[file:2.Petr_1.html][1]] *2* [[file:2.Petr_3.html][3]]

--------------

* 2.Petr 2
  :PROPERTIES:
  :CUSTOM_ID: petr-2
  :END:

<<verses>>

<<v1>>
** Warnung vor Irrlehrern: 2,1-22
   :PROPERTIES:
   :CUSTOM_ID: warnung-vor-irrlehrern-21-22
   :END:
**** Das Auftreten falscher Lehrer: 2,1-3
     :PROPERTIES:
     :CUSTOM_ID: das-auftreten-falscher-lehrer-21-3
     :END:
1 Es gab aber auch falsche Propheten im Volk; so wird es auch bei euch
falsche Lehrer geben. Sie werden verderbliche Irrlehren verbreiten und
den Herrscher, der sie freigekauft hat, verleugnen; doch dadurch werden
sie sich selbst bald ins Verderben stürzen. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Bei ihren Ausschweifungen werden sie viele Anhänger finden und
ihretwegen wird der Weg der Wahrheit in Verruf kommen.

<<v3>>
3 In ihrer Habgier werden sie euch mit verlogenen Worten zu kaufen
versuchen; aber das Gericht über sie bereitet sich schon seit langem vor
und das Verderben, das ihnen droht, schläft nicht.\\
\\

<<v4>>
**** Das drohende Gericht über die Irrlehrer: 2,4-10a
     :PROPERTIES:
     :CUSTOM_ID: das-drohende-gericht-über-die-irrlehrer-24-10a
     :END:
4 Gott hat auch die Engel, die gesündigt haben, nicht verschont, sondern
sie in die finsteren Höhlen der Unterwelt verstoßen und hält sie dort
eingeschlossen bis zum Gericht. ^{[[#fn3][3]][[#fn4][4]]}

<<v5>>
5 Er hat auch die frühere Welt nicht verschont, nur Noach, den Verkünder
der Gerechtigkeit, hat er zusammen mit sieben anderen als achten
bewahrt, als er die Flut über die Welt der Gottlosen brachte.

<<v6>>
6 Auch die Städte Sodom und Gomorra hat er eingeäschert und zum
Untergang verurteilt, als ein Beispiel für alle Gottlosen in späteren
Zeiten. ^{[[#fn5][5]]}

<<v7>>
7 Den gerechten Lot aber, der unter dem ausschweifenden Leben der
Gottesverächter litt, hat er gerettet; ^{[[#fn6][6]]}

<<v8>>
8 denn dieser Gerechte, der mitten unter ihnen wohnte, musste Tag für
Tag ihr gesetzwidriges Tun sehen und hören, und das quälte den gerechten
Mann Tag für Tag.

<<v9>>
9 Der Herr kann die Frommen aus der Prüfung retten; bei den Ungerechten
aber kann er warten, um sie am Tag des Gerichts zu bestrafen,

<<v10a>>
10a besonders die, die sich von der schmutzigen Begierde ihres Körpers
beherrschen lassen und die Macht des Herrn verachten.

<<v10b>>
**** Der Weg der Irrlehrer: 2,10b-22
     :PROPERTIES:
     :CUSTOM_ID: der-weg-der-irrlehrer-210b-22
     :END:
10b Diese frechen und anmaßenden Menschen schrecken nicht davor zurück,
die überirdischen Mächte zu lästern, ^{[[#fn7][7]]}

<<v11>>
11 während die Engel, die ihnen an Stärke und Macht überlegen sind, beim
Herrn nicht über sie urteilen und lästern.

<<v12>>
12 Diese Menschen aber sind wie unvernünftige Tiere, die von Natur aus
dazu geboren sind, gefangen zu werden und umzukommen. Sie lästern über
Dinge, die sie nicht verstehen; doch sie werden umkommen, wie die Tiere
umkommen,

<<v13>>
13 und als Lohn für ihr Unrecht werden sie Unrecht erleiden. Sie halten
es für ein Vergnügen, bei Tag ein üppiges Leben zu führen; ein
schmutziger Schandfleck sind sie, wenn sie in ihrer trügerischen
Genusssucht mit euch prassen und schwelgen.

<<v14>>
14 Sie haben nur Augen für die Ehebrecherin und sind unersättlich in der
Sünde. Sie locken haltlose Menschen an, deren Sinn nicht gefestigt ist;
ihr Herz ist in der Habgier geübt, sie sind Kinder des Fluches.

<<v15>>
15 Sie haben den geraden Weg verlassen und sind in die Irre gegangen.
Sie folgten dem Weg Bileams, des Sohnes Bosors; ihm ging es nur um den
Lohn für sein Unrecht, ^{[[#fn8][8]]}

<<v16>>
16 aber er wurde wegen seines Vergehens zurechtgewiesen: Ein stummes
Lasttier redete mit menschlicher Stimme und verhinderte das wahnwitzige
Vorhaben des Propheten. ^{[[#fn9][9]]}

<<v17>>
17 Diese Menschen sind Quellen ohne Wasser, sie sind Wolken, die der
Sturm vor sich herjagt; für sie ist die dunkelste Finsternis bestimmt.

<<v18>>
18 Sie führen geschwollene und nichts sagende Reden; sie lassen sich von
ihren fleischlichen Begierden treiben und locken mit ihren
Ausschweifungen die Menschen an, die sich eben erst von denen getrennt
haben, die im Irrtum leben.

<<v19>>
19 Freiheit versprechen sie ihnen und sind doch selbst Sklaven des
Verderbens; denn von wem jemand überwältigt worden ist, dessen Sklave
ist er.

<<v20>>
20 Sie waren dem Schmutz der Welt entronnen, weil sie den Herrn und
Retter Jesus Christus erkannt hatten; wenn sie sich aber von neuem davon
fangen und überwältigen lassen, dann steht es mit ihnen am Ende
schlimmer als vorher. ^{[[#fn10][10]]}

<<v21>>
21 Es wäre besser für sie, den Weg der Gerechtigkeit gar nicht erkannt
zu haben, als ihn erkannt zu haben und sich danach wieder von dem
heiligen Gebot abzuwenden, das ihnen überliefert worden ist.

<<v22>>
22 Auf sie trifft das wahre Sprichwort zu: /Der Hund kehrt zurück zu
dem, was er erbrochen hat,/ und: Die gewaschene Sau wälzt sich wieder im
Dreck. ^{[[#fn11][11]][[#fn12][12]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-22) Jud 3-16

^{[[#fnm2][2]]} 1-22: Zu den Irrlehrern vgl. die Einleitung zum 2.
Petrusbrief.

^{[[#fnm3][3]]} ℘ Jud 6; 1 Petr 3,19f

^{[[#fnm4][4]]} Es handelt sich um die Engel, von denen in Gen 6,1-4 die
Rede ist; vgl. Jud 6.

^{[[#fnm5][5]]} ℘ Gen 19,24f; Jud 7

^{[[#fnm6][6]]} ℘ Gen 19,1-16

^{[[#fnm7][7]]} 10b: die überirdischen Mächte, wörtlich: die
Herrlichkeiten.

^{[[#fnm8][8]]} Nach Num 22,5 hieß der Vater Bileams «Beor»; so auch
hier nach einigen Textzeugen.

^{[[#fnm9][9]]} ℘ Num 22,28f

^{[[#fnm10][10]]} ℘ Mt 12,45

^{[[#fnm11][11]]} ℘ Spr 26,11

^{[[#fnm12][12]]} Die Herkunft des zweiten Sprichwortes ist unbekannt.
