:PROPERTIES:
:ID:       0b96b182-d8f4-410e-b147-80d660f34db1
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der zweite Brief an die Thessalonicher* -- *1*
[[file:2.Thess_2.html][2]] [[file:2.Thess_3.html][3]]

--------------

* 2.Thess 1
  :PROPERTIES:
  :CUSTOM_ID: thess-1
  :END:

Anlass für den Brief ist das Auftreten von Irrlehrern in der Gemeinde.
Diese haben die Gemeinde in große Verwirrung gebracht mit der
Behauptung, dass der Tag der Wiederkunft Christi schon da sei (2,2). Der
Brief warnt die Thessalonicher vor diesen Schwärmern und belehrt sie
über die Geschehnisse, die nach dem Plan Gottes dem Ende vorausgehen
müssen. Dabei werden in starkem Maß Vorstellungen aufgegriffen, die im
zeitgenössischen Judentum verbreitet waren.\\
\\
Der Brief hat folgenden Aufbau: Paulus dankt für den guten Zustand der
Gemeinde, weist auf das gerechte Gericht Gottes hin und bittet um die
Vollendung der Thessalonicher in allem Guten (1,1-12). Vor dem Ende der
Welt wird es zum großen Abfall von Gott kommen und der »Sohn des
Verderbens, der Widersacher« (Antichrist) wird auftreten, der jetzt noch
»zurückgehalten«, bei der Wiederkunft Christi aber vernichtet wird
(2,1-12). Paulus ermahnt zum treuen Festhalten an den Überlieferungen
und weist einzelne Gemeindemitglieder zurecht, die sich, offenkundig
durch die Irrlehrer verführt, weigern, der täglichen Arbeit nachzugehen
(2,13 - 3,15). Der Brief schließt mit dem üblichen Segensgruß
(3,16-18).\\
\\
Die Bedeutung des Briefs ist vor allem darin zu sehen, dass er
angesichts der sich verzögernden Wiederkunft Christi dazu auffordert, im
Glauben nicht nachzulassen (vgl. 2 Petr), und vor schwärmerischer
Endzeiterwartung warnt.\\
\\

<<verses>>

<<v1>>
** Anschrift und Gruß: 1,1-2
   :PROPERTIES:
   :CUSTOM_ID: anschrift-und-gruß-11-2
   :END:
1 Paulus, Silvanus und Timotheus an die Gemeinde von Thessalonich, die
in Gott, unserem Vater, und in Jesus Christus, dem Herrn, ist:
^{[[#fn1][1]]}

<<v2>>
2 Gnade sei mit euch und Friede von Gott, dem Vater, und dem Herrn Jesus
Christus. ^{[[#fn2][2]]}\\
\\

<<v3>>
** Die Sorge des Apostels um die Gemeinde: 1,3-12
   :PROPERTIES:
   :CUSTOM_ID: die-sorge-des-apostels-um-die-gemeinde-13-12
   :END:
**** Die Bedrängnis der Thessalonicher und das gerechte Gericht Gottes:
1,3-10
     :PROPERTIES:
     :CUSTOM_ID: die-bedrängnis-der-thessalonicher-und-das-gerechte-gericht-gottes-13-10
     :END:
3 Wir müssen Gott euretwegen immer danken, Brüder, wie es recht ist,
denn euer Glaube wächst und die gegenseitige Liebe nimmt bei euch allen
zu. ^{[[#fn3][3]]}

<<v4>>
4 Wir können in den Gemeinden Gottes mit Stolz auf euch hinweisen, weil
ihr im Glauben standhaft bleibt bei aller Verfolgung und Bedrängnis, die
ihr zu ertragen habt. ^{[[#fn4][4]]}

<<v5>>
5 Dies ist ein Anzeichen des gerechten Gerichtes Gottes; ihr sollt ja
des Reiches Gottes teilhaftig werden, für das ihr leidet. ^{[[#fn5][5]]}

<<v6>>
6 Denn es entspricht der Gerechtigkeit Gottes, denen mit Bedrängnis zu
vergelten, die euch bedrängen,

<<v7>>
7 euch aber, den Bedrängten, zusammen mit uns Ruhe zu schenken, wenn
Jesus, der Herr, sich vom Himmel her offenbart mit seinen mächtigen
Engeln ^{[[#fn6][6]]}

<<v8>>
8 in loderndem Feuer. Dann /übt er Vergeltung/ an denen, die Gott nicht
kennen und dem Evangelium Jesu, unseres Herrn, nicht gehorchen.
^{[[#fn7][7]]}

<<v9>>
9 /Fern vom Angesicht des Herrn und von seiner Macht und Herrlichkeit/
müssen sie sein, mit ewigem Verderben werden sie bestraft,
^{[[#fn8][8]]}

<<v10>>
10 wenn er an jenem Tag kommt, um inmitten seiner Heiligen gefeiert und
im Kreis aller derer bewundert zu werden, die den Glauben angenommen
haben; auch bei euch hat ja unser Zeugnis Glauben gefunden.
^{[[#fn9][9]]}\\
\\

<<v11>>
**** Fürbitte des Apostels: 1,11-12
     :PROPERTIES:
     :CUSTOM_ID: fürbitte-des-apostels-111-12
     :END:
11 Darum beten wir auch immer für euch, dass unser Gott euch eurer
Berufung würdig mache und in seiner Macht allen Willen zum Guten und
jedes Werk des Glaubens vollende.

<<v12>>
12 So soll der Name Jesu, unseres Herrn, in euch verherrlicht werden und
ihr in ihm, durch die Gnade unseres Gottes und Herrn Jesus Christus.
^{[[#fn10][10]][[#fn11][11]]}\\
\\

^{[[#fnm1][1]]} ℘ 1 Thess 1,1

^{[[#fnm2][2]]} ℘ Röm 1,7

^{[[#fnm3][3]]} ℘ 1 Thess 1,2

^{[[#fnm4][4]]} ℘ Mk 4,17

^{[[#fnm5][5]]} ℘ Phil 1,28; (5-10) Röm 2,6-11

^{[[#fnm6][6]]} ℘ 1 Thess 3,13; 4,16

^{[[#fnm7][7]]} ℘ Ex 3,2; Jes 66,4.15; Jer 10,25; Ps 79,6

^{[[#fnm8][8]]} ℘ Jes 2,10.19.21

^{[[#fnm9][9]]} ℘ Jes 2,11.17; Ps 89,8

^{[[#fnm10][10]]} ℘ Jes 24,15; Mal 1,11

^{[[#fnm11][11]]} Andere Übersetzungsmöglichkeit: durch die Gnade
unseres Gottes und des Herrn Jesus Christus.
