:PROPERTIES:
:ID:       36e6acb6-d337-4f4a-a746-ff8ec92ecafc
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der zweite Brief an die Thessalonicher* --
[[file:2.Thess_1.html][1]] [[file:2.Thess_2.html][2]] *3*

--------------

* 2.Thess 3
  :PROPERTIES:
  :CUSTOM_ID: thess-3
  :END:

<<verses>>

<<v1>>
** Anweisungen an die Gemeinde: 3,1-15
   :PROPERTIES:
   :CUSTOM_ID: anweisungen-an-die-gemeinde-31-15
   :END:
**** Bitte um das Gebet der Gemeinde: 3,1-5
     :PROPERTIES:
     :CUSTOM_ID: bitte-um-das-gebet-der-gemeinde-31-5
     :END:
1 Im Übrigen, Brüder, betet für uns, damit das Wort des Herrn sich
ausbreitet und verherrlicht wird, ebenso wie bei euch. ^{[[#fn1][1]]}

<<v2>>
2 Betet auch darum, dass wir vor den bösen und schlechten Menschen
gerettet werden; denn nicht alle nehmen den Glauben an.

<<v3>>
3 Aber der Herr ist treu; er wird euch Kraft geben und euch vor dem
Bösen bewahren. ^{[[#fn2][2]]}

<<v4>>
4 Wir vertrauen im Herrn auf euch, dass ihr jetzt und auch in Zukunft
tut, was wir anordnen.

<<v5>>
5 Der Herr richte euer Herz darauf, dass ihr Gott liebt und unbeirrt auf
Christus wartet. ^{[[#fn3][3]]}\\
\\

<<v6>>
**** Zurechtweisung der Müßiggänger: 3,6-12
     :PROPERTIES:
     :CUSTOM_ID: zurechtweisung-der-müßiggänger-36-12
     :END:
6 Im Namen Jesu Christi, des Herrn, gebieten wir euch, Brüder: Haltet
euch von jedem Bruder fern, der ein unordentliches Leben führt und sich
nicht an die Überlieferung hält, die ihr von uns empfangen habt.
^{[[#fn4][4]]}

<<v7>>
7 Ihr selbst wisst, wie man uns nachahmen soll. Wir haben bei euch kein
unordentliches Leben geführt ^{[[#fn5][5]]}

<<v8>>
8 und bei niemand unser Brot umsonst gegessen; wir haben uns gemüht und
geplagt, Tag und Nacht haben wir gearbeitet, um keinem von euch zur Last
zu fallen. ^{[[#fn6][6]]}

<<v9>>
9 Nicht als hätten wir keinen Anspruch auf Unterhalt; wir wollten euch
aber ein Beispiel geben, damit ihr uns nachahmen könnt. ^{[[#fn7][7]]}

<<v10>>
10 Denn als wir bei euch waren, haben wir euch die Regel eingeprägt: Wer
nicht arbeiten will, soll auch nicht essen.

<<v11>>
11 Wir hören aber, dass einige von euch ein unordentliches Leben führen
und alles Mögliche treiben, nur nicht arbeiten.

<<v12>>
12 Wir ermahnen sie und gebieten ihnen im Namen Jesu Christi, des Herrn,
in Ruhe ihrer Arbeit nachzugehen und ihr selbst verdientes Brot zu
essen. ^{[[#fn8][8]]}\\
\\

<<v13>>
**** Mahnung an alle: 3,13-15
     :PROPERTIES:
     :CUSTOM_ID: mahnung-an-alle-313-15
     :END:
13 Ihr aber, Brüder, werdet nicht müde, Gutes zu tun.

<<v14>>
14 Wenn jemand auf unsere Mahnung in diesem Brief nicht hört, dann merkt
ihn euch und meidet den Umgang mit ihm, damit er sich schämt;
^{[[#fn9][9]]}

<<v15>>
15 doch seht ihn nicht als Feind an, sondern weist ihn als euren Bruder
zurecht! ^{[[#fn10][10]]}\\
\\

<<v16>>
** Der Schluss des Briefes: 3,16-18
   :PROPERTIES:
   :CUSTOM_ID: der-schluss-des-briefes-316-18
   :END:
16 Der Herr des Friedens aber schenke euch den Frieden zu jeder Zeit und
auf jede Weise. Der Herr sei mit euch allen. ^{[[#fn11][11]]}

<<v17>>
17 Den Gruß schreibe ich, Paulus, eigenhändig. Das ist mein Zeichen in
jedem Brief; so schreibe ich. ^{[[#fn12][12]][[#fn13][13]]}

<<v18>>
18 Die Gnade Jesu Christi, unseres Herrn, sei mit euch allen!
^{[[#fn14][14]]}\\
\\

^{[[#fnm1][1]]} ℘ Kol 4,3; 1 Thess 5,25

^{[[#fnm2][2]]} ℘ 1 Kor 10,13; 1 Thess 5,24

^{[[#fnm3][3]]} Andere Übersetzungsmöglichkeit: Der Herr lenke euer Herz
zur Liebe Gottes und zur Geduld Christi.

^{[[#fnm4][4]]} ℘ 1 Thess 5,14

^{[[#fnm5][5]]} ℘ 1 Kor 11,1

^{[[#fnm6][6]]} ℘ 1 Kor 4,12; 1 Thess 2,9

^{[[#fnm7][7]]} ℘ Mt 10,10; 1 Kor 9,6.14; Phil 3,17

^{[[#fnm8][8]]} ℘ 1 Thess 4,11

^{[[#fnm9][9]]} ℘ 1 Kor 5,9.11

^{[[#fnm10][10]]} ℘ Mt 18,15-17

^{[[#fnm11][11]]} ℘ Röm 15,33

^{[[#fnm12][12]]} ℘ 1 Kor 16,21

^{[[#fnm13][13]]} Zur eigenhändigen Unterschrift vgl. 1 Kor 16,21; Gal
6,11; Kol 4,18; Phlm 19 und die Anmerkung zu 2 Thess 2,2.

^{[[#fnm14][14]]} ℘ Röm 16,24
