:PROPERTIES:
:ID:       a8ce9016-0bf9-4912-9311-d89c15d6528f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der zweite Brief an Timotheus* --
[[file:2.Tim_1.html][1]] [[file:2.Tim_2.html][2]]
[[file:2.Tim_3.html][3]] *4*

--------------

* 2.Tim 4
  :PROPERTIES:
  :CUSTOM_ID: tim-4
  :END:

<<verses>>

<<v1>>
**** Aufruf zu unerschrockenem Einsatz: 4,1-8
     :PROPERTIES:
     :CUSTOM_ID: aufruf-zu-unerschrockenem-einsatz-41-8
     :END:
1 Ich beschwöre dich bei Gott und bei Christus Jesus, dem kommenden
Richter der Lebenden und der Toten, bei seinem Erscheinen und bei seinem
Reich: ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Verkünde das Wort, tritt dafür ein, ob man es hören will oder nicht;
weise zurecht, tadle, ermahne, in unermüdlicher und geduldiger
Belehrung.

<<v3>>
3 Denn es wird eine Zeit kommen, in der man die gesunde Lehre nicht
erträgt, sondern sich nach eigenen Wünschen immer neue Lehrer sucht, die
den Ohren schmeicheln; ^{[[#fn3][3]]}

<<v4>>
4 und man wird der Wahrheit nicht mehr Gehör schenken, sondern sich
Fabeleien zuwenden. ^{[[#fn4][4]]}

<<v5>>
5 Du aber sei in allem nüchtern, ertrage das Leiden, verkünde das
Evangelium, erfülle treu deinen Dienst!

<<v6>>
6 Denn ich werde nunmehr geopfert, und die Zeit meines Aufbruchs ist
nahe. ^{[[#fn5][5]]}

<<v7>>
7 Ich habe den guten Kampf gekämpft, den Lauf vollendet, die Treue
gehalten. ^{[[#fn6][6]][[#fn7][7]]}

<<v8>>
8 Schon jetzt liegt für mich der Kranz der Gerechtigkeit bereit, den mir
der Herr, der gerechte Richter, an jenem Tag geben wird, aber nicht nur
mir, sondern allen, die sehnsüchtig auf sein Erscheinen warten.
^{[[#fn8][8]]}\\
\\

<<v9>>
** Persönliche Mitteilungen und Aufträge: 4,9-18
   :PROPERTIES:
   :CUSTOM_ID: persönliche-mitteilungen-und-aufträge-49-18
   :END:
9 Beeil dich, komm bald zu mir!

<<v10>>
10 Demas hat mich aus Liebe zu dieser Welt verlassen und ist nach
Thessalonich gegangen; Kreszenz ging nach Galatien, Titus nach
Dalmatien.

<<v11>>
11 Nur Lukas ist noch bei mir. Bring Markus mit, denn er wird mir ein
guter Helfer sein.

<<v12>>
12 Tychikus habe ich nach Ephesus geschickt. ^{[[#fn9][9]]}

<<v13>>
13 Wenn du kommst, bring den Mantel mit, den ich in Troas bei Karpus
gelassen habe, auch die Bücher, vor allem die Pergamente.
^{[[#fn10][10]]}

<<v14>>
14 Alexander, der Schmied, hat mir viel Böses getan; /der Herr wird ihm
vergelten, wie es seine Taten verdienen./ ^{[[#fn11][11]]}

<<v15>>
15 Nimm auch du dich vor ihm in Acht, denn er hat unsere Lehre heftig
bekämpft.

<<v16>>
16 Bei meiner ersten Verteidigung ist niemand für mich eingetreten; alle
haben mich im Stich gelassen. Möge es ihnen nicht angerechnet werden.
^{[[#fn12][12]][[#fn13][13]]}

<<v17>>
17 Aber der Herr stand mir zur Seite und gab mir Kraft, damit durch mich
die Verkündigung vollendet wird und alle Heiden sie hören; und so wurde
ich dem /Rachen des Löwen entrissen./ ^{[[#fn14][14]]}

<<v18>>
18 Der Herr wird mich allem Bösen entreißen, er wird mich retten und in
sein himmlisches Reich führen. Ihm sei die Ehre in alle Ewigkeit.
Amen.\\
\\

<<v19>>
** Der Schluss des Briefes: Grüße und Segenswünsche: 4,19-22
   :PROPERTIES:
   :CUSTOM_ID: der-schluss-des-briefes-grüße-und-segenswünsche-419-22
   :END:
19 Grüße Priska und Aquila und die Familie des Onesiphorus!

<<v20>>
20 Erastus blieb in Korinth, Trophimus musste ich krank in Milet
zurücklassen.

<<v21>>
21 Beeil dich, komm noch vor dem Winter! Es grüßen dich Eubulus, Pudens,
Linus, Klaudia und alle Brüder.

<<v22>>
22 Der Herr sei mit deinem Geist! Die Gnade sei mit euch!\\
\\

^{[[#fnm1][1]]} ℘ 2 Petr 1,12; Jud 17

^{[[#fnm2][2]]} 1-8: In diesem Abschnitt wird der Charakter des Briefs
als eines Abschiedsbriefs und einer letztwilligen Verfügung besonders
deutlich; vgl. die Abschiedsrede des Paulus in Milet an die Presbyter
von Ephesus (Apg 20,18-35).

^{[[#fnm3][3]]} ℘ 1 Tim 4,1; 1,10; 4,6; 6,3; Tit 1,9; 2,1.10

^{[[#fnm4][4]]} ℘ 1 Tim 1,4

^{[[#fnm5][5]]} ℘ Phil 2,17

^{[[#fnm6][6]]} ℘ 1 Tim 6,12; Phil 3,14; 2 Petr 1,14

^{[[#fnm7][7]]} die Treue gehalten, andere Übersetzungsmöglichkeit: den
Glauben bewahrt.

^{[[#fnm8][8]]} Der Tag der Wiederkunft Christi ist, wenn auch nicht
mehr als unmittelbar bevorstehend gedacht, doch der alles entscheidende
Tag.

^{[[#fnm9][9]]} ℘ Eph 6,21

^{[[#fnm10][10]]} Die nicht näher bezeichneten Bücher waren wohl auf
Papyrus geschrieben; bei den Pergamenten handelt es sich wahrscheinlich
um Schriftrollen mit Texten des Alten Testaments.

^{[[#fnm11][11]]} ℘ 1 Tim 1,20; Ps 62,13; 28,4

^{[[#fnm12][12]]} ℘ Phil 1,15-18

^{[[#fnm13][13]]} Es ist nicht sicher, ob mit der «ersten Verteidigung»
auf eine frühere Gefangenschaft angespielt ist oder nur auf ein früheres
Verhör.

^{[[#fnm14][14]]} ℘ Ps 22,22; Dan 6,21.28
