:PROPERTIES:
:ID:       645a2f49-6748-4647-8e2e-d5d0a865364c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Apostelgeschichte* --
[[file:Apg_1.html][1]] ... [[file:Apg_13.html][13]]
[[file:Apg_14.html][14]] *15* [[file:Apg_16.html][16]]
[[file:Apg_17.html][17]] ... [[file:Apg_28.html][28]]

--------------

* Apg 15
  :PROPERTIES:
  :CUSTOM_ID: apg-15
  :END:

<<verses>>

<<v1>>
*** Das Apostelkonzil in Jerusalem: 15,1-35
    :PROPERTIES:
    :CUSTOM_ID: das-apostelkonzil-in-jerusalem-151-35
    :END:
**** Die Streitfrage: 15,1-5
     :PROPERTIES:
     :CUSTOM_ID: die-streitfrage-151-5
     :END:
1 Es kamen einige Leute von Judäa herab und lehrten die Brüder: Wenn ihr
euch nicht nach dem Brauch des Mose beschneiden lasst, könnt ihr nicht
gerettet werden. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Nach großer Aufregung und heftigen Auseinandersetzungen zwischen ihnen
und Paulus und Barnabas beschloss man, Paulus und Barnabas und einige
andere von ihnen sollten wegen dieser Streitfrage zu den Aposteln und
den Ältesten nach Jerusalem hinaufgehen. ^{[[#fn3][3]]}

<<v3>>
3 Sie wurden von der Gemeinde feierlich verabschiedet und zogen durch
Phönizien und Samarien; dabei berichteten sie den Brüdern von der
Bekehrung der Heiden und bereiteten damit allen große Freude.

<<v4>>
4 Bei ihrer Ankunft in Jerusalem wurden sie von der Gemeinde und von den
Aposteln und den Ältesten empfangen. Sie erzählten alles, was Gott mit
ihnen zusammen getan hatte.

<<v5>>
5 Da erhoben sich einige aus dem Kreis der Pharisäer, die gläubig
geworden waren, und sagten: Man muss sie beschneiden und von ihnen
fordern, am Gesetz des Mose fest zu halten.\\
\\

<<v6>>
**** Die Versammlung der Apostel und der Ältesten mit der Gemeinde:
15,6-21
     :PROPERTIES:
     :CUSTOM_ID: die-versammlung-der-apostel-und-der-ältesten-mit-der-gemeinde-156-21
     :END:
6 Die Apostel und die Ältesten traten zusammen, um die Frage zu prüfen.

<<v7>>
7 Als ein heftiger Streit entstand, erhob sich Petrus und sagte zu
ihnen: Brüder, wie ihr wisst, hat Gott schon längst hier bei euch die
Entscheidung getroffen, dass die Heiden durch meinen Mund das Wort des
Evangeliums hören und zum Glauben gelangen sollen.

<<v8>>
8 Und Gott, der die Herzen kennt, bestätigte dies, indem er ihnen ebenso
wie uns den Heiligen Geist gab. ^{[[#fn4][4]]}

<<v9>>
9 Er machte keinerlei Unterschied zwischen uns und ihnen; denn er hat
ihre Herzen durch den Glauben gereinigt. ^{[[#fn5][5]]}

<<v10>>
10 Warum stellt ihr also jetzt Gott auf die Probe und legt den Jüngern
ein Joch auf den Nacken, das weder unsere Väter noch wir tragen konnten?
^{[[#fn6][6]]}

<<v11>>
11 Wir glauben im Gegenteil, durch die Gnade Jesu, des Herrn, gerettet
zu werden, auf die gleiche Weise wie jene. ^{[[#fn7][7]]}

<<v12>>
12 Da schwieg die ganze Versammlung. Und sie hörten Barnabas und Paulus
zu, wie sie erzählten, welch große Zeichen und Wunder Gott durch sie
unter den Heiden getan hatte.

<<v13>>
13 Als sie geendet hatten, nahm Jakobus das Wort und sagte: Brüder, hört
mich an! ^{[[#fn8][8]]}

<<v14>>
14 Simon hat berichtet, dass Gott selbst zuerst eingegriffen hat, um aus
den Heiden ein Volk für seinen Namen zu gewinnen.

<<v15>>
15 Damit stimmen die Worte der Propheten überein, die geschrieben
haben:\\
\\

<<v16>>
16 /Danach werde ich mich umwenden/ /\\
 /und die zerfallene Hütte Davids wieder aufrichten;/ /\\
 /ich werde sie aus ihren Trümmern wieder aufrichten/ /\\
 /und werde sie wiederherstellen,/ ^{[[#fn9][9]]}\\
\\

<<v17>>
17 /damit die übrigen Menschen den Herrn suchen,/ /\\
 /auch alle Völker,/ /\\
 /über denen mein Name ausgerufen ist -/ /\\
 /spricht der Herr, der das ausführt,/\\
\\

<<v18>>
18 was ihm seit Ewigkeit bekannt ist. ^{[[#fn10][10]]}

<<v19>>
19 Darum halte ich es für richtig, den Heiden, die sich zu Gott
bekehren, keine Lasten aufzubürden;

<<v20>>
20 man weise sie nur an, Verunreinigung durch Götzen(opferfleisch) und
Unzucht zu meiden und weder Ersticktes noch Blut zu essen.
^{[[#fn11][11]][[#fn12][12]]}

<<v21>>
21 Denn Mose hat seit ältesten Zeiten in jeder Stadt seine Verkündiger,
da er in den Synagogen an jedem Sabbat verlesen wird.\\
\\

<<v22>>
**** Die Beschlüsse der Versammlung: 15,22-29
     :PROPERTIES:
     :CUSTOM_ID: die-beschlüsse-der-versammlung-1522-29
     :END:
22 Da beschlossen die Apostel und die Ältesten zusammen mit der ganzen
Gemeinde, Männer aus ihrer Mitte auszuwählen und sie zusammen mit Paulus
und Barnabas nach Antiochia zu senden, nämlich Judas, genannt Barsabbas,
und Silas, führende Männer unter den Brüdern.

<<v23>>
23 Sie gaben ihnen folgendes Schreiben mit: Die Apostel und die
Ältesten, eure Brüder, grüßen die Brüder aus dem Heidentum in Antiochia,
in Syrien und Zilizien.

<<v24>>
24 Wir haben gehört, dass einige von uns, denen wir keinen Auftrag
erteilt haben, euch mit ihren Reden beunruhigt und eure Gemüter erregt
haben. ^{[[#fn13][13]]}

<<v25>>
25 Deshalb haben wir uns geeinigt und beschlossen, Männer auszuwählen
und zusammen mit unseren lieben Brüdern Barnabas und Paulus zu euch zu
schicken,

<<v26>>
26 die beide für den Namen Jesu Christi, unseres Herrn, ihr Leben
eingesetzt haben.

<<v27>>
27 Wir haben Judas und Silas abgesandt, die euch das Gleiche auch
mündlich mitteilen sollen.

<<v28>>
28 Denn der Heilige Geist und wir haben beschlossen, euch keine weitere
Last aufzuerlegen als diese notwendigen Dinge: ^{[[#fn14][14]]}

<<v29>>
29 Götzenopferfleisch, Blut, Ersticktes und Unzucht zu meiden. Wenn ihr
euch davor hütet, handelt ihr richtig. Lebt wohl!\\
\\

<<v30>>
**** Die Mitteilung der Beschlüsse an die Gemeinde von Antiochia:
15,30-35
     :PROPERTIES:
     :CUSTOM_ID: die-mitteilung-der-beschlüsse-an-die-gemeinde-von-antiochia-1530-35
     :END:
30 Man verabschiedete die Abgesandten und sie zogen hinab nach
Antiochia, riefen die Gemeinde zusammen und übergaben ihr den Brief.

<<v31>>
31 Die Brüder lasen ihn und freuten sich über die Ermunterung.

<<v32>>
32 Judas und Silas, selbst Propheten, sprachen ihnen mit vielen Worten
Mut zu und stärkten sie. ^{[[#fn15][15]]}

<<v33>>
33 Nach einiger Zeit wurden sie von den Brüdern in Frieden wieder zu
denen entlassen, die sie abgesandt hatten.

<<v34>>
34 [] ^{[[#fn16][16]]}

<<v35>>
35 Paulus aber und Barnabas blieben in Antiochia und lehrten und
verkündeten mit vielen anderen das Wort des Herrn.\\
\\

<<v36>>
*** Die zweite Missionsreise des Paulus: 15,36 - 18,22
    :PROPERTIES:
    :CUSTOM_ID: die-zweite-missionsreise-des-paulus-1536---1822
    :END:
**** Die Trennung des Paulus von Barnabas: 15,36-41
     :PROPERTIES:
     :CUSTOM_ID: die-trennung-des-paulus-von-barnabas-1536-41
     :END:
36 Nach einiger Zeit sagte Paulus zu Barnabas: Wir wollen wieder
aufbrechen und sehen, wie es den Brüdern in all den Städten geht, in
denen wir das Wort des Herrn verkündet haben.

<<v37>>
37 Barnabas wollte auch den Johannes, genannt Markus, mitnehmen;
^{[[#fn17][17]]}

<<v38>>
38 doch Paulus bestand darauf, ihn nicht mitzunehmen, weil er sie in
Pamphylien im Stich gelassen hatte, nicht mit ihnen gezogen war und an
ihrer Arbeit nicht mehr teilgenommen hatte. ^{[[#fn18][18]]}

<<v39>>
39 Es kam zu einer heftigen Auseinandersetzung, so dass sie sich
voneinander trennten; Barnabas nahm Markus mit und segelte nach Zypern.

<<v40>>
40 Paulus aber wählte sich Silas und reiste ab, nachdem die Brüder ihn
der Gnade des Herrn empfohlen hatten.

<<v41>>
41 Er zog durch Syrien und Zilizien und stärkte die Gemeinden.
^{[[#fn19][19]]}\\
\\

^{[[#fnm1][1]]} ℘ 15,24; Gal 1,7; 5,10

^{[[#fnm2][2]]} 1-35: Zum Bericht des Lukas über das «Apostelkonzil»
(vermutlich um 48/49 n. Chr) vgl. Gal 2,1-10. Die Frage, ob die
Heidenchristen verpflichtet sind, das jüdische Gesetz zu halten, wurde
auf diesem Konzil verneint (vgl. besonders 15,8-11).

^{[[#fnm3][3]]} ℘ Gal 2,1

^{[[#fnm4][4]]} ℘ 10,44; 11,15

^{[[#fnm5][5]]} ℘ 10,34f

^{[[#fnm6][6]]} ℘ Mt 23,4; Gal 3,10; 5,1

^{[[#fnm7][7]]} ℘ Gal 2,16; Eph 2,4-10

^{[[#fnm8][8]]} ℘ 21,18; Gal 2,9

^{[[#fnm9][9]]} ℘ Am 9,11f G; Jer 12,15

^{[[#fnm10][10]]} ℘ Jes 45,21

^{[[#fnm11][11]]} ℘ 15,29; 21,25; Lev 18,6-18

^{[[#fnm12][12]]} 20.29: «Unzucht» meint hier wahrscheinlich verbotene
Verwandtschaftsehen; «Ersticktes» und «Blut» beziehen sich auf den
Genuss nicht geschächteter, d. h. beim Schlachten nicht ausgebluteter
Tiere. Man nennt diese Anweisung auch «Aposteldekret» oder
«Jakobusklauseln». Sie sollten ein ungestörtes Zusammenleben zwischen
Juden- und Heidenchristen in gemischten Gemeinden ermöglichen.

^{[[#fnm13][13]]} ℘ 15,1; Gal 1,7; 5,10

^{[[#fnm14][14]]} ℘ Mt 23,4; 1 Kor 8,1

^{[[#fnm15][15]]} ℘ 11,27; 13,1

^{[[#fnm16][16]]} Einzelne Textzeugen fügen hier ein: Silas aber
beschloss dazubleiben; so reiste Judas allein (nach Jerusalem) ab.

^{[[#fnm17][17]]} ℘ 12,12.25

^{[[#fnm18][18]]} ℘ 13,13; Kol 4,10

^{[[#fnm19][19]]} ℘ 9,30; 11,25; Gal 1,21
