:PROPERTIES:
:ID:       4996a38d-49ea-4fdc-96f4-7f957e174e65
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Apostelgeschichte* --
[[file:Apg_1.html][1]] ... [[file:Apg_9.html][9]]
[[file:Apg_10.html][10]] *11* [[file:Apg_12.html][12]]
[[file:Apg_13.html][13]] ... [[file:Apg_28.html][28]]

--------------

* Apg 11
  :PROPERTIES:
  :CUSTOM_ID: apg-11
  :END:

<<verses>>

<<v1>>
**** Die Rechenschaft des Petrus vor der Gemeinde in Jerusalem: 11,1-18
     :PROPERTIES:
     :CUSTOM_ID: die-rechenschaft-des-petrus-vor-der-gemeinde-in-jerusalem-111-18
     :END:
1 Die Apostel und die Brüder in Judäa erfuhren, dass auch die Heiden das
Wort Gottes angenommen hatten.

<<v2>>
2 Als nun Petrus nach Jerusalem hinaufkam, hielten ihm die gläubig
gewordenen Juden vor: ^{[[#fn1][1]]}

<<v3>>
3 Du hast das Haus von Unbeschnittenen betreten und hast mit ihnen
gegessen. ^{[[#fn2][2]]}

<<v4>>
4 Da begann Petrus, ihnen der Reihe nach zu berichten:

<<v5>>
5 Ich war in der Stadt Joppe und betete; da hatte ich in einer
Verzückung eine Vision: Eine Schale, die aussah wie ein großes
Leinentuch, das an den vier Ecken gehalten wurde, senkte sich aus dem
Himmel bis zu mir herab.

<<v6>>
6 Als ich genauer hinschaute, sah ich darin die Vierfüßler der Erde, die
wilden Tiere, die Kriechtiere und die Vögel des Himmels.

<<v7>>
7 Ich hörte auch eine Stimme, die zu mir sagte: Steh auf, Petrus,
schlachte und iss!

<<v8>>
8 Ich antwortete: Niemals, Herr! Noch nie ist etwas Unheiliges oder
Unreines in meinen Mund gekommen.

<<v9>>
9 Doch zum zweiten Mal kam eine Stimme vom Himmel; sie sagte: Was Gott
für rein erklärt hat, nenne du nicht unrein!

<<v10>>
10 Das geschah dreimal, dann wurde alles wieder in den Himmel
hinaufgezogen.

<<v11>>
11 Da standen auf einmal drei Männer vor dem Haus, in dem ich wohnte;
sie waren aus Cäsarea zu mir geschickt worden.

<<v12>>
12 Der Geist aber sagte mir, ich solle ohne Bedenken mit ihnen gehen.
Auch diese sechs Brüder zogen mit mir und wir kamen in das Haus jenes
Mannes.

<<v13>>
13 Er erzählte uns, wie er in seinem Haus den Engel stehen sah, der zu
ihm sagte: Schick jemand nach Joppe und lass Simon, der Petrus genannt
wird, holen.

<<v14>>
14 Er wird dir Worte sagen, durch die du mit deinem ganzen Haus gerettet
werden wirst.

<<v15>>
15 Während ich redete, kam der Heilige Geist auf sie herab, wie am
Anfang auf uns. ^{[[#fn3][3]]}

<<v16>>
16 Da erinnerte ich mich an das Wort des Herrn: Johannes hat mit Wasser
getauft, ihr aber werdet mit dem Heiligen Geist getauft werden.
^{[[#fn4][4]]}

<<v17>>
17 Wenn nun Gott ihnen, nachdem sie zum Glauben an Jesus Christus, den
Herrn, gekommen sind, die gleiche Gabe verliehen hat wie uns: wer bin
ich, dass ich Gott hindern könnte?

<<v18>>
18 Als sie das hörten, beruhigten sie sich, priesen Gott und sagten:
Gott hat also auch den Heiden die Umkehr zum Leben geschenkt.
^{[[#fn5][5]]}\\
\\

<<v19>>
**** Die Entstehung einer christlichen Gemeinde in Antiochia: 11,19-26
     :PROPERTIES:
     :CUSTOM_ID: die-entstehung-einer-christlichen-gemeinde-in-antiochia-1119-26
     :END:
19 Bei der Verfolgung, die wegen Stephanus entstanden war, kamen die
Versprengten bis nach Phönizien, Zypern und Antiochia; doch verkündeten
sie das Wort nur den Juden. ^{[[#fn6][6]][[#fn7][7]]}

<<v20>>
20 Einige aber von ihnen, die aus Zypern und Zyrene stammten,
verkündeten, als sie nach Antiochia kamen, auch den Griechen das
Evangelium von Jesus, dem Herrn.

<<v21>>
21 Die Hand des Herrn war mit ihnen und viele wurden gläubig und
bekehrten sich zum Herrn.

<<v22>>
22 Die Nachricht davon kam der Gemeinde von Jerusalem zu Ohren und sie
schickten Barnabas nach Antiochia. ^{[[#fn8][8]]}

<<v23>>
23 Als er ankam und die Gnade Gottes sah, freute er sich und ermahnte
alle, dem Herrn treu zu bleiben, wie sie es sich vorgenommen hatten.

<<v24>>
24 Denn er war ein trefflicher Mann, erfüllt vom Heiligen Geist und von
Glauben. So wurde für den Herrn eine beträchtliche Zahl hinzugewonnen.

<<v25>>
25 Barnabas aber zog nach Tarsus, um Saulus aufzusuchen. ^{[[#fn9][9]]}

<<v26>>
26 Er fand ihn und nahm ihn nach Antiochia mit. Dort wirkten sie
miteinander ein volles Jahr in der Gemeinde und unterrichteten eine
große Zahl von Menschen. In Antiochia nannte man die Jünger zum ersten
Mal Christen. ^{[[#fn10][10]][[#fn11][11]]}\\
\\

<<v27>>
**** Die Spende der Gemeinde von Antiochia für die Christen in Judäa:
11,27-30
     :PROPERTIES:
     :CUSTOM_ID: die-spende-der-gemeinde-von-antiochia-für-die-christen-in-judäa-1127-30
     :END:
27 In jenen Tagen kamen von Jerusalem Propheten nach Antiochia hinab.
^{[[#fn12][12]]}

<<v28>>
28 Einer von ihnen namens Agabus trat auf und weissagte durch den Geist,
eine große Hungersnot werde über die ganze Erde kommen. Sie brach dann
unter Klaudius aus. ^{[[#fn13][13]][[#fn14][14]]}

<<v29>>
29 Man beschloss, jeder von den Jüngern solle nach seinem Vermögen den
Brüdern in Judäa etwas zur Unterstützung senden. ^{[[#fn15][15]]}

<<v30>>
30 Das taten sie auch und schickten ihre Gaben durch Barnabas und Saulus
an die Ältesten.\\
\\

^{[[#fnm1][1]]} die gläubig gewordenen Juden, wörtlich: die aus der
Beschneidung.

^{[[#fnm2][2]]} ℘ 10,28; Gal 2,12

^{[[#fnm3][3]]} ℘ 2,3f

^{[[#fnm4][4]]} ℘ 1,5; Lk 3,16

^{[[#fnm5][5]]} ℘ 14,27

^{[[#fnm6][6]]} ℘ 8,1-4

^{[[#fnm7][7]]} Antiochia in Syrien war die drittgrößte Stadt des
römischen Reiches nach Rom und Alexandria; unter der halben Million
Einwohner war eine große jüdische Gemeinde.

^{[[#fnm8][8]]} ℘ 4,36

^{[[#fnm9][9]]} ℘ 9,30

^{[[#fnm10][10]]} ℘ 11,30; 12,25; 13,2; Gal 2,1.13; Apg 26,28; 1 Petr
4,16

^{[[#fnm11][11]]} Zum ersten Mal im Neuen Testament begegnet hier die
Bezeichnung «Christ» (vgl. 26,28; 1 Petr 4,16).

^{[[#fnm12][12]]} Gemeint sind hier christliche Propheten, die in der
Urkirche eine wichtige Rolle spielten; vgl. z. B. 1 Kor 12,28; 14,3-12;
Eph 2,20.

^{[[#fnm13][13]]} ℘ 21,10f

^{[[#fnm14][14]]} Kaiser Klaudius regierte von 41 bis 54 n. Chr.
Römische Geschichtsschreiber berichten von Hungersnöten während seiner
Regierungszeit. Nach 18,2 hat Klaudius die Juden aus Rom ausgewiesen,
wahrscheinlich im Jahr 49 n. Chr.

^{[[#fnm15][15]]} ℘ Röm 15,26; 1 Kor 16,1; 2 Kor 9,2.12; Gal 2,10
