:PROPERTIES:
:ID:       74d723cd-6984-4878-acc7-bcc31da4b6a4
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Apostelgeschichte* --
[[file:Apg_1.html][1]] ... [[file:Apg_23.html][23]]
[[file:Apg_24.html][24]] *25* [[file:Apg_26.html][26]]
[[file:Apg_27.html][27]] [[file:Apg_28.html][28]]

--------------

* Apg 25
  :PROPERTIES:
  :CUSTOM_ID: apg-25
  :END:

<<verses>>

<<v1>>
**** Paulus vor dem Statthalter Festus - Seine Berufung an den Kaiser:
25,1-12
     :PROPERTIES:
     :CUSTOM_ID: paulus-vor-dem-statthalter-festus---seine-berufung-an-den-kaiser-251-12
     :END:
1 Als Festus in der Provinz eingetroffen war, zog er drei Tage später
von Cäsarea nach Jerusalem hinauf.

<<v2>>
2 Da erstatteten die Hohenpriester und die Vornehmsten der Juden bei ihm
Anzeige gegen Paulus. Sie ersuchten ihn, gegen Paulus vorzugehen,

<<v3>>
3 und baten ihn um den Gefallen, Paulus nach Jerusalem bringen zu
lassen. Sie wollten ihn nämlich unterwegs aus einem Hinterhalt heraus
ermorden. ^{[[#fn1][1]]}

<<v4>>
4 Festus jedoch antwortete, Paulus bleibe in Cäsarea in Haft und er
selbst wolle in Kürze abreisen.

<<v5>>
5 Die unter euch, die dafür zuständig sind, sagte er, können mit
hinabkommen, und wenn gegen den Mann etwas vorliegt, sollen sie gegen
ihn Anklage erheben.

<<v6>>
6 Er hielt sich nicht länger als acht oder zehn Tage bei ihnen auf, dann
reiste er nach Cäsarea hinab. Am folgenden Tag setzte er sich auf den
Richterstuhl und ließ Paulus vorführen.

<<v7>>
7 Als dieser erschien, umringten ihn die Juden, die von Jerusalem
herabgekommen waren, und brachten viele schwere Beschuldigungen vor,
konnten sie aber nicht beweisen.

<<v8>>
8 Paulus verteidigte sich: Ich habe mich weder gegen das Gesetz der
Juden noch gegen den Tempel noch gegen den Kaiser vergangen.

<<v9>>
9 Festus jedoch wollte den Juden einen Gefallen erweisen und antwortete
dem Paulus: Willst du nach Jerusalem hinaufgehen und dich dort unter
meinem Vorsitz dieser Sache wegen richten lassen? ^{[[#fn2][2]]}

<<v10>>
10 Paulus sagte: Ich stehe vor dem Richterstuhl des Kaisers und da muss
ich gerichtet werden. Den Juden habe ich kein Unrecht getan, wie auch du
sehr wohl weißt.

<<v11>>
11 Wenn ich wirklich ein Unrecht begangen und etwas getan habe, worauf
die Todesstrafe steht, weigere ich mich nicht zu sterben. Wenn aber ihre
Anklage gegen mich unbegründet ist, kann mich niemand ihnen ausliefern.
Ich lege Berufung beim Kaiser ein!

<<v12>>
12 Da besprach sich Festus mit seinen Ratgebern und antwortete: An den
Kaiser hast du appelliert; zum Kaiser sollst du gehen.\\
\\

<<v13>>
**** Paulus vor dem Statthalter Festus und König Agrippa: 25,13 - 26,32
     :PROPERTIES:
     :CUSTOM_ID: paulus-vor-dem-statthalter-festus-und-könig-agrippa-2513---2632
     :END:
13 Einige Tage später trafen König Agrippa und Berenike in Cäsarea ein,
um Festus ihre Aufwartung zu machen. ^{[[#fn3][3]]}

<<v14>>
14 Sie blieben mehrere Tage dort. Da trug Festus dem König den Fall des
Paulus vor und sagte: Von Felix ist ein Mann als Gefangener
zurückgelassen worden,

<<v15>>
15 gegen den die Hohenpriester und die Ältesten der Juden, als ich in
Jerusalem war, vorstellig wurden. Sie forderten seine Verurteilung,

<<v16>>
16 ich aber erwiderte ihnen, es sei bei den Römern nicht üblich, einen
Menschen auszuliefern, bevor nicht der Angeklagte den Anklägern
gegenübergestellt sei und Gelegenheit erhalten habe, sich gegen die
Anschuldigungen zu verteidigen.

<<v17>>
17 Als sie dann zusammen hierher kamen, setzte ich mich gleich am
nächsten Tag auf den Richterstuhl und ließ den Mann vorführen.

<<v18>>
18 Bei der Gegenüberstellung brachten die Kläger keine Anklage wegen
solcher Verbrechen vor, die ich vermutet hatte;

<<v19>>
19 sie führten nur einige Streitfragen gegen ihn ins Feld, die ihre
Religion und einen gewissen Jesus betreffen, der gestorben ist, von dem
Paulus aber behauptet, er lebe. ^{[[#fn4][4]]}

<<v20>>
20 Da ich mich auf die Untersuchung dieser Dinge nicht verstand, fragte
ich, ob er nach Jerusalem gehen wolle, um sich dort deswegen richten zu
lassen.

<<v21>>
21 Paulus jedoch legte Berufung ein; er wollte bis zur Entscheidung der
kaiserlichen Majestät in Haft bleiben. Daher gab ich Befehl, ihn in Haft
zu halten, bis ich ihn zum Kaiser schicken kann.

<<v22>>
22 Da sagte Agrippa zu Festus: Ich würde den Mann gern selbst hören.
Morgen, antwortete er, sollst du ihn hören.

<<v23>>
23 So kamen am folgenden Tag Agrippa und Berenike mit großem Gepränge
und betraten die Empfangshalle, zusammen mit den Obersten und den
vornehmsten Männern der Stadt. Auf Befehl des Festus wurde Paulus
vorgeführt,

<<v24>>
24 und Festus sagte: König Agrippa und all ihr Männer, die ihr hier bei
uns seid! Da seht ihr den Mann, dessentwegen mich alle Juden in
Jerusalem und auch hier bestürmt haben mit ihrem Geschrei, er dürfe
nicht länger am Leben bleiben.

<<v25>>
25 Ich aber konnte bei ihm nichts feststellen, worauf die Todesstrafe
steht. Da er jedoch selbst an die kaiserliche Majestät appelliert hat,
habe ich beschlossen, ihn hinzuschicken.

<<v26>>
26 Etwas Genaues über ihn weiß ich meinem Herrn allerdings nicht zu
schreiben. Darum habe ich ihn euch und vor allem dir, König Agrippa,
vorführen lassen, um nach dem Verhör zu wissen, was ich schreiben kann.

<<v27>>
27 Denn es scheint mir unsinnig, einen Gefangenen zu schicken, ohne
anzugeben, was man ihm vorwirft.

^{[[#fnm1][1]]} ℘ 23,15

^{[[#fnm2][2]]} ℘ 24,27

^{[[#fnm3][3]]} Es handelt sich um Herodes Agrippa II., Sohn des Herodes
Agrippa I (vgl. die Anmerkung zu 12,1). Er hielt zu den Römern, wurde 50
n. Chr. Tetrarch und 53 n. Chr. König, hatte aber nur sehr beschränkte
Rechte. Er war unverheiratet und lebte mit seiner Schwester Berenike
zusammen.

^{[[#fnm4][4]]} ℘ 18,15
