:PROPERTIES:
:ID:       02707c1b-6977-4993-a9e6-7593142885ff
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Apostelgeschichte* -- *1*
[[file:Apg_2.html][2]] [[file:Apg_3.html][3]] ...
[[file:Apg_28.html][28]]

--------------

* Apg 1
  :PROPERTIES:
  :CUSTOM_ID: apg-1
  :END:

Das Buch trägt in den griechischen Textausgaben seit dem 2. Jahrhundert
den Titel »Taten der Apostel«. Es wird in ihm jedoch hauptsächlich von
der Tätigkeit der Apostel Petrus und Johannes und von dem
missionarischen Wirken des Paulus erzählt, darüber hinaus noch vor allem
von Stephanus, Philippus, Barnabas und Jakobus. Als Verfasser gilt der
altkirchlichen Tradition Lukas, dem auch das dritte Evangelium
zugeschrieben wird (entstanden zwischen 80 und 90 n. Chr.), das er in
Apg 1,1 sein »erstes Buch« nennt.\\
\\
Den unmittelbaren Anlass zur Abfassung des Werkes kennen wir nicht mehr.
Lukas berichtet über die Zeit nach Ostern: wie der »Missionsbefehl« Jesu
(Lk 24,47; Apg 1,8) von Jerusalem aus »in ganz Judäa und Samarien und
bis an die Grenzen der Erde« ausgeführt wurde, wobei »die Grenzen der
Erde« mit Rom, der Hauptstadt des römischen Reiches, erreicht sind
(28,16-31). Doch wird dabei nicht alles erzählt, sondern nur wichtige
Episoden, Einzelereignisse (wie die Ausgießung des Geistes an Pfingsten,
die »Bekehrung« des Paulus und das »Apostelkonzil«) werden erwähnt.
Breiten Raum in der Schilderung nehmen die »Missionsreisen« ein. Die
Apostelgeschichte ist deshalb keine »Geschichte der Urkirche«, sondern
eine »Missionschronik«, die den Weg des Evangeliums von den Juden und
Samaritern zu den Heiden zeigt. Diese Missionschronik weist drei Teile
auf, die geographisch orientiert sind: die Kirche in Jerusalem (1,4 -
8,3), die Kirche in Judäa und Samarien (8,4 - 12,25), die Kirche unter
den Völkern (13,1 - 28,31). Ihre »Mitte« bildet die Erzählung über das
»Apostelkonzil« (Apg 15), auf dem die mit Paulus und Barnabas in
Jerusalem versammelten Apostel und Ältesten die Entscheidung fällen,
dass die Heidenchristen sich nicht der Beschneidung und den Weisungen
des jüdischen Gesetzes zu unterwerfen haben.\\
\\
Woher Lukas sein Wissen über das von ihm Erzählte hat, entzieht sich
unserer Kenntnis. Es besteht jedoch kein Zweifel, dass er auf
Überlieferungen zurückgreifen konnte; deren Umfang und Inhalt sind aber
nur schwer zu bestimmen. Sicher ist jedenfalls, dass er die Briefe des
Paulus bei der Abfassung der Apostelgeschichte nicht benutzt hat.\\
\\
Was Lukas seinen Lesern theologisch sagen will, geht vor allem aus den
Reden hervor, die in der Apostelgeschichte eine wichtige Rolle spielen:
Jetzt ist die Zeit der Kirche und das ist für Lukas die Zeit des
Heiligen Geistes, die die Zeit des Alten Bundes abgelöst hat und die
Zeit Jesu in die Gegenwart verlängert. Der Heilige Geist lenkt das Leben
der Kirche und die Wege der Missionare. Die »Naherwartung« der
Wiederkunft Jesu tritt deshalb zurück; jedoch ist Lukas wie die
Verfasser der übrigen Schriften des Neuen Testaments überzeugt, dass die
Endzeit bereits angebrochen ist. Das Heil, das Christus gebracht hat,
wird von den Missionaren nochmals den Juden angeboten, aber bald auch
den Heiden. Mit der Ankunft des Paulus in Rom wird endgültig sichtbar,
dass das Herz des jüdischen Volkes dem Evangelium gegenüber »verstockt«
bleibt und das Heil den Heiden gesandt wird, »und sie werden es hören«
(28,28; vgl. auch 13,46f; 18,6). So ist ein Hauptziel der
»Geschichtsschreibung« des Lukas in der Apostelgeschichte, die
allmähliche Loslösung der Kirche von Israel zu beschreiben. Am Ende
stehen sich Kirche und Judentum als zwei voneinander getrennte Größen
gegenüber.\\
\\

<<verses>>

<<v1>>
** Das Vorwort: 1,1-3
   :PROPERTIES:
   :CUSTOM_ID: das-vorwort-11-3
   :END:
1 Im ersten Buch, lieber Theophilus, habe ich über alles berichtet, was
Jesus getan und gelehrt hat, ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 bis zu dem Tag, an dem er (in den Himmel) aufgenommen wurde. Vorher
hat er durch den Heiligen Geist den Aposteln, die er sich erwählt hatte,
Anweisungen gegeben. ^{[[#fn3][3]][[#fn4][4]]}

<<v3>>
3 Ihnen hat er nach seinem Leiden durch viele Beweise gezeigt, dass er
lebt; vierzig Tage hindurch ist er ihnen erschienen und hat vom Reich
Gottes gesprochen. ^{[[#fn5][5]]}\\
\\

<<v4>>
** Die Kirche in Jerusalem: 1,4 - 8,3
   :PROPERTIES:
   :CUSTOM_ID: die-kirche-in-jerusalem-14---83
   :END:
**** Letzte Anweisungen und Belehrungen des Auferstandenen: 1,4-8
     :PROPERTIES:
     :CUSTOM_ID: letzte-anweisungen-und-belehrungen-des-auferstandenen-14-8
     :END:
4 Beim gemeinsamen Mahl gebot er ihnen: Geht nicht weg von Jerusalem,
sondern wartet auf die Verheißung des Vaters, die ihr von mir vernommen
habt. ^{[[#fn6][6]][[#fn7][7]]}

<<v5>>
5 Johannes hat mit Wasser getauft, ihr aber werdet schon in wenigen
Tagen mit dem Heiligen Geist getauft. ^{[[#fn8][8]]}

<<v6>>
6 Als sie nun beisammen waren, fragten sie ihn: Herr, stellst du in
dieser Zeit das Reich für Israel wieder her?

<<v7>>
7 Er sagte zu ihnen: Euch steht es nicht zu, Zeiten und Fristen zu
erfahren, die der Vater in seiner Macht festgesetzt hat.

<<v8>>
8 Aber ihr werdet die Kraft des Heiligen Geistes empfangen, der auf euch
herabkommen wird; und ihr werdet meine Zeugen sein in Jerusalem und in
ganz Judäa und Samarien und bis an die Grenzen der Erde.
^{[[#fn9][9]]}\\
\\

<<v9>>
**** Die Himmelfahrt Jesu: 1,9-11
     :PROPERTIES:
     :CUSTOM_ID: die-himmelfahrt-jesu-19-11
     :END:
9 Als er das gesagt hatte, wurde er vor ihren Augen emporgehoben, und
eine Wolke nahm ihn auf und entzog ihn ihren Blicken. ^{[[#fn10][10]]}

<<v10>>
10 Während sie unverwandt ihm nach zum Himmel emporschauten, standen
plötzlich zwei Männer in weißen Gewändern bei ihnen

<<v11>>
11 und sagten: Ihr Männer von Galiläa, was steht ihr da und schaut zum
Himmel empor? Dieser Jesus, der von euch ging und in den Himmel
aufgenommen wurde, wird ebenso wiederkommen, wie ihr ihn habt zum Himmel
hingehen sehen. ^{[[#fn11][11]]}\\
\\

<<v12>>
**** Betende Gemeinde: 1,12-14
     :PROPERTIES:
     :CUSTOM_ID: betende-gemeinde-112-14
     :END:
12 Dann kehrten sie vom Ölberg, der nur einen Sabbatweg von Jerusalem
entfernt ist, nach Jerusalem zurück. ^{[[#fn12][12]]}

<<v13>>
13 Als sie in die Stadt kamen, gingen sie in das Obergemach hinauf, wo
sie nun ständig blieben: Petrus und Johannes, Jakobus und Andreas,
Philippus und Thomas, Bartholomäus und Matthäus, Jakobus, der Sohn des
Alphäus, und Simon, der Zelot, sowie Judas, der Sohn des Jakobus.
^{[[#fn13][13]][[#fn14][14]]}

<<v14>>
14 Sie alle verharrten dort einmütig im Gebet, zusammen mit den Frauen
und mit Maria, der Mutter Jesu, und mit seinen Brüdern.
^{[[#fn15][15]][[#fn16][16]]}\\
\\

<<v15>>
**** Die Wahl des Matthias zum Apostel: 1,15-26
     :PROPERTIES:
     :CUSTOM_ID: die-wahl-des-matthias-zum-apostel-115-26
     :END:
15 In diesen Tagen erhob sich Petrus im Kreis der Brüder - etwa
hundertzwanzig waren zusammengekommen - und sagte:

<<v16>>
16 Brüder! Es musste sich das Schriftwort erfüllen, das der Heilige
Geist durch den Mund Davids im voraus über Judas gesprochen hat. Judas
wurde zum Anführer derer, die Jesus gefangen nahmen. ^{[[#fn17][17]]}

<<v17>>
17 Er wurde zu uns gezählt und hatte Anteil am gleichen Dienst.

<<v18>>
18 Mit dem Lohn für seine Untat kaufte er sich ein Grundstück. Dann aber
stürzte er vornüber zu Boden, sein Leib barst auseinander und alle
Eingeweide fielen heraus. ^{[[#fn18][18]]}

<<v19>>
19 Das wurde allen Einwohnern von Jerusalem bekannt; deshalb nannten sie
jenes Grundstück in ihrer Sprache Hakeldamach, das heißt Blutacker.

<<v20>>
20 Denn es steht im Buch der Psalmen: /Sein Gehöft soll veröden, niemand
soll darin wohnen!/ und: /Sein Amt soll ein anderer erhalten!/
^{[[#fn19][19]]}

<<v21>>
21 Einer von den Männern, die die ganze Zeit mit uns zusammen waren, als
Jesus, der Herr, bei uns ein und aus ging, ^{[[#fn20][20]]}

<<v22>>
22 angefangen von der Taufe durch Johannes bis zu dem Tag, an dem er von
uns ging und (in den Himmel) aufgenommen wurde, - einer von diesen muss
nun zusammen mit uns Zeuge seiner Auferstehung sein.

<<v23>>
23 Und sie stellten zwei Männer auf: Josef, genannt Barsabbas, mit dem
Beinamen Justus, und Matthias.

<<v24>>
24 Dann beteten sie: Herr, du kennst die Herzen aller; zeige, wen von
diesen beiden du erwählt hast, ^{[[#fn21][21]]}

<<v25>>
25 diesen Dienst und dieses Apostelamt zu übernehmen. Denn Judas hat es
verlassen und ist an den Ort gegangen, der ihm bestimmt war.

<<v26>>
26 Dann gaben sie ihnen Lose; das Los fiel auf Matthias und er wurde den
elf Aposteln zugerechnet. ^{[[#fn22][22]]}\\
\\

^{[[#fnm1][1]]} ℘ Lk 1,1-4

^{[[#fnm2][2]]} Bei dem «ersten Buch» handelt es sich um das
Lukasevangelium.

^{[[#fnm3][3]]} ℘ Lk 24,49; 1 Tim 3,16; Lk 24,44-48; Joh 20,22

^{[[#fnm4][4]]} Andere Übersetzungsmöglichkeit: Vorher hat er den
Aposteln, die er sich durch den Heiligen Geist erwählt hatte,
Anweisungen gegeben.

^{[[#fnm5][5]]} ℘ 10,41; 13,31

^{[[#fnm6][6]]} ℘ Lk 24,49

^{[[#fnm7][7]]} Beim gemeinsamen Mahl, andere Übersetzungsmöglichkeit:
Als sie beisammen waren.

^{[[#fnm8][8]]} ℘ 11,16; Mt 3,11

^{[[#fnm9][9]]} ℘ 2,1-13; 10,39; Mt 28,19; Mk 16,15; Lk 24,47f

^{[[#fnm10][10]]} ℘ Mk 16,19; Lk 24,51; 1 Tim 3,16; 1 Petr 3,22

^{[[#fnm11][11]]} ℘ Offb 1,7

^{[[#fnm12][12]]} Sabbatweg: etwa 1000 Meter - eine Wegstrecke, die man
gehen durfte, ohne das Gebot der Sabbatruhe zu verletzen.

^{[[#fnm13][13]]} ℘ Lk 6,14-16

^{[[#fnm14][14]]} 13f: Die genannten Gruppen und Personen bilden den
Kern der Urgemeinde. Mit den «Frauen» sind wohl jene gemeint, die nach
Lk 8,2f; 23,49.55f zur Begleitung Jesu gehörten.

^{[[#fnm15][15]]} ℘ Lk 23,49

^{[[#fnm16][16]]} Vgl. die Anmerkung zu Mt 12,46f.

^{[[#fnm17][17]]} ℘ Lk 22,47

^{[[#fnm18][18]]} ℘ Mt 27,3-10

^{[[#fnm19][19]]} ℘ Ps 69,26; 109,8

^{[[#fnm20][20]]} ℘ Joh 15,27

^{[[#fnm21][21]]} ℘ 15,8

^{[[#fnm22][22]]} ℘ 1 Sam 14,41f; Spr 16,33
