:PROPERTIES:
:ID:       6d4e09b3-2809-4557-9771-233de034c641
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Apostelgeschichte* --
[[file:Apg_1.html][1]] ... [[file:Apg_7.html][7]] [[file:Apg_8.html][8]]
*9* [[file:Apg_10.html][10]] [[file:Apg_11.html][11]] ...
[[file:Apg_28.html][28]]

--------------

* Apg 9
  :PROPERTIES:
  :CUSTOM_ID: apg-9
  :END:

<<verses>>

<<v1>>
**** Die Bekehrung des Saulus: 9,1-22
     :PROPERTIES:
     :CUSTOM_ID: die-bekehrung-des-saulus-91-22
     :END:
1 Saulus wütete immer noch mit Drohung und Mord gegen die Jünger des
Herrn. Er ging zum Hohenpriester ^{[[#fn1][1]]}

<<v2>>
2 und erbat sich von ihm Briefe an die Synagogen in Damaskus, um die
Anhänger des (neuen) Weges, Männer und Frauen, die er dort finde, zu
fesseln und nach Jerusalem zu bringen. ^{[[#fn2][2]][[#fn3][3]]}

<<v3>>
3 Unterwegs aber, als er sich bereits Damaskus näherte, geschah es, dass
ihn plötzlich ein Licht vom Himmel umstrahlte. ^{[[#fn4][4]]}

<<v4>>
4 Er stürzte zu Boden und hörte, wie eine Stimme zu ihm sagte: Saul,
Saul, warum verfolgst du mich?

<<v5>>
5 Er antwortete: Wer bist du, Herr? Dieser sagte: Ich bin Jesus, den du
verfolgst.

<<v6>>
6 Steh auf und geh in die Stadt; dort wird dir gesagt werden, was du tun
sollst.

<<v7>>
7 Seine Begleiter standen sprachlos da; sie hörten zwar die Stimme,
sahen aber niemand.

<<v8>>
8 Saulus erhob sich vom Boden. Als er aber die Augen öffnete, sah er
nichts. Sie nahmen ihn bei der Hand und führten ihn nach Damaskus
hinein.

<<v9>>
9 Und er war drei Tage blind und er aß nicht und trank nicht.

<<v10>>
10 In Damaskus lebte ein Jünger namens Hananias. Zu ihm sagte der Herr
in einer Vision: Hananias! Er antwortete: Hier bin ich, Herr.
^{[[#fn5][5]]}

<<v11>>
11 Der Herr sagte zu ihm: Steh auf und geh zur sogenannten Geraden
Straße und frag im Haus des Judas nach einem Mann namens Saulus aus
Tarsus. Er betet gerade ^{[[#fn6][6]]}

<<v12>>
12 und hat in einer Vision gesehen, wie ein Mann namens Hananias
hereinkommt und ihm die Hände auflegt, damit er wieder sieht.

<<v13>>
13 Hananias antwortete: Herr, ich habe von vielen gehört, wie viel Böses
dieser Mann deinen Heiligen in Jerusalem angetan hat.

<<v14>>
14 Auch hier hat er Vollmacht von den Hohenpriestern, alle zu verhaften,
die deinen Namen anrufen. ^{[[#fn7][7]]}

<<v15>>
15 Der Herr aber sprach zu ihm: Geh nur! Denn dieser Mann ist mein
auserwähltes Werkzeug: Er soll meinen Namen vor Völker und Könige und
die Söhne Israels tragen. ^{[[#fn8][8]]}

<<v16>>
16 Ich werde ihm auch zeigen, wie viel er für meinen Namen leiden muss.
^{[[#fn9][9]]}

<<v17>>
17 Da ging Hananias hin und trat in das Haus ein; er legte Saulus die
Hände auf und sagte: Bruder Saul, der Herr hat mich gesandt, Jesus, der
dir auf dem Weg hierher erschienen ist; du sollst wieder sehen und mit
dem Heiligen Geist erfüllt werden.

<<v18>>
18 Sofort fiel es wie Schuppen von seinen Augen und er sah wieder; er
stand auf und ließ sich taufen.

<<v19>>
19 Und nachdem er etwas gegessen hatte, kam er wieder zu Kräften. Einige
Tage blieb er bei den Jüngern in Damaskus;

<<v20>>
20 und sogleich verkündete er Jesus in den Synagogen und sagte: Er ist
der Sohn Gottes. ^{[[#fn10][10]]}

<<v21>>
21 Alle, die es hörten, gerieten in Aufregung und sagten: Ist das nicht
der Mann, der in Jerusalem alle vernichten wollte, die diesen Namen
anrufen? Und ist er nicht auch hierher gekommen, um sie zu fesseln und
vor die Hohenpriester zu führen?

<<v22>>
22 Saulus aber trat um so kraftvoller auf und brachte die Juden in
Damaskus in Verwirrung, weil er ihnen bewies, dass Jesus der Messias
ist. ^{[[#fn11][11]]}\\
\\

<<v23>>
**** Die Flucht des Saulus aus Damaskus: 9,23-31
     :PROPERTIES:
     :CUSTOM_ID: die-flucht-des-saulus-aus-damaskus-923-31
     :END:
23 So verging einige Zeit; da beschlossen die Juden, ihn zu töten.

<<v24>>
24 Doch ihr Plan wurde dem Saulus bekannt. Sie bewachten sogar Tag und
Nacht die Stadttore, um ihn zu beseitigen. ^{[[#fn12][12]]}

<<v25>>
25 Aber seine Jünger nahmen ihn und ließen ihn bei Nacht in einem Korb
die Stadtmauer hinab.

<<v26>>
26 Als er nach Jerusalem kam, versuchte er, sich den Jüngern
anzuschließen. Aber alle fürchteten sich vor ihm und konnten nicht
glauben, dass er ein Jünger war. ^{[[#fn13][13]]}

<<v27>>
27 Barnabas jedoch nahm sich seiner an und brachte ihn zu den Aposteln.
Er erzählte ihnen, wie Saulus auf dem Weg den Herrn gesehen habe und
dass dieser mit ihm gesprochen habe und wie er in Damaskus mutig und
offen im Namen Jesu aufgetreten sei. ^{[[#fn14][14]]}

<<v28>>
28 So ging er bei ihnen in Jerusalem ein und aus, trat unerschrocken im
Namen des Herrn auf

<<v29>>
29 und führte auch Streitgespräche mit den Hellenisten. Diese aber
planten, ihn zu töten.

<<v30>>
30 Als die Brüder das merkten, brachten sie ihn nach Cäsarea hinab und
schickten ihn von dort nach Tarsus. ^{[[#fn15][15]]}

<<v31>>
31 Die Kirche in ganz Judäa, Galiläa und Samarien hatte nun Frieden; sie
wurde gefestigt und lebte in der Furcht vor dem Herrn. Und sie wuchs
durch die Hilfe des Heiligen Geistes.\\
\\

<<v32>>
*** Die Aufnahme von Heiden in die Kirche: 9,32 - 12,25
    :PROPERTIES:
    :CUSTOM_ID: die-aufnahme-von-heiden-in-die-kirche-932---1225
    :END:
**** Petrus in Lydda und Joppe: 9,32-43
     :PROPERTIES:
     :CUSTOM_ID: petrus-in-lydda-und-joppe-932-43
     :END:
32 Auf einer Reise zu den einzelnen Gemeinden kam Petrus auch zu den
Heiligen in Lydda.

<<v33>>
33 Dort fand er einen Mann namens Äneas, der seit acht Jahren lahm und
bettlägerig war.

<<v34>>
34 Petrus sagte zu ihm: Äneas, Jesus Christus heilt dich. Steh auf und
richte dir dein Bett! Sogleich stand er auf.

<<v35>>
35 Und alle Bewohner von Lydda und der Scharon-Ebene sahen ihn und
bekehrten sich zum Herrn.

<<v36>>
36 In Joppe lebte eine Jüngerin namens Tabita, das heißt übersetzt:
Gazelle. Sie tat viele gute Werke und gab reichlich Almosen.

<<v37>>
37 In jenen Tagen aber wurde sie krank und starb. Man wusch sie und
bahrte sie im Obergemach auf.

<<v38>>
38 Weil aber Lydda nahe bei Joppe liegt und die Jünger hörten, dass
Petrus dort war, schickten sie zwei Männer zu ihm und ließen ihn bitten:
Komm zu uns, zögere nicht!

<<v39>>
39 Da stand Petrus auf und ging mit ihnen. Als er ankam, führten sie ihn
in das Obergemach hinauf; alle Witwen traten zu ihm, sie weinten und
zeigten ihm die Röcke und Mäntel, die Gazelle gemacht hatte, als sie
noch bei ihnen war.

<<v40>>
40 Petrus aber schickte alle hinaus, kniete nieder und betete. Dann
wandte er sich zu dem Leichnam und sagte: Tabita, steh auf! Da öffnete
sie ihre Augen, sah Petrus an und setzte sich auf. ^{[[#fn16][16]]}

<<v41>>
41 Er gab ihr die Hand und ließ sie aufstehen; dann rief er die Heiligen
und die Witwen und zeigte ihnen, dass sie wieder lebte.

<<v42>>
42 Das wurde in ganz Joppe bekannt und viele kamen zum Glauben an den
Herrn.

<<v43>>
43 Petrus aber blieb längere Zeit in Joppe bei einem gewissen Simon,
einem Gerber. ^{[[#fn17][17]]}\\
\\

^{[[#fnm1][1]]} ℘ 8,3; 1 Kor 15,9; Gal 1,13; (1-22) 22,5-16; 26,12-18

^{[[#fnm2][2]]} ℘ 19,9.23; 22,4; 24,14.22

^{[[#fnm3][3]]} «Der Weg» ist in der Apostelgeschichte Bezeichnung für
die christliche Lehre.

^{[[#fnm4][4]]} ℘ 1 Kor 9,1; 15,8; Gal 1,16

^{[[#fnm5][5]]} ℘ 10,17; 16,9

^{[[#fnm6][6]]} ℘ 21,39

^{[[#fnm7][7]]} ℘ 1 Kor 1,2; 2 Tim 2,22

^{[[#fnm8][8]]} ℘ 22,15; Röm 1,5; Gal 2,9; 1 Kor 1,17; 2 Kor 4,7

^{[[#fnm9][9]]} ℘ Mt 10,22; Lk 21,12f; 2 Kor 11,23-29

^{[[#fnm10][10]]} ℘ Mt 14,33; 16,16; 27,54; Mk 15,39; Lk 1,32.35; 22,70;
Joh 1,49; 11,27

^{[[#fnm11][11]]} ℘ 18,28

^{[[#fnm12][12]]} ℘ 2 Kor 11,32f

^{[[#fnm13][13]]} ℘ Gal 1,18

^{[[#fnm14][14]]} ℘ 4,36

^{[[#fnm15][15]]} ℘ 11,25; Gal 1,21

^{[[#fnm16][16]]} ℘ Mk 5,40f

^{[[#fnm17][17]]} ℘ 10,6
