:PROPERTIES:
:ID:       cbc7778c-6667-42ca-ba11-672621f429a4
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Apostelgeschichte* --
[[file:Apg_1.html][1]] ... [[file:Apg_21.html][21]]
[[file:Apg_22.html][22]] *23* [[file:Apg_24.html][24]]
[[file:Apg_25.html][25]] ... [[file:Apg_28.html][28]]

--------------

* Apg 23
  :PROPERTIES:
  :CUSTOM_ID: apg-23
  :END:

<<verses>>

<<v1>>
1 Paulus schaute mit festem Blick auf den Hohen Rat und sagte: Brüder!
Bis zum heutigen Tag lebe ich vor Gott mit völlig reinem Gewissen.
^{[[#fn1][1]]}

<<v2>>
2 Der Hohepriester Hananias aber befahl denen, die bei ihm standen, ihn
auf den Mund zu schlagen.

<<v3>>
3 Da sagte Paulus zu ihm: Dich wird Gott schlagen, du übertünchte Wand!
Du sitzt hier, um mich nach dem Gesetz zu richten, und entgegen dem
Gesetz befiehlst du, mich zu schlagen? ^{[[#fn2][2]]}

<<v4>>
4 Die Umstehenden sagten: Du wagst es, den Hohenpriester Gottes zu
schmähen?

<<v5>>
5 Paulus antwortete: Ich wusste nicht, Brüder, dass er der Hohepriester
ist. Denn es heißt in der Schrift: /Einen Fürsten deines Volkes sollst
du nicht verfluchen./ ^{[[#fn3][3]]}

<<v6>>
6 Da Paulus aber wusste, dass der eine Teil zu den Sadduzäern, der
andere zu den Pharisäern gehörte, rief er vor dem Hohen Rat aus: Brüder,
ich bin Pharisäer und ein Sohn von Pharisäern; wegen der Hoffnung und
wegen der Auferstehung der Toten stehe ich vor Gericht.
^{[[#fn4][4]][[#fn5][5]]}

<<v7>>
7 Als er das sagte, brach ein Streit zwischen den Pharisäern und den
Sadduzäern aus, und die Versammlung spaltete sich.

<<v8>>
8 Die Sadduzäer behaupten nämlich, es gebe weder eine Auferstehung noch
Engel noch Geister, die Pharisäer dagegen bekennen sich zu all dem.
^{[[#fn6][6]]}

<<v9>>
9 Es erhob sich ein lautes Geschrei und einige Schriftgelehrte aus dem
Kreis der Pharisäer standen auf und verfochten ihre Ansicht. Sie sagten:
Wir finden nichts Schlimmes an diesem Menschen. Vielleicht hat doch ein
Geist oder ein Engel zu ihm gesprochen.

<<v10>>
10 Als der Streit heftiger wurde, befürchtete der Oberst, sie könnten
Paulus zerreißen. Daher ließ er die Wachtruppe herabkommen, ihn mit
Gewalt aus ihrer Mitte herausholen und in die Kaserne bringen.

<<v11>>
11 In der folgenden Nacht aber trat der Herr zu Paulus und sagte: Hab
Mut! Denn so wie du in Jerusalem meine Sache bezeugt hast, sollst du
auch in Rom Zeugnis ablegen. ^{[[#fn7][7]]}\\
\\

<<v12>>
**** Die Verschwörung der Juden gegen Paulus: 23,12-22
     :PROPERTIES:
     :CUSTOM_ID: die-verschwörung-der-juden-gegen-paulus-2312-22
     :END:
12 Nach Tagesanbruch rotteten sich die Juden zusammen und schworen einen
heiligen Eid, weder zu essen noch zu trinken, bis sie Paulus getötet
hätten.

<<v13>>
13 An dieser Verschwörung waren mehr als vierzig Männer beteiligt.

<<v14>>
14 Sie gingen zu den Hohenpriestern und den Ältesten und sagten: Wir
haben mit einem heiligen Eid geschworen, nichts zu essen, bis wir Paulus
getötet haben.

<<v15>>
15 Geht also jetzt zusammen mit dem Hohen Rat zum Obersten und bittet
ihn, Paulus zu euch herunterzuführen, da ihr den Fall noch genauer
untersuchen wollt; wir aber halten uns bereit, um ihn, noch bevor er
hierher kommt, umzubringen.

<<v16>>
16 Der Neffe des Paulus, der Sohn seiner Schwester, erfuhr jedoch von
dem Anschlag. Er ging in die Kaserne und verständigte Paulus.

<<v17>>
17 Paulus ließ einen der Hauptleute rufen und sagte: Bring diesen jungen
Mann zum Obersten, denn er hat ihm etwas zu melden.

<<v18>>
18 Der nahm ihn mit sich, brachte ihn zum Obersten und sagte: Der
Gefangene Paulus hat mich gerufen und gebeten, diesen jungen Mann zu dir
zu führen, da er dir etwas mitzuteilen habe.

<<v19>>
19 Der Oberst fasste ihn bei der Hand, nahm ihn beiseite und fragte: Was
hast du mir zu melden?

<<v20>>
20 Er antwortete: Die Juden haben verabredet, dich zu bitten, du mögest
morgen den Paulus vor den Hohen Rat hinunterführen lassen. Angeblich
wollen sie Genaueres über ihn erfahren.

<<v21>>
21 Trau ihnen nicht! Denn mehr als vierzig Männer von ihnen lauern ihm
auf. Sie haben sich geschworen, weder zu essen noch zu trinken, bis sie
ihn umgebracht haben; schon stehen sie bereit und warten auf deine
Anordnung.

<<v22>>
22 Der Oberst befahl dem jungen Mann: Sag niemand etwas darüber, dass du
mir das angezeigt hast. Dann ließ er ihn gehen.\\
\\

<<v23>>
**** Die Überführung des Paulus nach Cäsarea: 23,23-35
     :PROPERTIES:
     :CUSTOM_ID: die-überführung-des-paulus-nach-cäsarea-2323-35
     :END:
23 Er rief zwei von den Hauptleuten und gab ihnen den Befehl: Haltet von
der dritten Stunde der Nacht an zweihundert Soldaten zum Marsch nach
Cäsarea bereit, außerdem siebzig Reiter und zweihundert
Leichtbewaffnete;

<<v24>>
24 auch Tragtiere soll man bereitstellen, Paulus aufsitzen lassen und
sicher zum Statthalter Felix bringen.

<<v25>>
25 Und er schrieb einen Brief mit folgendem Inhalt:

<<v26>>
26 Klaudius Lysias entbietet dem erlauchten Statthalter Felix seinen
Gruß! ^{[[#fn8][8]]}

<<v27>>
27 Dieser Mann wurde von den Juden ergriffen und wäre beinahe von ihnen
umgebracht worden; da habe ich mit der Wachtruppe eingegriffen und ihn
befreit. Ich hatte nämlich erfahren, dass er Römer ist. ^{[[#fn9][9]]}

<<v28>>
28 Und weil ich ermitteln wollte, wessen sie ihn beschuldigen, brachte
ich ihn vor ihren Hohen Rat. ^{[[#fn10][10]]}

<<v29>>
29 Ich fand heraus, dass er wegen Streitfragen über ihr Gesetz
angeschuldigt wird, dass aber keine Anklage gegen ihn vorliegt, auf die
Tod oder Haft steht. ^{[[#fn11][11]]}

<<v30>>
30 Da mir aber angezeigt wurde, gegen den Mann sei ein Anschlag geplant,
schicke ich ihn sogleich zu dir; auch habe ich die Kläger angewiesen,
ihre Sache gegen ihn bei dir vorzubringen.

<<v31>>
31 Die Soldaten übernahmen Paulus, wie ihnen befohlen war, und brachten
ihn bei Nacht bis Antipatris.

<<v32>>
32 Am anderen Tag ließen sie die Reiter mit ihm weiterziehen und kehrten
in die Kaserne zurück.

<<v33>>
33 Diese gaben nach ihrer Ankunft in Cäsarea den Brief beim Statthalter
ab und führten ihm Paulus vor.

<<v34>>
34 Er las (den Brief) und fragte Paulus, aus welcher Provinz er stamme.
Als er hörte, er sei aus Zilizien,

<<v35>>
35 sagte er: Ich werde dich vernehmen, sobald deine Ankläger
eingetroffen sind. Dann befahl er, ihn im Prätorium des Herodes in
Gewahrsam zu halten. ^{[[#fn12][12]]}\\
\\

^{[[#fnm1][1]]} ℘ 24,16; 2 Kor 1,12

^{[[#fnm2][2]]} ℘ Mt 23,27; Lev 19,15

^{[[#fnm3][3]]} ℘ Ex 22,27

^{[[#fnm4][4]]} ℘ 4,2; 22,3; 26,5

^{[[#fnm5][5]]} Paulus gibt zu verstehen, dass die christliche
Auferstehungshoffnung mit der Erwartung der Pharisäer übereinstimmt.

^{[[#fnm6][6]]} ℘ Lk 20,27; Mt 22,23

^{[[#fnm7][7]]} ℘ 18,9; 19,21; 27,24; 28,23.31

^{[[#fnm8][8]]} Felix war bis etwa 58 n. Chr. Statthalter von Judäa.

^{[[#fnm9][9]]} ℘ 21,33; 22,25

^{[[#fnm10][10]]} ℘ 22,30

^{[[#fnm11][11]]} ℘ 18,14f

^{[[#fnm12][12]]} ℘ 22,3
