:PROPERTIES:
:ID:       d816818e-4802-43af-8025-df6dbb0b163f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Epheser* -- *1*
[[file:Eph_2.html][2]] [[file:Eph_3.html][3]] ... [[file:Eph_6.html][6]]

--------------

* Eph 1
  :PROPERTIES:
  :CUSTOM_ID: eph-1
  :END:

Beim Epheserbrief handelt es sich wohl um einen Rundbrief, da die
Erwähnung von «Ephesus» (1,1) in zahlreichen Handschriften fehlt. Die
Empfänger sind sehr wahrscheinlich die Christen Kleinasiens oder eines
noch größeren Gebiets. Als Abfassungsort kommt Ephesus in Frage.\\
\\
Das Schreiben ist zwar wie ein Brief gestaltet, stellt aber nach Stil
und Inhalt eher eine feierliche Predigt dar. Lob Gottes (1,3) und
Fürbitte (1,16; 3,1.14) kennzeichnen den ersten Teil, der mit einem
liturgischen Lobpreis abschließt (3,21). Manche Forscher nehmen daher
an, dass dieses Schreiben von einem Paulusschüler verfasst wurde, der im
Namen des Apostels schrieb.\\
\\
Ein bestimmter Anlass für die Entstehung des Schreibens ist nicht
erkennbar. Das zentrale Thema des Briefs ist die Kirche, und zwar die
weltweite Kirche, deren Haupt Christus ist. Inhaltlich wird dieses Thema
in den Kapiteln 1 - 3 entfaltet. Gott hat die Kirche durch Christus
schon vor der Erschaffung der Welt erwählt und als sein Volk
zusammengerufen (Kap. 1). Durch die Taufe sind die Gläubigen der Macht
der Finsternis entrissen und mit Christus verbunden worden (2,1-10). In
der Kirche ist ein neues Menschengeschlecht entstanden, in dem die alte
Feindschaft zwischen Juden und Heiden überwunden wurde, weil Christus
Frieden gestiftet hat (2,11-22). Werkzeug Gottes für den Bau der
Völkerkirche war der Apostel Paulus (Kap. 3). Im zweiten Teil werden
sittliche Folgerungen gezogen. Vor allem gilt es, die Einheit zu wahren
und alle Dienste in der Kirche zu aktivieren (4,1-16). Als Getaufte
haben die Christen den alten, der Sünde verfallenen Menschen zu
überwinden und ein neues Leben zu verwirklichen, das durch Christus
erleuchtet ist (4,17 - 5,20). Das neue Leben hat sich vor allem in Ehe
und Familie auszuwirken (5,21 - 6,9). Das Bild vom Streiter Christi
schließt die Mahnung ab (6,10-20).\\
\\
Der Epheserbrief enthält die bedeutendsten theologischen Aussagen im
Neuen Testament über die Kirche.\\
\\

<<verses>>

<<v1>>
** Anschrift und Gruß: 1,1-2
   :PROPERTIES:
   :CUSTOM_ID: anschrift-und-gruß-11-2
   :END:
1 Paulus, durch den Willen Gottes Apostel Christi Jesu, an die Heiligen
in Ephesus, die an Christus Jesus glauben. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Gnade sei mit euch und Friede von Gott, unserem Vater, und dem Herrn
Jesus Christus.\\
\\

<<v3>>
** Gottes Heilsplan: 1,3 - 2,22
   :PROPERTIES:
   :CUSTOM_ID: gottes-heilsplan-13---222
   :END:
**** Loblied auf den Heilsplan Gottes: 1,3-14
     :PROPERTIES:
     :CUSTOM_ID: loblied-auf-den-heilsplan-gottes-13-14
     :END:
3 Gepriesen sei der Gott und Vater unseres Herrn Jesus Christus: /\\
 Er hat uns mit allem Segen seines Geistes gesegnet /\\
 durch unsere Gemeinschaft mit Christus im Himmel.
^{[[#fn3][3]][[#fn4][4]]}\\
\\

<<v4>>
4 Denn in ihm hat er uns erwählt vor der Erschaffung der Welt, /\\
 damit wir heilig und untadelig leben vor Gott;\\
\\

<<v5>>
5 er hat uns aus Liebe im Voraus dazu bestimmt, /\\
 seine Söhne zu werden durch Jesus Christus /\\
 und nach seinem gnädigen Willen zu ihm zu gelangen,\\
\\

<<v6>>
6 zum Lob seiner herrlichen Gnade. /\\
 Er hat sie uns geschenkt in seinem geliebten Sohn;\\
\\

<<v7>>
7 durch sein Blut haben wir die Erlösung, /\\
 die Vergebung der Sünden nach dem Reichtum seiner Gnade.
^{[[#fn5][5]]}\\
\\

<<v8>>
8 Durch sie hat er uns mit aller Weisheit und Einsicht reich beschenkt\\
\\

<<v9>>
9 und hat uns das Geheimnis seines Willens kundgetan, /\\
 wie er es gnädig im Voraus bestimmt hat: ^{[[#fn6][6]]}\\
\\

<<v10>>
10 Er hat beschlossen, die Fülle der Zeiten heraufzuführen, /\\
 in Christus alles zu vereinen, alles, was im Himmel und auf Erden ist.
^{[[#fn7][7]]}\\
\\

<<v11>>
11 Durch ihn sind wir auch als Erben vorherbestimmt und eingesetzt /\\
 nach dem Plan dessen, der alles so verwirklicht, /\\
 wie er es in seinem Willen beschließt;\\
\\

<<v12>>
12 wir sind zum Lob seiner Herrlichkeit bestimmt, /\\
 die wir schon früher auf Christus gehofft haben. ^{[[#fn8][8]]}\\
\\

<<v13>>
13 Durch ihn habt auch ihr das Wort der Wahrheit gehört, das Evangelium
von eurer Rettung; /\\
 durch ihn habt ihr das Siegel des verheißenen Heiligen Geistes
empfangen, als ihr den Glauben annahmt.\\
\\

<<v14>>
14 Der Geist ist der erste Anteil des Erbes, /\\
 das wir erhalten sollen, /\\
 der Erlösung, durch die wir Gottes Eigentum werden, /\\
 zum Lob seiner Herrlichkeit. ^{[[#fn9][9]]}\\
\\

<<v15.16>>
**** Gebet um Erkenntnis der Hoheit Christi: 1,15-23
     :PROPERTIES:
     :CUSTOM_ID: gebet-um-erkenntnis-der-hoheit-christi-115-23
     :END:
15.16 Darum höre ich nicht auf, für euch zu danken, wenn ich in meinen
Gebeten an euch denke; denn ich habe von eurem Glauben an Jesus, den
Herrn, und von eurer Liebe zu allen Heiligen gehört. ^{[[#fn10][10]]}

<<v17>>
17 Der Gott Jesu Christi, unseres Herrn, der Vater der Herrlichkeit,
gebe euch den Geist der Weisheit und Offenbarung, damit ihr ihn erkennt.

<<v18>>
18 Er erleuchte die Augen eures Herzens, damit ihr versteht, zu welcher
Hoffnung ihr durch ihn berufen seid, welchen Reichtum die Herrlichkeit
seines Erbes den Heiligen schenkt

<<v19>>
19 und wie überragend groß seine Macht sich an uns, den Gläubigen,
erweist durch das Wirken seiner Kraft und Stärke.

<<v20>>
20 Er hat sie an Christus erwiesen, den er von den Toten auferweckt und
im Himmel auf den Platz /zu seiner Rechten/ erhoben hat,
^{[[#fn11][11]]}

<<v21>>
21 hoch über alle Fürsten und Gewalten, Mächte und Herrschaften und über
jeden Namen, der nicht nur in dieser Welt, sondern auch in der
zukünftigen genannt wird. ^{[[#fn12][12]]}

<<v22>>
22 /Alles hat er ihm zu Füßen gelegt/ und ihn, der als Haupt alles
überragt, über die Kirche gesetzt. ^{[[#fn13][13]]}

<<v23>>
23 Sie ist sein Leib und wird von ihm erfüllt, der das All ganz und gar
beherrscht. ^{[[#fn14][14]]}\\
\\

^{[[#fnm1][1]]} ℘ Kol 1,1f

^{[[#fnm2][2]]} in Ephesus: fehlt bei zahlreichen Textzeugen; vgl. die
Einleitung.

^{[[#fnm3][3]]} ℘ 2 Kor 1,3

^{[[#fnm4][4]]} Die Gemeinschaft mit Christus (vgl. 1,13f) wurde durch
die Taufe begründet.

^{[[#fnm5][5]]} ℘ Kol 1,14

^{[[#fnm6][6]]} 9f: Der Verfasser spricht von einem «Geheimnis», weil
der Heilsplan, der durch Christus verwirklicht wurde, vorher nicht
bekannt war; auch jetzt kennen ihn nur die Glaubenden (vgl. die
Anmerkung zu 3,3-6).

^{[[#fnm7][7]]} ℘ Kol 1,20

^{[[#fnm8][8]]} Mit denen, die «schon früher auf Christus gehofft
haben», sind wohl die Judenchristen gemeint.

^{[[#fnm9][9]]} ℘ 2 Kor 1,22

^{[[#fnm10][10]]} ℘ Kol 1,3f.9

^{[[#fnm11][11]]} ℘ Ps 110,1

^{[[#fnm12][12]]} ℘ Kol 1,16

^{[[#fnm13][13]]} ℘ Ps 8,7; Hebr 8,6; Kol 1,18

^{[[#fnm14][14]]} Wörtlich: Sie ist sein Leib, die Fülle dessen, der
alles in allem erfüllt.
