:PROPERTIES:
:ID:       46a60abd-e405-451a-b558-67d97b38a290
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Galater* --
[[file:Gal_1.html][1]] ... [[file:Gal_4.html][4]] [[file:Gal_5.html][5]]
*6*

--------------

* Gal 6
  :PROPERTIES:
  :CUSTOM_ID: gal-6
  :END:

<<verses>>

<<v1>>
**** Das Gesetz Christi: 6,1-10
     :PROPERTIES:
     :CUSTOM_ID: das-gesetz-christi-61-10
     :END:
1 Wenn einer sich zu einer Verfehlung hinreißen lässt, meine Brüder, so
sollt ihr, die ihr vom Geist erfüllt seid, ihn im Geist der Sanftmut
wieder auf den rechten Weg bringen. Doch gib Acht, dass du nicht selbst
in Versuchung gerätst. ^{[[#fn1][1]]}

<<v2>>
2 Einer trage des anderen Last; so werdet ihr das Gesetz Christi
erfüllen. ^{[[#fn2][2]][[#fn3][3]]}

<<v3>>
3 Wer sich einbildet, etwas zu sein, obwohl er nichts ist, der betrügt
sich. ^{[[#fn4][4]]}

<<v4>>
4 Jeder prüfe sein eigenes Tun. Dann wird er sich nur im Blick auf sich
selbst rühmen können, nicht aber im Vergleich mit anderen.

<<v5>>
5 Denn jeder wird seine eigene Bürde zu tragen haben. ^{[[#fn5][5]]}

<<v6>>
6 Wer im Evangelium unterrichtet wird, lasse seinen Lehrer an allem
teilhaben, was er besitzt. ^{[[#fn6][6]][[#fn7][7]]}

<<v7>>
7 Täuscht euch nicht: Gott lässt keinen Spott mit sich treiben; was der
Mensch sät, wird er ernten.

<<v8>>
8 Wer im Vertrauen auf das Fleisch sät, wird vom Fleisch Verderben
ernten; wer aber im Vertrauen auf den Geist sät, wird vom Geist ewiges
Leben ernten. ^{[[#fn8][8]]}

<<v9>>
9 Lasst uns nicht müde werden, das Gute zu tun; denn wenn wir darin
nicht nachlassen, werden wir ernten, sobald die Zeit dafür gekommen ist.
^{[[#fn9][9]]}

<<v10>>
10 Deshalb wollen wir, solange wir noch Zeit haben, allen Menschen Gutes
tun, besonders aber denen, die mit uns im Glauben verbunden sind.\\
\\

<<v11>>
** Schlusswort und Segenswunsch: 6,11-18
   :PROPERTIES:
   :CUSTOM_ID: schlusswort-und-segenswunsch-611-18
   :END:
11 Seht, ich schreibe euch jetzt mit eigener Hand; das ist meine
Schrift. ^{[[#fn10][10]]}

<<v12>>
12 Jene Leute, die in der Welt nach Anerkennung streben, nötigen euch
nur deshalb zur Beschneidung, damit sie wegen des Kreuzes Christi nicht
verfolgt werden. ^{[[#fn11][11]][[#fn12][12]]}

<<v13>>
13 Denn obwohl sie beschnitten sind, halten sie nicht einmal selber das
Gesetz; dennoch dringen sie auf eure Beschneidung, um sich dessen zu
rühmen, was an eurem Fleisch geschehen soll. ^{[[#fn13][13]]}

<<v14>>
14 Ich aber will mich allein des Kreuzes Jesu Christi, unseres Herrn,
rühmen, durch das mir die Welt gekreuzigt ist und ich der Welt.
^{[[#fn14][14]]}

<<v15>>
15 Denn es kommt nicht darauf an, ob einer beschnitten oder
unbeschnitten ist, sondern darauf, dass er neue Schöpfung ist.
^{[[#fn15][15]]}

<<v16>>
16 Friede und Erbarmen komme über alle, die sich von diesem Grundsatz
leiten lassen, und über das Israel Gottes. ^{[[#fn16][16]]}

<<v17>>
17 In Zukunft soll mir niemand mehr solche Schwierigkeiten bereiten.
Denn ich trage die Zeichen Jesu an meinem Leib.
^{[[#fn17][17]][[#fn18][18]]}

<<v18>>
18 Die Gnade Jesu Christi, unseres Herrn, sei mit eurem Geist, meine
Brüder. Amen. ^{[[#fn19][19]]}\\
\\

^{[[#fnm1][1]]} ℘ Mt 18,15; Jak 5,19; 1 Kor 10,12

^{[[#fnm2][2]]} ℘ Kol 3,13; Röm 8,2; 1 Kor 9,21

^{[[#fnm3][3]]} Das «Gesetz Christi» ist das von Christus her
verstandene Gesetz, das erfüllt wird im «Glauben, der in der Liebe
wirksam ist» (5,6b; vgl. 5,14).

^{[[#fnm4][4]]} ℘ (3f) 1 Kor 8,2; 2 Kor 12,11

^{[[#fnm5][5]]} ℘ Röm 14,12

^{[[#fnm6][6]]} ℘ 1 Kor 9,11.14

^{[[#fnm7][7]]} Vgl. den Grundsatz Röm 15,27b.

^{[[#fnm8][8]]} ℘ Röm 8,6.13

^{[[#fnm9][9]]} ℘ 2 Thess 3,13; Hebr 12,1.3

^{[[#fnm10][10]]} ℘ 1 Kor 16,21

^{[[#fnm11][11]]} ℘ 5,2.11

^{[[#fnm12][12]]} 12-16: Das Judentum war im römischen Reich als
Minderheitenreligion anerkannt; eine als jüdisch gekennzeichnete
christliche Gemeinde wäre also vor staatlichen Eingriffen geschützt
gewesen. Demgegenüber betont der Apostel die Kreuzesnachfolge.

^{[[#fnm13][13]]} Das, was nach Wunsch der Irrlehrer am Fleisch
geschehen soll, ist, wie aus dem Zusammenhang hervorgeht, der Vollzug
der Beschneidung.

^{[[#fnm14][14]]} ℘ 2,19; 1 Kor 2,2

^{[[#fnm15][15]]} ℘ 5,6; 1 Kor 7,19; 2 Kor 5,17

^{[[#fnm16][16]]} ℘ Ps 125,4f

^{[[#fnm17][17]]} ℘ 2 Kor 4,10

^{[[#fnm18][18]]} Die «Zeichen Jesu», die Paulus an seinem Leib trägt,
sind Narben von Misshandlungen, die er im Dienst des Evangeliums
erlitten hat (vgl. 2 Kor 11,22-31). Er versteht sie als Teilhabe am Tod
Jesu (vgl. Röm 6,3; 2 Kor 4,10).

^{[[#fnm19][19]]} ℘ Phil 4,23; 2 Tim 4,22; Phlm 25
