:PROPERTIES:
:ID:       c63a63bc-ac30-444e-850d-120942fd3258
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Hebräer* --
[[file:Hebr_1.html][1]] ... [[file:Hebr_9.html][9]]
[[file:Hebr_10.html][10]] *11* [[file:Hebr_12.html][12]]
[[file:Hebr_13.html][13]]

--------------

* Hebr 11
  :PROPERTIES:
  :CUSTOM_ID: hebr-11
  :END:

<<verses>>

<<v1>>
*** Der Glaube der Väter: 11,1 - 12,3
    :PROPERTIES:
    :CUSTOM_ID: der-glaube-der-väter-111---123
    :END:
**** Die Urväter: 11,1-7
     :PROPERTIES:
     :CUSTOM_ID: die-urväter-111-7
     :END:
1 Glaube aber ist: Feststehen in dem, was man erhofft, Überzeugtsein von
Dingen, die man nicht sieht. ^{[[#fn1][1]]}

<<v2>>
2 Aufgrund dieses Glaubens haben die Alten ein ruhmvolles Zeugnis
erhalten.

<<v3>>
3 Aufgrund des Glaubens erkennen wir, dass die Welt durch Gottes Wort
erschaffen worden und dass so aus Unsichtbarem das Sichtbare entstanden
ist. ^{[[#fn2][2]]}

<<v4>>
4 Aufgrund des Glaubens brachte Abel Gott ein besseres Opfer dar als
Kain; durch diesen Glauben erhielt er das Zeugnis, dass er gerecht war,
da Gott es bei seinen Opfergaben bezeugte, und durch den Glauben redet
Abel noch, obwohl er tot ist. ^{[[#fn3][3]]}

<<v5>>
5 Aufgrund des Glaubens wurde Henoch entrückt und musste nicht sterben;
/er wurde nicht mehr gefunden, weil Gott ihn entrückt hatte;/ vor der
Entrückung erhielt er das Zeugnis, dass er /Gott gefiel./ ^{[[#fn4][4]]}

<<v6>>
6 Ohne Glauben aber ist es unmöglich, (Gott) /zu gefallen;/ denn wer zu
Gott kommen will, muss glauben, dass er ist und dass er denen, die ihn
suchen, ihren Lohn geben wird.

<<v7>>
7 Aufgrund des Glaubens wurde Noach das offenbart, was noch nicht
sichtbar war, und er baute in frommem Gehorsam eine Arche zur Rettung
seiner Familie; durch seinen Glauben sprach er der Welt das Urteil und
wurde Erbe der Gerechtigkeit, die aus dem Glauben kommt.
^{[[#fn5][5]]}\\
\\

<<v8>>
**** Die Patriarchen: 11,8-22
     :PROPERTIES:
     :CUSTOM_ID: die-patriarchen-118-22
     :END:
8 Aufgrund des Glaubens gehorchte Abraham dem Ruf, /wegzuziehen/ in ein
Land, das er zum Erbe erhalten sollte; und /er zog weg,/ ohne zu wissen,
wohin er kommen würde. ^{[[#fn6][6]]}

<<v9>>
9 Aufgrund des Glaubens /hielt er sich als Fremder im/ verheißenen
/Land/ wie in einem fremden Land /auf/ und wohnte mit Isaak und Jakob,
den Miterben derselben Verheißung, in Zelten; ^{[[#fn7][7]]}

<<v10>>
10 denn er erwartete die Stadt mit den festen Grundmauern, die Gott
selbst geplant und gebaut hat.

<<v11>>
11 Aufgrund des Glaubens empfing selbst Sara die Kraft, trotz ihres
Alters noch Mutter zu werden; denn sie hielt den für treu, der die
Verheißung gegeben hatte. ^{[[#fn8][8]][[#fn9][9]]}

<<v12>>
12 So stammen denn auch von einem einzigen Menschen, dessen Kraft
bereits erstorben war, viele ab: /zahlreich wie die Sterne am Himmel und
der Sand am Meeresstrand, den man nicht zählen kann./ ^{[[#fn10][10]]}

<<v13>>
13 Voll Glauben sind diese alle gestorben, ohne das Verheißene erlangt
zu haben; nur von fern haben sie es geschaut und gegrüßt und haben
bekannt, dass sie Fremde und Gäste auf Erden sind. ^{[[#fn11][11]]}

<<v14>>
14 Mit diesen Worten geben sie zu erkennen, dass sie eine Heimat suchen.

<<v15>>
15 Hätten sie dabei an die Heimat gedacht, aus der sie weggezogen waren,
so wäre ihnen Zeit geblieben zurückzukehren;

<<v16>>
16 nun aber streben sie nach einer besseren Heimat, nämlich der
himmlischen. Darum schämt sich Gott ihrer nicht, er schämt sich nicht,
ihr Gott genannt zu werden; denn er hat für sie eine Stadt vorbereitet.

<<v17>>
17 Aufgrund des Glaubens /brachte Abraham den Isaak dar, als er auf die
Probe gestellt wurde,/ und gab den /einzigen Sohn/ dahin, er, der die
Verheißungen empfangen hatte ^{[[#fn12][12]]}

<<v18>>
18 und zu dem gesagt worden war: /Durch Isaak wirst du Nachkommen
haben./ ^{[[#fn13][13]]}

<<v19>>
19 Er verließ sich darauf, dass Gott sogar die Macht hat, Tote zum Leben
zu erwecken; darum erhielt er Isaak auch zurück. Das ist ein Sinnbild.
^{[[#fn14][14]]}

<<v20>>
20 Aufgrund des Glaubens segnete Isaak Jakob und Esau im Hinblick auf
das Kommende. ^{[[#fn15][15]]}

<<v21>>
21 Aufgrund des Glaubens segnete Jakob sterbend jeden der Söhne Josefs
und /neigte sich über das obere Ende seines Stabes./
^{[[#fn16][16]][[#fn17][17]]}

<<v22>>
22 Aufgrund des Glaubens dachte Josef vor seinem Tod an den Auszug der
Israeliten und traf Anordnungen wegen seiner Gebeine. ^{[[#fn18][18]]}\\
\\

<<v23>>
**** Weitere Zeugen des Glaubens: 11,23 - 12,3
     :PROPERTIES:
     :CUSTOM_ID: weitere-zeugen-des-glaubens-1123---123
     :END:
23 Aufgrund des Glaubens /wurde/ Mose nach seiner Geburt /drei Monate
lang/ von seinen Eltern /verborgen, weil sie sahen, dass es ein schönes
Kind war,/ und weil sie sich vor dem Befehl des Königs nicht fürchteten.
^{[[#fn19][19]]}

<<v24>>
24 Aufgrund des Glaubens weigerte sich Mose, als er herangewachsen war,
Sohn einer Tochter des Pharao genannt zu werden; ^{[[#fn20][20]]}

<<v25>>
25 lieber wollte er sich zusammen mit dem Volk Gottes misshandeln
lassen, als flüchtigen Genuss von der Sünde zu haben;

<<v26>>
26 er hielt /die Schmach des Messias/ für einen größeren Reichtum als
die Schätze Ägyptens; denn er dachte an den künftigen Lohn.
^{[[#fn21][21]]}

<<v27>>
27 Aufgrund des Glaubens verließ er Ägypten, ohne Furcht vor dem Zorn
des Königs; er hielt standhaft aus, als sähe er den Unsichtbaren.
^{[[#fn22][22]]}

<<v28>>
28 Aufgrund des Glaubens vollzog er /das Pascha/ und /bestrich die
Türpfosten mit Blut,/ damit /der Vernichter/ ihre Erstgeborenen nicht
anrührte. ^{[[#fn23][23]]}

<<v29>>
29 Aufgrund des Glaubens zogen sie durch das Rote Meer wie über
trockenes Land; als die Ägypter das Gleiche versuchten, wurden sie vom
Meer verschlungen. ^{[[#fn24][24]]}

<<v30>>
30 Aufgrund des Glaubens geschah es, dass die Mauern von Jericho
einstürzten, nachdem man sieben Tage um sie herumgezogen war.
^{[[#fn25][25]]}

<<v31>>
31 Aufgrund des Glaubens kam die Dirne Rahab nicht zusammen mit den
Ungehorsamen um; denn sie hatte die Kundschafter in Frieden aufgenommen.
^{[[#fn26][26]]}

<<v32>>
32 Und was soll ich noch aufzählen? Die Zeit würde mir nicht reichen,
wollte ich von Gideon reden, von Barak, Simson, Jiftach, David und von
Samuel und den Propheten;

<<v33>>
33 sie haben aufgrund des Glaubens Königreiche besiegt, Gerechtigkeit
geübt, Verheißungen erlangt, Löwen den Rachen gestopft, ^{[[#fn27][27]]}

<<v34>>
34 Feuersglut gelöscht; sie sind scharfen Schwertern entgangen; sie sind
stark geworden, als sie schwach waren; sie sind im Krieg zu Helden
geworden und haben feindliche Heere in die Flucht geschlagen.
^{[[#fn28][28]]}

<<v35>>
35 Frauen haben ihre Toten durch Auferstehung zurückerhalten. Einige
nahmen die Freilassung nicht an und ließen sich foltern, um eine bessere
Auferstehung zu erlangen. ^{[[#fn29][29]][[#fn30][30]]}

<<v36>>
36 Andere haben Spott und Schläge erduldet, ja sogar Ketten und Kerker.

<<v37>>
37 Gesteinigt wurden sie, verbrannt, zersägt, mit dem Schwert
umgebracht; sie zogen in Schafspelzen und Ziegenfellen umher, Not
leidend, bedrängt, misshandelt. ^{[[#fn31][31]][[#fn32][32]]}

<<v38>>
38 Sie, deren die Welt nicht wert war, irrten umher in Wüsten und
Gebirgen, in den Höhlen und Schluchten des Landes. ^{[[#fn33][33]]}

<<v39>>
39 Doch sie alle, die aufgrund des Glaubens (von Gott) besonders
anerkannt wurden, haben das Verheißene nicht erlangt, ^{[[#fn34][34]]}

<<v40>>
40 weil Gott erst für uns etwas Besseres vorgesehen hatte; denn sie
sollten nicht ohne uns vollendet werden.

^{[[#fnm1][1]]} 1-40: Auch die Gerechten und Frommen der vorchristlichen
Zeit waren Glaubende und gehören daher zum einen Volk Gottes. Andere
Übersetzungsmöglichkeit: Der Glaube aber ist die Grundlage dessen, was
man erhofft, und die Gewissheit über Dinge, die man nicht sieht.

^{[[#fnm2][2]]} Andere Übersetzungsmöglichkeit: und dass das Sichtbare
nicht aus der Welt der Erscheinungen entstanden ist.

^{[[#fnm3][3]]} ℘ Gen 4,4

^{[[#fnm4][4]]} ℘ Gen 5,24 G

^{[[#fnm5][5]]} ℘ Gen 6,13-22; 7,1

^{[[#fnm6][6]]} ℘ Gen 12,1.4

^{[[#fnm7][7]]} ℘ Gen 26,3

^{[[#fnm8][8]]} ℘ Gen 17,19; 21,2

^{[[#fnm9][9]]} Textüberlieferung unsicher; möglich ist auch: Aufgrund
des Glaubens empfing er auch trotz seines Alters zusammen mit Sara die
Kraft zur Zeugung; denn er hielt . . .

^{[[#fnm10][10]]} ℘ Gen 22,17; Ex 32,13; Gen 15,5

^{[[#fnm11][11]]} ℘ Ps 39,13; 119,19

^{[[#fnm12][12]]} ℘ Gen 22,1f

^{[[#fnm13][13]]} ℘ Gen 21,12 G

^{[[#fnm14][14]]} ℘ Gen 22,1-18

^{[[#fnm15][15]]} ℘ Gen 27,28f.39f

^{[[#fnm16][16]]} ℘ Gen 47,31 G

^{[[#fnm17][17]]} So nach dem griechischen Text; nach dem hebräischen:
neigte sich über das Kopfende seines Bettes.

^{[[#fnm18][18]]} ℘ Gen 50,24

^{[[#fnm19][19]]} ℘ Ex 2,2

^{[[#fnm20][20]]} ℘ Ex 2,11f

^{[[#fnm21][21]]} ℘ Ps 69,10; 89,51f; Hebr 12,2; 13,13

^{[[#fnm22][22]]} ℘ Ex 2,15

^{[[#fnm23][23]]} ℘ Ex 12,11.13.22f

^{[[#fnm24][24]]} ℘ Ex 14,21-31

^{[[#fnm25][25]]} ℘ Jos 6,1-21

^{[[#fnm26][26]]} ℘ Jos 2,11f; 6,17.22-25

^{[[#fnm27][27]]} ℘ Dan 6,23

^{[[#fnm28][28]]} ℘ Dan 3,23-25

^{[[#fnm29][29]]} ℘ 2 Makk 6,18 - 7,42

^{[[#fnm30][30]]} Gedacht ist wohl an die Erweckung des Sohns der Witwe
von Sarepta durch den Propheten Elija (vgl. 1 Kön 17,17-24) und des
Sohns einer Frau aus Schunem durch den Propheten Elischa (vgl. 2 Kön
4,18-37).

^{[[#fnm31][31]]} ℘ 2 Chr 24,21

^{[[#fnm32][32]]} verbrannt, viele alte Textzeugen haben: erprobt (durch
Folter?).

^{[[#fnm33][33]]} ℘ 1 Sam 13,6

^{[[#fnm34][34]]} (von Gott) besonders anerkannt wurden, andere
Übersetzungsmöglichkeit: (von der Schrift) ein rühmliches Zeugnis
erhielten.
