:PROPERTIES:
:ID:       b7085847-2855-4a6b-8c10-9ec2082f7f80
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Hebräer* --
[[file:Hebr_1.html][1]] ... [[file:Hebr_3.html][3]]
[[file:Hebr_4.html][4]] *5* [[file:Hebr_6.html][6]]
[[file:Hebr_7.html][7]] ... [[file:Hebr_13.html][13]]

--------------

* Hebr 5
  :PROPERTIES:
  :CUSTOM_ID: hebr-5
  :END:

<<verses>>

<<v1>>
1 Denn jeder Hohepriester wird aus den Menschen ausgewählt und für die
Menschen eingesetzt zum Dienst vor Gott, um Gaben und Opfer für die
Sünden darzubringen.

<<v2>>
2 Er ist fähig, für die Unwissenden und Irrenden Verständnis
aufzubringen, da auch er der Schwachheit unterworfen ist;

<<v3>>
3 deshalb muss er für sich selbst ebenso wie für das Volk Sündopfer
darbringen. ^{[[#fn1][1]]}

<<v4>>
4 Und keiner nimmt sich eigenmächtig diese Würde, sondern er wird von
Gott berufen, so wie Aaron.\\
\\

<<v5>>
5 So hat auch Christus sich nicht selbst die Würde eines Hohenpriesters
verliehen, sondern der, der zu ihm gesprochen hat: /Mein Sohn bist du./
/\\
 /Heute habe ich dich gezeugt,/ ^{[[#fn2][2]]}\\
\\

<<v6>>
6 wie er auch an anderer Stelle sagt: /Du bist Priester auf ewig/ /\\
 /nach der Ordnung Melchisedeks./ ^{[[#fn3][3]]}

<<v7>>
7 Als er auf Erden lebte, hat er mit lautem Schreien und unter Tränen
Gebete und Bitten vor den gebracht, der ihn aus dem Tod retten konnte,
und er ist erhört und aus seiner Angst befreit worden.
^{[[#fn4][4]][[#fn5][5]]}

<<v8>>
8 Obwohl er der Sohn war, hat er durch Leiden den Gehorsam gelernt;
^{[[#fn6][6]]}

<<v9>>
9 zur Vollendung gelangt, ist er für alle, die ihm gehorchen, der
Urheber des /ewigen Heils/ geworden ^{[[#fn7][7]]}

<<v10>>
10 und wurde von Gott angeredet als «Hoherpriester /nach der Ordnung
Melchisedeks»./ ^{[[#fn8][8]]}\\
\\

<<v11>>
**** Die schwache Gemeinde: 5,11 - 6,12
     :PROPERTIES:
     :CUSTOM_ID: die-schwache-gemeinde-511---612
     :END:
11 Darüber hätten wir noch viel zu sagen; es ist aber schwer
verständlich zu machen, da ihr schwerhörig geworden seid. ^{[[#fn9][9]]}

<<v12>>
12 Denn obwohl ihr der Zeit nach schon Lehrer sein müsstet, braucht ihr
von neuem einen, der euch die Anfangsgründe der Lehre von der
Offenbarung Gottes beibringt; Milch habt ihr nötig, nicht feste Speise.
^{[[#fn10][10]]}

<<v13>>
13 Denn jeder, der noch mit Milch genährt wird, ist unfähig, richtiges
Reden zu verstehen; er ist ja ein unmündiges Kind; ^{[[#fn11][11]]}

<<v14>>
14 feste Speise aber ist für Erwachsene, deren Sinne durch Gewöhnung
geübt sind, Gut und Böse zu unterscheiden.

^{[[#fnm1][1]]} ℘ Lev 9,7

^{[[#fnm2][2]]} ℘ Ps 2,7

^{[[#fnm3][3]]} ℘ Ps 110,4

^{[[#fnm4][4]]} ℘ Mt 26,37f; Mk 14,33f

^{[[#fnm5][5]]} Als er auf Erden lebte, wörtlich: In den Tagen seines
Fleisches. und er ist . . . befreit worden: andere
Übersetzungsmöglichkeit: und er ist seiner Gottesfurcht wegen erhört
worden.

^{[[#fnm6][6]]} ℘ Phil 2,8

^{[[#fnm7][7]]} ℘ Jes 45,17 G

^{[[#fnm8][8]]} ℘ Ps 110,4

^{[[#fnm9][9]]} 11-6,6: Der Abschnitt weist auf die zweistufige
Glaubensunterweisung der Kirche zu jener Zeit und auf die Sakramente der
Taufe und der Eucharistie hin.

^{[[#fnm10][10]]} ℘ (12-14) 1 Kor 3,1-3

^{[[#fnm11][11]]} richtiges Reden, andere Übersetzungsmöglichkeit: die
rechte Lehre.
