:PROPERTIES:
:ID:       0d7ab99e-506c-41ce-98e0-59e5eb757684
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Hebräer* --
[[file:Hebr_1.html][1]] [[file:Hebr_2.html][2]] *3*
[[file:Hebr_4.html][4]] [[file:Hebr_5.html][5]] ...
[[file:Hebr_13.html][13]]

--------------

* Hebr 3
  :PROPERTIES:
  :CUSTOM_ID: hebr-3
  :END:

<<verses>>

<<v1>>
**** Der Sohn und Mose: 3,1-6
     :PROPERTIES:
     :CUSTOM_ID: der-sohn-und-mose-31-6
     :END:
1 Darum, heilige Brüder, die ihr an der himmlischen Berufung teilhabt,
schaut auf den Apostel und Hohenpriester, dem unser Bekenntnis gilt: auf
Jesus, ^{[[#fn1][1]]}

<<v2>>
2 der - wie auch /Mose in/ Gottes /Haus/ - dem /treu/ ist, der ihn
eingesetzt hat. ^{[[#fn2][2]]}

<<v3>>
3 Denn er hat größere Herrlichkeit empfangen als Mose, so wie der, der
ein Haus baut, größeren Ruhm genießt als das Haus.

<<v4>>
4 Denn jedes Haus wird von jemand erbaut; der aber, der alles erbaut
hat, ist Gott.

<<v5>>
5 /Mose/ war /in/ Gottes /ganzem Haus treu/ als /Diener,/ zum Zeugnis
der künftigen Offenbarungen; ^{[[#fn3][3]]}

<<v6>>
6 Christus aber ist /treu/ als Sohn, der über das /Haus/ Gottes gesetzt
ist; /sein Haus/ aber sind wir, wenn wir an der Zuversicht und an dem
stolzen Bewusstsein festhalten, das unsere Hoffnung uns verleiht.\\
\\

<<v7>>
**** Gottes Wort als Gericht: 3,7-19
     :PROPERTIES:
     :CUSTOM_ID: gottes-wort-als-gericht-37-19
     :END:
7 Darum beherzigt, was der Heilige Geist sagt: /Heute, wenn ihr seine
Stimme hört,/ / ^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v8>>
8 /verhärtet euer Herz nicht wie beim Aufruhr,/ /\\
 /wie in der Wüste am Tag der Versuchung./\\
\\

<<v9>>
9 /Dort haben eure Väter mich versucht,/ /\\
 /sie haben mich auf die Probe gestellt/ /\\
 /und hatten doch meine Taten gesehen,/ /\\
\\

<<v10>>
10 /vierzig Jahre lang./ Darum /war mir diese Generation zuwider/ /\\
 /und ich sagte: Immer geht ihr Herz in die Irre./ /\\
 /Sie erkannten meine Wege nicht./\\
\\

<<v11>>
11 /Darum habe ich in meinem Zorn geschworen:/ /\\
 /Sie sollen nicht in das Land meiner Ruhe kommen./\\
\\

<<v12>>
12 Gebt Acht, Brüder, dass keiner von euch ein böses, ungläubiges Herz
hat, dass keiner vom lebendigen Gott abfällt,

<<v13>>
13 sondern ermahnt einander jeden Tag, solange es noch heißt: /Heute,/
damit niemand von euch durch den Betrug der Sünde verhärtet wird;

<<v14>>
14 denn an Christus haben wir nur Anteil, wenn wir bis zum Ende an der
Zuversicht festhalten, die wir am Anfang hatten.\\
\\

<<v15>>
15 Wenn es heißt: /Heute, wenn ihr seine Stimme hört,/ /\\
 /verhärtet euer Herz nicht wie beim Aufruhr -/ ^{[[#fn6][6]]}\\
\\

<<v16>>
16 wer waren denn jene, die /hörten/ und /sich auflehnten/? Waren es
nicht alle, die unter Mose aus Ägypten ausgezogen waren?

<<v17>>
17 Wer /war ihm vierzig Jahre lang zuwider/? Nicht etwa die Sünder,
deren /Leichen in der Wüsteliegen blieben/? ^{[[#fn7][7]][[#fn8][8]]}

<<v18>>
18 Wem hat er geschworen, /sie sollen nicht in das Land seiner Ruhe
kommen,/ wenn nicht den Ungehorsamen?

<<v19>>
19 Und wir sehen, dass sie wegen ihres Unglaubens /nicht hineinkommen/
konnten.\\
\\

^{[[#fnm1][1]]} 1-5: Jesus überragt auch den Mittler des Alten Bundes,
Mose, kraft seines Wesens. - «Haus» ist Bild für das Volk Gottes.

^{[[#fnm2][2]]} ℘ Num 12,7 G

^{[[#fnm3][3]]} ℘ Num 12,7 G

^{[[#fnm4][4]]} ℘ (7-11) Ps 95,7-11

^{[[#fnm5][5]]} 7-4,13: Der Abschnitt verdeutlicht den Zweck des
Schreibens: Christen, die in Gefahr sind, vom Glauben abzufallen, zur
Treue aufzurufen (vgl. 5,11 - 6,8).

^{[[#fnm6][6]]} ℘ Ps 95,7f

^{[[#fnm7][7]]} ℘ Num 14,29

^{[[#fnm8][8]]} Wörtlich: deren Leiber . . . hinfielen.
