:PROPERTIES:
:ID:       a95ce949-ff52-4ff8-9b19-9a8dc0f99d78
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Hebräer* --
[[file:Hebr_1.html][1]] [[file:Hebr_2.html][2]] [[file:Hebr_3.html][3]]
*4* [[file:Hebr_5.html][5]] [[file:Hebr_6.html][6]] ...
[[file:Hebr_13.html][13]]

--------------

* Hebr 4
  :PROPERTIES:
  :CUSTOM_ID: hebr-4
  :END:

<<verses>>

<<v1>>
**** Gottes Wort als Verheißung: 4,1-13
     :PROPERTIES:
     :CUSTOM_ID: gottes-wort-als-verheißung-41-13
     :END:
1 Darum lasst uns ernsthaft besorgt sein, dass keiner von euch
zurückbleibt, solange die Verheißung, /in das Land seiner Ruhe zu
kommen,/ noch gilt. ^{[[#fn1][1]]}

<<v2>>
2 Denn uns ist die gleiche Freudenbotschaft verkündet worden wie jenen;
doch hat ihnen das Wort, das sie hörten, nichts genützt, weil es sich
nicht durch den Glauben mit den Hörern verband. ^{[[#fn2][2]]}\\
\\

<<v3>>
3 Denn wir, die wir gläubig geworden sind, /kommen in das Land der
Ruhe,/ wie er gesagt hat: /Darum habe ich in meinem Zorn geschworen:/
/\\
 /Sie sollen nicht in das Land meiner Ruhe kommen./ Zwar waren die Werke
seit der Erschaffung der Welt vollendet; ^{[[#fn3][3]]}\\
\\

<<v4>>
4 denn vom siebten Tag heißt es an einer Stelle: /Und Gott ruhte am
siebten Tag aus von all seinen Werken;/ ^{[[#fn4][4]]}

<<v5>>
5 hier aber heißt es: /Sie sollen nicht in das Land meiner Ruhe kommen./
^{[[#fn5][5]]}

<<v6>>
6 Da es nun dabei bleibt, dass einige hineinkommen, die aber, die früher
die Freudenbotschaft empfangen haben, wegen ihres Ungehorsams /nicht
hineingekommen sind,/\\
\\

<<v7>>
7 setzt er aufs Neue einen Tag fest, nämlich: /Heute,/ indem er durch
David, wie schon gesagt, nach so langer Zeit spricht: /Heute, wenn ihr
seine Stimme hört,/ /\\
 /verhärtet euer Herz nicht!/ ^{[[#fn6][6]]}\\
\\

<<v8>>
8 Denn hätte schon Josua sie in das Land der Ruhe geführt, so wäre nicht
von einem anderen, späteren Tag die Rede.

<<v9>>
9 Also ist dem Volk Gottes eine Sabbatruhe vorbehalten.

<<v10>>
10 Denn wer /in das Land seiner Ruhe gekommen ist,/ der ruht auch selbst
von seinen Werken aus, wie Gott von den seinigen. ^{[[#fn7][7]]}

<<v11>>
11 Bemühen wir uns also, /in/ jenes /Land der Ruhe zu kommen,/ damit
niemand aufgrund des gleichen Ungehorsams zu Fall kommt. ^{[[#fn8][8]]}

<<v12>>
12 Denn lebendig ist das Wort Gottes, kraftvoll und schärfer als jedes
zweischneidige Schwert; es dringt durch bis zur Scheidung von Seele und
Geist, von Gelenk und Mark; es richtet über die Regungen und Gedanken
des Herzens; ^{[[#fn9][9]]}

<<v13>>
13 vor ihm bleibt kein Geschöpf verborgen, sondern alles liegt nackt und
bloß vor den Augen dessen, dem wir Rechenschaft schulden.\\
\\

<<v14>>
** Christus, der wahre und endgültige Hohepriester des Neuen Bundes:
4,14 - 10,18
   :PROPERTIES:
   :CUSTOM_ID: christus-der-wahre-und-endgültige-hohepriester-des-neuen-bundes-414---1018
   :END:
**** Das Amt des Hohenpriesters: 4,14 - 5,10
     :PROPERTIES:
     :CUSTOM_ID: das-amt-des-hohenpriesters-414---510
     :END:
14 Da wir nun einen erhabenen Hohenpriester haben, der die Himmel
durchschritten hat, Jesus, den Sohn Gottes, lasst uns an dem Bekenntnis
festhalten. ^{[[#fn10][10]]}

<<v15>>
15 Wir haben ja nicht einen Hohenpriester, der nicht mitfühlen könnte
mit unserer Schwäche, sondern einen, der in allem wie wir in Versuchung
geführt worden ist, aber nicht gesündigt hat. ^{[[#fn11][11]]}

<<v16>>
16 Lasst uns also voll Zuversicht hingehen zum Thron der Gnade, damit
wir Erbarmen und Gnade finden und so Hilfe erlangen zur rechten Zeit.
^{[[#fn12][12]]}

^{[[#fnm1][1]]} ℘ Ps 95,11

^{[[#fnm2][2]]} die Freudenbotschaft, wörtlich: das Evangelium.

^{[[#fnm3][3]]} ℘ Ps 95,11

^{[[#fnm4][4]]} ℘ Gen 2,2 G

^{[[#fnm5][5]]} ℘ Ps 95,11

^{[[#fnm6][6]]} ℘ Ps 95,7f

^{[[#fnm7][7]]} ℘ Ps 95,11; Gen 2,2 G

^{[[#fnm8][8]]} Wörtlich: damit niemand . . . hinfällt (vgl. 3,17).

^{[[#fnm9][9]]} ℘ Weish 18,15f

^{[[#fnm10][10]]} 14-5,10: Jesus wird hier als Hoherpriester und sein
Wirken als priesterlicher Dienst der Versöhnung beschrieben. Als
alttestamentliches Vorbild wird der vorisraelitische Priesterkönig von
Jerusalem, Melchisedek, genannt (vgl. Gen 14,17-20; Ps 110,4; Hebr 7,
1-24).

^{[[#fnm11][11]]} ℘ Mt 4,1-11

^{[[#fnm12][12]]} ℘ 10,22
