:PROPERTIES:
:ID:       3e9b4205-b06b-4d98-b8c9-72215ffd5214
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief des Jakobus* --
[[file:Jak_1.html][1]] [[file:Jak_2.html][2]] [[file:Jak_3.html][3]] *4*
[[file:Jak_5.html][5]]

--------------

* Jak 4
  :PROPERTIES:
  :CUSTOM_ID: jak-4
  :END:

<<verses>>

<<v1>>
**** Warnung vor Zwietracht und Weltsinn: 4,1-12
     :PROPERTIES:
     :CUSTOM_ID: warnung-vor-zwietracht-und-weltsinn-41-12
     :END:
1 Woher kommen die Kriege bei euch, woher die Streitigkeiten? Doch nur
vom Kampf der Leidenschaften in eurem Innern.

<<v2>>
2 Ihr begehrt und erhaltet doch nichts. Ihr mordet und seid eifersüchtig
und könnt dennoch nichts erreichen. Ihr streitet und führt Krieg. Ihr
erhaltet nichts, weil ihr nicht bittet.

<<v3>>
3 Ihr bittet und empfangt doch nichts, weil ihr in böser Absicht bittet,
um es in eurer Leidenschaft zu verschwenden.

<<v4>>
4 Ihr Ehebrecher, wisst ihr nicht, dass Freundschaft mit der Welt
Feindschaft mit Gott ist? Wer also ein Freund der Welt sein will, der
wird zum Feind Gottes. ^{[[#fn1][1]]}

<<v5>>
5 Oder meint ihr, die Schrift sage ohne Grund: Eifersüchtig sehnt er
sich nach dem Geist, den er in uns wohnen ließ. ^{[[#fn2][2]]}

<<v6>>
6 Doch er gibt noch größere Gnade; darum heißt es auch: /Gott tritt den
Stolzen entgegen, den Demütigen aber schenkt er seine Gnade./
^{[[#fn3][3]]}

<<v7>>
7 Ordnet euch also Gott unter, leistet dem Teufel Widerstand; dann wird
er vor euch fliehen. ^{[[#fn4][4]]}

<<v8>>
8 Sucht die Nähe Gottes; dann wird er sich euch nähern. Reinigt die
Hände, ihr Sünder, läutert euer Herz, ihr Menschen mit zwei Seelen!

<<v9>>
9 Klagt und trauert und weint! Euer Lachen verwandle sich in Trauer,
eure Freude in Betrübnis. ^{[[#fn5][5]]}

<<v10>>
10 Demütigt euch vor dem Herrn; dann wird er euch erhöhen.
^{[[#fn6][6]]}

<<v11>>
11 Verleumdet einander nicht, Brüder! Wer seinen Bruder verleumdet oder
seinen Bruder verurteilt, verleumdet das Gesetz und verurteilt das
Gesetz; wenn du aber das Gesetz verurteilst, handelst du nicht nach dem
Gesetz, sondern bist sein Richter.

<<v12>>
12 Nur einer ist der Gesetzgeber und Richter: er, der die Macht hat, zu
retten und zu verderben. Wer aber bist du, dass du über deinen Nächsten
richtest?\\
\\

<<v13>>
**** Warnung vor Selbstsicherheit: 4,13-17
     :PROPERTIES:
     :CUSTOM_ID: warnung-vor-selbstsicherheit-413-17
     :END:
13 Ihr aber, die ihr sagt: Heute oder morgen werden wir in diese oder
jene Stadt reisen, dort werden wir ein Jahr bleiben, Handel treiben und
Gewinne machen -,

<<v14>>
14 ihr wisst doch nicht, was morgen mit eurem Leben sein wird. Rauch
seid ihr, den man eine Weile sieht; dann verschwindet er.

<<v15>>
15 Ihr solltet lieber sagen: Wenn der Herr will, werden wir noch leben
und dies oder jenes tun.

<<v16>>
16 Nun aber prahlt ihr voll Übermut; doch all dieses Prahlen ist
schlecht.

<<v17>>
17 Wer also das Gute tun kann und es nicht tut, der sündigt.\\
\\

^{[[#fnm1][1]]} «Ehebrecher» kann hier im übertragenen Sinn gebraucht
sein. Auch im Alten Testament haben die Propheten (z. B. Hos 2 - 3) den
Abfall von Gott als «Ehebruch» gebrandmarkt.

^{[[#fnm2][2]]} Die Herkunft des Zitats ist unbekannt. Der Sinn ist
vermutlich: Gott, der dem Menschen seinen Geist eingehaucht hat (Gen
2,7), macht diesem Geist gegenüber seinen Anspruch geltend. - Andere
Übersetzungsmöglichkeit: Neidisch zeigt der Geist, den er in uns wohnen
ließ, sein Verlangen.

^{[[#fnm3][3]]} ℘ Spr 3,34 G; 1 Petr 5,5

^{[[#fnm4][4]]} ℘ 1 Petr 5,8f

^{[[#fnm5][5]]} ℘ Lk 6,25

^{[[#fnm6][6]]} ℘ 1 Petr 5,6
