:PROPERTIES:
:ID:       56e06a78-3642-4a03-ab81-b585609739f5
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_16.html][16]]
[[file:Joh_17.html][17]] *18* [[file:Joh_19.html][19]]
[[file:Joh_20.html][20]] [[file:Joh_21.html][21]]

--------------

* Joh 18
  :PROPERTIES:
  :CUSTOM_ID: joh-18
  :END:

<<verses>>

<<v1>>
** Die Erhöhung Jesu: 18,1 - 20,29
   :PROPERTIES:
   :CUSTOM_ID: die-erhöhung-jesu-181---2029
   :END:
*** Das Leiden Jesu: 18,1 - 19,42
    :PROPERTIES:
    :CUSTOM_ID: das-leiden-jesu-181---1942
    :END:
**** Die Verhaftung: 18,1-11
     :PROPERTIES:
     :CUSTOM_ID: die-verhaftung-181-11
     :END:
1 Nach diesen Worten ging Jesus mit seinen Jüngern hinaus, auf die
andere Seite des Baches Kidron. Dort war ein Garten; in den ging er mit
seinen Jüngern hinein.
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 330\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Auch Judas, der Verräter, der ihn auslieferte, kannte den Ort, weil
Jesus dort oft mit seinen Jüngern zusammengekommen war.
^{[[#fn4][4]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 331\\
$ŽG://ESyn0812/\\
\\

<<v3>>
3 Judas holte die Soldaten und die Gerichtsdiener der Hohenpriester und
der Pharisäer und sie kamen dorthin mit Fackeln, Laternen und Waffen.
^{[[#fn5][5]][[#fn6][6]]}

<<v4>>
4 Jesus, der alles wusste, was mit ihm geschehen sollte, ging hinaus und
fragte sie: Wen sucht ihr?

<<v5>>
5 Sie antworteten ihm: Jesus von Nazaret. Er sagte zu ihnen: Ich bin es.
Auch Judas, der Verräter, stand bei ihnen.

<<v6>>
6 Als er zu ihnen sagte: Ich bin es!, wichen sie zurück und stürzten zu
Boden.

<<v7>>
7 Er fragte sie noch einmal: Wen sucht ihr? Sie sagten: Jesus von
Nazaret.

<<v8>>
8 Jesus antwortete: Ich habe euch gesagt, dass ich es bin. Wenn ihr mich
sucht, dann lasst diese gehen!

<<v9>>
9 So sollte sich das Wort erfüllen, das er gesagt hatte: Ich habe keinen
von denen verloren, die du mir gegeben hast. ^{[[#fn7][7]]}

<<v10>>
10 Simon Petrus aber, der ein Schwert bei sich hatte, zog es, schlug
nach dem Diener des Hohenpriesters und hieb ihm das rechte Ohr ab; der
Diener hieß Malchus.

<<v11>>
11 Da sagte Jesus zu Petrus: Steck das Schwert in die Scheide! Der
Kelch, den mir der Vater gegeben hat - soll ich ihn nicht trinken?
^{[[#fn8][8]]}\\
\\

<<v12>>
**** Das Verhör vor Hannas und die Verleugnung durch Petrus: 18,12-27
     :PROPERTIES:
     :CUSTOM_ID: das-verhör-vor-hannas-und-die-verleugnung-durch-petrus-1812-27
     :END:
12 Die Soldaten, ihre Befehlshaber und die Gerichtsdiener der Juden
nahmen Jesus fest, fesselten ihn

<<v13>>
13 und führten ihn zuerst zu Hannas; er war nämlich der Schwiegervater
des Kajaphas, der in jenem Jahr Hoherpriester war.
^{[[#fn9][9]][[#fn10][10]][[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 332\\
$ŽG://ESyn0812/\\
\\

<<v14>>
14 Kajaphas aber war es, der den Juden den Rat gegeben hatte: Es ist
besser, dass ein einziger Mensch für das Volk stirbt. ^{[[#fn12][12]]}

<<v15>>
15 Simon Petrus und ein anderer Jünger folgten Jesus. Dieser Jünger war
mit dem Hohenpriester bekannt und ging mit Jesus in den Hof des
hohepriesterlichen Palastes. ^{[[#fn13][13]][[#fn14][14]]}

<<v16>>
16 Petrus aber blieb draußen am Tor stehen. Da kam der andere Jünger,
der Bekannte des Hohenpriesters, heraus; er sprach mit der Pförtnerin
und führte Petrus hinein.

<<v17>>
17 Da sagte die Pförtnerin zu Petrus: Bist du nicht auch einer von den
Jüngern dieses Menschen? Er antwortete: Nein.

<<v18>>
18 Die Diener und die Knechte hatten sich ein Kohlenfeuer angezündet und
standen dabei, um sich zu wärmen; denn es war kalt. Auch Petrus stand
bei ihnen und wärmte sich.

<<v19>>
19 Der Hohepriester befragte Jesus über seine Jünger und über seine
Lehre. ^{[[#fn15][15]]}

<<v20>>
20 Jesus antwortete ihm: Ich habe offen vor aller Welt gesprochen. Ich
habe immer in der Synagoge und im Tempel gelehrt, wo alle Juden
zusammenkommen. Nichts habe ich im Geheimen gesprochen.

<<v21>>
21 Warum fragst du mich? Frag doch die, die mich gehört haben, was ich
zu ihnen gesagt habe; sie wissen, was ich geredet habe.

<<v22>>
22 Auf diese Antwort hin schlug einer von den Knechten, der dabeistand,
Jesus ins Gesicht und sagte: Redest du so mit dem Hohenpriester?

<<v23>>
23 Jesus entgegnete ihm: Wenn es nicht recht war, was ich gesagt habe,
dann weise es nach; wenn es aber recht war, warum schlägst du mich?

<<v24>>
24 Danach schickte ihn Hannas gefesselt zum Hohenpriester Kajaphas.
^{[[#fn16][16]]}

<<v25>>
25 Simon Petrus aber stand (am Feuer) und wärmte sich. Sie sagten zu
ihm: Bist nicht auch du einer von seinen Jüngern? Er leugnete und sagte:
Nein. ^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 333\\
$ŽG://ESyn0812/\\
\\

<<v26>>
26 Einer von den Dienern des Hohenpriesters, ein Verwandter dessen, dem
Petrus das Ohr abgehauen hatte, sagte: Habe ich dich nicht im Garten bei
ihm gesehen?

<<v27>>
27 Wieder leugnete Petrus und gleich darauf krähte ein Hahn.\\
\\

<<v28>>
**** Das Verhör und die Verurteilung durch Pilatus: 18,28 - 19,16a
     :PROPERTIES:
     :CUSTOM_ID: das-verhör-und-die-verurteilung-durch-pilatus-1828---1916a
     :END:
28 Von Kajaphas brachten sie Jesus zum Prätorium; es war früh am Morgen.
Sie selbst gingen nicht in das Gebäude hinein, um nicht unrein zu
werden, sondern das Paschalamm essen zu können.
^{[[#fn18][18]][[#fn19][19]][[#fn20][20]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 334\\
$ŽG://ESyn0812/\\
\\

<<v29>>
29 Deshalb kam Pilatus zu ihnen heraus und fragte: Welche Anklage erhebt
ihr gegen diesen Menschen?
^{[[#fn21][21]][[#fn22][22]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 336\\
$ŽG://ESyn0812/\\
\\

<<v30>>
30 Sie antworteten ihm: Wenn er kein Übeltäter wäre, hätten wir ihn dir
nicht ausgeliefert.

<<v31>>
31 Pilatus sagte zu ihnen: Nehmt ihr ihn doch und richtet ihn nach eurem
Gesetz! Die Juden antworteten ihm: Uns ist es nicht gestattet, jemand
hinzurichten. ^{[[#fn23][23]]}

<<v32>>
32 So sollte sich das Wort Jesu erfüllen, mit dem er angedeutet hatte,
auf welche Weise er sterben werde. ^{[[#fn24][24]]}

<<v33>>
33 Pilatus ging wieder in das Prätorium hinein, ließ Jesus rufen und
fragte ihn: Bist du der König der Juden? ^{[[#fn25][25]]}

<<v34>>
34 Jesus antwortete: Sagst du das von dir aus, oder haben es dir andere
über mich gesagt?

<<v35>>
35 Pilatus entgegnete: Bin ich denn ein Jude? Dein eigenes Volk und die
Hohenpriester haben dich an mich ausgeliefert. Was hast du getan?

<<v36>>
36 Jesus antwortete: Mein Königtum ist nicht von dieser Welt. Wenn es
von dieser Welt wäre, würden meine Leute kämpfen, damit ich den Juden
nicht ausgeliefert würde. Aber mein Königtum ist nicht von hier.

<<v37>>
37 Pilatus sagte zu ihm: Also bist du doch ein König? Jesus antwortete:
Du sagst es, ich bin ein König. Ich bin dazu geboren und dazu in die
Welt gekommen, dass ich für die Wahrheit Zeugnis ablege. Jeder, der aus
der Wahrheit ist, hört auf meine Stimme.

<<v38>>
38 Pilatus sagte zu ihm: Was ist Wahrheit? Nachdem er das gesagt hatte,
ging er wieder zu den Juden hinaus und sagte zu ihnen: Ich finde keinen
Grund, ihn zu verurteilen.

<<v39>>
39 Ihr seid gewohnt, dass ich euch am Paschafest einen Gefangenen
freilasse. Wollt ihr also, dass ich euch den König der Juden freilasse?
^{[[#fn26][26]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 339\\
$ŽG://ESyn0812/\\
\\

<<v40>>
40 Da schrien sie wieder: Nicht diesen, sondern Barabbas! Barabbas aber
war ein Straßenräuber. ^{[[#fn27][27]]}

^{[[#fnm1][1]]} ℘ (1-2) Mt 26,30-36; Mk 14,26-32; Lk 22,39

^{[[#fnm2][2]]} 1-19,42: Der Passionsbericht des vierten Evangelisten
zeigt die Eigenart der johanneischen Theologie. Johannes will im
Leidensweg Jesu und seinem Tod am Kreuz die göttliche Hoheit und Würde,
seine Erhöhung und Verherrlichung aufleuchten lassen. Die
Überlieferungen der drei ersten Evangelien übernimmt er nur teilweise
und ordnet sie bei seiner Darstellung der eigenen Absicht unter. Der
Kidron ist der Bach im tiefen Taleinschnitt zwischen Jerusalem und dem
östlich davon liegenden Ölberg.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 330

^{[[#fnm4][4]]} ℘ ⇨Esyn: Synopse Nr. 331

^{[[#fnm5][5]]} ℘ (3-11) Mt 26,47-56; Mk 14,43-50; Lk 22,47-53

^{[[#fnm6][6]]} Soldaten, wörtlich: die Abteilung (Kohorte). Damit wird
sonst die römische Garnison, die in Jerusalem lag, bezeichnet.

^{[[#fnm7][7]]} ℘ 6,39; 10,28; 17,12

^{[[#fnm8][8]]} ℘ 12,27; Mt 20,22

^{[[#fnm9][9]]} ℘ Lk 3,2; Apg 4,6

^{[[#fnm10][10]]} Zu Hannas vgl. die Anmerkungen zu Mk 14,53-65 und zu
Lk 3,1f.

^{[[#fnm11][11]]} ℘ ⇨Esyn: Synopse Nr. 332

^{[[#fnm12][12]]} ℘ 11,50

^{[[#fnm13][13]]} ℘ (15-27) Mt 26,58.69-75; Mk 14,54.66-72; Lk 22,54-62

^{[[#fnm14][14]]} ein anderer Jünger: vielleicht «der Jünger, den Jesus
liebte» (13,23-26; 19,26f; 20,3-10; 21,7.20 - 23.24).

^{[[#fnm15][15]]} ℘ (19-24) Mt 26,63-65; 27,1; Mk 14,61-64; 15,1; Lk
22,66-71

^{[[#fnm16][16]]} Über den Prozess vor dem Gerichtshof der Juden sagt
das Johannesevangelium weiter nichts.

^{[[#fnm17][17]]} ℘ ⇨Esyn: Synopse Nr. 333

^{[[#fnm18][18]]} ℘ (28-38a) Mt 27,2.11-26; Mk 15,1-15; Lk 23,1-7.13-15

^{[[#fnm19][19]]} Prätorium: der Amtssitz des römischen Statthalters
(Prokurators), wahrscheinlich der Herodespalast. Das Betreten eines
heidnischen Hauses machte nach jüdischer Anschauung unrein (vgl. Apg
10,28; 11,1 und die Anmerkung zu Mt 8,5-10).

^{[[#fnm20][20]]} ℘ ⇨Esyn: Synopse Nr. 334

^{[[#fnm21][21]]} Zu Pilatus vgl. die Anmerkung zu Mt 27,11-26.

^{[[#fnm22][22]]} ℘ ⇨Esyn: Synopse Nr. 336

^{[[#fnm23][23]]} Die Römer hatten das Recht über Leben und Tod dem
Hohen Rat entzogen (vgl. die Anmerkung zu Mt 27,11-26).

^{[[#fnm24][24]]} ℘ 3,14; 12,32f

^{[[#fnm25][25]]} ℘ 12,13; 19,15.19-22

^{[[#fnm26][26]]} ℘ (39-40) Mt 27,15-26; Mk 15,6-15; Lk 23,6-22 ⇨Esyn:
Synopse Nr. 339

^{[[#fnm27][27]]} Zu Barabbas vgl. die Anmerkung zu Mt 27,15-18.
