:PROPERTIES:
:ID:       bb9f5c02-3e83-4f6a-bb0d-897fceab76fe
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_7.html][7]] [[file:Joh_8.html][8]]
*9* [[file:Joh_10.html][10]] [[file:Joh_11.html][11]] ...
[[file:Joh_21.html][21]]

--------------

* Joh 9
  :PROPERTIES:
  :CUSTOM_ID: joh-9
  :END:

<<verses>>

<<v1>>
*** Die Heilung eines Blinden und der Streit der Juden: 9,1-42
    :PROPERTIES:
    :CUSTOM_ID: die-heilung-eines-blinden-und-der-streit-der-juden-91-42
    :END:
**** Die Heilung eines Blinden: 9,1-12
     :PROPERTIES:
     :CUSTOM_ID: die-heilung-eines-blinden-91-12
     :END:
1 Unterwegs sah Jesus einen Mann, der seit seiner Geburt blind war.
^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 248\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Da fragten ihn seine Jünger: Rabbi, wer hat gesündigt? Er selbst? Ober
haben seine Eltern gesündigt, sodass er blind geboren wurde?

<<v3>>
3 Jesus antwortete: Weder er noch seine Eltern haben gesündigt, sondern
das Wirken Gottes soll an ihm offenbar werden.

<<v4>>
4 Wir müssen, solange es Tag ist, die Werke dessen vollbringen, der mich
gesandt hat; es kommt die Nacht, in der niemand mehr etwas tun kann.

<<v5>>
5 Solange ich in der Welt bin, bin ich das Licht der Welt.
^{[[#fn2][2]]}

<<v6>>
6 Als er dies gesagt hatte, spuckte er auf die Erde; dann machte er mit
dem Speichel einen Teig, strich ihn dem Blinden auf die Augen

<<v7>>
7 und sagte zu ihm: Geh und wasch dich in dem Teich Schiloach! Schiloach
heißt übersetzt: Der Gesandte. Der Mann ging fort und wusch sich. Und
als er zurückkam, konnte er sehen. ^{[[#fn3][3]][[#fn4][4]]}

<<v8>>
8 Die Nachbarn und andere, die ihn früher als Bettler gesehen hatten,
sagten: Ist das nicht der Mann, der dasaß und bettelte?

<<v9>>
9 Einige sagten: Er ist es. Andere meinten: Nein, er sieht ihm nur
ähnlich. Er selbst aber sagte: Ich bin es.

<<v10>>
10 Da fragten sie ihn: Wie sind deine Augen geöffnet worden?

<<v11>>
11 Er antwortete: Der Mann, der Jesus heißt, machte einen Teig, bestrich
damit meine Augen und sagte zu mir: Geh zum Schiloach und wasch dich!
Ich ging hin, wusch mich und konnte wieder sehen.

<<v12>>
12 Sie fragten ihn: Wo ist er? Er sagte: Ich weiß es nicht.\\
\\

<<v13>>
**** Das Eingreifen der Pharisäer: 9,13-34
     :PROPERTIES:
     :CUSTOM_ID: das-eingreifen-der-pharisäer-913-34
     :END:
13 Da brachten sie den Mann, der blind gewesen war, zu den Pharisäern.

<<v14>>
14 Es war aber Sabbat an dem Tag, als Jesus den Teig gemacht und ihm die
Augen geöffnet hatte. ^{[[#fn5][5]]}

<<v15>>
15 Auch die Pharisäer fragten ihn, wie er sehend geworden sei. Der Mann
antwortete ihnen: Er legte mir einen Teig auf die Augen; dann wusch ich
mich und jetzt kann ich sehen.

<<v16>>
16 Einige der Pharisäer meinten: Dieser Mensch kann nicht von Gott sein,
weil er den Sabbat nicht hält. Andere aber sagten: Wie kann ein Sünder
solche Zeichen tun? So entstand eine Spaltung unter ihnen.

<<v17>>
17 Da fragten sie den Blinden noch einmal: Was sagst du selbst über ihn?
Er hat doch deine Augen geöffnet. Der Mann antwortete: Er ist ein
Prophet.

<<v18>>
18 Die Juden aber wollten nicht glauben, dass er blind gewesen und
sehend geworden war. Daher riefen sie die Eltern des Geheilten

<<v19>>
19 und fragten sie: Ist das euer Sohn, von dem ihr behauptet, dass er
blind geboren wurde? Wie kommt es, dass er jetzt sehen kann?

<<v20>>
20 Seine Eltern antworteten: Wir wissen, dass er unser Sohn ist und dass
er blind geboren wurde.

<<v21>>
21 Wie es kommt, dass er jetzt sehen kann, das wissen wir nicht. Und wer
seine Augen geöffnet hat, das wissen wir auch nicht. Fragt doch ihn
selbst, er ist alt genug und kann selbst für sich sprechen.

<<v22>>
22 Das sagten seine Eltern, weil sie sich vor den Juden fürchteten; denn
die Juden hatten schon beschlossen, jeden, der ihn als den Messias
bekenne, aus der Synagoge auszustoßen. ^{[[#fn6][6]][[#fn7][7]]}

<<v23>>
23 Deswegen sagten seine Eltern: Er ist alt genug, fragt doch ihn
selbst.

<<v24>>
24 Da riefen die Pharisäer den Mann, der blind gewesen war, zum zweiten
Mal und sagten zu ihm: Gib Gott die Ehre! Wir wissen, dass dieser Mensch
ein Sünder ist. ^{[[#fn8][8]]}

<<v25>>
25 Er antwortete: Ob er ein Sünder ist, weiß ich nicht. Nur das eine
weiß ich, dass ich blind war und jetzt sehen kann.

<<v26>>
26 Sie fragten ihn: Was hat er mit dir gemacht? Wie hat er deine Augen
geöffnet?

<<v27>>
27 Er antwortete ihnen: Ich habe es euch bereits gesagt, aber ihr habt
nicht gehört. Warum wollt ihr es noch einmal hören? Wollt auch ihr seine
Jünger werden?

<<v28>>
28 Da beschimpften sie ihn: Du bist ein Jünger dieses Menschen; wir aber
sind Jünger des Mose.

<<v29>>
29 Wir wissen, dass zu Mose Gott gesprochen hat; aber von dem da wissen
wir nicht, woher er kommt. ^{[[#fn9][9]]}

<<v30>>
30 Der Mann antwortete ihnen: Darin liegt ja das Erstaunliche, dass ihr
nicht wisst, woher er kommt; dabei hat er doch meine Augen geöffnet.

<<v31>>
31 Wir wissen, dass Gott einen Sünder nicht erhört; wer aber Gott
fürchtet und seinen Willen tut, den erhört er.

<<v32>>
32 Noch nie hat man gehört, dass jemand die Augen eines Blindgeborenen
geöffnet hat.

<<v33>>
33 Wenn dieser Mensch nicht von Gott wäre, dann hätte er gewiss nichts
ausrichten können.

<<v34>>
34 Sie entgegneten ihm: Du bist ganz und gar in Sünden geboren und du
willst uns belehren? Und sie stießen ihn hinaus. ^{[[#fn10][10]]}\\
\\

<<v35>>
**** Jesu Selbstoffenbarung vor dem Geheilten: 9,35-41
     :PROPERTIES:
     :CUSTOM_ID: jesu-selbstoffenbarung-vor-dem-geheilten-935-41
     :END:
35 Jesus hörte, dass sie ihn hinausgestoßen hatten, und als er ihn traf,
sagte er zu ihm: Glaubst du an den Menschensohn?

<<v36>>
36 Der Mann antwortete: Wer ist das, Herr? (Sag es mir,) damit ich an
ihn glaube.

<<v37>>
37 Jesus sagte zu ihm: Du siehst ihn vor dir; er, der mit dir redet, ist
es.

<<v38>>
38 Er aber sagte: Ich glaube, Herr! Und er warf sich vor ihm nieder.

<<v39>>
39 Da sprach Jesus: Um zu richten, bin ich in diese Welt gekommen: damit
die Blinden sehend und die Sehenden blind werden.
^{[[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 303\\
$ŽG://ESyn0812/\\
\\

<<v40>>
40 Einige Pharisäer, die bei ihm waren, hörten dies. Und sie fragten
ihn: Sind etwa auch wir blind?

<<v41>>
41 Jesus antwortete ihnen: Wenn ihr blind wärt, hättet ihr keine Sünde.
Jetzt aber sagt ihr: Wir sehen. Darum bleibt eure Sünde.\\
\\

^{[[#fnm1][1]]} ℘ ⇨Esyn: Synopse Nr. 248

^{[[#fnm2][2]]} ℘ 8,12

^{[[#fnm3][3]]} ℘ 2 Kön 5,10; Jes 8,6

^{[[#fnm4][4]]} Der Name Schiloach wird vom Evangelisten auf Jesus, den
«Gesandten», gedeutet, durch den der Blinde geheilt wird.

^{[[#fnm5][5]]} ℘ 5,9

^{[[#fnm6][6]]} ℘ 7,13; 12,42; 16,2

^{[[#fnm7][7]]} Der Ausschluss aus der Synagoge, der vom zeitlich
begrenzten Synagogenbann zu unterscheiden ist, wird auch in 12,42 und
16,2 erwähnt.

^{[[#fnm8][8]]} ℘ Jos 7,19; 2 Chr 30,8; Ps 66,2; 68,35; Jes 42,12

^{[[#fnm9][9]]} ℘ 5,45f

^{[[#fnm10][10]]} ℘ Ps 51,7

^{[[#fnm11][11]]} ℘ ⇨Esyn: Synopse Nr. 303
