:PROPERTIES:
:ID:       c4ed41a0-b598-44b0-962d-5a51738e689c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_11.html][11]]
[[file:Joh_12.html][12]] *13* [[file:Joh_14.html][14]]
[[file:Joh_15.html][15]] ... [[file:Joh_21.html][21]]

--------------

* Joh 13
  :PROPERTIES:
  :CUSTOM_ID: joh-13
  :END:

<<verses>>

<<v1>>
** Der Abschied Jesu von seinen Jüngern: 13,1 - 17,26
   :PROPERTIES:
   :CUSTOM_ID: der-abschied-jesu-von-seinen-jüngern-131---1726
   :END:
*** Das Abschiedsmahl: 13,1 - 14,31
    :PROPERTIES:
    :CUSTOM_ID: das-abschiedsmahl-131---1431
    :END:
**** Die Fußwaschung: 13,1-20
     :PROPERTIES:
     :CUSTOM_ID: die-fußwaschung-131-20
     :END:
1 Es war vor dem Paschafest. Jesus wusste, dass seine Stunde gekommen
war, um aus dieser Welt zum Vater hinüberzugehen. Da er die Seinen, die
in der Welt waren, liebte, erwies er ihnen seine Liebe bis zur
Vollendung. ^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 309\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Es fand ein Mahl statt, und der Teufel hatte Judas, dem Sohn des Simon
Iskariot, schon ins Herz gegeben, ihn zu verraten und auszuliefern.
^{[[#fn4][4]][[#fn5][5]]}

<<v3>>
3 Jesus, der wusste, dass ihm der Vater alles in die Hand gegeben hatte
und dass er von Gott gekommen war und zu Gott zurückkehrte,

<<v4>>
4 stand vom Mahl auf, legte sein Gewand ab und umgürtete sich mit einem
Leinentuch. ^{[[#fn6][6]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 284\\
$ŽG://ESyn0812/\\
\\

<<v5>>
5 Dann goss er Wasser in eine Schüssel und begann, den Jüngern die Füße
zu waschen und mit dem Leinentuch abzutrocknen, mit dem er umgürtet war.
^{[[#fn7][7]]}

<<v6>>
6 Als er zu Simon Petrus kam, sagte dieser zu ihm: Du, Herr, willst mir
die Füße waschen?

<<v7>>
7 Jesus antwortete ihm: Was ich tue, verstehst du jetzt noch nicht; doch
später wirst du es begreifen.

<<v8>>
8 Petrus entgegnete ihm: Niemals sollst du mir die Füße waschen! Jesus
erwiderte ihm: Wenn ich dich nicht wasche, hast du keinen Anteil an mir.

<<v9>>
9 Da sagte Simon Petrus zu ihm: Herr, dann nicht nur meine Füße, sondern
auch die Hände und das Haupt.

<<v10>>
10 Jesus sagte zu ihm: Wer vom Bad kommt, ist ganz rein und braucht sich
nur noch die Füße zu waschen. Auch ihr seid rein, aber nicht alle.
^{[[#fn8][8]]}

<<v11>>
11 Er wusste nämlich, wer ihn verraten würde; darum sagte er: Ihr seid
nicht alle rein.

<<v12>>
12 Als er ihnen die Füße gewaschen, sein Gewand wieder angelegt und
Platz genommen hatte, sagte er zu ihnen: Begreift ihr, was ich an euch
getan habe? ^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 263\\
$ŽG://ESyn0812/\\
\\

<<v13>>
13 Ihr sagt zu mir Meister und Herr und ihr nennt mich mit Recht so;
denn ich bin es.

<<v14>>
14 Wenn nun ich, der Herr und Meister, euch die Füße gewaschen habe,
dann müsst auch ihr einander die Füße waschen. ^{[[#fn10][10]]}

<<v15>>
15 Ich habe euch ein Beispiel gegeben, damit auch ihr so handelt, wie
ich an euch gehandelt habe.

<<v16>>
16 Amen, amen, ich sage euch: Der Sklave ist nicht größer als sein Herr
und der Abgesandte ist nicht größer als der, der ihn gesandt hat.
^{[[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 81\\
$ŽG://ESyn0812/\\
\\

<<v17>>
17 Selig seid ihr, wenn ihr das wisst und danach handelt.

<<v18>>
18 Ich sage das nicht von euch allen. Ich weiß wohl, welche ich erwählt
habe, aber das Schriftwort muss sich erfüllen: /Einer, der mein Brot aß,
hat mich hintergangen./ ^{[[#fn12][12]][[#fn13][13]]}

<<v19>>
19 Ich sage es euch schon jetzt, ehe es geschieht, damit ihr, wenn es
geschehen ist, glaubt: Ich bin es.

<<v20>>
20 Amen, amen, ich sage euch: Wer einen aufnimmt, den ich sende, nimmt
mich auf; wer aber mich aufnimmt, nimmt den auf, der mich gesandt hat.
^{[[#fn14][14]]}\\
^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 104\\
$ŽG://ESyn0812/

<<v21>>
**** Jesu Hinweis auf den Verräter: 13,21-30
     :PROPERTIES:
     :CUSTOM_ID: jesu-hinweis-auf-den-verräter-1321-30
     :END:
21 Nach diesen Worten war Jesus im Innersten erschüttert und
bekräftigte: Amen, amen, das sage ich euch: Einer von euch wird mich
verraten. ^{[[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 310\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 Die Jünger blickten sich ratlos an, weil sie nicht wussten, wen er
meinte.

<<v23>>
23 Einer von den Jüngern lag an der Seite Jesu; es war der, den Jesus
liebte. ^{[[#fn17][17]]}

<<v24>>
24 Simon Petrus nickte ihm zu, er solle fragen, von wem Jesus spreche.

<<v25>>
25 Da lehnte sich dieser zurück an die Brust Jesu und fragte ihn: Herr,
wer ist es?

<<v26>>
26 Jesus antwortete: Der ist es, dem ich den Bissen Brot, den ich
eintauche, geben werde. Dann tauchte er das Brot ein, nahm es und gab es
Judas, dem Sohn des Simon Iskariot. ^{[[#fn18][18]]}

<<v27>>
27 Als Judas den Bissen Brot genommen hatte, fuhr der Satan in ihn.
Jesus sagte zu ihm: Was du tun willst, das tu bald! ^{[[#fn19][19]]}

<<v28>>
28 Aber keiner der Anwesenden verstand, warum er ihm das sagte.

<<v29>>
29 Weil Judas die Kasse hatte, meinten einige, Jesus wolle ihm sagen:
Kaufe, was wir zum Fest brauchen!, oder Jesus trage ihm auf, den Armen
etwas zu geben.

<<v30>>
30 Als Judas den Bissen Brot genommen hatte, ging er sofort hinaus. Es
war aber Nacht.\\
\\

<<v31>>
**** Das neue Gebot: 13,31-35
     :PROPERTIES:
     :CUSTOM_ID: das-neue-gebot-1331-35
     :END:
31 Als Judas hinausgegangen war, sagte Jesus: Jetzt ist der Menschensohn
verherrlicht und Gott ist in ihm verherrlicht.
^{[[#fn20][20]][[#fn21][21]][[#fn22][22]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 314\\
$ŽG://ESyn0812/\\
\\

<<v32>>
32 Wenn Gott in ihm verherrlicht ist, wird auch Gott ihn in sich
verherrlichen, und er wird ihn bald verherrlichen.

<<v33>>
33 Meine Kinder, ich bin nur noch kurze Zeit bei euch. Ihr werdet mich
suchen, und was ich den Juden gesagt habe, sage ich jetzt auch euch:
Wohin ich gehe, dorthin könnt ihr nicht gelangen. ^{[[#fn23][23]]}

<<v34>>
34 Ein neues Gebot gebe ich euch: Liebt einander! Wie ich euch geliebt
habe, so sollt auch ihr einander lieben. ^{[[#fn24][24]][[#fn25][25]]}

<<v35>>
35 Daran werden alle erkennen, dass ihr meine Jünger seid: wenn ihr
einander liebt.\\
\\

<<v36>>
**** Jesu Wort an Petrus: 13,36-38
     :PROPERTIES:
     :CUSTOM_ID: jesu-wort-an-petrus-1336-38
     :END:
36 Simon Petrus sagte zu ihm: Herr, wohin willst du gehen? Jesus
antwortete: Wohin ich gehe, dorthin kannst du mir jetzt nicht folgen. Du
wirst mir aber später folgen.
^{[[#fn26][26]][[#fn27][27]][[#fn28][28]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 367\\
$ŽG://ESyn0812/\\
\\

<<v37>>
37 Petrus sagte zu ihm: Herr, warum kann ich dir jetzt nicht folgen?
Mein Leben will ich für dich hingeben. ^{[[#fn29][29]]}

<<v38>>
38 Jesus entgegnete: Du willst für mich dein Leben hingeben? Amen, amen,
das sage ich dir: Noch bevor der Hahn kräht, wirst du mich dreimal
verleugnen.\\
\\

^{[[#fnm1][1]]} ℘ 7,30; 8,20; 12,23

^{[[#fnm2][2]]} bis zur Vollendung: Der Ausdruck im griechischen Text
kann sowohl «bis zuletzt» als auch «bis zum äußersten» bedeuten.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 309

^{[[#fnm4][4]]} ℘ Mt 26,14-16; Mk 14,10f; Lk 22,3-6

^{[[#fnm5][5]]} In Judas ist die Macht des Satans am Werk (vgl. 6,70f;
13,27).

^{[[#fnm6][6]]} ℘ ⇨Esyn: Synopse Nr. 284

^{[[#fnm7][7]]} Jemandem die Füße zu waschen, gehörte zu den Aufgaben
der Sklaven.

^{[[#fnm8][8]]} Nach anderen Textzeugen: Wer gebadet ist, braucht sich
nicht zu waschen, sondern ist ganz rein. - Bei der kürzeren Lesart meint
«gebadet» in einem übertragenen Sinn: Wer durch die Fußwaschung Jesu in
das dadurch versinnbildete Kreuzesgeschehen hineingenommen ist (wie die
Jünger), bedarf keiner Reinigung mehr, sondern ist ganz rein. Bei der
längeren Lesart oben im Text («außer die Füße») ist vielleicht an die
Taufe gedacht.

^{[[#fnm9][9]]} ℘ ⇨Esyn: Synopse Nr. 263

^{[[#fnm10][10]]} ℘ Mt 20,28; Mk 10,45; Lk 22,26f

^{[[#fnm11][11]]} ℘ Mt 10,24; Lk 6,40 ⇨Esyn: Synopse Nr. 81

^{[[#fnm12][12]]} ℘ Ps 41,10; Mt 26,21; Mk 14,18; Lk 22,21

^{[[#fnm13][13]]} Wörtlich: Einer . . . hat gegen mich seine Ferse
erhoben.

^{[[#fnm14][14]]} ℘ Mt 10,40; Lk 10,16

^{[[#fnm15][15]]} ℘ ⇨Esyn: Synopse Nr. 104

^{[[#fnm16][16]]} ℘ (21-30) Mt 26,21-25; Mk 14,18-21; Lk 22,21-23 ⇨Esyn:
Synopse Nr. 310

^{[[#fnm17][17]]} ℘ 19,26f; 20,3-10; 21,7.20-24

^{[[#fnm18][18]]} 26-30: Es handelt sich hier nicht um die Eucharistie,
sondern um einen Bissen der Vorkost.

^{[[#fnm19][19]]} ℘ Lk 22,3

^{[[#fnm20][20]]} ℘ 7,39; 12,16.23.28; 17,1.4f

^{[[#fnm21][21]]} Jetzt: die Stunde, in der Jesus durch den Tod am Kreuz
verherrlicht wird; diese Stunde wird durch den Weggang des Verräters
eingeleitet.

^{[[#fnm22][22]]} ℘ ⇨Esyn: Synopse Nr. 314

^{[[#fnm23][23]]} ℘ 7,33; 8,21

^{[[#fnm24][24]]} ℘ 1 Joh 2,7-11; 4,7-21

^{[[#fnm25][25]]} Das «neue» Gebot, die Bruderliebe nach dem Vorbild der
Liebe Jesu bis zum Tod, überbietet das alttestamentliche Gesetz (vgl.
Lev 19,18). Die Erfüllung dieses Gebots wird zum kennzeichnenden Merkmal
der Jünger Jesu.

^{[[#fnm26][26]]} ℘ 21,18f

^{[[#fnm27][27]]} Verhüllter Hinweis auf den Tod des Petrus (21,18f).

^{[[#fnm28][28]]} ℘ ⇨Esyn: Synopse Nr. 367

^{[[#fnm29][29]]} ℘ (37-38) Mt 26,33-35; Mk 14,29-31; Lk 22,31-34
