:PROPERTIES:
:ID:       ab0902bf-59fd-483a-a7ce-b154cd8de341
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_3.html][3]] [[file:Joh_4.html][4]]
*5* [[file:Joh_6.html][6]] [[file:Joh_7.html][7]] ...
[[file:Joh_21.html][21]]

--------------

* Joh 5
  :PROPERTIES:
  :CUSTOM_ID: joh-5
  :END:

<<verses>>

<<v1>>
*** Die Selbstoffenbarung Jesu vor der Welt: 5,1 - 12,50
    :PROPERTIES:
    :CUSTOM_ID: die-selbstoffenbarung-jesu-vor-der-welt-51---1250
    :END:
**** Die Heilung eines Gelähmten am Sabbat in Jerusalem: 5,1-18
     :PROPERTIES:
     :CUSTOM_ID: die-heilung-eines-gelähmten-am-sabbat-in-jerusalem-51-18
     :END:
1 Einige Zeit später war ein Fest der Juden und Jesus ging hinauf nach
Jerusalem. ^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 140\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 In Jerusalem gibt es beim Schaftor einen Teich, zu dem fünf
Säulenhallen gehören; dieser Teich heißt auf Hebräisch Betesda.
^{[[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 141\\
$ŽG://ESyn0812/\\
\\

<<v3>>
3 In diesen Hallen lagen viele Kranke, darunter Blinde, Lahme und
Verkrüppelte.

<<v3b>>
3b [] ^{[[#fn4][4]]}

<<v4>>
4 [] ^{[[#fn5][5]]}

<<v5>>
5 Dort lag auch ein Mann, der schon achtunddreißig Jahre krank war.

<<v6>>
6 Als Jesus ihn dort liegen sah und erkannte, dass er schon lange krank
war, fragte er ihn: Willst du gesund werden?

<<v7>>
7 Der Kranke antwortete ihm: Herr, ich habe keinen Menschen, der mich,
sobald das Wasser aufwallt, in den Teich trägt. Während ich mich
hinschleppe, steigt schon ein anderer vor mir hinein.

<<v8>>
8 Da sagte Jesus zu ihm: Steh auf, nimm deine Bahre und geh!
^{[[#fn6][6]]}

<<v9>>
9 Sofort wurde der Mann gesund, nahm seine Bahre und ging. Dieser Tag
war aber ein Sabbat.

<<v10>>
10 Da sagten die Juden zu dem Geheilten: Es ist Sabbat, du darfst deine
Bahre nicht tragen.

<<v11>>
11 Er erwiderte: Der Mann, der mich gesund gemacht hat, sagte zu mir:
Nimm deine Bahre und geh!

<<v12>>
12 Sie fragten ihn: Wer ist das denn, der zu dir gesagt hat: Nimm deine
Bahre und geh?

<<v13>>
13 Der Geheilte wusste aber nicht, wer es war. Jesus war nämlich
weggegangen, weil sich dort eine große Menschenmenge angesammelt hatte.

<<v14>>
14 Später traf ihn Jesus im Tempel und sagte zu ihm: Jetzt bist du
gesund; sündige nicht mehr, damit dir nicht noch Schlimmeres zustößt.
^{[[#fn7][7]]}

<<v15>>
15 Der Mann ging fort und teilte den Juden mit, dass es Jesus war, der
ihn gesund gemacht hatte.

<<v16>>
16 Daraufhin verfolgten die Juden Jesus, weil er das an einem Sabbat
getan hatte.

<<v17>>
17 Jesus aber entgegnete ihnen: Mein Vater ist noch immer am Werk und
auch ich bin am Werk. ^{[[#fn8][8]]}

<<v18>>
18 Darum waren die Juden noch mehr darauf aus, ihn zu töten, weil er
nicht nur den Sabbat brach, sondern auch Gott seinen Vater nannte und
sich damit Gott gleichstellte. ^{[[#fn9][9]]}\\
\\

<<v19>>
**** Jesu Rede über seine Vollmacht: 5,19-47
     :PROPERTIES:
     :CUSTOM_ID: jesu-rede-über-seine-vollmacht-519-47
     :END:
19 Jesus aber sagte zu ihnen: Amen, amen, ich sage euch: Der Sohn kann
nichts von sich aus tun, sondern nur, wenn er den Vater etwas tun sieht.
Was nämlich der Vater tut, das tut in gleicher Weise der Sohn.

<<v20>>
20 Denn der Vater liebt den Sohn und zeigt ihm alles, was er tut, und
noch größere Werke wird er ihm zeigen, sodass ihr staunen werdet.
^{[[#fn10][10]]}

<<v21>>
21 Denn wie der Vater die Toten auferweckt und lebendig macht, so macht
auch der Sohn lebendig, wen er will. ^{[[#fn11][11]]}

<<v22>>
22 Auch richtet der Vater niemand, sondern er hat das Gericht ganz dem
Sohn übertragen, ^{[[#fn12][12]]}

<<v23>>
23 damit alle den Sohn ehren, wie sie den Vater ehren. Wer den Sohn
nicht ehrt, ehrt auch den Vater nicht, der ihn gesandt hat.

<<v24>>
24 Amen, amen, ich sage euch: Wer mein Wort hört und dem glaubt, der
mich gesandt hat, hat das ewige Leben; er kommt nicht ins Gericht,
sondern ist aus dem Tod ins Leben hinübergegangen. ^{[[#fn13][13]]}

<<v25>>
25 Amen, amen, ich sage euch: Die Stunde kommt und sie ist schon da, in
der die Toten die Stimme des Sohnes Gottes hören werden; und alle, die
sie hören, werden leben.

<<v26>>
26 Denn wie der Vater das Leben in sich hat, so hat er auch dem Sohn
gegeben, das Leben in sich zu haben. ^{[[#fn14][14]]}

<<v27>>
27 Und er hat ihm Vollmacht gegeben, Gericht zu halten, weil er der
Menschensohn ist. ^{[[#fn15][15]]}

<<v28>>
28 Wundert euch nicht darüber! Die Stunde kommt, in der alle, die in den
Gräbern sind, seine Stimme hören ^{[[#fn16][16]]}

<<v29>>
29 und herauskommen werden: Die das Gute getan haben, werden zum Leben
auferstehen, die das Böse getan haben, zum Gericht.

<<v30>>
30 Von mir selbst aus kann ich nichts tun; ich richte, wie ich es (vom
Vater) höre, und mein Gericht ist gerecht, weil es mir nicht um meinen
Willen geht, sondern um den Willen dessen, der mich gesandt hat.
^{[[#fn17][17]]}

<<v31>>
31 Wenn ich über mich selbst als Zeuge aussage, ist mein Zeugnis nicht
gültig; ^{[[#fn18][18]]}

<<v32>>
32 ein anderer ist es, der über mich als Zeuge aussagt, und ich weiß:
Das Zeugnis, das er über mich ablegt, ist gültig.

<<v33>>
33 Ihr habt zu Johannes geschickt, und er hat für die Wahrheit Zeugnis
abgelegt. ^{[[#fn19][19]]}

<<v34>>
34 Ich aber nehme von keinem Menschen ein Zeugnis an, sondern ich sage
dies nur, damit ihr gerettet werdet.

<<v35>>
35 Jener war die Lampe, die brennt und leuchtet, und ihr wolltet euch
eine Zeit lang an seinem Licht erfreuen. ^{[[#fn20][20]]}

<<v36>>
36 Ich aber habe ein gewichtigeres Zeugnis als das des Johannes: Die
Werke, die mein Vater mir übertragen hat, damit ich sie zu Ende führe,
diese Werke, die ich vollbringe, legen Zeugnis dafür ab, dass mich der
Vater gesandt hat. ^{[[#fn21][21]]}

<<v37>>
37 Auch der Vater selbst, der mich gesandt hat, hat über mich Zeugnis
abgelegt. Ihr habt weder seine Stimme gehört noch seine Gestalt je
gesehen,

<<v38>>
38 und auch sein Wort bleibt nicht in euch, weil ihr dem nicht glaubt,
den er gesandt hat.

<<v39>>
39 Ihr erforscht die Schriften, weil ihr meint, in ihnen das ewige Leben
zu haben; gerade sie legen Zeugnis über mich ab.

<<v40>>
40 Und doch wollt ihr nicht zu mir kommen, um das Leben zu haben.

<<v41>>
41 Meine Ehre empfange ich nicht von Menschen. ^{[[#fn22][22]]}

<<v42>>
42 Ich habe erkannt, dass ihr die Liebe zu Gott nicht in euch habt.

<<v43>>
43 Ich bin im Namen meines Vaters gekommen und doch lehnt ihr mich ab.
Wenn aber ein anderer in seinem eigenen Namen kommt, dann werdet ihr ihn
anerkennen.

<<v44>>
44 Wie könnt ihr zum Glauben kommen, wenn ihr eure Ehre voneinander
empfangt, nicht aber die Ehre sucht, die von dem einen Gott kommt?

<<v45>>
45 Denkt nicht, dass ich euch beim Vater anklagen werde; Mose klagt euch
an, auf den ihr eure Hoffnung gesetzt habt.

<<v46>>
46 Wenn ihr Mose glauben würdet, müsstet ihr auch mir glauben; denn über
mich hat er geschrieben.

<<v47>>
47 Wenn ihr aber seinen Schriften nicht glaubt, wie könnt ihr dann
meinen Worten glauben?\\
\\

^{[[#fnm1][1]]} ℘ ⇨Esyn: Synopse Nr. 140

^{[[#fnm2][2]]} Nach anderen Textzeugen: Betzata. - Reste der Anlage
sind ausgegraben worden.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 141

^{[[#fnm4][4]]} Ein Teil der Textzeugen fügt nach «Verkrüppelte» hinzu:
die auf die Bewegung des Wassers warteten.

^{[[#fnm5][5]]} Ein Engel des Herrn aber stieg zu bestimmter Zeit in den
Teich hinab und brachte das Wasser zum Aufwallen. Wer dann als erster
hineinstieg, wurde gesund, an welcher Krankheit er auch litt. - Dies ist
wohl ein deutender Zusatz zum ursprünglichen Text.

^{[[#fnm6][6]]} ℘ Mt 9,6; Mk 2,11; Lk 5,24

^{[[#fnm7][7]]} ℘ 8,11

^{[[#fnm8][8]]} ℘ 9,4

^{[[#fnm9][9]]} ℘ 7,1.25; 10,33

^{[[#fnm10][10]]} ℘ 3,35; 14,12

^{[[#fnm11][11]]} ℘ 1 Sam 2,6; 2 Kön 5,7

^{[[#fnm12][12]]} ℘ 5,27

^{[[#fnm13][13]]} ℘ 3,18

^{[[#fnm14][14]]} ℘ Mt 11,27

^{[[#fnm15][15]]} ℘ Dan 7,13f

^{[[#fnm16][16]]} ℘ (28f) Dan 12,2; Mt 16,27

^{[[#fnm17][17]]} ℘ 4,34; 6,38

^{[[#fnm18][18]]} ℘ 8,13f

^{[[#fnm19][19]]} ℘ 1,19-34; 18,37

^{[[#fnm20][20]]} ℘ 1,8

^{[[#fnm21][21]]} ℘ 10,25

^{[[#fnm22][22]]} ℘ 1 Thess 2,6
