:PROPERTIES:
:ID:       7add1bb9-2029-44d4-bf6a-575dbf767f36
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_19.html][19]]
[[file:Joh_20.html][20]] *21*

--------------

* Joh 21
  :PROPERTIES:
  :CUSTOM_ID: joh-21
  :END:

<<verses>>

<<v1>>
** Nachtrag zum Evangelium: 21,1-25
   :PROPERTIES:
   :CUSTOM_ID: nachtrag-zum-evangelium-211-25
   :END:
**** Die Erscheinung des Auferstandenen am See: 21,1-14
     :PROPERTIES:
     :CUSTOM_ID: die-erscheinung-des-auferstandenen-am-see-211-14
     :END:
1 Danach offenbarte sich Jesus den Jüngern noch einmal. Es war am See
von Tiberias und er offenbarte sich in folgender Weise.
^{[[#fn1][1]][[#fn2][2]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 367\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Simon Petrus, Thomas, genannt Didymus (Zwilling), Natanaël aus Kana in
Galiläa, die Söhne des Zebedäus und zwei andere von seinen Jüngern waren
zusammen. ^{[[#fn3][3]]}

<<v3>>
3 Simon Petrus sagte zu ihnen: Ich gehe fischen. Sie sagten zu ihm: Wir
kommen auch mit. Sie gingen hinaus und stiegen in das Boot. Aber in
dieser Nacht fingen sie nichts.

<<v4>>
4 Als es schon Morgen wurde, stand Jesus am Ufer. Doch die Jünger
wussten nicht, dass es Jesus war.

<<v5>>
5 Jesus sagte zu ihnen: Meine Kinder, habt ihr nicht etwas zu essen? Sie
antworteten ihm: Nein. ^{[[#fn4][4]]}

<<v6>>
6 Er aber sagte zu ihnen: Werft das Netz auf der rechten Seite des
Bootes aus und ihr werdet etwas fangen. Sie warfen das Netz aus und
konnten es nicht wieder einholen, so voller Fische war es.
^{[[#fn5][5]]}

<<v7>>
7 Da sagte der Jünger, den Jesus liebte, zu Petrus: Es ist der Herr! Als
Simon Petrus hörte, dass es der Herr sei, gürtete er sich das Obergewand
um, weil er nackt war, und sprang in den See. ^{[[#fn6][6]]}

<<v8>>
8 Dann kamen die anderen Jünger mit dem Boot - sie waren nämlich nicht
weit vom Land entfernt, nur etwa zweihundert Ellen - und zogen das Netz
mit den Fischen hinter sich her. ^{[[#fn7][7]]}

<<v9>>
9 Als sie an Land gingen, sahen sie am Boden ein Kohlenfeuer und darauf
Fisch und Brot.

<<v10>>
10 Jesus sagte zu ihnen: Bringt von den Fischen, die ihr gerade gefangen
habt.

<<v11>>
11 Da ging Simon Petrus und zog das Netz an Land. Es war mit
hundertdreiundfünfzig großen Fischen gefüllt, und obwohl es so viele
waren, zerriss das Netz nicht. ^{[[#fn8][8]]}

<<v12>>
12 Jesus sagte zu ihnen: Kommt her und esst! Keiner von den Jüngern
wagte ihn zu fragen: Wer bist du? Denn sie wussten, dass es der Herr
war.

<<v13>>
13 Jesus trat heran, nahm das Brot und gab es ihnen, ebenso den Fisch.

<<v14>>
14 Dies war schon das dritte Mal, dass Jesus sich den Jüngern
offenbarte, seit er von den Toten auferstanden war. ^{[[#fn9][9]]}\\
\\

<<v15>>
**** Das Wort des Auferstandenen an Petrus: 21,15-23
     :PROPERTIES:
     :CUSTOM_ID: das-wort-des-auferstandenen-an-petrus-2115-23
     :END:
15 Als sie gegessen hatten, sagte Jesus zu Simon Petrus: Simon, Sohn des
Johannes, liebst du mich mehr als diese? Er antwortete ihm: Ja, Herr, du
weißt, dass ich dich liebe. Jesus sagte zu ihm: Weide meine Lämmer!
^{[[#fn10][10]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 315\\
$ŽG://ESyn0812/\\
\\

<<v16>>
16 Zum zweiten Mal fragte er ihn: Simon, Sohn des Johannes, liebst du
mich? Er antwortete ihm: Ja, Herr, du weißt, dass ich dich liebe. Jesus
sagte zu ihm: Weide meine Schafe!

<<v17>>
17 Zum dritten Mal fragte er ihn: Simon, Sohn des Johannes, liebst du
mich? Da wurde Petrus traurig, weil Jesus ihn zum dritten Mal gefragt
hatte: Hast du mich lieb? Er gab ihm zu Antwort: Herr, du weißt alles;
du weißt, dass ich dich lieb habe. Jesus sagte zu ihm: Weide meine
Schafe! ^{[[#fn11][11]]}

<<v18>>
18 Amen, amen, das sage ich dir: Als du noch jung warst, hast du dich
selbst gegürtet und konntest gehen, wohin du wolltest. Wenn du aber alt
geworden bist, wirst du deine Hände ausstrecken und ein anderer wird
dich gürten und dich führen, wohin du nicht willst.

<<v19>>
19 Das sagte Jesus, um anzudeuten, durch welchen Tod er Gott
verherrlichen würde. Nach diesen Worten sagte er zu ihm: Folge mir nach!
^{[[#fn12][12]]}

<<v20>>
20 Petrus wandte sich um und sah, wie der Jünger, den Jesus liebte,
(diesem) folgte. Es war der Jünger, der sich bei jenem Mahl an die Brust
Jesu gelehnt und ihn gefragt hatte: Herr, wer ist es, der dich verraten
wird? ^{[[#fn13][13]]}

<<v21>>
21 Als Petrus diesen Jünger sah, fragte er Jesus: Herr, was wird denn
mit ihm?

<<v22>>
22 Jesus antwortete ihm: Wenn ich will, dass er bis zu meinem Kommen
bleibt, was geht das dich an? Du aber folge mir nach! ^{[[#fn14][14]]}

<<v23>>
23 Da verbreitete sich unter den Brüdern die Meinung: Jener Jünger
stirbt nicht. Doch Jesus hatte zu Petrus nicht gesagt: Er stirbt nicht,
sondern: Wenn ich will, dass er bis zu meinem Kommen bleibt, was geht
das dich an?\\
\\

<<v24>>
**** Schlussbemerkung der Herausgeber des Evangeliums: 21,24-25
     :PROPERTIES:
     :CUSTOM_ID: schlussbemerkung-der-herausgeber-des-evangeliums-2124-25
     :END:
24 Dieser Jünger ist es, der all das bezeugt und der es aufgeschrieben
hat; und wir wissen, dass sein Zeugnis wahr ist. ^{[[#fn15][15]]}

<<v25>>
25 Es gibt aber noch vieles andere, was Jesus getan hat. Wenn man alles
aufschreiben wollte, so könnte, wie ich glaube, die ganze Welt die
Bücher nicht fassen, die man schreiben müsste.\\
\\

^{[[#fnm1][1]]} 1-25: Das nachträglich hinzugefügte Kapitel stammt aus
dem Schülerkreis des Evangelisten. noch einmal: die dritte Erscheinung
vor den Jüngern (vgl. 20,19-23.26-29).

^{[[#fnm2][2]]} ℘ ⇨Esyn: Synopse Nr. 367

^{[[#fnm3][3]]} ℘ 11,16; 14,5; 20,24; 1,45f

^{[[#fnm4][4]]} ℘ Lk 24,41

^{[[#fnm5][5]]} ℘ Lk 5,4-7

^{[[#fnm6][6]]} ℘ 13,23; 19,26f; 20,2

^{[[#fnm7][7]]} Zweihundert Ellen: etwa 90 bis 100 Meter.

^{[[#fnm8][8]]} Die Zahl 153 hat vielleicht symbolische Bedeutung und
bezeichnet die große Zahl der Gläubigen aus allen Völkern, die durch die
Jünger gewonnen werden (vgl. Mt 4,19; Mk 1,17; Lk 5,10).

^{[[#fnm9][9]]} ℘ 20,19-23.26-29

^{[[#fnm10][10]]} ℘ Mt 16,18; Lk 22,31f; 1 Petr 5,4 ⇨Esyn: Synopse Nr.
315

^{[[#fnm11][11]]} ℘ 13,36-38; 18,17.25-27

^{[[#fnm12][12]]} ℘ 11,22; Mt 8,22

^{[[#fnm13][13]]} ℘ 13,25

^{[[#fnm14][14]]} ℘ 21,19

^{[[#fnm15][15]]} ℘ 19,35
