:PROPERTIES:
:ID:       440d66b9-8122-49f1-80f0-5e9ee33937f7
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_5.html][5]] [[file:Joh_6.html][6]]
*7* [[file:Joh_8.html][8]] [[file:Joh_9.html][9]] ...
[[file:Joh_21.html][21]]

--------------

* Joh 7
  :PROPERTIES:
  :CUSTOM_ID: joh-7
  :END:

<<verses>>

<<v1>>
*** Die Selbstoffenbarung Jesu beim Laubhüttenfest in Jerusalem: 7,1-52
    :PROPERTIES:
    :CUSTOM_ID: die-selbstoffenbarung-jesu-beim-laubhüttenfest-in-jerusalem-71-52
    :END:
**** Jesu Flucht vor der Öffentlichkeit: 7,1-13
     :PROPERTIES:
     :CUSTOM_ID: jesu-flucht-vor-der-öffentlichkeit-71-13
     :END:
1 Danach zog Jesus in Galiläa umher; denn er wollte sich nicht in Judäa
aufhalten, weil die Juden darauf aus waren, ihn zu töten.
^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 238\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Das Laubhüttenfest der Juden war nahe. ^{[[#fn2][2]]}

<<v3>>
3 Da sagten seine Brüder zu ihm: Geh von hier fort und zieh nach Judäa,
damit auch deine Jünger die Werke sehen, die du vollbringst.
^{[[#fn3][3]]}

<<v4>>
4 Denn niemand wirkt im Verborgenen, wenn er öffentlich bekannt sein
möchte. Wenn du dies tust, zeig dich der Welt!

<<v5>>
5 Auch seine Brüder glaubten nämlich nicht an ihn. ^{[[#fn4][4]]}

<<v6>>
6 Jesus sagte zu ihnen: Meine Zeit ist noch nicht gekommen, für euch
aber ist immer die rechte Zeit. ^{[[#fn5][5]]}

<<v7>>
7 Euch kann die Welt nicht hassen, mich aber hasst sie, weil ich
bezeuge, dass ihre Taten böse sind. ^{[[#fn6][6]]}

<<v8>>
8 Geht ihr nur hinauf zum Fest; ich gehe nicht zu diesem Fest hinauf,
weil meine Zeit noch nicht erfüllt ist.

<<v9>>
9 Das sagte er zu ihnen und er blieb in Galiläa.

<<v10>>
10 Als aber seine Brüder zum Fest hinaufgegangen waren, zog auch er
hinauf, jedoch nicht öffentlich, sondern heimlich.
^{[[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 239\\
$ŽG://ESyn0812/\\
\\

<<v11>>
11 Die Juden suchten beim Fest nach ihm und sagten: Wo ist er?

<<v12>>
12 Und in der Volksmenge wurde viel über ihn hin und her geredet. Die
einen sagten: Er ist ein guter Mensch. Andere sagten: Nein, er führt das
Volk in die Irre.

<<v13>>
13 Aber niemand redete öffentlich über ihn, denn man fürchtete sich vor
den Juden. ^{[[#fn8][8]]}\\
\\

<<v14>>
**** Jesu Auftreten im Tempel: 7,14-24
     :PROPERTIES:
     :CUSTOM_ID: jesu-auftreten-im-tempel-714-24
     :END:
14 Schon war die Hälfte der Festwoche vorüber, da ging Jesus zum Tempel
hinauf und lehrte. ^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 240\\
$ŽG://ESyn0812/\\
\\

<<v15>>
15 Die Juden wunderten sich und sagten: Wie kann der die Schrift
verstehen, ohne dafür ausgebildet zu sein? ^{[[#fn10][10]]}

<<v16>>
16 Darauf antwortete ihnen Jesus: Meine Lehre stammt nicht von mir,
sondern von dem, der mich gesandt hat.

<<v17>>
17 Wer bereit ist, den Willen Gottes zu tun, wird erkennen, ob diese
Lehre von Gott stammt oder ob ich in meinem eigenen Namen spreche.

<<v18>>
18 Wer im eigenen Namen spricht, sucht seine eigene Ehre; wer aber die
Ehre dessen sucht, der ihn gesandt hat, der ist glaubwürdig und in ihm
ist keine Falschheit. ^{[[#fn11][11]]}

<<v19>>
19 Hat Mose euch nicht das Gesetz gegeben? Aber keiner von euch befolgt
das Gesetz. Warum wollt ihr mich töten?

<<v20>>
20 Die Menge antwortete: Du bist wohl von einem Dämon besessen - wer
will dich denn töten? ^{[[#fn12][12]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 117\\
$ŽG://ESyn0812/\\
\\

<<v21>>
21 Jesus entgegnete ihnen: Ich habe nur ein einziges Werk vollbracht,
und ihr alle wundert euch darüber. ^{[[#fn13][13]]}

<<v22>>
22 Mose hat euch die Beschneidung gegeben - sie stammt freilich nicht
von Mose, sondern von den Vätern -, und ihr beschneidet einen Menschen
auch am Sabbat.

<<v23>>
23 Wenn ein Mensch am Sabbat die Beschneidung empfangen darf, damit das
Gesetz des Mose nicht missachtet wird, warum zürnt ihr mir, weil ich am
Sabbat einen Menschen als Ganzen gesund gemacht habe?

<<v24>>
24 Urteilt nicht nach dem Augenschein, sondern urteilt gerecht!\\
\\

<<v25>>
**** Mutmaßungen des Volkes über Jesus: 7,25-36
     :PROPERTIES:
     :CUSTOM_ID: mutmaßungen-des-volkes-über-jesus-725-36
     :END:
25 Da sagten einige Leute aus Jerusalem: Ist das nicht der, den sie
töten wollen? ^{[[#fn14][14]]}

<<v26>>
26 Und doch redet er in aller Öffentlichkeit und man lässt ihn gewähren.
Sollte der Hohe Rat wirklich erkannt haben, dass er der Messias ist?

<<v27>>
27 Aber von dem hier wissen wir, woher er stammt; wenn jedoch der
Messias kommt, weiß niemand, woher er stammt.
^{[[#fn15][15]][[#fn16][16]]}

<<v28>>
28 Während Jesus im Tempel lehrte, rief er: Ihr kennt mich und wisst,
woher ich bin; aber ich bin nicht in meinem eigenen Namen gekommen,
sondern er, der mich gesandt hat, bürgt für die Wahrheit. Ihr kennt ihn
nur nicht. ^{[[#fn17][17]]}

<<v29>>
29 Ich kenne ihn, weil ich von ihm komme und weil er mich gesandt hat.
^{[[#fn18][18]]}

<<v30>>
30 Da wollten sie ihn festnehmen; aber keiner wagte ihn anzufassen, denn
seine Stunde war noch nicht gekommen.

<<v31>>
31 Aus der Menge kamen viele Leute zum Glauben an ihn; sie sagten: Wird
der Messias, wenn er kommt, mehr Zeichen tun, als dieser getan hat?

<<v32>>
32 Die Pharisäer hörten, was die Leute heimlich über ihn redeten. Da
schickten die Hohenpriester und die Pharisäer Gerichtsdiener aus, um ihn
festnehmen zu lassen.

<<v33>>
33 Jesus aber sagte: Ich bin nur noch kurze Zeit bei euch; dann gehe ich
fort, zu dem, der mich gesandt hat. ^{[[#fn19][19]]}

<<v34>>
34 Ihr werdet mich suchen und ihr werdet mich nicht finden; denn wo ich
bin, dorthin könnt ihr nicht gelangen.

<<v35>>
35 Da sagten die Juden zueinander: Wohin will er denn gehen, dass wir
ihn nicht mehr finden können? Will er in die Diaspora zu den Griechen
gehen und die Griechen lehren?

<<v36>>
36 Was bedeutet es, wenn er gesagt hat: Ihr werdet mich suchen, aber
nicht finden; denn wo ich bin, dorthin könnt ihr nicht gelangen?\\
\\

<<v37>>
**** Der Streit im Hohen Rat um Jesus: 7,37-52
     :PROPERTIES:
     :CUSTOM_ID: der-streit-im-hohen-rat-um-jesus-737-52
     :END:
37 Am letzten Tag des Festes, dem großen Tag, stellte sich Jesus hin und
rief: Wer Durst hat, komme zu mir, und es trinke, ^{[[#fn20][20]]}

<<v38>>
38 wer an mich glaubt. Wie die Schrift sagt: Aus seinem Inneren werden
Ströme von lebendigem Wasser fließen. ^{[[#fn21][21]]}

<<v39>>
39 Damit meinte er den Geist, den alle empfangen sollten, die an ihn
glauben; denn der Geist war noch nicht gegeben, weil Jesus noch nicht
verherrlicht war.

<<v40>>
40 Einige aus dem Volk sagten, als sie diese Worte hörten: Er ist
wahrhaftig der Prophet. ^{[[#fn22][22]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 241\\
$ŽG://ESyn0812/\\
\\

<<v41>>
41 Andere sagten: Er ist der Messias. Wieder andere sagten: Kommt denn
der Messias aus Galiäa? ^{[[#fn23][23]]}

<<v42>>
42 Sagt nicht die Schrift: Der Messias /kommt aus/ dem Geschlecht Davids
und aus dem Dorf /Betlehem,/ wo David lebte? ^{[[#fn24][24]]}

<<v43>>
43 So entstand seinetwegen eine Spaltung in der Menge.

<<v44>>
44 Einige von ihnen wollten ihn festnehmen; aber keiner wagte ihn
anzufassen. ^{[[#fn25][25]]}

<<v45>>
45 Als die Gerichtsdiener zu den Hohenpriestern und den Pharisäern
zurückkamen, fragten diese: Warum habt ihr ihn nicht hergebracht?

<<v46>>
46 Die Gerichtsdiener antworteten: Noch nie hat ein Mensch so
gesprochen. ^{[[#fn26][26]][[#fn27][27]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 76\\
$ŽG://ESyn0812/\\
\\

<<v47>>
47 Da entgegneten ihnen die Pharisäer: Habt auch ihr euch in die Irre
führen lassen?

<<v48>>
48 Ist etwa einer vom Hohen Rat oder von den Pharisäern zum Glauben an
ihn gekommen?

<<v49>>
49 Dieses Volk jedoch, das vom Gesetz nichts versteht, verflucht ist es.
^{[[#fn28][28]]}

<<v50>>
50 Nikodemus aber, einer aus ihren eigenen Reihen, der früher einmal
Jesus aufgesucht hatte, sagte zu ihnen: ^{[[#fn29][29]][[#fn30][30]]}

<<v51>>
51 Verurteilt etwa unser Gesetz einen Menschen, bevor man ihn verhört
und festgestellt hat, was er tut? ^{[[#fn31][31]]}

<<v52>>
52 Sie erwiderten ihm: Bist du vielleicht auch aus Galiläa? Lies doch
nach: Der Prophet kommt nicht aus Galiläa. ^{[[#fn32][32]]}\\
\\

<<v53>>
**** [Jesus und die Ehebrecherin: 7,53 - 8,11
     :PROPERTIES:
     :CUSTOM_ID: jesus-und-die-ehebrecherin-753---811
     :END:
53 Dann gingen alle nach Hause.
^{[[#fn33][33]][[#fn34][34]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 242\\
$ŽG://ESyn0812/\\
\\

^{[[#fnm1][1]]} ℘ Mt 17,22; Mk 9,30 ⇨Esyn: Synopse Nr. 238

^{[[#fnm2][2]]} Das Laubhüttenfest ist neben dem Pascha- und dem
Pfingstfest das dritte große jüdische Wallfahrtsfest. Es fand zur Zeit
der Wein-, Obst- und Olivenernte statt. Während der Festwoche wohnten
die Juden in eigens dafür errichteten Laubhütten (vgl. Lev 23,33-43; Dtn
16,13-15; besonders zu beachten ist Lev 23,42f).

^{[[#fnm3][3]]} 3-5: Vgl. die Anmerkung zu Mt 12,46f.

^{[[#fnm4][4]]} ℘ Mk 3,21

^{[[#fnm5][5]]} ℘ 2,4; 7,30; 8,20; Mt 26,18; Lk 4,13; 21,8; Apg 1,7

^{[[#fnm6][6]]} ℘ 15,18f

^{[[#fnm7][7]]} ℘ ⇨Esyn: Synopse Nr. 239

^{[[#fnm8][8]]} Der Ausdruck «die Juden» bezieht sich hier wie in 1,19;
2,18; 5,10 u. ö. auf die jüdischen Behörden.

^{[[#fnm9][9]]} ℘ ⇨Esyn: Synopse Nr. 240

^{[[#fnm10][10]]} ℘ Mt 13,54; Mk 6,2; Lk 4,16-30

^{[[#fnm11][11]]} ℘ 8,50

^{[[#fnm12][12]]} ℘ Mk 3,21f; Mt 10,25; 12,24; Lk 11,15 ⇨Esyn: Synopse
Nr. 117

^{[[#fnm13][13]]} Mit dem «einen Werk» ist die Heilung des Mannes am
Betesda-Teich (5,1-9) gemeint.

^{[[#fnm14][14]]} ℘ 5,18

^{[[#fnm15][15]]} ℘ 6,42

^{[[#fnm16][16]]} Es gab die Vorstellung, dass der Messias bei seinem
Auftreten zunächst unerkannt bleibt, bis Elija kommt und ihn dem Volk
bekannt macht. Zum Anstoß an Jesu «bekannter» Herkunft vgl. 6,42.

^{[[#fnm17][17]]} ℘ 8,55

^{[[#fnm18][18]]} ℘ 6,46

^{[[#fnm19][19]]} ℘ 8,21

^{[[#fnm20][20]]} Der siebte («große») Tag des Festes war durch den
Ritus des Wasserschöpfens ausgezeichnet: Die Priester schöpften Wasser
aus der Quelle Schiloach und zogen damit siebenmal um den Altar. An
diesen Ritus scheint Jesus mit seinem Ruf anzuknüpfen. Vgl. die
Anmerkung zu 8,12. 37f: Andere Übersetzungsmöglichkeit: Wer Durst hat,
komme zu mir und trinke. 38 Wer an mich glaubt, von dem sagt die
Schrift, dass aus seinem Innern Ströme lebendigen Wassers fließen
werden.

^{[[#fnm21][21]]} Es ist nicht klar, welche Schriftstelle hier gemeint
ist; vgl. Ez 47,1; Sach 14,8.

^{[[#fnm22][22]]} ℘ ⇨Esyn: Synopse Nr. 241

^{[[#fnm23][23]]} ℘ Dtn 18,15.18

^{[[#fnm24][24]]} ℘ 2 Sam 7,12-16; Mi 5,1; Mt 2,5; 22,42; Röm 1,3; 2 Tim
2,8

^{[[#fnm25][25]]} ℘ 7,30

^{[[#fnm26][26]]} Andere Textzeugen haben: Noch nie hat ein Mensch so
gesprochen, wie dieser Mensch spricht.

^{[[#fnm27][27]]} ℘ ⇨Esyn: Synopse Nr. 76

^{[[#fnm28][28]]} Hinter dem Fluch über das «gesetzesunkundige Volk»
steht ein rabbinischer Ausdruck, der eine Geringschätzung für alle Juden
bekundet, die sich nicht an die weitgehenden, von den Gesetzeslehrern
eingeschärften Vorschriften hielten.

^{[[#fnm29][29]]} ℘ 3,1

^{[[#fnm30][30]]} Zu Nikodemus vgl. die Anmerkung zu 3,1.

^{[[#fnm31][31]]} ℘ Dtn 1,16f; 17,2-5

^{[[#fnm32][32]]} Der Prophet, nach anderen Textzeugen: Ein Prophet.

^{[[#fnm33][33]]} 53-8,11: Dieses Stück gehört nicht zum ursprünglichen
Bestand des Johannesevangeliums; die besten Textzeugen überliefern es
nicht. Die Erzählung stellt aber wohl eine alte Überlieferung dar und
gehört inhaltlich zum Evangelium.

^{[[#fnm34][34]]} ℘ ⇨Esyn: Synopse Nr. 242
