:PROPERTIES:
:ID:       9c4fbe24-a0b7-48d6-a0de-659e133f4669
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_18.html][18]]
[[file:Joh_19.html][19]] *20* [[file:Joh_21.html][21]]

--------------

* Joh 20
  :PROPERTIES:
  :CUSTOM_ID: joh-20
  :END:

<<verses>>

<<v1>>
*** Osterberichte: 20,1-31
    :PROPERTIES:
    :CUSTOM_ID: osterberichte-201-31
    :END:
**** Die Entdeckung des leeren Grabes: 20,1-10
     :PROPERTIES:
     :CUSTOM_ID: die-entdeckung-des-leeren-grabes-201-10
     :END:
1 Am ersten Tag der Woche kam Maria von Magdala frühmorgens, als es noch
dunkel war, zum Grab und sah, dass der Stein vom Grab weggenommen war.
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 352\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Da lief sie schnell zu Simon Petrus und dem Jünger, den Jesus liebte,
und sagte zu ihnen: Man hat den Herrn aus dem Grab weggenommen und wir
wissen nicht, wohin man ihn gelegt hat. ^{[[#fn4][4]]}

<<v3>>
3 Da gingen Petrus und der andere Jünger hinaus und kamen zum Grab;

<<v4>>
4 sie liefen beide zusammen dorthin, aber weil der andere Jünger
schneller war als Petrus, kam er als erster ans Grab.

<<v5>>
5 Er beugte sich vor und sah die Leinenbinden liegen, ging aber nicht
hinein. ^{[[#fn5][5]]}

<<v6>>
6 Da kam auch Simon Petrus, der ihm gefolgt war, und ging in das Grab
hinein. Er sah die Leinenbinden liegen

<<v7>>
7 und das Schweißtuch, das auf dem Kopf Jesu gelegen hatte; es lag aber
nicht bei den Leinenbinden, sondern zusammengebunden daneben an einer
besonderen Stelle.

<<v8>>
8 Da ging auch der andere Jünger, der zuerst an das Grab gekommen war,
hinein; er sah und glaubte. ^{[[#fn6][6]]}

<<v9>>
9 Denn sie wussten noch nicht aus der Schrift, dass er von den Toten
auferstehen musste. ^{[[#fn7][7]]}

<<v10>>
10 Dann kehrten die Jünger wieder nach Hause zurück.\\
\\

<<v11>>
**** Die Erscheinung Jesu vor Maria aus Magdala: 20,11-18
     :PROPERTIES:
     :CUSTOM_ID: die-erscheinung-jesu-vor-maria-aus-magdala-2011-18
     :END:
11 Maria aber stand draußen vor dem Grab und weinte. Während sie weinte,
beugte sie sich in die Grabkammer hinein. ^{[[#fn8][8]]}

<<v12>>
12 Da sah sie zwei Engel in weißen Gewändern sitzen, den einen dort, wo
der Kopf, den anderen dort, wo die Füße des Leichnams Jesu gelegen
hatten.

<<v13>>
13 Die Engel sagten zu ihr: Frau, warum weinst du? Sie antwortete ihnen:
Man hat meinen Herrn weggenommen und ich weiß nicht, wohin man ihn
gelegt hat.

<<v14>>
14 Als sie das gesagt hatte, wandte sie sich um und sah Jesus dastehen,
wusste aber nicht, dass es Jesus war. ^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 353\\
$ŽG://ESyn0812/\\
\\

<<v15>>
15 Jesus sagte zu ihr: Frau, warum weinst du? Wen suchst du? Sie meinte,
es sei der Gärtner, und sagte zu ihm: Herr, wenn du ihn weggebracht
hast, sag mir, wohin du ihn gelegt hast. Dann will ich ihn holen.

<<v16>>
16 Jesus sagte zu ihr: Maria! Da wandte sie sich ihm zu und sagte auf
Hebräisch zu ihm: Rabbuni!, das heißt: Meister.
^{[[#fn10][10]][[#fn11][11]]}

<<v17>>
17 Jesus sagte zu ihr: Halte mich nicht fest; denn ich bin noch nicht
zum Vater hinaufgegangen. Geh aber zu meinen Brüdern und sag ihnen: Ich
gehe hinauf zu meinem Vater und zu eurem Vater, zu meinem Gott und zu
eurem Gott. ^{[[#fn12][12]]}

<<v18>>
18 Maria von Magdala ging zu den Jüngern und verkündete ihnen: Ich habe
den Herrn gesehen. Und sie richtete aus, was er ihr gesagt hatte.\\
\\

<<v19>>
**** Die Beauftragung der Jünger: 20,19-23
     :PROPERTIES:
     :CUSTOM_ID: die-beauftragung-der-jünger-2019-23
     :END:
19 Am Abend dieses ersten Tages der Woche, als die Jünger aus Furcht vor
den Juden die Türen verschlossen hatten, kam Jesus, trat in ihre Mitte
und sagte zu ihnen: Friede sei mit euch!
^{[[#fn13][13]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 356\\
$ŽG://ESyn0812/\\
\\

<<v20>>
20 Nach diesen Worten zeigte er ihnen seine Hände und seine Seite. Da
freuten sich die Jünger, dass sie den Herrn sahen.

<<v21>>
21 Jesus sagte noch einmal zu ihnen: Friede sei mit euch! Wie mich der
Vater gesandt hat, so sende ich euch.

<<v22>>
22 Nachdem er das gesagt hatte, hauchte er sie an und sprach zu ihnen:
Empfangt den Heiligen Geist! ^{[[#fn14][14]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 158\\
$ŽG://ESyn0812/\\
\\

<<v23>>
23 Wem ihr die Sünden vergebt, dem sind sie vergeben; wem ihr die
Vergebung verweigert, dem ist sie verweigert. ^{[[#fn15][15]]}\\
\\

<<v24>>
**** Jesus und Thomas: 20,24-29
     :PROPERTIES:
     :CUSTOM_ID: jesus-und-thomas-2024-29
     :END:
24 Thomas, genannt Didymus (Zwilling), einer der Zwölf, war nicht bei
ihnen, als Jesus kam. ^{[[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 357\\
$ŽG://ESyn0812/\\
\\

<<v25>>
25 Die anderen Jünger sagten zu ihm: Wir haben den Herrn gesehen. Er
entgegnete ihnen: Wenn ich nicht die Male der Nägel an seinen Händen
sehe und wenn ich meinen Finger nicht in die Male der Nägel und meine
Hand nicht in seine Seite lege, glaube ich nicht.

<<v26>>
26 Acht Tage darauf waren seine Jünger wieder versammelt und Thomas war
dabei. Die Türen waren verschlossen. Da kam Jesus, trat in ihre Mitte
und sagte: Friede sei mit euch!

<<v27>>
27 Dann sagte er zu Thomas: Streck deinen Finger aus - hier sind meine
Hände! Streck deine Hand aus und leg sie in meine Seite und sei nicht
ungläubig, sondern gläubig!

<<v28>>
28 Thomas antwortete ihm: Mein Herr und mein Gott!

<<v29>>
29 Jesus sagte zu ihm: Weil du mich gesehen hast, glaubst du. Selig
sind, die nicht sehen und doch glauben.\\
\\

<<v30>>
** Der Epilog: 20,30-31
   :PROPERTIES:
   :CUSTOM_ID: der-epilog-2030-31
   :END:
30 Noch viele andere Zeichen, die in diesem Buch nicht aufgeschrieben
sind, hat Jesus vor den Augen seiner Jünger getan.
^{[[#fn17][17]][[#fn18][18]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 366\\
$ŽG://ESyn0812/\\
\\

<<v31>>
31 Diese aber sind aufgeschrieben, damit ihr glaubt, dass Jesus der
Messias ist, der Sohn Gottes, und damit ihr durch den Glauben das Leben
habt in seinem Namen.\\
\\

^{[[#fnm1][1]]} ℘ (1-10) Mt 28,1-8; Mk 16,1-8; Lk 24,1-11

^{[[#fnm2][2]]} «Der erste Tag der Woche», der Tag, an dem Jesus
auferstanden ist, wurde zum christlichen Sonntag («Tag des Herrn»; vgl.
Offb 1,10).

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 352

^{[[#fnm4][4]]} ℘ 13,23; 19,26

^{[[#fnm5][5]]} ℘ (5-6) 19,40

^{[[#fnm6][6]]} ℘ (8-9) 2,22; Ps 16,8-11; Lk 24,25-27.44-46

^{[[#fnm7][7]]} ℘ Apg 2,24-31; 13,32-37; 1 Kor 15,4

^{[[#fnm8][8]]} ℘ (11-18) Mt 28,9f; Mk 16,9-11

^{[[#fnm9][9]]} ℘ ⇨Esyn: Synopse Nr. 353

^{[[#fnm10][10]]} ℘ Mk 10,51

^{[[#fnm11][11]]} Zu «Rabbuni» vgl. Anmerkung zu Mk 10,51.

^{[[#fnm12][12]]} «Halte mich nicht fest»: Maria hatte sich vermutlich
Jesus zu Füßen geworfen und diese umfasst oder umfassen wollen (vgl. Mt
28,9).

^{[[#fnm13][13]]} ℘ (19-23) Mk 16,14-18; Lk 24,36-39 ⇨Esyn: Synopse Nr.
356

^{[[#fnm14][14]]} ℘ 14,17.26; 15,26 ⇨Esyn: Synopse Nr. 158

^{[[#fnm15][15]]} ℘ Mt 16,19

^{[[#fnm16][16]]} ℘ 11,16; 14,5; 21,2 ⇨Esyn: Synopse Nr. 357

^{[[#fnm17][17]]} 30f: Ursprünglich Schlusswort des Johannesevangeliums.

^{[[#fnm18][18]]} ℘ ⇨Esyn: Synopse Nr. 366
