:PROPERTIES:
:ID:       c575bf1d-46bb-4064-9ee3-fe20c7437d90
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_6.html][6]] [[file:Joh_7.html][7]]
*8* [[file:Joh_9.html][9]] [[file:Joh_10.html][10]] ...
[[file:Joh_21.html][21]]

--------------

* Joh 8
  :PROPERTIES:
  :CUSTOM_ID: joh-8
  :END:

<<verses>>

<<v1>>
1 Jesus aber ging zum Ölberg. ^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 274\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Am frühen Morgen begab er sich wieder in den Tempel. Alles Volk kam zu
ihm. Er setzte sich und lehrte es. ^{[[#fn2][2]]}

<<v3>>
3 Da brachten die Schriftgelehrten und die Pharisäer eine Frau, die beim
Ehebruch ertappt worden war. Sie stellten sie in die Mitte

<<v4>>
4 und sagten zu ihm: Meister, diese Frau wurde beim Ehebruch auf
frischer Tat ertappt.

<<v5>>
5 Mose hat uns im Gesetz vorgeschrieben, solche Frauen zu steinigen.
Nun, was sagst du? ^{[[#fn3][3]]}

<<v6>>
6 Mit dieser Frage wollten sie ihn auf die Probe stellen, um einen Grund
zu haben, ihn zu verklagen. Jesus aber bückte sich und schrieb mit dem
Finger auf die Erde. ^{[[#fn4][4]]}

<<v7>>
7 Als sie hartnäckig weiterfragten, richtete er sich auf und sagte zu
ihnen: Wer von euch ohne Sünde ist, werfe als Erster einen Stein auf
sie. ^{[[#fn5][5]]}

<<v8>>
8 Und er bückte sich wieder und schrieb auf die Erde.

<<v9>>
9 Als sie seine Antwort gehört hatten, ging einer nach dem anderen fort,
zuerst die Ältesten. Jesus blieb allein zurück mit der Frau, die noch in
der Mitte stand.

<<v10>>
10 Er richtete sich auf und sagte zu ihr: Frau, wo sind sie geblieben?
Hat dich keiner verurteilt?

<<v11>>
11 Sie antwortete: Keiner, Herr. Da sagte Jesus zu ihr: Auch ich
verurteile dich nicht. Geh und sündige von jetzt an nicht mehr!]\\
\\

<<v12>>
*** Streitgespräche Jesu mit den Juden: 8,12-59
    :PROPERTIES:
    :CUSTOM_ID: streitgespräche-jesu-mit-den-juden-812-59
    :END:
**** Jesu Selbstzeugnis: 8,12-20
     :PROPERTIES:
     :CUSTOM_ID: jesu-selbstzeugnis-812-20
     :END:
12 Als Jesus ein andermal zu ihnen redete, sagte er: Ich bin das Licht
der Welt. Wer mir nachfolgt, wird nicht in der Finsternis umhergehen,
sondern wird das Licht des Lebens haben.
^{[[#fn6][6]][[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 243\\
$ŽG://ESyn0812/\\
\\

<<v13>>
13 Da sagten die Pharisäer zu ihm: Du legst über dich selbst Zeugnis ab;
dein Zeugnis ist nicht gültig. ^{[[#fn8][8]]}

<<v14>>
14 Jesus erwiderte ihnen: Auch wenn ich über mich selbst Zeugnis ablege,
ist mein Zeugnis gültig. Denn ich weiß, woher ich gekommen bin und wohin
ich gehe. Ihr aber wisst nicht, woher ich komme und wohin ich gehe.

<<v15>>
15 Ihr urteilt, wie Menschen urteilen, ich urteile über keinen.
^{[[#fn9][9]]}

<<v16>>
16 Wenn ich aber urteile, ist mein Urteil gültig; denn ich urteile nicht
allein, sondern ich und der Vater, der mich gesandt hat.
^{[[#fn10][10]]}

<<v17>>
17 Auch in eurem Gesetz heißt es: Erst das Zeugnis von zwei Menschen ist
gültig. ^{[[#fn11][11]]}

<<v18>>
18 Ich bin es, der über mich Zeugnis ablegt, und auch der Vater, der
mich gesandt hat, legt über mich Zeugnis ab.

<<v19>>
19 Da fragten sie ihn: Wo ist dein Vater? Jesus antwortete: Ihr kennt
weder mich noch meinen Vater; würdet ihr mich kennen, dann würdet ihr
auch meinen Vater kennen. ^{[[#fn12][12]]}

<<v20>>
20 Diese Worte sagte er, als er im Tempel bei der Schatzkammer lehrte.
Aber niemand nahm ihn fest; denn seine Stunde war noch nicht gekommen.
^{[[#fn13][13]][[#fn14][14]]}\\
\\

<<v21>>
**** Die Herkunft und Bestimmung Jesu: 8,21-29
     :PROPERTIES:
     :CUSTOM_ID: die-herkunft-und-bestimmung-jesu-821-29
     :END:
21 Ein andermal sagte Jesus zu ihnen: Ich gehe fort und ihr werdet mich
suchen und ihr werdet in eurer Sünde sterben. Wohin ich gehe, dorthin
könnt ihr nicht gelangen. ^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 244\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 Da sagten die Juden: Will er sich etwa umbringen? Warum sagt er
sonst: Wohin ich gehe, dorthin könnt ihr nicht gelangen?

<<v23>>
23 Er sagte zu ihnen: Ihr stammt von unten, ich stamme von oben; ihr
seid aus dieser Welt, ich bin nicht aus dieser Welt. ^{[[#fn16][16]]}

<<v24>>
24 Ich habe euch gesagt: Ihr werdet in euren Sünden sterben; denn wenn
ihr nicht glaubt, dass ich es bin, werdet ihr in euren Sünden sterben.
^{[[#fn17][17]]}

<<v25>>
25 Da fragten sie ihn: Wer bist du denn? Jesus antwortete: Warum rede
ich überhaupt noch mit euch? ^{[[#fn18][18]]}

<<v26>>
26 Ich hätte noch viel über euch zu sagen und viel zu richten, aber er,
der mich gesandt hat, bürgt für die Wahrheit, und was ich von ihm gehört
habe, das sage ich der Welt.

<<v27>>
27 Sie verstanden nicht, dass er damit den Vater meinte.

<<v28>>
28 Da sagte Jesus zu ihnen: Wenn ihr den Menschensohn erhöht habt, dann
werdet ihr erkennen, dass Ich es bin. Ihr werdet erkennen, dass ich
nichts im eigenen Namen tue, sondern nur das sage, was mich der Vater
gelehrt hat. ^{[[#fn19][19]]}

<<v29>>
29 Und er, der mich gesandt hat, ist bei mir; er hat mich nicht allein
gelassen, weil ich immer das tue, was ihm gefällt. ^{[[#fn20][20]]}\\
\\

<<v30>>
**** Die wahren Kinder Abrahams: 8,30-47
     :PROPERTIES:
     :CUSTOM_ID: die-wahren-kinder-abrahams-830-47
     :END:
30 Als Jesus das sagte, kamen viele zum Glauben an ihn.
^{[[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 245\\
$ŽG://ESyn0812/\\
\\

<<v31>>
31 Da sagte er zu den Juden, die an ihn glaubten: Wenn ihr in meinem
Wort bleibt, seid ihr wirklich meine Jünger. ^{[[#fn22][22]]}

<<v32>>
32 Dann werdet ihr die Wahrheit erkennen und die Wahrheit wird euch
befreien.

<<v33>>
33 Sie erwiderten ihm: Wir sind Nachkommen Abrahams und sind noch nie
Sklaven gewesen. Wie kannst du sagen: Ihr werdet frei werden?

<<v34>>
34 Jesus antwortete ihnen: Amen, amen, das sage ich euch: Wer die Sünde
tut, ist Sklave der Sünde. ^{[[#fn23][23]]}

<<v35>>
35 Der Sklave aber bleibt nicht für immer im Haus; nur der Sohn bleibt
für immer im Haus.

<<v36>>
36 Wenn euch also der Sohn befreit, dann seid ihr wirklich frei.

<<v37>>
37 Ich weiß, dass ihr Nachkommen Abrahams seid. Aber ihr wollt mich
töten, weil mein Wort in euch keine Aufnahme findet.
^{[[#fn24][24]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 246\\
$ŽG://ESyn0812/\\
\\

<<v38>>
38 Ich sage, was ich beim Vater gesehen habe, und ihr tut, was ihr von
eurem Vater gehört habt.

<<v39>>
39 Sie antworteten ihm: Unser Vater ist Abraham. Jesus sagte zu ihnen:
Wenn ihr Kinder Abrahams wärt, würdet ihr so handeln wie Abraham.

<<v40>>
40 Jetzt aber wollt ihr mich töten, einen Menschen, der euch die
Wahrheit verkündet hat, die Wahrheit, die ich von Gott gehört habe. So
hat Abraham nicht gehandelt.

<<v41>>
41 Ihr vollbringt die Werke eures Vaters. Sie entgegneten ihm: Wir
stammen nicht aus einem Ehebruch, sondern wir haben nur den einen Vater:
Gott.

<<v42>>
42 Jesus sagte zu ihnen: Wenn Gott euer Vater wäre, würdet ihr mich
lieben; denn von Gott bin ich ausgegangen und gekommen. Ich bin nicht in
meinem eigenen Namen gekommen, sondern er hat mich gesandt.
^{[[#fn25][25]]}

<<v43>>
43 Warum versteht ihr nicht, was ich sage? Weil ihr nicht imstande seid,
mein Wort zu hören.

<<v44>>
44 Ihr habt den Teufel zum Vater und ihr wollt das tun, wonach es euren
Vater verlangt. Er war ein Mörder von Anfang an. Und er steht nicht in
der Wahrheit; denn es ist keine Wahrheit in ihm. Wenn er lügt, sagt er
das, was aus ihm selbst kommt; denn er ist ein Lügner und ist der Vater
der Lüge. ^{[[#fn26][26]]}

<<v45>>
45 Mir aber glaubt ihr nicht, weil ich die Wahrheit sage.

<<v46>>
46 Wer von euch kann mir eine Sünde nachweisen? Wenn ich die Wahrheit
sage, warum glaubt ihr mir nicht? ^{[[#fn27][27]]}

<<v47>>
47 Wer aus Gott ist, hört die Worte Gottes; ihr hört sie deshalb nicht,
weil ihr nicht aus Gott seid. ^{[[#fn28][28]]}\\
\\

<<v48>>
**** Jesus und Abraham: 8,48-59
     :PROPERTIES:
     :CUSTOM_ID: jesus-und-abraham-848-59
     :END:
48 Da antworteten ihm die Juden: Sagen wir nicht mit Recht: Du bist ein
Samariter und von einem Dämon besessen?
^{[[#fn29][29]][[#fn30][30]][[#fn31][31]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 247\\
$ŽG://ESyn0812/\\
\\

<<v49>>
49 Jesus erwiderte: Ich bin von keinem Dämon besessen, sondern ich ehre
meinen Vater; ihr aber schmäht mich.

<<v50>>
50 Ich bin nicht auf meine Ehre bedacht; doch es gibt einen, der darauf
bedacht ist und der richtet. ^{[[#fn32][32]]}

<<v51>>
51 Amen, amen, ich sage euch: Wenn jemand an meinem Wort festhält, wird
er auf ewig den Tod nicht schauen. ^{[[#fn33][33]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 367\\
$ŽG://ESyn0812/\\
\\

<<v52>>
52 Da sagten die Juden zu ihm: Jetzt wissen wir, dass du von einem Dämon
besessen bist. Abraham und die Propheten sind gestorben, du aber sagst:
Wenn jemand an meinem Wort festhält, wird er auf ewig den Tod nicht
erleiden.

<<v53>>
53 Bist du etwa größer als unser Vater Abraham? Er ist gestorben und die
Propheten sind gestorben. Für wen gibst du dich aus? ^{[[#fn34][34]]}

<<v54>>
54 Jesus antwortete: Wenn ich mich selbst ehre, so gilt meine Ehre
nichts. Mein Vater ist es, der mich ehrt, er, von dem ihr sagt: Er ist
unser Gott.

<<v55>>
55 Doch ihr habt ihn nicht erkannt. Ich aber kenne ihn, und wenn ich
sagen würde: Ich kenne ihn nicht, so wäre ich ein Lügner wie ihr. Aber
ich kenne ihn und halte an seinem Wort fest.

<<v56>>
56 Euer Vater Abraham jubelte, weil er meinen Tag sehen sollte. Er sah
ihn und freute sich. ^{[[#fn35][35]]}

<<v57>>
57 Die Juden entgegneten: Du bist noch keine fünfzig Jahre alt und
willst Abraham gesehen haben? ^{[[#fn36][36]]}

<<v58>>
58 Jesus erwiderte ihnen: Amen, amen, ich sage euch: Noch ehe Abraham
wurde, bin ich.

<<v59>>
59 Da hoben sie Steine auf, um sie auf ihn zu werfen. Jesus aber verbarg
sich und verließ den Tempel. ^{[[#fn37][37]][[#fn38][38]]}\\
\\

^{[[#fnm1][1]]} ℘ ⇨Esyn: Synopse Nr. 274

^{[[#fnm2][2]]} ℘ Lk 21,38

^{[[#fnm3][3]]} ℘ Dtn 22,22-24

^{[[#fnm4][4]]} ℘ Jer 17,13

^{[[#fnm5][5]]} ℘ Dtn 17,7; Mt 7,1; Lk 6,37

^{[[#fnm6][6]]} Das Wort vom Licht knüpft möglicherweise an einen
Festbrauch an (vgl. die Anmerkung zu 7,37): Am siebten Tag des
Laubhüttenfestes wurden im Frauenvorhof des Tempels vier große Leuchter
aufgestellt, die ihr Licht über ganz Jerusalem verbreiten sollten.

^{[[#fnm7][7]]} ℘ ⇨Esyn: Synopse Nr. 243

^{[[#fnm8][8]]} ℘ 5,31f

^{[[#fnm9][9]]} ℘ 7,24

^{[[#fnm10][10]]} ℘ 5,30; 8,29

^{[[#fnm11][11]]} ℘ Dtn 17,6; 19,15

^{[[#fnm12][12]]} ℘ 7,28; 14,7; 15,21

^{[[#fnm13][13]]} ℘ 2,4; 7,30; 13,1

^{[[#fnm14][14]]} Die Schatzkammer, die auch in Mk 12,41.43; Lk 21,1
erwähnt wird, lag im Frauenvorhof.

^{[[#fnm15][15]]} ℘ 7,33f; 13,33 ⇨Esyn: Synopse Nr. 244

^{[[#fnm16][16]]} ℘ 3,13.31; 17,14-16

^{[[#fnm17][17]]} ℘ Jes 43,11; Joh 13,19

^{[[#fnm18][18]]} Der Sinn des griechischen Textes ist hier nicht sicher
zu ermitteln.

^{[[#fnm19][19]]} ℘ 3,14; 12,32; 14,24

^{[[#fnm20][20]]} ℘ 16,5

^{[[#fnm21][21]]} ℘ 10,42; 12,11 ⇨Esyn: Synopse Nr. 245

^{[[#fnm22][22]]} ℘ 14,21-23

^{[[#fnm23][23]]} ℘ 1 Joh 3,8

^{[[#fnm24][24]]} ℘ ⇨Esyn: Synopse Nr. 246

^{[[#fnm25][25]]} ℘ 1 Joh 5,1

^{[[#fnm26][26]]} ℘ 1 Joh 3,8-15

^{[[#fnm27][27]]} ℘ 1 Joh 3,5

^{[[#fnm28][28]]} ℘ 1 Joh 4,6

^{[[#fnm29][29]]} ℘ 7,20

^{[[#fnm30][30]]} In der Bezeichnung Jesu als «Samariter» steckt wohl
der Vorwurf, dass Jesus Gott nicht wahrhaft verehrt (vgl. die Anmerkung
zu 4,4-6). Zum Vorwurf der Besessenheit vgl. auch 7,20; 10,20.

^{[[#fnm31][31]]} ℘ ⇨Esyn: Synopse Nr. 247

^{[[#fnm32][32]]} ℘ 7,18

^{[[#fnm33][33]]} ℘ ⇨Esyn: Synopse Nr. 367

^{[[#fnm34][34]]} ℘ 4,12

^{[[#fnm35][35]]} ℘ Gen 17,17

^{[[#fnm36][36]]} «Fünfzig» ist als eine runde Zahl zu verstehen, nicht
als Angabe über das Lebensalter Jesu.

^{[[#fnm37][37]]} ℘ 10,31.39; 11,8

^{[[#fnm38][38]]} Auf Gotteslästerung stand die Strafe der Steinigung
(Lev 24,11-16; 1 Kön 21,10.13). Der Vorwurf der Gotteslästerung taucht
auch noch später auf: 10,31-33; vgl. 11,8; 19,7.
