:PROPERTIES:
:ID:       ad985c95-2fda-4acc-83bd-512f68ff0153
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Johannes* --
[[file:Joh_1.html][1]] ... [[file:Joh_15.html][15]]
[[file:Joh_16.html][16]] *17* [[file:Joh_18.html][18]]
[[file:Joh_19.html][19]] ... [[file:Joh_21.html][21]]

--------------

* Joh 17
  :PROPERTIES:
  :CUSTOM_ID: joh-17
  :END:

<<verses>>

<<v1>>
*** Das Abschiedsgebet des Herrn: 17,1-26
    :PROPERTIES:
    :CUSTOM_ID: das-abschiedsgebet-des-herrn-171-26
    :END:
**** Jesu Rechenschaft vor dem Vater: 17,1-8
     :PROPERTIES:
     :CUSTOM_ID: jesu-rechenschaft-vor-dem-vater-171-8
     :END:
1 Dies sagte Jesus. Und er erhob seine Augen zum Himmel und sprach:
Vater, die Stunde ist da. Verherrliche deinen Sohn, damit der Sohn dich
verherrlicht. ^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 329\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Denn du hast ihm Macht über alle Menschen gegeben, damit er allen, die
du ihm gegeben hast, ewiges Leben schenkt. ^{[[#fn4][4]]}

<<v3>>
3 Das ist das ewige Leben: dich, den einzigen wahren Gott, zu erkennen
und Jesus Christus, den du gesandt hast. ^{[[#fn5][5]]}

<<v4>>
4 Ich habe dich auf der Erde verherrlicht und das Werk zu Ende geführt,
das du mir aufgetragen hast.

<<v5>>
5 Vater, verherrliche du mich jetzt bei dir mit der Herrlichkeit, die
ich bei dir hatte, bevor die Welt war. ^{[[#fn6][6]]}

<<v6>>
6 Ich habe deinen Namen den Menschen offenbart, die du mir aus der Welt
gegeben hast. Sie gehörten dir und du hast sie mir gegeben, und sie
haben an deinem Wort festgehalten. ^{[[#fn7][7]]}

<<v7>>
7 Sie haben jetzt erkannt, dass alles, was du mir gegeben hast, von dir
ist.

<<v8>>
8 Denn die Worte, die du mir gegeben hast, gab ich ihnen und sie haben
sie angenommen. Sie haben wirklich erkannt, dass ich von dir ausgegangen
bin, und sie sind zu dem Glauben gekommen, dass du mich gesandt hast.
^{[[#fn8][8]]}\\
\\

<<v9>>
**** Jesu Fürbitte für die Jünger: 17,9-19
     :PROPERTIES:
     :CUSTOM_ID: jesu-fürbitte-für-die-jünger-179-19
     :END:
9 Für sie bitte ich; nicht für die Welt bitte ich, sondern für alle, die
du mir gegeben hast; denn sie gehören dir. ^{[[#fn9][9]]}

<<v10>>
10 Alles, was mein ist, ist dein, und was dein ist, ist mein; in ihnen
bin ich verherrlicht.

<<v11>>
11 Ich bin nicht mehr in der Welt, aber sie sind in der Welt, und ich
gehe zu dir. Heiliger Vater, bewahre sie in deinem Namen, den du mir
gegeben hast, damit sie eins sind wie wir.

<<v12>>
12 Solange ich bei ihnen war, bewahrte ich sie in deinem Namen, den du
mir gegeben hast. Und ich habe sie behütet und keiner von ihnen ging
verloren, außer dem Sohn des Verderbens, damit sich die Schrift erfüllt.
^{[[#fn10][10]][[#fn11][11]]}

<<v13>>
13 Aber jetzt gehe ich zu dir. Doch dies rede ich noch in der Welt,
damit sie meine Freude in Fülle in sich haben. ^{[[#fn12][12]]}

<<v14>>
14 Ich habe ihnen dein Wort gegeben und die Welt hat sie gehasst, weil
sie nicht von der Welt sind, wie auch ich nicht von der Welt bin.
^{[[#fn13][13]]}

<<v15>>
15 Ich bitte nicht, dass du sie aus der Welt nimmst, sondern dass du sie
vor dem Bösen bewahrst. ^{[[#fn14][14]]}

<<v16>>
16 Sie sind nicht von der Welt, wie auch ich nicht von der Welt bin.

<<v17>>
17 Heilige sie in der Wahrheit; dein Wort ist Wahrheit.

<<v18>>
18 Wie du mich in die Welt gesandt hast, so habe auch ich sie in die
Welt gesandt.

<<v19>>
19 Und ich heilige mich für sie, damit auch sie in der Wahrheit
geheiligt sind.\\
\\

<<v20>>
**** Jesu Fürbitte für alle Glaubenden: 17,20-26
     :PROPERTIES:
     :CUSTOM_ID: jesu-fürbitte-für-alle-glaubenden-1720-26
     :END:
20 Aber ich bitte nicht nur für diese hier, sondern auch für alle, die
durch ihr Wort an mich glauben.

<<v21>>
21 Alle sollen eins sein: Wie du, Vater, in mir bist und ich in dir bin,
sollen auch sie in uns sein, damit die Welt glaubt, dass du mich gesandt
hast. ^{[[#fn15][15]]}

<<v22>>
22 Und ich habe ihnen die Herrlichkeit gegeben, die du mir gegeben hast;
denn sie sollen eins sein, wie wir eins sind,

<<v23>>
23 ich in ihnen und du in mir. So sollen sie vollendet sein in der
Einheit, damit die Welt erkennt, dass du mich gesandt hast und die
Meinen ebenso geliebt hast wie mich. ^{[[#fn16][16]]}

<<v24>>
24 Vater, ich will, dass alle, die du mir gegeben hast, dort bei mir
sind, wo ich bin. Sie sollen meine Herrlichkeit sehen, die du mir
gegeben hast, weil du mich schon geliebt hast vor der Erschaffung der
Welt. ^{[[#fn17][17]]}

<<v25>>
25 Gerechter Vater, die Welt hat dich nicht erkannt, ich aber habe dich
erkannt und sie haben erkannt, dass du mich gesandt hast.

<<v26>>
26 Ich habe ihnen deinen Namen bekannt gemacht und werde ihn bekannt
machen, damit die Liebe, mit der du mich geliebt hast, in ihnen ist und
damit ich in ihnen bin. ^{[[#fn18][18]]}\\
\\

^{[[#fnm1][1]]} ℘ 7,39; 8,54; 11,4; 12,16.23.28; 13,31f; 14,13; 15,8;
16,14

^{[[#fnm2][2]]} 1-26: Dieser Abschnitt wird das «Hohepriesterliche
Gebet» Jesu genannt.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 329

^{[[#fnm4][4]]} ℘ 3,15; 5,24; 6,40; 10,10.28

^{[[#fnm5][5]]} ℘ 1 Joh 5,20; 1 Kor 8,6

^{[[#fnm6][6]]} ℘ Joh 1,1f; 1 Joh 1,2; Phil 2,6; Hebr 1,3

^{[[#fnm7][7]]} ℘ 17,26

^{[[#fnm8][8]]} ℘ 5,36; 6,57; 11,42; 17,25

^{[[#fnm9][9]]} «Welt» meint die gottfeindliche, alles Heilige
ablehnende Menschheit (1,10).

^{[[#fnm10][10]]} ℘ 10,28; Ps 41,10

^{[[#fnm11][11]]} Der «Sohn des Verderbens» (2 Thess 2,3) ist Judas
Iskariot (13,18.27.29).

^{[[#fnm12][12]]} ℘ 15,11; 16,22

^{[[#fnm13][13]]} ℘ 15,19

^{[[#fnm14][14]]} ℘ Mt 6,13; 1 Joh 2,13f

^{[[#fnm15][15]]} ℘ 10,30

^{[[#fnm16][16]]} Die Welt soll dadurch zum Glauben kommen, dass sie die
Einheit und Einigkeit der Christen sieht.

^{[[#fnm17][17]]} ℘ 12,26; 14,3

^{[[#fnm18][18]]} ℘ 15,15
