:PROPERTIES:
:ID:       846d54b0-162e-4654-9c22-26c92401728f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Kolosser* --
[[file:Kol_1.html][1]] *2* [[file:Kol_3.html][3]] [[file:Kol_4.html][4]]

--------------

* Kol 2
  :PROPERTIES:
  :CUSTOM_ID: kol-2
  :END:

<<verses>>

<<v1>>
**** Der Glaube der Gemeinde: 2,1-7
     :PROPERTIES:
     :CUSTOM_ID: der-glaube-der-gemeinde-21-7
     :END:
1 Ihr sollt wissen, was für einen schweren Kampf ich für euch und für
die Gläubigen in Laodizea zu bestehen habe, auch für alle anderen, die
mich persönlich nie gesehen haben.

<<v2>>
2 Dadurch sollen sie getröstet werden; sie sollen in Liebe
zusammenhalten, um die tiefe und reiche Einsicht zu erlangen und das
göttliche Geheimnis zu erkennen, das Christus ist.

<<v3>>
3 In ihm sind alle Schätze der Weisheit und Erkenntnis verborgen.
^{[[#fn1][1]]}

<<v4>>
4 Das sage ich, damit euch niemand durch Überredungskünste täuscht.

<<v5>>
5 Auch wenn ich fern von euch weile, bin ich im Geist bei euch. Mit
Freude sehe ich, wie fest und geordnet euer Glaube an Christus ist.

<<v6>>
6 Ihr habt Christus Jesus als Herrn angenommen. Darum lebt auch in ihm!

<<v7>>
7 Bleibt in ihm verwurzelt und auf ihn gegründet und haltet an dem
Glauben fest, in dem ihr unterrichtet wurdet. Hört nicht auf zu danken!
^{[[#fn2][2]]}\\
\\

<<v8>>
**** Warnung vor Irrlehrern: 2,8-23
     :PROPERTIES:
     :CUSTOM_ID: warnung-vor-irrlehrern-28-23
     :END:
8 Gebt Acht, dass euch niemand mit seiner Philosophie und falschen Lehre
verführt, die sich nur auf menschliche Überlieferung stützen und sich
auf die Elementarmächte der Welt, nicht auf Christus berufen.
^{[[#fn3][3]]}

<<v9>>
9 Denn in ihm allein wohnt wirklich die ganze Fülle Gottes.

<<v10>>
10 Durch ihn seid auch ihr davon erfüllt; denn er ist das Haupt aller
Mächte und Gewalten.

<<v11>>
11 In ihm habt ihr eine Beschneidung empfangen, die man nicht mit Händen
vornimmt, nämlich die Beschneidung, die Christus gegeben hat. Wer sie
empfängt, sagt sich los von seinem vergänglichen Körper. ^{[[#fn4][4]]}

<<v12>>
12 Mit Christus wurdet ihr in der Taufe begraben, mit ihm auch
auferweckt, durch den Glauben an die Kraft Gottes, der ihn von den Toten
auferweckt hat. ^{[[#fn5][5]]}

<<v13>>
13 Ihr wart tot infolge eurer Sünden, und euer Leib war unbeschnitten;
Gott aber hat euch mit Christus zusammen lebendig gemacht und uns alle
Sünden vergeben. ^{[[#fn6][6]]}

<<v14>>
14 Er hat den Schuldschein, der gegen uns sprach, durchgestrichen und
seine Forderungen, die uns anklagten, aufgehoben. Er hat ihn dadurch
getilgt, dass er ihn an das Kreuz geheftet hat.

<<v15>>
15 Die Fürsten und Gewalten hat er entwaffnet und öffentlich zur Schau
gestellt; durch Christus hat er über sie triumphiert. ^{[[#fn7][7]]}

<<v16>>
16 Darum soll euch niemand verurteilen wegen Speise und Trank oder wegen
eines Festes, ob Neumond oder Sabbat. ^{[[#fn8][8]]}

<<v17>>
17 Das alles ist nur ein Schatten von dem, was kommen wird, die
Wirklichkeit aber ist Christus. ^{[[#fn9][9]]}

<<v18>>
18 Niemand soll euch verachten, der sich in scheinbarer Demut auf die
Verehrung beruft, die er den Engeln erweist, der mit Visionen prahlt und
sich ohne Grund nach weltlicher Art wichtig macht.

<<v19>>
19 Er hält sich nicht an das Haupt, von dem aus der ganze Leib durch
Gelenke und Bänder versorgt und zusammengehalten wird und durch Gottes
Wirken wächst. ^{[[#fn10][10]]}

<<v20>>
20 Wenn ihr mit Christus gestorben seid und euch von den Elementen der
Welt losgesagt habt, warum lasst ihr euch dann, als würdet ihr noch in
der Welt leben, vorschreiben:

<<v21>>
21 Berühre das nicht, iss nicht davon, fass das nicht an!

<<v22>>
22 Das alles wird verbraucht und dadurch vernichtet. /Menschliche
Satzungen und Lehren/ sind es. ^{[[#fn11][11]]}

<<v23>>
23 Man sagt zwar, in ihnen liege Weisheit, es sei ein besonderer Kult,
ein Zeichen von Demut, seinen Körper zu kasteien. Doch es bringt keine
Ehre ein, sondern befriedigt nur die irdische Eitelkeit.\\
\\

^{[[#fnm1][1]]} ℘ Jes 45,3; Spr 2,2f

^{[[#fnm2][2]]} ℘ Eph 2,20; 3,17

^{[[#fnm3][3]]} Die Verehrung und Anerkennung der «Elementarmächte»
wurde von manchen Irrlehrern gefordert (vgl. die Anmerkung zu Gal 4,3).

^{[[#fnm4][4]]} Die Beschneidung, die Christus gegeben hat: Umschreibung
für die Taufe. Der Satz richtet sich vermutlich gegen Irrlehrer, die
verlangten, dass man sich auch körperlich beschneiden lasse.

^{[[#fnm5][5]]} ℘ Röm 6,4

^{[[#fnm6][6]]} ℘ Eph 2,1.5

^{[[#fnm7][7]]} ℘ Eph 1,21

^{[[#fnm8][8]]} 16-18: Zur Verehrung der Gestirne, wie sie die Irrlehrer
forderten, gehörte die Beachtung verschiedener anderer Vorschriften, z.
B. die Einhaltung von Speisegeboten und heiligen Zeiten.

^{[[#fnm9][9]]} ℘ Hebr 8,5; 10,1

^{[[#fnm10][10]]} ℘ Eph 2,22; 4,16

^{[[#fnm11][11]]} ℘ Jes 29,13 G
