:PROPERTIES:
:ID:       a05af43f-8523-4d11-82e8-619fff90c067
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Lukas* --
[[file:Lk_1.html][1]] ... [[file:Lk_8.html][8]] [[file:Lk_9.html][9]]
*10* [[file:Lk_11.html][11]] [[file:Lk_12.html][12]] ...
[[file:Lk_24.html][24]]

--------------

* Lk 10
  :PROPERTIES:
  :CUSTOM_ID: lk-10
  :END:

<<verses>>

<<v1>>
**** Die Aussendung der zweiundsiebzig Jünger: 10,1-16
     :PROPERTIES:
     :CUSTOM_ID: die-aussendung-der-zweiundsiebzig-jünger-101-16
     :END:
1 Danach suchte der Herr zweiundsiebzig andere aus und sandte sie zu
zweit voraus in alle Städte und Ortschaften, in die er selbst gehen
wollte. ^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 177\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Er sagte zu ihnen: Die Ernte ist groß, aber es gibt nur wenig
Arbeiter. Bittet also den Herrn der Ernte, Arbeiter für seine Ernte
auszusenden. ^{[[#fn4][4]]}

<<v3>>
3 Geht! Ich sende euch wie Schafe mitten unter die Wölfe.

<<v4>>
4 Nehmt keinen Geldbeutel mit, keine Vorratstasche und keine Schuhe!
Grüßt niemand unterwegs! ^{[[#fn5][5]]}

<<v5>>
5 Wenn ihr in ein Haus kommt, so sagt als erstes: Friede diesem Haus!

<<v6>>
6 Und wenn dort ein Mann des Friedens wohnt, wird der Friede, den ihr
ihm wünscht, auf ihm ruhen; andernfalls wird er zu euch zurückkehren.
^{[[#fn6][6]]}

<<v7>>
7 Bleibt in diesem Haus, esst und trinkt, was man euch anbietet; denn
wer arbeitet, hat ein Recht auf seinen Lohn. Zieht nicht von einem Haus
in ein anderes!

<<v8>>
8 Wenn ihr in eine Stadt kommt und man euch aufnimmt, so esst, was man
euch vorsetzt.

<<v9>>
9 Heilt die Kranken, die dort sind, und sagt den Leuten: Das Reich
Gottes ist euch nahe. ^{[[#fn7][7]]}

<<v10>>
10 Wenn ihr aber in eine Stadt kommt, in der man euch nicht aufnimmt,
dann stellt euch auf die Straße und ruft:

<<v11>>
11 Selbst den Staub eurer Stadt, der an unseren Füßen klebt, lassen wir
euch zurück; doch das sollt ihr wissen: Das Reich Gottes ist nahe.

<<v12>>
12 Ich sage euch: Sodom wird es an jenem Tag nicht so schlimm ergehen
wie dieser Stadt. ^{[[#fn8][8]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 108\\
$ŽG://ESyn0812/\\
\\

<<v13>>
13 Weh dir, Chorazin! Weh dir, Betsaida! Wenn einst in Tyrus und Sidon
die Wunder geschehen wären, die bei euch geschehen sind - man hätte dort
in Sack und Asche Buße getan.
^{[[#fn9][9]][[#fn10][10]][[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 178\\
$ŽG://ESyn0812/\\
\\

<<v14>>
14 Tyrus und Sidon wird es beim Gericht nicht so schlimm ergehen wie
euch.

<<v15>>
15 Und du, Kafarnaum, meinst du etwa, /du wirst bis zum Himmel erhoben?
Nein, in die Unterwelt wirst du hinabgeworfen./ ^{[[#fn12][12]]}

<<v16>>
16 Wer euch hört, der hört mich, und wer euch ablehnt, der lehnt mich
ab; wer aber mich ablehnt, der lehnt den ab, der mich gesandt hat.
^{[[#fn13][13]]}\\
^{[[#fn14][14]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 309\\
$ŽG://ESyn0812/

<<v17>>
**** Der Lohn der Jünger: 10,17-20
     :PROPERTIES:
     :CUSTOM_ID: der-lohn-der-jünger-1017-20
     :END:
17 Die Zweiundsiebzig kehrten zurück und berichteten voll Freude: Herr,
sogar die Dämonen gehorchen uns, wenn wir deinen Namen aussprechen.
^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 180\\
$ŽG://ESyn0812/\\
\\

<<v18>>
18 Da sagte er zu ihnen: Ich sah den Satan wie einen Blitz vom Himmel
fallen. ^{[[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 302\\
$ŽG://ESyn0812/\\
\\

<<v19>>
19 Seht, ich habe euch die Vollmacht gegeben, auf Schlangen und
Skorpione zu treten und die ganze Macht des Feindes zu überwinden.
Nichts wird euch schaden können. ^{[[#fn17][17]][[#fn18][18]]}

<<v20>>
20 Doch freut euch nicht darüber, dass euch die Geister gehorchen,
sondern freut euch darüber, dass eure Namen im Himmel verzeichnet
sind.\\
\\

<<v21>>
**** Der Dank Jesu an den Vater: 10,21-22
     :PROPERTIES:
     :CUSTOM_ID: der-dank-jesu-an-den-vater-1021-22
     :END:
21 In dieser Stunde rief Jesus, vom Heiligen Geist erfüllt, voll Freude
aus: Ich preise dich, Vater, Herr des Himmels und der Erde, weil du all
das den Weisen und Klugen verborgen, den Unmündigen aber offenbart hast.
Ja, Vater, so hat es dir gefallen.
^{[[#fn19][19]][[#fn20][20]][[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 181\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 Mir ist von meinem Vater alles übergeben worden; niemand weiß, wer
der Sohn ist, nur der Vater, und niemand weiß, wer der Vater ist, nur
der Sohn und der, dem es der Sohn offenbaren will. ^{[[#fn22][22]]}\\
\\

<<v23>>
**** Die Seligpreisung der Jünger: 10,23-24
     :PROPERTIES:
     :CUSTOM_ID: die-seligpreisung-der-jünger-1023-24
     :END:
23 Jesus wandte sich an die Jünger und sagte zu ihnen allein: Selig sind
die, deren Augen sehen, was ihr seht. ^{[[#fn23][23]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 123\\
$ŽG://ESyn0812/\\
\\

<<v24>>
24 Ich sage euch: Viele Propheten und Könige wollten sehen, was ihr
seht, und haben es nicht gesehen und wollten hören, was ihr hört, und
haben es nicht gehört. ^{[[#fn24][24]]}\\
\\

<<v25>>
**** Das Beispiel vom barmherzigen Samariter: 10,25-37
     :PROPERTIES:
     :CUSTOM_ID: das-beispiel-vom-barmherzigen-samariter-1025-37
     :END:
25 Da stand ein Gesetzeslehrer auf, und um Jesus auf die Probe zu
stellen, fragte er ihn: Meister, was muss ich tun, um das ewige Leben zu
gewinnen? ^{[[#fn25][25]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 182\\
$ŽG://ESyn0812/\\
\\

<<v26>>
26 Jesus sagte zu ihm: Was steht im Gesetz? Was liest du dort?

<<v27>>
27 Er antwortete: /Du sollst den Herrn, deinen Gott, lieben mit ganzem
Herzen und ganzer Seele, mit all deiner Kraft/ und all deinen Gedanken,
und: /Deinen Nächsten sollst du lieben wie dich selbst./
^{[[#fn26][26]]}

<<v28>>
28 Jesus sagte zu ihm: Du hast richtig geantwortet. Handle danach und du
wirst leben. ^{[[#fn27][27]]}

<<v29>>
29 Der Gesetzeslehrer wollte seine Frage rechtfertigen und sagte zu
Jesus: Und wer ist mein Nächster?
^{[[#fn28][28]][[#fn29][29]][[#fn30][30]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 183\\
$ŽG://ESyn0812/\\
\\

<<v30>>
30 Darauf antwortete ihm Jesus: Ein Mann ging von Jerusalem nach Jericho
hinab und wurde von Räubern überfallen. Sie plünderten ihn aus und
schlugen ihn nieder; dann gingen sie weg und ließen ihn halb tot liegen.

<<v31>>
31 Zufällig kam ein Priester denselben Weg herab; er sah ihn und ging
weiter.

<<v32>>
32 Auch ein Levit kam zu der Stelle; er sah ihn und ging weiter.

<<v33>>
33 Dann kam ein Mann aus Samarien, der auf der Reise war. Als er ihn
sah, hatte er Mitleid, ^{[[#fn31][31]][[#fn32][32]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 240\\
$ŽG://ESyn0812/\\
\\

<<v34>>
34 ging zu ihm hin, goss Öl und Wein auf seine Wunden und verband sie.
Dann hob er ihn auf sein Reittier, brachte ihn zu einer Herberge und
sorgte für ihn.

<<v35>>
35 Am andern Morgen holte er zwei Denare hervor, gab sie dem Wirt und
sagte: Sorge für ihn, und wenn du mehr für ihn brauchst, werde ich es
dir bezahlen, wenn ich wiederkomme.

<<v36>>
36 Was meinst du: Wer von diesen dreien hat sich als der Nächste dessen
erwiesen, der von den Räubern überfallen wurde?

<<v37>>
37 Der Gesetzeslehrer antwortete: Der, der barmherzig an ihm gehandelt
hat. Da sagte Jesus zu ihm: Dann geh und handle genauso!\\
\\

<<v38>>
**** Maria und Marta: 10,38-42
     :PROPERTIES:
     :CUSTOM_ID: maria-und-marta-1038-42
     :END:
38 Sie zogen zusammen weiter und er kam in ein Dorf. Eine Frau namens
Marta nahm ihn freundlich auf.
^{[[#fn33][33]][[#fn34][34]][[#fn35][35]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 184\\
$ŽG://ESyn0812/\\
\\

<<v39>>
39 Sie hatte eine Schwester, die Maria hieß. Maria setzte sich dem Herrn
zu Füßen und hörte seinen Worten zu.

<<v40>>
40 Marta aber war ganz davon in Anspruch genommen, für ihn zu sorgen.
Sie kam zu ihm und sagte: Herr, kümmert es dich nicht, dass meine
Schwester die ganze Arbeit mir allein überlässt? Sag ihr doch, sie soll
mir helfen!

<<v41>>
41 Der Herr antwortete: Marta, Marta, du machst dir viele Sorgen und
Mühen.

<<v42>>
42 Aber nur eines ist notwendig. Maria hat das Bessere gewählt, das soll
ihr nicht genommen werden. ^{[[#fn36][36]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-12) 9,1-6; Mt 10,7-16; Mk 6,8-11

^{[[#fnm2][2]]} 1-12: Vgl. die Anmerkung zu Mt 9,35 - 11,1. 1.17: Statt
«zweiundsiebzig» haben zahlreiche alte Textzeugen «siebzig».

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 177

^{[[#fnm4][4]]} ℘ Mt 9,37f

^{[[#fnm5][5]]} ℘ 22,35

^{[[#fnm6][6]]} Mann des Friedens, wörtlich: Sohn des Friedens.

^{[[#fnm7][7]]} ℘ Mt 4,17

^{[[#fnm8][8]]} ℘ ⇨Esyn: Synopse Nr. 108

^{[[#fnm9][9]]} ℘ (13-15) Mt 11,20-24

^{[[#fnm10][10]]} 13-15: Vgl. die Anmerkung zu Mt 11,21f.

^{[[#fnm11][11]]} ℘ ⇨Esyn: Synopse Nr. 178

^{[[#fnm12][12]]} ℘ Jes 14,13.15

^{[[#fnm13][13]]} ℘ Mt 10,40; Joh 13,20

^{[[#fnm14][14]]} ℘ ⇨Esyn: Synopse Nr. 309

^{[[#fnm15][15]]} ℘ 9,10; Mk 6,30f ⇨Esyn: Synopse Nr. 180

^{[[#fnm16][16]]} ℘ ⇨Esyn: Synopse Nr. 302

^{[[#fnm17][17]]} ℘ Ps 91,13

^{[[#fnm18][18]]} Andere Übersetzungsmöglichkeit: überwinden, und er
(das heißt der Feind) wird euch in keiner Weise schaden können.

^{[[#fnm19][19]]} ℘ Jes 29,14 G; (21-22) Mt 11,25-27

^{[[#fnm20][20]]} Einige Textzeugen haben: vom Geist erfüllt.

^{[[#fnm21][21]]} ℘ ⇨Esyn: Synopse Nr. 181

^{[[#fnm22][22]]} ℘ Joh 10,15

^{[[#fnm23][23]]} ℘ (23-24) Mt 13,16f ⇨Esyn: Synopse Nr. 123

^{[[#fnm24][24]]} ℘ 1 Petr 1,10-12

^{[[#fnm25][25]]} ℘ 18,18; (25-28) Mt 22,35-40; Mk 12,28-31 ⇨Esyn:
Synopse Nr. 182

^{[[#fnm26][26]]} ℘ Dtn 6,5; Lev 19,18; Mt 5,43; Röm 13,9; Gal 5,14

^{[[#fnm27][27]]} ℘ Lev 18,5

^{[[#fnm28][28]]} ℘ Lev 19,16-18

^{[[#fnm29][29]]} seine Frage, wörtlich: sich.

^{[[#fnm30][30]]} ℘ ⇨Esyn: Synopse Nr. 183

^{[[#fnm31][31]]} 33-37: Vgl. 9,51-56 und die Anmerkung zu Joh 4,4-6.

^{[[#fnm32][32]]} ℘ ⇨Esyn: Synopse Nr. 240

^{[[#fnm33][33]]} ℘ (38-42) Joh 11,1; 12,1-3

^{[[#fnm34][34]]} Statt «freundlich» haben viele Textzeugen «in ihr
Haus».

^{[[#fnm35][35]]} ℘ ⇨Esyn: Synopse Nr. 184

^{[[#fnm36][36]]} Zahlreiche Textzeugen haben stattdessen: Aber wenig
ist notwendig oder nur eines. - das Bessere, andere
Übersetzungsmöglichkeit: das Richtige.
