:PROPERTIES:
:ID:       edfce7e1-d2c4-4300-b96e-fecaa1ed4fd9
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Lukas* --
[[file:Lk_1.html][1]] ... [[file:Lk_12.html][12]]
[[file:Lk_13.html][13]] *14* [[file:Lk_15.html][15]]
[[file:Lk_16.html][16]] ... [[file:Lk_24.html][24]]

--------------

* Lk 14
  :PROPERTIES:
  :CUSTOM_ID: lk-14
  :END:

<<verses>>

<<v1>>
**** Die Heilung eines Wassersüchtigen am Sabbat: 14,1-6
     :PROPERTIES:
     :CUSTOM_ID: die-heilung-eines-wassersüchtigen-am-sabbat-141-6
     :END:
1 Als Jesus an einem Sabbat in das Haus eines führenden Pharisäers zum
Essen kam, beobachtete man ihn genau. ^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 214\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Da stand auf einmal ein Mann vor ihm, der an Wassersucht litt.

<<v3>>
3 Jesus wandte sich an die Gesetzeslehrer und die Pharisäer und fragte:
Ist es am Sabbat erlaubt zu heilen, oder nicht?

<<v4>>
4 Sie schwiegen. Da berührte er den Mann, heilte ihn und ließ ihn gehen.

<<v5>>
5 Zu ihnen aber sagte er: Wer von euch wird seinen Sohn oder seinen
Ochsen, der in den Brunnen fällt, nicht sofort herausziehen, auch am
Sabbat? ^{[[#fn2][2]]}

<<v6>>
6 Darauf konnten sie ihm nichts erwidern.\\
\\

<<v7>>
**** Mahnung zur Bescheidenheit: 14,7-11
     :PROPERTIES:
     :CUSTOM_ID: mahnung-zur-bescheidenheit-147-11
     :END:
7 Als er bemerkte, wie sich die Gäste die Ehrenplätze aussuchten, nahm
er das zum Anlass, ihnen eine Lehre zu erteilen. Er sagte zu ihnen:
^{[[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 215\\
$ŽG://ESyn0812/\\
\\

<<v8>>
8 Wenn du zu einer Hochzeit eingeladen bist, such dir nicht den
Ehrenplatz aus. Denn es könnte ein anderer eingeladen sein, der
vornehmer ist als du,

<<v9>>
9 und dann würde der Gastgeber, der dich und ihn eingeladen hat, kommen
und zu dir sagen: Mach diesem hier Platz! Du aber wärst beschämt und
müsstest den untersten Platz einnehmen.

<<v10>>
10 Wenn du also eingeladen bist, setz dich lieber, wenn du hinkommst,
auf den untersten Platz; dann wird der Gastgeber zu dir kommen und
sagen: Mein Freund, rück weiter hinauf! Das wird für dich eine Ehre sein
vor allen anderen Gästen.

<<v11>>
11 Denn wer sich selbst erhöht, wird erniedrigt, und wer sich selbst
erniedrigt, wird erhöht werden. ^{[[#fn4][4]]}\\
\\

<<v12>>
**** Von den rechten Gästen: 14,12-14
     :PROPERTIES:
     :CUSTOM_ID: von-den-rechten-gästen-1412-14
     :END:
12 Dann sagte er zu dem Gastgeber: Wenn du mittags oder abends ein Essen
gibst, so lade nicht deine Freunde oder deine Brüder, deine Verwandten
oder reiche Nachbarn ein; sonst laden auch sie dich ein, und damit ist
dir wieder alles vergolten.

<<v13>>
13 Nein, wenn du ein Essen gibst, dann lade Arme, Krüppel, Lahme und
Blinde ein.

<<v14>>
14 Du wirst selig sein, denn sie können es dir nicht vergelten; es wird
dir vergolten werden bei der Auferstehung der Gerechten.\\
\\

<<v15>>
**** Das Gleichnis vom Festmahl: 14,15-24
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-festmahl-1415-24
     :END:
15 Als einer der Gäste das hörte, sagte er zu Jesus: Selig, wer im Reich
Gottes am Mahl teilnehmen darf. ^{[[#fn5][5]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 216\\
$ŽG://ESyn0812/\\
\\

<<v16>>
16 Jesus sagte zu ihm: Ein Mann veranstaltete ein großes Festmahl und
lud viele dazu ein.

<<v17>>
17 Als das Fest beginnen sollte, schickte er seinen Diener und ließ den
Gästen, die er eingeladen hatte, sagen: Kommt, es steht alles bereit!

<<v18>>
18 Aber einer nach dem andern ließ sich entschuldigen. Der erste ließ
ihm sagen: Ich habe einen Acker gekauft und muss jetzt gehen und ihn
besichtigen. Bitte, entschuldige mich!

<<v19>>
19 Ein anderer sagte: Ich habe fünf Ochsengespanne gekauft und bin auf
dem Weg, sie mir genauer anzusehen. Bitte, entschuldige mich!

<<v20>>
20 Wieder ein anderer sagte: Ich habe geheiratet und kann deshalb nicht
kommen.

<<v21>>
21 Der Diener kehrte zurück und berichtete alles seinem Herrn. Da wurde
der Herr zornig und sagte zu seinem Diener: Geh schnell auf die Straßen
und Gassen der Stadt und hol die Armen und die Krüppel, die Blinden und
die Lahmen herbei.

<<v22>>
22 Bald darauf meldete der Diener: Herr, dein Auftrag ist ausgeführt;
aber es ist immer noch Platz.

<<v23>>
23 Da sagte der Herr zu dem Diener: Dann geh auf die Landstraßen und vor
die Stadt hinaus und nötige die Leute zu kommen, damit mein Haus voll
wird.

<<v24>>
24 Das aber sage ich euch: Keiner von denen, die eingeladen waren, wird
an meinem Mahl teilnehmen.\\
\\

<<v25>>
**** Vom Ernst der Nachfolge: 14,25-35
     :PROPERTIES:
     :CUSTOM_ID: vom-ernst-der-nachfolge-1425-35
     :END:
25 Viele Menschen begleiteten ihn; da wandte er sich an sie und sagte:
^{[[#fn6][6]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 217\\
$ŽG://ESyn0812/\\
\\

<<v26>>
26 Wenn jemand zu mir kommt und nicht Vater und Mutter, Frau und Kinder,
Brüder und Schwestern, ja sogar sein Leben gering achtet, dann kann er
nicht mein Jünger sein. ^{[[#fn7][7]]}

<<v27>>
27 Wer nicht sein Kreuz trägt und mir nachfolgt, der kann nicht mein
Jünger sein. ^{[[#fn8][8]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 160\\
$ŽG://ESyn0812/\\
\\

<<v28>>
28 Wenn einer von euch einen Turm bauen will, setzt er sich dann nicht
zuerst hin und rechnet, ob seine Mittel für das ganze Vorhaben
ausreichen?

<<v29>>
29 Sonst könnte es geschehen, dass er das Fundament gelegt hat, dann
aber den Bau nicht fertig stellen kann. Und alle, die es sehen, würden
ihn verspotten

<<v30>>
30 und sagen: Der da hat einen Bau begonnen und konnte ihn nicht zu Ende
führen.

<<v31>>
31 Oder wenn ein König gegen einen anderen in den Krieg zieht, setzt er
sich dann nicht zuerst hin und überlegt, ob er sich mit seinen
zehntausend Mann dem entgegenstellen kann, der mit zwanzigtausend gegen
ihn anrückt?

<<v32>>
32 Kann er es nicht, dann schickt er eine Gesandtschaft, solange der
andere noch weit weg ist, und bittet um Frieden.

<<v33>>
33 Darum kann keiner von euch mein Jünger sein, wenn er nicht auf seinen
ganzen Besitz verzichtet.

<<v34>>
34 Das Salz ist etwas Gutes. Wenn aber das Salz seinen Geschmack
verliert, womit kann man ihm die Würze wiedergeben?
^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 218\\
$ŽG://ESyn0812/\\
\\

<<v35>>
35 Es taugt weder für den Acker noch für den Misthaufen, man wirft es
weg. Wer Ohren hat zum Hören, der höre! ^{[[#fn10][10]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-6) 6,6-11 ⇨Esyn: Synopse Nr. 214

^{[[#fnm2][2]]} seinen Sohn, andere Lesart: seinen Esel.

^{[[#fnm3][3]]} ℘ 20,46; Mt 23,6 ⇨Esyn: Synopse Nr. 215

^{[[#fnm4][4]]} ℘ 18,14; Mt 23,12

^{[[#fnm5][5]]} ℘ (15-24) Mt 22,1-10 ⇨Esyn: Synopse Nr. 216

^{[[#fnm6][6]]} ℘ ⇨Esyn: Synopse Nr. 217

^{[[#fnm7][7]]} ℘ (26-27) Mt 10,37-39

^{[[#fnm8][8]]} ℘ 9,23; Mt 16,24; Mk 8,34 ⇨Esyn: Synopse Nr. 160

^{[[#fnm9][9]]} ℘ (34-35) Mt 5,13; Mk 9,50 ⇨Esyn: Synopse Nr. 218

^{[[#fnm10][10]]} ℘ Mt 11,15
