:PROPERTIES:
:ID:       9cd72303-3519-441e-97e6-05012f4ed5c1
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Lukas* --
[[file:Lk_1.html][1]] ... [[file:Lk_9.html][9]] [[file:Lk_10.html][10]]
*11* [[file:Lk_12.html][12]] [[file:Lk_13.html][13]] ...
[[file:Lk_24.html][24]]

--------------

* Lk 11
  :PROPERTIES:
  :CUSTOM_ID: lk-11
  :END:

<<verses>>

<<v1>>
**** Das Gebet des Herrn: 11,1-4
     :PROPERTIES:
     :CUSTOM_ID: das-gebet-des-herrn-111-4
     :END:
1 Jesus betete einmal an einem Ort; und als er das Gebet beendet hatte,
sagte einer seiner Jünger zu ihm: Herr, lehre uns beten, wie schon
Johannes seine Jünger beten gelehrt hat. ^{[[#fn1][1]]}\\
^{[[#fn2][2]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 185\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Da sagte er zu ihnen: Wenn ihr betet, so sprecht: Vater, /\\
 dein Name werde geheiligt. /\\
 Dein Reich komme. ^{[[#fn3][3]]}\\
\\

<<v3>>
3 Gib uns täglich das Brot, das wir brauchen.\\
\\

<<v4>>
4 Und erlass uns unsere Sünden; /\\
 denn auch wir erlassen jedem, was er uns schuldig ist. /\\
 Und führe uns nicht in Versuchung.\\
\\

<<v5>>
**** Das Gleichnis vom bittenden Freund: 11,5-8
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-bittenden-freund-115-8
     :END:
5 Dann sagte er zu ihnen: Wenn einer von euch einen Freund hat und um
Mitternacht zu ihm geht und sagt: Freund, leih mir drei Brote;
^{[[#fn4][4]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 186\\
$ŽG://ESyn0812/\\
\\

<<v6>>
6 denn einer meiner Freunde, der auf Reisen ist, ist zu mir gekommen,
und ich habe ihm nichts anzubieten!,

<<v7>>
7 wird dann etwa der Mann drinnen antworten: Lass mich in Ruhe, die Tür
ist schon verschlossen und meine Kinder schlafen bei mir; ich kann nicht
aufstehen und dir etwas geben?

<<v8>>
8 Ich sage euch: Wenn er schon nicht deswegen aufsteht und ihm seine
Bitte erfüllt, weil er sein Freund ist, so wird er doch wegen seiner
Zudringlichkeit aufstehen und ihm geben, was er braucht.\\
\\

<<v9>>
**** Vom Vertrauen beim Beten: 11,9-13
     :PROPERTIES:
     :CUSTOM_ID: vom-vertrauen-beim-beten-119-13
     :END:
9 Darum sage ich euch: Bittet, dann wird euch gegeben; sucht, dann
werdet ihr finden; klopft an, dann wird euch geöffnet.
^{[[#fn5][5]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 187\\
$ŽG://ESyn0812/\\
\\

<<v10>>
10 Denn wer bittet, der empfängt; wer sucht, der findet; und wer
anklopft, dem wird geöffnet.

<<v11>>
11 Oder ist unter euch ein Vater, der seinem Sohn eine Schlange gibt,
wenn er um einen Fisch bittet,

<<v12>>
12 oder einen Skorpion, wenn er um ein Ei bittet?

<<v13>>
13 Wenn nun schon ihr, die ihr böse seid, euren Kindern gebt, was gut
ist, wie viel mehr wird der Vater im Himmel den Heiligen Geist denen
geben, die ihn bitten. ^{[[#fn6][6]]}\\
\\

<<v14>>
**** Verteidigungsrede Jesu: 11,14-23
     :PROPERTIES:
     :CUSTOM_ID: verteidigungsrede-jesu-1114-23
     :END:
14 Jesus trieb einen Dämon aus, der stumm war. Als der Dämon den Stummen
verlassen hatte, konnte der Mann reden. Alle Leute staunten.
^{[[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 188\\
$ŽG://ESyn0812/\\
\\

<<v15>>
15 Einige von ihnen aber sagten: Mit Hilfe von Beelzebul, dem Anführer
der Dämonen, treibt er die Dämonen aus. ^{[[#fn8][8]][[#fn9][9]]}

<<v16>>
16 Andere wollten ihn auf die Probe stellen und forderten von ihm ein
Zeichen vom Himmel. ^{[[#fn10][10]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 119\\
$ŽG://ESyn0812/\\
\\

<<v17>>
17 Doch er wusste, was sie dachten, und sagte zu ihnen: Jedes Reich, das
in sich gespalten ist, wird veröden und ein Haus ums andere stürzt ein.

<<v18>>
18 Wenn also der Satan mit sich selbst im Streit liegt, wie kann sein
Reich dann Bestand haben? Ihr sagt doch, dass ich die Dämonen mit Hilfe
von Beelzebul austreibe.

<<v19>>
19 Wenn ich die Dämonen durch Beelzebul austreibe, durch wen treiben
dann eure Anhänger sie aus? Sie selbst also sprechen euch das Urteil.
^{[[#fn11][11]]}

<<v20>>
20 Wenn ich aber die Dämonen durch den Finger Gottes austreibe, dann ist
doch das Reich Gottes schon zu euch gekommen. ^{[[#fn12][12]]}

<<v21>>
21 Solange ein bewaffneter starker Mann seinen Hof bewacht, ist sein
Besitz sicher; ^{[[#fn13][13]]}

<<v22>>
22 wenn ihn aber ein Stärkerer angreift und besiegt, dann nimmt ihm der
Stärkere all seine Waffen weg, auf die er sich verlassen hat, und
verteilt die Beute.

<<v23>>
23 Wer nicht für mich ist, der ist gegen mich; wer nicht mit mir
sammelt, der zerstreut.\\
\\

<<v24>>
**** Von der Rückkehr der unreinen Geister: 11,24-26
     :PROPERTIES:
     :CUSTOM_ID: von-der-rückkehr-der-unreinen-geister-1124-26
     :END:
24 Ein unreiner Geist, der einen Menschen verlassen hat, wandert durch
die Wüste und sucht einen Ort, wo er bleiben kann. Wenn er keinen
findet, sagt er: Ich will in mein Haus zurückkehren, das ich verlassen
habe. ^{[[#fn14][14]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 189\\
$ŽG://ESyn0812/\\
\\

<<v25>>
25 Und wenn er es bei seiner Rückkehr sauber und geschmückt antrifft,

<<v26>>
26 dann geht er und holt sieben andere Geister, die noch schlimmer sind
als er selbst. Sie ziehen dort ein und lassen sich nieder. So wird es
mit diesem Menschen am Ende schlimmer werden als vorher.\\
\\

<<v27>>
**** Zweierlei Seligpreisungen: 11,27-28
     :PROPERTIES:
     :CUSTOM_ID: zweierlei-seligpreisungen-1127-28
     :END:
27 Als er das sagte, rief eine Frau aus der Menge ihm zu: Selig die
Frau, deren Leib dich getragen und deren Brust dich genährt hat.
^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 190\\
$ŽG://ESyn0812/\\
\\

<<v28>>
28 Er aber erwiderte: Selig sind vielmehr die, die das Wort Gottes hören
und es befolgen. ^{[[#fn16][16]]}\\
\\

<<v29>>
**** Die Verweigerung eines Zeichens: 11,29-32
     :PROPERTIES:
     :CUSTOM_ID: die-verweigerung-eines-zeichens-1129-32
     :END:
29 Als immer mehr Menschen zu ihm kamen, sagte er: Diese Generation ist
böse. Sie fordert ein Zeichen; aber es wird ihr kein anderes gegeben
werden als das Zeichen des Jona. ^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 191\\
$ŽG://ESyn0812/\\
\\

<<v30>>
30 Denn wie Jona für die Einwohner von Ninive ein Zeichen war, so wird
es auch der Menschensohn für diese Generation sein.

<<v31>>
31 Die Königin des Südens wird beim Gericht gegen die Männer dieser
Generation auftreten und sie verurteilen; denn sie kam vom Ende der
Erde, um die Weisheit Salomos zu hören. Hier aber ist einer, der mehr
ist als Salomo. ^{[[#fn18][18]]}

<<v32>>
32 Die Männer von Ninive werden beim Gericht gegen diese Generation
auftreten und sie verurteilen; denn sie haben sich nach der Predigt des
Jona bekehrt. Hier aber ist einer, der mehr ist als Jona.
^{[[#fn19][19]]}\\
\\

<<v33>>
**** Vom Licht und vom Auge: 11,33-36
     :PROPERTIES:
     :CUSTOM_ID: vom-licht-und-vom-auge-1133-36
     :END:
33 Niemand zündet ein Licht an und stellt es in einen versteckten Winkel
oder stülpt ein Gefäß darüber, sondern man stellt es auf einen Leuchter,
damit alle, die eintreten, es leuchten sehen.
^{[[#fn20][20]][[#fn21][21]]}

<<v34>>
34 Dein Auge gibt dem Körper Licht. Wenn dein Auge gesund ist, dann wird
auch dein ganzer Körper hell sein. Wenn es aber krank ist, dann wird
dein Körper finster sein. ^{[[#fn22][22]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 193\\
$ŽG://ESyn0812/\\
\\

<<v35>>
35 Achte also darauf, dass in dir nicht Finsternis statt Licht ist.

<<v36>>
36 Wenn dein ganzer Körper von Licht erfüllt und nichts Finsteres in ihm
ist, dann wird er so hell sein, wie wenn die Lampe dich mit ihrem Schein
beleuchtet.\\
\\

<<v37>>
**** Worte gegen die Pharisäer und die Schriftgelehrten: 11,37-54
     :PROPERTIES:
     :CUSTOM_ID: worte-gegen-die-pharisäer-und-die-schriftgelehrten-1137-54
     :END:
37 Nach dieser Rede lud ein Pharisäer Jesus zum Essen ein. Jesus ging zu
ihm und setzte sich zu Tisch. ^{[[#fn23][23]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 194\\
$ŽG://ESyn0812/\\
\\

<<v38>>
38 Als der Pharisäer sah, dass er sich vor dem Essen nicht die Hände
wusch, war er verwundert. ^{[[#fn24][24]]}

<<v39>>
39 Da sagte der Herr zu ihm: O ihr Pharisäer! Ihr haltet zwar Becher und
Teller außen sauber, innen aber seid ihr voll Raubgier und Bosheit.
^{[[#fn25][25]]}

<<v40>>
40 Ihr Unverständigen! Hat nicht der, der das Äußere schuf, auch das
Innere geschaffen?

<<v41>>
41 Gebt lieber, was in den Schüsseln ist, den Armen, dann ist für euch
alles rein. ^{[[#fn26][26]]}

<<v42>>
42 Doch weh euch Pharisäern! Ihr gebt den Zehnten von Minze, Gewürzkraut
und allem Gemüse, die Gerechtigkeit aber und die Liebe zu Gott vergesst
ihr. Man muss das eine tun, ohne das andere zu unterlassen.

<<v43>>
43 Weh euch Pharisäern! Ihr wollt in den Synagogen den vordersten Sitz
haben und auf den Straßen und Plätzen von allen gegrüßt werden.
^{[[#fn27][27]]}

<<v44>>
44 Weh euch: Ihr seid wie Gräber, die man nicht mehr sieht; die Leute
gehen darüber, ohne es zu merken.

<<v45>>
45 Darauf erwiderte ihm ein Gesetzeslehrer: Meister, damit beleidigst du
auch uns.

<<v46>>
46 Er antwortete: Weh auch euch Gesetzeslehrern! Ihr ladet den Menschen
Lasten auf, die sie kaum tragen können, selbst aber rührt ihr keinen
Finger dafür.

<<v47>>
47 Weh euch! Ihr errichtet Denkmäler für die Propheten, die von euren
Vätern umgebracht wurden.

<<v48>>
48 Damit bestätigt und billigt ihr, was eure Väter getan haben. Sie
haben die Propheten umgebracht, ihr errichtet ihnen Bauten.

<<v49>>
49 Deshalb hat auch die Weisheit Gottes gesagt: Ich werde Propheten und
Apostel zu ihnen senden und sie werden einige von ihnen töten und andere
verfolgen,

<<v50>>
50 damit das Blut aller Propheten, das seit der Erschaffung der Welt
vergossen worden ist, an dieser Generation gerächt wird,

<<v51>>
51 vom Blut Abels bis zum Blut des Zacharias, der im Vorhof zwischen
Altar und Tempel umgebracht wurde. Ja, das sage ich euch: An dieser
Generation wird es gerächt werden. ^{[[#fn28][28]]}

<<v52>>
52 Weh euch Gesetzeslehrern! Ihr habt den Schlüssel (der Tür) zur
Erkenntnis weggenommen. Ihr selbst seid nicht hineingegangen und die,
die hineingehen wollten, habt ihr daran gehindert.

<<v53>>
53 Als Jesus das Haus verlassen hatte, begannen die Schriftgelehrten und
die Pharisäer, ihn mit vielerlei Fragen hartnäckig zu bedrängen;

<<v54>>
54 sie versuchten, ihm eine Falle zu stellen, damit er sich in seinen
eigenen Worten verfange.\\
\\

^{[[#fnm1][1]]} ℘ (1-4) Mt 6,9-13

^{[[#fnm2][2]]} ℘ ⇨Esyn: Synopse Nr. 185

^{[[#fnm3][3]]} Bei zahlreichen Textzeugen ist der Vaterunser-Text des
Lukas an den des Matthäus angeglichen.

^{[[#fnm4][4]]} ℘ ⇨Esyn: Synopse Nr. 186

^{[[#fnm5][5]]} ℘ Mk 11,24; Joh 14,13f; 15,7; 16,24; (9-13) Mt 7,7-11
⇨Esyn: Synopse Nr. 187

^{[[#fnm6][6]]} Andere Übersetzungsmöglichkeit (nach einigen alten
Textzeugen): wird der Vater denen, die ihn bitten, aus dem Himmel den
Heiligen Geist geben.

^{[[#fnm7][7]]} ℘ (14-15) Mt 9,32-34; (14-23) Mt 12,22-30; Mk 3,22-27
⇨Esyn: Synopse Nr. 188

^{[[#fnm8][8]]} ℘ Mt 10,25

^{[[#fnm9][9]]} Vgl. die Anmerkung zu Mt 12,24.

^{[[#fnm10][10]]} ℘ 11,29-32; Mt 16,1-4; Mk 8,11-13; Joh 6,30; 1 Kor
1,22 ⇨Esyn: Synopse Nr. 119

^{[[#fnm11][11]]} Anhänger, wörtlich: Söhne.

^{[[#fnm12][12]]} ℘ Ex 8,15; Ps 8,4; Lk 17,21

^{[[#fnm13][13]]} ℘ Jes 49,24

^{[[#fnm14][14]]} ℘ (24-26) Mt 12,43-45 ⇨Esyn: Synopse Nr. 189

^{[[#fnm15][15]]} ℘ ⇨Esyn: Synopse Nr. 190

^{[[#fnm16][16]]} ℘ 8,21

^{[[#fnm17][17]]} ℘ 11,16; Mt 16,1-4; Joh 6,30; (29-32) Mt 12,38-42; Mk
8,11f ⇨Esyn: Synopse Nr. 191

^{[[#fnm18][18]]} ℘ 1 Kön 10,1-10

^{[[#fnm19][19]]} ℘ Jona 3,5

^{[[#fnm20][20]]} ℘ 8,16; Mt 5,15; Mk 4,21

^{[[#fnm21][21]]} Vgl. die Anmerkung zu Mt 5,15.

^{[[#fnm22][22]]} ℘ (34-36) Mt 6,22f ⇨Esyn: Synopse Nr. 193

^{[[#fnm23][23]]} ℘ ⇨Esyn: Synopse Nr. 194

^{[[#fnm24][24]]} ℘ Mt 15,2; Mk 7,2; Kol 2,21f

^{[[#fnm25][25]]} ℘ (39-52) Mt 23,1-36

^{[[#fnm26][26]]} Wörtlich: Gebt lieber den Inhalt als Almosen,
dann . . .

^{[[#fnm27][27]]} ℘ 20,46; Mk 12,38f

^{[[#fnm28][28]]} ℘ Gen 4,8.10; 2 Chr 24,20-22
