:PROPERTIES:
:ID:       cf36f021-6943-4563-8b57-47e098f05098
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Lukas* --
[[file:Lk_1.html][1]] ... [[file:Lk_20.html][20]]
[[file:Lk_21.html][21]] *22* [[file:Lk_23.html][23]]
[[file:Lk_24.html][24]]

--------------

* Lk 22
  :PROPERTIES:
  :CUSTOM_ID: lk-22
  :END:

<<verses>>

<<v1>>
** Das Leiden und die Auferstehung Jesu: 22,1 - 24,53
   :PROPERTIES:
   :CUSTOM_ID: das-leiden-und-die-auferstehung-jesu-221---2453
   :END:
**** Der Beschluss des Hohen Rates: 22,1-2
     :PROPERTIES:
     :CUSTOM_ID: der-beschluss-des-hohen-rates-221-2
     :END:
1 Das Fest der Ungesäuerten Brote, das Pascha genannt wird, war nahe.
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 305\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Und die Hohenpriester und die Schriftgelehrten suchten nach einer
Möglichkeit, Jesus (unauffällig) zu beseitigen; denn sie fürchteten sich
vor dem Volk. ^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v3>>
**** Der Verrat durch Judas: 22,3-6
     :PROPERTIES:
     :CUSTOM_ID: der-verrat-durch-judas-223-6
     :END:
3 Der Satan aber ergriff Besitz von Judas, genannt Iskariot, der zu den
Zwölf gehörte. ^{[[#fn6][6]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 309\\
$ŽG://ESyn0812/\\
\\

<<v4>>
4 Judas ging zu den Hohenpriestern und den Hauptleuten und beriet mit
ihnen, wie er Jesus an sie ausliefern könnte.

<<v5>>
5 Da freuten sie sich und kamen mit ihm überein, ihm Geld dafür zu
geben.

<<v6>>
6 Er sagte zu und suchte von da an nach einer Gelegenheit, ihn an sie
auszuliefern, ohne dass das Volk es merkte.\\
\\

<<v7>>
**** Die Vorbereitung des Paschamahls: 22,7-13
     :PROPERTIES:
     :CUSTOM_ID: die-vorbereitung-des-paschamahls-227-13
     :END:
7 Dann kam der Tag der Ungesäuerten Brote, an dem das Paschalamm
geschlachtet werden musste. ^{[[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 308\\
$ŽG://ESyn0812/\\
\\

<<v8>>
8 Jesus schickte Petrus und Johannes in die Stadt und sagte: Geht und
bereitet das Paschamahl für uns vor, damit wir es gemeinsam essen
können.

<<v9>>
9 Sie fragten ihn: Wo sollen wir es vorbereiten?

<<v10>>
10 Er antwortete ihnen: Wenn ihr in die Stadt kommt, wird euch ein Mann
begegnen, der einen Wasserkrug trägt. Folgt ihm in das Haus, in das er
hineingeht,

<<v11>>
11 und sagt zu dem Herrn des Hauses: Der Meister lässt dich fragen: Wo
ist der Raum, in dem ich mit meinen Jüngern das Paschalamm essen kann?

<<v12>>
12 Und der Hausherr wird euch einen großen Raum im Obergeschoss zeigen,
der mit Polstern ausgestattet ist. Dort bereitet alles vor!

<<v13>>
13 Sie gingen und fanden alles so, wie er es ihnen gesagt hatte, und
bereiteten das Paschamahl vor.\\
\\

<<v14>>
**** Das Mahl: 22,14-23
     :PROPERTIES:
     :CUSTOM_ID: das-mahl-2214-23
     :END:
14 Als die Stunde gekommen war, begab er sich mit den Aposteln zu Tisch.
^{[[#fn8][8]]}

<<v15>>
15 Und er sagte zu ihnen: Ich habe mich sehr danach gesehnt, vor meinem
Leiden dieses Paschamahl mit euch zu essen.
^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 311\\
$ŽG://ESyn0812/\\
\\

<<v16>>
16 Denn ich sage euch: Ich werde es nicht mehr essen, bis das Mahl seine
Erfüllung findet im Reich Gottes.

<<v17>>
17 Und er nahm den Kelch, sprach das Dankgebet und sagte: Nehmt den Wein
und verteilt ihn untereinander! ^{[[#fn10][10]]}

<<v18>>
18 Denn ich sage euch: Von nun an werde ich nicht mehr von der Frucht
des Weinstocks trinken, bis das Reich Gottes kommt.

<<v19>>
19 Und er nahm Brot, sprach das Dankgebet, brach das Brot und reichte es
ihnen mit den Worten: Das ist mein Leib, der für euch hingegeben wird.
Tut dies zu meinem Gedächtnis! ^{[[#fn11][11]][[#fn12][12]]}

<<v20>>
20 Ebenso nahm er nach dem Mahl den Kelch und sagte: Dieser Kelch ist
/der Neue Bund/ in meinem Blut, das für euch vergossen wird.
^{[[#fn13][13]]}

<<v21>>
21 Doch seht, der Mann, der mich verrät und ausliefert, sitzt mit mir am
Tisch. ^{[[#fn14][14]][[#fn15][15]][[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 312\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 Der Menschensohn muss zwar den Weg gehen, der ihm bestimmt ist. Aber
weh dem Menschen, durch den er verraten wird.

<<v23>>
23 Da fragte einer den andern, wer von ihnen das wohl sei, der so etwas
tun werde.\\
\\

<<v24>>
**** Vom Herrschen und vom Dienen: 22,24-30
     :PROPERTIES:
     :CUSTOM_ID: vom-herrschen-und-vom-dienen-2224-30
     :END:
24 Es entstand unter ihnen ein Streit darüber, wer von ihnen wohl der
Größte sei. ^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 313\\
$ŽG://ESyn0812/\\
\\

<<v25>>
25 Da sagte Jesus: Die Könige herrschen über ihre Völker und die
Mächtigen lassen sich Wohltäter nennen.

<<v26>>
26 Bei euch aber soll es nicht so sein, sondern der Größte unter euch
soll werden wie der Kleinste und der Führende soll werden wie der
Dienende. ^{[[#fn18][18]]}

<<v27>>
27 Welcher von beiden ist größer: wer bei Tisch sitzt oder wer bedient?
Natürlich der, der bei Tisch sitzt. Ich aber bin unter euch wie der, der
bedient.

<<v28>>
28 In allen meinen Prüfungen habt ihr bei mir ausgeharrt.

<<v29>>
29 Darum vermache ich euch das Reich, wie es mein Vater mir vermacht
hat:

<<v30>>
30 Ihr sollt in meinem Reich mit mir an meinem Tisch essen und trinken,
und ihr sollt auf Thronen sitzen und die zwölf Stämme Israels richten.
^{[[#fn19][19]]}\\
\\

<<v31>>
**** Die Ankündigung der Verleugnung und der Umkehr des Petrus: 22,31-34
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-der-verleugnung-und-der-umkehr-des-petrus-2231-34
     :END:
31 Simon, Simon, der Satan hat verlangt, dass er euch wie Weizen sieben
darf. ^{[[#fn20][20]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 367\\
$ŽG://ESyn0812/\\
\\

<<v32>>
32 Ich aber habe für dich gebetet, dass dein Glaube nicht erlischt. Und
wenn du dich wieder bekehrt hast, dann stärke deine Brüder.

<<v33>>
33 Darauf sagte Petrus zu ihm: Herr, ich bin bereit, mit dir sogar ins
Gefängnis und in den Tod zu gehen. ^{[[#fn21][21]]}

<<v34>>
34 Jesus erwiderte: Ich sage dir, Petrus, ehe heute der Hahn kräht,
wirst du dreimal leugnen, mich zu kennen. ^{[[#fn22][22]]}\\
\\

<<v35>>
**** Die Stunde der Entscheidung: 22,35-38
     :PROPERTIES:
     :CUSTOM_ID: die-stunde-der-entscheidung-2235-38
     :END:
35 Dann sagte Jesus zu ihnen: Als ich euch ohne Geldbeutel aussandte,
ohne Vorratstasche und ohne Schuhe, habt ihr da etwa Not gelitten? Sie
antworteten: Nein. ^{[[#fn23][23]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 316\\
$ŽG://ESyn0812/\\
\\

<<v36>>
36 Da sagte er: Jetzt aber soll der, der einen Geldbeutel hat, ihn
mitnehmen und ebenso die Tasche. Wer aber kein Geld hat, soll seinen
Mantel verkaufen und sich dafür ein Schwert kaufen.

<<v37>>
37 Ich sage euch: An mir muss sich das Schriftwort erfüllen: /Er wurde
zu den Verbrechern gerechnet./ Denn alles, was über mich gesagt ist,
geht in Erfüllung. ^{[[#fn24][24]]}

<<v38>>
38 Da sagten sie: Herr, hier sind zwei Schwerter. Er erwiderte: Genug
davon!\\
\\

<<v39>>
**** Das Gebet am Ölberg: 22,39-46
     :PROPERTIES:
     :CUSTOM_ID: das-gebet-am-ölberg-2239-46
     :END:
39 Dann verließ Jesus die Stadt und ging, wie er es gewohnt war, zum
Ölberg; seine Jünger folgten ihm. ^{[[#fn25][25]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 330\\
$ŽG://ESyn0812/\\
\\

<<v40>>
40 Als er dort war, sagte er zu ihnen: Betet darum, dass ihr nicht in
Versuchung geratet!

<<v41>>
41 Dann entfernte er sich von ihnen ungefähr einen Steinwurf weit,
kniete nieder und betete: ^{[[#fn26][26]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 302\\
$ŽG://ESyn0812/\\
\\

<<v42>>
42 Vater, wenn du willst, nimm diesen Kelch von mir! Aber nicht mein,
sondern dein Wille soll geschehen. ^{[[#fn27][27]]}

<<v43>>
43 Da erschien ihm ein Engel vom Himmel und gab ihm (neue) Kraft.
^{[[#fn28][28]]}

<<v44>>
44 Und er betete in seiner Angst noch inständiger und sein Schweiß war
wie Blut, das auf die Erde tropfte.

<<v45>>
45 Nach dem Gebet stand er auf, ging zu den Jüngern zurück und fand sie
schlafend; denn sie waren vor Kummer erschöpft.

<<v46>>
46 Da sagte er zu ihnen: Wie könnt ihr schlafen? Steht auf und betet,
damit ihr nicht in Versuchung geratet.\\
\\

<<v47>>
**** Die Gefangennahme: 22,47-53
     :PROPERTIES:
     :CUSTOM_ID: die-gefangennahme-2247-53
     :END:
47 Während er noch redete, kam eine Schar Männer; Judas, einer der
Zwölf, ging ihnen voran. Er näherte sich Jesus, um ihn zu küssen.
^{[[#fn29][29]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 331\\
$ŽG://ESyn0812/\\
\\

<<v48>>
48 Jesus aber sagte zu ihm: Judas, mit einem Kuss verrätst du den
Menschensohn?

<<v49>>
49 Als seine Begleiter merkten, was (ihm) drohte, fragten sie: Herr,
sollen wir mit dem Schwert dreinschlagen?

<<v50>>
50 Und einer von ihnen schlug auf den Diener des Hohenpriesters ein und
hieb ihm das rechte Ohr ab.

<<v51>>
51 Jesus aber sagte: Hört auf damit! Und er berührte das Ohr und heilte
den Mann.

<<v52>>
52 Zu den Hohenpriestern aber, den Hauptleuten der Tempelwache und den
Ältesten, die vor ihm standen, sagte Jesus: Wie gegen einen Räuber seid
ihr mit Schwertern und Knüppeln ausgezogen.

<<v53>>
53 Tag für Tag war ich bei euch im Tempel und ihr habt nicht gewagt,
gegen mich vorzugehen. Aber das ist eure Stunde, jetzt hat die
Finsternis die Macht. ^{[[#fn30][30]]}\\
^{[[#fn31][31]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 332\\
$ŽG://ESyn0812/

<<v54>>
**** Die Verleugnung durch Petrus: 22,54-62
     :PROPERTIES:
     :CUSTOM_ID: die-verleugnung-durch-petrus-2254-62
     :END:
54 Darauf nahmen sie ihn fest, führten ihn ab und brachten ihn in das
Haus des Hohenpriesters. Petrus folgte von weitem. ^{[[#fn32][32]]}

<<v55>>
55 Mitten im Hof hatte man ein Feuer angezündet und Petrus setzte sich
zu den Leuten, die dort beieinandersaßen.

<<v56>>
56 Eine Magd sah ihn am Feuer sitzen, schaute ihn genau an und sagte:
Der war auch mit ihm zusammen.

<<v57>>
57 Petrus aber leugnete es und sagte: Frau, ich kenne ihn nicht.

<<v58>>
58 Kurz danach sah ihn ein anderer und bemerkte: Du gehörst auch zu
ihnen. Petrus aber sagte: Nein, Mensch, ich nicht!

<<v59>>
59 Etwa eine Stunde später behauptete wieder einer: Wahrhaftig, der war
auch mit ihm zusammen; er ist doch auch ein Galiläer.

<<v60>>
60 Petrus aber erwiderte: Mensch, ich weiß nicht, wovon du sprichst. Im
gleichen Augenblick, noch während er redete, krähte ein Hahn.

<<v61>>
61 Da wandte sich der Herr um und blickte Petrus an. Und Petrus
erinnerte sich an das, was der Herr zu ihm gesagt hatte: Ehe heute der
Hahn kräht, wirst du mich dreimal verleugnen. ^{[[#fn33][33]]}

<<v62>>
62 Und er ging hinaus und weinte bitterlich.\\
\\

<<v63>>
**** Die Verspottung durch die Wächter: 22,63-65
     :PROPERTIES:
     :CUSTOM_ID: die-verspottung-durch-die-wächter-2263-65
     :END:
63 Die Wächter trieben ihren Spott mit Jesus. Sie schlugen ihn,
^{[[#fn34][34]]}

<<v64>>
64 verhüllten ihm das Gesicht und fragten ihn: Du bist doch ein Prophet!
Sag uns: Wer hat dich geschlagen?

<<v65>>
65 Und noch mit vielen anderen Lästerungen verhöhnten sie ihn.\\
\\

<<v66>>
**** Das Verhör vor dem Hohen Rat: 22,66-71
     :PROPERTIES:
     :CUSTOM_ID: das-verhör-vor-dem-hohen-rat-2266-71
     :END:
66 Als es Tag wurde, versammelten sich die Ältesten des Volkes, die
Hohenpriester und die Schriftgelehrten, also der Hohe Rat, und sie
ließen Jesus vorführen. ^{[[#fn35][35]]}

<<v67>>
67 Sie sagten zu ihm: Wenn du der Messias bist, dann sag es uns! Er
antwortete ihnen: Auch wenn ich es euch sage - ihr glaubt mir ja doch
nicht; ^{[[#fn36][36]]}

<<v68>>
68 und wenn ich euch etwas frage, antwortet ihr nicht.

<<v69>>
69 Von nun an wird /der Menschensohn zur Rechten/ des allmächtigen
/Gottes sitzen./ ^{[[#fn37][37]]}

<<v70>>
70 Da sagten alle: Du bist also der Sohn Gottes. Er antwortete ihnen:
Ihr sagt es - ich bin es.

<<v71>>
71 Da riefen sie: Was brauchen wir noch Zeugenaussagen? Wir haben es
selbst aus seinem eigenen Mund gehört.\\
\\

^{[[#fnm1][1]]} ℘ (1-2) Mt 26,3-5; Mk 14,1f

^{[[#fnm2][2]]} Vgl. die Anmerkung zu Mk 14,1. 1-24,53: Der
Passionsbericht des Lukas bietet über die Berichte des Markus und des
Matthäus hinaus folgende Sonderüberlieferungen: Rangstreit unter den
Jüngern (22,24-30), Verheißung an die Jünger (22,28-30), Mahnung an
Simon (22,31f), Hinweis auf eine Engelserscheinung am Ölberg und auf den
Blutschweiß (22,43f), Blick Jesu auf Petrus (22,61), Verspottung Jesu
durch Herodes (23, 6-12), Feststellen der Schuldlosigkeit Jesu durch
Pilatus (23, 13-16), Wort Jesu an die Frauen von Jerusalem (23,27-31),
Wort Jesu an den reumütigen Verbrecher (23,40-43), Sterbegebet Jesu
(23,46).

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 305

^{[[#fnm4][4]]} ℘ 19,47f; 20,19

^{[[#fnm5][5]]} Andere Übersetzungsmöglichkeit: denn sie fürchteten, das
Volk (werde einen Aufstand machen).

^{[[#fnm6][6]]} ℘ (3-6) Mt 26,14-16; Mk 14,10f ⇨Esyn: Synopse Nr. 309

^{[[#fnm7][7]]} ℘ Ex 12,14-20; (7-13) Mt 26,17-19; Mk 14,12-16 ⇨Esyn:
Synopse Nr. 308

^{[[#fnm8][8]]} ℘ (14-23) Mt 26,20-29; Mk 14,17-25

^{[[#fnm9][9]]} ℘ ⇨Esyn: Synopse Nr. 311

^{[[#fnm10][10]]} Nehmt den Wein, wörtlich: Nehmt diesen (Kelch). - Beim
jüdischen Paschamahl wird der Kelch mehrmals herumgereicht. Von dem bei
der Einsetzung des Abendmahls gereichten Kelch ist erst in V. 20 die
Rede.

^{[[#fnm11][11]]} ℘ (19-20) 1 Kor 11,23-25

^{[[#fnm12][12]]} 19f: Der Abendmahlsbericht des Lukas spricht im
Unterschied zu Markus und Matthäus ausdrücklich vom Neuen Bund, wie dies
auch Paulus in 1 Kor 11,25 tut.

^{[[#fnm13][13]]} ℘ Ex 24,8; Jer 31,31

^{[[#fnm14][14]]} ℘ (21-23) Joh 13,2.21-26

^{[[#fnm15][15]]} Wörtlich: Doch siehe, die Hand dessen, der mich verrät
und ausliefert, (ist) mit mir auf dem Tisch.

^{[[#fnm16][16]]} ℘ ⇨Esyn: Synopse Nr. 312

^{[[#fnm17][17]]} ℘ (24-26) 9,46-48; Mt 18,1; Mk 9,33f; (24-27) Mt
20,24-28; Mk 10,41-45 ⇨Esyn: Synopse Nr. 313

^{[[#fnm18][18]]} ℘ (26f) Joh 13,4f.12-17

^{[[#fnm19][19]]} ℘ Mt 19,28

^{[[#fnm20][20]]} ℘ Mt 16,18; Joh 21,15-17; (31-34) Joh 13,36-38 ⇨Esyn:
Synopse Nr. 367

^{[[#fnm21][21]]} ℘ (33-34) Mt 26,34f; Mk 14,30f

^{[[#fnm22][22]]} ℘ 22,61

^{[[#fnm23][23]]} ℘ 9,2f; 10,4 ⇨Esyn: Synopse Nr. 316

^{[[#fnm24][24]]} ℘ Jes 53,12; Joh 19,28

^{[[#fnm25][25]]} ℘ 21,37; Joh 18,1f; (39-46) Mt 26,30.36-46; Mk
14,26.32-42 ⇨Esyn: Synopse Nr. 330

^{[[#fnm26][26]]} ℘ ⇨Esyn: Synopse Nr. 302

^{[[#fnm27][27]]} ℘ Mt 6,10; Joh 12,27f

^{[[#fnm28][28]]} 43f: Diese zwei Verse fehlen bei wichtigen Textzeugen;
sie sind vermutlich nicht ursprünglich.

^{[[#fnm29][29]]} ℘ (47-53) Mt 26,47-56; Mk 14,43-50; Joh 18,3-11 ⇨Esyn:
Synopse Nr. 331

^{[[#fnm30][30]]} ℘ 19,47; 21,37; Joh 18,20

^{[[#fnm31][31]]} ℘ ⇨Esyn: Synopse Nr. 332

^{[[#fnm32][32]]} ℘ (54-62) Mt 26,57f.69-75; Mk 14,53f.66-72; Joh
18,12-18.25-27

^{[[#fnm33][33]]} ℘ 22,34

^{[[#fnm34][34]]} ℘ (63-65) Mt 26,67; Mk 14,65

^{[[#fnm35][35]]} ℘ (66-71) Mt 27,1; 26,57.63-65; Mk 15,1; 14,53.61-64;
Joh 18,19-24

^{[[#fnm36][36]]} ℘ 9,20; Joh 10,24

^{[[#fnm37][37]]} ℘ Dan 7,13; Ps 110,1
