:PROPERTIES:
:ID:       641fb7ad-262e-45b2-b271-e032f741f887
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Lukas* --
[[file:Lk_1.html][1]] ... [[file:Lk_22.html][22]]
[[file:Lk_23.html][23]] *24*

--------------

* Lk 24
  :PROPERTIES:
  :CUSTOM_ID: lk-24
  :END:

<<verses>>

<<v1>>
**** Die Botschaft der Engel im leeren Grab: 24,1-12
     :PROPERTIES:
     :CUSTOM_ID: die-botschaft-der-engel-im-leeren-grab-241-12
     :END:
1 Am ersten Tag der Woche gingen die Frauen mit den wohlriechenden
Salben, die sie zubereitet hatten, in aller Frühe zum Grab.
^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 352\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Da sahen sie, dass der Stein vom Grab weggewälzt war;

<<v3>>
3 sie gingen hinein, aber den Leichnam Jesu, des Herrn, fanden sie
nicht.

<<v4>>
4 Während sie ratlos dastanden, traten zwei Männer in leuchtenden
Gewändern zu ihnen.

<<v5>>
5 Die Frauen erschraken und blickten zu Boden. Die Männer aber sagten zu
ihnen: Was sucht ihr den Lebenden bei den Toten?

<<v6>>
6 Er ist nicht hier, sondern er ist auferstanden. Erinnert euch an das,
was er euch gesagt hat, als er noch in Galiläa war: ^{[[#fn2][2]]}

<<v7>>
7 Der Menschensohn muss den Sündern ausgeliefert und gekreuzigt werden
und am dritten Tag auferstehen. ^{[[#fn3][3]]}

<<v8>>
8 Da erinnerten sie sich an seine Worte.

<<v9>>
9 Und sie kehrten vom Grab in die Stadt zurück und berichteten alles den
Elf und den anderen Jüngern.

<<v10>>
10 Es waren Maria Magdalene, Johanna und Maria, die Mutter des Jakobus;
auch die übrigen Frauen, die bei ihnen waren, erzählten es den Aposteln.
^{[[#fn4][4]][[#fn5][5]]}

<<v11>>
11 Doch die Apostel hielten das alles für Geschwätz und glaubten ihnen
nicht.

<<v12>>
12 Petrus aber stand auf und lief zum Grab. Er beugte sich vor, sah aber
nur die Leinenbinden (dort liegen). Dann ging er nach Hause, voll
Verwunderung über das, was geschehen war. ^{[[#fn6][6]]}\\
\\

<<v13>>
**** Die Begegnung mit dem Auferstandenen auf dem Weg nach Emmaus:
24,13-35
     :PROPERTIES:
     :CUSTOM_ID: die-begegnung-mit-dem-auferstandenen-auf-dem-weg-nach-emmaus-2413-35
     :END:
13 Am gleichen Tag waren zwei von den Jüngern auf dem Weg in ein Dorf
namens Emmaus, das sechzig Stadien von Jerusalem entfernt ist.
^{[[#fn7][7]][[#fn8][8]][[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 355\\
$ŽG://ESyn0812/\\
\\

<<v14>>
14 Sie sprachen miteinander über all das, was sich ereignet hatte.

<<v15>>
15 Während sie redeten und ihre Gedanken austauschten, kam Jesus hinzu
und ging mit ihnen.

<<v16>>
16 Doch sie waren wie mit Blindheit geschlagen, sodass sie ihn nicht
erkannten.

<<v17>>
17 Er fragte sie: Was sind das für Dinge, über die ihr auf eurem Weg
miteinander redet? Da blieben sie traurig stehen,

<<v18>>
18 und der eine von ihnen - er hieß Kleopas - antwortete ihm: Bist du so
fremd in Jerusalem, dass du als einziger nicht weißt, was in diesen
Tagen dort geschehen ist?

<<v19>>
19 Er fragte sie: Was denn? Sie antworteten ihm: Das mit Jesus aus
Nazaret. Er war ein Prophet, mächtig in Wort und Tat vor Gott und dem
ganzen Volk.

<<v20>>
20 Doch unsere Hohenpriester und Führer haben ihn zum Tod verurteilen
und ans Kreuz schlagen lassen.

<<v21>>
21 Wir aber hatten gehofft, dass er der sei, der Israel erlösen werde.
Und dazu ist heute schon der dritte Tag, seitdem das alles geschehen
ist.

<<v22>>
22 Aber nicht nur das: Auch einige Frauen aus unserem Kreis haben uns in
große Aufregung versetzt. Sie waren in der Frühe beim Grab,

<<v23>>
23 fanden aber seinen Leichnam nicht. Als sie zurückkamen, erzählten
sie, es seien ihnen Engel erschienen und hätten gesagt, er lebe.

<<v24>>
24 Einige von uns gingen dann zum Grab und fanden alles so, wie die
Frauen gesagt hatten; ihn selbst aber sahen sie nicht. ^{[[#fn10][10]]}

<<v25>>
25 Da sagte er zu ihnen: Begreift ihr denn nicht? Wie schwer fällt es
euch, alles zu glauben, was die Propheten gesagt haben.

<<v26>>
26 Musste nicht der Messias all das erleiden, um so in seine
Herrlichkeit zu gelangen?

<<v27>>
27 Und er legte ihnen dar, ausgehend von Mose und allen Propheten, was
in der gesamten Schrift über ihn geschrieben steht.

<<v28>>
28 So erreichten sie das Dorf, zu dem sie unterwegs waren. Jesus tat,
als wolle er weitergehen,

<<v29>>
29 aber sie drängten ihn und sagten: Bleib doch bei uns; denn es wird
bald Abend, der Tag hat sich schon geneigt. Da ging er mit hinein, um
bei ihnen zu bleiben.

<<v30>>
30 Und als er mit ihnen bei Tisch war, nahm er das Brot, sprach den
Lobpreis, brach das Brot und gab es ihnen.

<<v31>>
31 Da gingen ihnen die Augen auf und sie erkannten ihn; dann sahen sie
ihn nicht mehr.

<<v32>>
32 Und sie sagten zueinander: Brannte uns nicht das Herz in der Brust,
als er unterwegs mit uns redete und uns den Sinn der Schrift erschloss?

<<v33>>
33 Noch in derselben Stunde brachen sie auf und kehrten nach Jerusalem
zurück und sie fanden die Elf und die anderen Jünger versammelt.

<<v34>>
34 Diese sagten: Der Herr ist wirklich auferstanden und ist dem Simon
erschienen. ^{[[#fn11][11]]}

<<v35>>
35 Da erzählten auch sie, was sie unterwegs erlebt und wie sie ihn
erkannt hatten, als er das Brot brach. ^{[[#fn12][12]]}\\
\\

<<v36>>
**** Die Erscheinung des Auferstandenen in Jerusalem: 24,36-53
     :PROPERTIES:
     :CUSTOM_ID: die-erscheinung-des-auferstandenen-in-jerusalem-2436-53
     :END:
36 Während sie noch darüber redeten, trat er selbst in ihre Mitte und
sagte zu ihnen: Friede sei mit euch!
^{[[#fn13][13]][[#fn14][14]][[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 356\\
$ŽG://ESyn0812/\\
\\

<<v37>>
37 Sie erschraken und hatten große Angst, denn sie meinten, einen Geist
zu sehen. ^{[[#fn16][16]]}

<<v38>>
38 Da sagte er zu ihnen: Was seid ihr so bestürzt? Warum lasst ihr in
eurem Herzen solche Zweifel aufkommen?

<<v39>>
39 Seht meine Hände und meine Füße an: Ich bin es selbst. Fasst mich
doch an und begreift: Kein Geist hat Fleisch und Knochen, wie ihr es bei
mir seht.

<<v40>>
40 Bei diesen Worten zeigte er ihnen seine Hände und Füße.
^{[[#fn17][17]]}

<<v41>>
41 Sie staunten, konnten es aber vor Freude immer noch nicht glauben. Da
sagte er zu ihnen: Habt ihr etwas zu essen hier? ^{[[#fn18][18]]}

<<v42>>
42 Sie gaben ihm ein Stück gebratenen Fisch; ^{[[#fn19][19]]}

<<v43>>
43 er nahm es und aß es vor ihren Augen.

<<v44>>
44 Dann sprach er zu ihnen: Das sind die Worte, die ich zu euch gesagt
habe, als ich noch bei euch war: Alles muss in Erfüllung gehen, was im
Gesetz des Mose, bei den Propheten und in den Psalmen über mich gesagt
ist. ^{[[#fn20][20]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 365\\
$ŽG://ESyn0812/\\
\\

<<v45>>
45 Darauf öffnete er ihnen die Augen für das Verständnis der Schrift.
^{[[#fn21][21]]}

<<v46>>
46 Er sagte zu ihnen: So steht es in der Schrift: Der Messias wird
leiden und am dritten Tag von den Toten auferstehen,

<<v47>>
47 und in seinem Namen wird man allen Völkern, angefangen in Jerusalem,
verkünden, sie sollen umkehren, damit ihre Sünden vergeben werden.

<<v48>>
48 Ihr seid Zeugen dafür. ^{[[#fn22][22]]}

<<v49>>
49 Und ich werde die Gabe, die mein Vater verheißen hat, zu euch
herabsenden. Bleibt in der Stadt, bis ihr mit der Kraft aus der Höhe
erfüllt werdet.

<<v50>>
50 Dann führte er sie hinaus in die Nähe von Betanien. Dort erhob er
seine Hände und segnete sie. ^{[[#fn23][23]]}

<<v51>>
51 Und während er sie segnete, verließ er sie und wurde zum Himmel
emporgehoben; ^{[[#fn24][24]][[#fn25][25]]}

<<v52>>
52 sie aber fielen vor ihm nieder. Dann kehrten sie in großer Freude
nach Jerusalem zurück.

<<v53>>
53 Und sie waren immer im Tempel und priesen Gott.\\
\\

^{[[#fnm1][1]]} ℘ (1-12) Mt 28,1-8; Mk 16,1-8; Joh 20,1-13 ⇨Esyn:
Synopse Nr. 352

^{[[#fnm2][2]]} Der erste Satz des Verses fehlt bei einigen alten
Textzeugen.

^{[[#fnm3][3]]} ℘ 9,22.44; 17,25; 18,32f

^{[[#fnm4][4]]} ℘ 8,2f; Mk 16,9

^{[[#fnm5][5]]} Vgl. die Anmerkung zu Mt 12,46f.

^{[[#fnm6][6]]} Dieser Vers fehlt bei einigen alten Textzeugen.

^{[[#fnm7][7]]} ℘ Mk 16,12

^{[[#fnm8][8]]} Sechzig Stadien sind etwa elf Kilometer. 13-35: Die
Erzählung von den Emmaus-Jüngern ist nur bei Lukas überliefert.

^{[[#fnm9][9]]} ℘ ⇨Esyn: Synopse Nr. 355

^{[[#fnm10][10]]} ℘ Joh 20,3-10

^{[[#fnm11][11]]} ℘ 1 Kor 15,4f

^{[[#fnm12][12]]} Andere Übersetzungsmöglichkeit: wie sie ihn daran
erkannten, wie er das Brot brach.

^{[[#fnm13][13]]} ℘ 1 Kor 15,5; (36-53) Mk 16,14-19; Joh 20,19-23

^{[[#fnm14][14]]} Die Worte «und sagte zu ihnen: Friede sei mit euch!»
fehlen bei einigen alten Textzeugen.

^{[[#fnm15][15]]} ℘ ⇨Esyn: Synopse Nr. 356

^{[[#fnm16][16]]} ℘ Mt 14,26

^{[[#fnm17][17]]} Dieser Vers fehlt bei einigen alten Textzeugen.

^{[[#fnm18][18]]} ℘ Joh 21,5.10

^{[[#fnm19][19]]} ℘ Apg 10,41

^{[[#fnm20][20]]} ℘ Mt 16,21; Joh 5,39.46 ⇨Esyn: Synopse Nr. 365

^{[[#fnm21][21]]} ℘ Joh 20,9

^{[[#fnm22][22]]} ℘ Apg 1,8

^{[[#fnm23][23]]} 50-52: Nach den Angaben des Lukas in Apg 1,3 erfolgte
die Himmelfahrt Jesu vierzig Tage nach seiner Auferstehung.

^{[[#fnm24][24]]} ℘ Apg 1,9f

^{[[#fnm25][25]]} 51f: Die Worte «und wurde zum Himmel emporgehoben, sie
aber fielen vor ihm nieder» fehlen bei einigen alten Textzeugen.
