:PROPERTIES:
:ID:       03539863-7190-4ff1-b1bc-aad54ca9957f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Lukas* --
[[file:Lk_1.html][1]] [[file:Lk_2.html][2]] *3* [[file:Lk_4.html][4]]
[[file:Lk_5.html][5]] ... [[file:Lk_24.html][24]]

--------------

* Lk 3
  :PROPERTIES:
  :CUSTOM_ID: lk-3
  :END:

<<verses>>

<<v1>>
** Die Vorbereitung des Wirkens Jesu: 3,1 - 4,13
   :PROPERTIES:
   :CUSTOM_ID: die-vorbereitung-des-wirkens-jesu-31---413
   :END:
**** Johannes der Täufer: 3,1-20
     :PROPERTIES:
     :CUSTOM_ID: johannes-der-täufer-31-20
     :END:
1 Es war im fünfzehnten Jahr der Regierung des Kaisers Tiberius; Pontius
Pilatus war Statthalter von Judäa, Herodes Tetrarch von Galiläa, sein
Bruder Philippus Tetrarch von Ituräa und Trachonitis, Lysanias Tetrarch
von Abilene; ^{[[#fn1][1]][[#fn2][2]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 13\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Hohepriester waren Hannas und Kajaphas. Da erging in der Wüste das
Wort Gottes an Johannes, den Sohn des Zacharias.
^{[[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 32\\
$ŽG://ESyn0812/\\
\\

<<v3>>
3 Und er zog in die Gegend am Jordan und verkündigte dort überall Umkehr
und Taufe zur Vergebung der Sünden. ^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v4>>
4 (So erfüllte sich,) was im Buch der Reden des Propheten Jesaja steht:
/Eine Stimme ruft in der Wüste:/ /\\
 /Bereitet dem Herrn den Weg!/ /\\
 /Ebnet/ ihm /die Straßen!/ ^{[[#fn6][6]]}\\
\\

<<v5>>
5 /Jede Schlucht soll aufgefüllt werden,/ /\\
 /jeder Berg und Hügel sich senken. Was krumm ist, soll gerade werden,/
/\\
 /was uneben ist, soll zum ebenen Weg werden./\\
\\

<<v6>>
6 /Und alle Menschen werden das Heil sehen, das von Gott kommt./

<<v7>>
7 Das Volk zog in Scharen zu ihm hinaus, um sich von ihm taufen zu
lassen. Er sagte zu ihnen: Ihr Schlangenbrut, wer hat euch denn gelehrt,
dass ihr dem kommenden Gericht entrinnen könnt?
^{[[#fn7][7]][[#fn8][8]][[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 14\\
$ŽG://ESyn0812/\\
\\

<<v8>>
8 Bringt Früchte hervor, die eure Umkehr zeigen, und fangt nicht an zu
sagen: Wir haben ja Abraham zum Vater. Denn ich sage euch: Gott kann aus
diesen Steinen Kinder Abrahams machen.

<<v9>>
9 Schon ist die Axt an die Wurzel der Bäume gelegt; jeder Baum, der
keine gute Frucht hervorbringt, wird umgehauen und ins Feuer geworfen.
^{[[#fn10][10]]}

<<v10>>
10 Da fragten ihn die Leute: Was sollen wir also tun?
^{[[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 15\\
$ŽG://ESyn0812/\\
\\

<<v11>>
11 Er antwortete ihnen: Wer zwei Gewänder hat, der gebe eines davon dem,
der keines hat, und wer zu essen hat, der handle ebenso.

<<v12>>
12 Es kamen auch Zöllner zu ihm, um sich taufen zu lassen, und fragten:
Meister, was sollen wir tun?

<<v13>>
13 Er sagte zu ihnen: Verlangt nicht mehr, als festgesetzt ist.

<<v14>>
14 Auch Soldaten fragten ihn: Was sollen denn wir tun? Und er sagte zu
ihnen: Misshandelt niemand, erpresst niemand, begnügt euch mit eurem
Sold!

<<v15>>
15 Das Volk war voll Erwartung und alle überlegten im Stillen, ob
Johannes nicht vielleicht selbst der Messias sei.
^{[[#fn12][12]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 16\\
$ŽG://ESyn0812/\\
\\

<<v16>>
16 Doch Johannes gab ihnen allen zur Antwort: Ich taufe euch nur mit
Wasser. Es kommt aber einer, der stärker ist als ich, und ich bin es
nicht wert, ihm die Schuhe aufzuschnüren. Er wird euch mit dem Heiligen
Geist und mit Feuer taufen. ^{[[#fn13][13]]}

<<v17>>
17 Schon hält er die Schaufel in der Hand, um die Spreu vom Weizen zu
trennen und den Weizen in seine Scheune zu bringen; die Spreu aber wird
er in nie erlöschendem Feuer verbrennen.

<<v18>>
18 Mit diesen und vielen anderen Worten ermahnte er das Volk in seiner
Predigt.

<<v19>>
19 Johannes tadelte auch den Tetrarchen Herodes wegen (der Sache mit)
Herodias, der Frau seines Bruders, und wegen all der anderen
Schandtaten, die er verübt hatte.
^{[[#fn14][14]][[#fn15][15]][[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 17\\
$ŽG://ESyn0812/\\
\\

<<v20>>
20 Deshalb ließ Herodes Johannes ins Gefängnis werfen und lud so noch
mehr Schuld auf sich.\\
\\

<<v21>>
**** Die Taufe Jesu: 3,21-22
     :PROPERTIES:
     :CUSTOM_ID: die-taufe-jesu-321-22
     :END:
21 Zusammen mit dem ganzen Volk ließ auch Jesus sich taufen. Und während
er betete, öffnete sich der Himmel, ^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 18\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 und der Heilige Geist kam sichtbar in Gestalt einer Taube auf ihn
herab, und eine Stimme aus dem Himmel sprach: /Du bist mein geliebter
Sohn, an dir habe ich Gefallen gefunden./ ^{[[#fn18][18]]}\\
^{[[#fn19][19]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 302\\
$ŽG://ESyn0812/

<<v23>>
**** Die Vorfahren Jesu: 3,23-38
     :PROPERTIES:
     :CUSTOM_ID: die-vorfahren-jesu-323-38
     :END:
23 Jesus war etwa dreißig Jahre alt, als er zum ersten Mal öffentlich
auftrat. Man hielt ihn für den Sohn Josefs. Die Vorfahren Josefs waren:
Eli, ^{[[#fn20][20]][[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 19\\
$ŽG://ESyn0812/\\
\\

<<v24>>
24 Mattat, Levi, Melchi, Jannai, Josef,

<<v25>>
25 Mattitja, Amos, Nahum, Hesli, Naggai,

<<v26>>
26 Mahat, Mattitja, Schimi, Josech, Joda,

<<v27>>
27 Johanan, Resa, Serubbabel, Schealtiël, Neri,

<<v28>>
28 Melchi, Addi, Kosam, Elmadam, Er,

<<v29>>
29 Joschua, Eliëser, Jorim, Mattat, Levi,

<<v30>>
30 Simeon, Juda, Josef, Jonam, Eljakim,

<<v31>>
31 Melea, Menna, Mattata, Natan, David, ^{[[#fn22][22]]}

<<v32>>
32 Isai, Obed, Boas, Salmon, Nachschon,

<<v33>>
33 Amminadab, Admin, Arni, Hezron, Perez, Juda,

<<v34>>
34 Jakob, Isaak, Abraham, Terach, Nahor, ^{[[#fn23][23]]}

<<v35>>
35 Serug, Regu, Peleg, Eber, Schelach,

<<v36>>
36 Kenan, Arpachschad, Sem, Noach, Lamech, ^{[[#fn24][24]]}

<<v37>>
37 Metuschelach, Henoch, Jered, Mahalalel, Kenan,

<<v38>>
38 Enosch, Set, Adam; (der stammte von) Gott.\\
\\

^{[[#fnm1][1]]} 1f: Durch die Verknüpfung der Geschichte Jesu mit der
Weltgeschichte weist Lukas auf die umfassende Bedeutung Jesu hin.
Tiberius war Kaiser von 14 bis 37 n. Chr.; Pontius Pilatus Statthalter
(Präfekt) über die römische Provinz Judäa von 26 bis 36 n. Chr.; Herodes
Antipas Tetrarch von Galiläa und Peräa von 4 v. Chr. bis 39 n. Chr.
(vgl. die Anmerkung zu Mt 14,1), sein Halbbruder Philippus Tetrarch der
vorwiegend heidnischen Gebiete Nordtransjordaniens von 4 v. Chr. bis 34
n. Chr. Die Regierungszeit des Lysanias ist nicht genau festzustellen.
Hannas war Hoherpriester von 6 bis 15 n. Chr. und blieb auch danach sehr
einflussreich. Seine fünf Söhne und sein Schwiegersohn Kajaphas kamen
nacheinander in den Besitz der Hohenpriesterwürde. Kajaphas amtierte von
18 bis 37 n. Chr.

^{[[#fnm2][2]]} ℘ ⇨Esyn: Synopse Nr. 13

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 32

^{[[#fnm4][4]]} ℘ Joh 1,19-23; Apg 13,24; 19,4; (3-6) Mt 3,1-6; Mk 1,2-6

^{[[#fnm5][5]]} Umkehr und Taufe, wörtlich: die Taufe der Umkehr.

^{[[#fnm6][6]]} ℘ (4f) Jes 40,3-5 G

^{[[#fnm7][7]]} ℘ (7-9) Mt 3,7-10

^{[[#fnm8][8]]} Gericht, wörtlich: Zorn.

^{[[#fnm9][9]]} ℘ ⇨Esyn: Synopse Nr. 14

^{[[#fnm10][10]]} ℘ Mt 7,19

^{[[#fnm11][11]]} ℘ ⇨Esyn: Synopse Nr. 15

^{[[#fnm12][12]]} ℘ Joh 1,24-28; (15-17) Mt 3,11f; Mk 1,7f ⇨Esyn:
Synopse Nr. 16

^{[[#fnm13][13]]} ℘ Apg 13,25

^{[[#fnm14][14]]} ℘ (19-20) Mt 14,3f; Mk 6,17f

^{[[#fnm15][15]]} Vgl. die Anmerkung zu Mt 14,3-12.

^{[[#fnm16][16]]} ℘ ⇨Esyn: Synopse Nr. 17

^{[[#fnm17][17]]} ℘ (21-22) Joh 1,29-34; Mt 3,13-17; Mk 1,9-11 ⇨Esyn:
Synopse Nr. 18

^{[[#fnm18][18]]} ℘ Gen 22,2; Ps 2,7; Jes 42,1; Mt 3,17

^{[[#fnm19][19]]} ℘ ⇨Esyn: Synopse Nr. 302

^{[[#fnm20][20]]} Aus den verschiedenen Zeitangaben der Evangelien
ergibt sich, dass Jesus sein öffentliches Wirken wohl im Jahr 28 begann
(vgl. die Anmerkung zu 2,1-3). 23-28: Anders als bei Matthäus beginnt
der Stammbaum bei Lukas mit Adam. Für die Unterschiede in den
Namensangaben der beiden Evangelisten gibt es keine befriedigende
Erklärung.

^{[[#fnm21][21]]} ℘ ⇨Esyn: Synopse Nr. 19

^{[[#fnm22][22]]} ℘ (31-33) Rut 4,18-22

^{[[#fnm23][23]]} ℘ (34-35) Gen 11,10-26

^{[[#fnm24][24]]} ℘ (36-38) Gen 5
