:PROPERTIES:
:ID:       2f92307e-6498-4a23-8f60-c818330ac015
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Lukas* --
[[file:Lk_1.html][1]] ... [[file:Lk_5.html][5]] [[file:Lk_6.html][6]]
*7* [[file:Lk_8.html][8]] [[file:Lk_9.html][9]] ...
[[file:Lk_24.html][24]]

--------------

* Lk 7
  :PROPERTIES:
  :CUSTOM_ID: lk-7
  :END:

<<verses>>

<<v1>>
*** Zeichen und Worte Jesu: 7,1 - 9,50
    :PROPERTIES:
    :CUSTOM_ID: zeichen-und-worte-jesu-71---950
    :END:
**** Der Hauptmann von Kafarnaum: 7,1-10
     :PROPERTIES:
     :CUSTOM_ID: der-hauptmann-von-kafarnaum-71-10
     :END:
1 Als Jesus diese Rede vor dem Volk beendet hatte, ging er nach
Kafarnaum hinein. ^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 85\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Ein Hauptmann hatte einen Diener, der todkrank war und den er sehr
schätzte.

<<v3>>
3 Als der Hauptmann von Jesus hörte, schickte er einige von den
jüdischen Ältesten zu ihm mit der Bitte, zu kommen und seinen Diener zu
retten.

<<v4>>
4 Sie gingen zu Jesus und baten ihn inständig. Sie sagten: Er verdient
es, dass du seine Bitte erfüllst;

<<v5>>
5 denn er liebt unser Volk und hat uns die Synagoge gebaut.

<<v6>>
6 Da ging Jesus mit ihnen. Als er nicht mehr weit von dem Haus entfernt
war, schickte der Hauptmann Freunde und ließ ihm sagen: Herr, bemüh dich
nicht! Denn ich bin es nicht wert, dass du mein Haus betrittst.

<<v7>>
7 Deshalb habe ich mich auch nicht für würdig gehalten, selbst zu dir zu
kommen. Sprich nur ein Wort, dann muss mein Diener gesund werden.

<<v8>>
8 Auch ich muss Befehlen gehorchen und ich habe selber Soldaten unter
mir; sage ich nun zu einem: Geh!, so geht er, und zu einem andern:
Komm!, so kommt er, und zu meinem Diener: Tu das!, so tut er es.

<<v9>>
9 Jesus war erstaunt über ihn, als er das hörte. Und er wandte sich um
und sagte zu den Leuten, die ihm folgten: Ich sage euch: Nicht einmal in
Israel habe ich einen solchen Glauben gefunden.

<<v10>>
10 Und als die Männer, die der Hauptmann geschickt hatte, in das Haus
zurückkehrten, stellten sie fest, dass der Diener gesund war.\\
\\

<<v11>>
**** Die Auferweckung eines jungen Mannes in Naïn: 7,11-17
     :PROPERTIES:
     :CUSTOM_ID: die-auferweckung-eines-jungen-mannes-in-naïn-711-17
     :END:
11 Einige Zeit später ging er in eine Stadt namens Naïn; seine Jünger
und eine große Menschenmenge folgten ihm.
^{[[#fn2][2]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 86\\
$ŽG://ESyn0812/\\
\\

<<v12>>
12 Als er in die Nähe des Stadttors kam, trug man gerade einen Toten
heraus. Es war der einzige Sohn seiner Mutter, einer Witwe. Und viele
Leute aus der Stadt begleiteten sie.

<<v13>>
13 Als der Herr die Frau sah, hatte er Mitleid mit ihr und sagte zu ihr:
Weine nicht!

<<v14>>
14 Dann ging er zu der Bahre hin und fasste sie an. Die Träger blieben
stehen und er sagte: Ich befehle dir, junger Mann: Steh auf!

<<v15>>
15 Da richtete sich der Tote auf und begann zu sprechen /und/ Jesus /gab
ihn seiner Mutter zurück./ ^{[[#fn3][3]]}

<<v16>>
16 Alle wurden von Furcht ergriffen; sie priesen Gott und sagten: Ein
großer Prophet ist unter uns aufgetreten: Gott hat sich seines Volkes
angenommen. ^{[[#fn4][4]]}

<<v17>>
17 Und die Kunde davon verbreitete sich überall in Judäa und im ganzen
Gebiet ringsum.\\
\\

<<v18>>
**** Die Frage des Täufers: 7,18-23
     :PROPERTIES:
     :CUSTOM_ID: die-frage-des-täufers-718-23
     :END:
18 Johannes erfuhr das alles von seinen Jüngern. Da rief er zwei von
ihnen zu sich, ^{[[#fn5][5]][[#fn6][6]][[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 106\\
$ŽG://ESyn0812/\\
\\

<<v19>>
19 schickte sie zum Herrn und ließ ihn fragen: Bist du der, der kommen
soll, oder müssen wir auf einen andern warten?

<<v20>>
20 Als die beiden Männer zu Jesus kamen, sagten sie: Johannes der Täufer
hat uns zu dir geschickt und lässt dich fragen: Bist du der, der kommen
soll, oder müssen wir auf einen andern warten?

<<v21>>
21 Damals heilte Jesus viele Menschen von ihren Krankheiten und Leiden,
befreite sie von bösen Geistern und schenkte vielen Blinden das
Augenlicht.

<<v22>>
22 Er antwortete den beiden: Geht und berichtet Johannes, was ihr
gesehen und gehört habt: /Blinde sehen wieder, Lahme/ gehen, und
Aussätzige werden rein; /Taube hören, Tote stehen auf,/ und /den Armen
wird das Evangelium verkündet./ ^{[[#fn8][8]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 211\\
$ŽG://ESyn0812/\\
\\

<<v23>>
23 Selig ist, wer an mir keinen Anstoß nimmt.\\
\\

<<v24>>
**** Das Urteil Jesu über den Täufer: 7,24-35
     :PROPERTIES:
     :CUSTOM_ID: das-urteil-jesu-über-den-täufer-724-35
     :END:
24 Als die Boten des Johannes weggegangen waren, begann Jesus zu der
Menge über Johannes zu reden; er sagte: Was habt ihr denn sehen wollen,
als ihr in die Wüste hinausgegangen seid? Ein Schilfrohr, das im Wind
schwankt? ^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 107\\
$ŽG://ESyn0812/\\
\\

<<v25>>
25 Oder was habt ihr sehen wollen, als ihr hinausgegangen seid? Einen
Mann in feiner Kleidung? Leute, die vornehm gekleidet sind und üppig
leben, findet man in den Palästen der Könige.

<<v26>>
26 Oder was habt ihr sehen wollen, als ihr hinausgegangen seid? Einen
Propheten? Ja, ich sage euch: Ihr habt sogar mehr gesehen als einen
Propheten.\\
\\

<<v27>>
27 Er ist der, von dem es in der Schrift heißt: /Ich sende meinen Boten
vor dir her;/ /\\
 /er soll den Weg/ für dich /bahnen./ ^{[[#fn10][10]]}\\
^{[[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 13\\
$ŽG://ESyn0812/\\
\\

<<v28>>
28 Ich sage euch: Unter allen Menschen gibt es keinen größeren als
Johannes; doch der Kleinste im Reich Gottes ist größer als er.
^{[[#fn12][12]]}

<<v29>>
29 Das ganze Volk, das Johannes hörte, selbst die Zöllner, sie alle
haben den Willen Gottes anerkannt und sich von Johannes taufen lassen.
^{[[#fn13][13]]}

<<v30>>
30 Doch die Pharisäer und die Gesetzeslehrer haben den Willen Gottes
missachtet und sich von Johannes nicht taufen lassen.

<<v31>>
31 Mit wem soll ich also die Menschen dieser Generation vergleichen? Wem
sind sie ähnlich? ^{[[#fn14][14]]}

<<v32>>
32 Sie sind wie Kinder, die auf dem Marktplatz sitzen und einander
zurufen: Wir haben für euch auf der Flöte (Hochzeitslieder) gespielt und
ihr habt nicht getanzt; wir haben Klagelieder gesungen und ihr habt
nicht geweint.

<<v33>>
33 Johannes der Täufer ist gekommen, er isst kein Brot und trinkt keinen
Wein und ihr sagt: Er ist von einem Dämon besessen. ^{[[#fn15][15]]}

<<v34>>
34 Der Menschensohn ist gekommen, er isst und trinkt; darauf sagt ihr:
Dieser Fresser und Säufer, dieser Freund der Zöllner und Sünder!
^{[[#fn16][16]]}

<<v35>>
35 Und doch hat die Weisheit durch alle ihre Kinder Recht bekommen.\\
\\

<<v36>>
**** Die Begegnung Jesu mit der Sünderin: 7,36-50
     :PROPERTIES:
     :CUSTOM_ID: die-begegnung-jesu-mit-der-sünderin-736-50
     :END:
36 Jesus ging in das Haus eines Pharisäers, der ihn zum Essen eingeladen
hatte, und legte sich zu Tisch. ^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 114\\
$ŽG://ESyn0812/\\
\\

<<v37>>
37 Als nun eine Sünderin, die in der Stadt lebte, erfuhr, dass er im
Haus des Pharisäers bei Tisch war, kam sie mit einem Alabastergefäß voll
wohlriechendem Öl

<<v38>>
38 und trat von hinten an ihn heran. Dabei weinte sie und ihre Tränen
fielen auf seine Füße. Sie trocknete seine Füße mit ihrem Haar, küsste
sie und salbte sie mit dem Öl. ^{[[#fn18][18]]}

<<v39>>
39 Als der Pharisäer, der ihn eingeladen hatte, das sah, dachte er: Wenn
er wirklich ein Prophet wäre, müsste er wissen, was das für eine Frau
ist, von der er sich berühren lässt; er wüsste, dass sie eine Sünderin
ist.

<<v40>>
40 Da wandte sich Jesus an ihn und sagte: Simon, ich möchte dir etwas
sagen. Er erwiderte: Sprich, Meister!

<<v41>>
41 (Jesus sagte:) Ein Geldverleiher hatte zwei Schuldner; der eine war
ihm fünfhundert Denare schuldig, der andere fünfzig.

<<v42>>
42 Als sie ihre Schulden nicht bezahlen konnten, erließ er sie beiden.
Wer von ihnen wird ihn nun mehr lieben? ^{[[#fn19][19]]}

<<v43>>
43 Simon antwortete: Ich nehme an, der, dem er mehr erlassen hat. Jesus
sagte zu ihm: Du hast recht.

<<v44>>
44 Dann wandte er sich der Frau zu und sagte zu Simon: Siehst du diese
Frau? Als ich in dein Haus kam, hast du mir kein Wasser zum Waschen der
Füße gegeben; sie aber hat ihre Tränen über meinen Füßen vergossen und
sie mit ihrem Haar abgetrocknet. ^{[[#fn20][20]]}

<<v45>>
45 Du hast mir (zur Begrüßung) keinen Kuss gegeben; sie aber hat mir,
seit ich hier bin, unaufhörlich die Füße geküsst.

<<v46>>
46 Du hast mir nicht das Haar mit Öl gesalbt; sie aber hat mir mit ihrem
wohlriechenden Öl die Füße gesalbt.

<<v47>>
47 Deshalb sage ich dir: Ihr sind ihre vielen Sünden vergeben, weil sie
(mir) so viel Liebe gezeigt hat. Wem aber nur wenig vergeben wird, der
zeigt auch nur wenig Liebe.

<<v48>>
48 Dann sagte er zu ihr: Deine Sünden sind dir vergeben.

<<v49>>
49 Da dachten die anderen Gäste: Wer ist das, dass er sogar Sünden
vergibt? ^{[[#fn21][21]]}

<<v50>>
50 Er aber sagte zu der Frau: Dein Glaube hat dir geholfen. Geh in
Frieden! ^{[[#fn22][22]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-10) Mt 8,5-13; Joh 4,46-53 ⇨Esyn: Synopse Nr. 85

^{[[#fnm2][2]]} ℘ ⇨Esyn: Synopse Nr. 86

^{[[#fnm3][3]]} ℘ 1 Kön 17,23

^{[[#fnm4][4]]} ℘ 1,68

^{[[#fnm5][5]]} ℘ (18-23) Mt 11,2-6

^{[[#fnm6][6]]} 18-23: Vgl. die Anmerkung zu Mt 11,2-6.

^{[[#fnm7][7]]} ℘ ⇨Esyn: Synopse Nr. 106

^{[[#fnm8][8]]} ℘ Jes 26,19; 29,18; 35,5f; 61,1 ⇨Esyn: Synopse Nr. 211

^{[[#fnm9][9]]} ℘ (24-35) Mt 11,7-19 ⇨Esyn: Synopse Nr. 107

^{[[#fnm10][10]]} ℘ Ex 23,20; Mal 3,1; Lk 1,76; Mk 1,2

^{[[#fnm11][11]]} ℘ ⇨Esyn: Synopse Nr. 13

^{[[#fnm12][12]]} Unter allen Menschen, wörtlich: Unter allen von einer
Frau Geborenen.

^{[[#fnm13][13]]} Wörtlich: sie alle haben Gott Recht gegeben.

^{[[#fnm14][14]]} 31-35: Vgl. die Anmerkung zu Mt 11,16-19.

^{[[#fnm15][15]]} ℘ 1,15

^{[[#fnm16][16]]} ℘ 5,30; 15,1f; 19,7; Mt 9,10f

^{[[#fnm17][17]]} ℘ (36-50) Mt 26,6-13; Mk 14,3-9; Joh 12,3-8 ⇨Esyn:
Synopse Nr. 114

^{[[#fnm18][18]]} 38f: Die Berührung durch Sünder machte unrein; vgl.
die Anmerkung zu Mk 7,1-8.

^{[[#fnm19][19]]} ℘ Mt 18,27

^{[[#fnm20][20]]} Wörtlich: hast du mir kein Wasser über die Füße
gegossen.

^{[[#fnm21][21]]} ℘ 5,21

^{[[#fnm22][22]]} ℘ 8,48; 18,42; Mt 9,22; Mk 5,34; 10,52
