:PROPERTIES:
:ID:       cd7ce5c8-b7aa-4248-944d-78b7b9aa92c3
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Lukas* --
[[file:Lk_1.html][1]] ... [[file:Lk_7.html][7]] [[file:Lk_8.html][8]]
*9* [[file:Lk_10.html][10]] [[file:Lk_11.html][11]] ...
[[file:Lk_24.html][24]]

--------------

* Lk 9
  :PROPERTIES:
  :CUSTOM_ID: lk-9
  :END:

<<verses>>

<<v1>>
**** Die Aussendung der zwölf Jünger: 9,1-6
     :PROPERTIES:
     :CUSTOM_ID: die-aussendung-der-zwölf-jünger-91-6
     :END:
1 Dann rief er die Zwölf zu sich und gab ihnen die Kraft und die
Vollmacht, alle Dämonen auszutreiben und die Kranken gesund zu machen.
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 142\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Und er sandte sie aus mit dem Auftrag, das Reich Gottes zu verkünden
und zu heilen. ^{[[#fn4][4]]}

<<v3>>
3 Er sagte zu ihnen: Nehmt nichts mit auf den Weg, keinen Wanderstab und
keine Vorratstasche, kein Brot, kein Geld und kein zweites Hemd.

<<v4>>
4 Bleibt in dem Haus, in dem ihr einkehrt, bis ihr den Ort wieder
verlasst.

<<v5>>
5 Wenn euch aber die Leute in einer Stadt nicht aufnehmen wollen, dann
geht weg und schüttelt den Staub von euren Füßen, zum Zeugnis gegen sie.

<<v6>>
6 Die Zwölf machten sich auf den Weg und wanderten von Dorf zu Dorf. Sie
verkündeten das Evangelium und heilten überall die Kranken.\\
\\

<<v7>>
**** Das Urteil des Herodes über Jesus: 9,7-9
     :PROPERTIES:
     :CUSTOM_ID: das-urteil-des-herodes-über-jesus-97-9
     :END:
7 Der Tetrarch Herodes hörte von allem, was geschah, und wusste nicht,
was er davon halten sollte. Denn manche sagten: Johannes ist von den
Toten auferstanden.
^{[[#fn5][5]][[#fn6][6]][[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 143\\
$ŽG://ESyn0812/\\
\\

<<v8>>
8 Andere meinten: Elija ist wiedererschienen. Wieder andere: Einer der
alten Propheten ist auferstanden. ^{[[#fn8][8]]}

<<v9>>
9 Herodes aber sagte: Johannes habe ich selbst enthaupten lassen. Wer
ist dann dieser Mann, von dem man mir solche Dinge erzählt? Und er hatte
den Wunsch, ihn einmal zu sehen. ^{[[#fn9][9]]}\\
\\

<<v10>>
**** Die Rückkehr der Jünger und die Speisung der Fünftausend: 9,10-17
     :PROPERTIES:
     :CUSTOM_ID: die-rückkehr-der-jünger-und-die-speisung-der-fünftausend-910-17
     :END:
10 Die Apostel kamen zurück und erzählten Jesus alles, was sie getan
hatten. Dann nahm er sie beiseite und zog sich in die Nähe der Stadt
Betsaida zurück, um mit ihnen allein zu sein.
^{[[#fn10][10]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 146\\
$ŽG://ESyn0812/\\
\\

<<v11>>
11 Aber die Leute erfuhren davon und folgten ihm. Er empfing sie
freundlich, redete zu ihnen vom Reich Gottes und heilte alle, die seine
Hilfe brauchten.

<<v12>>
12 Als der Tag zur Neige ging, kamen die Zwölf zu ihm und sagten: Schick
die Menschen weg, damit sie in die umliegenden Dörfer und Gehöfte gehen,
dort Unterkunft finden und etwas zu essen bekommen; denn wir sind hier
an einem abgelegenen Ort.

<<v13>>
13 Er antwortete: Gebt ihr ihnen zu essen! Sie sagten: Wir haben nicht
mehr als fünf Brote und zwei Fische; wir müssten erst weggehen und für
all diese Leute Essen kaufen.

<<v14>>
14 Es waren etwa fünftausend Männer. Er erwiderte seinen Jüngern: Sagt
ihnen, sie sollen sich in Gruppen zu ungefähr fünfzig zusammensetzen.

<<v15>>
15 Die Jünger taten, was er ihnen sagte, und veranlassten, dass sich
alle setzten.

<<v16>>
16 Jesus aber nahm die fünf Brote und die zwei Fische, blickte zum
Himmel auf, segnete sie und brach sie; dann gab er sie den Jüngern,
damit sie diese an die Leute austeilten.

<<v17>>
17 Und alle aßen und wurden satt. Als man die übrig gebliebenen
Brotstücke einsammelte, waren es zwölf Körbe voll.\\
\\

<<v18>>
**** Das Messiasbekenntnis des Petrus und die erste Ankündigung von
Leiden und Auferstehung: 9,18-22
     :PROPERTIES:
     :CUSTOM_ID: das-messiasbekenntnis-des-petrus-und-die-erste-ankündigung-von-leiden-und-auferstehung-918-22
     :END:
18 Jesus betete einmal in der Einsamkeit, und die Jünger waren bei ihm.
Da fragte er sie: Für wen halten mich die Leute?
^{[[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 158\\
$ŽG://ESyn0812/\\
\\

<<v19>>
19 Sie antworteten: Einige für Johannes den Täufer, andere für Elija;
wieder andere sagen: Einer der alten Propheten ist auferstanden.
^{[[#fn12][12]]}

<<v20>>
20 Da sagte er zu ihnen: Ihr aber, für wen haltet ihr mich? Petrus
antwortete: Für den Messias Gottes. ^{[[#fn13][13]]}

<<v21>>
21 Doch er verbot ihnen streng, es jemand weiterzusagen.

<<v22>>
22 Und er fügte hinzu: Der Menschensohn muss vieles erleiden und von den
Ältesten, den Hohenpriestern und den Schriftgelehrten verworfen werden;
er wird getötet werden, aber am dritten Tag wird er auferstehen.
^{[[#fn14][14]]}\\
^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 159\\
$ŽG://ESyn0812/

<<v23>>
**** Von Nachfolge und Selbstverleugnung: 9,23-27
     :PROPERTIES:
     :CUSTOM_ID: von-nachfolge-und-selbstverleugnung-923-27
     :END:
23 Zu allen sagte er: Wer mein Jünger sein will, der verleugne sich
selbst, nehme täglich sein Kreuz auf sich und folge mir nach.
^{[[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 302\\
$ŽG://ESyn0812/\\
\\

<<v24>>
24 Denn wer sein Leben retten will, wird es verlieren; wer aber sein
Leben um meinetwillen verliert, der wird es retten.
^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 235\\
$ŽG://ESyn0812/\\
\\

<<v25>>
25 Was nützt es einem Menschen, wenn er die ganze Welt gewinnt, dabei
aber sich selbst verliert und Schaden nimmt?

<<v26>>
26 Denn wer sich meiner und meiner Worte schämt, dessen wird sich der
Menschensohn schämen, wenn er in seiner Hoheit kommt und in der Hoheit
des Vaters und der heiligen Engel. ^{[[#fn18][18]]}

<<v27>>
27 Wahrhaftig, das sage ich euch: Von denen, die hier stehen, werden
einige den Tod nicht erleiden, bis sie das Reich Gottes gesehen haben.
^{[[#fn19][19]]}\\
^{[[#fn20][20]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 367\\
$ŽG://ESyn0812/

<<v28>>
**** Die Verklärung Jesu: 9,28-36
     :PROPERTIES:
     :CUSTOM_ID: die-verklärung-jesu-928-36
     :END:
28 Etwa acht Tage nach diesen Reden nahm Jesus Petrus, Johannes und
Jakobus beiseite und stieg mit ihnen auf einen Berg, um zu beten.
^{[[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 161\\
$ŽG://ESyn0812/\\
\\

<<v29>>
29 Und während er betete, veränderte sich das Aussehen seines Gesichtes
und sein Gewand wurde leuchtend weiß.

<<v30>>
30 Und plötzlich redeten zwei Männer mit ihm. Es waren Mose und Elija;

<<v31>>
31 sie erschienen in strahlendem Licht und sprachen von seinem Ende, das
sich in Jerusalem erfüllen sollte.

<<v32>>
32 Petrus und seine Begleiter aber waren eingeschlafen, wurden jedoch
wach und sahen Jesus in strahlendem Licht und die zwei Männer, die bei
ihm standen.

<<v33>>
33 Als die beiden sich von ihm trennen wollten, sagte Petrus zu Jesus:
Meister, es ist gut, dass wir hier sind. Wir wollen drei Hütten bauen,
eine für dich, eine für Mose und eine für Elija. Er wusste aber nicht,
was er sagte.

<<v34>>
34 Während er noch redete, kam eine Wolke und warf ihren Schatten auf
sie. Sie gerieten in die Wolke hinein und bekamen Angst.

<<v35>>
35 Da rief eine Stimme aus der Wolke: /Das ist mein auserwählter Sohn,
auf ihn sollt ihr hören./ ^{[[#fn22][22]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 302\\
$ŽG://ESyn0812/\\
\\

<<v36>>
36 Als aber die Stimme erklang, war Jesus wieder allein. Die Jünger
schwiegen jedoch über das, was sie gesehen hatten, und erzählten in
jenen Tagen niemand davon.\\
\\

<<v37>>
**** Die Heilung eines besessenen Jungen: 9,37-43a
     :PROPERTIES:
     :CUSTOM_ID: die-heilung-eines-besessenen-jungen-937-43a
     :END:
37 Als sie am folgenden Tag den Berg hinabstiegen, kam ihnen eine große
Menschenmenge entgegen. ^{[[#fn23][23]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 163\\
$ŽG://ESyn0812/\\
\\

<<v38>>
38 Da schrie ein Mann aus der Menge: Meister, ich bitte dich, hilf
meinem Sohn! Es ist mein einziger.

<<v39>>
39 Er ist von einem Geist besessen; plötzlich schreit er auf, wird hin
und her gezerrt und Schaum tritt ihm vor den Mund, und der Geist quält
ihn fast unaufhörlich.

<<v40>>
40 Ich habe schon deine Jünger gebeten ihn auszutreiben, aber sie
konnten es nicht.

<<v41>>
41 Da sagte Jesus: O du ungläubige und unbelehrbare Generation! Wie
lange muss ich noch bei euch sein und euch ertragen? Bring deinen Sohn
her!

<<v42>>
42 Als der Sohn herkam, warf der Dämon ihn zu Boden und zerrte ihn hin
und her. Jesus aber drohte dem unreinen Geist, heilte den Jungen und gab
ihn seinem Vater zurück.

<<v43a>>
43a Und alle gerieten außer sich über die Macht und Größe Gottes.

<<v43b>>
**** Die zweite Ankündigung von Leiden und Auferstehung: 9,43b-45
     :PROPERTIES:
     :CUSTOM_ID: die-zweite-ankündigung-von-leiden-und-auferstehung-943b-45
     :END:
43b Alle Leute staunten über das, was Jesus tat; er aber sagte zu seinen
Jüngern: ^{[[#fn24][24]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 164\\
$ŽG://ESyn0812/\\
\\

<<v44>>
44 Merkt euch genau, was ich jetzt sage: Der Menschensohn wird den
Menschen ausgeliefert werden. ^{[[#fn25][25]]}

<<v45>>
45 Doch die Jünger verstanden den Sinn seiner Worte nicht; er blieb
ihnen verborgen, sodass sie ihn nicht begriffen. Aber sie scheuten sich,
Jesus zu fragen, was er damit sagen wollte. ^{[[#fn26][26]]}\\
\\

<<v46>>
**** Der Rangstreit der Jünger: 9,46-48
     :PROPERTIES:
     :CUSTOM_ID: der-rangstreit-der-jünger-946-48
     :END:
46 Unter den Jüngern kam die Frage auf, wer von ihnen der Größte sei.
^{[[#fn27][27]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 166\\
$ŽG://ESyn0812/\\
\\

<<v47>>
47 Jesus wusste, was in ihrem Herzen vorging. Deshalb nahm er ein Kind,
stellte es neben sich

<<v48>>
48 und sagte zu ihnen: Wer dieses Kind um meinetwillen aufnimmt, der
nimmt mich auf; wer aber mich aufnimmt, der nimmt den auf, der mich
gesandt hat. Denn wer unter euch allen der Kleinste ist, der ist groß.
^{[[#fn28][28]]}\\
\\

<<v49>>
**** Der fremde Wundertäter: 9,49-50
     :PROPERTIES:
     :CUSTOM_ID: der-fremde-wundertäter-949-50
     :END:
49 Da sagte Johannes: Meister, wir haben gesehen, wie jemand in deinem
Namen Dämonen austrieb, und wir versuchten, ihn daran zu hindern, weil
er nicht mit uns zusammen dir nachfolgt.
^{[[#fn29][29]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 167\\
$ŽG://ESyn0812/\\
\\

<<v50>>
50 Jesus antwortete ihm: Hindert ihn nicht! Denn wer nicht gegen euch
ist, der ist für euch.\\
\\

<<v51>>
** Auf dem Weg nach Jerusalem: 9,51 - 19,27
   :PROPERTIES:
   :CUSTOM_ID: auf-dem-weg-nach-jerusalem-951---1927
   :END:
*** Von der wahren Jüngerschaft: 9,51 - 13,21
    :PROPERTIES:
    :CUSTOM_ID: von-der-wahren-jüngerschaft-951---1321
    :END:
**** Die ungastlichen Samariter: 9,51-56
     :PROPERTIES:
     :CUSTOM_ID: die-ungastlichen-samariter-951-56
     :END:
51 Als die Zeit herankam, in der er (in den Himmel) aufgenommen werden
sollte, entschloss sich Jesus, nach Jerusalem zu gehen.
^{[[#fn30][30]][[#fn31][31]][[#fn32][32]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 174\\
$ŽG://ESyn0812/\\
\\

<<v52>>
52 Und er schickte Boten vor sich her. Diese kamen in ein samaritisches
Dorf und wollten eine Unterkunft für ihn besorgen.
^{[[#fn33][33]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 175\\
$ŽG://ESyn0812/\\
\\

<<v53>>
53 Aber man nahm ihn nicht auf, weil er auf dem Weg nach Jerusalem war.

<<v54>>
54 Als die Jünger Jakobus und Johannes das sahen, sagten sie: Herr,
sollen wir befehlen, dass Feuer vom Himmel fällt und sie vernichtet?
^{[[#fn34][34]]}

<<v55>>
55 Da wandte er sich um und wies sie zurecht. ^{[[#fn35][35]]}

<<v56>>
56 Und sie gingen zusammen in ein anderes Dorf.\\
\\

<<v57>>
**** Von der Nachfolge: 9,57-62
     :PROPERTIES:
     :CUSTOM_ID: von-der-nachfolge-957-62
     :END:
57 Als sie auf ihrem Weg weiterzogen, redete ein Mann Jesus an und
sagte: Ich will dir folgen, wohin du auch gehst.
^{[[#fn36][36]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 176\\
$ŽG://ESyn0812/\\
\\

<<v58>>
58 Jesus antwortete ihm: Die Füchse haben ihre Höhlen und die Vögel ihre
Nester; der Menschensohn aber hat keinen Ort, wo er sein Haupt hinlegen
kann.

<<v59>>
59 Zu einem anderen sagte er: Folge mir nach! Der erwiderte: Lass mich
zuerst heimgehen und meinen Vater begraben. ^{[[#fn37][37]]}

<<v60>>
60 Jesus sagte zu ihm: Lass die Toten ihre Toten begraben; du aber geh
und verkünde das Reich Gottes!

<<v61>>
61 Wieder ein anderer sagte: Ich will dir nachfolgen, Herr. Zuvor aber
lass mich von meiner Familie Abschied nehmen.

<<v62>>
62 Jesus erwiderte ihm: Keiner, der die Hand an den Pflug gelegt hat und
nochmals zurückblickt, taugt für das Reich Gottes.\\
\\

^{[[#fnm1][1]]} ℘ (1-6) 10,1-12; Mt 10,1.5-14; Mk 6,7-13

^{[[#fnm2][2]]} 1-6: Vgl. die Anmerkung zu Mt 9,35 - 11,1.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 142

^{[[#fnm4][4]]} ℘ 22,35

^{[[#fnm5][5]]} ℘ 9,19; Mt 16,14; (7-9) Mt 14,1f; Mk 6,14-16

^{[[#fnm6][6]]} Zu «Tetrarch» vgl. die Anmerkung zu Mt 14,1.

^{[[#fnm7][7]]} ℘ ⇨Esyn: Synopse Nr. 143

^{[[#fnm8][8]]} 8f: Vgl. die Anmerkung zu Mt 17,10-13.

^{[[#fnm9][9]]} ℘ 23,8

^{[[#fnm10][10]]} ℘ (10-17) Mt 15,32-39; Mk 8,1-10; Mt 14,13-21; Mk
6,30-44; Joh 6,1-13 ⇨Esyn: Synopse Nr. 146

^{[[#fnm11][11]]} ℘ 5,16; Mk 1,35; (18-22) Mt 16,13-21; Mk 8,27-31
⇨Esyn: Synopse Nr. 158

^{[[#fnm12][12]]} ℘ 9,7f

^{[[#fnm13][13]]} ℘ Joh 11,27

^{[[#fnm14][14]]} ℘ 9,44; 17,25; 18,31-33; 24,7; Mt 17,22f; 20,18f;
26,2; Mk 9,31; 10,32-34

^{[[#fnm15][15]]} ℘ ⇨Esyn: Synopse Nr. 159

^{[[#fnm16][16]]} ℘ 14,27; Mt 10,38f; Mt 8,22; (23-27) Mt 16,24-28; Mk
8,34 - 9,1 ⇨Esyn: Synopse Nr. 302

^{[[#fnm17][17]]} ℘ 17,33; Mt 10,39; 16,25; Joh 12,25 ⇨Esyn: Synopse Nr.
235

^{[[#fnm18][18]]} ℘ Mt 10,33

^{[[#fnm19][19]]} ℘ Mt 10,23; 24,34

^{[[#fnm20][20]]} ℘ ⇨Esyn: Synopse Nr. 367

^{[[#fnm21][21]]} ℘ (28-36) 2 Petr 1,16-18; Mt 17,1-9; Mk 9,2-8 ⇨Esyn:
Synopse Nr. 161

^{[[#fnm22][22]]} ℘ Ps 2,7; Dtn 18,15; Jes 42,1; Mt 3,17 ⇨Esyn: Synopse
Nr. 302

^{[[#fnm23][23]]} ℘ (37-43a) Mt 17,14-21; Mk 9,14-29 ⇨Esyn: Synopse Nr.
163

^{[[#fnm24][24]]} ℘ (43b-45) Mt 17,22f; Mk 9,30-32 ⇨Esyn: Synopse Nr.
164

^{[[#fnm25][25]]} ℘ 9,22; 17,25; 18,32

^{[[#fnm26][26]]} ℘ 18,34

^{[[#fnm27][27]]} ℘ 22,24-26; (46-48) Mt 18,1-5; Mk 9,33-37 ⇨Esyn:
Synopse Nr. 166

^{[[#fnm28][28]]} um meinetwillen, wörtlich: aufgrund meines Namens.

^{[[#fnm29][29]]} ℘ (49-50) Mk 9,38-41 ⇨Esyn: Synopse Nr. 167

^{[[#fnm30][30]]} ℘ Apg 1,9

^{[[#fnm31][31]]} entschloss sich Jesus, wörtlich: richtet er sein
Gesicht fest darauf. 51-56: Vgl. die Anmerkung zu Joh 4,4-6.

^{[[#fnm32][32]]} ℘ ⇨Esyn: Synopse Nr. 174

^{[[#fnm33][33]]} ℘ ⇨Esyn: Synopse Nr. 175

^{[[#fnm34][34]]} Einige Textzeugen fügen am Ende des Verses hinzu: wie
es auch Elija getan hat; vgl. 2 Kön 1,10-12.

^{[[#fnm35][35]]} Einige Textzeugen fügen am Ende des Verses hinzu: und
sagte: Ihr wisst nicht, was für ein Geist aus euch spricht. Der
Menschensohn ist nicht gekommen, um Menschen zu vernichten, sondern um
sie zu retten. Vgl. Lk 19,10.

^{[[#fnm36][36]]} ℘ (57-60) Mt 8,18-22 ⇨Esyn: Synopse Nr. 176

^{[[#fnm37][37]]} Viele alte Textzeugen haben hier: Herr, lass
mich . . .
