:PROPERTIES:
:ID:       9ad3037d-3db7-4df0-8fb8-4ee0806a8f80
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Markus* --
[[file:Mk_1.html][1]] ... [[file:Mk_12.html][12]]
[[file:Mk_13.html][13]] *14* [[file:Mk_15.html][15]]
[[file:Mk_16.html][16]]

--------------

* Mk 14
  :PROPERTIES:
  :CUSTOM_ID: mk-14
  :END:

<<verses>>

<<v1>>
** Das Leiden und die Auferstehung Jesu: 14,1 - 16,20
   :PROPERTIES:
   :CUSTOM_ID: das-leiden-und-die-auferstehung-jesu-141---1620
   :END:
**** Der Beschluss des Hohen Rates: 14,1-2
     :PROPERTIES:
     :CUSTOM_ID: der-beschluss-des-hohen-rates-141-2
     :END:
1 Es war zwei Tage vor dem Pascha und dem Fest der Ungesäuerten Brote.
Die Hohenpriester und die Schriftgelehrten suchten nach einer
Möglichkeit, Jesus mit List in ihre Gewalt zu bringen, um ihn zu töten.
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 305\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Sie sagten aber: Ja nicht am Fest, damit es im Volk keinen Aufruhr
gibt.\\
\\

<<v3>>
**** Die Salbung in Betanien: 14,3-9
     :PROPERTIES:
     :CUSTOM_ID: die-salbung-in-betanien-143-9
     :END:
3 Als Jesus in Betanien im Haus Simons des Aussätzigen bei Tisch war,
kam eine Frau mit einem Alabastergefäß voll echtem, kostbarem Nardenöl,
zerbrach es und goss das Öl über sein Haar.
^{[[#fn4][4]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 306\\
$ŽG://ESyn0812/\\
\\

<<v4>>
4 Einige aber wurden unwillig und sagten zueinander: Wozu diese
Verschwendung?

<<v5>>
5 Man hätte das Öl um mehr als dreihundert Denare verkaufen und das Geld
den Armen geben können. Und sie machten der Frau heftige Vorwürfe.

<<v6>>
6 Jesus aber sagte: Hört auf! Warum lasst ihr sie nicht in Ruhe? Sie hat
ein gutes Werk an mir getan.

<<v7>>
7 Denn die Armen habt ihr immer bei euch und ihr könnt ihnen Gutes tun,
so oft ihr wollt; mich aber habt ihr nicht immer.

<<v8>>
8 Sie hat getan, was sie konnte. Sie hat im voraus meinen Leib für das
Begräbnis gesalbt.

<<v9>>
9 Amen, ich sage euch: Überall auf der Welt, wo das Evangelium verkündet
wird, wird man sich an sie erinnern und erzählen, was sie getan hat.\\
\\

<<v10>>
**** Der Verrat durch Judas: 14,10-11
     :PROPERTIES:
     :CUSTOM_ID: der-verrat-durch-judas-1410-11
     :END:
10 Judas Iskariot, einer der Zwölf, ging zu den Hohenpriestern. Er
wollte Jesus an sie ausliefern. ^{[[#fn5][5]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 307\\
$ŽG://ESyn0812/\\
\\

<<v11>>
11 Als sie das hörten, freuten sie sich und versprachen, ihm Geld dafür
zu geben. Von da an suchte er nach einer günstigen Gelegenheit, ihn
auszuliefern.\\
\\

<<v12>>
**** Die Vorbereitung des Paschamahls: 14,12-16
     :PROPERTIES:
     :CUSTOM_ID: die-vorbereitung-des-paschamahls-1412-16
     :END:
12 Am ersten Tag des Festes der Ungesäuerten Brote, an dem man das
Paschalamm schlachtete, sagten die Jünger zu Jesus: Wo sollen wir das
Paschamahl für dich vorbereiten? ^{[[#fn6][6]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 308\\
$ŽG://ESyn0812/\\
\\

<<v13>>
13 Da schickte er zwei seiner Jünger voraus und sagte zu ihnen: Geht in
die Stadt; dort wird euch ein Mann begegnen, der einen Wasserkrug trägt.
Folgt ihm, ^{[[#fn7][7]]}

<<v14>>
14 bis er in ein Haus hineingeht; dann sagt zu dem Herrn des Hauses: Der
Meister lässt dich fragen: Wo ist der Raum, in dem ich mit meinen
Jüngern das Paschalamm essen kann?

<<v15>>
15 Und der Hausherr wird euch einen großen Raum im Obergeschoss zeigen,
der schon für das Festmahl hergerichtet und mit Polstern ausgestattet
ist. Dort bereitet alles für uns vor!

<<v16>>
16 Die Jünger machten sich auf den Weg und kamen in die Stadt. Sie
fanden alles so, wie er es ihnen gesagt hatte, und bereiteten das
Paschamahl vor.\\
\\

<<v17>>
**** Das Mahl: 14,17-25
     :PROPERTIES:
     :CUSTOM_ID: das-mahl-1417-25
     :END:
17 Als es Abend wurde, kam Jesus mit den Zwölf. ^{[[#fn8][8]]}

<<v18>>
18 Während sie nun bei Tisch waren und aßen, sagte er: Amen, ich sage
euch: Einer von euch wird mich verraten und ausliefern, /einer von
denen, die zusammen mit mir essen./ ^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 310\\
$ŽG://ESyn0812/\\
\\

<<v19>>
19 Da wurden sie traurig und einer nach dem andern fragte ihn: Doch
nicht etwa ich?

<<v20>>
20 Er sagte zu ihnen: Einer von euch Zwölf, der mit mir aus derselben
Schüssel isst.

<<v21>>
21 Der Menschensohn muss zwar seinen Weg gehen, wie die Schrift über ihn
sagt. Doch weh dem Menschen, durch den der Menschensohn verraten wird.
Für ihn wäre es besser, wenn er nie geboren wäre.

<<v22>>
22 Während des Mahls nahm er das Brot und sprach den Lobpreis; dann
brach er das Brot, reichte es ihnen und sagte: Nehmt, das ist mein Leib.
^{[[#fn10][10]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 311\\
$ŽG://ESyn0812/\\
\\

<<v23>>
23 Dann nahm er den Kelch, sprach das Dankgebet, reichte ihn den Jüngern
und sie tranken alle daraus.

<<v24>>
24 Und er sagte zu ihnen: Das ist mein Blut, /das Blut des Bundes,/ das
für viele vergossen wird. ^{[[#fn11][11]][[#fn12][12]]}

<<v25>>
25 Amen, ich sage euch: Ich werde nicht mehr von der Frucht des
Weinstocks trinken bis zu dem Tag, an dem ich von neuem davon trinke im
Reich Gottes.\\
\\

<<v26>>
**** Der Gang zum Ölberg: 14,26-31
     :PROPERTIES:
     :CUSTOM_ID: der-gang-zum-ölberg-1426-31
     :END:
26 Nach dem Lobgesang gingen sie zum Ölberg hinaus.
^{[[#fn13][13]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 367\\
$ŽG://ESyn0812/\\
\\

<<v27>>
27 Da sagte Jesus zu ihnen: Ihr werdet alle (an mir) Anstoß nehmen und
zu Fall kommen; denn in der Schrift steht: /Ich werde den Hirten
erschlagen, dann werden sich die Schafe zerstreuen./ ^{[[#fn14][14]]}

<<v28>>
28 Aber nach meiner Auferstehung werde ich euch nach Galiläa
vorausgehen. ^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 352\\
$ŽG://ESyn0812/\\
\\

<<v29>>
29 Da sagte Petrus zu ihm: Auch wenn alle (an dir) Anstoß nehmen - ich
nicht! ^{[[#fn16][16]]}

<<v30>>
30 Jesus antwortete ihm: Amen, ich sage dir: Noch heute Nacht, ehe der
Hahn zweimal kräht, wirst du mich dreimal verleugnen.

<<v31>>
31 Petrus aber beteuerte: Und wenn ich mit dir sterben müsste - ich
werde dich nie verleugnen. Das gleiche sagten auch alle anderen.\\
\\

<<v32>>
**** Das Gebet in Getsemani: 14,32-42
     :PROPERTIES:
     :CUSTOM_ID: das-gebet-in-getsemani-1432-42
     :END:
32 Sie kamen zu einem Grundstück, das Getsemani heißt, und er sagte zu
seinen Jüngern: Setzt euch und wartet hier, während ich bete.
^{[[#fn17][17]]}

<<v33>>
33 Und er nahm Petrus, Jakobus und Johannes mit sich. Da ergriff ihn
Furcht und Angst,

<<v34>>
34 und er sagte zu ihnen: Meine Seele ist zu Tode betrübt. Bleibt hier
und wacht! ^{[[#fn18][18]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 302\\
$ŽG://ESyn0812/\\
\\

<<v35>>
35 Und er ging ein Stück weiter, warf sich auf die Erde nieder und
betete, dass die Stunde, wenn möglich, an ihm vorübergehe.

<<v36>>
36 Er sprach: Abba, Vater, alles ist dir möglich. Nimm diesen Kelch von
mir! Aber nicht, was ich will, sondern was du willst (soll geschehen).
^{[[#fn19][19]]}

<<v37>>
37 Und er ging zurück und fand sie schlafend. Da sagte er zu Petrus:
Simon, du schläfst? Konntest du nicht einmal eine Stunde wach bleiben?

<<v38>>
38 Wacht und betet, damit ihr nicht in Versuchung geratet. Der Geist ist
willig, aber das Fleisch ist schwach.

<<v39>>
39 Und er ging wieder weg und betete mit den gleichen Worten.

<<v40>>
40 Als er zurückkam, fand er sie wieder schlafend, denn die Augen waren
ihnen zugefallen; und sie wussten nicht, was sie ihm antworten sollten.

<<v41>>
41 Und er kam zum dritten Mal und sagte zu ihnen: Schlaft ihr immer noch
und ruht euch aus? Es ist genug. Die Stunde ist gekommen; jetzt wird der
Menschensohn den Sündern ausgeliefert.

<<v42>>
42 Steht auf, wir wollen gehen! Seht, der Verräter, der mich ausliefert,
ist da.\\
\\

<<v43>>
**** Die Gefangennahme: 14,43-52
     :PROPERTIES:
     :CUSTOM_ID: die-gefangennahme-1443-52
     :END:
43 Noch während er redete, kam Judas, einer der Zwölf, mit einer Schar
von Männern, die mit Schwertern und Knüppeln bewaffnet waren; sie waren
von den Hohenpriestern, den Schriftgelehrten und den Ältesten geschickt
worden. ^{[[#fn20][20]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 331\\
$ŽG://ESyn0812/\\
\\

<<v44>>
44 Der Verräter hatte mit ihnen ein Zeichen vereinbart und gesagt: Der,
den ich küssen werde, der ist es. Nehmt ihn fest, führt ihn ab und lasst
ihn nicht entkommen.

<<v45>>
45 Und als er kam, ging er sogleich auf Jesus zu und sagte: Rabbi! Und
er küsste ihn.

<<v46>>
46 Da ergriffen sie ihn und nahmen ihn fest.

<<v47>>
47 Einer von denen, die dabeistanden, zog das Schwert, schlug auf den
Diener des Hohenpriesters ein und hieb ihm ein Ohr ab.

<<v48>>
48 Da sagte Jesus zu ihnen: Wie gegen einen Räuber seid ihr mit
Schwertern und Knüppeln ausgezogen, um mich festzunehmen.

<<v49>>
49 Tag für Tag war ich bei euch im Tempel und lehrte und ihr habt mich
nicht verhaftet; aber (das ist geschehen), damit die Schrift in
Erfüllung geht. ^{[[#fn21][21]]}

<<v50>>
50 Da verließen ihn alle und flohen. ^{[[#fn22][22]]}

<<v51>>
51 Ein junger Mann aber, der nur mit einem leinenen Tuch bekleidet war,
wollte ihm nachgehen. Da packten sie ihn;

<<v52>>
52 er aber ließ das Tuch fallen und lief nackt davon.\\
\\

<<v53>>
**** Das Verhör vor dem Hohen Rat: 14,53-65
     :PROPERTIES:
     :CUSTOM_ID: das-verhör-vor-dem-hohen-rat-1453-65
     :END:
53 Darauf führten sie Jesus zum Hohenpriester und es versammelten sich
alle Hohenpriester und Ältesten und Schriftgelehrten.
^{[[#fn23][23]][[#fn24][24]][[#fn25][25]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 332\\
$ŽG://ESyn0812/\\
\\

<<v54>>
54 Petrus aber war Jesus von weitem bis in den Hof des
hohepriesterlichen Palastes gefolgt; nun saß er dort bei den Dienern und
wärmte sich am Feuer.

<<v55>>
55 Die Hohenpriester und der ganze Hohe Rat bemühten sich um
Zeugenaussagen gegen Jesus, um ihn zum Tod verurteilen zu können; sie
fanden aber nichts.

<<v56>>
56 Viele machten zwar falsche Aussagen über ihn, aber die Aussagen
stimmten nicht überein.

<<v57>>
57 Einige der falschen Zeugen, die gegen ihn auftraten, behaupteten:
^{[[#fn26][26]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 25\\
$ŽG://ESyn0812/\\
\\

<<v58>>
58 Wir haben ihn sagen hören: Ich werde diesen von Menschen erbauten
Tempel niederreißen und in drei Tagen einen anderen errichten, der nicht
von Menschenhand gemacht ist. ^{[[#fn27][27]]}

<<v59>>
59 Aber auch in diesem Fall stimmten die Aussagen nicht überein.

<<v60>>
60 Da stand der Hohepriester auf, trat in die Mitte und fragte Jesus:
Willst du denn nichts sagen zu dem, was diese Leute gegen dich
vorbringen?

<<v61>>
61 Er aber schwieg und gab keine Antwort. Da wandte sich der
Hohepriester nochmals an ihn und fragte: Bist du der Messias, der Sohn
des Hochgelobten? ^{[[#fn28][28]][[#fn29][29]]}

<<v62>>
62 Jesus sagte: Ich bin es. Und ihr werdet /den Menschensohn zur
Rechten/ der Macht /sitzen/ und /mit den Wolken des Himmels kommen/
sehen. ^{[[#fn30][30]]}

<<v63>>
63 Da zerriss der Hohepriester sein Gewand und rief: Wozu brauchen wir
noch Zeugen?

<<v64>>
64 Ihr habt die Gotteslästerung gehört. Was ist eure Meinung? Und sie
fällten einstimmig das Urteil: Er ist schuldig und muss sterben.

<<v65>>
65 Und einige spuckten ihn an, verhüllten sein Gesicht, schlugen ihn und
riefen: Zeig, dass du ein Prophet bist! Auch die Diener schlugen ihn ins
Gesicht. ^{[[#fn31][31]]}\\
\\

<<v66>>
**** Die Verleugnung durch Petrus: 14,66-72
     :PROPERTIES:
     :CUSTOM_ID: die-verleugnung-durch-petrus-1466-72
     :END:
66 Als Petrus unten im Hof war, kam eine von den Mägden des
Hohenpriesters. ^{[[#fn32][32]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 333\\
$ŽG://ESyn0812/\\
\\

<<v67>>
67 Sie sah, wie Petrus sich wärmte, blickte ihn an und sagte: Auch du
warst mit diesem Jesus aus Nazaret zusammen.

<<v68>>
68 Doch er leugnete es und sagte: Ich weiß nicht und verstehe nicht,
wovon du redest. Dann ging er in den Vorhof hinaus. ^{[[#fn33][33]]}

<<v69>>
69 Als die Magd ihn dort bemerkte, sagte sie zu denen, die dabeistanden,
noch einmal: Der gehört zu ihnen.

<<v70>>
70 Er aber leugnete es wieder ab. Wenig später sagten die Leute, die
dort standen, von neuem zu Petrus: Du gehörst wirklich zu ihnen; du bist
doch auch ein Galiläer.

<<v71>>
71 Da fing er an zu fluchen und schwor: Ich kenne diesen Menschen nicht,
von dem ihr redet.

<<v72>>
72 Gleich darauf krähte der Hahn zum zweiten Mal, und Petrus erinnerte
sich, dass Jesus zu ihm gesagt hatte: Ehe der Hahn zweimal kräht, wirst
du mich dreimal verleugnen. Und er begann zu weinen. ^{[[#fn34][34]]}\\
\\

^{[[#fnm1][1]]} ℘ 11,18; 12,12; (1-2) Mt 26,3-5; Lk 22,1f

^{[[#fnm2][2]]} Das jüdische Paschafest zum Gedenken an den Auszug aus
Ägypten war mit dem Fest der Ungesäuerten Brote (Mazzot) verbunden und
umfasste zwei verschiedene Festelemente: die Feier des Paschamahls in
der ersten Vollmondnacht nach der Frühjahrs-Tagundnachtgleiche, am 14.
Nisan, und das anschließende, 7 Tage dauernde Wallfahrtsfest, das
ursprünglich das neue Erntejahr einleitete (vgl. Ex 12; 34,18; Lev
23,5-8; Dtn 16,1-8). Am 14. Nisan wurde alles Sauerteigbrot aus den
Häuser entfernt und am Nachmittag dieses Tages wurden im Tempel die
Lämmer geschlachtet. Es mussten männliche Tiere sein, einjährig und
fehlerlos (Ex 12,5).

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 305

^{[[#fnm4][4]]} ℘ (3-9) Mt 26,6-13; Lk 7,36-50; Joh 12,1-8 ⇨Esyn:
Synopse Nr. 306

^{[[#fnm5][5]]} ℘ (10-11) Mt 26,14-16; Lk 22,3-6 ⇨Esyn: Synopse Nr. 307

^{[[#fnm6][6]]} ℘ Ex 12,14-20; (12-16) Mt 26,17-19; Lk 22,7-13 ⇨Esyn:
Synopse Nr. 308

^{[[#fnm7][7]]} 13f: Normalerweise waren es Frauen, die das Wasser
trugen. Insofern handelt es sich hier um ein auffälliges
Erkennungszeichen.

^{[[#fnm8][8]]} ℘ (17-25) Mt 26,20-29; Lk 22,14-23; (17-21) Joh
13,2.21-26

^{[[#fnm9][9]]} ℘ Ps 41,10 ⇨Esyn: Synopse Nr. 310

^{[[#fnm10][10]]} ℘ (22-24) 1 Kor 11,23f ⇨Esyn: Synopse Nr. 311

^{[[#fnm11][11]]} ℘ Ex 24,8; Jes 53,11f; Jer 31,31; Hebr 7,22; 9,15

^{[[#fnm12][12]]} Zu «Blut des Bundes» vgl. die Anmerkung zu Mt 26,28.

^{[[#fnm13][13]]} ℘ Lk 22,39; Joh 18,1; (26-31) Mt 26,30-35 ⇨Esyn:
Synopse Nr. 367

^{[[#fnm14][14]]} ℘ Sach 13,7; Joh 16,32

^{[[#fnm15][15]]} ℘ ⇨Esyn: Synopse Nr. 352

^{[[#fnm16][16]]} ℘ (30-31) 14,72; Lk 22,31-34; Joh 13,36-38

^{[[#fnm17][17]]} ℘ (32-42) Mt 26,36-46; Lk 22,39-46

^{[[#fnm18][18]]} ℘ Ps 42,6.12; 43,5; Joh 12,27 ⇨Esyn: Synopse Nr. 302

^{[[#fnm19][19]]} Abba: im Aramäischen die vertrauliche Form, in der man
den Familienvater anredet (vgl. Röm 8,15; Gal 4,6).

^{[[#fnm20][20]]} ℘ (43-50) Mt 26,47-56; Lk 22,47-53; Joh 18,3-12 ⇨Esyn:
Synopse Nr. 331

^{[[#fnm21][21]]} ℘ Lk 19,47; Joh 18,20

^{[[#fnm22][22]]} ℘ Joh 16,32

^{[[#fnm23][23]]} ℘ (53-65) Mt 26,57-68; Lk 22,54f.66-71; Joh 18,13-24

^{[[#fnm24][24]]} 53-65: Markus berichtet wie Matthäus von einem
nächtlichen Verhör vor dem Hohenpriester und Mitgliedern des Hohen
Rates, bei dem der Hohe Rat das Todesurteil fällte. Nach Lk 22,66-71
fand dieses Verhör am Morgen statt, ohne ausdrückliches Todesurteil.
Nach Joh 18,12-24 wurde Jesus von dem Hohenpriester Hannas nach seiner
Lehre und seinen Anhängern befragt und dann noch dem amtierenden
Hohenpriester Kajaphas vorgeführt. Von einem eigentlichen Verhör oder
gar einer Verurteilung zum Tod durch die Juden wird bei Johannes nichts
erzählt.

^{[[#fnm25][25]]} ℘ ⇨Esyn: Synopse Nr. 332

^{[[#fnm26][26]]} ℘ ⇨Esyn: Synopse Nr. 25

^{[[#fnm27][27]]} ℘ 15,29; Joh 2,19; Apg 6,14

^{[[#fnm28][28]]} ℘ 8,29; Joh 10,24

^{[[#fnm29][29]]} 61f: Der Ausdruck «der Hochgelobte» ist ebenso wie
«die Macht» Umschreibung für Gott.

^{[[#fnm30][30]]} ℘ Dan 7,13; Ps 110,1; Mt 24,30; Mk 13,26

^{[[#fnm31][31]]} Zeig, dass du ein Prophet bist, wörtlich: Prophezei!

^{[[#fnm32][32]]} ℘ (66-72) Mt 26,69-75; Lk 22,56-62; Joh 18,17.25-27
⇨Esyn: Synopse Nr. 333

^{[[#fnm33][33]]} Spätere Textzeugen fügen am Ende des Verses hinzu: Da
krähte der Hahn.

^{[[#fnm34][34]]} ℘ 14,30
