:PROPERTIES:
:ID:       eea5e659-cc84-4968-b407-fa1a4c1fbdc2
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Markus* --
[[file:Mk_1.html][1]] [[file:Mk_2.html][2]] [[file:Mk_3.html][3]] *4*
[[file:Mk_5.html][5]] [[file:Mk_6.html][6]] ... [[file:Mk_16.html][16]]

--------------

* Mk 4
  :PROPERTIES:
  :CUSTOM_ID: mk-4
  :END:

<<verses>>

<<v1>>
*** Die Gleichnisse vom Reich Gottes: 4,1-34
    :PROPERTIES:
    :CUSTOM_ID: die-gleichnisse-vom-reich-gottes-41-34
    :END:
**** Das Gleichnis vom Sämann: 4,1-9
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-sämann-41-9
     :END:
1 Ein andermal lehrte er wieder am Ufer des Sees und sehr viele Menschen
versammelten sich um ihn. Er stieg deshalb in ein Boot auf dem See und
setzte sich; die Leute aber standen am Ufer.
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 122\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Und er sprach lange zu ihnen und lehrte sie in Form von Gleichnissen.
Bei dieser Belehrung sagte er zu ihnen:

<<v3>>
3 Hört! Ein Sämann ging aufs Feld, um zu säen.

<<v4>>
4 Als er säte, fiel ein Teil der Körner auf den Weg und die Vögel kamen
und fraßen sie.

<<v5>>
5 Ein anderer Teil fiel auf felsigen Boden, wo es nur wenig Erde gab,
und ging sofort auf, weil das Erdreich nicht tief war;

<<v6>>
6 als aber die Sonne hochstieg, wurde die Saat versengt und verdorrte,
weil sie keine Wurzeln hatte.

<<v7>>
7 Wieder ein anderer Teil fiel in die Dornen und die Dornen wuchsen und
erstickten die Saat und sie brachte keine Frucht.

<<v8>>
8 Ein anderer Teil schließlich fiel auf guten Boden und brachte Frucht;
die Saat ging auf und wuchs empor und trug dreißigfach, ja sechzigfach
und hundertfach.

<<v9>>
9 Und Jesus sprach: Wer Ohren hat zum Hören, der höre! ^{[[#fn4][4]]}\\
\\

<<v10>>
**** Sinn und Zweck der Gleichnisse: 4,10-12
     :PROPERTIES:
     :CUSTOM_ID: sinn-und-zweck-der-gleichnisse-410-12
     :END:
10 Als er mit seinen Begleitern und den Zwölf allein war, fragten sie
ihn nach dem Sinn seiner Gleichnisse. ^{[[#fn5][5]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 303\\
$ŽG://ESyn0812/\\
\\

<<v11>>
11 Da sagte er zu ihnen: Euch ist das Geheimnis des Reiches Gottes
anvertraut; denen aber, die draußen sind, wird alles in Gleichnissen
gesagt;\\
\\

<<v12>>
12 denn /sehen sollen sie, sehen, aber nicht erkennen;/ /\\
 /hören sollen sie, hören, aber nicht verstehen,/ /\\
 /damit sie sich nicht bekehren/ /\\
 /und ihnen nicht vergeben wird./ ^{[[#fn6][6]]}\\
^{[[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 248\\
$ŽG://ESyn0812/

<<v13>>
**** Die Deutung des Gleichnisses vom Sämann: 4,13-20
     :PROPERTIES:
     :CUSTOM_ID: die-deutung-des-gleichnisses-vom-sämann-413-20
     :END:
13 Und er sagte zu ihnen: Wenn ihr schon dieses Gleichnis nicht
versteht, wie wollt ihr dann all die anderen Gleichnisse verstehen?
^{[[#fn8][8]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 124\\
$ŽG://ESyn0812/\\
\\

<<v14>>
14 Der Sämann sät das Wort.

<<v15>>
15 Auf den Weg fällt das Wort bei denen, die es zwar hören, aber sofort
kommt der Satan und nimmt das Wort weg, das in sie gesät wurde.

<<v16>>
16 Ähnlich ist es bei den Menschen, bei denen das Wort auf felsigen
Boden fällt: Sobald sie es hören, nehmen sie es freudig auf;

<<v17>>
17 aber sie haben keine Wurzeln, sondern sind unbeständig, und wenn sie
dann um des Wortes willen bedrängt oder verfolgt werden, kommen sie
sofort zu Fall.

<<v18>>
18 Bei anderen fällt das Wort in die Dornen: sie hören es zwar,

<<v19>>
19 aber die Sorgen der Welt, der trügerische Reichtum und die Gier nach
all den anderen Dingen machen sich breit und ersticken es und es bringt
keine Frucht. ^{[[#fn9][9]]}

<<v20>>
20 Auf guten Boden ist das Wort bei denen gesät, die es hören und
aufnehmen und Frucht bringen, dreißigfach, ja sechzigfach und
hundertfach.\\
\\

<<v21>>
**** Vom rechten Hören: 4,21-25
     :PROPERTIES:
     :CUSTOM_ID: vom-rechten-hören-421-25
     :END:
21 Er sagte zu ihnen: Zündet man etwa ein Licht an und stülpt ein Gefäß
darüber oder stellt es unter das Bett? Stellt man es nicht auf den
Leuchter? ^{[[#fn10][10]][[#fn11][11]][[#fn12][12]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 125\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 Es gibt nichts Verborgenes, das nicht offenbar wird, und nichts
Geheimes, das nicht an den Tag kommt. ^{[[#fn13][13]]}

<<v23>>
23 Wenn einer Ohren hat zum Hören, so höre er! ^{[[#fn14][14]]}

<<v24>>
24 Weiter sagte er: Achtet auf das, was ihr hört! Nach dem Maß, mit dem
ihr messt und zuteilt, wird euch zugeteilt werden, ja, es wird euch noch
mehr gegeben. ^{[[#fn15][15]]}

<<v25>>
25 Denn wer hat, dem wird gegeben; wer aber nicht hat, dem wird auch
noch weggenommen, was er hat. ^{[[#fn16][16]]}\\
\\

<<v26>>
**** Das Gleichnis vom Wachsen der Saat: 4,26-29
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-wachsen-der-saat-426-29
     :END:
26 Er sagte: Mit dem Reich Gottes ist es so, wie wenn ein Mann Samen auf
seinen Acker sät; ^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 126\\
$ŽG://ESyn0812/\\
\\

<<v27>>
27 dann schläft er und steht wieder auf, es wird Nacht und wird Tag, der
Samen keimt und wächst und der Mann weiß nicht, wie.

<<v28>>
28 Die Erde bringt von selbst ihre Frucht, zuerst den Halm, dann die
Ähre, dann das volle Korn in der Ähre.

<<v29>>
29 Sobald aber die Frucht reif ist, /legt er die Sichel an; denn die
Zeit der Ernte ist da./ ^{[[#fn18][18]]}\\
\\

<<v30>>
**** Das Gleichnis vom Senfkorn: 4,30-32
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-senfkorn-430-32
     :END:
30 Er sagte: Womit sollen wir das Reich Gottes vergleichen, mit welchem
Gleichnis sollen wir es beschreiben? ^{[[#fn19][19]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 128\\
$ŽG://ESyn0812/\\
\\

<<v31>>
31 Es gleicht einem Senfkorn. Dieses ist das kleinste von allen
Samenkörnern, die man in die Erde sät.

<<v32>>
32 Ist es aber gesät, dann geht es auf und wird größer als alle anderen
Gewächse und /treibt/ große /Zweige,/ sodass /in seinem Schatten die
Vögel des Himmels nisten/ können. ^{[[#fn20][20]]}\\
\\

<<v33>>
**** Schlussbemerkung zu den Gleichnissen: 4,33-34
     :PROPERTIES:
     :CUSTOM_ID: schlussbemerkung-zu-den-gleichnissen-433-34
     :END:
33 Durch viele solche Gleichnisse verkündete er ihnen das Wort, so wie
sie es aufnehmen konnten. ^{[[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 130\\
$ŽG://ESyn0812/\\
\\

<<v34>>
34 Er redete nur in Gleichnissen zu ihnen; seinen Jüngern aber erklärte
er alles, wenn er mit ihnen allein war.\\
\\

<<v35>>
*** Taten und Worte Jesu: 4,35 - 8,26
    :PROPERTIES:
    :CUSTOM_ID: taten-und-worte-jesu-435---826
    :END:
**** Der Sturm auf dem See: 4,35-41
     :PROPERTIES:
     :CUSTOM_ID: der-sturm-auf-dem-see-435-41
     :END:
35 Am Abend dieses Tages sagte er zu ihnen: Wir wollen ans andere Ufer
hinüberfahren. ^{[[#fn22][22]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 136\\
$ŽG://ESyn0812/\\
\\

<<v36>>
36 Sie schickten die Leute fort und fuhren mit ihm in dem Boot, in dem
er saß, weg; einige andere Boote begleiteten ihn.

<<v37>>
37 Plötzlich erhob sich ein heftiger Wirbelsturm, und die Wellen
schlugen in das Boot, sodass es sich mit Wasser zu füllen begann.

<<v38>>
38 Er aber lag hinten im Boot auf einem Kissen und schlief. Sie weckten
ihn und riefen: Meister, kümmert es dich nicht, dass wir zugrunde gehen?

<<v39>>
39 Da stand er auf, drohte dem Wind und sagte zu dem See: Schweig, sei
still! Und der Wind legte sich und es trat völlige Stille ein.
^{[[#fn23][23]]}

<<v40>>
40 Er sagte zu ihnen: Warum habt ihr solche Angst? Habt ihr noch keinen
Glauben? ^{[[#fn24][24]]}

<<v41>>
41 Da ergriff sie große Furcht und sie sagten zueinander: Was ist das
für ein Mensch, dass ihm sogar der Wind und der See gehorchen?\\
\\

^{[[#fnm1][1]]} ℘ (1-9) Mt 13,1-9; Lk 8,4-8

^{[[#fnm2][2]]} 1-34: In diesem Kapitel sind drei Saatgleichnisse (s.
VV. 3.26.31) gesammelt; dazu kommen eine nachträgliche allegorische
Deutung des ersten Gleichnisses (VV. 13-20) und mehrere Sprüche (VV.
21-24). Ursprünglich sind die Gleichnisse Jesu nicht als Allegorien
gemeint, die Zug um Zug auf die Wirklichkeit übertragen werden können,
sondern sie stellen jeweils als ein Ganzes einen Grundgedanken bildhaft
dar.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 122

^{[[#fnm4][4]]} ℘ Mt 11,15

^{[[#fnm5][5]]} ℘ (10-12) Mt 13,10-17; Lk 8,9f ⇨Esyn: Synopse Nr. 303

^{[[#fnm6][6]]} ℘ Jes 6,9f; Joh 12,40; Apg 28,26f

^{[[#fnm7][7]]} ℘ ⇨Esyn: Synopse Nr. 248

^{[[#fnm8][8]]} ℘ (13-20) Mt 13,18-23; Lk 8,11-15 ⇨Esyn: Synopse Nr. 124

^{[[#fnm9][9]]} ℘ 1 Tim 6,9

^{[[#fnm10][10]]} ℘ Mt 5,15; Lk 11,33; (21-25) Lk 8,16-18

^{[[#fnm11][11]]} Vgl. die Anmerkung zu Mt 5,15.

^{[[#fnm12][12]]} ℘ ⇨Esyn: Synopse Nr. 125

^{[[#fnm13][13]]} ℘ Mt 10,26; Lk 12,2

^{[[#fnm14][14]]} ℘ Mt 11,15

^{[[#fnm15][15]]} ℘ Mt 7,2; Lk 6,38

^{[[#fnm16][16]]} ℘ Mt 13,12; 25,29; Lk 19,26

^{[[#fnm17][17]]} ℘ ⇨Esyn: Synopse Nr. 126

^{[[#fnm18][18]]} ℘ Joël 4,13

^{[[#fnm19][19]]} ℘ (30-32) Mt 13,31f; Lk 13,18f ⇨Esyn: Synopse Nr. 128

^{[[#fnm20][20]]} ℘ Dan 4,8f.18; Ez 17,23

^{[[#fnm21][21]]} ℘ (33-34) Mt 13,34 ⇨Esyn: Synopse Nr. 130

^{[[#fnm22][22]]} ℘ (35-41) Mt 8,18.23-27; Lk 8,22-25 ⇨Esyn: Synopse Nr.
136

^{[[#fnm23][23]]} ℘ 6,51

^{[[#fnm24][24]]} Statt «Habt ihr . . .» haben mehrere Textzeugen: Warum
habt ihr keinen Glauben?
