:PROPERTIES:
:ID:       917afd8d-f67a-4b6a-9c97-0bffa0b2b275
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Markus* --
[[file:Mk_1.html][1]] ... [[file:Mk_5.html][5]] [[file:Mk_6.html][6]]
*7* [[file:Mk_8.html][8]] [[file:Mk_9.html][9]] ...
[[file:Mk_16.html][16]]

--------------

* Mk 7
  :PROPERTIES:
  :CUSTOM_ID: mk-7
  :END:

<<verses>>

<<v1>>
**** Von Reinheit und Unreinheit: 7,1-23
     :PROPERTIES:
     :CUSTOM_ID: von-reinheit-und-unreinheit-71-23
     :END:
1 Die Pharisäer und einige Schriftgelehrte, die aus Jerusalem gekommen
waren, hielten sich bei Jesus auf.
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 150\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Sie sahen, dass einige seiner Jünger ihr Brot mit unreinen, das heißt
mit ungewaschenen Händen aßen. ^{[[#fn4][4]]}

<<v3>>
3 Die Pharisäer essen nämlich wie alle Juden nur, wenn sie vorher mit
einer Hand voll Wasser die Hände gewaschen haben, wie es die
Überlieferung der Alten vorschreibt. ^{[[#fn5][5]]}

<<v4>>
4 Auch wenn sie vom Markt kommen, essen sie nicht, ohne sich vorher zu
waschen. Noch viele andere überlieferte Vorschriften halten sie ein, wie
das Abspülen von Bechern, Krügen und Kesseln. ^{[[#fn6][6]][[#fn7][7]]}

<<v5>>
5 Die Pharisäer und die Schriftgelehrten fragten ihn also: Warum halten
sich deine Jünger nicht an die Überlieferung der Alten, sondern essen
ihr Brot mit unreinen Händen?\\
\\

<<v6>>
6 Er antwortete ihnen: Der Prophet Jesaja hatte Recht mit dem, was er
über euch Heuchler sagte: /Dieses Volk ehrt mich mit den Lippen,/ /\\
 /sein Herz aber ist weit weg von mir./ ^{[[#fn8][8]]}\\
\\

<<v7>>
7 /Es ist sinnlos, wie sie mich verehren;/ /\\
 /was sie lehren, sind Satzungen von Menschen./

<<v8>>
8 Ihr gebt Gottes Gebot preis und haltet euch an die Überlieferung der
Menschen.

<<v9>>
9 Und weiter sagte Jesus: Sehr geschickt setzt ihr Gottes Gebot außer
Kraft und haltet euch an eure eigene Überlieferung. ^{[[#fn9][9]]}

<<v10>>
10 Mose hat zum Beispiel gesagt: /Ehre deinen Vater und deine Mutter!,/
und: /Wer Vater oder Mutter verflucht, soll mit dem Tod bestraft
werden./ ^{[[#fn10][10]]}

<<v11>>
11 Ihr aber lehrt: Es ist erlaubt, dass einer zu seinem Vater oder
seiner Mutter sagt: Was ich dir schulde, ist Korbán, das heißt: eine
Opfergabe.

<<v12>>
12 Damit hindert ihr ihn daran, noch etwas für Vater oder Mutter zu tun.

<<v13>>
13 So setzt ihr durch eure eigene Überlieferung Gottes Wort außer Kraft.
Und ähnlich handelt ihr in vielen Fällen.

<<v14>>
14 Dann rief er die Leute wieder zu sich und sagte: Hört mir alle zu und
begreift, was ich sage:

<<v15>>
15 Nichts, was von außen in den Menschen hineinkommt, kann ihn unrein
machen, sondern was aus dem Menschen herauskommt, das macht ihn unrein.

<<v16>>
16 [] ^{[[#fn11][11]]}

<<v17>>
17 Er verließ die Menge und ging in ein Haus. Da fragten ihn seine
Jünger nach dem Sinn dieses rätselhaften Wortes.

<<v18>>
18 Er antwortete ihnen: Begreift auch ihr nicht? Seht ihr nicht ein,
dass das, was von außen in den Menschen hineinkommt, ihn nicht unrein
machen kann?

<<v19>>
19 Denn es gelangt ja nicht in sein Herz, sondern in den Magen und wird
wieder ausgeschieden. Damit erklärte Jesus alle Speisen für rein.

<<v20>>
20 Weiter sagte er: Was aus dem Menschen herauskommt, das macht ihn
unrein.

<<v21>>
21 Denn von innen, aus dem Herzen der Menschen, kommen die bösen
Gedanken, Unzucht, Diebstahl, Mord, ^{[[#fn12][12]]}

<<v22>>
22 Ehebruch, Habgier, Bosheit, Hinterlist, Ausschweifung, Neid,
Verleumdung, Hochmut und Unvernunft.

<<v23>>
23 All dieses Böse kommt von innen und macht den Menschen unrein.\\
\\

<<v24>>
**** Die Erhörung der Bitte einer heidnischen Frau: 7,24-30
     :PROPERTIES:
     :CUSTOM_ID: die-erhörung-der-bitte-einer-heidnischen-frau-724-30
     :END:
24 Jesus brach auf und zog von dort in das Gebiet von Tyrus. Er ging in
ein Haus, wollte aber, dass niemand davon erfuhr; doch es konnte nicht
verborgen bleiben.
^{[[#fn13][13]][[#fn14][14]][[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 151\\
$ŽG://ESyn0812/\\
\\

<<v25>>
25 Eine Frau, deren Tochter von einem unreinen Geist besessen war, hörte
von ihm; sie kam sogleich herbei und fiel ihm zu Füßen.

<<v26>>
26 Die Frau, von Geburt Syrophönizierin, war eine Heidin. Sie bat ihn,
aus ihrer Tochter den Dämon auszutreiben. ^{[[#fn16][16]]}

<<v27>>
27 Da sagte er zu ihr: Lasst zuerst die Kinder satt werden; denn es ist
nicht recht, das Brot den Kindern wegzunehmen und den Hunden
vorzuwerfen.

<<v28>>
28 Sie erwiderte ihm: Ja, du hast recht, Herr! Aber auch für die Hunde
unter dem Tisch fällt etwas von dem Brot ab, das die Kinder essen.

<<v29>>
29 Er antwortete ihr: Weil du das gesagt hast, sage ich dir: Geh nach
Hause, der Dämon hat deine Tochter verlassen.

<<v30>>
30 Und als sie nach Hause kam, fand sie das Kind auf dem Bett liegen und
sah, dass der Dämon es verlassen hatte.\\
\\

<<v31>>
**** Die Heilung eines Taubstummen: 7,31-37
     :PROPERTIES:
     :CUSTOM_ID: die-heilung-eines-taubstummen-731-37
     :END:
31 Jesus verließ das Gebiet von Tyrus wieder und kam über Sidon an den
See von Galiläa, mitten in das Gebiet der Dekapolis.
^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 152\\
$ŽG://ESyn0812/\\
\\

<<v32>>
32 Da brachte man einen Taubstummen zu Jesus und bat ihn, er möge ihn
berühren.

<<v33>>
33 Er nahm ihn beiseite, von der Menge weg, legte ihm die Finger in die
Ohren und berührte dann die Zunge des Mannes mit Speichel;
^{[[#fn18][18]][[#fn19][19]]}

<<v34>>
34 danach blickte er zum Himmel auf, seufzte und sagte zu dem
Taubstummen: Effata!, das heißt: Öffne dich!

<<v35>>
35 Sogleich öffneten sich seine Ohren, seine Zunge wurde von ihrer
Fessel befreit und er konnte richtig reden.

<<v36>>
36 Jesus verbot ihnen, jemand davon zu erzählen. Doch je mehr er es
ihnen verbot, desto mehr machten sie es bekannt.

<<v37>>
37 Außer sich vor Staunen sagten sie: Er hat alles gut gemacht; er
macht, dass die Tauben hören und die Stummen sprechen.
^{[[#fn20][20]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-23) Mt 15,1-20

^{[[#fnm2][2]]} 1-8.14-23: Die Reinheitsvorschriften, die von den Juden
entwickelt wurden (von den «Alten», das heißt den jüdischen
Lehrautoritäten), gingen davon aus, dass alles Geschlechtliche,
Ausscheidungen des Körpers, bestimmte Tiere und Menschen (Heiden,
Sünder, Kranke mit bestimmten Krankheiten, z. B. Aussatz), auch Leichen
ebenso wie jede Art von Schmutz verunreinigen, das heißt für den
Gottesdienst und das Gebet unwürdig machen. Diese Unreinheit konnte sich
durch Berührung auch auf tote Gegenstände übertragen. Zur
Wiederherstellung der kultischen Reinheit bedurfte es gewisser
Waschungen, Fastenübungen und religiöser Handlungen. Auch Speisen
konnten verunreinigen (vgl. Lev 11 - 15). Demgegenüber stellte Jesus
fest, dass der Wert einer Handlung allein von der Gesinnung des
Handelnden abhängt (vgl. auch die Anmerkung zu Mt 15,11).

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 150

^{[[#fnm4][4]]} ℘ Lk 11,38; Kol 2,21f

^{[[#fnm5][5]]} mit einer Hand voll Wasser, wörtlich: mit der Faust.

^{[[#fnm6][6]]} ℘ Mt 23,25

^{[[#fnm7][7]]} Andere Übersetzungsmöglichkeit: Und sie essen auch das,
was vom Markt kommt, erst, wenn sie es gewaschen haben.

^{[[#fnm8][8]]} ℘ Jes 29,13 G

^{[[#fnm9][9]]} 9-13: Das Korbán-Gelübde war ein Gelöbnis, durch das ein
Gegenstand in den Dienst Gottes, des Tempels oder des Gottesdienstes
gestellt und so der Nutznießung durch Menschen entzogen wurde. Wer also
alle Verpflichtungen und Leistungen seinen Eltern gegenüber durch das
Korbán-Gelübde Gott weihte («Opfergabe ist, was ihr von mir als
Unterstützung haben solltet»), entzog diesen ihren Unterhalt, ohne dass
er gezwungen werden konnte, das den Eltern Nicht-Geleistete auch
wirklich für religiöse Zwecke einzusetzen. Diese Praxis widersprach
deutlich dem Sinn des vierten Gebots, das dazu bestimmt war, auch den
Unterhalt alter und kranker Eltern zu sichern.

^{[[#fnm10][10]]} ℘ Ex 20,12; 21,17; Lev 20,9; Dtn 5,16

^{[[#fnm11][11]]} Spätere Textzeugen fügen hier entsprechend 4,23 ein:
Wenn einer Ohren hat zum Hören, so höre er!

^{[[#fnm12][12]]} Bei den Juden galt das Herz als Mitte der
Gemütsregungen und Sitz des Gewissens. Vgl. die Anmerkung zu Mt 15,11.

^{[[#fnm13][13]]} ℘ (24-30) Mt 15,21-28

^{[[#fnm14][14]]} 24-30: Jesus hat sich nicht von sich aus an Heiden
gewandt (vgl. Mt 10,5f; 15,24), hat aber Heiden geholfen, wenn sie ihn
darum baten. «Hund» war ein jüdisches Schimpfwort für die Heiden. Die
Juden verstanden sich demgegenüber als Kinder im Haus Gottes.

^{[[#fnm15][15]]} ℘ ⇨Esyn: Synopse Nr. 151

^{[[#fnm16][16]]} Heidin, wörtlich: Griechin.

^{[[#fnm17][17]]} ℘ (31-37) Mt 15,29-31 ⇨Esyn: Synopse Nr. 152

^{[[#fnm18][18]]} ℘ 8,23

^{[[#fnm19][19]]} Speichel galt damals als Heilmittel.

^{[[#fnm20][20]]} ℘ Jes 35,5
