:PROPERTIES:
:ID:       be9430fd-7785-4ef8-8174-d7e434773b05
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Markus* --
[[file:Mk_1.html][1]] ... [[file:Mk_7.html][7]] [[file:Mk_8.html][8]]
*9* [[file:Mk_10.html][10]] [[file:Mk_11.html][11]] ...
[[file:Mk_16.html][16]]

--------------

* Mk 9
  :PROPERTIES:
  :CUSTOM_ID: mk-9
  :END:

<<verses>>

<<v1>>
1 Und er sagte zu ihnen: Amen, ich sage euch: Von denen, die hier
stehen, werden einige den Tod nicht erleiden, bis sie gesehen haben,
dass das Reich Gottes in (seiner ganzen) Macht gekommen ist.
^{[[#fn1][1]]}\\
^{[[#fn2][2]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 367\\
$ŽG://ESyn0812/

<<v2>>
**** Die Verklärung Jesu: 9,2-10
     :PROPERTIES:
     :CUSTOM_ID: die-verklärung-jesu-92-10
     :END:
2 Sechs Tage danach nahm Jesus Petrus, Jakobus und Johannes beiseite und
führte sie auf einen hohen Berg, aber nur sie allein. Und er wurde vor
ihren Augen verwandelt; ^{[[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 161\\
$ŽG://ESyn0812/\\
\\

<<v3>>
3 seine Kleider wurden strahlend weiß, so weiß, wie sie auf Erden kein
Bleicher machen kann.

<<v4>>
4 Da erschien vor ihren Augen Elija und mit ihm Mose und sie redeten mit
Jesus. ^{[[#fn4][4]]}

<<v5>>
5 Petrus sagte zu Jesus: Rabbi, es ist gut, dass wir hier sind. Wir
wollen drei Hütten bauen, eine für dich, eine für Mose und eine für
Elija.

<<v6>>
6 Er wusste nämlich nicht, was er sagen sollte; denn sie waren vor
Furcht ganz benommen.

<<v7>>
7 Da kam eine Wolke und warf ihren Schatten auf sie, und aus der Wolke
rief eine Stimme: Das ist /mein geliebter Sohn; auf ihn sollt ihr
hören./ ^{[[#fn5][5]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 302\\
$ŽG://ESyn0812/\\
\\

<<v8>>
8 Als sie dann um sich blickten, sahen sie auf einmal niemand mehr bei
sich außer Jesus.

<<v9>>
9 Während sie den Berg hinabstiegen, verbot er ihnen, irgendjemand zu
erzählen, was sie gesehen hatten, bis der Menschensohn von den Toten
auferstanden sei. ^{[[#fn6][6]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 163\\
$ŽG://ESyn0812/\\
\\

<<v10>>
10 Dieses Wort beschäftigte sie und sie fragten einander, was das sei:
von den Toten auferstehen.\\
\\

<<v11>>
**** Von der Wiederkunft des Elija: 9,11-13
     :PROPERTIES:
     :CUSTOM_ID: von-der-wiederkunft-des-elija-911-13
     :END:
11 Da fragten sie ihn: Warum sagen die Schriftgelehrten, zuerst müsse
Elija kommen? ^{[[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 162\\
$ŽG://ESyn0812/\\
\\

<<v12>>
12 Er antwortete: Ja, Elija kommt zuerst und /stellt/ alles /wieder
her./ Aber warum heißt es dann vom Menschensohn in der Schrift, er werde
viel leiden müssen und verachtet werden? ^{[[#fn8][8]]}

<<v13>>
13 Ich sage euch: Elija ist schon gekommen, doch sie haben mit ihm
gemacht, was sie wollten, wie es in der Schrift steht. ^{[[#fn9][9]]}\\
\\

<<v14>>
**** Die Heilung eines besessenen Jungen: 9,14-29
     :PROPERTIES:
     :CUSTOM_ID: die-heilung-eines-besessenen-jungen-914-29
     :END:
14 Als sie zu den anderen Jüngern zurückkamen, sahen sie eine große
Menschenmenge um sie versammelt und Schriftgelehrte, die mit ihnen
stritten. ^{[[#fn10][10]][[#fn11][11]]}

<<v15>>
15 Sobald die Leute Jesus sahen, liefen sie in großer Erregung auf ihn
zu und begrüßten ihn.

<<v16>>
16 Er fragte sie: Warum streitet ihr mit ihnen?

<<v17>>
17 Einer aus der Menge antwortete ihm: Meister, ich habe meinen Sohn zu
dir gebracht. Er ist von einem stummen Geist besessen;

<<v18>>
18 immer wenn der Geist ihn überfällt, wirft er ihn zu Boden und meinem
Sohn tritt Schaum vor den Mund, er knirscht mit den Zähnen und wird
starr. Ich habe schon deine Jünger gebeten, den Geist auszutreiben, aber
sie hatten nicht die Kraft dazu.

<<v19>>
19 Da sagte er zu ihnen: O du ungläubige Generation! Wie lange muss ich
noch bei euch sein? Wie lange muss ich euch noch ertragen? Bringt ihn zu
mir!

<<v20>>
20 Und man führte ihn herbei. Sobald der Geist Jesus sah, zerrte er den
Jungen hin und her, sodass er hinfiel und sich mit Schaum vor dem Mund
auf dem Boden wälzte.

<<v21>>
21 Jesus fragte den Vater: Wie lange hat er das schon? Der Vater
antwortete: Von Kind auf;

<<v22>>
22 oft hat er ihn sogar ins Feuer oder ins Wasser geworfen, um ihn
umzubringen. Doch wenn du kannst, hilf uns; hab Mitleid mit uns!

<<v23>>
23 Jesus sagte zu ihm: Wenn du kannst? Alles kann, wer glaubt.

<<v24>>
24 Da rief der Vater des Jungen: Ich glaube; hilf meinem Unglauben!

<<v25>>
25 Als Jesus sah, dass die Leute zusammenliefen, drohte er dem unreinen
Geist und sagte: Ich befehle dir, du stummer und tauber Geist: Verlass
ihn und kehr nicht mehr in ihn zurück!

<<v26>>
26 Da zerrte der Geist den Jungen hin und her und verließ ihn mit lautem
Geschrei. Der Junge lag da wie tot, so dass alle Leute sagten: Er ist
gestorben.

<<v27>>
27 Jesus aber fasste ihn an der Hand und richtete ihn auf, und der Junge
erhob sich.

<<v28>>
28 Als Jesus nach Hause kam und sie allein waren, fragten ihn seine
Jünger: Warum konnten denn wir den Dämon nicht austreiben?

<<v29>>
29 Er antwortete ihnen: Diese Art kann nur durch Gebet ausgetrieben
werden. ^{[[#fn12][12]]}\\
\\

<<v30>>
**** Die zweite Ankündigung von Leiden und Auferstehung: 9,30-32
     :PROPERTIES:
     :CUSTOM_ID: die-zweite-ankündigung-von-leiden-und-auferstehung-930-32
     :END:
30 Sie gingen von dort weg und zogen durch Galiläa. Er wollte aber
nicht, dass jemand davon erfuhr; ^{[[#fn13][13]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 164\\
$ŽG://ESyn0812/\\
\\

<<v31>>
31 denn er wollte seine Jünger über etwas belehren. Er sagte zu ihnen:
Der Menschensohn wird den Menschen ausgeliefert und sie werden ihn
töten; doch drei Tage nach seinem Tod wird er auferstehen.
^{[[#fn14][14]]}

<<v32>>
32 Aber sie verstanden den Sinn seiner Worte nicht, scheuten sich
jedoch, ihn zu fragen.\\
\\

<<v33>>
**** Der Rangstreit der Jünger: 9,33-37
     :PROPERTIES:
     :CUSTOM_ID: der-rangstreit-der-jünger-933-37
     :END:
33 Sie kamen nach Kafarnaum. Als er dann im Haus war, fragte er sie:
Worüber habt ihr unterwegs gesprochen? ^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 166\\
$ŽG://ESyn0812/\\
\\

<<v34>>
34 Sie schwiegen, denn sie hatten unterwegs miteinander darüber
gesprochen, wer (von ihnen) der Größte sei. ^{[[#fn16][16]]}

<<v35>>
35 Da setzte er sich, rief die Zwölf und sagte zu ihnen: Wer der Erste
sein will, soll der Letzte von allen und der Diener aller sein.
^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 313\\
$ŽG://ESyn0812/\\
\\

<<v36>>
36 Und er stellte ein Kind in ihre Mitte, nahm es in seine Arme und
sagte zu ihnen:

<<v37>>
37 Wer ein solches Kind um meinetwillen aufnimmt, der nimmt mich auf;
wer aber mich aufnimmt, der nimmt nicht nur mich auf, sondern den, der
mich gesandt hat. ^{[[#fn18][18]]}\\
\\

<<v38>>
**** Der fremde Wundertäter: 9,38-41
     :PROPERTIES:
     :CUSTOM_ID: der-fremde-wundertäter-938-41
     :END:
38 Da sagte Johannes zu ihm: Meister, wir haben gesehen, wie jemand in
deinem Namen Dämonen austrieb; und wir versuchten, ihn daran zu hindern,
weil er uns nicht nachfolgt.
^{[[#fn19][19]][[#fn20][20]][[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 167\\
$ŽG://ESyn0812/\\
\\

<<v39>>
39 Jesus erwiderte: Hindert ihn nicht! Keiner, der in meinem Namen
Wunder tut, kann so leicht schlecht von mir reden.

<<v40>>
40 Denn wer nicht gegen uns ist, der ist für uns.

<<v41>>
41 Wer euch auch nur einen Becher Wasser zu trinken gibt, weil ihr zu
Christus gehört - amen, ich sage euch: er wird nicht um seinen Lohn
kommen. ^{[[#fn22][22]]}\\
^{[[#fn23][23]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 104\\
$ŽG://ESyn0812/

<<v42>>
**** Warnung vor der Verführung: 9,42-48
     :PROPERTIES:
     :CUSTOM_ID: warnung-vor-der-verführung-942-48
     :END:
42 Wer einen von diesen Kleinen, die an mich glauben, zum Bösen
verführt, für den wäre es besser, wenn er mit einem Mühlstein um den
Hals ins Meer geworfen würde.
^{[[#fn24][24]][[#fn25][25]][[#fn26][26]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 168\\
$ŽG://ESyn0812/\\
\\

<<v43>>
43 Wenn dich deine Hand zum Bösen verführt, dann hau sie ab; es ist
besser für dich, verstümmelt in das Leben zu gelangen, als mit zwei
Händen in die Hölle zu kommen, in das nie erlöschende Feuer.
^{[[#fn27][27]]}

<<v44>>
44 [] ^{[[#fn28][28]]}

<<v45>>
45 Und wenn dich dein Fuß zum Bösen verführt, dann hau ihn ab; es ist
besser für dich, verstümmelt in das Leben zu gelangen, als mit zwei
Füßen in die Hölle geworfen zu werden.

<<v46>>
46 []

<<v47>>
47 Und wenn dich dein Auge zum Bösen verführt, dann reiß es aus; es ist
besser für dich, einäugig in das Reich Gottes zu kommen, als mit zwei
Augen in die Hölle geworfen zu werden, ^{[[#fn29][29]]}

<<v48>>
48 /wo ihr Wurm nicht stirbt und das Feuer nicht erlischt./
^{[[#fn30][30]]}\\
\\

<<v49>>
**** Vom Salz: 9,49-50
     :PROPERTIES:
     :CUSTOM_ID: vom-salz-949-50
     :END:
49 Denn jeder wird mit Feuer gesalzen werden.

<<v50>>
50 Das Salz ist etwas Gutes. Wenn das Salz die Kraft zum Salzen
verliert, womit wollt ihr ihm seine Würze wiedergeben? Habt Salz in euch
und haltet Frieden untereinander! ^{[[#fn31][31]]}\\
\\

^{[[#fnm1][1]]} ℘ Mt 10,23; 24,34

^{[[#fnm2][2]]} ℘ ⇨Esyn: Synopse Nr. 367

^{[[#fnm3][3]]} ℘ (2-8) 2 Petr 1,16-18; (2-10) Mt 17,1-9; Lk 9,28-36
⇨Esyn: Synopse Nr. 161

^{[[#fnm4][4]]} 4f.11-13: Vgl. die Anmerkung zu Mt 17,10-13.

^{[[#fnm5][5]]} ℘ Ps 2,7; Jes 42,1; Dtn 18,15; Mt 3,17 ⇨Esyn: Synopse
Nr. 302

^{[[#fnm6][6]]} ℘ Mt 8,4 ⇨Esyn: Synopse Nr. 163

^{[[#fnm7][7]]} ℘ (11-13) Mt 17,10-13 ⇨Esyn: Synopse Nr. 162

^{[[#fnm8][8]]} ℘ Mal 3,23 G; Jes 52,13 - 53,12; Ps 22,2-20

^{[[#fnm9][9]]} ℘ Mt 11,14

^{[[#fnm10][10]]} ℘ (14-29) Mt 17,14-21; Lk 9,37-42

^{[[#fnm11][11]]} Einige Textzeugen haben: Als er . . . zurückkam, sah
er.

^{[[#fnm12][12]]} Einige Textzeugen fügen nach «Gebet» hinzu: und
Fasten.

^{[[#fnm13][13]]} ℘ Lk 17,11; (30-32) Mt 17,22f; Lk 9,43b-45 ⇨Esyn:
Synopse Nr. 164

^{[[#fnm14][14]]} ℘ 8,31; 10,33

^{[[#fnm15][15]]} ℘ (33-37) Mt 18,1-5; Lk 9,46-48 ⇨Esyn: Synopse Nr. 166

^{[[#fnm16][16]]} ℘ Lk 22,24-26

^{[[#fnm17][17]]} ℘ 10,43; Mt 20,26f; Lk 22,26 ⇨Esyn: Synopse Nr. 313

^{[[#fnm18][18]]} um meinetwillen, wörtlich: aufgrund meines Namens.

^{[[#fnm19][19]]} ℘ (38-40) Lk 9,49f

^{[[#fnm20][20]]} Manche Textzeugen fügen nach «jemand» hinzu: der uns
nicht nachfolgt.

^{[[#fnm21][21]]} ℘ ⇨Esyn: Synopse Nr. 167

^{[[#fnm22][22]]} ℘ Mt 10,42

^{[[#fnm23][23]]} ℘ ⇨Esyn: Synopse Nr. 104

^{[[#fnm24][24]]} ℘ (42-48) Mt 18,6-9; Lk 17,1f

^{[[#fnm25][25]]} 42-48: Vgl. die Anmerkung zu Mt 18,6 und 18,8f. «an
mich» fehlt bei manchen alten Textzeugen.

^{[[#fnm26][26]]} ℘ ⇨Esyn: Synopse Nr. 168

^{[[#fnm27][27]]} ℘ Mt 5,30

^{[[#fnm28][28]]} 44.46: Spätere Textzeugen fügen entsprechend 9,48 hier
ein: wo ihr Wurm nicht stirbt und das Feuer nicht erlischt.

^{[[#fnm29][29]]} ℘ Mt 5,29

^{[[#fnm30][30]]} ℘ Jes 66,24

^{[[#fnm31][31]]} ℘ Mt 5,13; Lk 14,34f
