:PROPERTIES:
:ID:       4155e42e-efd6-423a-bb87-79726f87528c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_13.html][13]]
[[file:Mt_14.html][14]] *15* [[file:Mt_16.html][16]]
[[file:Mt_17.html][17]] ... [[file:Mt_28.html][28]]

--------------

* Mt 15
  :PROPERTIES:
  :CUSTOM_ID: mt-15
  :END:

<<verses>>

<<v1>>
**** Von Reinheit und Unreinheit: 15,1-20
     :PROPERTIES:
     :CUSTOM_ID: von-reinheit-und-unreinheit-151-20
     :END:
1 Da kamen von Jerusalem Pharisäer und Schriftgelehrte zu Jesus und
sagten: ^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 150\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Warum missachten deine Jünger die Überlieferung der Alten? Denn sie
waschen sich nicht die Hände vor dem Essen. ^{[[#fn4][4]]}

<<v3>>
3 Er entgegnete ihnen: Warum missachtet denn ihr Gottes Gebot um eurer
Überlieferung willen?

<<v4>>
4 Gott hat gesagt: /Ehre Vater und Mutter!,/ und: /Wer Vater oder Mutter
verflucht, soll mit dem Tod bestraft werden./ ^{[[#fn5][5]]}

<<v5>>
5 Ihr aber lehrt: Wer zu Vater oder Mutter sagt: Was ich dir schulde,
erkläre ich zur Opfergabe!, ^{[[#fn6][6]]}

<<v6>>
6 der braucht seinen Vater oder seine Mutter nicht mehr zu ehren. Damit
habt ihr Gottes Wort um eurer Überlieferung willen außer Kraft gesetzt.
^{[[#fn7][7]]}

<<v7>>
7 Ihr Heuchler! Der Prophet Jesaja hatte Recht, als er über euch
sagte:\\
\\

<<v8>>
8 /Dieses Volk ehrt mich mit den Lippen,/ /\\
 /sein Herz aber ist weit weg von mir./ ^{[[#fn8][8]]}\\
\\

<<v9>>
9 /Es ist sinnlos, wie sie mich verehren;/ /\\
 /was sie lehren, sind Satzungen von Menschen./

<<v10>>
10 Und er rief die Leute zu sich und sagte: Hört und begreift:

<<v11>>
11 Nicht das, was durch den Mund in den Menschen hineinkommt, macht ihn
unrein, sondern was aus dem Mund des Menschen herauskommt, das macht ihn
unrein. ^{[[#fn9][9]]}

<<v12>>
12 Da kamen die Jünger zu ihm und sagten: Weißt du, dass die Pharisäer
über deine Worte empört sind?

<<v13>>
13 Er antwortete ihnen: Jede Pflanze, die nicht mein himmlischer Vater
gepflanzt hat, wird ausgerissen werden.

<<v14>>
14 Lasst sie, es sind blinde Blindenführer. Und wenn ein Blinder einen
Blinden führt, werden beide in eine Grube fallen. ^{[[#fn10][10]]}

<<v15>>
15 Da sagte Petrus zu ihm: Erkläre uns jenes rätselhafte Wort!

<<v16>>
16 Er antwortete: Seid auch ihr noch immer ohne Einsicht?

<<v17>>
17 Begreift ihr nicht, dass alles, was durch den Mund (in den Menschen)
hineinkommt, in den Magen gelangt und dann wieder ausgeschieden wird?

<<v18>>
18 Was aber aus dem Mund herauskommt, das kommt aus dem Herzen, und das
macht den Menschen unrein.

<<v19>>
19 Denn aus dem Herzen kommen böse Gedanken, Mord, Ehebruch, Unzucht,
Diebstahl, falsche Zeugenaussagen und Verleumdungen.
^{[[#fn11][11]][[#fn12][12]]}

<<v20>>
20 Das ist es, was den Menschen unrein macht; aber mit ungewaschenen
Händen essen macht ihn nicht unrein.\\
\\

<<v21>>
**** Die Erhörung der Bitte einer heidnischen Frau: 15,21-28
     :PROPERTIES:
     :CUSTOM_ID: die-erhörung-der-bitte-einer-heidnischen-frau-1521-28
     :END:
21 Von dort zog sich Jesus in das Gebiet von Tyrus und Sidon zurück.
^{[[#fn13][13]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 151\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 Da kam eine kanaanäische Frau aus jener Gegend zu ihm und rief: Hab
Erbarmen mit mir, Herr, du Sohn Davids! Meine Tochter wird von einem
Dämon gequält. ^{[[#fn14][14]]}

<<v23>>
23 Jesus aber gab ihr keine Antwort. Da traten seine Jünger zu ihm und
baten: Befrei sie (von ihrer Sorge), denn sie schreit hinter uns her.
^{[[#fn15][15]]}

<<v24>>
24 Er antwortete: Ich bin nur zu den verlorenen Schafen des Hauses
Israel gesandt. ^{[[#fn16][16]]}

<<v25>>
25 Doch die Frau kam, fiel vor ihm nieder und sagte: Herr, hilf mir!

<<v26>>
26 Er erwiderte: Es ist nicht recht, das Brot den Kindern wegzunehmen
und den Hunden vorzuwerfen.

<<v27>>
27 Da entgegnete sie: Ja, du hast recht, Herr! Aber selbst die Hunde
bekommen von den Brotresten, die vom Tisch ihrer Herren fallen.

<<v28>>
28 Darauf antwortete ihr Jesus: Frau, dein Glaube ist groß. Was du
willst, soll geschehen. Und von dieser Stunde an war ihre Tochter
geheilt.\\
\\

<<v29>>
**** Die Heilung vieler Kranker: 15,29-31
     :PROPERTIES:
     :CUSTOM_ID: die-heilung-vieler-kranker-1529-31
     :END:
29 Jesus zog weiter und kam an den See von Galiläa. Er stieg auf einen
Berg und setzte sich. ^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 152\\
$ŽG://ESyn0812/\\
\\

<<v30>>
30 Da kamen viele Menschen und brachten Lahme, Krüppel, Blinde, Stumme
und viele andere Kranke zu ihm; sie legten sie vor ihn hin, und er
heilte sie.

<<v31>>
31 Als die Menschen sahen, dass Stumme plötzlich redeten, Krüppel gesund
wurden, Lahme gehen und Blinde sehen konnten, waren sie erstaunt und
priesen den Gott Israels.\\
\\

<<v32>>
**** Die Speisung der Viertausend: 15,32-39
     :PROPERTIES:
     :CUSTOM_ID: die-speisung-der-viertausend-1532-39
     :END:
32 Jesus rief seine Jünger zu sich und sagte: Ich habe Mitleid mit
diesen Menschen; sie sind schon drei Tage bei mir und haben nichts mehr
zu essen. Ich will sie nicht hungrig wegschicken, sonst brechen sie
unterwegs zusammen. ^{[[#fn18][18]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 153\\
$ŽG://ESyn0812/\\
\\

<<v33>>
33 Da sagten die Jünger zu ihm: Wo sollen wir in dieser unbewohnten
Gegend so viel Brot hernehmen, um so viele Menschen satt zu machen?

<<v34>>
34 Jesus sagte zu ihnen: Wie viele Brote habt ihr? Sie antworteten:
Sieben, und noch ein paar Fische.

<<v35>>
35 Da forderte er die Leute auf, sich auf den Boden zu setzen.

<<v36>>
36 Und er nahm die sieben Brote und die Fische, sprach das Dankgebet,
brach die Brote und gab sie den Jüngern und die Jünger verteilten sie an
die Leute.

<<v37>>
37 Und alle aßen und wurden satt. Dann sammelte man die übrig
gebliebenen Brotstücke ein, sieben Körbe voll.

<<v38>>
38 Es waren viertausend Männer, die an dem Mahl teilgenommen hatten,
dazu noch Frauen und Kinder.

<<v39>>
39 Danach schickte er die Menge nach Hause, stieg ins Boot und fuhr in
die Gegend von Magadan. ^{[[#fn19][19]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-20) Mk 7,1-23

^{[[#fnm2][2]]} 1f: Über die Reinheitsvorschriften der Pharisäer und
Schriftgelehrten vgl. Mk 7,1-4 und die dortige Anmerkung.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 150

^{[[#fnm4][4]]} ℘ Lk 11,38; Kol 2,21f

^{[[#fnm5][5]]} ℘ Ex 20,12; 21,17; Dtn 5,16; Lev 20,9

^{[[#fnm6][6]]} 5f: Über das Korbán-Gelübde vgl. die Anmerkung zu Mk 7,
9-13.

^{[[#fnm7][7]]} Gottes Wort, nach anderen Textzeugen: Gottes Gesetz.

^{[[#fnm8][8]]} ℘ Jes 29,13 G

^{[[#fnm9][9]]} In diesem wichtigen Satz wird der Wert jeder religiösen
Verhaltensweise und Handlung von der Gesinnung des Handelnden abhängig
gemacht, nicht vom äußeren Vollzug. Es gibt also keine Sünde ohne böse
Gesinnung.

^{[[#fnm10][10]]} ℘ 23,16.24; Lk 6,39

^{[[#fnm11][11]]} ℘ Röm 1,29-31; 1 Kor 5,10f; Gal 5,19-21; Eph 5,3-5;
Kol 3,5; 1 Tim 1,9f; 2 Tim 3,2-4; 1 Petr 4,3

^{[[#fnm12][12]]} Vgl. die Anmerkung zu Mk 7,21.

^{[[#fnm13][13]]} ℘ (21-28) Mk 7,24-30 ⇨Esyn: Synopse Nr. 151

^{[[#fnm14][14]]} ℘ 9,27

^{[[#fnm15][15]]} Befrei sie (von ihrer Sorge), andere
Übersetzungsmöglichkeit: Schick sie weg.

^{[[#fnm16][16]]} ℘ 10,6

^{[[#fnm17][17]]} ℘ (29-31) Mk 7,31-37 ⇨Esyn: Synopse Nr. 152

^{[[#fnm18][18]]} ℘ (32-39) 14,13-21; Mk 6,32-44; Lk 9,10-17; Joh
6,1-13; Mk 8,1-10 ⇨Esyn: Synopse Nr. 153

^{[[#fnm19][19]]} Die genaue Lage dieses Ortes ist nicht bekannt. Ein
Teil späterer Textzeugen nennt hier Magdala, das westlich von Kafarnaum
in einer Bucht des Sees von Gennesaret lag.
