:PROPERTIES:
:ID:       e918a9c2-ae0d-4399-bec3-da403d6319c6
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_14.html][14]]
[[file:Mt_15.html][15]] *16* [[file:Mt_17.html][17]]
[[file:Mt_18.html][18]] ... [[file:Mt_28.html][28]]

--------------

* Mt 16
  :PROPERTIES:
  :CUSTOM_ID: mt-16
  :END:

<<verses>>

<<v1>>
**** Die Verweigerung eines Zeichens: 16,1-4
     :PROPERTIES:
     :CUSTOM_ID: die-verweigerung-eines-zeichens-161-4
     :END:
1 Da kamen die Pharisäer und Sadduzäer zu Jesus, um ihn auf die Probe zu
stellen. Sie baten ihn: Lass uns ein Zeichen vom Himmel sehen.
^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 154\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Er antwortete ihnen: ^{[[#fn2][2]]}

<<v3>>
3 []

<<v4>>
4 Diese böse und treulose Generation fordert ein Zeichen, aber es wird
ihr kein anderes gegeben werden als das Zeichen des Jona. Und er ließ
sie stehen und ging weg. ^{[[#fn3][3]]}\\
\\

<<v5>>
**** Warnung vor den Pharisäern und Sadduzäern: 16,5-12
     :PROPERTIES:
     :CUSTOM_ID: warnung-vor-den-pharisäern-und-sadduzäern-165-12
     :END:
5 Die Jünger fuhren an das andere Ufer. Sie hatten aber vergessen, Brot
mitzunehmen. ^{[[#fn4][4]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 155\\
$ŽG://ESyn0812/\\
\\

<<v6>>
6 Und Jesus sagte zu ihnen: Gebt Acht, hütet euch vor dem Sauerteig der
Pharisäer und Sadduzäer! ^{[[#fn5][5]]}

<<v7>>
7 Sie aber machten sich Gedanken und sagten zueinander: Wir haben kein
Brot mitgenommen.

<<v8>>
8 Als Jesus das merkte, sagte er: Ihr Kleingläubigen, was macht ihr euch
darüber Gedanken, dass ihr kein Brot habt? ^{[[#fn6][6]]}

<<v9>>
9 Begreift ihr immer noch nicht? Erinnert ihr euch nicht an die fünf
Brote für die Fünftausend und daran, wie viele Körbe voll ihr wieder
eingesammelt habt? ^{[[#fn7][7]]}

<<v10>>
10 Auch nicht an die sieben Brote für die Viertausend, und wie viele
Körbe voll ihr da eingesammelt habt? ^{[[#fn8][8]]}

<<v11>>
11 Warum begreift ihr denn nicht, dass ich nicht von Brot gesprochen
habe, als ich zu euch sagte: Hütet euch vor dem Sauerteig der Pharisäer
und Sadduzäer?

<<v12>>
12 Da verstanden sie, dass er nicht gemeint hatte, sie sollten sich vor
dem Sauerteig hüten, mit dem man Brot backt, sondern vor der Lehre der
Pharisäer und Sadduzäer.\\
\\

<<v13>>
**** Das Messiasbekenntnis des Petrus und die Antwort Jesu: 16,13-20
     :PROPERTIES:
     :CUSTOM_ID: das-messiasbekenntnis-des-petrus-und-die-antwort-jesu-1613-20
     :END:
13 Als Jesus in das Gebiet von Cäsarea Philippi kam, fragte er seine
Jünger: Für wen halten die Leute den Menschensohn?
^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 158\\
$ŽG://ESyn0812/\\
\\

<<v14>>
14 Sie sagten: Die einen für Johannes den Täufer, andere für Elija,
wieder andere für Jeremia oder sonst einen Propheten. ^{[[#fn10][10]]}

<<v15>>
15 Da sagte er zu ihnen: Ihr aber, für wen haltet ihr mich?

<<v16>>
16 Simon Petrus antwortete: Du bist der Messias, der Sohn des lebendigen
Gottes! ^{[[#fn11][11]]}

<<v17>>
17 Jesus sagte zu ihm: Selig bist du, Simon Barjona; denn nicht Fleisch
und Blut haben dir das offenbart, sondern mein Vater im Himmel.

<<v18>>
18 Ich aber sage dir: Du bist Petrus und auf diesen Felsen werde ich
meine Kirche bauen und die Mächte der Unterwelt werden sie nicht
überwältigen. ^{[[#fn12][12]][[#fn13][13]]}

<<v19>>
19 Ich werde dir die Schlüssel des Himmelreichs geben; was du auf Erden
binden wirst, das wird auch im Himmel gebunden sein, und was du auf
Erden lösen wirst, das wird auch im Himmel gelöst sein. ^{[[#fn14][14]]}

<<v20>>
20 Dann befahl er den Jüngern, niemand zu sagen, dass er der Messias
sei.\\
\\

<<v21>>
**** Die erste Ankündigung von Leiden und Auferstehung: 16,21-23
     :PROPERTIES:
     :CUSTOM_ID: die-erste-ankündigung-von-leiden-und-auferstehung-1621-23
     :END:
21 Von da an begann Jesus, seinen Jüngern zu erklären, er müsse nach
Jerusalem gehen und von den Ältesten, den Hohenpriestern und den
Schriftgelehrten vieles erleiden; er werde getötet werden, aber am
dritten Tag werde er auferstehen. ^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 159\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 Da nahm ihn Petrus beiseite und machte ihm Vorwürfe; er sagte: Das
soll Gott verhüten, Herr! Das darf nicht mit dir geschehen!

<<v23>>
23 Jesus aber wandte sich um und sagte zu Petrus: Weg mit dir, Satan,
geh mir aus den Augen! Du willst mich zu Fall bringen; denn du hast
nicht das im Sinn, was Gott will, sondern was die Menschen wollen.\\
\\

<<v24>>
**** Von Nachfolge und Selbstverleugnung: 16,24-28
     :PROPERTIES:
     :CUSTOM_ID: von-nachfolge-und-selbstverleugnung-1624-28
     :END:
24 Darauf sagte Jesus zu seinen Jüngern: Wer mein Jünger sein will, der
verleugne sich selbst, nehme sein Kreuz auf sich und folge mir nach.
^{[[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 160\\
$ŽG://ESyn0812/\\
\\

<<v25>>
25 Denn wer sein Leben retten will, wird es verlieren; wer aber sein
Leben um meinetwillen verliert, wird es gewinnen. ^{[[#fn17][17]]}

<<v26>>
26 Was nützt es einem Menschen, wenn er die ganze Welt gewinnt, dabei
aber sein Leben einbüßt? Um welchen Preis kann ein Mensch sein Leben
zurückkaufen?

<<v27>>
27 Der Menschensohn wird mit seinen Engeln in der Hoheit seines Vaters
kommen und /jedem/ Menschen /vergelten, wie es seine Taten verdienen./
^{[[#fn18][18]]}

<<v28>>
28 Amen, ich sage euch: Von denen, die hier stehen, werden einige den
Tod nicht erleiden, bis sie den Menschensohn in seiner königlichen Macht
kommen sehen. ^{[[#fn19][19]]}\\
\\

^{[[#fnm1][1]]} ℘ 12,38f; Lk 11,16.29-32; Joh 6,30; (1-4) Mk 8,11-13
⇨Esyn: Synopse Nr. 154

^{[[#fnm2][2]]} 2b-3: Spätere Textzeugen fügen hier ein: Am Abend sagt
ihr: Es kommt schönes Wetter, denn der Himmel ist rot. Und am Morgen:
Heute gibt es Sturm, denn der Himmel ist rot und trüb. Das Aussehen des
Himmels könnt ihr beurteilen, die Zeichen der Zeit aber nicht.

^{[[#fnm3][3]]} Zu «treulose» vgl. die Anmerkung zu Mt 12,39.

^{[[#fnm4][4]]} ℘ (5-12) Mk 8,14-21 ⇨Esyn: Synopse Nr. 155

^{[[#fnm5][5]]} ℘ Lk 12,1

^{[[#fnm6][6]]} ℘ Mk 6,52

^{[[#fnm7][7]]} ℘ 14,21; Mk 6,44f

^{[[#fnm8][8]]} ℘ 15,38; Mk 8,9

^{[[#fnm9][9]]} ℘ (13-20) Mk 8,27-30; Lk 9,18-21 ⇨Esyn: Synopse Nr. 158

^{[[#fnm10][10]]} ℘ 14,2; Mk 6,14f; Lk 9,7f

^{[[#fnm11][11]]} ℘ 14,33; 27,54; Mk 15,39; Joh 1,49; 11,27

^{[[#fnm12][12]]} ℘ Joh 1,42; Ijob 38,17; Weish 16,13; Jes 38,10

^{[[#fnm13][13]]} Das dem Beinamen Petrus zugrunde liegende griechische
Wort petra bedeutet «Fels». - «die Mächte der Unterwelt», wörtlich: «die
Pforten des Hades». Hades, hebräisch Scheol, bezeichnete damals den als
Gebäude, Festungsanlage gedachten Bereich des Todes, aller Toten. Die
Totenwelt, die man sich unter der Erde befindlich vorstellte, war jedoch
nicht der Aufenthaltsort Satans oder der Dämonen. Die Pforten oder Tore
des Hades sind ein Bild für die alles verschlingende Macht des Todes und
der Vergänglichkeit.

^{[[#fnm14][14]]} ℘ 18,18; Joh 20,23; 21,15-17

^{[[#fnm15][15]]} ℘ 17,22f; 20,18f; 26,2; Mk 9,31; 10,32-34; Lk 9,44;
18,31-33; (21-23) Mk 8,31-33; Lk 9,22 ⇨Esyn: Synopse Nr. 159

^{[[#fnm16][16]]} ℘ 10,38f; Lk 14,27; (24-28) Mk 8,34 - 9,1; Lk 9,23-27
⇨Esyn: Synopse Nr. 160

^{[[#fnm17][17]]} ℘ 10,39; Lk 17,33; Joh 12,25

^{[[#fnm18][18]]} ℘ Ps 62,13; 28,4

^{[[#fnm19][19]]} ℘ 10,23; 24,34
