:PROPERTIES:
:ID:       927958ae-87fc-4891-82d5-7e87c6468e9b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_16.html][16]]
[[file:Mt_17.html][17]] *18* [[file:Mt_19.html][19]]
[[file:Mt_20.html][20]] ... [[file:Mt_28.html][28]]

--------------

* Mt 18
  :PROPERTIES:
  :CUSTOM_ID: mt-18
  :END:

<<verses>>

<<v1>>
*** Die Rede über das Leben in der Gemeinde: 18,1-35
    :PROPERTIES:
    :CUSTOM_ID: die-rede-über-das-leben-in-der-gemeinde-181-35
    :END:
**** Der Rangstreit der Jünger: 18,1-5
     :PROPERTIES:
     :CUSTOM_ID: der-rangstreit-der-jünger-181-5
     :END:
1 In jener Stunde kamen die Jünger zu Jesus und fragten: Wer ist im
Himmelreich der Größte?
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 166\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Da rief er ein Kind herbei, stellte es in ihre Mitte

<<v3>>
3 und sagte: Amen, das sage ich euch: Wenn ihr nicht umkehrt und wie die
Kinder werdet, könnt ihr nicht in das Himmelreich kommen. ^{[[#fn4][4]]}

<<v4>>
4 Wer so klein sein kann wie dieses Kind, der ist im Himmelreich der
Größte.

<<v5>>
5 Und wer ein solches Kind um meinetwillen aufnimmt, der nimmt mich auf.
^{[[#fn5][5]]}\\
\\

<<v6>>
**** Warnung vor der Verführung und der Verachtung von Jüngern: 18,6-11
     :PROPERTIES:
     :CUSTOM_ID: warnung-vor-der-verführung-und-der-verachtung-von-jüngern-186-11
     :END:
6 Wer einen von diesen Kleinen, die an mich glauben, zum Bösen verführt,
für den wäre es besser, wenn er mit einem Mühlstein um den Hals im
tiefen Meer versenkt würde.
^{[[#fn6][6]][[#fn7][7]][[#fn8][8]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 168\\
$ŽG://ESyn0812/\\
\\

<<v7>>
7 Wehe der Welt mit ihrer Verführung! Es muss zwar Verführung geben;
doch wehe dem Menschen, der sie verschuldet.

<<v8>>
8 Wenn dich deine Hand oder dein Fuß zum Bösen verführt, dann hau sie ab
und wirf sie weg! Es ist besser für dich, verstümmelt oder lahm in das
Leben zu gelangen, als mit zwei Händen und zwei Füßen in das ewige Feuer
geworfen zu werden. ^{[[#fn9][9]][[#fn10][10]]}

<<v9>>
9 Und wenn dich dein Auge zum Bösen verführt, dann reiß es aus und wirf
es weg! Es ist besser für dich, einäugig in das Leben zu gelangen, als
mit zwei Augen in das Feuer der Hölle geworfen zu werden.
^{[[#fn11][11]]}

<<v10>>
10 Hütet euch davor, einen von diesen Kleinen zu verachten! Denn ich
sage euch: Ihre Engel im Himmel sehen stets das Angesicht meines
himmlischen Vaters. ^{[[#fn12][12]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 169\\
$ŽG://ESyn0812/\\
\\

<<v11>>
11 [] ^{[[#fn13][13]]}\\
\\

<<v12>>
**** Das Gleichnis vom verlorenen Schaf: 18,12-14
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-verlorenen-schaf-1812-14
     :END:
12 Was meint ihr? Wenn jemand hundert Schafe hat und eines von ihnen
sich verirrt, lässt er dann nicht die neunundneunzig auf den Bergen
zurück und sucht das verirrte? ^{[[#fn14][14]]}

<<v13>>
13 Und wenn er es findet - amen, ich sage euch: er freut sich über
dieses eine mehr als über die neunundneunzig, die sich nicht verirrt
haben.

<<v14>>
14 So will auch euer himmlischer Vater nicht, dass einer von diesen
Kleinen verloren geht.\\
\\

<<v15>>
**** Von der Verantwortung für den Bruder: 18,15-20
     :PROPERTIES:
     :CUSTOM_ID: von-der-verantwortung-für-den-bruder-1815-20
     :END:
15 Wenn dein Bruder sündigt, dann geh zu ihm und weise ihn unter vier
Augen zurecht. Hört er auf dich, so hast du deinen Bruder
zurückgewonnen. ^{[[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 170\\
$ŽG://ESyn0812/\\
\\

<<v16>>
16 Hört er aber nicht auf dich, dann nimm einen oder zwei Männer mit,
denn /jede Sache muss durch die Aussage von zwei oder drei Zeugen
entschieden werden./ ^{[[#fn16][16]]}

<<v17>>
17 Hört er auch auf sie nicht, dann sag es der Gemeinde. Hört er aber
auch auf die Gemeinde nicht, dann sei er für dich wie ein Heide oder ein
Zöllner. ^{[[#fn17][17]]}

<<v18>>
18 Amen, ich sage euch: Alles, was ihr auf Erden binden werdet, das wird
auch im Himmel gebunden sein und alles, was ihr auf Erden lösen werdet,
das wird auch im Himmel gelöst sein. ^{[[#fn18][18]]}

<<v19>>
19 Weiter sage ich euch: Alles, was zwei von euch auf Erden gemeinsam
erbitten, werden sie von meinem himmlischen Vater erhalten.
^{[[#fn19][19]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 171\\
$ŽG://ESyn0812/\\
\\

<<v20>>
20 Denn wo zwei oder drei in meinem Namen versammelt sind, da bin ich
mitten unter ihnen. ^{[[#fn20][20]]}\\
\\

<<v21>>
**** Von der Pflicht zur Vergebung: 18,21-22
     :PROPERTIES:
     :CUSTOM_ID: von-der-pflicht-zur-vergebung-1821-22
     :END:
21 Da trat Petrus zu ihm und fragte: Herr, wie oft muss ich meinem
Bruder vergeben, wenn er sich gegen mich versündigt? Siebenmal?
^{[[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 172\\
$ŽG://ESyn0812/\\
\\

<<v22>>
22 Jesus sagte zu ihm: Nicht /siebenmal,/ sondern /siebenundsiebzigmal./
^{[[#fn22][22]][[#fn23][23]]}\\
\\

<<v23>>
**** Das Gleichnis vom unbarmherzigen Gläubiger: 18,23-35
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-unbarmherzigen-gläubiger-1823-35
     :END:
23 Mit dem Himmelreich ist es deshalb wie mit einem König, der
beschloss, von seinen Dienern Rechenschaft zu verlangen.
^{[[#fn24][24]][[#fn25][25]][[#fn26][26]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 173\\
$ŽG://ESyn0812/\\
\\

<<v24>>
24 Als er nun mit der Abrechnung begann, brachte man einen zu ihm, der
ihm zehntausend Talente schuldig war.

<<v25>>
25 Weil er aber das Geld nicht zurückzahlen konnte, befahl der Herr, ihn
mit Frau und Kindern und allem, was er besaß, zu verkaufen und so die
Schuld zu begleichen.

<<v26>>
26 Da fiel der Diener vor ihm auf die Knie und bat: Hab Geduld mit mir!
Ich werde dir alles zurückzahlen.

<<v27>>
27 Der Herr hatte Mitleid mit dem Diener, ließ ihn gehen und schenkte
ihm die Schuld. ^{[[#fn27][27]]}

<<v28>>
28 Als nun der Diener hinausging, traf er einen anderen Diener seines
Herrn, der ihm hundert Denare schuldig war. Er packte ihn, würgte ihn
und rief: Bezahl, was du mir schuldig bist!

<<v29>>
29 Da fiel der andere vor ihm nieder und flehte: Hab Geduld mit mir! Ich
werde es dir zurückzahlen.

<<v30>>
30 Er aber wollte nicht, sondern ging weg und ließ ihn ins Gefängnis
werfen, bis er die Schuld bezahlt habe.

<<v31>>
31 Als die übrigen Diener das sahen, waren sie sehr betrübt; sie gingen
zu ihrem Herrn und berichteten ihm alles, was geschehen war.

<<v32>>
32 Da ließ ihn sein Herr rufen und sagte zu ihm: Du elender Diener!
Deine ganze Schuld habe ich dir erlassen, weil du mich so angefleht
hast.

<<v33>>
33 Hättest nicht auch du mit jenem, der gemeinsam mit dir in meinem
Dienst steht, Erbarmen haben müssen, so wie ich mit dir Erbarmen hatte?

<<v34>>
34 Und in seinem Zorn übergab ihn der Herr den Folterknechten, bis er
die ganze Schuld bezahlt habe.

<<v35>>
35 Ebenso wird mein himmlischer Vater jeden von euch behandeln, der
seinem Bruder nicht von ganzem Herzen vergibt. ^{[[#fn28][28]]}\\
\\

^{[[#fnm1][1]]} ℘ Lk 22,24-26; (1-5) Mk 9,33-37; Lk 9,46-48

^{[[#fnm2][2]]} 1-4: Das Kind galt zur Zeit Jesu als unfertiger
Erwachsener und spielte in der damaligen Gesellschaft keine Rolle.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 166

^{[[#fnm4][4]]} ℘ 19,14; Mk 10,15; Lk 18,17

^{[[#fnm5][5]]} um meinetwillen, wörtlich: aufgrund meines Namens.

^{[[#fnm6][6]]} ℘ (6-9) Mk 9,42-47; Lk 17,1f

^{[[#fnm7][7]]} 6.10.14: Der Ausdruck «diese Kleinen» knüpft zwar an die
zuvor genannten Kinder an, wird aber nun zur Bezeichnung der Christen:
sie sind wenig angesehen, machtlos und auf (Gottes) Hilfe angewiesen.

^{[[#fnm8][8]]} ℘ ⇨Esyn: Synopse Nr. 168

^{[[#fnm9][9]]} ℘ 5,30

^{[[#fnm10][10]]} 8f: Nach jüdischer Auffassung saß die Begierde in den
einzelnen Gliedern. Darum wurde bei den Juden z. B. Diebstahl durch
Abhauen der Hand geahndet. Als Ort der ewigen Strafe galt dem Judentum
die Feuerhölle, die Gehenna, wo die Bösen nach dem Endgericht ewige Qual
erleiden werden (vgl. Jes 66,24; Offb 20,14f).

^{[[#fnm11][11]]} ℘ 5,29

^{[[#fnm12][12]]} ℘ ⇨Esyn: Synopse Nr. 169

^{[[#fnm13][13]]} Ein Teil der Textzeugen fügt hier ein: Denn der
Menschensohn ist gekommen, um zu retten, was verloren ist; vgl. Lk
19,10.

^{[[#fnm14][14]]} ℘ Joh 10,11-15; (12-14) Lk 15,4-7

^{[[#fnm15][15]]} ℘ Lev 19,17; Lk 17,3 ⇨Esyn: Synopse Nr. 170

^{[[#fnm16][16]]} ℘ Dtn 19,15

^{[[#fnm17][17]]} Mit «Gemeinde» ist die Ortskirche gemeint.

^{[[#fnm18][18]]} ℘ 16,19; Joh 20,23

^{[[#fnm19][19]]} ℘ 7,7 ⇨Esyn: Synopse Nr. 171

^{[[#fnm20][20]]} ℘ 28,20

^{[[#fnm21][21]]} ℘ ⇨Esyn: Synopse Nr. 172

^{[[#fnm22][22]]} ℘ Gen 4,24; Lk 17,4

^{[[#fnm23][23]]} Der griechische Text ist zu übersetzen mit
«siebenundsiebzigmal», nicht mit siebzigmal siebenmal wie in manchen
Übersetzungen. Der Ausdruck hat den Sinn: immer, ohne Einschränkung.

^{[[#fnm24][24]]} ℘ 25,19

^{[[#fnm25][25]]} 23-25: Ein Talent (griechische Rechnungseinheit)
entsprach sechstausend Drachmen. Ein Denar war damals einer Drachme
gleichwertig und war der Tageslohn eines Arbeiters. Die Schuld umfasste
also eine ungeheure Summe, die kaum aufzubringen war. Die
Jahreseinkünfte Herodes' des Großen betrugen 900 Talente, das
Steueraufkommen von ganz Galiläa und Peräa im Jahr 4 n. Chr. 200
Talente. Unter dem «Diener» kann man sich etwa den Finanzminister eines
orientalischen Königs vorstellen, dessen Beamte als Sklaven oder Diener
des Herrschers angesehen wurden. Die Folter diente dazu, Auskünfte über
beiseite geschafftes Geld zu erlangen.

^{[[#fnm26][26]]} ℘ ⇨Esyn: Synopse Nr. 173

^{[[#fnm27][27]]} ℘ Lk 7,42

^{[[#fnm28][28]]} ℘ 6,15
