:PROPERTIES:
:ID:       bdd86f1e-d7aa-4c5a-9f05-20825f6af740
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_17.html][17]]
[[file:Mt_18.html][18]] *19* [[file:Mt_20.html][20]]
[[file:Mt_21.html][21]] ... [[file:Mt_28.html][28]]

--------------

* Mt 19
  :PROPERTIES:
  :CUSTOM_ID: mt-19
  :END:

<<verses>>

<<v1>>
** Jesu Wirken in Judäa und in Jerusalem: 19,1 - 25,46
   :PROPERTIES:
   :CUSTOM_ID: jesu-wirken-in-judäa-und-in-jerusalem-191---2546
   :END:
*** Der Weg nach Jerusalem: 19,1 - 20,34
    :PROPERTIES:
    :CUSTOM_ID: der-weg-nach-jerusalem-191---2034
    :END:
**** Aufbruch nach Judäa: 19,1-2
     :PROPERTIES:
     :CUSTOM_ID: aufbruch-nach-judäa-191-2
     :END:
1 Als Jesus diese Reden beendet hatte, verließ er Galiläa und zog in das
Gebiet von Judäa jenseits des Jordan. ^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 251\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Viele Menschen folgten ihm dorthin und er heilte sie.\\
\\

<<v3>>
**** Von Ehescheidung und Ehelosigkeit: 19,3-12
     :PROPERTIES:
     :CUSTOM_ID: von-ehescheidung-und-ehelosigkeit-193-12
     :END:
3 Da kamen Pharisäer zu ihm, die ihm eine Falle stellen wollten, und
fragten: Darf man seine Frau aus jedem beliebigen Grund aus der Ehe
entlassen? ^{[[#fn2][2]][[#fn3][3]][[#fn4][4]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 252\\
$ŽG://ESyn0812/\\
\\

<<v4>>
4 Er antwortete: Habt ihr nicht gelesen, dass der Schöpfer die Menschen
am Anfang /als Mann und Frau geschaffen hat/ ^{[[#fn5][5]][[#fn6][6]]}

<<v5>>
5 und dass er gesagt hat: /Darum wird der Mann Vater und Mutter
verlassen und sich an seine Frau binden und die zwei werden/ *ein*
/Fleisch sein?/ ^{[[#fn7][7]]}

<<v6>>
6 Sie sind also nicht mehr zwei, sondern eins. Was aber Gott verbunden
hat, das darf der Mensch nicht trennen.

<<v7>>
7 Da sagten sie zu ihm: Wozu hat dann Mose vorgeschrieben, dass man (der
Frau) /eine Scheidungsurkunde geben muss,/ wenn man sich trennen will?
^{[[#fn8][8]]}

<<v8>>
8 Er antwortete: Nur weil ihr so hartherzig seid, hat Mose euch erlaubt,
eure Frauen aus der Ehe zu entlassen. Am Anfang war das nicht so.

<<v9>>
9 Ich sage euch: Wer seine Frau entlässt, obwohl kein Fall von Unzucht
vorliegt, und eine andere heiratet, der begeht Ehebruch.
^{[[#fn9][9]][[#fn10][10]]}

<<v10>>
10 Da sagten die Jünger zu ihm: Wenn das die Stellung des Mannes in der
Ehe ist, dann ist es nicht gut zu heiraten.

<<v11>>
11 Jesus sagte zu ihnen: Nicht alle können dieses Wort erfassen, sondern
nur die, denen es gegeben ist.

<<v12>>
12 Denn es ist so: Manche sind von Geburt an zur Ehe unfähig, manche
sind von den Menschen dazu gemacht und manche haben sich selbst dazu
gemacht - um des Himmelreiches willen. Wer das erfassen kann, der
erfasse es.\\
\\

<<v13>>
**** Die Segnung der Kinder: 19,13-15
     :PROPERTIES:
     :CUSTOM_ID: die-segnung-der-kinder-1913-15
     :END:
13 Da brachte man Kinder zu ihm, damit er ihnen die Hände auflegte und
für sie betete. Die Jünger aber wiesen die Leute schroff ab.
^{[[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 253\\
$ŽG://ESyn0812/\\
\\

<<v14>>
14 Doch Jesus sagte: Lasst die Kinder zu mir kommen; hindert sie nicht
daran! Denn Menschen wie ihnen gehört das Himmelreich. ^{[[#fn12][12]]}

<<v15>>
15 Dann legte er ihnen die Hände auf und zog weiter.\\
\\

<<v16>>
**** Von Reichtum und Nachfolge: 19,16-30
     :PROPERTIES:
     :CUSTOM_ID: von-reichtum-und-nachfolge-1916-30
     :END:
16 Es kam ein Mann zu Jesus und fragte: Meister, was muss ich Gutes tun,
um das ewige Leben zu gewinnen? ^{[[#fn13][13]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 254\\
$ŽG://ESyn0812/\\
\\

<<v17>>
17 Er antwortete: Was fragst du mich nach dem Guten? Nur einer ist «der
Gute». Wenn du aber das Leben erlangen willst, halte die Gebote!

<<v18>>
18 Darauf fragte er ihn: Welche? Jesus antwortete: /Du sollst nicht
töten, du sollst nicht die Ehe brechen, du sollst nicht stehlen, du
sollst nicht falsch aussagen;/ ^{[[#fn14][14]]}

<<v19>>
19 /ehre Vater und Mutter!/ Und: /Du sollst deinen Nächsten lieben wie
dich selbst!/ ^{[[#fn15][15]]}

<<v20>>
20 Der junge Mann erwiderte ihm: Alle diese Gebote habe ich befolgt. Was
fehlt mir jetzt noch?

<<v21>>
21 Jesus antwortete ihm: Wenn du vollkommen sein willst, geh, verkauf
deinen Besitz und gib das Geld den Armen; so wirst du einen bleibenden
Schatz im Himmel haben; dann komm und folge mir nach. ^{[[#fn16][16]]}

<<v22>>
22 Als der junge Mann das hörte, ging er traurig weg; denn er hatte ein
großes Vermögen.

<<v23>>
23 Da sagte Jesus zu seinen Jüngern: Amen, das sage ich euch: Ein
Reicher wird nur schwer in das Himmelreich kommen.
^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 255\\
$ŽG://ESyn0812/\\
\\

<<v24>>
24 Nochmals sage ich euch: Eher geht ein Kamel durch ein Nadelöhr, als
dass ein Reicher in das Reich Gottes gelangt.

<<v25>>
25 Als die Jünger das hörten, erschraken sie sehr und sagten: Wer kann
dann noch gerettet werden?

<<v26>>
26 Jesus sah sie an und sagte zu ihnen: Für Menschen ist das unmöglich,
/für Gott/ aber /ist alles möglich./ ^{[[#fn18][18]]}

<<v27>>
27 Da antwortete Petrus: Du weißt, wir haben alles verlassen und sind
dir nachgefolgt. Was werden wir dafür bekommen?

<<v28>>
28 Jesus erwiderte ihnen: Amen, ich sage euch: Wenn die Welt neu
geschaffen wird und der Menschensohn sich auf den Thron der Herrlichkeit
setzt, werdet ihr, die ihr mir nachgefolgt seid, auf zwölf Thronen
sitzen und die zwölf Stämme Israels richten. ^{[[#fn19][19]]}

<<v29>>
29 Und jeder, der um meines Namens willen Häuser oder Brüder,
Schwestern, Vater, Mutter, Kinder oder Äcker verlassen hat, wird dafür
das Hundertfache erhalten und das ewige Leben gewinnen. ^{[[#fn20][20]]}

<<v30>>
30 Viele aber, die jetzt die Ersten sind, werden dann die Letzten sein,
und die Letzten werden die Ersten sein. ^{[[#fn21][21]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-2) Mk 10,1; Lk 9,51 ⇨Esyn: Synopse Nr. 251

^{[[#fnm2][2]]} ℘ (3-9) Mk 10,2-12

^{[[#fnm3][3]]} 3.7f: Die Entlassung der Frau aus der Ehe war durch das
Gesetz des Mose erlaubt (vgl. Dtn 24,1); umstritten war lediglich,
welche Gründe dies rechtfertigten: nach der strengeren Auffassung des
Schriftgelehrten Schammai Ehebruch, ansteckende Krankheit,
Geisteskrankheit, Kinderlosigkeit; nach der Auffassung des
Schriftgelehrten Hillel, die zur Zeit Jesu vorherrschend war, alles, was
dem Mann an seiner Frau missfiel.

^{[[#fnm4][4]]} ℘ ⇨Esyn: Synopse Nr. 252

^{[[#fnm5][5]]} ℘ Gen 1,27

^{[[#fnm6][6]]} Mit dem Hinweis auf den «Anfang» verweist Jesus auf die
Schöpfungsordnung Gottes (vgl. Gen 1,1 - 2,4a; 2,4b-25).

^{[[#fnm7][7]]} ℘ Gen 2,24

^{[[#fnm8][8]]} ℘ Dtn 24,1; Mt 5,31

^{[[#fnm9][9]]} ℘ 5,32; Lk 16,18; 1 Kor 7,10f

^{[[#fnm10][10]]} Die sog. Unzuchtsklausel, die vom radikalen
Scheidungsverbot Jesu den Fall der Unzucht ausnimmt, findet sich in der
älteren Überlieferung, wie sie in Mk 10,2-12 und Lk 16,18 vorliegt, noch
nicht.

^{[[#fnm11][11]]} ℘ (13-15) Mk 10,13-16; Lk 18,15-17 ⇨Esyn: Synopse Nr.
253

^{[[#fnm12][12]]} ℘ 18,3

^{[[#fnm13][13]]} ℘ (16-30) Mk 10,17-31; Lk 18,18-30 ⇨Esyn: Synopse Nr.
254

^{[[#fnm14][14]]} ℘ Ex 20,12-16; Dtn 5,16-20

^{[[#fnm15][15]]} ℘ Lev 19,18

^{[[#fnm16][16]]} ℘ 6,20; 8,22

^{[[#fnm17][17]]} ℘ ⇨Esyn: Synopse Nr. 255

^{[[#fnm18][18]]} ℘ Gen 18,14; Ijob 42,2; Lk 1,37

^{[[#fnm19][19]]} ℘ 25,31; Offb 3,21; Lk 22,30

^{[[#fnm20][20]]} das Hundertfache, nach einigen alten Textzeugen: ein
Vielfaches; vgl. Lk 18,30.

^{[[#fnm21][21]]} ℘ 20,16; Lk 13,30
