:PROPERTIES:
:ID:       c4cbc0db-cacd-4742-8fe4-0b802b973779
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_8.html][8]] [[file:Mt_9.html][9]]
*10* [[file:Mt_11.html][11]] [[file:Mt_12.html][12]] ...
[[file:Mt_28.html][28]]

--------------

* Mt 10
  :PROPERTIES:
  :CUSTOM_ID: mt-10
  :END:

<<verses>>

<<v1>>
**** Die Wahl der Zwölf: 10,1-4
     :PROPERTIES:
     :CUSTOM_ID: die-wahl-der-zwölf-101-4
     :END:
1 Dann rief er seine zwölf Jünger zu sich und gab ihnen die Vollmacht,
die unreinen Geister auszutreiben und alle Krankheiten und Leiden zu
heilen. ^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 99\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Die Namen der zwölf Apostel sind: an erster Stelle Simon, genannt
Petrus, und sein Bruder Andreas, dann Jakobus, der Sohn des Zebedäus,
und sein Bruder Johannes, ^{[[#fn2][2]]}

<<v3>>
3 Philippus und Bartholomäus, Thomas und Matthäus, der Zöllner, Jakobus,
der Sohn des Alphäus, und Thaddäus,

<<v4>>
4 Simon Kananäus und Judas Iskariot, der ihn später verraten hat.
^{[[#fn3][3]]}\\
\\

<<v5>>
**** Anweisung für die Mission: 10,5-15
     :PROPERTIES:
     :CUSTOM_ID: anweisung-für-die-mission-105-15
     :END:
5 Diese Zwölf sandte Jesus aus und gebot ihnen: Geht nicht zu den Heiden
und betretet keine Stadt der Samariter, ^{[[#fn4][4]]}

<<v6>>
6 sondern geht zu den verlorenen Schafen des Hauses Israel.
^{[[#fn5][5]]}

<<v7>>
7 Geht und verkündet: Das Himmelreich ist nahe. ^{[[#fn6][6]]}

<<v8>>
8 Heilt Kranke, weckt Tote auf, macht Aussätzige rein, treibt Dämonen
aus! Umsonst habt ihr empfangen, umsonst sollt ihr geben.

<<v9>>
9 Steckt nicht Gold, Silber und Kupfermünzen in euren Gürtel.

<<v10>>
10 Nehmt keine Vorratstasche mit auf den Weg, kein zweites Hemd, keine
Schuhe, keinen Wanderstab; denn wer arbeitet, hat ein Recht auf seinen
Unterhalt. ^{[[#fn7][7]]}

<<v11>>
11 Wenn ihr in eine Stadt oder in ein Dorf kommt, erkundigt euch, wer es
wert ist, euch aufzunehmen; bei ihm bleibt, bis ihr den Ort wieder
verlasst.

<<v12>>
12 Wenn ihr in ein Haus kommt, dann wünscht ihm Frieden.

<<v13>>
13 Wenn das Haus es wert ist, soll der Friede, den ihr ihm wünscht, bei
ihm einkehren. Ist das Haus es aber nicht wert, dann soll der Friede zu
euch zurückkehren.

<<v14>>
14 Wenn man euch aber in einem Haus oder in einer Stadt nicht aufnimmt
und eure Worte nicht hören will, dann geht weg und schüttelt den Staub
von euren Füßen. ^{[[#fn8][8]]}

<<v15>>
15 Amen, das sage ich euch: Dem Gebiet von Sodom und Gomorra wird es am
Tag des Gerichts nicht so schlimm ergehen wie dieser Stadt.
^{[[#fn9][9]]}\\
\\

<<v16>>
**** Aufforderung zu furchtlosem Bekenntnis: 10,16-39
     :PROPERTIES:
     :CUSTOM_ID: aufforderung-zu-furchtlosem-bekenntnis-1016-39
     :END:
16 Seht, ich sende euch wie Schafe mitten unter die Wölfe; seid daher
klug wie die Schlangen und arglos wie die Tauben! ^{[[#fn10][10]]}

<<v17>>
17 Nehmt euch aber vor den Menschen in Acht! Denn sie werden euch vor
die Gerichte bringen und in ihren Synagogen auspeitschen.
^{[[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 100\\
$ŽG://ESyn0812/\\
\\

<<v18>>
18 Ihr werdet um meinetwillen vor Statthalter und Könige geführt, damit
ihr vor ihnen und den Heiden Zeugnis ablegt.

<<v19>>
19 Wenn man euch vor Gericht stellt, macht euch keine Sorgen, wie und
was ihr reden sollt; denn es wird euch in jener Stunde eingegeben, was
ihr sagen sollt. ^{[[#fn12][12]]}

<<v20>>
20 Nicht ihr werdet dann reden, sondern der Geist eures Vaters wird
durch euch reden.

<<v21>>
21 Brüder werden einander dem Tod ausliefern und Väter ihre Kinder, und
die Kinder werden sich gegen ihre Eltern auflehnen und sie in den Tod
schicken. ^{[[#fn13][13]]}

<<v22>>
22 Und ihr werdet um meines Namens willen von allen gehasst werden; wer
aber bis zum Ende standhaft bleibt, der wird gerettet. ^{[[#fn14][14]]}

<<v23>>
23 Wenn man euch in der einen Stadt verfolgt, so flieht in eine andere.
Amen, ich sage euch: Ihr werdet nicht zu Ende kommen mit den Städten
Israels, bis der Menschensohn kommt. ^{[[#fn15][15]]}

<<v24>>
24 Ein Jünger steht nicht über seinem Meister und ein Sklave nicht über
seinem Herrn. ^{[[#fn16][16]]}

<<v25>>
25 Der Jünger muss sich damit begnügen, dass es ihm geht wie seinem
Meister, und der Sklave, dass es ihm geht wie seinem Herrn. Wenn man
schon den Herrn des Hauses Beelzebul nennt, dann erst recht seine
Hausgenossen. ^{[[#fn17][17]][[#fn18][18]]}

<<v26>>
26 Darum fürchtet euch nicht vor ihnen! Denn nichts ist verhüllt, was
nicht enthüllt wird, und nichts ist verborgen, was nicht bekannt wird.
^{[[#fn19][19]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 101\\
$ŽG://ESyn0812/\\
\\

<<v27>>
27 Was ich euch im Dunkeln sage, davon redet am hellen Tag, und was man
euch ins Ohr flüstert, das verkündet von den Dächern.

<<v28>>
28 Fürchtet euch nicht vor denen, die den Leib töten, die Seele aber
nicht töten können, sondern fürchtet euch vor dem, der Seele und Leib
ins Verderben der Hölle stürzen kann. ^{[[#fn20][20]]}

<<v29>>
29 Verkauft man nicht zwei Spatzen für ein paar Pfennig? Und doch fällt
keiner von ihnen zur Erde ohne den Willen eures Vaters. ^{[[#fn21][21]]}

<<v30>>
30 Bei euch aber sind sogar die Haare auf dem Kopf alle gezählt.
^{[[#fn22][22]]}

<<v31>>
31 Fürchtet euch also nicht! Ihr seid mehr wert als viele Spatzen.

<<v32>>
32 Wer sich nun vor den Menschen zu mir bekennt, zu dem werde auch ich
mich vor meinem Vater im Himmel bekennen.

<<v33>>
33 Wer mich aber vor den Menschen verleugnet, den werde auch ich vor
meinem Vater im Himmel verleugnen. ^{[[#fn23][23]]}

<<v34>>
34 Denkt nicht, ich sei gekommen, um Frieden auf die Erde zu bringen.
Ich bin nicht gekommen, um Frieden zu bringen, sondern das Schwert.
^{[[#fn24][24]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 102\\
$ŽG://ESyn0812/\\
\\

<<v35>>
35 Denn ich bin gekommen, um /den Sohn mit seinem Vater/ zu entzweien
/und die Tochter mit ihrer Mutter und die Schwiegertochter mit ihrer
Schwiegermutter;/ ^{[[#fn25][25]]}

<<v36>>
36 und /die Hausgenossen eines Menschen werden seine Feinde sein./

<<v37>>
37 Wer Vater oder Mutter mehr liebt als mich, ist meiner nicht würdig,
und wer Sohn oder Tochter mehr liebt als mich, ist meiner nicht würdig.
^{[[#fn26][26]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 103\\
$ŽG://ESyn0812/\\
\\

<<v38>>
38 Und wer nicht sein Kreuz auf sich nimmt und mir nachfolgt, ist meiner
nicht würdig. ^{[[#fn27][27]]}

<<v39>>
39 Wer das Leben gewinnen will, wird es verlieren; wer aber das Leben um
meinetwillen verliert, wird es gewinnen. ^{[[#fn28][28]]}\\
\\

<<v40>>
**** Vom Lohn für die Aufnahme der Jünger: 10,40-42
     :PROPERTIES:
     :CUSTOM_ID: vom-lohn-für-die-aufnahme-der-jünger-1040-42
     :END:
40 Wer euch aufnimmt, der nimmt mich auf, und wer mich aufnimmt, nimmt
den auf, der mich gesandt hat. ^{[[#fn29][29]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 104\\
$ŽG://ESyn0812/\\
\\

<<v41>>
41 Wer einen Propheten aufnimmt, weil es ein Prophet ist, wird den Lohn
eines Propheten erhalten. Wer einen Gerechten aufnimmt, weil es ein
Gerechter ist, wird den Lohn eines Gerechten erhalten.

<<v42>>
42 Und wer einem von diesen Kleinen auch nur einen Becher frisches
Wasser zu trinken gibt, weil es ein Jünger ist - amen, ich sage euch: Er
wird gewiss nicht um seinen Lohn kommen. ^{[[#fn30][30]]}

^{[[#fnm1][1]]} ℘ Mk 6,7; Lk 9,1; (1-4) Mk 3,13-19; Lk 6,12-16 ⇨Esyn:
Synopse Nr. 99

^{[[#fnm2][2]]} ℘ (2-4) Joh 1,40-44; Apg 1,13

^{[[#fnm3][3]]} Kananäus ist nicht Eigenname, sondern Beiname im Sinn
von «der Zelot», «der Eiferer».

^{[[#fnm4][4]]} ℘ (5-15) Lk 10,4-12; Mk 6,8-11; Lk 9,2-5

^{[[#fnm5][5]]} ℘ 15,24

^{[[#fnm6][6]]} ℘ 4,17

^{[[#fnm7][7]]} ℘ 1 Kor 9,5-14; 1 Tim 5,18

^{[[#fnm8][8]]} ℘ Apg 13,51

^{[[#fnm9][9]]} ℘ Gen 19,23-29; Mt 11,24

^{[[#fnm10][10]]} ℘ Joh 10,12; Lk 10,3

^{[[#fnm11][11]]} ℘ Joh 16,1-4 a; (17-22) 24,9-14; Mk 13,9-13; Lk
21,12-19 ⇨Esyn: Synopse Nr. 100

^{[[#fnm12][12]]} ℘ (19-20) Lk 12,11f

^{[[#fnm13][13]]} ℘ 10,35

^{[[#fnm14][14]]} ℘ Joh 15,18; Mt 24,13

^{[[#fnm15][15]]} ℘ 16,28

^{[[#fnm16][16]]} ℘ Lk 6,40; Joh 13,16; 15,20

^{[[#fnm17][17]]} ℘ 12,24.27; Mk 3,22; Lk 11,15.18f

^{[[#fnm18][18]]} Beelzebul: Die bisher übliche Namensform Beelzebub
geht auf die Vulgataübersetzung zurück; zur Sache vgl. Mt 12,24.

^{[[#fnm19][19]]} ℘ Mk 4,22; Lk 8,17; (26-33) Lk 12,2-9 ⇨Esyn: Synopse
Nr. 101

^{[[#fnm20][20]]} ℘ Jak 4,12

^{[[#fnm21][21]]} ein paar Pfennig, wörtlich: ein As. Das As war die
zweitkleinste römische Münze.

^{[[#fnm22][22]]} ℘ Lk 21,18

^{[[#fnm23][23]]} ℘ Mk 8,38; Lk 9,26

^{[[#fnm24][24]]} ℘ (34-36) Lk 12,51-53 ⇨Esyn: Synopse Nr. 102

^{[[#fnm25][25]]} ℘ 10,21; Mi 7,6

^{[[#fnm26][26]]} ℘ 19,29; (37-38) Lk 14,26f ⇨Esyn: Synopse Nr. 103

^{[[#fnm27][27]]} ℘ (38-39) 16,24f; Mk 8,34f; Lk 9,23f; Joh 12,25f

^{[[#fnm28][28]]} ℘ Lk 17,33

^{[[#fnm29][29]]} ℘ Lk 10,16; Joh 13,20 ⇨Esyn: Synopse Nr. 104

^{[[#fnm30][30]]} ℘ Mk 9,41
