:PROPERTIES:
:ID:       e2b8670e-e35c-42c6-bb70-c26bf741023b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_20.html][20]]
[[file:Mt_21.html][21]] *22* [[file:Mt_23.html][23]]
[[file:Mt_24.html][24]] ... [[file:Mt_28.html][28]]

--------------

* Mt 22
  :PROPERTIES:
  :CUSTOM_ID: mt-22
  :END:

<<verses>>

<<v1>>
**** Das Gleichnis vom königlichen Hochzeitsmahl: 22,1-14
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-königlichen-hochzeitsmahl-221-14
     :END:
1 Jesus erzählte ihnen noch ein anderes Gleichnis:
^{[[#fn1][1]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 279\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Mit dem Himmelreich ist es wie mit einem König, der die Hochzeit
seines Sohnes vorbereitete. ^{[[#fn2][2]]}

<<v3>>
3 Er schickte seine Diener, um die eingeladenen Gäste zur Hochzeit rufen
zu lassen. Sie aber wollten nicht kommen.

<<v4>>
4 Da schickte er noch einmal Diener und trug ihnen auf: Sagt den
Eingeladenen: Mein Mahl ist fertig, die Ochsen und das Mastvieh sind
geschlachtet, alles ist bereit. Kommt zur Hochzeit!

<<v5>>
5 Sie aber kümmerten sich nicht darum, sondern der eine ging auf seinen
Acker, der andere in seinen Laden,

<<v6>>
6 wieder andere fielen über seine Diener her, misshandelten sie und
brachten sie um. ^{[[#fn3][3]]}

<<v7>>
7 Da wurde der König zornig; er schickte sein Heer, ließ die Mörder
töten und ihre Stadt in Schutt und Asche legen.

<<v8>>
8 Dann sagte er zu seinen Dienern: Das Hochzeitsmahl ist vorbereitet,
aber die Gäste waren es nicht wert (eingeladen zu werden).

<<v9>>
9 Geht also hinaus auf die Straßen und ladet alle, die ihr trefft, zur
Hochzeit ein.

<<v10>>
10 Die Diener gingen auf die Straßen hinaus und holten alle zusammen,
die sie trafen, Böse und Gute, und der Festsaal füllte sich mit Gästen.

<<v11>>
11 Als sie sich gesetzt hatten und der König eintrat, um sich die Gäste
anzusehen, bemerkte er unter ihnen einen Mann, der kein Hochzeitsgewand
anhatte.

<<v12>>
12 Er sagte zu ihm: Mein Freund, wie konntest du hier ohne
Hochzeitsgewand erscheinen? Darauf wusste der Mann nichts zu sagen.

<<v13>>
13 Da befahl der König seinen Dienern: Bindet ihm Hände und Füße und
werft ihn hinaus in die äußerste Finsternis! Dort wird er heulen und mit
den Zähnen knirschen. ^{[[#fn4][4]]}

<<v14>>
14 Denn viele sind gerufen, aber nur wenige auserwählt.\\
\\

<<v15>>
**** Die Frage nach der kaiserlichen Steuer: 22,15-22
     :PROPERTIES:
     :CUSTOM_ID: die-frage-nach-der-kaiserlichen-steuer-2215-22
     :END:
15 Damals kamen die Pharisäer zusammen und beschlossen, Jesus mit einer
Frage eine Falle zu stellen.
^{[[#fn5][5]][[#fn6][6]][[#fn7][7]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 280\\
$ŽG://ESyn0812/\\
\\

<<v16>>
16 Sie veranlassten ihre Jünger, zusammen mit den Anhängern des Herodes
zu ihm zu gehen und zu sagen: Meister, wir wissen, dass du immer die
Wahrheit sagst und wirklich den Weg Gottes lehrst, ohne auf jemand
Rücksicht zu nehmen; denn du siehst nicht auf die Person.

<<v17>>
17 Sag uns also: Ist es nach deiner Meinung erlaubt, dem Kaiser Steuer
zu zahlen, oder nicht?

<<v18>>
18 Jesus aber erkannte ihre böse Absicht und sagte: Ihr Heuchler, warum
stellt ihr mir eine Falle?

<<v19>>
19 Zeigt mir die Münze, mit der ihr eure Steuern bezahlt! Da hielten sie
ihm einen Denar hin.

<<v20>>
20 Er fragte sie: Wessen Bild und Aufschrift ist das?

<<v21>>
21 Sie antworteten: Des Kaisers. Darauf sagte er zu ihnen: So gebt dem
Kaiser, was dem Kaiser gehört, und Gott, was Gott gehört!

<<v22>>
22 Als sie das hörten, waren sie sehr überrascht, wandten sich um und
gingen weg.\\
\\

<<v23>>
**** Die Frage nach der Auferstehung der Toten: 22,23-33
     :PROPERTIES:
     :CUSTOM_ID: die-frage-nach-der-auferstehung-der-toten-2223-33
     :END:
23 Am selben Tag kamen zu Jesus einige von den Sadduzäern, die
behaupten, es gebe keine Auferstehung. Sie fragten ihn:
^{[[#fn8][8]][[#fn9][9]][[#fn10][10]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 281\\
$ŽG://ESyn0812/\\
\\

<<v24>>
24 Meister, Mose hat gesagt: /Wenn ein Mann stirbt, ohne Kinder zu
haben, dann soll sein Bruder dessen Frau heiraten und/ seinem /Bruder
Nachkommen verschaffen./ ^{[[#fn11][11]]}

<<v25>>
25 Bei uns lebten einmal sieben Brüder. Der erste heiratete und starb,
und weil er keine Nachkommen hatte, hinterließ er seine Frau seinem
Bruder,

<<v26>>
26 ebenso der zweite und der dritte und so weiter bis zum siebten.

<<v27>>
27 Als letzte von allen starb die Frau.

<<v28>>
28 Wessen Frau wird sie nun bei der Auferstehung sein? Alle sieben haben
sie doch zur Frau gehabt.

<<v29>>
29 Jesus antwortete ihnen: Ihr irrt euch; ihr kennt weder die Schrift
noch die Macht Gottes.

<<v30>>
30 Denn nach der Auferstehung werden die Menschen nicht mehr heiraten,
sondern sein wie die Engel im Himmel.

<<v31>>
31 Habt ihr im übrigen nicht gelesen, was Gott euch über die
Auferstehung der Toten mit den Worten gesagt hat:

<<v32>>
32 /Ich bin der Gott Abrahams, der Gott Isaaks und der Gott Jakobs/ ? Er
ist doch nicht der Gott der Toten, sondern der Gott der Lebenden.
^{[[#fn12][12]]}

<<v33>>
33 Als das Volk das hörte, war es über seine Lehre bestürzt.\\
\\

<<v34>>
**** Die Frage nach dem wichtigsten Gebot: 22,34-40
     :PROPERTIES:
     :CUSTOM_ID: die-frage-nach-dem-wichtigsten-gebot-2234-40
     :END:
34 Als die Pharisäer hörten, dass Jesus die Sadduzäer zum Schweigen
gebracht hatte, kamen sie (bei ihm) zusammen.
^{[[#fn13][13]][[#fn14][14]][[#fn15][15]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 282\\
$ŽG://ESyn0812/\\
\\

<<v35>>
35 Einer von ihnen, ein Gesetzeslehrer, wollte ihn auf die Probe stellen
und fragte ihn:

<<v36>>
36 Meister, welches Gebot im Gesetz ist das wichtigste?

<<v37>>
37 Er antwortete ihm: /Du sollst den Herrn, deinen Gott, lieben mit
ganzem Herzen, mit ganzer Seele/ und mit all deinen Gedanken.
^{[[#fn16][16]]}

<<v38>>
38 Das ist das wichtigste und erste Gebot.

<<v39>>
39 Ebenso wichtig ist das zweite: /Du sollst deinen Nächsten lieben wie
dich selbst./ ^{[[#fn17][17]]}

<<v40>>
40 An diesen beiden Geboten hängt das ganze Gesetz samt den Propheten.
^{[[#fn18][18]]}\\
\\

<<v41>>
**** Die Frage nach dem Messias: 22,41-46
     :PROPERTIES:
     :CUSTOM_ID: die-frage-nach-dem-messias-2241-46
     :END:
41 Danach fragte Jesus die Pharisäer, die bei ihm versammelt waren:
^{[[#fn19][19]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 283\\
$ŽG://ESyn0812/\\
\\

<<v42>>
42 Was denkt ihr über den Messias? Wessen Sohn ist er? Sie antworteten
ihm: Der Sohn Davids.

<<v43>>
43 Er sagte zu ihnen: Wie kann ihn dann David, vom Geist (Gottes)
erleuchtet, «Herr» nennen? Denn er sagt:

<<v44>>
44 /Der Herr sprach zu meinem Herrn: Setze dich mir zur Rechten und ich
lege dir deine Feinde unter die Füße./ ^{[[#fn20][20]]}

<<v45>>
45 Wenn ihn also David «Herr» nennt, wie kann er dann Davids Sohn sein?

<<v46>>
46 Niemand konnte ihm darauf etwas erwidern und von diesem Tag an wagte
keiner mehr, ihm eine Frage zu stellen. ^{[[#fn21][21]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-10) Lk 14,15-24 ⇨Esyn: Synopse Nr. 279

^{[[#fnm2][2]]} 2-10.11-13: Matthäus hat zwei selbständige Gleichnisse
miteinander verknüpft. Der zweite Teil besagt, dass der Eintritt in das
Reich Gottes die Umkehr des Sünders voraussetzt.

^{[[#fnm3][3]]} ℘ 21,35

^{[[#fnm4][4]]} ℘ 8,12

^{[[#fnm5][5]]} ℘ (15-22) Mk 12,13-17; Lk 20,20-26

^{[[#fnm6][6]]} 15-22: Im Jahr 6/7 n. Chr. wurde der Zensus, die
römische Kopfund Grundsteuer, auch in Judäa und Samarien eingeführt. Die
jüdischen Frommen, vor allem die sogenannten Zeloten, sahen in der
Steuerzahlung einen Verrat an Gott. Der römische Silber-Denar trug
damals ein Bild des Kaisers Tiberius (14-37 n. Chr.) und die Aufschrift:
«Tiberius, Cäsar, des göttlichen Augustus Sohn, Augustus».

^{[[#fnm7][7]]} ℘ ⇨Esyn: Synopse Nr. 280

^{[[#fnm8][8]]} ℘ Apg 23,8; (23-33) Mk 12,18-27; Lk 20,27-38

^{[[#fnm9][9]]} 23-33: Zur Zeit Jesu hofften die Pharisäer und ein
großer Teil des jüdischen Volkes auf eine allgemeine Auferstehung der
Toten am Ende der Zeit; die Sadduzäer lehnten diese Vorstellung ab.

^{[[#fnm10][10]]} ℘ ⇨Esyn: Synopse Nr. 281

^{[[#fnm11][11]]} ℘ Dtn 25,5f; Gen 38,8

^{[[#fnm12][12]]} ℘ Ex 3,6

^{[[#fnm13][13]]} ℘ (34-40) Mk 12,28-31; Lk 10,25-28

^{[[#fnm14][14]]} 34-40: Ob die zahlreichen Gebote und
Gesetzesvorschriften alle gleich wichtig seien, war im rabbinischen
Judentum eine strittige Frage. Für Jesus ist das doppelte Liebesgebot
der Inbegriff des ganzen Gesetzes, das eine Hauptgebot, an dem alle
anderen Gesetze hängen (vgl. die Anmerkung zu 23,4).

^{[[#fnm15][15]]} ℘ ⇨Esyn: Synopse Nr. 282

^{[[#fnm16][16]]} ℘ Dtn 6,5

^{[[#fnm17][17]]} ℘ Lev 19,18; Mt 5,43; Röm 13,9; Gal 5,14

^{[[#fnm18][18]]} ℘ 7,12

^{[[#fnm19][19]]} ℘ (41-45) Mk 12,35-37a; Lk 20,41-44 ⇨Esyn: Synopse Nr.
283

^{[[#fnm20][20]]} ℘ Ps 110,1

^{[[#fnm21][21]]} ℘ Mk 12,34; Lk 20,40
