:PROPERTIES:
:ID:       74d222fd-0c17-40be-a8b7-1f62a7e363b5
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_22.html][22]]
[[file:Mt_23.html][23]] *24* [[file:Mt_25.html][25]]
[[file:Mt_26.html][26]] ... [[file:Mt_28.html][28]]

--------------

* Mt 24
  :PROPERTIES:
  :CUSTOM_ID: mt-24
  :END:

<<verses>>

<<v1>>
*** Die Rede über die Endzeit: 24,1 - 25,46
    :PROPERTIES:
    :CUSTOM_ID: die-rede-über-die-endzeit-241---2546
    :END:
**** Die Ankündigung der Zerstörung des Tempels: 24,1-2
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-der-zerstörung-des-tempels-241-2
     :END:
1 Als Jesus den Tempel verlassen hatte, wandten sich seine Jünger an ihn
und wiesen ihn auf die gewaltigen Bauten des Tempels hin.
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 287\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Er sagte zu ihnen: Seht ihr das alles? Amen, das sage ich euch: Kein
Stein wird hier auf dem andern bleiben; alles wird niedergerissen
werden. ^{[[#fn4][4]]}\\
\\

<<v3>>
**** Vom Anfang der Not: 24,3-14
     :PROPERTIES:
     :CUSTOM_ID: vom-anfang-der-not-243-14
     :END:
3 Als er auf dem Ölberg saß, wandten sich die Jünger, die mit ihm allein
waren, an ihn und fragten: Sag uns, wann wird das geschehen, und was ist
das Zeichen für deine Ankunft und das Ende der Welt?
^{[[#fn5][5]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 288\\
$ŽG://ESyn0812/\\
\\

<<v4>>
4 Jesus antwortete: Gebt Acht, dass euch niemand irreführt!

<<v5>>
5 Denn viele werden unter meinem Namen auftreten und sagen: Ich bin der
Messias!, und sie werden viele irreführen.

<<v6>>
6 Ihr werdet von Kriegen hören und Nachrichten über Kriege werden euch
beunruhigen. Gebt Acht, lasst euch nicht erschrecken! Das /muss
geschehen./ Es ist aber noch nicht das Ende. ^{[[#fn6][6]]}

<<v7>>
7 Denn ein Volk wird sich gegen das andere erheben und ein Reich gegen
das andere und an vielen Orten wird es Hungersnöte und Erdbeben geben.
^{[[#fn7][7]]}

<<v8>>
8 Doch das alles ist erst der Anfang der Wehen.

<<v9>>
9 Dann wird man euch in große Not bringen und euch töten und ihr werdet
von allen Völkern um meines Namens willen gehasst.
^{[[#fn8][8]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 289\\
$ŽG://ESyn0812/\\
\\

<<v10>>
10 Dann werden viele zu Fall kommen und einander hassen und verraten.

<<v11>>
11 Viele falsche Propheten werden auftreten und sie werden viele
irreführen. ^{[[#fn9][9]]}

<<v12>>
12 Und weil die Missachtung von Gottes Gesetz überhandnimmt, wird die
Liebe bei vielen erkalten.

<<v13>>
13 Wer jedoch bis zum Ende standhaft bleibt, der wird gerettet.

<<v14>>
14 Aber dieses Evangelium vom Reich wird auf der ganzen Welt verkündet
werden, damit alle Völker es hören; dann erst kommt das Ende.
^{[[#fn10][10]][[#fn11][11]]}\\
\\

<<v15>>
**** Vom Höhepunkt der Not: 24,15-28
     :PROPERTIES:
     :CUSTOM_ID: vom-höhepunkt-der-not-2415-28
     :END:
15 Wenn ihr dann am heiligen Ort den /unheilvollen Gräuel/ stehen seht,
der durch den Propheten Daniel vorhergesagt worden ist - der Leser
begreife -, ^{[[#fn12][12]][[#fn13][13]][[#fn14][14]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 290\\
$ŽG://ESyn0812/\\
\\

<<v16>>
16 dann sollen die Bewohner von Judäa in die Berge fliehen;

<<v17>>
17 wer gerade auf dem Dach ist, soll nicht mehr ins Haus gehen, um seine
Sachen mitzunehmen; ^{[[#fn15][15]]}

<<v18>>
18 wer auf dem Feld ist, soll nicht zurückkehren, um seinen Mantel zu
holen.

<<v19>>
19 Weh aber den Frauen, die in jenen Tagen schwanger sind oder ein Kind
stillen.

<<v20>>
20 Betet darum, dass ihr nicht im Winter oder an einem Sabbat fliehen
müsst.

<<v21>>
21 Denn es wird eine so große /Not/ kommen, /wie es noch nie eine
gegeben hat, seit die Welt besteht, und wie es auch keine mehr geben
wird./ ^{[[#fn16][16]]}

<<v22>>
22 Und wenn jene Zeit nicht verkürzt würde, dann würde kein Mensch
gerettet; doch um der Auserwählten willen wird jene Zeit verkürzt
werden.

<<v23>>
23 Wenn dann jemand zu euch sagt: Seht, hier ist der Messias!, oder: Da
ist er!, so glaubt es nicht! ^{[[#fn17][17]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 291\\
$ŽG://ESyn0812/\\
\\

<<v24>>
24 Denn es wird mancher falsche Messias und mancher falsche Prophet
auftreten und sie werden große Zeichen und Wunder tun, um, wenn möglich,
auch die Auserwählten irrezuführen. ^{[[#fn18][18]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 289\\
$ŽG://ESyn0812/\\
\\

<<v25>>
25 Denkt daran: Ich habe es euch vorausgesagt.

<<v26>>
26 Wenn sie also zu euch sagen: Seht, er ist draußen in der Wüste!, so
geht nicht hinaus; und wenn sie sagen: Seht, er ist im Haus!, so glaubt
es nicht. ^{[[#fn19][19]]}

<<v27>>
27 Denn wie der Blitz bis zum Westen hin leuchtet, wenn er im Osten
aufflammt, so wird es bei der Ankunft des Menschensohnes sein.

<<v28>>
28 Überall wo ein Aas ist, da sammeln sich die Geier. ^{[[#fn20][20]]}\\
\\

<<v29>>
**** Vom Kommen des Menschensohnes: 24,29-31
     :PROPERTIES:
     :CUSTOM_ID: vom-kommen-des-menschensohnes-2429-31
     :END:
29 Sofort nach den Tagen der großen Not /wird sich die Sonne verfinstern
und der Mond wird nicht mehr scheinen; die Sterne/ werden vom Himmel
/fallen/ und die Kräfte des Himmels werden erschüttert werden.
^{[[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 292\\
$ŽG://ESyn0812/\\
\\

<<v30>>
30 Danach wird das Zeichen des Menschensohnes am Himmel erscheinen; dann
/werden alle Völker der Erde jammern und klagen/ und sie werden den
/Menschensohn/ mit großer Macht und Herrlichkeit /auf den Wolken des
Himmels kommen/ sehen. ^{[[#fn22][22]]}

<<v31>>
31 Er wird seine Engel unter lautem Posaunenschall aussenden und sie
werden die von ihm Auserwählten /aus allen vier Windrichtungen
zusammenführen,/ von einem Ende des Himmels bis zum andern.
^{[[#fn23][23]]}\\
\\

<<v32>>
**** Mahnungen im Hinblick auf das Ende: 24,32-42
     :PROPERTIES:
     :CUSTOM_ID: mahnungen-im-hinblick-auf-das-ende-2432-42
     :END:
32 Lernt etwas aus dem Vergleich mit dem Feigenbaum! Sobald seine Zweige
saftig werden und Blätter treiben, wisst ihr, dass der Sommer nahe ist.
^{[[#fn24][24]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 293\\
$ŽG://ESyn0812/\\
\\

<<v33>>
33 Genauso sollt ihr erkennen, wenn ihr das alles seht, dass das Ende
vor der Tür steht.

<<v34>>
34 Amen, ich sage euch: Diese Generation wird nicht vergehen, bis das
alles eintrifft. ^{[[#fn25][25]]}

<<v35>>
35 Himmel und Erde werden vergehen, aber meine Worte werden nicht
vergehen.

<<v36>>
36 Doch jenen Tag und jene Stunde kennt niemand, auch nicht die Engel im
Himmel, nicht einmal der Sohn, sondern nur der Vater.

<<v37>>
37 Denn wie es in den Tagen des Noach war, so wird es bei der Ankunft
des Menschensohnes sein. ^{[[#fn26][26]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 296\\
$ŽG://ESyn0812/\\
\\

<<v38>>
38 Wie die Menschen in den Tagen vor der Flut aßen und tranken und
heirateten, bis zu dem Tag, /an dem Noach in die Arche ging,/
^{[[#fn27][27]]}

<<v39>>
39 und nichts ahnten, bis die Flut hereinbrach und alle wegraffte, so
wird es auch bei der Ankunft des Menschensohnes sein.

<<v40>>
40 Dann wird von zwei Männern, die auf dem Feld arbeiten, einer
mitgenommen und einer zurückgelassen.

<<v41>>
41 Und von zwei Frauen, die mit derselben Mühle mahlen, wird eine
mitgenommen und eine zurückgelassen.

<<v42>>
42 Seid also wachsam! Denn ihr wisst nicht, an welchem Tag euer Herr
kommt. ^{[[#fn28][28]]}\\
\\

<<v43>>
**** Das Gleichnis vom wachsamen Hausherrn: 24,43-44
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-wachsamen-hausherrn-2443-44
     :END:
43 Bedenkt: Wenn der Herr des Hauses wüsste, zu welcher Stunde in der
Nacht der Dieb kommt, würde er wach bleiben und nicht zulassen, dass man
in sein Haus einbricht. ^{[[#fn29][29]]}

<<v44>>
44 Darum haltet auch ihr euch bereit! Denn der Menschensohn kommt zu
einer Stunde, in der ihr es nicht erwartet.\\
\\

<<v45>>
**** Das Gleichnis vom treuen und vom schlechten Knecht: 24,45-51
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-treuen-und-vom-schlechten-knecht-2445-51
     :END:
45 Wer ist nun der treue und kluge Knecht, den der Herr eingesetzt hat,
damit er dem Gesinde zur rechten Zeit gibt, was sie zu essen brauchen?
^{[[#fn30][30]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 297\\
$ŽG://ESyn0812/\\
\\

<<v46>>
46 Selig der Knecht, den der Herr damit beschäftigt findet, wenn er
kommt!

<<v47>>
47 Amen, das sage ich euch: Er wird ihn zum Verwalter seines ganzen
Vermögens machen. ^{[[#fn31][31]]}

<<v48>>
48 Wenn aber der Knecht schlecht ist und denkt: Mein Herr kommt noch
lange nicht!,

<<v49>>
49 und anfängt, seine Mitknechte zu schlagen, wenn er mit Trinkern
Gelage feiert,

<<v50>>
50 dann wird der Herr an einem Tag kommen, an dem der Knecht es nicht
erwartet, und zu einer Stunde, die er nicht kennt; ^{[[#fn32][32]]}

<<v51>>
51 und der Herr wird ihn in Stücke hauen und ihm seinen Platz unter den
Heuchlern zuweisen. Dort wird er heulen und mit den Zähnen knirschen.
^{[[#fn33][33]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-2) Mk 13,1f; Lk 21,5f

^{[[#fnm2][2]]} 1-25,46: Die umfangreiche Rede von den letzten Dingen
wurde vom Evangelisten zusammengestellt. Er rechnet noch mit einem nahen
Weltuntergang (vgl. 24,29: «sofort nach jenen Tagen»).

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 287

^{[[#fnm4][4]]} ℘ Lk 19,44

^{[[#fnm5][5]]} ℘ (3-14) Mk 13,3-13; Lk 21,7-19 ⇨Esyn: Synopse Nr. 288

^{[[#fnm6][6]]} ℘ Dan 2,28 G

^{[[#fnm7][7]]} ℘ Jes 19,2

^{[[#fnm8][8]]} ℘ (9-13) 10,17-22; Joh 16,1-4 ⇨Esyn: Synopse Nr. 289

^{[[#fnm9][9]]} ℘ 24,23

^{[[#fnm10][10]]} ℘ 28,19

^{[[#fnm11][11]]} damit alle Völker es hören, wörtlich: allen Völkern
zum Zeugnis.

^{[[#fnm12][12]]} ℘ Dan 9,27; 11,31; 12,11; 1 Makk 1,54; (15-28) Mk
13,14-23; Lk 21,20-24

^{[[#fnm13][13]]} Der «unheilvolle Gräuel» ist bei Dan 9,27; 11,31;
12,11 ein im Tempel aufgestellter Altar (oder ein Standbild) des
griechischen Gottes Zeus.

^{[[#fnm14][14]]} ℘ ⇨Esyn: Synopse Nr. 290

^{[[#fnm15][15]]} ℘ Mk 13,15f; Lk 17,31

^{[[#fnm16][16]]} ℘ Dan 12,1; Joël 2,2

^{[[#fnm17][17]]} ℘ ⇨Esyn: Synopse Nr. 291

^{[[#fnm18][18]]} ℘ ⇨Esyn: Synopse Nr. 289

^{[[#fnm19][19]]} ℘ Lk 17,23

^{[[#fnm20][20]]} ℘ Lk 17,37

^{[[#fnm21][21]]} ℘ Jes 13,10; 34,4 G; Joël 2,10; Hag 2,6.21; 2 Petr
3,10; (29-31) Mk 13,24-27; Lk 21,25-28 ⇨Esyn: Synopse Nr. 292

^{[[#fnm22][22]]} ℘ Sach 12,10.12; Dan 7,13; Mt 26,64; Mk 14,62; Offb
1,7

^{[[#fnm23][23]]} ℘ Sach 2,10 G

^{[[#fnm24][24]]} ℘ (32-36) Mk 13,28-32; Lk 21,29-33 ⇨Esyn: Synopse Nr.
293

^{[[#fnm25][25]]} ℘ 16,28; Mk 9,1; Lk 9,27

^{[[#fnm26][26]]} ℘ Gen 6,11-13; 7,7-23; (37-42) Mk 13,35; Lk 17,26-36
⇨Esyn: Synopse Nr. 296

^{[[#fnm27][27]]} ℘ Gen 7,7

^{[[#fnm28][28]]} ℘ 25,13; Lk 21,36

^{[[#fnm29][29]]} ℘ 1 Thess 5,2; 2 Petr 3,10; (43-44) Lk 12,39f

^{[[#fnm30][30]]} ℘ (45-51) Lk 12,42-46 ⇨Esyn: Synopse Nr. 297

^{[[#fnm31][31]]} ℘ 25,21.23

^{[[#fnm32][32]]} ℘ 24,42.44

^{[[#fnm33][33]]} ℘ 8,12
