:PROPERTIES:
:ID:       7233a04e-eb22-4d42-bd20-95edeb344de2
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_24.html][24]]
[[file:Mt_25.html][25]] *26* [[file:Mt_27.html][27]]
[[file:Mt_28.html][28]]

--------------

* Mt 26
  :PROPERTIES:
  :CUSTOM_ID: mt-26
  :END:

<<verses>>

<<v1>>
** Das Leiden und die Auferstehung Jesu: 26,1 - 28,20
   :PROPERTIES:
   :CUSTOM_ID: das-leiden-und-die-auferstehung-jesu-261---2820
   :END:
**** Der Beschluss des Hohen Rates: 26,1-5
     :PROPERTIES:
     :CUSTOM_ID: der-beschluss-des-hohen-rates-261-5
     :END:
1 Als Jesus seine Reden beendet hatte, sagte er zu seinen Jüngern:
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 305\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 Ihr wisst, dass in zwei Tagen das Paschafest beginnt; da wird der
Menschensohn ausgeliefert und gekreuzigt werden. ^{[[#fn4][4]]}

<<v3>>
3 Um die gleiche Zeit versammelten sich die Hohenpriester und die
Ältesten des Volkes im Palast des Hohenpriesters, der Kajaphas hieß,

<<v4>>
4 und beschlossen, Jesus mit List in ihre Gewalt zu bringen und ihn zu
töten. ^{[[#fn5][5]]}

<<v5>>
5 Sie sagten aber: Ja nicht am Fest, damit kein Aufruhr im Volk
entsteht.\\
\\

<<v6.7>>
**** Die Salbung in Betanien: 26,6-13
     :PROPERTIES:
     :CUSTOM_ID: die-salbung-in-betanien-266-13
     :END:
6.7 Als Jesus in Betanien im Haus Simons des Aussätzigen bei Tisch war,
kam eine Frau mit einem Alabastergefäß voll kostbarem, wohlriechendem Öl
zu ihm und goss es über sein Haar. ^{[[#fn6][6]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 306\\
$ŽG://ESyn0812/\\
\\

<<v8>>
8 Die Jünger wurden unwillig, als sie das sahen, und sagten: Wozu diese
Verschwendung?

<<v9>>
9 Man hätte das Öl teuer verkaufen und das Geld den Armen geben können.

<<v10>>
10 Jesus bemerkte ihren Unwillen und sagte zu ihnen: Warum lasst ihr die
Frau nicht in Ruhe? Sie hat ein gutes Werk an mir getan.

<<v11>>
11 Denn die Armen habt ihr immer bei euch, mich aber habt ihr nicht
immer. ^{[[#fn7][7]]}

<<v12>>
12 Als sie das Öl über mich goss, hat sie meinen Leib für das Begräbnis
gesalbt.

<<v13>>
13 Amen, ich sage euch: Überall auf der Welt, wo dieses Evangelium
verkündet wird, wird man sich an sie erinnern und erzählen, was sie
getan hat.\\
\\

<<v14>>
**** Der Verrat durch Judas: 26,14-16
     :PROPERTIES:
     :CUSTOM_ID: der-verrat-durch-judas-2614-16
     :END:
14 Darauf ging einer der Zwölf namens Judas Iskariot zu den
Hohenpriestern ^{[[#fn8][8]]}

<<v15>>
15 und sagte: Was wollt ihr mir geben, wenn ich euch Jesus ausliefere?
Und /sie zahlten/ ihm /dreißig Silberstücke./
^{[[#fn9][9]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 307\\
$ŽG://ESyn0812/\\
\\

<<v16>>
16 Von da an suchte er nach einer Gelegenheit, ihn auszuliefern.\\
\\

<<v17>>
**** Die Vorbereitung des Paschamahls: 26,17-19
     :PROPERTIES:
     :CUSTOM_ID: die-vorbereitung-des-paschamahls-2617-19
     :END:
17 Am ersten Tag des Festes der Ungesäuerten Brote gingen die Jünger zu
Jesus und fragten: Wo sollen wir das Paschamahl für dich vorbereiten?
^{[[#fn10][10]]}

<<v18>>
18 Er antwortete: Geht in die Stadt zu dem und dem und sagt zu ihm: Der
Meister lässt dir sagen: Meine Zeit ist da; bei dir will ich mit meinen
Jüngern das Paschamahl feiern. ^{[[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 308\\
$ŽG://ESyn0812/\\
\\

<<v19>>
19 Die Jünger taten, was Jesus ihnen aufgetragen hatte, und bereiteten
das Paschamahl vor.\\
\\

<<v20>>
**** Das Mahl: 26,20-29
     :PROPERTIES:
     :CUSTOM_ID: das-mahl-2620-29
     :END:
20 Als es Abend wurde, begab er sich mit den zwölf Jüngern zu Tisch.
^{[[#fn12][12]]}

<<v21>>
21 Und während sie aßen, sprach er: Amen, ich sage euch: Einer von euch
wird mich verraten und ausliefern.

<<v22>>
22 Da waren sie sehr betroffen und einer nach dem andern fragte ihn: Bin
ich es etwa, Herr? ^{[[#fn13][13]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 310\\
$ŽG://ESyn0812/\\
\\

<<v23>>
23 Er antwortete: Der, der die Hand mit mir in die Schüssel getaucht
hat, wird mich verraten.

<<v24>>
24 Der Menschensohn muss zwar seinen Weg gehen, wie die Schrift über ihn
sagt. Doch weh dem Menschen, durch den der Menschensohn verraten wird.
Für ihn wäre es besser, wenn er nie geboren wäre. ^{[[#fn14][14]]}

<<v25>>
25 Da fragte Judas, der ihn verriet: Bin ich es etwa, Rabbi? Jesus sagte
zu ihm: Du sagst es.

<<v26>>
26 Während des Mahls nahm Jesus das Brot und sprach den Lobpreis; dann
brach er das Brot, reichte es den Jüngern und sagte: Nehmt und esst; das
ist mein Leib. ^{[[#fn15][15]]}

<<v27>>
27 Dann nahm er den Kelch, sprach das Dankgebet und reichte ihn den
Jüngern mit den Worten: Trinkt alle daraus;
^{[[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 311\\
$ŽG://ESyn0812/\\
\\

<<v28>>
28 das ist mein Blut, /das Blut des Bundes,/ das für viele vergossen
wird zur Vergebung der Sünden. ^{[[#fn17][17]]}

<<v29>>
29 Ich sage euch: Von jetzt an werde ich nicht mehr von der Frucht des
Weinstocks trinken bis zu dem Tag, an dem ich mit euch von neuem davon
trinke im Reich meines Vaters.\\
\\

<<v30>>
**** Der Gang zum Ölberg: 26,30-35
     :PROPERTIES:
     :CUSTOM_ID: der-gang-zum-ölberg-2630-35
     :END:
30 Nach dem Lobgesang gingen sie zum Ölberg hinaus. ^{[[#fn18][18]]}

<<v31>>
31 Da sagte Jesus zu ihnen: Ihr alle werdet in dieser Nacht an mir
Anstoß nehmen und zu Fall kommen; denn in der Schrift steht: /Ich werde
den Hirten erschlagen, dann werden sich die Schafe der Herde
zerstreuen./ ^{[[#fn19][19]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 315\\
$ŽG://ESyn0812/\\
\\

<<v32>>
32 Aber nach meiner Auferstehung werde ich euch nach Galiläa
vorausgehen. ^{[[#fn20][20]]}

<<v33>>
33 Petrus erwiderte ihm: Und wenn alle an dir Anstoß nehmen - ich
niemals!

<<v34>>
34 Jesus entgegnete ihm: Amen, ich sage dir: In dieser Nacht, noch ehe
der Hahn kräht, wirst du mich dreimal verleugnen. ^{[[#fn21][21]]}

<<v35>>
35 Da sagte Petrus zu ihm: Und wenn ich mit dir sterben müsste - ich
werde dich nie verleugnen. Das Gleiche sagten auch alle anderen
Jünger.\\
\\

<<v36>>
**** Das Gebet in Getsemani: 26,36-46
     :PROPERTIES:
     :CUSTOM_ID: das-gebet-in-getsemani-2636-46
     :END:
36 Darauf kam Jesus mit den Jüngern zu einem Grundstück, das man
Getsemani nennt, und sagte zu ihnen: Setzt euch und wartet hier, während
ich dort bete. ^{[[#fn22][22]]}

<<v37>>
37 Und er nahm Petrus und die beiden Söhne des Zebedäus mit sich. Da
ergriff ihn Angst und Traurigkeit, ^{[[#fn23][23]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 330\\
$ŽG://ESyn0812/\\
\\

<<v38>>
38 und er sagte zu ihnen: Meine Seele ist zu Tode betrübt. Bleibt hier
und wacht mit mir! ^{[[#fn24][24]]}

<<v39>>
39 Und er ging ein Stück weiter, warf sich zu Boden und betete: Mein
Vater, wenn es möglich ist, gehe dieser Kelch an mir vorüber. Aber nicht
wie ich will, sondern wie du willst. ^{[[#fn25][25]]}

<<v40>>
40 Und er ging zu den Jüngern zurück und fand sie schlafend. Da sagte er
zu Petrus: Konntet ihr nicht einmal eine Stunde mit mir wachen?

<<v41>>
41 Wacht und betet, damit ihr nicht in Versuchung geratet. Der Geist ist
willig, aber das Fleisch ist schwach.

<<v42>>
42 Dann ging er zum zweiten Mal weg und betete: Mein Vater, wenn dieser
Kelch an mir nicht vorübergehen kann, ohne dass ich ihn trinke, geschehe
dein Wille.

<<v43>>
43 Als er zurückkam, fand er sie wieder schlafend, denn die Augen waren
ihnen zugefallen.

<<v44>>
44 Und er ging wieder von ihnen weg und betete zum dritten Mal mit den
gleichen Worten.

<<v45>>
45 Danach kehrte er zu den Jüngern zurück und sagte zu ihnen: Schlaft
ihr immer noch und ruht euch aus? Die Stunde ist gekommen; jetzt wird
der Menschensohn den Sündern ausgeliefert. ^{[[#fn26][26]]}

<<v46>>
46 Steht auf, wir wollen gehen! Seht, der Verräter, der mich ausliefert,
ist da.\\
\\

<<v47>>
**** Die Gefangennahme: 26,47-56
     :PROPERTIES:
     :CUSTOM_ID: die-gefangennahme-2647-56
     :END:
47 Während er noch redete, kam Judas, einer der Zwölf, mit einer großen
Schar von Männern, die mit Schwertern und Knüppeln bewaffnet waren; sie
waren von den Hohenpriestern und den Ältesten des Volkes geschickt
worden. ^{[[#fn27][27]]}

<<v48>>
48 Der Verräter hatte mit ihnen ein Zeichen verabredet und gesagt: Der,
den ich küssen werde, der ist es; nehmt ihn fest.
^{[[#fn28][28]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 331\\
$ŽG://ESyn0812/\\
\\

<<v49>>
49 Sogleich ging er auf Jesus zu und sagte: Sei gegrüßt, Rabbi! Und er
küsste ihn.

<<v50>>
50 Jesus erwiderte ihm: Freund, dazu bist du gekommen? Da gingen sie auf
Jesus zu, ergriffen ihn und nahmen ihn fest. ^{[[#fn29][29]]}

<<v51>>
51 Doch einer von den Begleitern Jesu zog sein Schwert, schlug auf den
Diener des Hohenpriesters ein und hieb ihm ein Ohr ab.

<<v52>>
52 Da sagte Jesus zu ihm: Steck dein Schwert in die Scheide; denn alle,
die zum Schwert greifen, werden durch das Schwert umkommen.

<<v53>>
53 Oder glaubst du nicht, mein Vater würde mir sogleich mehr als zwölf
Legionen Engel schicken, wenn ich ihn darum bitte?
^{[[#fn30][30]][[#fn31][31]]}

<<v54>>
54 Wie würde dann aber die Schrift erfüllt, nach der es so geschehen
muss?

<<v55>>
55 Darauf sagte Jesus zu den Männern: Wie gegen einen Räuber seid ihr
mit Schwertern und Knüppeln ausgezogen, um mich festzunehmen. Tag für
Tag saß ich im Tempel und lehrte und ihr habt mich nicht verhaftet.
^{[[#fn32][32]][[#fn33][33]]}

<<v56>>
56 Das alles aber ist geschehen, damit die Schriften der Propheten in
Erfüllung gehen. Da verließen ihn alle Jünger und flohen.
^{[[#fn34][34]]}\\
\\

<<v57>>
**** Das Verhör vor dem Hohen Rat: 26,57-68
     :PROPERTIES:
     :CUSTOM_ID: das-verhör-vor-dem-hohen-rat-2657-68
     :END:
57 Nach der Verhaftung führte man Jesus zum Hohenpriester Kajaphas, bei
dem sich die Schriftgelehrten und die Ältesten versammelt hatten.
^{[[#fn35][35]][[#fn36][36]]}

<<v58>>
58 Petrus folgte Jesus von weitem bis zum Hof des hohepriesterlichen
Palastes; er ging in den Hof hinein und setzte sich zu den Dienern, um
zu sehen, wie alles ausgehen würde. ^{[[#fn37][37]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 332\\
$ŽG://ESyn0812/\\
\\

<<v59>>
59 Die Hohenpriester und der ganze Hohe Rat bemühten sich um falsche
Zeugenaussagen gegen Jesus, um ihn zum Tod verurteilen zu können.

<<v60>>
60 Sie erreichten aber nichts, obwohl viele falsche Zeugen auftraten.
Zuletzt kamen zwei Männer

<<v61>>
61 und behaupteten: Er hat gesagt: Ich kann den Tempel Gottes
niederreißen und in drei Tagen wieder aufbauen. ^{[[#fn38][38]]}

<<v62>>
62 Da stand der Hohepriester auf und fragte Jesus: Willst du nichts
sagen zu dem, was diese Leute gegen dich vorbringen?

<<v63>>
63 Jesus aber schwieg. Darauf sagte der Hohepriester zu ihm: Ich
beschwöre dich bei dem lebendigen Gott, sag uns: Bist du der Messias,
der Sohn Gottes? ^{[[#fn39][39]]}

<<v64>>
64 Jesus antwortete: Du hast es gesagt. Doch ich erkläre euch: Von nun
an werdet ihr /den Menschensohn zur Rechten/ der Macht /sitzen/ und /auf
den Wolken des Himmels kommen/ sehen. ^{[[#fn40][40]][[#fn41][41]]}

<<v65>>
65 Da zerriss der Hohepriester sein Gewand und rief: Er hat Gott
gelästert! Wozu brauchen wir noch Zeugen? Jetzt habt ihr die
Gotteslästerung selbst gehört. ^{[[#fn42][42]]}

<<v66>>
66 Was ist eure Meinung? Sie antworteten: Er ist schuldig und muss
sterben.

<<v67>>
67 Dann spuckten sie ihm ins Gesicht und schlugen ihn. Andere ohrfeigten
ihn ^{[[#fn43][43]]}

<<v68>>
68 und riefen: Messias, du bist doch ein Prophet! Sag uns: Wer hat dich
geschlagen?\\
\\

<<v69>>
**** Die Verleugnung durch Petrus: 26,69-75
     :PROPERTIES:
     :CUSTOM_ID: die-verleugnung-durch-petrus-2669-75
     :END:
69 Petrus aber saß draußen im Hof. Da trat eine Magd zu ihm und sagte:
Auch du warst mit diesem Jesus aus Galiläa zusammen. ^{[[#fn44][44]]}

<<v70>>
70 Doch er leugnete es vor allen Leuten und sagte: Ich weiß nicht, wovon
du redest. ^{[[#fn45][45]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 333\\
$ŽG://ESyn0812/\\
\\

<<v71>>
71 Und als er zum Tor hinausgehen wollte, sah ihn eine andere Magd und
sagte zu denen, die dort standen: Der war mit Jesus aus Nazaret
zusammen.

<<v72>>
72 Wieder leugnete er und schwor: Ich kenne den Menschen nicht.

<<v73>>
73 Kurz darauf kamen die Leute, die dort standen, zu Petrus und sagten:
Wirklich, auch du gehörst zu ihnen, deine Mundart verrät dich.

<<v74>>
74 Da fing er an, sich zu verfluchen und schwor: Ich kenne den Menschen
nicht. Gleich darauf krähte ein Hahn,

<<v75>>
75 und Petrus erinnerte sich an das, was Jesus gesagt hatte: Ehe der
Hahn kräht, wirst du mich dreimal verleugnen. Und er ging hinaus und
weinte bitterlich. ^{[[#fn46][46]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-5) Mk 14,1f; Lk 22,1f; Joh 11,47-53

^{[[#fnm2][2]]} 1-28,20: Über Markus hinaus, dem Matthäus in seinem
Passionsbericht weithin folgt, bietet Matthäus folgendes Sondergut:
Traum der Frau des Pilatus (27,19), Ende des Judas (27,3-10), Übernahme
der Verantwortung für den Tod Jesu durch das Volk (27,24f), Öffnung der
Gräber beim Tod Jesu (27,51-53), Geschichte von den Grabwächtern
(27,62-66; 28,2-4.11-15).

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 305

^{[[#fnm4][4]]} ℘ 16,21

^{[[#fnm5][5]]} ℘ (4f) 21,46

^{[[#fnm6][6]]} ℘ (6-13) Mk 14,3-9; Lk 7,36-50; Joh 12,1-8 ⇨Esyn:
Synopse Nr. 306

^{[[#fnm7][7]]} ℘ Dtn 15,11

^{[[#fnm8][8]]} ℘ (14-16) Mk 14,10f; Lk 22,3-6

^{[[#fnm9][9]]} ℘ Joh 11,57; 13,2; Sach 11,12 ⇨Esyn: Synopse Nr. 307

^{[[#fnm10][10]]} ℘ Ex 12,14-20; (17-19) Mk 14,12-16; Lk 22,7-13

^{[[#fnm11][11]]} ℘ ⇨Esyn: Synopse Nr. 308

^{[[#fnm12][12]]} ℘ (20-29) Mk 14,17-25; Lk 22,14-23; (20-25) Joh
13,2.21-30

^{[[#fnm13][13]]} ℘ ⇨Esyn: Synopse Nr. 310

^{[[#fnm14][14]]} ℘ Ps 22,7f.16-18; Jes 53,8f

^{[[#fnm15][15]]} ℘ (26-28) 1 Kor 11,23-25

^{[[#fnm16][16]]} ℘ 1 Kor 10,16 ⇨Esyn: Synopse Nr. 311

^{[[#fnm17][17]]} ℘ Ex 24,8; Jer 31,31; Hebr 7,22; 9,15

^{[[#fnm18][18]]} ℘ Lk 22,39; Joh 18,1; (30-35) Mk 14,26-31

^{[[#fnm19][19]]} ℘ 26,56; Sach 13,7; Joh 16,32 ⇨Esyn: Synopse Nr. 315

^{[[#fnm20][20]]} ℘ 28,7.16

^{[[#fnm21][21]]} ℘ 26,75; (34-35) Lk 22,31-34; Joh 13,36-38

^{[[#fnm22][22]]} ℘ (36-46) Mk 14,32-42; Lk 22,39-46

^{[[#fnm23][23]]} ℘ Hebr 5,7 ⇨Esyn: Synopse Nr. 330

^{[[#fnm24][24]]} ℘ Ps 42,6.12; 43,5

^{[[#fnm25][25]]} ℘ Joh 12,27; Mt 20,22; Joh 6,38; 18,11; Hebr 10,9

^{[[#fnm26][26]]} ℘ Joh 2,4; 7,30; 8,20; 12,23; 13,1; 17,1

^{[[#fnm27][27]]} ℘ (47-56) Mk 14,43-50; Lk 22,47-53; Joh 18,3-12

^{[[#fnm28][28]]} ℘ ⇨Esyn: Synopse Nr. 331

^{[[#fnm29][29]]} Andere Übersetzungsmöglichkeit: Freund, tu, wozu du
gekommen bist. Die herkömmliche Übersetzung «Freund, wozu bist du
gekommen?» ist vom griechischen Text her nicht zu rechtfertigen.

^{[[#fnm30][30]]} ℘ Lk 2,13

^{[[#fnm31][31]]} Eine römische Legion umfasste 6000 Mann.

^{[[#fnm32][32]]} ℘ Lk 19,47; Joh 18,20

^{[[#fnm33][33]]} Darauf, wörtlich: In jener Stunde.

^{[[#fnm34][34]]} ℘ 26,31; Joh 16,32

^{[[#fnm35][35]]} ℘ (57-68) Mk 14,53-65; Lk 22,54f.66-71; Joh 18,12-24

^{[[#fnm36][36]]} Josef Kajaphas war von 18 bis 37 n. Chr. amtierender
Hoherpriester. Das jüdische Prozessrecht der Zeit Jesu ist nicht genau
bekannt.

^{[[#fnm37][37]]} ℘ ⇨Esyn: Synopse Nr. 332

^{[[#fnm38][38]]} ℘ 27,40; Joh 2,19; Apg 6,14

^{[[#fnm39][39]]} ℘ Jes 53,7; Mt 16,16; Joh 10,24

^{[[#fnm40][40]]} ℘ Dan 7,13; Ps 110,1; Mt 24,30; Mk 13,26; Lk 21,27

^{[[#fnm41][41]]} Der Ausdruck «die Macht» ist Umschreibung für Gott.

^{[[#fnm42][42]]} ℘ Lev 24,16; Joh 19,7

^{[[#fnm43][43]]} ℘ Jes 50,6

^{[[#fnm44][44]]} ℘ (69-75) Mk 14,66-72; Lk 22,56-62; Joh 18,15-18.25-27

^{[[#fnm45][45]]} ℘ ⇨Esyn: Synopse Nr. 333

^{[[#fnm46][46]]} ℘ 26,34
