:PROPERTIES:
:ID:       64fc0493-cc91-43ce-a455-62c419bb0200
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Evangelium nach Matthäus* --
[[file:Mt_1.html][1]] ... [[file:Mt_19.html][19]]
[[file:Mt_20.html][20]] *21* [[file:Mt_22.html][22]]
[[file:Mt_23.html][23]] ... [[file:Mt_28.html][28]]

--------------

* Mt 21
  :PROPERTIES:
  :CUSTOM_ID: mt-21
  :END:

<<verses>>

<<v1>>
*** Die Auseinandersetzung mit den Gegnern in Jerusalem: 21,1 - 23,39
    :PROPERTIES:
    :CUSTOM_ID: die-auseinandersetzung-mit-den-gegnern-in-jerusalem-211---2339
    :END:
**** Der Einzug in Jerusalem: 21,1-11
     :PROPERTIES:
     :CUSTOM_ID: der-einzug-in-jerusalem-211-11
     :END:
1 Als sich Jesus mit seinen Begleitern Jerusalem näherte und nach
Betfage am Ölberg kam, schickte er zwei Jünger voraus
^{[[#fn1][1]][[#fn2][2]][[#fn3][3]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 269\\
$ŽG://ESyn0812/\\
\\

<<v2>>
2 und sagte zu ihnen: Geht in das Dorf, das vor euch liegt; dort werdet
ihr eine Eselin angebunden finden und ein Fohlen bei ihr. Bindet sie los
und bringt sie zu mir!

<<v3>>
3 Und wenn euch jemand zur Rede stellt, dann sagt: Der Herr braucht sie,
er lässt sie aber bald zurückbringen. ^{[[#fn4][4]]}

<<v4>>
4 Das ist geschehen, damit sich erfüllte, was durch den Propheten gesagt
worden ist:\\
\\

<<v5>>
5 /Sagt der Tochter Zion:/ /\\
 /Siehe, dein König kommt zu dir./ /\\
 /Er ist friedfertig/ /\\
 /und er reitet auf einer Eselin/ /\\
 /und auf einem Fohlen,/ /\\
 /dem Jungen eines Lasttiers./ ^{[[#fn5][5]]}\\
\\

<<v6>>
6 Die Jünger gingen und taten, was Jesus ihnen aufgetragen hatte.

<<v7>>
7 Sie brachten die Eselin und das Fohlen, legten ihre Kleider auf sie,
und er setzte sich darauf.

<<v8>>
8 Viele Menschen breiteten ihre Kleider auf der Straße aus, andere
schnitten Zweige von den Bäumen und streuten sie auf den Weg.\\
\\

<<v9>>
9 Die Leute aber, die vor ihm hergingen und die ihm folgten, riefen:
/Hosanna/ dem Sohn Davids! /\\
 /Gesegnet sei er, der kommt im Namen des Herrn./ /\\
 /Hosanna/ in der Höhe! ^{[[#fn6][6]][[#fn7][7]]}\\
\\

<<v10>>
10 Als er in Jerusalem einzog, geriet die ganze Stadt in Aufregung, und
man fragte: Wer ist das? ^{[[#fn8][8]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 271\\
$ŽG://ESyn0812/\\
\\

<<v11>>
11 Die Leute sagten: Das ist der Prophet Jesus von Nazaret in Galiläa.\\
\\

<<v12>>
**** Die Tempelreinigung: 21,12-17
     :PROPERTIES:
     :CUSTOM_ID: die-tempelreinigung-2112-17
     :END:
12 Jesus ging in den Tempel und trieb alle Händler und Käufer aus dem
Tempel hinaus; er stieß die Tische der Geldwechsler und die Stände der
Taubenhändler um
^{[[#fn9][9]][[#fn10][10]][[#fn11][11]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 100\\
$ŽG://ESyn0812/\\
\\

<<v13>>
13 und sagte: In der Schrift steht: /Mein Haus soll ein Haus des Gebetes
sein./ Ihr aber macht daraus /eine Räuberhöhle./ ^{[[#fn12][12]]}

<<v14>>
14 Im Tempel kamen Lahme und Blinde zu ihm und er heilte sie.

<<v15>>
15 Als nun die Hohenpriester und die Schriftgelehrten die Wunder sahen,
die er tat, und die Kinder im Tempel rufen hörten: Hosanna dem Sohn
Davids!, da wurden sie ärgerlich

<<v16>>
16 und sagten zu ihm: Hörst du, was sie rufen? Jesus antwortete ihnen:
Ja, ich höre es. Habt ihr nie gelesen: /Aus dem Mund der Kinder und
Säuglinge schaffst du dir Lob/? ^{[[#fn13][13]]}

<<v17>>
17 Und er ließ sie stehen und ging aus der Stadt hinaus nach Betanien;
dort übernachtete er.\\
\\

<<v18>>
**** Die Verfluchung eines Feigenbaums: 21,18-22
     :PROPERTIES:
     :CUSTOM_ID: die-verfluchung-eines-feigenbaums-2118-22
     :END:
18 Als er am Morgen in die Stadt zurückkehrte, hatte er Hunger.
^{[[#fn14][14]][[#fn15][15]][[#fn16][16]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 272\\
$ŽG://ESyn0812/\\
\\

<<v19>>
19 Da sah er am Weg einen Feigenbaum und ging auf ihn zu, fand aber nur
Blätter daran. Da sagte er zu ihm: In Ewigkeit soll keine Frucht mehr an
dir wachsen. Und der Feigenbaum verdorrte auf der Stelle.
^{[[#fn17][17]]}

<<v20>>
20 Als die Jünger das sahen, fragten sie erstaunt: Wie konnte der
Feigenbaum so plötzlich verdorren? ^{[[#fn18][18]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 275\\
$ŽG://ESyn0812/\\
\\

<<v21>>
21 Jesus antwortete ihnen: Amen, das sage ich euch: Wenn ihr Glauben
habt und nicht zweifelt, dann werdet ihr nicht nur das vollbringen, was
ich mit dem Feigenbaum getan habe; selbst wenn ihr zu diesem Berg sagt:
Heb dich empor und stürz dich ins Meer!, wird es geschehen.
^{[[#fn19][19]]}

<<v22>>
22 Und alles, was ihr im Gebet erbittet, werdet ihr erhalten, wenn ihr
glaubt. ^{[[#fn20][20]]}\\
\\

<<v23>>
**** Die Frage nach der Vollmacht Jesu: 21,23-27
     :PROPERTIES:
     :CUSTOM_ID: die-frage-nach-der-vollmacht-jesu-2123-27
     :END:
23 Als er in den Tempel ging und dort lehrte, kamen die Hohenpriester
und die Ältesten des Volkes zu ihm und fragten: Mit welchem Recht tust
du das alles? Wer hat dir dazu die Vollmacht gegeben?
^{[[#fn21][21]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 276\\
$ŽG://ESyn0812/\\
\\

<<v24>>
24 Jesus antwortete ihnen: Auch ich will euch eine Frage stellen. Wenn
ihr mir darauf antwortet, dann werde ich euch sagen, mit welchem Recht
ich das tue.

<<v25>>
25 Woher stammte die Taufe des Johannes? Vom Himmel oder von den
Menschen? Da überlegten sie und sagten zueinander: Wenn wir antworten:
Vom Himmel!, so wird er zu uns sagen: Warum habt ihr ihm dann nicht
geglaubt?

<<v26>>
26 Wenn wir aber antworten: Von den Menschen!, dann müssen wir uns vor
den Leuten fürchten; denn alle halten Johannes für einen Propheten.
^{[[#fn22][22]]}

<<v27>>
27 Darum antworteten sie Jesus: Wir wissen es nicht. Da erwiderte er:
Dann sage auch ich euch nicht, mit welchem Recht ich das alles tue.\\
\\

<<v28>>
**** Das Gleichnis von den ungleichen Söhnen: 21,28-32
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-von-den-ungleichen-söhnen-2128-32
     :END:
28 Was meint ihr? Ein Mann hatte zwei Söhne. Er ging zum ersten und
sagte: Mein Sohn, geh und arbeite heute im Weinberg!
^{[[#fn23][23]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 277\\
$ŽG://ESyn0812/\\
\\

<<v29>>
29 Er antwortete: Ja, Herr!, ging aber nicht. ^{[[#fn24][24]]}

<<v30>>
30 Da wandte er sich an den zweiten Sohn und sagte zu ihm dasselbe.
Dieser antwortete: Ich will nicht. Später aber reute es ihn und er ging
doch.

<<v31>>
31 Wer von den beiden hat den Willen seines Vaters erfüllt? Sie
antworteten: Der zweite. Da sagte Jesus zu ihnen: Amen, das sage ich
euch: Zöllner und Dirnen gelangen eher in das Reich Gottes als ihr.
^{[[#fn25][25]]}

<<v32>>
32 Denn Johannes ist gekommen, um euch den Weg der Gerechtigkeit zu
zeigen, und ihr habt ihm nicht geglaubt; aber die Zöllner und die Dirnen
haben ihm geglaubt. Ihr habt es gesehen und doch habt ihr nicht bereut
und ihm nicht geglaubt.\\
\\

<<v33>>
**** Das Gleichnis von den bösen Winzern: 21,33-46
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-von-den-bösen-winzern-2133-46
     :END:
33 Hört noch ein anderes Gleichnis: Es war ein Gutsbesitzer, der /legte
einen Weinberg an, zog ringsherum einen Zaun, hob eine Kelter aus und
baute einen Turm./ Dann verpachtete er den Weinberg an Winzer und reiste
in ein anderes Land.
^{[[#fn26][26]][[#fn27][27]][[#fn28][28]]}]//ESyn0812/<t>\\
$ŽT://ESyn0812/Nr. 278\\
$ŽG://ESyn0812/\\
\\

<<v34>>
34 Als nun die Erntezeit kam, schickte er seine Knechte zu den Winzern,
um seinen Anteil an den Früchten holen zu lassen.

<<v35>>
35 Die Winzer aber packten seine Knechte; den einen prügelten sie, den
andern brachten sie um, einen dritten steinigten sie. ^{[[#fn29][29]]}

<<v36>>
36 Darauf schickte er andere Knechte, mehr als das erste Mal; mit ihnen
machten sie es genauso.

<<v37>>
37 Zuletzt sandte er seinen Sohn zu ihnen; denn er dachte: Vor meinem
Sohn werden sie Achtung haben.

<<v38>>
38 Als die Winzer den Sohn sahen, sagten sie zueinander: Das ist der
Erbe. Auf, wir wollen ihn töten, damit wir seinen Besitz erben.

<<v39>>
39 Und sie packten ihn, warfen ihn aus dem Weinberg hinaus und brachten
ihn um.

<<v40>>
40 Wenn nun der Besitzer des Weinbergs kommt: Was wird er mit solchen
Winzern tun?

<<v41>>
41 Sie sagten zu ihm: Er wird diesen bösen Menschen ein böses Ende
bereiten und den Weinberg an andere Winzer verpachten, die ihm die
Früchte abliefern, wenn es Zeit dafür ist.\\
\\

<<v42>>
42 Und Jesus sagte zu ihnen: Habt ihr nie in der Schrift gelesen: /Der
Stein, den die Bauleute verworfen haben,/ /\\
 /er ist zum Eckstein geworden;/ /\\
 /das hat der Herr vollbracht,/ /\\
 /vor unseren Augen geschah dieses Wunder/?
^{[[#fn30][30]][[#fn31][31]]}\\
\\

<<v44>>
44 Und wer auf diesen Stein fällt, der wird zerschellen; auf wen der
Stein aber fällt, den wird er zermalmen. ^{[[#fn32][32]]}

<<v43>>
43 Darum sage ich euch: Das Reich Gottes wird euch weggenommen und einem
Volk gegeben werden, das die erwarteten Früchte bringt.

<<v45>>
45 Als die Hohenpriester und die Pharisäer seine Gleichnisse hörten,
merkten sie, dass er von ihnen sprach.

<<v46>>
46 Sie hätten ihn gern verhaften lassen; aber sie fürchteten sich vor
den Leuten, weil alle ihn für einen Propheten hielten.
^{[[#fn33][33]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-11) Mk 11,1-11; Lk 19,28-40; Joh 12,12-19

^{[[#fnm2][2]]} 1-11: Der Evangelist deutet den Einzug Jesu im Licht von
Sach 9,9: Der Messias wird als Vertreter der armen Leute eine
friedliche, sozial gerechte Herrschaft aufrichten.

^{[[#fnm3][3]]} ℘ ⇨Esyn: Synopse Nr. 269

^{[[#fnm4][4]]} Andere Übersetzungsmöglichkeit: Der Herr braucht sie.
Und er (der Besitzer, der euch zur Rede stellt) wird sie euch sofort
mitgeben.

^{[[#fnm5][5]]} ℘ Jes 62,11; Sach 9,9

^{[[#fnm6][6]]} ℘ Ps 118,25f; Mt 23,39; Lk 13,35

^{[[#fnm7][7]]} 9.15: Ursprüngliche Bedeutung von «Hosanna»: Bring doch
Hilfe!; später ist das Wort unter Verlust des ursprünglichen Sinns zur
liturgischen Formel geworden.

^{[[#fnm8][8]]} ℘ ⇨Esyn: Synopse Nr. 271

^{[[#fnm9][9]]} ℘ (12-17) Mk 11,15-19; Lk 19,45-48; Joh 2,13-16

^{[[#fnm10][10]]} Im Tempelbezirk konnten die Tempelbesucher Opfertiere
kaufen und zur Bezahlung der Tempelsteuer heidnisches Geld in Münzen
ohne heidnische Götter- oder Herrscherbilder wechseln.

^{[[#fnm11][11]]} ℘ ⇨Esyn: Synopse Nr. 100

^{[[#fnm12][12]]} ℘ Jes 56,7; Jer 7,11

^{[[#fnm13][13]]} ℘ Ps 8,3

^{[[#fnm14][14]]} ℘ (18-19) Mk 11,12-14

^{[[#fnm15][15]]} 18-22: Der unfruchtbare Feigenbaum ist Bild für das
Volk Gottes, das den Glauben verweigert (vgl. Jer 8,13; Lk 13,6-9).

^{[[#fnm16][16]]} ℘ ⇨Esyn: Synopse Nr. 272

^{[[#fnm17][17]]} ℘ Lk 13,6

^{[[#fnm18][18]]} ℘ (20-22) Mk 11,20-25 ⇨Esyn: Synopse Nr. 275

^{[[#fnm19][19]]} ℘ Lk 17,6

^{[[#fnm20][20]]} ℘ 7,7

^{[[#fnm21][21]]} ℘ (23-27) Mk 11,27-33; Lk 20,1-8 ⇨Esyn: Synopse Nr.
276

^{[[#fnm22][22]]} ℘ 14,5

^{[[#fnm23][23]]} ℘ ⇨Esyn: Synopse Nr. 277

^{[[#fnm24][24]]} 29-31: In einer Reihe wichtiger Textzeugen sagt der
erste Sohn nein, geht aber dann doch; der zweite Sohn sagt ja, geht aber
nicht. In diesem Fall hat der erste Sohn den Willen des Vaters erfüllt.

^{[[#fnm25][25]]} ℘ Lk 7,29f

^{[[#fnm26][26]]} ℘ Jes 5,1f G; (33-46) Mk 12,1-12; Lk 20,9-19

^{[[#fnm27][27]]} 33-46: Mit dem Weinberg Gottes ist Israel gemeint
(vgl. Jes 5, 1-7).

^{[[#fnm28][28]]} ℘ ⇨Esyn: Synopse Nr. 278

^{[[#fnm29][29]]} ℘ 22,6

^{[[#fnm30][30]]} ℘ Ps 118,22f

^{[[#fnm31][31]]} Die Übersetzung «das hat der Herr vollbracht» nimmt
Rücksicht auf den hebräischen Text von Ps 118,22. Der griechische Text
lautet wörtlich übersetzt: ihn hat der Herr gemacht und er ist wunderbar
in unseren Augen.

^{[[#fnm32][32]]} Dieser Vers, der bei einigen alten Textzeugen fehlt,
ist irrtümlicherweise hinter V. 43 überliefert.

^{[[#fnm33][33]]} ℘ 26,4f
