:PROPERTIES:
:ID:       4296877e-1450-41db-9aee-6bfe5c749562
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Offenbarung des Johannes* --
[[file:Offb_1.html][1]] ... [[file:Offb_17.html][17]]
[[file:Offb_18.html][18]] *19* [[file:Offb_20.html][20]]
[[file:Offb_21.html][21]] [[file:Offb_22.html][22]]

--------------

* Offb 19
  :PROPERTIES:
  :CUSTOM_ID: offb-19
  :END:

<<verses>>

<<v1>>
**** Jubel im Himmel: 19,1-10
     :PROPERTIES:
     :CUSTOM_ID: jubel-im-himmel-191-10
     :END:
1 Danach hörte ich etwas wie den lauten Ruf einer großen Schar im
Himmel: Halleluja! /\\
 Das Heil und die Herrlichkeit und die Macht /\\
 ist bei unserm Gott. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 /Seine Urteile sind wahr und gerecht./ /\\
 Er hat die große Hure gerichtet, /\\
 die mit ihrer Unzucht die Erde verdorben hat. /Er hat Rache genommen
für das Blut seiner Knechte,/ /\\
 das an ihren Händen klebte. ^{[[#fn2][2]]}\\
\\

<<v3>>
3 Noch einmal riefen sie: Halleluja! /\\
 /Der Rauch/ der Stadt /steigt auf/ in alle Ewigkeit. ^{[[#fn3][3]]}

<<v4>>
4 Und die vierundzwanzig Ältesten und die vier Lebewesen fielen nieder
vor Gott, /der auf dem Thron sitzt,/ beteten ihn an und riefen: Amen,
halleluja! ^{[[#fn4][4]]}\\
\\

<<v5>>
5 Und eine Stimme kam vom Thron her: /Preist/ unsern Gott, /all/ seine
/Knechte/ /\\
 /und alle, die ihn fürchten, Kleine und Große!/ ^{[[#fn5][5]]}\\
\\

<<v6>>
6 Da hörte ich etwas wie den Ruf einer großen Schar und /wie das
Rauschen gewaltiger Wassermassen/ und wie das Rollen mächtiger Donner:
Halleluja! /\\
 /Denn König geworden ist der Herr,/ unser Gott, /\\
 der Herrscher über die ganze Schöpfung. ^{[[#fn6][6]]}\\
\\

<<v7>>
7 /Wir wollen uns freuen und jubeln/ /\\
 und ihm die Ehre erweisen. Denn gekommen ist die Hochzeit des Lammes
/\\
 und seine Frau hat sich bereit gemacht. ^{[[#fn7][7]]}\\
\\

<<v8>>
8 Sie durfte sich kleiden in strahlend reines Leinen. /\\
 Das Leinen bedeutet die gerechten Taten der Heiligen. ^{[[#fn8][8]]}

<<v9>>
9 Jemand sagte zu mir: Schreib auf: Selig, wer zum Hochzeitsmahl des
Lammes eingeladen ist. Dann sagte er zu mir: Das sind zuverlässige
Worte, es sind Worte Gottes. ^{[[#fn9][9]]}

<<v10>>
10 Und ich fiel ihm zu Füßen, um ihn anzubeten. Er aber sagte zu mir: Tu
das nicht! Ich bin ein Knecht wie du und deine Brüder, die das Zeugnis
Jesu festhalten. Gott bete an! Das Zeugnis Jesu ist der Geist
prophetischer Rede. ^{[[#fn10][10]]}\\
\\

<<v11>>
**** Sieg über das Tier und seinen Propheten: 19,11-21
     :PROPERTIES:
     :CUSTOM_ID: sieg-über-das-tier-und-seinen-propheten-1911-21
     :END:
11 Dann sah ich /den Himmel offen,/ und siehe, da war ein weißes Pferd,
und der, der auf ihm saß, heißt «Der Treue und Wahrhaftige»; /gerecht
richtet er/ und führt er Krieg. ^{[[#fn11][11]][[#fn12][12]]}

<<v12>>
12 /Seine Augen/ waren wie /Feuerflammen/ und auf dem Haupt trug er
viele Diademe; und auf ihm stand ein Name, den er allein kennt.
^{[[#fn13][13]]}

<<v13>>
13 Bekleidet war er mit einem blutgetränkten Gewand; und sein Name heißt
«Das Wort Gottes». ^{[[#fn14][14]][[#fn15][15]]}

<<v14>>
14 Die Heere des Himmels folgten ihm auf weißen Pferden; sie waren in
reines, weißes Leinen gekleidet.

<<v15>>
15 /Aus seinem Mund/ kam /ein scharfes Schwert;/ mit ihm wird er die
Völker schlagen. /Und er herrscht über sie mit eisernem Zepter, und/ er
/tritt die Kelter/ des Weines, des rächenden Zornes Gottes, des
Herrschers über die ganze Schöpfung. ^{[[#fn16][16]]}

<<v16>>
16 Auf seinem Gewand und auf seiner Hüfte trägt er den Namen: «König
/der Könige/ und /Herr der Herren»./ ^{[[#fn17][17]]}

<<v17>>
17 Dann sah ich einen Engel, der in der Sonne stand. Er rief mit lauter
Stimme allen Vögeln zu, die hoch am Himmel flogen: /Kommt her!
Versammelt euch zum großen Mahl/ Gottes. ^{[[#fn18][18]]}

<<v18>>
18 /Fresst Fleisch/ von Königen, von Heerführern und /von Helden,/
Fleisch /von Pferden/ und ihren /Reitern,/ Fleisch von allen, von Freien
und Sklaven, von Großen und Kleinen!

<<v19>>
19 Dann sah ich das Tier und die /Könige der Erde/ und ihre Heere
versammelt, um mit dem Reiter und seinem Heer Krieg zu führen.
^{[[#fn19][19]]}

<<v20>>
20 Aber das Tier wurde gepackt und mit ihm der falsche Prophet; er hatte
vor seinen Augen Zeichen getan und dadurch alle verführt, die das
Kennzeichen des Tieres angenommen und sein Standbild angebetet hatten.
Bei lebendigem Leib wurden beide in den See von brennendem Schwefel
geworfen. ^{[[#fn20][20]][[#fn21][21]]}

<<v21>>
21 Die Übrigen wurden getötet mit dem Schwert, das aus dem Mund des
Reiters kam; und /alle Vögel fraßen sich satt an/ ihrem /Fleisch./
^{[[#fn22][22]]}\\
\\

^{[[#fnm1][1]]} 1-9: Die Triumphlieder der Himmelsbewohner (vgl. 18,20)
preisen das gerechte Gericht über die Feinde Gottes («die große Hure»)
und das künftige Heil des Gottesvolkes. Das Heil wird unter dem Bild
einer Hochzeit dargestellt (vgl. Mt 22,1-3; Mk 2,19; Joh 3,29; 2 Kor
11,2).

^{[[#fnm2][2]]} ℘ Ps 19,10; 2 Kön 9,7

^{[[#fnm3][3]]} ℘ Jes 34,10

^{[[#fnm4][4]]} ℘ Jes 6,1

^{[[#fnm5][5]]} ℘ Ps 134,1; 115,13

^{[[#fnm6][6]]} ℘ Ez 1,24; 43,2; Ps 93,1; Dan 7,14

^{[[#fnm7][7]]} ℘ Ps 118,24

^{[[#fnm8][8]]} ℘ Ps 45,14f

^{[[#fnm9][9]]} ℘ 1,3

^{[[#fnm10][10]]} ℘ 22,9

^{[[#fnm11][11]]} ℘ Ez 1,1; Ps 96,13

^{[[#fnm12][12]]} 11-21: Die Vision vom Endkampf zwischen dem in die
Macht Gottes eingesetzten Christus, dem Reiter auf dem weißen Pferd, und
den gottfeindlichen Mächten schildert das endgültige Gericht über das
Tier und den Lügenpropheten.

^{[[#fnm13][13]]} ℘ Dan 10,6

^{[[#fnm14][14]]} ℘ Jes 63,1f

^{[[#fnm15][15]]} Das Blut, mit dem das Gewand Christi getränkt ist, ist
das im Endkampf vergossene Blut der Feinde Gottes. Der Name «Das Wort
Gottes» verweist auf die durchschlagende Kraft des ausgesprochenen
Wortes, des Willens Gottes (vgl. V. 15; 2 Thess 2,8); dieser Name steht
in Beziehung zur Bezeichnung Christi als «das Wort» in Joh 1,1-14.

^{[[#fnm16][16]]} ℘ Jes 11,4; 49,2; Ps 2,9 G; Jes 63,3

^{[[#fnm17][17]]} ℘ Dan 2,47; Dtn 10,17

^{[[#fnm18][18]]} ℘ Ez 39,4.17-20

^{[[#fnm19][19]]} ℘ Ps 2,2

^{[[#fnm20][20]]} ℘ Dan 7,11; Jes 30,33

^{[[#fnm21][21]]} Der brennende Schwefelsee ist Bild für den Ort ewiger
Peinigung. Dieser Ort wurde im Judentum «Gehenna» (Hölle) genannt (vgl.
Dtn 32,22; Mt 11,23; 23,33; Lk 12,5; 2 Petr 2,4).

^{[[#fnm22][22]]} ℘ Ez 39,17.20
