:PROPERTIES:
:ID:       dfb1a20e-2692-4d73-9ae3-d41ae6192c89
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Offenbarung des Johannes* --
[[file:Offb_1.html][1]] ... [[file:Offb_19.html][19]]
[[file:Offb_20.html][20]] *21* [[file:Offb_22.html][22]]

--------------

* Offb 21
  :PROPERTIES:
  :CUSTOM_ID: offb-21
  :END:

<<verses>>

<<v1>>
** Die neue Welt Gottes: 21,1 - 22,5
   :PROPERTIES:
   :CUSTOM_ID: die-neue-welt-gottes-211---225
   :END:
**** Gottes Wohnen unter den Menschen: 21,1-8
     :PROPERTIES:
     :CUSTOM_ID: gottes-wohnen-unter-den-menschen-211-8
     :END:
1 Dann sah ich /einen neuen Himmel und eine neue Erde;/ denn der erste
Himmel und die erste Erde sind vergangen, auch das Meer ist nicht mehr.
^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Ich sah /die heilige Stadt,/ das neue /Jerusalem,/ von Gott her aus
dem Himmel herabkommen; sie war bereit /wie eine Braut, die sich/ für
ihren Mann /geschmückt hat./ ^{[[#fn3][3]]}

<<v3>>
3 Da hörte ich eine laute Stimme vom Thron her rufen: /Seht, die
Wohnung/ Gottes unter den Menschen! /Er wird in ihrer Mitte wohnen, und
sie werden sein Volk sein; und er, Gott, wird bei ihnen sein./
^{[[#fn4][4]][[#fn5][5]]}

<<v4>>
4 /Er wird alle Tränen von ihren Augen abwischen:/ Der Tod wird nicht
mehr sein, keine /Trauer,/ keine /Klage,/ keine Mühsal. Denn was früher
war, ist vergangen. ^{[[#fn6][6]]}

<<v5>>
5 /Er, der auf dem Thron saß,/ sprach: /Seht, ich mache/ alles /neu./
Und er sagte: Schreib es auf, denn diese Worte sind zuverlässig und
wahr. ^{[[#fn7][7]][[#fn8][8]]}

<<v6>>
6 Er sagte zu mir: Sie sind in Erfüllung gegangen. Ich bin das Alpha und
das Omega, der Anfang und das Ende. /Wer durstig ist, den werde ich
umsonst aus der Quelle/ trinken lassen, aus der /das Wasser des Lebens
strömt./ ^{[[#fn9][9]]}

<<v7>>
7 Wer siegt, wird dies als Anteil erhalten: /Ich werde sein Gott sein
und er wird mein Sohn sein./ ^{[[#fn10][10]]}

<<v8>>
8 Aber die Feiglinge und Treulosen, die Befleckten, die Mörder und
Unzüchtigen, die Zauberer, Götzendiener und alle Lügner - ihr Los wird
der See /von brennendem Schwefel/ sein. Dies ist der zweite Tod.
^{[[#fn11][11]]}\\
\\

<<v9>>
**** Das neue Jerusalem: 21,9 - 22,5
     :PROPERTIES:
     :CUSTOM_ID: das-neue-jerusalem-219---225
     :END:
9 Und es kam einer von den sieben Engeln, die die sieben Schalen mit den
/sieben/ letzten /Plagen/ getragen hatten. Er sagte zu mir: Komm, ich
will dir die Braut zeigen, die Frau des Lammes.
^{[[#fn12][12]][[#fn13][13]]}

<<v10>>
10 /Da entrückte er mich/ in der Verzückung /auf einen/ großen, /hohen
Berg/ und zeigte mir /die heiligeStadt Jerusalem,/ wie sie von Gott her
aus dem Himmel herabkam, ^{[[#fn14][14]]}

<<v11>>
11 erfüllt von der Herrlichkeit Gottes. Sie glänzte wie ein kostbarer
Edelstein, wie ein kristallklarer Jaspis. ^{[[#fn15][15]]}

<<v12>>
12 /Die Stadt/ hat eine große und hohe Mauer mit zwölf /Toren/ und zwölf
Engeln darauf. Auf die Tore sind Namen geschrieben: /die Namen der zwölf
Stämme der Söhne Israels./ ^{[[#fn16][16]]}

<<v13>>
13 /Im Osten hat die Stadt drei Tore und im Norden drei Tore und im
Süden drei Tore und im Westen drei Tore./ ^{[[#fn17][17]]}

<<v14>>
14 Die Mauer der Stadt hat zwölf Grundsteine; auf ihnen stehen die zwölf
Namen der zwölf Apostel des Lammes.

<<v15>>
15 Und der Engel, der zu mir sprach, hatte einen goldenen /Messstab,/
mit dem die Stadt, ihre Tore und ihre Mauer gemessen wurden.
^{[[#fn18][18]]}

<<v16>>
16 Die Stadt war /viereckig/ angelegt und ebenso lang wie breit. Er maß
die Stadt mit dem Messstab; ihre Länge, Breite und Höhe sind gleich:
zwölftausend Stadien. ^{[[#fn19][19]]}

<<v17>>
17 /Und er maß ihre Mauer;/ sie ist hundertvierundvierzig Ellen hoch
nach Menschenmaß, das der Engel benutzt hatte. ^{[[#fn20][20]]}

<<v18>>
18 Ihre Mauer ist aus Jaspis gebaut und die Stadt ist aus reinem Gold,
wie aus reinem Glas. ^{[[#fn21][21]]}

<<v19>>
19 /Die Grundsteine/ der Stadtmauer sind mit /edlen Steinen/ aller Art
geschmückt; der erste Grundstein ist ein Jaspis, der zweite ein Saphir,
der dritte ein Chalzedon, der vierte ein Smaragd, ^{[[#fn22][22]]}

<<v20>>
20 der fünfte ein Sardonyx, der sechste ein Sardion, der siebte ein
Chrysolith, der achte ein Beryll, der neunte ein Topas, der zehnte ein
Chrysopras, der elfte ein Hyazinth, der zwölfte ein Amethyst.

<<v21>>
21 Die zwölf Tore sind zwölf Perlen; jedes der Tore besteht aus einer
einzigen Perle. Die Straße der Stadt ist aus reinem Gold, wie aus klarem
Glas.

<<v22>>
22 Einen Tempel sah ich nicht in der Stadt. Denn der Herr, ihr Gott, der
Herrscher über die ganze Schöpfung, ist ihr Tempel, er und das Lamm.

<<v23>>
23 Die Stadt braucht /weder Sonne noch Mond,/ die ihr /leuchten./ Denn
/die Herrlichkeit Gottes erleuchtet/ sie und ihre Leuchte ist das Lamm.
^{[[#fn23][23]]}

<<v24>>
24 /Die Völker werden/ in diesem /Licht einhergehen und die Könige/ der
Erde werden /ihre Pracht/ in die Stadt /bringen./ ^{[[#fn24][24]]}

<<v25>>
25 Ihre /Tore werden den ganzen Tag nicht geschlossen/ - Nacht wird es
dort nicht mehr geben. ^{[[#fn25][25]]}

<<v26>>
26 /Und man wird die Pracht/ und die Kostbarkeiten /der Völker/ in die
Stadt /bringen./

<<v27>>
27 /Aber nichts Unreines wird hineinkommen,/ keiner, der Gräuel verübt
und lügt. Nur die, /die im Lebensbuch/ des Lammes /eingetragen sind,/
werden eingelassen. ^{[[#fn26][26]]}

^{[[#fnm1][1]]} ℘ Jes 65,17; 66,22

^{[[#fnm2][2]]} Das Verschwinden der Erde und des Himmels (vgl. 20,11)
und das Kommen «eines neuen Himmels und einer neuen Erde» (Jes 65,17;
66,12) sind Hinweis auf die völlig andersartigen Bedingungen des Daseins
der Erlösten.

^{[[#fnm3][3]]} ℘ Jes 52,1; Gal 4,26; Hebr 12,22; Jes 61,10

^{[[#fnm4][4]]} ℘ Lev 26,11f; Ez 37,27; Sach 2,14; Jes 8,8

^{[[#fnm5][5]]} Nach anderen Textzeugen: sie werden seine Völker sein.

^{[[#fnm6][6]]} ℘ Jes 25,8; 1 Kor 15,26; Jes 35,10

^{[[#fnm7][7]]} ℘ Jes 6,1; 43,19 G; 2 Kor 5,17

^{[[#fnm8][8]]} 5-8: Wie in 1,8 spricht Gott hier selbst; seine Worte
bestätigen die Aussage des Sehers.

^{[[#fnm9][9]]} ℘ Jes 55,1; Sach 14,8

^{[[#fnm10][10]]} ℘ Röm 8,17; 2 Sam 7,14

^{[[#fnm11][11]]} ℘ 22,15; Mt 15,19; Ez 38,22

^{[[#fnm12][12]]} ℘ Lev 26,21 G

^{[[#fnm13][13]]} 9f: Auch hier werden «die Braut, die Frau des Lammes»
(Gegenbild der großen Hure) und «die heilige Stadt Jerusalem» (Gegenbild
Babylons) miteinander gleichgesetzt.

^{[[#fnm14][14]]} ℘ Ez 40,2; Jes 52,1

^{[[#fnm15][15]]} ℘ Jes 60,1f

^{[[#fnm16][16]]} ℘ Ez 48,31; Ex 28,21

^{[[#fnm17][17]]} ℘ Ez 48,31-35

^{[[#fnm18][18]]} ℘ Ez 40,3.5

^{[[#fnm19][19]]} ℘ Ez 43,16

^{[[#fnm20][20]]} ℘ Ez 40,5

^{[[#fnm21][21]]} ℘ Jes 54,11f

^{[[#fnm22][22]]} ℘ (19f) Ez 28,13 G

^{[[#fnm23][23]]} ℘ Jes 60,1.19

^{[[#fnm24][24]]} ℘ Jes 60,3.11; Ps 72,10

^{[[#fnm25][25]]} ℘ Sach 14,7

^{[[#fnm26][26]]} ℘ Jes 52,1; 4,3; Dan 12,1; Ps 69,29; Offb 3,5
