:PROPERTIES:
:ID:       e4a86019-fa53-4aab-90c4-ac17ea24fe9a
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Offenbarung des Johannes* --
[[file:Offb_1.html][1]] ... [[file:Offb_20.html][20]]
[[file:Offb_21.html][21]] *22*

--------------

* Offb 22
  :PROPERTIES:
  :CUSTOM_ID: offb-22
  :END:

<<verses>>

<<v1>>
1 Und er zeigte mir einen /Strom, das Wasser des Lebens,/ klar wie
Kristall; /er geht/ vom Thron Gottes und des Lammes aus. ^{[[#fn1][1]]}

<<v2>>
2 Zwischen der Straße der Stadt und dem Strom, hüben und drüben, stehen
Bäume des Lebens. Zwölfmal tragen sie Früchte, jeden Monat einmal; und
die Blätter der Bäume dienen zur Heilung der Völker. ^{[[#fn2][2]]}

<<v3>>
3 Es wird nichts mehr geben, was der Fluch Gottes trifft. Der Thron
Gottes und des Lammes wird in der Stadt stehen und seine Knechte werden
ihm dienen. ^{[[#fn3][3]]}

<<v4>>
4 Sie werden sein /Angesicht schauen/ und sein Name ist auf ihre Stirn
geschrieben. ^{[[#fn4][4]]}

<<v5>>
5 Es wird keine Nacht mehr geben und sie brauchen weder das Licht einer
Lampe noch das Licht der Sonne. Denn der Herr, ihr Gott, wird über ihnen
leuchten und sie werden herrschen /in alle Ewigkeit./ ^{[[#fn5][5]]}\\
\\

<<v6>>
** Zeugnis und Abschließende Mahnung des Sehers: 22,6-21
   :PROPERTIES:
   :CUSTOM_ID: zeugnis-und-abschließende-mahnung-des-sehers-226-21
   :END:
6 Und der Engel sagte zu mir: Diese Worte sind zuverlässig und wahr.
Gott, der Herr über den Geist der Propheten, hat seinen Engel gesandt,
um seinen Knechten zu zeigen, /was/ bald /geschehen muss./
^{[[#fn6][6]]}

<<v7>>
7 /Siehe, ich komme/ bald. Selig, wer an den prophetischen Worten dieses
Buches festhält. ^{[[#fn7][7]]}

<<v8>>
8 Ich, Johannes, habe dies gehört und gesehen. Und als ich es hörte und
sah, fiel ich dem Engel, der mir dies gezeigt hatte, zu Füßen, um ihn
anzubeten.

<<v9>>
9 Da sagte er zu mir: Tu das nicht! Ich bin nur ein Knecht wie du und
deine Brüder, die Propheten, und wie alle, die sich an die Worte dieses
Buches halten. Gott bete an! ^{[[#fn8][8]]}

<<v10>>
10 Und er sagte zu mir: /Versiegle/ dieses /Buch/ mit seinen
prophetischen /Worten/ nicht! Denn die Zeit ist nahe. ^{[[#fn9][9]]}

<<v11>>
11 /Wer Unrecht tut, tue weiter Unrecht,/ der Unreine bleibe unrein, der
Gerechte handle weiter gerecht und der Heilige strebe weiter nach
Heiligkeit. ^{[[#fn10][10]]}

<<v12>>
12 /Siehe, ich komme/ bald und /mit mir/ bringe ich den /Lohn und ich
werde jedem geben, was seinem Werk entspricht./ ^{[[#fn11][11]]}

<<v13>>
13 /Ich bin/ das Alpha und das Omega, /der Erste und der Letzte,/ der
Anfang und das Ende. ^{[[#fn12][12]]}

<<v14>>
14 Selig, wer sein Gewand wäscht: Er hat Anteil am /Baum des Lebens,/
und er wird durch die Tore in die Stadt eintreten können.
^{[[#fn13][13]]}

<<v15>>
15 Draußen bleiben die «Hunde» und die Zauberer, die Unzüchtigen und die
Mörder, die Götzendiener und jeder, der die Lüge liebt und tut.
^{[[#fn14][14]]}

<<v16>>
16 Ich, Jesus, habe meinen Engel gesandt als Zeugen für das, was die
Gemeinden betrifft. Ich bin die Wurzel und der Stamm Davids, der
strahlende Morgenstern. ^{[[#fn15][15]]}

<<v17>>
17 Der Geist und die Braut aber sagen: Komm! Wer hört, der rufe: Komm!
/Wer durstig ist, der komme./ Wer will, empfange /umsonst das Wasser des
Lebens./ ^{[[#fn16][16]]}

<<v18>>
18 Ich bezeuge jedem, der die prophetischen Worte dieses Buches hört:
Wer /etwas hinzufügt,/ dem wird Gott die Plagen zufügen, /von denen in
diesem Buch geschrieben steht./ ^{[[#fn17][17]]}

<<v19>>
19 /Und/ wer /etwas wegnimmt von/ den prophetischen Worten dieses
Buches, dem wird Gott seinen Anteil /am Baum des Lebens/ und an der
heiligen Stadt wegnehmen, von denen in diesem Buch geschrieben steht.
^{[[#fn18][18]]}

<<v20>>
20 Er, der dies bezeugt, spricht: Ja, ich komme bald. - Amen. Komm, Herr
Jesus! ^{[[#fn19][19]]}

<<v21>>
21 Die Gnade des Herrn Jesus sei mit allen! ^{[[#fn20][20]]}

^{[[#fnm1][1]]} ℘ Gen 2,10; Sach 14,8

^{[[#fnm2][2]]} ℘ Ez 47,12; Gen 2,9

^{[[#fnm3][3]]} ℘ Sach 14,11

^{[[#fnm4][4]]} ℘ Ps 17,15

^{[[#fnm5][5]]} ℘ Jes 60,19; Dan 7,18.27

^{[[#fnm6][6]]} ℘ Dan 2,28

^{[[#fnm7][7]]} ℘ Sach 2,14; Offb 1,3; 22,12.20

^{[[#fnm8][8]]} ℘ 19,10

^{[[#fnm9][9]]} ℘ Dan 12,4.9

^{[[#fnm10][10]]} ℘ Dan 12,10

^{[[#fnm11][11]]} ℘ Sach 2,14; Jes 40,10 G; Ps 28,4

^{[[#fnm12][12]]} ℘ Jes 44,6; Offb 1,17

^{[[#fnm13][13]]} ℘ 1,3; Gen 2,9; 3,22

^{[[#fnm14][14]]} ℘ 21,8; Mt 15,19

^{[[#fnm15][15]]} ℘ Jes 11,1.10; Num 24,17

^{[[#fnm16][16]]} ℘ Jes 55,1; Sach 14,8

^{[[#fnm17][17]]} ℘ Dtn 4,2; 13,1; 29,20

^{[[#fnm18][18]]} ℘ Dtn 4,2; Gen 2,9; 3,22

^{[[#fnm19][19]]} ℘ 3,11; 22,7.12; 1 Kor 16,22

^{[[#fnm20][20]]} ℘ Hebr 13,25
