:PROPERTIES:
:ID:       dc4401cd-9229-402f-aa46-e324b10c6e2d
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Offenbarung des Johannes* --
[[file:Offb_1.html][1]] ... [[file:Offb_11.html][11]]
[[file:Offb_12.html][12]] *13* [[file:Offb_14.html][14]]
[[file:Offb_15.html][15]] ... [[file:Offb_22.html][22]]

--------------

* Offb 13
  :PROPERTIES:
  :CUSTOM_ID: offb-13
  :END:

<<verses>>

<<v1>>
**** Die beiden Tiere: 13,1-18
     :PROPERTIES:
     :CUSTOM_ID: die-beiden-tiere-131-18
     :END:
1 Und ich sah: /Ein Tier stieg aus dem Meer, mit zehn Hörnern/ und
sieben Köpfen. Auf seinen Hörnern trug es zehn Diademe und auf seinen
Köpfen Namen, die eine Gotteslästerung waren. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 /Das Tier,/ das ich sah, /glich einem Panther;/ seine Füße waren wie
die Tatzen /eines Bären/ und sein Maul wie das Maul /eines Löwen./ Und
der Drache hatte ihm seine Gewalt übergeben, seinen Thron und seine
große Macht. ^{[[#fn3][3]]}

<<v3>>
3 Einer seiner Köpfe sah aus wie tödlich verwundet; aber die tödliche
Wunde wurde geheilt. Und die ganze Erde sah dem Tier staunend nach.
^{[[#fn4][4]]}

<<v4>>
4 Die Menschen warfen sich vor dem Drachen nieder, weil er seine Macht
dem Tier gegeben hatte; und sie beteten das Tier an und sagten: Wer ist
dem Tier gleich und wer kann den Kampf mit ihm aufnehmen?

<<v5>>
5 Und es wurde ermächtigt, mit seinem /Maul anmaßende Worte/ und
Lästerungen /auszusprechen;/ es wurde ihm Macht gegeben, dies
zweiundvierzig Monate zu tun. ^{[[#fn5][5]]}

<<v6>>
6 Das Tier öffnete sein Maul, um Gott und seinen Namen zu lästern, seine
Wohnung und alle, die im Himmel wohnen.

<<v7>>
7 Und es wurde ihm erlaubt, /mit den Heiligen zu kämpfen und sie zu
besiegen./ Es wurde ihm auch Macht gegeben über alle Stämme, Völker,
Sprachen und Nationen. ^{[[#fn6][6]][[#fn7][7]]}

<<v8>>
8 Alle Bewohner der Erde fallen nieder vor ihm: alle, deren Name nicht
seit der Erschaffung der Welt /eingetragen ist ins Lebensbuch/ des
Lammes, das geschlachtet wurde. ^{[[#fn8][8]]}

<<v9>>
9 Wenn einer Ohren hat, so höre er.

<<v10>>
10 /Wer zur Gefangenschaft bestimmt ist,/ geht /in die Gefangenschaft.
Wer mit dem Schwert/ getötet werden soll, wird /mit dem Schwert/
getötet. Hier muss sich die Standhaftigkeit und die Glaubenstreue der
Heiligen bewähren. ^{[[#fn9][9]]}

<<v11>>
11 Und ich sah: Ein anderes Tier stieg aus der Erde herauf. Es hatte
zwei Hörner wie ein Lamm, aber es redete wie ein Drache.
^{[[#fn10][10]]}

<<v12>>
12 Die ganze Macht des ersten Tieres übte es vor dessen Augen aus. Es
brachte die Erde und ihre Bewohner dazu, das erste Tier anzubeten,
dessen tödliche Wunde geheilt war.

<<v13>>
13 Es tat große Zeichen; sogar Feuer ließ es vor den Augen der Menschen
vom Himmel auf die Erde fallen.

<<v14>>
14 Es verwirrte die Bewohner der Erde durch die Wunderzeichen, die es im
Auftrag des Tieres tat; es befahl den Bewohnern der Erde, ein Standbild
zu errichten zu Ehren des Tieres, das mit dem Schwert erschlagen worden
war und doch wieder zum Leben kam.

<<v15>>
15 Es wurde ihm Macht gegeben, dem Standbild des Tieres Lebensgeist zu
verleihen, sodass es auch sprechen konnte und bewirkte, dass alle
getötet wurden, /die das Standbild/ des Tieres /nicht anbeteten./
^{[[#fn11][11]]}

<<v16>>
16 Die Kleinen und die Großen, die Reichen und die Armen, die Freien und
die Sklaven, alle zwang es, auf ihrer rechten Hand oder ihrer Stirn ein
Kennzeichen anzubringen.

<<v17>>
17 Kaufen oder verkaufen konnte nur, wer das Kennzeichen trug: den Namen
des Tieres oder die Zahl seines Namens.

<<v18>>
18 Hier braucht man Kenntnis. Wer Verstand hat, berechne den Zahlenwert
des Tieres. Denn es ist die Zahl eines Menschennamens; seine Zahl ist
sechshundertsechsundsechzig. ^{[[#fn12][12]]}\\
\\

^{[[#fnm1][1]]} ℘ Dan 7,3.7

^{[[#fnm2][2]]} 1f: Zur Bekämpfung der Christen bedient sich der Drache
des aus dem Meer aufsteigenden Tieres. Die Hörner, Diademe usw. sind
Symbole seiner Macht (vgl. Dan 7). Die Namen auf seinen sieben Köpfen
sind Titel der römischen Kaiser (Hinweis auf den Kaiserkult).

^{[[#fnm3][3]]} ℘ Dan 7,4-6

^{[[#fnm4][4]]} Die sieben Köpfe des Tieres werden in 17,9 ausdrücklich
auf sieben «Könige», das heißt auf römische Kaiser, gedeutet. Mit dem
erschlagenen Tier, das «wieder zum Leben kam» (V. 14), ist Kaiser
Domitian (81-96 n. Chr.), der «wiedererstandene Nero» (54-68 n. Chr.),
gemeint. Zu dieser Deutung könnte auch 666 als Zahl des Namens des
Tieres passen (vgl. 13,18).

^{[[#fnm5][5]]} ℘ Dan 7,8.25

^{[[#fnm6][6]]} ℘ Dan 7,21

^{[[#fnm7][7]]} erlaubt, wörtlich: gegeben.

^{[[#fnm8][8]]} ℘ Dan 12,1; Ps 69,29; Jes 53,7; Offb 3,5

^{[[#fnm9][9]]} ℘ Jer 15,2; 43,11

^{[[#fnm10][10]]} 11-17: Schon das Alte Testament kennt zwei
Tierungeheuer, den Leviatan im Meer und den Behemot auf dem festen Land
(vgl. Jes 27,1; Ps 74,14; 104,26; Ijob 3,8; 40,15-32); sie stellen
sinnbildlich die ungeordnete, gottwidrige Schöpfung dar (das Chaos). In
Offb ist das aus dem Land aufsteigende Tier der Beauftragte des Tieres
aus dem Meer. Es wird als «falscher Prophet» gekennzeichnet (16,13;
19,20; 20,10; vgl. Mk 13,22; 2 Thess 2,9f).

^{[[#fnm11][11]]} ℘ Dan 3,5f

^{[[#fnm12][12]]} Im Griechischen und Hebräischen dienen die Buchstaben
auch als Ziffern. Man kann also den Zahlenwert der Buchstaben eines
Namens zusammenzählen. Auf wen der Zahlenwert 666 sich bezieht, ist
nicht sicher; möglicherweise auf Kaiser Nero (vgl. die Anmerkung zu
13,3).
