:PROPERTIES:
:ID:       7d9eefff-25a7-4db6-8fe4-621d49e854ca
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Offenbarung des Johannes* --
[[file:Offb_1.html][1]] ... [[file:Offb_16.html][16]]
[[file:Offb_17.html][17]] *18* [[file:Offb_19.html][19]]
[[file:Offb_20.html][20]] ... [[file:Offb_22.html][22]]

--------------

* Offb 18
  :PROPERTIES:
  :CUSTOM_ID: offb-18
  :END:

<<verses>>

<<v1>>
**** Die Ankündigung von Babylons Sturz: 18,1-8
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-von-babylons-sturz-181-8
     :END:
1 Danach sah ich einen anderen Engel aus dem Himmel herabsteigen; er
hatte große Macht /und die Erde leuchtete auf von seiner Herrlichkeit./
^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Und er rief mit gewaltiger Stimme: /Gefallen, gefallen ist Babylon,
die Große!/ Zur Wohnung von Dämonen ist sie geworden, zur Behausung
aller unreinen Geister und zum Schlupfwinkel aller unreinen und
abscheulichen Vögel. ^{[[#fn3][3]]}

<<v3>>
3 Denn vom Zornwein ihrer Unzucht /haben/ alle /Völker getrunken und die
Könige der Erde haben mit ihr Unzucht getrieben./ Durch die Fülle ihres
Wohlstands sind die Kaufleute der Erde reich geworden. ^{[[#fn4][4]]}

<<v4>>
4 Dann hörte ich eine andere Stimme vom Himmel her rufen: Verlass die
Stadt, mein Volk, damit du nicht mitschuldig wirst an ihren Sünden und
von ihren Plagen mitgetroffen wirst. ^{[[#fn5][5]]}

<<v5>>
5 /Denn ihre/ Sünden /haben sich bis zum Himmel aufgetürmt/ und Gott hat
ihre Schandtaten nicht vergessen. ^{[[#fn6][6]]}

<<v6>>
6 Zahlt ihr mit gleicher Münze heim, gebt ihr doppelt zurück, was sie
getan hat. Mischt ihr den Becher, den sie gemischt hat, doppelt so
stark. ^{[[#fn7][7]]}

<<v7>>
7 Im gleichen Maß, wie sie in Prunk und Luxus lebte, lasst sie Qual und
Trauer erfahren. /Sie dachte bei sich:/ Ich throne als Königin, /ich bin
keine Witwe/ und werde keine Trauer kennen. ^{[[#fn8][8]]}

<<v8>>
8 Deshalb /werden an einem einzigen Tag/ die Plagen über sie /kommen,/
die für sie bestimmt sind: Tod, Trauer und Hunger. Und sie wird im Feuer
verbrennen; denn /stark ist der Herr,/ der Gott, der sie gerichtet hat.
^{[[#fn9][9]][[#fn10][10]]}\\
\\

<<v9>>
**** Die Klage über den Untergang Babylons: 18,9-24
     :PROPERTIES:
     :CUSTOM_ID: die-klage-über-den-untergang-babylons-189-24
     :END:
9 /Die Könige der Erde, die mit ihr gehurt/ und in Luxus gelebt /haben,
werden über/ sie /weinen und klagen,/ wenn sie den Rauch der brennenden
Stadt sehen. ^{[[#fn11][11]][[#fn12][12]]}

<<v10>>
10 Sie bleiben in der Ferne stehen aus Angst vor ihrer Qual und sagen:
Wehe! Wehe, du /große/ Stadt /Babylon, du mächtige Stadt!/ In einer
einzigen Stunde ist das Gericht über dich gekommen. ^{[[#fn13][13]]}

<<v11>>
11 Auch die /Kaufleute/ der Erde /weinen und klagen/ um sie, weil
niemand mehr ihre Ware kauft: ^{[[#fn14][14]]}

<<v12>>
12 Gold und Silber, Edelsteine und Perlen, feines Leinen, Purpur, Seide
und Scharlach, wohlriechende Hölzer aller Art und alle möglichen Geräte
aus Elfenbein, kostbarem Edelholz, Bronze, Eisen und Marmor;

<<v13>>
13 auch Zimt und Balsam, Räucherwerk, Salböl und Weihrauch, Wein und Öl,
feinstes Mehl und Weizen, Rinder und Schafe, Pferde und Wagen und sogar
Menschen mit Leib und Seele. ^{[[#fn15][15]]}

<<v14>>
14 Auch die Früchte, nach denen dein Herz begehrte, sind dir genommen.
Und alles, was prächtig und glänzend war, hast du verloren; nie mehr
wird man es finden.

<<v15>>
15 Die /Kaufleute,/ die durch den Handel mit dieser Stadt reich geworden
sind, werden aus Angst vor ihrer Qual in der Ferne stehen und sie werden
/weinen und klagen:/ ^{[[#fn16][16]]}

<<v16>>
16 Wehe! Wehe, du große Stadt, bekleidet mit feinem Leinen, mit Purpur
und Scharlach, geschmückt mit Gold, Edelsteinen und Perlen.

<<v17>>
17 In einer einzigen Stunde ist dieser ganze Reichtum dahin. /Alle
Kapitäne/ und Schiffsreisenden, /die Matrosen und alle, die/ ihren
Unterhalt /auf See/ verdienen, machten schon in der Ferne Halt,
^{[[#fn17][17]]}

<<v18>>
18 als sie den Rauch der brennenden Stadt sahen, und sie riefen: /Wer/
konnte sich mit der großen Stadt /messen/?

<<v19>>
19 /Und sie streuten sich Staub auf den Kopf, sie schrien, weinten und
klagten:/ Wehe! Wehe, du große Stadt, die mit ihren Schätzen alle reich
gemacht hat, die Schiffe auf dem Meer haben. In einer einzigen Stunde
ist sie verwüstet worden. ^{[[#fn18][18]]}

<<v20>>
20 /Freu dich/ über ihren Untergang, /du Himmel/ - und auch ihr,
Heilige, Apostel und Propheten, freut euch! Denn /Gott hat/ euch an ihr
/gerächt./ ^{[[#fn19][19]]}

<<v21>>
21 Dann hob ein gewaltiger Engel einen /Stein/ auf, so groß wie ein
Mühlstein; /er warf ihn/ ins Meer und rief: So wird /Babylon, die große
Stadt,/ mit /Wucht hinabgeworfen werden und man wird sie nicht mehr
finden./ ^{[[#fn20][20]][[#fn21][21]]}

<<v22>>
22 Die Musik von Harfenspielern und Sängern, von Flötenspielern und
Trompetern hört man nicht mehr in dir. Einen kundigen Handwerker gibt es
nicht mehr in dir. /Das Geräusch des Mühlsteins/ hört man nicht mehr in
dir. ^{[[#fn22][22]]}

<<v23>>
23 /Das Licht der Lampe/ scheint nicht mehr in dir. /Die Stimme von
Braut und Bräutigam/ hört man nicht mehr in dir. Deine /Kaufleute waren
die Großen der Erde, deine Zauberei/ verführte alle Völker.
^{[[#fn23][23]]}

<<v24>>
24 Aber in ihr war das Blut von Propheten und Heiligen und von allen,
die auf der Erde hingeschlachtet worden sind. ^{[[#fn24][24]]}\\
\\

^{[[#fnm1][1]]} ℘ Ez 43,2

^{[[#fnm2][2]]} 1-3: Das bereits 14,8 angekündigte Gericht über Babylon
wird nun Wirklichkeit. Zur Schilderung des Gerichts über gottfeindliche
Städte im Alten Testament vgl. Jes 47,10 G (Babylon), Jes 23,15-17
(Tyrus) und Nah 3,4 (Ninive).

^{[[#fnm3][3]]} ℘ Jes 21,9; Dan 4,27; Jes 13,21; 34,11; Jer 50,39

^{[[#fnm4][4]]} ℘ Jer 51,7; Jes 23,17; Ez 27,33

^{[[#fnm5][5]]} ℘ Jes 48,20; 2 Kor 6,17

^{[[#fnm6][6]]} ℘ Jer 51,9

^{[[#fnm7][7]]} ℘ Jer 50,15.29; Ps 137,8

^{[[#fnm8][8]]} ℘ Jes 47,7f

^{[[#fnm9][9]]} ℘ Jes 47,9; Jer 50,34

^{[[#fnm10][10]]} «An einem einzigen Tag» ist wie «in einer einzigen
Stunde» (VV. 10.17.19) symbolischer Ausdruck für das plötzliche
Eintreffen des Gerichts.

^{[[#fnm11][11]]} ℘ Ez 27,31-33; Jes 23,17

^{[[#fnm12][12]]} 9-19: Die Klagen «der Könige der Erde», der Kaufleute
und der Seefahrer über die verödete Stadt haben ihr Vorbild in Ez
26,15 - 27,36.

^{[[#fnm13][13]]} ℘ Dan 4,27; Ez 26,17

^{[[#fnm14][14]]} ℘ Ez 27,31.36

^{[[#fnm15][15]]} ℘ Ez 27,13

^{[[#fnm16][16]]} ℘ Ez 27,31.36

^{[[#fnm17][17]]} ℘ Ez 27,27-34

^{[[#fnm18][18]]} ℘ Ez 26,19

^{[[#fnm19][19]]} ℘ Jes 44,23; Dtn 32,43 G

^{[[#fnm20][20]]} ℘ Jer 51,63f; Dan 4,27; Ez 26,21

^{[[#fnm21][21]]} 21-23: Das symbolische Geschehen verweist auf die
Endgültigkeit des vollzogenen Gerichts.

^{[[#fnm22][22]]} ℘ Jes 24,8; Ez 26,13; Jer 25,10

^{[[#fnm23][23]]} ℘ Jes 23,8; 47,9; Nah 3,4

^{[[#fnm24][24]]} ℘ Jer 51,49
