:PROPERTIES:
:ID:       f7585806-bb27-49c8-a6f6-3328e61ddc6b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Offenbarung des Johannes* --
[[file:Offb_1.html][1]] ... [[file:Offb_10.html][10]]
[[file:Offb_11.html][11]] *12* [[file:Offb_13.html][13]]
[[file:Offb_14.html][14]] ... [[file:Offb_22.html][22]]

--------------

* Offb 12
  :PROPERTIES:
  :CUSTOM_ID: offb-12
  :END:

<<verses>>

<<v1>>
** Der Kampf des Satans gegen das Volk Gottes: 12,1 - 14,5
   :PROPERTIES:
   :CUSTOM_ID: der-kampf-des-satans-gegen-das-volk-gottes-121---145
   :END:
**** Die Frau und der Drache: 12,1-6
     :PROPERTIES:
     :CUSTOM_ID: die-frau-und-der-drache-121-6
     :END:
1 Dann erschien ein großes Zeichen am Himmel: eine Frau, mit der Sonne
bekleidet; der Mond war unter ihren Füßen und ein Kranz von zwölf
Sternen auf ihrem Haupt. ^{[[#fn1][1]]}

<<v2>>
2 Sie war schwanger und schrie vor Schmerz in ihren Geburtswehen.
^{[[#fn2][2]]}

<<v3>>
3 Ein anderes Zeichen erschien am Himmel: ein Drache, groß und feuerrot,
mit sieben Köpfen und /zehn Hörnern/ und mit sieben Diademen auf seinen
Köpfen. ^{[[#fn3][3]]}

<<v4>>
4 Sein Schwanz fegte ein Drittel /der Sterne vom Himmel/ und /warf/ sie
/auf die Erde herab./ Der Drache stand vor der Frau, die gebären sollte;
er wollte ihr Kind verschlingen, sobald es geboren war. ^{[[#fn4][4]]}

<<v5>>
5 Und /sie gebar/ ein Kind, /einen Sohn,/ der über alle Völker /mit
eisernem Zepter herrschen wird./ Und ihr Kind wurde zu Gott und zu
seinem Thron entrückt. ^{[[#fn5][5]]}

<<v6>>
6 Die Frau aber floh in die Wüste, wo Gott ihr einen Zufluchtsort
geschaffen hatte; dort wird man sie mit Nahrung versorgen,
zwölfhundertsechzig Tage lang.\\
\\

<<v7>>
**** Der Sturz des Drachen: 12,7-12
     :PROPERTIES:
     :CUSTOM_ID: der-sturz-des-drachen-127-12
     :END:
7 Da entbrannte im Himmel ein Kampf; /Michael/ und seine Engel erhoben
sich, um mit dem Drachen /zu kämpfen./ Der Drache und seine Engel
kämpften, ^{[[#fn6][6]]}

<<v8>>
8 aber sie konnten sich nicht halten und sie verloren ihren Platz im
Himmel. ^{[[#fn7][7]]}

<<v9>>
9 Er wurde gestürzt, der große Drache, die alte /Schlange,/ die /Teufel/
oder /Satan/ heißt und die ganze Welt verführt; der Drache wurde auf die
Erde gestürzt und mit ihm wurden seine Engel hinabgeworfen.
^{[[#fn8][8]]}\\
\\

<<v10>>
10 Da hörte ich eine laute Stimme im Himmel rufen: Jetzt ist er da, der
rettende Sieg, /\\
 die Macht und die Herrschaft unseres Gottes /\\
 und die Vollmacht seines Gesalbten; denn gestürzt wurde der Ankläger
unserer Brüder, /\\
 der sie bei Tag und bei Nacht /\\
 vor unserem Gott verklagte.\\
\\

<<v11>>
11 Sie haben ihn besiegt durch das Blut des Lammes /\\
 und durch ihr Wort und Zeugnis; sie hielten ihr Leben nicht fest, /\\
 bis hinein in den Tod.\\
\\

<<v12>>
12 Darum /jubelt, ihr Himmel/ /\\
 und alle, die darin wohnen. Weh aber euch, Land und Meer! /\\
 Denn der Teufel ist zu euch hinabgekommen; seine Wut ist groß, /\\
 weil er weiß, dass ihm nur noch eine kurze Frist bleibt.
^{[[#fn9][9]]}\\
\\

<<v13>>
**** Der Kampf des Drachen gegen die Frau: 12,13-18
     :PROPERTIES:
     :CUSTOM_ID: der-kampf-des-drachen-gegen-die-frau-1213-18
     :END:
13 Als der Drache erkannte, dass er auf die Erde gestürzt war, verfolgte
er die Frau, die den Sohn geboren hatte. ^{[[#fn10][10]]}

<<v14>>
14 Aber der Frau wurden die beiden Flügel des großen Adlers gegeben,
damit sie in die Wüste an ihren Ort fliegen konnte. Dort ist sie vor der
Schlange sicher und wird /eine Zeit und zwei Zeiten und eine halbe Zeit/
lang ernährt. ^{[[#fn11][11]]}

<<v15>>
15 Die Schlange spie einen Strom von Wasser aus ihrem Rachen hinter der
Frau her, damit sie von den Fluten fortgerissen werde.

<<v16>>
16 Aber die Erde kam der Frau zu Hilfe; sie öffnete sich und verschlang
den Strom, den der Drache aus seinem Rachen gespien hatte.

<<v17>>
17 Da geriet der Drache in Zorn über die Frau und er ging fort, um Krieg
zu führen mit ihren übrigen Nachkommen, die den Geboten Gottes gehorchen
und an dem Zeugnis für Jesus festhalten.

<<v18>>
18 Und der Drache trat an den Strand des Meeres.\\
\\

^{[[#fnm1][1]]} 1-6: Wie der Drache in 12,3, nach 12,9 der Teufel, so
ist auch die Frau eine symbolische Gestalt, Sinnbild des Gottesvolkes
des Alten und Neuen Bundes. Das Bild von der Geburt eines Sohnes und von
dessen Herrschaft über die Völker steht in der Tradition messianischer
Deutung prophetischer Texte (Jes 7,14; 66,7). - Die Schilderung des
Kampfes des Drachen gegen die Frau wird in V. 13 fortgesetzt.

^{[[#fnm2][2]]} ℘ Jes 66,7; Mi 4,10

^{[[#fnm3][3]]} ℘ Dan 7,7

^{[[#fnm4][4]]} ℘ Dan 8,10; Offb 9,1; Mi 5,2

^{[[#fnm5][5]]} ℘ Jes 66,7; Ps 2,9 G

^{[[#fnm6][6]]} ℘ Dan 10,13.20

^{[[#fnm7][7]]} ℘ Dan 2,35

^{[[#fnm8][8]]} ℘ Gen 3,1.14; Sach 3,1; Ijob 1,6

^{[[#fnm9][9]]} ℘ Jes 44,23

^{[[#fnm10][10]]} 13-17: Da der Teufel die Kirche als Ganze nicht
vernichten kann, versucht er, einzelne ihrer Mitglieder («Nachkommen»,
V. 17) zu Fall zu bringen.

^{[[#fnm11][11]]} ℘ Dan 7,25; 12,7
