:PROPERTIES:
:ID:       ea3ca64c-90f8-4437-ab4c-882cefed6193
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Offenbarung des Johannes* --
[[file:Offb_1.html][1]] ... [[file:Offb_12.html][12]]
[[file:Offb_13.html][13]] *14* [[file:Offb_15.html][15]]
[[file:Offb_16.html][16]] ... [[file:Offb_22.html][22]]

--------------

* Offb 14
  :PROPERTIES:
  :CUSTOM_ID: offb-14
  :END:

<<verses>>

<<v1>>
**** Das Lamm und sein Gefolge: 14,1-5
     :PROPERTIES:
     :CUSTOM_ID: das-lamm-und-sein-gefolge-141-5
     :END:
1 Und ich sah: Das Lamm stand auf dem Berg Zion und bei ihm waren
hundertvierundvierzigtausend; /auf ihrer Stirn/ trugen sie seinen Namen
und den Namen seines Vaters. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Dann hörte ich eine Stimme vom Himmel her, /die dem Rauschen von
Wassermassen/ und dem Rollen eines gewaltigen Donners /glich./ Die
Stimme, die ich hörte, war wie der Klang der Harfe, die ein
Harfenspieler schlägt. ^{[[#fn3][3]]}

<<v3>>
3 Und sie sangen ein neues Lied vor dem Thron und vor den vier Lebewesen
und vor den Ältesten. Aber niemand konnte das Lied singen lernen außer
den hundertvierundvierzigtausend, die freigekauft und von der Erde
weggenommen worden sind. ^{[[#fn4][4]]}

<<v4>>
4 Sie sind es, die sich nicht mit Weibern befleckt haben; denn sie sind
jungfräulich. Sie folgen dem Lamm, wohin es geht. Sie allein unter allen
Menschen sind freigekauft als Erstlingsgabe für Gott und das Lamm.

<<v5>>
5 Denn in ihrem Mund fand sich keinerlei Lüge. Sie sind ohne Makel.
^{[[#fn5][5]]}\\
\\

<<v6>>
** Das Gericht: 14,6 - 20,15
   :PROPERTIES:
   :CUSTOM_ID: das-gericht-146---2015
   :END:
**** Die Ankündigung des Gerichts: 14,6-13
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-des-gerichts-146-13
     :END:
6 Dann sah ich: Ein anderer Engel flog hoch am Himmel. Er hatte den
Bewohnern der Erde ein ewiges Evangelium zu verkünden, allen Nationen,
Stämmen, Sprachen und Völkern.

<<v7>>
7 Er rief mit lauter Stimme: Fürchtet Gott und erweist ihm die Ehre!
Denn die Stunde seines Gerichts ist gekommen. Betet ihn an, /der den
Himmel und die Erde, das Meer/ und die Wasserquellen /geschaffen hat./
^{[[#fn6][6]]}

<<v8>>
8 Ein anderer Engel, ein zweiter, folgte und rief: /Gefallen, gefallen
ist Babylon, die Große, die alle Völker betrunken gemacht hat mit dem
Zornwein/ ihrer Hurerei. ^{[[#fn7][7]][[#fn8][8]]}

<<v9>>
9 Ein anderer Engel, ein dritter, folgte ihnen und rief mit lauter
Stimme: Wer das Tier und sein Standbild anbetet und wer das Kennzeichen
auf seiner Stirn oder seiner Hand annimmt,

<<v10>>
10 der muss /den Wein des Zornes/ Gottes trinken, der unverdünnt /im
Becher seines Zorns gemischt ist./ Und er wird mit /Feuer und Schwefel/
gequält vor den Augen der heiligen Engel und des Lammes. ^{[[#fn9][9]]}

<<v11>>
11 /Der Rauch/ von ihrer Peinigung /steigt auf in/ alle /Ewigkeit/ und
alle, die das Tier und sein Standbild anbeten und die seinen Namen als
Kennzeichen annehmen, werden bei Tag und Nacht keine Ruhe haben.
^{[[#fn10][10]]}

<<v12>>
12 Hier muss sich die Standhaftigkeit der Heiligen bewähren, die an den
Geboten Gottes und an der Treue zu Jesus festhalten.

<<v13>>
13 Und ich hörte eine Stimme vom Himmel her rufen: Schreibe! Selig die
Toten, die im Herrn sterben, von jetzt an; ja, spricht der Geist, sie
sollen ausruhen von ihren Mühen; denn ihre Werke begleiten sie.
^{[[#fn11][11]][[#fn12][12]]}\\
\\

<<v14>>
**** Die Stunde der Ernte: 14,14-20
     :PROPERTIES:
     :CUSTOM_ID: die-stunde-der-ernte-1414-20
     :END:
14 Dann sah ich eine weiße Wolke. Auf der /Wolke/ thronte einer, der
/wie ein Menschensohn aussah./ Er trug einen goldenen Kranz auf dem
Haupt und eine scharfe Sichel in der Hand. ^{[[#fn13][13]][[#fn14][14]]}

<<v15>>
15 Und ein anderer Engel kam aus dem Tempel und rief dem, der auf der
Wolke saß, mit lauter Stimme zu: /Schick/ deine /Sichel aus/ und ernte!
Denn die Zeit zu ernten ist gekommen: /Die Frucht/ der Erde /ist reif/
geworden. ^{[[#fn15][15]]}

<<v16>>
16 Und der, der auf der Wolke saß, schleuderte seine Sichel über die
Erde und die Erde wurde abgeerntet.

<<v17>>
17 Und ein anderer Engel trat aus dem himmlischen Tempel. Auch er hatte
eine scharfe Sichel.

<<v18>>
18 Vom Altar her kam noch ein anderer Engel, der die Macht über das
Feuer hatte. Dem, der die scharfe Sichel trug, rief er mit lauter Stimme
zu: /Schick/ deine scharfe /Sichel aus/ und ernte die Trauben vom
Weinstock der Erde! Seine Beeren /sind reif/ geworden. ^{[[#fn16][16]]}

<<v19>>
19 Da schleuderte der Engel seine Sichel auf die Erde, erntete den
Weinstock der Erde ab und warf die Trauben in die große Kelter des
Zornes Gottes.

<<v20>>
20 /Die Kelter/ wurde draußen vor der Stadt /getreten/ und Blut strömte
aus der Kelter; es stieg an, bis an die Zügel der Pferde,
eintausendsechshundert Stadien weit. ^{[[#fn17][17]][[#fn18][18]]}\\
\\

^{[[#fnm1][1]]} ℘ Ez 9,4

^{[[#fnm2][2]]} 1-5: Die Christen, die in der Verfolgung dem Lamm die
Treue gehalten haben, werden aus den Katastrophen der Endzeit gerettet.
Zur Zahl «hundertvierundvierzigtausend» vgl. die Anmerkung zu 7,4-17. In
V. 4 wird auf alttestamentliche Bildsprache zurückgegriffen; vgl. die
Anmerkungen zu 12,1-6 und 21,9f.

^{[[#fnm3][3]]} ℘ Ez 1,24; 43,2

^{[[#fnm4][4]]} ℘ Ps 33,3; Jes 42,10

^{[[#fnm5][5]]} ℘ Jes 53,9; Zef 3,13

^{[[#fnm6][6]]} ℘ Ex 20,11

^{[[#fnm7][7]]} ℘ Jes 21,9; Dan 4,27; Jer 51,7f

^{[[#fnm8][8]]} Babylon war für die Juden der Inbegriff weltlicher Macht
und Gottlosigkeit, später wurde es apokalyptischer Deckname für Rom
(vgl. 1 Petr 5,13).

^{[[#fnm9][9]]} ℘ Jes 51,17.22; Ps 75,9 G; Jer 25,15; Gen 19,24

^{[[#fnm10][10]]} ℘ Jes 34,9f

^{[[#fnm11][11]]} ℘ 1,3

^{[[#fnm12][12]]} Andere Übersetzungsmöglichkeit: . . . im Herrn
sterben. Von jetzt an - ja, spricht der Geist - sollen sie ausruhen von
ihren Mühen.

^{[[#fnm13][13]]} ℘ Dan 7,13

^{[[#fnm14][14]]} 14-20: Auf die Ankündigung des Gerichts (14,6-13)
folgt die Vision vom Gericht haltenden Menschensohn. Die Bilder (Ernte,
Weinlese) stammen aus dem Alten Testament (vgl. Joël 4,12f).

^{[[#fnm15][15]]} ℘ Joël 4,13

^{[[#fnm16][16]]} ℘ Joël 4,13

^{[[#fnm17][17]]} ℘ Joël 4,13; Jes 63,3

^{[[#fnm18][18]]} Als ein Vielfaches der symbolischen Zahl der Erde
(Vier) symbolisiert die Zahl 1600 (4 mal 4 mal 100) die ganze Erde. -
«Stadion» ist ein griechisches Längenmaß, etwa 185 bis 200 Meter.
