:PROPERTIES:
:ID:       efaa3f12-8989-4564-91f5-b4410b399e60
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Philipper* --
[[file:Phil_1.html][1]] *2* [[file:Phil_3.html][3]]
[[file:Phil_4.html][4]]

--------------

* Phil 2
  :PROPERTIES:
  :CUSTOM_ID: phil-2
  :END:

<<verses>>

<<v1>>
1 Wenn es also Ermahnung in Christus gibt, Zuspruch aus Liebe, eine
Gemeinschaft des Geistes, herzliche Zuneigung und Erbarmen,

<<v2>>
2 dann macht meine Freude dadurch vollkommen, dass ihr eines Sinnes
seid, einander in Liebe verbunden, einmütig und einträchtig,

<<v3>>
3 dass ihr nichts aus Ehrgeiz und nichts aus Prahlerei tut. Sondern in
Demut schätze einer den andern höher ein als sich selbst.

<<v4>>
4 Jeder achte nicht nur auf das eigene Wohl, sondern auch auf das der
anderen.\\
\\

<<v5>>
**** Das Beispiel Christi: 2,5-11
     :PROPERTIES:
     :CUSTOM_ID: das-beispiel-christi-25-11
     :END:
5 Seid untereinander so gesinnt, wie es dem Leben in Christus Jesus
entspricht:\\
\\

<<v6>>
6 Er war Gott gleich, /\\
 hielt aber nicht daran fest, wie Gott zu sein, ^{[[#fn1][1]]}\\
\\

<<v7>>
7 sondern er entäußerte sich /\\
 und wurde wie ein Sklave /\\
 und den Menschen gleich. /\\
 Sein Leben war das eines Menschen;\\
\\

<<v8>>
8 er erniedrigte sich /\\
 und war gehorsam bis zum Tod, /\\
 bis zum Tod am Kreuz.\\
\\

<<v9>>
9 Darum hat ihn Gott über alle erhöht /\\
 und ihm den Namen verliehen, /\\
 der größer ist als alle Namen,\\
\\

<<v10>>
10 damit alle im Himmel, auf der Erde und unter der Erde /\\
 ihre /Knie beugen/ vor dem Namen Jesu ^{[[#fn2][2]]}\\
\\

<<v11>>
11 /und jeder Mund bekennt:/ /\\
 «Jesus Christus ist der Herr» - /\\
 zur Ehre Gottes, des Vaters.\\
\\

<<v12>>
**** Die Sorge des Apostels um das Heil der Gemeinde: 2,12-18
     :PROPERTIES:
     :CUSTOM_ID: die-sorge-des-apostels-um-das-heil-der-gemeinde-212-18
     :END:
12 Darum, liebe Brüder - ihr wart ja immer gehorsam, nicht nur in meiner
Gegenwart, sondern noch viel mehr jetzt in meiner Abwesenheit -: müht
euch mit Furcht und Zittern um euer Heil!

<<v13>>
13 Denn Gott ist es, der in euch das Wollen und das Vollbringen bewirkt,
noch über euren guten Willen hinaus.

<<v14>>
14 Tut alles ohne Murren und Bedenken,

<<v15>>
15 damit ihr rein und ohne Tadel seid, /Kinder Gottes ohne Makel/ mitten
in einer /verdorbenen und verwirrten Generation,/ unter der ihr als
Lichter in der Welt leuchtet. ^{[[#fn3][3]]}

<<v16>>
16 Haltet fest am Wort des Lebens, mir zum Ruhm für den Tag Christi,
damit ich nicht vergeblich gelaufen bin oder mich /umsonst abgemüht
habe./ ^{[[#fn4][4]]}

<<v17>>
17 Wenn auch mein Leben dargebracht wird zusammen mit dem Opfer und
Gottesdienst eures Glaubens, freue ich mich dennoch und ich freue mich
mit euch allen.

<<v18>>
18 Ebenso sollt auch ihr euch freuen; freut euch mit mir!
^{[[#fn5][5]]}\\
\\

<<v19>>
** Die Pläne des Apostels: 2,19-30
   :PROPERTIES:
   :CUSTOM_ID: die-pläne-des-apostels-219-30
   :END:
19 Ich hoffe aber im Vertrauen auf Jesus, den Herrn, dass ich Timotheus
bald zu euch schicken kann, damit auch ich ermutigt werde, wenn ich
erfahre, wie es um euch steht. ^{[[#fn6][6]]}

<<v20>>
20 Ich habe keinen Gleichgesinnten, der so aufrichtig um eure Sache
besorgt ist;

<<v21>>
21 denn alle suchen ihren Vorteil, nicht die Sache Jesu Christi.

<<v22>>
22 Ihr wisst ja, wie er sich bewährt hat: Wie ein Kind dem Vater - so
hat er mit mir zusammen dem Evangelium gedient.

<<v23>>
23 Ihn also hoffe ich schicken zu können, sobald ich meine Lage
übersehe.

<<v24>>
24 Doch ich habe die Zuversicht im Herrn, dass auch ich bald kommen
kann.

<<v25>>
25 Ich hielt es aber für notwendig, Epaphroditus, meinen Bruder,
Mitarbeiter und Mitstreiter, euren Abgesandten und Helfer in meiner Not,
zu euch zu schicken.

<<v26>>
26 Er sehnte sich danach, euch alle wieder zu sehen, und war beunruhigt,
weil ihr gehört hattet, dass er krank geworden war.

<<v27>>
27 Er war tatsächlich so krank, dass er dem Tod nahe war. Aber Gott
hatte Erbarmen mit ihm, und nicht nur mit ihm, sondern auch mit mir,
damit ich nicht vom Kummer überwältigt würde.

<<v28>>
28 Umso mehr beeile ich mich, ihn zu schicken, damit ihr euch wieder
freut, wenn ihr ihn seht, und auch ich weniger Kummer habe.

<<v29>>
29 Nehmt ihn also im Herrn mit aller Freude auf und haltet Menschen wie
ihn in Ehren,

<<v30>>
30 denn wegen seiner Arbeit für Christus kam er dem Tod nahe. Er hat
sein Leben aufs Spiel gesetzt, um zu vollenden, was an eurem Dienst für
mich noch gefehlt hat.\\
\\

^{[[#fnm1][1]]} 6-11: Paulus greift hier einen Hymnus auf, in dem der
Weg Christi von seinem vorzeitlichen Sein über seine Menschwerdung und
seinen Tod bis zur Erhöhung und Einsetzung zum Herrscher des Alls
beschrieben wird. Der im Lied betonte Gehorsam Jesu wird der Gemeinde
als Vorbild gegenseitigen Dienens vor Augen gestellt.

^{[[#fnm2][2]]} ℘ Jes 45,23

^{[[#fnm3][3]]} ℘ Dtn 32,5

^{[[#fnm4][4]]} ℘ Jes 65,23 G; 49,4

^{[[#fnm5][5]]} ℘ 3,1

^{[[#fnm6][6]]} ℘ Apg 16,1
