:PROPERTIES:
:ID:       bf085927-1040-4199-8ce7-8019fa09bbec
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Römer* --
[[file:Röm_1.html][1]] [[file:Röm_2.html][2]] [[file:Röm_3.html][3]] *4*
[[file:Röm_5.html][5]] [[file:Röm_6.html][6]] ...
[[file:Röm_16.html][16]]

--------------

* Röm 4
  :PROPERTIES:
  :CUSTOM_ID: röm-4
  :END:

<<verses>>

<<v1>>
**** Die Anrechnung des Glaubens als Gerechtigkeit: das Beispiel
Abrahams: 4,1-25
     :PROPERTIES:
     :CUSTOM_ID: die-anrechnung-des-glaubens-als-gerechtigkeit-das-beispiel-abrahams-41-25
     :END:
1 Müssen wir nun nicht fragen: Was hat dann unser leiblicher Stammvater
Abraham erlangt? ^{[[#fn1][1]]}

<<v2>>
2 Wenn Abraham aufgrund von Werken Gerechtigkeit erlangt hat, dann hat
er zwar Ruhm, aber nicht vor Gott. ^{[[#fn2][2]]}

<<v3>>
3 Denn die Schrift sagt: /Abraham glaubte Gott und das wurde ihm als
Gerechtigkeit angerechnet./ ^{[[#fn3][3]]}

<<v4>>
4 Dem, der Werke tut, werden diese nicht aus Gnade angerechnet, sondern
er bekommt den Lohn, der ihm zusteht.

<<v5>>
5 Dem aber, der keine Werke tut, sondern an den glaubt, der den
Gottlosen gerecht macht, dem wird sein Glaube als Gerechtigkeit
angerechnet.

<<v6>>
6 Auch David preist den Menschen selig, dem Gott Gerechtigkeit
unabhängig von Werken anrechnet:\\
\\

<<v7>>
7 /Selig sind die, deren Frevel vergeben/ /\\
 /und deren Sünden bedeckt sind./ ^{[[#fn4][4]]}\\
\\

<<v8>>
8 /Selig ist der Mensch,/ /\\
 /dem der Herr die Sünde nicht anrechnet./

<<v9>>
9 Gilt nun diese Seligpreisung nur den Beschnittenen oder auch den
Unbeschnittenen? Wir haben gesagt: /Abraham wurde der Glaube als
Gerechtigkeit angerechnet./ ^{[[#fn5][5]]}

<<v10>>
10 Wann wurde er ihm angerechnet: als er beschnitten oder als er
unbeschnitten war? Nicht als er beschnitten, sondern als er noch
unbeschnitten war. ^{[[#fn6][6]]}

<<v11>>
11 Das Zeichen der Beschneidung empfing er zur Besiegelung der
Glaubensgerechtigkeit, die ihm als Unbeschnittenem zuteil wurde; also
ist er der Vater aller, die als Unbeschnittene glauben und denen daher
Gerechtigkeit angerechnet wird,

<<v12>>
12 und er ist der Vater jener Beschnittenen, die nicht nur beschnitten
sind, sondern auch den Weg des Glaubens gehen, des Glaubens, den unser
Vater Abraham schon vor seiner Beschneidung hatte. ^{[[#fn7][7]]}

<<v13>>
13 Denn Abraham und seine Nachkommen erhielten nicht aufgrund des
Gesetzes die Verheißung, Erben der Welt zu sein, sondern aufgrund der
Glaubensgerechtigkeit. ^{[[#fn8][8]]}

<<v14>>
14 Wenn nämlich jene Erben sind, die das Gesetz haben, dann ist der
Glaube entleert und die Verheißung außer Kraft gesetzt.

<<v15>>
15 Das Gesetz bewirkt Zorn; wo es aber das Gesetz nicht gibt, da gibt es
auch keine Übertretung. ^{[[#fn9][9]]}

<<v16>>
16 Deshalb gilt: «aus Glauben», damit auch gilt: «aus Gnade». Nur so
bleibt die Verheißung für alle Nachkommen gültig, nicht nur für die,
welche das Gesetz haben, sondern auch für die, welche wie Abraham den
Glauben haben. ^{[[#fn10][10]]}

<<v17>>
17 Nach dem Schriftwort: /Ich habe dich zum Vater vieler Völker
bestimmt,/ ist er unser aller Vater vor Gott, dem er geglaubt hat, dem
Gott, der die Toten lebendig macht und das, was nicht ist, ins Dasein
ruft. ^{[[#fn11][11]]}

<<v18>>
18 Gegen alle Hoffnung hat er voll Hoffnung geglaubt, dass er der Vater
vieler Völker werde, nach dem Wort: /So zahlreich werden deine
Nachkommen sein./ ^{[[#fn12][12]]}

<<v19>>
19 Ohne im Glauben schwach zu werden, war er, der fast Hundertjährige,
sich bewusst, dass sein Leib und auch Saras Mutterschoß erstorben waren.
^{[[#fn13][13]]}

<<v20>>
20 Er zweifelte nicht im Unglauben an der Verheißung Gottes, sondern
wurde stark im Glauben und er erwies Gott Ehre,

<<v21>>
21 fest davon überzeugt, dass Gott die Macht besitzt zu tun, was er
verheißen hat. ^{[[#fn14][14]]}

<<v22>>
22 Darum wurde der Glaube /ihm als Gerechtigkeit angerechnet./
^{[[#fn15][15]]}

<<v23>>
23 Doch nicht allein um seinetwillen steht in der Schrift, dass der
Glaube ihm angerechnet wurde,

<<v24>>
24 sondern auch um unseretwillen; er soll auch uns angerechnet werden,
die wir an den glauben, der Jesus, unseren Herrn, von den Toten
auferweckt hat. ^{[[#fn16][16]]}\\
\\

<<v25>>
25 Wegen unserer Verfehlungen wurde er hingegeben, /\\
 wegen unserer Gerechtmachung wurde er auferweckt.
^{[[#fn17][17]][[#fn18][18]]}\\
\\

^{[[#fnm1][1]]} 1-25: Vgl. die Anmerkung zu Jak 2,20-24.

^{[[#fnm2][2]]} ℘ Jak 2,21-24

^{[[#fnm3][3]]} ℘ Gen 15,6; Gal 3,6; Jak 2,23

^{[[#fnm4][4]]} ℘ Ps 32,1f

^{[[#fnm5][5]]} ℘ 10-11: Gen 15,6

^{[[#fnm6][6]]} ℘ Gen 17,10f; Gal 3,7

^{[[#fnm7][7]]} ℘ Mt 3,9

^{[[#fnm8][8]]} ℘ Gen 12,7; 18,18; 22,16-18

^{[[#fnm9][9]]} ℘ 3,20; 5,13; 7,8.10

^{[[#fnm10][10]]} ℘ Gal 3,7-9

^{[[#fnm11][11]]} ℘ Gen 17,5; Hebr 11,19

^{[[#fnm12][12]]} ℘ Gen 15,5

^{[[#fnm13][13]]} ℘ Gen 17,17; Hebr 11,11

^{[[#fnm14][14]]} ℘ Gen 18,14; Lk 1,37

^{[[#fnm15][15]]} ℘ Gen 15,6

^{[[#fnm16][16]]} ℘ 10,9

^{[[#fnm17][17]]} ℘ Jes 53,4f.12

^{[[#fnm18][18]]} Paulus zitiert erneut einen ihm vorgegebenen
christlichen Bekenntnissatz.
