:PROPERTIES:
:ID:       91a4def2-2a1b-4a55-a6a4-d5c12f96a158
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Römer* --
[[file:Röm_1.html][1]] ... [[file:Röm_7.html][7]] [[file:Röm_8.html][8]]
*9* [[file:Röm_10.html][10]] [[file:Röm_11.html][11]] ...
[[file:Röm_16.html][16]]

--------------

* Röm 9
  :PROPERTIES:
  :CUSTOM_ID: röm-9
  :END:

<<verses>>

<<v1>>
** Die endgültige Rettung Israels: 9,1 - 11,36
   :PROPERTIES:
   :CUSTOM_ID: die-endgültige-rettung-israels-91---1136
   :END:
**** Paulus und Israel: 9,1-5
     :PROPERTIES:
     :CUSTOM_ID: paulus-und-israel-91-5
     :END:
1 Ich sage in Christus die Wahrheit und lüge nicht und mein Gewissen
bezeugt es mir im Heiligen Geist: ^{[[#fn1][1]]}

<<v2>>
2 Ich bin voll Trauer, unablässig leidet mein Herz.

<<v3>>
3 Ja, ich möchte selber verflucht und von Christus getrennt sein um
meiner Brüder willen, die der Abstammung nach mit mir verbunden sind.

<<v4>>
4 Sie sind Israeliten; damit haben sie die Sohnschaft, die Herrlichkeit,
die Bundesordnungen, ihnen ist das Gesetz gegeben, der Gottesdienst und
die Verheißungen, ^{[[#fn2][2]][[#fn3][3]]}

<<v5>>
5 sie haben die Väter und dem Fleisch nach entstammt ihnen der Christus,
der über allem als Gott steht, er ist gepriesen in Ewigkeit. Amen.
^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v6>>
**** Die bleibende Erwählung durch Gott: 9,6-13
     :PROPERTIES:
     :CUSTOM_ID: die-bleibende-erwählung-durch-gott-96-13
     :END:
6 Es ist aber keineswegs so, dass Gottes Wort hinfällig geworden ist.
Denn nicht alle, die aus Israel stammen, sind Israel; ^{[[#fn6][6]]}

<<v7>>
7 auch sind nicht alle, weil sie Nachkommen Abrahams sind, deshalb schon
seine Kinder, sondern es heißt: Nur /die Nachkommen Isaaks werden deine
Nachkommen heißen./ ^{[[#fn7][7]]}

<<v8>>
8 Das bedeutet: Nicht die Kinder des Fleisches sind Kinder Gottes,
sondern die Kinder der Verheißung werden als Nachkommen anerkannt;
^{[[#fn8][8]]}

<<v9>>
9 denn es ist eine Verheißung, wenn gesagt wird: /In einem Jahr werde
ich wiederkommen, dann wird Sara einen Sohn haben./ ^{[[#fn9][9]]}

<<v10>>
10 So war es aber nicht nur bei ihr, sondern auch bei Rebekka: Sie hatte
von einem einzigen Mann empfangen, von unserem Vater Isaak,

<<v11>>
11 und ihre Kinder waren noch nicht geboren und hatten weder Gutes noch
Böses getan; damit aber Gottes freie Wahl und Vorherbestimmung gültig
bleibe, ^{[[#fn10][10]]}

<<v12>>
12 nicht abhängig von Werken, sondern von ihm, der beruft, wurde ihr
gesagt: /Der Ältere muss dem Jüngeren dienen;/ ^{[[#fn11][11]]}

<<v13>>
13 denn es steht in der Schrift: /Jakob habe ich geliebt, Esau aber
gehasst./ ^{[[#fn12][12]]}\\
\\

<<v14>>
**** Die Freiheit und das Erbarmen Gottes: 9,14-29
     :PROPERTIES:
     :CUSTOM_ID: die-freiheit-und-das-erbarmen-gottes-914-29
     :END:
14 Heißt das nun, dass Gott ungerecht handelt? Keineswegs!
^{[[#fn13][13]]}

<<v15>>
15 Denn zu Mose sagt er: /Ich schenke Erbarmen, wem ich will, und
erweise Gnade, wem ich will./ ^{[[#fn14][14]]}

<<v16>>
16 Also kommt es nicht auf das Wollen und Streben des Menschen an,
sondern auf das Erbarmen Gottes. ^{[[#fn15][15]]}

<<v17>>
17 In der Schrift wird zum Pharao gesagt: /Eben dazu habe ich dich
bestimmt, dass ich an dir meine Macht zeige und dass auf der ganzen Erde
mein Name verkündet wird./ ^{[[#fn16][16]]}

<<v18>>
18 Er erbarmt sich also, wessen er will, und macht verstockt, wen er
will. ^{[[#fn17][17]]}

<<v19>>
19 Nun wirst du einwenden: Wie kann er dann noch anklagen, wenn niemand
seinem Willen zu widerstehen vermag? ^{[[#fn18][18]]}

<<v20>>
20 Wer bist du denn, dass du als Mensch mit Gott rechten willst? /Sagt
etwa das Werk zu dem, der es geschaffen hat:/ Warum hast du mich so
gemacht? ^{[[#fn19][19]]}

<<v21>>
21 Ist nicht vielmehr der Töpfer Herr über den Ton? Kann er nicht aus
derselben Masse ein Gefäß herstellen für Reines, ein anderes für
Unreines? ^{[[#fn20][20]][[#fn21][21]]}

<<v22>>
22 Gott, der seinen Zorn zeigen und seine Macht erweisen wollte, hat die
Gefäße des Zorns, die zur Vernichtung bestimmt sind, mit großer Langmut
ertragen; ^{[[#fn22][22]]}

<<v23>>
23 und um an den Gefäßen des Erbarmens, die er zur Herrlichkeit
vorherbestimmt hat, den Reichtum seiner Herrlichkeit zu erweisen,
^{[[#fn23][23]]}

<<v24>>
24 hat er uns berufen, nicht allein aus den Juden, sondern auch aus den
Heiden. ^{[[#fn24][24]]}

<<v25>>
25 So spricht er auch bei Hosea: /Ich werde als mein Volk berufen, was
nicht mein Volk war, und als Geliebte jene, die nicht geliebt war./
^{[[#fn25][25]]}

<<v26>>
26 /Und dort, wo ihnen gesagt wurde: Ihr seid nicht mein Volk, dort
werden sie Söhne des lebendigen Gottes genannt werden./ ^{[[#fn26][26]]}

<<v27>>
27 Und Jesaja ruft über Israel aus: /Wenn auch die Israeliten so
zahlreich wären wie der Sand am Meer - nur der Rest wird gerettet
werden./ ^{[[#fn27][27]]}

<<v28>>
28 /Denn der Herr wird handeln, indem er sein Wort auf der Erde erfüllt
und durchsetzt./

<<v29>>
29 Ebenso hat Jesaja vorhergesagt: /Hätte nicht der Herr der himmlischen
Heere uns Nachkommenschaft übrig gelassen, wir wären wie Sodom geworden,
wir wären Gomorra gleich./ ^{[[#fn28][28]]}\\
\\

<<v30>>
**** Israels falscher Eifer für Gott: 9,30 - 10,4
     :PROPERTIES:
     :CUSTOM_ID: israels-falscher-eifer-für-gott-930---104
     :END:
30 Was heißt das nun? Heiden, die die Gerechtigkeit nicht erstrebten,
haben Gerechtigkeit empfangen, die Gerechtigkeit aus Glauben.
^{[[#fn29][29]][[#fn30][30]]}

<<v31>>
31 Israel aber, das nach dem Gesetz der Gerechtigkeit strebte, hat das
Gesetz verfehlt. ^{[[#fn31][31]]}

<<v32>>
32 Warum? Weil es ihm nicht um die Gerechtigkeit aus Glauben, sondern um
die Gerechtigkeit aus Werken ging. Sie stießen sich am «Stein des
Anstoßes», ^{[[#fn32][32]]}

<<v33>>
33 wie es in der Schrift heißt: /Siehe, ich richte in Zion einen Stein
auf, an dem man anstößt, einen Fels, an dem man zu Fall kommt. Wer an
ihn glaubt, wird nicht zugrunde gehen./ ^{[[#fn33][33]]}

^{[[#fnm1][1]]} 1-5: die Bereitschaft des Paulus, selbst verflucht zu
sein, des Heils wieder verlustig zu gehen, bringt zum Ausdruck, wie sehr
er um die Rettung Israels ringt.

^{[[#fnm2][2]]} ℘ Ex 4,22; 40,34f; Röm 3,2; Eph 2,12

^{[[#fnm3][3]]} die Bundesordnungen, wörtlich: die Bundesschlüsse. -
Vgl. die Anmerkung zu Eph 2,12.

^{[[#fnm4][4]]} ℘ 1,3; 1 Kor 15,28

^{[[#fnm5][5]]} Andere Übersetzung: . . . und dem Fleisch nach entstammt
ihnen der Christus. Gott, der über allem ist, er ist gepriesen in
Ewigkeit. Amen. - In Anlehnung an die liturgische Tradition des
Judentums dürfte es sich ursprünglich um einen auf Gott selbst bezogenen
Lobspruch handeln. Aufgrund von Phil 2,9-11 und Joh 20,28 wurde er in
der kirchlichen Tradition schon früh im Sinn der im Text wiedergegebenen
Übersetzung verstanden.

^{[[#fnm6][6]]} ℘ 3,1-4; 11,29; 2,28

^{[[#fnm7][7]]} ℘ Gen 21,12; Mt 3,9

^{[[#fnm8][8]]} ℘ Gal 3,7; 4,28

^{[[#fnm9][9]]} ℘ Gen 18,10

^{[[#fnm10][10]]} ℘ 11,5f

^{[[#fnm11][11]]} ℘ Gen 25,23

^{[[#fnm12][12]]} ℘ Mal 1,2f

^{[[#fnm13][13]]} 14-18: Dass es nicht auf das Wollen und Streben des
Menschen, sondern auf das Erbarmen Gottes ankommt, besagt nicht, dass
menschliches Streben nach Rettung und Heil ohne jede Bedeutung ist. Aber
Gott handelt nach anderen Maßstäben als der Mensch.

^{[[#fnm14][14]]} ℘ Ex 33,19

^{[[#fnm15][15]]} ℘ Eph 2,8

^{[[#fnm16][16]]} ℘ Ex 9,16

^{[[#fnm17][17]]} ℘ 11,30-32; Ex 7,3

^{[[#fnm18][18]]} 19-24: Bei dem aus der alttestamentlichen Prophetie
aufgegriffenen Töpfergleichnis geht es Paulus vor allem um die Langmut
Gottes mit den «Gefäßen des Zorns», die zur Umkehr führen soll (2,4). Es
handelt sich also nicht um eine Vorherbestimmung (Prädestination) in dem
Sinn, dass ihr der Mensch völlig willenlos ausgesetzt wäre.

^{[[#fnm19][19]]} ℘ Jes 29,16; 45,9; Weish 12,12

^{[[#fnm20][20]]} ℘ Jer 18,6; 2 Tim 2,20

^{[[#fnm21][21]]} Wörtlich: ein Gefäß herstellen zur Ehre, ein anderes
zur Unehre.

^{[[#fnm22][22]]} ℘ 2,4

^{[[#fnm23][23]]} ℘ 8,29

^{[[#fnm24][24]]} ℘ 1,16; 3,29

^{[[#fnm25][25]]} ℘ Hos 2,25; 1 Petr 2,10

^{[[#fnm26][26]]} ℘ Hos 2,1

^{[[#fnm27][27]]} ℘ Jes 10,22f G; Röm 11,5

^{[[#fnm28][28]]} ℘ Jes 1,9 G

^{[[#fnm29][29]]} ℘ 10,20

^{[[#fnm30][30]]} 30-33: Dass Israel das Heil verfehlt, hängt damit
zusammen, dass es im falschen Vertrauen auf die eigene Frömmigkeit nicht
begreift, dass Gott das Heil aus Gnade schenkt.

^{[[#fnm31][31]]} ℘ 10,2f; 11,7

^{[[#fnm32][32]]} ℘ 1 Kor 1,23

^{[[#fnm33][33]]} ℘ Jes 8,14; 28,16; Mt 21,42; 1 Petr 2,6-8
