:PROPERTIES:
:ID:       7cb10066-8093-4aa3-9926-b9ec56695587
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Der Brief an die Römer* --
[[file:Röm_1.html][1]] [[file:Röm_2.html][2]] *3* [[file:Röm_4.html][4]]
[[file:Röm_5.html][5]] ... [[file:Röm_16.html][16]]

--------------

* Röm 3
  :PROPERTIES:
  :CUSTOM_ID: röm-3
  :END:

<<verses>>

<<v1>>
**** Gottes Treue angesichts der Sünde der Menschen: 3,1-20
     :PROPERTIES:
     :CUSTOM_ID: gottes-treue-angesichts-der-sünde-der-menschen-31-20
     :END:
1 Was ist nun der Vorzug der Juden, der Nutzen der Beschneidung?

<<v2>>
2 Er ist groß in jeder Hinsicht. Vor allem: Ihnen sind die Worte Gottes
anvertraut. ^{[[#fn1][1]]}

<<v3>>
3 Wenn jedoch einige Gott die Treue gebrochen haben, wird dann etwa ihre
Untreue die Treue Gottes aufheben? ^{[[#fn2][2]]}

<<v4>>
4 Keineswegs! Gott soll sich als der Wahrhaftige erweisen, /jeder
Mensch/ aber als /Lügner/, wie es in der Schrift heißt: /So behältst du
Recht mit deinen Worten und trägst den Sieg davon, wenn man mit dir
rechtet./ ^{[[#fn3][3]][[#fn4][4]]}

<<v5>>
5 Wenn aber unsere Ungerechtigkeit die Gerechtigkeit Gottes bestätigt,
was sagen wir dann? Ist Gott - ich frage sehr menschlich - nicht
ungerecht, wenn er seinen Zorn walten lässt? ^{[[#fn5][5]]}

<<v6>>
6 Keineswegs! Denn wie könnte Gott die Welt sonst richten?

<<v7>>
7 Wenn aber die Wahrheit Gottes sich durch meine Unwahrheit als noch
größer erweist und so Gott verherrlicht wird, warum werde ich dann als
Sünder gerichtet? ^{[[#fn6][6]]}

<<v8>>
8 Gilt am Ende das, womit man uns verleumdet und was einige uns in den
Mund legen: Lasst uns Böses tun, damit Gutes entsteht? Diese Leute
werden mit Recht verurteilt.

<<v9>>
9 Was heißt das nun? Sind wir als Juden im Vorteil? Ganz und gar nicht.
Denn wir haben vorher die Anklage erhoben, dass alle, Juden wie
Griechen, unter der Herrschaft der Sünde stehen, ^{[[#fn7][7]]}\\
\\

<<v10>>
10 wie es in der Schrift heißt: /Es gibt keinen, der gerecht ist,/ /\\
 /auch nicht einen;/ ^{[[#fn8][8]]}\\
\\

<<v11>>
11 /es gibt keinen Verständigen,/ /\\
 /keinen, der Gott sucht./\\
\\

<<v12>>
12 /Alle sind abtrünnig geworden,/ /\\
 /alle miteinander taugen nichts./ /\\
 /Keiner tut Gutes,/ /\\
 /auch nicht ein Einziger./\\
\\

<<v13>>
13 /Ihre Kehle ist ein offenes Grab,/ /\\
 /mit ihrer Zunge betrügen sie;/ /\\
 /Schlangengift ist auf ihren Lippen./ ^{[[#fn9][9]]}\\
\\

<<v14>>
14 /Ihr Mund ist voll Fluch und Gehässigkeit./ ^{[[#fn10][10]]}\\
\\

<<v15>>
15 /Schnell sind sie dabei, Blut zu vergießen;/ / ^{[[#fn11][11]]}\\
\\

<<v16>>
16 /Verderben und Unheil sind auf ihren Wegen,/ /\\
\\

<<v17>>
17 /und den Weg des Friedens kennen sie nicht./\\
\\

<<v18>>
18 /Die Gottesfurcht steht ihnen nicht vor Augen./ ^{[[#fn12][12]]}

<<v19>>
19 Wir wissen aber: Was das Gesetz sagt, sagt es denen, die unter dem
Gesetz leben, damit jeder Mund verstummt und die ganze Welt vor Gott
schuldig wird. ^{[[#fn13][13]]}

<<v20>>
20 Denn durch Werke des Gesetzes wird /niemand vor ihm gerecht werden;/
durch das Gesetz kommt es vielmehr zur Erkenntnis der Sünde.
^{[[#fn14][14]]}\\
\\

<<v21>>
*** Gerechtigkeit und neues Leben: 3,21 - 8,39
    :PROPERTIES:
    :CUSTOM_ID: gerechtigkeit-und-neues-leben-321---839
    :END:
**** Das Kreuz Christi als Grund der neuen Gerechtigkeit: 3,21-31
     :PROPERTIES:
     :CUSTOM_ID: das-kreuz-christi-als-grund-der-neuen-gerechtigkeit-321-31
     :END:
21 Jetzt aber ist unabhängig vom Gesetz die Gerechtigkeit Gottes
offenbart worden, bezeugt vom Gesetz und von den Propheten:
^{[[#fn15][15]]}

<<v22>>
22 die Gerechtigkeit Gottes aus dem Glauben an Jesus Christus, offenbart
für alle, die glauben. Denn es gibt keinen Unterschied: ^{[[#fn16][16]]}

<<v23>>
23 Alle haben gesündigt und die Herrlichkeit Gottes verloren.

<<v24>>
24 Ohne es verdient zu haben, werden sie gerecht, dank seiner Gnade,
durch die Erlösung in Christus Jesus. ^{[[#fn17][17]][[#fn18][18]]}

<<v25>>
25 Ihn hat Gott dazu bestimmt, Sühne zu leisten mit seinem Blut, Sühne,
wirksam durch Glauben. So erweist Gott seine Gerechtigkeit durch die
Vergebung der Sünden, die früher, in der Zeit seiner Geduld, begangen
wurden; ^{[[#fn19][19]]}

<<v26>>
26 er erweist seine Gerechtigkeit in der gegenwärtigen Zeit, um zu
zeigen, dass er gerecht ist und den gerecht macht, der an Jesus glaubt.

<<v27>>
27 Kann man sich da noch rühmen? Das ist ausgeschlossen. Durch welches
Gesetz? Durch das der Werke? Nein, durch das Gesetz des Glaubens.
^{[[#fn20][20]][[#fn21][21]]}

<<v28>>
28 Denn wir sind der Überzeugung, dass der Mensch gerecht wird durch
Glauben, unabhängig von Werken des Gesetzes. ^{[[#fn22][22]]}

<<v29>>
29 Ist denn Gott nur der Gott der Juden, nicht auch der Heiden? Ja, auch
der Heiden, ^{[[#fn23][23]]}

<<v30>>
30 da doch gilt: Gott ist «der Eine». Er wird aufgrund des Glaubens
sowohl die Beschnittenen wie die Unbeschnittenen gerecht machen.
^{[[#fn24][24]]}

<<v31>>
31 Setzen wir nun durch den Glauben das Gesetz außer Kraft? Im
Gegenteil, wir richten das Gesetz auf. ^{[[#fn25][25]]}\\
\\

^{[[#fnm1][1]]} ℘ 9,4

^{[[#fnm2][2]]} ℘ 9,6; 11,1.29

^{[[#fnm3][3]]} ℘ Ps 116,11; 51,6 G

^{[[#fnm4][4]]} Hinter diesem Gedanken steht die Vorstellung vom
Rechtsstreit Gottes mit den Menschen, bei dem sich sein Recht erweisen
und durchsetzen wird (z. B. Jes 1,18-20).

^{[[#fnm5][5]]} ℘ 9,14

^{[[#fnm6][6]]} ℘ 6,1

^{[[#fnm7][7]]} ℘ 1,16; 2,9f; 11,32

^{[[#fnm8][8]]} ℘ Koh 7,20; Ps 14,1-3

^{[[#fnm9][9]]} ℘ Ps 5,10 G; 140,4

^{[[#fnm10][10]]} ℘ Ps 10,7 G

^{[[#fnm11][11]]} ℘ Jes 59,7f; Spr 1,16

^{[[#fnm12][12]]} ℘ Ps 36,2

^{[[#fnm13][13]]} ℘ 7,7

^{[[#fnm14][14]]} ℘ Ps 143,2 G; Gal 2,16; 3,21f

^{[[#fnm15][15]]} ℘ 1,17

^{[[#fnm16][16]]} ℘ Phil 3,9

^{[[#fnm17][17]]} ℘ Eph 2,8; Tit 3,7

^{[[#fnm18][18]]} 24-26: Gott hat seine Gerechtigkeit darin gezeigt,
dass er durch den Tod Jesu die «Ungerechtigkeit» aller Menschen aufhebt
und den Gottlosen «Gerechtigkeit» schenkt (vgl. 4,5). Den VV. 25f liegt
wohl ein alter Bekenntnissatz zugrunde. - Leiden und Sterben bewirken
nach jüdischer Auffassung Sühne, auch stellvertretende Sühne.

^{[[#fnm19][19]]} ℘ Lev 16,12-15

^{[[#fnm20][20]]} ℘ 8,2

^{[[#fnm21][21]]} 27-31: Gesetz und Glaube stehen zueinander in
Gegensatz, wenn das Gesetz als Weg zum Heil angesehen wird. Zum Heil
kann nach der Offenbarung Gottes in Jesus Christus nur der Glaube
führen. Das «Gesetz» wird gleichwohl «aufgerichtet», das heißt seine
Forderung wird erfüllt durch den «Glauben, der in der Liebe wirksam ist»
(vgl. Gal 5,6; Röm 13,8-10).

^{[[#fnm22][22]]} ℘ Gal 2,16

^{[[#fnm23][23]]} ℘ 10,12; 9,24

^{[[#fnm24][24]]} ℘ Dtn 6,4; Röm 4,11f

^{[[#fnm25][25]]} ℘ 6,15; Mt 5,17
