#+TITLE: 1 Chr 16 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-20 Mo 11:07]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Chr 16.html

* 1.Chr 16

<<verses>>

<<v1>>
1 Man trug die Lade Gottes in das Zelt, das David für sie aufgestellt
hatte, setzte sie an ihren Platz in der Mitte des Zeltes und brachte
Brand- und Heilsopfer vor Gott dar.

<<v2>>
2 Als David mit dem Darbringen der Brand- und Heilsopfer fertig war,
segnete er das Volk im Namen des Herrn

<<v3>>
3 und ließ an alle Israeliten, Männer und Frauen, je einen Laib Brot,
einen Dattelkuchen und einen Traubenkuchen austeilen.\\
\\

<<v4>>
* Das Loblied Davids: 16,4-36

4 David bestellte für den Dienst vor der Lade des Herrn Leviten, die den
Herrn, den Gott Israels, rühmen, loben und preisen sollten.

<<v5>>
5 Er bestellte Asaf als ersten, Secharja als zweiten, ferner Jaasiël,
Schemiramot, Jehiël, Mattitja, Eliab, Benaja, Obed-Edom und Jëiël. Sie
sollten die Harfen und Zithern spielen, Asaf die Zimbeln schlagen

<<v6>>
6 und die Priester Benaja und Jahasiël ständig die Trompeten blasen vor
der Bundeslade Gottes.

<<v7>>
7 An jenem Tag ließ David Asaf und seine Amtsbrüder zum ersten Mal
diesen Lobpreis zur Ehre des Herrn vortragen:\\
\\

<<v8>>
8 Dankt dem Herrn! Ruft seinen Namen an! /\\
 Macht unter den Völkern seine Taten bekannt! [fn:1]\\
\\

<<v9>>
9 Singt ihm und spielt ihm, /\\
 sinnt nach über all seine Wunder!\\
\\

<<v10>>
10 Rühmt euch seines heiligen Namens! /\\
 Alle, die den Herrn suchen, /\\
 sollen sich von Herzen freuen.\\
\\

<<v11>>
11 Fragt nach dem Herrn und seiner Macht, /\\
 sucht sein Antlitz allezeit!\\
\\

<<v12>>
12 Denkt an die Wunder, die er getan hat, /\\
 an seine Zeichen und die Beschlüsse aus seinem Mund!\\
\\

<<v13>>
13 Bedenkt es, ihr Nachkommen seines Knechtes Abraham, /\\
 ihr Kinder Jakobs, die er erwählt hat!\\
\\

<<v14>>
14 Er, der Herr, ist unser Gott. /\\
 Seine Herrschaft umgreift die Erde.\\
\\

<<v15>>
15 Ewig denkt er an seinen Bund, /\\
 an das Wort, das er gegeben hat für tausend Geschlechter,\\
\\

<<v16>>
16 an den Bund, den er mit Abraham geschlossen, /\\
 an den Eid, den er Isaak geschworen hat.\\
\\

<<v17>>
17 Er bestimmte ihn als Satzung für Jakob, /\\
 als ewigen Bund für Israel.\\
\\

<<v18>>
18 Er sprach: Dir will ich Kanaan geben, /\\
 das Land, das dir als Erbe bestimmt ist.\\
\\

<<v19>>
19 Als sie noch gering waren an Zahl, /\\
 nur wenige und fremd im Land,\\
\\

<<v20>>
20 und noch zogen von Volk zu Volk, /\\
 von einem Reich zum andern,\\
\\

<<v21>>
21 da ließ er sie von niemand bedrücken, /\\
 wies ihretwegen Könige zurecht:\\
\\

<<v22>>
22 Tastet meine Gesalbten nicht an, /\\
 tut meinen Propheten nichts zuleide!\\
\\

<<v23>>
23 Singt dem Herrn, alle Länder der Erde! /\\
 Verkündet sein Heil von Tag zu Tag! [fn:2]\\
\\

<<v24>>
24 Erzählt bei den Völkern von seiner Herrlichkeit, /\\
 bei allen Nationen von seinen Wundern!\\
\\

<<v25>>
25 Denn groß ist der Herr und hoch zu preisen, /\\
 mehr zu fürchten als alle Götter.\\
\\

<<v26>>
26 Alle Götter der Heiden sind nichtig, /\\
 der Herr aber hat den Himmel geschaffen.\\
\\

<<v27>>
27 Hoheit und Pracht sind vor seinem Angesicht, /\\
 Macht und Glanz in seinem Heiligtum.\\
\\

<<v28>>
28 Bringt dar dem Herrn, ihr Stämme der Völker, /\\
 bringt dar dem Herrn Lob und Ehre!\\
\\

<<v29>>
29 Bringt dar dem Herrn die Ehre seines Namens, /\\
 spendet Opfergaben und tretet vor ihn hin! /\\
 In heiligem Schmuck werft euch nieder vor dem Herrn,\\
\\

<<v30>>
30 erbebt vor ihm, alle Länder der Erde! /\\
 Den Erdkreis hat er gegründet, sodass er nicht wankt.\\
\\

<<v31>>
31 Der Himmel freue sich, die Erde frohlocke. /\\
 Verkündet bei den Völkern: Der Herr ist König.\\
\\

<<v32>>
32 Es brause das Meer und alles, was es erfüllt, /\\
 es jauchze die Flur und was auf ihr wächst.\\
\\

<<v33>>
33 Jubeln sollen alle Bäume des Waldes vor dem Herrn, /\\
 wenn er kommt, um die Erde zu richten.\\
\\

<<v34>>
34 Danket dem Herrn, denn er ist gütig, /\\
 denn seine Huld währt ewig. [fn:3]\\
\\

<<v35>>
35 Sagt: Hilf uns, du Gott unsres Heils, /\\
 führe uns zusammen, rette uns vor den Völkern! Wir wollen deinen
heiligen Namen preisen, /\\
 uns rühmen, weil wir dich loben dürfen. [fn:4]\\
\\

<<v36>>
36 Gepriesen sei der Herr, der Gott Israels, /\\
 vom Anfang bis ans Ende der Zeiten. Und das ganze Volk rief: Amen, und:
Lob sei dem Herrn.\\
\\

<<v37>>
* Der Gottesdienst in Jerusalem und in Gibeon: 16,37-43

37 Auf Befehl Davids blieben Asaf und seine Brüder vor der Bundeslade
des Herrn, um dauernd den täglichen Dienst bei ihr zu verrichten. [fn:5]

<<v38>>
38 Bei ihnen waren Obed-Edom und seine Brüder, achtundsechzig Mann.
Obed-Edom, der Sohn Jedutuns, und Hosa waren Torwächter. [fn:6]

<<v39>>
39 Dem Priester Zadok aber und seinen Amtsbrüdern, den Priestern,
übertrug er den Dienst vor der Wohnstätte des Herrn auf der Kulthöhe in
Gibeon.

<<v40>>
40 Sie sollten täglich am Morgen und am Abend auf dem Brandopferaltar
dem Herrn Opfer darbringen und alles ausführen, was im Gesetz
geschrieben steht, auf das der Herr die Israeliten verpflichtet hat.

<<v41>>
41 Bei ihnen waren Heman und Jedutun sowie die anderen, die ausgewählt
und namentlich dazu bestimmt waren, den Herrn zu loben: «Denn seine Huld
währt ewig.»

<<v42>>
42 Heman und Jedutun hatten Trompeten und Zimbeln für die Spieler und
Instrumente für die Gotteslieder. Die Söhne Jedutuns waren für das Tor
bestellt.

<<v43>>
43 Dann ging das ganze Volk wieder nach Hause. Auch David ging heim, um
seine Familie zu begrüßen. [fn:7]\\
\\

* Footnotes

[fn:1] (8-22) [[file:Ps_105.org::v1][Ps 105,1-15]]

[fn:2] (23-33) [[file:Ps_96.org::v1][Ps 96,1-13]]

[fn:3] [[file:Ps_106.org::v1][Ps 106,1]]

[fn:4] (35-36) [[file:Ps_106.org::v47][Ps 106,47f]]

[fn:5] 37-41: Nach Chr wurde der liturgische Dienst fortan
sowohl vor der Bundeslade in Jerusalem als auch vor dem Zelt in Gibeon
vollzogen. Als Sänger wirkten Heman und Jedutun (= Etan, vgl. [[file:1.Chr_15.org::v17][15,17]]) in
Gibeon, Asaf in Jerusalem. Da Zadok für den Opferdienst in Gibeon
bestellt war, ist anzunehmen, dass Abjatar in Jerusalem wirkte.

[fn:6] Chr unterscheidet den Sänger Obed-Edom ([[file:1.Chr_15.org::v18][15,18]].[[file:1.Chr_15.org::v21][21]]; [[v5][16,5]])
vom Torhüter gleichen Namens ([[file:1.Chr_15.org::v24][15,24]]; [[v38][16,38]]; [[file:1.Chr_26.org::v4][26,4]]) und dem
Nichtisraeliten aus Gat ([[file:1.Chr_13.org::v13][13,13f]]).

[fn:7] [[file:2.Sam_6.org::v19][2 Sam 6,19f]]
