#+TITLE: 1 Chr 29 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-21 Di 22:17]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 29.html

<<verses>>

<<v1>>
* Die Spenden für den Tempelbau: 29,1-9

1 Darauf wandte sich König David an die ganze Versammlung: Mein Sohn
Salomo, den allein Gott erwählt hat, ist noch jung und unerfahren. Das
Werk aber ist groß; denn wir bauen nicht für Menschen, sondern für Gott,
den Herrn. [fn:1]

<<v2>>
2 Nach meinen besten Kräften habe ich nun für das Haus meines Gottes
Gold beschafft für die goldenen, Silber für die silbernen, Bronze für
die bronzenen, Eisen für die eisernen und Holz für die hölzernen
Gegenstände, dazu Schohamsteine mit Einfassungen, Malachit und
buntfarbige Steine sowie allerlei Edelsteine und Alabaster in Menge.

<<v3>>
3 Aus Liebe zum Haus meines Gottes spende ich aus meinem Besitz, meinem
Gold und Silber, über all das hinaus, was ich für das Haus des
Heiligtums schon bereitgestellt habe, [fn:2]

<<v4>>
4 noch weitere 3000 Talente Gold vom Ofirgold und 7000 Talente
geläutertes Silber. Man soll damit die Wände der Räume verkleiden [fn:3]

<<v5>>
5 und Gold zur Verfügung haben für die goldenen und Silber für die
silbernen Gegenstände und für jede Arbeit von Künstlerhand. Wer ist nun
bereit, seine Hand ebenso für den Herrn zu füllen? [fn:4]

<<v6>>
6 Da zeigten die Häupter der Großfamilien, die Vorsteher der
israelitischen Stämme, die Obersten der Tausend- und Hundertschaften und
die obersten Beamten des königlichen Dienstes ihre Freigebigkeit.

<<v7>>
7 Sie spendeten für den Bau des Hauses Gottes 5000 Talente Gold, 10000
Golddariken, 10000 Talente Silber, 18000 Talente Bronze, 100000 Talente
Eisen. [fn:5]

<<v8>>
8 Wer Edelsteine besaß, gab sie zum Schatz des Hauses des Herrn in die
Hände Jehiëls, eines Nachkommen Gerschons.

<<v9>>
9 Das Volk freute sich über diese Freigebigkeit, denn sie hatten mit
ungeteiltem Herzen willig für den Herrn gespendet. Auch König David
hatte eine große Freude.\\
\\

<<v10>>
* Das Dankgebet Davids: 29,10-20

10 Da pries David den Herrn vor der ganzen Versammlung und rief:
Gepriesen bist du, Herr, Gott unseres Vaters Israel, von Ewigkeit zu
Ewigkeit.

<<v11>>
11 Dein, Herr, sind Größe und Kraft, Ruhm und Glanz und Hoheit; dein ist
alles im Himmel und auf Erden. Herr, dein ist das Königtum. Du erhebst
dich als Haupt über alles.

<<v12>>
12 Reichtum und Ehre kommen von dir; du bist der Herrscher über das All.
In deiner Hand liegen Kraft und Stärke; von deiner Hand kommt alle Größe
und Macht.

<<v13>>
13 Darum danken wir dir, unser Gott, und rühmen deinen herrlichen Namen.

<<v14>>
14 Doch wer bin ich und was ist mein Volk, dass wir die Kraft besaßen,
diese Gaben zu spenden? Von dir kommt ja alles; und was wir dir gegeben
haben, stammt aus deiner Hand.

<<v15>>
15 Denn wir sind nur Gäste bei dir, Fremdlinge, wie alle unsere Väter.
Wie ein Schatten sind unsere Tage auf Erden und ohne Hoffnung. [fn:6]

<<v16>>
16 Herr, unser Gott, diese ganze Fülle, die wir bereitgestellt haben, um
dir, deinem heiligen Namen, ein Haus zu bauen, kam aus deiner Hand; dir
gehört alles.

<<v17>>
17 Ich weiß, mein Gott, dass du die Herzen prüfst und an Aufrichtigkeit
Gefallen hast. Mit aufrichtigem Herzen habe ich dies alles gegeben und
ich habe mit Freuden gesehen, wie auch dein Volk, das sich hier
eingefunden hat, dir willig spendet. [fn:7]

<<v18>>
18 Herr, Gott unserer Väter Abraham, Isaak und Israel, erhalte diese
Gesinnung für immer im Herzen deines Volkes! Lenke sein Herz auf dich!

<<v19>>
19 Gib auch meinem Sohn Salomo ein ungeteiltes Herz, damit er auf deine
Gebote, Anordnungen und Gesetze achtet und alles tut, um den Bau zu
errichten, den ich vorbereitet habe.

<<v20>>
20 Dann befahl David der ganzen Versammlung: Preist den Herrn, euren
Gott! Und die ganze Versammlung lobte den Herrn, den Gott ihrer Väter.
Sie verneigten sich und warfen sich nieder vor dem Herrn und dem
König.\\
\\

<<v21>>
* Salomos Thronbesteigung: 29,21-25

21 Am folgenden Tag brachten sie dem Herrn Opfer dar. Sie spendeten zu
Brandopfern tausend Stiere, tausend Widder, tausend Lämmer sowie die
dazugehörenden Trankopfer. Dazu kam eine Menge Schlachtopfer für ganz
Israel.

<<v22>>
22 Voller Freude aßen und tranken sie an jenem Tag vor dem Herrn und
machten Salomo, den Sohn Davids, zum zweiten Mal zum König. Sie salbten
ihn zum Fürsten des Herrn und Zadok salbten sie zum Priester.

<<v23>>
23 Salomo setzte sich nun anstelle seines Vaters David als König auf den
Thron des Herrn. Er hatte Glück und ganz Israel leistete ihm Gehorsam.

<<v24>>
24 Alle hohen Beamten und Helden, auch alle Söhne des Königs David,
unterwarfen sich Salomo. [fn:8]

<<v25>>
25 Der Herr ließ Salomo überaus mächtig werden vor den Augen Israels. Er
verlieh seinem Königtum einen Glanz, wie ihn kein König in Israel vor
ihm besessen hatte.\\
\\

<<v26>>
* Der Abschluss der Geschichte Davids: 29,26-30

26 David, der Sohn Isais, war König von ganz Israel.

<<v27>>
27 Die Zeit, die er in Israel regierte, betrug vierzig Jahre. In Hebron
regierte er sieben und in Jerusalem dreiunddreißig Jahre.

<<v28>>
28 Er starb in hohem Alter, satt an Tagen, Reichtum und Ehre. Sein Sohn
Salomo wurde König an seiner Stelle.

<<v29>>
29 Die frühere und die spätere Geschichte des Königs David ist
aufgezeichnet in der Geschichte des Sehers Samuel, in der Geschichte des
Propheten Natan und in der Geschichte des Sehers Gad. [fn:9]

<<v30>>
30 Sie berichten von seiner ganzen Regierung, seiner Machtentfaltung und
von den Zeiten, die über ihn, über Israel und alle Reiche der Länder
hinweggegangen sind.\\
\\

* Footnotes

[fn:1] [[file:1.Chr_22.org::v5][22,5]]

[fn:2] [[file:1.Chr_22.org::v14][22,14]]

[fn:3] Handelsfahrten nach Ofir sind erst unter Salomo bezeugt (vgl. [[file:1.Kön_9.org::v28][1 Kön 9,28]]).

[fn:4] Seine Hand für Jahwe füllen: hier nicht Weiheritus, wie
[[file:Ex_28.org::v41][Ex 28,41]]; [[file:Lev_8.org::v27][Lev 8,27]]; [[file:1.Kön_13.org::v33][1 Kön 13,33]] in H, sondern: etwas in die Hand nehmen,
um es dem Herrn darzubringen.

[fn:5] Eine Darike ist eine Münze; die Bezeichnung soll auf den
Perserkönig Darius I. (522-486 v. Chr.) zurückgehen.

[fn:6] [[file:Ps_39.org::v13][Ps 39,13]]

[fn:7] [[file:Ps_7.org::v10][Ps 7,10]]

[fn:8] Vgl. die Anmerkung zu [[file:1.Chr_28.org::v1][28,1]].

[fn:9] Die erwähnten Quellenwerke könnten die biblischen
Samuelbücher sein, die über die drei Genannten berichten.
