#+TITLE: 1 Chr 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 21:59]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 5.html

<<verses>>

<<v1>>
* Der Stamm Ruben: 5,1-10

1 Die Söhne Rubens, des Erstgeborenen Israels: Ruben war der
Erstgeborene. Da er aber das Bett seines Vaters entweiht hatte, wurde
sein Erstgeburtsrecht den Söhnen Josefs, des Sohnes Israels, gegeben.
Doch richten sich die Stammeslisten nicht nach dem Erstgeburtsrecht; [fn:1] [fn:2]

<<v2>>
2 Juda erlangte nämlich die Herrschaft über seine Brüder und einer aus
ihm wurde der Fürst, obwohl das Erstgeburtsrecht bei Josef war.

<<v3>>
3 Die Söhne Rubens, des Erstgeborenen Israels, waren: Henoch, Pallu,
Hezron und Karmi. [fn:3]

<<v4>>
4 Der Sohn Joëls war Schemaja, dessen Sohn Gog, dessen Sohn Schimi,

<<v5>>
5 dessen Sohn Micha, dessen Sohn Reaja, dessen Sohn Baal,

<<v6>>
6 dessen Sohn Beera, den Tiglat-Pileser, der König von Assur,
verschleppte. Er war der Anführer der Rubeniter.

<<v7>>
7 Seine Brüder wurden, als sie sich nach ihren Geschlechterfolgen in die
Stammeslisten eintragen ließen, seinen Familien zugezählt. Der erste war
Jëiël, ihm folgte Secharja.

<<v8>>
8 Bela war der Sohn des Asas, des Sohnes Schemas, des Sohnes Joëls. Die
Rubeniter wohnten in Aroër bis Nebo und Baal-Meon. [fn:4]

<<v9>>
9 Ostwärts wohnten sie bis an den Rand der Steppe, die sich vom Eufrat
her erstreckt; denn sie besaßen große Herden im Land Gilead.

<<v10>>
10 In den Tagen Sauls führten sie Krieg mit den Hagaritern. Diese fielen
in ihre Hand und sie besetzten ihre Zelte auf der ganzen Ostseite von
Gilead.\\
\\

<<v11>>
* Der Stamm Gad: 5,11-17

11 Die Nachkommen Gads wohnten ihnen gegenüber im Gebiet des Baschan bis
Salcha.

<<v12>>
12 Ihr Oberhaupt war Joël; Schafam war der Zweite, dazu kamen Janai und
Schafat; sie wohnten im Baschan.

<<v13>>
13 Ihre Brüder mit ihren Großfamilien waren Michael, Meschullam, Scheba,
Jorai, Jakan, Sia und Eber, insgesamt sieben.

<<v14>>
14 Das waren die Söhne Abihajils, des Sohnes Huris, des Sohnes Jaroachs,
des Sohnes Gileads, des Sohnes Michaels, des Sohnes Jeschischais, des
Sohnes Jachdos, des Sohnes des Bus: ... [fn:5]

<<v15>>
15 Ahi, der Sohn Abdiëls, des Sohnes Gunis, war Haupt ihrer
Großfamilien.

<<v16>>
16 Sie wohnten in Gilead, im Baschan und seinen Tochterstädten und an
allen Weideflächen Scharons bis zu ihren Ausläufern.

<<v17>>
17 In den Tagen Jotams, des Königs von Juda, und in den Tagen Jerobeams,
des Königs von Israel, wurden alle in die Stammeslisten eingetragen.\\
\\

<<v18>>
* Der Krieg mit Nachbarstämmen: 5,18-22

18 Die Krieger von Ruben, Gad und dem halben Stamm Manasse, Männer, die
Schild und Schwert trugen, den Bogen spannten und im Kampf geübt waren,
vierundvierzigtausendsiebenhundertsechzig Mann, die im Heer ausrückten,

<<v19>>
19 führten Krieg gegen die Hagariter und gegen Jetur, Nafisch und Nodab.

<<v20>>
20 Sie waren siegreich und konnten die Hagariter und deren Verbündete in
ihre Gewalt bringen; denn sie schrien im Kampf zu Gott und dieser ließ
sich erbitten, da sie auf ihn vertrauten.

<<v21>>
21 So führten sie deren Besitz weg: 50000 Kamele, 250000 Schafe und 2000
Esel, dazu 100000 Personen.

<<v22>>
22 Viele Feinde wurden erschlagen und fielen, denn es war ein Krieg
Gottes. Die Israeliten siedelten sich an ihrer Stelle an und blieben
dort bis zur Verschleppung.\\
\\

<<v23>>
* Der Stamm Ost-Manasse: 5,23-26

23 Die Angehörigen des halben Stammes Manasse wohnten in dem Land, das
vom Baschan bis Baal-Hermon, zum Senir und zum Hermongebirge reicht. Sie
waren sehr zahlreich.

<<v24>>
24 Und das waren die Häupter ihrer Großfamilien: Efer, Jischi, Eliël,
Asriël, Jirmeja, Hodawja und Jachdiël. Sie waren tapfere Krieger, Männer
von Namen, Häupter ihrer Großfamilien.

<<v25>>
25 Doch wurden sie dem Gott ihrer Väter untreu und gaben sich den
Göttern der Landesbevölkerung hin, die Gott vor ihnen vertrieben hatte.

<<v26>>
26 Darum erweckte der Gott Israels den Geist Puls, des Königs von Assur,
das heißt den Geist Tiglat-Pilesers, des Königs von Assur. Dieser führte
die Rubeniter, die Gaditer und den halben Stamm Manasse in die
Verbannung und brachte sie nach Halach, an den Habor, nach Hara und an
den Fluss von Gosan. Dort sind sie bis zum heutigen Tag. [fn:6] [fn:7]\\
\\

<<v27>>
* Der Stamm Levi: 5,27-41

27 Die Söhne Levis waren: Gerschon, Kehat und Merari. [fn:8]

<<v28>>
28 Die Söhne Kehats waren: Amram, Jizhar, Hebron und Usiël.

<<v29>>
29 Die Kinder Amrams waren: Aaron, Mose und Mirjam. Die Söhne Aarons
waren: Nadab, Abihu, Eleasar und Itamar.

<<v30>>
30 Eleasar zeugte Pinhas, Pinhas zeugte Abischua,

<<v31>>
31 Abischua zeugte Bukki, Bukki zeugte Usi,

<<v32>>
32 Usi zeugte Serachja, Serachja zeugte Merajot,

<<v33>>
33 Merajot zeugte Amarja, Amarja zeugte Ahitub,

<<v34>>
34 Ahitub zeugte Zadok, Zadok zeugte Ahimaaz,

<<v35>>
35 Ahimaaz zeugte Asarja, Asarja zeugte Johanan,

<<v36>>
36 Johanan zeugte Asarja - dieser war es, der im Tempel, den Salomo in
Jerusalem erbaute, das Priesteramt verwaltete -, [fn:9]

<<v37>>
37 Asarja zeugte Amarja, Amarja zeugte Ahitub,

<<v38>>
38 Ahitub zeugte Zadok, Zadok zeugte Schallum,

<<v39>>
39 Schallum zeugte Hilkija, Hilkija zeugte Asarja,

<<v40>>
40 Asarja zeugte Seraja, Seraja zeugte Jozadak.

<<v41>>
41 Jozadak zog fort, als der Herr Juda und Jerusalem durch Nebukadnezzar
in die Verbannung führte.\\
\\

* Footnotes

[fn:1] [[file:Gen_35.org::v22][Gen 35,22]]; [[file:Gen_49.org::v3][49,3f]]

[fn:2] Der Vers will erklären, warum das Buch den Stamm Juda
und nicht die Stämme Ruben oder Josef an erster Stelle bringt: Es
geschah, weil ihm das Königtum zufiel.

[fn:3] [[file:Gen_46.org::v9][Gen 46,9]]

[fn:4] Die Städte liegen im Süden des Ostjordanlands.

[fn:5] Die Namen der Söhne fehlen in H.

[fn:6] [[file:2.Kön_17.org::v6][2 Kön 17,6]]

[fn:7] zu Pul: vgl. die Anmerkung zu [[file:2.Kön_15.org::v19][2 Kön 15,19]].

[fn:8] (27-30) [[file:Ex_6.org::v16][Ex 6,16-25]]

[fn:9] Die Zwischenbemerkung ist an falscher Stelle eingereiht.
Sie gehört zu dem in V. 35 genannten Asarja (vgl. [[file:1.Kön_4.org::v2][1 Kön 4,2]]).
