#+TITLE: 1 Chr 8 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 22:54]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 8.html

<<verses>>

<<v1>>
* Das zweite Verzeichnis des Stammes Benjamin: 8,1-28

1 Benjamin zeugte Bela als seinen Erstgeborenen, Aschbel als zweiten,
Achrach als dritten, [fn:1]

<<v2>>
2 Noha als vierten und Rafa als fünften.

<<v3>>
3 Bela hatte folgende Söhne: Ard, Gera, Abihud,

<<v4>>
4 Abischua, Naaman, Ahoach,

<<v5>>
5 Gera, Schefufan und Huram.

<<v6>>
6 Und das waren die Söhne Ehuds . . . Sie waren die Familienhäupter der
Bewohner von Geba . . . Man führte sie in die Verbannung nach Manahat. [fn:2]

<<v7>>
7 Naaman, Ahija und Gera . . . Dieser führte sie gefangen fort. Er
zeugte Usa und Ahihud.

<<v8>>
8 Schaharajim zeugte im Grünland von Moab Söhne, nachdem er seine Frauen
Huschim und Baara entlassen hatte.

<<v9>>
9 Mit seiner Frau Hodesch zeugte er Jobab, Zibja, Mescha, Malkam,

<<v10>>
10 Jëuz, Sacheja und Mirma. Das waren seine Söhne, die Häupter ihrer
Großfamilien.

<<v11>>
11 Mit Huschim zeugte er Abitub und Elpaal.

<<v12>>
12 Die Söhne Elpaals waren: Eber, Mischam und Schemed. Dieser baute Ono
und Lod mit seinen Tochterstädten.

<<v13>>
13 Beria und Schema waren die Häupter der Großfamilien der Einwohner von
Ajalon. Sie vertrieben die Einwohner von Gat.

<<v14>>
14 Ihre Brüder waren Elpaal, Schaschak und Jeroham.

<<v15>>
15 Sebadja, Arad, Eder,

<<v16>>
16 Michael, Jischpa und Joha waren Söhne Berias.

<<v17>>
17 Sebadja, Meschullam, Hiski, Heber,

<<v18>>
18 Jischmerai, Jislia und Jobab waren Söhne Elpaals.

<<v19>>
19 Jakim, Sichri, Sabdi,

<<v20>>
20 Eliënai, Zilletai, Eliël,

<<v21>>
21 Adaja, Beraja und Schimrat waren Söhne Schimis. [fn:3]

<<v22>>
22 Jischpan, Eber, Eliël,

<<v23>>
23 Abdon, Sichri, Hanan,

<<v24>>
24 Hananja, Elam, Antotija,

<<v25>>
25 Jifdeja und Penuël waren Söhne Schaschaks.

<<v26>>
26 Schamscherai, Scheharja, Atalja,

<<v27>>
27 Jaareschja, Elija und Sichri waren Söhne Jerohams.

<<v28>>
28 Sie waren Häupter der Großfamilien entsprechend ihrer
Geschlechterfolge, ihre Oberhäupter, und wohnten in Jerusalem.\\
\\

<<v29>>
* Die Familie Sauls: 8,29-40

29 In Gibeon wohnte Jëiël, der Vater Gibeons. Seine Frau war Maacha [fn:4]

<<v30>>
30 und sein erstgeborener Sohn war Abdon. Ihm folgten Zur, Kisch, Baal,
Ner, Nadab,

<<v31>>
31 Gedor, Achjo, Secher und Miklot.

<<v32>>
32 Miklot zeugte Schima. Auch sie wohnten in Jerusalem bei ihren
Brüdern, ihnen gegenüber.

<<v33>>
33 Ner zeugte Abner und Kisch zeugte Saul. Saul zeugte Jonatan,
Malkischua, Abinadab und Eschbaal. [fn:5]

<<v34>>
34 Der Sohn Jonatans war Merib-Baal. Merib-Baal zeugte Micha. [fn:6]

<<v35>>
35 Die Söhne Michas waren: Piton, Melech, Tachrea und Ahas.

<<v36>>
36 Ahas zeugte Joadda und Joadda zeugte Alemet, Asmawet und Simri. Simri
zeugte Moza,

<<v37>>
37 Moza zeugte Bina; dessen Sohn war Rafa, dessen Sohn Elasa und dessen
Sohn Azel.

<<v38>>
38 Azel hatte sechs Söhne und das sind ihre Namen: Asrikam, Bochru,
Jischmael, Schearja, Obadja und Hanan. Alle diese waren Söhne Azels.

<<v39>>
39 Die Söhne seines Bruders Eschek waren: Ulam, sein Erstgeborener; der
zweite war Jëusch und der dritte Elifelet.

<<v40>>
40 Die Söhne Ulams waren tapfere Krieger, die den Bogen spannten. Sie
hatten viele Söhne und Enkel, insgesamt hundertfünfzig. Alle diese
gehörten zu den Nachkommen Benjamins.

* Footnotes

[fn:1] [[file:Gen_46.org::v21][Gen 46,21]]

[fn:2] 6f: Der Text ist nur lückenhaft überliefert.

[fn:3] Für Schimi steht in V. 13 Schema.

[fn:4] (29-38) [[file:1.Chr_9.org::v35][9,35-44]]

[fn:5] [[file:1.Sam_31.org::v2][1 Sam 31,2]]

[fn:6] [[file:2.Sam_9.org::v6][2 Sam 9,6]]
