#+TITLE: 1 Chr 10 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-20 Mo 09:16]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 10.html

<<verses>>

<<v1>>
* Die Geschichte Davids: 10,1 - 29,30

* Das Ende Sauls: 10,1-14

1 Als die Philister gegen Israel kämpften, flohen die Israeliten vor
ihnen. Viele waren gefallen und lagen erschlagen auf dem Gebirge Gilboa. [fn:1]

<<v2>>
2 Die Philister verfolgten Saul und seine Söhne und erschlugen Sauls
Söhne Jonatan, Abinadab und Malkischua.

<<v3>>
3 Um Saul selbst entstand ein schwerer Kampf. Die Bogenschützen hatten
ihn getroffen und er war schwer verwundet.

<<v4>>
4 Da sagte Saul zu seinem Waffenträger: Zieh dein Schwert und durchbohre
mich damit! Sonst kommen diese Unbeschnittenen und treiben mit mir ihren
Mutwillen. Der Waffenträger wollte es nicht tun, denn er hatte große
Angst. Da nahm Saul selbst das Schwert und stürzte sich hinein.

<<v5>>
5 Als der Waffenträger sah, dass Saul tot war, stürzte auch er sich in
sein Schwert und starb.

<<v6>>
6 So kamen Saul und seine drei Söhne ums Leben; sein ganzes Haus starb
mit ihm. [fn:2]

<<v7>>
7 Als die Israeliten in der Ebene (Jesreel) sahen, dass die Krieger
Israels geflohen und dass Saul und seine Söhne tot waren, verließen sie
ihre Städte und flohen. Dann kamen die Philister und besetzten die
Städte.

<<v8>>
8 Als am nächsten Tag die Philister kamen, um die Erschlagenen
auszuplündern, fanden sie Saul und seine Söhne, die auf dem Gebirge
Gilboa gefallen waren.

<<v9>>
9 Sie zogen ihn aus, nahmen seinen Kopf und seine Rüstung und schickten
beides im Land der Philister umher, um ihren Götzen und dem Volk die
Siegesnachricht zu übermitteln.

<<v10>>
10 Die Rüstung Sauls legten sie im Tempel ihrer Götter nieder. Seinen
Kopf aber hefteten sie an den Tempel des Dagon. [fn:3]

<<v11>>
11 Als die Einwohner von Jabesch-Gilead hörten, was die Philister mit
Saul gemacht hatten, [fn:4]

<<v12>>
12 brachen alle kriegstüchtigen Männer auf, nahmen die Leiche Sauls und
die Leichen seiner Söhne und brachten sie nach Jabesch. Sie begruben
ihre Gebeine unter der Terebinthe in Jabesch und fasteten sieben Tage
lang.

<<v13>>
13 So starb Saul wegen der Treulosigkeit, die er gegen den Herrn
begangen hatte. Er hatte das Wort des Herrn nicht befolgt und den
Totengeist befragt, um Auskunft zu suchen; [fn:5]

<<v14>>
14 an den Herrn aber hatte er sich nicht gewandt. Darum ließ er ihn
sterben und übergab das Königtum David, dem Sohn Isais.\\
\\

* Footnotes

[fn:1] (1-12) [[file:1.Sam_31.org::v1][1 Sam 31,1-13]]

[fn:2] In [[file:1.Chr_8.org::v29][8,29-38]] werden zwar noch zwölf Generationen nach Saul
erwähnt. Da sie aber unbedeutend blieben, kann V. 6 sagen, dass mit Saul
sein ganzes Haus, d.h. seine Dynastie, ausstarb.

[fn:3] Zu Dagon vgl. die Anmerkung zu [[file:1.Sam_5.org::v2][1 Sam 5,2]].

[fn:4] [[file:1.Sam_11.org::v1][1 Sam 11]]

[fn:5] [[file:1.Sam_15.org::v19][1 Sam 15,19]]; [[file:1.Sam_28.org::v8][28,8-19]]
