#+TITLE: 1 Chr 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 21:28]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 2.html

<<verses>>

<<v1>>
* Die Söhne Jakobs: 2,1-2

1 Das waren die Söhne Israels: Ruben, Simeon, Levi, Juda, Issachar,
Sebulon, [fn:1]

<<v2>>
2 Dan, Josef, Benjamin, Naftali, Gad und Ascher.\\
\\

<<v3>>
* Der Stamm Juda: 2,3 - 4,23

* Die Nachkommen Judas: 2,3-9
     :PROPERTIES:
     :CUSTOM_ID: die-nachkommen-judas-23-9
     :END:
3 Die Söhne Judas waren: Er, Onan und Schela. Diese drei wurden ihm von
der Tochter Schuas, der Kanaaniterin, geboren. Aber Er, der Erstgeborene
Judas, missfiel dem Herrn und so ließ ihn der Herr sterben. [fn:2] [fn:3]

<<v4>>
4 Judas Schwiegertochter Tamar gebar Perez und Serach. Juda hatte
insgesamt fünf Söhne.

<<v5>>
5 Die Söhne des Perez waren Hezron und Hamul, [fn:4]

<<v6>>
6 und die Söhne Serachs: Simri, Etan, Heman, Kalkol und Darda, insgesamt
fünf.

<<v7>>
7 Der Sohn Simris war Karmi und der Sohn Karmis Achan. Dieser brachte
Unglück über Israel, da er sich an der geweihten Beute vergriff. [fn:5]

<<v8>>
8 Der Sohn Etans war Asarja.

<<v9>>
9 Dem Hezron wurden die Söhne Jerachmeel, Ram und Kaleb geboren.\\
\\

<<v10>>
* Die Nachkommen Rams: 2,10-17

10 Ram zeugte Amminadab, Amminadab zeugte Nachschon, den Anführer der
Söhne Judas, [fn:6]

<<v11>>
11 Nachschon zeugte Salmon, Salmon zeugte Boas,

<<v12>>
12 Boas zeugte Obed, Obed zeugte Isai,

<<v13>>
13 Isai zeugte Eliab als Erstgeborenen, als zweiten Abinadab, als
dritten Schima,

<<v14>>
14 als vierten Netanel, als fünften Raddai,

<<v15>>
15 als sechsten Ozem, als siebten David.

<<v16>>
16 Ihre Schwestern waren Zeruja und Abigajil. Die Söhne der Zeruja waren
Abischai, Joab und Asaël, diese drei. [fn:7]

<<v17>>
17 Abigajil gebar Amasa. Der Vater Amasas war der Ismaeliter Jeter.\\
\\

<<v18>>
* Die Nachkommen Kalebs: 2,18-24

18 Kaleb, der Sohn Hezrons, zeugte mit seiner Frau Asuba die Jeriot.
Deren Söhne waren Jescher, Schobab und Ardon.

<<v19>>
19 Als Asuba starb, heiratete Kaleb Efrata, die ihm den Hur gebar.

<<v20>>
20 Hur zeugte Uri und Uri zeugte Bezalel. [fn:8]

<<v21>>
21 Danach ging Hezron zur Tochter Machirs, des Vaters Gileads. Er war
sechzig Jahre alt, als er sie nahm, und sie gebar ihm Segub.

<<v22>>
22 Segub zeugte Jaïr. Dieser besaß dreiundzwanzig Städte im Land Gilead. [fn:9]

<<v23>>
23 Doch die Geschuriter und Aramäer nahmen die Zeltdörfer Jaïrs sowie
Kenat und seine Tochterstädte weg, insgesamt sechzig Städte. Sie alle
hatten den Nachkommen Machirs, des Vaters Gileads, gehört.

<<v24>>
24 Nach dem Tod Hezrons kam Kaleb zu Efrata. Eine Frau Hezrons war
Abija; sie gebar ihm Aschhur, den Vater Tekoas.\\
\\

<<v25>>
* Die Nachkommen Jerachmeels: 2,25-41

25 Die Söhne Jerachmeels, des Erstgeborenen Hezrons, waren: Ram, der
Erstgeborene, ferner Buna, Oren, Ozem und Ahija.

<<v26>>
26 Jerachmeel hatte noch eine andere Frau namens Atara. Sie war die
Mutter Onams.

<<v27>>
27 Die Söhne Rams, des Erstgeborenen Jerachmeels, waren: Maaz, Jamin und
Eker.

<<v28>>
28 Die Söhne Onams waren Schammai und Jada und die Söhne Schammais Nadab
und Abischur.

<<v29>>
29 Die Frau Abischurs hieß Abihajil. Sie gebar ihm Achban und Molid.

<<v30>>
30 Die Söhne Nadabs waren Seled und Appajim. Seled starb ohne
Nachkommen.

<<v31>>
31 Der Sohn Appajims war Jischi, der Sohn Jischis Scheschan und die
Tochter Scheschans Achlai. [fn:10]

<<v32>>
32 Die Söhne Jadas, des Bruders von Schammai, waren Jeter und Jonatan.
Jeter starb ohne Nachkommen.

<<v33>>
33 Die Söhne Jonatans waren Pelet und Sasa. Das waren die Nachkommen
Jerachmeels.

<<v34>>
34 Scheschan hatte keine Söhne, sondern nur Töchter. Scheschan hatte
einen ägyptischen Sklaven namens Jarha.

<<v35>>
35 Diesem gab Scheschan seine Tochter zur Frau und sie gebar ihm Attai.

<<v36>>
36 Attai zeugte Natan, Natan zeugte Sabad,

<<v37>>
37 Sabad zeugte Eflal, Eflal zeugte Obed,

<<v38>>
38 Obed zeugte Jehu, Jehu zeugte Asarja,

<<v39>>
39 Asarja zeugte Helez, Helez zeugte Elasa,

<<v40>>
40 Elasa zeugte Sismai, Sismai zeugte Schallum,

<<v41>>
41 Schallum zeugte Jekamja und Jekamja zeugte Elischama.\\
\\

<<v42>>
* Die zweite Liste der Nachkommen Kalebs: 2,42-55

42 Die Söhne Kalebs, des Bruders Jerachmeels, waren: Mescha, sein
Erstgeborener - er war der Vater Sifs -, und sein zweiter Sohn Marescha,
der Vater Hebrons.

<<v43>>
43 Die Söhne Hebrons waren: Korach, Tappuach, Rekem und Schema.

<<v44>>
44 Schema zeugte Raham, den Vater Jorkoams, und Rekem zeugte Schammai.

<<v45>>
45 Der Sohn Schammais war Maon und Maon war der Vater von Bet-Zur.

<<v46>>
46 Efa, die Nebenfrau Kalebs, gebar Haran, Moza und Gases. Haran zeugte
Jahdai.

<<v47>>
47 Die Söhne Jahdais waren: Regem, Jotam, Geschan, Pelet, Efa und
Schaaf.

<<v48>>
48 Kalebs Nebenfrau Maacha gebar Scheber und Tirhana.

<<v49>>
49 Sie gebar auch Schaaf, den Vater Madmannas, sowie Schewa, den Vater
Machbenas und Gibeas. Die Tochter Kalebs war Achsa. [fn:11]

<<v50>>
50 Das waren die Nachkommen Kalebs. Die Söhne Hurs, des Erstgeborenen
der Efrata, waren: Schobal, der Vater von Kirjat-Jearim, [fn:12]

<<v51>>
51 Salmon, der Vater von Betlehem, und Haref, der Vater von Bet-Gader.

<<v52>>
52 Schobal, der Vater von Kirjat-Jearim, hatte als Söhne: Reaja und
Hazi, den Manahatiter.

<<v53>>
53 Die Sippenverbände von Kirjat-Jearim waren die Jeteriter, die
Putiter, die Schumatiter und die Mischraïter. Von ihnen zweigten ab die
Zoraïter und die Eschtaoliter.

<<v54>>
54 Die Söhne Salmons waren: Betlehem, die Netofatiter, Atrot-Bet-Joab,
die Hälfte der Manahatiter und der Zoraïter.

<<v55>>
55 Die Sippenverbände von Sofer, die Einwohner von Jabez, die Tiratiter,
Schimatiter und Suchatiter waren Keniter, die von Hammat, dem Vater von
Bet-Rechab, stammten. [fn:13]\\
\\

* Footnotes

[fn:1] (1-2) [[file:Gen_35.org::v23][Gen 35,23-26]]

[fn:2] (3-9) [[file:Gen_38.org::v3][Gen 38,3]]-[[file:Gen_38.org::v7][7]].[[file:Gen_38.org::v27][27]]-[[file:Gen_38.org::v30][30]]

[fn:3] 3-14: Die von Juda zu David führende Linie begegnet auch
im Stammbaum Jesu (vgl. [[file:~/RoamNotes/notes/Bibel/nt/Mt_1.org::v3][Mt 1,3-6]] und [[file:~/RoamNotes/notes/Bibel/nt/Lk_3.org::v32][Lk 3,32f]]).

[fn:4] [[file:Gen_46.org::v12][Gen 46,12]]

[fn:5] [[file:Jos_7.org::v1][Jos 7]]

[fn:6] (10-15) [[file:Rut_4.org::v19][Rut 4,19-22]]

[fn:7] Die Söhne der Zeruja spielen eine wichtige Rolle in der
Geschichte Davids. Joab war Befehlshaber des Heeres Davids.

[fn:8] Bezalel war der Künstler, der unter Mose das heilige
Zelt mit der Bundeslade und den heiligen Geräten angefertigt hat (vgl.
[[file:Ex_36.org::v1][Ex 36]] - [[file:Ex_38.org::v1][38]]).

[fn:9] [[file:Ri_10.org::v3][Ri 10,3]]

[fn:10] die Tochter: sinngemäß korr., vgl. V. 34.

[fn:11] [[file:Jos_15.org::v16][Jos 15,16]]

[fn:12] Zu Hur, dem Sohn der Efrata, vgl. [[v19][2,19]].

[fn:13] Die Keniter waren ein midianitischer Stamm, der sich
z. T. an die Israeliten anschloss.
