#+TITLE: 1 Chr 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-20 Mo 09:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Chr 12.html

<<verses>>

<<v1>>
* Das dritte Verzeichnis von Anhängern Davids: 12,1-23

1 Diese sind es, die zu David nach Ziklag kamen, als er sich noch von
Saul, dem Sohn des Kisch, fernhalten musste. Sie gehörten zu den Helden,
die ihn im Kampf unterstützten. [fn:1]

<<v2>>
2 Sie waren mit dem Bogen ausgerüstet und konnten mit der rechten und
mit der linken Hand Steine schleudern und Pfeile mit dem Bogen
abschießen. Von den Stammesbrüdern Sauls, von Benjamin, kamen:

<<v3>>
3 Ahiëser, ihr Anführer, ferner Joasch, der Sohn Schemaas, aus Gibea,
Jesiël und Pelet, die Söhne Asmawets, Beracha und Jehu aus Anatot,

<<v4>>
4 Jischmaja aus Gibeon, ein Held unter den Dreißig und ihr Anführer,

<<v5>>
5 Jirmeja, Jahasiël, Johanan und Josabad aus Gedera,

<<v6>>
6 Elusai, Jerimot, Bealja, Schemarja und Schefatja aus Haruf,

<<v7>>
7 Elkana, Jischija, Asarel, Joëser und Jaschobam, die Korachiter,

<<v8>>
8 Joëla und Sebadja, die Söhne Jerohams, aus Gedor.

<<v9>>
9 Auch Gaditer traten zu David über und kamen in die Bergfestung in der
Wüste. Sie waren tapfere Helden, kampfgeübte Krieger mit Schild und
Lanze, waren wie Löwen anzusehen und flink wie Gazellen auf den Bergen. [fn:2]

<<v10>>
10 Eser war der erste, Obadja der zweite, Eliab der dritte,

<<v11>>
11 Mischmanna der vierte, Jirmeja der fünfte,

<<v12>>
12 Attai der sechste, Eliël der siebte,

<<v13>>
13 Johanan der achte, Elsabad der neunte,

<<v14>>
14 Jirmeja der zehnte, Machbannai der elfte.

<<v15>>
15 Diese waren von den Gaditern gekommen. Sie waren Hauptleute im Heer.
Der kleinste von ihnen nahm es mit hundert, der stärkste mit tausend
auf.

<<v16>>
16 Sie waren es, die im ersten Monat den Jordan überquerten, als er über
die Ufer getreten war und die Täler im Osten und Westen abgeschnitten
waren.

<<v17>>
17 Auch Angehörige Benjamins und Judas kamen zu David in die
Bergfestung.

<<v18>>
18 David trat zu ihnen heraus, sprach sie an und sagte: Wenn ihr in
friedlicher Absicht zu mir kommt, um mir zu helfen, so bin ich zur
Gemeinschaft mit euch bereit. Wenn ihr aber kommt, um mich den Feinden
zu verraten, obwohl ich kein Unrecht begangen habe, dann soll der Gott
unserer Väter es sehen und euch strafen.

<<v19>>
19 Da ergriff ein Geist Amasai, das Haupt der Dreißig, sodass er
ausrief: Dir, David, gehören wir. Zu dir, Sohn Isais, stehen wir. Heil,
Heil sei dir, Heil deinem Helfer; denn dir hilft dein Gott. Da nahm sie
David auf und reihte sie ein unter die Anführer seiner Schar.

<<v20>>
20 Auch von Manasse gingen einige zu David über. David zog damals im
Heer der Philister gegen Saul in den Krieg, brachte ihnen aber keine
Hilfe, da ihn die Fürsten der Philister nach einer Beratung
wegschickten. Sie sagten nämlich: Er könnte um den Preis unserer Köpfe
zu seinem Herrn, zu Saul, übergehen. [fn:3] [fn:4]

<<v21>>
21 David kehrte daher nach Ziklag zurück. Zu dieser Zeit stießen von
Manasse zu ihm: Adnach, Josabad, Jediaël, Michael, Josabad, Elihu und
Zilletai, die Häupter der Tausendschaften Manasses.

<<v22>>
22 Sie halfen David im Kampf gegen die Räuberscharen (der Amalekiter);
denn sie alle waren tapfere Krieger und wurden Oberste im Heer.

<<v23>>
23 Tag für Tag kamen Leute zu David, um ihm zu helfen; und so entstand
ein großes Heerlager gleich einem Heerlager Gottes.\\
\\

<<v24>>
* Die Gefolgschaft bei der Thronerhebung in Hebron:

24 Das sind die Zahlen aller wehrfähigen Männer, die zu David nach
Hebron kamen, um ihm nach dem Wort des Herrn das Königtum Sauls zu
übertragen:

<<v25>>
25 Aus Juda kamen 6800 wehrfähige Männer, die Schild und Lanze trugen.

<<v26>>
26 Aus Simeon kamen 7100 tapfere Krieger,

<<v27>>
27 aus Levi 4600 Mann,

<<v28>>
28 dazu Jojada, der Fürst der Nachkommen Aarons, mit 3700 Mann

<<v29>>
29 und Zadok, ein junger, tapferer Krieger, dessen Großfamilie 22 Führer
stellte.

<<v30>>
30 Aus Benjamin, den Stammesbrüdern Sauls, kamen 3000 Mann. Ihre
Mehrheit war bis dahin in der Gefolgschaft des Hauses Saul geblieben.

<<v31>>
31 Aus Efraim kamen 20800 in ihren Großfamilien hoch angesehene Krieger,

<<v32>>
32 aus dem halben Stamm Manasse 18000 Mann, die namentlich dazu bestimmt
waren, zu kommen und David zum König zu machen.

<<v33>>
33 Von den Angehörigen Issachars, die die Zeiten verstanden und wussten,
was Israel zu tun hatte, kamen 200 Oberste mit allen Stammesbrüdern, die
ihrem Befehl unterstanden.

<<v34>>
34 Aus Sebulon kamen 50000 wehrfähige Männer, die mit allen Kriegswaffen
zu kämpfen verstanden und sich ohne Vorbehalt einordneten.

<<v35>>
35 Aus Naftali kamen 1000 Anführer und mit ihnen 37000 Mann mit Schild
und Lanze,

<<v36>>
36 aus Dan 28600 kampfbereite Männer,

<<v37>>
37 aus Ascher 40000 wehrfähige, kampfbereite Männer.

<<v38>>
38 Von jenseits des Jordan, aus Ruben, Gad und dem halben Stamm Manasse
kamen 120000 Mann mit allen Waffen eines Kriegsheeres.

<<v39>>
39 Alle diese waren Krieger, die sich willig einordneten. Sie kamen in
ehrlicher Gesinnung nach Hebron, um David zum König von ganz Israel zu
machen; aber auch alle übrigen Israeliten waren einig im Wunsch, David
zum König zu machen.

<<v40>>
40 Sie blieben drei Tage dort bei David; sie aßen und tranken, denn ihre
Stammesbrüder hatten für sie gesorgt.

<<v41>>
41 Auch jene, die bis nach Issachar, Sebulon und Naftali hin in ihrer
Nähe wohnten, brachten auf Eseln, Kamelen, Maultieren und Rindern
Lebensmittel zum Unterhalt herbei: Mehl, Feigen- und Traubenkuchen,
Wein, Öl und eine große Menge Rinder und Schafe; denn es herrschte
Freude in Israel.\\
\\

* Footnotes

[fn:1] Um sich der Verfolgung durch Saul zu entziehen, war
David zum Philisterkönig Achisch übergetreten, der ihm die Stadt Ziklag,
nördlich von Beerscheba, als Aufenthalt zuwies (vgl. [[file:1.Sam_27.org::v6][1 Sam 27,6]]).

[fn:2] Vor seinem Übertritt zu den Philistern hielt sich David
längere Zeit in der Bergfestung Adullam, südwestlich von Betlehem, auf
und sammelte Anhänger um sich (vgl. [[file:1.Sam_22.org::v1][1 Sam 22,1]]).

[fn:3] [[file:1.Sam_29.org][1 Sam 29]]

[fn:4] (David) brachte . . . keine Hilfe: Text korr.; H: sie
brachten . . . keine Hilfe.
