#+TITLE: 1 Chr 26 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-21 Di 21:51]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Chr 26.html

<<verses>>

<<v1>>
* Die Torwächter: 26,1-19

1 Bei den Abteilungen der Torwächter gehörte Meschelemja, der Sohn
Kores, ein Nachkomme Abiasafs, zu den Korachitern.

<<v2>>
2 Von den Söhnen Meschelemjas war Secharja der Erstgeborene, Jediaël der
zweite, Sebadja der dritte, Jatniël der vierte,

<<v3>>
3 Elam der fünfte, Johanan der sechste, Eljoënai der siebte.

<<v4>>
4 Von den Söhnen Obed-Edoms war Schemaja der Erstgeborene, Josabad der
zweite, Joach der dritte, Sachar der vierte, Netanel der fünfte,

<<v5>>
5 Ammiël der sechste, Issachar der siebte, Pëulletai der achte. Gott
hatte ihn nämlich gesegnet.

<<v6>>
6 Auch seinem Sohn Schemaja wurden Söhne geboren. Sie wurden Oberhäupter
in ihren Großfamilien, denn sie waren tüchtige Männer.

<<v7>>
7 Die Söhne Schemajas waren Otni, Refaël und Obed. Die Söhne seines
Bruders Elsabad waren Elihu und Semachja, ebenfalls tüchtige Männer. [fn:1]

<<v8>>
8 Diese alle waren Nachkommen Obed-Edoms. Sie selbst, ihre Söhne und
Brüder, waren tüchtige Leute und zu ihrem Dienst befähigt:
zweiundsechzig Angehörige Obed-Edoms.

<<v9>>
9 Auch Meschelemja hatte Söhne und Brüder, achtzehn tüchtige Männer.

<<v10>>
10 Ebenso wurden Hosa, einem Nachkommen Meraris, Söhne geboren. Schimri
war ihr Oberhaupt. Sein Vater hatte ihn dazu gemacht, obwohl er nicht
der Erstgeborene war.

<<v11>>
11 Sein zweiter Sohn war Hilkija, der dritte Tebalja, der vierte
Secharja. Insgesamt hatte Hosa dreizehn Söhne und Brüder.

<<v12>>
12 Diese Abteilungen der Torwächter besorgten die Wache mit der
Gesamtheit ihrer Männer. Wie ihre Brüder taten sie Dienst im Haus des
Herrn.

<<v13>>
13 Sie warfen für jedes einzelne Tor das Los in ihren Großfamilien, der
Geringste wie der Größte.

<<v14>>
14 Das Los für das Osttor fiel auf Meschelemja; für seinen Sohn
Secharja, einen klugen Berater, warf man das Los und es traf auf das
Nordtor.

<<v15>>
15 Obed-Edom fiel das Südtor zu und seinen Söhnen das Vorratshaus.

<<v16>>
16 Auf Hosa traf das Westtor mit dem Schallechettor an der aufsteigenden
Straße. Eine Wache entsprach der andern. [fn:2]

<<v17>>
17 Im Osten standen täglich sechs Posten, im Norden täglich vier, im
Süden täglich vier, an den Vorratskammern je zwei. [fn:3]

<<v18>>
18 Am Parbar im Westen waren vier für die Straße und zwei für den Parbar
bestimmt. [fn:4]

<<v19>>
19 Das waren die Abteilungen der Torwächter aus den Nachkommen der
Korachiter und den Nachkommen Meraris.\\
\\

<<v20>>
* Die Aufseher über die Schatzkammern: 26,20-28

20 Einige von den Leviten, ihren Stammesbrüdern, wachten über die
Schätze des Hauses Gottes und über die Schätze aus den Weihegaben. [fn:5]

<<v21a>>
21a Es waren dies die Söhne Ladans, eines Nachkommen Gerschons, nämlich
Jehiël [fn:6] [fn:7]

<<v22a>>
22a mit seinen Söhnen sowie Setam und sein Bruder Joël.

<<v21b>>
21b Sie waren die Familienhäupter Ladans, des Sohnes Gerschons,

<<v22b>>
22b und wachten über die Schätze im Haus des Herrn.

<<v23>>
23 Zu ihnen kamen Nachkommen Amrams, Jizhars, Hebrons und Usiëls. [fn:8]

<<v24>>
24 Schubaël, der Sohn Gerschoms und Enkel des Mose, war Oberaufseher
über die Schätze gewesen. [fn:9]

<<v25>>
25 Sein Stammesbruder aus der Linie Eliësers war dessen Sohn Rehabja;
dessen Sohn war Jeschaja, dessen Sohn Joram, dessen Sohn Sichri und
dessen Sohn Schelomit.

<<v26>>
26 Schelomit und seine Brüder hatten die Aufsicht über alle Schätze aus
den Weihegaben, die König David, die Häupter der Großfamilien, die
Obersten der Tausend- und Hundertschaften und die Obersten des Heeres
gespendet hatten.

<<v27>>
27 Diese hatten aus der Kriegsbeute Weihegaben gestiftet, um das Haus
des Herrn gut auszustatten.

<<v28>>
28 Sie überwachten auch alles, was der Seher Samuel, Saul, der Sohn des
Kisch, Abner, der Sohn Ners, und Joab, der Sohn der Zeruja, gespendet
hatten. Jeder, der eine Weihegabe darbrachte, legte sie in die Hand
Schelomits und seiner Brüder.\\
\\

<<v29>>
* Die Verwaltungsdienste: 26,29-32

29 Von den Nachkommen Jizhars waren Kenanja und seine Söhne als Beamte
und Richter für die äußeren Angelegenheiten in Israel bestellt. [fn:10]

<<v30>>
30 Von den Nachkommen Hebrons hatten Haschabja und seine Brüder,
siebzehnhundert tüchtige Männer, die Aufsicht über Israel westlich des
Jordan in allen Angelegenheiten des Herrn und im Dienst des Königs.

<<v31>>
31 Haupt der Hebroniter war Jerija. Im vierzigsten Jahr der Regierung
Davids suchte man anhand der Geschlechterlisten die Großfamilien der
Hebroniter ab und fand unter ihnen tüchtige Männer in Jaser in Gilead.

<<v32>>
32 König David setzte Jerija und seine Stammesbrüder,
zweitausendsiebenhundert tüchtige Männer, Häupter ihrer Familien, über
die Rubeniter, Gaditer und den halben Stamm Manasse in allen
Angelegenheiten Gottes und des Königs.\\
\\

* Footnotes

[fn:1] Elsabad: Josabad in V. 4 ist derselbe Name, nur mit
anderer Gottesbezeichnung gebildet.

[fn:2] In H steht vor Hosa der Name Schuppim infolge
Verschreibung aus dem vorausgehenden Wort.

[fn:3] täglich: sinngemäß ergänzt.

[fn:4] Zu Parbar vgl. die Anmerkung zu [[file:2.Kön_23.org::v11][2 Kön 23,11]]; dort: Parwar.

[fn:5] ihren Stammesbrüdern: Text korr. nach G.

[fn:6] [[file:1.Chr_23.org::v8][23,8]]

[fn:7] 21f: Text aus inhaltlichen Gründen umgestellt.

[fn:8] [[file:1.Chr_23.org::v12][23,12f]]

[fn:9] [[file:1.Chr_23.org::v15][23,15-17]]

[fn:10] Nach [[file:Dtn_17.org::v8][Dtn 17,8-13]]; [[file:Dtn_19.org::v16][19,16f]] und [[file:Dtn_21.org::v5][21,5]] waren die Leviten an
der Rechtsprechung beteiligt.
