#+TITLE: 1 Chr 11 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-20 Mo 09:20]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Chr 11.html

<<verses>>

<<v1>>
* Die Anerkennung Davids als König: 11,1-3

1 Ganz Israel versammelte sich bei David in Hebron und sagte: Wir sind
doch dein Fleisch und Bein. [fn:1] [fn:2]

<<v2>>
2 Schon früher, als Saul noch König war, hast du Israel in den Kampf und
wieder nach Hause geführt. Und der Herr, dein Gott, hat zu dir gesagt:
Du sollst der Hirt meines Volkes Israel sein, du sollst der Fürst meines
Volkes Israel werden.

<<v3>>
3 Alle Ältesten Israels kamen zum König nach Hebron; David schloss mit
ihnen in Hebron einen Vertrag vor dem Herrn und sie salbten David zum
König von Israel gemäß dem Wort, das der Herr durch Samuel verkündet
hatte. [fn:3]\\
\\

<<v4>>
* Die Eroberung Jerusalems: 11,4-9

4 David zog mit ganz Israel nach Jerusalem, das ist Jebus. Dort saßen
noch die Jebusiter, die damals im Land wohnten. [fn:4]

<<v5>>
5 Die Jebusiter aber sagten zu David: Du wirst nicht in die Stadt
hereinkommen. Doch David eroberte die Burg Zion; sie wurde die Stadt
Davids.

<<v6>>
6 Damals sagte David: Wer als erster die Jebusiter schlägt, soll
Hauptmann und Anführer werden. Da stieg Joab, der Sohn der Zeruja, als
Erster hinauf und wurde Hauptmann.

<<v7>>
7 David ließ sich in der Burg nieder und daher nannte man sie
Davidstadt.

<<v8>>
8 Er baute an der Stadt ringsum vom Millo an und im Umkreis, während
Joab die übrige Stadt wiederherstellte.

<<v9>>
9 David wurde immer mächtiger und der Herr der Heere war mit ihm.\\
\\

<<v10>>
* Davids Helden: 11,10-19

10 Das sind die Obersten der Helden Davids, die mit ganz Israel in der
Sache des Königtums fest zu ihm hielten, um ihn nach dem Wort des Herrn
zum König von Israel zu machen. [fn:5]

<<v11>>
11 Das ist das Verzeichnis der Helden Davids: Jaschobam, der Sohn
Hachmonis, war das Haupt der Drei; er schwang seine Lanze über
dreihundert Männer und erschlug sie alle auf einmal. [fn:6]

<<v12>>
12 Nach ihm kommt der Ahoachiter Eleasar, der Sohn Dodos.

<<v13>>
13 Er war bei David, als die Philister sich bei Pas-Dammim zum Kampf
sammelten. Dort war ein Gerstenfeld. Als das Volk vor den Philistern
floh, [fn:7]

<<v14>>
14 stellte er sich mitten in das Feld, behauptete es und schlug die
Philister. So verlieh ihm der Herr einen großen Sieg.

<<v15>>
15 Als sich einst das Lager der Philister in der Rafaïterebene befand,
kamen drei von den dreißig Helden zu David in das Felsennest, in die
Höhle Adullam.

<<v16>>
16 David hielt sich damals in seiner Bergfestung auf und ein Posten der
Philister lag in Betlehem.

<<v17>>
17 Da bekam David großen Durst und er sagte: Wer bringt mir Wasser aus
der Zisterne am Tor von Betlehem?

<<v18>>
18 Da drangen die drei Helden in das Lager der Philister ein, schöpften
Wasser aus der Zisterne am Tor von Betlehem, nahmen es mit und brachten
es David. Doch er wollte es nicht trinken, sondern goss es als
Trankopfer für den Herrn aus

<<v19>>
19 und sagte: Das sei fern von mir, Gott, dass ich so etwas tue. Soll
ich das Blut dieser Männer trinken, die unter Lebensgefahr hingegangen
sind? Denn unter Lebensgefahr haben sie es geholt. Darum wollte er es
nicht trinken. Eine solche Tat vollbrachten die drei Helden.\\
\\

<<v20>>
* Weitere Helden Davids: 11,20-47

20 Joabs Bruder Abischai war der Anführer der Dreißig. Er schwang seinen
Speer über dreihundert Männer und erschlug sie; er hatte bei den drei
Helden einen großen Namen. [fn:8] [fn:9]

<<v21>>
21 Unter den Dreißig war er hoch geehrt und er wurde ihr Anführer, aber
an die Drei reichte er nicht heran.

<<v22>>
22 Benaja aus Kabzeel, der Sohn Jojadas, war ein tapferer Mann, der
große Taten vollbrachte. Er erschlug die beiden Söhne Ariëls aus Moab.
Als einmal Schnee gefallen war, kam er zu einer Zisterne und erlegte
darin einen Löwen.

<<v23>>
23 Auch erschlug er einen riesenhaften Ägypter, der fünf Ellen groß war.
Der Ägypter hatte einen Speer gleich einem Weberbaum in der Hand. Benaja
aber ging nur mit einem Stock auf ihn los, riss ihm den Speer aus der
Hand und tötete ihn mit diesem Speer.

<<v24>>
24 Solche Taten vollbrachte Benaja, der Sohn Jojadas. Er hatte bei den
drei Helden einen großen Namen.

<<v25>>
25 Unter den Dreißig war er hoch geehrt, aber an die Drei reichte er
nicht heran. David stellte ihn an die Spitze seiner Leibwache.

<<v26>>
26 Tapfere Helden waren Joabs Bruder Asaël, Elhanan aus Betlehem, der
Sohn Dodos, [fn:10]

<<v27>>
27 Schammot aus Harod, Helez aus Bet-Pelet,

<<v28>>
28 Ira aus Tekoa, der Sohn des Ikkesch, Abiëser aus Anatot,

<<v29>>
29 Sibbechai aus Huscha, Ilai der Ahoachiter,

<<v30>>
30 Mahrai aus Netofa, Heled aus Netofa, der Sohn Baanas,

<<v31>>
31 Ittai aus Gibea in Benjamin, der Sohn Ribais, Benaja aus Piraton,

<<v32>>
32 Hiddai aus Nahale-Gaasch, Abiël aus Bet-Araba,

<<v33>>
33 Asmawet aus Bahurim, Eljachba aus Schaalbim,

<<v34>>
34 Jaschen der Guniter, Jonatan aus Harar, der Sohn Schages,

<<v35>>
35 Ahiam aus Harar, der Sohn Sachars, Elifal, der Sohn Urs,

<<v36>>
36 Hefer aus Mechera, Ahija aus Gilo,

<<v37>>
37 Hezro aus Karmel, Naarai, der Sohn Esbais,

<<v38>>
38 Joël, der Bruder Natans, Mibhar, der Sohn Hagris,

<<v39>>
39 Zelek, der Ammoniter, Nachrai aus Beerot, der Waffenträger Joabs, des
Sohnes der Zeruja,

<<v40>>
40 Ira aus Jattir, Gareb aus Jattir,

<<v41>>
41 Urija, der Hetiter, Sabad, der Sohn Achlais,

<<v42>>
42 Adina, der Sohn Schisas, aus dem Stamm Ruben, Haupt der Rubeniter und
Anführer von dreißig Mann,

<<v43>>
43 Hanan, der Sohn Maachas, Joschafat aus Meten,

<<v44>>
44 Usija aus Aschtarot, Schama und Jëiël, die Söhne Hotams, aus Aroër,

<<v45>>
45 Jediaël, der Sohn Schimris, und sein Bruder Joha aus Tiz,

<<v46>>
46 Eliël aus Mahanajim, Jeribai und Joschawja, die Söhne Elnaams, Jitma,
der Moabiter,

<<v47>>
47 Eliël, Obed und Jaasiël aus Zoba.\\
\\

* Footnotes

[fn:1] (1-3) [[file:2.Sam_5.org::v1][2 Sam 5,1-3]]

[fn:2] dein Fleisch und Bein: vgl. die Anmerkung zu [[file:Gen_2.org::v21][Gen 2,21-23]].

[fn:3] [[file:1.Sam_16.org::v1][1 Sam 16]]

[fn:4] (4-9) [[file:2.Sam_5.org::v6][2 Sam 5,6-10]]

[fn:5] (10-19) [[file:2.Sam_23.org::v8][2 Sam 23,8-17]]

[fn:6] Jaschobam ist wohl absichtliche Entstellung des Namens
Jischbaal (vgl. [[file:2.Sam_23.org::v8][2 Sam 23,8]]). - drei: H: dreißig. Es gab einen
Heldenkreis mit drei und einen größeren mit dreißig Männern.

[fn:7] In H sind einige Sätze verloren gegangen, sodass der
Name des dritten Helden, Schamma, wegfiel und seine Leistungen auf den
zweiten übertragen wurden. [[file:2.Sam_23.org::v9][2 Sam 23,9-12]] ist der volle Wortlaut noch
erhalten. Gerste: in [[file:2.Sam_23.org::v11][2 Sam 23,11]]: Linsen.

[fn:8] (20-47) [[file:2.Sam_23.org::v18][2 Sam 23,18-39]]

[fn:9] 20f: dreißig: in H zu «drei» verschrieben.

[fn:10] 26-47: Die Namen sind teilweise durch Schreibfehler
entstellt. Die Korrekturen stützen sich zumeist auf 2 Sam und G.
In [[file:2.Sam_1.org][2 Sam]] schließt die Liste mit Urija; Chr fügt sechzehn weitere Namen hinzu.
