#+TITLE: 1 Chr 27 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-21 Di 22:01]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 27.html

<<verses>>

<<v1>>
* Die Heerführer Davids: 27,1-15

1 Die Israeliten nach ihrer Anzahl, die Familienhäupter, die Obersten
der Tausend- und Hundertschaften und ihre Beamten dienten dem König in
allen Angelegenheiten der Abteilungen, die Monat für Monat das ganze
Jahr hindurch antraten und abzogen. Jede Abteilung war 24000 Mann stark.

<<v2>>
2 Die erste Abteilung für den ersten Monat befehligte Jaschobam, der
Sohn Sabdiëls. Zu seiner Abteilung gehörten 24000 Mann. [fn:1]

<<v3>>
3 Er war ein Nachkomme des Perez und Haupt aller Obersten des Heeres im
ersten Monat.

<<v4>>
4 Die Abteilung des zweiten Monats befehligte der Ahoachiter Dodai, ein
Fürst. Zu seiner Abteilung gehörten 24000 Mann. [fn:2] [fn:3]

<<v5>>
5 Der dritte Heerführer, für den dritten Monat, war Benaja, der Sohn des
Priesters Jojada, ein Oberhaupt. Zu seiner Abteilung gehörten 24000
Mann. [fn:4]

<<v6>>
6 Dieser Benaja war ein Held unter den Dreißig und Anführer der Dreißig
sowie seiner eigenen Abteilung. Sein Sohn war Ammisabad.

<<v7>>
7 Der vierte Befehlshaber, für den vierten Monat, war Asaël, der Bruder
Joabs. Nach ihm war es sein Sohn Sebadja. Zu seiner Abteilung gehörten
24000 Mann.

<<v8>>
8 Der fünfte, für den fünften Monat, war der Oberst Schamhut, ein
Nachkomme Serachs. Zu seiner Abteilung gehörten 24000 Mann.

<<v9>>
9 Der sechste, für den sechsten Monat, war Ira, der Sohn des Ikkesch,
aus Tekoa. Zu seiner Abteilung gehörten 24000 Mann.

<<v10>>
10 Der siebte, für den siebten Monat, war Helez aus Pelet, ein
Efraimiter. Zu seiner Abteilung gehörten 24000 Mann.

<<v11>>
11 Der achte, für den achten Monat, war der Huschatiter Sibbechai, ein
Nachkomme Serachs. Zu seiner Abteilung gehörten 24000 Mann.

<<v12>>
12 Der neunte, für den neunten Monat, war Abiëser aus Anatot vom Stamm
Benjamin. Zu seiner Abteilung gehörten 24000 Mann.

<<v13>>
13 Der zehnte, für den zehnten Monat, war Mahrai aus Netofa, ein
Nachkomme Serachs. Zu seiner Abteilung gehörten 24000 Mann.

<<v14>>
14 Der elfte, für den elften Monat, war Benaja aus Piraton, ein
Efraimiter. Zu seiner Abteilung gehörten 24000 Mann.

<<v15>>
15 Der zwölfte, für den zwölften Monat, war Heldai aus Netofa vom
Geschlecht Otniël. Zu seiner Abteilung gehörten 24000 Mann.\\
\\

<<v16>>
* Die Oberhäupter der Stämme: 27,16-24

16 Diese standen an der Spitze der Stämme Israels: Fürst bei den
Rubenitern war Eliëser, der Sohn Sichris; bei Simeon war es Schefatja,
der Sohn Maachas;

<<v17>>
17 bei Levi Haschabja, der Sohn Kemuëls; bei Aaron Zadok;

<<v18>>
18 bei Juda Elihu, ein Bruder Davids; bei Issachar Omri, der Sohn
Michaels;

<<v19>>
19 bei Sebulon Jischmaja, der Sohn Obadjas; bei Naftali Jerimot, der
Sohn Asriëls;

<<v20>>
20 bei den Efraimitern Hoschea, der Sohn Asasjas; bei der einen Hälfte
des Stammes Manasse Joël, der Sohn Pedajas;

<<v21>>
21 bei der anderen Hälfte des Stammes Manasse in Gilead war es Jiddo,
der Sohn Secharjas; bei Benjamin Jaasiël, der Sohn Abners;

<<v22>>
22 bei Dan Asarel, der Sohn Jerohams. Das waren die Anführer der Stämme
Israels.

<<v23>>
23 Die Zahl derer, die noch nicht zwanzig Jahre alt waren, hatte David
nicht aufnehmen lassen; denn der Herr hatte versprochen, dass er Israel
zahlreich werden lasse wie die Sterne des Himmels. [fn:5]

<<v24>>
24 Joab, der Sohn der Zeruja, hatte die Zählung begonnen, aber nicht zu
Ende geführt, da ihretwegen ein Zorngericht über Israel gekommen war. So
wurde ihre Zahl nicht in die Chronik des Königs David aufgenommen. [fn:6]\\
\\

<<v25>>
* Die Verwalter des königlichen Besitzes: 27,25-31

25 Asmawet, der Sohn Adiëls, hatte die Aufsicht über die Schätze des
Königs, Jonatan, der Sohn Usijas, über die Vorräte auf dem Land, in den
Städten, Dörfern und Türmen,

<<v26>>
26 Esri, der Sohn Kelubs, über die Feldarbeiter, die den Boden zu
bestellen hatten,

<<v27>>
27 Schimi aus Rama über die Weinberge, Sabdi aus Schefam über die
Weinvorräte in den Weinbergen,

<<v28>>
28 Baal-Hanan aus Bet-Gader über die Öl- und Maulbeerfeigenbäume in der
Schefela, Joasch über die Ölvorräte,

<<v29>>
29 Schitrai, der Scharoniter, über die Rinder, die in der Scharonebene
weideten, Schafat, der Sohn Adlais, über die Rinder in den Tälern,

<<v30>>
30 der Ismaeliter Obil über die Kamele, Jechdeja aus Meronot über die
Esel,

<<v31>>
31 der Hagariter Jasis über die Schafe und Ziegen. Sie alle waren
Verwalter des Eigentums, das dem König David gehörte.\\
\\

<<v32>>
* Die höchsten Beamten: 27,32-34

32 Jonatan, der Onkel Davids, war sein Berater. Er war ein kluger,
schriftkundiger Mann. Jehiël, der Sohn Hachmonis, war bei den Söhnen des
Königs.

<<v33>>
33 Ahitofel war Berater des Königs, der Arkiter Huschai war Freund des
Königs. [fn:7] [fn:8]

<<v34>>
34 Nach Ahitofel war Jojada, der Sohn Benajas (Berater des Königs).
Abjatar war Priester und Joab Heerführer des Königs. [fn:9]\\
\\

* Footnotes

[fn:1] 2-15: Die Namen der zwölf Befehlshaber sind in der Liste
der Helden Davids enthalten (vgl. [[file:1.Chr_11.org::v11][11,11-40]]).

[fn:2] [[file:1.Chr_11.org::v12][11,12]]; [[file:2.Sam_23.org::v9][2 Sam 23,9]]

[fn:3] In H folgen auf den Namen Varianten des Wortes für «Abteilung».

[fn:4] [[file:1.Chr_11.org::v22][11,22-25]]

[fn:5] [[file:1.Chr_21.org::v1][21,1-6]]

[fn:6] [[file:1.Chr_21.org::v1][21,1]]-[[file:1.Chr_21.org::v15][15]]; [[file:2.Sam_24.org::v1][2 Sam 24,1]]-[[file:2.Sam_24.org::v15][15]]

[fn:7] [[file:2.Sam_16.org::v23][2 Sam 16,23]]

[fn:8] Freund des Königs: eine Amtsbezeichnung (vgl. [[file:1.Kön_4.org::v5][1 Kön 4,5]]).

[fn:9] war Priester: sinngemäß ergänzt.
