#+TITLE: 1 Chr 6 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 22:06]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Chr 6.html

<<verses>>

<<v1>>
* Die Nachkommen der drei Söhne Levis: 6,1-15

1 Die Söhne Levis waren: Gerschon, Kehat und Merari.

<<v2>>
2 Die Söhne Gerschons hießen Libni und Schimi.

<<v3>>
3 Kehats Söhne waren: Amram, Jizhar, Hebron und Usiël.

<<v4>>
4 Die Söhne Meraris waren: Machli und Muschi. Das sind die Sippen der
Leviten nach ihren Stammvätern:

<<v5>>
5 Der Sohn Gerschons war Libni, dessen Sohn Jahat, dessen Sohn Simma,

<<v6>>
6 dessen Sohn Joach, dessen Sohn Iddo, dessen Sohn Serach und dessen
Sohn Etni.

<<v7>>
7 Der Sohn Kehats war Amminadab, dessen Sohn Korach, dessen Sohn Assir,

<<v8>>
8 dessen Sohn Elkana, dessen Sohn Abiasaf, dessen Sohn Assir,

<<v9>>
9 dessen Sohn Tahat, dessen Sohn Uriël, dessen Sohn Usija und dessen
Sohn Schaul.

<<v10>>
10 Die Söhne Elkanas waren Amasai und Ahimot.

<<v11>>
11 Der Sohn Elkanas war Elkana, dessen Sohn Zuf, dessen Sohn Tohu, [fn:1]

<<v12>>
12 dessen Sohn Eliab, dessen Sohn Jeroham, dessen Sohn Elkana, dessen
Sohn Samuel.

<<v13>>
13 Die Söhne Samuels waren: Joël, der Erstgeborene, und der zweite war
Abija. [fn:2] [fn:3]

<<v14>>
14 Der Sohn Meraris war Machli, dessen Sohn Libni, dessen Sohn Schimi,
dessen Sohn Usa,

<<v15>>
15 dessen Sohn Schima, dessen Sohn Haggija und dessen Sohn Asaja.\\
\\

<<v16>>
* Abstammung der Sänger: 6,16-32
     :PROPERTIES:
     :CUSTOM_ID: abstammung-der-sänger-616-32
     :END:
16 Diese sind es, die David zur Pflege des Gesangs im Haus des Herrn
bestellte, nachdem die Lade eine bleibende Stätte gefunden hatte. [fn:4]

<<v17>>
17 Sie versahen ihren Dienst als Sänger vor der Wohnstätte des
Offenbarungszeltes, bis Salomo das Haus des Herrn in Jerusalem baute.
Gemäß ihren Satzungen standen sie in ihrem Dienst. [fn:5]

<<v18>>
18 Diese sind es, die mit ihren Söhnen den Dienst besorgten: Von den
Nachkommen der Kehatiter: Heman, der Sänger, der Sohn Joëls, des Sohnes
Samuels,

<<v19>>
19 des Sohnes Elkanas, des Sohnes Jerohams, des Sohnes Eliëls, des
Sohnes Tohus, [fn:6]

<<v20>>
20 des Sohnes Zufs, des Sohnes Elkanas, des Sohnes Mahats, des Sohnes
Amasais,

<<v21>>
21 des Sohnes Elkanas, des Sohnes Joëls, des Sohnes Asarjas, des Sohnes
Zefanjas,

<<v22>>
22 des Sohnes Tahats, des Sohnes Assirs, des Sohnes Abiasafs, des Sohnes
Korachs,

<<v23>>
23 des Sohnes Jizhars, des Sohnes Kehats, des Sohnes Levis, des Sohnes
Israels.

<<v24>>
24 Sein Bruder war Asaf, der zu seiner Rechten stand: Er war der Sohn
Berechjas, des Sohnes Schimas,

<<v25>>
25 des Sohnes Michaels, des Sohnes Maasejas, des Sohnes Malkijas,

<<v26>>
26 des Sohnes Etnis, des Sohnes Serachs, des Sohnes Adajas,

<<v27>>
27 des Sohnes Etans, des Sohnes Simmas, des Sohnes Schimis,

<<v28>>
28 des Sohnes Jahats, des Sohnes Gerschoms, des Sohnes Levis.

<<v29>>
29 Die Söhne Meraris, ihre Brüder, standen zur Linken: Etan, der Sohn
Kischis, des Sohnes Abdis, des Sohnes Malluchs,

<<v30>>
30 des Sohnes Haschabjas, des Sohnes Amazjas, des Sohnes Hilkijas,

<<v31>>
31 des Sohnes Amzis, des Sohnes Banis, des Sohnes Schemers,

<<v32>>
32 des Sohnes Machlis, des Sohnes Muschis, des Sohnes Meraris, des
Sohnes Levis.\\
\\

<<v33>>
* Die Aufgaben der Leviten und Priester: 6,33-34

33 Ihre Brüder, die Leviten, waren für den gesamten Dienst an der
Wohnstätte des Hauses Gottes bestimmt.

<<v34>>
34 Aaron aber und seine Söhne verbrannten die Opfer auf dem
Brandopferaltar und dem Rauchopferaltar. Sie besorgten jeden Dienst am
Allerheiligsten und vollzogen die Sühne für Israel, genau wie Mose, der
Knecht Gottes, angeordnet hatte.\\
\\

<<v35>>
* Die Nachkommen Aarons: 6,35-38

35 Das sind die Nachkommen Aarons: Sein Sohn war Eleasar, dessen Sohn
Pinhas, dessen Sohn Abischua, [fn:7]

<<v36>>
36 dessen Sohn Bukki, dessen Sohn Usi, dessen Sohn Serachja,

<<v37>>
37 dessen Sohn Merajot, dessen Sohn Amarja, dessen Sohn Ahitub,

<<v38>>
38 dessen Sohn Zadok, dessen Sohn Ahimaaz.\\
\\

<<v39>>
* Die Wohnsitze der Leviten: 6,39-66

39 Das sind ihre Wohnsitze mit ihren Zeltlagern auf ihrem Gebiet: Den
Nachkommen Aarons von der Sippe der Kehatiter, auf die das erste Los
gefallen war, [fn:8] [fn:9]

<<v40>>
40 gaben sie Hebron im Land Juda mit seinen Weideflächen ringsum.

<<v41>>
41 Das Ackerland der Stadt aber und ihre Gehöfte gaben sie Kaleb, dem
Sohn Jefunnes.

<<v42>>
42 Sie gaben den Nachkommen Aarons die Asylstadt Hebron, ferner Libna
mit seinen Weideflächen, Jattir und Eschtemoa mit seinen Weideflächen, [fn:10]

<<v43>>
43 Holon mit seinen Weideflächen, Debir mit seinen Weideflächen,

<<v44>>
44 Aschan mit seinen Weideflächen, (Jutta mit seinen Weideflächen,)
Bet-Schemesch mit seinen Weideflächen. [fn:11]

<<v45>>
45 Vom Stamm Benjamin gaben sie ihnen: (Gibeon mit seinen Weideflächen,)
Geba mit seinen Weideflächen, Alemet mit seinen Weideflächen, Anatot mit
seinen Weideflächen. Insgesamt gehörten ihnen dreizehn Städte mit ihren
Weideflächen.

<<v46>>
46 Den übrigen Sippen von den Nachkommen Kehats gaben sie durch das Los
zehn Städte vom halben Stamm Manasse.

<<v47>>
47 Den Nachkommen Gerschoms gaben die Israeliten entsprechend ihren
Sippen aus dem Stamm Issachar, aus dem Stamm Ascher, aus dem Stamm
Naftali und aus dem Stamm Manasse im Baschan dreizehn Städte.

<<v48>>
48 Den Nachkommen Meraris gaben sie entsprechend ihren Sippen aus dem
Stamm Ruben, aus dem Stamm Gad und aus dem Stamm Sebulon durch das Los
zwölf Städte.

<<v49>>
49 Die Israeliten gaben den Leviten die Städte samt ihren Weideflächen.

<<v50>>
50 Durch das Los gaben sie ihnen aus dem Stamm Juda, aus dem Stamm
Simeon und aus dem Stamm Benjamin diese Städte, die sie namentlich
bezeichneten.

<<v51>>
51 Die Angehörigen der kehatitischen Sippen erhielten durch das Los vom
Stamm Efraim folgende Städte:

<<v52>>
52 Man gab ihnen die Asylstadt Sichem mit ihren Weideflächen auf dem
Gebirge Efraim, ferner Geser mit seinen Weideflächen,

<<v53>>
53 Kibzajim mit seinen Weideflächen, Bet-Horon mit seinen Weideflächen;

<<v54>>
54 (vom Stamm Dan: Elteke mit seinen Weideflächen, Gibbeton mit seinen
Weideflächen,) Ajalon mit seinen Weideflächen, Gat-Rimmon mit seinen
Weideflächen;

<<v55>>
55 vom halben Stamm Manasse: Taanach mit seinen Weideflächen und Jibleam
mit seinen Weideflächen. Diese gaben sie den Sippen der übrigen
Kehatiter. [fn:12]

<<v56>>
56 Den Nachkommen Gerschoms gaben sie von den Sippen des halben Stamms
Manasse: Golan im Baschan mit seinen Weideflächen, Aschtarot mit seinen
Weideflächen;

<<v57>>
57 vom Stamm Issachar: Kischjon mit seinen Weideflächen, Daberat mit
seinen Weideflächen,

<<v58>>
58 Ramot mit seinen Weideflächen, En-Gannim mit seinen Weideflächen;

<<v59>>
59 vom Stamm Ascher: Mischal mit seinen Weideflächen, Abdon mit seinen
Weideflächen,

<<v60>>
60 Helkat mit seinen Weideflächen, Rehob mit seinen Weideflächen;

<<v61>>
61 vom Stamm Naftali: Kedesch in Galiläa mit seinen Weideflächen, Hammon
mit seinen Weideflächen, Kirjatajim mit seinen Weideflächen.

<<v62>>
62 Den übrigen Nachkommen Meraris gaben sie vom Stamm Sebulon: (Jokneam
mit seinen Weideflächen, Karta mit seinen Weideflächen,) Rimmon mit
seinen Weideflächen, Tabor mit seinen Weideflächen; [fn:13]

<<v63>>
63 im Land jenseits des Jordan bei Jericho, östlich des Jordan, vom
Stamm Ruben: Bezer in der Steppe mit seinen Weideflächen, Jahaz mit
seinen Weideflächen,

<<v64>>
64 Kedemot mit seinen Weideflächen, Mefaat mit seinen Weideflächen;

<<v65>>
65 vom Stamm Gad: Ramot in Gilead mit seinen Weideflächen, Mahanajim mit
seinen Weideflächen,

<<v66>>
66 Heschbon mit seinen Weideflächen und Jaser mit seinen Weideflächen.\\
\\

* Footnotes
:PROPERTIES:
:ID:       7eb8e9a6-fc0e-4243-87fe-7073bdba5963
:END:

[fn:1] [[file:1.Sam_1.org::v1][1 Sam 1,1]]

[fn:2] [[file:1.Sam_8.org::v2][1 Sam 8,2]]

[fn:3] Text korr. nach 1 Sam 8,2.

[fn:4] David ließ die Lade nach Jerusalem bringen und in einem
Zelt aufstellen. Unter Salomo erhielt sie im Tempel ihre bleibende
Stätte.

[fn:5] Nach [[file:1.Chr_21.org::v29][1 Chr 21,29]] und [[file:2.Chr_1.org::v3][2 Chr 1,3]] befand sich das heilige
Zelt (ohne die Bundeslade) zur Zeit Davids in Gibeon; dort wurden auch
die Opfer unter Leitung des Priesters Zadok dargebracht (vgl. 1 Chr
16,39). Der Kult hörte dort auf, als Salomo das Zelt nach Jerusalem
bringen ließ.

[fn:6] [[file:1.Sam_1.org::v1][1 Sam 1,1]]

[fn:7] (35-38) [[file:1.Chr_5.org::v29][5,29-34]]

[fn:8] (39-66) [[file:Jos_21.org::v3][Jos 21,3-39]]

[fn:9] 39-66: Einige Ortsnamen fehlen in H und wurden aus Jos
21 ergänzt.

[fn:10] Eine Asylstadt ist ein Ort, wohin ein Totschläger
fliehen konnte, um vor dem Bluträcher sicher zu sein (vgl. [[file:Dtn_19.org::v1][Dtn 19,1-13]]).

[fn:11] 44f.54: Ergänzt aus [[file:Jos_21.org::v16][Jos 21,16f]].[[file:Jos_21.org::v23][23]].

[fn:12] Die «übrigen» Kehatiter sind jene, die nicht
Nachkommen Aarons sind (vgl. [[v39][6,39-45]]).

[fn:13] Ergänzt nach [[file:Jos_21.org::v34][Jos 21,34]].
