#+TITLE: 1 Chr 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-21 Di 16:19]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 21.html

<<verses>>

<<v1>>
* Davids Volkszählung: 21,1-17

1 Der Satan trat gegen Israel auf und reizte David, Israel zu zählen. [fn:1] [fn:2]

<<v2>>
2 David befahl Joab und den Anführern des Volkes: Geht, zählt Israel von
Beerscheba bis Dan und bringt mir Bescheid, damit ich weiß, wie viele es
sind.

<<v3>>
3 Joab aber sagte zum König: Der Herr möge sein Volk vermehren,
hundertmal mehr, als es jetzt ist. Sind denn nicht alle, mein Herr und
König, Untertanen meines Herrn? Warum hat mein Herr diesen Wunsch? Warum
soll Israel in Schuld geraten?

<<v4>>
4 Doch der König beharrte gegenüber Joab auf seinem Befehl. So ging Joab
weg und durchzog ganz Israel. Als er nach Jerusalem zurückkam,

<<v5>>
5 gab er David das Ergebnis der Volkszählung bekannt. Ganz Israel zählte
1100000 Krieger, die mit dem Schwert kämpfen konnten, und Juda zählte
470000 Mann, die mit dem Schwert kämpfen konnten. [fn:3]

<<v6>>
6 Levi und Benjamin hatte Joab nicht zusammen mit ihnen gezählt, denn
der Befehl des Königs war ihm ein Gräuel.

<<v7>>
7 Doch das missfiel Gott; darum schlug er Israel.

<<v8>>
8 Nun sagte David zu Gott: Ich habe schwer gesündigt, weil ich das getan
habe. Doch vergib deinem Knecht seine Schuld, denn ich habe sehr
unvernünftig gehandelt.

<<v9>>
9 Der Herr aber sprach zu Gad, dem Seher Davids:

<<v10>>
10 Geh und sag zu David: So spricht der Herr: Dreierlei lege ich dir
vor. Wähl dir eines davon! Das werde ich dir antun.

<<v11>>
11 Gad kam zu David und sagte zu ihm: So spricht der Herr: Wähle dir:

<<v12>>
12 drei Jahre Hungersnot, oder drei Monate, in denen du vor deinen
Feinden fliehen musst und das Schwert deiner Gegner dich verfolgt, oder
drei Tage, in denen das Schwert des Herrn, die Pest, im Land wütet und
der Engel des Herrn über alle Gebiete Israels Verderben bringt. Überleg
nun, was ich dem, der mich gesandt hat, als Antwort überbringen soll. [fn:4]

<<v13>>
13 Da sagte David zu Gad: Ich habe große Angst. Ich will lieber dem
Herrn in die Hände fallen, denn seine Barmherzigkeit ist groß. Den
Menschen aber möchte ich nicht in die Hände fallen. [fn:5]

<<v14>>
14 Da ließ der Herr über Israel eine Pest kommen und es kamen in Israel
siebzigtausend Menschen um.

<<v15>>
15 Gott sandte einen Engel nach Jerusalem, um es ins Verderben zu
stürzen. Doch als er mit der Vernichtung begann, sah es der Herr und das
Unheil reute ihn. Er sagte zu dem Engel des Verderbens: Es ist jetzt
genug, lass deine Hand sinken! Der Engel des Herrn stand gerade bei der
Tenne des Jebusiters Arauna.

<<v16>>
16 Als David aufblickte, sah er den Engel des Herrn zwischen Erde und
Himmel stehen. Er hielt das gezückte Schwert in der Hand gegen Jerusalem
gerichtet. Da fielen David und die Ältesten, die in Trauergewänder
gehüllt waren, auf ihr Angesicht nieder

<<v17>>
17 und David rief zu Gott: Habe nicht ich befohlen, das Volk zu zählen?
Ich bin es doch, der gesündigt und Böses getan hat. Aber diese, die
Herde, was haben denn sie getan? Herr, mein Gott, erheb deine Hand zum
Schlag gegen mich und gegen das Haus meines Vaters, nicht aber gegen
dein Volk!\\
\\

<<v18>>
* Die Bestimmung des Tempelplatzes: 21,18-30

18 Der Engel des Herrn befahl Gad, zu David zu sagen, er solle
hinaufgehen und dem Herrn auf der Tenne des Jebusiters Arauna einen
Altar errichten. [fn:6]

<<v19>>
19 David ging hinauf, wie ihm Gad im Namen des Herrn befohlen hatte.

<<v20>>
20 Arauna hatte sich umgewandt und den Engel erblickt. Seine vier Söhne,
die bei ihm waren, versteckten sich. Er drosch gerade Weizen.

<<v21>>
21 Als nun David zu Arauna kam und dieser aufschaute und David sah, kam
er aus der Tenne heraus und warf sich vor David mit dem Gesicht zur Erde
nieder.

<<v22>>
22 Da sagte David zu Arauna: Überlass mir den Platz der Tenne! Ich
möchte auf ihm einen Altar für den Herrn errichten. Um den vollen
Kaufpreis sollst du ihn mir geben, damit die Plage im Volk aufhört.

<<v23>>
23 Arauna antwortete David: Du magst ihn nehmen; mein Herr und König
tue, was er für gut findet. Ich gebe dir die Rinder für die Brandopfer,
die Dreschschlitten als Brennholz und den Weizen zum Speiseopfer; ich
will dir alles geben.

<<v24>>
24 Doch König David sagte zu Arauna: Nein, ich will dir den Platz zum
vollen Preis abkaufen. Ich will nicht dein Eigentum wegnehmen und dem
Herrn unbezahlte Brandopfer darbringen.

<<v25>>
25 So gab David dem Arauna für den Platz sechshundert abgewogene
Goldschekel. [fn:7]

<<v26>>
26 Er baute dort einen Altar für den Herrn, brachte Brand- und
Heilsopfer dar und rief den Herrn an. Dieser antwortete ihm durch Feuer,
das vom Himmel auf den Altar des Brandopfers niederfiel.

<<v27>>
27 Dem Engel aber gebot der Herr, das Schwert in die Scheide zu stecken.

<<v28>>
28 Damals merkte David, dass ihn der Herr auf der Tenne des Jebusiters
Arauna erhörte, und brachte dort Opfer dar.

<<v29>>
29 Die Wohnstätte des Herrn aber, die Mose in der Wüste angefertigt
hatte, und der Brandopferaltar waren zu jener Zeit auf der Kulthöhe von
Gibeon. [fn:8] [fn:9]

<<v30>>
30 Doch David konnte sich nicht mehr dorthin begeben, um Gott
aufzusuchen; denn ihn hatte vor dem Schwert des Engels des Herrn
Schrecken erfasst.\\
\\

* Footnotes

[fn:1] (1-17) [[file:2.Sam_24.org::v1][2 Sam 24,1-17]]

[fn:2] Zur Verwerflichkeit der Volkszählung vgl. die Anmerkung
zu [[file:2.Sam_24.org::v1][2 Sam 24,1]]. Während nach 2 Sam Gott selbst in David den Entschluss
zur Volkszählung weckte, wird dies in Chr dem Satan zugeschrieben, der
in [[file:Ijob_1.org::v1][Ijob 1]] - [[file:Ijob_2.org][2]] und in [[file:Sach_3.org::v1][Sach 3,1f]] als Widersacher und Gegenspieler Gottes
erscheint.

[fn:3] Nach dem Wortlaut ist die Zahl des Stammes Juda in den
1,1 Millionen enthalten. Die Zahlen in [[file:2.Sam_24.org::v9][2 Sam 24,9]] ergeben 1,3 Millionen.
Erfasst wurden nur die Wehrfähigen. Chr ergänzt, dass auch der Stamm
Benjamin, auf dessen Gebiet Jerusalem lag, und der Stamm Levi, der den
Kultdienst besorgte, in die Zählung nicht einbezogen waren.

[fn:4] fliehen musst: Text korr. nach G und [[file:2.Sam_24.org::v13][2 Sam 24,13]].

[fn:5] Davids Antwort schließt nur die zweite Möglichkeit aus.

[fn:6] (18-26) [[file:2.Sam_24.org::v18][2 Sam 24,18]]-[[file:2.Sam_24.org::v25][25]]

[fn:7] Nach [[file:2.Sam_24.org::v24][2 Sam 24,24]] betrug der Preis für das Grundstück
fünfzig Schekel Silber. Chr nennt eine zwölfmal höhere Zahl und spricht
von Goldschekeln. Dadurch wird angedeutet, dass der Platz für alle zwölf
Stämme erworben wurde und dass es sich um einen sehr kostbaren Bauplatz,
nämlich den Tempelplatz, handelt.

[fn:8] [[file:Ex_36.org::v8][Ex 36,8]]-[[file:Ex_36.org::v38][38]]; [[file:2.Chr_1.org::v3][2 Chr 1,3-5]]

[fn:9] In Gibeon wurden zwar noch die vorgeschriebenen Opfer
dargebracht und der kultische Dienst vollzogen ([[file:1.Chr_16.org::v39][16,39f]]); doch David
vermied es, daran teilzunehmen.
