#+TITLE: 1 Chr 13 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-20 Mo 10:50]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 13.html

<<verses>>

<<v1>>
* Die Überführung der Bundeslade nach Jerusalem: 13,1-14

1 David besprach sich mit den Obersten der Tausend- und Hundertschaften
und mit allen führenden Leuten. [fn:1]

<<v2>>
2 Dann sagte er zur ganzen Versammlung Israels: Wenn ihr einverstanden
seid und wenn es dem Herrn, unserem Gott, gefällt, schicken wir
überallhin Boten zu unseren Brüdern, die in allen Gegenden Israels
geblieben sind, sowie zu den Priestern und Leviten, die in ihren Städten
und auf ihren Weideflächen wohnen. Sie sollen sich bei uns versammeln

<<v3>>
3 und wir wollen die Lade unseres Gottes zu uns heraufholen; denn in den
Tagen Sauls haben wir uns nicht um sie gekümmert. [fn:2]

<<v4>>
4 Die ganze Versammlung stimmte dem Vorhaben zu, denn der Plan gefiel
dem ganzen Volk.

<<v5>>
5 David versammelte nun ganz Israel vom Schihor in Ägypten bis
Lebo-Hamat, um die Lade Gottes von Kirjat-Jearim heraufzuholen. [fn:3]

<<v6>>
6 Er zog mit ganz Israel nach Baala bei Kirjat-Jearim, das zu Juda
gehörte, um von dort die Lade Gottes heraufzuholen, über der der Name
des Herrn, der über den Kerubim thront, ausgerufen worden ist.

<<v7>>
7 Sie holten die Lade Gottes auf einem neuen Wagen vom Haus Abinadabs
ab; Usa und Achjo lenkten den Wagen.

<<v8>>
8 David und ganz Israel tanzten und sangen vor Gott mit ganzer Hingabe
und spielten auf Zithern, Harfen und Pauken, mit Zimbeln und Trompeten.

<<v9>>
9 Als sie zur Tenne Kidons kamen, brachen die Rinder aus und Usa
streckte seine Hand aus, um die Lade festzuhalten.

<<v10>>
10 Da entbrannte der Zorn des Herrn gegen Usa und er erschlug ihn, weil
er seine Hand nach der Lade ausgestreckt hatte, sodass er dort vor Gott
starb.

<<v11>>
11 David war sehr erregt darüber, dass der Herr den Usa so plötzlich
dahingerafft hatte, und man nennt den Ort bis heute darum Perez-Usa
(Wegraffung Usas).

<<v12>>
12 An jenem Tag bekam David Angst vor Gott, sodass er sagte: Wie soll
ich die Lade Gottes zu mir bringen?

<<v13>>
13 Er ließ sie darum nicht zu sich in die Davidstadt bringen, sondern
stellte sie in das Haus Obed-Edoms aus Gat.

<<v14>>
14 Drei Monate lang blieb die Lade Gottes im Haus Obed-Edoms und der
Herr segnete das Haus Obed-Edoms und alles, was ihm gehörte.\\
\\

* Footnotes

[fn:1] (1-14) [[file:2.Sam_6.org::v12][2 Sam 6,12-23]]

[fn:2] Die Lade war in der Zeit des Priesters Eli von den
Philistern erbeutet worden (vgl. [[file:1.Sam_4.org::v11][1 Sam 4,11]]). Sie befand sich nach ihrer
Rückgabe an Israel im Haus Abinadabs in Kirjat-Jearim (vgl. [[file:1.Sam_7.org::v1][1 Sam 7,1]]).

[fn:3] Gemeint ist die Ausdehnung des Landes vom östlichsten
Nilarm (Schihor) bis Lebo-Hamat an der syrischen Grenze.
