#+TITLE: 1 Chr 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 21:49]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 4.html

<<verses>>

<<v1>>
* Einzelne Familien des Stammes Juda:

1 Die Söhne Judas waren: Perez, Hezron, Kaleb, Hur und Schobal. [fn:1]

<<v2>>
2 Reaja, der Sohn Schobals, zeugte Jahat und Jahat zeugte Ahumai und
Lahad. Das waren die Sippen der Zoraïter.

<<v3>>
3 Und das waren die Söhne Etams: Jesreel, Jischma und Jidbasch. Der Name
ihrer Schwester war Hazlelponi.

<<v4>>
4 Penuel war der Vater Gedors und Eser der Vater Huschas. Das waren die
Nachkommen Hurs, des Erstgeborenen der Efrata, des Vaters von Betlehem.

<<v5>>
5 Aschhur, der Vater Tekoas, hatte zwei Frauen, Hela und Naara.

<<v6>>
6 Naara gebar ihm Ahusam, Hefer, Temni und Ahaschtari. Das waren die
Söhne der Naara.

<<v7>>
7 Die Söhne der Hela waren: Zeret, Zohar und Etnan.

<<v8>>
8 Koz zeugte Anub, Zobeba, ferner die Sippen Aharhels, des Sohnes
Harums.

<<v9>>
9 Jabez war angesehener als seine Brüder. Seine Mutter hatte ihn Jabez
genannt, denn sie sagte: Ich habe ihn unter Beschwerden geboren. [fn:2]

<<v10>>
10 Doch Jabez rief zum Gott Israels und sprach: Möchtest du mich segnen
und mein Gebiet erweitern. Möchte deine Hand mit mir sein, dass du mich
freimachst von Unheil und ich ohne Beschwerden bleibe. Und Gott erfüllte
seine Bitte.

<<v11>>
11 Kelub, der Bruder Schuhas, zeugte Mehir, den Vater Eschtons.

<<v12>>
12 Eschton zeugte Bet-Rafa, Paseach und Tehinna, den Vater von
Ir-Nahasch. Das sind die Männer von Recha.

<<v13>>
13 Die Söhne des Kenas waren Otniël und Seraja, die Söhne Otniëls Hatat
und Meonotai.

<<v14>>
14 Meonotai zeugte Ofra. Seraja zeugte Joab, den Vater von Ge-Haraschim
(Tal der Handwerker); denn sie waren Handwerker.

<<v15>>
15 Die Söhne Kalebs, des Sohnes Jefunnes, waren: Iru, Ela und Naam. Der
Sohn Elas war Kenas.

<<v16>>
16 Die Söhne Jehallelels waren: Sif, Sifa, Tirja und Asarel.

<<v17>>
17 Die Söhne Esras waren: Jeter, Mered, Efer und Jalon. (Bitja, die
ägyptische Frau Mereds,) gebar Mirjam, Schammai und Jischbach, den Vater
von Eschtemoa. [fn:3]

<<v18>>
18 Seine judäische Frau gebar: Jered, den Vater von Gedor, Heber, den
Vater von Socho, und Jekutiël, den Vater von Sanoach. Das waren die
Söhne der Bitja, der Tochter des Pharao, die Mered geheiratet hatte,

<<v19>>
19 und die Söhne seiner judäischen Frau, der Schwester Nahams, des
Vaters von Keïla, dem Garmiter, und von Eschtemoa, dem Maachatiter.

<<v20>>
20 Die Söhne Schimons waren: Amnon, Rinna, Ben-Hanan und Tilon. Die
Söhne Jischis waren Sohet und Ben-Sohet.

<<v21>>
21 Die Söhne Schelas, des Sohnes Judas, waren: Er, der Vater Lechas,
Lada, der Vater Mareschas, sowie die Sippen des Hauses der
Byssusbearbeiter von Bet-Aschbea,

<<v22>>
22 ferner Jokim und die Männer von Koseba, sowie Joasch und Saraf, die
Moab in Besitz genommen hatten, aber wieder nach Betlehem zurückgekehrt
waren - die Berichte sind altüberliefert.

<<v23>>
23 Sie sind die Töpfer und Einwohner von Netaïm und Gedera und wohnen
dort im Dienst des Königs.\\
\\

<<v24>>

* Der Stamm Simeon: 4,24-43

Die Söhne Simeons waren: Jemuël, Jamin, Jarib, Serach und Schaul. [fn:4]

<<v25>>
25 Dessen Sohn war Schallum, dessen Sohn Mibsam und dessen Sohn Mischma.

<<v26>>
26 Der Sohn Mischmas war Hammuël, dessen Sohn Sakkur und dessen Sohn
Schimi.

<<v27>>
27 Schimi hatte sechzehn Söhne und sechs Töchter. Doch seine Brüder
waren nicht kinderreich und alle ihre Sippen erreichten nicht die Zahl
der Söhne Judas.

<<v28>>
28 Sie wohnten in Beerscheba, Molada, Hazar-Schual, [fn:5]

<<v29>>
29 Baala, Ezem, Eltolad,

<<v30>>
30 Betuël, Horma, Ziklag,

<<v31>>
31 Bet-Markabot, Hazar-Susim, Bet-Biri und Schaarajim. Das waren ihre
Städte mit den dazugehörenden Gehöften, bis David König wurde,

<<v32>>
32 dazu noch Etam, Ajin, Rimmon, Tochen und Aschan, fünf Städte

<<v33>>
33 mit all ihren Gehöften im Umkreis dieser Städte bis nach Baal hin.
Das waren ihre Wohnsitze und sie hatten ihre eigenen Stammeslisten.

<<v34>>
34 Meschobab, Jamlech, Joscha, der Sohn Amazjas,

<<v35>>
35 Joël, Jehu, der Sohn Joschibjas, des Sohnes Serajas, des Sohnes
Asiëls,

<<v36>>
36 Eljoënai, Jaakoba, Jeschohaja, Asaja, Adiël, Jesimiël, Benaja,

<<v37>>
37 Sisa, der Sohn Schifis, des Sohnes Allons, des Sohnes Jedajas, des
Sohnes Schimris, des Sohnes Schemajas:

<<v38>>
38 Diese namentlich Genannten waren führende Männer in ihren
Sippenverbänden. Ihre Großfamilien hatten sich stark vermehrt.

<<v39>>
39 Daher zogen sie, um Weideplätze für ihre Schafe und Ziegen zu suchen,
zum Osten des Tals, wo der Weg nach Gedor abzweigt.

<<v40>>
40 Sie fanden fette und gute Weideplätze. Das Land war nach allen Seiten
hin ausgedehnt, ruhig und friedlich; denn die früheren Bewohner gehörten
zu den Hamiten.

<<v41>>
41 So kamen diese mit Namen Aufgezeichneten in den Tagen des Königs
Hiskija von Juda, zerstörten ihre Zelte und erschlugen die Mëuniter, die
sich dort fanden. Sie weihten sie für immer dem Untergang und ließen
sich an ihrer Stelle nieder; denn es gab dort Weideplätze für ihre
Schafe und Ziegen.

<<v42>>
42 Von den Nachkommen Simeons zogen fünfhundert Mann in das Gebirge
Seïr. Pelatja, Nearja, Refaja und Usiël, die Söhne Jischis, standen an
ihrer Spitze.

<<v43>>
43 Sie schlugen die Restbevölkerung, die von den Amalekitern noch
vorhanden war, und wohnen dort bis zum heutigen Tag.\\
\\

* Footnotes

[fn:1] Der jeweils folgende Name bezeichnet den Sohn des
vorhergehenden.

[fn:2] Jabez erinnert an das Wort ozeb (= Beschwerde).

[fn:3] Ergänzt aus V. 18.

[fn:4] [[file:Gen_46.org::v10][Gen 46,10]]; [[file:Num_26.org::v12][Num 26,12-14]]

[fn:5] [[file:Jos_19.org::v2][Jos 19,2-8]]
