#+TITLE: 1 Chr 28 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-21 Di 22:10]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Chr 28.html

<<verses>>

<<v1>>
* Der Auftrag zum Tempelbau: 28,1-21

1 David versammelte in Jerusalem alle führenden Männer Israels, die
Vorsteher der Stämme und der Abteilungen, die im Dienst des Königs
standen, die Obersten der Tausend- und der Hundertschaften, die
Verwalter des ganzen Eigentums und des Viehbesitzes des Königs und
seiner Söhne, dazu die Hofbeamten, die Helden und alle tapferen Krieger. [fn:1]

<<v2>>
2 Dabei erhob sich König David und sagte: Hört mich an, meine Brüder und
mein Volk! Ich selbst hatte vor, für die Bundeslade des Herrn, den
Fußschemel unseres Gottes, eine Ruhestätte zu errichten, und traf
Vorbereitungen für den Bau. [fn:2]

<<v3>>
3 Doch Gott sprach zu mir: Du sollst meinem Namen kein Haus bauen; denn
du hast Kriege geführt und Blut vergossen. [fn:3]

<<v4>>
4 Der Herr, der Gott Israels, hat mich aus dem ganzen Haus meines Vaters
für immer zum König von Israel auserwählt. Er hat Juda zur Herrschaft
bestimmt und im Haus Juda das Haus meines Vaters. Unter den Söhnen
meines Vaters hat er an mir Gefallen gefunden, sodass er mich zum König
über Israel machte.

<<v5>>
5 Unter allen meinen Söhnen aber - der Herr hat mir ja viele Söhne
geschenkt - hat er meinen Sohn Salomo erwählt, dass er auf dem
Königsthron des Herrn über Israel herrscht. [fn:4]

<<v6>>
6 Er sprach zu mir: Dein Sohn Salomo soll mein Haus und meine Höfe
bauen; denn ihn habe ich mir zum Sohn erwählt und ich werde ihm Vater
sein.

<<v7>>
7 Ich will seinem Königtum ewigen Bestand verleihen, wenn er mannhaft
meine Gebote und Anordnungen befolgt, wie es heute der Fall ist.

<<v8>>
8 Und nun ermahne ich euch vor den Augen ganz Israels, der Versammlung
des Herrn, und vor den Ohren unseres Gottes: Achtet auf alle Gebote des
Herrn, eures Gottes, und befolgt sie, damit ihr im Besitz des prächtigen
Landes bleibt und es für immer auf eure Söhne nach euch vererben könnt.

<<v9>>
9 Du aber, mein Sohn Salomo, erkenne den Gott deines Vaters; diene ihm
mit ungeteiltem Herzen und williger Seele; denn der Herr erforscht alle
Herzen und kennt jedes Sinnen der Gedanken. Wenn du ihn suchst, lässt er
sich von dir finden. Wenn du ihn aber verlässt, verwirft er dich auf
ewig.

<<v10>>
10 Sieh nun zu: Der Herr hat dich erwählt, dass du ihm ein Haus als
Heiligtum erbaust. Sei mutig und geh ans Werk!

<<v11>>
11 Darauf übergab David seinem Sohn Salomo den Plan der Vorhalle, des
Hauptraums mit seinen Schatzkammern, Obergemächern und Innenräumen und
des Raums der Deckplatte [fn:5]

<<v12>>
12 sowie den Plan von allem, was er sich für die Höfe des Tempels und
für alle Kammern ringsum vorgenommen hatte. Er gab Anweisungen über die
Schätze des Gotteshauses und die Schätze aus den Weihegaben,

<<v13>>
13 über die Abteilungen der Priester und Leviten, über den Vollzug des
gesamten Dienstes am Haus des Herrn und über alle Geräte, die man zum
Dienst im Haus des Herrn benötigte.

<<v14>>
14 Dazu übergab er ihm seine Berechnungen über das Gold, mit Angabe des
Gewichtes des Goldes für jedes einzelne Dienstgerät, und über alle
silbernen Geräte, mit Angabe des Gewichtes eines jeden Dienstgerätes.

<<v15>>
15 Er nannte ihm das Gewicht der goldenen Leuchter mit ihren goldenen
Lampen, mit Angabe des Gewichtes eines jeden Leuchters und seiner
Lampen, sowie der silbernen Leuchter, mit Angabe des Gewichtes eines
jeden Leuchters und seiner Lampen, entsprechend der Verwendung eines
jeden Leuchters. [fn:6]

<<v16>>
16 Er bestimmte das Gold mit Angabe des Gewichtes für die einzelnen
Schaubrotetische und des Silbers für die silbernen Tische.

<<v17>>
17 Ebenso gab er ihm Auskunft über die Gabeln, Schalen und Kannen aus
purem Gold, über die goldenen Becher, mit Angabe des Gewichtes eines
jeden Bechers, auch über die silbernen Becher, mit Angabe des Gewichtes
eines jeden Bechers.

<<v18>>
18 Er verordnete geläutertes Gold für den Räucheraltar, mit Angabe des
Gewichtes, und Gold für den Aufbau des Thronwagens, die Kerubim, die
ihre Flügel ausbreiteten und die Bundeslade des Herrn bedeckten. [fn:7]

<<v19>>
19 All das legte er dar in einer Schrift aus der Hand des Herrn, die
über ihm ruhte, und erörterte alle Arbeiten, die der Plan vorsah. [fn:8]

<<v20>>
20 Dann sagte David zu seinem Sohn Salomo: Sei mutig und stark! Geh ans
Werk! Fürchte dich nicht und verzage nicht! Denn der Herr, mein Gott,
wird mit dir sein. Er wird dich nicht erlahmen lassen und dich nicht im
Stich lassen, bis alle Arbeiten für den Dienst des Hauses des Herrn zu
Ende geführt sind.

<<v21>>
21 Sieh, die Abteilungen der Priester und Leviten stehen da, zu jeder
Dienstleistung im Haus Gottes bereit. Bei jeder Arbeit und zu jedem
Dienst werden dir alle willig nach ihren Fähigkeiten beistehen; ebenso
werden dir die führenden Männer und das ganze Volk in jeder
Angelegenheit zur Seite stehen.\\
\\

* Footnotes

[fn:1] Unter den Helden sind die in [[file:1.Chr_11.org::v11][11,11]]-[[file:1.Chr_11.org::v47][47]] genannten Männer zu verstehen.

[fn:2] [[file:2.Sam_7.org::v2][2 Sam 7,2]]-[[file:2.Sam_7.org::v17][17]]

[fn:3] [[file:1.Chr_22.org::v8][22,8]]

[fn:4] Da Gott der eigentliche König Israels und der König sein
Stellvertreter ist, ist der Thron des irdischen Königs in Wirklichkeit
der Thron Gottes.

[fn:5] Raum der Deckplatte: Der Chronist nennt so das
Allerheiligste, weil für ihn die Deckplatte über der Bundeslade der
wichtigste Kultgegenstand ist. An ihr vollzieht nach [[file:Lev_16.org::v13][Lev 16,13f]] der
Hohepriester den Sühneritus für die Gemeinde am Versöhnungstag.

[fn:6] 15f: Der Text beschreibt Einrichtungen zur Zeit des
Chronisten. [[file:1.Kön_7.org::v48][1 Kön 7,48]] erwähnt nur einen Schaubrotetisch.

[fn:7] Thronwagen: Bezeichnung der Bundeslade, im Anschluss an
[[file:Ez_1.org][Ez 1]], wo Gott, wie sonst auf der Bundeslade, auf Kerubim thront und die
Kerubim auf einem Wagen mit vier Rädern stehen.

[fn:8] über ihm: Text korr. nach G.
