#+TITLE: 1 Kön 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-12 So 20:54]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Kön 9.html

<<verses>>

<<v1>>
* Die Verheißung für den Tempel: 9,1-9

1 Nachdem Salomo den Bau des Tempels und des königlichen Palastes
vollendet und alle Pläne, die er auszuführen wünschte, verwirklicht
hatte, [fn:1]

<<v2>>
2 erschien ihm der Herr zum zweiten Mal, wie er ihm in Gibeon erschienen
war. [fn:2]

<<v3>>
3 Er sprach zu ihm: Ich habe dein flehentliches Gebet, das du an mich
gerichtet hast, gehört und dieses Haus, das du gebaut hast, geheiligt.
Meinen Namen werde ich für immer hierher legen, meine Augen und mein
Herz werden allezeit hier weilen.

<<v4>>
4 Wenn du mit ungeteiltem und aufrichtigem Herzen vor mir den Weg gehst,
den dein Vater David gegangen ist, und wenn du alles tust, was ich dir
befohlen habe, wenn du auf meine Gebote und Rechtsvorschriften achtest,

<<v5>>
5 dann werde ich deinen Königsthron auf ewig in Israel bestehen lassen,
wie ich es deinem Vater David zugesichert habe, zu dem ich gesagt habe:
Es soll dir nie an einem Nachkommen auf dem Thron Israels fehlen. [fn:3]

<<v6>>
6 Doch wenn ihr und eure Söhne euch von mir abwendet und die Gebote und
Gesetze, die ich euch gegeben habe, übertretet, wenn ihr euch anschickt,
andere Götter zu verehren und anzubeten,

<<v7>>
7 dann werde ich Israel in dem Land ausrotten, das ich ihm gegeben habe.
Das Haus, das ich meinem Namen geweiht habe, werde ich aus meinem
Angesicht wegschaffen und Israel soll zum Gespött und zum Hohn unter
allen Völkern werden.

<<v8>>
8 Dieses Haus wird zu einem Trümmerhaufen werden und jeder, der
vorübergeht, wird sich entsetzen und zischen. Man wird fragen: Warum hat
der Herr diesem Land und diesem Haus das angetan? [fn:4]

<<v9>>
9 Und man wird antworten: Weil sie den Herrn, ihren Gott, der ihre Väter
aus Ägypten geführt hat, verlassen, sich an andere Götter gehängt, sich
vor ihnen niedergeworfen und sie verehrt haben, darum hat der Herr all
dieses Unglück über sie gebracht.\\
\\

<<v10>>
* Verschiedene Nachrichten über Salomo: 9,10-28

10 Zwanzig Jahre hatte Salomo an den beiden Häusern, dem Tempel des
Herrn und dem königlichen Palast, gebaut. [fn:5]

<<v11>>
11 Der König Hiram von Tyrus hatte ihn dabei mit Zedern- und
Zypressenholz sowie mit Gold in der gewünschten Menge unterstützt.
Damals trat König Salomo zwanzig Städte in der Landschaft Galiläa an
Hiram ab.

<<v12>>
12 Als aber Hiram aus Tyrus herüberkam, um die Städte anzusehen, die
Salomo ihm gegeben hatte, gefielen sie ihm nicht.

<<v13>>
13 Er meinte: Was sind das für Städte, die du mir gegeben hast, mein
Bruder? - Man nennt sie Land Kabul bis zum heutigen Tag. [fn:6]

<<v14>>
14 Hiram hatte dem König hundertzwanzig Talente Gold gesandt.

<<v15>>
15 So verhielt es sich mit dem Frondienst: König Salomo hatte
Fronarbeiter ausgehoben zum Bau des Tempels, seines Palastes, des Millo
und der Mauern von Jerusalem, Hazor, Megiddo und Geser. [fn:7] [fn:8]

<<v16>>
16 Der Pharao, der König von Ägypten, war nämlich heraufgezogen, hatte
Geser erobert und eingeäschert, die Kanaaniter, die darin wohnten,
getötet und die Stadt als Brautgeschenk seiner Tochter, der Frau
Salomos, gegeben. [fn:9]

<<v17>>
17 Salomo baute nun Geser wieder auf. Ferner baute er das untere
Bet-Horon aus [fn:10]

<<v18>>
18 sowie Baala und Tamar in der Steppe im Land (Juda),

<<v19>>
19 dazu alle Vorratsstädte, die ihm gehörten, die Städte für die Wagen
und ihre Mannschaft und was er sonst in Jerusalem, auf dem Libanon und
im ganzen Bereich seiner Herrschaft zu bauen wünschte.

<<v20>>
20 Die Reste der Amoriter, Hetiter, Perisiter, Hiwiter und Jebusiter,
die nicht zu den Israeliten gehörten

<<v21>>
21 und von denen noch Nachkommen im Land lebten - die Israeliten hatten
sie nicht ausrotten können -, hob Salomo als Fronarbeiter aus und sie
blieben es bis zum heutigen Tag.

<<v22>>
22 Von den Israeliten aber machte Salomo niemand zum Sklaven; sie waren
seine Krieger und Beamten, seine Obersten und Hauptleute, die
Befehlshaber über seine Wagen und deren Mannschaft.

<<v23>>
23 Die Leitung der Arbeiten Salomos oblag den fünfhundertfünfzig
Werkführern unter dem Befehl der Statthalter. Sie hatten die Aufsicht
über die Leute, die bei den Arbeiten beschäftigt waren.

<<v24>>
24 Als die Tochter des Pharao aus der Davidstadt in ihr Haus
hinaufgezogen war, das Salomo für sie gebaut hatte, baute er den Millo
aus.

<<v25>>
25 Dreimal im Jahr brachte Salomo auf dem Altar, den er für den Herrn
erbaut hatte, Brand- und Heilsopfer dar und ließ seine Opfergaben vor
dem Herrn in Rauch aufgehen. Und er vollendete das Haus. [fn:11]

<<v26>>
26 König Salomo baute auch eine Flotte in Ezjon-Geber, das bei Elat an
der Küste des Schilfmeers in Edom liegt.

<<v27>>
27 Hiram schickte seine Leute, geübte Seefahrer, mit den Leuten Salomos
zu Schiff aus.

<<v28>>
28 Sie fuhren nach Ofir, holten von dort vierhundertzwanzig Talente Gold
und brachten es dem König Salomo. [fn:12]\\
\\

* Footnotes

[fn:1] (1-9) [[file:2.Chr_7.org::v11][2 Chr 7,11-22]]

[fn:2] (2-3) [[file:1.Kön_3.org::v4][3,4f]]

[fn:3] [[file:2.Sam_7.org::v16][2 Sam 7,16]]

[fn:4] wird zu einem Trümmerhaufen werden: sinngemäß korr.; H:
wird hoch sein. - Zischen ist ein Zeichen des Spottes.

[fn:5] (10-28) [[file:2.Chr_8.org::v1][2 Chr 8,1-18]]

[fn:6] Den Namen konnte man verächtlich verstehen als «wie
dürres Holz» (vgl. [[file:Jes_44.org::v19][Jes 44,19]]). Kabul: östlich von Akko.

[fn:7] [[file:2.Sam_5.org::v9][2 Sam 5,9]]

[fn:8] Zu Millo vgl. die Anmerkung zu [[file:2.Sam_5.org::v9][2 Sam 5,9]].

[fn:9] Vgl. die Anmerkung zu [[file:1.Kön_3.org::v1][3,1]].

[fn:10] 17f: Der Ausbau der Städte sicherte das Land gegen
Angriffe vom Norden und von Ägypten.

[fn:11] Der König bestritt vielleicht nur den Aufwand für die
Opfer, die von den Priestern dargebracht wurden. Die Dreizahl entsprach
wohl den drei Hauptfesten (vgl. [[file:2.Chr_8.org::v13][2 Chr 8,13]]). - Opfergaben: Text korr.

[fn:12] Ofir wird in Südarabien oder an der gegenüberliegenden
Küste Afrikas vermutet.
