#+TITLE: 1 Kön 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-12 So 14:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Kön 5.html

<<verses>>

<<v1>>
1 Salomo war Herrscher über alle Reiche vom Eufrat bis zum Land der
Philister und bis an die Grenze Ägyptens. Sie entrichteten Abgaben und
waren Salomo untertan, solange er lebte. [fn:1]

<<v2>>
2 Der tägliche Unterhalt Salomos belief sich auf dreißig Kor Feinmehl,
sechzig Kor gewöhnliches Mehl, [fn:2]

<<v3>>
3 zehn Mastrinder, zwanzig Weiderinder, hundert Schafe, nicht gerechnet
die Hirsche, Gazellen, Rehe und das gemästete Geflügel.

<<v4>>
4 Denn er herrschte über das ganze Gebiet diesseits des Stromes, von
Tifsach bis Gaza, über alle Könige diesseits des Stromes. Er hatte
Frieden ringsum nach allen Seiten. [fn:3]

<<v5>>
5 Juda und Israel lebten in Sicherheit von Dan bis Beerscheba; ein jeder
saß unter seinem Weinstock und seinem Feigenbaum, solange Salomo lebte. [fn:4]

<<v6>>
6 Salomo hatte viertausend Stallplätze für seine Wagenpferde und
zwölftausend Mann als Besatzung für die Wagen. [fn:5] [fn:6]

<<v7>>
7 Jene Statthalter, jeder in seinem Monat, versorgten den König Salomo
und alle, die zu seinem Tisch Zutritt hatten. Sie ließen es an nichts
fehlen.

<<v8>>
8 Die Gerste und das Stroh für die Pferde und Zugtiere brachten sie
jeweils an den Ort, für den jeder zuständig war.\\
\\

<<v9>>
* Die Weisheit Salomos: 5,9-14

9 Gott gab Salomo Weisheit und Einsicht in hohem Maß und Weite des
Herzens - wie Sand am Strand des Meeres. [fn:7]

<<v10>>
10 Die Weisheit Salomos war größer als die Weisheit aller Söhne des
Ostens und alle Weisheit Ägyptens. [fn:8]

<<v11>>
11 Er war weiser als alle Menschen, weiser als Etan, der Esrachiter, als
Heman, Kalkol und Darda, die Söhne Mahols. Sein Name war bekannt bei
allen Völkern ringsum. [fn:9]

<<v12>>
12 Er verfasste dreitausend Sprichwörter und die Zahl seiner Lieder
betrug tausendundfünf.

<<v13>>
13 Er redete über die Bäume, von der Zeder auf dem Libanon bis zum Ysop,
der an der Mauer wächst. Er redete über das Vieh, die Vögel, das Gewürm
und die Fische.

<<v14>>
14 Von allen Völkern kamen Leute, um die Weisheit Salomos zu hören,
Abgesandte von allen Königen der Erde, die von seiner Weisheit vernommen
hatten.\\
\\

<<v15>>
* Die Vorbereitungen zum Tempelbau: 5,15-32

15 Hiram, der König von Tyrus, sandte seine Diener zu Salomo; denn er
hatte gehört, dass man ihn anstelle seines Vaters zum König gesalbt
habe. Hiram war nämlich zeitlebens ein Freund Davids gewesen. [fn:10] [fn:11]

<<v16>>
16 Und Salomo ließ Hiram sagen:

<<v17>>
17 Du weißt selbst, dass mein Vater David durch Kriege verhindert war,
dem Namen des Herrn, seines Gottes, ein Haus zu bauen, da seine Feinde
ihn bedrängten, bis der Herr sie ihm unter die Füße legte.

<<v18>>
18 Jetzt aber hat mir der Herr, mein Gott, ringsum Ruhe verschafft. Es
gibt keinen Widersacher mehr und keine Gefahr.

<<v19>>
19 Darum gedenke ich, dem Namen des Herrn, meines Gottes, ein Haus zu
bauen; denn er hat meinem Vater David zugesagt: Dein Sohn, den ich an
deiner Stelle auf deinen Thron setzen werde, wird meinem Namen das Haus
bauen. [fn:12]

<<v20>>
20 Befiehl nun, dass man auf dem Libanon Zedern für mich fällt. Meine
Knechte sollen mit deinen Knechten arbeiten. Den Lohn für deine Knechte
werde ich dir geben, ganz wie du bestimmst. Du weißt ja selbst, dass wir
niemand haben, der so gut Holz fällen kann wie die Leute von Sidon.

<<v21>>
21 Als Hiram die Botschaft Salomos vernahm, freute er sich sehr und rief
aus: Gepriesen sei heute Jahwe, der David einen weisen Sohn als
Herrscher über dieses große Volk gegeben hat.

<<v22>>
22 Er ließ Salomo sagen: Ich habe die Botschaft vernommen, die du an
mich gesandt hast, und werde deinen Wunsch nach Zedern- und
Zypressenholz erfüllen.

<<v23>>
23 Meine Leute werden es vom Libanon an das Meer schaffen. Ich lasse es
dann auf dem Meer an den Ort flößen, den du mir nennen wirst. Dort lasse
ich es wieder auseinander nehmen, sodass du es abholen kannst. Du aber
erfülle meinen Wunsch und sende Lebensmittel für mein Haus!

<<v24>>
24 Also lieferte Hiram so viel Zedern- und Zypressenholz, wie Salomo
wollte,

<<v25>>
25 und Salomo gab Hiram zwanzigtausend Kor Weizen zum Unterhalt seines
Hofes und zwanzig Kor feinstes Öl. Diese Menge lieferte Salomo Jahr für
Jahr an Hiram.

<<v26>>
26 Der Herr schenkte Salomo Weisheit, wie er es ihm versprochen hatte.
Zwischen Salomo und Hiram herrschte Friede und sie schlossen miteinander
ein Bündnis.

<<v27>>
27 König Salomo ließ Leute aus ganz Israel zum Frondienst ausheben.
Dieser umfasste 30000 Fronpflichtige.

<<v28>>
28 Von ihnen schickte er abwechselnd jeden Monat 10000 Mann auf den
Libanon. Einen Monat waren sie auf dem Libanon und zwei Monate zu Hause.
Adoniram leitete den Frondienst.

<<v29>>
29 Ferner hatte Salomo 70000 Lastträger und 80000 Steinhauer im Gebirge, [fn:13]

<<v30>>
30 nicht eingerechnet die 3600 Werkführer unter dem Befehl der
Statthalter, denen die Leitung der Arbeit oblag. Sie führten die
Aufsicht über die Arbeiter.

<<v31>>
31 Der König ließ mächtige, kostbare Steine brechen, um mit Quadern das
Fundament des Tempels zu legen.

<<v32>>
32 Die Bauleute Salomos bearbeiteten mit den Bauleuten Hirams und den
Gebalitern das Holz und die Steine und richteten sie her für den Bau des
Tempels. [fn:14]\\
\\

* Footnotes

[fn:1] David hatte im Norden das Reich von Damaskus und im
Süden die Edomiter unterworfen und beherrschte dadurch das ganze Gebiet
vom Eufrat bis an die Grenzen Ägyptens. Die Küstengebiete der Philister
blieben aber selbstständig.

[fn:2] 2f: Der große Aufwand diente zur Versorgung aller
Personen, die im Dienst des Staates standen.

[fn:3] Eintragung aus nachexilischer Zeit. Zu «diesseits des
Stromes» vgl. die Anmerkung zu [[file:2.Sam_10.org::v16][2 Sam 10,16]]. - Tifsach = Thapsakus am
Eufrat.

[fn:4] Die Formel «von Dan bis Beerscheba» umschreibt die ganze
Nord-Süd-Ausdehnung des von Israeliten bewohnten Gebiets. - Unter seinem
Weinstock und seinem Feigenbaum sitzen ist Zeichen des Glücks und der
Zufriedenheit (vgl. [[file:2.Kön_18.org::v31][2 Kön 18,31]]; [[file:Mi_4.org::v4][Mi 4,4]]; [[file:Sach_3.org::v10][Sach 3,10]]).

[fn:5] [[file:1.Kön_10.org::v26][10,26]]; [[file:2.Chr_9.org::v25][2 Chr 9,25]]

[fn:6] Von Salomo wurde der Kriegswagen im israelitischen Heer
eingeführt. Seine Besatzung bestand wahrscheinlich aus drei Mann. Wenn
jeder Stallplatz zwei Pferde, das Gespann für einen Wagen enthielt,
verteilen sich die 12000 Mann auf 4000 Wagen, so [[file:2.Chr_9.org::v25][2 Chr 9,25]] (H: 40000);
der Wirklichkeit näher kommt vielleicht die Zahl 1400 in [[file:1.Kön_10.org::v26][1 Kön 10,26]].

[fn:7] [[file:Ps_139.org::v18][Ps 139,18]]

[fn:8] Söhne des Ostens: die Nomadenstämme der syrisch-arabischen Wüste.

[fn:9] [[file:1.Chr_2.org::v6][1 Chr 2,6]]; [[file:Ps_89.org::v1][Ps 89,1]]

[fn:10] (15-32) [[file:2.Chr_2.org::v2][2 Chr 2,2-17]]

[fn:11] Zum Verhältnis Hirams zu David vgl. [[file:2.Sam_5.org::v11][2 Sam 5,11]].

[fn:12] [[file:2.Sam_7.org::v12][2 Sam 7,12f]]

[fn:13] Die Lastträger und Steinhauer wurden nach [[file:2.Chr_2.org::v16][2 Chr 2,16f]]
aus der nichtisraelitischen Bevölkerung genommen. Den hohen Zahlen, die
kaum der Wirklichkeit entsprechen, mag eine nicht mehr bekannte Symbolik
zugrunde liegen.

[fn:14] Gebaliter sind die Bewohner der Stadt Gebal (= Byblus)
nördlich von Beirut.
