#+TITLE: 1 Kön 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-12 So 00:18]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Kön 2.html

<<verses>>

<<v1>>
* Davids letzte Anordnungen und sein Tod: 2,1-12

1 Als die Zeit herankam, da David sterben sollte, ermahnte er seinen
Sohn Salomo:

<<v2>>
2 Ich gehe nun den Weg alles Irdischen. Sei also stark und mannhaft!

<<v3>>
3 Erfüll deine Pflicht gegen den Herrn, deinen Gott: Geh auf seinen
Wegen und befolg alle Gebote, Befehle, Satzungen und Anordnungen, die im
Gesetz des Mose niedergeschrieben sind. Dann wirst du Erfolg haben bei
allem, was du tust, und in allem, was du unternimmst.

<<v4>>
4 Und der Herr wird sein Wort wahr machen, das er mir gegeben hat, als
er sagte: Wenn deine Söhne auf ihren Weg achten und aufrichtig mit
ganzem Herzen und ganzer Seele vor mir leben, wird es dir nie an
Nachkommen auf dem Thron Israels fehlen.

<<v5>>
5 Du weißt selbst, was Joab, der Sohn der Zeruja, mir angetan hat: was
er den beiden Heerführern Israels, Abner, dem Sohn Ners, und Amasa, dem
Sohn Jeters, angetan hat. Er hat sie ermordet, hat mit Blut, das im
Krieg vergossen wurde, den Frieden belastet und mit unschuldigem Blut
den Gürtel an seinen Hüften und die Schuhe an seinen Füßen befleckt. [fn:1] [fn:2]

<<v6>>
6 Lass dich von deiner Weisheit leiten und sorge dafür, dass sein graues
Haupt nicht unbehelligt in die Unterwelt kommt.

<<v7>>
7 Doch die Söhne Barsillais aus Gilead sollst du freundlich behandeln.
Sie sollen zu denen gehören, die von deinem Tisch essen; denn sie sind
mir ebenso entgegengekommen, als ich vor deinem Bruder Abschalom fliehen
musste. [fn:3]

<<v8>>
8 Da ist auch Schimi, der Sohn Geras, vom Stamm Benjamin, aus Bahurim.
Er hat einen bösen Fluch gegen mich ausgesprochen, als ich nach
Mahanajim floh. Doch ist er mir an den Jordan entgegengekommen und ich
habe ihm beim Herrn geschworen, dass ich ihn nicht mit dem Schwert
hinrichten werde. [fn:4] [fn:5]

<<v9>>
9 Jetzt aber lass ihn nicht ungestraft! Du bist ein kluger Mann und
weißt, was du mit ihm tun sollst. Schick sein graues Haupt blutig in die
Unterwelt!

<<v10>>
10 David entschlief zu seinen Vätern und wurde in der Davidstadt
begraben.

<<v11>>
11 Die Zeit, in der David über Israel König war, betrug vierzig Jahre.
In Hebron regierte er sieben und in Jerusalem dreiunddreißig Jahre.

<<v12>>
12 Salomo saß nun auf dem Thron seines Vaters David und seine Herrschaft
festigte sich mehr und mehr.\\
\\

<<v13>>
* Das Ende der Gegner Salomos: 2,13-46

13 Adonija, der Sohn der Haggit, begab sich zu Batseba, der Mutter
Salomos. Sie fragte ihn: Kommst du in friedlicher Absicht? Er
antwortete: Ja.

<<v14>>
14 Dann fuhr er fort: Ich möchte mit dir reden. Sie erwiderte: Rede nur!

<<v15>>
15 Da sagte er: Du weißt, dass mir das Königtum zustand und dass ganz
Israel mich als König haben wollte. Doch ist mir die Königswürde
entgangen; sie ist meinem Bruder zugefallen, weil sie ihm vom Herrn
bestimmt war.

<<v16>>
16 Jetzt aber möchte ich eine einzige Bitte an dich richten. Weise mich
nicht ab! Sie antwortete: Sprich sie nur aus!

<<v17>>
17 Da begann er: Rede doch mit König Salomo; dich wird er nicht
abweisen. Bitte ihn, dass er mir Abischag aus Schunem zur Frau gibt.

<<v18>>
18 Batseba erwiderte: Gut, ich werde in deiner Angelegenheit mit dem
König reden.

<<v19>>
19 Als nun Batseba zu König Salomo kam, um mit ihm wegen Adonija zu
sprechen, erhob sich der König, ging ihr entgegen und verneigte sich vor
ihr. Dann setzte er sich auf seinen Thron und ließ auch für die
Königinmutter einen Thron hinstellen. Sie setzte sich an seine rechte
Seite [fn:6]

<<v20>>
20 und begann: Eine einzige kleine Bitte hätte ich an dich. Weise mich
nicht ab! Der König antwortete ihr: Sprich sie nur aus, Mutter! Ich
werde dich nicht abweisen.

<<v21>>
21 Da bat sie: Man gebe doch Abischag aus Schunem deinem Bruder Adonija
zur Frau.

<<v22>>
22 Der König Salomo entgegnete seiner Mutter: Warum bittest du für
Adonija um Abischag aus Schunem? Fordere doch gleich das Königtum für
ihn! Er ist ja mein älterer Bruder und auf seiner Seite stehen der
Priester Abjatar und Joab, der Sohn der Zeruja.

<<v23>>
23 Und König Salomo schwor beim Herrn: Gott soll mir dies und das antun,
wenn dieses Ansinnen Adonija nicht das Leben kostet.

<<v24>>
24 So wahr der Herr lebt, der mich eingesetzt und auf den Thron meines
Vaters David erhoben hat und der mir, wie er versprochen hat, ein Haus
gebaut hat: Noch heute muss Adonija sterben.

<<v25>>
25 Darauf schickte König Salomo Benaja, den Sohn Jojadas, hinauf und
dieser versetzte Adonija den Todesstoß.

<<v26>>
26 Zum Priester Abjatar sagte der König: Geh auf dein Landgut nach
Anatot! Zwar hast du den Tod verdient; doch will ich dich heute nicht
töten, weil du die Lade Gottes, des Herrn, vor meinem Vater David
getragen und alle Demütigungen mit meinem Vater geteilt hast. [fn:7]

<<v27>>
27 So setzte Salomo Abjatar als Priester des Herrn ab und erfüllte das
Wort, das der Herr über das Haus Eli in Schilo gesprochen hatte. [fn:8]

<<v28>>
28 Die Kunde davon erreichte Joab. Er hatte zu Adonija gehalten, sich
aber nicht an Abschalom angeschlossen. Er floh in das Zelt des Herrn und
ergriff die Hörner des Altars.

<<v29>>
29 Man meldete dem König Salomo: Joab ist in das Zelt des Herrn geflohen
und steht neben dem Altar. Salomo sandte Benaja, den Sohn Jojadas, mit
dem Auftrag: Geh hin und stoß ihn nieder!

<<v30>>
30 Benaja kam in das Zelt des Herrn und rief Joab zu: Der König befiehlt
dir herauszukommen. Doch Joab antwortete: Nein, hier will ich sterben.
Benaja berichtete dem König: Das hat Joab gesagt, so hat er mir
geantwortet.

<<v31>>
31 Da gebot ihm der König: Tu, was er gesagt hat! Stoß ihn nieder und
begrab ihn! Nimm so von mir und vom Haus meines Vaters das Blut, das
Joab ohne Grund vergossen hat.

<<v32>>
32 Der Herr lasse sein Blut auf sein Haupt kommen, weil er ohne Wissen
meines Vaters zwei Männer, die gerechter und besser waren als er,
niedergestoßen und mit dem Schwert getötet hat: Abner, den Sohn Ners,
den Heerführer Israels, und Amasa, den Sohn Jeters, den Heerführer
Judas.

<<v33>>
33 Ihr Blut komme für immer auf das Haupt Joabs und seiner Nachkommen.
David aber, seinen Nachkommen, seinem Haus und seinem Thron sei vom
Herrn immerfort Heil beschieden.

<<v34>>
34 Nun ging Benaja, der Sohn Jojadas, hinauf, stieß Joab nieder und
tötete ihn. Er wurde auf seinem Besitz in der Steppe begraben.

<<v35>>
35 Der König setzte dann Benaja, den Sohn Jojadas, an seiner Stelle über
das Heer und dem Priester Zadok verlieh er die Stelle Abjatars.

<<v36>>
36 Hierauf ließ der König Schimi rufen und befahl ihm: Bau dir ein Haus
in Jerusalem, bleib hier und geh nicht weg, weder dahin noch dorthin!

<<v37>>
37 Du sollst wissen, dass du sterben musst, sobald du hinausgehst und
das Kidrontal überschreitest. Du wirst dann selbst schuld sein an deinem
Tod.

<<v38>>
38 Schimi antwortete dem König: Gut, dein Knecht wird tun, was mein
Herr, der König, bestimmt hat. So blieb Schimi viele Tage in Jerusalem.

<<v39>>
39 Nach Verlauf von drei Jahren entflohen zwei Sklaven Schimis zu
Achisch, dem Sohn Maachas, dem König von Gat. Man meldete Schimi: Deine
Sklaven sind in Gat.

<<v40>>
40 Da machte er sich auf, sattelte seinen Esel und begab sich zu Achisch
nach Gat, um seine Sklaven zu suchen. Er ging hin und holte sie aus Gat
zurück.

<<v41>>
41 Es wurde aber Salomo hinterbracht, dass Schimi von Jerusalem nach Gat
gegangen und wieder zurückgekehrt sei.

<<v42>>
42 Er ließ daher Schimi rufen und hielt ihm vor: Habe ich dich nicht
beim Herrn schwören lassen und dich gewarnt: Sobald du weggehst und dich
dahin oder dorthin begibst, so weißt du, dass du sterben musst? Und du
hast geantwortet: Gut, ich habe es gehört.

<<v43>>
43 Warum hast du den Eid beim Herrn und den Befehl, den ich dir gegeben
habe, nicht beachtet?

<<v44>>
44 Und weiter sagte der König zu Schimi: Du weißt, wie viel Böses du
meinem Vater David angetan hast; jetzt lässt es der Herr auf dich selbst
zurückfallen.

<<v45>>
45 Der König Salomo aber sei gesegnet und der Thron Davids stehe fest
vor dem Herrn in Ewigkeit.

<<v46>>
46 Hierauf erteilte der König dem Benaja, dem Sohn Jojadas, Befehl und
dieser ging hinaus und versetzte Schimi den Todesstoß. Die Herrschaft
war nun fest in der Hand Salomos.\\
\\

* Footnotes

[fn:1] [[file:2.Sam_3.org::v27][2 Sam 3,27]]; [[file:2.Sam_20.org::v10][20,10]]

[fn:2] Damals war David nicht in der Lage, Joab zu bestrafen.
Nach israelitischer Vorstellung von Vergeltung entsprachen die
Anweisungen Davids an seinen Sohn der auf David lastenden Verpflichtung,
den Tod der beiden Männer zu rächen.

[fn:3] [[file:2.Sam_17.org::v27][2 Sam 17,27-29]]

[fn:4] [[file:2.Sam_16.org::v5][2 Sam 16,5]]; [[file:2.Sam_19.org::v19][19,19-24]]

[fn:5] 8f: Die alte Zeit glaubte, dass ein einmal
ausgesprochener Fluch mit unwiderstehlicher Kraft fortwirkt. David
musste daher fürchten, dass seinem Haus Unglück drohte, solange Schimis
Fluch nicht gerächt war. Da er selbst durch den Eid gebunden war, sollte
Salomo die Drohung beseitigen.

[fn:6] 19f: Die Mutter des Königs hatte als «Herrin» ([[file:2.Sam_15.org::v13][15,13]])
eine Ehrenstellung inne.

[fn:7] [[file:1.Sam_22.org::v20][1 Sam 22,20-23]]

[fn:8] [[file:1.Sam_2.org::v30][1 Sam 2,30-36]]
