#+TITLE: 1 Kön 14 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-15 Mi 12:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Kön 14.html

<<verses>>

<<v1>>
* Das kranke Kind Jerobeams: 14,1-18

1 In jener Zeit erkrankte Jerobeams Sohn Abija.

<<v2>>
2 Jerobeam befahl daher seiner Frau: Mach dich auf, verkleide dich,
damit man nicht erkennt, dass du Jerobeams Frau bist, und geh nach
Schilo! Dort wohnt der Prophet Ahija, der mir verkündet hat, dass ich
König dieses Volkes sein werde. [fn:1]

<<v3>>
3 Nimm zehn Brote, Kuchen und einen Krug Honig mit und geh zu ihm! Er
wird dir sagen, was mit dem Kind geschehen wird.

<<v4>>
4 Die Frau Jerobeams tat so; sie machte sich auf, ging nach Schilo und
kam in das Haus Ahijas. Dieser aber konnte nicht mehr sehen; denn seine
Augen waren im Alter starr geworden.

<<v5>>
5 Doch der Herr hatte ihm gesagt: Die Frau Jerobeams kommt, um von dir
Auskunft über ihren kranken Sohn zu erhalten. Das und das sollst du zu
ihr sagen. Wenn sie kommt, wird sie sich verstellen.

<<v6>>
6 Sobald sie sich nun der Türe näherte und Ahija das Geräusch ihrer
Schritte hörte, rief er: Komm herein, Frau Jerobeams! Warum verstellst
du dich? Ich habe dir eine harte Botschaft zu verkünden.

<<v7>>
7 Geh heim und sag zu Jerobeam: So spricht der Herr, der Gott Israels:
Ich habe dich mitten aus dem Volk emporgehoben und zum Fürsten meines
Volkes Israel gemacht.

<<v8>>
8 Ich habe das Königtum dem Haus David entrissen und dir gegeben. Du
aber bist nicht wie mein Knecht David gewesen, der meine Gebote hielt,
mir mit ganzem Herzen folgte und nur das tat, was mir gefällt.

<<v9>>
9 Du hast es schlimmer getrieben als alle, die vor dir waren, du bist
hingegangen, hast dir andere Götter und Gussbilder gemacht und mich
dadurch erzürnt. Mir hast du den Rücken gekehrt.

<<v10>>
10 Darum bringe ich Unglück über das Haus Jerobeam und rotte von ihm
alles, was männlich ist, bis zum letzten Mann in Israel aus. Ich fege
das Haus Jerobeam hinweg, wie man Kot hinwegfegt, bis nichts mehr
vorhanden ist. [fn:2]

<<v11>>
11 Wer vom Haus Jerobeam in der Stadt stirbt, den werden die Hunde
fressen; und wer auf dem freien Feld stirbt, den werden die Vögel des
Himmels fressen. Ja, der Herr hat gesprochen.

<<v12>>
12 Du aber mach dich auf und geh in dein Haus! Sobald deine Füße die
Stadt betreten, wird der Knabe sterben.

<<v13>>
13 Ganz Israel wird ihm die Totenklage halten und ihn begraben; denn er
allein wird vom Haus Jerobeam ein Grab erhalten, weil im Haus Jerobeam
nur an ihm sich etwas fand, was dem Herrn, dem Gott Israels, gefiel.

<<v14>>
14 Der Herr aber wird sich einen König von Israel bestellen, der das
Haus Jerobeam ausrottet . . . [fn:3]

<<v15>>
15 Der Herr wird Israel schlagen, dass es schwankt wie das Rohr im
Wasser, und er wird Israel aus diesem guten Land, das er den Vätern
gegeben hat, ausreißen und es jenseits des Stromes zerstreuen, weil sie
sich Kultpfähle gemacht und ihn dadurch erzürnt haben. [fn:4]

<<v16>>
16 Er wird Israel preisgeben wegen der Sünden, die Jerobeam begangen und
zu denen er Israel verführt hat.

<<v17>>
17 Da stand die Frau Jerobeams auf und ging. Als sie nach Tirza kam und
über die Schwelle des Hauses trat, starb der Knabe. [fn:5]

<<v18>>
18 Ganz Israel begrub ihn und hielt ihm die Totenklage, wie der Herr
durch seinen Knecht, den Propheten Ahija, vorausgesagt hatte.\\
\\

<<v19>>
* Jerobeams Tod: 14,19-20

19 Die übrige Geschichte Jerobeams, welche Kriege er führte und wie er
regierte, ist aufgezeichnet in der Chronik der Könige von Israel.

<<v20>>
20 Die Regierungszeit Jerobeams betrug zweiundzwanzig Jahre. Er
entschlief zu seinen Vätern und sein Sohn Nadab wurde König an seiner
Stelle.\\
\\

<<v21>>
* Rehabeam von Juda: 14,21-31

21 Rehabeam, der Sohn Salomos, war König in Juda. Er war einundvierzig
Jahre alt, als er König wurde, und regierte siebzehn Jahre in Jerusalem,
der Stadt, die der Herr aus allen Stämmen Israels erwählt hatte, um
seinen Namen auf sie zu legen. Seine Mutter hieß Naama und war eine
Ammoniterin. [fn:6]

<<v22>>
22 Juda aber tat, was dem Herrn missfiel. Die Sünden, die sie begingen,
reizten ihn mehr als alles, was ihre Väter getan hatten.

<<v23>>
23 Denn auch sie errichteten Kulthöhen, Steinmale und Kultpfähle auf
allen hohen Hügeln und unter jedem üppigen Baum. [fn:7]

<<v24>>
24 Sogar Hierodulen gab es im Land. Die Israeliten ahmten alle Gräuel
der Völker nach, die der Herr vor ihnen vertrieben hatte. [fn:8]

<<v25>>
25 Im fünften Jahr des Königs Rehabeam zog Schischak, der König von
Ägypten, gegen Jerusalem.

<<v26>>
26 Er raubte die Schätze des Tempels und die Schätze des königlichen
Palastes und nahm alles weg, auch alle goldenen Schilde, die Salomo
hatte anfertigen lassen.

<<v27>>
27 An deren Stelle ließ König Rehabeam bronzene anfertigen und übergab
sie den Befehlshabern der Läufer, die den Eingang zum Haus des Königs
bewachten. [fn:9]

<<v28>>
28 Sooft nun der König in das Haus des Herrn ging, trugen die Läufer die
Schilde und brachten sie dann wieder in ihre Wachstube zurück.

<<v29>>
29 Die übrige Geschichte Rehabeams und alle seine Taten sind
aufgezeichnet in der Chronik der Könige von Juda.

<<v30>>
30 Es war aber dauernd Krieg zwischen Rehabeam und Jerobeam.

<<v31>>
31 Rehabeam entschlief zu seinen Vätern und wurde bei seinen Vätern in
der Davidstadt begraben. Seine Mutter hieß Naama und war eine
Ammoniterin. Sein Sohn Abija wurde König an seiner Stelle.\\
\\

* Footnotes

[fn:1] [[file:1.Kön_11.org::v29][11,29-39]]

[fn:2] [[file:1.Kön_16.org::v4][16,4]]; [[file:1.Kön_21.org::v21][21,21-24]]; [[file:2.Kön_9.org::v8][2 Kön 9,8]]

[fn:3] H unverständlich.

[fn:4] dass es schwankt: sinngemäß ergänzt.

[fn:5] Tirza, nördlich von Sichem, blieb bis Omri (885-874 v. Chr.)
Hauptstadt des Nordreichs (vgl. die Anmerkung zu 16,24).

[fn:6] (21-31) [[file:2.Chr_12.org::v9][2 Chr 12,9-16]]

[fn:7] Pfähle aus Holz standen als Sinnbilder der Göttin
Aschera oder Astarte neben oder auf den Altären. Steinmale, sog.
Mazzeben, wurden zur Erinnerung an Personen (Gen 35,20) oder besondere
Erlebnisse ([[file:Gen_28.org::v18][Gen 28,18]]; [[file:Gen_35.org::v14][35,14]]) errichtet und waren in diesem Fall auch
für den frommen Israeliten unbedenklich. Dagegen erscheinen sie zusammen
mit heiligen Pfählen in heidnischen Kulten als Symbole des Baal. -
Üppige Bäume konnten im wasserarmen Palästina leicht als
Offenbarungsstätte einer Fruchtbarkeitsgottheit gedeutet werden.

[fn:8] Die in der Umwelt Israels geübte kultische Unzucht im
Dienst heidnischer Götter war nach [[file:Dtn_23.org::v18][Dtn 23,18]] verboten und wurde von den
Propheten bekämpft (vgl. [[file:Jer_3.org::v2][Jer 3,2]]; [[file:Hos_4.org::v14][Hos 4,14]]).

[fn:9] Die «Läufer» waren ursprünglich die Begleiter des
Königs; später dienten sie als Palastwache.
