#+TITLE: 1 Kön 6 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-12 So 14:41]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Kön 6.html

<<verses>>

<<v1>>
* Der Tempelbau: 6,1-38

1 Im vierhundertachtzigsten Jahr nach dem Auszug der Israeliten aus
Ägypten, im vierten Jahr der Regierung Salomos über Israel, im Monat
Siw, das ist der zweite Monat, begann er das Haus des Herrn zu bauen. [fn:1] [fn:2]

<<v2>>
2 Das Haus, das König Salomo für den Herrn baute, war sechzig Ellen
lang, zwanzig Ellen breit und dreißig Ellen hoch.

<<v3>>
3 Die Vorhalle vor dem Hauptraum des Hauses war zwanzig Ellen breit,
entsprechend der Breite des Hauses, und zehn Ellen tief in der
Längsrichtung des Hauses.

<<v4>>
4 Er machte für das Haus Fenster mit Rahmen und Gittern.

<<v5>>
5 An die Wände des Hauses, und zwar an die Wände des Hauptraums und des
hinteren Raumes, legte er ringsum einen Anbau mit Kammern.

<<v6>>
6 Dieser war im Untergeschoss fünf Ellen, im mittleren sechs und im
dritten sieben Ellen breit; die Außenwand des Hauses hatte er abgestuft,
um sie nachher nicht beschädigen zu müssen.

<<v7>>
7 Beim Bau des Hauses wurden Steine verwendet, die man schon im
Steinbruch fertig behauen hatte; Hämmer, Meißel und sonstige eiserne
Werkzeuge waren beim Bau des Hauses nicht zu hören.

<<v8>>
8 Die Türe zu den unteren Kammern war an der Südseite des Hauses. Über
Treppen stieg man zum mittleren und vom mittleren zum dritten Stockwerk
hinauf.

<<v9>>
9 Als er den Bau des Hauses vollendet hatte, überdeckte er es mit Balken
und Brettern aus Zedernholz.

<<v10>>
10 Den Anbau führte er um das ganze Haus. Seine Höhe betrug (in jedem
Stockwerk) fünf Ellen und Zedernbalken verbanden ihn mit dem Haus.

<<v11>>
11 Das Wort des Herrn erging an Salomo:

<<v12>>
12 Dieses Haus, das du baust, - wenn du meinen Geboten gehorchst und auf
meine Vorschriften achtest und alle meine Befehle ausführst und
befolgst, dann werde ich an dir das Wort wahr machen, das ich zu deinem
Vater David gesprochen habe. [fn:3]

<<v13>>
13 Und ich werde inmitten der Israeliten wohnen und mein Volk Israel
nicht verlassen.

<<v14>>
14 So vollendete Salomo den Bau des Hauses.

<<v15>>
15 Er täfelte seine Innenwände mit Zedernholz aus; vom Fußboden bis zu
den Balken der Decke ließ er eine Holzvertäfelung anbringen. Den
Fußboden belegte er mit Zypressenholz.

<<v16>>
16 Zwanzig Ellen vor der Rückseite des Hauses errichtete er vom Fußboden
bis zum Gebälk eine Wand aus Zedernholz und schuf so die Gotteswohnung,
das Allerheiligste.

<<v17>>
17 Vierzig Ellen lang war der davorliegende Hauptraum.

<<v18>>
18 Im Innern hatte das Haus Zedernverkleidung mit eingeschnitzten
Blumengewinden und Blütenranken. Alles war aus Zedernholz, kein Stein
war zu sehen.

<<v19>>
19 Im Innern des Hauses richtete er die Gotteswohnung ein, um die
Bundeslade des Herrn aufstellen zu können.

<<v20>>
20 Die Wohnung war zwanzig Ellen lang, zwanzig Ellen breit und zwanzig
Ellen hoch; er überzog sie mit bestem Gold. Auch ließ er einen Altar aus
Zedernholz herstellen.

<<v21>>
21 Das Innere des Hauses ließ Salomo mit bestem Gold auskleiden und vor
der Gotteswohnung ließ er goldene Ketten anbringen. [fn:4]

<<v22>>
22 So überzog er das ganze Haus vollständig mit Gold; auch den Altar vor
der Gotteswohnung überzog er ganz mit Gold.

<<v23>>
23 In der Gotteswohnung ließ er zwei Kerubim aus Olivenholz anfertigen.
Ihre Höhe betrug zehn Ellen. [fn:5]

<<v24>>
24 Fünf Ellen maß der eine Flügel des Kerubs und fünf Ellen sein anderer
Flügel. Von einem Flügelende bis zum anderen waren es zehn Ellen.

<<v25>>
25 Auch der zweite Kerub war zehn Ellen hoch. Beide hatten gleiches Maß
und gleiche Gestalt.

<<v26>>
26 Der eine Kerub war zehn Ellen hoch und ebenso hoch war der andere.

<<v27>>
27 Er stellte die Kerubim mitten in den innersten Raum. Ihre Flügel
waren so ausgespannt, dass der Flügel des einen Kerubs die eine Wand,
der Flügel des zweiten Kerubs die andere Wand, die Flügel in der Mitte
des Raumes aber einander berührten.

<<v28>>
28 Er ließ die Kerubim mit Gold überziehen.

<<v29>>
29 An allen Wänden des Hauses, im inneren wie im äußeren Raum, ließ er
ringsum Kerubim, Palmen und Blütenranken einschnitzen.

<<v30>>
30 Auch die Fußböden des hinteren und des vorderen Raumes ließ er mit
Gold belegen.

<<v31>>
31 Für den Eingang zur Gotteswohnung ließ er Türflügel aus Olivenholz
anfertigen. Die Giebelbalken und die Seitenpfosten bildeten ein Fünfeck.

<<v32>>
32 An den beiden Türflügeln aus Olivenholz ließ er Kerubim, Palmen und
Blütenranken einschnitzen und sie mit Gold überziehen, indem er auf die
Kerubim und die Palmen Gold auftragen ließ.

<<v33>>
33 Ebenso ließ er für den Eingang zum Hauptraum Türpfosten aus
Olivenholz anfertigen, die ein Viereck bildeten,

<<v34>>
34 dazu zwei Türflügel aus Zypressenholz. Zwei drehbare Teile hatte der
eine Türflügel und zwei drehbare Teile der andere.

<<v35>>
35 Er ließ auf ihnen Kerubim, Palmen und Blütenranken einschnitzen und
auf das Schnitzwerk dünnes Blattgold legen.

<<v36>>
36 Er legte den inneren Hof an (und umgab ihn mit einer Mauer) aus drei
Lagen Quadern und einer Lage Zedernbalken.

<<v37>>
37 Im vierten Jahr, im Monat Siw, war das Fundament für das Haus des
Herrn gelegt worden

<<v38>>
38 und im elften Jahr, im Monat Bul, das ist der achte Monat, wurde das
Haus mit all seinem Zubehör vollendet, ganz so, wie es geplant war.
Sieben Jahre hatte man an ihm gebaut. [fn:6]\\
\\

* Footnotes

[fn:1] (1-38) [[file:2.Chr_3.org::v1][2 Chr 3,1-14]]

[fn:2] 1-7,51: Die Kap. [[v1][6]] und [[file:1.Kön_7.org::v1][7]] bereiten dem Verständnis
erhebliche Schwierigkeiten. Besonders die Angaben über den Tempel sind
oft schwer verständlich. H ist mehrfach durch Schreibfehler,
Erweiterungen und Kürzungen entstellt. Diese Schwierigkeiten, in der
Übersetzung teilweise geglättet, werden in den folgenden Anmerkungen
nicht ausdrücklich erwähnt.

[fn:3] [[file:2.Sam_7.org::v8][2 Sam 7,8-16]]

[fn:4] Ketten: Vielleicht ist ein Wort ausgefallen: einen
Vorhang an goldenen Ketten.

[fn:5] 23-28: Die Kerubim hatten wohl menschenähnliches
Aussehen. Die Bundeslade wurde zwischen sie gestellt (8,7), sodass sie
ihre Flügel über sie breiteten.

[fn:6] Der Monat Bul entspricht ungefähr unserem Oktober/November.
