#+TITLE: 1 Makk 10 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-27 Mo 12:59]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Makk 10.html

<<verses>>

<<v1>>
* Das Bündnisangebot des Demetrius I.: 10,1-14

1 Im Jahr 160 zog Alexander Epiphanes, der Sohn des Antiochus, gegen
Ptolemaïs und besetzte es. Die Einwohner nahmen ihn auf und er trat dort
die Herrschaft an. [fn:1]

<<v2>>
2 Als König Demetrius das hörte, sammelte er viele Truppen und zog gegen
ihn in den Kampf.

<<v3>>
3 An Jonatan schickte Demetrius einen Brief mit Friedensbeteuerungen und
versprach ihm hohe Würden.

<<v4>>
4 Denn er dachte: Wir wollen schnell mit ihm Frieden schließen, bevor er
sich mit Alexander gegen uns verbündet.

<<v5>>
5 Sonst erinnert er sich nämlich an all das Unheil, das wir ihm, seinen
Brüdern und seinem Volk angetan haben.

<<v6>>
6 Er gab Jonatan die Vollmacht, Truppen auszuheben und als seine
Verbündeten auszurüsten. Auch versprach er, die in der Burg von
Jerusalem festgehaltenen Geiseln freizulassen.

<<v7>>
7 Jonatan kam nach Jerusalem und las den Brief der ganzen Bevölkerung
und der Besatzung der Burg laut vor.

<<v8>>
8 Als sie hörten, dass er vom König die Vollmacht erhalten hatte,
Truppen auszuheben, bekamen sie große Angst.

<<v9>>
9 Die Besatzung der Burg lieferte dem Jonatan die Geiseln aus und er gab
sie ihren Eltern zurück.

<<v10>>
10 Jonatan ließ sich in Jerusalem nieder und begann in der Stadt mit
Bauarbeiten und Ausbesserungen.

<<v11>>
11 Er gab den Handwerkern den Auftrag, den Berg Zion und die Stadtmauern
mit Quadersteinen zu befestigen. Das führten sie auch aus. [fn:2]

<<v12>>
12 Darauf flohen die Fremden aus den Festungen, die Bakchides erbaut
hatte.

<<v13>>
13 Sie machten sich alle davon und kehrten nach Hause zurück.

<<v14>>
14 Nur in Bet-Zur blieben von denen, die vom Gesetz und von den Geboten
abgefallen waren, einige zurück; dort fanden sie nämlich Zuflucht.\\
\\

<<v15>>
* Die Einsetzung Jonatans zum Hohenpriester durch Alexander: 10,15-21

15 König Alexander erfuhr, was Demetrius Jonatan alles zugesichert
hatte. Man berichtete ihm auch von den Kriegen und den Heldentaten
Jonatans und seiner Brüder und von den zahlreichen Mühen, die sie auf
sich genommen hatten.

<<v16>>
16 Da sagte er: Können wir noch einmal solch einen Mann finden wie ihn?
Wir wollen ihn zu unserem Freund und Verbündeten machen.

<<v17>>
17 Er schrieb also einen Brief und schickte ihn an Jonatan. Der Brief
hatte folgenden Inhalt:

<<v18>>
18 König Alexander grüßt seinen Bruder Jonatan.

<<v19>>
19 Wir haben gehört, dass du ein tapferer Mann bist; du bist es wert,
unser Freund zu sein.

<<v20>>
20 Darum ernennen wir dich heute zum Hohenpriester über dein Volk; du
darfst den Titel Freund des Königs führen. Halte zu uns und bewahre uns
die Freundschaft! Zugleich übersandte er ihm den Purpurmantel und einen
goldenen Kranz. [fn:3]

<<v21>>
21 Im siebten Monat des Jahres 160 legte Jonatan am Laubhüttenfest das
heilige Gewand an. Er hob Truppen aus und verschaffte sich eine Menge
Waffen. [fn:4]\\
\\

<<v22>>
* Die Zugeständnisse des Demetrius I. an Jonatan: 10,22-45

22 Als Demetrius davon hörte, war er bestürzt. Er sagte: Was haben wir
da gemacht!

<<v23>>
23 Alexander ist uns zuvorgekommen. Er hat die Freundschaft der Juden
gewonnen, sodass sie ihn unterstützen.

<<v24>>
24 Doch ich will ihnen auch schreiben. Ich will ihnen gut zureden und
versprechen, sie auszuzeichnen und zu beschenken. Vielleicht werden sie
mich dann unterstützen.

<<v25>>
25 Er schrieb ihnen also folgenden Brief: König Demetrius grüßt das
jüdische Volk.

<<v26>>
26 Ihr habt die Verträge, die ihr mit uns geschlossen habt, gehalten,
habt uns die Freundschaft bewahrt und euch nicht unseren Feinden
angeschlossen. Wir haben es vernommen und uns darüber gefreut.

<<v27>>
27 Bleibt uns auch weiterhin treu! Wir werden euch das Gute vergelten,
das ihr uns erweist.

<<v28>>
28 Wir werden euch viele Verpflichtungen erlassen und euch Geschenke
machen.

<<v29>>
29 Von heute an erkläre ich euch für frei und erlasse allen Juden die
Kopfsteuer, die Salzsteuer und die Lieferung der Kränze. [fn:5]

<<v30>>
30 Von heute an verzichte ich für immer auf den dritten Teil der Erträge
der Felder und auf die Hälfte der Erträge der Bäume, die mir aus Judäa
zustehen sowie aus den drei Bezirken Samariens und Galiläas, die an
Judäa angeschlossen worden sind.

<<v31>>
31 Jerusalem sei heilig und unantastbar und soll mit seiner Umgebung vom
Zehnten und von der Steuer befreit sein.

<<v32>>
32 Ich verzichte auch auf die Befehlsgewalt über die Burg von Jerusalem.
Ich gestatte dem Hohenpriester, selbst die Männer auszuwählen, die er
als Wache in die Burg legen will.

<<v33>>
33 In meinem ganzen Reich lasse ich alle Juden, die als Gefangene aus
Judäa verschleppt worden sind, ohne Lösegeld frei. Auch ihre Tiere darf
niemand zum Frondienst heranziehen.

<<v34>>
34 An allen Festen, Sabbaten, Neumonden und Feiertagen sowie drei Tage
vor und nach einem Fest braucht kein Jude in meinem Reich Steuern oder
Schulden zu bezahlen.

<<v35>>
35 Niemand soll einen von ihnen in irgendeiner Sache belangen oder
belästigen dürfen.

<<v36>>
36 Bis zu dreißigtausend Juden sollen in das königliche Heer aufgenommen
werden und den gleichen Sold erhalten wie alle anderen Soldaten des
Königs.

<<v37>>
37 Sie sollen auch in den großen Festungen des Königs Dienst tun und
Vertrauensstellungen im Reich einnehmen. Ihre Offiziere und Befehlshaber
sind aus ihren eigenen Reihen zu wählen. Sie dürfen nach ihren eigenen
Gesetzen leben, ganz so, wie es der König für Judäa angeordnet hat.

<<v38>>
38 Die drei Bezirke, die von der Provinz Samarien abgetrennt und Judäa
angeschlossen worden sind, sollen unter gemeinsamer Verwaltung zu Judäa
gehören und nur dem Hohenpriester unterstellt sein. [fn:6]

<<v39>>
39 Ptolemaïs und das angrenzende Gebiet vermache ich als Geschenk dem
Tempel von Jerusalem; daraus soll der nötige Aufwand für den
Tempeldienst bestritten werden.

<<v40>>
40 Auf eigene Rechnung will ich aus geeigneten Orten jährlich
fünfzehntausend Silberschekel aufbringen.

<<v41>>
41 Alles, was die Behörden von den in den früheren Jahren üblichen
Zuwendungen noch nicht bezahlt haben, sollen sie von nun an für die
Arbeiten am Tempel zur Verfügung stellen.

<<v42>>
42 Auch die fünftausend Silberschekel, die bisher vom Jahresaufkommen
des Tempels als Steuer erhoben wurden, werden erlassen und sollen den
diensttuenden Priestern zukommen.

<<v43>>
43 Jeder, der sich in das Heiligtum von Jerusalem flüchtet oder in das
zum Tempel gehörende Gebiet, wird mit seinem ganzen Besitz, den er in
meinem Reich hat, von jeder Schuld dem König gegenüber und von jeder
anderen geschäftlichen Verpflichtung frei sein.

<<v44>>
44 Die Kosten für die Arbeiten am Heiligtum, sowohl für Neubauten wie
für Ausbesserungen, gehen zu Lasten des Königs,

<<v45>>
45 ebenso gehen die Kosten für den Bau der Mauern in Jerusalem und für
die Stadtmauern, die es umgeben, auf die Rechnung des Königs,
schließlich auch die Mauerbauten in Judäa.\\
\\

<<v46>>
* Das Bündnis zwischen Jonatan und Alexander: 10,46-66

46 Als Jonatan und das Volk diese Versprechungen hörten, glaubten sie
ihnen nicht und gingen nicht darauf ein; denn sie dachten an das große
Unheil, das er in Israel angerichtet, und in welche Not er sie gebracht
hatte.

<<v47>>
47 Sie hielten zu Alexander, weil er ihnen zuerst Frieden angeboten
hatte, und sie kämpften die ganze Zeit auf seiner Seite.

<<v48>>
48 König Alexander zog große Truppenmassen zusammen und schlug Demetrius
gegenüber sein Lager auf.

<<v49>>
49 Die beiden Könige eröffneten den Kampf gegeneinander. Das Heer des
Demetrius floh; Alexander setzte ihm nach und gewann die Oberhand.

<<v50>>
50 Er kämpfte hartnäckig, bis die Sonne unterging. An jenem Tag fiel
Demetrius in der Schlacht.

<<v51>>
51 Alexander schickte Gesandte zu Ptolemäus, dem König von Ägypten, und
ließ ihm folgendes sagen:

<<v52>>
52 Ich bin in mein Reich zurückgekehrt, habe mich auf den Thron meiner
Väter gesetzt und die Herrschaft angetreten. Ich habe Demetrius besiegt
und unser Land in meine Gewalt gebracht.

<<v53>>
53 Ich habe mit ihm gekämpft; er wurde mit seinem Heer von uns
vernichtend geschlagen. So haben wir uns auf den Thron seines Reiches
gesetzt.

<<v54>>
54 Lasst uns nun miteinander Freundschaft schließen. Gib mir deine
Tochter zur Frau, damit wir uns durch diese Heirat miteinander
verschwägern. Ich werde dir und ihr Geschenke machen, die deiner würdig
sind.

<<v55>>
55 König Ptolemäus antwortete: Welch glücklicher Tag, an dem du in das
Land deiner Väter zurückgekehrt bist und dich auf den Thron ihres
Reiches gesetzt hast.

<<v56>>
56 Ich will auf deinen Vorschlag eingehen. Doch komm mir bis Ptolemaïs
entgegen, damit wir uns kennen lernen. Dann werde ich mich mit dir
verschwägern, wie du geschrieben hast.

<<v57>>
57 Ptolemäus verließ Ägypten und nahm seine Tochter Kleopatra mit sich.
Im Jahr 162 kam er nach Ptolemaïs. [fn:7]

<<v58>>
58 Als König Alexander mit ihm zusammenkam, gab er ihm seine Tochter zur
Frau. Er veranstaltete in Ptolemaïs eine glänzende Hochzeit für sie, wie
es bei Königen üblich ist.

<<v59>>
59 König Alexander schrieb an Jonatan, er möge doch zu ihm kommen und
sich mit ihm treffen.

<<v60>>
60 Da begab sich Jonatan mit glänzendem Gefolge nach Ptolemaïs und traf
dort die beiden Könige. Er brachte ihnen und ihren Freunden Silber, Gold
und viele Geschenke mit. So gewann er sie für sich.

<<v61>>
61 Aber ehrlose Männer aus Israel, Verräter, traten gemeinsam auf und
klagten ihn an. Doch der König schenkte ihnen keine Beachtung.

<<v62>>
62 Vielmehr gab er die Anweisung, Jonatan anstelle der Gewänder, die er
trug, mit Purpur zu bekleiden. Das geschah

<<v63>>
63 und der König ließ ihn neben sich Platz nehmen. Dann sagte er zu
seinen höchsten Beamten: Nehmt ihn mit in die Stadt und gebt bekannt,
dass niemand ihn in irgendeiner Sache anklagen darf; keiner darf ihm aus
irgendeinem Grund Ungelegenheiten bereiten.

<<v64>>
64 Als die Ankläger sahen, dass er öffentlich geehrt wurde und mit
Purpur bekleidet war, machten sie sich alle davon.

<<v65>>
65 Der König ließ Jonatan noch weitere Ehrungen zukommen: Er ließ ihn in
das Verzeichnis seiner ersten Freunde aufnehmen und ernannte ihn zum
Befehlshaber und Statthalter.

<<v66>>
66 Darauf kehrte Jonatan in Frieden und voll Freude nach Jerusalem
zurück.\\
\\

<<v67>>
* Sieg Jonatans über ein Heer des Demetrius II.: 10,67-89

67 Im Jahr 165 kam Demetrius, der Sohn des Demetrius, aus Kreta in das
Land seiner Väter.

<<v68>>
68 Als König Alexander das hörte, war er sehr bestürzt und kehrte nach
Antiochia zurück.

<<v69>>
69 Demetrius ernannte Apollonius zum Statthalter von Zölesyrien. Dieser
brachte ein großes Heer zusammen und schlug sein Lager bei Jamnia auf.
Von dort schickte er dem Hohenpriester Jonatan diese Botschaft:

<<v70>>
70 Nur du allein stellst dich gegen uns. Deinetwegen verlacht und
verhöhnt man mich. Was maßt du dir uns gegenüber an in deinen Bergen?

<<v71>>
71 Wenn du dich auf deine Truppen verlassen kannst, dann komm doch
herunter zu uns in die Ebene; dort wollen wir unsere Kräfte messen. Denn
bei mir befinden sich die Truppen aus den Städten.

<<v72>>
72 Frag doch nach und erkundige dich, wer ich bin und wer die Leute
sind, die auf meiner Seite stehen. Man wird dir sagen, dass ihr uns
nicht standhalten könnt. Schon zweimal wurden deine Vorfahren in ihrem
Land in die Flucht geschlagen. [fn:8]

<<v73>>
73 In der Ebene wirst du dich auch diesmal gegen die Reiterei und gegen
eine solche Streitmacht nicht halten können; da gibt es nämlich keinen
Stein und keinen Kiesel und auch keinen Schlupfwinkel, in den man
fliehen kann.

<<v74>>
74 Als Jonatan die Worte des Apollonius vernahm, war er empört und
rückte mit zehntausend Mann aus Jerusalem aus. Sein Bruder Simeon ging
zu seiner Unterstützung mit.

<<v75>>
75 Vor Jafo schlug er sein Lager auf. Die Einwohner der Stadt
verschlossen die Tore vor ihm; denn Apollonius hatte eine Besatzung nach
Jafo gelegt. Als die Juden aber angriffen,

<<v76>>
76 bekamen die Einwohner Angst und übergaben die Stadt und Jonatan nahm
Jafo in Besitz.

<<v77>>
77 Das erfuhr Apollonius, der mit dreitausend Reitern und einem großen
Heer ein Lager bezogen hatte. Er zog auf Aschdod zu, als wolle er durch
die Stadt ziehen. Zugleich rückte er in die Ebene vor, weil er sich auf
seine starke Reiterei verließ.

<<v78>>
78 Jonatan aber setzte ihm nach bis vor Aschdod. Dort gerieten die Heere
aneinander.

<<v79>>
79 Apollonius hatte tausend Reiter in einem Hinterhalt zurückgelassen.

<<v80>>
80 Jonatan bemerkte den Hinterhalt, aber die Reiter umzingelten sein
Heer und schossen vom frühen Morgen bis zum Abend mit Pfeilen auf seine
Leute.

<<v81>>
81 Aber die Männer hielten stand, wie Jonatan befohlen hatte, und die
Pferde der Feinde wurden müde.

<<v82>>
82 Dann ließ Simeon seine Streitkräfte ausschwärmen und griff die
feindlichen Fußtruppen an. Da die Reiterei erschöpft war, wurde das Heer
von ihm in die Flucht geschlagen.

<<v83>>
83 Die Reiterei wurde über die ganze Ebene hin zersprengt und floh nach
Aschdod; sie gingen in den Tempel Dagons, ihres Götzenbildes, um sich zu
retten. [fn:9]

<<v84>>
84 Jonatan steckte Aschdod und die Nachbarorte in Brand und plünderte
sie; er brannte auch den Tempel des Dagon nieder mit allen, die sich
dorthin geflüchtet hatten.

<<v85>>
85 Es waren etwa achttausend Mann, die durch das Schwert oder im Feuer
umkamen.

<<v86>>
86 Von dort brach Jonatan auf und schlug sein Lager bei Aschkelon auf.
Die Einwohner kamen ihm in einem festlichen Zug aus der Stadt entgegen.

<<v87>>
87 Dann kehrten Jonatan und seine Leute mit großer Beute nach Jerusalem
zurück.

<<v88>>
88 Als König Alexander davon hörte, erwies er ihm noch weitere Ehren.

<<v89>>
89 Er übersandte ihm eine goldene Spange, wie man sie Angehörigen der
königlichen Familie verleiht; auch übergab er ihm die Stadt Ekron mit
ihrem ganzen Gebiet zum Besitz. [fn:10]\\
\\

* Footnotes

[fn:1] Alexander hieß in Wirklichkeit Balas; er gab sich als
Sohn des Epiphanes aus und hatte mit dieser Täuschung Erfolg. - Zu
Ptolemaïs: vgl. die Anmerkung zu 5,15.

[fn:2] [[file:2.Sam_5.org::v9][2 Sam 5,9]]

[fn:3] So vereinigt Jonatan das Amt des Hohenpriesters, des
weltlichen Oberhauptes und des Heerführers in seiner Person.

[fn:4] Nach der griechisch-seleuzidischen Zeitrechnung, d.h. 152 v. Chr.

[fn:5] Unter «Kränzen» verstand man Geschenke, die dem
Herrscher gemacht wurden.

[fn:6] [[v31][10,31]]; [[file:1.Makk_11.org::v28][11,28]]-[[file:1.Makk_11.org::v34][34]]

[fn:7] 57f: Kleopatra: Tochter des Ptolemäus VI. Philometor.

[fn:8] [[file:1.Sam_4.org::v1][1 Sam 4,1]]-[[file:1.Sam_4.org::v11][11]]

[fn:9] [[file:1.Sam_5.org::v1][1 Sam 5,1]]-[[file:1.Sam_5.org::v5][5]]

[fn:10] Die «Angehörigen der königlichen Familie» sind eine
Ehrenklasse, die höher als die «Freunde des Königs» stehen.
