#+TITLE: 1 Makk 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-26 So 15:39]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Makk 4.html

<<verses>>

<<v1>>
* Der Sieg über Gorgias: 4,1-25

1 Gorgias aber nahm eine Abteilung von fünftausend Mann und tausend
ausgesuchten Reitern und brach mit ihnen in der Nacht auf. [fn:1]

<<v2>>
2 Er wollte nämlich das jüdische Heer überfallen und überraschend
schlagen; Leute aus der Burg zeigten ihm den Weg. [fn:2]

<<v3>>
3 Doch Judas erfuhr davon und brach selbst mit seinen Männern auf, um
das Lager der königlichen Streitkräfte vor Emmaus anzugreifen,

<<v4>>
4 solange die anderen Truppen vom Lager getrennt waren.

<<v5>>
5 Gorgias erreichte noch in der Nacht das Lager der Juden, fand aber
niemand. Daher suchte er sie in den Bergen, denn er dachte: Sie sind vor
uns geflohen.

<<v6>>
6 Bei Tagesanbruch erschien Judas mit dreitausend Mann in der Ebene.
Doch sie waren nicht so ausgerüstet und bewaffnet, wie sie es wünschten.

<<v7>>
7 Als sie das Kriegslager der fremden Völker sahen, das stark, fest
gebaut und ringsum von Reiterei umgeben war - lauter gut ausgebildete
Soldaten -,

<<v8>>
8 da sagte Judas zu seinen Männern: Habt keine Angst vor ihrer Übermacht
und fürchtet euch nicht vor ihrer Kampfkraft!

<<v9>>
9 Denkt daran, wie unsere Väter im Roten Meer gerettet wurden, als der
Pharao sie mit seinem Heer verfolgte.

<<v10>>
10 Lasst uns den Himmel anrufen, dass er uns gewogen ist und des Bundes
mit unseren Vätern gedenkt und dass er dieses Heer heute vor unseren
Augen vernichtend schlägt.

<<v11>>
11 Dann werden alle Völker erkennen, dass es einen gibt, der Israel
loskauft und rettet.

<<v12>>
12 Als die fremden Soldaten aufblickten, sahen sie die Juden
heranrücken.

<<v13>>
13 Da kamen sie aus ihrem Lager heraus, um zu kämpfen; die Männer des
Judas aber bliesen die Widderhörner.

<<v14>>
14 Die beiden Heere stießen aufeinander und die fremden Völker wurden
vernichtend geschlagen und flohen in die Ebene.

<<v15>>
15 Alle, die nicht schnell genug waren, fielen unter dem Schwert. Die
Juden verfolgten sie bis nach Geser und in die Ebene von Idumäa, Aschdod
und Jamnia und erschlugen ungefähr dreitausend von ihnen.

<<v16>>
16 Dann hörte Judas mit seinen Leuten auf, sie zu verfolgen, und kehrte
um.

<<v17>>
17 Er sagte zu seinen Männern: Fallt noch nicht über die Beute her; denn
uns steht noch ein Kampf bevor.

<<v18>>
18 Gorgias steht mit seinen Truppen dicht vor uns in den Bergen. Stellt
euch also zum Kampf gegen eure Feinde auf und greift sie an; nachher
könnt ihr in aller Ruhe eure Beute holen.

<<v19>>
19 Während Judas noch sprach, sah man eine Abteilung der Feinde hinter
dem Berg auftauchen.

<<v20>>
20 Als sie merkten, dass ihre Leute geschlagen waren und die Juden das
Lager angezündet hatten - der weithin sichtbare Rauch zeigte an, was
geschehen war -,

<<v21>>
21 bekamen sie bei diesem Anblick große Angst. Als sie außerdem sahen,
dass das Heer des Judas kampfbereit in der Ebene stand,

<<v22>>
22 flohen sie alle ins Land der Philister.

<<v23>>
23 Jetzt erst machte sich Judas an die Plünderung des Lagers. Sie
erbeuteten viel Gold und Silber, violette und rote Purpurstoffe und
andere reiche Schätze.

<<v24>>
24 Auf dem Rückmarsch priesen und lobten sie den Himmel: «Denn er ist
gütig, denn seine Huld währt ewig». [fn:3]

<<v25>>
25 So wurde Israel an jenem Tag wunderbar gerettet.\\
\\

<<v26>>
* Der erste Angriff des königlichen Heeres unter Lysias: 4,26-35

26 Die Philister, die sich hatten retten können, kamen zu Lysias und
meldeten ihm, was geschehen war. [fn:4]

<<v27>>
27 Auf diese Nachricht hin war er bestürzt und in großer Sorge. Denn der
Feldzug gegen Israel war nicht so verlaufen, wie er es gewollt hatte;
der Auftrag des Königs war nicht ausgeführt worden.

<<v28>>
28 Darum warb er im nächsten Jahr sechzigtausend Söldner an, ausgesuchte
Männer, dazu fünftausend Reiter, um wieder gegen die Juden zu Felde zu
ziehen.

<<v29>>
29 Sie zogen nach Idumäa und schlugen in Bet-Zur ihr Lager auf. Judas
aber kam ihnen mit zehntausend Mann entgegen. [fn:5]

<<v30>>
30 Als Judas das gewaltige Heerlager der Feinde erblickte, sprach er
folgendes Gebet: Gepriesen seist du, Retter Israels. Du hast den
wütenden Riesen durch deinen Knecht David erschlagen; du hast das
Kriegslager der Philister Jonatan, dem Sohn Sauls, und seinem
Waffenträger in die Hand gegeben. [fn:6]

<<v31>>
31 Gib dieses Heer deinem Volk Israel preis! Sie sollen beschämt werden
samt ihrem Fußvolk und ihrer Reiterei.

<<v32>>
32 Jag ihnen einen Schrecken ein und lass ihren kühnen Mut schwinden!
Ihr Untergang soll sie erschüttern.

<<v33>>
33 Schlag sie nieder durch das Schwert derer, die dich lieben. Dann
werden alle, die deinen Namen kennen, dein Lob singen.

<<v34>>
34 Als nun die Heere aufeinanderstießen, fielen etwa fünftausend von den
Soldaten des Lysias.

<<v35>>
35 Als Lysias sah, welche Niederlage sein Heer erlitten hatte und wie
kühn die Leute des Judas waren, bereit tapfer zu leben oder zu sterben,
kehrte er nach Antiochia zurück. Dort warb er Söldner an, um mit noch
stärkerer Macht noch einmal gegen Judäa zu ziehen.\\
\\

<<v36>>
* Die Reinigung und Weihe des Tempels: 4,36-61

36 Judas und seine Brüder aber sagten: Unsere Feinde sind nun
vernichtend geschlagen. Wir wollen nach Jerusalem hinaufziehen, den
Tempel reinigen und ihn neu weihen. [fn:7]

<<v37>>
37 Das ganze Heer versammelte sich also und zog zum Berg Zion hinauf.

<<v38>>
38 Da sahen sie das Heiligtum verödet daliegen. Der Brandopferaltar war
entweiht; die Tore hatte man verbrannt. In den Vorhöfen wuchs Unkraut
wie in einem Wald oder auf einem Berg und die Nebengebäude waren
verfallen. [fn:8]

<<v39>>
39 Da zerrissen sie ihre Gewänder, begannen laut zu klagen und streuten
sich Staub auf das Haupt.

<<v40>>
40 Sie warfen sich nieder, mit dem Gesicht zur Erde. Sie bliesen die
Signaltrompeten und schrien zum Himmel.

<<v41>>
41 Dann befahl Judas einer Schar seiner Männer, die Besatzung der Burg
zu belagern, bis das Heiligtum gereinigt sei.

<<v42>>
42 Er wählte untadelige und gesetzestreue Priester aus,

<<v43>>
43 damit sie das Heiligtum reinigten und die entweihten Steine an einen
unreinen Ort trugen.

<<v44>>
44 Sie berieten, was sie mit dem entweihten Brandopferaltar tun sollten. [fn:9]

<<v45>>
45 Es kam ihnen der gute Gedanke, ihn niederzureißen; denn er hätte
ihnen Schande gebracht, da die fremden Völker ihn entweiht hatten. So
rissen sie den Altar nieder

<<v46>>
46 und legten die Steine an einen passenden Ort auf dem Tempelberg
nieder, bis ein Prophet komme und entscheide, was damit geschehen solle. [fn:10] [fn:11]

<<v47>>
47 Dann nahmen sie unbehauene Steine, wie es das Gesetz vorschreibt, und
errichteten einen neuen Altar, der genauso aussah wie der alte. [fn:12]

<<v48>>
48 Auch das Heiligtum und die Innenräume des Tempels bauten sie wieder
auf und reinigten die Vorhöfe.

<<v49>>
49 Sie fertigten neue heilige Geräte an und stellten den Leuchter, den
Rauchopferaltar und den Tisch in den Tempel. [fn:13]

<<v50>>
50 Dann brachten sie auf dem Altar ein Rauchopfer dar, zündeten die
Lichter an dem Leuchter an, sodass der Tempel hell wurde,

<<v51>>
51 legten Schaubrote auf den Tisch und hängten den Vorhang auf. So
beendeten sie alle Arbeiten, die sie sich vorgenommen hatten.

<<v52>>
52 Am Fünfundzwanzigsten des neunten Monats - das ist der Monat Kislew
im Jahr 148 standen sie früh am Morgen auf

<<v53>>
53 und brachten auf dem neuen Brandopferaltar, den sie errichtet hatten,
Opfer dar, so wie sie das Gesetz vorschreibt.

<<v54>>
54 Zur gleichen Zeit und am selben Tag, an dem ihn die fremden Völker
entweiht hatten, wurde er neu geweiht, unter Liedern, Zither- und
Harfenspiel und dem Klang der Zimbeln.

<<v55>>
55 Das ganze Volk warf sich nieder auf das Gesicht, sie beteten an und
priesen den Himmel, der ihnen Erfolg geschenkt hatte.

<<v56>>
56 Acht Tage lang feierten sie die Altarweihe, brachten mit Freuden
Brandopfer dar und schlachteten Heils- und Dankopfer.

<<v57>>
57 Sie schmückten die Vorderseite des Tempels mit Kränzen und kleinen
Schilden aus Gold; sie erneuerten die Tore und auch die Nebengebäude,
die sie wieder mit Türen versahen.

<<v58>>
58 Im Volk herrschte sehr große Freude; denn die Schande, die ihnen die
fremden Völker zugefügt hatten, war beseitigt.

<<v59>>
59 Judas fasste mit seinen Brüdern und mit der ganzen Gemeinde Israels
den Beschluss, Jahr für Jahr zur selben Zeit mit festlichem Jubel die
Tage der Altarweihe zu begehen, und zwar acht Tage lang, vom
fünfundzwanzigsten Kislew an. [fn:14]

<<v60>>
60 In jener Zeit errichteten sie rund um den Zionsberg auch hohe Mauern
mit festen Türmen, damit die fremden Völker nicht mehr in dieses Gebiet
eindringen und es entweihen konnten, wie sie es vorher getan hatten.

<<v61>>
61 Und Judas ordnete Truppen ab, um ihn zu bewachen. Auch Bet-Zur ließ
er befestigen und legte eine Besatzung hinein, um das Volk gegen Idumäa
abzusichern.\\
\\

* Footnotes

[fn:1] (1-25) [[file:2.Makk_8.org::v23][2 Makk 8,23]]-[[file:2.Makk_8.org::v29][29]]

[fn:2] [[file:1.Makk_1.org::v33][1,33]]

[fn:3] [[file:Ps_118.org::v1][Ps 118,1]]

[fn:4] (26-35) [[file:2.Makk_11.org::v1][2 Makk 11,1]]-[[file:2.Makk_11.org::v12][12]]

[fn:5] Bet-Zur ist ein Ort an der Südgrenze von Judäa und liegt
an der Straße von Jerusalem nach Hebron.

[fn:6] [[file:1.Sam_17.org][1 Sam 17]]; [[file:1.Sam_14.org::v1][14,1]]-[[file:1.Sam_14.org::v23][23]]

[fn:7] (36-61) [[file:2.Makk_10.org::v1][2 Makk 10,1]]-[[file:2.Makk_10.org::v8][8]]

[fn:8] [[file:Ps_74.org::v2][Ps 74,2]]-[[file:Ps_74.org::v7][7]]

[fn:9] [[file:1.Makk_1.org::v54][1,54]]

[fn:10] [[file:1.Makk_14.org::v41][14,41]]

[fn:11] Auch sonst ist die Rede davon, dass die Prophetie
unterbrochen ist: [[file:1.Makk_9.org::v27][9,27]]; vgl. [[file:Ps_74.org::v9][Ps 74,9]]; [[file:Klgl_2.org::v9][Klgl 2,9]]; [[file:Ez_7.org::v26][Ez 7,26]].

[fn:12] [[file:Ex_20.org::v25][Ex 20,25]]

[fn:13] [[file:Ex_37.org::v10][Ex 37,10]]-[[file:Ex_37.org::v29][29]]

[fn:14] Das Tempelweihfest (Hanukka) ist eines der jüngsten
Feste im Kalender Israels.
