#+TITLE: 1 Makk 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-25 Sa 23:03]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Makk 1.html

* Die Bücher der Makkabäer

Die beiden Makkabäer-Bücher gehören nicht zum hebräischen Alten
Testament, sondern zu den sog. deuterokanonischen, nur griechisch
überlieferten Büchern der Bibel. Den Hauptinhalt der beiden Bücher
bilden die Kämpfe der Juden gegen die Seleuziden im 2. Jahrhundert v.
Chr. Sie werden unternommen, um die religiöse und politische Freiheit
des jüdischen Volkes wiederzugewinnen. Benannt sind die Bücher nach dem
Ehrennamen Makkaba (= Hämmerer), der Judas, dem Haupthelden dieser
Kämpfe, und später auch seinen Brüdern beigelegt wurde.\\
\\
Das 1. Buch der Makkabäer berichtet über die Zeit von 175 bis 134 v.
Chr., vor allem über das Vorhaben des Seleuziden Antiochus Epiphanes,
der mit Hilfe jüdischer Parteigänger den Tempel entweiht und dem
jüdischen Volk griechische Lebensweise aufzwingen will (Kap. 1). Dagegen
erhebt sich Mattatias, der zum Heiligen Krieg aufruft (Kap. 2). Den
Hauptteil des Buches nimmt die Schilderung der militärischen
Unternehmungen der drei Söhne des Mattatias, Judas, Jonatan und Simeon,
ein. Judas gelingt es, 165 v. Chr. den Tempel wieder einzuweihen und den
Opferdienst erneut in Gang zu setzen. Er sucht ein Bündnis mit den
Römern (3,1 - 9,22). Jonatan (161-143) wird zum Hohenpriester ernannt
und bemüht sich um die Verbindung mit Rom und Sparta (9,23 - 12,52).
Simeon (143-135), von den Seleuziden Demetrius II. und Antiochus VII.
anerkannt, erhält das Doppelamt des Hohenpriesters und Fürsten in
Israel; unter ihm lebt das Volk in Frieden und Wohlstand (Kap. 13 -
16).\\
\\
Das 1. Buch der Makkabäer war ursprünglich hebräisch abgefasst; erhalten
ist es nur in griechischer Übersetzung. Sein Verfasser ist ein
palästinensischer Jude, der wohl gegen 100 v. Chr., sicher vor der
Eroberung Jerusalems durch Pompeius (63 v. Chr.), sein Werk geschaffen
hat. Er steht in der Glaubensüberlieferung seines Volkes und schreibt
religiös gedeutete Geschichte. Im Unglück des Volkes sieht er die Strafe
für Schuld und Vergehen; nur im Einklang mit der Offenbarung und in
Treue zu ihr vermag das jüdische Volk die Feinde zu besiegen, die
nationale Selbständigkeit zu erlangen und so der Gottesherrschaft den
Weg zu bereiten. Dabei ist der Verfasser ein entschiedener Gegner jeder
Anpassung; er lehnt alle Hellenisierungsbestrebungen ab. Voll
Bewunderung blickt er auf den Kampf seines Volkes für Gesetz und Tempel
in seiner ruhmreichen Geschichte zurück.\\
\\
Das 2. Buch der Makkabäer ist nicht, wie man erwarten könnte, die
Fortsetzung von 1 Makk, vielmehr eine ausgestaltende Parallele (Kap. 1 -
8 und 11 - 13) zu den Berichten von 1 Makk 1 - 7. Auch in der
literarischen Gattung ist ein beachtlicher Unterschied festzustellen.
Ursprünglich griechisch abgefasst, stellt 2 Makk sich selbst als Auszug
aus einem größeren Werk des Jason von Zyrene dar (2,19-32). Der
Verfasser schreibt in einem belehrenden Stil und zeigt sich mit
griechischen Persönlichkeiten und Einrichtungen bestens vertraut. Viel
betonter als in 1 Makk ist der Rückbezug der Geschichte auf Gott
geschildert. Die ganze Sympathie des Verfassers gilt Judas dem
Makkabäer. Selbst die Verfolgung ist ihm ein Zeichen der göttlichen
Barmherzigkeit, die das Volk auf den rechten Weg zurückführen will.\\
\\
Das Buch richtet sich an die Juden in Alexandria, um sie für das
Geschick ihres Volkes in der Heimat, vor allem für den Tempel und die
heiligen Schriften zu interessieren. Dieser Absicht dient der Aufbau des
Buches: Nach dem schrecklichen Tod des Antiochus folgt die Einsetzung
des Tempelweihfestes (9,1 - 10,8). Der zweite Teil ist vergleichbar
gestaltet: Nach dem Tod Nikanors, der den Tempel bedroht, wird ein
Einweihungsfest beschlossen (Kap. 14 und 15).\\
\\
Das 2. Makkabäerbuch dürfte nach 160 v. Chr. entstanden sein. Wenn auch
die Herkunft und Zuverlässigkeit mancher Berichte nicht nachprüfbar ist
und der Verfasser seine Darstellung ausgeschmückt hat (vgl. 2,29), so
ist die historische Treue nicht zu gering einzuschätzen; sie wird
weithin durch Parallelen in 1 Makk bestätigt. Das Buch ist vor allem
wegen seiner fortgeschrittenen Lehre über die Auferstehung der Toten,
über das Gebet für die Verstorbenen, über die Verdienste der Märtyrer
und die Fürbitte der Heiligen bedeutsam. Diese theologischen Aussagen
begründen und rechtfertigen die Stellung des Buches im
alttestamentlichen Kanon.\\
\\

<<verses>>

<<v1>>

* Die Verfolgung des Volkes Israel: 1,1-64

* Der Beginn der griechischen Herrschaft: 1,1-10

Der Mazedonier Alexander, Sohn des Philippus, zog damals vom Land der
Kittäer aus. Er besiegte Darius, den König der Perser und Meder, und
wurde als erster König von Griechenland sein Nachfolger. [fn:1]

<<v2>>
2 Er führte viele Kriege, eroberte zahlreiche Festungen und ließ die
Könige der Erde erschlagen;

<<v3>>
3 er kam bis an das Ende der Welt, plünderte viele Völker aus und die
ganze Erde lag ihm wehrlos zu Füßen. Da wurde sein Herz stolz und
überheblich.

<<v4>>
4 Er stellte ein sehr großes Heer auf, herrschte über Länder, Völker und
Fürsten und machte sie sich tributpflichtig.

<<v5>>
5 Doch dann sank er aufs Krankenlager und fühlte seinen Tod nahen.

<<v6>>
6 Er rief seine höchsten Offiziere zusammen, die mit ihm aufgewachsen
waren, und verteilte sein Reich unter sie, solange er noch lebte.

<<v7>>
7 Zwölf Jahre hatte Alexander regiert, als er starb. [fn:2]

<<v8>>
8 Seine Offiziere übernahmen die Regierung, jeder in seinem Bereich.

<<v9>>
9 Nach seinem Tod setzten sich alle die Königskrone auf; ebenso hielten
es ihre Nachkommen lange Zeit hindurch. Sie brachten großes Unglück über
die Erde.

<<v10>>
10 Aus ihnen ging ein besonders gottloser Spross hervor, Antiochus
Epiphanes, der Sohn des Königs Antiochus. Er war als Geisel in Rom
gewesen und trat im Jahr 137 der griechischen Herrschaft die Regierung
an. [fn:3] [fn:4]\\
\\

<<v11>>
* Das Aufkommen der Verräter: 1,11-15

11 Zu dieser Zeit traten Verräter am Gesetz in Israel auf, die viele
(zum Abfall) überredeten. Sie sagten: Wir wollen einen Bund mit den
fremden Völkern schließen, die rings um uns herum leben; denn seit wir
uns von ihnen abgesondert haben, geht es uns schlecht. [fn:5]

<<v12>>
12 Dieser Vorschlag gefiel ihnen

<<v13>>
13 und einige aus dem Volk fanden sich bereit, zum König zu gehen. Der
König gab ihnen die Erlaubnis, nach den Gesetzen der fremden Völker zu
leben.

<<v14>>
14 Sie errichteten in Jerusalem eine Sportschule, wie es bei den fremden
Völkern Brauch ist,

<<v15>>
15 und ließen bei sich die Beschneidung rückgängig machen. So fielen sie
vom heiligen Bund ab, vermischten sich mit den fremden Völkern und gaben
sich dazu her, Böses zu tun.\\
\\

<<v16>>
* Der Angriff der Heiden auf den Tempel: 1,16-28

16 Als Antiochus sah, dass sich seine Herrschaft gefestigt hatte, fasste
er den Plan, auch König von Ägypten zu werden und so über zwei Reiche zu
herrschen. [fn:6]

<<v17>>
17 Er drang mit vielen Soldaten in Ägypten ein, mit Streitwagen und
Kriegselefanten, mit Reitern und einer großen Flotte, [fn:7]

<<v18>>
18 und führte Krieg gegen Ptolemäus, den König von Ägypten. Ptolemäus
wurde von ihm geschlagen und musste fliehen, nachdem viele seiner Leute
im Kampf gefallen waren.

<<v19>>
19 Die befestigten Städte Ägyptens wurden erobert und das Land
geplündert.

<<v20>>
20 Antiochus wandte sich nach seinem Sieg über Ägypten im Jahr 143 gegen
Israel und rückte mit zahlreichen Truppen hinauf vor Jerusalem.

<<v21>>
21 In seiner Vermessenheit betrat er sogar das Heiligtum; er raubte den
goldenen Rauchopferaltar, den Leuchter samt seinem Zubehör,

<<v22>>
22 den Tisch für die Schaubrote, die Opfer- und Trinkschalen, die
goldenen Rauchfässer, den Vorhang, die Kronen und den goldenen Schmuck
von der Vorderseite des Tempels. Von allem ließ er das Gold abschlagen.

<<v23>>
23 Dann nahm er das Silber, das Gold, die kostbaren Geräte, und was er
von den versteckten Schätzen finden konnte,

<<v24>>
24 und ließ alles in sein Land schleppen. Er richtete ein Blutbad an und
führte ganz vermessene Reden.

<<v25>>
25 Da kam große Trauer über das ganze Land Israel.\\
\\

<<v26>>
26 Die Vornehmen und Alten stöhnten; /\\
 die Mädchen und jungen Männer verloren ihre Kraft /\\
 und die Schönheit der Frauen verfiel.\\
\\

<<v27>>
27 Jeder Bräutigam stimmte die Totenklage an, /\\
 die Braut saß trauernd in ihrem Gemach.\\
\\

<<v28>>
28 Das Land zitterte um seine Bewohner. /\\
 Das ganze Haus Jakob war mit Schande bedeckt.\\
\\

<<v29>>
* Die Verwüstung der Stadt Jerusalem: 1,29-40

29 Zwei Jahre später schickte der König einen Beamten in die Städte von
Judäa mit dem Auftrag, die Steuern einzutreiben. Er kam mit zahlreichen
Truppen nach Jerusalem. [fn:8]

<<v30>>
30 Hinterlistig bot er den Einwohnern zunächst Frieden an. Als man ihm
Glauben schenkte, fiel er plötzlich über die Stadt her, richtete großen
Schaden in ihr an und brachte viele Israeliten um.

<<v31>>
31 Er ließ die Stadt plündern und in Brand stecken und die Häuser und
Stadtmauern ringsum niederreißen.

<<v32>>
32 Frauen und Kinder schleppte man in die Sklaverei und ihren Besitz
nahm man als Beute mit.

<<v33>>
33 Um die Davidstadt bauten sie eine hohe und feste Mauer mit mächtigen
Türmen, damit sie ihnen als Burg dienen konnte.

<<v34>>
34 Sie legten eine heidnische Besatzung hinein, Männer, die sich nicht
an das Gesetz hielten. Diese setzten sich dort fest,

<<v35>>
35 versahen sich mit Waffen und Proviant und brachten auch die Beute,
die sie in Jerusalem gemacht hatten, dort unter. So wurden sie zu einer
großen Gefahr.\\
\\

<<v36>>
36 Aus dem Hinterhalt bedrohten sie das Heiligtum; /\\
 immer waren sie für Israel ein schlimmer Feind.\\
\\

<<v37>>
37 Rings um den Tempel vergossen sie unschuldiges Blut /\\
 und entweihten die heilige Stätte.\\
\\

<<v38>>
38 Jerusalems Einwohner flohen vor ihnen /\\
 und Ausländer zogen in die Stadt ein. /\\
 Ihren eigenen Kindern wurde die Stadt fremd /\\
 und ihre Söhne verließen sie.\\
\\

<<v39>>
39 Ihr Heiligtum wurde leer wie die Wüste, /\\
 ihre Feste verwandelten sich in Trauer. /\\
 Ihre Sabbate wurden verhöhnt; /\\
 statt geehrt zu sein, war sie verachtet.\\
\\

<<v40>>
40 So groß ihre Herrlichkeit gewesen war, /\\
 so groß war nun ihre Schande. /\\
 Von ihrer Höhe ist sie herabgestürzt, /\\
 jetzt liegt sie in Trauer.\\
\\

<<v41>>
* Die Verfolgung der treuen Israeliten: 1,41-64

41 Damals schrieb der König seinem ganzen Reich vor, alle sollen zu
einem einzigen Volk werden [fn:9]

<<v42>>
42 und jeder solle seine Eigenart aufgeben. Alle Völker fügten sich dem
Erlass des Königs.

<<v43>>
43 Auch vielen Männern aus Israel gefiel der Gottesdienst, den er
angeordnet hatte; sie opferten den Götterbildern und entweihten den
Sabbat.

<<v44>>
44 Der König schickte Boten nach Jerusalem und in die Städte Judäas mit
der schriftlichen Anordnung, man solle eine Lebensform übernehmen, die
dem Land fremd war. [fn:10]

<<v45>>
45 Brand-, Schlacht- und Trankopfer im Heiligtum seien einzustellen,
Sabbate und Feste zu entweihen, [fn:11]

<<v46>>
46 das Heiligtum und die Heiligen zu schänden.

<<v47>>
47 Man solle statt dessen Altäre, Heiligtümer und Tempel für die fremden
Götter errichten sowie Schweine und andere unreine Tiere opfern.

<<v48>>
48 Ihre Söhne dürften sie nicht mehr beschneiden, vielmehr sollten sie
sich mit jeder denkbaren Unreinheit und Schande beflecken.

<<v49>>
49 So sollte das Gesetz in Vergessenheit geraten und alle seine
Vorschriften sollten hinfällig werden.

<<v50>>
50 Wer aber des Königs Anordnung nicht befolge, müsse sterben.

<<v51>>
51 Ähnliche Anweisungen erließ er für sein ganzes Reich. Er setzte
Beamte ein, die die Durchführung im ganzen Volk überwachen sollten; auch
gab er den Befehl, der Reihe nach in allen Städten Judäas einen
Opfergottesdienst zu halten.

<<v52>>
52 Viele aus dem Volk schlossen sich ihnen an; sie alle fielen vom
Gesetz ab und trieben es schlimm im Land.

<<v53>>
53 Die Israeliten mussten sich vor ihnen verstecken, wo immer sie
Zuflucht fanden.

<<v54>>
54 Am fünfzehnten Kislew des Jahres 145 ließ der König auf dem
Brandopferaltar den unheilvollen Gräuel aufstellen; auch in den Städten
Judäas ringsum baute man Altäre. [fn:12] [fn:13]

<<v55>>
55 Vor den Haustüren und auf den Plätzen opferte man Weihrauch.

<<v56>>
56 Alle Buchrollen des Gesetzes, die man fand, wurden zerrissen und
verbrannt.

<<v57>>
57 Wer im Besitz einer Bundesrolle angetroffen wurde oder zum Gesetz
hielt, wurde aufgrund der königlichen Anordnung zum Tod verurteilt.

<<v58>>
58 Sie ließen Israel ihre Macht fühlen und gingen mit Gewalt gegen alle
vor, die sie Monat für Monat in den Städten aufspürten.

<<v59>>
59 Am fünfundzwanzigsten des Monats (Kislew) brachten sie auf dem Altar,
den sie über dem Brandopferaltar errichtet hatten, ein Opfer dar.

<<v60>>
60 Frauen, die ihre Kinder hatten beschneiden lassen, wurden auf Befehl
(des Königs) hingerichtet; [fn:14]

<<v61>>
61 dabei hängte man die Säuglinge an den Hals ihrer Mütter. Auch ihre
Familien brachte man um samt denen, die die Beschneidung vorgenommen
hatten.

<<v62>>
62 Dennoch blieben viele aus Israel fest und stark; sie aßen nichts, was
unrein war.

<<v63>>
63 Lieber wollten sie sterben, als sich durch die Speisen unrein machen
und den heiligen Bund entweihen. So starben sie.

<<v64>>
64 Ein gewaltiger Zorn lag auf Israel.\\
\\

* Footnotes

[fn:1] Die Kittäer sind eigentlich die Bewohner der Insel
Zypern, im weiteren Sinn die Bewohner aller Inseln im östlichen
Mittelmeerraum, schließlich alle Griechen überhaupt. - Griechenland ist
hier das von Griechen bewohnte westliche Kleinasien einschließlich
Griechenlands und Mazedoniens.

[fn:2] Er starb im Juni 323 v. Chr.

[fn:3] [[file:Dan_7.org::v24][Dan 7,24f]]; [[file:Dan_8.org::v23][8,23]]-[[file:Dan_8.org::v25][25]]; [[file:Dan_11.org::v21][11,21]]-[[file:Dan_11.org::v25][45]]; [[file:2.Makk_4.org::v7][2 Makk 4,7]]

[fn:4] Die griechische (seleuzidische) Zeitrechnung beginnt mit
dem Jahr 312 v. Chr. Das 137. Jahr ist also 175 v. Chr.

[fn:5] (11-15) [[file:2.Makk_4.org::v9][2 Makk 4,9]]-[[file:2.Makk_4.org::v17][17]]

[fn:6] (16-24) [[file:2.Makk_5.org::v1][2 Makk 5,1]]-[[file:2.Makk_5.org::v21][21]];[[file:Dan_11.org::v25][Dan 11,25]]-[[file:Dan_11.org::v28][28]]

[fn:7] Es handelt sich um den ersten Feldzug gegen Ptolemäus
Philometor im Jahr 169 v. Chr.

[fn:8] (29-30) [[file:2.Makk_5.org::v24][2 Makk 5,24]]-[[file:2.Makk_5.org::v26][26]]

[fn:9] (41-64) [[file:2.Makk_6.org][2 Makk 6f]]

[fn:10] Noch 198 v. Chr. hatte Antiochus III. den Juden
zugestanden, nach dem mosaischen Gesetz leben zu dürfen.

[fn:11] (45-46) [[file:Dan_9.org::v27][Dan 9,27]]; [[file:Dan_11.org::v31][11,31]]

[fn:12] [[file:Dan_9.org::v27][Dan 9,27]]; [[file:Dan_11.org::v31][11,31]]

[fn:13] Unheilvoller Gräuel: wohl ein Altar zu Ehren eines
Fruchtbarkeitsgottes.

[fn:14] (60-61) [[file:2.Makk_6.org::v10][2 Makk 6,10]]
