#+TITLE: 1 Makk 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-27 Mo 13:10]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Makk 12.html

<<verses>>

<<v1>>
* Jonatans Bündnisse mit Rom und Sparta: 12,1-23

1 Als Jonatan sah, dass die Zeit für ihn günstig war, wählte er einige
Männer aus und sandte sie nach Rom, um den Freundschaftsvertrag mit den
Römern zu bestätigen und zu erneuern. [fn:1] [fn:2]

<<v2>>
2 Auch nach Sparta und nach anderen Orten schickte er Briefe gleicher
Art.

<<v3>>
3 Die Abgesandten reisten nach Rom, traten vor den Senat und sagten: Uns
schicken der Hohepriester Jonatan und das jüdische Volk, um das frühere
Freundschaftsbündnis mit den Römern zu erneuern.

<<v4>>
4 Man gab ihnen Briefe mit an die Behörden der Orte unterwegs mit der
Anweisung, sie sicher nach Judäa weiterzuleiten.

<<v5>>
5 Hier ist eine Abschrift des Briefes, den Jonatan an die Spartaner
schrieb:

<<v6>>
6 Der Hohepriester Jonatan, der Ältestenrat des Volkes, die Priester und
das ganze jüdische Volk grüßen ihre Brüder, die Spartaner.

<<v7>>
7 Schon vor längerer Zeit hat euer König Arëus an den Hohenpriester
Onias einen Brief gerichtet, in dem steht, dass ihr unsere Brüder seid,
wie aus der Abschrift hervorgeht. [fn:3]

<<v8>>
8 Onias empfing den Abgesandten ehrenvoll und nahm den Brief entgegen,
in dem ausdrücklich vom Freundschaftsbündnis die Rede war.

<<v9>>
9 So etwas haben wir zwar nicht nötig; denn unser Trost sind die
heiligen Bücher, die wir besitzen. [fn:4]

<<v10>>
10 Dennoch wollten wir diese Botschaft an euch senden und die
brüderliche Gemeinschaft und Freundschaft mit euch erneuern, damit wir
euch nicht fremd werden. Viel Zeit ist nämlich verflossen, seit ihr eure
Gesandtschaft zu uns geschickt hattet.

<<v11>>
11 Wir haben seither an allen Festen und an allen Tagen, die dafür
vorgesehen sind, bei unseren Opfern und Gebeten ständig an euch gedacht.
Denn so gehört es sich und es entspricht ja auch der Sitte, an die
Brüder zu denken.

<<v12>>
12 Wir freuen uns über euren Ruhm.

<<v13>>
13 Wir selbst waren in großer Not und sind in viele Kämpfe verwickelt
worden; denn die Könige ringsum führten Krieg gegen uns.

<<v14>>
14 Dennoch wollten wir wegen dieser Kriege weder euch noch den anderen
Verbündeten und Freunden zur Last fallen.

<<v15>>
15 Denn wir haben den Himmel selbst als Helfer und Beistand. Darum sind
wir vor unseren Feinden gerettet worden und unsere Feinde liegen
gedemütigt am Boden.

<<v16>>
16 Jetzt haben wir Numenius, den Sohn des Antiochus, und Antipater, den
Sohn Jasons, als Gesandte zu den Römern geschickt, um das alte
Freundschaftsbündnis mit ihnen zu erneuern.

<<v17>>
17 Wir haben ihnen aufgetragen, auf ihrer Reise auch euch zu besuchen,
euch Grüße zu bestellen und unseren Brief zu überreichen, in dem wir
euch anbieten, die brüderliche Gemeinschaft mit uns zu erneuern.

<<v18>>
18 Es wäre freundlich von euch, uns darauf Antwort zu geben.

<<v19>>
19 Und hier ist die Abschrift des Briefes, den die Spartaner an Onias
gesandt hatten:

<<v20>>
20 Arëus, König der Spartaner, grüßt den Hohenpriester Onias.

<<v21>>
21 In einer Schrift über die Spartaner und Juden fand sich die
Nachricht, dass sie Brüder sind und beide von Abraham abstammen.

<<v22>>
22 Da wir dies erfahren haben, wäre es freundlich von euch, uns zu
schreiben, wie es euch geht.

<<v23>>
23 Wir schreiben euch wieder. Eure Herden und eure Habe gehören uns und
unsere euch. Wir geben den Auftrag, dass man euch darüber Auskunft
gibt.\\
\\

<<v24>>
* Der Feldzug gegen die Truppen des Demetrius II.: 12,24-34

24 Jonatan erfuhr, dass die Feldherren des Demetrius mit einem noch
größeren Heer als zuvor zurückgekehrt waren, um gegen ihn zu kämpfen.

<<v25>>
25 Er brach von Jerusalem auf und traf in der Gegend von Hamat auf sie.
Er wollte ihnen nämlich keine Zeit lassen, in sein Land einzudringen.

<<v26>>
26 Späher, die er in ihr Lager geschickt hatte, meldeten ihm bei ihrer
Rückkehr, dass die Feinde sich zu einem nächtlichen Überfall vorbereitet
hatten.

<<v27>>
27 Bei Sonnenuntergang befahl daher Jonatan seinen Leuten, wach zu
bleiben und die ganze Nacht kampfbereit unter Waffen zu stehen. Rings um
das Lager stellte er Posten auf.

<<v28>>
28 Als die Gegner merkten, dass Jonatan mit seinen Leuten kampfbereit
war, packte sie Furcht und Schrecken. Sie zündeten in ihrem Lager
Wachfeuer an und zogen ab.

<<v29>>
29 Jonatan und seine Leute bemerkten bis zum Morgen nichts; denn sie
sahen die Feuer brennen.

<<v30>>
30 Jonatan nahm zwar die Verfolgung auf, konnte die Feinde aber nicht
mehr einholen; denn sie hatten den Eleutherus bereits überschritten.

<<v31>>
31 Jonatan wandte sich nun gegen die sabadäischen Araber, schlug sie und
plünderte sie aus.

<<v32>>
32 Dann brach er nach Damaskus auf und zog durch das ganze dazwischen
liegende Gebiet.

<<v33>>
33 Auch Simeon war aufgebrochen. Er marschierte auf Aschkelon und auf
die Festungen in jenem Gebiet zu; dann wandte er sich überraschend gegen
Jafo und besetzte es.

<<v34>>
34 Er hatte nämlich gehört, dass die Einwohner vorhatten, die Festung
den Leuten des Demetrius zu übergeben. Daher legte er eine Besatzung
hinein, um die Stadt zu bewachen.\\
\\

<<v35>>
* Die Belagerung der Burg von Jerusalem durch Jonatan: 12,35-38

35 Als Jonatan zurückgekehrt war, ließ er die Ältesten des Volkes
zusammenkommen und beriet mit ihnen über die Anlage von Festungen in
Judäa.

<<v36>>
36 Auch sollten die Mauern von Jerusalem erhöht werden; ferner sei
zwischen der Burg und der Stadt eine hohe Mauer zu errichten, um die
Burg völlig von der Stadt abzuschneiden, damit die Besatzung weder etwas
kaufen noch verkaufen könne.

<<v37>>
37 So kam man zum Ausbau der Stadt zusammen. Als ein Teil der Mauer
oberhalb des Tales im Osten einstürzte, besserte man sie wieder aus und
gab ihr den Namen Kafnata.

<<v38>>
38 Simeon baute Hadid in der Schefela aus, befestigte es und versah es
mit Toren und die Tore mit Querbalken zum Verriegeln. [fn:5]\\
\\

<<v39>>
* Der Verrat des Tryphon an Jonatan: 12,39-52

39 Tryphon strebte nach der Herrschaft über Asien und wollte sich selbst
die Königskrone aufsetzen; deshalb trachtete er König Antiochus nach dem
Leben. [fn:6]

<<v40>>
40 Doch er fürchtete, dass Jonatan das nicht zulassen und Krieg gegen
ihn führen werde. So suchte er nach Mitteln und Wegen, ihn in seine
Gewalt zu bekommen und umzubringen. Darum zog er nach Bet-Schean.

<<v41>>
41 Jonatan rückte ihm mit vierzigtausend kampferprobten Männern nach
Bet-Schean entgegen.

<<v42>>
42 Als Tryphon sah, dass Jonatan ein großes Heer bei sich hatte,
fürchtete er sich, etwas gegen ihn zu unternehmen.

<<v43>>
43 Er bereitete ihm einen glänzenden Empfang, stellte ihn all seinen
Freunden vor, machte ihm Geschenke und befahl seinen Freunden und
Soldaten: Gehorcht ihm wie mir selbst!

<<v44>>
44 Dann sagte er zu Jonatan: Warum hast du dieses ganze Heer bemüht? Es
droht doch kein Krieg.

<<v45>>
45 Lass sie nach Hause gehen, wähl dir einige Männer als Begleitung aus
und geh mit mir nach Ptolemaïs! Ich werde dir die Stadt und die übrigen
Festungen übergeben und auch alle anderen Truppen und alle Behörden. Nur
deswegen bin ich gekommen, dann ziehe ich wieder ab.

<<v46>>
46 Jonatan vertraute ihm und tat, was Tryphon ihm vorgeschlagen hatte.
Er entließ seine Truppen und sie zogen nach Judäa ab.

<<v47>>
47 Dreitausend Mann behielt er bei sich, von denen er zweitausend in
Galiläa ließ; nur tausend begleiteten ihn.

<<v48>>
48 Sobald Jonatan Ptolemaïs betreten hatte, schlossen die Einwohner die
Tore, nahmen ihn fest und erschlugen alle, die mit ihm gekommen waren,
mit dem Schwert.

<<v49>>
49 Tryphon entsandte außerdem Fußvolk und Reiterei nach Galiläa und in
die Große Ebene, um alle Truppen Jonatans niederzumachen. [fn:7]

<<v50>>
50 Als diese merkten, dass Jonatan mit seinen Begleitern den Feinden in
die Hände gefallen und umgekommen war, machten sie einander Mut und
marschierten kampfbereit in bester Ordnung weiter.

<<v51>>
51 Als die Verfolger sahen, dass Jonatans Männer um ihr Leben kämpfen
würden, kehrten sie um.

<<v52>>
52 Die jüdischen Truppen kamen unversehrt in Judäa an. Sie trauerten um
Jonatan und seine Begleiter und waren voller Angst; auch ganz Israel war
in großer Trauer.\\
\\

<<v53>>
* Die Taten Simeons: 12,53 - 16,24

* Die Wahl Simeons zum Anführer Israels: 12,53 - 13,11

53 Alle Völker ringsum versuchten, Israel zu vernichten. Denn sie sagten
sich: Sie haben keinen Führer und Helfer mehr. Nun wollen wir gegen sie
kämpfen und die Erinnerung an sie austilgen. [fn:8]

* Footnotes

[fn:1] (1-2) [[file:1.Makk_8.org::v17][8,17]]-[[file:1.Makk_8.org::v32][32]]

[fn:2] Die Römer hatten nichts zur Unterstützung des Judas
Makkabäus getan. Auch diese Gesandtschaft blieb ohne Erfolg.

[fn:3] [[file:2.Makk_5.org::v9][2 Makk 5,9]]

[fn:4] die heiligen Bücher: Gemeint sind die Schriften des
Alten Testaments, die um diese Zeit zum Kanon vereinigt werden.

[fn:5] Schefela: der an die Küstenebene anschließende hügelige
Landstreifen, der dem judäischen Bergland vorgelagert ist.

[fn:6] [[file:1.Makk_11.org::v39][11,39f]]

[fn:7] die Große Ebene: die Ebene von Megiddo, auch die «Ebene
Jesreel» genannt.

[fn:8] [[file:1.Makk_5.org::v1][5,1f]]
