#+TITLE: 1 Makk 13 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-27 Mo 13:14]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Makk 13.html

* 1.Makk 13

<<verses>>

<<v1>>
1 Simeon erfuhr, dass Tryphon ein großes Heer zusammengebracht hatte, um
in Judäa einzufallen und es zu vernichten.

<<v2>>
2 Auch merkte er, wie das Volk voller Angst und Furcht war. Darum ging
er nach Jerusalem hinauf und rief das Volk zusammen.

<<v3>>
3 Er sprach ihnen Mut zu und sagte: Ihr wisst selbst, wie ich, meine
Brüder und meine Familie sich für unsere Gesetze und für das Heiligtum
eingesetzt und welche Kämpfe und Gefahren wir dafür auf uns genommen
haben.

<<v4>>
4 Alle meine Brüder sind nun für Israel gestorben; ich allein bin übrig
geblieben.

<<v5>>
5 Ich denke nicht daran, im Augenblick der Not mein Leben zu schonen.
Denn ich bin nicht mehr wert als meine Brüder.

<<v6>>
6 Vielmehr will ich mein Volk, das Heiligtum, unsere Frauen und Kinder
rächen. Denn alle Völker haben sich zusammengetan, um uns auszurotten,
weil sie uns hassen.

<<v7>>
7 Sobald das Volk seine Worte hörte, fasste es neuen Mut

<<v8>>
8 und rief laut: Sei du unser Führer anstelle deiner Brüder Judas und
Jonatan!

<<v9>>
9 Nimm unseren Kampf in deine Hand! Alles, was du befiehlst, wollen wir
tun.

<<v10>>
10 Simeon rief alle kampffähigen Männer zusammen, ließ den Bau der
Mauern von Jerusalem so schnell wie möglich zu Ende führen und sicherte
die Stadt nach allen Seiten.

<<v11>>
11 Jonatan, den Sohn des Abschalom, schickte er mit einem ansehnlichen
Heer nach Jafo. Dieser vertrieb die Einwohner und blieb in der Stadt.\\
\\

<<v12>>
* Tryphons Feldzug gegen Jerusalem und Jonatans Tod: 13,12-30

12 Tryphon brach mit einem großen Heer von Ptolemaïs auf, um in Judäa
einzufallen. Jonatan nahm er als Gefangenen mit sich.

<<v13>>
13 Simeon schlug sein Lager bei Hadid am Rand der Ebene auf.

<<v14>>
14 Da erfuhr Tryphon, Simeon habe anstelle seines Bruders Jonatan die
Führung übernommen und werde den Kampf gegen ihn fortsetzen. Er schickte
zu ihm Unterhändler mit der Botschaft:

<<v15>>
15 Wir halten deinen Bruder Jonatan nur fest, weil er der königlichen
Schatzkammer Geld schuldet für die Ämter, die er innehat.

<<v16>>
16 Schick uns also hundert Talente Silber und zwei seiner Söhne als
Geiseln, damit er nicht von uns abfällt, sobald er wieder frei ist; dann
werden wir ihn freilassen.

<<v17>>
17 Simeon merkte wohl, dass ihr Vorschlag nicht ehrlich gemeint war.
Dennoch ließ er das Geld und die Kinder holen, um sich beim Volk nicht
verhasst zu machen.

<<v18>>
18 Sonst hätte man nämlich gesagt: Jonatan musste sterben, weil Simeon
das Geld und die Kinder für ihn nicht ausgeliefert hat.

<<v19>>
19 So lieferte er die Kinder und die hundert Talente aus; aber es zeigte
sich, dass Tryphon ein Lügner war; denn er ließ Jonatan nicht frei.

<<v20>>
20 Danach rückte Tryphon heran, um in Judäa einzufallen und es zu
verwüsten. Er machte dabei einen Umweg über Adora; aber Simeon trat ihm
mit seinem Heer überall entgegen, wo er ins Land eindringen wollte. [fn:1]

<<v21>>
21 Die Besatzung der Burg von Jerusalem schickte Boten zu Tryphon, die
ihn zur Eile drängten und ihn aufforderten, von der Wüste her einen
Durchbruch zu versuchen und Nahrungsmittel für sie heranzuschaffen.

<<v22>>
22 Daraufhin stellte Tryphon die gesamte Reiterei bereit, um
durchzubrechen; aber in jener Nacht fiel sehr viel Schnee und er konnte
wegen des Schnees nicht durchkommen. Da zog er ab nach Gilead.

<<v23>>
23 In der Nähe von Baskama ließ er Jonatan umbringen und begraben.

<<v24>>
24 Dann zog Tryphon ab und kehrte in sein Land zurück.

<<v25>>
25 Simeon schickte einige Männer, um die Gebeine seines Bruders Jonatan
holen und in Modeïn, der Stadt seiner Väter, bestatten zu lassen.

<<v26>>
26 Ganz Israel hielt eine große Totenklage für ihn ab und trauerte viele
Tage um ihn.

<<v27>>
27 Simeon ließ ein hohes, weithin sichtbares Denkmal über dem Grab
seines Vaters und seiner Brüder errichten. Für die Vorder- und Rückseite
verwendete er behauene Steine.

<<v28>>
28 Auch ließ er sieben Pyramiden bauen, von denen jeweils zwei einander
gegenüberstanden: für den Vater, die Mutter und die vier Brüder.

<<v29>>
29 Um die Pyramiden ließ er eine kunstvolle Anlage errichten, indem er
sie mit hohen Säulen umgab. An den Säulen ließ er zum ewigen Gedenken
Rüstungen anbringen und neben den Rüstungen Schiffe einmeißeln. Das
Denkmal sollte für alle sichtbar sein, die auf dem Meer vorüberfahren.

<<v30>>
30 Dieses Grabmal, das er in Modeïn errichtete, steht noch heute dort.\\
\\

<<v31>>
* Das Bündnis zwischen Simeon und Demetrius II.: 13,31-42

31 Tryphon ließ den jungen König Antiochus heimtückisch ermorden, [fn:2]

<<v32>>
32 trat seine Nachfolge an und setzte sich die Krone von Asien auf. Er
richtete im Land großes Unheil an.

<<v33>>
33 Simeon legte in Judäa Festungen an, umgab sie mit hohen Türmen und
gewaltigen Mauern, versah sie mit Toren und Riegeln und ließ Proviant in
die Festungen bringen.

<<v34>>
34 Dann wählte Simeon einige Männer aus, die er zu König Demetrius
sandte, um einen Steuernachlass für das Land zu erwirken. Denn Tryphon
war nur auf Ausbeutung aus.

<<v35>>
35 König Demetrius antwortete ihm mit folgendem Brief:

<<v36>>
36 König Demetrius grüßt Simeon, den Hohenpriester und Freund der
Könige, sowie die Ältesten und das jüdische Volk.

<<v37>>
37 Den goldenen Kranz und den Palmzweig, den ihr gesandt habt, haben wir
erhalten. Wir sind bereit, ein für alle Mal Frieden mit euch zu
schließen und die Behörden anzuweisen, euch Nachlass zu gewähren.

<<v38>>
38 Alles, was wir euch bestätigt haben, bleibt in Kraft; auch die
Festungen, die ihr angelegt habt, dürfen bestehen bleiben.

<<v39>>
39 Wir vergeben euch alle Nachlässigkeiten und Verfehlungen, die ihr bis
auf den heutigen Tag begangen habt, und erlassen euch den Kranz, den ihr
noch schuldet. Sollten noch andere Abgaben von Jerusalem erhoben worden
sein, sollen sie künftig wegfallen.

<<v40>>
40 Wenn ihr Leute habt, die geeignet sind, in unserer Leibgarde Dienst
zu tun, sollen sie angenommen werden. Zwischen uns soll Friede
herrschen.

<<v41>>
41 Im Jahr 170 wurde das Joch der fremden Völker von Israel genommen. [fn:3]

<<v42>>
42 Das Volk begann, Urkunden und Verträge mit der Formel einzuleiten: Im
Jahr 1 der Regierung Simeons, des Hohenpriesters, Befehlshabers und
Führers der Juden.\\
\\

<<v43>>
* Die endgültige Befreiung Israels: 13,43 - 14,3

43 Damals zog Simeon nach Geser, schloss die Stadt mit seinen Truppen
ein, errichtete einen Belagerungsturm und ließ ihn an die Stadt
heranschieben. Man schlug eine Bresche in einen Turm der Stadtmauer und
besetzte ihn. [fn:4]

<<v44>>
44 Dann sprang die Mannschaft des Belagerungsturms in die Stadt hinein.
Es entstand ein großes Durcheinander in der Stadt.

<<v45>>
45 Ihre Bürger stiegen mit Frauen und Kindern auf die Mauern, zerrissen
ihre Gewänder, schrien laut und baten Simeon, mit ihnen Frieden zu
schließen.

<<v46>>
46 Sie sagten: Vergilt uns nicht nach unserer Schuld, sondern nach
deiner Güte!

<<v47>>
47 Simeon ließ sich erweichen und stellte den Kampf ein. Er vertrieb sie
jedoch aus der Stadt und ließ die Häuser, in denen Götterbilder waren,
entsühnen; dann zog er feierlich mit Lobliedern und Preisgesängen in die
Stadt ein.

<<v48>>
48 Er entfernte alles Unreine und siedelte gesetzestreue Männer an. Dann
ließ er die Stadt noch stärker befestigen und baute auch für sich ein
Haus in der Stadt.

<<v49>>
49 Die Besatzung der Burg von Jerusalem war von jeder Verbindung mit dem
Land abgeschnitten; sie konnten weder etwas kaufen noch etwas verkaufen
und hatten fast nichts mehr zu essen; eine beträchtliche Anzahl von
ihnen kam durch den Hunger um. [fn:5]

<<v50>>
50 Da baten sie Simeon um Frieden. Er gewährte ihn, vertrieb sie aber
von dort und entsühnte die Burg von jeder Befleckung. [fn:6]

<<v51>>
51 Am dreiundzwanzigsten Tag des zweiten Monats im Jahr 171 zogen die
Israeliten unter der Musik von Harfen, Zimbeln und Zithern mit Hymnen
und Gesängen in die Burg ein; sie trugen Palmzweige in den Händen und
sangen Freudenlieder. Denn Israel war von einem gefährlichen Feind
befreit.

<<v52>>
52 Simeon setzte fest, dass dieser Tag jährlich feierlich begangen
werden solle. Er ließ die zur Burg hin gelegene Seite des Tempelbergs
noch stärker befestigen und nahm mit seinem Gefolge Wohnung in der Burg.

<<v53>>
53 Als Simeon sah, dass sein Sohn Johanan zu einem Mann herangewachsen
war, machte er ihn zum Befehlshaber aller Streitkräfte und Johanan ließ
sich in Geser nieder.

* Footnotes

[fn:1] Adora: südwestlich von Hebron; schon Rehabeam hatte es
befestigt (vgl. 2 Chr 11,9).

[fn:2] [[file:1.Makk_12.org::v39][12,39]]

[fn:3] [[file:Jer_30.org::v8][Jer 30,8]]

[fn:4] (43 - 14,3) [[file:2.Makk_10.org::v32][2 Makk 10,32]]-[[file:2.Makk_10.org::v38][38]]

[fn:5] [[file:1.Makk_12.org::v36][12,36]]

[fn:6] [[file:1.Makk_1.org::v33][1,33]]-[[file:1.Makk_1.org::v36][36]]
