#+TITLE: 1 Makk 14 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-27 Mo 13:18]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/1 Makk 14.html

<<verses>>
* 1.Makk 14

<<v1>>
1 Im Jahr 172 zog König Demetrius seine Truppen zusammen und brach nach
Medien auf, um Hilfstruppen für den Kampf gegen Tryphon zu gewinnen.

<<v2>>
2 Als Arsakes, der König von Persien und Medien, erfuhr, dass Demetrius
in sein Gebiet eingedrungen war, sandte er einen seiner Feldherren mit
dem Auftrag aus, Demetrius lebendig gefangen zu nehmen. [fn:1]

<<v3>>
3 Der Feldherr machte sich auf den Weg, schlug das Heer des Demetrius,
nahm ihn gefangen und brachte ihn zu Arsakes, der ihn ins Gefängnis
warf.\\
\\

<<v4>>
* Das Loblied auf Simeon: 14,4-15

4 Das Land Judäa hatte Ruhe, solange Simeon lebte. /\\
 Er sorgte für das Wohl seines Volkes. /\\
 Sie freuten sich jeden Tag über seine Macht /\\
 und seinen Ruhm. [fn:2]\\
\\

<<v5>>
5 Sein Ruhm wuchs, als er den Hafen von Jafo gewann; /\\
 so öffnete er einen Weg zu den Inseln.\\
\\

<<v6>>
6 Er erweiterte das Gebiet seines Volkes /\\
 und gewann die Herrschaft über das ganze Land. [fn:3]\\
\\

<<v7>>
7 Viele Verbannte führte er wieder zurück. /\\
 Er eroberte Geser, Bet-Zur und die Burg /\\
 und vernichtete darin alles, was unrein war. /\\
 Niemand widersetzte sich ihm.\\
\\

<<v8>>
8 Sie bebauten in Frieden ihr Land; /\\
 der Boden gab seinen Ertrag, /\\
 die Bäume auf dem Feld ihre Frucht. [fn:4]\\
\\

<<v9>>
9 Auf den Plätzen saßen die Alten; /\\
 alle sprachen über ihr Glück. /\\
 Die jungen Männer /\\
 gingen im Schmuck ihrer Waffen umher. [fn:5]\\
\\

<<v10>>
10 Er versorgte die Städte mit Nahrung /\\
 und baute sie zu Festungen aus. /\\
 Sein Name wurde berühmt bis an das Ende der Welt.\\
\\

<<v11>>
11 Er brachte dem Land den Frieden, /\\
 in Israel herrschte Jubel und Freude.\\
\\

<<v12>>
12 Jeder saß unter seinem Weinstock und seinem Feigenbaum /\\
 und niemand schreckte sie auf. [fn:6]\\
\\

<<v13>>
13 Der Feind verschwand aus dem Land; /\\
 in jenen Tagen wurden die Könige besiegt.\\
\\

<<v14>>
14 Er stärkte alle Schwachen im Land /\\
 und setzte sich ein für das Gesetz. /\\
 Alle Verräter und Sünder aber rottete er aus. [fn:7]\\
\\

<<v15>>
15 Das Heiligtum baute er prachtvoll aus, /\\
 viele Geräte für den Tempel schaffte er an.\\
\\

<<v16>>
* Die Erneuerung der Bündnisse mit Sparta und Rom: 14,16-24

16 Als man in Rom - und auch in Sparta - erfuhr, dass Jonatan tot war,
war man sehr bestürzt.

<<v17>>
17 Als man aber hörte, sein Bruder Simeon habe seine Nachfolge als
Hoherpriester angetreten und das Land mit seinen Städten sei fest in
seiner Hand,

<<v18>>
18 schrieben sie ihm auf Bronzetafeln einen Brief und boten ihm an, das
Freundschaftsbündnis mit ihm zu erneuern, das sie mit seinen Brüdern
Judas und Jonatan geschlossen hatten. [fn:8]

<<v19>>
19 Diese Botschaft wurde vor der Volksversammlung in Jerusalem verlesen.

<<v20>>
20 Hier ist eine Abschrift des Briefes, den die Spartaner schickten: Die
Regierung und die Stadt der Spartaner grüßen den Hohenpriester Simeon,
die Ältesten, die Priester und das ganze übrige jüdische Volk, ihre
Brüder.

<<v21>>
21 Die Gesandten, die ihr zu unserem Volk geschickt habt, haben uns von
eurem Ruhm und eurem Ansehen berichtet und wir haben uns über ihren
Besuch sehr gefreut.

<<v22>>
22 Was sie vor dem Rat des Volkes gesagt haben, haben wir, wie folgt,
schriftlich festgehalten: Numenius, der Sohn des Antiochus, und
Antipater, der Sohn Jasons, sind als Gesandte der Juden zu uns gekommen,
um die Freundschaft mit uns zu erneuern.

<<v23>>
23 Das Volk hat beschlossen, ihnen einen glänzenden Empfang zu bereiten
und die Niederschrift ihrer Rede im Staatsarchiv zu hinterlegen, damit
das Volk von Sparta sie nicht vergisst. - Eine Abschrift davon schickten
sie an den Hohenpriester Simeon.

<<v24>>
24 Danach sandte Simeon den Numenius mit einem großen goldenen Schild,
der tausend Minen wog, nach Rom, um das Bündnis mit den Römern zu
bekräftigen. [fn:9]\\
\\

<<v25>>
* Die Bestätigung Simeons durch das jüdische Volk: 14,25-49

25 Als man im Volk davon erfuhr, sagte man: Wie können wir Simeon und
seinen Söhnen danken?

<<v26>>
26 Denn er, seine Brüder und seine ganze Familie waren uns Halt und
Stütze. Er hat den Kampf gegen Israels Feinde geführt und sie vertrieben
und mit seinen Brüdern dem Volk die Freiheit errungen. Man fertigte
Bronzetafeln an, die man auf dem Berg Zion an Säulen befestigte

<<v27>>
27 und auf denen folgendes stand: Am achtzehnten Tag des Monats Elul im
Jahr 172 - das ist im dritten Jahr der Regierung des großen
Hohenpriesters Simeon in Asaramel - [fn:10]

<<v28>>
28 wurde auf der großen Versammlung der Priester, des Volkes, der Führer
des Volkes und der Ältesten des Landes uns Folgendes bekanntgegeben:

<<v29>>
29 Als wiederholt im Land Krieg ausbrach, scheuten Simeon, der Sohn des
Mattatias, aus der Familie Jojaribs, und seine Brüder keine Gefahr. Sie
stellten sich den Feinden ihres Volkes entgegen, um ihr Heiligtum und
das Gesetz zu erhalten, und verschafften ihrem Volk großen Ruhm.

<<v30>>
30 Jonatan führte sein Volk zusammen; er wurde ihr Hoherpriester, bis er
mit seinen Vätern vereint wurde.

<<v31>>
31 Als darauf ihre Feinde den Plan fassten, in das Land einzufallen, um
es zu vernichten und ihr Heiligtum anzutasten,

<<v32>>
32 erhob sich Simeon und kämpfte für sein Volk. Aus eigenen Mitteln
brachte er viel Geld auf und versorgte die Krieger seines Volkes mit
Waffen und Verpflegung.

<<v33>>
33 Er ließ die Städte Judäas befestigen, besonders Bet-Zur, das an der
Grenze von Judäa liegt; er legte eine jüdische Besatzung dorthin, wo
zuvor ein Waffenlager der Feinde gewesen war.

<<v34>>
34 Auch die Städte Jafo am Meer und Geser bei Aschdod ließ er
befestigen. Früher wohnten dort die Feinde, er aber siedelte Juden an
und ließ ihnen alles zukommen, was sie zu ihrem Unterhalt brauchten.

<<v35>>
35 Als das Volk sah, wie treu Simeon war und welchen Ruhm er seinem Volk
zu verschaffen suchte, machten sie ihn zu ihrem Führer und Hohenpriester
zum Dank für all diese Taten, für die Gerechtigkeit und Treue, die er
seinem Volk bewies, und für sein Bestreben, auf jede Weise sein Volk zu
fördern.

<<v36>>
36 Es ist ihm zu seiner Zeit gelungen, die Fremden aus dem Land zu
vertreiben, vor allem die, die in der Davidstadt in Jerusalem wohnten
und sich eine Burg gebaut hatten, aus der sie Ausfälle machten, die
Umgebung des Tempels entweihten und seiner Heiligkeit großen Schaden
zufügten.

<<v37>>
37 Er siedelte in der Davidstadt Juden an und ließ sie befestigen, um
Land und Stadt zu sichern. Auch ließ er die Mauern von Jerusalem höher
machen.

<<v38>>
38 Demgemäß bestätigte ihn König Demetrius im Hohenpriesteramt.

<<v39>>
39 Er ernannte ihn zu seinem Freund und zeichnete ihn durch hohe Ehren
aus.

<<v40>>
40 Denn er hatte gehört, dass Rom die Juden Freunde, Verbündete und
Brüder genannt und den Gesandten Simeons einen glänzenden Empfang
bereitet hatte.

<<v41>>
41 Darum beschlossen die Juden und ihre Priester, Simeon solle für immer
ihr Anführer und Hoherpriester sein, bis ein wahrer Prophet auftrete. [fn:11]

<<v42>>
42 Auch solle er ihr Befehlshaber sein und für das Heiligtum Sorge
tragen; durch ihn seien die Beamten zu ernennen für die Arbeiten am
Tempel, für das Land, das Heer und die Festungen.

<<v43>>
43 [Er solle für das Heiligtum Sorge tragen.] Alle hätten ihm zu
gehorchen. Jede Urkunde im Land müsse in seinem Namen ausgestellt
werden. Auch dürfe er sich in Gold und Purpur kleiden.

<<v44>>
44 Keinem aus dem Volk oder aus der Priesterschaft sei es erlaubt, eine
dieser Bestimmungen außer Kraft zu setzen, gegen seine Anordnungen zu
verstoßen, ohne seine Erlaubnis im Land eine Versammlung einzuberufen,
Purpur zu tragen oder eine goldene Spange anzulegen.

<<v45>>
45 Jeder, der dem zuwiderhandle oder sich nicht daran halte, mache sich
strafbar.

<<v46>>
46 Das ganze Volk beschloss, diese Verfügungen zugunsten Simeons zu
erlassen.

<<v47>>
47 Simeon nahm an; er willigte ein, Hoherpriester, Befehlshaber und
Fürst der Juden und ihrer Priester zu sein und in allem den Vorsitz zu
führen. [fn:12]

<<v48>>
48 Sie ließen diese Urkunde auf Bronzetafeln schreiben und im Vorhof des
Tempels für alle sichtbar aufstellen.

<<v49>>
49 Eine Abschrift davon sei in der Schatzkammer für Simeon und seine
Söhne zu hinterlegen.\\
\\

* Footnotes

[fn:1] Arsakes ist Mitridates I. (171-138 v. Chr.), der Gründer
des Partherreiches; er entriss Demetrius Medien und Persien.

[fn:2] [[file:Ri_2.org::v18][Ri 2,18]]; [[file:Ri_3.org::v11][3,11]]

[fn:3] [[file:Ex_34.org::v24][Ex 34,24]]; [[file:Jes_54.org::v2][Jes 54,2f]]

[fn:4] [[file:Sach_8.org::v12][Sach 8,12]]

[fn:5] [[file:Sach_8.org::v4][Sach 8,4f]]

[fn:6] [[file:Mi_4.org::v4][Mi 4,4]]

[fn:7] [[file:Ps_72.org::v4][Ps 72,4]]

[fn:8] [[file:1.Makk_8.org::v17][8,17]]-[[file:1.Makk_8.org::v32][32]]; [[file:1.Makk_12.org::v3][12,3]]

[fn:9] [[file:1.Makk_15.org::v15][15,15]]

[fn:10] Asaramel ist hebräisch; es heißt entweder «Vorhof des
Volkes Gottes» oder ist verderbt aus sar-am-el (Fürst des Volkes
Gottes).

[fn:11] [[file:1.Makk_4.org::v46][4,46]]

[fn:12] Diese Titelverleihung bedeutet einen großen Schritt
hin zur Autonomie.
