#+TITLE: 1 Sam 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-07 Di 08:25]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Sam 21.html


<<verses>>

<<v1>>
* David bei Ahimelech: 21,1-10

1 Dann brach David auf und ging weg, Jonatan aber begab sich in die
Stadt zurück.

<<v2>>
2 David gelangte nach Nob zu dem Priester Ahimelech. Ahimelech kam David
aufgeregt entgegen und fragte ihn: Warum bist du allein und hast niemand
bei dir? [fn:1] [fn:2]

<<v3>>
3 David antwortete dem Priester Ahimelech: Der König hat mir einen
Auftrag gegeben und zu mir gesagt: Niemand darf etwas von der
Angelegenheit erfahren, in der ich dich sende und mit der ich dich
beauftrage. Darum habe ich meine Leute an einen bestimmten Ort bestellt.

<<v4>>
4 Hast du vielleicht etwas zur Hand für mich? Fünf Brote vielleicht?
Dann gib sie mir, oder gib mir, was du sonst finden kannst.

<<v5>>
5 Der Priester gab David Antwort und sagte: Gewöhnliches Brot habe ich
nicht zur Hand, nur heiliges Brot ist da; aber dann müssen sich die
jungen Männer von Frauen ferngehalten haben. [fn:3] [fn:4]

<<v6>>
6 David antwortete dem Priester: Wir haben uns schon gestern und
vorgestern von Frauen ferngehalten. Als ich auszog, waren die Waffen der
jungen Männer geheiligt; wenn dies auch ein gewöhnlicher Marsch ist, so
wird er doch durch die Waffen geheiligt.

<<v7>>
7 Da gab ihm der Priester heiliges Brot, denn es gab dort nur die
Schaubrote, die man von (dem Tisch) vor dem Angesicht des Herrn
entfernt, um an dem Tag, an dem sie weggenommen werden, frisches Brot
aufzulegen. [fn:5]

<<v8>>
8 Damals hielt sich dort im Heiligtum des Herrn gerade einer von den
Knechten Sauls auf, ein Edomiter namens Doëg; er war der Oberste von
Sauls Hirten.

<<v9>>
9 David fragte Ahimelech: Hast du einen Speer oder ein Schwert zur Hand?
Denn ich konnte weder mein Schwert noch andere Waffen mitnehmen, weil
der Auftrag des Königs so dringend war.

<<v10>>
10 Der Priester antwortete: Das Schwert des Philisters Goliat, den du im
Terebinthental erschlagen hast, liegt hier, in einem Mantel
eingewickelt, hinter dem Efod. Wenn du es nehmen willst, nimm es! Außer
diesem gibt es keines hier. David sagte: Kein anderes kommt ihm gleich;
gib es mir! [fn:6] [fn:7]\\
\\

<<v11>>
* David in Gat, Adullam und Mizpe: 21,11 - 22,5

11 David brach noch am gleichen Tag auf und floh vor Saul. Er kam zu
Achisch, dem König von Gat. [fn:8]

<<v12>>
12 Doch die Diener des Achisch sagten zu ihrem Herrn: Ist das nicht
David, der König des Landes? Ist das nicht der, von dem man beim
Reigentanz gesungen hat: Saul hat Tausend erschlagen, David aber
Zehntausend? [fn:9]

<<v13>>
13 David nahm sich diese Worte zu Herzen und er fürchtete sich sehr vor
Achisch, dem König von Gat.

<<v14>>
14 Darum verstellte er sich vor ihnen und tat in ihrer Gegenwart so, als
sei er wahnsinnig; er kritzelte auf die Flügel des Tores und ließ sich
den Speichel in den Bart laufen. [fn:10]

<<v15>>
15 Achisch sagte zu seinen Dienern: Seht ihr nicht, dass der Mann
verrückt ist? Warum bringt ihr ihn zu mir?

<<v16>>
16 Gibt es bei mir nicht schon genug Verrückte, sodass ihr auch noch
diesen Mann zu mir herbringt, damit er bei mir verrückt spielt? Soll der
etwa auch noch in mein Haus kommen?

* Footnotes

[fn:1] [[file:1.Sam_22.org::v9][22,9-19]]

[fn:2] Nob wird nach Jes 10,32 nördlich von Jerusalem vermutet.
Ahimelech ist nach 14,3 ein Urenkel Elis.

[fn:3] [[file:Lev_24.org::v5][Lev 24,5-9]]; [[file:Ex_19.org::v15][Ex 19,15]]

[fn:4] 5-7: Heiliges Brot darf wie die Schaubrote nur im
Zustand kultischer Reinheit genossen werden.

[fn:5] [[file:~/RoamNotes/notes/Bibel/nt/Mt_12.org::v3][Mt 12,3f]]

[fn:6] [[file:1.Sam_17.org::v50][17,50f]].[[file:1.Sam_17.org::v54][54]]

[fn:7] Efod ist hier ein Kultgegenstand unbekannten Aussehens.

[fn:8] [[file:1.Sam_27.org::v2][27,2]]; [[file:Ps_54.org::v1][Ps 56,1]]

[fn:9] [[file:1.Sam_18.org::v7][18,7]]

[fn:10] [[file:Ps_34.org::v1][Ps 34,1]]
