#+TITLE: 1 Sam 29 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-07 Di 21:23]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Sam 29.html

<<verses>>

<<v1>>
* Davids Entlassung aus dem Heer der Philister: 29,1-11

1 Die Philister versammelten ihr ganzes Heer bei Afek, während die
Israeliten ihr Lager an der Quelle bei Jesreel aufgeschlagen hatten.

<<v2>>
2 Als nun die Fürsten der Philister mit ihren Hundertschaften und
Tausendschaften auf dem Marsch waren - David und seine Männer zogen mit
Achisch am Schluss -,

<<v3>>
3 fragten die Obersten der Philister: Was sollen diese Hebräer hier?
Achisch antwortete den Obersten der Philister: Das ist doch David, der
Knecht Sauls, des Königs von Israel, der seit Jahr und Tag bei mir ist.
Seit dem Tag, da er übergelaufen ist, bis heute fand ich bei ihm nichts
Nachteiliges.

<<v4>>
4 Die Obersten der Philister aber wurden zornig auf ihn und sagten zu
ihm: Schick den Mann zurück! Er soll an den Ort zurückkehren, den du ihm
zugewiesen hast, und nicht mit uns in den Kampf ziehen. Dann kann er
sich in der Schlacht nicht gegen uns wenden. Womit könnte er sich die
Gunst seines Herrn besser erwerben als mit den Köpfen unserer Leute
hier?

<<v5>>
5 Ist das nicht der gleiche David, von dem man beim Reigentanz gesungen
hat: Saul hat Tausend erschlagen, David aber Zehntausend? [fn:1]

<<v6>>
6 Da rief Achisch David zu sich und sagte zu ihm: So wahr Jahwe lebt, du
bist ein aufrechter Mann und es wäre in meinen Augen gut, wenn du mit
mir ins Feld ziehen und wieder zurückkommen würdest; denn ich habe an
dir nichts Unrechtes entdeckt seit dem Tag, an dem du zu mir gekommen
bist, bis heute. Aber den Fürsten bist du nicht genehm.

<<v7>>
7 Darum kehr jetzt um und zieh in Frieden; so wirst du nichts tun, was
den Fürsten der Philister missfällt.

<<v8>>
8 David sagte zu Achisch: Was habe ich denn getan? Was hast du an deinem
Knecht auszusetzen gehabt von dem Tag an, an dem ich in deinen Dienst
getreten bin, bis heute? Warum darf ich nicht mitkommen und gegen die
Feinde meines Herrn, des Königs, kämpfen?

<<v9>>
9 Achisch antwortete David: Gewiss, mir bist du teuer wie ein Engel
Gottes; aber die Obersten der Philister haben gesagt: Er soll nicht mit
uns in den Kampf ziehen.

<<v10>>
10 Darum brich morgen früh auf, samt den Knechten deines Herrn, die mit
dir gekommen sind. Brecht morgen früh auf, sobald es hell wird, und geht
(nach Hause)!

<<v11>>
11 David machte sich also mit seinen Männern in aller Frühe auf den Weg;
er zog noch am Morgen weg und kehrte ins Land der Philister zurück; die
Philister aber zogen nach Jesreel hinauf.\\
\\

* Footnotes

[fn:1] [[file:1.Sam_18.org::v7][18,7]] 
