#+TITLE: 1 Sam 27 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-07 Di 21:16]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Sam 27.html

<<verses>>

<<v1>>
* David bei den Philistern: 27,1 - 28,2

1 David überlegte: Eines Tages werde ich doch noch durch Saul
umgebracht. Es bleibt nichts anderes übrig, als mich im Land der
Philister in Sicherheit zu bringen. Dann wird Saul mich in Ruhe lassen
und aufhören, mich weiter im ganzen Gebiet Israels zu suchen, und ich
bin seiner Hand entkommen. [fn:1]

<<v2>>
2 David machte sich also auf den Weg und ging mit den sechshundert
Männern, die bei ihm waren, zu Achisch hinüber, dem Sohn Maochs, dem
König von Gat. [fn:2]

<<v3>>
3 Und er blieb mit seinen Leuten bei Achisch in Gat; alle hatten ihre
Familien bei sich, David seine beiden Frauen: Ahinoam, die
Jesreeliterin, und Abigajil aus Karmel, die (frühere) Frau Nabals.

<<v4>>
4 Als man Saul meldete, dass David nach Gat geflohen war, suchte er
nicht mehr weiter nach ihm.

<<v5>>
5 David sagte zu Achisch: Wenn ich dein Wohlwollen gefunden habe, dann
weise mir einen Platz in einer der Städte des flachen Landes zu, wo ich
mich niederlassen kann. Warum soll dein Knecht bei dir in der
Königsstadt wohnen?

<<v6>>
6 Da gab ihm Achisch noch am gleichen Tag Ziklag. Deshalb gehört Ziklag
den Königen von Juda bis zum heutigen Tag. [fn:3]

<<v7>>
7 Die Zeit, die David im Land der Philister verbrachte, betrug ein Jahr
und vier Monate.

<<v8>>
8 David zog mit seinen Männern aus und sie unternahmen Raubzüge bei den
Geschuritern, den Geresitern und den Amalekitern; diese bewohnen von
jeher das Gebiet in Richtung Schur und nach Ägypten zu.

<<v9>>
9 David verheerte das Land und ließ weder Männer noch Frauen am Leben;
Schafe und Rinder, Esel, Kamele und Kleider aber nahm er mit. Wenn er
dann zurückkehrte und zu Achisch kam

<<v10>>
10 und Achisch ihn fragte: Wohin habt ihr heute euren Raubzug gemacht?,
antwortete David: Ins Südland von Juda, oder: Ins Südland der
Jerachmeeliter, oder: Ins Südland der Keniter. [fn:4]

<<v11>>
11 Weder Männer noch Frauen ließ er am Leben und er brachte niemand nach
Gat; denn er sagte sich: Niemand soll etwas über uns berichten und sagen
können: Das und das hat David gemacht. So hielt er es die ganze Zeit
über, solange er sich im Land der Philister aufhielt.

<<v12>>
12 Achisch aber schenkte David Vertrauen, denn er sagte sich: Er hat
sich bei seinem Volk, bei den Israeliten, so verhasst gemacht, dass er
für immer mein Knecht bleiben muss.

* Footnotes

[fn:1] [[file:1.Sam_23.org::v23][23,23]]

[fn:2] [[file:1.Sam_21.org::v11][21,11-16]]

[fn:3] [[file:1.Sam_30.org::v1][30,1]]

[fn:4] [[file:1.Sam_30.org::v29][30,29]]
