#+TITLE: 1 Sam 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-06 Mo 10:02]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Sam 5.html


* 1.Sam 5

<<verses>>

<<v1>>
1 Die Philister brachten die Lade Gottes, die sie erbeutet hatten, von
Eben-Eser nach Aschdod.

<<v2>>
2 Dann nahmen sie die Lade Gottes, brachten sie in den Tempel Dagons und
stellten sie neben Dagon auf. [fn:1]

<<v3>>
3 Als die Einwohner von Aschdod aber am nächsten Morgen aufstanden, war
Dagon vornüber gefallen und lag vor der Lade des Herrn mit dem Gesicht
auf dem Boden. Sie nahmen Dagon und stellten ihn wieder an seinen Platz.

<<v4>>
4 Doch als sie am nächsten Morgen in der Frühe wieder aufstanden, da war
Dagon wieder vornüber gefallen und lag vor der Lade des Herrn mit dem
Gesicht auf dem Boden. Dagons Kopf und seine beiden Hände lagen
abgeschlagen auf der Schwelle. Nur der Rumpf war Dagon geblieben.

<<v5>>
5 Deshalb treten die Priester Dagons und alle, die in den Tempel Dagons
kommen, bis zum heutigen Tag nicht auf die Schwelle des Dagon von
Aschdod. [fn:2]

<<v6>>
6 Die Hand des Herrn lastete schwer auf den Einwohnern von Aschdod, und
er versetzte sie in Schrecken und schlug Aschdod und sein Gebiet mit der
Beulenpest.

<<v7>>
7 Als die Einwohner von Aschdod sahen, was geschah, sagten sie: Die Lade
des Gottes Israels darf nicht bei uns bleiben; denn seine Hand liegt
schwer auf uns und auf unserem Gott Dagon.

<<v8>>
8 Sie sandten (Boten) zu allen Fürsten der Philister, riefen sie bei
sich zusammen und fragten sie: Was sollen wir mit der Lade des Gottes
Israels machen? Die Fürsten erklärten: Die Lade des Gottes Israels soll
nach Gat hinüberziehen. Darauf brachte man die Lade des Gottes Israels
nach Gat.

<<v9>>
9 Doch nachdem man sie nach Gat gebracht hatte, kam die Hand des Herrn
über diese Stadt und versetzte sie in gewaltigen Schrecken. Er schlug
die Leute der Stadt, vom Kleinsten bis zum Größten, sodass Pestbeulen
bei ihnen aufbrachen.

<<v10>>
10 Darauf schickte man die Lade Gottes nach Ekron. Als die Lade Gottes
nach Ekron kam, schrien die Einwohner von Ekron auf und sagten: Sie
bringen die Lade des Gottes Israels zu uns herüber, um uns und unser
Volk zu töten.

<<v11>>
11 Darauf sandten sie (Boten) zu allen Fürsten der Philister, riefen sie
zusammen und sagten: Schafft die Lade des Gottes Israels fort! Sie soll
an den Ort zurückkehren, an den sie gehört, und nicht uns und unser Volk
töten. Denn ein tödlicher Schrecken lag über der ganzen Stadt; die Hand
Gottes lastete schwer auf ihr.

<<v12>>
12 Die Leute, die nicht starben, waren mit Pestbeulen geschlagen, und
der Hilfeschrei der Stadt stieg zum Himmel empor.\\
\\

* Footnotes

[fn:1] Dagon war eine bei den Semiten weit verbreitete, auch
von den Philistern verehrte Gottheit, vielleicht ein Getreidegott (dagan
= Getreide).

[fn:2] Die Sitte, nicht auf die Schwelle zu treten, wird hier
mit der Niederlage Dagons erklärt. Sie entstand aber wohl aus der Scheu,
auf die Schwellendämonen zu treten.
