#+TITLE: 1 Sam 31 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-07 Di 21:27]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Sam 31.html

<<verses>>

<<v1>>
* Sauls Ende: 31,1-13

1 Als die Philister gegen Israel kämpften, flohen die Israeliten vor
ihnen; viele waren gefallen und lagen erschlagen auf dem Gebirge von
Gilboa. [fn:1]

<<v2>>
2 Die Philister verfolgten Saul und seine Söhne und erschlugen Sauls
Söhne Jonatan, Abinadab und Malkischua.

<<v3>>
3 Um Saul selbst entstand ein schwerer Kampf. Die Bogenschützen hatten
ihn getroffen und er war sehr schwer verwundet.

<<v4>>
4 Da sagte Saul zu seinem Waffenträger: Zieh dein Schwert und durchbohre
mich damit! Sonst kommen diese Unbeschnittenen, durchbohren mich und
treiben ihren Mutwillen mit mir. Der Waffenträger wollte es nicht tun;
denn er hatte große Angst. Da nahm Saul selbst das Schwert und stürzte
sich hinein.

<<v5>>
5 Als der Waffenträger sah, dass Saul tot war, stürzte auch er sich in
sein Schwert und starb zusammen mit Saul.

<<v6>>
6 So kamen Saul, seine drei Söhne, sein Waffenträger und alle seine
Männer an jenem Tag gemeinsam ums Leben. [fn:2]

<<v7>>
7 Als die Israeliten auf der anderen Seite der Ebene und jenseits des
Jordan sahen, dass die Israeliten geflohen und dass Saul und seine Söhne
tot waren, verließen sie ihre Städte und flohen. Dann kamen die
Philister und besetzten die Städte.

<<v8>>
8 Als am nächsten Tag die Philister kamen, um die Erschlagenen
auszuplündern, fanden sie Saul und seine drei Söhne, die auf dem Gebirge
von Gilboa gefallen waren.

<<v9>>
9 Sie schlugen ihm den Kopf ab, zogen ihm die Rüstung aus und schickten
beides im Land der Philister umher, um ihrem Götzentempel und dem Volk
die Siegesnachricht zu übermitteln.

<<v10>>
10 Die Rüstung Sauls legten sie im Astartetempel nieder; seinen Leichnam
aber hefteten sie an die Mauer von Bet-Schean. [fn:3]

<<v11>>
11 Als die Einwohner von Jabesch-Gilead hörten, was die Philister mit
Saul gemacht hatten, [fn:4]

<<v12>>
12 brachen alle kriegstüchtigen Männer auf, marschierten die ganze Nacht
hindurch und nahmen die Leiche Sauls und die Leichen seiner Söhne von
der Mauer von Bet-Schean ab; sie brachten sie nach Jabesch und
verbrannten sie dort. [fn:5]

<<v13>>
13 Dann nahmen sie die Gebeine, begruben sie unter der Tamariske von
Jabesch und fasteten sieben Tage lang.\\
\\

* Footnotes

[fn:1] (1-13) [[file:1.Chr_10.org::v1][1 Chr 10,1-12]]

[fn:2] (5-6) [[file:1.Sam_28.org::v19][28,19]]

[fn:3] Bet-Schean: südöstlich der Jesreelebene.

[fn:4] (11f) [[file:1.Sam_11.org::v1][11,1-11]]; [[file:2.Sam_21.org::v12][2 Sam 21,12]]

[fn:5] sie brachten sie: Text korr. nach G; H: sie kamen.
