#+TITLE: 1 Sam 22 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-07 Di 11:47]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Sam 22.html

* 1.Sam 22

<<verses>>

<<v1>>
1 Darum ging David von dort weg und brachte sich in der Höhle von
Adullam in Sicherheit. Als seine Brüder und seine Familie davon hörten,
kamen sie zu ihm hinab. [fn:1]

<<v2>>
2 Auch schlossen sich ihm viele Männer an, die unter Druck standen,
sowie alle möglichen Leute, die Schulden hatten oder verbittert waren,
und er wurde ihr Anführer. So waren etwa vierhundert Mann um ihn.

<<v3>>
3 Von dort zog David nach Mizpe-Moab und sagte zum König von Moab: Mein
Vater und meine Mutter möchten (von zu Hause) wegziehen und bei euch
bleiben, bis ich weiß, was Gott mit mir vorhat.

<<v4>>
4 So brachte er seine Eltern zum König von Moab und sie blieben bei ihm,
solange David sich in den unzugänglichen Bergen aufhielt.

<<v5>>
5 Der Prophet Gad aber sagte zu David: Bleib nicht in den Bergen,
sondern zieh weg und geh wieder ins Land Juda! Und David zog weg und kam
nach Jaar-Heret. [fn:2]\\
\\

<<v6>>
* Sauls Rache an den Priestern von Nob: 22,6-23

6 Saul hörte, David und die Männer, die er bei sich hatte, seien
entdeckt worden. Er saß gerade in Gibea unter der Tamariske auf der
Höhe. Er hatte den Speer in der Hand und alle seine Diener standen um
ihn herum.

<<v7>>
7 Da sagte Saul zu seinen Dienern, die um ihn standen: Hört her, ihr
Benjaminiter! Euch allen wird wohl der Sohn Isais Felder und Weinberge
geben und euch zu Obersten von Tausendschaften und Hundertschaften
machen,

<<v8>>
8 weil ihr euch alle gegen mich verschworen habt. Keiner hat mir etwas
davon gesagt, als mein Sohn einen Bund mit dem Sohn Isais schloss, und
keinem tat es Leid um mich, sodass er mir mitgeteilt hätte, dass mein
Sohn meinen Knecht dazu angestiftet hat, mir aufzulauern, wie es jetzt
der Fall ist.

<<v9>>
9 Da antwortete der Edomiter Doëg, der bei den Dienern Sauls stand: Ich
habe den Sohn Isais gesehen, wie er gerade nach Nob zu Ahimelech, dem
Sohn Ahitubs, kam. [fn:3]

<<v10>>
10 Ahimelech befragte für ihn den Herrn und gab ihm Verpflegung; auch
das Schwert des Philisters Goliat gab er ihm.

<<v11>>
11 Darauf schickte der König jemand hin und ließ den Priester Ahimelech,
den Sohn Ahitubs, rufen sowie alle vom Haus seines Vaters, die Priester
von Nob. Als sie alle zum König gekommen waren,

<<v12>>
12 sagte Saul: Hör her, Sohn Ahitubs! Er antwortete: Hier bin ich, mein
Herr.

<<v13>>
13 Saul sagte zu ihm: Warum habt ihr euch gegen mich verschworen, du und
der Sohn Isais? Du hast ihm doch Brot und ein Schwert gegeben und für
ihn Gott befragt, sodass er sich gegen mich erheben und mir auflauern
kann, wie es heute der Fall ist.

<<v14>>
14 Ahimelech erwiderte dem König: Wer hat sich denn von allen deinen
Dienern so sehr bewährt wie David, der Schwiegersohn des Königs, der
Anführer deiner Leibwache, der in deinem Haus hoch geehrt ist?

<<v15>>
15 Habe ich denn erst heute begonnen, für ihn Gott zu befragen?
Keineswegs! Der König möge seinem Knecht und dem ganzen Haus meines
Vaters nichts unterstellen; denn dein Knecht hat von all dem nichts
gewusst, weder Wichtiges noch Unwichtiges.

<<v16>>
16 Doch der König sagte: Du bist dem Tod verfallen, Ahimelech, du und
das ganze Haus deines Vaters.

<<v17>>
17 Und der König sagte den Läufern, die bei ihm standen: Umzingelt die
Priester des Herrn und tötet sie! Denn auch sie haben David die Hand
gereicht; sie haben gewusst, dass er auf der Flucht war, und mir nichts
davon berichtet. Aber die Diener des Königs wollten ihre Hand nicht
erheben, um die Priester des Herrn niederzustoßen.

<<v18>>
18 Da sagte der König zu Doëg: Komm her, stoß du die Priester nieder!
Der Edomiter Doëg ging zu den Priestern hin und stieß sie nieder. Er
brachte an jenem Tag fünfundachtzig Männer um, die das leinene Efod
trugen.

<<v19>>
19 Auch die Priesterstadt Nob schlug er mit scharfem Schwert: Die Männer
und Frauen, die Kinder und Säuglinge, die Rinder, Esel und Schafe
(erschlug er) mit scharfem Schwert.

<<v20>>
20 Nur ein einziger Sohn Ahimelechs, des Sohnes Ahitubs, namens Abjatar
konnte sich in Sicherheit bringen und zu David fliehen. [fn:4]

<<v21>>
21 Abjatar berichtete David, dass Saul die Priester des Herrn umgebracht
hatte.

<<v22>>
22 Da sagte David zu Abjatar: Ich wusste schon an jenem Tag, als der
Edomiter Doëg dort war, dass er Saul bestimmt alles berichten werde. Ich
selbst bin schuld am Tod all der Leute aus dem Haus deines Vaters. [fn:5]

<<v23>>
23 Bleib bei mir, fürchte dich nicht; denn der, der mir nach dem Leben
trachtet, trachtet auch dir nach dem Leben; bei mir bist du in
Sicherheit. [fn:6]\\
\\

* Footnotes

[fn:1] Adullam: südwestlich von Jerusalem.

[fn:2] [[file:2.Sam_24.org::v11][2 Sam 24,11]]; [[file:1.Chr_29.org::v29][1 Chr 29,29]]

[fn:3] [[file:1.Sam_21.org::v8][21,8]]; [[file:Ps_52.org::v2][Ps 52,2]]

[fn:4] [[file:1.Sam_23.org::v6][23,6]]; [[file:~/RoamNotes/notes/Bibel/nt/Mk_2.org::v26][Mk 2,26]]

[fn:5] Ich selbst bin schuld: Text korr. nach G.

[fn:6] [[file:1.Kön_2.org::v26][1 Kön 2,26]]
