#+TITLE: 1 Sam 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-06 Mo 22:34]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Sam 18.html


<<verses>>

<<v1>>
* Jonatans Freundschaft mit David: 18,1-9

1 Nach dem Gespräch Davids mit Saul schloss Jonatan David in sein Herz.
Und Jonatan liebte David wie sein eigenes Leben.

<<v2>>
2 Saul behielt David von jenem Tag an bei sich und ließ ihn nicht mehr
in das Haus seines Vaters zurückkehren. [fn:1]

<<v3>>
3 Jonatan schloss mit David einen Bund, weil er ihn wie sein eigenes
Leben liebte. [fn:2]

<<v4>>
4 Er zog den Mantel, den er anhatte, aus und gab ihn David, ebenso seine
Rüstung, sein Schwert, seinen Bogen und seinen Gürtel. [fn:3]

<<v5>>
5 David zog ins Feld und überall, wohin Saul ihn schickte, hatte er
Erfolg, sodass Saul ihn an die Spitze seiner Krieger stellte. David war
beim ganzen Volk und bei den Dienern Sauls beliebt.

<<v6>>
6 Als sie nach Davids Sieg über den Philister heimkehrten, zogen die
Frauen aus allen Städten Israels König Saul singend und tanzend mit
Handpauken, Freudenrufen und Zimbeln entgegen. [fn:4]\\
\\

<<v7>>
7 Die Frauen spielten und riefen voll Freude: Saul hat Tausend
erschlagen, /\\
 David aber Zehntausend.\\
\\

<<v8>>
8 Saul wurde darüber sehr zornig. Das Lied missfiel ihm und er sagte:
David geben sie Zehntausend, mir aber geben sie nur Tausend. Jetzt fehlt
ihm nur noch die Königswürde.

<<v9>>
9 Von diesem Tag an war Saul gegen David voll Argwohn.\\
\\

<<v10>>
* Sauls Feindschaft gegen David: 18,10-30

10 Am folgenden Tag kam über Saul wieder ein böser Gottesgeist, sodass
er in seinem Haus in Raserei geriet. David aber spielte wie jeden Tag.
Saul hatte den Speer in der Hand. [fn:5]

<<v11>>
11 Saul dachte: Ich will David an die Wand spießen!, und schleuderte den
Speer, aber David wich ihm zweimal aus. [fn:6]

<<v12>>
12 Und Saul begann sich vor David zu fürchten, weil der Herr mit David
war, Saul aber verlassen hatte.

<<v13>>
13 Darum entfernte Saul David aus seiner Umgebung und machte ihn zum
Obersten einer Tausendschaft. So zog David an der Spitze der Leute
hinaus (in den Krieg) und wieder heim.

<<v14>>
14 David hatte Erfolg, wohin ihn auch sein Weg führte, und der Herr war
mit ihm.

<<v15>>
15 Als Saul sah, dass David sehr erfolgreich war, bekam er noch mehr
Angst vor ihm.

<<v16>>
16 Ganz Israel und Juda aber liebte David, weil er an ihrer Spitze
hinaus (in den Krieg) und wieder heimzog.

<<v17>>
17 Saul sagte zu David: Hier ist meine älteste Tochter Merab. Ich will
sie dir zur Frau geben, wenn du dich mir als tapfer erweist und die
Kriege des Herrn führst. Saul dachte nämlich: Ich will nicht meine Hand
gegen ihn erheben; das sollen die Philister tun.

<<v18>>
18 David antwortete Saul: Wer bin ich denn und was ist schon meine Sippe
und die Verwandtschaft meines Vaters in Israel, dass ich der
Schwiegersohn des Königs werden sollte?

<<v19>>
19 Als aber dann die Zeit kam, in der Sauls Tochter Merab David zur Frau
gegeben werden sollte, wurde sie Adriël aus Mehola zur Frau gegeben. [fn:7]

<<v20>>
20 Sauls Tochter Michal liebte David; dies teilte man Saul mit. Es war
ihm recht;

<<v21>>
21 denn er sagte sich: Ich will sie ihm geben; sie soll ihm zum
Verhängnis werden, sodass er den Philistern in die Hände fällt. Saul
sagte zu David: Heute in zwei Jahren kannst du mein Schwiegersohn
werden. [fn:8]

<<v22>>
22 Seinen Dienern aber befahl Saul: Redet heimlich mit David und sagt:
Du siehst, dass der König Gefallen an dir hat und dass alle seine Diener
dich gern haben; du könntest sofort der Schwiegersohn des Königs werden.

<<v23>>
23 Sauls Diener redeten also in dieser Weise mit David. David aber
erwiderte: Scheint es euch so leicht zu sein, der Schwiegersohn des
Königs zu werden? Ich bin doch ein armer und geringer Mann.

<<v24>>
24 Die Diener berichteten Saul: Das und das hat David gesagt.

<<v25>>
25 Saul antwortete: So sollt ihr David sagen: Der König möchte keine
andere Brautgabe als die Vorhäute von hundert Philistern, um an den
Feinden des Königs Rache zu nehmen. Saul plante nämlich, David den
Philistern in die Hände fallen zu lassen.

<<v26>>
26 Seine Diener berichteten David, was Saul gesagt hatte, und es war
David recht, dass er so der Schwiegersohn des Königs werden sollte. Die
gesetzte Frist war noch nicht um,

<<v27>>
27 als David sich auf den Weg machte und mit seinen Leuten zog; er
erschlug zweihundert von den Philistern, brachte ihre Vorhäute zum König
und legte sie vollzählig vor ihn hin, um sein Schwiegersohn zu werden.
Und Saul gab ihm seine Tochter Michal zur Frau. [fn:9]

<<v28>>
28 Als Saul immer deutlicher erkannte, dass der Herr mit David war und
dass seine Tochter Michal ihn liebte,

<<v29>>
29 fürchtete er sich noch mehr vor David. So wurde Saul für alle Zeit
zum Feind Davids.

<<v30>>
30 Die Fürsten der Philister zogen (immer wieder) in den Kampf; sooft
sie aber ausrückten, hatte David mehr Erfolg als alle anderen Diener
Sauls, sodass sein Name immer mehr galt.\\
\\

* Footnotes

[fn:1] [[file:1.Sam_16.org::v22][16,22]]; [[file:1.Sam_17.org::v15][17,15]]

[fn:2] [[file:1.Sam_19.org::v1][19,1]]; [[file:1.Sam_20.org::v8][20,8]].[[file:1.Sam_20.org::v17][17]]; [[file:1.Sam_23.org::v18][23,18]]; [[file:2.Sam_1.org::v26][2 Sam 1,26]]; [[file:2.Sam_21.org::v7][21,7]]

[fn:3] Jonatan gibt symbolisch einen Teil seiner selbst als
Zeichen der Verbundenheit.

[fn:4] (6-7) [[file:1.Sam_21.org::v12][21,12]]; [[file:1.Sam_29.org::v5][29,5]]

[fn:5] [[file:1.Sam_16.org::v14][16,14]]

[fn:6] [[file:1.Sam_20.org::v33][20,33]]

[fn:7] [[file:2.Sam_21.org::v8][2 Sam 21,8]]

[fn:8] in zwei Jahren: Text korr., vgl. V. 26

[fn:9] [[file:2.Sam_3.org::v14][2 Sam 3,14]]
