#+TITLE: 1 Sam 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-06 Mo 22:07]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/1 Sam 17.html

<<verses>>

<<v1>>
* David und Goliat: 17,1-58

1 Die Philister zogen ihre Truppen zum Kampf zusammen. Sie versammelten
sich bei Socho, das zu Juda gehört, und schlugen zwischen Socho und
Aseka in Efes-Dammim ihr Lager auf. [fn:1]

<<v2>>
2 Auch Saul und die Männer Israels sammelten sich; sie schlugen ihr
Lager im Terebinthental auf und traten zum Kampf gegen die Philister an.

<<v3>>
3 Die Philister standen an dem Berg auf der einen Seite, die Israeliten
an dem Berg auf der anderen Seite; zwischen ihnen lag das Tal.

<<v4>>
4 Da trat aus dem Lager der Philister ein Vorkämpfer namens Goliat aus
Gat hervor. Er war sechs Ellen und eine Spanne groß.

<<v5>>
5 Auf seinem Kopf hatte er einen Helm aus Bronze und er trug einen
Schuppenpanzer aus Bronze, der fünftausend Schekel wog.

<<v6>>
6 Er hatte bronzene Schienen an den Beinen und zwischen seinen Schultern
hing ein Sichelschwert aus Bronze.

<<v7>>
7 Der Schaft seines Speeres war (so dick) wie ein Weberbaum und die
eiserne Speerspitze wog sechshundert Schekel. Sein Schildträger ging vor
ihm her.

<<v8>>
8 Goliat trat vor und rief zu den Reihen der Israeliten hinüber: Warum
seid ihr ausgezogen und habt euch zum Kampf aufgestellt? Bin ich nicht
ein Philister und seid ihr nicht die Knechte Sauls? Wählt euch doch
einen Mann aus! Er soll zu mir herunterkommen.

<<v9>>
9 Wenn er mich im Kampf erschlagen kann, wollen wir eure Knechte sein.
Wenn ich ihm aber überlegen bin und ihn erschlage, dann sollt ihr unsere
Knechte sein und uns dienen.

<<v10>>
10 Und der Philister sagte weiter: Heute habe ich die Reihen Israels
verhöhnt (und gesagt): Schickt mir doch einen Mann, damit wir
gegeneinander kämpfen können.

<<v11>>
11 Als Saul und ganz Israel diese Worte des Philisters hörten,
erschraken sie und hatten große Angst.

<<v12>>
12 David war der Sohn eines Efratiters namens Isai aus Betlehem in Juda,
der acht Söhne hatte. Zur Zeit Sauls war Isai bereits alt und betagt. [fn:2]

<<v13>>
13 Die drei ältesten Söhne Isais waren zusammen mit Saul in den Krieg
gezogen. Seine drei Söhne, die mit in den Krieg gezogen waren, hießen
Eliab - er war der Erstgeborene -, der zweite Abinadab, der dritte
Schima.

<<v14>>
14 Die drei Ältesten waren Saul gefolgt. David aber war der jüngste.

<<v15>>
15 David kehrte öfters vom Hof Sauls nach Betlehem zurück, um die Schafe
seines Vaters zu hüten. [fn:3]

<<v16>>
16 Der Philister kam jeden Morgen und Abend und stellte sich kampfbereit
hin - vierzig Tage lang.

<<v17>>
17 Eines Tages sagte Isai zu seinem Sohn David: Nimm für deine Brüder
ein Efa von diesem gerösteten Korn und diese zehn Brote und lauf damit
zu ihnen ins Lager.

<<v18>>
18 Und diese zehn Käse bring dem Obersten der Tausendschaft! Sieh nach,
ob es deinen Brüdern gut geht, und lass dir ein Pfand (als
Lebenszeichen) von ihnen geben!

<<v19>>
19 Saul ist mit ihnen und all den anderen Israeliten im Terebinthental
und sie kämpfen gegen die Philister.

<<v20>>
20 David brach früh am Morgen auf, überließ die Herde einem Wächter, lud
die Sachen auf und ging, wie es ihm Isai befohlen hatte. Als er zur
Wagenburg kam, rückte das Heer gerade in Schlachtordnung aus und ließ
den Kampfruf erschallen.

<<v21>>
21 Israel und die Philister stellten sich, Reihe gegen Reihe, zum Kampf
auf.

<<v22>>
22 David legte das Gepäck ab, überließ es dem Wächter des Trosses und
lief zur Schlachtreihe. Er ging zu seinen Brüdern und fragte, wie es
ihnen gehe.

<<v23>>
23 Während er noch mit ihnen redete, trat gerade aus den Reihen der
Philister ihr Vorkämpfer, der Philister namens Goliat aus Gat, hervor;
er rief die gewohnten Worte und David hörte es.

<<v24>>
24 Als die Israeliten den Mann sahen, hatten sie alle große Angst vor
ihm und flohen.

<<v25>>
25 Sie sagten: Habt ihr gesehen, wie dieser Mann daherkommt? Er kommt
doch nur, um Israel zu verhöhnen. Wer ihn erschlägt, den wird der König
sehr reich machen; er wird ihm seine Tochter geben und seine Familie
wird er von allen Steuern in Israel befreien.

<<v26>>
26 David fragte die Männer, die bei ihm standen: Was wird man für den
Mann tun, der diesen Philister erschlägt und die Schande von Israel
wegnimmt? Wer ist denn dieser unbeschnittene Philister, dass er die
Schlachtreihen des lebendigen Gottes verhöhnen darf?

<<v27>>
27 Die Leute antworteten ihm dasselbe: Das und das wird man dem tun, der
ihn erschlägt.

<<v28>>
28 Sein ältester Bruder Eliab hörte, wie er mit den Männern redete, und
er wurde zornig auf David. Er sagte: Wozu bist du denn hergekommen? Wem
hast du denn die paar Schafe in der Wüste überlassen? Ich kenne doch
deine Keckheit und die Bosheit in dir. Du bist nur hergekommen, um den
Kampf zu sehen.

<<v29>>
29 David erwiderte: Was habe ich denn jetzt wieder getan? Ich habe doch
nur gefragt.

<<v30>>
30 Dann wandte er sich von ihm ab und einem anderen zu und fragte ihn
dasselbe. Die Leute antworteten ihm wie beim ersten Mal.

<<v31>>
31 Als bekannt wurde, was David gesagt hatte, berichtete man davon auch
in Sauls Umgebung und Saul ließ ihn holen.

<<v32>>
32 David sagte zu Saul: Niemand soll wegen des Philisters den Mut sinken
lassen. Dein Knecht wird hingehen und mit diesem Philister kämpfen.

<<v33>>
33 Saul erwiderte ihm: Du kannst nicht zu diesem Philister hingehen, um
mit ihm zu kämpfen; du bist zu jung, er aber ist ein Krieger seit seiner
Jugend.

<<v34>>
34 David sagte zu Saul: Dein Knecht hat für seinen Vater die Schafe
gehütet. Wenn ein Löwe oder ein Bär kam und ein Lamm aus der Herde
wegschleppte,

<<v35>>
35 lief ich hinter ihm her, schlug auf ihn ein und riss das Tier aus
seinem Maul. Und wenn er sich dann gegen mich aufrichtete, packte ich
ihn an der Mähne und schlug ihn tot.

<<v36>>
36 Dein Knecht hat den Löwen und den Bären erschlagen und diesem
unbeschnittenen Philister soll es genauso ergehen wie ihnen, weil er die
Schlachtreihen des lebendigen Gottes verhöhnt hat.

<<v37>>
37 Und David sagte weiter: Der Herr, der mich aus der Gewalt des Löwen
und des Bären gerettet hat, wird mich auch aus der Gewalt dieses
Philisters retten. Da antwortete Saul David: Geh, der Herr sei mit dir.

<<v38>>
38 Und Saul zog David seine Rüstung an; er setzte ihm einen bronzenen
Helm auf den Kopf und legte ihm seinen Panzer an,

<<v39>>
39 und über der Rüstung hängte er ihm sein Schwert um. David versuchte
(in der Rüstung) zu gehen, aber er war es nicht gewohnt. Darum sagte er
zu Saul: Ich kann in diesen Sachen nicht gehen, ich bin nicht daran
gewöhnt. Und er legte sie wieder ab,

<<v40>>
40 nahm seinen Stock in die Hand, suchte sich fünf glatte Steine aus dem
Bach und legte sie in die Hirtentasche, die er bei sich hatte (und) die
(ihm als) Schleudersteintasche (diente). Die Schleuder in der Hand, ging
er auf den Philister zu.

<<v41>>
41 Der Philister kam immer näher an David heran; sein Schildträger
schritt vor ihm her.

<<v42>>
42 Voll Verachtung blickte der Philister David an, als er ihn sah; denn
David war noch sehr jung, er war blond und von schöner Gestalt. [fn:4]

<<v43>>
43 Der Philister sagte zu David: Bin ich denn ein Hund, dass du mit
einem Stock zu mir kommst? Und er verfluchte David bei seinen Göttern.

<<v44>>
44 Er rief David zu: Komm nur her zu mir, ich werde dein Fleisch den
Vögeln des Himmels und den wilden Tieren (zum Fraß) geben.

<<v45>>
45 David antwortete dem Philister: Du kommst zu mir mit Schwert, Speer
und Sichelschwert, ich aber komme zu dir im Namen des Herrn der Heere,
des Gottes der Schlachtreihen Israels, den du verhöhnt hast.

<<v46>>
46 Heute wird dich der Herr mir ausliefern. Ich werde dich erschlagen
und dir den Kopf abhauen. Die Leichen des Heeres der Philister werde ich
noch heute den Vögeln des Himmels und den wilden Tieren (zum Fraß)
geben. Alle Welt soll erkennen, dass Israel einen Gott hat.

<<v47>>
47 Auch alle, die hier versammelt sind, sollen erkennen, dass der Herr
nicht durch Schwert und Speer Rettung verschafft; denn es ist ein Krieg
des Herrn und er wird euch in unsere Gewalt geben.

<<v48>>
48 Als der Philister weiter vorrückte und immer näher an David herankam,
lief auch David von der Schlachtreihe (der Israeliten) aus schnell dem
Philister entgegen.

<<v49>>
49 Er griff in seine Hirtentasche, nahm einen Stein heraus, schleuderte
ihn ab und traf den Philister an der Stirn. Der Stein drang in die Stirn
ein und der Philister fiel mit dem Gesicht zu Boden.

<<v50>>
50 So besiegte David den Philister mit einer Schleuder und einem Stein;
er traf den Philister und tötete ihn, ohne ein Schwert in der Hand zu
haben.

<<v51>>
51 Dann lief David hin und trat neben den Philister. Er ergriff sein
Schwert, zog es aus der Scheide, schlug ihm den Kopf ab und tötete ihn.
Als die Philister sahen, dass ihr starker Mann tot war, flohen sie.

<<v52>>
52 Die Männer von Israel und Juda aber griffen an, erhoben das
Kriegsgeschrei und verfolgten die Philister bis nach Gat und bis vor die
Tore von Ekron. Von Schaarajim bis nach Gat und Ekron lagen die
erschlagenen Philister am Weg. [fn:5]

<<v53>>
53 Nach der Verfolgung kehrten die Israeliten zurück und plünderten das
Lager der Philister.

<<v54>>
54 David nahm den Kopf des Philisters und brachte ihn nach Jerusalem.
Goliats Waffen aber legte er in sein Zelt. [fn:6]

<<v55>>
55 Als Saul David dem Philister entgegengehen sah, sagte er zu Abner,
seinem Heerführer: Abner, wessen Sohn ist der junge Mann? Abner
antwortete: So wahr du lebst, König, ich weiß es nicht.

<<v56>>
56 Der König sagte: Dann erkundige dich, wessen Sohn der Knabe ist.

<<v57>>
57 Als David zurückkehrte, nachdem er den Philister erschlagen hatte,
nahm ihn Abner mit und führte ihn zu Saul. David hatte den Kopf des
Philisters noch in der Hand.

<<v58>>
58 Saul fragte ihn: Wessen Sohn bist du, junger Mann? David antwortete:
Der Sohn deines Knechtes Isai aus Betlehem.\\
\\

* Footnotes

[fn:1] Socho: westlich von Betlehem. - Der Text des Kapitels
lässt erkennen, dass verschiedene Überlieferungen über David miteinander
verbunden wurden.

[fn:2] [[file:1.Sam_16.org::v10][16,10]]

[fn:3] [[file:1.Sam_18.org::v2][18,2]]

[fn:4] [[file:1 Sam 16::v12][16,12]]

[fn:5] nach Gat: Text korr., vgl. G und die zweite Vershälfte;
H: bis zu einem Tal.

[fn:6] [[file:1.Sam_21.org::v10][21,10]]
