#+TITLE: 2 Chr 24 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 22:57]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Chr 24.html

<<verses>>

<<v1>>
* Joasch: 24,1-27

1 Joasch war sieben Jahre alt, als er König wurde, und regierte vierzig
Jahre in Jerusalem. Seine Mutter hieß Zibja und stammte aus Beerscheba. [fn:1]

<<v2>>
2 Joasch tat, was dem Herrn gefiel, solange der Priester Jojada lebte.

<<v3>>
3 Jojada warb für ihn zwei Frauen und er zeugte Söhne und Töchter.

<<v4>>
4 Danach fasste Joasch den Entschluss, das Haus des Herrn zu erneuern.

<<v5>>
5 Er ließ die Priester und die Leviten zusammenkommen und sagte zu
ihnen: Geht in die Städte Judas und sammelt Geld von ganz Israel, um
Jahr für Jahr Ausbesserungen am Haus eures Gottes vornehmen zu können.
Beeilt euch dabei! Als sich aber die Leviten nicht beeilten,

<<v6>>
6 rief Joasch den Oberpriester Jojada zu sich und hielt ihm vor: Warum
hast du die Leviten nicht angehalten, von Juda und Jerusalem die Abgabe
zu erheben, die Mose, der Knecht des Herrn, und die Versammlung Israels
für das Zelt der Bundesurkunde vorgeschrieben haben? [fn:2]

<<v7>>
7 Die ruchlose Atalja und ihre Bauleute haben das Haus Gottes verfallen
lassen und sogar die Weihegaben des Hauses des Herrn für die Baale
verwendet.

<<v8>>
8 Der König ließ nun einen Kasten anfertigen und außen am Tor des Hauses
des Herrn aufstellen.

<<v9>>
9 Dann rief man in Juda und Jerusalem aus, man solle die Abgabe für den
Herrn entrichten, die Mose, der Knecht Gottes, den Israeliten in der
Wüste befohlen hat.

<<v10>>
10 Alle führenden Männer und das ganze Volk waren darüber erfreut. Sie
brachten ihre Beiträge und warfen sie in den Kasten, bis er voll war.

<<v11>>
11 Zu bestimmten Zeiten ließ man den Kasten durch Leviten zur
Überprüfung zum König bringen. Wenn man sah, dass viel Geld darin war,
kamen der Schreiber des Königs und der Beauftragte des Oberpriesters,
leerten den Kasten und trugen ihn wieder an seinen Platz zurück. Das
taten sie Tag für Tag und brachten viel Geld zusammen.

<<v12>>
12 Der König und Jojada übergaben es den Werkmeistern, die am Haus des
Herrn tätig waren, und diese bestellten Maurer und Zimmerleute sowie
Eisen- und Bronzeschmiede, die das Haus des Herrn erneuern und seine
Schäden beseitigen sollten.

<<v13>>
13 Die Werkmeister griffen zu und unter ihrer Leitung gingen die
Ausbesserungsarbeiten gut voran. Sie stellten das Haus Gottes nach
seinen Plänen wieder her und erhöhten seine Festigkeit.

<<v14>>
14 Als sie fertig waren, brachten sie den Rest des Geldes vor den König
und vor Jojada und dieser ließ dafür Geräte für das Haus des Herrn,
Kult- und Opfergeräte, Schalen und sonstige Gefäße aus Gold und Silber
anfertigen. Solange Jojada lebte, wurden ständig im Haus des Herrn Opfer
dargebracht.

<<v15>>
15 Jojada aber wurde alt und satt an Lebenstagen; er war hundertdreißig
Jahre alt, als er starb.

<<v16>>
16 Man begrub ihn bei den Königen in der Davidstadt; denn er hatte an
Israel, für Gott und sein Haus, Gutes getan.

<<v17>>
17 Nach dem Tod Jojadas kamen die führenden Männer Judas zum König und
warfen sich vor ihm nieder. Dieser hörte damals auf sie,

<<v18>>
18 sodass sie den Bund des Herrn, des Gottes ihrer Väter, verließen und
die Kultpfähle und Götzenbilder verehrten. Wegen dieser Schuld kam ein
Zorngericht über Juda und Jerusalem.

<<v19>>
19 Der Herr schickte Propheten zu ihnen, um sie zur Umkehr zum Herrn zu
bewegen, aber man hörte nicht auf ihre Warnung.

<<v20>>
20 Da kam der Geist Gottes über Secharja, den Sohn des Priesters Jojada.
Er trat vor das Volk und hielt ihm vor: So spricht Gott: Warum
übertretet ihr die Gebote des Herrn? So könnt ihr kein Glück mehr haben.
Weil ihr den Herrn verlassen habt, wird er euch verlassen. [fn:3]

<<v21>>
21 Sie aber taten sich gegen ihn zusammen und steinigten ihn auf Befehl
des Königs im Hof des Hauses des Herrn. [fn:4]

<<v22>>
22 König Joasch dachte nicht mehr an die Treue, mit der ihm Jojada, der
Vater Secharjas, gedient hatte, sondern ließ dessen Sohn töten. Dieser
aber rief sterbend aus: Der Herr möge es sehen und vergelten.

<<v23>>
23 Um die Jahreswende zog das Heer der Aramäer gegen Joasch. Sie drangen
nach Juda und Jerusalem vor und machten alle führenden Männer des Volkes
nieder. Ihre gesamte Beute brachte man zum König von Damaskus.

<<v24>>
24 Mit nur wenig Kriegern war das Heer der Aramäer gekommen; aber der
Herr gab ein sehr großes Heer in ihre Gewalt, weil die Israeliten den
Herrn, den Gott ihrer Väter, verlassen hatten. So vollzogen die Aramäer
an Joasch das Strafgericht.

<<v25>>
25 Als sie abzogen und ihn schwer krank zurückließen, verschworen sich
seine Diener gegen ihn wegen der Blutschuld am Sohn des Priesters Jojada
und erschlugen ihn auf seinem Bett. Man begrub ihn in der Davidstadt,
aber nicht in den Gräbern der Könige.

<<v26>>
26 Die Verschwörer waren Sabad, der Sohn der Ammoniterin Schimat, und
Josabad, der Sohn der Moabiterin Schomer.

<<v27>>
27 Weitere Nachrichten über seine Söhne, über die vielen
Prophetensprüche gegen ihn und über die Wiederherstellung des Hauses
Gottes sind aufgezeichnet in den Erläuterungen zum Buch der Könige. Sein
Sohn Amazja wurde König an seiner Stelle.\\
\\

* Footnotes

[fn:1] (1-27) [[file:1.Kön_12.org::v1][2 Kön 12,1]]-[[file:1.Kön_12.org::v22][22]]

[fn:2] [[file:Ex_30.org::v12][Ex 30,12]]-[[file:Ex_30.org::v16][16]]; [[file:Ex_38.org::v24][38,24]]-[[file:Ex_38.org::v26][26]]

[fn:3] [[file:2.Chr_15.org::v2][15,2]]

[fn:4] Darauf bezieht sich das Wort Jesu in [[file:~/Documents/notes/Bibel/nt/Mt_23.org::v35][Mt 23,35]].
