#+TITLE: 2 Chr 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 22:20]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 15.html

<<verses>>

<<v1>>
* Die Bundeserneuerung unter Asa: 15,1-18

1 Über Asarja, den Sohn Odeds, kam der Geist Gottes.

<<v2>>
2 Er ging zu Asa hinaus und sagte zu ihm: Hört mich an, Asa und ihr alle
von Juda und Benjamin! Der Herr ist mit euch, wenn ihr zu ihm haltet.
Wenn ihr ihn sucht, lässt er sich von euch finden; wenn ihr ihn aber
verlasst, verlässt er euch.

<<v3>>
3 Lange Zeit lebte Israel ohne den wahren Gott, ohne einen belehrenden
Priester, ohne Gesetz. [fn:1]

<<v4>>
4 In ihrer Not bekehrten sie sich zum Herrn, dem Gott Israels, und da
sie ihn suchten, ließ er sich von ihnen finden.

<<v5>>
5 In jenen Zeiten konnte niemand sicher aus- und eingehen, denn große
Unruhe lag über allen Bewohnern der Länder.

<<v6>>
6 Ein Volk wurde vom andern bedrängt, eine Stadt von der andern, denn
Gott beunruhigte sie durch allerlei Not.

<<v7>>
7 Ihr aber, seid stark! Eure Hände sollen nicht erschlaffen, denn euer
Tun wird seinen Lohn finden.

<<v8>>
8 Als Asa diese Worte und Weissagungen des Propheten Asarja, des Sohnes
Odeds, hörte, entfernte er mutig die Götzenbilder aus dem ganzen Gebiet
von Juda und Benjamin sowie aus den Städten, die er im Gebirge Efraim
erobert hatte. Auch erneuerte er den Altar des Herrn, der vor dem Tempel
des Herrn stand. [fn:2]

<<v9>>
9 Dann versammelte er ganz Juda und Benjamin sowie die Leute von Efraim,
Manasse und Simeon, die sich bei ihnen aufhielten. Sehr viele waren
nämlich aus Israel zu ihm übergegangen, als sie sahen, dass der Herr,
sein Gott, mit ihm war.

<<v10>>
10 Im dritten Monat des fünfzehnten Jahres der Regierung Asas kamen sie
in Jerusalem zusammen

<<v11>>
11 und opferten an jenem Tag dem Herrn siebenhundert Rinder und
siebentausend Schafe von der Beute, die sie gemacht hatten.

<<v12>>
12 Sie gingen die Verpflichtung ein, mit ganzem Herzen und ganzer Seele
den Herrn, den Gott ihrer Väter, zu suchen.

<<v13>>
13 Wer aber nicht den Herrn, den Gott Israels, suchen würde, sollte
getötet werden, sei er klein oder groß, Mann oder Frau.

<<v14>>
14 Das schworen sie dem Herrn mit lauter Stimme, unter Freudenrufen,
beim Schall der Trompeten und Hörner.

<<v15>>
15 Ganz Juda freute sich über den Schwur, denn sie hatten ihn mit ganzem
Herzen geleistet. Und da sie mit bestem Willen den Herrn suchten, ließ
er sich von ihnen finden und verschaffte ihnen ringsum Ruhe.

<<v16>>
16 König Asa enthob auch seine Großmutter Maacha ihrer Stellung als
Herrin, weil sie der Aschera ein Schandbild errichtet hatte. Er ließ das
Schandbild umhauen, es zertrümmern und im Kidrontal verbrennen. [fn:3]

<<v17>>
17 Nur die Kulthöhen verschwanden nicht aus Israel. Doch das Herz Asas
war ungeteilt (beim Herrn), solange er lebte.

<<v18>>
18 Er brachte auch die Weihegaben seines Vaters und seine eigenen
Weihegaben in das Haus Gottes: Silber, Gold und allerlei Geräte.\\
\\

<<v19>>
* Der Krieg Asas mit dem Nordreich: 15,19 - 16,10

19 Es gab keinen Krieg bis zum fünfunddreißigsten Jahr der Regierung
Asas. [fn:4] [fn:5]

* Footnotes

[fn:1] 3-6: Die Verse beschreiben die Zeit der Richter.

[fn:2] Asarja, des Sohnes: Text sinngemäß ergänzt.

[fn:3] (16-18) 1 Kön 15,13-15

[fn:4] (19-16,6) 1 Kön 15,17-22

[fn:5] 19-16,1: Die Zahlen 35 und 36 beruhen auf einem Versehen
des Schreibers, da Bascha schon im 26. Jahr Asas starb (vgl. 1 Kön
16,8).
