#+TITLE: 2 Chr 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 22:10]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 12.html

* 2.Chr 12

<<verses>>

<<v1>>
1 Als aber seine Herrschaft gefestigt und er stark geworden war, fiel er
mit ganz Israel vom Gesetz des Herrn ab.

<<v2>>
2 Im fünften Jahr des Königs Rehabeam zog Schischak, der König von
Ägypten, gegen Jerusalem, da sie dem Herrn untreu geworden waren. [fn:1]

<<v3>>
3 Er kam mit zwölfhundert Wagen und sechzigtausend Wagenkämpfern.
Zahllos war das Kriegsvolk, das mit ihm aus Ägypten kam: Libyer,
Sukkijiter und Kuschiter.

<<v4>>
4 Er eroberte die Festungen in Juda und rückte vor Jerusalem.

<<v5>>
5 Damals kam der Prophet Schemaja zu Rehabeam und zu den führenden
Leuten Judas, die sich vor Schischak nach Jerusalem zurückgezogen
hatten, und sagte zu ihnen: So spricht der Herr: Ihr habt mich
verlassen; darum verlasse auch ich euch und übergebe euch der Hand
Schischaks.

<<v6>>
6 Doch nun demütigten sich die führenden Leute Israels und der König und
sagten: Der Herr ist gerecht.

<<v7>>
7 Als der Herr sah, dass sie sich demütigten, erging das Wort des Herrn
an Schemaja: Sie haben sich gedemütigt; darum werde ich sie nicht
verderben. Bald werde ich ihnen Rettung bringen und mein Zorn soll sich
nicht durch Schischak über Jerusalem ergießen.

<<v8>>
8 Doch sollen sie ihm untertan werden, damit sie den Unterschied
zwischen meinem Dienst und dem Dienst der irdischen Reiche erfahren. [fn:2]

<<v9>>
9 Schischak, der König von Ägypten, zog also gegen Jerusalem. Er raubte
die Schätze des Tempels und die Schätze des königlichen Palastes und
nahm alles weg, auch die goldenen Schilde, die Salomo hatte anfertigen
lassen. [fn:3]

<<v10>>
10 An deren Stelle ließ König Rehabeam bronzene anfertigen und übergab
sie den Befehlshabern der Läufer, die den Eingang zum Haus des Königs
bewachten. [fn:4]

<<v11>>
11 Sooft nun der König in das Haus des Herrn ging, kamen die Läufer,
trugen die Schilde und brachten sie dann wieder in ihre Wachstube
zurück.

<<v12>>
12 Da der König sich demütigte, ließ der Zorn des Herrn von ihm ab,
sodass er ihn nicht ganz zugrunde richtete. Es gab ja in Juda noch
manches Gute.

<<v13>>
13 So gewann König Rehabeam wieder festen Halt in Jerusalem und
herrschte weiter als König. Er war einundvierzig Jahre alt, als er König
wurde, und regierte siebzehn Jahre in Jerusalem, der Stadt, die der Herr
aus allen Stämmen Israels erwählt hatte, um seinen Namen dorthin zu
legen. Seine Mutter hieß Naama und war eine Ammoniterin.

<<v14>>
14 Er tat Böses und war nicht darauf bedacht, den Herrn zu suchen.

<<v15>>
15 Die frühere und die spätere Geschichte Rehabeams ist aufgezeichnet in
der Geschichte des Propheten Schemaja und des Sehers Iddo. Sie enthalten
auch seinen Stammbaum. Der Krieg zwischen Rehabeam und Jerobeam dauerte
die ganze Zeit an.

<<v16>>
16 Rehabeam entschlief zu seinen Vätern und wurde in der Davidstadt
begraben. Sein Sohn Abija wurde König an seiner Stelle.\\
\\

* Footnotes

[fn:1] [[file:1.Kön_14.org::v25][1 Kön 14,25]]

[fn:2] Die Forderungen Gottes sind leichter zu erfüllen als die
Ansprüche der Menschen (vgl. [[file:1.Chr_21.org::v13][1 Chr 21,13]]).

[fn:3] (9-16) [[file:1.Kön_14.org::v26][1 Kön 14,26-28]]

[fn:4] Läufer: vgl. die Anmerkung zu [[file:1.Kön_14.org::v27][1 Kön 14,27]].
