#+TITLE: 2 Chr 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-21 Di 22:33]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 2.html

* 2.Chr 2

<<verses>>

<<v1>>
1 Er ließ 70000 Lastträger und 80000 Steinhauer im Gebirge auszählen und
setzte 3600 Aufseher über sie.

<<v2>>
2 Dann sandte er Boten zu Hiram, dem König von Tyrus, und ließ ihm
sagen: Du hast meinem Vater David geholfen und ihm Zedern geliefert,
damit er sich ein Haus als Wohnung bauen konnte. [fn:1]

<<v3>>
3 Ich möchte jetzt dem Namen des Herrn, meines Gottes, ein Haus bauen
und es ihm weihen. Man soll wohlriechendes Räucherwerk vor ihm anzünden,
ständig die Brote auflegen und jeden Morgen und jeden Abend, an den
Sabbaten, Neumondtagen und Festen des Herrn, unseres Gottes, Brandopfer
darbringen. So ist es Israel für ewige Zeiten zur Pflicht gemacht
worden. [fn:2]

<<v4>>
4 Das Haus, das ich bauen will, soll groß werden, denn unser Gott ist
größer als alle Götter.

<<v5>>
5 Wer aber besitzt die Kraft, ihm ein Haus zu bauen? Der Himmel und die
Himmel der Himmel fassen ihn nicht. Und wer bin ich, dass ich ihm ein
Haus baue, wenn auch nur, um Rauchopfer vor ihm darzubringen? [fn:3]

<<v6>>
6 Schick mir nun einen fähigen Mann, der Arbeiten in Gold, Silber,
Bronze, Eisen, rotem Purpur, Karmesin und blauem Purpur ausführen kann
und sich aufs Gravieren versteht. Er soll mit den Künstlern
zusammenarbeiten, die bei mir in Juda und Jerusalem sind und die mein
Vater David bestellt hat.

<<v7>>
7 Liefere mir auch Zedern, Zypressen und Algummimholz vom Libanon! Ich
weiß, dass deine Leute die Bäume des Libanon zu fällen verstehen. Meine
Leute sollen deinen Leuten dabei helfen. [fn:4]

<<v8>>
8 Sie sollen eine Menge Holz herrichten; denn das Haus, das ich bauen
will, soll groß und wunderbar werden.

<<v9>>
9 Den Arbeitern, die das Holz fällen, gebe ich zum Unterhalt für deine
Knechte 20000 Kor Weizen, 20000 Kor Gerste, 20000 Bat Wein und 20000 Bat
Öl. [fn:5]

<<v10>>
10 Hiram, der König von Tyrus, antwortete Salomo in einem Schreiben, das
er ihm sandte: Weil der Herr sein Volk liebt, hat er dich ihm als König
gegeben.

<<v11>>
11 Ferner schrieb Hiram: Gepriesen sei der Herr, der Gott Israels, der
Himmel und Erde gemacht hat. Er hat dem König David einen weisen Sohn
gegeben, der Einsicht und Verstand besitzt, um ein Haus für den Herrn
und eine königliche Residenz für sich selbst zu bauen.

<<v12>>
12 Ich schicke dir einen fähigen, klugen Mann, Hiram-Abi, [fn:6]

<<v13>>
13 den Sohn einer danitischen Frau. Sein Vater stammt aus Tyrus. Er
versteht es, Arbeiten in Gold, Silber, Bronze, Eisen, Stein, Holz, rotem
und blauem Purpur, Byssus und Karmesin auszuführen, alle Gravierungen zu
besorgen und jeden Plan zu entwerfen, der ihm aufgetragen wird. Er wird
mit deinen Künstlern und den Künstlern meines Herrn, deines Vaters
David, zusammenarbeiten.

<<v14>>
14 Den Weizen, die Gerste, das Öl und den Wein, von denen mein Herr
gesprochen hat, möge er seinen Knechten liefern.

<<v15>>
15 Wir aber werden die Bäume auf dem Libanon fällen, so viele du nötig
hast, und sie dir in Flößen auf dem Meer nach Jafo schaffen. Du magst
sie dann nach Jerusalem hinaufbringen.

<<v16>>
16 Salomo ließ nun alle Fremden zählen, die im Land Israel wohnten,
nachdem schon sein Vater David eine Zählung unter ihnen vorgenommen
hatte. Es fanden sich 153600 Mann.

<<v17>>
17 Von diesen machte er 70000 zu Lastträgern, 80000 zu Steinhauern im
Gebirge und 3600 zu Aufsehern, die das Volk zur Arbeit anhalten
sollten.\\
\\

* Footnotes

[fn:1] (2-17) [[file:1.Kön_5.org::v15][1 Kön 5,15-32]]

[fn:2] Das Brot, das aufgelegt wird, sind die Schaubrote (vgl. [[file:Lev_24.org::v6][Lev 24,6]]).

[fn:3] [[file:1.Kön_8.org::v27][1 Kön 8,27]]

[fn:4] Zu Algummim (Almuggim) vgl. die Anmerkung zu [[file:1.Kön_10.org::v11][1 Kön 10,11]].

[fn:5] zum Unterhalt: Text korr. nach G und [[file:1.Kön_5.org::v25][1 Kön 5,25]]. 1 Kön
spricht nur von 20000 Kor Weizen und 20 Kor (= 200 Bat) Öl.

[fn:6] [[file:1.Kön_7.org::v13][1 Kön 7,13f]]
