#+TITLE: 2 Chr 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 22:31]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 18.html

<<verses>>

<<v1>>
1 So wurden Joschafat Reichtum und Ehre in hohem Maß zuteil.\\
* Joschafats Teilnahme am Feldzug Ahabs: 18,1 - 19,3

Joschafat verschwägerte sich mit Ahab. [fn:1] [fn:2]

<<v2>>
2 Als er nach einigen Jahren zu Ahab nach Samaria kam, ließ Ahab für ihn
und seine Leute eine Menge Schafe und Rinder schlachten und überredete
ihn, gegen Ramot-Gilead in den Krieg zu ziehen.

<<v3>>
3 Ahab, der König von Israel, fragte Joschafat, den König von Juda:
Würdest du mit mir gegen Ramot-Gilead ziehen? Er antwortete: Ich ziehe
mit dir, mein Volk mit deinem Volk. Ich nehme mit dir am Krieg teil.

<<v4>>
4 Joschafat bat aber den König von Israel: Befrag doch zuvor den Herrn!

<<v5>>
5 Da versammelte der König von Israel die Propheten, vierhundert Mann,
und fragte sie: Soll ich gegen Ramot-Gilead zu Felde ziehen oder soll
ich es lassen? Sie gaben den Bescheid: Zieh hinauf! Gott gibt die Stadt
in die Hand des Königs.

<<v6>>
6 Doch Joschafat sagte: Ist hier sonst kein Prophet des Herrn, den wir
befragen könnten?

<<v7>>
7 Der König von Israel antwortete Joschafat: Es ist noch einer da, durch
den wir den Herrn befragen könnten. Doch ich hasse ihn; denn er weissagt
mir nie Gutes, sondern immer nur Schlimmes. Es ist Micha, der Sohn
Jimlas. Joschafat erwiderte: Der König sage das nicht.

<<v8>>
8 Da rief der König von Israel einen Hofbeamten herbei und befahl ihm,
unverzüglich Micha, den Sohn Jimlas, zu holen.

<<v9>>
9 Der König von Israel und Joschafat, der König von Juda, saßen in
königlichen Gewändern auf ihren Thronen. Sie befanden sich auf der Tenne
beim Tor Samarias und alle Propheten weissagten vor ihnen.

<<v10>>
10 Zidkija, der Sohn Kenaanas, hatte sich eiserne Hörner gemacht und
rief: So spricht der Herr: Mit diesen wirst du die Aramäer niederstoßen,
bis du sie vernichtet hast.

<<v11>>
11 Alle Propheten weissagten in gleicher Weise und riefen: Zieh nach
Ramot-Gilead und sei erfolgreich; der Herr gibt die Stadt in die Hand
des Königs.

<<v12>>
12 Der Bote aber, der Micha holen sollte, redete ihm zu: Die Worte der
Propheten waren ohne Ausnahme günstig für den König. Mögen deine Worte
ihren Worten gleichen. Sag daher Gutes an!

<<v13>>
13 Doch Micha erwiderte: So wahr der Herr lebt: Nur was Gott mir sagt,
werde ich sagen.

<<v14>>
14 Als er zum König kam, fragte ihn dieser: Micha, sollen wir gegen
Ramot-Gilead zu Felde ziehen oder sollen wir es lassen? Micha
antwortete: Zieht hinauf und seid erfolgreich! Sie werden eurer Gewalt
übergeben werden.

<<v15>>
15 Doch der König entgegnete: Wie oft muss ich dich beschwören, mir im
Namen des Herrn nur die Wahrheit zu sagen?

<<v16>>
16 Da sagte Micha: Ich sah ganz Israel über die Berge zerstreut wie
Schafe, die keinen Hirten haben. Und der Herr sagte: Sie haben keine
Herren mehr. So gehe jeder in Frieden nach Hause.

<<v17>>
17 Da wandte sich der König von Israel an Joschafat: Habe ich es dir
nicht gesagt? Er weissagt mir nie Gutes, sondern immer nur Schlimmes.

<<v18>>
18 Micha aber fuhr fort: Darum hört das Wort des Herrn: Ich sah den
Herrn auf seinem Thron sitzen; das ganze Heer des Himmels stand zu
seiner Rechten und seiner Linken. [fn:3]

<<v19>>
19 Und der Herr fragte: Wer will Ahab, den König von Israel, betören,
sodass er nach Ramot-Gilead hinaufzieht und dort fällt? Da hatte der
eine diesen, der andere jenen Vorschlag.

<<v20>>
20 Zuletzt trat der Geist vor, stellte sich vor den Herrn und sagte: Ich
werde ihn betören. Der Herr fragte ihn: Auf welche Weise? [fn:4]

<<v21>>
21 Er gab zur Antwort: Ich werde mich aufmachen und zu einem Lügengeist
im Mund all seiner Propheten werden. Da sagte der Herr: Du wirst ihn
betören; du vermagst es. Geh und tu es!

<<v22>>
22 So hat der Herr jetzt einen Geist der Lüge in den Mund deiner
Propheten gelegt; denn er hat über dich Unheil beschlossen.

<<v23>>
23 Da trat Zidkija, der Sohn Kenaanas, zu Micha, schlug ihn ins Gesicht
und rief: Wie, sollte denn der Geist des Herrn von mir gewichen sein, um
mit dir zu reden?

<<v24>>
24 Micha erwiderte: Du wirst es an jenem Tag erfahren, an dem du von
einem Gemach in das andere eilst, um dich zu verstecken.

<<v25>>
25 Der König von Israel aber gab den Befehl: Nehmt Micha fest, führt ihn
zum Stadtobersten Amon und zum Prinzen Joasch

<<v26>>
26 und meldet: So spricht der König: Werft diesen Mann ins Gefängnis,
und haltet ihn streng bei Brot und Wasser, bis ich wohlbehalten
zurückkomme.

<<v27>>
27 Doch Micha erwiderte: Wenn du wohlbehalten zurückkommst, dann hat der
Herr nicht durch mich geredet. [Und er sagte: Hört, alle ihr Völker!] [fn:5]

<<v28>>
28 Darauf zog der König von Israel mit Joschafat, dem König von Juda,
gegen Ramot-Gilead.

<<v29>>
29 Der König von Israel sagte zu Joschafat: Ich will mich verkleiden und
so in den Kampf ziehen. Du aber behalte deine Gewänder an! So ging der
König von Israel verkleidet in den Kampf.

<<v30>>
30 Der König von Aram hatte aber den Obersten seiner Kriegswagen
befohlen: Greift niemanden an, er sei hohen oder niederen Ranges, außer
den König von Israel.

<<v31>>
31 Als daher die Obersten der Kriegswagen Joschafat erblickten und ihn
für den König von Israel hielten, stürmten sie auf ihn ein, sodass er um
Hilfe schrie. Doch der Herr half ihm und lenkte sie von ihm weg.

<<v32>>
32 Als sie nämlich sahen, dass er nicht der König von Israel war, ließen
sie von ihm ab.

<<v33>>
33 Ein Mann aber spannte aufs Geratewohl seinen Bogen und traf den König
von Israel zwischen Panzer und Leibgurt. Dieser befahl daher dem
Wagenlenker: Wende um und bring mich aus der Schlacht; denn ich bin
verwundet.

<<v34>>
34 Da aber die Schlacht an jenem Tag heftig wurde, hielt der König von
Israel den Aramäern gegenüber im Wagen stand bis zum Abend. Zur Zeit des
Sonnenuntergangs starb er.

* Footnotes

[fn:1] Joram, der Sohn Joschafats, war mit Atalja, der Tochter
Ahabs, verheiratet (vgl. [[file:2.Chr_21.org::v6][21,6]]).

[fn:2] (1-34) [[file:1.Kön_22.org::v4][1 Kön 22,4-35]]

[fn:3] [[file:Jes_6.org::v1][Jes 6,1-3]]

[fn:4] Zum «Geist» vgl. die Anmerkung zu [[file:1.Kön_22.org::v19][1 Kön 22,19-23]].

[fn:5] [[file:Mi_1.org::v2][Mi 1,2]]
