#+TITLE: 2 Chr 25 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 23:01]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Chr 25.html

<<verses>>

<<v1>>
* Amazja: 25,1-13
     :PROPERTIES:
     :CUSTOM_ID: amazja-251-13
     :END:
1 Amazja war fünfundzwanzig Jahre alt, als er König wurde, und regierte
neunundzwanzig Jahre in Jerusalem. Seine Mutter hieß Joaddan und stammte
aus Jerusalem. [fn:1]

<<v2>>
2 Er tat, was dem Herrn gefiel, wenn auch nicht mit ungeteiltem Herzen. [fn:2]

<<v3>>
3 Sobald die Herrschaft fest in seiner Hand war, ließ er die Diener
hinrichten, die seinen Vater, den König, erschlagen hatten.

<<v4>>
4 Ihre Söhne aber verschonte er, wie es im Gesetz, im Buch des Mose,
geschrieben steht, wo der Herr geboten hat: Die Väter sollen nicht für
ihre Söhne und die Söhne nicht für ihre Väter mit dem Tod bestraft
werden, sondern jeder soll nur für sein eigenes Verbrechen sterben. [fn:3]

<<v5>>
5 Amazja versammelte die Judäer aus ganz Juda und Benjamin und stellte
sie nach Großfamilien unter den Führern der Tausend- und Hundertschaften
auf. Er ließ alle, die zwanzig Jahre und darüber waren, mustern. Ihre
Zählung ergab dreihunderttausend auserlesene, wehrfähige Männer, die
Lanze und Schild trugen.

<<v6>>
6 Dazu ließ er in Israel hunderttausend tapfere Krieger um hundert
Silbertalente anwerben.

<<v7>>
7 Doch ein Gottesmann kam zu ihm und sagte: Das Heer Israels, o König,
soll nicht mit dir ziehen; denn der Herr ist nicht mit Israel, er hilft
keinem Efraimiter. [fn:4]

<<v8>>
8 Rück vielmehr allein aus und nimm mutig und entschlossen den Kampf
auf! Gott könnte dich sonst vor dem Feind zu Fall bringen; denn Gott hat
die Macht, zu helfen oder zu stürzen.

<<v9>>
9 Amazja erwiderte dem Gottesmann: Wozu habe ich dann den israelitischen
Söldnerscharen hundert Talente gegeben? Der Gottesmann antwortete: Der
Herr kann dir viel mehr als diese geben.

<<v10>>
10 Da schied Amazja die Truppe, die aus Efraim zu ihm gekommen war, aus
und ließ sie in ihre Heimat zurückkehren. Sie geriet deswegen in
heftigen Zorn über Juda und zog grollend in ihr Land zurück.

<<v11>>
11 Amazja aber fasste Mut und führte sein Volk in den Krieg. Er zog in
das Salztal und erschlug von den Seïritern zehntausend Mann.

<<v12>>
12 Zehntausend nahmen die Judäer lebend gefangen, führten sie auf die
Höhe eines Felsens und stürzten sie hinab, sodass alle zerschmettert
wurden.

<<v13>>
13 Die Angehörigen der Söldnertruppe aber, die Amazja zurückgeschickt
und am Kriegszug nicht hatte teilnehmen lassen, überfielen die Städte
Judas zwischen Samaria und Bet-Horon, erschlugen dort dreitausend Mann
und machten reiche Beute.\\
\\

<<v14>>
* Amazjas Übermut und Tod: 25,14-28

14 Nach der Rückkehr vom Sieg über die Edomiter stellte Amazja die
Götter der Seïriter, die er mitgebracht hatte, als Götter für sich auf,
fiel vor ihnen nieder und brachte ihnen Opfer dar.

<<v15>>
15 Da entbrannte der Zorn des Herrn gegen Amazja. Er sandte einen
Propheten zu ihm und ließ ihm sagen: Warum suchst du die Götter des
Volkes, die ihr Volk aus deiner Hand nicht retten konnten?

<<v16>>
16 Amazja fiel ihm ins Wort und rief: Haben wir dich zum Berater des
Königs bestellt? Halt ein! Warum soll man dich schlagen? Da hielt der
Prophet inne und sagte: Ich weiß, dass Gott dein Verderben plant, weil
du das getan und auf meinen Rat nicht gehört hast.

<<v17>>
17 Nach einer Beratung sandte Amazja, der König von Juda, Boten an
Joasch, den Sohn des Joahas, des Sohnes Jehus, den König von Israel, und
ließ ihm sagen: Komm, wir wollen (im Kampf) einander gegenübertreten. [fn:5]

<<v18>>
18 Doch Joasch, der König von Israel, ließ dem König Amazja von Juda
sagen: Der Dornstrauch auf dem Libanon ließ der Zeder auf dem Libanon
sagen: Gib deine Tochter meinem Sohn zur Frau! Aber die Tiere des
Libanon liefen über den Dornstrauch und zertraten ihn.

<<v19>>
19 Du denkst: Ich habe Edom besiegt!, und bist übermütig geworden. Wahre
jetzt deinen Ruhm und bleib zu Hause! Wozu willst du das Unglück
herausfordern und zu Fall kommen, du und Juda mit dir?

<<v20>>
20 Doch Amazja wollte nicht hören; denn Gott hatte es so bestimmt, um
sie ihren Feinden preiszugeben, weil sie die Götter der Edomiter
suchten.

<<v21>>
21 Joasch, der König von Israel, rückte daraufhin aus. Er und Amazja,
der König von Juda, traten bei Bet-Schemesch, das zu Juda gehört,
einander gegenüber.

<<v22>>
22 Die Judäer wurden von den Israeliten geschlagen und flohen zu ihren
Zelten.

<<v23>>
23 Den König Amazja von Juda, den Sohn des Joasch, des Sohnes des
Joahas, nahm König Joasch von Israel bei Bet-Schemesch gefangen und
brachte ihn nach Jerusalem. Dort riss er die Mauer der Stadt vom
Efraimtor bis zum Ecktor auf einer Strecke von vierhundert Ellen nieder, [fn:6]

<<v24>>
24 nahm alles Gold und Silber sowie alle Geräte, die sich im Haus Gottes
bei Obed-Edom befanden, samt den Schätzen des königlichen Palastes, ließ
sich Geiseln stellen und kehrte nach Samaria zurück. [fn:7]

<<v25>>
25 Amazja, der Sohn des Joasch, der König von Juda, lebte nach dem Tod
des Joasch, des Sohnes des Joahas, des Königs von Israel, noch fünfzehn
Jahre.

<<v26>>
26 Die übrige Geschichte Amazjas, die frühere und die spätere, ist
aufgezeichnet im Buch der Könige von Juda und Israel.

<<v27>>
27 Zur Zeit, da Amazja sich vom Herrn abwandte, bildete sich in
Jerusalem gegen ihn eine Verschwörung. Er floh nach Lachisch; aber man
sandte Verfolger hinter ihm her nach Lachisch, die ihn dort erschlugen.

<<v28>>
28 Man brachte ihn auf Pferden nach Jerusalem und begrub ihn bei seinen
Vätern in der Davidstadt. [fn:8]\\
\\

* Footnotes

[fn:1] (1-4) [[file:2.Kön_14.org::v1][2 Kön 14,1]]-[[file:2.Kön_14.org::v6][6]]

[fn:2] Die Einschränkung bezieht sich auf V. 14.

[fn:3] [[file:Dtn_24.org::v16][Dtn 24,16]]; [[file:Ez_18.org::v10][Ez 18,10]]-[[file:Ez_18.org::v20][20]]

[fn:4] [[file:2.Chr_19.org::v2][19,2]]; [[file:2.Chr_20.org::v37][20,37]]

[fn:5] (17-28) [[file:2.Kön_14.org::v8][2 Kön 14,8]]-[[file:2.Kön_14.org::v20][20]]

[fn:6] Joahas: vgl. die Anmerkung zu [[file:2.Chr_21.org::v17][21,17]].

[fn:7] [[file:1.Chr_26.org::v15][1 Chr 26,15]]

[fn:8] in der Davidstadt: Text korr. nach G und [[file:2.Kön_14.org::v20][2 Kön 14,20]];
H: in der Stadt Judas.
