#+TITLE: 2 Chr 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-21 Di 22:49]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 4.html

* 2.Chr 4

<<verses>>

<<v1>>
1 Er ließ einen bronzenen Altar herstellen, zwanzig Ellen lang, zwanzig
Ellen breit und zehn Ellen hoch. [fn:1]

<<v2>>
2 Dann machte er das «Meer». Es wurde aus Bronze gegossen, maß zehn
Ellen von einem Rand zum andern, war völlig rund und fünf Ellen hoch.
Eine Schnur von dreißig Ellen konnte es rings umspannen.

<<v3>>
3 Unterhalb seines Rands waren rundum Bilder von Rindern. In einem Band
von dreißig Ellen Länge umsäumten sie das Meer ringsum in zwei Reihen.
Sie wurden bei seinem Guss mitgegossen. [fn:2]

<<v4>>
4 Das Meer stand auf zwölf Rindern. Von ihnen schauten drei nach Norden,
drei nach Westen, drei nach Süden und drei nach Osten. Das Meer ruhte
oben auf den Rindern. Ihre Hinterteile waren nach innen gekehrt.

<<v5>>
5 Die Wand des Meeres war eine Handbreit dick. Sein Rand war wie der
Rand eines Bechers geformt, einer Lilienblüte gleich. Es fasste
dreitausend Bat.

<<v6>>
6 Auch machte er zehn Kessel, von denen er fünf an die Südseite und fünf
an die Nordseite brachte. Sie dienten für die Waschungen; was zum
Brandopfer gehörte, sollte man in ihnen abspülen. Das Meer war für die
Waschungen der Priester bestimmt.

<<v7>>
7 Er machte die zehn goldenen Leuchter der Vorschrift gemäß und stellte
sie im Tempel auf, fünf auf der rechten und fünf auf der linken Seite.

<<v8>>
8 Ferner machte er zehn Tische und brachte sie in den Tempel, fünf auf
die rechte und fünf auf die linke Seite. Desgleichen verfertigte er
hundert goldene Schalen.

<<v9>>
9 Auch schuf er den Vorhof der Priester und den großen Hof mit seinen
Toren. Die Torflügel überzog er mit Bronze. [fn:3]

<<v10>>
10 Das Meer stellte er an die Südseite des Hauses gegen Südosten.

<<v11>>
11 Endlich machte Hiram die Töpfe, Schaufeln und Schalen. So führte
Hiram die Arbeiten zu Ende, die er dem König Salomo für das Haus Gottes
anzufertigen hatte:

<<v12>>
12 zwei Säulen, zwei beckenförmige Kapitelle oben auf den Säulen, die
zwei Flechtwerke, mit denen man die beiden beckenförmigen Kapitelle oben
auf den Säulen bedeckte,

<<v13>>
13 die vierhundert Granatäpfel für die beiden Flechtwerke, die in zwei
Reihen an jedem Flechtwerk angebracht waren und die die beiden
beckenförmigen Kapitelle auf den Säulen bedeckten,

<<v14>>
14 die zehn fahrbaren Gestelle, die zehn Kessel für die Gestelle,

<<v15>>
15 das eine Meer, die zwölf Rinder unter ihm,

<<v16>>
16 die Töpfe, Schaufeln und Gabeln. Alle diese Geräte machte Hiram-Abi
dem König Salomo für das Haus des Herrn aus glatter Bronze.

<<v17>>
17 In der Jordanau zwischen Sukkot und Zereda ließ sie der König in
Formen aus festem Lehm gießen.

<<v18>>
18 Salomo ließ alle diese Geräte in überaus großer Menge anfertigen; das
Gewicht der Bronze war darum nicht festzustellen.

<<v19>>
19 Salomo ließ alle Geräte, die zum Haus Gottes gehörten, anfertigen:
den goldenen Altar, die Tische, auf die man die Schaubrote legte,

<<v20>>
20 die Leuchter mit ihren Lampen aus bestem Gold, um sie der Vorschrift
gemäß vor der Gotteswohnung anzuzünden,

<<v21>>
21 die goldenen Blüten, Lampen und Dochtscheren aus bestem Gold,

<<v22>>
22 ferner die Messer, Schalen, Schüsseln und Pfannen aus bestem Gold. An
den Türen des Hauses waren die Flügel im inneren Raum gegen das
Allerheiligste und die beiden Türflügel, die zum Hauptraum führten, mit
Gold verkleidet.

* Footnotes

[fn:1] Der Altar wird im Baubericht von 1 Kön nicht erwähnt;
doch wird sein Vorhandensein vorausgesetzt (vgl. [[file:1.Kön_8.org::v22][1 Kön 8,22]].[[file:1.Kön_8.org::v64][64]]).

[fn:2] H: zehn Ellen.

[fn:3] Der Hof der Priester wird in [[file:1.Kön_6.org::v36][1 Kön 6,36]] und [[file:1.Kön_7.org::v12][7,12]]
«innerer Hof» genannt. Die Bezeichnung in Chr deutet an, dass er zu
ihrer Zeit nur noch von den Priestern betreten werden durfte.
