#+TITLE: 2 Chr 31 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 23:30]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Chr 31.html

* 2.Chr 31

<<verses>>

<<v1>>
1 Nachdem sie dies alles beendet hatten, zogen die anwesenden Israeliten
insgesamt in die Städte Judas, zertrümmerten die Steinmale, hieben die
Kultpfähle um und zerstörten die Kulthöhen und Altäre in ganz Juda,
Benjamin, Efraim und Manasse vollständig. Darauf kehrten alle in ihre
Städte auf ihren Besitz zurück. [fn:1]\\
\\

<<v2>>
* Die Neuordnung des Tempeldienstes: 31,2-21

2 Hiskija stellte die Abteilungen der Priester und Leviten nach ihren
Dienstklassen auf. Er wies alle Priester und Leviten einzeln in ihren
Dienst ein und bestellte sie zum Vollzug der Brand- und Heilsopfer, zu
Dienstleistungen und zum Vortrag der Dank- und Lobgesänge an den Toren
des Lagers des Herrn. [fn:2]

<<v3>>
3 Der Beitrag, den der König aus seinem Vermögen für die Brandopfer
leistete, betraf die Opfer am Morgen und am Abend sowie die Brandopfer
an den Sabbaten, Neumondtagen und Festen, die durch das Gesetz des Herrn
vorgeschrieben waren.

<<v4>>
4 Hiskija befahl dem Volk, das heißt, den Einwohnern Jerusalems, die den
Priestern und den Leviten zustehenden Anteile abzuliefern, damit sie
sich ganz dem Gesetz des Herrn widmen könnten. [fn:3]

<<v5>>
5 Sobald der Befehl bekannt wurde, brachten die Israeliten die
Ersterträge von Getreide, Most, Öl, Honig und allen Früchten des Feldes
reichlich herbei und lieferten den Zehnten von allem vollzählig ab.

<<v6>>
6 Ebenso brachten die Israeliten und die Judäer, die in den Städten
Judas wohnten, den Zehnten von den Rindern und Schafen sowie den Zehnten
von den Weihegaben, die dem Herrn, ihrem Gott, übergeben wurden. Sie
reihten Stapel an Stapel. [fn:4]

<<v7>>
7 Im dritten Monat fingen sie an, die unterste Schicht zu legen, und im
siebten Monat waren sie damit fertig.

<<v8>>
8 Als dann Hiskija und die führenden Männer kamen und die aufgestapelten
Mengen sahen, priesen sie den Herrn und sein Volk Israel.

<<v9>>
9 Hiskija erkundigte sich bei den Priestern und den Leviten wegen der
aufgestapelten Mengen

<<v10>>
10 und der Oberpriester Asarja aus dem Haus Zadok gab zur Antwort:
Seitdem man begonnen hat, die Abgaben in das Haus des Herrn zu bringen,
haben wir zu essen, werden satt und lassen noch reichlich übrig; denn
der Herr hat sein Volk gesegnet. Diese Menge ist übrig geblieben.

<<v11>>
11 Hiskija ließ nun Kammern im Haus des Herrn herrichten, und als man
sie hergerichtet hatte,

<<v12>>
12 brachte man die Abgaben, die Zehnten und die Weihegaben gewissenhaft
dorthin. Der Levit Konanja war Aufseher über sie und sein Bruder Schimi
sein Stellvertreter.

<<v13>>
13 Ihnen standen auf Anordnung des Königs Hiskija und Asarjas, des
Fürsten des Hauses Gottes, Jehiël, Asasja, Nahat, Asaël, Jerimot,
Josabad, Eliël, Jismachja, Mahat und Benaja als Beamte zur Seite.

<<v14>>
14 Der Levit Kore, der Sohn Jimnas, der Wächter am Osttor, wachte über
die freiwilligen Spenden an Gott, damit die für den Herrn bestimmte
Abgabe und das Hochheilige abgeliefert würden. [fn:5]

<<v15>>
15 Ihm standen Eden, Minjamin, Jeschua, Schemaja, Amarja und Schechanja
in den Priesterstädten gewissenhaft zur Seite, damit ihre Amtsbrüder,
die Vornehmen wie die Geringen, abteilungsweise ihre Anteile erhielten.

<<v16>>
16 Außerdem hatte man für alle, die abteilungsweise in das Haus des
Herrn kamen, um aufgrund ihrer Obliegenheiten und entsprechend den
Erfordernissen eines jeden Tages ihren Dienst zu verrichten,
Verzeichnisse angelegt. Sie erfassten alle männlichen Personen, die drei
Jahre und darüber waren.

<<v17>>
17 Dabei war die Eintragung der Priester nach Großfamilien geschehen;
die Leviten wurden, von zwanzig Jahren an aufwärts, nach ihren
Obliegenheiten und nach ihren Abteilungen aufgeschrieben.

<<v18>>
18 Die Eintragung erfasste bei jeder Gemeinschaft alle Kinder, Frauen,
Söhne und Töchter; denn auch diese wurden durch deren ständigen Dienst
geheiligt.

<<v19>>
19 Für die Söhne Aarons, die Priester, die auf den Weideflächen ihrer
Städte wohnten, wurden in jeder einzelnen Stadt Männer bestellt, die
namentlich bestimmt waren, um allen männlichen Angehörigen der Priester
und allen im Verzeichnis stehenden Leviten ihre Anteile zu geben.

<<v20>>
20 So verfuhr Hiskija in ganz Juda. Er tat, was gut, recht und getreu
war vor dem Herrn, seinem Gott.

<<v21>>
21 Bei jedem Unternehmen, das er im Dienst des Hauses Gottes oder für
das Gesetz und die Gebote begann, um seinen Gott zu suchen, handelte er
mit Hingabe seines ganzen Herzens und hatte Erfolg.\\
\\

* Footnotes

[fn:1] [[file:2.Kön_18.org::v4][2 Kön 18,4]]

[fn:2] Der Ausdruck «Lager des Herrn» vergleicht den
Tempelbereich mit dem Zeltlager der Wüstenzeit.

[fn:3] Nach [[file:Num_18.org::v21][Num 18,21]]-[[file:Num_18.org::v32][32]] gehörten den Priestern und Leviten die
Zehnten und Erstlingsfrüchte.

[fn:4] [[file:Num_18.org::v8][Num 18,8]]-[[file:Num_18.org::v32][32]]

[fn:5] das Hochheilige: die Anteile, die bei bestimmten Opfern
von den Priestern am Heiligtum gegessen werden mussten (vgl. [[file:Lev_2.org::v3][Lev 2,3]];
[[file:Lev_6.org::v10][6,10]].[[file:Lev_6.org::v18][18]]; [[file:Lev_7.org::v6][7,6]]; [[file:Lev_14.org::v13][14,13]]).
