#+TITLE: 2 Chr 33 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 23:40]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 33.html

<<verses>>

<<v1>>
* Manasse: 33,1-20

1 Manasse war zwölf Jahre alt, als er König wurde, und regierte
fünfundfünfzig Jahre in Jerusalem. [fn:1]

<<v2>>
2 Er tat, was dem Herrn missfiel, und ahmte die Gräuel der Völker nach,
die der Herr vor den Augen der Israeliten vertrieben hatte.

<<v3>>
3 Er baute die Kulthöhen wieder auf, die sein Vater Hiskija zerstört
hatte, errichtete Altäre für die Baale, ließ Kultpfähle anfertigen, warf
sich vor dem ganzen Heer des Himmels nieder und diente ihm. [fn:2] [fn:3]

<<v4>>
4 Auch baute er solche Altäre im Haus des Herrn, obwohl der Herr gesagt
hatte: In Jerusalem soll mein Name auf ewig bleiben. [fn:4]

<<v5>>
5 In den beiden Höfen des Tempels baute er Altäre für das ganze Heer des
Himmels.

<<v6>>
6 Er ließ im Tal Ben-Hinnom seine Söhne durch das Feuer gehen, trieb
Zauberei, Wahrsagerei und andere geheime Künste, bestellte
Totenbeschwörer und Zeichendeuter. So tat er vieles, was dem Herrn
missfiel und ihn erzürnte. [fn:5]

<<v7>>
7 Er brachte auch das Götterbild, das er hatte anfertigen lassen, in das
Haus Gottes, von dem Gott zu David und dessen Sohn Salomo gesagt hatte:
Auf dieses Haus und auf Jerusalem, das ich aus allen Stämmen Israels
auserwählt habe, will ich meinen Namen auf ewig legen. [fn:6] [fn:7]

<<v8>>
8 Ich werde Israels Fuß nicht mehr außerhalb des Landes ziehen lassen,
das ich für eure Väter bestimmt habe, wenn sie nur alles befolgen, was
ich ihnen im ganzen Gesetz, in den Geboten und Rechtsvorschriften des
Mose befohlen habe. [fn:8]

<<v9>>
9 Doch Manasse verführte Juda und die Einwohner Jerusalems, noch
Schlimmeres zu tun als die Völker, die der Herr vor den Augen der
Israeliten vernichtet hatte.

<<v10>>
10 Der Herr redete zu Manasse und zu seinem Volk. Doch sie achteten
nicht darauf.

<<v11>>
11 Da ließ der Herr die Heerführer des Königs von Assur gegen sie
anrücken. Sie ergriffen Manasse in seinem Versteck, fesselten ihn mit
bronzenen Ketten und führten ihn nach Babel. [fn:9]

<<v12>>
12 Als man ihn so bedrängte, suchte er den Herrn, seinen Gott, zu
besänftigen. Er beugte sich tief vor dem Gott seiner Väter

<<v13>>
13 und betete zu ihm. Gott erbarmte sich seiner; er hörte sein Flehen
und ließ ihn als König nach Jerusalem zurückkehren. So musste Manasse
erfahren, dass der Herr der wahre Gott ist.

<<v14>>
14 Danach baute er draußen an der Davidstadt eine Mauer, die im Tal
westlich vom Gihon gegen das Fischtor lief, sodass er den Ofel
umschloss; er machte sie sehr hoch. Auch bestellte er Kriegsoberste für
alle befestigten Städte Judas. [fn:10]

<<v15>>
15 Sodann entfernte er die fremden Götter und das Götzenbild aus dem
Haus des Herrn, auch alle Altäre, die er auf dem Berg des Hauses des
Herrn und in Jerusalem errichtet hatte, und warf sie vor die Stadt
hinaus.

<<v16>>
16 Den Altar des Herrn aber stellte er wieder her, brachte auf ihm
Heils- und Dankopfer dar und befahl Juda, dem Herrn, dem Gott Israels,
zu dienen.

<<v17>>
17 Doch opferte das Volk immer noch auf den Kulthöhen, wenn auch nur dem
Herrn, seinem Gott.

<<v18>>
18 Die übrige Geschichte Manasses, sein Gebet zu seinem Gott und die
Worte der Seher, die im Namen des Herrn, des Gottes Israels, zu ihm
redeten, sind aufgezeichnet in der Geschichte der Könige von Israel.

<<v19>>
19 Sein Gebet und dessen Erhörung, alle seine Sünden und treulosen
Taten, die Orte, an denen er Kulthöhen errichtete und Kultpfähle und
Götzenbilder aufstellte, bevor er sich demütigte, sind aufgezeichnet in
der Geschichte seiner Seher. [fn:11]

<<v20>>
20 Manasse entschlief zu seinen Vätern und man begrub ihn im Garten
seines Hauses. Sein Sohn Amon wurde König an seiner Stelle. [fn:12]\\
\\

<<v21>>
* Amon: 33,21-25

21 Amon war zweiundzwanzig Jahre alt, als er König wurde, und regierte
zwei Jahre in Jerusalem. [fn:13]

<<v22>>
22 Wie sein Vater Manasse tat er, was dem Herrn missfiel; er opferte
allen Götzenbildern, die sein Vater Manasse hatte machen lassen, und
verehrte sie.

<<v23>>
23 Doch demütigte er sich nicht vor dem Herrn wie sein Vater Manasse,
sondern vermehrte die Schuld.

<<v24>>
24 Gegen ihn zettelten seine Diener eine Verschwörung an und töteten ihn
in seinem Haus.

<<v25>>
25 Doch die Bürger des Landes erschlugen alle, die sich gegen König Amon
verschworen hatten, und machten seinen Sohn Joschija zum König an seiner
Stelle.\\
\\

* Footnotes

[fn:1] (1-20) [[file:2.Kön_21.org::v1][2 Kön 21,1]]-[[file:2.Kön_21.org::v18][18]]

[fn:2] [[file:2.Chr_31.org::v1][31,1]]

[fn:3] Heer des Himmels: die Sterne, die vielfach als göttliche
Wesen verehrt wurden.

[fn:4] [[file:1.Kön_9.org::v3][1 Kön 9,3]]

[fn:5] Er ließ sie durch das Feuer gehen: vgl. die Anmerkung zu [[file:2.Kön_16.org::v3][2 Kön 16,3]].

[fn:6] [[file:1.Kön_9.org::v3][1 Kön 9,3]]

[fn:7] Gemeint ist das Bild der Göttin Aschera, der weiblichen
Entsprechung zu Baal (vgl. [[file:2.Kön_21.org::v7][2 Kön 21,7]]).

[fn:8] [[file:2.Sam_7.org::v10][2 Sam 7,10]]

[fn:9] In assyrischen Texten wird Manasse als Vasall der Könige
Asarhaddon und Assurbanipal erwähnt; von seiner Gefangenschaft ist nicht
die Rede.

[fn:10] Vielleicht Fortsetzung der von Hiskija begonnenen
Mauer (vgl. [[file:2.Chr_32.org::v5][32,5]]).

[fn:11] seiner Seher: Text korr.; der Ausdruck in H wird von
manchen Auslegern als Eigenname (Hosai) verstanden.

[fn:12] im Garten: nach G und [[file:2.Kön_21.org::v18][2 Kön 21,18]] eingefügt.

[fn:13] (21-25) [[file:2.Kön_21.org::v19][2 Kön 21,19]]-[[file:2.Kön_21.org::v24][24]]
