#+TITLE: 2 Chr 8 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-21 Di 23:13]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Chr 8.html

<<verses>>

<<v1>>
* Verschiedene Nachrichten über Salomo: 8,1-18

1 Nach Ablauf von zwanzig Jahren, in denen Salomo das Haus des Herrn und
seinen Palast gebaut hatte, [fn:1]

<<v2>>
2 baute er auch die Städte aus, die Hiram ihm (zurück) gegeben hatte,
und siedelte Israeliten darin an. [fn:2]

<<v3>>
3 Salomo zog nach Hamat-Zoba und eroberte es.

<<v4>>
4 Er baute Tadmor in der Steppe aus und alle Vorratsstädte, die er in
Hamat anlegte.

<<v5>>
5 Er baute auch das obere und das untere Bet-Horon zu Festungen mit
Mauern, Toren und Riegeln aus,

<<v6>>
6 ebenso Baala und alle Vorratsstädte, die ihm gehörten, die Städte für
die Wagen und ihre Mannschaft und was er sonst in Jerusalem, auf dem
Libanon und im ganzen Bereich seiner Herrschaft zu bauen wünschte.

<<v7>>
7 Die Reste der Hetiter, Amoriter, Perisiter, Hiwiter und Jebusiter, die
nicht zu den Israeliten gehörten

<<v8>>
8 und von denen noch Nachkommen im Land lebten - die Israeliten hatten
sie nicht ausgerottet - hob Salomo als Fronarbeiter aus und sie blieben
es bis zum heutigen Tag.

<<v9>>
9 Von den Israeliten aber machte Salomo niemand zum Sklaven für seine
Arbeit; sie waren seine Krieger, seine Obersten und Hauptleute, die
Befehlshaber über seine Wagen und deren Mannschaft. [fn:3]

<<v10>>
10 Zweihundertfünfzig Werkführer, die unter dem Befehl der Statthalter
Salomos standen, hatten die Aufsicht über die Arbeiter.

<<v11>>
11 Salomo brachte die Tochter des Pharao aus der Davidstadt in das Haus,
das er für sie gebaut hatte; denn er sagte: Eine Frau soll nicht im Haus
Davids, des Königs von Israel, wohnen; denn die Räume, in die die Lade
des Herrn gekommen ist, sind heilig.

<<v12>>
12 Damals brachte Salomo auf dem Altar, den er vor der Halle für den
Herrn erbaut hatte, Brandopfer dar.

<<v13>>
13 Auch an den Sabbaten und Neumondtagen ließ er die Opfer darbringen,
die nach dem Befehl des Mose für diese Tage angeordnet waren. Das
Gleiche tat er dreimal im Jahr, jeweils an den Festen, am Fest der
Ungesäuerten Brote, am Wochenfest und am Laubhüttenfest.

<<v14>>
14 Dem Auftrag seines Vaters David folgend, bestellte er die Abteilungen
der Priester für ihren Dienst und die Leviten für ihre Aufgabe,
Loblieder zu singen und an der Seite der Priester Dienst zu tun, wie es
für jeden Tag vorgeschrieben war. Auch bestellte er die Torwächter nach
ihren Abteilungen für die einzelnen Tore; denn so lautete der Befehl
Davids, des Mannes Gottes.

<<v15>>
15 Man wich in keinem Punkt von den Befehlen ab, die der König für die
Priester und für die Leviten erlassen hatte.

<<v16>>
16 So wurde das ganze Werk Salomos planmäßig ausgeführt, vom Tag der
Grundlegung des Hauses des Herrn bis zu seiner Fertigstellung, bis zur
Vollendung des Hauses des Herrn.

<<v17>>
17 Damals begab sich Salomo nach Ezjon-Geber und Elat an der Küste des
Meeres in Edom.

<<v18>>
18 Hiram schickte ihm durch seine Knechte Schiffe und geübte Seefahrer.
Sie fuhren mit den Leuten Salomos nach Ofir, holten von dort
vierhundertfünfzig Talente Gold und brachten es dem König Salomo. [fn:4]\\
\\

* Footnotes

[fn:1] (1-18) [[file:1.Kön_9.org::v10][1 Kön 9,10]]-[[file:1.Kön_9.org::v28][28]]

[fn:2] Nach [[file:1.Kön_9.org::v11][1 Kön 9,11]]-[[file:1.Kön_9.org::v13][13]] hatte Salomo zwanzig Städte in
Galiläa an Hiram abgetreten, die diesem aber nicht gefielen. Der
Chronist will sagen, dass Salomo sie wieder zurückerhielt.

[fn:3] seine Obersten und Hauptleute: Text korr. nach G und [[file:1.Kön_9.org::v22][1 Kön 9,22]];
H: die Obersten seiner Hauptleute.

[fn:4] In Chr sind zwei Tatsachen zusammengefasst: Hiram sandte
Schiffe, die im Mittelmeer nach Tarschisch fuhren ([[file:2.Chr_9.org::v21][9,21]]), und Seeleute,
die von Elat aus mit der israelitischen Schiffsbesatzung nach Ofir
fuhren.
