#+TITLE: 2 Chr 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 22:43]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 21.html

<<verses>>

<<v1>>
* Joram: 21,1-20

1 Joschafat entschlief zu seinen Vätern und wurde bei seinen Vätern in
der Davidstadt begraben. Sein Sohn Joram wurde König an seiner Stelle. [fn:1]

<<v2>>
2 Seine Brüder, die Söhne Joschafats, waren: Asarja, Jehiël, Secharja,
Asarja, Michael und Schefatja; sie alle waren Söhne Joschafats, des
Königs von Juda. [fn:2]

<<v3>>
3 Ihr Vater gab ihnen reiche Geschenke an Silber, Gold und anderen
Kostbarkeiten, dazu befestigte Städte in Juda. Das Königtum aber verlieh
er Joram; denn dieser war der Erstgeborene.

<<v4>>
4 Doch Joram erhob sich gegen das Königtum seines Vaters, gewann die
Oberhand und ließ alle seine Brüder und auch einige führende Männer
Israels mit dem Schwert hinrichten.

<<v5>>
5 Joram war zweiunddreißig Jahre alt, als er König wurde, und regierte
acht Jahre in Jerusalem. [fn:3]

<<v6>>
6 Er folgte den Wegen der Könige von Israel, wie es das Haus Ahab getan
hatte; denn er hatte eine Tochter Ahabs zur Frau und er tat, was dem
Herrn missfiel.

<<v7>>
7 Doch der Herr wollte das Haus David nicht verderben wegen des Bundes,
den er mit David geschlossen hatte, und weil er ihm versprochen hatte,
er werde ihm und seinen Söhnen für immer eine Leuchte geben. [fn:4]

<<v8>>
8 In den Tagen Jorams fiel Edom von Juda ab und setzte einen eigenen
König ein. [fn:5]

<<v9>>
9 Joram zog daher mit seinen Obersten und allen Kriegswagen gegen sie.
Während der Nacht griff er an und schlug die Edomiter, die ihn und die
Obersten der Kriegswagen umzingelt hatten.

<<v10>>
10 Doch Edom fiel von Juda ab und ist abtrünnig bis zum heutigen Tag.
Damals, zur gleichen Zeit, fiel auch Libna von Juda ab; denn Joram hatte
den Herrn, den Gott seiner Väter, verlassen.

<<v11>>
11 Auch errichtete er Kulthöhen auf den Bergen Judas und verführte die
Einwohner Jerusalems zur Untreue und Juda zum Abfall.

<<v12>>
12 Damals traf ein Schreiben des Propheten Elija bei ihm ein. Es hatte
folgenden Inhalt: So spricht der Herr, der Gott deines Vaters David:
Weil du nicht auf den Wegen deines Vaters Joschafat und auf den Wegen
Asas, des Königs von Juda,

<<v13>>
13 sondern auf den Wegen der Könige von Israel gegangen bist, weil du
Juda und die Einwohner Jerusalems zur Untreue verführt hast, wie es das
Haus Ahab getan hat, und weil du deine eigenen Brüder aus der Familie
deines Vaters, die besser waren als du, getötet hast,

<<v14>>
14 darum wird der Herr dein Volk, deine Söhne und Frauen und deinen
ganzen Besitz mit harten Schlägen treffen.

<<v15>>
15 Du selbst wirst in schweres Siechtum verfallen und an deinen
Eingeweiden erkranken, sodass sie nach Jahr und Tag infolge der
Krankheit herausfallen werden.

<<v16>>
16 Der Herr reizte nun den Wagemut der Philister und der Araber, die
neben den Kuschitern wohnen, gegen Joram auf. [fn:6]

<<v17>>
17 Sie zogen gegen Juda, überfielen das Land und nahmen den ganzen
Besitz weg, der sich im Palast des Königs fand; auch seine Söhne und
Frauen führten sie weg. Es blieb ihm kein Sohn außer Joahas, dem
jüngsten von ihnen. [fn:7]

<<v18>>
18 Nach all dem schlug der Herr den Joram mit einer unheilbaren
Krankheit in den Eingeweiden.

<<v19>>
19 Nach Jahr und Tag, zwei Tage vor seinem Ende, fielen infolge der
Krankheit seine Eingeweide heraus und er starb unter großen Schmerzen.
Das Volk zündete zu seiner Ehre kein Feuer an, wie das bei seinen Vätern
geschehen war.

<<v20>>
20 Er war zweiunddreißig Jahre alt, als er König wurde, und regierte
acht Jahre in Jerusalem. Er ging dahin, von niemand bedauert. Man begrub
ihn in der Davidstadt, aber nicht in den Gräbern der Könige.\\
\\

* Footnotes

[fn:1] [[file:1.Kön_22.org::v51][1 Kön 22,51]]

[fn:2] Juda: Text korr. nach G; H: Israel, doch vgl. die Anmerkung zu [[file:2.Chr_10.org::v1][10,1]].

[fn:3] (5-10) [[file:2.Kön_8.org::v16][2 Kön 8,16]]-[[file:2.Kön_8.org::v24][24]]

[fn:4] [[file:1.Kön_11.org::v36][1 Kön 11,36]]

[fn:5] 8-10: Vgl. die Anmerkung zu [[file:2.Kön_8.org::v21][2 Kön 8,21]].

[fn:6] Kuschiter: wie in [[file:2.Chr_14.org::v8][14,8]].

[fn:7] Joahas: Im folgenden wird er Ahasja genannt.
