#+TITLE: 2 Chr 19 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 22:35]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 19.html

* 2.Chr 19

<<verses>>

<<v1>>
1 Joschafat aber, der König von Juda, kehrte wohlbehalten nach Jerusalem
in sein Haus zurück.

<<v2>>
2 Da trat ihm der Seher Jehu, der Sohn Hananis, entgegen und hielt ihm
vor: Musstest du dem Frevler helfen und liebst du jene, die den Herrn
hassen? So lastet nun der Zorn des Herrn auf dir.

<<v3>>
3 Doch fand sich auch Gutes an dir. Du hast die Kultpfähle aus dem Land
beseitigt und deinen Sinn darauf gerichtet, den wahren Gott zu suchen.\\
\\

<<v4>>
* Joschafats Sorge für das Recht: 19,4-11

4 Joschafat blieb in Jerusalem. Dann zog er wieder von Beerscheba bis
zum Gebirge Efraim unter dem Volk umher und führte es zum Herrn, dem
Gott ihrer Väter, zurück.

<<v5>>
5 Er bestellte Richter im Land für jede einzelne feste Stadt Judas [fn:1]

<<v6>>
6 und gab ihnen die Weisung: Seht zu, was ihr tut; denn nicht im Auftrag
von Menschen haltet ihr Gericht, sondern im Auftrag des Herrn. Er steht
euch in der Rechtsprechung zur Seite.

<<v7>>
7 Lasst euch also von der Furcht des Herrn leiten und handelt
gewissenhaft; denn beim Herrn, unserem Gott, gibt es keine
Ungerechtigkeit, kein Ansehen der Person, keine Bestechlichkeit.

<<v8>>
8 Außerdem bestellte Joschafat in Jerusalem Leviten, Priester und
Familienhäupter für das Gericht des Herrn und für Streitigkeiten unter
den Einwohnern Jerusalems. [fn:2]

<<v9>>
9 Er trug ihnen auf: Mit Furcht vor dem Herrn, mit Festigkeit und
ehrlichem Herzen verfahrt folgendermaßen:

<<v10>>
10 Bei jedem Streitfall, den eure Brüder in ihren Städten euch vorlegen,
mag es sich nun um Blutschuld oder um eine Weisung, um ein Gebot oder um
Gesetze und Rechte handeln, sollt ihr die Beteiligten warnen, damit sie
nicht vor dem Herrn schuldig werden und ein Zorngericht über euch und
eure Brüder kommt. Das sollt ihr tun, damit ihr euch nicht versündigt.

<<v11>>
11 Seht, der Oberpriester Amarja ist euer Vorgesetzter in allen
Angelegenheiten des Herrn und Sebadja, der Sohn Jischmaels, der Fürst
des Hauses Juda, in allen Angelegenheiten des Königs. Als Beamte stehen
euch die Leviten zur Verfügung. Geht mutig an die Arbeit und der Herr
sei mit dem, der seine Pflicht erfüllt.\\
\\

* Footnotes

[fn:1] Die Einsetzung von Richtern in den Städten entspricht
dem Gesetz in [[file:Dtn_16.org::v18][Dtn 16,18]].

[fn:2] Gemeint sind Streitigkeiten unter den Einwohnern (Text
korr. nach G) Jerusalems bei Vergehen gegen das göttliche Gesetz.
