#+TITLE: 2 Chr 26 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-22 Mi 23:08]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Chr 26.html

<<verses>>

<<v1>>
* Usija (Asarja): 26,1-23

1 Das ganze Volk von Juda nahm Usija, der damals sechzehn Jahre alt war,
und machte ihn zum König anstelle seines Vaters Amazja. [fn:1]

<<v2>>
2 Er baute Elat aus, das er für Juda zurückgewonnen hatte, nachdem
Amazja zu seinen Vätern entschlafen war.

<<v3>>
3 Usija war sechzehn Jahre alt, als er König wurde, und regierte
zweiundfünfzig Jahre in Jerusalem. Seine Mutter hieß Jecholja und
stammte aus Jerusalem.

<<v4>>
4 Genau wie sein Vater Amazja tat er, was dem Herrn gefiel. [fn:2]

<<v5>>
5 Er war bestrebt, Gott zu suchen, solange Secharja lebte, der ihn in
der Furcht Gottes unterwies, und solange er den Herrn suchte, ließ ihn
Gott erfolgreich sein. [fn:3]

<<v6>>
6 Er unternahm einen Kriegszug gegen die Philister, riss die Mauern von
Gat, Jabne und Aschdod nieder und baute Städte bei Aschdod und im
übrigen Gebiet der Philister aus.

<<v7>>
7 Gott stand ihm bei gegen die Philister, gegen die Araber, die in
Gur-Baal wohnten, und gegen die Mëuniter. [fn:4]

<<v8>>
8 Die Ammoniter zahlten ihm Tribut und sein Ruhm reichte bis an die
Grenze Ägyptens, denn er war überaus mächtig geworden.

<<v9>>
9 In Jerusalem baute Usija Türme am Ecktor und am Taltor sowie im Winkel
und befestigte sie.

<<v10>>
10 Auch in der Steppe baute er Türme und grub viele Zisternen. Er besaß
nämlich große Herden in der Schefela und in der Ebene und beschäftigte
Acker- und Weinbauern in den Bergen und im Fruchtland, denn er liebte
den Ackerbau.

<<v11>>
11 Usija hatte ein kriegstüchtiges Heer, das, nach Abteilungen
gegliedert, in der Stärke ausrückte, die der Staatsschreiber Jëiël und
der Amtmann Maaseja unter Aufsicht Hananjas, eines der Obersten des
Königs, bei der Musterung festgestellt hatten.

<<v12>>
12 Unter den Kriegern waren insgesamt zweitausendsechshundert Häupter
von Großfamilien.

<<v13>>
13 Sie befehligten ein Heer von dreihundertsiebentausendfünfhundert
kampffähigen Männern, die stark genug waren, um dem König gegen seine
Feinde zu helfen.

<<v14>>
14 Für das ganze Heer stellte Usija Schilde, Lanzen, Helme, Panzer,
Bogen und Schleudersteine bereit.

<<v15>>
15 In Jerusalem ließ er kunstvolle Wurfmaschinen bauen und auf den
Türmen und Mauerecken aufstellen, um Pfeile und große Steine abschießen
zu können. So wurde er weithin berühmt; denn ihm wurde außergewöhnliche
Hilfe zuteil, sodass er an Macht gewann.

<<v16>>
16 Doch als er mächtig geworden war, wurde sein Herz übermütig und er
handelte verkehrt. Er wurde dem Herrn, seinem Gott, untreu und drang in
den Tempel des Herrn ein, um auf dem Rauchopferaltar zu opfern.

<<v17>>
17 Aber der Priester Asarja folgte ihm mit achtzig mutigen Priestern des
Herrn.

<<v18>>
18 Sie traten dem König Usija entgegen und sagten zu ihm: Nicht dir,
Usija, steht es zu, dem Herrn Rauchopfer darzubringen, sondern den
Priestern, den Söhnen Aarons, die geweiht sind, das Rauchopfer
darzubringen. Verlass das Heiligtum; denn du bist untreu geworden und es
gereicht dir nicht zur Ehre vor Gott, dem Herrn.

<<v19>>
19 Usija wurde zornig; er hielt schon die Räucherpfanne in der Hand, um
das Rauchopfer darzubringen. Als er sich aber zornig gegen die Priester
wandte, brach an seiner Stirn der Aussatz hervor. Es geschah vor den
Augen der Priester, während er im Tempel neben dem Rauchopferaltar
stand.

<<v20>>
20 Als daher der Oberpriester Asarja und alle anderen Priester sich ihm
zuwandten, zeigte sich der Aussatz an seiner Stirn. Sie drängten ihn
eiligst von dort weg und auch er selbst beeilte sich hinauszukommen, da
der Herr ihn geschlagen hatte.

<<v21>>
21 So war König Usija aussätzig bis zu seinem Tod. Da er vom Haus des
Herrn ausgeschlossen war, musste er als Aussätziger in einem
abgesonderten Haus wohnen, während sein Sohn Jotam Vorsteher des
königlichen Palastes war und die Bürger des Landes regierte.

<<v22>>
22 Die übrige Geschichte Usijas, die frühere und die spätere, schrieb
der Prophet Jesaja, der Sohn des Amoz.

<<v23>>
23 Usija entschlief zu seinen Vätern und man begrub ihn bei seinen
Vätern auf dem Feld bei der Grabstätte der Könige; denn man sagte: Er
war aussätzig. Sein Sohn Jotam wurde König an seiner Stelle.\\
\\

* Footnotes

[fn:1] (1-23) [[file:2.Kön_14.org::v21][2 Kön 14,21]]-[[file:2.Kön_14.org::v22][22]]; [[file:2.Kön_15.org::v1][15,1]]-[[file:2.Kön_15.org::v7][7]]

[fn:2] Der Vergleich mit Amazja ist aus [[file:2.Kön_15.org::v3][2 Kön 15,3]] übernommen;
vgl. aber die Anmerkung zu [[file:2.Chr_25.org::v2][25,2]].

[fn:3] in der Furcht: Text korr. nach G. - Secharja ist sonst unbekannt.

[fn:4] Zu den Mëunitern vgl. die Anmerkung zu [[file:2.Chr_20.org::v1][20,1]].
