#+TITLE: 2 Kön 20 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 10:28]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Kön 20.html

<<verses>>

<<v1>>

* Die Krankheit Hiskijas: 20,1-11

In jenen Tagen wurde Hiskija schwer krank und war dem Tod nahe. Der
Prophet Jesaja, der Sohn des Amoz, kam zu ihm und sagte: So spricht der
Herr: Bestell dein Haus; denn du wirst sterben, du wirst nicht am Leben
bleiben. [fn:1]

<<v2>>
2 Da drehte sich Hiskija mit dem Gesicht zur Wand und betete zum Herrn:

<<v3>>
3 Ach, Herr, denk daran, dass ich mein Leben lang treu und mit
aufrichtigem Herzen meinen Weg vor deinen Augen gegangen bin und dass
ich immer getan habe, was dir gefällt. Und Hiskija begann laut zu
weinen.

<<v4>>
4 Jesaja hatte aber die innere Stadt noch nicht verlassen, als das Wort
des Herrn an ihn erging:

<<v5>>
5 Kehr um und sag zu Hiskija, dem Fürsten meines Volkes: So spricht der
Herr, der Gott deines Vaters David: Ich habe dein Gebet gehört und deine
Tränen gesehen. Nun heile ich dich. Übermorgen wirst du zum Haus des
Herrn hinaufgehen;

<<v6>>
6 zu deiner Lebenszeit will ich noch fünfzehn Jahre hinzufügen. Und ich
will dich und diese Stadt aus der Hand des Königs von Assur retten und
diese Stadt beschützen, um meinetwillen und um meines Knechtes David
willen.

<<v8>>
8 Hiskija aber fragte Jesaja: Was ist das Zeichen dafür, dass der Herr
mich heilen wird und ich übermorgen zum Haus des Herrn hinaufgehen
werde? [fn:2]

<<v9>>
9 Jesaja antwortete: Das soll für dich das Zeichen des Herrn sein, dass
der Herr sein Versprechen halten wird: Soll der Schatten zehn Stufen
weiter abwärts oder zehn Stufen rückwärts gehen? [fn:3]

<<v10>>
10 Hiskija erwiderte: Für den Schatten ist es ein Leichtes, zehn Stufen
weiter abwärts zu gehen. Nein, er soll zehn Stufen rückwärts gehen.

<<v11>>
11 Da rief der Prophet Jesaja zum Herrn und dieser ließ den Schatten die
zehn Stufen zurückgehen, die er auf den Stufen des Ahas bereits
herabgestiegen war.

<<v7>>
7 Darauf sagte Jesaja: Holt einen Feigenbrei! Man holte ihn, strich ihn
auf das Geschwür und der König wurde gesund.\\
\\

<<v12>>
* Die Gesandtschaft aus Babel: 20,12-21

12 Damals sandte Merodach-Baladan, der Sohn Baladans, der König von
Babel, einen Brief und Geschenke an Hiskija; denn er hatte von seiner
Krankheit gehört. [fn:4] [fn:5]

<<v13>>
13 Hiskija freute sich darüber und zeigte den Gesandten sein ganzes
Schatzhaus, das Silber und das Gold, die Vorräte an Balsam und feinem
Öl, sein Waffenlager und alle anderen Schätze, die er besaß. Es gab
nichts in seinem Haus und in seinem Herrschaftsbereich, das er ihnen
nicht gezeigt hätte. [fn:6]

<<v14>>
14 Danach kam der Prophet Jesaja zu König Hiskija und fragte ihn: Was
haben diese Männer gesagt? Woher sind sie gekommen? Hiskija antwortete:
Sie sind aus einem fernen Land, aus Babel, gekommen.

<<v15>>
15 Er fragte weiter: Was haben sie in deinem Haus gesehen? Hiskija
antwortete: Sie haben alles gesehen, was in meinem Haus ist. Es gibt
nichts in meinen Schatzkammern, das ich ihnen nicht gezeigt hätte.

<<v16>>
16 Da sagte Jesaja zu Hiskija: Höre das Wort des Herrn:

<<v17>>
17 Es werden Tage kommen, an denen man alles, was in deinem Haus ist,
alles, was deine Väter bis zum heutigen Tag angesammelt haben, nach
Babel bringt. Nichts wird übrig bleiben, spricht der Herr.

<<v18>>
18 Auch von deinen eigenen Söhnen, die du noch bekommen wirst, wird man
einige mitnehmen und sie werden als Kämmerer im Palast des Königs von
Babel dienen müssen.

<<v19>>
19 Hiskija sagte zu Jesaja: Das Wort des Herrn, das du mir gesagt hast,
ist gut. Und er dachte: Wenn nur zu meinen Lebzeiten noch Friede und
Sicherheit herrschen.

<<v20>>
20 Die übrige Geschichte Hiskijas und alle seine Erfolge, wie er den
Teich und die Wasserleitung angelegt und das Wasser in die Stadt
geleitet hat, das alles ist aufgezeichnet in der Chronik der Könige von
Juda.

<<v21>>
21 Hiskija entschlief zu seinen Vätern und sein Sohn Manasse wurde König
an seiner Stelle.\\
\\

* Footnotes

[fn:1] (1-11) [[file:Jes_38.org::v1][Jes 38,1-8]]; [[file:2.Chr_32.org::v24][2 Chr 32,24-26]]

[fn:2] V. 7 ist wegen des Zusammenhangs nach V. 11 eingereiht.

[fn:3] soll der Schatten: Text korr. nach G. Es kann sich um
die Beobachtung des Schattens an einer Sonnenuhr oder an den Stufen der
Treppe handeln.

[fn:4] (12-19) [[file:Jes_39.org::v1][Jes 39,1-8]]

[fn:5] Merodach: nach G und Jes 39,1; H: Berodach.

[fn:6] freute sich: Text korr. nach G und Jes 39,2; H: hörte
davon. Merodach-Baladan hatte sich im Kampf gegen Assur zum König von
Babylon gemacht und suchte Bundesgenossen. Hiskija scheint bereit
gewesen zu sein und zeigte seine Schätze, um sich als leistungsfähigen
Helfer zu empfehlen. Jesaja hatte wiederholt vor solchen Bündnissen
gewarnt.
