#+TITLE: 2 Kön 11 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-18 Sa 21:46]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Kön 11.html

<<verses>>

<<v1>>
* Atalja: 11,1-20

1 Als Atalja, die Mutter Ahasjas, sah, dass ihr Sohn tot war, ging sie
daran, die ganze Nachkommenschaft der königlichen Familie auszurotten. [fn:1]

<<v2>>
2 Doch Joscheba, die Tochter des Königs Joram und Schwester Ahasjas,
nahm Joasch, den Sohn Ahasjas, aus dem Kreis der Königssöhne, die
ermordet werden sollten, weg und brachte ihn heimlich mit seiner Amme in
die Bettenkammer. Dort versteckte sie ihn vor Atalja, sodass er nicht
getötet wurde. [fn:2]

<<v3>>
3 Er blieb sechs Jahre bei ihr im Haus des Herrn verborgen, während
Atalja das Land regierte. [fn:3]

<<v4>>
4 Im siebten Jahr bestellte der Priester Jojada die Hundertschaftsführer
der Karer und Läufer zu sich. Er führte sie in das Haus des Herrn,
schloss mit ihnen ein Abkommen, ließ sie im Haus des Herrn schwören und
zeigte ihnen den Sohn des Königs. [fn:4]

<<v5>>
5 Dann ordnete er an: Das ist es, was ihr tun sollt: Ein Drittel von der
Wache, die am Sabbat aufzieht, soll den Königspalast bewachen, [fn:5]

<<v6>>
6 ein Drittel soll am Tor Sur und ein Drittel am Tor hinter den Läufern
stehen. Auf diese Weise sollt ihr abwechselnd die Bewachung des Tempels
übernehmen.

<<v7>>
7 Die zwei Abteilungen aber, die am Sabbat abziehen, sollen im Haus des
Herrn beim König als Wache stehen.

<<v8>>
8 Schart euch mit der Waffe in der Hand um den König! Wer in die Reihen
einzudringen versucht, soll getötet werden. Seid beim König, wenn er
auszieht und wenn er einzieht.

<<v9>>
9 Die Führer der Hundertschaften befolgten alle Weisungen des Priesters
Jojada. Jeder holte seine Leute, sowohl jene, die am Sabbat aufzogen,
als auch jene, die am Sabbat abzogen. Sie kamen zum Priester Jojada

<<v10>>
10 und dieser gab den Anführern der Hundertschaften die Lanzen und
Schilde, die dem König David gehört hatten und sich jetzt im Haus des
Herrn befanden.

<<v11>>
11 Die Läufer stellten sich mit der Waffe in der Hand von der Südseite
des Tempels bis zur Nordseite vor dem Altar und dem Tempel rings um den
König auf.

<<v12>>
12 Dann führte Jojada den Königssohn heraus und überreichte ihm den
Stirnreif und das Königsgesetz. So machten sie ihn zum König, salbten
ihn, klatschten in die Hände und riefen: Es lebe der König! [fn:6]

<<v13>>
13 Als Atalja das Geschrei des Volkes hörte, kam sie zu den Leuten in
das Haus des Herrn.

<<v14>>
14 Da sah sie den König am gewohnten Platz bei der Säule stehen; die
Obersten und die Trompeter waren bei ihm und alle Bürger des Landes
waren voller Freude und bliesen die Trompeten. Atalja zerriss ihre
Kleider und schrie: Verrat, Verrat!

<<v15>>
15 Doch der Priester Jojada befahl den Hundertschaftsführern, die das
Kommando über die Truppen hatten: Führt sie durch die Reihen hinaus und
schlagt jeden mit dem Schwert nieder, der ihr folgen will; denn so sagte
der Priester - sie soll nicht im Haus des Herrn getötet werden.

<<v16>>
16 Da legte man Hand an sie, und als sie an den Weg kam, auf dem man die
Pferde zum Palast des Königs führt, wurde sie dort getötet.

<<v17>>
17 Jojada schloss nun den Bund des Herrn mit König und Volk. Sie
versprachen, dass sie das Volk des Herrn sein wollten. Auch König und
Volk ließ er einen Bund schließen. [fn:7]

<<v18>>
18 Darauf zogen alle Bürger des Landes zum Baalstempel und rissen ihn
nieder. Sie zertrümmerten seine Altäre und Bilder vollständig und
erschlugen den Baalspriester Mattan vor den Altären. Auch stellte Jojada
Posten vor das Haus des Herrn

<<v19>>
19 und rief die Hundertschaftsführer, die Karer und Läufer sowie alle
Bürger des Landes herbei. Sie führten den König aus dem Haus des Herrn
durch das Tor der Läufer hinab in den königlichen Palast. Dort setzte er
sich auf den Thron der Könige.

<<v20>>
20 Alle Bürger des Landes waren voll Freude und die Stadt blieb ruhig.
Atalja aber hatte man vor dem Palast des Königs mit dem Schwert
umgebracht.\\
\\

* Footnotes

[fn:1] (1-20) [[file:2.Chr_22.org::v10][2 Chr 22,10]] - [[file:2.Chr_23.org::v21][23,21]]

[fn:2] versteckte sie: Text korr. nach G; H: versteckten sie.

[fn:3] Durch Atalja, die Tochter Ahabs, war die davidische
Linie unterbrochen. Ihre Regierung galt daher als illegitim.

[fn:4] Karer waren ausländische Söldner wie die Kereter und
Peleter. Zu den «Läufern» vgl. die Anmerkung zu [[file:1.Kön_14.org::v27][1 Kön 14,27]].

[fn:5] soll den Königspalast bewachen: Text korr. nach G.

[fn:6] [[file:Dtn_17.org::v18][Dtn 17,18]]

[fn:7] Der Bund zwischen König und Volk hatte die
Wiedereinsetzung der davidischen Dynastie zum Ziel.
