#+TITLE: 2 Kön 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 10:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Kön 21.html


<<verses>>

<<v1>>
* Manasse: 21,1-18
     :PROPERTIES:
     :CUSTOM_ID: manasse-211-18
     :END:
1 Manasse war zwölf Jahre alt, als er König wurde, und regierte
fünfundfünfzig Jahre in Jerusalem. Seine Mutter hieß Hefzi-Bah. [fn:1]

<<v2>>
2 Er tat, was dem Herrn missfiel, und ahmte die Gräuel der Völker nach,
die der Herr vor den Israeliten vertrieben hatte.

<<v3>>
3 Er baute die Kulthöhen wieder auf, die sein Vater Hiskija zerstört
hatte, errichtete Altäre für den Baal, ließ einen Kultpfahl anfertigen,
wie es schon Ahab, der König von Israel, getan hatte, warf sich vor dem
ganzen Heer des Himmels nieder und diente ihm. [fn:2] [fn:3]

<<v4>>
4 Auch baute er Altäre im Haus des Herrn, obwohl der Herr gesagt hatte:
Auf Jerusalem will ich meinen Namen legen. [fn:4]

<<v5>>
5 In den beiden Höfen des Tempels baute er Altäre für das ganze Heer des
Himmels.

<<v6>>
6 Er ließ seinen Sohn durch das Feuer gehen, trieb Zauberei und
Wahrsagerei, bestellte Totenbeschwörer und Zeichendeuter. So tat er
vieles, was dem Herrn missfiel und ihn erzürnte.

<<v7>>
7 Er brachte auch den Kultpfahl, den er hatte anfertigen lassen, in das
Haus, von dem der Herr zu David und dessen Sohn Salomo gesagt hatte: Auf
dieses Haus und auf Jerusalem, das ich aus allen Stämmen Israels
auserwählt habe, will ich meinen Namen auf ewig legen.

<<v8>>
8 Ich werde Israels Fuß nicht mehr unstet außerhalb des Landes wandern
lassen, das ich ihren Vätern gegeben habe, wenn sie nur alles befolgen,
was ich ihnen geboten habe, und mein ganzes Gesetz einhalten, das ihnen
mein Knecht Mose gegeben hat. [fn:5]

<<v9>>
9 Doch sie wollten nicht hören und Manasse verführte sie, noch
Schlimmeres zu tun als die Völker, die der Herr vor den Augen der
Israeliten vernichtet hatte.

<<v10>>
10 Da ließ der Herr durch seine Knechte, die Propheten, sagen:

<<v11>>
11 Weil Manasse, der König von Juda, diese Gräuel verübt und noch
Schlimmeres getrieben hat als die Amoriter vor ihm, weil er auch Juda
durch seine Götzen zur Sünde verführt hat,

<<v12>>
12 darum - so spricht der Herr, der Gott Israels: Ich bringe Unheil über
Jerusalem und Juda, sodass jedem, der davon hört, beide Ohren gellen
werden.

<<v13>>
13 Ich will an Jerusalem die Messschnur Samarias und die Waage des
Hauses Ahab anlegen und Jerusalem auswischen, wie man eine Schüssel
auswischt und dann umdreht.

<<v14>>
14 Den Rest meines Erbbesitzes will ich preisgeben und den Feinden
ausliefern. So wird mein Volk ein Raub und eine Beute all seiner Feinde
werden;

<<v15>>
15 denn es hat getan, was mir missfällt, und mich erzürnt seit dem Tag,
da seine Väter aus Ägypten zogen, bis zum heutigen Tag.

<<v16>>
16 Manasse vergoss unschuldiges Blut in Strömen, bis er Jerusalem von
einem Ende zum andern damit anfüllte; er verführte Juda zur Sünde,
sodass es tat, was dem Herrn missfiel.

<<v17>>
17 Die übrige Geschichte Manasses, alle seine Taten und die Sünden, die
er beging, sind aufgezeichnet in der Chronik der Könige von Juda.

<<v18>>
18 Manasse entschlief zu seinen Vätern und wurde im Garten seines
Hauses, im Garten Usas, begraben. Sein Sohn Amon wurde König an seiner
Stelle. [fn:6]\\
\\

<<v19>>
* Amon: 21,19-26
     :PROPERTIES:
     :CUSTOM_ID: amon-2119-26
     :END:
19 Amon war zweiundzwanzig Jahre alt, als er König wurde, und regierte
zwei Jahre in Jerusalem. Seine Mutter hieß Meschullemet und war eine
Tochter des Haruz aus Jotba. [fn:7]

<<v20>>
20 Wie sein Vater Manasse tat er, was dem Herrn missfiel,

<<v21>>
21 und folgte ganz den Wegen, die sein Vater gegangen war. Er diente den
Götzen, die sein Vater verehrt hatte, und warf sich vor ihnen nieder.

<<v22>>
22 Er verließ den Herrn, den Gott seiner Väter, und hielt sich nicht an
die Wege des Herrn.

<<v23>>
23 Gegen ihn zettelten seine Diener eine Verschwörung an und töteten ihn
in seinem Haus.

<<v24>>
24 Doch die Bürger des Landes erschlugen alle, die sich gegen den König
Amon verschworen hatten, und machten seinen Sohn Joschija zum König an
seiner Stelle.

<<v25>>
25 Die übrige Geschichte Amons, seine Taten, sind aufgezeichnet in der
Chronik der Könige von Juda.

<<v26>>
26 Man begrub ihn in seinem Grab im Garten Usas und sein Sohn Joschija
wurde König an seiner Stelle.\\
\\

* Footnotes

[fn:1] (1-18) [[file:2.Chr_33.org::v1][2 Chr 33,1-20]]

[fn:2] [[file:1.Kön_16.org::v33][1 Kön 16,33]]

[fn:3] Heer des Himmels: vgl. die Anmerkung zu 17,16.

[fn:4] [[file:1.Kön_8.org::v16][1 Kön 8,16]]

[fn:5] [[file:2.Sam_7.org::v10][2 Sam 7,10]]

[fn:6] [[file:2.Chr_33.org::v20][2 Chr 33,20]]

[fn:7] (19-24) [[file:2.Chr_33.org::v21][2 Chr 33,21-25]]
