#+TITLE: 2 Kön 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 00:31]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Kön 17.html

<<verses>>

<<v1>>
* Die Eroberung Samarias: 17,1-23

1 Im zwölften Jahr des Königs Ahas von Juda wurde Hoschea, der Sohn
Elas, in Samaria König von Israel. Er regierte neun Jahre

<<v2>>
2 und tat, was dem Herrn missfiel, jedoch nicht in dem Maß wie die
Könige von Israel, die vor ihm herrschten.

<<v3>>
3 Gegen ihn zog Salmanassar, der König von Assur. Hoschea musste sich
ihm unterwerfen und Abgaben entrichten.

<<v4>>
4 Dann aber erfuhr der König von Assur, dass Hoschea an einer
Verschwörung beteiligt war. Er hatte nämlich Boten nach So zum König von
Ägypten gesandt und die jährliche Abgabe an den König von Assur nicht
mehr geleistet. Daher ließ ihn dieser festnehmen und ins Gefängnis
werfen. [fn:1]

<<v5>>
5 Der König von Assur fiel über das ganze Land her, rückte gegen Samaria
vor und belagerte es drei Jahre lang. [fn:2]

<<v6>>
6 Im neunten Jahr Hoscheas eroberte er die Stadt, verschleppte die
Israeliten nach Assur und siedelte sie in Halach, am Habor, einem Fluss
von Gosan, und in den Städten der Meder an. [fn:3]

<<v7>>
7 Das geschah, weil die Israeliten sich gegen den Herrn, ihren Gott,
versündigten, der sie aus Ägypten, aus der Gewalt des Pharao, des Königs
von Ägypten, heraufgeführt hatte. Sie verehrten fremde Götter,

<<v8>>
8 ahmten die Bräuche der Völker nach, die der Herr vor den Israeliten
vertrieben hatte, und folgten dem Beispiel, das die Könige von Israel
gaben.

<<v9>>
9 Gegen den Herrn, ihren Gott, ersannen die Israeliten Dinge, die nicht
recht waren. Sie bauten sich Kulthöhen in allen ihren Städten, vom
Wachtturm angefangen bis zur befestigten Stadt,

<<v10>>
10 errichteten Steinmale und Kultpfähle auf jedem hohen Hügel und unter
jedem üppigen Baum.

<<v11>>
11 Auf allen Kulthöhen brachten sie Opfer dar wie die Völker, die der
Herr vor ihnen vertrieben hatte, taten böse Dinge und erzürnten dadurch
den Herrn.

<<v12>>
12 Sie dienten den Götzen, obwohl der Herr es ihnen verboten hatte.

<<v13>>
13 Der Herr warnte Israel und Juda durch alle seine Propheten, durch
alle Seher: Kehrt um von euren bösen Wegen, achtet auf meine Befehle und
meine Gebote genau nach dem Gesetz, das ich euren Vätern gegeben und
euch durch meine Knechte, die Propheten, verkündet habe.

<<v14>>
14 Doch sie wollten nicht hören, sondern versteiften ihre Nacken wie
ihre Väter, die nicht auf den Herrn, ihren Gott, vertrauten.

<<v15>>
15 Sie verwarfen seine Gebote und den Bund, den er mit ihren Vätern
geschlossen hatte, und verschmähten die Warnungen, die er an sie
richtete. Sie liefen nichtigen Göttern nach und wurden selbst zunichte;
sie ahmten die Völker ihrer Umgebung nach, obwohl der Herr verboten
hatte, ihrem Beispiel zu folgen. [fn:4]

<<v16>>
16 Sie übertraten alle Gebote des Herrn, ihres Gottes, schufen sich
Gussbilder, zwei Kälber, stellten einen Kultpfahl auf, beteten das ganze
Heer des Himmels an und dienten dem Baal. [fn:5]

<<v17>>
17 Ihre Söhne und Töchter ließen sie durch das Feuer gehen, trieben
Wahrsagerei und Zauberei und gaben sich dazu her zu tun, was dem Herrn
missfiel, und ihn zu erzürnen.

<<v18>>
18 Darum wurde der Herr über Israel sehr zornig. Er verstieß es von
seinem Angesicht, sodass der Stamm Juda allein übrig blieb.

<<v19>>
19 Doch auch Juda befolgte nicht die Befehle des Herrn, seines Gottes,
sondern ahmte die Bräuche nach, die Israel eingeführt hatte.

<<v20>>
20 Darum verwarf der Herr das ganze Geschlecht Israels. Er demütigte sie
und gab sie Räubern preis; schließlich verstieß er sie von seinem
Angesicht.

<<v21>>
21 Er hatte Israel vom Haus David losgerissen und sie hatten Jerobeam,
den Sohn Nebats, als König eingesetzt. Jerobeam aber machte Israel vom
Herrn abtrünnig und verführte es zu schwerer Sünde. [fn:6]

<<v22>>
22 Die Israeliten begingen all die Sünden, die Jerobeam begangen hatte,
und ließen nicht von ihnen ab.

<<v23>>
23 Schließlich verstieß der Herr Israel von sich, wie er es durch seine
Knechte, die Propheten, angedroht hatte. So wanderte Israel aus seinem
Land weg in die Verbannung nach Assur und blieb dort bis zum heutigen
Tag.\\
\\

<<v24>>
* Die Umsiedlung der Bevölkerung: 17,24-28

24 Der König von Assur brachte Leute aus Babel, Kuta, Awa, Hamat und
Sefarwajim in das Land und siedelte sie anstelle der Israeliten in den
Städten Samariens an. Sie nahmen Samarien in Besitz und ließen sich in
seinen Städten nieder. [fn:7]

<<v25>>
25 In der ersten Zeit, in der sie dort wohnten, erwiesen sie dem Herrn
keine Verehrung. Er schickte deshalb Löwen unter sie, die manche von
ihnen töteten.

<<v26>>
26 Da meldete man dem König von Assur: Die Völker, die du weggeführt und
in den Städten Samariens angesiedelt hast, wissen nicht, wie man den
Landesgott verehren soll. Er hat daher Löwen unter sie gesandt, von
denen sie getötet werden, weil sie nicht wissen, wie man den Landesgott
verehren soll.

<<v27>>
27 Da befahl der König von Assur: Bringt einen von den Priestern zurück,
die ihr von dort weggeführt habt. Er soll zu ihnen gehen, bei ihnen
wohnen und sie belehren, wie man den Landesgott verehren soll. [fn:8]

<<v28>>
28 So kam einer von den Priestern zurück, die man aus Samarien
weggeführt hatte. Er ließ sich in Bet-El nieder und belehrte sie, wie
man den Herrn verehren müsse.\\
\\

<<v29>>
* Die Religion der neuen Bevölkerung: 17,29-41

29 Jedes Volk aber schuf sich seine eigenen Götter und stellte sie in
den Höhentempeln auf, die von den Bewohnern Samariens erbaut worden
waren. Jedes Volk tat dies in der Stadt, in der es wohnte.

<<v30>>
30 Die Leute aus Babel machten sich Bilder Sukkot-Benots. Die Ansiedler
aus Kuta stellten Bilder Nergals her. Jene aus Hamat schufen Bilder
Aschimas. [fn:9]

<<v31>>
31 Die Awiter fertigten Bilder des Nibhas und des Tartak an. Die, die
aus Sefarwajim gekommen waren, verbrannten ihre Kinder zur Ehre
Adrammelechs und Anammelechs, der Götter von Sefarwajim.

<<v32>>
32 Gleichzeitig verehrten sie aber auch den Herrn. Auch setzten sie aus
ihren eigenen Reihen Priester für die Kulthöhen ein, die für sie in den
Höhentempeln Dienst taten.

<<v33>>
33 So verehrten sie den Herrn und dienten daneben ihren Göttern nach den
Bräuchen der Völker, aus denen man sie weggeführt hatte.

<<v34>>
34 Bis zum heutigen Tag handeln sie nach ihren früheren Bräuchen. Sie
fürchten den Herrn nicht und halten sich nicht an die Satzungen und
Bräuche, an das Gesetz und die Gebote, auf die der Herr die Nachkommen
Jakobs, dem er den Namen Israel gegeben hatte, verpflichtet hat. [fn:10]

<<v35>>
35 Der Herr hat nämlich mit ihnen einen Bund geschlossen und ihnen
befohlen: Ihr dürft keine fremden Götter verehren, sie nicht anbeten,
ihnen nicht dienen und ihnen keine Opfer darbringen.

<<v36>>
36 Den Herrn allein, der euch mit großer Kraft und hoch erhobenem Arm
aus Ägypten heraufgeführt hat, sollt ihr fürchten und anbeten und ihm
eure Opfer darbringen.

<<v37>>
37 Die Satzungen und Bräuche, das Gesetz und die Gebote, die er für euch
niedergeschrieben hat, sollt ihr befolgen und alle Tage erfüllen. Fremde
Götter aber dürft ihr nicht verehren.

<<v38>>
38 Ihr sollt den Bund, den er mit euch geschlossen hat, nicht vergessen
und fremde Götter nicht verehren.

<<v39>>
39 Den Herrn allein, euren Gott, sollt ihr fürchten. Er wird euch aus
der Gewalt all eurer Feinde erretten.

<<v40>>
40 Doch sie wollten nicht hören, sondern sie handelten, wie sie es immer
schon gewohnt waren.

<<v41>>
41 Sie verehren den Herrn und dienen zugleich ihren Götzen. Was ihre
Väter getan haben, das tun auch ihre Kinder und Kindeskinder bis zum
heutigen Tag.\\
\\

* Footnotes

[fn:1] So: Name der Stadt Saïs, Sitz der 24. Dynastie.

[fn:2] 5f: Beide Verse sind Parallelbericht zu V. 3f.

[fn:3] Samaria wurde im Spätherbst 722 v. Chr. erobert. Die
Wegführung der Bevölkerung erfolgte erst 720 durch Sargon. Die genannten
Gegenden liegen im nördlichen Mesopotamien. Medien ist das Bergland
südwestlich des Kaspischen Meers.

[fn:4] [[file:Jer_2.org::v5][Jer 2,5]]

[fn:5] Heer des Himmels: die Sterne, die von den östlichen
Völkern als Götter verehrt wurden.

[fn:6] [[file:1.Kön_11.org::v31][1 Kön 11,31]]

[fn:7] Die neue Bevölkerung kam aus dem Osten und Norden.

[fn:8] Er soll zu ihnen gehen: H: Sie sollen ...

[fn:9] 30f: Die Aufzählung nennt Namen von weniger oder nicht
bekannten Gottheiten, die vom Volk mehr verehrt wurden als die
Staatsgottheiten. Nergal ist der Gott der Unterwelt, der Sonnenhitze und
der Pest.

[fn:10] 34b-40a: Einschaltung, die die Schuld der im Land
verbliebenen Israeliten hervorhebt.
