#+TITLE: 2 Kön 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-18 Sa 17:17]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Kön 4.html

<<verses>>

<<v1>>
* Das Öl der Witwe: 4,1-7

1 Eine von den Frauen der Prophetenjünger wandte sich laut rufend an
Elischa: Mein Mann, dein Knecht, ist gestorben. Du weißt, dass dein
Knecht gottesfürchtig war. Nun kommt der Gläubiger, um sich meine beiden
Söhne als Sklaven zu nehmen. [fn:1]

<<v2>>
2 Elischa fragte sie: Was kann ich für dich tun? Sag mir: Was hast du im
Haus? Sie antwortete: Deine Magd hat nichts im Haus als einen Krug Öl.

<<v3>>
3 Da sagte er: Geh und erbitte dir auf der Gasse von allen deinen
Nachbarn leere Gefäße, aber nicht zu wenige!

<<v4>>
4 Dann geh heim, verschließ die Tür hinter dir und deinen Söhnen, gieß
Öl in alle diese Gefäße und stell die gefüllten beiseite!

<<v5>>
5 Sie ging von ihm weg und verschloss die Tür hinter sich und ihren
Söhnen. Diese reichten ihr die Gefäße hin und sie füllte ein.

<<v6>>
6 Als alle Gefäße voll waren, sagte sie zu ihrem Sohn: Bring mir noch
ein Gefäß! Er antwortete: Es ist keines mehr da. Da floss das Öl nicht
mehr weiter.

<<v7>>
7 Sie aber kam und erzählte es dem Gottesmann. Dieser befahl ihr: Geh,
verkauf das Öl und bezahl deine Schuld! Von dem, was übrig bleibt, magst
du mit deinen Söhnen leben.\\
\\

<<v8>>
* Die Totenerweckung: 4,8-37

8 Eines Tages ging Elischa nach Schunem. Dort lebte eine vornehme Frau,
die ihn dringend bat, bei ihr zu essen. Seither kehrte er zum Essen bei
ihr ein, sooft er vorbeikam. [fn:2]

<<v9>>
9 Sie aber sagte zu ihrem Mann: Ich weiß, dass dieser Mann, der ständig
bei uns vorbeikommt, ein heiliger Gottesmann ist.

<<v10>>
10 Wir wollen ein kleines, gemauertes Obergemach herrichten und dort ein
Bett, einen Tisch, einen Stuhl und einen Leuchter für ihn bereitstellen.
Wenn er dann zu uns kommt, kann er sich dorthin zurückziehen.

<<v11>>
11 Als Elischa eines Tages wieder hinkam, ging er in das Obergemach, um
dort zu schlafen.

<<v12>>
12 Dann befahl er seinem Diener Gehasi: Ruf diese Schunemiterin! Er rief
sie, und als sie vor ihm stand,

<<v13>>
13 befahl er dem Diener: Sag zu ihr: Du hast dir so viel Mühe um uns
gemacht. Was können wir für dich tun? Sollen wir beim König oder beim
Obersten des Heeres ein Wort für dich einlegen? Doch sie entgegnete: Ich
wohne inmitten meiner Verwandten. [fn:3]

<<v14>>
14 Und als er weiter fragte, was man für sie tun könne, sagte Gehasi:
Nun, sie hat keinen Sohn und ihr Mann ist alt.

<<v15>>
15 Da befahl er: Ruf sie herein! Er rief sie und sie blieb in der Tür
stehen.

<<v16>>
16 Darauf versicherte ihr Elischa: Im nächsten Jahr um diese Zeit wirst
du einen Sohn liebkosen. Sie aber entgegnete: Ach nein, Herr, Mann
Gottes, täusche doch deiner Magd nichts vor!

<<v17>>
17 Doch die Frau wurde schwanger und im nächsten Jahr, um die Zeit, die
Elischa genannt hatte, gebar sie einen Sohn.

<<v18>>
18 Als das Kind herangewachsen war, ging es eines Tages zu seinem Vater
hinaus zu den Schnittern. [fn:4]

<<v19>>
19 Dort klagte es ihm: Mein Kopf, mein Kopf! Der Vater befahl seinem
Knecht: Trag das Kind heim zu seiner Mutter!

<<v20>>
20 Der Knecht nahm es und brachte es zu ihr. Es saß noch bis zum Mittag
auf ihren Knien; dann starb es.

<<v21>>
21 Sie stieg nun in das obere Gemach hinauf, legte das Kind auf das Bett
des Gottesmannes und schloss die Tür hinter ihm ab. Dann verließ sie das
Haus,

<<v22>>
22 rief ihren Mann und bat ihn: Schick mir einen von den Knechten und
einen Esel! Ich will zum Gottesmann eilen und komme bald zurück.

<<v23>>
23 Er wandte ein: Warum gehst du heute zu ihm? Es ist doch nicht Neumond
und nicht Sabbat. Doch sie sagte nur: Friede mit dir!, [fn:5]

<<v24>>
24 sattelte den Esel und befahl dem Knecht: Treib tüchtig an und halte
mich beim Reiten nicht auf, es sei denn, dass ich es dir sage.

<<v25>>
25 So reiste sie ab und kam zum Gottesmann auf den Karmel. Als er sie
von ferne sah, sagte er zu seinem Diener Gehasi: Da kommt die
Schunemiterin.

<<v26>>
26 Lauf ihr entgegen und frag sie: Geht es dir gut? Geht es auch deinem
Mann und dem Kind gut? Sie antwortete: Es geht gut.

<<v27>>
27 Sobald sie aber zum Gottesmann auf den Berg kam, umfasste sie seine
Füße. Gehasi trat hinzu, um sie wegzudrängen; aber der Gottesmann wehrte
ab: Lass sie; denn ihre Seele ist betrübt. Doch der Herr hat mir den
Grund verborgen und mir nicht mitgeteilt.

<<v28>>
28 Darauf sagte sie: Habe ich denn meinen Herrn um einen Sohn gebeten?
Habe ich nicht gesagt: Mach mir keine falschen Hoffnungen?

<<v29>>
29 Elischa befahl nun Gehasi: Gürte dich, nimm meinen Stab in die Hand
und mach dich auf den Weg! Wenn du jemand begegnest, so grüß ihn nicht;
und wenn dich jemand grüßt, so antworte ihm nicht! Leg meinen Stab auf
das Gesicht des Kindes!

<<v30>>
30 Aber die Mutter des Kindes sagte: So wahr der Herr lebt und so wahr
du lebst: Ich lasse nicht von dir ab. Da stand er auf und folgte ihr.

<<v31>>
31 Gehasi war vorausgeeilt und hatte den Stab auf das Gesicht des Kindes
gelegt; doch es kam kein Laut und kein Lebenszeichen. Daher lief er zum
Gottesmann zurück und berichtete: Das Kind ist nicht aufgewacht.

<<v32>>
32 Als Elischa in das Haus kam, lag das Kind tot auf seinem Bett.

<<v33>>
33 Er ging in das Gemach, schloss die Tür hinter sich und dem Kind und
betete zum Herrn.

<<v34>>
34 Dann trat er an das Bett und warf sich über das Kind; er legte seinen
Mund auf dessen Mund, seine Augen auf dessen Augen, seine Hände auf
dessen Hände. Als er sich so über das Kind hinstreckte, kam Wärme in
dessen Leib. [fn:6]

<<v35>>
35 Dann stand er auf, ging im Haus einmal hin und her, trat wieder an
das Bett und warf sich über das Kind. Da nieste es siebenmal und öffnete
die Augen.

<<v36>>
36 Nun rief Elischa seinen Diener Gehasi und befahl ihm, die
Schunemiterin zu rufen. Er rief sie, und als sie kam, sagte der
Gottesmann zu ihr: Nimm deinen Sohn!

<<v37>>
37 Sie trat hinzu, fiel Elischa zu Füßen und verneigte sich bis zur
Erde. Dann nahm sie ihren Sohn und ging hinaus.\\
\\

<<v38>>
* Die ungenießbare Speise: 4,38-41

38 Elischa kehrte nach Gilgal zurück. Im Land herrschte damals eine
Hungersnot. Als die Prophetenjünger vor ihm saßen, befahl er seinem
Diener: Setz den großen Topf auf und koch ein Gericht für die
Prophetenjünger!

<<v39>>
39 Einer von ihnen ging auf das Feld hinaus, um Malven zu holen. Dabei
fand er ein wildes Rankengewächs und pflückte davon so viele Früchte,
wie sein Gewand fassen konnte. Dann kam er zurück und schnitt sie in den
Kochtopf hinein, da man sie nicht kannte.

<<v40>>
40 Als man sie aber den Männern zum Essen vorsetzte und sie von der
Speise kosteten, schrien sie laut und riefen: Der Tod ist im Topf, Mann
Gottes. Sie konnten nichts essen.

<<v41>>
41 Doch er befahl: Bringt mir etwas Mehl! Er streute das Mehl in den
Topf und sagte: Setzt es nun den Leuten zum Essen vor! Jetzt war nichts
Schädliches mehr im Topf.\\
\\

<<v42>>
* Die Brotvermehrung: 4,42-44

42 Einmal kam ein Mann von Baal-Schalischa und brachte dem Gottesmann
Brot von Erstlingsfrüchten, zwanzig Gerstenbrote, und frische Körner in
einem Beutel. Elischa befahl seinem Diener: Gib es den Leuten zu essen!

<<v43>>
43 Doch dieser sagte: Wie soll ich das hundert Männern vorsetzen?
Elischa aber sagte: Gib es den Leuten zu essen! Denn so spricht der
Herr: Man wird essen und noch übrig lassen.

<<v44>>
44 Nun setzte er es ihnen vor; und sie aßen und ließen noch übrig, wie
der Herr gesagt hatte.\\
\\

* Footnotes

[fn:1] Zahlungsunfähige Schuldner konnten zu Sklaven gemacht
werden (vgl. [[file:Am_2.org::v6][Am 2,6]]; [[file:Am_8.org::v6][8,6]]; [[file:~/Documents/notes/Bibel/nt/Mt_18.org::v25][Mt 18,25]]).

[fn:2] Schunem: nördlich von Jesreel.

[fn:3] Die Frau hält eine Vermittlung beim König für unnötig
und bezeugt damit die starke Stellung des Familienverbands im
israelitischen Staat.

[fn:4] (18-37) [[file:1.Kön_17.org::v17][1 Kön 17,17-24]]

[fn:5] Aus der Frage geht hervor, dass man an Neumondtagen und
Sabbaten Propheten aufsuchte.

[fn:6] [[file:1.Kön_17.org::v21][1 Kön 17,21]]; [[file:~/Documents/notes/Bibel/nt/Apg_20.org::v10][Apg 20,10]]
