#+TITLE: 2 Kön 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-18 Sa 17:30]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Kön 7.html

* 2.Kön 7

<<verses>>

<<v1>>
1 Doch Elischa entgegnete: Hört das Wort des Herrn! So spricht der Herr:
Morgen um diese Zeit kostet am Tor von Samaria ein Sea Feinmehl nur noch
einen Schekel und auch zwei Sea Gerste kosten nur noch einen Schekel. [fn:1]

<<v2>>
2 Doch der Adjutant, auf dessen Arm sich der König stützte, antwortete
dem Gottesmann: Selbst wenn der Herr Schleusen am Himmel anbrächte,
könnte das nicht geschehen. Elischa erwiderte: Du wirst es mit deinen
eigenen Augen sehen, aber nicht davon essen.

<<v3>>
3 Vor dem Eingang des Stadttors saßen vier aussätzige Männer. Sie sagten
zueinander: Warum sitzen wir hier, bis wir sterben?

<<v4>>
4 Wollten wir in die Stadt gehen, in der Hungersnot herrscht, dann
sterben wir in ihr. Bleiben wir draußen, dann sterben wir auch. Kommt,
wir gehen in das Lager der Aramäer hinüber! Wenn sie uns am Leben
lassen, bleiben wir am Leben. Wenn sie uns töten, so sterben wir.

<<v5>>
5 Sie machten sich daher in der Abenddämmerung auf, um in das Lager der
Aramäer zu gehen. Doch als sie in den Bereich des aramäischen Lagers
kamen, war dort niemand zu sehen.

<<v6>>
6 Der Herr hatte nämlich das Rollen von Wagen, das Getrampel von Pferden
und das Lärmen eines großen Heeres im Lager vernehmen lassen, sodass
einer zum andern sagte: Der König von Israel hat die Könige der Hetiter
und die Könige von Ägypten gegen uns angeworben, um uns überfallen zu
lassen.

<<v7>>
7 Sie waren daher in der Dämmerung aufgebrochen und geflohen. Dabei
hatten sie ihre Zelte, Pferde und Esel und das ganze Lager, so wie es
war, zurückgelassen, um durch die Flucht ihr Leben zu retten.

<<v8>>
8 Als nun die Aussätzigen in den Bereich des Lagers kamen, gingen sie in
ein Zelt, aßen und tranken, nahmen Silber, Gold und Kleider und
entfernten sich, um die Beute zu verstecken. Dann kamen sie zurück,
gingen in ein anderes Zelt, machten auch hier ihre Beute und entfernten
sich wieder, um sie zu verstecken.

<<v9>>
9 Dann aber sagten sie zueinander: Wir handeln nicht recht. Heute ist
ein Tag froher Botschaft. Wenn wir schweigen und bis zum Morgengrauen
warten, trifft uns Schuld. Kommt also; wir gehen und melden es im Palast
des Königs.

<<v10>>
10 Sie machten sich auf, riefen die Wächter der Stadt und erzählten
ihnen: Wir sind in das Lager der Aramäer gekommen. Aber dort war niemand
zu sehen und kein menschlicher Laut zu hören. Die Pferde und Esel waren
angebunden und die Zelte standen so da, wie sie waren.

<<v11>>
11 Da schlugen die Wächter Lärm und man meldete es drinnen im Palast des
Königs. [fn:2]

<<v12>>
12 Noch in der Nacht stand der König auf und sagte zu seinen Leuten: Ich
will euch erklären, was die Aramäer gegen uns planen. Sie wissen, dass
wir Hunger leiden, und haben das Lager nur verlassen, um sich auf dem
freien Feld zu verstecken mit dem Hintergedanken: Wenn sie die Stadt
verlassen, nehmen wir sie lebendig gefangen und dringen in die Stadt
ein.

<<v13>>
13 Doch einer von den Leuten schlug vor: Man nehme doch fünf von den
noch vorhandenen Pferden. Ihnen mag es ergehen wie den vielen
Israeliten, die schon zugrunde gegangen sind. Wir wollen Männer mit den
Pferden hinschicken und dann weiter sehen. [fn:3]

<<v14>>
14 Man nahm also zwei Wagen mit den Pferden. Der König schickte sie der
Streitmacht der Aramäer nach und befahl ihnen: Brecht auf und seht nach!

<<v15>>
15 Sie fuhren hinter ihnen her bis an den Jordan und fanden den ganzen
Weg mit Kleidern und Waffen übersät, die die Aramäer auf ihrer
überstürzten Flucht weggeworfen hatten. Als sie zurückkamen und dem
König Meldung erstatteten,

<<v16>>
16 strömte das Volk hinaus und plünderte das Lager der Aramäer. Jetzt
kostete ein Sea Feinmehl nur noch einen Schekel und auch zwei Sea Gerste
kosteten nur noch einen Schekel, wie es der Herr vorausgesagt hatte.

<<v17>>
17 Der König hatte die Aufsicht über das Tor dem Adjutanten übertragen,
auf dessen Arm er sich zu stützen pflegte. Ihn trat das Volk im Stadttor
nieder und so starb er, wie es ihm der Gottesmann vorausgesagt hatte,
als der König gekommen war, um mit ihm zu reden.

<<v18>>
18 Als nämlich der Gottesmann zum König sagte: Morgen um diese Zeit
kosten am Tor von Samaria zwei Sea Gerste nur noch einen Schekel und ein
Sea Feinmehl kostet nur noch einen Schekel,

<<v19>>
19 hatte der Adjutant dem Gottesmann geantwortet: Selbst wenn der Herr
Schleusen am Himmel anbrächte, könnte dies nicht geschehen. Und Elischa
hatte ihm erwidert: Du wirst es mit deinen Augen sehen, aber nicht davon
essen.

<<v20>>
20 So geschah es ihm nun: Das Volk trat ihn im Tor nieder, sodass er
starb.\\
\\

* Footnotes

[fn:1] Man wird Lebensmittel wieder zu normalen Preisen
erhalten, sie werden also wieder in genügender Menge vorhanden sein.

[fn:2] schlugen Lärm: Text korr. nach G.

[fn:3] H ist durch Doppelschreibung einer Zeile entstellt.
