#+TITLE: 2 Kön 13 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-18 Sa 22:30]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Kön 13.html

<<verses>>

<<v1>>
* Joahas von Israel: 13,1-9

1 Im dreiundzwanzigsten Jahr des Joasch, des Sohnes Ahasjas, des Königs
von Juda, wurde Joahas, der Sohn Jehus, König von Israel. Er regierte
siebzehn Jahre in Samaria

<<v2>>
2 und tat, was dem Herrn missfiel; er hielt an der Sünde fest, zu der
Jerobeam, der Sohn Nebats, Israel verführt hatte, und ließ nicht von ihr
ab.

<<v3>>
3 Deswegen entbrannte der Zorn des Herrn gegen Israel. Er gab sie in die
Gewalt Hasaëls, des Königs von Aram, und seines Sohnes Ben-Hadad, die
ganze Zeit hindurch.

<<v4>>
4 Als aber Joahas den Herrn besänftigte, erhörte ihn der Herr; denn er
sah die Bedrängnis, die der König von Aram über Israel brachte.

<<v5>>
5 Er gab Israel einen Helfer, sodass es sich aus der Gewalt Arams
befreien konnte und die Israeliten wieder in ihren Zelten wohnten wie
früher.

<<v6>>
6 Doch ließen sie nicht von der Sünde ab, zu der das Haus Jerobeam
Israel verführt hatte, sondern hielten an ihr fest. Auch der Kultpfahl
blieb in Samaria stehen.

<<v7>>
7 Der Herr ließ vom Heer des Joahas nur fünfzig Wagenkämpfer, zehn Wagen
und zehntausend Mann Fußtruppen übrig. Alles andere hatte der König von
Aram vernichtet und dem Staub gleichgemacht, auf den man tritt. [fn:1]

<<v8>>
8 Die übrige Geschichte des Joahas, alle seine Taten und Erfolge, sind
aufgezeichnet in der Chronik der Könige von Israel.

<<v9>>
9 Er entschlief zu seinen Vätern; man begrub ihn in Samaria. Sein Sohn
Joasch wurde König an seiner Stelle.\\
\\

<<v10>>
* Joasch von Israel: 13,10-13

10 Im siebenunddreißigsten Jahr des Königs Joasch von Juda wurde Joasch,
der Sohn des Joahas, König von Israel. Er regierte sechzehn Jahre in
Samaria

<<v11>>
11 und tat, was dem Herrn missfiel; er ließ nicht von der Sünde ab, zu
der Jerobeam, der Sohn Nebats, Israel verführt hatte.

<<v12>>
12 Die übrige Geschichte des Joasch, alle seine Taten und Erfolge, wie
er mit Amazja, dem König von Juda, Krieg führte, all das ist
aufgezeichnet in der Chronik der Könige von Israel. [fn:2]

<<v13>>
13 Joasch entschlief zu seinen Vätern und Jerobeam bestieg seinen Thron.
Joasch wurde in Samaria bei den Königen von Israel begraben.\\
\\

<<v14>>
* Die Krankheit und der Tod Elischas: 13,14-21

14 Als Elischa von der Krankheit befallen wurde, an der er sterben
sollte, ging Joasch, der König von Israel, zu ihm hinab. Er weinte vor
ihm und rief: Mein Vater, mein Vater! Wagen Israels und sein Lenker! [fn:3]

<<v15>>
15 Doch Elischa befahl ihm: Hol einen Bogen und Pfeile! Er holte sie
herbei.

<<v16>>
16 Dann sagte Elischa zum König von Israel: Leg deine Hand auf den
Bogen! Da legte er die Hand auf den Bogen, Elischa aber legte seine
Hände auf die Hände des Königs.

<<v17>>
17 Hierauf sagte er: Öffne das Fenster nach Osten! Der König öffnete es
und Elischa forderte ihn auf zu schießen. Als er abschoss, rief Elischa:
Ein Siegespfeil vom Herrn, ein Siegespfeil gegen Aram. Du wirst Aram bei
Afek vernichtend schlagen. [fn:4]

<<v18>>
18 Weiter sagte er: Nimm die Pfeile! Als der König von Israel sie
genommen hatte, befahl ihm Elischa, auf den Boden zu schlagen. Der König
tat drei Schläge und hielt dann inne.

<<v19>>
19 Da wurde der Gottesmann unwillig über ihn und sagte: Du hättest fünf-
oder sechsmal schlagen sollen; dann hättest du die Aramäer vernichtend
geschlagen. Jetzt aber wirst du sie nur dreimal schlagen. [fn:5]

<<v20>>
20 Elischa starb und man begrub ihn. In jenem Jahr fielen moabitische
Räuberscharen in das Land ein. [fn:6]

<<v21>>
21 Als man einmal einen Toten begrub und eine dieser Scharen erblickte,
warf man den Toten in das Grab Elischas und floh. Sobald aber der Tote
die Gebeine Elischas berührte, wurde er wieder lebendig und richtete
sich auf.\\
\\

<<v22>>
* Die Erfolge gegen Aram: 13,22-25

22 Hasaël, der König von Aram, bedrängte Israel, solange Joahas lebte.

<<v23>>
23 Doch der Herr war seinem Volk gnädig und hatte Erbarmen mit ihm.
Wegen seines Bundes mit Abraham, Isaak und Jakob wandte er sich ihm
wieder zu. Er wollte es nicht verderben und hatte es bis dahin nicht von
seinem Angesicht verstoßen.

<<v24>>
24 Als daher Hasaël, der König von Aram, starb und sein Sohn Ben-Hadad
an seiner Stelle König wurde,

<<v25>>
25 konnte Joasch, der Sohn des Joahas, Ben-Hadad, dem Sohn Hasaëls, die
Städte wieder entreißen, die dieser seinem Vater Joahas im Krieg
weggenommen hatte. Dreimal schlug ihn Joasch und gewann die
israelitischen Städte zurück. [fn:7]\\
\\

* Footnotes

[fn:1] Der Vers ist Fortsetzung von V. 3.

[fn:2] (12-13) [[file:2.Kön_14.org::v15][14,15f]]

[fn:3] [[file:2.Kön_2.org::v12][2,12]]

[fn:4] Der König soll die Worte des Propheten durch
sinnbildliche Handlungen begleiten. Die Erfüllung der Weissagung
berichtet 1 Kön 20,26-30.

[fn:5] [[v25][13,25]]

[fn:6] In jenem Jahr: Text korr.; andere Korrektur: Jahr für Jahr.

[fn:7] [[file:1.Kön_20.org::v34][1 Kön 20,34]]
