#+TITLE: 2 Kön 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-18 Sa 17:25]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Kön 5.html

<<verses>>

<<v1>>
* Die Heilung des Aramäers Naaman: 5,1-27

1 Naaman, der Feldherr des Königs von Aram, galt viel bei seinem Herrn
und war angesehen; denn durch ihn hatte der Herr den Aramäern den Sieg
verliehen. Der Mann war tapfer, aber an Aussatz erkrankt.

<<v2>>
2 Nun hatten die Aramäer bei einem Streifzug ein junges Mädchen aus dem
Land Israel verschleppt. Es war in den Dienst der Frau Naamans gekommen.

<<v3>>
3 Es sagte zu seiner Herrin: Wäre mein Herr doch bei dem Propheten in
Samaria! Er würde seinen Aussatz heilen.

<<v4>>
4 Naaman ging zu seinem Herrn und meldete ihm: Das und das hat das
Mädchen aus Israel gesagt.

<<v5>>
5 Der König von Aram antwortete: So geh doch hin; ich werde dir ein
Schreiben an den König von Israel mitgeben. Naaman machte sich auf den
Weg. Er nahm zehn Talente Silber, sechstausend Schekel Gold und zehn
Festkleider mit

<<v6>>
6 und überbrachte dem König von Israel das Schreiben. Es hatte folgenden
Inhalt: Wenn jetzt dieser Brief zu dir gelangt, so wisse: Ich habe
meinen Knecht Naaman zu dir geschickt, damit du seinen Aussatz heilst. [fn:1]

<<v7>>
7 Als der König von Israel den Brief gelesen hatte, zerriss er seine
Kleider und rief: Bin ich denn ein Gott, der töten und zum Leben
erwecken kann? Er schickt einen Mann zu mir, damit ich ihn von seinem
Aussatz heile. Merkt doch und seht, dass er nur Streit mit mir sucht.

<<v8>>
8 Als der Gottesmann Elischa hörte, der König von Israel habe seine
Kleider zerrissen, ließ er ihm sagen: Warum hast du deine Kleider
zerrissen? Naaman soll zu mir kommen; dann wird er erfahren, dass es in
Israel einen Propheten gibt.

<<v9>>
9 So kam Naaman mit seinen Pferden und Wagen und hielt vor dem Haus
Elischas.

<<v10>>
10 Dieser schickte einen Boten zu ihm hinaus und ließ ihm sagen: Geh und
wasch dich siebenmal im Jordan! Dann wird dein Leib wieder gesund, und
du wirst rein.

<<v11>>
11 Doch Naaman wurde zornig. Er ging weg und sagte: Ich dachte, er würde
herauskommen, vor mich hintreten, den Namen Jahwes, seines Gottes,
anrufen, seine Hand über die kranke Stelle bewegen und so den Aussatz
heilen.

<<v12>>
12 Sind nicht der Abana und der Parpar, die Flüsse von Damaskus, besser
als alle Gewässer Israels? Kann ich nicht dort mich waschen, um rein zu
werden? Voll Zorn wandte er sich ab und ging weg.

<<v13>>
13 Doch seine Diener traten an ihn heran und redeten ihm zu: Wenn der
Prophet etwas Schweres von dir verlangt hätte, würdest du es tun; wie
viel mehr jetzt, da er zu dir nur gesagt hat: Wasch dich und du wirst
rein. [fn:2]

<<v14>>
14 So ging er also zum Jordan hinab und tauchte siebenmal unter, wie ihm
der Gottesmann befohlen hatte. Da wurde sein Leib gesund wie der Leib
eines Kindes und er war rein.

<<v15>>
15 Nun kehrte er mit seinem ganzen Gefolge zum Gottesmann zurück, trat
vor ihn hin und sagte: Jetzt weiß ich, dass es nirgends auf der Erde
einen Gott gibt außer in Israel. So nimm jetzt von deinem Knecht ein
Dankgeschenk an!

<<v16>>
16 Elischa antwortete: So wahr der Herr lebt, in dessen Dienst ich
stehe: Ich nehme nichts an. Auch als Naaman ihn dringend bat, es zu
nehmen, lehnte er ab.

<<v17>>
17 Darauf sagte Naaman: Wenn es also nicht sein kann, dann gebe man
deinem Knecht so viel Erde, wie zwei Maultiere tragen können; denn dein
Knecht wird keinem andern Gott mehr Brand- und Schlachtopfer darbringen
als Jahwe allein. [fn:3]

<<v18>>
18 Nur dies möge Jahwe deinem Knecht verzeihen: Wenn mein Herr zur
Anbetung in den Tempel Rimmons geht, stützt er sich dort auf meinen Arm.
Ich muss mich dann im Tempel Rimmons niederwerfen, wenn er sich dort
niederwirft. Dann möge das Jahwe deinem Knecht verzeihen. [fn:4]

<<v19>>
19 Elischa antwortete: Geh in Frieden! Als Naaman schon eine Strecke
Weges von ihm entfernt war,

<<v20>>
20 sagte sich Gehasi, der Diener Elischas, des Gottesmannes: Mein Herr
hat diesen Aramäer Naaman geschont und nichts von dem angenommen, was er
mitgebracht hatte. So wahr der Herr lebt: Ich werde ihm nachlaufen und
mir etwas von ihm holen.

<<v21>>
21 Gehasi eilte ihm also nach. Als ihn Naaman hinter sich herankommen
sah, beugte er sich ihm vom Wagen aus zu und fragte: Steht alles gut?

<<v22>>
22 Er antwortete: Ja; nur lässt mein Herr sagen: Soeben sind vom Gebirge
Efraim zwei junge Männer, zwei Prophetenjünger, zu mir gekommen. Gib
ihnen doch ein Talent Silber und zwei Festkleider!

<<v23>>
23 Naaman erwiderte: Tu mir den Gefallen und nimm zwei Talente! Er bat
ihn dringend darum und tat zwei Talente Silber in zwei Beutel, legte
zwei Festkleider dazu und ließ sie durch zwei Diener vor ihm hertragen.

<<v24>>
24 Als Gehasi auf der Höhe angekommen war, nahm er ihnen die Geschenke
ab und brachte sie in das Haus. Die Männer schickte er weg und sie
kehrten zurück.

<<v25>>
25 Er selbst ging hinein und trat vor seinen Herrn. Elischa fragte ihn:
Woher kommst du, Gehasi? Er antwortete: Dein Knecht ist nirgendwohin
gegangen.

<<v26>>
26 Da sagte Elischa zu ihm: War nicht mein Geist zugegen, als sich
jemand von seinem Wagen aus dir zuwandte? Ist es denn Zeit, Geld
anzunehmen und Kleider, Ölgärten, Weinberge, Schafe und Rinder, Knechte
und Mägde zu erwerben?

<<v27>>
27 Der Aussatz Naamans aber soll für immer an dir und deinen Nachkommen
haften. Gehasi ging hinaus und war vom Aussatz weiß wie Schnee.\\
\\

* Footnotes

[fn:1] In Damaskus zählte man Elischa zu den Hofpropheten;
daher richtete der König das Schreiben an den König von Israel, der
einen Propheten mit der Heilung beauftragen kann.

[fn:2] Wenn: Text korr.

[fn:3] Der besonderen Beziehung Jahwes zum Land Israel wegen
will er Opfer auf israelitischer Erde darbringen.

[fn:4] wenn er sich dort niederwirft: Text korr. nach G; H:
wenn ich mich dort niederwerfe.
