#+TITLE: 2 Kön 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-19 So 00:01]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Kön 15.html

<<verses>>

<<v1>>
* Asarja (Usija) von Juda: 15,1-7

1 Im siebenundzwanzigsten Jahr Jerobeams, des Königs von Israel, wurde
Asarja, der Sohn Amazjas, König von Juda. [fn:1] [fn:2]

<<v2>>
2 Er war sechzehn Jahre alt, als er König wurde, und regierte
zweiundfünfzig Jahre in Jerusalem. Seine Mutter hieß Jecholja und
stammte aus Jerusalem. [fn:3]

<<v3>>
3 Genau wie sein Vater Amazja tat er, was dem Herrn gefiel.

<<v4>>
4 Nur die Kulthöhen verschwanden nicht; das Volk brachte noch Schlacht-
und Rauchopfer auf ihnen dar.

<<v5>>
5 Doch der Herr schlug den König mit Aussatz. Er musste bis zu seinem
Tod in einem abgesonderten Haus wohnen, während Jotam, der Sohn des
Königs, Vorsteher des Palastes war und die Bürger des Landes regierte. [fn:4]

<<v6>>
6 Die übrige Geschichte Asarjas und alle seine Taten sind aufgezeichnet
in der Chronik der Könige von Juda.

<<v7>>
7 Asarja entschlief zu seinen Vätern; man begrub ihn bei seinen Vätern
in der Davidstadt. Sein Sohn Jotam wurde König an seiner Stelle.\\
\\

<<v8>>
* Secharja von Israel: 15,8-12

8 Im achtunddreißigsten Jahr des Königs Asarja von Juda wurde Secharja,
der Sohn Jerobeams, König von Israel. Er regierte sechs Monate in
Samaria.

<<v9>>
9 Wie seine Väter tat er, was dem Herrn missfiel. Er ließ nicht von den
Sünden ab, zu denen Jerobeam, der Sohn Nebats, Israel verführt hatte.

<<v10>>
10 Gegen ihn zettelte Schallum, der Sohn des Jabesch, eine Verschwörung
an; er erschlug ihn in Jibleam und wurde König an seiner Stelle. [fn:5]

<<v11>>
11 Die übrige Geschichte Secharjas ist aufgezeichnet in der Chronik der
Könige von Israel.

<<v12>>
12 So erfüllte sich das Wort, das der Herr zu Jehu gesprochen hatte:
Nachkommen von dir sollen bis in das vierte Geschlecht auf dem Thron
Israels sitzen. So ist es geschehen. [fn:6]\\
\\

<<v13>>
* Schallum von Israel: 15,13-16

13 Im neununddreißigsten Jahr Usijas, des Königs von Juda, wurde
Schallum, der Sohn des Jabesch, König und regierte einen Monat in
Samaria.

<<v14>>
14 Gegen ihn zog Menahem, der Sohn Gadis, von Tirza heran, kam nach
Samaria, erschlug Schallum, den Sohn des Jabesch, in Samaria und wurde
König an seiner Stelle.

<<v15>>
15 Die übrige Geschichte Schallums und die Verschwörung, die er
angezettelt hat, sind aufgezeichnet in der Chronik der Könige von
Israel.

<<v16>>
16 Damals eroberte Menahem von Tirza aus die Stadt Tifsach und tötete
alle Bewohner der Stadt und ihrer Umgebung, weil sie ihm die Tore nicht
geöffnet hatten. Er eroberte sie und ließ ihren schwangeren Frauen den
Leib aufschlitzen.\\
\\

<<v17>>
* Menahem von Israel: 15,17-22

17 Im neununddreißigsten Jahr Asarjas, des Königs von Juda, wurde
Menahem, der Sohn Gadis, König von Israel. Er regierte zehn Jahre in
Samaria

<<v18>>
18 und tat, was dem Herrn missfiel; er ließ nicht von den Sünden ab, zu
denen Jerobeam, der Sohn Nebats, Israel verführt hatte.

<<v19>>
19 In seinen Tagen kam Pul, der König von Assur, in das Land. Menahem
gab ihm tausend Talente Silber, damit er ihm helfe, seine Herrschaft zu
festigen. [fn:7]

<<v20>>
20 Um das Geld dem König von Assur abliefern zu können, musste er den
wohlhabenden Männern in Israel eine Steuer auferlegen; fünfzig
Silberschekel kamen auf jeden. Daraufhin zog der König von Assur ab und
blieb nicht länger im Land. [fn:8]

<<v21>>
21 Die übrige Geschichte Menahems und alle seine Taten sind
aufgezeichnet in der Chronik der Könige von Israel.

<<v22>>
22 Er entschlief zu seinen Vätern und sein Sohn Pekachja wurde König an
seiner Stelle.\\
\\

<<v23>>
* Pekachja von Israel: 15,23-26

23 Im fünfzigsten Jahr Asarjas, des Königs von Juda, wurde Pekachja, der
Sohn Menahems, König von Israel. Er regierte zwei Jahre in Samaria

<<v24>>
24 und tat, was dem Herrn missfiel; er ließ nicht von den Sünden ab, zu
denen Jerobeam, der Sohn Nebats, Israel verführt hatte.

<<v25>>
25 Gegen ihn zettelte sein Adjutant Pekach, der Sohn Remaljas, eine
Verschwörung an und erschlug ihn im Wohnturm des königlichen Palastes in
Samaria . . . Er hatte fünfzig Mann aus Gilead bei sich, tötete Pekachja
und wurde König an seiner Stelle. [fn:9]

<<v26>>
26 Die übrige Geschichte Pekachjas und alle seine Taten sind
aufgezeichnet in der Chronik der Könige von Israel.\\
\\

<<v27>>
* Pekach von Israel: 15,27-31

27 Im zweiundfünfzigsten Jahr des Königs Asarja von Juda wurde Pekach,
der Sohn Remaljas, König von Israel. Er regierte zwanzig Jahre in
Samaria

<<v28>>
28 und tat, was dem Herrn missfiel; er ließ nicht von den Sünden ab, zu
denen Jerobeam, der Sohn Nebats, Israel verführt hatte.

<<v29>>
29 In den Tagen Pekachs, des Königs von Israel, zog Tiglat-Pileser, der
König von Assur, heran. Er eroberte Ijon, Abel-Bet-Maacha, Janoach,
Kedesch, Hazor, Gilead, Galiläa, das ganze Land Naftali, und
verschleppte ihre Bewohner nach Assur. [fn:10]

<<v30>>
30 Hoschea aber, der Sohn Elas, zettelte eine Verschwörung gegen Pekach,
den Sohn Remaljas, an. Er erschlug ihn und wurde König an seiner Stelle
im zwanzigsten Jahr Jotams, des Sohnes Usijas.

<<v31>>
31 Die übrige Geschichte Pekachs und alle seine Taten sind aufgezeichnet
in der Chronik der Könige von Israel.\\
\\

<<v32>>
* Jotam von Juda: 15,32-38

32 Im zweiten Jahr Pekachs, des Sohnes Remaljas, des Königs von Israel,
wurde Jotam, der Sohn Usijas, König von Juda. [fn:11]

<<v33>>
33 Er war fünfundzwanzig Jahre alt, als er König wurde, und regierte
sechzehn Jahre in Jerusalem. Seine Mutter hieß Jeruscha und war eine
Tochter Zadoks. [fn:12]

<<v34>>
34 Er tat, was dem Herrn gefiel, genau wie sein Vater Usija.

<<v35>>
35 Nur die Kulthöhen verschwanden nicht. Das Volk brachte noch Schlacht-
und Rauchopfer auf ihnen dar. Er baute das obere Tor am Haus des Herrn.

<<v36>>
36 Die übrige Geschichte Jotams und seine Taten sind aufgezeichnet in
der Chronik der Könige von Juda.

<<v37>>
37 In jenen Tagen begann der Herr, Rezin, den König von Aram, und
Pekach, den Sohn Remaljas, gegen Juda ziehen zu lassen.

<<v38>>
38 Jotam aber entschlief zu seinen Vätern und wurde bei seinen Vätern in
der Stadt seines Vaters David begraben. Sein Sohn Ahas wurde König an
seiner Stelle.\\
\\

* Footnotes

[fn:1] (1-7) [[file:2.Chr_26.org::v3][2 Chr 26,3-4]].[[file:2.Chr_26.org::v16][16-23]]

[fn:2] Der Name des Königs ist in beiden Formen überliefert
(vgl. V. 13 und [[file:2.Chr_26.org::v1][2 Chr 26,1]]).

[fn:3] Die Zeit vom 27. Jahr Jerobeams bis zum 2. Jahr Pekachs
(V. 32) umspannt nur 28 Jahre. Die hier genannte Zahl 52 setzt voraus,
dass er schon 24 Jahre vor dem Tod Amazjas als Mitregent oder
Stellvertreter seines Vaters König geworden war.

[fn:4] [[file:2.Chr_26.org::v21][2 Chr 26,21]]

[fn:5] Jibleam: südlich von Jesreel; in H ist der Name entstellt.

[fn:6] [[file:2.Kön_10.org::v30][10,30]]

[fn:7] In seinen Tagen: Text korr. nach G; H: alle seine Tage
(mit dem vorausgehenden Satz verbunden). - Pul ist der babylonische
Thronname des assyrischen Königs Tiglat-Pileser III. (745-727 v. Chr.).
Seine Annalen berichten ausführlich über seine Vasallen und erwähnen
unter ihnen auch Menahem von Samaria.

[fn:8] Von der Steuer wurden auf diese Weise 72000 Bürger betroffen.

[fn:9] H unverständlich.

[fn:10] Die genannten Städte liegen im Norden des Reiches
Israel. Naftali ist der Landstrich westlich des Jordan zwischen dem See
Gennesaret und dem Hule-See. Assyrische Texte berichten ausführlich über
den Feldzug Tiglat-Pilesers.

[fn:11] (32-38) [[file:2.Chr_27.org::v1][2 Chr 27,1-9]]

[fn:12] In den sechzehn Jahren sind zehn Jahre enthalten, in
denen Jotam für seinen erkrankten Vater die Regierungsgeschäfte führte
(V. 5). Auf den Tod Usijas folgten daher nicht sechzehn, sondern nur
sechs Jahre Jotams. Die Nichtbeachtung dieser Tatsache führte zu
Unstimmigkeiten in den Daten Pekachs, Hoscheas und des Ahas, die auch
durch nachträgliche Änderungen nicht beseitigt werden konnten.
