#+TITLE: 2 Makk 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-27 Mo 21:55]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Makk 1.html

<<verses>>

<<v1>>
* Briefe der Juden Jerusalems an die Juden in Ägypten: 1,1 - 2,18

* Der erste Brief zum Tempelweihfest: 1,1-9

1 Wir, eure Brüder, die Juden aus Jerusalem und aus dem Land Judäa,
grüßen euch, unsere Brüder, die Juden, die in Ägypten wohnen, und
wünschen euch Frieden. [fn:1]

<<v2>>
2 Gott möge euch Gutes erweisen und seines Bundes gedenken, den er mit
seinen treuen Dienern Abraham, Isaak und Jakob geschlossen hat.

<<v3>>
3 Er gebe euch allen ein Herz, das euch fähig macht, ihn zu fürchten und
seiner Lehre mutig und bereitwillig zu folgen.

<<v4>>
4 Er öffne euer Herz für sein Gesetz und für die Gebote und schenke euch
Frieden.

<<v5>>
5 Er erhöre eure Gebete, schenke euch Versöhnung und verlasse euch nicht
in der Not.

<<v6>>
6 So beten wir hier für euch.

<<v7>>
7 Unter der Regierung des Demetrius, im Jahr 169, haben wir Juden euch
geschrieben: In der höchsten Not, die in diesen Jahren über uns kam, als
Jason und sein Anhang vom Heiligen Land und vom Königreich abfielen, [fn:2] [fn:3]

<<v8>>
8 verbrannten sie das Tempeltor und vergossen unschuldiges Blut. Wir
aber beteten zum Herrn und er hat uns erhört. So konnten wir wieder
Brand- und Speiseopfer darbringen; wir zündeten die Leuchter an und
legten die Schaubrote aus. [fn:4]

<<v9>>
9 Und nun begeht die Tage des Laubhüttenfestes im Monat Kislew!
Geschrieben im Jahr 188. [fn:5]\\
\\

<<v10>>
* Der zweite Brief zum Tempelweihfest: 1,10 - 2,18

10 Die Bewohner Jerusalems und Judäas, der Hohe Rat und Judas wünschen
dem Aristobul, dem Lehrer des Königs Ptolemäus, aus dem Geschlecht der
gesalbten Priester, und den Juden Ägyptens Glück und Heil.

<<v11>>
11 Wir danken Gott von Herzen, der uns aus großen Gefahren errettet hat.
So sind wir bereit, selbst mit einem König zu streiten.

<<v12>>
12 Gott selbst nämlich hat alle verjagt, die gegen die Heilige Stadt
gekämpft haben. [fn:6]

<<v13>>
13 Denn als der Fürst mit seinem Heer, das als unüberwindlich galt, nach
Persien zog, fanden sie im Tempel der Nanäa den Tod. Die Priester der
Nanäa hatten sie nämlich überlistet. [fn:7]

<<v14>>
14 Unter dem Vorwand, sich mit der Göttin zu vermählen, war Antiochus
mit seinen Freunden, die ihn begleiteten, zum Tempel gekommen; sozusagen
als Mitgift wollte er sich dabei die großen Reichtümer aneignen.

<<v15>>
15 Die Priester der Nanäa legten die Schätze für sie auch bereit und
Antiochus ging mit einigen wenigen Männern in den heiligen Bezirk.
Sobald er aber das Heiligtum betreten hatte, schlossen sie das Tor.

<<v16>>
16 Sie öffneten eine geheime Tür an der Decke, warfen schwere Steine
herab, zerschmetterten den Fürsten (und seine Begleiter), zerstückelten
sie, schnitten ihnen die Köpfe ab und warfen sie hinaus zu denen, die
draußen stehen geblieben waren.

<<v17>>
17 Für all das sei unser Gott gepriesen: Er hat die Sünder dem Untergang
preisgegeben.

<<v18>>
18 Wir wollen nun am fünfundzwanzigsten Kislew die Reinigung des Tempels
feiern. Darum hielten wir es für unsere Pflicht, euch davon zu
benachrichtigen, damit auch ihr sie wie die Tage des Laubhüttenfestes
feiern könnt und wie die Tage des Feuers. (Letztere erinnern an den
Tag,) an dem Nehemia nach dem Aufbau von Tempel und Altar erstmals
wieder Opfer darbrachte.

<<v19>>
19 Denn als unsere Väter nach Persien in die Verbannung geführt wurden,
nahmen die Priester, die fromm geblieben waren, etwas von dem Feuer des
Altars mit und verbargen es heimlich im Schacht eines leeren Brunnens.
Sie versteckten es so, dass die Stelle allen unbekannt blieb. [fn:8]

<<v20>>
20 Darüber vergingen viele Jahre. Doch als es Gott gefiel, sandte der
König von Persien den Nehemia her. Der schickte die Nachkommen jener
Priester aus, um das Feuer holen zu lassen, das ihre Väter einst
versteckt hatten.

<<v21>>
21 Als sie uns erklärten, kein Feuer gefunden zu haben, sondern nur eine
dicke Flüssigkeit, befahl er ihnen, etwas davon zu schöpfen und zu ihm
zu bringen. Das Opfer wurde hergerichtet. Dann ließ Nehemia von den
Priestern das Brennholz, und was darauf lag, mit diesem zähflüssigen
Wasser begießen.

<<v22>>
22 So geschah es. Nach einiger Zeit brach die Sonne hervor, die von
Wolken verdeckt gewesen war. Da flammte ein großes Feuer auf und alle
staunten.

<<v23>>
23 Während das Opfer verbrannte, beteten die Priester und alle Anderen,
die bei ihnen waren; Jonatan stimmte an und die Übrigen, darunter auch
Nehemia, beteten laut mit.

<<v24>>
24 Das Gebet aber lautete so: Herr, o Herr, du Gott und Schöpfer aller
Dinge, furchtbarer, starker, gerechter und barmherziger Gott! Du allein
bist König und du bist gütig.

<<v25>>
25 Du allein gibst alle Gaben. Nur du bist gerecht, allmächtig und ewig.
Du rettest Israel aus aller Not. Du hast unsere Väter erwählt und sie
heilig gemacht.

<<v26>>
26 Nimm dieses Opfer an für dein ganzes Volk Israel! Behüte dein Erbteil
und mach es heilig!

<<v27>>
27 Sammle uns aus der Zerstreuung, befrei alle, die bei den Heiden in
Knechtschaft leben, schau auf die Verachteten und Verabscheuten! Dadurch
sollen die Heiden erkennen, dass du unser Gott bist.

<<v28>>
28 Strafe die stolzen und frechen Unterdrücker!

<<v29>>
29 Pflanz dein Volk an deinem heiligen Ort ein! Denn so hat es Mose
zugesagt. [fn:9]

<<v30>>
30 Die Priester begleiteten die Loblieder, die man sang, mit Musik.

<<v31>>
31 Als das Opfer verbrannt war, ließ Nehemia das übrig gebliebene Wasser
auf große Steine schütten.

<<v32>>
32 Da entzündete sich eine lodernde Flamme. Sie verzehrte sich im Schein
des Feuers, das vom Altar her leuchtete.

<<v33>>
33 Dieses Ereignis wurde überall bekannt und man meldete dem persischen
König, an der Stelle, an der die Priester, die in die Verbannung gingen,
das Feuer versteckt hätten, sei das Wasser zum Vorschein gekommen, das
die Leute des Nehemia dann über das Opfer gossen.

<<v34>>
34 Nachdem der König die Sache geprüft hatte, ließ er den Ort umfrieden
und für heilig erklären.

<<v35>>
35 Auch nahm der König viele kostbare Geschenke und verteilte sie unter
die, denen er wohlgesinnt war.

<<v36>>
36 Die Leute um Nehemia nannten das Wasser Neftar, das heißt: Reinigung.
Bei den meisten aber heißt es Neftai. [fn:10]

* Footnotes

[fn:1] Seit langem gab es jüdische Kolonien in Ägypten. Die am
meisten bekannte in Elefantine geht bis in die Anfänge des 6. Jh. v.
Chr. zurück.

[fn:2] [[file:1.Makk_10.org::v67][1 Makk 10,67]]; [[file:2.Makk_4.org::v7][2 Makk 4,7]]-[[file:2.Makk_4.org::v22][22]]

[fn:3] 7.9: Das Jahr 169 entspricht dem Jahr 143 v. Chr., das
Jahr 188 dem Jahr 124 v. Chr. (vgl. die Anmerkung zu [[file:1.Makk_1.org::v10][1 Makk 1,10]]).

[fn:4] [[file:1.Makk_4.org::v38][1 Makk 4,38]]

[fn:5] Mit dem Laubhüttenfest im Monat Kislew (Dezember) ist in
Wirklichkeit das Tempelweihfest gemeint.

[fn:6] (12f) [[file:2.Makk_9.org::v1][9,1]]-[[file:2.Makk_9.org::v9][29]]

[fn:7] Der Tempel der Nanäa, vergleichbar dem der Artemis von
Ephesus, den Antiochus IV. berauben wollte, befand sich in Elymaïs.

[fn:8] [[file:Lev_6.org::v9][Lev 6,5]]

[fn:9] [[file:Dtn_30.org::v3][Dtn 30,3]]-[[file:Dtn_30.org::v5][5]]

[fn:10] Neftar (= Erdöl): Manche lesen Naftan, andere Nafta.
