#+TITLE: 2 Makk 11 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-28 Di 18:31]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Makk 11.html

<<verses>>

<<v1>>
* Der Sieg des Judas über Lysias: 11,1-12

1 Der Reichsverweser Lysias, des Königs Vormund und Verwandter, war über
diese Ereignisse sehr verärgert. [fn:1]

<<v2>>
2 Er zog daher in kürzester Zeit an die achtzigtausend Mann zusammen,
dazu seine ganze Reiterei, und marschierte gegen die Juden. Er hatte
vor, aus der Stadt Jerusalem eine griechische Siedlung zu machen,

<<v3>>
3 das Heiligtum ebenso wie die heidnischen Kultstätten zu besteuern und
das Amt des Hohenpriesters jedes Jahr für Geld auszuschreiben.

<<v4>>
4 Doch rechnete er überhaupt nicht mit der Macht Gottes, sondern stützte
seine Überlegungen allein auf die Zehntausende von Fußtruppen, die
Tausende von Reitern und seine achtzig Elefanten.

<<v5>>
5 Er drang in Judäa ein, rückte vor die Festung Bet-Zur, die
hundertfünfzig Stadien von Jerusalem entfernt liegt, und bestürmte sie.

<<v6>>
6 Als die Leute des Makkabäers von der Belagerung der Festung erfuhren,
flehten sie mit dem ganzen Volk unter Klagen und Weinen den Herrn an, er
möge doch einen guten Engel schicken, um Israel zu retten. [fn:2]

<<v7>>
7 Der Makkabäer griff als erster nach den Waffen und hielt eine
anfeuernde Rede an die anderen: Sie sollten, zusammen mit ihm, die
Gefahr auf sich nehmen und ihren Brüdern zu Hilfe eilen. Geschlossen und
voll Kampfesmut brachen sie auf.

<<v8>>
8 Sie waren noch in der Nähe von Jerusalem, da erschien ihnen ein Reiter
und zog in einem weißen Gewand und einer blinkenden goldenen
Waffenrüstung vor ihnen her.

<<v9>>
9 Gemeinsam priesen sie den barmherzigen Gott und ihr Mut wurde so groß,
dass sie bereit gewesen wären, nicht nur Menschen, sondern auch die
wildesten Tiere und eiserne Mauern zusammenzuschlagen.

<<v10>>
10 Sie rückten mit ihrem himmlischen Bundesgenossen, zum Kampf bereit,
vor; denn der Herr hatte Erbarmen mit ihnen.

<<v11>>
11 Sie stürzten sich wie Löwen auf die Feinde und erschlugen elftausend
von ihnen, dazu sechzehnhundert Reiter. Alle Übrigen jagten sie in die
Flucht;

<<v12>>
12 die meisten davon waren verwundet und konnten nur das nackte Leben
retten. Auch Lysias selbst konnte sich nur durch eine schimpfliche
Flucht retten.\\
\\

<<v13>>
* Der Friedensschluss des Lysias mit den Juden: 11,13-38

13 Da Lysias jedoch nicht ohne Verstand war und über die erlittene
Niederlage nachdachte, begriff er, dass die Hebräer unbesiegbar waren,
weil der starke Gott auf ihrer Seite kämpfte. [fn:3]

<<v14>>
14 Darum schickte er Unterhändler, die auf einen Friedensvertrag drängen
und jeder annehmbaren Bedingung zustimmen sollten; er ließ sagen, er
wolle auch dem König sehr zureden, mit ihnen Freundschaft zu schließen.

<<v15>>
15 Der Makkabäer ging auf alle Vorschläge des Lysias ein, ohne indes
seinen Vorteil zu vernachlässigen. Alle Forderungen, die er für die
Juden stellte und dem Lysias schriftlich vorlegte, nahm der König an.

<<v16>>
16 Lysias schrieb an die Juden einen Brief, der folgenden Inhalt hatte:
Lysias grüßt das jüdische Volk.

<<v17>>
17 Eure Abgesandten Johanan und Abschalom haben euer Antwortschreiben
vorgelegt, das unten beigefügt ist, und mich gebeten, die darin
geäußerten Forderungen zu genehmigen.

<<v18>>
18 Was in die Zuständigkeit des Königs fällt, habe ich ihm dargelegt; er
ist auf jede annehmbare Bedingung eingegangen.

<<v19>>
19 Wenn ihr weiterhin die Politik der Regierung wohlwollend aufnehmt,
werde ich mich bemühen, euch Vorteile zu verschaffen.

<<v20>>
20 Was die Einzelheiten betrifft, habe ich euren und meinen
Unterhändlern aufgetragen, mit euch zu verhandeln.

<<v21>>
21 Lebt wohl! Im Jahr 148, am Vierundzwanzigsten des Monats Dioskorus. [fn:4]

<<v22>>
22 Im Brief des Königs stand dies: König Antiochus grüßt seinen Bruder
Lysias.

<<v23>>
23 Nachdem unser Vater zu den Göttern hinübergegangen ist, wollen wir,
dass die Untertanen des Reichs ungestört ihren Beschäftigungen nachgehen
können. [fn:5]

<<v24>>
24 Andererseits haben wir erfahren, dass die Juden mit der von meinem
Vater gewünschten Übernahme griechischer Sitten nicht einverstanden
sind, es vielmehr vorziehen, auf ihre eigene Art zu leben, und
verlangen, dass man ihnen wieder gestattet, ihren Gewohnheiten zu
folgen.

<<v25>>
25 Wir beschließen darum, dass auch dieses Volk ungestört bleibt, und
verfügen, dass man ihnen ihr Heiligtum zurückgibt und dass sie ihr Leben
so einrichten können, wie es schon zur Zeit ihrer Vorfahren Brauch war.

<<v26>>
26 Du wirst nun am besten zu ihnen Gesandte schicken und ihnen die Hand
zum Frieden reichen, damit sie die Grundlinien unserer Politik erkennen,
Vertrauen fassen und ihre Angelegenheiten zu ihrer Zufriedenheit regeln
können.

<<v27>>
27 Der Brief des Königs an das Volk lautete so: König Antiochus grüßt
den Rat und alle übrigen Juden.

<<v28>>
28 Wir hoffen, dass es euch gut geht; auch wir erfreuen uns guter
Gesundheit.

<<v29>>
29 Menelaus hat uns wissen lassen, dass ihr nach Hause zu eurer Arbeit
zurückkehren wollt.

<<v30>>
30 Jedem also, der bis zum dreißigsten Tag des Monats Xanthikus
heimkehrt, wird Friede angeboten mit der Zusicherung,

<<v31>>
31 dass die Juden ihre gewohnten Speisevorschriften und Gesetze befolgen
dürfen; keiner von ihnen darf dabei irgendwie belangt werden für
Vergehen, die er in Unkenntnis der Verhältnisse begangen hat.

<<v32>>
32 Ich habe Menelaus zu eurer Beruhigung zu euch geschickt.

<<v33>>
33 Lebt wohl! Im Jahr 148, am Fünfzehnten des Monats Xanthikus.

<<v34>>
34 Auch die Römer schickten ihnen einen Brief; er hatte folgenden
Inhalt: Die römischen Gesandten Quintus Memmius und Titus Manius grüßen
das jüdische Volk.

<<v35>>
35 Auch wir sind einverstanden mit den Bedingungen, die Lysias, der
Verwandte des Königs, mit euch ausgehandelt hat.

<<v36>>
36 Lasst uns die Vorschläge, die er dem König unterbreiten will,
zukommen, sobald ihr sie geprüft habt, damit wir eure Sache vortragen
können, wie es für euch am günstigsten ist; wir sind nämlich auf dem Weg
nach Antiochia.

<<v37>>
37 Teilt uns deswegen auch umgehend durch Boten eure Meinung darüber
mit.

<<v38>>
38 Lebt wohl! Im Jahr 148, am Fünfzehnten des Monats Xanthikus.\\
\\

* Footnotes

[fn:1] (1-12) [[file:1.Makk_4.org::v26][1 Makk 4,26]]-[[file:1.Makk_4.org::v35][35]]

[fn:2] [[file:Ex_23.org::v20][Ex 23,20]]

[fn:3] (13-38) [[file:1.Makk_6.org::v55][1 Makk 6,55]]-[[file:1.Makk_6.org::v63][63]]

[fn:4] Gemeint ist das Frühjahr 164 v. Chr.

[fn:5] Vergöttlichung und kultische Verehrung der Herrscher war
bei den Seleuziden ebenso üblich wie bei den Lagiden in Ägypten.
