#+TITLE: 2 Makk 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-28 Di 18:18]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Makk 9.html

<<verses>>

<<v1>>
* Das Gottesgericht über den heidnischen König: 9,1-29

1 Etwa zur selben Zeit musste Antiochus mit Schimpf und Schande aus
Persien abziehen. [fn:1]

<<v2>>
2 Er war in die Stadt, die man Persepolis nennt, einmarschiert. Bei dem
Versuch, den Tempel auszurauben und eine Besatzung in die Stadt zu
legen, erhob sich die Bevölkerung in Massen und griff zu den Waffen. Die
Truppen wurden geschlagen und Antiochus von den Einwohnern verjagt; er
musste schmählich den Rückzug antreten.

<<v3>>
3 In der Gegend von Ekbatana erhielt er die Nachricht von der Niederlage
Nikanors und der Truppen des Timotheus.

<<v4>>
4 Da geriet er in heftigen Zorn und glaubte, seine Wut über die
unglückliche Flucht an den Juden auslassen zu können. Darum befahl er
dem Wagenlenker, ohne Unterbrechung bis zum Ziel durchzufahren. Aber
schon drohte ihm das Gericht des Himmels; denn in seiner Vermessenheit
sagte er: Sobald ich in Jerusalem bin, mache ich die Stadt zu einem
Friedhof für alle Juden.

<<v5>>
5 Doch der Herr, der alles sieht, Israels Gott, traf ihn, ohne dass es
jemand sehen konnte, mit einem Schlag, für den es keine Heilung gab.
Kaum hatte er zu reden aufgehört, da spürte er in seinen Eingeweiden
quälende Schmerzen, die kein Arzt lindern konnte. [fn:2]

<<v6>>
6 Damit geschah ihm ganz recht, hatte er doch die Eingeweide anderer
durch zahllose ausgefallene Foltern gequält.

<<v7>>
7 Dennoch blieb sein Stolz ungebrochen; die Vermessenheit hatte ihn ganz
und gar in Besitz genommen. Glühende Wut gegen die Juden verzehrte ihn
und er befahl dem Wagenlenker, noch schneller zu fahren. Doch dann
geschah es: In voller Fahrt fiel er aus dem dahinrasenden Wagen und
stürzte so schwer, dass er sich alle Glieder verrenkte.

<<v8>>
8 Eben noch hatte er in maßloser Aufgeblasenheit geglaubt, er könne den
Wogen des Meeres gebieten und die Gipfel der Berge auf einer Waage
wiegen. Nun lag er auf der Erde und man musste ihn auf eine Bahre legen.
So zeigte sich an ihm sichtbar Gottes Macht. [fn:3]

<<v9>>
9 Aus den Augen des Verruchten krochen Würmer; während er noch lebte,
verfaulte sein Fleisch unter Schmerzen und Qualen und der
Verwesungsgeruch, der von ihm ausging, verpestete das ganze Lager. [fn:4] [fn:5]

<<v10>>
10 Kurz zuvor hatte er noch geglaubt, er könne nach den Sternen des
Himmels greifen; jetzt konnte es niemand mehr bei ihm aushalten, so
unerträglich war der Gestank.

<<v11>>
11 Da endlich begann der Gepeinigte, von seinem maßlosen Hochmut
abzulassen und unter Gottes Schlägen zur Einsicht zu kommen; denn seine
Schmerzen wurden immer schlimmer.

<<v12>>
12 Als er seinen Geruch selbst nicht mehr ertragen konnte, sagte er:
Wenn man nur ein sterblicher Mensch ist, soll man sich Gott unterordnen
und nicht überheblich sein. [fn:6]

<<v13>>
13 Der Verbrecher rief sogar den Herrn an, fand aber bei ihm kein
Erbarmen mehr. Er gelobte,

<<v14>>
14 die Heilige Stadt, die er kurzerhand hatte dem Erdboden gleichmachen
und in einen Friedhof umwandeln wollen, in den Rang einer freien Stadt
zu erheben.

<<v15>>
15 Hatte er zuerst beschlossen, die Juden nicht einmal eines Grabes zu
würdigen, sondern sie samt den Säuglingen den Raubvögeln und den wilden
Tieren zum Fraß vorzuwerfen, so wollte er sie nun alle den Bürgern von
Athen gleichstellen.

<<v16>>
16 Er versprach, den heiligen Tempel, den er zuvor geplündert hatte, mit
den schönsten Weihegeschenken auszuschmücken, die heiligen Geräte um ein
Vielfaches zu ersetzen und die nötigen Aufwendungen für die Opfer aus
eigenen Mitteln aufbringen.

<<v17>>
17 Ja, er wollte sogar selbst Jude werden und überall hingehen, wo
Menschen wohnen, um Gottes Macht zu verkünden.

<<v18>>
18 Trotzdem ließen seine Schmerzen nicht nach; denn das gerechte Gericht
Gottes war über ihn gekommen. Da gab er alle Hoffnung auf und schrieb
den Juden einen Brief, der eigentlich eine Bittschrift war. Der Brief
hatte diesen Inhalt:

<<v19>>
19 Seinen guten jüdischen Bürgern wünscht Antiochus, König und
Befehlshaber, viel Freude, Gesundheit und Wohlergehen.

<<v20>>
20 Ich danke Gott sehr, wenn ihr gesund seid und wenn es auch euren
Kindern und eurem Besitz nach Wunsch ergeht. Dafür setze ich meine
Hoffnung auf den Himmel.

<<v21>>
21 Ich erinnere mich in Liebe an die Achtung und freundliche
Hochschätzung, die ihr mir entgegengebracht habt. Bei meiner Rückkehr
aus Persien zog ich mir eine Krankheit zu, die mich sehr belastet. Darum
hielt ich es für nötig, für die öffentliche Sicherheit aller Bürger zu
sorgen.

<<v22>>
22 Nicht dass ich mich schon aufgegeben hätte - ich habe vielmehr gute
Hoffnung, wieder gesund zu werden.

<<v23>>
23 Aber ich dachte daran, dass schon mein Vater jedes Mal einen
Nachfolger bestimmte, wenn er sich mit seinem Heer im Osten aufhielt.

<<v24>>
24 Falls dann etwas Unvorhergesehenes eintrat oder ein Missgeschick
gemeldet wurde, wussten die Bewohner des Reiches, wem die Regierung
übertragen worden war, und sie brauchten sich nicht zu beunruhigen.

<<v25>>
25 Auch sehe ich, wie die Machthaber an den Grenzen unseres Landes,
unsere Nachbarn, nur auf eine günstige Gelegenheit lauern und die
kommende Entwicklung abwarten. Darum habe ich in aller Form meinen Sohn
Antiochus zum Nachfolger bestimmt; ihn habe ich den meisten von euch ja
schon oft anvertraut und empfohlen, wenn ich plötzlich in die östlichen
Provinzen hinaufziehen musste. An ihn habe ich einen Brief geschrieben,
den ich beilege.

<<v26>>
26 Ich bitte euch eindringlich: Denkt daran, wie viel Gutes ich eurer
Gemeinschaft und jedem einzelnen von euch erwiesen habe, und bewahrt mir
und meinem Sohn euer Wohlwollen!

<<v27>>
27 Ich bin überzeugt, dass er meine Politik der Güte und Freundschaft
weiterführen und in gutem Einvernehmen mit euch bleiben wird.

<<v28>>
28 Der Menschenmörder und Gotteslästerer endete also fern seiner Heimat
im Gebirge auf jämmerliche Weise, unter entsetzlichen Schmerzen, ganz
wie er sie anderen zugefügt hatte.

<<v29>>
29 Sein Jugendfreund Philippus ließ den Leichnam überführen; dann begab
er sich nach Ägypten zu Ptolemäus Philometor, weil er dem Sohn des
Antiochus nicht traute.\\
\\

* Footnotes

[fn:1] (1-29) [[file:1.Makk_6.org::v1][1 Makk 6,1]]-[[file:1.Makk_6.org::v16][16]]; [[file:2.Makk_1.org::v11][2 Makk 1,11]]-[[file:2.Makk_1.org::v17][17]]

[fn:2] [[file:~/RoamNotes/notes/Bibel/nt/Apg_12.org::v20][Apg 12,20]]-[[file:2.Makk_1.org::v23][23]]

[fn:3] [[file:Ps_65.org::v7][Ps 65,7f]]; [[file:Jes_40.org::v12][Jes 40,12]]

[fn:4] [[file:~/RoamNotes/notes/Bibel/nt/Apg_12.org::v23][Apg 12,23]]; [[file:Sir_7.org::v17][Sir 7,17]]

[fn:5] Aus den Augen, andere Lesart: Aus dem Leib.

[fn:6] nicht überheblich sein, andere Lesart: nicht wie Gott
sein wollen.
