#+TITLE: 2 Makk 10 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-28 Di 18:22]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Makk 10.html

<<verses>>

<<v1>>
* Die Reinigung des entweihten Tempels: 10,1-8

1 Der Makkabäer aber und seine Leute konnten unter der Führung des Herrn
das Heiligtum und die Stadt wieder in Besitz nehmen. [fn:1] [fn:2]

<<v2>>
2 Sie rissen die Altäre ein, die die Heiden auf dem Tempelplatz
errichtet hatten, und legten die Umfriedungsmauern nieder.

<<v3>>
3 Den Tempel selbst reinigten sie und bauten einen neuen
Brandopferaltar. Sie schlugen Feuer aus Steinen und zündeten so die
Opfer an, die sie nach zweijähriger Unterbrechung wieder darbringen
konnten. Auch bemühten sie sich um Räucherwerk, Leuchter und Schaubrote.

<<v4>>
4 Dann warfen sie sich auf die Erde nieder und flehten zum Herrn, dass
sie nie wieder in solches Unglück gerieten. Für den Fall, dass sie noch
einmal sündigen sollten, wollten sie lieber von ihm selbst in Güte
gezüchtigt werden als in die Hände frecher und barbarischer Heiden
fallen. [fn:3]

<<v5>>
5 Es traf sich, dass die Reinigung des Tempels auf den gleichen Tag
fiel, an dem ihn die Fremden entweiht hatten, nämlich auf den
fünfundzwanzigsten Kislew.

<<v6>>
6 Sie feierten acht Tage lang ein fröhliches Fest nach Art des
Laubhüttenfestes; dabei dachten sie daran, dass sie noch vor kurzem das
Laubhüttenfest wie wilde Tiere in den Höhlen der Berge verbracht hatten. [fn:4]

<<v7>>
7 Sie nahmen Stäbe, die sie mit grünen Blättern umwunden hatten, in die
Hand und Laubzweige - auch Palmzweige - und brachten dem Loblieder dar,
der den Weg zur Reinigung des Ortes bereitet hatte, der sein Eigentum
ist.

<<v8>>
8 Sie setzten durch eine öffentliche Entschließung und Abstimmung fest,
dass das ganze jüdische Volk jedes Jahr diese Tage festlich zu begehen
habe.\\
\\

<<v9>>
* Die Ereignisse unter Antiochus Eupator: 10,9 - 13,26

* Der Regierungsantritt des Antiochus Eupator: 10,9-13

9 So starb Antiochus, den man Epiphanes nannte.

<<v10>>
10 Jetzt wollen wir noch berichten, was unter Antiochus Eupator geschah,
dem Sohn dieses ruchlosen Menschen. Dabei fassen wir kurz zusammen,
welches Unheil aus den kriegerischen Verwicklungen entstand.

<<v11>>
11 Als Eupator seine Herrschaft antrat, ernannte er einen Mann namens
Lysias zum Reichsverweser; außerdem machte er ihn zum Befehlshaber über
Zölesyrien und Phönizien und zum Oberkommandierenden über die dort
liegenden Truppen. [fn:5]

<<v12>>
12 Ptolemäus, mit dem Zunamen Makron, hatte als erster den Juden
Gerechtigkeit widerfahren lassen, weil ihnen so viel Unrecht geschehen
war; er hatte versucht, den Streit mit ihnen friedlich beizulegen. [fn:6]

<<v13>>
13 Seine Vertrauten verklagten ihn deswegen bei Eupator. Schon vorher
hatte er allerorten als Verräter gegolten; denn er hatte Zypern, das ihm
von Philometor anvertraut worden war, verlassen und war zu Antiochus
Epiphanes übergelaufen. Da er seine ehrenvolle Stellung nicht mehr in
Ehren verwalten konnte, machte er seinem Leben durch Gift ein Ende.\\
\\

<<v14>>
* Die Kämpfe mit den Idumäern und mit Timotheus: 10,14-38

14 Gorgias wurde Befehlshaber in dieser Gegend; er warb Söldner an und
führte Krieg gegen die Juden, wo er nur konnte. [fn:7]

<<v15>>
15 Außer ihm machten auch die Idumäer, die eine Reihe gut gelegener
Festungen besaßen, den Juden zu schaffen. Sie hatten Flüchtlinge aus
Jerusalem bei sich aufgenommen und begannen, Krieg zu führen. [fn:8]

<<v16>>
16 Die Männer um den Makkabäer hielten einen Bittgottesdienst ab und
baten Gott, ihr Bundesgenosse zu sein. Dann berannten sie die Festungen
der Idumäer.

<<v17>>
17 Sie eroberten sie im Sturm, schlugen die Verteidiger auf den Mauern
in die Flucht und machten jeden nieder, der ihnen in die Hände fiel.
Dabei töteten sie mindestens zwanzigtausend Mann.

<<v18>>
18 Nicht weniger als neuntausend Mann konnten sich in zwei stark
befestigte Burgen flüchten, die für eine Belagerung mit allem aufs Beste
ausgerüstet waren. [fn:9]

<<v19>>
19 Der Makkabäer zog ab, da seine Anwesenheit an einem anderen Ort
dringend notwendig war. Doch ließ er Simeon und Josef zurück, ferner
Zachäus mit seinen Leuten; sie reichten aus, um die Burgen zu belagern.

<<v20>>
20 Simeons Soldaten nahmen jedoch aus Habgier Bestechungsgelder an und
ließen für siebzigtausend Drachmen einige Leute aus den Burgen
entweichen.

<<v21>>
21 Sobald der Makkabäer davon erfuhr, rief er die Führer des Volkes
zusammen und erhob Anklage: Man habe die Brüder um Geld verkauft, da man
zu deren Schaden die Feinde freigelassen habe.

<<v22>>
22 Er ließ die Verräter hinrichten und eroberte die beiden Burgen auf
der Stelle.

<<v23>>
23 Mit seinen Waffen hatte er überall Erfolg und so vernichtete er in
den beiden Festungen über zwanzigtausend Mann.

<<v24>>
24 Timotheus - derselbe, den die Juden schon einmal geschlagen hatten
sammelte ein großes Söldnerheer und brachte auch ziemlich viel Reiterei
aus der Provinz Asien zusammen. Damit rückte er an, um Judäa zu erobern. [fn:10]

<<v25>>
25 Als er schon in der Nähe war, riefen die Männer des Makkabäers Gott
um Hilfe an, streuten sich Erde auf das Haupt und zogen Bußgewänder an.

<<v26>>
26 Sie warfen sich vor den Stufen des Brandopferaltars nieder und baten
den, der ihnen wieder gnädig war, ihren Feinden feindlich gesinnt zu
sein und ihren Widersachern zu widerstehen, wie das Gesetz sagt. [fn:11]

<<v27>>
27 Nach diesem Gebet nahmen sie ihre Waffen, verließen die Stadt und
rückten Timotheus entgegen. Als sie sich den Feinden näherten, hielten
sie sich zunächst zurück.

<<v28>>
28 Sobald aber die Sonne aufging und es hell wurde, stießen die beiden
Heere aufeinander. Die einen hatten als Bürgschaft für einen glücklichen
Sieg neben ihrer Tapferkeit nur ihr Gottvertrauen; die anderen ließen
sich im Kampf durch ihre wilde Wut treiben.

<<v29>>
29 Schon war die Schlacht heftig entbrannt, da erschienen den Kämpfenden
vom Himmel her fünf herrliche Reiter auf goldgezäumten Pferden und
stellten sich an die Spitze der Juden.

<<v30>>
30 Zwei von ihnen nahmen den Makkabäer in ihre Mitte, deckten ihn mit
ihren Rüstungen und schützten ihn vor jeder Verwundung; auf die Feinde
aber schossen sie Pfeile und Blitze. Diese wurden geblendet und flohen
verwirrt nach allen Seiten.

<<v31>>
31 So kamen zwanzigtausendfünfhundert Mann und sechshundert Reiter um.

<<v32>>
32 Timotheus selbst flüchtete sich mit anderen in eine Festung namens
Geser, die sehr stark befestigt war; ihr Kommandant war Chäreas.

<<v33>>
33 Die Truppen des Makkabäers belagerten vier Tage lang voll
Begeisterung die Festung.

<<v34>>
34 Die Verteidiger, die sich in ihren Befestigungen sicher fühlten,
führten lästerliche Reden und schrien freche Worte herunter.

<<v35>>
35 Am Morgen des fünften Tages packte zwanzig junge Männer aus dem Heer
des Makkabäers der Zorn, als sie die Lästerreden hörten. Sie stürmten
mutig auf die Mauer los und schlugen in wilder Wut jeden nieder, der
sich ihnen in den Weg stellte.

<<v36>>
36 Andere umgingen die Stadt und erzwangen sich mit demselben Mut den
Zugang zu den Verteidigern; sie legten Feuer an die Türme und steckten
sie in Brand und verbrannten so die Lästerer bei lebendigem Leib. Wieder
andere brachen die Tore auf, ließen die übrigen Truppen ein und
eroberten die Stadt im Handstreich.

<<v37>>
37 Timotheus, der sich in einer Zisterne versteckt hatte, stachen sie
nieder, ebenso seinen Bruder Chäreas und den Apollophanes.

<<v38>>
38 Darauf priesen sie mit Lob- und Dankliedern den Herrn, der so Großes
für Israel getan und ihnen den Sieg geschenkt hatte.\\
\\

* Footnotes

[fn:1] (1-8) [[file:1.Makk_4.org::v36][1 Makk 4,36]]-[[file:1.Makk_4.org::v61][61]]

[fn:2] 1-8: Im Herbst 164 v. Chr. starb Antiochus; im Dezember
des gleichen Jahres wurde der Tempel gereinigt.

[fn:3] [[file:2.Sam_24.org::v14][2 Sam 24,14]]; [[file:1.Chr_21.org::v13][1 Chr 21,13]]

[fn:4] [[file:2.Makk_5.org::v27][5,27]]

[fn:5] [[file:1.Makk_3.org::v32][1 Makk 3,32f]]; [[file:1.Makk_6.org::v17][6,17]]

[fn:6] [[file:2.Makk_4.org::v45][4,45]]

[fn:7] [[file:1.Makk_3.org::v38][1 Makk 3,38]]

[fn:8] [[file:1.Makk_5.org::v3][1 Makk 5,3]]

[fn:9] [[file:1.Makk_5.org::v4][1 Makk 5,4f]]

[fn:10] [[file:1.Makk_5.org::v6][1 Makk 5,6f]]; [[file:2.Makk_8.org::v30][2 Makk 8,30]]; [[file:2.Makk_12.org::v10][12,10]].[[file:2.Makk_12.org::v21][21]]-[[file:2.Makk_12.org::v25][25]]

[fn:11] [[file:Ex_23.org::v22][Ex 23,22]]
