#+TITLE: 2 Makk 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-27 Mo 22:16]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Makk 3.html

<<verses>>

<<v1>>
* Jerusalem unter Gottes Schutz: 3,1-40

* Die Heilige Stadt: 3,1-3

1 Die Bewohner der Heiligen Stadt lebten in tiefem Frieden und hielten
die Gesetze aufs treueste; denn der Hohepriester Onias war ein frommer
Mann und hasste alles Böse. [fn:1]

<<v2>>
2 Darum ehrten sogar die Könige den Ort und schmückten das Heiligtum mit
den kostbarsten Weihegaben.

<<v3>>
3 So bestritt Seleukus, der König Asiens, aus seinen eigenen Einkünften
alle Kosten, die durch den Opferdienst entstanden. [fn:2]\\
\\

<<v4>>
* Der Verrat Simeons am Tempel: 3,4-7

4 Ein gewisser Simeon aus dem Stamm Benjamin war als Tempelvorsteher
eingesetzt worden. Er entzweite sich jedoch mit dem Hohenpriester wegen
der Marktordnung in der Stadt.

<<v5>>
5 Weil er sich gegen Onias nicht durchsetzen konnte, ging er zu
Apollonius, dem Sohn des Tharseas, der damals Befehlshaber in Zölesyrien
und Phönizien war.

<<v6>>
6 Er erzählte ihm, der Tempelschatz in Jerusalem sei voll von
unvorstellbaren Reichtümern; unzählbar sei die Menge des Geldes. Sie
stehe in keinem Verhältnis zu dem, was man für die Opfer aufwenden
müsse, und lasse sich leicht für den König beschlagnahmen.

<<v7>>
7 Als Apollonius mit dem König zusammentraf, berichtete er, was man ihm
über die Gelder hinterbracht hatte. Der aber bestimmte seinen Kanzler
Heliodor und schickte ihn auf den Weg mit dem Auftrag, sich die
erwähnten Gelder ausliefern zu lassen.\\
\\

<<v8>>
* Der Anschlag auf den Tempelschatz: 3,8-14a

8 Heliodor machte sich sofort auf die Reise, angeblich um die Städte in
Zölesyrien und Phönizien zu besuchen, in Wirklichkeit jedoch, um das
Vorhaben des Königs auszuführen.

<<v9>>
9 Als er nach Jerusalem kam, wurde er vom Hohenpriester der Stadt
freundlich empfangen. Da gab er bekannt, welche Anzeige gemacht worden
sei, und teilte den wahren Grund seiner Anwesenheit mit. Er fragte, ob
sich die Sache wirklich so verhalte.

<<v10>>
10 Der Hohepriester erklärte ihm, es handele sich um hinterlegtes Gut
von Witwen und Waisen;

<<v11>>
11 ein Teil gehöre auch Hyrkanus, dem Sohn des Tobija, einem sehr
einflussreichen Mann. - So hatte der ruchlose Simeon gelogen. - Alles
zusammen belaufe sich nur auf vierhundert Talente Silber und zweihundert
Talente Gold.

<<v12>>
12 Man dürfe aber doch denen nicht Unrecht tun, die ihr Vertrauen auf
die Heiligkeit des Ortes und auf die Würde und Unantastbarkeit des
weltberühmten Heiligtums gesetzt hätten.

<<v13>>
13 Heliodor berief sich jedoch auf die Befehle, die er vom König
erhalten hatte, und bestand darauf, alles für die königliche
Schatzkammer zu beschlagnahmen.

<<v14>>
14 Am festgesetzten Tag schickte er sich an hineinzugehen, um eine
Untersuchung der Schätze anzustellen.\\
\\

<<v15>>
* Der Bittgottesdienst um die Rettung des Tempels: 3,14b-22

15 Da geriet die ganze Stadt in nicht geringe Bestürzung. Die Priester
warfen sich in ihren heiligen Gewändern vor dem Altar nieder und riefen
den Himmel an: Er habe die Hinterlegung von Geld durch Gesetze geordnet;
so solle er es jetzt denen, die es hinterlegt hatten, unversehrt
bewahren.

<<v16>>
16 Wer aber die Gestalt des Hohenpriesters sah, dem blutete das Herz.
Wie er aussah und wie sein Gesicht sich verfärbt hatte, verriet seine
innere Qual.

<<v17>>
17 Furcht und Zittern nämlich hatten den Mann befallen und er bebte am
ganzen Leib. Allen, die ihn sahen, wurde der Schmerz seines Herzens
offenbar.

<<v18>>
18 Die Leute stürzten in Scharen aus den Häusern heraus zum öffentlichen
Gebet; denn dem Tempel drohte Schande.

<<v19>>
19 Die Frauen zogen Trauerkleider an, die die Brüste freiließen, und
drängten sich auf die Straßen. Von den jungen Mädchen aber, die man
sonst eingeschlossen hielt, liefen die einen an die Türen, die andern
auf die Mauern; einige beugten sich aus den Fenstern heraus.

<<v20>>
20 Sie alle streckten die Hände zum Himmel empor und beteten
flehentlich.

<<v21>>
21 Es war zum Erbarmen, wie die Menge sich in heillosem Durcheinander zu
Boden warf und wie der Hohepriester sich in seinem Kummer so schrecklich
ängstigte.

<<v22>>
22 So riefen sie zum Herrn, dem Allherrscher, er möge das anvertraute
Gut denen, die es hinterlegt hatten, unversehrt und ganz sicher
bewahren.\\
\\

<<v23>>
* Die Bestrafung des Tempelräubers: 3,23-30

23 Heliodor jedoch machte sich daran, seinen Entschluss auszuführen.

<<v24>>
24 Schon stand er mit der Leibwache an der Schatzkammer. Da ließ der
Herr der Geister und aller Macht eine gewaltige Erscheinung sichtbar
werden. Alle, die ihn frech begleitet hatten, erschraken vor Gottes
Macht; ihre Kräfte verließen sie und sie bekamen große Angst.

<<v25>>
25 Denn es erschien ihnen ein Pferd mit einem schrecklichen Reiter
darauf; das Pferd war mit prächtigem Geschirr geschmückt. Es stürmte
wild auf Heliodor ein und traf ihn heftig mit den Vorderhufen. Sein
Reiter aber trug eine goldene Rüstung.

<<v26>>
26 Noch zwei andere junge Männer erschienen, voll gewaltiger Kraft, in
strahlender Schönheit und herrlich gekleidet. Sie traten auf Heliodor zu
und peitschten von beiden Seiten auf ihn ein; pausenlos schlugen sie ihn
mit vielen Hieben.

<<v27>>
27 Da stürzte er zu Boden und es wurde ihm schwarz vor den Augen. Man
hob ihn schnell auf und legte ihn auf eine Bahre.

<<v28>>
28 Eben noch war er mit großem Gefolge und der ganzen Leibwache zu der
genannten Schatzkammer gekommen; nun trug man ihn hilflos hinaus.
Deutlich hatte man die Herrschermacht Gottes erkannt.

<<v29>>
29 So lag er da, durch Gottes Macht gestürzt, der Sprache beraubt, ohne
jede Hoffnung auf Rettung.

<<v30>>
30 Die Juden aber priesen den Herrn, der an seinem Ort so herrlich seine
Macht gezeigt hatte; und das Heiligtum, das eben noch voll war von Angst
und Verwirrung, war erfüllt von Freude und Jubel; denn der allmächtige
Herr hatte sich offenbart.\\
\\

<<v31>>
* Die Bekehrung des Tempelräubers: 3,31-40

31 Sehr bald kamen ein paar Vertraute Heliodors zu Onias und baten ihn,
er möge doch den Höchsten anrufen und so dem das Leben schenken, der in
den letzten Zügen lag.

<<v32>>
32 Aus Sorge, der König könne der Meinung verfallen, Heliodor sei einem
hinterhältigen Anschlag der Juden zum Opfer gefallen, brachte der
Hohepriester ein Opfer dar, damit der Mann wieder gesund würde.

<<v33>>
33 Während der Hohepriester noch mit dem Versöhnungsopfer beschäftigt
war, erschienen dem Heliodor dieselben jungen Männer wie zuvor, in der
gleichen Kleidung. Sie traten zu ihm und sagten: Danke dem Hohenpriester
Onias vielmals; denn seinetwegen schenkt der Herr dir gnädig das Leben.

<<v34>>
34 Der Himmel hat dich gezüchtigt. Nun verkünde du allen die gewaltige
Kraft Gottes! Nach diesen Worten entschwanden sie.

<<v35>>
35 Da ließ Heliodor dem Herrn ein Opfer darbringen und machte ihm große
Gelübde, weil er ihn am Leben gelassen hatte. Er nahm Abschied von Onias
und zog mit seinen Truppen zum König zurück.

<<v36>>
36 Vor allen Menschen bezeugte er die Taten des größten Gottes, die er
mit eigenen Augen gesehen hatte.

<<v37>>
37 Als der König ihn fragte, wer geeignet sei, noch einmal nach
Jerusalem geschickt zu werden, gab er zur Antwort:

<<v38>>
38 Wenn du einen Feind oder einen Hochverräter weißt, dann schick ihn
dorthin! Du kannst sicher sein, dass er geprügelt zurückkommt, wenn er
überhaupt am Leben bleibt; denn an jenem Ort wirkt wahrhaftig eine
göttliche Kraft.

<<v39>>
39 Er, der im Himmel wohnt, ist selbst der Wächter und Schützer jenes
Ortes; und wer in böser Absicht dorthin kommt, den schlägt er nieder.

<<v40>>
40 Das waren die Ereignisse um Heliodor und um die Rettung des
Tempels.\\
\\

* Footnotes

[fn:1] Onias III. ist der Sohn Simeons III., der in Sir 50,1-21
gepriesen wird.

[fn:2] «Asien» ist hier Bezeichnung für den Vorderen Orient.
