#+TITLE: 2 Sam 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-11 Sa 17:52]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Sam 9.html

<<verses>>

<<v1>>
* Jonatans Sohn: 9,1-13

1 David sagte: Gibt es noch jemand, der vom Haus Saul übrig geblieben
ist? Ich will ihm um Jonatans willen eine Huld erweisen.

<<v2>>
2 Zum Haus Sauls gehörte ein Knecht namens Ziba; man rief ihn zu David
und der König fragte ihn: Bist du Ziba? Er antwortete: Ja, dein Knecht. [fn:1]

<<v3>>
3 Der König fragte ihn: Ist vom Haus Sauls niemand mehr am Leben, dass
ich ihm göttliche Huld erweisen könnte? Ziba antwortete dem König: Es
gibt einen Sohn Jonatans, der an beiden Füßen gelähmt ist. [fn:2]

<<v4>>
4 Der König sagte zu ihm: Wo ist er? Ziba antwortete dem König: Er lebt
jetzt im Haus Machirs, des Sohnes Ammiëls, in Lo-Dabar. [fn:3]

<<v5>>
5 Da schickte der König David hin und ließ ihn aus dem Haus Machirs, des
Sohnes Ammiëls, in Lo-Dabar holen. [fn:4]

<<v6>>
6 Als Merib-Baal, der Sohn Jonatans, des Sohnes Sauls, zu David kam,
warf er sich (vor ihm) auf sein Gesicht nieder und huldigte ihm. David
sagte: Merib-Baal! Er antwortete: Hier ist dein Knecht. [fn:5]

<<v7>>
7 David sagte zu ihm: Fürchte dich nicht; denn ich will dir um deines
Vaters Jonatan willen eine Huld erweisen: Ich gebe dir alle Felder
deines Großvaters Saul zurück und du sollst immer an meinem Tisch essen. [fn:6]

<<v8>>
8 Da warf sich Merib-Baal (vor ihm) nieder und sagte: Was ist dein
Knecht, dass du dich einem toten Hund zuwendest, wie ich es bin?

<<v9>>
9 Der König David rief Ziba, den Diener Sauls, und sagte zu ihm: Alles,
was Saul und seiner ganzen Familie gehört hat, gebe ich dem Sohn deines
Herrn. [fn:7]

<<v10>>
10 Du sollst mit deinen Söhnen und Knechten für ihn das Land bebauen und
ihm den Ertrag bringen, damit der Sohn deines Herrn zu essen hat.
Merib-Baal selbst aber, der Sohn deines Herrn, soll immer an meinem
Tisch essen. Ziba hatte fünfzehn Söhne und zwanzig Knechte.

<<v11>>
11 Ziba sagte zum König: Genauso, wie es mein Herr, der König, seinem
Knecht befohlen hat, wird es dein Knecht tun. Und Merib-Baal aß am Tisch
Davids wie einer von den Söhnen des Königs.

<<v12>>
12 Merib-Baal hatte einen kleinen Sohn namens Micha und alle, die im
Haus Zibas wohnten, waren Merib-Baals Knechte.

<<v13>>
13 Merib-Baal blieb also in Jerusalem; denn er aß immer am Tisch des
Königs; er war aber an beiden Füßen gelähmt.\\
\\

* Footnotes

[fn:1] [[file:2.Sam_16.org::v1][16,1]]

[fn:2] [[file:2.Sam_4.org::v4][4,4]]

[fn:3] Lo-Dabar: im Ostjordanland.

[fn:4] [[file:2.Sam_17.org::v27][17,27]]

[fn:5] [[file:2.Sam_19.org::v25][19,25]]

[fn:6] [[file:2.Sam_19.org::v29][19,29]]

[fn:7] (9-11) [[file:2.Sam_19.org::v29][19,29f]]
