#+TITLE: 2 Sam 23 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-11 Sa 23:24]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Sam 23.html

<<verses>>

<<v1>>
* Davids letzte Worte: 23,1-7

1 Das sind die letzten Worte Davids: Spruch Davids, des Sohnes Isais,
/\\
 Spruch des hochgestellten Mannes, /\\
 des Gesalbten des Gottes Jakobs, /\\
 des Lieblingshelden der Lieder Israels:\\
\\

<<v2>>
2 Der Geist des Herrn sprach durch mich, /\\
 sein Wort war auf meiner Zunge. [fn:1]\\
\\

<<v3>>
3 Der Gott Israels sprach, /\\
 zu mir sagte der Fels Israels: /\\
 Wer gerecht über die Menschen herrscht, /\\
 wer voll Gottesfurcht herrscht,\\
\\

<<v4>>
4 der ist wie das Licht am Morgen, /\\
 wenn die Sonne aufstrahlt /\\
 an einem Morgen ohne Wolken, /\\
 der nach dem Regen grünes Gras /\\
 aus der Erde hervorsprießen lässt. [fn:2]\\
\\

<<v5>>
5 Ist nicht mein Haus durch Gott gesichert? /\\
 Weil er mir einen ewigen Bund gewährt hat, ist es in allem wohlgeordnet
und gut gesichert. /\\
 All mein Heil und alles, was ich begehrte, /\\
 ließ er es nicht aufsprießen? [fn:3]\\
\\

<<v6>>
6 All die Übeltäter aber sind wie verwehte Dornen; /\\
 man fasst sie nicht mit der Hand an.\\
\\

<<v7>>
7 Wenn jemand sie anrühren will, /\\
 rüstet er sich mit Eisen und einer Lanze; /\\
 sie werden im Feuer verbrannt. [fn:4]\\
\\

<<v8>>
* Davids Helden: 23,8-39

8 Das sind die Namen der Helden Davids: Jischbaal, der Hachmoniter, das
Haupt der Drei; er schwang seine Streitaxt über achthundert Männer und
erschlug sie alle auf einmal. [fn:5] [fn:6]

<<v9>>
9 Nach ihm kommt (als Zweiter) der Ahoachiter Eleasar, der Sohn Dodos,
unter den drei Helden. Er war bei David in Pas-Dammim, als die Philister
sich zum Kampf sammelten. Als sich die Israeliten zurückzogen, [fn:7]

<<v10>>
10 hielt er (allein) stand und schlug auf die Philister ein, bis seine
Hand erlahmte und am Schwert erstarrte. So verschaffte der Herr an jenem
Tag (Israel) einen großen Sieg. Das Volk kehrte wieder um und folgte
Eleasar, aber nur noch, um zu plündern.

<<v11>>
11 Nach ihm kommt (als dritter) der Harariter Schamma, der Sohn Ages.
Einst versammelten sich die Philister bei Lehi. Dort war ein Linsenfeld.
Als das Volk vor den Philistern floh, [fn:8]

<<v12>>
12 stellte sich Schamma mitten in das Feld, behauptete es und schlug die
Philister. So verlieh ihm der Herr einen großen Sieg.

<<v13>>
13 Als sich einst das Lager der Philister in der Rafaïterebene befand,
kamen drei von den Dreißig zu Beginn der Ernte hinab zur Höhle Adullam.

<<v14>>
14 David hielt sich damals in der Bergfestung auf und ein Posten der
Philister lag in Betlehem.

<<v15>>
15 Da bekam David großen Durst und er sagte: Wer bringt mir Wasser aus
der Zisterne am Tor von Betlehem? [fn:9]

<<v16>>
16 Da drangen die drei Helden in das Lager der Philister ein, schöpften
Wasser aus der Zisterne am Tor von Betlehem, nahmen es mit und brachten
es David. Doch er wollte es nicht trinken, sondern goss es für den Herrn
als Trankopfer aus

<<v17>>
17 und sagte: Das sei fern von mir, Herr, dass ich so etwas tue. Ist es
nicht sozusagen das Blut der Männer, die unter Lebensgefahr hingegangen
sind? Darum wollte er es nicht trinken. Eine solche Tat vollbrachten die
drei Helden.

<<v18>>
18 Joabs Bruder Abischai, der Sohn der Zeruja, war der Anführer der
Dreißig. Er schwang seinen Speer über dreihundert Männer und erschlug
sie; bei den drei Helden hatte er einen großen Namen.

<<v19>>
19 Unter den Dreißig war er hoch geehrt und er wurde ihr Anführer, aber
an die Drei reichte er nicht heran. [fn:10]

<<v20>>
20 Benaja aus Kabzeel, der Sohn Jojadas, war ein tapferer Mann, der
große Taten vollbrachte. Er erschlug die beiden Söhne Ariëls aus Moab.
Als einmal Schnee gefallen war, kam er zu einer Zisterne und erlegte
darin einen Löwen. [fn:11]

<<v21>>
21 Auch erschlug er einen Ägypter, einen Furcht erregenden Mann. Der
Ägypter hatte einen Speer in der Hand. Benaja aber ging nur mit einem
Stock auf ihn los, riss ihm den Speer aus der Hand und tötete ihn mit
diesem Speer.

<<v22>>
22 Solche Taten vollbrachte Benaja, der Sohn Jojadas. Er hatte bei den
drei Helden einen großen Namen.

<<v23>>
23 Unter den Dreißig war er hoch geehrt, aber an die Drei reichte er
nicht heran. David stellte ihn an die Spitze seiner Leibwache.

<<v24>>
24 Zu den Dreißig gehörte Joabs Bruder Asaël, ferner Elhanan aus
Betlehem, der Sohn Dodos,

<<v25>>
25 Schamma und Elika aus Harod,

<<v26>>
26 Helez aus Pelet, Ira aus Tekoa, der Sohn des Ikkesch,

<<v27>>
27 Abiëser aus Anatot, Sibbechai aus Huscha, [fn:12]

<<v28>>
28 Zalmon, der Ahoachiter, Machrai aus Netofa,

<<v29>>
29 Heled aus Netofa, der Sohn Baanas, Ittai aus Gibea in Benjamin, der
Sohn Ribais,

<<v30>>
30 Benaja aus Piraton, Hiddai aus Nahale-Gaasch,

<<v31>>
31 Abialbon aus Bet-Araba, Asmawet aus Bahurim,

<<v32>>
32 Eljachba aus Schaalbon, Jaschen aus Nun, [fn:13]

<<v33>>
33 Schamma aus Harar, Ahiam aus Harar, der Sohn Scharars,

<<v34>>
34 Elifelet aus Maacha, der Sohn Ahasbais, Eliam aus Gilo, der Sohn
Ahitofels,

<<v35>>
35 Hezro aus Karmel, Paarai aus Arab,

<<v36>>
36 Jigal aus Zoba, der Sohn Natans, Mibhar aus Gad,

<<v37>>
37 Zelek, der Ammoniter, Nachrai aus Beerot, der Waffenträger Joabs, des
Sohnes der Zeruja,

<<v38>>
38 Ira aus Jattir, Gareb aus Jattir [fn:14]

<<v39>>
39 sowie Urija, der Hetiter. Im Ganzen (waren es) siebenunddreißig.\\
\\

* Footnotes

[fn:1] 2-7: Davids «letzte Worte» (V. 1) sind keine
Abschiedsrede, sondern ein Danklied für die Wohltaten Gottes (V. 5),
eingerahmt von einer Weisung für den König (VV. 3f.6f).

[fn:2] hervorsprießen lässt: Text korr.

[fn:3] gesichert: Text korr.

[fn:4] H liest am Ende des Verses noch ein Wort, das wohl aus
dem folgenden Vers hierher geraten ist.

[fn:5] (8-39) [[file:1.Chr_11.org::v10][1 Chr 11,10-47]]

[fn:6] Text korr., vgl. G und [[file:1.Chr_11.org::v11][1 Chr 11,11]].

[fn:7] Pas-Dammim: Text korr., vgl. [[file:1.Chr_11.org::v13][1 Chr 11,13]].

[fn:8] bei Lehi: Text korr.

[fn:9] Da bekam David großen Durst, wörtlich: Da hatte David ein Verlangen.

[fn:10] Unter den Dreißig: Text korr.; H: Unter den Drei.

[fn:11] Söhne: eingefügt nach G.

[fn:12] Sibbechai: Text korr., vgl. G-Handschriften und [[file:1.Chr_11.org::v29][1 Chr 11,29]].

[fn:13] Jaschen aus Nun: Text korr., vgl. [[file:1.Chr_11.org::v34][1 Chr 11,34]] in G-Handschriften.

[fn:14] aus Jattir: Text korr. vgl. G-Handschriften.
