#+TITLE: 2 Sam 24 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-11 Sa 23:31]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Sam 24.html

<<verses>>

<<v1>>
* Davids Volkszählung: 24,1-25

1 Der Zorn des Herrn entbrannte noch einmal gegen Israel und er reizte
David gegen das Volk auf und sagte: Geh, zähl Israel und Juda! [fn:1] [fn:2]

<<v2>>
2 Der König befahl Joab, dem Obersten des Heeres, der bei ihm war:
Durchstreift alle Stämme Israels von Dan bis Beerscheba, und mustert das
Volk, damit ich weiß, wie viele es sind. [fn:3]

<<v3>>
3 Joab aber sagte zum König: Der Herr, dein Gott, möge das Volk
vermehren, hundertmal mehr, als es jetzt ist, und mein Herr, der König,
möge es mit eigenen Augen sehen. Warum aber hat mein Herr, der König,
Gefallen an einer solchen Sache?

<<v4>>
4 Doch der König beharrte gegenüber Joab und den Anführern des Heeres
auf seinem Befehl und Joab und die Anführer des Heeres verließen den
König, um das Volk Israel zu mustern.

<<v5>>
5 Sie überschritten den Jordan und begannen bei Aroër, rechts von der
Stadt, die mitten im Tal liegt. Dann gingen sie auf Gad und Jaser zu [fn:4]

<<v6>>
6 und weiter nach Gilead und ins Land der Hetiter nach Kadesch. Von dort
aus zogen sie nach Dan und von Dan wandten sie sich nach Sidon. [fn:5]

<<v7>>
7 Dann kamen sie zur Festung Tyrus und zu all den Städten der Hiwiter
und der Kanaaniter. Darauf zogen sie in den Negeb von Juda hinab nach
Beerscheba.

<<v8>>
8 So durchstreiften sie das ganze Land und kamen nach neun Monaten und
zwanzig Tagen wieder nach Jerusalem zurück.

<<v9>>
9 Und Joab gab dem König das Ergebnis der Volkszählung bekannt: Israel
zählte achthunderttausend Krieger, die mit dem Schwert kämpfen konnten,
und Juda fünfhunderttausend.

<<v10>>
10 Dann aber schlug David das Gewissen, weil er das Volk gezählt hatte,
und er sagte zum Herrn: Ich habe schwer gesündigt, weil ich das getan
habe. Doch vergib deinem Knecht seine Schuld, Herr; denn ich habe sehr
unvernünftig gehandelt.

<<v11>>
11 Als David am Morgen aufstand, war bereits folgendes Wort des Herrn an
den Propheten Gad, den Seher Davids, ergangen:

<<v12>>
12 Geh und sag zu David: So spricht der Herr: Dreierlei lege ich dir
vor. Wähl dir eines davon! Das werde ich dir antun.

<<v13>>
13 Gad kam zu David, teilte ihm das Wort mit und sagte: Was soll über
dich kommen? Sieben Jahre Hungersnot in deinem Land? Oder drei Monate,
in denen dich deine Feinde verfolgen und du vor ihnen fliehen musst?
Oder soll drei Tage lang die Pest in deinem Land wüten? Überleg dir sehr
genau, was ich dem, der mich gesandt hat, als Antwort überbringen soll.

<<v14>>
14 Da sagte David zu Gad: Ich habe große Angst. Wir wollen lieber dem
Herrn in die Hände fallen, denn seine Barmherzigkeit ist groß; den
Menschen aber möchte ich nicht in die Hände fallen.

<<v15>>
15 Da ließ der Herr über Israel eine Pest kommen; sie dauerte von jenem
Morgen an bis zu dem festgesetzten Zeitpunkt und es starben zwischen Dan
und Beerscheba siebzigtausend Menschen im Volk. [fn:6]

<<v16>>
16 Als der Engel seine Hand gegen Jerusalem ausstreckte, um es ins
Verderben zu stürzen, reute den Herrn das Unheil und er sagte zu dem
Engel, der das Volk ins Verderben stürzte: Es ist jetzt genug, lass
deine Hand sinken! Der Engel war gerade bei der Tenne des Jebusiters
Arauna.

<<v17>>
17 Als David den Engel sah, der das Volk schlug, sagte er zum Herrn: Ich
bin es doch, der gesündigt hat; ich bin es, der sich vergangen hat. Aber
diese, die Herde, was haben denn sie getan? Erheb deine Hand gegen mich
und gegen das Haus meines Vaters!

<<v18>>
18 Am gleichen Tag kam Gad zu David und sagte zu ihm: Geh hinauf und
errichte dem Herrn auf der Tenne des Jebusiters Arauna einen Altar! [fn:7]

<<v19>>
19 David ging hinauf, wie es Gad gesagt und der Herr befohlen hatte.

<<v20>>
20 Arauna hielt gerade Ausschau und sah den König mit seinen Dienern
kommen. Er ging hinaus, warf sich vor dem König mit dem Gesicht zur Erde
nieder

<<v21>>
21 und sagte: Warum kommt mein Herr, der König, zu seinem Knecht? David
antwortete: Um von dir die Tenne zu kaufen und dem Herrn einen Altar zu
errichten, damit die Plage im Volk aufhört.

<<v22>>
22 Arauna antwortete David: Mein Herr, der König, möge alles nehmen, was
er für gut findet, und es (als Opfer) darbringen. Sieh her, hier sind
die Rinder für das Brandopfer und die Dreschschlitten und das Geschirr
der Rinder als Brennholz.

<<v23>>
23 Das alles gab [der König] Arauna dem König und sagte zu ihm: Der
Herr, dein Gott, sei dir gnädig.

<<v24>>
24 Der König erwiderte Arauna: Nein, ich will es dir gegen Bezahlung
abkaufen; ich will dem Herrn, meinem Gott, keine unbezahlten Brandopfer
darbringen. David kaufte also die Tenne und die Rinder für fünfzig
Silberschekel.

<<v25>>
25 Und er baute dort einen Altar für den Herrn und brachte Brandopfer
und Heilsopfer dar; der Herr aber ließ sich um des Landes willen
erweichen und die Plage hörte auf in Israel.\\
\\

* Footnotes

[fn:1] (1-25) [[file:1.Chr_21.org::v1][1 Chr 21,1-26]]

[fn:2] Der Vers schließt sachlich an 21,1-14 an. Eine
Volkszählung wird als Sünde des Misstrauens gegenüber Gott betrachtet;
sie konnte als Nachprüfung des Segens, der sich im Wachstum des Volkes
ausdrückte (V. 3), verstanden werden.

[fn:3] durchstreift: Text korr.; Angleichung an V. 4.

[fn:4] begannen: Text korr., vgl. G; H: lagerten sich.

[fn:5] nach Kadesch: Text korr., vgl. G. - wandten sie sich: Text korr., vgl. G.

[fn:6] Die Strafe entspricht dem Vergehen. Wenn das Volk
vermindert wird, ist der König, dessen Macht sich mindert, getroffen.

[fn:7] 18-25: Die Erzählung erklärt, warum die Tenne des Arauna
ein heiliger Ort geworden ist. Hier baute Salomo den Tempel (vgl. [[file:1.Chr_22.org::v1][1 Chr 22,1]]; [[file:2.Chr_3.org::v1][2 Chr 3,1]]).
