#+TITLE: 2 Sam 14 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-11 Sa 18:28]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Sam 14.html

* 2.Sam 14

<<verses>>

<<v1>>
1 Als Joab, der Sohn der Zeruja, merkte, dass das Herz des Königs sich
wieder Abschalom zuwandte, [fn:1]

<<v2>>
2 schickte er (einen Boten) nach Tekoa und ließ von dort eine kluge Frau
holen. Er sagte zu ihr: Tu so, als ob du trauerst, zieh Trauergewänder
an und salbe dich nicht mit Öl! Stell dich wie eine Frau, die schon
lange Zeit um einen Toten trauert.

<<v3>>
3 Dann geh zum König und sprich Folgendes zu ihm - und Joab sagte ihr,
was sie sagen sollte.

<<v4>>
4 Die Frau aus Tekoa ging zum König, warf sich mit dem Gesicht auf die
Erde nieder, um ihm zu huldigen und sagte: Hilf mir, mein König!

<<v5>>
5 Der König fragte sie: Was hast du? Sie antwortete: Ach, ich bin eine
Witwe; mein Mann ist tot.

<<v6>>
6 Deine Magd hatte zwei Söhne. Die beiden bekamen auf dem Feld Streit
miteinander, und weil niemand da war, der sich zwischen die beiden
gestellt hätte, schlug der eine den anderen tot.

<<v7>>
7 Da erhob sich die ganze Verwandtschaft gegen deine Magd. Sie sagten:
Gib den, der seinen Bruder erschlagen hat, heraus, damit wir ihn töten,
weil er seinen Bruder ums Leben gebracht hat. So wollten sie sogar den
Erben vernichten. Sie wollten die Kohle, die mir geblieben ist,
auslöschen, um meinem Mann weder Namen noch Nachkommen auf dem Erdboden
zu lassen. [fn:2]

<<v8>>
8 Da sagte der König zu der Frau: Geh nach Hause! Ich werde deine Sache
in Ordnung bringen. [fn:3]

<<v9>>
9 Die Frau aus Tekoa erwiderte dem König: Mein Herr und König, dann
lastet die Schuld auf mir und dem Haus meines Vaters. Der König aber und
sein Thron werden schuldlos sein.

<<v10>>
10 Der König antwortete: Wenn jemand gegen dich spricht, bring ihn zu
mir; er wird dir nicht wieder zu nahe treten.

<<v11>>
11 Sie aber sagte: Der König rufe doch den Herrn, deinen Gott, dafür an,
dass der Bluträcher nicht noch mehr Unheil anrichtet und meinen Sohn
umbringt. Der König antwortete: So wahr der Herr lebt, deinem Sohn soll
kein Haar gekrümmt werden. [fn:4]

<<v12>>
12 Darauf sagte die Frau: Deine Magd möchte meinem Herrn, dem König,
noch ein Wort sagen. Er antwortete: Sprich!

<<v13>>
13 Da fragte die Frau: Warum planst du genau das Gleiche gegen das Volk
Gottes? Wenn der König ein solches Urteil gefällt hat, spricht er sich
selbst schuldig, da er seinen verstoßenen (Sohn) nicht zurückkehren
lässt.

<<v14>>
14 Wir müssen alle sterben und sind wie das Wasser, das man auf die Erde
schüttet und nicht wieder einsammeln kann. Aber Gott wird dem das Leben
nicht nehmen, der darauf aus ist, dass ein von ihm Verstoßener nicht
verstoßen bleibt. [fn:5]

<<v15>>
15 Dass ich aber hergekommen bin, um dem König, meinem Herrn, das zu
sagen, geschah, weil die Leute mir Angst machten. Darum sagte sich deine
Magd: Ich will mit dem König reden; vielleicht wird der König tun, was
seine Magd sagt.

<<v16>>
16 Ja, der König wird (auf mich) hören und seine Magd aus der Hand des
Mannes retten, der mich zusammen mit meinem Sohn aus dem Erbbesitz
austilgen will.

<<v17>>
17 Deine Magd hat sich gesagt: Das Wort meines Herrn, des Königs, wird
mich beruhigen; denn mein Herr, der König, ist gerade so wie der Engel
Gottes: Er hört Gutes und Böses. Der Herr, dein Gott, sei mit dir.

<<v18>>
18 Der König erwiderte der Frau: Verhehl mir nichts von dem, was ich
dich jetzt frage. Die Frau sagte: Mein Herr und König, rede!

<<v19>>
19 Da fragte der König: Hat etwa Joab bei all dem die Hand im Spiel? Die
Frau antwortete: So wahr du lebst, mein Herr und König, an all dem, was
mein Herr, der König, sagt, kann man sich unmöglich rechts oder links
vorbeidrücken. Ja, dein Knecht Joab war es, der mir das befohlen hat; er
hat all diese Worte deiner Magd in den Mund gelegt.

<<v20>>
20 Das hat dein Knecht Joab getan, um der Sache ein anderes Gesicht zu
geben. Mein Herr ist weise wie der Engel Gottes, der alles weiß, was im
Land geschieht.

<<v21>>
21 Darauf sagte der König zu Joab: Gut, ich erfülle dir diese deine
Bitte. Geh, bring den jungen Abschalom zurück!

<<v22>>
22 Joab warf sich mit dem Gesicht auf die Erde nieder und huldigte (dem
König). Er segnete den König und sagte: Heute hat dein Knecht erkannt,
dass ich dein Wohlwollen gefunden habe, mein Herr und König, weil der
König die Bitte seines Knechtes erfüllt hat.

<<v23>>
23 Dann brach Joab auf, ging nach Geschur und brachte Abschalom nach
Jerusalem zurück. [fn:6]

<<v24>>
24 Der König aber sagte: Er soll in sein Haus gehen, aber er soll mir
nicht unter die Augen treten. Abschalom ging in sein Haus, aber dem
König durfte er nicht unter die Augen treten.

<<v25>>
25 In ganz Israel gab es keinen schöneren und lobenswerteren Mann als
Abschalom. Vom Scheitel bis zur Sohle war kein Makel an ihm.

<<v26>>
26 Und wenn er sein Haar schneiden ließ - das geschah von Zeit zu Zeit,
weil es so schwer wurde, dass er es schneiden lassen musste - und man
wog sein Haar, dann wog es zweihundert Schekel nach königlichem Gewicht.

<<v27>>
27 Drei Söhne wurden Abschalom geboren und eine Tochter namens Tamar;
sie wurde eine Frau von großer Schönheit. [fn:7]

<<v28>>
28 Abschalom wohnte zwei Jahre lang in Jerusalem, ohne dem König unter
die Augen zu treten.

<<v29>>
29 Da schickte Abschalom jemand zu Joab, weil er ihn zum König senden
wollte; aber Joab wollte nicht kommen. Er schickte noch ein zweites Mal
jemand hin, aber er wollte wieder nicht kommen.

<<v30>>
30 Da sagte Abschalom zu seinen Knechten: Seht, das Feld Joabs, das
neben meinem liegt; er hat dort Gerste (angebaut). Geht hin, steckt es
in Brand! Die Diener Abschaloms steckten das Feld in Brand.

<<v31>>
31 Darauf machte sich Joab auf den Weg, suchte Abschalom in seinem Haus
auf und fragte ihn: Warum haben deine Knechte das Feld in Brand
gesteckt, das mir gehört?

<<v32>>
32 Abschalom antwortete: Ich hatte doch jemand zu dir geschickt und dir
sagen lassen: Komm her, ich möchte dich zum König senden. Du sollst ihn
fragen: Wozu bin ich eigentlich von Geschur hergekommen? Es wäre für
mich besser gewesen, ich wäre dort geblieben. Jetzt aber möchte ich dem
König vor die Augen treten. Wenn eine Schuld auf mir liegt, soll er mich
töten.

<<v33>>
33 Joab ging zum König und berichtete ihm alles und der König ließ
Abschalom rufen. Er kam zum König und fiel vor ihm mit dem Gesicht zur
Erde nieder. Und der König küsste Abschalom.\\
\\

* Footnotes

[fn:1] Tekoa: südlich von Betlehem, Heimat des Propheten Amos.

[fn:2] [[file:Dtn_19.org::v11][Dtn 19,11-13]]

[fn:3] Ich werde . . . in Ordnung bringen, wörtlich: Ich werde
deinetwegen Befehl geben.

[fn:4] Wörtlich: Keines von den Haaren deines Sohnes soll zu
Boden fallen.

[fn:5] Einen Toten kann man nicht wieder ins Leben rufen,
selbst wenn Abschalom verstoßen bleibt. Der Sinn des zweiten Satzes ist
nicht ganz klar. Mit V. 15 kehrt die Rede der Frau zu dem angenommenen
Fall zurück.

[fn:6] [[file:2.Sam_13.org::v37][13,37]]

[fn:7] [[file:2.Sam_18.org::v18][18,18]]
