#+TITLE: 2 Sam 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-11 Sa 23:12]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/2 Sam 21.html

<<verses>>

<<v1>>
* Nachträge: 21,1 - 24,25

* Die Rache der Gibeoniter und die Treue der Rizpa: 21,1-14

1 Zur Zeit Davids herrschte drei Jahre hintereinander eine Hungersnot.
Da suchte David den Herrn auf (um ihn zu befragen). Der Herr sagte: Auf
Saul und seinem Haus lastet eine Blutschuld, weil er die Gibeoniter
getötet hat.

<<v2>>
2 Da rief der König die Gibeoniter zu sich und redete mit ihnen. Die
Gibeoniter stammten nicht von den Söhnen Israels ab, sondern von einem
Rest der Amoriter. Obwohl die Israeliten sich ihnen gegenüber mit einem
Eid (zum Wohlwollen) verpflichtet hatten, versuchte Saul in seinem Eifer
für die Söhne Israels und Judas, sie zu vernichten. [fn:1]

<<v3>>
3 David sagte also zu den Gibeonitern: Was soll ich für euch tun? Womit
kann ich Sühne leisten, damit ihr dem Erbe des Herrn wieder Segen
bringt?

<<v4>>
4 Die Gibeoniter antworteten ihm: Wir wollen weder Silber noch Gold von
Saul und seinem Haus; auch steht es uns nicht zu, jemand in Israel zu
töten. David sagte: Was meint ihr, was soll ich für euch tun?

<<v5>>
5 Sie sagten zum König: Der Mann, der uns vernichten wollte und der
darauf aus war, uns auszurotten, sodass wir uns in keinem Gebiet Israels
mehr hätten halten können,

<<v6>>
6 von dessen Söhnen soll man uns sieben Männer geben. Wir wollen sie vor
dem Herrn im Gibea Sauls, des vom Herrn Erwählten, hinrichten. Der König
antwortete: Ich will sie euch geben. [fn:2]

<<v7>>
7 Merib-Baal, den Sohn Jonatans, des Sohnes Sauls, aber verschonte der
König wegen der Abmachung zwischen David und Jonatan, dem Sohn Sauls,
die sie mit einem Eid beim Herrn bekräftigt hatten. [fn:3] [fn:4]

<<v8>>
8 Der König nahm Armoni und Mefi-Boschet, die beiden Söhne, die Rizpa,
die Tochter Ajas, dem Saul geboren hatte, und die fünf Söhne, die
Michal, die Tochter Sauls, dem Adriël, dem Sohn Barsillais aus Mehola,
geboren hatte. [fn:5]

<<v9>>
9 Er lieferte sie den Gibeonitern aus, die sie auf dem Berg vor dem
Angesicht des Herrn hinrichteten; so kamen alle sieben auf einmal um.
Sie wurden in den ersten Tagen der Ernte getötet, zu Beginn der
Gerstenernte.

<<v10>>
10 Rizpa, die Tochter Ajas, aber nahm Sackleinen und legte es für sich
auf den Felsen und (sie blieb dort) bei den Toten vom Beginn der Ernte,
bis sich Wasser vom Himmel über die Toten ergoss. Sie ließ nicht zu,
dass bei Tag die Vögel des Himmels und bei Nacht die Tiere des Feldes an
sie herankamen.

<<v11>>
11 Als David erzählt wurde, was Rizpa, die Tochter Ajas und Nebenfrau
Sauls, getan hatte,

<<v12>>
12 holte er die Gebeine Sauls und die Gebeine seines Sohnes Jonatan von
den Bürgern von Jabesch-Gilead, die sie heimlich vom Marktplatz in
Bet-Schean weggenommen hatten, wo die Philister sie aufgehängt hatten,
als sie Israel am Gilboa schlugen. [fn:6]

<<v13>>
13 Er ließ also von dort die Gebeine Sauls und die Gebeine seines Sohnes
Jonatan heraufbringen. Dann sammelte man die Gebeine der Hingerichteten
ein

<<v14>>
14 und begrub sie zusammen mit den Gebeinen Sauls und seines Sohnes
Jonatan in Zela im Land Benjamin, im Grab von Sauls Vater Kisch. Man tat
alles, was der König befohlen hatte, und Gott ließ sich daraufhin für
das Land gnädig stimmen.\\
\\

<<v15>>
* Die Helden Davids und ihre Taten: 21,15-22

15 Wieder einmal kam es zum Krieg zwischen den Philistern und Israel.
David zog mit seinen Leuten hinab. Als sie gegen die Philister kämpften,
wurde David müde.

<<v16>>
16 Jischbi aus Nob, ein Rafaïter, dessen Bronze-Speer dreihundert
Schekel wog und der mit einem neuen Schwert umgürtet war, sagte, er
werde David erschlagen.

<<v17>>
17 Aber Abischai, der Sohn der Zeruja, kam David zu Hilfe und schlug den
Philister tot. Damals leisteten die Männer Davids ihm folgenden Schwur:
Du wirst nicht mehr mit uns in den Kampf ziehen, damit du nicht die
Leuchte Israels auslöschst. [fn:7]

<<v18>>
18 Danach kam es bei Gob wieder zum Kampf mit den Philistern. Damals
erschlug Sibbechai aus Huscha den Sippai, der zu den Rafaïtern gehörte. [fn:8]

<<v19>>
19 Als es wieder einmal bei Gob zum Kampf gegen die Philister kam,
erschlug Elhanan, der Sohn Jaïrs aus Betlehem, den Goliat aus Gat,
dessen Speer einem Weberbaum glich. [fn:9]

<<v20>>
20 Dann kam es noch einmal bei Gat zum Kampf. Da trat ein Mann von
riesenhafter Größe auf; er hatte an jeder Hand sechs Finger und an jedem
Fuß sechs Zehen, zusammen vierundzwanzig; auch er stammte von Rafa ab.

<<v21>>
21 Als er Israel verhöhnte, erschlug ihn Jonatan, der Sohn von Davids
Bruder Schima.

<<v22>>
22 Diese vier stammten von Rafa aus Gat ab; sie fielen durch die Hand
Davids und seiner Krieger.\\
\\

* Footnotes

[fn:1] [[file:Jos_9.org::v3][Jos 9,3]].[[file:Jos_9.org::v15][15]].[[file:Jos_9.org::v19][19]]

[fn:2] Die Gibeoniter wollen die Blutrache ausüben.

[fn:3] [[file:1.Sam_18.org::v3][1 Sam 18,3]]

[fn:4] Merib-Baal: H: Mefi-Boschet (vgl. die Anmerkung zu 4,4).

[fn:5] [[file:2.Sam_3.org::v7][3,7]]; [[file:1.Sam_18.org::v19][1 Sam 18,19]]

[fn:6] [[file:1.Sam_31.org::v12][1 Sam 31,12f]]

[fn:7] Die «Leuchte Israels» ist der König, also David.

[fn:8] (18-22) [[file:1.Chr_20.org::v4][1 Chr 20,4-8]]

[fn:9] Jaïrs: Text korr. nach [[file:1.Chr_20.org::v5][1 Chr 20,5]].
