#+TITLE: 2 Sam 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-11 Sa 18:08]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Sam 12.html

<<verses>>

<<v1>>
* Gottes Strafe für David: 12,1-25

1 Darum schickte der Herr den Natan zu David; dieser ging zu David und
sagte zu ihm: In einer Stadt lebten einst zwei Männer; der eine war
reich, der andere arm.

<<v2>>
2 Der Reiche besaß sehr viele Schafe und Rinder,

<<v3>>
3 der Arme aber besaß nichts außer einem einzigen kleinen Lamm, das er
gekauft hatte. Er zog es auf und es wurde bei ihm zusammen mit seinen
Kindern groß. Es aß von seinem Stück Brot und es trank aus seinem
Becher, in seinem Schoß lag es und war für ihn wie eine Tochter.

<<v4>>
4 Da kam ein Besucher zu dem reichen Mann und er brachte es nicht über
sich, eines von seinen Schafen oder Rindern zu nehmen, um es für den
zuzubereiten, der zu ihm gekommen war. Darum nahm er dem Armen das Lamm
weg und bereitete es für den Mann zu, der zu ihm gekommen war.

<<v5>>
5 Da geriet David in heftigen Zorn über den Mann und sagte zu Natan: So
wahr der Herr lebt: Der Mann, der das getan hat, verdient den Tod.

<<v6>>
6 Das Lamm soll er vierfach ersetzen, weil er das getan und kein Mitleid
gehabt hat. [fn:1]

<<v7>>
7 Da sagte Natan zu David: Du selbst bist der Mann. So spricht der Herr,
der Gott Israels: Ich habe dich zum König von Israel gesalbt und ich
habe dich aus der Hand Sauls gerettet.

<<v8>>
8 Ich habe dir das Haus deines Herrn und die Frauen deines Herrn in den
Schoß gegeben und ich habe dir das Haus Israel und Juda gegeben, und
wenn das zu wenig ist, gebe ich dir noch manches andere dazu.

<<v9>>
9 Aber warum hast du das Wort des Herrn verachtet und etwas getan, was
ihm missfällt? Du hast den Hetiter Urija mit dem Schwert erschlagen und
hast dir seine Frau zur Frau genommen; durch das Schwert der Ammoniter
hast du ihn umgebracht. [fn:2]

<<v10>>
10 Darum soll jetzt das Schwert auf ewig nicht mehr von deinem Haus
weichen; denn du hast mich verachtet und dir die Frau des Hetiters
genommen, damit sie deine Frau werde. [fn:3]

<<v11>>
11 So spricht der Herr: Ich werde dafür sorgen, dass sich aus deinem
eigenen Haus das Unheil gegen dich erhebt, und ich werde dir vor deinen
Augen deine Frauen wegnehmen und sie einem andern geben; er wird am
hellen Tag bei deinen Frauen liegen. [fn:4]

<<v12>>
12 Ja, du hast es heimlich getan, ich aber werde es vor ganz Israel und
am hellen Tag tun.

<<v13>>
13 Darauf sagte David zu Natan: Ich habe gegen den Herrn gesündigt.
Natan antwortete David: Der Herr hat dir deine Sünde vergeben; du wirst
nicht sterben. [fn:5]

<<v14>>
14 Weil du aber die Feinde des Herrn durch diese Sache zum Lästern
veranlasst hast, muss der Sohn, der dir geboren wird, sterben.

<<v15>>
15 Dann ging Natan nach Hause. Der Herr aber ließ das Kind, das die Frau
des Urija dem David geboren hatte, schwer krank werden.

<<v16>>
16 David suchte Gott wegen des Knaben auf und fastete streng; und wenn
er heimkam, legte er sich bei Nacht auf die bloße Erde.

<<v17>>
17 Die Ältesten seines Hauses kamen zu ihm, um ihn dazu zu bewegen, von
der Erde aufzustehen. Er aber wollte nicht und aß auch nicht mit ihnen.

<<v18>>
18 Am siebten Tag aber starb das Kind. Davids Diener fürchteten sich,
ihm mitzuteilen, dass das Kind tot war; denn sie sagten: Wir haben ihm
zugeredet, als das Kind noch am Leben war; er aber hat nicht auf uns
gehört. Wie können wir ihm jetzt sagen: Das Kind ist tot? Er würde ein
Unheil anrichten.

<<v19>>
19 David jedoch sah, dass seine Diener miteinander flüsterten, und
merkte daran, dass das Kind tot war. Er fragte seine Diener: Ist das
Kind tot? Sie antworteten: Ja, es ist tot.

<<v20>>
20 Da erhob sich David von der Erde, wusch sich, salbte sich, wechselte
seine Kleider, ging zum Haus des Herrn und warf sich (davor) nieder. Als
er dann nach Hause zurückkehrte, verlangte er (zu essen). Man setzte ihm
etwas vor und er aß.

<<v21>>
21 Da fragten ihn seine Diener: Was soll das bedeuten, was du getan
hast? Als das Kind noch am Leben war, hast du seinetwegen gefastet und
geweint. Nachdem aber das Kind tot ist, stehst du auf und isst.

<<v22>>
22 Er antwortete: Als das Kind noch am Leben war, habe ich gefastet und
geweint; denn ich dachte: Wer weiß, vielleicht ist der Herr mir gnädig
und das Kind bleibt am Leben.

<<v23>>
23 Jetzt aber, da es tot ist, warum soll ich da noch fasten? Kann ich es
zurückholen? Ich werde einmal zu ihm gehen, aber es kommt nicht zu mir
zurück.

<<v24>>
24 Und David tröstete seine Frau Batseba; er ging zu ihr hinein und
schlief mit ihr. Und sie gebar einen Sohn und er gab ihm den Namen
Salomo. Der Herr liebte Salomo

<<v25>>
25 und sandte den Propheten Natan, damit er ihm um des Herrn willen den
Namen Jedidja (Liebling des Herrn) gebe. [fn:6]\\
\\

<<v26>>
* Die Eroberung von Rabba: 12,26-31

26 Joab kämpfte gegen Rabba, (die Stadt) der Ammoniter, und er eroberte
die Königsstadt. [fn:7] [fn:8]

<<v27>>
27 Darauf schickte Joab Boten zu David und ließ ihm sagen: Ich habe
gegen Rabba gekämpft und dabei auch die Wasserstadt eingenommen.

<<v28>>
28 Darum versammle jetzt den Rest des Heeres, belagere die Stadt und
nimm sie selbst ein, damit nicht ich sie einnehme und mein Name über ihr
ausgerufen wird.

<<v29>>
29 David sammelte also das ganze Heer, zog nach Rabba, kämpfte gegen die
Stadt und nahm sie ein.

<<v30>>
30 Dann nahm er ihrem König die Krone vom Haupt, deren Gewicht ein
Talent Gold betrug und an der ein kostbarer Stein war; sie wurde nun
Davids Krone. Und er schaffte eine sehr große Beute aus der Stadt fort. [fn:9] [fn:10]

<<v31>>
31 Auch ihre Einwohner führte er fort und stellte sie an die Steinsägen,
an die eisernen Spitzhacken und an die eisernen Äxte und ließ sie in den
Ziegeleien arbeiten. So machte er es mit allen Städten der Ammoniter.
Dann kehrte David mit dem ganzen Heer nach Jerusalem zurück. [fn:11]\\
\\

* Footnotes

[fn:1] [[file:Ex_21.org::v37][Ex 21,37]]

[fn:2] [[file:1.Kön_15.org::v5][1 Kön 15,5]]

[fn:3] [[file:2.Sam_13.org::v28][13,28f]]; [[file:2.Sam_18.org::v14][18,14]]; [[file:1.Kön_2.org::v24][1 Kön 2,24f]]

[fn:4] [[file:2.Sam_16.org::v22][16,22]]; [[file:2.Sam_20.org::v3][20,3]]

[fn:5] [[file:Ps_51.org::v2][Ps 51,2]]

[fn:6] Der Name Jedidja, der nur hier vorkommt, weist schon auf
die Nachfolge Davids hin und bringt auch zum Ausdruck, dass Gott nun dem
König wieder gnädig ist.

[fn:7] [[file:2.Sam_11.org::v1][11,1]]

[fn:8] Rabba: die Hauptstadt des Ammoniterreichs, heute Amman.

[fn:9] (30-31) [[file:1.Chr_20.org::v2][1 Chr 20,2f]]

[fn:10] Wahrscheinlich ist eher der Wert als das Gewicht (etwa
41 kg) der Krone gemeint.

[fn:11] ließ sie arbeiten: Text korr.; H: führte sie hindurch.
