#+TITLE: 2 Sam 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-11 Sa 21:58]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Sam 17.html

* 2.Sam 17

<<verses>>

<<v1>>
1 Und Ahitofel sagte weiter zu Abschalom: Ich möchte zwölftausend Mann
auswählen, mit ihnen noch heute Nacht aufbrechen und David nachsetzen.

<<v2>>
2 Ich will ihn überfallen, wenn er noch müde und ermattet ist, und ihm
einen Schrecken einjagen. Alle Leute, die bei ihm sind, werden fliehen
und ich kann den König, wenn er allein ist, erschlagen.

<<v3>>
3 Dann werde ich das ganze Volk zu dir zurückführen, wie eine
Neuvermählte zu ihrem Mann heimgeholt wird. Du trachtest ja nur dem
einen Mann nach dem Leben; das ganze übrige Volk aber soll Frieden
haben. [fn:1]

<<v4>>
4 Der Plan erschien Abschalom und allen Ältesten Israels gut.

<<v5>>
5 Abschalom aber sagte: Ruft auch den Arkiter Huschai! Wir wollen hören,
was er zu sagen hat.

<<v6>>
6 Als Huschai kam, sagte Abschalom zu ihm: Das und das hat Ahitofel
gesagt. Sollen wir seinen Vorschlag ausführen? Wenn nicht, dann rede du!

<<v7>>
7 Da sagte Huschai zu Abschalom: Diesmal ist der Rat, den Ahitofel
gegeben hat, nicht gut. [fn:2]

<<v8>>
8 Und er fuhr fort: Du kennst deinen Vater und seine Männer; sie sind
Krieger und von wildem Mut erfüllt, wie eine Bärin im freien Gelände,
der man die Jungen geraubt hat. Dein Vater ist ein Krieger, der mit
seinen Leuten keine Nachtruhe hält.

<<v9>>
9 Sicher hält er sich jetzt in einer Höhle oder an einem anderen Ort
versteckt. Wenn nun gleich zu Anfang einige von deinen Leuten fallen und
man hört davon, wird man sagen: Die Anhänger Abschaloms haben eine
Niederlage erlitten. [fn:3]

<<v10>>
10 Dann wird auch der Tapferste - und habe er ein Herz wie ein Löwe
völlig den Mut verlieren; denn ganz Israel weiß, dass dein Vater ein
Held ist und tapfere Männer bei sich hat.

<<v11>>
11 Darum rate ich: Alle Israeliten zwischen Dan und Beerscheba sollen
sich bei dir versammeln, (ein Heer) so zahlreich wie der Sand am Ufer
des Meeres. Du selbst musst (mit ihnen) in den Kampf ziehen.

<<v12>>
12 Wenn wir ihn dann in einem der Orte, wo er sich aufhält, finden,
überfallen wir ihn, wie der Tau auf die Erde fällt; dann wird von ihm
und allen Männern, die bei ihm sind, auch nicht einer übrig bleiben.

<<v13>>
13 Und wenn er sich in eine Stadt zurückzieht, so wird ganz Israel Seile
an (den Mauern) jener Stadt befestigen und wir schleifen sie ins Tal
hinab, sodass dort, wo sie sind, kein Stein mehr zu finden ist.

<<v14>>
14 Da sagten Abschalom und alle Israeliten: Der Rat des Arkiters Huschai
ist besser als der Rat Ahitofels. Der Herr hatte es nämlich so bestimmt;
der gute Rat Ahitofels sollte durchkreuzt werden, weil der Herr Unheil
über Abschalom bringen wollte. [fn:4] [fn:5]

<<v15>>
15 Darauf sagte Huschai zu den Priestern Zadok und Abjatar: Das und das
hat Ahitofel Abschalom und den Ältesten Israels geraten und das und das
habe ich geraten. [fn:6]

<<v16>>
16 Schickt jetzt schnell jemand zu David und lasst ihm sagen: Bleib
heute Nacht nicht bei den Furten, (die) zur Steppe (hinüberführen),
sondern zieh sofort hinüber, damit nicht der König samt allen Leuten,
die er bei sich hat, vernichtet wird.

<<v17>>
17 Jonatan und Ahimaaz aber hielten sich an der Rogel-Quelle auf; eine
Magd ging zu ihnen und brachte ihnen die Nachricht, sie aber gingen zu
König David und machten ihm Meldung. Sie durften sich nämlich nicht
sehen lassen und konnten deshalb die Stadt nicht betreten. [fn:7]

<<v18>>
18 Doch ein junger Mann sah sie trotzdem und meldete es Abschalom. Die
beiden aber gingen schnell weiter und kamen zum Haus eines Mannes in
Bahurim, der in seinem Hof einen Brunnen hatte. Sie stiegen hinein

<<v19>>
19 und die Frau nahm eine Decke, breitete sie über die Öffnung des
Brunnens und streute Körner darauf, sodass man nichts merken konnte.

<<v20>>
20 Als Abschaloms Knechte zu der Frau ins Haus kamen, fragten sie: Wo
sind Ahimaaz und Jonatan? Die Frau antwortete ihnen: Sie sind von hier
zum Wasser weitergegangen. Die Knechte machten sich auf die Suche, als
sie sie aber nicht fanden, kehrten sie nach Jerusalem zurück. [fn:8]

<<v21>>
21 Nachdem sie weggegangen waren, stiegen die beiden aus dem Brunnen
heraus, gingen zu König David und brachten ihm die Nachricht. Sie sagten
zu David: Brecht auf und geht schnell über den Fluss hinüber; denn
Ahitofel hat gegen euch den und den Rat erteilt.

<<v22>>
22 Da brach David mit allen Leuten, die noch bei ihm waren, auf, und zog
über den Jordan. Als es Morgen wurde, war auch nicht mehr einer da, der
den Jordan nicht überschritten hätte.

<<v23>>
23 Als Ahitofel sah, dass sein Rat nicht ausgeführt wurde, sattelte er
seinen Esel, brach auf und kehrte in seine Heimatstadt zurück. Dann
bestellte er sein Haus und erhängte sich. So starb er und man begrub ihn
im Grab seines Vaters. [fn:9]\\
\\

<<v24>>
* Davids Vorbereitungen zum Kampf: 17,24 - 18,5

24 Als David nach Mahanajim gekommen war, überschritt Abschalom mit
allen Israeliten den Jordan.

<<v25>>
25 Abschalom hatte Amasa anstelle Joabs an die Spitze des Heeres
gestellt. Amasa war der Sohn eines Ismaeliters namens Jeter und der
Abigal, die eine Tochter des Nahasch und eine Schwester von Joabs Mutter
Zeruja war. [fn:10]

<<v26>>
26 Die Israeliten unter Abschalom schlugen ihr Lager im Gebiet von
Gilead auf.

<<v27>>
27 Als nun David nach Mahanajim gekommen war, brachten ihm Schobi, der
Sohn des Nahasch aus der Ammoniterstadt Rabba, und Machir, der Sohn
Ammiëls aus Lo-Dabar, sowie der Gileaditer Barsillai aus Roglim [fn:11] [fn:12]

<<v28>>
28 Matten und Decken, irdene Gefäße, Weizen, Gerste, Mehl und geröstetes
Korn, Bohnen und Linsen [und geröstetes Korn];

<<v29>>
29 außerdem brachten sie David und seinen Leuten Honig und Butter,
Schafe und Käse als Nahrung. Denn sie sagten: Das Volk in der Steppe ist
hungrig, durstig und erschöpft.

* Footnotes

[fn:1] Text korr. nach G.

[fn:2] [[file:2.Sam_15.org::v34][15,34]]

[fn:3] von deinen Leuten, wörtlich: von ihnen; gemeint sind die
Leute Abschaloms.

[fn:4] [[file:2.Sam_15.org::v31][15,31]]

[fn:5] Der Rat Huschais soll David Zeitgewinn bringen.

[fn:6] (15-21) [[file:2.Sam_15.org::v36][15,36]]

[fn:7] Die Rogel-Quelle ist bei Jerusalem, südlich der
Vereinigung des Kidrontals mit dem Hinnomtal.

[fn:8] von hier zum Wasser: Text korr.

[fn:9] Selbstmord begeht im AT nur jemand, der einem grausamen
Tod entgehen will (vgl. [[file:Ri_9.org::v54][Ri 9,54]]; [[file:1.Sam_31.org::v4][1 Sam 31,4]]; [[file:1.Kön_16.org::v18][1 Kön 16,18]]; [[file:2.Makk_14.org::v43][2 Makk 14,43-46]]).

[fn:10] Ismaeliters: Text korr. nach [[file:1.Chr_2.org::v17][1 Chr 2,17]].

[fn:11] [[file:2.Sam_9.org::v4][9,4]]; [[file:2.Sam_19.org::v32][19,32]]; [[file:1.Kön_2.org::v7][1 Kön 2,7]]

[fn:12] brachten: ergänzt nach G.
