#+TITLE: 2 Sam 11 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-11 Sa 18:00]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/2 Sam 11.html


<<verses>>

<<v1>>
* David und Batseba: 11,1-27

1 Um die Jahreswende, zu der Zeit, in der die Könige in den Krieg
ziehen, schickte David den Joab mit seinen Männern und ganz Israel aus
und sie verwüsteten das Land der Ammoniter und belagerten Rabba. David
selbst aber blieb in Jerusalem. [fn:1] [fn:2]

<<v2>>
2 Als David einmal zur Abendzeit von seinem Lager aufstand und auf dem
Flachdach des Königspalastes hin- und herging, sah er von dort aus eine
Frau, die badete. Die Frau war sehr schön anzusehen.

<<v3>>
3 David schickte jemand hin und erkundigte sich nach ihr. Man sagte ihm:
Das ist Batseba, die Tochter Ammiëls, die Frau des Hetiters Urija.

<<v4>>
4 Darauf schickte David Boten zu ihr und ließ sie holen; sie kam zu ihm,
und er schlief mit ihr - sie hatte sich gerade von ihrer Unreinheit
gereinigt. Dann kehrte sie in ihr Haus zurück. [fn:3]

<<v5>>
5 Die Frau war aber schwanger geworden und schickte deshalb zu David und
ließ ihm mitteilen: Ich bin schwanger.

<<v6>>
6 Darauf sandte David einen Boten zu Joab (und ließ ihm sagen): Schick
den Hetiter Urija zu mir! Und Joab schickte Urija zu David.

<<v7>>
7 Als Urija zu ihm kam, fragte David, ob es Joab und dem Volk gut gehe
und wie es mit dem Kampf stehe.

<<v8>>
8 Dann sagte er zu Urija: Geh in dein Haus hinab und wasch dir die Füße!
Urija verließ das Haus des Königs und es wurde ihm ein Geschenk des
Königs nachgetragen.

<<v9>>
9 Urija aber legte sich am Tor des Königshauses bei den Knechten seines
Herrn nieder und ging nicht in sein Haus hinab.

<<v10>>
10 Man berichtete David: Urija ist nicht in sein Haus hinabgegangen.
Darauf sagte David zu Urija: Bist du nicht gerade von einer Reise
gekommen? Warum bist du nicht in dein Haus hinuntergegangen?

<<v11>>
11 Urija antwortete David: Die Lade und Israel und Juda wohnen in Hütten
und mein Herr Joab und die Knechte meines Herrn lagern auf freiem Feld;
da soll ich in mein Haus gehen, um zu essen und zu trinken und bei
meiner Frau zu liegen? So wahr du lebst und so wahr deine Seele lebt,
das werde ich nicht tun. [fn:4]

<<v12>>
12 Darauf sagte David zu Urija: Bleib auch heute noch hier; morgen werde
ich dich wegschicken. So blieb Urija an jenem Tag in Jerusalem. Am
folgenden Tag

<<v13>>
13 lud David ihn ein, bei ihm zu essen und zu trinken, und machte ihn
betrunken. Am Abend aber ging Urija weg, um sich wieder auf seinem Lager
bei den Knechten seines Herrn niederzulegen; er ging nicht in sein Haus
hinab.

<<v14>>
14 Am anderen Morgen schrieb David einen Brief an Joab und ließ ihn
durch Urija überbringen.

<<v15>>
15 Er schrieb in dem Brief: Stellt Urija nach vorn, wo der Kampf am
heftigsten ist, dann zieht euch von ihm zurück, sodass er getroffen wird
und den Tod findet.

<<v16>>
16 Joab hatte die Stadt beobachtet und er stellte Urija an einen Platz,
von dem er wusste, dass dort besonders tüchtige Krieger standen.

<<v17>>
17 Als dann die Leute aus der Stadt einen Ausfall machten und gegen Joab
kämpften, fielen einige vom Volk, das heißt von den Kriegern Davids;
auch der Hetiter Urija fand den Tod.

<<v18>>
18 Joab schickte (einen Boten) zu David und ließ ihm den Verlauf des
Kampfes berichten.

<<v19>>
19 Und er befahl dem Boten: Wenn du dem König alles über den Verlauf des
Kampfes bis zu Ende berichtet hast

<<v20>>
20 und wenn dann der König in Zorn gerät und zu dir sagt: Warum seid ihr
beim Kampf so nahe an die Stadt herangegangen? Habt ihr nicht gewusst,
dass sie von der Mauer herabschießen?

<<v21>>
21 Wer hat Abimelech, den Sohn Jerubbaals, erschlagen? Hat nicht eine
Frau in Tebez einen Mühlstein von der Mauer auf ihn herabgeworfen,
sodass er starb? Warum seid ihr so nahe an die Mauer herangegangen?,
dann sollst du sagen: Auch dein Knecht, der Hetiter Urija, ist tot. [fn:5] [fn:6]

<<v22>>
22 Der Bote ging fort, kam zu David und berichtete ihm alles, was Joab
ihm aufgetragen hatte.

<<v23>>
23 Der Bote sagte zu David: Die Männer waren stärker als wir und waren
gegen uns bis aufs freie Feld vorgedrungen; wir aber drängten sie bis
zum Eingang des Tores zurück.

<<v24>>
24 Da schossen die Schützen von der Mauer herab auf deine Knechte,
sodass einige von den Knechten des Königs starben; auch dein Knecht, der
Hetiter Urija, ist tot.

<<v25>>
25 Da sagte David zu dem Boten: So sollst du zu Joab sagen: Betrachte
die Sache nicht als so schlimm; denn das Schwert frisst bald hier, bald
dort. Setz den Kampf gegen die Stadt mutig fort und zerstöre sie! So
sollst du ihm Mut machen.

<<v26>>
26 Als die Frau Urijas hörte, dass ihr Mann Urija tot war, hielt sie für
ihren Gemahl die Totenklage.

<<v27>>
27 Sobald die Trauerzeit vorüber war, ließ David sie zu sich in sein
Haus holen. Sie wurde seine Frau und gebar ihm einen Sohn. Dem Herrn
aber missfiel, was David getan hatte.\\
\\

* Footnotes

[fn:1] [[file:2.Sam_12.org::v26][12,26]]

[fn:2] das Land: so sinngemäß nach [[file:1.Chr_20.org::v1][1 Chr 20,1]].

[fn:3] [[file:Ex_20.org::v14][Ex 20,14]].[[file:Ex_20.org::v17][17]]; [[file:Dtn_5.org::v18][Dtn 5,18]].[[file:Dtn_5.org::v21][21]]

[fn:4] Die Lade Gottes wurde in den Kampf mitgenommen
(vgl. [[file:1.Sam_4.org::v3][1 Sam 4,3f]]; [[file:Num_10.org::v35][Num 10,35f]]).

[fn:5] [[file:Ri_9.org::v53][Ri 9,53f]]

[fn:6] Jerubbaals: Text korr. nach G (vgl. [[file:Ri_7.org::v1][Ri 7,1]]); H liest
Jerubbeschet, um den Namen des Gottes Baal verächtlich zu machen (vgl.
die Anmerkungen zu 2,8; 4,4).
