#+filetags:   :at:gen1:
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur authoryear-ibid
#+TODO: TODO(t) STARTED(s!) WAITING(w@/!) APPT(a) PROJ(p) NOTIZ(n) NEXT(x) BESPROCHEN(b) DELEGATED(g@/!) | DONE(d!) CANCELED(c@)
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+title:      Gen 1
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com

* Gen 1
:PROPERTIES:
  :CUSTOM_ID: gen-1
  :ID:       Gen-1
  :END:

Das erste der fünf Bücher Mose heißt in der griechischen und in der
lateinischen Übersetzung Genesis (Entstehung), weil es von der
Entstehung der Welt, der Menschheit und des Volkes Israel handelt. Die
Juden nennen das Buch nach dem Anfangswort Bereschit (Im Anfang). Es
gliedert sich in zwei Hauptteile: Urgeschichte (Kap. 1 - 11) und
Patriarchengeschichte (Kap. 12 - 50). In der Patriarchengeschichte
unterscheidet man: die Geschichte der Erzväter (Kap. 12 - 36) und die
Geschichte der Söhne Jakobs (Kap. 37 - 50).\\
\\
Die theologische Bedeutung des Buches liegt in seinen Aussagen über Gott
als den Schöpfer der Welt und den Herrn der Geschichte. Wichtig ist
dabei vor allem die Erschaffung der Welt durch das Wort Gottes, die
Gottebenbildlichkeit des Menschen, die Erzählung von Paradies und
Sündenfall, von der Sintflut und dem Bund mit Noach, von der
gnadenhaften Erwählung Abrahams und seiner Nachkommen als Segensmittler
für die ganze Menschheit, von den Verheißungen an die Patriarchen. Alles
Handeln Gottes in der Geschichte ist nach dieser Sicht letztlich auf das
Heil der Menschen ausgerichtet.\\
\\
Das Buch Genesis verarbeitet älteste Überlieferungen Israels und seiner
Nachbarvölker über die Urgeschichte der Menschheit und die Vorgeschichte
Israels. Es wählt davon Ereignisse aus, die für die
Menschheitsgeschichte charakteristisch sind, und zeigt an bestimmten
Personen, wie Gott die Menschen zum Heil beruft, wie die Menschen das
Heilsangebot Gottes ausschlagen und sich damit selbst immer tiefer ins
Unheil stürzen; es zeigt aber auch, wie Gott in Abraham und seinen
Nachkommen dem Fluch den unverdienten Segen entgegensetzt, an dem alle
Menschen Anteil erhalten sollen (Gen 12,3).\\
\\
Die Erzählungen der Urgeschichte sind weder als naturwissenschaftliche
Aussagen noch als Geschichtsdarstellung, sondern als Glaubensaussagen
über das Wesen der Welt und des Menschen und über deren Beziehung zu
Gott zu verstehen. Die Geschichte der Erzväter und der Söhne Jakobs sind
zwar in Einzelheiten ebenfalls nicht historisch nachprüfbar, doch
stimmen die politischen, sozialen, rechtlichen, kulturellen und
religiösen Zustände, die hier geschildert werden, weithin mit den
Verhältnissen überein, wie sie die heutige Forschung für Palästina und
seine Umwelt in der Zeit vor Mose, d. h. für die sog. Mittlere und Späte
Bronzezeit, erschlossen hat. Man darf die Geschichtsdarstellung des
Buches Genesis nicht an der modernen Geschichtsschreibung messen,
sondern man muss sie als antike Geschichtsschreibung und als
theologische Geschichtsdeutung beurteilen. Der die Verfasser des Buches
inspirierende Gott wollte uns nicht genaue Einzelheiten über die
Entstehung der Welt und des Menschen mitteilen oder uns über den exakten
Verlauf der Patriarchengeschichte unterrichten. Vielmehr wollte er an
den erzählten Begebenheiten sein Heilsangebot und die typischen
Reaktionen des Menschen darauf aufzeigen. Damit wollte er deutlich
machen, dass er auch Sünder zu Trägern und Vermittlern von Segen und
Heil erwählt.\\
\\

<<verses>>

<<v1>>
** Die Anfänge: 1,1 - 11,9
:PROPERTIES:
   :CUSTOM_ID: die-anfänge-11---119
   :ID:       die-anfänge-11---119
   :END:
*** Die Erschaffung der Welt: 1,1 - 2,4a
:PROPERTIES:
     :CUSTOM_ID: die-erschaffung-der-welt-11---24a
     :ID:       die-erschaffung-der-welt-11---24a
     :END:
1 Im Anfang schuf Gott Himmel und Erde; [fn:1] [fn:2]

<<v2>>
2 die Erde aber war wüst und wirr, Finsternis lag über der Urflut und
Gottes Geist schwebte über dem Wasser.

<<v3>>
3 Gott sprach: Es werde Licht. Und es wurde Licht.

<<v4>>
4 Gott sah, dass das Licht gut war. Gott schied das Licht von der
Finsternis

<<v5>>
5 und Gott nannte das Licht Tag und die Finsternis nannte er Nacht. Es
wurde Abend und es wurde Morgen: erster Tag.

<<v6>>
6 Dann sprach Gott: Ein Gewölbe entstehe mitten im Wasser und scheide
Wasser von Wasser. [fn:3]

<<v7>>
7 Gott machte also das Gewölbe und schied das Wasser unterhalb des
Gewölbes vom Wasser oberhalb des Gewölbes. So geschah es

<<v8>>
8 und Gott nannte das Gewölbe Himmel. Es wurde Abend und es wurde
Morgen: zweiter Tag.

<<v9>>
9 Dann sprach Gott: Das Wasser unterhalb des Himmels sammle sich an
einem Ort, damit das Trockene sichtbar werde. So geschah es.

<<v10>>
10 Das Trockene nannte Gott Land und das angesammelte Wasser nannte er
Meer. Gott sah, dass es gut war.

<<v11>>
11 Dann sprach Gott: Das Land lasse junges Grün wachsen, alle Arten von
Pflanzen, die Samen tragen, und von Bäumen, die auf der Erde Früchte
bringen mit ihrem Samen darin. So geschah es.

<<v12>>
12 Das Land brachte junges Grün hervor, alle Arten von Pflanzen, die
Samen tragen, alle Arten von Bäumen, die Früchte bringen mit ihrem Samen
darin. Gott sah, dass es gut war.

<<v13>>
13 Es wurde Abend und es wurde Morgen: dritter Tag.

<<v14>>
14 Dann sprach Gott: Lichter sollen am Himmelsgewölbe sein, um Tag und
Nacht zu scheiden. Sie sollen Zeichen sein und zur Bestimmung von
Festzeiten, von Tagen und Jahren dienen; [fn:4]

<<v15>>
15 sie sollen Lichter am Himmelsgewölbe sein, die über die Erde hin
leuchten. So geschah es.

<<v16>>
16 Gott machte die beiden großen Lichter, das größere, das über den Tag
herrscht, das kleinere, das über die Nacht herrscht, auch die Sterne.

<<v17>>
17 Gott setzte die Lichter an das Himmelsgewölbe, damit sie über die
Erde hin leuchten,

<<v18>>
18 über Tag und Nacht herrschen und das Licht von der Finsternis
scheiden. Gott sah, dass es gut war.

<<v19>>
19 Es wurde Abend und es wurde Morgen: vierter Tag.

<<v20>>
20 Dann sprach Gott: Das Wasser wimmle von lebendigen Wesen und Vögel
sollen über dem Land am Himmelsgewölbe dahinfliegen.

<<v21>>
21 Gott schuf alle Arten von großen Seetieren und anderen Lebewesen, von
denen das Wasser wimmelt, und alle Arten von gefiederten Vögeln. Gott
sah, dass es gut war.

<<v22>>
22 Gott segnete sie und sprach: Seid fruchtbar und vermehrt euch und
bevölkert das Wasser im Meer und die Vögel sollen sich auf dem Land
vermehren.

<<v23>>
23 Es wurde Abend und es wurde Morgen: fünfter Tag.

<<v24>>
24 Dann sprach Gott: Das Land bringe alle Arten von lebendigen Wesen
hervor, von Vieh, von Kriechtieren und von Tieren des Feldes. So geschah
es.

<<v25>>
25 Gott machte alle Arten von Tieren des Feldes, alle Arten von Vieh und
alle Arten von Kriechtieren auf dem Erdboden. Gott sah, dass es gut war.

<<v26>>
26 Dann sprach Gott: Lasst uns Menschen machen als unser Abbild, uns
ähnlich. Sie sollen herrschen über die Fische des Meeres, über die Vögel
des Himmels, über das Vieh, über die ganze Erde und über alle
Kriechtiere auf dem Land. [fn:5]

<<v27>>
27 Gott schuf also den Menschen als sein Abbild; als Abbild Gottes schuf
er ihn. Als Mann und Frau schuf er sie. [fn:6]

<<v28>>
28 Gott segnete sie und Gott sprach zu ihnen: Seid fruchtbar und
vermehrt euch, bevölkert die Erde, unterwerft sie euch und herrscht über
die Fische des Meeres, über die Vögel des Himmels und über alle Tiere,
die sich auf dem Land regen.

<<v29>>
29 Dann sprach Gott: Hiermit übergebe ich euch alle Pflanzen auf der
ganzen Erde, die Samen tragen, und alle Bäume mit samenhaltigen
Früchten. Euch sollen sie zur Nahrung dienen. [fn:7]

<<v30>>
30 Allen Tieren des Feldes, allen Vögeln des Himmels und allem, was sich
auf der Erde regt, was Lebensatem in sich hat, gebe ich alle grünen
Pflanzen zur Nahrung. So geschah es.

<<v31>>
31 Gott sah alles an, was er gemacht hatte: Es war sehr gut. Es wurde
Abend und es wurde Morgen: der sechste Tag.

* Footnotes

[fn:1] 2,4b [[file:Gen_2.org::v4b][Gen 2,4b]]; Joh 1,1-3 [[file:~/RoamNotes/EUe-RoundtripHTML/nt/Joh_1.org::v1][Joh 1,1-3]]

[fn:2] 1-2,4a: Im Gegensatz zu Schöpfungsvorstellungen der
Umwelt Israels, nach denen die Elemente des Kosmos Gottheiten sind und
durch göttliche Zeugungen entstanden, lehrt hier die priesterliche
Tradition Israels, dass alle Dinge, Pflanzen, Tiere und der Mensch durch
Gottes Wort entstanden sind. Dabei setzt sie die antike Weltsicht
voraus, stellt die Bewegungen und Veränderungen am gestirnten Himmel und
auf der Erde so dar, wie sie sich dem Augenschein zeigen, und setzt
voraus, dass Gott, von dem Israel die Siebentagewoche mit dem Sabbat als
Ruhetag im Bundesgesetz erhalten hat, auch selbst sich bei der
Erschaffung der Welt an das Schema der Siebentagewoche gehalten hat.
Durch die Erschaffung des Menschen nach Gottes Ebenbild, das letzte
Schöpfungswerk, wird der Mensch als Krone und Herr der Schöpfung
herausgehoben.

[fn:3] Nach dem Weltbild seiner Zeit stellt sich der Verfasser
das Firmament als eine Halbkugel aus festem Stoff vor, die das
Chaoswasser so teilt, dass über ihr und unter ihr Wasser ist, wobei vom
oberen Wasser durch Öffnungen im Firmament der Regen herabströmt.

[fn:4] Ps 136,7-9 [[file:Ps_139.org::v7][Ps 139,7-9]]

[fn:5] 2,7 [[file:Gen_2.org::v7][Gen 2,7]]; Ps 8,6-9 [[file:Ps_8.org::v6][Ps 8,6-9]]; Eph 4,24 [[file:~/RoamNotes/EUe-RoundtripHTML/nt/Eph_4.org::v24][Eph 4,24]]; Kol 3,10 [[file:~/RoamNotes/EUe-RoundtripHTML/nt/Kol_3.org::v10][Kol 3,10]]

[fn:6] 5,1f [[file:Gen_5.org::v1][Gen 5,1f]]

[fn:7] 9,3 [[file:Gen_9.org::v3][Gen 9,3]]
