:PROPERTIES:
:ID:       da4aa630-851c-4c23-87a9-923d44669f6a
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Amos* -- [[file:Am_1.html][1]]
[[file:Am_2.html][2]] [[file:Am_3.html][3]] *4* [[file:Am_5.html][5]]
[[file:Am_6.html][6]] ... [[file:Am_9.html][9]]

--------------

* Am 4
  :PROPERTIES:
  :CUSTOM_ID: am-4
  :END:

<<verses>>

<<v1>>
**** Die Unterdrückung der Armen: 4,1-3
     :PROPERTIES:
     :CUSTOM_ID: die-unterdrückung-der-armen-41-3
     :END:
1 Hört dieses Wort, /\\
 ihr Baschankühe auf dem Berg von Samaria, die ihr die Schwachen
unterdrückt /\\
 und die Armen zermalmt und zu euren Männern sagt: /\\
 Schafft Wein herbei, wir wollen trinken. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Bei seiner Heiligkeit /\\
 hat Gott, der Herr, geschworen: Seht, Tage kommen über euch, /\\
 da holt man euch mit Fleischerhaken weg, und was dann noch von euch
übrig ist, /\\
 mit Angelhaken.\\
\\

<<v3>>
3 Ihr müsst durch die Breschen der Mauern hinaus, /\\
 eine hinter der andern; man jagt euch dem Hermon zu - /\\
 Spruch des Herrn.\\
\\

<<v4>>
**** Umkehr - nicht äußerlicher Kult: 4,4 - 5,9
     :PROPERTIES:
     :CUSTOM_ID: umkehr---nicht-äußerlicher-kult-44---59
     :END:
4 Kommt nach Bet-El und sündigt, /\\
 kommt nach Gilgal und sündigt noch mehr! Bringt jeden Morgen eure
Schlachtopfer herbei, /\\
 bringt am dritten Tag euren Zehnten! ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Verbrennt als Dankopfer gesäuertes Brot! /\\
 Ruft zu freiwilligen Opfern auf, /\\
 verkündet es laut, damit man es hört! Denn so gefällt es euch, ihr
Söhne Israels - /\\
 Spruch Gottes, des Herrn.\\
\\

<<v6>>
6 Ich ließ euch hungern in all euren Städten, /\\
 ich gab euch kein Brot mehr in all euren Dörfern und dennoch seid ihr
nicht umgekehrt zu mir - /\\
 Spruch des Herrn. ^{[[#fn3][3]]}\\
\\

<<v7>>
7 Ich versagte euch den Regen /\\
 drei Monate vor der Ernte. Über der einen Stadt ließ ich es regnen, /\\
 über der anderen nicht; das eine Feld bekam Regen, /\\
 das andere nicht, sodass es verdorrte.\\
\\

<<v8>>
8 Zwei, drei Städte taumelten zu der einen; /\\
 sie wollten Wasser trinken und blieben doch durstig. Und dennoch seid
ihr nicht umgekehrt zu mir - /\\
 Spruch des Herrn.\\
\\

<<v9>>
9 Ich vernichtete euer Getreide durch Rost und Mehltau, /\\
 ich verwüstete eure Gärten und Weinberge; eure Feigenbäume und eure
Ölbäume /\\
 fraßen die Heuschrecken kahl. Und dennoch seid ihr nicht umgekehrt zu
mir - /\\
 Spruch des Herrn. ^{[[#fn4][4]]}\\
\\

<<v10>>
10 Ich ließ die Pest gegen euch los wie gegen Ägypten, /\\
 eure jungen Männer tötete ich mit dem Schwert /\\
 und gab eure Pferde (den Feinden) zur Beute; den Leichengestank von
eurem Heerlager /\\
 ließ ich euch in die Nase steigen. Und dennoch seid ihr nicht umgekehrt
zu mir - /\\
 Spruch des Herrn. ^{[[#fn5][5]]}\\
\\

<<v11>>
11 Ich brachte über euch eine gewaltige Zerstörung /\\
 wie die, die Gott einst über Sodom und Gomorra verhängte; ihr wart wie
ein Holzscheit, /\\
 das man aus dem Feuer herausholt. Und dennoch seid ihr nicht umgekehrt
zu mir - /\\
 Spruch des Herrn. ^{[[#fn6][6]]}\\
\\

<<v12>>
12 Darum will ich dir all das antun, Israel, /\\
 und weil ich dir all das antun werde, /\\
 mach dich bereit, deinem Gott gegenüberzutreten.\\
\\

<<v13>>
13 Denn siehe, er formt die Berge, /\\
 er erschafft den Wind, er verkündet den Menschen, was er im Sinn hat;
/\\
 er macht das Morgenrot und die Finsternis, er schreitet über die Höhen
der Erde dahin - /\\
 Jahwe, Gott der Heere, ist sein Name.\\
\\

^{[[#fnm1][1]]} Die Frauen der Oberschicht werden mit den üppigen Kühen
des Baschan, eines Weidegebiets im nördlichen Ostjordanland, verglichen.

^{[[#fnm2][2]]} ℘ Hos 4,15; 12,12

^{[[#fnm3][3]]} ℘ Lev 26,14-39

^{[[#fnm4][4]]} ℘ Hag 2,17; Joël 1,4

^{[[#fnm5][5]]} ℘ Ex 9,3

^{[[#fnm6][6]]} ℘ Gen 19,24; Sach 3,2
