:PROPERTIES:
:ID:       9f0f061a-ac93-411c-8b38-ca66bf75b387
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Amos* -- [[file:Am_1.html][1]] ...
[[file:Am_6.html][6]] [[file:Am_7.html][7]] *8* [[file:Am_9.html][9]]

--------------

* Am 8
  :PROPERTIES:
  :CUSTOM_ID: am-8
  :END:

<<verses>>

<<v1>>
**** Die vierte Vision: Der Obstkorb: 8,1-3
     :PROPERTIES:
     :CUSTOM_ID: die-vierte-vision-der-obstkorb-81-3
     :END:
1 Dies zeigte mir Gott, der Herr, in einer Vision: Ich sah einen Korb
mit reifem Obst.

<<v2>>
2 Er fragte: Was siehst du, Amos? Ich antwortete: Einen Korb mit reifem
Obst. Da sagte der Herr zu mir: Mein Volk Israel ist reif für das Ende.
Ich verschone es nicht noch einmal. ^{[[#fn1][1]]}

<<v3>>
3 An jenem Tag werden die Sängerinnen des Palastes Klagelieder singen -
Spruch des Herrn. Alles ist voller Leichen, überall wirft man sie hin.
Still!\\
\\

<<v4>>
**** Gegen die Ausbeutung: 8,4-14
     :PROPERTIES:
     :CUSTOM_ID: gegen-die-ausbeutung-84-14
     :END:
4 Hört dieses Wort, die ihr die Schwachen verfolgt /\\
 und die Armen im Land unterdrückt. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Ihr sagt: Wann ist das Neumondfest vorbei? /\\
 Wir wollen Getreide verkaufen. Und wann ist der Sabbat vorbei? /\\
 Wir wollen den Kornspeicher öffnen, das Maß kleiner und den Preis
größer machen /\\
 und die Gewichte fälschen. ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Wir wollen mit Geld die Hilflosen kaufen, /\\
 für ein paar Sandalen die Armen. Sogar den Abfall des Getreides /\\
 machen wir zu Geld.\\
\\

<<v7>>
7 Beim Stolz Jakobs hat der Herr geschworen: /\\
 Keine ihrer Taten werde ich jemals vergessen. ^{[[#fn4][4]]}\\
\\

<<v8>>
8 Sollte deshalb die Erde nicht beben, /\\
 sollten nicht alle ihre Bewohner voll Trauer sein? Sollte nicht die
ganze Erde sich heben wie der Nil: /\\
 [aufgewühlt sein] und sich wieder senken wie der Strom von Ägypten?
^{[[#fn5][5]]}\\
\\

<<v9>>
9 An jenem Tag - Spruch Gottes, des Herrn - /\\
 lasse ich am Mittag die Sonne untergehen und breite am helllichten Tag
/\\
 über die Erde Finsternis aus.\\
\\

<<v10>>
10 Ich verwandle eure Feste in Trauer /\\
 und all eure Lieder in Totenklage. Ich lege allen ein Trauergewand um
/\\
 und schere alle Köpfe kahl. Ich bringe Trauer über das Land /\\
 wie die Trauer um den einzigen Sohn und das Ende wird sein /\\
 wie der bittere Tag (des Todes). ^{[[#fn6][6]]}\\
\\

<<v11>>
11 Seht, es kommen Tage - Spruch Gottes, des Herrn -, /\\
 da schicke ich den Hunger ins Land, nicht den Hunger nach Brot, nicht
Durst nach Wasser, /\\
 sondern nach einem Wort des Herrn.\\
\\

<<v12>>
12 Dann wanken die Menschen von Meer zu Meer, /\\
 sie ziehen von Norden nach Osten, um das Wort des Herrn zu suchen; /\\
 doch sie finden es nicht.\\
\\

<<v13>>
13 An jenem Tag werden die schönen jungen Mädchen /\\
 und die jungen Männer ohnmächtig vor Durst, ^{[[#fn7][7]]}\\
\\

<<v14>>
14 alle, die beim Götzenbild von Samaria schwören und sagen: /\\
 So wahr dein Gott lebt, Dan, /\\
 so wahr dein Geliebter lebt, Beerscheba!, sie werden zu Boden stürzen
/\\
 und sich nicht mehr erheben. ^{[[#fn8][8]]}\\
\\

^{[[#fnm1][1]]} ℘ Offb 14,15 -19

^{[[#fnm2][2]]} ℘ 2,6-8

^{[[#fnm3][3]]} ℘ Dtn 25,13; Mi 6,10f

^{[[#fnm4][4]]} Stolz Jakobs: wahrscheinlich ist das Gelobte Land
gemeint.

^{[[#fnm5][5]]} ℘ 9,5

^{[[#fnm6][6]]} ℘ Hos 2,13; Jes 3,24; Jer 6,26

^{[[#fnm7][7]]} ℘ Sach 9,17

^{[[#fnm8][8]]} beim Götzenbild, wörtlich: bei der Sünde (vgl. 2 Kön
17,30).
