:PROPERTIES:
:ID:       cb6aac7e-5548-44e2-8406-441f17b92aa0
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Amos* -- [[file:Am_1.html][1]] ...
[[file:Am_7.html][7]] [[file:Am_8.html][8]] *9*

--------------

* Am 9
  :PROPERTIES:
  :CUSTOM_ID: am-9
  :END:

<<verses>>

<<v1>>
**** Die fünfte Vision: Der Untergang des Tempels und des Volkes: 9,1-6
     :PROPERTIES:
     :CUSTOM_ID: die-fünfte-vision-der-untergang-des-tempels-und-des-volkes-91-6
     :END:
1 Ich sah den Herrn beim Altar stehen. /\\
 Er sagte: Zerschlag den Knauf der Säule, /\\
 sodass die Tragbalken zittern. Ich zerschmettere allen den Kopf. /\\
 Was dann von ihnen noch übrig ist, /\\
 töte ich mit dem Schwert. Keiner von ihnen kann entfliehen, /\\
 keiner entrinnt, keiner entkommt. ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v2>>
2 Wenn sie in die Totenwelt einbrechen: /\\
 meine Hand packt sie auch dort. Und wenn sie zum Himmel aufsteigen: /\\
 ich hole sie von dort herunter. ^{[[#fn3][3]]}\\
\\

<<v3>>
3 Wenn sie sich auf dem Gipfel des Karmel verstecken: /\\
 ich spüre sie dort auf und ergreife sie. Wenn sie sich vor mir auf dem
Grund des Meeres verbergen, /\\
 dann gebiete ich der Seeschlange, sie zu beißen.\\
\\

<<v4>>
4 Und wenn sie vor ihren Feinden her in die Gefangenschaft ziehen, /\\
 dann befehle ich dort dem Schwert, sie zu töten. Ich habe meine Augen
auf sie gerichtet /\\
 zu ihrem Unheil, nicht zu ihrem Glück.\\
\\

<<v5>>
5 Gott, der Herr der Heere, /\\
 er berührt die Erde, sodass sie vergeht /\\
 und all ihre Bewohner voll Trauer sind, sodass die ganze Erde sich hebt
wie der Nil /\\
 und sich senkt wie der Strom von Ägypten. ^{[[#fn4][4]]}\\
\\

<<v6>>
6 Er erbaut seine Hallen im Himmel /\\
 und gründet sein Gewölbe auf die Erde; er ruft das Wasser des Meeres
/\\
 und gießt es aus über die Erde - /\\
 Jahwe ist sein Name. ^{[[#fn5][5]]}\\
\\

<<v7>>
** Gericht und Heil: 9,7-15
   :PROPERTIES:
   :CUSTOM_ID: gericht-und-heil-97-15
   :END:
**** Erwählung und Gericht: 9,7-10
     :PROPERTIES:
     :CUSTOM_ID: erwählung-und-gericht-97-10
     :END:
7 Seid ihr für mich mehr als die Kuschiter, ihr Israeliten? - /\\
 Spruch des Herrn. Wohl habe ich Israel aus Ägypten heraufgeführt, /\\
 aber ebenso die Philister aus Kaftor /\\
 und die Aramäer aus Kir. ^{[[#fn6][6]]}\\
\\

<<v8>>
8 Die Augen Gottes, des Herrn, /\\
 sind auf das sündige Königreich gerichtet. Ich lasse es vom Erdboden
verschwinden; /\\
 doch ich werde das Haus Jakob nicht völlig vernichten - /\\
 Spruch des Herrn. ^{[[#fn7][7]]}\\
\\

<<v9>>
9 Ja, seht, ich selbst gebe den Befehl, /\\
 ich schüttle unter allen Völkern das Haus Israel, wie man (Korn)
schüttelt in einem Sieb, /\\
 ohne dass ein Stein zu Boden fällt.\\
\\

<<v10>>
10 Alle Sünder meines Volkes /\\
 sollen durch das Schwert umkommen, alle, die sagen: Das Unheil erreicht
uns nicht, /\\
 es holt uns nicht ein. ^{[[#fn8][8]]}\\
\\

<<v11>>
**** Die Verheißung des künftigen Heils: 9,11-15
     :PROPERTIES:
     :CUSTOM_ID: die-verheißung-des-künftigen-heils-911-15
     :END:
11 An jenem Tag richte ich die zerfallene Hütte Davids wieder auf /\\
 und bessere ihre Risse aus, ich richte ihre Trümmer auf /\\
 und stelle alles wieder her /\\
 wie in den Tagen der Vorzeit, ^{[[#fn9][9]]}\\
\\

<<v12>>
12 damit sie den Rest von Edom unterwerfen /\\
 und alle Völker, über denen mein Name ausgerufen ist - /\\
 Spruch des Herrn, der das alles bewirkt. ^{[[#fn10][10]]}\\
\\

<<v13>>
13 Seht, es kommen Tage - Spruch des Herrn -, /\\
 da folgt der Pflüger dem Schnitter auf dem Fuß /\\
 und der Keltertreter dem Sämann; da triefen die Berge von Wein /\\
 und alle Hügel fließen über. ^{[[#fn11][11]]}\\
\\

<<v14>>
14 Dann wende ich das Geschick meines Volkes Israel. /\\
 Sie bauen die verwüsteten Städte wieder auf und wohnen darin; sie
pflanzen Weinberge und trinken den Wein, /\\
 sie legen Gärten an und essen die Früchte. ^{[[#fn12][12]]}\\
\\

<<v15>>
15 Und ich pflanze sie ein in ihrem Land /\\
 und nie mehr werden sie ausgerissen aus ihrem Land, das ich ihnen
gegeben habe, spricht der Herr, dein Gott.\\
\\

^{[[#fnm1][1]]} ℘ 2,14-16

^{[[#fnm2][2]]} Text nicht ganz klar.

^{[[#fnm3][3]]} ℘ Ps 139,7-12; Jer 23,23f

^{[[#fnm4][4]]} ℘ 8,8

^{[[#fnm5][5]]} ℘ 5,8

^{[[#fnm6][6]]} Kaftor ist wahrscheinlich Kreta, möglicherweise auch
Kappadozien (vgl. Jer 47,4). - Kir: in Mesopotamien.

^{[[#fnm7][7]]} ℘ 3,12

^{[[#fnm8][8]]} ℘ 6,1-6; Jes 28,15

^{[[#fnm9][9]]} ℘ Apg 15,16f

^{[[#fnm10][10]]} ℘ Num 24,18

^{[[#fnm11][11]]} ℘ Lev 26,5

^{[[#fnm12][12]]} ℘ 5,11
