:PROPERTIES:
:ID:       b438fbfc-18fb-4aa9-8a83-2f9ec68bd20b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Baruch* -- [[file:Bar_1.html][1]] ...
[[file:Bar_4.html][4]] [[file:Bar_5.html][5]] *6*

--------------

* Bar 6
  :PROPERTIES:
  :CUSTOM_ID: bar-6
  :END:

<<verses>>

<<v1--1>>
** Der Brief des Jeremia: 6,1-72
   :PROPERTIES:
   :CUSTOM_ID: der-brief-des-jeremia-61-72
   :END:
**** Einleitung: 6,1-6
     :PROPERTIES:
     :CUSTOM_ID: einleitung-61-6
     :END:
1--1 Abschrift des Briefes, den Jeremia an jene gesandt hat, die vom
König der Babylonier als Gefangene nach Babel weggeführt werden sollten;
darin teilte er ihnen mit, was Gott ihm aufgetragen hatte.
^{[[#fn1][1]][[#fn2][2]]}

<<v1>>
1 Wegen der Sünden, die ihr gegen Gott begangen habt, werdet ihr von
Nebukadnezzar, dem König der Babylonier, als Gefangene nach Babel
geführt.

<<v2>>
2 Seid ihr dann nach Babel gekommen, so müsst ihr dort viele Jahre
bleiben, für lange Zeit, bis zu sieben Generationen; danach führe ich
euch von dort in Frieden wieder heraus.

<<v3>>
3 Nun werdet ihr in Babel Götterbilder aus Silber, Gold und Holz sehen,
die man auf den Schultern trägt und die den Völkern Furcht einflößen.
^{[[#fn3][3]]}

<<v4>>
4 Hütet euch dann, euch den Fremden anzugleichen und euch von Furcht vor
diesen Göttern erfassen zu lassen,

<<v5>>
5 wenn ihr seht, wie die Menge sich vor und hinter ihnen niederwirft;
sprecht vielmehr im Herzen: Herr, dir allein gebührt Anbetung.

<<v6>>
6 Denn mein Engel ist bei euch; er wird über euer Leben wachen.
^{[[#fn4][4]]}\\
\\

<<v7>>
**** Die Nichtigkeit der Götzenbilder: 6,7-72
     :PROPERTIES:
     :CUSTOM_ID: die-nichtigkeit-der-götzenbilder-67-72
     :END:
7 Ein Handwerker hat ihnen eine glatte Zunge angefertigt; sie selbst
wurden mit Gold und Silber überzogen; doch sind sie Fälschungen und
können nicht reden. ^{[[#fn5][5]]}

<<v8>>
8 Wie für ein Mädchen, das Schmuck liebt, nimmt man Gold

<<v9>>
9 und fertigt Kronen für die Häupter ihrer Götter. Manchmal nehmen aber
die Priester Gold und Silber heimlich von ihren Göttern weg und
verwenden es für sich selber; sie geben davon auch den Dirnen in der
Kammer. ^{[[#fn6][6]][[#fn7][7]]}

<<v10>>
10 Man schmückt sie auch, die Götter aus Silber, Gold und Holz, mit
Gewändern wie Menschen. Diese Götter können sich aber nicht vor Schmutz
und Wurmfraß schützen. ^{[[#fn8][8]][[#fn9][9]]}

<<v11>>
11 Sie sind in Purpurgewänder gehüllt

<<v12>>
12 und doch muss man ihnen den Staub aus dem Gesicht wischen, der im
Tempel aufwirbelt und sich dick auf sie legt.

<<v13>>
13 Sogar ein Zepter trägt ein solcher Gott, wie ein Mann, der das Land
regiert; doch kann er niemand töten, der sich gegen ihn verfehlt.

<<v14>>
14 Er hat in der Rechten ein Schwert oder eine Streitaxt, kann aber
nicht einmal sich selbst vor Krieg oder Räubern retten. So zeigen sie
deutlich, dass sie keine Götter sind. Fürchtet sie also nicht!

<<v15>>
15 Wie ein zerbrochenes Tongefäß unbrauchbar wird,

<<v16>>
16 so geht es auch mit ihren Göttern, die in ihren Tempeln aufgestellt
sind: Ihre Augen sind voll vom Staub, den die Füße der Besucher
hineintragen.

<<v17>>
17 Und wie die Höfe rings verschlossen sind, sobald ein Mann, der sich
am König vergangen hat, zur Hinrichtung abgeführt werden soll, so
sichern die Priester die Tempel der Götter mit Türen, Schlössern und
Riegeln, damit sie nicht von Räubern geplündert werden.

<<v18>>
18 Die Priester zünden Lichter an, mehr sogar als für sich selbst, doch
die Götter können keines davon sehen.

<<v19>>
19 Es geht ihnen wie einem Balken am Tempel: Ihr Inneres wird, wie man
sagt, zerfressen. Sie aber bemerken nicht die Würmer, die aus der Erde
kommen und sie selbst samt ihren Gewändern aufzehren.

<<v20>>
20 Ihre Gesichter sind geschwärzt vom Rauch, der im Tempel aufsteigt.

<<v21>>
21 Auf ihrem Körper und auf ihrem Kopf lassen sich Fledermäuse,
Schwalben und andere Vögel nieder, ebenso auch Katzen.

<<v22>>
22 Daran erkennt ihr, dass sie keine Götter sind. Fürchtet sie also
nicht!

<<v23>>
23 Sie sind mit Gold überzogen, damit sie schön aussehen; wenn aber
niemand den Schmutz wegputzt, glänzen sie nicht. Nicht einmal, als sie
gegossen wurden, spürten sie es.

<<v24>>
24 Jeden Preis zahlte man für sie, obwohl sie keinen Lebensatem
besitzen.

<<v25>>
25 Da sie ihre Füße nicht gebrauchen können, werden sie auf den
Schultern getragen und zeigen so den Menschen ihren eigenen Unwert. Auch
ihre Diener müssen sich schämen; ^{[[#fn10][10]]}

<<v26>>
26 denn (der Götze) muss von ihnen aufgestellt werden, damit er nicht zu
Boden fällt. Stellt man ihn aufrecht hin, so kann er sich selbst nicht
bewegen; steht er schief, kann er sich nicht aufrichten. Vielmehr setzt
man ihnen die Gaben vor wie den Toten. ^{[[#fn11][11]]}

<<v27>>
27 Mit ihren Opfern aber treiben ihre Priester Missbrauch und verkaufen
sie. Nicht besser handeln ihre Frauen: Sie pökeln davon ein, aber einem
Armen oder Schwachen geben sie nichts.

<<v28>>
28 Sogar unreine Frauen und Wöchnerinnen berühren ihre Opfer. Daran
erkennt ihr, dass sie keine Götter sind. Fürchtet sie also nicht!
^{[[#fn12][12]]}

<<v29>>
29 Wie könnte man sie Götter nennen? Sogar Frauen bringen ihnen Opfer
dar, diesen Göttern aus Silber, Gold und Holz. ^{[[#fn13][13]]}

<<v30>>
30 In ihren Tempeln hocken die Priester, das Gewand zerrissen, Kopf und
Bart geschoren und das Haupt entblößt.

<<v31>>
31 Sie heulen und schreien vor ihren Göttern wie andere beim Totenmahl.
^{[[#fn14][14]]}

<<v32>>
32 Von ihren Gewändern nehmen die Priester und kleiden damit ihre Frauen
und Kinder.

<<v33>>
33 Ob jemand diesen Göttern Böses oder Gutes antut, sie sind nicht
imstande, es zu vergelten. Einen König können sie weder einsetzen noch
absetzen.

<<v34>>
34 Ebenso wenig können sie Reichtum oder auch nur Geld verschaffen. Hat
ihnen jemand ein Gelübde gemacht, erfüllt es aber nicht, so können sie
keine Rechenschaft fordern.

<<v35>>
35 Sie können keinen Menschen vom Tod erretten noch einen Schwachen dem
Starken entreißen.

<<v36>>
36 Einen Blinden können sie nicht sehend machen, einen Bedrängten nicht
befreien.

<<v37>>
37 Mit der Witwe haben sie kein Mitleid, dem Waisenkind helfen sie
nicht. ^{[[#fn15][15]]}

<<v38>>
38 Den Steinen aus den Bergen gleichen die hölzernen, mit Gold und
Silber überzogenen Götter. Wer sie verehrt, wird zuschanden.

<<v39>>
39 Wie kann einer da glauben oder behaupten, sie seien wirklich Götter?

<<v40>>
40 Ihrer Ehre schaden die Chaldäer sogar selbst. Sehen sie nämlich einen
Stummen, der nicht sprechen kann, so bringen sie ihn zu Bel und bitten,
dass er die Sprache erhalte, als ob Bel ihn auch nur wahrnehmen könnte.
^{[[#fn16][16]]}

<<v41>>
41 Und obwohl sie das wissen, bringen sie es doch nicht über sich, die
Götter zu verlassen; sie haben ja keinen Verstand.

<<v42>>
42 Die Frauen aber sitzen, mit Schnüren umwunden, an den Wegen und
lassen Kleie in Rauch aufgehen. ^{[[#fn17][17]][[#fn18][18]]}

<<v43>>
43 Sobald nun eine aus ihrer Mitte von einem Vorübergehenden mitgenommen
worden ist und sich ihm hingegeben hat, schmäht sie ihre Nachbarin, weil
diese nicht gleich ihr für würdig befunden und ihre Schnur noch nicht
zerrissen wurde.

<<v44>>
44 Was immer bei diesen Göttern geschieht, ist Trug. Wie kann einer da
glauben oder behaupten, dass sie wirklich Götter seien?

<<v45>>
45 Von Handwerkern und Goldschmieden sind sie verfertigt. Sie werden
nichts anderes, als was sie nach dem Willen der Künstler werden sollten.

<<v46>>
46 Ihre Hersteller erreichen selbst kein hohes Alter;

<<v47>>
47 wie sollten da ihre Erzeugnisse Götter sein? Nein, nur Trug und
Schande hinterlassen sie ihren Nachkommen.

<<v48>>
48 Nähern sich nämlich Krieg und Unheil diesen Göttern, dann beraten die
Priester miteinander, wo sie sich mit ihnen verstecken können.

<<v49>>
49 Wie sollte man da nicht merken, dass sie keine Götter sind, da sie
sich selbst weder vor Krieg noch vor Unheil retten können?

<<v50>>
50 Sie sind ja nur hölzerne, mit Gold und Silber überzogene Gebilde; man
wird nach alldem erkennen, dass sie Trug sind. Allen Völkern und Königen
wird es dann offenbar, dass jene keine Götter sind, sondern Werke von
Menschenhand, und dass ihnen keine göttliche Wirkkraft innewohnt.

<<v51>>
51 Wer sieht da nicht, dass sie keine Götter sind? ^{[[#fn19][19]]}

<<v52>>
52 Sie können weder einen König im Land einsetzen noch den Menschen
Regen spenden. ^{[[#fn20][20]]}

<<v53>>
53 Sie halten nicht Gericht bei ihnen und befreien keinen, dem Unrecht
geschah; denn sie sind machtlos

<<v54>>
54 wie die Krähen zwischen Himmel und Erde. Ergreift gar Feuer den
Tempel der hölzernen, mit Gold und Silber überzogenen Götter, dann
fliehen zwar ihre Priester und retten sich, sie selbst aber verbrennen
darin wie die Balken.

<<v55>>
55 Keinem König und keinem Feind bieten sie Widerstand.

<<v56>>
56 Wie kann einer da annehmen oder glauben, dass sie Götter sind? Weder
vor Dieben noch vor Räubern können sie sich retten, diese hölzernen, mit
Silber und Gold überzogenen Götter.

<<v57>>
57 Jene sind stärker und nehmen ihnen das Gold und Silber ringsum ab,
samt den Gewändern, die ihnen umgelegt sind, und machen sich damit fort,
ohne dass die Götter auch nur sich selber helfen könnten.

<<v58>>
58 Besser ist darum ein König, der seine Stärke zeigt, besser ein
nützliches Hausgerät, das der Besitzer brauchen kann, als solche
trügerischen Götter; besser im Haus eine Tür, die das, was drinnen ist,
schützt, als solche trügerischen Götter; besser im Königspalast eine
hölzerne Säule als solche trügerischen Götter.

<<v59>>
59 Sonne, Mond und Sterne, die bestellt sind, um als Leuchten zu nützen,
gehorchen willig. ^{[[#fn21][21]]}

<<v60>>
60 Ebenso ist auch der Blitz, wenn er aufleuchtet, schön anzusehen.
Genauso ist es beim Wind, der über das ganze Land weht.

<<v61>>
61 Wenn den Wolken von Gott befohlen wird, über die ganze Erde
dahinzuziehen, so vollführen sie den Auftrag.

<<v62>>
62 Wird endlich das Feuer von oben ausgesandt, um Berge und Wälder zu
verzehren, so tut es, was befohlen war. All dem kommen aber diese Götter
weder an Schönheit gleich noch an Kraft.

<<v63>>
63 Daher kann man weder glauben noch behaupten, dass sie wirklich Götter
sind; sie sind ja nicht imstande, Gericht zu halten oder den Menschen
Gutes zu tun.

<<v64>>
64 Da ihr nun wisst, dass sie keine Götter sind, so fürchtet sie nicht!

<<v65>>
65 Sie können den Königen weder fluchen noch sie segnen.

<<v66>>
66 Sie lassen bei den Völkern keine Zeichen am Himmel erscheinen. Sie
können nicht strahlen wie die Sonne noch leuchten wie der Mond.

<<v67>>
67 Die Tiere sind besser daran als jene; denn sie können an einen
schützenden Ort fliehen und sich selber helfen.

<<v68>>
68 So ist uns auf gar keine Weise sichtbar, dass sie Götter sind. Darum
fürchtet sie nicht!

<<v69>>
69 Wie im Gurkenfeld eine Vogelscheuche, die nichts behütet, so sind
ihre hölzernen, mit Gold und Silber überzogenen Götter. ^{[[#fn22][22]]}

<<v70>>
70 Ebenso gleichen sie einem Dornbusch im Garten, auf den sich Vögel
jeder Art niederlassen; oder auch einem Toten, der ins Dunkel geworfen
ist, gleichen diese hölzernen, mit Gold und Silber überzogenen Götter.

<<v71>>
71 Auch an den Purpur- und Byssusgewändern, die auf ihnen vermodern,
erkennt ihr, dass sie keine Götter sind. Zuletzt werden sie selbst
zerfressen und zum Gespött im Land. ^{[[#fn23][23]]}

<<v72>>
72 Besser ist also ein gerechter Mann, der keine Götterbilder hat; denn
er ist sicher vor dem Gespött.\\
\\

^{[[#fnm1][1]]} ℘ Jer 29,1

^{[[#fnm2][2]]} 1-72: Zu Bar 6 vgl. die Einleitung.

^{[[#fnm3][3]]} ℘ Jer 10,3f

^{[[#fnm4][4]]} ℘ Ex 23,21f

^{[[#fnm5][5]]} ℘ Jes 40,19f; 41,7; 46,6f

^{[[#fnm6][6]]} ℘ 6,42f

^{[[#fnm7][7]]} Dirnen: Gemeint sind die Tempeldirnen.

^{[[#fnm8][8]]} ℘ Jer 10,9

^{[[#fnm9][9]]} 10.23: Für «Schmutz» steht in G ein Wort, das eigentlich
«Rost» bedeutet. Gold rostet aber nicht, sondern es setzt sich eine
feine Schmutzschicht an, die man von Zeit zu Zeit wegputzt.

^{[[#fnm10][10]]} ℘ Jes 46,7; Jer 10,14

^{[[#fnm11][11]]} ℘ Weish 13,16

^{[[#fnm12][12]]} ℘ Lev 12,4

^{[[#fnm13][13]]} Nach dem Gesetz war Frauen der Tempeldienst verboten.

^{[[#fnm14][14]]} Das Totenmahl spielt auf den Kult der sterbenden und
wieder auflebenden heidnischen Gottheiten an.

^{[[#fnm15][15]]} ℘ Ps 68,6f

^{[[#fnm16][16]]} ℘ Dan 2,2

^{[[#fnm17][17]]} ℘ (42-43) Hos 4,13f

^{[[#fnm18][18]]} Der Brauch gehört zur sakralen Prostitution.

^{[[#fnm19][19]]} Andere Lesart: Wer sieht da, dass . . .

^{[[#fnm20][20]]} ℘ Jer 14,22

^{[[#fnm21][21]]} ℘ Gen 1,15-17

^{[[#fnm22][22]]} ℘ Jer 10,5

^{[[#fnm23][23]]} Byssus: Text korr.; mehrere Textzeugen: Marmor.
