:PROPERTIES:
:ID:       51065d6c-8721-4556-b9b4-39376d25373a
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Daniel* -- [[file:Dan_1.html][1]] ...
[[file:Dan_4.html][4]] [[file:Dan_5.html][5]] *6* [[file:Dan_7.html][7]]
[[file:Dan_8.html][8]] ... [[file:Dan_14.html][14]]

--------------

* Dan 6
  :PROPERTIES:
  :CUSTOM_ID: dan-6
  :END:

<<verses>>

<<v1>>
1 und der Meder Darius übernahm die Königsherrschaft im Alter von
zweiundsechzig Jahren.\\
\\

<<v2>>
** Daniel in der Löwengrube: 6,2-29
   :PROPERTIES:
   :CUSTOM_ID: daniel-in-der-löwengrube-62-29
   :END:
2 Darius fand es für gut, über das Reich hundertzwanzig Satrapen
einzusetzen, die über das ganze Reich verteilt sein sollten.

<<v3>>
3 Über diese wieder setzte er drei oberste Beamte, zu denen auch Daniel
gehörte. Ihnen sollten die Satrapen Rechenschaft ablegen, damit der
König keinen Schaden erleide.

<<v4>>
4 Daniel nun zeichnete sich vor den anderen obersten Beamten und den
Satrapen aus; denn in ihm war ein außergewöhnlicher Geist. Der König
erwog sogar, ihn zum höchsten Beamten des ganzen Reiches zu machen.
^{[[#fn1][1]]}

<<v5>>
5 Da suchten die obersten Beamten und die Satrapen einen Grund, um
Daniel wegen seiner Amtsführung anzuklagen. Sie konnten aber keinen
Grund zur Anklage und kein Vergehen finden; denn er war zuverlässig;
keine Nachlässigkeit und kein Vergehen konnte man ihm nachweisen.

<<v6>>
6 Da sagten jene Männer: Wir werden keinen Grund finden, um diesen
Daniel anzuklagen, es sei denn, wir finden gegen ihn etwas wegen des
Gesetzes seines Gottes.

<<v7>>
7 Darum bestürmten die obersten Beamten und Satrapen den König und
sagten zu ihm: König Darius, mögest du ewig leben.

<<v8>>
8 Alle obersten Beamten des Reiches, die Präfekten, Satrapen, Räte und
Statthalter raten dem König, ein Dekret zu erlassen und folgendes Verbot
in Kraft zu setzen: Jeder, der innerhalb von dreißig Tagen an
irgendeinen Gott oder Menschen außer an dich, König, eine Bitte richtet,
der soll in die Löwengrube geworfen werden.

<<v9>>
9 Erlass dieses Verbot, o König, und fertige ein Schreiben darüber aus!
Es soll nach dem unwandelbaren Gesetz der Meder und Perser unabänderlich
sein. ^{[[#fn2][2]]}

<<v10>>
10 König Darius unterzeichnete das Verbot.

<<v11>>
11 Als Daniel erfuhr, dass das Schreiben unterzeichnet war, ging er in
sein Haus. In seinem Obergemach waren die Fenster nach Jerusalem hin
offen. Dort kniete er dreimal am Tag nieder und richtete sein Gebet und
seinen Lobpreis an seinen Gott, ganz so, wie er es gewohnt war.
^{[[#fn3][3]]}

<<v12>>
12 Nun schlichen sich jene Männer heran und fanden Daniel, wie er zu
seinem Gott betete und flehte.

<<v13>>
13 Darauf gingen sie zum König und erinnerten ihn an sein Verbot; sie
sagten: O König, hast du nicht ein Verbot unterzeichnet, nach dem jeder,
der innerhalb von dreißig Tagen an irgendeinen Gott oder Menschen außer
an dich, König, eine Bitte richtet, in die Löwengrube geworfen werden
soll? Der König gab zur Antwort: Die Anordnung steht fest nach dem
unwandelbaren Gesetz der Meder und Perser. ^{[[#fn4][4]]}

<<v14>>
14 Da berichteten sie dem König: Daniel, einer von den verschleppten
Juden, achtet weder dich, König, noch das Verbot, das du unterschrieben
hast, sondern verrichtet dreimal am Tag sein Gebet.

<<v15>>
15 Als der König das hörte, war es ihm sehr peinlich und er dachte nach,
wie er Daniel retten könne. Bis Sonnenuntergang bemühte er sich, ihn
freizubekommen.

<<v16>>
16 Doch jene Männer bestürmten ihn und sagten: Bedenke, König, es ist
bei den Medern und Persern Gesetz, dass jedes Verbot und Dekret, das der
König erlässt, unabänderlich ist.

<<v17>>
17 Darauf befahl der König, Daniel herzubringen, und man warf ihn zu den
Löwen in die Grube. Der König sagte noch zu Daniel: Möge dein Gott, dem
du so unablässig dienst, dich erretten. ^{[[#fn5][5]]}

<<v18>>
18 Und man nahm einen großen Stein und wälzte ihn auf die Öffnung der
Grube. Der König versiegelte ihn mit seinem Siegel und den Siegeln
seiner Großen, um zu verhindern, dass an der Lage Daniels etwas
verändert würde.

<<v19>>
19 Dann ging der König in seinen Palast; fastend verbrachte er die
Nacht; er ließ sich keine Speisen bringen und konnte keinen Schlaf
finden.

<<v20>>
20 Früh am Morgen, als es gerade hell wurde, stand der König auf und
ging in Eile zur Löwengrube.

<<v21>>
21 Als er sich der Grube näherte, rief er mit schmerzlicher Stimme nach
Daniel und fragte: Daniel, du Diener des lebendigen Gottes! Hat dein
Gott, dem du so unablässig dienst, dich vor den Löwen erretten können?
^{[[#fn6][6]]}

<<v22>>
22 Daniel antwortete ihm: O König, mögest du ewig leben.

<<v23>>
23 Mein Gott hat seinen Engel gesandt und den Rachen der Löwen
verschlossen. Sie taten mir nichts zuleide; denn in seinen Augen war ich
schuldlos und auch dir gegenüber, König, bin ich ohne Schuld.
^{[[#fn7][7]]}

<<v24>>
24 Darüber war der König hoch erfreut und befahl, Daniel aus der Grube
herauszuholen. So wurde Daniel aus der Grube herausgeholt; man fand an
ihm nicht die geringste Verletzung, denn er hatte seinem Gott vertraut.

<<v25>>
25 Nun aber ließ der König die Männer herbeiholen, die Daniel verklagt
hatten, und ließ sie mit ihren Kindern und Frauen in die Löwengrube
werfen. Sie waren noch nicht am Boden der Grube angelangt, da stürzten
sich die Löwen auf sie und zermalmten ihnen alle Knochen.

<<v26>>
26 Daraufhin schrieb König Darius an alle Völker, Nationen und Sprachen
auf der ganzen Erde: Friede sei mit euch in Fülle!

<<v27>>
27 Hiermit ordne ich an: Im ganzen Gebiet meines Reiches soll man vor
dem Gott Daniels zittern und sich vor ihm fürchten. Denn er ist der
lebendige Gott; er lebt in Ewigkeit. Sein Reich geht niemals unter;
seine Herrschaft hat kein Ende. ^{[[#fn8][8]]}

<<v28>>
28 Er rettet und befreit; er wirkt Zeichen und Wunder am Himmel und auf
der Erde; er hat Daniel aus den Tatzen der Löwen errettet.

<<v29>>
29 Daniel aber ging es gut unter dem König Darius und auch unter dem
Perserkönig Kyrus. ^{[[#fn9][9]]}\\
\\

^{[[#fnm1][1]]} ℘ 1,19f

^{[[#fnm2][2]]} ℘ Est 1,19

^{[[#fnm3][3]]} ℘ 1 Kön 8,48f

^{[[#fnm4][4]]} ℘ 3,10-12

^{[[#fnm5][5]]} ℘ 3,15-18

^{[[#fnm6][6]]} ℘ Ps 22,22

^{[[#fnm7][7]]} ℘ 3,49.95; Hebr 11,33

^{[[#fnm8][8]]} ℘ 3,100

^{[[#fnm9][9]]} ℘ 1,21
