:PROPERTIES:
:ID:       f857fa3f-d604-4c9a-b3d4-b9f2e0624977
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Daniel* -- [[file:Dan_1.html][1]] ...
[[file:Dan_3.html][3]] [[file:Dan_4.html][4]] *5* [[file:Dan_6.html][6]]
[[file:Dan_7.html][7]] ... [[file:Dan_14.html][14]]

--------------

* Dan 5
  :PROPERTIES:
  :CUSTOM_ID: dan-5
  :END:

<<verses>>

<<v1>>
** Das Gastmahl Belschazzars: 5,1 - 6,1
   :PROPERTIES:
   :CUSTOM_ID: das-gastmahl-belschazzars-51---61
   :END:
1 König Belschazzar gab ein großes Gastmahl für seine Großen; es waren
tausend Menschen und zusammen mit den Tausend sprach er dem Wein zu.

<<v2>>
2 In seiner Weinlaune nun ließ Belschazzar die goldenen und silbernen
Gefäße holen, die sein Vater Nebukadnezzar aus dem Tempel in Jerusalem
mitgenommen hatte. Jetzt sollten der König und seine Großen, seine
Frauen und Nebenfrauen daraus trinken. ^{[[#fn1][1]]}

<<v3>>
3 Man holte also die goldenen Gefäße, die man aus dem Tempel des
Gotteshauses in Jerusalem mitgenommen hatte, und der König und seine
Großen, seine Frauen und Nebenfrauen tranken daraus.

<<v4>>
4 Sie tranken Wein und lobten die Götter aus Gold und Silber, aus
Bronze, Eisen, Holz und Stein. ^{[[#fn2][2]]}

<<v5>>
5 In derselben Stunde erschienen die Finger einer Menschenhand und
schrieben gegenüber dem Leuchter etwas auf die weißgetünchte Wand des
königlichen Palastes. Der König sah den Rücken der Hand, als sie
schrieb.

<<v6>>
6 Da erbleichte er und seine Gedanken erschreckten ihn. Seine Glieder
wurden schwach und ihm schlotterten die Knie.

<<v7>>
7 Der König schrie laut, man solle die Wahrsager, Chaldäer und
Astrologen holen. Dann sagte er zu den Weisen von Babel: Wer diese
Schrift lesen und mir deuten kann - was er auch sei: er soll in Purpur
gekleidet werden, eine goldene Kette um den Hals tragen und als der
Dritte in meinem Reich herrschen. ^{[[#fn3][3]][[#fn4][4]]}

<<v8>>
8 Da kamen alle Weisen des Königs herbei; aber sie waren nicht imstande,
die Schrift zu lesen oder dem König zu sagen, was sie bedeutete.

<<v9>>
9 Darüber erschrak König Belschazzar noch mehr und sein Gesicht wurde
bleich. Auch seine Großen gerieten in Angst.

<<v10>>
10 Da die Rufe des Königs und seiner Großen bis zur Königin drangen, kam
sie in den Festsaal und sagte: O König, mögest du ewig leben. Lass dich
von deinen Gedanken nicht erschrecken; du brauchst nicht zu erbleichen.

<<v11>>
11 In deinem Reich gibt es einen Mann, in dem der Geist der heiligen
Götter wohnt. Schon zu deines Vaters Zeiten fand man bei ihm Erleuchtung
und Einsicht und Weisheit, wie nur die Götter sie haben; deshalb hat
König Nebukadnezzar, dein Vater, ihn zum Obersten der Zeichendeuter,
Wahrsager, Chaldäer und Astrologen ernannt, dein eigener Vater, o König!

<<v12>>
12 Bei diesem Daniel also, dem der König den Namen Beltschazzar gegeben
hat, fand man außergewöhnlichen Geist sowie Erkenntnis und Einsicht und
die Gabe, Träume auszulegen, Rätsel zu erklären und schwierige Fragen zu
lösen. Darum lass jetzt Daniel herrufen; er wird die Deutung geben.
^{[[#fn5][5]]}

<<v13>>
13 Daniel wurde vor den König gebracht und der König sagte zu ihm: Du
also bist Daniel, einer von den verschleppten Juden, die mein Vater, der
König, aus Juda hierher gebracht hat.

<<v14>>
14 In dir, so habe ich gehört, ist der Geist der Götter und bei dir fand
man Erleuchtung und Einsicht und außergewöhnliche Weisheit.

<<v15>>
15 Man hat die Weisen und die Wahrsager vor mich gebracht, damit sie
diese Schrift lesen und mir deuten. Sie konnten mir aber nicht sagen,
was das Geschriebene bedeutet.

<<v16>>
16 Doch du, so habe ich gehört, kannst Deutungen geben und schwierige
Fragen lösen. Wenn du nun die Schrift lesen und mir deuten kannst,
sollst du in Purpur gekleidet werden, um den Hals eine goldene Kette
tragen und als der Dritte in meinem Reich herrschen.

<<v17>>
17 Daniel gab dem König zur Antwort: Behalte deine Gaben oder schenk sie
einem andern! Aber die Schrift will ich für den König lesen und deuten.

<<v18>>
18 Mein König! Der höchste Gott hat deinem Vater Nebukadnezzar
Herrschaft und Macht, Herrlichkeit und Majestät gegeben. ^{[[#fn6][6]]}

<<v19>>
19 Vor der Macht, die ihm verliehen war, zitterten und bebten alle
Völker, Nationen und Sprachen. Er tötete, wen er wollte, und ließ am
Leben, wen er wollte. Er erhöhte, wen er wollte, und stürzte, wen er
wollte.

<<v20>>
20 Als aber sein Herz überheblich und sein Geist hochmütig wurde,
stürzte man ihn von seinem königlichen Thron und er verlor die
Herrscherwürde.

<<v21>>
21 Man verstieß ihn aus der Gemeinschaft der Menschen. Sein Herz wurde
dem der Tiere gleichgemacht. Er musste bei den wilden Eseln hausen und
sich von Gras ernähren wie die Ochsen. Der Tau des Himmels benetzte
seinen Körper, bis er erkannte: Der höchste Gott gebietet über die
Herrschaft bei den Menschen und gibt sie, wem er will. ^{[[#fn7][7]]}

<<v22>>
22 Obgleich nun du, sein Sohn Belschazzar, das alles weißt, bist du in
deinem Herzen doch nicht bescheiden geblieben.

<<v23>>
23 Du hast dich gegen den Herrn des Himmels erhoben und dir die Gefäße
aus seinem Tempel herbeischaffen lassen. Du und deine Großen, deine
Frauen und Nebenfrauen, ihr habt daraus Wein getrunken. Du hast die
Götter aus Gold und Silber, aus Bronze, Eisen, Holz und Stein gepriesen,
die weder sehen noch hören können und keinen Verstand haben. Aber den
Gott, der deinen Lebensatem in seiner Hand hat und dem all deine Wege
gehören, den hast du nicht verherrlicht. ^{[[#fn8][8]]}

<<v24>>
24 Darum hat er diese Hand geschickt und diese Schrift geschrieben.

<<v25>>
25 Das Geschriebene lautet aber: Mene mene tekel u-parsin.

<<v26>>
26 Diese Worte bedeuten: Mene: *Gezählt* hat Gott die Tage deiner
Herrschaft und macht ihr ein Ende. ^{[[#fn9][9]]}

<<v27>>
27 Tekel: *Gewogen* wurdest du auf der Waage und zu leicht befunden.

<<v28>>
28 Peres: *Geteilt* wird dein Reich und den Medern und Persern gegeben.

<<v29>>
29 Da befahl Belschazzar, Daniel in Purpur zu kleiden und ihm eine
goldene Kette um den Hals zu legen, und er ließ verkünden, dass Daniel
als der Dritte im Reich herrschen sollte. ^{[[#fn10][10]]}

<<v30>>
30 Aber noch in derselben Nacht wurde Belschazzar, der König der
Chaldäer, getötet

^{[[#fnm1][1]]} ℘ 1,2

^{[[#fnm2][2]]} ℘ 2,35; Bar 6,3; Offb 9,20

^{[[#fnm3][3]]} ℘ 2,2.6.48; Gen 41,42f; Est 8,15

^{[[#fnm4][4]]} der Dritte: hier Rangbezeichnung für eines der höchsten
Ämter im Staat (vgl. auch 6,3).

^{[[#fnm5][5]]} ℘ 1,17

^{[[#fnm6][6]]} ℘ 2,37

^{[[#fnm7][7]]} ℘ 4,13.29

^{[[#fnm8][8]]} ℘ Ijob 12,10; 34,21

^{[[#fnm9][9]]} 26-28: In Daniels Deutung ist mene = gezählt, tekel =
gewogen, peres = geteilt; peres, Mehrzahl parsin, erinnert zugleich an
«Perser».

^{[[#fnm10][10]]} ℘ 5,7
