#+TITLE: Dtn 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-29 So 22:00]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Dtn 21.html


<<verses>>

<<v1>>
* Der Mord durch einen unbekannten Täter: 21,1-9

1 Wenn in dem Land, das der Herr, dein Gott, dir gibt, damit du es in
Besitz nimmst, einer auf freiem Feld ermordet aufgefunden wird und man
nicht weiß, wer ihn erschlagen hat, [fn:1] [fn:2]

<<v2>>
2 dann sollen deine Ältesten und Richter hinausgehen und feststellen,
wie weit die Städte ringsum von dem Ermordeten entfernt sind.

<<v3>>
3 Wenn feststeht, welche Stadt dem Ermordeten am nächsten liegt, sollen
die Ältesten dieser Stadt eine junge Kuh aussuchen, die noch nicht zur
Arbeit verwendet worden ist, das heißt, die noch nicht unter dem Joch
gegangen ist.

<<v4>>
4 Die Ältesten dieser Stadt sollen die Kuh in ein ausgetrocknetes
Bachtal bringen, wo weder geackert noch gesät wird. Dort sollen sie im
Bachbett der Kuh das Genick brechen.

<<v5>>
5 Dann sollen die Priester, die Nachkommen Levis, herantreten; denn sie
hat der Herr, dein Gott, dazu ausgewählt, vor ihm Dienst zu tun und im
Namen des Herrn den Segen zu sprechen. Nach ihrem Spruch soll jeder
Rechtsstreit und jeder Fall von Körperverletzung entschieden werden. [fn:3]

<<v6>>
6 Alle Ältesten dieser Stadt sollen, weil sie dem Ermordeten am nächsten
sind, über der Kuh, der im Bachbett das Genick gebrochen wurde, ihre
Hände waschen. [fn:4]

<<v7>>
7 Sie sollen feierlich sagen: Unsere Hände haben dieses Blut nicht
vergossen und unsere Augen haben nichts gesehen. [fn:5]

<<v8>>
8 Deck es zu, zum Schutz deines Volkes Israel, das du freigekauft hast,
Herr, und lass kein unschuldig vergossenes Blut in der Mitte deines
Volkes Israel bleiben. Dann ist das Blut zu ihrem Schutz zugedeckt.

<<v9>>
9 Du wirst das unschuldig vergossene Blut aus deiner Mitte wegschaffen
können, wenn du tust, was in den Augen des Herrn richtig ist. [fn:6]\\
\\

<<v10>>
* Die Heirat einer Kriegsgefangenen: 21,10-14

10 Wenn du zum Kampf gegen deine Feinde ausziehst und der Herr, dein
Gott, sie alle in deine Gewalt gibt, wenn du dabei Gefangene machst

<<v11>>
11 und unter den Gefangenen eine Frau von schöner Gestalt erblickst,
wenn sie dein Herz gewinnt und du sie heiraten möchtest,

<<v12>>
12 dann sollst du sie in dein Haus bringen und sie soll sich den Kopf
scheren, ihre Nägel kürzen [fn:7]

<<v13>>
13 und die Gefangenenkleidung ablegen. Sie soll in deinem Haus wohnen
und einen Monat lang ihren Vater und ihre Mutter beweinen. Danach darfst
du mit ihr Verkehr haben, du darfst ihr Mann werden und sie deine Frau.

<<v14>>
14 Wenn sie dir aber nicht mehr gefällt, darfst du sie entlassen, und
sie darf tun, was sie will. Auf keinen Fall darfst du sie für Silber
verkaufen. Auch darfst du sie nicht als Sklavin kennzeichnen. Denn du
hast sie dir gefügig gemacht.\\
\\

<<v15>>
* Das Erbrecht des erstgeborenen Sohnes: 21,15-17

15 Wenn ein Mann zwei Frauen hat, eine, die er liebt, und eine, die er
nicht liebt, und wenn beide ihm Söhne gebären, die geliebte wie die
ungeliebte, und der erstgeborene Sohn von der ungeliebten stammt,

<<v16>>
16 dann darf er, wenn er sein Erbe unter seine Söhne verteilt, den Sohn
der geliebten Frau nicht als Erstgeborenen behandeln und damit gegen das
Recht des wirklichen Erstgeborenen, des Sohnes der ungeliebten Frau,
verstoßen.

<<v17>>
17 Vielmehr soll er den Erstgeborenen, den Sohn der Ungeliebten,
anerkennen, indem er ihm von allem, was er besitzt, den doppelten Anteil
gibt. Ihn hat er zuerst gezeugt, er besitzt das Erstgeborenenrecht. [fn:8] [fn:9]\\
\\

<<v18>>
* Die Verstoßung eines Sohnes: 21,18-21

18 Wenn ein Mann einen störrischen und widerspenstigen Sohn hat, der
nicht auf die Stimme seines Vaters und seiner Mutter hört, und wenn sie
ihn züchtigen und er trotzdem nicht auf sie hört, [fn:10] [fn:11]

<<v19>>
19 dann sollen Vater und Mutter ihn packen, vor die Ältesten der Stadt
und die Torversammlung des Ortes führen [fn:12]

<<v20>>
20 und zu den Ältesten der Stadt sagen: Unser Sohn hier ist störrisch
und widerspenstig, er hört nicht auf unsere Stimme, er ist ein
Verschwender und Trinker.

<<v21>>
21 Dann sollen alle Männer der Stadt ihn steinigen und er soll sterben.
Du sollst das Böse aus deiner Mitte wegschaffen. Ganz Israel soll davon
hören, damit sie sich fürchten. [fn:13]\\
\\

<<v22>>
* Die Bestattung von Hingerichteten: 21,22f

22 Wenn jemand ein Verbrechen begangen hat, auf das die Todesstrafe
steht, wenn er hingerichtet wird und du den Toten an einen Pfahl hängst, [fn:14]

<<v23>>
23 dann soll die Leiche nicht über Nacht am Pfahl hängen bleiben,
sondern du sollst ihn noch am gleichen Tag begraben; denn ein Gehenkter
ist ein von Gott Verfluchter. Du sollst das Land nicht unrein werden
lassen, das der Herr, dein Gott, dir als Erbbesitz gibt. [fn:15]\\
\\

* Footnotes

[fn:1] (1-9) [[file:Dtn_5.org::v17][5,17]]; [[file:Dtn_19.org::v12][19,12]]

[fn:2] 1-9: War der Mörder nicht bekannt, dann konnte die
Blutrache sich gegen jeden Menschen aus der nächstliegenden Stadt
richten. Durch die hier vorgeschriebene rechtlich-rituelle Aktion
befreite sich die Stadt von dieser Bedrohung.

[fn:3] [[file:Dtn_10.org::v8][10,8]]; [[file:Dtn_17.org::v8][17,8-13]]; [[file:Dtn_19.org::v17][19,17]]

[fn:4] (6-7) [[file:~/Documents/notes/Bibel/nt/Mt_27.org::v24][Mt 27,24]]

[fn:5] (7-9) [[file:Dtn_19.org::v18][19,10]]

[fn:6] [[v21][21,21]]

[fn:7] 12f: Haarescheren, Nägelschneiden und Neueinkleidung
sind wahrscheinlich Symbolhandlungen, die besagen, hier beginne ein
neues Leben. Der Sinn der Trauer ist die seelische Loslösung von der
Vergangenheit.

[fn:8] [[file:Gen_49.org::v3][Gen 49,3]]

[fn:9] den doppelten Anteil, andere Übersetzungsmöglichkeit:
zwei Drittel.

[fn:10] (18-21) [[file:Dtn_5.org::v16][5,16]]; [[file:Ex_21.org::v15][Ex 21,15]].[[file:Ex_21.org::v17][17]]

[fn:11] 18-21: Das Gesetz begrenzt die in der
patriarchalischen Gesellschaft unbegrenzte väterliche Gewalt auf
doppelte Weise: Die Verstoßung eines Sohnes muss über ein öffentliches
Gerichtsverfahren laufen und neben dem Vater muss auch die Mutter tätig
werden.

[fn:12] [[file:Dtn_19.org::v12][19,12]]

[fn:13] [[file:Dtn_13.org::v6][13,6]].[[file:Dtn_13.org::v12][12]]; [[file:Dtn_17.org::v7][17,7]].[[file:Dtn_17.org::v12][12]]; [[file:Dtn_19.org::v13][19,13]].[[file:Dtn_19.org::v19][19]]; [[v9][21,9]]; [[file:Dtn_22.org::v21][22,21f]]; [[file:Dtn_24.org::v7][24,7]]; [[file:Ri_20.org::v13][Ri 20,13]]

[fn:14] [[file:~/Documents/notes/Bibel/nt/Apg_10.org::v39][Apg 10,39]]; (22-23) [[file:Jos_8.org::v29][Jos 8,29]]; [[file:~/Documents/notes/Bibel/nt/Mt_27.org::v57][Mt 27,57f]]; [[file:~/Documents/notes/Bibel/nt/Joh_19.org::v31][Joh 19,31]]

[fn:15] [[file:~/Documents/notes/Bibel/nt/Gal_3.org::v13][Gal 3,13]]
