#+TITLE: Dtn 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-26 Do 23:43]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Dtn 3.html


* Dtn 3

<<verses>>

<<v1>>
1 Dann wendeten wir uns dem Weg zum Baschan zu und zogen hinauf. Og, der
König des Baschan, rückte mit seinem ganzen Volk gegen uns aus, um bei
Edreï zu kämpfen. [fn:1]

<<v2>>
2 Der Herr sagte zu mir: Fürchte ihn nicht, denn ich gebe ihn, sein
ganzes Volk und sein Land in deine Gewalt. Tu mit ihm, was du mit Sihon
getan hast, dem König der Amoriter, der in Heschbon seinen Sitz hatte.

<<v3>>
3 Und der Herr, unser Gott, gab auch Og, den König des Baschan, und sein
ganzes Volk in unsere Gewalt. Wir schlugen ihn und ließen keinen
überleben.

<<v4>>
4 Damals eroberten wir alle seine Städte. Es gab keine befestigte Stadt,
die wir ihnen nicht genommen hätten: sechzig Städte, den ganzen Bezirk
von Argob, das Königreich des Og im Baschan.

<<v5>>
5 Alle diese Städte waren durch hohe Mauern, Torflügel und Torbalken
befestigt. Hinzu kamen die zahlreichen offenen Landstädte.

<<v6>>
6 Wir weihten sie der Vernichtung, wie wir es mit Sihon, dem König von
Heschbon, getan hatten. Wir weihten die ganze männliche Bevölkerung und
die Frauen, Kinder und Greise der Vernichtung. [fn:2]

<<v7>>
7 Alles Vieh und das, was wir in den Städten geplündert hatten,
behielten wir als Beute.

<<v8>>
8 Damals entrissen wir der Gewalt der beiden Amoriterkönige jenseits des
Jordan das Land vom Arnontal bis zum Gebirge Hermon -

<<v9>>
9 die Sidonier nennen den Hermon Sirjon, die Amoriter nennen ihn Senir
-, [fn:3]

<<v10>>
10 alle Städte der Hochebene, ganz Gilead und den ganzen Baschan bis
nach Salka und Edreï, das heißt nur die Städte des Königreichs Ogs im
Baschan.

<<v11>>
11 Denn Og, der König des Baschan, war als Einziger von den letzten
Rafaïtern noch übrig geblieben. Sein Bett war aus Eisen. Steht es nicht
in Rabba, der Hauptstadt der Ammoniter? Es ist neun gewöhnliche Ellen
lang und vier breit.

<<v12>>
12 Dieses Land nahmen wir damals in Besitz. Von Aroër an, das am
Arnontal liegt, einschließlich der Hälfte des Gebirges Gilead und ihrer
Städte, übergab ich es (euch,) den Rubenitern und Gaditern. [fn:4]

<<v13>>
13 Den Rest von Gilead und den ganzen Baschan, soweit er zum Königreich
Ogs gehört hatte, übergab ich (euch,) der einen Hälfte des Stammes
Manasse - den ganzen Bezirk von Argob. Diesen ganzen Baschan bezeichnet
man als Land der Rafaïter.

<<v14>>
14 Jaïr, der Sohn Manasses, übernahm den ganzen Bezirk von Argob
einschließlich des Gebiets der Geschuriter und der Maachatiter und
benannte sie nach seinem eigenen Namen: Er nannte den Baschan Hawot-Jaïr
(Zeltdörfer Jaïrs). So heißt er noch heute. [fn:5]

<<v15>>
15 Dem Machir übergab ich Gilead,

<<v16>>
16 den Rubenitern und Gaditern aber gab ich das Gebiet von Gilead bis
zum Arnontal, das Tal selbst und das zugehörige Gebiet bis zum Jabbok,
wo das Tal die Grenze zu den Ammonitern bildet,

<<v17>>
17 dazu die Araba und den Jordan mit dem zugehörigen Gebiet, vom See
Kinneret bis zum Meer der Araba, dem Salzmeer am Fuß der Steilhänge des
Pisga, nach Osten hin.\\
\\

<<v18>>
* Die Vorbereitungen zur Eroberung des Westjordanlandes: 3,18-29

18 Damals wies ich euch an: Der Herr, euer Gott, hat euch dieses Land
gegeben, sodass ihr es in Besitz nehmen könnt. Doch jetzt, in Waffen,
sollt ihr zunächst mit allen Wehrfähigen an der Spitze eurer Brüder, der
Israeliten, über den Jordan ziehen. [fn:6]

<<v19>>
19 Nur eure Frauen, Kinder, Greise und Herden - ich weiß, ihr habt viele
Herden - können in den Städten bleiben, die ich für euch bestimmt habe.

<<v20>>
20 Erst wenn der Herr euren Brüdern wie euch Ruhe verschafft hat, erst
wenn auch sie das Land jenseits des Jordan in Besitz genommen haben, das
der Herr, euer Gott, ihnen gibt, dürft ihr zurückkehren, jeder zu seinem
Besitz, den ich für euch bestimmt habe.

<<v21>>
21 Damals wies ich Josua an: Du hast mit eigenen Augen alles gesehen,
was der Herr, euer Gott, mit diesen beiden Königen getan hat. Das
Gleiche wird der Herr mit allen Königreichen tun, zu denen du
hinüberziehst. [fn:7]

<<v22>>
22 Ihr sollt sie nicht fürchten; denn der Herr, euer Gott, ist es, der
für euch kämpft.

<<v23>>
23 Damals rief ich den Herrn um Gnade für mich an: [fn:8]

<<v24>>
24 Gott, mein Herr! Du hast angefangen, deinen Knecht deine Macht und
deine starke Hand schauen zu lassen. Welcher Gott im Himmel oder auf der
Erde hat etwas vollbracht, was deinen Taten und deinen Siegen
vergleichbar wäre?

<<v25>>
25 Lass mich doch hinüberziehen! Lass mich das prächtige Land jenseits
des Jordan sehen, dieses prächtige Bergland und den Libanon!

<<v26>>
26 Doch euretwegen zürnte mir der Herr und erhörte mich nicht. Der Herr
sagte zu mir: Genug! Trag mir diese Sache niemals wieder vor!

<<v27>>
27 Steig auf den Gipfel des Pisga, richte die Augen nach Westen, nach
Norden, nach Süden und nach Osten und schau mit eigenen Augen hinüber!
Doch hinüberziehen über den Jordan hier wirst du nicht. [fn:9]

<<v28>>
28 Setz Josua ein, verleih ihm Macht und Stärke: Er soll an der Spitze
dieses Volkes hinüberziehen. Er soll an sie das Land als Erbbesitz
verteilen, das du nur schauen darfst.

<<v29>>
29 So blieben wir in der Talschlucht gegenüber Bet-Pegor. [fn:10] [fn:11]\\
\\

* Footnotes

[fn:1] (1-7) Num 21,33-35 [[file:Num_21.org::v33][Num 21,33-35]]

[fn:2] 20,16-18 [[file:Dtn_20.org::v16][Dtn 20,16-18]]

[fn:3] 9.13f: Erklärender Zusatz (vgl. die Anmerkung zu [[file:Dtn_1.org::v1][Dtn 1,1-5]]).

[fn:4] (12-17) Num 32 [[file:Num_23.org::v1][Num 23]]; Jos 13,15-33 [[file:Jos_13.org::v15][Jos 13,15-33]]

[fn:5] 14-17: Wohl spätere Variante zu V. 12f.

[fn:6] (18-20) Num 32,16f [[file:Num_32.org::v16][Num 32,16f]]; Jos 1,13 [[file:Jos_1.org::v1][Jos 1,13]]

[fn:7] (21-22) 20,2-4 [[file:Dtn_20.org::v2][Dtn 20,2-4]]

[fn:8] (23-27) 1,37 [[file:Dtn_1.org::v37][Dtn 1,37]]

[fn:9] 34,1-3 [[file:Dtn_34.org::v1][Dtn 34,1-3]]

[fn:10] Num 25 [[file:Num_25.org::v1][Num 25]]

[fn:11] Bet-Pegor ist der Ort, Baal-Pegor ([[file:Dtn_4.org::v3][4,3]]) der dort
verehrte kanaanäische Gott.
