#+TITLE: Dtn 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-27 Fr 18:29]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Dtn 4.html


<<verses>>

<<v1>>
* Ermahnung und Ausblick: 4,1-40

1 Und nun, Israel, höre die Gesetze und Rechtsvorschriften, die ich euch
zu halten lehre. Hört und ihr werdet leben, ihr werdet in das Land, das
der Herr, der Gott eurer Väter, euch gibt, hineinziehen und es in Besitz
nehmen. [fn:1]

<<v2>>
2 Ihr sollt dem Wortlaut dessen, worauf ich euch verpflichte, nichts
hinzufügen und nichts davon wegnehmen; ihr sollt auf die Gebote des
Herrn, eures Gottes, achten, auf die ich euch verpflichte. [fn:2]

<<v3>>
3 Ihr habt mit eigenen Augen gesehen, was der Herr wegen des Baal-Pegor
getan hat. Jeden, der dem Baal-Pegor nachfolgte, hat der Herr, dein
Gott, in deiner Mitte vernichtet. [fn:3]

<<v4>>
4 Ihr aber habt euch am Herrn, eurem Gott, fest gehalten, und darum seid
ihr alle heute noch am Leben.

<<v5>>
5 Hiermit lehre ich euch, wie es mir der Herr, mein Gott, aufgetragen
hat, Gesetze und Rechtsvorschriften. Ihr sollt sie innerhalb des Landes
halten, in das ihr hineinzieht, um es in Besitz zu nehmen. [fn:4] [fn:5]

<<v6>>
6 Ihr sollt auf sie achten und sollt sie halten. Denn darin besteht eure
Weisheit und eure Bildung in den Augen der Völker. Wenn sie dieses
Gesetzeswerk kennen lernen, müssen sie sagen: In der Tat, diese große
Nation ist ein weises und gebildetes Volk. [fn:6]

<<v7>>
7 Denn welche große Nation hätte Götter, die ihr so nah sind, wie Jahwe,
unser Gott, uns nah ist, wo immer wir ihn anrufen? [fn:7]

<<v8>>
8 Oder welche große Nation besäße Gesetze und Rechtsvorschriften, die so
gerecht sind wie alles in dieser Weisung, die ich euch heute vorlege?

<<v9>>
9 Jedoch, nimm dich in Acht, achte gut auf dich! Vergiss nicht die
Ereignisse, die du mit eigenen Augen gesehen, und die Worte, die du
gehört hast. Lass sie dein ganzes Leben lang nicht aus dem Sinn! Präge
sie deinen Kindern und Kindeskindern ein! [fn:8]

<<v10>>
10 Vergiss nicht den Tag, als du am Horeb vor dem Herrn, deinem Gott,
standest. Der Herr hatte zu mir gesagt: Ruf mir das Volk zusammen! Ich
will sie meine Worte hören lassen. Sie sollen lernen, mich zu fürchten,
so lange, wie sie im Land leben, und sie sollen es auch ihre Kinder
lehren.

<<v11>>
11 Ihr wart herangekommen und standet unten am Berg und der Berg
brannte: Feuer, hoch bis in den Himmel hinauf, Finsternis, Wolken und
Dunkel. [fn:9]

<<v12>>
12 Der Herr sprach zu euch mitten aus dem Feuer. Ihr hörtet den Donner
der Worte. Eine Gestalt habt ihr nicht gesehen. Ihr habt nur den Donner
gehört. [fn:10]

<<v13>>
13 Der Herr offenbarte euch seinen Bund, er verpflichtete euch, ihn zu
halten: die Zehn Worte. Er schrieb sie auf zwei Steintafeln.

<<v14>>
14 Mir befahl damals der Herr, euch Gesetze und Rechtsvorschriften zu
lehren, die ihr in dem Land halten sollt, in das ihr hinüberzieht, um es
in Besitz zu nehmen.

<<v15>>
15 Nehmt euch um eures Lebens willen gut in Acht! Denn eine Gestalt habt
ihr an dem Tag, als der Herr am Horeb mitten aus dem Feuer zu euch
sprach, nicht gesehen. [fn:11]

<<v16>>
16 Lauft nicht in euer Verderben und macht euch kein Gottesbildnis, das
irgendetwas darstellt, keine Statue, kein Abbild eines männlichen oder
weiblichen Wesens, [fn:12] [fn:13]

<<v17>>
17 kein Abbild irgendeines Tiers, das auf der Erde lebt, kein Abbild
irgendeines gefiederten Vogels, der am Himmel fliegt,

<<v18>>
18 kein Abbild irgendeines Tiers, das am Boden kriecht, und kein Abbild
irgendeines Meerestieres im Wasser unter der Erde.

<<v19>>
19 Wenn du die Augen zum Himmel erhebst und das ganze Himmelsheer
siehst, die Sonne, den Mond und die Sterne, dann lass dich nicht
verführen! Du sollst dich nicht vor ihnen niederwerfen und ihnen nicht
dienen. Der Herr, dein Gott, hat sie allen anderen Völkern überall unter
dem Himmel zugewiesen. [fn:14] [fn:15]

<<v20>>
20 Euch aber hat der Herr genommen und aus dem Schmelzofen, aus Ägypten,
herausgeführt, damit ihr sein Volk, sein Erbbesitz werdet wie ihr es
heute seid. [fn:16]

<<v21>>
21 Zwar hat der Herr mir wegen eures Murrens gegrollt und mir
geschworen, ich dürfe nicht über den Jordan ziehen und das prächtige
Land betreten, das der Herr, dein Gott, dir als Erbbesitz gibt. [fn:17]

<<v22>>
22 Ich muss in diesem Land hier sterben und werde nicht über den Jordan
ziehen. Aber ihr werdet hinüberziehen und dieses prächtige Land in
Besitz nehmen.

<<v23>>
23 Nehmt euch in Acht! Vergesst nicht den Bund, den der Herr, euer Gott,
mit euch geschlossen hat. Ihr sollt euch kein Gottesbildnis machen, das
irgendetwas darstellt, was der Herr, dein Gott, dir verboten hat. [fn:18]

<<v24>>
24 Denn der Herr, dein Gott, ist verzehrendes Feuer. Er ist ein
eifersüchtiger Gott. [fn:19]

<<v25>>
25 Wenn du Kinder und Kindeskinder zeugst und ihr im Land heimisch seid,
wenn ihr dann ins Verderben lauft und ein Gottesbildnis macht, das
irgendetwas darstellt, wenn ihr also tut, was in den Augen des Herrn,
deines Gottes, böse ist, und wenn ihr ihn erzürnt - [fn:20]

<<v26>>
26 den Himmel und die Erde rufe ich heute als Zeugen gegen euch an: dann
werdet ihr unverzüglich aus dem Land ausgetilgt sein, in das ihr jetzt
über den Jordan zieht, um es in Besitz zu nehmen. Nicht lange werdet ihr
darin leben. Ihr werdet vernichtet werden. [fn:21]

<<v27>>
27 Der Herr wird euch unter die Völker verstreuen. Nur einige von euch
werden übrig bleiben in den Nationen, zu denen der Herr euch führt.

<<v28>>
28 Dort müsst ihr Göttern dienen, Machwerken von Menschenhand, aus Holz
und Stein. Sie können nicht sehen und nicht hören, nicht essen und nicht
riechen. [fn:22]

<<v29>>
29 Dort werdet ihr den Herrn, deinen Gott, wieder suchen. Du wirst ihn
auch finden, wenn du dich mit ganzem Herzen und mit ganzer Seele um ihn
bemühst. [fn:23]

<<v30>>
30 Wenn du in Not bist, werden alle diese Worte dich finden. In späteren
Tagen wirst du zum Herrn, deinem Gott, zurückkehren und auf seine Stimme
hören.

<<v31>>
31 Denn der Herr, dein Gott, ist ein barmherziger Gott. Er lässt dich
nicht fallen und gibt dich nicht dem Verderben preis und vergisst nicht
den Bund mit deinen Vätern, den er ihnen beschworen hat. [fn:24]

<<v32>>
32 Forsche doch einmal in früheren Zeiten nach, die vor dir gewesen
sind, seit dem Tag, als Gott den Menschen auf der Erde schuf; forsche
nach vom einen Ende des Himmels bis zum andern Ende: Hat sich je etwas
so Großes ereignet wie dieses und hat man je solche Worte gehört? [fn:25]

<<v33>>
33 Hat je ein Volk einen Gott mitten aus dem Feuer im Donner sprechen
hören, wie du ihn gehört hast, und ist am Leben geblieben?

<<v34>>
34 Oder hat je ein Gott es ebenso versucht, zu einer Nation zu kommen
und sie mitten aus einer anderen herauszuholen unter Prüfungen, unter
Zeichen, Wundern und Krieg, mit starker Hand und hoch erhobenem Arm und
unter großen Schrecken, wie es der Herr, euer Gott, in Ägypten mit euch
getan hat, vor deinen Augen? [fn:26]

<<v35>>
35 Das hast du sehen dürfen, damit du erkennst: Jahwe ist der Gott, kein
anderer ist außer ihm. [fn:27] [fn:28]

<<v36>>
36 Vom Himmel herab ließ er dich seinen Donner hören, um dich zu
erziehen. Auf der Erde ließ er dich sein großes Feuer sehen und mitten
aus dem Feuer hast du seine Worte gehört.

<<v37>>
37 Weil er deine Väter lieb gewonnen hatte, hat er alle Nachkommen eines
jeden von ihnen erwählt und dich dann in eigener Person durch seine
große Kraft aus Ägypten geführt, [fn:29] [fn:30]

<<v38>>
38 um bei deinem Angriff Völker zu vertreiben, die größer und mächtiger
sind als du, um dich in ihr Land zu führen und es dir als Erbbesitz zu
geben, wie es jetzt geschieht. [fn:31]

<<v39>>
39 Heute sollst du erkennen und dir zu Herzen nehmen: Jahwe ist der Gott
im Himmel droben und auf der Erde unten, keiner sonst. [fn:32]

<<v40>>
40 Daher sollst du auf seine Gesetze und seine Gebote, auf die ich dich
heute verpflichte, achten, damit es dir und später deinen Nachkommen gut
geht und du lange lebst in dem Land, das der Herr, dein Gott, dir gibt
für alle Zeit.\\
\\

<<v41>>
* Die Asylstädte im Ostjordanland: 4,41-43

41 Damals hat Mose jenseits des Jordan, nach Osten hin, drei Städten
eine Sonderstellung zugewiesen. [fn:33] [fn:34]

<<v42>>
42 Dorthin soll jeder, der einen Menschen getötet hat, fliehen können,
falls er den andern ohne Vorsatz getötet hat und nicht schon früher mit
ihm verfeindet gewesen ist. Wenn er in eine dieser Städte flieht, darf
er am Leben bleiben.

<<v43>>
43 Es sind Bezer im Wüstengebiet der Hochebene für die Rubeniter, Ramot
in Gilead für die Gaditer und Golan im Baschan für die Manassiter.\\
\\

<<v44>>
* Die Verkündigung des Gesetzes: 4,44 - 28,68

* Ort und Zeit: 4,44-49

44 Und das ist die Weisung, die Mose den Israeliten vorgelegt hat. [fn:35]

<<v45>>
45 Das sind die Satzungen, die Gesetze und Rechtsvorschriften, die Mose
den Israeliten verkündet hat, als sie aus Ägypten zogen. [fn:36]

<<v46>>
46 Es geschah jenseits des Jordan, in der Talschlucht gegenüber
Bet-Pegor, im Land Sihons, des Königs der Amoriter, der in Heschbon
seinen Sitz hatte. Ihn hatten Mose und die Israeliten geschlagen, als
sie aus Ägypten zogen.

<<v47>>
47 Sie hatten sein Land und das Land Ogs, des Königs des Baschan, in
Besitz genommen, das Land der beiden Amoriterkönige jenseits des Jordan,
im Osten,

<<v48>>
48 von Aroër am Rand des Arnontals bis zum Gebirge Sion - das ist der
Hermon -

<<v49>>
49 und die ganze Araba jenseits des Jordan nach Osten hin, bis zum Meer
der Araba unterhalb der Steilhänge des Pisga.\\
\\


* Footnotes

[fn:1] (1-4) 30,15-20 [[file:Dtn_30.org::v15][Dtn 30,15-20]]

[fn:2] 13,1 [[file:Dtn_13.org::v1][Dtn 13,1]]; Offb 22,18f [[file:~/Documents/notes/Bibel/nt/Offb_22.org::v18][Offb 22,18f]]

[fn:3] 29,1 [[file:Dtn_29.org::v1][Dtn 29,1]]; Num 25,1-9 [[file:Num_25.org::v1][Num 25,1-9]]

[fn:4] 12,1 [[file:Dtn_12.org::v1][Dtn 12,1]]; 31,13 [[file:Dtn_31.org::v13][Dtn 31,13]]

[fn:5] Das deuteronomische Gesetz verpflichtet Israel innerhalb
des verheißenen Landes nach dessen Einnahme.

[fn:6] 6f: Hier ist besonders an die Zeit Salomos gedacht, wie
sie in [[file:1.Kön_3.org::v1][1 Kön 3]] - [[file:1.Kön_11.org::v1][11]] geschildert wird.

[fn:7] (7-8) Röm 3,2 [[file:~/Documents/notes/Bibel/nt/Röm_3.org::v2][Röm 3,2]]

[fn:8] (9-14) [[file:Dtn_5.org::v2][5,2-31]]; [[file:Ex_19.org::v1][Ex 19-20]]; [[file:Dtn_5.org::v24][Dtn 5,24]]; [[file:Dtn_29.org::v1][29,1]]; [[file:Dtn_31.org::v13][31,13]]; [[file:Dtn_32.org::v46][32,46]]

[fn:9] (11-12) [[file:~/Documents/notes/Bibel/nt/Hebr_12.org::v18][Hebr 12,18f]]

[fn:10] [[file:~/Documents/notes/Bibel/nt/Joh_1.org::v18][Joh 1,18]]; [[file:~/Documents/notes/Bibel/nt/Joh_5.org::v37][5,37]]; [[file:~/Documents/notes/Bibel/nt/Joh_6.org::v46][6,46]]

[fn:11] (15-19) [[file:~/Documents/notes/Bibel/nt/Röm_1.org::v23][Röm 1,23]]

[fn:12] (16-19) [[file:Dtn_5.org::v8][5,8f]]

[fn:13] 16-20: Umschreibende Erklärung zum ersten der Zehn
Gebote. Dabei ist weniger eine bildhafte Jahweverehrung gemeint, als
eher die Verehrung anderer Götter unter verschiedensten Gestalten (vgl.
[[file:2.Kön_21.org::v3][2 Kön 21,3-8]]; [[file:2.Kön_23.org::v4][23,4-14]]; [[file:Ez_8.org::v1][Ez 8]]).

[fn:14] (19-20) [[file:Dtn_32.org::v8][32,8f]]; [[file:Dtn_17.org::v2][17,2-5]]; [[file:Dtn_29.org::v25][29,25]]

[fn:15] Die für Israel nicht erlaubte Verehrung der Gestirne
wird anderen Völkern zugestanden.

[fn:16] [[file:Dtn_9.org::v29][9,29]]; [[file:1.Kön_8.org::v51][1 Kön 8,51]]

[fn:17] [[file:Dtn_1.org::v37][1,37]]

[fn:18] [[file:Dtn_29.org::v24][29,24]]

[fn:19] [[file:Dtn_5.org::v9][5,9]]; [[file:~/Documents/notes/Bibel/nt/Hebr_12.org::v29][Hebr 12,29]]

[fn:20] (25-28) [[file:Dtn_28.org::v15][28,15-68]]

[fn:21] [[file:Dtn_30.org::v18][30,18f]]; [[file:Dtn_31.org::v28][31,28]]

[fn:22] [[file:Dtn_27.org::v15][27,15]]; [[file:Dtn_28.org::v36][28,36]]; [[file:Ps_115.org::v4][Ps 115,4-8]]; [[file:Ps_135.org::v15][135,15-18]]

[fn:23] (29-31) [[file:Dtn_30.org::v1][30,1-10]]

[fn:24] [[file:Gen_15.org::v18][Gen 15,18]]

[fn:25] (32-40) [[file:Dtn_8.org::v2][8,2-6]]

[fn:26] [[file:Dtn_34.org::v11][34,11f]]

[fn:27] [[file:~/Documents/notes/Bibel/nt/Mk_12.org::v32][Mk 12,32]]; [[file:~/Documents/notes/Bibel/nt/1.Kor_8.org::v4][1 Kor 8,4]]

[fn:28] 35.39: Die Frage nach der Existenz fremder Götter
stellt das Dtn noch nicht; Israel ist jedoch einzig auf seinen Gott
Jahwe verpflichtet. Doch hier wird ähnlich wie in [[file:Jes_41.org::v22][Jes 41,22f]]; [[file:Jes_43.org::v10][43,10-13]];
[[file:Jes_44.org::v6][44,6]] und [[file:Jes_45.org::v5][45,5]] eine streng monotheistische Aussage erreicht.

[fn:29] [[file:Dtn_10.org::v15][10,15]]

[fn:30] Andere Übersetzungsmöglichkeit: Weil er deine Väter
lieb gewonnen hatte, hat er «seinen Nachkommen» erwählt. - Dann läge
eine für den Leser damals erkennbare Anspielung an [[file:Gen_17.org::v19][Gen 17,19]] vor, wo
Abraham gesagt bekommt, Gott werde seinen Bund mit ihm über die
Isaak-Linie weiterführen.

[fn:31] [[file:Dtn_18.org::v12][18,12]]

[fn:32] [[file:~/Documents/notes/Bibel/nt/1.Kor_8.org::v4][1 Kor 8,4]]

[fn:33] (41-43) [[file:Dtn_19.org::v1][19,1-10]]; [[file:Num_35.org::v6][Num 35,6-15]]

[fn:34] 41-43: Die Einrichtung der Asylstädte dient dazu, die
bei jeder Tötung mögliche Blutrache zu mildern. Schuldloser Unfall und
fahrlässige Tötung werden von der Blutrache ausgenommen, nur noch
Totschlag und Mord fallen unter sie.

[fn:35] 44-5,1a: Vorbemerkungen zur Rede des Mose 5,1 - 26,19;
28,1-68. «als sie aus Ägypten zogen» (V. 45) meint ganz unbestimmt: in
den Jahren des Anfangs der Volksgeschichte. Die «Weisung» wird nicht
einfach geboten, sondern Israel von Mose «vorgelegt»; denn sie ist ein
Bundestext, der frei angenommen werden soll (vgl. [[file:Dtn_26.org::v17][26,17-19]] und [[file:Dtn_28.org::v69][28,69]] -
[[file:Dtn_30.org::v20][30,20]], ferner [[file:Ex_19.org::v7][Ex 19,7f]]; [[file:Ex_21.org::v1][21,1]] und [[file:Ex_24.org::v3][24,3]]). Auch hinter «Satzungen» ([[v45][4,45]])
steht ein Wort, das im Alten Orient «Vertragsurkunde» bedeutet und das
in den vorausgehenden Büchern stets mit «Bundesurkunde» übersetzt ist.

[fn:36] Andere Lesart: die Satzungen, Gesetze und Rechtsvorschriften.
