#+TITLE: Dtn 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-29 So 20:14]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Dtn 17.html

<<verses>>

<<v1>>
* Das Verbot fehlerhafter Opfer: 17,1

1 Du sollst dem Herrn, deinem Gott, keinen Stier und kein Lamm
schlachten, die einen Fehler, irgendeine Missbildung haben, denn das ist
dem Herrn, deinem Gott, ein Gräuel. [fn:1]\\
\\

<<v2>>
* Das Verfahren beim Abfall zu Gestirngöttern: 17,2-7

2 Wenn in deiner Mitte, in einem der Stadtbereiche, die der Herr, dein
Gott, dir gibt, ein Mann - oder auch eine Frau - lebt, der tut, was in
den Augen des Herrn, deines Gottes, böse ist, und sich über seinen Bund
hinwegsetzt, [fn:2]

<<v3>>
3 wenn er hingeht, anderen Göttern dient und sich vor ihnen
niederwirft - und zwar vor der Sonne, dem Mond oder dem ganzen
Himmelsheer, was ich verboten habe -, [fn:3]

<<v4>>
4 wenn dir das gemeldet wird, wenn du den Fall anhängig machst, genaue
Ermittlungen anstellst und es sich zeigt: Ja, es ist wahr, der
Tatbestand steht fest, dieser Gräuel ist in Israel geschehen!, [fn:4]

<<v5>>
5 dann sollst du diesen Mann oder diese Frau, die den Frevel begangen
haben, den Mann oder die Frau, zu einem deiner Stadttore führen und
steinigen und sie sollen sterben.

<<v6>>
6 Wenn es um Leben oder Tod eines Angeklagten geht, darf er nur auf die
Aussage von zwei oder drei Zeugen hin zum Tod verurteilt werden. Auf die
Aussage eines einzigen Zeugen hin darf er nicht zum Tod verurteilt
werden. [fn:5]

<<v7>>
7 Wenn er hingerichtet wird, sollen die Zeugen als Erste ihre Hand gegen
ihn erheben, dann erst das ganze Volk. Du sollst das Böse aus deiner
Mitte wegschaffen. [fn:6]\\
\\

<<v8>>
* Das sakrale Gerichtsverfahren: 17,8-13

8 Wenn bei einem Verfahren wegen Mord, Eigentumsdelikt oder
Körperverletzung - also wegen Streitsachen, über die in deinen
Stadtbereichen entschieden werden darf - der Fall für dich zu
ungewöhnlich liegt, dann sollst du dich aufmachen, zu der Stätte
hinaufziehen, die der Herr auswählt, [fn:7]

<<v9>>
9 und vor die levitischen Priester und den Richter treten, der dann
amtiert. Du sollst genaue Ermittlungen anstellen lassen und sie sollen
dir den Urteilsspruch verkünden. [fn:8]

<<v10>>
10 Dann sollst du dich an den Spruch halten, den sie dir an dieser
Stätte, die der Herr auswählt, verkünden, und du sollst auf alles, was
sie dich lehren, genau achten und es halten.

<<v11>>
11 An den Wortlaut der Weisung, die sie dich lehren, und an das Urteil,
das sie fällen, sollst du dich halten. Von dem Spruch, den sie dir
verkünden, sollst du weder rechts noch links abweichen.

<<v12>>
12 Ein Mann aber, der so vermessen ist, auf den Priester, der dort
steht, um vor dem Herrn, deinem Gott, Dienst zu tun, oder auf den
Richter nicht zu hören, dieser Mann soll sterben. Du sollst das Böse aus
Israel wegschaffen. [fn:9]

<<v13>>
13 Das ganze Volk soll davon hören, damit sie sich fürchten und nicht
noch einmal so vermessen sind.\\
\\

<<v14>>
* Der König: 17,14-20

14 Wenn du in das Land, das der Herr, dein Gott, dir gibt, hineingezogen
bist, es in Besitz genommen hast, in ihm wohnst und dann sagst: Ich will
einen König über mich einsetzen wie alle Völker in meiner
Nachbarschaft!, [fn:10]

<<v15>>
15 dann darfst du einen König über dich einsetzen, doch nur einen, den
der Herr, dein Gott, auswählt. Nur aus der Mitte deiner Brüder darfst du
einen König über dich einsetzen. Einen Ausländer darfst du nicht über
dich einsetzen, weil er nicht dein Bruder ist. [fn:11]

<<v16>>
16 Der König soll sich aber nicht zu viele Pferde halten. Er soll das
Volk nicht nach Ägypten zurückbringen, um mehr Pferde zu bekommen; denn
der Herr hat zu euch gesagt: Ihr sollt auf diesem Weg nie wieder
zurückkehren. [fn:12]

<<v17>>
17 Er soll sich auch keine große Zahl von Frauen nehmen, damit sein Sinn
nicht vom rechten Weg abweicht. Er soll nicht zu viel Silber und Gold
anhäufen. [fn:13]

<<v18>>
18 Und wenn er seinen Königsthron bestiegen hat, soll er sich von dieser
Weisung, die die levitischen Priester aufbewahren, auf einer
Schriftrolle eine Zweitschrift anfertigen lassen. [fn:14] [fn:15]

<<v19>>
19 Sein Leben lang soll er die Weisung mit sich führen und in der Rolle
lesen, damit er lernt, den Herrn, seinen Gott, zu fürchten, auf alle
Worte dieser Weisung und dieser Gesetze zu achten, sie zu halten,

<<v20>>
20 sein Herz nicht über seine Brüder zu erheben und von dem Gebot weder
rechts noch links abzuweichen, damit er lange als König in Israels Mitte
lebt, er und seine Nachkommen. [fn:16]\\
\\


* Footnotes

[fn:1] [[file:Mal_1.org::v6][Mal 1,6-9]]

[fn:2] (2-5) [[file:Dtn_4.org::v19][4,19]]; [[file:Dtn_13.org::v2][13,2-19]]; [[file:2.Kön_17.org::v16][2 Kön 17,16]]; [[file:2.Kön_21.org::v3][21,3]].[[file:2.Kön_21.org::v5][5]]; [[file:2.Kön_23.org::v4][23,4f]]; [[file:Dtn_29.org::v24][Dtn 29,24]]

[fn:3] was ich verboten habe: vgl. die Anmerkung zu 11,13-15.

[fn:4] [[file:Dtn_19.org::v18][19,18]]

[fn:5] [[file:Dtn_19.org::v15][19,15]]; [[file:~/RoamNotes/notes/Bibel/nt/Mt_18.org::v16][Mt 18,16]]; [[file:~/RoamNotes/notes/Bibel/nt/Joh_8.org::v17][Joh 8,17]]; [[file:~/RoamNotes/notes/Bibel/nt/2 Kor 13::v1][2 Kor 13,1]]; [[file:~/RoamNotes/notes/Bibel/nt/1.Tim_5.org::v19][1 Tim 5,19]]; [[file:~/RoamNotes/notes/Bibel/nt/Hebr_10.org::v28][Hebr 10,28]]

[fn:6] [[file:Dtn_13.org::v10][13,10]]; [[file:Dtn_21.org::v21][21,21]]; [[file:~/RoamNotes/notes/Bibel/nt/Joh_8.org::v7][Joh 8,7]]; [[file:~/RoamNotes/notes/Bibel/nt/1.Kor_5.org::v13][1 Kor 5,13]]

[fn:7] (8-13) [[file:Dtn_21.org::v5][21,5]]; [[file:Ex_18.org::v13][Ex 18,13-26]]; [[file:2.Chr_19.org::v8][2 Chr 19,8-11]]

[fn:8] [[file:Dtn_10.org::v8][10,8]]; [[file:Dtn_19.org::v17][19,17]]; [[file:Dtn_26.org::v3][26,3]]

[fn:9] (12-13) [[file:Dtn_21.org::v21][21,21]]; [[file:Dtn_20.org::v2][20,2]]

[fn:10] (14-20) [[file:1.Sam_7.org::v2][1 Sam 7,2]] - [[file:1.Sam_8.org::v22][8,22]]; [[file:1.Sam_10.org::v18][10,18f]]; [[file:1.Sam_21.org::v1][21,1-25]]

[fn:11] [[file:1.Sam_10.org::v24][1 Sam 10,24]]; [[file:1.Sam_16.org::v1][16,1-13]]; [[file:2.Sam_5.org::v1][2 Sam 5,1-3]]

[fn:12] [[file:Dtn_28.org::v68][28,68]]; [[file:Gen_26.org::v2][Gen 26,2]]; [[file:2.Sam_8.org::v4][2 Sam 8,4]]; [[file:1.Kön_10.org::v26][1 Kön 10,26-29]]

[fn:13] [[file:1.Kön_10.org::v14][1 Kön 10,14-25]]; [[file:1.Kön_11.org::v1][11,1-8]]

[fn:14] [[file:Dtn_10.org::v8][10,8]]; [[file:Dtn_31.org::v9][31,9]].[[file:Dtn_31.org::v26][26]]; (18-20) [[file:Jos_1.org::v7][Jos 1,7-9]]; [[file:1.Kön_2.org::v1][1 Kön 2,1-4]]

[fn:15] Mit «dieser Weisung» dürfte der Text der Kapitel [[file:Dtn_5.org::v1][5]] - [[file:Dtn_28.org::v1][28]]
gemeint sein. Der Buchname «Deuteronomium» kommt vielleicht von
diesem Vers.

[fn:16] [[file:Dtn_5.org::v32][5,32f]]
