#+TITLE: Dtn 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-29 So 19:44]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Dtn 15.html


<<verses>>

<<v1>>
* Der Verzicht auf Forderungen in jedem siebten Jahr: 15,1-6
     
1 In jedem siebten Jahr sollst du die Ackerbrache einhalten. [fn:1] [fn:2]

<<v2>>
2 Und so lautet eine Bestimmung für die Brache: Jeder Gläubiger soll den
Teil seines Vermögens, den er einem andern unter Personalhaftung als
Darlehen gegeben hat, brachliegen lassen. Er soll gegen den andern,
falls dieser sein Bruder ist, nicht mit Zwang vorgehen; denn er hat die
Brache für den Herrn verkündet.

<<v3>>
3 Gegen einen Ausländer darfst du mit Zwang vorgehen. Wenn es sich aber
um deinen Bruder handelt, dann lass deinen Vermögensteil brachliegen! [fn:3]

<<v4>>
4 Doch eigentlich sollte es bei dir gar keine Armen geben; denn der Herr
wird dich reich segnen in dem Land, das der Herr, dein Gott, dir als
Erbbesitz gibt und das du in Besitz nimmst, [fn:4]

<<v5>>
5 wenn du auf die Stimme des Herrn, deines Gottes, hörst, auf dieses
Gebot, auf das ich dich heute verpflichte, achtest und es hältst.

<<v6>>
6 Wenn der Herr, dein Gott, dich segnet, wie er es dir zugesagt hat,
dann kannst du vielen Völkern gegen Pfand leihen, du selbst aber
brauchst nichts zu verpfänden; du wirst über viele Völker Gewalt haben,
über dich aber werden sie keine Gewalt haben. [fn:5]\\
\\

<<v7>>
* Die Kredithilfen an arme Israeliten: 15,7-11

7 Wenn bei dir ein Armer lebt, irgendeiner deiner Brüder in irgendeinem
deiner Stadtbereiche in dem Land, das der Herr, dein Gott, dir gibt,
dann sollst du nicht hartherzig sein und sollst deinem armen Bruder
deine Hand nicht verschließen. [fn:6]

<<v8>>
8 Du sollst ihm deine Hand öffnen und ihm gegen Pfand leihen, was der
Not, die ihn bedrückt, abhilft.

<<v9>>
9 Nimm dich in Acht, dass du nicht in niederträchtigem Herzen den
Gedanken hegst: Bald kommt das siebte Jahr, das Brachjahr!, und deinen
armen Bruder böse ansiehst und ihm nichts gibst, sodass er den Herrn
gegen dich anruft und Strafe für diese Sünde über dich kommt. [fn:7]

<<v10>>
10 Du sollst ihm etwas geben, und wenn du ihm gibst, soll auch dein Herz
nicht böse darüber sein; denn wegen dieser Tat wird dich der Herr, dein
Gott, segnen in allem, was du arbeitest, und in allem, was deine Hände
schaffen.

<<v11>>
11 Die Armen werden niemals ganz aus deinem Land verschwinden. Darum
mache ich dir zur Pflicht: Du sollst deinem Not leidenden und armen
Bruder, der in deinem Land lebt, deine Hand öffnen. [fn:8]\\
\\

<<v12>>
* Die Selbstverknechtung: 15,12-18

12 Wenn dein Bruder, ein Hebräer - oder auch eine Hebräerin -, sich dir
verkauft, soll er dir sechs Jahre als Sklave dienen. Im siebten Jahr
sollst du ihn als freien Mann entlassen. [fn:9]

<<v13>>
13 Und wenn du ihn als freien Mann entlässt, sollst du ihn nicht mit
leeren Händen entlassen.

<<v14>>
14 Du sollst ihm von deinen Schafen und Ziegen, von deiner Tenne und von
deiner Kelter so viel mitgeben, wie er tragen kann. Wie der Herr, dein
Gott, dich gesegnet hat, so sollst du ihn bedenken. [fn:10]

<<v15>>
15 Denk daran: Als du in Ägypten Sklave warst, hat der Herr, dein Gott,
dich freigekauft. Darum verpflichte ich dich heute auf dieses Gebot. [fn:11]

<<v16>>
16 Wenn dieser Sklave dir aber erklärt: Ich will nicht von dir
freigelassen werden - denn er hat dich und deine Familie lieb gewonnen,
weil es ihm bei dir gut ging -,

<<v17>>
17 so nimm einen Pfriem und stich ihn durch sein Ohr in die Tür: Dann
ist er dein Sklave für immer. Bei einer Sklavin sollst du das Gleiche
tun.

<<v18>>
18 Halt es nicht für eine Härte, wenn du ihn als freien Mann entlassen
musst; denn was er in den sechs Jahren für dich erarbeitet hat,
entspricht dem, was du einem Tagelöhner als Lohn hättest zahlen müssen.
Dann wird der Herr, dein Gott, dich in allem segnen, was du tust.\\
\\

<<v19>>
* Die Erstgeburt des Viehs: 15,19-23

19 Alle männlichen Erstlinge, die unter deinen Rindern, Schafen und
Ziegen geboren werden, sollst du dem Herrn, deinem Gott, weihen. Mit
einem Erstlingsstier darfst du nicht arbeiten und ein Erstlingsschaf
darfst du nicht scheren. [fn:12]

<<v20>>
20 Jahr für Jahr sollst du die Erstlinge vor dem Herrn, deinem Gott, an
der Stätte, die der Herr auswählt, essen, du und deine Familie. [fn:13]

<<v21>>
21 Doch wenn ein Tier einen Fehler hat, wenn es hinkt oder blind ist,
wenn es irgendeinen Makel hat, sollst du es nicht für den Herrn, deinen
Gott, schlachten.

<<v22>>
22 In deinen Stadtbereichen sollst du es verzehren; der Reine und der
Unreine können es gemeinsam essen, wie bei Gazelle und Damhirsch. [fn:14]

<<v23>>
23 Nur das Blut sollst du nicht genießen, sondern wie Wasser auf die
Erde schütten.\\
\\

* Footnotes

[fn:1] (1-11) [[v9][15,9]].[[v12][12]]; [[file:Dtn_31.org::v10][31,10]]; [[file:Ex_23.org::v10][Ex 23,10f]]

[fn:2] 1-6: Das Gesetz über den Verzicht auf Forderungen in
jedem siebten Jahr wird als Weiterentwicklung des alten Brauchs der
Ackerbrache im siebten Jahr und zum Teil mit den dorthin gehörenden
Ausdrücken formuliert.

[fn:3] [[file:Dtn_23.org::v20][23,20f]]

[fn:4] (4-6) [[file:Dtn_28.org::v1][28,1-13]]

[fn:5] [[file:Dtn_28.org::v12][28,12]]

[fn:6] (7-8) [[file:~/RoamNotes/notes/Bibel/nt/1.Joh_3.org::v17][1 Joh 3,17]]

[fn:7] [[v1][15,1]]

[fn:8] [[file:~/RoamNotes/notes/Bibel/nt/Mt_26.org::v11][Mt 26,11]]; [[file:~/RoamNotes/notes/Bibel/nt/Mk_14.org::v7][Mk 14,7]]; [[file:~/RoamNotes/notes/Bibel/nt/Joh_12.org::v8][Joh 12,8]]

[fn:9] [[v1][15,1]]; [[file:~/RoamNotes/notes/Bibel/nt/Joh_8.org::v35][Joh 8,35]]; (12-18) [[file:Ex_21.org::v2][Ex 21,2-11]]; [[file:Jer_24.org::v8][Jer 34,8-22]]

[fn:10] Andere Lesart: Womit der Herr, dein Gott, dich
gesegnet hat, damit sollst du ihn bedenken.

[fn:11] [[file:Dtn_5.org::v15][5,15]]

[fn:12] (19-23) [[file:Ex_13.org::v2][Ex 13,2]].[[file:Ex_13.org::v11][11-16]]; [[file:Ex_22.org::v29][22,29]]; [[file:Ex_34.org::v19][34,19]]

[fn:13] [[file:Dtn_14.org::v23][14,23]]

[fn:14] (22-23) [[file:Dtn_12.org::v15][12,15f]].[[file:Dtn_12.org::v22][22-25]]
