#+TITLE: Esra 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 18:27]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Esra 9.html

<<verses>>

<<v1>>
* Das Verbot von Mischehen: 9,1-4

1 Als das vollbracht war, kamen die Obersten zu mir und sagten: Das Volk
Israel und die Priester und die Leviten haben sich nicht fern gehalten
von der Bevölkerung des Landes und ihren Gräueltaten, von den
Kanaanitern, Hetitern, Perisitern, Jebusitern, Ammonitern, Moabitern,
Ägyptern und Amoritern. [fn:1]

<<v2>>
2 Sie haben von deren Töchtern Frauen genommen für sich und ihre Söhne.
So hat sich der heilige Same mit den Völkern des Landes vermischt und
die Obersten und Beamten waren bei diesem Treubruch die Ersten. [fn:2]

<<v3>>
3 Als ich das hörte, zerriss ich mein Gewand und meinen Mantel; ich
raufte mir die Haare und den Bart und setzte mich erschüttert nieder.

<<v4>>
4 Da versammelten sich alle um mich, die wegen des Treubruchs der
Heimkehrer die Drohungen des Gottes Israels fürchteten. Bis zum
Abendopfer saß ich erschüttert da.\\
\\

<<v5>>
* Esras Bußgebet: 9,5-15

5 Zur Zeit des Abendopfers erhob ich mich aus meiner Bußübung, mit
zerrissenem Gewand und Mantel. Dann warf ich mich auf die Knie, breitete
die Hände aus und betete zum Herrn, meinem Gott:

<<v6>>
6 Mein Gott, ich schäme mich und wage nicht, die Augen zu dir, mein
Gott, zu erheben. Denn unsere Vergehen sind uns über den Kopf gewachsen;
unsere Schuld reicht bis zum Himmel.

<<v7>>
7 Seit den Tagen unserer Väter bis heute sind wir in großer Schuld.
Wegen unserer Vergehen wurden wir, unsere Könige und Priester, den
Königen der Länder ausgeliefert, dem Schwert, der Gefangenschaft, der
Plünderung und der Schande, wie es noch heute der Fall ist.

<<v8>>
8 Jetzt, für einen kurzen Augenblick, hat der Herr, unser Gott, uns
Erbarmen gezeigt; er hat einen Rest gerettet und übrig gelassen und uns
einen Ruheplatz an seinem heiligen Ort gewährt. So ließ unser Gott
unsere Augen aufleuchten, er ließ uns ein wenig aufleben in unserer
Knechtschaft.

<<v9>>
9 Ja, wir sind Knechte. Aber auch in unserer Knechtschaft hat unser Gott
uns nicht verlassen. Er wandte uns die Gunst der Könige von Persien zu.
Er ließ uns aufleben, sodass wir das Haus unseres Gottes wieder aufbauen
und es aus den Trümmern wieder aufrichten konnten. Er gewährte uns ein
geschütztes Gebiet in Juda und Jerusalem.

<<v10>>
10 Aber jetzt, unser Gott, was sollen wir nach all dem sagen? Wir haben
ja deine Gebote verlassen.

<<v11>>
11 Du hast durch deine Diener, die Propheten, geboten: Das Land, in das
ihr kommt, um es in Besitz zu nehmen, ist ein beflecktes Land; denn die
Völker im Land haben es befleckt; in ihrer Unreinheit haben sie es mit
ihren Gräueltaten erfüllt, vom einen Ende bis zum andern. [fn:3]

<<v12>>
12 Darum dürft ihr eure Töchter nicht ihren Söhnen als Frauen geben,
noch dürft ihr ihre Töchter für eure Söhne nehmen. Ihr Glück und ihren
Wohlstand sollt ihr nicht begehren. Dann werdet ihr stark sein und die
Güter des Landes genießen und sie euren Kindern vererben für alle Zeit.

<<v13>>
13 Was ist alles über uns gekommen wegen unserer bösen Taten und unserer
großen Schuld! Dabei hast du, unser Gott, unsere Schuld mit Nachsicht
behandelt und uns diese Schar von Geretteten gelassen.

<<v14>>
14 Können wir nach alledem von neuem deine Gebote brechen und uns mit
diesen gräuelbeladenen Völkern verschwägern? Musst du uns dann nicht
zürnen, bis wir ganz vernichtet sind, sodass kein Rest von Geretteten
mehr übrig bleibt?

<<v15>>
15 Herr, Gott Israels, du bist gerecht; darum hast du uns als geretteten
Rest übrig gelassen, wie es heute der Fall ist. Nun stehen wir vor dir
mit unserer Schuld. Nein, so kann niemand vor dir bestehen.\\
\\

* Footnotes

[fn:1] [[file:Dtn_7.org::v1][Dtn 7,1]]-[[file:Dtn_7.org::v4][4]]; [[file:Dtn_23.org::v3][23,3f]]

[fn:2] [[file:Mal_2.org::v10][Mal 2,10]]-[[file:Mal_2.org::v12][12]]; [[file:Neh_13.org::v23][Neh 13,23]]-[[file:Neh_13.org::v28][28]]; [[file:Jes_6.org::v13][Jes 6,13]]

[fn:3] [[file:Lev_18.org::v24][Lev 18,24]]-[[file:Lev_18.org::v27][27]]; [[file:Dtn_7.org::v1][Dtn 7,1]].[[file:Dtn_7.org::v3][3]]; [[file:Ez_36.org::v17][Ez 36,17]]; [[file:Ez_37.org::v25][37,25]]
