#+TITLE: Esra 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 09:22]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Esra 2.html

<<verses>>

<<v1>>
* Das Verzeichnis der heimkehrenden Laien: 2,1-35

1 Hier folgt eine Liste der Einwohner der Provinz Juda, die aus der
Gefangenschaft und der Verschleppung heimzogen. Nebukadnezzar, der König
von Babel, hatte sie nach Babel gebracht; nun kehrten sie nach Jerusalem
und Juda zurück, jeder in seine Stadt. [fn:1]

<<v2>>
2 Sie kamen zusammen mit Serubbabel, Jeschua, Nehemja, Seraja, Reelaja,
Mordochai, Bilschan, Misperet, Bigwai, Rehum und Baana. Das ist die Zahl
der Männer des Volkes Israel: [fn:2]

<<v3>>
3 Nachkommen des Parosch: 2172.

<<v4>>
4 Nachkommen Schefatjas: 372.

<<v5>>
5 Nachkommen Arachs: 775.

<<v6>>
6 Nachkommen des Pahat-Moab, und zwar Nachkommen Jeschuas und
Joabs: 2812.

<<v7>>
7 Nachkommen Elams: 1254.

<<v8>>
8 Nachkommen Sattus: 945.

<<v9>>
9 Nachkommen Sakkais: 760.

<<v10>>
10 Nachkommen Banis: 642.

<<v11>>
11 Nachkommen Bebais: 623.

<<v12>>
12 Nachkommen Asgads: 1222.

<<v13>>
13 Nachkommen Adonikams: 666.

<<v14>>
14 Nachkommen Bigwais: 2056.

<<v15>>
15 Nachkommen Adins: 454.

<<v16>>
16 Nachkommen Aters aus der Linie Hiskijas: 98.

<<v17>>
17 Nachkommen Bezais: 323.

<<v18>>
18 Nachkommen Joras: 112.

<<v19>>
19 Nachkommen Haschums: 223.

<<v20>>
20 Nachkommen Gibbars: 95.

<<v21>>
21 Männer aus Betlehem: 123.

<<v22>>
22 Männer aus Netofa: 56.

<<v23>>
23 Männer aus Anatot: 128.

<<v24>>
24 Männer aus Asmawet: 42.

<<v25>>
25 Männer aus Kirjat-Jearim, Kefira und Beerot: 743.

<<v26>>
26 Männer aus Rama und Geba: 621.

<<v27>>
27 Männer aus Michmas: 122.

<<v28>>
28 Männer aus Bet-El und Ai: 223.

<<v29>>
29 Männer aus Nebo: 52.

<<v30>>
30 Nachkommen des Magbisch: 156.

<<v31>>
31 Nachkommen eines anderen Elam: 1254.

<<v32>>
32 Nachkommen Harims: 320.

<<v33>>
33 Männer aus Lod, Hadid und Ono: 725.

<<v34>>
34 Männer aus Jericho: 345.

<<v35>>
35 Nachkommen Senaas: 3630.\\
\\

<<v36>>
* Das Verzeichnis der heimkehrenden Priester und Leviten: 2,36-63

36 Von den Priestern: Nachkommen Jedajas vom Haus Jeschua: 973. [fn:3]

<<v37>>
37 Nachkommen Immers: 1052.

<<v38>>
38 Nachkommen Paschhurs: 1247.

<<v39>>
39 Nachkommen Harims: 1017.

<<v40>>
40 Von den Leviten: Nachkommen Jeschuas, und zwar Nachkommen Kadmiëls,
Binnuis und Hodawjas: 74.

<<v41>>
41 Von den Sängern: Nachkommen Asafs: 128.

<<v42>>
42 Von den Torwächtern: Nachkommen Schallums, Nachkommen Aters,
Nachkommen Talmons, Nachkommen Akkubs, Nachkommen Hatitas, Nachkommen
Schobais, im Ganzen: 139.

<<v43>>
43 Von den Tempeldienern: Nachkommen Zihas, Nachkommen Hasufas,
Nachkommen Tabbaots, [fn:4]

<<v44>>
44 Nachkommen des Keros, Nachkommen Sias, Nachkommen Padons,

<<v45>>
45 Nachkommen Lebanas, Nachkommen Hagabas, Nachkommen Akkubs,

<<v46>>
46 Nachkommen Hagabs, Nachkommen Salmais, Nachkommen Hanans,

<<v47>>
47 Nachkommen Giddels, Nachkommen Gahars, Nachkommen Reajas,

<<v48>>
48 Nachkommen Rezins, Nachkommen Nekodas, Nachkommen Gasams,

<<v49>>
49 Nachkommen Usas, Nachkommen Paseachs, Nachkommen Besais,

<<v50>>
50 Nachkommen Asnas, Nachkommen der Mëuniter, Nachkommen der Nefusiter,

<<v51>>
51 Nachkommen Bakbuks, Nachkommen Hakufas, Nachkommen Harhurs,

<<v52>>
52 Nachkommen Bazluts, Nachkommen Mehidas, Nachkommen Harschas,

<<v53>>
53 Nachkommen des Barkos, Nachkommen Siseras, Nachkommen Temachs,

<<v54>>
54 Nachkommen Neziachs, Nachkommen Hatifas.

<<v55>>
55 Von den Nachkommen der Knechte Salomos: Nachkommen Sotais, Nachkommen
Soferets, Nachkommen Perudas, [fn:5]

<<v56>>
56 Nachkommen Jaalas, Nachkommen Darkons, Nachkommen Giddels,

<<v57>>
57 Nachkommen Schefatjas, Nachkommen Hattils, Nachkommen des
Pocheret-Zebajim und Nachkommen des Ami.

<<v58>>
58 Die Gesamtzahl der Tempeldiener und der Nachkommen der Knechte
Salomos betrug 392.

<<v59>>
59 Die Folgenden kamen aus Tel-Melach, Tel-Harscha, Kerub-Addon und
Immer, konnten aber nicht angeben, ob sie ihrer Familie und Herkunft
nach aus Israel stammten:

<<v60>>
60 Nachkommen Delajas, Nachkommen Tobijas und Nachkommen Nekodas, im
Ganzen 652;

<<v61>>
61 dazu bei den Priestern die Nachkommen Habajas, die Nachkommen des Koz
und die Nachkommen Barsillais; dieser hatte eine von den Töchtern
Barsillais aus Gilead geheiratet und dessen Namen angenommen. [fn:6]

<<v62>>
62 Die Genannten suchten ihre Eintragung im Geschlechterverzeichnis,
aber man fand sie nicht; deshalb wurden sie aus dem Priesterstand
ausgeschlossen.

<<v63>>
63 Der Statthalter untersagte ihnen, vom Hochheiligen zu essen, bis ein
Priester für den Losentscheid mit Urim und Tummim zur Verfügung stehe. [fn:7]\\
\\

<<v64>>
* Die Volkszählung: 2,64-70

64 Die ganze Volksgemeinde zählte insgesamt 42360 Personen. [fn:8]

<<v65>>
65 Dabei waren ihre Knechte und Mägde nicht mitgerechnet; das waren im
Ganzen 7337 Personen; dazu kamen noch 200 Sänger und Sängerinnen.

<<v66>>
66 Pferde hatten sie 736, Maultiere 245,

<<v67>>
67 Kamele 435, Esel 6720.

<<v68>>
68 Als sie zum Haus des Herrn in Jerusalem kamen, machten einige von den
Familienoberhäuptern großzügige Spenden, damit man das Gotteshaus an
seiner alten Stelle wieder errichten könne.

<<v69>>
69 Ihrem Vermögen entsprechend gaben sie für den Bauschatz 61000
Golddariken, 5000 Minen Silber und 100 Priestergewänder.

<<v70>>
70 Die Priester, die Leviten, ein Teil des Volkes, die Sänger, die
Torwächter und die Tempeldiener ließen sich in ihren Städten nieder,
ebenso alle übrigen Israeliten.\\
\\

* Footnotes

[fn:1] (1-35) [[file:Neh_7.org::v6][Neh 7,6]]-[[file:Neh_7.org::v38][38]]

[fn:2] Männer des Volkes Israel: die Laien im Unterschied zu
den in VV. 36-43 genannten Priestern und Leviten.

[fn:3] (36-63) [[file:Neh_7.org::v39][Neh 7,39]]-[[file:Neh_7.org::v65][65]]

[fn:4] [[file:Esra_8.org::v20][8,20]]

[fn:5] [[file:1.Kön_9.org::v20][1 Kön 9,20f]]

[fn:6] [[file:2.Sam_17.org::v27][2 Sam 17,27]]; [[file:2.Sam_19.org::v32][19,32]]

[fn:7] [[file:Lev_2.org::v3][Lev 2,3]]; [[file:Lev_6.org::v9][6,9]]-[[file:Lev_6.org::v11][11]]; [[file:Lev_7.org::v6][7,6]]-[[file:Lev_7.org::v10][10]].[[file:Lev_7.org::v33][33]]-[[file:Lev_7.org::v35][35]]; [[file:Ex_28.org::v30][Ex 28,30]]

[fn:8] (64-70) [[file:Neh_7.org::v66][Neh 7,66]]-[[file:Neh_7.org::v72][72]]
