#+TITLE: Esra 10 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 18:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Esra 10.html

<<verses>>

<<v1>>
* Die Auflösung der Mischehen: 10,1-17

1 Während Esra vor dem Haus Gottes auf den Knien lag und weinend sein
Gebet und sein Bekenntnis sprach, versammelte sich um ihn eine sehr
große Gemeinde von Männern, Frauen und Kindern aus Israel. Auch das Volk
vergoss viele Tränen.

<<v2>>
2 Schechanja, der Sohn Jehiëls, einer der Nachkommen Elams, nahm das
Wort und sagte zu Esra: Ja, wir haben unserem Gott die Treue gebrochen;
wir haben fremde Frauen aus der Bevölkerung des Landes geheiratet. Doch
auch jetzt gibt es noch Hoffnung für Israel:

<<v3>>
3 Wir wollen jetzt mit unserem Gott einen Bund schließen und uns
verpflichten, dass wir alle fremden Frauen samt ihren Kindern
wegschicken nach dem Rat meines Herrn und aller, die das Gebot unseres
Gottes fürchten. Man handle nach dem Gesetz.

<<v4>>
4 Steh auf! Denn dir obliegt die Sache. Wir aber stehen dir bei. Fass
Mut und handle!

<<v5>>
5 Da stand Esra auf; er ließ die Obersten der Priester, der Leviten und
ganz Israels schwören, nach diesem Vorschlag zu handeln, und sie
leisteten den Eid.

<<v6>>
6 Dann verließ Esra den Platz vor dem Haus Gottes und ging in die Kammer
Johanans, des Sohnes Eljaschibs. Dort verbrachte er die Nacht, aß aber
kein Brot und trank kein Wasser; denn er trauerte über den Treubruch der
Heimkehrer. [fn:1]

<<v7>>
7 Dann machte man in Juda und Jerusalem allen Heimkehrern bekannt, sie
sollten sich in Jerusalem versammeln.

<<v8>>
8 Jeder, der nicht binnen drei Tagen komme, wie es die Vorsteher und
Ältesten beschlossen hätten, dessen ganzer Besitz solle der Vernichtung
anheim fallen und er selbst solle aus der Gemeinde der Heimkehrer
ausgeschlossen werden. [fn:2]

<<v9>>
9 Da versammelten sich nach drei Tagen alle Männer von Juda und Benjamin
in Jerusalem; es war am zwanzigsten Tag des neunten Monats. Das ganze
Volk ließ sich auf dem Platz vor dem Haus Gottes nieder. Alle zitterten
wegen der Sache, um die es ging, aber auch wegen des Regens, der
niederging.

<<v10>>
10 Der Priester Esra stand auf und sagte zu ihnen: Ihr habt dem Herrn
die Treue gebrochen; ihr habt fremde Frauen genommen und so die Schuld
Israels noch größer gemacht.

<<v11>>
11 So legt nun vor dem Herrn, dem Gott eurer Väter, ein Bekenntnis ab
und tut, was er wünscht: Trennt euch von der Bevölkerung des Landes,
insbesondere von den fremden Frauen!

<<v12>>
12 Darauf antwortete die ganze Gemeinde laut: Alles, was du uns gesagt
hast, müssen wir tun.

<<v13>>
13 Aber es sind viele Menschen und es ist Regenzeit; da kann man nicht
im Freien bleiben und die Angelegenheit ist nicht an einem oder zwei
Tagen abzumachen. Denn viele von uns haben sich in dieser Sache
verfehlt.

<<v14>>
14 Unsere Vorsteher sollen darum die ganze Gemeinde vertreten. Alle, die
in unseren Städten fremde Frauen geheiratet haben, sollen dann zu
festgesetzten Zeiten herkommen, dazu die Ältesten und Richter jeder
einzelnen Stadt, bis wir den Zorn unseres Gottes, der wegen dieser Sache
entbrannt ist, von uns abgewendet haben.

<<v15>>
15 Nur Jonatan, der Sohn Asaëls, und Jachseja, der Sohn Tikwas, sprachen
gegen diesen Vorschlag; Meschullam und der Levit Schabbetai
unterstützten sie.

<<v16>>
16 Die Heimkehrer machten es aber so, wie vorgeschlagen worden war. Der
Priester Esra wählte Männer aus, für jede Großfamilie ein
Familienoberhaupt; alle wurden mit Namen aufgerufen. Am ersten Tag des
zehnten Monats traten sie zusammen, um die Sache zu untersuchen,

<<v17>>
17 und am ersten Tag des ersten Monats waren sie fertig mit den Fällen
aller Männer, die fremde Frauen geheiratet hatten.\\
\\

<<v18>>
* Die Liste der Betroffenen: 10,18-44

18 Unter den Priestern fand man folgende, die fremde Frauen geheiratet
hatten: Von den Nachkommen Jeschuas, des Sohnes des Jozadak, und seinen
Brüdern: Maaseja, Eliëser, Jarib und Gedalja. [fn:3]

<<v19>>
19 Sie gaben die Hand darauf, ihre Frauen wegzuschicken, und brachten
für ihre Schuld einen Widder als Schuldopfer dar. [fn:4]

<<v20>>
20 Von den Nachkommen Immers fand man schuldig: Hanani und Sebadja;

<<v21>>
21 von den Nachkommen Harims: Maaseja, Elija, Schemaja, Jehiël und
Usija;

<<v22>>
22 von den Nachkommen Paschhurs: Eljoënai, Maaseja, Jischmael, Netanel,
Josabad und Elasa.

<<v23>>
23 Von den Leviten: Josabad, Schimi, Kelaja, das ist Kelita, Petachja,
Juda und Eliëser.

<<v24>>
24 Von den Sängern: Eljaschib. Von den Torwächtern: Schallum, Telem und
Uri.

<<v25>>
25 Unter den Israeliten von den Nachkommen des Parosch: Ramja, Jisija,
Malkija, Mijamin, Eleasar, Malkija und Benaja; [fn:5]

<<v26>>
26 von den Nachkommen Elams: Mattanja, Secharja, Jehiël, Abdi, Jeremot
und Elija;

<<v27>>
27 von den Nachkommen Sattus: Eljoënai, Eljaschib, Mattanja, Jeremot,
Sabad und Asisa;

<<v28>>
28 von den Nachkommen Bebais: Johanan, Hananja, Sabbai und Atlai;

<<v29>>
29 von den Nachkommen Banis: Meschullam, Malluch, Adaja, Jaschub, Scheal
und Jeremot;

<<v30>>
30 von den Nachkommen des Pahat-Moab: Adna, Kelal, Benaja, Maaseja,
Mattanja, Bezalel, Binnui und Manasse;

<<v31>>
31 von den Nachkommen Harims: Eliëser, Jischija, Malkija, Schemaja,
Simeon,

<<v32>>
32 Benjamin, Malluch und Schemarja;

<<v33>>
33 von den Nachkommen Haschums: Mattenai, Mattatta, Sabad, Elifelet,
Jeremai, Manasse und Schimi;

<<v34>>
34 von den Nachkommen Bigwais: Maadai, Amram, Uël,

<<v35>>
35 Benaja, Bedja, Keluhi,

<<v36>>
36 Wanja, Meremot, Eljaschib,

<<v37>>
37 Mattanja, Mattenai und Jaasai;

<<v38>>
38 von den Nachkommen Binnuis: Schimi,

<<v39>>
39 Schelemja, Natan und Adaja;

<<v40>>
40 von den Nachkommen Sakkais: Schaschai, Scharai,

<<v41>>
41 Asarel, Schelemja, Schemarja,

<<v42>>
42 Schallum, Amarja und Josef;

<<v43>>
43 von den Nachkommen Nebos: Jëiël, Mattitja, Sabad, Sebina, Jaddai,
Joël und Benaja.

<<v44>>
44 Alle diese hatten fremde Frauen geheiratet; sie trennten sich nun von
ihren Frauen, auch wenn sie von ihnen Kinder hatten. [fn:6]\\
\\

* Footnotes

[fn:1] [[file:Neh_13.org::v4][Neh 13,4]]

[fn:2] [[file:Esra_7.org::v26][7,26]]

[fn:3] [[file:Esra_2.org::v36][2,36]]-[[file:Esra_2.org::v39][39]]

[fn:4] [[file:Lev_5.org::v14][Lev 5,14]]-[[file:Lev_5.org::v19][19]]

[fn:5] (25-43) [[file:Esra_2.org::v3][2,3]]-[[file:Esra_2.org::v35][35]]

[fn:6] Text gestört, daher Übersetzung unsicher.
