#+TITLE: Esra 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 09:17]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Esra 1.html

* Die Bücher Esra und Nehemia

Die Bücher Esra und Nehemia bilden nach weit verbreiteter Meinung
zusammen mit den Büchern der Chronik das Chronistische Geschichtswerk.
Im Rahmen dieser Geschichtsdarstellung, die mit der Begründung der
Gottesherrschaft in Israel unter David und Salomo anhebt, um
anschließend am Beispiel der Königszeit die Treulosigkeit des
Gottesvolkes, aber auch die dem Sünder stets gewährte Möglichkeit der
Umkehr zu verdeutlichen, berichten die Bücher Esra und Nehemia von der
heilvollen Wende in der Geschichte des Gottesvolkes nach dem
Babylonischen Exil.\\
\\
Die verbannten Judäer erhalten durch den Erlass des Perserkönigs Kyrus
die Erlaubnis, nach Jerusalem heimzukehren und den Tempel wieder
aufzubauen (Esra 1 - 6). Als aber nach der Einweihung des neu
errichteten Tempels die Festigung des jungen Gemeinwesens ins Stocken
gerät, kommt im Auftrag des persischen Königs der Priester und
Schriftgelehrte Esra nach Jerusalem, um in der Heimat die Verhältnisse
nach dem Gesetz des Mose zu ordnen (Esra 7 - 10). In Verbindung mit ihm
bemüht sich auch Nehemia, der bis dahin am persischen Hof eine hohe
Beamtenstelle innegehabt hat, um den Wiederaufbau der Mauern Jerusalems
(Neh 1 - 6) sowie um die Reform des religiösen Lebens und um die
Beseitigung ärgerniserregender Missstände (Neh 7 - 13).\\
\\
Im Rahmen des Chronistischen Geschichtswerkes stellt der Verfasser der
Bücher Esra und Nehemia die Zeit nach dem Babylonischen Exil in
Jerusalem und Juda so dar, dass sie deutlich an die Begründung der
Gottesherrschaft in Israel nach dem Scheitern des Königtums Sauls
erinnert. Der Wiederaufbau Jerusalems, die Einweihung des Tempels und
die Neubegründung des religiösen Lebens im Land nach dem Gesetz des Mose
bezeichnen darum nach der Meinung des Verfassers die Wende vom Unheil
zum Heil, von einer Zeit des Gerichts und des Zorns zu einer Zeit der
neuen Zuwendung Gottes zu Israel und Israels zu seinem Gott. Und wie
nach chronistischer Darstellung die Zeit Davids nur als Vorstufe zu der
als Ideal der Gottesherrschaft geschilderten Zeit Salomos erscheint, so
wird auch bei der Neuordnung der Gemeinde unter Esra und Nehemia der
Abstand deutlich, der diese Zeit von der noch ausstehenden endgültigen
Offenbarung der Herrlichkeit Gottes über Israel trennt.\\
\\
Die von Esra und Nehemia wiederholt ausgesprochene Mahnung, Gott und
seinem Gesetz die Treue zu halten und sich auf seine Führung zu
verlassen, gilt daher einer Gemeinde, die sich zwar als »heiliger Same«
(Esra 9,2) und als »geretteter Rest« (Esra 9,15) begreift, die aber noch
ein endgültiges Heilshandeln Gottes erwartet.\\
\\
Die Bücher Esra und Nehemia, die auch aramäisch geschriebene Urkunden
aus der Perserzeit verwenden (Esra 4,8 - 6,18; 7,12-26), sind zusammen
mit den Büchern der Chronik um 400 v. Chr. oder etwas später in
Jerusalem verfasst worden.\\
\\

<<verses>>

<<v1>>

* Die Heimkehr der Juden und der Wiederaufbau des Tempels: 1,1 - 6,22

* Die Erlaubnis zur Heimkehr und zum Tempelbau: 1,1-11

Im ersten Jahr des Königs Kyrus von Persien sollte sich erfüllen, was
der Herr durch Jeremia gesprochen hatte. Darum erweckte der Herr den
Geist des Königs Kyrus von Persien und Kyrus ließ in seinem ganzen Reich
mündlich und schriftlich den Befehl verkünden: [fn:1]

<<v2>>
2 So spricht der König Kyrus von Persien: Der Herr, der Gott des
Himmels, hat mir alle Reiche der Erde verliehen. Er selbst hat mir
aufgetragen, ihm in Jerusalem in Juda ein Haus zu bauen. [fn:2]

<<v3>>
3 Jeder unter euch, der zu seinem Volk gehört - sein Gott sei mit ihm -,
der soll nach Jerusalem in Juda hinaufziehen und das Haus des Herrn, des
Gottes Israels, aufbauen; denn er ist der Gott, der in Jerusalem wohnt.

<<v4>>
4 Und jeden, der irgendwo übrig geblieben ist, sollen die Leute des
Ortes, in dem er ansässig war, unterstützen mit Silber und Gold, mit
beweglicher Habe und Vieh, neben den freiwilligen Gaben für das Haus
Gottes in Jerusalem.

<<v5>>
5 Die Familienoberhäupter von Juda und Benjamin sowie die Priester und
Leviten, kurz alle, deren Geist Gott erweckte, machten sich auf den Weg,
um nach Jerusalem zu ziehen und dort das Haus des Herrn zu bauen.

<<v6>>
6 Alle ihre Nachbarn unterstützten sie in jeder Weise mit Silber und
Gold, mit beweglicher Habe und mit Vieh sowie mit wertvollen Dingen,
abgesehen von dem, was jeder für den Tempel spendete.

<<v7>>
7 König Kyrus gab auch die Geräte des Hauses des Herrn zurück, die
Nebukadnezzar aus Jerusalem weggeschleppt und in das Haus seines Gottes
gebracht hatte.

<<v8>>
8 König Kyrus von Persien übergab sie dem Schatzmeister Mitredat und
dieser zählte sie Scheschbazzar, dem Oberen von Juda, vor.

<<v9>>
9 Das war ihre Zahl: 30 goldene Opferschalen, 1000 silberne
Opferschalen, 29 Räucherpfannen,

<<v10>>
10 30 goldene Becher, 410 silberne Becher, 1000 sonstige Geräte.

<<v11>>
11 Insgesamt waren es 5400 Geräte aus Gold und Silber. All das brachte
Scheschbazzar mit, als er mit den Verschleppten von Babel nach Jerusalem
zurückkehrte. [fn:3]\\
\\

* Footnotes

[fn:1] (1-3) [[file:2.Chr_36.org::v22][2 Chr 36,22f]]; [[file:Jer_25.org::v11][Jer 25,11f]]; [[file:Jer_29.org::v10][29,10]]

[fn:2] [[file:Jes_44.org::v28][Jes 44,28]]; [[file:Jes_45.org::v1][45,1]]-[[file:Jes_45.org::v4][4]]

[fn:3] Die angegebene Gesamtzahl der Tempelgeräte übersteigt
die Summe der vorher wohl nur als Beispiele genannten Einzelposten (vgl.
auch [[file:Bar_1.org::v8][Bar 1,8]]).
