#+TITLE: Esra 6 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 18:14]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Esra 6.html

<<verses>>

<<v1>>
* Der Weiterbau mit königlicher Unterstützung: 6,1-12

1 Auf Befehl des Königs Darius forschte man nun in den Schatzhäusern
nach, dort, wo in Babel die Urkunden aufbewahrt wurden.

<<v2>>
2 In der Festung Ekbatana in der Provinz Medien fand man eine
Schriftrolle, in der geschrieben war: Beurkundung:

<<v3>>
3 Im ersten Jahr des Königs Kyrus hat König Kyrus einen Befehl erlassen,
der das Gotteshaus in Jerusalem betrifft: Das Haus soll wieder aufgebaut
werden als Ort, an dem man Opfer darbringt. Seine Fundamente sollen
erhalten bleiben. Seine Höhe soll sechzig Ellen betragen und seine
Breite zwanzig Ellen.

<<v4>>
4 Auf drei Lagen Quadersteinen soll eine Lage Holz kommen. Die Kosten
bestreitet der königliche Hof.

<<v5>>
5 Auch soll man die goldenen und silbernen Geräte des Gotteshauses
zurückgeben, die Nebukadnezzar aus dem Tempel von Jerusalem weggenommen
und nach Babel gebracht hat. Alles soll wieder an seinen alten Platz in
den Tempel von Jerusalem kommen und in das Gotteshaus gebracht werden.

<<v6>>
6 Darum, Tattenai, Statthalter des Gebiets jenseits des Stroms,
Schetar-Bosnai und eure Amtsgenossen, die Beamten des Gebiets jenseits
des Stroms: Haltet euch aus der Sache dort heraus!

<<v7>>
7 Lasst die Arbeit an jenem Gotteshaus weitergehen! Der Statthalter der
Juden und ihre Ältesten mögen das Gotteshaus an seiner früheren Stelle
wieder aufbauen.

<<v8>>
8 Auch ordne ich an, wie ihr die Ältesten der Juden dort beim Bau jenes
Gotteshauses unterstützen sollt: Aus den königlichen Einkünften, die das
Gebiet jenseits des Stroms aufbringt, sollen jenen Männern pünktlich die
Kosten bezahlt werden, damit sie nicht aufgehalten werden.

<<v9>>
9 Auch ist ihnen jeden Tag ohne Versäumnis zu liefern, was nach den
Angaben der Priester von Jerusalem an Stieren, Widdern und Lämmern als
Brandopfer für den Gott des Himmels benötigt wird, auch Weizen und Salz,
Wein und Öl.

<<v10>>
10 So mögen sie dem Gott des Himmels wohlgefällige Opfer darbringen und
auch für das Leben des Königs und seiner Söhne beten.

<<v11>>
11 Schließlich befehle ich: Jedem, der diesen Erlass missachtet, reiße
man einen Balken aus seinem Haus und pfähle ihn auf diesem Balken; sein
Haus soll wegen seines Vergehens zu einem Trümmerhaufen gemacht werden.

<<v12>>
12 Der Gott aber, der seinen Namen dort wohnen lässt, vernichte jeden
König und jedes Volk, die sich unterfangen, den Erlass zu missachten und
jenes Gotteshaus in Jerusalem zu zerstören. Ich, Darius, habe den Befehl
gegeben; man befolge ihn genau.\\
\\

<<v13>>
* Die Vollendung des Baus und die Tempelweihe: 6,13-22

13 Tattenai, der Statthalter des Gebiets jenseits des Stroms,
Schetar-Bosnai und ihre Amtsgenossen befolgten genau den Befehl, den der
König Darius gesandt hatte,

<<v14>>
14 und die Ältesten der Juden bauten weiter. Dank der Wirksamkeit
Haggais, des Propheten, und Sacharjas, des Sohnes Iddos, kamen sie gut
voran. Sie konnten den Bau vollenden, wie der Gott Israels es geboten
und wie Kyrus und Darius sowie der Perserkönig Artaxerxes es befohlen
hatten. [fn:1]

<<v15>>
15 Das Gotteshaus war fertig am dritten Tag des Monats Adar, im sechsten
Jahr der Regierung des Königs Darius.

<<v16>>
16 Die Israeliten, die Priester, die Leviten und die übrigen, die
heimgekehrt waren, feierten voll Freude die Einweihung dieses
Gotteshauses. [fn:2]

<<v17>>
17 Bei der Einweihung des Gotteshauses brachten sie als Opfer dar:
hundert Stiere, zweihundert Widder und vierhundert Lämmer, dazu als
Sündopfer für ganz Israel zwölf Ziegenböcke, entsprechend der Zahl der
Stämme Israels. [fn:3]

<<v18>>
18 Für den Gottesdienst in Jerusalem bestellten sie die Priester nach
ihren Klassen und die Leviten nach ihren Abteilungen, wie es das Buch
des Mose vorschreibt. [fn:4]

<<v19>>
19 Am vierzehnten Tag des ersten Monats feierten die Heimkehrer das
Pascha-Fest. [fn:5] [fn:6]

<<v20>>
20 Jeder der Priester und Leviten hatte sich gereinigt, sodass sie alle
rein waren. Die Leviten schlachteten das Paschalamm für alle Heimkehrer
und für ihre Brüder, die Priester, und für sich selbst.

<<v21>>
21 Dieses Paschalamm aßen die Israeliten, die aus der Verbannung
heimgekehrt waren, sowie alle, die sich von der Unreinheit der Völker
des Landes abgesondert hatten, um mit ihnen zusammen den Herrn, den Gott
Israels, zu suchen.

<<v22>>
22 Sieben Tage lang feierten sie voll Freude das Fest der Ungesäuerten
Brote. Denn der Herr hatte sie froh gemacht und ihnen das Herz des
Königs von Assur zugewandt, sodass er sie bei der Arbeit am Haus Gottes,
des Gottes Israels, unterstützte.\\
\\

* Footnotes

[fn:1] [[file:Esra_5.org::v1][5,1]]; [[file:Esra_1.org::v2][1,2]]; [[file:Esra_7.org::v19][7,19]]-[[file:Esra_7.org::v24][24]]

[fn:2] (16-17) [[file:1.Kön_8.org::v1][1 Kön 8,1f]].[[file:1.Kön_8.org::v62][62]]-[[file:1.Kön_8.org::v65][65]]

[fn:3] [[file:2.Chr_29.org::v20][2 Chr 29,20]]-[[file:2.Chr_29.org::v32][32]]

[fn:4] [[file:1.Chr_24.org::v19][1 Chr 24,19]]

[fn:5] [[file:2.Chr_35.org::v10][2 Chr 35,10]]-[[file:2.Chr_35.org::v15][15]]

[fn:6] Von hier ab ist der Urtext wieder hebräisch, vgl. die Anmerkung zu 4,8.
