#+TITLE: Esra 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 18:19]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Esra 7.html

<<verses>>

<<v1>>
* Esra und die Neuordnung der Gemeinde in Jerusalem: 7,1 - 10,44

* Esra, der Gesetzeslehrer: 7,1-10

1 Nach diesen Ereignissen unter der Herrschaft des Perserkönigs
Artaxerxes kam Esra, der Sohn Serajas, des Sohnes Asarjas, des Sohnes
Hilkijas, [fn:1]

<<v2>>
2 des Sohnes Schallums, des Sohnes Zadoks, des Sohnes Ahitubs,

<<v3>>
3 des Sohnes Amarjas, des Sohnes Asarjas, des Sohnes Merajots,

<<v4>>
4 des Sohnes Serachjas, des Sohnes Usis, des Sohnes Bukkis,

<<v5>>
5 des Sohnes Abischuas, des Sohnes des Pinhas, des Sohnes Eleasars, des
Sohnes des Hohenpriesters Aaron.

<<v6>>
6 Dieser Esra kam also von Babel herauf. Er war ein Schriftgelehrter,
kundig im Gesetz des Mose, das der Herr, der Gott Israels, gegeben
hatte. Weil die Hand des Herrn, seines Gottes, über ihm war, gewährte
der König ihm alles, was er wünschte.

<<v7>>
7 Mit ihm zog im siebten Jahr des Königs Artaxerxes auch eine Anzahl von
Israeliten sowie von Priestern, Leviten, Sängern, Torwächtern und
Tempeldienern nach Jerusalem.

<<v8>>
8 Im fünften Monat dieses siebten Regierungsjahrs des Königs kam Esra in
Jerusalem an.

<<v9>>
9 Den Aufbruch von Babel hatte er auf den Ersten des ersten Monats
festgesetzt und am Ersten des fünften Monats kam er in Jerusalem an, da
die gütige Hand seines Gottes über ihm war.

<<v10>>
10 Denn Esra war von ganzem Herzen darauf aus, das Gesetz des Herrn zu
erforschen und danach zu handeln und es als Satzung und Recht in Israel
zu lehren.\\
\\

<<v11>>
* Der zweite Befehl zur Rückführung: 7,11-23

11 Das ist eine Abschrift des Erlasses, den der König Artaxerxes dem
Priester und Schriftgelehrten Esra mitgab, dem Schriftkundigen in den
Geboten und Satzungen, die der Herr Israel gegeben hatte:

<<v12>>
12 Artaxerxes, der König der Könige, wünscht dem Priester Esra, dem
Schriftkundigen im Gesetz des Gottes des Himmels, alles Gute. [fn:2]

<<v13>>
13 Das ist es, was ich befehle: Jeder in meinem Reich, der zum Volk
Israel oder seinen Priestern und Leviten gehört und gewillt ist, nach
Jerusalem zu gehen, darf mit dir ziehen.

<<v14>>
14 Denn du bist von dem König und seinen sieben Räten ausgesandt und
sollst nach dem Gesetz deines Gottes, das in deiner Hand ist,
untersuchen, wie es in Juda und Jerusalem steht. [fn:3]

<<v15>>
15 Auch sollst du das Silber und Gold hinbringen, das der König und
seine Räte dem Gott Israels gespendet haben, der in Jerusalem seine
Wohnstätte hat. [fn:4]

<<v16>>
16 Bring auch alles Silber und Gold dorthin, das du in der ganzen
Provinz Babel bekommst, samt den Spenden, die das Volk Israel und die
Priester für das Haus ihres Gottes in Jerusalem geben.

<<v17>>
17 Von diesem Geld sollst du dann gewissenhaft Stiere, Widder und Lämmer
sowie die dazugehörenden Speiseopfer und Trankopfer kaufen und sie auf
dem Altar des Hauses eures Gottes in Jerusalem darbringen.

<<v18>>
18 Das übrige Silber und Gold dürft ihr nach dem Willen eures Gottes
verwenden, wie es dir und deinen Amtsbrüdern gut scheint.

<<v19>>
19 Auch die Geräte, die man dir für den Dienst im Haus deines Gottes
übergibt, sollst du dem Gott in Jerusalem abliefern.

<<v20>>
20 Den restlichen Bedarf für das Haus deines Gottes, den du aufzubringen
hast, bekommst du aus den königlichen Schatzhäusern. [fn:5]

<<v21>>
21 Ich, der König Artaxerxes, befehle allen Schatzmeistern im Gebiet
jenseits des Stroms: Alles, was der Priester Esra, der Schriftkundige im
Gesetz des Gottes des Himmels, von euch fordert, soll man pünktlich
liefern,

<<v22>>
22 und zwar bis zu hundert Talenten Silber, bis zu hundert Kor Weizen,
bis zu hundert Bat Wein, bis zu hundert Bat Öl, dazu Salz in jeder
Menge.

<<v23>>
23 Alles, was der Gott des Himmels befiehlt, soll man mit frommem Eifer
liefern für das Haus des Gottes des Himmels, damit nicht ein
Strafgericht das Reich des Königs und seiner Söhne trifft.\\
\\

<<v24>>
* Neue Anordnungen: 7,24-28

24 Auch wird euch Folgendes bekannt gemacht: Niemand ist befugt,
irgendeinem Priester, Leviten, Sänger, Torwächter, Tempeldiener oder
Arbeiter dieses Gotteshauses Steuern, Abgaben oder Zölle aufzuerlegen.

<<v25>>
25 Du aber, Esra, bestelle Rechtskundige und Richter nach dem weisen
Gesetz deines Gottes, das in deiner Hand ist; sie sollen dem ganzen Volk
im Gebiet jenseits des Stroms Recht sprechen, allen, die das Gesetz
deines Gottes kennen; wer es aber nicht kennt, den sollt ihr es lehren.

<<v26>>
26 Doch über jeden, der das Gesetz deines Gottes und das Gesetz des
Königs nicht befolgt, halte man streng Gericht und verurteile ihn je
nachdem zum Tod, zum Ausschluss (aus der Gemeinde), zu einer Geldstrafe
oder zu Gefängnis! [fn:6]

<<v27>>
27 Gepriesen sei der Herr, der Gott unserer Väter! Denn er hat dem König
das alles ins Herz gelegt, um das Haus des Herrn in Jerusalem so
herrlich auszustatten.

<<v28>>
28 Mir hat er die Gunst des Königs und seiner Räte sowie all der
mächtigen Großen des Königs zugewandt. Ich aber fasste Mut, da die Hand
des Herrn, meines Gottes, über mir war, und sammelte Familienoberhäupter
aus Israel, die bereit waren, mit mir hinaufzuziehen.\\
\\

* Footnotes

[fn:1] [[file:1.Chr_5.org::v29][1 Chr 5,29]]-[[file:1.Chr_5.org::v40][40]]

[fn:2] 12-26: Das Schreiben des Artaxerxes ist in aramäischer
Sprache überliefert (vgl. [[file:Esra_4.org::v8][4,8]] - [[file:Esra_6.org::v18][6,18]]).

[fn:3] [[file:Est_1.org::v14][Est 1,14]]

[fn:4] [[file:2.Makk_3.org::v2][2 Makk 3,2]]

[fn:5] [[file:Esra_6.org::v9][6,9]]

[fn:6] Gemeint ist der Ausschluss aus der Gemeinde der
Heimgekehrten (vgl. [[file:Esra_10.org::v8][10,8]]).
