#+TITLE: Est 8 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-25 Sa 21:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Est 8.html

<<verses>>

<<v1>>
* Die Rettung der Juden: 8,1 - 10,3

* Mordechais Erhöhung und Esters erneute Bitte: 8,1-6

1 Noch am gleichen Tag schenkte König Artaxerxes der Königin Ester das
Haus des Judenfeindes Haman. Mordechai aber erhielt Zutritt zum König;
denn Ester hatte dem König gesagt, wie nahe Mordechai mit ihr verwandt
war. [fn:1]

<<v2>>
2 Der König zog seinen Siegelring, den er Haman hatte abnehmen lassen,
vom Finger und gab ihn Mordechai. Ester machte Mordechai zum Verwalter
von Hamans Haus.

<<v3>>
3 Ester redete noch einmal mit dem König; sie fiel ihm weinend zu Füßen
und flehte ihn an, das drohende Unheil, das der Agagiter Haman gegen die
Juden geplant hatte, von ihnen abzuwenden.

<<v4>>
4 Der König streckte Ester sein goldenes Zepter entgegen und Ester stand
auf und trat vor den König.

<<v5>>
5 Sie sagte: Wenn es dem König gefällt und ich sein Wohlwollen gefunden
habe, wenn ihm mein Vorschlag richtig erscheint und ich seine Gunst
genieße, dann soll durch einen schriftlichen Erlass die Anordnung
widerrufen werden, die der Agagiter Haman, der Sohn Hammedatas, in der
Absicht getroffen hat, die Juden in allen königlichen Provinzen
auszurotten.

<<v6>>
6 Denn wie könnte ich das Unglück mit ansehen, das mein Volk trifft, wie
könnte ich den Untergang meines Stammes mit ansehen?\\
\\

<<v7>>
* Der Erlass zum Schutz der Juden: 8,7-17

7 Da sagte König Artaxerxes zu Königin Ester und zu dem Juden Mordechai:
Ich habe Ester das Haus Hamans übergeben, den man am Galgen aufgehängt
hat, weil er seine Hand gegen die Juden erhob.

<<v8>>
8 Jetzt aber sollt ihr im Namen des Königs einen schriftlichen Erlass
zugunsten der Juden herausgeben, wie er euch richtig erscheint. Siegelt
ihn mit dem königlichen Siegelring; denn ein Schreiben, das im Namen des
Königs verfasst und mit dem königlichen Siegelring gesiegelt ist, kann
nicht mehr rückgängig gemacht werden.

<<v9>>
9 Da rief man die königlichen Schreiber; es war der dreiundzwanzigste
Tag im dritten Monat, dem Monat Siwan. Und so, wie es Mordechai befahl,
wurde zugunsten der Juden ein schriftlicher Erlass herausgegeben und an
die Satrapen, Statthalter und Fürsten der hundertsiebenundzwanzig
Provinzen von Indien bis Kusch geschickt, für jede einzelne Provinz in
ihrer eigenen Schrift und für jedes einzelne Volk in seiner eigenen
Sprache.

<<v10>>
10 Man verfasste die Schreiben im Namen des Königs Artaxerxes, siegelte
mit dem königlichen Siegelring und verschickte sie mit Eilboten auf
Postpferden, die aus den königlichen Gestüten stammten.

<<v11>>
11 Mit diesem Erlass gestattete der König den Juden in allen Städten,
sich zusammenzutun, um für ihr Leben einzutreten, um in jedem Volk und
in jeder Provinz alle ihre Gegner samt ihren Frauen und Kindern zu
erschlagen, zu ermorden und auszurotten und ihren Besitz zu plündern;

<<v12>>
12 das sollte in allen Provinzen des Königs Artaxerxes am gleichen Tag
geschehen, am dreizehnten Tag im zwölften Monat, dem Monat Adar. [fn:2]

<<v12a>>
12a Dies ist eine Abschrift des Briefes:

<<v12b>>
12b Der Großkönig Artaxerxes entbietet den Statthaltern der
hundertsiebenundzwanzig Provinzen von Indien bis Kusch und allen, denen
unsere Angelegenheiten am Herzen liegen, seinen Gruß.

<<v12c>>
12c Viele, die aufgrund der überreichen Güte ihrer Wohltäter hoch geehrt
waren, waren damit noch nicht zufrieden; sie versuchten nicht nur,
unseren Untertanen zu schaden, sondern sie konnten auch den Überfluss
nicht ertragen und planen sogar Anschläge gegen ihre eigenen Wohltäter.

<<v12d>>
12d Sie wollen nicht nur die Dankbarkeit unter den Menschen beseitigen,
sondern sie sind durch die Prahlerei derer, die vom Guten nichts wissen
wollen, überheblich geworden und meinen, dem Gericht des alles
durchschauenden Gottes, der das Böse hasst, entfliehen zu können.

<<v12e>>
12e Schon viele, die als Herrscher eingesetzt waren, hat der schlechte
Einfluss von Freunden, die mit den Staatsgeschäften betraut waren,
mitschuldig am Tod Unschuldiger gemacht und sie in schreckliches Unglück
gestürzt.

<<v12f>>
12f Das lautere Wohlwollen der Herrschenden wurde durch ihre böswilligen
und verlogenen Ratschläge getäuscht.

<<v12g>>
12g Das ersieht man schon aus den altüberlieferten Geschichten; noch
viel deutlicher aber wird es, wenn ihr all das untersucht, was vor euren
Augen geschehen ist: Die Niederträchtigkeit derer, die ihr hohes Amt
missbrauchten, hat zu großem Unrecht geführt.

<<v12h>>
12h In Anbetracht der veränderten Lage nehmen wir uns vor, in Zukunft
darauf zu achten, dass alle Menschen im Reich ungestört und in Frieden
leben können;

<<v12i>>
12i alles, was uns zur Kenntnis gebracht wird, werden wir erst nach
genauerem Zusehen entscheiden.

<<v12k>>
12k So ging es auch mit dem Mazedonier Haman, dem Sohn Hammedatas.
Obwohl er in Wahrheit dem persischen Volk und unserer Güte sehr fern
stand, wurde er bei uns gastlich aufgenommen.

<<v12l>>
12l Er erfuhr unsere Liebe zu den Menschen, die wir allen Völkern
erweisen, in so reichem Maß, dass er sogar als unser Vater ausgerufen
wurde und als der zweite Mann neben dem König bei allen immer höchste
Verehrung genoss.

<<v12m>>
12m Doch er ertrug seine hohe Würde nicht, sondern er wollte uns die
Herrschaft und das Leben rauben.

<<v12n>>
12n Er versuchte, Mordechai, unseren Retter und steten Wohltäter, und
Ester, die untadelige Mitinhaberin der Königswürde, durch hinterhältige
Intrigen mit ihrem ganzen Volk ins Verderben zu stürzen.

<<v12o>>
12o Auf diese Weise glaubte er, uns aller Freunde zu berauben und die
Herrschaft über die Perser den Mazedoniern verschaffen zu können.

<<v12p>>
12p Wir aber finden, dass die Juden, die dieser Erzschurke ausrotten
wollte, keine Aufrührer sind, sondern dass sie als Bürger nach sehr
gerechten Gesetzen leben,

<<v12q>>
12q als Kinder des höchsten, größten und lebendigen Gottes, der unser
Reich, wie schon zu Zeiten unserer Vorfahren, in der schönsten Ordnung
erhält.

<<v12r>>
12r Es wird daher gut sein, wenn ihr euch nicht nach den Schreiben
richtet, die euch Haman, der Sohn Hammedatas, geschickt hat. Denn ihr
Verfasser ist mit seiner ganzen Familie vor den Toren Susas gekreuzigt
worden; der über alles herrschende Gott hat ihm nämlich sehr bald die
wohlverdiente Strafe geschickt.

<<v12s>>
12s Ihr sollt überall eine Abschrift dieses Briefes öffentlich
aushängen, damit man die Juden nach ihren eigenen Gesetzen leben lässt.
Man soll ihnen helfen, sich an dem einen Tag, der für ihre Verfolgung
festgesetzt war, gegen alle zu verteidigen, von denen sie angegriffen
werden; es ist der dreizehnte Tag im zwölften Monat, dem Monat Adar.

<<v12t>>
12t Diesen Tag hat der alles beherrschende Gott statt zu einem Tag der
Vernichtung für das auserwählte Volk zu einem Tag der Freude gemacht.

<<v12u>>
12u Daher sollt ihr neben euren großen Gedenktagen einen weiteren
besonderen Festtag mit aller Freude feiern, damit er von jetzt an uns
und allen uns treu ergebenen Persern Heil bringt; für die aber, die uns
bedrohen, soll er ein Mahnmal des Untergangs sein.

<<v12x>>
12x Jede Stadt und jede Provinz, die nicht danach handelt, wird ohne
Erbarmen mit Feuer und Schwert verwüstet. Kein Mensch wird sie mehr
betreten, selbst den Tieren und Vögeln soll sie für immer verhasst sein. [fn:3]

<<v13>>
13 In jeder einzelnen Provinz wurde eine Abschrift des Erlasses als
Gesetz für alle Völker veröffentlicht; die Juden sollten bereit sein,
sich an diesem Tag an ihren Feinden zu rächen.

<<v14>>
14 Die Boten ritten auf Postpferden, die aus den (königlichen) Gestüten
stammten, hinaus, durch königlichen Befehl zu großer Eile gedrängt. Auch
in der Burg Susa wurde das Gesetz veröffentlicht.

<<v15>>
15 Als Mordechai den König verließ, trug er ein königliches Gewand aus
violettem Purpur und weißem Leinen, eine große goldene Krone und einen
Mantel aus kostbarem Leinen und rotem Purpur und die Stadt Susa war voll
Jubel und Freude.

<<v16>>
16 Die Juden waren glücklich, sie jauchzten vor Freude und waren wieder
angesehen.

<<v17>>
17 In jeder Provinz und in jeder Stadt, überall, wo der Erlass des
Königs und sein Befehl bekannt wurde, jauchzten die Juden vor Freude,
sie aßen und tranken und ließen es sich an diesem Tag gut gehen. In
allen Völkern der Erde bekannten sich viele zum Judentum; denn ein
Schrecken vor den Juden hatte sie befallen. [fn:4]\\
\\

* Footnotes

[fn:1] 1-2: Mordechai tritt an Hamans Stelle.

[fn:2] 7-11.12a-x. 13-17 G=8,7-12; 16,1-24; 8,13-17 Vg; 8,13-17 Vg

[fn:3] Die Ausgaben von G übergehen die Buchstaben v und w bei
der Zählung der Verse.

[fn:4] [[file:Ps_105.org::v38][Ps 105,38]]
