#+TITLE: Est 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-25 Sa 21:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Est 5.html

<<verses>>

<<v1>>
* Die Audienz beim König: 5,1-4 5,1a-f. 2a.b. G = 15,4-19 Vg

1 Am dritten Tag legte Ester ihre königlichen Gewänder an und ging in
den inneren Palasthof, der vor dem Haus des Königs lag. Der König saß im
Königshaus auf seinem Königsthron, dem Eingang gegenüber.

<<v2>>
2 Als der König die Königin Ester im Hof stehen sah, fand sie Gnade vor
seinen Augen. Der König streckte ihr das goldene Zepter entgegen, das er
in der Hand hielt. Ester trat näher und berührte die Spitze des Zepters.

<<v5,1G>>
5,1G [Am dritten Tag legte Ester, als sie ihr Gebet beendet hatte, ihr
Bußgewand ab und zog ihre Prunkgewänder an. [fn:1]

<<v1a>>
1a Nachdem sie ihre strahlende Schönheit wiedergewonnen hatte, betete
sie zu dem allsehenden Gott und Retter. Dann nahm sie zwei Dienerinnen
mit; auf die eine stützte sie sich nach der Art der vornehmen Frauen,
die andere ging hinter ihr und trug ihr die Schleppe.

<<v1b>>
1b Sie selbst strahlte in blühender Schönheit, ihr Gesicht war
bezaubernd und heiter, ihr Herz aber war beklommen vor Furcht.

<<v1c>>
1c Sie durchschritt alle Türen und blieb vor dem König stehen. Er saß
auf seinem königlichen Thron, angetan mit seinen Prunkgewändern voll
Gold und Edelsteinen. Der Anblick war Furcht erregend.

<<v1d>>
1d Als er aufblickte und die Königin in wildem Zorn mit feuerrotem
Gesicht ansah, wurde sie bleich, fiel in Ohnmacht und sank auf die
Schulter der Dienerin, die vorausging.

<<v1e>>
1e Da erweichte Gott das Herz des Königs. Besorgt sprang er vom Thron
auf und nahm sie in seine Arme, bis sie wieder zu sich kam. Dann redete
er ihr mit freundlichen Worten zu und sagte:

<<v1f>>
1f Was hast du, Ester? Ich bin dein Bruder, sei unbesorgt! Du sollst
nicht sterben; denn unser Befehl gilt nur für die anderen. Komm her! [fn:2]

<<v2G>>
2G Dann nahm er das goldene Zepter, legte es ihr auf den Nacken, küsste
sie und sagte: Nun rede mit mir!

<<v2a>>
2a Da sagte sie zu ihm: Ich sah dich, Herr, wie einen Engel Gottes und
mein Herz erschrak aus Furcht vor deinem majestätischen Anblick; denn du
bist herrlich, Herr, und dein Gesicht ist voll Wohlwollen.

<<v2b>>
2b Während sie mit ihm redete, fiel sie wieder in Ohnmacht. Der König
war sehr bestürzt und sein ganzes Gefolge suchte ihr Mut zu machen.]

<<v3>>
3 Der König sagte zu ihr: Was willst du, Königin Ester? Was hast du für
einen Wunsch? Auch wenn es die Hälfte meines Reiches wäre, du sollst es
erhalten. [fn:3]

<<v4>>
4 Ester antwortete: Wenn es dem König gefällt, möge er heute mit Haman
zu dem Festmahl kommen, das ich für ihn vorbereitet habe.\\
\\

<<v5>>
* Die Einladung zum Festmahl bei Ester: 5,5-8

5 Der König sagte: Holt in aller Eile Haman her, damit wir Esters Wunsch
erfüllen können. Und der König kam mit Haman zu dem Festmahl, das Ester
vorbereitet hatte.

<<v6>>
6 Als sie beim Wein saßen, sagte der König zu Ester: Was hast du für
eine Bitte? Sie wird dir erfüllt. Was hast du für einen Wunsch? Selbst
wenn es die Hälfte des Reiches wäre, man wird es dir geben.

<<v7>>
7 Ester antwortete: Das ist meine Bitte und mein Wunsch:

<<v8>>
8 Wenn ich beim König Gnade gefunden habe und es ihm gefällt, mir zu
geben, worum ich bitte, und meinen Wunsch zu erfüllen, dann möge der
König auch morgen mit Haman zu dem Festmahl kommen, das ich für sie
veranstalte. Morgen will ich dann die Frage des Königs beantworten. [fn:4]\\
\\

<<v9>>
* Hamans Racheplan gegen Mordechai: 5,9-14

9 Haman ging an diesem Tag fröhlich und gut gelaunt nach Hause. Als er
aber am Tor des Königspalastes Mordechai sah, der sich nicht erhob und
keinerlei Ehrfurcht vor ihm zeigte, geriet er in Zorn über Mordechai.

<<v10>>
10 Doch er ließ sich nichts anmerken. Er ging nach Hause und rief seine
Freunde und seine Frau Seresch zu sich.

<<v11>>
11 Und er erzählte ihnen von seinem gewaltigen Reichtum und von seinen
vielen Söhnen, von all der Macht, die ihm der König verliehen habe, und
wie er ihn hoch über alle anderen Fürsten und königlichen Diener
gestellt habe.

<<v12>>
12 Haman sagte: Auch Königin Ester hat an dem Festmahl, das sie
veranstaltete, nur den König und mich teilnehmen lassen. Und auch morgen
bin ich von ihr zusammen mit dem König eingeladen.

<<v13>>
13 Aber mein Glück ist noch nicht vollkommen, solange ich den Juden
Mordechai am Tor des Palastes sitzen sehe.

<<v14>>
14 Da sagten seine Frau Seresch und alle seine Freunde zu ihm: Man
könnte doch einen Galgen errichten, fünfzig Ellen hoch. Du aber sag
morgen früh dem König, man solle Mordechai daran aufhängen. Dann kannst
du mit dem König frohen Herzens zu dem Mahl gehen. Der Vorschlag gefiel
Haman sehr und er ließ den Galgen aufstellen. [fn:5]\\
\\

* Footnotes

[fn:1] 1-2b: Der Zusatz ist eine in G überlieferte Erweiterung zu [[v1][5,1-2]].

[fn:2] [[file:Est_4.org::v11][4,11]]

[fn:3] [[v6][5,6]]; [[file:Est_7.org::v2][7,2]]; [[file:Est_9.org::v12][9,12]]; [[file:~/RoamNotes/notes/Bibel/nt/Mk_6.org::v23][Mk 6,23]]

[fn:4] auch morgen: eingefügt mit G. - Die Frage des Königs
beantworten, wörtlich: nach dem Wort des Königs handeln.

[fn:5] Das Aufhängen am Galgen dient nicht der Hinrichtung,
sondern der Zurschaustellung der Leiche; deshalb die außergewöhnliche
Höhe des Galgens (vgl. 9,13).
