#+TITLE: Est 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-25 Sa 20:17]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Est 2.html

<<verses>>

<<v1>>
* Der Entschluss des Königs: 2,1-4

1 Als sich nach einiger Zeit der Zorn des Königs gelegt hatte, erinnerte
er sich wieder an Waschti und an das, was sie getan und was man über sie
beschlossen hatte.

<<v2>>
2 Da sagten die Pagen des Königs: Man sollte für den König schöne junge
Mädchen suchen.

<<v3>>
3 Der König soll in jeder Provinz seines Reiches Männer beauftragen,
alle schönen jungen Mädchen in den Frauenpalast auf der Burg Susa zu
bringen und dem königlichen Kämmerer Hegai, dem Aufseher der Frauen, zu
übergeben. Dort sollen sie der nötigen Schönheitspflege unterzogen
werden.

<<v4>>
4 Und das Mädchen, das dem König gefällt, soll anstelle Waschtis Königin
werden. Der König fand den Vorschlag gut und handelte nach ihm.\\
\\

<<v5>>
* Ester am königlichen Hof: 2,5-14

5 In der Burg Susa lebte ein Jude namens Mordechai. Er war der Sohn
Jaïrs, des Sohnes Schimis, des Sohnes des Kisch, aus dem Stamm Benjamin. [fn:1] [fn:2]

<<v6>>
6 Er war mit den Verschleppten aus Jerusalem gekommen, die der
babylonische König Nebukadnezzar zusammen mit König Jojachin deportiert
hatte.

<<v7>>
7 Er war der Vormund von Hadassa, der Tochter seines Onkels, die auch
Ester hieß. Sie hatte keinen Vater und keine Mutter mehr. Das Mädchen
war von schöner Gestalt und großer Anmut. Nach dem Tod ihres Vaters und
ihrer Mutter hatte Mordechai sie als seine Tochter angenommen. [fn:3] [fn:4]

<<v8>>
8 Als der Befehl und Erlass des Königs bekannt wurde, brachte man viele
Mädchen zur Burg Susa und gab sie in die Obhut Hegais. Auch Ester wurde
in den Königspalast geholt und Hegai, dem Aufseher der Frauen,
übergeben.

<<v9>>
9 Das Mädchen fand sein Gefallen und seine Gunst. Er war sehr darauf
bedacht, dass sie die nötige Pflege und die richtige Kost erhielt;
außerdem gab er ihr sieben auserlesene Dienerinnen aus dem Königshaus.
Später ließ er sie mit ihren Dienerinnen in die schönsten Räume des
Frauenpalastes umziehen.

<<v10>>
10 Ester hatte nichts von ihrem Volk und ihrer Abstammung erzählt; denn
Mordechai hatte sie angewiesen, nichts davon zu sagen.

<<v11>>
11 Jeden Tag ging Mordechai zum Hof des Frauenpalastes, um zu erfahren,
wie es Ester ging und was mit ihr geschah.

<<v12>>
12 Der Reihe nach wurden alle Mädchen zu König Artaxerxes geholt. Zuvor
waren sie, wie es für die Frauen Vorschrift war, zwölf Monate lang
gepflegt worden; denn so lange dauerte ihre Schönheitspflege: sechs
Monate Myrrhenöl und sechs Monate Balsam und andere Schönheitsmittel der
Frauen.

<<v13>>
13 Dann gingen die Mädchen zum König und alles, was sie sich aus dem
Haus der Frauen wünschten, gab man ihnen in den Königspalast mit.

<<v14>>
14 Am Abend gingen sie hinein und am Morgen kamen sie zurück und wurden
in den zweiten Frauenpalast gebracht und dem königlichen Kämmerer
Schaaschgas anvertraut, dem Aufseher der Nebenfrauen. Sie durften nicht
mehr zum König gehen, außer wenn der König Gefallen an ihnen gefunden
hatte und sie ausdrücklich rufen ließ. [fn:5]\\
\\

<<v15>>
* Esters Erhebung zur Königin: 2,15-20

15 Eines Tages war Ester, die Tochter Abihajils, des Onkels Mordechais,
der sie als seine Tochter angenommen hatte, an der Reihe, zum König zu
gehen. Sie wollte nichts mitnehmen, außer was der königliche Kämmerer
Hegai, der Aufseher der Frauen, ihr nahelegte. Ester aber gefiel allen,
die sie sahen.

<<v16>>
16 Es war im zehnten Monat, dem Monat Tebet, im siebten Jahr der
Regierung des Königs, als Ester zu Artaxerxes in den königlichen Palast
geholt wurde.

<<v17>>
17 Und der König liebte Ester mehr als alle Frauen zuvor und sie gewann
seine Gunst und Zuneigung mehr als alle anderen Mädchen. Er setzte ihr
das königliche Diadem auf und machte sie anstelle Waschtis zur Königin.

<<v18>>
18 Der König veranstaltete zu Ehren Esters ein großes Festmahl für alle
seine Fürsten und Diener. Den Provinzen gewährte er einen Steuererlass
und mit königlicher Freigebigkeit teilte er Geschenke aus.

<<v19>>
19 Damals, als man die Mädchen [zum zweiten Mal] zusammenholte, hatte
Mordechai einen Posten am Tor des königlichen Palastes.

<<v20>>
20 Ester aber erzählte nichts von ihrer Abstammung und ihrem Volk, wie
Mordechai ihr aufgetragen hatte. Ester hielt sich an die Worte
Mordechais, wie früher, als sie noch seine Pflegetochter war.\\
\\

<<v21>>
* Die Aufdeckung einer Verschwörung: 2,21-23

21 In jenen Tagen, als Mordechai einen Posten am Tor des königlichen
Palastes hatte, planten Bigtan und Teresch, zwei unzufriedene königliche
Kämmerer, die zu den Türhütern gehörten, einen Anschlag auf König
Artaxerxes. [fn:6]

<<v22>>
22 Mordechai erfuhr davon und berichtete es der Königin Ester. Ester
sagte es im Auftrag Mordechais dem König weiter.

<<v23>>
23 Die Sache wurde untersucht und aufgedeckt. Man hängte die beiden auf
und hielt das Ereignis in der Chronik fest, die für den König geführt
wurde.\\
\\

* Footnotes

[fn:1] (5-6) [[file:Est_1.org::v1][1,1]] [[file:Est_1.org::v1a][a]]-[[file:Est_1.org::v1c][c]]

[fn:2] 5f: Mordechai (= dem Gott Marduk gehörig) ist ein
babylonischer Name. Nicht er selber, sondern wohl Kisch ist mit Jojachin
in die Verbannung geführt worden (597 v. Chr.).

[fn:3] [[file:Est_8.org::v1][8,1]]

[fn:4] Hadassa (= Myrthe) ist der hebräische, Ester (= Stern)
ist der babylonische Name für die Nichte und Adoptivtochter Mordechais.

[fn:5] [[file:Est_4.org::v11][4,11]]

[fn:6] [[file:Est_6.org::v1][6,1f]]; (21-23) [[file:Est_1.org::v1m][1,1m]]-[[file:Est_1.org::v1p][p]]
