#+TITLE: Est 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-25 Sa 21:31]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Est 7.html

<<verses>>

<<v1>>
* Hamans Ende: 7,1-10

1 Der König und Haman kamen zu dem Mahl, das die Königin Ester gab,

<<v2>>
2 und der König sagte auch am zweiten Tag zu Ester, als sie beim Wein
saßen: Was hast du für eine Bitte, Königin Ester? Sie wird dir erfüllt.
Was hast du für einen Wunsch? Selbst wenn es die Hälfte des Reiches
wäre - man wird es dir geben. [fn:1]

<<v3>>
3 Die Königin Ester antwortete: Wenn ich beim König Wohlwollen gefunden
habe und wenn es ihm gefällt, dann möge mir und meinem Volk das Leben
geschenkt werden. Das ist meine Bitte und mein Wunsch.

<<v4>>
4 Man hat mich und mein Volk verkauft, um uns zu erschlagen, zu ermorden
und auszurotten. Wenn man uns als Sklaven und Sklavinnen verkaufen
würde, hätte ich nichts gesagt; denn dann gäbe es keinen Feind, der es
wert wäre, dass man seinetwegen den König belästigt.

<<v5>>
5 Da sagte der König Artaxerxes zu Königin Ester: Wer ist der Mann? Wo
ist der Mensch, der es wagt, so etwas zu tun?

<<v6>>
6 Ester antwortete: Dieser gefährliche Feind ist der verbrecherische
Haman hier. Da erschrak Haman vor dem König und der Königin.

<<v7>>
7 Der König aber stand auf, verließ voll Zorn das Trinkgelage und ging
in den Garten des Palastes. Haman trat zu Ester und flehte sie um sein
Leben an; denn er sah, dass sein Untergang beim König besiegelt war.

<<v8>>
8 Als der König aus dem Garten wieder in den Raum zurückkam, in dem das
Trinkgelage stattfand, hatte sich Haman über das Polster geworfen, auf
dem Ester lag. Der König sagte: Tut man jetzt sogar hier in meiner
Gegenwart der Königin Gewalt an? Kaum hatte der König das gesagt, da
verhüllte man schon das Gesicht Hamans. [fn:2]

<<v9>>
9 Harbona, einer der Hofbeamten, sagte zum König: Vor dem Haus Hamans
steht schon ein fünfzig Ellen hoher Galgen; ihn hat Haman für Mordechai
aufgestellt, der dem König durch seine Anzeige einen guten Dienst
erwiesen hat. Der König befahl: Hängt ihn daran auf!

<<v10>>
10 Da hängten sie Haman an den Galgen, den er für Mordechai errichtet
hatte, und der Zorn des Königs legte sich.\\
\\

* Footnotes

[fn:1] [[file:Est_5.org::v6][5,6]]

[fn:2] Das Verhüllen des Gesichts bedeutet, dass Hamans
Schicksal schon besiegelt ist.
