#+TITLE: Est 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-25 Sa 20:05]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Est 1.html

* Est 1

Die Jüdin Ester und ihr Onkel Mordechai auf der einen, König Artaxerxes
und Haman auf der anderen Seite sind die Hauptpersonen des Buches, in
dem es um die Abwendung einer drohenden Judenverfolgung im Perserreich
geht. Das Buch hat einen geschichtlichen Hintergrund, weil es schon in
alter Zeit Judenverfolgungen gab. Es erzählt, wie Ester, die
Pflegetochter Mordechais, anstelle der verstoßenen Waschti von
Artaxerxes zur Königin erhoben wird. Mordechai hat durch die Aufdeckung
einer Verschwörung dem König das Leben gerettet (Kap. 1 und 2). Haman,
der zweite Mann im Reich, hasst aus Missgunst gegen Mordechai die Juden
und erwirkt einen königlichen Erlass zu ihrer Ausrottung; sie wird durch
das Los (pûr) auf den 13. Adar (FebruarMärz) festgesetzt (Kap. 3). Auf
Veranlassung Mordechais geht Ester unter Lebensgefahr zum König, erlangt
sein Wohlwollen und erreicht den Sturz Hamans (Kap. 4 - 7). Mordechai
tritt an Hamans Stelle, Ester erhält Hamans Besitz und erwirkt gegen den
ersten Erlass des Königs einen zweiten, der den Juden erlaubt, sich
ihrer Feinde zu erwehren (Kap. 8). Das geschieht am 13. Adar im
Perserreich und am 14. Adar in der Hauptstadt Susa, worauf der 14. Adar
für die Juden in den Provinzen und der 15. für die in Susa lebenden
Juden zum Festtag erklärt wird (Purimfest, abgeleitet von pûr);
Mordechai und Ester rufen in Briefen zur Feier dieses Festes auf (Kap.
9). Ein Bericht über die Taten des Königs und über die Amtsführung
Mordechais schließen das Buch ab (Kap. 10).\\
\\
Der Verfasser ist über die Zustände am persischen Hof und in Susa gut
informiert, verfährt aber recht frei und ungenau mit geschichtlichen
Tatsachen, was sich besonders daran zeigt, dass er den Perserkönig
Artaxerxes unmittelbar auf den Babylonier Nebukadnezzar folgen lässt
(2,6). Die novellenartige Erzählung ist mit märchenhaften Zügen
ausgeschmückt. Das Buch, dessen Abfassung vermutlich nach der
Perserzeit, etwa um 300 v. Chr., anzusetzen ist, erklärt die Entstehung
des jüdischen Purimfestes.\\
\\
Das Buch Ester steht im dritten Teil der hebräischen Bibel unter den
»Fünf Festrollen« (vgl. die Einleitung zu Rut). Seine Aufnahme in die
Bibel fand es erst nach längeren Diskussionen unter den
Schriftgelehrten. Das hängt damit zusammen, dass das Buch recht profan
anmutet, wie auch das Purimfest ein weltliches Fest ist. Gott wird im
hebräischen Esterbuch nicht erwähnt. Dem suchte die griechische Fassung
abzuhelfen, indem sie außer anderen Erweiterungen die Gebete Mordechais
und Esters (nach 4,17), den Traum Mordechais (vor 1,1) und seine Deutung
(nach 10,3) einfügte. Hier wird ausdrücklich von Gott gesprochen. Diese
Erweiterungen, die auch den judenfeindlichen Erlass (nach 3,13), eine
Schilderung der Audienz Esters (in 5,1 und 2) und den Gegenerlass des
Königs (nach 8,12) bringen, stehen in der griechischen Bibel an der
jeweils passenden Stelle. In der lateinischen Bibel sind sie gesammelt
als Anhang an den Schluss gestellt. Stil, Sprachcharakter und Denkweise
zeigen, dass die Zusätze von Anfang an griechisch geschrieben waren.\\
\\
Das spannend geschriebene Buch bringt, auch wenn es in der hebräischen
Fassung Gott nicht nennt, den Glauben an Gott als Retter und Befreier
zum Ausdruck; dazu genügt dem gläubigen Leser bereits eine Andeutung
(4,14; 6,13). Das Beispiel Esters und Mordechais zeigt auch, was der
Einzelne im Vertrauen auf Gott zum Besten seines Volkes zu tun vermag.\\
\\
Die folgende Übersetzung hält sich in der Textanordnung an die
griechische Bibel und zählt in den deuterokanonischen Zusätzen die Verse
nach Buchstaben.\\
\\

<<verses>>

<<v1a>>
* Mordechai und die Verschwörung gegen König Artaxerxes: 1,1a-r

* Der Traum Mordechais: 1,1a-l G = 11,2-12 Vg

1a Im zweiten Jahr der Regierung des Großkönigs Artaxerxes, am ersten
Tag des Monats Nisan, hatte Mordechai, der Sohn Jaïrs, des Sohnes
Schimis, des Sohnes des Kisch, aus dem Stamm Benjamin, einen Traum. [fn:1]

<<v1b>>
1b Der Jude Mordechai wohnte in der Stadt Susa; er war ein angesehener
Mann, der am Hof des Königs diente. [fn:2]

<<v1c>>
1c Er gehörte zu denen, die der babylonische König Nebukadnezzar mit
Jojachin, dem König von Juda, aus Jerusalem verschleppt hatte. [fn:3]

<<v1d>>
1d Er hatte folgenden Traum: Es gab Geschrei und Lärm, Donner und
Erdbeben und ein Tumult entstand auf der Erde. [fn:4] [fn:5]

<<v1e>>
1e Plötzlich kamen zwei große Drachen, beide bereit zu kämpfen. Sie
brüllten laut

<<v1f>>
1f und durch ihr Brüllen wurden alle Völker zum Kampf aufgereizt, sodass
sie gegen das Volk der Gerechten Krieg führten.

<<v1g>>
1g Es war ein Tag des Dunkels und der Finsternis; Bedrängnis und Not,
Unheil und großer Tumult waren auf der Erde.

<<v1h>>
1h Das ganze Volk der Gerechten geriet in Bestürzung. Sie fürchteten
Unheil und rechneten mit ihrem Untergang. Da schrien sie zu Gott.

<<v1i>>
1i Auf ihr Rufen hin wurde aus einer kleinen Quelle ein großer Strom mit
viel Wasser.

<<v1k>>
1k Licht und Sonne schienen wieder; die Niedrigen wurden erhöht und sie
vernichteten die Angesehenen. [fn:6]

<<v1l>>
1l Als Mordechai diesen Traum gehabt hatte, erwachte er. Den ganzen Tag
überlegte er, was Gott wohl beschlossen habe, und versuchte, auf jede
nur mögliche Weise den Traum zu verstehen.\\
\\

<<v1m>>
* Die Aufdeckung der Verschwörung: 1,1m-r G = 12,1-6 Vg

1m Mordechai schlief im Palast in der Nähe der zwei Hofbeamten Gabata
und Teresch, die den Palast bewachten. [fn:7] [fn:8]

<<v1n>>
1n Dabei hörte er, was sie miteinander überlegten; er versuchte, über
ihre Pläne Genaueres zu erfahren, und entdeckte, dass sie einen Anschlag
gegen König Artaxerxes vorbereiteten. Er zeigte sie beim König an

<<v1o>>
1o und der König verhörte die beiden Beamten. Sie gestanden und wurden
hingerichtet.

<<v1p>>
1p Zur Erinnerung ließ der König diese Begebenheit aufzeichnen; auch
Mordechai machte Aufzeichnungen darüber. [fn:9]

<<v1q>>
1q Und der König beauftragte Mordechai, im Palast zu dienen, und
belohnte ihn für seine Tat mit reichen Geschenken. [fn:10]

<<v1r>>
1r Aber der Bugäer Haman, der Sohn Hammedatas, ein angesehener Mann beim
König, suchte wegen der beiden Hofbeamten des Königs Unheil über
Mordechai und sein Volk zu bringen. [fn:11] [fn:12]\\
\\

<<v1>>
* Die Erhebung Esters zur Königin: 1,1 - 2,23

* Das Mahl im Königspalast: 1,1-9

1 Es war zur Zeit des Artaxerxes, jenes Artaxerxes, der von Indien bis
Kusch über hundertsiebenundzwanzig Provinzen herrschte.

<<v2>>
2 Drei Jahre, nachdem König Artaxerxes in der Burg Susa den Thron seines
Reiches bestiegen hatte,

<<v3>>
3 gab er ein Festmahl für alle seine Fürsten und Beamten. Die Obersten
des Heeres von Persien und Medien, die Vornehmen und die Statthalter der
Provinzen waren erschienen [fn:13]

<<v4>>
4 und er stellte viele Tage lang seinen ganzen Reichtum und seine
königliche Pracht, seine Herrlichkeit und seinen ungeheueren Prunk zur
Schau, hundertachtzig Tage lang.

<<v5>>
5 Am Ende dieser Tage gab der König allen, die in der Burg Susa waren,
vom Größten bis zum Geringsten, sieben Tage lang im Hofgarten des
Palastes ein Festmahl.

<<v6>>
6 Weißes Leinen, violetter Purpurstoff und andere feine Gewebe waren mit
weißen und roten Schnüren in silbernen Ringen an Alabastersäulen
aufgehängt. Auf dem Mosaikboden aus Alabaster, weißem und buntem Marmor
und Perlmuttsteinen standen goldene und silberne Ruhelager.

<<v7>>
7 Man trank aus goldenen Gefäßen, von denen keines den andern gleich
war. Großzügig ließ der König seinen Wein ausschenken.

<<v8>>
8 Bei dem Gelage sollte keinerlei Zwang herrschen. Denn der König hatte
seinen Palastbeamten befohlen: Jeder kann tun, was ihm beliebt.

<<v9>>
9 Auch Königin Waschti gab ein Festmahl für die Frauen, die im Palast
des Königs Artaxerxes lebten.\\
\\

<<v10>>
* Die Verstoßung der Königin Waschti: 1,10-22

10 Als König Artaxerxes am siebten Tag vom Wein angeheitert war, befahl
er Mehuman, Biseta, Harbona, Bigta, Abagta, Setar und Karkas, den sieben
Hofbeamten, die ihn persönlich bedienten,

<<v11>>
11 die Königin Waschti im königlichen Diadem vor ihn zu bringen, damit
das Volk und die Fürsten ihre Schönheit bewunderten; denn sie war sehr
schön.

<<v12>>
12 Aber die Königin Waschti weigerte sich, dem Befehl des Königs, den
die Hofbeamten überbracht hatten, zu folgen und zu kommen. Da wurde der
König erbost und es packte ihn großer Zorn.

<<v13>>
13 Er besprach sich mit den Weisen, die sich in der Geschichte
auskennen; denn er pflegte seine Angelegenheiten vor den Kreis der
Gesetzes- und Rechtskundigen zu bringen, [fn:14]

<<v14>>
14 die zu ihm Zutritt hatten, nämlich Karschena, Schetar, Admata,
Tarschisch, Meres, Marsena, Memuchan, die sieben Fürsten Persiens und
Mediens. Sie hatten freien Zugang zum König und nahmen den ersten Rang
im Königreich ein.

<<v15>>
15 Er fragte: Was soll man nach dem Gesetz mit der Königin Waschti tun,
nachdem sie dem Befehl des Königs Artaxerxes, den ihr die Hofbeamten
überbracht haben, nicht gefolgt ist?

<<v16>>
16 Da sagte Memuchan zum König und zu den Fürsten: Nicht nur gegen den
König, sondern auch gegen alle Fürsten und alle Völker, die in all den
Provinzen des Königs Artaxerxes leben, hat sich Königin Waschti
verfehlt.

<<v17>>
17 Denn das Verhalten der Königin wird allen Frauen bekannt werden, und
sie werden die Achtung vor ihren Ehemännern verlieren und sagen: König
Artaxerxes befahl der Königin Waschti, vor ihm zu erscheinen; aber sie
kam nicht.

<<v18>>
18 Von heute an werden alle Fürstinnen Persiens und Mediens, die vom
Verhalten der Königin hören, dies allen Fürsten des Königs vorhalten und
es gibt viel Ärger und Verdruss.

<<v19>>
19 Wenn es dem König recht ist, möge ein unwiderruflicher königlicher
Erlass ergehen, der in den Gesetzen der Perser und Meder aufgezeichnet
wird: Waschti darf dem König Artaxerxes nicht mehr unter die Augen
treten. Der König aber verleihe den Rang der Königin einer anderen, die
würdiger ist als sie.

<<v20>>
20 Wenn die Anordnung, die der König erlässt, in seinem ganzen großen
Reich bekannt wird, dann werden alle Frauen ihren Ehemännern, den
vornehmsten wie den geringsten, die gebührende Achtung erweisen.

<<v21>>
21 Der Vorschlag gefiel dem König und den Fürsten und der König handelte
nach Memuchans Worten.

<<v22>>
22 Er sandte Schreiben an alle königlichen Provinzen, an jede Provinz in
ihrer eigenen Schrift und an jedes Volk in seiner Sprache, damit alle
Männer Herr in ihrem Haus blieben [redend in der Sprache seines Volkes]. [fn:15] [fn:16]\\
\\

* Footnotes

[fn:1] G liest in allen Teilen des Buches den Namen des Königs
als Artaxerxes; H liest Ahaschwerosch, dessen griechische Form sonst
Xerxes lautet. Gemeint ist Xerxes I. (486-465 v. Chr.).

[fn:2] Susa ist neben Babylon und Ekbatana eine der Residenzen
des Perserreichs.

[fn:3] [[file:2.Kön_24.org::v8][2 Kön 24,8]].[[file:2.Kön_24.org::v15][15]]

[fn:4] [[file:Est_10.org::v3a][10,3a-k]]

[fn:5] 1d-l: Der Traum wird in [[file:Est_10.org::v3b][10,3b]]-[[file:Est_10.org::v3f][f]] gedeutet.

[fn:6] [[file:Est_8.org::v16][8,16]]

[fn:7] (1m-p) [[file:Est_2.org::v21][2,21]]-[[file:Est_2.org::v23][23]]; [[file:Est_6.org::v2][6,2f]]

[fn:8] 1m-p: Vgl. [[file:Est_6.org::v21][2,21-23]].

[fn:9] [[file:Est_6.org::v1][6,1]]; [[file:Est_10.org::v2][10,2]]

[fn:10] [[file:Est_6.org::v3][6,3]]

[fn:11] [[file:Est_3.org::v1][3,1f]].[[file:Est_3.org::v5][5f]]

[fn:12] Bugäer: sonst wird Haman als Agagiter bezeichnet.

[fn:13] Die Obersten des Heeres: Text korr.; H: das Heer.

[fn:14] die sich in der Geschichte auskennen, wörtlich: die
die Zeiten kennen. Andere Deutung: die wissen, was jeweils in einer
bestimmten Zeit zu tun ist (vgl. [[file:1.Chr_12.org::v33][1 Chr 12,33]]).

[fn:15] [[file:Est_3.org::v12][3,12]]; [[file:Est_8.org::v9][8,9]]

[fn:16] Dieser Zusatz fehlt in G.
