#+TITLE: Est 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-25 Sa 21:35]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Est 9.html

<<verses>>

<<v1>>
* Der Siegestag der Juden: 9,1-19

1 Am dreizehnten Tag im zwölften Monat, dem Monat Adar, sollte der
Erlass des Königs und sein Befehl ausgeführt werden. Es war der Tag, an
dem die Gegner der Juden gehofft hatten, sie zu überwältigen. Doch nun
überwältigten umgekehrt die Juden ihre Feinde.

<<v2>>
2 In allen Provinzen des Königs Artaxerxes taten sich die Juden in den
Städten zusammen und überfielen die, die den Untergang der Juden geplant
hatten. Niemand konnte ihnen standhalten; denn alle Völker hatte
Schrecken vor ihnen befallen;

<<v3>>
3 auch alle Fürsten der Provinzen, die Satrapen, Statthalter und
königlichen Beamten, waren aufseiten der Juden; denn Schrecken vor
Mordechai hatte sie befallen.

<<v4>>
4 Mordechai war nämlich im Königspalast hoch angesehen und es war in
allen Provinzen bekannt geworden, dass er immer einflussreicher wurde.

<<v5>>
5 So metzelten die Juden alle ihre Feinde mit dem Schwert nieder; es gab
ein großes Blutbad. Sie machten mit ihren Gegnern, was sie wollten.

<<v6>>
6 In der Burg Susa brachten die Juden fünfhundert Männer um

<<v7>>
7 und auch Parschandata, Dalfon, Aspata,

<<v8>>
8 Porata, Adalja, Aridata,

<<v9>>
9 Parmaschta, Arisai, Aridai und Wajesata,

<<v10>>
10 die zehn Söhne des Judenfeindes Haman, des Sohnes Hammedatas, töteten
sie, aber sie vergriffen sich nicht an ihrem Besitz.

<<v11>>
11 Als man an jenem Tag dem König meldete, wie viele Menschen in der
Burg Susa erschlagen worden waren,

<<v12>>
12 sagte er zur Königin Ester: In der Burg Susa haben die Juden ein
Blutbad angerichtet; man hat fünfhundert Männer, auch die zehn Söhne
Hamans, umgebracht. Was haben sie dann wohl in den übrigen königlichen
Provinzen getan? Hast du einen Wunsch? Er wird dir erfüllt werden. Hast
du eine Bitte? Sie soll erfüllt werden.

<<v13>>
13 Ester antwortete: Wenn es dem König gefällt, soll den Juden in Susa
erlaubt werden, auch morgen nach dem Gesetz von heute zu handeln.
Außerdem soll man die zehn Söhne Hamans an den Galgen hängen.

<<v14>>
14 Der König befahl, es solle so geschehen. Man gab also in Susa noch
einen Erlass heraus und hängte die zehn Söhne Hamans auf.

<<v15>>
15 Auch am vierzehnten Tag des Monats Adar taten sich die Juden in Susa
zusammen und töteten dort dreihundert Männer; aber an ihrem Besitz
vergriffen sie sich nicht.

<<v16>>
16 Die übrigen Juden in den königlichen Provinzen versammelten sich, um
für ihr Leben einzutreten; sie verschafften sich Ruhe vor ihren Feinden
und töteten fünfundsiebzigtausend ihrer Gegner; aber an ihrem Besitz
vergriffen sie sich nicht.

<<v17>>
17 Das geschah am dreizehnten Tag des Monats Adar, am vierzehnten Tag
des Monats jedoch war Ruhe. Sie feierten ihn als Festtag mit Essen und
Trinken.

<<v18>>
18 Die Juden in Susa aber versammelten sich am Dreizehnten und
Vierzehnten des Monats; bei ihnen war am Fünfzehnten wieder Ruhe, und
sie feierten ihn als Festtag mit Essen und Trinken.

<<v19>>
19 Deswegen begehen die Juden in den unbefestigten Orten auf dem Land
den vierzehnten Tag des Monats Adar als Festtag, den sie mit Essen und
Trinken feiern und an dem sie sich gegenseitig beschenken.\\
\\

<<v20>>
* Die Einführung des Purimfestes: 9,20-32

20 Mordechai schrieb alles auf, was geschehen war. Er schickte Schreiben
an alle Juden in allen Provinzen des Königs Artaxerxes nah und fern

<<v21>>
21 und machte ihnen zur Pflicht, den vierzehnten und den fünfzehnten Tag
des Monats Adar in jedem Jahr als Festtag zu begehen.

<<v22>>
22 Das sind die Tage, an denen die Juden wieder Ruhe hatten vor ihren
Feinden; es ist der Monat, in dem sich ihr Kummer in Freude verwandelte
und ihre Trauer in Glück. Sie sollten sie als Festtage mit Essen und
Trinken begehen und sich gegenseitig beschenken und auch den Armen
sollten sie Geschenke geben.

<<v23>>
23 So wurde bei den Juden das, was sie damals zum ersten Mal taten und
was Mordechai ihnen vorschrieb, zu einem festen Brauch.

<<v24>>
24 Denn der Agagiter Haman, der Sohn Hammedatas, der Feind aller Juden,
hatten den Plan gefasst, die Juden auszurotten, und hatte das Pur, das
heißt das Los geworfen, um sie in Schrecken zu versetzen und
auszurotten.

<<v25>>
25 Als das dem König bekannt wurde, ordnete er in einem Schreiben an:
Sein böser Plan gegen die Juden solle auf ihn selbst zurückfallen; man
hänge ihn und seine Söhne an den Galgen.

<<v26>>
26 Darum nennt man diese Tage das Purimfest, nach dem Wort Pur. Wegen
all dem, was in diesem Schreiben stand und was sie selbst gesehen und
erlebt hatten,

<<v27>>
27 machten es sich die Juden zur Pflicht und erklärten es zur
unverbrüchlichen Satzung für sich, für ihre Nachkommen und für alle, die
sich ihnen anschließen würden, diese beiden Tage alljährlich, wie
vorgeschrieben, zur festgesetzten Zeit zu begehen.

<<v28>>
28 Diese Tage sollten in Erinnerung bleiben und in jeder Generation, in
jeder Familie, in jeder Provinz und in jeder Stadt begangen werden. Die
Juden sollten nie aufhören, das Purimfest zu feiern, diese Tage sollten
bei ihren Nachkommen nie vergessen werden.

<<v29>>
29 Um den Purim-Erlass mit allem Nachdruck zu bestätigen, verfassten die
Königin Ester, die Tochter Abihajils, und der Jude Mordechai ein zweites
Schreiben.

<<v30>>
30 Sie schickten es mit Glück- und Segenswünschen an alle Juden in den
hundertsiebenundzwanzig Provinzen des Reiches des Artaxerxes,

<<v31>>
31 um das Datum der Purimtage festzulegen, wie es der Jude Mordechai und
Königin Ester angeordnet und wie sie es selbst sich und ihren Nachkommen
zur Pflicht gemacht hatten. Das Schreiben enthielt die Vorschriften für
das Fasten und die Wehklage.

<<v32>>
32 Esters Worte bestätigten die Anordnungen für das Purimfest, und alles
wurde in einer Urkunde aufgezeichnet.\\
\\
