#+TITLE: Ex 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 22:30]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ex 15.html

<<verses>>

<<v1>>
* Das Lied des Mose: 15,1-21

1 Damals sang Mose mit den Israeliten dem Herrn dieses Lied; sie sagten:
Ich singe dem Herrn ein Lied, /\\
 denn er ist hoch und erhaben. /\\
 Rosse und Wagen warf er ins Meer.\\
\\

<<v2>>
2 Meine Stärke und mein Lied ist der Herr, /\\
 er ist für mich zum Retter geworden. /\\
 Er ist mein Gott, ihn will ich preisen; /\\
 den Gott meines Vaters will ich rühmen. [fn:1]\\
\\

<<v3>>
3 Der Herr ist ein Krieger, /\\
 Jahwe ist sein Name.\\
\\

<<v4>>
4 Pharaos Wagen und seine Streitmacht /\\
 warf er ins Meer. /\\
 Seine besten Kämpfer versanken im Schilfmeer.\\
\\

<<v5>>
5 Fluten deckten sie zu, /\\
 sie sanken in die Tiefe wie Steine.\\
\\

<<v6>>
6 Deine Rechte, Herr, ist herrlich an Stärke; /\\
 deine Rechte, Herr, zerschmettert den Feind.\\
\\

<<v7>>
7 In deiner erhabenen Größe /\\
 wirfst du die Gegner zu Boden. /\\
 Du sendest deinen Zorn; /\\
 er frisst sie wie Stoppeln.\\
\\

<<v8>>
8 Du schnaubtest vor Zorn, /\\
 da türmte sich Wasser, /\\
 da standen Wogen als Wall, /\\
 Fluten erstarrten im Herzen des Meeres.\\
\\

<<v9>>
9 Da sagte der Feind: Ich jage nach, hole ein. /\\
 Ich teile die Beute, ich stille die Gier. /\\
 Ich zücke mein Schwert, meine Hand jagt sie davon.\\
\\

<<v10>>
10 Da schnaubtest du Sturm. Das Meer deckte sie zu. /\\
 Sie sanken wie Blei ins tosende Wasser.\\
\\

<<v11>>
11 Wer ist wie du unter den Göttern, o Herr? /\\
 Wer ist wie du gewaltig und heilig, /\\
 gepriesen als furchtbar, Wunder vollbringend?\\
\\

<<v12>>
12 Du strecktest deine Rechte aus, /\\
 da verschlang sie die Erde.\\
\\

<<v13>>
13 Du lenktest in deiner Güte /\\
 das Volk, das du erlöst hast, /\\
 du führtest sie machtvoll /\\
 zu deiner heiligen Wohnung.\\
\\

<<v14>>
14 Als die Völker das hörten, erzitterten sie, /\\
 die Philister packte das Schütteln.\\
\\

<<v15>>
15 Damals erschraken die Häuptlinge Edoms, /\\
 die Mächtigen von Moab packte das Zittern, /\\
 Kanaans Bewohner, sie alle verzagten.\\
\\

<<v16>>
16 Schrecken und Furcht überfiel sie, /\\
 sie erstarrten zu Stein /\\
 vor der Macht deines Arms, /\\
 bis hindurchzog, o Herr, dein Volk, /\\
 bis hindurchzog das Volk, das du erschufst.\\
\\

<<v17>>
17 Du brachtest sie hin /\\
 und pflanztest sie ein /\\
 auf dem Berg deines Erbes. /\\
 Einen Ort, wo du thronst, Herr, /\\
 hast du gemacht; /\\
 ein Heiligtum, Herr, haben deine Hände gegründet. [fn:2]\\
\\

<<v18>>
18 Der Herr ist König für immer und ewig.

<<v19>>
19 Denn als die Rosse des Pharao mit Wagen und Reitern ins Meer zogen,
ließ der Herr das Wasser des Meeres auf sie zurückfluten, nachdem die
Israeliten auf trockenem Boden mitten durchs Meer gezogen waren.

<<v20>>
20 Die Prophetin Mirjam, die Schwester Aarons, nahm die Pauke in die
Hand und alle Frauen zogen mit Paukenschlag und Tanz hinter ihr her.\\
\\

<<v21>>
21 Mirjam sang ihnen vor: Singt dem Herrn ein Lied, /\\
 denn er ist hoch und erhaben! /\\
 Rosse und Wagen warf er ins Meer.\\
\\

<<v22>>
* Auf dem Weg zum Sinai: 15,22 - 17,16

22 Mose ließ Israel vom Schilfmeer aufbrechen und sie zogen zur Wüste
Schur weiter. Drei Tage waren sie in der Wüste unterwegs und fanden kein
Wasser.

<<v23>>
23 Als sie nach Mara kamen, konnten sie das Wasser von Mara nicht
trinken, weil es bitter war. Deshalb nannte man es Mara (Bitterbrunn).

<<v24>>
24 Da murrte das Volk gegen Mose und sagte: Was sollen wir trinken?

<<v25>>
25 Er schrie zum Herrn und der Herr zeigte ihm ein Stück Holz. Als er es
ins Wasser warf, wurde das Wasser süß. Dort gab Gott dem Volk Gesetz und
Rechtsentscheidungen und dort stellte er es auf die Probe.

<<v26>>
26 Er sagte: Wenn du auf die Stimme des Herrn, deines Gottes, hörst und
tust, was in seinen Augen gut ist, wenn du seinen Geboten gehorchst und
auf alle seine Gesetze achtest, werde ich dir keine der Krankheiten
schicken, die ich den Ägyptern geschickt habe. Denn ich bin der Herr,
dein Arzt.

<<v27>>
27 Dann kamen sie nach Elim. Dort gab es zwölf Quellen und siebzig
Palmen; dort am Wasser schlugen sie ihr Lager auf.


* Footnotes

[fn:1] Ps 118,14; Jes 12,2

[fn:2] Der "Berg deines Erbes" ist wahrscheinlich der Zion in
Jerusalem. Demnach dürfte das Lied erst im Tempelgottesdienst von
Jerusalem seine heutige Gestalt erhalten haben.
