#+TITLE: Ex 19 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 22:39]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ex 19.html

<<verses>>

<<v1>>
* Am Sinai: 19,1 - 40,38

* Das Bundesangebot Gottes: 19,1-25

1 Im dritten Monat nach dem Auszug der Israeliten aus Ägypten - am
heutigen Tag - kamen sie in der Wüste Sinai an. [fn:1]

<<v2>>
2 Sie waren von Refidim aufgebrochen und kamen in die Wüste Sinai. Sie
schlugen in der Wüste das Lager auf. Dort lagerte Israel gegenüber dem
Berg.

<<v3>>
3 Mose stieg zu Gott hinauf. Da rief ihm der Herr vom Berg her zu: Das
sollst du dem Haus Jakob sagen und den Israeliten verkünden:

<<v4>>
4 Ihr habt gesehen, was ich den Ägyptern angetan habe, wie ich euch auf
Adlerflügeln getragen und hierher zu mir gebracht habe.

<<v5>>
5 Jetzt aber, wenn ihr auf meine Stimme hört und meinen Bund haltet,
werdet ihr unter allen Völkern mein besonderes Eigentum sein. Mir gehört
die ganze Erde,

<<v6>>
6 ihr aber sollt mir als ein Reich von Priestern und als ein heiliges
Volk gehören. Das sind die Worte, die du den Israeliten mitteilen
sollst. [fn:2]

<<v7>>
7 Mose ging und rief die Ältesten des Volkes zusammen. Er legte ihnen
alles vor, was der Herr ihm aufgetragen hatte.

<<v8>>
8 Das ganze Volk antwortete einstimmig und erklärte: Alles, was der Herr
gesagt hat, wollen wir tun. Mose überbrachte dem Herrn die Antwort des
Volkes.

<<v9>>
9 Der Herr sprach zu Mose: Ich werde zu dir in einer dichten Wolke
kommen; das Volk soll es hören, wenn ich mit dir rede, damit sie auch an
dich immer glauben. Da berichtete Mose dem Herrn, was das Volk gesagt
hatte.

<<v10>>
10 Der Herr sprach zu Mose: Geh zum Volk! Ordne an, dass sie sich heute
und morgen heilig halten und ihre Kleider waschen.

<<v11>>
11 Sie sollen sich für den dritten Tag bereithalten. Am dritten Tag
nämlich wird der Herr vor den Augen des ganzen Volkes auf den Berg Sinai
herabsteigen.

<<v12>>
12 Zieh um das Volk eine Grenze und sag: Hütet euch, auf den Berg zu
steigen oder auch nur seinen Fuß zu berühren. Jeder, der den Berg
berührt, wird mit dem Tod bestraft.

<<v13>>
13 Keine Hand soll den Berg berühren. Wer es aber tut, soll gesteinigt
oder mit Pfeilen erschossen werden; ob Tier oder Mensch, niemand darf am
Leben bleiben. Erst wenn das Horn ertönt, dürfen sie auf den Berg
steigen.

<<v14>>
14 Mose stieg vom Berg zum Volk hinunter und ordnete an, das Volk solle
sich heilig halten und seine Kleider waschen.

<<v15>>
15 Er sagte zum Volk: Haltet euch für den dritten Tag bereit! Berührt
keine Frau!

<<v16>>
16 Am dritten Tag, im Morgengrauen, begann es zu donnern und zu blitzen.
Schwere Wolken lagen über dem Berg und gewaltiger Hörnerschall erklang.
Das ganze Volk im Lager begann zu zittern.

<<v17>>
17 Mose führte es aus dem Lager hinaus Gott entgegen. Unten am Berg
blieben sie stehen.

<<v18>>
18 Der ganze Sinai war in Rauch gehüllt, denn der Herr war im Feuer auf
ihn herabgestiegen. Der Rauch stieg vom Berg auf wie Rauch aus einem
Schmelzofen. Der ganze Berg bebte gewaltig

<<v19>>
19 und der Hörnerschall wurde immer lauter. Mose redete und Gott
antwortete im Donner.

<<v20>>
20 Der Herr war auf den Sinai, auf den Gipfel des Berges,
herabgestiegen. Er hatte Mose zu sich auf den Gipfel des Berges gerufen
und Mose war hinaufgestiegen.

<<v21>>
21 Da sprach der Herr zu Mose: Geh hinunter und schärf dem Volk ein, sie
sollen nicht neugierig sein und nicht versuchen, zum Herrn vorzudringen;
sonst müssten viele von ihnen umkommen.

<<v22>>
22 Auch die Priester, die sich dem Herrn nähern, müssen sich geheiligt
haben, damit der Herr in ihre Reihen keine Bresche reißt.

<<v23>>
23 Mose entgegnete dem Herrn: Das Volk kann nicht auf den Sinai steigen.
Denn du selbst hast uns eingeschärft: Zieh eine Grenze um den Berg und
erklär ihn für heilig!

<<v24>>
24 Doch der Herr sprach zu ihm: Geh hinunter und komm zusammen mit Aaron
wieder herauf! Die Priester aber und das Volk sollen nicht versuchen
hinaufzusteigen und zum Herrn vorzudringen, sonst reißt er in ihre
Reihen eine Bresche.

<<v25>>
25 Da ging Mose zum Volk hinunter und sagte es ihnen.\\
\\


* Footnotes

[fn:1] am heutigen Tag: Hinweis auf die liturgische Verwendung
des Textes an einem bestimmten Tag; die Juden lesen ihn am Wochenfest,
unserem Pfingstfest.

[fn:2] (5f) 1 Petr 2,9
