#+TITLE: Ex 14 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 22:29]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ex 14.html

* Ex 14

<<verses>>

<<v1>>
1 Der Herr sprach zu Mose:

<<v2>>
2 Sag den Israeliten, sie sollen umkehren und vor Pi-Hahirot zwischen
Migdol und dem Meer ihr Lager aufschlagen. Gegenüber von Baal-Zefon
sollt ihr am Meer das Lager aufschlagen.

<<v3>>
3 Dann denkt der Pharao: Die Israeliten haben sich im Land verlaufen,
die Wüste hat sie eingeschlossen.

<<v4>>
4 Ich will das Herz des Pharao verhärten, sodass er ihnen nachjagt; dann
will ich am Pharao und an seiner ganzen Streitmacht meine Herrlichkeit
erweisen und die Ägypter sollen erkennen, dass ich der Herr bin. Und so
taten sie es.

<<v5>>
5 Als man dem König von Ägypten meldete, das Volk sei geflohen, änderten
der Pharao und seine Diener ihre Meinung über das Volk und sagten: Wie
konnten wir nur Israel aus unserem Dienst entlassen!

<<v6>>
6 Er ließ seinen Streitwagen anspannen und nahm seine Leute mit.

<<v7>>
7 Sechshundert auserlesene Streitwagen nahm er mit und alle anderen
Streitwagen der Ägypter und drei Mann auf jedem Wagen.

<<v8>>
8 Der Herr verhärtete das Herz des Pharao, des Königs von Ägypten,
sodass er den Israeliten nachjagte, während sie voll Zuversicht
weiterzogen.

<<v9>>
9 Die Ägypter jagten mit allen Pferden und Streitwagen des Pharao, mit
seiner Reiterei und seiner Streitmacht hinter ihnen her und holten sie
ein, als sie gerade am Meer lagerten. Es war bei Pi-Hahirot vor
Baal-Zefon.

<<v10>>
10 Als der Pharao sich näherte, blickten die Israeliten auf und sahen
plötzlich die Ägypter von hinten anrücken. Da erschraken die Israeliten
sehr und schrien zum Herrn.

<<v11>>
11 Zu Mose sagten sie: Gab es denn keine Gräber in Ägypten, dass du uns
zum Sterben in die Wüste holst? Was hast du uns da angetan? Warum hast
du uns aus Ägypten herausgeführt?

<<v12>>
12 Haben wir dir in Ägypten nicht gleich gesagt: Lass uns in Ruhe! Wir
wollen Sklaven der Ägypter bleiben; denn es ist für uns immer noch
besser, Sklaven der Ägypter zu sein, als in der Wüste zu sterben.

<<v13>>
13 Mose aber sagte zum Volk: Fürchtet euch nicht! Bleibt stehen und
schaut zu, wie der Herr euch heute rettet. Wie ihr die Ägypter heute
seht, so seht ihr sie niemals wieder.

<<v14>>
14 Der Herr kämpft für euch, ihr aber könnt ruhig abwarten.

<<v15>>
15 Der Herr sprach zu Mose: Was schreist du zu mir? Sag den Israeliten,
sie sollen aufbrechen.

<<v16>>
16 Und du heb deinen Stab hoch, streck deine Hand über das Meer und
spalte es, damit die Israeliten auf trockenem Boden in das Meer
hineinziehen können.

<<v17>>
17 Ich aber will das Herz der Ägypter verhärten, damit sie hinter ihnen
hineinziehen. So will ich am Pharao und an seiner ganzen Streitmacht, an
seinen Streitwagen und Reitern meine Herrlichkeit erweisen.

<<v18>>
18 Die Ägypter sollen erkennen, dass ich der Herr bin, wenn ich am
Pharao, an seinen Streitwagen und Reitern meine Herrlichkeit erweise.

<<v19>>
19 Der Engel Gottes, der den Zug der Israeliten anführte, erhob sich und
ging an das Ende des Zuges und die Wolkensäule vor ihnen erhob sich und
trat an das Ende.

<<v20>>
20 Sie kam zwischen das Lager der Ägypter und das Lager der Israeliten.
Die Wolke war da und Finsternis und Blitze erhellten die Nacht. So kamen
sie die ganze Nacht einander nicht näher. [fn:1]

<<v21>>
21 Mose streckte seine Hand über das Meer aus und der Herr trieb die
ganze Nacht das Meer durch einen starken Ostwind fort. Er ließ das Meer
austrocknen und das Wasser spaltete sich.

<<v22>>
22 Die Israeliten zogen auf trockenem Boden ins Meer hinein, während
rechts und links von ihnen das Wasser wie eine Mauer stand.

<<v23>>
23 Die Ägypter setzten ihnen nach; alle Pferde des Pharao, seine
Streitwagen und Reiter zogen hinter ihnen ins Meer hinein.

<<v24>>
24 Um die Zeit der Morgenwache blickte der Herr aus der Feuer- und
Wolkensäule auf das Lager der Ägypter und brachte es in Verwirrung.

<<v25>>
25 Er hemmte die Räder an ihren Wagen und ließ sie nur schwer
vorankommen. Da sagte der Ägypter: Ich muss vor Israel fliehen; denn
Jahwe kämpft auf ihrer Seite gegen Ägypten.

<<v26>>
26 Darauf sprach der Herr zu Mose: Streck deine Hand über das Meer,
damit das Wasser zurückflutet und den Ägypter, seine Wagen und Reiter,
zudeckt.

<<v27>>
27 Mose streckte seine Hand über das Meer und gegen Morgen flutete das
Meer an seinen alten Platz zurück, während die Ägypter auf der Flucht
ihm entgegenliefen. So trieb der Herr die Ägypter mitten ins Meer.

<<v28>>
28 Das Wasser kehrte zurück und bedeckte Wagen und Reiter, die ganze
Streitmacht des Pharao, die den Israeliten ins Meer nachgezogen war.
Nicht ein Einziger von ihnen blieb übrig.

<<v29>>
29 Die Israeliten aber waren auf trockenem Boden mitten durch das Meer
gezogen, während rechts und links von ihnen das Wasser wie eine Mauer
stand.

<<v30>>
30 So rettete der Herr an jenem Tag Israel aus der Hand der Ägypter.
Israel sah die Ägypter tot am Strand liegen.

<<v31>>
31 Als Israel sah, dass der Herr mit mächtiger Hand an den Ägyptern
gehandelt hatte, fürchtete das Volk den Herrn. Sie glaubten an den Herrn
und an Mose, seinen Knecht.\\
\\


* Footnotes

[fn:1] H unklar, darum Übersetzung unsicher.
