#+TITLE: Ex 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 22:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ex 17.html

* Ex 17

<<verses>>

<<v1>>
1 Die ganze Gemeinde der Israeliten zog von der Wüste Sin weiter, von
einem Rastplatz zum andern, wie es der Herr jeweils bestimmte. In
Refidim schlugen sie ihr Lager auf. Weil das Volk kein Wasser zu trinken
hatte,

<<v2>>
2 geriet es mit Mose in Streit und sagte: Gebt uns Wasser zu trinken!
Mose aber antwortete: Was streitet ihr mit mir? Warum stellt ihr den
Herrn auf die Probe?

<<v3>>
3 Das Volk dürstete dort nach Wasser und murrte gegen Mose. Sie sagten:
Warum hast du uns überhaupt aus Ägypten hierher geführt? Um uns, unsere
Söhne und unser Vieh verdursten zu lassen?

<<v4>>
4 Mose schrie zum Herrn: Was soll ich mit diesem Volk anfangen? Es fehlt
nur wenig und sie steinigen mich.

<<v5>>
5 Der Herr antwortete Mose: Geh am Volk vorbei und nimm einige von den
Ältesten Israels mit; nimm auch den Stab in die Hand, mit dem du auf den
Nil geschlagen hast, und geh!

<<v6>>
6 Dort drüben auf dem Felsen am Horeb werde ich vor dir stehen. Dann
schlag an den Felsen! Es wird Wasser herauskommen und das Volk kann
trinken. Das tat Mose vor den Augen der Ältesten Israels.

<<v7>>
7 Den Ort nannte er Massa und Meriba (Probe und Streit), weil die
Israeliten Streit begonnen und den Herrn auf die Probe gestellt hatten,
indem sie sagten: Ist der Herr in unserer Mitte oder nicht? [fn:1]

<<v8>>
8 Als Amalek kam und in Refidim den Kampf mit Israel suchte,

<<v9>>
9 sagte Mose zu Josua: Wähl uns Männer aus und zieh in den Kampf gegen
Amalek! Ich selbst werde mich morgen auf den Gipfel des Hügels stellen
und den Gottesstab mitnehmen.

<<v10>>
10 Josua tat, was ihm Mose aufgetragen hatte, und kämpfte gegen Amalek,
während Mose, Aaron und Hur auf den Gipfel des Hügels stiegen.

<<v11>>
11 Solange Mose seine Hand erhoben hielt, war Israel stärker; sooft er
aber die Hand sinken ließ, war Amalek stärker.

<<v12>>
12 Als dem Mose die Hände schwer wurden, holten sie einen Steinbrocken,
schoben ihn unter Mose und er setzte sich darauf. Aaron und Hur stützten
seine Arme, der eine rechts, der andere links, sodass seine Hände
erhoben blieben, bis die Sonne unterging.

<<v13>>
13 So besiegte Josua mit scharfem Schwert Amalek und sein Heer.

<<v14>>
14 Danach sprach der Herr zu Mose: Halte das zur Erinnerung in einer
Urkunde fest und präg es Josua ein! Denn ich will die Erinnerung an
Amalek unter dem Himmel austilgen.

<<v15>>
15 Mose baute einen Altar und gab ihm den Namen «Jahwe mein
Feldzeichen».

<<v16>>
16 Er sagte: Die Hand an Jahwes Feldzeichen! Krieg ist zwischen Jahwe
und Amalek von Generation zu Generation.\\
\\


* Footnotes

[fn:1] Num 20,7-13; Dtn 32,51; 33,8; Ps 95,8f; 106,32f
