#+TITLE: Ex 11 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 22:22]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ex 11.html

* Ex 11

<<verses>>

<<v1>>
1 Da sprach der Herr zu Mose: Noch eine Plage schicke ich dem Pharao und
seinem Land. Danach wird er euch von hier wegziehen lassen. Und wenn er
euch endlich ziehen lässt, wird er euch sogar fortjagen.

<<v2>>
2 Lass unter dem Volk ausrufen, jeder Mann und jede Frau soll sich von
dem Nachbarn Geräte aus Silber und Gold erbitten. [fn:1]

<<v3>>
3 Der Herr ließ das Volk bei den Ägyptern Gunst finden. Auch Mose genoss
in Ägypten bei den Dienern des Pharao und beim Volk hohes Ansehen.

<<v4>>
4 Mose sagte: So spricht Jahwe: Um Mitternacht will ich mitten durch
Ägypten gehen.

<<v5>>
5 Dann wird jeder Erstgeborene in Ägypten sterben, vom Erstgeborenen des
Pharao, der auf dem Thron sitzt, bis zum Erstgeborenen der Magd an der
Handmühle und bis zu den Erstlingen unter dem Vieh. [fn:2]

<<v6>>
6 Geschrei wird sich in ganz Ägypten erheben, so groß, wie es keines je
gegeben hat oder geben wird.

<<v7>>
7 Doch gegen keinen der Israeliten wird auch nur ein Hund die Zähne
fletschen, weder gegen Mensch noch Vieh; denn ihr sollt wissen, dass
Jahwe zwischen Ägypten und Israel einen Unterschied macht.

<<v8>>
8 Dann werden alle deine Diener hier zu mir herabsteigen, sich vor mir
niederwerfen und sagen: Zieht doch fort, du und das ganze Volk, das du
anführst. Danach werde ich fortziehen. Er verließ den Pharao, rot vor
Zorn.

<<v9>>
9 Der Herr sprach zu Mose: Der Pharao hört nicht auf euch; denn ich will
viele Wunder in Ägypten vollbringen.

<<v10>>
10 Mose und Aaron vollbrachten alle diese Wunder vor den Augen des
Pharao, aber der Herr verhärtete das Herz des Pharao, sodass er die
Israeliten nicht aus seinem Land fortziehen ließ.\\
\\


* Footnotes

[fn:1] 3,22; 12,35f

[fn:2] 4,23
