#+TITLE: Ex 16 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 22:33]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ex 16.html

* Ex 16

<<verses>>

<<v1>>
1 Die ganze Gemeinde der Israeliten brach von Elim auf und kam in die
Wüste Sin, die zwischen Elim und dem Sinai liegt. Es war der fünfzehnte
Tag des zweiten Monats nach ihrem Auszug aus Ägypten.

<<v2>>
2 Die ganze Gemeinde der Israeliten murrte in der Wüste gegen Mose und
Aaron.

<<v3>>
3 Die Israeliten sagten zu ihnen: Wären wir doch in Ägypten durch die
Hand des Herrn gestorben, als wir an den Fleischtöpfen saßen und Brot
genug zu essen hatten. Ihr habt uns nur deshalb in diese Wüste geführt,
um alle, die hier versammelt sind, an Hunger sterben zu lassen.

<<v4>>
4 Da sprach der Herr zu Mose: Ich will euch Brot vom Himmel regnen
lassen. Das Volk soll hinausgehen, um seinen täglichen Bedarf zu
sammeln. Ich will es prüfen, ob es nach meiner Weisung lebt oder nicht.

<<v5>>
5 Wenn sie am sechsten Tag feststellen, was sie zusammengebracht haben,
wird es doppelt so viel sein, wie sie sonst täglich gesammelt haben.

<<v6>>
6 Da sagten Mose und Aaron zu allen Israeliten: Heute Abend sollt ihr
erfahren, dass der Herr euch aus Ägypten geführt hat,

<<v7>>
7 und morgen werdet ihr die Herrlichkeit des Herrn schauen; denn er hat
euer Murren gegen ihn gehört. Aber wer sind schon wir, dass ihr gegen
uns murrt?

<<v8>>
8 Weiter sagte Mose: Wenn der Herr euch heute Abend Fleisch zu essen
gibt und euch am Morgen mit Brot sättigt, wenn er also euer Murren hört,
mit dem ihr ihn bedrängt, was sind wir dann? Nicht uns galt euer Murren,
sondern dem Herrn. [fn:1]

<<v9>>
9 Dann sagte Mose zu Aaron: Sag der ganzen Gemeinde der Israeliten:
Tretet hin vor den Herrn; denn er hat euer Murren gehört.

<<v10>>
10 Während Aaron zur ganzen Gemeinde der Israeliten sprach, wandten sie
sich zur Wüste hin. Da erschien plötzlich in der Wolke die Herrlichkeit
des Herrn.

<<v11>>
11 Der Herr sprach zu Mose:

<<v12>>
12 Ich habe das Murren der Israeliten gehört. Sag ihnen: Am Abend werdet
ihr Fleisch zu essen haben, am Morgen werdet ihr satt sein von Brot und
ihr werdet erkennen, dass ich der Herr, euer Gott, bin.

<<v13>>
13 Am Abend kamen die Wachteln und bedeckten das Lager. Am Morgen lag
eine Schicht von Tau rings um das Lager.

<<v14>>
14 Als sich die Tauschicht gehoben hatte, lag auf dem Wüstenboden etwas
Feines, Knuspriges, fein wie Reif, auf der Erde.

<<v15>>
15 Als das die Israeliten sahen, sagten sie zueinander: Was ist das?
Denn sie wussten nicht, was es war. Da sagte Mose zu ihnen: Das ist das
Brot, das der Herr euch zu essen gibt. [fn:2]

<<v16>>
16 Das ordnet der Herr an: Sammelt davon so viel, wie jeder zum Essen
braucht, ein Gomer je Kopf. Jeder darf so viel Gomer holen, wie Personen
im Zelt sind.

<<v17>>
17 Die Israeliten taten es und sammelten ein, der eine viel, der andere
wenig.

<<v18>>
18 Als sie die Gomer zählten, hatte keiner, der viel gesammelt hatte, zu
viel und keiner, der wenig gesammelt hatte, zu wenig. Jeder hatte so
viel gesammelt, wie er zum Essen brauchte.

<<v19>>
19 Mose sagte zu ihnen: Davon darf bis zum Morgen niemand etwas übrig
lassen.

<<v20>>
20 Doch sie hörten nicht auf Mose, sondern einige ließen etwas bis zum
Morgen übrig. Aber es wurde wurmig und stank. Da geriet Mose in Zorn
über sie.

<<v21>>
21 Sie sammelten es Morgen für Morgen, jeder so viel, wie er zum Essen
brauchte. Sobald die Sonnenhitze einsetzte, zerging es.

<<v22>>
22 Am sechsten Tag sammelten sie die doppelte Menge Brot, zwei Gomer für
jeden. Da kamen alle Sippenhäupter der Gemeinde und berichteten es Mose.

<<v23>>
23 Er sagte zu ihnen: Es ist so, wie der Herr gesagt hat: Morgen ist
Feiertag, heiliger Sabbat zur Ehre des Herrn. Backt, was ihr backen
wollt, und kocht, was ihr kochen wollt, den Rest bewahrt bis morgen früh
auf!

<<v24>>
24 Sie bewahrten es also bis zum Morgen auf, wie es Mose angeordnet
hatte, und es faulte nicht, noch wurde es madig.

<<v25>>
25 Da sagte Mose: Esst es heute, denn heute ist Sabbat zur Ehre des
Herrn. Heute findet ihr draußen nichts.

<<v26>>
26 Sechs Tage dürft ihr es sammeln, am siebten Tag ist Sabbat; da findet
ihr nichts.

<<v27>>
27 Am siebten Tag gingen trotzdem einige vom Volk hinaus, um zu sammeln,
fanden aber nichts.

<<v28>>
28 Da sprach der Herr zu Mose: Wie lange wollt ihr euch noch weigern,
meine Gebote und Weisungen zu befolgen?

<<v29>>
29 Ihr seht, der Herr hat euch den Sabbat gegeben; daher gibt er auch am
sechsten Tag Brot für zwei Tage. Jeder bleibe, wo er ist. Am siebten Tag
verlasse niemand seinen Platz.

<<v30>>
30 Das Volk ruhte also am siebten Tag.

<<v31>>
31 Das Haus Israel nannte das Brot Manna. Es war weiß wie Koriandersamen
und schmeckte wie Honigkuchen. [fn:3]

<<v32>>
32 Mose sagte: Der Herr ordnet Folgendes an. Ein volles Gomer Manna ist
für die Generationen nach euch aufzubewahren, damit sie das Brot sehen,
das ich euch in der Wüste zu essen gab, als ich euch aus Ägypten
herausführte.

<<v33>>
33 Zu Aaron sagte Mose: Nimm ein Gefäß, schütte ein volles Gomer Manna
hinein und stell es vor den Herrn! Es soll für die nachkommenden
Generationen aufbewahrt werden.

<<v34>>
34 Wie der Herr dem Mose befohlen hatte, stellte Aaron das Manna vor die
Bundesurkunde, damit es dort aufbewahrt würde.

<<v35>>
35 Die Israeliten aßen vierzig Jahre lang Manna, bis sie in bewohntes
Land kamen. Sie aßen Manna, bis sie die Grenze von Kanaan erreichten. [fn:4]

<<v36>>
36 Ein Gomer ist der zehnte Teil eines Efa.


* Footnotes

[fn:1] Num 11,31-33; Ps 78,26-29; Weish 19,11f

[fn:2] 16,4; Num 11,7-9; Dtn 8,3.16; Ps 78,24; Weish 16,20-28

[fn:3] Manna bedeutet «Was ist das?» (vgl. V. 15). Man
vergleicht das biblische Manna oft mit dem genießbaren süßlichen Harz
der auf der Sinaihalbinsel noch heute vorkommenden Manna-Tamariske; doch
kommt dieses «Manna» in so geringen Mengen vor, dass es nicht für eine
größere wandernde Gruppe die Nahrung ersetzen kann. Die Bibel versteht
die Mannagabe als Wunder.

[fn:4] Jos 5,12
