#+TITLE: Ex 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:39]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ex 2.html

* Ex 2

<<verses>>

<<v1>>
* Die Jugend des Mose: 2,1-14
1 Ein Mann aus einer levitischen Familie ging hin und nahm eine Frau aus
dem gleichen Stamm.

<<v2>>
2 Sie wurde schwanger und gebar einen Sohn. Weil sie sah, dass es ein
schönes Kind war, verbarg sie es drei Monate lang.

<<v3>>
3 Als sie es nicht mehr verborgen halten konnte, nahm sie ein
Binsenkästchen, dichtete es mit Pech und Teer ab, legte den Knaben
hinein und setzte ihn am Nilufer im Schilf aus.

<<v4>>
4 Seine Schwester blieb in der Nähe stehen, um zu sehen, was mit ihm
geschehen würde.

<<v5>>
5 Die Tochter des Pharao kam herab, um im Nil zu baden. Ihre Dienerinnen
gingen unterdessen am Nilufer auf und ab. Auf einmal sah sie im Schilf
das Kästchen und ließ es durch ihre Magd holen.

<<v6>>
6 Als sie es öffnete und hineinsah, lag ein weinendes Kind darin. Sie
bekam Mitleid mit ihm und sie sagte: Das ist ein Hebräerkind.

<<v7>>
7 Da sagte seine Schwester zur Tochter des Pharao: Soll ich zu den
Hebräerinnen gehen und dir eine Amme rufen, damit sie dir das Kind
stillt?

<<v8>>
8 Die Tochter des Pharao antwortete ihr: Ja, geh! Das Mädchen ging und
rief die Mutter des Knaben herbei.

<<v9>>
9 Die Tochter des Pharao sagte zu ihr: Nimm das Kind mit und still es
mir! Ich werde dich dafür entlohnen. Die Frau nahm das Kind zu sich und
stillte es.

<<v10>>
10 Als der Knabe größer geworden war, brachte sie ihn der Tochter des
Pharao. Diese nahm ihn als Sohn an, nannte ihn Mose und sagte: Ich habe
ihn aus dem Wasser gezogen. [fn:1]

<<v11>>
11 Die Jahre vergingen und Mose wuchs heran. Eines Tages ging er zu
seinen Brüdern hinaus und schaute ihnen bei der Fronarbeit zu. Da sah
er, wie ein Ägypter einen Hebräer schlug, einen seiner Stammesbrüder.

<<v12>>
12 Mose sah sich nach allen Seiten um, und als er sah, dass sonst
niemand da war, erschlug er den Ägypter und verscharrte ihn im Sand.

<<v13>>
13 Als er am nächsten Tag wieder hinausging, sah er zwei Hebräer
miteinander streiten. Er sagte zu dem, der im Unrecht war: Warum
schlägst du deinen Stammesgenossen?

<<v14>>
14 Der Mann erwiderte: Wer hat dich zum Aufseher und Schiedsrichter über
uns bestellt? Meinst du, du könntest mich umbringen, wie du den Ägypter
umgebracht hast? Da bekam Mose Angst und sagte: Die Sache ist also
bekannt geworden.\\
\\

<<v15>>
* Mose in Midian: 2,15-22
15 Der Pharao hörte von diesem Vorfall und wollte Mose töten; Mose aber
entkam ihm. Er wollte in Midian bleiben und setzte sich an einen
Brunnen.

<<v16>>
16 Der Priester von Midian hatte sieben Töchter. Sie kamen zum
Wasserschöpfen und wollten die Tröge füllen, um die Schafe und Ziegen
ihres Vaters zu tränken.

<<v17>>
17 Doch die Hirten kamen und wollten sie verdrängen. Da stand Mose auf,
kam ihnen zu Hilfe und tränkte ihre Schafe und Ziegen.

<<v18>>
18 Als sie zu ihrem Vater Reguël zurückkehrten, fragte er: Warum seid
ihr heute so schnell wieder da? [fn:2]

<<v19>>
19 Sie erzählten: Ein Ägypter hat uns gegen die Hirten verteidigt; er
hat uns sogar Wasser geschöpft und das Vieh getränkt.

<<v20>>
20 Da fragte Reguël seine Töchter: Wo ist er? Warum habt ihr ihn dort
gelassen? Holt ihn und ladet ihn zum Essen ein!

<<v21>>
21 Mose entschloss sich, bei dem Mann zu bleiben, und dieser gab seine
Tochter Zippora Mose zur Frau.

<<v22>>
22 Als sie einen Sohn gebar, nannte er ihn Gerschom (Ödgast) und sagte:
Gast bin ich in fremdem Land. [fn:3] [fn:4]\\
\\

<<v23>>
* Die Berufung des Mose: 2,23 - 4,17
23 Nach vielen Jahren starb der König von Ägypten. Die Israeliten
stöhnten noch unter der Sklavenarbeit; sie klagten und ihr Hilferuf
stieg aus ihrem Sklavendasein zu Gott empor.

<<v24>>
24 Gott hörte ihr Stöhnen und Gott gedachte seines Bundes mit Abraham,
Isaak und Jakob.

<<v25>>
25 Gott blickte auf die Söhne Israels und gab sich ihnen zu erkennen. [fn:5]

* Footnotes

[fn:1] Der Name Mose ist ägyptisch und bedeutet «Kind»; der
israelitische Erzähler hört das hebräische Zeitwort «ziehen» (mascháh)
heraus.

[fn:2] Reguël: So auch Num 10,29 [[file:Num_10.org::v29][Num 10,29]]. In Ex 3,1 [[file:Ex_3.org::v1][Ex 3,1]]; 4,18 [[file:Ex_4.org::v18][Ex 4,18]]; 18,1 [[file:Ex_18.org::v1][Ex 18,1]] heißt
er Jitro, in Ri 4,11 [[file:Ri_4.org::11][Ri 4,11]] aber Hobab. In den verschiedenen Traditionsschichten lautet der Name anders, ähnlich wie der Berg des Bundesschlusses bald Sinai, bald Horeb heißt.

[fn:3] 18,3 [[file:Ex_18.org::v3][Ex 18,3]]

[fn:4] Wortspiel mit dem Namen Gerschom, der aus ger (= Gast)
und schom (= Öde) zusammengesetzt ist; in der Deutung des Namens wird
aber das ungewöhnliche schom durch das geläufigere nokrí (= fremd)
verdeutlicht.

[fn:5] und gab sich ihnen zu erkennen: so nach G.
