#+TITLE: Ex 24 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 23:22]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ex 24.html

<<verses>>

<<v1>>
* Der Bundesschluß: 24,1-18
Zu Mose sprach er: Steig zum Herrn hinauf zusammen mit Aaron, Nadab,
Abihu und mit siebzig von den Ältesten Israels; werft euch in einiger
Entfernung nieder!

<<v2>>
2 Mose allein soll sich dem Herrn nähern, die anderen dürfen nicht näher
kommen und das Volk darf den Berg nicht mit ihm zusammen besteigen.

<<v3>>
3 Mose kam und übermittelte dem Volk alle Worte und Rechtsvorschriften
des Herrn. Das ganze Volk antwortete einstimmig und sagte: Alles, was
der Herr gesagt hat, wollen wir tun.

<<v4>>
4 Mose schrieb alle Worte des Herrn auf. Am nächsten Morgen stand er
zeitig auf und errichtete am Fuß des Berges einen Altar und zwölf
Steinmale für die zwölf Stämme Israels.

<<v5>>
5 Er schickte die jungen Männer Israels aus. Sie brachten Brandopfer dar
und schlachteten junge Stiere als Heilsopfer für den Herrn.

<<v6>>
6 Mose nahm die Hälfte des Blutes und goss es in eine Schüssel, mit der
anderen Hälfte besprengte er den Altar.

<<v7>>
7 Darauf nahm er die Urkunde des Bundes und verlas sie vor dem Volk. Sie
antworteten: Alles, was der Herr gesagt hat, wollen wir tun; wir wollen
gehorchen.

<<v8>>
8 Da nahm Mose das Blut, besprengte damit das Volk und sagte: Das ist
das Blut des Bundes, den der Herr aufgrund all dieser Worte mit euch
geschlossen hat.

<<v9>>
9 Danach stiegen Mose, Aaron, Nadab, Abihu und die siebzig von den
Ältesten Israels hinauf

<<v10>>
10 und sie sahen den Gott Israels. Die Fläche unter seinen Füßen war wie
mit Saphir ausgelegt und glänzte hell wie der Himmel selbst.

<<v11>>
11 Gott streckte nicht seine Hand gegen die Edlen der Israeliten aus;
sie durften Gott sehen und sie aßen und tranken.

<<v12>>
12 Der Herr sprach zu Mose: Komm herauf zu mir auf den Berg und bleib
hier! Ich will dir die Steintafeln übergeben, die Weisung und die
Gebote, die ich aufgeschrieben habe. Du sollst das Volk darin
unterweisen.

<<v13>>
13 Da erhob sich Mose mit seinem Diener Josua und stieg den Gottesberg
hinauf.

<<v14>>
14 Zu den Ältesten sagte er: Bleibt hier, bis wir zu euch zurückkehren;
Aaron und Hur sind ja bei euch. Wer ein Anliegen hat, wende sich an sie.

<<v15>>
15 Dann stieg Mose auf den Berg und die Wolke bedeckte den Berg.

<<v16>>
16 Die Herrlichkeit des Herrn ließ sich auf den Sinai herab und die
Wolke bedeckte den Berg sechs Tage lang. Am siebten Tag rief der Herr
mitten aus der Wolke Mose herbei.

<<v17>>
17 Die Erscheinung der Herrlichkeit des Herrn auf dem Gipfel des Berges
zeigte sich vor den Augen der Israeliten wie verzehrendes Feuer.

<<v18>>
18 Mose ging mitten in die Wolke hinein und stieg auf den Berg hinauf.
Vierzig Tage und vierzig Nächte blieb Mose auf dem Berg.\\
\\
