#+TITLE: Ex 27 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 23:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ex 27.html

* Ex 26
<<verses>>

<<v1>>
1 Die Wohnstätte sollst du aus zehn Zelttüchern herstellen; aus
gezwirntem Byssus, violettem und rotem Purpur und Karmesin mit Kerubim
sollst du sie machen, wie es ein Kunstweber macht. [fn:1] [fn:2]

<<v2>>
2 Ein Zelttuch soll achtundzwanzig Ellen lang und vier Ellen breit sein;
alle Zelttücher sollen dasselbe Maß haben.

<<v3>>
3 Fünf Zelttücher sollen jeweils aneinander gefügt sein.

<<v4>>
4 Mach Schleifen aus violettem Purpur am Rand des einen Zelttuchs, am
Ende des zusammengefügten Stückes; ebenso sollst du es am Rand des
letzten Zelttuchs des außen zusammengefügten Stückes machen.

<<v5>>
5 Fünfzig Schleifen sollst du an dem einen Zelttuch anbringen und
fünfzig Schleifen am Zelttuchende des zweiten zusammengefügten Stückes;
die Schleifen sollen einander entsprechen.

<<v6>>
6 Du sollst auch fünfzig Goldhaken machen und die Zelttücher mit den
Haken verbinden, eines mit dem andern; so soll die Wohnstätte ein Ganzes
bilden.

<<v7>>
7 Mach Decken aus Ziegenhaar für das Zelt über der Wohnstätte; elf Stück
sollst du herstellen. [fn:3]

<<v8>>
8 Eine Decke soll dreißig Ellen lang und vier Ellen breit sein; die elf
Decken sollen dasselbe Maß haben.

<<v9>>
9 Verbinde fünf Decken zu einem Stück und sechs Decken zu einem Stück;
die sechste Decke sollst du an der Vorderseite des Zeltes doppelt
zusammenlegen.

<<v10>>
10 Fünfzig Schleifen mach am Saum der Decke, die das Ende eines
zusammengesetzten Stückes bildet, und ebenso fünfzig Schleifen am Saum
der Decke, die das Ende des andern zusammengesetzten Stückes bildet.

<<v11>>
11 Fertige fünfzig Kupferhaken an, häng die Haken in die Schleifen und
setz das Zelt so zusammen, dass es ein Ganzes bildet.

<<v12>>
12 Den herabhängenden überschüssigen Teil der Zeltdecke lass zur Hälfte
an der Rückseite der Wohnstätte herabhängen!

<<v13>>
13 Die überschüssige Elle auf beiden Längsseiten der Zeltdecken soll auf
die beiden Seiten der Wohnstätte herabhängen, sodass sie sie bedeckt.

<<v14>>
14 Schließlich mach für das Zelt eine Decke aus rötlichen Widderfellen
und darüber eine Decke aus Tahaschhäuten! [fn:4]

<<v15>>
15 Mach für die Wohnstätte Bretter aus Akazienholz zum Aufstellen! [fn:5]

<<v16>>
16 Jedes Brett soll zehn Ellen lang und anderthalb Ellen breit sein;

<<v17>>
17 jedes Brett soll durch zwei Zapfen mit dem nächsten verbunden werden.
So mach es mit allen Brettern für die Wohnstätte!

<<v18>>
18 An Brettern für die Wohnstätte verfertige zwanzig für die Südseite!

<<v19>>
19 Stell vierzig Sockel aus Silber her als Unterlage für die zwanzig
Bretter je zwei Sockel als Unterlage eines Brettes für seine beiden
Zapfen!

<<v20>>
20 Für die zweite Seite der Wohnstätte, die Nordseite, ebenfalls zwanzig
Bretter

<<v21>>
21 und vierzig Sockel aus Silber, je zwei Sockel als Unterlage eines
Brettes.

<<v22>>
22 Für die Rückseite der Wohnstätte, die Westseite, verfertige sechs
Bretter

<<v23>>
23 und zwei Bretter stell für die Eckstücke an der Rückseite der
Wohnstätte her!

<<v24>>
24 Sie sollen einander entsprechen und von unten bis oben zum ersten
Ring reichen. So soll es mit den beiden Brettern geschehen, die die
Eckstücke bilden.

<<v25>>
25 Acht Bretter und sechzehn Sockel aus Silber sollen vorhanden sein, je
zwei Sockel als Unterlage für jedes Brett.

<<v26>>
26 Verfertige Querlatten aus Akazienholz, fünf für die Bretter auf der
einen Seite der Wohnstätte, [fn:6]

<<v27>>
27 fünf für die Bretter der zweiten Seite der Wohnstätte und fünf für
die Bretter der Rückseite der Wohnstätte, der Westseite!

<<v28>>
28 Die mittlere Querlatte soll in der Mitte der Bretter angebracht
werden und von einem Ende zum andern reichen.

<<v29>>
29 Überzieh die Bretter mit Gold und mach Ringe aus Gold, welche die
Querlatten aufnehmen; auch die Querlatten überzieh mit Gold!

<<v30>>
30 So errichte die Wohnstätte nach dem Muster, das dir auf dem Berg
gezeigt worden ist.

<<v31>>
31 Mach einen Vorhang aus violettem und rotem Purpur, Karmesin und
gezwirntem Byssus; wie Kunstweberarbeit soll er gemacht werden, mit
Kerubim. [fn:7]

<<v32>>
32 Häng ihn an die vier mit Gold überzogenen Akaziensäulen, die auf vier
Sockeln aus Silber stehen sollen. Auch die Nägel der Säulen sollen aus
Gold sein.

<<v33>>
33 Häng den Vorhang an die Haken und bring dorthin, hinter den Vorhang,
die Lade der Bundesurkunde! Der Vorhang trenne euch das Heiligtum vom
Allerheiligsten.

<<v34>>
34 Setz die Deckplatte auf die Lade der Bundesurkunde im
Allerheiligsten!

<<v35>>
35 Stell den Tisch außen vor den Vorhang, den Leuchter gegenüber dem
Tisch an die Südseite der Wohnstätte; den Tisch stell an die Nordseite!

<<v36>>
36 Für den Eingang des Zeltes mach einen Vorhang aus violettem und rotem
Purpur, Karmesin und gezwirntem Byssus; Arbeit eines Buntwirkers soll er
sein.

<<v37>>
37 Für den Vorhang mach fünf Akaziensäulen, überzieh sie mit Gold und
gieß für sie fünf kupferne Sockel! Auch die Nägel der Säulen sollen aus
Gold sein.


* Footnotes

[fn:1] (1-6) 36,8-13

[fn:2] Zu Byssus vgl. die Anmerkung zu Gen 41,42.

[fn:3] (7-14) 36,14-19

[fn:4] Zu den Tahaschhäuten vgl. die Anmerkung zu 25,5.

[fn:5] (15-25) 36,20-30

[fn:6] (26-30) 36,31-34

[fn:7] (31-37) 36,35-38
