#+TITLE: Ex 22 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 23:08]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ex 22.html

* Ex 22
<<verses>>

<<v1>>
1 Wird ein Dieb beim Einbruch ertappt und so geschlagen, dass er stirbt,
so entsteht dadurch keine Blutschuld.

<<v2>>
2 Doch ist darüber bereits die Sonne aufgegangen, dann entsteht
Blutschuld. Ein Dieb muss Ersatz leisten. Besitzt er nichts, soll man
ihn für den Wert des Gestohlenen verkaufen.

<<v3>>
3 Findet man das Gestohlene, sei es Rind, Esel oder Schaf, noch lebend
in seinem Besitz, dann soll er doppelten Ersatz leisten.\\
\\

<<v4>>
* Ersatz bei fahrlässigem Feldbrand: 22,4-5
4 Wenn jemand ein Feld oder einen Weinberg abbrennt und das Feuer sich
ausbreiten lässt, sodass es das Feld eines andern in Brand steckt, dann
soll er den besten Ertrag seines Feldes oder Weinbergs als Ersatz dafür
geben.

<<v5>>
5 Breitet sich das Feuer aus, erfasst es eine Dornenhecke und vernichtet
einen Getreidehaufen, auf dem Halm stehendes Getreide oder ein Feld,
dann soll der für den Brand Verantwortliche den Schaden ersetzen.\\
\\

<<v6>>
* Haftung für fremdes Eigentum: 22,6-14
6 Übergibt jemand einem andern Geld oder Gerät zur Aufbewahrung und es
wird aus dessen Haus gestohlen, dann soll der Dieb, wenn man ihn findet,
doppelten Ersatz leisten.

<<v7>>
7 Findet man den Dieb nicht, soll der Hausherr vor Gott erklären, dass
er sich nicht selbst am Eigentum des andern vergriffen hat.

<<v8>>
8 Wenn jemandem etwas veruntreut wurde, ein Rind, ein Esel, ein Schaf,
ein Kleid oder sonst etwas, und er behauptet: Ja, das ist es, dann soll
der Streitfall der beiden vor Gott kommen. Wen Gott als schuldig
bezeichnet, soll dem andern doppelten Ersatz leisten.

<<v9>>
9 Wenn jemand einem andern einen Esel, ein Rind, ein Schaf oder sonst
ein Haustier zur Verwahrung übergibt und das Tier eingeht, sich etwas
bricht oder fortgetrieben wird, ohne dass es jemand sieht,

<<v10>>
10 dann soll ein Eid beim Namen des Herrn Klarheit darüber schaffen,
dass der eine sich nicht am Eigentum des andern vergriffen hat. Der
Eigentümer soll an sich nehmen, was noch da ist, ohne dass der andere
Ersatz zu leisten hätte.

<<v11>>
11 Ist es ihm aber gestohlen worden, muss er dem Eigentümer Ersatz
leisten.

<<v12>>
12 Ist das Tier gerissen worden, bringe er es zum Beweis herbei; dann
braucht er für das Gerissene keinen Ersatz zu leisten.

<<v13>>
13 Leiht jemand von einem andern ein Tier und bricht es sich etwas oder
geht ein, und zwar in Abwesenheit des Eigentümers, so muss er Ersatz
leisten.

<<v14>>
14 War der Eigentümer aber anwesend, so braucht der andere keinen Ersatz
zu leisten. Ist er Taglöhner, so geht es von seinem Lohn ab.\\
\\

<<v15>>
* Verführung einer Jungfrau: 22,15-16
15 Wenn jemand ein noch nicht verlobtes Mädchen verführt und bei ihm
schläft, dann soll er das Brautgeld zahlen und sie zur Frau nehmen.

<<v16>>
16 Weigert sich aber ihr Vater, sie ihm zu geben, dann hat er ihm so
viel zu zahlen, wie der Brautpreis für eine Jungfrau beträgt.\\
\\

<<v17>>
* Todeswürdige Verbrechen: Zauberei, Bestialität, Götzendienst: 22,17-19
17 Eine Hexe sollst du nicht am Leben lassen. [fn:1]

<<v18>>
18 Jeder, der mit einem Tier verkehrt, soll mit dem Tod bestraft werden. [fn:2]

<<v19>>
19 Wer einer Gottheit außer Jahwe Schlachtopfer darbringt, an dem soll
die Vernichtungsweihe vollstreckt werden. [fn:3]\\
\\

<<v20>>
* Schutz vor Unterdrückung und Ausbeutung: 22,20-26
20 Einen Fremden sollst du nicht ausnützen oder ausbeuten, denn ihr
selbst seid in Ägypten Fremde gewesen.

<<v21>>
21 Ihr sollt keine Witwe oder Waise ausnützen.

<<v22>>
22 Wenn du sie ausnützt und sie zu mir schreit, werde ich auf ihren
Klageschrei hören.

<<v23>>
23 Mein Zorn wird entbrennen und ich werde euch mit dem Schwert
umbringen, sodass eure Frauen zu Witwen und eure Söhne zu Waisen werden.

<<v24>>
24 Leihst du einem aus meinem Volk, einem Armen, der neben dir wohnt,
Geld, dann sollst du dich gegen ihn nicht wie ein Wucherer benehmen. Ihr
sollt von ihm keinen Wucherzins fordern. [fn:4]

<<v25>>
25 Nimmst du von einem Mitbürger den Mantel zum Pfand, dann sollst du
ihn bis Sonnenuntergang zurückgeben;

<<v26>>
26 denn es ist seine einzige Decke, der Mantel, mit dem er seinen bloßen
Leib bedeckt. Worin soll er sonst schlafen? Wenn er zu mir schreit, höre
ich es, denn ich habe Mitleid.\\
\\

<<v27>>
* Gotteslästerung und Majestätsbeleidigung: 22,27
27 Du sollst Gott nicht verächtlich machen und den Fürsten deines Volkes
nicht verfluchen.\\
\\

<<v28>>
* Erstlingsopfer: 22,28-29
28 Deinen Reichtum und Überfluss sollst du nicht für dich behalten. Den
Erstgeborenen unter deinen Söhnen sollst du mir geben. [fn:5]

<<v29>>
29 Ebenso sollst du es mit deinen Rindern, Schafen und Ziegen halten.
Sieben Tage sollen sie bei ihrer Mutter bleiben, am achten Tag sollst du
sie mir übergeben.\\
\\

<<v30>>
* Verbot, gerissene Tiere zu essen: 22,30
30 Als heilige Männer sollt ihr mir gehören. Fleisch von einem Tier, das
auf dem Feld gerissen wurde, sollt ihr nicht essen; ihr sollt es den
Hunden vorwerfen. [fn:6]\\
\\


* Footnotes

[fn:1] Lev 20,27; Dtn 18,10-12

[fn:2] 27,21

[fn:3] Dtn 13,3f; 13-16; 18,13

[fn:4] Lev 25,36f; Dtn 23,20f

[fn:5] 34,19f; Dtn 15,19-23

[fn:6] Lev 17,15
