#+TITLE: Ex 37 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 08:51]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ex 37.html

* Ex 37
<<verses>>

<<v1>>
1 Dann machte Bezalel die Lade aus Akazienholz, zweieinhalb Ellen lang,
anderthalb Ellen breit und anderthalb Ellen hoch. [fn:1]

<<v2>>
2 Er überzog sie innen und außen mit purem Gold und brachte daran
ringsherum eine Goldleiste an.

<<v3>>
3 Er goss für sie vier Goldringe und befestigte sie an ihren vier Füßen,
zwei Ringe an der einen Seite und zwei Ringe an der anderen Seite.

<<v4>>
4 Er fertigte Stangen aus Akazienholz an und überzog sie mit Gold.

<<v5>>
5 Er steckte die Stangen durch die Ringe an den Seiten der Lade, sodass
man damit die Lade tragen konnte.

<<v6>>
6 Er verfertigte auch eine Deckplatte aus purem Gold, zweieinhalb Ellen
lang und anderthalb Ellen breit.

<<v7>>
7 Er machte zwei Kerubim aus getriebenem Gold und arbeitete sie aus den
beiden Enden der Deckplatte heraus,

<<v8>>
8 und zwar einen Kerub an dem einen Ende und einen Kerub an dem andern
Ende der Deckplatte; er arbeitete die Kerubim an ihren beiden Enden
heraus.

<<v9>>
9 Die Kerubim breiteten ihre Flügel nach oben aus; mit ihren Flügeln
beschirmten sie die Deckplatte und sie wandten ihre Gesichter einander
zu; die Gesichter waren der Deckplatte zugewandt.

<<v10>>
10 Er fertigte auch den Tisch aus Akazienholz an, zwei Ellen lang, eine
Elle breit und anderthalb Ellen hoch. [fn:2]

<<v11>>
11 Er überzog ihn mit purem Gold und brachte daran ringsherum eine
Goldleiste an.

<<v12>>
12 Er machte ihm ringsherum eine handbreite Einfassung und verfertigte
um diese Einfassung eine goldene Leiste.

<<v13>>
13 Er goss für ihn vier Goldringe und befestigte die Ringe an den vier
Ecken, die von seinen vier Füßen gebildet wurden.

<<v14>>
14 Die Ringe waren dicht unter der Einfassung, sodass sie die Stangen
aufnahmen und man den Tisch tragen konnte.

<<v15>>
15 Er machte die Stangen aus Akazienholz und überzog sie mit Gold,
sodass man den Tisch tragen konnte.

<<v16>>
16 Dazu machte er die Geräte, die auf dem Tisch stehen sollten: seine
Schüsseln, Schalen, Kannen und Krüge für die Trankopfer - alles aus
purem Gold.

<<v17>>
17 Er machte den Leuchter aus purem Gold. Der Leuchter, sein Gestell und
sein Schaft, seine Kelche, Knospen und Blüten waren aus einem Stück
getrieben. [fn:3]

<<v18>>
18 Von seinen Seiten gingen sechs Arme aus, drei Leuchterarme auf der
einen Seite und drei Leuchterarme auf der anderen Seite.

<<v19>>
19 Der erste Arm wies drei mandelblütenförmige Kelche auf mit je einer
Knospe und einer Blüte und der zweite Arm wies drei mandelblütenförmige
Kelche auf mit je einer Knospe und einer Blüte; so alle sechs Arme, die
von dem Leuchter ausgingen.

<<v20>>
20 An dem Leuchter waren vier mandelblütenförmige Kelche, Knospen und
Blüten:

<<v21>>
21 je eine Knospe unten zwischen zwei Armen, entsprechend den sechs
Armen, die vom Leuchter ausgingen.

<<v22>>
22 Die Knospen und Arme bildeten mit dem Schaft ein Ganzes; das Ganze
war ein Stück aus getriebenem purem Gold.

<<v23>>
23 Dann machte er auch für den Leuchter die sieben Lampen, seine
Dochtscheren und Pfannen aus purem Gold.

<<v24>>
24 Aus einem Talent puren Goldes machte er den Leuchter und alle
dazugehörenden Geräte.

<<v25>>
25 Auch machte er den Räucheraltar aus Akazienholz, eine Elle lang, eine
Elle breit - also quadratisch - und zwei Ellen hoch; seine Hörner
bildeten mit ihm eine Einheit. [fn:4]

<<v26>>
26 Er überzog ihn mit purem Gold, seine Platte, seine Wände ringsum und
seine Hörner, und brachte an ihm ringsum eine Goldleiste an.

<<v27>>
27 Er machte für ihn zwei Paar Goldringe und befestigte sie unterhalb
der Leiste an seinen beiden Seiten, seinen Seitenwänden, zum Aufnehmen
der Stangen, sodass man ihn damit tragen konnte.

<<v28>>
28 Er machte die Stangen aus Akazienholz und überzog sie mit Gold.

<<v29>>
29 Er bereitete auch das heilige Salböl und das reine duftende
Räucherwerk, wie Salbenmischer sie zubereiten. [fn:5]


* Footnotes

[fn:1] (1-9) 25,10-22 [[file:Ex_25.org::v10][Ex 25,10-22]]

[fn:2] (10-16) 25,23-30 [[file:Ex_25.org::v23][Ex 25,23-30]]

[fn:3] (17-24) 25,31-39 [[file:Ex_25.org::v31][Ex 25,31-39]]

[fn:4] (25-28) 30,1-10 [[file:Ex_30.org::v1][Ex 30,1-10]]

[fn:5] 30,22-33 [[file:Ex_30.org::v22][Ex 30,22-33]]
