#+TITLE: Ex 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 09:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ex 3.html


* Ex 3
<<verses>>

<<v1>>
1 Mose weidete die Schafe und Ziegen seines Schwiegervaters Jitro, des
Priesters von Midian. Eines Tages trieb er das Vieh über die Steppe
hinaus und kam zum Gottesberg Horeb.

<<v2>>
2 Dort erschien ihm der Engel des Herrn in einer Flamme, die aus einem
Dornbusch emporschlug. Er schaute hin: Da brannte der Dornbusch und
verbrannte doch nicht.

<<v3>>
3 Mose sagte: Ich will dorthin gehen und mir die außergewöhnliche
Erscheinung ansehen. Warum verbrennt denn der Dornbusch nicht?

<<v4>>
4 Als der Herr sah, dass Mose näher kam, um sich das anzusehen, rief
Gott ihm aus dem Dornbusch zu: Mose, Mose! Er antwortete: Hier bin ich.

<<v5>>
5 Der Herr sagte: Komm nicht näher heran! Leg deine Schuhe ab; denn der
Ort, wo du stehst, ist heiliger Boden.

<<v6>>
6 Dann fuhr er fort: Ich bin der Gott deines Vaters, der Gott Abrahams,
der Gott Isaaks und der Gott Jakobs. Da verhüllte Mose sein Gesicht;
denn er fürchtete sich, Gott anzuschauen.

<<v7>>
7 Der Herr sprach: Ich habe das Elend meines Volkes in Ägypten gesehen
und ihre laute Klage über ihre Antreiber habe ich gehört. Ich kenne ihr
Leid.

<<v8>>
8 Ich bin herabgestiegen, um sie der Hand der Ägypter zu entreißen und
aus jenem Land hinaufzuführen in ein schönes, weites Land, in ein Land,
in dem Milch und Honig fließen, in das Gebiet der Kanaaniter, Hetiter,
Amoriter, Perisiter, Hiwiter und Jebusiter.

<<v9>>
9 Jetzt ist die laute Klage der Israeliten zu mir gedrungen und ich habe
auch gesehen, wie die Ägypter sie unterdrücken.

<<v10>>
10 Und jetzt geh! Ich sende dich zum Pharao. Führe mein Volk, die
Israeliten, aus Ägypten heraus!

<<v11>>
11 Mose antwortete Gott: Wer bin ich, dass ich zum Pharao gehen und die
Israeliten aus Ägypten herausführen könnte?

<<v12>>
12 Gott aber sagte: Ich bin mit dir; ich habe dich gesandt und als
Zeichen dafür soll dir dienen: Wenn du das Volk aus Ägypten
herausgeführt hast, werdet ihr Gott an diesem Berg verehren.

<<v13>>
13 Da sagte Mose zu Gott: Gut, ich werde also zu den Israeliten kommen
und ihnen sagen: Der Gott eurer Väter hat mich zu euch gesandt. Da
werden sie mich fragen: Wie heißt er? Was soll ich ihnen darauf sagen?

<<v14>>
14 Da antwortete Gott dem Mose: Ich bin der «Ich-bin-da». Und er fuhr
fort: So sollst du zu den Israeliten sagen: Der «Ich-bin-da» hat mich zu
euch gesandt. [fn:1]

<<v15>>
15 Weiter sprach Gott zu Mose: So sag zu den Israeliten: Jahwe, der Gott
eurer Väter, der Gott Abrahams, der Gott Isaaks und der Gott Jakobs, hat
mich zu euch gesandt. Das ist mein Name für immer und so wird man mich
nennen in allen Generationen.

<<v16>>
16 Geh, versammle die Ältesten Israels und sag ihnen: Jahwe, der Gott
eurer Väter, der Gott Abrahams, Isaaks und Jakobs, ist mir erschienen
und hat mir gesagt: Ich habe sorgsam auf euch geachtet und habe gesehen,
was man euch in Ägypten antut.

<<v17>>
17 Darum habe ich beschlossen, euch aus dem Elend Ägyptens
hinaufzuführen in das Land der Kanaaniter, Hetiter, Amoriter, Perisiter,
Hiwiter und Jebusiter, in ein Land, in dem Milch und Honig fließen.

<<v18>>
18 Wenn sie auf dich hören, so geh mit den Ältesten Israels zum König
von Ägypten; sagt ihm: Jahwe, der Gott der Hebräer, ist uns begegnet.
Und jetzt wollen wir drei Tagesmärsche weit in die Wüste ziehen und
Jahwe, unserem Gott, Schlachtopfer darbringen. [fn:2]

<<v19>>
19 Ich weiß, dass euch der König von Ägypten nicht ziehen lässt, es sei
denn, er würde von starker Hand dazu gezwungen.

<<v20>>
20 Erst wenn ich meine Hand ausstrecke und Ägypten niederschlage mit
allen meinen Wundern, die ich in seiner Mitte vollbringe, wird er euch
ziehen lassen.

<<v21>>
21 Dann werde ich die Ägypter zugunsten dieses Volkes umstimmen, und
wenn ihr wegzieht, werdet ihr nicht mit leeren Händen gehen.

<<v22>>
22 Jede Frau kann von ihrer Nachbarin oder Hausgenossin silberne und
goldene Geräte und Kleider verlangen. Übergebt sie euren Söhnen und
Töchtern und plündert so die Ägypter aus!

* Footnotes

[fn:1] 14f: Im Hebräischen ist «Jahwe» eine Zeitwortform in
der 3. Person Einzahl, etwa «er ist da»; da hier Gott von sich selbst in
der 1. Person redet, gebraucht er das Zeitwort in der Ich-Form: Ich bin
da. Für «Jahwe» werden allerdings auch andere Erklärungen versucht, von
denen noch am ehesten zutreffen könnte: Er setzt ins Dasein. Zur
Umschreibung des Gottesnamens Jahwe mit «der Herr» vgl. die Anmerkung zu
Gen 4,26.

[fn:2] Hier und an ähnlichen Stellen, wo der Name Jahwe im
Gespräch mit fremden Völkern gebraucht wird, ist die Umschreibung mit
«der Herr» nicht angebracht, weil die nicht israelitischen Völker den
Gott Israels nicht als Herrn anerkennen und weil sie für ihre Götter
Eigennamen haben.
