#+TITLE: Ex 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-11 Mi 22:13]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ex 7.html

* Ex 7

<<verses>>

<<v1>>
* Die ägyptischen Plagen: 7,1 - 11,10

1 Der Herr sprach zu Mose: Hiermit mache ich dich für den Pharao zum
Gott; dein Bruder Aaron soll dein Prophet sein. [fn:1] [fn:2]

<<v2>>
2 Du sollst alles sagen, was ich dir auftrage; dein Bruder Aaron soll es
dem Pharao sagen und der Pharao muss die Israeliten aus seinem Land
fortziehen lassen.

<<v3>>
3 Ich aber will das Herz des Pharao verhärten und dann werde ich meine
Zeichen und Wunder in Ägypten häufen.

<<v4>>
4 Der Pharao wird nicht auf euch hören. Deshalb werde ich meine Hand auf
Ägypten legen und unter gewaltigem Strafgericht meine Scharen, mein
Volk, die Israeliten, aus Ägypten führen.

<<v5>>
5 Erst wenn ich meine Hand gegen die Ägypter ausstrecke, werden sie
erkennen, dass ich der Herr bin, und dann werde ich die Israeliten aus
ihrer Mitte herausführen.

<<v6>>
6 Mose und Aaron taten, was ihnen der Herr aufgetragen hatte. So machten
sie es.

<<v7>>
7 Mose war achtzig Jahre und Aaron dreiundachtzig Jahre alt, als sie mit
dem Pharao verhandelten.

<<v8>>
8 Der Herr sprach zu Mose und Aaron:

<<v9>>
9 Wenn der Pharao zu euch sagt: Tut doch ein Wunder zu eurer
Beglaubigung!, dann sag zu Aaron: Nimm deinen Stab und wirf ihn vor den
Pharao hin! Er wird zu einer Schlange werden. [fn:3]

<<v10>>
10 Als Mose und Aaron zum Pharao kamen, taten sie, was ihnen der Herr
aufgetragen hatte: Aaron warf seinen Stab vor den Pharao und seine
Diener hin und er wurde zu einer Schlange.

<<v11>>
11 Da rief auch der Pharao Weise und Beschwörungspriester und sie, die
Wahrsager der Ägypter, taten mit Hilfe ihrer Zauberkunst das Gleiche:

<<v12>>
12 Jeder warf seinen Stab hin und die Stäbe wurden zu Schlangen. Doch
Aarons Stab verschlang die Stäbe der Wahrsager.

<<v13>>
13 Das Herz des Pharao aber blieb hart und er hörte nicht auf sie. So
hatte es der Herr vorausgesagt.

<<v14>>
14 Der Herr sprach zu Mose: Das Herz des Pharao ist ungerührt und er ist
nicht bereit, das Volk ziehen zu lassen.

<<v15>>
15 Geh morgen früh zum Pharao, wenn er an den Fluss hinuntergeht, und
tritt am Nilufer vor ihn hin! Den Stab, der sich in eine Schlange
verwandelt hat, nimm mit!

<<v16>>
16 Sag zum Pharao: Jahwe, der Gott der Hebräer, hat mich zu dir gesandt
und lässt dir sagen: Lass mein Volk ziehen, damit sie mich in der Wüste
verehren können. Bis jetzt hast du nicht hören wollen.

<<v17>>
17 So spricht Jahwe: Daran sollst du erkennen, dass ich Jahwe bin: Mit
dem Stab in meiner Hand schlage ich auf das Wasser im Nil und es wird
sich in Blut verwandeln.

<<v18>>
18 Die Fische im Nil werden sterben und der Nil wird stinken, sodass
sich die Ägypter davor ekeln, Nilwasser zu trinken.

<<v19>>
19 Dann sprach der Herr zu Mose: Sag Aaron: Nimm deinen Stab und streck
deine Hand über die Gewässer Ägyptens aus, über ihre Flüsse und Nilarme,
über ihre Sümpfe und alle Wasserstellen; sie sollen zu Blut werden. Blut
soll es geben in ganz Ägypten, in den Gefäßen aus Holz und Stein.

<<v20>>
20 Mose und Aaron taten, was ihnen der Herr aufgetragen hatte. Er erhob
den Stab und schlug vor den Augen des Pharao und seiner Höflinge auf das
Wasser im Nil. Da verwandelte sich alles Nilwasser in Blut.

<<v21>>
21 Die Fische im Nil starben und der Nil stank, sodass die Ägypter kein
Nilwasser mehr trinken konnten. Das Blut gab es in ganz Ägypten.

<<v22>>
22 Doch die Wahrsager der Ägypter taten mit Hilfe ihrer Zauberkunst das
Gleiche. Das Herz des Pharao blieb hart und er hörte nicht auf sie. So
hatte es der Herr vorausgesagt.

<<v23>>
23 Der Pharao kehrte nach Hause zurück und nahm die Sache nicht ernst.

<<v24>>
24 Alle Ägypter gruben in der Umgebung des Nil nach Trinkwasser, denn
das Nilwasser konnten sie nicht trinken.

<<v25>>
25 So vergingen sieben Tage, nachdem der Herr den Nil geschlagen hatte.

<<v26>>
26 Dann sprach der Herr zu Mose: Geh zum Pharao und sag ihm: So spricht
Jahwe: Lass mein Volk ziehen, damit sie mich verehren können.

<<v27>>
27 Weigerst du dich, sie ziehen zu lassen, so bringe ich eine
Froschplage über dein ganzes Land.

<<v28>>
28 Der Nil wird von Fröschen wimmeln; sie werden heraufkommen und in
dein Haus eindringen, in dein Schlafgemach, auf dein Bett werden sie
kommen, in die Häuser deiner Diener und deines Volkes, in deine Backöfen
und Backschüsseln.

<<v29>>
29 Über dich, dein Volk und alle deine Diener werden die Frösche kommen.


* Footnotes

[fn:1] 4,15f

[fn:2] Wie Gott durch einen Propheten zu Menschen redet, so
soll Mose durch seinen Bruder Aaron zum Pharao reden.

[fn:3] 4,1-5
