:PROPERTIES:
:ID:       3a19639c-28e5-4a43-b0f6-370b3b4d1ff2
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_11.html][11]] [[file:Ez_12.html][12]] *13*
[[file:Ez_14.html][14]] [[file:Ez_15.html][15]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 13
  :PROPERTIES:
  :CUSTOM_ID: ez-13
  :END:

<<verses>>

<<v1>>
**** Gegen die falschen Propheten: 13,1-23
     :PROPERTIES:
     :CUSTOM_ID: gegen-die-falschen-propheten-131-23
     :END:
1 Das Wort des Herrn erging an mich:

<<v2>>
2 Menschensohn, sprich als Prophet gegen die Propheten Israels und sag
zu denen, die aus ihrem eigenen Herzen heraus prophetisch reden: Hört
das Wort des Herrn! ^{[[#fn1][1]]}

<<v3>>
3 So spricht Gott, der Herr: Weh den törichten Propheten, die nur ihrem
eigenen Geist folgen und nichts geschaut haben. ^{[[#fn2][2]]}

<<v4>>
4 Wie Füchse in Ruinen sind deine Propheten, Israel. ^{[[#fn3][3]]}

<<v5>>
5 Ihr seid nicht in die Bresche gesprungen. Ihr habt keine Mauer für das
Haus Israel errichtet, damit es am Tag des Herrn im Kampf standhalten
kann. ^{[[#fn4][4]]}

<<v6>>
6 Sie haben nichtige Visionen, verkünden falsche Orakel und sagen:
Spruch des Herrn - obwohl der Herr sie nicht gesandt hat. Trotzdem
warten sie darauf, dass er ihre Worte erfüllt. ^{[[#fn5][5]][[#fn6][6]]}

<<v7>>
7 Ist es nicht so, dass ihr nichtige Visionen gehabt, falsche Orakel
verkündet und gesagt habt: Spruch des Herrn - obwohl ich gar nicht
gesprochen hatte?

<<v8>>
8 Darum - so spricht Gott, der Herr: Weil ihr leere Worte gemacht habt
und trügerische Visionen hattet, darum gehe ich gegen euch vor Spruch
Gottes, des Herrn.

<<v9>>
9 Ich strecke meine Hand gegen die Propheten aus, die nichtige Visionen
haben und falsche Orakel verkünden. Sie gehören nicht in die
Gemeinschaft meines Volkes und sollen nicht in der Liste des Hauses
Israel verzeichnet sein; sie werden nicht in das Land Israel kommen.
Dann werdet ihr erkennen, dass ich Gott, der Herr, bin. ^{[[#fn7][7]]}

<<v10>>
10 Sie führen mein Volk in die Irre und verkünden Heil, wo es kein Heil
gibt, und wenn das Volk eine Mauer aufrichtet, dann übertünchen sie sie.
^{[[#fn8][8]]}

<<v11>>
11 Deshalb sag denen, die sie übertünchen: Sie wird einstürzen. Es kommt
ein Wolkenbruch, Hagel fällt wie Steine vom Himmel, ein Sturm bricht los
^{[[#fn9][9]]}

<<v12>>
12 und schon stürzt die Mauer ein. Wird man dann nicht zu euch sagen: Wo
ist jetzt eure Tünche?

<<v13>>
13 Darum - so spricht Gott, der Herr: Ich lasse in meinem Zorn einen
Sturm losbrechen, in meinem Groll schicke ich einen Wolkenbruch, in
meinem Zorn einen verheerenden Hagelschlag. ^{[[#fn10][10]]}

<<v14>>
14 Ich reiße die Wand ein, die ihr übertüncht habt, ich lasse sie zu
Boden stürzen und ihr Fundament wird bloßgelegt. Und wenn sie einstürzt,
werdet ihr in ihren Trümmern umkommen. Dann werdet ihr erkennen, dass
ich der Herr bin. ^{[[#fn11][11]]}

<<v15>>
15 Ich lasse meinen Zorn an der Mauer aus und an denen, die sie
übertüncht haben, und ich sage euch: Die Mauer ist weg und weg sind die,
die sie übertüncht haben,

<<v16>>
16 die Propheten Israels, die über Jerusalem prophezeien und der Stadt
mit ihren Visionen Heil versprechen, obwohl es kein Heil gibt - Spruch
Gottes, des Herrn.

<<v17>>
17 Du, Menschensohn, richte dein Gesicht auf die Töchter deines Volkes,
die aus ihrem eigenen Herzen heraus prophetisch reden. Sprich als
Prophet gegen sie!

<<v18>>
18 Sag: So spricht Gott, der Herr: Weh den Frauen, die Zauberbinden für
alle Handgelenke nähen und Zaubermützen für Leute jeder Größe
anfertigen, um damit auf Menschenjagd zu gehen. Meint ihr, ihr könnt in
meinem Volk Menschen jagen und Menschen verschonen, je nachdem, wie es
euch passt? ^{[[#fn12][12]]}

<<v19>>
19 Ihr habt mich entweiht in meinem Volk für ein paar Hände voll Gerste
und für ein paar Bissen Brot: Ihr habt Menschen getötet, die nicht
sterben sollten, und Menschen verschont, die nicht am Leben bleiben
sollten; ihr habt mein Volk belogen, das so gern auf Lügen hört.
^{[[#fn13][13]]}

<<v20>>
20 Darum - so spricht Gott, der Herr: Ich gehe gegen eure Zauberbinden
vor, mit denen ihr die Menschen jagt wie Vögel, und reiße sie von euren
Armen und lasse die Menschen frei, die ihr gefangen habt wie Vögel.

<<v21>>
21 Ich reiße die Zaubermützen, die ihr gemacht habt, herunter und
befreie mein Volk aus eurer Gewalt. Es wird nicht länger in eurer Gewalt
bleiben. Dann werdet ihr erkennen, dass ich der Herr bin.

<<v22>>
22 Ihr habt dem Herzen des Gerechten durch eure Lügen Kummer bereitet;
ich aber wollte ihm keinen Kummer bereiten. Statt das Leben des Bösen zu
retten, habt ihr ihn ermutigt, sein verkehrtes Verhalten nicht zu
ändern. ^{[[#fn14][14]][[#fn15][15]]}

<<v23>>
23 Darum sollt ihr keine nichtigen Visionen mehr haben und keine Orakel
mehr verkünden. Ich werde mein Volk aus eurer Gewalt befreien. Dann
werdet ihr erkennen, dass ich der Herr bin.\\
\\

^{[[#fnm1][1]]} Text korr. nach G.

^{[[#fnm2][2]]} ℘ Jer 14,14

^{[[#fnm3][3]]} 4f: Statt auf das Fehlverhalten des Volkes aufmerksam zu
machen, haben die falschen Propheten das Volk in seinem Verhalten
bestärkt.

^{[[#fnm4][4]]} ℘ 22,30

^{[[#fnm5][5]]} ℘ 22,28

^{[[#fnm6][6]]} verkünden . . . Orakel: Text korr.; vgl. G.

^{[[#fnm7][7]]} ℘ 14,9

^{[[#fnm8][8]]} ℘ Jer 6,14

^{[[#fnm9][9]]} Text korr.

^{[[#fnm10][10]]} schicke ich einen, wörtlich: wird es sein, ein. . .

^{[[#fnm11][11]]} in ihren Trümmern, wörtlich: mitten in ihr.

^{[[#fnm12][12]]} für alle Handgelenke: Text korr.; vgl. die alten
Übersetzungen. - Die Frauen üben magische Zauberhandlungen aus, mit
denen sie unheilvolle Kräfte an die Menschen binden oder von ihnen
fernhalten wollen.

^{[[#fnm13][13]]} ℘ 1 Sam 9,7

^{[[#fnm14][14]]} ℘ Jer 23,14

^{[[#fnm15][15]]} Ihr habt. . . Kummer bereitet: Text korr.; vgl. den
zweiten Satz.
