:PROPERTIES:
:ID:       1807900d-54a1-469c-953c-f76c0269ea1b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_12.html][12]] [[file:Ez_13.html][13]] *14*
[[file:Ez_15.html][15]] [[file:Ez_16.html][16]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 14
  :PROPERTIES:
  :CUSTOM_ID: ez-14
  :END:

<<verses>>

<<v1>>
**** Gegen die Götzendiener: 14,1-11
     :PROPERTIES:
     :CUSTOM_ID: gegen-die-götzendiener-141-11
     :END:
1 Einige von den Ältesten Israels kamen zu mir und setzten sich vor mir
nieder. ^{[[#fn1][1]]}

<<v2>>
2 Da erging das Wort des Herrn an mich:

<<v3>>
3 Menschensohn, diese Männer haben die Götzen in ihr Herz geschlossen,
sie haben sie vor sich aufgestellt; das wurde für sie der Anlass, in
Schuld zu fallen. Und jetzt soll ich mich von ihnen befragen lassen?

<<v4>>
4 Darum sprich mit ihnen und sag zu ihnen: Wenn jemand aus dem Haus
Israel die Götzen in sein Herz geschlossen und sie vor sich aufgestellt
hat - was für ihn der Anlass geworden ist, in Schuld zu fallen - und
wenn er dann zum Propheten kommt, dann werde ich, der Herr, dem, der mit
seinen vielen Götzen zu mir kommt, in eigener Person antworten:
^{[[#fn2][2]]}

<<v5>>
5 Ich werde das Haus Israel hart anfassen, weil sie alle sich um ihrer
Götzen willen von mir abgewandt haben. ^{[[#fn3][3]]}

<<v6>>
6 Darum sag zum Haus Israel: So spricht Gott, der Herr: Kehrt um!
Verlasst eure Götzen und wendet eure Augen ab von all euren
abscheulichen Göttern!

<<v7>>
7 Wenn jemand aus dem Haus Israel oder aus den in Israel lebenden
Fremden sich von mir abwendet, wenn er die Götzen in sein Herz schließt
und sie vor sich aufstellt - was für ihn der Anlass wird, in Schuld zu
fallen - und wenn er dann zum Propheten kommt, um mich zu befragen, dann
werde ich, der Herr, ihm in eigener Person antworten:

<<v8>>
8 Ich richte meinen Blick gegen diesen Mann und mache ihn zum
sprichwörtlichen (warnenden) Zeichen, ich merze ihn aus meinem Volk aus.
Dann werdet ihr erkennen, dass ich der Herr bin.

<<v9>>
9 Wenn der Prophet sich jedoch dazu verleiten lässt, etwas zu sagen,
dann habe ich, der Herr, diesen Propheten verleitet und ich werde meine
Hand gegen ihn ausstrecken und ihn mitten in meinem Volk Israel
vernichten. ^{[[#fn4][4]]}

<<v10>>
10 Sie werden beide die Folgen ihrer Schuld tragen müssen; denn die
Schuld dessen, der mich befragt, und die Schuld des Propheten sind
gleich.

<<v11>>
11 Dann wird sich das Haus Israel nicht mehr davon abbringen lassen, mir
zu folgen, und wird sich nicht länger durch all seine Sünden unrein
machen. Sie werden mein Volk sein und ich werde ihr Gott sein - Spruch
Gottes, des Herrn.\\
\\

<<v12>>
**** Das unerbittliche Gericht Gottes: 14,12-23
     :PROPERTIES:
     :CUSTOM_ID: das-unerbittliche-gericht-gottes-1412-23
     :END:
12 Das Wort des Herrn erging an mich: ^{[[#fn5][5]]}

<<v13>>
13 Menschensohn, wenn sich ein Land gegen mich versündigt und mir die
Treue bricht und wenn ich dann meine Hand gegen das Land ausstrecke, ihm
seinen Vorrat an Brot entziehe, den Hunger ins Land schicke und Mensch
und Tier ausrotte ^{[[#fn6][6]]}

<<v14>>
14 und wenn in diesem Land die drei Männer Noach, Daniel und Ijob leben
würden, dann würden nur diese drei um ihrer Gerechtigkeit willen ihr
Leben retten - Spruch Gottes, des Herrn. ^{[[#fn7][7]]}

<<v15>>
15 Oder wenn ich wilde Tiere gegen das Land losließe, die es entvölkern,
sodass es zur Wüste würde und wegen der wilden Tiere kein Mensch mehr
durch das Land reisen könnte, ^{[[#fn8][8]]}

<<v16>>
16 und wenn diese drei Männer darin wären - so wahr ich lebe, Spruch
Gottes, des Herrn: sie würden nicht einmal ihre eigenen Söhne und
Töchter retten. Nur sie selbst könnten sich retten, das Land aber würde
zur Wüste werden.

<<v17>>
17 Oder wenn ich das Schwert über dieses Land bringen und sagen würde:
Ein Schwert soll durch das Land fahren, ich will Mensch und Tier darin
ausrotten!,

<<v18>>
18 und wenn diese drei Männer darin wären - so wahr ich lebe, Spruch
Gottes, des Herrn: sie würden nicht einmal ihre eigenen Söhne und
Töchter retten. Nur sie selbst könnten sich retten.

<<v19>>
19 Oder wenn ich die Pest in jenes Land schicken und meinen Zorn darüber
ausgießen würde, um Mensch und Tier in einem Blutbad zu vernichten,

<<v20>>
20 und wenn Noach, Daniel und Ijob in dem Land wären - so wahr ich lebe,
Spruch Gottes, des Herrn: nicht einmal ihren Sohn und ihre Tochter
würden sie retten. Sie würden nur ihr eigenes Leben retten, um ihrer
Gerechtigkeit willen.

<<v21>>
21 Wahrhaftig, so spricht Gott, der Herr: Selbst wenn ich die vier
schlimmsten Strafen, Schwert, Hunger, wilde Tiere und Pest, über
Jerusalem bringe, um Mensch und Tier auszurotten, ^{[[#fn9][9]]}

<<v22>>
22 werden einige in der Stadt verschont werden und übrig bleiben und
ihre Söhne und Töchter zu euch herausführen. Wenn ihr dann ihr Verhalten
und ihre Taten seht, werdet ihr euch über das Unheil hinwegtrösten, das
ich über Jerusalem verhängt habe, über alles, was ich über die Stadt
kommen ließ.

<<v23>>
23 Sie trösten euch darüber hinweg, weil ihr ihr Verhalten und ihre
Taten seht und daran erkennt, dass ich all das, was ich mit der Stadt
machte, nicht ohne Grund getan habe - Spruch Gottes, des Herrn.\\
\\

^{[[#fnm1][1]]} ℘ 8,1; 20,1

^{[[#fnm2][2]]} in eigener Person: Text korr. nach V. 7.

^{[[#fnm3][3]]} hart anfassen, wörtlich: an seinem Herzen packen.

^{[[#fnm4][4]]} ℘ 1 Kön 22,20-23; Ez 13,9

^{[[#fnm5][5]]} ℘ (12-23) 18; 33,10-20

^{[[#fnm6][6]]} ℘ 4,16

^{[[#fnm7][7]]} Noach (Gen 6,9; 7,1), Daniel (in ugaritischen Texten ein
gerechter Herrscher, kaum identisch mit dem biblischen Daniel) und Ijob
(Ijob 1,1 - 2,10) gelten als beispielhaft gerecht.

^{[[#fnm8][8]]} ℘ Lev 26,22

^{[[#fnm9][9]]} ℘ 5,17; Lev 26,16-25; Jer 15,3; Offb 6,8
