:PROPERTIES:
:ID:       ddbe976e-b48f-4599-9534-364422ae99b0
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_19.html][19]] [[file:Ez_20.html][20]] *21*
[[file:Ez_22.html][22]] [[file:Ez_23.html][23]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 21
  :PROPERTIES:
  :CUSTOM_ID: ez-21
  :END:

<<verses>>

<<v1>>
**** Das Gleichnis vom Waldbrand: 21,1-5
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-waldbrand-211-5
     :END:
1 Das Wort des Herrn erging an mich:

<<v2>>
2 Menschensohn, richte dein Gesicht nach Süden, weissage gegen das
Südland, tritt als Prophet auf gegen den Wald im Süden

<<v3>>
3 und sag zum Wald des Südlands: Höre das Wort des Herrn: So spricht
Gott, der Herr: Ich will Feuer an dich legen, jeden grünen Baum und
jeden dürren Baum in dir wird es verzehren. Seine lodernde Flamme wird
nicht erlöschen. Alle Gesichter sollen von ihr versengt werden, vom
Süden bis zum Norden. ^{[[#fn1][1]][[#fn2][2]]}

<<v4>>
4 Dann wird jeder Sterbliche sehen, dass ich, der Herr, das Feuer
entfacht habe. Und es wird nicht erlöschen.

<<v5>>
5 Da sagte ich: Ach, Herr und Gott, sie sagen über mich: Er redet ja
immer nur in Gleichnissen.\\
\\

<<v6>>
**** Das Lied vom Schwert des Herrn: 21,6-22
     :PROPERTIES:
     :CUSTOM_ID: das-lied-vom-schwert-des-herrn-216-22
     :END:
6 Das Wort des Herrn erging an mich:

<<v7>>
7 Menschensohn, richte dein Gesicht gegen Jerusalem, weissage gegen sein
Heiligtum, tritt als Prophet auf gegen das Land Israel

<<v8>>
8 und sag zu ihm: So spricht Gott, der Herr: Nun gehe ich gegen dich
vor. Ich ziehe mein Schwert aus der Scheide und rotte bei dir die
Gerechten ebenso wie die Schuldigen aus.

<<v9>>
9 Weil ich bei dir die Gerechten und die Schuldigen ausrotten will,
deshalb wird mein Schwert aus seiner Scheide fahren, gegen jeden
Sterblichen vom Süden bis zum Norden.

<<v10>>
10 Dann werden alle Sterblichen erkennen, dass ich, der Herr, mein
Schwert aus der Scheide gezogen habe. Es wird nicht mehr in die Scheide
zurückkehren.

<<v11>>
11 Du, Menschensohn, stöhne: Stöhne mit gebrochenen Hüften und in
bitterem Schmerz vor ihren Augen.

<<v12>>
12 Wenn sie dann zu dir sagen: Warum stöhnst du?, antworte: Weil eine
Nachricht kommt, bei der jedes Herz verzagt, alle Hände kraftlos
heruntersinken, bei der jeder Atem stockt und an allen Knien das Wasser
herabläuft. Seht, es kommt und geschieht - Spruch Gottes, des Herrn.
^{[[#fn3][3]]}

<<v13>>
13 Das Wort des Herrn erging an mich:\\
\\

<<v14>>
14 Menschensohn, tritt als Prophet auf und sag: So spricht Gott, der
Herr: Sag: Ein Schwert, ein Schwert, /\\
 geschärft und poliert.\\
\\

<<v15>>
15 Zum Schlachten, zum Schlachten ist es geschärft; /\\
 um wie ein Blitz zu leuchten, ist es poliert. [Oder sollen wir uns
freuen? /\\
 Der Stock meines Sohnes verachtet jedes andere Holz.] ^{[[#fn4][4]]}\\
\\

<<v16>>
16 Man gab es zum Polieren, dann packt es die Faust, /\\
 ein Schwert, geschärft und poliert /\\
 für des Henkers Hand.\\
\\

<<v17>>
17 Schrei und heule, Menschensohn! /\\
 Denn es richtet sich gegen mein Volk, /\\
 gegen alle Fürsten von Israel. Dem Schwert sind sie verfallen, /\\
 sie und mein Volk. Darum schlag auf die Hüfte! /\\
\\

<<v18>>
18 Denn es wurde erprobt. [Doch was wird, wenn auch der verachtende
Stock nicht mehr ist?] - /\\
 Spruch Gottes, des Herrn.\\
\\

<<v19>>
19 Du, Menschensohn, sprich als Prophet /\\
 und schlag die Hände zusammen! Verdoppelt wird das Schwert, ja
verdreifacht. /\\
 Ein Schwert zum Morden ist es, zum Morden, /\\
 das gewaltige Schwert, das sie durchbohrt.\\
\\

<<v20>>
20 Das Herz soll verzagen und viele sollen straucheln. /\\
 An all ihren Toren habe ich dem Schwert zu schlachten befohlen. Ja, zum
Blitzen bist du gemacht, /\\
 zum Schlachten poliert. ^{[[#fn5][5]]}\\
\\

<<v21>>
21 Zeig, dass du scharf bist! /\\
 Zucke nach rechts und nach links, /\\
 wohin deine Schneide gelenkt wird. ^{[[#fn6][6]]}\\
\\

<<v22>>
22 Auch ich schlage die Hände zusammen; /\\
 meinen Zorn will ich stillen. - /\\
 Ich, der Herr, habe gesprochen.\\
\\

<<v23>>
**** Eine weitere symbolische Handlung: Das Schwert des Königs von
Babel: 21,23-37
     :PROPERTIES:
     :CUSTOM_ID: eine-weitere-symbolische-handlung-das-schwert-des-königs-von-babel-2123-37
     :END:
23 Das Wort des Herrn erging an mich:

<<v24>>
24 Du, Menschensohn, mach dir zwei Wege, auf denen das Schwert des
Königs von Babel kommt. Sie sollen beide vom gleichen Land ausgehen. Am
Anfang der beiden Wege stell einen Wegweiser zu je einer Stadt auf!

<<v25>>
25 Gib die Richtung an, die das Schwert einschlagen kann: entweder
Rabbat-Ammon oder Juda mit dem befestigten Jerusalem.

<<v26>>
26 Denn der König von Babel steht an der Wegscheide, am Anfang der zwei
Wege, und lässt das Orakel entscheiden: Er schüttelt die Pfeile, befragt
die Götterbilder und hält Leberschau.

<<v27>>
27 In seiner rechten Hand hält er den Entscheid des Orakels: Jerusalem.
Jetzt wird er die Sturmböcke aufstellen, das Kampflied anstimmen, das
Kriegsgeschrei erheben, die Sturmböcke auf die Tore richten, einen Damm
aufschütten und Belagerungstürme bauen. ^{[[#fn7][7]]}

<<v28>>
28 Doch in den Augen der Leute (von Jerusalem) ist das Orakel
bedeutungslos. Für sie galten heilige Eide, darum wird er (der König von
Babel) sie an ihre Schuld erinnern und sie packen.

<<v29>>
29 Darum - so spricht Gott, der Herr: Ihr habt selbst an eure Schuld
erinnert - eure Vergehen liegen offen zutage, eure Sünden sind samt all
euren Untaten ans Licht gekommen -, und weil ihr überführt seid, wird
man euch mit Gewalt packen.

<<v30>>
30 Du entweihter, verbrecherischer Fürst von Israel, für den der Tag
gekommen ist, die Zeit der endgültigen Abrechnung!

<<v31>>
31 So spricht Gott, der Herr: Weg mit dem Turban, herunter mit der
Krone! Nichts soll bleiben, wie es ist. Das Niedrige wird hoch, das Hohe
wird niedrig. ^{[[#fn8][8]]}

<<v32>>
32 Zu Trümmern, Trümmern, Trümmern mache ich die Stadt. [Auch dies
geschieht nicht, bis der kommt, der auf sie ein Anrecht hat und dem ich
sie geben will.] ^{[[#fn9][9]]}

<<v33>>
33 Du aber, Menschensohn, sprich als Prophet und sag: So spricht Gott,
der Herr, über die Ammoniter und ihr Hohngelächter. Du sollst sagen:
Schwert, Schwert, gezückt zum Schlachten, poliert, um ganze Arbeit zu
tun, um wie ein Blitz einzuschlagen.

<<v34>>
34 Während sie noch für dich leere Visionen haben und dir falsche Orakel
verkünden, ist den todgeweihten Verbrechern das Schwert schon an den
Hals gelegt; jetzt ist für sie der Tag gekommen, die Zeit der
endgültigen Abrechnung.

<<v35>>
35 Steck das Schwert in die Scheide! An dem Ort, wo du erschaffen
wurdest, im Land deiner Herkunft will ich dich richten.

<<v36>>
36 Ich gieße meinen Groll über dich aus, das Feuer meines Zorns will ich
gegen dich entfachen. Ich liefere dich grausamen Menschen aus, die ihr
mörderisches Handwerk verstehen.

<<v37>>
37 Das Feuer soll dich verzehren. Mitten im Land soll dein Blut fließen.
An dich wird sich niemand erinnern. Denn ich, der Herr, habe
gesprochen.\\
\\

^{[[#fnm1][1]]} ℘ Jer 21,14

^{[[#fnm2][2]]} Das Bild vom Wald im Südland meint Juda und Jerusalem.

^{[[#fnm3][3]]} ℘ 7,17

^{[[#fnm4][4]]} 15.18: Text des Zusatzes verderbt und unverständlich.

^{[[#fnm5][5]]} Text unsicher.

^{[[#fnm6][6]]} Zeig, dass du scharf bist: Text korr.; vgl. G.

^{[[#fnm7][7]]} das Kampflied anstimmen: Text korr. nach G; H ist
unklar.

^{[[#fnm8][8]]} ℘ Jes 40,4

^{[[#fnm9][9]]} Sinn des Zusatzes unklar. Im Blick auf V. 31, dritter
Satz, könnte an eine messianische Zukunft gedacht sein (vgl. Gen 49,10).
