:PROPERTIES:
:ID:       8ec2c67c-04a5-462f-b75f-2bb0648552f0
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_18.html][18]] [[file:Ez_19.html][19]] *20*
[[file:Ez_21.html][21]] [[file:Ez_22.html][22]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 20
  :PROPERTIES:
  :CUSTOM_ID: ez-20
  :END:

<<verses>>

<<v1>>
**** Die zahlreichen Treulosigkeiten Israels: 20,1-44
     :PROPERTIES:
     :CUSTOM_ID: die-zahlreichen-treulosigkeiten-israels-201-44
     :END:
1 Im fünften Monat des siebten Jahres kamen am zehnten Tag des Monats
einige von den Ältesten Israels, um den Herrn zu befragen. Sie setzten
sich vor mir nieder. ^{[[#fn1][1]]}

<<v2>>
2 Da erging das Wort des Herrn an mich:

<<v3>>
3 Menschensohn, rede mit den Ältesten Israels und sag zu ihnen: So
spricht Gott, der Herr: Seid ihr gekommen, um mich zu befragen? So wahr
ich lebe, ich lasse mich von euch nicht befragen - Spruch Gottes, des
Herrn.

<<v4>>
4 Willst du nicht über sie Gericht halten, Menschensohn, willst nicht du
Gericht halten? Mach ihnen die Gräueltaten ihrer Väter bewusst
^{[[#fn2][2]]}

<<v5>>
5 und sag zu ihnen: So spricht Gott, der Herr: An dem Tag, als ich
Israel erwählt habe, erhob ich meine Hand, (um) den Nachkommen des
Hauses Jakob (einen Eid zu leisten). Ich offenbarte mich ihnen in
Ägypten. Ich erhob meine Hand (zum Schwur) und sprach: Ich bin der Herr,
euer Gott. ^{[[#fn3][3]]}

<<v6>>
6 An jenem Tag erhob ich meine Hand (zum Schwur), dass ich sie aus
Ägypten herausführe in ein Land, das ich für sie erkundete, in dem Milch
und Honig fließen, ein Schmuckstück unter allen Ländern. ^{[[#fn4][4]]}

<<v7>>
7 Und ich sagte zu ihnen: Ihr alle, werft die Götzen weg, an denen eure
Augen hängen. Macht euch nicht unrein durch die Gräueltaten Ägyptens!
Ich bin der Herr, euer Gott. ^{[[#fn5][5]]}

<<v8>>
8 Sie aber widersetzten sich mir und wollten nicht auf mich hören.
Keiner warf die Götzen weg, an denen seine Augen hingen, und sie sagten
sich nicht los von den Götzen Ägyptens. Da sagte ich: Ich will meinen
Zorn über sie ausgießen und meinen Grimm an ihnen auslassen, mitten in
Ägypten.

<<v9>>
9 Aber dann handelte ich um meines Namens willen anders; ich wollte ihn
nicht entweihen vor den Augen der Völker, in deren Mitte sie lebten und
vor deren Augen ich mich ihnen offenbarte, als ich sie aus Ägypten
herausführte. ^{[[#fn6][6]]}

<<v10>>
10 Ich führte sie aus Ägypten heraus, brachte sie in die Wüste

<<v11>>
11 und gab ihnen meine Gesetze. Ich gab ihnen meine Rechtsvorschriften
bekannt, die der Mensch befolgen muss, damit er durch sie am Leben
bleibt. ^{[[#fn7][7]]}

<<v12>>
12 Auch meine Sabbat-Tage gab ich ihnen zum Zeichen (des Bundes)
zwischen mir und ihnen. Daran sollte man erkennen, dass ich, der Herr,
Israel heilige. ^{[[#fn8][8]]}

<<v13>>
13 Aber das Haus Israel widersetzte sich mir in der Wüste. Sie lebten
nicht nach meinen Gesetzen und wiesen meine Rechtsvorschriften zurück,
die der Mensch befolgen muss, damit er durch sie am Leben bleibt. Auch
meine Sabbat-Tage entweihten sie völlig. Da sagte ich: Ich will in der
Wüste über sie meinen Zorn ausgießen und sie vernichten. ^{[[#fn9][9]]}

<<v14>>
14 Aber ich handelte anders um meines Namens willen; ich wollte ihn
nicht entweihen vor den Völkern, vor deren Augen ich sie (aus Ägypten)
herausgeführt hatte. ^{[[#fn10][10]]}

<<v15>>
15 Doch in der Wüste erhob ich meine Hand (zum Schwur), dass ich sie
nicht in das Land bringe, das ich für sie bestimmt hatte, in das Land,
wo Milch und Honig fließen, das Schmuckstück unter allen Ländern.
^{[[#fn11][11]][[#fn12][12]]}

<<v16>>
16 Denn sie wiesen meine Rechtsvorschriften zurück, sie lebten nicht
nach meinen Gesetzen und entweihten meine Sabbat-Tage, weil ihr Herz
hinter den Götzen her war.

<<v17>>
17 Aber mein Auge zeigte Mitleid mit ihnen: Ich rottete sie nicht völlig
aus in der Wüste.

<<v18>>
18 Zu ihren Söhnen sagte ich in der Wüste: Lebt nicht nach den Gesetzen
eurer Väter, achtet nicht auf ihre Rechtsvorschriften und macht euch
nicht unrein an ihren Götzen!

<<v19>>
19 Ich bin der Herr, euer Gott. Lebt nach meinen Gesetzen, achtet auf
meine Rechtsvorschriften und befolgt sie!

<<v20>>
20 Haltet meine Sabbat-Tage heilig; sie sollen das Zeichen (des Bundes)
zwischen mir und euch sein. Daran wird man erkennen, dass ich, der Herr,
euer Gott bin.

<<v21>>
21 Aber die Söhne widersetzten sich mir. Sie lebten nicht nach meinen
Gesetzen und sie beachteten und befolgten meine Rechtsvorschriften
nicht, die der Mensch befolgen muss, damit er durch sie am Leben bleibt.
Meine Sabbat-Tage entweihten sie. Da sagte ich: Ich werde in der Wüste
meinen Zorn über sie ausgießen und meinen Grimm an ihnen auslassen.

<<v22>>
22 Aber ich zog meine Hand zurück und handelte anders, um meines Namens
willen; ich wollte ihn nicht vor all den Völkern entweihen, vor deren
Augen ich sie (aus Ägypten) herausgeführt hatte. ^{[[#fn13][13]]}

<<v23>>
23 Doch ich erhob in der Wüste meine Hand (zum Schwur), dass ich sie
unter die Völker zerstreuen und in alle Länder vertreiben werde,

<<v24>>
24 weil sie meine Rechtsvorschriften nicht befolgten, meine Gesetze
ablehnten und meine Sabbat-Tage entweihten und weil ihre Augen hinter
den Götzen ihrer Väter her waren.

<<v25>>
25 Auch gab ich ihnen Gesetze, die nicht gut waren, und
Rechtsvorschriften, die es ihnen unmöglich machten, am Leben zu bleiben.
^{[[#fn14][14]]}

<<v26>>
26 Ich machte sie unrein durch ihre Opfergaben; sie ließen nämlich alle
Erstgeborenen durch das Feuer gehen. Ich wollte ihnen Entsetzen
einjagen; denn sie sollten erkennen, dass ich der Herr bin.
^{[[#fn15][15]]}

<<v27>>
27 Darum sprich zum Haus Israel, Menschensohn, und sag zu ihnen: So
spricht Gott, der Herr: Eure Väter haben mich auch dadurch verhöhnt,
dass sie mir untreu wurden.

<<v28>>
28 Als ich sie in das Land gebracht hatte - ich hatte ja meine Hand
erhoben (und geschworen), es ihnen zu geben -, schlachteten sie, sobald
sie irgendeinen hohen Hügel und einen dichtbelaubten Baum sahen, dort
ihre Opfer; dort brachten sie ihre ärgerlichen Gaben dar, legten ihre
duftenden Spenden nieder, um mich zu beruhigen, und gossen dort ihre
Trankopfer aus. ^{[[#fn16][16]]}

<<v29>>
29 Da sagte ich zu ihnen: Was ist das schon, die Höhe, zu der ihr
kommt? - Deshalb wird ein solcher Platz bis zum heutigen Tag Kulthöhe
genannt. ^{[[#fn17][17]]}

<<v30>>
30 Darum sag zum Haus Israel: So spricht Gott, der Herr: Wie schon eure
Väter, so macht auch ihr euch unrein und lauft in eurer Untreue ihren
Götzen nach.

<<v31>>
31 Wenn ihr eure Gaben darbringt, eure Söhne durch das Feuer gehen
lasst, wenn ihr euch bis zum heutigen Tag immer wieder unrein macht mit
all euren Götzen, soll ich mich dann von euch befragen lassen, ihr vom
Haus Israel? So wahr ich lebe - Spruch Gottes, des Herrn -, ich lasse
mich von euch nicht befragen.

<<v32>>
32 Niemals soll geschehen, was euch eingefallen ist, als ihr sagtet: Wir
wollen wie die anderen Völker sein, wie die Völkerstämme in anderen
Ländern, und wollen Holz und Stein verehren. ^{[[#fn18][18]]}

<<v33>>
33 So wahr ich lebe - Spruch Gottes, des Herrn: Ich will mit starker
Hand und hoch erhobenem Arm über euch als König herrschen und dabei
meinen Zorn über euch ausgießen. ^{[[#fn19][19]]}

<<v34>>
34 Ich will euch mit starker Hand und hoch erhobenem Arm aus den Völkern
herausführen und aus den Ländern, in die ihr zerstreut seid, sammeln und
dabei meinen Zorn über euch ausgießen.

<<v35>>
35 Ich bringe euch in die Wüste der Völker; dort trete ich euch von
Angesicht zu Angesicht als Richter gegenüber. ^{[[#fn20][20]]}

<<v36>>
36 Wie ich mit euren Vätern in der Wüste Ägyptens ins Gericht gegangen
bin, so will ich auch mit euch ins Gericht gehen - Spruch Gottes, des
Herrn.

<<v37>>
37 Ich lasse euch unter dem Hirtenstab an mir vorbeiziehen und zähle
euch ab. ^{[[#fn21][21]][[#fn22][22]]}

<<v38>>
38 Die Abtrünnigen und alle, die sich gegen mich auflehnten, sondere ich
von euch ab. Ich führe sie zwar aus dem Land, in dem sie als Fremde
leben, heraus, in das Land Israel aber werden sie nicht kommen; dann
werdet ihr erkennen, dass ich der Herr bin. ^{[[#fn23][23]]}

<<v39>>
39 Ihr aber vom Haus Israel - so spricht Gott, der Herr -, geht doch
alle und dient euren Götzen! Doch später werdet ihr auf mich hören und
meinen heiligen Namen nicht mehr mit euren Opfergaben und mit euren
Götzen entweihen. ^{[[#fn24][24]]}

<<v40>>
40 Denn auf meinem heiligen Berg, auf dem hohen Berg Israels - Spruch
Gottes, des Herrn -, dort im Land wird mir das ganze Haus Israel dienen.
Dort will ich sie gnädig annehmen und dort fordere ich eure Abgaben und
Erstlingsopfer mit all euren heiligen Gaben.

<<v41>>
41 Beim beruhigenden Duft eurer Opfer will ich euch gnädig annehmen.
Wenn ich euch aus den Völkern herausführe und aus den Ländern sammle, in
die ihr zerstreut seid, werde ich mich vor den Augen der Völker an euch
als heilig erweisen.

<<v42>>
42 Ihr sollt erkennen, dass ich der Herr bin, wenn ich euch in das Land
Israel bringe; denn ich habe meine Hand erhoben (zum Schwur), dieses
Land euren Vätern zu geben.

<<v43>>
43 Dort werdet ihr euch an euer Verhalten und an all eure Taten
erinnern, durch die ihr euch unrein gemacht habt, und es wird euch ekeln
vor euch selbst wegen all der bösen Taten, die ihr begangen habt.
^{[[#fn25][25]]}

<<v44>>
44 Ihr werdet erkennen, dass ich der Herr bin, wenn ich um meines Namens
willen so an euch handle und nicht nach eurem verkehrten Verhalten und
nach euren verwerflichen Taten, ihr vom Haus Israel - Spruch Gottes, des
Herrn. ^{[[#fn26][26]]}\\
\\

^{[[#fnm1][1]]} ℘ 8,1; 14,1.3

^{[[#fnm2][2]]} ℘ 22,2; 23,36; 16,2

^{[[#fnm3][3]]} ℘ Dtn 7,6

^{[[#fnm4][4]]} ℘ Ex 3,8

^{[[#fnm5][5]]} ℘ Jos 24,14.23

^{[[#fnm6][6]]} ℘ 20,14; 36,21f

^{[[#fnm7][7]]} ℘ Lev 18,5

^{[[#fnm8][8]]} ℘ Ex 31,13-17

^{[[#fnm9][9]]} ℘ Ex 14,11

^{[[#fnm10][10]]} ℘ 20,9; Ex 32,11f

^{[[#fnm11][11]]} ℘ Num 14,28-30; Ps 95,11

^{[[#fnm12][12]]} für sie: ergänzt nach den alten Übersetzungen und
H-Handschriften.

^{[[#fnm13][13]]} ℘ 20,14

^{[[#fnm14][14]]} Nach V. 26 denkt Ezechiel hier an das Gesetz über die
Erstgeburtsopfer. In Notzeiten brachte man die erstgeborenen Kinder als
Opfer dar, obwohl nach Ex 34,19f die menschliche Erstgeburt durch ein
Tier auszulösen ist.

^{[[#fnm15][15]]} ℘ Lev 18,21

^{[[#fnm16][16]]} ℘ 6,13; Dtn 12,2

^{[[#fnm17][17]]} die Höhe, hebräisch bamáh, sonst mit «Kulthöhe»
übersetzt. In H Wortspiel mit bamáh, aus dem man auch die Wörter für
«was» und «kommen» heraushören konnte.

^{[[#fnm18][18]]} ℘ 1 Sam 8,5

^{[[#fnm19][19]]} ℘ Jer 21,5

^{[[#fnm20][20]]} ℘ Hos 2,16; Num 14,22-38

^{[[#fnm21][21]]} ℘ Lev 27,32; Jer 33,13

^{[[#fnm22][22]]} und zähle euch ab: Text korr.; vgl. G; der Text ist
unklar.

^{[[#fnm23][23]]} Der letzte Satz korr. nach den alten Übersetzungen und
einigen hebräischen Handschriften.

^{[[#fnm24][24]]} werdet ihr auf mich hören: Text korr.; H: werdet ihr
nicht auf mich hören.

^{[[#fnm25][25]]} ℘ 36,31f

^{[[#fnm26][26]]} ℘ 20,14
