:PROPERTIES:
:ID:       6b1095e9-55e5-49eb-99d9-74812d3e5b7e
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_22.html][22]] [[file:Ez_23.html][23]] *24*
[[file:Ez_25.html][25]] [[file:Ez_26.html][26]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 24
  :PROPERTIES:
  :CUSTOM_ID: ez-24
  :END:

<<verses>>

<<v1>>
** Weitere symbolische Handlungen: 24,1-27
   :PROPERTIES:
   :CUSTOM_ID: weitere-symbolische-handlungen-241-27
   :END:
**** Die vergebliche Reinigung der Stadt: 24,1-14
     :PROPERTIES:
     :CUSTOM_ID: die-vergebliche-reinigung-der-stadt-241-14
     :END:
1 Am zehnten Tag des zehnten Monats im neunten Jahr erging das Wort des
Herrn an mich:

<<v2>>
2 Menschensohn, schreib dir das Datum dieses Tages auf, genau den
heutigen Tag! Am heutigen Tag begann der König von Babel seinen Angriff
auf Jerusalem.\\
\\

<<v3>>
3 Leg dem widerspenstigen Volk ein Gleichnis vor und sag zu ihnen: So
spricht Gott, der Herr: Stell einen Kessel aufs Feuer, /\\
 stell ihn auf; auch Wasser gieß ein! ^{[[#fn1][1]]}\\
\\

<<v4>>
4 Leg Fleisch hinein, /\\
 lauter gute Stücke, Lende und Schulter! /\\
 Gib die besten Knochen dazu!\\
\\

<<v5>>
5 Nimm auserlesene Schafe! /\\
 Auch Brennholz leg ringsum unter den Kessel! Lass die Fleischstücke
kochen! /\\
 Auch die Knochen koch mit! ^{[[#fn2][2]]}\\
\\

<<v6>>
6 Darum - so spricht Gott, der Herr: Weh der Stadt voll Blutschuld, /\\
 weh dem verrosteten Kessel und weh dem Rost, der nicht abgeht. /\\
 Stück für Stück nimm wahllos heraus! ^{[[#fn3][3]]}\\
\\

<<v7>>
7 Denn das Blut, das die Stadt vergoss, /\\
 ist noch mitten in ihr. An den nackten Felsen hat sie es hingeschüttet.
/\\
 Nicht auf die Erde hat sie es vergossen /\\
 und nicht mit Erde bedeckt, ^{[[#fn4][4]]}\\
\\

<<v8>>
8 sodass mein Zorn entbrannte und ich Rache nahm: /\\
 Auf dem nackten Felsen vergieße ich ihr Blut; /\\
 es wird nicht mit Erde bedeckt.\\
\\

<<v9>>
9 Darum - so spricht Gott, der Herr: Weh der Stadt voll Blutschuld. /\\
 Auch ich schichte einen großen Holzstoß auf,\\
\\

<<v10>>
10 ich häufe das Holz, /\\
 ich entzünde das Feuer, ich koche das Fleisch, /\\
 ich gieße die Brühe ab /\\
 [und die Knochen sollen verbrennen]. ^{[[#fn5][5]]}\\
\\

<<v11>>
11 Dann stelle ich den Kessel leer auf die Glut, damit das Metall sich
erhitzt und glüht, damit schmilzt, was an ihm unrein ist, und der Rost
verschwindet.

<<v12>>
12 Doch umsonst die Mühe: Der starke Rost geht im Feuer nicht ab.

<<v13>>
13 Wegen deiner Schandtaten und deiner Unreinheit - weil ich dich rein
machen wollte, du aber nicht frei wurdest von deiner Unreinheit sollst
du nicht mehr rein werden, bis ich meinen Zorn an dir gestillt habe.
^{[[#fn6][6]]}

<<v14>>
14 Ich, der Herr, habe gesprochen. Jetzt ist es soweit, ich führe es
aus. Ich sehe nicht tatenlos zu. Ich habe kein Mitleid, es reut mich
nicht. Nach deinem Verhalten und deinen Taten will ich dich richten
Spruch Gottes, des Herrn. ^{[[#fn7][7]][[#fn8][8]]}\\
\\

<<v15>>
**** Die Zerstörung der Stadt: 24,15-27
     :PROPERTIES:
     :CUSTOM_ID: die-zerstörung-der-stadt-2415-27
     :END:
15 Das Wort des Herrn erging an mich:

<<v16>>
16 Menschensohn, ich nehme dir die Freude deiner Augen durch einen jähen
Tod. Doch du sollst weder klagen noch weinen. Keine Träne darfst du
vergießen,

<<v17>>
17 nur leise stöhnen. Keine Trauerfeier sollst du halten. Binde deinen
Kopfbund um und zieh deine Schuhe an! Verhülle deinen Bart nicht, und
iss kein Trauerbrot! ^{[[#fn9][9]]}

<<v18>>
18 Ich redete am Morgen zum Volk. Meine Frau starb am Abend und ich tat
am Morgen, was mir befohlen war.

<<v19>>
19 Da sagte das Volk zu mir: Willst du uns nicht erklären, was dein
Verhalten für uns zu bedeuten hat?

<<v20>>
20 Ich antwortete ihnen: Das Wort des Herrn ist an mich ergangen.

<<v21>>
21 Sag zum Haus Israel: So spricht Gott, der Herr: Ich will mein
Heiligtum entweihen, den Zufluchtsort, auf den ihr so stolz seid, die
Freude eurer Augen und die Sehnsucht eurer Seele. Eure Söhne und
Töchter, die ihr zurückgelassen habt, werden unter dem Schwert fallen.

<<v22>>
22 Dann werdet ihr genauso handeln wie ich: Ihr werdet den Bart nicht
verhüllen und kein Trauerbrot essen.

<<v23>>
23 Euren Kopfbund werdet ihr auf dem Kopf behalten und eure Schuhe an
den Füßen. Ihr werdet weder klagen noch weinen, sondern wegen eurer
Sünden dahinsiechen und miteinander stöhnen.

<<v24>>
24 Ezechiel wird ein Mahnzeichen für euch sein. Genauso wie er gehandelt
hat, werdet ihr handeln; wenn das eintrifft, werdet ihr erkennen, dass
ich Gott, der Herr, bin.

<<v25>>
25 Du aber, Menschensohn, an jenem Tag, wenn ich ihnen ihren
Zufluchtsort nehme, ihre Pracht und Wonne, die Freude ihrer Augen und
die Sehnsucht ihrer Seele, ihre Söhne und Töchter,

<<v26>>
26 an jenem Tag wird zu dir ein Flüchtling kommen, um dir die Nachricht
zu bringen. ^{[[#fn10][10]]}

<<v27>>
27 Und an jenem Tag wird in Gegenwart des Flüchtlings dein Mund
geöffnet. Du wirst reden und nicht mehr stumm sein. So wirst du zu einem
Mahnzeichen für sie und sie werden erkennen, dass ich der Herr bin.
^{[[#fn11][11]]}\\
\\

^{[[#fnm1][1]]} ℘ (3-14) 11,3-13

^{[[#fnm2][2]]} Brennholz: Text korr.; H: die Knochen. - koch mit: Text
korr.; H: kochen sie.

^{[[#fnm3][3]]} ℘ 22,2

^{[[#fnm4][4]]} ℘ Lev 17,13; Ijob 16,18

^{[[#fnm5][5]]} ich gieße die Brühe ab: Text korr. nach G.

^{[[#fnm6][6]]} ℘ 5,13

^{[[#fnm7][7]]} ℘ 5,11

^{[[#fnm8][8]]} ich will dich richten: Text korr. nach den alten
Übersetzungen und einigen H-Handschriften.

^{[[#fnm9][9]]} Trauerbrot: Text korr. nach Vg und der aramäischen
Übersetzung; H: Menschenbrot.

^{[[#fnm10][10]]} ℘ 33,21

^{[[#fnm11][11]]} ℘ 12,6.11
