:PROPERTIES:
:ID:       5b14a305-d13b-4d90-8d65-6842d4bc254f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_20.html][20]] [[file:Ez_21.html][21]] *22*
[[file:Ez_23.html][23]] [[file:Ez_24.html][24]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 22
  :PROPERTIES:
  :CUSTOM_ID: ez-22
  :END:

<<verses>>

<<v1>>
**** Anklage gegen Jerusalem: 22,1-16
     :PROPERTIES:
     :CUSTOM_ID: anklage-gegen-jerusalem-221-16
     :END:
1 Das Wort des Herrn erging an mich:

<<v2>>
2 Du, Menschensohn, willst du das Urteil sprechen, willst du das Urteil
sprechen über die Stadt voll Blutschuld, willst du ihr alle ihre
Gräueltaten bewusst machen, ^{[[#fn1][1]]}

<<v3>>
3 dann sag zu ihr: So spricht Gott, der Herr: Du Stadt, die in ihrer
Mitte Blut vergießt, sodass die Zeit (des Gerichts) über sie kommt, und
die sich Götzen macht und dadurch unrein wird:

<<v4>>
4 Durch das Blut, das du vergossen hast, bist du schuldig geworden und
durch die Götzen, die du gemacht hast, bist du unrein geworden. Du hast
dafür gesorgt, dass die Tage (deines Gerichts) nahe gerückt sind; so
bist du ans Ende deiner Jahre gekommen. Deshalb mache ich dich zu einem
Zeichen der Schande unter den Völkern und des höhnischen Spottes in
allen Ländern. ^{[[#fn2][2]]}

<<v5>>
5 Nah und Fern verhöhnt dich; denn dein Name ist befleckt und deine
Bestürzung ist groß.

<<v6>>
6 Jeder der Fürsten Israels strebt mit aller Macht danach, in dir Blut
zu vergießen.

<<v7>>
7 In dir verachtet man Vater und Mutter. In deiner Mitte beutet man die
Fremden aus. In dir unterdrückt man Waisen und Witwen. ^{[[#fn3][3]]}

<<v8>>
8 Was mir heilig ist, verachtest du. Meine Sabbat-Tage entweihst du.

<<v9>>
9 In dir gibt es Verleumder, die Blut vergießen wollen. Man hält bei dir
auf den Bergen Opfermahlzeiten ab. Schandtaten verübt man bei dir:
^{[[#fn4][4]]}

<<v10>>
10 Man schändet die Frau des Vaters, man missbraucht bei dir Frauen
während ihrer Blutung. ^{[[#fn5][5]]}

<<v11>>
11 Der eine treibt abscheuliche Dinge mit der Frau seines Nächsten; ein
anderer begeht die Schandtat, seine Schwiegertochter unrein zu machen,
wieder ein anderer missbraucht seine Schwester, die Tochter seines
Vaters. ^{[[#fn6][6]]}

<<v12>>
12 Bei dir lässt man sich bestechen und vergießt dadurch Blut. Du nimmst
Zins und treibst Wucher und erpresst deinen Nächsten. Mich aber hast du
vergessen - Spruch Gottes, des Herrn. ^{[[#fn7][7]]}

<<v13>>
13 Ich schlage meine Hände zusammen wegen des Gewinns, den du gemacht
hast, und wegen der Morde, die in deiner Mitte geschehen sind.

<<v14>>
14 Wird dein Herz standhalten können, werden deine Hände stark bleiben
in den Tagen, in denen ich gegen dich vorgehe? Ich, der Herr, habe
gesprochen und ich führe es aus.

<<v15>>
15 Ich zerstreue deine Einwohner unter die Völker und vertreibe sie in
alle Länder, ich mache der Unreinheit bei dir ein Ende. ^{[[#fn8][8]]}

<<v16>>
16 Durch deine eigene Schuld bist du entweiht vor den Augen der Völker
und du wirst erkennen, dass ich der Herr bin.\\
\\

<<v17>>
**** Der Schmelzofen des göttlichen Zorns: 22,17-22
     :PROPERTIES:
     :CUSTOM_ID: der-schmelzofen-des-göttlichen-zorns-2217-22
     :END:
17 Das Wort des Herrn erging an mich:

<<v18>>
18 Menschensohn, das Haus Israel ist für mich zu Schlacke geworden. Sie
alle sollten Silber, Kupfer und Zinn, Eisen und Blei im Schmelzofen
sein; doch sie sind Schlacke. ^{[[#fn9][9]][[#fn10][10]]}

<<v19>>
19 Darum - so spricht Gott, der Herr: Weil ihr alle zu Schlacke geworden
seid, werde ich euch mitten in Jerusalem sammeln.

<<v20>>
20 Wie man Silber, Kupfer, Eisen, Blei und Zinn im Schmelzofen
zusammentut und darunter das Feuer anzündet, um alles zum Schmelzen zu
bringen, so will ich euch in meinem Zorn und Grimm zusammentun, will
euch in den Ofen legen und euch zum Schmelzen bringen.

<<v21>>
21 Ich tue euch alle zusammen hinein und lasse das Feuer meines Zorns
gegen euch auflodern; darin werdet ihr dann schmelzen.

<<v22>>
22 Wie Silber im Schmelzofen schmilzt, so werdet ihr darin zum Schmelzen
gebracht. Dann erkennt ihr, dass ich, der Herr, meinen Zorn über euch
ausschütte.\\
\\

<<v23>>
**** Die Verderbtheit aller Schichten des Volkes: 22,23-31
     :PROPERTIES:
     :CUSTOM_ID: die-verderbtheit-aller-schichten-des-volkes-2223-31
     :END:
23 Das Wort des Herrn erging an mich:

<<v24>>
24 Menschensohn, sag zu dem Land: Du bist ein Land, das nicht vom Regen
begossen, nicht benetzt wird am Tag des Zorns.

<<v25>>
25 Mitten in ihm sind seine Fürsten wie brüllende Löwen, die auf Beute
aus sind. Sie fressen Menschen, nehmen Schätze und Kostbarkeiten an sich
und machen viele Frauen im Land zu Witwen. ^{[[#fn11][11]][[#fn12][12]]}

<<v26>>
26 Seine Priester vergewaltigen mein Gesetz. Sie entweihen, was mir
heilig ist. Zwischen heilig und nicht heilig machen sie keinen
Unterschied. Sie belehren niemand mehr über unrein und rein und vor
meinen Sabbat-Tagen verschließen sie die Augen. So werde ich mitten
unter ihnen entweiht.

<<v27>>
27 Mitten in ihm sind seine Beamten wie Wölfe, die auf Beute aus sind;
sie vergießen Blut und richten Menschenleben zugrunde, um Gewinn zu
machen.

<<v28>>
28 Seine Propheten aber übertünchen ihnen alles. Sie haben nichtige
Visionen, verkünden ihnen falsche Orakel und sagen: So spricht Gott, der
Herr - obwohl der Herr gar nicht gesprochen hat. ^{[[#fn13][13]]}

<<v29>>
29 Die Bürger des Landes erpressen und rauben. Sie beuten die Schwachen
und Armen aus und erpressen die Fremden gegen jedes Recht.

<<v30>>
30 Da suchte ich unter ihnen einen Mann, der eine Mauer baut oder für
das Land in die Bresche springt und mir entgegentritt, damit ich es
nicht vernichten muss; aber ich fand keinen.

<<v31>>
31 Darum schütte ich meinen Groll über sie aus. Ich vernichte sie im
Feuer meines Zorns. Ihr Verhalten lasse ich auf sie selbst
zurückfallen - Spruch Gottes, des Herrn. ^{[[#fn14][14]]}\\
\\

^{[[#fnm1][1]]} ℘ 20,4; 23,36

^{[[#fnm2][2]]} ℘ 5,14

^{[[#fnm3][3]]} ℘ Ex 22,21f

^{[[#fnm4][4]]} ℘ 18,5-9

^{[[#fnm5][5]]} ℘ Lev 18,20; 20,10

^{[[#fnm6][6]]} ℘ Lev 18,15; 20,12; 18,9; 20,17

^{[[#fnm7][7]]} ℘ Ex 22,24; Lev 25,36; Dtn 23,20

^{[[#fnm8][8]]} ℘ Lev 26,33

^{[[#fnm9][9]]} ℘ Jes 1,22-25; Jer 6,28

^{[[#fnm10][10]]} Text korr.

^{[[#fnm11][11]]} ℘ Zef 3,3f

^{[[#fnm12][12]]} sind seine Fürsten: Text korr. nach G; H: ist die
Verschwörung seiner Propheten.

^{[[#fnm13][13]]} ℘ 13,3-10

^{[[#fnm14][14]]} ℘ 9,10; 11,21; 16,43
