:PROPERTIES:
:ID:       e2d9a2da-7466-48f6-9596-b9dd1ca709ca
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_23.html][23]] [[file:Ez_24.html][24]] *25*
[[file:Ez_26.html][26]] [[file:Ez_27.html][27]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 25
  :PROPERTIES:
  :CUSTOM_ID: ez-25
  :END:

<<verses>>

<<v1>>
** Die Drohsprüche gegen die Nachbarvölker: 25,1 - 32,32
   :PROPERTIES:
   :CUSTOM_ID: die-drohsprüche-gegen-die-nachbarvölker-251---3232
   :END:
*** Gegen die unmittelbaren Nachbarn Israels: 25,1 - 28,26
    :PROPERTIES:
    :CUSTOM_ID: gegen-die-unmittelbaren-nachbarn-israels-251---2826
    :END:
**** Gegen Ammon, Moab, Edom und die Philister: 25,1-17
     :PROPERTIES:
     :CUSTOM_ID: gegen-ammon-moab-edom-und-die-philister-251-17
     :END:
1 Das Wort des Herrn erging an mich:

<<v2>>
2 Menschensohn, richte dein Gesicht gegen die Ammoniter, sprich als
Prophet über sie, ^{[[#fn1][1]]}

<<v3>>
3 und sag zu ihnen: Hört das Wort Gottes, des Herrn: So spricht Gott,
der Herr: Weil du gegen mein Heiligtum hin «Ha, ha» geschrien hast, als
es entweiht wurde, und gegen das Land Israel, als es verwüstet wurde,
und gegen das Haus Juda, als es verschleppt wurde,

<<v4>>
4 darum gebe ich dich jetzt den Völkern des Ostens zum Besitz. Sie
werden ihre Zelte bei dir aufschlagen und ihre Siedlungen bei dir
errichten. Sie werden deine Früchte essen und deine Milch trinken.

<<v5>>
5 Rabba mache ich zum Weideplatz der Kamele und die Städte der Ammoniter
zum Lager der Schafe und Ziegen. Dann werdet ihr erkennen, dass ich der
Herr bin.

<<v6>>
6 Denn so spricht Gott, der Herr: Weil du in die Hände geklatscht und
mit dem Fuß auf den Boden gestampft hast, voll höhnischer Schadenfreude
über das Land Israel,

<<v7>>
7 darum strecke ich jetzt meine Hand gegen dich aus, ich überlasse dich
den Völkern zur Plünderung, ich rotte dich aus unter den Nationen und
sorge dafür, dass du aus der Zahl der Länder verschwindest; ich
vernichte dich. Dann wirst du erkennen, dass ich der Herr bin.

<<v8>>
8 So spricht Gott, der Herr: Weil Moab und Seïr sagen: Dem Haus Juda
geht es wie allen anderen Völkern!, ^{[[#fn2][2]]}

<<v9>>
9 darum will ich die Flanke Moabs aufreißen, sodass es bei ihm keine
Stadt mehr gibt von einem Ende zum andern, nicht mehr Bet-Jeschimot,
Baal-Meon und Kirjatajim, die Zierde des Landes. ^{[[#fn3][3]]}

<<v10>>
10 Zusammen mit den Ammonitern gebe ich es den Völkern des Ostens zum
Besitz, sodass die Ammoniter unter den Nationen nicht mehr erwähnt
werden

<<v11>>
11 und ich an Moab das Urteil vollstrecke. Dann werden sie erkennen,
dass ich der Herr bin.

<<v12>>
12 So spricht Gott, der Herr: Weil Edom sich am Haus Juda gerächt hat,
weil es Schuld auf sich geladen und Rache an ihm genommen hat,
^{[[#fn4][4]]}

<<v13>>
13 darum - so spricht Gott, der Herr: Ich strecke meine Hand gegen Edom
aus, ich vernichte darin Mensch und Tier und mache es zur Wüste. Von
Teman bis Dedan sollen sie unter dem Schwert fallen. ^{[[#fn5][5]]}

<<v14>>
14 Ich lege meine Rache an Edom in die Hand meines Volkes Israel. Sie
werden an Edom meinem Zorn und Grimm entsprechend handeln. Dann wird
Edom meine Rache kennen lernen - Spruch Gottes, des Herrn.

<<v15>>
15 So spricht Gott, der Herr: Weil die Philister rachsüchtig waren und
voll Verachtung Rache nahmen, um Juda aus uralter Feindschaft zu
vernichten, ^{[[#fn6][6]]}

<<v16>>
16 darum - so spricht Gott, der Herr: Ich will jetzt meine Hand gegen
die Philister ausstrecken, ich will die Kereter ausrotten und die
übrigen Völker an der Küste vernichten. ^{[[#fn7][7]]}

<<v17>>
17 Ich nehme an ihnen gewaltige Rache mit grimmigen Strafen. Dann werden
sie erkennen, dass ich der Herr bin, wenn ich mich an ihnen räche.\\
\\

^{[[#fnm1][1]]} ℘ (1-7) 21,33-37; Am 1,13-15; Jer 49,1-6

^{[[#fnm2][2]]} ℘ (8-11) Jes 15; Jer 48

^{[[#fnm3][3]]} Die hier genannten Städte liegen östlich des Toten
Meeres.

^{[[#fnm4][4]]} ℘ (12-14) 35,1-15; Jer 49,7-22; Ps 137,7; Am 1,11f

^{[[#fnm5][5]]} Die Lage von Teman ist nicht mehr zu bestimmen; es lag
aber in Edom; Dedan ist ein Gebiet südlich von Edom.

^{[[#fnm6][6]]} ℘ (15-17) Jer 47; Jes 14,29-32; Am 1,6-8; Zef 2,4-7

^{[[#fnm7][7]]} Die Kereter sind eine Gruppe innerhalb der Philister;
«ausrotten» und «Kereter» bilden in H ein Wortspiel.
