:PROPERTIES:
:ID:       93f319d8-f64a-4cb0-9710-98cbf94a497b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_29.html][29]] [[file:Ez_30.html][30]] *31*
[[file:Ez_32.html][32]] [[file:Ez_33.html][33]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 31
  :PROPERTIES:
  :CUSTOM_ID: ez-31
  :END:

<<verses>>

<<v1>>
**** Das Gleichnis vom Pharao, dem prächtigen Baum: 31,1-18
     :PROPERTIES:
     :CUSTOM_ID: das-gleichnis-vom-pharao-dem-prächtigen-baum-311-18
     :END:
1 Am ersten Tag des dritten Monats im elften Jahr erging das Wort des
Herrn an mich:\\
\\

<<v2>>
2 Menschensohn, sag zum Pharao, dem König von Ägypten, und zu seinem
Gefolge: Wem war deine Größe vergleichbar? /\\
\\

<<v3>>
3 Auf dem Libanon stand eine [Esche] Zeder. Die Pracht ihrer Äste gab
reichlichen Schatten. /\\
 Hoch war ihr Wuchs /\\
 und in die Wolken ragte ihr Wipfel. ^{[[#fn1][1]]}\\
\\

<<v4>>
4 Das Wasser machte sie groß. /\\
 Die Flut in der Tiefe ließ sie hoch emporwachsen. Die Tiefe ließ ihre
Ströme fließen /\\
 rings um den Ort, wo sie gepflanzt war, sie leitete (von dort) ihre
Kanäle /\\
 zu allen anderen Bäumen des Feldes.\\
\\

<<v5>>
5 So war sie höher gewachsen /\\
 als alle anderen Bäume des Feldes. Ihre Zweige wurden sehr zahlreich
/\\
 und ihre Äste breiteten sich aus wegen des Reichtums an Wasser, /\\
 als sie emporwuchs. ^{[[#fn2][2]]}\\
\\

<<v6>>
6 Alle Vögel des Himmels /\\
 hatten ihr Nest in den Zweigen. Alle wilden Tiere brachten unter den
Ästen ihre Jungen zur Welt. /\\
 All die vielen Völker wohnten in ihrem Schatten.\\
\\

<<v7>>
7 Schön war sie in ihrer Größe mit ihrem breiten Geäst; /\\
 denn ihre Wurzeln hatten viel Wasser.\\
\\

<<v8>>
8 Keine Zeder im Garten Gottes war ihr vergleichbar. /\\
 Keine Zypresse hatte Zweige wie sie, /\\
 keine Platane so mächtige Äste. Keiner der Bäume im Garten Gottes /\\
 glich ihr an Schönheit.\\
\\

<<v9>>
9 Ja, ich hatte sie herrlich gemacht /\\
 mit ihren zahlreichen Zweigen. Voll Eifersucht auf sie waren im Garten
Gottes /\\
 alle Bäume von Eden. ^{[[#fn3][3]]}\\
\\

<<v10>>
10 Darum - so spricht Gott, der Herr: Weil sie so hoch emporwuchs und
mit ihrem Wipfel in die Wolken ragte und wegen ihrer Höhe überheblich
wurde, ^{[[#fn4][4]][[#fn5][5]]}

<<v11>>
11 deshalb liefere ich sie dem mächtigsten Herrscher der Völker aus. Er
behandelt sie so, wie sie es in ihrer Schlechtigkeit verdient hat; ich
beseitige sie.

<<v12>>
12 Fremde, die gewalttätigsten unter den Völkern, werden sie umhauen und
hinwerfen. Ihre Zweige fallen auf die Berge und in alle Täler, ihre Äste
zerbrechen in allen Schluchten der Erde. Alle Völker der Erde verlassen
den Schatten der Zeder und lassen sie liegen.

<<v13>>
13 Auf ihren gefällten Stamm setzen sich alle Vögel des Himmels, die
wilden Tiere hausen in ihren Zweigen.

<<v14>>
14 Darum soll kein Baum mehr am Wasser emporwachsen und mit seinem
Wipfel in die Wolken ragen, keiner der Bäume am Wasser soll mehr so
mächtig und hoch dastehen. Denn alle werden dem Tod ausgeliefert, sie
müssen hinab in die Unterwelt zu den Menschen, die ins Grab gesunken
sind.

<<v15>>
15 So spricht Gott, der Herr: Wenn die Zeder in die Unterwelt stürzt,
dann lasse ich die Flut in der Tiefe versiegen, ich decke sie zu; ich
halte ihre Ströme zurück, sodass der Reichtum an Wasser versiegt.
Ihretwegen hülle ich den Libanon in Trauer und alle Bäume des Feldes
sinken in Ohnmacht.

<<v16>>
16 Durch das Getöse ihres Sturzes lasse ich die Völker erzittern, wenn
ich den Baum in die Unterwelt stürze, hinab zu denen, die ins Grab
gesunken sind. Dann trösten sich in der Unterwelt alle Bäume von Eden,
die erlesenen und besten Bäume des Libanon, alle Bäume am Wasser.
^{[[#fn6][6]]}

<<v17>>
17 Denn auch sie stürzen zusammen mit ihr in die Unterwelt, hinab zu
denen, die vom Schwert erschlagen wurden. Alle aber, die im Schatten der
Zeder wohnten, werden unter die Völker zerstreut. ^{[[#fn7][7]]}

<<v18>>
18 Welcher der Bäume von Eden glich dir an Größe und Pracht? Und doch
wirst du zusammen mit den Bäumen von Eden in die Unterwelt gestürzt.
Dort wirst du mitten unter den Unbeschnittenen liegen, unter denen, die
vom Schwert erschlagen wurden. So geht es dem Pharao und seinem ganzen
Gefolge - Spruch Gottes, des Herrn.\\
\\

^{[[#fnm1][1]]} Esche: Text korr.; H: Assur.

^{[[#fnm2][2]]} Übersetzung unsicher.

^{[[#fnm3][3]]} ℘ Gen 2,8

^{[[#fnm4][4]]} ℘ Dan 5,20

^{[[#fnm5][5]]} sie . . . emporwuchs: Text korr. (3. statt 2. Person);
vgl. G.

^{[[#fnm6][6]]} ℘ 32,17-32; 28,8

^{[[#fnm7][7]]} wohnten, werden . . . zerstreut: Text korr., vgl. G.
