:PROPERTIES:
:ID:       772977b8-5757-45b6-8d8f-b5292c9b93fc
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_32.html][32]] [[file:Ez_33.html][33]] *34*
[[file:Ez_35.html][35]] [[file:Ez_36.html][36]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 34
  :PROPERTIES:
  :CUSTOM_ID: ez-34
  :END:

<<verses>>

<<v1>>
**** Die schlechten Hirten: 34,1-10
     :PROPERTIES:
     :CUSTOM_ID: die-schlechten-hirten-341-10
     :END:
1 Das Wort des Herrn erging an mich:

<<v2>>
2 Menschensohn, sprich als Prophet gegen die Hirten Israels, sprich als
Prophet und sag zu ihnen: So spricht Gott, der Herr: Weh den Hirten
Israels, die nur sich selbst weiden. Müssen die Hirten nicht die Herde
weiden? ^{[[#fn1][1]][[#fn2][2]]}

<<v3>>
3 Ihr trinkt die Milch, nehmt die Wolle für eure Kleidung und schlachtet
die fetten Tiere; aber die Herde führt ihr nicht auf die Weide.
^{[[#fn3][3]]}

<<v4>>
4 Die schwachen Tiere stärkt ihr nicht, die kranken heilt ihr nicht, die
verletzten verbindet ihr nicht, die verscheuchten holt ihr nicht zurück,
die verirrten sucht ihr nicht und die starken misshandelt ihr.
^{[[#fn4][4]]}

<<v5>>
5 Und weil sie keinen Hirten hatten, zerstreuten sich meine Schafe und
wurden eine Beute der wilden Tiere. ^{[[#fn5][5]]}

<<v6>>
6 Meine Herde irrte auf allen Bergen und Höhen umher und war über das
ganze Land verstreut. Doch keiner kümmerte sich um sie; niemand suchte
sie.

<<v7>>
7 Darum ihr Hirten, hört das Wort des Herrn:

<<v8>>
8 So wahr ich lebe - Spruch Gottes, des Herrn: Weil meine Herde geraubt
wurde und weil meine Schafe eine Beute der wilden Tiere wurden - denn
sie hatten keinen Hirten - und weil meine Hirten nicht nach meiner Herde
fragten, sondern nur sich selbst und nicht meine Herde weideten,

<<v9>>
9 darum, ihr Hirten, hört das Wort des Herrn:

<<v10>>
10 So spricht Gott, der Herr: Nun gehe ich gegen die Hirten vor und
fordere meine Schafe von ihnen zurück. Ich setze sie ab, sie sollen
nicht mehr die Hirten meiner Herde sein. Die Hirten sollen nicht länger
nur sich selbst weiden: Ich reiße meine Schafe aus ihrem Rachen, sie
sollen nicht länger ihr Fraß sein. ^{[[#fn6][6]]}\\
\\

<<v11>>
**** Der gute Hirt: 34,11-22
     :PROPERTIES:
     :CUSTOM_ID: der-gute-hirt-3411-22
     :END:
11 Denn so spricht Gott, der Herr: Jetzt will ich meine Schafe selber
suchen und mich selber um sie kümmern. ^{[[#fn7][7]]}

<<v12>>
12 Wie ein Hirt sich um die Tiere seiner Herde kümmert an dem Tag, an
dem er mitten unter den Schafen ist, die sich verirrt haben, so kümmere
ich mich um meine Schafe und hole sie zurück von all den Orten, wohin
sie sich am dunklen, düsteren Tag zerstreut haben.

<<v13>>
13 Ich führe sie aus den Völkern heraus, ich hole sie aus den Ländern
zusammen und bringe sie in ihr Land. Ich führe sie in den Bergen Israels
auf die Weide, in den Tälern und an allen bewohnten Orten des Landes.

<<v14>>
14 Auf gute Weide will ich sie führen, im Bergland Israels werden ihre
Weideplätze sein. Dort sollen sie auf guten Weideplätzen lagern, auf den
Bergen Israels sollen sie fette Weide finden. ^{[[#fn8][8]]}

<<v15>>
15 Ich werde meine Schafe auf die Weide führen, ich werde sie ruhen
lassen - Spruch Gottes, des Herrn.

<<v16>>
16 Die verloren gegangenen Tiere will ich suchen, die vertriebenen
zurückbringen, die verletzten verbinden, die schwachen kräftigen, die
fetten und starken behüten. Ich will ihr Hirt sein und für sie sorgen,
wie es recht ist. ^{[[#fn9][9]]}

<<v17>>
17 Ihr aber, meine Herde - so spricht Gott, der Herr -, ich sorge für
Recht zwischen Schafen und Schafen, zwischen Widdern und Böcken.
^{[[#fn10][10]]}

<<v18>>
18 War es euch nicht genug, auf der besten Weide zu weiden? Musstet ihr
auch noch euer übriges Weideland mit euren Füßen zertrampeln? War es
euch nicht genug, das klare Wasser zu trinken? Musstet ihr den Rest des
Wassers mit euren Füßen verschmutzen?

<<v19>>
19 Meine Schafe mussten abweiden, was eure Füße zertrampelt hatten, und
trinken, was eure Füße verschmutzt hatten.

<<v20>>
20 Darum - so spricht Gott, der Herr, zu euch: Ich selbst sorge für
Recht zwischen den fetten und den mageren Schafen.

<<v21>>
21 Weil ihr mit eurem breiten Körper und eurer Schulter alle schwachen
Tiere zur Seite gedrängt und weil ihr sie mit euren Hörnern weggestoßen
habt, bis ihr sie weggetrieben hattet,

<<v22>>
22 deshalb will ich meinen Schafen zu Hilfe kommen. Sie sollen nicht
länger eure Beute sein; denn ich werde für Recht sorgen zwischen Schafen
und Schafen.\\
\\

<<v23>>
**** Das messianische Reich: 34,23-31
     :PROPERTIES:
     :CUSTOM_ID: das-messianische-reich-3423-31
     :END:
23 Ich setze für sie einen einzigen Hirten ein, der sie auf die Weide
führt, meinen Knecht David. Er wird sie weiden und er wird ihr Hirt
sein. ^{[[#fn11][11]]}

<<v24>>
24 Ich selbst, der Herr, werde ihr Gott sein und mein Knecht David wird
in ihrer Mitte der Fürst sein. Ich, der Herr, habe gesprochen.

<<v25>>
25 Ich schließe mit ihnen einen Friedensbund: Ich rotte die wilden Tiere
im Land aus. Dann kann man in der Steppe sicher wohnen und in den
Wäldern schlafen. ^{[[#fn12][12]]}

<<v26>>
26 Ich werde sie und die Umgebung meines Berges segnen. Ich schicke
Regen zur rechten Zeit und der Regen wird Segen bringen.
^{[[#fn13][13]]}

<<v27>>
27 Die Bäume des Feldes werden ihre Früchte tragen und das Land wird
seinen Ertrag geben. Sie werden auf ihrem Grund und Boden sicher sein.
Wenn ich die Stangen ihres Jochs zerbreche und sie der Gewalt derer
entreiße, von denen sie versklavt wurden, werden sie erkennen, dass ich
der Herr bin. ^{[[#fn14][14]]}

<<v28>>
28 Sie werden nicht länger eine Beute der Völker sein, von den wilden
Tieren werden sie nicht gefressen. Sie werden in Sicherheit wohnen und
niemand wird sie erschrecken. ^{[[#fn15][15]]}

<<v29>>
29 Ich pflanze ihnen einen Garten des Heils. Sie werden in ihrem Land
nicht mehr vom Hunger dahingerafft werden und die Schmähungen der Völker
müssen sie nicht mehr ertragen. ^{[[#fn16][16]][[#fn17][17]]}

<<v30>>
30 Sie werden erkennen, dass ich, der Herr, ihr Gott, mit ihnen bin und
dass sie, das Haus Israel, mein Volk sind - Spruch Gottes, des Herrn.
^{[[#fn18][18]]}

<<v31>>
31 Ihr seid meine Schafe, ihr seid die Herde meiner Weide. Ich bin euer
Gott - Spruch Gottes, des Herrn. ^{[[#fn19][19]]}\\
\\

^{[[#fnm1][1]]} ℘ Jer 23,1-4

^{[[#fnm2][2]]} Die bildhafte Rede meint die Führer des Volkes.

^{[[#fnm3][3]]} die Milch: Text korr. nach Vg, G; H: das Fett.

^{[[#fnm4][4]]} ℘ Sach 11,15f; Joh 10,11

^{[[#fnm5][5]]} ℘ Sach 10,2; Mt 9,36

^{[[#fnm6][6]]} ℘ Jer 23,2

^{[[#fnm7][7]]} ℘ Jes 40,11; Joh 10,1-18; Lk 15,4

^{[[#fnm8][8]]} ℘ Ps 23,2

^{[[#fnm9][9]]} behüten: Text korr. nach G; H: austilgen.

^{[[#fnm10][10]]} ℘ Mt 25,32

^{[[#fnm11][11]]} ℘ (23-24) 37,24; Ps 78,70; Jer 30,9; Hos 3,5; Joh
10,14-16

^{[[#fnm12][12]]} ℘ 37,26; Lev 26,6; Hos 2,20

^{[[#fnm13][13]]} ℘ Lev 26,4; Ps 84,7

^{[[#fnm14][14]]} ℘ Ps 67,7

^{[[#fnm15][15]]} ℘ Jer 30,10

^{[[#fnm16][16]]} ℘ 36,30

^{[[#fnm17][17]]} des Heils: Text korr. nach G und S; H: zum Ruhm.

^{[[#fnm18][18]]} ℘ 11,20

^{[[#fnm19][19]]} ℘ Ps 95,7; 100,3
