:PROPERTIES:
:ID:       c9b8f250-a40b-461b-9865-7a3425a00e37
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_28.html][28]] [[file:Ez_29.html][29]] *30*
[[file:Ez_31.html][31]] [[file:Ez_32.html][32]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 30
  :PROPERTIES:
  :CUSTOM_ID: ez-30
  :END:

<<verses>>

<<v1>>
**** Das Gericht über Ägypten: 30,1-26
     :PROPERTIES:
     :CUSTOM_ID: das-gericht-über-ägypten-301-26
     :END:
1 Das Wort des Herrn erging an mich:\\
\\

<<v2>>
2 Menschensohn, tritt als Prophet auf und sag: So spricht Gott, der
Herr: Jammert und schreit: /\\
 Weh über diesen Tag!\\
\\

<<v3>>
3 Denn der Tag ist nahe, /\\
 der Tag des Herrn ist nahe, ein Tag dunkler Wolken. /\\
 Die Zeit für die Völker ist da. ^{[[#fn1][1]]}\\
\\

<<v4>>
4 Das Schwert dringt ein in Ägypten. /\\
 Ein Zittern überfällt die Kuschiter, /\\
 wenn in Ägypten die Menschen erschlagen werden und fallen. Man schleppt
seine Schätze hinweg /\\
 und reißt seine Grundmauern nieder.\\
\\

<<v5>>
5 (Die Männer aus) Kusch, aus Put und Lud, /\\
 das ganze Völkergemisch, (die Männer aus) Kub und die Söhne des Landes,
/\\
 mit dem ich einst meinen Bund schloss, /\\
 fallen wie sie unter dem Schwert. ^{[[#fn2][2]]}\\
\\

<<v6>>
6 So spricht der Herr: Es fallen die Helfer Ägyptens, /\\
 seine herrliche Macht sinkt dahin. Von Migdol bis hin nach Syene /\\
 fallen die Krieger unter dem Schwert - /\\
 Spruch Gottes, des Herrn. ^{[[#fn3][3]][[#fn4][4]]}\\
\\

<<v7>>
7 Verwüstet liegt es dann da /\\
 inmitten verwüsteter Länder /\\
 und seine Städte inmitten verödeter Städte.\\
\\

<<v8>>
8 Sie werden erkennen, dass ich der Herr bin, /\\
 wenn ich Ägypten verbrenne, /\\
 wenn all seine Helfer zusammenbrechen.\\
\\

<<v9>>
9 An jenem Tag schicke ich meine Boten auf Schiffen hinaus, /\\
 um Kusch aus seiner Ruhe zu schrecken. Ein Zittern überfällt sie am
Gerichtstag Ägyptens; /\\
 schon trifft all das ein.\\
\\

<<v10>>
10 So spricht Gott, der Herr: Ich mache der Pracht Ägyptens ein Ende /\\
 durch die Hand Nebukadnezzars, /\\
 des Königs von Babel. ^{[[#fn5][5]]}\\
\\

<<v11>>
11 Er und sein Heer, /\\
 die gewalttätigsten unter den Völkern, /\\
 werden herbeigeholt, um das Land zu vernichten. Sie zücken ihr Schwert
und schlagen Ägypten /\\
 und füllen das Land mit erschlagenen Menschen. ^{[[#fn6][6]]}\\
\\

<<v12>>
12 Ich lege die Nilarme trocken, /\\
 verkaufe das Land an Verbrecher, ich verwüste das Land und alles darin
/\\
 durch die Hände von Fremden. /\\
 Ich, der Herr, habe gesprochen. ^{[[#fn7][7]]}\\
\\

<<v13>>
13 So spricht Gott, der Herr: Ich will die Götzen vernichten. /\\
 Ich führe das Ende der Götter von Memfis herbei. Der Fürst von Ägypten
wird (bald) nicht mehr leben. /\\
 Ich stürze Ägypten in Angst.\\
\\

<<v14>>
14 Patros will ich verwüsten, /\\
 Zoan will ich verbrennen, /\\
 an No vollstrecke ich das Urteil. ^{[[#fn8][8]]}\\
\\

<<v15>>
15 Über Sin, die Festung Ägyptens, gieße ich meinen Zorn aus und ich
vernichte die Pracht von No.

<<v16>>
16 Ägypten will ich verbrennen. Sin wird sich in Krämpfen winden; No
wird man erstürmen und Memfis wird am hellen Tag von Feinden bedrängt.

<<v17>>
17 Die jungen Männer von On und Pi-Beset fallen unter dem Schwert und
die Einwohner dieser Städte ziehen in die Gefangenschaft. ^{[[#fn9][9]]}

<<v18>>
18 Es wird ein schwarzer Tag für Tachpanhes, wenn ich dort die Zepter
Ägyptens zerbreche; dann ist es mit seiner herrlichen Macht zu Ende.
Finstere Wolken werden Ägypten bedecken und seine Töchter ziehen in die
Gefangenschaft. ^{[[#fn10][10]]}

<<v19>>
19 So vollstrecke ich an Ägypten das Urteil und sie werden erkennen,
dass ich der Herr bin.

<<v20>>
20 Am siebten Tag des ersten Monats im elften Jahr erging das Wort des
Herrn an mich:

<<v21>>
21 Menschensohn, ich habe dem Pharao, dem König von Ägypten, den Arm
zerbrochen. Man hat ihn nicht verbunden und nicht geschient und ihm
keine Heilung gegönnt, damit er nicht wieder zu Kräften kommt und zum
Schwert greift.

<<v22>>
22 Darum - so spricht Gott, der Herr: Jetzt gehe ich gegen den Pharao
vor, den König von Ägypten: Ich zerbreche ihm beide Arme, den gesunden
und den bereits zerbrochenen, und schlage ihm das Schwert aus der Hand.

<<v23>>
23 Ich zerstreue die Ägypter unter die Völker und vertreibe sie in alle
Länder. ^{[[#fn11][11]]}

<<v24>>
24 Ich stärke die Arme des Königs von Babel und gebe ihm mein Schwert in
die Hand. Dem Pharao aber zerbreche ich die Arme, sodass er vor ihm
stöhnt wie ein tödlich Verletzter.

<<v25>>
25 Ich stärke die Arme des Königs von Babel; doch die Arme des Pharao
sinken kraftlos herunter. Wenn ich dem König von Babel mein Schwert in
die Hand gebe und er es über Ägypten schwingt, dann werden sie erkennen,
dass ich der Herr bin.

<<v26>>
26 Ich zerstreue die Ägypter unter die Völker und vertreibe sie in alle
Länder. Dann werden sie erkennen, dass ich der Herr bin.\\
\\

^{[[#fnm1][1]]} ℘ Joël 1,15; Am 5,18; Zef 1,14

^{[[#fnm2][2]]} ℘ Jer 46,9

^{[[#fnm3][3]]} ℘ 29,10

^{[[#fnm4][4]]} Vgl. die Anmerkung zu 29,10.

^{[[#fnm5][5]]} ℘ 29,10

^{[[#fnm6][6]]} ℘ 28,7

^{[[#fnm7][7]]} ℘ Jes 19,5

^{[[#fnm8][8]]} 14-16: Zu Patros vgl. die Anmerkung zu 29,14. - Zoan
liegt im Nildelta: No ist Residenz- und Tempelstadt; Theben liegt in
Oberägypten; Sin (V. 16) liegt nahe bei Zoan.

^{[[#fnm9][9]]} 17f: On: Text korr. mit G. On (= Heliopolis) ist der
zentrale Ort des ägyptischen Sonnenkults, nordwestlich von Kairo.
Pi-Beset (= Bubastis) liegt im östlichen Nildelta, ebenso Tachpanhes (=
Daphne). - die Zepter: Text korr. nach G und Vg; H: die Jochstangen.

^{[[#fnm10][10]]} ℘ Jer 43,9

^{[[#fnm11][11]]} ℘ (23-24) 29,19f
