:PROPERTIES:
:ID:       8be7eef2-f94c-4d1f-9125-c2a13d8a357f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]]
[[file:Ez_2.html][2]] *3* [[file:Ez_4.html][4]] [[file:Ez_5.html][5]]
... [[file:Ez_48.html][48]]

--------------

* Ez 3
  :PROPERTIES:
  :CUSTOM_ID: ez-3
  :END:

<<verses>>

<<v1>>
1 Er sagte zu mir: Menschensohn, iss, was du vor dir hast. Iss diese
Rolle! Dann geh und rede zum Haus Israel! ^{[[#fn1][1]]}

<<v2>>
2 Ich öffnete meinen Mund und er ließ mich die Rolle essen.

<<v3>>
3 Er sagte zu mir: Menschensohn, gib deinem Bauch zu essen, fülle dein
Inneres mit dieser Rolle, die ich dir gebe. Ich aß sie und sie wurde in
meinem Mund süß wie Honig. ^{[[#fn2][2]]}

<<v4>>
4 Er sagte zu mir: Geh zum Haus Israel, Menschensohn, und sprich mit
meinen Worten zu ihnen!

<<v5>>
5 Nicht zu einem Volk mit fremder Sprache und unverständlicher Rede
wirst du gesandt, sondern zum Haus Israel, ^{[[#fn3][3]]}

<<v6>>
6 auch nicht zu vielen Völkern mit fremder Sprache und unverständlicher
Rede, deren Worte du nicht verstehst. Würde ich dich zu ihnen senden,
sie würden auf dich hören.

<<v7>>
7 Doch das Haus Israel will nicht auf dich hören, es fehlt ihnen der
Wille, auf mich zu hören; denn jeder vom Haus Israel hat eine harte
Stirn und ein trotziges Herz.

<<v8>>
8 Ich aber mache dein Gesicht ebenso hart wie ihr Gesicht und deine
Stirn ebenso hart wie ihre Stirn. ^{[[#fn4][4]]}

<<v9>>
9 Wie Diamant und härter als Kieselstein mache ich deine Stirn. Fürchte
sie nicht, erschrick nicht vor ihrem Blick; denn sie sind ein
widerspenstiges Volk. ^{[[#fn5][5]]}

<<v10>>
10 Er sagte zu mir: Menschensohn, nimm alle meine Worte, die ich dir
sage, mit deinem Herzen auf und höre mit deinen Ohren!

<<v11>>
11 Geh zu den Verschleppten, zu den Söhnen deines Volkes, und ob sie
hören oder nicht, sprich zu ihnen und sag zu ihnen: So spricht Gott, der
Herr.

<<v12>>
12 Da hob mich der Geist empor und ich hörte hinter mir ein Geräusch,
ein gewaltiges Dröhnen, als sich die Herrlichkeit des Herrn von ihrem
Ort erhob, ^{[[#fn6][6]][[#fn7][7]]}

<<v13>>
13 das Geräusch von den Flügeln der Lebewesen, die einander berührten,
und das Geräusch der Räder neben ihnen, ein lautes, gewaltiges Dröhnen.

<<v14>>
14 Der Geist, der mich emporgehoben hatte, trug mich fort. Ich ging
dahin, mit bitterem und grollendem Herzen, und die Hand des Herrn lag
schwer auf mir.

<<v15>>
15 So kam ich zu den Verschleppten, [die am Fluss Kebar wohnten,] die in
Tel-Abib wohnten, und ich saß dort sieben Tage lang verstört mitten
unter ihnen.\\
\\

<<v16>>
**** Ezechiel als Wächter Israels: 3,16-21
     :PROPERTIES:
     :CUSTOM_ID: ezechiel-als-wächter-israels-316-21
     :END:
16 Am Ende der sieben Tage erging das Wort des Herrn an mich:
^{[[#fn8][8]]}

<<v17>>
17 Menschensohn, ich gebe dich dem Haus Israel als Wächter. Wenn du ein
Wort aus meinem Mund hörst, musst du sie vor mir warnen.

<<v18>>
18 Wenn ich zu einem, der sich schuldig gemacht hat, sage: Du musst
sterben!, und wenn du ihn nicht warnst und nicht redest, um den
Schuldigen von seinem schuldhaften Weg abzubringen, damit er am Leben
bleibt, dann wird der Schuldige seiner Sünde wegen sterben; von dir aber
fordere ich Rechenschaft für sein Blut. ^{[[#fn9][9]]}

<<v19>>
19 Wenn du aber den Schuldigen warnst und er sich von seiner Schuld und
seinem schuldhaften Weg nicht abwendet, dann wird er seiner Sünde wegen
sterben; du aber hast dein Leben gerettet.

<<v20>>
20 Und wenn ein Gerechter sein rechtschaffenes Leben aufgibt und Unrecht
tut, werde ich ihn zu Fall bringen und er wird sterben, weil du ihn
nicht gewarnt hast. Seiner Sünde wegen wird er sterben und an seine
gerechten Taten von einst wird man nicht mehr denken. Von dir aber
fordere ich Rechenschaft für sein Blut. ^{[[#fn10][10]]}

<<v21>>
21 Wenn du aber den Gerechten davor warnst zu sündigen und er sündigt
nicht, dann wird er am Leben bleiben, weil er gewarnt wurde, und du hast
dein Leben gerettet.\\
\\

<<v22>>
**** Das Verstummen Ezechiels: 3,22-27
     :PROPERTIES:
     :CUSTOM_ID: das-verstummen-ezechiels-322-27
     :END:
22 Dann legte sich die Hand des Herrn auf mich. Er sagte zu mir: Steh
auf und geh hinaus in die Ebene! Ich will dort mit dir reden.
^{[[#fn11][11]][[#fn12][12]]}

<<v23>>
23 Ich stand auf und ging in die Ebene hinaus. Und siehe, dort stand die
Herrlichkeit des Herrn, so wie ich sie schon am Fluss Kebar gesehen
hatte, und ich fiel nieder auf mein Gesicht. ^{[[#fn13][13]]}

<<v24>>
24 Doch der Geist kam in mich und stellte mich wieder auf die Füße. Er
redete mit mir und sagte zu mir: Geh in dein Haus und schließ dich ein!
^{[[#fn14][14]]}

<<v25>>
25 Und du, Menschensohn - sie werden dich fesseln und mit Stricken
binden, sodass du nicht mehr zum Volk hinausgehen kannst.

<<v26>>
26 Deine Zunge lasse ich dir am Gaumen kleben. Du wirst verstummen und
nicht mehr ihr Mahner sein können; denn sie sind ein widerspenstiges
Volk.

<<v27>>
27 Wenn ich aber mit dir rede, werde ich deinen Mund öffnen. Dann sag zu
ihnen: So spricht Gott, der Herr. Wer hören will, der höre, wer nicht
hören will, der lasse es; denn sie sind ein widerspenstiges Volk.
^{[[#fn15][15]][[#fn16][16]]}\\
\\

^{[[#fnm1][1]]} ℘ Jer 15,16; Offb 10,9

^{[[#fnm2][2]]} ℘ Ps 119,103

^{[[#fnm3][3]]} ℘ Jes 33,19

^{[[#fnm4][4]]} ℘ (8-9) Jes 50,7

^{[[#fnm5][5]]} ℘ Jer 1,17f

^{[[#fnm6][6]]} ℘ 8,3; 11,1.24; 37,1

^{[[#fnm7][7]]} Der Geist, d. h. die Kraft Gottes bringt den Propheten
vom Ort der Vision zu den Verschleppten, die in Tel-Abib am Eufratkanal
Kebar wohnen. - erhob: Text korr.; vgl. 10,4.

^{[[#fnm8][8]]} 16-21: Die Berufung Ezechiels zum Wächter Israels
erfolgte vermutlich erst nach der Zerstörung Jerusalems (vgl. 33,1-9).

^{[[#fnm9][9]]} ℘ Gen 9,5

^{[[#fnm10][10]]} ℘ 18,24; 33,12f

^{[[#fnm11][11]]} ℘ 1,3; 8,1; 33,22; 37,1; 40,1

^{[[#fnm12][12]]} 22-27: Nach 24,25-27 und 33,21f verstummt der Prophet
erst bei der Eroberung Jerusalems.

^{[[#fnm13][13]]} ℘ 1,28

^{[[#fnm14][14]]} ℘ 2,2

^{[[#fnm15][15]]} ℘ 24,27; 33,22

^{[[#fnm16][16]]} Gott, der Herr, wörtlich: der Herr Jahwe. So an allen
einschlägigen Stellen.
