:PROPERTIES:
:ID:       071d26a7-28ec-428b-99ac-6e7ca5e4a9cf
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_35.html][35]] [[file:Ez_36.html][36]] *37*
[[file:Ez_38.html][38]] [[file:Ez_39.html][39]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 37
  :PROPERTIES:
  :CUSTOM_ID: ez-37
  :END:

<<verses>>

<<v1>>
**** Die Vision von der Auferweckung Israels: 37,1-14
     :PROPERTIES:
     :CUSTOM_ID: die-vision-von-der-auferweckung-israels-371-14
     :END:
1 Die Hand des Herrn legte sich auf mich und der Herr brachte mich im
Geist hinaus und versetzte mich mitten in die Ebene. Sie war voll von
Gebeinen. ^{[[#fn1][1]]}

<<v2>>
2 Er führte mich ringsum an ihnen vorüber und ich sah sehr viele über
die Ebene verstreut liegen; sie waren ganz ausgetrocknet.

<<v3>>
3 Er fragte mich: Menschensohn, können diese Gebeine wieder lebendig
werden? Ich antwortete: Herr und Gott, das weißt nur du.

<<v4>>
4 Da sagte er zu mir: Sprich als Prophet über diese Gebeine und sag zu
ihnen: Ihr ausgetrockneten Gebeine, hört das Wort des Herrn!

<<v5>>
5 So spricht Gott, der Herr, zu diesen Gebeinen: Ich selbst bringe Geist
in euch, dann werdet ihr lebendig. ^{[[#fn2][2]]}

<<v6>>
6 Ich spanne Sehnen über euch und umgebe euch mit Fleisch; ich überziehe
euch mit Haut und bringe Geist in euch, dann werdet ihr lebendig. Dann
werdet ihr erkennen, dass ich der Herr bin.

<<v7>>
7 Da sprach ich als Prophet, wie mir befohlen war; und noch während ich
redete, hörte ich auf einmal ein Geräusch: Die Gebeine rückten zusammen,
Bein an Bein.

<<v8>>
8 Und als ich hinsah, waren plötzlich Sehnen auf ihnen und Fleisch umgab
sie und Haut überzog sie. Aber es war noch kein Geist in ihnen.

<<v9>>
9 Da sagte er zu mir: Rede als Prophet zum Geist, rede, Menschensohn,
sag zum Geist: So spricht Gott, der Herr: Geist, komm herbei von den
vier Winden! Hauch diese Erschlagenen an, damit sie lebendig werden.

<<v10>>
10 Da sprach ich als Prophet, wie er mir befohlen hatte, und es kam
Geist in sie. Sie wurden lebendig und standen auf - ein großes,
gewaltiges Heer. ^{[[#fn3][3]]}

<<v11>>
11 Er sagte zu mir: Menschensohn, diese Gebeine sind das ganze Haus
Israel. Jetzt sagt Israel: Ausgetrocknet sind unsere Gebeine, unsere
Hoffnung ist untergegangen, wir sind verloren.

<<v12>>
12 Deshalb tritt als Prophet auf und sag zu ihnen: So spricht Gott, der
Herr: Ich öffne eure Gräber und hole euch, mein Volk, aus euren Gräbern
herauf. Ich bringe euch zurück in das Land Israel.

<<v13>>
13 Wenn ich eure Gräber öffne und euch, mein Volk, aus euren Gräbern
heraufhole, dann werdet ihr erkennen, dass ich der Herr bin.

<<v14>>
14 Ich hauche euch meinen Geist ein, dann werdet ihr lebendig und ich
bringe euch wieder in euer Land. Dann werdet ihr erkennen, dass ich der
Herr bin. Ich habe gesprochen und ich führe es aus - Spruch des Herrn.
^{[[#fn4][4]]}\\
\\

<<v15>>
**** Eine weitere symbolische Handlung: Die Wiedervereinigung Israels
und Judas: 37,15-28
     :PROPERTIES:
     :CUSTOM_ID: eine-weitere-symbolische-handlung-die-wiedervereinigung-israels-und-judas-3715-28
     :END:
15 Das Wort des Herrn erging an mich:

<<v16>>
16 Du, Menschensohn, nimm dir ein Holz und schreib darauf: Juda und die
mit ihm verbündeten Israeliten. Dann nimm dir ein anderes Holz, und
schreib darauf: Josef [Holz Efraims] und das ganze mit ihm verbündete
Haus Israel.

<<v17>>
17 Dann füge beide zu einem einzigen Holz zusammen, sodass sie eins
werden in deiner Hand.

<<v18>>
18 Und wenn die Söhne deines Volkes dich fragen: Willst du uns nicht
erklären, was das bedeuten soll?,

<<v19>>
19 dann antworte ihnen: So spricht Gott, der Herr: Ich nehme das Holz
Josefs [das in der Hand Efraims ist] und der mit ihm verbündeten Stämme
Israels und lege es auf das Holz Judas. Ich mache sie zu einem einzigen
Holz und sie werden eins in meiner Hand.

<<v20>>
20 Die Hölzer, auf die du geschrieben hast, sollst du vor ihren Augen in
deiner Hand halten.

<<v21>>
21 Dann sag zu ihnen: So spricht Gott, der Herr: Ich hole die Israeliten
aus den Völkern heraus, zu denen sie gehen mussten; ich sammle sie von
allen Seiten und bringe sie in ihr Land. ^{[[#fn5][5]]}

<<v22>>
22 Ich mache sie in meinem Land, auf den Bergen Israels, zu einem
einzigen Volk. Sie sollen alle einen einzigen König haben. Sie werden
nicht länger zwei Völker sein und sich nie mehr in zwei Reiche teilen.
^{[[#fn6][6]][[#fn7][7]]}

<<v23>>
23 Sie werden sich nicht mehr unrein machen durch ihre Götzen und Gräuel
und durch all ihre Untaten. Ich befreie sie von aller Sünde, die sie in
ihrer Untreue begangen haben, und ich mache sie rein. Dann werden sie
mein Volk sein und ich werde ihr Gott sein. ^{[[#fn8][8]][[#fn9][9]]}

<<v24>>
24 Mein Knecht David wird ihr König sein und sie werden alle einen
einzigen Hirten haben. Sie werden nach meinen Rechtsvorschriften leben
und auf meine Gesetze achten und sie erfüllen.

<<v25>>
25 Sie werden in dem Land wohnen, das ich meinem Knecht Jakob gegeben
habe und in dem ihre Väter gewohnt haben. Sie und ihre Kinder und
Kindeskinder werden für immer darin wohnen und mein Knecht David wird
für alle Zeit ihr Fürst sein. ^{[[#fn10][10]][[#fn11][11]]}

<<v26>>
26 Ich schließe mit ihnen einen Friedensbund; es soll ein ewiger Bund
sein. Ich werde sie zahlreich machen. Ich werde mitten unter ihnen für
immer mein Heiligtum errichten ^{[[#fn12][12]][[#fn13][13]]}

<<v27>>
27 und bei ihnen wird meine Wohnung sein. Ich werde ihr Gott sein und
sie werden mein Volk sein. ^{[[#fn14][14]]}

<<v28>>
28 Wenn mein Heiligtum für alle Zeit in ihrer Mitte ist, dann werden die
Völker erkennen, dass ich der Herr bin, der Israel heiligt.
^{[[#fn15][15]]}\\
\\

^{[[#fnm1][1]]} ℘ 1,3; 3,22

^{[[#fnm2][2]]} ℘ Jes 26,19

^{[[#fnm3][3]]} ℘ Gen 2,7; Ps 104,30

^{[[#fnm4][4]]} ℘ 39,29

^{[[#fnm5][5]]} ℘ 34,13; 36,24

^{[[#fnm6][6]]} ℘ Jes 11,11.13; Ez 34,23

^{[[#fnm7][7]]} in meinem Land: ergänzt nach G.

^{[[#fnm8][8]]} ℘ 11,20

^{[[#fnm9][9]]} Sünde: Text korr.; vgl. G.

^{[[#fnm10][10]]} ℘ 28,25

^{[[#fnm11][11]]} ihre Väter: Text korr. nach G und S; H: eure Väter.

^{[[#fnm12][12]]} ℘ Jes 54,10

^{[[#fnm13][13]]} Text korr.; H hat zwei weitere Wörter, die kaum
ursprünglich sind.

^{[[#fnm14][14]]} ℘ 43,7; 11,20; Lev 26,11f

^{[[#fnm15][15]]} ℘ 36,23
