:PROPERTIES:
:ID:       49497596-5ac4-491c-9f6d-0842ea16c9c5
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_42.html][42]] [[file:Ez_43.html][43]] *44*
[[file:Ez_45.html][45]] [[file:Ez_46.html][46]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 44
  :PROPERTIES:
  :CUSTOM_ID: ez-44
  :END:

<<verses>>

<<v1>>
**** Das verschlossene Tor: 44,1-3
     :PROPERTIES:
     :CUSTOM_ID: das-verschlossene-tor-441-3
     :END:
1 Dann führte er mich zum äußeren Osttor des Heiligtums zurück. Es war
geschlossen.

<<v2>>
2 Da sagte der Herr zu mir: Dieses Tor soll geschlossen bleiben, es soll
nie geöffnet werden, niemand darf hindurchgehen; denn der Herr, der Gott
Israels, ist durch dieses Tor eingezogen; deshalb bleibt es geschlossen.
^{[[#fn1][1]]}

<<v3>>
3 Nur der Fürst darf, weil er der Fürst ist, sich dort niedersetzen, um
vor den Augen des Herrn die Opfermahlzeit abzuhalten. Dabei soll er von
der Vorhalle des Tores aus eintreten und auf dem gleichen Weg wieder
hinausgehen. ^{[[#fn2][2]]}\\
\\

<<v4>>
*** Die Vorschriften für den Kult und die Verteilung des Landes: 44,4 -
48,35
    :PROPERTIES:
    :CUSTOM_ID: die-vorschriften-für-den-kult-und-die-verteilung-des-landes-444---4835
    :END:
**** Die Leviten und Priester: 44,4-31
     :PROPERTIES:
     :CUSTOM_ID: die-leviten-und-priester-444-31
     :END:
4 Dann führte er mich zum Nordtor, zur Vorderseite des Tempels. Ich sah:
Die Herrlichkeit des Herrn erfüllte den Tempel des Herrn. Und ich fiel
nieder auf mein Gesicht.

<<v5>>
5 Der Herr sagte zu mir: Menschensohn, gib Acht, öffne deine Augen und
deine Ohren und hör auf alles, was ich zu dir sage, vernimm alle Gesetze
und Anweisungen über den Tempel des Herrn! Achte an allen Eingängen des
Heiligtums darauf, wer den Tempel betritt.

<<v6>>
6 Sag zu dem widerspenstigen Haus Israel: So spricht Gott, der Herr:
Hört endlich auf mit all euren Gräueltaten, ihr vom Haus Israel!

<<v7>>
7 Fremde, die unbeschnitten sind am Herzen und unbeschnitten am Körper,
sie habt ihr eintreten lassen, sie waren in meinem Heiligtum und haben
meinen Tempel entweiht, wenn ihr mir meine Opferspeise, Fett und Blut,
dargebracht habt. So habt ihr mit all euren Gräueltaten meinen Bund
gebrochen. ^{[[#fn3][3]]}

<<v8>>
8 Ihr wolltet den Dienst in meinem Heiligtum nicht verrichten, sondern
ihr habt sie an eurer Stelle den Dienst in meinem Heiligtum verrichten
lassen.

<<v9>>
9 So spricht Gott, der Herr: Kein Fremder, der unbeschnitten ist am
Herzen und unbeschnitten am Körper, darf mein Heiligtum betreten, keiner
von all den Fremden, die bei den Israeliten leben,

<<v10>>
10 sondern nur die Leviten. Doch weil sie mich verlassen haben, als
Israel in die Irre ging, und weil sie statt mir ihren Götzen gefolgt
sind, müssen sie die Folgen ihrer Schuld tragen:

<<v11>>
11 Sie dürfen in meinem Heiligtum nur Wächter an den Tempeltoren und
Tempeldiener sein; sie dürfen (die Tiere für) das Brandopfer und das
Schlachtopfer des Volkes schlachten und sollen vor den Leuten
bereitstehen, um ihnen zu dienen.

<<v12>>
12 Weil sie ihnen bei ihrem Götzendienst geholfen haben und für das Haus
Israel der Anlass wurden, in Schuld zu fallen, darum habe ich meine Hand
gegen sie erhoben - Spruch Gottes, des Herrn -; sie müssen die Folgen
ihrer Schuld tragen.

<<v13>>
13 Sie dürfen nicht mehr vor mich hintreten, um mir als Priester zu
dienen und alle meine heiligen Geräte und hochheiligen Opfer zu
berühren. Sie müssen ihre Schande und die Folgen der Gräueltaten tragen,
die sie begangen haben.

<<v14>>
14 Ich setze sie als Tempeldiener ein, damit sie alles erledigen, was im
Tempel zu tun ist.

<<v15>>
15 Die levitischen Priester, die Nachkommen Zadoks, die mir in meinem
Heiligtum treu gedient haben, als die Israeliten mich verließen und in
die Irre gingen, sie sollen vor mich hintreten und mir dienen, sie
sollen vor mir stehen, um mir Fett und Blut darzubringen - Spruch
Gottes, des Herrn. ^{[[#fn4][4]]}

<<v16>>
16 Sie dürfen in mein Heiligtum kommen und an meinen Tisch herantreten,
um mir zu dienen; sie sollen meinen Dienst verrichten.

<<v17>>
17 Wenn sie durch die Tore des Innenhofs hineingehen, sollen sie
Leinengewänder tragen. Sie dürfen nichts Wollenes tragen, wenn sie in
den Toren des Innenhofs und im Tempel Dienst tun.

<<v18>>
18 Sie sollen einen Kopfbund aus Leinen aufsetzen und leinene Hosen
anziehen; sie sollen keine Kleider tragen, in denen man schwitzt.
^{[[#fn5][5]][[#fn6][6]]}

<<v19>>
19 Wenn sie in den Vorhof zum Volk hinausgehen, sollen sie die
Leinengewänder ausziehen, in denen sie Dienst getan haben; sie sollen
sie in die heiligen Räume legen und andere Kleider anziehen, damit sie
das Volk nicht durch ihre Leinengewänder heilig machen. ^{[[#fn7][7]]}

<<v20>>
20 Sie sollen weder ihren Kopf kahl scheren, noch ihre Haare lang
herabhängen lassen, sondern sie sollen ihr Haar kurz schneiden.
^{[[#fn8][8]]}

<<v21>>
21 Ein Priester darf keinen Wein trinken, wenn er den Innenhof betreten
muss. ^{[[#fn9][9]]}

<<v22>>
22 Die Priester dürfen keine Witwe und keine verstoßene Frau heiraten,
sondern nur Jungfrauen aus der Nachkommenschaft des Hauses Israel. Eine
Witwe aber, die mit einem Priester verheiratet war, dürfen sie zur Frau
nehmen. ^{[[#fn10][10]]}

<<v23>>
23 Sie sollen mein Volk über den Unterschied zwischen heilig und nicht
heilig belehren und ihnen den Unterschied zwischen unrein und rein
deutlich machen. ^{[[#fn11][11]]}

<<v24>>
24 Bei einem Rechtsstreit sind sie die Richter; nach meinen
Rechtsvorschriften sollen sie ihn entscheiden. An allen meinen Festen
sollen sie auf meine Weisungen und meine Gesetze achten und sie sollen
meine Sabbat-Tage heilig halten. ^{[[#fn12][12]]}

<<v25>>
25 Einem Toten sollen sie sich nicht nähern; denn sie werden dadurch
unrein. Nur beim Tod von Vater und Mutter, Sohn und Tochter, Bruder und
unverheirateter Schwester dürfen sie sich unrein machen;
^{[[#fn13][13]]}

<<v26>>
26 wenn der Priester dann wieder rein geworden ist, soll er noch sieben
Tage warten.

<<v27>>
27 Wenn er danach wieder in den Innenhof des Heiligtums geht, um dort
Dienst zu tun, dann soll er ein Sündopfer für sich darbringen - Spruch
Gottes, des Herrn.

<<v28>>
28 Erbbesitz dürfen sie nicht haben; ich bin ihr Erbbesitz. Auch
Eigentum sollt ihr ihnen in Israel nicht geben; ich bin ihr Eigentum.
^{[[#fn14][14]][[#fn15][15]]}

<<v29>>
29 Sie dürfen das Speise-, Sünd- und Schuldopfer essen. Jede Gabe, die
man in Israel Gott weiht, gehört ihnen. ^{[[#fn16][16]]}

<<v30>>
30 Das Beste von allen Erstlingsopfern, all eure Abgaben, die ihr
entrichten müsst, gehören den Priestern; auch das Beste von dem, was ihr
backt, sollt ihr dem Priester geben, damit ihr Segen über eure Häuser
bringt.

<<v31>>
31 Verendete und (von Raubtieren) zerrissene Vögel und Tiere dürfen die
Priester nicht essen. ^{[[#fn17][17]]}\\
\\

^{[[#fnm1][1]]} ℘ Ps 24,7

^{[[#fnm2][2]]} ℘ 46,2

^{[[#fnm3][3]]} ℘ Jes 52,1; Jer 9,25

^{[[#fnm4][4]]} ℘ 40,46

^{[[#fnm5][5]]} ℘ Lev 6,3f; 16,4

^{[[#fnm6][6]]} Schweiß macht demnach wie andere Ausscheidungen (vgl.
Dtn 23,12-14) unrein und kultunfähig.

^{[[#fnm7][7]]} ℘ 46,20

^{[[#fnm8][8]]} ℘ Lev 21,5; 19,27

^{[[#fnm9][9]]} ℘ Lev 10,9

^{[[#fnm10][10]]} ℘ Lev 21,7.13f

^{[[#fnm11][11]]} ℘ 22,26; Lev 10,10

^{[[#fnm12][12]]} ℘ Dtn 17,8f

^{[[#fnm13][13]]} ℘ Lev 21,1-4

^{[[#fnm14][14]]} ℘ Num 18,20-24; Dtn 18,1f

^{[[#fnm15][15]]} nicht (haben): Text korr. nach Vg.

^{[[#fnm16][16]]} ℘ (29-30) Ex 25,2; Num 15,20; Neh 10,38

^{[[#fnm17][17]]} ℘ Lev 22,8
