:PROPERTIES:
:ID:       0d9bacb3-a9de-4cbb-a293-9fc530a343bb
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_44.html][44]] [[file:Ez_45.html][45]] *46*
[[file:Ez_47.html][47]] [[file:Ez_48.html][48]]

--------------

* Ez 46
  :PROPERTIES:
  :CUSTOM_ID: ez-46
  :END:

<<verses>>

<<v1>>
**** Die Opfer: 46,1-15
     :PROPERTIES:
     :CUSTOM_ID: die-opfer-461-15
     :END:
1 So spricht Gott, der Herr: Das Osttor des Innenhofs soll an den sechs
Werktagen geschlossen bleiben, nur am Sabbat und am Neumondtag soll es
geöffnet werden.

<<v2>>
2 Der Fürst soll von außen her durch die Vorhalle den Torbau betreten
und sich an den Torpfosten stellen. Dann sollen die Priester sein Brand-
und Heilsopfer darbringen, er aber soll sich an der Schwelle des Tors
niederwerfen und wieder hinausgehen. Das Tor soll erst am Abend
geschlossen werden. ^{[[#fn1][1]]}

<<v3>>
3 Die Bürger des Landes sollen sich an den Sabbat- und Neumond-Tagen am
Eingang dieses Tors ebenfalls vor dem Herrn niederwerfen.

<<v4>>
4 Das Brandopfer, das der Fürst dem Herrn darbringen lässt, soll am
Sabbat-Tag aus sechs Lämmern und einem Widder bestehen, die ohne Fehler
sind. ^{[[#fn2][2]]}

<<v5>>
5 Zu dem Widder gehört ein Speiseopfer von einem Efa Mehl, zu den
Lämmern ein Speiseopfer, dessen Menge er selbst bestimmen kann, dazu ein
Hin Öl je Efa Mehl. ^{[[#fn3][3]]}

<<v6>>
6 Am Neumond-Tag sollen es ein junger Stier, sechs Lämmer und ein Widder
sein, die alle ohne Fehler sind.

<<v7>>
7 Zu dem Stier und zu dem Widder soll er je ein Efa Mehl als Speiseopfer
besorgen, außerdem zu den Lämmern so viel, wie er gerade zur Verfügung
hat, und dazu je Efa Mehl ein Hin Öl.

<<v8>>
8 Wenn der Fürst den Torbau betritt, soll er ihn durch die Vorhalle
betreten und auf dem gleichen Weg muss er wieder hinausgehen.

<<v9>>
9 Wenn aber das Volk an den Festen vor den Herrn tritt, dann soll der,
der durch das Nordtor gekommen ist, um (den Herrn) anzubeten, durch das
Südtor hinausgehen, und wer durch das Südtor gekommen ist, soll durch
das Nordtor hinausgehen. Niemand soll durch das Tor wieder hinausgehen,
durch das er gekommen ist, sondern jeder soll durch das
gegenüberliegende Tor hinausgehen. ^{[[#fn4][4]]}

<<v10>>
10 Der Fürst soll mitten unter ihnen sein; wenn sie hineingehen, soll
auch er hineingehen, und wenn sie hinausgehen, soll auch er hinausgehen.

<<v11>>
11 An den Fest- und Feiertagen gehört zu dem Stier und zu dem Widder ein
Speiseopfer von je einem Efa Mehl und zu den Lämmern ein Speiseopfer,
dessen Menge er selbst bestimmen kann, dazu ein Hin Öl je Efa Mehl.

<<v12>>
12 Wenn der Fürst dem Herrn von sich aus ein Brandopfer oder ein
Heilsopfer darbringen lassen will, soll man für ihn das Osttor öffnen.
Dann soll er sein Brand- und Heilsopfer genauso darbringen lassen wie am
Sabbat. Daraufhin soll er hinausgehen, und wenn er hinausgegangen ist,
soll man das Tor schließen.

<<v13>>
13 Täglich sollst du dem Herrn ein einjähriges Lamm, das ohne Fehler
ist, als Brandopfer darbringen, und zwar jeden Morgen. ^{[[#fn5][5]]}

<<v14>>
14 Dazu sollst du als Speiseopfer jeden Morgen ein Sechstel Efa Mehl und
ein Drittel Hin Öl herrichten, mit dem das Mehl besprengt wird. Das soll
das Speiseopfer für den Herrn sein. Diese Vorschrift über das tägliche
Opfer soll für immer gelten.

<<v15>>
15 Bringt also jeden Morgen das Lamm, das Speiseopfer und das Öl als das
tägliche Brandopfer dar!\\
\\

<<v16>>
**** Der Besitz des Fürsten: 46,16-18
     :PROPERTIES:
     :CUSTOM_ID: der-besitz-des-fürsten-4616-18
     :END:
16 So spricht Gott, der Herr: Wenn der Fürst einem seiner Söhne etwas
von seinem Erbbesitz schenkt, gehört es seinen Söhnen; es ist ihr
Eigentum und sie können es weitervererben. ^{[[#fn6][6]]}

<<v17>>
17 Wenn er aber etwas von seinem Erbbesitz einem seiner Diener schenkt,
gehört es diesem nur bis zum nächsten Erlassjahr; dann fällt es an den
Fürsten zurück. Nur seine Söhne dürfen behalten, was er ihnen von seinem
Erbbesitz geschenkt hat.

<<v18>>
18 Vom Erbbesitz des Volkes darf der Fürst nichts nehmen; er darf sie
nicht mit Gewalt von ihrem Eigentum verdrängen. Wenn er seinen Söhnen
etwas vererben will, muss er es von seinem Eigentum nehmen, damit die
Angehörigen meines Volkes nicht von ihrem Eigentum vertrieben werden.\\
\\

<<v19>>
**** Die Opferküchen des Tempels: 46,19-24
     :PROPERTIES:
     :CUSTOM_ID: die-opferküchen-des-tempels-4619-24
     :END:
19 Dann brachte er mich durch den Eingang auf der Torseite zu den
heiligen Priesterräumen im Norden (des Tempels), und zwar zu einer
Stelle am äußersten Ende (der Räume) im Westen. ^{[[#fn7][7]]}

<<v20>>
20 Dort sagte er zu mir: Das ist die Stelle, wo die Priester das Schuld-
und das Sündopfer kochen und das Speiseopfer backen, damit sie es nicht
in den Vorhof hinausbringen müssen und dadurch das Volk heiligen.

<<v21>>
21 Dann führte er mich in den Vorhof hinaus und brachte mich zu den vier
Ecken des Vorhofs. Und an jeder Ecke des Vorhofs war noch ein Hof.

<<v22>>
22 An allen vier Ecken des Vorhofs waren kleine Höfe, vierzig Ellen lang
und dreißig Ellen breit. Alle vier Höfe an den Ecken hatten das gleiche
Maß. ^{[[#fn8][8]]}

<<v23>>
23 Und ringsum lief in den vier Höfen eine Steinmauer und unten an den
Steinmauern waren ringsum Kochstellen angelegt.

<<v24>>
24 Da sagte er zu mir: Das sind die Küchen, wo die Tempeldiener das
Schlachtopfer des Volkes kochen.\\
\\

^{[[#fnm1][1]]} ℘ 44,3

^{[[#fnm2][2]]} ℘ Num 28,9f

^{[[#fnm3][3]]} 5.11: dessen Menge (er bestimmen kann): sinngemäß
übersetzt.

^{[[#fnm4][4]]} ℘ Ex 23,14-17

^{[[#fnm5][5]]} ℘ Ex 29,38-42; Num 28,3

^{[[#fnm6][6]]} etwas von seinem Erbbesitz: Text korr.; vgl. G, V. 17.

^{[[#fnm7][7]]} zu den heiligen Priesterräumen: Text korr.; vgl. die
alten Übersetzungen.

^{[[#fnm8][8]]} kleine: Text korr. nach G.
