:PROPERTIES:
:ID:       33faefdc-b855-46d7-9376-bb022b523fe0
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_41.html][41]] [[file:Ez_42.html][42]] *43*
[[file:Ez_44.html][44]] [[file:Ez_45.html][45]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 43
  :PROPERTIES:
  :CUSTOM_ID: ez-43
  :END:

<<verses>>

<<v1>>
**** Der Einzug des Herrn in den Tempel: 43,1-12
     :PROPERTIES:
     :CUSTOM_ID: der-einzug-des-herrn-in-den-tempel-431-12
     :END:
1 Dann führte er mich zu einem der Tore, dem Tor, das im Osten lag.

<<v2>>
2 Da sah ich, wie die Herrlichkeit des Gottes Israels aus dem Osten
herankam. Ihr Rauschen war wie das Rauschen gewaltiger Wassermassen und
die Erde leuchtete auf von seiner Herrlichkeit. ^{[[#fn1][1]]}

<<v3>>
3 Die Erscheinung, die ich sah, war wie die Erscheinung, die ich damals
sah, als er kam, um die Stadt zu vernichten, und wie die Erscheinung,
die ich am Fluss Kebar gesehen hatte. Da fiel ich nieder auf mein
Gesicht. ^{[[#fn2][2]][[#fn3][3]]}

<<v4>>
4 Und die Herrlichkeit des Herrn zog in den Tempel ein durch das Tor,
das im Osten lag. ^{[[#fn4][4]]}

<<v5>>
5 Der Geist hob mich empor und brachte mich in den Innenhof. Und die
Herrlichkeit des Herrn erfüllte den Tempel.

<<v6>>
6 Dann hörte ich vom Tempel her, während der Mann neben mir stand,
einen, der mit mir redete;

<<v7>>
7 er sagte zu mir: Menschensohn, das ist der Ort, wo mein Thron steht,
und der Ort, wo meine Füße ruhen; hier will ich für immer mitten unter
den Israeliten wohnen. Das Haus Israel aber und seine Könige sollen
meinen heiligen Namen nie mehr beflecken mit ihrer Unzucht und mit den
Leichen ihrer Könige [wenn sie tot sind]. ^{[[#fn5][5]]}

<<v8>>
8 Sie legten ihre Schwelle neben meine Schwelle und setzten ihre
Türpfosten neben meine Türpfosten, sodass zwischen mir und ihnen nur
eine Wand war. So befleckten sie meinen heiligen Namen durch die
Gräueltaten, die sie begingen, und ich musste sie in meinem Zorn
vernichten.

<<v9>>
9 Jetzt aber sollen sie ihre Unzucht und die Leichen ihrer Könige von
mir fern halten, sodass ich für immer mitten unter ihnen wohnen kann.

<<v10>>
10 Du, Menschensohn, berichte dem Haus Israel über den Tempel, damit sie
sich wegen ihrer bösen Taten schämen. Sie sollen den Entwurf des Tempels
kennen lernen. ^{[[#fn6][6]]}

<<v11>>
11 Wenn sie sich all dessen schämen, was sie getan haben, dann mach
ihnen den Plan des Tempels bekannt, seine Einrichtung, seine Ausgänge
und Eingänge und seinen ganzen Plan, alle ihn betreffenden Gesetze
[meine ganzen Pläne] und alle ihn betreffenden Anweisungen. Zeichne
alles vor ihren Augen auf! Sie sollen darauf achten, dass sie seinen
ganzen Plan ausführen und alle ihn betreffenden Gesetze befolgen.

<<v12>>
12 Das ist meine Anweisung für den Tempelbezirk. Das ganze Gebiet auf
dem Gipfel des Berges ringsum ist hochheiliger Boden. [Siehe, das ist
die Anweisung für den Tempelbezirk.]\\
\\

<<v13>>
**** Der Altar im Innenhof und die Altarweihe: 43,13-27
     :PROPERTIES:
     :CUSTOM_ID: der-altar-im-innenhof-und-die-altarweihe-4313-27
     :END:
13 Das waren die Maße des Altars, gemessen in Ellen, die Elle zu einer
gewöhnlichen Elle und einer Handbreit gerechnet: Der Graben (um den
Altar) war eine Elle tief und eine Elle breit und die gemauerte
Einfassung an seinem Rand war eine Spanne breit. Die Höhe des Altars
maß: ^{[[#fn7][7]]}

<<v14>>
14 vom Boden des Grabens bis zur unteren Stufe zwei Ellen; die Stufe war
eine Elle breit; auf diese niedrige Stufe folgte eine höhere Stufe von
vier Ellen, die oben wieder eine Elle zurücksprang. ^{[[#fn8][8]]}

<<v15>>
15 Der (darauf folgende) Opferherd war vier Ellen hoch und an dem
Opferherd ragten vier Hörner empor.

<<v16>>
16 Der Opferherd hatte eine Länge von zwölf Ellen und eine Breite von
zwölf Ellen; er war quadratisch.

<<v17>>
17 Auch die (mittlere) Stufe war quadratisch, vierzehn Ellen lang und
vierzehn Ellen breit. Rings um die untere Stufe lief eine gemauerte
Einfassung von einer halben Elle (Höhe). Der Graben, der sie umgab, maß
ringsum eine Elle. Im Osten führte eine Treppe zum Altar hinauf.
^{[[#fn9][9]]}

<<v18>>
18 Dann sagte er zu mir: Menschensohn, so spricht Gott, der Herr: Das
sind die Gesetze für den Tag, an dem der Altar fertig gestellt wird,
damit man Brandopfer auf ihm darbringen und Blut auf ihn sprengen kann:
^{[[#fn10][10]]}

<<v19>>
19 Du sollst den levitischen Priestern, den Nachkommen Zadoks, die vor
mich hintreten dürfen, um mir zu dienen - Spruch Gottes, des Herrn -,
einen jungen Stier zum Sündopfer geben. ^{[[#fn11][11]]}

<<v20>>
20 Dann sollst du etwas von seinem Blut nehmen und es auf die vier
Hörner und auf die vier Ecken der (mittleren) Stufe sowie ringsum auf
die gemauerte Einfassung tun. So sollst du den Altar entsündigen und
entsühnen.

<<v21>>
21 Dann sollst du den Stier des Sündopfers nehmen und man soll ihn auf
dem dafür vorgesehenen Platz beim Tempel außerhalb des Heiligtums
verbrennen.

<<v22>>
22 Am zweiten Tag sollst du einen Ziegenbock, der ohne Fehler ist, als
Sündopfer darbringen und man soll den Altar damit entsündigen, wie man
ihn mit dem Stier entsündigt hat.

<<v23>>
23 Wenn du die Entsündigung vollzogen hast, sollst du einen jungen
Stier, der ohne Fehler ist, sowie einen Widder aus der Herde, der ohne
Fehler ist, darbringen.

<<v24>>
24 Du sollst beide vor den Herrn bringen und die Priester sollen sie mit
Salz bestreuen und dem Herrn als Brandopfer darbringen.

<<v25>>
25 Sieben Tage lang sollst du täglich einen Bock als Sündopfer
darbringen und man soll (täglich) einen jungen Stier und einen Widder
aus der Herde - Tiere ohne Fehler - darbringen.

<<v26>>
26 Sieben Tage lang soll man den Altar entsühnen, rein machen und
einweihen.

<<v27>>
27 Man soll diese Tage genau einhalten. Vom achten Tag an sollen dann
die Priester auf dem Altar eure Brand- und Heilsopfer darbringen. Dann
will ich euch gnädig sein - Spruch Gottes, des Herrn.\\
\\

^{[[#fnm1][1]]} ℘ 1,28; Offb 1,15

^{[[#fnm2][2]]} ℘ 8 - 11; 1,3

^{[[#fnm3][3]]} als er kam: Text korr. nach einigen H-Handschriften und
Vg; H: als ich kam.

^{[[#fnm4][4]]} ℘ Ex 40,34; 1 Kön 8,10f

^{[[#fnm5][5]]} ℘ Ps 132,7f; Klgl 2,1; Ez 37,26f

^{[[#fnm6][6]]} kennen lernen, wörtlich: ausmessen.

^{[[#fnm7][7]]} ℘ Ex 27,1-8; 1 Kön 8,64

^{[[#fnm8][8]]} die oben . . . zurücksprang: H wörtlich: und die Breite
eine Elle.

^{[[#fnm9][9]]} Text ergänzt; vermutlich ist ein Satz ausgefallen.

^{[[#fnm10][10]]} ℘ Ex 29,36f

^{[[#fnm11][11]]} ℘ 40,46; 44,15
