:PROPERTIES:
:ID:       37dcc0d5-a258-4aa1-9fdc-e17e6dbaada8
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_43.html][43]] [[file:Ez_44.html][44]] *45*
[[file:Ez_46.html][46]] [[file:Ez_47.html][47]] [[file:Ez_48.html][48]]

--------------

* Ez 45
  :PROPERTIES:
  :CUSTOM_ID: ez-45
  :END:

<<verses>>

<<v1>>
**** Die Aufteilung des Kerngebietes: 45,1-8
     :PROPERTIES:
     :CUSTOM_ID: die-aufteilung-des-kerngebietes-451-8
     :END:
1 Wenn ihr das Land durch das Los verteilt, sollt ihr ein Stück von
fünfundzwanzigtausend Ellen Länge und zwanzigtausend Ellen Breite als
eine Abgabe für den Herrn zurückbehalten. Es soll in seinem ganzen
Umfang heilig sein. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Davon gehört um den Tempel herum ein Quadrat von fünfhundert mal
fünfhundert Ellen dem Heiligtum, dazu ringsum fünfzig Ellen unbestelltes
Land.

<<v3>>
3 Von diesem abgemessenen Stück Land sollt ihr wiederum ein Stück von
fünfundzwanzigtausend Ellen Länge und zehntausend Ellen Breite abmessen,
auf dem das hochheilige Heiligtum stehen soll.

<<v4>>
4 Das ist das heilige Gebiet des Landes und es soll den Priestern
gehören, die den Dienst im Heiligtum verrichten und sich beim
Gottesdienst dem Herrn nähern dürfen. Es ist der Platz für ihre Häuser
und die Weidefläche für ihre Herden. ^{[[#fn3][3]]}

<<v5>>
5 Das (übrige) Stück von fünfundzwanzigtausend Ellen Länge und
zehntausend Ellen Breite soll den Leviten gehören, die den Tempeldienst
verrichten. Es ist ihr Eigentum; dort können sie ihre Städte bauen und
darin wohnen.

<<v6>>
6 Als Eigentum der Stadt sollt ihr ein (weiteres) Stück von fünftausend
Ellen Breite und fünfundzwanzigtausend Ellen Länge abmessen, genauso
lang wie die heilige Abgabe. Dieses Stück gehört dem ganzen Haus Israel.

<<v7>>
7 Dem Fürsten soll auf beiden Seiten der heiligen Abgabe und des
Eigentums der Stadt, im Westen und Osten, ein Gebiet gehören, das an die
heilige Abgabe und das Eigentum der Stadt angrenzt und in der Länge
einem der Stammesanteile von der Westgrenze bis zur Ostgrenze

<<v8>>
8 des Landes entspricht. Es gehört dem Fürsten als Eigentum in Israel.
Meine Fürsten werden mein Volk nicht mehr unterdrücken, sondern das Land
dem Haus Israel und seinen Stämmen überlassen.\\
\\

<<v9>>
**** Mahnung an die Fürsten: 45,9-17
     :PROPERTIES:
     :CUSTOM_ID: mahnung-an-die-fürsten-459-17
     :END:
9 So spricht Gott, der Herr: Genug, ihr Fürsten Israels! Beseitigt
Gewalt und Unterdrückung! Sorgt für Recht und Gerechtigkeit! Hört auf,
mein Volk von seinem Grund und Boden zu vertreiben - Spruch Gottes, des
Herrn. ^{[[#fn4][4]]}

<<v10>>
10 Verwendet richtige Waagen, richtiges Efa und richtiges Bat!
^{[[#fn5][5]]}

<<v11>>
11 Das Efa und das Bat sollen das gleiche Maß haben; das Bat soll der
zehnte Teil eines Hómer sein und ebenso das Efa der zehnte Teil eines
Hómer; nach dem Hómer sollen sich die anderen Maße richten.

<<v12>>
12 Ein Schekel soll bei euch zwanzig Gera entsprechen. Zehn Schekel sind
ein Fünftel einer Mine, fünf Schekel ein Zehntel; fünfzig Schekel sind
eine ganze Mine. ^{[[#fn6][6]]}

<<v13>>
13 Folgende Abgaben sollt ihr erheben: von jedem Hómer Weizen ein
Sechstel Efa und ebenso von jedem Hómer Gerste ein Sechstel Efa;

<<v14>>
14 und für das Öl gilt: von jedem Kor ein Zehntel Bat; das Bat ist das
Ölmaß; zehn Bat entsprechen einem Hómer und zehn Bat entsprechen auch
einem Kor; ^{[[#fn7][7]]}

<<v15>>
15 ferner aus jeder Herde ein Schaf auf je zweihundert Tiere vom
Viehbesitz Israels. (Diese Abgabe ist) für die Speise-, Brand- und
Heilsopfer (bestimmt), die euch entsühnen sollen - Spruch Gottes, des
Herrn. ^{[[#fn8][8]]}

<<v16>>
16 Das ganze Volk im Land hat diese Abgaben an den Fürsten von Israel zu
entrichten.

<<v17>>
17 Der Fürst aber hat an allen Feiertagen des Hauses Israel, an den
Festen und an den Neumond- und Sabbat-Tagen für Brandopfer, Speiseopfer
und Trankopfer zu sorgen. Er veranstaltet die Sünd-, Speise-, Brand- und
Heilsopfer, die das Haus Israel entsühnen sollen. ^{[[#fn9][9]]}\\
\\

<<v18>>
**** Die großen Feste: 45,18-25
     :PROPERTIES:
     :CUSTOM_ID: die-großen-feste-4518-25
     :END:
18 So spricht Gott, der Herr: Am ersten Tag des ersten Monats sollst du
einen jungen Stier nehmen, der ohne Fehler ist, und das Heiligtum
entsündigen.

<<v19>>
19 Der Priester nimmt etwas Blut von dem Sündopfer und bestreicht damit
die Türpfosten des Tempels und die vier Ecken der (mittleren) Stufe des
Altars und die Türpfosten des Tors zum Innenhof.

<<v20>>
20 Dasselbe sollst du am siebten Tag des Monats tun für die, die sich
aus Versehen oder aus Unwissenheit verfehlt haben. So sollt ihr den
Tempel entsühnen. ^{[[#fn10][10]]}

<<v21>>
21 Am vierzehnten Tag des ersten Monats sollt ihr das Pascha feiern, ein
Fest von sieben Tagen. Da soll man ungesäuerte Brote essen.
^{[[#fn11][11]][[#fn12][12]]}

<<v22>>
22 Der Fürst soll an diesem Tag für sich und für das ganze Volk im Land
einen Stier zum Sündopfer bereitstellen. ^{[[#fn13][13]]}

<<v23>>
23 An den sieben Festtagen soll er als Brandopfer für den Herrn sieben
Stiere und sieben Widder, die ohne Fehler sind, bereitstellen, und zwar
an jedem der sieben Tage, dazu täglich einen Ziegenbock als Sündopfer.
^{[[#fn14][14]]}

<<v24>>
24 Für das Speiseopfer soll er ein Efa Mehl je Stier und ein Efa Mehl je
Widder bereitstellen, dazu je Efa Mehl ein Hin Öl.

<<v25>>
25 Genau dasselbe soll er sieben Tage lang mit dem Sünd-, Brand- und
Speiseopfer und mit dem Öl an dem Fest machen, das am fünfzehnten Tag
des siebten Monats beginnt. ^{[[#fn15][15]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-8) 48,8-20

^{[[#fnm2][2]]} zwanzigtausend: Text korr. nach G; H: zehntausend.

^{[[#fnm3][3]]} die Weideflächen für ihre Herden: Text korr.; vgl. G und
die aramäische Übersetzung; H: ein Heiligtum zum Heiligtum.

^{[[#fnm4][4]]} ℘ Jer 21,11f; 22,3f; Mi 3,1-3

^{[[#fnm5][5]]} ℘ (10-11) Lev 19,35f; Dtn 25,13-15

^{[[#fnm6][6]]} fünfzig: Text korr. nach G; H: fünf.

^{[[#fnm7][7]]} einem Kor: Text korr. nach Vg.

^{[[#fnm8][8]]} vom Viehbesitz: Text korr.

^{[[#fnm9][9]]} ℘ Lev 1,3; 2,1; 3,1

^{[[#fnm10][10]]} ℘ Lev 5,17f

^{[[#fnm11][11]]} ℘ Lev 23,5

^{[[#fnm12][12]]} sieben: Text korr. nach den alten Übersetzungen.

^{[[#fnm13][13]]} ℘ Lev 4,22

^{[[#fnm14][14]]} ℘ (23-24) Num 28,17-23

^{[[#fnm15][15]]} ℘ Num 15,4-12; Lev 23,34; Ex 23,14
