:PROPERTIES:
:ID:       1cfa6c47-4ef1-4136-990b-e2d2a9b07678
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]]
[[file:Ez_2.html][2]] [[file:Ez_3.html][3]] *4* [[file:Ez_5.html][5]]
[[file:Ez_6.html][6]] ... [[file:Ez_48.html][48]]

--------------

* Ez 4
  :PROPERTIES:
  :CUSTOM_ID: ez-4
  :END:

<<verses>>

<<v1>>
** Die Drohsprüche gegen Juda und Jerusalem: 4,1 - 24,27
   :PROPERTIES:
   :CUSTOM_ID: die-drohsprüche-gegen-juda-und-jerusalem-41---2427
   :END:
*** Symbolische Handlungen: 4,1 - 5,17
    :PROPERTIES:
    :CUSTOM_ID: symbolische-handlungen-41---517
    :END:
**** Die Belagerung Jerusalems: 4,1-3
     :PROPERTIES:
     :CUSTOM_ID: die-belagerung-jerusalems-41-3
     :END:
1 Du, Menschensohn, nimm dir einen Lehmziegel, leg ihn vor dich hin und
ritze eine Stadt darauf ein [nämlich Jerusalem]! ^{[[#fn1][1]]}

<<v2>>
2 Belagere sie; bau ihr gegenüber einen Belagerungswall; schütte einen
Damm gegen sie auf; leg vor ihr ein Truppenlager an und stell gegen sie
ringsum Sturmböcke auf! ^{[[#fn2][2]]}

<<v3>>
3 Nimm eine Eisenplatte und stell sie als eiserne Mauer zwischen dich
und die Stadt! Richte dein Gesicht auf die Stadt: Nun ist sie belagert
und du belagerst sie. Das ist ein (warnendes) Zeichen für das Haus
Israel.\\
\\

<<v4>>
**** Die Dauer der Verbannung: 4,4-8
     :PROPERTIES:
     :CUSTOM_ID: die-dauer-der-verbannung-44-8
     :END:
4 Du, leg dich auf deine linke Seite! Dann lege ich die Schuld des
Hauses Israel auf dich. So viele Tage, wie du auf dieser Seite liegst,
trägst du ihre Schuld. ^{[[#fn3][3]]}

<<v5>>
5 Und ich setze für dich fest: So viele Jahre, wie die Schuld des Hauses
Israel dauert, so viele Tage sollst du ihre Schuld tragen:
dreihundertneunzig Tage. ^{[[#fn4][4]]}

<<v6>>
6 Wenn du diese Zeit beendet hast, leg dich auf die andere, die rechte
Seite und trag vierzig Tage lang die Schuld des Hauses Juda: einen Tag
für jedes Jahr; so setze ich es für dich fest. ^{[[#fn5][5]]}

<<v7>>
7 Dann sollst du dein Gesicht unbeweglich auf das belagerte Jerusalem
richten und mit erhobenem Arm gegen die Stadt weissagen.

<<v8>>
8 Ich aber lege dir Stricke an, sodass du dich nicht von einer Seite auf
die andere drehen kannst, so lange, bis du die Tage der Belagerung
beendet hast. ^{[[#fn6][6]]}\\
\\

<<v9>>
**** Hungersnot und Unreinheit: 4,9-17
     :PROPERTIES:
     :CUSTOM_ID: hungersnot-und-unreinheit-49-17
     :END:
9 Du, nimm dir Weizen, Gerste, Bohnen, Linsen, Hirse und Dinkel; tu sie
zusammen in ein Gefäß und mach dir Brot daraus! Solange du auf der Seite
liegst, dreihundertneunzig Tage lang, sollst du davon essen.

<<v10>>
10 Das Brot, das du isst, soll genau abgewogen sein, zwanzig Schekel am
Tag; davon sollst du von Zeit zu Zeit essen. ^{[[#fn7][7]]}

<<v11>>
11 Auch das Wasser, das du trinkst, soll genau abgemessen sein: ein
sechstel Hin; davon sollst du von Zeit zu Zeit trinken.

<<v12>>
12 Das Brot sollst du wie Gerstenbrot zubereiten und essen; auf
Menschenkot sollst du es vor aller Augen backen.

<<v13>>
13 Und der Herr sprach: Ebenso werden die Israeliten unreines Brot essen
bei den Völkern, zu denen ich sie verstoße.

<<v14>>
14 Ich aber sagte: Ach, Herr und Gott, ich habe mich noch nie unrein
gemacht. Seit meiner Jugend habe ich noch nie von verendeten oder
zerrissenen Tieren gegessen. Niemals ist verdorbenes Fleisch in meinen
Mund gekommen. ^{[[#fn8][8]]}

<<v15>>
15 Da sagte er zu mir: Gut, ich erlaube dir, dein Brot auf Rindermist
statt auf Menschenkot zu backen.

<<v16>>
16 Dann sagte er zu mir: Menschensohn, ich entziehe Jerusalem seinen
Vorrat an Brot. Sie werden ihr Brot wiegen und es mit Sorgen essen; das
Wasser werden sie genau abmessen und mit Schaudern trinken;
^{[[#fn9][9]][[#fn10][10]]}

<<v17>>
17 denn sie sollen an Brot und Wasser Mangel haben und sich entsetzen,
einer wie der andere, und sollen dahinsiechen wegen ihrer Schuld.
^{[[#fn11][11]]}\\
\\

^{[[#fnm1][1]]} In Babylonien wurden solche auf Ton gezeichnete
Stadtpläne, z. B. von Nippur, gefunden.

^{[[#fnm2][2]]} ℘ 21,27; 26,8

^{[[#fnm3][3]]} Dann lege ich . . . auf dich: Text korr.; H: Und du
legst dann. . .

^{[[#fnm4][4]]} 5f: Die 390 Tage stehen für die Zahl der Jahre, in denen
sich Israel seit Salomo (1 Kön 11,1-8) durch die Verunreinigung des
Tempels versündigt hat (vgl. Ez 8). - Die 40 Tage bedeuten die Jahre der
Strafe, die Israel im Exil zu tragen hat.

^{[[#fnm5][5]]} ℘ Num 14,33f

^{[[#fnm6][6]]} ℘ 3,25

^{[[#fnm7][7]]} 10f: Zwanzig Schekel sind etwa 230 Gramm. - Ein sechstel
Hin ist höchstens 1 Liter.

^{[[#fnm8][8]]} ℘ Ex 22,30; Lev 17,15; 22,8; Apg 10,14

^{[[#fnm9][9]]} ℘ Ps 105,16; Ez 12,18f

^{[[#fnm10][10]]} ich entziehe Jerusalem seinen Vorrat an Brot: vgl. die
Anmerkung zu Lev 26,26.

^{[[#fnm11][11]]} ℘ Lev 26,39
