:PROPERTIES:
:ID:       5237f4f9-20fb-4ff6-938b-79d8e778823e
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_39.html][39]] [[file:Ez_40.html][40]] *41*
[[file:Ez_42.html][42]] [[file:Ez_43.html][43]] ...
[[file:Ez_48.html][48]]

--------------

* Ez 41
  :PROPERTIES:
  :CUSTOM_ID: ez-41
  :END:

<<verses>>

<<v1>>
1 Dann brachte er mich zur Tempelhalle und maß die Pfeiler zu beiden
Seiten (des Eingangs); jeder war sechs Ellen dick. [So dick waren die
Pfeiler.] ^{[[#fn1][1]]}

<<v2>>
2 Die Breite der Türöffnung betrug zehn Ellen und die der beiden
Seitenwände neben der Türöffnung je fünf Ellen. Darauf maß er die Länge
der Tempelhalle - vierzig Ellen - und ihre Breite - zwanzig Ellen.

<<v3>>
3 Er trat ins Innere und maß die Pfeiler der Türöffnung (zum
Allerheiligsten) - zwei Ellen - und die Türöffnung - sechs Ellen sowie
die Breite der Seitenwände neben der Türöffnung - sieben Ellen.
^{[[#fn2][2]]}

<<v4>>
4 Und er maß seine Länge - zwanzig Ellen - und seine Breite an der Seite
der Tempelhalle - zwanzig Ellen. Und er sagte zu mir: Das ist das
Allerheiligste.\\
\\

<<v5>>
**** Die Nebengebäude des Tempels: 41,5-12
     :PROPERTIES:
     :CUSTOM_ID: die-nebengebäude-des-tempels-415-12
     :END:
5 Dann maß er die Mauer des Tempelgebäudes - sechs Ellen dick - und die
Breite des Anbaus rings um das Tempelgebäude - vier Ellen.

<<v6>>
6 (In dem Anbau waren) Nebenräume, einer am andern, im ganzen dreißig in
drei Stockwerken. An der Mauer des Tempelgebäudes waren ringsum
Vorsprünge für die (Deckenbalken der) Nebenräume; die Vorsprünge dienten
als Auflagen; es brauchten also in der Wand des Tempelgebäudes keine
Auflagen zu sein. ^{[[#fn3][3]]}

<<v7>>
7 Durch die Nebenräume ergab sich bis zu einer bestimmten Höhe hinauf
eine Verbreiterung, denn das Tempelgebäude war ringsum umbaut; durch
diesen Anbau ergab sich eine Verbreiterung bis zu einer bestimmten Höhe.
Vom untersten Stockwerk konnte man (im Innern) über das mittlere zum
oberen hinaufsteigen. ^{[[#fn4][4]]}

<<v8>>
8 Das Tempelgebäude selbst konnte man von allen Seiten (über die
Anbauten) herausragen sehen. Die Fundamente der Nebenräume waren eine
ganze Messlatte dick - sechs Ellen. ^{[[#fn5][5]]}

<<v9>>
9 Die Außenmauer des Anbaus war fünf Ellen dick. Zwischen den
Nebenräumen des Tempelgebäudes ^{[[#fn6][6]]}

<<v10>>
10 und den (Priester-)Räumen war ein freier Platz von zwanzig Ellen
Breite, der rings um den Tempel herumlief.

<<v11>>
11 Aus dem Anbau führten zwei Türen ins Freie, eine im Norden und eine
im Süden. Die Mauer des freien Platzes war ringsum fünf Ellen dick.
^{[[#fn7][7]]}

<<v12>>
12 Vor dem eingefriedeten Platz lag auf der Westseite ein (großes)
Gebäude, das neunzig Ellen breit und siebzig Ellen lang war. Die Mauer
dieses Gebäudes war ringsum fünf Ellen dick.\\
\\

<<v13>>
**** Die Maße des Tempels: 41,13-15a
     :PROPERTIES:
     :CUSTOM_ID: die-maße-des-tempels-4113-15a
     :END:
13 Dann maß er das Tempelgebäude - hundert Ellen lang - sowie den
eingefriedeten Platz, das andere Gebäude und seine Mauern - auch hundert
Ellen lang.

<<v14>>
14 Die Breite der Vorderseite des Tempels und des eingefriedeten Platzes
betrug im Osten zusammen ebenfalls hundert Ellen.

<<v15>>
15 Und er maß die Breite des (großen) Gebäudes, das vor dem
eingefriedeten Platz lag, auf der Rückseite und (die Länge) der
Terrassenbauten auf seinen beiden Seiten - wieder je hundert Ellen.\\
**** Das Innere des Tempels: 41,15b-26
     :PROPERTIES:
     :CUSTOM_ID: das-innere-des-tempels-4115b-26
     :END:
Das Innere der Tempelhalle und der Vorhalle, die aus dem Innenhof in den
Tempel führt,

<<v16>>
16 waren getäfelt. Die Rahmen der verschließbaren Fenster und die drei
Gesimse, die von der Schwelle an ringsum liefen, waren aus Holz; ebenso
gab es vom Fußboden bis zu den Fenstern - die Fenster waren verdeckbar -
^{[[#fn8][8]]}

<<v17>>
17 und bis über die Türöffnungen hinauf eine Holztäfelung. Auf allen
Wänden ringsum, auch auf den Wänden zum Innenraum und nach draußen, war
die Täfelung in Felder eingeteilt, auf denen ^{[[#fn9][9]]}

<<v18>>
18 geschnitzte Kerubim und Palmen zu sehen waren, je eine Palme zwischen
zwei Kerubim. Jeder Kerub hatte zwei Gesichter:

<<v19>>
19 Ein Menschengesicht (blickte) zur einen Palme und ein Löwengesicht
zur andern. So war das ganze Haus ringsum ausgestaltet.

<<v20>>
20 Vom Fußboden bis über die Türöffnungen hinauf waren an der Tempelwand
Kerubim und Palmen angebracht.

<<v21>>
21 Die Tür der Tempelhalle hatte einen vierfach gestuften Türrahmen. Vor
dem Allerheiligsten war etwas, das aussah wie

<<v22>>
22 ein Altar aus Holz, drei Ellen hoch, zwei Ellen lang und zwei Ellen
breit. Seine Ecken, sein Sockel und seine Wände waren aus Holz. Der Mann
sagte zu mir: Das ist der Tisch, der vor dem Herrn steht.
^{[[#fn10][10]][[#fn11][11]]}

<<v23>>
23 Die Tempelhalle und das Allerheiligste hatten je eine Doppeltür.

<<v24>>
24 Die Türen hatten zwei Türflügel, zwei drehbare Türflügel, zwei die
eine Tür und zwei die andere Tür.

<<v25>>
25 An den Türen der Tempelhalle waren Kerubim und Palmen angebracht wie
an den Wänden. Außen, an der Vorderseite der Vorhalle, war ein Vordach
aus Holz.

<<v26>>
26 An den beiden Seitenwänden der Vorhalle und an den Nebenräumen des
Tempels [und an den Vordächern] waren verschließbare Fenster und
Palmen.\\
\\

^{[[#fnm1][1]]} Text korr.

^{[[#fnm2][2]]} der Seitenwände: ergänzt nach G.

^{[[#fnm3][3]]} dreißig in drei: Text korr.; vgl. die alten
Übersetzungen; H: dreiunddreißig.

^{[[#fnm4][4]]} Text korr. nach G. Der ganze Vers ist unklar.

^{[[#fnm5][5]]} 8a: Sinn von H nicht ganz klar.

^{[[#fnm6][6]]} Zwischen: Text korr.; vgl. G.

^{[[#fnm7][7]]} Die Mauer: Text korr.; vgl. G; H: Der Platz.

^{[[#fnm8][8]]} waren getäfelt: Text korr. nach G.

^{[[#fnm9][9]]} Text unklar.

^{[[#fnm10][10]]} ℘ Ex 25,23-30; 40,22f

^{[[#fnm11][11]]} und zwei Ellen breit: Text korr., eingefügt nach G. -
sein Sockel: Text korr. nach G; H: seine Länge.
