:PROPERTIES:
:ID:       f1194a53-c992-4aff-81bc-778e6a4cbc7d
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_46.html][46]] [[file:Ez_47.html][47]] *48*

--------------

* Ez 48
  :PROPERTIES:
  :CUSTOM_ID: ez-48
  :END:

<<verses>>

<<v1>>
1 Das sind die Namen der Stämme: Im Norden, entlang dem Weg von Hetlon
nach Lebo-Hamat und nach Hazar-Enan - das Gebiet von Damaskus liegt
dabei nördlich, seitlich von Hamat - gehört von Osten nach Westen Dan
ein Anteil.

<<v2>>
2 Neben dem Gebiet Dans von Osten nach Westen Ascher - ein Anteil;

<<v3>>
3 neben dem Gebiet Aschers von Osten nach Westen Naftali - ein Anteil;

<<v4>>
4 neben dem Gebiet Naftalis von Osten nach Westen Manasse - ein Anteil;

<<v5>>
5 neben dem Gebiet Manasses von Osten nach Westen Efraim - ein Anteil;

<<v6>>
6 neben dem Gebiet Efraims von Osten nach Westen Ruben - ein Anteil;

<<v7>>
7 neben dem Gebiet Rubens von Osten nach Westen Juda - ein Anteil.

<<v8>>
8 Neben dem Gebiet Judas liegt von Osten nach Westen das Land, das ihr
(dem Herrn) als Abgabe entrichten sollt, 25000 Ellen breit und genauso
lang wie jeder andere Anteil von Osten nach Westen. In der Mitte dieses
Stückes liegt das Heiligtum. ^{[[#fn1][1]]}

<<v9>>
9 Das Land, das ihr dem Herrn als Abgabe entrichtet, hat eine Länge von
25000 Ellen und eine Breite von 20000 Ellen. ^{[[#fn2][2]]}

<<v10>>
10 Die heilige Abgabe soll wie folgt eingeteilt werden: Den Priestern
soll ein Stück gehören, das im Norden 25000 Ellen lang ist, im Westen
und im Osten 10000 Ellen breit und im Süden auch 25000 Ellen lang. Das
Heiligtum des Herrn soll in der Mitte liegen.

<<v11>>
11 Den geweihten Priestern aus den Nachkommen Zadoks, die ihren Dienst
verrichtet und mich nicht verlassen haben, als die Israeliten ebenso in
die Irre gingen wie die Leviten,

<<v12>>
12 ihnen soll als Abgabe ein Stück von dem Land gehören, das ihr (dem
Herrn) als Abgabe entrichtet habt; dieses Stück ist hochheilig und liegt
neben dem Gebiet der Leviten. ^{[[#fn3][3]]}

<<v13>>
13 Den Leviten soll wie den Priestern ein Gebiet von 25000 Ellen Länge
und 10000 Ellen Breite gehören. Das Ganze hat also eine Länge von 25000
Ellen und eine Breite von 20000 Ellen.

<<v14>>
14 Man darf nichts davon verkaufen oder zum Tausch anbieten, noch darf
man dieses beste Stück des Landes auf andere übertragen; denn es ist dem
Herrn heilig.

<<v15>>
15 Die 5000 Ellen, die längs der 25000 Ellen in der Breite noch übrig
bleiben, sind nicht heilig, sondern gehören der Stadt als Wohngebiet und
Weidefläche. Die Stadt soll mitten darin liegen. ^{[[#fn4][4]]}

<<v16>>
16 Ihre Maße sollen im Norden 4500 Ellen und im Süden 4500 Ellen
betragen, ebenso 4500 Ellen im Osten und 4500 Ellen im Westen.

<<v17>>
17 Die Weidefläche der Stadt erstreckt sich 250 Ellen nach Norden, 250
Ellen nach Süden, 250 Ellen nach Osten und 250 Ellen nach Westen.

<<v18>>
18 Was dann der Länge nach noch übrig ist längs der heiligen Abgabe
10000 Ellen nach Osten und 10000 Ellen nach Westen [es liegt längs der
heiligen Abgabe] -, von dessen Erträgen sollen sich die Arbeiter der
Stadt ernähren.

<<v19>>
19 Die Arbeiter der Stadt, die dieses Stück bebauen, sollen aus allen
Stämmen Israels sein.

<<v20>>
20 Die ganze Abgabe soll 25000 mal 25000 Ellen betragen. Dieses ganze
Quadrat einschließlich des Eigentums der Stadt sollt ihr als heilige
Abgabe entrichten.

<<v21>>
21 Was zu beiden Seiten der heiligen Abgabe und des Besitzes der Stadt
übrig bleibt, von den 25000 Ellen der (Ostseite der ganzen) Abgabe bis
zur Ostgrenze (des Landes) und von den 25000 Ellen der Westseite (der
Abgabe) bis zur Westgrenze (des Landes), diese (beiden) Stücke entlang
den Stammesanteilen sollen dem Fürsten gehören. Die heilige Abgabe und
das Tempelheiligtum liegen mitten darin.

<<v22>>
22 Der Besitz der Leviten und der Besitz der Stadt soll mitten in dem
Gebiet liegen, das dem Fürsten gehört, und das Gebiet des Fürsten liegt
zwischen dem Gebiet Judas und dem Gebiet Benjamins.

<<v23>>
23 Nun folgen die übrigen Stämme: Von Osten nach Westen Benjamin - ein
Anteil;

<<v24>>
24 neben dem Gebiet Benjamins von Osten nach Westen Simeon - ein Anteil;

<<v25>>
25 neben dem Gebiet Simeons von Osten nach Westen Issachar - ein Anteil;

<<v26>>
26 neben dem Gebiet Issachars von Osten nach Westen Sebulon - ein
Anteil;

<<v27>>
27 neben dem Gebiet Sebulons von Osten nach Westen Gad - ein Anteil.

<<v28>>
28 Neben dem Gebiet Gads verläuft im Negeb die Südgrenze; sie führt von
Tamar zu den Quellen von Meribat-Kadesch und zu dem Bach, der ins große
Meer fließt.

<<v29>>
29 Das ist das Land, das ihr als Erbbesitz an die Stämme Israels
verlosen sollt, und das sind ihre Anteile - Spruch Gottes, des Herrn.\\
\\

<<v30.31>>
**** Die heilige Stadt: 48,30-35
     :PROPERTIES:
     :CUSTOM_ID: die-heilige-stadt-4830-35
     :END:
30.31 Das sind die Ausgänge der Stadt. Die Stadttore sind nach den
Stämmen Israels benannt: auf der Nordseite, die 4500 Ellen misst, drei
Tore: ein Tor ist nach Ruben benannt, ein Tor nach Juda und ein Tor nach
Levi;

<<v32>>
32 auf der Ostseite, die 4500 Ellen misst, drei Tore: ein Tor nach
Josef, ein Tor nach Benjamin und ein Tor nach Dan;

<<v33>>
33 auf der Südseite, die 4500 Ellen misst, drei Tore: ein Tor nach
Simeon, ein Tor nach Issachar und ein Tor nach Sebulon;

<<v34>>
34 auf der Westseite, die 4500 Ellen misst, drei Tore: ein Tor nach Gad,
ein Tor nach Ascher und ein Tor nach Naftali.

<<v35>>
35 Der Umfang der Stadt beträgt 18000 Ellen. Und der Name der Stadt soll
von heute an sein: Hier ist der Herr. ^{[[#fn5][5]]}\\
\\

^{[[#fnm1][1]]} ℘ (8-20) 45,1-8

^{[[#fnm2][2]]} 9.13: 20000 Ellen: Text korr., vgl. 45,1.

^{[[#fnm3][3]]} ℘ Lev 25,32-34

^{[[#fnm4][4]]} ℘ Offb 21,12-17

^{[[#fnm5][5]]} ℘ Offb 21,3
