:PROPERTIES:
:ID:       e85c8343-653b-45e6-98ad-e245a8f3ef6c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Ezechiel* -- [[file:Ez_1.html][1]] ...
[[file:Ez_4.html][4]] [[file:Ez_5.html][5]] *6* [[file:Ez_7.html][7]]
[[file:Ez_8.html][8]] ... [[file:Ez_48.html][48]]

--------------

* Ez 6
  :PROPERTIES:
  :CUSTOM_ID: ez-6
  :END:

<<verses>>

<<v1>>
*** Gerichtsworte: 6,1 - 7,27
    :PROPERTIES:
    :CUSTOM_ID: gerichtsworte-61---727
    :END:
**** Die Zerstörung der Kultstätten: 6,1-14
     :PROPERTIES:
     :CUSTOM_ID: die-zerstörung-der-kultstätten-61-14
     :END:
1 Das Wort des Herrn erging an mich:

<<v2>>
2 Menschensohn, richte dein Gesicht auf die Berge Israels; sprich als
Prophet zu ihnen ^{[[#fn1][1]]}

<<v3>>
3 und sag: Ihr Berge Israels, hört das Wort Gottes, des Herrn! So
spricht Gott, der Herr, zu den Bergen und Hügeln, zu den Schluchten und
Tälern: Ich selbst werde das Schwert über euch bringen und eure
Kulthöhen zerstören. ^{[[#fn2][2]]}

<<v4>>
4 Eure Opferaltäre werden vernichtet und eure Räuchertische zerbrochen.
Eure Erschlagenen werfe ich vor eure Götzen hin.

<<v5>>
5 Die Leichen der Israeliten lege ich ihren Götzen zu Füßen. Eure
Gebeine verstreue ich rings um eure Altäre. ^{[[#fn3][3]]}

<<v6>>
6 Überall, wo ihr wohnt, werden die Städte verwüstet und die Kulthöhen
veröden; denn eure Altäre sollen verwüstet und öde sein, eure Götzen
zerbrochen und verschwunden, eure Räuchertische zerschlagen, eure
Machwerke vernichtet.

<<v7>>
7 Mitten unter euch liegen die Erschlagenen. Dann werdet ihr erkennen,
dass ich der Herr bin.

<<v8>>
8 Wenn ihr in alle Länder vertrieben seid, lasse ich einen Rest von euch
übrig. Bei den Völkern werden einige von euch sein, die dem Schwert
entronnen sind.

<<v9>>
9 Doch die von euch, die davongekommen sind, werden bei den Völkern, zu
denen sie verschleppt wurden, an mich denken; denn ich zerbreche ihr
Herz, das mir untreu geworden ist, und zermalme ihre Augen, die treulos
nach den Götzen schielten. Dann werden sie vor sich selbst Abscheu
empfinden wegen der bösen Gräueltaten, die sie begangen haben,

<<v10>>
10 und sie werden erkennen, dass ich der Herr bin und nicht umsonst
gedroht habe, dieses Unheil über sie zu bringen.

<<v11>>
11 So spricht Gott, der Herr: Schlag die Hände zusammen, stampf mit dem
Fuß auf den Boden und schrei: Weh über all die bösen Gräueltaten des
Hauses Israel! Ihretwegen werden sie durch Schwert, Hunger und Pest
umkommen.

<<v12>>
12 Wer in der Ferne ist, wird an der Pest sterben; wer nahe ist, wird
unter dem Schwert fallen. Wer übrig und verschont geblieben ist, wird
vor Hunger sterben. So lasse ich meinen Grimm an ihnen aus.

<<v13>>
13 Wenn die Erschlagenen mitten unter ihren Götzenbildern liegen, rings
um ihre Altäre, auf allen Hügeln, auf allen Bergeshöhen, unter jedem
üppigen Baum und jeder schattigen Eiche, an den Stellen, wo sie all
ihren Götzen den beruhigenden Duft ihrer Opfer spendeten, dann werdet
ihr erkennen, dass ich der Herr bin. ^{[[#fn4][4]]}

<<v14>>
14 Ich strecke meine Hand gegen sie aus und mache ihr Land zur öden
Wüste, von der Steppe bis nach Ribla, überall, wo sie wohnen. Dann
werden sie erkennen, dass ich der Herr bin. ^{[[#fn5][5]][[#fn6][6]]}\\
\\

^{[[#fnm1][1]]} ℘ 36,1

^{[[#fnm2][2]]} ℘ Lev 26,30f

^{[[#fnm3][3]]} ℘ 2 Kön 23,14

^{[[#fnm4][4]]} ℘ 1 Kön 14,23

^{[[#fnm5][5]]} ℘ 2 Kön 25,21

^{[[#fnm6][6]]} von der Steppe bis nach Ribla: Text korr.; H: bis nach
der Steppe von Dibla. Die ganze Ausdehnung des Landes von der Arabischen
Wüste bis nach Ribla am Orontes ist betroffen.
