#+TITLE: Gen 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:09]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Gen 21.html


<<verses>>

<<v1>>
* Isaaks Geburt: 21,1-8

1 Der Herr nahm sich Saras an, wie er gesagt hatte, und er tat Sara so,
wie er versprochen hatte. [fn:1]

<<v2>>
2 Sara wurde schwanger und gebar dem Abraham noch in seinem Alter einen
Sohn zu der Zeit, die Gott angegeben hatte.

<<v3>>
3 Abraham nannte den Sohn, den ihm Sara gebar, Isaak.

<<v4>>
4 Als sein Sohn Isaak acht Tage alt war, beschnitt ihn Abraham, wie Gott
ihm befohlen hatte.

<<v5>>
5 Abraham war hundert Jahre alt, als sein Sohn Isaak zur Welt kam.

<<v6>>
6 Sara aber sagte: Gott ließ mich lachen; jeder, der davon hört, wird
mit mir lachen. [fn:2]

<<v7>>
7 Wer, sagte sie, hätte Abraham zu sagen gewagt, Sara werde noch Kinder
stillen? Und nun habe ich ihm noch in seinem Alter einen Sohn geboren.

<<v8>>
8 Das Kind wuchs heran und wurde entwöhnt. Als Isaak entwöhnt wurde,
veranstaltete Abraham ein großes Festmahl.\\
\\

<<v9>>
* Hagar und Ismael: 21,9-21

9 Eines Tages beobachtete Sara, wie der Sohn, den die Ägypterin Hagar
Abraham geboren hatte, umhertollte. [fn:3] [fn:4]

<<v10>>
10 Da sagte sie zu Abraham: Verstoß diese Magd und ihren Sohn! Denn der
Sohn dieser Magd soll nicht zusammen mit meinem Sohn Isaak Erbe sein.

<<v11>>
11 Dieses Wort verdross Abraham sehr, denn es ging doch um seinen Sohn.

<<v12>>
12 Gott sprach aber zu Abraham: Sei wegen des Knaben und deiner Magd
nicht verdrossen! Hör auf alles, was dir Sara sagt! Denn nach Isaak
sollen deine Nachkommen benannt werden.

<<v13>>
13 Aber auch den Sohn der Magd will ich zu einem großen Volk machen,
weil auch er dein Nachkomme ist.

<<v14>>
14 Am Morgen stand Abraham auf, nahm Brot und einen Schlauch mit Wasser,
übergab beides Hagar, legte es ihr auf die Schulter, übergab ihr das
Kind und entließ sie. Sie zog fort und irrte in der Wüste von Beerscheba
umher.

<<v15>>
15 Als das Wasser im Schlauch zu Ende war, warf sie das Kind unter einen
Strauch,

<<v16>>
16 ging weg und setzte sich in der Nähe hin, etwa einen Bogenschuss weit
entfernt; denn sie sagte: Ich kann nicht mit ansehen, wie das Kind
stirbt. Sie saß in der Nähe und weinte laut.

<<v17>>
17 Gott hörte den Knaben schreien; da rief der Engel Gottes vom Himmel
her Hagar zu und sprach: Was hast du, Hagar? Fürchte dich nicht, Gott
hat den Knaben dort schreien gehört, wo er liegt.

<<v18>>
18 Steh auf, nimm den Knaben und halt ihn fest an deiner Hand; denn zu
einem großen Volk will ich ihn machen.

<<v19>>
19 Gott öffnete ihr die Augen und sie erblickte einen Brunnen. Sie ging
hin, füllte den Schlauch mit Wasser und gab dem Knaben zu trinken.

<<v20>>
20 Gott war mit dem Knaben. Er wuchs heran, ließ sich in der Wüste
nieder und wurde ein Bogenschütze.

<<v21>>
21 Er ließ sich in der Wüste Paran nieder und seine Mutter nahm ihm eine
Frau aus Ägypten.\\
\\

<<v22>>
* Der Vertrag Abrahams mit Abimelech: 21,22-34

22 Um jene Zeit sagten Abimelech und sein Feldherr Pichol zu Abraham:
Gott ist mit dir bei allem, was du unternimmst.

<<v23>>
23 Aber nun schwör mir hier bei Gott, dass du weder mich noch meinen
Thronerben noch meine Nachfahren hintergehen wirst. Das gleiche
Wohlwollen, das ich dir erwiesen habe, sollst du mir erweisen und dem
Land, in dem du dich als Fremder aufhältst.

<<v24>>
24 Abraham erwiderte: Gut, ich will den Eid leisten.

<<v25>>
25 Abraham stellte aber Abimelech zur Rede wegen des Brunnens, den ihm
Abimelechs Knechte weggenommen hatten.

<<v26>>
26 Abimelech antwortete: Ich weiß nicht, wer das getan hat. Du hast es
mir noch nicht gemeldet und auch ich habe erst heute davon gehört.

<<v27>>
27 Da nahm Abraham Schafe und Rinder und gab sie Abimelech; so schlossen
beide einen Vertrag.

<<v28>>
28 Abraham stellte aber sieben Lämmer der Herde beiseite.

<<v29>>
29 Da fragte ihn Abimelech: Was sollen die sieben Lämmer da, die du
beiseite gestellt hast?

<<v30>>
30 Die sieben Lämmer, sagte er, sollst du von mir annehmen als Beweis
dafür, dass ich diesen Brunnen gegraben habe.

<<v31>>
31 Darum nannte er den Ort Beerscheba (Siebenbrunn oder Eidbrunn); denn
dort leisteten beide einen Eid. [fn:5] [fn:6]

<<v32>>
32 Sie schlossen also zu Beerscheba einen Vertrag. Dann machten sich
Abimelech und sein Feldherr Pichol auf und kehrten ins Philisterland
zurück.

<<v33>>
33 Abraham aber pflanzte eine Tamariske in Beerscheba und rief dort den
Herrn an unter dem Namen: Gott, der Ewige.

<<v34>>
34 Darauf hielt sich Abraham längere Zeit als Fremder im Philisterland
auf.\\
\\


* Footnotes

[fn:1] 17,15-22 [[file:Gen_17.org::v15][Gen 17,15-22]]; 18,10-15 [[file:Gen_18.org::v10][Gen 18,10-15]]

[fn:2] Wieder Wortspiel mit der Bedeutung des Namens Isaak
(vgl. 17,17 und 18,12-15).

[fn:3] (9-21) 16,1-16 [[file:Gen_16.org::v1][Gen 16,1-16]]

[fn:4] 9-21: Vgl. die Anmerkung zu 16,2 [[file:Gen_16.org::v2][Gen 16,2]].

[fn:5] 26,33 [[file:Gen_26.org::v33][Gen 26,33]]

[fn:6] Das hebräische Wort scheba kann sowohl «sieben» als auch
"Eid" bedeuten.
