#+TITLE: Gen 37 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:30]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Gen 37.html

<<verses>>

<<v1>>
* Die Söhne Jakobs: 37,1 - 50,26

* Josef und seine Brüder: 37,1-36

1 Jakob ließ sich in dem Land nieder, in dem sich sein Vater als Fremder
aufgehalten hatte, in Kanaan.

<<v2>>
2 Das ist die Geschlechterfolge nach Jakob: Als Josef siebzehn Jahre
zählte, also noch jung war, weidete er mit seinen Brüdern, den Söhnen
Bilhas und Silpas, der Frauen seines Vaters, die Schafe und Ziegen.
Josef hinterbrachte ihrem Vater, was die Brüder Böses taten.

<<v3>>
3 Israel liebte Josef unter allen seinen Söhnen am meisten, weil er ihm
noch in hohem Alter geboren worden war. Er ließ ihm einen Ärmelrock
machen. [fn:1]

<<v4>>
4 Als seine Brüder sahen, dass ihr Vater ihn mehr liebte als alle seine
Brüder, hassten sie ihn und konnten mit ihm kein gutes Wort mehr reden.

<<v5>>
5 Einst hatte Josef einen Traum. Als er ihn seinen Brüdern erzählte,
hassten sie ihn noch mehr.

<<v6>>
6 Er sagte zu ihnen: Hört, was ich geträumt habe.

<<v7>>
7 Wir banden Garben mitten auf dem Feld. Meine Garbe richtete sich auf
und blieb auch stehen. Eure Garben umringten sie und neigten sich tief
vor meiner Garbe.

<<v8>>
8 Da sagten seine Brüder zu ihm: Willst du etwa König über uns werden
oder dich als Herr über uns aufspielen? Und sie hassten ihn noch mehr
wegen seiner Träume und seiner Worte.

<<v9>>
9 Er hatte noch einen anderen Traum. Er erzählte ihn seinen Brüdern und
sagte: Ich träumte noch einmal: Die Sonne, der Mond und elf Sterne
verneigten sich tief vor mir.

<<v10>>
10 Als er davon seinem Vater und seinen Brüdern erzählte, schalt ihn
sein Vater und sagte zu ihm: Was soll das, was du da geträumt hast?
Sollen wir vielleicht, ich, deine Mutter und deine Brüder, kommen und
uns vor dir zur Erde niederwerfen?

<<v11>>
11 Seine Brüder waren eifersüchtig auf ihn, sein Vater aber vergaß die
Sache nicht.

<<v12>>
12 Als seine Brüder fortgezogen waren, um das Vieh ihres Vaters bei
Sichem zu weiden,

<<v13>>
13 sagte Israel zu Josef: Deine Brüder weiden bei Sichem das Vieh. Geh,
ich will dich zu ihnen schicken. Er antwortete: Ich bin bereit.

<<v14>>
14 Da sagte der Vater zu ihm: Geh doch hin und sieh, wie es deinen
Brüdern und dem Vieh geht, und berichte mir! So schickte er ihn aus dem
Tal von Hebron fort und Josef kam nach Sichem.

<<v15>>
15 Ein Mann traf ihn, wie er auf dem Feld umherirrte; er fragte ihn: Was
suchst du?

<<v16>>
16 Josef antwortete: Meine Brüder suche ich. Sag mir doch, wo sie das
Vieh weiden.

<<v17>>
17 Der Mann antwortete: Sie sind von hier weitergezogen. Ich habe
nämlich gehört, wie sie sagten: Gehen wir nach Dotan. Da ging Josef
seinen Brüdern nach und fand sie in Dotan.

<<v18>>
18 Sie sahen ihn von weitem. Bevor er jedoch nahe an sie herangekommen
war, fassten sie den Plan, ihn umzubringen.

<<v19>>
19 Sie sagten zueinander: Dort kommt ja dieser Träumer.

<<v20>>
20 Jetzt aber auf, erschlagen wir ihn und werfen wir ihn in eine der
Zisternen. Sagen wir, ein wildes Tier habe ihn gefressen. Dann werden
wir ja sehen, was aus seinen Träumen wird.

<<v21>>
21 Ruben hörte das und wollte ihn aus ihrer Hand retten. Er sagte:
Begehen wir doch keinen Mord.

<<v22>>
22 Und Ruben sagte zu ihnen: Vergießt kein Blut! Werft ihn in die
Zisterne da in der Steppe, aber legt nicht Hand an ihn! Er wollte ihn
nämlich aus ihrer Hand retten und zu seinem Vater zurückbringen.

<<v23>>
23 Als Josef bei seinen Brüdern angekommen war, zogen sie ihm sein
Gewand aus, den Ärmelrock, den er anhatte,

<<v24>>
24 packten ihn und warfen ihn in die Zisterne. Die Zisterne war leer; es
war kein Wasser darin.

<<v25>>
25 Als sie dann beim Essen saßen und aufblickten, sahen sie, dass gerade
eine Karawane von Ismaelitern aus Gilead kam. Ihre Kamele waren mit
Tragakant, Mastix und Ladanum beladen. Sie waren unterwegs nach Ägypten. [fn:2]

<<v26>>
26 Da schlug Juda seinen Brüdern vor: Was haben wir davon, wenn wir
unseren Bruder erschlagen und sein Blut zudecken?

<<v27>>
27 Kommt, verkaufen wir ihn den Ismaelitern. Wir wollen aber nicht Hand
an ihn legen, denn er ist doch unser Bruder und unser Verwandter. Seine
Brüder waren einverstanden.

<<v28>>
28 Midianitische Kaufleute kamen vorbei. Da zogen sie Josef aus der
Zisterne heraus und verkauften ihn für zwanzig Silberstücke an die
Ismaeliter. Diese brachten Josef nach Ägypten.

<<v29>>
29 Als Ruben zur Zisterne zurückkam, war Josef nicht mehr dort. Er
zerriss seine Kleider,

<<v30>>
30 wandte sich an seine Brüder und sagte: Der Kleine ist ja nicht mehr
da. Und ich, was soll ich jetzt anfangen?

<<v31>>
31 Da nahmen sie Josefs Gewand, schlachteten einen Ziegenbock und
tauchten das Gewand in das Blut.

<<v32>>
32 Dann schickten sie den Ärmelrock zu ihrem Vater und ließen ihm sagen:
Das haben wir gefunden. Sieh doch, ob das der Rock deines Sohnes ist
oder nicht.

<<v33>>
33 Als er ihn angesehen hatte, sagte er: Der Rock meines Sohnes! Ein
wildes Tier hat ihn gefressen. Zerrissen, zerrissen ist Josef.

<<v34>>
34 Jakob zerriss seine Kleider, legte Trauerkleider an und trauerte um
seinen Sohn viele Tage.

<<v35>>
35 Alle seine Söhne und Töchter machten sich auf, um ihn zu trösten. Er
aber ließ sich nicht trösten und sagte: Ich will dauernd zu meinem Sohn
in die Unterwelt hinabsteigen. So beweinte ihn sein Vater.

<<v36>>
36 Die Midianiter aber verkauften Josef nach Ägypten an Potifar, einen
Hofbeamten des Pharao, den Obersten der Leibwache.\\
\\


* Footnotes

[fn:1] Ein «Ärmelrock» ist ein Festtagsgewand.

[fn:2] Tragakant, Mastix und Ladanum sind wohlriechende Harze,
die als Räucherwerk und als Grundstoffe für die Salbenherstellung
dienten.
