#+TITLE: Gen 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 09:59]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Gen 5.html

* Gen 5
<<verses>>

<<v1>>
1 Das ist die Liste der Geschlechterfolge nach Adam: Am Tag, da Gott den
Menschen erschuf, machte er ihn Gott ähnlich. [fn:1] [fn:2]

<<v2>>
2 Als Mann und Frau erschuf er sie, er segnete sie und nannte sie Mensch
an dem Tag, da sie erschaffen wurden.

<<v3>>
3 Adam war hundertdreißig Jahre alt, da zeugte er einen Sohn, der ihm
ähnlich war, wie sein Abbild, und nannte ihn Set. [fn:3]

<<v4>>
4 Nach der Geburt Sets lebte Adam noch achthundert Jahre und zeugte
Söhne und Töchter.

<<v5>>
5 Die gesamte Lebenszeit Adams betrug neunhundertdreißig Jahre, dann
starb er.

<<v6>>
6 Set war hundertfünf Jahre alt, da zeugte er Enosch.

<<v7>>
7 Nach der Geburt des Enosch lebte Set noch achthundertsieben Jahre und
zeugte Söhne und Töchter.

<<v8>>
8 Die gesamte Lebenszeit Sets betrug neunhundertzwölf Jahre, dann starb
er.

<<v9>>
9 Enosch war neunzig Jahre alt, da zeugte er Kenan.

<<v10>>
10 Nach der Geburt Kenans lebte Enosch noch achthundertfünfzehn Jahre
und zeugte Söhne und Töchter.

<<v11>>
11 Die gesamte Lebenszeit des Enosch betrug neunhundertfünf Jahre, dann
starb er.

<<v12>>
12 Kenan war siebzig Jahre alt, da zeugte er Mahalalel.

<<v13>>
13 Nach der Geburt Mahalalels lebte Kenan noch achthundertvierzig Jahre
und zeugte Söhne und Töchter.

<<v14>>
14 Die gesamte Lebenszeit Kenans betrug neunhundertzehn Jahre, dann
starb er.

<<v15>>
15 Mahalalel war fünfundsechzig Jahre alt, da zeugte er Jered.

<<v16>>
16 Nach der Geburt Jereds lebte Mahalalel noch achthundertdreißig Jahre
und zeugte Söhne und Töchter.

<<v17>>
17 Die gesamte Lebenszeit Mahalalels betrug achthundertfünfundneunzig
Jahre, dann starb er.

<<v18>>
18 Jered war hundertzweiundsechzig Jahre alt, da zeugte er Henoch.

<<v19>>
19 Nach der Geburt Henochs lebte Jered noch achthundert Jahre und zeugte
Söhne und Töchter.

<<v20>>
20 Die gesamte Lebenszeit Jereds betrug neunhundertzweiundsechzig Jahre,
dann starb er.

<<v21>>
21 Henoch war fünfundsechzig Jahre alt, da zeugte er Metuschelach.

<<v22>>
22 Nach der Geburt Metuschelachs ging Henoch seinen Weg mit Gott noch
dreihundert Jahre lang und zeugte Söhne und Töchter.

<<v23>>
23 Die gesamte Lebenszeit Henochs betrug dreihundertfünfundsechzig
Jahre.

<<v24>>
24 Henoch war seinen Weg mit Gott gegangen, dann war er nicht mehr da;
denn Gott hatte ihn aufgenommen.

<<v25>>
25 Metuschelach war hundertsiebenundachtzig Jahre alt, da zeugte er
Lamech.

<<v26>>
26 Nach der Geburt Lamechs lebte Metuschelach noch
siebenhundertzweiundachtzig Jahre und zeugte Söhne und Töchter.

<<v27>>
27 Die gesamte Lebenszeit Metuschelachs betrug neunhundertneunundsechzig
Jahre, dann starb er.

<<v28>>
28 Lamech war hundertzweiundachtzig Jahre alt, da zeugte er einen Sohn

<<v29>>
29 und nannte ihn Noach (Ruhe). Dabei sagte er: Er wird uns aufatmen
lassen von unserer Arbeit und von der Mühe unserer Hände um den
Ackerboden, den der Herr verflucht hat. [fn:4] [fn:5]

<<v30>>
30 Nach der Geburt Noachs lebte Lamech noch fünfhundertfünfundneunzig
Jahre und zeugte Söhne und Töchter.

<<v31>>
31 Die gesamte Lebenszeit Lamechs betrug siebenhundertsiebenundsiebzig
Jahre, dann starb er.

<<v32>>
32 Noach zeugte im Alter von fünfhundert Jahren Sem, Ham und Jafet.\\
\\


* Footnotes

[fn:1] (1f) 1,26f [[file:Gen_1.org::v26][Gen 1,26f]]

[fn:2] 1-32: Zu den Angaben über das hohe Lebensalter der
Urväter ist zu bedenken, dass sie nur in der jüngsten Pentateuchschicht
stehen; diese arbeitet gern mit symbolischen Zahlenwerten, die wir heute
nicht mehr durchschauen. Die babylonischen Listen der Urkönige kennen
noch viel höhere Lebensjahre bzw. Regierungszeiten.

[fn:3] 1,26f [[file:Gen_1.org::v26][Gen 1,26f]]

[fn:4] 3,17 [[file:Gen_3.org::v17][Gen 3,17]]

[fn:5] Wortspiel mit dem Namen Noach und den Zeitwörtern für
«ruhen» (núach) und «trösten» (nihám).
