#+TITLE: Gen 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:07]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Gen 18.html


<<verses>>

<<v1>>
* Gott zu Gast bei Abraham: 18,1-33

1 Der Herr erschien Abraham bei den Eichen von Mamre. Abraham saß zur
Zeit der Mittagshitze am Zelteingang.

<<v2>>
2 Er blickte auf und sah vor sich drei Männer stehen. Als er sie sah,
lief er ihnen vom Zelteingang aus entgegen, warf sich zur Erde nieder

<<v3>>
3 und sagte: Mein Herr, wenn ich dein Wohlwollen gefunden habe, geh doch
an deinem Knecht nicht vorbei!

<<v4>>
4 Man wird etwas Wasser holen; dann könnt ihr euch die Füße waschen und
euch unter dem Baum ausruhen.

<<v5>>
5 Ich will einen Bissen Brot holen und ihr könnt dann nach einer kleinen
Stärkung weitergehen; denn deshalb seid ihr doch bei eurem Knecht
vorbeigekommen. Sie erwiderten: Tu, wie du gesagt hast.

<<v6>>
6 Da lief Abraham eiligst ins Zelt zu Sara und rief: Schnell drei Sea
feines Mehl! Rühr es an und backe Brotfladen!

<<v7>>
7 Er lief weiter zum Vieh, nahm ein zartes, prächtiges Kalb und übergab
es dem Jungknecht, der es schnell zubereitete.

<<v8>>
8 Dann nahm Abraham Butter, Milch und das Kalb, das er hatte zubereiten
lassen, und setzte es ihnen vor. Er wartete ihnen unter dem Baum auf,
während sie aßen.

<<v9>>
9 Sie fragten ihn: Wo ist deine Frau Sara? Dort im Zelt, sagte er.

<<v10>>
10 Da sprach der Herr: In einem Jahr komme ich wieder zu dir, dann wird
deine Frau Sara einen Sohn haben. Sara hörte am Zelteingang hinter
seinem Rücken zu. [fn:1]

<<v11>>
11 Abraham und Sara waren schon alt; sie waren in die Jahre gekommen.
Sara erging es längst nicht mehr, wie es Frauen zu ergehen pflegt.

<<v12>>
12 Sara lachte daher still in sich hinein und dachte: Ich bin doch schon
alt und verbraucht und soll noch das Glück der Liebe erfahren? Auch ist
mein Herr doch schon ein alter Mann! [fn:2]

<<v13>>
13 Da sprach der Herr zu Abraham: Warum lacht Sara und sagt: Soll ich
wirklich noch Kinder bekommen, obwohl ich so alt bin?

<<v14>>
14 Ist beim Herrn etwas unmöglich? Nächstes Jahr um diese Zeit werde ich
wieder zu dir kommen; dann wird Sara einen Sohn haben.

<<v15>>
15 Sara leugnete: Ich habe nicht gelacht. Sie hatte nämlich Angst. Er
aber sagte: Doch, du hast gelacht.

<<v16>>
16 Die Männer erhoben sich von ihrem Platz und schauten gegen Sodom.
Abraham wollte mitgehen, um sie zu verabschieden.

<<v17>>
17 Da sagte sich der Herr: Soll ich Abraham verheimlichen, was ich
vorhabe?

<<v18>>
18 Abraham soll doch zu einem großen, mächtigen Volk werden, durch ihn
sollen alle Völker der Erde Segen erlangen. [fn:3]

<<v19>>
19 Denn ich habe ihn dazu auserwählt, dass er seinen Söhnen und seinem
Haus nach ihm aufträgt, den Weg des Herrn einzuhalten und zu tun, was
gut und recht ist, damit der Herr seine Zusagen an Abraham erfüllen
kann.

<<v20>>
20 Der Herr sprach also: Das Klagegeschrei über Sodom und Gomorra, ja,
das ist laut geworden, und ihre Sünde, ja, die ist schwer.

<<v21>>
21 Ich will hinabgehen und sehen, ob ihr Tun wirklich dem Klagegeschrei
entspricht, das zu mir gedrungen ist. Ich will es wissen.

<<v22>>
22 Die Männer wandten sich von dort ab und gingen auf Sodom zu. Abraham
aber stand noch immer vor dem Herrn.

<<v23>>
23 Er trat näher und sagte: Willst du auch den Gerechten mit den
Ruchlosen wegraffen?

<<v24>>
24 Vielleicht gibt es fünfzig Gerechte in der Stadt: Willst du auch sie
wegraffen und nicht doch dem Ort vergeben wegen der fünfzig Gerechten
dort?

<<v25>>
25 Das kannst du doch nicht tun, die Gerechten zusammen mit den
Ruchlosen umbringen. Dann ginge es ja dem Gerechten genauso wie dem
Ruchlosen. Das kannst du doch nicht tun. Sollte sich der Richter über
die ganze Erde nicht an das Recht halten?

<<v26>>
26 Da sprach der Herr: Wenn ich in Sodom, in der Stadt, fünfzig Gerechte
finde, werde ich ihretwegen dem ganzen Ort vergeben.

<<v27>>
27 Abraham antwortete und sprach: Ich habe es nun einmal unternommen,
mit meinem Herrn zu reden, obwohl ich Staub und Asche bin.

<<v28>>
28 Vielleicht fehlen an den fünfzig Gerechten fünf. Wirst du wegen der
fünf die ganze Stadt vernichten? Nein, sagte er, ich werde sie nicht
vernichten, wenn ich dort fünfundvierzig finde.

<<v29>>
29 Er fuhr fort, zu ihm zu reden: Vielleicht finden sich dort nur
vierzig. Da sprach er: Ich werde es der vierzig wegen nicht tun.

<<v30>>
30 Und weiter sagte er: Mein Herr zürne nicht, wenn ich weiterrede.
Vielleicht finden sich dort nur dreißig. Er entgegnete: Ich werde es
nicht tun, wenn ich dort dreißig finde.

<<v31>>
31 Darauf sagte er: Ich habe es nun einmal unternommen, mit meinem Herrn
zu reden. Vielleicht finden sich dort nur zwanzig. Er antwortete: Ich
werde sie um der zwanzig willen nicht vernichten.

<<v32>>
32 Und nochmals sagte er: Mein Herr zürne nicht, wenn ich nur noch
einmal das Wort ergreife. Vielleicht finden sich dort nur zehn. Und
wiederum sprach er: Ich werde sie um der zehn willen nicht vernichten.

<<v33>>
33 Nachdem der Herr das Gespräch mit Abraham beendet hatte, ging er weg
und Abraham kehrte heim.\\
\\


* Footnotes

[fn:1] 17,15-21 [[file:Gen_17.org::v15][Gen 17,15-21]]; 21,1-8 [[file:Gen_21.org::v1][Gen 21,1-8]]

[fn:2] 12-15: Die Erzählung vom Lachen Saras ist wieder
Anspielung auf den Namen Isaak (vgl. 17,17).

[fn:3] 12,2f [[file:Gen_12.org::v2][Gen 12,2f]]; 22,17f [[file:Gen_22.org::v17][Gen 22,17f]]; 26,4 [[file:Gen_26.org::v4][Gen 26,4]]; 28,14 [[file:Gen_28.org::v14][Gen 28,14]]
