#+TITLE: Gen 35 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:29]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Gen 35.html

<<verses>>

<<v1>>
* Jakob wieder in Bet-El: 35,1-15
:PROPERTIES:
:CUSTOM_ID: jakob-wieder-in-bet-el-351-15
:END:
1 Gott sprach zu Jakob: Zieh nach Bet-El hinauf und lass dich dort
nieder! Errichte dort einen Altar dem Gott, der dir auf der Flucht vor
deinem Bruder Esau erschienen ist.

<<v2>>
2 Dann sagte Jakob zu seinem Haus und zu allen, die zu ihm gehörten:
Entfernt die fremden Götter aus eurer Mitte, reinigt euch und wechselt
eure Kleider!

<<v3>>
3 Wir wollen uns aufmachen und nach Bet-El hinaufziehen. Dort will ich
einen Altar für den Gott errichten, der mich am Tag meiner Bedrängnis
erhört hat und der auf meinem Weg mit mir war.

<<v4>>
4 Sie übergaben Jakob alle fremden Götter, die sie hatten, und die Ringe
an ihren Ohren. Jakob vergrub sie unter der Eiche bei Sichem.

<<v5>>
5 Dann brachen sie auf. Da überkam ein Gottesschrecken die Städte
ringsum und so verfolgten sie die Söhne Jakobs nicht.

<<v6>>
6 Jakob kam nach Lus in Kanaan, das jetzt Bet-El heißt, er und alles
Volk, das bei ihm war.

<<v7>>
7 Er baute dort einen Altar und nannte die Stätte «Gott von Bet-El»;
denn auf der Flucht vor seinem Bruder hatte Gott sich ihm dort
offenbart. [fn:1]

<<v8>>
8 Debora, die Amme Rebekkas, starb. Man begrub sie unterhalb von Bet-El
unter der Eiche. Er gab ihr den Namen Träneneiche.

<<v9>>
9 Gott erschien Jakob noch einmal nach seiner Rückkehr aus Paddan-Aram
und segnete ihn.

<<v10>>
10 Gott sprach zu ihm: Dein Name ist Jakob. Dein Name soll jedoch nicht
mehr Jakob lauten, sondern Israel soll dein Name sein. Er gab ihm also
den Namen Israel. [fn:2]

<<v11>>
11 Und Gott sprach zu ihm: Ich bin Gott, der Allmächtige. Sei fruchtbar
und vermehre dich! Ein Volk, eine Schar von Völkern soll aus dir
hervorgehen, Könige sollen deinen Lenden entstammen.

<<v12>>
12 Das Land, das ich Abraham und Isaak gegeben habe, will ich dir geben
und auch deinen Nachkommen will ich es geben. [fn:3]

<<v13>>
13 Dann fuhr Gott von dem Ort, an dem er mit ihm geredet hatte, zum
Himmel auf.

<<v14>>
14 Jakob richtete an dem Ort, wo Gott mit ihm geredet hatte, ein
Steinmal, einen Gedenkstein, auf. Darüber schüttete er ein Trankopfer
und goss Öl darauf.

<<v15>>
15 Jakob gab dem Ort, an dem Gott mit ihm geredet hatte, den Namen
Bet-El.\\
\\

<<v16>>
* Benjamins Geburt und Rahels Tod: 35,16-20
:PROPERTIES:
:CUSTOM_ID: benjamins-geburt-und-rahels-tod-3516-20
:END:
16 Sie brachen von Bet-El auf. Nur ein kleines Stück Weg war es noch bis
Efrata, als Rahel gebar. Sie hatte eine schwere Geburt.

<<v17>>
17 Als sie bei der Geburt schwer litt, redete ihr die Amme zu: Fürchte
dich nicht, auch diesmal hast du einen Sohn.

<<v18>>
18 Während ihr das Leben entfloh - sie musste nämlich sterben -, gab sie
ihm den Namen Ben-Oni (Unheilskind); sein Vater aber nannte ihn Benjamin
(Erfolgskind).

<<v19>>
19 Als Rahel gestorben war, begrub man sie an der Straße nach Efrata,
das jetzt Betlehem heißt.

<<v20>>
20 Jakob errichtete ein Steinmal über ihrem Grab. Das ist das Grabmal
Rahels bis auf den heutigen Tag.\\
\\

<<v21>>
* Die Söhne Jakobs und der Tod Isaaks: 35,21-29
:PROPERTIES:
:CUSTOM_ID: die-söhne-jakobs-und-der-tod-isaaks-3521-29
:END:
21 Israel brach auf und schlug sein Zelt jenseits von Migdal-Eder auf.

<<v22>>
22 Während Israel in jenem Land wohnte, ging Ruben hin und schlief mit
Bilha, der Nebenfrau seines Vaters. Israel hörte davon. Jakob hatte
zwölf Söhne. [fn:4]

<<v23>>
23 Die Söhne Leas waren: Ruben, der Erstgeborene Jakobs, ferner Simeon,
Levi, Juda, Issachar und Sebulon.

<<v24>>
24 Die Söhne Rahels waren: Josef und Benjamin.

<<v25>>
25 Die Söhne Bilhas, der Magd Rahels, waren: Dan und Naftali.

<<v26>>
26 Die Söhne Silpas, der Magd Leas, waren: Gad und Ascher. Das waren die
Söhne Jakobs, die ihm in Paddan-Aram geboren wurden.

<<v27>>
27 Jakob kam zu seinem Vater Isaak nach Mamre, nach Kirjat-Arba, das
jetzt Hebron heißt, wo sich Abraham und Isaak als Fremde aufgehalten
hatten.

<<v28>>
28 Isaak wurde hundertachtzig Jahre alt,

<<v29>>
29 dann verschied er. Er starb und wurde mit seinen Vorfahren vereint,
betagt und satt an Jahren. Seine Söhne Esau und Jakob begruben ihn.\\
\\


* Footnotes

[fn:1] 28,12-22 [[file:Gen_28.org::v12][Gen 28,12-22]]

[fn:2] 32,29 [[file:Gen_32.org::v29][Gen 32,29]]

[fn:3] 13,14f [[file:Gen_13.org::v14][Gen 13,14]]; 15,17-21 [[file:Gen_15.org::v17][Gen 15,17-21]]; 26,3f [[file:Gen_26.org::v3][Gen 26,3f]]

[fn:4] 49,3f [[file:Gen_49.org::v3][Gen 49,3f]]
