#+TITLE: Gen 31 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:22]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Gen 31.html


<<verses>>

<<v1>>
* Jakobs Trennung von Laban: 31,1 - 32,1

1 Jakob hatte erfahren, dass die Söhne Labans sagten: Jakob hat alles,
was unserem Vater gehört, weggenommen; auf Kosten unseres Vaters hat er
sich so bereichert.

<<v2>>
2 Jakob sah Laban ins Gesicht: Laban war ihm nicht mehr zugetan wie
früher.

<<v3>>
3 Da sagte der Herr zu Jakob: Kehr zurück in das Land deiner Väter und
zu deiner Verwandtschaft! Ich bin mit dir.

<<v4>>
4 Jakob ließ Rahel und Lea auf das Feld zu seiner Herde rufen

<<v5>>
5 und sagte zu ihnen: Ich sehe am Gesicht eures Vaters, dass er mir
nicht mehr so gesinnt ist wie früher. Aber der Gott meines Vaters war
mit mir.

<<v6>>
6 Ihr wisst, dass ich mit allen Kräften eurem Vater gedient habe.

<<v7>>
7 Aber euer Vater hat mich hintergangen und meinen Lohn zehnmal
geändert; Gott freilich hat ihn daran gehindert, mich zu schädigen.

<<v8>>
8 Sagte er, die Gesprenkelten sollen dein Lohn sein, dann warfen alle
Tiere gesprenkelte Junge; sagte er, die Gestreiften sollen dein Lohn
sein, dann warfen alle Tiere gestreifte Junge.

<<v9>>
9 Gott hat eurem Vater den Viehbestand entzogen und ihn mir gegeben.

<<v10>>
10 Zur Zeit, da die Tiere brünstig waren, hatte ich einen Traum; ich
sah: Gestreifte, gesprenkelte und fleckige Böcke besprangen die Tiere.

<<v11>>
11 Der Engel Gottes sprach im Traum zu mir: Jakob! Ich antwortete: Hier
bin ich.

<<v12>>
12 Dann sprach er: Schau hin: Alle Böcke, welche die Tiere bespringen,
sind gestreift, gesprenkelt oder gefleckt. Ich habe nämlich alles
gesehen, was dir Laban antut.

<<v13>>
13 Ich bin der Gott von Bet-El, wo du das Steinmal gesalbt und mir ein
Gelübde gemacht hast. Jetzt auf, zieh fort aus diesem Land und kehr in
deine Heimat zurück! [fn:1]

<<v14>>
14 Rahel und Lea antworteten ihm: Haben wir noch Anteil oder Erbe im
Haus unseres Vaters?

<<v15>>
15 Gelten wir ihm nicht wie Fremde? Er hat uns ja verkauft und sogar
unser Geld aufgezehrt.

<<v16>>
16 Ja, der ganze Reichtum, den Gott unserem Vater weggenommen hat, uns
gehört er und unseren Söhnen. Nun also, tu jetzt alles, was Gott dir
gesagt hat.

<<v17>>
17 Da machte sich Jakob auf, hob seine Söhne und Frauen auf die Kamele

<<v18>>
18 und führte sein ganzes Vieh fort, seinen ganzen Besitz an Vieh, den
er in Paddan-Aram erworben hatte, um zu seinem Vater Isaak nach Kanaan
zurückzukehren.

<<v19>>
19 Laban war weggegangen, um seine Schafe zu scheren; da stahl Rahel die
Götterbilder ihres Vaters [fn:2]

<<v20>>
20 und Jakob überlistete den Aramäer Laban: Er verriet ihm nicht, dass
er sich davonmachen wollte.

<<v21>>
21 Mit allem, was ihm gehörte, machte er sich auf und davon. Er
überquerte den Strom (den Eufrat) und schlug die Richtung zum Gebirge
von Gilead ein.

<<v22>>
22 Am dritten Tag meldete man Laban, Jakob sei auf und davon.

<<v23>>
23 Da nahm Laban seine Brüder mit und jagte ihm sieben Tage lang nach.
Im Gebirge von Gilead war er ihm schon ganz nahe.

<<v24>>
24 Gott aber kam in einem nächtlichen Traum zum Aramäer Laban und sprach
zu ihm: Hüte dich, Jakob auch nur das Geringste vorzuwerfen.

<<v25>>
25 Laban holte Jakob ein, als dieser gerade im Gebirge die Zelte
aufgeschlagen hatte. Da schlug auch Laban mit seinen Brüdern im Gebirge
von Gilead die Zelte auf.

<<v26>>
26 Laban sagte nun zu Jakob: Was hast du getan? Du hast mich überlistet
und meine Töchter wie Kriegsgefangene weggeführt.

<<v27>>
27 Warum hast du mir verheimlicht, dass du dich davonmachen wolltest,
und warum hast du mich überlistet und mir nichts gesagt? Ich hätte dir
gern das Geleit gegeben mit Gesang, Pauken und Harfen.

<<v28>>
28 Du hast mir aber nicht einmal gestattet, meine Söhne und Töchter zu
küssen. Da hast du töricht gehandelt. [fn:3]

<<v29>>
29 Es stünde in meiner Macht, euch Schlimmes anzutun; aber der Gott
eures Vaters hat mir gestern Nacht gesagt: Hüte dich, Jakob auch nur das
Geringste vorzuwerfen.

<<v30>>
30 Nun bist du also fortgezogen, weil du Heimweh hattest nach deinem
Vaterhaus. Aber warum hast du meine Götter gestohlen?

<<v31>>
31 Jakob erwiderte Laban: Ich fürchtete mich und meinte, du könntest mir
deine Töchter wegnehmen.

<<v32>>
32 Bei wem du aber deine Götter findest, der soll nicht am Leben
bleiben. In Gegenwart unserer Brüder durchsuche, was ich habe, und nimm,
was dein ist. Jakob wusste nicht, dass Rahel die Götter gestohlen hatte.

<<v33>>
33 Laban betrat das Zelt Jakobs, das Zelt der Lea und das der beiden
Mägde, fand aber nichts. Vom Zelt der Lea ging er in das Zelt Rahels. [fn:4]

<<v34>>
34 Rahel hatte die Götterbilder genommen, sie in die Satteltasche des
Kamels gelegt und sich darauf gesetzt. Laban durchstöberte das ganze
Zelt, fand aber nichts.

<<v35>>
35 Rahel aber sagte zu ihrem Vater: Sei nicht böse, mein Herr! Ich kann
vor dir nicht aufstehen, es geht mir gerade, wie es eben Frauen ergeht.
Er suchte weiter, die Götterbilder aber fand er nicht.

<<v36>>
36 Da wurde Jakob zornig und begann mit Laban zu streiten. Jakob ergriff
das Wort und sagte zu Laban: Was habe ich verbrochen, was habe ich
Unrechtes getan, dass du mir nachhetzt?

<<v37>>
37 Alle meine Sachen hast du durchstöbert. Was hast du gefunden an
Sachen, die zu deinem Haus gehören? Leg sie her vor meine und deine
Brüder und sie sollen zwischen uns beiden entscheiden. [fn:5]

<<v38>>
38 Schon zwanzig Jahre bin ich bei dir. Deine Schafe und Ziegen hatten
keinen Fehlwurf. Die Böcke deiner Herde habe ich nicht aufgezehrt.

<<v39>>
39 Gerissenes Vieh habe ich dir nicht gebracht; ich habe es selbst
ersetzt. Du hättest ja doch Ersatz gefordert, ob es mir nun bei Tag oder
bei Nacht abhanden kam.

<<v40>>
40 So ging es mir: Bei Tag fraß mich die Hitze, der Frost bei Nacht und
der Schlaf floh meine Augen.

<<v41>>
41 Schon zwanzig Jahre diene ich in deinem Haus, vierzehn Jahre um deine
beiden Töchter und sechs Jahre um dein Vieh. Du aber hast meinen Lohn
zehnmal geändert.

<<v42>>
42 Wäre nicht der Gott meines Vaters, der Gott Abrahams und der
Schrecken Isaaks, für mich eingetreten, dann hättest du mich jetzt mit
leeren Händen weggeschickt. Doch Gott hat mein Elend und die Mühe meiner
Hände gesehen und gestern Nacht hat er entschieden. [fn:6]

<<v43>>
43 Darauf ergriff Laban das Wort und sagte zu Jakob: Die Töchter sind
meine Töchter und die Söhne sind meine Söhne und das Vieh ist mein Vieh
und alles, was du siehst, gehört mir. Was kann ich heute für meine
Töchter tun oder für die Söhne, die sie geboren haben?

<<v44>>
44 Jetzt aber komm, wir wollen einen Vertrag schließen, ich und du. Der
Vertrag soll Zeuge sein zwischen mir und dir.

<<v45>>
45 Da nahm Jakob einen Stein und richtete ihn als Steinmal auf.

<<v46>>
46 Jakob sagte zu seinen Brüdern: Tragt Steine zusammen! Da holten sie
Steine und legten einen Steinhügel an. Dort auf dem Steinhügel aßen sie.

<<v47>>
47 Laban nannte ihn Jegar-Sahaduta und Jakob nannte ihn Gal-Ed.

<<v48>>
48 Dieser Steinhügel, sagte Laban, soll heute Zeuge sein zwischen mir
und dir. Darum gab er ihm den Namen Gal-Ed (Zeugenhügel)

<<v49>>
49 und Mizpa (Spähturm), weil er sagte: Der Herr sei Späher zwischen mir
und dir, wenn wir voneinander nichts mehr wissen. [fn:7]

<<v50>>
50 Solltest du meine Töchter schlecht behandeln oder dir außer meinen
Töchtern noch andere Frauen nehmen - auch wenn kein Mensch bei uns ist:
Sieh, Gott ist Zeuge zwischen mir und dir.

<<v51>>
51 Weiter sagte Laban zu Jakob: Hier, dieser Steinhügel, hier, dieses
Steinmal, das ich zwischen mir und dir errichtet habe -

<<v52>>
52 Zeuge sei dieser Steinhügel. Zeuge sei dieses Steinmal: Nie will ich
diesen Steinhügel in böser Absicht gegen dich überschreiten und nie
sollst du diesen Steinhügel oder dieses Steinmal in böser Absicht gegen
mich überschreiten.

<<v53>>
53 Der Gott Abrahams und der Gott Nahors seien Richter zwischen uns. Da
leistete Jakob einen Eid beim Schrecken seines Vaters Isaak. [fn:8]

<<v54>>
54 Dann schlachtete Jakob auf dem Berg ein Opfertier und lud seine
Brüder zum Mahl ein. Sie aßen und verbrachten die Nacht auf dem Berg.


* Footnotes

[fn:1] Söhne: hier im Sinn von "Enkel".

[fn:2] Die Schafschur war mit einem Fest verbunden. Laban war
daher abgelenkt und für Jakob war das eine günstige Gelegenheit zur
Flucht. Nach dem in der Heimat Labans geltenden Erbrecht gehen die
Bilder der Familiengötter in den Besitz des Erben über. Durch die
Mitnahme der Familiengötter beansprucht Rahel also das Erbrecht.

[fn:3] Söhne: hier im Sinn von "Enkel".

[fn:4] 33-35: Aus der Erzählung klingt eine Verspottung der
heidnischen Götter heraus.

[fn:5] Brüder: hier im Sinn von "Verwandte".

[fn:6] «Schrecken Isaaks» ist ein altertümlicher Gottesname.

[fn:7] Gott soll wie ein Späher darüber wachen, dass beide den
Vertrag einhalten.

[fn:8] zwischen uns: H fügt hinzu «der Gott ihrer Väter», was G
mit Recht weglässt. - Zu «Schrecken seines Vaters» vgl. V. 42 und die
dortige Anmerkung.
