#+TITLE: Gen 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 09:56]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Gen 3.html

* Gen 3
<<verses>>

<<v1>>
* Der Fall des Menschen: 3,1-24
1 Die Schlange war schlauer als alle Tiere des Feldes, die Gott, der
Herr, gemacht hatte. Sie sagte zu der Frau: Hat Gott wirklich gesagt:
Ihr dürft von keinem Baum des Gartens essen? [fn:1] [fn:2]

<<v2>>
2 Die Frau entgegnete der Schlange: Von den Früchten der Bäume im Garten
dürfen wir essen; [fn:3]

<<v3>>
3 nur von den Früchten des Baumes, der in der Mitte des Gartens steht,
hat Gott gesagt: Davon dürft ihr nicht essen und daran dürft ihr nicht
rühren, sonst werdet ihr sterben. [fn:4]

<<v4>>
4 Darauf sagte die Schlange zur Frau: Nein, ihr werdet nicht sterben.

<<v5>>
5 Gott weiß vielmehr: Sobald ihr davon esst, gehen euch die Augen auf;
ihr werdet wie Gott und erkennt Gut und Böse.

<<v6>>
6 Da sah die Frau, dass es köstlich wäre, von dem Baum zu essen, dass
der Baum eine Augenweide war und dazu verlockte, klug zu werden. Sie
nahm von seinen Früchten und aß; sie gab auch ihrem Mann, der bei ihr
war, und auch er aß. [fn:5]

<<v7>>
7 Da gingen beiden die Augen auf und sie erkannten, dass sie nackt
waren. Sie hefteten Feigenblätter zusammen und machten sich einen
Schurz.

<<v8>>
8 Als sie Gott, den Herrn, im Garten gegen den Tagwind einherschreiten
hörten, versteckten sich Adam und seine Frau vor Gott, dem Herrn, unter
den Bäumen des Gartens. [fn:6]

<<v9>>
9 Gott, der Herr, rief Adam zu und sprach: Wo bist du?

<<v10>>
10 Er antwortete: Ich habe dich im Garten kommen hören; da geriet ich in
Furcht, weil ich nackt bin, und versteckte mich.

<<v11>>
11 Darauf fragte er: Wer hat dir gesagt, dass du nackt bist? Hast du von
dem Baum gegessen, von dem zu essen ich dir verboten habe?

<<v12>>
12 Adam antwortete: Die Frau, die du mir beigesellt hast, sie hat mir
von dem Baum gegeben und so habe ich gegessen.

<<v13>>
13 Gott, der Herr, sprach zu der Frau: Was hast du da getan? Die Frau
antwortete: Die Schlange hat mich verführt und so habe ich gegessen.\\
\\

<<v14>>
14 Da sprach Gott, der Herr, zur Schlange: Weil du das getan hast, bist
du verflucht /\\
 unter allem Vieh und allen Tieren des Feldes. /\\
 Auf dem Bauch sollst du kriechen /\\
 und Staub fressen alle Tage deines Lebens.\\
\\

<<v15>>
15 Feindschaft setze ich zwischen dich und die Frau, /\\
 zwischen deinen Nachwuchs und ihren Nachwuchs. /\\
 Er trifft dich am Kopf /\\
 und du triffst ihn an der Ferse.\\
\\

<<v16>>
16 Zur Frau sprach er: Viel Mühsal bereite ich dir, sooft du schwanger
wirst. /\\
 Unter Schmerzen gebierst du Kinder. /\\
 Du hast Verlangen nach deinem Mann; /\\
 er aber wird über dich herrschen.\\
\\

<<v17>>
17 Zu Adam sprach er: Weil du auf deine Frau gehört und von dem Baum
gegessen hast, von dem zu essen ich dir verboten hatte: So ist verflucht
der Ackerboden deinetwegen. /\\
 Unter Mühsal wirst du von ihm essen /\\
 alle Tage deines Lebens.\\
\\

<<v18>>
18 Dornen und Disteln lässt er dir wachsen /\\
 und die Pflanzen des Feldes musst du essen.\\
\\

<<v19>>
19 Im Schweiße deines Angesichts /\\
 sollst du dein Brot essen, /\\
 bis du zurückkehrst zum Ackerboden; /\\
 von ihm bist du ja genommen. /\\
 Denn Staub bist du, zum Staub musst du zurück.\\
\\

<<v20>>
20 Adam nannte seine Frau Eva (Leben), denn sie wurde die Mutter aller
Lebendigen.

<<v21>>
21 Gott, der Herr, machte Adam und seiner Frau Röcke aus Fellen und
bekleidete sie damit.

<<v22>>
22 Dann sprach Gott, der Herr: Seht, der Mensch ist geworden wie wir; er
erkennt Gut und Böse. Dass er jetzt nicht die Hand ausstreckt, auch vom
Baum des Lebens nimmt, davon isst und ewig lebt!

<<v23>>
23 Gott, der Herr, schickte ihn aus dem Garten von Eden weg, damit er
den Ackerboden bestellte, von dem er genommen war.

<<v24>>
24 Er vertrieb den Menschen und stellte östlich des Gartens von Eden die
Kerubim auf und das lodernde Flammenschwert, damit sie den Weg zum Baum
des Lebens bewachten. [fn:7]\\
\\


* Footnotes

[fn:1] Joh 8,44 [[file:~/RoamNotes/EUe-RoundtripHTML/nt/Joh_8.org::v44][Joh 8,44]]

[fn:2] 1-24: In einfacher und bildhafter Sprache und an Hand
eines typischen Beispiels aus dem Alltag stellt der Erzähler die erste
Sünde und ihre verhängnisvollen Folgen dar. Die Schlange ist Sinnbild
für die gefährliche Macht des Bösen und für die Hinterhältigkeit. Der
Baum des Lebens und der Baum der Erkenntnis von Gut und Böse sind Bilder
für die nur Gott zukommenden Eigenschaften der Unsterblichkeit und des
umfassenden Wissens, über die der Mensch nicht von sich aus verfügen
kann, die Gott ihm aber unter Umständen aus Gnade schenkt.

[fn:3] Offb 12,9 [[file:~/RoamNotes/EUe-RoundtripHTML/nt/Offb_12.org::v9][Offb 12,9]]

[fn:4] 2,17 [[file:Gen_2.org::v17][Gen 2,17]]

[fn:5] Weish 2,23f [[file:Weish_2.org::v23][Weish 2,23f]]; Sir 25,24 [[file:Sir_25.org::24][Sir 25,24]]

[fn:6] 3,8 Tagwind: der Wind, der in Palästina auch an heißen
Tagen vom Meer her aufkommt und Kühlung bringt.

[fn:7] Eden ist ein symbolischer Ort großer Fruchtbarkeit, den
man geographisch nicht festlegen kann. - Kerubim sind Engelgestalten.
Übermenschliche Wesen und Feuer bewachen in den Urzeiterzählungen vieler
Völker den Zugang zu verbotenen Orten.
