#+TITLE: Gen 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:07]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Gen 17.html


<<verses>>

<<v1>>
* Die Beschneidung als Bundeszeichen: 17,1-27

1 Als Abram neunundneunzig Jahre alt war, erschien ihm der Herr und
sprach zu ihm: Ich bin Gott, der Allmächtige. Geh deinen Weg vor mir und
sei rechtschaffen!

<<v2>>
2 Ich will einen Bund stiften zwischen mir und dir und dich sehr
zahlreich machen.

<<v3>>
3 Abram fiel auf sein Gesicht nieder; Gott redete mit ihm und sprach:

<<v4>>
4 Das ist mein Bund mit dir: Du wirst Stammvater einer Menge von
Völkern.

<<v5>>
5 Man wird dich nicht mehr Abram nennen. Abraham (Vater der Menge) wirst
du heißen; denn zum Stammvater einer Menge von Völkern habe ich dich
bestimmt.

<<v6>>
6 Ich mache dich sehr fruchtbar und lasse Völker aus dir entstehen;
Könige werden von dir abstammen.

<<v7>>
7 Ich schließe meinen Bund zwischen mir und dir samt deinen Nachkommen,
Generation um Generation, einen ewigen Bund: Dir und deinen Nachkommen
werde ich Gott sein.

<<v8>>
8 Dir und deinen Nachkommen gebe ich ganz Kanaan, das Land, in dem du
als Fremder weilst, für immer zu Eigen und ich will ihnen Gott sein. [fn:1]

<<v9>>
9 Und Gott sprach zu Abraham: Du aber halte meinen Bund, du und deine
Nachkommen, Generation um Generation.

<<v10>>
10 Das ist mein Bund zwischen mir und euch samt deinen Nachkommen, den
ihr halten sollt: Alles, was männlich ist unter euch, muss beschnitten
werden.

<<v11>>
11 Am Fleisch eurer Vorhaut müsst ihr euch beschneiden lassen. Das soll
geschehen zum Zeichen des Bundes zwischen mir und euch.

<<v12>>
12 Alle männlichen Kinder bei euch müssen, sobald sie acht Tage alt
sind, beschnitten werden in jeder eurer Generationen, seien sie im Haus
geboren oder um Geld von irgendeinem Fremden erworben, der nicht von dir
abstammt.

<<v13>>
13 Beschnitten muss sein der in deinem Haus Geborene und der um Geld
Erworbene. So soll mein Bund, dessen Zeichen ihr an eurem Fleisch tragt,
ein ewiger Bund sein.

<<v14>>
14 Ein Unbeschnittener, eine männliche Person, die am Fleisch ihrer
Vorhaut nicht beschnitten ist, soll aus ihrem Stammesverband ausgemerzt
werden. Er hat meinen Bund gebrochen.

<<v15>>
15 Weiter sprach Gott zu Abraham: Deine Frau Sarai sollst du nicht mehr
Sarai nennen, sondern Sara (Herrin) soll sie heißen.

<<v16>>
16 Ich will sie segnen und dir auch von ihr einen Sohn geben. Ich segne
sie, sodass Völker aus ihr hervorgehen; Könige über Völker sollen ihr
entstammen. [fn:2]

<<v17>>
17 Da fiel Abraham auf sein Gesicht nieder und lachte. Er dachte: Können
einem Hundertjährigen noch Kinder geboren werden und kann Sara als
Neunzigjährige noch gebären? [fn:3]

<<v18>>
18 Dann sagte Abraham zu Gott: Wenn nur Ismael vor dir am Leben bleibt!

<<v19>>
19 Gott entgegnete: Nein, deine Frau Sara wird dir einen Sohn gebären
und du sollst ihn Isaak nennen. Ich werde meinen Bund mit ihm schließen
als einen ewigen Bund für seine Nachkommen. [fn:4]

<<v20>>
20 Auch was Ismael angeht, erhöre ich dich. Ja, ich segne ihn, ich lasse
ihn fruchtbar und sehr zahlreich werden. Zwölf Fürsten wird er zeugen
und ich mache ihn zu einem großen Volk.

<<v21>>
21 Meinen Bund aber schließe ich mit Isaak, den dir Sara im nächsten
Jahr um diese Zeit gebären wird.

<<v22>>
22 Als Gott das Gespräch beendet hatte, verließ er Abraham und fuhr zur
Höhe auf.

<<v23>>
23 Abraham nahm nun seinen Sohn Ismael sowie alle in seinem Haus
Geborenen und alle um Geld Erworbenen, alle männlichen Personen vom Haus
Abraham, und beschnitt das Fleisch ihrer Vorhaut noch am selben Tag, wie
Gott ihm befohlen hatte.

<<v24>>
24 Abraham war neunundneunzig Jahre alt, als er am Fleisch seiner
Vorhaut beschnitten wurde,

<<v25>>
25 und sein Sohn Ismael war dreizehn Jahre alt, als er am Fleisch seiner
Vorhaut beschnitten wurde.

<<v26>>
26 Am selben Tag wurden Abraham und sein Sohn Ismael beschnitten.

<<v27>>
27 Auch alle Männer seines Hauses, die im Haus Geborenen und die um Geld
von Fremden Erworbenen, wurden mit ihm beschnitten.\\
\\


* Footnotes

[fn:1] 13,15 [[file:Gen_13.org::v15][Gen 13,15]]; 15,18-21 [[file:Gen_15.org::v18][Gen 15,18-21]]; 26,3-5 [[file:Gen_26.org::v3][Gen 26,3-5]]; 28,3f [[file:Gen_28.org::v3][Gen 28,3f]]; 35,12 [[file:Gen_35.org::v12][Gen 35,12]]

[fn:2] 18,10-14 [[file:Gen_18.org::v10][Gen 18,10-14]]

[fn:3] Anspielung auf die Bedeutung des Namens Isaak, hebr.:
jizchák (= er lacht; vgl. 18,12-15 [[file:Gen_18.org::v12][Gen 18,12-15]]).

[fn:4] 18,10 [[file:Gen_18.org::v10][Gen 18,10]]; 21,1-8 [[file:Gen_21.org::v1][Gen 21,1-8]]
