#+TITLE: Gen 47 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Gen 47.html

* Gen 47
<<verses>>

<<v1>>
1 Josef ging also hin, berichtete dem Pharao und sagte: Mein Vater und
meine Brüder sind mit ihren Schafen, Ziegen und Rindern und mit allem,
was ihnen gehört, aus Kanaan gekommen. Sie sind bereits in Goschen.

<<v2>>
2 Aus dem Kreis seiner Brüder hatte er fünf Männer mitgebracht und
stellte sie dem Pharao vor.

<<v3>>
3 Der Pharao fragte Josefs Brüder: Womit beschäftigt ihr euch? Sie
antworteten dem Pharao: Hirten von Schafen und Ziegen sind deine
Knechte; wir sind es und unsere Väter waren es auch schon.

<<v4>>
4 Weiter sagten sie zum Pharao: Wir sind gekommen, um uns als Fremde im
Land aufzuhalten. Es gibt ja keine Weide für das Vieh deiner Knechte,
denn schwer lastet die Hungersnot auf Kanaan. Nun möchten sich deine
Knechte in Goschen niederlassen.

<<v5>>
5 Darauf sagte der Pharao zu Josef: Dein Vater und deine Brüder sind
also zu dir gekommen.

<<v6>>
6 Ägypten steht dir offen. Im besten Teil des Landes lass deinen Vater
und deine Brüder wohnen! Sie sollen sich in Goschen niederlassen. Wenn
du aber unter ihnen tüchtige Leute kennst, dann setze sie als Aufseher
über meine Herden ein!

<<v7>>
7 Darauf führte Josef seinen Vater Jakob hinein und stellte ihn dem
Pharao vor. Jakob grüßte den Pharao mit einem Segenswunsch.

<<v8>>
8 Der Pharao redete Jakob an: Wie viele Lebensjahre zählst du?

<<v9>>
9 Jakob gab dem Pharao zur Antwort: Die Zahl der Jahre meiner
Pilgerschaft beträgt hundertdreißig. Gering an Zahl und unglücklich
waren meine Lebensjahre und sie reichen nicht heran an die Lebensjahre
meiner Väter in den Tagen ihrer Pilgerschaft.

<<v10>>
10 Jakob verabschiedete sich vom Pharao mit einem Segenswunsch.

<<v11>>
11 Josef siedelte seinen Vater und seine Brüder an und wies ihnen den
Grundbesitz in Ägypten zu, im besten Teil des Landes, im Gebiet von
Ramses, wie der Pharao verfügt hatte.

<<v12>>
12 Josef versorgte seinen Vater und seine Brüder und das ganze Haus
seines Vaters mit so viel Brot, dass die Kinder genug zu essen hatten.\\
\\

<<v13>>
* Josefs Verwaltung in Ägypten: 47,13-26
:PROPERTIES:
:CUSTOM_ID: josefs-verwaltung-in-ägypten-4713-26
:END:
13 Im ganzen Land gab es kein Brot und der Hunger war sehr drückend.
Ägypten und Kanaan waren vor Hunger erschöpft.

<<v14>>
14 Josef hatte das Geld, das in Ägypten und in Kanaan im Umlauf war, für
das Getreide, das sie kaufen mussten, eingezogen und in den Palast des
Pharao gebracht.

<<v15>>
15 So war das Geld in Ägypten und Kanaan ausgegangen. Alle Ägypter kamen
zu Josef und sagten: Gib uns Brot! Warum sollen wir vor deinen Augen
umkommen? Das Geld ist nämlich zu Ende.

<<v16>>
16 Liefert euer Vieh ab, sagte Josef, dann gebe ich euch dafür Brot,
wenn das Geld zu Ende ist.

<<v17>>
17 So brachten sie ihr Vieh zu Josef und Josef verkaufte ihnen Brot um
den Preis der Pferde, ihrer Bestände an Schafen und Ziegen, an Rindern
und Eseln. Er versorgte die Leute also in jenem Jahr gegen ihren ganzen
Viehbestand mit Brot.

<<v18>>
18 Das Jahr ging indes zu Ende und im nächsten Jahr kamen sie und sagten
zu ihm: Wir können unserem Herrn nicht verhehlen, dass das Geld zu Ende
und unser Viehbestand in den Besitz unseres Herrn übergegangen ist. Wie
unser Herr sieht, haben wir nichts mehr als unsere Leiber und unser
Ackerland.

<<v19>>
19 Warum sollen wir vor deinen Augen umkommen, wir selbst und auch unser
Ackerland? Kauf uns und unsere Äcker um Brot! Wir und unser Ackerland
wollen dem Pharao dienstbar sein. Stell Saatgut zur Verfügung, so werden
wir am Leben bleiben, wir müssen dann nicht sterben und das Ackerland
braucht nicht zu verkommen.

<<v20>>
20 Josef kaufte also das ganze Ackerland der Ägypter für den Pharao auf;
denn die Ägypter verkauften alle ihr Feld, weil sie der Hunger dazu
zwang. So wurde das Land Eigentum des Pharao.

<<v21>>
21 Das Volk aber machte er ihm Leibeigen von einem Ende Ägyptens bis zum
andern.

<<v22>>
22 Nur das Ackerland der Priester kaufte er nicht auf, denn den
Priestern steht ein festes Einkommen vom Pharao zu; sie leben von dem
festen Einkommen, das ihnen der Pharao gewährt. Darum brauchten sie ihr
Ackerland nicht zu verkaufen.

<<v23>>
23 Nun sprach Josef zum Volk: Seht, heute habe ich euch und euer
Ackerland für den Pharao gekauft. Hier habt ihr Saatgut; bestellt nun
die Äcker!

<<v24>>
24 Vom Ertrag liefert ihr dann ein Fünftel dem Pharao ab, vier Teile
aber gehören euch als Saatgut für das Feld sowie als Nahrung für euch,
für die Leute in euren Häusern und für eure Kinder.

<<v25>>
25 Da antworteten sie: Du hast uns am Leben erhalten. Wenn wir das
Wohlwollen unseres Herrn finden, wollen wir gern dem Pharao als Knechte
dienen.

<<v26>>
26 So verfügte Josef als gültiges Recht bis auf den heutigen Tag, dass
das Ackerland Ägyptens zugunsten des Pharao mit einem Fünftel zu
besteuern ist. Nur die Äcker der Priester wurden nicht Eigentum des
Pharao.\\
\\

<<v27>>
* Jakobs letzter Wille: 47,27 - 48,22
:PROPERTIES:
:CUSTOM_ID: jakobs-letzter-wille-4727---4822
:END:
27 Israel ließ sich in Ägypten nieder, in der Landschaft Goschen. Sie
wurden dort ansässig, waren fruchtbar und vermehrten sich sehr.

<<v28>>
28 Jakob lebte noch siebzehn Jahre in Ägypten und die Tage Jakobs, seine
Lebensjahre, betrugen hundertsiebenundvierzig Jahre.

<<v29>>
29 Als die Zeit kam, da Israel sterben sollte, rief er seinen Sohn Josef
und sagte zu ihm: Wenn ich dein Wohlwollen gefunden habe, leg deine Hand
unter meine Hüfte, dass du nach Treu und Glauben an mir handeln wirst:
Begrab mich nicht in Ägypten! [fn:1]

<<v30>>
30 Bin ich zu meinen Vätern entschlafen, dann bring mich fort aus
Ägypten und begrab mich in der Grabstätte meiner Väter! Er antwortete:
Ich will tun, wie du gesagt hast.

<<v31>>
31 Da sagte Jakob: Leiste mir einen Eid! Er leistete ihm den Eid. Darauf
neigte sich Israel über das Kopfende seines Bettes.


* Footnotes

[fn:1] Zu der Schwurgebärde vgl. die Anmerkung zu 24,2.
