#+TITLE: Gen 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:01]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Gen 9.html


<<verses>>

<<v1>>
* Gottes Bund mit Noach: 9,1-17

1 Dann segnete Gott Noach und seine Söhne und sprach zu ihnen: Seid
fruchtbar, vermehrt euch und bevölkert die Erde! [fn:1]

<<v2>>
2 Furcht und Schrecken vor euch soll sich auf alle Tiere der Erde legen,
auf alle Vögel des Himmels, auf alles, was sich auf der Erde regt, und
auf alle Fische des Meeres; euch sind sie übergeben.

<<v3>>
3 Alles Lebendige, das sich regt, soll euch zur Nahrung dienen. Alles
übergebe ich euch wie die grünen Pflanzen. [fn:2]

<<v4>>
4 Nur Fleisch, in dem noch Blut ist, dürft ihr nicht essen.

<<v5>>
5 Wenn aber euer Blut vergossen wird, fordere ich Rechenschaft, und zwar
für das Blut eines jeden von euch. Von jedem Tier fordere ich
Rechenschaft und vom Menschen. Für das Leben des Menschen fordere ich
Rechenschaft von jedem seiner Brüder.

<<v6>>
6 Wer Menschenblut vergießt, dessen Blut wird durch Menschen vergossen.
Denn: Als Abbild Gottes hat er den Menschen gemacht. [fn:3]

<<v7>>
7 Seid fruchtbar und vermehrt euch; bevölkert die Erde und vermehrt euch
auf ihr! [fn:4]

<<v8>>
8 Dann sprach Gott zu Noach und seinen Söhnen, die bei ihm waren:

<<v9>>
9 Hiermit schließe ich meinen Bund mit euch und mit euren Nachkommen

<<v10>>
10 und mit allen Lebewesen bei euch, mit den Vögeln, dem Vieh und allen
Tieren des Feldes, mit allen Tieren der Erde, die mit euch aus der Arche
gekommen sind.

<<v11>>
11 Ich habe meinen Bund mit euch geschlossen: Nie wieder sollen alle
Wesen aus Fleisch vom Wasser der Flut ausgerottet werden; nie wieder
soll eine Flut kommen und die Erde verderben.

<<v12>>
12 Und Gott sprach: Das ist das Zeichen des Bundes, den ich stifte
zwischen mir und euch und den lebendigen Wesen bei euch für alle
kommenden Generationen:

<<v13>>
13 Meinen Bogen setze ich in die Wolken; er soll das Bundeszeichen sein
zwischen mir und der Erde.

<<v14>>
14 Balle ich Wolken über der Erde zusammen und erscheint der Bogen in
den Wolken,

<<v15>>
15 dann gedenke ich des Bundes, der besteht zwischen mir und euch und
allen Lebewesen, allen Wesen aus Fleisch, und das Wasser wird nie wieder
zur Flut werden, die alle Wesen aus Fleisch vernichtet.

<<v16>>
16 Steht der Bogen in den Wolken, so werde ich auf ihn sehen und des
ewigen Bundes gedenken zwischen Gott und allen lebenden Wesen, allen
Wesen aus Fleisch auf der Erde.

<<v17>>
17 Und Gott sprach zu Noach: Das ist das Zeichen des Bundes, den ich
zwischen mir und allen Wesen aus Fleisch auf der Erde geschlossen
habe.\\
\\

<<v18>>
* Noachs Fluch und Segen: 9,18-29

18 Die Söhne Noachs, die aus der Arche gekommen waren, sind Sem, Ham und
Jafet. Ham ist der Vater Kanaans.

<<v19>>
19 Diese drei sind die Söhne Noachs; von ihnen stammen alle Völker der
Erde ab.

<<v20>>
20 Noach wurde der erste Ackerbauer und pflanzte einen Weinberg.

<<v21>>
21 Er trank von dem Wein, wurde davon betrunken und lag entblößt in
seinem Zelt.

<<v22>>
22 Ham, der Vater Kanaans, sah die Blöße seines Vaters und erzählte
davon draußen seinen Brüdern.

<<v23>>
23 Da nahmen Sem und Jafet einen Überwurf; den legten sich beide auf die
Schultern, gingen rückwärts und bedeckten die Blöße ihres Vaters. Sie
hatten ihr Gesicht abgewandt und konnten die Blöße des Vaters nicht
sehen.

<<v24>>
24 Als Noach aus seinem Rausch erwachte und erfuhr, was ihm sein zweiter
Sohn angetan hatte,\\
\\

<<v25>>
25 sagte er: Verflucht sei Kanaan. /\\
 Der niedrigste Knecht sei er seinen Brüdern.\\
\\

<<v26>>
26 Und weiter sagte er: Gepriesen sei der Herr, der Gott Sems, /\\
 Kanaan aber sei sein Knecht.\\
\\

<<v27>>
27 Raum schaffe Gott für Jafet. /\\
 In Sems Zelten wohne er, /\\
 Kanaan aber sei sein Knecht. [fn:5]\\
\\

<<v28>>
28 Noach lebte nach der Flut noch dreihundertfünfzig Jahre.

<<v29>>
29 Die gesamte Lebenszeit Noachs betrug neunhundertfünfzig Jahre, dann
starb er.\\
\\


* Footnotes

[fn:1] 1,28 [[file:Gen_1.org::v28][Gen 1,28]]; 9,7 [[file:Gen_9.org::v7][Gen 9,7]]

[fn:2] 1,29 [[file:Gen_1.org::v29][Gen 1,29]]

[fn:3] 1,26-28 [[file:Gen_1.org::v26][Gen 1,26-28]]

[fn:4] 9,1 [[file:Gen_9.org::v1][Gen 9,1]]

[fn:5] Wortspiel mit dem Namen Jafet und dem ähnlich klingenden
Zeitwort "er schaffe Raum" (jaft).
