#+TITLE: Gen 22 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:13]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Gen 22.html


<<verses>>

<<v1>>
* Abrahams Opfer: 22,1-19
1 Nach diesen Ereignissen stellte Gott Abraham auf die Probe. Er sprach
zu ihm: Abraham! Er antwortete: Hier bin ich. [fn:1]

<<v2>>
2 Gott sprach: Nimm deinen Sohn, deinen einzigen, den du liebst, Isaak,
geh in das Land Morija und bring ihn dort auf einem der Berge, den ich
dir nenne, als Brandopfer dar.

<<v3>>
3 Frühmorgens stand Abraham auf, sattelte seinen Esel, holte seine
beiden Jungknechte und seinen Sohn Isaak, spaltete Holz zum Opfer und
machte sich auf den Weg zu dem Ort, den ihm Gott genannt hatte.

<<v4>>
4 Als Abraham am dritten Tag aufblickte, sah er den Ort von weitem.

<<v5>>
5 Da sagte Abraham zu seinen Jungknechten: Bleibt mit dem Esel hier! Ich
will mit dem Knaben hingehen und anbeten; dann kommen wir zu euch
zurück.

<<v6>>
6 Abraham nahm das Holz für das Brandopfer und lud es seinem Sohn Isaak
auf. Er selbst nahm das Feuer und das Messer in die Hand. So gingen
beide miteinander.

<<v7>>
7 Nach einer Weile sagte Isaak zu seinem Vater Abraham: Vater! Er
antwortete: Ja, mein Sohn! Dann sagte Isaak: Hier ist Feuer und Holz. Wo
aber ist das Lamm für das Brandopfer?

<<v8>>
8 Abraham entgegnete: Gott wird sich das Opferlamm aussuchen, mein Sohn.
Und beide gingen miteinander weiter.

<<v9>>
9 Als sie an den Ort kamen, den ihm Gott genannt hatte, baute Abraham
den Altar, schichtete das Holz auf, fesselte seinen Sohn Isaak und legte
ihn auf den Altar, oben auf das Holz.

<<v10>>
10 Schon streckte Abraham seine Hand aus und nahm das Messer, um seinen
Sohn zu schlachten.

<<v11>>
11 Da rief ihm der Engel des Herrn vom Himmel her zu: Abraham, Abraham!
Er antwortete: Hier bin ich.

<<v12>>
12 Jener sprach: Streck deine Hand nicht gegen den Knaben aus und tu ihm
nichts zuleide! Denn jetzt weiß ich, dass du Gott fürchtest; du hast mir
deinen einzigen Sohn nicht vorenthalten.

<<v13>>
13 Als Abraham aufschaute, sah er: Ein Widder hatte sich hinter ihm mit
seinen Hörnern im Gestrüpp verfangen. Abraham ging hin, nahm den Widder
und brachte ihn statt seines Sohnes als Brandopfer dar.

<<v14>>
14 Abraham nannte jenen Ort Jahwe-Jire (Der Herr sieht), wie man noch
heute sagt: Auf dem Berg lässt sich der Herr sehen.

<<v15>>
15 Der Engel des Herrn rief Abraham zum zweiten Mal vom Himmel her zu

<<v16>>
16 und sprach: Ich habe bei mir geschworen - Spruch des Herrn: Weil du
das getan hast und deinen einzigen Sohn mir nicht vorenthalten hast,

<<v17>>
17 will ich dir Segen schenken in Fülle und deine Nachkommen zahlreich
machen wie die Sterne am Himmel und den Sand am Meeresstrand. Deine
Nachkommen sollen das Tor ihrer Feinde einnehmen. [fn:2]

<<v18>>
18 Segnen sollen sich mit deinen Nachkommen alle Völker der Erde, weil
du auf meine Stimme gehört hast.

<<v19>>
19 Darauf kehrte Abraham zu seinen Jungknechten zurück. Sie machten sich
auf und gingen miteinander nach Beerscheba. Abraham blieb in Beerscheba
wohnen.\\
\\

<<v20>>
* Abrahams Verwandtschaft: 22,20-24

20 Nach diesen Ereignissen meldete man Abraham: Auch Milka hat deinem
Bruder Nahor Söhne geboren:

<<v21>>
21 Uz, seinen Erstgeborenen, dessen Bruder Bus sowie Kemuël, den
Stammvater der Aramäer,

<<v22>>
22 ferner Kesed, Haso, Pildasch, Jidlaf und Betuël.

<<v23>>
23 Betuël zeugte Rebekka. Diese acht gebar Milka dem Nahor, dem Bruder
Abrahams. Er hatte noch eine Nebenfrau namens Rëuma.

<<v24>>
24 Auch sie bekam Kinder, nämlich Tebach, Gaham, Tahasch und Maacha.\\
\\


* Footnotes

[fn:1] 1-19: Gott stellt Abrahams Glaubensgehorsam auf die
äußerste Probe, die Abraham in der Bereitschaft zum schwersten Opfer
besteht. In der Erzählung wird aber auch deutlich, dass Gott das
Kinderopfer ablehnt, das bei den Kanaanitern bezeugt ist.

[fn:2] 12,2f [[file:Gen_12.org::v2][Gen 12,2f]]; 18,18 [[file:Gen_18.org::v18][Gen 18,18]]; 26,4f [[file:Gen_26.org::v4][Gen 26,4f]]; 28,14 [[file:Gen_28.org::v14][Gen 28,14]]; Gal 3,16 [[file:~/Documents/EUe-RoundtripHTML/nt/Gal_3.org::v16][Gal 3,16]]
