#+TITLE: Gen 50 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:38]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Gen 50.html

* Gen 50
<<verses>>

<<v1>>
1 Josef warf sich über seinen Vater, weinte um ihn und küsste ihn.

<<v2>>
2 Darauf befahl er den Ärzten, die ihm zu Dienste standen, seinen Vater
einzubalsamieren. Die Ärzte balsamierten also Israel ein.

<<v3>>
3 Darüber vergingen vierzig volle Tage, denn so lange dauerte die
Einbalsamierung. Die Ägypter beweinten ihn siebzig Tage lang.

<<v4>>
4 Als die Tage der Trauer vorüber waren, sagte Josef zu den Hofleuten
des Pharao: Wenn ich euer Wohlwollen genieße, tragt dem Pharao dieses
mein Anliegen vor:

<<v5>>
5 Mein Vater hat mich schwören lassen und gesagt: Ich muss sterben; in
dem Grab, das ich mir in Kanaan angelegt habe, dort begrabt mich! Nun
also möchte ich hinaufziehen und meinen Vater begraben; dann komme ich
wieder zurück.

<<v6>>
6 Da sagte der Pharao: Zieh hinauf, begrabe deinen Vater, wie du
geschworen hast.

<<v7>>
7 Josef zog hinauf, um seinen Vater zu begraben. Mit ihm zogen alle
Hofleute des Pharao, die Ältesten seines Hofes und alle Ältesten
Ägyptens,

<<v8>>
8 das ganze Haus Josef, seine Brüder und das Haus seines Vaters. Nur
ihre Kinder, ihre Schafe, Ziegen und Rinder ließen sie in Goschen
zurück.

<<v9>>
9 Auch die Wagen und die dazugehörige Mannschaft zogen mit ihm, sodass
es ein sehr großer Zug wurde.

<<v10>>
10 Als sie nach Goren-Atad jenseits des Jordan gekommen waren, hielten
sie dort eine sehr große, würdige Totenklage; sieben Tage hielt er um
seinen Vater Trauer.

<<v11>>
11 Die Einheimischen, die Kanaaniter, beobachteten die Trauerfeier in
Goren-Atad und sagten: Eine würdige Trauerfeier veranstalten da die
Ägypter. Darum heißt der Ort Abel-Mizrajim (Ägyptertrauer); er liegt
jenseits des Jordan.

<<v12>>
12 Jakobs Söhne taten an Jakob so, wie er ihnen aufgetragen hatte.

<<v13>>
13 Sie brachten ihn nach Kanaan und begruben ihn in der Höhle des
Grundstücks von Machpela. Abraham hatte das Grundstück bei Mamre als
eigene Grabstätte von dem Hetiter Efron gekauft.\\
\\

<<v14>>
* Josefs letzte Lebensjahre und sein Tod: 50,14-26
14 Nachdem Josef seinen Vater begraben hatte, kehrte er nach Ägypten
zurück, zusammen mit seinen Brüdern und allen, die mitgezogen waren, um
seinen Vater zu begraben.

<<v15>>
15 Als Josefs Brüder sahen, dass ihr Vater tot war, sagten sie: Wenn
sich Josef nur nicht feindselig gegen uns stellt und uns alles Böse
vergilt, das wir ihm getan haben.

<<v16>>
16 Deshalb ließen sie Josef wissen: Dein Vater hat uns, bevor er starb,
aufgetragen:

<<v17>>
17 So sagt zu Josef: Vergib doch deinen Brüdern ihre Untat und Sünde,
denn Schlimmes haben sie dir angetan. Nun also vergib doch die Untat der
Knechte des Gottes deines Vaters! Als man ihm diese Worte überbrachte,
musste Josef weinen.

<<v18>>
18 Seine Brüder gingen dann auch selbst hin, fielen vor ihm nieder und
sagten: Hier sind wir als deine Sklaven.

<<v19>>
19 Josef aber antwortete ihnen: Fürchtet euch nicht! Stehe ich denn an
Gottes Stelle?

<<v20>>
20 Ihr habt Böses gegen mich im Sinne gehabt, Gott aber hatte dabei
Gutes im Sinn, um zu erreichen, was heute geschieht: viel Volk am Leben
zu erhalten.

<<v21>>
21 Nun also fürchtet euch nicht! Ich will für euch und eure Kinder
sorgen. So tröstete er sie und redete ihnen freundlich zu.

<<v22>>
22 Josef blieb in Ägypten, er und das Haus seines Vaters. Josef wurde
hundertzehn Jahre alt.

<<v23>>
23 Er sah noch Efraims Söhne und Enkel. Auch die Söhne Machirs, des
Sohnes Manasses, kamen auf Josefs Knien zur Welt. [fn:1]

<<v24>>
24 Dann sprach Josef zu seinen Brüdern: Ich muss sterben. Gott wird sich
euer annehmen, er wird euch aus diesem Land heraus und in jenes Land
hinaufführen, das er Abraham, Isaak und Jakob mit einem Eid zugesichert
hat.

<<v25>>
25 Josef ließ die Söhne Israels schwören: Wenn Gott sich euer annimmt,
dann nehmt meine Gebeine von hier mit hinauf!

<<v26>>
26 Josef starb im Alter von hundertzehn Jahren. Man balsamierte ihn ein
und legte ihn in Ägypten in einen Sarg.\\
\\


* Footnotes

[fn:1] Josef nimmt die Kinder Manasses zum Zeichen der Adoption
unmittelbar nach ihrer Geburt auf seine Knie (vgl. 30,3 [[file:Gen_30.org::v3][Gen 30,3]]). 
