#+TITLE: Gen 29 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 10:21]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Gen 29.html


<<verses>>

<<v1>>
* Jakobs Frauen und Söhne: 29,1 - 30,24

1 Jakob machte sich auf und zog weiter ins Land der Söhne des Ostens. [fn:1]

<<v2>>
2 Eines Tages sah er einen Brunnen auf freiem Feld. Dort lagerten drei
Herden von Schafen und Ziegen; denn aus dem Brunnen tränkte man die
Herden. Ein großer Stein lag über der Brunnenöffnung.

<<v3>>
3 Wenn sich dort alle Herden eingefunden hatten, schob man den Stein von
der Brunnenöffnung und tränkte das Vieh. Dann schob man den Stein wieder
zurück an seinen Platz über der Brunnenöffnung.

<<v4>>
4 Jakob fragte die Leute dort: Meine Brüder, woher seid ihr? Aus Haran,
antworteten sie.

<<v5>>
5 Da sagte er zu ihnen: Kennt ihr Laban, den Sohn Nahors? Ja, wir kennen
ihn, antworteten sie.

<<v6>>
6 Weiter fragte er sie: Geht es ihm gut? Sie entgegneten: Ja, es geht
ihm gut. Aber da kommt gerade seine Tochter Rahel mit der Herde.

<<v7>>
7 Da sagte er: Es ist noch mitten am Tag und nicht die Zeit, das Vieh
zusammenzutreiben. Tränkt doch die Tiere, dann geht und weidet weiter!

<<v8>>
8 Da sagten sie: Das können wir nicht, bevor nicht alle Herden sich
eingefunden haben. Erst dann kann man den Stein von der Brunnenöffnung
wegschieben und die Tiere tränken.

<<v9>>
9 Während er sich noch mit ihnen unterhielt, war Rahel mit der Herde,
die ihrem Vater gehörte, eingetroffen; denn sie war Hirtin.

<<v10>>
10 Als Jakob Rahel, die Tochter Labans, des Bruders seiner Mutter, und
dessen Herde sah, trat er hinzu, schob den Stein von der Brunnenöffnung
und tränkte das Vieh Labans, des Bruders seiner Mutter.

<<v11>>
11 Dann küsste er Rahel und begann laut zu weinen.

<<v12>>
12 Jakob sagte zu Rahel, dass er ein Bruder ihres Vaters und der Sohn
Rebekkas sei. Da lief sie weg und erzählte es ihrem Vater.

<<v13>>
13 Als Laban von Jakob, dem Sohn seiner Schwester, hörte, lief er ihm
entgegen; er umarmte und küsste ihn und führte ihn in sein Haus. Jakob
erzählte Laban die ganze Geschichte.

<<v14>>
14 Da erwiderte ihm Laban: Du bist wirklich mein Bein und mein Fleisch.
Als Jakob etwa einen Monat bei ihm geblieben war, [fn:2]

<<v15>>
15 sagte Laban zu ihm: Sollst du mir umsonst dienen, weil du mein Bruder
bist? Sag mir, welchen Lohn du haben willst.

<<v16>>
16 Laban hatte zwei Töchter; die ältere hieß Lea, die jüngere Rahel.

<<v17>>
17 Die Augen Leas waren matt, Rahel aber war schön von Gestalt und hatte
ein schönes Gesicht.

<<v18>>
18 Jakob hatte Rahel lieb und so sagte er: Ich will dir um die jüngere
Tochter Rahel sieben Jahre dienen.

<<v19>>
19 Laban entgegnete: Es ist besser, ich gebe sie dir als einem anderen.
Bleib bei mir!

<<v20>>
20 Jakob diente also um Rahel sieben Jahre. Weil er sie liebte, kamen
sie ihm wie wenige Tage vor. [fn:3]

<<v21>>
21 Dann aber sagte er zu Laban: Gib mir jetzt meine Frau; denn meine
Zeit ist um und ich will nun zu ihr gehen.

<<v22>>
22 Da ließ Laban alle Männer des Ortes zusammenkommen und veranstaltete
ein Festmahl.

<<v23>>
23 Am Abend nahm er aber seine Tochter Lea, führte sie zu ihm und Jakob
wohnte ihr bei.

<<v24>>
24 Laban gab seine Magd Silpa seiner Tochter Lea zur Magd.

<<v25>>
25 Am Morgen stellte sich heraus: Es war Lea. Da sagte Jakob zu Laban:
Was hast du mir angetan? Habe ich dir denn nicht um Rahel gedient? Warum
hast du mich hintergangen?

<<v26>>
26 Laban erwiderte: Es ist hierzulande nicht üblich, die Jüngere vor der
Älteren zur Ehe zu geben.

<<v27>>
27 Verbring mit dieser noch die Brautwoche, dann soll dir auch die
andere gehören um weitere sieben Jahre Dienst.

<<v28>>
28 Jakob ging darauf ein. Er verbrachte mit Lea die Brautwoche, dann gab
ihm Laban seine Tochter Rahel zur Frau.

<<v29>>
29 Laban gab seine Magd Bilha seiner Tochter Rahel zur Magd.

<<v30>>
30 Jakob wohnte Rahel ebenfalls bei und er liebte Rahel mehr als Lea. Er
blieb noch weitere sieben Jahre bei Laban im Dienst.

<<v31>>
31 Als der Herr sah, dass Lea zurückgesetzt wurde, öffnete er ihren
Mutterschoß, Rahel aber blieb unfruchtbar.

<<v32>>
32 Lea wurde schwanger und gebar einen Sohn. Sie nannte ihn Ruben (Seht,
ein Sohn!); denn sie sagte: Der Herr hat mein Elend gesehen. Jetzt wird
mein Mann mich lieben.

<<v33>>
33 Sie wurde abermals schwanger und gebar einen Sohn. Da sagte sie: Der
Herr hat gehört, dass ich zurückgesetzt bin, und hat mir auch noch
diesen geschenkt. Sie nannte ihn Simeon (Hörer).

<<v34>>
34 Sie wurde noch einmal schwanger und gebar einen Sohn. Da sagte sie:
Jetzt endlich wird mein Mann an mir hängen, denn ich habe ihm drei Söhne
geboren. Darum nannte sie ihn Levi (Anhang).

<<v35>>
35 Abermals wurde sie schwanger und gebar einen Sohn. Da sagte sie:
Diesmal will ich dem Herrn danken. Darum nannte sie ihn Juda (Dank).
Dann bekam sie keine Kinder mehr.


* Footnotes

[fn:1] 1-30,24: Jakobs Ehe mit zwei Schwestern widerspricht Lev
18,18, wird aber vor der Gesetzgebung vom Sinai nicht beanstandet. Zu
den Söhnen von den zwei Mägden vgl. die Anmerkung zu 16,2 [[file:Gen_16.org::v2][Gen 16,2]].

[fn:2] Zu der Redensart vgl. die Anmerkung zu 2,21-23 [[file:Gen_2.org::v21][Gen 2,21-23]].

[fn:3] Hos 12,13 [[file:Hos_12.org::v13][Hos 12,13]]
