:PROPERTIES:
:ID:       df7b76bc-048c-4bb0-a0f3-a20927d7fc96
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Hosea* -- [[file:Hos_1.html][1]]
[[file:Hos_2.html][2]] [[file:Hos_3.html][3]] *4* [[file:Hos_5.html][5]]
[[file:Hos_6.html][6]] ... [[file:Hos_14.html][14]]

--------------

* Hos 4
  :PROPERTIES:
  :CUSTOM_ID: hos-4
  :END:

<<verses>>

<<v1>>
** Schuld und Rettung: 4,1 - 14,9
   :PROPERTIES:
   :CUSTOM_ID: schuld-und-rettung-41---149
   :END:
**** Das Gericht über die Priester: 4,1-10
     :PROPERTIES:
     :CUSTOM_ID: das-gericht-über-die-priester-41-10
     :END:
1 Hört das Wort des Herrn, ihr Söhne Israels! /\\
 Denn der Herr erhebt Klage /\\
 gegen die Bewohner des Landes: Es gibt keine Treue und keine Liebe /\\
 und keine Gotteserkenntnis im Land. ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v2>>
2 Nein, Fluch und Betrug, /\\
 Mord, Diebstahl und Ehebruch machen sich breit, /\\
 Bluttat reiht sich an Bluttat. ^{[[#fn3][3]]}\\
\\

<<v3>>
3 Darum soll das Land verdorren, /\\
 jeder, der darin wohnt, soll verwelken, samt den Tieren des Feldes /\\
 und den Vögeln des Himmels; /\\
 auch die Fische im Meer sollen zugrunde gehen. ^{[[#fn4][4]]}\\
\\

<<v4>>
4 Doch nicht irgendeiner wird verklagt, /\\
 nicht irgendwer wird gerügt, /\\
 sondern dich, Priester, klage ich an. ^{[[#fn5][5]]}\\
\\

<<v5>>
5 Am helllichten Tag kommst du zu Fall /\\
 und ebenso wie du stürzt in der Nacht der Prophet. /\\
 Auch deine Mutter lasse ich umkommen. ^{[[#fn6][6]]}\\
\\

<<v6>>
6 Mein Volk kommt um, weil ihm die Erkenntnis fehlt. /\\
 Weil du die Erkenntnis verworfen hast, /\\
 darum verwerfe auch ich dich als meinen Priester. Du hast die Weisung
deines Gottes vergessen; /\\
 deshalb vergesse auch ich deine Söhne. ^{[[#fn7][7]]}\\
\\

<<v7>>
7 Je mehr sie wurden, /\\
 umso mehr sündigten sie gegen mich. /\\
 Ihre Ehre tauschen sie ein gegen Schande. ^{[[#fn8][8]]}\\
\\

<<v8>>
8 Sie nähren sich von der Sünde meines Volkes /\\
 und sind gierig nach seinen ruchlosen Opfern.\\
\\

<<v9>>
9 Darum wird es dem Priester ergehen wie dem Volk: /\\
 Ich bestrafe ihn für sein Verhalten, /\\
 seine Taten vergelte ich ihm.\\
\\

<<v10>>
10 Sie werden zwar essen, doch sie werden nicht satt, /\\
 sie treiben Unzucht, aber sie vermehren sich nicht. Ja, sie haben den
Herrn verlassen /\\
 und sich an Unzucht gehalten. ^{[[#fn9][9]]}\\
\\

<<v11>>
**** Die Sünde Israels: 4,11-19
     :PROPERTIES:
     :CUSTOM_ID: die-sünde-israels-411-19
     :END:
11 Der Opferwein raubt meinem Volk den Verstand: /\\
\\

<<v12>>
12 Es befragt sein Götzenbild aus Holz, /\\
 von seinem Stock erwartet es Auskunft. Ja, der Geist der Unzucht führt
es irre. /\\
 Es hat seinen Gott verlassen /\\
 und ist zur Dirne geworden. ^{[[#fn10][10]]}\\
\\

<<v13>>
13 Sie feiern Schlachtopfer auf den Höhen der Berge, /\\
 auf den Hügeln bringen sie Rauchopfer dar, unter Eichen, Storaxbäumen
und Terebinthen, /\\
 deren Schatten so angenehm ist. So werden eure Töchter zu Dirnen /\\
 und eure Schwiegertöchter brechen die Ehe. ^{[[#fn11][11]]}\\
\\

<<v14>>
14 Aber ich strafe nicht eure Töchter dafür, /\\
 dass sie zu Dirnen werden, und nicht eure Schwiegertöchter dafür, /\\
 dass sie die Ehe brechen; denn sie (die Priester) selbst /\\
 gehen mit den Dirnen beiseite, mit den Weihedirnen feiern sie
Schlachtopfer. /\\
 So kommt das unwissende Volk zu Fall. ^{[[#fn12][12]]}\\
\\

<<v15>>
15 Auch wenn du, Israel, zur Dirne wirst, /\\
 so soll sich doch Juda nicht schuldig machen. Kommt nicht nach Gilgal,
/\\
 zieht nicht nach Bet-Awen hinauf! /\\
 Schwört nicht: So wahr der Herr lebt! ^{[[#fn13][13]][[#fn14][14]]}\\
\\

<<v16>>
16 Ja, Israel ist störrisch wie eine störrische Kuh. /\\
 Und da sollte der Herr sie auf die Weide führen /\\
 wie die Lämmer auf der weiten Flur? ^{[[#fn15][15]]}\\
\\

<<v17>>
17 Efraim ist im Bund mit den Götzen, / ^{[[#fn16][16]]}\\
\\

<<v18>>
18 es sitzt da, ein Haufen von Zechern; sie treiben es mit den Dirnen,
/\\
 sie lieben ihre schändliche Schamlosigkeit. ^{[[#fn17][17]]}\\
\\

<<v19>>
19 Doch ein Sturm rafft sie mit seinen Flügeln dahin, /\\
 sie gehen mit Schande zugrunde wegen ihrer Altäre. ^{[[#fn18][18]]}\\
\\

^{[[#fnm1][1]]} ℘ Jes 3,13-15; Mi 6,2

^{[[#fnm2][2]]} «Gotteserkenntnis» meint die Entscheidung für Gott und
die Mitmenschen aus der Kenntnis des durch die Priester verkündeten
Gotteswillens (vgl. V. 6).

^{[[#fnm3][3]]} ℘ Jer 7,9

^{[[#fnm4][4]]} ℘ Jer 4,28; Zef 1,3

^{[[#fnm5][5]]} ℘ Jer 5,4f

^{[[#fnm6][6]]} 5bc: Text nicht ganz klar.

^{[[#fnm7][7]]} ℘ Mal 2,8

^{[[#fnm8][8]]} ℘ Jer 2,11

^{[[#fnm9][9]]} ℘ Mi 6,14

^{[[#fnm10][10]]} ℘ Jer 2,27; Hos 1,2

^{[[#fnm11][11]]} ℘ Dtn 12,2

^{[[#fnm12][12]]} ℘ Dtn 23,18f

^{[[#fnm13][13]]} ℘ 12,12; Am 4,4; 8,14

^{[[#fnm14][14]]} Bet-Awen (= Haus des Frevels): anklagend für Bet-El (=
Haus Gottes).

^{[[#fnm15][15]]} ℘ Jer 31,18

^{[[#fnm16][16]]} ℘ 6,4-6

^{[[#fnm17][17]]} ℘ Am 2,8; 4,1

^{[[#fnm18][18]]} ℘ Jer 4,11-13
