:PROPERTIES:
:ID:       801c4757-67cb-47bb-9248-6ca5fa0eeb31
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Hosea* -- [[file:Hos_1.html][1]] ...
[[file:Hos_6.html][6]] [[file:Hos_7.html][7]] *8* [[file:Hos_9.html][9]]
[[file:Hos_10.html][10]] ... [[file:Hos_14.html][14]]

--------------

* Hos 8
  :PROPERTIES:
  :CUSTOM_ID: hos-8
  :END:

<<verses>>

<<v1>>
**** Die Tage der Abrechnung: 8,1 - 9,6
     :PROPERTIES:
     :CUSTOM_ID: die-tage-der-abrechnung-81---96
     :END:
1 Stoß ins Horn! /\\
 Denn wie ein Geier kommt das Unheil /\\
 über das Haus des Herrn, weil sie meinen Bund nicht halten /\\
 und mein Gesetz missachten. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Sie schreien zwar zu mir: Mein Gott! /\\
 Wir, Israel, kennen dich doch.\\
\\

<<v3>>
3 Aber Israel hat das Gute verworfen. /\\
 Darum soll der Feind es verfolgen.\\
\\

<<v4>>
4 Sie setzen Könige ein, aber gegen meinen Willen; /\\
 sie wählen Fürsten, doch ich erkenne sie nicht an. Sie machen sich
Götzen aus ihrem Silber und Gold - /\\
 wohl damit es vernichtet wird. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Samaria, dein Kalb ist verworfen. /\\
 Mein Zorn ist entbrannt gegen sie; /\\
 wie lange noch sind sie unfähig, sich zu läutern?
^{[[#fn3][3]][[#fn4][4]]}\\
\\

<<v6>>
6 Denn wer sind Israel und das Kalb? /\\
 Ein Handwerker hat das Kalb gemacht /\\
 und es ist kein Gott. Ja, zersplittert soll es am Boden liegen, /\\
 das Kalb von Samaria. ^{[[#fn5][5]]}\\
\\

<<v7>>
7 Denn sie säen Wind /\\
 und sie ernten Sturm. Halme ohne Ähren bringen kein Mehl. /\\
 Und wenn sie es bringen, /\\
 verschlingen es Fremde. ^{[[#fn6][6]]}\\
\\

<<v8>>
8 Israel ist schon verschlungen. /\\
 Jetzt gilt es im Kreis der Völker /\\
 als wertloses Zeug.\\
\\

<<v9>>
9 Denn Israel ist nach Assur gelaufen. /\\
 Ein Wildesel bleibt für sich allein; /\\
 Efraim aber macht Liebesgeschenke. ^{[[#fn7][7]]}\\
\\

<<v10>>
10 Auch wenn sie sich unter den Völkern preisgeben, /\\
 treibe ich sie jetzt zusammen; schon bald sollen sie sich krümmen /\\
 unter der Last des Königs der Fürsten. ^{[[#fn8][8]]}\\
\\

<<v11>>
11 Efraim hat viele Altäre gebaut, /\\
 um sich zu entsündigen, /\\
 doch die Altäre sind ihm zur Sünde geworden.\\
\\

<<v12>>
12 Ich kann ihnen noch so viele Gesetze aufschreiben, /\\
 sie gelten ihnen so wenig wie die eines Fremden.\\
\\

<<v13>>
13 Schlachtopfer lieben sie, /\\
 sie opfern Fleisch und essen davon; /\\
 der Herr aber hat kein Gefallen an ihnen. Jetzt denkt er an ihre Schuld
/\\
 und straft sie für ihre Sünden: /\\
 Sie müssen zurück nach Ägypten. ^{[[#fn9][9]]}\\
\\

<<v14>>
14 Israel hat seinen Schöpfer vergessen /\\
 und große Paläste gebaut, /\\
 Juda hat viele Festungen errichtet. Doch ich sende Feuer in seine
Städte; /\\
 es soll seine Paläste verzehren. ^{[[#fn10][10]]}\\
\\

^{[[#fnm1][1]]} ℘ 5,8

^{[[#fnm2][2]]} ℘ 2,10

^{[[#fnm3][3]]} ℘ 1 Kön 12,28-30

^{[[#fnm4][4]]} 5f: Das «Kalb» ist das in den Tempeln des Nordreichs
aufgestellte Kultbild eines Jungstiers.

^{[[#fnm5][5]]} ℘ Jes 40,18-20

^{[[#fnm6][6]]} ℘ Spr 22,8

^{[[#fnm7][7]]} ℘ 5,13; 7,11

^{[[#fnm8][8]]} 10d: König der Fürsten: Titel für den assyrischen
Großkönig.

^{[[#fnm9][9]]} ℘ 6,6; Am 5,22

^{[[#fnm10][10]]} ℘ Dtn 32,15.18; Am 2,5
