:PROPERTIES:
:ID:       c8b9fdf0-9c34-4400-a45b-f77e74c9ea1b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Hosea* -- [[file:Hos_1.html][1]]
[[file:Hos_2.html][2]] *3* [[file:Hos_4.html][4]] [[file:Hos_5.html][5]]
... [[file:Hos_14.html][14]]

--------------

* Hos 3
  :PROPERTIES:
  :CUSTOM_ID: hos-3
  :END:

<<verses>>

<<v1>>
**** Die Wiederannahme der treulosen Frau: 3,1-5
     :PROPERTIES:
     :CUSTOM_ID: die-wiederannahme-der-treulosen-frau-31-5
     :END:
1 Der Herr sagte zu mir: /\\
 Geh noch einmal hin und liebe die Frau, /\\
 die einen Liebhaber hat und Ehebruch treibt. (Liebe sie) so, /\\
 wie der Herr die Söhne Israels liebt, obwohl sie sich anderen Göttern
zuwenden /\\
 und Opferkuchen aus Rosinen lieben.\\
\\

<<v2>>
2 Da kaufte ich sie für fünfzehn Silberstücke /\\
 und anderthalb Hómer Gerste. ^{[[#fn1][1]]}\\
\\

<<v3>>
3 Ich sagte zu ihr: /\\
 Du bleibst jetzt viele Tage bei mir, ohne als Dirne einem Mann zu
gehören. /\\
 Und so mache auch ich es mit dir.\\
\\

<<v4>>
4 Denn viele Tage bleiben Israels Söhne /\\
 ohne König und Fürst, ohne Opfer und Steinmal, /\\
 ohne Efod und ohne Terafim. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Danach werden die Söhne Israels umkehren /\\
 und den Herrn, ihren Gott, suchen /\\
 und ihren König David. Zitternd werden sie zum Herrn kommen /\\
 und seine Güte suchen am Ende der Tage. ^{[[#fn3][3]]}\\
\\

^{[[#fnm1][1]]} anderthalb Hómer, wörtlich ein Hómer und ein Letech;
Letech ist ein Hohlmaß, das ein halbes Hómer ausmacht.

^{[[#fnm2][2]]} Efod und Terafim sind Kultgegenstände, deren Gestalt und
Bedeutung wir nicht genau kennen.

^{[[#fnm3][3]]} ℘ Jer 30,9; Ez 34,24
