#+TITLE: Ijob 14 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-29 Mi 22:13]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ijob 14.html

<<verses>>

<<v1>>
* Ijobs Hoffnungslosigkeit: 14,1-22

1 Der Mensch, vom Weib geboren, /\\
 knapp an Tagen, unruhvoll, [fn:1]\\
\\

<<v2>>
2 er geht wie die Blume auf und welkt, /\\
 flieht wie ein Schatten und bleibt nicht bestehen. [fn:2]\\
\\

<<v3>>
3 Doch über ihm hältst du dein Auge offen /\\
 und ihn bringst du ins Gericht mit dir. [fn:3]\\
\\

<<v4>>
4 Kann denn ein Reiner von Unreinem kommen? /\\
 Nicht ein Einziger. [fn:4]\\
\\

<<v5>>
5 Wenn seine Tage fest bestimmt sind /\\
 und die Zahl seiner Monde bei dir, /\\
 wenn du gesetzt hast seine Grenzen, /\\
 sodass er sie nicht überschreitet, [fn:5]\\
\\

<<v6>>
6 schau weg von ihm! Lass ab, /\\
 damit er seines Tags sich freue wie ein Tagelöhner. [fn:6]\\
\\

<<v7>>
7 Denn für den Baum besteht noch Hoffnung, /\\
 ist er gefällt, so treibt er wieder, /\\
 sein Sprössling bleibt nicht aus. [fn:7]\\
\\

<<v8>>
8 Wenn in der Erde seine Wurzel altert /\\
 und sein Stumpf im Boden stirbt,\\
\\

<<v9>>
9 vom Dunst des Wassers sprosst er wieder /\\
 und wie ein Setzling treibt er Zweige.\\
\\

<<v10>>
10 Doch stirbt ein Mann, so bleibt er kraftlos, /\\
 verscheidet ein Mensch, wo ist er dann? [fn:8]\\
\\

<<v11>>
11 Die Wasser schwinden aus dem Meer, /\\
 der Strom vertrocknet und versiegt. [fn:9]\\
\\

<<v12>>
12 So legt der Mensch sich hin, steht nie mehr auf; /\\
 die Himmel werden vergehen, eh er erwacht, /\\
 eh er aus seinem Schlaf geweckt wird.\\
\\

<<v13>>
13 Dass du mich in der Unterwelt verstecktest, /\\
 mich bergen wolltest, bis dein Zorn sich wendet, /\\
 ein Ziel mir setztest und dann an mich dächtest! [fn:10]\\
\\

<<v14>>
14 Wenn einer stirbt, lebt er dann wieder auf? /\\
 Alle Tage meines Kriegsdienstes harrte ich, /\\
 bis einer käme, um mich abzulösen. [fn:11]\\
\\

<<v15>>
15 Du riefest und ich gäbe Antwort, /\\
 du sehntest dich nach deiner Hände Werk.\\
\\

<<v16>>
16 Dann würdest du meine Schritte zählen, /\\
 auf meinen Fehltritt nicht mehr achten. [fn:12]\\
\\

<<v17>>
17 Versiegelt im Beutel wäre mein Vergehen, /\\
 du würdest meinen Frevel übertünchen.\\
\\

<<v18>>
18 Jedoch der Berg, der fällt, zergeht, /\\
 von seiner Stätte rückt der Fels.\\
\\

<<v19>>
19 Das Wasser zerreibt Steine, /\\
 Platzregen spült das Erdreich fort; /\\
 so machst du das Hoffen des Menschen zunichte.\\
\\

<<v20>>
20 Du bezwingst ihn für immer, so geht er dahin, /\\
 du entstellst sein Gesicht und schickst ihn fort. [fn:13]\\
\\

<<v21>>
21 Sind seine Kinder in Ehren, er weiß es nicht; /\\
 sind sie verachtet, er merkt es nicht.\\
\\

<<v22>>
22 Sein Leib fühlt nur die eigenen Schmerzen, /\\
 seine Seele trauert nur um sich selbst.\\
\\

* Footnotes

[fn:1] [[file:Ijob_10.org::v10][10,20]]; [[file:Ps_39.org::v5][Ps 39,5]]

[fn:2] [[file:Ps_90.org::v5][Ps 90,5f]]; [[file:Koh_6.org::v12][Koh 6,12]]

[fn:3] und ihn: Text korr. nach G, S, Vg; H: und mich.

[fn:4] [[file:Ijob_4.org::v17][4,17]]; [[file:Ijob_15.org::v14][15,14]]; [[file:Ijob_25.org::v4][25,4]]; [[file:Ps_51.org::v7][Ps 51,7]]

[fn:5] [[file:Ps_39.org::v6][Ps 39,6]]; [[file:Ps_139.org::v16][139,16]]

[fn:6] [[file:Ps_39.org::v14][Ps 39,14]]

[fn:7] [[file:Ijob_19.org::v10][19,10]]; [[file:Jes_6.org::v13][Jes 6,13]]

[fn:8] [[file:Koh_3.org::v21][Koh 3,21]]

[fn:9] [[file:Jes_19.org::v5][Jes 19,5]]

[fn:10] [[file:Jes_26.org::v20][Jes 26,20]]

[fn:11] [[file:Ijob_7.org::v1][7,1]]

[fn:12] [[file:Ijob_10.org::v6][10,6]]

[fn:13] [[file:Ijob_21.org::v21][21,21]]
