#+TITLE: Ijob 34 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-02 Sa 22:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ijob 34.html

<<verses>>

<<v1>>
* Die zweite Rede Elihus: 34,1-37

* Die Verwegenheit Ijobs: 34,1-9

1 Dann ergriff Elihu das Wort und sprach:\\
\\

<<v2>>
2 Ihr Weisen, hört meine Worte, /\\
 ihr Kundigen, leiht mir Gehör!\\
\\

<<v3>>
3 Denn das Ohr prüft die Worte /\\
 und der Gaumen schmeckt die Speise. [fn:1]\\
\\

<<v4>>
4 Lasst das Recht uns untersuchen, /\\
 erkennen unter uns, was gut ist.\\
\\

<<v5>>
5 Denn Ijob sagt: Ich bin im Recht, /\\
 doch Gott hat mir mein Recht entzogen.\\
\\

<<v6>>
6 Meinem Recht zuwider soll ich lügen? /\\
 Unheilbar traf mich ohne Schuld der Pfeil. [fn:2]\\
\\

<<v7>>
7 Wo ist ein Mann wie Ijob, /\\
 der Lästerung wie Wasser trinkt, [fn:3]\\
\\

<<v8>>
8 der hingeht, um sich den Übeltätern zuzugesellen, /\\
 und mit den Frevlern Umgang pflegt?\\
\\

<<v9>>
9 Er sagte ja: Es nützt dem Menschen nichts, /\\
 dass er in Freundschaft lebt mit Gott.\\
\\

<<v10>>
* Das gerechte Handeln des Allmächtigen: 34,10-15

10 Darum hört mir zu, ihr Männer mit Verstand! /\\
 Fern ist es Gott, Unrecht zu tun, /\\
 und dem Allmächtigen, Frevel zu üben.\\
\\

<<v11>>
11 Nein, was der Mensch tut, das vergilt er ihm, /\\
 nach eines jeden Verhalten lässt er es ihn treffen. [fn:4]\\
\\

<<v12>>
12 Nein, wahrhaftig, nie tut Gott unrecht /\\
 und der Allmächtige beugt nicht das Recht. [fn:5]\\
\\

<<v13>>
13 Wer hat ihm seine Erde anvertraut /\\
 und wer den ganzen Erdkreis hingestellt?\\
\\

<<v14>>
14 Wenn er auf ihn den Sinn nur richtet, /\\
 seinen Geist und Atem zu sich holt, [fn:6]\\
\\

<<v15>>
15 muss alles Fleisch zusammen sterben, /\\
 der Mensch zum Staube wiederkehren.\\
\\

<<v16>>
* Gottes Macht: 34,16-24

16 Hast du Verstand, so höre dies, /\\
 lausche dem Laut meiner Worte!\\
\\

<<v17>>
17 Kann, wer das Recht hasst, Herrschaft führen? /\\
 Und willst du den Gerechten, /\\
 den Erhabenen verklagen, [fn:7]\\
\\

<<v18>>
18 ihn, der zum König sagt: Du Nichtsnutz!, /\\
 zu Edelmännern: Bösewicht!, [fn:8]\\
\\

<<v19>>
19 der nicht auf Fürsten Rücksicht nimmt, /\\
 vornehm nicht vor arm begünstigt; /\\
 denn alle sind sie seiner Hände Werk. [fn:9]\\
\\

<<v20>>
20 Sie sterben plötzlich, mitten in der Nacht; /\\
 das Volk gerät in Aufruhr und sie müssen fort. /\\
 Starke müssen weichen, /\\
 ohne dass eine Hand sich rührt.\\
\\

<<v21>>
21 Denn seine Augen schauen auf des Menschen Wege, /\\
 alle seine Schritte sieht er wohl. [fn:10]\\
\\

<<v22>>
22 Kein Dunkel gibt es, keine Finsternis, /\\
 wo sich die Übeltäter bergen könnten. [fn:11]\\
\\

<<v23>>
23 Denn dem Menschen setzt er keine Frist, /\\
 zu Gott ins Gericht zu gehen. [fn:12]\\
\\

<<v24>>
24 Gewaltige knickt er ohne Verhör /\\
 und stellt andere an ihren Platz. [fn:13]\\
\\

<<v25>>
* Gottes Recht: 34,25-37

25 Wahrhaftig, Gott kennt ja ihre Taten, /\\
 er stürzt sie bei Nacht und sie sind zermalmt.\\
\\

<<v26>>
26 Wie Frevler schlägt er sie /\\
 an einem Ort, wo man es sieht,\\
\\

<<v27>>
27 deshalb, weil sie von ihm wichen, /\\
 nicht achteten auf alle seine Wege.\\
\\

<<v28>>
28 So lässt er der Armen Geschrei zu sich kommen, /\\
 er hört das Geschrei der Gebeugten.\\
\\

<<v29>>
29 Hält er sich still, wer spricht ihn schuldig? /\\
 Verbirgt er sein Gesicht, wer nimmt ihn wahr? /\\
 Über Volk und Menschen aber wacht er, [fn:14] [fn:15]\\
\\

<<v30>>
30 damit nicht ruchlose Menschen herrschen, /\\
 die dem Volk zum Fallstrick werden.\\
\\

<<v31>>
31 Denn nicht ist's an Gott, zu sagen: /\\
 Geirrt habe ich, ich mach's nicht wieder falsch. [fn:16]\\
\\

<<v32>>
32 Was ich nicht sehe, lehre du mich! /\\
 Tat ich Unrecht, ich will es nicht mehr tun.\\
\\

<<v33>>
33 Soll er nach deinem Sinn vergelten, /\\
 weil du verwirfst? So musst ja du entscheiden, nicht ich, /\\
 und was du weißt, das sage an!\\
\\

<<v34>>
34 Verständige Männer werden zu mir sagen, /\\
 ein jeder Weise, der mich hört:\\
\\

<<v35>>
35 Bar des Wissens redet Ijob /\\
 und unbedacht sind seine Worte.\\
\\

<<v36>>
36 Wohlan, weiter werde Ijob geprüft, /\\
 weil er nach der Frevler Art erwidert.\\
\\

<<v37>>
37 Denn Frevel fügt er noch zu seiner Sünde, /\\
 in unserer Mitte höhnt er laut, /\\
 mehrt seine Worte gegen Gott.\\
\\

* Footnotes

[fn:1] [[file:Ijob_12.org::v11][12,11]]

[fn:2] [[file:Ijob_9.org::v15][9,15]]

[fn:3] [[file:Ijob_15.org::v16][15,16]]

[fn:4] [[file:Ps_62.org::v13][Ps 62,13]]; [[file:Spr_24.org::v12][Spr 24,12]]; [[file:Sir_16.org::v14][Sir 16,14]]

[fn:5] [[file:Gen_18.org::v25][Gen 18,25]]

[fn:6] (14-15) [[file:Ps_104.org::v29][Ps 104,29f]]; [[file:Gen_2.org::v7][Gen 2,7]]; [[file:Koh_3.org::v20][Koh 3,20]]; [[file:Gen_3.org::v19][Gen 3,19]]

[fn:7] [[file:~/Documents/notes/Bibel/nt/Röm_3.org::v5][Röm 3,5]]

[fn:8] [[file:Jes_40.org::v23][Jes 40,23f]]

[fn:9] [[file:Sir_35.org::v16][Sir 35,16]]

[fn:10] [[file:Jer_32.org::v19][Jer 32,19]]; [[file:~/Documents/notes/Bibel/nt/Hebr_4.org::v13][Hebr 4,13]]

[fn:11] [[file:Ps_139.org::v12][Ps 139,12]]

[fn:12] Frist: Text korr.

[fn:13] [[file:Dan_2.org::v21][Dan 2,21]]

[fn:14] [[file:Weish_12.org::v2][Weish 12,2]]

[fn:15] wacht er: Text korr.

[fn:16] Text korr.
