#+TITLE: Ijob 23 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-02 Sa 16:34]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ijob 23.html

<<verses>>

<<v1>>
* Ijobs Gegenrede: 23,1 - 24,25

* Der Ruf nach Gott, dem Richter: 23,1-17

1 Da antwortete Ijob und sprach:\\
\\

<<v2>>
2 Auch heute ist meine Klage Widerspruch; /\\
 schwer lastet seine Hand auf meinem Seufzen. [fn:1]\\
\\

<<v3>>
3 Wüßte ich doch, wie ich ihn finden könnte, /\\
 gelangen könnte zu seiner Stätte.\\
\\

<<v4>>
4 Ich wollte vor ihm das Recht ausbreiten, /\\
 meinen Mund mit Beweisen füllen. [fn:2]\\
\\

<<v5>>
5 Wissen möchte ich die Worte, die er mir entgegnet, /\\
 erfahren, was er zu mir sagt.\\
\\

<<v6>>
6 Würde er in der Fülle der Macht mit mir streiten? /\\
 Nein, gerade er wird auf mich achten.\\
\\

<<v7>>
7 Dort würde ein Redlicher mit ihm rechten /\\
 und ich käme für immer frei von meinem Richter.\\
\\

<<v8>>
8 Geh ich nach Osten, so ist er nicht da, /\\
 nach Westen, so merke ich ihn nicht, [fn:3]\\
\\

<<v9>>
9 nach Norden, sein Tun erblicke ich nicht; /\\
 bieg ich nach Süden, sehe ich ihn nicht. [fn:4]\\
\\

<<v10>>
10 Doch er kennt den Weg, den ich gehe; /\\
 prüfte er mich, ich ginge wie Gold hervor. [fn:5]\\
\\

<<v11>>
11 Mein Fuß hielt fest an seiner Spur, /\\
 seinen Weg hielt ich ein und bog nicht ab. [fn:6]\\
\\

<<v12>>
12 Das Gebot seiner Lippen gab ich nicht auf; /\\
 seines Mundes Worte barg ich im Herzen. [fn:7]\\
\\

<<v13>>
13 Doch er bleibt sich gleich. Wer stimmt ihn um? /\\
 Wonach ihn gelüstet, das führt er aus. [fn:8]\\
\\

<<v14>>
14 Ja, er vollendet, was er mir bestimmt hat; /\\
 und Ähnliches hat er noch viel im Sinn.\\
\\

<<v15>>
15 Darum erschrecke ich vor seinem Angesicht; /\\
 denk ich daran, gerate ich in Angst vor ihm. [fn:9]\\
\\

<<v16>>
16 Gott macht mein Herz verzagt, /\\
 der Allmächtige versetzt mich in Schrecken.\\
\\

<<v17>>
17 Denn bin ich nicht von Finsternis umschlossen, /\\
 bedeckt nicht Dunkel mein Angesicht?\\
\\

* Footnotes

[fn:1] seine Hand: Text korr. nach G und S; H: meine Hand.

[fn:2] [[file:Ijob_9.org::v14][9,14]]

[fn:3] [[file:Ijob_9.org::v11][9,11]]; [[file:Ps_139.org::v7][Ps 139,7]]-[[file:Ps_139.org::v10][10]]

[fn:4] bieg ich: Text korr.; H: biegt er.

[fn:5] [[file:Ps_17.org::v3][Ps 17,3]]; [[file:Ps_139.org::v1][139,1]]-[[file:Ps_139.org::v6][6]]; [[file:Weish_3.org::v6][Weish 3,6]]

[fn:6] [[file:Ps_17.org::v5][Ps 17,5]]

[fn:7] im Herzen: Text korr.

[fn:8] [[file:Jes_55.org::v10][Jes 55,10f]]; [[file:Ps_115.org::v3][Ps 115,3]]

[fn:9] [[file:Ps_119.org::v120][Ps 119,120]]
