#+TITLE: Ijob 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-30 Do 00:05]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ijob 21.html

<<verses>>

<<v1>>
* Ijobs Gegenrede: 21,1-34

* Die Bitte um Geduld: 21,1-6

1 Da antwortete Ijob und sprach:\\
\\

<<v2>>
2 Hört, hört doch auf mein Wort, /\\
 das wäre mir schon Trost von euch.\\
\\

<<v3>>
3 Ertragt mich, sodass ich reden kann. /\\
 Habe ich geredet, dann könnt ihr spotten. [fn:1]\\
\\

<<v4>>
4 Richt ich an Menschen meine Klage, /\\
 hab ich nicht Grund zur Ungeduld? [fn:2]\\
\\

<<v5>>
5 Wendet euch mir zu und erstarrt /\\
 und legt die Hand auf den Mund! [fn:3]\\
\\

<<v6>>
6 Denk ich daran, bin ich erschreckt /\\
 und Schauder packt meinen Leib.\\
\\

<<v7>>
* Das Glück des Frevlers: 21,7-21

7 Warum bleiben Frevler am Leben, /\\
 werden alt und stark an Kraft? [fn:4]\\
\\

<<v8>>
8 Ihre Nachkommen stehen fest vor ihnen, /\\
 ihre Sprösslinge vor ihren Augen.\\
\\

<<v9>>
9 Ihre Häuser sind in Frieden, ohne Schreck, /\\
 die Rute Gottes trifft sie nicht.\\
\\

<<v10>>
10 Ihr Stier bespringt und fehlt nicht, /\\
 die Kühe kalben und verwerfen nicht.\\
\\

<<v11>>
11 Wie Schafe treiben sie ihre Kinder aus, /\\
 ihre Kleinen tanzen und springen.\\
\\

<<v12>>
12 Sie singen zu Pauke und Harfe, /\\
 erfreuen sich am Klang der Flöte, [fn:5]\\
\\

<<v13>>
13 verbrauchen ihre Tage im Glück /\\
 und fahren voll Ruhe ins Totenreich. [fn:6]\\
\\

<<v14>>
14 Und doch sagten sie zu Gott: Weiche von uns! /\\
 Deine Wege wollen wir nicht kennen. [fn:7]\\
\\

<<v15>>
15 Was ist der Allmächtige, dass wir ihm dienen, /\\
 was nützt es uns, wenn wir ihn angehen? [fn:8]\\
\\

<<v16>>
16 Doch in ihrer Hand liegt nicht das Glück; /\\
 der Frevler Denkart ist mir fern.\\
\\

<<v17>>
17 Wie oft erlischt der Frevler Lampe, /\\
 kommt Unheil über sie, /\\
 teilt er Verderben zu in seinem Zorn? [fn:9]\\
\\

<<v18>>
18 Wie oft werden sie wie Stroh vor dem Wind, /\\
 wie Spreu, die der Sturm entführt? [fn:10]\\
\\

<<v19>>
19 Nicht dessen Kindern spare Gott sein Unheil auf, /\\
 ihm selbst vergelte er, sodass er es spürt. [fn:11]\\
\\

<<v20>>
20 Mit eigenen Augen soll er sein Unglück schauen, /\\
 vom Grimm des Allmächtigen soll er trinken. [fn:12] [fn:13]\\
\\

<<v21>>
21 Denn was kümmert ihn sein Haus, wenn er dahin ist, /\\
 wenn abgeschnitten seiner Monde Zahl? [fn:14]\\
\\

<<v22>>
* Der trügerische Trost: 21,22-34

22 Darf man Gott Erkenntnis lehren, /\\
 ihn, der die Erhabenen richtet? [fn:15]\\
\\

<<v23>>
23 Der eine stirbt in vollem Glück, /\\
 ist ganz in Frieden, sorgenfrei.\\
\\

<<v24>>
24 Seine Schenkel sind voll von Fett, /\\
 getränkt mit Mark sind seine Knochen. [fn:16]\\
\\

<<v25>>
25 Der andere stirbt mit bitterer Seele /\\
 und hat kein Glück genossen.\\
\\

<<v26>>
26 Zusammen liegen sie im Staub /\\
 und Gewürm deckt beide zu. [fn:17]\\
\\

<<v27>>
27 Ja, euer Denken kenn ich wohl, /\\
 die Ränke, die ihr sinnt gegen mich.\\
\\

<<v28>>
28 Ihr sagt: Wo ist das Haus des Edlen /\\
 und wo das Zelt, in dem Frevler wohnen?\\
\\

<<v29>>
29 Habt ihr nie die fahrenden Leute befragt /\\
 und ihre Zeichen genau beachtet?\\
\\

<<v30>>
30 Dass am Unglückstag der Böse verschont wird, /\\
 weggebracht am Tag des Zorns. [fn:18]\\
\\

<<v31>>
31 Wer hält ihm seinen Lebenswandel vor, /\\
 was er getan hat, wer vergilt es ihm?\\
\\

<<v32>>
32 Er aber wird zur Gruft geleitet, /\\
 bei seinem Grab hält man die Wacht.\\
\\

<<v33>>
33 Ein Labsal sind für ihn die Schollen des Schachts, /\\
 hinter ihm her zieht alle Welt, /\\
 vor ihm die Menge ohne Zahl.\\
\\

<<v34>>
34 Wie wollt ihr mich mit Nichtigem trösten? /\\
 Eure Antworten bleiben Betrug.\\
\\

* Footnotes

[fn:1] könnt ihr: Text korr.; H: kannst du.

[fn:2] [[file:Ijob_6.org::v26][6,26]]

[fn:3] [[file:Ijob_29.org::v9][29,9]]; [[file:Ijob_40.org::v4][40,4]]

[fn:4] [[file:Ps_73.org::v3][Ps 73,3]]-[[file:Ps_73.org::v12][12]]; [[file:Jer_12.org::v1][Jer 12,1f]]; [[file:Mal_3.org::v15][Mal 3,15]].[[file:Mal_3.org::v18][18]]

[fn:5] [[file:Jes_5.org::v12][Jes 5,12]]; [[file:Am_6.org::v5][Am 6,5]]

[fn:6] [[file:Ps_73.org::v3][Ps 73,3]]

[fn:7] [[file:Ijob_22.org::v17][22,17]]; [[file:Ps_95.org::v10][Ps 95,10]]

[fn:8] [[file:Mal_3.org::v14][Mal 3,14f]]

[fn:9] [[file:Ijob_18.org::v5][18,5]]

[fn:10] [[file:Ps_1.org::v4][Ps 1,4]]

[fn:11] Nicht: Text korr.

[fn:12] [[file:Ps_75.org::v9][Ps 75,9]]

[fn:13] Unglück: Übersetzung unsicher.

[fn:14] [[file:Ijob_14.org::v21][14,21f]]; [[file:Koh_9.org::v5][Koh 9,5f]]

[fn:15] [[file:Jes_40.org::v13][Jes 40,13]]

[fn:16] Schenkel: Übersetzung unsicher.

[fn:17] [[file:Koh_9.org::v2][Koh 9,2f]]

[fn:18] [[file:~/RoamNotes/notes/Bibel/nt/Röm_2.org::v3][Röm 2,3]]-[[file:Koh_9.org::v6][6]]
