#+TITLE: Ijob 42 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-03 So 00:17]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ijob 42.html

<<verses>>

<<v1>>
* Ijobs Umkehr und Unterwerfung: 42,1-6

1 Da antwortete Ijob dem Herrn und sprach:\\
\\

<<v2>>
2 Ich hab erkannt, dass du alles vermagst; /\\
 kein Vorhaben ist dir verwehrt.\\
\\

<<v3>>
3 Wer ist es, der ohne Einsicht den Rat verdunkelt? /\\
 So habe ich denn im Unverstand geredet über Dinge, /\\
 die zu wunderbar für mich und unbegreiflich sind. [fn:1]\\
\\

<<v4>>
4 Hör doch, ich will nun reden, /\\
 ich will dich fragen, du belehre mich!\\
\\

<<v5>>
5 Vom Hörensagen nur hatte ich von dir vernommen; /\\
 jetzt aber hat mein Auge dich geschaut.\\
\\

<<v6>>
6 Darum widerrufe ich und atme auf, /\\
 in Staub und Asche. [fn:2]\\
\\

<<v7>>
* Die Rahmenerzählung: 42,7-17

* Ijobs Rechtfertigung: 42,7-9

7 Als der Herr diese Worte zu Ijob gesprochen hatte, sagte der Herr zu
Elifas von Teman: Mein Zorn ist entbrannt gegen dich und deine beiden
Gefährten; denn ihr habt nicht recht von mir geredet wie mein Knecht
Ijob.

<<v8>>
8 So nehmt nun sieben Jungstiere und sieben Widder, geht hin zu meinem
Knecht Ijob und bringt ein Brandopfer für euch dar! Mein Knecht Ijob
aber soll für euch Fürbitte einlegen; nur auf ihn nehme ich Rücksicht,
dass ich euch nichts Schlimmeres antue. Denn ihr habt nicht recht von
mir geredet wie mein Knecht Ijob.

<<v9>>
9 Da gingen Elifas von Teman, Bildad von Schuach und Zofar von Naama hin
und taten, was der Herr ihnen gesagt hatte. Und der Herr nahm Rücksicht
auf Ijob.\\
\\

<<v10>>
* Ijobs neues Glück: 42,10-17

10 Der Herr wendete das Geschick Ijobs, als er für seinen Nächsten
Fürbitte einlegte; und der Herr mehrte den Besitz Ijobs auf das
Doppelte. [fn:3]

<<v11>>
11 Da kamen zu ihm alle seine Brüder, alle seine Schwestern und alle
seine früheren Bekannten und speisten mit ihm in seinem Haus. Sie
bezeigten ihm ihr Mitleid und trösteten ihn wegen all des Unglücks, das
der Herr über ihn gebracht hatte. Ein jeder schenkte ihm eine Kesita und
einen goldenen Ring. [fn:4]

<<v12>>
12 Der Herr aber segnete die spätere Lebenszeit Ijobs mehr als seine
frühere. Er besaß vierzehntausend Schafe, sechstausend Kamele, tausend
Joch Rinder und tausend Esel.

<<v13>>
13 Auch bekam er sieben Söhne und drei Töchter.

<<v14>>
14 Die erste nannte er Jemima, die zweite Kezia und die dritte
Keren-Happuch. [fn:5]

<<v15>>
15 Man fand im ganzen Land keine schöneren Frauen als die Töchter Ijobs;
ihr Vater gab ihnen Erbbesitz unter ihren Brüdern. [fn:6]

<<v16>>
16 Ijob lebte danach noch hundertvierzig Jahre; er sah seine Kinder und
Kindeskinder, vier Geschlechter. [fn:7]

<<v17>>
17 Dann starb Ijob, hochbetagt und satt an Lebenstagen. [fn:8]\\
\\

* Footnotes

[fn:1] [[file:Ijob_38.org::v2][38,2]]

[fn:2] widerrufe ich, wörtlich: verwerfe ich. - und atme auf:
übersetzt nach der dem betreffenden hebräischen Wort entsprechenden
arabischen Wurzel.

[fn:3] [[file:~/RoamNotes/notes/Bibel/nt/Jak_5.org::v11][Jak 5,11]]

[fn:4] Kesita: ursprünglich altes Metallgewicht unbekannter
Schwere, später Zahlungsmittel. - Ring: ein Nasenreif oder ein Ohrring.

[fn:5] Die Namen der drei Töchter bedeuten: Täubchen, Zimtblüte
und Schminkhörnchen.

[fn:6] [[file:Ps_144.org::v12][Ps 144,12]]

[fn:7] [[file:Ps_128.org::v6][Ps 128,6]]

[fn:8] [[file:Gen_25.org::v8][Gen 25,8]]
