#+TITLE: Ijob 20 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-29 Mi 23:04]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ijob 20.html

<<verses>>

<<v1>>
* Die zweite Rede Zofars: 20,1-29

* Ijobs unbegründeter Vorwurf: 20,1-3

1 Da antwortete Zofar von Naama und sprach:\\
\\

<<v2>>
2 Darum drängt mich meine Erregung zur Antwort /\\
 und deswegen stürmt es in mir.\\
\\

<<v3>>
3 Schmähende Rüge muss ich hören, /\\
 doch der Geist meiner Einsicht lässt mich entgegnen.\\
\\

<<v4>>
* Das Schicksal des Frevlers: 20,4-29

4 Weißt du das nicht von Urzeit her, /\\
 seit Gott Menschen auf die Erde gesetzt hat:\\
\\

<<v5>>
5 dass kurz nur währt der Frevler Jubel, /\\
 einen Augenblick nur des Ruchlosen Freude?\\
\\

<<v6>>
6 Steigt auch sein Übermut zum Himmel /\\
 und rührt sein Kopf bis ans Gewölk, [fn:1]\\
\\

<<v7>>
7 wie sein Kot vergeht er doch für immer; /\\
 die ihn gesehen haben, werden fragen: Wo ist er?\\
\\

<<v8>>
8 Wie ein Traum verfliegt er /\\
 und ist nicht mehr zu finden, /\\
 wird weggescheucht wie ein Gesicht der Nacht. [fn:2]\\
\\

<<v9>>
9 Das Auge, das ihn sah, erblickt ihn nicht wieder, /\\
 seine Stätte schaut ihn nie mehr.\\
\\

<<v10>>
10 Seine Söhne müssen bei Armen betteln, /\\
 ihre Hände geben seine Habe zurück.\\
\\

<<v11>>
11 Strotzen von Jugendkraft auch seine Glieder, /\\
 sie betten sich doch mit ihm in den Staub.\\
\\

<<v12>>
12 Schmeckt süß das Böse in seinem Mund, /\\
 birgt er es unter seiner Zunge, [fn:3]\\
\\

<<v13>>
13 spart er es auf und will nicht von ihm lassen, /\\
 hält er es auch tief in seinem Gaumen fest,\\
\\

<<v14>>
14 in seinem Innern verwandelt sich die Speise, /\\
 sie wird in seinem Leib ihm zu Natterngift.\\
\\

<<v15>>
15 Das Gut, das er verschlungen hat, speit er aus; /\\
 aus seinem Leib treibt Gott es heraus.\\
\\

<<v16>>
16 Das Gift von Nattern saugt er ein, /\\
 es tötet ihn der Viper Zunge. [fn:4]\\
\\

<<v17>>
17 Nicht darf er Bäche von Öl schauen, /\\
 nicht Flüsse, die von Milch und Honig fließen. [fn:5]\\
\\

<<v18>>
18 Zurückgeben muss er seinen Gewinn, /\\
 genießen darf er ihn nicht, /\\
 darf sich nicht freuen am ertauschten Gut. [fn:6]\\
\\

<<v19>>
19 Denn Arme schlug er nieder, ließ sie liegen, /\\
 raubte das Haus, das er nicht gebaut. [fn:7]\\
\\

<<v20>>
20 Denn kein Genug kennt er in seinem Bauch, /\\
 drum entkommt er nicht mit seinen Schätzen.\\
\\

<<v21>>
21 Nichts entgeht seinem Fraß, /\\
 darum hält sein Glück auch nicht stand.\\
\\

<<v22>>
22 Trotz vollen Überflusses kommt er in Not, /\\
 die ganze Wucht des Elends fällt ihn an. [fn:8]\\
\\

<<v23>>
23 Und so geschieht es: Um des Frevlers Bauch zu füllen, /\\
 lässt Gott auf ihn die Gluten seines Zornes los, /\\
 lässt auf ihn regnen seine Schläge.\\
\\

<<v24>>
24 Flieht er vor dem Eisenpanzer, /\\
 durchbohrt ihn der Bogen aus Bronze.\\
\\

<<v25>>
25 In den Rücken fährt ihm Gottes Geschoss, /\\
 ein Blitz in seine Galle. /\\
 Schrecken gehen über ihn hin.\\
\\

<<v26>>
26 Nur finsteres Unheil ist für ihn aufbewahrt, /\\
 Feuer, von niemand entfacht, verzehrt ihn, /\\
 frisst noch den letzten Mann in seinem Zelt. [fn:9]\\
\\

<<v27>>
27 Der Himmel enthüllt seine Schuld, /\\
 die Erde bäumt sich gegen ihn auf.\\
\\

<<v28>>
28 Die Flut wälzt sein Haus hinweg, /\\
 Wasserströme am Tag seines Zorns. [fn:10]\\
\\

<<v29>>
29 Das ist des Frevlers Anteil von Gott, /\\
 das Erbe, das Gott ihm zuspricht. [fn:11]\\
\\

* Footnotes

[fn:1] [[file:Ps_37.org::v35][Ps 37,35]]

[fn:2] [[file:Ps_73.org::v20][Ps 73,20]]

[fn:3] [[file:Spr_20.org::v17][Spr 20,17]]; [[file:Sir_40.org::v30][Sir 40,30]]

[fn:4] [[file:Dtn_32.org::v33][Dtn 32,33]]

[fn:5] von Öl: Text korr.

[fn:6] [[file:Ps_109.org::v11][Ps 109,11]]

[fn:7] [[file:Ps_109.org::v16][Ps 109,16]]

[fn:8] [[file:Ijob_21.org::v17][21,17]]

[fn:9] [[file:Ijob_15.org::v23][15,23]].[[file:Ijob_15.org::v34][34]]

[fn:10] seines Zorns: des Zorns Gottes.

[fn:11] [[file:Ijob_27.org::v13][27,13]]
