#+TITLE: Ijob 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-28 Di 21:48]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ijob 1.html

* Ijob 1

* Die Bücher der Lehrweisheit und die Psalmen

Das Buch Ijob, eines der Hauptwerke der Weltliteratur, ist nach seiner
zentralen Gestalt benannt, da uns sein Verfasser unbekannt ist. Die uns
heute vorliegende Form hat das Buch in nachexilischer Zeit gefunden. Man
hatte sich aber mit der Thematik des Buches schon früher in Israel
beschäftigt (vgl. Ez 14,14.20). Um 200 v. Chr. liegt es jedenfalls vor
(vgl. Sir 49,9).\\
\\
Die in Prosa gehaltene Rahmenerzählung (1,1 - 2,10 und 42,7-17) geht auf
eine alte Volksüberlieferung von einem vorbildlichen, frommen und
gerechten Mann zurück. In diese Rahmenerzählung ist der Hauptteil in
dichterischer Form eingefügt (3,1 - 42,6): Nach einer einleitenden Klage
Ijobs (3,1-26) folgen drei Redegänge aus je einer Rede der drei Freunde
und einer Entgegnung Ijobs (4,1 - 27,23) - der letzte Redegang ist
allerdings nur bruchstückhaft erhalten -, ein Lied über die Weisheit
(Kap. 28), eine Schlussrede Ijobs (29,1 - 31,40), die das Eingreifen
Gottes herbeiführen will, vier Reden des sonst nicht bekannten
Weisheitslehrers Elihu (32,1 - 37,24) und schließlich zwei Gottesreden
mit je einer Antwort Ijobs (38,1 - 42,6).\\
\\
Als Erweiterungen des ursprünglichen Textes werden vielfach das Lied
über die Weisheit (Kap. 28) und die Reden Elihus angesehen. Der
Verfasser erweist sich als mit dem Bildungsgut der Weisheitslehre
vertraut, er verarbeitet naturkundliches Wissen seiner Zeit und kennt
alte Mythen. Auch das biblische Überlieferungsgut hat er stets lebendig
vor Augen.\\
\\
Ob der Verfasser außerbiblische Quellen bei der Abfassung seines Werkes
benutzt hat, bleibt umstritten. Zwar besitzen Form und Inhalt des Buches
eine außerbiblische Vorgeschichte: Die Form des Dialogs findet sich z.
B. in Weisheitsschriften Ägyptens; für den Inhalt wird auf Parallelen in
der sog. mesopotamischen Ijobliteratur verwiesen, die sich mit der
Ungerechtigkeit und dem Leiden eines Unschuldigen beschäftigt. Doch
verbieten es Gesamtkomposition und Aussageabsicht des Buches, von
literarischer Abhängigkeit zu sprechen.\\
\\
Gattungsmäßig gehört das Buch zur Weisheitsliteratur. Es verwendet
Redeformen aus den Bereichen der Weisheit, des Rechts und der Psalmen:
längere, erörternde Reden mit überwiegend polemischem Charakter, die für
»Streitgespräche« unter Weisheitslehrern und »Parteireden« im
Gerichtsverfahren charakteristisch sind; Klagen (an Gott gerichtete
Klagen, Sich-Beklagen, Verklagen der Gegner); auch fehlen nicht
hymnische Elemente. Alle Einzelformen sind der Aussageabsicht des Buches
dienstbar gemacht.\\
\\
Der Hauptteil besteht in einer Auseinandersetzung mit dem im alten
Israel verbreiteten Vergeltungsglauben, nach welchem es dem wirklich
guten Menschen in seinem Leben gut, dem Sünder dagegen schlecht ergeht.
Leid ist dann nur Strafe für begangene Sünden. Ijobs Freunde vertreten
diese Ansicht; doch Ijob wehrt sich entschieden gegen ihre Annahme, auch
er habe sich verfehlt und deshalb treffe ihn jetzt Gottes Strafe.\\
\\
Schließlich wendet sich Ijob angesichts des Rätsels seines für ihn
unverständlichen und ungerechtfertigten Leids an Gott selber als den
Helfer, auf den allein er in seiner Not seine ganze Hoffnung setzt. Gott
führt das Rätsel des Leidens des Gerechten keiner eigentlichen Lösung
zu, vielmehr weist er Ijob auf sein Unvermögen hin, die Pläne Gottes zu
durchschauen. Der Einblick in Gottes Absicht bei der Weltlenkung und in
seinen Ratschluss, nach dem er Glück und Unglück, Freud und Leid
zuteilt, bleibt dem Menschen versagt. So ergibt sich dann Ijob demütig
in Gottes Willen. Er überwindet jeden Gedanken an einen ihm feindlich
gesinnten und ihn ungerecht quälenden Gott zugunsten eines immer stärker
werdenden Vertrauens auf den immer gerechten Gott, der nicht wie Ijobs
Freunde den Menschen verurteilt, sondern ihn jenseits einer engherzigen
Vergeltungsvorstellung annimmt und nach dem Leid (vgl. Kap. 19) zu sich
führt.\\
\\
Das Buch Ijob zeigt einen Menschen im Leid, der Gott immer größer als
den Menschen sein lässt und sich ganz dieser Größe Gottes anheimgibt.
Das Leid bleibt ein ungelöstes Rätsel, das sich aller vernunftgemäßen
Erklärung entzieht. Aber durch das Leid stößt Gott neu zur
Glaubensentscheidung an.\\
\\

<<verses>>

<<v1>>
* Die Rahmenerzählung: 1,1 - 2,10

* Ijobs Rechtlichkeit: 1,1-5

1 Im Lande Uz lebte ein Mann mit Namen Ijob. Dieser Mann war untadelig
und rechtschaffen; er fürchtete Gott und mied das Böse. [fn:1] [fn:2]

<<v2>>
2 Sieben Söhne und drei Töchter wurden ihm geboren.

<<v3>>
3 Er besaß siebentausend Stück Kleinvieh, dreitausend Kamele,
fünfhundert Joch Rinder und fünfhundert Esel, dazu zahlreiches Gesinde.
An Ansehen übertraf dieser Mann alle Bewohner des Ostens. [fn:3]

<<v4>>
4 Reihum hielten seine Söhne ein Gastmahl, ein jeder an seinem Tag in
seinem Haus. Dann schickten sie hin und luden auch ihre Schwestern ein,
mit ihnen zu essen und zu trinken.

<<v5>>
5 Wenn die Tage des Gastmahls vorbei waren, schickte Ijob hin und
entsühnte sie. Früh am Morgen stand er auf und brachte so viele
Brandopfer dar, wie er Kinder hatte. Denn Ijob sagte: Vielleicht haben
meine Kinder gesündigt und Gott gelästert in ihrem Herzen. So tat Ijob
jedes Mal. [fn:4]\\
\\

<<v6>>
* Zwei Bewährungsproben: 1,6 - 2,10

* Der Verlust des Reichtums: 1,6-22

6 Nun geschah es eines Tages, da kamen die Gottessöhne, um vor den Herrn
hinzutreten; unter ihnen kam auch der Satan. [fn:5] [fn:6]

<<v7>>
7 Der Herr sprach zum Satan: Woher kommst du? Der Satan antwortete dem
Herrn und sprach: Die Erde habe ich durchstreift, hin und her.

<<v8>>
8 Der Herr sprach zum Satan: Hast du auf meinen Knecht Ijob geachtet?
Seinesgleichen gibt es nicht auf der Erde, so untadelig und
rechtschaffen, er fürchtet Gott und meidet das Böse.

<<v9>>
9 Der Satan antwortete dem Herrn und sagte: Geschieht es ohne Grund,
dass Ijob Gott fürchtet?

<<v10>>
10 Bist du es nicht, der ihn, sein Haus und all das Seine ringsum
beschützt? Das Tun seiner Hände hast du gesegnet; sein Besitz hat sich
weit ausgebreitet im Land.

<<v11>>
11 Aber streck nur deine Hand gegen ihn aus und rühr an all das, was
sein ist; wahrhaftig, er wird dir ins Angesicht fluchen. [fn:7]

<<v12>>
12 Der Herr sprach zum Satan: Gut, all sein Besitz ist in deiner Hand,
nur gegen ihn selbst streck deine Hand nicht aus! Darauf ging der Satan
weg vom Angesicht des Herrn.

<<v13>>
13 Nun geschah es eines Tages, dass seine Söhne und Töchter im Haus
ihres erstgeborenen Bruders aßen und Wein tranken.

<<v14>>
14 Da kam ein Bote zu Ijob und meldete: Die Rinder waren beim Pflügen
und die Esel weideten daneben.

<<v15>>
15 Da fielen Sabäer ein, nahmen sie weg und erschlugen die Knechte mit
scharfem Schwert. Ich ganz allein bin entronnen, um es dir zu berichten.

<<v16>>
16 Noch ist dieser am Reden, da kommt schon ein anderer und sagt: Feuer
Gottes fiel vom Himmel, schlug brennend ein in die Schafe und Knechte
und verzehrte sie. Ich ganz allein bin entronnen, um es dir zu
berichten. [fn:8]

<<v17>>
17 Noch ist dieser am Reden, da kommt schon ein anderer und sagt: Die
Chaldäer stellten drei Rotten auf, fielen über die Kamele her, nahmen
sie weg und erschlugen die Knechte mit scharfem Schwert. Ich ganz allein
bin entronnen, um es dir zu berichten.

<<v18>>
18 Noch ist dieser am Reden, da kommt schon ein anderer und sagt: Deine
Söhne und Töchter aßen und tranken Wein im Haus ihres erstgeborenen
Bruders.

<<v19>>
19 Da kam ein gewaltiger Wind über die Wüste und packte das Haus an
allen vier Ecken; es stürzte über die jungen Leute und sie starben. Ich
ganz allein bin entronnen, um es dir zu berichten.

<<v20>>
20 Nun stand Ijob auf, zerriss sein Gewand, schor sich das Haupt, fiel
auf die Erde und betete an.\\
\\

<<v21>>
21 Dann sagte er: Nackt kam ich hervor aus dem Schoß meiner Mutter; /\\
 nackt kehre ich dahin zurück. /\\
 Der Herr hat gegeben, der Herr hat genommen; /\\
 gelobt sei der Name des Herrn. [fn:9]\\
\\

<<v22>>
22 Bei alldem sündigte Ijob nicht und äußerte nichts Ungehöriges gegen
Gott.\\
\\

* Footnotes

[fn:1] [[file:Ez_14.org::v14][Ez 14,14]].[[file:Ez_14.org::v20][20]]; [[file:Gen_22.org::v12][Gen 22,12]]

[fn:2] Das Land Uz liegt vermutlich in Arabien (vgl. [[file:Gen_36.org::v28][Gen 36,28]];
[[file:Klgl_4.org::v21][Klgl 4,21]]). Ijob ist ein schon früh belegter Name und bedeutet
vielleicht «der Angefeindete».

[fn:3] Die «Bewohner des Ostens» sind die Bewohner Arabiens.

[fn:4] In H steht für «lästern» euphemistisch «segnen».

[fn:5] [[file:Sach_3.org::v1][Sach 3,1f]]

[fn:6] Die «Gottessöhne» werden in G mit den Engeln
gleichgesetzt. Sie gehören zum Hofstaat Jahwes (vgl. [[file:Ijob_38.org::v7][38,7]]). In [[file:Ps_29.org::v1][Ps 29,1]]
wird dieselbe Wendung mit «die Himmlischen», in [[file:Ps_82.org::v1][Ps 82,1]] und [[file:Ps_89.org::v7][89,7]] mit
«Götter» wiedergegeben.

[fn:7] Statt «fluchen» steht in H euphemistisch «segnen» (vgl.
Anmerkung zu [[v5][1,5]]).

[fn:8] Feuer Gottes: der Blitz (vgl. [[file:2.Kön_1.org::v10][2 Kön 1,10]]).

[fn:9] [[file:Ps_22.org::v10][Ps 22,10]]; [[file:Jes_44.org::v2][Jes 44,2]]
