#+TITLE: Ijob 27 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-02 Sa 18:23]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ijob 27.html

<<verses>>

<<v1>>
* Die Unschuldsbeteuerung vor den Freunden: 27,1-6

1 Dann setzte Ijob seine Rede fort und sprach:\\
\\

<<v2>>
2 So wahr Gott lebt, der mir mein Recht entzog, /\\
 der Allmächtige, der meine Seele quälte: [fn:1]\\
\\

<<v3>>
3 Solange noch Atem in mir ist /\\
 und Gottes Hauch in meiner Nase, [fn:2]\\
\\

<<v4>>
4 soll Unrecht nicht von meinen Lippen kommen, /\\
 noch meine Zunge Falsches reden.\\
\\

<<v5>>
5 Fern sei es mir, euch Recht zu geben, /\\
 ich gebe, bis ich sterbe, meine Unschuld nicht preis. [fn:3]\\
\\

<<v6>>
6 An meinem Rechtsein halt ich fest und lass es nicht; /\\
 mein Herz schilt keinen meiner Tage.\\
\\

<<v7>>
* Der Untergang der Frevler: 27,7-23

7 Mein Feind sei wie ein Frevler, /\\
 mein Gegner wie ein Bösewicht.\\
\\

<<v8>>
8 Denn was ist des Ruchlosen Hoffen, /\\
 wenn er dahingeht, /\\
 wenn Gott das Leben von ihm nimmt?\\
\\

<<v9>>
9 Wird Gott sein Schreien hören, /\\
 wenn über ihn die Drangsal kommt?\\
\\

<<v10>>
10 Kann er sich des Allmächtigen erfreuen /\\
 und Gott anrufen zu jeder Zeit? [fn:4]\\
\\

<<v11>>
11 Ich will euch belehren über Gottes Tun, /\\
 nicht verhehlen, was der Allmächtige plant.\\
\\

<<v12>>
12 Ihr habt es ja alle selbst gesehen. /\\
 Warum führt ihr nichtige Reden?\\
\\

<<v13>>
13 Das ist des Frevlers Anteil bei Gott, /\\
 der Gewalttätigen Erbe, /\\
 das sie vom Allmächtigen empfangen: [fn:5]\\
\\

<<v14>>
14 Werden zahlreich seine Söhne, /\\
 fürs Schwert sind sie bestimmt; /\\
 nie werden seine Kinder satt an Brot.\\
\\

<<v15>>
15 Was übrig bleibt, wird durch den Tod begraben /\\
 und seine Witwen weinen nicht. [fn:6]\\
\\

<<v16>>
16 Häuft er auch Silber auf wie Staub /\\
 und beschafft er sich Kleider wie Lehm:\\
\\

<<v17>>
17 er schafft sie zwar an; /\\
 doch anziehen wird sie der Gerechte, /\\
 das Silber wird der Schuldlose erben. [fn:7]\\
\\

<<v18>>
18 Er baut wie die Spinne sein Haus /\\
 und wie die Hütte, die der Wächter aufstellt. [fn:8] [fn:9]\\
\\

<<v19>>
19 Reich legt er sich schlafen, nichts ist ihm genommen. /\\
 Macht er die Augen auf, ist nichts mehr da.\\
\\

<<v20>>
20 Schrecken holt ihn ein wie eine Wasserflut, /\\
 der Sturmwind trägt ihn fort bei Nacht.\\
\\

<<v21>>
21 Der Ostwind hebt ihn hoch, er muss dahin, /\\
 er weht ihn weg von seinem Ort.\\
\\

<<v22>>
22 Er stürzt sich auf ihn schonungslos, /\\
 seiner Gewalt will er entfliehen.\\
\\

<<v23>>
23 Man klatscht über ihn in die Hände /\\
 und zischt ihn fort von seiner Stätte.\\
\\

* Footnotes

[fn:1] [[file:Ijob_34.org::v5][34,5f]]

[fn:2] [[file:Ijob_33.org::v4][33,4]]; [[file:Gen_2.org::v7][Gen 2,7]]

[fn:3] [[file:Ijob_33.org::v9][33,9]]

[fn:4] [[file:Ijob_22.org::v26][22,26]]

[fn:5] [[file:Ijob_20.org::v29][20,29]]

[fn:6] [[file:Ps_78.org::v64][Ps 78,64]]

[fn:7] [[file:Koh_2.org::v26][Koh 2,26]]; [[file:Sir_11.org::v18][Sir 11,18]]; [[file:Sir_14.org::v4][14,4]]

[fn:8] [[file:Ijob_8.org::v14][8,14]]

[fn:9] wie die Spinne: Text korr.; H: wie die Motte.
