#+TITLE: Ijob 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-29 Mi 22:22]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ijob 15.html

<<verses>>

<<v1>>
* Die zweite Rede des Elifas: 15,1-35

* Die Sündigkeit aller Menschen: 15,1-16

1 Da antwortete Elifas von Teman und sprach:\\
\\

<<v2>>
2 Gibt ein Weiser windige Kunde zur Antwort, /\\
 füllt er sein Inneres mit Ostwind an,\\
\\

<<v3>>
3 um zu rechten mit Gerede, das nichts taugt, /\\
 mit Worten, in denen kein Nutzen liegt?\\
\\

<<v4>>
4 Du brichst sogar die Gottesfurcht, /\\
 zerstörst das Besinnen vor Gott.\\
\\

<<v5>>
5 Denn deine Schuld belehrt deinen Mund, /\\
 die Sprache der Listigen hast du gewählt.\\
\\

<<v6>>
6 Dein eigener Mund verurteilt dich, nicht ich, /\\
 deine Lippen zeugen gegen dich.\\
\\

<<v7>>
7 Bist du als erster Mensch geboren, /\\
 kamst du zur Welt noch vor den Hügeln? [fn:1]\\
\\

<<v8>>
8 Hast du gelauscht im Rate Gottes /\\
 und die Weisheit an dich gerissen? [fn:2]\\
\\

<<v9>>
9 Was weißt du, das wir nicht wissen, /\\
 verstehst du, was uns nicht bekannt ist? [fn:3]\\
\\

<<v10>>
10 Auch unter uns sind Alte, sind Ergraute, /\\
 die älter sind an Tagen als dein Vater. [fn:4]\\
\\

<<v11>>
11 Ist zu gering dir Gottes Tröstung, /\\
 ein Wort, das sanft mit dir verfährt?\\
\\

<<v12>>
12 Wie reißt doch dein Herz dich fort, /\\
 wie überheben sich deine Augen,\\
\\

<<v13>>
13 dass gegen Gott deinen Zorn du wendest /\\
 und Worte (gegen ihn) aus deinem Mund stößt?\\
\\

<<v14>>
14 Was ist der Mensch, dass rein er wäre, /\\
 der vom Weib Geborene, dass er im Recht sein könnte? [fn:5]\\
\\

<<v15>>
15 Sieh doch, selbst seinen Heiligen traut er nicht /\\
 und der Himmel ist nicht rein vor ihm.\\
\\

<<v16>>
16 Geschweige denn ein Unreiner und Verderbter, /\\
 ein Mensch, der Verkehrtes trinkt wie Wasser. [fn:6]\\
\\

<<v17>>
* Die Hoffnungslosigkeit des Frevlers: 15,17-35

17 Verkünden will ich dir, hör mir zu! /\\
 Was ich geschaut, will ich erzählen,\\
\\

<<v18>>
18 was Weise zu berichten wissen, /\\
 was ihre Väter ihnen nicht verhehlten. [fn:7] [fn:8]\\
\\

<<v19>>
19 Ihnen allein war das Land gegeben, /\\
 kein Fremder ging unter ihnen einher.\\
\\

<<v20>>
20 Der Frevler bebt in Ängsten all seine Tage, /\\
 die Zahl der Jahre ist dem Tyrannen verborgen.\\
\\

<<v21>>
21 In seinen Ohren hallen Schreckensrufe, /\\
 mitten im Frieden kommt der Verwüster über ihn. [fn:9]\\
\\

<<v22>>
22 Er kann nicht hoffen, dem Dunkel zu entfliehen, /\\
 aufgespart ist er für das Schwert.\\
\\

<<v23>>
23 Er irrt umher nach Brot, wo (er es finde), /\\
 er weiß, dass ihn ein schwarzer Tag bedroht.\\
\\

<<v24>>
24 Not und Drangsal erschrecken ihn, /\\
 sie packen ihn wie ein kampfbereiter König.\\
\\

<<v25>>
25 Denn gegen Gott erhebt er seine Hand, /\\
 gegen den Allmächtigen erkühnt er sich. [fn:10]\\
\\

<<v26>>
26 Halsstarrig rennt er gegen ihn an /\\
 mit den dicken Buckeln seiner Schilde.\\
\\

<<v27>>
27 Mit Fett bedeckt er sein Gesicht, /\\
 tut Fett um seine Hüfte. [fn:11] [fn:12]\\
\\

<<v28>>
28 Er wohnt in zerstörten Städten, /\\
 in Häusern, darin niemand wohnt, /\\
 die man zu Trümmerstätten bestimmt.\\
\\

<<v29>>
29 Er wird nicht reich; sein Besitz hat nicht Bestand; /\\
 zur Erde neigt sich seine Ähre nicht.\\
\\

<<v30>>
30 Der Finsternis entrinnt er nicht, /\\
 die Flammenglut dörrt seinen Schößling aus, /\\
 er schwindet dahin beim Hauch seines Mundes.\\
\\

<<v31>>
31 Er baue nicht auf eitlen Trug; /\\
 denn sein Erwerb wird nur Enttäuschung sein. [fn:13]\\
\\

<<v32>>
32 Bevor sein Tag kommt, welkt er hin /\\
 und sein Palmzweig grünt nicht mehr.\\
\\

<<v33>>
33 Er stößt ihn ab wie der Weinstock saure Trauben, /\\
 wie der Ölbaum wirft er seine Blüten fort.\\
\\

<<v34>>
34 Unfruchtbar ist der Ruchlosen Rotte /\\
 und Feuer verzehrt die Zelte der Bestechung. [fn:14]\\
\\

<<v35>>
35 Von Mühsal schwanger, gebären sie nur Unheil; /\\
 nur Trug ist, was ihr Schoß hervorbringt. [fn:15]\\
\\

* Footnotes

[fn:1] [[file:Sir_49.org::v16][Sir 49,16]]; [[file:Spr_8.org::v25][Spr 8,25]]

[fn:2] [[file:Jes_40.org::v13][Jes 40,13]]; [[file:Jer_23.org::v18][Jer 23,18]]

[fn:3] [[file:~/Documents/notes/Bibel/nt/Röm_11.org::v34][Röm 11,34]]

[fn:4] [[file:Ijob_32.org::v7][32,7]]

[fn:5] [[file:Ijob_4.org::v17][4,17]]; [[file:Ijob_14.org::v4][14,4]]

[fn:6] [[file:Ijob_34.org::v7][34,7]]

[fn:7] [[file:Ijob_8.org::v8][8,8]]; [[file:Dtn_32.org::v7][Dtn 32,7]]

[fn:8] was ihre Väter ihnen nicht verhehlten: Text korr.; H:
was sie vor ihren Vätern nicht verhehlten.

[fn:9] [[file:Ijob_18.org::v11][18,11]]

[fn:10] [[file:Ps_75.org::v6][Ps 75,6]]

[fn:11] [[file:Ps_73.org::v7][Ps 73,7]]

[fn:12] Übersetzung unsicher.

[fn:13] [[file:Ijob_20.org::v6][20,6f]]

[fn:14] [[file:Ijob_20.org::v26][20,26]]

[fn:15] [[file:Ps_7.org::v15][Ps 7,15]]; [[file:Jes_59.org::v4][Jes 59,4]]; [[file:~/Documents/notes/Bibel/nt/Gal_6.org::v8][Gal 6,8]]
