#+TITLE: Ijob 8 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-29 Mi 14:15]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ijob 8.html

<<verses>>

<<v1>>
* Die erste Rede Bildads: 8,1-22

* Das Gesetz der Vergeltung: 8,1-7

1 Da antwortete Bildad von Schuach und sprach:\\
\\

<<v2>>
2 Wie lange noch willst du derlei reden? /\\
 Nur heftiger Wind sind die Worte deines Mundes.\\
\\

<<v3>>
3 Beugt etwa Gott das Recht /\\
 oder beugt der Allmächtige die Gerechtigkeit? [fn:1]\\
\\

<<v4>>
4 Haben deine Kinder gefehlt gegen ihn, /\\
 gab er sie der Gewalt ihres Frevels preis.\\
\\

<<v5>>
5 Wenn du mit Eifer Gott suchst, /\\
 an den Allmächtigen dich flehend wendest,\\
\\

<<v6>>
6 wenn du rein bist und recht, /\\
 dann wird er über dich wachen, /\\
 dein Heim herstellen, wie es dir zusteht.\\
\\

<<v7>>
7 Und war dein Anfang auch gering, /\\
 dein Ende wird gewaltig groß.\\
\\

<<v8>>
* Das Zeugnis der Erfahrung: 8,8-22

8 Ja, frag nur das frühere Geschlecht /\\
 und merk dir, was die Väter erforschten. [fn:2]\\
\\

<<v9>>
9 Wir sind von gestern nur und wissen nichts, /\\
 wie Schatten sind auf Erden unsre Tage.\\
\\

<<v10>>
10 Unterweisen sie dich nicht, sprechen sie nicht zu dir, /\\
 geben sie dir nicht Worte aus ihrem Herzen:\\
\\

<<v11>>
11 Wächst ohne Sumpf das Schilfrohr hoch, /\\
 wird Riedgras ohne Wasser groß?\\
\\

<<v12>>
12 In Blüte und noch nicht gemäht, /\\
 verwelkt es schon vor allem Gras.\\
\\

<<v13>>
13 So enden alle, die Gott vergessen, /\\
 des Ruchlosen Hoffen wird zunichte. [fn:3] [fn:4]\\
\\

<<v14>>
14 Ein Spinngewebe ist seine Zuversicht, /\\
 ein Spinnennetz sein Verlass.\\
\\

<<v15>>
15 Stützt er sich auf sein Haus, es hält nicht stand, /\\
 klammert er sich daran, es bleibt nicht stehen.\\
\\

<<v16>>
16 Er steht im Saft vor der Sonne, /\\
 seine Zweige überwuchern den Garten,\\
\\

<<v17>>
17 im Geröll verflechten sich seine Wurzeln, /\\
 zwischen Steinen halten sie sich fest.\\
\\

<<v18>>
18 Doch Gott tilgt ihn aus an seiner Stätte, /\\
 sie leugnet ihn: Nie habe ich dich gesehen.\\
\\

<<v19>>
19 Siehe, das ist die Freude seines Weges /\\
 und ein anderer sprießt aus dem Staub.\\
\\

<<v20>>
20 Ja, Gott verschmäht den Schuldlosen nicht, /\\
 die Hand der Boshaften aber hält er nicht fest.\\
\\

<<v21>>
21 Mit Lachen wird er deinen Mund noch füllen, /\\
 deine Lippen mit Jubel.\\
\\

<<v22>>
22 Deine Hasser werden sich kleiden in Schmach, /\\
 das Zelt der Frevler besteht nicht mehr. [fn:5]\\
\\

* Footnotes

[fn:1] [[file:Ijob_34.org::v10][34,10]]-[[file:Ijob_34.org::v12][12]]; [[file:Dtn_32.org::v4][Dtn 32,4]]

[fn:2] [[file:Ijob_15.org::v18][15,18]]; [[file:Ps_78.org::v3][Ps 78,3f]]

[fn:3] [[file:Spr_10.org::v28][Spr 10,28]]

[fn:4] Wörtlich: So sind die Wege aller.

[fn:5] [[file:Ps_6.org::v11][Ps 6,11]]; [[file:Spr_14.org::v11][Spr 14,11]]
