#+TITLE: Ijob 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-28 Di 23:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ijob 7.html

<<verses>>

<<v1>>
* Die Not des Lebens: 7,1-10

1 Ist nicht Kriegsdienst des Menschen Leben auf der Erde? /\\
 Sind nicht seine Tage die eines Tagelöhners? [fn:1]\\
\\

<<v2>>
2 Wie ein Knecht ist er, der nach Schatten lechzt, /\\
 wie ein Tagelöhner, der auf den Lohn wartet.\\
\\

<<v3>>
3 So wurden Monde voll Enttäuschung mein Erbe /\\
 und Nächte voller Mühsal teilte man mir zu.\\
\\

<<v4>>
4 Lege ich mich nieder, sage ich: /\\
 Wann darf ich aufstehn? /\\
 Wird es Abend, bin ich gesättigt mit Unrast, bis es dämmert. [fn:2]\\
\\

<<v5>>
5 Mein Leib ist gekleidet in Maden und Schorf, /\\
 meine Haut schrumpft und eitert. [fn:3]\\
\\

<<v6>>
6 Schneller als das Weberschiffchen eilen meine Tage, /\\
 der Faden geht aus, sie schwinden dahin. [fn:4] [fn:5]\\
\\

<<v7>>
7 Denk daran, dass mein Leben nur ein Hauch ist. /\\
 Nie mehr schaut mein Auge Glück. [fn:6]\\
\\

<<v8>>
8 Kein Auge gewahrt mich, das nach mir sieht, /\\
 suchen mich deine Augen, dann bin ich nicht mehr da.\\
\\

<<v9>>
9 Die Wolke schwindet, vergeht, /\\
 so steigt nie mehr auf, wer zur Unterwelt fuhr. [fn:7]\\
\\

<<v10>>
10 Nie kehrt er zurück in sein Haus, /\\
 nie mehr erblickt ihn sein Ort.\\
\\

<<v11>>
* Die unbegreifliche Heimsuchung: 7,11-21

11 So wehre ich nicht meinem Mund, /\\
 mit bedrängtem Geist will ich reden, /\\
 mit betrübter Seele will ich klagen.\\
\\

<<v12>>
12 Bin ich das Meer, der Meeresdrache, /\\
 dass du gegen mich eine Wache stellst? [fn:8]\\
\\

<<v13>>
13 Sagte ich: Mein Lager soll mich trösten, /\\
 mein Bett trage das Leid mit mir!,\\
\\

<<v14>>
14 so quältest du mich mit Träumen /\\
 und mit Gesichten jagtest du mich in Angst.\\
\\

<<v15>>
15 Erwürgt zu werden, zöge ich vor, /\\
 den Tod diesem Totengerippe. [fn:9]\\
\\

<<v16>>
16 Ich mag nicht mehr. Ich will nicht ewig leben. /\\
 Lass ab von mir; denn nur ein Hauch sind meine Tage. [fn:10]\\
\\

<<v17>>
17 Was ist der Mensch, dass du groß ihn achtest /\\
 und deinen Sinn auf ihn richtest, [fn:11]\\
\\

<<v18>>
18 dass du ihn musterst jeden Morgen /\\
 und jeden Augenblick ihn prüfst? [fn:12]\\
\\

<<v19>>
19 Wie lange schon schaust du nicht weg von mir, /\\
 lässt mich nicht los, sodass ich den Speichel schlucke? [fn:13]\\
\\

<<v20>>
20 Hab ich gefehlt? /\\
 Was tat ich dir, du Menschenwächter? /\\
 Warum stellst du mich vor dich als Zielscheibe hin? /\\
 Bin ich dir denn zur Last geworden? [fn:14]\\
\\

<<v21>>
21 Warum nimmst du mein Vergehen nicht weg, /\\
 lässt du meine Schuld nicht nach? /\\
 Dann könnte ich im Staub mich betten; /\\
 suchtest du mich, wäre ich nicht mehr da.\\
\\

* Footnotes

[fn:1] [[file:Ijob_14.org::v14][14,14]]

[fn:2] [[file:Koh_2.org::v23][Koh 2,23]]; [[file:Sir_40.org::v5][Sir 40,5]]

[fn:3] Text korr.; H: meine Hand schrumpft und wird verworfen.

[fn:4] [[file:Ps_39.org::v6][Ps 39,6]]; [[file:Jes_38.org::v12][Jes 38,12]]

[fn:5] Text korr.; H: sie gehen zu Ende ohne Hoffnung.

[fn:6] [[file:Ps_78.org::v39][Ps 78,39]]

[fn:7] [[file:Weish_2.org::v4][Weish 2,4]]

[fn:8] Anklang an einen alten Mythos (vgl. [[file:Ijob_3.org::v8][3,8]]).

[fn:9] [[file:Tob_3.org::v6][Tob 3,6]]

[fn:10] [[file:Ps_144.org::v4][Ps 144,4]]

[fn:11] [[file:Ps_144.org::v3][Ps 144,3]]

[fn:12] [[file:Ps_17.org::v3][Ps 17,3]]; [[file:Ps_139.org][139]]

[fn:13] [[file:Ps_39.org::v14][Ps 39,14]]

[fn:14] dir zur Last: H: mir zu Last.
