#+TITLE: Ijob 37 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-02 Sa 23:27]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ijob 37.html

<<verses>>

<<v1>>
* Über Gottes Macht: 37,1-13

1 Darum erbebt mein Herz sehr heftig, /\\
 pocht erregt an seiner Stelle.\\
\\

<<v2>>
2 Hört, hört das Toben der Stimme Gottes, /\\
 welch ein Grollen seinem Mund entfährt. [fn:1]\\
\\

<<v3>>
3 Unter dem ganzen Himmel lässt er es los /\\
 und seinen Blitz über die Säume der Erde.\\
\\

<<v4>>
4 Hinter ihm brüllt der Donner drein, /\\
 er dröhnt mit erhabener Stimme. Nicht hält er (die Blitze) zurück, /\\
 wenn sein Donner gehört wird. [fn:2]\\
\\

<<v5>>
5 Gott dröhnt mit seiner Stimme, wunderbar, /\\
 er schafft große Dinge, wir verstehen sie nicht: [fn:3]\\
\\

<<v6>>
6 Dem Schnee befiehlt er: Fall zur Erde!, /\\
 dem Regenschwall, seinen mächtigen Güssen.\\
\\

<<v7>>
7 Er versiegelt die Hand aller Menschen, /\\
 sodass alle Welt sein Tun erkennt. [fn:4] [fn:5]\\
\\

<<v8>>
8 Die Tiere verkriechen sich in ihr Versteck, /\\
 sie lagern in ihren Höhlen.\\
\\

<<v9>>
9 Aus seiner Kammer kommt der Sturm, /\\
 von den Winden des Nordens die Kälte.\\
\\

<<v10>>
10 Durch Gottes Hauch entsteht das Eis, /\\
 liegt starr des Wassers Fläche. [fn:6] [fn:7]\\
\\

<<v11>>
11 Auch belädt er die Wolken mit Nass, /\\
 streut umher die leuchtenden Wolken.\\
\\

<<v12>>
12 Sie ziehen hin und her, wie er sie lenkt, /\\
 um alles, was er gebietet, /\\
 zu wirken auf dem Kreis der Erde.\\
\\

<<v13>>
13 Sei es als Zuchtrute, sei es auch für seine Erde, /\\
 sei es als Erweis seiner Huld, /\\
 so lässt er es sie treffen.\\
\\

<<v14>>
* Über die Furcht vor Gott: 37,14-24

14 Hör dir dies an, Ijob! Steh still, /\\
 um die Wunder Gottes zu betrachten.\\
\\

<<v15>>
15 Weißt du, wie Gott ihnen Auftrag gibt, /\\
 wie das Licht seiner Wolke aufstrahlt?\\
\\

<<v16>>
16 Weißt du um der Wolke Schweben, /\\
 um die Wunderwerke des Allwissenden? [fn:8]\\
\\

<<v17>>
17 Du, dem die Kleider vor Hitze glühen, /\\
 wenn die Erde unter dem Südwind liegt,\\
\\

<<v18>>
18 wölbst du gleich ihm das Wolkenfirmament, /\\
 das fest ist wie ein gegossener Spiegel? [fn:9]\\
\\

<<v19>>
19 Lehre du uns, was wir ihm sagen sollen. /\\
 Wir können wegen des Dunkels nichts vorbringen.\\
\\

<<v20>>
20 Muss man ihm erst erzählen, wenn ich rede? /\\
 Muss es erst einer sagen, /\\
 damit es ihm mitgeteilt wird? [fn:10]\\
\\

<<v21>>
21 Und nun, wenn man das Sonnenlicht nicht sieht, /\\
 ist es verdunkelt durch die Wolken, /\\
 ein Windhauch bläst und fegt sie weg.\\
\\

<<v22>>
22 Vom Norden naht ein Lichtglanz, /\\
 um Gott her ist schreckliche Herrlichkeit. [fn:11]\\
\\

<<v23>>
23 Den Allmächtigen ergründen wir nicht, /\\
 er ist erhaben an Macht und Recht, /\\
 er ist reich an Gerechtigkeit; Recht beugt er nicht.\\
\\

<<v24>>
24 Darum sollen die Menschen ihn fürchten. /\\
 Keinen sieht er an, wie weise sie auch sind.\\
\\

* Footnotes

[fn:1] [[file:Ps_29.org][Ps 29]]

[fn:2] [[file:Ps_29.org::v3][Ps 29,3f]]

[fn:3] [[file:Ijob_5.org::v9][5,9]]

[fn:4] [[file:Ps_104.org::v19][Ps 104,19]]-[[file:Ps_104.org::v23][23]]

[fn:5] Gemeint ist: Gott zwingt die Menschen zur Untätigkeit.

[fn:6] [[file:Ps_147.org::v17][Ps 147,17]]

[fn:7] entsteht: Text korr.; H hat eine andere Vokalisierung.

[fn:8] [[file:Spr_8.org::v28][Spr 8,28]]

[fn:9] [[file:Gen_1.org::v6][Gen 1,6]]

[fn:10] Text unsicher.

[fn:11] [[file:Ex_24.org::v16][Ex 24,16]]
