#+TITLE: Ijob 19 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-29 Mi 22:56]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ijob 19.html

<<verses>>

<<v1>>
* Ijobs Gegenrede: 19,1-29

* Die Zurückweisung der Schmähung: 19,1-5

1 Da antwortete Ijob und sprach:\\
\\

<<v2>>
2 Wie lange noch wollt ihr mich quälen /\\
 und mich mit Worten niedertreten?\\
\\

<<v3>>
3 Zum zehnten Mal schon schmäht ihr mich /\\
 und schämt euch nicht, mich zu beleidigen.\\
\\

<<v4>>
4 Ging ich wirklich unwissend fehl, /\\
 mein Fehltritt weilt doch allein bei mir.\\
\\

<<v5>>
5 Wollt ihr wirklich großtun gegen mich /\\
 und mir meine Schmach beweisen?\\
\\

<<v6>>
* Das unbegreifliche Verhalten Gottes: 19,6-12

6 Erkennt doch, dass Gott mich niederdrückt, /\\
 da er sein Netz rings um mich warf.\\
\\

<<v7>>
7 Schrei ich: Gewalt!, wird mir keine Antwort, /\\
 rufe ich um Hilfe, gibt es kein Recht. [fn:1]\\
\\

<<v8>>
8 Meinen Pfad hat er versperrt; ich kann nicht weiter, /\\
 Finsternis legt er auf meine Wege.\\
\\

<<v9>>
9 Meiner Ehre hat er mich entkleidet, /\\
 die Krone mir vom Haupt genommen. [fn:2]\\
\\

<<v10>>
10 Er brach mich ringsum nieder, ich muss dahin; /\\
 er riss mein Hoffen aus wie einen Baum. [fn:3]\\
\\

<<v11>>
11 Sein Zorn ist gegen mich entbrannt, /\\
 gleich seinen Gegnern gelte ich ihm. [fn:4]\\
\\

<<v12>>
12 Vereint rückten seine Scharen an, /\\
 bahnten gegen mich den Weg, /\\
 lagerten sich rings um mein Zelt.\\
\\

<<v13>>
* Die Entfremdung der Verwandten und Freunde: 19,13-22

13 Meine Brüder hat er von mir entfernt, /\\
 meine Bekannten sind mir entfremdet. [fn:5]\\
\\

<<v14>>
14 Meine Verwandten, Bekannten blieben aus, /\\
 die Gäste meines Hauses haben mich vergessen.\\
\\

<<v15>>
15 Als Fremder gelte ich meinen Mägden, /\\
 von anderem Stamm bin ich in ihren Augen.\\
\\

<<v16>>
16 Rufe ich meinen Knecht, so antwortet er nicht; /\\
 mit eigenem Mund muss ich ihn anflehen.\\
\\

<<v17>>
17 Mein Atem ist meiner Frau zuwider; /\\
 die Söhne meiner Mutter ekelt es vor mir.\\
\\

<<v18>>
18 Buben selbst verachten mich, /\\
 stehe ich auf, verhöhnen sie mich.\\
\\

<<v19>>
19 Alle meine Gefährten verabscheuen mich, /\\
 die ich liebe, lehnen sich gegen mich auf. [fn:6]\\
\\

<<v20>>
20 An Haut und Fleisch klebt mein Gebein, /\\
 nur das Fleisch an meinen Zähnen blieb.\\
\\

<<v21>>
21 Erbarmt, erbarmt euch meiner, ihr, meine Freunde! /\\
 Denn Gottes Hand hat mich getroffen.\\
\\

<<v22>>
22 Warum verfolgt ihr mich wie Gott, /\\
 warum werdet ihr an meinem Fleisch nicht satt?\\
\\

<<v23>>
* Ijobs Hoffnung und Vertrauen: 19,23-29

23 Dass doch meine Worte geschrieben würden, /\\
 in einer Inschrift eingegraben\\
\\

<<v24>>
24 mit eisernem Griffel und mit Blei, /\\
 für immer gehauen in den Fels.\\
\\

<<v25>>
25 Doch ich, ich weiß: mein Erlöser lebt, /\\
 als Letzter erhebt er sich über dem Staub. [fn:7]\\
\\

<<v26>>
26 Ohne meine Haut, die so zerfetzte, /\\
 und ohne mein Fleisch werde ich Gott schauen. [fn:8]\\
\\

<<v27>>
27 Ihn selber werde ich dann für mich schauen; /\\
 meine Augen werden ihn sehen, nicht mehr fremd. /\\
 Danach sehnt sich mein Herz in meiner Brust. [fn:9]\\
\\

<<v28>>
28 Wenn ihr sagt: Wie wollen wir ihn verfolgen /\\
 und den Grund der Sache an ihm finden!,\\
\\

<<v29>>
29 dann bangt für euch selber vor dem Schwert; /\\
 denn heftiger Zorn verdient das Schwert, /\\
 damit ihr wisst: Es gibt ein Gericht. [fn:10]\\
\\

* Footnotes

[fn:1] [[file:Klgl_3.org::v7][Klgl 3,7]]-[[file:Klgl_3.org::v9][9]]; [[file:Hab_1.org::v2][Hab 1,2]]

[fn:2] [[file:Ijob_29.org::v14][29,14]]

[fn:3] [[file:Ijob_14.org::v7][14,7f]]

[fn:4] [[file:Ijob_33.org::v10][33,10]]

[fn:5] [[file:Ps_32.org::v12][Ps 31,12]]; [[file:Ps_38.org::v12][38,12]]; [[file:Ps_69.org::v9][69,9]]; [[file:Ps_88.org::v19][88,19]]

[fn:6] [[file:Ps_41.org::v10][Ps 41,10]]; [[file:Sir_6.org::v8][Sir 6,8]]

[fn:7] [[file:Ijob_16.org::v19][16,19]]

[fn:8] H unklar.

[fn:9] Für «Herz» steht in H «Nieren» als Sitz des
Seelenlebens.

[fn:10] [[file:Ps_58.org::v12][Ps 58,12]]
