#+TITLE: Ijob 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-28 Di 23:15]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ijob 5.html

<<verses>>

<<v1>>
* Die Verantwortlichkeit des Menschen: 5,1-7

1 Ruf doch! Ist einer, der dir Antwort gibt? /\\
 An wen von den Heiligen willst du dich wenden? [fn:1] [fn:2]\\
\\

<<v2>>
2 Den Toren bringt der Ärger um, /\\
 Leidenschaft tötet den Narren.\\
\\

<<v3>>
3 Wohl sah ich einen Toren Wurzel fassen, /\\
 doch plötzlich musste ich seine Wohnstatt verwünschen.\\
\\

<<v4>>
4 Weit weg vom Heil sind seine Kinder, /\\
 werden zertreten im Tor, sind ohne Helfer. [fn:3] [fn:4]\\
\\

<<v5>>
5 Seine Ernte verzehrt der Hungernde, /\\
 selbst aus Dornen holt er sie heraus, /\\
 Durstige lechzen nach seinem Gut.\\
\\

<<v6>>
6 Denn nicht aus dem Staub geht Unheil hervor, /\\
 nicht aus dem Ackerboden sprosst die Mühsal,\\
\\

<<v7>>
7 sondern der Mensch ist zur Mühsal geboren, /\\
 wie Feuerfunken, die hochfliegen. [fn:5]\\
\\

<<v8>>
* Die Unterwerfung unter Gott: 5,8-27

8 Ich aber, ich würde Gott befragen /\\
 und Gott meine Sache vorlegen,\\
\\

<<v9>>
9 der Großes und Unergründliches tut, /\\
 Wunder, die niemand zählen kann. [fn:6]\\
\\

<<v10>>
10 Er spendet Regen über die Erde hin /\\
 und sendet Wasser auf die weiten Fluren,\\
\\

<<v11>>
11 um Niedere hoch zu erheben, /\\
 damit Trauernde glücklich werden. [fn:7]\\
\\

<<v12>>
12 Er zerbricht die Ränke der Listigen, /\\
 damit ihre Hände nichts Rechtes vollbringen.\\
\\

<<v13>>
13 Weise fängt er in ihrer List, /\\
 damit der Schlauen Plan sich überstürzt.\\
\\

<<v14>>
14 Am hellen Tag stoßen sie auf Finsternis, /\\
 am Mittag tappen sie umher wie in der Nacht. [fn:8]\\
\\

<<v15>>
15 Er rettet vor dem Schwert ihres Mundes, /\\
 aus der Hand des Starken den Armen.\\
\\

<<v16>>
16 Hoffnung wird den Geringen zuteil, /\\
 die Bosheit muss ihr Maul verschließen. [fn:9]\\
\\

<<v17>>
17 Ja, wohl dem Mann, den Gott zurechtweist. /\\
 Die Zucht des Allmächtigen verschmähe nicht! [fn:10]\\
\\

<<v18>>
18 Denn er verwundet und er verbindet, /\\
 er schlägt, doch seine Hände heilen auch. [fn:11]\\
\\

<<v19>>
19 In sechs Drangsalen wird er dich retten, /\\
 in sieben rührt kein Leid dich an.\\
\\

<<v20>>
20 In Hungerzeiten rettet er dich vom Tod, /\\
 im Krieg aus der Gewalt des Schwertes. [fn:12]\\
\\

<<v21>>
21 Du bist geborgen vor der Geißel der Zunge, /\\
 brauchst nicht zu bangen, dass Verwüstung kommt. [fn:13]\\
\\

<<v22>>
22 Über Verwüstung und Hunger kannst du lachen, /\\
 von wilden Tieren hast du nichts zu fürchten.\\
\\

<<v23>>
23 Mit den Steinen des Feldes bist du verbündet, /\\
 die Tiere des Feldes werden Frieden mit dir halten. [fn:14]\\
\\

<<v24>>
24 Du wirst erfahren, dass dein Zelt in Frieden bleibt; /\\
 prüfst du dein Heim, so fehlt dir nichts.\\
\\

<<v25>>
25 Du wirst erfahren, dass deine Nachkommen zahlreich sind, /\\
 deine Sprösslinge wie das Gras der Erde. [fn:15]\\
\\

<<v26>>
26 Bei voller Kraft steigst du ins Grab, /\\
 wie man Garben einbringt zu ihrer Zeit.\\
\\

<<v27>>
27 Ja, das haben wir erforscht, so ist es. /\\
 Wir haben es gehört. Nimm auch du es an! [fn:16]\\
\\

* Footnotes

[fn:1] [[file:Ps_89.org::v6][Ps 89,6]]

[fn:2] Die «Heiligen» sind die Engel im Hofstaat Gottes (vgl.
die Anmerkung zu [[file:Ijob_1.org::v6][1,6]]).

[fn:3] [[file:ps109::v10][Ps 109,10]]

[fn:4] Das Stadttor ist der Ort der Gerichtsverhandlung.

[fn:5] [[file:Gen_3.org::v17][Gen 3,17]]-[[file:Gen_3.org::v19][19]]

[fn:6] [[file:Ijob_9.org::v10][9,10]]

[fn:7] [[file:1.Sam_2.org::v7][1 Sam 2,7f]]

[fn:8] [[file:~/RoamNotes/notes/Bibel/nt/Joh_12.org::v35][Joh 12,35]]

[fn:9] [[file:Ps_107.org::v42][Ps 107,42]]

[fn:10] [[file:Ps_94.org::v12][Ps 94,12]]

[fn:11] [[file:Dtn_32.org::v39][Dtn 32,39]]

[fn:12] [[file:ps33:v19][Ps 33,19]]

[fn:13] [[file:Ps_12.org::v3][Ps 12,3]]-[[file:Ps_12.org::v5][5]]

[fn:14] [[file:Jes_11.org::v6][Jes 11,6]]-[[file:Jes_11.org::v8][8]]; [[file:Hos_2.org::v20][Hos 2,20]]

[fn:15] [[file:Dtn_28.org::v4][Dtn 28,4]].[[file:Dtn_28.org::v11][11]]

[fn:16] Wir haben es gehört: Text korr. nach G und S; H: Hör es!
