#+TITLE: Ijob 41 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-03 So 00:15]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ijob 41.html

* Ijob 41

<<verses>>

<<v1>>
1 Sieh, das Hoffen darauf wird enttäuscht; /\\
 sein bloßer Anblick bringt zu Fall.\\
\\

<<v2>>
2 So kühn ist keiner, es zu reizen; /\\
 wer könnte ihm wohl trotzen?\\
\\

<<v3>>
3 Wer begegnete ihm und bliebe heil? /\\
 Unter dem ganzen Himmel gibt es so einen nicht. [fn:1]\\
\\

<<v4>>
4 Ich will nicht schweigen von seinen Gliedern, /\\
 wie groß und mächtig, wie wohlgeschaffen es ist. [fn:2]\\
\\

<<v5>>
5 Wer öffnet die Hülle seines Kleides, /\\
 wer dringt in seinen Doppelpanzer ein?\\
\\

<<v6>>
6 Wer öffnet die Tore seines Mauls? /\\
 Rings um seine Zähne lagert Schrecken. [fn:3]\\
\\

<<v7>>
7 Reihen von Schilden sind sein Rücken, /\\
 verschlossen mit Siegel aus Kieselstein. [fn:4]\\
\\

<<v8>>
8 Einer reiht sich an den andern, /\\
 kein Lufthauch dringt zwischen ihnen durch.\\
\\

<<v9>>
9 Fest haftet jeder an dem andern, /\\
 sie sind verklammert, lösen sich nicht.\\
\\

<<v10>>
10 Sein Niesen lässt Licht aufleuchten; /\\
 seine Augen sind wie des Frührots Wimpern.\\
\\

<<v11>>
11 Aus seinem Maul fahren brennende Fackeln, /\\
 feurige Funken schießen hervor.\\
\\

<<v12>>
12 Rauch dampft aus seinen Nüstern /\\
 wie aus kochendem, heißem Topf. [fn:5] [fn:6]\\
\\

<<v13>>
13 Sein Atem entflammt glühende Kohlen, /\\
 eine Flamme schlägt aus seinem Maul hervor.\\
\\

<<v14>>
14 Stärke wohnt in seinem Nacken, /\\
 vor ihm her hüpft bange Furcht.\\
\\

<<v15>>
15 Straff liegt seines Wanstes Fleisch, /\\
 wie angegossen, unbewegt.\\
\\

<<v16>>
16 Sein Herz ist fest wie Stein, /\\
 fest wie der untere Mühlstein.\\
\\

<<v17>>
17 Erhebt es sich, erschrecken selbst die Starken; /\\
 vor Schrecken wissen sie nicht aus noch ein.\\
\\

<<v18>>
18 Trifft man es, kein Schwert hält stand, /\\
 nicht Lanze noch Geschoss und Pfeil.\\
\\

<<v19>>
19 Eisen achtet es wie Stroh, /\\
 Bronze wie morsch gewordenes Holz.\\
\\

<<v20>>
20 Kein Bogenpfeil wird es verjagen, /\\
 in Stoppeln verwandeln sich ihm /\\
 die Steine der Schleuder.\\
\\

<<v21>>
21 Wie Stoppeln dünkt ihm die Keule, /\\
 es lacht nur über Schwertergerassel.\\
\\

<<v22>>
22 Sein Unteres sind Scherbenspitzen; /\\
 ein Dreschbrett breitet es über den Schlamm.\\
\\

<<v23>>
23 Die Tiefe lässt es brodeln wie den Kessel, /\\
 macht das Meer zu einem Salbentopf.\\
\\

<<v24>>
24 Es hinterlässt eine leuchtende Spur; /\\
 man meint, die Flut sei Greisenhaar.\\
\\

<<v25>>
25 Auf Erden gibt es seinesgleichen nicht, /\\
 dazu geschaffen, um sich nie zu fürchten.\\
\\

<<v26>>
26 Alles Hohe blickt es an; /\\
 König ist es über alle stolzen Tiere.\\
\\

* Footnotes

[fn:1] ihm: Text korr.; H: mir.

[fn:2] Sinn von H unklar.

[fn:3] Maul, wörtlich: Gesicht.

[fn:4] sein Rücken: Text korr.; H: sein Hochmut.

[fn:5] [[file:~/Documents/notes/Bibel/nt/Offb_9.org::v17][Offb 9,17]]

[fn:6] Sinn von H unklar.
