#+TITLE: Jdt 16 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 22:02]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jdt 16.html

<<verses>>

<<v1>>
* Judits Lobgesang: 16,1-17

1 Judit sang: Stimmt ein Lied an für meinen Gott unter Paukenschall, /\\
 singt für den Herrn unter Zimbelklang! /\\
 Preist ihn und singt sein Lob, /\\
 rühmt seinen Namen und ruft ihn an! [fn:1]\\
\\

<<v2>>
2 Denn der Herr ist ein Gott, /\\
 der den Kriegen ein Ende setzt; /\\
 er führte mich heim in sein Lager inmitten des Volkes /\\
 und rettete mich aus der Gewalt der Feinde. [fn:2]\\
\\

<<v3>>
3 Assur kam von den Bergen des Nordens /\\
 mit seiner unzählbaren Streitmacht; /\\
 die Masse der Truppen verstopfte die Täler, /\\
 sein Reiterheer bedeckte die Hügel.\\
\\

<<v4>>
4 Brandschatzen wollten sie mein Gebiet, /\\
 die Jugend morden mit scharfem Schwert, /\\
 den zarten Säugling am Boden zerschmettern, /\\
 die Kinder als Beute verschleppen, /\\
 als billigen Raub die Mädchen entführen.\\
\\

<<v5>>
5 Doch der Herr, der Allmächtige, gab sie preis, /\\
 er gab sie der Vernichtung preis /\\
 durch die Hand einer Frau.\\
\\

<<v6>>
6 Ihr Held fiel nicht durch die Kraft junger Männer, /\\
 nicht Söhne von Riesen erschlugen ihn, /\\
 noch traten ihm hohe Recken entgegen. /\\
 Nein, Judit, Meraris Tochter, /\\
 bannte seine Macht mit dem Reiz ihrer Schönheit.\\
\\

<<v7>>
7 Sie legte ihr Witwengewand ab, /\\
 um den Bedrängten in Israel zu helfen. /\\
 Sie salbte ihr Gesicht mit duftendem Öl,\\
\\

<<v8>>
8 sie schmückte ihre Haare mit einem Diadem /\\
 und zog ein Leinenkleid an, um ihn zu verführen.\\
\\

<<v9>>
9 Ihre Sandalen bezauberten sein Auge. /\\
 So schlug ihre Schönheit sein Herz in Bann. /\\
 Das Schwert traf seinen Nacken mit Wucht.\\
\\

<<v10>>
10 Die Perser erschraken vor ihrer Kühnheit, /\\
 die Meder erstarrten vor ihrem Mut. [fn:3]\\
\\

<<v11>>
11 Jubel erfüllte mein armes Volk - /\\
 sie aber gerieten in Schrecken. /\\
 Die Meinen waren schwach - /\\
 sie aber packte Entsetzen. /\\
 Die einen stimmten den Schlachtruf an - /\\
 die anderen ergriffen die Flucht.\\
\\

<<v12>>
12 Erbärmliches Volk! Man stieß sie nieder /\\
 und schlug sie nieder wie Kinder von Ehebrecherinnen; /\\
 sie kamen um durch das Heer meines Herrn.\\
\\

<<v13>>
13 Ich singe meinem Gott ein neues Lied; /\\
 Herr, du bist groß und voll Herrlichkeit. /\\
 Wunderbar bist du in deiner Stärke, /\\
 keiner kann dich übertreffen. [fn:4]\\
\\

<<v14>>
14 Dienen muss dir deine ganze Schöpfung. /\\
 Denn du hast gesprochen und alles entstand. /\\
 Du sandtest deinen Geist, um den Bau zu vollenden. /\\
 Kein Mensch kann deinem Wort widerstehen.\\
\\

<<v15>>
15 Meere und Berge erbeben in ihrem Grund, /\\
 vor dir zerschmelzen die Felsen wie Wachs. /\\
 Doch wer dich fürchtet, der erfährt deine Gnade.\\
\\

<<v16>>
16 Zu gering ist jedes Opfer, um dich zu erfreuen, /\\
 alle Fettstücke sind nichts beim Opfer für dich. /\\
 Wer den Herrn fürchtet, der ist groß für immer.\\
\\

<<v17>>
17 Doch weh den Völkern, die mein Volk bekämpfen. /\\
 Am Tag des Gerichts straft sie der allmächtige Herr, /\\
 er schickt Feuer und Würmer in ihr Gebein; /\\
 in Ewigkeit sollen sie heulen vor Schmerz. [fn:5]\\
\\

<<v18>>
* Das Siegesfest in Jerusalem: 16,18-20

18 Als sie nach Jerusalem gekommen waren, warfen sie sich vor Gott zum
Gebet nieder. Die Leute reinigten sich und brachten ihre Brandopfer,
ihre freiwilligen Opfer und ihre sonstigen Gaben dar.

<<v19>>
19 Judit stiftete dem Heiligtum alles, was ihr das Volk aus der Beute
des Holofernes überlassen hatte. Auch das Mückennetz, das sie aus seinem
Schlafgemach mitgenommen hatte, schenkte sie Gott als Weihegabe.

<<v20>>
20 Drei Monate lang feierte das Volk vor dem Heiligtum in Jerusalem ein
Freudenfest und Judit blieb bei ihnen.\\
\\

<<v21>>
* Die letzten Jahre Judits: 16,21-25

21 Nach Ablauf dieser Zeit kehrte jeder in seinen Erbbesitz zurück.
Judit ging nach Betulia und blieb auf ihrem Anwesen. Solange sie lebte,
war sie im ganzen Land hochgerühmt.

<<v22>>
22 Viele hätten sie gern zur Frau gehabt; aber seit ihr Gatte Manasse
gestorben und zu seinen Vätern gerufen war, durfte kein Mann sie mehr
berühren ihr Leben lang.

<<v23>>
23 Sie erlebte ein sehr hohes Alter und wurde im Haus ihres Mannes
hundertfünf Jahre alt. Ihrer Dienerin schenkte sie die Freiheit. Sie
starb in Betulia und man bestattete sie in der Grabhöhle ihres Gatten
Manasse.

<<v24>>
24 Das Haus Israel betrauerte sie sieben Tage lang. Vor ihrem Tod hatte
sie noch ihren Besitz an alle Verwandten ihres Gatten Manasse und an die
Angehörigen ihrer eigenen Familie verteilt.

<<v25>>
25 Niemand aber wagte mehr, die Israeliten zu beunruhigen, solange Judit
lebte und auch noch lange Zeit nach ihrem Tod.\\
\\

* Footnotes

[fn:1] [[file:Ps_150.org::v4][Ps 150,4]]

[fn:2] [[file:Ps_46.org::v10][Ps 46,10]]

[fn:3] Die Erwähnung von Persern und Medern in einem Lied, das
die Niederlage der Assyrer zum Gegenstand hat, erklärt sich leicht, wenn
man den übergeschichtlichen Charakter der heidnischen Weltmacht beachtet
(vgl. die Anmerkung zu 1,1).

[fn:4] [[file:Ps_33.org::v3][Ps 33,3]]; [[file:Ps_96.org::v1][96,1]]; [[file:Ps_144.org::v9][144,9]]; [[file:Jes_42.org::v10][Jes 42,10]]

[fn:5] [[file:Jes_66.org::v24][Jes 66,24]]
