#+TITLE: Jdt 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 21:34]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Jdt 3.html

* Jdt 3

<<verses>>

<<v1>>
1 Sie schickten Boten zu ihm mit einem Friedensangebot und ließen ihm
sagen:

<<v2>>
2 Wir, die Sklaven des großen Königs Nebukadnezzar, liegen dir zu Füßen.
Tu mit uns, wie du willst.

<<v3>>
3 Unsere Gehöfte, alle unsere Ortschaften und Weizenfelder, die Herden,
das Klein- und Großvieh in allen Hürden an unseren Lagerplätzen stehen
dir zur Verfügung. Verfahr damit nach deinem Belieben!

<<v4>>
4 Auch unsere Städte mit ihren Einwohnern sind dir untertan. Komm und
verfahr mit ihnen nach deinem Willen!

<<v5>>
5 Mit dieser Botschaft kamen die Männer zu Holofernes.

<<v6>>
6 Da stieg er mit seinen Truppen zur Küste hinab, besetzte die
befestigten Städte und hob dort die tüchtigsten Männer aus zur
Verstärkung seines Heeres.

<<v7>>
7 Die Einwohner der Städte und des Landes empfingen ihn mit Kränzen und
unter Tanz und Paukenschlag.

<<v8>>
8 Doch er ließ alle ihre Kulthöhen zerstören und ihre Götterhaine
umhauen. Ihm war die Macht gegeben, alle Götter der Erde zu vernichten.
Alle Völker sollten nur Nebukadnezzar verehren und alle Stämme und
Nationen ihn als Gott anrufen.\\
\\

<<v9>>
* Die Bedrohung des Gottesvolkes: 3,9-10

9 So kam er in das Gebiet von Jesreel nahe bei Dotan, das vor dem großen
Gebirgszug von Judäa liegt.

<<v10>>
10 Er schlug zwischen Gabbai und Skythopolis sein Lager auf und blieb
dort einen Monat, um den ganzen Tross seines Heeres zusammenzuziehen.\\
\\
