#+TITLE: Jdt 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 21:58]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jdt 12.html

<<verses>>

<<v1>>
* Judits Sorge um die rituelle Reinheit: 12,1-9

1 Dann ließ er sie in den Raum führen, wo sein silbernes Tafelgerät
aufgestellt war, und befahl, ihr von den feinen Speisen auf seinem Tisch
vorzusetzen und von seinem Wein zu trinken zu geben.

<<v2>>
2 Doch Judit sagte: Ich werde nichts davon nehmen, damit ich keinen
Anstoß errege. Man soll mir statt dessen von meinem Vorrat zu essen
geben, den ich mitgebracht habe. [fn:1]

<<v3>>
3 Da fragte Holofernes: Wenn aber dein Vorrat erschöpft ist, woher
sollen wir dann solche Nahrungsmittel beschaffen? Wir haben ja niemand
aus deinem Volk bei uns.

<<v4>>
4 Judit erwiderte: Bei deinem Leben, mein Herr, noch bevor deine Magd
ihren Vorrat aufgebraucht hat, wird der Herr durch meine Hand
vollbringen, was er beschlossen hat.

<<v5>>
5 Darauf führten die Diener des Holofernes sie in das Zelt, wo sie bis
Mitternacht schlief. Um die Zeit der Morgenwache stand sie auf,

<<v6>>
6 schickte einen Boten zu Holofernes und ließ ihm sagen: Möge mein Herr
Anweisung geben, dass man deine Sklavin zum Gebet hinausgehen lässt.

<<v7>>
7 Da befahl Holofernes seinen Leibwächtern, sie nicht daran zu hindern.
So verbrachte sie drei Tage im Lager und ging jede Nacht in die Schlucht
von Betulia hinaus, um sich im Lager an der Wasserquelle zu baden.

<<v8>>
8 Wenn sie aus dem Bad herausstieg, flehte sie zu dem Herrn, dem Gott
Israels, er möge ihr Vorhaben gelingen lassen und ihrem Volk wieder
aufhelfen.

<<v9>>
9 Dann kehrte sie im Zustand der Reinheit zurück und blieb in dem Zelt,
bis sie gegen Abend ihr Essen zu sich nahm.\\
\\

<<v10>>
* Judit beim Gastmahl des Holofernes: 12,10-20

10 Am vierten Tag gab Holofernes ein Gastmahl nur für seine
Dienerschaft; von den Männern, die sonst um ihn waren, lud er keinen
ein.

<<v11>>
11 Dem Eunuchen Bagoas, der sein ganzes Eigentum zu verwalten hatte, gab
er den Auftrag: Geh und rede der Hebräerin zu, die deiner Obhut
anvertraut ist, dass sie zu uns kommt und mit uns isst und trinkt.

<<v12>>
12 Es wäre wahrhaftig eine Schande für uns, wenn wir eine solche Frau
gehen ließen, ohne mit ihr zusammen gewesen zu sein. Sie selber würde
uns auslachen, wenn wir sie nicht an uns rissen.

<<v13>>
13 Bagoas ging weg, trat bei Judit ein und sagte: Möge das schöne
Mädchen nicht zögern, zu meinem Herrn zu kommen; sie soll ihm gegenüber
den Ehrenplatz einnehmen, mit uns Wein trinken und fröhlich sein und
heute den assyrischen Mädchen gleich werden, die im Palast
Nebukadnezzars ihren Dienst tun.

<<v14>>
14 Judit entgegnete: Wer bin ich, dass ich meinem Herrn widersprechen
dürfte? Ich will unverzüglich alles tun, was er wünscht; das soll mir
eine Freude sein bis zum Tag meines Todes.

<<v15>>
15 Judit stand auf, legte ihr bestes Kleid und ihren ganzen Schmuck an.
Ihre Dienerin eilte voraus und legte für sie gegenüber von Holofernes
die Teppiche auf den Boden, die sie von Bagoas als Lager für ihre
täglichen Mahlzeiten erhalten hatte.

<<v16>>
16 Darauf trat Judit ein und nahm Platz. Holofernes aber war über sie
ganz außer sich vor Entzücken. Seine Leidenschaft entbrannte und er war
begierig danach, mit ihr zusammen zu sein. Denn seit er sie gesehen
hatte, lauerte er auf eine günstige Gelegenheit, um sie zu verführen.

<<v17>>
17 Als Holofernes sie aufforderte: Trink doch und sei vergnügt mit uns!,

<<v18>>
18 erwiderte Judit: Gern will ich trinken, Herr, denn ich habe in meinem
ganzen Leben noch keine solche Ehre erfahren wie heute.

<<v19>>
19 Sie griff zu, aß und trank vor seinen Augen, was ihre Dienerin
zubereitet hatte.

<<v20>>
20 Holofernes wurde ihretwegen immer fröhlicher und trank so viel Wein,
wie er noch nie zuvor in seinem Leben an einem einzigen Tag getrunken
hatte.\\
\\

* Footnotes

[fn:1] [[file:Dan_1.org::v8][Dan 1,8]]
