#+TITLE: Jdt 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 21:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Jdt 5.html

<<verses>>

<<v1>>
* Der Kriegsrat bei Holofernes: 5,1-4

1 Holofernes, dem Oberbefehlshaber des assyrischen Heeres, wurde
gemeldet, dass die Israeliten sich zum Krieg gerüstet, die Gebirgspässe
gesperrt, alle hohen Bergkuppen befestigt und in der Ebene Hindernisse
angelegt hatten.

<<v2>>
2 Da entbrannte sein Zorn. Er berief alle Fürsten von Moab, die
Heerführer von Ammon und alle Statthalter der Küstengebiete zu sich

<<v3>>
3 und sagte zu ihnen: Sagt mir, ihr Söhne Kanaans, was ist das für ein
Volk, das da im Bergland haust? Wie heißen die Städte, die es bewohnt?
Wie groß ist die Streitmacht dieser Leute und worin liegt ihre Kraft und
Stärke? Wer gebietet über sie als König und Anführer ihres Heeres?

<<v4>>
4 Und warum haben sie allein von allen Bewohnern des Westens es
abgelehnt, mir zu huldigen?\\
\\

<<v5>>
* Die Rede des Ammoniters Achior: 5,5-21

5 Da antwortete ihm Achior, der Anführer aller Ammoniter: Möge mein Herr
anhören, was sein Knecht ihm zu sagen hat. Ich will dir die Wahrheit
sagen über dieses Volk, das in dem Bergland hier in deiner Nähe wohnt;
kein falsches Wort soll aus dem Mund deines Knechtes kommen.

<<v6>>
6 Diese Leute stammen von den Chaldäern ab. [fn:1]

<<v7>>
7 Sie hatten sich zuerst in Mesopotamien niedergelassen, weil sie den
Göttern ihrer Väter im Land der Chaldäer nicht mehr dienen wollten.

<<v8>>
8 Sie waren nämlich von dem Glauben ihrer Vorfahren abgewichen und
hatten ihre Verehrung dem Gott des Himmels zugewandt, zu dessen
Erkenntnis sie gelangt waren. Deshalb hatten die Chaldäer sie aus dem
Bereich ihrer Götter vertrieben und sie waren nach Mesopotamien
geflohen, wo sie sich einige Zeit aufhielten.

<<v9>>
9 Doch ihr Gott gebot ihnen, ihren Wohnsitz zu verlassen und in das Land
Kanaan weiterzuziehen. Hier ließen sie sich nieder und wurden reich an
Gold, Silber und an riesigen Herden. [fn:2]

<<v10>>
10 Weil aber eine Hungersnot über das Land Kanaan hereinbrach, zogen sie
nach Ägypten und blieben dort, solange sie Nahrung fanden. Dort wuchsen
sie zu einer gewaltigen Menge heran und ihr Volk war nicht mehr zu
zählen. [fn:3]

<<v11>>
11 Da schritt der König von Ägypten gegen sie ein. Arglistig befahl er
ihnen, in mühseliger Arbeit Ziegel herzustellen. Man unterdrückte sie
und machte sie zu Sklaven. [fn:4]

<<v12>>
12 Sie aber schrien zu ihrem Gott und dieser schlug das ganze Land
Ägypten mit Plagen, gegen die es keine Abhilfe gab. Darauf jagten die
Ägypter sie aus ihrem Land fort. [fn:5]

<<v13>>
13 Gott aber trocknete das Rote Meer vor ihnen aus. [fn:6]

<<v14>>
14 Er führte sie den Weg zum Sinai und nach Kadesch-Barnea und sie
vertrieben alle Bewohner der Wüste. [fn:7]

<<v15>>
15 Dann ließen sie sich im Land der Amoriter nieder und vernichteten mit
ihrem Heer alle Einwohner von Heschbon. Danach überschritten sie den
Jordan, nahmen das ganze Bergland in Besitz, [fn:8]

<<v16>>
16 verjagten die Kanaaniter, die Perisiter, Jebusiter, Sichemiter und
alle Girgaschiter und ließen sich dort für lange Zeit nieder. [fn:9]

<<v17>>
17 Solange sie sich nicht gegen ihren Gott versündigten, blieb das Glück
ihnen treu; denn ihnen steht ein Gott bei, der das Unrecht hasst.

<<v18>>
18 Als sie aber von dem Weg abwichen, den er ihnen gewiesen hatte,
wurden sie in vielen Kriegen mehr und mehr aufgerieben und schließlich
als Gefangene in ein fremdes Land verschleppt. Der Tempel ihres Gottes
wurde dem Erdboden gleichgemacht und ihre Städte fielen ihren Feinden in
die Hand. [fn:10]

<<v19>>
19 Jetzt aber haben sie sich wieder ihrem Gott zugewandt und sind aus
den Ländern heimgekehrt, in die sie verstreut worden waren. Sie haben
Jerusalem, wo ihr Heiligtum steht, wieder in Besitz genommen und das
verlassene Bergland von neuem besiedelt.

<<v20>>
20 Wenn nun, mein Herr und Gebieter, auf diesem Volk eine Schuld lastet
und sie sich gegen ihren Gott versündigt haben und wenn wir uns
vergewissert haben, dass dieser Anlass zum Unheil bei ihnen vorliegt,
dann können wir hinaufziehen und sie vernichtend schlagen.

<<v21>>
21 Wenn aber ihr Volk sich nichts zu Schulden kommen ließ, dann möge
mein Herr nur ja davon Abstand nehmen. Sonst würde ihnen nämlich ihr
Herr und Gott Hilfe leisten und wir müssten uns dann vor aller Welt
schämen.\\
\\

<<v22>>
* Die feindliche Reaktion des Heeres: 5,22-24

22 Diese Rede des Achior rief bei allen Soldaten, die im Umkreis des
Zeltes standen, Empörung hervor. Die Offiziere des Holofernes sowie alle
Bewohner der Küstengebiete und von Moab forderten, man solle ihn
niederhauen.

<<v23>>
23 Sie sagten: Wir haben doch keine Angst vor den Israeliten. Sie sind
doch ein Volk, das weder die Macht noch die Kraft hat für einen harten
Feldzug.

<<v24>>
24 Darum, Gebieter Holofernes, wollen wir hinaufziehen; sie sollen
deinem ganzen Heer zum Fraß dienen.\\
\\

* Footnotes

[fn:1] [[file:Gen_11.org::v28][Gen 11,28]].[[file:Gen_11.org::v31][31]]

[fn:2] [[file:Gen_12.org::v1][Gen 12,1]]

[fn:3] [[file:Gen_45.org::v5][Gen 46,5]]-[[file:Gen_45.org::v7][7]]; [[file:Ex_1.org::v7][Ex 1,7]]

[fn:4] [[file:Ex_1.org::v11][Ex 1,11]]-[[file:Ex_1.org::v14][14]]

[fn:5] [[file:Ex_5.org::v4][Ex 5,4]]-[[file:Ex_5.org::v19][19]]; [[file:Ex_7.org][7]] - [[file:Ex_12.org][12]]

[fn:6] [[file:Ex_14.org][Ex 14]]

[fn:7] [[file:Dtn_1.org::v2][Dtn 1,2]]

[fn:8] [[file:Num_21.org::v21][Num 21,21]]-[[file:Num_21.org::v31][31]]

[fn:9] [[file:Jos_11.org::v1][Jos 11,1]]-[[file:Jos_11.org::v12][12]]

[fn:10] [[file:Ri_2.org::v11][Ri 2,11]]-[[file:Ri_2.org::v15][15]]; [[file:2.Kön_17.org::v6][2 Kön 17,6]]-[[file:2.Kön_17.org::v23][23]]; [[file:2.Kön_25.org::v1][25,1]]-[[file:2.Kön_25.org::v21][21]]
