#+TITLE: Jdt 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 22:02]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Jdt 15.html

<<verses>>

<<v1>>
* Die Flucht der Assyrer: 15,1-7

1 Als die Männer in den Zelten hörten, was geschehen war, packte sie das
Entsetzen.

<<v2>>
2 Furcht und Schrecken überfiel sie und keiner wollte mehr bei dem
andern bleiben. Sie stoben auseinander und liefen auf allen Wegen in der
Ebene und im Gebirge davon.

<<v3>>
3 Auch die, die auf den Berghöhen rings um Betulia ihr Lager hatten,
wandten sich zur Flucht. Nun aber machten sich die wehrfähigen
Israeliten über sie her.

<<v4>>
4 Usija schickte Boten nach Betomestajim, Bebai, Choba und Kola sowie in
das ganze übrige Land Israel. Sie berichteten, was sich zugetragen
hatte, und forderten die Bevölkerung auf, sich ebenfalls auf die Feinde
zu stürzen und sie zu vernichten.

<<v5>>
5 Sobald die Israeliten das hörten, fielen sie einmütig über die Feinde
her, verfolgten sie bis nach Choba und schlugen sie nieder. Auch die
Bewohner Jerusalems und des ganzen Berglandes fanden sich ein; denn man
hatte ihnen gemeldet, was mit dem Heer ihrer Feinde geschehen war. Die
Bewohner von Gilead und Galiläa fielen den Assyrern in die Flanke. Sie
fügten ihnen schwere Verluste zu, bis sie über das Gebiet von Damaskus
hinaus waren.

<<v6>>
6 Die zurückgebliebenen Einwohner von Betulia machten sich über das
Lager der Assyrer her, plünderten es und verschafften sich großen
Reichtum.

<<v7>>
7 Was übrig blieb, nahmen die Israeliten an sich, als sie von der
Verfolgung zurückkehrten. Auch die Dörfer und Gehöfte im Bergland und in
der Ebene machten große Beute; denn es gab davon eine unermessliche
Menge.\\
\\

<<v8>>
* Der Jubel über Judit: 15,8-14

8 Der Hohepriester Jojakim und der Ältestenrat von Israel, die in
Jerusalem wohnten, kamen herbei, um die rettende Tat zu sehen, die der
Herr für Israel getan hatte, aber auch um Judit aufzusuchen und sie zu
beglückwünschen.

<<v9>>
9 Sie traten bei ihr ein, lobten sie wie aus einem Mund und sagten zu
ihr: Du bist der Ruhm Jerusalems, du bist die große Freude Israels und
der Stolz unseres Volkes.

<<v10>>
10 Mit deiner Hand hast du das alles getan, du hast segensreiche Taten
für Israel vollbracht und Gott hat daran Gefallen gehabt. Sei gesegnet
vom Herrn, dem Allmächtigen, für ewige Zeiten. Und alles Volk rief:
Amen.

<<v11>>
11 Dreißig Tage lang plünderte die Menge das feindliche Lager. Man
schenkte Judit das Zelt des Holofernes, alle seine silbernen Geräte, die
Ruhebetten, die Gefäße und alle übrigen Einrichtungsgegenstände. Sie
nahm ihren Anteil an der Beute und packte ihn auf ihr Maultier; auch
ihre Wagen ließ sie anspannen und verstaute die Beute darauf.

<<v12>>
12 Alle Frauen in Israel eilten herbei, um Judit zu sehen, und sangen
ihr Lob. Als sie sich ihr zu Ehren zu einem Festreigen aufstellten, nahm
Judit belaubte Zweige in die Hand und gab auch den umstehenden Frauen
davon.

<<v13>>
13 Sie und ihre Begleiterinnen setzten sich Kränze von Ölzweigen auf,
und so ging sie vor dem ganzen Volk her und führte den Festreigen der
Frauen an. Ihr folgten alle Männer von Israel in Waffen und mit Kränzen
geschmückt. Von allen Lippen ertönten Loblieder.

<<v14>>
14 Judit aber stimmte im Beisein von ganz Israel das folgende Danklied
an und alles Volk sang den Lobpreis mit, im Wechsel mit ihr.\\
\\
