#+TITLE: Jdt 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 21:34]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jdt 4.html

<<verses>>

<<v1>>
* Das Gottesvolk in großer Bedrängnis: 4,1 - 7,32

* Die Gefahr: 4,1-3

1 Die Israeliten, die in Judäa wohnten, hörten von allem, was
Holofernes, der oberste Feldherr des Assyrerkönigs Nebukadnezzar, den
Völkern angetan und wie er alle ihre Heiligtümer geplündert und
vernichtet hatte.

<<v2>>
2 Da befiel sie Furcht und Schrecken vor ihm und sie hatten Angst um
Jerusalem und den Tempel des Herrn, ihres Gottes.

<<v3>>
3 Denn sie waren noch nicht lange aus der Gefangenschaft heimgekehrt;
erst kürzlich hatte sich das ganze Volk von Judäa wieder gesammelt und
waren die heiligen Geräte, der Altar und der Tempel nach der Entweihung
neu geweiht worden.\\
\\

<<v4>>
* Die Vorbereitung des Widerstandes: 4,4-8

4 Sie schickten Boten in das ganze Gebiet von Samarien und Kona, nach
Bet-Horon, Abel-Majim und Jericho sowie nach Choba, Hazor und in das Tal
von Salim.

<<v5>>
5 Sie besetzten alle hohen Bergkuppen, befestigten die Ortschaften und
versahen sie mit Lebensmitteln für den Krieg, denn ihre Felder waren
eben abgeerntet worden.

<<v6>>
6 Jojakim, der zu jener Zeit Hoherpriester in Jerusalem war, schrieb an
die Einwohner von Betulia und Betomestajim, das Jesreel gegenüber vor
der Ebene nahe bei Dotan liegt,

<<v7>>
7 sie sollten die Gebirgspässe besetzt halten. Durch sie konnte man nach
Judäa vordringen. Es war aber auch leicht, den Vormarsch der
Heranrückenden dort aufzuhalten; die Gebirgswege waren nämlich so
schmal, dass jeweils nur zwei Mann nebeneinander hindurchgehen konnten.

<<v8>>
8 Die Israeliten taten, was ihnen der Hohepriester Jojakim und die
Ältesten des ganzen Volkes Israel in Jerusalem befohlen hatten.\\
\\

<<v9>>
* Das Flehen zu Gott um Rettung: 4,9-15

9 Alle Männer Israels aber flehten Gott inständig an und taten Buße
unter strengem Fasten.

<<v10>>
10 Sie selbst, ihre Frauen, ihre Kinder und ihr Vieh, aber auch alle
Fremden, die bei ihnen wohnten, die Tagelöhner und Sklaven, legten
Bußgewänder an. [fn:1]

<<v11>>
11 Alle Israeliten in Jerusalem, ihre Frauen und Kinder warfen sich vor
dem Tempel nieder, streuten sich vor dem Herrn Asche auf das Haupt und
legten Bußgewänder an.

<<v12>>
12 Selbst den Altar umhüllten sie mit einem Bußgewand. Sie schrien alle
einmütig in stürmischen Gebeten zu dem Gott Israels, er möge doch nicht
zulassen, dass man ihre Kinder raube, ihre Frauen als Beute verteile,
die Städte ihres Erbbesitzes zerstöre und das Heiligtum entweihe und
verwüste, zum Gespött für die Heiden.

<<v13>>
13 Und der Herr hörte ihr Rufen und sah auf ihre Not. Das Volk fastete
mehrere Tage lang in ganz Judäa und in Jerusalem vor dem Heiligtum des
Herrn, des Allmächtigen.

<<v14>>
14 Auch der Hohepriester Jojakim mit der ganzen Priesterschaft im Tempel
und den Dienern des Herrn legten Bußgewänder an; so brachten sie das
tägliche Brandopfer dar und dazu die gelobten und die freiwilligen
Opfergaben des Volkes.

<<v15>>
15 Auf ihren Kopfbund hatten sie Asche gestreut und sie riefen mit aller
Macht zum Herrn, er möge doch gnädig auf das ganze Haus Israel
herabschauen.\\
\\

* Footnotes

[fn:1] (10f) [[file:Jona_3.org::v7][Jona 3,7f]]
