#+TITLE: Jdt 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 21:30]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jdt 1.html

* Jdt 1

Das Buch Judit schildert am Beispiel der Bedrohung Israels durch die
Macht eines Königs Nebukadnezzar die Gefährdung des Gottesvolkes durch
das entartete und gottfeindliche Heidentum aller Zeiten (Kap. 1 - 3). An
der durch den Druck der heidnischen Weltmacht hervorgerufenen
Glaubenskrise bei den Einwohnern von Betulia (Kap. 4 - 7) und ihrer
Überwindung durch die fromme Witwe Judit (Kap. 8 - 16) wird jedoch
deutlich, wie sich das Gottesvolk verhalten muss, wenn es in der
Bedrängnis die Hilfe Gottes erfahren will. Vorbedingung für das rettende
Eingreifen Gottes ist die Umkehr Israels zu seinem göttlichen Herrn und
das Vertrauen auf die im göttlichen Heilsplan beschlossene Offenbarung
seiner universalen Königsherrschaft. Judit, die als gesetzestreue und
gottergebene Frau diese Vorbedingung erfüllt und zur Befreiung Betulias
mutig ihr Leben einsetzt, erfährt beispielhaft für ihr Volk die rettende
Hilfe Gottes.\\
\\
Das Buch will nicht von einem bestimmten geschichtlichen Ereignis
berichten, sondern zieht gleichsam die Summe aus den
Auseinandersetzungen zwischen Israel und seinen heidnischen
Widersachern. Man kann deshalb die literarische Art des Buches als
Lehrschrift im Gewand einer Geschichtserzählung bezeichnen. Dem
Verfasser geht es nicht darum, den wirklichen Verlauf der Geschichte
nachzuzeichnen, sondern in freier Darstellung die Mächte und Kräfte
sichtbar zu machen, die den Verlauf der Geschichte bestimmen.\\
\\
Die Bedeutung des Buches besteht darin, dass sowohl die entartete
heidnische Weltmacht als eine übergeschichtliche Wirklichkeit wie auch
die Glaubenshaltung des bedrängten Gottesvolkes in Anfechtung und
Bewährung deutlich vor Augen gestellt werden. Das Hauptgewicht liegt
dabei auf der Darstellung der rettenden Hilfe Gottes, der seine
universale Königsherrschaft nicht erst am Ende der Zeiten, sondern schon
vorher durch das Gericht über seine Feinde und die Feinde seines Volkes
offenbart.\\
\\
Das Buch ist in griechischer Sprache überliefert und wahrscheinlich an
der Wende vom 2. zum 1. Jahrhundert v. Chr. in Palästina verfasst
worden.\\
\\

<<verses>>

<<v1>>
* Die Bedrohung: 1,1 - 3,10

* Der Krieg zwischen Nebukadnezzar und Arphaxad: 1,1-6

1 Es war im zwölften Jahr des Nebukadnezzar, der in der großen Stadt
Ninive als König der Assyrer regierte. Zur gleichen Zeit regierte damals
in Ekbatana Arphaxad als König der Meder. [fn:1]

<<v2>>
2 Arphaxad hatte aus behauenen Steinen von drei Ellen Breite und sechs
Ellen Länge rings um Ekbatana Mauern errichten lassen, die siebzig Ellen
hoch und fünfzig Ellen breit waren.

<<v3>>
3 Die Türme der Mauern hatte er über den Stadttoren hundert Ellen hoch
aufgeführt; ihre Grundfläche war sechzig Ellen breit.

<<v4>>
4 Die Stadttore selber hatte er siebzig Ellen hoch und vierzig Ellen
breit machen lassen, damit die Abteilungen seiner Helden und die
Regimenter seiner Fußtruppen genügend Raum zum Ausrücken hatten.

<<v5>>
5 Zu jener Zeit führte König Nebukadnezzar Krieg gegen König Arphaxad in
der großen Ebene, das heißt in der Ebene im Gebiet von Regu.

<<v6>>
6 Arphaxad schlossen sich alle Bewohner des Berglandes an sowie alle,
die am Eufrat und Tigris, am Hydaspes und im Flachland des
Elamiterkönigs Arjoch wohnten; es waren viele Völker, die zum Aufgebot
der Söhne Chelëuds zusammenströmten.\\
\\

<<v7>>
* Der vergebliche Hilferuf an die Nachbarvölker: 1,7-12

7 Der Assyrerkönig Nebukadnezzar schickte Boten zu allen Bewohnern
Persiens und zu allen, die ihre Wohnsitze im Westen hatten, nämlich zu
den Bewohnern von Zilizien und von Damaskus, zu allen Bewohnern des
Libanon, des Antilibanon und der Küstengebiete,

<<v8>>
8 zu den Völkerschaften am Karmel und in Gilead, zu den Bewohnern des
oberen Galiläa und der großen Ebene Jesreel,

<<v9>>
9 zu allen, die in Samaria und in seinen Städten und jenseits des Jordan
wohnten bis nach Jerusalem, Batane, Chelus, Kadesch und zum Grenzbach
Ägyptens, zu den Bewohnern von Tachpanhes und Ramesse und den Bewohnern
des ganzen Landes Goschen,

<<v10>>
10 ja, über Zoan und Memfis hinaus zu allen Bewohnern Ägyptens bis zu
den Grenzen Äthiopiens.

<<v11>>
11 Doch alle Bewohner der ganzen Erde missachteten den Befehl des
Assyrerkönigs Nebukadnezzar und leisteten ihm keine Heeresfolge, denn
sie hatten keine Angst vor ihm; er war in ihren Augen nicht mehr als ein
gewöhnlicher Mensch. Darum beschimpften sie seine Boten und ließen sie
mit leeren Händen wieder abziehen.

<<v12>>
12 Da entbrannte Nebukadnezzars Zorn über all diese Länder und er schwor
bei seinem Thron und seinem Reich, an dem ganzen Gebiet von Zilizien,
Damaskus und Syrien Rache zu nehmen und alle Bewohner Moabs, die
Ammoniter, ganz Judäa und alle Bewohner Ägyptens bis zum Gebiet der
beiden Meere mit seinem Schwert auszurotten. [fn:2]\\
\\

<<v13>>
* Der Sieg über Arphaxad: 1,13-16

13 Im siebzehnten Jahr seiner Regierung griff er König Arphaxad mit
seinem Heer an und konnte den Kampf für sich entscheiden; das gesamte
Heer des Arphaxad, seine ganze Reiterei und all seine Wagen jagte er in
die Flucht.

<<v14>>
14 Er eroberte seine Städte und drang bis nach Ekbatana vor; er besetzte
die Türme der Stadt, gab ihre Häuser der Plünderung preis und machte so
ihre Pracht zuschanden.

<<v15>>
15 Arphaxad nahm er im Bergland von Regu gefangen, durchbohrte ihn mit
seinen Speeren und setzte seiner Macht für immer ein Ende.

<<v16>>
16 Darauf kehrte er mit seinem ganzen Gefolge, einer fast unübersehbaren
Menge von Soldaten, nach Ninive zurück. Im Hochgefühl seines Erfolges
feierte er dort mit dem Heer ein Freudenfest, das hundertzwanzig Tage
lang dauerte.\\
\\

* Footnotes

[fn:1] Die Angaben stehen im Widerspruch zur Geschichte.
Nebukadnezzar (605-562 v. Chr.) war König von Babylon und nicht König
der Assyrer in Ninive. Schon sein Vater Nabopolassar hatte 612 v. Chr.
Ninive zerstört. Der König von Assur ist seit der mittleren Königszeit
für Israel die Verkörperung einer gottwidrigen heidnischen Weltmacht
(vgl. Jes 10,5-19). Nebukadnezzar hat 586 v. Chr. Jerusalem zerstört und
das Gottesvolk in die Verbannung nach Babylonien geführt (vgl. 2 Kön
25). Daher erscheint der «Assyrerkönig Nebukadnezzar» in Jdt als
übergeschichtlicher Repräsentant des gottwidrigen Heidentums und in
dieser Eigenschaft ist er mit dem neutestamentlichen «Antichristen» zu
vergleichen (vgl. Mk 13,14; 2 Thess 2,4; 1 Joh 2,18; 2 Joh 7; Offb
13,1-10).

[fn:2] ganz Judäa, andere Lesart: ganz Idumäa.
