#+TITLE: Jdt 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 21:52]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Jdt 9.html

<<verses>>

<<v1>>
* Judits Gebet: 9,1-14

1 Judit warf sich auf ihr Gesicht nieder, streute sich Asche auf das
Haupt und öffnete das Bußgewand, das sie trug. Es war gerade die Zeit,
zu der man an jenem Abend in Jerusalem im Haus Gottes das Rauchopfer
darbrachte. Und Judit rief laut zum Herrn; sie sagte: [fn:1]

<<v2>>
2 Herr, du Gott meines Stammvaters Simeon! Du hast ihm das Schwert in
die Hand gegeben zur Bestrafung der Fremden, die den Gürtel der Jungfrau
lösten, um sie zu beflecken, die ihre Schenkel entblößten, um sie zu
schänden, und ihren Schoß entweihten zu ihrer Schande. Du hattest
nämlich geboten: Das darf nicht geschehen. Und dennoch taten sie es. [fn:2] [fn:3]

<<v3>>
3 Deswegen gabst du ihre Fürsten Mördern preis und tauchtest zur
Vergeltung das Lager, das ihrer Arglist gedient hatte, in Blut; du
erschlugst die Knechte samt ihren Herren, ja auch die Herren auf ihren
Thronen.

<<v4>>
4 Du gabst ihre Frauen dem Raub und ihre Töchter der Gefangenschaft
preis und ihren ganzen Besitz gabst du deinen geliebten Söhnen; denn sie
glühten vor Eifer für dich, hatten Abscheu vor der Befleckung ihres
Blutes und riefen zu dir um Hilfe. Gott, mein Gott, erhöre auch mich,
die Witwe!

<<v5>>
5 Du hast bewirkt, was damals war und auch was vorher und später
geschah. Doch auch was jetzt geschieht und noch kommen wird, hast du
erdacht und es ist eingetroffen, was du geplant hast.

<<v6>>
6 Deine Beschlüsse standen da und sagten: Hier sind wir! Denn alle deine
Wege sind schon gebahnt und dein Gericht ist eine beschlossene Sache. [fn:4]

<<v7>>
7 Sieh doch auf die Assyrer! Sie verfügen über ein gewaltiges Heer,
brüsten sich mit ihren Rossen und Reitern, sind stolz auf die
Schlagkraft ihres Fußvolkes, vertrauen auf ihre Schilde und Speere, ihre
Bogen und Schleudern und wollen nicht einsehen, dass du der Herr bist,
der den Kriegen ein Ende setzt. [fn:5]

<<v8>>
8 «Herr» ist dein Name. Brich ihre Stärke mit deiner Macht und vernichte
ihre Kraft in deinem Zorn! Denn sie haben beschlossen, dein Heiligtum zu
entweihen, das Zelt, in dem dein herrlicher Name wohnt, zu beflecken und
die Hörner deines Altars mit dem Schwert abzuschlagen.

<<v9>>
9 Schau dir ihren Übermut an und lass deinen Zorn auf ihr Haupt
herabfahren! Schenke mir, der Witwe, die Kraft zu der Tat, die ich
plane.

<<v10>>
10 Schlag den Knecht wie den Herrn und den Herrn wie den Diener durch
meine listigen Worte; brich ihren Trotz durch die Hand einer Frau!

<<v11>>
11 Denn deine Macht stützt sich nicht auf die große Zahl, deine
Herrschaft braucht keine starken Männer, sondern du bist der Gott der
Schwachen und der Helfer der Geringen; du bist der Beistand der Armen,
der Beschützer der Verachteten und der Retter der Hoffnungslosen.

<<v12>>
12 Ja, du Gott meines Vaters und Gott deines Erbbesitzes Israel, du Herr
des Himmels und der Erde, Schöpfer der Meere und König deiner ganzen
Schöpfung, erhöre mein Gebet!

<<v13>>
13 Lass meine listigen Worte Wunden und Striemen schlagen bei denen, die
gegen deinen Bund und dein heiliges Haus, gegen den Berg Zion und den
Wohnsitz deiner Söhne Böses beschlossen haben.

<<v14>>
14 Lass dein ganzes Volk und alle Stämme erkennen und wissen, dass du
der wahre Gott bist, der Gott aller Macht und Stärke, und dass es für
dein Volk Israel keinen anderen Beschützer gibt als dich allein. [fn:6]\\
\\

* Footnotes

[fn:1] [[file:Ex_30.org::v8][Ex 30,8]]

[fn:2] [[file:Gen_34.org::v25][Gen 34,25f]]

[fn:3] Judit beruft sich auf das Strafgericht, das ihr
Stammvater Simeon zusammen mit seinem Bruder Levi an Sichem vollstreckt
hat (vgl. Gen 34).

[fn:4] [[file:Ps_33.org::v9][Ps 33,9]]

[fn:5] [[file:Ps_46.org::v10][Ps 46,10]]; [[file:Ps_83.org::v19][83,19]]

[fn:6] [[file:Jes_37.org::v20][Jes 37,20]]
