:PROPERTIES:
:ID:       ffc0bc92-0252-4bef-b3f4-bd157b18e8f7
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_11.html][11]] [[file:Jer_12.html][12]] *13*
[[file:Jer_14.html][14]] [[file:Jer_15.html][15]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 13
  :PROPERTIES:
  :CUSTOM_ID: jer-13
  :END:

<<verses>>

<<v1>>
**** Gottes Strafe im Gleichnis: 13,1-14
     :PROPERTIES:
     :CUSTOM_ID: gottes-strafe-im-gleichnis-131-14
     :END:
1 So hat der Herr zu mir gesagt: Geh, kauf dir einen leinenen Gürtel,
und leg ihn dir um die Hüften, aber tauch ihn nicht ins Wasser!

<<v2>>
2 Da kaufte ich, wie der Herr mir aufgetragen hatte, den Gürtel und
legte ihn mir um die Hüften.

<<v3>>
3 Nun erging das Wort des Herrn zum zweiten Mal an mich; er sagte:

<<v4>>
4 Nimm den gekauften Gürtel, den du um die Hüften trägst, mach dich auf
den Weg an den Eufrat und verbirg ihn dort in einer Felsspalte!

<<v5>>
5 Ich ging hin und verbarg ihn am Eufrat, wie mir der Herr befohlen
hatte.

<<v6>>
6 Nach längerer Zeit sprach der Herr zu mir: Mach dich auf den Weg an
den Eufrat und hol den Gürtel zurück, den du dort auf meinen Befehl hin
verborgen hast.

<<v7>>
7 Da ging ich zum Eufrat, suchte den Gürtel und holte ihn von der
Stelle, wo ich ihn verborgen hatte. Doch der Gürtel war verdorben, zu
nichts mehr zu gebrauchen.

<<v8>>
8 Nun erging das Wort des Herrn an mich:

<<v9>>
9 So spricht der Herr: Ebenso verderbe ich die stolze Pracht Judas und
Jerusalems, wie groß sie auch sei.

<<v10>>
10 Dieses böse Volk weigert sich, auf meine Worte zu hören, es folgt dem
Trieb seines Herzens und läuft anderen Göttern nach, um ihnen zu dienen
und sie anzubeten; es soll daher wie dieser Gürtel werden, der zu nichts
mehr zu gebrauchen ist. ^{[[#fn1][1]]}

<<v11>>
11 Denn wie sich der Gürtel den Hüften des Mannes anschmiegt, so wollte
ich, dass sich das ganze Haus Juda mir anschmiegte - Spruch des Herrn -,
damit es mein Volk und mein Ruhm, mein Preis und mein Schmuck wäre. Sie
aber haben nicht gehorcht.

<<v12>>
12 Du sollst ihnen das folgende Wort ausrichten: So spricht der Herr,
der Gott Israels: Jeden Krug kann man mit Wein füllen. Wenn sie dir
darauf erwidern: Wissen wir nicht selbst, dass man jeden Krug mit Wein
füllen kann?,

<<v13>>
13 dann sollst du ihnen antworten: So spricht der Herr: Seht, ich fülle
alle Bewohner dieses Landes mit Trunkenheit, die Könige, die auf Davids
Thron sitzen, die Priester, die Propheten und alle Einwohner Jerusalems.
^{[[#fn2][2]]}

<<v14>>
14 Ich zerschmettere sie, den einen am andern, Väter und Söhne
zugleich - Spruch des Herrn. Keine Schonung, kein Mitleid und kein
Erbarmen hält mich ab, sie zu vernichten.\\
\\

<<v15>>
**** Die Warnung vor Hochmut: 13,15-17
     :PROPERTIES:
     :CUSTOM_ID: die-warnung-vor-hochmut-1315-17
     :END:
15 Hört und merkt auf! /\\
 Seid nicht hochmütig; denn der Herr redet.\\
\\

<<v16>>
16 Erweist dem Herrn, eurem Gott, die Ehre, /\\
 bevor es dunkel wird, /\\
 bevor eure Füße straucheln auf dämmrigen Bergen. Wartet ihr dann auf
das Licht - /\\
 er verwandelt es in Finsternis /\\
 und macht es zur Dunkelheit.\\
\\

<<v17>>
17 Wenn ihr aber darauf nicht hört, /\\
 so muss ich im Verborgenen weinen über den Hochmut und mein Auge muss
ohne Unterlass Tränen vergießen, /\\
 da die Herde des Herrn weggeführt wird. ^{[[#fn3][3]]}\\
\\

<<v18>>
**** Die drohende Wegführung: 13,18-19
     :PROPERTIES:
     :CUSTOM_ID: die-drohende-wegführung-1318-19
     :END:
18 Sag zum König und zur Herrin: /\\
 Setzt euch tief hinunter; denn eure prächtige Krone /\\
 sinkt euch vom Haupt. ^{[[#fn4][4]]}\\
\\

<<v19>>
19 Die Städte im Negeb sind verschlossen /\\
 und niemand kann sie öffnen. /\\
 Weggeführt wird ganz Juda, vollständig weggeführt.\\
\\

<<v20>>
**** Die Schändung Jerusalems: 13,20-27
     :PROPERTIES:
     :CUSTOM_ID: die-schändung-jerusalems-1320-27
     :END:
20 Blick auf [Jerusalem] /\\
 und schau, wie sie kommen vom Norden! Wo bleibt da die Herde, die dir
anvertraut war, /\\
 deine prächtigen Schafe?\\
\\

<<v21>>
21 Was wirst du sagen, /\\
 wenn man die Freunde, die du selbst an dich gewöhnt hast, /\\
 als Herren über dich setzt? Werden dich nicht Wehen ergreifen /\\
 wie eine gebärende Frau?\\
\\

<<v22>>
22 Und wenn du dich fragst: /\\
 Warum hat mich das alles getroffen?, so wisse: Wegen deiner großen
Schuld wird deine Schleppe aufgehoben /\\
 und dein Leib vergewaltigt. ^{[[#fn5][5]]}\\
\\

<<v23>>
23 Ändert wohl ein Neger seine Hautfarbe /\\
 oder ein Leopard seine Flecken? Dann könntet auch ihr euch noch
bessern, /\\
 die ihr ans Böse gewöhnt seid. ^{[[#fn6][6]]}\\
\\

<<v24>>
24 So aber zerstreue ich euch wie Spreu, /\\
 die verfliegt, wenn der Wüstenwind weht.\\
\\

<<v25>>
25 Das ist dein Los, dein Lohn, /\\
 von mir dir zugemessen - Spruch des Herrn -, weil du mich vergessen /\\
 und dich auf Lügen verlassen hast.\\
\\

<<v26>>
26 Nun hebe auch ich deine Schleppe auf, /\\
 bis über dein Gesicht, /\\
 sodass deine Schande offenbar wird,\\
\\

<<v27>>
27 deine Ehebrüche, dein geiles Wiehern, /\\
 deine schändliche Unzucht. Auf den Hügeln und auf dem Feld /\\
 habe ich deine Gräuel gesehen. Weh dir, Jerusalem, /\\
 weil du dich nicht reinigst - /\\
 wie lange noch? ^{[[#fn7][7]]}\\
\\

^{[[#fnm1][1]]} ℘ 11,8

^{[[#fnm2][2]]} ℘ Jes 51,17

^{[[#fnm3][3]]} ℘ 14,17

^{[[#fnm4][4]]} Gemeint sind König Jojachin und seine Mutter (2 Kön
24,10-17) vor ihrer Gefangennahme 597 v. Chr.

^{[[#fnm5][5]]} ℘ Ez 16,37

^{[[#fnm6][6]]} Neger, wörtlich: Kuschiter. - Kusch entspricht dem
heutigen Sudan und Teilen Äthiopiens.

^{[[#fnm7][7]]} ℘ 5,8
