:PROPERTIES:
:ID:       398db578-488a-47e4-8120-f8a503d4309d
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_41.html][41]] [[file:Jer_42.html][42]] *43*
[[file:Jer_44.html][44]] [[file:Jer_45.html][45]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 43
  :PROPERTIES:
  :CUSTOM_ID: jer-43
  :END:

<<verses>>

<<v1>>
**** Der Zug nach Ägypten: 43,1-7
     :PROPERTIES:
     :CUSTOM_ID: der-zug-nach-ägypten-431-7
     :END:
1 Als Jeremia dem ganzen Volk alle Worte des Herrn, ihres Gottes,
vollständig mitgeteilt hatte, nämlich all die Worte, mit denen ihn der
Herr zu ihnen gesandt hatte,

<<v2>>
2 da sagten Asarja, der Sohn Hoschajas, und Johanan, der Sohn Kareachs,
sowie alle übermütigen Männer zu Jeremia: Was du sagst, ist erlogen.
Nicht der Herr, unser Gott, hat dich gesandt mit dem Auftrag: Ihr sollt
nicht nach Ägypten ziehen, um euch dort niederzulassen.

<<v3>>
3 Vielmehr hetzt dich Baruch, der Sohn Nerijas, gegen uns auf, um uns
den Chaldäern auszuliefern, sodass sie uns töten oder nach Babel
verschleppen.

<<v4>>
4 Johanan, der Sohn Kareachs, alle Truppenführer und das ganze Volk
hörten also nicht auf die Stimme des Herrn, im Land Juda zu bleiben.

<<v5>>
5 Johanan, der Sohn Kareachs, und alle Truppenführer nahmen den ganzen
Rest Judas, der aus allen Völkern, unter die er versprengt gewesen,
zurückgekehrt war, um sich im Land Juda niederzulassen:

<<v6>>
6 Männer, Frauen und Kinder, die Prinzessinnen und alle Leute, die
Nebusaradan, der Kommandant der Leibwache, bei Gedalja, dem Sohn
Ahikams, des Sohnes Schafans, gelassen hatte, auch den Propheten Jeremia
und Baruch, den Sohn Nerijas,

<<v7>>
7 und sie zogen nach Ägypten, weil sie nicht auf die Stimme des Herrn
hörten, und kamen bis Tachpanhes.\\
\\

<<v8>>
**** Die Heimsuchung auch in Ägypten: 43,8-13
     :PROPERTIES:
     :CUSTOM_ID: die-heimsuchung-auch-in-ägypten-438-13
     :END:
8 In Tachpanhes erging das Wort des Herrn an Jeremia:

<<v9>>
9 Nimm vor den Augen judäischer Männer große Steine in die Hand und
maure sie mit Mörtel in das Ziegelpflaster am Eingang zum Haus des
Pharao in Tachpanhes!

<<v10>>
10 Dann sag zu ihnen: So spricht der Herr der Heere, der Gott Israels:
Seht, ich werde meinen Knecht Nebukadnezzar, den König von Babel,
herbeiholen; er wird seinen Thron über diesen Steinen, die ich hier
eingemauert habe, aufstellen und sein Prunkzelt darüber ausspannen.

<<v11>>
11 Er wird kommen und das Land Ägypten schlagen; wer für den Tod
bestimmt ist, verfällt dem Tod, wer für die Gefangenschaft, der
Gefangenschaft und wer für das Schwert, dem Schwert. ^{[[#fn1][1]]}

<<v12>>
12 Er wird an die Tempel der Götter Ägyptens Feuer legen und die Götter
verbrennen oder wegführen. Er wird das Land Ägypten ablausen, wie ein
Hirt sein Gewand ablaust; danach wird er unbehelligt abziehen.

<<v13>>
13 Er wird die spitzen Säulen des Sonnentempels in Ägypten zertrümmern
und die Tempel der Götter Ägyptens in Brand stecken.\\
\\

^{[[#fnm1][1]]} ℘ 46,26; 15,2
