:PROPERTIES:
:ID:       b91fa8ba-cfd6-4d2a-aac9-d39564a34e3a
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_10.html][10]] [[file:Jer_11.html][11]] *12*
[[file:Jer_13.html][13]] [[file:Jer_14.html][14]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 12
  :PROPERTIES:
  :CUSTOM_ID: jer-12
  :END:

<<verses>>

<<v1>>
**** Der Prophet in seelischer Not: 12,1-6
     :PROPERTIES:
     :CUSTOM_ID: der-prophet-in-seelischer-not-121-6
     :END:
1 Du bleibst im Recht, Herr, wenn ich mit dir streite; /\\
 dennoch muss ich mit dir rechten. Warum haben die Frevler Erfolg, /\\
 weshalb können alle Abtrünnigen sorglos sein? ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Du hast sie eingepflanzt und sie schlagen Wurzel, /\\
 sie wachsen heran und bringen auch Frucht. Nur ihrem Mund bist du nah,
/\\
 ihrem Herzen aber fern.\\
\\

<<v3>>
3 Du jedoch, Herr, kennst und durchschaust mich; /\\
 du hast mein Herz erprobt /\\
 und weißt, dass es an dir hängt. Raff sie weg wie Schafe zum
Schlachten, /\\
 sondere sie aus für den Tag des Mordens!\\
\\

<<v4>>
4 Wie lange noch soll das Land vertrocknen, /\\
 das Grün auf allen Feldern verdorren? Weil seine Bewohner Böses tun,
/\\
 schwinden Vieh und Vögel dahin. /\\
 Denn sie denken: Er sieht unsre Zukunft nicht. - ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Wenn schon der Wettlauf mit Fußgängern dich ermüdet, /\\
 wie willst du mit Pferden um die Wette laufen? Wenn du nur im
friedlichen Land dich sicher fühlst, /\\
 wie wirst du dich verhalten im Dickicht des Jordan? ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Selbst deine Brüder und das Haus deines Vaters handeln treulos an dir;
/\\
 auch sie schreien laut hinter dir her. Trau ihnen nicht, /\\
 selbst wenn sie freundlich mit dir reden. ^{[[#fn4][4]]}\\
\\

<<v7>>
**** Die Klage Gottes über sein Land: 12,7-13
     :PROPERTIES:
     :CUSTOM_ID: die-klage-gottes-über-sein-land-127-13
     :END:
7 Ich verlasse mein Haus, /\\
 ich verstoße mein Erbteil. Meinen Herzensliebling gebe ich preis /\\
 in die Hand seiner Feinde.\\
\\

<<v8>>
8 Mein Erbteil wandte sich gegen mich /\\
 wie ein Löwe im Wald. Es erhob gegen mich seine Stimme; /\\
 deshalb bin ich ihm Feind.\\
\\

<<v9>>
9 Ist mir mein Erbteil zur Höhle einer Hyäne geworden, /\\
 dass Raubvögel es umlagern? Auf, sammelt euch, alle Tiere des Feldes,
/\\
 kommt zum Fraß! ^{[[#fn5][5]]}\\
\\

<<v10>>
10 Hirten in großer Zahl /\\
 haben meinen Weinberg verwüstet, mein Feld zertreten, /\\
 mein prächtiges Feld zur öden Wüste gemacht.\\
\\

<<v11>>
11 Man hat es in dürres Ödland verwandelt, /\\
 verwüstet liegt es vor mir. Das ganze Land ist verödet, /\\
 doch keiner nimmt sich das zu Herzen.\\
\\

<<v12>>
12 Über alle Hügel der Steppe drangen Verderber ein; /\\
 denn das Schwert des Herrn frisst von einem Ende des Landes zum andern.
/\\
 Kein Mensch bleibt unversehrt.\\
\\

<<v13>>
13 Sie haben Weizen gesät und Dornen geerntet, /\\
 sie haben sich abgemüht, doch ohne Ertrag. Enttäuscht sind sie von
ihrer Ernte; /\\
 (sie ist vernichtet) durch den glühenden Zorn des Herrn.\\
\\

<<v14>>
**** Gericht oder Heil für die Nachbarn: 12,14-17
     :PROPERTIES:
     :CUSTOM_ID: gericht-oder-heil-für-die-nachbarn-1214-17
     :END:
14 So spricht der Herr: Alle meine bösen Nachbarn, die das Erbteil
antasten, das ich meinem Volk Israel zum Erbe gegeben habe, fürwahr, ich
reiße sie von ihrem Boden weg; doch auch das Haus Juda reiße ich aus
ihrer Mitte.

<<v15>>
15 Aber nachdem ich sie weggerissen habe, will ich mich ihrer wieder
erbarmen und sie zurückbringen, einen jeden in sein Erbteil und in seine
Heimat.

<<v16>>
16 Lernen sie dann die rechte Lebensweise meines Volkes, sodass sie bei
meinem Namen schwören: So wahr der Herr lebt!, wie sie vorher mein Volk
gelehrt hatten, beim Baal zu schwören, dann sollen sie inmitten meines
Volkes wiederhergestellt werden. ^{[[#fn6][6]]}

<<v17>>
17 Gehorchen sie jedoch nicht, so werde ich dieses Volk völlig ausreißen
und vernichten - Spruch des Herrn.\\
\\

^{[[#fnm1][1]]} ℘ Ps 73,3-12; Ijob 21,7-13

^{[[#fnm2][2]]} 4e: G: Gott sieht unsere Pfade nicht.

^{[[#fnm3][3]]} Die Antwort Gottes hält dem Propheten in zwei
Vergleichen vor, dass er schon kleinen Schwierigkeiten nicht gewachsen
ist; er muss auf noch größere gefasst sein.

^{[[#fnm4][4]]} ℘ 9,3

^{[[#fnm5][5]]} ℘ Jes 56,9

^{[[#fnm6][6]]} ℘ 4,2
