:PROPERTIES:
:ID:       83d153ad-ea95-4493-9d3a-fdde0d757e9d
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_32.html][32]] [[file:Jer_33.html][33]] *34*
[[file:Jer_35.html][35]] [[file:Jer_36.html][36]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 34
  :PROPERTIES:
  :CUSTOM_ID: jer-34
  :END:

<<verses>>

<<v1>>
**** Zidkijas Ende: 34,1-7
     :PROPERTIES:
     :CUSTOM_ID: zidkijas-ende-341-7
     :END:
1 Das Wort, das vom Herrn an Jeremia erging, als Nebukadnezzar, der
König von Babel, und sein ganzes Heer, alle Königreiche seines
Herrschaftsgebietes und alle Völkerschaften gegen Jerusalem und alle
seine umliegenden Städte Krieg führten:

<<v2>>
2 So spricht der Herr, der Gott Israels: Mach dich auf, rede mit
Zidkija, dem König von Juda, und sag zu ihm: So spricht der Herr: Ich
gebe diese Stadt in die Hand des Königs von Babel und er wird sie
niederbrennen. ^{[[#fn1][1]]}

<<v3>>
3 Auch du wirst seiner Hand nicht entrinnen, sondern ergriffen und in
seine Hand gegeben werden. Auge in Auge wirst du den König von Babel
sehen und von Mund zu Mund wird er mit dir reden und nach Babel wirst du
kommen.

<<v4>>
4 Doch höre das Wort des Herrn, Zidkija, König von Juda! So spricht der
Herr über dich: Du brauchst nicht durch das Schwert zu sterben.

<<v5>>
5 In Frieden kannst du sterben, und wie deinen Vätern und Vorgängern,
den früheren Königen, so wird man auch dir zu Ehren Totenfeuer anzünden
und dir die Totenklage halten: «Ach, der Herrscher!» Ich bin es, der
dieses Wort gesprochen hat - Spruch des Herrn. ^{[[#fn2][2]]}

<<v6>>
6 Der Prophet Jeremia sagte alle diese Worte zu Zidkija, dem König von
Juda, in Jerusalem,

<<v7>>
7 als das Heer des Königs von Babel bereits gegen Jerusalem und die
übrig gebliebenen Städte Judas, nämlich Lachisch und Aseka, kämpfte;
denn nur diese befestigten Städte waren in Juda noch übrig geblieben.\\
\\

<<v8>>
**** Der Widerruf der Sklavenfreilassung: 34,8-22
     :PROPERTIES:
     :CUSTOM_ID: der-widerruf-der-sklavenfreilassung-348-22
     :END:
8 Das Wort, das vom Herrn an Jeremia erging, als König Zidkija mit dem
ganzen Volk in Jerusalem das Abkommen getroffen hatte, eine Freilassung
auszurufen.

<<v9>>
9 Es sollte nämlich jeder seinen hebräischen Sklaven und seine
hebräische Sklavin freilassen und keiner sollte mehr seinen hebräischen
Stammesbruder als Sklaven halten.

<<v10>>
10 Dem hatten sich alle Großen gefügt, ebenso das ganze Volk, das dem
Abkommen beigetreten war, dass jeder seinen Sklaven oder seine Sklavin
freilassen und nicht mehr als Sklave halten werde. Sie hatten gehorcht
und die Sklaven freigelassen.

<<v11>>
11 Danach aber holten sie die Sklaven und Sklavinnen, die sie
freigelassen hatten, zurück und machten sie mit Gewalt wieder zu Sklaven
und Sklavinnen.

<<v12>>
12 Da erging das Wort des Herrn an Jeremia:

<<v13>>
13 So spricht der Herr, der Gott Israels: Ich habe mit euren Vätern, als
ich sie aus Ägypten, dem Sklavenhaus, herausführte, ein Abkommen
getroffen und verlangt:

<<v14>>
14 Alle sieben Jahre soll jeder von euch seinen hebräischen
Stammesbruder, der sich ihm verkauft hat, freilassen; sechs Jahre soll
er dein Sklave sein, dann sollst du ihn freilassen. Aber eure Väter
haben mir nicht gehorcht und mir ihr Ohr nicht zugeneigt. ^{[[#fn3][3]]}

<<v15>>
15 Da seid ihr jetzt umgekehrt und habt das getan, was in meinen Augen
recht ist, indem jeder für seinen Nächsten die Freilassung ausrief. Vor
mir hattet ihr ein Abkommen getroffen in dem Haus, über dem mein Name
ausgerufen ist.

<<v16>>
16 Aber ihr seid wieder umgekehrt und habt meinen Namen entweiht; denn
jeder von euch hat seinen Sklaven oder seine Sklavin zurückgeholt, die
ihr doch völlig freigelassen hattet. Ihr habt sie gezwungen, wieder eure
Sklaven und Sklavinnen zu werden.

<<v17>>
17 Darum - so spricht der Herr: Ihr habt mir nicht gehorcht und keiner
hat für seinen Stammesbruder und seinen Nächsten die Freilassung
ausgerufen. Wohlan, so rufe ich euch eine Freilassung aus - Spruch des
Herrn - für Schwert, Pest und Hunger und ich mache euch zu einem Bild
des Schreckens für alle Reiche der Erde.

<<v18>>
18 Ich mache die Männer, die mein Abkommen verletzt und die Worte der
Abmachung, die sie vor mir getroffen hatten, nicht gehalten haben, dem
Kalb gleich, das sie in zwei Hälften zerschnitten haben und zwischen
dessen Stücken sie hindurchgegangen sind. ^{[[#fn4][4]]}

<<v19>>
19 Die Großen Judas und Jerusalems, die Höflinge, die Priester und alle
Bürger des Landes, die zwischen den Stücken des Kalbes hindurchgegangen
sind,

<<v20>>
20 sie alle gebe ich in die Hand ihrer Feinde und derer, die ihnen nach
dem Leben trachten. Ihre Leichen sollen den Vögeln des Himmels und den
Tieren des Feldes zum Fraß dienen.

<<v21>>
21 Auch Zidkija, den König von Juda, und seine Großen liefere ich ihren
Feinden aus und denen, die ihnen nach dem Leben trachten, dem Heer des
Königs von Babel, das eben von euch abgezogen ist.

<<v22>>
22 Schon gebe ich den Befehl - Spruch des Herrn - und hole sie zu dieser
Stadt zurück, damit sie gegen sie kämpfen, sie erobern und
niederbrennen. Die Städte Judas mache ich zur menschenleeren Wüste.
^{[[#fn5][5]]}\\
\\

^{[[#fnm1][1]]} ℘ (2-3) 32,3f

^{[[#fnm2][2]]} ℘ 2 Chr 16,14; Jer 22,18

^{[[#fnm3][3]]} ℘ Ex 21,2; Lev 25,41; Dtn 15,12

^{[[#fnm4][4]]} Diese Form des Bundesschlusses wird in Gen 15,9f.17
beschrieben. Das Hindurchschreiten zwischen den Teilen eines Tieres ist
sinnbildliche Handlung für eine bedingte Selbstverfluchung: Ich will
selbst in Stücke gehauen werden, wenn ich den Vertrag breche.

^{[[#fnm5][5]]} ℘ 37,8f
