:PROPERTIES:
:ID:       bff8f509-2bd3-4c00-a9b2-f906f14e6fc4
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_24.html][24]] [[file:Jer_25.html][25]] *26*
[[file:Jer_27.html][27]] [[file:Jer_28.html][28]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 26
  :PROPERTIES:
  :CUSTOM_ID: jer-26
  :END:

<<verses>>

<<v1>>
** Die Gerichtsworte über Israel und Juda: 26,1 - 29,32
   :PROPERTIES:
   :CUSTOM_ID: die-gerichtsworte-über-israel-und-juda-261---2932
   :END:
**** Die Tempelrede: 26,1-19
     :PROPERTIES:
     :CUSTOM_ID: die-tempelrede-261-19
     :END:
1 Im Anfang der Regierung Jojakims, des Sohnes Joschijas, des Königs von
Juda, erging vom Herrn dieses Wort: ^{[[#fn1][1]]}

<<v2>>
2 So spricht der Herr: Stell dich in den Vorhof des Hauses des Herrn und
sag zu den Leuten, die aus allen Städten Judas kommen, um im Haus des
Herrn anzubeten, alles, was ich dir ihnen zu verkünden aufgetragen habe;
kein Wort sollst du weglassen.

<<v3>>
3 Vielleicht hören sie und kehren um, jeder von seinem bösen Weg, sodass
mich das Unheil reut, das ich ihnen wegen ihrer schlechten Taten
zugedacht habe.

<<v4>>
4 Sag also zu ihnen: So spricht der Herr: Wenn ihr nicht auf mein Wort
hört und meiner Weisung nicht folgt, die ich euch gegeben habe,

<<v5>>
5 wenn ihr nicht auf die Worte meiner Knechte, der Propheten, hört, die
ich immer wieder zu euch sende, obwohl ihr nicht hört, ^{[[#fn2][2]]}

<<v6>>
6 dann verfahre ich mit diesem Haus wie mit Schilo und mache diese Stadt
zu einem Fluch bei allen Völkern der Erde. ^{[[#fn3][3]][[#fn4][4]]}

<<v7>>
7 Die Priester, die Propheten und das ganze Volk hörten, wie Jeremia
diese Worte vor dem Haus des Herrn vortrug.

<<v8>>
8 Als Jeremia alles gesagt hatte, was er im Auftrag des Herrn vor dem
ganzen Volk zu verkünden hatte, ergriffen ihn die Priester, die
Propheten und alles Volk und schrien: Jetzt musst du sterben.

<<v9>>
9 Warum weissagst du im Namen des Herrn: Wie Schilo wird es diesem Haus
gehen und diese Stadt wird verwüstet und entvölkert werden? Das ganze
Volk rottete sich beim Haus des Herrn um Jeremia zusammen.

<<v10>>
10 Als die Beamten Judas von diesen Vorgängen hörten, gingen sie vom
Königspalast zum Haus des Herrn hinauf und setzten sich am Eingang des
Neuen Tempeltors nieder.

<<v11>>
11 Die Priester und Propheten sagten zu den Beamten und zum ganzen Volk:
Dieser Mann hat den Tod verdient; denn er hat gegen diese Stadt
geweissagt, wie ihr mit eigenen Ohren gehört habt.

<<v12>>
12 Jeremia aber erwiderte allen Beamten und dem ganzen Volk: Der Herr
hat mich gesandt, damit ich als Prophet gegen dieses Haus und diese
Stadt alle Worte verkünde, die ihr gehört habt.

<<v13>>
13 Nun also, bessert euer Verhalten und euer Tun und hört auf die Stimme
des Herrn, eures Gottes! Dann wird den Herrn das Unheil reuen, das er
euch angedroht hat. ^{[[#fn5][5]]}

<<v14>>
14 Ich selbst bin in eurer Hand; macht mit mir, was ihr für gut und
recht haltet.

<<v15>>
15 Aber das sollt ihr wissen: Wenn ihr mich tötet, bringt ihr
unschuldiges Blut über euch, über diese Stadt und ihre Einwohner. Denn
der Herr hat mich wirklich zu euch gesandt, damit ich euch alle diese
Worte in die Ohren rufe.

<<v16>>
16 Da sagten die Beamten und das ganze Volk zu den Priestern und
Propheten: Dieser Mann hat den Tod nicht verdient; denn er hat zu uns im
Namen des Herrn, unseres Gottes, geredet.

<<v17>>
17 Einige von den Ältesten des Landes standen auf und sagten zu der
ganzen Volksversammlung:

<<v18>>
18 Micha von Moreschet, der zur Zeit Hiskijas, des Königs von Juda, als
Prophet wirkte, hat zum ganzen Volk Juda gesagt: So spricht der Herr der
Heere: Zion wird umgepflügt zu Ackerland, Jerusalem wird zum
Trümmerhaufen, der Tempelberg zur überwucherten Höhe. ^{[[#fn6][6]]}

<<v19>>
19 Haben ihn etwa Hiskija, der König von Juda, und ganz Juda deshalb
hingerichtet? Hat er nicht Gott gefürchtet und den Zorn des Herrn
besänftigt, sodass den Herrn das Unheil reute, das er ihnen angedroht
hatte? Und wir sollten ein so großes Unrecht tun zu unserem eigenen
Schaden?\\
\\

<<v20>>
**** Die Ermordung des Propheten Urija: 26,20-24
     :PROPERTIES:
     :CUSTOM_ID: die-ermordung-des-propheten-urija-2620-24
     :END:
20 Damals wirkte noch ein anderer Mann als Prophet im Namen des Herrn,
Urija, der Sohn Schemajas, aus Kirjat-Jearim. Er weissagte gegen diese
Stadt und dieses Land mit ganz ähnlichen Worten wie Jeremia.

<<v21>>
21 Der König Jojakim, alle seine Heerführer und alle Beamten hörten von
seinen Reden. Daher suchte der König ihn zu töten. Als Urija davon
erfuhr, bekam er Angst, floh und gelangte nach Ägypten.

<<v22>>
22 Der König Jojakim aber schickte Leute nach Ägypten, nämlich Elnatan,
den Sohn Achbors, mit einigen Männern.

<<v23>>
23 Sie holten Urija aus Ägypten und brachten ihn zu König Jojakim;
dieser ließ ihn mit dem Schwert erschlagen und seinen Leichnam zu den
Gräbern des niedrigen Volkes werfen.

<<v24>>
24 Ahikam jedoch, der Sohn Schafans, beschützte Jeremia, sodass man ihn
nicht dem Volk auslieferte, das ihn töten wollte.\\
\\

^{[[#fnm1][1]]} ℘ (1-9) 7,1-15

^{[[#fnm2][2]]} ℘ 25,4

^{[[#fnm3][3]]} ℘ 7,12; 9,10

^{[[#fnm4][4]]} Zu Schilo vgl. die Anmerkung zu 7,12.

^{[[#fnm5][5]]} ℘ 7,3

^{[[#fnm6][6]]} ℘ Mi 3,12
