:PROPERTIES:
:ID:       3a8336d7-7bd1-4006-8af8-097a7184545b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_47.html][47]] [[file:Jer_48.html][48]] *49*
[[file:Jer_50.html][50]] [[file:Jer_51.html][51]]
[[file:Jer_52.html][52]]

--------------

* Jer 49
  :PROPERTIES:
  :CUSTOM_ID: jer-49
  :END:

<<verses>>

<<v1>>
*** Über andere Nachbarvölker: 49,1-39
    :PROPERTIES:
    :CUSTOM_ID: über-andere-nachbarvölker-491-39
    :END:
**** Über die Ammoniter: 49,1-6
     :PROPERTIES:
     :CUSTOM_ID: über-die-ammoniter-491-6
     :END:
1 Über die Ammoniter: So spricht der Herr: Hat denn Israel keine Söhne
/\\
 oder besitzt es keinen Erben? Warum hat Milkom den Stamm Gad beerbt,
/\\
 warum ließ sich sein Volk in dessen Städten nieder? ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Darum seht, es kommen Tage - Spruch des Herrn -, /\\
 da lasse ich gegen das ammonitische Rabba Kriegslärm ertönen. Zum
wüsten Trümmerhaufen wird es werden, /\\
 seine Tochterstädte brennen im Feuer nieder und Israel wird die
beerben, /\\
 die ihm sein Erbteil raubten - spricht der Herr.\\
\\

<<v3>>
3 Klage laut, Heschbon, denn die Stadt ist zerstört. /\\
 Schreit, ihr Töchter von Rabba! Legt Trauerkleider an, haltet die
Totenklage, /\\
 lauft umher mit eingeritzten Wunden! Denn Milkom muss in die Verbannung
gehen /\\
 zusammen mit seinen Priestern und Fürsten.\\
\\

<<v4>>
4 Was rühmst du dich deiner Kräfte? /\\
 Deine Kraft wird zerrinnen, du abtrünnige Tochter, die auf ihre Schätze
vertraut und sagt: /\\
 Wer kommt an mich heran?\\
\\

<<v5>>
5 Schon lasse ich über dich kommen Schrecken von allen Seiten /\\
 - Spruch des Herrn, des Gottes der Heere. Ihr stoßt einander vorwärts
(auf der Flucht) /\\
 und niemand wird die Flüchtlinge sammeln.\\
\\

<<v6>>
6 Aber danach wende ich das Geschick der Ammoniter /\\
 - Spruch des Herrn. ^{[[#fn2][2]]}\\
\\

<<v7>>
**** Über Edom: 49,7-22
     :PROPERTIES:
     :CUSTOM_ID: über-edom-497-22
     :END:
7 Über Edom: So spricht der Herr der Heere: Gibt es keine Weisheit mehr
in Teman? /\\
 Ging den Klugen der Rat verloren, /\\
 ist ihre Weisheit verdorben? ^{[[#fn3][3]]}\\
\\

<<v8>>
8 Flieht, macht kehrt, /\\
 tief unten versteckt euch, Einwohner von Dedan! Denn ich bringe über
Esau Verderben, /\\
 die Zeit seiner Bestrafung. ^{[[#fn4][4]]}\\
\\

<<v9>>
9 Wenn Winzer zu dir kommen, /\\
 lassen sie keine Nachlese übrig. Wenn Diebe in der Nacht kommen, /\\
 zerstören sie nach Lust. ^{[[#fn5][5]]}\\
\\

<<v10>>
10 Ja, ich selbst hole Esau aus dem Versteck, /\\
 decke seine Schlupfwinkel auf, /\\
 sodass er sich nicht mehr verbergen kann. Seine Brut wird vernichtet,
/\\
 seine Verwandtschaft und seine Nachbarn, /\\
 sodass keiner mehr sagt: ^{[[#fn6][6]]}\\
\\

<<v11>>
11 Lass deine Waisen! Ich will für sie sorgen, /\\
 deine Witwen können sich verlassen auf mich.

<<v12>>
12 Denn so spricht der Herr: Sogar jene, die es nicht verdient hätten,
aus dem Becher zu trinken, müssen daraus trinken und da solltest du
verschont bleiben? Du bleibst nicht verschont, du musst trinken.
^{[[#fn7][7]]}

<<v13>>
13 Denn ich schwöre bei mir selbst - Spruch des Herrn: Zu einem Bild des
Entsetzens, zum Hohn, zur Öde und zum Fluch wird Bozra und alle seine
Nachbarstädte werden für immer zu Trümmerhaufen. ^{[[#fn8][8]]}\\
\\

<<v14>>
14 Ich habe vom Herrn eine Kunde gehört, /\\
 ein Bote ist zu den Völkern gesandt: Schart euch zusammen, rückt aus
gegen Edom, /\\
 tretet an zum Kampf! ^{[[#fn9][9]]}\\
\\

<<v15>>
15 Ja, ich mache dich klein unter den Völkern, /\\
 verachtet unter den Menschen.\\
\\

<<v16>>
16 Deine Furcht erregende Macht hat dich betört, /\\
 dein vermessener Sinn, weil du in Felsklüften wohnst, /\\
 an Bergeshöhen dich klammerst. Baust du dein Nest auch hoch wie der
Adler, /\\
 ich stürze dich von dort hinab - Spruch des Herrn.\\
\\

<<v17>>
17 Edom wird zu einem Bild des Entsetzens; /\\
 jeder, der vorbeikommt, ist entsetzt /\\
 und spottet über alle Schläge, die es erlitt. ^{[[#fn10][10]]}\\
\\

<<v18>>
18 Wie beim Untergang von Sodom und Gomorra /\\
 und ihrer Nachbarstädte, spricht der Herr, so wird auch dort niemand
mehr wohnen, /\\
 kein Mensch darin leben. ^{[[#fn11][11]]}\\
\\

<<v19>>
19 Wie ein Löwe, der heraufkommt /\\
 aus dem Dickicht des Jordan /\\
 zu den immer grünen Auen, so jage ich sie jählings davon /\\
 und setze meinen Erwählten dort ein. Denn wer ist mir gleich, /\\
 wer zieht mich zur Rechenschaft /\\
 und wo ist der Hirt, der vor mir standhält? ^{[[#fn12][12]]}\\
\\

<<v20>>
20 Darum hört den Beschluss, /\\
 den der Herr gegen Edom gefasst hat, und die Pläne, die er ersann /\\
 gegen Temans Bewohner: Wegschleppen wird man die Hirtenknaben, /\\
 ihr Weideplatz wird sich über sie entsetzen.\\
\\

<<v21>>
21 Von Edoms dröhnendem Fall erbebt die Erde, /\\
 bis zum Schilfmeer hört man sein Schreien.\\
\\

<<v22>>
22 Seht, wie ein Adler steigt es empor, /\\
 schwebt es heran /\\
 und breitet seine Schwingen über Bozra aus. Das Herz der Helden Edoms
ist an jenem Tag /\\
 wie das Herz einer Frau in Wehen. ^{[[#fn13][13]]}\\
\\

<<v23>>
**** Über Damaskus: 49,23-27
     :PROPERTIES:
     :CUSTOM_ID: über-damaskus-4923-27
     :END:
23 Über Damaskus: Bestürzt sind Hamat und Arpad; /\\
 denn böse Nachricht mussten sie hören. Sie wanken vor Kummer wie das
Meer, /\\
 das nicht zur Ruhe kommen kann. ^{[[#fn14][14]]}\\
\\

<<v24>>
24 Damaskus wird schwach, es wendet sich zur Flucht, /\\
 Schrecken erfasst es, /\\
 Angst und Wehen ergreifen es wie eine Gebärende.\\
\\

<<v25>>
25 Wie ist doch die ruhmreiche Stadt verlassen, /\\
 die Burg der Freude!\\
\\

<<v26>>
26 Darum fallen ihre jungen Männer auf den Plätzen, /\\
 alle Krieger kommen um an jenem Tag /\\
 - Spruch des Herrn der Heere. ^{[[#fn15][15]]}\\
\\

<<v27>>
27 Ich lege Feuer an die Mauer von Damaskus; /\\
 es verzehrt die Paläste Ben-Hadads. ^{[[#fn16][16]]}\\
\\

<<v28>>
**** Über die arabischen Stämme: 49,28-33
     :PROPERTIES:
     :CUSTOM_ID: über-die-arabischen-stämme-4928-33
     :END:
28 Über Kedar und die Reiche von Hazor, die Nebukadnezzar, der König von
Babel, erobert hat. So spricht der Herr: Auf, zieht gegen Kedar, /\\
 bezwingt die Söhne des Ostens! ^{[[#fn17][17]]}\\
\\

<<v29>>
29 Man raubt ihre Zelte und Herden, /\\
 ihre Decken und ihr ganzes Gerät; auch ihre Kamele nimmt man mit /\\
 und man ruft über sie: Grauen ringsum! ^{[[#fn18][18]]}\\
\\

<<v30>>
30 Flieht, macht euch eilends davon, /\\
 tief unten versteckt euch, /\\
 ihr Bewohner von Hazor - Spruch des Herrn. Denn Nebukadnezzar, der
König von Babel, /\\
 hat gegen euch einen Beschluss gefasst /\\
 und einen Plan gegen euch ersonnen. ^{[[#fn19][19]]}\\
\\

<<v31>>
31 Auf, zieht gegen das sorglose Volk, /\\
 das in Sicherheit lebt - Spruch des Herrn -, das keine Tore und Riegel
hat; /\\
 man haust ja einsam für sich.\\
\\

<<v32>>
32 Ihre Kamele werden erbeutet, /\\
 ihre vielen Herden geraubt. In alle Winde zerstreue ich sie, /\\
 die Leute mit gestutztem Haar, von allen Seiten bringe ich ihnen
Verderben /\\
 - Spruch des Herrn. ^{[[#fn20][20]]}\\
\\

<<v33>>
33 Hazor wird zur Behausung für die Schakale, /\\
 eine Wüste für immer. Niemand wird mehr dort wohnen, /\\
 kein Mensch darin leben. ^{[[#fn21][21]]}\\
\\

<<v34>>
**** Über Elam: 49,34-39
     :PROPERTIES:
     :CUSTOM_ID: über-elam-4934-39
     :END:
34 Das Wort des Herrn gegen Elam, das zu Beginn der Regierung Zidkijas,
des Königs von Juda, an den Propheten Jeremia erging. ^{[[#fn22][22]]}\\
\\

<<v35>>
35 So spricht der Herr der Heere: Seht, ich zerbreche den Bogen Elams,
/\\
 seine stärkste Waffe. ^{[[#fn23][23]]}\\
\\

<<v36>>
36 Ich bringe über Elam vier Winde /\\
 von den vier Enden des Himmels. In alle diese Winde zerstreue ich sie,
/\\
 sodass es kein Volk gibt, /\\
 zu dem nicht Versprengte aus Elam kommen.\\
\\

<<v37>>
37 Ich jage den Elamitern Schrecken ein vor ihren Feinden, /\\
 vor allen, die ihnen nach dem Leben trachten. Unheil lasse ich über sie
kommen, /\\
 meinen glühenden Zorn - Spruch des Herrn. Ich schicke das Schwert
hinter ihnen her, /\\
 bis ich sie vernichtet habe. ^{[[#fn24][24]]}\\
\\

<<v38>>
38 Ich stelle meinen Thron in Elam auf /\\
 und vernichte dort König und Fürsten - /\\
 Spruch des Herrn.\\
\\

<<v39>>
39 Aber in ferner Zukunft wende ich Elams Geschick /\\
 - Spruch des Herrn. ^{[[#fn25][25]]}\\
\\

^{[[#fnm1][1]]} Milkom (= König) ist der Hauptgott der Ammoniter.

^{[[#fnm2][2]]} ℘ 48,47

^{[[#fnm3][3]]} ℘ Obd 8f

^{[[#fnm4][4]]} 8.10: Esau ist nach Gen 36 der Stammvater der Edomiter.

^{[[#fnm5][5]]} ℘ Obd 5

^{[[#fnm6][6]]} ℘ Obd 6

^{[[#fnm7][7]]} ℘ 25,15-17

^{[[#fnm8][8]]} ℘ 44,22

^{[[#fnm9][9]]} ℘ (14-16) Obd 1-4

^{[[#fnm10][10]]} ℘ 19,8; 50,13

^{[[#fnm11][11]]} ℘ 50,40; Jes 13,19f

^{[[#fnm12][12]]} 19-21: Ist fast wörtlich gleich wie die Drohrede gegen
Babel in 50,44-46 und hat dort seinen ursprünglichen Platz, wie man aus
V. 21 ersieht. Nicht vom Untergang des Kleinstaats Edom «erbebt die
Erde», sondern nur vom Fall des Neubabylonischen Großreichs.

^{[[#fnm13][13]]} ℘ 48,40f

^{[[#fnm14][14]]} ℘ Jes 57,20

^{[[#fnm15][15]]} ℘ 50,30

^{[[#fnm16][16]]} ℘ 17,27; Am 1,4

^{[[#fnm17][17]]} Söhne des Ostens: die Beduinen der Arabischen Wüste.

^{[[#fnm18][18]]} ℘ 6,25; 20,3; 46,5

^{[[#fnm19][19]]} ℘ 49,8.20

^{[[#fnm20][20]]} ℘ 25,23

^{[[#fnm21][21]]} ℘ 9,10; 49,13.18; 50,3

^{[[#fnm22][22]]} Elam war damals noch selbstständig, ging aber später
im Kernland des Perserreichs auf. Es ist das Gebiet nördlich des
Persischen Golfs.

^{[[#fnm23][23]]} ℘ Jes 22,6

^{[[#fnm24][24]]} ℘ 9,15

^{[[#fnm25][25]]} ℘ 48,47; 49,6
