:PROPERTIES:
:ID:       9f3a9ce7-8f70-40e8-98e8-b45d403b658f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_46.html][46]] [[file:Jer_47.html][47]] *48*
[[file:Jer_49.html][49]] [[file:Jer_50.html][50]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 48
  :PROPERTIES:
  :CUSTOM_ID: jer-48
  :END:

<<verses>>

<<v1>>
*** Über Moab: 48,1-47
    :PROPERTIES:
    :CUSTOM_ID: über-moab-481-47
    :END:
**** Die Zerstörung: 48,1-10
     :PROPERTIES:
     :CUSTOM_ID: die-zerstörung-481-10
     :END:
1 Über Moab: So spricht der Herr der Heere, der Gott Israels: Weh über
Nebo, es wird verwüstet, /\\
 erobert wird Kirjatajim. /\\
 Zuschanden wird die Hochburg und geschleift.\\
\\

<<v2>>
2 Moabs Ruhm ist dahin. /\\
 In Heschbon plante man sein Verderben: Kommt, wir rotten es aus, /\\
 sodass es kein Volk mehr ist. Auch du, Madmen, wirst verstummen; /\\
 das Schwert verfolgt dich.\\
\\

<<v3>>
3 Horch! Wehgeschrei aus Horonajim: /\\
 Verwüstung und große Zerstörung!\\
\\

<<v4>>
4 Zerstört ist Moab! /\\
 So gellt der Schrei bis nach Zoar. ^{[[#fn1][1]]}\\
\\

<<v5>>
5 Die Steige von Luhit /\\
 steigt man weinend hinauf. Ja, am Abstieg von Horonajim /\\
 hört man über die Zerstörung entsetzliches Schreien.\\
\\

<<v6>>
6 Flieht, rettet euer Leben! /\\
 Macht es wie der Wildesel in der Wüste!\\
\\

<<v7>>
7 Weil du auf eigene Werke und Schätze vertraut hast, /\\
 wirst auch du erobert werden. In die Verbannung muss Kemosch ziehen /\\
 samt seinen Priestern und Fürsten.\\
\\

<<v8>>
8 Der Verwüster kommt über jede Stadt, /\\
 keine Stadt kann sich retten. Verheert wird das Tal, verwüstet die
Ebene, /\\
 so spricht der Herr.\\
\\

<<v9>>
9 Setzt ein Grabmal für Moab; /\\
 denn es verfällt ganz und gar. Seine Städte werden zur Wüste, /\\
 niemand wohnt mehr darin.\\
\\

<<v10>>
10 Verflucht, wer den Auftrag des Herrn lässig betreibt, /\\
 ja, verflucht, wer sein Schwert abhält vom Blutvergießen.\\
\\

<<v11>>
**** Der Verwüster: 48,11-28
     :PROPERTIES:
     :CUSTOM_ID: der-verwüster-4811-28
     :END:
11 Ungestört war Moab von Jugend an, /\\
 ruhig lag es auf seiner Hefe. Es wurde nicht umgeschüttet von Gefäß zu
Gefäß: /\\
 Nie musste es in die Verbannung ziehen. Darum blieb ihm sein
Wohlgeschmack erhalten, /\\
 sein Duft veränderte sich nicht. ^{[[#fn2][2]]}\\
\\

<<v12>>
12 Darum kommen Tage - Spruch des Herrn -, /\\
 da schicke ich Kellermeister zu ihm; sie gießen es um, /\\
 entleeren seine Gefäße und zerschlagen seine Krüge.\\
\\

<<v13>>
13 Moab wird an Kemosch zuschanden, /\\
 wie das Haus Israel zuschanden wurde /\\
 an Bet-El, auf das es vertraute. ^{[[#fn3][3]]}\\
\\

<<v14>>
14 Wie könnt ihr sagen: Helden sind wir, /\\
 starke Krieger zum Kampf?\\
\\

<<v15>>
15 Der Verwüster Moabs und seiner Städte steigt hinauf; /\\
 da steigen seine besten jungen Männer hinab, um geschlachtet zu
werden - Spruch des Königs, /\\
 Herr der Heere ist sein Name. ^{[[#fn4][4]]}\\
\\

<<v16>>
16 Der Untergang Moabs rückt heran, /\\
 schnell eilt sein Unglück herbei.\\
\\

<<v17>>
17 Beklagt es alle, ihr seine Nachbarn, /\\
 und alle, die ihr seinen Namen kennt. Sagt: Ach, wie ist zerbrochen der
starke Stab, /\\
 das herrliche Zepter!\\
\\

<<v18>>
18 Steig herab von deiner Würde, /\\
 setz dich in den Kot, /\\
 du thronende Tochter Dibon! Denn Moabs Verwüster zieht hinauf zu dir,
/\\
 zerstört deine Burgen.\\
\\

<<v19>>
19 Stellt euch an den Weg und späht aus, /\\
 ihr Einwohner von Aroër! Fragt den Flüchtling und die fliehende Frau,
/\\
 sagt: Was ist denn geschehen?\\
\\

<<v20>>
20 Zuschanden ist Moab, ja, ganz zerbrochen. /\\
 Klagt und schreit! /\\
 Meldet am Arnon: Moab ist verwüstet.\\
\\

<<v21>>
21 Ein Gericht kam über das ebene Land, /\\
 über Holon, Jahaz und Mefaat,\\
\\

<<v22>>
22 über Dibon, Nebo und Bet-Diblatajim, /\\
\\

<<v23>>
23 über Kirjatajim, Bet-Gamul und Bet-Meon,\\
\\

<<v24>>
24 über Kerijot und Bozra /\\
 und über alle Städte des Landes Moab, /\\
 die fernen und die nahen.\\
\\

<<v25>>
25 Abgehauen ist Moabs Horn, /\\
 zerschmettert sein Arm [- Spruch des Herrn]. ^{[[#fn5][5]]}\\
\\

<<v26>>
26 Macht es betrunken; /\\
 denn es hat geprahlt gegen den Herrn. So stürze Moab in sein eigenes
Gespei /\\
 und verfalle nun selbst dem Gespött. ^{[[#fn6][6]]}\\
\\

<<v27>>
27 Oder diente nicht Israel dir zum Gespött? /\\
 Wurde es etwa beim Diebstahl ertappt, dass du höhnend den Kopf
geschüttelt hast, /\\
 sooft du von ihm sprachst? ^{[[#fn7][7]]}\\
\\

<<v28>>
28 Verlasst die Städte, wohnt in den Felsen, /\\
 ihr Bewohner von Moab! Macht es wie die Taube, die nistet /\\
 an den Wänden der offenen Schlucht.\\
\\

<<v29>>
**** Der Hochmut vor dem Fall: 48,29-39
     :PROPERTIES:
     :CUSTOM_ID: der-hochmut-vor-dem-fall-4829-39
     :END:
29 Wir haben von Moabs Stolz gehört - /\\
 es ist stolz über die Maßen -; von seinem Hochmut und Stolz haben wir
gehört, /\\
 von seinem Dünkel und hochfahrenden Sinn. ^{[[#fn8][8]]}\\
\\

<<v30>>
30 Ich kenne seinen Übermut - Spruch des Herrn -, /\\
 sein Geschwätz ist nicht wahr, /\\
 sein Tun ist nicht recht.\\
\\

<<v31>>
31 Darum jammere ich laut über Moab, /\\
 über ganz Moab klage ich /\\
 und seufze über die Leute von Kir-Heres.\\
\\

<<v32>>
32 Mehr als um Jaser weine ich um dich, /\\
 Weinstock von Sibma; bis ans Meer zogen sich deine Ranken hin, /\\
 sie reichten bis Jaser. Über deine Weinlese und Ernte /\\
 fiel der Verwüster her.\\
\\

<<v33>>
33 Verschwunden sind Freude und Jubelgeschrei /\\
 vom Fruchtland und vom Land Moab. Die Kufen sind leer von Wein, /\\
 kein Winzer keltert, /\\
 kein Jauchzen ertönt.\\
\\

<<v34>>
34 Das Schreien von Heschbon und Elale dringt bis Jahaz, laut klagt man
von Zoar bis Horonajim und Eglat-Schelischija; denn selbst das Wasser
von Nimrim versiegt. ^{[[#fn9][9]]}

<<v35>>
35 Ich mache es für Moab unmöglich - Spruch des Herrn -, dass jemand auf
der Kulthöhe opfert und seinen Göttern Rauchopfer darbringt.

<<v36>>
36 Darum jammert mein Herz um Moab wie eine Flöte, ja mein Herz jammert
um die Leute von Kir-Heres wie eine Flöte, weil sie ihre ganze Habe
verloren.

<<v37>>
37 Jedes Haupt ist kahl geschoren und jeder Bart abgeschnitten, an allen
Händen sind Trauermale und um die Hüften Trauerkleider. ^{[[#fn10][10]]}

<<v38>>
38 Auf allen Dächern und Plätzen Moabs hört man nichts als Klage. Ja,
ich zerschlage Moab wie ein Gefäß, das niemand mehr will - Spruch des
Herrn.

<<v39>>
39 Ach, wie ist es zerbrochen, wie hat Moab sich schmählich zur Flucht
gewandt! So wird Moab zum Gespött und zu einem Bild des Entsetzens für
all seine Nachbarn.\\
\\

<<v40>>
**** Das unabwendbare Strafgericht: 48,40-47
     :PROPERTIES:
     :CUSTOM_ID: das-unabwendbare-strafgericht-4840-47
     :END:
40 Denn so spricht der Herr: Seht, wie ein Adler schwebt es heran /\\
 und breitet seine Schwingen über Moab aus.
^{[[#fn11][11]][[#fn12][12]]}\\
\\

<<v41>>
41 Die Städte werden erobert, /\\
 die Festungen eingenommen. Das Herz der Helden Moabs ist an jenem Tag
/\\
 wie das Herz einer Frau in Wehen.\\
\\

<<v42>>
42 Vernichtet wird Moab, sodass es kein Volk mehr ist; /\\
 denn es hat geprahlt gegen den Herrn. ^{[[#fn13][13]]}\\
\\

<<v43>>
43 Grauen, Grube und Garn warten auf dich, /\\
 Bewohner von Moab - Spruch des Herrn. ^{[[#fn14][14]]}\\
\\

<<v44>>
44 Wer dem Grauen entflieht, fällt in die Grube, /\\
 wer aus der Grube steigt, fängt sich im Garn. Ja, das werde ich über
Moab bringen /\\
 im Jahr seiner Bestrafung - Spruch des Herrn.\\
\\

<<v45>>
45 Im Schatten von Heschbon bleiben erschöpft Flüchtlinge stehen. /\\
 Doch Feuer geht aus von Heschbon, /\\
 eine Flamme von Sihons Haus. Es verzehrt die Schläfe Moabs, /\\
 den Scheitel der lärmenden Schreier. ^{[[#fn15][15]]}\\
\\

<<v46>>
46 Wehe dir, Moab, /\\
 verloren bist du, Volk des Kemosch. Denn deine Söhne schleppt man in
die Verbannung, /\\
 deine Töchter in die Gefangenschaft.\\
\\

<<v47>>
47 Aber in ferner Zukunft wende ich Moabs Geschick /\\
 - Spruch des Herrn. /\\
 [Bis hierher geht das Gerichtswort über Moab.]
^{[[#fn16][16]][[#fn17][17]]}\\
\\

^{[[#fnm1][1]]} ℘ Jes 15,5

^{[[#fnm2][2]]} ℘ Zef 1,12

^{[[#fnm3][3]]} Kemosch ist der Hauptgott der Moabiter.

^{[[#fnm4][4]]} ℘ 46,18

^{[[#fnm5][5]]} Spruch des Herrn: fehlt in G.

^{[[#fnm6][6]]} ℘ 48,42

^{[[#fnm7][7]]} ℘ 2,26

^{[[#fnm8][8]]} ℘ Jes 16,6-12

^{[[#fnm9][9]]} ℘ Jes 15,4

^{[[#fnm10][10]]} ℘ 16,6; Jes 15,2f

^{[[#fnm11][11]]} ℘ 49,22

^{[[#fnm12][12]]} Wer «es» oder «er» ist, wird in geheimnisvoller
Schwebe gelassen: Gott selbst oder ein menschlicher Vollstrecker seines
Strafgerichts.

^{[[#fnm13][13]]} ℘ 48,26

^{[[#fnm14][14]]} ℘ Jes 24,17f

^{[[#fnm15][15]]} ℘ (45-46) Num 21,28f

^{[[#fnm16][16]]} ℘ 49,6.39

^{[[#fnm17][17]]} 47c: Fehlt in G.
