:PROPERTIES:
:ID:       6d42be52-71b3-4ebd-97fd-b1ad908a4bcd
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_25.html][25]] [[file:Jer_26.html][26]] *27*
[[file:Jer_28.html][28]] [[file:Jer_29.html][29]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 27
  :PROPERTIES:
  :CUSTOM_ID: jer-27
  :END:

<<verses>>

<<v1>>
**** Das Joch Babels: 27,1-22
     :PROPERTIES:
     :CUSTOM_ID: das-joch-babels-271-22
     :END:
1 Im Anfang der Regierung Zidkijas, des Sohnes Joschijas, des Königs von
Juda, erging vom Herrn folgendes Wort an Jeremia.

<<v2>>
2 So sprach der Herr zu mir: Mach dir Stricke und Jochhölzer, und leg
sie dir auf den Nacken! ^{[[#fn1][1]]}

<<v3>>
3 Dann schick eine Botschaft an den König von Edom, den König von Moab,
den König der Ammoniter, den König von Tyrus und den König von Sidon,
durch die Gesandten, die zu Zidkija, dem König von Juda, nach Jerusalem
gekommen sind.

<<v4>>
4 Gib ihnen folgenden Auftrag an ihre Gebieter: So spricht der Herr der
Heere, der Gott Israels: Sagt so zu euren Gebietern:

<<v5>>
5 Ich bin es, der die Erde erschaffen hat samt den Menschen und den
Tieren, die auf der Erde leben, durch meine gewaltige Kraft und meinen
hoch erhobenen Arm, und ich gebe sie, wem ich will. ^{[[#fn2][2]]}

<<v6>>
6 Jetzt gebe ich alle diese Länder in die Hand meines Knechtes, des
Königs Nebukadnezzar von Babel; selbst die Tiere des Feldes mache ich
ihm dienstbar.

<<v7>>
7 Alle Völker sollen ihm untertan sein, ihm, seinem Sohn und seinem
Enkel, bis auch für sein eigenes Land die Zeit kommt, dass große Völker
und mächtige Könige es knechten.

<<v8>>
8 Will aber ein Volk oder Reich dem König Nebukadnezzar von Babel nicht
untertan sein und seinen Nacken nicht unter das Joch des Königs von
Babel beugen, so werde ich dieses Volk mit Schwert, Hunger und Pest
heimsuchen - Spruch des Herrn -, bis ich es seiner Hand ausgeliefert
habe.

<<v9>>
9 Ihr aber, hört nicht auf eure Propheten, Wahrsager, Träumer,
Zeichendeuter und Zauberer, wenn sie zu euch sagen: Ihr werdet dem König
von Babel nicht untertan sein. ^{[[#fn3][3]]}

<<v10>>
10 Denn sie lügen, wenn sie euch weissagen, und damit vertreiben sie
euch aus eurer Heimat; denn ich verstoße euch, sodass ihr zugrunde geht.

<<v11>>
11 Das Volk aber, das seinen Nacken unter das Joch des Königs von Babel
beugt und ihm untertan ist, lasse ich ungestört auf seinem heimatlichen
Boden - Spruch des Herrn -; es kann ihn bebauen und auf ihm wohnen.

<<v12>>
12 Auch zu Zidkija, dem König von Juda, redete ich ganz in diesem Sinn:
Beugt euren Nacken unter das Joch des Königs von Babel und seid ihm und
seinem Volk untertan; dann bleibt ihr am Leben.

<<v13>>
13 Warum sollt ihr, du und dein Volk, durch Schwert, Hunger und Pest
umkommen, wie der Herr dem Volk, das dem König von Babel nicht untertan
sein will, angedroht hat?

<<v14>>
14 Hört nicht auf die Reden der Propheten, die zu euch sagen: Ihr sollt
dem König von Babel nicht untertan sein. Denn was sie euch weissagen,
ist Lüge. ^{[[#fn4][4]]}

<<v15>>
15 Ich habe sie nicht gesandt - Spruch des Herrn -; darum ist es Lüge,
wenn sie in meinem Namen weissagen; die Folge wird sein, dass ich euch
verstoße und dass ihr zugrunde geht, ihr und die Propheten, die euch
weissagen.

<<v16>>
16 Zu den Priestern und dem ganzen Volk sagte ich: So spricht der Herr:
Hört nicht auf die Reden eurer Propheten, die euch weissagen: Die Geräte
des Hauses des Herrn werden aus Babel zurückgebracht werden, und zwar
bald. Denn was sie euch weissagen, ist Lüge.

<<v17>>
17 Hört nicht auf sie! Seid dem König von Babel untertan; dann bleibt
ihr am Leben. Warum soll diese Stadt ein Trümmerhaufen werden?

<<v18>>
18 Wenn sie Propheten sind und das Wort des Herrn wirklich bei ihnen
ist, so mögen sie doch den Herrn der Heere bestürmen, dass die Geräte,
die noch im Haus des Herrn, im Palast des Königs von Juda und in
Jerusalem verblieben sind, nicht auch nach Babel kommen.

<<v19>>
19 Denn so spricht der Herr der Heere über die Säulen, das Eherne Meer,
die fahrbaren Gestelle und den Rest der in dieser Stadt noch
verbliebenen Geräte, ^{[[#fn5][5]]}

<<v20>>
20 die Nebukadnezzar, der König von Babel, nicht mitgenommen hat, als er
Jojachin, den Sohn Jojakims, den König von Juda, aus Jerusalem nach
Babel verschleppte samt allen Vornehmen Judas und Jerusalems:

<<v21>>
21 Ja, so spricht der Herr der Heere, der Gott Israels, über die Geräte,
die im Haus des Herrn, im Palast des Königs von Juda und in Jerusalem
verblieben sind:

<<v22>>
22 Nach Babel werden sie gebracht und dort bleiben sie bis zu dem Tag,
an dem ich mich ihrer annehme - Spruch des Herrn - und sie wieder an
diesen Ort heraufbringe. ^{[[#fn6][6]]}\\
\\

^{[[#fnm1][1]]} ℘ 28,10

^{[[#fnm2][2]]} ℘ 32,17

^{[[#fnm3][3]]} ℘ 14,13f

^{[[#fnm4][4]]} ℘ 14,14; 29,8f

^{[[#fnm5][5]]} ℘ 2 Kön 25,13-17

^{[[#fnm6][6]]} ℘ Esra 1,7-11
