:PROPERTIES:
:ID:       dc941953-bb13-4d2d-85fc-8655371f3a8f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_3.html][3]] [[file:Jer_4.html][4]] *5* [[file:Jer_6.html][6]]
[[file:Jer_7.html][7]] ... [[file:Jer_52.html][52]]

--------------

* Jer 5
  :PROPERTIES:
  :CUSTOM_ID: jer-5
  :END:

<<verses>>

<<v1>>
**** Die schwere Schuld: 5,1-31
     :PROPERTIES:
     :CUSTOM_ID: die-schwere-schuld-51-31
     :END:
1 Zieht durch Jerusalems Straßen, /\\
 schaut genau hin und forscht nach, sucht auf seinen Plätzen, ob ihr
einen findet, /\\
 ob einer da ist, der Recht übt und auf Treue bedacht ist: /\\
 Dann will ich der Stadt verzeihen - Spruch des Herrn.\\
\\

<<v2>>
2 Doch selbst wenn sie sagen: /\\
 «So wahr der Herr lebt», /\\
 schwören sie gewiss einen Meineid. ^{[[#fn1][1]]}\\
\\

<<v3>>
3 Herr, sind deine Augen nicht auf Treue gerichtet? /\\
 Du hast sie geschlagen, /\\
 aber es tut ihnen nicht weh; du hast sie beinahe vernichtet, /\\
 aber sie wollen sich nicht erziehen lassen. Ihre Stirn ist härter als
Stein, /\\
 sie weigern sich umzukehren.\\
\\

<<v4>>
4 Ich aber dachte: Nur die geringen Leute, /\\
 nur sie handeln töricht, weil sie den Weg des Herrn nicht kennen, /\\
 das Recht ihres Gottes. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Ich will doch lieber zu den Großen gehen /\\
 und zu ihnen reden; denn sie kennen den Weg des Herrn, /\\
 das Recht ihres Gottes. Doch auch sie haben das Joch zerbrochen, /\\
 die Stricke zerrissen. ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Darum schlägt sie der Löwe des Waldes, /\\
 der Steppenwolf überwältigt sie. Vor ihren Städten lauert der Panther,
/\\
 alle, die herauskommen, werden zerfleischt. Denn zahlreich sind ihre
Verbrechen, /\\
 schwer wiegt ihre Abtrünnigkeit.\\
\\

<<v7>>
7 Weshalb sollte ich dir vergeben? /\\
 Deine Söhne haben mich verlassen /\\
 und bei Nichtgöttern geschworen. Ich machte sie satt, doch sie trieben
Ehebruch /\\
 und waren zu Gast im Dirnenhaus.\\
\\

<<v8>>
8 Hengste sind sie geworden, feist und geil, /\\
 jeder wiehert nach der Frau seines Nächsten. ^{[[#fn4][4]]}\\
\\

<<v9>>
9 Sollte ich das nicht bestrafen - Spruch des Herrn - /\\
 und an einem solchen Volk keine Rache nehmen? ^{[[#fn5][5]]}\\
\\

<<v10>>
10 Steigt auf ihre Rebenhänge, und verwüstet sie! /\\
 Doch völlig vernichten sollt ihr sie nicht. Reißt ihre Reben weg; /\\
 denn sie gehören nicht dem Herrn. ^{[[#fn6][6]][[#fn7][7]]}\\
\\

<<v11>>
11 Sie sind mir ja gänzlich untreu geworden, /\\
 das Haus Israel und das Haus Juda - Spruch des Herrn.\\
\\

<<v12>>
12 Sie haben den Herrn verleugnet und gesagt: /\\
 Er ist ein Nichts! Kein Unheil kommt über uns, /\\
 weder Schwert noch Hunger werden wir spüren.\\
\\

<<v13>>
13 Doch diese Propheten werden zunichte; /\\
 das Gotteswort ist nicht bei ihnen. /\\
 [So wird es ihnen ergehen.]\\
\\

<<v14>>
14 Darum - so spricht der Herr, /\\
 der Gott der Heere: Weil man solche Reden führt, /\\
 seht, darum mache ich meine Worte /\\
 in deinem Mund zu Feuersglut und dieses Volk da zum Brennholz, /\\
 das von ihr verzehrt wird.\\
\\

<<v15>>
15 Seht, ich lasse über euch herfallen, Haus Israel, /\\
 ein Volk aus der Ferne - Spruch des Herrn. Ein unüberwindliches Volk
ist es, /\\
 ein uraltes Volk, ein Volk, dessen Sprache du nicht kennst /\\
 und dessen Rede du nicht verstehst. ^{[[#fn8][8]]}\\
\\

<<v16>>
16 Sein Köcher ist wie ein offenes Grab, /\\
 sie alle sind Helden.\\
\\

<<v17>>
17 Es frisst deine Ernte und dein Brot, /\\
 es frisst deine Söhne und Töchter, es frisst deine Schafe und Rinder,
/\\
 es frisst deinen Weinstock und Feigenbaum, es zerschlägt mit dem
Schwert /\\
 deine befestigten Städte, auf die du vertraust.\\
\\

<<v18>>
18 Doch auch in jenen Tagen - Spruch des Herrn - will ich euch nicht
völlig vernichten.

<<v19>>
19 Wenn man dann fragt: Weshalb hat der Herr, unser Gott, uns das alles
angetan?, so sag zu ihnen: Wie ihr mich verlassen und fremden Göttern in
eurem Land gedient habt, so müsst ihr Fremden dienen in einem Land, das
euch nicht gehört. ^{[[#fn9][9]]}\\
\\

<<v20>>
20 Verkündet dies im Haus Jakob /\\
 und ruft es in Juda aus:\\
\\

<<v21>>
21 Hör das, du törichtes Volk ohne Verstand: /\\
 Augen haben sie und sehen nicht; /\\
 Ohren haben sie und hören nicht. ^{[[#fn10][10]]}\\
\\

<<v22>>
22 Fürchtet ihr mich denn nicht - Spruch des Herrn -, /\\
 zittert ihr nicht vor meinem Angesicht? Ich bin es, der dem Meer die
Düne als Grenze gesetzt hat, /\\
 als ewige Schranke, die es nicht überschreiten darf. Mag es auch toben,
es richtet nichts aus; /\\
 mögen seine Wogen auch tosen, /\\
 sie können die Schranke nicht überschreiten.\\
\\

<<v23>>
23 Dieses Volk aber hat ein störrisches, trotziges Herz. /\\
 Sie wichen vom Weg ab und gingen davon.\\
\\

<<v24>>
24 Sie sagten nicht bei sich selbst: /\\
 Lasst uns den Herrn fürchten, unseren Gott, der Regen spendet im Herbst
/\\
 und im Frühjahr zur rechten Zeit, /\\
 der uns die feste Ordnung der Erntewochen bewahrt.\\
\\

<<v25>>
25 Eure Frevel haben diese Ordnung gestört, /\\
 eure Sünden haben euch den Regen vorenthalten.\\
\\

<<v26>>
26 Ja, Frevler gibt es in meinem Volk; /\\
 sie lauern, gebückt wie Vogelsteller, Fallen stellen sie auf, /\\
 Menschen wollen sie fangen.\\
\\

<<v27>>
27 Wie ein Korb mit Vögeln gefüllt ist, /\\
 so sind ihre Häuser voll Betrug; dadurch sind sie mächtig und reich
geworden, /\\
\\

<<v28>>
28 fett und feist. Auch sündigen sie durch ruchloses Tun. /\\
 Das Recht pflegen sie nicht, das Recht der Waisen, die Erfolg erwarten,
/\\
 und die Sache der Armen entscheiden sie nicht. ^{[[#fn11][11]]}\\
\\

<<v29>>
29 Sollte ich das nicht bestrafen - Spruch des Herrn - /\\
 und an einem solchen Volk keine Rache nehmen? ^{[[#fn12][12]]}\\
\\

<<v30>>
30 Wüstes, Grässliches geschieht im Land: /\\
\\

<<v31>>
31 Die Propheten weissagen Lüge und die Priester richten ihre Lehre nach
ihnen aus; /\\
 mein Volk aber liebt es so. Doch was werdet ihr tun, /\\
 wenn es damit zu Ende geht?\\
\\

^{[[#fnm1][1]]} ℘ 4,2

^{[[#fnm2][2]]} «Weg» und «Recht» meinen die sittlichen Forderungen.

^{[[#fnm3][3]]} ℘ 2,20

^{[[#fnm4][4]]} ℘ Ez 22,11

^{[[#fnm5][5]]} ℘ 5,29; 9,8

^{[[#fnm6][6]]} ℘ 5,18; 4,27

^{[[#fnm7][7]]} 10b.18: Vgl. die Anmerkung zu 4,27.

^{[[#fnm8][8]]} ℘ 6,22

^{[[#fnm9][9]]} ℘ 16,10-13

^{[[#fnm10][10]]} ℘ Jes 6,9f

^{[[#fnm11][11]]} ℘ Dtn 32,15

^{[[#fnm12][12]]} ℘ 5,9
