:PROPERTIES:
:ID:       b506383f-18c7-45fd-9624-5807d9f390aa
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_40.html][40]] [[file:Jer_41.html][41]] *42*
[[file:Jer_43.html][43]] [[file:Jer_44.html][44]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 42
  :PROPERTIES:
  :CUSTOM_ID: jer-42
  :END:

<<verses>>

<<v1>>
**** Die Bitte um ein Gotteswort: 42,1-6
     :PROPERTIES:
     :CUSTOM_ID: die-bitte-um-ein-gotteswort-421-6
     :END:
1 Da kamen alle Truppenführer und Johanan, der Sohn Kareachs, ferner
Asarja, der Sohn Haschajas, sowie das ganze Volk, Klein und Groß, herbei

<<v2>>
2 und sagten zum Propheten Jeremia: Möge unsere Bitte bei dir Gehör
finden: Bete für uns zum Herrn, deinem Gott, für diesen ganzen Rest;
denn von einst so vielen sind nur wir wenige übrig geblieben, wie du mit
eigenen Augen siehst.

<<v3>>
3 Möge der Herr, dein Gott, uns kundtun, welchen Weg wir einschlagen und
was wir tun sollen.

<<v4>>
4 Der Prophet Jeremia erwiderte ihnen: Gut, ich will nach eurem Wunsch
zum Herrn, eurem Gott, beten und euch dann alles, was der Herr
antwortet, mitteilen, ohne euch ein Wort vorzuenthalten.

<<v5>>
5 Sie selbst versicherten Jeremia: Der Herr sei ein wahrer und treuer
Zeuge gegen uns, wenn wir nicht genau nach dem Wort handeln, mit dem
dich der Herr, dein Gott, zu uns sendet.

<<v6>>
6 Sei es gut oder schlimm, auf die Stimme des Herrn, unseres Gottes, zu
dem wir dich senden, werden wir hören, damit es uns gut gehe, weil wir
auf die Stimme des Herrn, unseres Gottes, hören.\\
\\

<<v7>>
**** Die Warnung vor der Auswanderung nach Ägypten: 42,7-18
     :PROPERTIES:
     :CUSTOM_ID: die-warnung-vor-der-auswanderung-nach-ägypten-427-18
     :END:
7 Zehn Tage später erging das Wort des Herrn an Jeremia.

<<v8>>
8 Daraufhin rief er Johanan, den Sohn Kareachs, und alle Truppenführer,
die bei ihm waren, sowie das ganze Volk, Klein und Groß, zusammen

<<v9>>
9 und sagte zu ihnen: So spricht der Herr, der Gott Israels, zu dem ihr
mich gesandt habt, um ihm eure Bitte vorzutragen:

<<v10>>
10 Wenn ihr in diesem Land wohnen bleibt, so werde ich euch aufbauen und
nicht niederreißen, euch einpflanzen und nicht ausreißen; ja, ich bereue
das Unheil, das ich euch angetan habe. ^{[[#fn1][1]]}

<<v11>>
11 Fürchtet euch nicht vor dem König von Babel, vor dem ihr Angst habt.
Fürchtet euch nicht vor ihm - Spruch des Herrn -; denn ich bin mit euch,
um euch zu retten und seiner Hand zu entreißen.

<<v12>>
12 Ich bewirke Erbarmen für euch; er wird sich euer erbarmen und euch in
eure Heimat zurückkehren lassen.

<<v13>>
13 Wenn ihr aber sagt: Wir bleiben nicht in diesem Land!, und auf die
Stimme des Herrn, eures Gottes, nicht hört,

<<v14>>
14 sondern sagt: Nein, nach Ägypten wollen wir ziehen, wo wir weder
Krieg sehen noch Trompetenschall hören, noch nach Brot hungern werden,
und dort wollen wir bleiben!,

<<v15>>
15 nun, dann hört das Wort des Herrn, ihr, der Rest Judas: So spricht
der Herr der Heere, der Gott Israels: Wenn ihr darauf besteht, nach
Ägypten zu ziehen, und auswandert, um euch dort niederzulassen,

<<v16>>
16 dann wird euch das Schwert, das ihr fürchtet, dort in Ägypten
erreichen und der Hunger, vor dem euch bangt, wird euch dort in Ägypten
verfolgen und ihr werdet dort umkommen.

<<v17>>
17 Ja, alle, die darauf bestehen, nach Ägypten zu ziehen, um sich dort
niederzulassen, werden durch Schwert, Hunger und Pest umkommen. Keiner
von ihnen wird entkommen, keiner dem Unheil entrinnen, das ich über sie
bringe.

<<v18>>
18 Denn so spricht der Herr der Heere, der Gott Israels: Wie sich mein
Zorn und Grimm über die Einwohner Jerusalems ergossen hat, so wird sich
mein Grimm auch über euch ergießen, wenn ihr nach Ägypten zieht. Ihr
werdet zum Fluch und zu einem Bild des Entsetzens, zur Verwünschung und
zur Schmach werden. Dieses Land aber werdet ihr nie wieder sehen.
^{[[#fn2][2]]}\\
\\

<<v19>>
**** Die Drohung an die Verstockten: 42,19-22
     :PROPERTIES:
     :CUSTOM_ID: die-drohung-an-die-verstockten-4219-22
     :END:
19 Der Herr hat zu euch gesprochen, Rest Judas: Zieht nicht nach
Ägypten! Ihr sollt genau wissen: Ich warne euch heute. ^{[[#fn3][3]]}

<<v20>>
20 Denn ihr gebt euch einer gefährlichen Täuschung hin. Ihr selbst habt
mich ja zum Herrn, eurem Gott, gesandt mit den Worten: Bete für uns zum
Herrn, unserem Gott, und ganz wie der Herr, unser Gott, spricht, gib uns
Bescheid und wir werden danach handeln.

<<v21>>
21 Heute nun habe ich euch den Bescheid gegeben, aber ihr habt auf die
Stimme des Herrn, eures Gottes, nicht gehört, auf nichts von dem, womit
er mich zu euch gesandt hat.

<<v22>>
22 Jetzt aber sollt ihr wissen: Durch Schwert, Hunger und Pest werdet
ihr umkommen an dem Ort, wohin ihr ziehen wollt, um euch dort
niederzulassen.\\
\\

^{[[#fnm1][1]]} ℘ 1,10

^{[[#fnm2][2]]} ℘ 25,9

^{[[#fnm3][3]]} 19-22: Dem Zusammenhang nach wohl ursprünglich Antwort
auf die Ablehnung des Gotteswortes in 43,1-3.
