:PROPERTIES:
:ID:       9521a7bb-111a-423d-98b1-94c4c0d2e0a3
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_4.html][4]] [[file:Jer_5.html][5]] *6* [[file:Jer_7.html][7]]
[[file:Jer_8.html][8]] ... [[file:Jer_52.html][52]]

--------------

* Jer 6
  :PROPERTIES:
  :CUSTOM_ID: jer-6
  :END:

<<verses>>

<<v1>>
**** Die Kriegsgefahr als Strafe: 6,1-15
     :PROPERTIES:
     :CUSTOM_ID: die-kriegsgefahr-als-strafe-61-15
     :END:
1 Flieht, ihr Leute von Benjamin, /\\
 hinaus aus Jerusalem! Stoßt in Tekoa in die Trompete /\\
 und richtet über Bet-Kerem ein Zeichen auf! Denn von Norden droht
Unheil /\\
 und großes Verderben. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Die Schöne und Verwöhnte, /\\
 die Tochter Zion, ich vernichte sie.\\
\\

<<v3>>
3 Hirten kommen zu ihr mit ihren Herden; /\\
 sie schlagen rings um sie ihre Zelte auf, /\\
 jeder weidet seinen Bereich ab. ^{[[#fn2][2]]}\\
\\

<<v4>>
4 Ruft gegen Zion den Heiligen Krieg aus! /\\
 Auf! Greifen wir an am Mittag! - Weh uns: Schon neigt sich der Tag, /\\
 die Abendschatten strecken sich.\\
\\

<<v5>>
5 Auf! Greifen wir an in der Nacht, /\\
 zerstören wir ihre Paläste!\\
\\

<<v6>>
6 Denn so spricht der Herr der Heere: Fällt ihre Bäume /\\
 und werft einen Wall auf gegen Jerusalem! Das ist die Stadt, von der
erwiesen ist: /\\
 Alles in ihr ist Unterdrückung.\\
\\

<<v7>>
7 Wie ein Brunnen sein Wasser sprudeln lässt, /\\
 so lässt sie ihre Schlechtigkeit sprudeln. Von Gewalttat und Unrecht
hört man in ihr; /\\
 ständig sind mir vor Augen Leid und Misshandlung.\\
\\

<<v8>>
8 Lass dich warnen, Jerusalem, /\\
 sonst trenne ich mich von dir, sonst mache ich dich zur Wüste, /\\
 zum Land ohne Bewohner.\\
\\

<<v9>>
9 So spricht der Herr der Heere: Genaue Nachlese wie am Weinstock /\\
 soll man halten am Rest Israels. Leg deine Hand an /\\
 wie ein Winzer an die Reben!\\
\\

<<v10>>
10 Zu wem soll ich reden /\\
 und wer wird mich hören, wenn ich mahne? Ihr Ohr ist ja unbeschnitten,
/\\
 sie können nichts vernehmen. Das Wort des Herrn dient ihnen zum Spott;
/\\
 es gefällt ihnen nicht.\\
\\

<<v11>>
11 Darum bin ich erfüllt vom Zorn des Herrn, /\\
 bin es müde, ihn länger zurückzuhalten. - Gieß ihn aus über das Kind
auf der Straße /\\
 und zugleich über die Schar der jungen Männer! Ja, alle werden gefangen
genommen, /\\
 Mann und Frau, Greis und Hochbetagter.\\
\\

<<v12>>
12 Ihre Häuser gehen an andere über, /\\
 die Felder und auch die Frauen. Denn ich strecke meine Hand aus /\\
 gegen die Bewohner des Landes - Spruch des Herrn.\\
\\

<<v13>>
13 Sie sind doch alle, vom Kleinsten bis zum Größten, /\\
 nur auf Gewinn aus; vom Propheten bis zum Priester /\\
 betrügen sie alle. ^{[[#fn3][3]]}\\
\\

<<v14>>
14 Den Schaden meines Volkes möchten sie leichthin heilen, indem sie
rufen: /\\
 Heil, Heil! Aber kein Heil ist da.\\
\\

<<v15>>
15 Schämen müssten sie sich, /\\
 weil sie Gräuel verüben. Doch sie schämen sich nicht; /\\
 Scham ist ihnen unbekannt. Deshalb müssen sie fallen, /\\
 wenn die anderen fallen. Sobald ich sie zur Rechenschaft ziehe, /\\
 werden sie stürzen, spricht der Herr.\\
\\

<<v16>>
**** Jerusalems Trotz: 6,16-26
     :PROPERTIES:
     :CUSTOM_ID: jerusalems-trotz-616-26
     :END:
16 So spricht der Herr: Stellt euch an die Wege und haltet Ausschau, /\\
 fragt nach den Pfaden der Vorzeit, fragt, wo der Weg zum Guten liegt;
/\\
 geht auf ihm, so werdet ihr Ruhe finden für eure Seele. /\\
 Sie aber sagten: Wir gehen nicht.\\
\\

<<v17>>
17 Auch habe ich Wächter für euch aufgestellt: /\\
 Achtet auf den Schall der Trompete! /\\
 Sie aber sagten: Wir achten nicht darauf.\\
\\

<<v18>>
18 Darum hört, ihr Völker, und erkennt, /\\
 was ich ihnen antun will.\\
\\

<<v19>>
19 Höre es, Erde! /\\
 Schon bringe ich Unheil über dieses Volk /\\
 als die Frucht seiner bösen Gesinnung. Denn auf meine Worte haben sie
nicht geachtet /\\
 und meine Weisung haben sie verschmäht. ^{[[#fn4][4]]}\\
\\

<<v20>>
20 Was soll mir der Weihrauch aus Saba /\\
 und das gute Gewürzrohr aus fernem Land? Eure Brandopfer gefallen mir
nicht, /\\
 eure Schlachtopfer sind mir nicht angenehm. ^{[[#fn5][5]]}\\
\\

<<v21>>
21 Darum - so spricht der Herr: Ich lege diesem Volk Hindernisse in den
Weg, /\\
 sodass sie darüber straucheln. Väter und Söhne zusammen, /\\
 einer wie der andere geht zugrunde.\\
\\

<<v22>>
22 So spricht der Herr: Seht, ein Volk zieht vom Nordland heran, /\\
 ein großes Volk bricht auf /\\
 von den Grenzen der Erde. ^{[[#fn6][6]]}\\
\\

<<v23>>
23 Sie kommen mit Bogen und Sichelschwert, /\\
 grausam sind sie und ohne Erbarmen. Ihr Lärm gleicht dem Brausen des
Meeres /\\
 und sie reiten auf Rossen, Krieger, zum Kampf gerüstet /\\
 gegen dich, Tochter Zion.\\
\\

<<v24>>
24 Kaum hörten wir diese Nachricht, /\\
 da erschlafften uns die Hände, es packte uns die Angst, /\\
 das Zittern wie eine Gebärende.\\
\\

<<v25>>
25 Geht nicht aufs Feld hinaus, /\\
 macht euch nicht auf den Weg; /\\
 denn der Feind greift zum Schwert - Grauen ringsum!\\
\\

<<v26>>
26 Tochter, mein Volk, leg das Trauerkleid an /\\
 und wälz dich im Staub! Halte Trauer wie um den einzigen Sohn,
bitterste Klage: /\\
 «Ach, jählings kam über uns der Verwüster.» ^{[[#fn7][7]]}\\
\\

<<v27>>
**** Der Prophet als Prüfer des Volkes: 6,27-30
     :PROPERTIES:
     :CUSTOM_ID: der-prophet-als-prüfer-des-volkes-627-30
     :END:
27 Zum Prüfer für mein Volk habe ich dich bestellt [zum Metallprüfer];
/\\
 du sollst sein Verhalten erkennen und prüfen.\\
\\

<<v28>>
28 Sie alle sind schlimme Empörer, /\\
 Verleumder sind sie, Bronze und Eisen sind sie, /\\
 alle zusammen Verbrecher.\\
\\

<<v29>>
29 Der Blasebalg schnaubt, /\\
 doch das Blei bleibt unberührt vom Feuer. Umsonst versucht der
Schmelzer zu schmelzen; /\\
 die Bösen lassen sich nicht ausscheiden.\\
\\

<<v30>>
30 «Verworfenes Silber» nennt man sie; /\\
 denn verworfen hat sie der Herr.\\
\\

^{[[#fnm1][1]]} ℘ 4,6

^{[[#fnm2][2]]} «Hirten» und «Herden» sind die mit Nebukadnezzar
verbündeten Könige und deren Heere.

^{[[#fnm3][3]]} ℘ 8,10-12

^{[[#fnm4][4]]} ℘ Jes 1,2

^{[[#fnm5][5]]} ℘ Ps 40,7

^{[[#fnm6][6]]} ℘ 50,41-43

^{[[#fnm7][7]]} ℘ Am 8,10
