:PROPERTIES:
:ID:       9ef05ac5-fbd9-4fe2-9145-c3453ff1f1dc
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_34.html][34]] [[file:Jer_35.html][35]] *36*
[[file:Jer_37.html][37]] [[file:Jer_38.html][38]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 36
  :PROPERTIES:
  :CUSTOM_ID: jer-36
  :END:

<<verses>>

<<v1>>
** Die Berichte Baruchs: 36,1 - 45,5
   :PROPERTIES:
   :CUSTOM_ID: die-berichte-baruchs-361---455
   :END:
**** Die Verbrennung der Buchrolle: 36,1-32
     :PROPERTIES:
     :CUSTOM_ID: die-verbrennung-der-buchrolle-361-32
     :END:
1 Im vierten Jahr Jojakims, des Sohnes Joschijas, des Königs von Juda,
erging vom Herrn dieses Wort an Jeremia: ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Nimm dir eine Buchrolle und schreib darauf alle Worte, die ich zu dir
über Israel und Juda und über alle Völker gesprochen habe, seitdem ich
zu dir rede, von den Tagen Joschijas an bis heute. ^{[[#fn3][3]]}

<<v3>>
3 Vielleicht werden die Leute vom Haus Juda, wenn sie hören, wie viel
Unheil ich ihnen antun will, umkehren von ihrem bösen Weg und ich kann
ihnen Schuld und Sünde verzeihen. ^{[[#fn4][4]]}

<<v4>>
4 Da rief Jeremia Baruch, den Sohn Nerijas, und Baruch schrieb nach dem
Diktat Jeremias alle Worte, die der Herr zu ihm gesprochen hatte, auf
eine Buchrolle.

<<v5>>
5 Jeremia gab hierauf Baruch folgenden Auftrag: Mir ist es verwehrt, das
Haus des Herrn zu betreten. ^{[[#fn5][5]]}

<<v6>>
6 Darum geh du hin und lies am Fasttag aus der Rolle, die du nach meinem
Diktat geschrieben hast, dem Volk im Haus des Herrn die Worte des Herrn
vor. Auch allen Judäern, die aus ihren Städten herbeiströmen, sollst du
sie vorlesen.

<<v7>>
7 Vielleicht flehen sie vor dem Herrn um Erbarmen und kehren um, jeder
von seinem bösen Weg; denn groß ist der Zorn und Grimm, den der Herr
diesem Volk angedroht hat.

<<v8>>
8 Baruch, der Sohn Nerijas, handelte genau nach dem Auftrag des
Propheten Jeremia und las im Haus des Herrn die Worte des Herrn aus dem
Buch vor.

<<v9>>
9 Im fünften Jahr Jojakims, des Sohnes Joschijas, des Königs von Juda,
hatte man im neunten Monat alles Volk in Jerusalem und alle Leute, die
von den Städten Judas nach Jerusalem kommen sollten, zu einem Fasten vor
dem Herrn aufgerufen.

<<v10>>
10 Nun las Baruch im Haus des Herrn dem ganzen Volk aus dem Buch die
Worte Jeremias vor, und zwar in der Halle Gemarjas, des Sohnes des
Staatsschreibers Schafan, im oberen Vorhof am Eingang des Neuen
Tempeltores.

<<v11>>
11 Als Micha, der Sohn Gemarjas, des Sohnes Schafans, alle Worte des
Herrn aus dem Buch vernommen hatte,

<<v12>>
12 ging er hinab in den Königspalast zur Halle des Staatsschreibers.
Dort waren gerade alle hohen Beamten zu einer Sitzung versammelt: der
Staatsschreiber Elischama, Delaja, der Sohn Schemajas, Elnatan, der Sohn
Achbors, Gemarja, der Sohn Schafans, Zidkija, der Sohn Hananjas, und
alle sonstigen Beamten.

<<v13>>
13 Micha teilte ihnen alle Worte mit, die er gehört hatte, als Baruch
dem Volk aus dem Buch vorlas.

<<v14>>
14 Da schickten die versammelten Beamten Jehudi, den Sohn Netanjas, des
Sohnes Schelemjas, des Sohnes Kuschis, zu Baruch und ließen ihm sagen:
Nimm die Rolle, aus der du dem Volk vorgelesen hast, und komm hierher!
Sogleich nahm Baruch, der Sohn Nerijas, die Rolle und ging zu ihnen.

<<v15>>
15 Sie sagten zu ihm: Setz dich und lies sie uns vor! Nun las ihnen
Baruch vor.

<<v16>>
16 Als sie all die Worte hörten, schauten sie einander erschrocken an
und sagten [zu Baruch]: Wir müssen das alles dem König mitteilen.

<<v17>>
17 Sie fragten Baruch: Sag uns doch, wie hast du alle diese Worte
niedergeschrieben?

<<v18>>
18 Baruch erwiderte ihnen: Jeremia hat mir alle diese Worte diktiert und
ich habe sie mit Tinte in das Buch geschrieben.

<<v19>>
19 Darauf sagten die Beamten zu Baruch: Geh und verbirg dich, du und
auch Jeremia! Niemand soll wissen, wo ihr seid.

<<v20>>
20 Dann begaben sie sich zum König in den Palasthof, nachdem sie die
Rolle in der Halle des Staatsschreibers Elischama verwahrt hatten, und
berichteten das alles dem König.

<<v21>>
21 Da gab der König dem Jehudi den Auftrag, die Rolle zu holen, und
dieser holte sie aus der Halle des Staatsschreibers Elischama. Und
Jehudi las sie dem König vor und allen Beamten, die um den König
herumstanden.

<<v22>>
22 Der König wohnte im Winterhaus, es war ja der neunte Monat, und vor
ihm brannte das Feuer auf dem Kohlenbecken.

<<v23>>
23 Sooft nun Jehudi drei oder vier Spalten gelesen hatte, schnitt sie
der König mit dem Schreibermesser ab und warf sie in das Feuer auf dem
Kohlenbecken, bis das Feuer auf dem Kohlenbecken die ganze Rolle
verzehrt hatte.

<<v24>>
24 Niemand erschrak und niemand zerriss seine Kleider, weder der König
noch irgendeiner seiner Diener, die all diese Worte gehört hatten.
^{[[#fn6][6]]}

<<v25>>
25 Selbst als Elnatan, Delaja und Gemarja den König bestürmten, die
Rolle nicht zu verbrennen, hörte er nicht auf sie.

<<v26>>
26 Vielmehr befahl der König dem Prinzen Jerachmeël, ferner Seraja, dem
Sohn Asriëls, und Schelemja, dem Sohn Abdeëls, den Schreiber Baruch und
den Propheten Jeremia festzunehmen; aber der Herr hielt sie verborgen.

<<v27>>
27 Nachdem der König die Rolle mit den Worten, die Baruch nach dem
Diktat Jeremias niedergeschrieben hat, verbrannt hatte, erging das Wort
des Herrn an Jeremia:

<<v28>>
28 Nimm dir eine andere Rolle und schreib all die früheren Worte darauf,
die auf der ersten Rolle standen, die Jojakim, der König von Juda,
verbrannt hat.

<<v29>>
29 Über Jojakim aber, den König von Juda, sollst du sagen: So spricht
der Herr: Du hast diese Rolle verbrannt und gesagt: Warum hast du darin
geschrieben, der König von Babel werde bestimmt kommen, dieses Land
verheeren und Mensch und Vieh darin vernichten?

<<v30>>
30 Darum - so spricht der Herr über Jojakim, den König von Juda: Er wird
keinen Nachkommen mehr haben, der auf dem Thron Davids sitzt, und sein
Leichnam soll weggeworfen werden und der Hitze des Tags und der Kälte
der Nacht ausgesetzt sein. ^{[[#fn7][7]]}

<<v31>>
31 Ich ziehe ihn, seine Nachkommen und seine Diener zur Rechenschaft für
ihre Schuld. Ich bringe über sie, über die Einwohner Jerusalems und die
Leute von Juda all das Unheil, das ich ihnen angedroht habe, ohne dass
sie hören wollten.

<<v32>>
32 Da nahm Jeremia eine andere Rolle und übergab sie dem Schreiber
Baruch, dem Sohn Nerijas. Dieser schrieb auf sie nach dem Diktat
Jeremias alle Worte des Buches, das Jojakim, der König von Juda, im
Feuer verbrannt hatte. Ihnen wurden noch viele ähnliche Worte
hinzugefügt.\\
\\

^{[[#fnm1][1]]} ℘ 25,1

^{[[#fnm2][2]]} Es ist das Jahr 605 v. Chr. - Man sieht, dass die
einzelnen Abschnitte nicht chronologisch, sondern sachlich geordnet
sind. Vorher waren bereits Ereignisse berichtet, die viel später
geschehen sind.

^{[[#fnm3][3]]} ℘ 25,3

^{[[#fnm4][4]]} ℘ 26,3

^{[[#fnm5][5]]} Jeremia hatte wahrscheinlich vom König Redeverbot
erhalten; vielleicht war das Prophetenwort 22,18f vorausgegangen.

^{[[#fnm6][6]]} ℘ 2 Kön 22,11

^{[[#fnm7][7]]} ℘ 22,19
