:PROPERTIES:
:ID:       4e006e5f-646d-4139-b38f-01114159cd8d
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_9.html][9]] [[file:Jer_10.html][10]] *11*
[[file:Jer_12.html][12]] [[file:Jer_13.html][13]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 11
  :PROPERTIES:
  :CUSTOM_ID: jer-11
  :END:

<<verses>>

<<v1>>
**** Der gebrochene Bund: 11,1-17
     :PROPERTIES:
     :CUSTOM_ID: der-gebrochene-bund-111-17
     :END:
1 Das Wort, das vom Herrn an Jeremia erging:

<<v2>>
2 Hört die Worte dieses Bundes! Du sollst sie den Leuten von Juda und
den Einwohnern Jerusalems verkünden.

<<v3>>
3 Du sollst ihnen sagen: So spricht der Herr, der Gott Israels:
Verflucht der Mensch, der nicht hört auf die Worte dieses Bundes,

<<v4>>
4 die ich euren Vätern aufgetragen habe, als ich sie aus Ägypten
herausführte, aus dem Schmelzofen des Eisens: Hört auf meine Stimme, und
handelt in allem nach meinen Geboten; dann werdet ihr mein Volk sein und
ich will euer Gott sein. ^{[[#fn1][1]]}

<<v5>>
5 Nur so kann ich den Eid halten, den ich euren Vätern geschworen habe:
ihnen ein Land zu geben, in dem Milch und Honig fließen, wie ihr es
heute habt. Ich antwortete: Ja, Herr.

<<v6>>
6 Darauf sprach der Herr zu mir: Verkünde alle diese Worte laut in den
Städten Judas und auf den Straßen Jerusalems: Hört die Worte dieses
Bundes und handelt danach!

<<v7>>
7 Denn ich habe eure Väter, schon als ich sie aus Ägypten heraufführte
und bis zum heutigen Tag, immer wieder beschworen: Hört auf meine
Stimme! ^{[[#fn2][2]]}

<<v8>>
8 Sie aber haben nicht gehört und mir ihr Ohr nicht zugeneigt; alle
folgten dem Trieb ihres bösen Herzens. So musste ich an ihnen alle Worte
dieses Bundes erfüllen, den zu halten ich ihnen geboten habe, den sie
aber nicht gehalten haben. ^{[[#fn3][3]]}

<<v9>>
9 Der Herr sagte zu mir: Es gibt eine Verschwörung unter den Leuten von
Juda und den Einwohnern Jerusalems.

<<v10>>
10 Sie sind zurückgekehrt zu den Sünden ihrer Väter, die sich weigerten,
meinen Worten zu gehorchen. Auch sie sind fremden Göttern nachgelaufen,
um ihnen zu dienen. Das Haus Israel und das Haus Juda haben meinen Bund
gebrochen, den ich mit ihren Vätern geschlossen habe.

<<v11>>
11 Darum - so spricht der Herr: Jetzt bringe ich Unheil über sie, dem
sie nicht entgehen können. Schreien sie dann zu mir, so werde ich nicht
auf sie hören.

<<v12>>
12 Wenn aber die Städte Judas und die Einwohner Jerusalems hingehen und
zu den Göttern schreien, denen sie Opfer darbringen, dann werden diese
zur Zeit der Not ihnen ganz gewiss nicht helfen können.

<<v13>>
13 Denn so zahlreich wie deine Städte sind auch deine Götter, Juda, und
so zahlreich wie die Straßen Jerusalems sind die schändlichen Altäre,
die ihr errichtet habt, um dem Baal zu opfern. ^{[[#fn4][4]]}

<<v14>>
14 Du aber bete nicht für dieses Volk! Fang nicht an, für sie zu flehen
und zu bitten. Denn ich höre nicht, wenn du zu mir rufst wegen ihrer
Not. ^{[[#fn5][5]]}

<<v15>>
15 Was hat mein Liebling in meinem Haus zu suchen, wenn er nur Schlimmes
verübt? Können Zehnt und Opferfleisch das Unheil von dir fernhalten,
sodass du dann jubeln könntest?

<<v16>>
16 Einen üppigen Ölbaum von schöner Gestalt hatte der Herr dich genannt.
Wenn der gewaltige (Kriegs-)Lärm ertönt, legt er Feuer an ihn, sodass
seine Zweige hässlich werden.

<<v17>>
17 Der Herr der Heere, der dich pflanzte, hat Unheil über dich verhängt
wegen der bösen Taten, die das Haus Israel und das Haus Juda verübten;
dem Baal opferten sie, um mich zu erzürnen.\\
\\

<<v18>>
**** Die Mordpläne gegen Jeremia: 11,18-23
     :PROPERTIES:
     :CUSTOM_ID: die-mordpläne-gegen-jeremia-1118-23
     :END:
18 Der Herr ließ es mich wissen und so wusste ich es; damals ließest du
mich ihr Treiben durchschauen.

<<v19>>
19 Ich selbst war wie ein zutrauliches Lamm, das zum Schlachten geführt
wird, und ahnte nicht, dass sie gegen mich Böses planten: Wir wollen den
Baum im Saft verderben; wir wollen ihn ausrotten aus dem Land der
Lebenden, sodass man seinen Namen nicht mehr erwähnt. ^{[[#fn6][6]]}

<<v20>>
20 Aber der Herr der Heere richtet gerecht, er prüft Herz und Nieren.
Ich werde sehen, wie du Rache an ihnen nimmst; denn dir habe ich meine
Sache anvertraut. ^{[[#fn7][7]]}

<<v21>>
21 Darum - so spricht der Herr gegen die Leute von Anatot, die mir nach
dem Leben trachten und sagen: Du darfst nicht als Prophet im Namen des
Herrn auftreten, wenn du nicht durch unsere Hand sterben willst.

<<v22>>
22 Darum - so spricht der Herr der Heere: Seht, ich werde sie zur
Rechenschaft ziehen. Die jungen Männer sterben durchs Schwert, ihre
Söhne und Töchter sterben vor Hunger.

<<v23>>
23 So wird den Leuten von Anatot kein Rest mehr bleiben, wenn ich Unheil
über sie bringe, das Jahr ihrer Bestrafung.\\
\\

^{[[#fnm1][1]]} ℘ Lev 26,12; Dtn 26,17f

^{[[#fnm2][2]]} ℘ (7-8) 7,25f

^{[[#fnm3][3]]} ℘ 18,12; 25,4

^{[[#fnm4][4]]} ℘ 2,28

^{[[#fnm5][5]]} ℘ 7,16; 14,11

^{[[#fnm6][6]]} ℘ Jes 53,7

^{[[#fnm7][7]]} ℘ 20,12; Ps 7,10
