:PROPERTIES:
:ID:       064227e7-86c6-409e-80d8-ebb22753f3a7
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_12.html][12]] [[file:Jer_13.html][13]] *14*
[[file:Jer_15.html][15]] [[file:Jer_16.html][16]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 14
  :PROPERTIES:
  :CUSTOM_ID: jer-14
  :END:

<<verses>>

<<v1>>
**** Die große Dürre: 14,1-9
     :PROPERTIES:
     :CUSTOM_ID: die-große-dürre-141-9
     :END:
1 Das Wort des Herrn erging an Jeremia wegen der großen Dürre:\\
\\

<<v2>>
2 Juda ist ausgedörrt; /\\
 seine Tore verfallen, sie sinken trauernd zu Boden /\\
 und Jerusalems Klageschrei steigt empor. ^{[[#fn1][1]]}\\
\\

<<v3>>
3 Die Vornehmen schicken ihre Diener nach Wasser; /\\
 sie kommen zu den Brunnen, /\\
 finden aber kein Wasser; sie kehren mit leeren Krügen zurück. /\\
 [Sie sind bestürzt und enttäuscht /\\
 und verhüllen ihr Haupt.] ^{[[#fn2][2]]}\\
\\

<<v4>>
4 Die Bauern sind um den Ackerboden besorgt; /\\
 denn es fiel kein Regen im Land. Sie sind bestürzt /\\
 und verhüllen ihr Haupt.\\
\\

<<v5>>
5 Selbst die Hirschkuh im Feld /\\
 lässt ihr Junges im Stich, /\\
 weil kein Grün mehr da ist.\\
\\

<<v6>>
6 Die Wildesel stehen auf den kahlen Höhen; /\\
 sie schnappen nach Luft wie Schakale. Ihre Augen erlöschen; /\\
 denn nirgends ist Gras.\\
\\

<<v7>>
7 Unsre Sünden klagen uns an. /\\
 Doch um deines Namens willen handle, o Herr! Ja, zahlreich sind unsre
Vergehen; /\\
 gegen dich haben wir gesündigt.\\
\\

<<v8>>
8 Du, Israels Hoffnung, /\\
 sein Retter zur Zeit der Not, warum bist du wie ein Fremder im Land /\\
 und wie ein Wanderer, der nur über Nacht einkehrt?\\
\\

<<v9>>
9 Warum bist du wie ein ratloser Mann, /\\
 wie ein Krieger, der nicht zu siegen vermag? Du bist doch in unsrer
Mitte, Herr, /\\
 und dein Name ist über uns ausgerufen. /\\
 Verlass uns nicht!\\
\\

<<v10>>
**** Von Gott verworfen: 14,10-18
     :PROPERTIES:
     :CUSTOM_ID: von-gott-verworfen-1410-18
     :END:
10 So spricht der Herr von diesem Volk: Haltlos hin und her zu
schweifen, das lieben sie; ihren Füßen gönnen sie keine Ruhe. Doch der
Herr hat kein Gefallen an ihnen. Jetzt denkt er an ihre Schuld und
straft ihre Sünden.

<<v11>>
11 Und der Herr sprach zu mir: Bete nicht um das Wohlergehen dieses
Volkes! ^{[[#fn3][3]]}

<<v12>>
12 Auch wenn sie fasten, höre ich nicht auf ihr Flehen; wenn sie
Brandopfer und Speiseopfer darbringen, habe ich kein Gefallen an ihnen.
Durch Schwert, Hunger und Pest mache ich ihnen ein Ende.

<<v13>>
13 Da sagte ich: Ach, Herr und Gott, die Propheten sagen doch zu ihnen:
Ihr werdet das Schwert nicht sehen, der Hunger wird nicht über euch
kommen, sondern beständiges Heil gewähre ich euch an diesem Ort.

<<v14>>
14 Aber der Herr erwiderte mir: Lüge ist, was die Propheten in meinem
Namen verkünden. Ich habe sie weder gesandt noch beauftragt, ich habe
nicht zu ihnen gesprochen. Erlogene Visionen, leere Wahrsagerei und
selbst erdachten Betrug verkünden sie euch. ^{[[#fn4][4]]}

<<v15>>
15 Darum spreche ich, der Herr, so gegen die Propheten, die in meinem
Namen weissagen, obwohl ich sie nicht gesandt habe, und die behaupten,
Schwert und Hunger werde es nicht geben in diesem Land: Durch Schwert
und Hunger werden diese Propheten enden.

<<v16>>
16 Die Leute aber, denen sie weissagen, werden auf den Straßen
Jerusalems liegen, hingestreckt durch Hunger und Schwert. Niemand wird
sie begraben, sie, ihre Frauen, Söhne und Töchter. So gieße ich das
verdiente Unheil über sie aus.\\
\\

<<v17>>
17 Du sollst zu ihnen dieses Wort sagen: Meine Augen fließen über von
Tränen /\\
 bei Tag und bei Nacht /\\
 und finden keine Ruhe. Denn großes Verderben brach herein /\\
 über die Jungfrau, die Tochter, mein Volk, /\\
 eine unheilbare Wunde. ^{[[#fn5][5]]}\\
\\

<<v18>>
18 Gehe ich aufs Feld hinaus - /\\
 seht, vom Schwert Durchbohrte! Komme ich in die Stadt - /\\
 seht, vom Hunger Gequälte! Ja, auch Propheten und Priester werden
verschleppt /\\
 in ein Land, das sie nicht kennen.\\
\\

<<v19>>
**** Die Klage des Volkes: 14,19-22
     :PROPERTIES:
     :CUSTOM_ID: die-klage-des-volkes-1419-22
     :END:
19 Hast du denn Juda ganz verworfen, /\\
 wurde dir Zion zum Abscheu? Warum hast du uns so geschlagen, /\\
 dass es für uns keine Heilung mehr gibt? Wir hofften auf Heil, /\\
 doch kommt nichts Gutes, auf die Zeit der Heilung, /\\
 doch ach, nur Schrecken! ^{[[#fn6][6]]}\\
\\

<<v20>>
20 Wir erkennen, Herr, unser Unrecht, /\\
 die Schuld unsrer Väter: /\\
 Ja, wir haben gegen dich gesündigt.\\
\\

<<v21>>
21 Um deines Namens willen verschmäh nicht, /\\
 verstoß nicht den Thron deiner Herrlichkeit! Gedenke deines Bundes mit
uns /\\
 und löse ihn nicht!\\
\\

<<v22>>
22 Gibt es etwa Regenspender /\\
 unter den Götzen der Völker? Oder ist es der Himmel, der von selbst
regnen lässt? /\\
 Bist nicht du es, Herr, unser Gott? Wir setzen unsre Hoffnung auf dich;
/\\
 denn du hast dies alles gemacht.\\
\\

^{[[#fnm1][1]]} ℘ Joël 1,10-12

^{[[#fnm2][2]]} Das Eingeklammerte fehlt in G; irrtümliche
Doppelschreibung für V. 4cd.

^{[[#fnm3][3]]} ℘ 7,16; 11,14

^{[[#fnm4][4]]} ℘ 27,14f; 29,8f

^{[[#fnm5][5]]} ℘ 13,17

^{[[#fnm6][6]]} ℘ 8,15
