:PROPERTIES:
:ID:       4e4bc8cb-b21a-45bc-aad3-8291ce09cc5d
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_13.html][13]] [[file:Jer_14.html][14]] *15*
[[file:Jer_16.html][16]] [[file:Jer_17.html][17]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 15
  :PROPERTIES:
  :CUSTOM_ID: jer-15
  :END:

<<verses>>

<<v1>>
**** Das unabänderliche Strafgericht: 15,1-4
     :PROPERTIES:
     :CUSTOM_ID: das-unabänderliche-strafgericht-151-4
     :END:
1 Doch der Herr sprach zu mir: Selbst wenn Mose und Samuel vor mein
Angesicht träten, würde sich mein Herz diesem Volk nicht mehr zuneigen.
Schaff sie mir aus den Augen, sie sollen gehen.

<<v2>>
2 Fragen sie dich dann: Wohin sollen wir gehen?, so sag ihnen: So
spricht der Herr: Wer der Pest verfallen ist, zur Pest! Wer dem Schwert,
zum Schwert! Wer dem Hunger, zum Hunger! Wer der Gefangenschaft, zur
Gefangenschaft! ^{[[#fn1][1]]}

<<v3>>
3 Vier Plagen biete ich gegen sie auf - Spruch des Herrn: Das Schwert
zum Morden, die Hunde zum Fortschleifen, die Vögel des Himmels und die
Tiere des Feldes zum Fressen und Vertilgen. ^{[[#fn2][2]]}

<<v4>>
4 Ich mache sie zu einem Bild des Schreckens für alle Reiche der Erde
wegen des Manasse, des Sohnes Hiskijas, des Königs von Juda, zur Strafe
für das, was er in Jerusalem verübt hat. ^{[[#fn3][3]]}\\
\\

<<v5>>
**** Jerusalems Ende: 15,5-9
     :PROPERTIES:
     :CUSTOM_ID: jerusalems-ende-155-9
     :END:
5 Wer wird mit dir, Jerusalem, Mitleid haben /\\
 und wer wird dich bedauern? Wer wird kommen, /\\
 um nach deinem Ergehen zu fragen?\\
\\

<<v6>>
6 Du selbst hast mich verworfen - Spruch des Herrn - /\\
 du hast mir den Rücken gekehrt. Deshalb streckte ich meine Hand gegen
dich aus /\\
 und zerstörte dich; /\\
 ich bin der Nachsicht müde geworden.\\
\\

<<v7>>
7 Die Bewohner habe ich mit der Schaufel geworfelt /\\
 auf den freien Plätzen des Landes. Ich habe mein Volk kinderlos gemacht
/\\
 und es dem Untergang geweiht, weil es von seinen schlimmen Wegen /\\
 nicht umkehren wollte. ^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v8>>
8 Seine Witwen wurden zahlreicher /\\
 als der Sand am Meer; ich brachte über sie [die Mütter der jungen
Männer] /\\
 am hellen Mittag den Verwüster, ließ jählings auf sie fallen /\\
 Angst und Schrecken.\\
\\

<<v9>>
9 Die Mutter, die sieben Söhne gebar, /\\
 welkte dahin, verhauchte ihr Leben. Ihr sank die Sonne mitten am Tag,
/\\
 sie fiel in Schande und Schmach. Den Rest des Volkes gebe ich dem
Schwerte preis /\\
 vor den Augen seiner Feinde - Spruch des Herrn.\\
\\

<<v10>>
**** Die Klage des Propheten: 15,10-21
     :PROPERTIES:
     :CUSTOM_ID: die-klage-des-propheten-1510-21
     :END:
10 Weh mir, Mutter, dass du mich geboren hast, /\\
 einen Mann, der mit aller Welt in Zank und Streit liegt. Ich bin
niemands Gläubiger und niemands Schuldner /\\
 und doch fluchen mir alle. ^{[[#fn6][6]]}\\
\\

<<v11>>
11 Fürwahr, Herr, ich habe dir mit gutem Willen gedient, /\\
 ich bin für den Feind bei dir eingetreten /\\
 zur Zeit des Unheils und der Bedrängnis.\\
\\

<<v12>>
12 [Kann man Eisen zertrümmern, /\\
 Eisen vom Norden, und Kupfer? ^{[[#fn7][7]]}\\
\\

<<v13>>
13 Dein Vermögen und deine Schätze /\\
 gebe ich zur Plünderung preis als Lohn für all deine Sünden /\\
 in deinem ganzen Gebiet.\\
\\

<<v14>>
14 Ich mache dich zum Sklaven deiner Feinde /\\
 in einem Land, das du nicht kennst. Denn Feuer lodert auf in meinem
Zorn, /\\
 gegen euch ist es entbrannt.]\\
\\

<<v15>>
15 Du weißt es, Herr; denk an mich /\\
 und nimm dich meiner an! /\\
 Nimm für mich Rache an meinen Verfolgern! Raff mich nicht hinweg, /\\
 sondern schieb deinen Zorn hinaus! /\\
 Bedenke, dass ich deinetwillen Schmach erleide.\\
\\

<<v16>>
16 Kamen Worte von dir, /\\
 so verschlang ich sie; /\\
 dein Wort war mir Glück und Herzensfreude; denn dein Name ist über mir
ausgerufen, /\\
 Herr, Gott der Heere.\\
\\

<<v17>>
17 Ich sitze nicht heiter im Kreis der Fröhlichen; /\\
 von deiner Hand gepackt, sitze ich einsam; /\\
 denn du hast mich mit Groll angefüllt. ^{[[#fn8][8]]}\\
\\

<<v18>>
18 Warum dauert mein Leiden ewig /\\
 und ist meine Wunde so bösartig, /\\
 dass sie nicht heilen will? Wie ein versiegender Bach bist du mir
geworden, /\\
 ein unzuverlässiges Wasser.\\
\\

<<v19>>
19 Darum - so spricht der Herr: Wenn du umkehrst, lasse ich dich
umkehren, /\\
 dann darfst du wieder vor mir stehen. Redest du Edles und nicht
Gemeines, /\\
 dann darfst du mir wieder Mund sein. Jene sollen sich dir zuwenden, /\\
 du aber wende dich ihnen nicht zu. ^{[[#fn9][9]]}\\
\\

<<v20>>
20 Dann mache ich dich für dieses Volk /\\
 zur festen, ehernen Mauer. Mögen sie dich bekämpfen, /\\
 sie werden dich nicht bezwingen; denn ich bin mit dir, /\\
 um dir zu helfen und dich zu retten /\\
 - Spruch des Herrn. ^{[[#fn10][10]]}\\
\\

<<v21>>
21 Ja, ich rette dich aus der Hand der Bösen, /\\
 ich befreie dich aus der Faust der Tyrannen.\\
\\

^{[[#fnm1][1]]} ℘ 43,11

^{[[#fnm2][2]]} ℘ Ez 14,21

^{[[#fnm3][3]]} ℘ 2 Kön 21,1-16

^{[[#fnm4][4]]} ℘ Mt 3,12

^{[[#fnm5][5]]} Zum Bild vom Worfeln vgl. die Anmerkung zu Rut 3,2-4.

^{[[#fnm6][6]]} ℘ 20,14

^{[[#fnm7][7]]} 12-14: Stört den Zusammenhang und unterbricht die Klage.
Die VV. 13f stammen aus 17,3f.

^{[[#fnm8][8]]} ℘ 16,8

^{[[#fnm9][9]]} Der Prophet, der die Umkehr gepredigt hat, muss nun, da
er versagt hat und an seiner Berufung zweifelt, erst selbst umkehren,
wenn er wieder in den Dienst Gottes treten will.

^{[[#fnm10][10]]} ℘ 1,18f
