:PROPERTIES:
:ID:       d5d8b9ec-b2ef-4352-88ce-314aab0e702d
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]]
[[file:Jer_2.html][2]] *3* [[file:Jer_4.html][4]] [[file:Jer_5.html][5]]
... [[file:Jer_52.html][52]]

--------------

* Jer 3
  :PROPERTIES:
  :CUSTOM_ID: jer-3
  :END:

<<verses>>

<<v1>>
**** Der Bundesbruch als Ehebruch: 3,1-13
     :PROPERTIES:
     :CUSTOM_ID: der-bundesbruch-als-ehebruch-31-13
     :END:
1 Wenn ein Mann seine Frau entlässt und wenn sie von ihm weggeht und die
Frau eines andern wird, wendet er sich dann ihr wieder zu? Würde das
Land nicht völlig entweiht? Du aber hast mit vielen Freunden gebuhlt und
da solltest du zu mir zurückkehren dürfen? - Spruch des Herrn.
^{[[#fn1][1]]}

<<v2>>
2 Blick hin und schau zu den Höhen hinauf! Wo hast du dich nicht
schänden lassen? An allen Wegen hast du auf sie gewartet wie ein Araber
in der Wüste. Mit deiner Unzucht und Verkommenheit hast du das Land
entweiht. ^{[[#fn2][2]]}

<<v3>>
3 Da blieb der Regen aus und auch der Frühjahrsregen kam nicht. Doch du
hattest die freche Stirn einer Dirne und wolltest dich nicht schämen.

<<v4>>
4 Gewiss, von da an hast du mir zugerufen: Mein Vater, der Freund meiner
Jugend bist du.

<<v5>>
5 Wird er denn ewig zürnen oder immerfort nachtragen? Ja, so sagtest du
und tatest Böses, so viel du konntest.

<<v6>>
6 Der Herr sprach zu mir zur Zeit des Königs Joschija: Hast du gesehen,
was Israel, die Abtrünnige, getan hat? Sie begab sich auf jeden hohen
Berg und unter jeden üppigen Baum und trieb dort Unzucht.
^{[[#fn3][3]][[#fn4][4]]}

<<v7>>
7 Ich dachte: Nachdem sie dies alles getan hat, wird sie schließlich zu
mir zurückkehren; aber sie kehrte nicht zurück. Das sah ihre Schwester
Juda, die Treulose.

<<v8>>
8 Auch sah sie, dass ich Israel, die Abtrünnige, wegen ihres Ehebruchs
entließ und ihr die Scheidungsurkunde gab. Aber das schreckte ihre
Schwester Juda, die Treulose, nicht ab; sie ging hin und trieb ebenfalls
Unzucht. ^{[[#fn5][5]]}

<<v9>>
9 Durch ihre leichtfertige Unzucht hat sie das Land entweiht und mit
Stein und Holz Ehebruch getrieben.

<<v10>>
10 Bei all dem ist auch ihre Schwester Juda, die Treulose, nicht mit
ganzem Herzen zu mir zurückgekehrt, sondern nur zum Schein - Spruch des
Herrn.

<<v11>>
11 Auch sagte der Herr zu mir: Israel, die Abtrünnige, trifft weniger
Schuld als Juda, die Treulose.

<<v12>>
12 Geh hin, ruf diese Worte gegen Norden und sprich: Kehr zurück,
Israel, du Abtrünnige - Spruch des Herrn! Ich schaue dich nicht mehr
zornig an; denn ich bin gütig - Spruch des Herrn -, ich trage nicht ewig
nach.

<<v13>>
13 Doch erkenne deine Schuld: Dem Herrn, deinem Gott, hast du die Treue
gebrochen, überallhin bist du zu den fremden Göttern gelaufen [unter
jeden üppigen Baum], auf meine Stimme aber hast du nicht gehört Spruch
des Herrn.\\
\\

<<v14>>
**** Die bessere Zukunft: 3,14-18
     :PROPERTIES:
     :CUSTOM_ID: die-bessere-zukunft-314-18
     :END:
14 Kehrt um, ihr abtrünnigen Söhne - Spruch des Herrn; denn ich bin euer
Gebieter. Ich hole euch, einen aus jeder Stadt und zwei aus jeder Sippe,
und bringe euch nach Zion. ^{[[#fn6][6]]}

<<v15>>
15 Ich gebe euch Hirten nach meinem Herzen; mit Einsicht und Klugheit
werden sie euch weiden.

<<v16>>
16 In jenen Tagen, wenn ihr euch im Land vermehrt und fruchtbar seid
Spruch des Herrn -, wird man nicht mehr rufen: Die Bundeslade des Herrn!
Sie wird niemand in den Sinn kommen; man denkt nicht mehr an sie,
vermisst sie nicht und stellt auch keine neue her.

<<v17>>
17 In jener Zeit wird man Jerusalem «Thron des Herrn» nennen; dort, beim
Namen des Herrn in Jerusalem, werden sich alle Völker versammeln und sie
werden nicht mehr dem Trieb ihres bösen Herzens folgen.

<<v18>>
18 In jenen Tagen wird das Haus Juda zum Haus Israel gehen und sie
werden vereint aus dem Nordland in das Land kommen, das ich euren Vätern
zum Erbe gegeben habe.\\
\\

<<v19>>
**** Die Umkehr durch Buße: 3,19 - 4,4
     :PROPERTIES:
     :CUSTOM_ID: die-umkehr-durch-buße-319---44
     :END:
19 Ich hatte gedacht: /\\
 Ja, ich will dich unter die Söhne aufnehmen und dir ein liebliches Land
geben, /\\
 das herrlichste Erbteil unter den Völkern. Ich dachte, du würdest mich
Vater nennen /\\
 und dich nicht abwenden von mir.\\
\\

<<v20>>
20 Doch wie eine Frau ihres Freundes wegen treulos wird, /\\
 so seid auch ihr mir treulos geworden, /\\
 ihr vom Haus Israel - Spruch des Herrn.\\
\\

<<v21>>
21 Horch, man hört auf den Höhen /\\
 das Weinen und Flehen der Söhne Israels, weil sie krumme Wege gegangen
sind /\\
 und den Herrn, ihren Gott, vergessen haben.\\
\\

<<v22>>
22 Kehrt um, ihr abtrünnigen Söhne, /\\
 ich will eure Abtrünnigkeit heilen. «Da sind wir, wir kommen zu dir;
/\\
 denn du bist der Herr, unser Gott!\\
\\

<<v23>>
23 Fürwahr, Trug sind die Höhen, /\\
 der Lärm auf den Bergen. Fürwahr, beim Herrn, unserm Gott, /\\
 ist Israels Rettung.\\
\\

<<v24>>
24 Doch der Baal fraß seit unsrer Jugend alles, /\\
 was unsere Väter erwarben, /\\
 ihre Schafe und Rinder, ihre Söhne und Töchter.\\
\\

<<v25>>
25 Wir betten uns in unsere Schmach /\\
 und unsere Schande bedeckt uns. Denn wir haben gesündigt gegen den
Herrn, unsern Gott, /\\
 wir selbst und unsere Väter, /\\
 von Jugend an bis auf den heutigen Tag. /\\
 Wir haben nicht gehört auf die Stimme des Herrn, unseres Gottes.»\\
\\

^{[[#fnm1][1]]} ℘ Dtn 24,1-4

^{[[#fnm2][2]]} ℘ Hos 4,13

^{[[#fnm3][3]]} ℘ Ez 23

^{[[#fnm4][4]]} 6-8: Die Bevölkerung des Reiches Juda hätte am Schicksal
des Bruderreiches Israel, das 722 v. Chr. unterging, sehen können, wohin
die Untreue gegen Gott führt; sie hat aber daraus keine Lehre gezogen.

^{[[#fnm5][5]]} ℘ Dtn 24,1-3

^{[[#fnm6][6]]} 14-18: Ein Nachtrag aus der Zeit des Exils. Die
Bundeslade wurde vielleicht 586 v. Chr. bei der Zerstörung des Tempels
vernichtet.
