:PROPERTIES:
:ID:       e9879f36-3666-4cab-9f18-bfad0a626443
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_20.html][20]] [[file:Jer_21.html][21]] *22*
[[file:Jer_23.html][23]] [[file:Jer_24.html][24]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 22
  :PROPERTIES:
  :CUSTOM_ID: jer-22
  :END:

<<verses>>

<<v1>>
**** Das Drohwort im Königspalast: 22,1-9
     :PROPERTIES:
     :CUSTOM_ID: das-drohwort-im-königspalast-221-9
     :END:
1 So hat der Herr gesprochen: Geh hinab in den Palast des Königs von
Juda und rede dort folgende Worte!

<<v2>>
2 Du sollst sagen: König von Juda, der du auf dem Thron Davids sitzt,
höre das Wort des Herrn, du selbst, deine Diener und deine Leute, die
durch diese Tore kommen.

<<v3>>
3 So spricht der Herr: Sorgt für Recht und Gerechtigkeit und rettet den
Ausgeplünderten aus der Hand des Gewalttäters! Fremde, Waisen und Witwen
bedrängt und misshandelt nicht; vergießt kein unschuldiges Blut an
diesem Ort! ^{[[#fn1][1]]}

<<v4>>
4 Wenn ihr wirklich dieses Wort erfüllt, dann werden durch die Tore
dieses Palastes Könige einziehen, die auf dem Thron Davids sitzen; mit
Wagen und Rossen werden sie fahren, sie selbst, ihre Beamten und ihre
Leute. ^{[[#fn2][2]]}

<<v5>>
5 Hört ihr aber nicht auf diese Worte, so schwöre ich bei mir selbst
Spruch des Herrn: Zum Trümmerhaufen wird dieser Palast.

<<v6>>
6 Ja, so spricht der Herr gegen den Palast des Königs von Juda: Giltst
du mir auch so viel wie Gilead, wie der Gipfel des Libanon, fürwahr, ich
mache dich zur Wüste, zur unbewohnten Stadt. ^{[[#fn3][3]]}

<<v7>>
7 Ich biete Verwüster gegen dich auf, die mit ihren Äxten kommen, deine
auserlesenen Zedern umhauen und ins Feuer werfen.

<<v8>>
8 Wenn dann Leute aus vielen Völkern an dieser Stadt vorbeikommen und
einander fragen: Warum hat der Herr so an dieser großen Stadt
gehandelt?,

<<v9>>
9 wird man erwidern: Weil sie den Bund mit dem Herrn, ihrem Gott,
aufgegeben, andere Götter angebetet und ihnen gedient haben.\\
\\

<<v10>>
**** Gegen Schallum: 22,10-12
     :PROPERTIES:
     :CUSTOM_ID: gegen-schallum-2210-12
     :END:
10 Weint nicht um den Toten und beklagt ihn nicht! Weint vielmehr um
den, der fortmusste; denn er kehrt nie wieder zurück, nie mehr sieht er
sein Heimatland. ^{[[#fn4][4]]}

<<v11>>
11 Denn so spricht der Herr über Schallum, den Sohn Joschijas, den König
von Juda, der seinem Vater Joschija in der Regierung gefolgt war und
wegziehen musste von diesem Ort: Nie mehr kommt er hierher zurück.

<<v12>>
12 An dem Ort, wohin man ihn verschleppt hat, dort wird er sterben und
dieses Land nie wieder sehen.\\
\\

<<v13>>
**** Gegen Jojakim: 22,13-19
     :PROPERTIES:
     :CUSTOM_ID: gegen-jojakim-2213-19
     :END:
13 Weh dem, der seinen Palast mit Ungerechtigkeit baut, /\\
 seine Gemächer mit Unrecht, der seinen Nächsten ohne Entgelt arbeiten
lässt /\\
 und ihm seinen Lohn nicht gibt, ^{[[#fn5][5]]}\\
\\

<<v14>>
14 der sagt: Ich baue mir einen stattlichen Palast /\\
 und weite Gemächer. Er setzt ihm hohe Fenster ein, /\\
 täfelt ihn mit Zedernholz /\\
 und bemalt ihn mit Mennigrot.\\
\\

<<v15>>
15 Bist du König geworden, /\\
 um mit Zedern zu prunken? Hat dein Vater nicht auch gegessen und
getrunken, /\\
 dabei aber für Recht und Gerechtigkeit gesorgt? /\\
 Und es ging ihm gut.\\
\\

<<v16>>
16 Dem Schwachen und Armen verhalf er zum Recht. /\\
 Heißt nicht das, mich wirklich erkennen? /\\
 - Spruch des Herrn.\\
\\

<<v17>>
17 Doch deine Augen und dein Herz /\\
 sind nur auf deinen Vorteil gerichtet, auf das Blut des Unschuldigen,
das du vergießt, /\\
 auf Bedrückung und Erpressung, die du verübst. ^{[[#fn6][6]]}\\
\\

<<v18>>
18 Darum - so spricht der Herr über Jojakim, /\\
 den Sohn Joschijas, den König von Juda: Man wird für ihn nicht die
Totenklage halten: /\\
 «Ach, mein Bruder! Ach, Schwester!» Man wird für ihn nicht die
Totenklage halten: /\\
 «Ach, der Herrscher! Ach, seine Majestät!» ^{[[#fn7][7]]}\\
\\

<<v19>>
19 Ein Eselsbegräbnis wird er bekommen. /\\
 Man schleift ihn weg und wirft ihn hin, /\\
 draußen vor den Toren Jerusalems. ^{[[#fn8][8]][[#fn9][9]]}\\
\\

<<v20>>
**** Jerusalems Sturz: 22,20-23
     :PROPERTIES:
     :CUSTOM_ID: jerusalems-sturz-2220-23
     :END:
20 (Jerusalem,) steig auf den Libanon und schrei, /\\
 im Baschan erheb deine Stimme, schrei vom Abarimgebirge herab, /\\
 dass alle deine Freunde zerschmettert sind.\\
\\

<<v21>>
21 Ich habe dir zugeredet, als du dich noch sicher fühltest; /\\
 du aber hast gesagt: Ich höre nicht. So hast du es getrieben von Jugend
an: /\\
 Du hast auf meine Stimme nicht gehört.\\
\\

<<v22>>
22 All deine Hirten wird der Wind weiden, /\\
 deine Freunde müssen fort in die Gefangenschaft. Dann wirst du Schmach
und Schande ernten /\\
 wegen all deiner Untaten.\\
\\

<<v23>>
23 Die du auf dem Libanon thronst (Jerusalem), /\\
 in Zedern nistest, wie wirst du stöhnen, wenn Wehen über dich kommen,
/\\
 Schmerzen wie die einer Gebärenden.\\
\\

<<v24>>
**** Gegen Jojachin: 22,24-30
     :PROPERTIES:
     :CUSTOM_ID: gegen-jojachin-2224-30
     :END:
24 So wahr ich lebe - Spruch des Herrn -, selbst wenn Jojachin, der Sohn
Jojakims und König von Juda, ein Siegelring an meiner Rechten wäre, ich
risse dich weg. ^{[[#fn10][10]][[#fn11][11]]}

<<v25>>
25 Ich gebe dich in die Hand derer, die dir nach dem Leben trachten, in
die Hand derer, vor denen dir graut, in die Hand Nebukadnezzars, des
Königs von Babel, und in die Hand der Chaldäer.

<<v26>>
26 Ich schleudere dich samt deiner Mutter, die dich gebar, in ein
anderes Land, in dem ihr nicht geboren seid, und dort werdet ihr
sterben.

<<v27>>
27 In das Land aber, nach dem ihr Herz sehnlich zurückverlangt, werden
sie nie wieder kommen. -

<<v28>>
28 Ist denn dieser Mann Jojachin ein verachtetes, zerschlagenes Gefäß
oder ein Gerät, das niemand mehr mag? Warum wird er fortgeschleudert und
hingeworfen in ein Land, das er nicht kennt?

<<v29>>
29 Land, Land, Land, höre das Wort des Herrn!

<<v30>>
30 So spricht der Herr: Schreibt diesen Mann als kinderlos ein, als
Mann, der in seinem Leben kein Glück hat. Denn keinem seiner Nachkommen
wird es glücken, sich auf den Thron Davids zu setzen und wieder über
Juda zu herrschen. ^{[[#fn12][12]]}\\
\\

^{[[#fnm1][1]]} ℘ 21,12

^{[[#fnm2][2]]} ℘ 17,25

^{[[#fnm3][3]]} Gilead ist ein fruchtbares Gebiet östlich des Jordan.

^{[[#fnm4][4]]} 10f: Der tüchtige, in der Schlacht bei Megiddo gefallene
König Joschija wurde sehr betrauert (609 v. Chr.). Sein Sohn Schallum,
auch Joahas genannt, wurde vom Pharao Necho gefangen genommen und nach
Ägypten verschleppt (vgl. 2 Kön 23,31-34).

^{[[#fnm5][5]]} ℘ Mi 3,10; Lev 19,13

^{[[#fnm6][6]]} ℘ 2 Kön 24,1-4

^{[[#fnm7][7]]} ℘ 34,5

^{[[#fnm8][8]]} ℘ 36,30

^{[[#fnm9][9]]} Von einem «Eselsbegräbnis» weiß 2 Kön 24,6 nichts.
Jojakim starb 597 v. Chr., noch vor Beginn der Belagerung Jerusalems,
und dürfte ein normales Königsbegräbnis erhalten haben.

^{[[#fnm10][10]]} ℘ 2 Kön 24,8-16

^{[[#fnm11][11]]} In H heißt der König Konja, ein Kurzname für Jojachin.
Kurz nach der Thronbesteigung beginnt die Belagerung Jerusalems durch
Nebukadnezzar. Jojachin ergibt sich bald, wird abgesetzt und als
Gefangener nach Babylon gebracht.

^{[[#fnm12][12]]} als kinderlos: Er steht als kinderlos in der
davidischen Königsliste verzeichnet. Jojachin hatte zwar Söhne, doch
kamen sie nicht an die Regierung, sodass er keinen Nachfolger hatte.
