:PROPERTIES:
:ID:       e38c5ac6-f730-4676-b61c-122ab7911729
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jeremia* -- [[file:Jer_1.html][1]] ...
[[file:Jer_8.html][8]] [[file:Jer_9.html][9]] *10*
[[file:Jer_11.html][11]] [[file:Jer_12.html][12]] ...
[[file:Jer_52.html][52]]

--------------

* Jer 10
  :PROPERTIES:
  :CUSTOM_ID: jer-10
  :END:

<<verses>>

<<v1>>
**** Gott und die Götzenbilder: 10,1-16
     :PROPERTIES:
     :CUSTOM_ID: gott-und-die-götzenbilder-101-16
     :END:
1 Hört das Wort, das der Herr zu euch spricht, ihr vom Haus Israel.\\
\\

<<v2>>
2 So spricht der Herr: Gewöhnt euch nicht an den Weg der Völker, /\\
 erschreckt nicht vor den Zeichen des Himmels, /\\
 wenn auch die Völker vor ihnen erschrecken.\\
\\

<<v3>>
3 Denn die Gebräuche der Völker sind leerer Wahn. /\\
 Ihre Götzen sind nur Holz, das man im Wald schlägt, /\\
 ein Werk aus der Hand des Schnitzers, /\\
 mit dem Messer verfertigt. ^{[[#fn1][1]]}\\
\\

<<v4>>
4 Er verziert es mit Silber und Gold, /\\
 mit Nagel und Hammer macht er es fest, sodass es nicht wackelt.
^{[[#fn2][2]]}\\
\\

<<v5>>
5 Sie sind wie Vogelscheuchen im Gurkenfeld. /\\
 Sie können nicht reden; /\\
 man muss sie tragen, weil sie nicht gehen können. Fürchtet euch nicht
vor ihnen; /\\
 denn sie können weder Schaden zufügen /\\
 noch Gutes bewirken.\\
\\

<<v6>>
6 Niemand, Herr, ist wie du: /\\
 Groß bist du und groß an Kraft ist dein Name.\\
\\

<<v7>>
7 Wer sollte dich nicht fürchten, du König der Völker? /\\
 Ja, das steht dir zu. Denn unter allen Weisen der Völker /\\
 und in jedem ihrer Reiche ist keiner wie du.\\
\\

<<v8>>
8 Sie alle sind töricht und dumm. /\\
 Was die nichtigen Götzen zu bieten haben - Holz ist es.\\
\\

<<v9>>
9 Sie sind gehämmertes Silber aus Tarschisch und Gold aus Ofir, /\\
 Arbeit des Schnitzers und Goldschmieds; violetter und roter Purpur ist
ihr Gewand; /\\
 sie alle sind nur das Werk kunstfertiger Männer.\\
\\

<<v10>>
10 Der Herr aber ist in Wahrheit Gott, /\\
 lebendiger Gott und ewiger König. Vor seinem Zorn erbebt die Erde, /\\
 die Völker halten seinen Groll nicht aus.\\
\\

<<v11>>
11 Von jenen dagegen sollt ihr sagen: /\\
 Die Götter, die weder Himmel noch Erde erschufen, /\\
 sie sollen verschwinden von der Erde und unter dem Himmel.
^{[[#fn3][3]]}\\
\\

<<v12>>
12 Er aber hat die Erde erschaffen durch seine Kraft, /\\
 den Erdkreis gegründet durch seine Weisheit, /\\
 durch seine Einsicht den Himmel ausgespannt. ^{[[#fn4][4]]}\\
\\

<<v13>>
13 Lässt er seine Stimme ertönen, /\\
 dann rauschen die Wasser am Himmel. Wolken führt er herauf vom Rand der
Erde; /\\
 er lässt es blitzen und regnen, /\\
 aus seinen Kammern entsendet er den Wind. ^{[[#fn5][5]]}\\
\\

<<v14>>
14 Töricht steht jeder Mensch da, ohne Erkenntnis, /\\
 beschämt jeder Goldschmied mit seinem Götzenbild; denn seine Bilder
sind Trug, /\\
 kein Atem ist in ihnen. ^{[[#fn6][6]]}\\
\\

<<v15>>
15 Nichtig sind sie, ein Spottgebilde. /\\
 Zur Zeit ihrer Heimsuchung gehen sie zugrunde.\\
\\

<<v16>>
16 Anders der Gott, der Jakobs Anteil ist. /\\
 Denn er ist der Schöpfer des Alls und Israel der Stamm, der ihm gehört.
/\\
 Herr der Heere ist sein Name.\\
\\

<<v17>>
**** Klage und Bitte: 10,17-25
     :PROPERTIES:
     :CUSTOM_ID: klage-und-bitte-1017-25
     :END:
17 Raff dein Bündel zusammen! Fort aus dem Land, /\\
 du schwer bedrängte Stadt!\\
\\

<<v18>>
18 Denn so spricht der Herr: Fürwahr, diesmal schleudere ich /\\
 die Bewohner des Landes hinweg und bringe sie in Bedrängnis, /\\
 damit sie mich finden.\\
\\

<<v19>>
19 Weh mir ob meines Zusammenbruchs! /\\
 Unheilbar ist meine Wunde. Ich aber hatte gedacht: /\\
 Das ist doch nur eine Krankheit, die ich ertragen kann.
^{[[#fn7][7]]}\\
\\

<<v20>>
20 Nun ist mein Zelt verwüstet, /\\
 alle meine Zeltstricke sind zerrissen. Meine Kinder gingen von mir fort
/\\
 und sind nicht mehr. Niemand schlägt mein Zelt wieder auf /\\
 und breitet darüber die Zeltdecken aus.\\
\\

<<v21>>
21 Denn töricht waren die Hirten, /\\
 den Herrn suchten sie nicht; deshalb hatten sie keinen Erfolg /\\
 und ihre ganze Herde wurde zerstreut.\\
\\

<<v22>>
22 Horch, eine Kunde trifft eben ein, /\\
 großes Getöse vom Nordland her: Judas Städte sollen zum Ödland werden,
/\\
 zur Behausung für Schakale. ^{[[#fn8][8]]}\\
\\

<<v23>>
23 Ich weiß, Herr, dass der Mensch seinen Weg nicht zu bestimmen vermag,
/\\
 dass keiner beim Gehen seinen Schritt lenken kann.\\
\\

<<v24>>
24 Herr, züchtige mich, doch mit rechtem Maß, /\\
 nicht in deinem Zorn, /\\
 sonst machst du mich allzu elend. ^{[[#fn9][9]]}\\
\\

<<v25>>
25 Gieß deinen Zorn aus über die Völker, /\\
 die dich nicht kennen, und über die Stämme, /\\
 die deinen Namen nicht anrufen. Denn sie haben Jakob verschlungen und
vernichtet, /\\
 seine Wohnstätte verwüstet.\\
\\

^{[[#fnm1][1]]} ℘ Jes 44,12-17

^{[[#fnm2][2]]} ℘ Bar 6

^{[[#fnm3][3]]} In aramäischer Sprache.

^{[[#fnm4][4]]} ℘ (12-16) 51,15-19

^{[[#fnm5][5]]} ℘ Ps 135,7

^{[[#fnm6][6]]} ℘ Jes 45,16

^{[[#fnm7][7]]} ℘ 14,17; 30,12

^{[[#fnm8][8]]} ℘ 9,10; 26,18

^{[[#fnm9][9]]} ℘ 30,11
