:PROPERTIES:
:ID:       8be01971-3d73-4fe6-9666-8a4c02d683c8
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_52.html][52]] [[file:Jes_53.html][53]] *54*
[[file:Jes_55.html][55]] [[file:Jes_56.html][56]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 54
  :PROPERTIES:
  :CUSTOM_ID: jes-54
  :END:

<<verses>>

<<v1>>
** Die Verheißung des Glücks im neuen Zion: 54,1 - 55,5
   :PROPERTIES:
   :CUSTOM_ID: die-verheißung-des-glücks-im-neuen-zion-541---555
   :END:
**** Der Segen Gottes für das Volk: 54,1-10
     :PROPERTIES:
     :CUSTOM_ID: der-segen-gottes-für-das-volk-541-10
     :END:
1 Freu dich, du Unfruchtbare, die nie gebar, /\\
 du, die nie in Wehen lag, brich in Jubel aus und jauchze! Denn die
Einsame hat jetzt viel mehr Söhne /\\
 als die Vermählte, spricht der Herr. ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v2>>
2 Mach den Raum deines Zeltes weit, /\\
 spann deine Zelttücher aus, ohne zu sparen. /\\
 Mach die Stricke lang und die Pflöcke fest! ^{[[#fn3][3]]}\\
\\

<<v3>>
3 Denn nach rechts und links breitest du dich aus. /\\
 Deine Nachkommen werden Völker beerben /\\
 und verödete Städte besiedeln.\\
\\

<<v4>>
4 Fürchte dich nicht, du wirst nicht beschämt; /\\
 schäme dich nicht, du wirst nicht enttäuscht. Denn die Schande in
deiner Jugend wirst du vergessen, /\\
 an die Schmach deiner Witwenschaft wirst du nicht mehr denken.
^{[[#fn4][4]]}\\
\\

<<v5>>
5 Denn dein Schöpfer ist dein Gemahl, /\\
 «Herr der Heere» ist sein Name. Der Heilige Israels ist dein Erlöser,
/\\
 «Gott der ganzen Erde» wird er genannt. ^{[[#fn5][5]]}\\
\\

<<v6>>
6 Ja, der Herr hat dich gerufen /\\
 als verlassene, bekümmerte Frau. Kann man denn die Frau verstoßen, /\\
 die man in der Jugend geliebt hat?, /\\
 spricht dein Gott.\\
\\

<<v7>>
7 Nur für eine kleine Weile habe ich dich verlassen, /\\
 doch mit großem Erbarmen hole ich dich heim. ^{[[#fn6][6]]}\\
\\

<<v8>>
8 Einen Augenblick nur verbarg ich vor dir mein Gesicht /\\
 in aufwallendem Zorn; aber mit ewiger Huld habe ich Erbarmen mit dir,
/\\
 spricht dein Erlöser, der Herr. ^{[[#fn7][7]]}\\
\\

<<v9>>
9 Wie in den Tagen Noachs soll es für mich sein: /\\
 So wie ich damals schwor, dass die Flut Noachs die Erde nie mehr
überschwemmen wird, /\\
 so schwöre ich jetzt, dir nie mehr zu zürnen /\\
 und dich nie mehr zu schelten. ^{[[#fn8][8]]}\\
\\

<<v10>>
10 Auch wenn die Berge von ihrem Platz weichen /\\
 und die Hügel zu wanken beginnen - meine Huld wird nie von dir weichen
/\\
 und der Bund meines Friedens nicht wanken, /\\
 spricht der Herr, der Erbarmen hat mit dir. ^{[[#fn9][9]]}\\
\\

<<v11>>
**** Das neue Jerusalem: 54,11-17
     :PROPERTIES:
     :CUSTOM_ID: das-neue-jerusalem-5411-17
     :END:
11 Du Ärmste, vom Sturm Gepeitschte, /\\
 die ohne Trost ist, sieh her: Ich selbst lege dir ein Fundament aus
Malachit /\\
 und Grundmauern aus Saphir. ^{[[#fn10][10]]}\\
\\

<<v12>>
12 Aus Rubinen mache ich deine Zinnen, /\\
 aus Beryll deine Tore /\\
 und alle deine Mauern aus kostbaren Steinen.\\
\\

<<v13>>
13 Alle deine Söhne werden Jünger des Herrn sein /\\
 und groß ist der Friede deiner Söhne. ^{[[#fn11][11]]}\\
\\

<<v14>>
14 Du wirst auf Gerechtigkeit gegründet sein. /\\
 Du bist fern von Bedrängnis, denn du brauchst dich nicht mehr zu
fürchten /\\
 und bist fern von Schrecken; /\\
 er kommt an dich nicht heran. ^{[[#fn12][12]]}\\
\\

<<v15>>
15 Wenn dich jemand angreift, misslingt es, /\\
 denn es geschieht ohne mich; /\\
 wer dich angreift, fällt im Kampf gegen dich.\\
\\

<<v16>>
16 Ich habe den Schmied erschaffen, /\\
 der das Kohlenfeuer entfacht und Waffen erzeugt, /\\
 wie es seinem Handwerk entspricht. Ich habe auch den, der vernichtet,
erschaffen, /\\
 damit er zerstört.\\
\\

<<v17>>
17 Keine Waffe wird etwas ausrichten, die man gegen dich schmiedet; /\\
 jede Zunge, die dich vor Gericht verklagt, strafst du Lügen. Das ist
das Erbteil der Knechte des Herrn: /\\
 Von mir kommt ihre Rettung Spruch des Herrn.\\
\\

^{[[#fnm1][1]]} ℘ Gal 4,27; Jes 62,4

^{[[#fnm2][2]]} Angeredet ist Jerusalem.

^{[[#fnm3][3]]} spann . . . aus: Text korr. nach den alten
Übersetzungen.

^{[[#fnm4][4]]} 4-6: Die Zeit des Gerichts über Jerusalem ist vorbei.

^{[[#fnm5][5]]} ℘ Hos 2,18

^{[[#fnm6][6]]} ℘ Ps 30,6

^{[[#fnm7][7]]} ℘ 60,10

^{[[#fnm8][8]]} ℘ Gen 9,8-17

^{[[#fnm9][9]]} ℘ Ez 34,25; 37,26

^{[[#fnm10][10]]} ℘ (11-12) Tob 13,17; Offb 21,18-21

^{[[#fnm11][11]]} ℘ Joh 6,45

^{[[#fnm12][12]]} ℘ Ps 91,10
