:PROPERTIES:
:ID:       ca88c855-40a9-4095-b1f6-e975c584ce56
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_37.html][37]] [[file:Jes_38.html][38]] *39*
[[file:Jes_40.html][40]] [[file:Jes_41.html][41]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 39
  :PROPERTIES:
  :CUSTOM_ID: jes-39
  :END:

<<verses>>

<<v1>>
**** Die Gesandtschaft aus Babel: 39,1-8
     :PROPERTIES:
     :CUSTOM_ID: die-gesandtschaft-aus-babel-391-8
     :END:
1 Damals sandte Merodach-Baladan, der Sohn Baladans, der König von
Babel, einen Brief und Geschenke an Hiskija; denn er hatte von seiner
Krankheit und von seiner Genesung gehört. ^{[[#fn1][1]]}

<<v2>>
2 Hiskija freute sich darüber und zeigte den Gesandten sein Schatzhaus,
das Silber und das Gold, die Vorräte an Balsam und feinem Öl, sein
ganzes Waffenlager und alle anderen Schätze, die er besaß. Es gab nichts
in seinem Haus und in seinem ganzen Herrschaftsbereich, das er ihnen
nicht gezeigt hätte.

<<v3>>
3 Danach kam der Prophet Jesaja zu König Hiskija und fragte ihn: Was
haben diese Männer gesagt? Woher kamen sie? Hiskija antwortete: Sie sind
aus einem fernen Land, aus Babel, zu mir gekommen.

<<v4>>
4 Er fragte weiter: Was haben sie in deinem Haus gesehen? Hiskija
antwortete: Sie haben alles gesehen, was in meinem Haus ist. Es gibt
nichts in meinen Schatzkammern, das ich ihnen nicht gezeigt hätte.

<<v5>>
5 Da sagte Jesaja zu Hiskija: Höre das Wort des Herrn der Heere:

<<v6>>
6 Es werden Tage kommen, an denen man alles, was in deinem Haus ist,
alles, was deine Väter bis zum heutigen Tag angesammelt haben, nach
Babel bringt. Nichts wird übrig bleiben, spricht der Herr.

<<v7>>
7 Auch von deinen eigenen Söhnen, die du noch bekommen wirst, wird man
einige mitnehmen und sie werden als Kämmerer im Palast des Königs von
Babel dienen müssen.

<<v8>>
8 Hiskija sagte zu Jesaja: Das Wort des Herrn, das du mir gesagt hast,
ist gut. Und er dachte: Zu meinen Lebzeiten herrscht ja noch Friede und
Sicherheit.\\
\\

^{[[#fnm1][1]]} ℘ (1-8) 2 Kön 20,12-19
