:PROPERTIES:
:ID:       84b45ff7-ecd0-4b77-9391-675ada87c790
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_5.html][5]] [[file:Jes_6.html][6]] *7* [[file:Jes_8.html][8]]
[[file:Jes_9.html][9]] ... [[file:Jes_66.html][66]]

--------------

* Jes 7
  :PROPERTIES:
  :CUSTOM_ID: jes-7
  :END:

<<verses>>

<<v1>>
**** Die Weissagung über den Immanuel: 7,1-25
     :PROPERTIES:
     :CUSTOM_ID: die-weissagung-über-den-immanuel-71-25
     :END:
1 In der Zeit, als Ahas, der Sohn Jotams, des Sohnes Usijas, König von
Juda war, zogen Rezin, der König von Aram, und Pekach, der Sohn
Remaljas, der König von Israel, gegen Jerusalem in den Krieg; aber sie
konnten die Stadt nicht einnehmen. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Als man dem Haus David meldete: Aram hat sich mit Efraim verbündet!,
da zitterte das Herz des Königs und das Herz seines Volkes, wie die
Bäume des Waldes im Wind zittern.

<<v3>>
3 Der Herr aber sagte zu Jesaja: Geh zur Walkerfeldstraße hinaus,
zusammen mit deinem Sohn Schear-Jaschub (Ein Rest kehrt um), an das Ende
der Wasserleitung des oberen Teiches, um Ahas zu treffen.
^{[[#fn3][3]][[#fn4][4]]}

<<v4>>
4 Sag zu ihm: Bewahre die Ruhe, fürchte dich nicht! Dein Herz soll nicht
verzagen wegen dieser beiden Holzscheite, dieser rauchenden Stummel,
wegen des glühenden Zorns Rezins von Aram und des Sohnes Remaljas.
^{[[#fn5][5]]}

<<v5>>
5 Zwar planen Aram, Efraim und der Sohn Remaljas Böses gegen dich und
sagen:

<<v6>>
6 Wir wollen gegen Juda ziehen, es an uns reißen und für uns erobern;
dann wollen wir den Sohn Tabeals dort zum König machen.\\
\\

<<v7>>
7 Doch so spricht Gott, der Herr: Das kommt nicht zustande, /\\
 das wird nicht geschehen.\\
\\

<<v8>>
8 Denn das Haupt von Aram ist Damaskus /\\
 und das Haupt von Damaskus ist Rezin. Noch fünfundsechzig Jahre, dann
wird Efraim zerschlagen, /\\
 es wird aufhören, ein Volk zu sein. ^{[[#fn6][6]]}\\
\\

<<v9>>
9 Das Haupt von Efraim ist Samaria /\\
 und das Haupt von Samaria ist der Sohn Remaljas. /\\
 Glaubt ihr nicht, so bleibt ihr nicht. ^{[[#fn7][7]][[#fn8][8]]}\\
\\

<<v10>>
10 Der Herr sprach noch einmal zu Ahas; er sagte:

<<v11>>
11 Erbitte dir vom Herrn, deinem Gott, ein Zeichen, sei es von unten,
aus der Unterwelt, oder von oben, aus der Höhe.

<<v12>>
12 Ahas antwortete: Ich will um nichts bitten und den Herrn nicht auf
die Probe stellen.

<<v13>>
13 Da sagte Jesaja: Hört her, ihr vom Haus David! Genügt es euch nicht,
Menschen zu belästigen? Müßt ihr auch noch meinen Gott belästigen?

<<v14>>
14 Darum wird euch der Herr von sich aus ein Zeichen geben: Seht, die
Jungfrau wird ein Kind empfangen, sie wird einen Sohn gebären und sie
wird ihm den Namen Immanuel (Gott mit uns) geben.
^{[[#fn9][9]][[#fn10][10]]}

<<v15>>
15 Er wird Butter und Honig essen bis zu der Zeit, in der er versteht,
das Böse zu verwerfen und das Gute zu wählen.

<<v16>>
16 Denn noch bevor das Kind versteht, das Böse zu verwerfen und das Gute
zu wählen, wird das Land verödet sein, vor dessen beiden Königen dich
das Grauen packt. ^{[[#fn11][11]]}

<<v17>>
17 Der Herr wird Tage kommen lassen über dich und dein Volk und das Haus
deines Vaters [durch den König von Assur], wie man sie nicht mehr erlebt
hat, seit Efraim von Juda abgefallen ist.

<<v18>>
18 An jenem Tag wird der Herr den Fliegen an den Mündungen des Nil in
Ägypten pfeifen und den Bienen im Land Assur ^{[[#fn12][12]]}

<<v19>>
19 und alle kommen und lassen sich nieder in den Schluchten und
Felsspalten, in allen Hecken und an allen Wasserstellen.

<<v20>>
20 An jenem Tag wird der Herr mit dem Messer, das er jenseits des Eufrat
gekauft hat [mit dem König von Assur], euch den Kopf kahl scheren und
die Schamhaare abrasieren; auch den Bart schneidet er ab.

<<v21>>
21 An jenem Tag wird ein Mann nur eine junge Kuh und ein paar Schafe
halten.

<<v22>>
22 Aber sie werden so viel Milch geben, dass man Butter essen kann. Ja,
Butter und Honig essen alle, die im Land übrig geblieben sind.

<<v23>>
23 An jenem Tag wird jedes Grundstück, auf dem jetzt tausend Weinstöcke
im Wert von tausend Silberstücken stehen, voll von Dornen und Disteln
sein.

<<v24>>
24 Nur mit Pfeil und Bogen geht man dorthin; denn das ganze Land ist
voll von Dornen und Disteln.

<<v25>>
25 Aus Angst vor den Dornen und Disteln geht man auf keinen von all den
Bergen mehr, die man jetzt noch mit der Hacke bearbeitet. Man treibt die
Rinder dorthin und lässt die Schafe dort weiden.\\
\\

^{[[#fnm1][1]]} ℘ 2 Kön 16,5-9

^{[[#fnm2][2]]} Ziel des sogenannten Syrisch-efraimitischen Kriegs
(734/33 v. Chr.) ist es, Juda als Verbündeten gegen Assyrien zu
gewinnen.

^{[[#fnm3][3]]} ℘ 36,2

^{[[#fnm4][4]]} Der symbolische Name des Sohns ist Mahnung und Warnung
für Ahas, der anscheinend die Anlagen zur Wasserversorgung inspiziert.

^{[[#fnm5][5]]} Die beiden Könige können nicht mehr gefährlich werden;
ihr Schicksal ist bereits besiegelt: 732 v. Chr. erfolgt die Eroberung
von Damaskus, 722 die Eroberung von Samaria.

^{[[#fnm6][6]]} 8cd: Bezieht sich auf die Ansiedlung einer fremden
Oberschicht in Samaria um 720 v. Chr.

^{[[#fnm7][7]]} ℘ 28,16; 30,15; 2 Chr 20,20

^{[[#fnm8][8]]} Der letzte Satz ist in H ein Wortspiel.

^{[[#fnm9][9]]} ℘ Mt 1,23; Lk 1,31; Mi 5,2

^{[[#fnm10][10]]} Jungfrau: nach G und Mt 1,23; das hebräische Wort
almáh wird auch als «junge Frau» gedeutet. Nach V. 16 besagt das
Zeichen, dass das Unheil in wenigen Jahren hereinbricht.

^{[[#fnm11][11]]} ℘ 8,4

^{[[#fnm12][12]]} ℘ 5,26
