:PROPERTIES:
:ID:       66c871cb-2ee9-4712-8f45-eb21ccf6667b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_10.html][10]] [[file:Jes_11.html][11]] *12*
[[file:Jes_13.html][13]] [[file:Jes_14.html][14]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 12
  :PROPERTIES:
  :CUSTOM_ID: jes-12
  :END:

<<verses>>

<<v1>>
**** Das Danklied der Geretteten: 12,1-6
     :PROPERTIES:
     :CUSTOM_ID: das-danklied-der-geretteten-121-6
     :END:
1 An jenem Tag wirst du sagen: /\\
 Ich danke dir, Herr. Du hast mir gezürnt, /\\
 doch dein Zorn hat sich gewendet /\\
 und du hast mich getröstet.\\
\\

<<v2>>
2 Ja, Gott ist meine Rettung; /\\
 ihm will ich vertrauen und niemals verzagen. Denn meine Stärke und mein
Lied ist der Herr. /\\
 Er ist für mich zum Retter geworden. ^{[[#fn1][1]]}\\
\\

<<v3>>
3 Ihr werdet Wasser schöpfen voll Freude /\\
 aus den Quellen des Heils.\\
\\

<<v4>>
4 An jenem Tag werdet ihr sagen: /\\
 Dankt dem Herrn! Ruft seinen Namen an! Macht seine Taten unter den
Völkern bekannt, /\\
 verkündet: Sein Name ist groß und erhaben!\\
\\

<<v5>>
5 Preist den Herrn; /\\
 denn herrliche Taten hat er vollbracht; /\\
 auf der ganzen Erde soll man es wissen.\\
\\

<<v6>>
6 Jauchzt und jubelt, ihr Bewohner von Zion; /\\
 denn groß ist in eurer Mitte der Heilige Israels.\\
\\

^{[[#fnm1][1]]} ℘ Ex 15,2; Ps 118,14
