:PROPERTIES:
:ID:       26bc109e-28e3-441a-b427-2a016bcfe56f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_46.html][46]] [[file:Jes_47.html][47]] *48*
[[file:Jes_49.html][49]] [[file:Jes_50.html][50]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 48
  :PROPERTIES:
  :CUSTOM_ID: jes-48
  :END:

<<verses>>

<<v1>>
**** Der Erweis der Gottheit des Herrn durch Weissagungen: 48,1-11
     :PROPERTIES:
     :CUSTOM_ID: der-erweis-der-gottheit-des-herrn-durch-weissagungen-481-11
     :END:
1 Hört her, ihr vom Haus Jakob, /\\
 die ihr den Namen Israels tragt /\\
 und Judas Nachkommen seid, die ihr beim Namen des Herrn schwört /\\
 und euch bekennt zu Israels Gott, /\\
 aber nicht offen und ehrlich.\\
\\

<<v2>>
2 Sie nennen sich nach der Heiligen Stadt /\\
 und verlassen sich auf Israels Gott, /\\
 der «Herr der Heere» genannt wird.\\
\\

<<v3>>
3 Was früher war, hatte ich schon längst im Voraus verkündet, /\\
 es kam aus meinem Mund, ich ließ es hören; /\\
 plötzlich habe ich gehandelt und es traf ein. ^{[[#fn1][1]]}\\
\\

<<v4>>
4 Weil ich wusste, dass du halsstarrig bist, /\\
 dass dein Nacken eiserne Sehnen hat /\\
 und deine Stirn aus Bronze ist,\\
\\

<<v5>>
5 hatte ich es dir schon längst im Voraus verkündet; /\\
 ich ließ es dich hören, bevor es geschah, damit du nicht sagst: Mein
Götterbild hat das vollbracht, /\\
 mein geschnitztes und gegossenes Bild hat es befohlen.\\
\\

<<v6>>
6 Du hast es gehört. Betrachte nun alles! /\\
 Willst du es nicht andern verkünden? Von jetzt an lasse ich dich etwas
Neues hören, /\\
 etwas Verborgenes, von dem du nichts weißt. ^{[[#fn2][2]][[#fn3][3]]}\\
\\

<<v7>>
7 Eben erst kam es zustande, /\\
 nicht schon vor langer Zeit. Zuvor hast du nichts erfahren davon, /\\
 damit du nicht sagst: /\\
 Das habe ich längst schon gewusst.\\
\\

<<v8>>
8 Du hast davon nichts gehört und gewusst, /\\
 dein Ohr war bisher nicht offen. Denn ich wusste, dass du treulos sein
wirst, /\\
 man nennt dich «abtrünnig vom Mutterleib an».\\
\\

<<v9>>
9 Doch um meines Namens willen /\\
 halte ich meinen Zorn lange zurück, um meiner Ehre willen bezähme ich
mich, /\\
 um dich nicht vernichten zu müssen.\\
\\

<<v10>>
10 Ich habe dich geläutert, doch nicht wie Silber: /\\
 Im Schmelzofen des Elends prüfte ich dich. ^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v11>>
11 Nur um meinetwillen handle ich jetzt, /\\
 denn sonst würde mein Name entweiht; /\\
 ich überlasse die Ehre, die mir gebührt, keinem andern.
^{[[#fn6][6]][[#fn7][7]]}\\
\\

<<v12>>
**** Kyrus, der Beauftragte Jahwes: 48,12-16
     :PROPERTIES:
     :CUSTOM_ID: kyrus-der-beauftragte-jahwes-4812-16
     :END:
12 Jakob, höre auf mich, /\\
 höre mich, Israel, den ich berief: /\\
 Ich bin es, ich, der Erste und auch der Letzte. ^{[[#fn8][8]]}\\
\\

<<v13>>
13 Meine Hand hat die Fundamente der Erde gelegt, /\\
 meine Rechte hat den Himmel ausgespannt; /\\
 ich rief ihnen zu und schon standen sie alle da. ^{[[#fn9][9]]}\\
\\

<<v14>>
14 Versammelt euch alle und hört - /\\
 wer von den Göttern hat so etwas jemals verkündet? -: Der, den der Herr
liebt, wird meinen Willen an Babel vollstrecken /\\
 und sein Arm wird es an den Chaldäern bewirken.\\
\\

<<v15>>
15 Ich habe gesprochen und ich habe ihn auch berufen, /\\
 ich habe ihn kommen lassen /\\
 und er wird seinen Weg erfolgreich beenden.\\
\\

<<v16>>
16 Kommt her zu mir und hört, was ich sage: /\\
 Ich habe von Anfang an nicht im Verborgenen geredet; /\\
 seit das alles geschieht, bin ich dabei. /\\
 [Und jetzt hat Gott, der Herr, mich und seinen Geist gesandt.]
^{[[#fn10][10]][[#fn11][11]]}\\
\\

<<v17>>
**** Die Lehre aus der Vergangenheit: 48,17-19
     :PROPERTIES:
     :CUSTOM_ID: die-lehre-aus-der-vergangenheit-4817-19
     :END:
17 So spricht der Herr, dein Erlöser, /\\
 der Heilige Israels: Ich bin der Herr, dein Gott, /\\
 der dich lehrt, was Nutzen bringt, und der dich auf den Weg führt, /\\
 den du gehen sollst.\\
\\

<<v18>>
18 Hättest du doch auf meine Gebote geachtet! /\\
 Dein Glück wäre wie ein Strom /\\
 und dein Heil wie die Wogen des Meeres. ^{[[#fn12][12]]}\\
\\

<<v19>>
19 Deine Nachkommen wären (zahlreich) wie der Sand /\\
 und deine leiblichen Kinder wie seine Körner. /\\
 Ihr Name wäre in meinen Augen nicht getilgt und gelöscht.
^{[[#fn13][13]]}\\
\\

<<v20>>
**** Die glückliche Heimkehr aus Babel: 48,20-22
     :PROPERTIES:
     :CUSTOM_ID: die-glückliche-heimkehr-aus-babel-4820-22
     :END:
20 Heraus aus Babel, flieht aus Chaldäa! /\\
 Verkündet es jauchzend, damit man es hört. Ruft es hinaus bis ans Ende
der Erde! /\\
 Ruft: Der Herr hat seinen Knecht Jakob ausgelöst. ^{[[#fn14][14]]}\\
\\

<<v21>>
21 Sie litten keinen Durst, als er sie durch die Wüste führte; /\\
 Wasser ließ er für sie aus dem Felsen sprudeln, /\\
 er spaltete den Felsen und es strömte das Wasser. ^{[[#fn15][15]]}\\
\\

<<v22>>
22 [Die Ruchlosen finden keinen Frieden, spricht der Herr.]
^{[[#fn16][16]]}\\
\\

^{[[#fnm1][1]]} ℘ 43,9

^{[[#fnm2][2]]} ℘ 42,9

^{[[#fnm3][3]]} Willst du, wörtlich: Wollt ihr.

^{[[#fnm4][4]]} ℘ Dtn 4,20

^{[[#fnm5][5]]} 10b: prüfte: Text korr. nach dem Qumran-Text; H:
erwählte.

^{[[#fnm6][6]]} ℘ 42,8

^{[[#fnm7][7]]} mein Name: ergänzt nach G.

^{[[#fnm8][8]]} ℘ 44,6

^{[[#fnm9][9]]} ℘ Ps 33,9

^{[[#fnm10][10]]} ℘ 45,19

^{[[#fnm11][11]]} Zusatz aus einem anderen Zusammenhang (vgl. 61,1).

^{[[#fnm12][12]]} ℘ Dtn 5,29; Ps 81,14-17

^{[[#fnm13][13]]} ℘ Gen 22,17

^{[[#fnm14][14]]} ℘ 52,11; Jer 51,6; Offb 18,4

^{[[#fnm15][15]]} ℘ Ex 17,6

^{[[#fnm16][16]]} ℘ 57,21
