:PROPERTIES:
:ID:       93fcde56-fc5b-407d-bcb8-fac84601903e
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_43.html][43]] [[file:Jes_44.html][44]] *45*
[[file:Jes_46.html][46]] [[file:Jes_47.html][47]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 45
  :PROPERTIES:
  :CUSTOM_ID: jes-45
  :END:

<<verses>>

<<v1>>
1 So spricht der Herr zu Kyrus, seinem Gesalbten, /\\
 den er an der rechten Hand gefasst hat, um ihm die Völker zu
unterwerfen, um die Könige zu entwaffnen, /\\
 um ihm die Türen zu öffnen und kein Tor verschlossen zu halten:
^{[[#fn1][1]]}\\
\\

<<v2>>
2 Ich selbst gehe vor dir her /\\
 und ebne die Berge ein. Ich zertrümmere die bronzenen Tore /\\
 und zerschlage die eisernen Riegel.\\
\\

<<v3>>
3 Ich gebe dir verborgene Schätze /\\
 und Reichtümer, die im Dunkel versteckt sind. So sollst du erkennen,
dass ich der Herr bin, /\\
 der dich bei deinem Namen ruft, ich, Israels Gott. ^{[[#fn2][2]]}\\
\\

<<v4>>
4 Um meines Knechtes Jakob willen, /\\
 um Israels, meines Erwählten, willen /\\
 habe ich dich bei deinem Namen gerufen; ich habe dir einen Ehrennamen
gegeben, /\\
 ohne dass du mich kanntest.\\
\\

<<v5>>
5 Ich bin der Herr und sonst niemand; /\\
 außer mir gibt es keinen Gott. Ich habe dir den Gürtel angelegt /\\
 ohne dass du mich kanntest,\\
\\

<<v6>>
6 damit man vom Aufgang der Sonne bis zu ihrem Untergang erkennt, /\\
 dass es außer mir keinen Gott gibt. /\\
 Ich bin der Herr und sonst niemand. ^{[[#fn3][3]]}\\
\\

<<v7>>
7 Ich erschaffe das Licht und mache das Dunkel, /\\
 ich bewirke das Heil und erschaffe das Unheil. /\\
 Ich bin der Herr, der das alles vollbringt. ^{[[#fn4][4]]}\\
\\

<<v8>>
8 Taut, ihr Himmel, von oben, /\\
 ihr Wolken, lasst Gerechtigkeit regnen! Die Erde tue sich auf und
bringe das Heil hervor, /\\
 sie lasse Gerechtigkeit sprießen. /\\
 Ich, der Herr, will es vollbringen. ^{[[#fn5][5]]}\\
\\

<<v9>>
**** Gegen die Unzufriedenen und die Zweifler: 45,9-13
     :PROPERTIES:
     :CUSTOM_ID: gegen-die-unzufriedenen-und-die-zweifler-459-13
     :END:
9 Weh dem, der mit seinem Schöpfer rechtet, /\\
 er, eine Scherbe unter irdenen Scherben. Sagt denn der Ton zu dem
Töpfer: /\\
 Was machst du mit mir?, und zu dem, der ihn verarbeitet: /\\
 Du hast kein Geschick? ^{[[#fn6][6]][[#fn7][7]]}\\
\\

<<v10>>
10 Weh dem, der zum Vater sagt: Warum zeugtest du mich?, /\\
 und zur Mutter: Warum brachtest du mich zur Welt?\\
\\

<<v11>>
11 So spricht der Herr, /\\
 der Heilige Israels und sein Schöpfer: Wollt ihr mir etwa Vorwürfe
machen wegen meiner Kinder /\\
 und Vorschriften über das Werk meiner Hände? ^{[[#fn8][8]]}\\
\\

<<v12>>
12 Ich habe die Erde gemacht /\\
 und die Menschen auf ihr geschaffen. Ich habe den Himmel ausgespannt
mit meinen Händen /\\
 und ich befehle seinem ganzen Heer.\\
\\

<<v13>>
13 Ich habe ihn (Kyrus) aus Gerechtigkeit zum Aufbruch veranlasst. /\\
 Alle Wege ebne ich ihm. Er baut meine Stadt wieder auf, /\\
 mein verschlepptes Volk lässt er frei, aber nicht für Lösegeld oder
Geschenke. /\\
 Der Herr der Heere hat gesprochen.\\
\\

<<v14>>
**** Die Huldigung der Heidenvölker: 45,14-25
     :PROPERTIES:
     :CUSTOM_ID: die-huldigung-der-heidenvölker-4514-25
     :END:
14 So spricht der Herr: Die Ägypter mit ihren Erträgen, /\\
 die Kuschiter mit ihrem Gewinn und die groß gewachsenen Sebaiter /\\
 werden zu dir kommen und dir gehören; /\\
 in Ketten werden sie hinter dir herziehen. Sie werfen sich nieder vor
dir und bekennen: /\\
 Nur bei dir gibt es einen Gott /\\
 und sonst gibt es keinen.\\
\\

<<v15>>
15 Wahrhaftig, du bist ein verborgener Gott. /\\
 Israels Gott ist der Retter.\\
\\

<<v16>>
16 Schmach und Schande kommt über sie alle, /\\
 die Götzenschmiede geraten in Schande. ^{[[#fn9][9]][[#fn10][10]]}\\
\\

<<v17>>
17 Israel aber wird vom Herrn gerettet, /\\
 wird für immer errettet. Über euch kommt keine Schande und Schmach mehr
/\\
 für immer und ewig.\\
\\

<<v18>>
18 Denn so spricht der Herr, der den Himmel erschuf, /\\
 er ist der Gott, der die Erde geformt und gemacht hat - er ist es, der
sie erhält, /\\
 er hat sie nicht als Wüste geschaffen, er hat sie zum Wohnen gemacht -:
/\\
 Ich bin der Herr und sonst niemand. ^{[[#fn11][11]]}\\
\\

<<v19>>
19 Ich habe nicht im Verborgenen geredet, /\\
 irgendwo in einem finsteren Land. Ich habe nicht zum Geschlecht Jakobs
gesagt: /\\
 Sucht mich im leeren Raum! Ich bin der Herr, der die Wahrheit spricht
/\\
 und der verkündet, was recht ist. ^{[[#fn12][12]]}\\
\\

<<v20>>
20 Versammelt euch, kommt alle herbei, /\\
 tretet herzu, die ihr aus den Völkern entkommen seid. Wer hölzerne
Götzen umherträgt, hat keine Erkenntnis, /\\
 wer einen Gott anbetet, der niemanden rettet. ^{[[#fn13][13]]}\\
\\

<<v21>>
21 Macht es bekannt, bringt es vor, /\\
 beratet euch untereinander: Wer hat das alles seit langem verkündet /\\
 und längst im Voraus angesagt? War es nicht ich, der Herr? /\\
 Es gibt keinen Gott außer mir; /\\
 außer mir gibt es keinen gerechten und rettenden Gott.\\
\\

<<v22>>
22 Wendet euch mir zu und lasst euch erretten, /\\
 ihr Menschen aus den fernsten Ländern der Erde; /\\
 denn ich bin Gott und sonst niemand.\\
\\

<<v23>>
23 Ich habe bei mir selbst geschworen /\\
 und mein Mund hat die Wahrheit gesprochen, /\\
 es ist ein unwiderrufliches Wort: Vor mir wird jedes Knie sich beugen
/\\
 und jede Zunge wird bei mir schwören: ^{[[#fn14][14]]}\\
\\

<<v24>>
24 Nur beim Herrn - sagt man von mir - gibt es Rettung und Schutz. /\\
 Beschämt kommen alle zu ihm, die sich ihm widersetzten.\\
\\

<<v25>>
25 Alle Nachkommen Israels bekommen ihr Recht /\\
 und erlangen Ruhm durch den Herrn.\\
\\

^{[[#fnm1][1]]} um die Könige zu entwaffnen, wörtlich: um den Gürtel an
den Hüften der Könige zu lösen.

^{[[#fnm2][2]]} ℘ 41,25

^{[[#fnm3][3]]} ℘ 59,19; 45,18

^{[[#fnm4][4]]} ℘ Am 3,6

^{[[#fnm5][5]]} Dieser Vers hat die Anregung zum Lied «Tauet, Himmel,
den Gerechten» gegeben.

^{[[#fnm6][6]]} ℘ 29,16; Jer 18,6; Röm 9,20f

^{[[#fnm7][7]]} kein Geschick, wörtlich: keine Hände; Text korr.

^{[[#fnm8][8]]} 11c: Text korr.

^{[[#fnm9][9]]} ℘ 41,11

^{[[#fnm10][10]]} 16a: sie alle: nach G die Gegner Gottes.

^{[[#fnm11][11]]} ℘ 45,6

^{[[#fnm12][12]]} ℘ 48,16

^{[[#fnm13][13]]} Angeredet sind die aus den Völkern, die den Kampf
überlebt haben.

^{[[#fnm14][14]]} ℘ Röm 14,11; Phil 2,10f
