:PROPERTIES:
:ID:       33182abe-cd4b-4dd8-ac2c-7df0fa046a94
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_28.html][28]] [[file:Jes_29.html][29]] *30*
[[file:Jes_31.html][31]] [[file:Jes_32.html][32]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 30
  :PROPERTIES:
  :CUSTOM_ID: jes-30
  :END:

<<verses>>

<<v1>>
**** Die Nutzlosigkeit des Bündnisses mit Ägypten: 30,1-7
     :PROPERTIES:
     :CUSTOM_ID: die-nutzlosigkeit-des-bündnisses-mit-ägypten-301-7
     :END:
1 Weh den trotzigen Söhnen - Spruch des Herrn -, /\\
 die einen Plan ausführen, der nicht von mir ist, und ein Bündnis
schließen, /\\
 das nicht nach meinem Sinn ist; /\\
 sie häufen Sünde auf Sünde. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Sie machen sich auf den Weg nach Ägypten, /\\
 ohne meinen Mund zu befragen. Sie suchen beim Pharao Zuflucht und
Schutz /\\
 und flüchten in den Schatten Ägyptens.\\
\\

<<v3>>
3 Doch der Schutz des Pharao bringt euch nur Schande, /\\
 die Flucht in den Schatten Ägyptens bringt euch nur Schmach.\\
\\

<<v4>>
4 Wenn auch Israels Fürsten nach Zoan gingen /\\
 und seine Boten nach Hanes: ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Sie werden doch alle enttäuscht von dem Volk, /\\
 das nichts nützt, das niemand Nutzen und Hilfe verschafft, /\\
 sondern nur Schande und Schmach bringt.\\
\\

<<v6>>
6 Ausspruch über die Tiere des Negeb: Durch ein Land der Ängste und
Nöte, /\\
 der jungen Löwen, der knurrenden Löwen, /\\
 der Nattern und fliegenden Schlangen bringen sie ihren Reichtum /\\
 auf dem Rücken der Esel, ihre Schätze auf dem Höcker der Kamele /\\
 zu dem Volk, das nichts nützt. ^{[[#fn3][3]]}\\
\\

<<v7>>
7 Nichtig und nutzlos ist die Hilfe Ägyptens; /\\
 darum nenne ich es: die untätige Rahab. ^{[[#fn4][4]]}\\
\\

<<v8>>
**** Die Bestrafung des trotzigen Volkes: 30,8-17
     :PROPERTIES:
     :CUSTOM_ID: die-bestrafung-des-trotzigen-volkes-308-17
     :END:
8 Nun geh, schreib es vor ihren Augen auf eine Tafel, /\\
 ritz es als Inschrift ein, /\\
 damit es für künftige Zeiten auf immer bezeugt ist:\\
\\

<<v9>>
9 Sie sind ein trotziges Volk, missratene Söhne, /\\
 Söhne, die auf die Weisung des Herrn nicht hören. ^{[[#fn5][5]]}\\
\\

<<v10>>
10 Sie sagen zu den Sehern: Seht nichts!, /\\
 und zu den Propheten: Erschaut für uns ja nicht, was wahr ist, sondern
sagt, was uns schmeichelt, /\\
 erschaut für uns das, was uns täuscht. ^{[[#fn6][6]][[#fn7][7]]}\\
\\

<<v11>>
11 Weicht nur ab vom rechten Weg, /\\
 verlasst den richtigen Pfad, /\\
 lasst uns in Ruhe mit dem Heiligen Israels!\\
\\

<<v12>>
12 Darum - so spricht der Heilige Israels: /\\
 Weil ihr dieses Wort missachtet, weil ihr auf Ränke vertraut /\\
 und euch auf das Falsche verlasst,\\
\\

<<v13>>
13 darum wird eure Schuld für euch sein /\\
 wie ein herabfallendes Bruchstück /\\
 von einer hoch aufragenden Mauer, /\\
 die dann plötzlich, urplötzlich einstürzt.\\
\\

<<v14>>
14 Sie zerbricht wie der Krug eines Töpfers, /\\
 den man ohne Erbarmen zerschlägt, sodass sich unter all den Stücken
keine Scherbe mehr findet, /\\
 mit der man Feuer vom Herd holen kann /\\
 oder Wasser schöpfen aus der Zisterne.\\
\\

<<v15>>
15 Denn so spricht der Herr, der Heilige Israels: Nur in Umkehr und Ruhe
liegt eure Rettung, /\\
 nur Stille und Vertrauen verleihen euch Kraft. Doch ihr habt nicht
gewollt, /\\
\\

<<v16>>
16 sondern gesagt: Nein, auf Rossen wollen wir dahinfliegen. /\\
 Darum sollt ihr jetzt fliehen. Ihr habt gesagt: Auf Rennpferden wollen
wir reiten. /\\
 Darum rennen die Verfolger euch nach. ^{[[#fn8][8]]}\\
\\

<<v17>>
17 Tausende werden zittern, wenn ein Einziger droht, /\\
 wenn nur fünf euch drohen, ergreift ihr alle die Flucht, bis das, was
von euch übrig ist, aussieht, /\\
 wie ein Fahnenmast auf dem Gipfel eines Berges, /\\
 wie ein Feldzeichen auf dem Hügel. ^{[[#fn9][9]][[#fn10][10]]}\\
\\

<<v18>>
**** Die Begnadigung des Volkes: 30,18-26
     :PROPERTIES:
     :CUSTOM_ID: die-begnadigung-des-volkes-3018-26
     :END:
18 Darum wartet der Herr darauf, /\\
 euch seine Gnade zu zeigen, darum erhebt er sich, /\\
 um euch sein Erbarmen zu schenken. Denn der Herr ist ein Gott des
Rechtes; /\\
 wohl denen, die auf ihn warten. ^{[[#fn11][11]]}\\
\\

<<v19>>
19 Ja, du Volk auf dem Berg Zion, /\\
 das in Jerusalem wohnt, /\\
 du brauchst jetzt nicht mehr zu weinen. Der Herr ist dir gnädig, wenn
du um Hilfe schreist; /\\
 er wird dir antworten, sobald er dich hört.\\
\\

<<v20>>
20 Auch wenn dir der Herr bisher nur wenig Brot und nicht genug Wasser
gab, /\\
 so wird er, dein Lehrer, sich nicht mehr verbergen. Deine Augen werden
deinen Lehrer sehen, /\\
\\

<<v21>>
21 deine Ohren werden es hören, wenn er dir nachruft: Hier ist der Weg,
auf ihm müsst ihr gehen, /\\
 auch wenn ihr selbst rechts oder links gehen wolltet.\\
\\

<<v22>>
22 Dann wirst du deine Götzen aus Silber /\\
 und deine Götterbilder aus Gold entweihen. Wie Abfall wirfst du sie weg
und sagst: /\\
 Hinaus mit euch!\\
\\

<<v23>>
23 Dann spendet er Regen für die Saat, /\\
 die du auf den Acker gesät hast. Das Korn, das auf dem Acker
heranreift, /\\
 wird üppig und fett sein. /\\
 Auf weiten Wiesen weidet dein Vieh an jenem Tag.\\
\\

<<v24>>
24 Die Rinder und Esel, die dir bei der Feldarbeit helfen, /\\
 bekommen würziges Futter zu fressen, /\\
 das man mit Schaufel und Gabel gemischt hat.\\
\\

<<v25>>
25 Auf allen hohen Bergen und stattlichen Hügeln /\\
 gibt es Bäche voll Wasser am Tag des großen Mordens, /\\
 wenn die Türme einstürzen. ^{[[#fn12][12]][[#fn13][13]]}\\
\\

<<v26>>
26 Zu der Zeit, wenn der Herr die Leiden seines Volkes heilt und seine
Wunden verbindet, wird das Licht des Mondes so hell sein wie das Licht
der Sonne und das Licht der Sonne wird siebenmal so stark sein wie das
Licht von sieben Tagen.\\
\\

<<v27>>
**** Das Gericht über Assur: 30,27-33
     :PROPERTIES:
     :CUSTOM_ID: das-gericht-über-assur-3027-33
     :END:
27 Seht her, der Herr [sein Name] kommt aus der Ferne. /\\
 Sein Zorn ist entflammt, /\\
 gewaltig drohend, zieht er heran. Seine Lippen sind voll grollendem
Zorn, /\\
 seine Zunge ist wie ein verzehrendes Feuer, ^{[[#fn14][14]]}\\
\\

<<v28>>
28 sein Atem wie ein reißender Bach, /\\
 der bis an den Hals reicht. Er spannt die Völker ins Joch /\\
 und legt den Nationen den Zaum an, /\\
 um sie in die Irre und ins Unheil zu führen.\\
\\

<<v29>>
29 Dann singt ihr Lieder wie in der Nacht, /\\
 in der man sich heiligt für das Fest. Ihr freut euch von Herzen /\\
 wie die Pilger, die unter dem Klang ihrer Flöten /\\
 zum Berg des Herrn, zu Israels Felsen, hinaufziehen.\\
\\

<<v30>>
30 Der Herr lässt seine mächtige Stimme erschallen /\\
 und man sieht, wie sein Arm herabzuckt mit zornigem Grollen und
verzehrendem Feuer, /\\
 mit Sturm, Gewitter und Hagel. ^{[[#fn15][15]]}\\
\\

<<v31>>
31 Vor der Stimme des Herrn wird Assur erschrecken, /\\
 wenn er zuschlägt mit seinem Stock,\\
\\

<<v32>>
32 jedes Mal, wenn die Zuchtrute auf Assur herabsaust, /\\
 mit der der Herr auf es einschlägt. Unter dem Klang von Pauken und
Zithern /\\
 und bei schwungvollem Reigentanz kämpft er gegen Assur.
^{[[#fn16][16]]}\\
\\

<<v33>>
33 Ja, schon längst ist eine Feuerstelle bereitet, /\\
 auch für den König ist sie bestimmt; /\\
 tief ist sie und weit; ein Holzstoß ist da, Feuer und Brennholz in
Menge, /\\
 der Atem des Herrn brennt darin wie ein Schwefelstrom.\\
\\

^{[[#fnm1][1]]} ℘ 31,1; 2 Kön 18,21; Jer 2,18

^{[[#fnm2][2]]} Zu Zoan vgl. die Anmerkung zu 19,11. Hanes: südlich von
Memfis. Hierher kommen die Boten Hiskijas 703/2 v. Chr.

^{[[#fnm3][3]]} Spricht von den Gefahren, die für die Gesandtschaft
Hiskijas von den Tieren drohen.

^{[[#fnm4][4]]} Ägypten wird sich nicht, wie einst Rahab (das Urmeer),
die gegen den Schöpfergott kämpfte, erheben, sondern untätig bleiben.

^{[[#fnm5][5]]} ℘ 1,4

^{[[#fnm6][6]]} ℘ Am 2,12; 7,12f

^{[[#fnm7][7]]} 10b: zu den Propheten; wörtlich: zu den Schauenden.

^{[[#fnm8][8]]} In H zwei Wortspiele.

^{[[#fnm9][9]]} ℘ Dtn 32,30

^{[[#fnm10][10]]} 17a: werden zittern: Text korr.

^{[[#fnm11][11]]} ℘ Ps 2,12

^{[[#fnm12][12]]} ℘ 2,14

^{[[#fnm13][13]]} 25cd.26: Apokalyptischer Ausblick auf die Endzeit.

^{[[#fnm14][14]]} ℘ 29,6

^{[[#fnm15][15]]} ℘ 30,27; 29,6

^{[[#fnm16][16]]} Text unsicher.
