:PROPERTIES:
:ID:       b30619bd-24aa-4819-b609-41f1b266d042
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_61.html][61]] [[file:Jes_62.html][62]] *63*
[[file:Jes_64.html][64]] [[file:Jes_65.html][65]]
[[file:Jes_66.html][66]]

--------------

* Jes 63
  :PROPERTIES:
  :CUSTOM_ID: jes-63
  :END:

<<verses>>

<<v1>>
** Völkergericht und endzeitliches Heil: 63,1 - 66,24
   :PROPERTIES:
   :CUSTOM_ID: völkergericht-und-endzeitliches-heil-631---6624
   :END:
**** Die Ankündigung des Gerichts an den Völkern: 63,1-6
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-des-gerichts-an-den-völkern-631-6
     :END:
1 Wer ist jener, der aus Edom kommt, /\\
 aus Bozra in rot gefärbten Gewändern? Er schreitet in prächtigen
Kleidern daher /\\
 in seiner gewaltigen Kraft. Ich bin es, ich verkünde Gerechtigkeit, /\\
 ich bin der mächtige Helfer. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Warum aber ist dein Gewand so rot, /\\
 ist dein Kleid wie das eines Mannes, der die Kelter tritt?\\
\\

<<v3>>
3 Ich allein trat die Kelter; /\\
 von den Völkern war niemand dabei. Da zertrat ich sie voll Zorn, /\\
 zerstampfte sie in meinem Grimm. Ihr Blut spritzte auf mein Gewand /\\
 und befleckte meine Kleider. ^{[[#fn2][2]]}\\
\\

<<v4>>
4 Denn ein Tag der Rache lag mir im Sinn /\\
 und das Jahr der Erlösung war gekommen. ^{[[#fn3][3]]}\\
\\

<<v5>>
5 Ich sah mich um, doch niemand wollte mir helfen; /\\
 ich war bestürzt, weil keiner mir beistand. Da half mir mein eigener
Arm, /\\
 mein Zorn war meine Stütze. ^{[[#fn4][4]]}\\
\\

<<v6>>
6 Ich zertrat die Völker in meinem Zorn, /\\
 ich zerschmetterte sie in meinem Grimm /\\
 und ihr Blut ließ ich zur Erde rinnen. ^{[[#fn5][5]]}\\
\\

<<v7>>
**** Das Gebet des Volkes um Gottes Erscheinen: 63,7 - 64,11
     :PROPERTIES:
     :CUSTOM_ID: das-gebet-des-volkes-um-gottes-erscheinen-637---6411
     :END:
7 Die Huld des Herrn will ich preisen, /\\
 die ruhmreichen Taten des Herrn, alles, was der Herr für uns tat, /\\
 seine große Güte, die er dem Haus Israel erwies /\\
 in seiner Barmherzigkeit und seiner großen Huld. ^{[[#fn6][6]]}\\
\\

<<v8>>
8 Er sagte: Sie sind doch mein Volk, /\\
 meine Söhne, die nicht enttäuschen. /\\
 Er wurde ihr Retter in jeder Not.\\
\\

<<v9>>
9 Nicht ein Bote oder ein Engel, /\\
 sondern sein Angesicht hat sie gerettet. In seiner Liebe und seinem
Mitleid /\\
 hat er selbst sie erlöst. Er hat sie emporgehoben und sie getragen /\\
 in all den Tagen der Vorzeit. ^{[[#fn7][7]]}\\
\\

<<v10>>
10 Sie aber lehnten sich gegen ihn auf /\\
 und betrübten seinen heiligen Geist. Da wandelte er sich und wurde ihr
Feind, /\\
 ja, er führte Krieg gegen sie.\\
\\

<<v11>>
11 Nun dachten sie an die Tage der Vorzeit, /\\
 die Zeit seines Knechtes Mose: Wo ist der, der den Hirten seiner Schafe
aus dem Meer herausgeführt hat? /\\
 Wo ist der, der seinen heiligen Geist in ihn gelegt hat,
^{[[#fn8][8]][[#fn9][9]]}\\
\\

<<v12>>
12 der an der rechten Seite des Mose ging /\\
 und ihm half mit mächtigem Arm, der das Wasser vor ihnen zerteilte, /\\
 um sich ewigen Ruhm zu verschaffen,\\
\\

<<v13>>
13 der sie durch die Fluten führte wie Pferde durch die Steppe, /\\
 ohne dass sie strauchelten? ^{[[#fn10][10]]}\\
\\

<<v14>>
14 Der Geist des Herrn ließ sie zur Ruhe kommen, /\\
 wie das Vieh, das ins Tal hinabzieht. So führtest du einst dein Volk,
/\\
 um dir herrlichen Ruhm zu verschaffen.\\
\\

<<v15>>
15 Blick vom Himmel herab und sieh her /\\
 von deiner heiligen, herrlichen Wohnung! Wo ist dein leidenschaftlicher
Eifer /\\
 und deine Macht, dein großes Mitleid und dein Erbarmen? /\\
 Halte dich nicht von uns fern! ^{[[#fn11][11]][[#fn12][12]]}\\
\\

<<v16>>
16 Du bist doch unser Vater; /\\
 denn Abraham weiß nichts von uns, Israel will uns nicht kennen. /\\
 Du, Herr, bist unser Vater, /\\
 «Unser Erlöser von jeher» wirst du genannt. ^{[[#fn13][13]]}\\
\\

<<v17>>
17 Warum lässt du uns, Herr, von deinen Wegen abirren /\\
 und machst unser Herz hart, /\\
 sodass wir dich nicht mehr fürchten? Kehre zurück um deiner Knechte
willen, /\\
 um der Stämme willen, die dein Eigentum sind.\\
\\

<<v18>>
18 Erst vor kurzem haben unsere Feinde dein heiliges Volk vertrieben;
/\\
 dein Heiligtum haben sie zertreten. ^{[[#fn14][14]]}\\
\\

<<v19>>
19 Uns geht es, als wärest du nie unser Herrscher gewesen, /\\
 als wären wir nicht nach deinem Namen benannt. Reiß doch den Himmel auf
und komm herab, /\\
 sodass die Berge zittern vor dir.\\
\\

^{[[#fnm1][1]]} Er schreitet: Text korr. nach Symmachus und Vg. - Gott
wird als siegreicher Krieger geschildert.

^{[[#fnm2][2]]} ℘ Offb 14,20; 19,15.13

^{[[#fnm3][3]]} ℘ 34,8; 61,2

^{[[#fnm4][4]]} ℘ 59,16

^{[[#fnm5][5]]} ich zerschmetterte sie: Text korr. nach vielen
H-Handschriften (vgl. 14,25); H: ich machte sie trunken.

^{[[#fnm6][6]]} ℘ Ps 89,2

^{[[#fnm7][7]]} ℘ 46,3f

^{[[#fnm8][8]]} ℘ Hebr 13,20

^{[[#fnm9][9]]} 11-14: Es wird an den Auszug aus Ägypten erinnert. 11b:
seines Knechtes: Text korr.; H: seines Volkes.

^{[[#fnm10][10]]} ℘ Ps 106,9

^{[[#fnm11][11]]} ℘ Dtn 26,15; Jes 64,11

^{[[#fnm12][12]]} 15e: Halte . . . fern: Text korr.; vgl. G und 64,11.

^{[[#fnm13][13]]} Israels Stammväter können dem Volk nicht helfen.

^{[[#fnm14][14]]} ℘ Offb 11,2
