:PROPERTIES:
:ID:       311614d1-ae3d-4c5f-9060-52bc06eb031b
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_20.html][20]] [[file:Jes_21.html][21]] *22*
[[file:Jes_23.html][23]] [[file:Jes_24.html][24]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 22
  :PROPERTIES:
  :CUSTOM_ID: jes-22
  :END:

<<verses>>

<<v1>>
*** Das Gericht über Jerusalem: 22,1-25
    :PROPERTIES:
    :CUSTOM_ID: das-gericht-über-jerusalem-221-25
    :END:
**** Die unverbesserlichen Einwohner Jerusalems: 22,1-14
     :PROPERTIES:
     :CUSTOM_ID: die-unverbesserlichen-einwohner-jerusalems-221-14
     :END:
1 Ausspruch über das Tal der Vision. Was ist mit dir? /\\
 Warum sind deine Bewohner alle auf die Dächer gestiegen,
^{[[#fn1][1]]}\\
\\

<<v2>>
2 du Stadt voll Lärm und Gedränge, /\\
 du fröhliche Burg? Deine Toten wurden nicht vom Schwert getötet, /\\
 sie sind nicht im Krieg gefallen.\\
\\

<<v3>>
3 Alle deine Anführer sind gemeinsam geflohen, /\\
 ohne einen einzigen Bogenschuss wurden sie gefangen; alle, die man von
dir noch fand, wurden gefesselt, /\\
 wenn sie auch noch so weit flohen. ^{[[#fn2][2]]}\\
\\

<<v4>>
4 Darum sage ich: Blickt von mir weg, /\\
 ich weine in bitterem Schmerz. Bemüht euch nicht, mich zu trösten /\\
 über die Misshandlung der Tochter, meines Volkes.\\
\\

<<v5>>
5 Denn einen Tag der Bestürzung, der Verwüstung und Verwirrung /\\
 schickt Gott, der Herr der Heere. Im Tal der Vision macht man
gewaltigen Lärm /\\
 und stürmt mit Geschrei gegen den Berg an. ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Elam hat den Köcher umgehängt, /\\
 vor die Wagen Arams sind Pferde gespannt, /\\
 Kir hat den Schild aus der Hülle genommen. ^{[[#fn4][4]]}\\
\\

<<v7>>
7 Deine herrlichen Täler füllten sich mit Wagen, /\\
 vor deinem Tor stellten sich die Reiter auf.\\
\\

<<v8>>
8 So nahm er Juda jeden Schutz. /\\
 Ihr aber habt an jenem Tag nach euren Waffen im «Waldhaus» gesehen;
^{[[#fn5][5]]}\\
\\

<<v9>>
9 ihr habt festgestellt, wie rissig die (Mauer der) Davidstadt war; /\\
 ihr habt im unteren Teich das Wasser gesammelt\\
\\

<<v10>>
10 und habt Jerusalems Häuser gezählt; /\\
 ihr habt die Häuser abgerissen /\\
 und (mit den Steinen) die Mauer befestigt;\\
\\

<<v11>>
11 ihr habt zwischen den beiden Mauern ein Becken angelegt, /\\
 um das Wasser des alten Teiches zu sammeln, doch ihr habt nicht auf den
geblickt, der alles bewirkt; /\\
 ihr habt nicht auf den geschaut, der alles aus der Ferne bestimmt.
^{[[#fn6][6]][[#fn7][7]]}\\
\\

<<v12>>
12 An jenem Tag befahl Gott, der Herr der Heere, zu weinen und zu
klagen, /\\
 sich eine Glatze zu scheren und Trauergewänder zu tragen.\\
\\

<<v13>>
13 Doch was sieht man: Freude und Frohsinn, /\\
 Rindertöten und Schafeschlachten, /\\
 Fleischessen und Weintrinken, (und ihr sagt:) Lasst uns essen und
trinken, /\\
 denn morgen sind wir tot. ^{[[#fn8][8]]}\\
\\

<<v14>>
14 Der Herr der Heere hat mir offenbart: /\\
 Diese Schuld wird euch bis zu eurem Tod nicht vergeben, /\\
 spricht Gott, der Herr der Heere.\\
\\

<<v15>>
**** Die Absetzung Schebnas: 22,15-19
     :PROPERTIES:
     :CUSTOM_ID: die-absetzung-schebnas-2215-19
     :END:
15 So spricht Gott, der Herr der Heere: Auf, geh zu dem Verwalter hier,
zu Schebna, dem Palastvorsteher, ^{[[#fn9][9]]}

<<v16>>
16 und sag: Wie kommst du dazu und wer bist du denn, dass du dir hier
ein Grab aushauen lässt? - Da lässt er sich hoch oben ein Grab aushauen,
im Felsen sich eine Wohnung ausmeißeln! -

<<v17>>
17 Gib Acht, der Herr wird dich in hohem Bogen wegschleudern.

<<v18>>
18 Er wird dich zu einem Knäuel zusammenwickeln und wie einen Ball in
ein geräumiges Land rollen. Dort wirst du sterben; dorthin kommen dann
deine Prunkwagen, du Schandfleck im Haus deines Herrn.

<<v19>>
19 Ich verjage dich aus deinem Amt, ich vertreibe dich von deinem
Posten. ^{[[#fn10][10]]}\\
\\

<<v20>>
**** Die Einsetzung Eljakims: 22,20-25
     :PROPERTIES:
     :CUSTOM_ID: die-einsetzung-eljakims-2220-25
     :END:
20 An jenem Tag werde ich meinen Knecht Eljakim, den Sohn Hilkijas,
berufen.

<<v21>>
21 Ich bekleide ihn mit deinem Gewand und lege ihm deine Schärpe um. Ich
übergebe ihm dein Amt und er wird für die Einwohner Jerusalems und für
das Haus Juda ein Vater sein.

<<v22>>
22 Ich lege ihm den Schlüssel des Hauses David auf die Schulter. Wenn er
öffnet, kann niemand schließen; wenn er schließt, kann niemand öffnen.
^{[[#fn11][11]]}

<<v23>>
23 Ich schlage ihn an einer festen Stelle als Pflock ein; er wird in
seinem Vaterhaus den Ehrenplatz einnehmen.

<<v24>>
24 Wenn sich aber all die vielen Mitglieder seines Vaterhauses mit
Kindern und Kindeskindern an ihn hängen, alle die Kännchen, die Töpfe
und Krüge, ^{[[#fn12][12]]}

<<v25>>
25 an jenem Tag - Spruch des Herrn der Heere - wird der Pflock, den man
an der festen Stelle eingeschlagen hat, nachgeben. Er wird herausbrechen
und herunterfallen, sodass alles zerbricht, was an ihm aufgehängt war.
Wahrhaftig, der Herr hat gesprochen.\\
\\

^{[[#fnm1][1]]} ℘ 22,5

^{[[#fnm2][2]]} H schwer verständlich, daher Übersetzung unsicher.

^{[[#fnm3][3]]} ℘ 22,1

^{[[#fnm4][4]]} Aram: Text korr. nach G; H: Adam.

^{[[#fnm5][5]]} Zu «Waldhaus», auch «Libanonwaldhaus» genannt, vgl. die
Anmerkung zu 1 Kön 7,2.

^{[[#fnm6][6]]} ℘ 2 Kön 20,20; Sir 48,17

^{[[#fnm7][7]]} aus der Ferne, andere Übersetzungsmöglichkeit: im
Voraus.

^{[[#fnm8][8]]} ℘ 1 Kor 15,32

^{[[#fnm9][9]]} ℘ 36,3.11.22

^{[[#fnm10][10]]} Ich vertreibe dich: Text korr. nach den alten
Übersetzungen (1. statt 3. Person).

^{[[#fnm11][11]]} ℘ Mt 16,19; Offb 3,7

^{[[#fnm12][12]]} mit Kindern und Kindeskindern, wörtlich: die
Schösslinge und die Blätter.
