:PROPERTIES:
:ID:       e0db69e6-3819-42fe-9bd4-bc368c0ed266
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_59.html][59]] [[file:Jes_60.html][60]] *61*
[[file:Jes_62.html][62]] [[file:Jes_63.html][63]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 61
  :PROPERTIES:
  :CUSTOM_ID: jes-61
  :END:

<<verses>>

<<v1>>
**** Die frohe Botschaft des Gesalbten Jahwes: 61,1-11
     :PROPERTIES:
     :CUSTOM_ID: die-frohe-botschaft-des-gesalbten-jahwes-611-11
     :END:
1 Der Geist Gottes, des Herrn, ruht auf mir; /\\
 denn der Herr hat mich gesalbt. Er hat mich gesandt, damit ich den
Armen eine frohe Botschaft bringe /\\
 und alle heile, deren Herz zerbrochen ist, damit ich den Gefangenen die
Entlassung verkünde /\\
 und den Gefesselten die Befreiung, ^{[[#fn1][1]]}\\
\\

<<v2>>
2 damit ich ein Gnadenjahr des Herrn ausrufe, /\\
 einen Tag der Vergeltung unseres Gottes, /\\
 damit ich alle Trauernden tröste, ^{[[#fn2][2]]}\\
\\

<<v3>>
3 die Trauernden Zions erfreue, /\\
 ihnen Schmuck bringe anstelle von Schmutz, Freudenöl statt
Trauergewand, /\\
 Jubel statt der Verzweiflung. Man wird sie «Die Eichen der
Gerechtigkeit» nennen, /\\
 «Die Pflanzung, durch die der Herr seine Herrlichkeit zeigt».
^{[[#fn3][3]][[#fn4][4]]}\\
\\

<<v4>>
4 Dann bauen sie die uralten Trümmerstätten wieder auf /\\
 und richten die Ruinen ihrer Vorfahren wieder her. Die verödeten Städte
erbauen sie neu, /\\
 die Ruinen vergangener Generationen. ^{[[#fn5][5]]}\\
\\

<<v5>>
5 Fremde stehen bereit und führen eure Herden auf die Weide, /\\
 Ausländer sind eure Bauern und Winzer. ^{[[#fn6][6]]}\\
\\

<<v6>>
6 Ihr alle aber werdet «Priester des Herrn» genannt, /\\
 man sagt zu euch «Diener unseres Gottes». Was die Völker besitzen,
werdet ihr genießen, /\\
 mit ihrem Reichtum könnt ihr euch brüsten. ^{[[#fn7][7]]}\\
\\

<<v7>>
7 Doppelte Schande mussten sie ertragen, /\\
 sie wurden angespuckt und verhöhnt; darum erhalten sie doppelten Besitz
in ihrem Land, /\\
 ewige Freude wird ihnen zuteil. ^{[[#fn8][8]]}\\
\\

<<v8>>
8 Denn ich, der Herr, liebe das Recht, /\\
 ich hasse Verbrechen und Raub. Ich bin treu und gebe ihnen den Lohn,
/\\
 ich schließe mit ihnen einen ewigen Bund. ^{[[#fn9][9]]}\\
\\

<<v9>>
9 Ihre Nachkommen werden bei allen Nationen bekannt sein /\\
 und ihre Kinder in allen Völkern. Jeder, der sie sieht, wird erkennen:
/\\
 Das sind die Nachkommen, die der Herr gesegnet hat. ^{[[#fn10][10]]}\\
\\

<<v10>>
10 Von Herzen will ich mich freuen über den Herrn. /\\
 Meine Seele soll jubeln über meinen Gott. Denn er kleidet mich in
Gewänder des Heils, /\\
 er hüllt mich in den Mantel der Gerechtigkeit, wie ein Bräutigam sich
festlich schmückt /\\
 und wie eine Braut ihr Geschmeide anlegt.
^{[[#fn11][11]][[#fn12][12]]}\\
\\

<<v11>>
11 Denn wie die Erde die Saat wachsen lässt /\\
 und der Garten die Pflanzen hervorbringt, so bringt Gott, der Herr,
Gerechtigkeit hervor /\\
 und Ruhm vor allen Völkern.\\
\\

^{[[#fnm1][1]]} ℘ Lk 4,18f; Jes 58,6

^{[[#fnm2][2]]} ℘ 34,8; 63,4

^{[[#fnm3][3]]} ℘ 60,21

^{[[#fnm4][4]]} erfreue: Text korr. - Schmuck anstelle von Schmutz,
wörtlich: «einen Turban anstelle von Staub». Staub streut man sich bei
Trauer auf den Kopf. In H ein Wortspiel.

^{[[#fnm5][5]]} ℘ 58,12

^{[[#fnm6][6]]} ℘ 60,10

^{[[#fnm7][7]]} ℘ Ex 19,6; 1 Petr 2,5.9; Offb 1,6; 20,6

^{[[#fnm8][8]]} Schande: Text korr.; H: eure Schande. - sie wurden
angespuckt: Text korr.; H: sie jubeln.

^{[[#fnm9][9]]} ℘ Ps 37,28; Jes 55,3

^{[[#fnm10][10]]} ℘ 65,23

^{[[#fnm11][11]]} ℘ 41,16; Offb 21,2

^{[[#fnm12][12]]} 10e: sich festlich schmückt: Text korr.; H:
Priesterdienst tut.
