:PROPERTIES:
:ID:       1d454159-45de-44ff-978e-3994d8374ff9
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_58.html][58]] [[file:Jes_59.html][59]] *60*
[[file:Jes_61.html][61]] [[file:Jes_62.html][62]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 60
  :PROPERTIES:
  :CUSTOM_ID: jes-60
  :END:

<<verses>>

<<v1>>
** Die künftige Herrlichkeit Zions: 60,1 - 62,12
   :PROPERTIES:
   :CUSTOM_ID: die-künftige-herrlichkeit-zions-601---6212
   :END:
**** Die Wallfahrt der Völker zum gesegneten Jerusalem: 60,1-22
     :PROPERTIES:
     :CUSTOM_ID: die-wallfahrt-der-völker-zum-gesegneten-jerusalem-601-22
     :END:
1 Auf, werde licht denn es kommt dein Licht /\\
 und die Herrlichkeit des Herrn geht leuchtend auf über dir.
^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v2>>
2 Denn siehe, Finsternis bedeckt die Erde /\\
 und Dunkel die Völker, doch über dir geht leuchtend der Herr auf, /\\
 seine Herrlichkeit erscheint über dir.\\
\\

<<v3>>
3 Völker wandern zu deinem Licht /\\
 und Könige zu deinem strahlenden Glanz. ^{[[#fn3][3]]}\\
\\

<<v4>>
4 Blick auf und schau umher: /\\
 Sie alle versammeln sich und kommen zu dir. Deine Söhne kommen von
fern, /\\
 deine Töchter trägt man auf den Armen herbei. ^{[[#fn4][4]]}\\
\\

<<v5>>
5 Du wirst es sehen und du wirst strahlen, /\\
 dein Herz bebt vor Freude und öffnet sich weit. Denn der Reichtum des
Meeres strömt dir zu, /\\
 die Schätze der Völker kommen zu dir. ^{[[#fn5][5]]}\\
\\

<<v6>>
6 Zahllose Kamele bedecken dein Land, /\\
 Dromedare aus Midian und Efa. Alle kommen von Saba, /\\
 bringen Weihrauch und Gold /\\
 und verkünden die ruhmreichen Taten des Herrn. ^{[[#fn6][6]]}\\
\\

<<v7>>
7 Alle Schafe von Kedar scharen sich bei dir, /\\
 die Widder von Nebajot stehen in deinem Dienst. Als willkommene Opfer
steigen sie auf meinen Altar; /\\
 so verherrliche ich mein herrliches Haus.\\
\\

<<v8>>
8 Wer sind die, die heranfliegen wie Wolken, /\\
 wie Tauben zu ihrem Schlag?\\
\\

<<v9>>
9 Die Schiffe kommen bei mir zusammen, /\\
 voran die Schiffe von Tarschisch, um deine Söhne mit ihrem Gold und
Silber /\\
 aus der Ferne zu bringen, zum Ruhm des Herrn, deines Gottes, /\\
 des Heiligen Israels, /\\
 weil er dich herrlich gemacht hat. ^{[[#fn7][7]][[#fn8][8]]}\\
\\

<<v10>>
10 Fremde bauen deine Mauern, /\\
 ihre Könige stehen in deinem Dienst. Denn in meinem Zorn habe ich dich
geschlagen, /\\
 aber in meinem Wohlwollen zeige ich dir mein Erbarmen. ^{[[#fn9][9]]}\\
\\

<<v11>>
11 Deine Tore bleiben immer geöffnet, /\\
 sie werden bei Tag und bei Nacht nicht geschlossen, damit man den
Reichtum der Völker zu dir hineintragen kann; /\\
 auch ihre Könige führt man herbei. ^{[[#fn10][10]]}\\
\\

<<v12>>
12 Denn jedes Volk und jedes Reich, /\\
 das dir nicht dient, geht zugrunde, /\\
 die Völker werden völlig vernichtet.\\
\\

<<v13>>
13 Die Pracht des Libanon kommt zu dir, /\\
 Zypressen, Platanen und Eschen zugleich, um meinen heiligen Ort zu
schmücken; /\\
 dann ehre ich den Platz, wo meine Füße ruhen. ^{[[#fn11][11]]}\\
\\

<<v14>>
14 Gebückt kommen die Söhne deiner Unterdrücker zu dir, /\\
 alle, die dich verachtet haben, werfen sich dir zu Füßen. Man nennt
dich «Die Stadt des Herrn» /\\
 und «Das Zion des Heiligen Israels». ^{[[#fn12][12]]}\\
\\

<<v15>>
15 Dafür, dass du verlassen warst und verhasst /\\
 und niemand dich besucht hat, mache ich dich zum ewigen Stolz, /\\
 zur Freude für alle Generationen. ^{[[#fn13][13]]}\\
\\

<<v16>>
16 Du wirst die Milch der Völker saugen /\\
 und an der Brust von Königen trinken. Dann wirst du erkennen, /\\
 dass ich, der Herr, dein Retter bin /\\
 und ich, der Starke Jakobs, dein Erlöser. ^{[[#fn14][14]]}\\
\\

<<v17>>
17 Statt Kupfer bringe ich Gold, /\\
 statt Eisen bringe ich Silber, /\\
 statt Holz Kupfer und statt Steine Eisen. Ich setze den Frieden als
Aufsicht über dich ein /\\
 und die Gerechtigkeit als deinen Vogt.\\
\\

<<v18>>
18 Man hört nichts mehr von Unrecht in deinem Land, /\\
 von Verheerung und Zerstörung in deinem Gebiet. Deine Mauern nennst du
«Rettung» /\\
 und deine Tore «Ruhm». ^{[[#fn15][15]]}\\
\\

<<v19>>
19 Bei Tag wird nicht mehr die Sonne dein Licht sein, /\\
 und um die Nacht zu erhellen, scheint dir nicht mehr der Mond, sondern
der Herr ist dein ewiges Licht, /\\
 dein Gott dein strahlender Glanz. ^{[[#fn16][16]]}\\
\\

<<v20>>
20 Deine Sonne geht nicht mehr unter /\\
 und dein Mond nimmt nicht mehr ab; denn der Herr ist dein ewiges Licht,
/\\
 zu Ende sind deine Tage der Trauer.\\
\\

<<v21>>
21 Dein Volk besteht nur aus Gerechten; /\\
 sie werden für immer das Land besitzen /\\
 als aufblühende Pflanzung des Herrn, als das Werk seiner Hände, /\\
 durch das er seine Herrlichkeit zeigt. ^{[[#fn17][17]][[#fn18][18]]}\\
\\

<<v22>>
22 Der Kleinste wird zu einer Tausendschaft, /\\
 der Geringste zu einem starken Volk. Ich, der Herr, führe es schnell
herbei, /\\
 sobald es Zeit dafür ist.\\
\\

^{[[#fnm1][1]]} ℘ Offb 21,23

^{[[#fnm2][2]]} 1-62,12: Diese Kapitel gehören nach Thema und
Gedankenführung enger zusammen und sind darin mit Jes 40 - 55 verwandt.

^{[[#fnm3][3]]} ℘ 2,2-5; Offb 21,24

^{[[#fnm4][4]]} ℘ 49,18; 66,12

^{[[#fnm5][5]]} ℘ Offb 21,24

^{[[#fnm6][6]]} ℘ Ps 72,10; Mt 2,11

^{[[#fnm7][7]]} ℘ 55,5

^{[[#fnm8][8]]} Die Schiffe kommen . . . zusammen: Text korr.; H: Auf
mich harren die Inseln.

^{[[#fnm9][9]]} ℘ 61,5; 54,8

^{[[#fnm10][10]]} ℘ Offb 21,25f

^{[[#fnm11][11]]} ℘ 41,19

^{[[#fnm12][12]]} ℘ Offb 3,9

^{[[#fnm13][13]]} ℘ 62,4

^{[[#fnm14][14]]} ℘ 49,23; 66,11; 49,26

^{[[#fnm15][15]]} ℘ Jer 6,7

^{[[#fnm16][16]]} 19b: die Nacht: eingefügt mit G und dem Qumran-Text.

^{[[#fnm17][17]]} ℘ 57,13; 65,9; Mt 5,5; Jes 61,3

^{[[#fnm18][18]]} 21d: seiner Hände: Text korr. nach G und dem
Qumran-Text; H: meiner Hände.
