:PROPERTIES:
:ID:       20cd9d4a-38f9-48c2-a364-2138a758a4e8
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_41.html][41]] [[file:Jes_42.html][42]] *43*
[[file:Jes_44.html][44]] [[file:Jes_45.html][45]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 43
  :PROPERTIES:
  :CUSTOM_ID: jes-43
  :END:

<<verses>>

<<v1>>
**** Die Heimkehr Israels: 43,1-7
     :PROPERTIES:
     :CUSTOM_ID: die-heimkehr-israels-431-7
     :END:
1 Jetzt aber - so spricht der Herr, /\\
 der dich geschaffen hat, Jakob, /\\
 und der dich geformt hat, Israel: Fürchte dich nicht, denn ich habe
dich ausgelöst, /\\
 ich habe dich beim Namen gerufen, /\\
 du gehörst mir. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Wenn du durchs Wasser schreitest, bin ich bei dir, /\\
 wenn durch Ströme, dann reißen sie dich nicht fort. Wenn du durchs
Feuer gehst, wirst du nicht versengt, /\\
 keine Flamme wird dich verbrennen.\\
\\

<<v3>>
3 Denn ich, der Herr, bin dein Gott, /\\
 ich, der Heilige Israels, bin dein Retter. Ich gebe Ägypten als
Kaufpreis für dich, /\\
 Kusch und Seba gebe ich für dich.\\
\\

<<v4>>
4 Weil du in meinen Augen teuer und wertvoll bist /\\
 und weil ich dich liebe, gebe ich für dich ganze Länder /\\
 und für dein Leben ganze Völker. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Fürchte dich nicht, denn ich bin mit dir. /\\
 Vom Osten bringe ich deine Kinder herbei, /\\
 vom Westen her sammle ich euch. ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Ich sage zum Norden: Gib her!, /\\
 und zum Süden: Halt nicht zurück! Führe meine Söhne heim aus der Ferne,
/\\
 meine Töchter vom Ende der Erde!\\
\\

<<v7>>
7 Denn jeden, der nach meinem Namen benannt ist, /\\
 habe ich zu meiner Ehre erschaffen, /\\
 geformt und gemacht. ^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v8>>
**** Gott, der einzige Retter: 43,8-13
     :PROPERTIES:
     :CUSTOM_ID: gott-der-einzige-retter-438-13
     :END:
8 Bringt das Volk her, das blind ist, obwohl es Augen hat, /\\
 und taub, obwohl es Ohren hat.\\
\\

<<v9>>
9 Alle Völker sollen sich versammeln, /\\
 die Nationen sollen zusammenkommen. Wer von ihnen kündigt dies an /\\
 und wer kann uns sagen, was früher war? Sie sollen ihre Zeugen stellen,
/\\
 damit sie Recht bekommen, /\\
 damit man (die Zeugen) hört und sagt: Es ist wahr. ^{[[#fn6][6]]}\\
\\

<<v10>>
10 Ihr seid meine Zeugen - Spruch des Herrn - /\\
 und auch mein Knecht, den ich erwählte, damit ihr erkennt und mir
glaubt /\\
 und einseht, dass ich es bin. Vor mir wurde kein Gott erschaffen /\\
 und auch nach mir wird es keinen geben.\\
\\

<<v11>>
11 Ich bin Jahwe, ich, /\\
 und außer mir gibt es keinen Retter.\\
\\

<<v12>>
12 Ich habe es selbst angekündet und euch gerettet, /\\
 ich habe es euch zu Gehör gebracht. Kein fremder (Gott) ist bei euch
gewesen. /\\
 Ihr seid meine Zeugen - Spruch des Herrn. Ich allein bin Gott; /\\
\\

<<v13>>
13 auch künftig werde ich es sein. Niemand kann mir etwas entreißen. /\\
 Ich handle. Wer kann es rückgängig machen?\\
\\

<<v14>>
**** Der Weg durch die Wüste: 43,14-21
     :PROPERTIES:
     :CUSTOM_ID: der-weg-durch-die-wüste-4314-21
     :END:
14 So spricht der Herr, euer Erlöser, /\\
 der Heilige Israels: Um euretwillen schicke ich (Boten) nach Babel /\\
 und reiße alle Riegel heraus, /\\
 die Chaldäer aber werden mit Ketten gefesselt. ^{[[#fn7][7]]}\\
\\

<<v15>>
15 Ich bin der Herr, euer Heiliger, /\\
 euer König, Israels Schöpfer.\\
\\

<<v16>>
16 So spricht der Herr, der einen Weg durchs Meer bahnt, /\\
 einen Pfad durch das gewaltige Wasser, ^{[[#fn8][8]]}\\
\\

<<v17>>
17 der Wagen und Rosse ausziehen lässt, /\\
 zusammen mit einem mächtigen Heer; doch sie liegen am Boden und stehen
nicht mehr auf, /\\
 sie sind erloschen und verglüht wie ein Docht.\\
\\

<<v18>>
18 Denkt nicht mehr an das, was früher war; /\\
 auf das, was vergangen ist, sollt ihr nicht achten. ^{[[#fn9][9]]}\\
\\

<<v19>>
19 Seht her, nun mache ich etwas Neues. /\\
 Schon kommt es zum Vorschein, merkt ihr es nicht? Ja, ich lege einen
Weg an durch die Steppe /\\
 und Straßen durch die Wüste. ^{[[#fn10][10]][[#fn11][11]]}\\
\\

<<v20>>
20 Die wilden Tiere werden mich preisen, /\\
 die Schakale und Strauße, denn ich lasse in der Steppe Wasser fließen
/\\
 und Ströme in der Wüste, /\\
 um mein Volk, mein erwähltes, zu tränken.\\
\\

<<v21>>
21 Das Volk, das ich mir erschaffen habe, /\\
 wird meinen Ruhm verkünden. ^{[[#fn12][12]]}\\
\\

<<v22>>
**** Die Schuld Israels und die Gnade Gottes: 43,22-28
     :PROPERTIES:
     :CUSTOM_ID: die-schuld-israels-und-die-gnade-gottes-4322-28
     :END:
22 Jakob, du hast mich nicht gerufen, /\\
 Israel, du hast dir mit mir keine Mühe gemacht. ^{[[#fn13][13]]}\\
\\

<<v23>>
23 Du brachtest mir keine Lämmer als Brandopfer dar /\\
 und mit Schlachtopfern hast du mich nicht geehrt. Ich habe dich nicht
zu Speiseopfern gezwungen /\\
 und von dir keinen Weihrauch gefordert und dich dadurch geplagt.\\
\\

<<v24>>
24 Du hast mir für dein Geld kein Gewürzrohr gekauft /\\
 und hast mich nicht gelabt mit dem Fett deiner Opfer. Nein, du hast mir
mit deinen Sünden Arbeit gemacht, /\\
 mit deinen üblen Taten hast du mich geplagt.\\
\\

<<v25>>
25 Ich, ich bin es, der um meinetwillen deine Vergehen auslöscht, /\\
 ich denke nicht mehr an deine Sünden. ^{[[#fn14][14]]}\\
\\

<<v26>>
26 Lade mich vor, gehen wir miteinander vor Gericht; /\\
 verteidige dich, damit du Recht bekommst. ^{[[#fn15][15]]}\\
\\

<<v27>>
27 Schon dein Urahn hat gesündigt; /\\
 deine Anführer sind mir untreu geworden;\\
\\

<<v28>>
28 deine Fürsten haben mein Heiligtum entweiht. /\\
 Darum habe ich Jakob preisgegeben, /\\
 damit man es dem Untergang weiht, /\\
 und Israel, damit man es verspottet. ^{[[#fn16][16]]}\\
\\

^{[[#fnm1][1]]} 1d: ausgelöst: vgl. die Anmerkung zu 41,14.

^{[[#fnm2][2]]} ganze Länder: Text korr.; H: Menschen.

^{[[#fnm3][3]]} ℘ 41,10

^{[[#fnm4][4]]} ℘ Jer 14,9

^{[[#fnm5][5]]} Alle, die zum Volk Gottes gehören, auch die in der
weiten Diaspora, sind seine Kinder (vgl. 1,2; 63,16; 64,7).

^{[[#fnm6][6]]} ℘ 48,3

^{[[#fnm7][7]]} 14e: H ist verderbt, daher Übersetzung unsicher; vgl. G.

^{[[#fnm8][8]]} 16f: Dieses Gotteswort erinnert an den Auszug aus
Ägypten und die Rettung am Schilfmeer (vgl. Ex 14).

^{[[#fnm9][9]]} ℘ 65,17

^{[[#fnm10][10]]} ℘ Offb 21,5

^{[[#fnm11][11]]} Straßen: nach dem Qumran-Text; H: Ströme (aus V. 20).

^{[[#fnm12][12]]} ℘ 1 Petr 2,9

^{[[#fnm13][13]]} 22-24: Israel hat Gott, der all das nicht braucht,
nicht wirklich gedient, sondern ihm nur Arbeit gemacht.

^{[[#fnm14][14]]} ℘ 44,22

^{[[#fnm15][15]]} 26b: verteidige dich, wörtlich: zähl auf.

^{[[#fnm16][16]]} 28a: Text korr., vgl. G; H: und ich entweihte die
Fürsten des Heiligtums.
