:PROPERTIES:
:ID:       e3f4d1ba-9e9e-4ef9-934a-f13973c5fd81
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_16.html][16]] [[file:Jes_17.html][17]] *18*
[[file:Jes_19.html][19]] [[file:Jes_20.html][20]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 18
  :PROPERTIES:
  :CUSTOM_ID: jes-18
  :END:

<<verses>>

<<v1>>
**** Ankündigung des Gerichts über Kusch: 18,1-7
     :PROPERTIES:
     :CUSTOM_ID: ankündigung-des-gerichts-über-kusch-181-7
     :END:
1 Weh dem Land der Heuschreckenschwärme /\\
 jenseits der Flüsse von Kusch. ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v2>>
2 Es schickt seine Boten aus auf dem Nil, /\\
 in Papyruskähnen über das Wasser. Geht, ihr schnellen Boten, /\\
 zu dem hoch gewachsenen Volk mit der glänzenden Haut, zu der Nation,
die man weit und breit fürchtet, /\\
 zu dem Volk, das kraftvoll alles zertritt, /\\
 dessen Land von den Flüssen durchschnitten wird.\\
\\

<<v3>>
3 Ihr Bewohner der Welt, ihr Bürger der Erde, /\\
 seht alle hin, wenn man das Zeichen aufstellt auf den Bergen, horcht
alle auf, /\\
 wenn man das Widderhorn bläst.\\
\\

<<v4>>
4 Denn so hat der Herr zu mir gesprochen: /\\
 Ich will mir alles betrachten von meinem Platz aus, unbewegt wie die
glühende Hitze am Mittag, /\\
 wie die Dunstwolken in der Hitze des Sommers.\\
\\

<<v5>>
5 Ja, noch vor der Ernte, wenn die Blüte vorbei ist /\\
 und die Frucht zur Traube heranreift, schneidet er die Reben ab mit dem
Messer; /\\
 er entfernt die Triebe, er reißt sie ab. ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Sie alle werden den Raubvögeln der Berge überlassen /\\
 und den wilden Tieren im Land. Den Sommer über sitzen die Raubvögel
darauf /\\
 und im Winter sind dort die wilden Tiere.\\
\\

<<v7>>
7 In jener Zeit werden von dem hoch gewachsenen Volk mit der glänzenden
Haut dem Herrn der Heere Geschenke gebracht, von der Nation, die man
weit und breit fürchtet, von dem Volk, das kraftvoll alles zertritt,
dessen Land von Flüssen durchschnitten wird. Man bringt die Geschenke an
den Ort, wo der Name des Herrn der Heere gegenwärtig ist: zum Berg
Zion.\\
\\

^{[[#fnm1][1]]} ℘ Dtn 28,42

^{[[#fnm2][2]]} der Heuschreckenschwärme, wörtlich: des
Flügelgeschwirrs. - Zu Kusch vgl. die Anmerkung zu 11,11; gemeint sind
die Äthiopier, die Herodot die größten und schönsten aller Menschen
nennt.

^{[[#fnm3][3]]} 5f: Eine Warnung zuerst an Juda.
