:PROPERTIES:
:ID:       31c85d9b-5bd4-4860-8125-520fcb41711c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_51.html][51]] [[file:Jes_52.html][52]] *53*
[[file:Jes_54.html][54]] [[file:Jes_55.html][55]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 53
  :PROPERTIES:
  :CUSTOM_ID: jes-53
  :END:

<<verses>>

<<v1>>
1 Wer hat unserer Kunde geglaubt? /\\
 Der Arm des Herrn - wem wurde er offenbar? ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Vor seinen Augen wuchs er auf wie ein junger Spross, /\\
 wie ein Wurzeltrieb aus trockenem Boden. Er hatte keine schöne und edle
Gestalt, /\\
 sodass wir ihn anschauen mochten. Er sah nicht so aus, /\\
 dass wir Gefallen fanden an ihm. ^{[[#fn2][2]]}\\
\\

<<v3>>
3 Er wurde verachtet und von den Menschen gemieden, /\\
 ein Mann voller Schmerzen, /\\
 mit Krankheit vertraut. Wie einer, vor dem man das Gesicht verhüllt,
/\\
 war er verachtet; wir schätzten ihn nicht.\\
\\

<<v4>>
4 Aber er hat unsere Krankheit getragen /\\
 und unsere Schmerzen auf sich geladen. Wir meinten, er sei von Gott
geschlagen, /\\
 von ihm getroffen und gebeugt. ^{[[#fn3][3]]}\\
\\

<<v5>>
5 Doch er wurde durchbohrt wegen unserer Verbrechen, /\\
 wegen unserer Sünden zermalmt. Zu unserem Heil lag die Strafe auf ihm,
/\\
 durch seine Wunden sind wir geheilt. ^{[[#fn4][4]]}\\
\\

<<v6>>
6 Wir hatten uns alle verirrt wie Schafe, /\\
 jeder ging für sich seinen Weg. Doch der Herr lud auf ihn /\\
 die Schuld von uns allen. ^{[[#fn5][5]]}\\
\\

<<v7>>
7 Er wurde misshandelt und niedergedrückt, /\\
 aber er tat seinen Mund nicht auf. Wie ein Lamm, das man zum Schlachten
führt, /\\
 und wie ein Schaf angesichts seiner Scherer, /\\
 so tat auch er seinen Mund nicht auf. ^{[[#fn6][6]]}\\
\\

<<v8>>
8 Durch Haft und Gericht wurde er dahingerafft, /\\
 doch wen kümmerte sein Geschick? Er wurde vom Land der Lebenden
abgeschnitten /\\
 und wegen der Verbrechen seines Volkes zu Tode getroffen.
^{[[#fn7][7]]}\\
\\

<<v9>>
9 Bei den Ruchlosen gab man ihm sein Grab, /\\
 bei den Verbrechern seine Ruhestätte, obwohl er kein Unrecht getan hat
/\\
 und kein trügerisches Wort in seinem Mund war. ^{[[#fn8][8]]}\\
\\

<<v10>>
10 Doch der Herr fand Gefallen an seinem zerschlagenen (Knecht), /\\
 er rettete den, der sein Leben als Sühnopfer hingab. Er wird Nachkommen
sehen und lange leben. /\\
 Der Plan des Herrn wird durch ihn gelingen.\\
\\

<<v11>>
11 Nachdem er so vieles ertrug, erblickt er das Licht. /\\
 Er sättigt sich an Erkenntnis. Mein Knecht, der gerechte, macht die
vielen gerecht; /\\
 er lädt ihre Schuld auf sich. ^{[[#fn9][9]][[#fn10][10]]}\\
\\

<<v12>>
12 Deshalb gebe ich ihm seinen Anteil unter den Großen /\\
 und mit den Mächtigen teilt er die Beute, weil er sein Leben dem Tod
preisgab /\\
 und sich unter die Verbrecher rechnen ließ. Denn er trug die Sünden von
vielen /\\
 und trat für die Schuldigen ein. ^{[[#fn11][11]]}\\
\\

^{[[#fnm1][1]]} ℘ Joh 12,38; Röm 10,16

^{[[#fnm2][2]]} ℘ 11,1.10

^{[[#fnm3][3]]} ℘ Mt 8,17

^{[[#fnm4][4]]} ℘ 1 Petr 2,24f

^{[[#fnm5][5]]} ℘ 56,11

^{[[#fnm6][6]]} ℘ Apg 8,32f; Offb 5,6.12; 13,8

^{[[#fnm7][7]]} seines Volkes: Text korr. nach dem Qumran-Text; H:
meines Volkes.

^{[[#fnm8][8]]} ℘ 1 Petr 2,22

^{[[#fnm9][9]]} ℘ Dan 12,3; Röm 5,19

^{[[#fnm10][10]]} Licht: eingefügt nach dem Qumran-Text und G.

^{[[#fnm11][11]]} ℘ Röm 4,25; Lk 22,37; Hebr 9,28; Joh 1,29; Röm 5,16; 1
Petr 2,24
