:PROPERTIES:
:ID:       6d9e6acd-bf03-4471-8277-aa9894d601bb
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_33.html][33]] [[file:Jes_34.html][34]] *35*
[[file:Jes_36.html][36]] [[file:Jes_37.html][37]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 35
  :PROPERTIES:
  :CUSTOM_ID: jes-35
  :END:

<<verses>>

<<v1>>
**** Die Verheißung des messianischen Heils: 35,1-10
     :PROPERTIES:
     :CUSTOM_ID: die-verheißung-des-messianischen-heils-351-10
     :END:
1 Die Wüste und das trockene Land sollen sich freuen, /\\
 die Steppe soll jubeln und blühen.\\
\\

<<v2>>
2 Sie soll prächtig blühen wie eine Lilie, /\\
 jubeln soll sie, jubeln und jauchzen. Die Herrlichkeit des Libanon wird
ihr geschenkt, /\\
 die Pracht des Karmel und der Ebene Scharon. Man wird die Herrlichkeit
des Herrn sehen, /\\
 die Pracht unseres Gottes.\\
\\

<<v3>>
3 Macht die erschlafften Hände wieder stark /\\
 und die wankenden Knie wieder fest! ^{[[#fn1][1]]}\\
\\

<<v4>>
4 Sagt den Verzagten: /\\
 Habt Mut, fürchtet euch nicht! Seht, hier ist euer Gott! /\\
 Die Rache Gottes wird kommen und seine Vergeltung; /\\
 er selbst wird kommen und euch erretten.\\
\\

<<v5>>
5 Dann werden die Augen der Blinden geöffnet, /\\
 auch die Ohren der Tauben sind wieder offen.\\
\\

<<v6>>
6 Dann springt der Lahme wie ein Hirsch, /\\
 die Zunge des Stummen jauchzt auf. In der Wüste brechen Quellen hervor
/\\
 und Bäche fließen in der Steppe.\\
\\

<<v7>>
7 Der glühende Sand wird zum Teich /\\
 und das durstige Land zu sprudelnden Quellen. An dem Ort, wo jetzt die
Schakale sich lagern, /\\
 gibt es dann Gras, Schilfrohr und Binsen.\\
\\

<<v8>>
8 Eine Straße wird es dort geben; /\\
 man nennt sie den Heiligen Weg. Kein Unreiner darf ihn betreten. /\\
 Er gehört dem, der auf ihm geht. /\\
 Unerfahrene gehen nicht mehr in die Irre.\\
\\

<<v9>>
9 Es wird keinen Löwen dort geben, /\\
 kein Raubtier betritt diesen Weg, keines von ihnen ist hier zu finden.
/\\
 Dort gehen nur die Erlösten.\\
\\

<<v10>>
10 Die vom Herrn Befreiten kehren zurück /\\
 und kommen voll Jubel nach Zion. Ewige Freude ruht auf ihren Häuptern.
/\\
 Wonne und Freude stellen sich ein, /\\
 Kummer und Seufzen entfliehen. ^{[[#fn2][2]]}\\
\\

^{[[#fnm1][1]]} ℘ Hebr 12,12

^{[[#fnm2][2]]} ℘ 51,11
