:PROPERTIES:
:ID:       db5d6f07-85e3-472e-85b9-2e4a0fbff236
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_64.html][64]] [[file:Jes_65.html][65]] *66*

--------------

* Jes 66
  :PROPERTIES:
  :CUSTOM_ID: jes-66
  :END:

<<verses>>

<<v1>>
**** Die Beschreibung der Endzeit: 66,1-24
     :PROPERTIES:
     :CUSTOM_ID: die-beschreibung-der-endzeit-661-24
     :END:
1 So spricht der Herr: Der Himmel ist mein Thron /\\
 und die Erde der Schemel für meine Füße. Was wäre das für ein Haus, /\\
 das ihr mir bauen könntet? Was wäre das für ein Ort, /\\
 an dem ich ausruhen könnte? ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Denn all das hat meine Hand gemacht; /\\
 es gehört mir ja schon - Spruch des Herrn. Ich blicke auf den Armen und
Zerknirschten /\\
 und auf den, der zittert vor meinem Wort.\\
\\

<<v3>>
3 Man opfert Rinder - und erschlägt Menschen; /\\
 man opfert Schafe - und erwürgt Hunde; man bringt Speiseopfer dar - /\\
 und auch Schweineblut; man spendet Weihrauch - /\\
 und preist einen Götzen. Wie diese Menschen ihre eigenen Wege wählen
/\\
 und an ihren Götterbildern Gefallen haben, ^{[[#fn2][2]]}\\
\\

<<v4>>
4 so wähle ich für sie die Strafe aus /\\
 und bringe über sie Schrecken. Denn sie gaben keine Antwort, als ich
sie rief, /\\
 als ich zu ihnen redete, hörten sie nicht; sondern sie haben getan, was
mir missfällt, /\\
 und haben sich für das entschieden, was ich nicht will.
^{[[#fn3][3]]}\\
\\

<<v5>>
5 Hört das Wort des Herrn, /\\
 die ihr zittert vor seinem Wort! Eure Brüder, die euch hassen, /\\
 die euch um meines Namens willen verstoßen, sie sagen: Der Herr soll
doch seine Herrlichkeit zeigen, /\\
 damit wir eure Freude miterleben. /\\
 Aber sie werden beschämt.\\
\\

<<v6>>
6 Horcht: Getöse dringt aus der Stadt, /\\
 Getöse aus dem Tempel. /\\
 Horcht: Der Herr vergilt seinen Feinden ihr Tun. ^{[[#fn4][4]]}\\
\\

<<v7>>
7 Noch ehe die Frau ihre Wehen bekommt, /\\
 hat sie schon geboren; ehe die Wehen über sie kamen, /\\
 brachte sie einen Knaben zur Welt. ^{[[#fn5][5]][[#fn6][6]]}\\
\\

<<v8>>
8 Wer hat so etwas je gehört, /\\
 wer hat je dergleichen gesehen? Wird ein Land an einem einzigen Tag
geboren, /\\
 kommt ein Volk auf einmal zur Welt? Doch Zion, kaum in den Wehen, /\\
 hat schon ihre Kinder geboren.\\
\\

<<v9>>
9 Hätte ich ihr etwa den Schoß öffnen sollen, /\\
 ohne sie gebären zu lassen?, spricht der Herr. Sollte ich, der die
Frauen gebären lässt, /\\
 ihnen den Schoß verschließen?, spricht dein Gott.\\
\\

<<v10>>
10 Freut euch mit Jerusalem! /\\
 Jubelt in der Stadt, alle, die ihr sie liebt. Seid fröhlich mit ihr,
/\\
 alle, die ihr über sie traurig wart.\\
\\

<<v11>>
11 Saugt euch satt an ihrer tröstenden Brust, /\\
 trinkt und labt euch an ihrem mütterlichen Reichtum! ^{[[#fn7][7]]}\\
\\

<<v12>>
12 Denn so spricht der Herr: /\\
 Seht her: Wie einen Strom /\\
 leite ich den Frieden zu ihr und den Reichtum der Völker /\\
 wie einen rauschenden Bach. Ihre Kinder wird man auf den Armen tragen
/\\
 und auf den Knien schaukeln. ^{[[#fn8][8]][[#fn9][9]]}\\
\\

<<v13>>
13 Wie eine Mutter ihren Sohn tröstet, /\\
 so tröste ich euch; /\\
 in Jerusalem findet ihr Trost.\\
\\

<<v14>>
14 Wenn ihr das seht, wird euer Herz sich freuen /\\
 und ihr werdet aufblühen wie frisches Gras. So offenbart sich die Hand
des Herrn an seinen Knechten, /\\
 aber seine Feinde wird er bedrohen. ^{[[#fn10][10]]}\\
\\

<<v15>>
15 Ja, seht, der Herr kommt wie das Feuer heran, /\\
 wie der Sturm sind seine Wagen, um in glühendem Zorn Vergeltung zu
üben, /\\
 und er droht mit feurigen Flammen.\\
\\

<<v16>>
16 Ja, mit Feuer und Schwert hält der Herr Gericht über alle Sterblichen
/\\
 und viele sind es, die der Herr erschlägt. ^{[[#fn11][11]]}\\
\\

<<v17>>
17 Alle, die sich weihen und reinigen bei den Gärten /\\
 für den einen, der in der Mitte steht, die Schweinefleisch, Würmer und
Mäuse verzehren, /\\
 sie alle nehmen ein Ende - Spruch des Herrn.
^{[[#fn12][12]][[#fn13][13]]}\\
\\

<<v18>>
18 Ich kenne ihre Taten und ihre Gedanken und komme, um die Völker aller
Sprachen zusammenzurufen, und sie werden kommen und meine Herrlichkeit
sehen. ^{[[#fn14][14]]}

<<v19>>
19 Ich stelle bei ihnen ein Zeichen auf und schicke von ihnen einige,
die entronnen sind, zu den übrigen Völkern: nach Tarschisch, Pul und
Lud, Meschech und Rosch, Tubal und Jawan und zu den fernen Inseln, die
noch nichts von mir gehört und meine Herrlichkeit noch nicht gesehen
haben. Sie sollen meine Herrlichkeit unter den Völkern verkünden.
^{[[#fn15][15]]}

<<v20>>
20 Sie werden aus allen Völkern eure Brüder als Opfergabe für den Herrn
herbeiholen auf Rossen und Wagen, in Sänften, auf Maultieren und
Dromedaren, her zu meinem heiligen Berg nach Jerusalem, spricht der
Herr, so wie die Söhne Israels ihr Opfer in reinen Gefäßen zum Haus des
Herrn bringen.

<<v21>>
21 Und auch aus ihnen werde ich Männer als Priester und Leviten
auswählen, spricht der Herr.\\
\\

<<v22>>
22 Wie der neue Himmel und die neue Erde, /\\
 die ich erschaffe, /\\
 vor mir stehen - Spruch des Herrn -, /\\
 so wird euer Stamm und euer Name dastehen. ^{[[#fn16][16]]}\\
\\

<<v23>>
23 An jedem Neumond und an jedem Sabbat /\\
 wird alle Welt kommen, um mir zu huldigen, /\\
 spricht der Herr. ^{[[#fn17][17]]}\\
\\

<<v24>>
24 Dann wird man hinausgehen, /\\
 um die Leichen derer zu sehen, /\\
 die sich gegen mich aufgelehnt haben. Denn der Wurm in ihnen wird nicht
sterben /\\
 und das Feuer in ihnen wird niemals erlöschen; /\\
 ein Ekel sind sie für alle Welt. ^{[[#fn18][18]]}\\
\\

^{[[#fnm1][1]]} ℘ Apg 7,49f

^{[[#fnm2][2]]} Die Opfer für Jahwe stehen neben Opfern (Menschen-,
Hunde- und Schweineopfern) für andere Götter.

^{[[#fnm3][3]]} ℘ 65,12

^{[[#fnm4][4]]} ℘ 59,18

^{[[#fnm5][5]]} ℘ Offb 12,2.5

^{[[#fnm6][6]]} 7-9: Zion wird die Mutter der kommenden Heilsgemeinde
(VV. 10-14).

^{[[#fnm7][7]]} ℘ 60,16; 49,23

^{[[#fnm8][8]]} ℘ 30,28; 60,4

^{[[#fnm9][9]]} Ihre Kinder: Text korr.; vgl. G.

^{[[#fnm10][10]]} 14b: und ihr werdet aufblühen, wörtlich: und eure
Gebeine werden sprossen.

^{[[#fnm11][11]]} ℘ Jer 25,31

^{[[#fnm12][12]]} ℘ 65,3f; Ez 8,10f

^{[[#fnm13][13]]} Vielleicht ein Götterbild in einem Garten; Text und
Sinn unklar. Würmer: Text korr.; H: Gräuel.

^{[[#fnm14][14]]} Ich kenne: ergänzt nach G. - und komme: Text korr.
nach G.

^{[[#fnm15][15]]} Die Völkernamen sind zum Teil im Anschluss an G
wiedergegeben. Es ist an weit entfernte Völker gedacht.

^{[[#fnm16][16]]} ℘ 65,17; Offb 21,1

^{[[#fnm17][17]]} ℘ Sach 14,16

^{[[#fnm18][18]]} ℘ Jdt 16,17; Mk 9,48
