:PROPERTIES:
:ID:       e94d5953-8e9f-49ec-995d-76b7c7da37a9
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_12.html][12]] [[file:Jes_13.html][13]] *14*
[[file:Jes_15.html][15]] [[file:Jes_16.html][16]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 14
  :PROPERTIES:
  :CUSTOM_ID: jes-14
  :END:

<<verses>>

<<v1>>
**** Das Spottlied auf den König von Babel: 14,1-21
     :PROPERTIES:
     :CUSTOM_ID: das-spottlied-auf-den-könig-von-babel-141-21
     :END:
1 Der Herr wird mit Jakob Erbarmen haben und Israel von neuem erwählen.
Er wird ihnen Ruhe gewähren in ihrer Heimat; Fremde gesellen sich ihnen
bei und schließen sich an das Haus Jakob an. ^{[[#fn1][1]]}

<<v2>>
2 Die Völker werden Israel nehmen und in seine Heimat zurückführen und
im Land des Herrn wird das Haus Israel sie zu Leibeigenen machen, zu
Knechten und Mägden. Es wird die gefangen halten, die es gefangen
hielten, und wird die unterdrücken, die es einst unterdrückten.

<<v3>>
3 Und wenn der Herr dir dann Ruhe gewährt nach deinen Leiden, deiner
Unruhe und der harten Knechtschaft, die du erdulden musstest,\\
\\

<<v4>>
4 dann wirst du auf den König von Babel dieses Spottlied singen: Ach,
der Unterdrücker fand sein Ende, /\\
 ein Ende nahm die Not.\\
\\

<<v5>>
5 Der Herr hat die Knüppel der Frevler zerbrochen, /\\
 den Stock der Tyrannen,\\
\\

<<v6>>
6 der in seinem Zorn die Völker erschlug, /\\
 sie schlug ohne Ende, der die Völker in seiner Wut zertrat /\\
 und sie verfolgte ohne jedes Erbarmen.\\
\\

<<v7>>
7 Nun hat die ganze Welt Ruhe und Frieden, /\\
 man bricht in Jubel aus.\\
\\

<<v8>>
8 Selbst die Zypressen und die Zedern des Libanon /\\
 machen sich über dich lustig: Seit du am Boden liegst, kommt keiner
mehr her, /\\
 um uns zu fällen.\\
\\

<<v9>>
9 Das Totenreich drunten gerät in Erregung, /\\
 wenn du hinabkommst. Deinetwegen weckt es die Totengeister auf, /\\
 alle Fürsten der Erde, alle Könige der Völker lässt es aufstehen /\\
 von ihren Thronen.\\
\\

<<v10>>
10 Sie alle rufen dir zu: /\\
 Auch du bist nun kraftlos geworden wie wir, /\\
 jetzt bist du uns gleich.\\
\\

<<v11>>
11 Hinabgeschleudert zur Unterwelt ist deine Pracht /\\
 samt deinen klingenden Harfen. Auf Würmer bist du gebettet, /\\
 Maden sind deine Decke. ^{[[#fn2][2]]}\\
\\

<<v12>>
12 Ach, du bist vom Himmel gefallen, /\\
 du strahlender Sohn der Morgenröte. Zu Boden bist du geschmettert, /\\
 du Bezwinger der Völker. ^{[[#fn3][3]]}\\
\\

<<v13>>
13 Du aber hattest in deinem Herzen gedacht: /\\
 Ich ersteige den Himmel; dort oben stelle ich meinen Thron auf, /\\
 über den Sternen Gottes; auf den Berg der (Götter-)versammlung setze
ich mich, /\\
 im äußersten Norden. ^{[[#fn4][4]]}\\
\\

<<v14>>
14 Ich steige weit über die Wolken hinauf, /\\
 um dem Höchsten zu gleichen.\\
\\

<<v15>>
15 Doch in die Unterwelt wirst du hinabgeworfen, /\\
 in die äußerste Tiefe.\\
\\

<<v16>>
16 Jeder, der dich sieht, starrt dich an, /\\
 er blickt genau auf dich hin und denkt: Ist das der Mann, der die
Königreiche in Schrecken versetzte, /\\
 der die Erde erbeben ließ,\\
\\

<<v17>>
17 der die Welt zur Wüste gemacht hat, /\\
 ihre Städte zerstörte, /\\
 der die Gefangenen nicht nach Hause entließ?\\
\\

<<v18>>
18 Alle Könige der Völker ruhen in Ehren, /\\
 jeder in seinem Grab;\\
\\

<<v19>>
19 du aber wurdest hingeworfen ohne Begräbnis, /\\
 wie ein verachteter Bastard. Mit Erschlagenen bist du bedeckt, /\\
 die vom Schwert durchbohrt sind, /\\
 wie ein zertretener Leichnam. Mit denen, die in steinerne Grüfte
hinabsteigen, / ^{[[#fn5][5]]}\\
\\

<<v20>>
20 bist du nicht vereint im Grab. Du hast dein eigenes Land zugrunde
gerichtet, /\\
 hingemordet dein eigenes Volk; darum soll man die Namen der Nachkommen
dieses Verbrechers /\\
 niemals mehr nennen. ^{[[#fn6][6]]}\\
\\

<<v21>>
21 Richtet eine Schlachtbank her für seine Söhne /\\
 wegen der Sünden des Vaters, damit sie sich niemals wieder erheben und
die Welt erobern /\\
 und den Erdkreis mit Städten erfüllen. ^{[[#fn7][7]]}\\
\\

<<v22>>
**** Die völlige Verwüstung Babels: 14,22-23
     :PROPERTIES:
     :CUSTOM_ID: die-völlige-verwüstung-babels-1422-23
     :END:
22 Ich will mich gegen Babel erheben - Spruch des Herrn der Heere -, mit
Stumpf und Stiel will ich seinen Namen und Samen vernichten Spruch des
Herrn. ^{[[#fn8][8]][[#fn9][9]]}

<<v23>>
23 Ich mache es zum Platz für die Eulen und zu einem sumpfigen Teich,
mit meinem vernichtenden Besen fege ich es hinweg - Spruch des Herrn der
Heere. ^{[[#fn10][10]]}\\
\\

<<v24>>
*** Das Gericht über andere Völker: 14,24 - 21,17
    :PROPERTIES:
    :CUSTOM_ID: das-gericht-über-andere-völker-1424---2117
    :END:
**** Die Ankündigung der Vernichtung des assyrischen Heeres: 14,24-27
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-der-vernichtung-des-assyrischen-heeres-1424-27
     :END:
24 Der Herr der Heere hat geschworen: /\\
 Wie ich es erdacht habe, so wird es geschehen; /\\
 wie ich es plante, so wird es auch kommen.\\
\\

<<v25>>
25 In meinem eigenen Land will ich Assur zerschmettern, /\\
 ich will es auf meinen Bergen zertreten. Dann wird sein Joch von ihnen
genommen /\\
 und seine Last fällt von ihrer Schulter.
^{[[#fn11][11]][[#fn12][12]]}\\
\\

<<v26>>
26 Das ist der Plan, der für die ganze Erde beschlossen ist, /\\
 das ist die Hand, die über alle Völker ausgestreckt ist.\\
\\

<<v27>>
27 Denn der Herr der Heere hat es beschlossen. /\\
 Wer kann es vereiteln? Seine Hand ist ausgestreckt. /\\
 Wer will sie zurückbiegen?\\
\\

<<v28>>
**** Die Ankündigung des Gerichts über die Philister: 14,28-32
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-des-gerichts-über-die-philister-1428-32
     :END:
28 Im Todesjahr des Königs Ahas erging folgender Ausspruch:\\
\\

<<v29>>
29 Freu dich nicht, Land der Philister, /\\
 weil der Stock zerbrochen ist, der dich schlug; denn aus der Schlange
geht wie aus einer Wurzel eine Natter hervor /\\
 und ihre Frucht ist ein fliegender Drache.
^{[[#fn13][13]][[#fn14][14]]}\\
\\

<<v30>>
30 Auf meiner Wiese weiden die Schwachen, /\\
 dort leben die Armen in Sicherheit; deine Wurzeln aber lasse ich
verhungern, /\\
 den Rest von dir werde ich erschlagen.\\
\\

<<v31>>
31 Schreit auf, ihr Tore, jammere, o Stadt, /\\
 verzage, Land der Philister! Denn von Norden kommt Rauch /\\
 und keiner entfernt sich aus den Reihen des Heeres.\\
\\

<<v32>>
32 Was gibt man den Gesandten der Völker zur Antwort? /\\
 Der Herr hat Zion gegründet, /\\
 die Armen seines Volkes finden dort ihre Zuflucht.\\
\\

^{[[#fnm1][1]]} ℘ 61,5

^{[[#fnm2][2]]} ℘ Am 5,23

^{[[#fnm3][3]]} 12-21: Der Text verwendet mythische Bilder. Nach
babylonischer Anschauung wurde Helel, der Sohn der Morgenröte, in die
Unterwelt gestürzt, als er in den Himmel aufsteigen wollte.

^{[[#fnm4][4]]} ℘ Jer 51,53

^{[[#fnm5][5]]} Bastard, wörtlich: Spross.

^{[[#fnm6][6]]} dieses Verbrechers: Text korr., Einzahl nach G und S.

^{[[#fnm7][7]]} Vielleicht Städte, die der Eroberer neu erbaut.

^{[[#fnm8][8]]} ℘ Ijob 18,19

^{[[#fnm9][9]]} In H zwei Wortspiele.

^{[[#fnm10][10]]} ℘ 34,11

^{[[#fnm11][11]]} ℘ 9,3; 10,27

^{[[#fnm12][12]]} von ihnen: Gemeint sind die Israeliten.

^{[[#fnm13][13]]} ℘ 30,6

^{[[#fnm14][14]]} Der «Stock» ist ein feindlicher Herrscher, vielleicht
Tiglat-Pileser III., der 727 v. Chr. starb.
