:PROPERTIES:
:ID:       08c39fdb-d1a3-4cc6-aa77-34e556be1987
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_19.html][19]] [[file:Jes_20.html][20]] *21*
[[file:Jes_22.html][22]] [[file:Jes_23.html][23]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 21
  :PROPERTIES:
  :CUSTOM_ID: jes-21
  :END:

<<verses>>

<<v1>>
**** Erneute Ankündigung des Gerichts über Babel: 21,1-10
     :PROPERTIES:
     :CUSTOM_ID: erneute-ankündigung-des-gerichts-über-babel-211-10
     :END:
1 Ausspruch über die Wüste am Meer: Wie die Stürme im Negeb toben, /\\
 so kommt Unheil aus der Wüste, /\\
 aus dem schaurigen Land. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Eine schreckliche Vision wurde mir gezeigt: /\\
 Der Empörer empört sich, der Vernichter vernichtet. Zieh herauf, Elam!
/\\
 Medien, beginne mit der Belagerung! /\\
 Ich mache allem Seufzen ein Ende. ^{[[#fn2][2]]}\\
\\

<<v3>>
3 Darum zittert mein ganzer Leib, /\\
 Krämpfe befallen mich /\\
 wie die Wehen eine gebärende Frau. Ich bin betäubt von dem, was ich
höre, /\\
 bestürzt von dem, was ich sehe.\\
\\

<<v4>>
4 Mein Herz pocht wild, mich schüttelt ein Schauder. /\\
 Das ersehnte Dunkel des Abends macht der Herr für mich zum Schrecken.\\
\\

<<v5>>
5 Man deckt den Tisch, legt die Polster zurecht /\\
 und isst und trinkt. /\\
 Steht auf, ihr Fürsten, ölt euren Schild ein! ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Denn so hat der Herr zu mir gesagt: /\\
 Geh, stell einen Späher auf! /\\
 Was er sieht, soll er melden.\\
\\

<<v7>>
7 Sieht er Wagen und Pferdegespanne, /\\
 einen Zug von Eseln, einen Zug von Kamelen, /\\
 soll er darauf achten, genau darauf achten.\\
\\

<<v8>>
8 Der Späher rief: /\\
 Herr, den ganzen Tag stehe ich auf meinem Posten, /\\
 die ganze Nacht halte ich Wache. ^{[[#fn4][4]]}\\
\\

<<v9>>
9 Seht, dort kommt ein Zug von Männern, dazu Pferdegespanne. /\\
 Und er begann zu rufen: Gefallen ist Babel, gefallen, /\\
 und all seine Götterbilder hat man zu Boden geschmettert.
^{[[#fn5][5]]}\\
\\

<<v10>>
10 Du mein zerschlagenes, zerdroschenes Volk! /\\
 Was ich hörte vom Herrn der Heere, /\\
 von Israels Gott, das verkünde ich euch.\\
\\

<<v11>>
**** Der Spruch über Edom: 21,11-12
     :PROPERTIES:
     :CUSTOM_ID: der-spruch-über-edom-2111-12
     :END:
11 Ausspruch über Edom. Aus Seïr ruft man mir zu: /\\
 Wächter, wie lange noch dauert die Nacht? /\\
 Wächter, wie lange noch dauert die Nacht? ^{[[#fn6][6]]}\\
\\

<<v12>>
12 Der Wächter antwortet: /\\
 Es kommt der Morgen, es kommt auch die Nacht. /\\
 Wenn ihr fragen wollt, kommt wieder und fragt!\\
\\

<<v13>>
**** Die Ankündigung des Gerichts über Arabien: 21,13-17
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-des-gerichts-über-arabien-2113-17
     :END:
13 Ausspruch über Arabien. Übernachtet im Gebüsch, in der Steppe, /\\
 ihr Karawanen von Dedan! ^{[[#fn7][7]]}\\
\\

<<v14>>
14 Bringt den Durstigen Wasser, /\\
 ihr Bewohner der Gegend von Tema! /\\
 Kommt den Fliehenden entgegen mit Brot!\\
\\

<<v15>>
15 Denn sie sind vor den Schwertern geflohen, /\\
 vor dem gezückten Schwert, vor dem gespannten Bogen, /\\
 vor dem schweren Kampf.\\
\\

<<v16>>
16 Denn so hat der Herr zu mir gesagt: Noch ein Jahr - ein Söldnerjahr
-, dann ist es mit der ganzen Macht Kedars zu Ende. ^{[[#fn8][8]]}

<<v17>>
17 Von den Bogenschützen in Kedar bleiben nur wenige übrig. Der Herr,
der Gott Israels, hat gesprochen.\\
\\

^{[[#fnm1][1]]} Nach V. 9 ist Babel gemeint. - Wüste am Meer; Bedeutung
unklar.

^{[[#fnm2][2]]} ℘ 33,1

^{[[#fnm3][3]]} ℘ Dan 5

^{[[#fnm4][4]]} Der Späher: Qumran-Text: Der Seher; H: Der Löwe.

^{[[#fnm5][5]]} ℘ Jer 51,8; Offb 14,8; 18,2

^{[[#fnm6][6]]} Edom: Text korr. mit G; H: Duma. Der Spruch ist ein sog.
Wächterlied.

^{[[#fnm7][7]]} 13f: Dedan und Tema sind Orte an der Karawanenstraße in
Südarabien, östlich vom Roten Meer; Kedar: nördlich von Tema.

^{[[#fnm8][8]]} Vgl. die Anmerkung zu 16,13f.
