:PROPERTIES:
:ID:       933a8de8-bed8-4376-bb3a-c11986c2c6f1
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_34.html][34]] [[file:Jes_35.html][35]] *36*
[[file:Jes_37.html][37]] [[file:Jes_38.html][38]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 36
  :PROPERTIES:
  :CUSTOM_ID: jes-36
  :END:

<<verses>>

<<v1>>
** Geschichtlicher Anhang: 36,1 - 39,8
   :PROPERTIES:
   :CUSTOM_ID: geschichtlicher-anhang-361---398
   :END:
*** Sanheribs Feldzug gegen Jerusalem: 36,1 - 37,38
    :PROPERTIES:
    :CUSTOM_ID: sanheribs-feldzug-gegen-jerusalem-361---3738
    :END:
**** Die erste Gesandtschaft Sanheribs: 36,1-22
     :PROPERTIES:
     :CUSTOM_ID: die-erste-gesandtschaft-sanheribs-361-22
     :END:
1 Im vierzehnten Jahr des Königs Hiskija zog Sanherib, der König von
Assur, gegen alle befestigten Städte Judas und nahm sie ein.
^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Der König von Assur sandte den Rabschake mit einer großen Streitmacht
von Lachisch aus nach Jerusalem gegen König Hiskija. Er stellte sich an
der Wasserleitung des oberen Teiches auf, der an der Walkerfeldstraße
liegt. ^{[[#fn3][3]]}

<<v3>>
3 Der Palastvorsteher Eljakim, der Sohn Hilkijas, der Staatsschreiber
Schebna und der Sprecher des Königs Joach, der Sohn Asafs, gingen zu ihm
hinaus.

<<v4>>
4 Da sagte der Rabschake zu ihnen: Sagt zu Hiskija: So spricht der
Großkönig, der König von Assur: Worauf vertraust du denn, dass du dich
so sicher fühlst?

<<v5>>
5 Du glaubst wohl, bloßes Gerede sei im Krieg schon Rat und Stärke? Auf
wen vertraust du also, dass du von mir abgefallen bist?

<<v6>>
6 Du vertraust gewiss auf Ägypten, dieses geknickte Schilfrohr, das
jeden, der sich darauf stützt, in die Hand sticht und sie durchbohrt.
Denn so macht es der Pharao, der König von Ägypten, mit allen, die ihm
vertrauen. ^{[[#fn4][4]]}

<<v7>>
7 Wenn ihr aber zu mir sagt: Wir vertrauen auf Jahwe, unseren Gott, dann
bedenkt: Ist nicht gerade er der Gott, dessen Kulthöhen und Altäre
Hiskija beseitigt hat? Hat nicht Hiskija in Juda und Jerusalem
angeordnet: Nur vor diesem Altar in Jerusalem dürft ihr euch
niederwerfen?

<<v8>>
8 Geh doch mit meinem Herrn, dem König von Assur, eine Wette ein! Ich
gebe dir zweitausend Pferde. Kannst du die Reiter für sie stellen?

<<v9>>
9 Wie willst du auch nur einen einzigen Statthalter meines Herrn in die
Flucht schlagen, und wäre es der unbedeutendste seiner Knechte? Du
vertraust ja nur auf Ägypten, auf seine Wagen und deren Besatzung.

<<v10>>
10 Außerdem: Bin ich denn gegen den Willen Jahwes heraufgezogen, um
dieses Land zu verwüsten? Jahwe selbst hat mir befohlen: Zieh gegen
dieses Land und verwüste es!

<<v11>>
11 Da sagten Eljakim, Schebna und Joach zu dem Rabschake: Sprich doch
aramäisch mit deinen Knechten! Wir verstehen es. Sprich vor den Ohren
des Volkes, das auf der Mauer steht, nicht judäisch mit uns!

<<v12>>
12 Der Rabschake antwortete ihnen: Hat mich mein Herr etwa beauftragt,
das alles nur zu deinem Herrn und zu dir zu sagen und nicht vielmehr zu
all den Männern, die auf der Mauer sitzen und ihren eigenen Kot essen
und ihren Harn trinken wie ihr?

<<v13>>
13 Dann trat der Rabschake vor und rief laut auf Judäisch: Hört die
Worte des Großkönigs, des Königs von Assur!

<<v14>>
14 So spricht der König: Lasst euch nicht von Hiskija betören; denn er
kann euch nicht retten.

<<v15>>
15 Er soll euch nicht verleiten, auf Jahwe zu vertrauen, und sagen:
Jahwe wird uns sicher retten, diese Stadt wird dem König von Assur nicht
in die Hände fallen.

<<v16>>
16 Hört nicht auf Hiskija! Denn so spricht der König von Assur: Trefft
mit mir ein Abkommen und ergebt euch! Dann kann jeder von euch von
seinem Weinstock und von seinem Feigenbaum essen und Wasser aus seiner
Zisterne trinken,

<<v17>>
17 bis ich komme und euch in ein Land bringe, das eurem Land gleicht: in
ein Land voll Getreide und Most, ein Land voll Brot und Wein.

<<v18>>
18 Lasst euch von Hiskija nicht in die Irre führen, wenn er sagt: Jahwe
wird uns retten. Hat denn einer von den Göttern der anderen Völker sein
Land vor dem König von Assur gerettet?

<<v19>>
19 Wo sind die Götter von Hamat und Arpad? Wo sind die Götter von
Sefarwajim? Haben sie etwa Samaria vor mir gerettet?

<<v20>>
20 Wer von all den Göttern der anderen Länder hat sein Land vor mir
gerettet? Wie sollte denn Jahwe Jerusalem vor mir retten?

<<v21>>
21 Die Männer aber schwiegen und gaben ihm keine Antwort; denn der König
hatte befohlen: Ihr dürft ihm nicht antworten.

<<v22>>
22 Der Palastvorsteher Eljakim, der Sohn Hilkijas, der Staatsschreiber
Schebna und der Sprecher des Königs Joach, der Sohn Asafs, zerrissen
ihre Kleider, gingen zu Hiskija und berichteten ihm, was der Rabschake
gesagt hatte.\\
\\

^{[[#fnm1][1]]} ℘ (1-22) 2 Kön 18,13-37; 2 Chr 32,1-19

^{[[#fnm2][2]]} 1-39,8: Stimmt weithin mit 2 Kön überein; nur das Lied
des Hiskija ist Eigengut von Jes. - Vgl. die Anmerkungen zu 2 Kön
18,13 - 20,19.

^{[[#fnm3][3]]} Rabschake ist ein assyrischer Beamtentitel, der etwa
«Obermundschenk» bedeutet.

^{[[#fnm4][4]]} ℘ Ez 29,6f
