:PROPERTIES:
:ID:       e45b8573-cced-441d-996f-bd89155f4c4e
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_32.html][32]] [[file:Jes_33.html][33]] *34*
[[file:Jes_35.html][35]] [[file:Jes_36.html][36]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 34
  :PROPERTIES:
  :CUSTOM_ID: jes-34
  :END:

<<verses>>

<<v1>>
**** Die Ankündigung des Gerichts über Edom: 34,1-17
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-des-gerichts-über-edom-341-17
     :END:
1 Kommt her, ihr Völker, und hört, /\\
 horcht auf, ihr Nationen! Die Erde und alles, was sie erfüllt, /\\
 die Welt und alles, was auf ihr sprosst, sollen es hören,\\
\\

<<v2>>
2 dass der Herr über alle Völker erzürnt ist, /\\
 dass er zornig ist auf all ihre Heere. Er hat sie dem Untergang geweiht
/\\
 und zum Schlachtopfer bestimmt.\\
\\

<<v3>>
3 Die Erschlagenen wirft man hinaus, /\\
 der Gestank ihrer Leichen steigt auf, die Berge triefen von ihrem Blut,
/ ^{[[#fn1][1]]}\\
\\

<<v4>>
4 alle Hügel zerfließen. Wie eine Buchrolle rollt sich der Himmel
zusammen, /\\
 sein ganzes Heer welkt dahin, wie Laub am Weinstock verwelkt, /\\
 wie Früchte am Feigenbaum schrumpfen. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Am Himmel erscheint das Schwert des Herrn. /\\
 Seht her, es fährt auf Edom herab, /\\
 auf das Volk, das der Herr im Gericht dem Untergang weiht.
^{[[#fn3][3]]}\\
\\

<<v6>>
6 Das Schwert des Herrn ist voll Blut, /\\
 es trieft von Fett, vom Blut der Lämmer und Böcke, /\\
 vom Nierenfett der Widder; denn der Herr hält in Bozra ein Opferfest
ab, /\\
 ein großes Schlachtfest in Edom. ^{[[#fn4][4]]}\\
\\

<<v7>>
7 Da fallen die Büffel und Kälber, /\\
 die Stiere und Ochsen. Ihr Land wird betrunken vom Blut, /\\
 ihr Erdreich ist getränkt von Fett.\\
\\

<<v8>>
8 Denn der Herr hat einen Tag der Rache bestimmt, /\\
 ein Jahr der Vergeltung für den Streit um Zion.\\
\\

<<v9>>
9 In Edoms Bächen wird das Wasser zu Pech, /\\
 sein Boden verwandelt sich in Schwefel, /\\
 sein Land wird zu brennendem Pech.\\
\\

<<v10>>
10 Es erlischt nicht bei Tag und bei Nacht, /\\
 der Rauch steigt unaufhörlich empor. Das Land ist für Generationen
verödet, /\\
 nie mehr zieht jemand hindurch. ^{[[#fn5][5]]}\\
\\

<<v11>>
11 Dohlen und Eulen nehmen es in Besitz, /\\
 Käuze und Raben hausen darin. Der Herr spannt die Messschnur «Öde»
darüber, /\\
 er legt das Senkblei «Leere» an. ^{[[#fn6][6]]}\\
\\

<<v12>>
12 Die Bocksgeister werden dort ihr Unwesen treiben. /\\
 Die Edlen Edoms leben nicht mehr. Man ruft dort keinen König mehr aus,
/\\
 mit all seinen Fürsten hat es ein Ende. ^{[[#fn7][7]]}\\
\\

<<v13>>
13 An seinen Palästen ranken sich Dornen empor, /\\
 in den Burgen wachsen Nesseln und Disteln. Das Land wird zu einem Ort
für Schakale, /\\
 zu einem Platz für die Strauße. ^{[[#fn8][8]][[#fn9][9]]}\\
\\

<<v14>>
14 Wüstenhunde und Hyänen treffen sich hier, /\\
 die Bocksgeister begegnen einander. Auch Lilit (das Nachtgespenst) ruht
sich dort aus /\\
 und findet für sich eine Bleibe. ^{[[#fn10][10]]}\\
\\

<<v15>>
15 Der Kauz hat hier sein sicheres Nest, /\\
 er legt seine Eier und brütet sie aus. Auch die Geier sammeln sich
hier, /\\
 einer neben dem andern. ^{[[#fn11][11]]}\\
\\

<<v16>>
16 Forscht nach im Buch des Herrn, /\\
 dort werdet ihr lesen: Keines dieser Tiere ist ausgeblieben, /\\
 keines braucht seinen Gefährten zu suchen; denn der Mund des Herrn hat
es befohlen, /\\
 sein Geist hat sie zusammengeführt. ^{[[#fn12][12]]}\\
\\

<<v17>>
17 Er selbst hat für sie das Los geworfen, /\\
 er hat mit eigener Hand das Land vermessen und ihnen zugeteilt: Für
immer sollen sie es besitzen, /\\
 von Generation zu Generation darin wohnen.\\
\\

^{[[#fnm1][1]]} ℘ Joël 2,20

^{[[#fnm2][2]]} 4a: Hügel: Text korr.; H: das Heer des Himmels (aus V.
5).

^{[[#fnm3][3]]} erscheint: Text korr. nach dem Qumran-Text. - das
Schwert des Herrn, wörtlich: mein Schwert.

^{[[#fnm4][4]]} 6e: Bozra: südöstlich des Toten Meeres.

^{[[#fnm5][5]]} ℘ (10-15) 13,20-22

^{[[#fnm6][6]]} ℘ 14,23; Zef 2,14

^{[[#fnm7][7]]} 12ab: Ergänzt nach G; in H ist nur erhalten: seine
Edlen.

^{[[#fnm8][8]]} ℘ Hos 9,6; Jes 35,7

^{[[#fnm9][9]]} 13d: Strauße, wörtlich: Töchter der Wüste.

^{[[#fnm10][10]]} ℘ 13,21

^{[[#fnm11][11]]} 15b: seine Eier: Text korr.

^{[[#fnm12][12]]} 16f: Später wird man im Jesaja-Buch nachlesen und
feststellen, dass das Gericht über Edom eingetroffen ist. - der Mund des
Herrn: Text korr. nach H-Handschriften und G.
