:PROPERTIES:
:ID:       58724b22-44e3-4188-99fc-199c9efe08ac
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] *2*
[[file:Jes_3.html][3]] [[file:Jes_4.html][4]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 2
  :PROPERTIES:
  :CUSTOM_ID: jes-2
  :END:

<<verses>>

<<v1>>
**** Jerusalem als Mittelpunkt des messianischen Reiches: 2,1-5
     :PROPERTIES:
     :CUSTOM_ID: jerusalem-als-mittelpunkt-des-messianischen-reiches-21-5
     :END:
1 Das Wort, das Jesaja, der Sohn des Amoz, in einer Vision über Juda und
Jerusalem gehört hat.\\
\\

<<v2>>
2 Am Ende der Tage wird es geschehen: Der Berg mit dem Haus des Herrn
/\\
 steht fest gegründet als höchster der Berge; er überragt alle Hügel.
/\\
 Zu ihm strömen alle Völker. ^{[[#fn1][1]]}\\
\\

<<v3>>
3 Viele Nationen machen sich auf den Weg. /\\
 Sie sagen: Kommt, wir ziehen hinauf zum Berg des Herrn /\\
 und zum Haus des Gottes Jakobs. Er zeige uns seine Wege, /\\
 auf seinen Pfaden wollen wir gehen. Denn von Zion kommt die Weisung des
Herrn, /\\
 aus Jerusalem sein Wort. ^{[[#fn2][2]]}\\
\\

<<v4>>
4 Er spricht Recht im Streit der Völker, /\\
 er weist viele Nationen zurecht. Dann schmieden sie Pflugscharen aus
ihren Schwertern /\\
 und Winzermesser aus ihren Lanzen. Man zieht nicht mehr das Schwert,
Volk gegen Volk, /\\
 und übt nicht mehr für den Krieg. ^{[[#fn3][3]]}\\
\\

<<v5>>
5 Ihr vom Haus Jakob, kommt, /\\
 wir wollen unsere Wege gehen im Licht des Herrn.\\
\\

<<v6>>
**** Der Tag Jahwes: 2,6-22
     :PROPERTIES:
     :CUSTOM_ID: der-tag-jahwes-26-22
     :END:
6 Ja, du hast dein Volk, das Haus Jakob, verstoßen; /\\
 denn es ist voll von Zauberern und Wahrsagern wie das Volk der
Philister /\\
 und überflutet von Fremden. ^{[[#fn4][4]]}\\
\\

<<v7>>
7 Sein Land ist voll Silber und Gold, /\\
 zahllos sind seine Schätze. Sein Land ist voll von Pferden, /\\
 zahllos sind seine Wagen. ^{[[#fn5][5]]}\\
\\

<<v8>>
8 Sein Land ist voll von Götzen. /\\
 Alle beten das Werk ihrer Hände an, /\\
 das ihre Finger gemacht haben.\\
\\

<<v9>>
9 Doch die Menschen müssen sich ducken, /\\
 jeder Mann muss sich beugen. /\\
 Verzeih ihnen nicht! ^{[[#fn6][6]][[#fn7][7]]}\\
\\

<<v10>>
10 Verkriech dich im Felsen, /\\
 verbirg dich im Staub vor dem Schrecken des Herrn /\\
 und seiner strahlenden Pracht! ^{[[#fn8][8]]}\\
\\

<<v11>>
11 Da senken sich die stolzen Augen der Menschen, /\\
 die hochmütigen Männer müssen sich ducken, /\\
 der Herr allein ist erhaben an jenem Tag. ^{[[#fn9][9]]}\\
\\

<<v12>>
12 Denn der Tag des Herrn der Heere kommt /\\
 über alles Stolze und Erhabene, /\\
 über alles Hohe - es wird erniedrigt -,\\
\\

<<v13>>
13 über alle hoch ragenden Zedern des Libanon /\\
 und alle Eichen des Baschan, ^{[[#fn10][10]]}\\
\\

<<v14>>
14 über alle hohen Berge und alle stattlichen Hügel, ^{[[#fn11][11]]}

<<v15>>
15 über jeden hohen Turm und jede steile Mauer,\\
\\

<<v16>>
16 über alle Tarschisch-Schiffe /\\
 und die kostbaren Segler. ^{[[#fn12][12]][[#fn13][13]]}\\
\\

<<v17>>
17 Die stolzen Menschen müssen sich ducken, /\\
 die hochmütigen Männer sich beugen, /\\
 der Herr allein ist erhaben an jenem Tag. ^{[[#fn14][14]]}\\
\\

<<v18>>
18 Die Götzen aber schwinden alle dahin. ^{[[#fn15][15]]}\\
\\

<<v19>>
19 Verkriecht euch in Felshöhlen und Erdlöchern /\\
 vor dem Schrecken des Herrn und vor seiner strahlenden Pracht, /\\
 wenn er sich erhebt, um die Erde zu erschrecken. ^{[[#fn16][16]]}\\
\\

<<v20>>
20 An jenem Tag nimmt jeder seine silbernen und goldenen Götzen, /\\
 die er gemacht hat, um sie anzubeten, /\\
 und wirft sie den Fledermäusen und Ratten hin; ^{[[#fn17][17]]}\\
\\

<<v21>>
21 und man wird sich in den Spalten und Höhlen der Felsen verkriechen
/\\
 vor dem Schrecken des Herrn und vor seiner strahlenden Pracht, /\\
 wenn er sich erhebt, um die Erde zu erschrecken. ^{[[#fn18][18]]}\\
\\

<<v22>>
22 [Lasst doch ab vom Menschen; /\\
 in seiner Nase ist nur ein Lufthauch. /\\
 Was bedeutet er schon?]\\
\\

^{[[#fnm1][1]]} ℘ Mi 4,1-3

^{[[#fnm2][2]]} ℘ 51,4

^{[[#fnm3][3]]} ℘ Joël 4,10

^{[[#fnm4][4]]} Übersetzung unsicher. - von Zauberern: Text korr.; H:
vom Osten.

^{[[#fnm5][5]]} ℘ 31,1

^{[[#fnm6][6]]} ℘ 2,11.17; 5,15

^{[[#fnm7][7]]} 9c: Sinn nicht klar.

^{[[#fnm8][8]]} ℘ 2,19.21

^{[[#fnm9][9]]} ℘ 2,9.17; 5,15

^{[[#fnm10][10]]} ℘ Sach 11,2

^{[[#fnm11][11]]} ℘ 30,25

^{[[#fnm12][12]]} ℘ Ps 48,8

^{[[#fnm13][13]]} Tarschisch-Schiffe: seetüchtige Schiffe, die bis
Tarschisch (Tartessus) in Spanien fahren konnten.

^{[[#fnm14][14]]} ℘ 2,9.11; 5,15

^{[[#fnm15][15]]} schwinden dahin: nach dem Qumran-Text.

^{[[#fnm16][16]]} ℘ 2,10

^{[[#fnm17][17]]} den Ratten: nach dem Qumran-Text.

^{[[#fnm18][18]]} ℘ 2,10
