:PROPERTIES:
:ID:       67e053b6-1570-4448-9034-1094c8d91b97
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_42.html][42]] [[file:Jes_43.html][43]] *44*
[[file:Jes_45.html][45]] [[file:Jes_46.html][46]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 44
  :PROPERTIES:
  :CUSTOM_ID: jes-44
  :END:

<<verses>>

<<v1>>
**** Die Ausgießung des Geistes: 44,1-5
     :PROPERTIES:
     :CUSTOM_ID: die-ausgießung-des-geistes-441-5
     :END:
1 Jetzt aber höre, Jakob, mein Knecht, /\\
 Israel, den ich erwählte.\\
\\

<<v2>>
2 So spricht der Herr, dein Schöpfer, /\\
 der dich im Mutterleib geformt hat, der dir hilft: Fürchte dich nicht,
Jakob, mein Knecht, /\\
 du, Jeschurun, den ich erwählte. ^{[[#fn1][1]]}\\
\\

<<v3>>
3 Denn ich gieße Wasser auf den dürstenden Boden, /\\
 rieselnde Bäche auf das trockene Land. Ich gieße meinen Geist über
deine Nachkommen aus /\\
 und meinen Segen über deine Kinder.\\
\\

<<v4>>
4 Dann sprossen sie auf wie das Schilfgras, /\\
 wie Weidenbäume an Wassergräben. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Der eine sagt: Ich gehöre dem Herrn. /\\
 Ein anderer benennt sich mit dem Namen Jakobs. Einer schreibt auf seine
Hand: für den Herrn. /\\
 Ein anderer wird ehrenvoll mit dem Namen Israel benannt.\\
\\

<<v6>>
**** Gottes Ewigkeit und Einzigkeit: 44,6-8
     :PROPERTIES:
     :CUSTOM_ID: gottes-ewigkeit-und-einzigkeit-446-8
     :END:
6 So spricht der Herr, Israels König, /\\
 sein Erlöser, der Herr der Heere: Ich bin der Erste, ich bin der
Letzte, /\\
 außer mir gibt es keinen Gott. ^{[[#fn3][3]]}\\
\\

<<v7>>
7 Wer ist mir gleich? Er soll sich melden, /\\
 er tue es mir kund und beweise es mir. Wer hat von Anfang an die
Zukunft verkündet? /\\
 Sie sollen uns sagen, was alles noch kommt. ^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v8>>
8 Erschreckt nicht und fürchtet euch nicht! /\\
 Habe ich es euch nicht schon längst zu Gehör gebracht und verkündet?
Ihr seid meine Zeugen: Gibt es einen Gott außer mir? /\\
 Es gibt keinen Fels außer mir, ich kenne keinen.\\
\\

<<v9>>
**** Die Hilflosigkeit der Götzen: 44,9-20
     :PROPERTIES:
     :CUSTOM_ID: die-hilflosigkeit-der-götzen-449-20
     :END:
9 Ein Nichts sind alle, die ein Götterbild formen; /\\
 ihre geliebten Götzen nützen nichts. Wer sich zu seinen Göttern
bekennt, sieht nichts, /\\
 ihm fehlt es an Einsicht; darum wird er beschämt.\\
\\

<<v10>>
10 Wer sich einen Gott macht /\\
 und sich ein Götterbild gießt, /\\
 hat keinen Nutzen davon.\\
\\

<<v11>>
11 Seht her, alle, die sich ihm anschließen, werden beschämt, /\\
 die Schmiede sind nichts als Menschen. Sie sollen sich alle versammeln
und vor mich treten; /\\
 dann werden sie alle von Schrecken gepackt und beschämt.\\
\\

<<v12>>
12 Der Schmied facht die Kohlenglut an, /\\
 er formt (das Götterbild) mit seinem Hammer /\\
 und bearbeitet es mit kräftigem Arm. Dabei wird er hungrig und hat
keine Kraft mehr. /\\
 Trinkt er kein Wasser, so wird er ermatten. ^{[[#fn6][6]][[#fn7][7]]}\\
\\

<<v13>>
13 Der Schnitzer misst das Holz mit der Messschnur, /\\
 er entwirft das Bild mit dem Stift /\\
 und schnitzt es mit seinem Messer; er umreißt es mit seinem Zirkel /\\
 und formt die Gestalt eines Mannes, das prächtige Bild eines Menschen;
/\\
 in einem Haus soll es wohnen.\\
\\

<<v14>>
14 Man fällt eine Zeder, wählt eine Eiche /\\
 oder sonst einen mächtigen Baum, den man stärker werden ließ /\\
 als die übrigen Bäume im Wald. Oder man pflanzt einen Lorbeerbaum, /\\
 den der Regen groß werden lässt.\\
\\

<<v15>>
15 Das Holz nehmen die Menschen zum Heizen; /\\
 man macht ein Feuer und wärmt sich daran. Auch schürt man das Feuer und
bäckt damit Brot. /\\
 Oder man schnitzt daraus einen Gott /\\
 und wirft sich nieder vor ihm; man macht ein Götterbild /\\
 und fällt vor ihm auf die Knie.\\
\\

<<v16>>
16 Den einen Teil des Holzes wirft man ins Feuer /\\
 und röstet Fleisch in der Glut /\\
 und sättigt sich an dem Braten. Oder man wärmt sich am Feuer und sagt:
/\\
 Oh, wie ist mir warm! Ich spüre die Glut. ^{[[#fn8][8]]}\\
\\

<<v17>>
17 Aus dem Rest des Holzes aber macht man sich einen Gott, /\\
 ein Götterbild, vor das man sich hinkniet, zu dem man betet und sagt:
/\\
 Rette mich, du bist doch mein Gott!\\
\\

<<v18>>
18 Unwissend sind sie und ohne Verstand; /\\
 denn ihre Augen sind verklebt, sie sehen nichts mehr /\\
 und ihr Herz wird nicht klug.\\
\\

<<v19>>
19 Sie überlegen nichts, /\\
 sie haben keine Erkenntnis und Einsicht, /\\
 sodass sie sich sagen würden: Den einen Teil habe ich ins Feuer
geworfen, /\\
 habe Brot in der Glut gebacken /\\
 und Fleisch gebraten und es gegessen. Aus dem Rest des Holzes aber habe
ich mir /\\
 einen abscheulichen Götzen gemacht /\\
 und nun knie ich nieder vor einem Holzklotz.\\
\\

<<v20>>
20 Wer Asche hütet, /\\
 den hat sein Herz verführt und betrogen. Er wird sein Leben nicht
retten /\\
 und wird nicht sagen: /\\
 Ich halte ja nur ein Trugbild in meiner rechten Hand. ^{[[#fn9][9]]}\\
\\

<<v21>>
**** Die Erlösung Israels: 44,21-23
     :PROPERTIES:
     :CUSTOM_ID: die-erlösung-israels-4421-23
     :END:
21 Denk daran, Jakob, und du, Israel, /\\
 dass du mein Knecht bist. Ich habe dich geschaffen, du bist mein
Knecht; /\\
 Israel, ich vergesse dich nicht.\\
\\

<<v22>>
22 Ich fege deine Vergehen hinweg wie eine Wolke /\\
 und deine Sünden wie Nebel. /\\
 Kehr um zu mir; denn ich erlöse dich. ^{[[#fn10][10]]}\\
\\

<<v23>>
23 Jauchzt, ihr Himmel, denn der Herr hat gehandelt; /\\
 jubelt, ihr Tiefen der Erde! Brecht in Jubel aus, ihr Berge, /\\
 ihr Wälder mit all euren Bäumen! Denn der Herr hat Jakob erlöst /\\
 und an Israel bewiesen, wie herrlich er ist. ^{[[#fn11][11]]}\\
\\

<<v24>>
** Die Ankündigung der Befreiung durch Kyrus: 44,24 - 48,22
   :PROPERTIES:
   :CUSTOM_ID: die-ankündigung-der-befreiung-durch-kyrus-4424---4822
   :END:
**** Die Berufung und die Aufgabe des Kyrus: 44,24 - 45,8
     :PROPERTIES:
     :CUSTOM_ID: die-berufung-und-die-aufgabe-des-kyrus-4424---458
     :END:
24 So spricht der Herr, dein Erlöser, /\\
 der dich im Mutterleib geformt hat: Ich bin der Herr, der alles
bewirkt, /\\
 der ganz allein den Himmel ausgespannt hat, /\\
 der die Erde gegründet hat aus eigener Kraft, ^{[[#fn12][12]]}\\
\\

<<v25>>
25 der das Wirken der Zauberer vereitelt /\\
 und die Wahrsager zu Narren macht, der die Weisen zum Rückzug zwingt
/\\
 und ihre Klugheit als Dummheit entlarvt,\\
\\

<<v26>>
26 der das Wort seiner Knechte erfüllt /\\
 und den Plan ausführt, den seine Boten verkünden, der zu Jerusalem
sagt: Du wirst wieder bewohnt!, /\\
 und zu den Städten Judas: Ihr werdet wieder aufgebaut werden, /\\
 ich baue eure Ruinen wieder auf!, ^{[[#fn13][13]][[#fn14][14]]}\\
\\

<<v27>>
27 der zum tiefen Meer sagt: Trockne aus, /\\
 ich lasse deine Fluten versiegen!,\\
\\

<<v28>>
28 der zu Kyrus sagt: Mein Hirt - /\\
 alles, was ich will, wird er vollenden!, der zu Jerusalem sagt: Du
wirst wieder aufgebaut werden!, /\\
 und zum Tempel: Du wirst wieder dastehen.
^{[[#fn15][15]][[#fn16][16]]}\\
\\

^{[[#fnm1][1]]} 2d: Jeschurun («der Redliche», vielleicht im Gegensatz
zu «Jakob», was als «Betrüger» gedeutet wird; vgl. Hos 12,3f) ist
Ehrenname für Israel (vgl. Dtn 32,15; 33,5.26).

^{[[#fnm2][2]]} das Schilfgras, wörtlich: das Gras zwischen Wassern;
Text korr., ergänzt nach G.

^{[[#fnm3][3]]} ℘ 41,4

^{[[#fnm4][4]]} ℘ 41,23

^{[[#fnm5][5]]} 7c: Text korr.

^{[[#fnm6][6]]} ℘ (12-17) Jer 10,3f

^{[[#fnm7][7]]} Text unklar.

^{[[#fnm8][8]]} 16b: in der Glut: Text korr. nach G (vgl. V. 19).

^{[[#fnm9][9]]} 20ab: Nimmt wohl ein Sprichwort auf.

^{[[#fnm10][10]]} ℘ 43,25

^{[[#fnm11][11]]} ℘ 49,13; 55,12; Ps 96,11-13; Jes 49,3

^{[[#fnm12][12]]} ℘ 44,2; Ijob 9,8

^{[[#fnm13][13]]} ℘ Am 3,7

^{[[#fnm14][14]]} 26a: H: seines Knechtes; gemeint sind die Propheten
als Boten Gottes.

^{[[#fnm15][15]]} ℘ 2 Chr 36,23; Esra 1,1-4

^{[[#fnm16][16]]} der zu Jerusalem sagt . . . und zum Tempel: Text
korr.; vgl. Vg und G.
