:PROPERTIES:
:ID:       fefdad5f-6fac-46e0-8bdb-dfba3796665c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_63.html][63]] [[file:Jes_64.html][64]] *65*
[[file:Jes_66.html][66]]

--------------

* Jes 65
  :PROPERTIES:
  :CUSTOM_ID: jes-65
  :END:

<<verses>>

<<v1>>
**** Gegen die Götzendiener: 65,1-16d
     :PROPERTIES:
     :CUSTOM_ID: gegen-die-götzendiener-651-16d
     :END:
1 Ich wäre zu erreichen gewesen für die, /\\
 die nicht nach mir fragten, ich wäre zu finden gewesen für die, /\\
 die nicht nach mir suchten. Ich sagte zu einem Volk, /\\
 das meinen Namen nicht anrief: /\\
 Hier bin ich, hier bin ich. ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v2>>
2 Den ganzen Tag streckte ich meine Hände aus /\\
 nach einem abtrünnigen Volk, das einen Weg ging, der nicht gut war, /\\
 nach seinen eigenen Plänen,\\
\\

<<v3>>
3 nach einem Volk, /\\
 das in seinem Trotz mich ständig ärgert. Sie bringen Schlachtopfer dar
in Gärten /\\
 und Rauchopfer auf Ziegeln; ^{[[#fn3][3]]}\\
\\

<<v4>>
4 sie sitzen in Grabkammern /\\
 und verbringen die Nächte in Höhlen; sie essen das Fleisch von
Schweinen /\\
 und haben Brühe von verdorbenem Fleisch in ihren Töpfen;\\
\\

<<v5>>
5 sie sagen: Bleib, wo du bist, komm mir nicht nahe, /\\
 sonst bist du geweiht. Diese Menschen sind wie Rauch in meiner Nase,
/\\
 wie ein immer brennendes Feuer. ^{[[#fn4][4]]}\\
\\

<<v6>>
6 Seht her, alles ist aufgeschrieben bei mir /\\
 und ich werde nicht schweigen, /\\
 sondern zahle ihnen heim, wie sie es verdienen; ^{[[#fn5][5]]}\\
\\

<<v7>>
7 ich zahle ihnen den Lohn aus für ihre Schuld /\\
 und die Schuld ihrer Väter, spricht der Herr. Weil sie auf den Bergen
Weihrauch verbrannten /\\
 und mich auf den Hügeln verhöhnten, messe ich ihnen ihren Lohn zu /\\
 und zahle ihnen heim, wie sie es verdienen. ^{[[#fn6][6]]}\\
\\

<<v8>>
8 So spricht der Herr: /\\
 Sobald sich Saft in der Traube findet, /\\
 sagt man: Verdirb sie nicht, denn es ist Segen darin. Ebenso will ich
um meiner Knechte willen handeln, /\\
 um nicht alle vernichten zu müssen.\\
\\

<<v9>>
9 Ich lasse aus Jakob Nachkommen hervorgehen /\\
 und aus Juda einen Erben für meine Berge. Meine Auserwählten sollen das
Land besitzen /\\
 und meine Knechte sollen dort wohnen. ^{[[#fn7][7]]}\\
\\

<<v10>>
10 Für mein Volk, das nach mir fragt, /\\
 wird dann (die Ebene) Scharon zur Schafweide /\\
 und das Achortal zum Lagerplatz der Rinder. ^{[[#fn8][8]][[#fn9][9]]}\\
\\

<<v11>>
11 Euch aber, die ihr den Herrn verlassen, /\\
 meinen heiligen Berg vergessen, dem Glücksgott den Tisch gedeckt /\\
 und dem Gott des Schicksals den Weinkrug gefüllt habt,\\
\\

<<v12>>
12 überantworte ich dem Schwert: /\\
 Ihr müsst euch alle ducken und werdet geschlachtet. Denn ihr gabt keine
Antwort, als ich euch rief, /\\
 als ich zu euch redete, hörtet ihr nicht, sondern ihr habt getan, was
mir missfällt, /\\
 und habt euch für das entschieden, /\\
 was ich nicht will. ^{[[#fn10][10]]}\\
\\

<<v13>>
13 Darum - so spricht Gott, der Herr: /\\
 Meine Knechte sollen essen, /\\
 doch ihr leidet Hunger. Meine Knechte sollen trinken, /\\
 doch ihr leidet Durst. Meine Knechte sollen sich freuen, /\\
 doch ihr müsst euch schämen.\\
\\

<<v14>>
14 Meine Knechte sollen aus Herzenslust jubeln, /\\
 doch ihr werdet schreien vor Herzeleid und heulen vor Verzweiflung.\\
\\

<<v15>>
15 Ihr müsst euren Namen dazu hergeben, /\\
 dass meine Auserwählten ihn beim Eid /\\
 als Fluchwort gebrauchen und sagen: Genauso töte dich Gott, der Herr.
/\\
 Meinen Knechten aber wird man einen anderen Namen geben.
^{[[#fn11][11]]}\\
\\

<<v16>>
16 Wer sich segnet im Land, /\\
 wird sich Segen wünschen von Gott, dem Getreuen, und wer schwört im
Land, /\\
 wird schwören bei Gott, dem Getreuen. ^{[[#fn12][12]]}\\
\\

<<v17>>
**** Das endzeitliche Heil: 65,16e-25
     :PROPERTIES:
     :CUSTOM_ID: das-endzeitliche-heil-6516e-25
     :END:
17 Ja, vergessen sind die früheren Nöte, /\\
 sie sind meinen Augen entschwunden. Denn schon erschaffe ich einen
neuen Himmel /\\
 und eine neue Erde. Man wird nicht mehr an das Frühere denken, /\\
 es kommt niemand mehr in den Sinn. ^{[[#fn13][13]]}\\
\\

<<v18>>
18 Nein, ihr sollt euch ohne Ende freuen und jubeln /\\
 über das, was ich erschaffe. Denn ich mache aus Jerusalem Jubel /\\
 und aus seinen Einwohnern Freude.\\
\\

<<v19>>
19 Ich will über Jerusalem jubeln /\\
 und mich freuen über mein Volk. Nie mehr hört man dort lautes Weinen
/\\
 und lautes Klagen. ^{[[#fn14][14]]}\\
\\

<<v20>>
20 Dort gibt es keinen Säugling mehr, /\\
 der nur wenige Tage lebt, und keinen Greis, /\\
 der nicht das volle Alter erreicht; wer als Hundertjähriger stirbt, /\\
 gilt noch als jung, /\\
 und wer nicht hundert Jahre alt wird, /\\
 gilt als verflucht. ^{[[#fn15][15]]}\\
\\

<<v21>>
21 Sie werden Häuser bauen /\\
 und selbst darin wohnen, /\\
 sie werden Reben pflanzen /\\
 und selbst ihre Früchte genießen. ^{[[#fn16][16]]}\\
\\

<<v22>>
22 Sie bauen nicht, /\\
 damit ein anderer in ihrem Haus wohnt, und sie pflanzen nicht, /\\
 damit ein anderer die Früchte genießt. In meinem Volk werden die
Menschen so alt /\\
 wie die Bäume. Was meine Auserwählten mit eigenen Händen erarbeitet
haben, /\\
 werden sie selber verbrauchen.\\
\\

<<v23>>
23 Sie arbeiten nicht mehr vergebens, /\\
 sie bringen nicht Kinder zur Welt für einen jähen Tod. Denn sie sind
die Nachkommen der vom Herrn Gesegneten /\\
 und ihre Sprösslinge zusammen mit ihnen. ^{[[#fn17][17]]}\\
\\

<<v24>>
24 Schon ehe sie rufen, gebe ich Antwort, /\\
 während sie noch reden, erhöre ich sie. ^{[[#fn18][18]]}\\
\\

<<v25>>
25 Wolf und Lamm weiden zusammen, /\\
 der Löwe frisst Stroh wie das Rind /\\
 [doch die Schlange nährt sich von Staub]. Man tut nichts Böses mehr /\\
 und begeht kein Verbrechen /\\
 auf meinem ganzen heiligen Berg, spricht der Herr. ^{[[#fn19][19]]}\\
\\

^{[[#fnm1][1]]} ℘ (1-2) Röm 10,20f

^{[[#fnm2][2]]} nach mir: eingefügt mit dem Qumran-Text und den alten
Übersetzungen.

^{[[#fnm3][3]]} 3-5: Aufzählung heidnischer Kultbräuche.

^{[[#fnm4][4]]} 5b: Wörtlich: sonst mache ich dich heilig. - Die
kultische Heiligkeit (vgl. Ez 44,19; 46,20), hier aus dem Kult fremder
Götter, überträgt sich auf alle, die damit in Berührung kommen.

^{[[#fnm5][5]]} wie sie es verdienen, wörtlich: in ihren Gewandbausch;
so erhielt der Arbeiter seinen Lohn in Naturalien.

^{[[#fnm6][6]]} und zahle ihnen heim, wie sie es verdienen: Text korr.
nach V. 6.

^{[[#fnm7][7]]} ℘ 57,13; 60,21

^{[[#fnm8][8]]} ℘ 33,9; 1 Chr 27,29

^{[[#fnm9][9]]} Die Scharon-Ebene liegt zwischen Jaffa und dem Karmel,
das Achor-Tal nordwestlich von Jericho.

^{[[#fnm10][10]]} ℘ 34,2; 66,4; Jer 7,13.27

^{[[#fnm11][11]]} Meinen Knechten: Text korr., vgl. G; H: Seinen
Knechten.

^{[[#fnm12][12]]} ℘ 43,18

^{[[#fnm13][13]]} ℘ 66,22

^{[[#fnm14][14]]} ℘ 62,5; Offb 21,4

^{[[#fnm15][15]]} ℘ Sach 8,4

^{[[#fnm16][16]]} ℘ (21-22) 62,8f; Ps 128,2

^{[[#fnm17][17]]} ℘ 61,9

^{[[#fnm18][18]]} ℘ 58,9

^{[[#fnm19][19]]} ℘ 11,6f; Gen 3,14; Jes 11,9
