:PROPERTIES:
:ID:       c3bbdb95-f6e2-4add-8d06-29d5e4563b74
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]]
[[file:Jes_2.html][2]] [[file:Jes_3.html][3]] *4* [[file:Jes_5.html][5]]
[[file:Jes_6.html][6]] ... [[file:Jes_66.html][66]]

--------------

* Jes 4
  :PROPERTIES:
  :CUSTOM_ID: jes-4
  :END:

<<verses>>

<<v1>>
1 An jenem Tag klammern sich sieben Frauen an einen einzigen Mann und
sagen: Wir wollen unser eigenes Brot essen und uns selber kleiden, nur
lass uns deinen Namen tragen, nimm die Schande von uns!\\
\\

<<v2>>
**** Die Rettung der Übriggebliebenen: 4,2-6
     :PROPERTIES:
     :CUSTOM_ID: die-rettung-der-übriggebliebenen-42-6
     :END:
2 An jenem Tag wird, was der Herr sprossen lässt, für alle Israeliten,
die entronnen sind, eine Zierde und Ehre sein; die Früchte des Landes
sind ihr Stolz und Ruhm. ^{[[#fn1][1]]}

<<v3>>
3 Dann wird der Rest von Zion und wer in Jerusalem noch übrig ist,
heilig genannt werden, jeder, der in Jerusalem in das Verzeichnis derer,
die am Leben bleiben sollen, eingetragen ist. ^{[[#fn2][2]]}

<<v4>>
4 Wenn der Herr durch den Sturm des Gerichts und den Sturm der Läuterung
von den Töchtern Zions den Kot abgewaschen und aus Jerusalems Mitte die
Blutschuld weggespült hat, ^{[[#fn3][3]]}

<<v5>>
5 dann kommt er und über dem ganzen Gebiet des Berges Zion und seinen
Festplätzen erscheint bei Tag eine Wolke und bei Nacht Rauch und eine
strahlende Feuerflamme. Denn über allem liegt als Schutz und Schirm die
Herrlichkeit des Herrn; ^{[[#fn4][4]][[#fn5][5]]}

<<v6>>
6 sie spendet bei Tag Schatten vor der Hitze und ist Zuflucht und Obdach
bei Unwetter und Regen.\\
\\

^{[[#fnm1][1]]} was der Herr sprossen lässt: Anklang an den
messianischen Ausdruck «Spross» in Jer 23,5; 33,15; Sach 3,8; 6,12.

^{[[#fnm2][2]]} Das Verzeichnis erinnert an Bürgerlisten (vgl. Ez 13,9;
Ps 87,6).

^{[[#fnm3][3]]} Andere Übersetzungsmöglichkeit: den Geist des Gerichts
und den Geist der Läuterung.

^{[[#fnm4][4]]} ℘ Ex 13,21f

^{[[#fnm5][5]]} kommt er: Text korr. nach G.
