:PROPERTIES:
:ID:       003225c6-2549-43e0-9347-acd02f5e3032
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesaja* -- [[file:Jes_1.html][1]] ...
[[file:Jes_15.html][15]] [[file:Jes_16.html][16]] *17*
[[file:Jes_18.html][18]] [[file:Jes_19.html][19]] ...
[[file:Jes_66.html][66]]

--------------

* Jes 17
  :PROPERTIES:
  :CUSTOM_ID: jes-17
  :END:

<<verses>>

<<v1>>
**** Die Ankündigung des Gerichts über Damaskus und über das Nordreich
Israel: 17,1-11
     :PROPERTIES:
     :CUSTOM_ID: die-ankündigung-des-gerichts-über-damaskus-und-über-das-nordreich-israel-171-11
     :END:
1 Ausspruch über Damaskus. Seht hin: Damaskus verschwindet /\\
 und wird keine Stadt mehr sein, /\\
 es wird zu einem Haufen von Trümmern.\\
\\

<<v2>>
2 Die Städte um Aroër sind verlassen; /\\
 sie gehören den Herden, die dort ungestört lagern.\\
\\

<<v3>>
3 Mit dem Bollwerk von Efraim ist es zu Ende, /\\
 mit dem Königreich von Damaskus. Dem Rest von Aram wird es gehen wie
der Macht der Israeliten - /\\
 Spruch des Herrn der Heere.\\
\\

<<v4>>
4 An jenem Tag schrumpft Jakobs Macht zusammen, /\\
 das Fett seines Leibes schwindet dahin.\\
\\

<<v5>>
5 Dann wird es sein, wie wenn ein Schnitter die Halme packt /\\
 und mit seinem Arm die Ähren abmäht. Dann wird es sein, wie wenn jemand
Ähren aufliest /\\
 in der Rafaïterebene: ^{[[#fn1][1]]}\\
\\

<<v6>>
6 Nur ein Rest bleibt für die Nachlese übrig /\\
 wie beim Abernten der Ölbäume: zwei, drei reife Oliven an den oberen
Ästen des Baumes, /\\
 vier oder fünf an seinen Zweigen - /\\
 Spruch des Herrn, des Gottes Israels. ^{[[#fn2][2]]}\\
\\

<<v7>>
7 An jenem Tag werden die Menschen auf ihren Schöpfer blicken, /\\
 ihre Augen werden auf den Heiligen Israels schauen.\\
\\

<<v8>>
8 Sie blicken nicht mehr auf die Altäre, /\\
 das Machwerk ihrer Hände, sie schauen nicht mehr auf das, was ihre
Finger gemacht haben, /\\
 auf die Kultpfähle und die Räucheraltäre. ^{[[#fn3][3]]}\\
\\

<<v9>>
9 An jenem Tag sind deine befestigten Städte verlassen /\\
 wie die Städte der Hiwiter und Amoriter, die man verlassen hat aus
Furcht vor den Israeliten; /\\
 es wird eine schaurige Öde entstehen. ^{[[#fn4][4]]}\\
\\

<<v10>>
10 Denn du hast den Gott, der dich rettet, vergessen; /\\
 an den Felsen, auf dem du Zuflucht findest, /\\
 hast du nicht mehr gedacht. Leg nur liebliche Gärten an, /\\
 bepflanze sie mit Setzlingen aus der Fremde, ^{[[#fn5][5]]}\\
\\

<<v11>>
11 pfleg sie an dem Tag, an dem du sie pflanzt, /\\
 lass sie wachsen an dem Morgen, an dem du sie säst: Dahin ist die Ernte
am Tag deiner Krankheit /\\
 und des heillosen Schmerzes.\\
\\

<<v12>>
**** Der Wehruf über die Assyrer: 17,12-14
     :PROPERTIES:
     :CUSTOM_ID: der-wehruf-über-die-assyrer-1712-14
     :END:
12 Weh, welch Getöse von zahlreichen Völkern; /\\
 wie das Tosen des Meeres, so tosen sie. Man hört das Toben der
Nationen; /\\
 wie das Toben gewaltiger Fluten, so toben sie.\\
\\

<<v13>>
13 [Die Nationen toben wie das Toben gewaltiger Fluten.] /\\
 Doch der Herr wird ihnen drohen, /\\
 dann fliehen sie weit in die Ferne, dahingejagt vom Wind wie die Spreu
auf den Bergen, /\\
 wie Disteln, die der Sturm vor sich herrollt. ^{[[#fn6][6]]}\\
\\

<<v14>>
14 Am Abend herrscht plötzlich Schrecken, /\\
 doch ehe es Morgen wird verschwunden sind sie. Das ist das Schicksal
derer, die uns ausplündern wollen, /\\
 das Los derer, die uns berauben wollen.\\
\\

^{[[#fnm1][1]]} ein Schnitter: Text korr. - Die Rafaïterebene liegt
zwischen Jerusalem und Betlehem.

^{[[#fnm2][2]]} ℘ 24,13

^{[[#fnm3][3]]} ℘ 27,9

^{[[#fnm4][4]]} 9ab: Text korr.; vgl. G.

^{[[#fnm5][5]]} 10f: Hier werden Praktiken verurteilt, die Fruchtbarkeit
und Leben garantieren sollen.

^{[[#fnm6][6]]} ℘ Ps 83,14
