:PROPERTIES:
:ID:       a1998157-8519-4d7b-ad2f-59a66184da0c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jona* -- [[file:Jona_1.html][1]]
[[file:Jona_2.html][2]] [[file:Jona_3.html][3]] *4*

--------------

* Jona 4
  :PROPERTIES:
  :CUSTOM_ID: jona-4
  :END:

<<verses>>

<<v1>>
** Die Belehrung des Propheten: 4,1-11
   :PROPERTIES:
   :CUSTOM_ID: die-belehrung-des-propheten-41-11
   :END:
1 Das missfiel Jona ganz und gar und er wurde zornig.

<<v2>>
2 Er betete zum Herrn und sagte: Ach Herr, habe ich das nicht schon
gesagt, als ich noch daheim war? Eben darum wollte ich ja nach
Tarschisch fliehen; denn ich wusste, dass du ein gnädiger und
barmherziger Gott bist, langmütig und reich an Huld und dass deine
Drohungen dich reuen. ^{[[#fn1][1]]}

<<v3>>
3 Darum nimm mir jetzt lieber das Leben, Herr! Denn es ist für mich
besser zu sterben als zu leben. ^{[[#fn2][2]]}

<<v4>>
4 Da erwiderte der Herr: Ist es recht von dir, zornig zu sein?

<<v5>>
5 Da verließ Jona die Stadt und setzte sich östlich vor der Stadt
nieder. Er machte sich dort ein Laubdach und setzte sich in seinen
Schatten, um abzuwarten, was mit der Stadt geschah.

<<v6>>
6 Da ließ Gott, der Herr, einen Rizinusstrauch über Jona emporwachsen,
der seinem Kopf Schatten geben und seinen Ärger vertreiben sollte. Jona
freute sich sehr über den Rizinusstrauch.

<<v7>>
7 Als aber am nächsten Tag die Morgenröte heraufzog, schickte Gott einen
Wurm, der den Rizinusstrauch annagte, sodass er verdorrte.

<<v8>>
8 Und als die Sonne aufging, schickte Gott einen heißen Ostwind. Die
Sonne stach Jona auf den Kopf, sodass er fast ohnmächtig wurde. Da
wünschte er sich den Tod und sagte: Es ist besser für mich zu sterben
als zu leben.

<<v9>>
9 Gott aber fragte Jona: Ist es recht von dir, wegen des
Rizinusstrauches zornig zu sein? Er antwortete: Ja, es ist recht, dass
ich zornig bin und mir den Tod wünsche.

<<v10>>
10 Darauf sagte der Herr: Dir ist es leid um den Rizinusstrauch, für den
du nicht gearbeitet und den du nicht großgezogen hast. Über Nacht war er
da, über Nacht ist er eingegangen.

<<v11>>
11 Mir aber sollte es nicht leid sein um Ninive, die große Stadt, in der
mehr als hundertzwanzigtausend Menschen leben, die nicht einmal rechts
und links unterscheiden können - und außerdem so viel Vieh?\\
\\

^{[[#fnm1][1]]} ℘ Ex 34,6; Joël 2,13

^{[[#fnm2][2]]} ℘ 1 Kön 19,4
