#+TITLE: Jos 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-01 Mi 10:23]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jos 1.html


* Jos 1

* Die Bücher der Geschichte des Volkes Gottes

Dieses Buch ist nach Josua, dem Nachfolger des Mose, benannt. Es
berichtet vom Einzug Israels in das verheißene Land und umfasst den
Zeitraum vom Tod des Mose bis zum Tod Josuas. In dieser Zeit wird nach
der Darstellung des Buches das von Gott verheißene Land westlich des
Jordan erobert und durch Josua an die Stämme Israels verteilt, soweit
sie nicht schon im Ostjordanland (Ruben, Gad und der halbe Stamm
Manasse) Landbesitz erhalten haben (vgl. Num 32). Der Bericht über die
feierliche Verpflichtung Israels auf Jahwe, seinen Gott, schließt das
Buch ab. Dementsprechend besteht das Buch aus drei Teilen: Eroberung des
Westjordanlandes unter Führung Josuas (Kap. 1 12); Verteilung des Landes
(Kap. 13 - 22); Verpflichtung auf Jahwe (Kap. 23 und 24).\\
\\
Der erste Teil enthält Erzählungen über die Landnahme, die als rein
kriegerisches Unternehmen gesehen wird (doch vgl. Ri 1). Die meisten
dieser Erzählungen, ausgenommen der Bericht über die Schlacht bei dem im
Norden Palästinas gelegenen Merom (11,1-15), spielen in Mittelpalästina.
Dort gewann der Stamm Benjamin, dem Josua angehörte, sein Gebiet. Josua
wird zur beherrschenden Gestalt der ganzen Darstellung der Eroberung des
Landes: Nach seiner Beauftragung (Kap. 1) wird Jericho erkundet (Kap. 2)
und der Jordan überschritten (Kap. 3 und 4). Israel lagert in Gilgal
(Kap. 5) und erobert von dort aus durch göttliche Hilfe Jericho (Kap.
6). Nach einem Fehlschlag, der durch einen Diebstahl Achans an dem Jahwe
geweihten Beutegut verursacht war, wird Ai erobert (Kap. 7 und 8). Die
Gibeoniter erlisten sich einen Vertrag mit Israel (Kap. 9); in der Nähe
ihrer Stadt werden fünf Könige der Kanaaniter besiegt (Kap. 10). Über
Eroberungen im Süden und Norden wird nur zusammenfassend berichtet
(10,28 - 11,23). Eine Liste der in Kanaan besiegten Könige beschließt
die Darstellung der Landnahme (Kap. 12).\\
\\
Die Erzählungen des Buches Josua sind von recht verschiedener Art: Neben
Kampfberichten stehen listenartige Angaben, Anweisungen und Berichte
über kultische Begehungen, Erzählungen über Auseinandersetzungen in
Israel selbst und mit den Bewohnern des Landes. Einige dieser
Erzählungen, darunter Kap. 22, »erklären« auffallende Gegebenheiten: den
Steinkreis bei Gilgal, die zwölf Steine im Jordan, die Ortsnamen »Hügel
der Vorhäute« und Gilgal, den Steinhaufen im Achortal bei Jericho, den
Ruinenhügel bei Ai, das Vertragsverhältnis mit Gibeon, den Altar im
Ostjordanland. Man bezeichnet sie deshalb als Ätiologien
(Ursprungserzählungen).\\
\\
Der zweite Teil enthält die Angaben über die Verteilung des Landes. Nach
dem Befehl Gottes (13,1-7) werden das Ostjordanland (13,15-33) und das
Westjordanland an die Stämme verteilt (Kap. 14 19). Asyl- und
Levitenstädte werden eingerichtet (Kap. 20 und 21). Der Streit um einen
Altar östlich des Jordan wird beigelegt (Kap. 22). In der Gebiets- und
Grenzbeschreibung der einzelnen Stämme sind vermutlich alte Listen, vor
allem über die verwaltungsmäßige Einteilung Judas, verwendet.\\
\\
Der dritte Teil des Buches enthält zwei Abschiedsreden, in denen Josua
Israel zum Gehorsam gegenüber Gott verpflichtet. Diese Verpflichtung
übernimmt Israel auf dem »Landtag« zu Sichem (Kap. 23 und 24).\\
\\
Das Buch Josua, das zum Deuteronomistischen Geschichtswerk gehört (vgl.
die Einleitung zum Buch Deuteronomium), will bezeugen, dass Gott die
Landverheißung eingelöst hat, und es mahnt Israel, seinem Bund mit Gott
treu zu bleiben.\\
\\

<<verses>>

<<v1>>
* Die Eroberung des Landes: 1,1 - 12,24

* Der Befehl zur Besetzung des Westjordanlandes: 1,1-18

1 Nachdem Mose, der Knecht des Herrn, gestorben war, sagte der Herr zu
Josua, dem Sohn Nuns, dem Diener des Mose: [fn:1]

<<v2>>
2 Mein Knecht Mose ist gestorben. Mach dich also auf den Weg und zieh
über den Jordan hier mit diesem ganzen Volk in das Land, das ich ihnen,
den Israeliten, geben werde.

<<v3>>
3 Jeden Ort, den euer Fuß betreten wird, gebe ich euch, wie ich es Mose
versprochen habe. [fn:2]

<<v4>>
4 Euer Gebiet soll von der Steppe und vom Libanon an bis zum großen
Strom, zum Eufrat, reichen - das ist das ganze Land der Hetiter - und
bis hin zum großen Meer, wo die Sonne untergeht. [fn:3]

<<v5>>
5 Niemand wird dir Widerstand leisten können, solange du lebst. Wie ich
mit Mose war, will ich auch mit dir sein. Ich lasse dich nicht fallen
und verlasse dich nicht. [fn:4]

<<v6>>
6 Sei mutig und stark! Denn du sollst diesem Volk das Land zum Besitz
geben, von dem du weißt: Ich habe ihren Vätern geschworen, es ihnen zu
geben. [fn:5] [fn:6]

<<v7>>
7 Sei nur mutig und stark und achte genau darauf, dass du ganz nach der
Weisung handelst, die mein Knecht Mose dir gegeben hat. Weich nicht nach
rechts und nicht nach links davon ab, damit du Erfolg hast in allem, was
du unternimmst. [fn:7]

<<v8>>
8 Über dieses Gesetzbuch sollst du immer reden und Tag und Nacht darüber
nachsinnen, damit du darauf achtest, genau so zu handeln, wie darin
geschrieben steht. Dann wirst du auf deinem Weg Glück und Erfolg haben.

<<v9>>
9 Habe ich dir nicht befohlen: Sei mutig und stark? Fürchte dich also
nicht und hab keine Angst; denn der Herr, dein Gott, ist mit dir bei
allem, was du unternimmst.

<<v10>>
10 Da befahl Josua den Listenführern im Volk:

<<v11>>
11 Geht durch das Lager und befehlt den Leuten: Versorgt euch mit
Lebensmitteln; denn in drei Tagen werdet ihr den Jordan hier
überschreiten, um in das Land hineinzuziehen und es in Besitz zu nehmen,
das der Herr, euer Gott, euch zu eigen gibt. [fn:8]

<<v12>>
12 Und den Rubenitern, den Gaditern und dem halben Stamm Manasse sagte
Josua: [fn:9] [fn:10]

<<v13>>
13 Erinnert euch an das, was Mose, der Knecht des Herrn, euch geboten
hat: Der Herr, euer Gott, gewährt euch Ruhe und gibt euch dieses Land. [fn:11]

<<v14>>
14 Eure Frauen, eure Kinder und euer Vieh sollen in dem Land bleiben,
das Mose euch östlich des Jordan gegeben hat. Ihr aber sollt mit euren
Brüdern hinübergehen, ihnen kampfbereit mit allen Kriegern voranziehen
und ihnen helfen, [fn:12]

<<v15>>
15 bis der Herr euren Brüdern ebenso wie euch Ruhe gewährt und bis auch
sie das Land in Besitz nehmen, das der Herr, euer Gott, ihnen gibt. Dann
sollt ihr in euren eigenen Besitz zurückkehren, in das Land, das euch
Mose, der Knecht des Herrn, östlich des Jordan gegen Sonnenaufgang als
Besitz gegeben hat.

<<v16>>
16 Sie antworteten Josua: Alles, was du uns befohlen hast, wollen wir
tun und dahin, wohin du uns schickst, werden wir gehen.

<<v17>>
17 Genauso, wie wir auf Mose gehört haben, wollen wir auch auf dich
hören. Der Herr aber, dein Gott, möge mit dir sein, wie er mit Mose
gewesen ist.

<<v18>>
18 Jeder, der sich deinem Befehl widersetzt und nicht allen deinen
Anordnungen gehorcht, soll mit dem Tod bestraft werden. Sei nur mutig
und stark!\\
\\

* Footnotes

[fn:1] [[file:Dtn_34.org::v5][Dtn 34,5]]

[fn:2] [[file:Dtn_11.org::v24][Dtn 11,24]]

[fn:3] Umschreibung des verheißenen Landes in seiner idealen
größten Ausdehnung. Syrien-Palästina ist nach den assyrischen
Königsinschriften das Hetiterland.

[fn:4] [[file:Dtn_31.org::v6][Dtn 31,6]].[[file:Dtn_31.org::v8][8]]

[fn:5] [[file:Dtn_3.org::v28][Dtn 3,28]]

[fn:6] Vgl. die Anmerkung zu [[file:Dtn_1.org::v8][Dtn 1,8]].

[fn:7] [[file:Dtn_5.org::v32][Dtn 5,32]]; [[file:Dtn_29.org::v8][29,8]]

[fn:8] [[file:Dtn_3.org::v12][Dtn 3,12-29]]

[fn:9] (12-18) [[file:Jos_4.org::v12][4,12]]

[fn:10] Diese Stämme hatten ihren Landanteil bereits im
Ostjordanland erhalten (vgl. [[file:Num_32.org::v1][Num 32]]).

[fn:11] [[file:Num_32.org::v20][Num 32,20-29]]

[fn:12] 14f: östlich, wörtlich: jenseits; vom Standpunkt des
Autors aus betrachtet, der in Palästina lebt.
