#+TITLE: Jos 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-01 Mi 23:40]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jos 3.html

<<verses>>

<<v1>>
* Der Übergang über den Jordan: 3,1-17

1 Am frühen Morgen brach Josua mit allen Israeliten von Schittim auf.
Als sie an den Jordan kamen, übernachteten sie dort, bevor sie ihn
überschritten.

<<v2>>
2 Nach drei Tagen gingen die Listenführer durch das Lager

<<v3>>
3 und befahlen dem Volk: Wenn ihr die Bundeslade des Herrn, eures
Gottes, seht und die levitischen Priester, die sie tragen, dann sollt
auch ihr von dort, wo ihr gerade seid, aufbrechen und ihr folgen;

<<v4>>
4 nur müsst ihr zwischen ihr und euch einen Abstand von zweitausend
Ellen lassen, ihr dürft nicht zu nahe an sie herankommen. So werdet ihr
wissen, welchen Weg ihr gehen sollt; denn ihr seid den Weg ja früher
noch nie gegangen.

<<v5>>
5 Und Josua sagte zum Volk: Heiligt euch; denn morgen wird der Herr
mitten unter euch Wunder tun. [fn:1]

<<v6>>
6 Und zu den Priestern sagte Josua: Nehmt die Bundeslade auf und zieht
dem Volk voran! Und sie nahmen die Bundeslade auf und gingen dem Volk
voraus.

<<v7>>
7 Da sagte der Herr zu Josua: Heute fange ich an, dich vor den Augen
ganz Israels groß zu machen, damit alle erkennen, dass ich mit dir sein
werde, wie ich mit Mose gewesen bin. [fn:2]

<<v8>>
8 Du aber sollst den Priestern, die die Bundeslade tragen, befehlen:
Wenn ihr zum Ufer des Jordan kommt, geht in den Jordan hinein und bleibt
dort stehen!

<<v9>>
9 Darauf sagte Josua zu den Israeliten: Kommt her und hört die Worte des
Herrn, eures Gottes!

<<v10>>
10 Dann sagte Josua: Daran sollt ihr erkennen, dass ein lebendiger Gott
mitten unter euch ist: Er wird die Kanaaniter, die Hetiter, Hiwiter,
Perisiter, Girgaschiter, Amoriter und Jebusiter vor euren Augen
vertreiben.

<<v11>>
11 Seht, die Bundeslade des Herrn der ganzen Erde zieht vor euch her
durch den Jordan.

<<v12>>
12 Wählt nun zwölf Männer aus den Stämmen Israels aus, aus jedem Stamm
einen! [fn:3]

<<v13>>
13 Sobald die Füße der Priester, die die Lade des Herrn tragen, des
Herrn der ganzen Erde, im Wasser des Jordan stehen, wird das Wasser des
Jordan, das von oben herabkommt, wie abgeschnitten sein und wie ein Wall
dastehen. [fn:4]

<<v14>>
14 Als dann das Volk seine Zelte verließ und aufbrach, um den Jordan zu
überschreiten, gingen die Priester, die die Bundeslade trugen, an der
Spitze des Volkes.

<<v15>>
15 Und als die Träger der Lade an den Jordan kamen und die Füße der
Priester, die die Lade trugen, das Wasser berührten - der Jordan war
aber während der ganzen Erntezeit über alle Ufer getreten -,

<<v16>>
16 da blieben die Fluten des Jordan stehen. Das von oben herabkommende
Wasser stand wie ein Wall in weiter Entfernung, bei der Stadt Adam, die
in der Nähe von Zaretan liegt. Die zum Meer der Araba, zum Salzmeer,
hinabfließenden Fluten dagegen liefen vollständig ab und das Volk zog
Jericho gegenüber durch den Jordan. [fn:5] [fn:6]

<<v17>>
17 Die Priester, die die Bundeslade des Herrn trugen, standen, während
ganz Israel trockenen Fußes hindurchzog, fest und sicher mitten im
Jordan auf trockenem Boden, bis das ganze Volk den Jordan durchschritten
hatte.\\
\\

* Footnotes

[fn:1] Wie für eine kultische Handlung muss sich das Volk durch
sexuelle Enthaltung und Reinigen der Kleider bereit machen.

[fn:2] [[file:Jos_4.org::v14][4,14]]; [[file:Jos_1.org::v5][1,5]].[[file:Jos_1.org::v17][17]]

[fn:3] Die Aufgabe der zwölf Männer wird in [[file:Jos_4.org::v2][4,2-5]] mitgeteilt.

[fn:4] [[file:Jos_4.org::v7][4,7]]

[fn:5] [[file:Ex_14.org::v21][Ex 14,21]]; [[file:Ps_114.org::v3][Ps 114,3]]

[fn:6] Die Stadt Adam sucht man in der Nähe der Einmündung des
Jabbok in den Jordan. Das «Meer der Araba» ist das Tote Meer.
