#+TITLE: Jos 10 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-02 Do 10:24]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jos 10.html


<<verses>>

<<v1>>
* Der Krieg mit den fünf Kanaaniter-Königen: 10,1-27

1 Adoni-Zedek, der König von Jerusalem, hörte, dass Josua Ai erobert und
dem Untergang geweiht hatte - wie er es mit Jericho und seinem König
gemacht hatte, so hatte er es auch mit Ai und seinem König gemacht - und
dass die Einwohner von Gibeon mit den Israeliten Frieden geschlossen
hatten und weiterhin mitten unter ihnen leben durften. [fn:1] [fn:2]

<<v2>>
2 Da bekam er große Angst; denn die Stadt Gibeon war ebenso groß wie die
Städte mit Königssitz; sie war größer als Ai und alle ihre Männer waren
kampferprobte Krieger. [fn:3]

<<v3>>
3 Darum sandte Adoni-Zedek, der König von Jerusalem, Boten an Hoham, den
König von Hebron, an Piram, den König von Jarmut, an Jafia, den König
von Lachisch, und an Debir, den König von Eglon, und ließ ihnen sagen: [fn:4]

<<v4>>
4 Zieht herauf zu mir und helft mir! Wir wollen Gibeon schlagen, weil es
mit Josua und den Israeliten Frieden geschlossen hat.

<<v5>>
5 Da sammelten sich die fünf Könige der Amoriter und zogen mit ihren
ganzen Heeren hinauf: der König von Jerusalem, der König von Hebron, der
König von Jarmut, der König von Lachisch und der König von Eglon. Sie
belagerten Gibeon und eröffneten den Kampf gegen die Stadt.

<<v6>>
6 Darauf sandten die Männer von Gibeon (Boten) zu Josua ins Lager nach
Gilgal und ließen ihm sagen: Lass deine Knechte nicht im Stich! Zieh
schnell herauf zu uns, rette uns und komm uns zu Hilfe; denn alle
Amoriterkönige, die das Bergland bewohnen, haben sich gegen uns
zusammengetan.

<<v7>>
7 Da zog Josua mit dem ganzen Heer, mit allen kampferprobten Männern,
von Gilgal herauf.

<<v8>>
8 Der Herr sagte zu Josua: Fürchte dich nicht vor ihnen; denn ich gebe
sie in deine Gewalt. Keiner von ihnen kann dir standhalten.

<<v9>>
9 Nachdem Josua die ganze Nacht von Gilgal her auf dem Marsch gewesen
war, stieß er plötzlich auf sie.

<<v10>>
10 Der Herr versetzte sie beim Anblick der Israeliten in Verwirrung,
sodass Josua ihnen bei Gibeon eine schwere Niederlage beibringen konnte.
Er verfolgte sie in Richtung auf die Steige von Bet-Horon und schlug sie
bis nach Aseka und Makkeda zurück. [fn:5]

<<v11>>
11 Als sie auf der Flucht vor Israel an den Abhang von Bet-Horon kamen,
warf der Herr große Steine auf sie vom Himmel her, bis nach Aseka hin,
sodass viele umkamen. Es kamen mehr durch die Hagelsteine um, als die
Israeliten mit dem Schwert töteten.\\
\\

<<v12>>
12 Damals, als der Herr die Amoriter den Israeliten preisgab, redete
Josua mit dem Herrn; dann sagte er in Gegenwart der Israeliten: Sonne,
bleib stehen über Gibeon /\\
 und du, Mond, über dem Tal von Ajalon! - [fn:6] [fn:7]\\
\\

<<v13>>
13 Und die Sonne blieb stehen /\\
 und der Mond stand still, /\\
 bis das Volk an seinen Feinden Rache genommen hatte. Das steht im «Buch
des Aufrechten». Die Sonne blieb also mitten am Himmel stehen und ihr
Untergang verzögerte sich, ungefähr einen ganzen Tag lang. [fn:8]\\
\\

<<v14>>
14 Weder vorher noch nachher hat es je einen solchen Tag gegeben, an dem
der Herr auf die Stimme eines Menschen gehört hätte; der Herr kämpfte
nämlich für Israel.

<<v15>>
15 Danach kehrte Josua und mit ihm ganz Israel in das Lager nach Gilgal
zurück.

<<v16>>
16 Die fünf Könige aber waren geflohen und hatten sich in der Höhle bei
Makkeda versteckt.

<<v17>>
17 Da meldete man Josua: Wir haben die fünf Könige gefunden; sie haben
sich in der Höhle bei Makkeda versteckt.

<<v18>>
18 Josua sagte: Wälzt große Steine vor den Eingang der Höhle und stellt
einige Männer davor, um die Könige zu bewachen.

<<v19>>
19 Ihr (anderen) aber bleibt nicht stehen, sondern verfolgt die Feinde
und macht auch noch die Nachhut nieder! Lasst sie nicht bis zu ihren
Städten gelangen; denn der Herr, euer Gott, hat sie in eure Gewalt
gegeben.

<<v20>>
20 So brachten Josua und die Israeliten ihnen endgültig eine schwere
Niederlage bei, die sie völlig vernichtete; nur einige Flüchtlinge
konnten entkommen und in die festen Städte gelangen.

<<v21>>
21 Darauf kehrte das ganze Heer wohlbehalten zu Josua nach Makkeda
zurück und keiner wagte es mehr, die Israeliten zu bedrohen.

<<v22>>
22 Dann sagte Josua: Öffnet den Eingang der Höhle und bringt die fünf
Könige aus der Höhle zu mir her!

<<v23>>
23 Sie taten es und führten die fünf Könige aus der Höhle heraus: den
König von Jerusalem, den König von Hebron, den König von Jarmut, den
König von Lachisch und den König von Eglon.

<<v24>>
24 Als man die Könige zu Josua gebracht hatte, rief Josua alle
Israeliten herbei und sagte zu den Anführern der Krieger, die mit ihm
ausgezogen waren: Kommt her, setzt diesen Königen euren Fuß auf den
Nacken! Sie kamen herbei und setzten ihnen den Fuß auf den Nacken.

<<v25>>
25 Und Josua sagte zu ihnen: Fürchtet euch nicht und habt keine Angst!
Seid mutig und stark! Denn so wird es der Herr mit allen euren Feinden
machen, mit denen ihr kämpfen werdet.

<<v26>>
26 Danach erschlug Josua die Könige und ließ die Leichen an fünf Bäumen
aufhängen. Dort blieben sie bis zum Abend hängen. [fn:9]

<<v27>>
27 Bei Sonnenuntergang befahl Josua, sie von den Bäumen abzunehmen und
in die Höhle zu werfen, in der sie sich zuvor versteckt hatten. Dann
wälzte man große Steine vor den Eingang der Höhle; sie liegen dort bis
zum heutigen Tag.\\
\\

<<v28>>
* Die Eroberung von sechs Städten: 10,28-43

28 Am gleichen Tag nahm Josua Makkeda ein und erschlug seine Einwohner
und seinen König mit scharfem Schwert. Er weihte sie und alles, was in
der Stadt lebte, dem Untergang; niemand ließ er entkommen. Mit dem König
von Makkeda machte er es, wie er es mit dem König von Jericho gemacht
hatte.

<<v29>>
29 Dann zog Josua mit ganz Israel von Makkeda weiter nach Libna und
kämpfte gegen Libna.

<<v30>>
30 Der Herr gab auch Libna und seinen König in die Gewalt Israels. Josua
erschlug alles, was in ihm lebte, mit scharfem Schwert; niemand ließ er
entkommen. Mit seinem König machte er es, wie er es mit dem König von
Jericho gemacht hatte.

<<v31>>
31 Dann zog Josua mit ganz Israel von Libna weiter nach Lachisch,
belagerte die Stadt und griff sie an.

<<v32>>
32 Und der Herr gab auch Lachisch in die Gewalt Israels. Josua nahm die
Stadt am zweiten Tag ein. Er erschlug alles, was in ihr lebte, mit
scharfem Schwert, genau so, wie er es mit Libna gemacht hatte.

<<v33>>
33 Als Horam, der König von Geser, heranzog, um Lachisch zu helfen,
schlug Josua auch ihn und sein Volk und ließ niemand übrig, der hätte
entkommen können.

<<v34>>
34 Dann zog Josua mit ganz Israel von Lachisch weiter nach Eglon. Sie
belagerten die Stadt und griffen sie an.

<<v35>>
35 Noch am gleichen Tag nahmen sie die Stadt ein und erschlugen ihre
Einwohner mit scharfem Schwert. Alles, was in ihr lebte, weihte man noch
am gleichen Tag dem Untergang, genau so, wie man es mit Lachisch gemacht
hatte.

<<v36>>
36 Von Eglon zog Josua mit ganz Israel nach Hebron hinauf und griff es
an.

<<v37>>
37 Sie nahmen die Stadt ein und erschlugen [ihren König und] alles, was
in ihr lebte, ebenso die Einwohner aller ihrer Tochterstädte, mit
scharfem Schwert; niemand ließ er entkommen, genau so, wie er es mit
Eglon gemacht hatte. Er weihte die Stadt und alles, was in ihr lebte,
dem Untergang. [fn:10]

<<v38>>
38 Dann wandte sich Josua mit ganz Israel gegen Debir und griff die
Stadt an.

<<v39>>
39 Er eroberte die Stadt und ihre (Tochter)städte, nahm ihren König
gefangen, erschlug ihre Einwohner mit scharfem Schwert und weihte alles,
was in ihr lebte, dem Untergang; niemand ließ er entkommen. Wie er es
mit Hebron und mit Libna und seinem König gemacht hatte, so machte er es
auch mit Debir und seinem König.

<<v40>>
40 So schlug Josua das ganze Land - das Bergland und den Negeb, die
Schefela und ihre Ausläufer - mit allen seinen Königen. Niemand ließ er
entkommen; alles, was lebte, weihte er dem Untergang, wie es der Herr,
der Gott Israels, befohlen hatte.

<<v41>>
41 Josua eroberte (das ganze Gebiet) von Kadesch-Barnea bis Gaza und
ebenso das ganze Land Goschen und das Gebiet bis nach Gibeon.

<<v42>>
42 Aller dieser Könige und ihrer Länder bemächtigte sich Josua mit einem
Schlag; denn der Herr, der Gott Israels, kämpfte für Israel.

<<v43>>
43 Dann kehrte Josua mit ganz Israel in das Lager nach Gilgal zurück.\\
\\

* Footnotes

[fn:1] [[file:Jos_6.org::v1][6]]; [[file:Jos_8.org::v1][8]]; [[file:Jos_9.org::v1][9]]

[fn:2] Jerusalem wurde erst durch David erobert (vgl. [[file:2.Sam_5.org::v6][2 Sam 5,6-9]]).

[fn:3] er: Text korr. nach S und Vg.

[fn:4] Städte südlich und südwestlich von Jerusalem.

[fn:5] [[file:Ex_23.org::v27][Ex 23,27]]; [[file:Ri_4.org::v15][Ri 4,15]]; [[file:1.Sam_7.org::v10][1 Sam 7,10]]

[fn:6] [[file:Hab_3.org::v11][Hab 3,11]]

[fn:7] 12f: Der Sieg, in dem Gott durch ein schweres Unwetter
Israel half, wird mit einem Stück aus einem uns nicht bekannten
Liederbuch gefeiert und dichterisch ausgemalt.

[fn:8] [[file:2.Sam_1.org::v18][2 Sam 1,18]]

[fn:9] [[file:Dtn_21.org::v23][Dtn 21,23]]

[fn:10] Nach VV. [[v23][23]]-[[v26][26]] ist der König schon tot.
