#+TITLE: Jos 24 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-03 Fr 14:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jos 24.html

<<verses>>

<<v1>>
* Die Versammlung des Volkes in Sichem: 24,1-28

1 Josua versammelte alle Stämme Israels in Sichem; er rief die Ältesten
Israels, seine Oberhäupter, Richter und Listenführer zusammen und sie
traten vor Gott hin. [fn:1]

<<v2>>
2 Josua sagte zum ganzen Volk: So spricht der Herr, der Gott Israels:
Jenseits des Stroms wohnten eure Väter von Urzeiten an [Terach, der
Vater Abrahams und der Vater Nahors] und dienten anderen Göttern. [fn:2]

<<v3>>
3 Da holte ich euren Vater Abraham von jenseits des Stroms und ließ ihn
durch das ganze Land Kanaan ziehen. Ich schenkte ihm zahlreiche
Nachkommenschaft und gab ihm Isaak. [fn:3]

<<v4>>
4 Dem Isaak gab ich Jakob und Esau und ich verlieh Esau das Bergland
Seïr, damit er es in Besitz nahm. Jakob aber und seine Söhne zogen nach
Ägypten hinab. [fn:4]

<<v5>>
5 Dann sandte ich Mose und Aaron und strafte Ägypten durch das, was ich
in Ägypten tat. Danach habe ich euch herausgeführt [fn:5]

<<v6>>
6 [ich führte eure Väter heraus] aus Ägypten und ihr seid ans Meer
gekommen. Die Ägypter aber verfolgten eure Väter mit Wagen und Pferden
bis zum Schilfmeer. [fn:6]

<<v7>>
7 Da schrien eure Väter zum Herrn und er legte zwischen euch und die
Ägypter eine Finsternis und ließ das Meer über sie kommen, sodass es sie
überflutete. Mit eigenen Augen habt ihr gesehen, was ich in Ägypten
getan habe. Dann habt ihr euch lange in der Wüste aufgehalten.

<<v8>>
8 Ich brachte euch in das Land der Amoriter, die jenseits des Jordan
wohnten. Sie kämpften mit euch, aber ich gab sie in eure Gewalt; ihr
habt ihr Land in Besitz genommen und ich habe sie euretwegen vernichtet. [fn:7]

<<v9>>
9 Dann erhob sich der König Balak von Moab, der Sohn Zippors, und
kämpfte gegen Israel. Er schickte Boten zu Bileam, dem Sohn Beors, und
ließ ihn rufen, damit er euch verflucht. [fn:8]

<<v10>>
10 Ich aber wollte keinen Fluch von Bileam hören. Darum musste er euch
segnen und ich rettete euch aus seiner Gewalt. [fn:9]

<<v11>>
11 Dann habt ihr den Jordan durchschritten und seid nach Jericho
gekommen; die Bürger von Jericho kämpften gegen euch, ebenso die
Amoriter, die Perisiter, die Kanaaniter, die Hetiter, die Girgaschiter,
die Hiwiter und die Jebusiter und ich gab sie in eure Gewalt. [fn:10]

<<v12>>
12 Ich habe Panik vor euch hergeschickt. Sie trieb sie vor euch her [die
beiden Könige der Amoriter]; das geschah nicht durch dein Schwert und
deinen Bogen. [fn:11] [fn:12]

<<v13>>
13 Ich gab euch ein Land, um das ihr euch nicht bemüht hattet, und
Städte, die ihr nicht erbaut hattet. Ihr habt in ihnen gewohnt und ihr
habt von Weinbergen und Ölbäumen gegessen, die ihr nicht gepflanzt
hattet. [fn:13]

<<v14>>
14 Fürchtet also jetzt den Herrn und dient ihm in vollkommener Treue.
Schafft die Götter fort, denen eure Väter jenseits des Stroms und in
Ägypten gedient haben, und dient dem Herrn!

<<v15>>
15 Wenn es euch aber nicht gefällt, dem Herrn zu dienen, dann
entscheidet euch heute, wem ihr dienen wollt: den Göttern, denen eure
Väter jenseits des Stroms dienten, oder den Göttern der Amoriter, in
deren Land ihr wohnt. Ich aber und mein Haus, wir wollen dem Herrn
dienen.

<<v16>>
16 Das Volk antwortete: Das sei uns fern, dass wir den Herrn verlassen
und anderen Göttern dienen.

<<v17>>
17 Denn der Herr, unser Gott, war es, der uns und unsere Väter aus dem
Sklavenhaus Ägypten herausgeführt hat und der vor unseren Augen alle die
großen Wunder getan hat. Er hat uns beschützt auf dem ganzen Weg, den
wir gegangen sind, und unter allen Völkern, durch deren Gebiet wir
gezogen sind.

<<v18>>
18 Der Herr hat alle Völker vertrieben, auch die Amoriter, die vor uns
im Land wohnten. Auch wir wollen dem Herrn dienen; denn er ist unser
Gott.

<<v19>>
19 Da sagte Josua zum Volk: Ihr seid nicht imstande, dem Herrn zu
dienen, denn er ist ein heiliger Gott, ein eifersüchtiger Gott; er wird
euch eure Frevel und eure Sünden nicht verzeihen. [fn:14]

<<v20>>
20 Wenn ihr den Herrn verlasst und fremden Göttern dient, dann wird er
sich von euch abwenden, wird Unglück über euch bringen und euch ein Ende
bereiten, obwohl er euch zuvor Gutes getan hat.

<<v21>>
21 Das Volk aber sagte zu Josua: Nein, wir wollen dem Herrn dienen.

<<v22>>
22 Josua antwortete dem Volk: Ihr seid Zeugen gegen euch selbst, dass
ihr euch für den Herrn und für seinen Dienst entschieden habt. [Sie
antworteten: Das sind wir.]

<<v23>>
23 Schafft also jetzt die fremden Götter ab, die noch bei euch sind, und
neigt eure Herzen dem Herrn zu, dem Gott Israels!

<<v24>>
24 Das Volk sagte zu Josua: Dem Herrn, unserem Gott, wollen wir dienen
und auf seine Stimme hören.

<<v25>>
25 So schloss Josua an jenem Tag einen Bund für das Volk und gab dem
Volk Gesetz und Recht in Sichem. [fn:15]

<<v26>>
26 Josua schrieb alle diese Worte in das Buch des Gesetzes Gottes und er
nahm einen großen Stein und stellte ihn in Sichem unter der Eiche auf,
die im Heiligtum des Herrn steht. [fn:16]

<<v27>>
27 Dabei sagte er zu dem ganzen Volk: Seht her, dieser Stein wird ein
Zeuge sein gegen uns; denn er hat alle Worte des Herrn gehört, die er zu
uns gesprochen hat. Er soll ein Zeuge sein gegen euch, damit ihr euren
Gott nicht verleugnet.

<<v28>>
28 Dann entließ Josua das Volk, einen jeden in seinen Erbbesitz.\\
\\

<<v29>>
* Die Grabstätten Josuas, Josefs und Eleasars: 24,29-33

29 Nach diesen Ereignissen starb Josua, der Sohn Nuns, der Knecht des
Herrn, im Alter von hundertzehn Jahren. [fn:17]

<<v30>>
30 Man begrub ihn in Timnat-Serach, im Gebiet seines Erbbesitzes auf dem
Gebirge Efraim, nördlich vom Berg Gaasch.

<<v31>>
31 Israel aber diente dem Herrn, solange Josua lebte und solange die
Ältesten am Leben waren, die Josua überlebten und alles wussten, was der
Herr für Israel getan hatte. [fn:18]

<<v32>>
32 Die Gebeine Josefs, die die Israeliten aus Ägypten mitgebracht
hatten, begrub man in Sichem auf dem Grundstück, das Jakob von den
Söhnen Hamors, des Vaters Sichems, für hundert Kesita erworben hatte; es
war den Nachkommen Josefs als Erbbesitz zuteil geworden. [fn:19]

<<v33>>
33 Auch Eleasar, der Sohn Aarons, starb und man begrub ihn in Gibea,
(der Stadt) seines Sohnes Pinhas, die man ihm im Gebirge Efraim gegeben
hatte. [fn:20]\\
\\

* Footnotes

[fn:1] 1-28: Der sog. Landtag zu Sichem ist eine Versammlung
der Stämme Israels. Vor ihnen hält Josua eine zweite Abschiedsrede. Auch
darin klingen deuteronomische Gedanken an.

[fn:2] [[file:Gen_11.org::v26][Gen 11,26]]

[fn:3] [[file:Gen_12.org::v1][Gen 12]] - [[file:Gen_24.org::v1][24]]

[fn:4] [[file:Gen_25.org::v19][Gen 25,19]]-[[file:Gen_25.org::v26][26]].[[file:Gen_25.org::v27][27]]; [[file:Gen_32.org::v4][32,4]]; [[file:Gen_36.org::v1][36,1-8]]; [[file:Gen_46.org::v6][46,6]]

[fn:5] [[file:Ex_3.org::v1][Ex 3]] - [[file:Ex_15.org::v1][15]]

[fn:6] [[file:Ex_14.org::v1][Ex 14]]

[fn:7] [[file:Num_21.org::v25][Num 21,25]].[[file:Num_21.org::v31][31]]

[fn:8] (9-10) [[file:Num_22.org::v1][Num 22]]-[[file:Num_24.org::v1][24]]; [[file:Ri_11.org::v25][Ri 11,25]]

[fn:9] Ich wollte keinen Fluch von Bileam hören, wörtlich: Ich
wollte nicht auf Bileam hören.

[fn:10] [[file:Jos_3.org::v16][3,16f]]; [[file:Jos_6.org::v1][6,1-11]]

[fn:11] [[file:Jos_10.org::v1][10,1f]]; [[file:Ex_23.org::v27][Ex 23,27f]]; [[file:Dtn_7.org::v20][Dtn 7,20]]

[fn:12] Der Zusatz passt besser zu V. 8.

[fn:13] [[file:Dtn_6.org::v10][Dtn 6,10f]]

[fn:14] [[file:Ex_20.org::v5][Ex 20,5]]

[fn:15] 25-28: Josua tritt als Bundesmittler auf. Sichem ist
ein altes Heiligtum, das bereits in der Patriarchenzeit eine Rolle
spielt.

[fn:16] [[file:Gen_35.org::v4][Gen 35,4]]; [[file:Ri_9.org::v6][Ri 9,6]]

[fn:17] [[file:Ri_2.org::v8][Ri 2,8f]]

[fn:18] [[file:Ri_2.org::v7][Ri 2,7]]

[fn:19] [[file:Gen_50.org::v25][Gen 50,25]]; [[file:Gen_33.org::v19][Gen 33,19]]

[fn:20] [[file:Dtn_10.org::v6][Dtn 10,6]]
