#+TITLE: Jos 13 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-02 Do 22:14]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Jos 13.html

<<verses>>

<<v1>>
* Die Verteilung des Landes: 13,1 - 22,34

* Das Land im Westen: 13,1-14

1 Als Josua alt und hochbetagt war, sagte der Herr zu ihm: Du bist alt
und hochbetagt, aber vom Land bleibt noch sehr viel in Besitz zu nehmen.

<<v2>>
2 Das ist das Land, das noch übrig ist: alle Bezirke der Philister und
das ganze Gebiet der Geschuriter

<<v3>>
3 vom Schihor-Fluss östlich von Ägypten bis zum Gebiet von Ekron im
Norden - es wird den Kanaanitern zugerechnet -, die fünf
Philisterfürsten von Gaza, Aschdod, Aschkelon, Gat und Ekron sowie die
Awiter [fn:1]

<<v4>>
4 im Süden, das ganze Land der Kanaaniter und Meara, das zu Sidon
gehört, bis nach Afek und bis zum Gebiet der Amoriter,

<<v5>>
5 ferner das Land der Gibliter und der ganze Libanon im Osten, von
Baal-Gad am Fuß des Hermongebirges bis nach Lebo-Hamat.

<<v6>>
6 Alle Bewohner des Berglandes vom Libanon bis nach Misrefot-Majim, alle
Sidonier werde ich selbst vor den Israeliten vertreiben. Du aber verlose
das Land unter Israel als Erbbesitz, wie ich es dir befohlen habe.

<<v7>>
7 Verteil nun dieses Land als Erbbesitz an die neun Stämme und den
halben Stamm Manasse.

<<v8>>
8 Die andere Hälfte des Stammes Manasse und mit ihm die Rubeniter und
Gaditer hatten ihren Erbbesitz schon erhalten; ihn hatte Mose ihnen
jenseits des Jordan im Osten gegeben, [wie ihn Mose, der Knecht des
Herrn, ihnen zugewiesen hatte], [fn:2] [fn:3]

<<v9>>
9 von Aroër am Rand des Arnontales und von der Stadt an, die mitten im
Tal liegt, also die ganze Ebene von Medeba bis Dibon,

<<v10>>
10 alle Städte des Amoriterkönigs Sihon, der in Heschbon herrschte, bis
zum Gebiet der Ammoniter,

<<v11>>
11 dazu Gilead und das Gebiet der Geschuriter und Maachatiter und das
ganze Hermongebirge und den ganzen Baschan bis nach Salcha,

<<v12>>
12 das ganze Reich des Og im Baschan, der in Aschtarot und Edreï
herrschte. Er war vom Rest der Rafaïter übrig geblieben. Mose hatte sie
geschlagen und vertrieben.

<<v13>>
13 Aber die Israeliten vertrieben die Geschuriter und die Maachatiter
nicht; so wohnen Geschuriter und Maachatiter bis zum heutigen Tag mitten
in Israel.

<<v14>>
14 Nur dem Stamm Levi gab Josua keinen Erbbesitz; der Herr, der Gott
Israels, ist sein Erbteil, wie der Herr ihm gesagt hatte. [fn:4] [fn:5]\\
\\

<<v15>>
* Die Verteilung des Ostjordanlandes: 13,15-33

15 Die Zuteilung an den Stamm der Rubeniter hatte also Mose entsprechend
ihren Sippen vorgenommen. [fn:6]

<<v16>>
16 Ihnen war zuteil geworden das Gebiet von Aroër am Rand des Arnontales
und von der Stadt an, die mitten im Tal liegt: die ganze Ebene bei
Medeba,

<<v17>>
17 Heschbon und alle seine Städte in der Ebene, Dibon, Bamot-Baal und
Bet-Baal-Meon,

<<v18>>
18 Jahaz, Kedemot und Mefaat,

<<v19>>
19 Kirjatajim, Sibma und Zeret-Schahar auf dem Berg im Tal,

<<v20>>
20 Bet-Pegor, die Abhänge des Pisga, Bet-Jeschimot

<<v21>>
21 und alle Städte der Ebene, das heißt: das ganze Reich des
Amoriterkönigs Sihon, der in Heschbon herrschte. Mose hatte ihn und die
Fürsten Midians geschlagen: Ewi, Rekem, Zur, Hur und Reba, die
Heerführer Sihons, die im Land wohnten.

<<v22>>
22 Auch den Wahrsager Bileam, den Sohn Beors, hatten die Israeliten
zusammen mit den anderen mit dem Schwert erschlagen. [fn:7]

<<v23>>
23 Die Grenze der Rubeniter bildete der Jordan und sein Ufergebiet.
Dieses Gebiet mit seinen Städten und Gehöften ist der Erbbesitz der
Rubeniter, entsprechend ihren Sippen.

<<v24>>
24 Mose hatte auch die Zuteilung an den Stamm Gad, die Gaditer,
entsprechend ihren Sippen vorgenommen.

<<v25>>
25 Ihnen war zuteil geworden das Gebiet von Jaser und alle Städte
Gileads, das halbe Land der Ammoniter bis Aroër, das gegenüber Rabba
liegt,

<<v26>>
26 (das Land) von Heschbon bis Ramat-Mizpe und Betonim und von Mahanajim
bis zum Gebiet von Lo-Dabar,

<<v27>>
27 dazu im Tal Bet-Haram, Bet-Nimra, Sukkot und Zafon - der Rest des
Reiches Sihons, des Königs von Heschbon -, ferner der Jordan und das
Gebiet bis zum Ende des Sees von Kinneret jenseits des Jordan im Osten.

<<v28>>
28 Dieses Gebiet mit seinen Städten und Gehöften ist der Erbbesitz der
Gaditer, entsprechend ihren Sippen.

<<v29>>
29 Mose hatte auch die Zuteilung an den halben Stamm Manasse
vorgenommen, [dem halben Stamm Manasse wurde zuteil] entsprechend seinen
Sippen.

<<v30>>
30 Sein Gebiet umfasste von Mahanajim an den ganzen Baschan, das ganze
Reich des Königs Og vom Baschan und alle Zeltdörfer Jaïrs im Baschan,
sechzig Städte.

<<v31>>
31 Die Hälfte von Gilead sowie Aschtarot und Edreï, die Königsstädte des
Og vom Baschan, fiel den Nachkommen Machirs, des Sohnes Manasses zu, und
zwar der Hälfte der Machiriter entsprechend ihren Sippen.

<<v32>>
32 Das sind die Gebiete, die Mose in den Steppen von Moab jenseits des
Jordan östlich von Jericho als Erbbesitz verteilt hatte.

<<v33>>
33 Dem Stamm Levi aber hatte Mose keinen Erbbesitz zugeteilt. Der Herr,
der Gott Israels, ist ihr Erbteil, wie er es ihnen gesagt hatte. [fn:8]\\
\\

* Footnotes

[fn:1] [[file:Ri_3.org::v3][Ri 3,3]]

[fn:2] [[v15][13,15-32]]

[fn:3] Der Anfang des Verses «Die andere Hälfte des Stammes
Manasse» ist sinngemäß ergänzt.

[fn:4] [[v33][13,33]]; [[file:Jos_18.org::v7][18,7]]; [[file:Num_18.org::v20][Num 18,20f]]; [[file:Dtn_18.org::v1][Dtn 18,1]]

[fn:5] H liest nach Dtn 18,1, aber im Gegensatz zu Jos 13,33:
die Feueropfer des Herrn, des Gottes Israels, sind sein Erbteil.

[fn:6] (15-32) [[file:Num_32.org::v1][Num 32,1-42]]

[fn:7] [[file:Num_22.org::v5][Num 22,5]]; [[file:Num_31.org::v8][31,8]]

[fn:8] [[v14][13,14]]; [[file:Jos_18.org::v7][18,7]]
