#+TITLE: Jos 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-01 Mi 23:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jos 2.html

<<verses>>

<<v1>>
* Die Kundschafter in Jericho: 2,1-24

1 Josua, der Sohn Nuns, schickte von Schittim heimlich zwei Kundschafter
aus und befahl ihnen: Geht, erkundet das Land, besonders die Stadt
Jericho! Sie brachen auf und kamen zu dem Haus einer Dirne namens Rahab;
dort wollten sie übernachten. [fn:1] [fn:2]

<<v2>>
2 Man meldete dem König von Jericho: Heute Nacht sind ein paar Männer
hierher gekommen, Israeliten, um das Land auszukundschaften.

<<v3>>
3 Da schickte der König von Jericho Boten zu Rahab und ließ ihr sagen:
Gib die Männer heraus, die bei dir in deinem Haus eingekehrt sind; denn
sie sind gekommen, um das ganze Land auszukundschaften.

<<v4>>
4 Da nahm die Frau die beiden Männer und versteckte sie. (Zu den Boten
aber) sagte sie: Ja, die Männer sind zu mir gekommen; doch ich wusste
nicht, woher sie waren.

<<v5>>
5 Als das Stadttor bei Einbruch der Dunkelheit geschlossen werden
sollte, sind die Männer weggegangen; ich weiß aber nicht, wohin sie
gegangen sind. Lauft ihnen schnell nach, dann könnt ihr sie noch
einholen.

<<v6>>
6 Sie hatte aber die Männer auf das flache Dach gebracht und unter den
Flachsstängeln versteckt, die auf dem Dach aufgeschichtet waren.

<<v7>>
7 Inzwischen hatte man die Verfolgung der Männer aufgenommen, und zwar
in Richtung Jordan, zu den Furten hin. Und man hatte das Stadttor
geschlossen, nachdem die Verfolger hinausgegangen waren.

<<v8>>
8 Bevor die Männer sich niederlegten, stieg Rahab zu ihnen auf das Dach
hinauf

<<v9>>
9 und sagte zu ihnen: Ich weiß, dass der Herr euch das Land gegeben hat
und dass uns Furcht vor euch befallen hat und alle Bewohner des Landes
aus Angst vor euch vergehen.

<<v10>>
10 Denn wir haben gehört, wie der Herr das Wasser des Schilfmeers
euretwegen austrocknen ließ, als ihr aus Ägypten ausgezogen seid. Wir
haben auch gehört, was ihr mit Sihon und Og, den beiden Königen der
Amoriter jenseits des Jordan, gemacht habt: Ihr habt sie dem Untergang
geweiht. [fn:3] [fn:4]

<<v11>>
11 Als wir das hörten, zerschmolz unser Herz und jedem stockte
euretwegen der Atem; denn der Herr, euer Gott, ist Gott droben im Himmel
und hier unten auf der Erde.

<<v12>>
12 Nun schwört mir beim Herrn, dass ihr der Familie meines Vaters euer
Wohlwollen erweist, wie ich es euch erwiesen habe, und gebt mir ein
sicheres Zeichen dafür, [fn:5]

<<v13>>
13 dass ihr meinen Vater und meine Mutter, meine Brüder und meine
Schwestern und alles, was ihnen gehört, am Leben lasst und dass ihr uns
vor dem Tod bewahrt.

<<v14>>
14 Die Männer antworteten ihr: Wir bürgen mit unserem Leben für euch,
wenn ihr nur unsere Sache nicht verratet. Wenn uns der Herr das Land
gibt, werden wir dir unser Wohlwollen und unsere Treue zeigen. [fn:6]

<<v15>>
15 Darauf ließ die Frau sie mit einem Seil durch das Fenster die
Stadtmauer hinab; das Haus, in dem sie wohnte, war nämlich in die
Stadtmauer eingebaut.

<<v16>>
16 Sie riet ihnen: Geht ins Gebirge, damit die Verfolger euch nicht
finden; dort haltet euch drei Tage lang verborgen, bis die Verfolger
zurückgekehrt sind; dann könnt ihr eures Weges gehen.

<<v17>>
17 Die Männer sagten zu ihr: Wir können uns nur unter folgender
Bedingung an den Eid halten, den du uns hast schwören lassen:

<<v18>>
18 Wenn wir in das Land eindringen, musst du diese geflochtene
purpurrote Schnur an das Fenster binden, durch das du uns herabgelassen
hast, und du musst deinen Vater, deine Mutter, deine Brüder und die
ganze Familie deines Vaters bei dir in deinem Haus versammeln.

<<v19>>
19 Jeder aber, der aus der Tür deines Hauses heraustritt, ist selbst
schuld, wenn sein Blut vergossen wird. Wir sind dann ohne Schuld. Doch
bei jedem, der mit dir in deinem Haus bleibt, tragen wir die Schuld,
wenn Hand an ihn gelegt wird. [fn:7]

<<v20>>
20 Auch wenn du unsere Sache verrätst, brauchen wir uns nicht an den Eid
zu halten, den du uns hast schwören lassen.

<<v21>>
21 Sie antwortete: Es sei, wie ihr gesagt habt. Dann ließ sie die beiden
gehen und band die purpurrote Schnur an das Fenster.

<<v22>>
22 Die Männer gingen also und kamen ins Gebirge; dort blieben sie drei
Tage, bis die Verfolger (in die Stadt) zurückgekehrt waren. Die
Verfolger hatten sie überall gesucht, aber nicht gefunden.

<<v23>>
23 Dann machten sich die beiden Männer auf den Rückweg. Sie stiegen vom
Gebirge herab, überschritten den Jordan und kamen zu Josua, dem Sohn
Nuns. Sie erzählten ihm alles, was sie erfahren hatten,

<<v24>>
24 und sagten: Der Herr hat uns das ganze Land ausgeliefert; alle
Bewohner des Landes vergehen aus Angst vor uns.\\
\\

* Footnotes

[fn:1] [[file:Jos_6.org::v22][6,22]]

[fn:2] Schittim lag am Ostrand der Jordansenke, Jericho
gegenüber. Das Haus der Rahab scheint eine an der Stadtmauer gelegene
(V. 15) Herberge zu sein. Rahab, im Stammbaum Jesu [[file:~/RoamNotes/notes/Bibel/nt/Mt_1.org::v5][Mt 1,5]] als Mutter des
Boas genannt, wird [[file:~/RoamNotes/notes/Bibel/nt/Hebr_11.org::v31][Hebr 11,31]] wegen ihres Glaubens, [[file:~/RoamNotes/notes/Bibel/nt/Jak_2.org::v25][Jak 2,25]] wegen ihrer
guten Werke gerühmt.

[fn:3] [[file:Ex_14.org::v21][Ex 14,21]]; [[file:Num_21.org::v21][Num 21,21-26]]

[fn:4] Dem Untergang weihen: eine alte Kriegssitte, die auf
Gottes Befehl bei der Eroberung des Landes anzuwenden war (vgl. [[file:Jos_6.org::v18][6,18-24]];
[[file:Jos_10.org::v22][10,22-27]] und die Anmerkung zu [[file:Dtn_2.org::v34][Dtn 2,34]]).

[fn:5] [[file:Jos_6.org::v25][6,25]]

[fn:6] [[file:Jos_6.org::v22][6,22]]

[fn:7] ist selbst schuld, wenn sein Blut vergossen wird:
wörtlich: sein Blut ist auf seinem Haupt.
