#+TITLE: Jos 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-03 Fr 12:09]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jos 21.html


<<verses>>

<<v1>>
* Die Städte für die Leviten: 21,1-42

1 Die Familienoberhäupter der Leviten kamen in Schilo im Land Kanaan zu
dem Priester Eleasar, zu Josua, dem Sohn Nuns, und zu den
Stammeshäuptern der Israeliten [fn:1]

<<v2>>
2 und sagten zu ihnen: Der Herr hat durch Mose befohlen, uns Städte zum
Wohnen und ihre Weideflächen für unser Vieh zu geben.

<<v3>>
3 Da gaben die Israeliten den Leviten nach der Anordnung des Herrn aus
ihrem Erbbesitz die folgenden Städte mit ihren Weideflächen.

<<v4>>
4 Als das Los auf die Sippen der Kehatiter fiel, erhielten unter den
Leviten die Nachkommen des Priesters Aaron durch das Los dreizehn Städte
vom Stamm Juda, vom Stamm der Simeoniter und vom Stamm Benjamin.

<<v5>>
5 Die übrigen Kehatiter erhielten, entsprechend ihren Sippen, durch das
Los zehn Städte vom Stamm Efraim, vom Stamm Dan und vom halben Stamm
Manasse. [fn:2]

<<v6>>
6 Die Nachkommen Gerschons erhielten, entsprechend ihren Sippen, durch
das Los dreizehn Städte vom Stamm Issachar, vom Stamm Ascher, vom Stamm
Naftali und vom halben Stamm Manasse im Baschan.

<<v7>>
7 Die Nachkommen Meraris erhielten, entsprechend ihren Sippen, zwölf
Städte vom Stamm Ruben, vom Stamm Gad und vom Stamm Sebulon.

<<v8>>
8 Diese Städte mit ihren Weideflächen gaben die Israeliten durch das Los
den Leviten, wie es der Herr durch Mose befohlen hatte.

<<v9>>
9 Vom Stamm der Judäer und vom Stamm der Simeoniter gaben sie ihnen die
folgenden, namentlich genannten Städte. [fn:3]

<<v10>>
10 Sie wurden den Nachkommen Aarons unter den Kehatitern, unter den
Leviten, zuteil; denn auf sie fiel das erste Los.

<<v11>>
11 Ihnen gab man die Stadt des Arba, des Vaters Anaks, also Hebron, im
Gebirge Juda, mit seinen Weideflächen ringsum.

<<v12>>
12 Das Ackerland der Stadt aber und die dazugehörenden Gehöfte hatte man
Kaleb, dem Sohn Jefunnes, als Besitz gegeben. [fn:4]

<<v13>>
13 Den Nachkommen des Priesters Aaron gab man also die Asylstadt für
solche, die einen Menschen erschlagen haben, Hebron mit seinen
Weideflächen, ferner Libna mit seinen Weideflächen,

<<v14>>
14 Jattir mit seinen Weideflächen, Eschtemoa mit seinen Weideflächen,

<<v15>>
15 Holon mit seinen Weideflächen, Debir mit seinen Weideflächen,

<<v16>>
16 Ajin mit seinen Weideflächen, Jutta mit seinen Weideflächen und
Bet-Schemesch mit seinen Weideflächen: neun Städte von den zwei Stämmen
(den Judäern und den Simeonitern).

<<v17>>
17 Vom Stamm Benjamin (gab man ihnen) Gibeon mit seinen Weideflächen,
Geba mit seinen Weideflächen,

<<v18>>
18 Anatot mit seinen Weideflächen und Alemet mit seinen Weideflächen:
vier Städte.

<<v19>>
19 Im Ganzen erhielten die Nachkommen Aarons, die Priester waren,
dreizehn Städte mit ihren Weideflächen.

<<v20>>
20 Die Sippen der levitischen Kehatiter, die von den Nachkommen Kehats
außerdem noch vorhanden waren, erhielten die Städte ihres Anteils vom
Stamm Efraim.

<<v21>>
21 Man gab ihnen die Asylstädte für solche, die einen Menschen
erschlagen haben, Sichem mit seinen Weideflächen im Gebirge Efraim,
ferner Geser mit seinen Weideflächen,

<<v22>>
22 Kibzajim mit seinen Weideflächen und Bet-Horon mit seinen
Weideflächen: vier Städte;

<<v23>>
23 vom Stamm Dan erhielten sie Elteke mit seinen Weideflächen, Gibbeton
mit seinen Weideflächen,

<<v24>>
24 Ajalon mit seinen Weideflächen und Gat-Rimmon mit seinen
Weideflächen: vier Städte;

<<v25>>
25 vom halben Stamm Manasse erhielten sie Taanach mit seinen
Weideflächen und Gat-Rimmon mit seinen Weideflächen: zwei Städte.

<<v26>>
26 Im Ganzen erhielten die Sippen der übrigen Nachkommen Kehats zehn
Städte.

<<v27>>
27 Den Gerschonitern aus den levitischen Sippen gab man vom halben Stamm
Manasse die Asylstadt für solche, die einen Menschen erschlagen haben,
Golan im Baschan mit seinen Weideflächen sowie Aschtarot mit seinen
Weideflächen: zwei Städte;

<<v28>>
28 vom Stamm Issachar erhielten sie Kischjon mit seinen Weideflächen,
Daberat mit seinen Weideflächen,

<<v29>>
29 Jarmut mit seinen Weideflächen und En-Gannim mit seinen Weideflächen:
vier Städte;

<<v30>>
30 vom Stamm Ascher erhielten sie Mischal mit seinen Weideflächen, Abdon
mit seinen Weideflächen,

<<v31>>
31 Helkat mit seinen Weideflächen und Rehob mit seinen Weideflächen:
vier Städte;

<<v32>>
32 vom Stamm Naftali erhielten sie die Asylstadt für solche, die einen
Menschen erschlagen haben, Kedesch in Galiläa mit seinen Weideflächen
sowie Hammot-Dor mit seinen Weideflächen und Kartan mit seinen
Weideflächen: drei Städte.

<<v33>>
33 Im Ganzen erhielten die Gerschoniter, entsprechend ihren Sippen,
dreizehn Städte mit ihren Weideflächen.

<<v34>>
34 Den übrigen Leviten, also den Sippen der Nachkommen Meraris, gab man
vom Stamm Sebulon Jokneam mit seinen Weideflächen, Karta mit seinen
Weideflächen,

<<v35>>
35 Dimna mit seinen Weideflächen und Nahalal mit seinen Weideflächen:
vier Städte;

<<v36>>
36 dazu vom Stamm Ruben Bezer mit seinen Weideflächen, Jahaz mit seinen
Weideflächen,

<<v37>>
37 Kedemot mit seinen Weideflächen und Mefaat mit seinen Weideflächen:
vier Städte;

<<v38>>
38 vom Stamm Gad erhielten sie die Asylstadt für solche, die einen
Menschen erschlagen haben, Ramot-Gilead mit seinen Weideflächen, ferner
Mahanajim mit seinen Weideflächen,

<<v39>>
39 Heschbon mit seinen Weideflächen und Jaser mit seinen Weideflächen:
zusammen vier Städte.

<<v40>>
40 Im Ganzen erhielten die Merariter entsprechend ihren Sippen, die
unter den Sippen der Leviten noch übrig waren, als ihren Anteil zwölf
Städte.

<<v41>>
41 Die Gesamtanzahl der Levitenstädte mitten im Besitz der Israeliten
betrug achtundvierzig, mit ihren Weideflächen.

<<v42>>
42 Diese Städte bestanden jeweils aus der Stadt und den Weideflächen in
ihrer Umgebung; so war es bei allen diesen Städten.\\
\\

<<v43>>
* Die Ruhe in der neu gewonnenen Heimat: 21,43 - 22,9

43 So gab der Herr Israel das ganze Land, das er ihren Vätern mit einem
Eid zugesichert hatte. Sie nahmen es in Besitz und wohnten darin.

<<v44>>
44 Und der Herr verschaffte ihnen Ruhe ringsum, genau so, wie er es
ihren Vätern mit einem Eid zugesichert hatte. Keiner von all ihren
Feinden konnte ihnen Widerstand leisten; alle ihre Feinde gab der Herr
in ihre Gewalt.

<<v45>>
45 Keine von all den Zusagen, die der Herr dem Haus Israel gegeben
hatte, war ausgeblieben; jede war in Erfüllung gegangen. [fn:5]

* Footnotes

[fn:1] (1-3) [[file:Jos_14.org::v4][14,4]]; [[file:Num_35.org::v1][Num 35,1-8]]

[fn:2] 5f: entsprechend ihren Sippen, vom Stamm: Text korr.
nach V. 7; H: von den Sippen des Stammes.

[fn:3] 9-40: Die in [[file:Jos_20.org::v7][20,7-9]] genannten Asylstädte sind auch
Levitenstädte; darin besitzen die Leviten Wohn- und Weiderechte.

[fn:4] [[file:Jos_15.org::v13][15,13]]

[fn:5] war ausgeblieben, wörtlich: war dahingefallen (vgl. [[file:Jos_23.org::v14][23,14]]).
