#+TITLE: Jos 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-01 Mi 23:53]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jos 5.html

* Jos 5

<<verses>>

<<v1>>
1 Alle Könige der Amoriter jenseits des Jordan im Westen und alle Könige
der Kanaaniter am Meer hörten, dass der Herr das Wasser des Jordan vor
den Augen der Israeliten austrocknen ließ, bis sie hinübergezogen waren;
da zerschmolz ihr Herz und jedem stockte der Atem wegen der
Israeliten.\\
\\

<<v2>>
* Die Beschneidung in Gilgal: 5,2-12

2 Damals sagte der Herr zu Josua: Mach dir Steinmesser und ordne wieder
eine Beschneidung der Israeliten an, eine zweite! [fn:1] [fn:2]

<<v3>>
3 Da machte sich Josua Steinmesser und er beschnitt die Israeliten auf
dem «Hügel der Vorhäute».

<<v4>>
4 Josua nahm die Beschneidung vor, weil das ganze Volk, das aus Ägypten
ausgezogen war, das heißt die Männer, alle Krieger, nach ihrem Auszug
aus Ägypten auf dem Weg durch die Wüste gestorben waren.

<<v5>>
5 Als das Volk auszog, waren alle beschnitten. Alle aber, die nach dem
Auszug aus Ägypten unterwegs in der Wüste geboren wurden, hatte man
nicht beschnitten.

<<v6>>
6 Denn vierzig Jahre lang wanderten die Israeliten durch die Wüste.
Schließlich war das ganze Volk, alle Krieger, die aus Ägypten ausgezogen
waren, umgekommen, weil sie nicht auf die Stimme des Herrn gehört
hatten. Der Herr hatte ihnen geschworen, er werde sie das Land nicht
schauen lassen, das er ihren Vätern mit einem Eid zugesichert hatte, ein
Land, in dem Milch und Honig fließen. [fn:3]

<<v7>>
7 Ihre Söhne, die der Herr an ihre Stelle treten ließ, beschnitt Josua;
denn sie waren noch unbeschnitten, da man sie unterwegs nicht
beschnitten hatte.

<<v8>>
8 Als nun das ganze Volk beschnitten war, blieb man an Ort und Stelle,
im Lager, bis die Männer wieder gesund waren.

<<v9>>
9 Und der Herr sagte zu Josua: Heute habe ich die ägyptische Schande von
euch abgewälzt. Darum nennt man diesen Ort bis zum heutigen Tag Gilgal
(Wälzplatz). [fn:4]

<<v10>>
10 Als die Israeliten in Gilgal ihr Lager hatten, feierten sie am Abend
des vierzehnten Tages jenes Monats in den Steppen von Jericho das
Pascha.

<<v11>>
11 Am Tag nach dem Pascha, genau an diesem Tag, aßen sie ungesäuerte
Brote und geröstetes Getreide aus den Erträgen des Landes. [fn:5] [fn:6]

<<v12>>
12 Vom folgenden Tag an, nachdem sie von den Erträgen des Landes
gegessen hatten, blieb das Manna aus; von da an hatten die Israeliten
kein Manna mehr, denn sie aßen in jenem Jahr von der Ernte des Landes
Kanaan. [fn:7]\\
\\

<<v13>>
* Der Anführer des Heeres des Herrn: 5,13-15

13 Als Josua bei Jericho war und Ausschau hielt, sah er plötzlich einen
Mann mit einem gezückten Schwert in der Hand vor sich stehen. Josua ging
auf ihn zu und fragte ihn: Gehörst du zu uns oder zu unseren Feinden?

<<v14>>
14 Er antwortete: Nein, ich bin der Anführer des Heeres des Herrn. Ich
bin soeben gekommen. Da warf sich Josua vor ihm zu Boden, um ihm zu
huldigen, und fragte ihn: Was befiehlt mein Herr seinem Knecht?

<<v15>>
15 Der Anführer des Heeres des Herrn antwortete Josua: Zieh deine Schuhe
aus; denn der Ort, wo du stehst, ist heilig. Und Josua tat es. [fn:8]\\
\\

* Footnotes

[fn:1] [[file:Gen_17.org::v10][Gen 17,10-14]]

[fn:2] Eine frühere Beschneidung ist hier vorausgesetzt, sie
wird aber in den bekannten Texten nicht erwähnt.

[fn:3] [[file:Num_14.org::v22][Num 14,22f]]

[fn:4] Der Name Gilgal bedeutet wohl «Steinkreis» (vgl. [[file:Jos_4.org::v19][4,19f]]);
er wird hier von galal (wälzen) abgeleitet.

[fn:5] [[file:Lev_23.org::v10][Lev 23,10.14]]

[fn:6] 11f: Ungesäuerte Brote gehören nach [[file:Ex_20.org::v18][Ex 12,18]] zum
Paschamahl; soeben gereiftes, wohl mit den Ähren geröstetes Getreide
(vgl. [[file:Lev_2.org::v14][Lev 2,14]]) ist die Erstlingsfrucht des Landes. Das Aufhören des
Manna bezeichnet das Ende der Wüstenwanderung.

[fn:7] [[file:Ex_16.org::v35][Ex 16,35]]

[fn:8] [[file:Ex_3.org::v5][Ex 3,5]] 
