#+TITLE: Jos 16 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-03 Fr 11:39]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Jos 16.html


<<verses>>

<<v1>>
* Das Gebiet der Nachkommen Josefs: 16,1 - 17,18

1 Das war der Anteil, der den Nachkommen Josefs durch das Los zufiel:
(Seine Grenze verläuft) vom Jordan bei Jericho zu den Quellen von
Jericho im Osten, dann von Jericho aus in die Wüste aufsteigend und ins
Gebirge von Bet-El.

<<v2>>
2 Von Bet-El geht sie nach Lus hinaus und hinüber zum Gebiet der Arkiter
nach Atarot.

<<v3>>
3 Dann führt sie westwärts hinab zum Gebiet der Jafletiter bis zum
Gebiet von Unter-Bet-Horon und Geser und läuft am Meer aus.

<<v4>>
4 Erbbesitz erhielten auch die Söhne Josefs, Manasse und Efraim.

<<v5>>
5 Dies war das Gebiet der Efraimiter, entsprechend ihren Sippen: Die
Grenze ihres Erbbesitzes [im Osten] verläuft von Atarot-Adar bis
Ober-Bet-Horon

<<v6>>
6 und läuft zum Meer. Von Michmetat im Norden wendet sich die Grenze
ostwärts nach Taanat-Schilo und geht ostwärts daran vorbei nach Janoach.

<<v7>>
7 Von Janoach führt sie hinab nach Atarot und Naara, berührt Jericho und
läuft am Jordan aus.

<<v8>>
8 Von Tappuach geht die Grenze westwärts zum Bach Kana und läuft am Meer
aus. Das ist der Erbbesitz des Stammes der Efraimiter, entsprechend
ihren Sippen;

<<v9>>
9 ferner (gehören) den Efraimitern vereinzelte Städte mitten im
Erbbesitz der Manassiter, und zwar die Städte samt den dazugehörenden
Gehöften.

<<v10>>
10 Die Efraimiter konnten aber die Kanaaniter, die in Geser wohnten,
nicht vertreiben. So wohnen die Kanaaniter bis zum heutigen Tag mitten
in Efraim; sie wurden aber zu Fronknechten gemacht.
