#+TITLE: Jos 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-03 Fr 10:49]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Jos 15.html

<<verses>>

<<v1>>
* Das Gebiet des Stammes Juda: 15,1-63

1 An den Stamm der Judäer fiel durch das Los, entsprechend seinen
Sippen, der Anteil gegen die Grenze Edoms hin, südwärts der Wüste Zin zu
gelegen, die im äußersten Süden ist.

<<v2>>
2 Die Südgrenze Judas beginnt am Ende des Salzmeeres, an der
(Meeres)zunge, die sich nach Süden erstreckt,

<<v3>>
3 verläuft dann südlich zur Skorpionen-Steige, zieht sich hinüber nach
Zin, steigt südlich von Kadesch-Barnea hinauf, führt hinüber nach
Hezron, steigt hinauf nach Addar und wendet sich nach Karka;

<<v4>>
4 dann führt sie hinüber nach Azmon, geht hinaus zum Grenzbach Ägyptens
und läuft am Meer aus. Das ist die Südgrenze des Stammes Juda. [fn:1]

<<v5>>
5 Die Ostgrenze bildet das Salzmeer bis zur Jordanmündung. Für die
Nordseite beginnt die Grenze an der Meereszunge bei der Jordanmündung.

<<v6>>
6 Die Grenze geht dann nach Bet-Hogla hinauf und läuft nördlich an
Bet-Araba vorbei. Dann zieht sie sich hinauf zum Stein Bohans, des
Sohnes Rubens.

<<v7>>
7 Vom Achortal steigt sie empor nach Debir und wendet sich nordwärts
nach Gelilot gegenüber der Steige von Adummim, die südlich des Bachtals
liegt; dann führt sie hinüber zum Wasser von En-Schemesch und läuft
hinaus zur Rogel-Quelle. [fn:2]

<<v8>>
8 Von da an steigt die Grenze hinauf in das Ben-Hinnom-Tal südlich des
Bergrückens der Jebusiter - das ist Jerusalem - und weiter empor zum
Gipfel des Berges, der westlich des Hinnom-Tals am nördlichen Rand der
Rafaïter-Ebene liegt.

<<v9>>
9 Vom Gipfel des Berges biegt die Grenze ab zur Neftoach-Quelle und
führt hinaus zum Berg Efron. Dann biegt sie ab nach Baala, das ist
Kirjat-Jearim. [fn:3]

<<v10>>
10 Von Baala wendet sich die Grenze nach Westen zum Berg Seïr, führt
dann an der Nordflanke des Berges von Jearim, das ist Kesalon, vorbei,
hinab nach Bet-Schemesch und hinüber nach Timna.

<<v11>>
11 Dann verläuft sie hinaus zur Nordflanke von Ekron, biegt ab nach
Schikkaron, geht hinüber zum Berg Baala und hinaus nach Jabneel. Die
Grenze läuft aus am Meer.

<<v12>>
12 Das große Meer und das Küstengebiet bilden die Westgrenze. Das ist
das Gebiet der Judäer ringsum, entsprechend ihren Sippen.

<<v13>>
13 Kaleb aber, dem Sohn Jefunnes, gab Josua einen Anteil mitten unter
den Judäern, nach der Anweisung des Herrn an Josua (und zwar)
Kirjat-Arba - Arba war der Vater Anaks -, das heißt Hebron. [fn:4]

<<v14>>
14 Kaleb vertrieb von dort die drei Anakiter Scheschai, Ahiman und
Talmai, die Söhne Anaks.

<<v15>>
15 Von dort zog er hinauf zu den Einwohnern von Debir. Debir hieß früher
Kirjat-Sefer.

<<v16>>
16 Und Kaleb sagte: Wer Kirjat-Sefer besiegt und einnimmt, dem gebe ich
meine Tochter Achsa zur Frau.

<<v17>>
17 Otniël, der Sohn des Kenas, eines Bruders Kalebs, nahm die Stadt ein
und Kaleb gab ihm seine Tochter Achsa zur Frau. [fn:5]

<<v18>>
18 Als sie bei Otniël ankam, drängte er sie, von ihrem Vater ein Stück
Land zu verlangen. Da ließ sie sich vom Esel herabgleiten und Kaleb
fragte sie: Was hast du? [fn:6]

<<v19>>
19 Sie antwortete: Gib mir ein Geschenk als Zeichen des Segens! Wenn du
mich schon ins Trockenland schickst, dann gib mir auch Wasserstellen! Da
gab er ihr die obere und die untere Wasserquelle. [fn:7]

<<v20>>
20 Das ist der Erbbesitz des Stammes der Judäer, entsprechend ihren
Sippen: [fn:8]

<<v21>>
21 Die Städte im Bereich des Stammes der Judäer waren folgende: an der
Grenze zu Edom im Negeb: Kabzeel, Eder, Jagur,

<<v22>>
22 Kina, Dimona, Adada,

<<v23>>
23 Kadesch, Hazor, Jitna,

<<v24>>
24 Sif, Telem, Bealot,

<<v25>>
25 Hazor-Hadatta, Kerijot-Hezron, das ist Hazor,

<<v26>>
26 Amam, Schema, Molada,

<<v27>>
27 Hazar-Gadda, Heschmon, Bet-Pelet,

<<v28>>
28 Hazar-Schual, Beerscheba und seine Tochterstädte, [fn:9]

<<v29>>
29 Baala, Ijim, Ezem,

<<v30>>
30 Eltolad, Kesil, Horma,

<<v31>>
31 Ziklag, Madmanna, Sansanna,

<<v32>>
32 Lebaot, Schilhim und En-Rimmon: im ganzen neunundzwanzig Städte mit
den dazugehörenden Gehöften; [fn:10]

<<v33>>
33 in der Schefela: Eschtaol, Zora, Aschna,

<<v34>>
34 Sanoach, En-Gannim, Tappuach, Enajim,

<<v35>>
35 Jarmut, Adullam, Socho, Aseka,

<<v36>>
36 Schaarajim, Aditajim, Gedera und Gederotajim: vierzehn Städte mit den
dazugehörenden Gehöften;

<<v37>>
37 Zenan, Hadascha, Migdal-Gad,

<<v38>>
38 Dilan, Mizpe, Jokteel,

<<v39>>
39 Lachisch, Bozkat, Eglon,

<<v40>>
40 Kabbon, Lachmas, Kitlisch,

<<v41>>
41 Gederot, Bet-Dagon, Naama und Makkeda: sechzehn Städte mit den
dazugehörenden Gehöften;

<<v42>>
42 Libna, Eter, Aschan,

<<v43>>
43 Jiftach, Aschna, Nezib,

<<v44>>
44 Keïla, Achsib und Marescha: neun Städte mit den dazugehörenden
Gehöften;

<<v45>>
45 Ekron mit den dazugehörenden Tochterstädten und Gehöften,

<<v46>>
46 von Ekron bis zum Meer alles, was auf der Seite von Aschdod liegt,
samt den dazugehörenden Gehöften;

<<v47>>
47 Aschdod mit den dazugehörenden Tochterstädten und Gehöften, Gaza mit
den dazugehörenden Tochterstädten und Gehöften bis zum Grenzbach
Ägyptens und zum großen Meer mit dem Küstengebiet;

<<v48>>
48 auf dem Gebirge: Schamir, Jattir, Socho,

<<v49>>
49 Danna, Kirjat-Sanna, das ist Debir,

<<v50>>
50 Anab, Eschtemoa, Anim,

<<v51>>
51 Goschen, Holon und Gilo: elf Städte mit den dazugehörenden Gehöften;

<<v52>>
52 Arab, Duma, Eschan,

<<v53>>
53 Janum, Bet-Tappuach, Afeka,

<<v54>>
54 Humta, Kirjat-Arba, das ist Hebron, und Zior: neun Städte und die
dazugehörenden Gehöfte;

<<v55>>
55 Maon, Karmel, Sif, Jutta,

<<v56>>
56 Jesreel, Jokdeam, Sanoach,

<<v57>>
57 Kaim, Gibea und Timna: zehn Städte mit den dazugehörenden Gehöften;

<<v58>>
58 Halhul, Bet-Zur, Gedor,

<<v59>>
59 Maarat, Bet-Anot und Eltekon: sechs Städte mit den dazugehörenden
Gehöften; Tekoa, Efrata, das ist Betlehem, Pegor, Etam, Kulon, Tatam,
Schoresch, Kerem, Gallim, Bet-Ter und Manocho: elf Städte mit den
dazugehörenden Gehöften: [fn:11]

<<v60>>
60 Kirjat-Baal, das ist Kirjat-Jearim, und Rabba: zwei Städte mit den
dazugehörenden Gehöften;

<<v61>>
61 in der Steppe: Bet-Araba, Middin, Sechacha,

<<v62>>
62 Nibschan, Ir-Melach und En-Gedi: sechs Städte mit den dazugehörenden
Gehöften.

<<v63>>
63 Nur die Jebusiter, die in Jerusalem wohnten, konnten die Judäer nicht
vertreiben und so wohnen die Jebusiter bis zum heutigen Tag mit den
Judäern zusammen in Jerusalem.\\
\\

* Footnotes

[fn:1] des Stammes Juda: Text korr. nach G (wörtlich: für sie);
H: für euch.

[fn:2] nach Gelilot: Text korr. (vgl. 18,7); H: Gilgal.

[fn:3] zum Berg Efron: Text korr. nach G; H: zu den Städten des Berges Efron.

[fn:4] (13-19) [[file:Jos_14.org::v13][14,13-15]]; [[file:Ri_1.org::v10][Ri 1,10-15]]

[fn:5] [[file:Ri_3.org::v9][Ri 3,9]]

[fn:6] Übersetzung unsicher.

[fn:7] ein Geschenk als Zeichen des Segens, wörtlich: einen Segen.

[fn:8] 20-63: Die Aufstellung geht auf alte Ortslisten zurück,
in denen die Bezirke Judas umschrieben waren.

[fn:9] und seine Tochterstädte: Text korr., H ist verderbt, vgl. G.

[fn:10] En-Rimmon: Text korr. nach [[file:Neh_11.org::v29][Neh 11,29]] (vgl. [[file:Jos_19.org::v7][Jos 19,7]]).

[fn:11] Dieser Versteil ist nur in G erhalten.
