:PROPERTIES:
:ID:       df1cd6f1-bf8c-4549-a7e4-94f9361460ed
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Klagelieder* -- [[file:Klgl_1.html][1]]
[[file:Klgl_2.html][2]] [[file:Klgl_3.html][3]] *4*
[[file:Klgl_5.html][5]]

--------------

* Klgl 4
  :PROPERTIES:
  :CUSTOM_ID: klgl-4
  :END:

<<verses>>

<<v1>>
** Das vierte Lied: 4,1-22
   :PROPERTIES:
   :CUSTOM_ID: das-vierte-lied-41-22
   :END:
1 Weh, wie glanzlos ist das Gold, /\\
 gedunkelt das köstliche Feingold, hingeschüttet die heiligen Steine /\\
 an den Ecken aller Straßen.\\
\\

<<v2>>
2 Die edlen Kinder Zions, /\\
 einst aufgewogen mit reinem Gold, weh, wie Krüge aus Ton sind sie
geachtet, /\\
 wie Werk von Töpferhand.\\
\\

<<v3>>
3 Selbst Schakale reichen die Brust, /\\
 säugen ihre Jungen. Die Töchter meines Volkes sind grausam /\\
 wie Strauße in der Wüste. ^{[[#fn1][1]]}\\
\\

<<v4>>
4 Des Säuglings Zunge klebt /\\
 an seinem Gaumen vor Durst. Kinder betteln um Brot; /\\
 keiner bricht es ihnen.\\
\\

<<v5>>
5 Die einst Leckerbissen schmausten, /\\
 verschmachten auf den Straßen. Die einst auf Purpur lagen, /\\
 wälzen sich jetzt im Unrat.\\
\\

<<v6>>
6 Größer ist die Schuld der Tochter, meines Volkes, /\\
 als die Sünde Sodoms, das plötzlich vernichtet wurde, /\\
 ohne dass eine Hand sich rührte. ^{[[#fn2][2]]}\\
\\

<<v7>>
7 Ihre jungen Männer waren reiner als Schnee, /\\
 weißer als Milch, ihr Leib rosiger als Korallen, /\\
 saphirblau ihre Adern. ^{[[#fn3][3]]}\\
\\

<<v8>>
8 Schwärzer als Ruß sehen sie aus, /\\
 man erkennt sie nicht auf den Straßen. Die Haut schrumpft ihnen am
Leib, /\\
 trocken wie Holz ist sie geworden.\\
\\

<<v9>>
9 Besser die vom Schwert Getöteten /\\
 als die vom Hunger Getöteten; sie sind verschmachtet, /\\
 vom Missertrag der Felder getroffen. ^{[[#fn4][4]]}\\
\\

<<v10>>
10 Die Hände liebender Mütter /\\
 kochten die eigenen Kinder. Sie dienten ihnen als Speise /\\
 beim Zusammenbruch der Tochter, meines Volkes. ^{[[#fn5][5]]}\\
\\

<<v11>>
11 Randvoll gemacht hat der Herr seinen Grimm, /\\
 ausgegossen seinen glühenden Zorn. Er entfachte in Zion ein Feuer, /\\
 das bis auf den Grund alles verzehrte. ^{[[#fn6][6]]}\\
\\

<<v12>>
12 Kein König eines Landes, kein Mensch auf der Erde /\\
 hätte jemals geglaubt, dass ein Bedränger und Feind /\\
 durchschritte die Tore Jerusalems.\\
\\

<<v13>>
13 Wegen der Sünden ihrer Propheten, /\\
 wegen der Verfehlung ihrer Priester, die in ihrer Mitte vergossen haben
/\\
 das Blut von Gerechten,\\
\\

<<v14>>
14 wankten sie blind durch die Gassen, /\\
 besudelt mit Blut, sodass man nicht berühren mochte /\\
 ihre Kleider. ^{[[#fn7][7]]}\\
\\

<<v15>>
15 Fort, unrein!, rief man ihnen zu. /\\
 Fort, fort! Rührt mich nicht an! Da flohen sie, da wankten sie. /\\
 Unter den Völkern sagte man: /\\
 Sie durften nicht länger bleiben.\\
\\

<<v16>>
16 Der Herr selbst hat sie zerstreut, /\\
 schaut sie nicht mehr an. Keine Ehrfurcht zollte man den Priestern, /\\
 Greise fanden keine Gnade. ^{[[#fn8][8]]}\\
\\

<<v17>>
17 Als wir uns noch die Augen nach Hilfe ausschauten, /\\
 war es umsonst. Auf unserer Warte spähten wir nach einem Volk, /\\
 das dann doch keine Hilfe brachte. ^{[[#fn9][9]]}\\
\\

<<v18>>
18 Man horchte auf unsere Schritte, /\\
 wir konnten nicht auf die Straßen. Unser Ende war nah, die Tage voll,
/\\
 ja, unser Ende kam.\\
\\

<<v19>>
19 Schneller waren unsere Verfolger /\\
 als Adler am Himmel. Sie jagten uns auf den Bergen, /\\
 lauerten uns auf in der Wüste.\\
\\

<<v20>>
20 Unser Lebensatem, der Gesalbte des Herrn, /\\
 ist gefangen in ihren Gruben. Wir aber hatten gedacht: /\\
 In seinem Schatten werden wir leben unter den Völkern.
^{[[#fn10][10]][[#fn11][11]]}\\
\\

<<v21>>
21 Juble nur und freue dich, Tochter Edom, /\\
 die du wohnst im Lande Uz. Auch zu dir wird der Becher kommen, /\\
 du wirst dich betrinken und dich entblößen. ^{[[#fn12][12]]}\\
\\

<<v22>>
22 Zu Ende ist deine Schuld, Tochter Zion; /\\
 nicht wieder führt er dich in Verbannung. Deine Schuld bestraft er,
Tochter Edom, /\\
 deckt deine Sünden auf.\\
\\

^{[[#fnm1][1]]} 3c: Text korr. nach G; H: Die Tochter meines Volkes
ist . . .

^{[[#fnm2][2]]} ℘ Gen 19; Ez 16,48

^{[[#fnm3][3]]} 7a: Ihre jungen Männer: Text korr.; H: Ihre Nasiräer.

^{[[#fnm4][4]]} 9d: Text korr.; H: meiner Felder.

^{[[#fnm5][5]]} ℘ 2,20; Dtn 28,53-57; 2 Kön 6,29

^{[[#fnm6][6]]} ℘ Jer 7,20; Dtn 32,22

^{[[#fnm7][7]]} Gemeint sind die Einwohner Jerusalems.

^{[[#fnm8][8]]} 16a: Text korr.; H: Das Angesicht des Herrn.

^{[[#fnm9][9]]} Gemeint ist der unzuverlässige Bundesgenosse Ägypten.

^{[[#fnm10][10]]} ℘ 2 Kön 25,5f

^{[[#fnm11][11]]} 20a: Poetische Bezeichnung für König Zidkija.

^{[[#fnm12][12]]} ℘ Gen 36,28
