:PROPERTIES:
:ID:       72fc7dfb-3f1e-4202-b88d-2e0c2e634fa9
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Klagelieder* -- [[file:Klgl_1.html][1]] ...
[[file:Klgl_3.html][3]] [[file:Klgl_4.html][4]] *5*

--------------

* Klgl 5
  :PROPERTIES:
  :CUSTOM_ID: klgl-5
  :END:

<<verses>>

<<v1>>
** Das fünfte Lied: 5,1-22
   :PROPERTIES:
   :CUSTOM_ID: das-fünfte-lied-51-22
   :END:
1 Herr, denk daran, was uns geschehen, /\\
 blick her und sieh unsre Schmach!\\
\\

<<v2>>
2 An Ausländer fiel unser Erbe, /\\
 unsre Häuser kamen an Fremde.\\
\\

<<v3>>
3 Wir wurden Waisen, Kinder ohne Vater, /\\
 unsere Mütter wurden Witwen.\\
\\

<<v4>>
4 Unser Wasser trinken wir für Geld, /\\
 unser Holz müssen wir bezahlen.\\
\\

<<v5>>
5 Wir werden getrieben, das Joch auf dem Nacken, /\\
 wir sind müde, man versagt uns die Ruhe.\\
\\

<<v6>>
6 Nach Ägypten streckten wir die Hand, /\\
 nach Assur, um uns mit Brot zu sättigen. ^{[[#fn1][1]]}\\
\\

<<v7>>
7 Unsere Väter haben gesündigt; sie sind nicht mehr. /\\
 Wir müssen ihre Sünden tragen.\\
\\

<<v8>>
8 Sklaven herrschen über uns, /\\
 niemand entreißt uns ihren Händen.\\
\\

<<v9>>
9 Unter Lebensgefahr holen wir unser Brot, /\\
 bedroht vom Schwert der Wüste. ^{[[#fn2][2]]}\\
\\

<<v10>>
10 Unsere Haut glüht wie ein Ofen /\\
 von den Gluten des Hungers.\\
\\

<<v11>>
11 Frauen hat man in Zion geschändet, /\\
 Jungfrauen in den Städten von Juda.\\
\\

<<v12>>
12 Fürsten wurden von Feindeshand gehängt, /\\
 den Ältesten nahm man die Ehre.\\
\\

<<v13>>
13 Junge Männer mussten die Handmühlen schleppen, /\\
 unter der Holzlast brachen Knaben zusammen.\\
\\

<<v14>>
14 Die Alten blieben fern vom Tor, /\\
 die Jungen vom Saitenspiel.\\
\\

<<v15>>
15 Dahin ist unseres Herzens Freude, /\\
 in Trauer gewandelt unser Reigen. ^{[[#fn3][3]]}\\
\\

<<v16>>
16 Die Krone ist uns vom Haupt gefallen. /\\
 Weh uns, wir haben gesündigt.\\
\\

<<v17>>
17 Darum ist krank unser Herz, /\\
 darum sind trüb unsere Augen ^{[[#fn4][4]]}\\
\\

<<v18>>
18 über den Zionsberg, der verwüstet liegt; /\\
 Füchse laufen dort umher.\\
\\

<<v19>>
19 Du aber, Herr, bleibst ewig, /\\
 dein Thron von Geschlecht zu Geschlecht. ^{[[#fn5][5]]}\\
\\

<<v20>>
20 Warum willst du uns für immer vergessen, /\\
 uns verlassen fürs ganze Leben? ^{[[#fn6][6]]}\\
\\

<<v21>>
21 Kehre uns, Herr, dir zu, /\\
 dann können wir uns zu dir bekehren. /\\
 Erneuere unsere Tage, damit sie werden wie früher.\\
\\

<<v22>>
22 Oder hast du uns denn ganz verworfen, /\\
 zürnst du uns über alle Maßen?\\
\\

^{[[#fnm1][1]]} ℘ Hos 7,11

^{[[#fnm2][2]]} Mit dem «Schwert der Wüste» sind die feindlich gesinnten
Wüstenbewohner gemeint.

^{[[#fnm3][3]]} ℘ Ijob 30,31

^{[[#fnm4][4]]} ℘ Jer 8,18

^{[[#fnm5][5]]} ℘ Ps 9,8

^{[[#fnm6][6]]} ℘ Ps 13,2
