:PROPERTIES:
:ID:       28353686-81d2-4035-94fd-19b540b78bba
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Die Klagelieder* -- [[file:Klgl_1.html][1]] *2*
[[file:Klgl_3.html][3]] [[file:Klgl_4.html][4]] [[file:Klgl_5.html][5]]

--------------

* Klgl 2
  :PROPERTIES:
  :CUSTOM_ID: klgl-2
  :END:

<<verses>>

<<v1>>
** Das zweite Lied: 2,1-22
   :PROPERTIES:
   :CUSTOM_ID: das-zweite-lied-21-22
   :END:
1 Weh, mit seinem Zorn umwölkt /\\
 der Herr die Tochter Zion. Er schleudert vom Himmel zur Erde /\\
 die Pracht Israels. Nicht dachte er an den Schemel seiner Füße /\\
 am Tag seines Zornes. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Schonungslos hat der Herr vernichtet /\\
 alle Fluren Jakobs, niedergerissen in seinem Grimm /\\
 die Bollwerke der Tochter Juda, zu Boden gestreckt, entweiht /\\
 das Königtum und seine Fürsten.\\
\\

<<v3>>
3 Abgehauen hat er in Zornesglut /\\
 jedes Horn in Israel. Er zog seine Rechte zurück /\\
 angesichts des Feindes und brannte in Jakob wie flammendes Feuer, /\\
 ringsum alles verzehrend.\\
\\

<<v4>>
4 Er spannte den Bogen wie ein Feind, /\\
 stand da, erhoben die Rechte. Wie ein Gegner erschlug er alles, /\\
 was das Auge erfreut. Im Zelt der Tochter Zion /\\
 goss er seinen Zorn aus wie Feuer. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Wie ein Feind ist geworden der Herr, /\\
 Israel hat er vernichtet. Vernichtet hat er alle Paläste, /\\
 zerstört seine Burgen. Auf die Tochter Juda hat er gehäuft /\\
 Jammer über Jammer. ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Er zertrat wie einen Garten seine Wohnstatt, /\\
 zerstörte seinen Festort. Vergessen ließ der Herr auf Zion /\\
 Festtag und Sabbat. In glühendem Zorn verwarf er /\\
 König und Priester. ^{[[#fn4][4]]}\\
\\

<<v7>>
7 Seinen Altar hat der Herr verschmäht, /\\
 entweiht sein Heiligtum, überliefert in die Hand des Feindes /\\
 die Mauern von Zions Palästen. Man lärmte im Haus des Herrn /\\
 wie an einem Festtag\\
\\

<<v8>>
8 Zu schleifen plante der Herr /\\
 die Mauer der Tochter Zion. Er spannte die Messschnur und zog nicht
zurück /\\
 die Hand vom Vertilgen. Trauern ließ er Wall und Mauer; /\\
 miteinander sanken sie nieder. ^{[[#fn5][5]]}\\
\\

<<v9>>
9 In den Boden sanken ihre Tore, /\\
 ihre Riegel hat er zerstört und zerbrochen. Ihr König und ihre Fürsten
sind unter den Völkern, /\\
 keine Weisung ist da, auch keine Offenbarung /\\
 schenkt der Herr ihren Propheten. ^{[[#fn6][6]]}\\
\\

<<v10>>
10 Am Boden sitzen, verstummt, /\\
 die Ältesten der Tochter Zion, streuen sich Staub aufs Haupt, /\\
 legen Trauerkleider an. Zu Boden senken den Kopf /\\
 die Mädchen von Jerusalem.\\
\\

<<v11>>
11 Meine Augen ermatten vor Tränen, /\\
 mein Inneres glüht. Ausgeschüttet auf die Erde ist mein Herz /\\
 über den Zusammenbruch der Tochter, meines Volkes. Kind und Säugling
verschmachten /\\
 auf den Plätzen der Stadt.\\
\\

<<v12>>
12 Sie sagen zu ihren Müttern: /\\
 Wo ist Brot und Wein?, da sie erschöpft verschmachten /\\
 auf den Plätzen der Stadt, da sie ihr Leben aushauchen /\\
 auf dem Schoß ihrer Mütter.\\
\\

<<v13>>
13 Wie soll ich dir zureden, was dir gleichsetzen, /\\
 du Tochter Jerusalem? Womit kann ich dich vergleichen, wie dich
trösten, /\\
 Jungfrau, Tochter Zion? Dein Zusammenbruch ist groß wie das Meer, /\\
 wer kann dich heilen?\\
\\

<<v14>>
14 Deine Propheten schauten dir Lug und Trug. /\\
 Deine Schuld haben sie nicht aufgedeckt, /\\
 um dein Schicksal zu wenden. Sie schauten dir als Prophetenworte /\\
 nur Trug und Verführung. ^{[[#fn7][7]][[#fn8][8]]}\\
\\

<<v15>>
15 Über dich klatschen in die Hände /\\
 alle, die des Weges ziehen. Sie zischeln und schütteln den Kopf /\\
 über die Tochter Jerusalem: Ist das die Stadt, die man nannte: /\\
 Entzücken der ganzen Welt, /\\
 Krone der Schönheit? ^{[[#fn9][9]]}\\
\\

<<v16>>
16 Über dich reißen ihr Maul auf /\\
 all deine Feinde. Sie zischeln und fletschen die Zähne, /\\
 sie sprechen: Wir haben sie verschlungen. Das ist der Tag, auf den wir
hofften. /\\
 Wir haben ihn erreicht und gesehen. ^{[[#fn10][10]]}\\
\\

<<v17>>
17 Getan hat der Herr, was er geplant, /\\
 seinen Drohspruch vollzogen, /\\
 den er seit alters verkündet hat. Eingerissen hat er, nicht geschont.
/\\
 Den Feind ließ er über dich jubeln, /\\
 erhöhte die Macht deiner Gegner. ^{[[#fn11][11]][[#fn12][12]]}\\
\\

<<v18>>
18 Schrei laut zum Herrn, /\\
 stöhne, Tochter Zion! Wie einen Bach lass fließen die Tränen /\\
 Tag und Nacht! Niemals gewähre dir Ruhe, /\\
 nie lass dein Auge rasten! ^{[[#fn13][13]]}\\
\\

<<v19>>
19 Steh auf, klage bei Nacht, /\\
 zu jeder Nachtwache Anfang! Schütte aus wie Wasser dein Herz /\\
 vor dem Angesicht des Herrn! Erhebe zu ihm die Hände /\\
 für deiner Kinder Leben, die vor Hunger verschmachten /\\
 an den Ecken aller Straßen.\\
\\

<<v20>>
20 Herr, sieh doch und schau: /\\
 Wem hast du solches getan? Dürfen Frauen ihre Leibesfrucht essen, /\\
 ihre sorgsam gehegten Kinder? Darf man erschlagen im Heiligtum des
Herrn /\\
 Priester und Propheten? ^{[[#fn14][14]]}\\
\\

<<v21>>
21 Am Boden liegen in den Gassen /\\
 Kind und Greis. Die Mädchen und die jungen Männer /\\
 fielen unter dem Schwert. Du hast sie erschlagen am Tag deines Zorns,
/\\
 geschlachtet, ohne zu schonen.\\
\\

<<v22>>
22 Wie zum Festtag hast du gerufen, /\\
 die Schrecken ringsum. Am Zorntag des Herrn gab es keinen, /\\
 der entkam und entrann. Die ich hegte und großzog, /\\
 mein Feind hat sie vernichtet. ^{[[#fn15][15]]}\\
\\

^{[[#fnm1][1]]} 1e: Schemel seiner Füße: Gemeint ist der Tempel (vgl. 1
Chr 28,2).

^{[[#fnm2][2]]} ℘ Jer 21,5f

^{[[#fnm3][3]]} ℘ Jes 63,10

^{[[#fnm4][4]]} ℘ Am 5,21-23

^{[[#fnm5][5]]} ℘ Jes 34,11

^{[[#fnm6][6]]} ℘ Ps 74,9; Ez 7,26

^{[[#fnm7][7]]} ℘ Jer 14,14

^{[[#fnm8][8]]} 14a: Trug, wörtlich: Tünche (vgl. Ez 13,10).

^{[[#fnm9][9]]} ℘ Jer 18,16

^{[[#fnm10][10]]} ℘ Ps 35,21.25

^{[[#fnm11][11]]} ℘ Jer 40,3; Sach 1,6

^{[[#fnm12][12]]} die Macht, wörtlich: das Horn.

^{[[#fnm13][13]]} 18a: Text korr.; H: Ihr Herz ruft. 18b: stöhne,
Tochter Zion!: Text korr.; H: Mauer der Tochter Zion!

^{[[#fnm14][14]]} ℘ Dtn 28,53-57; 2 Kön 6,29

^{[[#fnm15][15]]} 22b: die Schrecken: Text korr.; H: meine Schrecken.
