#+TITLE: Koh 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-02-13 Do 12:35]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Koh 5.html

* Koh 5

<<verses>>

<<v1>>
1 Sei nicht zu schnell mit dem Mund, ja selbst innerlich fiebere nicht,
vor Gott das Wort zu ergreifen. Gott ist im Himmel, du bist auf der
Erde, also mach wenig Worte!

<<v2>>
2 Im Traum schließt man viele Geschäfte ab, der Ungebildete macht viele
Worte. [fn:1]\\
\\

<<v3>>
* Gelübde: 5,3-6

3 Wenn du Gott ein Gelübde machst, /\\
 dann zögere nicht, es zu erfüllen. Die Ungebildeten gefallen Gott
nicht: /\\
 Was du gelobst, erfülle! [fn:2]\\
\\

<<v4>>
4 Es ist besser, wenn du nichts gelobst, /\\
 als wenn du etwas gelobst und nicht erfüllst.\\
\\

<<v5>>
5 Lass nicht zu, dass dein Mund /\\
 dein Fleisch in Sünde stürzt. Erkläre nie vor dem Boten: /\\
 Es war ein Versehen. Warum soll Gott zürnen über das, was du redest,
/\\
 und vernichten, was deine Hände tun? [fn:3] [fn:4]\\
\\

<<v6>>
6 Vielmehr, wo Träume sich mehren und Windhauch und viele Worte, /\\
 da fürchte du Gott!\\
\\

<<v7>>
* Über Armut und Reichtum: 5,7 - 6,10

* Beamtenherrschaft: 5,7-8

7 Wenn du beobachtest, dass in der Provinz die Armen ausgebeutet und
Gericht und Gerechtigkeit nicht gewährt werden, dann wundere dich nicht
über solche Vorgänge: Ein Mächtiger deckt den andern, /\\
 hinter beiden stehen noch Mächtigere [fn:5]\\
\\

<<v8>>
8 und es ist auf jeden Fall ein Vorteil für das Land, wenn das bebaute
Feld einem König untersteht. [fn:6]\\
\\

<<v9>>
* Die Nutzlosigkeit des Reichtums: 5,9-11

9 Wer das Geld liebt, /\\
 bekommt vom Geld nie genug; wer den Luxus liebt, /\\
 hat nie genug Einnahmen - auch das ist Windhauch. [fn:7]\\
\\

<<v10>>
10 Mehrt sich das Vermögen, /\\
 so mehren sich auch die, die es verzehren. Was für ein Erfolg bleibt
dem Besitzer? /\\
 Seine Augen dürfen zusehen. [fn:8]\\
\\

<<v11>>
11 Süß ist der Schlaf des Arbeiters, /\\
 ob er wenig oder viel zu essen hat. Dem Reichen raubt sein voller Bauch
/\\
 die Ruhe des Schlafs.\\
\\

<<v12>>
* Verlust des Reichtums: 5,12-16

12 Es gibt etwas Schlimmes, etwas wie eine Krankheit, das ich unter der
Sonne beobachtet habe: wenn Reichtum, der für seinen Besitzer ängstlich
gehütet wurde, diesem Schlimmes brachte. [fn:9]

<<v13>>
13 Durch ein schlechtes Geschäft ging ihm dieser Reichtum verloren. Er
hatte einen Sohn gezeugt, aber jetzt hat er nichts mehr, das ihm gehört. [fn:10]

<<v14>>
14 Wie er aus dem Leib seiner Mutter herausgekommen ist - nackt, wie er
kam, muss er wieder gehen. Von seinem Besitz darf er überhaupt nichts
forttragen, nichts, das er als ihm gehörig mitnehmen könnte. [fn:11]

<<v15>>
15 So ist auch dies etwas Schlimmes, etwas wie eine Krankheit. Genau wie
er kam, muss er gehen. Welchen Vorteil bringt es ihm, dass er sich
anstrengt für den Wind?

<<v16>>
16 Auch wird er während seines ganzen restlichen Lebens sein Essen im
Dunkeln einnehmen; er wird sich häufig ärgern und Krankheit und Unmut
werden ihn plagen. [fn:12]\\
\\

<<v17>>
* Unverwerteter Reichtum: 5,17 - 6,2

17 Dies ist etwas, was ich eingesehen habe: Das vollkommene Glück
besteht darin, dass jemand isst und trinkt und das Glück kennen lernt
durch seinen eigenen Besitz, für den er sich unter der Sonne anstrengt
während der wenigen Tage seines Lebens, die Gott ihm geschenkt hat. Denn
das ist sein Anteil. [fn:13]

<<v18>>
18 Außerdem: Immer wenn Gott einem Menschen Reichtum und Wohlstand
geschenkt und ihn ermächtigt hat, davon zu essen und seinen Anteil
fortzutragen und durch seinen Besitz Freude zu gewinnen, besteht das
eigentliche Geschenk Gottes darin,

<<v19>>
19 dass dieser Mensch sich nicht so oft daran erinnern muss, wie wenige
Tage sein Leben zählt, weil Gott ihn sich um die Freude seines Herzens
bemühen lässt.


* Footnotes

[fn:1] [[file:Koh_10.org::v14][10,14]]; [[file:Spr_10.org::v19][Spr 10,19]]

[fn:2] [[file:Num_30.org::v3][Num 30,3]]; [[file:Dtn_23.org::v22][Dtn 23,22]]; (3-6) [[file:Spr_20.org::v25][Spr 20,25]]; [[file:Sir_18.org::v22][Sir 18,22f]]

[fn:3] [[file:Lev_4.org][Lev 4f]]; [[file:Num_15.org::v22][Num 15,22-31]]; [[file:Num_35.org::v9][35,9-25]]

[fn:4] Unter dem «Boten» ist wahrscheinlich der Priester zu
verstehen (vgl. Mal 2,7).

[fn:5] [[file:Koh_3.org::v16][3,16]]; [[file:Koh_4.org::v1][4,1]]; [[file:Ex_23.org::v6][Ex 23,6-9]]

[fn:6] Andere Übersetzungsmöglichkeit: wenn ein König sich um
das Ackerland kümmert. - Gegenüber einem Beamtenstaat wird ausgedehnter
königlicher Grundbesitz als das geringere Übel betrachtet.

[fn:7] [[file:Koh_1.org::v8][1,8]]; [[file:Koh_4.org::v8][4,8]]

[fn:8] [[file:Spr_19.org::v6][Spr 19,6]]

[fn:9] [[file:Koh_2.org::v17][2,17]]

[fn:10] Durch ein schlechtes Geschäft, andere
Übersetzungsmöglichkeit: Durch ein schlimmes Ereignis.

[fn:11] [[file:Ijob_1.org::v21][Ijob 1,21]]; [[file:Ps_49.org::v17][Ps 49,17f]]; [[file:~/Documents/notes/Bibel/nt/1.Tim_6.org::v7][1 Tim 6,7]]

[fn:12] [[file:Koh_2.org::v23][2,23]]

[fn:13] [[file:Koh_2.org::v10][2,10]]
