#+TITLE: Koh 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-02-03 Mo 10:21]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Koh 2.html

* Koh 2

<<verses>>

<<v1>>
1 Ich dachte mir: Auf, versuch es mit der Freude, genieß das Glück! Das
Ergebnis: Auch das ist Windhauch. [fn:1]\\
\\

<<v2>>
2 Über das Lachen sagte ich: Wie verblendet!, /\\
 über die Freude: Was bringt sie schon ein? [fn:2]\\
\\

<<v3>>
* Menschliches Glück durch Weltgestaltung: 2,3-11

3 Ich trieb meine Forschung an mir selbst, indem ich meinen Leib mit
Wein lockte, während mein Verstand das Wissen auf die Weide führte, und
indem ich das Unwissen gefangen nahm. Ich wollte dabei beobachten, wo es
vielleicht für die einzelnen Menschen möglich ist, sich unter dem Himmel
Glück zu verschaffen während der wenigen Tage ihres Lebens. [fn:3] [fn:4]\\
\\

<<v4>>
4 Ich vollbrachte meine großen Taten: Ich baute mir Häuser, /\\
 ich pflanzte Weinberge. [fn:5]\\
\\

<<v5>>
5 Ich legte mir Gärten und Parks an, /\\
 darin pflanzte ich alle Arten von Bäumen. [fn:6]\\
\\

<<v6>>
6 Ich legte Wasserbecken an, /\\
 um aus ihnen den sprossenden Baumbestand zu bewässern. [fn:7]\\
\\

<<v7>>
7 Ich kaufte Sklaven und Sklavinnen, /\\
 obwohl ich schon hausgeborene Sklaven besaß. Auch Vieh besaß ich in
großer Zahl, Rinder, Schafe, Ziegen, /\\
 mehr als alle meine Vorgänger in Jerusalem. [fn:8]\\
\\

<<v8>>
8 Ich hortete auch Silber und Gold /\\
 und, als meinen persönlichen Schatz, Könige und ihre Provinzen. Ich
besorgte mir Sänger und Sängerinnen /\\
 und die Lust jedes Menschen: einen großen Harem. [fn:9] [fn:10]\\
\\

<<v9>>
9 Ich war schon groß gewesen, doch ich gewann noch mehr hinzu, sodass
ich alle meine Vorgänger in Jerusalem übertraf. Und noch mehr: Mein
Wissen stand mir zur Verfügung [fn:11]

<<v10>>
10 und was immer meine Augen sich wünschten, verwehrte ich ihnen nicht.
Ich musste meinem Herzen keine einzige Freude versagen. Denn mein Herz
konnte immer durch meinen ganzen Besitz Freude gewinnen. Und das war
mein Anteil, den ich durch meinen ganzen Besitz gewinnen konnte. [fn:12]

<<v11>>
11 Doch dann dachte ich nach über alle meine Taten, die meine Hände
vollbracht hatten, und über den Besitz, für den ich mich bei diesem Tun
angestrengt hatte. Das Ergebnis: Das ist alles Windhauch und
Luftgespinst. Es gibt keinen Vorteil unter der Sonne. [fn:13]\\
\\

<<v12>>
* Bildung und Besitz in ihrer Bedingtheit: 2,12-23

12 Ich dachte nach, indem ich beobachtete, was Wissen wirklich ist und
was Verblendung und Unwissen wirklich sind. Außerdem: Was für ein Mann
wird auf den König folgen, den sie einst eingesetzt haben? [fn:14] [fn:15]

<<v13>>
13 Ich beobachtete: Es gibt einen Vorteil, den das Wissen bietet, aber
nicht das Unwissen, wie es einen Vorteil gibt, den das Licht bietet,
aber nicht die Dunkelheit: [fn:16]

<<v14>>
14 Der Gebildete hat Augen im Kopf, der Ungebildete tappt im Dunkeln.
Aber ich erkannte auch: Beide trifft ein und dasselbe Geschick. [fn:17]

<<v15>>
15 Da dachte ich mir: Was den Ungebildeten trifft, trifft also auch
mich. Warum bin ich dann über die Maßen gebildet? Und ich überlegte mir,
dass auch das Windhauch ist. [fn:18]

<<v16>>
16 Denn an den Gebildeten gibt es ebenso wenig wie an den Ungebildeten
eine Erinnerung, die ewig währt, weil man schon in den Tagen, die bald
kommen, beide vergessen wird. Wie ist es möglich, dass der Gebildete
ebenso sterben muss wie der Ungebildete? [fn:19]

<<v17>>
17 Da verdross mich das Leben. Denn das Tun, das unter der Sonne getan
wurde, lastete auf mir als etwas Schlimmes. Denn es ist alles Windhauch
und Luftgespinst. [fn:20]

<<v18>>
18 Mich verdross auch mein ganzer Besitz, für den ich mich unter der
Sonne anstrenge und den ich dem Menschen lassen muss, der nach mir
kommt. [fn:21]

<<v19>>
19 Wer weiß, ob er ein Wissender ist oder ein Unwissender? Jedenfalls
wird er über meinen ganzen Besitz verfügen, für den ich mich unter der
Sonne angestrengt und mein Wissen eingesetzt habe. Auch das ist
Windhauch.

<<v20>>
20 Ich stellte mich um und überließ mich der Verzweiflung über meinen
ganzen Besitz, für den ich mich unter der Sonne angestrengt hatte. [fn:22]

<<v21>>
21 Denn es kommt vor, dass ein Mensch, dessen Besitz durch Wissen,
Können und Erfolg erworben wurde, ihn einem andern, der sich nicht dafür
angestrengt hat, als dessen Anteil überlassen muss. Auch das ist
Windhauch und etwas Schlimmes, das häufig vorkommt. [fn:23]

<<v22>>
22 Was erhält der Mensch dann durch seinen ganzen Besitz und durch das
Gespinst seines Geistes, für die er sich unter der Sonne anstrengt? [fn:24]\\
\\

<<v23>>
23 Alle Tage besteht sein Geschäft nur aus Sorge und Ärger /\\
 und selbst in der Nacht kommt sein Geist nicht zur Ruhe. Auch das ist
Windhauch. [fn:25]\\
\\

<<v24>>
* Gottes Handeln in seiner Vollkommenheit und Undurchschaubarkeit: 2,24 - 3,15

24 Nicht im Menschen selbst gründet das Glück, dass er essen und trinken
und durch seinen Besitz das Glück selbst kennen lernen kann. Ich habe
vielmehr beobachtet, dass dies von Gottes Verfügung abhängt. [fn:26]

<<v25>>
25 Denn wer hat zu essen, wer weiß zu genießen, wenn nicht ich? [fn:27]

<<v26>>
26 Aber es gibt Menschen, denen Gott wohlwill. Es sind die, denen er
Wissen, Können und Freude geschenkt hat. Und es gibt Menschen, deren
Leben verfehlt ist. Es sind diejenigen, die er mit dem Geschäft
beauftragt hat, zu sammeln und zu horten und dann alles denen zu geben,
denen er wohl will. Auch das ist Windhauch und Luftgespinst. [fn:28]

* Footnotes

[fn:1] [[v3][2,3]].[[v10][10]].[[v24][24]]; [[file:Koh_3.org::v12][3,12]]; [[file:Weish_2.org::v6][Weish 2,6]]

[fn:2] [[file:Spr_14.org::v13][Spr 14,13]]; [[file:Spr_20.org::v1][20,1]]; [[file:Spr_23.org::v29][23,29-35]]

[fn:3] [[v1][2,1]]

[fn:4] Der Sinn von H ist stellenweise nicht klar.

[fn:5] [[file:1.Kön_7.org][1 Kön 7]]; [[file:Hld_8.org::v11][Hld 8,11]]

[fn:6] [[file:Hld_4.org::v13][Hld 4,13]]

[fn:7] [[file:Neh_2.org::v14][Neh 2,14]]

[fn:8] [[file:1.Kön_10.org::v5][1 Kön 10,5]]; [[file:Koh_8.org::v63][8,63]]; [[file:Koh_10.org::v23][10,23]]

[fn:9] [[file:1.Kön_10.org::v21][1 Kön 10,21]]; [[file:1.Kön_5.org::v1][5,1-8]]; [[file:2.Sam_19.org::v36][2 Sam 19,36]]; [[file:1.Kön_11.org::v3][1 Kön 11,3]]

[fn:10] einen großen Harem: Übersetzung nicht ganz sicher.

[fn:11] [[file:Koh_1.org::v16][1,16]]; [[file:1.Kön_10.org::v23][1 Kön 10,23]]; [[file:1.Kön_5.org::v9][5,9-14]]

[fn:12] [[v1][2,1]].[[v24][24]]; [[file:Koh_3.org::v12][3,12]].[[file:Koh_3.org::v22][22]]; [[file:Koh_5.org::v17][5,17f]]; [[file:Koh_8.org::v15][8,15]]; [[file:Koh_9.org::v6][9,6-9]]; [[file:Koh_11.org::v7][11,7-10]]

[fn:13] [[file:Koh_1.org::v3][1,3]]

[fn:14] [[file:Koh_1.org::v17][1,17]]; [[file:Koh_7.org::v25][7,25]]

[fn:15] Dieser Vers deutet nacheinander die beiden Themen an,
die dann entfaltet werden: Wissen endet mit dem Tod (2,13-17) und Besitz
endet mit dem Tod (2,18-23).

[fn:16] [[file:Koh_6.org::v8][6,8]]

[fn:17] [[file:Koh_8.org::v1][8,1]]; [[file:Koh_10.org::v2][10,2]]; [[file:Koh_3.org::v19][3,19]]; [[file:Koh_9.org::v2][9,2f]]; [[file:Ijob_9.org::v22][Ijob 9,22]]

[fn:18] [[file:Koh_7.org::v16][7,16]]

[fn:19] [[file:Koh_1.org::v11][1,11]]; [[file:Koh_9.org::v5][9,5]]; [[file:Weish_2.org::v4][Weish 2,4]]; [[file:Ps_49.org::v11][Ps 49,11]]

[fn:20] [[file:Koh_5.org::v12][5,12]]; [[file:Koh_6.org::v1][6,1f]]

[fn:21] [[file:1.Kön_12.org::v1][1 Kön 12,1-17]]; (18-19) [[v12][2,12]]; [[file:Koh_6.org::v1][6,1-7]]; [[file:Ps_39.org::v7][Ps 39,7]]

[fn:22] 20-23: Nicht nur nach dem Tod, sondern sogar schon
während des Lebens kann man seinen Besitz verlieren. Dieser Gedanke
leitet zu 2,24 - 3,9 über, wo dargelegt wird, dass auch während des
Lebens kein Augenblick ganz in der Hand des Menschen selbst ist.

[fn:23] [[file:Koh_6.org::v2][6,2]]; [[file:Sir_11.org::v18][Sir 11,18f]]

[fn:24] [[file:Koh_1.org::v3][1,3]]

[fn:25] [[file:Koh_1.org::v18][1,18]]; [[file:Koh_5.org::v16][5,16]]; [[file:Koh_8.org::v16][8,16f]]; [[file:Koh_11.org::v10][11,10]]; [[file:Ijob_7.org::v1][Ijob 7,1-4]]

[fn:26] [[v10][2,10]]

[fn:27] [[file:Koh_9.org::v1][9,1]]

[fn:28] [[file:Koh_7.org::v26][7,26]]; [[file:Ijob_27.org::v16][Ijob 27,16f]]; [[file:Spr_13.org::v22][Spr 13,22]]; [[file:Spr_28.org::v8][28,8]]
