#+TITLE: Koh 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-02-03 Mo 11:19]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Koh 3.html

* Koh 3

<<verses>>

<<v1>>
1 Alles hat seine Stunde. Für jedes Geschehen unter dem Himmel gibt es
eine bestimmte Zeit: [fn:1]\\
\\

<<v2>>
2 eine Zeit zum Gebären /\\
 und eine Zeit zum Sterben, /\\
 eine Zeit zum Pflanzen /\\
 und eine Zeit zum Abernten der Pflanzen, [fn:2]\\
\\

<<v3>>
3 eine Zeit zum Töten /\\
 und eine Zeit zum Heilen, /\\
 eine Zeit zum Niederreißen /\\
 und eine Zeit zum Bauen,\\
\\

<<v4>>
4 eine Zeit zum Weinen /\\
 und eine Zeit zum Lachen, /\\
 eine Zeit für die Klage /\\
 und eine Zeit für den Tanz;\\
\\

<<v5>>
5 eine Zeit zum Steinewerfen /\\
 und eine Zeit zum Steinesammeln, /\\
 eine Zeit zum Umarmen /\\
 und eine Zeit, die Umarmung zu lösen,\\
\\

<<v6>>
6 eine Zeit zum Suchen /\\
 und eine Zeit zum Verlieren, /\\
 eine Zeit zum Behalten /\\
 und eine Zeit zum Wegwerfen,\\
\\

<<v7>>
7 eine Zeit zum Zerreißen /\\
 und eine Zeit zum Zusammennähen, /\\
 eine Zeit zum Schweigen /\\
 und eine Zeit zum Reden, [fn:3]\\
\\

<<v8>>
8 eine Zeit zum Lieben /\\
 und eine Zeit zum Hassen, /\\
 eine Zeit für den Krieg /\\
 und eine Zeit für den Frieden. [fn:4]\\
\\

<<v9>>
9 Wenn jemand etwas tut - welchen Vorteil hat er davon, dass er sich
anstrengt? [fn:5]

<<v10>>
10 Ich sah mir das Geschäft an, für das jeder Mensch durch Gottes
Auftrag sich abmüht. [fn:6]

<<v11>>
11 Gott hat das alles zu seiner Zeit auf vollkommene Weise getan.
Überdies hat er die Ewigkeit in alles hineingelegt, doch ohne dass der
Mensch das Tun, das Gott getan hat, von seinem Anfang bis zu seinem Ende
wieder finden könnte. [fn:7] [fn:8]

<<v12>>
12 Ich hatte erkannt: Es gibt kein in allem Tun gründendes Glück, es sei
denn, ein jeder freut sich und so verschafft er sich Glück, während er
noch lebt, [fn:9]

<<v13>>
13 wobei zugleich immer, wenn ein Mensch isst und trinkt und durch
seinen ganzen Besitz das Glück kennen lernt, das ein Geschenk Gottes
ist. [fn:10]

<<v14>>
14 Jetzt erkannte ich: Alles, was Gott tut, geschieht in Ewigkeit. Man
kann nichts hinzufügen und nichts abschneiden und Gott hat bewirkt, dass
die Menschen ihn fürchten. [fn:11]

<<v15>>
15 Was auch immer geschehen ist, war schon vorher da, und was geschehen
soll, ist schon geschehen und Gott wird das Verjagte wieder suchen. [fn:12]\\
\\

<<v16>>
* Die Übel der Welt: 3,16 - 4,16

* Unrecht bei Gericht: 3,16-22

16 Noch etwas habe ich beobachtet unter der Sonne: An der Stätte, wo man
Urteil spricht, geschieht Unrecht; an der Stätte, wo man gerechtes
Urteil sprechen sollte, geschieht Unrecht. [fn:13]

<<v17>>
17 Da dachte ich mir: Gott ist es, der den Unschuldigen wie den
Schuldigen verurteilt. Denn eine bestimmte Zeit für jedes Geschehen und
für jedes Tun gibt es (auch) dort. [fn:14] [fn:15]

<<v18>>
18 Was die einzelnen Menschen angeht, dachte ich mir, dass Gott sie
herausgegriffen hat und dass sie selbst (daraus) erkennen müssen, dass
sie eigentlich Tiere sind. [fn:16]

<<v19>>
19 Denn jeder Mensch unterliegt dem Geschick und auch die Tiere
unterliegen dem Geschick. Sie haben ein und dasselbe Geschick. Wie diese
sterben, so sterben jene. Beide haben ein und denselben Atem. Einen
Vorteil des Menschen gegenüber dem Tier gibt es da nicht. Beide sind
Windhauch. [fn:17] [fn:18]

<<v20>>
20 Beide gehen an ein und denselben Ort. Beide sind aus Staub
entstanden, beide kehren zum Staub zurück. [fn:19]

<<v21>>
21 Wer weiß, ob der Atem der einzelnen Menschen wirklich nach oben
steigt, während der Atem der Tiere ins Erdreich hinabsinkt?

<<v22>>
22 So habe ich eingesehen: Es gibt kein Glück, es sei denn, der Mensch
kann durch sein Tun Freude gewinnen. Das ist sein Anteil. Wer könnte es
ihm ermöglichen, etwas zu genießen, das erst nach ihm sein wird? [fn:20]\\
\\


* Footnotes

[fn:1] [[v17][3,17]]; [[file:Koh_8.org::v5][8,5f]]; [[file:Koh_9.org::v11][9,11f]]; [[file:Ps_31.org::v16][Ps 31,16]]

[fn:2] [[file:Koh_7.org::v17][7,17]]; [[file:Ijob_5.org::v26][Ijob 5,26]]; [[file:Jes_28.org::v23][Jes 28,23-29]]

[fn:3] [[file:Spr_15.org::v23][Spr 15,23]]

[fn:4] [[file:Koh_9.org::v1][9,1]]

[fn:5] [[file:Koh_1.org::v3][1,3]]

[fn:6] [[file:Koh_1.org::v13][1,13]]

[fn:7] [[file:Koh_11.org::v5][11,5]]; [[v14][3,14f]]; [[file:Koh_7.org::v14][7,14]].[[file:Koh_7.org::v23][23-29]]; [[file:Koh_8.org::v16][8,16f]]; [[file:Ps_139.org::v13][Ps 139,13-18]]

[fn:8] 11b: Andere Übersetzungsmöglichkeit: Überdies hat er den
Menschen eine Vorstellung von der Ewigkeit eingegeben ...

[fn:9] [[file:Koh_2.org::v10][2,10]]

[fn:10] [[file:Koh_2.org::v24][2,24f]]

[fn:11] [[file:Spr_30.org::v6][Spr 30,6]]; [[file:Sir_18.org::v6][Sir 18,6]]; [[file:Sir_42.org::v21][42,21]] (14-15) [[file:Sir_1.org::v4][1,4-11]]

[fn:12] [[file:Koh_1.org::v9][1,9]]; [[file:Sir_5.org::v3][Sir 5,3]]

[fn:13] [[file:Koh_5.org::v7][5,7]]; (16-22) [[file:Koh_8.org::v12][8,12-15]]

[fn:14] [[v1][3,1]]; [[file:Koh_11.org::v3][11,3]]

[fn:15] Wenn menschliche Richter Unschuldige zum Tod
verurteilen, muss das zugleich als Tun Gottes betrachtet werden; denn
[[v1][3,1]] gilt auch bei menschlichen Gerichtsentscheidungen. Von [[v18][3,18]] ab wird
dann erwogen, welche Absicht Gott dabei haben könnte.

[fn:16] Die «einzelnen Menschen», die Gott «herausgegriffen»
hat, sind die unschuldig zum Tod Verurteilten. In H ein Wortspiel: sie
selbst (hemmah) - Tiere (behemah).

[fn:17] [[file:Koh_2.org::v14][2,14]]; [[file:Ps_49.org::v13][Ps 49,13]].[[file:Ps_49.org::v21][21]]

[fn:18] 19a: Wörtlich: Denn jeder Mensch ist Geschick und auch
die Tiere sind Geschick. Oder: Denn jeder Mensch ist ein Zufall und auch
die Tiere sind Zufall.

[fn:19] [[file:Koh_6.org::v6][6,6]]; [[file:Koh_12.org::v7][12,7]]; [[file:Gen_2.org::v7][Gen 2,7]]; [[file:Gen_3.org::v19][3,19]]; [[file:Ps_103.org::v14][Ps 103,14]]; [[file:Ps_104.org::v29][104,29]]; [[file:Ps_146.org::v4][146,4]];
[[file:Ijob_34.org::v14][Ijob 34,14f]]; [[file:Sir_17.org::v1][Sir 17,1]]; [[file:Sir_40.org::v11][40,11]]; [[file:Weish_2.org::v2][Weish 2,2f]]

[fn:20] [[file:Koh_2.org::v10][2,10]]; [[file:Koh_6.org::v12][6,12]]
