#+TITLE: Koh 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-02-13 Do 14:42]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Koh 12.html

* Koh 12

<<verses>>

<<v1>>
1 Denk an deinen Schöpfer in deinen frühen Jahren, /\\
 ehe die Tage der Krankheit kommen und die Jahre dich erreichen, /\\
 von denen du sagen wirst: Ich mag sie nicht!,\\
\\

<<v2>>
2 ehe Sonne und Licht und Mond und Sterne erlöschen /\\
 und auch nach dem Regen wieder Wolken aufziehen:\\
\\

<<v3>>
3 am Tag, da die Wächter des Hauses zittern, /\\
 die starken Männer sich krümmen, /\\
 die Müllerinnen ihre Arbeit einstellen, weil sie zu wenige sind, /\\
 es dunkel wird bei den Frauen, die aus den Fenstern blicken, [fn:1]\\
\\

<<v4>>
4 und das Tor zur Straße verschlossen wird; /\\
 wenn das Geräusch der Mühle verstummt, /\\
 steht man auf beim Zwitschern der Vögel, /\\
 doch die Töne des Lieds verklingen; [fn:2]\\
\\

<<v5>>
5 selbst vor der Anhöhe fürchtet man sich und vor den Schrecken am Weg;
/\\
 der Mandelbaum blüht, /\\
 die Heuschrecke schleppt sich dahin, /\\
 die Frucht der Kaper platzt, /\\
 doch ein Mensch geht zu seinem ewigen Haus /\\
 und die Klagenden ziehen durch die Straßen - [fn:3] [fn:4]\\
\\

<<v6>>
6 ja, ehe die silberne Schnur zerreißt, /\\
 die goldene Schale bricht, /\\
 der Krug an der Quelle zerschmettert wird, /\\
 das Rad zerbrochen in die Grube fällt,\\
\\

<<v7>>
7 der Staub auf die Erde zurückfällt als das, was er war, /\\
 und der Atem zu Gott zurückkehrt, /\\
 der ihn gegeben hat. [fn:5]\\
\\

<<v8>>
* Rahmenvers: 12,8

8 Windhauch, Windhauch, sagte Kohelet, das ist alles Windhauch. [fn:6]\\
\\

<<v9>>
* Zwei Nachworte von Herausgebern: 12,9-14

* Das erste Nachwort: 12,9-11

9 Kohelet war ein Gelehrter. Außerdem hat er einfachen Leuten Kenntnisse
beigebracht. Er hörte zu und prüfte, er hat viele Sprichwörter selbst in
Form gebracht. [fn:7]

<<v10>>
10 Kohelet hat sich bemüht, gut formulierte Worte zu entdecken, und hier
sind diese wahren Worte sorgfältig aufgeschrieben.\\
\\

<<v11>>
11 Worte von Gelehrten sind wie Ochsenstecken, /\\
 Sprüche aus Sammlungen aber sitzen wie eingetriebene Nägel - /\\
 sie sind die Gabe eines einzigen Hirten. [fn:8]\\
\\

<<v12>>
* Das zweite Nachwort: 12,12-14

12 Im Übrigen, mein Sohn, lass dich warnen! Es nimmt kein Ende mit dem
vielen Bücherschreiben und viel Studieren ermüdet den Leib. [fn:9]

<<v13>>
13 Hast du alles gehört, so lautet der Schluss: Fürchte Gott und achte
auf seine Gebote! Das allein hat jeder Mensch nötig. [fn:10]

<<v14>>
14 Denn Gott wird jedes Tun vor das Gericht bringen, das über alles
Verborgene urteilt, es sei gut oder böse. [fn:11]\\
\\


* Footnotes

[fn:1] 3f: Allegorie; gemeint sind Arme, Beine, Zähne, Augen,
Mund und Ohren des alternden Menschen.

[fn:2] 4d: Wörtlich: Alle Töchter des Liedes ducken sich. - Die
«Töchter des Liedes» sind in der Übersetzung als Töne der Melodie
verstanden. Es könnte sich aber auch um eine poetische Umschreibung für
die Vögel handeln, die verstummen.

[fn:3] [[file:Sir_25.org::v20][Sir 25,20]]

[fn:4] Das «ewige Haus» ist das Grab.

[fn:5] [[file:Koh_3.org::v20][3,20f]]

[fn:6] [[file:Koh_1.org::v2][1,2]]

[fn:7] [[file:1.Kön_5.org::v12][1 Kön 5,12]]

[fn:8] Hier ist vom Vorteil schriftlicher Aufzeichnungen
gegenüber mündlicher Lehre die Rede. Vielleicht hatte Kohelet selbst nur
mündlich gelehrt und der Verfasser des ersten Nachwortes mag seine von
den Schülern auswendig gelernten oder in privaten Aufzeichnungen
festgehaltenen Lehren gesammelt und als Buch veröffentlicht haben.

[fn:9] 12-14: Das zweite Nachwort bringt einige Absicherungen
an dem Buch an, damit dieses Buch als rechtgläubig gelten kann.

[fn:10] [[file:Koh_3.org::v14][3,14]]; [[file:Koh_5.org::v6][5,6]]; [[file:Koh_7.org::v18][7,18]]; [[file:Dtn_10.org::v12][Dtn 10,12]]; [[file:Spr_1.org::v7][Spr 1,7]]; [[file:Sir_1.org::v13][Sir 1,13]]

[fn:11] [[file:Koh_11.org::v9][11,9]]
