#+TITLE: Koh 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-12-20 Fr 18:34]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Koh 1.html

* Koh 1
Das Buch Kohelet wurde um die Mitte des 3. Jahrhunderts v. Chr.
geschrieben. Der Verfasser, der sich selbst Kohelet nennt, ist uns nicht
bekannt. Palästina gehörte damals zum Ptolemäerreich. Es war die Zeit
noch vor den hellenistischen Religionsverfolgungen und vor der
nationalen Erhebung der Makkabäer. Die gebildete Oberschicht von Judäa
war wohlhabend und weltoffen. Man versuchte, die Traditionen Israels mit
der die Welt beherrschenden griechischen Bildung und Lebensform zu einer
neuen Einheit zu verschmelzen.\\
\\
Das Buch Kohelet ist das eindrucksvollste Zeugnis dieses Bemühens. Die
Bildungstraditionen Israels, ja des ganzen Orients, besonders auch
Ägyptens, sind Kohelet bekannt (zur »Weisheit« vgl. die Einleitung zu
Spr). Sein Denken und Fühlen ist von den Schriftstellern, die man in den
griechischen Schulen liest, und von der sogenannten Popularphilosophie
bestimmt. Seine Sprache ist ein ganz neuartiges Hebräisch, in dem
einerseits die aramäische Alltagssprache, andererseits manches
griechische Wort- und Satzmuster durchschlägt. Das Buch lehnt sich nur
noch teilweise an die poetische Gestalt der alten Lehrschriften an. Es
enthält auch schon viele Merkmale der damals aufkommenden Predigt von
Wanderphilosophen (»Diatribe«).\\
\\
Das Buch entwirft zunächst eine Lehre vom Kosmos (1,4-11). Der
herrliche, ewig kreisende Kosmos ist die Bühne, auf der die
vergänglichen Menschen kommen und gehen. Sprache, Sinne und Gedächtnis
der Menschen können die Fülle der Welt nicht erfassen. Es folgt als
grundlegender Teil des Buches die Lehre vom Menschen (1,12 - 3,15).
Kohelet versetzt sich in die höchste menschliche Möglichkeit: Er sieht
sich als gebildeten, weltgestaltenden und das Leben voll auskostenden
Herrscher und fragt dann nach dem Sinn. Angesichts des sicher kommenden
Todes erweist sich selbst dann alles als »Windhauch«. Jeder Augenblick
ist von Gott her bestimmt; der Mensch kann ihn weder berechnen noch in
den Griff bekommen. Er kann nur in Furcht das, was ihm jeweils gegeben
wird, annehmen. Dieses Daseinsverständnis bestätigt sich dann in einem
anschließenden Teil, der die Übel der Welt anhand ausgewählter Beispiele
aus dem öffentlichen, wirtschaftlichen und familiären Leben kritisiert
(3,16 - 6,10). Im nächsten Teil werden Beispiele traditioneller
Spruchweisheit und die weisheitliche Theorie über den Zusammenhang von
Tun und Ergehen kritisch überprüft (6,11 - 9,6). Am Ende steht wieder
das Thema Tod. Daran schließt sich die Ethik an, die Weisung für die
rechte Lebensführung (9,7 - 12,7). Sie ist sehr vielfältig, doch ist sie
geleitet von der Mahnung, in Gottesfurcht die Gabe des jeweiligen
Augenblicks zu ergreifen: jede Freude zu genießen und überall da, wo es
sich anbietet, tatkräftig zu handeln. Denn jedes »Jetzt« ist die dem
Menschen gegebene Zeit. Er soll nie vergessen, dass er auf Alter und Tod
zugeht. Aus dieser Ethik sind die Anweisungen über das religiöse
Verhalten herausgenommen und schon vorher als eine Art Zwischenstück in
die Gesellschaftskritik eingesetzt (4,17 - 5,6). So bilden sie im
Gesamtaufbau des Buches eine Art Mitte.\\
\\
Im modernen Denken wird man mit dem Buch Kohelet vor allem die
Existenzphilosophie vergleichen können. Doch ist im Buch Kohelet bei
aller Neigung zur Erfahrungsweisheit und zur kritischen
Auseinandersetzung mit gängigen Meinungen zugleich eine sehr radikale
Theorie von der Bindung der Welt an Gott vorausgesetzt. Nach ihr kann
nichts, auch nicht das Böseste und Schlimmste, von der Allursächlichkeit
Gottes ausgenommen werden. Und von Gott her ist letztlich alles »schön«.
Dies sollte man nicht übersehen, wenn man beim Lesen des Buches von
Melancholie überwältigt wird und Kohelet gerade deshalb als modern
empfinden möchte. Wer Kohelet als Teil des ganzen Kanons der heiligen
Schriften liest, wird das Buch, ohne dabei die Härte seines Fragens und
Denkens preiszugeben, mit der Botschaft vom Handeln Gottes in der
Geschichte verbinden.\\
\\

<<verses>>

<<v1>>
* Buchtitel: 1,1
1 Worte Kohelets, des Davidsohnes, der König in Jerusalem war. [fn:1]
\\
\\

<<v2>>
* Vorspruch: 1,2-3
2 Windhauch, Windhauch, sagte Kohelet, Windhauch, Windhauch, das ist
alles Windhauch. [fn:2]

<<v3>>
3 Welchen Vorteil hat der Mensch von all seinem Besitz, für den er sich
anstrengt unter der Sonne? [fn:3] [fn:4]\\
\\

<<v4>>
* Wechsel, Dauer und Vergessen: 1,4-11
4 Eine Generation geht, eine andere kommt. /\\
 Die Erde steht in Ewigkeit. [fn:5]\\
\\

<<v5>>
5 Die Sonne, die aufging und wieder unterging, /\\
 atemlos jagt sie zurück an den Ort, wo sie wieder aufgeht. [fn:6]\\
\\

<<v6>>
6 Er weht nach Süden, dreht nach Norden, dreht, dreht, weht, der Wind.
/\\
 Weil er sich immerzu dreht, kehrt er zurück, der Wind.\\
\\

<<v7>>
7 Alle Flüsse fließen ins Meer, /\\
 das Meer wird nicht voll. Zu dem Ort, wo die Flüsse entspringen, /\\
 kehren sie zurück, um wieder zu entspringen.\\
\\

<<v8>>
8 Alle Dinge sind rastlos tätig, /\\
 kein Mensch kann alles ausdrücken, nie wird ein Auge satt, wenn es
beobachtet, /\\
 nie wird ein Ohr vom Hören voll. [fn:7] [fn:8]\\
\\

<<v9>>
9 Was geschehen ist, wird wieder geschehen, /\\
 was man getan hat, wird man wieder tun: /\\
 Es gibt nichts Neues unter der Sonne. [fn:9] [fn:10]\\
\\

<<v10>>
10 Zwar gibt es bisweilen ein Ding, von dem es heißt: /\\
 Sieh dir das an, das ist etwas Neues - /\\
 aber auch das gab es schon in den Zeiten, die vor uns gewesen sind. [fn:11]\\
\\

<<v11>>
11 Nur gibt es keine Erinnerung an die Früheren /\\
 und auch an die Späteren, die erst kommen werden, auch an sie wird es
keine Erinnerung geben /\\
 bei denen, die noch später kommen werden. [fn:12]\\
\\

<<v12>>
* Die Bedingtheit des Menschen - die Undurchschaubarkeit Gottes: 1,12 - 3,15
   
* Drei Überblicke: 1,12 - 2,2
12 Ich, Kohelet, war in Jerusalem König über Israel. [fn:13]

<<v13>>
13 Ich hatte mir vorgenommen, das Wissen daraufhin zu untersuchen und zu
erforschen, ob nicht alles, was unter dem Himmel getan wurde, ein
schlechtes Geschäft war, für das die einzelnen Menschen durch Gottes
Auftrag sich abgemüht haben. [fn:14]

<<v14>>
14 Ich beobachtete alle Taten, die unter der Sonne getan wurden. Das
Ergebnis: Das ist alles Windhauch und Luftgespinst. [fn:15] [fn:16]\\
\\

<<v15>>
15 Was krumm ist, kann man nicht gerade biegen; /\\
 was nicht da ist, kann man nicht zählen. [fn:17]\\
\\

<<v16>>
16 Ich überlegte mir Folgendes: Ich habe mein Wissen immerzu vergrößert,
sodass ich jetzt darin jeden übertreffe, der vor mir über Jerusalem
geherrscht hat. Oft konnte ich Wissen und Können beobachten. [fn:18]

<<v17>>
17 So habe ich mir vorgenommen zu erkennen, was Wissen wirklich ist, und
zu erkennen, was Verblendung und Unwissen wirklich sind. Ich erkannte,
dass auch dies ein Luftgespinst ist. [fn:19]\\
\\

<<v18>>
18 Denn: Viel Wissen, viel Ärger, /\\
 wer das Können mehrt, der mehrt die Sorge. [fn:20]\\
\\

* Footnotes

[fn:1] [[v12][1,12]]; [[file:Spr_1.org::v1][Spr 1,1]]; [[file:1.Kön_8.org::v1][1 Kön 8,1]]

[fn:2] [[file:Koh_12.org::v8][12,8]]; [[file:Ijob_7.org::v16][Ijob 7,16]]; [[file:Ps_39.org::v6][Ps 39,6]]; [[file:Ps_62.org::v10][62,10]]; [[file:~/Documents/notes/Bibel/nt/Röm_8.org::v20][Röm 8,20]]

[fn:3] [[file:Koh_2.org::v11][2,11]].[[file:Koh_2.org::v18][18-22]]; [[file:Koh_3.org::v9][3,9]]; [[file:Koh_5.org::v15][5,15]].[[file:Koh_5.org::v17][17]]; [[file:Koh_9.org::v9][9,9]]

[fn:4] Besitz, für den er sich anstrengt: ein Leitmotiv des
Buches; in H ein Wortspiel. Das Wort für «Besitz» meint sowohl die
menschliche Arbeit, die den Besitz hervorbringt, als auch den durch die
Arbeit und Mühe erworbenen Besitz selbst.

[fn:5] [[file:Sir_14.org::v18][Sir 14,18]]; (4-11) [[file:Koh_3.org::v11][3,11-15]]

[fn:6] Nach dem antiken Weltbild muss die Sonne nachts
unterhalb der Erdscheibe wieder zum östlichen Horizont zurückkehren.

[fn:7] [[file:Koh_5.org::v9][5,9]]; [[file:Koh_8.org::v17][8,17]]; [[file:Spr_27.org::v20][Spr 27,20]]

[fn:8] Alle Dinge sind rastlos tätig, andere
Übersetzungsmöglichkeit: Alle Worte sind überanstrengt.

[fn:9] [[file:Koh_3.org::v10][3,15]]; [[file:Koh_6.org::v10][6,10]]; [[file:Koh_4.org::v13][4,13-16]]

[fn:10] Dass es «nichts Neues unter der Sonne» gibt, ist
entgegen unserer Empfindung eine positive Aussage.

[fn:11] 10cd: Andere Übersetzungsmöglichkeit: aber schon seit
Ewigkeiten hat es das gegeben, was sich vor unseren Augen ereignet hat.

[fn:12] [[file:Koh_2.org::v16][2,16]]; [[file:Koh_9.org::v5][9,5]]

[fn:13] [[v12][1,12]] - [[file:Koh_3.org::v15][3,15]]: In diesem Teil des Buches spielt der
Verfasser in literarischer Fiktion die Rolle eines Königs.

[fn:14] [[file:Koh_3.org::v10][3,10]]; [[file:Koh_8.org::v9][8,9]].[[file:Koh_8.org::v16][16f]]; [[file:Koh_5.org::v13][5,13]]

[fn:15] [[file:Koh_2.org::v11][2,11]]; [[file:Koh_4.org::v4][4,4]]

[fn:16] Luftgespinst, andere Übersetzungsmöglichkeit: Haschen
nach Luft. So auch später, wenn dieses Wort wiederkommt.

[fn:17] [[file:Koh_7.org::v13][7,13]]; [[file:Spr_27.org::v22][Spr 27,22]]

[fn:18] [[file:Koh_2.org::v9][2,9]]; [[file:1.Kön_5.org::v9][1 Kön 5,9f]]

[fn:19] [[file:Koh_2.org::v12][2,12]]; [[file:Koh_7.org::v25][7,25]]; [[file:Koh_8.org::v16][8,16f]]

[fn:20] [[file:Koh_2.org::v23][2,23]]; [[file:Koh_5.org::v16][5,16]]; [[file:Spr_22.org::v15][Spr 22,15]]
