#+TITLE: Lev 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 13:57]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Lev 3.html

<<verses>>

<<v1>>
* Das Heilsopfer: 3,1-17

1 Ist seine Opfergabe ein Heilsopfer und vom Rind, dann soll er ein
männliches oder ein weibliches fehlerloses Tier vor den Herrn bringen. [fn:1]

<<v2>>
2 Er soll seine Hand auf den Kopf des Opfers legen und es am Eingang des
Offenbarungszeltes schlachten. Dann sollen die Söhne Aarons, die
Priester, das Blut ringsum an den Altar sprengen.

<<v3>>
3 Er soll einen Teil dieses Opfers als Feueropfer für den Herrn
darbringen, und zwar das Fett, das die Eingeweide bedeckt, das gesamte
Fett über den Eingeweiden,

<<v4>>
4 die beiden Nieren, das Fett über ihnen und das an den Lenden sowie die
Fettmasse, die er von der Leber und den Nieren loslöst.

<<v5>>
5 Die Söhne Aarons sollen diesen Teil mit dem Brandopfer, das auf dem
Holz über dem Feuer liegt, auf dem Altar in Rauch aufgehen lassen. Es
ist ein Feueropfer zum beruhigenden Duft für den Herrn.

<<v6>>
6 Ist seine Opfergabe ein Heilsopfer für den Herrn vom Kleinvieh, dann
soll er ein männliches oder weibliches fehlerloses Tier darbringen.

<<v7>>
7 Wenn er ein Schaf darbringt, soll er es vor den Herrn bringen.

<<v8>>
8 Er soll seine Hand auf den Kopf des Opfers legen und es vor dem
Offenbarungszelt schlachten; dann sollen die Söhne Aarons das Blut
ringsum an den Altar sprengen.

<<v9>>
9 Von diesem Heilsopfer soll er das Fett als Feueropfer für den Herrn
darbringen: den ganzen Fettschwanz, den er nahe an den
Schwanzwirbelknochen ablösen soll, das Fett, das die Eingeweide bedeckt,
das gesamte Fett über den Eingeweiden,

<<v10>>
10 die beiden Nieren, das Fett über ihnen und das an den Lenden sowie
die Fettmasse, die er von der Leber und den Nieren loslöst.

<<v11>>
11 Der Priester lasse diese Teile auf dem Altar in Rauch aufgehen. Das
soll eine Feueropferspeise für den Herrn sein.

<<v12>>
12 Wenn er eine Ziege darbringt, soll er sie vor den Herrn bringen.

<<v13>>
13 Er soll seine Hand auf ihren Kopf legen und sie vor dem
Offenbarungszelt schlachten; dann sollen die Söhne Aarons ihr Blut
ringsum an den Altar sprengen.

<<v14>>
14 Von ihr soll er als Feueropfer für den Herrn darbringen: das Fett,
das die Eingeweide bedeckt, das gesamte Fett über den Eingeweiden,

<<v15>>
15 die beiden Nieren, das Fett über ihnen und das an den Lenden sowie
die Fettmasse, die er von der Leber und den Nieren loslöst.

<<v16>>
16 Der Priester lasse diese Teile auf dem Altar in Rauch aufgehen. Sie
sind eine Feueropferspeise zum beruhigenden Duft für den Herrn. Das
ganze Fett gehört dem Herrn.

<<v17>>
17 Als feste Regel gelte bei euch von Generation zu Generation an allen
euren Wohnstätten: Ihr dürft weder Fett noch Blut genießen.\\
\\


* Footnotes

[fn:1] 1-17: Bei Heilsopfern oder, wie manche übersetzen, bei
Fried- oder Bundesopfern, werden nur die besten Teile des geschlachteten
Tiers auf dem Altar verbrannt, während der Rest beim Opfermahl von den
Teilnehmern der Feier verzehrt wird (vgl. die Anmerkung zu 1,1-17).
