#+TITLE: Lev 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 13:54]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Lev 2.html


<<verses>>

<<v1>>
* Das Speiseopfer: 2,1-16

1 Wenn jemand dem Herrn ein Speiseopfer darbringt, muss seine Opfergabe
aus Feinmehl bestehen, auf das er Öl gießen und Weihrauch legen soll.

<<v2>>
2 Er bringe es zu den Söhnen Aarons, den Priestern. Er nehme davon eine
Hand voll, vom Feinmehl und vom Öl mit dem ganzen Weihrauch, und der
Priester lasse sie auf dem Altar als Gedächtnisanteil in Rauch aufgehen,
als ein Feueropfer zum beruhigenden Duft für den Herrn. [fn:1]

<<v3>>
3 Der Rest des Speiseopfers gehört Aaron und seinen Söhnen als etwas
Hochheiliges von den Feueropfern des Herrn.

<<v4>>
4 Wenn du ein im Ofen gebackenes Speiseopfer darbringst, so soll es aus
Feinmehl sein, ein mit Öl vermengter ungesäuerter Kuchen und ein mit Öl
bestrichener ungesäuerter Brotfladen.

<<v5>>
5 Ist deine Opfergabe eine auf einer Ofenplatte zubereitete Speise, so
soll sie aus ungesäuertem Feinmehl sein, das mit Öl vermengt ist.

<<v6>>
6 Du sollst sie zerbröckeln und Öl darüber gießen. Ein Speiseopfer ist
es.

<<v7>>
7 Ist deine Opfergabe eine im Kochtopf zubereitete Speise, so soll sie
aus Feinmehl mit Öl angemacht sein.

<<v8>>
8 Du sollst die daraus zubereitete Speise zum Herrn bringen. Man soll
sie dem Priester reichen, der sie an den Altar bringt.

<<v9>>
9 Der Priester soll davon den Gedächtnisanteil abheben und auf dem Altar
in Rauch aufgehen lassen als ein Feueropfer zum beruhigenden Duft für
den Herrn.

<<v10>>
10 Der Rest des Speiseopfers gehört Aaron und seinen Söhnen als etwas
Hochheiliges von den Feueropfern des Herrn.

<<v11>>
11 Kein Speiseopfer, das ihr dem Herrn darbringt, darf mit Sauerteig
angemacht sein; denn ihr dürft dem Herrn weder Sauerteig noch Honig als
Feueropfer darbringen.

<<v12>>
12 Ihr sollt sie dem Herrn als Erstlingsopfer darbringen, aber auf dem
Altar sollen sie nicht zum beruhigenden Duft aufsteigen.

<<v13>>
13 Jedes Speiseopfer sollst du salzen und deinem Speiseopfer sollst du
das Salz des Bundes deines Gottes nicht fehlen lassen; jede deiner
Opfergaben sollst du mit Salz darbringen. [fn:2]

<<v14>>
14 Wenn du dem Herrn ein Speiseopfer von den Erstlingsfrüchten
darbringst, sollst du geröstete reife Körner und Grütze aus frischen
Körnern als Speiseopfer deiner Erstlingsfrüchte darbringen.

<<v15>>
15 Du sollst Öl darauf gießen und Weihrauch darauf geben. Ein
Speiseopfer ist es.

<<v16>>
16 Der Priester soll den Gedächtnisanteil mit einem Teil der Grütze und
des Öls mit dem ganzen Weihrauch als ein Feueropfer für den Herrn in
Rauch aufgehen lassen.\\
\\


* Footnotes

[fn:1] Gedächtnisanteil: der Teil des Opfers, der Gott dazu
bewegen soll, an den Opfernden zu denken.

[fn:2] Salz des Bundes: Salz gehört zum Mahl und darum auch zum
Opfer, das den Bund zwischen Gott und Volk bewusst macht (vgl. Num 18,19
und 2 Chr 13,5).
