#+TITLE: Lev 14 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 14:54]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Lev 14.html


<<verses>>

<<v1>>
* Die Reinigungsriten für vom Aussatz Geheilte: 14,1-32

1 Der Herr sprach zu Mose:

<<v2>>
2 Das ist das Gesetz für den Aussätzigen, wenn er für rein erklärt wird:
Man soll ihn zum Priester führen

<<v3>>
3 und der Priester soll vor das Lager herauskommen. Stellt er nach der
Untersuchung fest, dass der Aussätzige von seinem Aussatz geheilt ist,

<<v4>>
4 soll er anordnen, dass man für den, der sich der Reinigung unterzieht,
zwei lebende reine Vögel, Zedernholz, Karmesin und Ysop nimmt.

<<v5>>
5 Dann soll er anordnen, den einen Vogel über einem Tongefäß mit
Quellwasser zu schlachten.

<<v6>>
6 Den lebenden Vogel, das Zedernholz, das Karmesin und den Ysop soll er
nehmen und alles, auch den lebenden Vogel, in das Blut des über dem
Quellwasser geschlachteten Vogels tauchen.

<<v7>>
7 Nun soll er den, der sich der Reinigung vom Aussatz unterzieht,
siebenmal besprengen und, nachdem er ihn für rein erklärt hat, den
lebenden Vogel ins freie Feld fliegen lassen.

<<v8>>
8 Der sich der Reinigung unterzieht, der soll seine Kleider waschen,
sein ganzes Haar scheren, sich in Wasser baden und dann rein sein.
Nachher darf er ins Lager kommen, muss aber noch sieben Tage außerhalb
seines Zeltes bleiben.

<<v9>>
9 Am siebten Tag soll er sein ganzes Haar scheren, die Kopfhaare, den
Bart und die Augenbrauen; alle Haare muss er scheren. Nachdem er seine
Kleider gewaschen und seinen Körper in Wasser gebadet hat, ist er rein.

<<v10>>
10 Am achten Tag soll er zwei fehlerlose Widder, ein einjähriges
fehlerloses Schaf, drei Zehntel Efa Speiseopfermehl, das mit Öl vermengt
ist, und ein Log Öl nehmen.

<<v11>>
11 Der Priester, der die Reinigung vornimmt, soll den, der sich der
Reinigung unterzieht, mit seinen Opfergaben am Eingang des
Offenbarungszeltes vor dem Herrn aufstellen.

<<v12>>
12 Dann soll er den einen Widder nehmen, ihn zusammen mit dem Log Öl als
Schuldopfer darbringen und mit beiden den Darbringungsritus vor dem
Herrn vollziehen.

<<v13>>
13 Er soll den Widder an der Stelle schlachten, wo man das Sünd- und das
Brandopfer schlachtet, an dem heiligen Ort. Dieses Schuldopfer nämlich
gehört wie ein Sündopfer dem Priester, es ist etwas Hochheiliges.

<<v14>>
14 Der Priester soll etwas Blut vom Schlachtopfer nehmen und es auf das
rechte Ohrläppchen dessen tun, der sich der Reinigung unterzieht, und
auf den Daumen seiner rechten Hand und auf die große Zehe seines rechten
Fußes. [fn:1]

<<v15>>
15 Dann soll er etwas von dem Log Öl nehmen und auf seinen eigenen
linken Handteller gießen.

<<v16>>
16 Er soll einen Finger seiner rechten Hand in das Öl, das auf seinem
linken Handteller ist, tauchen und mit diesem Finger siebenmal Öl vor
dem Herrn verspritzen.

<<v17>>
17 Dann soll er etwas von dem auf seinem Handteller übrig gebliebenen Öl
auf das rechte Ohrläppchen dessen tun, der sich der Reinigung
unterzieht, auf den Daumen seiner rechten Hand und auf die große Zehe
seines rechten Fußes, auf das Blut des Schuldopfers.

<<v18>>
18 Den Rest des Öls, das er auf seinem Handteller hat, soll er auf den
Kopf dessen tun, der sich der Reinigung unterzieht. So soll er ihn vor
dem Herrn entsühnen.

<<v19>>
19 Nun soll der Priester das Sündopfer durchführen und den, der sich der
Reinigung unterzieht, von seiner Unreinheit entsühnen. Danach soll er
das Brandopfer schlachten

<<v20>>
20 und dieses und das Speiseopfer auf dem Altar als Ganzopfer
darbringen. Hat der Priester den betreffenden Menschen entsühnt, so ist
er rein.

<<v21>>
21 Wenn er arm ist und seine Mittel nicht ausreichen, soll der Priester
einen einzigen Schuldopferwidder für den Darbringungsritus nehmen, um
ihn zu entsühnen. Er soll nur ein Zehntel Efa Feinmehl, das mit Öl
vermengt ist, und ein Log Öl als Speiseopfer nehmen,

<<v22>>
22 und je nachdem es seine Mittel gestatten, soll er zwei Turteltauben
oder zwei junge Tauben bringen, von denen die eine als Sündopfer und die
andere als Brandopfer dienen soll.

<<v23>>
23 Er soll sie am achten Tag zu seiner Reinigung dem Priester zum
Eingang des Offenbarungszeltes vor den Herrn bringen.

<<v24>>
24 Der Priester soll den Schuldopferwidder und das Log Öl nehmen und
damit den Darbringungsritus vor dem Herrn vollziehen.

<<v25>>
25 Hat er diesen Schuldopferwidder geschlachtet, dann nehme er etwas
Blut vom Schuldopfer und tue es auf das rechte Ohrläppchen dessen, der
sich der Reinigung unterzieht, auf den Daumen seiner rechten Hand und
auf die große Zehe seines rechten Fußes.

<<v26>>
26 Er soll etwas Öl auf seinen linken Handteller gießen

<<v27>>
27 und etwas von diesem Öl, das auf seinem linken Handteller ist, mit
seinem rechten Zeigefinger siebenmal vor dem Herrn verspritzen.

<<v28>>
28 Dann soll er etwas von dem Öl, das auf seinem Handteller ist, auf das
rechte Ohrläppchen dessen, der sich der Reinigung unterzieht, auf den
Daumen seiner rechten Hand und auf die große Zehe seines rechten Fußes
tun, und zwar auf die Stelle des Schuldopferblutes.

<<v29>>
29 Den Rest des Öls auf seinem Handteller soll der Priester auf den Kopf
dessen tun, der sich der Reinigung unterzieht. So soll er ihn vor dem
Herrn entsühnen.

<<v30>>
30 Seinen Mitteln entsprechend soll er die eine der beiden Turteltauben
oder jungen Tauben

<<v31>>
31 als ein Sündopfer und die andere als ein Brandopfer mit einem
Speiseopfer verwenden. Der Priester soll damit den, der sich der
Reinigung unterzieht, vor dem Herrn entsühnen.

<<v32>>
32 Das ist das Gesetz für einen, der vom Aussatz befallen ist und dessen
Mittel für seine Reinigung nicht ausreichen.\\
\\

<<v33>>
* Der Aussatz an Häusern: 14,33-57

33 Der Herr sprach zu Mose und Aaron: [fn:2]

<<v34>>
34 Wenn ihr in das Land Kanaan kommt, das ich euch zum Besitz gebe, und
ich lasse an einem Haus des Landes, das ihr besitzen werdet, Aussatz
auftreten,

<<v35>>
35 so soll der Hausherr kommen, es dem Priester anzeigen und sagen: Ich
habe an meinem Haus so etwas wie Aussatz gesehen.

<<v36>>
36 Der Priester soll anordnen, dass man das Haus räumt, bevor er kommt,
um das Übel zu untersuchen; auf diese Weise wird das, was sich im Haus
befindet, nicht unrein. Danach erst soll der Priester kommen, um das
Haus zu besichtigen.

<<v37>>
37 Stellt er dabei fest, dass sich an den Mauern des Hauses grünlich
gelbe oder rötliche Vertiefungen zeigen, die Mulden in der Mauer bilden,

<<v38>>
38 so soll der Priester aus dem Haus hinausgehen und den Eingang für
sieben Tage abschließen.

<<v39>>
39 Am siebten Tag soll er wiederkommen. Stellt er bei der Besichtigung
fest, dass sich das Übel an den Hausmauern ausgebreitet hat,

<<v40>>
40 so ordne er an, die Steine, die vom Übel befallen sind,
herauszureißen und sie vor die Stadt hinaus an einen unreinen Ort zu
werfen.

<<v41>>
41 Dann soll er die Innenwände des Hauses abkratzen lassen und man soll
den so entfernten Mörtel aus der Stadt hinausschaffen und an einen
unreinen Ort schütten.

<<v42>>
42 Man soll andere Steine nehmen, um die herausgerissenen zu ersetzen,
und das Haus mit frischem Mörtel bestreichen.

<<v43>>
43 Hat man die Steine entfernt, das Haus abgekratzt und neu verputzt und
das Übel bricht wieder aus,

<<v44>>
44 soll der Priester kommen, um es zu besichtigen. Stellt er fest, dass
sich das Übel an dem Haus ausgebreitet hat, so ist bösartiger Aussatz an
dem Haus; es ist unrein.

<<v45>>
45 Man soll es niederreißen und seine Steine, seine Balken und seinen
ganzen Mörtelverputz vor die Stadt hinausbringen an einen unreinen Ort.

<<v46>>
46 Jeder, der das Haus während der Tage, an denen es durch den Priester
verschlossen war, betreten hat, ist unrein bis zum Abend.

<<v47>>
47 Wer im Haus geschlafen hat, muss seine Kleider waschen; wer im Haus
gegessen hat, muss seine Kleider waschen.

<<v48>>
48 Kommt aber der Priester, um das Übel zu besichtigen, und stellt fest,
dass sich das Übel, nachdem das Haus neu verputzt wurde, nicht
ausgebreitet hat, soll er das Haus für rein erklären, denn das Übel ist
abgeheilt.

<<v49>>
49 Um das Haus zu entsündigen, soll er zwei Vögel, Zedernholz, Karmesin
und Ysop nehmen.

<<v50>>
50 Er soll einen der Vögel über einem Tongefäß mit Quellwasser
schlachten.

<<v51>>
51 Dann soll er das Zedernholz, den Ysop, das Karmesin und den lebenden
Vogel nehmen, um sie in das Blut des geschlachteten Vogels und in das
Quellwasser zu tauchen. Er soll das Haus siebenmal besprengen und,

<<v52>>
52 nachdem er das Haus mit dem Blut des Vogels, dem Quellwasser, dem
lebenden Vogel, dem Zedernholz, dem Ysop und dem Karmesin entsündigt
hat,

<<v53>>
53 den lebenden Vogel aus der Stadt hinaus ins freie Feld fliegen
lassen. So entsühnt er das Haus und es ist wieder rein.

<<v54>>
54 Das ist das Gesetz für alle Fälle von Aussatz und Flechte,

<<v55>>
55 von Aussatz an Kleidern und Häusern,

<<v56>>
56 von Geschwülsten, Ausschlag und hellen Flecken,

<<v57>>
57 zur Unterweisung, wann etwas unrein oder rein ist. Das ist das Gesetz
über den Aussatz.\\
\\


* Footnotes

[fn:1] 8,23 [[file:Lev_8.org::v23][Lev 8,23]]; Ex 29,20 [[file:Ex_29.org::v20][Ex 29,20]]

[fn:2] 33-57: Ähnliches wie zum Aussatz an Kleidern ist zum
Aussatz an Häusern zu sagen (vgl. die Anmerkung zu 13,47-59 [[file:Lev_13.org::v47][Lev 13,47-59]]).
