#+TITLE: Lev 21 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 21:29]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Lev 21.html

<<verses>>


* Vorschriften für Priester: 21,1-24
   
* Das Verhalten beim Begräbnis von Verwandten: 21,1-6
<<v1>>   
1 Der Herr sprach zu Mose: Rede zu den Priestern, den Söhnen Aarons, und
sag zu ihnen: Keiner von ihnen darf sich an der Leiche eines seiner
Stammesgenossen verunreinigen,

<<v2>>
2 außer an seinen nächsten Verwandten: seiner Mutter, seinem Vater,
seinem Sohn, seiner Tochter oder seinem Bruder.

<<v3>>
3 An seiner unverheirateten Schwester, die seine nahe Verwandte blieb,
da sie keinem Mann angehörte, darf er unrein werden.

<<v4>>
4 Nicht aber darf er an seiner Schwester, die mit einem Stammesgenossen
verheiratet ist, unrein werden; er würde sich entweihen.

<<v5>>
5 Die Priester sollen sich auf ihrem Kopf keine Glatze scheren, ihren
Bart nicht stutzen und an ihrem Körper keine Einschnitte machen.

<<v6>>
6 Sie sollen ihrem Gott geheiligt sein und den Namen ihres Gottes nicht
entweihen. Denn sie sind es, die die Feueropfer des Herrn, die Speise
ihres Gottes, darbringen; darum sollen sie heilig sein.\\
\\

<<v7>>
* Ehehindernisse für Priester: 21,7-8

7 Sie dürfen weder eine Dirne, noch eine Entehrte, noch eine Frau
heiraten, die ihr Mann verstoßen hat; denn der Priester ist seinem Gott
geweiht.

<<v8>>
8 Du sollst ihn heilig halten, denn er bringt die Speise deines Gottes
dar. Heilig soll er dir sein, denn ich bin heilig, der Herr, der euch
heiligt.\\
\\

<<v9>>
* Die Strafe für unzüchtige Priestertöchter: 21,9

9 Wenn sich die Tochter eines Priesters als Dirne entweiht, so entweiht
sie ihren Vater; sie soll im Feuer verbrannt werden.\\
\\

<<v10>>
* Das Verhalten des Hohenpriesters bei Todesfällen: 21,10-12

10 Der Priester, der unter seinen Brüdern den höchsten Rang einnimmt,
auf dessen Haupt das Salböl ausgegossen wurde und der durch das Anlegen
der heiligen Gewänder eingesetzt ist, soll sein Haar nicht lose
herunterhängen lassen, seine Kleider nicht zerreißen,

<<v11>>
11 sich an keinem Leichnam verunreinigen, auch nicht, wenn es sich um
Vater oder Mutter handelt.

<<v12>>
12 Er soll sich nicht vom Heiligtum entfernen, um nicht das Heiligtum
seines Gottes zu entweihen; denn die Weihe des Salböls seines Gottes ist
auf ihm. Ich bin der Herr.\\
\\

<<v13>>
* Ehehindernisse für den Hohenpriester: 21,13-15

13 Er soll nur eine Jungfrau heiraten.

<<v14>>
14 Eine Witwe, eine Verstoßene oder eine Entehrte, eine Dirne, darf er
nicht heiraten; nur eine Jungfrau aus seinem Stamm darf er zur Frau
nehmen;

<<v15>>
15 sonst würde er seine Nachkommenschaft unter seinen Stammesgenossen
entweihen; denn ich, der Herr, bin es, der ihn heiligt.\\
\\

<<v16>>
* Die körperliche Tauglichkeit für das Priesteramt: 21,16-23

16 Der Herr sprach zu Mose:

<<v17>>
17 Sag zu Aaron: Keiner deiner Nachkommen, auch in den kommenden
Generationen, der ein Gebrechen hat, darf herantreten, um die Speise
seines Gottes darzubringen.

<<v18>>
18 Denn keiner mit einem Gebrechen darf herantreten: kein Blinder oder
Lahmer, kein im Gesicht oder am Körper Entstellter,

<<v19>>
19 kein Mann, der einen gebrochenen Fuß oder eine gebrochene Hand hat,

<<v20>>
20 keiner mit Buckel, Muskelschwund, Augenstar, Krätze, Flechte oder
Hodenquetschung.

<<v21>>
21 Keiner der Nachkommen Aarons, des Priesters, darf herantreten, um die
Feueropfer des Herrn darzubringen, wenn er ein Gebrechen hat. Er hat ein
Gebrechen, er darf nicht herantreten, um die Speise seines Gottes
darzubringen.

<<v22>>
22 Doch darf er von der Speise seines Gottes, von den hochheiligen und
heiligen Dingen, essen, [fn:1]

<<v23>>
23 aber nicht zum Vorhang kommen und sich nicht dem Altar nähern; denn
er hat ein Gebrechen und darf meine heiligen Gegenstände nicht
entweihen; denn ich bin der Herr, der sie geheiligt hat.\\
\\

<<v24>>
* Schlussbemerkung: 21,24

24 Das sagte Mose zu Aaron, zu dessen Söhnen und zu allen Israeliten.\\
\\


* Footnotes

[fn:1] «Speise Gottes» ist das Opfer; im AT wird aber nirgends
angenommen, dass Gott die Opferspeise genießt oder ihrer bedarf (vgl. Ps
50,8-13 [[file:Ps_50.org::v8][Ps 50,8-13]]). 
