#+TITLE: Lev 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 15:12]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Lev 17.html


<<verses>>

<<v1>>
* Das Heiligkeitsgesetz: 17,1 - 26,46

* Schlachtungen und Blutgenuss: 17,1-16

1 Der Herr sprach zu Mose: [fn:1]

<<v2>>
2 Rede zu Aaron, seinen Söhnen und allen Israeliten und sag zu ihnen:
Das ist es, worauf der Herr euch verpflichtet hat:

<<v3>>
3 Jeder Mann aus dem Haus Israel, der innerhalb oder außerhalb des
Lagers ein Rind, ein Schaf oder eine Ziege schlachtet

<<v4>>
4 und das Tier nicht zum Eingang des Offenbarungszeltes bringt, um es
dem Herrn vor seiner Wohnstätte zu opfern, dem soll es als Blutschuld
angerechnet werden; er hat Blut vergossen und soll aus der Mitte seines
Volkes ausgemerzt werden.

<<v5>>
5 Daher sollen die Israeliten die Opfer, die sie (jetzt noch) auf dem
freien Feld schlachten, dem Priester für den Herrn zum Eingang des
Offenbarungszeltes bringen und sie als Heilsopfer für den Herrn
schlachten. [fn:2]

<<v6>>
6 Der Priester soll das Blut auf den Altar des Herrn am Eingang des
Offenbarungszeltes gießen und das Fett zum beruhigenden Duft für den
Herrn in Rauch aufgehen lassen.

<<v7>>
7 Sie sollen nicht mehr ihre Schlachtopfer für Bocksdämonen schlachten,
mit denen sie Unzucht treiben. Das gelte ihnen und ihren kommenden
Generationen als feste Regel.

<<v8>>
8 Du sollst ihnen weiter sagen: Jeder Mann aus dem Haus Israel oder
jeder Fremde in eurer Mitte, der ein Brand- oder Schlachtopfer
darbringt,

<<v9>>
9 ohne es zum Eingang des Offenbarungszeltes zu bringen, um es für den
Herrn zu vollziehen, soll aus seinen Stammesgenossen ausgemerzt werden.

<<v10>>
10 Jeder Mann aus dem Haus Israel oder jeder Fremde in eurer Mitte, der
irgendwie Blut genießt, gegen einen solchen werde ich mein Angesicht
wenden und ihn aus der Mitte seines Volkes ausmerzen.

<<v11>>
11 Die Lebenskraft des Fleisches sitzt nämlich im Blut. Dieses Blut habe
ich euch gegeben, damit ihr auf dem Altar für euer Leben die Sühne
vollzieht; denn das Blut ist es, das für ein Leben sühnt. [fn:3]

<<v12>>
12 Deshalb habe ich zu den Israeliten gesagt: Niemand unter euch darf
Blut genießen, auch der Fremde, der in eurer Mitte lebt, darf kein Blut
genießen.

<<v13>>
13 Jeder unter den Israeliten oder der Fremde in eurer Mitte, der Wild
oder für den Genuss erlaubte Vögel erlegt, muss das Blut ausfließen
lassen und es mit Erde bedecken.

<<v14>>
14 Denn das Leben aller Wesen aus Fleisch ist das Blut, das darin ist.
Ich habe zu den Israeliten gesagt: Das Blut irgendeines Wesens aus
Fleisch dürft ihr nicht genießen; denn das Leben aller Wesen aus Fleisch
ist ihr Blut. Jeder, der es genießt, soll ausgemerzt werden.

<<v15>>
15 Jeder, sei er einheimisch oder fremd, der ein verendetes oder
zerrissenes Tier isst, muss seine Kleider waschen, sich in Wasser baden
und ist unrein bis zum Abend; dann ist er rein. [fn:4]

<<v16>>
16 Wer seine Kleider nicht wäscht und seinen Körper nicht in Wasser
badet, muss die Folgen seiner Schuld tragen.\\
\\


* Footnotes

[fn:1] 1-16: Dieser Text scheint zu fordern, dass die
Schlachtung eines Tiers nur am Heiligtum geschehen darf, und zwar in
Verbindung mit einem Opfer, wobei zumindest das Fett und das Blut Gott
gehören. Ein solches Gesetz wäre nur denkbar zur Zeit der
Wüstenwanderung, wie sie sich die Priestertradition vorstellt. In
Palästina nach der Sesshaftwerdung wäre es nicht durchführbar gewesen.
Vielleicht meint aber 17,1-9 nur, dass man nirgends als nur am Heiligtum
Schlachtopfer darbringen darf. So ist jedenfalls Dtn 12 gemeint, wo
ausdrücklich festgestellt wird, dass man überall einfache Schlachtungen
vornehmen darf, wenn man nur das Blut nicht genießt, sondern zur Erde
rinnen lässt und mit Erde bedeckt. Auch in Lev 17 wird der Blutgenuss
ausdrücklich verboten. Das Verbot wird in V. 11 damit begründet, dass
das Blut Sitz des Lebens und von Gott dazu vorgesehen ist, beim
Sühnopfer als Ersatz für das durch die Sünde verwirkte Blut des Sünders
zu dienen.

[fn:2] 3,1-17 [[file:Lev_3.org::v1][Lev 3,1-17]]

[fn:3] Gen 9,4 [[file:Gen_9.org::v4][Gen 9,4]]; Dtn 12,23 [[file:Dtn_12.org::v23][Dtn 12,23]]

[fn:4] 11,40 [[file:Lev_11.org::v40][Lev 11,40]]; Ex 22,30 [[file:Ex_22.org::v30][Ex 22,30]]
