#+TITLE: Lev 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 15:15]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Lev 18.html


<<verses>>

<<v1>>
* Sexuelle Vorschriften: 18,1-30

* Einleitung: 18,1-5

1 Der Herr sprach zu Mose:

<<v2>>
2 Rede zu den Israeliten und sag zu ihnen: Ich bin der Herr, euer Gott.

<<v3>>
3 Ihr sollt nicht tun, was man in Ägypten tut, wo ihr gewohnt habt; ihr
sollt nicht tun, was man in Kanaan tut, wohin ich euch führe. Ihre
Bräuche sollt ihr nicht befolgen.

<<v4>>
4 Meine Vorschriften sollt ihr einhalten und meine Satzungen sollt ihr
beachten und befolgen. Ich bin der Herr, euer Gott.

<<v5>>
5 Ihr sollt auf meine Satzungen und meine Vorschriften achten. Wer sie
einhält, wird durch sie leben. Ich bin der Herr.\\
\\

<<v6>>
* Unzucht unter Verwandten: 18,6-18

6 Niemand von euch darf sich einer Blutsverwandten nähern, um ihre Scham
zu entblößen. Ich bin der Herr.

<<v7>>
7 Die Scham deines Vaters, nämlich die Scham deiner Mutter, darfst du
nicht entblößen. Sie ist deine Mutter, du darfst ihre Scham nicht
entblößen.

<<v8>>
8 Die Scham der Frau deines Vaters darfst du nicht entblößen; sie ist
die Scham deines Vaters.

<<v9>>
9 Die Scham deiner Schwester, einer Tochter deines Vaters oder einer
Tochter deiner Mutter, darfst du nicht entblößen, sei sie im Haus oder
außerhalb geboren.

<<v10>>
10 Die Scham einer Tochter deines Sohnes oder einer Tochter deiner
Tochter darfst du nicht entblößen; denn ihre Scham ist deine eigene
Scham.

<<v11>>
11 Die Scham der Tochter einer Frau deines Vaters darfst du nicht
entblößen. Sie ist deinem Vater geboren, also deine Schwester; du darfst
ihre Scham nicht entblößen.

<<v12>>
12 Die Scham einer Schwester deines Vaters darfst du nicht entblößen;
denn sie ist mit deinem Vater leiblich verwandt.

<<v13>>
13 Die Scham der Schwester deiner Mutter darfst du nicht entblößen; denn
sie ist mit deiner Mutter leiblich verwandt.

<<v14>>
14 Die Scham des Bruders deines Vaters darfst du nicht entblößen; du
darfst dich seiner Frau nicht nähern; denn sie ist deine Tante.

<<v15>>
15 Die Scham deiner Schwiegertochter darfst du nicht entblößen. Sie ist
die Frau deines Sohnes; du darfst ihre Scham nicht entblößen.

<<v16>>
16 Die Scham der Frau deines Bruders darfst du nicht entblößen; denn sie
ist die Scham deines Bruders.

<<v17>>
17 Die Scham einer Frau und gleichzeitig die ihrer Tochter darfst du
nicht entblößen; weder die Tochter ihres Sohnes noch die Tochter ihrer
Tochter darfst du nehmen, um ihre Scham zu entblößen. Sie sind leiblich
verwandt, es wäre Blutschande.

<<v18>>
18 Du darfst neben einer Frau nicht auch noch deren Schwester heiraten;
du würdest sie zur Nebenbuhlerin machen, wenn du zu Lebzeiten der Frau
die Scham ihrer Schwester entblößt.\\
\\

<<v19>>
* Andere Unzuchtvergehen: 18,19-23

19 Einer Frau, die wegen ihrer Regel unrein ist, darfst du dich nicht
nähern, um ihre Scham zu entblößen.

<<v20>>
20 Der Frau deines Stammesgenossen darfst du nicht beiwohnen; du würdest
dadurch unrein.

<<v21>>
21 Von deinen Nachkommen darfst du keinen für Moloch darbringen. Du
darfst den Namen deines Gottes nicht entweihen. Ich bin der Herr. [fn:1] [fn:2]

<<v22>>
22 Du darfst nicht mit einem Mann schlafen, wie man mit einer Frau
schläft; das wäre ein Gräuel.

<<v23>>
23 Keinem Vieh darfst du beiwohnen; du würdest dadurch unrein. Keine
Frau darf vor ein Vieh hintreten, um sich mit ihm zu begatten; das wäre
eine schandbare Tat.\\
\\

<<v24>>
* Schlussmahnung: 18,24-30

24 Ihr sollt euch nicht durch all das verunreinigen; denn durch all das
haben sich die Völker verunreinigt, die ich vor euch vertrieben habe.

<<v25>>
25 Das Land wurde unrein, ich habe an ihm seine Schuld geahndet und das
Land hat seine Bewohner ausgespien.

<<v26>>
26 Ihr aber sollt auf meine Satzungen und Vorschriften achten und keine
dieser Gräueltaten begehen, weder der Einheimische noch der Fremde, der
in eurer Mitte lebt.

<<v27>>
27 Denn all diese Gräueltaten haben die Leute begangen, die vor euch im
Land waren, und so wurde das Land unrein.

<<v28>>
28 Wird es etwa euch, wenn ihr es verunreinigt, nicht ebenso ausspeien,
wie es das Volk vor euch ausgespien hat?

<<v29>>
29 Alle nämlich, die irgendeine dieser Gräueltaten begehen, werden aus
der Mitte ihres Volkes ausgemerzt.

<<v30>>
30 Achtet auf meine Anordnungen, befolgt keinen von den gräulichen
Bräuchen, die man vor euch befolgt hat, und verunreinigt euch nicht
durch sie. Ich bin der Herr, euer Gott.\\
\\


* Footnotes

[fn:1] 20,2-5 [[file:Lev_20.org::v2][Lev 20,2-5]]

[fn:2] Kinderopfer waren in außerordentlichen Notsituationen
bei den Kanaanitern üblich (vgl. die Anmerkung zu Gen 22,1-19). Moloch
bedeutet eigentlich «König» und ist ein entstellter Beiname für Baal.
Nach 2 Kön 23,10 [[file:2.Kön_23.org::v10][2 Kön 23,10]]; Jer 32,35 [[file:Jer_32.org::v35][Jer 32,35]]; Ez 16,20-22 [[file:Ez_16.org::v20][Ez 16,20-22]]
ist das Kinderopfer für Moloch zur Königszeit auch in Israel und Juda geübt worden, wobei man Kinder «durchs Feuer gehen ließ», d. h. verbrannte.
