#+TITLE: Lev 23 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-13 Fr 08:19]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Lev 23.html

<<verses>>

<<v1>>
* Festordnungen und Feiervorschriften: 23,1 - 24,23

* Einleitung: 23,1-2

1 Der Herr sprach zu Mose:

<<v2>>
2 Rede zu den Israeliten und sag zu ihnen: Die Feste des Herrn, die ihr
als Tage heiliger Versammlung ausrufen sollt, sind folgende:\\
\\

<<v3>>
* Der Sabbat: 23,3

3 Sechs Tage soll man arbeiten, aber am siebten Tag ist vollständiger
Ruhetag, ein Tag heiliger Versammlung, an dem ihr keinerlei Arbeit
verrichten dürft. Es ist ein Feiertag zur Ehre des Herrn überall, wo ihr
wohnt. [fn:1]\\
\\

<<v4>>
* Das Pascha und das Fest der ungesäuerten Brote: 23,4-8

4 Das sind die Feste des Herrn, Tage heiliger Versammlungen, die ihr zur
festgesetzten Zeit ausrufen sollt: [fn:2]

<<v5>>
5 Im ersten Monat, am vierzehnten Tag des Monats, zur Abenddämmerung,
ist Pascha zur Ehre des Herrn. [fn:3]

<<v6>>
6 Am fünfzehnten Tag dieses Monats ist das Fest der ungesäuerten Brote
zur Ehre des Herrn. Sieben Tage sollt ihr ungesäuertes Brot essen. [fn:4]

<<v7>>
7 Am ersten Tag habt ihr heilige Versammlung; ihr dürft keine schwere
Arbeit verrichten.

<<v8>>
8 Sieben Tage hindurch sollt ihr ein Feueropfer für den Herrn
darbringen. Am siebten Tag ist heilige Versammlung; da dürft ihr keine
schwere Arbeit verrichten.\\
\\

<<v9>>
* Die Erstlingsfrüchte: 23,9-14

9 Der Herr sprach zu Mose:

<<v10>>
10 Rede zu den Israeliten und sag zu ihnen: Wenn ihr in das Land kommt,
das ich euch gebe, und wenn ihr dort die Ernte einbringt, sollt ihr dem
Priester die erste Garbe eurer Ernte bringen.

<<v11>>
11 Er soll sie vor dem Herrn hin- und herschwingen und sie so
darbringen, damit ihr Annahme findet. Am Tag nach dem Sabbat soll der
Priester den Ritus ausführen.

<<v12>>
12 Am Tag, an dem ihr die Garbe darbringt, sollt ihr dem Herrn auch ein
fehlerloses einjähriges Schaf als Brandopfer herrichten,

<<v13>>
13 dazu als Speiseopfer zwei Zehntel Feinmehl, das mit Öl vermengt ist.
Das Ganze soll ein Feueropfer für den Herrn zum beruhigenden Duft sein;
dazu kommt ein viertel Hin Wein als Trankopfer.

<<v14>>
14 Vor diesem Tag, bevor ihr eurem Gott die Opfergabe gebracht habt,
dürft ihr kein Brot und kein geröstetes oder frisches Korn essen. Das
gelte als feste Regel bei euch von Generation zu Generation überall, wo
ihr wohnt.\\
\\

<<v15>>
* Das Wochenfest (Pfingstfest): 23,15-22

15 Vom Tag nach dem Sabbat, an dem ihr die Garbe für die Darbringung
gebracht habt, sollt ihr sieben volle Wochen zählen. [fn:5]

<<v16>>
16 Zählt fünfzig Tage bis zum Tag nach dem siebten Sabbat, und dann
bringt dem Herrn ein neues Speiseopfer dar!

<<v17>>
17 Bringt als Erstlingsgaben für den Herrn aus euren Wohnsitzen zwei
Brote dar, gebacken aus zwei zehntel Efa Feinmehl mit Sauerteig.

<<v18>>
18 Zum Brot bringt sieben fehlerlose einjährige Lämmer, einen Jungstier
und zwei Widder als Brandopfer für den Herrn dar, dazu das Speiseopfer
sowie das Trankopfer als ein Feueropfer zum beruhigenden Duft für den
Herrn.

<<v19>>
19 Bereitet auch einen Ziegenbock als Sündopfer und zwei einjährige
Lämmer als Heilsopfer zu!

<<v20>>
20 Der Priester soll sie, zusammen mit dem Brot der Erstlingsgaben, vor
dem Herrn hin- und herschwingen und sie so darbringen; sie sind mit den
beiden Lämmern heilige Gaben für den Herrn, die dem Priester gehören.

<<v21>>
21 Am selben Tag ruft eine heilige Versammlung aus und haltet sie ab! Da
dürft ihr keine schwere Arbeit verrichten. Das gelte bei euch als feste
Regel von Generation zu Generation überall, wo ihr wohnt.

<<v22>>
22 Wenn ihr die Ernte eures Landes einbringt, sollst du dein Feld nicht
bis zum äußersten Rand abernten und keine Nachlese deiner Ernte halten.
Du sollst das dem Armen und dem Fremden überlassen. Ich bin der Herr,
euer Gott. [fn:6]\\
\\

<<v23>>
* Der Neujahrstag: 23,23-25

23 Der Herr sprach zu Mose:

<<v24>>
24 Sag zu den Israeliten: Im siebten Monat, am ersten Tag des Monats,
ist für euch Ruhetag, in Erinnerung gerufen durch Lärmblasen, eine
heilige Versammlung.

<<v25>>
25 Da dürft ihr keine schwere Arbeit verrichten und ihr sollt dem Herrn
ein Feueropfer darbringen.\\
\\

<<v26>>
* Das Versöhnungsfest: 23,26-32

26 Der Herr sprach zu Mose: [fn:7]

<<v27>>
27 Am zehnten Tag dieses siebten Monats ist der Versöhnungstag. Da sollt
ihr heilige Versammlung halten. Ihr sollt euch Enthaltung auferlegen und
dem Herrn ein Feueropfer darbringen.

<<v28>>
28 An ebendiesem Tag dürft ihr keinerlei Arbeit verrichten, denn es ist
der Versöhnungstag, an dem man euch vor dem Herrn, eurem Gott, entsühnt.

<<v29>>
29 Denn jede Person, die sich an diesem Tag nicht Enthaltung auferlegt,
soll aus ihren Stammesgenossen ausgemerzt werden.

<<v30>>
30 Wer an diesem Tag irgendeine Arbeit verrichtet, den werde ich aus der
Mitte seines Volkes austilgen.

<<v31>>
31 Ihr dürft keinerlei Arbeit tun. Das gelte bei euch als feste Regel
von Generation zu Generation überall, wo ihr wohnt.

<<v32>>
32 Dieser Tag ist für euch ein vollständiger Ruhetag. Ihr sollt euch
Enthaltung auferlegen. Vom Abend des neunten Tags in diesem Monat bis
zum folgenden Abend sollt ihr Ruhetag halten.\\
\\

<<v33>>
* Das Laubhüttenfest: 23,33-36

33 Der Herr sprach zu Mose:

<<v34>>
34 Sag zu den Israeliten: Am fünfzehnten Tag dieses siebten Monats ist
sieben Tage hindurch das Laubhüttenfest zur Ehre des Herrn. [fn:8]

<<v35>>
35 Am ersten Tag, einem Tag heiliger Versammlung, dürft ihr keine
schwere Arbeit verrichten.

<<v36>>
36 Sieben Tage hindurch sollt ihr ein Feueropfer für den Herrn
darbringen. Am achten Tag habt ihr heilige Versammlung und ihr sollt ein
Feueropfer für den Herrn darbringen. Es ist der Tag der Festversammlung;
da dürft ihr keine schwere Arbeit verrichten.\\
\\

<<v37>>
* Schlussbemerkung: 23,37-38

37 Das sind die Festzeiten des Herrn, die ihr als Tage heiliger
Versammlung ausrufen sollt, dazu bestimmt, für den Herrn Feueropfer,
Brandopfer, Speiseopfer, Schlachtopfer und Trankopfer darzubringen, dem
jeweiligen Tag entsprechend,

<<v38>>
38 abgesehen von den Sabbaten des Herrn und abgesehen von euren
Geschenken, den gelobten und freiwilligen Gaben, die ihr dem Herrn
gebt.\\
\\

<<v39>>
* Einzelbestimmung für das Laubhüttenfest: 23,39-44

39 Am fünfzehnten Tag des siebten Monats, wenn ihr den Ertrag des Landes
erntet, feiert sieben Tage lang das Fest des Herrn! Am ersten und am
achten Tag ist Ruhetag.

<<v40>>
40 Am ersten Tag nehmt schöne Baumfrüchte, Palmwedel, Zweige von dicht
belaubten Bäumen und von Bachweiden und seid sieben Tage lang vor dem
Herrn, eurem Gott, fröhlich!

<<v41>>
41 Feiert dieses Fest zur Ehre des Herrn jährlich sieben Tage lang! Das
gelte bei euch als feste Regel von Generation zu Generation. Ihr sollt
dieses Fest im siebten Monat feiern.

<<v42>>
42 Sieben Tage sollt ihr in Hütten wohnen. Alle Einheimischen in Israel
sollen in Hütten wohnen,

<<v43>>
43 damit eure kommenden Generationen wissen, dass ich die Israeliten in
Hütten wohnen ließ, als ich sie aus Ägypten herausführte. Ich bin der
Herr, euer Gott.

<<v44>>
44 Da teilte Mose den Israeliten die Festzeiten des Herrn mit.\\
\\


* Footnotes

[fn:1] Ex 20,8-11 [[file:Ex_20.org::v8][Ex 20,8-11]]; 31,12-17 [[file:Ex_31.org::v12][Ex 31,12-17]]; 35,2 [[file:Ex_35.org::v2][Ex 35,2]]; Dtn 5,12-15 [[file:Dtn_5.org::v12][Dtn 5,12-17]]

[fn:2] 4-8: Zum Pascha und Fest der ungesäuerten Brote vgl. die
Anmerkung zu Ex 12,1 - 13,16 [[file:Ex_12.org::v1][Ex 12,1]].

[fn:3] Ex 12,2-11 [[file:Ex_12.org::v2][Ex 12,2-11]]

[fn:4] 23,15 [[file:Lev_23.org::v15][Lev 23,15]]; Ex 34,18 [[file:Ex_34.org::v18][Ex 34,18]]

[fn:5] Ex 23,16 [[file:Ex_23.org::v16][Ex 23,16]]; 34,22 [[file:Ex_34.org::v22][Ex 34,22]]

[fn:6] 19,9f [[file:Lev_19.org::v9][Lev 19,9f]]

[fn:7] (26-32) 16,2-34 [[file:Lev_16.org::v2][Lev 16,2-34]]

[fn:8] Ex 23,16 [[file:Ex_23.org::16][Ex 23,16]]; 34,22 [[file:Ex_34.org::v22][Ex 34,22]]
