#+TITLE: Lev 27 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-13 Fr 10:05]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Lev 27.html

<<verses>>

<<v1>>
* Die Ablösung von Gelübden und Weihegaben: 27,1-34

* Bei Personen: 27,1-8

1 Der Herr sprach zu Mose: [fn:1]

<<v2>>
2 Rede zu den Israeliten und sag zu ihnen: Will jemand ein Gelübde für
den Herrn einlösen, das er nach dem üblichen Wert einer Person abgelegt
hat,

<<v3>>
3 so gilt für einen Mann zwischen zwanzig und sechzig Jahren ein
Schätzwert von fünfzig Silberschekel, nach dem Schekelgewicht des
Heiligtums,

<<v4>>
4 für eine Frau ein Schätzwert von dreißig Schekel,

<<v5>>
5 für einen Jugendlichen zwischen fünf und zwanzig Jahren, wenn es ein
Junge ist, ein Schätzwert von zwanzig Schekel, wenn es ein Mädchen ist,
ein Schätzwert von zehn Schekel,

<<v6>>
6 für einen Knaben zwischen einem Monat und fünf Jahren ein Schätzwert
von fünf und für ein Mädchen ein Schätzwert von drei Silberschekel,

<<v7>>
7 für einen Mann von sechzig und mehr Jahren ein Schätzwert von fünfzehn
und für eine Frau ein Schätzwert von zehn Schekel.

<<v8>>
8 Ist derjenige, der das Gelübde gemacht hat, nicht in der Lage, den
Schätzwert zu entrichten, dann soll er die Person dem Priester
vorstellen. Dieser soll den Schätzwert nach Maßgabe dessen, was der
Gelobende aufbringen kann, feststellen.\\
\\

<<v9>>
* Bei Tieren: 27,9-13

9 Handelt es sich um Tiere, die man für den Herrn als Opfergabe
darbringen kann, so wird jedes Tier, das man dem Herrn gibt, etwas
Heiliges.

<<v10>>
10 Man darf es weder auswechseln noch vertauschen, nicht ein gutes gegen
ein schlechtes oder ein schlechtes gegen ein gutes geben. Wenn man aber
doch ein Tier gegen ein anderes vertauscht, so wird sowohl das eine als
auch das andere etwas Heiliges.

<<v11>>
11 Handelt es sich um ein unreines Tier, von dem man keine Opfergabe für
den Herrn darbringen darf, soll man das Tier dem Priester vorführen,

<<v12>>
12 und dieser soll den Durchschnittswert feststellen; an seine Schätzung
soll man sich halten.

<<v13>>
13 Will man es auslösen, so soll man den Schätzwert um ein Fünftel
erhöhen. [fn:2]\\
\\

<<v14>>
* Bei Häusern: 27,14-15

14 Will man sein Haus dem Herrn weihen, so soll es der Priester
schätzen, indem er seinen Durchschnittswert feststellt. Man halte sich
an die Schätzung des Priesters.

<<v15>>
15 Will der Mann, der das Haus gelobt hat, es auslösen, so soll er ein
Fünftel des Geldes zum Schätzwert hinzufügen und es soll wieder ihm
gehören.\\
\\

<<v16>>
* Bei Grundstücken: 27,16-24

16 Weiht ein Mann eines von seinen Erbgrundstücken dem Herrn, so soll
der Schätzwert seines Saatgutes geschätzt werden. Ein Hómer Saatgerste
entspricht fünfzig Silberschekeln.

<<v17>>
17 Weiht jemand das Feld vom Jubeljahr an, so halte man sich an diesen
Schätzwert;

<<v18>>
18 weiht er es aber nach dem Jubeljahr, soll ihm der Priester den Preis
entsprechend der bis zum nächsten Jubeljahr ausstehenden Jahre berechnen
und vom Schätzwert abziehen.

<<v19>>
19 Will derjenige, der das Feld geweiht hat, es wieder auslösen, soll er
ein Fünftel des Geldes zum Schätzwert hinzufügen, und es soll wieder ihm
gehören.

<<v20>>
20 Löst er es nicht aus, verkauft es aber einem anderen, so kann es
nicht mehr ausgelöst werden,

<<v21>>
21 und das Feld wird, wenn es im Jubeljahr frei wird, etwas Heiliges für
den Herrn, wie ein Feld, das geweihtes Gut ist. Es wird Eigentum des
Priesters.

<<v22>>
22 Wenn jemand dem Herrn ein Feld weiht, das er erworben hat und das
nicht zu seinem Erbbesitz gehört,

<<v23>>
23 berechne der Priester den Schätzwert mit Rücksicht auf die Zeit bis
zum Jubeljahr und der Mann bezahle die Summe am selben Tag als etwas
Heiliges für den Herrn.

<<v24>>
24 Im Jubeljahr soll das Feld an den Verkäufer zurückfallen, dem es als
ererbter Landbesitz gehört. [fn:3]\\
\\

<<v25>>
* Das Maß der Schätzung: 27,25

25 Jede Schätzung bei dir soll nach dem Schekelgewicht des Heiligtums
erfolgen: Zwanzig Gera entsprechen einem Schekel.\\
\\

<<v26>>
* Sonderfälle: 27,26-33

26 Eine Erstgeburt beim Vieh, die als Erstlingsgabe dem Herrn gehört,
kann man nicht weihen, weder ein Rind noch ein Schaf; denn es gehört
schon dem Herrn.

<<v27>>
27 Aber wenn es die Erstgeburt eines unreinen Tiers ist, kann man es um
den um ein Fünftel erhöhten Schätzwert auslösen. Wird das Tier nicht
ausgelöst, soll es nach dem Schätzwert verkauft werden.

<<v28>>
28 Aber nichts von dem, was ein Mann von seinem Eigentum an Menschen,
Vieh und Feldbesitz als Banngut dem Herrn geweiht hat, darf verkauft
oder ausgelöst werden. Alles Banngut ist etwas Hochheiliges; es gehört
dem Herrn.

<<v29>>
29 Kein menschliches Wesen, das als Banngut geweiht wird, kann
zurückgekauft werden; man muss es töten.

<<v30>>
30 Jeder Zehnt des Landes, der vom Ertrag des Landes oder von den
Baumfrüchten abzuziehen ist, gehört dem Herrn; es ist etwas Heiliges für
den Herrn.

<<v31>>
31 Will ein Mann einen Teil seines Zehnten auslösen, muss er ein Fünftel
dazuzahlen.

<<v32>>
32 Jeder Zehnt an Rind, Schaf und Ziege ist dem Herrn geweiht, jedes
zehnte Stück von allem, was unter dem Hirtenstab hindurchgeht.

<<v33>>
33 Man soll nicht zwischen dem Guten und dem Schlechten unterscheiden
und keinen Tausch vornehmen. Wenn man es dennoch tut, werden das Tier
und das mit ihm vertauschte Tier etwas Heiliges; es darf nicht ausgelöst
werden.\\
\\

<<v34>>
* Abschluss: 27,34

34 Das sind die Gebote, die der Herr dem Mose für die Israeliten auf dem
Sinai gegeben hat.\\
\\


* Footnotes

[fn:1] 1-8: Diese Bestimmung geht vielleicht auf einen alten
Brauch zurück, Personen aus der eigenen Sippe aufgrund eines in
Notzeiten abgelegten Gelübdes dem Heiligtum zu weihen, d. h. zur
Dienstleistung zu übergeben (vgl. 1 Sam 1,11.23-28). Konnte man sich
später von der Person nicht trennen, musste man sie gegen Geld auslösen.

[fn:2] 13.15.27: Der Zuschlag von einem Fünftel zum Schätzwert
ist wohl als Buße für die Zurücknahme des Gelübdes gedacht.

[fn:3] 25,23-28 [[file:Lev_25.org::v23][Lev 25,23-28]]
