#+TITLE: Lev 24 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-13 Fr 08:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Lev 24.html

<<verses>>

<<v1>>
* Einzelbestimmungen über den Leuchter und den Tisch für die Schaubrote: 24,1-9

1 Der Herr sprach zu Mose:

<<v2>>
2 Befiehl den Israeliten, dass sie dir für den Leuchter reines Öl aus
zerstoßenen Oliven bringen, damit man ständig eine Lampe brennen lassen
kann. [fn:1]

<<v3>>
3 Im Offenbarungszelt, vor dem Vorhang der Lade, soll Aaron diese Lampe
aufstellen. Sie soll hier vor dem Herrn ständig vom Abend bis zum Morgen
brennen. Das gelte bei euch als feste Regel von Generation zu
Generation.

<<v4>>
4 Aaron soll die Lampen auf dem Leuchter aus reinem Gold vor dem Herrn
ständig in Ordnung halten.

<<v5>>
5 Du sollst Feinmehl nehmen und daraus zwölf Kuchen backen; aus zwei
zehntel Efa Feinmehl soll jeder einzelne Kuchen zubereitet sein. [fn:2]

<<v6>>
6 Dann sollst du sie in zwei Schichten, sechs in jeder Schicht, auf den
Tisch aus reinem Gold vor den Herrn legen.

<<v7>>
7 Auf jede Schicht sollst du reinen Weihrauch tun; er soll der
Gedächtnisanteil des Brotes sein, ein Feueropfer für den Herrn.

<<v8>>
8 Sabbat für Sabbat soll man die Brote vor dem Herrn zurichten als
dauernde Bundesleistung von Seiten der Israeliten.

<<v9>>
9 Sie gehören Aaron und seinen Söhnen, die sie an einem heiligen Ort
essen sollen; denn sie sind für ihn etwas Hochheiliges, ein dauerndes
Anrecht von den Feueropfern des Herrn.\\
\\

<<v10>>
* Einschub: Die Lästerung des Gottesnamens: 24,10-23

10 Der Sohn einer Israelitin und eines Ägypters ging unter die
Israeliten. Im Lager geriet er in Streit mit einem Mann, der Israelit
war.

<<v11>>
11 Der Sohn der Israelitin schmähte den Gottesnamen und fluchte. Da
brachten sie ihn zu Mose. Der Name der Mutter war Schelomit; sie war die
Tochter Dibris aus dem Stamm Dan.

<<v12>>
12 Man nahm ihn in Gewahrsam, um auf einen Spruch des Herrn hin zu
entscheiden.

<<v13>>
13 Der Herr sprach zu Mose:

<<v14>>
14 Lass den, der den Fluch ausgesprochen hat, aus dem Lager
hinausführen! Alle, die es gehört haben, sollen ihm ihre Hände auf den
Kopf legen; dann soll ihn die ganze Gemeinde steinigen.

<<v15>>
15 Sag den Israeliten: Jeder, der seinem Gott flucht, muss die Folgen
seiner Sünde tragen. [fn:3]

<<v16>>
16 Wer den Namen des Herrn schmäht, wird mit dem Tod bestraft; die ganze
Gemeinde soll ihn steinigen. Der Fremde muss ebenso wie der Einheimische
getötet werden, wenn er den Gottesnamen schmäht.

<<v17>>
17 Wer einen Menschen erschlägt, wird mit dem Tod bestraft. [fn:4]

<<v18>>
18 Wer ein Stück Vieh erschlägt, muss es ersetzen: Leben für Leben.

<<v19>>
19 Wenn jemand einen Stammesgenossen verletzt, soll man ihm antun, was
er getan hat:

<<v20>>
20 Bruch um Bruch, Auge um Auge, Zahn um Zahn. Der Schaden, den er einem
Menschen zugefügt hat, soll ihm zugefügt werden. [fn:5]

<<v21>>
21 Wer ein Stück Vieh erschlägt, muss es ersetzen; wer aber einen
Menschen erschlägt, wird mit dem Tod bestraft.

<<v22>>
22 Gleiches Recht soll bei euch für den Fremden wie für den
Einheimischen gelten; denn ich bin der Herr, euer Gott.

<<v23>>
23 Nachdem Mose so zu den Israeliten gesprochen hatte, führten sie den,
der den Fluch ausgesprochen hatte, aus dem Lager hinaus und steinigten
ihn. So erfüllten sie, was der Herr dem Mose aufgetragen hatte.\\
\\


* Footnotes

[fn:1] (2-4) Ex 25,31-40 [[file:Ex_25.org::v31][Ex 25,31-40]]

[fn:2] Die zwölf Kuchen werden in Ex 25,30 und 1 Sam 21,7
«Schaubrote» (wörtlich: Brote des Angesichts) genannt, wahrscheinlich in
dem Sinn, dass Gott sie anschaut und als Zeichen des Dankes Israels
gnädig annimmt.

[fn:3] Ex 20,7 [[file:Ex_20.org::v7][Ex 20,7]]; 22,27 [[file:Ex_22.org::v27][Ex 22,27]]

[fn:4] Ex 20,13 [[file:Ex_20.org::v13][Ex 20,13]]; 21,12-20 [[file:Ex_21.org::v12][Ex 21,12-20]]

[fn:5] Ex 21,23-25 [[file:Ex_21.org::v23][Ex 21,23-25]]; Dtn 19,21 [[file:Dtn_19.org::v21][Dtn 19,21]]
