#+TITLE: Lev 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-12 Do 14:21]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Lev 7.html

<<verses>>

<<v1>>
* Das Schuldopfer: 7,1-10

1 Für das Schuldopfer gilt folgendes Gesetz: Es ist etwas Hochheiliges. [fn:1]

<<v2>>
2 Dort, wo man das Brandopfer schlachtet, soll man das Schuldopfer
schlachten und der Priester soll das Blut ringsum an den Altar sprengen.

<<v3>>
3 Dann soll er das ganze Fett davon darbringen: den Fettschwanz, das
Fett, das die Eingeweide bedeckt,

<<v4>>
4 die beiden Nieren, das Fett über ihnen und das an den Lenden sowie die
Fettmasse, die er von der Leber und den Nieren loslöst.

<<v5>>
5 Der Priester lasse das alles auf dem Altar als Feueropfer für den
Herrn in Rauch aufgehen; es ist ein Schuldopfer.

<<v6>>
6 Jede männliche Person unter den Priestern darf davon essen; man soll
es an einem heiligen Ort essen. Es ist etwas Hochheiliges.

<<v7>>
7 Für das Schuldopfer gilt dasselbe Gesetz wie für das Sündopfer. Es
gehört dem Priester, der damit die Sühne vollzieht.

<<v8>>
8 Das Fell des Opfertieres, das einer als ein Brandopfer zum Priester
bringt, gehört dem Priester, der es darbringt.

<<v9>>
9 Jedes Speiseopfer, das im Ofen gebacken oder in einem Kochtopf oder
auf einer Ofenplatte zubereitet wurde, gehört dem Priester, der es
darbringt.

<<v10>>
10 Jedes mit Öl vermengte und jedes trockene Speiseopfer gehört allen
Söhnen Aarons ohne Unterschied.\\
\\

<<v11>>
* Das Heilsopfer: 7,11-21

11 Für das Heilsopfer, das man für den Herrn darbringt, gilt folgendes
Gesetz: [fn:2]

<<v12>>
12 Wenn man es als Dankopfer darbringt, soll man zu diesem
Dankschlachtopfer ungesäuerten, mit Öl vermengten Kuchen hinzutun und
ungesäuerte, mit Öl bestrichene Brotfladen sowie Kuchen aus Feinmehl,
das mit Öl vermengt und eingerührt ist.

<<v13>>
13 Dazu soll man auch Gebäck aus gesäuertem Brot geben und das alles
zusammen mit dem Heilsopfer als Dankopfer darbringen.

<<v14>>
14 Einen Teil von jeder Opfergabe soll man mit dem Erhebungsritus dem
Herrn darbringen; es gehört dem Priester, der das Blut des Heilsopfers
sprengt. [fn:3]

<<v15>>
15 Das Opferfleisch des Schlachtdankopfers soll am Tag der Darbringung
gegessen werden; nichts davon darf bis zum nächsten Morgen liegen
bleiben.

<<v16>>
16 Wenn es sich um ein Gelübde oder um ein freiwilliges Opfer handelt,
darf das Fleisch am Tag der Darbringung und am folgenden Tag gegessen
werden; was übrig bleibt, darf gegessen werden;

<<v17>>
17 was aber vom Fleisch des Schlachtopfers dann noch übrig bleibt, soll
am dritten Tag verbrannt werden.

<<v18>>
18 Wenn man vom Fleisch des Heilsopfers am dritten Tag isst, findet der
Darbringende keine Annahme. Es wird ihm nicht angerechnet und ist
untauglich und die Person, die davon isst, muss die Folgen ihrer Schuld
tragen.

<<v19>>
19 Fleisch, das mit irgendetwas Unreinem in Berührung kommt, darf man
nicht essen; man soll es im Feuer verbrennen. Jeder Reine darf
Opferfleisch essen;

<<v20>>
20 wenn aber jemand im Zustand der Unreinheit vom Fleisch des
Heilsopfers isst, das dem Herrn gehört, soll er aus seinen
Stammesgenossen ausgemerzt werden.

<<v21>>
21 Wenn jemand mit irgendetwas Unreinem in Berührung kommt, sei es mit
etwas Unreinem von einem Menschen oder einem unreinen Tier oder
irgendeiner unreinen, abscheulichen Sache, und dann vom Fleisch eines
Heilsopfers isst, das für den Herrn geopfert wird, soll er aus seinen
Stammesgenossen ausgemerzt werden.\\
\\

<<v22>>
* Das Verbot von Fett- und Blutgenuß: 7,22-27

22 Der Herr sprach zu Mose:

<<v23>>
23 Sag zu den Israeliten: Von Rind, Schaf oder Ziege dürft ihr keinerlei
Fett essen.

<<v24>>
24 Das Fett eines verendeten oder zerrissenen Tieres kann zu jedem Zweck
verwendet werden, doch essen dürft ihr es auf keinen Fall. [fn:4]

<<v25>>
25 Jeder, der dennoch das Fett eines Tieres isst, das man als Feueropfer
für den Herrn darbringt, soll aus seinen Stammesgenossen ausgemerzt
werden.

<<v26>>
26 Wo immer ihr wohnt, dürft ihr kein Blut genießen, weder von Vögeln,
noch vom Vieh. [fn:5]

<<v27>>
27 Wer Blut genießt, soll aus seinen Stammesgenossen ausgemerzt
werden.\\
\\

<<v28>>
* Die Feueropfer: 7,28-38

28 Der Herr sprach zu Mose:

<<v29>>
29 Sag zu den Israeliten: Wer ein Tier als Heilsopfer für den Herrn
darbringen will, soll davon als Opfergabe für den Herrn Folgendes
herbeibringen:

<<v30>>
30 Mit seinen Händen bringe er als Feueropfer für den Herrn das Fett des
Bruststückes; er soll dieses Fett und die Brust bringen, die er vor dem
Herrn hin- und herschwingen und so darbringen soll.

<<v31>>
31 Der Priester lasse das Fett auf dem Altar in Rauch aufgehen, die
Brust aber gehört Aaron und seinen Söhnen.

<<v32>>
32 Für den Erhebungsritus gebt von euren Heilsopfern die rechte
Schenkelkeule dem Priester!

<<v33>>
33 Diese rechte Schenkelkeule soll jenem der Söhne Aarons als Anteil
gehören, der das Blut und das Fett des Heilsopfers darbringt.

<<v34>>
34 Ich nehme nämlich von den Heilsopfern der Israeliten die Brust für
den Darbringungsritus und die Schenkelkeule für den Erhebungsritus und
gebe sie dem Priester Aaron und seinen Söhnen als ein dauerndes Anrecht,
das die Israeliten ihnen gewähren müssen.

<<v35>>
35 Das also ist der Anteil Aarons und seiner Söhne an den Feueropfern
des Herrn an dem Tag, an dem er sie dem Herrn als Priester darbringt.

<<v36>>
36 Das hat der Herr ihnen zu geben befohlen an dem Tag, an dem er sie
unter den Israeliten salbte. Das gelte für sie als feste Regel von
Generation zu Generation.

<<v37>>
37 Das ist das Gesetz für Brandopfer, Speiseopfer, Sündopfer,
Schuldopfer, Priestereinsetzungsopfer und Heilsopfer.

<<v38>>
38 So hat es der Herr dem Mose auf dem Sinai an dem Tag aufgetragen, an
dem er die Israeliten verpflichtete, ihre Gaben dem Herrn in der Wüste
Sinai darzubringen.\\
\\


* Footnotes

[fn:1] (1-10) 5,1-26 [[file:Lev_5.org::v1][Lev 5,1-26]]

[fn:2] (11-21) 3,1-17 [[file:Lev_3.org::v1][Lev 3,1-17]]

[fn:3] Der Erhebungsritus ist ein ritueller Akt, bei dem der
Priester die Opfergabe mit beiden Händen hochhebt zum Zeichen dafür,
dass er sie Gott anbietet.

[fn:4] Ex 22,30 [[file:Ex_22.org::30][Ex 22,30]]

[fn:5] Gen 9,4 [[file:Gen_9.org::v4][Gen 9,4]]
