:PROPERTIES:
:ID:       d0cdc1a2-bfa7-4c45-8386-a414ad941eb7
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Micha* -- [[file:Mi_1.html][1]] *2*
[[file:Mi_3.html][3]] [[file:Mi_4.html][4]] ... [[file:Mi_7.html][7]]

--------------

* Mi 2
  :PROPERTIES:
  :CUSTOM_ID: mi-2
  :END:

<<verses>>

<<v1>>
**** Gegen die Habsucht der Reichen: 2,1-11
     :PROPERTIES:
     :CUSTOM_ID: gegen-die-habsucht-der-reichen-21-11
     :END:
1 Weh denen, die auf ihrem Lager Unheil planen /\\
 und Böses ersinnen. Wenn es Tag wird, führen sie es aus; /\\
 denn sie haben die Macht dazu. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Sie wollen Felder haben /\\
 und reißen sie an sich, /\\
 sie wollen Häuser haben /\\
 und bringen sie in ihren Besitz. Sie wenden Gewalt an gegen den Mann
und sein Haus, /\\
 gegen den Besitzer und sein Eigentum. ^{[[#fn2][2]]}\\
\\

<<v3>>
3 Darum - so spricht der Herr: /\\
 Seht, ich plane Unheil gegen diese Sippe. Dann könnt ihr den Hals /\\
 nicht mehr aus der Schlinge ziehen und ihr werdet den Kopf nicht mehr
so hoch tragen; /\\
 denn es wird eine böse Zeit sein. ^{[[#fn3][3]]}\\
\\

<<v4>>
4 An jenem Tag singt man ein Spottlied auf euch /\\
 und es ertönt die Klage: /\\
 Vernichtet sind wir, vernichtet! Den Besitz seines Volkes veräußert der
Herr /\\
 und niemand gibt ihn zurück; /\\
 an Treulose verteilt er unsere Felder.\\
\\

<<v5>>
5 Darum wird in der Gemeinde des Herrn keiner mehr sein, /\\
 der euch einen Acker zuteilt mit der Messschnur.\\
\\

<<v6>>
6 Sie geifern: Prophezeit nicht!, und sagen: /\\
 Man soll nicht prophezeien: /\\
 Diese Schmach wird nicht enden. ^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v7>>
7 Ist etwa das Haus Jakob verflucht? /\\
 Hat der Herr die Geduld verloren? /\\
 Sind das seine Taten? Sind seine Worte nicht voll Güte /\\
 gegenüber dem, der geradeaus geht?\\
\\

<<v8>>
8 Gestern noch war es mein Volk, /\\
 jetzt steht es da als mein Feind. Friedlichen Menschen reißt ihr den
Mantel herunter, /\\
 arglose Wanderer nehmt ihr gefangen, als wäre Krieg. ^{[[#fn6][6]]}\\
\\

<<v9>>
9 Die Frauen meines Volkes vertreibt ihr /\\
 aus ihrem behaglichen Heim, ihren Kindern nehmt ihr für immer /\\
 mein herrliches Land.\\
\\

<<v10>>
10 (Ihr sagt:) Auf, fort mit euch! /\\
 Hier ist für euch kein Ort der Ruhe mehr. Wegen einer Kleinigkeit
pflegt ihr zu pfänden; /\\
 diese Pfändung ist grausam.\\
\\

<<v11>>
11 Würde einer sich nach dem Wind drehen /\\
 und dir vorlügen: Ich prophezeie dir Wein und Bier!, /\\
 das wäre ein Prophet für dieses Volk. ^{[[#fn7][7]]}\\
\\

<<v12>>
**** Die Rettung Israels: 2,12-13
     :PROPERTIES:
     :CUSTOM_ID: die-rettung-israels-212-13
     :END:
12 Ich werde ganz Jakob versammeln, /\\
 den Rest von Israel will ich vereinen. Ich führe sie zusammen wie die
Schafe im Pferch, /\\
 wie die Herde mitten auf der Weide - /\\
 eine wogende Menschenmenge. ^{[[#fn8][8]]}\\
\\

<<v13>>
13 Ein Vorkämpfer bricht ihnen die Bahn, /\\
 sie brechen durch das Tor in die Stadt ein; /\\
 dann ziehen sie weiter. Ihr König geht vor ihnen her, /\\
 der Herr schreitet an ihrer Spitze. ^{[[#fn9][9]]}\\
\\

^{[[#fnm1][1]]} ℘ Ps 36,5

^{[[#fnm2][2]]} ℘ Jes 5,8

^{[[#fnm3][3]]} ℘ Am 5,13

^{[[#fnm4][4]]} ℘ Jes 30,10

^{[[#fnm5][5]]} 6-8: Text nicht klar.

^{[[#fnm6][6]]} ℘ Dtn 24,12f

^{[[#fnm7][7]]} ℘ Jer 5,31

^{[[#fnm8][8]]} ℘ Jer 3,18; Ez 37,15-28; 34,11-16

^{[[#fnm9][9]]} ℘ Joh 14,4
