:PROPERTIES:
:ID:       3c0918cb-3604-4121-8bba-32b4fa37f0b6
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Nahum* -- [[file:Nah_1.html][1]] *2*
[[file:Nah_3.html][3]]

--------------

* Nah 2
  :PROPERTIES:
  :CUSTOM_ID: nah-2
  :END:

<<verses>>

<<v1>>
1 Seht auf den Bergen die Schritte des Freudenboten! /\\
 Er verkündet Frieden! Juda, feiere deine Feste, /\\
 erfülle deine Gelübde! Denn der Unheilstifter durchstreift dein Land
nicht mehr; /\\
 er ist völlig vernichtet. ^{[[#fn1][1]]}\\
\\

<<v2>>
**** Die Zerstörung der Stadt: 2,2-14
     :PROPERTIES:
     :CUSTOM_ID: die-zerstörung-der-stadt-22-14
     :END:
2 Ein Mann zieht hinauf gegen dich, /\\
 der dich zerschmettern wird. Halt Wache! /\\
 Beobachte die Wege! Mach deine Hüften stark! /\\
 Rüste dich mit Macht und Kraft!\\
\\

<<v3>>
3 Wahrhaftig, der Herr /\\
 stellt die Pracht Jakobs wieder her /\\
 wie die Pracht Israels; denn Verwüster haben sie verwüstet /\\
 und ihre jungen Pflanzen vernichtet.\\
\\

<<v4>>
4 Rot leuchtet der Schild seiner Helden. /\\
 Seine Krieger sind in Scharlach gekleidet. Wie funkelnder Stahl glänzen
die Wagen /\\
 am Tag, an dem er sie aufbietet, /\\
 und die Speere wiegen sich.\\
\\

<<v5>>
5 Durch die Gassen rasen die Kriegswagen, /\\
 sie stürmen über die Plätze. Ihr Anblick gleicht Fackeln, /\\
 wie Blitze jagen sie daher.\\
\\

<<v6>>
6 Er denkt an seine Mächtigen; /\\
 sie aber straucheln beim Ansturm. Sie eilen zur Stadtmauer; /\\
 doch unbeweglich steht die Sperre. ^{[[#fn2][2]]}\\
\\

<<v7>>
7 Die Flusstore sind geöffnet, /\\
 schon wankt der Palast.\\
\\

<<v8>>
8 Die Königin wird zur Schau gestellt, /\\
 wird entblößt, wird weggeführt; ihre Mägde jammern wie gurrende Tauben
/\\
 und schlagen sich an die Brust.\\
\\

<<v9>>
9 Ninive ist wie ein voller Teich, /\\
 dessen Wasser davonfließt. Halt! Halt! (ruft man), /\\
 doch keiner wendet sich um.\\
\\

<<v10>>
10 Plündert das Silber, plündert das Gold! /\\
 Kostbarkeiten ohne Ende! Welche Pracht aller Art /\\
 an bezaubernden Schätzen!\\
\\

<<v11>>
11 Alles leer, entleert, verheert; /\\
 das Herz verzagt. Es wanken die Knie, /\\
 ein Zittern in allen Hüften, /\\
 alle Gesichter glühen rot.\\
\\

<<v12>>
12 Wo ist jetzt das Versteck der Löwen, /\\
 der Tummelplatz der jungen Löwen, wohin der Löwe geht, um sich zu
verbergen, /\\
 wo der junge Löwe bleibt, /\\
 ohne dass jemand ihn aufschreckt?\\
\\

<<v13>>
13 Reichen Raub machte der Löwe für seine Jungen. /\\
 Er würgte für seine Löwinnen. Mit Raub füllte er seine Höhlen, /\\
 seine Verstecke mit Raubgut.\\
\\

<<v14>>
14 Nun gehe ich gegen dich vor /\\
 - Spruch des Herrn der Heere. Ich lasse deine Wagen in Rauch aufgehen,
/\\
 deine jungen Löwen frisst das Schwert. Ich mache deinem Rauben auf der
Erde ein Ende, /\\
 nie mehr hört man den Ruf deiner Boten. ^{[[#fn3][3]]}\\
\\

^{[[#fnm1][1]]} ℘ Jes 40,9; 52,7-10

^{[[#fnm2][2]]} Er: Gemeint ist der König von Assur.

^{[[#fnm3][3]]} ℘ 3,5
