#+TITLE: Neh 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 22:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Neh 1.html

<<verses>>

<<v1>>
* Der Wiederaufbau durch Nehemia: 1,1 - 6,19

* Das Gebet Nehemias: 1,1-11

1 Bericht des Nehemia, des Sohnes Hachaljas. Im Monat Kislew, im
zwanzigsten Jahr des Artaxerxes, war ich in der Festung Susa; [fn:1] [fn:2]

<<v2>>
2 da kam Hanani, einer meiner Brüder, mit einigen Männern aus Juda. Ich
fragte sie, wie es den Juden gehe, den Geretteten, die von den
Gefangenen übrig geblieben waren, und wie es um Jerusalem stehe.

<<v3>>
3 Sie sagten zu mir: Der Rest, der von den Gefangenen übrig geblieben
ist, lebt dort in der Provinz in großer Not und Schmach. Die Stadtmauer
von Jerusalem ist niedergelegt und die Tore sind abgebrannt. [fn:3]

<<v4>>
4 Als ich das hörte, setzte ich mich nieder und weinte. Ich trauerte
tagelang, fastete und betete zu dem Gott des Himmels. [fn:4]

<<v5>>
5 Ich sagte: Ach, Herr, Gott des Himmels, du großer und
furchtgebietender Gott! Du hältst deinen Bund und bewahrst deine Gnade
denen, die dich lieben und deine Gebote halten. [fn:5]

<<v6>>
6 Hab ein aufmerksames Ohr und ein offenes Auge und hör das Gebet deines
Knechtes! Ich bete jetzt Tag und Nacht vor dir für die Söhne Israels,
deine Diener. Ich lege ein Bekenntnis ab wegen der Sünden der Söhne
Israels. Wir haben gegen dich gesündigt; auch ich und meine Familie
haben gesündigt.

<<v7>>
7 Wir haben sehr schlecht gegen dich gehandelt: Wir haben die Gebote,
Gesetze und Anordnungen missachtet, die du deinem Diener Mose gegeben
hast.

<<v8>>
8 Aber denk an das Wort, das du deinem Diener Mose aufgetragen hast:
Wenn ihr mir die Treue brecht, dann werde ich euch unter die Völker
zerstreuen; [fn:6]

<<v9>>
9 wenn ihr aber zu mir umkehrt, meine Gebote befolgt und sie ausführt,
dann sammle ich euch wieder, selbst die, die bis ans Ende des Himmels
verschlagen wurden; ich bringe sie an den Ort, den ich erwählt habe, um
dort meinen Namen wohnen zu lassen.

<<v10>>
10 Sie sind ja deine Knechte, dein Volk, das du erlöst hast mit deiner
großen Kraft und deiner starken Hand. [fn:7]

<<v11>>
11 Ach, Herr, dein Ohr höre aufmerksam auf das Gebet deines Knechtes und
das Gebet deiner Knechte, die von Herzen deinen Namen fürchten: Gewähre
deinem Knecht heute Erfolg und lass ihn Erbarmen finden bei diesem Mann!
Ich war nämlich Mundschenk beim König.\\
\\

* Footnotes

[fn:1] [[file:Est_1.org::v2][Est 1,2f]]; [[file:Dan_8.org::v2][Dan 8,2]]

[fn:2] Das 20. Jahr des Perserkönigs Artaxerxes I. ist das Jahr 445 v. Chr.

[fn:3] [[file:Esra_4.org::v21][Esra 4,21]]-[[file:Dtn_30.org::v24][24]]

[fn:4] [[file:Esra_9.org::v3][Esra 9,3]]

[fn:5] [[file:Dan_9.org::v4][Dan 9,4]]

[fn:6] (8-9) [[file:Dtn_30.org::v1][Dtn 30,1]]-[[file:Dtn_30.org::v4][4]]

[fn:7] [[file:Dtn_9.org::v29][Dtn 9,29]]
