#+TITLE: Neh 8 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 00:08]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Neh 8.html

<<verses>>

<<v1>>
* Die Unterweisung im Gesetz: 8,1-12

1 Das ganze Volk versammelte sich geschlossen auf dem Platz vor dem
Wassertor und bat den Schriftgelehrten Esra, das Buch mit dem Gesetz des
Mose zu holen, das der Herr den Israeliten vorgeschrieben hat. [fn:1]

<<v2>>
2 Am ersten Tag des siebten Monats brachte der Priester Esra das Gesetz
vor die Versammlung; zu ihr gehörten die Männer und die Frauen und alle,
die das Gesetz verstehen konnten. [fn:2]

<<v3>>
3 Vom frühen Morgen bis zum Mittag las Esra auf dem Platz vor dem
Wassertor den Männern und Frauen und denen, die es verstehen konnten,
das Gesetz vor. Das ganze Volk lauschte auf das Buch des Gesetzes.

<<v4>>
4 Der Schriftgelehrte Esra stand auf einer Kanzel aus Holz, die man
eigens dafür errichtet hatte. Neben ihm standen rechts Mattitja, Schema,
Anaja, Urija, Hilkija und Maaseja und links Pedaja, Mischaël, Malkija,
Haschum, Haschbaddana, Secharja und Meschullam.

<<v5>>
5 Esra öffnete das Buch vor aller Augen, denn er stand höher als das
versammelte Volk. Als er das Buch aufschlug, erhoben sich alle.

<<v6>>
6 Dann pries Esra den Herrn, den großen Gott; darauf antworteten alle
mit erhobenen Händen: Amen, amen! Sie verneigten sich, warfen sich vor
dem Herrn nieder, mit dem Gesicht zur Erde. [fn:3]

<<v7>>
7 Die Leviten Jeschua, Bani, Scherebja, Jamin, Akkub, Schabbetai,
Hodija, Maaseja, Kelita, Asarja, Josabad, Hanan und Pelaja erklärten dem
Volk das Gesetz; die Leute blieben auf ihrem Platz.

<<v8>>
8 Man las aus dem Buch, dem Gesetz Gottes, in Abschnitten vor und gab
dazu Erklärungen, sodass die Leute das Vorgelesene verstehen konnten.

<<v9>>
9 Der Statthalter Nehemia, der Priester und Schriftgelehrte Esra und die
Leviten, die das Volk unterwiesen, sagten dann zum ganzen Volk: Heute
ist ein heiliger Tag zu Ehren des Herrn, eures Gottes. Seid nicht
traurig und weint nicht! Alle Leute weinten nämlich, als sie die Worte
des Gesetzes hörten.

<<v10>>
10 Dann sagte Esra zu ihnen: Nun geht, haltet ein festliches Mahl und
trinkt süßen Wein! Schickt auch denen etwas, die selbst nichts haben;
denn heute ist ein heiliger Tag zur Ehre des Herrn. Macht euch keine
Sorgen; denn die Freude am Herrn ist eure Stärke. [fn:4]

<<v11>>
11 Auch die Leviten beruhigten das ganze Volk und sagten: Seid still,
denn dieser Tag ist heilig. Macht euch keine Sorgen!

<<v12>>
12 Da gingen alle Leute nach Hause, um zu essen und zu trinken und auch
andern davon zu geben und um ein großes Freudenfest zu begehen; denn sie
hatten die Worte verstanden, die man ihnen verkündet hatte.\\
\\

<<v13>>
* Die Feier des Laubhüttenfestes: 8,13-18

13 Am zweiten Tag versammelten sich die Familienoberhäupter des ganzen
Volkes sowie die Priester und Leviten bei dem Schriftgelehrten Esra, um
die Worte des Gesetzes weiter kennen zu lernen.

<<v14>>
14 Da fanden sie im Gesetz, das der Herr durch Mose geboten hat, die
Stelle, an der es heißt: Die Israeliten sollen während des Festes im
siebten Monat in Laubhütten wohnen. [fn:5]

<<v15>>
15 Wie man sie unterrichtet hatte, ließen sie nun in all ihren Städten
und in Jerusalem ausrufen: Geht in die Berge und holt Zweige von
veredelten und von wilden Ölbäumen, Zweige von Myrten, Palmen und
Laubbäumen zum Bau von Laubhütten, wie es vorgeschrieben ist.

<<v16>>
16 Da ging das Volk hinaus; man holte Zweige und baute sich Laubhütten,
der eine auf seinem flachen Dach, andere in ihren Höfen, in den Vorhöfen
des Gotteshauses, auf dem Platz am Wassertor und auf dem Platz am
Efraimtor.

<<v17>>
17 Die ganze Gemeinde, alle, die aus der Gefangenschaft heimgekehrt
waren, bauten Laubhütten und wohnten darin. So hatten die Israeliten es
nicht mehr gehalten seit den Tagen Josuas, des Sohnes Nuns, bis zu
diesem Tag, und die Freude war überaus groß.

<<v18>>
18 Jeden Tag las Esra aus dem Buch des Gesetzes Gottes vor, vom ersten
Tag bis zum letzten. So feierte man das Fest sieben Tage lang; am achten
Tag war, wie vorgeschrieben, die Festversammlung. [fn:6]\\
\\

* Footnotes

[fn:1] [[file:Esra_3.org::v1][Esra 3,1]]; [[file:Esra_7.org::v6][7,6]]

[fn:2] und alle, die das Gesetz verstehen konnten: die Kinder,
die schon das Alter der Vernunft erreicht hatten.

[fn:3] [[file:Esra_5.org::v13][5,13]]; [[file:1.Chr_16.org::v36][1 Chr 16,36]]

[fn:4] [[file:Dtn_14.org::v29][Dtn 14,29]]; [[file:Dtn_26.org::v12][26,12]]

[fn:5] [[file:Lev_23.org::v40][Lev 23,40]]-[[file:Lev_23.org::v42][42]]

[fn:6] [[file:Lev_23.org::v36][Lev 23,36]]
