#+TITLE: Neh 13 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 09:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Neh 13.html

<<verses>>

<<v1>>
* Weitere Reformen Nehemias: 13,1-14

1 Zu jener Zeit las man dem Volk aus dem Buch des Mose vor; da fand man
die Stelle, an der steht: Ammoniter und Moabiter dürfen niemals in die
Gemeinde Gottes eintreten; [fn:1]

<<v2>>
2 denn sie sind den Israeliten einst nicht mit Brot und Wasser
entgegengekommen. Moab hat gegen sie Bileam gedungen, der sie verfluchen
sollte. Doch unser Gott verwandelte den Fluch in einen Segen.

<<v3>>
3 Als man dieses Gesetz gehört hatte, sonderte man aus Israel alle
Mischvölker aus.

<<v4>>
4 Früher hatte der Priester Eljaschib die Kammern des Hauses unseres
Gottes betreut; er war verwandt mit Tobija [fn:2]

<<v5>>
5 und hatte darum für ihn eine große Kammer einrichten lassen. Dort
bewahrte man früher das Opfermehl und den Weihrauch auf sowie die
Behälter und den Zehnten von Getreide, Wein und Öl, der den Leviten,
Sängern und Torwächtern gesetzlich zukam, außerdem die Abgaben für die
Priester.

<<v6>>
6 Bei all dem war ich aber nicht in Jerusalem gewesen; denn im
zweiunddreißigsten Jahr des Artaxerxes, des Königs von Babel, war ich
zum König gereist. Nach einiger Zeit erbat ich aber vom König (die
Erlaubnis zur Abreise)

<<v7>>
7 und kam wieder nach Jerusalem. Nun bemerkte ich die Untat, die
Eljaschib zugunsten Tobijas begangen hatte, indem er ihm in den Vorhöfen
des Hauses Gottes eine Kammer eingerichtet hatte. [fn:3]

<<v8>>
8 Das missfiel mir sehr und ich warf den ganzen Hausrat Tobijas aus der
Kammer hinaus.

<<v9>>
9 Dann ließ ich die Kammer reinigen und brachte die Behälter des Hauses
Gottes, das Opfermehl und den Weihrauch wieder dorthin. [fn:4]

<<v10>>
10 Ich erfuhr auch, dass die Anteile der Leviten nicht abgeliefert
wurden; darum waren die Leviten und die Sänger, die den Dienst zu
versehen hatten, weggegangen, jeder auf seinen Landbesitz. [fn:5]

<<v11>>
11 Da machte ich den Beamten Vorwürfe und sagte: Warum wird das Haus
Gottes vernachlässigt? Und ich holte die Leviten wieder zusammen und
stellte sie auf ihren Posten.

<<v12>>
12 Nun brachte ganz Juda wieder den Zehnten von Getreide, Wein und Öl zu
den Vorratskammern. [fn:6]

<<v13>>
13 Zur Aufsicht über die Vorratskammern bestimmte ich den Priester
Schelemja, den Schreiber Zadok und den Leviten Pedaja. Ihnen stellte ich
Hanan, den Sohn Sakkurs, des Sohnes Mattanjas, an die Seite, denn sie
galten als zuverlässig. Ihnen oblag es nun, den Zehnten an ihre Brüder
zu verteilen.

<<v14>>
14 Denk dafür an mich, mein Gott, und lösch die guten Taten nicht aus,
die ich für das Haus meines Gottes und seine Ordnung vollbracht habe. [fn:7]\\
\\

<<v15>>
* Die Sabbatordnung: 13,15-22

15 Damals sah ich in Juda Leute, die am Sabbat die Kelter traten. Andere
brachten Getreide ein und luden es auf Esel; auch Wein, Trauben, Feigen
und Lasten aller Art brachten sie am Sabbattag nach Jerusalem. Ich
verwarnte sie, weil sie an diesem Tag Lebensmittel verkauften. [fn:8]

<<v16>>
16 Die Leute von Tyrus, die in Juda wohnten, brachten Fische und
allerlei Waren und verkauften sie am Sabbat an die Juden, sogar in
Jerusalem.

<<v17>>
17 Da machte ich den Vornehmen von Juda Vorwürfe und sagte zu ihnen: Wie
könnt ihr eine solche Untat begehen und den Sabbat entweihen?

<<v18>>
18 Haben das nicht schon eure Väter getan? Dafür ließ unser Gott all
dieses Unheil über uns und diese Stadt kommen. Wollt ihr neuen Zorn über
Israel bringen, indem ihr den Sabbat entweiht?

<<v19>>
19 Ich ließ von da an vor dem Anbruch des Sabbats, wenn es in den Toren
Jerusalems dunkel wurde, die Tore schließen und befahl, sie erst nach
dem Sabbat wieder zu öffnen. Auch stellte ich einige meiner Leute an die
Tore, damit am Sabbattag keine Lasten hereingebracht wurden. [fn:9]

<<v20>>
20 Einmal und ein zweites Mal übernachteten die Händler und die
Verkäufer von allerlei Waren draußen vor Jerusalem.

<<v21>>
21 Da warnte ich sie und sagte zu ihnen: Wozu übernachtet ihr gerade vor
der Mauer? Wenn ihr es noch einmal tut, lasse ich euch festnehmen. Von
da an kamen sie nicht mehr am Sabbat.

<<v22>>
22 Den Leviten aber befahl ich, sie sollten sich reinigen und sich als
Wächter an die Tore stellen, damit man den Sabbattag heilig halte. Auch
dafür denk an mich, mein Gott, und sei mir gnädig in deiner großen Huld! [fn:10]\\
\\

<<v23>>
* Das Verbot der Mischehen: 13,23-31
     
23 Damals sah ich auch Juden, die Frauen von Aschdod, Ammon und Moab
geheiratet hatten. [fn:11]

<<v24>>
24 Die Hälfte ihrer Kinder redete in der Sprache von Aschdod oder in der
Sprache eines der anderen Völker, konnten aber nicht mehr Jüdisch.

<<v25>>
25 Ich machte ihnen Vorwürfe und verfluchte sie. Einige von ihnen schlug
ich und packte sie bei den Haaren. Ich beschwor sie bei Gott: Ihr dürft
eure Töchter nicht ihren Söhnen geben noch ihre Töchter zu Frauen für
eure Söhne oder für euch selbst nehmen. [fn:12]

<<v26>>
26 Hat sich nicht wegen solcher Frauen Salomo, der König Israels,
versündigt? Unter den vielen Völkern gab es keinen König wie ihn. Er
wurde von seinem Gott geliebt; darum hatte ihn Gott zum König über ganz
Israel gemacht. Aber selbst ihn haben die fremden Frauen zur Sünde
verführt. [fn:13]

<<v27>>
27 Und jetzt hört man von euch, dass ihr genau dieselbe Untat begeht und
unserem Gott die Treue brecht, indem ihr fremde Frauen heiratet.

<<v28>>
28 Einer der Söhne des Hohenpriesters Jojada, des Sohnes Eljaschibs, war
der Schwiegersohn des Sanballat von Horon; ihn verwies ich aus meinem
Gebiet. [fn:14]

<<v29>>
29 Vergiss es ihnen nicht, mein Gott, dass sie das Priestertum und den
Bund der Priester und Leviten befleckt haben. [fn:15]

<<v30>>
30 So habe ich das Volk von allem gereinigt, was fremd war. Für die
Priester und Leviten habe ich Ordnungen aufgestellt, die jedem seinen
Dienst zuteilen.

<<v31>>
31 Auch habe ich angeordnet, wie man an den festgesetzten Zeiten das
Brennholz liefern und die ersten Erträge bringen soll. Denk daran, mein
Gott, und halt es mir zugute! [fn:16]\\
\\

* Footnotes

[fn:1] [[file:Dtn_23.org::v4][Dtn 23,4]]-[[file:Dtn_23.org::v6][6]]

[fn:2] [[file:Neh_2.org::v19][2,19]]; [[file:Neh_12.org::v44][12,44]]

[fn:3] [[file:~/RoamNotes/notes/Bibel/nt/Mt_21.org::v12][Mt 21,12]]

[fn:4] [[file:Neh_12.org::v30][12,30]]

[fn:5] [[file:Neh_12.org::v47][12,47]]

[fn:6] [[file:Neh_10.org::v38][10,38]]

[fn:7] [[file:Neh_5.org::v19][5,19]]

[fn:8] (15-16) [[file:Neh_10.org::v32][10,32]]; [[file:Jer_17.org::v19][Jer 17,19]]-[[file:Jer_17.org::v27][27]]

[fn:9] Der Sabbat beginnt mit dem Sonnenuntergang.

[fn:10] [[file:Neh_12.org::v30][12,30]]

[fn:11] [[file:Esra_9.org::v1][Esra 9,1f]]

[fn:12] [[file:Dtn_7.org::v3][Dtn 7,3]]

[fn:13] [[file:1.Kön_11.org::v1][1 Kön 11,1]]-[[file:1.Kön_11.org::v8][8]]; [[file:1.Kön_10.org::v23][10,23]]; [[file:2.Sam_12.org::v24][2 Sam 12,24f]]

[fn:14] [[file:Lev_21.org::v14][Lev 21,14]]

[fn:15] [[file:Num_25.org::v12][Num 25,12f]]; [[file:Mal_2.org::v8][Mal 2,8]]

[fn:16] [[file:Neh_10.org::v35][10,35]]; [[v14][13,14]]; [[file:Neh_5.org::v19][5,19]]
