#+TITLE: Neh 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 23:23]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Neh 3.html

<<verses>>

<<v1>>
* Der Bericht über den Bau: 3,1-32

1 Der Hohepriester Eljaschib und seine Brüder, die Priester, machten
sich ans Werk und bauten das Schaftor auf. Sie setzten die Balken ein
und brachten die Torflügel an. Sie bauten weiter bis zum Turm der
Hundert, setzten die Balken ein und kamen bis zum Turm Hananel. [fn:1] [fn:2]

<<v2>>
2 Anschließend bauten die Männer von Jericho und daneben baute Sakkur,
der Sohn Imris.

<<v3>>
3 Das Fischtor bauten die Söhne des Senaa; sie setzten die Balken ein
und brachten die Torflügel, Riegel und Sperrbalken an.

<<v4>>
4 Neben ihnen arbeitete an der Instandsetzung Meremot, der Sohn Urijas,
des Sohnes des Koz. Daneben arbeitete Meschullam, der Sohn Berechjas,
des Sohnes Meschesabels. Daneben arbeitete Zadok, der Sohn Baanas.

<<v5>>
5 Daneben arbeiteten die Leute aus Tekoa. Die Vornehmen unter ihnen
freilich beugten den Nacken nicht zum Dienst für ihre Herren.

<<v6>>
6 Jojada, der Sohn Paseachs, und Meschullam, der Sohn Besodjas,
arbeiteten an der Instandsetzung des Jeschanators; sie setzten die
Balken ein und brachten die Torflügel, Riegel und Sperrbalken an.

<<v7>>
7 Daneben arbeitete Melatja aus Gibeon und Jadon aus Meronot sowie die
Leute aus Gibeon und Mizpa, dort wo der Statthalter des Gebiets jenseits
des Stroms seinen Sitz hatte.

<<v8>>
8 Daneben arbeitete Usiël, der Sohn Harhajas, einer von den
Goldschmieden; und daneben arbeitete Hananja, ein Salbenhersteller. Sie
befestigten Jerusalem bis zur Breiten Mauer.

<<v9>>
9 Daneben arbeitete Refaja, der Sohn Hurs, der Vorsteher der einen
Hälfte des Bezirks von Jerusalem.

<<v10>>
10 Daneben arbeitete Jedaja, der Sohn Harumafs, gegenüber seinem Haus;
und daneben arbeitete Hattusch, der Sohn Haschabnejas.

<<v11>>
11 Malkija, der Sohn Harims, und Haschub, der Sohn des Pahat-Moab,
arbeiteten an der Instandsetzung des folgenden Stückes und des
Ofenturms.

<<v12>>
12 Daneben arbeitete Schallum, der Sohn des Lohesch, der Vorsteher der
anderen Hälfte des Bezirks von Jerusalem. Ihm halfen seine Töchter.

<<v13>>
13 Hanun und die Einwohner von Sanoach arbeiteten an der Instandsetzung
des Taltors; sie bauten es auf und brachten die Torflügel, Riegel und
Sperrbalken an; sie setzten auch weitere tausend Ellen der Mauer
instand, bis zum Aschentor.

<<v14>>
14 Malkija, der Sohn Rechabs, der Vorsteher des Bezirks von Bet-Kerem,
arbeitete an der Instandsetzung des Aschentors; er baute es auf und
brachte die Torflügel, Riegel und Sperrbalken an.

<<v15>>
15 Schallun, der Sohn Kolhoses, der Vorsteher des Bezirks von Mizpa,
arbeitete an der Instandsetzung des Quelltors; er baute es auf, versah
es mit einem Dach und brachte die Torflügel, Riegel und Sperrbalken an.
Weiter setzte er die Mauer am Teich der Wasserleitung beim Königsgarten
instand, bis zu den Stufen, die von der Davidstadt herabführen. [fn:3]

<<v16>>
16 Hinter ihm arbeitete Nehemja, der Sohn des Asbuk, der Vorsteher der
einen Hälfte des Bezirks von Bet-Zur; er arbeitete bis zu der Stelle
gegenüber den Gräbern Davids und weiter bis zum künstlichen Teich und
zur Kaserne der Leibwache.

<<v17>>
17 Hinter ihm arbeiteten die Leviten, nämlich Rehum, der Sohn Banis, und
daneben Haschabja, der Vorsteher der einen Hälfte des Bezirks von Keïla;
er arbeitete für seinen Bezirk.

<<v18>>
18 Hinter ihm arbeiteten die Brüder dieser Leviten unter Binnui, dem
Sohn des Henadad, dem Vorsteher der anderen Hälfte des Bezirks von
Keïla.

<<v19>>
19 Neben ihm arbeitete Eser, der Sohn Jeschuas, der Vorsteher von Mizpa,
an der Instandsetzung des folgenden Stückes, gegenüber dem Aufstieg zum
Zeughaus am Winkel.

<<v20>>
20 Hinter ihm arbeitete Baruch, der Sohn Sabbais, an der Instandsetzung
des anschließenden Stückes, vom Winkel bis an den Eingang zum Haus des
Hohenpriesters Eljaschib.

<<v21>>
21 Hinter ihm arbeitete Meremot, der Sohn Urijas, des Sohnes des Koz, am
anschließenden Stück, vom Eingang bis zum Ende des Hauses von Eljaschib.

<<v22>>
22 Hinter ihm arbeiteten die Priester, die im Umkreis wohnten.

<<v23>>
23 Dahinter arbeiteten Benjamin und Haschub gegenüber ihrem Haus und
hinter ihnen arbeitete Asarja, der Sohn Maasejas, des Sohnes Ananejas,
neben seinem Haus.

<<v24>>
24 Dahinter arbeitete Binnui, der Sohn Henadads, an der Instandsetzung
des anschließenden Stückes, vom Haus des Asarja bis zum Winkel und
weiter bis zur Ecke.

<<v25>>
25 Palal, der Sohn Usais, arbeitete gegenüber dem Winkel und dem oberen
Turm, der vom königlichen Palast am Wachthof vorspringt. Hinter ihm
arbeiteten Pedaja, der Sohn des Parosch, [fn:4]

<<v26>>
26 und die Tempeldiener, die auf dem Ofel wohnten, bis zu der Stelle
gegenüber dem Wassertor im Osten und dem vorspringenden Turm.

<<v27>>
27 Dahinter arbeiteten die Leute von Tekoa an der Instandsetzung des
anschließenden Stückes, von der Stelle, die dem großen, vorspringenden
Turm gegenüberliegt, bis zur Mauer des Ofel.

<<v28>>
28 Oberhalb des Rosstors arbeiteten die Priester, jeder seinem Haus
gegenüber.

<<v29>>
29 Dahinter arbeitete Zadok, der Sohn Immers, seinem Haus gegenüber, und
hinter ihm arbeitete Schemaja, der Sohn Schechanjas, der Wächter des
Osttors. [fn:5]

<<v30>>
30 Dahinter arbeiteten Hananja, der Sohn Schelemjas, und Hanun, der
sechste Sohn Zalafs, an der Instandsetzung eines weiteren Stückes.
Dahinter arbeitete Meschullam, der Sohn Berechjas, gegenüber seiner
Zelle.

<<v31>>
31 Hinter ihm arbeitete Malkija, einer von den Goldschmieden, bis zum
Haus der Tempeldiener und der Händler, gegenüber dem Wachttor, und bis
zum Obergemach an der Ecke.

<<v32>>
32 Und zwischen dem Obergemach an der Ecke und dem Schaftor arbeiteten
die Goldschmiede und die Händler.\\
\\

<<v33>>
* Der Spott der Feinde: 3,33-38

33 Als Sanballat hörte, dass wir die Mauer aufbauten, wurde er zornig
und ärgerte sich sehr. Er spottete über die Juden [fn:6]

<<v34>>
34 und sagte vor seinen Brüdern und dem Heer von Samarien: Was machen
diese elenden Juden da? Wollen sie Jerusalem wieder für sich befestigen?
Wollen sie Opfer darbringen? Wollen sie es an einem Tag vollenden?
Können sie die Steine, die doch ausgeglüht sind, aus den Schutthaufen zu
neuem Leben aufrichten?

<<v35>>
35 Und Tobija von Ammon, der neben ihm stand, sagte: Lasst sie nur
bauen! Springt ein Fuchs hinauf, dann reißt er ihre Steinmauer nieder.

<<v36>>
36 Hör, unser Gott, wie wir zum Gespött geworden sind. Lass ihren Hohn
auf sie selbst zurückfallen! Gib sie der Plünderung und der
Gefangenschaft preis!

<<v37>>
37 Deck ihr Vergehen nicht zu! Ihre Sünde soll bei dir nicht ausgelöscht
sein, denn sie haben die Bauenden beleidigt. [fn:7]

<<v38>>
38 Wir bauten an der Mauer weiter und bald hatte sich die Mauer ringsum
bis zur Hälfte geschlossen. Das ermutigte das Volk zur weiteren
Arbeit.\\
\\

* Footnotes

[fn:1] [[file:Jer_31.org::v38][Jer 31,38-40]]; [[file:Neh_12.org::v31][Neh 12,31-39]]

[fn:2] Text korr.; H unklar.

[fn:3] [[file:2.Kön_20.org::v20][2 Kön 20,20]]; [[file:~/RoamNotes/notes/Bibel/nt/Joh_9.org::v7][Joh 9,7]]

[fn:4] [[file:Jer_32.org::v2][Jer 32,2]]

[fn:5] [[file:Ez_40.org::v6][Ez 40,6]]

[fn:6] [[file:Neh_2.org::v10][2,10]].[[file:Neh_2.org::v19][19]]

[fn:7] [[file:Jer_18.org::v23][Jer 18,23]]
