#+TITLE: Neh 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-23 Do 23:16]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Neh 2.html

<<verses>>

<<v1>>
* Die Rückkehr Nehemias: 2,1-10

1 Im Monat Nisan, im zwanzigsten Jahr des Königs Artaxerxes, nahm ich
den Wein und reichte ihn dem König - mein Amt war es nämlich, für den
Wein zu sorgen. Nie zuvor hatte der König mein Aussehen schlecht
gefunden;

<<v2>>
2 jetzt aber fragte er mich: Warum siehst du so schlecht aus? Du bist
doch nicht etwa krank? Nein, du hast gewiss Kummer. Ich erschrak sehr;

<<v3>>
3 dann sagte ich zum König: Der König möge ewig leben. Wie sollte ich
nicht schlecht aussehen? Die Stadt, in der die Gräber meiner Väter sind,
liegt in Trümmern und ihre Tore sind vom Feuer verzehrt.

<<v4>>
4 Der König erwiderte: Was möchtest du also? Da betete ich zum Gott des
Himmels;

<<v5>>
5 dann sagte ich zum König: Wenn du, König, es für gut findest und wenn
du deinem Knecht vertraust, so sende mich nach Juda, damit ich die Stadt
wieder aufbaue, in der die Gräber meiner Väter sind.

<<v6>>
6 Darauf fragte mich der König, während die Königin neben ihm saß: Wie
lang soll deine Reise dauern? Wann kommst du zurück? Ich nannte ihm eine
bestimmte Zeit; der König war einverstanden und ließ mich ziehen.

<<v7>>
7 Ich sagte dem König noch: Wenn der König es für gut findet, dann gebe
man mir Briefe mit an die Statthalter des Gebiets jenseits des Stroms,
damit sie mich bis nach Juda durchreisen lassen; [fn:1]

<<v8>>
8 ferner einen Brief an Asaf, den Verwalter der königlichen Wälder: Er
soll mir Bauholz liefern für die Tore der Tempelburg, für die Stadtmauer
und für das Haus, in das ich ziehen will. Der König bewilligte es mir,
weil die gütige Hand meines Gottes über mir war.

<<v9>>
9 So kam ich zu den Statthaltern im Gebiet jenseits des Stroms und ich
übergab ihnen die Briefe des Königs. Der König hatte mir auch Hauptleute
und Reiter als Geleit gegeben. [fn:2]

<<v10>>
10 Sanballat, der Horoniter, und Tobija, der Knecht von Ammon, hörten
davon. Es verdross sie sehr, dass da ein Mann kam, der sich für das Wohl
der Israeliten einsetzte.\\
\\

<<v11>>
* Der Entschluss zum Mauerbau: 2,11-20

11 So kam ich nach Jerusalem. Dort blieb ich drei Tage. [fn:3]

<<v12>>
12 Dann machte ich mich bei Nacht auf, nahm aber nur einige wenige
Männer mit. Noch hatte ich keinem Menschen mitgeteilt, was mein Gott mir
eingegeben hatte, für Jerusalem zu tun. Ich nahm keine Tiere mit außer
dem einen, auf dem ich ritt.

<<v13>>
13 So ritt ich bei Nacht zum Taltor hinaus. An der Drachenquelle vorbei
gelangte ich zum Aschentor. Dabei besichtigte ich die Mauern Jerusalems:
Sie waren niedergerissen und die Tore vom Feuer verzehrt. [fn:4]

<<v14>>
14 Ich ritt zum Quelltor und zum Königsteich hinüber. Hier konnte ich
mit dem Reittier nicht mehr vorwärts kommen.

<<v15>>
15 So ging ich bei Nacht das Bachtal hinauf und besichtigte die Mauer.
Dann kehrte ich um und kam durch das Taltor wieder zurück.

<<v16>>
16 Die Vorsteher wussten nicht, wohin ich gegangen war und was ich
vorhatte. Denn ich hatte bis dahin den Juden nichts mitgeteilt, weder
den Priestern noch den Vornehmen, noch den Beamten und den übrigen, die
an dem Werk mitwirken sollten.

<<v17>>
17 Jetzt aber sagte ich zu ihnen: Ihr seht selbst, in welchem Elend wir
leben: Jerusalem liegt in Trümmern und seine Tore sind abgebrannt. Gehen
wir daran und bauen wir die Mauern Jerusalems wieder auf! So machen wir
unserer Schande ein Ende.

<<v18>>
18 Dann berichtete ich ihnen, wie die Hand meines Gottes so gütig über
mir gewesen war und was der König mir zugesagt hatte. Da sagten sie: Wir
wollen ans Werk gehen und bauen. Und sie nahmen die gute Sache in die
Hand.

<<v19>>
19 Als aber Sanballat, der Horoniter, Tobija, der Knecht von Ammon, und
der Araber Geschem davon hörten, verspotteten sie uns und sagten
verächtlich: Was soll das, was ihr da macht? Wollt ihr euch etwa gegen
den König auflehnen? [fn:5]

<<v20>>
20 Ich ließ ihnen antworten: Der Gott des Himmels wird uns Erfolg
verleihen. Wir, seine Knechte, wollen ans Werk gehen und bauen. Ihr
hingegen habt weder einen Anteil (an der Stadt) noch Anrecht (auf sie);
es gibt keine Erinnerung an euch in Jerusalem.\\
\\

* Footnotes

[fn:1] [[file:Esra_4.org::v10][Esra 4,10f]]; [[file:Esra_7.org::v11][7,11]]

[fn:2] [[file:Esra_8.org::v22][Esra 8,22]]

[fn:3] [[file:Esra_8.org::v32][Esra 8,32]]

[fn:4] [[file:Neh_3.org::v13][3,13]]-[[file:Neh_3.org::v15][15]]; [[file:Neh_12.org::v31][12,31]]-[[file:Neh_12.org::v34][34]].[[file:Neh_12.org::v37][37]]

[fn:5] [[file:Esra_4.org::v23][Esra 4,23]]
