#+TITLE: Num 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-14 Sa 22:39]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 5.html

<<verses>>

<<v1>>
* Die Ausweisung der Unreinen: 5,1-4

1 Der Herr sprach zu Mose: [fn:1]

<<v2>>
2 Befiehl den Israeliten, jeden aus dem Lager zu schicken, der an
Aussatz oder an einem Ausfluss leidet, und jeden, der sich an einer
Leiche verunreinigt hat.

<<v3>>
3 Ob Mann oder Frau, schickt sie weg, weist sie aus dem Lager hinaus!
Sie sollen nicht das Lager unrein machen, in dem ich mitten unter ihnen
wohne.

<<v4>>
4 Die Israeliten taten, was der Herr gesagt hatte, und schickten sie aus
dem Lager. Wie der Herr es Mose gesagt hatte, so machten sie es.\\
\\

<<v5>>
* Schadenersatz und Abgaben ans Heiligtum: 5,5-10

5 Der Herr sprach zu Mose:

<<v6>>
6 Sag zu den Israeliten: Wenn ein Mann oder eine Frau etwas, was dem
Herrn gehört, veruntreut hat, also eine von den Sünden begangen hat, wie
sie bei Menschen vorkommen, dann ist dieser Mensch schuldig geworden.

<<v7>>
7 Sie sollen die Sünde, die sie begangen haben, bekennen und der
Schuldige soll das, was er schuldet, voll ersetzen und dem, an dem er
schuldig geworden ist, noch ein Fünftel dazugeben.

<<v8>>
8 Wenn aber der Anspruchsberechtigte keinen Löser hat, dem der Schuldige
Ersatz leisten könnte, dann gehört der geschuldete Betrag dem Herrn
zugunsten des Priesters, ebenso wie der Sühnewidder, mit dem der
Priester für ihn die Sühne erwirkt. [fn:2]

<<v9>>
9 Dem Priester gehören auch alle Weihegeschenke, die die Israeliten zu
ihm bringen.

<<v10>>
10 Jeder kann selbst bestimmen, was er als Weihegeschenk geben will; was
er aber dem Priester gibt, gehört dem Priester. [fn:3]\\
\\

<<v11>>
* Das Eifersuchtsordal: 5,11-31

11 Der Herr sprach zu Mose:

<<v12>>
12 Rede zu den Israeliten und sag ihnen: Angenommen, eine Frau gerät auf
Abwege, sie wird ihrem Mann untreu,

<<v13>>
13 und ein anderer Mann schläft mit ihr, ohne dass es ihr Mann merkt,
angenommen also, sie ist unrein geworden, ohne dass es entdeckt wird,
und es gibt keine Zeugen, weil sie nicht ertappt worden ist,

<<v14>>
14 der Mann aber schöpft Verdacht und wird eifersüchtig auf seine Frau,
die wirklich unrein geworden ist; angenommen aber auch, er schöpft
Verdacht und wird auf seine Frau eifersüchtig, obwohl sie in
Wirklichkeit nicht unrein geworden ist:

<<v15>>
15 In einem solchen Fall soll der Mann seine Frau zum Priester bringen
und soll zugleich die für sie vorgesehene Opfergabe mitbringen: ein
zehntel Efa Gerstenmehl. Er darf kein Öl darauf gießen und keinen
Weihrauch darauf streuen; denn es ist ein Eifersuchtsopfer, ein Opfer
zur Ermittlung der Schuld.

<<v16>>
16 Der Priester führt die Frau hinein und stellt sie vor den Herrn.

<<v17>>
17 Er nimmt heiliges Wasser in einem Tongefäß; dann nimmt er etwas Staub
vom Fußboden der Wohnstätte und streut ihn in das Wasser.

<<v18>>
18 Dann stellt der Priester die Frau vor den Herrn, löst ihr Haar und
legt ihr das Ermittlungsopfer, das heißt das Eifersuchtsopfer, in die
Hände; der Priester aber hält das bittere, fluchbringende Wasser in der
Hand.

<<v19>>
19 Dann beschwört der Priester die Frau und sagt zu ihr: Wenn kein Mann
mit dir geschlafen hat, wenn du deinem Mann nicht untreu gewesen, also
nicht unrein geworden bist, dann wird sich deine Unschuld durch dieses
bittere, fluchbringende Wasser erweisen.

<<v20>>
20 Wenn du aber deinem Mann untreu gewesen, wenn du unrein geworden bist
und wenn ein anderer als dein eigener Mann mit dir geschlafen hat -

<<v21>>
21 und nun soll der Priester die Frau mit einem Fluch beschwören und zu
ihr sprechen -, dann wird der Herr dich zum sprichwörtlichen Beispiel
für einen Fluch und Schwur in deinem Volk machen. Der Herr wird deine
Hüften einfallen und deinen Bauch anschwellen lassen.

<<v22>>
22 Dieses fluchbringende Wasser wird in deine Eingeweide eindringen,
sodass dein Bauch anschwillt und deine Hüften einfallen. Darauf soll die
Frau antworten: Amen, amen.

<<v23>>
23 Der Priester aber schreibt diese Flüche auf und wischt die Schrift
sodann in das bittere Wasser. [fn:4]

<<v24>>
24 Dann gibt er der Frau das bittere, fluchbringende Wasser zu trinken,
damit dieses Fluchwasser in sie eindringt und ihr bittere Schmerzen
bereitet.

<<v25>>
25 Der Priester nimmt aus der Hand der Frau das Eifersuchtsopfer,
schwingt die Opfergabe vor dem Herrn hin und her und bringt sie so dar;
dann legt er sie auf den Altar.

<<v26>>
26 Der Priester nimmt von der Opfergabe eine Hand voll als
Gedächtnisanteil weg und lässt ihn auf dem Altar in Rauch aufgehen. Dann
erst lässt er die Frau das Wasser trinken.

<<v27>>
27 Sobald er sie das Wasser hat trinken lassen, wird das fluchbringende
Wasser in sie eindringen und bittere Schmerzen bewirken, falls sie
unrein und ihrem Mann untreu geworden ist: Es wird ihren Bauch
anschwellen und ihre Hüften einfallen lassen, sodass die Frau in ihrem
Volk zum sprichwörtlichen Beispiel für einen Fluch wird.

<<v28>>
28 Wenn sie aber nicht unrein geworden, sondern rein ist, dann wird sich
zeigen, dass sie unschuldig ist, und sie kann weiterhin Kinder bekommen.

<<v29>>
29 Das ist das Eifersuchtsgesetz für den Fall, dass eine Frau ihren Mann
betrügt und unrein geworden ist

<<v30>>
30 oder dass ein Mann gegen seine Frau Verdacht schöpft, auf sie
eifersüchtig wird und sie vor den Herrn treten lässt. Wenn der Priester
dieses Gesetz auf sie anwendet,

<<v31>>
31 dann ist der Mann von Schuld frei, die Frau aber muss die Folgen
ihrer Schuld tragen.\\
\\

* Footnotes

[fn:1] 1-4: Zur Unreinheit bei Aussatz vgl. die Anmerkung zu
Lev 13,1-46 ([[file:Lev_13.org::v1][Lev 13,1-46]]) und die Einleitung zu Lev. - Alles, was mit dem Tod
zusammenhängt, also auch Leichen und Gräber, wird für unrein erklärt, um
den Totenkult, wie er bei den Nachbarvölkern üblich war, abzuwehren.

[fn:2] Zum Löser vgl. die Anmerkung zu Lev 25,25 [[file:Lev_25.org::v25][Lev 25,25]].

[fn:3] Der Sinn von H ist unklar.

[fn:4] Von Segens- und Fluchformeln erwartet man im Alten
Orient, dass von ihnen die Macht ausgeht, das darin Gesagte
herbeizuführen. Sie gewinnen nach dem Glauben jener Zeit noch an Kraft,
wenn man sie aufschreibt (vgl. die Anmerkung zu Lev 5,1).
