#+TITLE: Num 8 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-14 Sa 22:47]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 8.html

<<verses>>

<<v1>>
* Die Bedienung des Leuchters: 8,1-4

1 Der Herr sprach zu Mose:

<<v2>>
2 Rede zu Aaron und sag zu ihm: Wenn du die Lampen auf den Leuchter
steckst, dann so, dass das Licht der sieben Lampen vom Leuchter aus nach
vorn fällt.

<<v3>>
3 Das tat Aaron; er steckte die Lampen so auf, dass ihr Licht vom
Leuchter aus nach vorn fiel, wie der Herr es Mose aufgetragen hatte.

<<v4>>
4 Der Leuchter war aus Gold getrieben, vom Gestell bis zu den Blüten war
er aus Gold getrieben. Mose hatte den Leuchter nach dem Muster
angefertigt, das der Herr ihm gezeigt hatte. [fn:1]\\
\\

<<v5>>
* Die Weihe und der Dienst der Leviten: 8,5-26

5 Der Herr sprach zu Mose:

<<v6>>
6 Sondere die Leviten von den Israeliten ab und reinige sie!

<<v7>>
7 So sollst du ihre Reinigung vollziehen: Spreng über sie das
Entsündigungswasser! Sie selbst sollen sich an ihrem ganzen Körper mit
einem Schermesser die Haare schneiden, ihre Kleider waschen und sich
reinigen.

<<v8>>
8 Dann sollen sie einen Jungstier nehmen und dazu als Speiseopfer
Feinmehl, das mit Öl vermengt ist. Einen zweiten Jungstier sollst du für
das Sündopfer nehmen.

<<v9>>
9 Dann sollst du die Leviten vor das Offenbarungszelt führen und die
ganze Gemeinde der Israeliten versammeln.

<<v10>>
10 Lass die Leviten vor den Herrn treten! Die Israeliten sollen den
Leviten die Hände auflegen

<<v11>>
11 und Aaron soll an den Leviten im Namen der Israeliten vor den Augen
des Herrn die Weihe vornehmen. Auf diese Weise sollen sie den Dienst des
Herrn antreten.

<<v12>>
12 Die Leviten sollen ihre Hände den Stieren auf den Kopf legen. Dann
richte den einen als Sündopfer und den anderen als Brandopfer für den
Herrn her, um die Leviten zu entsühnen.

<<v13>>
13 Lass die Leviten vor Aaron und seine Söhne treten und vollzieh an
ihnen die Weihe für den Herrn!

<<v14>>
14 Auf diese Weise sollst du die Leviten aus den Israeliten aussondern;
dann gehören die Leviten mir.

<<v15>>
15 Danach sollen die Leviten mit ihrem Dienst am Offenbarungszelt
beginnen. Reinige sie und vollzieh an ihnen die Weihe;

<<v16>>
16 denn sie sind mir von den Israeliten übergeben, als Ersatz für alle,
die den Mutterschoß durchbrechen; als Ersatz für alle erstgeborenen
Israeliten habe ich sie mir genommen.

<<v17>>
17 Denn alle erstgeborenen Israeliten gehören mir, sowohl bei den
Menschen als auch beim Vieh. An dem Tag, an dem ich in Ägypten alle
Erstgeborenen erschlug, habe ich sie als mir heilig erklärt [fn:2]

<<v18>>
18 und habe die Leviten als Ersatz für alle erstgeborenen Israeliten
genommen.

<<v19>>
19 Ich gebe die Leviten dem Aaron und seinen Söhnen; aus dem Kreis der
Israeliten sind sie ihnen übergeben, damit sie am Offenbarungszelt den
Gottesdienst der Israeliten vollziehen und die Israeliten entsühnen.
Dann wird die Israeliten kein Unheil treffen, wenn sie dem Heiligtum zu
nahe kommen.

<<v20>>
20 Mose, Aaron und die ganze Gemeinde der Israeliten taten mit den
Leviten genau das, was der Herr dem Mose hinsichtlich der Leviten
befohlen hatte; das taten die Israeliten mit den Leviten.

<<v21>>
21 Die Leviten ließen sich entsündigen und wuschen ihre Kleider. Aaron
vollzog an ihnen vor den Augen des Herrn die Weihe und entsühnte sie; so
machte er sie rein.

<<v22>>
22 Danach traten die Leviten bei Aaron und seinen Söhnen ihren Dienst am
Offenbarungszelt an. Was der Herr dem Mose hinsichtlich der Leviten
befohlen hatte, das tat man mit ihnen.

<<v23>>
23 Der Herr sprach zu Mose:

<<v24>>
24 Folgendes gilt für die Leviten: Mit fünfundzwanzig Jahren und darüber
ist jeder verpflichtet, am Offenbarungszelt seinen Dienst zu tun.

<<v25>>
25 Mit fünfzig Jahren endet seine Verpflichtung und er braucht keinen
Dienst mehr zu tun;

<<v26>>
26 er kann aber am Offenbarungszelt seinen Brüdern bei der Ausübung
ihrer Pflichten helfen; doch den eigentlichen Dienst soll er nicht
versehen. So sollst du die Dienstpflichten der Leviten ordnen.\\
\\

* Footnotes

[fn:1] Ex 25,31-36.40 [[file:Ex_25.org::v31][Ex 25,31-36.40]]; 37,17-24 [[file:Ex_37.org::v17][Ex 37,17-24]]

[fn:2] 3,11-13 [[file:Num_3.org::v11][Num 3,11-13]]; Ex 13,11-15 [[file:Ex_13.org::v11][Ex 13,11-15]]
