#+TITLE: Num 34 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-26 Do 21:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Num 34.html


<<verses>>

<<v1>>
* Das Verzeichnis der Lagerstationen: 33,1-49

1 Das sind die Wegstrecken, die die Israeliten bei ihrem Auszug aus
Ägypten unter der Führung von Mose und Aaron zurücklegten, nach
Abteilungen geordnet.

<<v2>>
2 Mose schrieb die Orte, an denen sie zu den einzelnen Wegstrecken
aufbrachen, auf Befehl des Herrn auf. Das sind also die Wegstrecken in
der Reihenfolge, in der die Israeliten aufbrachen:

<<v3>>
3 Aus Ramses brachen sie am fünfzehnten Tag des ersten Monats auf. Am
Tag nach dem Paschafest zogen die Israeliten vor den Augen aller Ägypter
voll Zuversicht aus, [fn:1]

<<v4>>
4 während die Ägypter ihre Erstgeborenen begruben, die der Herr bei
ihnen alle erschlagen hatte, und während der Herr an ihren Göttern sein
Strafgericht vollstreckte.

<<v5>>
5 Die Israeliten brachen von Ramses auf und schlugen ihr Lager in Sukkot
auf.

<<v6>>
6 Von Sukkot brachen sie auf und schlugen ihr Lager in Etam, am Rand der
Wüste, auf.

<<v7>>
7 Von Etam brachen sie auf, bogen nach Pi-Hahirot gegenüber Baal-Zefon
ab und schlugen ihr Lager vor Migdol auf.

<<v8>>
8 Von Pi-Hahirot brachen sie auf und zogen mitten durch das Meer in die
Wüste. In der Wüste Etam waren sie drei Tage unterwegs und schlugen dann
ihr Lager in Mara auf. [fn:2]

<<v9>>
9 Von Mara brachen sie auf und kamen nach Elim. In Elim gab es zwölf
Quellen und siebzig Palmen; daher schlugen sie dort ihr Lager auf.

<<v10>>
10 Von Elim brachen sie auf und schlugen ihr Lager am Schilfmeer auf.

<<v11>>
11 Vom Schilfmeer brachen sie auf und schlugen ihr Lager in der Wüste
Sin auf.

<<v12>>
12 Von der Wüste Sin brachen sie auf und schlugen ihr Lager in Dofka
auf.

<<v13>>
13 Von Dofka brachen sie auf und schlugen ihr Lager in Alusch auf.

<<v14>>
14 Von Alusch brachen sie auf und schlugen ihr Lager in Refidim auf;
dort hatte das Volk kein Wasser zu trinken.

<<v15>>
15 Von Refidim brachen sie auf und schlugen ihr Lager in der Wüste Sinai
auf.

<<v16>>
16 Aus der Wüste Sinai brachen sie auf und schlugen ihr Lager in
Kibrot-Taawa auf.

<<v17>>
17 Von Kibrot-Taawa brachen sie auf und schlugen ihr Lager in Hazerot
auf.

<<v18>>
18 Von Hazerot brachen sie auf und schlugen ihr Lager in Ritma auf.

<<v19>>
19 Von Ritma brachen sie auf und schlugen ihr Lager in Rimmon-Perez auf.

<<v20>>
20 Von Rimmon-Perez brachen sie auf und schlugen ihr Lager in Libna auf.

<<v21>>
21 Von Libna brachen sie auf und schlugen ihr Lager in Rissa auf.

<<v22>>
22 Von Rissa brachen sie auf und schlugen ihr Lager in Kehelata auf.

<<v23>>
23 Von Kehelata brachen sie auf und schlugen ihr Lager am Berg Schefer
auf.

<<v24>>
24 Vom Berg Schefer brachen sie auf und schlugen ihr Lager in Harada
auf.

<<v25>>
25 Von Harada brachen sie auf und schlugen ihr Lager in Makhelot auf.

<<v26>>
26 Von Makhelot brachen sie auf und schlugen ihr Lager in Tahat auf.

<<v27>>
27 Von Tahat brachen sie auf und schlugen ihr Lager in Terach auf.

<<v28>>
28 Von Terach brachen sie auf und schlugen ihr Lager in Mitka auf.

<<v29>>
29 Von Mitka brachen sie auf und schlugen ihr Lager in Haschmona auf.

<<v30>>
30 Von Haschmona brachen sie auf und schlugen ihr Lager in Moserot auf.

<<v31>>
31 Von Moserot brachen sie auf und schlugen ihr Lager in Bene-Jaakan
auf.

<<v32>>
32 Von Bene-Jaakan brachen sie auf und schlugen ihr Lager in Hor-Gidgad
auf.

<<v33>>
33 Von Hor-Gidgad brachen sie auf und schlugen ihr Lager in Jotbata auf.

<<v34>>
34 Von Jotbata brachen sie auf und schlugen ihr Lager in Abrona auf.

<<v35>>
35 Von Abrona brachen sie auf und schlugen ihr Lager in Ezjon-Geber auf.

<<v36>>
36 Von Ezjon-Geber brachen sie auf und schlugen ihr Lager in der Wüste
Zin, das heißt Kadesch, auf.

<<v37>>
37 Von Kadesch brachen sie auf und schlugen ihr Lager am Berg Hor am
Rand von Edom auf.

<<v38>>
38 Auf Befehl des Herrn stieg der Priester Aaron auf den Berg Hor und
starb dort im vierzigsten Jahr nach dem Auszug der Israeliten aus
Ägypten, am ersten Tag des fünften Monats. [fn:3]

<<v39>>
39 Aaron war hundertdreiundzwanzig Jahre alt, als er auf dem Berg Hor
starb.

<<v40>>
40 Der kanaanitische König von Arad, der im Negeb, im Süden Kanaans saß,
hörte, dass die Israeliten heranrückten. [fn:4]

<<v41>>
41 Vom Berg Hor brachen sie auf und schlugen ihr Lager in Zalmona auf.

<<v42>>
42 Von Zalmona brachen sie auf und schlugen ihr Lager in Punon auf.

<<v43>>
43 Von Punon brachen sie auf und schlugen ihr Lager in Obot auf.

<<v44>>
44 Von Obot brachen sie auf und schlugen ihr Lager in Ije-Abarim, im
Gebiet von Moab, auf.

<<v45>>
45 Von Ijim brachen sie auf und schlugen ihr Lager in Dibon-Gad auf.

<<v46>>
46 Von Dibon-Gad brachen sie auf und schlugen ihr Lager in
Almon-Diblatajim auf.

<<v47>>
47 Von Almon-Diblatajim brachen sie auf und schlugen ihr Lager im
Abarimgebirge vor Nebo auf.

<<v48>>
48 Vom Abarimgebirge brachen sie auf und schlugen ihr Lager in den
Steppen von Moab am Jordan bei Jericho auf;

<<v49>>
49 ihr Lager am Jordan erstreckte sich von Bet-Jeschimot bis
Abel-Schittim in den Steppen von Moab.\\
\\

<<v50>>
* Die Anweisungen für die Landverteilung: 33,50 - 34,29

50 In den Steppen von Moab, am Jordan bei Jericho, sprach der Herr zu
Mose:

<<v51>>
51 Rede zu den Israeliten und sag zu ihnen: Wenn ihr den Jordan
überschritten und Kanaan betreten habt, [fn:5]

<<v52>>
52 dann vertreibt vor euch alle Einwohner des Landes und vernichtet alle
ihre Götterbilder! Alle ihre aus Metall gegossenen Figuren sollt ihr
vernichten und alle ihre Kulthöhen zerstören.

<<v53>>
53 Dann nehmt das Land in Besitz und lasst euch darin nieder; denn ich
habe es euch zum Besitz gegeben.

<<v54>>
54 Verteilt das Land durch das Los an eure Sippen! Einem großen Stamm
gebt großen Erbbesitz, einem kleinen Stamm gebt kleinen Erbbesitz!
Worauf das Los eines jeden fällt, das soll ihm gehören. Teilt das Land
so unter die Stämme eurer Väter auf! [fn:6]

<<v55>>
55 Wenn ihr die Einwohner des Landes vor euch nicht vertreibt, dann
werden die, die von ihnen übrig bleiben, zu Splittern in euren Augen und
zu Stacheln in eurer Seite. Sie werden euch in dem Land, in dem ihr
wohnt, in eine große Gefahr bringen.

<<v56>>
56 Dann werde ich mit euch machen, was ich mit ihnen machen wollte.


* Footnotes

[fn:1] Ex 14,8 [[file:Ex_14.org::v8][Ex 14,8]]

[fn:2] Ex 14 [[file:Ex_14.org::v1][Ex 14]]

[fn:3] 20,22-29 [[file:Num_20.org::v22][Num 20,22-29]]

[fn:4] 21,1 [[file:Num_21.org::v1][Num 21,1]]

[fn:5] Ex 34,12f [[file:Ex_34.org::v12][Ex 34,12f]]

[fn:6] 26,52-56 [[file:Num_26.org::v52][Num 26,52-56]]
