#+TITLE: Num 24 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-24 Di 17:18]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 24.html


* Num 24

<<verses>>

<<v1>>
1 Bileam aber sah, dass es dem Herrn recht war, wenn er Israel segnete.
Er suchte nicht geheimnisvolle Zeichen, wie er sonst zu tun pflegte,
sondern wandte sein Gesicht der Wüste zu.

<<v2>>
2 Als Bileam aufblickte, sah er Israel im Lager, nach Stämmen geordnet.
Da kam der Geist Gottes über ihn,\\
\\

<<v3>>
3 er begann mit seinem Orakelspruch und sagte: Spruch Bileams, des
Sohnes Beors, /\\
 Spruch des Mannes mit geschlossenem Auge, [fn:1]\\
\\

<<v4>>
4 Spruch dessen, der Gottesworte hört, /\\
 der eine Vision des Allmächtigen sieht, /\\
 der daliegt mit entschleierten Augen:\\
\\

<<v5>>
5 Jakob, wie schön sind deine Zelte, /\\
 wie schön deine Wohnstätten, Israel!\\
\\

<<v6>>
6 Wie Bachtäler ziehen sie sich hin, /\\
 wie Gärten am Strom, /\\
 wie Eichen, vom Herrn gepflanzt, /\\
 wie Zedern am Wasser.\\
\\

<<v7>>
7 Von seinen Schöpfeimern rinnt das Wasser, /\\
 reichlich Wasser hat seine Saat. /\\
 Sein König ist Agag überlegen, /\\
 seine Königsherrschaft erstarkt. [fn:2]\\
\\

<<v8>>
8 Ja, Gott hat ihn aus Ägypten geführt. /\\
 Er hat Hörner wie ein Wildstier. /\\
 Er frißt die Völker, die ihm Feind sind, /\\
 er zermalmt ihre Knochen /\\
 und zerbricht ihre Pfeile.\\
\\

<<v9>>
9 Er duckt sich, liegt da wie ein Löwe, /\\
 wie ein Raubtier. Wer wagt es, ihn aufzujagen? /\\
 Wer dich segnet, ist gesegnet, /\\
 und wer dich verflucht, ist verflucht. [fn:3]\\
\\

<<v10>>
10 Da wurde Balak zornig auf Bileam. Er schlug die Hände zusammen und
sagte zu Bileam: Ich habe dich gerufen, damit du meine Feinde
verwünschst, du aber hast sie schon dreimal gesegnet.

<<v11>>
11 Geh weg, dorthin, woher du gekommen bist! Ich habe versprochen, dir
einen hohen Lohn zu geben, aber Jahwe hat dich daran gehindert, ihn zu
erhalten.

<<v12>>
12 Bileam antwortete Balak: Habe ich nicht gleich zu deinen Boten, die
du zu mir geschickt hast, gesagt:

<<v13>>
13 Auch wenn mir Balak sein Haus voll Silber und Gold gibt, kann ich dem
Befehl des Herrn nicht zuwiderhandeln und nach eigenem Gutdünken Gutes
oder Böses bewirken. Ich muss sagen, was der Herr sagt. [fn:4]

<<v14>>
14 Gut, ich gehe jetzt zu meinem Volk zurück. Ich will dir aber noch
verraten, was dieses Volk deinem Volk in der Zukunft antun wird.\\
\\

<<v15>>
15 Und er begann mit seinem Orakelspruch und sagte: Spruch Bileams, des
Sohnes Beors, /\\
 Spruch des Mannes mit geschlossenem Auge, [fn:5]\\
\\

<<v16>>
16 Spruch dessen, der Gottesworte hört, /\\
 der die Gedanken des Höchsten kennt, /\\
 der eine Vision des Allmächtigen sieht, /\\
 der daliegt mit entschleierten Augen:\\
\\

<<v17>>
17 Ich sehe ihn, aber nicht jetzt, /\\
 ich erblicke ihn, aber nicht in der Nähe: /\\
 Ein Stern geht in Jakob auf, /\\
 ein Zepter erhebt sich in Israel. /\\
 Er zerschlägt Moab die Schläfen /\\
 und allen Söhnen Sets den Schädel. [fn:6]\\
\\

<<v18>>
18 Edom wird sein Eigentum, /\\
 Seïr, sein Feind, wird sein Besitz. /\\
 Israel aber wird mächtig und stark.\\
\\

<<v19>>
19 Aus Jakob steigt einer herab /\\
 und vernichtet alles, was aus der Stadt entkam.\\
\\

<<v20>>
20 Dann sah Bileam Amalek; er begann mit seinem Orakelspruch und sagte:
Amalek war das erste unter den Völkern, /\\
 doch es endet im Untergang.\\
\\

<<v21>>
21 Dann sah Bileam die Keniter; er begann mit seinem Orakelspruch und
sagte: Dein Wohnsitz, Kain, ist sicher und fest, /\\
 dein Nest ist auf Felsen gebaut;\\
\\

<<v22>>
22 doch es wird hinweggefegt werden. /\\
 Nicht mehr lange, dann führt Assur dich weg.\\
\\

<<v23>>
23 Er begann nochmals mit seinem Orakelspruch und sagte: Weh, wer wird
am Leben bleiben, wenn Gott das tut? [fn:7]\\
\\

<<v24>>
24 Schiffe kommen von den Kittäern, /\\
 sie demütigen Assur, sie demütigen Eber. /\\
 Doch auch er endet im Untergang. [fn:8]\\
\\

<<v25>>
25 Dann brach Bileam auf und kehrte in seine Heimat zurück und auch
Balak zog seines Weges.\\
\\

* Footnotes

[fn:1] 24,15f [[file:Num_24.org::v15][Num 24,15f]]

[fn:2] 1 Sam 15,8 [[file:1.Sam_15.org::v8][1 Sam 15,8]]

[fn:3] 22,6 [[file:Num_22.org::v6][Num 22,6]]; Gen 12,3 [[file:Gen_12.org::v3][Gen 12,3]]; 27,29 [[file:Gen_27.org::v29][Gen 27,29]]

[fn:4] 22,18 [[file:Num_22.org::v18][Num 22,18]]

[fn:5] (15-16) 24,3f [[file:Num_24.org::v3][Num 24,3f]]

[fn:6] Wahrscheinlich ist David und sein Sieg über die Moabiter
gemeint.

[fn:7] Der Fragesatz ist in H unklar.

[fn:8] Wer der ist, der im Untergang endet, ist unklar.
