#+TITLE: Num 14 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-22 So 11:45]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 14.html


* Num 14

<<verses>>

<<v1>>
1 Da erhob die ganze Gemeinde ein lautes Geschrei und das Volk weinte
die ganze Nacht.

<<v2>>
2 Alle Israeliten murrten über Mose und Aaron und die ganze Gemeinde
sagte zu ihnen: Wären wir doch in Ägypten oder wenigstens hier in der
Wüste gestorben!

<<v3>>
3 Warum nur will uns der Herr in jenes Land bringen? Etwa damit wir
durch das Schwert umkommen und unsere Frauen und Kinder eine Beute der
Feinde werden? Wäre es für uns nicht besser, nach Ägypten
zurückzukehren?

<<v4>>
4 Und sie sagten zueinander: Wir wollen einen neuen Anführer wählen und
nach Ägypten zurückkehren.

<<v5>>
5 Da warfen sich Mose und Aaron vor der ganzen Gemeindeversammlung der
Israeliten auf ihr Gesicht nieder.

<<v6>>
6 Josua, der Sohn Nuns, und Kaleb, der Sohn Jefunnes, zwei von denen,
die das Land erkundet hatten, zerrissen ihre Kleider

<<v7>>
7 und sagten zu der ganzen Gemeinde der Israeliten: Das Land, das wir
durchwandert und erkundet haben, dieses Land ist überaus schön.

<<v8>>
8 Wenn der Herr uns wohlgesinnt ist und uns in dieses Land bringt, dann
schenkt er uns ein Land, in dem Milch und Honig fließen.

<<v9>>
9 Lehnt euch nur nicht gegen den Herrn auf! Habt keine Angst vor den
Leuten in jenem Land; sie werden unsere Beute. Ihr schützender Schatten
ist von ihnen gewichen, denn der Herr ist mit uns. Habt keine Angst vor
ihnen!

<<v10>>
10 Doch die ganze Gemeinde drohte Mose und Aaron zu steinigen. Da
erschien die Herrlichkeit des Herrn am Offenbarungszelt allen
Israeliten,

<<v11>>
11 und der Herr sprach zu Mose: Wie lange verachtet mich dieses Volk
noch, wie lange noch wollen sie nicht an mich glauben trotz all der
Zeichen, die ich mitten unter ihnen vollbracht habe?

<<v12>>
12 Ich will sie mit der Pest schlagen und vertreiben; aber dich will ich
zu einem Volk machen, das größer und mächtiger ist als dieses.

<<v13>>
13 Da antwortete Mose dem Herrn: Die Ägypter werden hören, dass du
dieses Volk mit deiner Kraft aus ihrer Mitte hierher geführt hast,

<<v14>>
14 und sie werden zu den Einwohnern dieses Landes sagen, sie hätten
gehört, dass du, Herr, mitten in diesem Volk warst, dass du, Herr,
sichtbar erschienen bist, dass deine Wolke über ihnen stand, dass du
ihnen bei Tag in einer Wolkensäule und bei Nacht in einer Feuersäule
vorangegangen bist,

<<v15>>
15 dass du dann aber dieses Volk wie einen einzigen Mann umgebracht
hast. Wenn sie das alles über dich hören, werden die Völker sagen:

<<v16>>
16 Weil Jahwe nicht imstande war, dieses Volk in das Land zu bringen,
das er ihnen mit einem Eid zugesichert hatte, hat er sie in der Wüste
abgeschlachtet.

<<v17>>
17 Gerade jetzt sollte sich die Kraft meines Herrn in ihrer ganzen Größe
zeigen, wie du gesagt hast:

<<v18>>
18 Ich bin Jahwe, langmütig und reich an Huld, der Schuld und Frevel
wegnimmt, der aber (den Sünder) nicht ungestraft lässt, der die Schuld
der Väter an den Söhnen verfolgt, an der dritten und vierten Generation: [fn:1]

<<v19>>
19 Verzeih also diesem Volk seine Sünde nach deiner großen Huld, wie du
diesem Volk auch schon bisher vergeben hast, von Ägypten bis hierher.

<<v20>>
20 Da sprach der Herr: Ich verzeihe ihm, da du mich bittest.

<<v21>>
21 Doch so wahr ich lebe und die Herrlichkeit des Herrn das ganze Land
erfüllt:

<<v22>>
22 Alle Männer, die meine Herrlichkeit und meine Zeichen gesehen haben,
die ich in Ägypten und in der Wüste vollbracht habe und die mich jetzt
schon zum zehnten Mal auf die Probe gestellt und doch nicht auf mich
gehört haben,

<<v23>>
23 sie alle werden das Land nicht zu sehen bekommen, das ich ihren
Vätern mit einem Eid zugesichert habe. Keiner von denen, die mich
verachtet haben, wird es zu sehen bekommen.

<<v24>>
24 Meinen Knecht Kaleb aber, der anders denkt und treu zu mir hält, ihn
werde ich in das Land bringen. Er darf es betreten und seine Nachkommen
sollen es erben.

<<v25>>
25 [Die Amalekiter und die Kanaaniter sitzen in der Ebene.] Brecht also
morgen auf und schlagt eine andere Richtung ein, in die Wüste, zum
Schilfmeer hin!

<<v26>>
26 Der Herr sprach zu Mose und Aaron:

<<v27>>
27 Wie lange soll das mit dieser bösen Gemeinde so weitergehen, die
immer über mich murrt? Ich habe mir das Murren der Israeliten jetzt
lange genug angehört.

<<v28>>
28 Sag ihnen: So wahr ich lebe - Spruch des Herrn -, ich will euch das
antun, womit ihr mir die Ohren vollgeschrien habt: [fn:2]

<<v29>>
29 Hier in der Wüste sollen eure Leichen liegen bleiben, alle ohne
Ausnahme; jeder von euch, der gemustert worden ist, wird sterben, alle
Männer von zwanzig Jahren und darüber, die über mich gemurrt haben.

<<v30>>
30 Keiner von euch wird in das Land kommen, auch wenn ich meine Hand
erhoben und geschworen habe, euch darin wohnen zu lassen, außer Kaleb,
der Sohn Jefunnes, und Josua, der Sohn Nuns.

<<v31>>
31 Eure Kinder aber, von denen ihr gesagt habt, sie würden eine Beute
der Feinde werden, sie werde ich in das Land bringen. Sie werden das
Land kennen lernen, das ihr verschmäht habt. [fn:3]

<<v32>>
32 Eure Leichen aber werden in dieser Wüste liegen bleiben.

<<v33>>
33 Eure Söhne müssen vierzig Jahre lang ihr Vieh in der Wüste weiden
lassen; sie haben so lange unter eurer Untreue zu leiden, bis ihr alle
tot in der Wüste liegt.

<<v34>>
34 So viele Tage, wie ihr gebraucht habt, um das Land zu erkunden,
nämlich vierzig Tage, so viele Jahre lang - für jeden Tag ein Jahr müsst
ihr die Folgen eurer Schuld tragen, also vierzig Jahre lang; dann werdet
ihr erkennen, was es heißt, mir Widerstand zu leisten.

<<v35>>
35 Ich, der Herr, habe gesprochen. Unwiderruflich werde ich es mit
dieser ganzen bösen Gemeinde so machen, die sich gegen mich
zusammengerottet hat: In dieser Wüste finden sie ihr Ende, hier müssen
sie sterben.

<<v36>>
36 Die Männer, die Mose ausgeschickt hatte, um das Land erkunden zu
lassen, die dann aber nach ihrer Rückkehr die ganze Gemeinde zum Murren
verführt hatten, [fn:4]

<<v37>>
37 fielen plötzlich tot zu Boden, vor den Augen des Herrn, alle, die
über das Land falsche Gerüchte verbreitet hatten.

<<v38>>
38 Nur Josua, der Sohn Nuns, und Kaleb, der Sohn Jefunnes, blieben am
Leben, als einzige von allen, die ausgezogen waren, um das Land zu
erkunden.

<<v39>>
39 Mose sagte das alles den Israeliten. Da wurde das Volk sehr traurig.

<<v40>>
40 Sie standen am nächsten Morgen auf, um auf die Höhe des Gebirges zu
steigen; sie sagten: Wir ziehen jetzt zu dem Ort hinauf, den der Herr
genannt hat. Ja, wir haben gesündigt.

<<v41>>
41 Da sagte Mose: Warum übertretet ihr den Befehl des Herrn? Das wird
euch nicht gelingen.

<<v42>>
42 Zieht nicht hinauf, denn der Herr ist nicht bei euch; ihr werdet von
euren Feinden nur geschlagen werden.

<<v43>>
43 Denn ihr habt dort die Amalekiter und die Kanaaniter gegen euch, und
ihr werdet durch das Schwert umkommen. Weil ihr euch vom Herrn
abgewendet habt, wird der Herr nicht mit euch sein.

<<v44>>
44 Doch in ihrem Starrsinn stiegen sie auf die Höhe des Gebirges hinauf.
Aber die Bundeslade des Herrn und Mose wichen nicht von ihrer Stelle
mitten im Lager.

<<v45>>
45 Da kamen die Amalekiter und die Kanaaniter, die dort im Gebirge
wohnten, herunter und schlugen die Israeliten und zersprengten sie bis
nach Horma.\\
\\

* Footnotes

[fn:1] Ex 34,6f [[file:Ex_34.org::v6][Ex 34,6f]]; Ex 20,5 [[file:Ex_20.org::v5][Ex 20,5]]; Dtn 5,9 [[file:Dtn_5.org::v9][Dtn 5,9]]

[fn:2] 14,2 [[file:Num_14.org::v2][Num 14,2]]

[fn:3] 14,3 [[file:Num_14.org::v3][Num 14,3]]

[fn:4] 1 Kor 10,5.10 [[file:~/Documents/notes/Bibel/nt/1.Kor_10.org::v5][1 Kor 10,5]] [[file:~/Documents/notes/Bibel/nt/1.Kor_10.org::v10][1 Kor 10,10]]
