#+TITLE: Num 19 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-23 Mo 09:45]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Num 19.html


<<verses>>

<<v1>>
* Das Reinigungswasser: 19,1-22

1 Der Herr sprach zu Mose und Aaron: [fn:1]

<<v2>>
2 Das ist die Verordnung, die der Herr erlässt: Sag den Israeliten, sie
sollen dir eine fehlerlose, einwandfreie rote Kuh bringen, die noch nie
ein Joch getragen hat.

<<v3>>
3 Übergebt die Kuh dem Priester Eleasar! Dann soll man sie vor das Lager
hinausführen und sie vor seinen Augen schlachten.

<<v4>>
4 Der Priester Eleasar nimmt mit seinem Finger etwas von ihrem Blut und
spritzt damit siebenmal gegen die Vorderseite des Offenbarungszeltes.

<<v5>>
5 Darauf verbrennt man die Kuh vor seinen Augen. Ihr Fell, ihr Fleisch
und ihr Blut, alles soll man verbrennen, samt ihrem Mageninhalt.

<<v6>>
6 Der Priester nimmt Zedernholz, Ysop und Karmesin und wirft alles in
das Feuer, in dem die Kuh verbrannt wird.

<<v7>>
7 Dann wäscht der Priester seine Kleider, badet seinen Körper in Wasser
und kehrt nachher ins Lager zurück; der Priester bleibt aber bis zum
Abend unrein.

<<v8>>
8 Derjenige, der die Kuh verbrannt hat, wäscht seine Kleider und badet
seinen Körper in Wasser; er bleibt aber bis zum Abend unrein.

<<v9>>
9 Ein reiner Mann sammelt die Asche der Kuh und legt sie an einen reinen
Ort außerhalb des Lagers. Sie wird für die Gemeinde der Israeliten zur
Zubereitung des Reinigungswassers aufbewahrt. Es ist ein Sündopfer.

<<v10>>
10 Derjenige, der die Asche der Kuh gesammelt hat, wäscht dann seine
Kleider, bleibt aber bis zum Abend unrein. Für die Israeliten und für
die Fremden, die bei ihnen leben, gilt die feste Regel:

<<v11>>
11 Wer irgendeinen toten Menschen berührt, ist sieben Tage lang unrein.

<<v12>>
12 Am dritten Tag entsündigt er sich mit dem Reinigungswasser und am
siebten Tag wird er rein. Wenn er sich am dritten Tag nicht entsündigt,
dann wird er am siebten Tag nicht rein.

<<v13>>
13 Jeder, der einen toten Menschen, einen Verstorbenen, anrührt und sich
nicht entsündigt, hat die Wohnstätte des Herrn verunreinigt. Ein solcher
Mensch muss aus Israel ausgemerzt werden, weil er sich nicht hat mit dem
Reinigungswasser besprengen lassen. Er ist unrein; seine Unreinheit
haftet ihm immer noch an.

<<v14>>
14 Folgendes Gesetz gilt, wenn ein Mensch in einem Zelt stirbt: Jeder,
der ins Zelt kommt oder der schon im Zelt ist, wird für sieben Tage
unrein;

<<v15>>
15 auch jedes offene Gefäß, das keinen verschnürten Deckel hat, ist
unrein.

<<v16>>
16 Jeder, der auf freiem Feld einen mit dem Schwert Erschlagenen, einen
Toten, menschliche Gebeine oder ein Grab berührt, ist für sieben Tage
unrein.

<<v17>>
17 Für den Unreinen nimmt man etwas Brandasche vom Sündopfer, schüttet
sie in ein Gefäß und gießt Quellwasser darüber.

<<v18>>
18 Ein reiner Mann nimmt Ysop, taucht ihn in das Wasser und bespritzt
damit das Zelt sowie die Gefäße und die Menschen, die im Zelt sind, oder
den, der Gebeine, einen Erschlagenen, einen Toten oder ein Grab berührt
hat.

<<v19>>
19 Der Reine bespritzt den Unreinen am dritten und am siebten Tag und
entsündigt ihn am siebten Tag. Dann wäscht der Betreffende seine Kleider
und badet seinen Körper in Wasser; am Abend ist er dann rein.

<<v20>>
20 Wer aber unrein geworden ist und sich nicht entsündigt, ein solcher
Mensch ist aus der Versammlung auszumerzen; denn er hat das Heiligtum
des Herrn verunreinigt. Er hat sich nicht mit dem Reinigungswasser
besprengen lassen; er ist unrein.

<<v21>>
21 Das soll bei den Israeliten als feste Regel gelten. Auch wer das
Reinigungswasser verspritzt hat, wäscht seine Kleider; wer mit dem
Reinigungswasser in Berührung kommt, ist bis zum Abend unrein.

<<v22>>
22 Alles, was der Unreine berührt, ist unrein. Ebenso ist jeder, der ihn
berührt, bis zum Abend unrein.\\
\\

* Footnotes

[fn:1] 1-13: Rot ist die Farbe des Blutes. Das Reinigungswasser
ist eine Art Weihwasser, das die Reinigung von Sünde und kultischer
Unreinheit symbolisiert (vgl. Hebr 9,13).
