#+TITLE: Num 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-13 Fr 10:33]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Num 2.html

<<verses>>

<<v1>>
* Die Ordnung im Lager und auf dem Marsch: 2,1-34

1 Der Herr sprach zu Mose und Aaron:

<<v2>>
2 Alle Israeliten sollen bei ihren Feldzeichen lagern, jede Großfamilie
mit einer eigenen Fahne. Sie sollen rings um das Offenbarungszelt so
lagern, dass es jeder vor sich hat.

<<v3>>
3 Vorne, nach Osten hin, ist das Lager Judas mit seinem Feldzeichen,
geordnet nach Abteilungen. Befehlshaber der Nachkommen Judas ist
Nachschon, der Sohn Amminadabs;

<<v4>>
4 sein Heer zählt im Ganzen 74600 gemusterte Männer.

<<v5>>
5 Daran anschließend ist das Lager des Stammes Issachar; Befehlshaber
der Issachariter ist Netanel, der Sohn Zuars;

<<v6>>
6 sein Heer zählt im Ganzen 54400 gemusterte Männer.

<<v7>>
7 Dann folgt der Stamm Sebulon; Befehlshaber der Sebuloniter ist Eliab,
der Sohn Helons;

<<v8>>
8 sein Heer zählt im Ganzen 57400 gemusterte Männer.

<<v9>>
9 Die Gesamtzahl der Gemusterten, die zum Lager Judas gehören, beträgt
186400 Mann, geordnet nach Abteilungen. Sie brechen als Erste auf.

<<v10>>
10 Im Süden ist das Lager Rubens mit seinem Feldzeichen, geordnet nach
Abteilungen. Befehlshaber der Rubeniter ist Elizur, der Sohn Schedëurs;

<<v11>>
11 sein Heer zählt im Ganzen 46500 gemusterte Männer.

<<v12>>
12 Daran anschließend ist das Lager des Stammes Simeon; Befehlshaber der
Simeoniter ist Schelumiël, der Sohn Zurischaddais;

<<v13>>
13 sein Heer zählt im Ganzen 59300 gemusterte Männer.

<<v14>>
14 Dann folgt der Stamm Gad; Befehlshaber der Gaditer ist Eljasaf, der
Sohn Reguëls;

<<v15>>
15 sein Heer zählt im Ganzen 45650 gemusterte Männer.

<<v16>>
16 Die Gesamtzahl der Gemusterten, die zum Lager Rubens gehören, beträgt
151450 Mann, geordnet nach Abteilungen. Sie brechen als Zweite auf.

<<v17>>
17 Dann bricht das Offenbarungszelt auf und das Lager der Leviten, das
in der Mitte der Lager liegt. Wie sie lagern, so brechen sie auf, jeder
an seiner Stelle, nach Feldzeichen geordnet.

<<v18>>
18 Im Westen ist das Lager Efraims mit seinem Feldzeichen, geordnet nach
Abteilungen. Befehlshaber der Efraimiter ist Elischama, der Sohn
Ammihuds;

<<v19>>
19 sein Heer zählt im Ganzen 40500 gemusterte Männer.

<<v20>>
20 Daran anschließend kommt der Stamm Manasse; Befehlshaber der
Manassiter ist Gamliël, der Sohn Pedazurs;

<<v21>>
21 sein Heer zählt im Ganzen 32200 gemusterte Männer.

<<v22>>
22 Dann folgt der Stamm Benjamin; Befehlshaber der Benjaminiter ist
Abidan, der Sohn Gidonis;

<<v23>>
23 sein Heer zählt im Ganzen 35400 gemusterte Männer.

<<v24>>
24 Die Gesamtzahl der Gemusterten, die zum Lager Efraims gehören,
beträgt 108100 Mann, geordnet nach Abteilungen. Sie brechen als Dritte
auf.

<<v25>>
25 Im Norden ist das Lager Dans mit seinem Feldzeichen, geordnet nach
Abteilungen. Befehlshaber der Daniter ist Ahiëser, der Sohn
Ammischaddais;

<<v26>>
26 sein Heer zählt im Ganzen 62700 gemusterte Männer.

<<v27>>
27 Daran anschließend ist das Lager des Stammes Ascher; Befehlshaber der
Ascheriter ist Pagiël, der Sohn Ochrans;

<<v28>>
28 sein Heer zählt im Ganzen 41500 gemusterte Männer.

<<v29>>
29 Dann folgt der Stamm Naftali; Befehlshaber der Naftaliter ist Ahira,
der Sohn Enans;

<<v30>>
30 sein Heer zählt im Ganzen 53400 gemusterte Männer.

<<v31>>
31 Die Gesamtzahl der Gemusterten, die zum Lager Dans gehören, beträgt
157600 Mann. Sie brechen als Letzte auf, nach Feldzeichen geordnet.

<<v32>>
32 Das sind also die gemusterten Israeliten, geordnet nach Großfamilien.
Die Gesamtzahl der Gemusterten im Lager, geordnet nach Abteilungen,
beträgt 603550 Mann.

<<v33>>
33 Die Leviten wurden, wie der Herr es Mose befohlen hatte, unter den
Israeliten nicht gemustert.

<<v34>>
34 Die Israeliten führten alles aus, was der Herr dem Mose befohlen
hatte; sie lagerten geordnet nach ihren Feldzeichen und so brachen sie
auch auf, jeder in seiner Sippe und bei seiner Großfamilie.\\
\\
