#+TITLE: Num 30 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-26 Do 21:11]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 30.html


* Num 30
 
<<verses>>

<<v1>>
1 Mose teilte den Israeliten alles genau so mit, wie es ihm der Herr
aufgetragen hatte.\\
\\

<<v2>>
* Die Gültigkeit von Gelübden: 30,2-17

2 Mose sagte zu den Stammeshäuptern der Israeliten: Das befiehlt der
Herr:

<<v3>>
3 Wenn ein Mann dem Herrn ein Gelübde ablegt oder sich durch einen Eid
zu einer Enthaltung verpflichtet, dann darf er sein Wort nicht brechen;
genau so, wie er es ausgesprochen hat, muss er es ausführen.

<<v4>>
4 Wenn aber eine Frau dem Herrn ein Gelübde ablegt oder sich zu einer
Enthaltung verpflichtet, während sie noch ledig im Haus ihres Vaters
lebt,

<<v5>>
5 dann soll ihr Vater von ihrem Gelübde oder von der Enthaltung, zu der
sie sich verpflichtet hat, erfahren. Schweigt ihr Vater dazu, dann
treten die Gelübde oder jede Enthaltung, zu der sie sich verpflichtet
hat, in Kraft;

<<v6>>
6 versagt aber ihr Vater an dem Tag, an dem er davon erfährt, seine
Zustimmung, dann tritt das Gelübde oder die Enthaltung, zu der sie sich
verpflichtet hat, nicht in Kraft; der Herr wird es ihr erlassen, weil
ihr Vater seine Zustimmung versagt hat.

<<v7>>
7 Heiratet sie einen Mann, während sie durch ein Gelübde oder durch ein
voreiliges Wort, mit dem sie sich verpflichtet hat, gebunden ist,

<<v8>>
8 dann bleiben die Gelübde oder die Enthaltung, zu der sie sich
verpflichtet hat, in Kraft, falls ihr Mann an dem Tag, an dem er davon
erfährt, dazu schweigt.

<<v9>>
9 Wenn ihr Mann aber an dem Tag, an dem er davon erfährt, seine
Zustimmung versagt, dann hat er ihr Gelübde, an das sie gebunden war,
oder das voreilige Wort, durch das sie sich verpflichtet hatte, außer
Kraft gesetzt und der Herr wird es ihr erlassen.

<<v10>>
10 Aber das Gelübde einer Witwe oder einer verstoßenen Frau - alles,
wozu sie sich verpflichtet hat - bleibt für sie in Kraft.

<<v11>>
11 Wenn sie im Haus ihres Mannes etwas gelobt oder sich mit einem Eid zu
einer Enthaltung verpflichtet hat,

<<v12>>
12 dann bleiben alle Gelübde und jede Enthaltung, zu der sie sich
verpflichtet hat, in Kraft, wenn ihr Mann zwar davon gehört, aber
geschwiegen und seine Zustimmung nicht versagt hat.

<<v13>>
13 Wenn aber ihr Mann an dem Tag, an dem er davon hörte, ihr Gelübde
oder die Verpflichtung zur Enthaltung, die sie ausgesprochen hat, außer
Kraft gesetzt hat, dann ist alles aufgehoben; ihr Mann hat es außer
Kraft gesetzt und der Herr wird es ihr erlassen.

<<v14>>
14 Ihr Mann kann jedes Gelübde und jeden Eid, der zu einer Enthaltung
verpflichtet, anerkennen oder außer Kraft setzen.

<<v15>>
15 Schweigt ihr Mann dazu von einem Tag bis zum andern, dann erkennt er
alle Gelübde und Verpflichtungen zur Enthaltung an. Er hat sie
anerkannt, denn er hat an dem Tag, an dem er davon erfahren hat,
geschwiegen.

<<v16>>
16 Hat er aber davon erfahren und setzte sie erst später außer Kraft,
dann trägt er dafür die Verantwortung.

<<v17>>
17 Das sind die Gesetze, die der Herr dem Mose aufgetragen hat; sie
gelten für den Mann und seine Frau, für den Vater und seine ledige
Tochter, solange sie noch im Haus ihres Vaters lebt.\\
\\
