#+TITLE: Num 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-16 Mo 13:06]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 12.html


<<verses>>

<<v1>>
* Auflehnung Mirjams und Aarons: 12,1-16

1 Als sie in Hazerot waren, redeten Mirjam und Aaron über Mose wegen der
kuschitischen Frau, die er sich genommen hatte. Er hatte sich nämlich
eine Kuschiterin zur Frau genommen.

<<v2>>
2 Sie sagten: Hat etwa der Herr nur mit Mose gesprochen? Hat er nicht
auch mit uns gesprochen? Das hörte der Herr.

<<v3>>
3 Mose aber war ein sehr demütiger Mann, demütiger als alle Menschen auf
der Erde.

<<v4>>
4 Kurz darauf sprach der Herr zu Mose, Aaron und Mirjam: Geht ihr drei
hinaus zum Offenbarungszelt! Da gingen die drei hinaus.

<<v5>>
5 Der Herr kam in der Wolkensäule herab, blieb am Zelteingang stehen und
rief Aaron und Mirjam. Beide traten vor

<<v6>>
6 und der Herr sprach: Hört meine Worte! Wenn es bei euch einen
Propheten gibt, so gebe ich mich ihm in Visionen zu erkennen und rede
mit ihm im Traum.

<<v7>>
7 Anders bei meinem Knecht Mose. Mein ganzes Haus ist ihm anvertraut.

<<v8>>
8 Mit ihm rede ich von Mund zu Mund, von Angesicht zu Angesicht, nicht
in Rätseln. Er darf die Gestalt des Herrn sehen. Warum habt ihr es
gewagt, über meinen Knecht Mose zu reden?

<<v9>>
9 Der Herr wurde zornig auf sie und ging weg.

<<v10>>
10 Kaum hatte die Wolke das Zelt verlassen, da war Mirjam weiß wie
Schnee vor Aussatz. Aaron wandte sich Mirjam zu und sah: Sie war
aussätzig.

<<v11>>
11 Da sagte Aaron zu Mose: Mein Herr, ich bitte dich, lass uns nicht die
Folgen der Sünde tragen, die wir leichtfertig begangen haben.

<<v12>>
12 Mirjam soll nicht wie eine Totgeburt sein, die schon halb verwest
ist, wenn sie den Schoß der Mutter verlässt.

<<v13>>
13 Da schrie Mose zum Herrn: Ach, heile sie doch!

<<v14>>
14 Der Herr antwortete Mose: Wenn ihr Vater ihr ins Gesicht gespuckt
hätte, müsste sie sich dann nicht sieben Tage lang schämen? Sie soll
sieben Tage lang aus dem Lager ausgesperrt sein; erst dann soll man sie
wieder hereinlassen.

<<v15>>
15 So wurde Mirjam sieben Tage aus dem Lager ausgesperrt. Das Volk brach
nicht auf, bis man Mirjam wieder hereinließ.

<<v16>>
16 Erst nachher brach das Volk von Hazerot auf und schlug dann sein
Lager in der Wüste Paran auf.\\
\\
