#+TITLE: Num 16 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-22 So 11:58]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Num 16.html

<<verses>>

<<v1>>
* Der Aufruhr Korachs, Datans und Abirams: 16,1 - 17,28

1 Korach, der Sohn Jizhars, des Sohnes Kehats, des Sohnes Levis, ferner
Datan und Abiram, die Söhne Eliabs, und On, der Sohn Pallus, der
Rubeniter, [fn:1]

<<v2>>
2 erhoben sich gegen Mose, zusammen mit zweihundertfünfzig führenden
Männern aus der Gemeinde, angesehenen Abgeordneten der Versammlung.

<<v3>>
3 Sie rotteten sich gegen Mose und Aaron zusammen und sagten zu ihnen:
Ihr nehmt euch zu viel heraus. Alle sind heilig, die ganze Gemeinde, und
der Herr ist mitten unter ihnen. Warum erhebt ihr euch über die Gemeinde
des Herrn?

<<v4>>
4 Als Mose das hörte, warf er sich auf sein Gesicht nieder

<<v5>>
5 und er sagte zu Korach und seinem ganzen Anhang: Morgen früh wird der
Herr zeigen, wer zu ihm gehört, wer der Heilige ist und wer sich ihm
nähern darf. Wen der Herr erwählt, der darf sich ihm nähern.

<<v6>>
6 Du, Korach, und dein ganzer Anhang, macht Folgendes: Nehmt euch
Räucherpfannen,

<<v7>>
7 tut Feuer hinein und legt Weihrauch für den Herrn darauf, und zwar
morgen! Dann wird sich zeigen, wen der Herr erwählt und wer der Heilige
ist. Ihr nehmt euch zu viel heraus, ihr Leviten!

<<v8>>
8 Dann sagte Mose zu Korach: Hört, ihr Leviten!

<<v9>>
9 Ist es euch noch zu wenig, dass euch der Gott Israels aus der Gemeinde
Israels herausgehoben hat, um euch in seine Nähe zu holen, damit ihr an
der Wohnstätte des Herrn Dienst tut, vor die Gemeinde tretet und für sie
euren Dienst verrichtet?

<<v10>>
10 Er hat dich und alle deine Brüder, die Leviten, die bei dir sind, in
seine Nähe geholt, doch nun wollt ihr auch noch das Priesteramt.

<<v11>>
11 Deshalb rottet ihr, du und dein ganzer Anhang, euch gegen den Herrn
zusammen. Über ihn, nicht über Aaron, murrt ihr.

<<v12>>
12 Dann ließ Mose Datan und Abiram, die Söhne Eliabs, rufen. Sie aber
ließen ihm sagen: Wir kommen nicht.

<<v13>>
13 Ist es nicht genug, dass du uns aus einem Land, in dem Milch und
Honig fließen, hergeholt hast, um uns in der Wüste sterben zu lassen?
Willst du dich auch noch als unser Herrscher aufspielen?

<<v14>>
14 Du hast uns nicht in ein Land gebracht, in dem Milch und Honig
fließen, und hast uns keine Felder und Weinberge zum Besitz gegeben.
Hältst du diese Männer hier etwa für blind? Wir kommen nicht.

<<v15>>
15 Da wurde Mose sehr zornig und sagte zum Herrn: Sieh ihre Opfer nicht
an! Nicht einen einzigen Esel habe ich ihnen weggenommen, keinem von
ihnen habe ich etwas zuleide getan.

<<v16>>
16 Dann sagte Mose zu Korach: Du und dein ganzer Anhang, erscheint
morgen vor dem Herrn, du, diese Männer und Aaron!

<<v17>>
17 Nehmt eure Räucherpfannen mit, tut Weihrauch hinein und bringt eure
Räucherpfannen vor den Herrn, jeder seine eigene Räucherpfanne, im
Ganzen also zweihundertfünfzig Räucherpfannen, auch du und Aaron, bringt
eure Räucherpfannen mit!

<<v18>>
18 Jeder nahm also seine Räucherpfanne, sie taten Feuer hinein, legten
Weihrauch darauf und traten an den Eingang des Offenbarungszeltes,
zusammen mit Mose und Aaron.

<<v19>>
19 Korach aber versammelte die ganze Gemeinde bei ihnen am Eingang des
Offenbarungszeltes. Da erschien der ganzen Gemeinde die Herrlichkeit des
Herrn.

<<v20>>
20 Der Herr sprach zu Mose und Aaron:

<<v21>>
21 Sondert euch von dieser Gemeinde ab! Ich will ihr auf einen Schlag
ein Ende bereiten.

<<v22>>
22 Da warfen sie sich auf ihr Gesicht nieder und sagten: Gott, du Gott
der Geister, die alle Menschen beleben, ein einzelner Mensch sündigt und
du willst der ganzen Gemeinde zürnen? [fn:2]

<<v23>>
23 Der Herr antwortete Mose:

<<v24>>
24 Sag der Gemeinde: Entfernt euch aus der Nähe der Zelte Korachs,
Datans und Abirams!

<<v25>>
25 Da stand Mose auf und ging zu Datan und Abiram und die Ältesten
Israels folgten ihm.

<<v26>>
26 Dann sagte er zur Gemeinde: Geht aus der Nähe der Zelte dieser
niederträchtigen Leute weg und rührt nichts von dem an, was ihnen
gehört, sonst werdet auch ihr wegen aller ihrer Sünden hingerafft.

<<v27>>
27 Da entfernten sie sich aus der Nähe der Zelte Korachs, Datans und
Abirams. Datan und Abiram waren herausgekommen und standen am Eingang
ihrer Zelte, zusammen mit ihren Frauen, Söhnen und kleinen Kindern.

<<v28>>
28 Dann sagte Mose: Daran sollt ihr erkennen, dass der Herr mich gesandt
hat, damit ich alle diese Taten vollbringe, und dass ich nicht aus
eigenem Antrieb gehandelt habe:

<<v29>>
29 Wenn diese Leute sterben, wie jeder Mensch stirbt, und wenn sie nur
so wie jeder andere Mensch Rechenschaft ablegen müssen, dann hat der
Herr mich nicht gesandt.

<<v30>>
30 Wenn aber der Herr etwas ganz Ungewöhnliches tut, wenn die Erde ihren
Rachen aufreißt und sie verschlingt zusammen mit allem, was ihnen
gehört, wenn sie also lebend in die Unterwelt hinabstürzen, dann werdet
ihr erkennen, dass diese Leute den Herrn beleidigt haben.

<<v31>>
31 Kaum hatte er das gesagt, da spaltete sich der Boden unter ihnen,

<<v32>>
32 die Erde öffnete ihren Rachen und verschlang sie samt ihrem Haus, mit
allen Menschen, die zu Korach gehörten, und mit ihrem ganzen Besitz.

<<v33>>
33 Sie und alles, was zu ihnen gehörte, stürzten lebend in die Unterwelt
hinab. Die Erde deckte sie zu und sie waren aus der Gemeinde
verschwunden.

<<v34>>
34 Alle Israeliten, die um sie herumstanden, liefen weg, als sie sie
schreien hörten; sie sagten: Die Erde wird auch uns noch verschlingen.

<<v35>>
35 Vom Herrn ging ein Feuer aus und fraß die zweihundertfünfzig Männer,
die den Weihrauch dargebracht hatten.

* Footnotes

[fn:1] 1-35: Hier sind zwei einst selbstständige Erzählungen,
eine von Korach und eine von Datan und Abiram, zusammengearbeitet.

[fn:2] 27,16 [[file:Num_27.org::v16][Num 27,16]]
