#+TITLE: Num 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-15 So 14:07]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 9.html

<<verses>>

<<v1>>
* Ergänzung der Paschaordnung: 9,1-14

1 Im ersten Monat des zweiten Jahres nach ihrem Auszug aus Ägypten
sprach der Herr in der Wüste Sinai zu Mose: [fn:1]

<<v2>>
2 Die Israeliten sollen zur festgesetzten Zeit das Paschafest feiern.

<<v3>>
3 Am vierzehnten Tag dieses Monats sollt ihr es in der Abenddämmerung
zur festgesetzten Zeit feiern. Ihr sollt es genau nach den dafür
geltenden Gesetzen und Vorschriften feiern.

<<v4>>
4 Da befahl Mose den Israeliten, das Paschafest zu feiern.

<<v5>>
5 So feierten sie am vierzehnten Tag des ersten Monats in der
Abenddämmerung das Paschafest in der Wüste Sinai. Genau so, wie der Herr
es Mose befohlen hatte, machten es die Israeliten.

<<v6>>
6 Es gab Männer, die unrein waren, weil sie einen Toten berührt hatten,
und die deshalb an jenem Tag das Paschafest nicht feiern konnten. Die
Männer kamen noch am selben Tag zu Mose und Aaron

<<v7>>
7 und sagten zu ihnen: Wir sind unrein, weil wir einen Toten berührt
haben. Warum soll es uns verwehrt sein, zur festgesetzten Zeit wie die
anderen Israeliten dem Herrn unsere Opfergabe darzubringen?

<<v8>>
8 Mose antwortete ihnen: Bleibt da; ich will hören, was euch der Herr
befiehlt.

<<v9>>
9 Der Herr sprach zu Mose:

<<v10>>
10 Sag den Israeliten: Wenn einige von euch oder von euren Nachkommen
unrein sind wegen eines Toten oder wenn sie weit weg auf einer Reise
sind, aber trotzdem das Paschafest für den Herrn feiern wollen,

<<v11>>
11 dann sollen sie es im zweiten Monat am vierzehnten Tag in der
Abenddämmerung feiern; zu ungesäuerten Broten und Bitterkräutern sollen
sie das Paschalamm essen.

<<v12>>
12 Sie sollen davon nichts bis zum nächsten Morgen übrig lassen und
sollen an dem Paschalamm keinen Knochen zerbrechen. Genau so, wie es das
Paschagesetz vorschreibt, sollen sie handeln.

<<v13>>
13 Wer jedoch rein ist und sich nicht auf einer Reise befindet, es aber
trotzdem unterlässt, das Paschafest zu feiern, der soll aus seinen
Stammesgenossen ausgemerzt werden, denn er hat dem Herrn seine Gabe
nicht zur festgesetzten Zeit dargebracht; ein solcher Mensch muss die
Folgen seiner Sünde tragen.

<<v14>>
14 Wenn ein Fremder bei euch lebt und das Paschafest für den Herrn
feiern will, dann soll er es nach dem Paschagesetz und Pascharecht
feiern. Für den Fremden und für den Einheimischen soll bei euch dasselbe
Gesetz gelten.\\
\\

<<v15>>
* Die Wolkensäule über dem heiligen Zelt: 9,15-23

15 An dem Tag, als man die Wohnstätte aufstellte, bedeckte eine Wolke
die Wohnstätte, das Zelt der Bundesurkunde. Am Abend legte sie sich wie
ein Feuerschein über die Wohnstätte und blieb dort bis zum Morgen. [fn:2]

<<v16>>
16 So war es die ganze Zeit: Bei Tag bedeckte die Wolke die Wohnstätte
und bei Nacht der Feuerschein.

<<v17>>
17 Jedes Mal, wenn sich die Wolke über dem Zelt erhob, brachen die
Israeliten auf, und wo sich die Wolke niederließ, dort schlugen die
Israeliten ihr Lager auf.

<<v18>>
18 Nach dem Gebot des Herrn brachen die Israeliten auf und nach dem
Gebot des Herrn schlugen sie ihr Lager auf. Solange die Wolke über der
Wohnstätte lag, blieben sie im Lager.

<<v19>>
19 Auch wenn die Wolke längere Zeit über der Wohnstätte stehen blieb,
achteten die Israeliten auf die Anordnung des Herrn und brachen nicht
auf.

<<v20>>
20 Und wenn die Wolke nur wenige Tage über der Wohnstätte stehen blieb,
blieben sie nach dem Gebot des Herrn nur so lange in ihrem Lager, bis
sie nach dem Gebot des Herrn aufzubrechen hatten.

<<v21>>
21 Wenn die Wolke nur vom Abend bis zum Morgen blieb und sich am Morgen
erhob, dann brachen sie am nächsten Morgen auf. Ob es bei Tag oder bei
Nacht war: wenn die Wolke sich erhob, brachen sie auf.

<<v22>>
22 Ob es zwei Tage dauerte oder einen Monat oder noch länger: wenn die
Wolke über der Wohnstätte anhielt und stehen blieb, dann schlugen die
Israeliten ihr Lager auf und brachen nicht auf; erst wenn sie sich
erhob, brachen sie auf.

<<v23>>
23 Nach dem Gebot des Herrn schlugen sie das Lager auf, nach dem Gebot
des Herrn brachen sie auf. Sie achteten auf die Anordnungen des Herrn,
so wie es ihnen der Herr durch Mose befahl.\\
\\

* Footnotes

[fn:1] (1-14) Ex 12,1-20.43-49 [[file:Ex_12.org::v1][Ex 12,1-20.43-49]]

[fn:2] (15-18) Ex 40,34-38 [[file:Ex_40.org::v34][Ex 40,34-38]]
