#+TITLE: Num 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-23 Mo 09:41]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 18.html


<<verses>>

<<v1>>
* Der Dienst und die Entlohnung der Priester und Leviten: 18,1-32

1 Der Herr sprach zu Aaron: Du, deine Söhne und deine ganze Familie, ihr
tragt die Verantwortung für das Heiligtum; du und mit dir deine Söhne,
ihr tragt die Verantwortung für euer Priesteramt.

<<v2>>
2 Aber auch deine Brüder, den Stamm Levi, deinen väterlichen Stamm, lass
zusammen mit dir herkommen! Sie sollen sich dir anschließen und dir
dienen, während ihr, du und deine Söhne, vor dem Offenbarungszelt seid.

<<v3>>
3 Sie sollen sich an deine Anordnungen und an die für das ganze Zelt
geltende Ordnung halten. Nur den heiligen Geräten und dem Altar dürfen
sie nicht zu nahe kommen, sonst müssen sie sterben und ihr mit ihnen.

<<v4>>
4 Sie sollen sich dir anschließen und sich beim ganzen Dienst am Zelt an
die Ordnung halten, die am Offenbarungszelt gilt. Kein Unbefugter darf
in eure Nähe kommen.

<<v5>>
5 Wenn ihr euch an die Ordnung haltet, die am Heiligtum und am Altar
gilt, wird der Zorn (Gottes) nicht mehr über die Israeliten kommen.

<<v6>>
6 Seht, ich habe eure Brüder, die Leviten, aus den Israeliten euch
übergeben; sie sind dem Herrn übergeben, um den Dienst am
Offenbarungszelt zu verrichten.

<<v7>>
7 Du aber und mit dir deine Söhne, ihr sollt euer Priesteramt in allem
ausüben, was den Altar und den Raum hinter dem Vorhang betrifft; dort
sollt ihr euren Dienst tun. Als einen Dienst, der ein Geschenk ist,
übergebe ich euch das Priesteramt. Wer sich nähert, ohne dazu befugt zu
sein, ist mit dem Tod zu bestrafen.

<<v8>>
8 Der Herr sagte zu Aaron: Ich selbst übergebe dir jetzt die Verwaltung
der Abgaben, die mir entrichtet werden. Von allen heiligen Gaben der
Israeliten gebe ich sie dir als Anteil und deinen Söhnen als ein
dauerndes Anrecht.

<<v9>>
9 Dir soll an den hochheiligen Gaben all das zufallen, was nicht für das
Feuer bestimmt ist: alle ihre Opfergaben bei allen ihren Speise-, Sünd-
und Schuldopfern, die sie mir als hochheilige Gaben entrichten; dir und
deinen Söhnen gehören sie.

<<v10>>
10 Esst sie am hochheiligen Ort! Jede männliche Person darf davon essen;
sie sollen dir als heilig gelten.

<<v11>>
11 Auch das gehört dir: die Abgabe, die die Israeliten bei allem
entrichten, was sie darbringen. Dir und deinen Söhnen und Töchtern, die
bei dir sind, habe ich diese Abgabe als dauerndes Anrecht gegeben.
Jeder, der rein ist in deinem Haus, darf davon essen.

<<v12>>
12 Das Beste von allem Öl, das Beste von allem Most und Getreide, die
Erstlingsgaben, die sie dem Herrn entrichten, sie habe ich für dich
bestimmt.

<<v13>>
13 Von allem, was es in ihrem Land gibt, gehören dir die
Erstlingsfrüchte, die sie dem Herrn bringen. Jeder, der rein ist in
deinem Haus, darf davon essen.

<<v14>>
14 Alles, was in Israel geweiht wird, gehört dir.

<<v15>>
15 Alle lebenden Wesen, die den Mutterschoß durchbrechen und die man dem
Herrn darbringt, Mensch und Vieh, gehören dir. Du musst aber den
Erstgeborenen bei den Menschen auslösen und ebenso musst du auch die
erstgeborenen Tiere bei unreinem Vieh auslösen,

<<v16>>
16 und zwar musst du die, die ausgelöst werden, im Alter von etwa einem
Monat, je nachdem, wie du sie einschätzt, mit Geld auslösen, mit fünf
Schekel, gerechnet nach dem Schekelgewicht des Heiligtums, das sind
zwanzig Gera.

<<v17>>
17 Aber die Erstlinge vom Rind, vom Schaf oder von der Ziege darfst du
nicht auslösen; sie sind heilig. Ihr Blut sollst du auf den Altar
sprengen und ihre Fettteile als Feueropfer zum beruhigenden Duft für den
Herrn in Rauch aufgehen lassen.

<<v18>>
18 Ihr Fleisch gehört dir, wie auch die Brust vom Darbringungsritus und
auch die rechte Keule dir gehören.

<<v19>>
19 Alle Abgaben von den heiligen Opfern, die die Israeliten dem Herrn
entrichten, habe ich dir und deinen Söhnen und Töchtern, die bei dir
sind, als dauerndes Anrecht gegeben. Das soll für dich und auch für
deine Nachkommen als ein ewiger «Salzbund» vor dem Herrn gelten. [fn:1]

<<v20>>
20 Der Herr sprach zu Aaron: Du sollst in ihrem Land keinen erblichen
Besitz haben. Dir gehört unter ihnen kein Besitzanteil; ich bin dein
Besitz und dein Erbteil mitten unter den Israeliten.

<<v21>>
21 Den Leviten gebe ich als Erbteil den ganzen Zehnten, den die
Israeliten entrichten, als Entgelt für den Dienst, den die Leviten
verrichten, den Dienst am Offenbarungszelt.

<<v22>>
22 Die Israeliten dürfen künftig nicht mehr in die Nähe des
Offenbarungszeltes kommen; sonst laden sie eine Sünde auf sich und
sterben.

<<v23>>
23 Nur der Levit soll am Offenbarungszelt Dienst tun; die Leviten tragen
die Verantwortung - das soll bei euch von Generation zu Generation als
feste Regel gelten. Darum sollen sie unter den Israeliten keinen
Erbbesitz haben.

<<v24>>
24 Denn als Erbteil für die Leviten habe ich die Zehnten bestimmt, die
die Israeliten dem Herrn als Abgabe entrichten. Darum habe ich zu den
Leviten gesagt, sie sollen keinen Erbbesitz unter den Israeliten
bekommen.

<<v25>>
25 Der Herr sprach zu Mose:

<<v26>>
26 Rede zu den Leviten und sag zu ihnen: Wenn ihr von den Israeliten den
Zehnten entgegennehmt, den ich euch von ihnen als euren Anteil
zugewiesen habe, dann entrichtet davon dem Herrn eine Abgabe als Zehnten
vom Zehnten!

<<v27>>
27 Das soll als eure Abgabe angerechnet werden wie bei den anderen die
Abgabe vom Getreide der Tenne und vom Inhalt der Kelter.

<<v28>>
28 So sollt auch ihr dem Herrn eine Abgabe von allen euch zustehenden
Zehnten entrichten, die ihr von den Israeliten erhaltet; diese Abgabe
für den Herrn sollt ihr dem Priester Aaron übergeben.

<<v29>>
29 Von allem, was man euch gibt, sollt ihr die ganze Abgabe für den
Herrn leisten, von allem das Beste, als heilige Gabe.

<<v30>>
30 Ferner sag zu ihnen: Wenn ihr davon das Beste abliefert, wird es den
Leviten angerechnet wie den anderen der Ertrag von Tenne und Kelter.

<<v31>>
31 Diesen dürft ihr überall essen, ihr und eure Familien, denn es gehört
euch als Lohn für euren Dienst am Offenbarungszelt.

<<v32>>
32 Ihr dürft aber keine Sünde auf euch laden, wenn ihr selbst das Beste
abzugeben habt, und ihr dürft die heiligen Gaben der Israeliten nicht
entweihen. Wenn ihr das befolgt, werdet ihr nicht sterben.\\
\\

* Footnotes

[fn:1] Salzbund: Der Ausdruck kommt vielleicht daher, dass
durch gemeinsames Essen von Salz ein Freundschaftsverhältnis besiegelt
wurde (vgl. Lev 2,13 und 2 Chr 13,5).
