#+TITLE: Num 26 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-24 Di 17:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 26.html


* Num 26

<<verses>>

<<v1>>
1 sagte der Herr zu Mose und zu dem Priester Eleasar, dem Sohn Aarons: [fn:1]

<<v2>>
2 Ermittelt die Gesamtzahl der Gemeinde aller Israeliten, die zwanzig
Jahre und älter sind, aller wehrfähigen Israeliten, nach Großfamilien
geordnet.

<<v3>>
3 Da redeten Mose und der Priester Eleasar zu den Israeliten in den
Steppen von Moab, am Jordan bei Jericho,

<<v4>>
4 zu allen Männern von zwanzig Jahren und darüber, wie der Herr es Mose
befohlen hatte. Das sind die Israeliten, die aus Ägypten ausgezogen
waren:

<<v5>>
5 Ruben war der Erstgeborene Israels. Zu den Rubenitern gehörten von
Henoch die Sippe der Henochiter, von Pallu die Sippe der Palluiter,

<<v6>>
6 von Hezron die Sippe der Hezroniter, von Karmi die Sippe der Karmiter.

<<v7>>
7 Das waren die Sippen der Rubeniter. Die Zahl der bei ihnen Gemusterten
betrug 43730 Mann.

<<v8>>
8 Der Sohn Pallus war Eliab;

<<v9>>
9 die Söhne Eliabs: Nemuël, Datan und Abiram. Datan und Abiram waren die
Abgeordneten der Gemeinde, die mit Mose und Aaron in Streit geraten
waren, zusammen mit den Anhängern Korachs, als diese mit dem Herrn in
Streit geraten waren.

<<v10>>
10 Die Erde tat ihren Rachen auf und verschlang sie und Korach, als
seine Anhänger ums Leben kamen; das Feuer fraß die zweihundertfünfzig
Mann und sie wurden zu einem warnenden Zeichen. [fn:2]

<<v11>>
11 Die Söhne Korachs waren aber dabei nicht ums Leben gekommen.

<<v12>>
12 Zu den Simeonitern gehörten folgende Sippen: von Jemuël die Sippe der
Jemuëliter, von Jamin die Sippe der Jaminiter, von Jachin die Sippe der
Jachiniter,

<<v13>>
13 von Serach die Sippe der Serachiter, von Schaul die Sippe der
Schauliter.

<<v14>>
14 Das waren die Sippen der Simeoniter, im Ganzen 22200 Mann.

<<v15>>
15 Zu den Gaditern gehörten folgende Sippen: von Zifjon die Sippe der
Zifjoniter, von Haggi die Sippe der Haggiter, von Schuni die Sippe der
Schuniter,

<<v16>>
16 von Osni die Sippe der Osniter, von Eri die Sippe der Eriter,

<<v17>>
17 von Arod die Sippe der Aroditer, von Areli die Sippe der Areliter.

<<v18>>
18 Das waren die Sippen der Gaditer mit ihren Gemusterten, im Ganzen
40500 Mann.

<<v19>>
19 Die Söhne Judas waren: Er und Onan; Er und Onan aber waren in Kanaan
gestorben. [fn:3]

<<v20>>
20 Zu Juda gehörten folgende Sippen: von Schela die Sippe der
Schelaniter, von Perez die Sippe der Pereziter, von Serach die Sippe der
Serachiter.

<<v21>>
21 Zu den Perezitern gehörten von Hezron die Sippe der Hezroniter und
von Hamul die Sippe der Hamuliter.

<<v22>>
22 Das waren die Sippen Judas mit ihren Gemusterten, im Ganzen 76 500
Mann.

<<v23>>
23 Zu den Issacharitern gehörten folgende Sippen: von Tola die Sippe der
Tolaiter, von Puwa die Sippe der Puwaniter,

<<v24>>
24 von Jaschub die Sippe der Jaschubiter, von Schimron die Sippe der
Schimroniter.

<<v25>>
25 Das waren die Sippen Issachars mit ihren Gemusterten, im Ganzen 64300
Mann.

<<v26>>
26 Zu den Sebulonitern gehörten folgende Sippen: von Sered die Sippe der
Serediter, von Elon die Sippe der Eloniter, von Jachleel die Sippe der
Jachleeliter.

<<v27>>
27 Das waren die Sippen der Sebuloniter mit ihren Gemusterten, im Ganzen
60500 Mann.

<<v28>>
28 Bei den Josefstämmen Manasse und Efraim gehörten folgende Sippen

<<v29>>
29 zu den Manassitern: von Machir die Sippe der Machiriter; Machir
zeugte Gilead und von Gilead stammt die Sippe der Gileaditer.

<<v30>>
30 Das sind die Gileaditer: von Iëser die Sippe der Iëseriter, von Helek
die Sippe der Helekiter,

<<v31>>
31 von Asriël die Sippe der Asriëliter, von Schechem die Sippe der
Schechemiter,

<<v32>>
32 von Schemida die Sippe der Schemidaiter, von Hefer die Sippe der
Heferiter.

<<v33>>
33 Zelofhad, der Sohn Hefers, hatte keine Söhne, sondern nur Töchter;
die Töchter Zelofhads hießen Machla, Noa, Hogla, Milka und Tirza. [fn:4]

<<v34>>
34 Das waren die Sippen Manasses mit ihren Gemusterten, im Ganzen 52700
Mann.

<<v35>>
35 Zu den Efraimitern gehörten folgende Sippen: von Schutelach die Sippe
der Schutelachiter, von Becher die Sippe der Becheriter, von Tahan die
Sippe der Tahaniter.

<<v36>>
36 Zu den Schutelachitern gehört von Eran die Sippe der Eraniter.

<<v37>>
37 Das waren die Sippen der Efraimiter mit ihren Gemusterten, im Ganzen
32500 Mann. Das waren die Josefstämme nach ihren Sippen.

<<v38>>
38 Zu den Benjaminitern gehörten folgende Sippen: von Bela die Sippe der
Belaiter, von Aschbel die Sippe der Aschbeliter, von Ahiram die Sippe
der Ahiramiter,

<<v39>>
39 von Schufam die Sippe der Schufamiter, von Hufam die Sippe der
Hufamiter.

<<v40>>
40 Die Söhne Belas waren Ard und Naaman; von Ard stammt die Sippe der
Arditer, von Naaman die Sippe der Naamaniter.

<<v41>>
41 Das waren die Benjaminiter nach ihren Sippen; die Zahl der bei ihnen
Gemusterten betrug 45600 Mann.

<<v42>>
42 Zu den Danitern gehörten folgende Sippen: von Schuham die Sippe der
Schuhamiter. Das waren die Sippen Dans.

<<v43>>
43 Die Zahl der Gemusterten bei den Sippen der Schuhamiter betrug im
Ganzen 64400 Mann.

<<v44>>
44 Zu den Ascheritern gehörten folgende Sippen: von Jimna die Sippe der
Jimnaiter, von Jischwi die Sippe der Jischwiter, von Beria die Sippe der
Beriaiter.

<<v45>>
45 Zu den Beriaitern gehörten folgende Sippen: von Heber die Sippe der
Heberiter, von Malkiël die Sippe der Malkiëliter.

<<v46>>
46 Die Tochter Aschers hieß Serach.

<<v47>>
47 Das waren die Sippen der Ascheriter mit ihren Gemusterten, im Ganzen
53400 Mann.

<<v48>>
48 Zu den Naftalitern gehörten folgende Sippen: von Jachzeel die Sippe
der Jachzeeliter, von Guni die Sippe der Guniter,

<<v49>>
49 von Jezer die Sippe der Jezeriter, von Schillem die Sippe der
Schillemiter.

<<v50>>
50 Das waren die Sippen Naftalis. Die Zahl der bei ihnen Gemusterten
betrug 45400 Mann.

<<v51>>
51 Die Gesamtzahl der gemusterten Israeliten betrug 601730 Mann.

<<v52>>
52 Der Herr sprach zu Mose:

<<v53>>
53 An diese Männer soll das Land als Erbbesitz verteilt werden,
entsprechend der Zahl der verzeichneten Namen.

<<v54>>
54 Wer mehr Namen zählt, dem sollst du einen größeren Erbbesitz geben;
wer weniger zählt, dem sollst du einen kleineren Erbbesitz geben. Jedem
soll sein Erbbesitz entsprechend der Zahl der bei ihm Gemusterten
gegeben werden.

<<v55>>
55 Doch soll das Land durch das Los verteilt werden und sie sollen ihren
Erbbesitz nach den Namen der Stämme ihrer Väter erhalten.

<<v56>>
56 Der Erbbesitz soll durch das Los zwischen den großen und den kleinen
Stämmen aufgeteilt werden.

<<v57>>
57 Zu den im Stamm Levi Gemusterten gehörten folgende Sippen: von
Gerschon die Sippe der Gerschoniter, von Kehat die Sippe der Kehatiter,
von Merari die Sippe der Merariter.

<<v58>>
58 Das sind die Sippen Levis: die Sippe der Libniter, die Sippe der
Hebroniter, die Sippe der Machliter, die Sippe der Muschiter, die Sippe
der Korachiter. Kehat zeugte Amram.

<<v59>>
59 Die Frau Amrams hieß Jochebed; sie war die Tochter Levis, die dem
Levi noch in Ägypten geboren wurde. Sie gebar dem Amram Aaron und Mose
sowie deren Schwester Mirjam.

<<v60>>
60 Dem Aaron wurden Nadab, Abihu, Eleasar und Itamar geboren. [fn:5]

<<v61>>
61 Nadab und Abihu aber waren gestorben, als sie dem Herrn ein
unerlaubtes Feueropfer darbrachten.

<<v62>>
62 Bei den Leviten wurden im Ganzen 23000 Mann gemustert, alle
männlichen Personen im Alter von einem Monat und darüber. Sie wurden
aber nicht zusammen mit den Israeliten gemustert; denn ihnen wurde kein
Erbbesitz wie den anderen Israeliten gegeben.

<<v63>>
63 Das waren die von Mose und dem Priester Eleasar gemusterten
Israeliten, die sie in den Steppen von Moab am Jordan bei Jericho
gemustert hatten.

<<v64>>
64 Unter ihnen war niemand mehr von denen, die Mose und der Priester
Aaron in der Wüste Sinai gemustert hatten. [fn:6]

<<v65>>
65 Denn über sie hatte der Herr ja gesagt: Sie müssen in der Wüste
sterben. Daher war keiner von ihnen am Leben geblieben außer Kaleb, der
Sohn Jefunnes, und Josua, der Sohn Nuns. [fn:7]\\
\\

* Footnotes

[fn:1] (1-65) 1,1-54 [[file:Num_1.org::v1][Num 1,1-54]]

[fn:2] 16,1-35 [[file:Num_16.org::v1][Num 16,1-35]]

[fn:3] Gen 38,3-10 [[file:Gen_38.org::v3][Gen 38,3-10]]

[fn:4] 27,1-11 [[file:Num_27.org::v1][Num 27,1-11]]

[fn:5] 3,2.4 [[file:Num_33.org::v2][Num 3,2.4]]; Lev 10,1-5 [[file:Lev_10.org::v1][Lev 10,1-5]]

[fn:6] 1 [[file:Num_1.org::v1][Num 1]]; 3 [[file:Num_3.org::v1][Num 3]]

[fn:7] 14,21-35 [[file:Num_14.org::v21][Num 14,21-35]]
