#+TITLE: Num 32 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-10-26 Do 21:14]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Num 32.html

<<verses>>

<<v1>>
* Die Landzuteilung an die ostjordanischen Stämme: 32,1-42

1 Die Rubeniter und die Gaditer hatten sehr große Viehherden. Als sie
nun das Land Jaser und das Land Gilead sahen, erschien ihnen diese
Gegend gut geeignet für ihre Viehhaltung.

<<v2>>
2 Darum kamen sie zu Mose, zu dem Priester Eleasar und zu den Anführern
der Gemeinde und sagten:

<<v3>>
3 Atarot, Dibon, Jaser, Nimra, Heschbon, Elale, Sibma, Nebo und Beon,

<<v4>>
4 das Land, das der Herr für die Gemeinde Israel erobert hat, ist gut
geeignet für die Viehhaltung und deine Knechte haben Viehherden.

<<v5>>
5 Sie sagten: Wenn wir dein Wohlwollen gefunden haben, dann gebe man
dieses Land deinen Knechten als Besitz. Nimm uns nicht über den Jordan
mit!

<<v6>>
6 Mose antwortete den Gaditern und den Rubenitern: Sollen eure Brüder in
den Krieg ziehen, während ihr hier sitzen bleibt?

<<v7>>
7 Warum wollt ihr den Israeliten den Mut nehmen, in das Land
hinüberzuziehen, das der Herr für sie bestimmt hat?

<<v8>>
8 Genauso haben es schon eure Väter gemacht, als ich sie von
Kadesch-Barnea ausgeschickt hatte, damit sie das Land erkundeten.

<<v9>>
9 Sie waren bis zum Traubental hinaufgekommen, hatten das Land gesehen
und haben dann den Israeliten den Mut genommen, sodass sie das Land
nicht mehr betreten wollten, das der Herr für sie bestimmt hatte. [fn:1]

<<v10>>
10 Damals entbrannte der Zorn des Herrn und er schwor: [fn:2]

<<v11>>
11 Auf keinen Fall werden die, die aus Ägypten heraufgekommen sind, die
Männer von zwanzig Jahren und darüber, das Land zu sehen bekommen, das
ich Abraham, Isaak und Jakob mit einem Eid zugesichert habe; denn sie
haben nicht treu zu mir gehalten.

<<v12>>
12 Nur der Kenasiter Kaleb, der Sohn Jefunnes, und Josua, der Sohn Nuns,
waren ausgenommen, denn sie hielten treu zum Herrn.

<<v13>>
13 Der Zorn des Herrn entbrannte über Israel und er ließ sie vierzig
Jahre lang in der Wüste umherirren, bis die ganze Generation
ausgestorben war, die getan hatte, was dem Herrn missfiel.

<<v14>>
14 Und jetzt kommt ihr anstelle eurer Väter, ihr Brut von Sündern, um
den glühenden Zorn des Herrn auf Israel noch größer zu machen?

<<v15>>
15 Wenn ihr euch von ihm abwendet, wird er dieses ganze Volk noch länger
in der Wüste lassen und ihr richtet das ganze Volk zugrunde.

<<v16>>
16 Doch sie traten noch näher an Mose heran und sagten: Wir errichten
hier Pferche für unser Vieh, unsere Schafe und Ziegen, und bauen Städte
für unsere Kinder.

<<v17>>
17 Wir selbst aber rüsten uns und ziehen bewaffnet vor den Israeliten
her, bis wir sie in ihr Land gebracht haben. Unterdessen werden unsere
Kinder in den Städten wohnen, die zum Schutz gegen die Einwohner des
Landes befestigt sind.

<<v18>>
18 Wir kehren nicht in unsere Häuser zurück, bevor jeder Israelit seinen
Erbbesitz erhalten hat.

<<v19>>
19 Wir verlangen auf der anderen Seite des Jordan keinen Erbbesitz wie
sie, wenn wir diesseits, östlich des Jordan, unseren Erbbesitz bekommen.

<<v20>>
20 Mose antwortete ihnen: Wenn ihr das tut, wenn ihr euch also vor den
Augen des Herrn zum Kampf rüstet

<<v21>>
21 und jeder von euch, der sich gerüstet hat, vor den Augen des Herrn
den Jordan überschreitet und kämpft, bis er seine Feinde vertrieben hat

<<v22>>
22 und das Land dem Herrn unterworfen ist, dann dürft ihr nachher
umkehren und ihr seid gegenüber dem Herrn und Israel frei von weiteren
Verpflichtungen. Dann soll dieses Land vor den Augen des Herrn euch als
Eigentum gehören.

<<v23>>
23 Wenn ihr das aber nicht tut, versündigt ihr euch gegen den Herrn.
Dann habt ihr die Folgen für eure Sünde zu tragen; das müsst ihr wissen.

<<v24>>
24 Baut euch Städte für eure Kinder und errichtet Pferche für eure
Schafe und Ziegen! Aber haltet auch, was ihr versprochen habt.

<<v25>>
25 Da sagten die Gaditer und die Rubeniter zu Mose: Deine Knechte werden
tun, was mein Herr befiehlt.

<<v26>>
26 Unsere Kinder, unsere Frauen und unsere Herden, unser ganzes Vieh,
werden dort in den Städten von Gilead bleiben.

<<v27>>
27 Alle deine Knechte aber werden sich rüsten und vor den Augen des
Herrn über den Jordan in den Krieg ziehen, wie mein Herr befiehlt.

<<v28>>
28 Für sie gab Mose dem Priester Eleasar, Josua, dem Sohn Nuns, und den
Familienhäuptern der israelitischen Stämme folgende Weisung:

<<v29>>
29 Er sagte zu ihnen: Wenn die Gaditer und die Rubeniter, zum Kampf
gerüstet, vor den Augen des Herrn mit euch den Jordan überschreiten und
wenn ihr das Land unterworfen habt, dann gebt ihnen das Land Gilead zum
Besitz!

<<v30>>
30 Wenn sie sich aber nicht rüsten und mit euch hinübergehen, dann
sollen sie mitten unter euch in Kanaan eigenen Grund und Boden erhalten.

<<v31>>
31 Die Gaditer und die Rubeniter antworteten: Was der Herr zu deinen
Knechten sagt, werden wir tun.

<<v32>>
32 Wir rüsten uns und ziehen vor den Augen des Herrn nach Kanaan
hinüber, dann bleibt uns jenseits des Jordan unser Erbbesitz erhalten.

<<v33>>
33 Da übergab Mose den Gaditern, den Rubenitern und dem halben Stamm des
Manasse, des Sohnes Josefs, das Reich des Amoriterkönigs Sihon und das
Reich Ogs, des Königs des Baschan, das Land mit seinen Städten und deren
ganzen Umgebung, soweit das Land reichte.

<<v34>>
34 Die Gaditer erbauten die befestigten Städte Dibon, Atarot, Aroër,

<<v35>>
35 Atrot-Schofan, Jaser, Jogboha,

<<v36>>
36 Bet-Nimra und Bet-Haran und errichteten Schafpferche.

<<v37>>
37 Die Rubeniter erbauten Heschbon, Elale, Kirjatajim,

<<v38>>
38 Nebo und Baal-Meon, denen sie andere Namen gaben, sowie Sibma. Sie
gaben nämlich den Städten, die sie wieder aufbauten, neue Namen.

<<v39>>
39 Die Söhne Machirs, des Sohnes des Manasse, zogen nach Gilead und
eroberten es. Sie vertrieben die Amoriter, die dort lebten.

<<v40>>
40 Da übergab Mose Gilead dem Machir, dem Sohn des Manasse, und Machir
ließ sich dort nieder.

<<v41>>
41 Jaïr, der Sohn des Manasse, zog in den Kampf und eroberte die
Zeltdörfer der Amoriter; er nannte sie Hawot-Jaïr (Zeltdörfer Jaïrs).

<<v42>>
42 Nobach zog in den Kampf, eroberte Kenat und seine Tochterstädte und
nannte es nach seinem eigenen Namen Nobach.\\
\\


* Footnotes

[fn:1] 14,1-38 [[file:Num_14.org::v1][Num 14,1-38]]

[fn:2] (10-12) 14,21-24.30f [[file:Num_14.org::v21][Num 14,21-24]] [[file:Num_14.org::v30][Num 14,30]]
