#+TITLE: Ps 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-04 Mo 22:25]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ps 18.html

* Ps 18

<<verses>>

<<v1>>
* Ein Danklied des Königs für Rettung und Sieg

1 [Für den Chormeister. Von David, dem Knecht des Herrn, der dem Herrn
die Worte dieses Liedes sang an dem Tag, als ihn der Herr aus der Gewalt
all seiner Feinde und aus der Hand Sauls errettet hatte. [fn:1]\\
\\

<<v2>>
2 Er sprach:] Ich will dich rühmen, Herr, meine Stärke, / [fn:2]\\
\\

<<v3>>
3 Herr, du mein Fels, meine Burg, mein Retter, mein Gott, meine Feste,
in der ich mich berge, /\\
 mein Schild und sicheres Heil, meine Zuflucht. [fn:3]\\
\\

<<v4>>
4 Ich rufe: Der Herr sei gepriesen!, /\\
 und ich werde vor meinen Feinden gerettet.\\
\\

<<v5>>
5 Mich umfingen die Fesseln des Todes, /\\
 mich erschreckten die Fluten des Verderbens. [fn:4]\\
\\

<<v6>>
6 Die Bande der Unterwelt umstrickten mich, /\\
 über mich fielen die Schlingen des Todes.\\
\\

<<v7>>
7 In meiner Not rief ich zum Herrn /\\
 und schrie zu meinem Gott. Aus seinem Heiligtum hörte er mein Rufen,
/\\
 mein Hilfeschrei drang an sein Ohr.\\
\\

<<v8>>
8 Da wankte und schwankte die Erde, /\\
 die Grundfesten der Berge erbebten. /\\
 Sie wankten, denn sein Zorn war entbrannt. [fn:5]\\
\\

<<v9>>
9 Rauch stieg aus seiner Nase auf, /\\
 aus seinem Mund kam verzehrendes Feuer, /\\
 glühende Kohlen sprühten aus von ihm. [fn:6]\\
\\

<<v10>>
10 Er neigte den Himmel und fuhr herab, /\\
 zu seinen Füßen dunkle Wolken. [fn:7]\\
\\

<<v11>>
11 Er fuhr auf dem Kerub und flog daher; /\\
 er schwebte auf den Flügeln des Windes. [fn:8]\\
\\

<<v12>>
12 Er hüllte sich in Finsternis, /\\
 in dunkles Wasser und dichtes Gewölk wie in ein Zelt.\\
\\

<<v13>>
13 Von seinem Glanz erstrahlten die Wolken, /\\
 Hagel fiel nieder und glühende Kohlen. [fn:9]\\
\\

<<v14>>
14 Da ließ der Herr den Donner im Himmel erdröhnen, /\\
 der Höchste ließ seine Stimme erschallen. [fn:10] [fn:11]\\
\\

<<v15>>
15 Er schoss seine Pfeile und streute sie, /\\
 er schleuderte Blitze und jagte sie dahin. [fn:12]\\
\\

<<v16>>
16 Da wurden sichtbar die Tiefen des Meeres, /\\
 die Grundfesten der Erde wurden entblößt vor deinem Drohen, Herr, /\\
 vor dem Schnauben deines zornigen Atems. [fn:13] [fn:14]\\
\\

<<v17>>
17 Er griff aus der Höhe herab und fasste mich, /\\
 zog mich heraus aus gewaltigen Wassern. [fn:15]\\
\\

<<v18>>
18 Er entriss mich meinen mächtigen Feinden, /\\
 die stärker waren als ich und mich hassten.\\
\\

<<v19>>
19 Sie überfielen mich am Tag meines Unheils, /\\
 doch der Herr wurde mein Halt.\\
\\

<<v20>>
20 Er führte mich hinaus ins Weite, /\\
 er befreite mich, denn er hatte an mir Gefallen. [fn:16]\\
\\

<<v21>>
21 Der Herr hat gut an mir gehandelt und mir vergolten, /\\
 weil ich gerecht bin und meine Hände rein sind.\\
\\

<<v22>>
22 Denn ich hielt mich an die Wege des Herrn /\\
 und fiel nicht ruchlos ab von meinem Gott.\\
\\

<<v23>>
23 Ja, ich habe alle seine Gebote vor Augen, /\\
 weise seine Gesetze niemals ab.\\
\\

<<v24>>
24 Ich war vor ihm ohne Makel, /\\
 ich nahm mich in Acht vor der Sünde.\\
\\

<<v25>>
25 Darum hat der Herr mir vergolten, weil ich gerecht bin /\\
 und meine Hände rein sind vor seinen Augen.\\
\\

<<v26>>
26 Gegen den Treuen zeigst du dich treu, /\\
 an dem Aufrichtigen handelst du recht.\\
\\

<<v27>>
27 Gegen den Reinen zeigst du dich rein, /\\
 doch falsch gegen den Falschen.\\
\\

<<v28>>
28 Dem bedrückten Volk bringst du Heil, /\\
 doch die Blicke der Stolzen zwingst du nieder. [fn:17]\\
\\

<<v29>>
29 Du, Herr, lässt meine Leuchte erstrahlen, /\\
 mein Gott macht meine Finsternis hell. [fn:18]\\
\\

<<v30>>
30 Mit dir erstürme ich Wälle, /\\
 mit meinem Gott überspringe ich Mauern. [fn:19]\\
\\

<<v31>>
31 Vollkommen ist Gottes Weg, /\\
 das Wort des Herrn ist im Feuer geläutert. /\\
 Ein Schild ist er für alle, die sich bei ihm bergen. [fn:20]\\
\\

<<v32>>
32 Denn wer ist Gott als allein der Herr, /\\
 wer ist ein Fels, wenn nicht unser Gott? [fn:21]\\
\\

<<v33>>
33 Gott hat mich mit Kraft umgürtet, /\\
 er führte mich auf einen Weg ohne Hindernis.\\
\\

<<v34>>
34 Er ließ mich springen schnell wie Hirsche, /\\
 auf hohem Weg ließ er mich gehen. [fn:22] [fn:23]\\
\\

<<v35>>
35 Er lehrte meine Hände zu kämpfen, /\\
 meine Arme, den ehernen Bogen zu spannen. [fn:24]\\
\\

<<v36>>
36 Du gabst mir deine Hilfe zum Schild, /\\
 deine Rechte stützt mich; /\\
 du neigst dich mir zu und machst mich groß. [fn:25]\\
\\

<<v37>>
37 Du schaffst meinen Schritten weiten Raum, /\\
 meine Knöchel wanken nicht. [fn:26]\\
\\

<<v38>>
38 Ich verfolge meine Feinde und hole sie ein, /\\
 ich kehre nicht um, bis sie vernichtet sind.\\
\\

<<v39>>
39 Ich schlage sie nieder; /\\
 sie können sich nicht mehr erheben, sie fallen und liegen unter meinen
Füßen.\\
\\

<<v40>>
40 Du hast mich zum Kampf mit Kraft umgürtet, /\\
 hast alle in die Knie gezwungen, die sich gegen mich erhoben. [fn:27]\\
\\

<<v41>>
41 Meine Feinde hast du zur Flucht gezwungen; /\\
 ich konnte die vernichten, die mich hassen. [fn:28]\\
\\

<<v42>>
42 Sie schreien, doch hilft ihnen niemand, /\\
 sie schreien zum Herrn, doch er gibt keine Antwort.\\
\\

<<v43>>
43 Ich zermalme sie zu Staub vor dem Wind, /\\
 schütte sie auf die Straße wie Unrat.\\
\\

<<v44>>
44 Du rettest mich vor zahllosem Kriegsvolk, /\\
 du machst mich zum Haupt über ganze Völker. Stämme, die ich früher
nicht kannte, sind mir nun untertan. / [fn:29] [fn:30]\\
\\

<<v45>>
45 Sobald sie mich nur hören, gehorchen sie. Mir huldigen die Söhne der
Fremde, /\\
\\

<<v46>>
46 sie kommen zitternd aus ihren Burgen hervor. [fn:31] [fn:32]\\
\\

<<v47>>
47 Es lebt der Herr! Mein Fels sei gepriesen. /\\
 Der Gott meines Heils sei hoch erhoben; [fn:33]\\
\\

<<v48>>
48 denn Gott verschaffte mir Vergeltung /\\
 und unterwarf mir die Völker. [fn:34]\\
\\

<<v49>>
49 Du hast mich von meinen Feinden befreit, /\\
 mich über meine Gegner erhoben, /\\
 dem Mann der Gewalt mich entrissen.\\
\\

<<v50>>
50 Darum will ich dir danken, Herr, vor den Völkern, /\\
 ich will deinem Namen singen und spielen. [fn:35]\\
\\

<<v51>>
51 Seinem König verlieh er große Hilfe, /\\
 Huld erwies er seinem Gesalbten, /\\
 David und seinem Stamm auf ewig. [fn:36]\\
\\

* Footnotes

[fn:1] (1-51) [[file:2.Sam_22.org::v1][2 Sam 22,1-51]]

[fn:2] Text korr.; H: Ich will dich lieben.

[fn:3] [[file:Ps_92.org::v16][92,16]]; [[file:Ps_27.org::v5][27,5]]; [[file:Ps_31.org::v3][31,3]]; [[file:Ps_3.org::v4][3,4]]

[fn:4] [[file:Ps_42.org::v8][42,8]]; (5-7) [[file:Ps_116.org::v3][116,3f]]

[fn:5] [[file:Ps_68.org::v9][68,9]]

[fn:6] [[file:Ps_97.org::v3][97,3]]; [[file:Ex_19.org::v18][Ex 19,18]]

[fn:7] (10-17) [[file:Ps_144.org::v5][144,5-7]]

[fn:8] [[file:Ps_99.org::v1][99,1]]; [[file:Ps_104.org::v3][104,3]]

[fn:9] die Wolken: Text korr. nach G und [[file:2.Sam_22.org::v14][2 Sam 22,14]].

[fn:10] (14-15) [[file:Ps_77.org::v18][77,18f]]

[fn:11] Text korr. nach G und [[file:2.Sam_22.org::v14][2 Sam 22,14]]; H fügt am Schluss
hinzu: Hagel und glühende Kohlen.

[fn:12] Text korr. nach [[file:2.Sam_22.org::v15][2 Sam 22,15]].

[fn:13] [[file:Ps_77.org::v17][77,17]]; [[file:Ex_15.org::v8][Ex 15,8]]

[fn:14] Text korr.; H: des Wassers des Meeres.

[fn:15] [[file:Ps_32.org::v6][32,6]]; [[file:Ps_144.org::v7][144,7]]

[fn:16] [[file:Ps_31.org::v9][31,9]]

[fn:17] [[file:Ijob_22.org::v29][Ijob 22,29]]

[fn:18] [[file:Ijob_29.org::v3][Ijob 29,3]]

[fn:19] Text korr.; H ist unklar.

[fn:20] [[file:Ps_25.org::v4][25,4]]; [[file:Ps_12.org::v7][12,7]]; [[file:Ps_3.org::v4][3,4]]; [[file:Spr_30.org::v5][Spr 30,5]]

[fn:21] [[file:Jes_44.org::v8][Jes 44,8]]; [[file:Ps_92.org::v16][Ps 92,16]]

[fn:22] [[file:Hab_3.org::v19][Hab 3,19]]; [[file:Jes_58.org::v14][Jes 58,14]]

[fn:23] Wörtlich: auf meinen Höhen.

[fn:24] [[file:Ps_144.org::v1][144,1]]

[fn:25] Text korr.; in H andere Vokalisierung.

[fn:26] [[file:Ijob_18.org::v7][Ijob 18,7]]

[fn:27] alle: ergänzt nach G.

[fn:28] [[file:Ps_21.org::v13][21,13]]

[fn:29] [[file:Ps_2.org::v8][2,8]]

[fn:30] Text leicht korr.

[fn:31] [[file:Mi_7.org::v17][Mi 7,17]]

[fn:32] Text korr.; in H geht eine zusätzliche Verszeile (46a)
voraus: Die Söhne der Fremde verschmachten und kommen.

[fn:33] [[file:Ps_92.org::v16][92,16]]

[fn:34] [[file:Ps_144.org::v2][144,2]]

[fn:35] [[file:Ps_108.org::v4][108,4]]; [[file:Ps_7.org::v18][7,18]]; [[file:~/RoamNotes/notes/Bibel/nt/Röm_15.org::V9][Röm 15,9]]

[fn:36] [[file:Ps_20.org::v7][20,7]]; [[file:Ps_89.org::v29][89,29f]]; [[file:Ps_144.org::v10][144,10]]
