#+TITLE: Ps 104 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-10 Sa 22:07]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Ps 104.html

* Ps 104

<<verses>>

<<v1>>
* Ein Loblied auf den Schöpfer

1 Lobe den Herrn, meine Seele! /\\
 Herr, mein Gott, wie groß bist du! /\\
 Du bist mit Hoheit und Pracht bekleidet. [fn:1]\\
\\

<<v2>>
2 Du hüllst dich in Licht wie in ein Kleid, /\\
 du spannst den Himmel aus wie ein Zelt. [fn:2]\\
\\

<<v3>>
3 Du verankerst die Balken deiner Wohnung im Wasser. /\\
 Du nimmst dir die Wolken zum Wagen, /\\
 du fährst einher auf den Flügeln des Sturmes. [fn:3]\\
\\

<<v4>>
4 Du machst dir die Winde zu Boten /\\
 und lodernde Feuer zu deinen Dienern. [fn:4]\\
\\

<<v5>>
5 Du hast die Erde auf Pfeiler gegründet; /\\
 in alle Ewigkeit wird sie nicht wanken. [fn:5]\\
\\

<<v6>>
6 Einst hat die Urflut sie bedeckt wie ein Kleid, /\\
 die Wasser standen über den Bergen.\\
\\

<<v7>>
7 Sie wichen vor deinem Drohen zurück, /\\
 sie flohen vor der Stimme deines Donners. [fn:6]\\
\\

<<v8>>
8 Da erhoben sich Berge und senkten sich Täler /\\
 an den Ort, den du für sie bestimmt hast.\\
\\

<<v9>>
9 Du hast den Wassern eine Grenze gesetzt, /\\
 die dürfen sie nicht überschreiten; /\\
 nie wieder sollen sie die Erde bedecken. [fn:7]\\
\\

<<v10>>
10 Du lässt die Quellen hervorsprudeln in den Tälern, /\\
 sie eilen zwischen den Bergen dahin. [fn:8]\\
\\

<<v11>>
11 Allen Tieren des Feldes spenden sie Trank, /\\
 die Wildesel stillen ihren Durst daraus.\\
\\

<<v12>>
12 An den Ufern wohnen die Vögel des Himmels, /\\
 aus den Zweigen erklingt ihr Gesang. [fn:9]\\
\\

<<v13>>
13 Du tränkst die Berge aus deinen Kammern, /\\
 aus deinen Wolken wird die Erde satt. [fn:10] [fn:11]\\
\\

<<v14>>
14 Du lässt Gras wachsen für das Vieh, /\\
 auch Pflanzen für den Menschen, die er anbaut, damit er Brot gewinnt
von der Erde / [fn:12]\\
\\

<<v15>>
15 und Wein, der das Herz des Menschen erfreut, damit sein Gesicht von
Öl erglänzt /\\
 und Brot das Menschenherz stärkt. [fn:13]\\
\\

<<v16>>
16 Die Bäume des Herrn trinken sich satt, /\\
 die Zedern des Libanon, die er gepflanzt hat.\\
\\

<<v17>>
17 In ihnen bauen die Vögel ihr Nest, /\\
 auf den Zypressen nistet der Storch.\\
\\

<<v18>>
18 Die hohen Berge gehören dem Steinbock, /\\
 dem Klippdachs bieten die Felsen Zuflucht.\\
\\

<<v19>>
19 Du hast den Mond gemacht als Maß für die Zeiten, /\\
 die Sonne weiß, wann sie untergeht. [fn:14]\\
\\

<<v20>>
20 Du sendest Finsternis und es wird Nacht, /\\
 dann regen sich alle Tiere des Waldes.\\
\\

<<v21>>
21 Die jungen Löwen brüllen nach Beute, /\\
 sie verlangen von Gott ihre Nahrung. [fn:15]\\
\\

<<v22>>
22 Strahlt die Sonne dann auf, so schleichen sie heim /\\
 und lagern sich in ihren Verstecken. [fn:16]\\
\\

<<v23>>
23 Nun geht der Mensch hinaus an sein Tagwerk, /\\
 an seine Arbeit bis zum Abend.\\
\\

<<v24>>
24 Herr, wie zahlreich sind deine Werke! /\\
 Mit Weisheit hast du sie alle gemacht, /\\
 die Erde ist voll von deinen Geschöpfen. [fn:17]\\
\\

<<v25>>
25 Da ist das Meer, so groß und weit, /\\
 darin ein Gewimmel ohne Zahl: kleine und große Tiere. [fn:18] [fn:19]\\
\\

<<v26>>
26 Dort ziehen die Schiffe dahin, /\\
 auch der Leviatan, den du geformt hast, um mit ihm zu spielen. [fn:20]\\
\\

<<v27>>
27 Sie alle warten auf dich, /\\
 dass du ihnen Speise gibst zur rechten Zeit. [fn:21]\\
\\

<<v28>>
28 Gibst du ihnen, dann sammeln sie ein; /\\
 öffnest du deine Hand, werden sie satt an Gutem.\\
\\

<<v29>>
29 Verbirgst du dein Gesicht, sind sie verstört; /\\
 nimmst du ihnen den Atem, so schwinden sie hin /\\
 und kehren zurück zum Staub der Erde. [fn:22]\\
\\

<<v30>>
30 Sendest du deinen Geist aus, so werden sie alle erschaffen /\\
 und du erneuerst das Antlitz der Erde. [fn:23]\\
\\

<<v31>>
31 Ewig währe die Herrlichkeit des Herrn; /\\
 der Herr freue sich seiner Werke.\\
\\

<<v32>>
32 Er blickt auf die Erde und sie erbebt; /\\
 er rührt die Berge an und sie rauchen. [fn:24]\\
\\

<<v33>>
33 Ich will dem Herrn singen, solange ich lebe, /\\
 will meinem Gott spielen, solange ich da bin. [fn:25]\\
\\

<<v34>>
34 Möge ihm mein Dichten gefallen. /\\
 Ich will mich freuen am Herrn. [fn:26]\\
\\

<<v35>>
35 Doch die Sünder sollen von der Erde verschwinden /\\
 und es sollen keine Frevler mehr da sein. /\\
 Lobe den Herrn, meine Seele! /\\
 Halleluja!\\
\\

* Footnotes

[fn:1] [[file:Ps_40.org::v17][40,17]]

[fn:2] [[file:Ijob_9.org::v8][Ijob 9,8]]; [[file:Jes_40.org::v22][Jes 40,22]]; [[file:Jes_44.org::v24][44,24]]

[fn:3] [[file:Ps_18.org::v11][18,11]]; [[file:Ps_68.org::v5][68,5]]

[fn:4] [[file:~/Documents/notes/Bibel/nt/Hebr_1.org::v7][Hebr 1,7]]

[fn:5] [[file:Ps_75.org::v4][75,4]]

[fn:6] (7-9) [[file:Spr_8.org::v29][Spr 8,29]]

[fn:7] [[file:Ijob_38.org::v8][Ijob 38,8-11]]; [[file:Jer_5.org::v22][Jer 5,22]]; [[file:Gen_9.org::v11][Gen 9,11-15]]

[fn:8] [[file:Ps_74.org::v15][74,15]]

[fn:9] [[file:Ez_31.org::v6][Ez 31,6-9]]

[fn:10] [[file:Ps_65.org::v10][65,10f]]; [[file:Ijob_36.org::v31][Ijob 36,31]]

[fn:11] Text korr.; H ist unverständlich.

[fn:12] [[file:Ps_147.org::v8][147,8f]]

[fn:13] [[file:Ri_9.org::v13][Ri 9,13]]; [[file:Koh_10.org::v19][Koh 10,19]]; [[file:Sir_31.org::v27][Sir 31,27]]

[fn:14] [[file:Ps_74.org::v16][74,16]]; [[file:Sir_43.org::v6][Sir 43,6-8]]

[fn:15] [[file:Ps_17.org::v12][17,12]]; [[file:Ijob_38.org::v39][Ijob 38,39]]

[fn:16] [[file:Ijob_37.org::v8][Ijob 37,8]]

[fn:17] [[file:Spr_8.org::v22][Spr 8,22-31]]

[fn:18] [[file:Sir_43.org::v25][Sir 43,25]]

[fn:19] so groß und weit, wörtlich: groß und weit nach beiden Seiten.

[fn:20] [[file:Ps_107.org::v23][107,23]]

[fn:21] [[file:Ps_136.org::v25][136,25]]; (27-28) [[file:Ps_145.org::v15][145,15f]]

[fn:22] [[file:Ps_30.org::v8][30,8]]; [[file:Ps_146.org::v4][146,4]]

[fn:23] [[file:Gen_2.org::v7][Gen 2,7]]

[fn:24] [[file:Ps_144.org::v5][144,5]]

[fn:25] [[file:Ps_7.org::v18][7,18]]; [[file:Ps_142.org::v2][146,2]]

[fn:26] [[file:Ps_19.org::v15][19,15]]
