#+TITLE: Ps 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-04 Mo 22:15]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ps 17.html

* Ps 17

<<verses>>

<<v1>>
* Das Gebet eines Verfolgten

1 [Ein Gebet Davids.] Höre, Herr, die gerechte Sache, /\\
 achte auf mein Flehen, /\\
 vernimm mein Gebet von Lippen ohne Falsch!\\
\\

<<v2>>
2 Von deinem Angesicht ergehe mein Urteil; /\\
 denn deine Augen sehen, was recht ist.\\
\\

<<v3>>
3 Prüfst du mein Herz, /\\
 suchst du mich heim in der Nacht und erprobst mich, /\\
 dann findest du an mir kein Unrecht. Mein Mund verging sich nicht, / [fn:1] [fn:2]\\
\\

<<v4>>
4 trotz allem, was die Menschen auch treiben; /\\
 ich halte mich an das Wort deiner Lippen. [fn:3]\\
\\

<<v5>>
5 Auf dem Weg deiner Gebote gehn meine Schritte, /\\
 meine Füße wanken nicht auf deinen Pfaden.\\
\\

<<v6>>
6 Ich rufe dich an, denn du, Gott, erhörst mich. /\\
 Wende dein Ohr mir zu, vernimm meine Rede!\\
\\

<<v7>>
7 Wunderbar erweise deine Huld! /\\
 Du rettest alle, die sich an deiner Rechten vor den Feinden bergen. [fn:4]\\
\\

<<v8>>
8 Behüte mich wie den Augapfel, den Stern des Auges, /\\
 birg mich im Schatten deiner Flügel [fn:5]\\
\\

<<v9>>
9 vor den Frevlern, die mich hart bedrängen, /\\
 vor den Feinden, die mich wütend umringen.\\
\\

<<v10>>
10 Sie haben ihr hartes Herz verschlossen, /\\
 sie führen stolze Worte im Mund, [fn:6]\\
\\

<<v11>>
11 sie lauern mir auf, jetzt kreisen sie mich ein; /\\
 sie trachten danach, mich zu Boden zu strecken, [fn:7]\\
\\

<<v12>>
12 so wie der Löwe voll Gier ist zu zerreißen, /\\
 wie der junge Löwe, der im Hinterhalt lauert. [fn:8]\\
\\

<<v13>>
13 Erheb dich, Herr, tritt dem Frevler entgegen! /\\
 Wirf ihn zu Boden, mit deinem Schwert entreiß mich ihm!\\
\\

<<v14>>
14 Rette mich, Herr, mit deiner Hand vor diesen Leuten, /\\
 vor denen, die im Leben schon alles haben. Du füllst ihren Leib mit
Gütern, /\\
 auch ihre Söhne werden noch satt /\\
 und hinterlassen den Enkeln, was übrig bleibt. [fn:9] [fn:10]\\
\\

<<v15>>
15 Ich aber will in Gerechtigkeit dein Angesicht schauen, /\\
 mich satt sehen an deiner Gestalt, wenn ich erwache. [fn:11]\\
\\

* Footnotes

[fn:1] [[file:Ps_139.org::v1][139,1]]; [[file:Ijob_7.org::v18][Ijob 7,18]]; [[file:Ps_23.org::v10][23,10]]

[fn:2] findest du: Text korr. nach G und S.

[fn:3] (4-5) [[file:Ijob_23.org::v11][Ijob 23,11f]]

[fn:4] (7-8) [[file:Ps_36.org::v8][36,8]]; [[file:Ps_57.org::v2][57,2]]; [[file:Ps_61.org::v5][61,5]]; [[file:Ps_63.org::v8][63,8]]; [[file:Ps_91.org::v4][91,4]]; [[file:Ex_37.org::v9][Ex 37,9]]; [[file:~/Documents/notes/Bibel/nt/Mt_23.org::v37][Mt 23,37]]

[fn:5] [[file:Dtn_32.org::v10][Dtn 32,10]]; [[file:Sach_2.org::v12][Sach 2,12]]

[fn:6] ihr hartes Herz, wörtlich: ihr Fett.

[fn:7] sie lauern mir auf: Text korr.; H: unsere Schritte.

[fn:8] [[file:Ps_7.org::v3][7,3]]; [[file:Ps_10.org::v9][10,9]]; [[file:Ps_22.org::v14][22,14]].[[file:Ps_22.org::v22][22]]; [[file:Ps_35.org::v17][35,17]]; [[file:Ps_57.org::v5][57,5]]; [[file:Ps_58.org::v7][58,7]]

[fn:9] [[file:Ps_73.org::v12][73,12]]

[fn:10] ist verderbt.

[fn:11] [[file:Num_12.org::v8][Num 12,8]]; [[file:~/Documents/notes/Bibel/nt/Offb_22.org::v4][Offb 22,4]]
