#+TITLE: Ps 102 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-08 Do 21:32]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Ps 102.html

* Ps 102

<<verses>>

<<v1>>
* Das Gebet eines Unglücklichen

1 [Gebet eines Unglücklichen, wenn er in Verzweiflung ist und vor dem
Herrn seine Sorge ausschüttet.]\\
\\

<<v2>>
2 Herr, höre mein Gebet! /\\
 Mein Schreien dringe zu dir.\\
\\

<<v3>>
3 Verbirg dein Antlitz nicht vor mir! /\\
 Wenn ich in Not bin, wende dein Ohr mir zu! /\\
 Wenn ich dich anrufe, erhöre mich bald! [fn:1]\\
\\

<<v4>>
4 Meine Tage sind wie Rauch geschwunden, /\\
 meine Glieder wie von Feuer verbrannt. [fn:2]\\
\\

<<v5>>
5 Versengt wie Gras und verdorrt ist mein Herz, /\\
 sodass ich vergessen habe, mein Brot zu essen.\\
\\

<<v6>>
6 Vor lauter Stöhnen und Schreien /\\
 bin ich nur noch Haut und Knochen. [fn:3] [fn:4]\\
\\

<<v7>>
7 Ich bin wie eine Dohle in der Wüste, /\\
 wie eine Eule in öden Ruinen.\\
\\

<<v8>>
8 Ich liege wach und ich klage /\\
 wie ein einsamer Vogel auf dem Dach. [fn:5]\\
\\

<<v9>>
9 Den ganzen Tag schmähen mich die Feinde; /\\
 die mich verhöhnen, nennen meinen Namen beim Fluchen. [fn:6]\\
\\

<<v10>>
10 Staub muss ich essen wie Brot, /\\
 mit Tränen mische ich meinen Trank; [fn:7]\\
\\

<<v11>>
11 denn auf mir lasten dein Zorn und dein Grimm. /\\
 Du hast mich hochgerissen und zu Boden geschleudert.\\
\\

<<v12>>
12 Meine Tage schwinden dahin wie Schatten, /\\
 ich verdorre wie Gras. [fn:8] [fn:9]\\
\\

<<v13>>
13 Du aber, Herr, du thronst für immer und ewig, /\\
 dein Name dauert von Geschlecht zu Geschlecht. [fn:10]\\
\\

<<v14>>
14 Du wirst dich erheben, dich über Zion erbarmen; /\\
 denn es ist Zeit, ihm gnädig zu sein, die Stunde ist da. [fn:11]\\
\\

<<v15>>
15 An Zions Steinen hängt das Herz deiner Knechte, /\\
 um seine Trümmer tragen sie Leid.\\
\\

<<v16>>
16 Dann fürchten die Völker den Namen des Herrn /\\
 und alle Könige der Erde deine Herrlichkeit.\\
\\

<<v17>>
17 Denn der Herr baut Zion wieder auf /\\
 und erscheint in all seiner Herrlichkeit. [fn:12]\\
\\

<<v18>>
18 Er wendet sich dem Gebet der Verlassenen zu, /\\
 ihre Bitten verschmäht er nicht.\\
\\

<<v19>>
19 Dies sei aufgeschrieben für das kommende Geschlecht, /\\
 damit das Volk, das noch erschaffen wird, den Herrn lobpreise. [fn:13]\\
\\

<<v20>>
20 Denn der Herr schaut herab aus heiliger Höhe, /\\
 vom Himmel blickt er auf die Erde nieder; [fn:14]\\
\\

<<v21>>
21 er will auf das Seufzen der Gefangenen hören /\\
 und alle befreien, die dem Tod geweiht sind, [fn:15]\\
\\

<<v22>>
22 damit sie den Namen des Herrn auf dem Zion verkünden /\\
 und sein Lob in Jerusalem,\\
\\

<<v23>>
23 wenn sich dort Königreiche und Völker versammeln, /\\
 um den Herrn zu verehren. [fn:16]\\
\\

<<v24>>
24 Er hat meine Kraft auf dem Weg gebrochen, /\\
 er hat meine Tage verkürzt. [fn:17]\\
\\

<<v25>>
25 Darum sage ich: Raff mich nicht weg in der Mitte des Lebens, /\\
 mein Gott, dessen Jahre Geschlecht um Geschlecht überdauern! [fn:18]\\
\\

<<v26>>
26 Vorzeiten hast du der Erde Grund gelegt, /\\
 die Himmel sind das Werk deiner Hände. [fn:19]\\
\\

<<v27>>
27 Sie werden vergehen, du aber bleibst; /\\
 sie alle zerfallen wie ein Gewand; du wechselst sie wie ein Kleid /\\
 und sie schwinden dahin.\\
\\

<<v28>>
28 Du aber bleibst, der du bist, /\\
 und deine Jahre enden nie. [fn:20]\\
\\

<<v29>>
29 Die Kinder deiner Knechte werden (in Sicherheit) wohnen, /\\
 ihre Nachkommen vor deinem Antlitz bestehen. [fn:21]\\
\\

* Footnotes

[fn:1] [[file:Ps_31.org::v3][31,3]]; [[file:Ps_69.org::v18][69,18]]; [[file:Ps_143.org::v7][143,7]]

[fn:2] [[file:Ps_38.org::v8][38,8f]]

[fn:3] [[file:Ijob_19.org::v20][Ijob 19,20]]

[fn:4] Wörtlich: Vor lauter Jammern klebt mein Gebein am
Fleisch.

[fn:5] und ich klage wie: Text korr.; H: und ich bin wie ...

[fn:6] [[file:Ps_41.org::v6][41,6]]

[fn:7] [[file:Ps_42.org::v4][42,4]]

[fn:8] [[file:Ps_90.org::v9][90,9f]]

[fn:9] Text korr.; H: Meine Tage (sind) wie ein lang sich
dehnender Schatten (d. h.: es geht dem Ende entgegen)

[fn:10] [[file:Ps_145.org::v13][145,13]]; [[file:Ps_135.org::v13][135,13]]; [[file:Klgl_5.org::v19][Klgl 5,19]]

[fn:11] [[file:Ps_69.org::v14][69,14]]

[fn:12] [[file:Ps_51.org::v20][51,20]]; [[file:Jes_60.org::v1][Jes 60,1]]

[fn:13] [[file:Ps_22.org::v31][22,31f]]

[fn:14] [[file:Ps_11.org::v4][11,4]]; [[file:Ps_33.org::v13][33,13]]

[fn:15] [[file:Ps_79.org::v11][79,11]]

[fn:16] [[file:Jes_60.org::v3][Jes 60,3-10]]; [[file:~/Documents/notes/Bibel/nt/Lk_13.org::v29][Lk 13,29f]]

[fn:17] [[file:Ps_89.org::v46][89,46]]

[fn:18] [[file:Ps_55.org::v24][55,24]]

[fn:19] (26-28) [[file:Jes_51.org::v6][Jes 51,6-8]]; [[file:~/Documents/notes/Bibel/nt/Hebr_1.org::v10][Hebr 1,10-12]]

[fn:20] [[file:~/Documents/notes/Bibel/nt/Hebr_13.org::v8][Hebr 13,8]]

[fn:21] [[file:Ps_69.org::v36][69,36f]]
