#+TITLE: Ps 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-03 So 13:35]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ps 1.html

* Ps 1

Ähnlich wie die Bücher des Mose ist diese Sammlung von 150
Einzelliedern, die eines der bedeutendsten Bücher der Heiligen Schrift
und auch der gesamten Weltliteratur darstellen, in fünf Bücher
eingeteilt: Ps 1 - 41; 42 - 72; 73 - 89; 90 - 106; 107 - 150. Die
griechische und die lateinische Bibel haben eine leicht abweichende
Zählweise der Psalmen (vgl. Anhang dieser Bibelausgabe). Die heutige
Reihenfolge und Anordnung der Psalmen in der hebräischen Bibel, die eine
gewisse Korrespondenz zu den Büchern des Mose aufweist, ist
höchstwahrscheinlich von ihrem Gebrauch im Synagogengottesdienst her zu
verstehen. Thematisch berühren die Psalmen fast alle Fragen und Probleme
der alttestamentlichen Theologie. Die neuere Forschung befasst sich
besonders mit den verschiedenen Psalmengattungen und ihrem »Sitz im
Leben« sowie mit der Überlieferung der einzelnen Psalmen bis zu ihrer
jetzigen Gestalt. Man unterscheidet heute vor allem folgende Gattungen:
Hymnen, Danklieder, Klagelieder eines Einzelnen und des Volkes,
Bittpsalmen, Wallfahrtslieder, Königslieder, Weisheitslieder,
»messianische Psalmen«.\\
\\
Dass der Psalter eine Sonderstellung unter den Schriften des Alten
Testaments einnimmt, wird kaum bezweifelt. Denn die Psalmen lassen einen
einzigartigen Einblick in die innere Struktur der Offenbarung tun. Der
Psalter gibt nämlich davon Kunde, dass die Offenbarung sich nicht nur
als monologes Sprechen und Handeln Gottes ereignet, sondern dass Gott
sich im auserwählten Volk einen Partner bereitet hat, der mit in das
Offenbarungsgeschehen einbezogen wird. Die Offenbarung ist demnach ein
dialogischer Vorgang: Gott handelt und spricht nicht nur auf das Volk
hin, sondern Israel spricht und handelt mit (vgl. Ex 19,8, wo das Volk
sich einmütig bereit erklärt, Gottes Auserwählung anzunehmen). Von der
Aufnahme des Dialogs durch das auserwählte Volk künden wie kein anderes
biblisches Buch die Psalmen: Sie sind die in der Offenbarung und aus ihr
erfolgte Antwort auf Gottes offenbartes Wort. Das sollen einige
Entsprechungen der Psalmen zu wichtigen alttestamentlichen Texten
zeigen: Schöpfungstat und -werk Gottes: Gen 1 - Ps 104. Der Mensch: Gen
1,26-28 - Ps 8. Gottes Heiligkeit: Jes 6 - Ps 99. Das Meerwunder: Ex
13 - 15 - Ps 66. Lobpreis des Bundesgottes: Ex 19 - 24 - Ps 97. Von
Ägypten ins Gelobte Land: Ps 114. Von der Patriarchenzeit bis zur
Landverleihung: Ps 105. Gottes Heilswerk an Zion: 2 Sam 6 - Ps 48. Der
Neue Bund: Jer 31,31-34; Ez 36,24-28 - Ps 51,12-14. Der Messias als
König: Jes 9,1-6; 11,1-5; Mi 5,1-3 - Ps 2; 72; 110. Der Messias als
Leidensmann: Jes 53 - Ps 22.\\
\\
Natürlich decken sich die Inhalte der angeführten einander
entsprechenden Texte nicht vollauf; aber Hauptmotive werden vom
lobpreisenden Gottesvolk aufgegriffen, neu interpretiert, um andere
Offenbarungsgehalte vermehrt und weiter entfaltet.\\
\\
Noch etwas anderes geht aus den Psalmen hervor, nämlich dass Israels
wichtigste und vornehmste Aufgabe, ja der Grund seiner Sonderexistenz im
Gotteslob, im Gott gemäßen Kult besteht. Vom Kult her dürfte auch Licht
auf die heutige Anordnung der Psalmen fallen. In Neh 8,1-6 ist ein
Muster für den Synagogengottesdienst enthalten, der im Exil oder in der
nachexilischen Zeit neben dem Tempelgottesdienst aufkommt. Weil der
Opferdienst auf den Tempel beschränkt bleibt, handelt es sich im
Synagogengottesdienst um den Typus eines reinen Lesegottesdienstes, der
in etwa unserem Wortgottesdienst vergleichbar ist. Er enthält als
wesentliche Bestandteile:\\
\\
1. Nach Einleitungsgebeten folgt die Lesung des fälligen Abschnitts aus
dem Pentateuch. Die fünf Bücher des Mose sind in einer einjährigen oder
dreijährigen Leseordnung auf die Sabbate des Jahres verteilt (für die
Feste sind besondere Texte ausgesucht).\\
\\
2. Dann antwortet das Volk mit dem zugeordneten, vielleicht gesungenen
Psalm.\\
\\
3. An den Psalm schließt eine zweite Lesung aus den Propheten und eine
Homilie an.\\
\\
4. Segensgebete beschließen den Gottesdienst.\\
\\
Mit ziemlicher Sicherheit lässt sich also sagen, dass zur Zeit der
Wiederherstellung der nachexilischen Gemeinde unter Esra und Nehemia der
Psalter seine heutige Gestalt erhalten hat. Für die einzelnen Psalmen
wird man insgesamt eine Entstehungszeit von mehreren Jahrhunderten, von
David bis Esra, anzunehmen haben. Weiter deutet ihre Verwendung im
Synagogengottesdienst auch eine vom Kult her bestimmte Anordnung und
Reihung verschiedener Texteinheiten im Pentateuch an und legt sie nahe.
So hat man also für das Verständnis der einzelnen Psalmen und des
gesamten Psalters viel mehr als bisher deren Verwendung im Gottesdienst
zu berücksichtigen.\\
\\
Der Psalter hat seinen hohen Rang als Gebetbuch des alten Bundesvolkes
auch für Christus und die junge Kirche behalten. Die Kirche hat mit den
Psalmen auf die in Christus erfüllte Offenbarung geantwortet. Bis heute
verwendet sie daher in der Nachfolge des Herrn den Psalter vor allen
anderen Gebetstexten für den Gottesdienst in seiner vielfältigen
Gestalt.\\
\\

<<verses>>

<<v1>>
* Das erste Buch

* Die beiden Wege

1 Wohl dem Mann, der nicht dem Rat der Frevler folgt, /\\
 nicht auf dem Weg der Sünder geht, /\\
 nicht im Kreis der Spötter sitzt, [fn:1]\\
\\

<<v2>>
2 sondern Freude hat an der Weisung des Herrn, /\\
 über seine Weisung nachsinnt bei Tag und bei Nacht. [fn:2]\\
\\

<<v3>>
3 Er ist wie ein Baum, /\\
 der an Wasserbächen gepflanzt ist, der zur rechten Zeit seine Frucht
bringt /\\
 und dessen Blätter nicht welken. Alles, was er tut, /\\
 wird ihm gut gelingen. [fn:3]\\
\\

<<v4>>
4 Nicht so die Frevler: /\\
 Sie sind wie Spreu, die der Wind verweht. [fn:4]\\
\\

<<v5>>
5 Darum werden die Frevler im Gericht nicht bestehen /\\
 noch die Sünder in der Gemeinde der Gerechten.\\
\\

<<v6>>
6 Denn der Herr kennt den Weg der Gerechten, /\\
 der Weg der Frevler aber führt in den Abgrund. [fn:5]\\
\\

* Footnotes

[fn:1] [[file:Ps_26.org::v4][26,4f]]; [[file:Spr_4.org::v14][Spr 4,14]]

[fn:2] [[file:Ps_112.org::v1][112,1]]; [[file:Jos_1.org::v8][Jos 1,8]]

[fn:3] [[file:Ps_92.org::v13][92,13]]; [[file:Jer_17.org::v8][Jer 17,8]]

[fn:4] [[file:Ps_35.org::v5][35,5]]; [[file:Ijob_21.org::v18][Ijob 21,18]]

[fn:5] [[file:Ps_119.org::v1][119,1]]; [[file:Spr_10.org::v28][Spr 10,28]]
