#+TITLE: Ps 14 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-04 Mo 22:04]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ps 14.html

* Ps 14

<<verses>>

<<v1>>
* Die Torheit der Gottesleugner

1 [Für den Chormeister. Von David.] Die Toren sagen in ihrem Herzen: /\\
 «Es gibt keinen Gott.» Sie handeln verwerflich und schnöde; /\\
 da ist keiner, der Gutes tut. [fn:1]\\
\\

<<v2>>
2 Der Herr blickt vom Himmel herab auf die Menschen, /\\
 ob noch ein Verständiger da ist, der Gott sucht. [fn:2]\\
\\

<<v3>>
3 Alle sind sie abtrünnig und verdorben, /\\
 keiner tut Gutes, auch nicht ein Einziger. [fn:3]\\
\\

<<v4>>
4 Haben denn all die Übeltäter keine Einsicht? /\\
 Sie verschlingen mein Volk. Sie essen das Brot des Herrn, /\\
 doch seinen Namen rufen sie nicht an. [fn:4]\\
\\

<<v5>>
5 Es trifft sie Furcht und Schrecken; /\\
 denn Gott steht auf der Seite der Gerechten.\\
\\

<<v6>>
6 Die Pläne der Armen wollt ihr vereiteln, /\\
 doch ihre Zuflucht ist der Herr.\\
\\

<<v7>>
7 Ach, käme doch vom Zion Hilfe für Israel! /\\
 Wenn einst der Herr das Geschick seines Volkes wendet, /\\
 dann jubelt Jakob, dann freut sich Israel. [fn:5]\\
\\

* Footnotes

[fn:1] [[file:Ps_10.org::v4][10,4]]; [[file:Jes_32.org::v6][Jes 32,6]]; [[file:Mi_7.org::v2][Mi 7,2]]; (1-3) [[file:~/RoamNotes/notes/Bibel/nt/Röm_3.org::v10][Röm 3,10-12]]; (1-7) [[file:Ps_53.org::v1][Ps 53,1-7]]

[fn:2] [[file:Ps_33.org::v13][33,13-15]]

[fn:3] [[file:Ps_12.org::v2][12,2]]; [[file:Gen_6.org::v12][Gen 6,12]]

[fn:4] [[file:Mi_3.org::v3][Mi 3,3]]

[fn:5] [[file:Ps_126.org::v1][126,1f]]; [[file:Jes_35.org::v10][Jes 35,10]]
