#+TITLE: Ps 132 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-19 Mo 14:59]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Ps 132.html

* Ps 132

<<verses>>

<<v1>>
* Die Erwählung Davids und des Zion

1 [Ein Wallfahrtslied.] O Herr, denk an David, /\\
 denk an all seine Mühen,\\
\\

<<v2>>
2 wie er dem Herrn geschworen, /\\
 dem starken Gott Jakobs gelobt hat:\\
\\

<<v3>>
3 «Nicht will ich mein Zelt betreten /\\
 noch mich zur Ruhe betten, [fn:1]\\
\\

<<v4>>
4 nicht Schlaf den Augen gönnen /\\
 noch Schlummer den Lidern,\\
\\

<<v5>>
5 bis ich eine Stätte finde für den Herrn, /\\
 eine Wohnung für den starken Gott Jakobs.»\\
\\

<<v6>>
6 Wir hörten von seiner Lade in Efrata, /\\
 fanden sie im Gefilde von Jáar. [fn:2] [fn:3]\\
\\

<<v7>>
7 Lasst uns hingehen zu seiner Wohnung /\\
 und niederfallen vor dem Schemel seiner Füße! [fn:4]\\
\\

<<v8>>
8 Erheb dich, Herr, komm an den Ort deiner Ruhe, /\\
 du und deine machtvolle Lade! [fn:5]\\
\\

<<v9>>
9 Deine Priester sollen sich bekleiden mit Gerechtigkeit /\\
 und deine Frommen sollen jubeln. [fn:6]\\
\\

<<v10>>
10 Weil David dein Knecht ist, /\\
 weise deinen Gesalbten nicht ab!\\
\\

<<v11>>
11 Der Herr hat David geschworen, /\\
 einen Eid, den er niemals brechen wird: «Einen Spross aus deinem
Geschlecht /\\
 will ich setzen auf deinen Thron. [fn:7] [fn:8]\\
\\

<<v12>>
12 Wenn deine Söhne meinen Bund bewahren, /\\
 mein Zeugnis, das ich sie lehre, dann sollen auch ihre Söhne /\\
 auf deinem Thron sitzen für immer.»\\
\\

<<v13>>
13 Denn der Herr hat den Zion erwählt, /\\
 ihn zu seinem Wohnsitz erkoren: [fn:9]\\
\\

<<v14>>
14 «Das ist für immer der Ort meiner Ruhe; /\\
 hier will ich wohnen, ich hab ihn erkoren. [fn:10]\\
\\

<<v15>>
15 Zions Nahrung will ich reichlich segnen, /\\
 mit Brot seine Armen sättigen. [fn:11]\\
\\

<<v16>>
16 Seine Priester will ich bekleiden mit Heil, /\\
 seine Frommen sollen jauchzen und jubeln. [fn:12]\\
\\

<<v17>>
17 Dort lasse ich Davids Macht erstarken /\\
 und stelle für meinen Gesalbten ein Licht auf. [fn:13]\\
\\

<<v18>>
18 Ich bedecke seine Feinde mit Schande; /\\
 doch auf ihm erglänzt seine Krone.»\\
\\

* Footnotes

[fn:1] (3-5) [[file:2.Sam_7.org::v1][2 Sam 7,1f]]; [[file:1.Chr_28.org::v2][1 Chr 28,2]]

[fn:2] [[file:1.Sam_7.org::v1][1 Sam 7,1]]; [[file:2.Sam_6.org::v2][2 Sam 6,2]]

[fn:3] von seiner Lade, wörtlich: von ihr.

[fn:4] [[file:Ps_99.org::v5][99,5]]

[fn:5] [[file:Num_10.org::v35][Num 10]],35f; (8-10) [[file:2.Chr_6.org::v41][2 Chr 6,41f]]

[fn:6] [[file:Ijob_29.org::v14][Ijob 29,14]]

[fn:7] [[file:Ps_89.org::v4][89,4f]]

[fn:8] Wörtlich: (Einen) von deiner Leibesfrucht.

[fn:9] [[file:Ps_68.org::v17][68,17]]; [[file:Ps_76.org::v3][76,3]]; [[file:Ps_78.org::v68][78,68]]

[fn:10] [[file:1.Kön_8.org::v13][1 Kön 8,13]]

[fn:11] Zions Nahrung, wörtlich: Seine Nahrung.

[fn:12] [[v9][132,9]]; [[file:Jes_61.org::v10][Jes 61,10]]

[fn:13] [[file:1.Kön_11.org::v36][1 Kön 11,36]]; [[file:~/RoamNotes/notes/Bibel/nt/Lk_1.org::v69][Lk 1,69]]
