#+TITLE: Ps 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-03 So 13:42]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ps 2.html

* Ps 2

<<verses>>

<<v1>>
* Der Herr und sein Gesalbter

1 Warum toben die Völker, /\\
 warum machen die Nationen vergebliche Pläne? [fn:1]\\
\\

<<v2>>
2 Die Könige der Erde stehen auf, /\\
 die Großen haben sich verbündet gegen den Herrn und seinen Gesalbten. [fn:2]\\
\\

<<v3>>
3 «Lasst uns ihre Fesseln zerreißen /\\
 und von uns werfen ihre Stricke!»\\
\\

<<v4>>
4 Doch er, der im Himmel thront, lacht, /\\
 der Herr verspottet sie. [fn:3]\\
\\

<<v5>>
5 Dann aber spricht er zu ihnen im Zorn, /\\
 in seinem Grimm wird er sie erschrecken:\\
\\

<<v6>>
6 «Ich selber habe meinen König eingesetzt /\\
 auf Zion, meinem heiligen Berg.»\\
\\

<<v7>>
7 Den Beschluss des Herrn will ich kundtun. /\\
 Er sprach zu mir: «Mein Sohn bist du. /\\
 Heute habe ich dich gezeugt. [fn:4]\\
\\

<<v8>>
8 Fordre von mir und ich gebe dir die Völker zum Erbe, /\\
 die Enden der Erde zum Eigentum. [fn:5] [fn:6]\\
\\

<<v9>>
9 Du wirst sie zerschlagen mit eiserner Keule, /\\
 wie Krüge aus Ton wirst du sie zertrümmern.» [fn:7]\\
\\

<<v10>>
10 Nun denn, ihr Könige, kommt zur Einsicht, /\\
 lasst euch warnen, ihr Gebieter der Erde!\\
\\

<<v11>>
11 Dient dem Herrn in Furcht /\\
 und küsst ihm mit Beben die Füße, [fn:8]\\
\\

<<v12>>
12 damit er nicht zürnt /\\
 und euer Weg nicht in den Abgrund führt. Denn wenig nur und sein Zorn
ist entbrannt. /\\
 Wohl allen, die ihm vertrauen!\\
\\

* Footnotes

[fn:1] [[file:~/Documents/notes/Bibel/nt/Offb_11.org::v18][Offb 11,18]]; [[file:~/Documents/notes/Bibel/nt/Apg_4.org::v25][Apg 4,25f]]

[fn:2] [[file:~/Documents/notes/Bibel/nt/Offb_19.org::v19][Offb 19,19]]

[fn:3] [[file:Ps_59.org::v9][59,9]]

[fn:4] [[file:Ps_89.org::v27][89,27f]]; [[file:~/Documents/notes/Bibel/nt/Apg_13.org::v33][Apg 13,33]]; [[file:~/Documents/notes/Bibel/nt/Hebr_1.org::v5][Hebr 1,5]]; [[file:~/Documents/notes/Bibel/nt/Hebr_5.org::v5][5,5]]

[fn:5] (8-9) [[file:Ps_72.org::v8][72,8]]; [[file:~/Documents/notes/Bibel/nt/Offb_2.org::v26][Offb 2,26f]]

[fn:6] dir: ergänzt nach G und S.

[fn:7] [[file:Ps_110.org::v5][110,5f]]; [[file:~/Documents/notes/Bibel/nt/Offb_12.org::v5][Offb 12,5]]; [[file:~/Documents/notes/Bibel/nt/Offb_19.org::v15][19,15]]

[fn:8] Text korr.; H ist kaum verständlich: und jauchzt mit
Beben, küsst den Sohn (in H zum Teil bereits V. 12).
