#+TITLE: Ps 34 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-22 Fr 09:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ps 34.html

* Ps 34

<<verses>>

<<v1>>
* Unter Gottes Schutz

1 [Von David, als er sich vor Abimelech wahnsinnig stellte und dieser
ihn fortjagte und er ging.] [fn:1]\\
\\

<<v2>>
2 Ich will den Herrn allezeit preisen; /\\
 immer sei sein Lob in meinem Mund. [fn:2]\\
\\

<<v3>>
3 Meine Seele rühme sich des Herrn; /\\
 die Armen sollen es hören und sich freuen.\\
\\

<<v4>>
4 Verherrlicht mit mir den Herrn, /\\
 lasst uns gemeinsam seinen Namen rühmen.\\
\\

<<v5>>
5 Ich suchte den Herrn und er hat mich erhört, /\\
 er hat mich all meinen Ängsten entrissen.\\
\\

<<v6>>
6 Blickt auf zu ihm, so wird euer Gesicht leuchten /\\
 und ihr braucht nicht zu erröten. [fn:3]\\
\\

<<v7>>
7 Da ist ein Armer; er rief und der Herr erhörte ihn. /\\
 Er half ihm aus all seinen Nöten. [fn:4]\\
\\

<<v8>>
8 Der Engel des Herrn umschirmt alle, die ihn fürchten und ehren, /\\
 und er befreit sie. [fn:5]\\
\\

<<v9>>
9 Kostet und seht, wie gütig der Herr ist; /\\
 wohl dem, der zu ihm sich flüchtet! [fn:6]\\
\\

<<v10>>
10 Fürchtet den Herrn, ihr seine Heiligen; /\\
 denn wer ihn fürchtet, leidet keinen Mangel.\\
\\

<<v11>>
11 Reiche müssen darben und hungern; /\\
 wer aber den Herrn sucht, braucht kein Gut zu entbehren. [fn:7] [fn:8]\\
\\

<<v12>>
12 Kommt, ihr Kinder, hört mir zu! /\\
 Ich will euch in der Furcht des Herrn unterweisen.\\
\\

<<v13>>
13 Wer ist der Mensch, der das Leben liebt /\\
 und gute Tage zu sehen wünscht? [fn:9]\\
\\

<<v14>>
14 Bewahre deine Zunge vor Bösem /\\
 und deine Lippen vor falscher Rede!\\
\\

<<v15>>
15 Meide das Böse und tu das Gute; /\\
 suche Frieden und jage ihm nach! [fn:10]\\
\\

<<v16>>
16 Die Augen des Herrn blicken auf die Gerechten, /\\
 seine Ohren hören ihr Schreien. [fn:11]\\
\\

<<v17>>
17 Das Antlitz des Herrn richtet sich gegen die Bösen, /\\
 um ihr Andenken von der Erde zu tilgen. [fn:12]\\
\\

<<v18>>
18 Schreien die Gerechten, so hört sie der Herr; /\\
 er entreißt sie all ihren Ängsten. [fn:13]\\
\\

<<v19>>
19 Nahe ist der Herr den zerbrochenen Herzen, /\\
 er hilft denen auf, die zerknirscht sind. [fn:14]\\
\\

<<v20>>
20 Der Gerechte muss viel leiden, /\\
 doch allem wird der Herr ihn entreißen. [fn:15]\\
\\

<<v21>>
21 Er behütet all seine Glieder, /\\
 nicht eines von ihnen wird zerbrochen.\\
\\

<<v22>>
22 Den Frevler wird seine Bosheit töten; /\\
 wer den Gerechten hasst, muss es büßen.\\
\\

<<v23>>
23 Der Herr erlöst seine Knechte; /\\
 straflos bleibt, wer zu ihm sich flüchtet.\\
\\

* Footnotes

[fn:1] [[file:1.Sam_21.org::v11][1 Sam 21,11-16]]

[fn:2] [[file:Ps_145.org::v2][145,2]]

[fn:3] euer Gesicht: Text korr.; H: ihr Gesicht.

[fn:4] [[file:Ps_91.org::v15][91,15]]

[fn:5] [[file:Ps_35.org::v5][35,5f]]; [[file:Ps_91.org::v11][91,11]]; [[file:Gen_32.org::v2][Gen 32,2f]]; [[file:Ex_14.org::v19][Ex 14,19]]

[fn:6] [[file:~/Documents/notes/Bibel/nt/1.Petr_2.org::v3][1 Petr 2,3]]

[fn:7] [[file:~/Documents/notes/Bibel/nt/Lk_1.org::v53][Lk 1,53]]

[fn:8] Reiche: Text korr. nach G und S; H: junge Löwen.

[fn:9] (13-17) [[file:~/Documents/notes/Bibel/nt/1.Petr_3.org::v10][1 Petr 3,10-12]]

[fn:10] [[file:Ps_37.org::v27][37,27]]; [[file:Spr_3.org::v7][Spr 3,7]]; [[file:~/Documents/notes/Bibel/nt/Hebr_12.org::v14][Hebr 12,14]]

[fn:11] [[file:Ps_33.org::v18][33,18]]

[fn:12] [[file:Ps_109.org::v15][109,15]]; [[file:Ijob_18.org::v17][Ijob 18,17]]

[fn:13] die Gerechten: ergänzt nach G, S und der aramäischen
Übersetzung.

[fn:14] [[file:Ps_51.org::v19][51,19]]; [[file:Ps_145.org::v18][145,18]]

[fn:15] [[file:~/Documents/notes/Bibel/nt/2.Kor_1.org::v5][2 Kor 1,5]]
