#+TITLE: Ps 37 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-30 Sa 17:03]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ps 37.html

* Ps 37

<<verses>>

<<v1>>
* Gott, der Anwalt der Guten

1 [Von David.] Errege dich nicht über die Bösen, /\\
 wegen der Übeltäter ereifere dich nicht! [fn:1]\\
\\

<<v2>>
2 Denn sie verwelken schnell wie das Gras, /\\
 wie grünes Kraut verdorren sie. [fn:2]\\
\\

<<v3>>
3 Vertrau auf den Herrn und tu das Gute, /\\
 bleib wohnen im Land und bewahre Treue!\\
\\

<<v4>>
4 Freu dich innig am Herrn! /\\
 Dann gibt er dir, was dein Herz begehrt. [fn:3]\\
\\

<<v5>>
5 Befiehl dem Herrn deinen Weg und vertrau ihm; /\\
 er wird es fügen. [fn:4]\\
\\

<<v6>>
6 Er bringt deine Gerechtigkeit heraus wie das Licht /\\
 und dein Recht so hell wie den Mittag. [fn:5]\\
\\

<<v7>>
7 Sei still vor dem Herrn und harre auf ihn! /\\
 Erhitze dich nicht über den Mann, dem alles gelingt, /\\
 den Mann, der auf Ränke sinnt. [fn:6]\\
\\

<<v8>>
8 Steh ab vom Zorn und lass den Grimm; /\\
 erhitze dich nicht, es führt nur zu Bösem. [fn:7]\\
\\

<<v9>>
9 Denn die Bösen werden ausgetilgt; /\\
 die aber auf den Herrn hoffen, werden das Land besitzen. [fn:8]\\
\\

<<v10>>
10 Eine Weile noch und der Frevler ist nicht mehr da; /\\
 schaust du nach seiner Wohnung - sie ist nicht mehr zu finden. [fn:9]\\
\\

<<v11>>
11 Doch die Armen werden das Land bekommen, /\\
 sie werden Glück in Fülle genießen. [fn:10]\\
\\

<<v12>>
12 Der Frevler sinnt auf Ränke gegen den Gerechten /\\
 und knirscht gegen ihn mit den Zähnen.\\
\\

<<v13>>
13 Der Herr verlacht ihn, /\\
 denn er sieht, dass sein Tag kommt. [fn:11]\\
\\

<<v14>>
14 Die Frevler zücken das Schwert /\\
 und spannen ihren Bogen; sie wollen den Schwachen und Armen fällen /\\
 und alle hinschlachten, die den rechten Weg gehn. [fn:12]\\
\\

<<v15>>
15 Ihr Schwert dringe in ihr eigenes Herz /\\
 und ihre Bogen sollen zerbrechen.\\
\\

<<v16>>
16 Besser das wenige, das der Gerechte besitzt, /\\
 als der Überfluss vieler Frevler. [fn:13]\\
\\

<<v17>>
17 Denn die Arme der Frevler werden zerschmettert, /\\
 doch die Gerechten stützt der Herr. [fn:14]\\
\\

<<v18>>
18 Der Herr kennt die Tage der Bewährten, /\\
 ihr Erbe hat ewig Bestand.\\
\\

<<v19>>
19 In bösen Zeiten werden sie nicht zuschanden, /\\
 sie werden satt in den Tagen des Hungers. [fn:15]\\
\\

<<v20>>
20 Doch die Frevler gehen zugrunde, /\\
 die Feinde des Herrn sind wie die Pracht der Auen: /\\
 Sie schwinden dahin, wie Rauch schwinden sie hin. [fn:16]\\
\\

<<v21>>
21 Der Frevler muss borgen und kann nicht bezahlen, /\\
 doch freigebig schenkt der Gerechte.\\
\\

<<v22>>
22 Denn wen der Herr segnet, der wird das Land besitzen, /\\
 aber wen er verflucht, der wird ausgetilgt. [fn:17]\\
\\

<<v23>>
23 Der Herr festigt die Schritte des Mannes, /\\
 er hat Gefallen an seinem Weg.\\
\\

<<v24>>
24 Auch wenn er strauchelt, stürzt er nicht hin; /\\
 denn der Herr hält ihn fest an der Hand. [fn:18]\\
\\

<<v25>>
25 Einst war ich jung, nun bin ich alt, /\\
 nie sah ich einen Gerechten verlassen /\\
 noch seine Kinder betteln um Brot.\\
\\

<<v26>>
26 Allzeit ist er mildtätig, gern leiht er aus, /\\
 seine Kinder werden zum Segen.\\
\\

<<v27>>
27 Meide das Böse und tu das Gute, /\\
 so bleibst du wohnen für immer. [fn:19]\\
\\

<<v28>>
28 Denn der Herr liebt das Recht /\\
 und verlässt seine Frommen nicht. Doch das Geschlecht der Frevler wird
ausgetilgt, /\\
 sie werden für immer vernichtet. [fn:20]\\
\\

<<v29>>
29 Die Gerechten werden das Land besitzen /\\
 und darin wohnen für alle Zeiten. [fn:21]\\
\\

<<v30>>
30 Der Mund des Gerechten bewegt Worte der Weisheit /\\
 und seine Zunge redet, was recht ist. [fn:22]\\
\\

<<v31>>
31 Er hat die Weisung seines Gottes im Herzen, /\\
 seine Schritte wanken nicht. [fn:23]\\
\\

<<v32>>
32 Der Frevler belauert den Gerechten /\\
 und sucht ihn zu töten. [fn:24]\\
\\

<<v33>>
33 Der Herr überlässt ihn nicht seiner Hand, /\\
 lässt nicht zu, dass man ihn vor Gericht verurteilt.\\
\\

<<v34>>
34 Hoffe auf den Herrn /\\
 und bleib auf seinem Weg! Er wird dich erhöhen zum Erben des Landes;
/\\
 du wirst sehen, wie der Frevler vernichtet wird.\\
\\

<<v35>>
35 Ich sah einen Frevler, bereit zu Gewalttat; /\\
 er reckte sich hoch wie eine grünende Zeder. [fn:25] [fn:26]\\
\\

<<v36>>
36 Wieder ging ich vorüber und er war nicht mehr da; /\\
 ich suchte ihn, doch er war nicht zu finden. [fn:27]\\
\\

<<v37>>
37 Achte auf den Frommen und schau auf den Redlichen! /\\
 Denn Zukunft hat der Mann des Friedens.\\
\\

<<v38>>
38 Die Sünder aber werden alle zusammen vernichtet; /\\
 die Zukunft der Frevler ist Untergang.\\
\\

<<v39>>
39 Die Rettung der Gerechten kommt vom Herrn, /\\
 er ist ihre Zuflucht in Zeiten der Not. [fn:28]\\
\\

<<v40>>
40 Der Herr hilft ihnen und rettet sie, /\\
 er rettet sie vor den Frevlern; er schenkt ihnen Heil, /\\
 denn sie suchen Zuflucht bei ihm.\\
\\

* Footnotes

[fn:1] [[file:Spr_23.org::v17][Spr 23,17]]; [[file:Spr_24.org::v19][24,19]]

[fn:2] [[file:Ps_90.org::v5][90,5f]]

[fn:3] [[file:Ps_20.org::v5][20,5]]

[fn:4] [[file:Ps_119.org::v1][119,1]]; [[file:Ps_55.org::v23][55,23]]; [[file:Spr_3.org::v5][Spr 3,5]]; [[file:Spr_16.org::v3][16,3]]

[fn:5] [[file:Ijob_11.org::v17][Ijob 11,17]]; [[file:Spr_4.org::v18][Spr 4,18]]

[fn:6] dem alles gelingt, wörtlich: dem sein Weg gelingt.

[fn:7] [[file:~/Documents/notes/Bibel/nt/Eph_4.org::v26][Eph 4,26]]

[fn:8] [[file:Ps_25.org::v13][25,13]]

[fn:9] [[file:Ijob_20.org::v8][Ijob 20,8f]]

[fn:10] [[file:~/Documents/notes/Bibel/nt/Mt_5.org::v5][Mt 5,5]]

[fn:11] [[file:Ps_59.org::v9][59,9]]; [[file:Ijob_18.org::v20][Ijob 18,20]]

[fn:12] [[file:Ps_11.org::v2][11,2]]

[fn:13] [[file:Spr_15.org::v16][Spr 15,16]]; [[file:Spr_16.org::v8][16,8]]

[fn:14] [[file:Ps_10.org::v15][10,15]]

[fn:15] [[file:Ps_33.org::v19][33,19]]

[fn:16] [[file:Ps_68.org::v3][68,3]]

[fn:17] [[file:Spr_2.org::v21][Spr 2,21f]]

[fn:18] [[file:Ps_145.org::v14][145,14]]; [[file:Spr_24.org::v16][Spr 24,16]]

[fn:19] [[file:Ps_34.org::v15][34,15]]; [[file:Am_5.org::v14][Am 5,14]]

[fn:20] sinngemäß umgestellt; Text korr.; H: sie werden für
immer bewahrt.

[fn:21] [[file:Ps_25.org::v13][25,13]]; [[file:Jes_60.org::v21][Jes 60,21]]

[fn:22] [[file:Spr_10.org::v31][Spr 10,31]]

[fn:23] [[file:Ps_40.org::v9][40,9]]

[fn:24] [[file:Ps_11.org::v2][11,2]]

[fn:25] [[file:Ps_92.org::v8][92,8]]; (35-36) [[file:Ijob_20.org::v6][Ijob 20,6f]]

[fn:26] Text korr.; H: und er entwickelte sich wie eine
lebenskräftige Pflanze.

[fn:27] Text korr. nach G, S und Hieronymus; H: ging er vorüber.

[fn:28] [[file:Ps_46.org::v2][46,2]]
