#+TITLE: Ps 32 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-12-15 Fr 22:40]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ps 32.html

* Ps 32

<<verses>>

<<v1>>
* Freude über die Vergebung

1 [Von David. Ein Weisheitslied.] Wohl dem, dessen Frevel vergeben /\\
 und dessen Sünde bedeckt ist. [fn:1]\\
\\

<<v2>>
2 Wohl dem Menschen, dem der Herr die Schuld nicht zur Last legt /\\
 und dessen Herz keine Falschheit kennt.\\
\\

<<v3>>
3 Solang ich es verschwieg, waren meine Glieder matt, /\\
 den ganzen Tag musste ich stöhnen.\\
\\

<<v4>>
4 Denn deine Hand lag schwer auf mir bei Tag und bei Nacht; /\\
 meine Lebenskraft war verdorrt wie durch die Glut des Sommers. [Sela] [fn:2] [fn:3]\\
\\

<<v5>>
5 Da bekannte ich dir meine Sünde /\\
 und verbarg nicht länger meine Schuld vor dir. Ich sagte: Ich will dem
Herrn meine Frevel bekennen. /\\
 Und du hast mir die Schuld vergeben. [Sela] [fn:4]\\
\\

<<v6>>
6 Darum soll jeder Fromme in der Not zu dir beten; /\\
 fluten hohe Wasser heran, ihn werden sie nicht erreichen. [fn:5] [fn:6]\\
\\

<<v7>>
7 Du bist mein Schutz, bewahrst mich vor Not; /\\
 du rettest mich und hüllst mich in Jubel. [Sela]\\
\\

<<v8>>
8 «Ich unterweise dich und zeige dir den Weg, den du gehen sollst. /\\
 Ich will dir raten; über dir wacht mein Auge.» [fn:7]\\
\\

<<v9>>
9 Werdet nicht wie Ross und Maultier, /\\
 die ohne Verstand sind. Mit Zaum und Zügel muss man ihr Ungestüm
bändigen, /\\
 sonst folgen sie dir nicht.\\
\\

<<v10>>
10 Der Frevler leidet viele Schmerzen, /\\
 doch wer dem Herrn vertraut, den wird er mit seiner Huld umgeben.\\
\\

<<v11>>
11 Freut euch am Herrn und jauchzt, ihr Gerechten, /\\
 jubelt alle, ihr Menschen mit redlichem Herzen! [fn:8]\\
\\

* Footnotes

[fn:1] [[file:Ps_65.org::v4][65,4]]; [[file:Ps_78.org::v38][78,38]]; [[file:Ps_83.org::v3][85,3]]; [[file:Ps_103.org::v3][103,3]]; [[file:Jes_1.org::v18][Jes 1,18]]; [[file:Jes_38.org::v17][38,17]]; [[file:Jer_31.org::v34][Jer 31,34]];
[[file:~/RoamNotes/notes/Bibel/nt/1.Joh_1.org::v9][1 Joh 1,9]]; (1-2) [[file:~/RoamNotes/notes/Bibel/nt/Röm_4.org::v7][Röm 4,7f]]

[fn:2] [[file:Ps_38.org::v3][38,3]]; [[file:Ps_102.org::v5][102,5f]]

[fn:3] Text korr.

[fn:4] [[file:Ps_38.org::v19][38,19]]

[fn:5] [[file:Ps_66.org::v12][66,12]]

[fn:6] Text korr.; H ist verderbt.

[fn:7] [[file:Ps_25.org::v12][25,12]]; [[file:Ps_119.org::v1][119,1]]; [[file:Ps_33.org::v18][33,18]]

[fn:8] [[file:Ps_33.org::v1][33,1]]
