#+TITLE: Ps 51 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-01-12 Fr 21:55]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Ps 51.html

<<verses>>

<<v1>>
* Bitte um Vergebung und Neuschaffung

1 [Für den Chormeister. Ein Psalm Davids,

<<v2>>
2 als der Prophet Natan zu ihm kam, nachdem sich David mit Batseba
vergangen hatte.] [fn:1]\\
\\

<<v3>>
3 Gott, sei mir gnädig nach deiner Huld, /\\
 tilge meine Frevel nach deinem reichen Erbarmen! [fn:2]\\
\\

<<v4>>
4 Wasch meine Schuld von mir ab /\\
 und mach mich rein von meiner Sünde!\\
\\

<<v5>>
5 Denn ich erkenne meine bösen Taten, /\\
 meine Sünde steht mir immer vor Augen. [fn:3]\\
\\

<<v6>>
6 Gegen dich allein habe ich gesündigt, /\\
 ich habe getan, was dir missfällt. So behältst du recht mit deinem
Urteil, /\\
 rein stehst du da als Richter. [fn:4]\\
\\

<<v7>>
7 Denn ich bin in Schuld geboren; /\\
 in Sünde hat mich meine Mutter empfangen. [fn:5]\\
\\

<<v8>>
8 Lauterer Sinn im Verborgenen gefällt dir, /\\
 im Geheimen lehrst du mich Weisheit.\\
\\

<<v9>>
9 Entsündige mich mit Ysop, dann werde ich rein; /\\
 wasche mich, dann werde ich weißer als Schnee. [fn:6]\\
\\

<<v10>>
10 Sättige mich mit Entzücken und Freude! /\\
 Jubeln sollen die Glieder, die du zerschlagen hast. [fn:7] [fn:8]\\
\\

<<v11>>
11 Verbirg dein Gesicht vor meinen Sünden, /\\
 tilge all meine Frevel!\\
\\

<<v12>>
12 Erschaffe mir, Gott, ein reines Herz /\\
 und gib mir einen neuen, beständigen Geist! [fn:9]\\
\\

<<v13>>
13 Verwirf mich nicht von deinem Angesicht /\\
 und nimm deinen heiligen Geist nicht von mir! [fn:10]\\
\\

<<v14>>
14 Mach mich wieder froh mit deinem Heil /\\
 mit einem willigen Geist rüste mich aus!\\
\\

<<v15>>
15 Dann lehre ich Abtrünnige deine Wege /\\
 und die Sünder kehren um zu dir.\\
\\

<<v16>>
16 Befrei mich von Blutschuld, Herr, du Gott meines Heiles, /\\
 dann wird meine Zunge jubeln über deine Gerechtigkeit.\\
\\

<<v17>>
17 Herr, öffne mir die Lippen /\\
 und mein Mund wird deinen Ruhm verkünden.\\
\\

<<v18>>
18 Schlachtopfer willst du nicht, ich würde sie dir geben; /\\
 an Brandopfern hast du kein Gefallen. [fn:11]\\
\\

<<v19>>
19 Das Opfer, das Gott gefällt, ist ein zerknirschter Geist, /\\
 ein zerbrochenes und zerschlagenes Herz wirst du, Gott, nicht
verschmähen. [fn:12]\\
\\

<<v20>>
20 In deiner Huld tu Gutes an Zion; /\\
 bau die Mauern Jerusalems wieder auf! [fn:13]\\
\\

<<v21>>
21 Dann hast du Freude an rechten Opfern, /\\
 an Brandopfern und Ganzopfern, /\\
 dann opfert man Stiere auf deinem Altar. [fn:14]\\
\\

* Footnotes

[fn:1] [[file:2.Sam_12.org][2 Sam 12]]

[fn:2] [[file:~/Documents/notes/Bibel/nt/Lk_18.org::v13][Lk 18,13]]

[fn:3] [[file:Jes_59.org::v12][Jes 59,12]]

[fn:4] [[file:~/Documents/notes/Bibel/nt/Röm_3.org::v4][Röm 3,4]]

[fn:5] [[file:Ijob_14.org::v4][Ijob 14,4]]; [[file:~/Documents/notes/Bibel/nt/Joh_3.org::v6][Joh 3,6]]

[fn:6] [[file:Num_19.org::v18][Num 19,18]]; [[file:Jes_1.org::v18][Jes 1,18]]

[fn:7] [[file:Ps_6.org::v3][6,3]]

[fn:8] Text korr.

[fn:9] [[file:Ez_36.org::v26][Ez 36,26f]]

[fn:10] (13-14) [[file:~/Documents/notes/Bibel/nt/Röm_8.org::v9][Röm 8,9]].[[file:~/Documents/notes/Bibel/nt/Röm_8.org::v14][14-16]]

[fn:11] [[file:Ps_40.org::v7][40,7]]

[fn:12] [[file:Ps_34.org::v19][34,19]]; [[file:Jes_57.org::v15][Jes 57,15]]; [[file:Ps_66.org::v2][66,2]]; [[file:Dan_3.org::v39][Dan 3,39]]

[fn:13] [[file:Ps_147.org::v2][147,2]]

[fn:14] [[file:Ps_4.org::v6][4,6]]
