#+TITLE: Pc 68 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-07-31 Mi 16:51]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Pc 68.html

* Ps 68

<<verses>>

<<v1>>
* Ein Lied auf Gottes Sieg und Herrschaft

1 [Für den Chormeister. Ein Psalm Davids. Ein Lied.]\\
\\

<<v2>>
2 Gott steht auf, seine Feinde zerstieben; /\\
 die ihn hassen, fliehen vor seinem Angesicht. [fn:1]\\
\\

<<v3>>
3 Sie verfliegen, wie Rauch verfliegt; /\\
 wie Wachs am Feuer zerfließt, /\\
 so vergehen die Frevler vor Gottes Angesicht. [fn:2] [fn:3]\\
\\

<<v4>>
4 Die Gerechten aber freuen sich und jubeln vor Gott; /\\
 sie jauchzen in heller Freude.\\
\\

<<v5>>
5 Singt für Gott, spielt seinem Namen; /\\
 jubelt ihm zu, ihm, der auf den Wolken einherfährt! Preist seinen
Namen! /\\
 Freut euch vor seinem Angesicht! [fn:4] [fn:5]\\
\\

<<v6>>
6 Ein Vater der Waisen, ein Anwalt der Witwen /\\
 ist Gott in seiner heiligen Wohnung. [fn:6]\\
\\

<<v7>>
7 Gott bringt die Verlassenen heim, /\\
 führt die Gefangenen hinaus in das Glück; /\\
 doch die Empörer müssen wohnen im dürren Land. [fn:7]\\
\\

<<v8>>
8 Gott, als du deinem Volk voranzogst, /\\
 als du die Wüste durchschrittest, [Sela] / [fn:8]\\
\\

<<v9>>
9 da bebte die Erde, da ergossen sich die Himmel vor Gott, /\\
 vor Gott, dem Herrn vom Sinai, vor Israels Gott. [fn:9]\\
\\

<<v10>>
10 Gott, du ließest Regen strömen in Fülle /\\
 und erquicktest dein verschmachtendes Erbland.\\
\\

<<v11>>
11 Deine Geschöpfe finden dort Wohnung; /\\
 Gott, in deiner Güte versorgst du den Armen.\\
\\

<<v12>>
12 Der Herr entsendet sein Wort; /\\
 groß ist der Siegesbotinnen Schar. [fn:10]\\
\\

<<v13>>
13 Die Könige der Heere fliehen, sie fliehen. /\\
 Im Haus verteilt man die Beute. [fn:11]\\
\\

<<v14>>
14 Was bleibt ihr zurück in den Hürden? /\\
 Du Taube mit silbernen Schwingen, mit goldenem Flügel! [fn:12]\\
\\

<<v15>>
15 Als der Allmächtige die Könige vertrieb, /\\
 fiel Schnee auf dem Zalmon. [fn:13]\\
\\

<<v16>>
16 Ein Gottesberg ist der Baschanberg, /\\
 ein Gebirge, an Gipfeln reich, ist der Baschan.\\
\\

<<v17>>
17 Warum blickt ihr voll Neid, ihr hohen Gipfel, /\\
 auf den Berg, den Gott sich zum Wohnsitz erwählt hat? /\\
 Dort wird der Herr wohnen in Ewigkeit. [fn:14]\\
\\

<<v18>>
18 Die Wagen Gottes sind zahllos, tausendmal tausend. /\\
 Vom Sinai zieht der Herr zu seinem Heiligtum. [fn:15] [fn:16]\\
\\

<<v19>>
19 Du zogst hinauf zur Höhe, /\\
 führtest Gefangene mit; du nahmst Gaben entgegen von den Menschen. /\\
 Auch Empörer müssen wohnen bei Gott, dem Herrn. [fn:17]\\
\\

<<v20>>
20 Gepriesen sei der Herr, Tag für Tag! /\\
 Gott trägt uns, er ist unsre Hilfe. [Sela] [fn:18]\\
\\

<<v21>>
21 Gott ist ein Gott, der uns Rettung bringt, /\\
 Gott, der Herr, führt uns heraus aus dem Tod. [fn:19]\\
\\

<<v22>>
22 Denn Gott zerschmettert das Haupt seiner Feinde, /\\
 den Kopf des Frevlers, der in Sünde dahinlebt.\\
\\

<<v23>>
23 Der Herr hat gesprochen: «Ich bringe (sie) vom Baschan zurück, /\\
 ich bringe (sie) zurück aus den Tiefen des Meeres.\\
\\

<<v24>>
24 Dein Fuß wird baden im Blut, /\\
 die Zunge deiner Hunde ihren Anteil bekommen an den Feinden.» [fn:20] [fn:21]\\
\\

<<v25>>
25 Gott, sie sahen deinen Einzug, /\\
 den Einzug meines Gottes und Königs ins Heiligtum: [fn:22]\\
\\

<<v26>>
26 voraus die Sänger, die Saitenspieler danach, /\\
 dazwischen Mädchen mit kleinen Pauken. [fn:23]\\
\\

<<v27>>
27 Versammelt euch und preist unsern Gott, /\\
 den Herrn in der Gemeinde Israels: [fn:24]\\
\\

<<v28>>
28 voran der kleine Stamm Benjamin, /\\
 im Zug die Fürsten von Juda, /\\
 die Fürsten von Sebulon, die Fürsten von Naftali. [fn:25] [fn:26]\\
\\

<<v29>>
29 Biete auf, o Gott, deine Macht, /\\
 die Gottesmacht, die du an uns erwiesen hast / [fn:27] [fn:28]\\
\\

<<v30a>>
30a von deinem Tempel aus, hoch über Jerusalem.\\
\\

<<v31>>
31 Wehr ab das Untier im Schilf, die Rotte der Starken, /\\
 wehr ab die Herrscher der Völker! Sie sind gierig nach Silber, tritt
sie nieder; /\\
 zerstreue die Völker, die Lust haben am Krieg. [fn:29] [fn:30]\\
\\

<<v30b>>
30b Könige kommen mit Gaben, /\\
\\

<<v32>>
32 aus Ägypten bringt man Geräte von Erz, /\\
 Kusch erhebt zu Gott seine Hände. [fn:31]\\
\\

<<v33>>
33 Ihr Königreiche der Erde, singt für Gott, /\\
 singt und spielt für den Herrn, [Sela] [fn:32]\\
\\

<<v34>>
34 der dahinfährt über den Himmel, den uralten Himmel, /\\
 der seine Stimme erhebt, seine machtvolle Stimme.\\
\\

<<v35>>
35 Preist Gottes Macht! /\\
 Über Israel ragt seine Hoheit empor, /\\
 seine Macht ragt bis zu den Wolken.\\
\\

<<v36>>
36 Gott in seinem Heiligtum ist voll Majestät, Israels Gott; /\\
 seinem Volk verleiht er Stärke und Kraft. Gepriesen sei Gott. [fn:33]\\
\\

* Footnotes

[fn:1] [[file:Num_10.org::v35][Num 10,35]]; [[file:Jes_33.org::v3][Jes 33,3]]

[fn:2] [[file:Ps_92.org::v10][92,10]]

[fn:3] Sie verfliegen, wie Rauch verfliegt: Text korr.; H: Wie
Rauch verweht wird, den du auseinander wehst.

[fn:4] [[file:Ps_7.org::v18][7,18]]; [[file:Ps_18.org::v11][18,11]]; [[file:Dtn_33.org::v26][Dtn 33,26]]; [[file:Jes_19.org::v1][Jes 19,1]]

[fn:5] Text korr.

[fn:6] [[file:Ps_10.org::v18][10,18]]

[fn:7] [[file:Ps_146.org::v7][146,7]]

[fn:8] [[file:Ex_13.org::v21][Ex 13,21]]; [[file:Dtn_33.org::v2][Dtn 33,2]]

[fn:9] [[file:Ps_18.org::v8][18,8]]; [[file:Ps_77.org::v19][77,19]]; [[file:Ps_97.org::v4][97,4]]; [[file:Ps_99.org::v1][99,1]]; [[file:Ps_104.org::v32][104,32]]; [[file:Ps_114.org::v6][114,6f]]; [[file:Ex_19.org::v18][Ex 19,18]]; [[file:Ri_5.org::v4][Ri 5,4f]]; [[file:Sir_16.org::v18][Sir 16,18f]]; [[file:Jes_63.org::v19][Jes 63,19]]; [[file:Hab_3.org::v6][Hab 3,6]]

[fn:10] [[file:Jes_52.org::v7][Jes 52,7]]

[fn:11] Text korr.

[fn:12] [[file:Ri_5.org::v16][Ri 5,16]].[[file:Ri_5.org::v23][23]]

[fn:13] [[file:Ri_9.org::v48][Ri 9,48]]

[fn:14] [[file:Ps_132.org::v13][132,13]]; [[file:Ez_43.org::v7][Ez 43,7]]

[fn:15] [[file:2.Kön_6.org::v17][2 Kön 6,17]]

[fn:16] Text korr.; H: Der Herr ist unter ihnen, (der vom) Sinai (ist) im Heiligtum.

[fn:17] [[file:Ps_47.org::v6][47,6]]; [[file:~/RoamNotes/notes/Bibel/nt/Eph_4.org::v8][Eph 4,8-10]]

[fn:18] [[file:Ps_145.org::v2][145,2]]; [[file:Jes_46.org::v3][Jes 46,3f]]; [[file:Ps_63.org::v9][63,9]]

[fn:19] [[file:Ps_9.org::v14][9,14]]

[fn:20] [[file:Ps_58.org::v11][58,11]]; [[file:1.Kön_21.org::v19][1 Kön 21,19]]; [[file:1.Kön_22.org::v38][22,38]]

[fn:21] Text korr. nach G, S und der aramäischen Übersetzung;
H: damit du (Feinde) zerschmetterst, wobei dein Fuß im Blut (watet).

[fn:22] [[file:Ps_24.org::v7][24,7]]; [[file:2.Sam_6.org::v13][2 Sam 6,13-15]]

[fn:23] [[file:Ps_149.org::v3][149,3]]; [[file:2.Sam_6.org::v5][2 Sam 6,5]]

[fn:24] in der Gemeinde: Text korr.; H: ihr aus dem Brunnen Israels.

[fn:25] [[file:Ri_20.org::v43][Ri 20,43-48]]; [[file:Jes_8.org::v23][Jes 8,23]]

[fn:26] im Zug, wörtlich: im Lärmen der Menge.

[fn:27] [[file:Ps_80.org::v3][80,3]]

[fn:28] Gott: Text korr.; H: dein Gott.

[fn:29] [[file:Ez_29.org::v2][Ez 29,2f]]

[fn:30] Text korr.

[fn:31] [[file:Ps_72.org::v10][72,10]]; [[file:Jes_18.org::v7][Jes 18,7]]; [[file:Jes_45.org::v14][45,14]]; [[file:~/RoamNotes/notes/Bibel/nt/Apg_8.org::v27][Apg 8,27]]

[fn:32] [[file:Ps_7.org::v18][7,18]]

[fn:33] in seinem Heiligtum: Text korr.; H: aus deinem Heiligtum.
