#+TITLE: Ps 71 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-02 Fr 11:01]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Ps 71.html

* Ps 71

<<verses>>

<<v1>>
* Gott, die Zuflucht bis ins Alter

1 Herr, ich suche Zuflucht bei dir. /\\
 Lass mich doch niemals scheitern! [fn:1]\\
\\

<<v2>>
2 Reiß mich heraus und rette mich in deiner Gerechtigkeit, /\\
 wende dein Ohr mir zu und hilf mir!\\
\\

<<v3>>
3 Sei mir ein sicherer Hort, /\\
 zu dem ich allzeit kommen darf. Du hast mir versprochen zu helfen; /\\
 denn du bist mein Fels und meine Burg. [fn:2]\\
\\

<<v4>>
4 Mein Gott, rette mich aus der Hand des Frevlers, /\\
 aus der Faust des Bedrückers und Schurken! [fn:3]\\
\\

<<v5>>
5 Herr, mein Gott, du bist ja meine Zuversicht, /\\
 meine Hoffnung von Jugend auf.\\
\\

<<v6>>
6 Vom Mutterleib an stütze ich mich auf dich, /\\
 vom Mutterschoß an bist du mein Beschützer; /\\
 dir gilt mein Lobpreis allezeit. [fn:4]\\
\\

<<v7>>
7 Für viele bin ich wie ein Gezeichneter, /\\
 du aber bist meine starke Zuflucht. [fn:5]\\
\\

<<v8>>
8 Mein Mund ist erfüllt von deinem Lob, /\\
 von deinem Ruhm den ganzen Tag.\\
\\

<<v9>>
9 Verwirf mich nicht, wenn ich alt bin, /\\
 verlass mich nicht, wenn meine Kräfte schwinden. [fn:6]\\
\\

<<v10>>
10 Denn meine Feinde reden schlecht von mir, /\\
 die auf mich lauern, beraten gemeinsam;\\
\\

<<v11>>
11 sie sagen: «Gott hat ihn verlassen. /\\
 Verfolgt und ergreift ihn! /\\
 Für ihn gibt es keinen Retter.» [fn:7]\\
\\

<<v12>>
12 Gott, bleib doch nicht fern von mir! /\\
 Mein Gott, eil mir zu Hilfe! [fn:8]\\
\\

<<v13>>
13 Alle, die mich bekämpfen, /\\
 sollen scheitern und untergehn; über sie komme Schmach und Schande, /\\
 weil sie mein Unglück suchen. [fn:9] [fn:10]\\
\\

<<v14>>
14 Ich aber will jederzeit hoffen, /\\
 all deinen Ruhm noch mehren.\\
\\

<<v15>>
15 Mein Mund soll von deiner Gerechtigkeit künden /\\
 und von deinen Wohltaten sprechen den ganzen Tag; /\\
 denn ich kann sie nicht zählen. [fn:11]\\
\\

<<v16>>
16 Ich will kommen in den Tempel Gottes, des Herrn, /\\
 deine großen und gerechten Taten allein will ich rühmen. [fn:12]\\
\\

<<v17>>
17 Gott, du hast mich gelehrt von Jugend auf /\\
 und noch heute verkünde ich dein wunderbares Walten.\\
\\

<<v18>>
18 Auch wenn ich alt und grau bin, /\\
 o Gott, verlass mich nicht, damit ich von deinem machtvollen Arm der
Nachwelt künde, /\\
 den kommenden Geschlechtern von deiner Stärke / [fn:13]\\
\\

<<v19>>
19 und von deiner Gerechtigkeit, Gott, die größer ist als alles. Du hast
Großes vollbracht. /\\
 Mein Gott, wer ist wie du? [fn:14]\\
\\

<<v20>>
20 Du ließest mich viel Angst und Not erfahren. /\\
 Belebe mich neu, /\\
 führe mich herauf aus den Tiefen der Erde! [fn:15]\\
\\

<<v21>>
21 Bring mich wieder zu Ehren! /\\
 Du wirst mich wiederum trösten.\\
\\

<<v22>>
22 Dann will ich dir danken mit Saitenspiel /\\
 und deine Treue preisen; mein Gott, du Heiliger Israels, /\\
 ich will dir auf der Harfe spielen. [fn:16]\\
\\

<<v23>>
23 Meine Lippen sollen jubeln, /\\
 denn dir will ich singen und spielen, /\\
 meine Seele, die du erlöst hast, soll jubeln. [fn:17]\\
\\

<<v24>>
24 Auch meine Zunge soll von deiner Gerechtigkeit reden den ganzen Tag.
/\\
 Denn alle, die mein Unglück suchen, müssen vor Scham erröten und
scheitern. [fn:18]\\
\\

* Footnotes

[fn:1] (1-2) 31,2f

[fn:2] 92,16

[fn:3] 140,2

[fn:4] 22,11

[fn:5] 31,12; Jes 52,14

[fn:6] Jes 46,4

[fn:7] 3,3; 22,9; 69,27

[fn:8] 22,12

[fn:9] 35,4

[fn:10] Wörtlich: sie sollen sich kleiden in Schmach und Schande.

[fn:11] 35,28

[fn:12] Andere Übersetzungsmöglichkeit: Ich will kommen mit
den Großtaten Gottes, des Herrn.

[fn:13] 22,31f

[fn:14] 40,6; 72,18; 86,8

[fn:15] 9,14

[fn:16] Jes 6,3; 43,3

[fn:17] 7,18

[fn:18] 40,15
