#+TITLE: Ps 84 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-04 So 11:01]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Ps 84.html

* Ps 84

<<verses>>

<<v1>>
* Die Freude am Heiligtum

1 [Für den Chormeister. Nach dem Kelterlied. Ein Psalm der
Korachiter.]\\
\\

<<v2>>
2 Wie liebenswert ist deine Wohnung, Herr der Heerscharen! /\\
\\

<<v3>>
3 Meine Seele verzehrt sich in Sehnsucht /\\
 nach dem Tempel des Herrn. Mein Herz und mein Leib jauchzen ihm zu, /\\
 ihm, dem lebendigen Gott. [fn:1] [fn:2]\\
\\

<<v4>>
4 Auch der Sperling findet ein Haus /\\
 und die Schwalbe ein Nest für ihre Jungen - /\\
 deine Altäre, Herr der Heerscharen, mein Gott und mein König. [fn:3]\\
\\

<<v5>>
5 Wohl denen, die wohnen in deinem Haus, /\\
 die dich allezeit loben. [Sela] [fn:4]\\
\\

<<v6>>
6 Wohl den Menschen, die Kraft finden in dir, /\\
 wenn sie sich zur Wallfahrt rüsten.\\
\\

<<v7>>
7 Ziehen sie durch das trostlose Tal, /\\
 wird es für sie zum Quellgrund /\\
 und Frühregen hüllt es in Segen.\\
\\

<<v8>>
8 Sie schreiten dahin mit wachsender Kraft; /\\
 dann schauen sie Gott auf dem Zion. [fn:5]\\
\\

<<v9>>
9 Herr der Heerscharen, höre mein Beten, /\\
 vernimm es, Gott Jakobs! [Sela] [fn:6]\\
\\

<<v10>>
10 Gott, sieh her auf unsern Schild, /\\
 schau auf das Antlitz deines Gesalbten! [fn:7]\\
\\

<<v11>>
11 Denn ein einziger Tag in den Vorhöfen deines Heiligtums /\\
 ist besser als tausend andere. Lieber an der Schwelle stehen im Haus
meines Gottes /\\
 als wohnen in den Zelten der Frevler. [fn:8]\\
\\

<<v12>>
12 Denn Gott der Herr ist Sonne und Schild. /\\
 Er schenkt Gnade und Herrlichkeit; der Herr versagt denen, die
rechtschaffen sind, keine Gabe. / [fn:9]\\
\\

<<v13>>
13 Herr der Heerscharen, wohl dem, der dir vertraut!\\
\\

* Footnotes

[fn:1] [[file:Ps_27.org::v4][27,4]]

[fn:2] dem Tempel, wörtlich: den (Tempel-)Vorhöfen des Herrn.

[fn:3] [[file:Ps_5.org::v3][5,3]]

[fn:4] [[file:Ps_23.org::v6][23,6]]

[fn:5] Text korr.; H: er erscheint (ihnen), der Gott der Götter
auf dem Zion.

[fn:6] H: Herr, Gott der Heerscharen.

[fn:7] [[file:Ps_89.org::v19][89,19]]

[fn:8] [[file:Ps_27.org::v4][27,4]]

[fn:9] [[file:Ps_3.org::v4][3,4]]
