#+TITLE: Ps 98 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-08 Do 17:49]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Ps 98.html

* Ps 98

<<verses>>

<<v1>>
* Ein neues Lied auf den Richter und Retter

1 [Ein Psalm.] Singt dem Herrn ein neues Lied; /\\
 denn er hat wunderbare Taten vollbracht. Er hat mit seiner Rechten
geholfen /\\
 und mit seinem heiligen Arm. [fn:1]\\
\\

<<v2>>
2 Der Herr hat sein Heil bekannt gemacht /\\
 und sein gerechtes Wirken enthüllt vor den Augen der Völker.\\
\\

<<v3>>
3 Er dachte an seine Huld /\\
 und an seine Treue zum Hause Israel. Alle Enden der Erde /\\
 sahen das Heil unsres Gottes.\\
\\

<<v4>>
4 Jauchzt vor dem Herrn, alle Länder der Erde, /\\
 freut euch, jubelt und singt!\\
\\

<<v5>>
5 Spielt dem Herrn auf der Harfe, /\\
 auf der Harfe zu lautem Gesang!\\
\\

<<v6>>
6 Zum Schall der Trompeten und Hörner /\\
 jauchzt vor dem Herrn, dem König! [fn:2]\\
\\

<<v7>>
7 Es brause das Meer und alles, was es erfüllt, /\\
 der Erdkreis und seine Bewohner. [fn:3]\\
\\

<<v8>>
8 In die Hände klatschen sollen die Ströme, /\\
 die Berge sollen jubeln im Chor [fn:4]\\
\\

<<v9>>
9 vor dem Herrn, wenn er kommt, /\\
 um die Erde zu richten. Er richtet den Erdkreis gerecht, /\\
 die Nationen so, wie es recht ist. [fn:5]\\
\\

* Footnotes

[fn:1] [[file:Ps_33.org::v3][33,3]]; [[file:Jes_59.org::v16][Jes 59,16]]; [[file:Jes_63.org::v5][63,5]]

[fn:2] [[file:Ps_24.org::v7][24,7-10]]

[fn:3] [[file:Ps_96.org::v11][96,11]]

[fn:4] [[file:Ps_96.org::v12][96,12f]]

[fn:5] [[file:Ps_96.org::v13][96,13]]; [[file:Ps_67.org::v5][67,5]]
