#+TITLE: Ps 95 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-05 Mo 23:02]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Ps 95.html

* Ps 95

<<verses>>

<<v1>>
* Aufruf zur Treue gegen Gott

1 Kommt, lasst uns jubeln vor dem Herrn /\\
 und zujauchzen dem Fels unsres Heiles! [fn:1]\\
\\

<<v2>>
2 Lasst uns mit Lob seinem Angesicht nahen, /\\
 vor ihm jauchzen mit Liedern! [fn:2]\\
\\

<<v3>>
3 Denn der Herr ist ein großer Gott, /\\
 ein großer König über allen Göttern. [fn:3]\\
\\

<<v4>>
4 In seiner Hand sind die Tiefen der Erde, /\\
 sein sind die Gipfel der Berge.\\
\\

<<v5>>
5 Sein ist das Meer, das er gemacht hat, /\\
 das trockene Land, das seine Hände gebildet. [fn:4]\\
\\

<<v6>>
6 Kommt, lasst uns niederfallen, uns vor ihm verneigen, /\\
 lasst uns niederknien vor dem Herrn, unserm Schöpfer!\\
\\

<<v7>>
7 Denn er ist unser Gott, /\\
 wir sind das Volk seiner Weide, /\\
 die Herde, von seiner Hand geführt. Ach, würdet ihr doch heute auf
seine Stimme hören! / [fn:5]\\
\\

<<v8>>
8 «Verhärtet euer Herz nicht wie in Meríba, /\\
 wie in der Wüste am Tag von Massa! [fn:6]\\
\\

<<v9>>
9 Dort haben eure Väter mich versucht, /\\
 sie haben mich auf die Probe gestellt und hatten doch mein Tun gesehen. [fn:7]\\
\\

<<v10>>
10 Vierzig Jahre war mir dies Geschlecht zuwider /\\
 und ich sagte: Sie sind ein Volk, dessen Herz in die Irre geht; /\\
 denn meine Wege kennen sie nicht. [fn:8] [fn:9]\\
\\

<<v11>>
11 Darum habe ich in meinem Zorn geschworen: /\\
 Sie sollen nicht kommen in das Land meiner Ruhe.» [fn:10]\\
\\

* Footnotes

[fn:1] [[file:Ps_92.org::v16][92,16]]

[fn:2] [[file:Ps_100.org::v2][100,2]]

[fn:3] [[file:Ps_47.org::v3][47,3]]; [[file:Ps_48.org::v2][48,2]]; [[file:Ps_96.org::v4][96,4]]; [[file:Ps_99.org::v2][99,2]]; [[file:Ps_113.org::v4][113,4]]; [[file:Ps_136.org::v2][136,2f]]; [[file:Ps_145.org::v3][145,3]]; [[file:Ijob_36.org::v22][Ijob 36,22]]

[fn:4] [[file:Ps_24.org::v1][24,1]]

[fn:5] [[file:Ps_100.org::v3][100,3]]; (7-11) [[file:~/RoamNotes/notes/Bibel/nt/Hebr_3.org::v7][Hebr 3,7-11]].[[file:~/RoamNotes/notes/Bibel/nt/Hebr_3.org::v15][15]]; [[file:~/RoamNotes/notes/Bibel/nt/Hebr_4.org::v1][4,1-10]]

[fn:6] [[file:Ps_81.org::v8][81,8]]

[fn:7] [[file:Num_14.org::v22][Num 14,22]]; [[file:Dtn_6.org::v16][Dtn 6,16]]

[fn:8] [[file:Num_14.org::v30][Num 14,30]].[[file:Num_14.org::v34][34]]; [[file:dtn32::v5][Dtn 32,5]].[[file:Dtn_32.org::v20][20]]; [[file:Ijob_21.org::v14][Ijob 21,14]]

[fn:9] dies: ergänzt nach G.

[fn:10] [[file:Num_14.org::v22][Num 14,22f]]; [[file:Ps_132.org::v14][Ps 132,14]]; [[file:Ez_20.org::v15][Ez 20,15]]
