#+TITLE: Ps 94 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-05 Mo 22:35]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Ps 94.html

* Ps 94

<<verses>>

<<v1>>
* Gott, der Anwalt der Gerechten

1 Gott der Vergeltung, o Herr, /\\
 du Gott der Vergeltung, erscheine! [fn:1]\\
\\

<<v2>>
2 Erhebe dich, Richter der Erde, /\\
 vergilt den Stolzen ihr Tun! [fn:2]\\
\\

<<v3>>
3 Wie lange noch dürfen die Frevler, o Herr, /\\
 wie lange noch dürfen die Frevler frohlocken?\\
\\

<<v4>>
4 Sie führen freche Reden, /\\
 alle, die Unrecht tun, brüsten sich. [fn:3]\\
\\

<<v5>>
5 Herr, sie zertreten dein Volk, /\\
 sie unterdrücken dein Erbteil.\\
\\

<<v6>>
6 Sie bringen die Witwen und Waisen um /\\
 und morden die Fremden. [fn:4]\\
\\

<<v7>>
7 Sie denken: Der Herr sieht es ja nicht, /\\
 der Gott Jakobs merkt es nicht. [fn:5]\\
\\

<<v8>>
8 Begreift doch, ihr Toren im Volk! /\\
 Ihr Unvernünftigen, wann werdet ihr klug? [fn:6]\\
\\

<<v9>>
9 Sollte der nicht hören, der das Ohr gepflanzt hat, /\\
 sollte der nicht sehen, der das Auge geformt hat? [fn:7]\\
\\

<<v10>>
10 Sollte der nicht strafen, der die Völker erzieht, /\\
 er, der die Menschen Erkenntnis lehrt?\\
\\

<<v11>>
11 Der Herr kennt die Gedanken der Menschen: /\\
 Sie sind nichts als ein Hauch. [fn:8]\\
\\

<<v12>>
12 Wohl dem Mann, den du, Herr, erziehst, /\\
 den du mit deiner Weisung belehrst. [fn:9]\\
\\

<<v13>>
13 Du bewahrst ihn vor bösen Tagen, /\\
 bis man dem Frevler die Grube gräbt.\\
\\

<<v14>>
14 Ja, der Herr wird sein Volk nicht verstoßen /\\
 und niemals sein Erbe verlassen. [fn:10]\\
\\

<<v15>>
15 Nun spricht man wieder Recht nach Gerechtigkeit; /\\
 ihr folgen alle Menschen mit redlichem Herzen.\\
\\

<<v16>>
16 Wer wird sich für mich gegen die Frevler erheben, /\\
 wer steht für mich ein gegen den, der Unrecht tut?\\
\\

<<v17>>
17 Wäre nicht der Herr meine Hilfe, /\\
 bald würde ich im Land des Schweigens wohnen. [fn:11]\\
\\

<<v18>>
18 Wenn ich sage: «Mein Fuß gleitet aus», /\\
 dann stützt mich, Herr, deine Huld. [fn:12]\\
\\

<<v19>>
19 Mehren sich die Sorgen des Herzens, /\\
 so erquickt dein Trost meine Seele. [fn:13]\\
\\

<<v20>>
20 Kann sich mit dir der bestechliche Richter verbünden, /\\
 der willkürlich straft, gegen das Gesetz? [fn:14]\\
\\

<<v21>>
21 Sie wollen das Leben des Gerechten vernichten /\\
 und verurteilen schuldlose Menschen.\\
\\

<<v22>>
22 Doch meine Burg ist der Herr, /\\
 mein Gott ist der Fels meiner Zuflucht. [fn:15]\\
\\

<<v23>>
23 Er wird ihnen ihr Unrecht vergelten /\\
 und sie wegen ihrer Bosheit vernichten; /\\
 vernichten wird sie der Herr, unser Gott. [fn:16]\\
\\

* Footnotes

[fn:1] [[file:Dtn_32.org::v35][Dtn 32,35]]; [[file:Nah_1.org::v2][Nah 1,2]]

[fn:2] [[file:Jer_51.org::v56][Jer 51,56]]; [[file:Ps_62.org::v13][Ps 62,13]]

[fn:3] [[file:Ps_75.org::v6][75,6]]

[fn:4] [[file:Ex_22.org::v21][Ex 22,21f]]; [[file:Ez_22.org::v7][Ez 22,7]]

[fn:5] [[file:Ps_10.org::v11][10,11]]

[fn:6] [[file:Spr_1.org::v22][Spr 1,22]]; [[file:Spr_8.org::v5][8,5]]

[fn:7] [[file:Ps_33.org::v15][33,15]]; [[file:Ex_4.org::v11][Ex 4,11]]; [[file:Spr_20.org::v12][Spr 20,12]]

[fn:8] [[file:~/Documents/notes/Bibel/nt/1.Kor_3.org::v20][1 Kor 3,20]]

[fn:9] [[file:Ps_119.org::v71][119,71]]; [[file:Ijob_5.org::v17][Ijob 5,17]]

[fn:10] [[file:1.Sam_12.org::v22][1 Sam 12,22]]

[fn:11] [[file:Ps_115.org::v17][115,17]]

[fn:12] [[file:Ps_145.org::v14][145,14]]

[fn:13] [[file:~/Documents/notes/Bibel/nt/2.Kor_1.org::v4][2 Kor 1,4f]]

[fn:14] der bestechliche Richter, wörtlich: ein Richterstuhl
des Verderbens.

[fn:15] [[file:Ps_92.org::v16][92,16]]

[fn:16] [[file:Ps_7.org::v17][7,17]]; [[file:Spr_5.org::v22][Spr 5,22]]; [[file:Ps_62.org::v13][Ps 62,13]]
