#+TITLE: Ps 99 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-08 Do 18:00]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Ps 99.html

* Ps 99

<<verses>>

<<v1>>
* Der heilige Gott auf dem Zion

1 Der Herr ist König: Es zittern die Völker. /\\
 Er thront auf den Kerubim: Es wankt die Erde. [fn:1]\\
\\

<<v2>>
2 Groß ist der Herr auf Zion, /\\
 über alle Völker erhaben. [fn:2]\\
\\

<<v3>>
3 Preisen sollen sie deinen großen, majestätischen Namen. /\\
 Denn er ist heilig. [fn:3]\\
\\

<<v4>>
4 Stark ist der König, er liebt das Recht. /\\
 Du hast die Weltordnung fest begründet, /\\
 hast Recht und Gerechtigkeit in Jakob geschaffen. [fn:4]\\
\\

<<v5>>
5 Rühmt den Herrn, unseren Gott; /\\
 werft euch am Schemel seiner Füße nieder! /\\
 Denn er ist heilig. [fn:5]\\
\\

<<v6>>
6 Mose und Aaron sind unter seinen Priestern, /\\
 Samuel unter denen, die seinen Namen anrufen; /\\
 sie riefen zum Herrn und er hat sie erhört. [fn:6] [fn:7]\\
\\

<<v7>>
7 Aus der Wolkensäule sprach er zu ihnen; /\\
 seine Gebote hielten sie, /\\
 die Satzung, die er ihnen gab. [fn:8]\\
\\

<<v8>>
8 Herr, unser Gott, du hast sie erhört; /\\
 du warst ihnen ein verzeihender Gott, /\\
 aber du hast ihre Frevel vergolten. [fn:9]\\
\\

<<v9>>
9 Rühmt den Herrn, unsern Gott, /\\
 werft euch nieder an seinem heiligen Berge! /\\
 Denn heilig ist der Herr, unser Gott.\\
\\

* Footnotes

[fn:1] [[file:Ps_24.org::v7][24,7-10]]; [[file:Ps_80.org::v2][80,2]]

[fn:2] [[file:Ps_48.org::v2][48,2]]; [[file:Ps_95.org::v3][95,3]]

[fn:3] [[file:Ps_111.org::v9][111,9]]

[fn:4] H: Und die Stärke des Königs liebt das Recht.

[fn:5] [[file:Ps_132.org::v7][132,7]]

[fn:6] [[file:Jer_15.org::v1][Jer 15,1]]

[fn:7] Vorschlag für die Psalmodie: auch Samuel rief seinen
Namen an.

[fn:8] [[file:Ex_33.org::v9][Ex 33,9]]; [[file:Num_12.org::v5][Num 12,5]]

[fn:9] [[file:Ex_32.org::v11][Ex 32,11]]; [[file:Ex_34.org::v7][34,7]]
