#+TITLE: Ri 19 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-05 So 16:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ri 19.html


<<verses>>

<<v1>>
* Die Schandtat der Männer von Gibea: 19,1-30

1 In jenen Tagen, als es noch keinen König in Israel gab, lebte im
entlegensten Teil des Gebirges Efraim ein Levit als Fremder. Er hatte
sich eine Frau aus Betlehem in Juda zur Nebenfrau genommen. [fn:1]

<<v2>>
2 Aber seine Nebenfrau wurde zornig auf ihn und verließ ihn; sie ging in
das Haus ihres Vaters nach Betlehem in Juda zurück. Dort war sie nun
schon vier Monate lang. [fn:2]

<<v3>>
3 Da machte sich ihr Mann auf den Weg und zog ihr mit seinem Knecht und
zwei Eseln nach, um ihr ins Gewissen zu reden und sie zurückzuholen. Die
Frau brachte ihn in das Haus ihres Vaters, und als der Vater der jungen
Frau ihn sah, kam er ihm freudig entgegen.

<<v4>>
4 Da sein Schwiegervater, der Vater der jungen Frau, ihn dringend darum
bat, blieb er drei Tage bei ihm. Sie aßen und tranken und er
übernachtete dort.

<<v5>>
5 Als sie am vierten Tag frühmorgens aufgestanden waren und er sich auf
den Weg machen wollte, sagte der Vater der jungen Frau zu seinem
Schwiegersohn: Stärke dich erst noch mit einem Bissen Brot; dann könnt
ihr gehen.

<<v6>>
6 Sie setzten sich und die beiden aßen und tranken zusammen. Der Vater
der jungen Frau aber sagte zu dem Mann: Entschließ dich doch, (noch
einmal) über Nacht zu bleiben, und lass es dir gut gehen!

<<v7>>
7 Der Mann stand auf, um zu gehen; doch sein Schwiegervater nötigte ihn,
sodass er dort noch einmal übernachtete.

<<v8>>
8 Als er sich dann am Morgen des fünften Tages auf den Weg machen
wollte, sagte der Vater der jungen Frau: Stärke dich erst noch und
bleibt hier, bis der Tag zur Neige geht. So aßen die beiden zusammen.

<<v9>>
9 Dann stand der Mann auf, um mit seiner Nebenfrau und seinem Knecht
abzureisen. Sein Schwiegervater aber, der Vater der jungen Frau, sagte
zu ihm: Sieh doch, der Tag geht zu Ende und es wird Abend. Bleibt über
Nacht hier! Der Tag geht zur Neige; übernachte hier und lass es dir gut
gehen! Morgen früh könnt ihr euch dann auf den Heimweg zu deinem Zelt
machen.

<<v10>>
10 Aber der Mann wollte nicht mehr übernachten, sondern erhob sich und
ging mit seinen zwei gesattelten Eseln, seiner Nebenfrau und seinem
Knecht fort. Sie kamen zu einem Ort gegenüber von Jebus, das heißt
Jerusalem. [fn:3]

<<v11>>
11 Als sie dort waren, war der Tag schon fast zu Ende gegangen. Darum
sagte der Knecht zu seinem Herrn: Komm, wir wollen in der Jebusiterstadt
hier einkehren und übernachten.

<<v12>>
12 Sein Herr antwortete ihm: Wir wollen nicht in einer Stadt von
Fremden, die nicht zu den Israeliten gehört, einkehren, sondern nach
Gibea weiterziehen.

<<v13>>
13 Und er sagte zu seinem Knecht: Lass uns lieber zu einem anderen Ort
gehen; wir wollen in Gibea oder Rama übernachten. [fn:4]

<<v14>>
14 Sie zogen also weiter; als sie bei Gibea, das zu Benjamin gehört,
waren, ging die Sonne unter.

<<v15>>
15 Sie bogen daher dort (vom Weg) ab, um nach Gibea hineinzugehen und
dort zu übernachten. In der Stadt setzte er sich auf dem Marktplatz
nieder; aber es fand sich niemand, der ihn in seinem Haus zum
Übernachten aufnehmen wollte.

<<v16>>
16 Schließlich kam ein alter Mann am Abend von seiner Arbeit auf dem
Feld. Der Mann stammte aus dem Gebirge Efraim und lebte als Fremder in
Gibea; die Einwohner des Ortes waren Benjaminiter.

<<v17>>
17 Als der alte Mann aufsah, erblickte er den Wanderer auf dem Platz der
Stadt und fragte ihn: Woher kommst du und wohin gehst du?

<<v18>>
18 Er antwortete ihm: Wir sind auf der Durchreise von Betlehem in Juda
zum entlegensten Teil des Gebirges Efraim. Von dort komme ich; ich war
nach Betlehem in Juda gegangen und bin nun auf dem Weg nach Hause. Aber
hier findet sich niemand, der mich in sein Haus aufnimmt, [fn:5]

<<v19>>
19 obwohl wir alles dabeihaben, Stroh und Futter für unsere Esel und
auch Brot und Wein für mich, deine Magd und den Knecht, der bei deinem
Diener ist. Es fehlt also an nichts.

<<v20>>
20 Der alte Mann entgegnete: Sei mir willkommen! Was dir fehlt, das lass
nur meine Sorge sein; auf dem Platz jedenfalls darfst du nicht
übernachten.

<<v21>>
21 Und er führte ihn in sein Haus und schüttete den Eseln Futter vor.
Sie wuschen sich die Füße und aßen und tranken.

<<v22>>
22 Während sie sich's nun wohl sein ließen, umringten plötzlich einige
Männer aus der Stadt, übles Gesindel, das Haus, schlugen an die Tür und
sagten zu dem alten Mann, dem Besitzer des Hauses: Bring den Mann
heraus, der in dein Haus gekommen ist; wir wollen unseren Mutwillen mit
ihm treiben. [fn:6] [fn:7]

<<v23>>
23 Der Besitzer des Hauses ging zu ihnen hinaus und sagte zu ihnen:
Nein, meine Brüder, so etwas Schlimmes dürft ihr nicht tun. Dieser Mann
ist als Gast in mein Haus gekommen; darum dürft ihr keine solche
Schandtat begehen. [fn:8]

<<v24>>
24 Da ist meine jungfräuliche Tochter und seine Nebenfrau. Sie will ich
zu euch hinausbringen; ihr könnt sie euch gefügig machen und mit ihnen
tun, was euch gefällt. Aber an diesem Mann dürft ihr keine solche
Schandtat begehen.

<<v25>>
25 Doch die Männer wollten nicht auf ihn hören. Da ergriff der Levit
seine Nebenfrau und brachte sie zu ihnen auf die Straße hinaus. Sie
missbrauchten sie und trieben die ganze Nacht hindurch bis zum Morgen
ihren Mutwillen mit ihr. Sie ließen sie erst gehen, als die Morgenröte
heraufzog.

<<v26>>
26 Als der Morgen anbrach, kam die Frau zurück; vor der Haustür des
Mannes, bei dem ihr Herr wohnte, brach sie zusammen und blieb dort
liegen, bis es hell wurde.

<<v27>>
27 Ihr Herr stand am Morgen auf, öffnete die Haustür und ging hinaus, um
seine Reise fortzusetzen. Da lag die Frau, seine Nebenfrau,
zusammengebrochen am Eingang des Hauses, die Hände auf der Schwelle.

<<v28>>
28 Er sagte zu ihr: Steh auf, wir wollen gehen! Doch sie antwortete
nicht. Da legte er sie auf den Esel und machte sich auf die Heimreise.

<<v29>>
29 Als er nach Hause gekommen war, nahm er ein Messer, ergriff seine
Nebenfrau, zerschnitt sie in zwölf Stücke, Glied für Glied, und schickte
sie in das ganze Gebiet Israels. [fn:9] [fn:10]

<<v30>>
30 Jeder, der das sah, sagte: So etwas ist noch nie geschehen, so etwas
hat man nicht erlebt, seit die Söhne Israels aus Ägypten heraufgezogen
sind, bis zum heutigen Tag. Denkt darüber nach, beratet und sagt (was
ihr dazu meint)! [fn:11]\\
\\

* Footnotes

[fn:1] [[file:Ri_17.org::v6][17,6]]

[fn:2] wurde zornig: So versteht wohl zu Recht G den Text im
Sinn eines Zerwürfnisses.

[fn:3] und seinem Knecht: Text korr., vgl. G und V. 11f. -
Jebus wird Jerusalem wegen der dort wohnenden Jebusiter genannt.

[fn:4] 13f: Gibea, nördlich von Jerusalem, ist die Stadt Sauls.

[fn:5] nach Hause: Text korr. nach G und V. 29; H: zum Haus des
Herrn.

[fn:6] (22-24) [[file:Gen_19.org::v4][Gen 19,4-11]]

[fn:7] unseren Mutwillen mit ihm treiben, wörtlich: ihn
erkennen.

[fn:8] 23f: Der Hausherr muss nach den Regeln der
Gastfreundschaft den Gast schützen (vgl. die Anmerkung zu Gen 19,8).

[fn:9] [[file:1.Sam_11.org::v7][1 Sam 11,7]]

[fn:10] So wird die schreckliche Tat auf drastische Weise
mitgeteilt und alle werden aufgerufen, den Mord zu rächen.

[fn:11] [[file:Hos_10.org::v9][Hos 10,9]]
