#+TITLE: Ri 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-04 Sa 23:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ri 12.html

<<verses>>

<<v1>>
* Der Krieg der Efraimiter gegen Jiftach: 12,1-7

1 Die Männer aus Efraim wurden (zum Kampf) aufgeboten; sie zogen nach
Zafon und sagten zu Jiftach: Warum bist du gegen die Ammoniter in den
Kampf gezogen und hast uns nicht aufgefordert, mit dir zu ziehen? Wir
werden dir dein Haus über dem Kopf anzünden. [fn:1]

<<v2>>
2 Jiftach sagte zu ihnen: Ich selbst und mein Volk lagen mit den
Ammonitern in heftigem Streit. Ich habe euch gerufen, aber ihr habt mich
nicht aus ihrer Gewalt befreit.

<<v3>>
3 Als ich nun sah, dass ihr mir nicht helfen wolltet, setzte ich mein
Leben aufs Spiel und zog gegen die Ammoniter und der Herr gab sie in
meine Gewalt. Warum seid ihr nun heute zu mir heraufgekommen, um Krieg
mit mir anzufangen?

<<v4>>
4 Darauf sammelte Jiftach alle Männer aus Gilead und kämpfte gegen
Efraim und die Männer aus Gilead schlugen Efraim. Die Efraimiter hatten
gesagt: Ihr seid Flüchtlinge aus Efraim; Gilead liegt ja mitten in
Efraim, mitten in Manasse.

<<v5>>
5 Gilead besetzte die nach Efraim führenden Übergänge über den Jordan.
Und wenn efraimitische Flüchtlinge (kamen und) sagten: Ich möchte
hinüber!, fragten ihn die Männer aus Gilead: Bist du ein Efraimiter?
Wenn er Nein sagte,

<<v6>>
6 forderten sie ihn auf: Sag doch einmal «Schibbolet». Sagte er dann
«Sibbolet», weil er es nicht richtig aussprechen konnte, ergriffen sie
ihn und machten ihn dort an den Furten des Jordan nieder. So fielen
damals zweiundvierzigtausend Mann aus Efraim. [fn:2]

<<v7>>
7 Jiftach war sechs Jahre lang Richter in Israel. Dann starb Jiftach,
der Gileaditer, und wurde in seiner Stadt in Gilead begraben. [fn:3]\\
\\

<<v8>>
* Die Richter Ibzan, Elon und Abdon: 12,8-15

8 Nach ihm war Ibzan aus Betlehem Richter in Israel.

<<v9>>
9 Er hatte dreißig Söhne; dreißig Töchter gab er nach auswärts (in die
Ehe) und dreißig Töchter führte er seinen Söhnen von auswärts zu. Ibzan
war sieben Jahre lang Richter in Israel.

<<v10>>
10 Dann starb er und wurde in Betlehem begraben.

<<v11>>
11 Nach ihm war Elon, der Sebuloniter, Richter in Israel; er war zehn
Jahre lang Richter in Israel.

<<v12>>
12 Dann starb der Sebuloniter Elon und wurde in Ajalon im Land Sebulon
begraben.

<<v13>>
13 Nach ihm war Abdon, der Sohn Hillels aus Piraton, Richter in Israel.

<<v14>>
14 Er hatte vierzig Söhne und dreißig Enkel, die auf siebzig Eseln
ritten. Er war acht Jahre lang Richter in Israel.

<<v15>>
15 Dann starb Abdon, der Sohn Hillels aus Piraton, und wurde in Piraton,
im Land Efraim, auf dem Amalekiterberg begraben.\\
\\

* Footnotes

[fn:1] [[file:Ri_8.org::v1][8,1]]

[fn:2] An der besonderen Aussprache dieses Wortes werden die
efraimitischen Flüchtlinge erkannt.

[fn:3] in seiner Stadt: Text korr. nach G.
