#+TITLE: Ri 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-05 So 16:19]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ri 18.html

<<verses>>

<<v1>>
* Die Kundschafter aus Dan: 18,1-10

1 Damals gab es noch keinen König in Israel. Der Stamm der Daniter war
zu jener Zeit dabei, sich einen Erbbesitz zu suchen, um sich
niederzulassen; denn es war ihm inmitten der Stämme Israels bis zu jener
Zeit noch kein Erbbesitz zugefallen. [fn:1]

<<v2>>
2 Daher schickten die Daniter von ihrer Sippe fünf kampferprobte Männer
aus Zora und Eschtaol aus, um das Land zu durchstreifen und zu erkunden.
Sie sagten zu ihnen: Geht, erkundet das Land! Die Männer kamen ins
Gebirge Efraim zum Haus Michas und übernachteten dort. [fn:2]

<<v3>>
3 Als sie beim Haus Michas waren, fiel ihnen die Mundart des jungen
Leviten auf. Sie gingen zu ihm hin und fragten ihn: Wer hat dich hierher
gebracht? Was willst du hier und was tust du hier?

<<v4>>
4 Er antwortete ihnen: Das und das hat Micha mit mir gemacht; er hat
mich angestellt und so wurde ich sein Priester.

<<v5>>
5 Sie sagten zu ihm: Befrag doch Gott für uns, damit wir erfahren, ob
die Reise, die wir machen, Erfolg haben wird.

<<v6>>
6 Der Priester erwiderte ihnen: Zieht in Frieden weiter! Der Weg, den
ihr gehen wollt, liegt vor den Augen des Herrn.

<<v7>>
7 Die fünf Männer zogen weiter und kamen nach Lajisch. Sie sahen, dass
das Volk dort ungestört nach Art der Sidonier lebte, ruhig und sicher.
Es gab niemand, der Schaden anrichtete im Land, keinen Eroberer und
keine Unterdrückung. Sie waren weit entfernt von den Sidoniern und
hatten auch mit den Aramäern nichts zu tun. [fn:3]

<<v8>>
8 Als die Männer zu ihren Brüdern nach Zora und Eschtaol kamen, sagten
ihre Brüder zu ihnen: Wie ist es euch ergangen?

<<v9>>
9 Sie antworteten: Auf, lasst uns gegen jene Leute (in den Kampf)
ziehen. Denn wir haben gesehen, dass das Land sehr schön ist. Warum
wollt ihr zögern? Seid nicht so träge! Macht euch auf den Weg dorthin
und nehmt das Land in Besitz!

<<v10>>
10 Ihr findet ein sorgloses Volk vor, wenn ihr hinkommt. Das Land ist
nach allen Seiten hin weiträumig. Wahrhaftig, Gott hat es in eure Gewalt
gegeben. Es ist ein Ort, wo es an nichts fehlt, was es auf Erden gibt.\\
\\

<<v11>>
* Der Zug der Daniter nach Lajisch: 18,11-31

11 Darauf brachen von dort, also von Zora und Eschtaol aus, sechshundert
mit Waffen ausgerüstete Männer aus der Sippe der Daniter auf.

<<v12>>
12 Sie zogen hinauf und schlugen bei Kirjat-Jearim in Juda ihr Lager
auf; deshalb nennt man diesen Ort bis auf den heutigen Tag «Lager Dans»;
es liegt hinter Kirjat-Jearim.

<<v13>>
13 Von dort zogen sie hinüber ins Gebirge Efraim und kamen zum Haus
Michas.

<<v14>>
14 Da sagten die fünf Männer, die unterwegs gewesen waren, um das Land
[Lajisch] zu erkunden, zu ihren Brüdern: Wisst ihr auch, dass es in
diesen Häusern ein Efod und Terafim sowie ein mit Metall überzogenes
Gottesbild gibt? Überlegt also, was ihr tun wollt.

<<v15>>
15 Da bogen sie (von ihrem Weg) ab und gingen zum Haus des jungen
Leviten [zum Haus Michas] und begrüßten ihn.

<<v16>>
16 Die sechshundert mit Waffen ausgerüsteten Daniter blieben am Hoftor
stehen,

<<v17>>
17 während die fünf Männer, die unterwegs gewesen waren, um das Land zu
erkunden, hineingingen. Sie nahmen das Gottesbild mit dem Metallüberzug
sowie das Efod und die Terafim, während der Priester am Eingang des
Tores bei den sechshundert mit Waffen ausgerüsteten Männern stand.

<<v18>>
18 Als die Leute in das Haus Michas eindrangen und das Gottesbild mit
dem Metallüberzug, das Efod und die Terafim nahmen, fragte sie der
Priester: Was macht ihr da?

<<v19>>
19 Sie antworteten ihm: Schweig! Halt den Mund! Geh mit uns und werde
uns Vater und Priester! Was ist besser - wenn du Priester im Haus eines
einzigen Mannes bist oder wenn du Priester für einen Stamm und eine
Sippe in Israel bist?

<<v20>>
20 Das erschien dem Priester gut. Er nahm das Efod, die Terafim und das
Gottesbild und begab sich damit unter die Leute.

<<v21>>
21 Dann brachen sie auf und zogen weiter. Die Kinder, das Vieh und die
Habe führten sie an der Spitze des Zuges mit sich.

<<v22>>
22 Als sie schon weit vom Haus Michas weg waren, rief Micha die Männer
in den Häusern, die in der Nähe lagen, zusammen und sie verfolgten die
Daniter.

<<v23>>
23 Sie riefen hinter den Danitern her, diese aber wandten sich um und
sagten zu Micha: Was ist los? Warum habt ihr euch zusammengetan?

<<v24>>
24 Er antwortete: Ihr habt meinen Gott, den ich mir gemacht hatte, und
auch den Priester weggenommen und seid davongezogen. Was habe ich jetzt
noch? Wie könnt ihr da zu mir sagen: Was ist los?

<<v25>>
25 Die Daniter entgegneten ihm: Lass dein Geschwätz, sonst fallen unsere
erbitterten Leute über euch her und du bist selbst schuld, wenn du
zusammen mit deiner Familie das Leben verlierst.

<<v26>>
26 Dann zogen die Daniter auf ihrem Weg weiter. Micha aber sah ein, dass
sie stärker waren als er, kehrte um und ging nach Hause zurück.

<<v27>>
27 Sie aber nahmen das Bild, das Micha angefertigt hatte, samt dem
Priester, den er hatte, und überfielen Lajisch, ein ruhiges und
friedliches Volk. Sie erschlugen die Leute mit scharfem Schwert und
steckten die Stadt in Brand. [fn:4]

<<v28>>
28 Niemand konnte zu Hilfe kommen; denn die Stadt lag weit entfernt von
Sidon und hatte auch mit den Aramäern nichts zu tun; sie lag im Tal von
Bet-Rehob. Die Daniter bauten die Stadt wieder auf und wohnten in ihr. [fn:5]

<<v29>>
29 Sie nannten sie Dan, nach dem Namen ihres Stammvaters Dan, der einst
dem Israel geboren worden war. Doch früher hatte die Stadt den Namen
Lajisch.

<<v30>>
30 Die Daniter stellten das Gottesbild bei sich auf und Jonatan, der
Sohn Gerschoms, des Sohnes des Mose, und seine Nachkommen dienten dem
Stamm der Daniter als Priester bis zu dem Tag, an dem die Bewohner des
Landes in die Gefangenschaft geführt wurden. [fn:6] [fn:7]

<<v31>>
31 Sie hatten also das Gottesbild, das Micha gemacht hatte, bei sich
aufgestellt und (es stand dort) die ganze Zeit über, solange es das
Gotteshaus in Schilo gab.\\
\\

* Footnotes

[fn:1] [[file:Ri_17.org::v6][17,6]]; [[file:Ri_1.org::v34][1,34;]] [[file:Ri_19.org::v47][Jos 19,47]]

[fn:2] fünf kampferprobte Männer: Text korr. nach G.

[fn:3] mit den Aramäern: Text korr. nach G; H: mit den
Menschen. - Lajisch (Dan) liegt im Quellgebiet des Jordan (vgl. V. 29).

[fn:4] [[file:Jos_19.org::v47][Jos 19,47]]

[fn:5] mit den Aramäern: Text korr. (vgl. die Anmerkung zu V. 7).

[fn:6] [[file:2.Kön_15.org::v29][2 Kön 15,29]]

[fn:7] des Mose: Text korr., vgl. G, Vg; H: Manasses, wohl
nachträgliche Korrektur.
