#+TITLE: Ri 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-01 Mi 10:22]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Ri 1.html


* Ri 1

Das Buch der Richter hat seinen Namen von den »Richtern«, die in der
Zeit nach der Landnahme Israels wichtige Leitungsaufgaben erfüllten und
einzelne Sippenverbände oder Stammesgruppen aus der Bedrängnis durch
Feinde retteten. Zu den Leitungsaufgaben gehörte vor allem die
Rechtsprechung (daher der Name »Richter«).\\
\\
Den Hauptteil des Buches machen die Erzählungen über die verschiedenen
Richtergestalten aus (3,7 - 16,31). Voraus geht eine Einleitung, die an
das Buch Josua anknüpft; sie bietet eine knappe Beschreibung der
Landnahme durch einzelne Stämme und leitet mit einer allgemeinen
Charakterisierung der Richterzeit zu den Richtererzählungen über (1,1 -
3,6). Auf den Hauptteil folgen zwei längere Anhänge, in denen die
Gründung des Heiligtums von Dan (Kap. 17 und 18) sowie die Schandtat und
Bestrafung der Benjaminiter von Gibea (Kap. 19 - 21) berichtet werden.\\
\\
Die Heldenerzählungen des Hauptteils waren ursprünglich wohl bei
einzelnen Stämmen beheimatet. Auffällig breit werden die wunderbare
Geburt Simsons und dessen außergewöhnliche Taten geschildert (Kap. 13 -
16). Auch die Geschichte Gideons nimmt einen breiten Raum ein (Kap. 6 -
8); seine Berufung wird mit der Gründung eines Heiligtums verbunden
(Kap. 6). Im Debora-Lied (Kap. 5) wird der Sieg über Sisera und sein
Heer besungen; es gehört zu den ältesten Texten des Alten Testaments.
Die Fabel in 9,8-15 ist ein politischer Text, der unterstreicht, dass
man das Königtum in Israel nicht ohne den Willen Gottes erlangen kann.\\
\\
Die Zeit zwischen Josua und Samuel war nach dem Bild, das das
Richterbuch zeichnet, eine Periode, in der sich Israel im Land Kanaan,
zumeist gegen Feinde von außen, behaupten musste. Das gelang dem Volk
nicht aus eigener Kraft, wie es auch das verheißene Land nicht durch
eigene Anstrengung, sondern nur mit Gottes Hilfe erobert hatte. Das
Verhältnis Israels zu seinem Gott entschied auch darüber, ob Israel
ruhig in seinem Land wohnen konnte. Das war die Überzeugung der
Bearbeiter, die die einzelnen Erzählungen zu einem Gesamtbild der
Richterzeit zusammenstellten.\\
\\
Der Geschichtsverlauf wird nach folgenden Leitgedanken des
Deuteronomisten beurteilt: Jahwe allein verehren; auf seine Stimme
hören; seine Gebote befolgen; anderen Göttern nicht nachlaufen. So
kommen die Verfasser zu ihrer in der Konsequenz beeindruckenden Wertung
der Richterzeit (Kap. 2) und gewinnen ein Schema, das sie an diese Zeit
anlegen können: Abfall von Gott, Strafe, Hilferuf, Umkehr, Rettung,
Wohlergehen und Frieden, solange das Volk auf die Richter hört und Gott
die Treue hält (so erstmals 3,7-11). Das Richterbuch ist ein
eindrucksvolles Zeugnis für den Glauben an den Herrschaftsanspruch
Gottes gegenüber seinem Volk, aber auch an seine Treue und Fürsorge.\\
\\

<<verses>>

<<v1>>
* Die Charakterisierung der Richterzeit: 1,1 - 3,6

* Die Eroberung des Gebiets der Stämme Juda und Simeon: 1,1-21

1 Nach dem Tod Josuas befragten die Israeliten den Herrn: Wer von uns
soll zuerst gegen die Kanaaniter in den Kampf ziehen?

<<v2>>
2 Der Herr antwortete: Juda soll (zuerst) hinaufziehen; ich gebe das
Land in seine Gewalt.

<<v3>>
3 Da sagte Juda zu seinem Bruder Simeon: Zieh mit mir hinauf in das
Gebiet, das mir durch das Los zugefallen ist; wir wollen (zusammen)
gegen die Kanaaniter kämpfen. Dann werde auch ich mit dir in dein Gebiet
ziehen. Da ging Simeon mit ihm.

<<v4>>
4 Juda zog hinauf und der Herr gab die Kanaaniter und die Perisiter in
ihre Gewalt. Sie schlugen sie bei Besek - (ein Heer von) zehntausend
Mann. [fn:1]

<<v5>>
5 Sie stießen bei Besek auf Adoni-Besek, kämpften mit ihm und schlugen
die Kanaaniter und die Perisiter.

<<v6>>
6 Adoni-Besek floh, aber sie verfolgten ihn, ergriffen ihn und hackten
ihm die Daumen und die großen Zehen ab. [fn:2]

<<v7>>
7 Da sagte Adoni-Besek: Siebzig Könige mit abgehackten Daumen und
abgehackten großen Zehen haben unter meinem Tisch (den Abfall)
aufgelesen. Wie ich gehandelt habe, so vergilt mir Gott. Man brachte ihn
nach Jerusalem und dort starb er.

<<v8>>
8 Die Judäer kämpften auch gegen Jerusalem, nahmen es ein, schlugen die
Stadt mit scharfem Schwert und steckten sie in Brand.

<<v9>>
9 Danach zogen die Judäer weiter, um gegen die Kanaaniter zu kämpfen,
die im Gebirge, im Negeb und in der Schefela wohnten. [fn:3]

<<v10>>
10 Juda zog auch gegen die Kanaaniter, die in Hebron wohnten - Hebron
hieß früher Kirjat-Arba -, und sie schlugen Scheschai, Ahiman und
Talmai. [fn:4]

<<v11>>
11 Von dort zogen sie weiter gegen die Einwohner von Debir. Debir hieß
früher Kirjat-Sefer.

<<v12>>
12 Da sagte Kaleb: Wer Kirjat-Sefer schlägt und einnimmt, dem gebe ich
meine Tochter Achsa zur Frau.

<<v13>>
13 Otniël, der Sohn des Kenas, des jüngeren Bruders Kalebs, nahm die
Stadt ein. Da gab ihm Kaleb seine Tochter Achsa zur Frau. [fn:5]

<<v14>>
14 Als sie nun ankam, drängte er sie, von ihrem Vater ein Stück Land zu
verlangen. Da ließ sie sich vom Esel herabgleiten und Kaleb fragte sie:
Was hast du? [fn:6]

<<v15>>
15 Sie antwortete: Gib mir ein Geschenk als Zeichen des Segens! Wenn du
mich schon ins Trockenland schickst, dann gib mir auch Wasserstellen! Da
gab Kaleb ihr die Obere und die Untere Quelle. [fn:7]

<<v16>>
16 Die Söhne des Keniters (Hobab), des Schwiegervaters des Mose, waren
mit den Judäern von der Palmenstadt zur Wüste Juda südlich von Arad
hinaufgezogen; nun zogen sie weiter und ließen sich bei den Amalekitern
nieder. [fn:8] [fn:9]

<<v17>>
17 Juda aber zog mit seinem Bruder Simeon weiter. Sie schlugen die
Kanaaniter, die in Zefat wohnten, weihten die Stadt dem Untergang und
nannten sie Horma (Untergangsweihe). [fn:10]

<<v18>>
18 Doch Gaza und sein Gebiet, Aschkelon und sein Gebiet, Ekron und sein
Gebiet konnte Juda nicht erobern. [fn:11]

<<v19>>
19 Der Herr war mit Juda, sodass es das Bergland in Besitz nehmen
konnte. Aber die Bewohner der Ebene konnten sie nicht vertreiben, weil
sie eiserne Kampfwagen hatten.

<<v20>>
20 Dem Kaleb gab man Hebron, wie Mose es angeordnet hatte; er vertrieb
von dort die drei Söhne Anaks. [fn:12]

<<v21>>
21 Die Benjaminiter konnten die Jebusiter, die in Jerusalem wohnten,
nicht vertreiben und so blieben die Jebusiter bei den Benjaminitern in
Jerusalem wohnen bis auf den heutigen Tag. [fn:13] [fn:14]\\
\\

<<v22>>
* Die Eroberung des Gebiets der Nachkommen Josefs: 1,22-36

22 Auch die Nachkommen Josefs zogen hinauf, und zwar nach Bet-El. Und
der Herr war mit ihnen. [fn:15]

<<v23>>
23 Die Nachkommen Josefs ließen Bet-El beobachten. Die Stadt hieß früher
Lus.

<<v24>>
24 Als die Wachen einen Mann aus der Stadt herauskommen sahen, sagten
sie zu ihm: Zeig uns, wo man in die Stadt eindringen kann, dann werden
wir dir unser Wohlwollen beweisen.

<<v25>>
25 Er zeigte ihnen eine Stelle, wo sie in die Stadt eindringen konnten,
und sie schlugen die Stadt mit scharfem Schwert. Den Mann aber und seine
ganze Sippe ließen sie gehen.

<<v26>>
26 Der Mann ging in das Land der Hetiter, erbaute eine Stadt und nannte
sie Lus. Das ist ihr Name bis auf den heutigen Tag.

<<v27>>
27 Manasse konnte (die Einwohner von) Bet-Schean und seinen
Tochterstädten sowie von Taanach und seinen Tochterstädten, die
Einwohner von Dor und seinen Tochterstädten, die Einwohner von Jibleam
und seinen Tochterstädten und die Einwohner von Megiddo und seinen
Tochterstädten nicht vertreiben. So gelang es den Kanaanitern, in dieser
Gegend zu verbleiben. [fn:16]

<<v28>>
28 Als die Israeliten stark geworden waren, zwangen sie die Kanaaniter
zur Fron, aber vertreiben konnten sie sie nicht.

<<v29>>
29 Efraim konnte die Kanaaniter nicht vertreiben, die in Geser wohnten.
Darum blieben die Kanaaniter mitten unter ihnen in Geser wohnen. [fn:17]

<<v30>>
30 Sebulon konnte die Einwohner von Kitron und die Einwohner von Nahalol
nicht vertreiben. Darum blieben die Kanaaniter mitten unter ihnen
wohnen, aber sie wurden Fronarbeiter.

<<v31>>
31 Ascher konnte die Einwohner von Akko und die Einwohner von Sidon
nicht vertreiben, auch nicht (die Einwohner) von Mahaleb, Achsib, Helba,
Afek und Roheb. [fn:18]

<<v32>>
32 Darum leben die Ascheriter mitten unter den Kanaanitern, die in der
Gegend wohnen blieben, weil man sie nicht vertreiben konnte.

<<v33>>
33 Naftali konnte die Einwohner von Bet-Schemesch und die Einwohner von
Bet-Anat nicht vertreiben und wohnt deshalb mitten unter den
Kanaanitern, die im Land verblieben sind. Die Einwohner von
Bet-Schemesch und Bet-Anat aber wurden Fronarbeiter.

<<v34>>
34 Die Amoriter drängten die Daniter ins Bergland ab und ließen sie
nicht in die Ebene herabkommen. [fn:19]

<<v35>>
35 Es gelang den Amoritern, in Har-Heres, Ajalon und Schaalbim zu
bleiben; als aber das Haus Josef ihnen überlegen war, wurden sie
Fronarbeiter.

<<v36>>
36 Das Gebiet der Amoriter reicht von der Skorpionensteige bis nach Sela
und darüber hinaus.\\
\\

* Footnotes

[fn:1] 4f: Besek liegt nördlich von Samaria. Anscheinend wird
Adoni-Besek mit Adoni-Zedek von Jerusalem in Verbindung gebracht (vgl. [[file:Jos_10.org::v1][Jos 10]]).

[fn:2] 6f: Die grausame Sitte soll den Feind kampfunfähig
machen.

[fn:3] [[file:Jos_10.org::v40][Jos 10,40]]; [[file:Jos_11.org::v16][11,16-20]]

[fn:4] (10-15) [[file:Jos_15.org::v13][Jos 15,13-19]]

[fn:5] [[file:Ri_3.org::v9][3,9]]

[fn:6] drängte er sie: Text korr. nach G (vgl. [[file:Jos_15.org::v18][Jos 15,18]]).

[fn:7] ein Geschenk als Zeichen des Segens, wörtlich: einen
Segen (vgl. [[file:Jos_15.org::v19][Jos 15,19]]).

[fn:8] [[file:Ri_4.org::v11][4,11]]; [[file:1.Sam_15.org::v6][1 Sam 15,6]]

[fn:9] nun zogen sie weiter und ließen sich . . . nieder: Text
korr. vgl. G; H: Er ging hin und wohnte beim Volk.

[fn:10] [[file:Dtn_20.org::v13][Dtn 20,13-17]]

[fn:11] nicht: Text korr. nach G und V. 19.

[fn:12] [[file:Jos_14.org::v6][Jos 14,6-15]]; [[file:Jos_11.org::v21][Jos 11,21]]

[fn:13] [[file:Jos_15.org::v63][Jos 15,63]]

[fn:14] Jerusalem lag zwischen dem Gebiet Judas und dem
Benjamins (vgl. [[file:Jos_18.org::v16][Jos 18,16]]).

[fn:15] die Nachkommen: so G; H: das Haus.

[fn:16] [[file:Jos_17.org::v11][Jos 17,11-13]]

[fn:17] [[file:Jos_16.org::v10][Jos 16,10]]

[fn:18] Mahaleb: Text korr. (vgl. [[file:Jos_19.org::v29][Jos 19,29]]).

[fn:19] [[file:Ri_18.org::v1][18,1]]
