#+TITLE: Ri 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-03 Fr 22:23]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ri 7.html


<<verses>>

<<v1>>
* Der Kampf gegen die Midianiter: 7,1 - 8,3

1 Am frühen Morgen brach Jerubbaal - das ist Gideon - mit allen Leuten,
die er bei sich hatte, auf und sie errichteten bei der Harod-Quelle ihr
Lager; das Lager Midians war nördlich davon beim Hügel More in der
Ebene. [fn:1] [fn:2]

<<v2>>
2 Der Herr sagte zu Gideon: Die Leute, die du bei dir hast, sind zu
zahlreich, als dass ich Midian in deine Gewalt geben könnte. Sonst
könnte sich Israel mir gegenüber rühmen und sagen: Meine eigene Hand hat
mich gerettet.

<<v3>>
3 Ruf daher so laut, dass die Leute es hören: Wer sich fürchtet und
Angst hat, soll umkehren. Gideon musterte sie und darauf kehrten von den
Leuten zweiundzwanzigtausend um, während zehntausend bei ihm blieben. [fn:3] [fn:4]

<<v4>>
4 Doch der Herr sagte zu Gideon: Die Leute sind immer noch zu zahlreich.
Führ sie hinab ans Wasser; dort will ich sie für dich mustern. Von wem
ich sagen werde: Er soll mit dir gehen!, der soll mitgehen, und jeder,
von dem ich zu dir sagen werde: Dieser soll nicht mit dir gehen!, der
soll nicht mitgehen.

<<v5>>
5 Gideon führte die Leute zum Wasser hinab und der Herr sagte zu ihm:
Stell alle, die das Wasser mit der Zunge auflecken, wie es ein Hund tut,
auf einen besonderen Platz, und ebenso alle, die sich zum Trinken
hinknien.

<<v6>>
6 Die Zahl derer, die das Wasser aufleckten, betrug dreihundert Mann.
Alle übrigen Leute aber knieten sich hin, um das Wasser zu trinken,
indem sie es mit der Hand zum Mund führten. [fn:5]

<<v7>>
7 Der Herr sagte zu Gideon: Durch die dreihundert Mann, die (das Wasser)
aufgeleckt haben, will ich euch retten; ich werde Midian in deine Gewalt
geben. Alle übrigen Leute sollen nach Hause gehen.

<<v8>>
8 Gideon entließ also alle Israeliten, jeden zu seinem Zelt, und sie
nahmen die Verpflegung der Leute und ihre Widderhörner mit. Nur die
dreihundert Mann behielt er bei sich. Das Lager Midians lag unterhalb
von ihm in der Ebene. [fn:6]

<<v9>>
9 In jener Nacht geschah es, dass Jahwe zu ihm sagte: Steh auf, geh zum
Lager hinab; denn ich habe es in deine Gewalt gegeben.

<<v10>>
10 Wenn du dich aber davor fürchtest hinabzusteigen, dann geh (zuerst
allein) mit deinem Diener Pura ins Lager hinab

<<v11>>
11 und höre, was man dort redet. Dann wirst du die Kraft bekommen, zum
Lager hinabzuziehen. Gideon ging also mit seinem Diener Pura bis
unmittelbar an die Krieger im Lager heran.

<<v12>>
12 Midian und Amalek und die Leute des Ostens waren in die Ebene
eingefallen, zahlreich wie die Heuschrecken, und ihre Kamele waren
zahllos wie der Sand am Ufer des Meeres.

<<v13>>
13 Als Gideon ankam, erzählte gerade einer dem andern einen Traum. Er
sagte: Hör zu, ich hatte einen Traum: Ich sah, wie ein Laib Gerstenbrot
ins Lager Midians rollte. Er gelangte bis zum Zelt und stieß dagegen,
sodass es umfiel und umgestülpt dalag. Dann brach das Zelt zusammen.

<<v14>>
14 Der andere antwortete: Das bedeutet nichts anderes als das Schwert
des Israeliten Gideon, des Sohnes des Joasch. Gott hat Midian und das
ganze Lager in seine Gewalt gegeben.

<<v15>>
15 Als Gideon die Erzählung von dem Traum und seine Deutung hörte, warf
er sich nieder und betete. Dann kehrte er ins Lager Israels zurück und
rief: Auf! Der Herr hat das Lager Midians in eure Gewalt gegeben.

<<v16>>
16 Gideon teilte die dreihundert Mann in drei Abteilungen und gab allen
Männern Widderhörner und leere Krüge in die Hand; in den Krügen waren
Fackeln.

<<v17>>
17 Er sagte zu ihnen: Seht auf mich und macht alles ebenso wie ich!
Passt auf: Ich gehe nun an den Rand des Lagers (der Midianiter) und das,
was ich mache, müsst auch ihr machen.

<<v18>>
18 Wenn ich und alle, die bei mir sind, das Widderhorn blasen, dann
müsst auch ihr rings um das ganze Lager eure Hörner blasen und rufen:
Für den Herrn und Gideon!

<<v19>>
19 Gideon und die hundert Mann, die bei ihm waren, gelangten zu Beginn
der mittleren Nachtwache an den Rand des Lagers (der Midianiter); man
hatte gerade die Wachen aufgestellt. Sie bliesen das Widderhorn und
zerschlugen die Krüge, die sie in der Hand hatten.

<<v20>>
20 Nun bliesen auch die beiden anderen Abteilungen ihre Hörner,
zerschlugen die Krüge, ergriffen mit der linken Hand die Fackeln,
während sie in der rechten Hand die Widderhörner hielten, um zu blasen,
und schrien: Das Schwert für den Herrn und Gideon! [fn:7]

<<v21>>
21 Dabei blieben sie rings um das Lager stehen, jeder an dem Platz, wo
er gerade war. Im Lager liefen alle durcheinander, schrien und flohen.

<<v22>>
22 Als die dreihundert Männer ihre Hörner bliesen, richtete der Herr im
ganzen Lager das Schwert des einen gegen den andern. Alle im Lager
flohen bis nach Bet-Schitta, Zereda, Sefat-Abel-Mehola und Tabbat.

<<v23>>
23 Nun wurden die Israeliten aus Naftali, Ascher und ganz Manasse
aufgeboten, um die Midianiter zu verfolgen.

<<v24>>
24 Außerdem schickte Gideon Boten im ganzen Bergland von Efraim umher
und ließ sagen: Zieht hinab gegen Midian und nehmt ihm die Wasserstellen
weg bis nach Bet-Bara und (besetzt) den Jordanübergang! So wurden alle
Männer Efraims zusammengerufen und sie besetzten die Wasserstellen bis
Bet-Bara und den Jordanübergang.

<<v25>>
25 Sie nahmen auch die zwei Midianiterfürsten Oreb (Rabe) und Seeb
(Wolf) gefangen. Oreb töteten sie am Rabenfelsen und Seeb töteten sie an
der Wolfskelter; dann setzten sie die Verfolgung Midians fort. Die Köpfe
Orebs und Seebs aber brachten sie zu Gideon über den Jordan. [fn:8] [fn:9]

* Footnotes

[fn:1] [[file:Ri_6.org::v32][6,32]]

[fn:2] Die Harod-Quelle liegt in der Jesreelebene am Fuß der
Gilboa-Berge.

[fn:3] [[file:Dtn_20.org::v8][Dtn 20,8]]

[fn:4] musterte sie: Text korr. (vgl. V. 4).

[fn:5] Text durch Umstellung korr., vgl. G.

[fn:6] Text und Übersetzung unsicher.

[fn:7] auch die beiden anderen, wörtlich: die drei (dabei ist
die Abteilung von V. 19 einbezogen).

[fn:8] [[file:Ps_83.org::v12][Ps 83,12]]

[fn:9] Der Vers erklärt, warum die beiden Orte so genannt
werden.
