#+TITLE: Ri 8 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-03 Fr 22:48]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Ri 8.html


* Ri 8

<<verses>>

<<v1>>
1 Die Efraimiter aber sagten zu Gideon: Was hast du uns da angetan, dass
du uns nicht hast rufen lassen, als du ausgezogen bist, um gegen Midian
zu kämpfen? Und sie stritten heftig mit ihm. [fn:1]

<<v2>>
2 Er antwortete ihnen: Was habe ich schon getan im Vergleich zu euch?
Ist nicht die Nachlese Efraims besser als die Weinlese Abiësers? [fn:2]

<<v3>>
3 In eure Gewalt hat Gott Oreb und Seeb, die Fürsten Midians, gegeben.
Was vermochte ich zu tun im Vergleich zu euch? Als er das sagte, legte
sich ihr Zorn gegen ihn.\\
\\

<<v4>>
* Der Feldzug im Ostjordanland: 8,4-21

4 Als Gideon an den Jordan gekommen und mit den dreihundert Männern, die
bei ihm waren, hinübergegangen war, erschöpft von der Verfolgung,

<<v5>>
5 sagte er zu den Einwohnern von Sukkot: Gebt doch den Leuten, die mir
folgen, einige Laibe Brot, denn sie sind erschöpft. Ich bin dabei,
Sebach und Zalmunna, die Könige von Midian, zu verfolgen.

<<v6>>
6 Doch die Oberen von Sukkot entgegneten: Hast du denn Sebach und
Zalmunna schon in deiner Gewalt? Warum sollten wir deinem Heer Brot
geben? [fn:3]

<<v7>>
7 Darauf sagte Gideon: Wahrhaftig, wenn der Herr Sebach und Zalmunna in
meine Gewalt gegeben hat, dann dresche ich euch den Leib mit
Wüstendornen und Stechdisteln.

<<v8>>
8 Dann zog er von Sukkot hinauf nach Penuël und sprach die Leute dort in
derselben Weise an, aber die Einwohner von Penuël antworteten ihm
genauso, wie die Männer von Sukkot geantwortet hatten.

<<v9>>
9 Da drohte er auch den Männern von Penuël: Wenn ich heil zurückkehre,
werde ich die Burg hier niederreißen.

<<v10>>
10 Sebach und Zalmunna befanden sich mit ihrem Heerlager in Karkor; es
waren etwa fünfzehntausend Mann; das war alles, was von dem ganzen
Heerlager der Leute aus dem Osten übrig geblieben war.
Hundertzwanzigtausend mit dem Schwert bewaffnete Männer waren gefallen.

<<v11>>
11 Gideon zog auf dem Beduinenweg östlich von Nobach und Jogboha hinauf
und schlug das (feindliche) Heer, das sich in Sicherheit wähnte.

<<v12>>
12 Sebach und Zalmunna, die beiden Könige von Midian, flohen, aber er
verfolgte sie, nahm sie gefangen und scheuchte das ganze Heerlager
auseinander.

<<v13>>
13 Als Gideon, der Sohn des Joasch, aus dem Kampf von Maale-Heres
zurückkehrte,

<<v14>>
14 nahm er einen jungen Mann fest, der zu den Leuten von Sukkot gehörte.
Er fragte ihn aus und dieser musste ihm die Oberen und Ältesten von
Sukkot aufschreiben, siebenundsiebzig Männer.

<<v15>>
15 Als er nun zu den Einwohnern von Sukkot kam, sagte er: Hier sind
Sebach und Zalmunna, deretwegen ihr mich verhöhnt habt mit den Worten:
Ist denn Sebach und Zalmunna schon in deiner Hand? Warum sollten wir
deinen erschöpften Männern Brot geben?

<<v16>>
16 Dann ergriff er die Ältesten der Stadt, die Männer von Sukkot, und
drosch sie mit den Wüstendornen und mit den Stechdisteln.

<<v17>>
17 Die Burg von Penuël aber riss er nieder und tötete die Männer in der
Stadt.

<<v18>>
18 Dann sagte er zu Sebach und Zalmunna: Wie sahen die Männer aus, die
ihr in Tabor getötet habt? Sie antworteten: Sie waren wie du; jeder sah
aus wie ein Königssohn.

<<v19>>
19 Er entgegnete: Es waren meine Brüder, die Söhne meiner Mutter. So
wahr der Herr lebt: Hättet ihr sie am Leben gelassen, würde ich euch
nicht töten.

<<v20>>
20 Und er sagte zu Jeter, seinem Erstgeborenen: Auf, töte sie! Aber der
Junge zog sein Schwert nicht; er hatte Angst, weil er noch so jung war.

<<v21>>
21 Da sagten Sebach und Zalmunna: Steh selber auf und schlag uns nieder!
Denn wie der Mann, so seine Kraft. Da stand Gideon auf und tötete Sebach
und Zalmunna. Dann nahm er ihren Kamelen die kleinen Monde ab, die sie
am Hals trugen. [fn:4]\\
\\

<<v22>>
* Die Ablehnung der Königswürde: 8,22-35

22 Die Israeliten sagten zu Gideon: Werde unser Herrscher, du und auch
dein Sohn und dein Enkel; denn du hast uns aus der Gewalt Midians
befreit.

<<v23>>
23 Aber Gideon antwortete ihnen: Ich will nicht über euch herrschen, und
auch mein Sohn soll nicht über euch herrschen; der Herr soll über euch
herrschen.

<<v24>>
24 Weiter sagte Gideon zu ihnen: Ich möchte euch um etwas bitten: Jeder
von euch gebe mir einen Ring aus seiner Beute. Die Feinde hatten nämlich
goldene Ringe, denn sie waren Ismaeliter. [fn:5]

<<v25>>
25 Sie antworteten: Wir geben sie dir gern. Sie breiteten einen Mantel
aus und jeder legte einen Ring aus seiner Beute darauf.

<<v26>>
26 Das Gewicht der goldenen Ringe, um die er gebeten hatte, betrug
tausendsiebenhundert Goldschekel, ohne die kleinen Monde und die
Ohrgehänge und die Purpurkleider, die die Könige von Midian getragen
hatten, und ohne die Halsketten ihrer Kamele.

<<v27>>
27 Gideon machte daraus ein Efod und stellte es in seiner Stadt Ofra
auf. Und ganz Israel trieb dort damit Abgötterei. Das brachte Gideon und
sein Haus zu Fall. [fn:6]

<<v28>>
28 Midian aber war von den Israeliten gedemütigt, sodass es sein Haupt
nicht mehr erheben konnte. Das Land hatte dann vierzig Jahre lang Ruhe,
solange Gideon lebte.

<<v29>>
29 Jerubbaal, der Sohn des Joasch, ging heim und blieb bei seiner
Familie.

<<v30>>
30 Gideon hatte siebzig leibliche Söhne, denn er hatte viele Frauen.

<<v31>>
31 Auch seine Nebenfrau, die in Sichem war, gebar ihm einen Sohn; dem
gab er den Namen Abimelech. [fn:7]

<<v32>>
32 Gideon, der Sohn des Joasch, starb in hohem Alter und wurde im Grab
seines Vaters Joasch in Ofra, der Stadt der Abiësriter, begraben.

<<v33>>
33 Als Gideon tot war, trieben die Israeliten wieder Abgötterei mit den
Baalen und machten den «Baal des Bundes» zu ihrem Gott. [fn:8]

<<v34>>
34 Die Israeliten dachten nicht mehr an den Herrn, ihren Gott, der sie
aus der Gewalt all ihrer Feinde ringsum befreit hatte.

<<v35>>
35 Auch dem Haus Jerubbaal-Gideon erwiesen sie kein Wohlwollen, wie es
all dem Guten entsprochen hätte, das es für Israel getan hatte.\\
\\

* Footnotes

[fn:1] [[file:Ri_12.org::v1][12,1]]

[fn:2] Gideon verwendet ein Wortspiel.

[fn:3] [[v6][6]].[[v15][15]]: Wörtlich: Hast du denn die Faust Sebachs und
Zalmunnas schon in deiner Hand? - Sukkot und Penuël liegen am Jabbok.

[fn:4] Gideon vollstreckt die Blutrache.

[fn:5] Die Ismaeliter gelten als Händler (vgl. [[file:Gen_37.org::v24][Gen 37,24-27]]).

[fn:6] Efod ist hier ein Kultgegenstand, vielleicht ein
Gottesbild.

[fn:7] [[file:Ri_9.org::v1][9,1]]

[fn:8] Der Baal des Bundes ist der Stadtgott von Sichem (vgl. [[file:Ri_9.org::v4][9,4]]).
