#+TITLE: Rut 2 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-06 Mo 09:15]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Rut 2.html


<<verses>>

<<v1>>
* Rut auf dem Acker des Boas: 2,1-23

1 Noomi hatte einen Verwandten von ihrem Mann her, einen Grundbesitzer;
er war aus dem Geschlecht Elimelechs und hieß Boas.

<<v2>>
2 Eines Tages sagte die Moabiterin Rut zu Noomi: Ich möchte aufs Feld
gehen und Ähren lesen, wo es mir jemand erlaubt. Sie antwortete ihr:
Geh, Tochter!

<<v3>>
3 Rut ging hin und las auf dem Feld hinter den Schnittern her. Dabei war
sie auf ein Grundstück des Boas aus dem Geschlecht Elimelechs geraten.

<<v4>>
4 Und nun kam Boas von Betlehem dazu. Er sagte zu den Schnittern: Der
Herr sei mit euch! Sie antworteten ihm: Der Herr segne dich.

<<v5>>
5 Boas fragte seinen Knecht, der die Schnitter beaufsichtigte: Wem
gehört dieses Mädchen da?

<<v6>>
6 Der Knecht antwortete: Es ist eine junge Moabiterin, die mit Noomi aus
dem Grünland Moabs gekommen ist.

<<v7>>
7 Sie hat gesagt: Ich möchte gern Ähren lesen und bei den Garben hinter
den Schnittern her sammeln. So kam sie zu uns und hielt aus vom Morgen
bis jetzt und gönnte sich kaum Ruhe.

<<v8>>
8 Boas sagte zu Rut: Höre wohl, meine Tochter, geh auf kein anderes
Feld, um zu lesen; entfern dich nicht von hier, sondern halte dich an
meine Mägde;

<<v9>>
9 behalte das Feld im Auge, wo sie ernten, und geh hinter ihnen her! Ich
werde meinen Knechten befehlen, dich nicht anzurühren. Hast du Durst, so
darfst du zu den Gefäßen gehen und von dem trinken, was die Knechte
schöpfen.

<<v10>>
10 Sie sank vor ihm nieder, beugte sich zur Erde und sagte: Wie habe ich
es verdient, dass du mich so achtest, da ich doch eine Fremde bin?

<<v11>>
11 Boas antwortete ihr: Mir wurde alles berichtet, was du nach dem Tod
deines Mannes für deine Schwiegermutter getan hast, wie du deinen Vater
und deine Mutter, dein Land und deine Verwandtschaft verlassen hast und
zu einem Volk gegangen bist, das dir zuvor unbekannt war.

<<v12>>
12 Der Herr, der Gott Israels, zu dem du gekommen bist, um dich unter
seinen Flügeln zu bergen, möge dir dein Tun vergelten und dich reich
belohnen.

<<v13>>
13 Sie sagte: Du bist sehr gütig zu mir, Herr. Du hast mir Mut gemacht
und so freundlich zu deiner Magd gesprochen und ich bin nicht einmal
eine deiner Mägde.

<<v14>>
14 Zur Essenszeit sagte Boas zu ihr: Komm und iss von dem Brot, tauch
deinen Bissen in die Würztunke! Sie setzte sich neben die Schnitter. Er
reichte ihr geröstete Körner und sie aß sich satt und behielt noch
übrig.

<<v15>>
15 Als sie wieder aufstand zum Ährenlesen, befahl Boas seinen Knechten:
Auch wenn sie zwischen den Garben liest, dürft ihr sie nicht schelten.

<<v16>>
16 Ihr sollt sogar für sie etwas aus den Bündeln herausziehen und liegen
lassen; sie mag es auflesen und ihr dürft sie nicht schelten.

<<v17>>
17 So sammelte sie auf dem Feld bis zum Abend. Als sie ausklopfte, was
sie aufgelesen hatte, war es etwa ein Efa Gerste.

<<v18>>
18 Sie hob es auf, ging in die Stadt und zeigte ihrer Schwiegermutter,
was sie aufgelesen hatte. Dann packte sie aus, was sie von ihrer
Mahlzeit übrig behalten hatte, und gab es ihr.

<<v19>>
19 Ihre Schwiegermutter fragte: Wo hast du heute gelesen und gearbeitet?
Gesegnet sei, der auf dich Acht hatte. Sie berichtete ihrer
Schwiegermutter, bei wem sie gearbeitet hatte, und sagte: Der Mann, bei
dem ich heute gearbeitet habe, heißt Boas.

<<v20>>
20 Da sagte Noomi zu ihrer Schwiegertochter: Gesegnet sei er vom Herrn,
der seine Gunst den Lebenden und Toten nicht entzogen hat. Und sie
erzählte ihr: Der Mann ist mit uns verwandt, er ist einer unserer Löser. [fn:1]

<<v21>>
21 Die Moabiterin Rut sagte: Er hat noch zu mir gesagt: Halte dich an
meine Knechte, bis sie meine Ernte eingebracht haben.

<<v22>>
22 Gut, meine Tochter, sagte Noomi zu Rut, wenn du mit seinen Mägden
hinausgehst, dann kann man dich auf einem anderen Feld nicht belästigen.

<<v23>>
23 Rut hielt sich beim Ährenlesen an die Mägde des Boas, bis die
Gersten- und Weizenernte beendet war. Danach blieb sie bei ihrer
Schwiegermutter.\\
\\

* Footnotes

[fn:1] Zum «Löser» vgl. die Anmerkung zu [[file:Rut_1.org::v5][1,5f]] und zu [[file:Lev_25.org::v25][Lev 25,25]]. 
