#+TITLE: Rut 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-06 Mo 09:21]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Rut 4.html


<<verses>>

<<v1>>
* Die Verhandlung im Tor: 4,1-12

1 Indes war Boas zum Tor gegangen und hatte sich dort niedergelassen. Da
ging gerade der Löser vorüber, von dem Boas gesprochen hatte. Er sagte
zu ihm: Komm herüber und setz dich hierher! Der kam herüber und setzte
sich.

<<v2>>
2 Dann holte Boas zehn Männer von den Ältesten der Stadt und sagte:
Setzt euch hierher! Sie taten es.

<<v3>>
3 Darauf sagte er zu dem Löser: Das Grundstück, das unserem Verwandten
Elimelech gehört, will Noomi, die aus dem Grünland Moabs zurückgekehrt
ist, verkaufen. [fn:1]

<<v4>>
4 Ich dachte, ich will dich davon unterrichten und dir sagen: Erwirb es
in Gegenwart der hier Sitzenden und in Gegenwart der Ältesten meines
Volkes! Wenn du lösen willst, so löse! Willst du aber nicht lösen, so
sag es mir, damit ich es weiß; denn außer dir ist niemand zum Lösen da
und ich bin nach dir an der Reihe. Jener antwortete: Ich werde lösen.

<<v5>>
5 Boas fuhr fort: Wenn du den Acker aus der Hand der Noomi erwirbst,
dann erwirbst du zugleich auch die Moabiterin Rut, die Frau des
Verstorbenen, um den Namen des Toten auf seinem Erbe wieder erstehen zu
lassen. [fn:2]

<<v6>>
6 Der Löser sagte: Dann kann ich für mich nicht lösen, sonst schädige
ich mein eigenes Erbe. Übernimm du mein Löserecht; denn ich kann nicht
lösen. [fn:3]

<<v7>>
7 Früher bestand in Israel folgender Brauch: Um ein Löse- oder
Tauschgeschäft rechtskräftig zu machen, zog man den Schuh aus und gab
ihn seinem Partner. Das galt in Israel als Bestätigung. [fn:4]

<<v8>>
8 Der Löser sagte nun zu Boas: Erwirb es!, und er zog seinen Schuh aus.

<<v9>>
9 Boas sagte zu den Ältesten und zu allem Volk: Ihr seid heute Zeugen,
dass ich alles Eigentum Elimelechs sowie das Kiljons und Machlons aus
der Hand der Noomi erworben habe.

<<v10>>
10 Auch Rut, die Moabiterin, die Frau Machlons, habe ich mir zur Frau
erworben, um den Namen des Verstorbenen auf seinem Erbe wieder erstehen
zu lassen, damit sein Name unter seinen Verwandten und innerhalb der
Mauern seiner Stadt nicht erlischt. Ihr seid heute Zeugen. [fn:5]

<<v11>>
11 Da antwortete alles Volk im Tor samt den Ältesten: Wir sind Zeugen.
Der Herr mache die Frau, die in dein Haus kommt, wie Rahel und Lea, die
zwei, die das Haus Israel aufgebaut haben. Komm zu Reichtum in Efrata
und zu Ansehen in Betlehem! [fn:6]

<<v12>>
12 Dein Haus gleiche dem Haus des Perez, den Tamar dem Juda geboren hat,
durch die Nachkommenschaft, die der Herr dir aus dieser jungen Frau
geben möge. [fn:7]\\
\\

<<v13>>
* Das gesegnete Kind: 4,13-17

13 So nahm Boas Rut zur Frau und ging zu ihr. Der Herr ließ sie
schwanger werden und sie gebar einen Sohn.

<<v14>>
14 Da sagten die Frauen zu Noomi: Gepriesen sei der Herr, der es dir
heute nicht an einem Löser hat fehlen lassen. Sein Name soll in Israel
gerühmt werden.

<<v15>>
15 Du wirst jemand haben, der dein Herz erfreut und dich im Alter
versorgt; denn deine Schwiegertochter, die dich liebt, hat ihn geboren,
sie, die mehr wert ist als sieben Söhne.

<<v16>>
16 Noomi nahm das Kind, drückte es an ihre Brust und wurde seine
Wärterin.

<<v17>>
17 Die Nachbarinnen wollten ihm einen Namen geben und sagten: Der Noomi
ist ein Sohn geboren. Und sie gaben ihm den Namen Obed. Er ist der Vater
Isais, des Vaters Davids.\\
\\

<<v18>>
* Der Stammbaum: 4,18-22

18 Das ist die Geschlechterfolge nach Perez: Perez zeugte Hezron, [fn:8]

<<v19>>
19 Hezron zeugte Ram, Ram zeugte Amminadab,

<<v20>>
20 Amminadab zeugte Nachschon, Nachschon zeugte Salmon,

<<v21>>
21 Salmon zeugte Boas, Boas zeugte Obed,

<<v22>>
22 Obed zeugte Isai und Isai zeugte David.\\
\\

* Footnotes

[fn:1] [[file:Lev_25.org::v24][Lev 25,24f]]; [[file:Jer_32.org::v7][Jer 32,7f]]

[fn:2] Die Auslösung eines Grundstücks und die Leviratsehe
bilden für den nächsten Verwandten eine Einheit.

[fn:3] [[file:Dtn_25.org::v7][Dtn 25,7-10]]

[fn:4] In [[file:Dtn_25.org::v5][Dtn 25,5-9]] hat das Ausziehen der Schuhe eine andere
Bedeutung: Es soll denjenigen, der die Schwagerehe verweigert, der
Schande preisgeben. Hier aber bedeutet es lediglich den Verzicht
zugunsten eines anderen.

[fn:5] Nach [[file:Dtn_25.org::v5][Dtn 25,5f]] ist nur der Bruder, nicht ein weiterer
Verwandter zur Leviratsehe verpflichtet; nach Lev 25,25-27 muss aber
auch ein weiterer Verwandter, wenn kein näherer vorhanden ist, einen
Acker auslösen.

[fn:6] [[file:Gen_29.org::v1][Gen 29]] - [[file:Gen_31.org::v1][31]]

[fn:7] [[file:Gen_38.org::v29][Gen 38,29]]

[fn:8] 18-22: Der Stammbaum Davids findet sich auch in [[file:1.Chr_2.org::v5][1 Chr 2,5-15]]
und in [[file:~/RoamNotes/notes/Bibel/nt/Mt_1.org::v3][Mt 1,3-6]], wo Rut in V. 5 ausdrücklich als die Stammmutter
Davids genannt wird; in Mt 1 wird der Stammbaum dann bis auf Jesus
weitergeführt. So gilt in der christlichen Tradition Rut als Ahnfrau
Jesu.
