:PROPERTIES:
:ID:       439c39af-6b1b-4893-805e-e7dc4c4d185f
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Sacharja* -- [[file:Sach_1.html][1]]
... [[file:Sach_10.html][10]] [[file:Sach_11.html][11]] *12*
[[file:Sach_13.html][13]] [[file:Sach_14.html][14]]

--------------

* Sach 12
  :PROPERTIES:
  :CUSTOM_ID: sach-12
  :END:

<<verses>>

<<v1>>
**** Jerusalems Not und Errettung: 12,1 - 13,1
     :PROPERTIES:
     :CUSTOM_ID: jerusalems-not-und-errettung-121---131
     :END:
1 Ausspruch. Das Wort des Herrn über Israel. Der Spruch des Herrn, der
den Himmel ausgespannt, die Erde gegründet und den Geist im Innern des
Menschen geformt hat:

<<v2>>
2 Seht, ich mache Jerusalem zur Schale voll berauschendem Getränk für
alle Völker ringsum [und auch für Juda wird dies gelten bei der
Belagerung Jerusalems]. ^{[[#fn1][1]][[#fn2][2]]}

<<v3>>
3 An jenem Tag mache ich Jerusalem für alle Völker zum Stein, den man
hochstemmen will: Jeder, der ihn hebt, wird schwer zerschunden. Alle
Völker der Erde werden sich gegen Jerusalem verbünden. ^{[[#fn3][3]]}

<<v4>>
4 An jenem Tag - Spruch des Herrn - bringe ich alle Pferde in Verwirrung
und ihre Reiter zur Raserei. Über dem Haus Juda aber halte ich meine
Augen offen, während ich alle Pferde der Völker mit Blindheit schlage.
^{[[#fn4][4]]}

<<v5>>
5 Dann werden die Anführer Judas denken: Die Einwohner Jerusalems sind
stark durch den Herrn der Heere, ihren Gott.

<<v6>>
6 An jenem Tag mache ich Judas Anführer gleich einem Feuerbecken im
Holzhaufen und gleich brennenden Fackeln in den Garben. Sie fressen alle
Völker ringsum, rechts und links. Jerusalem aber wird weiterhin an
seinem Ort bleiben, in Jerusalem. ^{[[#fn5][5]]}

<<v7>>
7 Dann wird der Herr zuerst die Zelte Judas retten, damit der Stolz des
Hauses David und der Stolz der Einwohner Jerusalems nicht zu groß wird
gegenüber Juda.

<<v8>>
8 An jenem Tag beschirmt der Herr die Einwohner Jerusalems und dann wird
selbst der von ihnen, der strauchelt, wie David sein und das Haus David
an ihrer Spitze wie Gott, wie der Engel des Herrn.

<<v9>>
9 An jenem Tag werde ich danach trachten, alle Völker zu vernichten, die
gegen Jerusalem anrücken.

<<v10>>
10 Doch über das Haus David und über die Einwohner Jerusalems werde ich
den Geist des Mitleids und des Gebets ausgießen. Und sie werden auf den
blicken, den sie durchbohrt haben. Sie werden um ihn klagen, wie man um
den einzigen Sohn klagt; sie werden bitter um ihn weinen, wie man um den
Erstgeborenen weint. ^{[[#fn6][6]][[#fn7][7]]}

<<v11>>
11 An jenem Tag wird die Totenklage in Jerusalem so laut sein wie die
Klage um Hadad-Rimmon in der Ebene von Megiddo.
^{[[#fn8][8]][[#fn9][9]]}

<<v12>>
12 Das Land wird trauern, jede Sippe für sich: die Sippe des Hauses
David für sich und ihre Frauen für sich; die Sippe des Hauses Natan für
sich und ihre Frauen für sich;

<<v13>>
13 die Sippe des Hauses Levi für sich und ihre Frauen für sich; die
Sippe des Hauses Schimi für sich und ihre Frauen für sich;

<<v14>>
14 alle überlebenden Sippen, jede Sippe für sich und ihre Frauen für
sich.

^{[[#fnm1][1]]} ℘ Jes 51,17-23; Jer 25,15-26

^{[[#fnm2][2]]} 2b: H verderbt.

^{[[#fnm3][3]]} ℘ 14,2

^{[[#fnm4][4]]} ℘ Dtn 28,28

^{[[#fnm5][5]]} ℘ Weish 3,7; Obd 18

^{[[#fnm6][6]]} ℘ Ez 36,25-27; Joël 3,1; Joh 19,37; Offb 1,7

^{[[#fnm7][7]]} Und sie werden auf den blicken: nach Theodotion; H: und
sie werden auf mich blicken.

^{[[#fnm8][8]]} ℘ 2 Kön 5,18

^{[[#fnm9][9]]} Hadad, ein babylonischer Wetter- und Vegetationsgott,
der auch in Kanaan bekannt war, wird hier dem ihm wesensverwandten
aramäischen Gott Rimmon (vgl. 2 Kön 5,18) gleichgesetzt. Der mythisch
gedeutete Tod dieses Gottes zu Beginn der Trockenzeit im Sommer löste
alljährlich bei der heidnischen Bevölkerung von Megiddo eine große
Kultklage aus.
