#+TITLE: Sir 8 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-02 Do 08:16]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 8.html

* Sir 8

<<verses>>

<<v1>>
* Takt und Klugheit: 8,1-19

1 Streite nicht mit einem Mächtigen, /\\
 damit du ihm nicht in die Hände fällst. [fn:1]\\
\\

<<v2>>
2 Kämpf nicht gegen einen Reichen an, /\\
 sonst wirft er zu deinem Verderben sein Geld ins Gewicht. Schon viele
hat das Geld übermütig gemacht, /\\
 die Herzen der Großen hat es verführt.\\
\\

<<v3>>
3 Zank nicht mit einem Schwätzer /\\
 und leg nicht noch Holz auf das Feuer! [fn:2]\\
\\

<<v4>>
4 Pflege keinen Umgang mit einem Toren; /\\
 er wird die Weisen doch nur verachten. [fn:3]\\
\\

<<v5>>
5 Beschäm keinen, der sich von der Sünde bekehrt hat; /\\
 denk daran, dass wir alle schuldig sind.\\
\\

<<v6>>
6 Beschimpf keinen alten Mann, /\\
 denn auch mancher von uns wird ein Greis.\\
\\

<<v7>>
7 Freu dich nicht, wenn einer gestorben ist, /\\
 bedenk: Wir alle werden sterben.\\
\\

<<v8>>
8 Verwirf die Rede der Weisen nicht, /\\
 wirf dich vielmehr auf ihre Sinnsprüche! Denn dadurch wirst du Bildung
lernen, /\\
 um vor Fürsten stehen zu können. [fn:4]\\
\\

<<v9>>
9 Verachte nicht die Überlieferung der Alten, /\\
 die sie übernommen haben von ihren Vätern. Dann wirst du Einsicht
lernen, /\\
 um antworten zu können, sobald es notwendig ist.\\
\\

<<v10>>
10 Entzünde nicht die Glut des Frevlers, /\\
 damit du in der Flamme seines Feuers nicht verbrennst.\\
\\

<<v11>>
11 Weich einem Zuchtlosen nicht aus, /\\
 sonst lauert er heimlich auf deine Reden.\\
\\

<<v12>>
12 Borge keinem, der mächtiger ist als du. /\\
 Hast du geborgt, so hast du verloren. [fn:5]\\
\\

<<v13>>
13 Bürge für keinen, der höher steht als du. /\\
 Hast du gebürgt, so musst du zahlen. [fn:6]\\
\\

<<v14>>
14 Rechte nicht mit einem Richter; /\\
 denn er spricht Recht, wie es ihm beliebt.\\
\\

<<v15>>
15 Mit einem Gewalttätigen geh nicht des Wegs, /\\
 damit du nicht schweres Unheil über dich bringst. Denn er läuft
rücksichtslos weiter /\\
 und du gehst zugrunde durch seinen Unverstand.\\
\\

<<v16>>
16 Einem Jähzornigen biete nicht die Stirn /\\
 und reite mit ihm nicht durch die Wüste! Leicht wiegt in seinen Augen
die Blutschuld; /\\
 wenn kein Helfer da ist, bringt er dich um. [fn:7]\\
\\

<<v17>>
17 Führe kein vertrauliches Gespräch mit einem Toren; /\\
 er kann dein Geheimnis nicht für sich behalten.\\
\\

<<v18>>
18 Vor einem Fremden tu nichts, was geheim bleiben soll; /\\
 du weißt nicht, wie er sich am Ende verhält.\\
\\

<<v19>>
19 Öffne dein Herz nicht jedem Menschen /\\
 und wirf das Glück nicht von dir!\\
\\


* Footnotes

[fn:1] [[file:Koh_10.org::v20][Koh 10,20]]

[fn:2] [[file:Sir_28.org::v10][28,10]]

[fn:3] [[file:Sir_9.org::v15][9,15f]]; [[file:Spr_23.org::v9][Spr 23,9]]

[fn:4] 8ab: Auch in H liegt ein Wortspiel vor.

[fn:5] [[file:Sir_29.org::v1][29,1-20]]

[fn:6] [[file:Spr_6.org::v1][Spr 6,1-5]]

[fn:7] [[file:Sir_28.org::v8][28,8]]; [[file:Spr_22.org::v24][Spr 22,24]]
