#+TITLE: Sir 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-02 Do 08:00]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 7.html


* Sir 7

<<verses>>

<<v1>>
* Gefahren für den Weisen: 7,1-17

1 Tu nichts Böses, so trifft dich nichts Böses. /\\
\\

<<v2>>
2 Bleib der Sünde fern, so meidet sie dich.\\
\\

<<v3>>
3 Säe nicht in Furchen des Unrechts, /\\
 damit du es nicht siebenfach erntest. [fn:1]\\
\\

<<v4>>
4 Begehr von Gott kein Herrscheramt /\\
 und vom König keinen Ehrenplatz!\\
\\

<<v5>>
5 Halte dich nicht für gerecht vor Gott, /\\
 nicht für klug vor dem König!\\
\\

<<v6>>
6 Begehr nicht, Herrscher zu werden, /\\
 wenn dir die Kraft fehlt, dem Übermut zu steuern; du würdest sonst den
Vornehmen fürchten /\\
 und deine Ehre beflecken.\\
\\

<<v7>>
7 Setz dich nicht ins Unrecht bei der Versammlung am Tor, /\\
 bring dich nicht selbst zu Fall vor der Gemeinde! [fn:2]\\
\\

<<v8>>
8 Sinne nicht darauf, die Sünde zu wiederholen; /\\
 schon bei einer bleibst du nicht straflos. [fn:3]\\
\\

<<v9>>
9 Sag nicht: Auf die Menge meiner Gaben wird Gott sehen, /\\
 und wenn ich dem Höchsten opfere, nimmt er es an.\\
\\

<<v10>>
10 Sei nicht kleinmütig beim Gebet /\\
 und nicht säumig beim Wohltun!\\
\\

<<v11>>
11 Blick nicht geringschätzig auf einen Verbitterten; /\\
 bedenk, dass einer da ist, der erhöht und erniedrigt.\\
\\

<<v12>>
12 Sinne nicht auf Unrecht gegen deinen Bruder, /\\
 auch nicht gegen den Freund und Gefährten.\\
\\

<<v13>>
13 Jede Lüge missfalle dir; /\\
 denn sie hat nichts Gutes zu erhoffen.\\
\\

<<v14>>
14 Rede nicht heimlich in der Versammlung der Fürsten /\\
 und wiederhol nicht die Worte beim Gebet! [fn:4]\\
\\

<<v15>>
15 Sei nicht leichtfertig bei der schweren Arbeit auf dem Acker, /\\
 denn von Gott ist sie zugewiesen. [fn:5]\\
\\

<<v16>>
16 Überschätz dich nicht vor dem Volk; /\\
 bedenk, dass der Zorn nicht ausbleibt. [fn:6]\\
\\

<<v17>>
17 Demütige deinen Stolz ganz tief, /\\
 denn was den Menschen erwartet, ist die Verwesung. [Sag nicht
vorschnell: Welch ein Widersinn! /\\
 Überlass es Gott und willige ein in seinen Weg!] [fn:7] [fn:8]\\
\\

<<v18>>
* Das rechte Verhalten im häuslichen Kreis: 7,18-28

18 Wechsle keinen Freund für Geld, /\\
 einen treuen Bruder nicht für Gold aus Ofir!\\
\\

<<v19>>
19 Verachte nicht eine kluge Frau; /\\
 liebenswürdige Güte ist mehr wert als Perlen.\\
\\

<<v20>>
20 Misshandle einen Sklaven nicht, der dir treu dient, /\\
 auch nicht einen Tagelöhner, der sich willig einsetzt.\\
\\

<<v21>>
21 Einen klugen Sklaven liebe wie dich selbst, /\\
 verweigere ihm die Freilassung nicht!\\
\\

<<v22>>
22 Hast du Vieh, so schau darauf; /\\
 ist es brauchbar, so behalt es!\\
\\

<<v23>>
23 Hast du Söhne, nimm sie in Zucht /\\
 und gib ihnen Frauen in jungen Jahren! [fn:9]\\
\\

<<v24>>
24 Hast du Töchter, so behüte ihren Leib; /\\
 zeig dich ihnen nicht allzu freundlich!\\
\\

<<v25>>
25 Bring die Tochter aus dem Haus, dann zieht die Sorge aus; /\\
 doch verheirate sie nur mit einem verständigen Mann!\\
\\

<<v26>>
26 Hast du eine Frau, so verstoße sie nicht /\\
 und schenk dein Vertrauen keiner Geschiedenen! [fn:10]\\
\\

<<v27>>
27 Ehre deinen Vater von ganzem Herzen, /\\
 vergiss niemals die Schmerzen deiner Mutter! [fn:11]\\
\\

<<v28>>
28 Denk daran, dass sie dir das Leben gaben. /\\
 Wie kannst du ihnen vergelten, was sie für dich taten?\\
\\

<<v29>>
* Die Erfüllung heiliger Pflichten: 7,29-36

29 Fürchte Gott von ganzem Herzen, /\\
 seine Priester halt in Ehren!\\
\\

<<v30>>
30 Liebe deinen Schöpfer mit aller Kraft /\\
 und lass seine Diener nie im Stich!\\
\\

<<v31>>
31 Ehre Gott und achte den Priester, /\\
 entrichte ihm den Anteil, wie es dir geboten ist: den Speiseanteil vom
Schuldopfer und die freiwillige Abgabe, /\\
 die gesetzlichen Schlachtopfer und die heilige Abgabe.\\
\\

<<v32>>
32 Streck deine Hand auch dem Armen entgegen, /\\
 damit dein Segen vollkommen sei.\\
\\

<<v33>>
33 Schenk jedem Lebenden deine Gaben /\\
 und auch dem Toten versag deine Liebe nicht!\\
\\

<<v34>>
34 Entzieh dich nicht den Weinenden, /\\
 vielmehr trauere mit den Trauernden!\\
\\

<<v35>>
35 Säume nicht, den Kranken zu besuchen, /\\
 dann wirst du von ihm geliebt.\\
\\

<<v36>>
36 Bei allem, was du tust, denk an das Ende, /\\
 so wirst du niemals sündigen.\\
\\


* Footnotes

[fn:1] [[file:Spr_22.org::v8][Spr 22,8]]; [[file:Ijob_4.org::v8][Ijob 4,8]]

[fn:2] Vor Parteilichkeit, besonders bei den Gerichtssitzungen am Tor der Stadt, wird im AT oft gewarnt (vgl. [[file:Lev_19.org::v15][Lev 19,15]]; [[file:Spr_17.org::v15][Spr 17,15]]; [[file:Spr_24.org::v23][24,23f]]; [[file:Jes_1.org::v17][Jes 1,17]].[[file:Jes_1.org::v23][23]]).

[fn:3] [[file:Sir_5.org::v5][5,5f]]

[fn:4] [[file:Sir_11.org::v8][11,8]]

[fn:5] Die Landwirtschaft ist dem Menschen von Gott aufgetragen (vgl. [[file:Gen_2.org::v15][Gen 2,15]]; [[file:Gen_3.org::v23][3,23]]; [[file:Jes_28.org::v24][Jes 28,24-26]]).

[fn:6] [[file:Spr_16.org::v18][Spr 16,18]]

[fn:7] [[file:Weish_15.org::v10][Weish 15,10]]

[fn:8] 17cd: Fehlt in G und S.

[fn:9] 23b: Im Orient verheiratet der Vater seine Söhne und Töchter.

[fn:10] Im AT waren Polygamie und Ehescheidung möglich (vgl. [[file:Sir_25.org::v14][25,14]]; [[file:Dtn_24.org::v1][Dtn 24,1]]; [[file:Spr_30.org::v23][Spr 30,23]]; [[file:~/Documents/notes/Bibel/nt/Mt_19.org::v7][Mt 19,7f]]; [[file:~/Documents/notes/Bibel/nt/Mk_10.org::v4][Mk 10,4f]]).

[fn:11] [[file:Sir_3.org::v1][3,1-16]]; (27-28) [[file:Tob_4.org::v3][Tob 4,3f]]
