#+TITLE: Sir 6 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-02 Do 07:52]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 6.html

* Sir 6

<<verses>>

<<v1>>
1 Schlimmen Ruf und Schande erntet die schmähsüchtige Frau, /\\
 ebenso schlecht ist der doppelzüngige Mann.\\
\\

<<v2>>
2 Verfall nicht der Macht deiner Gier; /\\
 sie wird wie ein Stier deine Kraft abweiden.\\
\\

<<v3>>
3 Dein Laub wird sie fressen, deine Früchte verderben /\\
 und dich zurücklassen wie einen dürren Baum.\\
\\

<<v4>>
4 Freche Gier richtet ihre Opfer zugrunde /\\
 und macht sie zum Gespött des Feindes.\\
\\

<<v5>>
* Die Freundschaft: 6,5-17

5 Sanfte Rede erwirbt viele Freunde, /\\
 freundliche Lippen sind willkommen. [fn:1]\\
\\

<<v6>>
6 Viele seien es, die dich grüßen, /\\
 dein Vertrauter aber sei nur einer aus tausend.\\
\\

<<v7>>
7 Willst du einen Freund gewinnen, /\\
 gewinne ihn durch Erprobung, /\\
 schenk ihm nicht zu schnell dein Vertrauen! [fn:2]\\
\\

<<v8>>
8 Mancher ist Freund je nach der Zeit, /\\
 am Tag der Not hält er nicht stand.\\
\\

<<v9>>
9 Mancher Freund wird zum Feind, /\\
 unter Schmähungen deckt er den Streit mit dir auf.\\
\\

<<v10>>
10 Mancher ist Freund als Gast am Tisch, /\\
 am Tag des Unheils ist er nicht zu finden. [fn:3]\\
\\

<<v11>>
11 In deinem Glück ist er eins mit dir, /\\
 in deinem Unglück trennt er sich von dir. [fn:4]\\
\\

<<v12>>
12 Trifft dich ein Unglück, wendet er sich gegen dich /\\
 und hält sich vor dir verborgen.\\
\\

<<v13>>
13 Von deinen Feinden halte dich fern, /\\
 vor deinen Freunden sei auf der Hut!\\
\\

<<v14>>
14 Ein treuer Freund ist wie ein festes Zelt; /\\
 wer einen solchen findet, hat einen Schatz gefunden.\\
\\

<<v15>>
15 Für einen treuen Freund gibt es keinen Preis, /\\
 nichts wiegt seinen Wert auf.\\
\\

<<v16>>
16 Das Leben ist geborgen bei einem treuen Freund, /\\
 ihn findet, wer Gott fürchtet. [fn:5]\\
\\

<<v17>>
17 Wer den Herrn fürchtet, hält rechte Freundschaft, /\\
 wie er selbst, so ist auch sein Freund.\\
\\

<<v18>>
* Der Weg zur Weisheit: 6,18-37

18 Mein Sohn, lerne Zucht von Jugend an /\\
 und du wirst Weisheit gewinnen, bis du ergraut bist.\\
\\

<<v19>>
19 Wie ein Pflüger und Schnitter geh auf sie zu /\\
 und warte auf ihren reichen Ertrag! Du wirst in ihrem Dienst nur wenig
Mühe haben /\\
 und bald ihre Früchte genießen.\\
\\

<<v20>>
20 Rau ist sie für den Toren, /\\
 wer ohne Einsicht ist, erträgt sie nicht.\\
\\

<<v21>>
21 Wie ein schwerer Stein lastet sie auf ihm, /\\
 er zögert nicht, sie abzuwerfen.\\
\\

<<v22>>
22 Denn die Zucht ist wie ihr Name, /\\
 vielen ist sie unbequem.\\
\\

<<v23>>
23 Höre, mein Sohn, nimm meine Lehre an, /\\
 verschmäh nicht meinen Rat!\\
\\

<<v24>>
24 Bring deine Füße in ihre Fesseln, /\\
 deinen Hals unter ihr Joch!\\
\\

<<v25>>
25 Beuge deinen Nacken und trage sie, /\\
 werde ihrer Stricke nicht überdrüssig! [fn:6]\\
\\

<<v26>>
26 Mit ganzem Herzen schreite auf sie zu, /\\
 mit voller Kraft halte ihre Wege ein!\\
\\

<<v27>>
27 Frage und forsche, suche und finde! /\\
 Hast du sie erfasst, lass sie nicht wieder los!\\
\\

<<v28>>
28 Denn schließlich wirst du bei ihr Ruhe finden, /\\
 sie wandelt sich dir in Freude.\\
\\

<<v29>>
29 Ihre Fessel wird dir zum sicheren Schutz, /\\
 ihre Stricke werden zu goldenen Gewändern.\\
\\

<<v30>>
30 Ein Goldschmuck ist ihr Joch, /\\
 ihre Garne sind ein Purpurband.\\
\\

<<v31>>
31 Als Prachtgewand kannst du sie anlegen, /\\
 sie aufsetzen als herrliche Krone. [fn:7]\\
\\

<<v32>>
32 Wenn du willst, mein Sohn, kannst du weise werden, /\\
 du wirst klug, wenn du dein Herz darauf richtest.\\
\\

<<v33>>
33 Bist du bereit zu hören, so wirst du belehrt, /\\
 neigst du dein Ohr, erlangst du Bildung.\\
\\

<<v34>>
34 Verweile gern im Kreis der Alten, /\\
 wer weise ist, dem schließ dich an!\\
\\

<<v35>>
35 Lausche gern jeder ernsten Rede, /\\
 keinen Weisheitsspruch lass dir entgehen!\\
\\

<<v36>>
36 Achte auf den, der Weisheit hat, und suche ihn auf; /\\
 dein Fuß trete seine Türschwelle aus.\\
\\

<<v37>>
37 Achte auf die Furcht vor dem Herrn, /\\
 sinn allezeit über seine Gebote nach! Dann gibt er deinem Herzen
Einsicht, /\\
 er macht dich weise, wie du es begehrst. [fn:8]\\
\\
 

* Footnotes

[fn:1] [[file:Spr_15.org::v4][Spr 15,4]]

[fn:2] [[file:Sir_19.org::v4][19,4]]

[fn:3] [[file:Sir_37.org::v4][37,4]]; [[file:Spr_19.org::v4][Spr 19,4]]

[fn:4] 11b: G: und gegen deine Sklaven tritt er freimütig auf.

[fn:5] 16a: Wörtlich: Ein treuer Freund ist ein Beutel des Lebens. Zu diesem Bild vgl. die Anmerkung zu [[file:1.Sam_25.org::v29][1 Sam 25,29]]. Wie eine Kostbarkeit in einem Beutel verborgen wird, so ist das Leben bei Gott und bei einem Freund gut aufgehoben.

[fn:6] [[file:Sir_51.org::v26][51,26]]

[fn:7] [[file:Spr_4.org::v9][Spr 4,9]]

[fn:8] [[file:Ps_1.org::v2][Ps 1,2]]
