:PROPERTIES:
:ID:       99e1e954-cd6a-4c4a-8538-a1b17de780ce
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_11.html][11]]
[[file:Sir_12.html][12]] *13* [[file:Sir_14.html][14]]
[[file:Sir_15.html][15]] ... [[file:Sir_51.html][51]]

--------------

* Sir 13
  :PROPERTIES:
  :CUSTOM_ID: sir-13
  :END:

<<verses>>

<<v1>>
1 Wer Pech anrührt, dem klebt es an der Hand; /\\
 wer mit einem Zuchtlosen umgeht, nimmt seine Art an.\\
\\

<<v2>>
2 Wie willst du tragen, was dir zu schwer ist? /\\
 Ist einer reicher als du, wie kannst du mit ihm zusammengehen? Wie kann
der irdene Topf mit dem Kessel zusammengehen? /\\
 Der Kessel stößt an ihn und er zerbricht.\\
\\

<<v3>>
3 Der Reiche tut Unrecht und prahlt noch damit, /\\
 der Arme leidet Unrecht und muss um Gnade bitten.\\
\\

<<v4>>
4 Bist du ihm nützlich, ist er um dich bemüht, /\\
 brichst du zusammen, lässt er dich im Stich.\\
\\

<<v5>>
5 Hast du etwas, gibt er dir schöne Worte, /\\
 doch er macht dich arm, ohne dass es ihm Leid tut.\\
\\

<<v6>>
6 Hat er dich nötig, schmeichelt er dir, /\\
 er lächelt dir zu und macht dir Hoffnung. ^{[[#fn1][1]]}\\
\\

<<v7>>
7 Solange es Vorteil bringt, hält er dich zum Besten, /\\
 zweimal, dreimal täuscht er dich. Sieht er dich dann wieder, geht er an
dir vorbei /\\
 und schüttelt den Kopf über dich.\\
\\

<<v8>>
8 Gib Acht, wag dich nicht zu weit vor /\\
 und werde nicht wie die, denen der Verstand fehlt.\\
\\

<<v9>>
9 Naht sich ein Vornehmer, halte dich fern, /\\
 umso mehr wird er dich an sich ziehen.\\
\\

<<v10>>
10 Dräng dich nicht vor, sonst musst du dich wieder zurückziehen; /\\
 zieh dich aber nicht ganz zurück, sonst wirst du vergessen.
^{[[#fn2][2]]}\\
\\

<<v11>>
11 Sei nicht zu sicher im freien Umgang mit ihm, /\\
 trau nicht seinen vielen Reden! Mit seinen vielen Reden sucht er dich
zu verführen, /\\
 er lächelt dir zu und forscht dich aus.\\
\\

<<v12>>
12 Grausam handelt der Mächtige und kennt kein Mitleid, /\\
 gegen das Leben vieler schmiedet er heimliche Pläne.\\
\\

<<v13>>
13 Gib Acht und sei vorsichtig, /\\
 geh nicht mit gewalttätigen Menschen!\\
\\

<<v14>>
14 ^{[[#fn3][3]]}\\
\\

<<v15>>
15 Jedes Lebewesen liebt seinesgleichen, /\\
 jeder Mensch den, der ihm ähnlich ist.\\
\\

<<v16>>
16 Jedes Lebewesen hat seinesgleichen um sich, /\\
 mit seinesgleichen gehe auch der Mensch zusammen.\\
\\

<<v17>>
17 Geht etwa der Wolf mit dem Lamm zusammen? /\\
 Ebenso wenig der Frevler mit dem Gerechten.\\
\\

<<v18>>
18 Lebt etwa die Hyäne mit dem Hund in Frieden /\\
 und der Reiche in Frieden mit dem Armen?\\
\\

<<v19>>
19 Des Löwen Beute sind die Wildesel in der Wüste; /\\
 so sind die Geringen die Weide des Reichen.\\
\\

<<v20>>
20 Ein Gräuel für den Stolzen ist die Demut, /\\
 ein Gräuel für den Reichen ist der Arme.\\
\\

<<v21>>
21 Wankt ein Reicher, wird er vom Freund gestützt, /\\
 wankt ein Geringer, wird er vom Freund gestürzt.\\
\\

<<v22>>
22 Redet ein Reicher, so hat er viele Helfer. /\\
 Sein törichtes Gerede nennen sie schön. Redet ein Geringer, ruft man:
Pfui! /\\
 Mag er auch klug reden, für ihn ist kein Platz.\\
\\

<<v23>>
23 Redet ein Reicher, dann schweigen alle, /\\
 sie erheben seine Klugheit bis zu den Wolken. Redet ein Geringer, heißt
es: Wer ist denn das? /\\
 Stolpert er, dann stoßen sie ihn noch.\\
\\

<<v24>>
**** Der rechte Genuss: 13,24 - 14,19
     :PROPERTIES:
     :CUSTOM_ID: der-rechte-genuss-1324---1419
     :END:
24 Gut ist der Reichtum, wenn keine Schuld an ihm klebt; /\\
 schlimm ist die Armut, die aus Übermut entstand.\\
\\

<<v25>>
25 Das Herz des Menschen verändert sein Gesicht /\\
 und macht es heiter oder traurig.\\
\\

<<v26>>
26 Zeichen des glücklichen Herzens ist ein frohes Gesicht; /\\
 Sorgen und Kummer sind quälendes Grübeln.\\
\\

^{[[#fnm1][1]]} G hat den Zusatz: Er redet dir freundlich zu und fragt:
Was brauchst du? Und er beschämt dich bei seinen Gastmählern.

^{[[#fnm2][2]]} Das Verhältnis des einfachen Mannes zum reichen
Machthaber bringt viele Gefahren mit sich. Es wird ein taktvoller
Mittelweg zwischen Aufdringlichkeit und Schüchternheit empfohlen. Der
Reiche ist immer der Überlegene (VV. 22f).

^{[[#fnm3][3]]} Nur in wenigen nichthebräischen Textzeugen überliefert
(stört den Zusammenhang): Wenn du davon hörst, noch schlaftrunken, wach
auf! Mit ganzer Lebenskraft liebe den Herrn und ruf ihn an zu deinem
Heil!
