#+TITLE: Sir 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-01 Mi 13:39]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 4.html

* Sir 4

<<verses>>

<<v1>>
* Mildtätigkeit: 4,1-10

1 Mein Sohn, entzieh dem Armen nicht den Lebensunterhalt /\\
 und lass die Augen des Betrübten nicht vergebens warten!\\
\\

<<v2>>
2 Enttäusche den Hungrigen nicht /\\
 und das Herz des Unglücklichen errege nicht! [fn:1]\\
\\

<<v3>>
3 Verweigere die Gabe dem Bedürftigen nicht

<<v4>>
4 und missachte nicht die Bitten des Geringen!\\
\\

<<v5>>
5 Verbirg dich nicht vor dem Verzweifelten /\\
 und gib ihm keinen Anlass, dich zu verfluchen.\\
\\

<<v6>>
6 Schreit der Betrübte im Schmerz seiner Seele, /\\
 so wird Gott, sein Fels, auf sein Wehgeschrei hören. [fn:2]\\
\\

<<v7>>
7 Mach dich beliebt in der Gemeinde, /\\
 beuge das Haupt vor dem, der sie führt.\\
\\

<<v8>>
8 Neige dem Armen dein Ohr zu /\\
 und erwidere ihm freundlich den Gruß!\\
\\

<<v9>>
9 Rette den Bedrängten vor seinen Bedrängern; /\\
 ein gerechtes Gericht sei dir nicht widerwärtig. [fn:3] [fn:4]\\
\\

<<v10>>
10 Sei den Waisen wie ein Vater /\\
 und den Witwen wie ein Gatte! Dann wird Gott dich seinen Sohn nennen,
/\\
 er wird Erbarmen mit dir haben /\\
 und dich vor dem Grab bewahren. [fn:5] [fn:6]\\
\\

<<v11>>
* Der Weg zum Leben: 4,11-19

11 Die Weisheit belehrt ihre Söhne, /\\
 sie mahnt eindringlich alle, die auf sie achten.\\
\\

<<v12>>
12 Wer sie liebt, liebt das Leben, /\\
 wer sie sucht, wird Gott gefallen. [fn:7]\\
\\

<<v13>>
13 Wer sie ergreift, findet Ehre beim Herrn /\\
 und wird unter Gottes Segen leben.\\
\\

<<v14>>
14 Der Dienst an ihr ist Dienst am Heiligtum; /\\
 wer sie liebt, den liebt der Herr.\\
\\

<<v15>>
15 Wer auf mich hört, wird gerecht richten, /\\
 wer mir zuhört, wohnt in meinen innersten Kammern.\\
\\

<<v16>>
16 Hat er Vertrauen zu mir, wird er mich erlangen, /\\
 auch seine Nachkommen werden mich besitzen.\\
\\

<<v17>>
17 Denn unerkannt gehe ich mit ihm /\\
 und prüfe ihn durch Versuchungen. Furcht und Bangen lasse ich über ihn
kommen, /\\
 bis sein Herz von mir erfüllt ist. [fn:8]\\
\\

<<v18>>
18 Dann wende ich mich ihm zu, /\\
 zeige ihm den geraden Weg und enthülle ihm meine Geheimnisse.\\
\\

<<v19>>
19 Weicht er ab, so verwerfe ich ihn /\\
 und überlasse ihn denen, die ihn vernichten.\\
\\

<<v20>>
* Die Gottesfurcht im Leben der Gemeinschaft: 4,20 - 18,14

* Die echte und die falsche Scham: 4,20-30

20 Mein Sohn, achte auf die rechte Zeit /\\
 und scheue das Unrecht! Deiner selbst sollst du dich nicht schämen
müssen. [fn:9]\\
\\

<<v21>>
21 Es gibt eine Scham, die Sünde bringt, /\\
 und eine Scham, die Ehre und Ruhm einträgt. [fn:10]\\
\\

<<v22>>
22 Sei nicht parteiisch, dir selbst zum Schaden, /\\
 strauchle nicht, dir selbst zum Fall.\\
\\

<<v23>>
23 Halte zur rechten Zeit dein Wort nicht zurück, /\\
 verbirg deine Weisheit nicht!\\
\\

<<v24>>
24 Denn die Weisheit zeigt sich in der Rede /\\
 und die Einsicht in der Antwort der Zunge.\\
\\

<<v25>>
25 Widerstreite der Wahrheit nicht; /\\
 deiner Torheit sollst du dich schämen.\\
\\

<<v26>>
26 Schäme dich nicht, von der Sünde umzukehren, /\\
 leiste nicht trotzig Widerstand! [fn:11]\\
\\

<<v27>>
27 Unterwirf dich nicht dem Toren, /\\
 nimm keine Rücksicht auf den Herrscher!\\
\\

<<v28>>
28 Bis zum Tod setz dich ein für das Recht, /\\
 dann wird der Herr für dich kämpfen.\\
\\

<<v29>>
29 Sei nicht prahlerisch mit deinen Worten /\\
 und schlaff und matt in deinem Tun!\\
\\

<<v30>>
30 Spiel nicht in deinem Haus den Löwen, /\\
 vor dem sich deine Knechte fürchten müssen.\\
\\

<<v31>>
* Das rechte Verhalten gegen den Besitz: 4,31 - 5,8

31 Deine Hand sei nicht ausgestreckt zum Nehmen /\\
 und verschlossen beim Zurückgeben.\\
\\


* Footnotes

[fn:1] 2-5: Text korr.; in H und G Doppelungen

[fn:2] [[file:Dtn_32.org::v3][Dtn 32,3f]]

[fn:3] [[file:Spr_17.org::v15][Spr 17,15]]; [[file:Spr_31.org::v8][31,8f]]

[fn:4] Nach G: Sei nicht feig im Gericht!

[fn:5] [[file:Ijob_29.org::v12][Ijob 29,12f]]

[fn:6] 10cd: G: Dann wirst du wie ein Sohn des Höchsten sein; er wird dich mehr lieben als deine Mutter.

[fn:7] [[file:Spr_8.org::v35][Spr 8,35]]; [[file:Spr_12.org::v2][12,2]]; [[file:Spr_18.org::v22][18,22]]

[fn:8] [[file:Sir_2.org::v1][2,1]]

[fn:9] [[file:Koh_3.org::v1][Koh 3,1]]

[fn:10] [[file:Sir_41.org::v16][41,16]] - [[file:Sir_42.org::v8][42,8]]

[fn:11] [[file:Sir_5.org::v7][5,7]]
