#+TITLE: Sir 19 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-05 So 22:50]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 19.html

* Sir 19

<<verses>>

<<v1>>
1 Wer das tut, wird niemals reich, /\\
 wer das wenige gering schätzt, richtet sich zugrunde. [fn:1]\\
\\

<<v2>>
2 Wein und Weiber machen das Herz zügellos; /\\
 wer sich an Dirnen hängt, wird frech.\\
\\

<<v3>>
3 [Moder und Würmer nehmen ihn in Besitz, /\\
 freche Gier richtet den zugrunde, über den sie herrscht.] [fn:2] [fn:3]\\
\\

<<v4>>
4 Wer schnell vertraut, ist leichtfertig, /\\
 wer sündigt, verfehlt sich gegen sich selbst.\\
\\

<<v5>>
5 Wer sich über eine Schlechtigkeit freut, wird selbst verachtet, /\\
 [wer den Lüsten widerstrebt, krönt sein Leben. [fn:4]\\
\\

<<v6>>
6 Wer seine Zunge beherrscht, lebt ohne Streit;] /\\
 wer Gerede verbreitet, dem fehlt es an Verstand.\\
\\

<<v7>>
7 Verbreite niemals ein Gerede, /\\
 dann wird auch dich niemand schmähen.\\
\\

<<v8>>
8 Rede weder über Freund noch Feind; /\\
 wenn du einen Freund hast, enthülle nichts über ihn! [fn:5]\\
\\

<<v9>>
9 Denn wer dich hört, wird sich vor dir hüten /\\
 und dir zur gegebenen Zeit seinen Groll zeigen. [fn:6]\\
\\

<<v10>>
10 Hast du etwas gehört, so sterbe es in dir; /\\
 sei unbesorgt, es wird dich nicht zerreißen.\\
\\

<<v11>>
11 Um eines Wortes willen kommt der Tor in Wehen /\\
 wie eine Gebärende durch ihre Leibesfrucht. [fn:7]\\
\\

<<v12>>
12 Wie ein Pfeil im Schenkel sitzt, /\\
 so steckt das Wort im Leib des Toren.\\
\\

<<v13>>
13 Stell den Freund zur Rede, ob er etwas getan hat, /\\
 und wenn er es getan hat - damit er es nicht wieder tut.\\
\\

<<v14>>
14 Stell deinen Nächsten zur Rede, ob er etwas gesagt hat, /\\
 und wenn er es gesagt hat - damit er es nicht wiederholt.\\
\\

<<v15>>
15 Stell den Freund zur Rede, denn oft gibt es Verleumdung; /\\
 trau nicht jedem Wort!\\
\\

<<v16>>
16 Mancher gleitet aus, doch ohne Absicht. /\\
 Wer hätte noch nie mit seiner Zunge gesündigt?\\
\\

<<v17>>
17 Stell deinen Nächsten zur Rede, ehe du ihm Vorwürfe machst. /\\
 Gib dem Gesetz des Höchsten Raum! [fn:8]\\
\\

<<v18>>
18 [] [fn:9]

<<v19>>
19 []\\
\\

<<v20>>
* Rechte und falsche Klugheit: 19,20-30

20 Alle Weisheit ist Furcht vor dem Herrn; /\\
 in jeder Weisheit liegt Erfüllung des Gesetzes.\\
\\

<<v21>>
21 []\\
\\

<<v22>>
22 Schlechtes zu kennen ist keine Weisheit, /\\
 der Rat der Sünder ist keine Klugheit.\\
\\

<<v23>>
23 Es gibt eine Schläue, die ein Gräuel ist, /\\
 und es gibt Einfältige, die nichts Schlechtes tun.\\
\\

<<v24>>
24 Besser ist es, arm an Klugheit und gottesfürchtig zu sein, /\\
 als reich an Einsicht, aber das Gesetz zu übertreten.\\
\\

<<v25>>
25 Es gibt eine listige Schläue, doch sie ist ungerecht; /\\
 mancher verstellt sich, um Rechtschaffenheit vorzutäuschen.\\
\\

<<v26>>
26 Mancher geht gebeugt und traurig einher, /\\
 doch sein Inneres ist voll Tücke.\\
\\

<<v27>>
27 Er schlägt den Blick nieder und stellt sich taub; /\\
 wo er nicht durchschaut wird, tritt er gegen dich auf.\\
\\

<<v28>>
28 Wenn ihm die Kraft fehlt, Unrecht zu tun, /\\
 tut er doch Böses, sobald er Gelegenheit findet.\\
\\

<<v29>>
29 Am Aussehen erkennt man den Menschen, /\\
 am Gesichtsausdruck erkennt ihn der Weise.\\
\\

<<v30>>
30 Die Kleidung des Menschen offenbart sein Verhalten, /\\
 die Schritte des Menschen zeigen, was an ihm ist. [fn:10]\\
\\


* Footnotes

[fn:1] Wer das tut: nach H. - «das wenige» in b meint die im Einzelfall nicht besonders hohen Ausgaben des Schlemmers; erst die maßlose Gewohnheit ist gefährlich.

[fn:2] [[file:Sir_10.org::v11][10,11]]; [[file:Sir_6.org::v4][6,4]]

[fn:3] Wohl nicht ursprünglich, sondern aus [[file:Sir_10.org::v11][10,11]] und [[file:Sir_6.org::v4][6,4]] zusammengestellt. Der erste Halbvers fehlt in H und S.

[fn:4] 5b.6a: Nur in einigen G-Handschriften.

[fn:5] 8b: G kaum richtig: Wenn es für dich keine Sünde ist, enthülle nichts! (Vgl. [[file:Sir_27.org::v16][27,16-21]]).

[fn:6] (8-9) [[file:Sir_22.org::v26][22,26]]

[fn:7] 11f: Sinn der Vergleiche: Der Tor kann nichts für sich behalten.

[fn:8] [[file:Lev_19.org::v17][Lev 19,17]]

[fn:9] 18.19.21: Späte Zusätze

[fn:10] So nach S.
