:PROPERTIES:
:ID:       547a0694-cb28-45d9-8b19-3679d748a800
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_18.html][18]]
[[file:Sir_19.html][19]] *20* [[file:Sir_21.html][21]]
[[file:Sir_22.html][22]] ... [[file:Sir_51.html][51]]

--------------

* Sir 20
  :PROPERTIES:
  :CUSTOM_ID: sir-20
  :END:

<<verses>>

<<v1>>
**** Das rechtzeitige Reden und Schweigen: 20,1-26
     :PROPERTIES:
     :CUSTOM_ID: das-rechtzeitige-reden-und-schweigen-201-26
     :END:
1 Manche Ermahnung geschieht zur Unzeit; /\\
 mancher schweigt und der ist weise.\\
\\

<<v2>>
2 Keinen Dank erntet, wer den Zornigen zurechtweist; ^{[[#fn1][1]]}

<<v3>>
3 wer Lob erteilt, bleibt vor Schimpf bewahrt.\\
\\

<<v4>>
4 Wie ein Entmannter, der bei einem Mädchen liegt, /\\
 ist einer, der mit Gewalt das Recht durchsetzen will. ^{[[#fn2][2]]}\\
\\

<<v5>>
5 Mancher schweigt und gilt als weise, /\\
 mancher wird trotz vielen Redens verachtet.\\
\\

<<v6>>
6 Mancher schweigt, weil er keine Antwort weiß, /\\
 mancher schweigt, weil er die rechte Zeit beachtet. ^{[[#fn3][3]]}\\
\\

<<v7>>
7 Der Weise schweigt bis zur rechten Zeit, /\\
 der Tor aber achtet nicht auf die rechte Zeit. ^{[[#fn4][4]]}\\
\\

<<v8>>
8 Wer viele Worte macht, wird zum Ekel, /\\
 der Anmaßende wird gehasst.\\
\\

<<v9>>
9 Mancher Erfolg wird dem Menschen zum Schaden, /\\
 mancher Gewinn wird zum Verlust.\\
\\

<<v10>>
10 Es gibt Geschenke, von denen man nichts hat, /\\
 es gibt Geschenke, die man doppelt vergüten muss.\\
\\

<<v11>>
11 Es gibt Demütigung um der Ehre willen; /\\
 mancher erhob sein Haupt aus der Erniedrigung.\\
\\

<<v12>>
12 Mancher kauft vieles billig ein /\\
 und muss es doch siebenfach bezahlen.\\
\\

<<v13>>
13 Wer klug zu reden weiß, macht sich beliebt, /\\
 die Liebenswürdigkeit der Toren ist umsonst. ^{[[#fn5][5]]}\\
\\

<<v14>>
14 Vom Geschenk eines Toren hast du nichts, /\\
 denn sieben Augen hat er, nicht nur eines. ^{[[#fn6][6]]}\\
\\

<<v15>>
15 Er gibt wenig und schimpft viel, /\\
 er reißt den Mund auf wie ein Ausrufer. Heute leiht er, morgen fordert
er zurück; /\\
 solch ein Mensch ist verhasst.\\
\\

<<v16>>
16 Der Tor sagt: Ich habe keinen Freund, /\\
 meine Wohltaten finden keinen Dank.\\
\\

<<v17>>
17 Alle, die sein Brot essen, haben böse Zungen: /\\
 Wie oft und wie viel verlachen sie ihn!\\
\\

<<v18>>
18 Besser ein Fehltritt auf dem Boden als ein Fehltritt durch die Zunge;
/\\
 so schnell wird auch der Sturz der Bösen kommen.\\
\\

<<v19>>
19 Ein Wort zur Unzeit ist ein Braten ohne Salz, /\\
 im Mund des Ungebildeten findet es sich dauernd.
^{[[#fn7][7]][[#fn8][8]]}\\
\\

<<v20>>
20 Ein Sinnspruch aus dem Mund des Toren wird verachtet, /\\
 denn er spricht ihn nicht zur rechten Zeit.\\
\\

<<v21>>
21 Mancher sündigt nicht, obwohl er arm ist; /\\
 er lässt sich in seiner Ruhe nicht stören. ^{[[#fn9][9]]}\\
\\

<<v22>>
22 Mancher richtet aus Scham sich selbst zugrunde; /\\
 weil er (seine Not) verbirgt, geht er unter. ^{[[#fn10][10]]}\\
\\

<<v23>>
23 Mancher gibt aus Scham dem Freund Versprechen /\\
 und macht ihn sich ohne Grund zum Feind.\\
\\

<<v24>>
24 Ein schlimmer Schandfleck am Menschen ist die Lüge; /\\
 im Mund des Ungebildeten findet sie sich dauernd. ^{[[#fn11][11]]}\\
\\

<<v25>>
25 Besser ein Dieb als einer, der immer nur lügt; /\\
 beide aber werden zugrunde gehen. ^{[[#fn12][12]]}\\
\\

<<v26>>
26 Das Ende des Lügners ist Schmach, /\\
 immerfort haftet seine Schande an ihm.\\
\\

<<v27>>
**** Verschiedene Sprichwörter: 20,27-31
     :PROPERTIES:
     :CUSTOM_ID: verschiedene-sprichwörter-2027-31
     :END:
27 Wer weise ist im Reden, kommt voran, /\\
 ein kluger Mann ist bei den Machthabern beliebt. ^{[[#fn13][13]]}\\
\\

<<v28>>
28 Wer das Land bebaut, schichtet hohe Garbenstöße auf; /\\
 wer den Machthabern gefällt, kann manches Unrecht gutmachen.
^{[[#fn14][14]]}\\
\\

<<v29>>
29 Geschenke und Gaben blenden die Augen der Weisen, /\\
 wie ein Zügel im Maul lenken sie Vorwürfe ab. ^{[[#fn15][15]]}\\
\\

<<v30>>
30 Verborgene Weisheit und versteckter Schatz: /\\
 was nützen sie beide? ^{[[#fn16][16]]}\\
\\

<<v31>>
31 Besser einer, der seine Torheit verbirgt, /\\
 als einer, der seine Weisheit verbirgt.\\
\\

^{[[#fnm1][1]]} G: Wie ist es doch besser zurechtzuweisen, als zu
zürnen.

^{[[#fnm2][2]]} Der eigenartige Vergleich soll dartun, wie widerwärtig
und erfolglos äußere Nötigung ist.

^{[[#fnm3][3]]} ℘ 37,20; Spr 17,28

^{[[#fnm4][4]]} ℘ 21,25f; Spr 29,11

^{[[#fnm5][5]]} 13a: Andere Übersetzungsmöglichkeit: Der Weise macht
sich mit wenigen Worten beliebt.

^{[[#fnm6][6]]} Nach S wäre zu übersetzen: Das Geschenk des Toren nützt
ihm nichts, weil seine Augen siebenfach auf die Vergeltung gerichtet
sind. Logischer G: Der Tor (= der Geizige) rechnet mit reichlichen
Gegengaben, sodass du von seinem Geschenk keinen Nutzen hast.

^{[[#fnm7][7]]} ℘ 22,6; Spr 26,7

^{[[#fnm8][8]]} 19a: So nach S; G: Ein widerwärtiger Mensch - ein Wort
zur Unzeit!

^{[[#fnm9][9]]} 21b: Übersetzung unsicher.

^{[[#fnm10][10]]} 22-26: Es handelt sich um unaufrichtige Versprechungen
eines verlegenen Schuldners. Das führt zum allgemeinen Thema «Lüge» in
VV. 24-26.

^{[[#fnm11][11]]} ℘ 20,19

^{[[#fnm12][12]]} ℘ 5,14

^{[[#fnm13][13]]} 27a: Andere Übersetzungsmöglichkeit: Der Weise bringt
sich mit wenigen Worten voran (vgl. V. 13a).

^{[[#fnm14][14]]} Sinn: Wie ein tüchtiger Landwirt reiche Ernte
einbringt, so kann ein kluger Diplomat manches Unrecht verhindern.

^{[[#fnm15][15]]} ℘ Dtn 16,19

^{[[#fnm16][16]]} 30f: Wie 41,14f ohne Zusammenhang mit dem Kontext.
