:PROPERTIES:
:ID:       ce171a95-e29d-4fcb-9abb-3ed8f7450d69
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] *2* [[file:Sir_3.html][3]] [[file:Sir_4.html][4]]
... [[file:Sir_51.html][51]]

--------------

* Sir 2
  :PROPERTIES:
  :CUSTOM_ID: sir-2
  :END:

<<verses>>

<<v1>>
**** Vertrauen und Treue gegen Gott: 2,1-18
     :PROPERTIES:
     :CUSTOM_ID: vertrauen-und-treue-gegen-gott-21-18
     :END:
1 Mein Sohn, wenn du dem Herrn dienen willst, /\\
 dann mach dich auf Prüfung gefasst!\\
\\

<<v2>>
2 Sei tapfer und stark, /\\
 zur Zeit der Heimsuchung überstürze nichts!\\
\\

<<v3>>
3 Hänge am Herrn und weiche nicht ab, /\\
 damit du am Ende erhöht wirst.\\
\\

<<v4>>
4 Nimm alles an, was über dich kommen mag, /\\
 halt aus in vielfacher Bedrängnis!\\
\\

<<v5>>
5 Denn im Feuer wird das Gold geprüft /\\
 und jeder, der Gott gefällt, im Schmelzofen der Bedrängnis.\\
\\

<<v6>>
6 Vertrau auf Gott, er wird dir helfen, /\\
 hoffe auf ihn, er wird deine Wege ebnen. ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v7>>
7 Ihr, die ihr den Herrn fürchtet, /\\
 hofft auf sein Erbarmen, /\\
 weicht nicht ab, damit ihr nicht zu Fall kommt.\\
\\

<<v8>>
8 Ihr, die ihr den Herrn fürchtet, vertraut auf ihn /\\
 und er wird euch den Lohn nicht vorenthalten.
^{[[#fn3][3]][[#fn4][4]]}\\
\\

<<v9>>
9 Ihr, die ihr den Herrn fürchtet, hofft auf Heil, /\\
 auf immer währende Freude und auf Erbarmen! ^{[[#fn5][5]]}\\
\\

<<v10>>
10 Schaut auf die früheren Generationen und seht: /\\
 Wer hat auf den Herrn vertraut /\\
 und ist dabei zuschanden geworden? Wer hoffte auf ihn und wurde
verlassen? /\\
 Wer rief ihn an und er erhörte ihn nicht? ^{[[#fn6][6]]}\\
\\

<<v11>>
11 Denn gnädig und barmherzig ist der Herr; /\\
 er vergibt die Sünden und hilft zur Zeit der Not.\\
\\

<<v12>>
12 Weh den mutlosen Herzen und den schlaffen Händen, /\\
 dem Menschen, der auf zweierlei Wegen geht. ^{[[#fn7][7]]}\\
\\

<<v13>>
13 Weh dem schlaffen Herzen, weil es nicht glaubt; /\\
 darum wird es keinen Schutz haben.\\
\\

<<v14>>
14 Weh euch, die ihr die Hoffnung verloren habt. /\\
 Was werdet ihr tun, wenn euch der Herr zur Rechenschaft zieht?
^{[[#fn8][8]]}\\
\\

<<v15>>
15 Wer den Herrn fürchtet, ist nicht ungehorsam gegen sein Wort, /\\
 wer ihn liebt, hält seine Wege ein.\\
\\

<<v16>>
16 Wer den Herrn fürchtet, sucht ihm zu gefallen, /\\
 wer ihn liebt, ist erfüllt von seinem Gesetz.\\
\\

<<v17>>
17 Wer den Herrn fürchtet, macht sein Herz bereit /\\
 und demütigt sich vor ihm.\\
\\

<<v18>>
18 Besser ist es, in die Hände des Herrn zu fallen /\\
 als in die Hände der Menschen. Denn wie seine Größe, so ist sein
Erbarmen, /\\
 und wie sein Name, so sind auch seine Werke.
^{[[#fn9][9]][[#fn10][10]]}\\
\\

^{[[#fnm1][1]]} ℘ Spr 3,6

^{[[#fnm2][2]]} 6b: Übersetzung nach S und Origenes; weniger gut G: Ebne
deine Wege und hoffe auf ihn!

^{[[#fnm3][3]]} ℘ 16,14; 51,30

^{[[#fnm4][4]]} 8b: G hat leicht geändert: und euer Lohn wird nicht
ausbleiben.

^{[[#fnm5][5]]} 9b: Erbarmen: nach G, wie in V. 7a; S: Rettung.

^{[[#fnm6][6]]} ℘ Ps 37,25

^{[[#fnm7][7]]} 12b: dem Menschen: nach S; G verschärft: dem Sünder.

^{[[#fnm8][8]]} ℘ 17,24; 41,2

^{[[#fnm9][9]]} ℘ 2 Sam 24,14

^{[[#fnm10][10]]} 18d: Fehlt in G zu Unrecht.
