:PROPERTIES:
:ID:       35ee8bf6-9081-431e-b6d5-7fdbe59eea98
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_19.html][19]]
[[file:Sir_20.html][20]] *21* [[file:Sir_22.html][22]]
[[file:Sir_23.html][23]] ... [[file:Sir_51.html][51]]

--------------

* Sir 21
  :PROPERTIES:
  :CUSTOM_ID: sir-21
  :END:

<<verses>>

<<v1>>
**** Die Grundlehre des Weisen: 21,1-10
     :PROPERTIES:
     :CUSTOM_ID: die-grundlehre-des-weisen-211-10
     :END:
1 Mein Sohn, hast du gesündigt, tu es nicht wieder /\\
 und bete wegen deiner früheren Sünden!\\
\\

<<v2>>
2 Flieh vor der Sünde wie vor der Schlange; /\\
 kommst du ihr zu nahe, so beißt sie dich. Löwenzähne sind ihre Zähne,
/\\
 sie rauben den Menschen das Leben.\\
\\

<<v3>>
3 Wie ein zweischneidiges Schwert ist jedes Unrecht; /\\
 für die Wunde, die es schlägt, gibt es keine Heilung.\\
\\

<<v4>>
4 Gewalttat und Hochmut verwüsten den Wohlstand, /\\
 das Haus des Übermütigen stürzt ein.\\
\\

<<v5>>
5 Das Gebet aus dem Mund des Armen dringt zu den Ohren Gottes /\\
 und rasch kommt Gottes Gericht.\\
\\

<<v6>>
6 Wer Ermahnung hasst, folgt der Spur des Sünders; /\\
 wer den Herrn fürchtet, nimmt sie sich zu Herzen.\\
\\

<<v7>>
7 Von weitem erkennt man den Schwätzer; /\\
 der Erfahrene merkt es, wenn jener entgleist.\\
\\

<<v8>>
8 Baut einer sein Haus mit fremdem Geld, /\\
 sammelt er Steine für einen Schutthaufen.\\
\\

<<v9>>
9 Ein Bündel Werg ist die Versammlung der Ruchlosen, /\\
 ihr Ende ist die Feuerflamme.\\
\\

<<v10>>
10 Der Weg der Sünder ist frei von Steinen; /\\
 doch sein Ende ist die Tiefe der Unterwelt. ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v11>>
**** Der Weise und der Tor: 21,11 - 22,2
     :PROPERTIES:
     :CUSTOM_ID: der-weise-und-der-tor-2111---222
     :END:
11 Wer das Gesetz befolgt, beherrscht seinen Trieb /\\
 und Gottesfurcht ist vollendete Weisheit.\\
\\

<<v12>>
12 Der Unkluge lässt sich nicht erziehen; /\\
 doch es gibt auch Klugheit, die viel Bitterkeit einträgt.
^{[[#fn3][3]]}\\
\\

<<v13>>
13 Das Wissen des Weisen schwillt an wie ein Bach, /\\
 wie ein lebendiger Quell ist sein Rat.\\
\\

<<v14>>
14 Das Herz des Toren ist wie eine geborstene Zisterne: /\\
 Es hält keine Weisheit fest. ^{[[#fn4][4]]}\\
\\

<<v15>>
15 Hört der Verständige ein weises Wort, /\\
 lobt er es und fügt andere hinzu. Hört es der Leichtfertige, lacht er
darüber, /\\
 er wirft es weit hinter sich.\\
\\

<<v16>>
16 Das Gespräch des Toren ist wie eine Last auf der Reise, /\\
 doch auf den Lippen des Verständigen findet sich Anmut.
^{[[#fn5][5]]}\\
\\

<<v17>>
17 Die Rede des Weisen begehrt man in der Versammlung /\\
 und seine Worte überdenkt man im Herzen.\\
\\

<<v18>>
18 Wie ein Gefängnis ist dem Toren die Weisheit, /\\
 Erkenntnis ist dem Unverständigen wie eine Fessel. ^{[[#fn6][6]]}\\
\\

<<v19>>
19 Wie Ketten an den Füßen ist dem Unvernünftigen die Zucht /\\
 und wie Handschellen an der rechten Hand.\\
\\

<<v20>>
20 Der Tor lacht mit lauter Stimme, /\\
 der Kluge aber lächelt kaum leise. ^{[[#fn7][7]]}\\
\\

<<v21>>
21 Wie ein goldener Schmuck ist dem Weisen die Zucht /\\
 und wie eine Spange am rechten Arm.\\
\\

<<v22>>
22 Der Fuß des Toren eilt rasch ins Haus, /\\
 der Besonnene aber wartet bescheiden.\\
\\

<<v23>>
23 Der Tor blickt durch die Tür ins Haus hinein, /\\
 der Wohlerzogene bleibt draußen stehen.\\
\\

<<v24>>
24 Ungezogen ist es, an der Tür zu horchen, /\\
 der Verständige aber verschließt seine Ohren.\\
\\

<<v25>>
25 Die Lippen der Frevler erzählen ihre eigene Torheit, /\\
 die Worte der Verständigen sind wohl abgewogen. ^{[[#fn8][8]]}\\
\\

<<v26>>
26 Die Toren haben ihr Herz auf der Zunge, /\\
 die Weisen haben ihre Zunge im Herzen.\\
\\

<<v27>>
27 Verflucht der Ruchlose den Gerechten, /\\
 so verflucht er sich selbst. ^{[[#fn9][9]]}\\
\\

<<v28>>
28 Sich selbst besudelt der Verleumder; /\\
 wo er wohnt, ist er verhasst.\\
\\

^{[[#fnm1][1]]} ℘ Spr 7,27

^{[[#fnm2][2]]} 10a: Sinn: Die Sünder eilen ohne Hindernis dem Untergang
entgegen.

^{[[#fnm3][3]]} ℘ 19,22

^{[[#fnm4][4]]} 14a: Zisterne: nach S; G: Krug.

^{[[#fnm5][5]]} ℘ Koh 10,12

^{[[#fnm6][6]]} Übersetzung vorwiegend nach S; G, weniger
wahrscheinlich: Wie ein verwüstetes Haus, so ist dem Toren die Weisheit
und die Erkenntnis des Unvernünftigen sind unverständliche Reden.

^{[[#fnm7][7]]} ℘ Koh 7,6

^{[[#fnm8][8]]} 25a: Text unsicher.

^{[[#fnm9][9]]} 27a: G unrichtig: den Satan.
