#+TITLE: Sir 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-05 So 17:50]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 18.html

* Sir 18

<<verses>>

<<v1>>
* Die Größe Gottes: 18,1-14

1 Der Herr, der in Ewigkeit lebt, hat alles insgesamt erschaffen, /\\
 der Herr allein erweist sich als gerecht.\\
\\

<<v2>>
2 [] [fn:1]

<<v3>>
3 []\\
\\

<<v4>>
4 Keiner vermag seine Werke zu verkünden. /\\
 Wer ergründet seine großen Taten?\\
\\

<<v5>>
5 Wer kann seine gewaltige Größe beschreiben /\\
 und seine großen Taten aufzählen bis zum Ende?\\
\\

<<v6>>
6 Man kann nichts wegnehmen und nichts hinzutun, /\\
 unmöglich ist es, die Wunder des Herrn zu ergründen. [fn:2]\\
\\

<<v7>>
7 Ist der Mensch am Ende angelangt, /\\
 steht er noch am Anfang, /\\
 wenn er es aufgibt, ist er ratlos. [fn:3]\\
\\

<<v8>>
8 Was ist der Mensch und wozu nützt er? /\\
 Was ist gut an ihm und was ist schlecht?\\
\\

<<v9>>
9 Das Leben eines Menschen dauert /\\
 höchstens hundert Jahre. [fn:4]\\
\\

<<v10>>
10 Wie ein Wassertropfen im Meer und wie ein Körnchen im Sand, /\\
 so verhalten sich die wenigen Jahre zu der Zeit der Ewigkeit.\\
\\

<<v11>>
11 Darum hat der Herr mit ihnen Geduld /\\
 und er gießt über sie sein Erbarmen aus.\\
\\

<<v12>>
12 Er sieht und weiß, dass ihr Ende schlimm ist; /\\
 darum hat er so viel Nachsicht mit ihnen.\\
\\

<<v13>>
13 Das Erbarmen des Menschen gilt nur seinem Nächsten, /\\
 das Erbarmen des Herrn allen Menschen. Er weist zurecht, erzieht und
belehrt /\\
 und führt wie ein Hirt seine Herde zurück.\\
\\

<<v14>>
14 Glücklich alle, die auf sein Erbarmen hoffen /\\
 und seine Gebote annehmen. [fn:5]\\
\\

<<v15>>
* Verschiedene Mahnungen und Warnungen: 18,15 - 24,34

* Das Verhalten des Weisen: 18,15-29

15 Mein Sohn, bring keinen Makel auf deine Wohltaten /\\
 und füg zu keiner Gabe kränkende Worte! [fn:6]\\
\\

<<v16>>
16 Vertreibt nicht der Tau die Hitze? /\\
 So ist das Wort mehr als die Gabe.\\
\\

<<v17>>
17 Ist das Wort nicht mehr wert als die Gabe? /\\
 Dem Gütigen steht beides wohl an.\\
\\

<<v18>>
18 Der Tor schmäht in liebloser Weise, /\\
 die Gabe des Geizigen macht die Augen traurig.\\
\\

<<v19>>
19 Bevor du redest, unterrichte dich, /\\
 und ehe du krank wirst, sorge für die Gesundheit!\\
\\

<<v20>>
20 Noch vor dem Gericht erforsche dich selbst, /\\
 dann wird dir in der Stunde der Prüfung verziehen.\\
\\

<<v21>>
21 Demütige dich, ehe du zu Fall kommst; /\\
 zur Zeit der Sünde lass Umkehr erkennen!\\
\\

<<v22>>
22 Säume nicht, ein Gelübde rechtzeitig einzulösen, /\\
 warte nicht bis zum Tod, um davon frei zu werden.\\
\\

<<v23>>
23 Ehe du gelobst, überdenk dein Gelübde, /\\
 sei nicht wie einer, der den Herrn versucht. [fn:7]\\
\\

<<v24>>
24 Denk an den Zorn am Ende der Tage, /\\
 an die Zeit der Vergeltung, wenn er sein Gesicht abwendet. [fn:8]\\
\\

<<v25>>
25 Denk zur Zeit des Überflusses an die Zeit des Hungers, /\\
 in den Tagen des Reichtums an Armut und Not! [fn:9]\\
\\

<<v26>>
26 Vom Morgen zum Abend wechselt die Zeit, /\\
 alles eilt dahin vor dem Herrn.\\
\\

<<v27>>
27 Ein Weiser nimmt sich immer in Acht, /\\
 in Zeiten der Sünde hütet er sich vor Verfehlung.\\
\\

<<v28>>
28 Jeder Verständige soll Weisheit lehren; /\\
 wer sie gefunden hat, soll ihr Lob verkünden. [fn:10]\\
\\

<<v29>>
29 Wer klug zu reden vermag, ist selbst ein Weisheitslehrer /\\
 und trägt in Bescheidenheit seine Sinnsprüche vor. [fn:11]\\
\\

<<v30>>
* Die Beherrschung der Begierden: 18,30 - 19,17

30 Folg nicht deinen Begierden, /\\
 von deinen Gelüsten halte dich fern!\\
\\

<<v31>>
31 Wenn du erfüllst, was deine Seele begehrt, /\\
 erfüllst du das Begehren deines Feindes.\\
\\

<<v32>>
32 Freu dich nicht über ein wenig Lust; /\\
 doppelt so schwer wird dann die Armut sein.\\
\\

<<v33>>
33 Sei kein Fresser und Säufer; /\\
 denn sonst bleibt nichts im Beutel. [fn:12]\\
\\

* Footnotes

[fn:1] 2f: Die beiden Verse sind späte Zusätze.

[fn:2] [[file:Sir_42.org::v21][42,21]]

[fn:3] [[file:Ps_139.org::v18][Ps 139,18]]

[fn:4] Hier die runde Zahl hundert; [[file:Ps_90.org::v10][Ps 90,10]]: siebzig, höchstens achtzig Jahre.

[fn:5] So mit S; G: Er erbarmt sich derer, die Zucht annehmen und eifrig nach seinen Geboten suchen.

[fn:6] [[file:Sir_41.org::v22][41,22]]

[fn:7] [[file:Spr_20.org::v25][Spr 20,25]]; [[file:Koh_5.org::v3][Koh 5,3f]]

[fn:8] Jenseitige Strafe kennt Sirach noch nicht. Er denkt an den zuletzt doch eintreffenden Zorn Gottes.

[fn:9] Das Stichwort «Denk an» leitet zur Mahnung über, im Glück an das drohende Unglück zu denken, da die Zeiten wechseln.

[fn:10] Übersetzung nach S.

[fn:11] [[file:Sir_16.org::v25][16,25]]; [[file:Sir_24.org::v32][24,32f]].

[fn:12] 33b: Andere Übersetzungsmöglichkeit: während du nichts im Beutel hast.
