:PROPERTIES:
:ID:       436173e6-6afb-4e1d-86b0-4b93fe605773
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_15.html][15]]
[[file:Sir_16.html][16]] *17* [[file:Sir_18.html][18]]
[[file:Sir_19.html][19]] ... [[file:Sir_51.html][51]]

--------------

* Sir 17
  :PROPERTIES:
  :CUSTOM_ID: sir-17
  :END:

<<verses>>

<<v1>>
1 Der Herr hat die Menschen aus Erde erschaffen /\\
 und lässt sie wieder zu ihr zurückkehren. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Gezählte Tage und eine bestimmte Zeit wies er ihnen zu /\\
 und gab ihnen Macht über alles auf der Erde.\\
\\

<<v3>>
3 Ihm selbst ähnlich hat er sie mit Kraft bekleidet /\\
 und sie nach seinem Abbild erschaffen. ^{[[#fn2][2]]}\\
\\

<<v4>>
4 Auf alle Wesen legte er die Furcht vor ihnen, /\\
 über Tiere und Vögel sollten sie herrschen.

<<v5>>
5 ^{[[#fn3][3]]}\\
\\

<<v6>>
6 Er bildete ihnen Mund und Zunge, Auge und Ohr /\\
 und ein Herz zum Denken gab er ihnen. ^{[[#fn4][4]]}\\
\\

<<v7>>
7 Mit kluger Einsicht erfüllte er sie /\\
 und lehrte sie, Gutes und Böses zu erkennen.\\
\\

<<v8>>
8 Er zeigte ihnen die Größe seiner Werke, /\\
 um die Furcht vor ihm in ihr Herz zu pflanzen.\\
\\

<<v9>>
9 Sie sollten für immer seine Wunder rühmen /\\
\\

<<v10>>
10 und seinen heiligen Namen loben.\\
\\

<<v11>>
**** Die Erwählung Israels: 17,11-23
     :PROPERTIES:
     :CUSTOM_ID: die-erwählung-israels-1711-23
     :END:
11 Er hat ihnen Weisheit geschenkt /\\
 und ihnen das Leben spendende Gesetz gegeben. ^{[[#fn5][5]]}\\
\\

<<v12>>
12 Einen ewigen Bund hat er mit ihnen geschlossen /\\
 und ihnen seine Gebote mitgeteilt. ^{[[#fn6][6]]}\\
\\

<<v13>>
13 Ihre Augen sahen seine machtvolle Herrlichkeit, /\\
 ihr Ohr vernahm seine gewaltige Stimme.\\
\\

<<v14>>
14 Er sprach zu ihnen: Hütet euch vor allem Unrecht! /\\
 Er schrieb ihnen ihr Verhalten gegenüber dem Nächsten vor.\\
\\

<<v15>>
15 Ihre Wege liegen allezeit offen vor ihm, /\\
 sie sind nicht verborgen vor seinen Augen.\\
\\

<<v16>>
16 [] ^{[[#fn7][7]]}\\
\\

<<v17>>
17 Für jedes Volk bestellte er einen Herrscher, /\\
 Israel aber ist der Erbbesitz des Herrn.\\
\\

<<v18>>
18 []\\
\\

<<v19>>
19 Alle ihre Taten stehen vor ihm wie die Sonne, /\\
 seine Augen ruhen stets auf ihren Wegen.\\
\\

<<v20>>
20 Ihre Frevel sind vor ihm nicht verborgen, /\\
 alle ihre Sünden stehen dem Herrn vor Augen.\\
\\

<<v21>>
21 []\\
\\

<<v22>>
22 Das Almosen eines jeden ist bei ihm wie ein Siegelring, /\\
 des Menschen Wohltat behütet er wie einen Augapfel.\\
\\

<<v23>>
23 Schließlich erhebt er sich und vergilt ihnen, /\\
 er lässt die Vergeltung über ihr Haupt kommen. ^{[[#fn8][8]]}\\
\\

<<v24>>
**** Reue und Umkehr: 17,24-32
     :PROPERTIES:
     :CUSTOM_ID: reue-und-umkehr-1724-32
     :END:
24 Den Reumütigen aber gewährt er Umkehr /\\
 und tröstet die Hoffnungslosen /\\
 [und bestimmte sie für ein Leben in der Wahrheit]. ^{[[#fn9][9]]}\\
\\

<<v25>>
25 Wende dich zum Herrn, lass ab von der Sünde, /\\
 bete vor ihm und beseitige das Ärgernis!\\
\\

<<v26>>
26 Kehre zum Höchsten zurück und wende dich ab vom Bösen, /\\
 hasse stets das Schlechte!\\
\\

<<v27>>
27 Wer wird in der Unterwelt den Höchsten loben /\\
 anstelle derer, die leben und ihn preisen?
^{[[#fn10][10]][[#fn11][11]]}\\
\\

<<v28>>
28 Beim Toten, der nicht mehr ist, verstummt der Lobgesang; /\\
 nur der Lebende und Gesunde preist den Herrn. ^{[[#fn12][12]]}\\
\\

<<v29>>
29 Wie groß ist das Erbarmen des Herrn /\\
 und seine Nachsicht gegen alle, die umkehren zu ihm.\\
\\

<<v30>>
30 Denn nicht wie Gott ist der Mensch, /\\
 Gottes Gedanken sind nicht wie die Gedanken der Menschen.
^{[[#fn13][13]][[#fn14][14]]}\\
\\

<<v31>>
31 Was ist heller als die Sonne? /\\
 Und selbst sie verfinstert sich; /\\
 so ist auch das Begehren von Fleisch und Blut böse.\\
\\

<<v32>>
32 Das Heer in der Höhe zieht er zur Rechenschaft, /\\
 erst recht die Menschen, die nur Staub und Asche sind.
^{[[#fn15][15]][[#fn16][16]]}\\
\\

^{[[#fnm1][1]]} ℘ 40,11; Gen 3,19

^{[[#fnm2][2]]} ℘ (3-4) Gen 1,26; 9,2; Weish 9,2f

^{[[#fnm3][3]]} Entfällt (später Zusatz).

^{[[#fnm4][4]]} 6-10: Text verderbt; aus den alten Übersetzungen
erschlossen.

^{[[#fnm5][5]]} ℘ 45,5

^{[[#fnm6][6]]} ℘ Ex 24,8

^{[[#fnm7][7]]} 16.18.21: Zusätze aus verschiedenen G-Handschriften.

^{[[#fnm8][8]]} Die Vergeltung im Gericht bezieht sich natürlich auf die
Sünder von V. 20.

^{[[#fnm9][9]]} Die schroffe Unterscheidung zwischen Guten und Bösen
wird abgeschwächt durch eine weitere Gruppe von Menschen: die
Reumütigen. 24c: Nur in Vg überliefert.

^{[[#fnm10][10]]} ℘ Jes 38,18f

^{[[#fnm11][11]]} 27f: Vgl. die Anmerkung zu 14,16b. In Verbindung mit
V. 26 wird gesagt, dass nur im irdischen Leben Umkehr und
Gottesverehrung möglich sind.

^{[[#fnm12][12]]} ℘ Ps 115,17f; Bar 2,17f

^{[[#fnm13][13]]} ℘ Jes 55,8

^{[[#fnm14][14]]} Übersetzung vorwiegend nach S.

^{[[#fnm15][15]]} ℘ Ijob 4,18; 25,5f

^{[[#fnm16][16]]} Das «Heer in der Höhe» sind, im Anschluss an die Sonne
in V. 31, die Sterne, die man als eine Heerschar personifizierte und in
die Nähe der Engel rückte (vgl. Ri 5,20; Ijob 38,7; Jes 24,21; Bar
3,34f).
