:PROPERTIES:
:ID:       813f7cc1-8b5d-4e62-b005-29138d234fdf
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_4.html][4]] [[file:Sir_5.html][5]]
*6* [[file:Sir_7.html][7]] [[file:Sir_8.html][8]] ...
[[file:Sir_51.html][51]]

--------------

* Sir 6
  :PROPERTIES:
  :CUSTOM_ID: sir-6
  :END:

<<verses>>

<<v1>>
1 Schlimmen Ruf und Schande erntet die schmähsüchtige Frau, /\\
 ebenso schlecht ist der doppelzüngige Mann.\\
\\

<<v2>>
2 Verfall nicht der Macht deiner Gier; /\\
 sie wird wie ein Stier deine Kraft abweiden.\\
\\

<<v3>>
3 Dein Laub wird sie fressen, deine Früchte verderben /\\
 und dich zurücklassen wie einen dürren Baum.\\
\\

<<v4>>
4 Freche Gier richtet ihre Opfer zugrunde /\\
 und macht sie zum Gespött des Feindes.\\
\\

<<v5>>
**** Die Freundschaft: 6,5-17
     :PROPERTIES:
     :CUSTOM_ID: die-freundschaft-65-17
     :END:
5 Sanfte Rede erwirbt viele Freunde, /\\
 freundliche Lippen sind willkommen. ^{[[#fn1][1]]}\\
\\

<<v6>>
6 Viele seien es, die dich grüßen, /\\
 dein Vertrauter aber sei nur einer aus tausend.\\
\\

<<v7>>
7 Willst du einen Freund gewinnen, /\\
 gewinne ihn durch Erprobung, /\\
 schenk ihm nicht zu schnell dein Vertrauen! ^{[[#fn2][2]]}\\
\\

<<v8>>
8 Mancher ist Freund je nach der Zeit, /\\
 am Tag der Not hält er nicht stand.\\
\\

<<v9>>
9 Mancher Freund wird zum Feind, /\\
 unter Schmähungen deckt er den Streit mit dir auf.\\
\\

<<v10>>
10 Mancher ist Freund als Gast am Tisch, /\\
 am Tag des Unheils ist er nicht zu finden. ^{[[#fn3][3]]}\\
\\

<<v11>>
11 In deinem Glück ist er eins mit dir, /\\
 in deinem Unglück trennt er sich von dir. ^{[[#fn4][4]]}\\
\\

<<v12>>
12 Trifft dich ein Unglück, wendet er sich gegen dich /\\
 und hält sich vor dir verborgen.\\
\\

<<v13>>
13 Von deinen Feinden halte dich fern, /\\
 vor deinen Freunden sei auf der Hut!\\
\\

<<v14>>
14 Ein treuer Freund ist wie ein festes Zelt; /\\
 wer einen solchen findet, hat einen Schatz gefunden.\\
\\

<<v15>>
15 Für einen treuen Freund gibt es keinen Preis, /\\
 nichts wiegt seinen Wert auf.\\
\\

<<v16>>
16 Das Leben ist geborgen bei einem treuen Freund, /\\
 ihn findet, wer Gott fürchtet. ^{[[#fn5][5]]}\\
\\

<<v17>>
17 Wer den Herrn fürchtet, hält rechte Freundschaft, /\\
 wie er selbst, so ist auch sein Freund.\\
\\

<<v18>>
**** Der Weg zur Weisheit: 6,18-37
     :PROPERTIES:
     :CUSTOM_ID: der-weg-zur-weisheit-618-37
     :END:
18 Mein Sohn, lerne Zucht von Jugend an /\\
 und du wirst Weisheit gewinnen, bis du ergraut bist.\\
\\

<<v19>>
19 Wie ein Pflüger und Schnitter geh auf sie zu /\\
 und warte auf ihren reichen Ertrag! Du wirst in ihrem Dienst nur wenig
Mühe haben /\\
 und bald ihre Früchte genießen.\\
\\

<<v20>>
20 Rau ist sie für den Toren, /\\
 wer ohne Einsicht ist, erträgt sie nicht.\\
\\

<<v21>>
21 Wie ein schwerer Stein lastet sie auf ihm, /\\
 er zögert nicht, sie abzuwerfen.\\
\\

<<v22>>
22 Denn die Zucht ist wie ihr Name, /\\
 vielen ist sie unbequem.\\
\\

<<v23>>
23 Höre, mein Sohn, nimm meine Lehre an, /\\
 verschmäh nicht meinen Rat!\\
\\

<<v24>>
24 Bring deine Füße in ihre Fesseln, /\\
 deinen Hals unter ihr Joch!\\
\\

<<v25>>
25 Beuge deinen Nacken und trage sie, /\\
 werde ihrer Stricke nicht überdrüssig! ^{[[#fn6][6]]}\\
\\

<<v26>>
26 Mit ganzem Herzen schreite auf sie zu, /\\
 mit voller Kraft halte ihre Wege ein!\\
\\

<<v27>>
27 Frage und forsche, suche und finde! /\\
 Hast du sie erfasst, lass sie nicht wieder los!\\
\\

<<v28>>
28 Denn schließlich wirst du bei ihr Ruhe finden, /\\
 sie wandelt sich dir in Freude.\\
\\

<<v29>>
29 Ihre Fessel wird dir zum sicheren Schutz, /\\
 ihre Stricke werden zu goldenen Gewändern.\\
\\

<<v30>>
30 Ein Goldschmuck ist ihr Joch, /\\
 ihre Garne sind ein Purpurband.\\
\\

<<v31>>
31 Als Prachtgewand kannst du sie anlegen, /\\
 sie aufsetzen als herrliche Krone. ^{[[#fn7][7]]}\\
\\

<<v32>>
32 Wenn du willst, mein Sohn, kannst du weise werden, /\\
 du wirst klug, wenn du dein Herz darauf richtest.\\
\\

<<v33>>
33 Bist du bereit zu hören, so wirst du belehrt, /\\
 neigst du dein Ohr, erlangst du Bildung.\\
\\

<<v34>>
34 Verweile gern im Kreis der Alten, /\\
 wer weise ist, dem schließ dich an!\\
\\

<<v35>>
35 Lausche gern jeder ernsten Rede, /\\
 keinen Weisheitsspruch lass dir entgehen!\\
\\

<<v36>>
36 Achte auf den, der Weisheit hat, und suche ihn auf; /\\
 dein Fuß trete seine Türschwelle aus.\\
\\

<<v37>>
37 Achte auf die Furcht vor dem Herrn, /\\
 sinn allezeit über seine Gebote nach! Dann gibt er deinem Herzen
Einsicht, /\\
 er macht dich weise, wie du es begehrst. ^{[[#fn8][8]]}\\
\\

^{[[#fnm1][1]]} ℘ Spr 15,4

^{[[#fnm2][2]]} ℘ 19,4

^{[[#fnm3][3]]} ℘ 37,4; Spr 19,4

^{[[#fnm4][4]]} 11b: G: und gegen deine Sklaven tritt er freimütig auf.

^{[[#fnm5][5]]} 16a: Wörtlich: Ein treuer Freund ist ein Beutel des
Lebens. Zu diesem Bild vgl. die Anmerkung zu 1 Sam 25,29. Wie eine
Kostbarkeit in einem Beutel verborgen wird, so ist das Leben bei Gott
und bei einem Freund gut aufgehoben.

^{[[#fnm6][6]]} ℘ 51,26

^{[[#fnm7][7]]} ℘ Spr 4,9

^{[[#fnm8][8]]} ℘ Ps 1,2
