#+TITLE: Sir 17 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-05 So 17:37]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 17.html

* Sir 17

<<verses>>

<<v1>>
1 Der Herr hat die Menschen aus Erde erschaffen /\\
 und lässt sie wieder zu ihr zurückkehren. [fn:1]\\
\\

<<v2>>
2 Gezählte Tage und eine bestimmte Zeit wies er ihnen zu /\\
 und gab ihnen Macht über alles auf der Erde.\\
\\

<<v3>>
3 Ihm selbst ähnlich hat er sie mit Kraft bekleidet /\\
 und sie nach seinem Abbild erschaffen. [fn:2]\\
\\

<<v4>>
4 Auf alle Wesen legte er die Furcht vor ihnen, /\\
 über Tiere und Vögel sollten sie herrschen.

<<v5>>
5 [fn:3]\\
\\

<<v6>>
6 Er bildete ihnen Mund und Zunge, Auge und Ohr /\\
 und ein Herz zum Denken gab er ihnen. [fn:4]\\
\\

<<v7>>
7 Mit kluger Einsicht erfüllte er sie /\\
 und lehrte sie, Gutes und Böses zu erkennen.\\
\\

<<v8>>
8 Er zeigte ihnen die Größe seiner Werke, /\\
 um die Furcht vor ihm in ihr Herz zu pflanzen.\\
\\

<<v9>>
9 Sie sollten für immer seine Wunder rühmen /\\
\\

<<v10>>
10 und seinen heiligen Namen loben.\\
\\

<<v11>>
* Die Erwählung Israels: 17,11-23

11 Er hat ihnen Weisheit geschenkt /\\
 und ihnen das Leben spendende Gesetz gegeben. [fn:5]\\
\\

<<v12>>
12 Einen ewigen Bund hat er mit ihnen geschlossen /\\
 und ihnen seine Gebote mitgeteilt. [fn:6]\\
\\

<<v13>>
13 Ihre Augen sahen seine machtvolle Herrlichkeit, /\\
 ihr Ohr vernahm seine gewaltige Stimme.\\
\\

<<v14>>
14 Er sprach zu ihnen: Hütet euch vor allem Unrecht! /\\
 Er schrieb ihnen ihr Verhalten gegenüber dem Nächsten vor.\\
\\

<<v15>>
15 Ihre Wege liegen allezeit offen vor ihm, /\\
 sie sind nicht verborgen vor seinen Augen.\\
\\

<<v16>>
16 [] [fn:7]\\
\\

<<v17>>
17 Für jedes Volk bestellte er einen Herrscher, /\\
 Israel aber ist der Erbbesitz des Herrn.\\
\\

<<v18>>
18 []\\
\\

<<v19>>
19 Alle ihre Taten stehen vor ihm wie die Sonne, /\\
 seine Augen ruhen stets auf ihren Wegen.\\
\\

<<v20>>
20 Ihre Frevel sind vor ihm nicht verborgen, /\\
 alle ihre Sünden stehen dem Herrn vor Augen.\\
\\

<<v21>>
21 []\\
\\

<<v22>>
22 Das Almosen eines jeden ist bei ihm wie ein Siegelring, /\\
 des Menschen Wohltat behütet er wie einen Augapfel.\\
\\

<<v23>>
23 Schließlich erhebt er sich und vergilt ihnen, /\\
 er lässt die Vergeltung über ihr Haupt kommen. [fn:8]\\
\\

<<v24>>
* Reue und Umkehr: 17,24-32

24 Den Reumütigen aber gewährt er Umkehr /\\
 und tröstet die Hoffnungslosen /\\
 [und bestimmte sie für ein Leben in der Wahrheit]. [fn:9]\\
\\

<<v25>>
25 Wende dich zum Herrn, lass ab von der Sünde, /\\
 bete vor ihm und beseitige das Ärgernis!\\
\\

<<v26>>
26 Kehre zum Höchsten zurück und wende dich ab vom Bösen, /\\
 hasse stets das Schlechte!\\
\\

<<v27>>
27 Wer wird in der Unterwelt den Höchsten loben /\\
 anstelle derer, die leben und ihn preisen? [fn:10] [fn:11]\\
\\

<<v28>>
28 Beim Toten, der nicht mehr ist, verstummt der Lobgesang; /\\
 nur der Lebende und Gesunde preist den Herrn. [fn:12]\\
\\

<<v29>>
29 Wie groß ist das Erbarmen des Herrn /\\
 und seine Nachsicht gegen alle, die umkehren zu ihm.\\
\\

<<v30>>
30 Denn nicht wie Gott ist der Mensch, /\\
 Gottes Gedanken sind nicht wie die Gedanken der Menschen. [fn:13] [fn:14]\\
\\

<<v31>>
31 Was ist heller als die Sonne? /\\
 Und selbst sie verfinstert sich; /\\
 so ist auch das Begehren von Fleisch und Blut böse.\\
\\

<<v32>>
32 Das Heer in der Höhe zieht er zur Rechenschaft, /\\
 erst recht die Menschen, die nur Staub und Asche sind. [fn:15] [fn:16]\\
\\

* Footnotes

[fn:1] [[file:Sir_40.org::v11][40,11]]; [[file:Gen_3.org::v19][Gen 3,19]]

[fn:2] (3-4) [[file:Gen_1.org::v26][Gen 1,26]]; [[file:Gen_9.org::v2][9,2]]; [[file:Weish_9.org::v2][Weish 9,2f]]

[fn:3] Entfällt (später Zusatz).

[fn:4] 6-10: Text verderbt; aus den alten Übersetzungen erschlossen.

[fn:5] [[file:Sir_45.org::v5][45,5]]

[fn:6] [[file:Ex_24.org::v8][Ex 24,8]]

[fn:7] 16.18.21: Zusätze aus verschiedenen G-Handschriften.

[fn:8] Die Vergeltung im Gericht bezieht sich natürlich auf die Sünder von V. 20.

[fn:9] Die schroffe Unterscheidung zwischen Guten und Bösen wird abgeschwächt durch eine weitere Gruppe von Menschen: die Reumütigen. 24c: Nur in Vg überliefert.

[fn:10] [[file:Jes_38.org::v18][Jes 38,18f]]

[fn:11] 27f: Vgl. die Anmerkung zu 14,16b. In Verbindung mit V. 26 wird gesagt, dass nur im irdischen Leben Umkehr und Gottesverehrung möglich sind.

[fn:12] [[file:Ps_115.org::v17][Ps 115,17f]]; [[file:Bar_2.org::v17][Bar 2,17f]]

[fn:13] [[file:Jes_55.org::v8][Jes 55,8]]

[fn:14] Übersetzung vorwiegend nach S.

[fn:15] [[file:Ijob_4.org::v18][Ijob 4,18]]; [[file:Ijob_25.org::v5][25,5f]]

[fn:16] Das «Heer in der Höhe» sind, im Anschluss an die Sonne in V. 31, die Sterne, die man als eine Heerschar personifizierte und in die Nähe der Engel rückte (vgl. [[file:Ri_5.org::v20][Ri 5,20]]; [[file:Ijob_38.org::v7][Ijob 38,7]]; [[file:Jes_24.org::v21][Jes 24,21]]; [[file:Bar_3.org::v34][Bar 3,34f]]).
