#+TITLE: Sir 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-02 Do 08:24]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 9.html

* Sir 9

<<verses>>

<<v1>>
* Der rechte Umgang mit Frauen: 9,1-9

1 Sei nicht eifersüchtig gegen die Frau an deiner Brust, /\\
 damit sie nicht auf böse Gedanken gegen dich selbst kommt.\\
\\

<<v2>>
2 Liefere dich nicht einer Frau aus, /\\
 damit sie nicht Gewalt bekommt über dich.\\
\\

<<v3>>
3 Nah dich nicht einer fremden Frau, /\\
 damit du nicht in ihre Netze fällst. [fn:1]\\
\\

<<v4>>
4 Verkehr nicht mit einer Saitenspielerin, /\\
 damit du nicht durch ihre Töne gefangen wirst. [fn:2]\\
\\

<<v5>>
5 Denk nicht zu viel an ein Mädchen, /\\
 damit du nicht seinetwegen der Strafe verfällst. [fn:3] [fn:4]\\
\\

<<v6>>
6 Gib dich nicht mit einer Dirne ab, /\\
 damit sie dich nicht um dein Erbe bringt. [fn:5]\\
\\

<<v7>>
7 Schau nicht umher auf den Wegen zur Stadt, /\\
 streif nicht umher in ihren abgelegenen Winkeln!\\
\\

<<v8>>
8 Verhüll dein Auge vor einer reizvollen Frau, /\\
 blick nicht auf eine Schönheit, die dir nicht gehört. Wegen einer Frau
kamen schon viele ins Verderben, /\\
 sie versengt ihre Liebhaber wie Feuer. [fn:6]\\
\\

<<v9>>
9 Streck dich nicht mit einer Verheirateten zum Weingelage hin, /\\
 sitz nicht berauscht mit ihr zusammen, /\\
 damit du ihr nicht dein Herz zuneigst und verblutend ins Grab sinkst.\\
\\

<<v10>>
* Der rechte Umgang von Mann zu Mann: 9,10-18

10 Gib einen alten Freund nicht auf; /\\
 denn ein neuer hält nicht zu dir. Neuer Freund, neuer Wein: /\\
 Nur alt trinkst du ihn gern.\\
\\

<<v11>>
11 Sei nicht neidisch auf einen bösen Menschen; /\\
 denn du weißt nicht, wann sein Tag ihn erreicht. [fn:7]\\
\\

<<v12>>
12 Liebäugle nicht mit einem übermütigen Menschen, der Erfolg hat, /\\
 bedenk, dass er nicht bis zum Tod straflos bleibt.\\
\\

<<v13>>
13 Bleib dem Menschen fern, der Macht hat zu töten, /\\
 und setz dich nicht Todesängsten aus! Nahst du dich ihm, so verfehle
dich nicht, /\\
 sonst nimmt er dir das Leben. Wisse, dass du dich zwischen Schlingen
bewegst /\\
 und über eine Fanggrube schreitest. [fn:8] [fn:9]\\
\\

<<v14>>
14 Antworte deinem Nächsten, so gut du kannst, /\\
 du selbst aber berate dich mit Weisen!\\
\\

<<v15>>
15 Stell deine Überlegung zusammen mit Verständigen an /\\
 und berate alles in ihrem Kreis! [fn:10] [fn:11]\\
\\

<<v16>>
16 Gerechte Männer seien deine Tischgenossen, /\\
 dein Ruhm bestehe in der Gottesfurcht. [fn:12]\\
\\

<<v17>>
17 Die Hände der Weisen fassen das Richtige an, /\\
 ein redegewandter Weiser ist Herrscher in seinem Volk. [fn:13] [fn:14]\\
\\

<<v18>>
18 Gefürchtet in der Stadt ist der Schwätzer, /\\
 ein prahlerischer Mund ist verhasst.\\
\\


* Footnotes

[fn:1] [[file:Spr_2.org::v16][Spr 2,16]]

[fn:2] [[file:Spr_6.org::v25][Spr 6,25]]

[fn:3] [[file:Ijob_31.org::v1][Ijob 31,1]]

[fn:4] 5b: Der Verfasser hat vor allem die materiellen und sozialen Nachteile im Auge (vgl. [[file:Ex_22.org::v15][Ex 22,15f]]; [[file:Dtn_22.org::v29][Dtn 22,29]]). Sittliche Beweggründe sind oft weniger wirkungsvoll.

[fn:5] [[file:Spr_5.org::v10][Spr 5,10]]; [[file:Spr_29.org::v3][29,3]]

[fn:6] [[file:Spr_5.org::v5][Spr 5,5]]

[fn:7] [[file:Ps_37.org::v13][Ps 37,13]]

[fn:8] [[file:Spr_29.org::v5][Spr 29,5]]

[fn:9] Es ist wohl an die heidnischen Herrscher Ägyptens oder Syriens gedacht, die wegen ihrer Willkür und Grausamkeit bekannt waren.

[fn:10] [[file:Sir_6.org::v34][6,34-37]]

[fn:11] 15b: G: und berate alles nach dem Gesetz des Höchsten!

[fn:12] [[file:Sir_10.org::v22][10,22]]; [[file:Sir_25.org::v6][25,6]]

[fn:13] [[file:Sir_20.org::v27][20,27]]

[fn:14] 17a: Text unsicher; G, kaum richtig: Ein Werk aus Künstlerhand findet Lob.
