:PROPERTIES:
:ID:       f80826fd-61bc-4f46-bd52-c3bfc655e718
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_27.html][27]]
[[file:Sir_28.html][28]] *29* [[file:Sir_30.html][30]]
[[file:Sir_31.html][31]] ... [[file:Sir_51.html][51]]

--------------

* Sir 29
  :PROPERTIES:
  :CUSTOM_ID: sir-29
  :END:

<<verses>>

<<v1>>
**** Borgen und Bürgen: 29,1-20
     :PROPERTIES:
     :CUSTOM_ID: borgen-und-bürgen-291-20
     :END:
1 Wer dem Nächsten borgt, erweist Liebe, /\\
 wer ihm unter die Arme greift, erfüllt die Gebote.
^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v2>>
2 Borge dem Nächsten, wenn er in Not ist, /\\
 doch gib dem Nächsten auch zurück zur rechten Zeit!\\
\\

<<v3>>
3 Halte dein Wort und sei treu gegen ihn, /\\
 dann bekommst du stets, was du nötig hast.\\
\\

<<v4>>
4 Viele Schuldner bitten um ein Darlehen, /\\
 doch dann verärgern sie ihre Helfer.\\
\\

<<v5>>
5 Bis er etwas bekommt, küsst er dem andern die Hand /\\
 und redet mit ihm unterwürfig wegen seines Geldes. Am Tag der
Rückzahlung aber enttäuscht er ihn, /\\
 weil er erst nach langer Zeit zurückerstattet.\\
\\

<<v6>>
6 Ist er auch zahlungsfähig, bringt er kaum die Hälfte /\\
 und betrachtet es wie einen Fund; ist er es nicht, bringt er ihn um
sein Geld /\\
 und macht sich ihn leichtfertig zum Feind. Fluchen und Schimpfen zahlt
er ihm zurück, /\\
 statt mit Ehre vergilt er mit Schmach.\\
\\

<<v7>>
7 Viele sind nicht aus Härte zurückhaltend, /\\
 sie fürchten nur unnötigen Ärger.\\
\\

<<v8>>
8 Hab dennoch Geduld mit dem Bedürftigen /\\
 und lass ihn nicht auf die Wohltat warten!\\
\\

<<v9>>
9 Um des Gebotes willen nimm dich des Armen an, /\\
 lass ihn in seiner Not nicht leer weggehen!\\
\\

<<v10>>
10 Setz dein Geld ein für den Bruder und Freund, /\\
 lass es nicht rosten unter dem Stein, bis es verdirbt.\\
\\

<<v11>>
11 Leg dir einen Schatz an nach den Geboten des Höchsten; /\\
 der wird dir mehr nützen als Gold.\\
\\

<<v12>>
12 Wohltaten verschnüre und leg sie in deine Vorratskammer, /\\
 sie werden dich retten aus allem Unheil. ^{[[#fn3][3]]}\\
\\

<<v13>>
13 Besser als ein fester Schild und eine schwere Lanze /\\
 werden sie für dich gegen den Feind streiten.\\
\\

<<v14>>
14 Der gute Mensch bürgt für den Nächsten; /\\
 nur wer die Scham verloren hat, flieht vor seinem Bürgen.
^{[[#fn4][4]][[#fn5][5]]}\\
\\

<<v15>>
15 Vergiss nie die Gefälligkeit des Bürgen, /\\
 gab er doch sich selbst für dich hin.\\
\\

<<v16>>
16 Der Sünder missachtet die Gefälligkeit des Bürgen, / ^{[[#fn6][6]]}\\
\\

<<v17>>
17 doch seinen Schöpfer missachtet, /\\
 wer seinen Helfer missachtet. ^{[[#fn7][7]]}\\
\\

<<v18>>
18 Bürgschaft hat schon viele Vermögende zugrunde gerichtet, /\\
 hat sie umhergeworfen wie eine Woge im Meer; reiche Männer hat sie
heimatlos gemacht, /\\
 sodass sie umherirrten bei fremden Völkern.\\
\\

<<v19>>
19 Der Sünder wird in Bürgschaft verwickelt, /\\
 wer trüben Geschäften nachjagt, fällt in Prozesse.\\
\\

<<v20>>
20 Steh für den Nächsten ein, so gut du kannst, /\\
 doch sei auf der Hut, dass du nicht hereinfällst.\\
\\

<<v21>>
**** Heimat und Fremde: 29,21-28
     :PROPERTIES:
     :CUSTOM_ID: heimat-und-fremde-2921-28
     :END:
21 Das Wichtigste zum Leben sind Brot und Wasser, /\\
 Kleidung und Wohnung, um die Blöße zu bedecken.\\
\\

<<v22>>
22 Besser das Leben eines Armen unter schützendem Dach /\\
 als köstliche Leckerbissen in der Fremde.\\
\\

<<v23>>
23 Ob wenig oder viel, sei zufrieden, /\\
 dann hörst du keinen Vorwurf in der Fremde.\\
\\

<<v24>>
24 Schlimm ist ein Leben von einem Haus zum andern; /\\
 wo du fremd bist, darfst du den Mund nicht auftun.\\
\\

<<v25>>
25 Ohne Dank reichst du Trank und Speise /\\
 und musst noch bittere Worte hören: ^{[[#fn8][8]]}\\
\\

<<v26>>
26 Komm, Fremder, deck den Tisch, /\\
 und wenn du etwas hast, gib mir zu essen!\\
\\

<<v27>>
27 Fort, Fremder, ich habe eine Ehrenpflicht: /\\
 Ein Bruder kam zu Gast, ich brauche das Haus.\\
\\

<<v28>>
28 Für einen Mann mit Bildung ist es hart, /\\
 geschmäht zu werden, wenn man in der Fremde lebt, /\\
 oder beschimpft zu werden, wenn man einem geborgt hat.\\
\\

^{[[#fnm1][1]]} ℘ Ps 37,26; 112,5

^{[[#fnm2][2]]} 1b: Zum Borgen als Gebot vgl. V. 9 und V. 11 und Dtn
15,7-11.

^{[[#fnm3][3]]} ℘ 3,30; 17,22

^{[[#fnm4][4]]} ℘ 8,13; Spr 6,1-5

^{[[#fnm5][5]]} 14-20: Viele Sprichwörter empfehlen zwar, dem Nächsten
in der Not auszuhelfen, mahnen aber auch zur nötigen Vorsicht.

^{[[#fnm6][6]]} 16f: Nach S; G: Die Güter des Bürgen verwüstet der
Sünder und der in seiner Gesinnung Undankbare lässt seinen Retter im
Stich.

^{[[#fnm7][7]]} ℘ Spr 17,5

^{[[#fnm8][8]]} 25a: Nach G; S: Ein Fremdling bist du und trinkst
Schmach.
