:PROPERTIES:
:ID:       e5923729-ae10-49f1-bf2f-b6dea601d0f4
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_42.html][42]]
[[file:Sir_43.html][43]] *44* [[file:Sir_45.html][45]]
[[file:Sir_46.html][46]] ... [[file:Sir_51.html][51]]

--------------

* Sir 44
  :PROPERTIES:
  :CUSTOM_ID: sir-44
  :END:

<<verses>>

<<v1>>
**** Das Lob der Väter Israels: 44,1-15
     :PROPERTIES:
     :CUSTOM_ID: das-lob-der-väter-israels-441-15
     :END:
1 Die ehrwürdigen Männer will ich preisen, /\\
 unsere Väter, wie sie aufeinander folgten. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Viel Ehre hat der Höchste ausgeteilt, /\\
 viel von seiner Größe, seit den Tagen der Vorzeit:\\
\\

<<v3>>
3 Männer, die über die Erde als Könige herrschten /\\
 und die berühmt waren durch ihre Macht; die Rat erteilten durch ihre
Einsicht, /\\
 die prophetisch alle Dinge erschauten; ^{[[#fn2][2]]}\\
\\

<<v4>>
4 Fürsten des Volkes wegen ihrer Klugheit, /\\
 angesehen wegen ihres Scharfsinns; redekundig durch ihre Kenntnis der
Schriften, /\\
 Lehrer von Sinnsprüchen durch ihre Lebenserfahrung;\\
\\

<<v5>>
5 Dichter von Liedern in Versmaß, /\\
 Verfasser von geschriebenen Sinnsprüchen;\\
\\

<<v6>>
6 tüchtige Männer, auf Macht gestützt, /\\
 unbehelligt in ihrem Wohnsitz:\\
\\

<<v7>>
7 Sie alle waren geehrt zu ihrer Zeit /\\
 und ihr Ruhm blühte in ihren Tagen.\\
\\

<<v8>>
8 Manche hinterließen einen Namen, /\\
 sodass man ihr Lob weitererzählte. ^{[[#fn3][3]]}\\
\\

<<v9>>
9 Andere blieben ohne Nachruhm; /\\
 sie sind erloschen, sobald sie starben. Sie sind, als wären sie nie
gewesen, /\\
 und ebenso auch ihre Kinder. ^{[[#fn4][4]]}\\
\\

<<v10>>
10 Jene aber sind die ehrwürdigen Männer, /\\
 deren Hoffnung nicht vergeht.\\
\\

<<v11>>
11 Bei ihren Nachkommen bleibt ihr Gut, /\\
 ihr Erbe bei ihren Enkeln.\\
\\

<<v12>>
12 Ihre Nachkommen halten fest an ihrem Bund /\\
 und ebenso ihre Kinder, um der Väter willen.\\
\\

<<v13>>
13 Ihre Nachkommen haben für immer Bestand, /\\
 ihr Ruhm wird niemals ausgelöscht. ^{[[#fn5][5]]}\\
\\

<<v14>>
14 Ihr Leib ist in Frieden bestattet, /\\
 ihr Name lebt fort von Geschlecht zu Geschlecht.\\
\\

<<v15>>
15 Von ihrer Weisheit erzählt die Gemeinde, /\\
 ihr Lob verkündet das versammelte Volk. ^{[[#fn6][6]]}\\
\\

<<v16>>
**** Das Beispiel Henochs: 44,16
     :PROPERTIES:
     :CUSTOM_ID: das-beispiel-henochs-4416
     :END:
16 Henoch ging seinen Weg mit dem Herrn und wurde entrückt: /\\
 ein Beispiel der Gotteserkenntnis für alle Zeiten. ^{[[#fn7][7]]}\\
\\

<<v17>>
**** Das Vorbild Noachs: 44,17-18
     :PROPERTIES:
     :CUSTOM_ID: das-vorbild-noachs-4417-18
     :END:
17 Der gerechte Noach wurde untadelig befunden, /\\
 zur Zeit des Untergangs war er ein neuer Anfang. Durch ihn blieb ein
Rest erhalten, /\\
 der Bund mit ihm beendete die Sintflut. ^{[[#fn8][8]]}\\
\\

<<v18>>
18 Ein ewiger Bund wurde mit ihm geschlossen: /\\
 Nie wieder sollte alles Leben vernichtet werden. ^{[[#fn9][9]]}\\
\\

<<v19>>
**** Die Bedeutung Abrahams: 44,19-21
     :PROPERTIES:
     :CUSTOM_ID: die-bedeutung-abrahams-4419-21
     :END:
19 Abraham wurde der Vater vieler Völker, /\\
 seine Ehre blieb makellos. ^{[[#fn10][10]]}\\
\\

<<v20>>
20 Er hielt das Gebot des Höchsten /\\
 und trat in einen Bund mit ihm. Wie ihm befohlen wurde, hat er sich
beschnitten; /\\
 in der Prüfung wurde er treu befunden. ^{[[#fn11][11]]}\\
\\

<<v21>>
21 Darum hat ihm Gott mit einem Eid zugesichert, /\\
 durch seine Nachkommen die Völker zu segnen, sie zahlreich zu machen
wie den Staub auf der Erde /\\
 und seine Nachkommen zu erhöhen wie die Sterne, ihnen Besitz zu geben
von Meer zu Meer, /\\
 vom Eufrat bis an die Grenzen der Erde. ^{[[#fn12][12]]}\\
\\

<<v22>>
**** Der Segen Isaaks und Jakobs: 44,22-23
     :PROPERTIES:
     :CUSTOM_ID: der-segen-isaaks-und-jakobs-4422-23
     :END:
22 Das Gleiche sicherte er Isaak zu /\\
 um Abrahams, seines Vaters willen. ^{[[#fn13][13]]}\\
\\

<<v23>>
23 Den Bund mit allen Vorfahren übertrug er auf ihn. /\\
 Auch auf Israels Haupt ruhte der Segen. Er bestätigte ihm die
Erstgeburt /\\
 und übergab ihm sein Erbe. Er bestimmte es für die Stämme, /\\
 zum Anteil für die Zwölf. Er ließ von ihm einen Mann abstammen, /\\
 der bei allen Lebenden in Ansehen stand:
^{[[#fn14][14]][[#fn15][15]]}\\
\\

^{[[#fnm1][1]]} Zur natürlichen Offenbarung kommt die Offenbarung in der
Heilsgeschichte Israels. Die folgende «Biblische Geschichte» beginnt mit
Henoch und reicht bis zum Hohenpriester Simeon, der zur Zeit des
Verfassers lebte.

^{[[#fnm2][2]]} 3-6: Die zwölf Ehrentitel können nicht auf bestimmte
Einzelgestalten bezogen werden.

^{[[#fnm3][3]]} ℘ (8-9) Koh 2,16

^{[[#fnm4][4]]} Dass es im Verlauf der Geschichte auch Versager gab,
wird als Kontrast kurz erwähnt. Betont wird, dass auch die Nachkommen am
Segen oder am Unheil ihrer Väter teilhaben.

^{[[#fnm5][5]]} ℘ 39,9

^{[[#fnm6][6]]} ℘ 39,10

^{[[#fnm7][7]]} ℘ Gen 5,24; Hebr 11,5

^{[[#fnm8][8]]} ℘ Gen 6,9

^{[[#fnm9][9]]} ℘ Gen 8,21; 9,9-11

^{[[#fnm10][10]]} ℘ Gen 17,4f

^{[[#fnm11][11]]} ℘ Gen 15,18; 17,24; 22,1-19; Hebr 11,8

^{[[#fnm12][12]]} ℘ Gen 12,3; 13,16; 15,5.18

^{[[#fnm13][13]]} ℘ Gen 17,19

^{[[#fnm14][14]]} ℘ Gen 27,27-29; 35,12; Ex 2,1f

^{[[#fnm15][15]]} 23c: Andere Übersetzungsmöglichkeit nach G: Er
erkannte (= bevorzugte) ihn in seinen Segnungen.
