:PROPERTIES:
:ID:       18b4986d-8968-46e8-8d08-c43b45e0a295
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_21.html][21]]
[[file:Sir_22.html][22]] *23* [[file:Sir_24.html][24]]
[[file:Sir_25.html][25]] ... [[file:Sir_51.html][51]]

--------------

* Sir 23
  :PROPERTIES:
  :CUSTOM_ID: sir-23
  :END:

<<verses>>

<<v1>>
1 Herr, Vater und Gebieter meines Lebens, /\\
 bring mich durch sie nicht zu Fall! ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Wer hält eine Peitsche bereit für mein Denken /\\
 und eine Zuchtrute für mein Herz, um ihre Vergehen nicht zu schonen /\\
 und ihnen keine Sünden zu gestatten,\\
\\

<<v3>>
3 damit meine Fehler sich nicht mehren, /\\
 meine Sünden sich nicht häufen /\\
 und ich nicht zu Fall komme vor meinen Feinden, /\\
 sodass mein Gegner sich über mich freuen könnte?\\
\\

<<v4>>
4 Herr, Vater und Gott meines Lebens, /\\
 überlass mich nicht ihrem Plan!\\
\\

<<v5>>
5 Übermütige Augen gib mir nicht, /\\
 halte fern von mir die Begierde!\\
\\

<<v6>>
6 Unzucht und Sinnenlust sollen mich nicht ergreifen, /\\
 schamloser Gier gib mich nicht preis!\\
\\

<<v7>>
**** Eine Unterweisung über das Reden: 23,7-15
     :PROPERTIES:
     :CUSTOM_ID: eine-unterweisung-über-das-reden-237-15
     :END:
7 Ihr Söhne, vernehmt die Unterweisung über das Reden; /\\
 wer sie beachtet, verfehlt sich nicht.\\
\\

<<v8>>
8 Durch seine Lippen verstrickt sich der Sünder, /\\
 Lästerer und Stolze stürzen durch sie.\\
\\

<<v9>>
9 Gewöhn deinen Mund nicht ans Schwören, /\\
 den Namen des Heiligen zu nennen, gewöhn dir nicht an! ^{[[#fn2][2]]}\\
\\

<<v10>>
10 Wie ein Sklave, der dauernd straffällig wird, /\\
 von Striemen nie frei bleibt, /\\
 so bleibt von Sünde nicht rein, /\\
 wer immerfort schwört und Gottes Namen ausspricht.\\
\\

<<v11>>
11 Ein Mensch, der viel schwört, häuft Schuld auf sich, /\\
 die Strafrute weicht nicht von seinem Haus. Verfehlt er sich unbedacht,
/\\
 lastet seine Sünde auf ihm; übersieht er den Schwur, sündigt er
doppelt, /\\
 schwört er falsch, bleibt er nicht ungestraft; /\\
 ja, sein Haus wird von Leiden erfüllt. ^{[[#fn3][3]]}\\
\\

<<v12>>
12 Es gibt ein Reden, das der Pest vergleichbar ist; /\\
 möge es sich im Erbland Jakobs nicht finden. Den Frommen liegt dies
alles fern, /\\
 sie wälzen sich nicht in Sünden.\\
\\

<<v13>>
13 Gewöhn deinen Mund nicht an Zuchtlosigkeit; /\\
 denn es kommt dabei zu sündhaften Reden.\\
\\

<<v14>>
14 Denk an Vater und Mutter, wenn du im Kreis der Großen sitzt, /\\
 damit du bei ihnen keinen Anstoß erregst /\\
 und nicht durch dein Benehmen dich zum Toren machst /\\
 und wünschen musst, nicht geboren zu sein, /\\
 und den Tag deiner Geburt verfluchst.\\
\\

<<v15>>
15 Hat sich einer an schändliche Reden gewöhnt, /\\
 nimmt er sein Leben lang keine Zucht mehr an.\\
\\

<<v16>>
**** Warnung vor Unzucht: 23,16-27
     :PROPERTIES:
     :CUSTOM_ID: warnung-vor-unzucht-2316-27
     :END:
16 Zwei Gruppen von Menschen häufen die Sünden, /\\
 drei ziehen den Zorn herbei: Leidenschaftliche Begierde, sie brennt wie
Feuer /\\
 und erlischt nicht, bis sie sich verzehrt hat; der Mensch, der am
eigenen Leib Unzucht treibt /\\
 und nicht aufhört, bis das Feuer verglüht;\\
\\

<<v17>>
17 der Wollüstige, dem jedes Brot süß schmeckt, /\\
 der nicht aufhört, bis er tot ist; ^{[[#fn4][4]]}\\
\\

<<v18>>
18 der Mensch, der Ehebruch treibt auf seinem Lager, /\\
 der bei sich denkt: Wer sieht mich? Dunkel umgibt mich, Wände verbergen
mich, /\\
 keiner sieht mich, warum sollte ich mich fürchten zu sündigen?\\
\\

<<v19>>
19 Er denkt nicht an den Höchsten, /\\
 nur die Augen der Menschen fürchtet er. Er bedenkt nicht, dass die
Augen des Herrn /\\
 zehntausendmal heller sind als die Sonne, dass sie alle Wege des
Menschen sehen /\\
 und die geheimsten Winkel durchdringen.\\
\\

<<v20>>
20 Schon ehe es geschieht, ist ihm alles bekannt, /\\
 ebenso, wenn es vollbracht ist.\\
\\

<<v21>>
21 Jener wird auf den Straßen der Stadt verurteilt; /\\
 wo er es nicht vermutet, da wird er ergriffen.\\
\\

<<v22>>
22 So auch die Frau, die ihren Mann verlässt /\\
 und von einem andern einen Erben zur Welt bringt:\\
\\

<<v23>>
23 Erstens war sie dem Gesetz des Höchsten untreu, /\\
 zweitens hat sie sich gegen ihren Gatten vergangen, drittens hat sie in
Unzucht die Ehe gebrochen /\\
 und von einem andern Kinder zur Welt gebracht. ^{[[#fn5][5]]}\\
\\

<<v24>>
24 Sie wird vor die Gemeinde geführt /\\
 und ihre Kinder werden es büßen müssen.\\
\\

<<v25>>
25 Ihre Sprösslinge werden keine Wurzel treiben /\\
 und ihre Zweige keine Frucht bringen.\\
\\

<<v26>>
26 Ihr Andenken hinterlässt sie zum Fluch, /\\
 ihre Schande wird niemals getilgt.\\
\\

<<v27>>
27 Alle Bewohner des Landes werden erkennen, /\\
 alle Nachkommen werden einsehen: Nichts ist besser als die Furcht vor
dem Herrn, /\\
 nichts süßer, als seine Gebote zu halten. ^{[[#fn6][6]][[#fn7][7]]}\\
\\

^{[[#fnm1][1]]} 1-6: Ein inniges Gebet um Lauterkeit bis in die
innersten Gedanken, was aber Wachsamkeit und die Hilfe Gottes
voraussetzt.

^{[[#fnm2][2]]} ℘ 27,14

^{[[#fnm3][3]]} Es werden verschiedene juristische Unterscheidungen
gemacht wie später bei Mt 5,34-37.

^{[[#fnm4][4]]} ℘ 26,12; Spr 7,5-27

^{[[#fnm5][5]]} ℘ Spr 2,17

^{[[#fnm6][6]]} ℘ 46,10; Koh 12,13

^{[[#fnm7][7]]} 27a: Nach S; in G ausgefallen.
