#+TITLE: Sir 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-04 Sa 18:47]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 12.html

* Sir 12

<<verses>>

<<v1>>
1 Wenn du Gutes tust, wisse, wem du es tust, /\\
 dann wirst du Dank ernten für deine Wohltat.\\
\\

<<v2>>
2 Tu dem Gerechten Gutes; dann findest du Lohn, /\\
 wenn nicht von ihm, so doch vom Herrn.\\
\\

<<v3>>
3 Ohne Dank bleibt, wer einen Frevler beschenkt, /\\
 auch hat er kein gutes Werk vollbracht.\\
\\

<<v4>>
4 Gib dem Guten, nicht aber dem Bösen, /\\
 unterstütze den Demütigen, gib nicht dem Hochmütigen!\\
\\

<<v5>>
5 Rüste ihn nicht mit Kampfwaffen aus, /\\
 sonst greift er dich selbst mit ihnen an. Doppeltes Übel trifft dich
[in der Zeit der Not] /\\
 für all das Gute, das du ihm getan hast. [fn:1]\\
\\

<<v6>>
6 Denn auch Gott hasst die Bösen, /\\
 den Frevlern vergilt er mit Strafe.

<<v7>>
7 [fn:2]\\
\\

<<v8>>
8 Im Glück erkennt man den Freund nicht, /\\
 aber im Unglück bleibt der Feind nicht verborgen. [fn:3]\\
\\

<<v9>>
9 Im Glück ist auch der Feind ein Freund; /\\
 im Unglück wendet auch der Freund sich ab.\\
\\

<<v10>>
10 Trau niemals einem Feind; /\\
 denn seine Bosheit gleicht dem rostenden Eisen. [fn:4]\\
\\

<<v11>>
11 Zeigt er sich auch willig und tut unterwürfig, /\\
 nimm dich in Acht und hüte dich vor ihm! Sei zu ihm wie ein
Spiegelputzer /\\
 und beachte die letzten Spuren des Rostes!\\
\\

<<v12>>
12 Lass ihn nicht an deiner Seite stehen, /\\
 sonst stürzt er dich und tritt an deine Stelle. Lass ihn nicht zu
deiner Rechten sitzen, /\\
 sonst strebt er nach deinem Sitz. Zu spät begreifst du dann meine Worte
/\\
 und stimmst in meine Klage ein.\\
\\

<<v13>>
13 Wer bedauert den Schlangenbeschwörer, wenn er gebissen wird, /\\
 und den, der sich reißenden Tieren nähert?\\
\\

<<v14>>
14 Ihnen gleicht, wer mit einem Schurken verkehrt /\\
 und sich in seine Sünden verstrickt.\\
\\

<<v15>>
15 Solange er neben dir steht, zeigt er sich nicht offen, /\\
 wankst du aber, hält er nicht stand.\\
\\

<<v16>>
16 Auf seinen Lippen hat der Gegner süße Worte, /\\
 doch in seinem Herzen sinnt er auf Verderben. Mag auch der Feind mit
seinen Augen weinen, /\\
 findet er Gelegenheit, wird er an Blut nicht satt.\\
\\

<<v17>>
17 Trifft dich ein Unglück, findet er sich ein; /\\
 als heuchelnder Helfer sucht er dich zu stürzen.\\
\\

<<v18>>
18 Er schüttelt den Kopf und schwingt die Hand, /\\
 doch unter viel dunklem Gerede ändert er das Gesicht.\\
\\

* Footnotes

[fn:1] H wörtlich: Die Waffen des Brotes gib ihm nicht. - Nach G wäre V. 5ab zu übersetzen: Halte das Brot zurück und gib es ihm nicht; sonst bekommt er dich dadurch in seine Gewalt. Der Zusatz in 5c fehlt zu Recht in G.

[fn:2] In G Wiederholung von V. 4a.

[fn:3] [[file:Sir_6.org::v8][6,8-13]]; [[file:Sir_37.org::v1][37,1-6]]; [[file:Spr_19.org::v4][Spr 19,4]]

[fn:4] 10f: Der Vergleich meint die immer wieder auftretenden Gefahren von seiten des Feindes. Dieser Vergleich wird in V. 11 beibehalten: Wie ein Spiegelputzer auf jeden Rostfleck achten muss, so soll man seinen Gegner nicht aus den Augen verlieren.
