:PROPERTIES:
:ID:       15f4a8c1-1660-4351-b232-c06b4db98fa2
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_41.html][41]]
[[file:Sir_42.html][42]] *43* [[file:Sir_44.html][44]]
[[file:Sir_45.html][45]] ... [[file:Sir_51.html][51]]

--------------

* Sir 43
  :PROPERTIES:
  :CUSTOM_ID: sir-43
  :END:

<<verses>>

<<v1>>
**** Die Größe Gottes in der Schöpfung: 43,1-33
     :PROPERTIES:
     :CUSTOM_ID: die-größe-gottes-in-der-schöpfung-431-33
     :END:
1 Die Schönheit der Höhe, das klare Firmament und der gewaltige Himmel
/\\
 sind ein herrlicher Anblick.\\
\\

<<v2>>
2 Die Sonne geht auf und erglänzt in vollem Licht, /\\
 ein staunenswertes Gestirn, das Werk des Höchsten.\\
\\

<<v3>>
3 Steht sie in der Mittagshöhe, /\\
 versetzt sie die Welt in Glut, /\\
 wer hält es aus in ihrer Hitze?\\
\\

<<v4>>
4 Ein brennender Schmelzofen ist das Kunstwerk des Gießers; /\\
 der Pfeil der Sonne setzt Berge in Brand; ihre Feuerzunge verbrennt das
bewohnte Land, /\\
 ihr Licht versengt das Auge.\\
\\

<<v5>>
5 Ja, groß ist der Herr, ihr Schöpfer, /\\
 sein Wort lässt seinen Helden erstrahlen. ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v6>>
6 Der Mond führt die Zeiten herauf; /\\
 er herrscht bis ans Ende und dient für immer als Zeichen.
^{[[#fn3][3]]}\\
\\

<<v7>>
7 Durch ihn werden Fristen und Festzeiten bestimmt, /\\
 ist er erschöpft, freut er sich wieder auf seinen Umlauf.\\
\\

<<v8>>
8 Der Neumond ist so, wie sein Name sagt: /\\
 Er erneuert sich selbst. /\\
 Wie staunenswert ist er in seinem Wechsel. Er ist ein Fahrzeug für das
Heer der Wolken in der Höhe /\\
 und lässt durch seinen Glanz das Himmelsgewölbe erglühen.
^{[[#fn4][4]]}\\
\\

<<v9>>
9 Des Himmels Schönheit und Pracht sind die Sterne, /\\
 ein strahlender Schmuck in den Höhen Gottes.\\
\\

<<v10>>
10 Durch Gottes Wort stehen sie geordnet da /\\
 und ermatten nicht bei ihrer Nachtwache. ^{[[#fn5][5]]}\\
\\

<<v11>>
11 Schau den Regenbogen an und preise seinen Schöpfer; /\\
 denn überaus schön und herrlich ist er. ^{[[#fn6][6]]}\\
\\

<<v12>>
12 Über den Himmelskreis erstreckt er sich in seiner Pracht, /\\
 Gottes Hand hat ihn machtvoll ausgespannt.\\
\\

<<v13>>
13 Gottes Machtwort zeichnet den Blitz hin, /\\
 lässt die Brandpfeile seines Gerichtes leuchten.\\
\\

<<v14>>
14 Zu seinem Dienst hat er einen Speicher geöffnet, /\\
 lässt er Wolken fliegen wie Vögel. ^{[[#fn7][7]]}\\
\\

<<v15>>
15 Seine Allmacht ballt die Wolken zusammen /\\
 und schlägt aus ihnen Hagelsteine.\\
\\

<<v17a>>
17a Seines Donners Stimme lässt die Erde beben, /
^{[[#fn8][8]][[#fn9][9]]}\\
\\

<<v16>>
16 mit seiner Kraft erschüttert er die Berge. Sein Wort hetzt den
Südwind auf, /\\
\\

<<v17b>>
17b den tobenden Nordwind, den Sturm und Orkan. Seinen Schnee streut er
aus wie Vogelschwärme; /\\
 wie einfallende Heuschrecken wirbelt er herab. ^{[[#fn10][10]]}\\
\\

<<v18>>
18 Sein weißer Glanz blendet die Augen, /\\
 bei seinem Rieseln bebt das Herz.\\
\\

<<v19>>
19 Auch den Reif schüttet er aus wie Salz /\\
 und lässt Eisblumen sprießen wie Dornen. ^{[[#fn11][11]]}\\
\\

<<v20>>
20 Den kalten Nordwind lässt er wehen, /\\
 wie Erdschollen lässt er die Quellen erstarren. Jedes stehende Gewässer
überzieht er /\\
 und kleidet den Teich wie mit einem Panzer. ^{[[#fn12][12]]}\\
\\

<<v21>>
21 Das Grün der Berge versengt er wie durch Hitze, /\\
 die sprossende Flur wie durch Flammenglut.\\
\\

<<v22>>
22 Linderung für alles ist das Träufeln der Wolken, /\\
 der Tau, der sich ergießt, um das Trockene zu erfrischen.\\
\\

<<v23>>
23 Sein kluger Plan bändigte das Meer /\\
 und pflanzte Inseln im Ozean ein. ^{[[#fn13][13]]}\\
\\

<<v24>>
24 Die Seefahrer erzählen von der Weite des Meeres; /\\
 hören es unsere Ohren, so erschaudern wir.\\
\\

<<v25>>
25 Dort gibt es Wunderwesen, die erstaunlichsten seiner Werke, /\\
 allerlei Getier und die Ungeheuer des Weltmeers. ^{[[#fn14][14]]}\\
\\

<<v26>>
26 In seinem Dienst hat sein Bote Erfolg /\\
 und durch sein Wort vollzieht er seinen Willen. ^{[[#fn15][15]]}\\
\\

<<v27>>
27 Sagten wir noch mal so viel, wir kämen an kein Ende; /\\
 darum sei der Rede Schluss: Er ist alles! ^{[[#fn16][16]]}\\
\\

<<v28>>
28 Wir können (ihn) nur loben, aber nie erfassen, /\\
 ist er doch größer als alle seine Werke. ^{[[#fn17][17]]}\\
\\

<<v29>>
29 Überaus Ehrfurcht gebietend ist der Herr, /\\
 unbegreiflich ist seine Stärke.\\
\\

<<v30>>
30 Ihr, die ihr den Herrn lobt, singt laut, so viel ihr könnt; /\\
 denn nie wird es genügen. Ihr, die ihr ihn preist, schöpft neue Kraft,
werdet nicht müde; /\\
 denn fassen könnt ihr es nie.\\
\\

<<v31>>
31 Wer hat ihn gesehen, dass er erzählen könnte, /\\
 und wer kann ihn loben, wie es ihm entspricht?\\
\\

<<v32>>
32 Die Menge des Verborgenen ist größer als das Genannte, /\\
 nur wenige von seinen Werken habe ich gesehen.\\
\\

<<v33>>
33 Alles hat der Herr gemacht /\\
 und den Frommen hat er Weisheit verliehen.\\
\\

^{[[#fnm1][1]]} ℘ Ps 19,6

^{[[#fnm2][2]]} 5b: Die Sonne, im Hebräischen männlich, wird auch in Ps
19,6 mit einem Helden verglichen.

^{[[#fnm3][3]]} ℘ Gen 1,14-18; Ps 104,19

^{[[#fnm4][4]]} 8d: Text unsicher; gemeint ist wohl, dass der Mond den
höchsten Wolken als Schiff dient.

^{[[#fnm5][5]]} Die Sterne sind wie ein geordnetes Heer; jeder hat
seinen bestimmten Posten (vgl. Bar 3,34f).

^{[[#fnm6][6]]} ℘ 50,7

^{[[#fnm7][7]]} Die atmosphärischen Kräfte sind nach dichterischer
Vorstellung in einem Speicher am Rand des Himmels untergebracht, von wo
sie Gott zur gegebenen Zeit herauskommen lässt (vgl. 39,30).

^{[[#fnm8][8]]} ℘ Ps 29,8

^{[[#fnm9][9]]} 17a: Gehört dem Zusammenhang nach vor V. 16.

^{[[#fnm10][10]]} 17c-25: Schnee und Eis werden besonders eindrucksvoll
beschrieben, weil sie in Palästina etwas Seltenes sind; sie werden vom
frostigen Nordwind verursacht. Fremdartig ist auch der ungeheure Ozean.

^{[[#fnm11][11]]} ℘ Ps 147,16-18

^{[[#fnm12][12]]} 20b: Nach dem Masada-Text; G: auf dem Wasser gefriert
das Eis.

^{[[#fnm13][13]]} ℘ (23-24) Ps 104,5f

^{[[#fnm14][14]]} ℘ Ps 104,25f

^{[[#fnm15][15]]} Zu Gottes Wort als Bote vgl. Ps 147,15-18.

^{[[#fnm16][16]]} ℘ Weish 1,7; 7,22 - 8,1

^{[[#fnm17][17]]} ℘ Ps 96,4; 145,3
