#+TITLE: Sir 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-04-16 Do 13:41]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 3.html

* Sir 3

<<verses>>

<<v1>>
* Ehrfurcht gegen die Eltern: 3,1-16

1 Hört, ihr Söhne, was das Recht des Vaters ist, /\\
 und handelt danach, damit es euch gut geht.\\
\\

<<v2>>
2 Denn der Herr hat den Kindern befohlen, ihren Vater zu ehren, /\\
 und die Söhne verpflichtet, das Recht ihrer Mutter zu achten. [fn:1]\\
\\

<<v3>>
3 Wer den Vater ehrt, erlangt Verzeihung der Sünden, /\\
\\

<<v4>>
4 und wer seine Mutter achtet, /\\
 gleicht einem Menschen, der Schätze sammelt.\\
\\

<<v5>>
5 Wer den Vater ehrt, wird Freude haben an den eigenen Kindern, /\\
 und wenn er betet, wird er Erhörung finden.\\
\\

<<v6>>
6 Wer den Vater achtet, wird lange leben, /\\
 und wer seiner Mutter Ehre erweist, der erweist sie dem Herrn.\\
\\

<<v7>>
7 Wer den Herrn fürchtet, ehrt seinen Vater /\\
 und dient seinen Eltern wie Vorgesetzten.\\
\\

<<v8>>
8 Mein Sohn, ehre deinen Vater in Wort und Tat, /\\
 damit aller Segen über dich kommt.\\
\\

<<v9>>
9 Der Segen des Vaters festigt die Wurzel, /\\
 doch der Fluch der Mutter reißt die junge Pflanze aus. [fn:2]\\
\\

<<v10>>
10 Such deinen Ruhm nicht darin, den Vater herabzusetzen, /\\
 denn das ist keine Ehre für dich.\\
\\

<<v11>>
11 Die Ehre eines Menschen ist die seines Vaters; /\\
 wer seine Mutter verachtet, sündigt schwer. [fn:3]\\
\\

<<v12>>
12 Mein Sohn, wenn dein Vater alt ist, nimm dich seiner an /\\
 und betrübe ihn nicht, solange er lebt.\\
\\

<<v13>>
13 Wenn sein Verstand abnimmt, sieh es ihm nach /\\
 und beschäme ihn nicht in deiner Vollkraft! [fn:4]\\
\\

<<v14>>
14 Denn die Liebe zum Vater wird nicht vergessen, /\\
 sie wird als Sühne für deine Sünden eingetragen.\\
\\

<<v15>>
15 Zur Zeit der Bedrängnis wird sie dir vergolten werden; /\\
 sie lässt deine Sünden schmelzen wie Wärme den Reif.\\
\\

<<v16>>
16 Wie ein Gotteslästerer handelt, wer seinen Vater im Stich lässt, /\\
 und von Gott ist verflucht, wer seine Mutter kränkt.\\
\\

<<v17>>
* Bescheidenheit: 3,17-31

17 Mein Sohn, bei all deinem Tun bleibe bescheiden /\\
 und du wirst mehr geliebt werden als einer, der Gaben verteilt.\\
\\

<<v18>>
18 Je größer du bist, umso mehr bescheide dich, /\\
 dann wirst du Gnade finden bei Gott. [fn:5]\\
\\

<<v19>>
19 [] [fn:6]\\
\\

<<v20>>
20 Denn groß ist die Macht Gottes /\\
 und von den Demütigen wird er verherrlicht.\\
\\

<<v21>>
21 Such nicht zu ergründen, was dir zu wunderbar ist, /\\
 untersuch nicht, was dir verhüllt ist.\\
\\

<<v22>>
22 Was dir zugewiesen ist, magst du durchforschen, /\\
 doch das Verborgene hast du nicht nötig.\\
\\

<<v23>>
23 Such nicht hartnäckig zu erfahren, /\\
 was deine Kraft übersteigt. /\\
 Es ist schon zu viel, was du sehen darfst.\\
\\

<<v24>>
24 Vielfältig sind die Gedanken der Menschen, /\\
 schlimmer Wahn führt in die Irre.\\
\\

<<v25>>
25 [Wer kein Auge hat, dem fehlt das Licht, /\\
 wer keine Einsicht hat, dem fehlt die Weisheit.] [fn:7]\\
\\

<<v26>>
26 Ein trotziges Herz nimmt ein böses Ende, /\\
 wer aber das Gute liebt, den wird es geleiten.\\
\\

<<v27>>
27 Ein trotziges Herz schafft sich viel Leid /\\
 und der Frevler häuft Sünde auf Sünde.\\
\\

<<v28>>
28 Für die Wunde des Übermütigen gibt es keine Heilung, /\\
 denn ein giftiges Kraut hat in ihm seine Wurzeln.\\
\\

<<v29>>
29 Ein weises Herz versteht die Sinnsprüche [der Weisen], /\\
 ein Ohr, das auf die Weisheit hört, macht Freude. [fn:8] [fn:9]\\
\\

<<v30>>
30 Wie Wasser loderndes Feuer löscht, /\\
 so sühnt Mildtätigkeit Sünde.\\
\\

<<v31>>
31 Wer Gutes tut, dem begegnet es auf seinen Wegen, /\\
 sobald er wankt, findet er eine Stütze. [fn:10]\\
\\


* Footnotes

[fn:1] [[file:Ex_20.org::v12][Ex 20,12]]; [[file:Dtn_5.org::v16][Dtn 5,16]]; [[file:Spr_10.org::v1][Spr 10,1]]

[fn:2] So nach H; G: Denn der Segen des Vaters baut den Kindern feste Häuser, doch der Fluch der Mutter reißt die Fundamente aus.

[fn:3] [[file:Spr_30.org::v17][Spr 30,17]]

[fn:4] [[file:Spr_23.org::v22][Spr 23,22]]

[fn:5] [[file:Spr_3.org::v34][Spr 3,34]]

[fn:6] Der folgende V. 19 entfällt, da nur von wenigen Textzeugen überliefert.

[fn:7] Fehlt im älteren G- und im Vg-Text; späterer Zusatz.

[fn:8] [[file:Spr_2.org::v2][Spr 2,2]]

[fn:9] 29b: G: Ein aufmerksames Ohr ist der Wunsch des Weisen.

[fn:10] [[file:Spr_11.org::v18][Spr 11,18-20]]
