:PROPERTIES:
:ID:       c709206f-e719-49fb-8cc6-fe4714fc7c36
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_16.html][16]]
[[file:Sir_17.html][17]] *18* [[file:Sir_19.html][19]]
[[file:Sir_20.html][20]] ... [[file:Sir_51.html][51]]

--------------

* Sir 18
  :PROPERTIES:
  :CUSTOM_ID: sir-18
  :END:

<<verses>>

<<v1>>
**** Die Größe Gottes: 18,1-14
     :PROPERTIES:
     :CUSTOM_ID: die-größe-gottes-181-14
     :END:
1 Der Herr, der in Ewigkeit lebt, hat alles insgesamt erschaffen, /\\
 der Herr allein erweist sich als gerecht.\\
\\

<<v2>>
2 [] ^{[[#fn1][1]]}

<<v3>>
3 []\\
\\

<<v4>>
4 Keiner vermag seine Werke zu verkünden. /\\
 Wer ergründet seine großen Taten?\\
\\

<<v5>>
5 Wer kann seine gewaltige Größe beschreiben /\\
 und seine großen Taten aufzählen bis zum Ende?\\
\\

<<v6>>
6 Man kann nichts wegnehmen und nichts hinzutun, /\\
 unmöglich ist es, die Wunder des Herrn zu ergründen. ^{[[#fn2][2]]}\\
\\

<<v7>>
7 Ist der Mensch am Ende angelangt, /\\
 steht er noch am Anfang, /\\
 wenn er es aufgibt, ist er ratlos. ^{[[#fn3][3]]}\\
\\

<<v8>>
8 Was ist der Mensch und wozu nützt er? /\\
 Was ist gut an ihm und was ist schlecht?\\
\\

<<v9>>
9 Das Leben eines Menschen dauert /\\
 höchstens hundert Jahre. ^{[[#fn4][4]]}\\
\\

<<v10>>
10 Wie ein Wassertropfen im Meer und wie ein Körnchen im Sand, /\\
 so verhalten sich die wenigen Jahre zu der Zeit der Ewigkeit.\\
\\

<<v11>>
11 Darum hat der Herr mit ihnen Geduld /\\
 und er gießt über sie sein Erbarmen aus.\\
\\

<<v12>>
12 Er sieht und weiß, dass ihr Ende schlimm ist; /\\
 darum hat er so viel Nachsicht mit ihnen.\\
\\

<<v13>>
13 Das Erbarmen des Menschen gilt nur seinem Nächsten, /\\
 das Erbarmen des Herrn allen Menschen. Er weist zurecht, erzieht und
belehrt /\\
 und führt wie ein Hirt seine Herde zurück.\\
\\

<<v14>>
14 Glücklich alle, die auf sein Erbarmen hoffen /\\
 und seine Gebote annehmen. ^{[[#fn5][5]]}\\
\\

<<v15>>
** Verschiedene Mahnungen und Warnungen: 18,15 - 24,34
   :PROPERTIES:
   :CUSTOM_ID: verschiedene-mahnungen-und-warnungen-1815---2434
   :END:
**** Das Verhalten des Weisen: 18,15-29
     :PROPERTIES:
     :CUSTOM_ID: das-verhalten-des-weisen-1815-29
     :END:
15 Mein Sohn, bring keinen Makel auf deine Wohltaten /\\
 und füg zu keiner Gabe kränkende Worte! ^{[[#fn6][6]]}\\
\\

<<v16>>
16 Vertreibt nicht der Tau die Hitze? /\\
 So ist das Wort mehr als die Gabe.\\
\\

<<v17>>
17 Ist das Wort nicht mehr wert als die Gabe? /\\
 Dem Gütigen steht beides wohl an.\\
\\

<<v18>>
18 Der Tor schmäht in liebloser Weise, /\\
 die Gabe des Geizigen macht die Augen traurig.\\
\\

<<v19>>
19 Bevor du redest, unterrichte dich, /\\
 und ehe du krank wirst, sorge für die Gesundheit!\\
\\

<<v20>>
20 Noch vor dem Gericht erforsche dich selbst, /\\
 dann wird dir in der Stunde der Prüfung verziehen.\\
\\

<<v21>>
21 Demütige dich, ehe du zu Fall kommst; /\\
 zur Zeit der Sünde lass Umkehr erkennen!\\
\\

<<v22>>
22 Säume nicht, ein Gelübde rechtzeitig einzulösen, /\\
 warte nicht bis zum Tod, um davon frei zu werden.\\
\\

<<v23>>
23 Ehe du gelobst, überdenk dein Gelübde, /\\
 sei nicht wie einer, der den Herrn versucht. ^{[[#fn7][7]]}\\
\\

<<v24>>
24 Denk an den Zorn am Ende der Tage, /\\
 an die Zeit der Vergeltung, wenn er sein Gesicht abwendet.
^{[[#fn8][8]]}\\
\\

<<v25>>
25 Denk zur Zeit des Überflusses an die Zeit des Hungers, /\\
 in den Tagen des Reichtums an Armut und Not! ^{[[#fn9][9]]}\\
\\

<<v26>>
26 Vom Morgen zum Abend wechselt die Zeit, /\\
 alles eilt dahin vor dem Herrn.\\
\\

<<v27>>
27 Ein Weiser nimmt sich immer in Acht, /\\
 in Zeiten der Sünde hütet er sich vor Verfehlung.\\
\\

<<v28>>
28 Jeder Verständige soll Weisheit lehren; /\\
 wer sie gefunden hat, soll ihr Lob verkünden. ^{[[#fn10][10]]}\\
\\

<<v29>>
29 Wer klug zu reden vermag, ist selbst ein Weisheitslehrer /\\
 und trägt in Bescheidenheit seine Sinnsprüche vor. ^{[[#fn11][11]]}\\
\\

<<v30>>
**** Die Beherrschung der Begierden: 18,30 - 19,17
     :PROPERTIES:
     :CUSTOM_ID: die-beherrschung-der-begierden-1830---1917
     :END:
30 Folg nicht deinen Begierden, /\\
 von deinen Gelüsten halte dich fern!\\
\\

<<v31>>
31 Wenn du erfüllst, was deine Seele begehrt, /\\
 erfüllst du das Begehren deines Feindes.\\
\\

<<v32>>
32 Freu dich nicht über ein wenig Lust; /\\
 doppelt so schwer wird dann die Armut sein.\\
\\

<<v33>>
33 Sei kein Fresser und Säufer; /\\
 denn sonst bleibt nichts im Beutel. ^{[[#fn12][12]]}\\
\\

^{[[#fnm1][1]]} 2f: Die beiden Verse sind späte Zusätze.

^{[[#fnm2][2]]} ℘ 42,21

^{[[#fnm3][3]]} ℘ Ps 139,18

^{[[#fnm4][4]]} Hier die runde Zahl hundert; Ps 90,10: siebzig,
höchstens achtzig Jahre.

^{[[#fnm5][5]]} So mit S; G: Er erbarmt sich derer, die Zucht annehmen
und eifrig nach seinen Geboten suchen.

^{[[#fnm6][6]]} ℘ 41,22

^{[[#fnm7][7]]} ℘ Spr 20,25; Koh 5,3f

^{[[#fnm8][8]]} Jenseitige Strafe kennt Sirach noch nicht. Er denkt an
den zuletzt doch eintreffenden Zorn Gottes.

^{[[#fnm9][9]]} Das Stichwort «Denk an» leitet zur Mahnung über, im
Glück an das drohende Unglück zu denken, da die Zeiten wechseln.

^{[[#fnm10][10]]} Übersetzung nach S.

^{[[#fnm11][11]]} ℘ 16,25; 24,32f

^{[[#fnm12][12]]} 33b: Andere Übersetzungsmöglichkeit: während du nichts
im Beutel hast.
