:PROPERTIES:
:ID:       fa070b9a-2ed0-4c63-b221-df761d62f450
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_35.html][35]]
[[file:Sir_36.html][36]] *37* [[file:Sir_38.html][38]]
[[file:Sir_39.html][39]] ... [[file:Sir_51.html][51]]

--------------

* Sir 37
  :PROPERTIES:
  :CUSTOM_ID: sir-37
  :END:

<<verses>>

<<v1>>
1 Jeder Freund sagt: Ich bin dein Freund. /\\
 Doch mancher Freund ist nur dem Namen nach Freund. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Ist es nicht ein tödlicher Schmerz, /\\
 wenn ein gleich gesinnter Freund zum Feind wird?\\
\\

<<v3>>
3 Weh, treuloser Freund, wozu bist du geschaffen? /\\
 Um die weite Erde mit Falschheit zu erfüllen?\\
\\

<<v4>>
4 Übel ist ein Freund, der nur nach dem Tisch sieht; /\\
 zur Zeit der Not hält er sich fern.\\
\\

<<v5>>
5 Ein guter Freund kämpft mit dem Feind, /\\
 er hält den Schild gegen den Widersacher.\\
\\

<<v6>>
6 Vergiss nicht den Kampfgefährten! /\\
 Hast du Beute gemacht, lass ihn nicht leer ausgehen!\\
\\

<<v7>>
7 Jeder Ratgeber weist mit der Hand die Richtung, /\\
 doch mancher rät einen Weg zum eigenen Vorteil. ^{[[#fn2][2]]}\\
\\

<<v8>>
8 Hüte dich vor dem Ratgeber! /\\
 Erforsche zuerst, was seine Absicht ist. Denn auch er denkt an sich
selbst. /\\
 Doch warum soll das Los ihm zufallen?\\
\\

<<v9>>
9 Er sagt zu dir: Dein Weg ist der rechte. /\\
 Dann stellt er sich beiseite und schaut zu, wie du arm wirst.\\
\\

<<v10>>
10 Berate dich nicht mit deinem Neider; /\\
 vor dem, der eifersüchtig ist, verbirg Geheimes!\\
\\

<<v11>>
11 Berate dich nicht mit einer Frau über ihre Nebenbuhlerin, /\\
 mit einem Feind über den Kampf gegen ihn, /\\
 mit einem Händler über das Geschäft, /\\
 mit einem Käufer über die Ware, /\\
 mit einem Geizhals über die Liebestätigkeit, /\\
 mit einem Unbarmherzigen über das Glück des Mitmenschen, /\\
 mit einem Faulen über seine Arbeit, /\\
 mit einem Arbeiter über die Aussaat, /\\
 mit einem trägen Sklaven über die Menge der Arbeit. Vertraue dich nie
diesen Menschen an, /\\
 wenn du Rat einholst. ^{[[#fn3][3]]}\\
\\

<<v12>>
12 Doch berate dich mit einem stets Besonnenen, /\\
 von dem du weißt, dass er die Gebote hält, /\\
 mit einem, dessen Herz denkt wie dein Herz /\\
 und der dir hilft, wenn du strauchelst. ^{[[#fn4][4]]}\\
\\

<<v13>>
13 Doch achte auch auf den Rat deines Gewissens. /\\
 Wer ist dir treuer als dieses? ^{[[#fn5][5]]}\\
\\

<<v14>>
14 Das Gewissen des Menschen gibt ihm bessere Auskunft /\\
 als sieben Wächter auf der Warte.\\
\\

<<v15>>
15 Bei alledem bete zu Gott! /\\
 Er wird in Treue deine Schritte lenken. ^{[[#fn6][6]]}\\
\\

<<v16>>
16 Der Anfang eines jeden Werkes ist das Wort, /\\
 der Anfang jeder Tat die Überlegung. ^{[[#fn7][7]]}\\
\\

<<v17>>
17 Die Wurzel der Pläne ist das Herz. /\\
\\

<<v18>>
18 Vier Reiser wachsen daraus hervor: Gutes und Böses, Leben und Tod.
/\\
 Doch die Zunge hat Gewalt über sie alle. ^{[[#fn8][8]]}\\
\\

<<v19>>
19 Es gibt Weise, die für viele weise sind, /\\
 für sich selber aber sind sie Toren. ^{[[#fn9][9]]}\\
\\

<<v20>>
20 Es gibt Weise, die trotz ihres Wortes verachtet sind, /\\
 von allen Genüssen sind sie ausgeschlossen.\\
\\

<<v21>>
21 [Denn vom Herrn wurde ihm keine Huld zuteil, /\\
 weil ihm alle Weisheit fehlt.]\\
\\

<<v22>>
22 Es gibt Weise, die für sich selbst weise sind; /\\
 die Frucht ihres Wissens zeigt sich an ihrem Leib.\\
\\

<<v23>>
23 Es gibt Weise, die für ihr Volk weise sind; /\\
 die Frucht ihres Wissens ist von Dauer.\\
\\

<<v24>>
24 Wer weise ist für sich selbst, sättigt sich an Genüssen, /\\
 alle, die ihn sehen, preisen ihn glücklich.\\
\\

<<v25>>
25 [Des Menschen Leben währt zählbare Tage, /\\
 das Leben des Volkes Israel unzählbare Tage.]\\
\\

<<v26>>
26 Wer weise ist für das Volk, erlangt Ehre, /\\
 sein Ruhm wird dauernd weiterleben.\\
\\

<<v27>>
**** Krankheit und Tod: 37,27 - 38,23
     :PROPERTIES:
     :CUSTOM_ID: krankheit-und-tod-3727---3823
     :END:
27 Mein Sohn, prüfe dich in deiner Lebensweise, /\\
 beobachte, was dir schlecht bekommt, und meide es! ^{[[#fn10][10]]}\\
\\

<<v28>>
28 Denn nicht alles ist für alle gut, /\\
 nicht jeder kann jedes wählen.\\
\\

<<v29>>
29 Giere nicht nach jedem Genuss, /\\
 stürz dich nicht auf alle Leckerbissen!\\
\\

<<v30>>
30 Denn im Übermaß des Essens steckt die Krankheit, /\\
 der Unmäßige verfällt heftigem Erbrechen.\\
\\

<<v31>>
31 Schon viele sind durch Unmäßigkeit gestorben, /\\
 wer sich aber beherrscht, verlängert sein Leben.\\
\\

^{[[#fnm1][1]]} ℘ 6,5-17; 12,8f; Spr 20,6

^{[[#fnm2][2]]} 7-9: Nach dem Freund wird auch der Ratgeber eigens
erwähnt. Beiden gegenüber ist kluge Vorsicht geboten.

^{[[#fnm3][3]]} Wo einer persönlich betroffen ist, wird er nie ganz
sachlich urteilen, daher als Ratgeber ungeeignet sein.

^{[[#fnm4][4]]} 12d: G: und der Mitleid mit dir hat.

^{[[#fnm5][5]]} 13f: Für «Gewissen» sagt der Hebräer «Herz». Der Rat des
«Herzens» ist stets der beste.

^{[[#fnm6][6]]} ℘ Spr 16,9

^{[[#fnm7][7]]} 16-18: Eine psychologische Überlegung: Aus den Plänen
des Herzens entspringt das Gute und das Böse.

^{[[#fnm8][8]]} ℘ Spr 18,21

^{[[#fnm9][9]]} 19-26: Die psychologischen Betrachtungen führen Sirach
zur Aufzählung verschiedener Gruppen von «Weisen», die ihre Lehren unter
das Volk bringen wollen, daher: «weise für ihr Volk» (VV. 23.26). «Weise
für sich selbst» (VV. 22.24) sind die praktischen Lebenskünstler
(Epikureer), die auf Erfolg und Gewinn aus sind. Ihnen stehen die
Idealisten gegenüber, die es zu nichts bringen (VV. 19f).

^{[[#fnm10][10]]} 27-31: Hier wird eine Empfehlung zur Mäßigkeit
eingeschoben. Wie bei den Folgen der Unmäßigkeit in 31,19-21 werden
nicht moralische Gesichtspunkte angeführt, sondern gesundheitliche.
