#+TITLE: Sir 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-07-04 Sa 18:58]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Sir 15.html

* Sir 15

<<verses>>

<<v1>>
1 Wer den Herrn fürchtet, handelt so, /\\
 und wer am Gesetz fest hält, erlangt die Weisheit. [fn:1]\\
\\

<<v2>>
2 Sie geht ihm entgegen wie eine Mutter, /\\
 wie eine junge Gattin nimmt sie ihn auf. [fn:2]\\
\\

<<v3>>
3 Sie nährt ihn mit dem Brot der Klugheit /\\
 und tränkt ihn mit dem Wasser der Einsicht.\\
\\

<<v4>>
4 Er stützt sich auf sie und kommt nicht zu Fall, /\\
 er vertraut auf sie und wird nicht enttäuscht.\\
\\

<<v5>>
5 Sie erhöht ihn über seine Gefährten, /\\
 sie öffnet ihm den Mund in der Versammlung.\\
\\

<<v6>>
6 Sie lässt ihn Jubel und Freude finden, /\\
 unvergänglichen Ruhm wird sie ihm verleihen.\\
\\

<<v7>>
7 Für schlechte Menschen ist sie unerreichbar, /\\
 Unbeherrschte werden sie nicht schauen.\\
\\

<<v8>>
8 Den Zuchtlosen ist sie fern. /\\
 Lügner denken nicht an sie.\\
\\

<<v9>>
9 Schlecht klingt das Gotteslob im Mund des Frevlers, /\\
 es ist ihm von Gott nicht zugeteilt.\\
\\

<<v10>>
10 Im Mund des Weisen erklinge das Gotteslob /\\
 und wer dazu Vollmacht hat, unterrichte darin.\\
\\

<<v11>>
* Die Verantwortung des Menschen: 15,11-20

11 Sag nicht: Meine Sünde kommt von Gott. /\\
 Denn was er hasst, das tut er nicht.\\
\\

<<v12>>
12 Sag nicht: Er hat mich zu Fall gebracht. /\\
 Denn er hat keine Freude an schlechten Menschen.\\
\\

<<v13>>
13 Verabscheuungswürdiges hasst der Herr; /\\
 alle, die ihn fürchten, bewahrt er davor.\\
\\

<<v14>>
14 Er hat am Anfang den Menschen erschaffen /\\
 und ihn der Macht der eigenen Entscheidung überlassen.\\
\\

<<v15>>
15 [Er gab ihm seine Gebote und Vorschriften.] /\\
 Wenn du willst, kannst du das Gebot halten; /\\
 Gottes Willen zu tun ist Treue. [fn:3]\\
\\

<<v16>>
16 Feuer und Wasser sind vor dich hingestellt; /\\
 streck deine Hände aus nach dem, was dir gefällt.\\
\\

<<v17>>
17 Der Mensch hat Leben und Tod vor sich; /\\
 was er begehrt, wird ihm zuteil. [fn:4]\\
\\

<<v18>>
18 Überreich ist die Weisheit des Herrn; /\\
 stark und mächtig ist er und sieht alles.\\
\\

<<v19>>
19 Die Augen Gottes schauen auf das Tun des Menschen, /\\
 er kennt alle seine Taten. [fn:5]\\
\\

<<v20>>
20 Keinem gebietet er zu sündigen /\\
 und die Betrüger unterstützt er nicht. [fn:6]\\
\\

* Footnotes

[fn:1] 1-16,7: Dieser Text ist seit 1958 auch aus einem zweiten hebräischen Fragment bekannt, das sich enger an den ursprünglichen G-Text anschließt, während die bisher bekannte Handschrift eine spätere Bearbeitung erfuhr. Gottesfurcht, Weisheit und Gesetzestreue sind für den Weisen identisch (vgl. [[file:Sir_1.org::v16][1,16]]; [[file:Sir_19.org::v20][19,20]]).

[fn:2] [[file:Sir_51.org::v13][51,13-21]]; [[file:Spr_7.org::v4][Spr 7,4]]

[fn:3] 15a: Nur in Vg.

[fn:4] [[file:Dtn_30.org::v15][Dtn 30,15]].[[file:Dtn_30.org::v19][19]]; [[file:Jer_21.org::v8][Jer 21,8]]

[fn:5] [[file:Sir_17.org::v15][17,15]]

[fn:6] [[file:Ps_5.org::v5][Ps 5,5-7]]
