:PROPERTIES:
:ID:       53eb8afa-ea3c-40a9-9ca1-09680b753481
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_17.html][17]]
[[file:Sir_18.html][18]] *19* [[file:Sir_20.html][20]]
[[file:Sir_21.html][21]] ... [[file:Sir_51.html][51]]

--------------

* Sir 19
  :PROPERTIES:
  :CUSTOM_ID: sir-19
  :END:

<<verses>>

<<v1>>
1 Wer das tut, wird niemals reich, /\\
 wer das wenige gering schätzt, richtet sich zugrunde. ^{[[#fn1][1]]}\\
\\

<<v2>>
2 Wein und Weiber machen das Herz zügellos; /\\
 wer sich an Dirnen hängt, wird frech.\\
\\

<<v3>>
3 [Moder und Würmer nehmen ihn in Besitz, /\\
 freche Gier richtet den zugrunde, über den sie herrscht.]
^{[[#fn2][2]][[#fn3][3]]}\\
\\

<<v4>>
4 Wer schnell vertraut, ist leichtfertig, /\\
 wer sündigt, verfehlt sich gegen sich selbst.\\
\\

<<v5>>
5 Wer sich über eine Schlechtigkeit freut, wird selbst verachtet, /\\
 [wer den Lüsten widerstrebt, krönt sein Leben. ^{[[#fn4][4]]}\\
\\

<<v6>>
6 Wer seine Zunge beherrscht, lebt ohne Streit;] /\\
 wer Gerede verbreitet, dem fehlt es an Verstand.\\
\\

<<v7>>
7 Verbreite niemals ein Gerede, /\\
 dann wird auch dich niemand schmähen.\\
\\

<<v8>>
8 Rede weder über Freund noch Feind; /\\
 wenn du einen Freund hast, enthülle nichts über ihn! ^{[[#fn5][5]]}\\
\\

<<v9>>
9 Denn wer dich hört, wird sich vor dir hüten /\\
 und dir zur gegebenen Zeit seinen Groll zeigen. ^{[[#fn6][6]]}\\
\\

<<v10>>
10 Hast du etwas gehört, so sterbe es in dir; /\\
 sei unbesorgt, es wird dich nicht zerreißen.\\
\\

<<v11>>
11 Um eines Wortes willen kommt der Tor in Wehen /\\
 wie eine Gebärende durch ihre Leibesfrucht. ^{[[#fn7][7]]}\\
\\

<<v12>>
12 Wie ein Pfeil im Schenkel sitzt, /\\
 so steckt das Wort im Leib des Toren.\\
\\

<<v13>>
13 Stell den Freund zur Rede, ob er etwas getan hat, /\\
 und wenn er es getan hat - damit er es nicht wieder tut.\\
\\

<<v14>>
14 Stell deinen Nächsten zur Rede, ob er etwas gesagt hat, /\\
 und wenn er es gesagt hat - damit er es nicht wiederholt.\\
\\

<<v15>>
15 Stell den Freund zur Rede, denn oft gibt es Verleumdung; /\\
 trau nicht jedem Wort!\\
\\

<<v16>>
16 Mancher gleitet aus, doch ohne Absicht. /\\
 Wer hätte noch nie mit seiner Zunge gesündigt?\\
\\

<<v17>>
17 Stell deinen Nächsten zur Rede, ehe du ihm Vorwürfe machst. /\\
 Gib dem Gesetz des Höchsten Raum! ^{[[#fn8][8]]}\\
\\

<<v18>>
18 [] ^{[[#fn9][9]]}

<<v19>>
19 []\\
\\

<<v20>>
**** Rechte und falsche Klugheit: 19,20-30
     :PROPERTIES:
     :CUSTOM_ID: rechte-und-falsche-klugheit-1920-30
     :END:
20 Alle Weisheit ist Furcht vor dem Herrn; /\\
 in jeder Weisheit liegt Erfüllung des Gesetzes.\\
\\

<<v21>>
21 []\\
\\

<<v22>>
22 Schlechtes zu kennen ist keine Weisheit, /\\
 der Rat der Sünder ist keine Klugheit.\\
\\

<<v23>>
23 Es gibt eine Schläue, die ein Gräuel ist, /\\
 und es gibt Einfältige, die nichts Schlechtes tun.\\
\\

<<v24>>
24 Besser ist es, arm an Klugheit und gottesfürchtig zu sein, /\\
 als reich an Einsicht, aber das Gesetz zu übertreten.\\
\\

<<v25>>
25 Es gibt eine listige Schläue, doch sie ist ungerecht; /\\
 mancher verstellt sich, um Rechtschaffenheit vorzutäuschen.\\
\\

<<v26>>
26 Mancher geht gebeugt und traurig einher, /\\
 doch sein Inneres ist voll Tücke.\\
\\

<<v27>>
27 Er schlägt den Blick nieder und stellt sich taub; /\\
 wo er nicht durchschaut wird, tritt er gegen dich auf.\\
\\

<<v28>>
28 Wenn ihm die Kraft fehlt, Unrecht zu tun, /\\
 tut er doch Böses, sobald er Gelegenheit findet.\\
\\

<<v29>>
29 Am Aussehen erkennt man den Menschen, /\\
 am Gesichtsausdruck erkennt ihn der Weise.\\
\\

<<v30>>
30 Die Kleidung des Menschen offenbart sein Verhalten, /\\
 die Schritte des Menschen zeigen, was an ihm ist. ^{[[#fn10][10]]}\\
\\

^{[[#fnm1][1]]} Wer das tut: nach H. - «das wenige» in b meint die im
Einzelfall nicht besonders hohen Ausgaben des Schlemmers; erst die
maßlose Gewohnheit ist gefährlich.

^{[[#fnm2][2]]} ℘ 10,11; 6,4

^{[[#fnm3][3]]} Wohl nicht ursprünglich, sondern aus 10,11 und 6,4
zusammengestellt. Der erste Halbvers fehlt in H und S.

^{[[#fnm4][4]]} 5b.6a: Nur in einigen G-Handschriften.

^{[[#fnm5][5]]} 8b: G kaum richtig: Wenn es für dich keine Sünde ist,
enthülle nichts! (Vgl. 27,16-21).

^{[[#fnm6][6]]} ℘ (8-9) 22,26

^{[[#fnm7][7]]} 11f: Sinn der Vergleiche: Der Tor kann nichts für sich
behalten.

^{[[#fnm8][8]]} ℘ Lev 19,17

^{[[#fnm9][9]]} 18.19.21: Späte Zusätze.

^{[[#fnm10][10]]} So nach S.
