:PROPERTIES:
:ID:       2ad8047b-0c26-446f-9684-00f989c4c4b6
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_40.html][40]]
[[file:Sir_41.html][41]] *42* [[file:Sir_43.html][43]]
[[file:Sir_44.html][44]] ... [[file:Sir_51.html][51]]

--------------

* Sir 42
  :PROPERTIES:
  :CUSTOM_ID: sir-42
  :END:

<<verses>>

<<v1>>
1 ein Wort, das du gehört hast, weiterzutragen /\\
 und ein vertrauliches Gespräch zu verraten. Dann bist du in der Tat
schamhaft /\\
 und findest Gunst bei allen Menschen. Aber nimm keine falsche Rücksicht
/\\
 und schäme dich nicht folgender Dinge: ^{[[#fn1][1]]}\\
\\

<<v2>>
2 des Gesetzes des Höchsten und seiner Satzung, /\\
 des gerechten Urteils, das nicht den Schuldigen freispricht,\\
\\

<<v3>>
3 der Abrechnung mit dem Geschäftsfreund und dem Kaufmann, /\\
 der Verteilung von Erbe und Besitz,\\
\\

<<v4>>
4 der Säuberung von Waagschalen und Waage, /\\
 der Reinigung von Maß und Gewicht, /\\
 des Einkaufs, ob viel oder wenig,\\
\\

<<v5>>
5 des Handelns um den Kaufpreis mit dem Krämer, /\\
 der häufigen Züchtigung der Kinder /\\
 und der Schläge für einen schlechten und trägen Sklaven.
^{[[#fn2][2]]}\\
\\

<<v6>>
6 (Schäme dich nicht,) eine schlimme Frau in Gewahrsam zu halten /\\
 und dort abzuschließen, wo viele Hände sind, ^{[[#fn3][3]]}\\
\\

<<v7>>
7 ein Verzeichnis aufzustellen, wenn du etwas hinterlegt hast, /\\
 auch Einnahme und Ausgabe immer aufzuschreiben, ^{[[#fn4][4]]}\\
\\

<<v8>>
8 einen Unverständigen und Toren zurechtzuweisen /\\
 und einen haltlosen Greis, der Unzucht treibt. Dann bist du in Wahrheit
vorsichtig /\\
 und ein behutsamer Mann vor den Augen aller Menschen. ^{[[#fn5][5]]}\\
\\

<<v9>>
**** Die Sorgen des Vaters um seine Tochter: 42,9-14
     :PROPERTIES:
     :CUSTOM_ID: die-sorgen-des-vaters-um-seine-tochter-429-14
     :END:
9 Eine Tochter ist für den Vater ein Schatz, den er hütet, /\\
 die Sorge um sie nimmt ihm den Schlaf: in ihrer Jugend, dass sie nicht
verschmäht wird, /\\
 nach der Heirat, dass sie nicht verstoßen wird, ^{[[#fn6][6]]}\\
\\

<<v10>>
10 als Mädchen, dass sie nicht verführt wird, /\\
 bei ihrem Gatten, dass sie nicht untreu wird, im Haus ihres Vaters,
dass sie nicht schwanger wird, /\\
 im Haus ihres Gatten, dass sie nicht kinderlos bleibt.\\
\\

<<v11>>
11 Mein Sohn, wache streng über deine Tochter, /\\
 damit sie dich nicht in schlechten Ruf bringt, kein Stadtgespräch und
keinen Volksauflauf erregt, /\\
 dich nicht beschämt in der Versammlung am Stadttor. Wo sie sich
aufhält, sei kein Fenster, /\\
 kein Ausblick auf die Wege ringsum.\\
\\

<<v12>>
12 Keinem Mann zeige sie ihre Schönheit /\\
 und unter Frauen halte sie sich nicht auf.\\
\\

<<v13>>
13 Denn aus dem Kleid kommt die Motte, /\\
 aus der einen Frau die Schlechtigkeit der andern.\\
\\

<<v14>>
14 Besser ein unfreundlicher Mann als eine freundliche Frau /\\
 und (besser) eine gewissenhafte Tochter als jede Art von Schmach.
^{[[#fn7][7]]}\\
\\

<<v15>>
** Der Lobpreis Gottes in Natur und Geschichte: 42,15 - 50,24
   :PROPERTIES:
   :CUSTOM_ID: der-lobpreis-gottes-in-natur-und-geschichte-4215---5024
   :END:
**** Das Lob des Schöpfers in der Natur: 42,15-25
     :PROPERTIES:
     :CUSTOM_ID: das-lob-des-schöpfers-in-der-natur-4215-25
     :END:
15 Nun will ich der Werke Gottes gedenken; /\\
 was ich gesehen habe, will ich erzählen: Durch Gottes Wort entstanden
seine Werke; /\\
 seine Lehre ist ein Ausfluss seiner Liebe. ^{[[#fn8][8]][[#fn9][9]]}\\
\\

<<v16>>
16 Über allem strahlt die leuchtende Sonne, /\\
 die Herrlichkeit des Herrn erfüllt alle seine Werke.\\
\\

<<v17>>
17 Die Heiligen Gottes vermögen nicht, /\\
 alle seine Wunder zu erzählen. Gott gibt seinen Heerscharen die Kraft,
/\\
 vor seiner Herrlichkeit zu bestehen.\\
\\

<<v18>>
18 Meerestiefe und Menschenherz durchforscht er /\\
 und er kennt alle ihre Geheimnisse. Der Höchste hat Kenntnis von allem,
/\\
 bis in die fernste Zeit sieht er das Kommende. ^{[[#fn10][10]]}\\
\\

<<v19>>
19 Vergangenheit und Zukunft macht er kund /\\
 und enthüllt die Rätsel des Verborgenen.\\
\\

<<v20>>
20 Es fehlt ihm keine Einsicht, /\\
 kein Ding entgeht ihm. ^{[[#fn11][11]]}\\
\\

<<v21>>
21 Seine machtvolle Weisheit hat er fest gegründet, /\\
 er ist der Einzige von Ewigkeit her. Nichts ist hinzuzufügen, nichts
wegzunehmen, /\\
 er braucht keinen Lehrmeister. ^{[[#fn12][12]]}\\
\\

<<v22>>
22 Alle seine Werke sind vortrefflich, /\\
 doch sehen wir nur einen Funken und ein Spiegelbild.\\
\\

<<v23>>
23 Alles lebt und besteht für immer, /\\
 für jeden Gebrauch ist alles bereit.\\
\\

<<v24>>
24 Jedes Ding ist vom andern verschieden, /\\
 keines von ihnen hat er vergeblich gemacht. ^{[[#fn13][13]]}\\
\\

<<v25>>
25 Eines ergänzt durch seinen Wert das andere. /\\
 Wer kann sich satt sehen an ihrer Pracht?\\
\\

^{[[#fnm1][1]]} ℘ 19,7f

^{[[#fnm2][2]]} ℘ 30,1; 33,25-33

^{[[#fnm3][3]]} ℘ 26,10f

^{[[#fnm4][4]]} Das Hinterlegte soll nach Menge und Gewicht (G) notiert
werden. «Einnahme» und «Ausgabe» beziehen sich wohl auch noch auf das
Hinterlegte.

^{[[#fnm5][5]]} ℘ Spr 10,13; Sir 25,2

^{[[#fnm6][6]]} ℘ 7,24; Dtn 24,1

^{[[#fnm7][7]]} 14b: G: und eine schändliche Tochter gereicht zur
Schmach.

^{[[#fnm8][8]]} ℘ Gen 1; Ps 33,6; Weish 9,1

^{[[#fnm9][9]]} Der letzte Abschnitt bringt nicht mehr Weisheitsregeln
im engeren Sinn, sondern einen Lobpreis auf Gott, den Schöpfer der Welt
(42,15 - 43,33) und Lenker seines auserwählten Volkes (44,1 - 50,24).

^{[[#fnm10][10]]} ℘ Spr 15,11

^{[[#fnm11][11]]} ℘ Ps 139,1-4

^{[[#fnm12][12]]} ℘ 18,6; Koh 3,14

^{[[#fnm13][13]]} ℘ (24-25) 33,14f; Koh 3,1-8
