:PROPERTIES:
:ID:       961bdd57-27d4-4e37-9e10-577f2c8616ae
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Jesus Sirach* --
[[file:Sir_1.html][1]] ... [[file:Sir_37.html][37]]
[[file:Sir_38.html][38]] *39* [[file:Sir_40.html][40]]
[[file:Sir_41.html][41]] ... [[file:Sir_51.html][51]]

--------------

* Sir 39
  :PROPERTIES:
  :CUSTOM_ID: sir-39
  :END:

<<verses>>

<<v1>>
1 Die Weisheit aller Vorfahren ergründet er /\\
 und beschäftigt sich mit den Weissagungen;\\
\\

<<v2>>
2 er achtet auf die Reden berühmter Männer /\\
 und in die Tiefen der Sinnsprüche dringt er ein. ^{[[#fn1][1]]}\\
\\

<<v3>>
3 Er erforscht den verborgenen Sinn der Gleichnisse /\\
 und verweilt über den Rätseln der Sinnsprüche.\\
\\

<<v4>>
4 Im Kreis der Großen tut er Dienst /\\
 und erscheint vor den Fürsten; er bereist das Land fremder Völker, /\\
 erfährt Gutes und Böses unter den Menschen;\\
\\

<<v5>>
5 er richtet seinen Sinn darauf, /\\
 den Herrn, seinen Schöpfer, zu suchen, /\\
 und betet zum Höchsten; er öffnet seinen Mund zum Gebet /\\
 und fleht wegen seiner Sünden.\\
\\

<<v6>>
6 Wenn Gott, der Höchste, es will, /\\
 wird er mit dem Geist der Einsicht erfüllt: Er bringt eigene
Weisheitsworte hervor /\\
 und im Gebet preist er den Herrn.\\
\\

<<v7>>
7 Er versteht sich auf Rat und Erkenntnis /\\
 und erforscht die Geheimnisse;\\
\\

<<v8>>
8 er trägt verständige Lehre vor /\\
 und das Gesetz des Herrn ist sein Ruhm.\\
\\

<<v9>>
9 Viele loben seine Einsicht; /\\
 sie wird niemals vergehen. Sein Andenken wird nicht schwinden, /\\
 sein Name lebt fort bis in ferne Geschlechter.\\
\\

<<v10>>
10 Von seiner Weisheit erzählt die Gemeinde, /\\
 sein Lob verkündet das versammelte Volk. ^{[[#fn2][2]]}\\
\\

<<v11>>
11 Solange er lebt, wird er mehr gelobt als tausend andere; /\\
 geht er zur Ruhe ein, genügt ihm sein Nachruhm.\\
\\

<<v12>>
**** Die Einladung zum Gotteslob: 39,12-35
     :PROPERTIES:
     :CUSTOM_ID: die-einladung-zum-gotteslob-3912-35
     :END:
12 Weiterhin will ich mit Überlegung reden; /\\
 denn ich bin angefüllt wie der volle Mond.\\
\\

<<v13>>
13 Hört mich, ihr frommen Söhne, und ihr werdet gedeihen /\\
 wie die Zeder, die am Wasserlauf wächst. ^{[[#fn3][3]]}\\
\\

<<v14>>
14 Ihr werdet Duft verströmen wie der Weihrauch, /\\
 ihr werdet Blüten treiben wie die Lilie. Erhebt die Stimme und singt im
Chor, /\\
 preist den Herrn für all seine Werke! ^{[[#fn4][4]]}\\
\\

<<v15>>
15 Verherrlicht seinen Namen, /\\
 feiert ihn mit Lobgesang, /\\
 mit Liedern zu Harfe und Saitenspiel! Sprecht unter lautem Jubel: /\\
\\

<<v16>>
16 Alle Werke Gottes sind gut, /\\
 sie genügen zur rechten Zeit für jeden Bedarf. ^{[[#fn5][5]]}\\
\\

<<v17>>
17 Durch sein Wort stellt er das Meer hin wie einen Wall, /\\
 durch den Befehl seines Mundes seinen Wasserspeicher.\\
\\

<<v18>>
18 Was er will, geschieht ohne Verzug, /\\
 kein Hindernis gibt es für seine Hilfe.\\
\\

<<v19>>
19 Das Tun aller Menschen liegt vor ihm, /\\
 nichts ist verborgen vor seinen Augen. ^{[[#fn6][6]]}\\
\\

<<v20>>
20 Von Ewigkeit zu Ewigkeit blickt er hernieder. /\\
 Gibt es eine Grenze für seine Hilfe? Nichts ist klein und gering bei
ihm, /\\
 nichts ist für ihn zu unbegreiflich und zu schwer. ^{[[#fn7][7]]}\\
\\

<<v21>>
21 Man sage nicht: Wozu dies, wozu das? /\\
 Denn alles ist für seinen besonderen Zweck bestimmt. Man sage nicht:
Dies ist schlechter als das. /\\
 Denn alles ist zu seiner Zeit von Wert. ^{[[#fn8][8]][[#fn9][9]]}\\
\\

<<v22>>
22 Sein Segen strömt über wie der Nil, /\\
 wie der Eufrat tränkt er den Erdkreis.\\
\\

<<v23>>
23 So hat auch sein Zorn ganze Völker vertrieben, /\\
 er hat wasserreiches Land zur Salzwüste gemacht. ^{[[#fn10][10]]}\\
\\

<<v24>>
24 Seine Pfade sind für die Rechtschaffenden eben, /\\
 wie sie für die Verbrecher unwegsam sind. ^{[[#fn11][11]]}\\
\\

<<v25>>
25 Von Anbeginn hat er Gutes den Guten zugeteilt, /\\
 doch den Schlechten Gutes und Schlechtes.\\
\\

<<v26>>
26 Das Nötigste im Leben des Menschen sind: /\\
 Wasser, Feuer, Eisen und Salz, /\\
 kräftiger Weizen, Milch und Honig, /\\
 Blut der Trauben, Öl und Kleidung.\\
\\

<<v27>>
27 All dies dient den Guten zum Guten, /\\
 doch für die Schlechten verwandelt es sich in Schlechtes.\\
\\

<<v28>>
28 Es gibt Winde, die für das Gericht geschaffen sind /\\
 und durch ihr Wüten Berge versetzen. Ihre Kraft schütten sie aus zur
Zeit des Verderbens /\\
 und stillen den Zorn ihres Schöpfers. ^{[[#fn12][12]]}\\
\\

<<v29>>
29 Feuer und Hagel, Hunger und Pest, /\\
 auch sie sind für das Gericht erschaffen, ^{[[#fn13][13]]}\\
\\

<<v30>>
30 reißende Tiere, Skorpion und Natter, /\\
 rächendes Schwert zur Vernichtung der Frevler: Alle diese Dinge sind zu
ihrem Zweck erschaffen, /\\
 sie sind im Speicher aufbewahrt /\\
 und zu ihrer Zeit werden sie losgelassen.\\
\\

<<v31>>
31 Wenn er ihnen befiehlt, jauchzen sie auf, /\\
 sie erfüllen ihren Auftrag, /\\
 ohne seinem Wort zu widerstreben.\\
\\

<<v32>>
32 Darum stand es bei mir von Anfang an fest, /\\
 ich bedachte es und lege es schriftlich nieder:\\
\\

<<v33>>
33 Alle Werke Gottes sind gut, /\\
 sie genügen zur rechten Zeit für jeden Bedarf. ^{[[#fn14][14]]}\\
\\

<<v34>>
34 Man sage nicht: Dies ist schlechter als das. /\\
 Denn alles ist zu seiner Zeit von Wert. ^{[[#fn15][15]]}\\
\\

<<v35>>
35 Nun jubelt von ganzem Herzen /\\
 und preist den Namen des Heiligen!\\
\\

^{[[#fnm1][1]]} ℘ Spr 1,5f; Weish 8,8

^{[[#fnm2][2]]} ℘ 44,15

^{[[#fnm3][3]]} 13b: So mit S; G: wie die Rose.

^{[[#fnm4][4]]} 14c: Nach S; G verderbt.

^{[[#fnm5][5]]} ℘ 39,33

^{[[#fnm6][6]]} ℘ 15,19; Weish 1,7-10

^{[[#fnm7][7]]} 20bc: Fehlt in G.

^{[[#fnm8][8]]} ℘ Spr 16,4; Koh 3,11; Sir 39,34

^{[[#fnm9][9]]} Zeilenfolge nach H.

^{[[#fnm10][10]]} Anspielung auf die Vertreibung der Kanaaniter und den
Untergang von Sodom.

^{[[#fnm11][11]]} ℘ Ps 18,26f

^{[[#fnm12][12]]} ℘ (28-30) 40,10

^{[[#fnm13][13]]} «Feuer» bedeutet oft den Blitz. Die verheerenden
Naturkräfte sind eigens geschaffen, um an den Schlechten das Gericht zu
vollstrecken.

^{[[#fnm14][14]]} ℘ 39,16

^{[[#fnm15][15]]} ℘ 39,21
