#+TITLE: Spr 30 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-10-02 Mi 21:33]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Spr 30.html

* Spr 30

<<verses>>

<<v1>>
* Die Worte Agurs: 30,1-14

1 Worte Agurs, des Sohnes des Jake aus Massa. Spruch des Mannes Laïtiël:
/\\
 Ich mühte mich ab mit Gott und bin am Ende. [fn:1]\\
\\

<<v2>>
2 Denn ich bin zu dumm für einen Menschen, /\\
 ich habe keinen Menschenverstand,\\
\\

<<v3>>
3 ich habe keine Weisheit gelernt /\\
 und keine Kenntnis des Heiligen erlangt. [fn:2]\\
\\

<<v4>>
4 Wer stieg zum Himmel hinauf und kam wieder herab? /\\
 Wer sammelte den Wind in seine Fäuste? /\\
 Wer band das Wasser in ein Gewand? /\\
 Wer setzte fest alle Enden der Erde? /\\
 Wie ist sein Name und wie der Name seines Sohnes, wenn du es weißt? [fn:3]\\
\\

<<v5>>
5 Jede Rede Gottes ist im Feuer geläutert; /\\
 ein Schild ist er für alle, die bei ihm sich bergen. [fn:4]\\
\\

<<v6>>
6 Füg seinen Worten nichts hinzu, /\\
 sonst überführt er dich und du stehst als Lügner da.\\
\\

<<v7>>
7 Um zweierlei bitte ich dich, /\\
 versag es mir nicht, bevor ich sterbe: [fn:5]\\
\\

<<v8>>
8 Falschheit und Lügenwort halt fern von mir; /\\
 gib mir weder Armut noch Reichtum, /\\
 nähr mich mit dem Brot, das mir nötig ist,\\
\\

<<v9>>
9 damit ich nicht, satt geworden, dich verleugne /\\
 und sage: Wer ist denn der Herr?, damit ich nicht als Armer zum Dieb
werde /\\
 und mich am Namen meines Gottes vergreife. [fn:6]\\
\\

<<v10>>
10 Verleumde nicht den Knecht bei seinem Herrn, /\\
 sonst verflucht er dich und du musst es büßen.\\
\\

<<v11>>
11 Ein Geschlecht, das seinem Vater flucht /\\
 und seine Mutter nicht segnet; [fn:7]\\
\\

<<v12>>
12 ein Geschlecht, das rein ist in den eigenen Augen, /\\
 doch nicht gewaschen von seinem Schmutz;\\
\\

<<v13>>
13 ein Geschlecht - wie überheblich sind seine Augen /\\
 und wie hochmütig seine Wimpern;\\
\\

<<v14>>
14 ein Geschlecht, dessen Zähne Schwerter /\\
 und dessen Gebiss Messer sind, /\\
 um die Notleidenden aus dem Land wegzufressen /\\
 und die Armen weg aus der Menschheit.\\
\\

<<v15>>
* Die Zahlensprüche: 30,15-33

15 Der Blutegel hat zwei Töchter: Gib! - Gib! Drei sind es, die nie satt
werden, /\\
 vier sagen nie: Genug: [fn:8]\\
\\

<<v16>>
16 Die Unterwelt und der unfruchtbare Mutterschoß, /\\
 die Erde, die nicht satt wird an Wasser, /\\
 und das Feuer, das nie sagt: Genug!\\
\\

<<v17>>
17 Ein Auge, das den Vater verspottet /\\
 und die alte Mutter verachtet, /\\
 das hacken die Raben am Bach aus, /\\
 die jungen Adler fressen es auf. [fn:9]\\
\\

<<v18>>
18 Drei Dinge sind mir unbegreiflich, /\\
 vier vermag ich nicht zu fassen:\\
\\

<<v19>>
19 den Weg des Adlers am Himmel, /\\
 den Weg der Schlange über den Felsen, /\\
 den Weg des Schiffes auf hoher See, /\\
 den Weg des Mannes bei der jungen Frau.\\
\\

<<v20>>
20 So benimmt sich die ehebrecherische Frau: /\\
 Sie isst, wischt sich den Mund /\\
 und sagt: Ich habe nichts Böses getan.\\
\\

<<v21>>
21 Unter dreien erzittert das Land, /\\
 unter vieren wird es ihm unerträglich:\\
\\

<<v22>>
22 unter einem Sklaven, wenn er König wird, /\\
 und einem Toren, wenn er Brot im Überfluss hat,\\
\\

<<v23>>
23 unter einer Verschmähten, wenn sie geheiratet wird, /\\
 und einer Sklavin, wenn sie ihre Herrin verdrängt.\\
\\

<<v24>>
24 Vier sind die Kleinsten auf Erden /\\
 und sind doch die Allerklügsten:\\
\\

<<v25>>
25 Die Ameisen sind kein starkes Volk /\\
 und besorgen sich doch im Sommer ihr Futter; [fn:10]\\
\\

<<v26>>
26 Klippdachse sind ein Volk ohne Macht /\\
 und doch bauen sie ihre Wohnung im Fels; [fn:11]\\
\\

<<v27>>
27 die Heuschrecken haben keinen König /\\
 und doch schwärmen sie alle geordnet aus;\\
\\

<<v28>>
28 Eidechsen fängst du mit der Hand /\\
 und doch wohnen sie in Königspalästen.\\
\\

<<v29>>
29 Drei sind es, die stolz einherschreiten, /\\
 vier haben einen stolzen Gang:\\
\\

<<v30>>
30 der Löwe, der Held unter den Tieren, /\\
 der vor keinem umkehrt;\\
\\

<<v31>>
31 der Hahn, der einherstolziert, und der Leitbock /\\
 und der König, wenn er vor seinem Volk auftritt wie ein Gott. [fn:12]\\
\\

<<v32>>
32 Wenn du dich stolz erhoben und dabei blamiert hast /\\
 oder wenn du nachdenkst - so leg die Hand auf den Mund! [fn:13]\\
\\

<<v33>>
33 Denn stößt man Milch, so gibt es Butter, /\\
 stößt man die Nase, so gibt es Blut, /\\
 stößt man den Zorn, so gibt es Streit.\\
\\

* Footnotes

[fn:1] 1-14: Die zwei letzten Kapitel bringen Anhänge an die
zweite salomonische Sammlung. Die Worte Agurs aus dem ismaëlitischen
Massa (?) scheinen bis [[v14][30,14]] zu reichen. Sie stehen in G hinter [[file:Spr_24.org::v22][24,22]].
Das Gebet in VV. 7-9, der Vers 10 und die VV. 11-14 sind inhaltlich
selbstständig. Laïtiël, der Beiname Agurs, konnte verstanden werden als:
Ich mühte mich ab mit Gott.

[fn:2] [[file:Spr_9.org::v10][9,10]]

[fn:3] [[file:Ijob_38.org::v1][Ijob 38,1-35]]

[fn:4] [[file:Ps_18.org::v31][Ps 18,31]]

[fn:5] 7-9: Das Stichwort «Lüge» veranlasste wohl den Einschub
des Gebets des Bescheidenen.

[fn:6] [[file:Sir_5.org::v1][Sir 5,1-3]]

[fn:7] 11a.12a.13a.14a: Der Anfang dieser Worte meint
sinngemäß: Weh dem Geschlecht ...

[fn:8] 15-33: Die selbstständige Gruppe der Zahlensprüche und
die Worte an Lemuël ([[file:Spr_31.org::v1][31,1-9]]) stehen in G hinter 24,34. 15a: Wohl ein
versprengtes Fragment. - Der Blutegel ist Bild für den Habsüchtigen;
seine beiden «Töchter» sind seine Saug- und Haftorgane.

[fn:9] Eine Unterbrechung, wohl verursacht durch das Stichwort
«Adler» in V. 19. Eine andere Erweiterung ist V. 20.

[fn:10] [[file:Spr_6.org::v6][6,6-8]]

[fn:11] [[file:Ps_104.org::v18][Ps 104,18]]

[fn:12] H ist unklar.

[fn:13] 32a: blamiert, wörtlich: als Tor erwiesen.
