#+TITLE: Spr 1 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-21 Mi 14:07]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Spr 1.html

* Spr 1

Sprichwörter sind bei allen Völkern sehr verbreitet und nehmen besonders
in den Literaturen des Alten Orients eine bedeutende Stelle ein. Im
alten Israel war es vor allem der wegen seiner Weisheit berühmte König
Salomo, dem zahlreiche Lieder und gelehrte Aussprüche zugeschrieben
wurden (1 Kön 5,12-14). Kein Wunder, dass die spätere Tradition in ihm
auch den Verfasser des Buches der Sprichwörter gesehen hat (1,1).
Ausdrücklich wird er als Verfasser der beiden Hauptsammlungen 10,1 -
22,16 und 25,1 - 29,27 genannt. Weil in den Sammlungen seiner
Sprichwörter schriftlich und mündlich überliefertes Material
zusammengetragen und fortlaufend erweitert wurde, ist es nicht möglich,
den Anteil Salomos an den beiden Hauptsammlungen herauszuschälen. Von
der zweiten salomonischen Sammlung wird erwähnt, dass sie von den
»Männern Hiskijas, des Königs von Juda«, zusammengestellt wurde
(25,1).\\
\\
Eine zweite Blütezeit erlebte die Weisheitsliteratur in der
nachexilischen Epoche. Damals entstanden die Bücher Ijob und Kohelet und
etwas später Sirach und Weisheit. In dieser Spätzeit sind auch die
Anhänge an die zwei genannten salomonischen Sammlungen angefügt worden:
»Worte von Weisen« (22,17 - 24,34), »Worte Agurs« (30,1-14), die
Zahlensprüche (30,15-33), »Worte an Lemuël« (31,1-9) sowie, als
Abschluss des Buches, das Loblied auf die tüchtige Frau (31,10-31). Von
den Sprichwörtersammlungen hebt sich die lange Einleitung (Kap. 1 - 9)
ab. In ihr stehen größtenteils zusammenhängende Mahnungen eines
Weisheitslehrers, der vor Torheit warnt und Weisheit empfiehlt. Für die
Endfassung des Buchs kommt somit die Nachexilszeit bis hinab zur
griechischen Übersetzung in Frage, also etwa 500 bis 200 v. Chr.
Herkunft und Alter der einzelnen Teile und erst recht der einzelnen
Sprichwörter können sehr verschieden sein.\\
\\
Die Schlüsselwörter »Weisheit« und »Torheit« sind nicht allein vom
Verstand her aufzufassen. »Weisheit« ist vielmehr der Inbegriff einer
charaktervollen, religiös und sittlich intakten Verhaltensweise in allen
Lebenslagen. Das ganze Buch hat eine erzieherische Tendenz; daher
spricht besonders in den ersten neun Kapiteln der Weisheitslehrer wie
ein Vater zu seinem Sohn.\\
\\
Für die nachexilische Entwicklung der Weisheitsliteratur ist typisch,
dass die »Weisheit« (in 9,13-18 auch die »Torheit«) personifiziert wird
und selbstständig redend und handelnd auftritt (vgl. schon 1,20-33). Im
Hymnus 8,22-36 stellt sie sich als Erstling der Schöpfung vor. Da sie in
Wirklichkeit die göttliche Weisheit selbst ist, steht sie Gott bei der
Weltschöpfung zur Verfügung. Sie kann aber auch den Menschen und dem
Volk Israel mitgeteilt werden.\\
\\
Die eigentlichen Sprichwörter, die den größten Teil des Buches
ausfüllen, haben ihre Wurzel im Volksmund. Deshalb sind sie manchmal
etwas derb, stellen drastische Vergleiche an und bieten alltägliche und
allgemein menschliche Lebenserfahrungen. Gelegentlich formulieren sie,
um einprägsame Kürze zu erreichen, einseitig. Der Vorteil und der
materielle Nutzen der Weisheit wird im Sprichwort besonders stark
betont. Doch steht selbst hinter den profanen Sprichwörtern eine
religiöse Grundhaltung und wenigstens ein Siebtel aller Verse nimmt auf
den Gottesglauben Bezug. Der Grundsatz »Anfang der Weisheit ist die
Gottesfurcht« (vgl. 1,7; 9,10; Ps 111,10; Sir 1,14) rückt alles Streben
nach Weisheit, auch das rein innerweltliche, in eine Beziehung zu Gott.
Im Neuen Testament wird unser Buch oft wörtlich oder dem Sinn nach
angeführt. Einige Sprichwörter sind auch in den deutschen Sprachschatz
eingegangen (vgl. 16,18; 24,16; 25,21f; 26,27).\\
\\

<<verses>>

<<v1>>
* Einleitung: 1,1-7

1 Sprichwörter Salomos, des Sohnes Davids, /\\
 des Königs von Israel:\\
\\

<<v2>>
2 um Weisheit zu lernen und Zucht, /\\
 um kundige Rede zu verstehen,\\
\\

<<v3>>
3 um Zucht und Verständnis zu erlangen, /\\
 Gerechtigkeit, Rechtssinn und Redlichkeit,\\
\\

<<v4>>
4 um Unerfahrenen Klugheit zu verleihen, /\\
 der Jugend Kenntnis und Umsicht.\\
\\

<<v5>>
5 Der Weise höre und vermehre sein Wissen, /\\
 der Verständige lerne kluge Führung, [fn:1]\\
\\

<<v6>>
6 um Sinnspruch und Gleichnis zu verstehen, /\\
 die Worte und Rätsel der Weisen.\\
\\

<<v7>>
7 Gottesfurcht ist Anfang der Erkenntnis, /\\
 nur Toren verachten Weisheit und Zucht. [fn:2]\\
\\

<<v8>>
* Eine Sammlung von Weisheitslehren: 1,8 - 9,18

* Die Warnung vor Verführung und Unerfahrenheit: 1,8 - 3,35

8 Höre, mein Sohn, auf die Mahnung des Vaters /\\
 und die Lehre deiner Mutter verwirf nicht! [fn:3]\\
\\

<<v9>>
9 Sie sind ein schöner Kranz auf deinem Haupt /\\
 und eine Kette für deinen Hals.\\
\\

<<v10>>
10 Mein Sohn, wenn dich Sünder locken, /\\
 dann folg ihnen nicht,\\
\\

<<v11>>
11 wenn sie sagen: Geh mit uns, /\\
 wir wollen darauf lauern, Blut zu vergießen, /\\
 ohne Grund dem Arglosen nachzustellen;\\
\\

<<v12>>
12 wie die Unterwelt wollen wir sie lebendig verschlingen, /\\
 Männer in ihrer Kraft, als wären sie dem Grab verfallen.\\
\\

<<v13>>
13 Manch kostbares Stück werden wir finden, /\\
 mit Beute unsere Häuser füllen.\\
\\

<<v14>>
14 Wirf dein Los in unserm Kreis, /\\
 gemeinsam sei uns der Beutel.\\
\\

<<v15>>
15 Mein Sohn, geh nicht mit ihnen, /\\
 halte deinen Fuß fern von ihrem Pfad!\\
\\

<<v16>>
16 Denn ihre Füße laufen dem Bösen nach, /\\
 sie eilen, Blut zu vergießen. [fn:4]\\
\\

<<v17>>
17 Umsonst wird das Netz ausgespannt /\\
 vor den Augen aller Vögel; [fn:5]\\
\\

<<v18>>
18 sie aber lauern auf ihr eigenes Blut, /\\
 sie trachten sich selbst nach dem Leben.\\
\\

<<v19>>
19 So enden alle, die sich durch Raub bereichern: /\\
 Wer ihn an sich nimmt, dem raubt er das Leben.\\
\\

<<v20>>
20 Die Weisheit ruft laut auf der Straße, /\\
 auf den Plätzen erhebt sie ihre Stimme. [fn:6] [fn:7]\\
\\

<<v21>>
21 Am Anfang der Mauern predigt sie, /\\
 an den Stadttoren hält sie ihre Reden:\\
\\

<<v22>>
22 Wie lang noch, ihr Törichten, liebt ihr Betörung, /\\
 gefällt den Zuchtlosen ihr dreistes Gerede, /\\
 hassen die Toren Erkenntnis?\\
\\

<<v23>>
23 Wendet euch meiner Mahnung zu! /\\
 Dann will ich auf euch meinen Geist ausgießen /\\
 und meine Worte euch kundtun.\\
\\

<<v24>>
24 Als ich rief, habt ihr euch geweigert, /\\
 meine drohende Hand hat keiner beachtet;\\
\\

<<v25>>
25 jeden Rat, den ich gab, habt ihr ausgeschlagen, /\\
 meine Mahnung gefiel euch nicht.\\
\\

<<v26>>
26 Darum werde auch ich lachen, /\\
 wenn euch Unglück trifft, /\\
 werde spotten, wenn Schrecken über euch kommt,\\
\\

<<v27>>
27 wenn der Schrecken euch wie ein Unwetter naht /\\
 und wie ein Sturm euer Unglück hereinbricht, /\\
 wenn Not und Drangsal euch überfallen.\\
\\

<<v28>>
28 Dann werden sie nach mir rufen, doch ich höre nicht; /\\
 sie werden mich suchen, aber nicht finden.\\
\\

<<v29>>
29 Weil sie die Einsicht hassten /\\
 und nicht die Gottesfurcht wählten,\\
\\

<<v30>>
30 meinen Rat nicht wollten, /\\
 meine ganze Mahnung missachteten,\\
\\

<<v31>>
31 sollen sie nun essen von der Frucht ihres Tuns /\\
 und von ihren Plänen sich sättigen.\\
\\

<<v32>>
32 Denn die Abtrünnigkeit der Haltlosen ist ihr Tod, /\\
 die Sorglosigkeit der Toren ist ihr Verderben.\\
\\

<<v33>>
33 Wer aber auf mich hört, wohnt in Sicherheit, /\\
 ihn stört kein böser Schrecken.\\
\\

* Footnotes

[fn:1] [[file:Spr_9.org::v9][9,9]]

[fn:2] [[file:Spr_9.org::v10][9,10]]; [[file:Ps_111.org::v10][Ps 111,10]]; [[v14][Sir 1,14]]

[fn:3] [[file:Spr_6.org::v20][6,20]]; [[file:Spr_23.org::v22][23,22]]

[fn:4] [[file:Jes_59.org::v7][Jes 59,7]]; [[file:~/RoamNotes/notes/Bibel/nt/Röm_3.org::v15][Röm 3,15]]

[fn:5] 17f: Sinn: Die Vögel meiden ein Netz, das sie sehen; die
Verführer aber rennen in ihr eigenes Verderben.

[fn:6] [[file:Spr_8.org::v1][8,1-3]]; [[file:Sir_24.org::v1][Sir 24,1f]]

[fn:7] 20-33: Die Weisheit wird als Bußpredigerin
personifiziert.
