#+TITLE: Spr 5 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-21 Mi 21:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Spr 5.html

* Spr 5

<<verses>>

<<v1>>
* Die Warnung vor der fremden Frau: 5,1-23

1 Mein Sohn, merk auf meinen weisen Rat, /\\
 neige meiner Einsicht dein Ohr zu, [fn:1] [fn:2]\\
\\

<<v2>>
2 damit du Besonnenheit bewahrst /\\
 und deine Lippen auf Klugheit achten.\\
\\

<<v3>>
3 Denn die Lippen der fremden Frau triefen von Honig, /\\
 glatter als Öl ist ihr Mund. [fn:3]\\
\\

<<v4>>
4 Doch zuletzt ist sie bitter wie Wermut, /\\
 scharf wie ein zweischneidiges Schwert.\\
\\

<<v5>>
5 Ihre Füße steigen zur Totenwelt hinab, /\\
 ihre Schritte gehen der Unterwelt zu. [fn:4]\\
\\

<<v6>>
6 Den ebenen Pfad zum Leben verfehlt sie, /\\
 sie geht krumme Wege und merkt es nicht.\\
\\

<<v7>>
7 Nun denn, ihr Söhne, hört auf mich, /\\
 weicht nicht ab von den Worten, die mein Mund spricht.\\
\\

<<v8>>
8 Halte deinen Weg von ihr fern, /\\
 komm ihrer Haustür nicht nahe!\\
\\

<<v9>>
9 Sonst schenkst du andern deine Kraft, /\\
 deine Jahre einem Rücksichtslosen;\\
\\

<<v10>>
10 sonst sättigen sich Fremde an deinem Besitz, /\\
 die Frucht deiner Arbeit /\\
 kommt in das Haus eines andern\\
\\

<<v11>>
11 und am Ende wirst du stöhnen, /\\
 wenn dein Leib und dein Fleisch dahinsiechen.\\
\\

<<v12>>
12 Dann wirst du bekennen: /\\
 Weh mir, ich habe die Zucht gehasst, /\\
 mein Herz hat die Warnung verschmäht;\\
\\

<<v13>>
13 ich habe nicht auf die Stimme meiner Erzieher gehört, /\\
 mein Ohr nicht meinen Lehrern zugeneigt.\\
\\

<<v14>>
14 Fast hätte mich alles Unheil getroffen /\\
 in der Versammlung und in der Gemeinde. [fn:5]\\
\\

<<v15>>
15 Trink Wasser aus deiner eigenen Zisterne, /\\
 Wasser, das aus deinem Brunnen quillt. [fn:6]\\
\\

<<v16>>
16 Sollen deine Quellen auf die Straße fließen, /\\
 auf die freien Plätze deine Bäche?\\
\\

<<v17>>
17 Dir allein sollen sie gehören, /\\
 kein Fremder soll teilen mit dir.\\
\\

<<v18>>
18 Dein Brunnen sei gesegnet; /\\
 freu dich der Frau deiner Jugendtage,\\
\\

<<v19>>
19 der lieblichen Gazelle, der anmutigen Gämse! /\\
 Ihre Liebkosung mache dich immerfort trunken, /\\
 an ihrer Liebe berausch dich immer wieder!\\
\\

<<v20>>
20 Warum solltest du dich an einer Fremden berauschen, /\\
 den Busen einer andern umfangen?\\
\\

<<v21>>
21 Denn der Weg eines jeden liegt offen vor den Augen des Herrn, /\\
 er achtet auf alle seine Pfade.\\
\\

<<v22>>
22 Der Frevler verfängt sich in der eigenen Schuld, /\\
 die Stricke seiner Sünde halten ihn fest.\\
\\

<<v23>>
23 Er stirbt aus Mangel an Zucht, /\\
 wegen seiner großen Torheit stürzt er ins Verderben.\\
\\

* Footnotes

[fn:1] (1-23) [[file:Spr_7.org::v1][7,1-27]]

[fn:2] 1-23: Der junge Mann wird besonders oft und eindringlich
vor der «fremden» Frau, d. h. der bereits verheirateten, gewarnt. In der
späten Nachexilszeit setzte sich die Einehe immer mehr durch.

[fn:3] [[file:Spr_26.org::v9][Sir 26,9-27]]

[fn:4] [[file:Spr_2.org::v18][2,18]]; [[file:Spr_7.org::v27][7,27]]

[fn:5] Auf Ehebruch stand nach [[file:Lev_20.org::v10][Lev 20,10]] und [[file:Dtn_22.org::v22][Dtn 22,22]] die Todesstrafe, die von der Versammlung am Stadttor verhängt wurde (vgl. [[file:Dan_13.org::v41][Dan 13,41]])

[fn:6] D. h.: Begnüge dich mit deiner eigenen Frau!
