#+TITLE: Spr 31 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-10-02 Mi 21:42]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Spr 31.html

* Spr 31

<<verses>>

<<v1>>
* Die Worte an Lemuël: 31,1-9

1 Worte an Lemuël, den König von Massa, mit denen ihn seine Mutter
ermahnt hat: [fn:1]\\
\\

<<v2>>
2 Was soll ich dir sagen, Lemuël, mein Erstgeborener, /\\
 du Sohn meines Schoßes, /\\
 was, du Sohn meiner Gelübde? [fn:2] [fn:3]\\
\\

<<v3>>
3 Gib deine Kraft nicht den Frauen hin, /\\
 dein Tun und Treiben nicht denen, die Könige verderben. [fn:4]\\
\\

<<v4>>
4 Könige sollen sich nicht, Lemuël, /\\
 Könige sollen sich nicht mit Wein betrinken, /\\
 Fürsten nicht berauschenden Trank begehren. [fn:5]\\
\\

<<v5>>
5 Er könnte beim Trinken seine Pflicht vergessen /\\
 und das Recht aller Notleidenden verdrehen.\\
\\

<<v6>>
6 Gebt berauschenden Trank dem, der zusammenbricht, /\\
 und Wein denen, die im Herzen verbittert sind.\\
\\

<<v7>>
7 Ein solcher möge trinken und seine Armut vergessen /\\
 und nicht mehr an seine Mühsal denken.\\
\\

<<v8>>
8 Öffne deinen Mund für den Stummen, /\\
 für das Recht aller Schwachen!\\
\\

<<v9>>
9 Öffne deinen Mund, richte gerecht, /\\
 verschaff dem Bedürftigen und Armen Recht!\\
\\

<<v10>>
* Das Lob der tüchtigen Frau: 31,10-31

10 Eine tüchtige Frau, wer findet sie? /\\
 Sie übertrifft alle Perlen an Wert. [fn:6]\\
\\

<<v11>>
11 Das Herz ihres Mannes vertraut auf sie /\\
 und es fehlt ihm nicht an Gewinn.\\
\\

<<v12>>
12 Sie tut ihm Gutes und nichts Böses /\\
 alle Tage ihres Lebens.\\
\\

<<v13>>
13 Sie sorgt für Wolle und Flachs /\\
 und schafft mit emsigen Händen.\\
\\

<<v14>>
14 Sie gleicht den Schiffen des Kaufmanns: /\\
 Aus der Ferne holt sie ihre Nahrung.\\
\\

<<v15>>
15 Noch bei Nacht steht sie auf, /\\
 um ihrem Haus Speise zu geben /\\
 [und den Mägden, was ihnen zusteht]. [fn:7]\\
\\

<<v16>>
16 Sie überlegt es und kauft einen Acker, /\\
 vom Ertrag ihrer Hände pflanzt sie einen Weinberg.\\
\\

<<v17>>
17 Sie gürtet ihre Hüften mit Kraft /\\
 und macht ihre Arme stark.\\
\\

<<v18>>
18 Sie spürt den Erfolg ihrer Arbeit, /\\
 auch des Nachts erlischt ihre Lampe nicht.\\
\\

<<v19>>
19 Nach dem Spinnrocken greift ihre Hand, /\\
 ihre Finger fassen die Spindel.\\
\\

<<v20>>
20 Sie öffnet ihre Hand für den Bedürftigen /\\
 und reicht ihre Hände dem Armen.\\
\\

<<v21>>
21 Ihr bangt nicht für ihr Haus vor dem Schnee; /\\
 denn ihr ganzes Haus hat wollene Kleider.\\
\\

<<v22>>
22 Sie hat sich Decken gefertigt, /\\
 Leinen und Purpur sind ihr Gewand.\\
\\

<<v23>>
23 Ihr Mann ist in den Torhallen geachtet, /\\
 wenn er zu Rat sitzt mit den Ältesten des Landes.\\
\\

<<v24>>
24 Sie webt Tücher und verkauft sie, /\\
 Gürtel liefert sie dem Händler.\\
\\

<<v25>>
25 Kraft und Würde sind ihr Gewand, /\\
 sie spottet der drohenden Zukunft.\\
\\

<<v26>>
26 Öffnet sie ihren Mund, dann redet sie klug /\\
 und gütige Lehre ist auf ihrer Zunge.\\
\\

<<v27>>
27 Sie achtet auf das, was vorgeht im Haus, /\\
 und isst nicht träge ihr Brot.\\
\\

<<v28>>
28 Ihre Söhne stehen auf und preisen sie glücklich, /\\
 auch ihr Mann erhebt sich und rühmt sie:\\
\\

<<v29>>
29 Viele Frauen erwiesen sich tüchtig, /\\
 doch du übertriffst sie alle.\\
\\

<<v30>>
30 Trügerisch ist Anmut, vergänglich die Schönheit, /\\
 nur eine gottesfürchtige Frau verdient Lob.\\
\\

<<v31>>
31 Preist sie für den Ertrag ihrer Hände, /\\
 ihre Werke soll man am Stadttor loben.\\
\\

* Footnotes

[fn:1] Wie Agur (vgl. [[file:Spr_30.org::v1][30,1]]) stammt auch Lemuël aus dem
nordarabischen Massa. Sprachliche Anklänge an das Aramäische und der
eigenartige Inhalt weisen auf nichtisraelitischen Ursprung hin.

[fn:2] [[file:1.Sam_1.org::v11][1 Sam 1,11]]

[fn:3] 2a: Ergänzt nach G; H hat kein Zeitwort.

[fn:4] 3b: dein Tun und Treiben, wörtlich: deine Wege.

[fn:5] [[file:Koh_10.org::v16][Koh 10,16]]

[fn:6] 10-31: Dieses Lied dürfte zu den jüngsten Teilen des
Buches gehören. In H beginnen die Verse der Reihe nach mit den
Buchstaben des hebräischen Alphabets.

[fn:7] [[file:Spr_27.org::v27][27,27]]
