#+TITLE: Spr 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-21 Mi 21:47]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Spr 7.html

* Spr 7

<<verses>>

<<v1>>
1 Mein Sohn, achte auf meine Worte, /\\
 meine Gebote verwahre bei dir!\\
\\

<<v2>>
2 Achte auf meine Gebote, damit du am Leben bleibst, /\\
 hüte meine Lehre wie deinen Augapfel!\\
\\

<<v3>>
3 Binde sie dir an die Finger, /\\
 schreib sie auf die Tafel deines Herzens!\\
\\

<<v4>>
4 Sag zur Weisheit: Du bist meine Schwester!, /\\
 und nenne die Klugheit deine Freundin!\\
\\

<<v5>>
5 Sie bewahrt dich vor der Frau eines andern, /\\
 vor der Fremden, die verführerisch redet. [fn:1]\\
\\

<<v6>>
6 Vom Fenster meines Hauses, /\\
 durch das Gitter, habe ich ausgeschaut; [fn:2]\\
\\

<<v7>>
7 da sah ich bei den Unerfahrenen, /\\
 da bemerkte ich bei den Burschen /\\
 einen jungen Mann ohne Verstand:\\
\\

<<v8>>
8 Er ging über die Straße, bog um die Ecke /\\
 und nahm den Weg zu ihrem Haus;\\
\\

<<v9>>
9 als der Tag sich neigte, in der Abenddämmerung, /\\
 um die Zeit, da es dunkel wird und die Nacht kommt.\\
\\

<<v10>>
10 Da! Eine Frau kommt auf ihn zu, /\\
 im Kleid der Dirnen, mit listiger Absicht;\\
\\

<<v11>>
11 voll Leidenschaft ist sie und unbändig, /\\
 ihre Füße blieben nicht mehr im Haus;\\
\\

<<v12>>
12 bald auf den Gassen, bald auf den Plätzen, /\\
 an allen Straßenecken lauert sie.\\
\\

<<v13>>
13 Nun packt sie ihn, küsst ihn, /\\
 sagt zu ihm mit keckem Gesicht:\\
\\

<<v14>>
14 Ich war zu Heilsopfern verpflichtet /\\
 und heute erfüllte ich meine Gelübde.\\
\\

<<v15>>
15 Darum bin ich ausgegangen, dir entgegen, /\\
 ich habe dich gesucht und gefunden.\\
\\

<<v16>>
16 Ich habe Decken über mein Bett gebreitet, /\\
 bunte Tücher aus ägyptischem Leinen;\\
\\

<<v17>>
17 ich habe mein Lager besprengt /\\
 mit Myrrhe, Aloe und Zimt.\\
\\

<<v18>>
18 Komm, wir wollen bis zum Morgen in Liebe schwelgen, /\\
 wir wollen die Liebeslust kosten.\\
\\

<<v19>>
19 Denn mein Mann ist nicht zu Hause, /\\
 er ist auf Reisen, weit fort.\\
\\

<<v20>>
20 Den Geldbeutel hat er mitgenommen, /\\
 erst am Vollmondstag kehrt er heim.\\
\\

<<v21>>
21 So macht sie ihn willig mit viel Überredung, /\\
 mit schmeichelnden Lippen verführt sie ihn.\\
\\

<<v22>>
22 Betört folgt er ihr, /\\
 wie ein Ochse, den man zum Schlachten führt, /\\
 wie ein Hirsch, den das Fangseil umschlingt,\\
\\

<<v23>>
23 bis ein Pfeil ihm die Leber zerreißt; /\\
 wie ein Vogel, der in das Netz fliegt /\\
 und nicht merkt, dass es um sein Leben geht.\\
\\

<<v24>>
24 Darum, ihr Söhne, hört auf mich, /\\
 achtet auf meine Reden! [fn:3]\\
\\

<<v25>>
25 Dein Herz schweife nicht ab auf ihre Wege, /\\
 verirre dich nicht auf ihre Pfade!\\
\\

<<v26>>
26 Denn zahlreich sind die Erschlagenen, /\\
 die sie gefällt hat; /\\
 viele sind es, die sie ermordet hat;\\
\\

<<v27>>
27 ihr Haus ist ein Weg zur Unterwelt, /\\
 er führt zu den Kammern des Todes. [fn:4]\\
\\

* Footnotes

[fn:1] [[file:Spr_2.org::v16][2,16]]; [[file:Spr_6.org::v24][6,24]]

[fn:2] 6-27: Hier wird das Thema «fremde Frau» breit entfaltet.
Untergang und Tod sind immer das Ende.

[fn:3] [[file:Spr_1.org::v8][1,8]]; [[file:Spr_4.org::v1][4,1]]; [[file:Spr_5.org::v7][5,7]]

[fn:4] [[file:Spr_5.org::v5][5,5]]; [[file:Spr_9.org::v18][9,18]]
