#+TITLE: Spr 10 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-24 Sa 00:00]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Spr 10.html

* Spr 10

<<verses>>

<<v1>>
* Die erste salomonische Spruchsammlung: 10,1 - 22,16

1 Sprichwörter Salomos: Ein kluger Sohn macht dem Vater Freude, /\\
 ein dummer Sohn ist der Kummer seiner Mutter. [fn:1]\\
\\

<<v2>>
2 Unrecht Gut gedeiht nicht, /\\
 Gerechtigkeit aber rettet vor dem Tod. [fn:2]\\
\\

<<v3>>
3 Das Verlangen des Gerechten sättigt der Herr, /\\
 die Gier der Frevler stößt er zurück.\\
\\

<<v4>>
4 Lässige Hand bringt Armut, /\\
 fleißige Hand macht reich. [fn:3]\\
\\

<<v5>>
5 Wer im Sommer sammelt, ist ein kluger Mensch; /\\
 in Schande gerät, wer zur Erntezeit schläft.\\
\\

<<v6>>
6 Segen ruht auf dem Haupt des Gerechten, /\\
 im Mund der Frevler versteckt sich Gewalttat.\\
\\

<<v7>>
7 Das Andenken des Gerechten ist gesegnet, /\\
 der Name der Frevler vermodert.\\
\\

<<v8>>
8 Verständiger Sinn nimmt die Gebote an, /\\
 wer Törichtes redet, kommt zu Fall.\\
\\

<<v9>>
9 Wer aufrichtig seinen Weg geht, geht sicher, /\\
 wer krumme Wege geht, wird durchschaut.\\
\\

<<v10>>
10 Wer mit den Augen zwinkert, schafft Leid, /\\
 wer offen tadelt, stiftet Frieden. [fn:4] [fn:5]\\
\\

<<v11>>
11 Der Mund des Gerechten ist ein Lebensquell, /\\
 im Mund der Frevler versteckt sich Gewalttat.\\
\\

<<v12>>
12 Hass weckt Streit, /\\
 Liebe deckt alle Vergehen zu.\\
\\

<<v13>>
13 Auf den Lippen des Einsichtigen findet man Weisheit, /\\
 auf den Rücken des Unverständigen passt der Stock. [fn:6]\\
\\

<<v14>>
14 Weise verbergen ihr Wissen, /\\
 der Mund des Toren ist drohendes Verderben.\\
\\

<<v15>>
15 Dem Reichen ist seine Habe eine feste Burg, /\\
 dem Armen bringt seine Armut Verderben.\\
\\

<<v16>>
16 Der Besitz des Gerechten führt zum Leben, /\\
 das Einkommen des Frevlers zur Sünde.\\
\\

<<v17>>
17 Den Weg zum Leben geht, wer Zucht bewahrt; /\\
 wer Warnung missachtet, geht in die Irre.\\
\\

<<v18>>
18 Wer Hass verbirgt, heuchelt; /\\
 wer Verleumdung ausstreut, ist ein Tor.\\
\\

<<v19>>
19 Bei vielem Reden bleibt die Sünde nicht aus, /\\
 wer seine Lippen zügelt, ist klug.\\
\\

<<v20>>
20 Erlesenes Silber ist die Zunge des Gerechten, /\\
 das Sinnen des Frevlers ist wenig wert.\\
\\

<<v21>>
21 Die Lippen des Gerechten leiten viele, /\\
 die Toren sterben an Unverstand.\\
\\

<<v22>>
22 Der Segen des Herrn macht reich, /\\
 eigene Mühe tut nichts hinzu.\\
\\

<<v23>>
23 Des Toren Freude ist es, Böses zu tun, /\\
 des Verständigen Freude, weise zu sein.\\
\\

<<v24>>
24 Was der Frevler fürchtet, kommt über ihn, /\\
 was die Gerechten ersehnen, wird ihnen zuteil. [fn:7]\\
\\

<<v25>>
25 Wenn der Sturm daherbraust, ist der Frevler verloren, /\\
 der Gerechte ist fest gegründet für immer. [fn:8]\\
\\

<<v26>>
26 Wie Essig für die Zähne und Rauch für die Augen /\\
 ist der Faule für den, der ihn schickt.\\
\\

<<v27>>
27 Gottesfurcht bringt langes Leben, /\\
 doch die Jahre der Frevler sind verkürzt.\\
\\

<<v28>>
28 Die Hoffnung der Gerechten blüht auf, /\\
 die Erwartung der Frevler wird zunichte.\\
\\

<<v29>>
29 Dem Schuldlosen ist der Herr eine Zuflucht, /\\
 Verderben aber den Übeltätern.\\
\\

<<v30>>
30 Der Gerechte wird niemals wanken, /\\
 doch die Frevler bleiben nicht im Land wohnen.\\
\\

<<v31>>
31 Der Mund des Gerechten bringt Weisheit hervor, /\\
 eine Zunge voll Falschheit aber wird abgeschnitten.\\
\\

<<v32>>
32 Die Lippen des Gerechten achten auf das, was gefällt, /\\
 der Mund der Frevler aber auf das, was verkehrt ist.\\
\\

* Footnotes

[fn:1] 1f: Im Unterschied zum Vorausgehenden folgen nun in der
ersten salomonischen Sammlung 375 Sprichwörter, größtenteils Zweizeiler
in dichterischem Parallelismus. Ihr Alter reicht von König Salomo (etwa
930 v. Chr.) bis zum letzten nachexilischen Redaktor (um 200 v. Chr.).
Wahrscheinlich liegen zwei Teilsammlungen vor: [[v1][10,1]] - [[file:Spr_15.org::v33][15,33]] und [[file:Spr_16.org::v1][16,1]] -
[[file:Spr_22.org::v16][22,16]]. - [[v1][10,1b]] lautet genau wie [[file:Spr_15.org::v20][15,20a]], 2b wie 11,4b. Die ältesten
Sprichwörter bestanden wohl nur aus Einzeilern.

[fn:2] 2b: Gerechtigkeit, andere Übersetzungsmöglichkeit:
Mildtätigkeit (vgl. [[file:Sir_3.org::v30][Sir 3,30b]]; [[file:Tob_4.org::v10][Tob 4,10f]]; [[file:Tob_12.org::v9][12,9]]).

[fn:3] Vg schiebt noch ein (= G hinter [[file:Spr_9.org::v12][9,12]]): Wer sich aufs
Lügen stützt, der weidet Wind; er jagt hinter fliegenden Vögeln her.

[fn:4] [[file:Spr_6.org::v13][6,13]]; [[file:Spr_16.org::v30][16,30]]

[fn:5] 10b: So nach G.

[fn:6] [[file:Spr_19.org::v29][19,29]]; [[file:Spr_26.org::v3][26,3]]

[fn:7] [[file:Ps_7.org::v4][Ps 7,4-6]]; [[file:Weish_11.org::v16][Weish 11,16]]

[fn:8] [[file:~/RoamNotes/notes/Bibel/nt/Mt_7.org::v24][Mt 7,24-27]]
