#+TITLE: Spr 12 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-23 Fr 00:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Spr 12.html

* Spr 12

<<verses>>

<<v1>>
1 Wer Zucht liebt, liebt Erkenntnis, /\\
 wer Zurechtweisung hasst, ist dumm.\\
\\

<<v2>>
2 Der Gute findet Gefallen beim Herrn, /\\
 den Heimtückischen aber spricht er schuldig.\\
\\

<<v3>>
3 Wer unrecht tut, hat keinen Bestand, /\\
 doch die Wurzel der Gerechten sitzt fest.\\
\\

<<v4>>
4 Eine tüchtige Frau ist die Krone ihres Mannes, /\\
 eine schändliche ist wie Fäulnis in seinen Knochen. [fn:1]\\
\\

<<v5>>
5 Die Gedanken der Gerechten trachten nach Recht, /\\
 die Pläne der Frevler sind auf Betrug aus.\\
\\

<<v6>>
6 Die Reden der Frevler sind ein Lauern auf Blut, /\\
 die Redlichen rettet ihr Mund.\\
\\

<<v7>>
7 Die Frevler werden gestürzt und sind dahin, /\\
 das Haus der Gerechten hat Bestand.\\
\\

<<v8>>
8 Nach dem Maß seiner Klugheit wird ein jeder gelobt, /\\
 verkehrter Sinn fällt der Verachtung anheim.\\
\\

<<v9>>
9 Besser unbeachtet bleiben /\\
 und seine Arbeit verrichten, /\\
 als großtun und kein Brot haben.\\
\\

<<v10>>
10 Der Gerechte weiß, was sein Vieh braucht, /\\
 doch das Herz der Frevler ist hart. [fn:2]\\
\\

<<v11>>
11 Wer sein Feld bestellt, wird satt von Brot, /\\
 wer nichtigen Dingen nachjagt, ist ohne Verstand. [fn:3]\\
\\

<<v12>>
12 Schwankender Lehm ist die Burg der Bösen, /\\
 die Wurzel der Gerechten hat festen Grund. [fn:4]\\
\\

<<v13>>
13 Der Böse verfängt sich im Lügengespinst, /\\
 der Gerechte entkommt der Bedrängnis.\\
\\

<<v14>>
14 Von der Frucht seines Mundes wird der Mensch reichlich gesättigt, /\\
 nach dem Tun seiner Hände wird ihm vergolten.\\
\\

<<v15>>
15 Der Tor hält sein eigenes Urteil für richtig, /\\
 der Weise aber hört auf Rat.\\
\\

<<v16>>
16 Der Tor zeigt sogleich seinen Ärger, /\\
 klug ist, wer Schimpfworte einsteckt.\\
\\

<<v17>>
17 Wer Wahrheit spricht, sagt aus, was recht ist, /\\
 der falsche Zeuge aber betrügt.\\
\\

<<v18>>
18 Mancher Leute Gerede verletzt wie Schwertstiche, /\\
 die Zunge der Weisen bringt Heilung. [fn:5]\\
\\

<<v19>>
19 Ein Mund, der die Wahrheit sagt, /\\
 hat für immer Bestand, /\\
 eine lügnerische Zunge nur einen Augenblick.\\
\\

<<v20>>
20 Wer auf Böses sinnt, betrügt sich selbst, /\\
 wer heilsamen Rat gibt, erntet Freude.\\
\\

<<v21>>
21 Kein Unheil trifft den Gerechten, /\\
 doch die Frevler erdrückt das Unglück.\\
\\

<<v22>>
22 Lügnerische Lippen sind dem Herrn ein Gräuel, /\\
 doch wer zuverlässig ist in seinem Tun, der gefällt ihm.\\
\\

<<v23>>
23 Ein kluger Mensch verbirgt sein Wissen, /\\
 das Herz der Toren schreit die Narrheit hinaus.\\
\\

<<v24>>
24 Die Hand der Fleißigen erringt die Herrschaft, /\\
 die lässige Hand muss Frondienste leisten.\\
\\

<<v25>>
25 Kummer im Herzen bedrückt den Menschen, /\\
 ein gutes Wort aber heitert ihn auf.\\
\\

<<v26>>
26 Der Gerechte findet fette Weide, /\\
 der Weg der Frevler führt in die Irre. [fn:6]\\
\\

<<v27>>
27 Bequemlichkeit erjagt sich kein Wild, /\\
 kostbare Güter erlangt der Fleißige.\\
\\

<<v28>>
28 Der Pfad der Gerechtigkeit führt zum Leben, /\\
 der Weg der Abtrünnigen führt zum Tod.\\
\\

* Footnotes

[fn:1] [[file:Spr_31.org::v11][31,11f]]

[fn:2] [[file:Dtn_25.org::v4][Dtn 25,4]]; [[file:Sir_7.org::v22][Sir 7,22]]

[fn:3] [[file:Spr_28.org::v19][28,19]]

[fn:4] Text verderbt; die alten Übersetzungen sind kaum
verständlich.

[fn:5] [[file:Ps_57.org::v5][Ps 57,5]]

[fn:6] 26-28: Der Text ist schlecht erhalten und darum schwer
zu deuten.
