#+TITLE: Spr 29 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-10-02 Mi 21:26]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Spr 29.html

* Spr 29

<<verses>>

<<v1>>
1 Wer bei Tadel halsstarrig bleibt, /\\
 wird plötzlich zerschmettert /\\
 und es gibt keine Heilung.\\
\\

<<v2>>
2 Kommen die Gerechten an die Macht, dann freut sich das Volk, /\\
 herrscht der Frevler, dann stöhnt das Volk. [fn:1]\\
\\

<<v3>>
3 Wer Weisheit liebt, erfreut seinen Vater; /\\
 wer mit Dirnen verkehrt, verschleudert das Vermögen.\\
\\

<<v4>>
4 Ein König richtet das Land auf durch Pflege des Rechts, /\\
 wer Abgaben erpresst, zerstört es. [fn:2]\\
\\

<<v5>>
5 Wer seinem Nächsten schmeichelt, /\\
 breitet ihm ein Netz vor die Füße.\\
\\

<<v6>>
6 In Sünde verstrickt sich der Böse, /\\
 doch der Gerechte jubelt und freut sich.\\
\\

<<v7>>
7 Der Gerechte hat Verständnis für den Rechtsstreit der Armen, /\\
 der Frevler aber kennt kein Verständnis. [fn:3]\\
\\

<<v8>>
8 Hetzer bringen eine Stadt in Aufruhr, /\\
 Weise beschwichtigen die Erregung. [fn:4]\\
\\

<<v9>>
9 Rechtet ein Weiser mit einem Toren, /\\
 tobt dieser und lacht und gibt keine Ruhe.\\
\\

<<v10>>
10 Mörder hassen den Schuldlosen, /\\
 Rechtschaffene bemühen sich um sein Leben.\\
\\

<<v11>>
11 Ein Tor lässt seiner ganzen Erregung freien Lauf, /\\
 aber ein Weiser hält sie zurück.\\
\\

<<v12>>
12 Achtet ein Herrscher auf Lügen, /\\
 werden alle seine Beamten zu Schurken.\\
\\

<<v13>>
13 Der Arme und der Ausbeuter begegnen einander, /\\
 der Herr gibt beiden das Augenlicht. [fn:5]\\
\\

<<v14>>
14 Spricht ein König den Geringen zuverlässig Recht, /\\
 hat sein Thron für immer Bestand.\\
\\

<<v15>>
15 Rute und Rüge verleihen Weisheit, /\\
 ein zügelloser Knabe macht seiner Mutter Schande. [fn:6]\\
\\

<<v16>>
16 Herrschen die Frevler, dann herrscht die Sünde, /\\
 doch die Gerechten erleben ihren Sturz.\\
\\

<<v17>>
17 Züchtige deinen Sohn, so wird er dir Verdruss ersparen /\\
 und deinem Herzen Freude machen. [fn:7]\\
\\

<<v18>>
18 Ohne prophetische Offenbarung verwildert das Volk; /\\
 wohl ihm, wenn es die Lehre bewahrt.\\
\\

<<v19>>
19 Durch Worte wird kein Sklave gebessert, /\\
 er versteht sie wohl, aber kehrt sich nicht daran.\\
\\

<<v20>>
20 Siehst du einen, der eilfertig ist im Reden, /\\
 mehr Hoffnung gibt es für den Toren als für ihn. [fn:8]\\
\\

<<v21>>
21 Ein Sklave, verwöhnt von Jugend an, /\\
 wird am Ende widerspenstig.\\
\\

<<v22>>
22 Ein aufbrausender Mensch erregt Streit, /\\
 ein Jähzorniger begeht viele Sünden.\\
\\

<<v23>>
23 Hochmut erniedrigt den Menschen, /\\
 doch der Demütige kommt zu Ehren.\\
\\

<<v24>>
24 Wer mit dem Dieb teilt, hasst sich selbst, /\\
 er hört die Verfluchung, doch er macht keine Anzeige. [fn:9]\\
\\

<<v25>>
25 Die Angst des Menschen führt ihn in die Falle; /\\
 wer auf den Herrn vertraut, ist gesichert.\\
\\

<<v26>>
26 Viele suchen die Gunst des Herrschers, /\\
 aber das Recht kommt für alle vom Herrn.\\
\\

<<v27>>
27 Der Übeltäter ist den Gerechten ein Gräuel. /\\
 Der Rechtschaffene ist für den Frevler ein Gräuel.\\
\\

* Footnotes

[fn:1] [[file:Spr_28.org::v12][28,12]].[[file:Spr_28.org::v28][28]]

[fn:2] [[v14][29,14]]

[fn:3] [[file:Jes_1.org::v17][Jes 1,17f]]

[fn:4] [[file:Sir_28.org::v14][Sir 28,14]]

[fn:5] [[file:Spr_22.org::v2][22,2]]

[fn:6] [[file:Spr_13.org::v24][13,24]]; [[file:Spr_22.org::v15][22,15]]; [[file:Spr_23.org::v13][23,13]]; [[file:Sir_30.org::v1][Sir 30,1]]

[fn:7] 17a: Wörtlich: so wird er dir Ruhe gewähren.

[fn:8] [[file:Spr_26.org::v12][26,12]]

[fn:9] 24b: Vgl. die Anmerkungen zu [[file:Lev_5.org::v1][Lev 5,1]] und [[file:Ri_17.org::v2][Ri 17,2]].
