#+TITLE: Spr 27 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-09-30 Mo 21:36]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Spr 27.html

* Spr 27

<<verses>>

<<v1>>
1 Rühme dich nicht des morgigen Tages, /\\
 denn du weißt nicht, was der Tag gebiert. [fn:1]\\
\\

<<v2>>
2 Rühmen soll dich ein anderer, nicht dein eigener Mund, /\\
 ein Fremder, nicht deine eigenen Lippen.\\
\\

<<v3>>
3 Schwer ist der Stein und eine Last ist der Sand, /\\
 doch der Ärger mit einem Toren ist schwerer als beide. [fn:2]\\
\\

<<v4>>
4 Mag der Zorn grausam sein /\\
 und überschäumend die Wut, /\\
 wer aber besteht vor der Eifersucht?\\
\\

<<v5>>
5 Besser offener Tadel /\\
 als Liebe, die sich nicht zeigt.\\
\\

<<v6>>
6 Treu gemeint sind die Schläge eines Freundes, /\\
 doch trügerisch die Küsse eines Feindes. [fn:3]\\
\\

<<v7>>
7 Der Satte tritt Honig mit Füßen, /\\
 doch dem Hungrigen schmeckt alles Bittere süß.\\
\\

<<v8>>
8 Wie ein Vogel, der aus seinem Nest flüchtet, /\\
 so ist ein Mensch, der aus seiner Heimat fliehen muss.\\
\\

<<v9>>
9 Salböl und Weihrauch erfreuen das Herz, /\\
 die Herzlichkeit eines Freundes erfreut mehr als duftendes Holz. [fn:4]\\
\\

<<v10>>
10 Deinen Freund und deines Vaters Freund gib nicht auf, /\\
 geh nicht in das Haus deines Bruders, wenn du in Not bist. Besser ein
Nachbar in der Nähe /\\
 als ein Bruder in der Ferne.\\
\\

<<v11>>
11 Sei weise, mein Sohn, und erfreue mein Herz, /\\
 damit ich dem antworten kann, der mich beschimpft. [fn:5]\\
\\

<<v12>>
12 Der Kluge sieht das Unheil und verbirgt sich, /\\
 die Unerfahrenen laufen weiter und müssen es büßen. [fn:6]\\
\\

<<v13>>
13 Nimm ihm das Kleid; /\\
 denn er hat für einen andern gebürgt, /\\
 fremder Leute wegen pfände bei ihm! [fn:7]\\
\\

<<v14>>
14 Wer seinen Nächsten zu laut begrüßt, /\\
 dem wird es frühmorgens als Verwünschung ausgelegt.\\
\\

<<v15>>
15 Ein ständig tropfendes Dach in der Regenzeit /\\
 und eine zänkische Frau gleichen einander. [fn:8]\\
\\

<<v16>>
16 Wer sie fest hält, hält den Wind fest /\\
 und seine Hand greift nach Öl.\\
\\

<<v17>>
17 Eisen wird an Eisen geschliffen; /\\
 so schleift einer den Charakter des andern.\\
\\

<<v18>>
18 Wer einen Feigenbaum pflegt, wird seine Frucht essen, /\\
 wer auf seinen Herrn Acht gibt, wird geehrt.\\
\\

<<v19>>
19 Wie Wasser ein Spiegel ist für das Gesicht, /\\
 so ist das Herz des Menschen ein Spiegel für den Menschen.\\
\\

<<v20>>
20 Unterwelt und Totenreich sind unersättlich /\\
 und unersättlich sind die Augen des Menschen. [fn:9]\\
\\

<<v21>>
21 Der Schmelztiegel prüft das Silber, der Ofen das Gold, /\\
 der Mensch aber wird geprüft im Urteil dessen, der ihn lobt.\\
\\

<<v22>>
22 Zerstampfst du den Toren auch mit dem Stößel, /\\
 [im Mörser zwischen den Körnern,] /\\
 seine Torheit weicht nicht von ihm.\\
\\

<<v23>>
23 Kümmere dich um das Aussehen deiner Schafe /\\
 und sorge für deine Herden;\\
\\

<<v24>>
24 denn Besitz bleibt nicht für ewig /\\
 und Reichtum nicht für alle Zeit.\\
\\

<<v25>>
25 Kommt das Gras hervor, erscheint das Grün, /\\
 sammelt man die Kräuter auf den Bergen,\\
\\

<<v26>>
26 dann gibt es Lämmer für deine Kleidung, /\\
 Böcke als Kaufpreis für Äcker\\
\\

<<v27>>
27 und genug Ziegenmilch für dich als Nahrung, /\\
 als Nahrung für dein Haus /\\
 [und Lebensunterhalt für deine Mägde].\\
\\

* Footnotes

[fn:1] [[file:~/Documents/notes/Bibel/nt/Lk_12.org::v19][Lk 12,19f]]

[fn:2] [[file:Sir_22.org::v15][Sir 22,15]]

[fn:3] 6b: trügerisch, andere Übersetzungsmöglichkeit: reichlich.

[fn:4] 9c: Andere Übersetzungsmöglichkeit: mehr als eigenes Planen

[fn:5] [[file:Ps_119.org::v42][Ps 119,42]]

[fn:6] [[file:Spr_22.org::v3][22,3]]

[fn:7] [[file:Spr_20.org::v16][20,16]]

[fn:8] [[file:Spr_19.org::v13][19,13]]

[fn:9] [[file:Spr_30.org::v15][30,15f]]; [[file:Jes_5.org::v14][Jes 5,14]]
