#+TITLE: Spr 19 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-08-31 Sa 22:49]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Spr 19.html

* Spr 19

<<verses>>

<<v1>>
1 Besser ein Armer, der schuldlos seinen Weg geht, als einer mit
verlogenen Lippen, der ein Tor ist. [fn:1]\\
\\

<<v2>>
2 Schon unvernünftige Begierde ist nicht gut, /\\
 und wer hastig rennt, tritt fehl.\\
\\

<<v3>>
3 Die Torheit verdirbt dem Menschen den Weg /\\
 und dann grollt sein Herz gegen den Herrn. [fn:2]\\
\\

<<v4>>
4 Besitz vermehrt die Zahl der Freunde, /\\
 der Arme aber wird von seinem Freund verlassen. [fn:3]\\
\\

<<v5>>
5 Ein falscher Zeuge bleibt nicht ungestraft, /\\
 wer Lügen flüstert, wird nicht entrinnen. [fn:4]\\
\\

<<v6>>
6 Viele umschmeicheln den Vornehmen /\\
 und jeder will der Freund eines freigebigen Mannes sein.\\
\\

<<v7>>
7 Vom Armen wollen alle seine Brüder nichts wissen, /\\
 erst recht bleiben ihm seine Freunde fern. /\\
 [Gute Einsicht ist denen nahe, die sich um sie kümmern, /\\
 ein verständiger Mann findet sie. /\\
 Wer viel redet, versündigt sich.] /\\
 Wer Worten nachjagt, wird nicht entrinnen. [fn:5]\\
\\

<<v8>>
8 Wer Verstand erwirbt, liebt sich selbst, /\\
 wer Einsicht bewahrt, findet sein Glück.\\
\\

<<v9>>
9 Ein falscher Zeuge bleibt nicht ungestraft, /\\
 wer Lügen flüstert, geht zugrunde.\\
\\

<<v10>>
10 Wohlleben steht dem Toren nicht an, /\\
 noch weniger einem Knecht, über Fürsten zu herrschen.\\
\\

<<v11>>
11 Einsicht macht den Menschen langmütig, /\\
 sein Ruhm ist es, über Verfehlungen hinwegzugehen.\\
\\

<<v12>>
12 Wie das Knurren des Löwen ist der Zorn des Königs, /\\
 doch wie Tau auf dem Gras ist seine Gunst. [fn:6]\\
\\

<<v13>>
13 Ein Unglück für den Vater ist ein törichter Sohn /\\
 und wie ein ständig tropfendes Dach das Gezänk einer Frau. [fn:7]\\
\\

<<v14>>
14 Haus und Habe sind das Erbe der Väter, /\\
 doch eine verständige Frau kommt vom Herrn.\\
\\

<<v15>>
15 Faulheit versenkt in Schlaf, /\\
 ein träger Mensch muss hungern. [fn:8]\\
\\

<<v16>>
16 Wer (Gottes) Gebot bewahrt, bewahrt sein Leben, /\\
 wer seine Wege verachtet, muss sterben. [fn:9]\\
\\

<<v17>>
17 Wer Erbarmen hat mit dem Elenden, leiht dem Herrn; /\\
 er wird ihm seine Wohltat vergelten.\\
\\

<<v18>>
18 Züchtige deinen Sohn, solange noch Hoffnung ist, /\\
 doch lass dich nicht hinreißen, ihn zu töten. [fn:10]\\
\\

<<v19>>
19 Der maßlos Jähzornige muss büßen; /\\
 denn willst du schlichten, machst du es noch ärger. [fn:11]\\
\\

<<v20>>
20 Hör auf guten Rat und nimm Zucht an, /\\
 damit du weise wirst für die Zukunft.\\
\\

<<v21>>
21 Viele Pläne fasst das Herz des Menschen, /\\
 doch nur der Ratschluss des Herrn hat Bestand.\\
\\

<<v22>>
22 Die Menschen streben nach Gewinn, /\\
 doch besser ein Armer als ein Betrüger. [fn:12]\\
\\

<<v23>>
23 Die Gottesfurcht führt zum Leben; /\\
 gesättigt geht man zur Ruhe, /\\
 von keinem Übel heimgesucht.\\
\\

<<v24>>
24 Greift der Faule mit der Hand in die Schüssel, /\\
 bringt er sie nicht einmal zum Mund zurück. [fn:13]\\
\\

<<v25>>
25 Schlägst du den Zuchtlosen, so wird der Unerfahrene klug; /\\
 weist man den Verständigen zurecht, gewinnt er Einsicht. [fn:14]\\
\\

<<v26>>
26 Wer den Vater misshandelt, die Mutter wegjagt, /\\
 ist ein verkommener, schändlicher Sohn.\\
\\

<<v27>>
27 Gibst du es auf, mein Sohn, auf Mahnung zu hören, /\\
 so entziehst du dich den Worten der Einsicht.\\
\\

<<v28>>
28 Ein nichtsnutziger Zeuge verspottet das Recht, /\\
 der Mund der Frevler sprudelt Unheil hervor. [fn:15]\\
\\

<<v29>>
29 Für die Zuchtlosen stehen Ruten bereit /\\
 und Schläge für den Rücken der Toren. [fn:16] [fn:17]\\
\\

* Footnotes

[fn:1] [[file:Spr_28.org::v6][28,6]]

[fn:2] [[file:Sir_15.org::v11][Sir 15,11-20]]

[fn:3] [[file:Spr_14.org::v20][14,20]]; [[file:Sir_13.org::v21][Sir 13,21]]

[fn:4] [[file:Spr_21.org::v28][21,28]]

[fn:5] Das Eingeklammerte fehlt in H, steht aber in G und
gehört vielleicht zum ursprünglichen Textbestand.

[fn:6] [[file:Spr_16.org::v14][16,14]]

[fn:7] [[file:Spr_27.org::v15][27,15]]

[fn:8] 15a: Text umstritten.

[fn:9] 16b: Vielleicht zu korrigieren: wer seine Worte
verachtet.

[fn:10] 18b: Andere Übersetzungsmöglichkeit: und achte nicht
auf sein Jammern; oder: doch lass dich nicht hinreißen zum Jähzorn!

[fn:11] 19b: Übersetzung unsicher.

[fn:12] 22a: Text korr.

[fn:13] [[file:Spr_26.org::v15][26,15]]

[fn:14] [[file:Spr_21.org::v11][21,11]]

[fn:15] [[file:Spr_15.org::v28][15,28]]

[fn:16] [[file:Spr_10.org::v13][10,13]]

[fn:17] 29a: Ruten: nach G; H: Strafgerichte.
