#+TITLE: Spr 25 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-09-30 Mo 10:09]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Spr 25.html

* Spr 25

<<verses>>

<<v1>>
* Die zweite salomonische Spruchsammlung: 25,1 - 29,27

1 Auch das sind Sprichwörter Salomos, die die Männer Hiskijas, des
Königs von Juda, sammelten. [fn:1]\\
\\

<<v2>>
2 Gottes Ehre ist es, eine Sache zu verhüllen, /\\
 des Königs Ehre ist es, eine Sache zu erforschen. [fn:2]\\
\\

<<v3>>
3 Der Himmel so hoch und die Erde so tief /\\
 und das Herz des Königs: sie sind nicht zu erforschen.\\
\\

<<v4>>
4 Scheidet man die Schlacken vom Silber, /\\
 gelingt dem Feinschmied das Gefäß.\\
\\

<<v5>>
5 Scheidet man den Frevler vom König, /\\
 erlangt dessen Thron Bestand durch Gerechtigkeit. [fn:3]\\
\\

<<v6>>
6 Rühme dich nicht vor dem König /\\
 und stell dich nicht an den Platz der Großen; [fn:4]\\
\\

<<v7>>
7 denn besser, man sagt zu dir: Rück hier herauf, /\\
 als dass man dich nach unten setzt wegen eines Vornehmen. Was deine
Augen sahen, / [fn:5]\\
\\

<<v8>>
8 bring es nicht übereilt als Streitfall vor; denn was willst du später
tun, /\\
 wenn dein Nächster dich bloßstellt?\\
\\

<<v9>>
9 Trag deinen Streit mit deinem Nächsten aus, /\\
 doch verrate nicht das Geheimnis eines andern,\\
\\

<<v10>>
10 sonst wird dich schmähen, wer es hört, /\\
 und dein Geschwätz wird auf dich zurückfallen. [fn:6]\\
\\

<<v11>>
11 Wie goldene Äpfel auf silbernen Schalen /\\
 ist ein Wort, gesprochen zur rechten Zeit. [fn:7]\\
\\

<<v12>>
12 Wie ein goldener Ring und Schmuck aus Feingold /\\
 ist ein weiser Mahner für ein Ohr, das zuhört.\\
\\

<<v13>>
13 Wie kühlender Schnee an einem Sommertag /\\
 ist ein verlässlicher Bote für den, der ihn sendet; /\\
 er erquickt die Seele seines Herrn.\\
\\

<<v14>>
14 Aufziehende Wolken mit Wind, doch kein Regen, /\\
 so ist ein Mann, der Versprechungen macht und nicht hält. [fn:8]\\
\\

<<v15>>
15 Mit Geduld wird ein Vorgesetzter umgestimmt, /\\
 sanfte Zunge bricht Knochen.\\
\\

<<v16>>
16 Findest du Honig, iss nur, so viel dir bekommt, /\\
 sonst wirst du ihn satt und erbrichst ihn.\\
\\

<<v17>>
17 Mach dich rar im Haus deines Nächsten, /\\
 sonst wird er dich satt und verabscheut dich.\\
\\

<<v18>>
18 Keule und Schwert und scharfer Pfeil: /\\
 das ist einer, der falsch aussagt /\\
 gegen seinen Nächsten.\\
\\

<<v19>>
19 Schlechter Zahn und stolpernder Fuß: /\\
 der Verräter am Tag der Not.\\
\\

<<v20>>
20 Essig auf Laugensalz - /\\
 (so ist,) wer Lieder singt vor einem missmutigen Herzen. [Wie die Motte
am Kleid, der Wurm im Holz, /\\
 so nagt der Kummer am Herzen des Menschen.] [fn:9]\\
\\

<<v21>>
21 Hat dein Feind Hunger, gib ihm zu essen, /\\
 hat er Durst, gib ihm zu trinken; [fn:10]\\
\\

<<v22>>
22 so sammelst du glühende Kohlen auf sein Haupt /\\
 und der Herr wird es dir vergelten.\\
\\

<<v23>>
23 Der Nordwind bringt Regen, /\\
 eine heimtückische Zunge zornige Gesichter.\\
\\

<<v24>>
24 Besser in einer Ecke des Daches wohnen /\\
 als eine zänkische Frau im gemeinsamen Haus. [fn:11]\\
\\

<<v25>>
25 Kühles Wasser für eine durstige Kehle /\\
 ist eine gute Nachricht aus fernem Land.\\
\\

<<v26>>
26 Ein getrübter Brunnen, ein verschütteter Quell /\\
 ist ein Gerechter, der vor dem Frevler wankt.\\
\\

<<v27>>
27 Zu viel Honig essen ist nicht gut: /\\
 Ebenso spare mit ehrenden Worten! [fn:12]\\
\\

<<v28>>
28 Eine Stadt mit eingerissener Mauer /\\
 ist ein Mann, der sich nicht beherrscht.\\
\\

* Footnotes

[fn:1] [[v1][25,1]] - [[file:Spr_29.org::v27][29,27]]: Die zweite salomonische Hauptsammlung
umfasst nur die Kapitel 25 - 29. Auch sie ist in zwei Hälften zu teilen:
Kap. 25 27 und Kap. 28f. - Hiskija (728-699 v. Chr.) war einer der
tüchtigsten Könige Judas, sodass die Mitteilung, unter ihm habe eine
Gruppe von Gelehrten die Weisheitssprüche zusammengestellt, durchaus
glaubwürdig ist.

[fn:2] [[file:Spr_16.org::v10][16,10]]

[fn:3] [[file:Spr_16.org::v12][16,12]]

[fn:4] [[file:Sir_13.org::v9][Sir 13,9f]]

[fn:5] Lk 14,7-11

[fn:6] 10b: Übersetzung unsicher.

[fn:7] [[file:Spr_15.org::v23][15,23]]

[fn:8] 14b: Wörtlich: Ein Mann, der mit erlogener Gabe prahlt.

[fn:9] 20a: H schickt voraus: Ein das Kleid Ablegender am
kalten Tag. Hier sind Buchstaben aus V. 19b wiederholt und missdeutet
worden. 20c: Fehlt in H, steht aber in allen alten Übersetzungen und ist
daher wohl ursprünglich.

[fn:10] [[file:~/Documents/notes/Bibel/nt/Röm_12.org::v20][Röm 12,20]]

[fn:11] [[file:Spr_21.org::v9][21,9]]

[fn:12] 27b: Nach G; H ist verderbt.
