#+TITLE: Spr 22 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2024-09-03 Di 00:45]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Spr 22.html

* Spr 22

<<verses>>

<<v1>>
1 Guter Ruf ist kostbarer als großer Reichtum, /\\
 hohes Ansehen besser als Silber und Gold.\\
\\

<<v2>>
2 Reiche und Arme begegnen einander, /\\
 doch der Herr hat sie alle erschaffen. [fn:1] [fn:2]\\
\\

<<v3>>
3 Der Kluge sieht das Unheil und verbirgt sich, /\\
 die Unerfahrenen laufen weiter und müssen es büßen. [fn:3]\\
\\

<<v4>>
4 Der Lohn für Demut und Gottesfurcht /\\
 ist Reichtum, Ehre und Leben.\\
\\

<<v5>>
5 Dornen und Schlingen liegen auf dem Weg des Falschen; /\\
 wer sein Leben behütet, bleibt ihnen fern.\\
\\

<<v6>>
6 Erzieh den Knaben für seinen Lebensweg, /\\
 dann weicht er auch im Alter nicht davon ab.\\
\\

<<v7>>
7 Der Reiche hat die Armen in seiner Gewalt, /\\
 der Schuldner ist seines Gläubigers Knecht.\\
\\

<<v8>>
8 Wer Unrecht sät, erntet Unheil, /\\
 der Stecken seines Übermuts versagt.\\
\\

<<v9>>
9 Wer ein gütiges Auge hat, wird gesegnet, /\\
 weil er den Armen von seinem Brot gibt.\\
\\

<<v10>>
10 Vertreib den Zuchtlosen, so schwindet der Zank, /\\
 Streiten und Schimpfen hören auf.\\
\\

<<v11>>
11 Wer die Lauterkeit des Herzens liebt - /\\
 wegen seiner gefälligen Rede wird der König sein Freund. [fn:4]\\
\\

<<v12>>
12 Die Augen des Herrn behüten den Einsichtigen, /\\
 das Gerede des Verräters bringt er zu Fall. [fn:5]\\
\\

<<v13>>
13 Der Faule sagt: Ein Löwe ist draußen, /\\
 mitten auf der Straße käme ich ums Leben. [fn:6]\\
\\

<<v14>>
14 Der Mund fremder Frauen ist eine tiefe Grube; /\\
 wem der Herr zürnt, der fällt hinein.\\
\\

<<v15>>
15 Steckt Torheit im Herzen des Knaben, /\\
 die Rute der Zucht vertreibt sie daraus.\\
\\

<<v16>>
16 Wer den Armen bedrückt, macht ihn reich, /\\
 wer dem Reichen gibt, macht ihn arm.\\
\\

<<v17>>
* Die Worte von Weisen: 22,17 - 24,33

* Eine Sprichwörtersammlung: 22,17 - 23,11

17 Worte von Weisen: Neige mir dein Ohr zu und hör auf meine Worte, /\\
 nimm dir meine Lehren zu Herzen! [fn:7]\\
\\

<<v18>>
18 Schön ist es, wenn du sie in deinem Innern bewahrst; /\\
 sie mögen fest wie ein Zeltpflock auf deinen Lippen haften.\\
\\

<<v19>>
19 Damit dein Vertrauen auf dem Herrn steht, /\\
 lehre ich dich heute seinen Weg.\\
\\

<<v20>>
20 Habe ich nicht dreißig Sätze für dich aufgeschrieben /\\
 als wissenswerte Ratschläge,\\
\\

<<v21>>
21 um dir verlässliche Worte mitzuteilen, /\\
 damit du deinem Auftraggeber antworten kannst?\\
\\

<<v22>>
22 Beraube den Schwachen nicht, denn er ist ja so schwach, /\\
 zertritt den Armen nicht am Tor! [fn:8]\\
\\

<<v23>>
23 Denn der Herr führt den Rechtsstreit für sie /\\
 und raubt denen das Leben, die sie berauben. [fn:9]\\
\\

<<v24>>
24 Befreunde dich nicht mit dem Jähzornigen, /\\
 verkehre nicht mit einem Hitzkopf,\\
\\

<<v25>>
25 damit du dich nicht an seine Pfade gewöhnst /\\
 und dir eine Schlinge legst für dein Leben.\\
\\

<<v26>>
26 Sei nicht unter denen, die sich durch Handschlag verpflichten, /\\
 die Bürgschaft leisten für Schulden; [fn:10]\\
\\

<<v27>>
27 wenn du nicht zahlen kannst, /\\
 nimmt man dein Bett unter dir weg.\\
\\

<<v28>>
28 Verschieb nicht die alte Grenze, /\\
 die deine Väter gesetzt haben. [fn:11]\\
\\

<<v29>>
29 Siehst du einen, der gewandt ist in seinem Beruf: /\\
 vor Königen wird er dienen. /\\
 [Nicht wird er vor Niedrigen dienen.]\\
\\

* Footnotes

[fn:1] [[file:Spr_29.org::v13][29,13]]

[fn:2] Soziale Unterschiede gibt es immer. Da aber vor dem
Schöpfer alle Menschen gleich sind, sollen die Gegensätze möglichst
gemildert werden.

[fn:3] [[file:Spr_27.org::v12][27,12]]

[fn:4] Übersetzung unsicher; G hat Änderungen und Einschübe.

[fn:5] 12a: Wörtlich: behüten Einsicht.

[fn:6] [[file:Spr_26.org::v13][26,13]]

[fn:7] Eine leichte Textkorrektur nach G stellt die Überschrift
dieses ersten Anhangs an die erste salomonische Hauptsammlung wieder
her. Eine erste Sammlung von «Worten von Weisen» reicht bis zur nächsten
Überschrift in [[file:Spr_24.org::v33][24,23]]. Sie enthält drei kurze Teilsammlungen, von denen
die erste ([[v17][22,17]] - [[file:Spr_23.org::v11][23,11]]) besondere Beachtung verdient, weil sie
abhängig ist vom ägyptischen Weisheitsbuch des Amen-em-ope (etwa 10. Jh.
v. Chr.). Das ägyptische Spruchgut wurde in Auswahl und unter
Angleichung an den Glauben Israels übernommen. Angehängt ist eine
weitere Sammlung von «Sprichwörtern von Weisen» ([[file:Spr_24.org::v23][24,23-34]]).

[fn:8] 22b: Am Stadttor finden die Rats- und Gerichtsverhandlungen statt.

[fn:9] [[file:Jes_1.org::v17][Jes 1,17f]]

[fn:10] [[file:Spr_6.org::v1][6,1-5]]; [[file:Spr_20.org::v16][20,16]]

[fn:11] [[file:Spr_23.org::v10][23,10]]
