#+TITLE: Tob 11 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 20:50]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Tob 11.html

<<verses>>

<<v1>>
* Tobits Heilung: 11,1-15

1 Als sie auf ihrer Heimreise in die Nähe von Ninive kamen, sagte Rafael
zu Tobias:

<<v2>>
2 Weißt du noch, Bruder, wie es deinem Vater ging, als du ihn verlassen
hast?

<<v3>>
3 Wir wollen deshalb deiner Frau vorausgehen und das Haus für ihren
Empfang vorbereiten.

<<v4>>
4 Nimm auch die Galle des Fisches mit! Sie machten sich auf den Weg und
der Hund lief hinter ihnen her.

<<v5>>
5 Hanna saß am Weg und hielt nach ihrem Sohn Ausschau.

<<v6>>
6 Als sie ihn kommen sah, rief sie seinem Vater zu: Dein Sohn kommt
zurück und mit ihm der Mann, der ihn begleitet hat.

<<v7>>
7 Rafael aber sagte zu Tobias: Ich weiß, dein Vater wird wieder sehen
können.

<<v8>>
8 Streich ihm die Galle auf die Augen! Sie wird zwar brennen; aber wenn
er sich die Augen reibt, wird er die weißen Flecken wegwischen und wird
dich wieder sehen können.

<<v9>>
9 Hanna war inzwischen herbeigeeilt, fiel ihrem Sohn um den Hals und
rief: Ich habe dich wieder gesehen, mein Sohn, jetzt kann ich ruhig
sterben. Und beide brachen in Tränen aus. [fn:1]

<<v10>>
10 Auch Tobit versuchte, ihm entgegenzugehen, stolperte aber an der Tür.
Da lief ihm sein Sohn entgegen

<<v11>>
11 und fing ihn auf. Und er strich seinem Vater die Galle auf die Augen
und sagte: Hab keine Angst, mein Vater!

<<v12>>
12 Tobit rieb sich die Augen, weil sie brannten; da begannen die weißen
Flecken, sich von den Augenwinkeln aus abzulösen.

<<v13>>
13 Und er konnte seinen Sohn sehen, fiel ihm um den Hals und sagte unter
Tränen:

<<v14>>
14 Sei gepriesen, Gott, gepriesen sei dein heiliger Name in Ewigkeit.
Gepriesen seien alle deine heiligen Engel. Du hast mich gezüchtigt und
hast wieder Erbarmen mit mir gehabt. Denn ich darf meinen Sohn Tobias
wieder sehen.

<<v15>>
15 Voll Freude ging der Sohn mit seinem Vater ins Haus und erzählte ihm,
was für wunderbare Dinge er in Medien erlebt hatte.\\
\\

<<v16>>
* Saras Ankunft: 11,16-19

16 Dann ging Tobit seiner Schwiegertochter bis an das Tor von Ninive
entgegen. Er war voll Freude und pries Gott und alle, die ihn sahen,
staunten, dass er wieder sehen konnte. Tobit aber bezeugte ihnen, dass
Gott Erbarmen mit ihm gehabt hatte.

<<v17>>
17 Als Tobit seiner Schwiegertochter begegnete, segnete er sie und
sagte: Sei willkommen, meine Tochter! Gepriesen sei Gott, der dich zu
uns geführt hat, und gesegnet seien dein Vater und deine Mutter.

<<v18>>
18 Bei allen Brüdern aus seinem Stamm in Ninive herrschte große Freude.

<<v19>>
19 Auch Achikar und sein Neffe Nadab kamen und sieben Tage lang wurde
die Hochzeit des Tobias mit einem fröhlichen Fest gefeiert.\\
\\

* Footnotes

[fn:1] [[file:Gen_46.org::v29][Gen 46,29f]]
