#+TITLE: Tob 6 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 10:21]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Tob 6.html

<<verses>>

<<v1>>
* Wunderbare Heilmittel: 6,1-9

1 Die beiden kamen auf ihrer Reise abends an den Tigris, wo sie
übernachteten.

<<v2>>
2 Als der junge Tobias im Fluss baden wollte, schoss ein Fisch aus dem
Wasser hoch und wollte ihn verschlingen.

<<v3>>
3 Der Engel rief Tobias zu: Pack ihn! Da packte der junge Mann zu und
warf den Fisch ans Ufer.

<<v4>>
4 Und der Engel sagte zu Tobias: Schneide den Fisch auf, nimm Herz,
Leber und Galle heraus und bewahre sie gut auf!

<<v5>>
5 Der junge Tobias tat, was ihm der Engel sagte. Dann brieten sie den
Fisch und aßen ihn.

<<v6>>
6 Als sie weiterreisten und in die Gegend von Ekbatana kamen,

<<v7>>
7 fragte der junge Tobias den Engel: Asarja, lieber Bruder, wozu sollen
die Leber, das Herz und die Galle des Fisches gut sein?

<<v8>>
8 Rafael antwortete: Wenn ein Mann oder eine Frau von einem Dämon oder
einem bösen Geist gequält wird, soll man das Herz und die Leber des
Fisches in Gegenwart dieses Menschen verbrennen; dann wird er von der
Plage befreit.

<<v9>>
9 Und wenn jemand weiße Flecken in den Augen hat, soll man die Augen mit
der Galle bestreichen; so wird er geheilt.\\
\\

<<v10>>
* Der Heiratsplan: 6,10-19

10 Als sie in der Nähe der Stadt Ekbatana waren,

<<v11>>
11 sagte der Engel zu dem jungen Tobias: Bruder, heute werden wir bei
Raguël übernachten. Es ist ein Verwandter von dir. Er hat nur ein
einziges Kind, eine Tochter namens Sara.

<<v12>>
12 Ich will mit ihm reden, dass er sie dir zur Frau geben soll. Denn dir
steht ihr Erbe zu, weil du ihr einziger Verwandter bist. Das Mädchen ist
schön und klug.

<<v13>>
13 Darum hör mir zu! Ich will mit ihrem Vater sprechen, und wenn wir aus
Rages zurückkommen, feiern wir die Hochzeit. Denn ich weiß, dass Raguël
sie nach dem Gesetz des Mose keinem anderen Mann geben darf, sonst wird
er mit dem Tod bestraft; denn du hast vor allen anderen Anspruch auf ihr
Erbe.

<<v14>>
14 Der junge Tobias antwortete: Asarja, Bruder, ich habe gehört, dass
das Mädchen schon mit sieben Männern verheiratet war, dass aber alle im
Brautgemach gestorben sind.

<<v15>>
15 Ich bin der einzige Sohn meines Vaters und habe Angst, dass ich
ebenso sterben muss wie die anderen Männer, wenn ich das Brautgemach
betrete. Ein Dämon liebt sie und bringt alle um, die ihr nahekommen.
Darum habe ich Angst, dass ich sterben muss und dass ich dann meinen
Vater und meine Mutter aus Kummer um mich ins Grab bringe. Sie haben
keinen zweiten Sohn, der sie dann begraben könnte. [fn:1]

<<v16>>
16 Da sagte der Engel zu ihm: Erinnerst du dich nicht mehr, wie dein
Vater dir aufgetragen hat, nur eine Frau aus deinem Volk zu heiraten?
Darum hör jetzt auf mich, Bruder! Sie wird deine Frau werden. Und mach
dir keine Sorgen wegen des Dämons! Noch in dieser Nacht wird sie deine
Frau.

<<v17>>
17 Wenn du in das Brautgemach gehst, nimm etwas Glut aus dem
Räucherbecken, leg ein Stück vom Herz und von der Leber des Fisches
darauf und lass es verbrennen! Sobald der Dämon den Geruch spürt, wird
er fliehen und in alle Ewigkeit nicht mehr zurückkommen.

<<v18>>
18 Wenn du dann zu ihr gehst, steht beide auf und ruft den barmherzigen
Gott an; er wird euch helfen und Erbarmen mit euch haben. Hab also keine
Angst; das Mädchen ist schon immer für dich bestimmt gewesen. Du wirst
sie aus ihrer Not befreien; sie wird mit dir ziehen und wird dir gewiss
Kinder schenken.

<<v19>>
19 Als Tobias das hörte, fasste er Zuneigung zu dem Mädchen und sein
Herz gehörte ihr.\\
\\

* Footnotes

[fn:1] [[file:Gen_44.org::v29][Gen 44,29]].[[file:Gen_44.org::v31][31]]
