#+TITLE: Tob 13 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 20:53]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/Documents/exports/Tob 13.html

<<verses>>

<<v1>>
* Der Lobpreis des Rettergottes und letzte Mahnungen: 13,1 - 14,15

* Tobits Lobgesang: 13,1-18

1 Und Tobit schrieb zum Lobpreis Gottes ein Gebet nieder:\\
\\

<<v2>>
2 Gepriesen sei Gott, der in Ewigkeit lebt, /\\
 sein Königtum sei gepriesen. /\\
 Er züchtigt und hat auch wieder Erbarmen; /\\
 er führt hinab in die Unterwelt /\\
 und führt auch wieder zum Leben. /\\
 Niemand kann seiner Macht entfliehen. [fn:1]\\
\\

<<v3>>
3 Bekennt euch zu ihm vor allen Völkern, /\\
 ihr Kinder Israels; /\\
 denn er selbst hat uns unter die Völker zerstreut.\\
\\

<<v4>>
4 Verkündet dort seine erhabene Größe, /\\
 preist ihn laut vor allem, was lebt. /\\
 Denn er ist unser Herr und Gott, /\\
 er ist unser Vater in alle Ewigkeit.\\
\\

<<v5>>
5 Er züchtigt uns wegen unserer Sünden, /\\
 doch hat er auch wieder Erbarmen. /\\
 Er führt uns aus allen Völkern zusammen, /\\
 von überall her, wohin ihr verschleppt worden seid.\\
\\

<<v6>>
6 Wenn ihr zu ihm umkehrt, /\\
 von ganzem Herzen und aus ganzer Seele, /\\
 und euch an seine Wahrheit haltet, /\\
 dann kehrt er sich euch zu /\\
 und verbirgt sein Angesicht nicht mehr vor euch. [fn:2]\\
\\

<<v7>>
7 Wenn ihr dann seht, was er für euch tut, /\\
 bekennt euch laut und offen zu ihm! /\\
 Preist den Herrn der Gerechtigkeit, /\\
 rühmt den ewigen König!\\
\\

<<v8>>
8 Ich bekenne mich zum Herrn /\\
 im Land der Verbannung, /\\
 ich bezeuge den Sündern seine Macht /\\
 und erhabene Größe. /\\
 Kehrt um, ihr Sünder, /\\
 tut, was recht ist in seinen Augen. /\\
 Vielleicht ist er gnädig und hat mit euch Erbarmen. [fn:3]\\
\\

<<v9>>
9 Ich will meinen Gott rühmen, /\\
 den König des Himmels, /\\
 meine Seele freut sich /\\
 über die erhabene Größe meines Gottes.\\
\\

<<v10>>
10 Alle, die in Jerusalem wohnen, /\\
 sollen sich zu ihm bekennen und sagen: /\\
 Jerusalem, du heilige Stadt! /\\
 Der Herr bestraft die Taten deiner Kinder, /\\
 doch er hat wieder Erbarmen /\\
 mit den Söhnen der Gerechten.\\
\\

<<v11>>
11 Bekenne dich zum Herrn in rechter Weise, /\\
 preise den ewigen König, /\\
 damit sein Zelt von neuem errichtet wird, /\\
 dir zur großen Freude.\\
\\

<<v12>>
12 Er mache in dir die Gefangenen wieder froh /\\
 und schenke denen, die im Elend leben, seine Liebe, /\\
 für alle Zeiten bis in Ewigkeit.\\
\\

<<v13>>
13 Von weither werden die Völker kommen, /\\
 um den Namen des Herrn, unseres Gottes, zu preisen. /\\
 Sie tragen Geschenke herbei, /\\
 Geschenke für den himmlischen König. /\\
 Alle Menschen jubeln dir zu. [fn:4]\\
\\

<<v14>>
14 Verflucht sind alle, die dich hassen, /\\
 auf ewig gesegnet alle, die dich lieben. [fn:5]\\
\\

<<v15>>
15 Freu dich und juble /\\
 über alle Gerechten! /\\
 Sie werden vereint sein /\\
 und den Herrn der Gerechten preisen. /\\
 Wohl denen, die dich lieben; /\\
 sie werden sich freuen /\\
 über den Frieden, den du schenkst.\\
\\

<<v16>>
16 Wohl denen, die betrübt waren /\\
 über deine harten Strafen; /\\
 denn sie werden sich über dich freuen, /\\
 wenn sie all deine Herrlichkeit sehen. /\\
 Sie werden sich freuen in Ewigkeit. /\\
 Meine Seele preise Gott, den großen König.\\
\\

<<v17>>
17 Denn Jerusalem wird wieder aufgebaut /\\
 aus Saphir und Smaragd; /\\
 seine Mauern macht man aus Edelstein, /\\
 seine Türme und Wälle aus reinem Gold; /\\
 Jerusalems Plätze werden ausgelegt /\\
 mit Beryll und Rubinen und mit Steinen aus Ofir. [fn:6]\\
\\

<<v18>>
18 Halleluja ruft man in all seinen Gassen /\\
 und stimmt in den Lobpreis ein: /\\
 Gepriesen sei Gott; /\\
 er hat uns groß gemacht für alle Zeiten.\\
\\

* Footnotes

[fn:1] [[file:Dtn_32.org::39][Dtn 32,39]]; [[file:1.Sam_2.org::v6][1 Sam 2,6]]; [[file:Hos_6.org::v1][Hos 6,1]]

[fn:2] [[file:Sach_1.org::v3][Sach 1,3]]; [[file:Mal_3.org::v7][Mal 3,7]]

[fn:3] [[file:Am_5.org::v17][Am 5,15]]; [[file:Jona_3.org::v9][Jona 3,9]]

[fn:4] [[file:Jes_60.org::v5][Jes 60,5]]-[[file:Jes_60.org::v9][9]]

[fn:5] [[file:Gen_12.org::v3][Gen 12,3]]

[fn:6] [[file:Jes_54.org::v11][Jes 54,11f]]; [[file:~/Documents/notes/Bibel/nt/Offb_21.org::v18][Offb 21,18]]-[[file:~/Documents/notes/Bibel/nt/Offb_21.org::v21][21]]
