#+TITLE: Tob 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2023-11-24 Fr 10:15]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+export_file_name: ~/RoamNotes/exports/Tob 3.html

<<verses>>

<<v1>>
* Tobits Gebet: 3,1-6

1 Da wurde ich traurig und begann zu weinen. In meinem Schmerz betete
ich:

<<v2>>
2 Herr, du bist gerecht, alle deine Wege und Taten zeugen von deiner
Barmherzigkeit und Wahrheit; wahr und gerecht ist dein Gericht in
Ewigkeit.

<<v3>>
3 Denk an mich und blick auf mich herab! Straf mich nicht für die Sünden
und Fehler, die ich und meine Väter dir gegenüber begangen haben.

<<v4>>
4 Sie haben nicht auf deine Gebote gehört. Darum hast du uns der
Plünderung, der Gefangenschaft und dem Tod preisgegeben; bei allen
Völkern, unter die wir zerstreut worden sind, hast du uns zum Gespött
gemacht.

<<v5>>
5 Auch jetzt treffen mich zu Recht deine harten Strafen, die du über
mich kommen lässt wegen meiner und meiner Väter Sünden. Denn wir haben
deine Gebote nicht gehalten und haben den Weg deiner Wahrheit verlassen.

<<v6>>
6 Tu also mit mir, was dir gefällt. Lass meinen Geist von mir scheiden;
lass mich sterben und zu Staub werden! Es ist besser für mich, tot zu
sein als zu leben. Denn ungerechte Vorwürfe musste ich anhören und ich
bin sehr betrübt. Lass mich jetzt aus meiner Not zur ewigen Ruhestatt
gelangen! Wende deine Augen nicht von mir ab! [fn:1] [fn:2]\\
\\

<<v7>>
* Saras Verhöhnung durch ihre Mägde: 3,7-9

7 Am gleichen Tag geschah es, dass in Ekbatana in Medien Sara, die
Tochter Raguëls, von den Mägden ihres Vaters ebenfalls beschimpft wurde.

<<v8>>
8 Sie war mit sieben Männern verheiratet gewesen; doch der böse Dämon
Aschmodai hatte sie alle getötet, bevor sie mit ihr geschlafen hatten.
Die Mägde sagten zu ihr: Begreifst du denn nicht, dass du deine eigenen
Männer erwürgst? Sieben hast du gehabt, doch kein einziger ist dir
geblieben. [fn:3]

<<v9>>
9 Mit welchem Recht also behandelst du uns so hart? Wenn sie schon
sterben mussten, dann verschwinde du doch mit ihnen! Hoffentlich
bekommen wir nie einen Sohn oder eine Tochter von dir zu sehen.\\
\\

<<v10>>
* Saras Gebet: 3,10-15

10 Als Sara das hörte, wurde sie so traurig, dass sie sich erhängen
wollte. Aber sie dachte: Ich bin die einzige Tochter meines Vaters. Wenn
ich das täte, wäre es eine große Schande für ihn und ich wäre schuld
daran, dass der alte Mann vor Kummer ins Grab sinkt.

<<v11>>
11 Darum trat sie ans Fenster und betete: Gepriesen seist du, Herr, mein
Gott. Gepriesen sei dein heiliger und ehrwürdiger Name in Ewigkeit. Alle
deine Werke sollen dich ewig preisen. [fn:4]

<<v12>>
12 Nun aber, Herr, habe ich meine Augen und mein Gesicht dir zugewandt.

<<v13>>
13 Lass mich von dieser Erde scheiden, damit ich nicht länger solche
Beschimpfungen hören muss.

<<v14>>
14 Du weißt, Herr, dass ich frei bin von jeder Sünde mit einem Mann.

<<v15>>
15 Weder meinen eigenen Namen noch den meines Vaters habe ich befleckt
in dem Land, wo ich gefangen bin. Ich bin die einzige Tochter meines
Vaters; er hat kein anderes Kind, das ihn beerben könnte. Auch ist kein
naher Verwandter da und kein Sohn eines Verwandten, dessen Frau ich
werden müsste. Schon sieben Männer habe ich verloren. Was nützt mir da
noch das Leben? Doch wenn es dir nicht gefällt, mich sterben zu lassen,
dann blick auf mich herab und hab Erbarmen mit mir, damit ich nicht
länger solche Beschimpfungen hören muss.\\
\\

<<v16>>
* Gottes Hilfe in Aussicht: 3,16-17

16 Das Gebet beider, Tobits und Saras, fand Gehör bei der Majestät des
großen Rafael.

<<v17>>
17 Er wurde gesandt, um beide zu heilen: um Tobit von den weißen Flecken
auf seinen Augen zu befreien und um Sara, die Tochter Raguëls, mit
Tobits Sohn Tobias zu vermählen und den bösen Dämon Aschmodai zu
fesseln. Denn Tobias sollte Sara zur Frau haben. Und Tobit kehrte zur
gleichen Zeit in sein Haus zurück, als Sara, die Tochter Raguëls, aus
ihrem Zimmer herabkam.\\
\\

* Footnotes

[fn:1] [[file:1.Kön_19.org::v4][1 Kön 19,4]]

[fn:2] ewige Ruhestatt: Gemeint ist das Grab (vgl. [[file:Koh_12.org::v5][Koh 12,5]]; [[file:Ps_49.org::v12][Ps 49,12]]; [[file:Ez_26.org::v20][Ez 26,20]]).

[fn:3] Der Dämon Aschmodai wird im AT nur hier genannt. Die
jüdische Tradition deutet den Namen mit dem hebräischen Zeitwort
hischmid (= verderben) als «Verderber». Wahrscheinlich ist der Name
persisch: aëschma daëva = böser Dämon.

[fn:4] [[file:Dan_6.org::v11][Dan 6,11]]
