#+TITLE: Weish 9 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-11-13 Do 14:41]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Weish 9.html


* Weish 9


<<verses>>

<<v1>>
* Die Bitte um Weisheit: 9,1-19

1 Gott der Väter und Herr des Erbarmens, /\\
 du hast das All durch dein Wort gemacht.\\
\\

<<v2>>
2 Den Menschen hast du durch deine Weisheit erschaffen, /\\
 damit er über deine Geschöpfe herrscht. [fn:1]\\
\\

<<v3>>
3 Er soll die Welt in Heiligkeit und Gerechtigkeit leiten /\\
 und Gericht halten in rechter Gesinnung. [fn:2]\\
\\

<<v4>>
4 Gib mir die Weisheit, die an deiner Seite thront, /\\
 und verstoß mich nicht aus der Schar deiner Kinder! [fn:3]\\
\\

<<v5>>
5 Ich bin ja dein Knecht, der Sohn deiner Magd, /\\
 ein schwacher Mensch, dessen Leben nur kurz ist, /\\
 und gering ist meine Einsicht in Recht und Gesetz. [fn:4]\\
\\

<<v6>>
6 Wäre einer auch vollkommen unter den Menschen, /\\
 er wird kein Ansehen genießen, wenn ihm deine Weisheit fehlt.\\
\\

<<v7>>
7 Du bist es, der mich zum König deines Volkes /\\
 und zum Richter deiner Söhne und Töchter erwählt hat.\\
\\

<<v8>>
8 Du hast befohlen, einen Tempel auf deinem heiligen Berg zu bauen /\\
 und einen Altar in der Stadt deiner Wohnung, /\\
 ein Abbild des heiligen Zeltes, das du von Anfang an entworfen hast. [fn:5] [fn:6]\\
\\

<<v9>>
9 Mit dir ist die Weisheit, die deine Werke kennt /\\
 und die zugegen war, als du die Welt erschufst. Sie weiß, was dir
gefällt /\\
 und was recht ist nach deinen Geboten. [fn:7]\\
\\

<<v10>>
10 Sende sie vom heiligen Himmel /\\
 und schick sie vom Thron deiner Herrlichkeit, damit sie bei mir sei und
alle Mühe mit mir teile /\\
 und damit ich erkenne, was dir gefällt. [fn:8]\\
\\

<<v11>>
11 Denn sie weiß und versteht alles; /\\
 sie wird mich in meinem Tun besonnen leiten /\\
 und mich in ihrem Lichtglanz schützen. [fn:9]\\
\\

<<v12>>
12 Dann wird dir mein Handeln gefallen; /\\
 ich werde dein Volk gerecht regieren /\\
 und des Throns meines Vaters würdig sein.\\
\\

<<v13>>
13 Denn welcher Mensch kann Gottes Plan erkennen, /\\
 oder wer begreift, was der Herr will? ^{[[#fn10][10]]}\\
\\

<<v14>>
14 Unsicher sind die Berechnungen der Sterblichen /\\
 und hinfällig unsere Gedanken;\\
\\

<<v15>>
15 denn der vergängliche Leib beschwert die Seele /\\
 und das irdische Zelt belastet den um vieles besorgten Geist.
^{[[#fn11][11]]}\\
\\

<<v16>>
16 Wir erraten kaum, was auf der Erde vorgeht, /\\
 und finden nur mit Mühe, was doch auf der Hand liegt; /\\
 wer kann dann ergründen, was im Himmel ist? ^{[[#fn12][12]]}\\
\\

<<v17>>
17 Wer hat je deinen Plan erkannt, wenn du ihm nicht Weisheit gegeben
/\\
 und deinen heiligen Geist aus der Höhe gesandt hast? ^{[[#fn13][13]]}\\
\\

<<v18>>
18 So wurden die Pfade der Erdenbewohner gerade gemacht /\\
 und die Menschen lernten, was dir gefällt; ^{[[#fn14][14]]}\\
\\

<<v19>>
19 durch die Weisheit wurden sie gerettet. ^{[[#fn15][15]]}\\
\\

^{[[#fnm1][1]]} ℘ 

^{[[#fnm2][2]]} ℘ 

^{[[#fnm3][3]]} ℘ 

^{[[#fnm4][4]]} ℘ 

^{[[#fnm5][5]]} ℘ 

^{[[#fnm6][6]]} .

^{[[#fnm7][7]]} ℘ 

^{[[#fnm8][8]]} ℘ 

^{[[#fnm9][9]]} ℘ 10,11-14; 11,1

^{[[#fnm10][10]]} ℘ Jes 40,13 G; Röm 11,34

^{[[#fnm11][11]]} ℘ 2 Kor 5,1

^{[[#fnm12][12]]} ℘ Joh 3,12

^{[[#fnm13][13]]} ℘ Joh 3,13; 1 Kor 2,16; Jes 32,15

^{[[#fnm14][14]]} ℘ Bar 4,4

^{[[#fnm15][15]]} Einige Vg-Handschriften fügen hinzu: alle, die dir
gefallen haben, Herr, von Anfang an.

* Footnotes

[fn:1] Gen 1,26-28

[fn:2] Lk 1,75

[fn:3] 2 Chr 1,10

[fn:4] Ps 116,16; Ijob 14,1

[fn:5] 1 Kön 5,19; Ps 132,13f; Ex 29,9.40; Hebr 8,2

[fn:6] Nach Ex 25,9.40 sollte Mose das heilige Zelt nach dem
Muster bauen, das Gott ihm gezeigt hatte. Da der Tempel nach dem Vorbild
des heiligen Zeltes gebaut war, ist er ebenfalls nach jenem Muster
gebaut. Nach anderer Auffassung ist mit dem «Zelt» der Himmel gemeint.

[fn:7] 8,4; Spr 8,27-30

[fn:8] 9,4

[fn:9] 
