#+TITLE: Weish 15 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-12-08 Mo 18:17]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Weish 15.html


* Weish 15

<<verses>>

<<v1>>
1 Du aber, unser Gott, bist gütig, wahrhaftig und langmütig; voll
Erbarmen durchwaltest du das All. [fn:1]

<<v2>>
2 Auch wenn wir sündigen, gehören wir dir, da wir deine Stärke kennen;
doch wir wollen nicht sündigen, da wir wissen, dass wir dein Eigentum
sind. [fn:2]

<<v3>>
3 Denn es ist vollendete Gerechtigkeit, dich zu verstehen; und deine
Stärke zu kennen ist die Wurzel der Unsterblichkeit. [fn:3]

<<v4>>
4 Die arglistige Erfindung der Menschen hat uns nicht verführt, die
unfruchtbare Arbeit der Maler, eine mit bunten Farben besudelte Gestalt. [fn:4]

<<v5>>
5 Ihr Anblick erregt die Sehnsucht der Toren und weckt in ihnen das
Verlangen nach der leblosen Gestalt eines toten Bildes.

<<v6>>
6 Liebhaber des Bösen und solcher Hoffnungen würdig sind alle, die es
anfertigen, die nach ihm verlangen und die es anbeten. [fn:5]

<<v7>>
7 Der Töpfer knetet mühsam den weichen Ton, um daraus Gefäße zu unserem
Gebrauch zu formen. Aus dem gleichen Lehm bildet er solche, die sauberen
Zwecken dienen, und solche für das Gegenteil, alle in gleicher Weise;
über den Gebrauch eines jeden entscheidet der Töpfer. [fn:6]

<<v8>>
8 Aus dem gleichen Lehm formt er in verkehrter Mühe auch einen nichtigen
Gott, er, der vor kurzem aus Erde entstand und bald dorthin zurückkehrt,
woher er genommen ist, wenn seine Seele, das ihm anvertraute Darlehen,
zurückgefordert wird. [fn:7]

<<v9>>
9 Doch es kümmert ihn nicht, dass er dahinschwinden wird und nur ein
kurzes Leben hat. Er wetteifert mit Goldschmieden und Silbergießern, er
ahmt Kupferschmiede nach und sieht seinen Ruhm darin, Trugbilder zu
formen.

<<v10>>
10 Asche ist sein Herz, noch weniger wert als Erdenstaub seine Hoffnung,
und sein Leben ist wertloser als Lehm. [fn:8]

<<v11>>
11 Seinen eigenen Bildner hat er nämlich nicht erkannt, den, der ihm
eine wirkende Seele eingehaucht und Lebensatem eingeblasen hat.

<<v12>>
12 Nein, er hält unser Leben für ein Kinderspiel, das Dasein für einen
einträglichen Jahrmarkt; er sagt, man müsse aus allem, auch aus
Schlechtem, Gewinn ziehen.

<<v13>>
13 Denn er weiß besser als alle, dass er sündigt, wenn er aus dem
gleichen Erdenstoff nicht nur zerbrechliche Gefäße, sondern auch
Götzenbilder fertigt. [fn:9]

<<v14>>
14 Ganz unverständig aber und ärmer als eines Kindes Seele waren die
Feinde, die dein Volk knechteten. [fn:10] [fn:11]

<<v15>>
15 Sie hielten alle Götzen der Völker für Götter, Götter, die weder ihre
Augen gebrauchen können, um zu sehen, noch ihre Nase, um die Luft zu
atmen, noch ihre Ohren, um zu hören, noch die Finger ihrer Hände, um zu
tasten, und deren Füße nicht gehen können. [fn:12]

<<v16>>
16 Ein Mensch hat sie gemacht, einer, dem der Geist nur geliehen ist,
hat sie gebildet; kein Mensch hat die Kraft, einen Gott zu bilden, der
auch nur ihm selber ähnlich wäre.

<<v17>>
17 Als Sterblicher schafft er mit frevelhaften Händen nur Totes. Er ist
besser als seine angebeteten Gebilde; denn er bekam einmal Leben, diese
aber nie. [fn:13]

<<v18>>
18 Sie verehren sogar die widerlichsten Tiere, die dümmsten im Vergleich
mit den anderen, [fn:14]

<<v19>>
19 solche, die nicht einmal schön sind, sodass man an ihnen Gefallen
finden könnte, soweit das beim Anblick von Tieren möglich ist, die zudem
Gottes Lob und seinen Segen verloren haben. [fn:15]\\
\\


* Footnotes

[fn:1] [[file:Weish_8.org::v1][8,1]]; [[file:Ex_34.org::v6][Ex 34,6]]; [[file:Ps_86.org::v5][Ps 86,5]].[[file:Ps_86.org::v15][15]]

[fn:2] [[file:Weish_12.org::v16][12,16-18]]

[fn:3] [[file:Hos_6.org::v6][Hos 6,6]]; [[file:~/Documents/notes/Bibel/nt/1.Joh_2.org::v3][1 Joh 2,3-6]]

[fn:4] [[file:Weish_13.org::v14][13,14]]; [[file:Weish_14.org::v20][14,20]]

[fn:5] [[file:Weish_14.org::v8][14,8-10]]

[fn:6] [[file:Jer_18.org::v3][Jer 18,3f]]; [[file:~/Documents/notes/Bibel/nt/Röm_9.org::v21][Röm 9,21]]

[fn:7] [[file:Gen_2.org::v7][Gen 2,7]]; [[file:Gen_3.org::v19][3,19]]; [[file:Koh_12.org::v7][Koh 12,7]]; [[file:~/Documents/notes/Bibel/nt/Lk_12.org::v20][Lk 12,20]]

[fn:8] [[file:Weish_3.org::v18][3,18]]; [[file:Weish_5.org::v14][5,14]]; [[file:Weish_14.org::v29][14,29]]; [[file:2.Makk_7.org::v14][2 Makk 7,14]]

[fn:9] [[v7][15,7f]]

[fn:10] [[file:Weish_12.org::v24][12,24]]

[fn:11] 14-19: Der Weise redet noch einmal vom Götzendienst
der Ägypter, um dann in 16,1 den in 11,15 begonnenen Vergleich zu Ende
zu führen.

[fn:12] [[file:Ps_115.org::v4][Ps 115,4-7]]

[fn:13] [[file:Weish_13.org::v10][13,10]]

[fn:14] (18-19) [[file:Weish_11.org::v15][11,15]]; [[file:Weish_12.org::v24][12,24]]

[fn:15] [[file:Gen_1.org::v21][Gen 1,21f]].[[file:Gen_1.org::v25][25]]; [[file:Gen_3.org::v14][3,14]]
