:PROPERTIES:
:ID:       ded7b11b-cbb2-435b-a7b1-3142046285cc
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch der Weisheit* --
[[file:Weish_1.html][1]] ... [[file:Weish_12.html][12]]
[[file:Weish_13.html][13]] *14* [[file:Weish_15.html][15]]
[[file:Weish_16.html][16]] ... [[file:Weish_19.html][19]]

--------------

* Weish 14
  :PROPERTIES:
  :CUSTOM_ID: weish-14
  :END:

<<verses>>

<<v1>>
1 Ein anderer, der sich zu einer Seefahrt rüstet, auf der er wilde Wogen
durchqueren wird, ruft ein Holz an, das gebrechlicher ist als das
Fahrzeug, das ihn trägt.

<<v2>>
2 Das Fahrzeug hat der Erwerbstrieb ersonnen und die Weisheit eines
Künstlers hergestellt.

<<v3>>
3 Deine Vorsehung, Vater, steuert es; denn du hast auch im Meer einen
Weg gebahnt und in den Wogen einen sicheren Pfad. ^{[[#fn1][1]]}

<<v4>>
4 Damit zeigst du, dass du imstande bist, aus jeder Lage zu retten, so
dass auch jemand, der keine Erfahrung hat, ein Schiff besteigen kann.
^{[[#fn2][2]]}

<<v5>>
5 Du willst, dass die Werke deiner Weisheit nicht ungenutzt bleiben.
Darum vertrauen Menschen ihr Leben sogar einem winzigen Holz an und
fahren wohlbehalten auf einem Floss durch die Brandung. ^{[[#fn3][3]]}

<<v6>>
6 So hat auch in der Urzeit beim Untergang der übermütigen Riesen die
Hoffnung der Welt sich auf ein Floss geflüchtet und, durch deine Hand
gesteuert, der Welt den Samen eines neuen Geschlechtes hinterlassen.
^{[[#fn4][4]]}

<<v7>>
7 Denn Segen ruht auf dem Holz, durch das Gerechtigkeit geschieht.

<<v8>>
8 Fluch hingegen trifft das von Händen geformte Holz und seinen Bildner,
ihn, weil er es bearbeitet hat, jenes, weil es Gott genannt wurde,
obwohl es vergänglich ist. ^{[[#fn5][5]]}

<<v9>>
9 Denn Gott sind in gleicher Weise Frevler wie Frevel verhasst;
^{[[#fn6][6]]}

<<v10>>
10 mit dem Bildner wird sein Werk der Strafe verfallen.

<<v11>>
11 Darum kommt auch über die Götzenbilder der Völker das Gericht, weil
sie in Gottes Schöpfung zum Gräuel geworden sind, zum Anstoß für die
Seelen der Menschen und zur Schlinge für die Füße der Toren.
^{[[#fn7][7]]}

<<v12>>
12 Mit dem Gedanken an Götzenbilder beginnt der Abfall und ihre
Erfindung führt zur Sittenverderbnis. ^{[[#fn8][8]][[#fn9][9]]}

<<v13>>
13 Weder waren sie von Anfang an da, noch werden sie ewig bleiben.

<<v14>>
14 Durch die eitle Ruhmsucht der Menschen sind sie in die Welt gekommen;
darum ist ihnen auch ein jähes Ende zugedacht. ^{[[#fn10][10]]}

<<v15>>
15 Bedrückt durch allzu frühe Trauer ließ ein Vater von seinem Kind, das
gar schnell hinweggerafft wurde, ein Bildnis machen; so ehrte er einen
toten Menschen als Gott und führte bei seinen Leuten geheime Kulte und
festliche Bräuche ein. ^{[[#fn11][11]]}

<<v16>>
16 Im Lauf der Zeit verfestigte sich die frevelhafte Sitte und wurde
schließlich als Gesetz befolgt;

<<v17>>
17 die Standbilder erhielten auf Anordnung der Herrscher göttliche
Verehrung. Konnten die Menschen einen König nicht unmittelbar ehren,
weil er weit weg wohnte, dann vergegenwärtigten sie den Fernen; sie
machten von dem verehrten König ein Bildnis, das allen sichtbar war, um
dem Abwesenden, als ob er gegenwärtig wäre, mit Eifer zu huldigen.

<<v18>>
18 Der Ehrgeiz des Künstlers führte dazu, dass auch jene, die den König
gar nicht kannten, ihm göttliche Verehrung erwiesen.

<<v19>>
19 Wohl um dem Herrscher zu gefallen, bot er seine ganze Kunst auf, um
ihn schöner darzustellen, als er war.

<<v20>>
20 Von der Anmut des Bildes hingerissen, betete die Menge den, der noch
kurz zuvor nur als Mensch geehrt wurde, jetzt wie einen Gott an.

<<v21>>
21 Der Welt ist dies zum Verhängnis geworden: Die Menschen haben, unter
dem Druck von Unglück oder Herrschermacht, Stein und Holz den Namen
beigelegt, der mit niemand geteilt werden kann. ^{[[#fn12][12]]}

<<v22>>
22 Als ob es nicht genug wäre, in der Erkenntnis Gottes zu irren, nennen
sie in dem heftigen Zwiespalt, den die Unwissenheit in ihr Leben bringt,
so große Übel auch noch Frieden. ^{[[#fn13][13]]}

<<v23>>
23 Bei kindermörderischen Festbräuchen, heimlichen Kulten oder wilden
Gelagen mit fremdartigen Sitten ^{[[#fn14][14]]}

<<v24>>
24 halten sie weder Leben noch Ehe rein, sondern einer tötet
heimtückisch den andern oder beleidigt ihn durch Ehebruch.
^{[[#fn15][15]]}

<<v25>>
25 Alles ist ein wirres Gemisch von Blut und Mord, Diebstahl und Betrug,
Verdorbenheit, Untreue, Aufruhr und Meineid;

<<v26>>
26 es herrscht Umkehrung der Werte, undankbare Vergesslichkeit,
Befleckung der Seelen, widernatürliche Unzucht, Zerrüttung der Ehen,
Ehebruch und Zügellosigkeit.

<<v27>>
27 Die Verehrung der namenlosen Götzenbilder ist aller Übel Anfang,
Ursache und Höhepunkt. ^{[[#fn16][16]]}

<<v28>>
28 Sie rasen im Freudentaumel, weissagen Lügen, leben in Ungerechtigkeit
oder schwören leichthin einen Meineid.

<<v29>>
29 Im Vertrauen auf leblose Götzen fürchten sie nicht, dass ihre
Meineide ihnen schaden könnten.

<<v30>>
30 Jedoch für beides wird sie die gerechte Strafe treffen: dass sie sich
von Gott eine verkehrte Vorstellung machten, indem sie Götzenbilder
verehrten, und dass sie unter Missachtung der Heiligkeit des Eides
hinterlistig und ungerecht schworen.

<<v31>>
31 Es ist nie die Macht derer, bei denen sie schworen, sondern immer die
den Sündern gebührende Strafe, die die Vergehen der Frevler verfolgt.

^{[[#fnm1][1]]} ℘ Jes 43,16

^{[[#fnm2][2]]} ℘ Ps 107,28-30

^{[[#fnm3][3]]} ℘ Gen 1,28

^{[[#fnm4][4]]} ℘ Gen 6 - 8; Bar 3,26-28; Weish 10,4f; Sir 44,17f

^{[[#fnm5][5]]} ℘ Dtn 27,15

^{[[#fnm6][6]]} ℘ (9-10) Dtn 7,25f

^{[[#fnm7][7]]} ℘ Jes 2,18f; Jer 10,15; Weish 14,14; Ps 106,36

^{[[#fnm8][8]]} ℘ 15,5; Num 25,1f

^{[[#fnm9][9]]} 12-21: Die Götzenverehrung ist unter dem Druck von
Unglück (V. 15) und Herrscherstolz (VV. 16-20) entstanden. Für beides
gab es auch in Ägypten Beispiele.

^{[[#fnm10][10]]} ℘ 14,10f

^{[[#fnm11][11]]} ℘ 12,4

^{[[#fnm12][12]]} ℘ Jes 42,8

^{[[#fnm13][13]]} ℘ Röm 1,24-32

^{[[#fnm14][14]]} ℘ 12,4f

^{[[#fnm15][15]]} ℘ Lev 18,24

^{[[#fnm16][16]]} ℘ 14,12
