:PROPERTIES:
:ID:       588fd602-d499-4dbb-b322-a0d301d29ce6
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch der Weisheit* --
[[file:Weish_1.html][1]] ... [[file:Weish_8.html][8]]
[[file:Weish_9.html][9]] *10* [[file:Weish_11.html][11]]
[[file:Weish_12.html][12]] ... [[file:Weish_19.html][19]]

--------------

* Weish 10
  :PROPERTIES:
  :CUSTOM_ID: weish-10
  :END:

<<verses>>

<<v1>>
*** Die rettende Macht der Weisheit - sieben Beispiele: 10,1 - 11,4
    :PROPERTIES:
    :CUSTOM_ID: die-rettende-macht-der-weisheit---sieben-beispiele-101---114
    :END:
**** Adam: 10,1-3
     :PROPERTIES:
     :CUSTOM_ID: adam-101-3
     :END:
1 Sie hat den Urvater der Welt nach seiner Erschaffung behütet, als er
noch allein war; sie hat ihn aus seiner Sünde befreit ^{[[#fn1][1]]}

<<v2>>
2 und ihm die Kraft gegeben, über alles zu herrschen. ^{[[#fn2][2]]}

<<v3>>
3 Ein Ungerechter aber, der in seinem Zorn von ihr abfiel, ging durch
seine Leidenschaft zugrunde, die ihn zum Brudermord trieb.
^{[[#fn3][3]]}\\
\\

<<v4>>
**** Noach: 10,4
     :PROPERTIES:
     :CUSTOM_ID: noach-104
     :END:
4 Die Weisheit hat die Erde, die seinetwegen überflutet wurde, wieder
gerettet und den Gerechten auf wertlosem Holz durch die Wasser
gesteuert. ^{[[#fn4][4]]}\\
\\

<<v5>>
**** Abraham: 10,5
     :PROPERTIES:
     :CUSTOM_ID: abraham-105
     :END:
5 Als die Völker, einmütig nur in ihrer Schlechtigkeit, durch die
Verwirrung ihrer Sprache getrennt wurden, erwählte sie den Gerechten und
behütete ihn, sodass er vor Gott ohne Tadel war und trotz der Liebe zu
seinem Kind stark blieb. ^{[[#fn5][5]]}\\
\\

<<v6>>
**** Lot: 10,6-9
     :PROPERTIES:
     :CUSTOM_ID: lot-106-9
     :END:
6 Als die Frevler zugrunde gingen, rettete sie einen Gerechten, sodass
er vor dem Feuer fliehen konnte, das auf die fünf Städte fiel;
^{[[#fn6][6]]}

<<v7>>
7 von ihrer Schlechtigkeit zeugen heute noch rauchendes Ödland und
Pflanzen, die zur Unzeit Früchte tragen, und eine Salzsäule ragt als
Denkmal einer ungläubigen Seele empor. ^{[[#fn7][7]]}

<<v8>>
8 Jene, die an der Weisheit achtlos vorübergingen, erlitten nicht nur
Schaden, weil sie das Gute nicht erkannten, sondern sie hinterließen
auch den Lebenden ein Mahnmal ihrer Torheit, damit nicht verborgen
bleibe, worin sie sich verfehlt hatten.

<<v9>>
9 Die Weisheit aber rettete ihre Diener aus jeglicher Mühsal.\\
\\

<<v10>>
**** Jakob: 10,10-12
     :PROPERTIES:
     :CUSTOM_ID: jakob-1010-12
     :END:
10 Einen Gerechten, der vor dem Zorn des Bruders floh, geleitete sie auf
geraden Wegen, zeigte ihm das Reich Gottes und enthüllte ihm heilige
Geheimnisse. Sie machte ihn reich bei seiner harten Arbeit und vermehrte
den Ertrag seiner Mühen. ^{[[#fn8][8]]}

<<v11>>
11 Sie half ihm gegen die Habsucht seiner Unterdrücker und verschaffte
ihm Wohlstand.

<<v12>>
12 Sie beschützte ihn vor seinen Feinden und gab ihm Sicherheit vor
seinen Verfolgern. In einem harten Kampf verlieh sie ihm den
Siegespreis, damit er erkannte, dass Gottesfurcht stärker als alles
andere ist. ^{[[#fn9][9]]}\\
\\

<<v13>>
**** Josef: 10,13-14
     :PROPERTIES:
     :CUSTOM_ID: josef-1013-14
     :END:
13 Einen Gerechten, der verkauft worden war, ließ sie nicht im Stich,
sondern bewahrte ihn vor der Sünde. ^{[[#fn10][10]]}

<<v14>>
14 Sie stieg mit ihm in den Kerker hinab und verließ ihn während seiner
Gefangenschaft nicht, bis sie ihm das königliche Zepter brachte und
Gewalt über seine Bedrücker. Sie überführte alle, die ihn beschuldigt
hatten, als Lügner und verlieh ihm ewigen Ruhm. ^{[[#fn11][11]]}\\
\\

<<v15>>
**** Das Volk Israel: 10,15 - 11,4
     :PROPERTIES:
     :CUSTOM_ID: das-volk-israel-1015---114
     :END:
15 Sie hat ein heiliges Volk, ein untadeliges Geschlecht, aus der Gewalt
einer Nation gerettet, die es unterdrückte. ^{[[#fn12][12]]}

<<v16>>
16 Sie ging in die Seele eines Dieners des Herrn ein und widerstand
schrecklichen Königen durch Zeichen und Wunder.
^{[[#fn13][13]][[#fn14][14]]}

<<v17>>
17 Sie gab den Heiligen den Lohn ihrer Mühen und geleitete sie auf
wunderbarem Weg. Sie wurde ihnen am Tag zum Schutz und in der Nacht zum
Sternenlicht. ^{[[#fn15][15]]}

<<v18>>
18 Sie führte sie durch das Rote Meer und geleitete sie durch gewaltige
Wasser. ^{[[#fn16][16]]}

<<v19>>
19 Ihre Feinde aber ließ sie in der Flut ertrinken und spülte sie aus
der Tiefe des Abgrunds ans Land. ^{[[#fn17][17]]}

<<v20>>
20 Darum plünderten die Gerechten die Frevler aus, sie priesen, Herr,
deinen heiligen Namen und lobten einmütig deine schützende Hand.
^{[[#fn18][18]]}

<<v21>>
21 Denn die Weisheit hat den Mund der Stummen geöffnet und die Zungen
der Unmündigen hat sie beredt gemacht.

^{[[#fnm1][1]]} ℘ Sir 49,16; Gen 5,1

^{[[#fnm2][2]]} ℘ 9,2; Gen 1,28

^{[[#fnm3][3]]} ℘ Gen 4,3-15

^{[[#fnm4][4]]} ℘ Sir 44,17f; Weish 14,6f

^{[[#fnm5][5]]} ℘ Gen 11,1-9; 12,1-3; 15,1-6; 22,1-12; Sir 44,19f

^{[[#fnm6][6]]} ℘ Gen 19,23-25

^{[[#fnm7][7]]} ℘ Gen 19,26; Lk 17,32

^{[[#fnm8][8]]} ℘ Gen 27,41-45; 28,10-15; 30,31-43

^{[[#fnm9][9]]} ℘ Gen 31 - 33; Hos 12,4-7

^{[[#fnm10][10]]} ℘ Gen 39; Ps 105,17f

^{[[#fnm11][11]]} ℘ Gen 41,39-47; Ps 105,19-22

^{[[#fnm12][12]]} ℘ 18,7; 19,1-9; Ex 12,37-42; Ps 106,10

^{[[#fnm13][13]]} ℘ Ex 7-12; Ps 78,43-51; 105,27-37

^{[[#fnm14][14]]} Der «Diener des Herrn» ist Mose.

^{[[#fnm15][15]]} ℘ Ex 13,21f; Ps 78,14; 105,39

^{[[#fnm16][16]]} ℘ Ex 14,21f; Ps 78,13; 106,9

^{[[#fnm17][17]]} ℘ 18,5; Ps 106,11

^{[[#fnm18][18]]} ℘ Ex 15,1-21
