:PROPERTIES:
:ID:       ade9632e-5452-4486-9588-8f00db6e9af5
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch der Weisheit* --
[[file:Weish_1.html][1]] ... [[file:Weish_4.html][4]]
[[file:Weish_5.html][5]] *6* [[file:Weish_7.html][7]]
[[file:Weish_8.html][8]] ... [[file:Weish_19.html][19]]

--------------

* Weish 6
  :PROPERTIES:
  :CUSTOM_ID: weish-6
  :END:

<<verses>>

<<v1>>
**** Die Mahnung, die Weisheit zu suchen: 6,1-21
     :PROPERTIES:
     :CUSTOM_ID: die-mahnung-die-weisheit-zu-suchen-61-21
     :END:
1 Hört also, ihr Könige, und seid verständig, /\\
 lernt, ihr Gebieter der ganzen Welt! ^{[[#fn1][1]][[#fn2][2]]}\\
\\

<<v2>>
2 Horcht, ihr Herrscher der Massen, /\\
 die ihr stolz seid auf Völkerscharen!\\
\\

<<v3>>
3 Der Herr hat euch die Gewalt gegeben, /\\
 der Höchste die Herrschaft, /\\
 er, der eure Taten prüft und eure Pläne durchforscht. ^{[[#fn3][3]]}\\
\\

<<v4>>
4 Ihr seid Diener seines Reichs, /\\
 aber ihr habt kein gerechtes Urteil gefällt, das Gesetz nicht bewahrt
/\\
 und die Weisung Gottes nicht befolgt.\\
\\

<<v5>>
5 Schnell und furchtbar wird er kommen und euch bestrafen; /\\
 denn über die Großen ergeht ein strenges Gericht.\\
\\

<<v6>>
6 Der Geringe erfährt Nachsicht und Erbarmen, /\\
 doch die Mächtigen werden gerichtet mit Macht.\\
\\

<<v7>>
7 Denn der Herrscher des Alls scheut niemand /\\
 und weicht vor keiner Größe zurück. Er hat Klein und Groß erschaffen
/\\
 und trägt gleiche Sorge für alle; ^{[[#fn4][4]]}\\
\\

<<v8>>
8 den Mächtigen aber droht strenge Untersuchung. ^{[[#fn5][5]]}\\
\\

<<v9>>
9 An euch also, ihr Herrscher, richten sich meine Worte, /\\
 damit ihr Weisheit lernt und nicht sündigt.\\
\\

<<v10>>
10 Wer das Heilige heilig hält, wird geheiligt, /\\
 und wer sich darin unterweisen lässt, findet Schutz.\\
\\

<<v11>>
11 Verlangt also nach meinen Worten; /\\
 sehnt euch danach und ihr werdet gute Belehrung empfangen.\\
\\

<<v12>>
12 Strahlend und unvergänglich ist die Weisheit; /\\
 wer sie liebt, erblickt sie schnell, /\\
 und wer sie sucht, findet sie. ^{[[#fn6][6]]}\\
\\

<<v13>>
13 Denen, die nach ihr verlangen, /\\
 gibt sie sich sogleich zu erkennen.\\
\\

<<v14>>
14 Wer sie am frühen Morgen sucht, braucht keine Mühe, /\\
 er findet sie vor seiner Türe sitzen. ^{[[#fn7][7]]}\\
\\

<<v15>>
15 Über sie nachzusinnen ist vollkommene Klugheit; /\\
 wer ihretwegen wacht, wird schnell von Sorge frei.\\
\\

<<v16>>
16 Sie geht selbst umher, um die zu suchen, die ihrer würdig sind; /\\
 freundlich erscheint sie ihnen auf allen Wegen /\\
 und kommt jenen entgegen, die an sie denken. ^{[[#fn8][8]]}\\
\\

<<v17>>
17 Ihr Anfang ist aufrichtiges Verlangen nach Bildung; /\\
 das eifrige Bemühen um Bildung aber ist Liebe. ^{[[#fn9][9]]}\\
\\

<<v18>>
18 Liebe ist Halten ihrer Gebote; /\\
 Erfüllen der Gebote sichert Unvergänglichkeit, / ^{[[#fn10][10]]}\\
\\

<<v19>>
19 und Unvergänglichkeit bringt in Gottes Nähe.

<<v20>>
20 So führt das Verlangen nach Weisheit zur Herrschaft hinauf.\\
\\

<<v21>>
21 Ihr Herrscher der Völker, wenn ihr Gefallen an Thronen und Zeptern
habt, /\\
 dann ehrt die Weisheit, damit ihr ewig herrscht. ^{[[#fn11][11]]}\\
\\

<<v22>>
** Das Wesen und Wirken der Weisheit: 6,22 - 8,18
   :PROPERTIES:
   :CUSTOM_ID: das-wesen-und-wirken-der-weisheit-622---818
   :END:
**** Einleitung: 6,22-25
     :PROPERTIES:
     :CUSTOM_ID: einleitung-622-25
     :END:
22 Ich will verkünden, was die Weisheit ist und wie sie wurde, /\\
 und will euch kein Geheimnis verbergen. Ich will ihre Spur vom Anfang
der Schöpfung an verfolgen, /\\
 ihre Kenntnis will ich verbreiten /\\
 und nicht an der Wahrheit vorbeigehen. ^{[[#fn12][12]][[#fn13][13]]}\\
\\

<<v23>>
23 Verzehrender Neid soll mich nicht auf meinem Weg begleiten; /\\
 denn er hat mit der Weisheit nichts gemein. ^{[[#fn14][14]]}\\
\\

<<v24>>
24 Eine große Anzahl von Weisen ist Heil für die Welt, /\\
 ein kluger König ist Wohlstand für das Volk. ^{[[#fn15][15]]}\\
\\

<<v25>>
25 Lasst euch also durch meine Worte unterweisen; /\\
 es wird euch von Nutzen sein.\\
\\

^{[[#fnm1][1]]} ℘ Ps 2,10

^{[[#fnm2][2]]} 1-8: Salomo nimmt die Anrede an die Herrscher wieder
auf; mit «also» zeigt er, dass er sie auch in 1,16 - 5,23 als seine
Hörer voraussetzt, obwohl er sie nicht mehr direkt anredet. Die Mahnung,
verständig zu sein, nimmt auf das Weltgericht Bezug (5,17-23). Die
Könige sollen sich nicht mit ihrer Herrschermacht brüsten, sondern
bedenken, dass sie sich als Diener Gottes und seines Reiches vor dem
strengen Richter zu verantworten haben. Vg fügt vor V. 1 ein: Besser ist
Weisheit als Kraft und ein kluger Mann (ist besser) als ein starker.
Dieser Vers ist in Vg als V. 1 gezählt; entsprechend verschiebt sich die
Verszählung.

^{[[#fnm3][3]]} ℘ Röm 13,1; 1 Chr 28,9

^{[[#fnm4][4]]} ℘ Ijob 34,19; Weish 12,13

^{[[#fnm5][5]]} ℘ Lk 12,48

^{[[#fnm6][6]]} ℘ Spr 8,17

^{[[#fnm7][7]]} ℘ Spr 8,34

^{[[#fnm8][8]]} ℘ Spr 8,2f

^{[[#fnm9][9]]} 17-21: Ein sog. Kettenschluss, der zeigt, wie das
Verlangen nach Weisheit in Gottes Nähe und damit zur Herrschaft führt.

^{[[#fnm10][10]]} ℘ Joh 14,23

^{[[#fnm11][11]]} Einige wichtige Vg-Handschriften fügen als V. 23
hinzu: Liebt das Licht der Weisheit, ihr alle, die ihr den Völkern
vorsteht. - Die VV. 22-25 werden in Vg als VV. 24-27 gezählt.

^{[[#fnm12][12]]} ℘ Spr 8,22-31

^{[[#fnm13][13]]} 22-25: Salomo will seine Weisheit neidlos mitteilen
und möglichst viele weise machen, weil eine große Zahl von Weisen der
Welt Heil, Frieden und Glück bringen kann.

^{[[#fnm14][14]]} ℘ 7,13

^{[[#fnm15][15]]} ℘ Spr 11,14
