#+TITLE: Weish 19 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-04-09 Do 13:55]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Weish 19.html

* Weish 19

<<verses>>

<<v1>>
* Untergang im Meer - Rettung durch das Meer: 19,1-17

1 Über die Frevler kam erbarmungsloser Zorn, bis sie vernichtet waren;
denn Gott wusste im Voraus, wie sie sich verhalten würden: [fn:1]

<<v2>>
2 Sie selbst hatten den Abzug der Gerechten gestattet und sie sogar dazu
gedrängt; dann aber änderten sie ihren Sinn und verfolgten sie. [fn:2]

<<v3>>
3 Sie waren noch mit der Bestattung der Toten beschäftigt und klagten an
ihren Gräbern, als sie in ihrer Torheit einen anderen Entschluss fassten
und denen wie Entlaufenen nachsetzten, denen sie flehentlich zugeredet
hatten wegzugehen. [fn:3]

<<v4>>
4 Das selbst verschuldete Verhängnis trieb sie in diesen Untergang und
ließ sie alles vergessen, was geschehen war; denn sie sollten über die
bisherigen Plagen hinaus die äußerste Strafe erleiden. [fn:4]

<<v5>>
5 Deinem Volk aber sollte sich ein unerwarteter Weg eröffnen, während
jene einen ungewöhnlichen Tod fanden. [fn:5]

<<v6>>
6 Das Wesen der ganzen Schöpfung wurde neu gestaltet; sie gehorchte
deinen Befehlen, damit deine Kinder unversehrt bewahrt blieben. [fn:6]

<<v7>>
7 Man sah die Wolke, die das Lager überschattete, trockenes Land tauchte
auf, wo zuvor Wasser war; es zeigte sich ein Weg ohne Hindernisse durch
das Rote Meer, eine grüne Ebene stieg aus der gewaltigen Flut. [fn:7]

<<v8>>
8 Von deiner Hand behütet, zogen sie vollzählig hindurch und sahen
staunenswerte Wunder.

<<v9>>
9 Sie weideten wie Rosse, hüpften wie Lämmer und lobten dich, Herr,
ihren Retter. [fn:8]

<<v10>>
10 Denn sie dachten zudem auch an das, was im fremden Land geschehen
war: wie Mücken nicht von Tieren, sondern von der Erde hervorgebracht
wurden und wie der Fluss nicht Wassertiere, sondern eine Menge Frösche
auswarf. [fn:9]

<<v11>>
11 Schließlich sahen sie auch Vögel auf eine neue Weise entstehen, als
sie, um ihre Gier zu befriedigen, nach üppigen Speisen verlangten. [fn:10] [fn:11]

<<v12>>
12 Zu ihrem Trost entstiegen nämlich Wachteln dem Meer. [fn:12]

<<v13>>
13 Die Strafen kamen über die Sünder nicht ohne Warnung durch wuchtige
Blitze. Mit Recht mussten sie für ihre bösen Taten leiden, weil sie
einen so schlimmen Fremdenhass gezeigt hatten. [fn:13]

<<v14>>
14 Während andere die Unbekannten, die zu ihnen kamen, nicht aufnahmen,
machten diese sogar Gäste, die ihre Wohltäter waren, zu Sklaven. [fn:14] [fn:15]

<<v15>>
15 Noch mehr: Gewiss wird auch jene eine Strafe treffen, weil sie Fremde
feindselig empfangen hatten;

<<v16>>
16 diese aber haben Gäste, die sie festlich aufgenommen hatten und die
schon die gleichen Bürgerrechte genossen, mit schwerem Frondienst
geplagt.

<<v17>>
17 Wie jene an der Türe des Gerechten mit Blindheit geschlagen wurden,
so auch diese, als sie von dichter Finsternis umgeben waren und jeder
versuchte, seine Türe zu finden. [fn:16] [fn:17]\\
\\

<<v18>>
* Schluss: 19,18-22

18 Die Elemente verändern sich untereinander, wie auf einer Harfe die
Töne den Rhythmus ändern und doch den gleichen Klang behalten. Dies
lässt sich aus der Betrachtung der Geschehnisse deutlich erkennen. [fn:18]

<<v19>>
19 Landtiere verwandelten sich in Wassertiere und schwimmende Tiere
stiegen ans Land.

<<v20>>
20 Das Feuer steigerte im Wasser die ihm eigene Kraft und das Wasser
vergaß seine löschende Wirkung. [fn:19]

<<v21>>
21 Flammen verzehrten nicht das Fleisch der hinfälligen Tiere, die
hineingerieten, noch schmolz im Feuer die eisartige, leicht schmelzende
himmlische Speise. [fn:20]

<<v22>>
22 In allem hast du, Herr, dein Volk groß gemacht und verherrlicht; du
hast es nicht im Stich gelassen, sondern bist ihm immer und überall
beigestanden. [fn:21]\\
\\

* Footnotes

[fn:1] [[file:Ex_14.org::v13][Ex 14,13f]]

[fn:2] [[file:Ex_12.org::v31][Ex 12,31-33]]; [[file:Ex_14.org::v3][Ex 14,3-31]]

[fn:3] [[file:Weish_18.org::v12][18,12]]

[fn:4] [[file:Weish_12.org::v27][12,27]]

[fn:5] [[file:Weish_10.org::v18][10,18f]]

[fn:6] [[file:Weish_5.org::v20][5,20]]; [[file:Weish_16.org::v24][16,24]]; [[v10][19,10f]].[[v18][18]]

[fn:7] [[file:Ex_14.org::v19][Ex 14,19-22]]

[fn:8] [[file:Jes_63.org::v13][Jes 63,13f]]; [[file:Ex_15.org][Ex 15]]

[fn:9] [[file:Weish_16.org::v9][16,9]]; [[file:Ex_8.org::v12][Ex 8,12f]]; [[file:Weish_16.org::v1][Weish 16,1]]; [[file:Ex_7.org::v28][Ex 7,28]] - [[file:Ex_8.org::v2][8,2]]

[fn:10] [[file:Weish_16.org::v2][16,2]]; [[v19][19,19]]

[fn:11] 11f: Der Verfasser deutet «vom Meer her» ([[file:Num_11.org::v31][Num 11,31]])
so, wie wenn die Wachteln aus dem Meer aufgetaucht wären.

[fn:12] [[file:Num_11.org::v31][Num 11,31f]]

[fn:13] [[file:Ex_9.org::v18][Ex 9,18]]; [[file:Weish_12.org::v26][Weish 12,26]]

[fn:14] [[file:Ri_19.org::v15][Ri 19,15-30]]; [[file:Gen_47.org::v25][Gen 47,25]]

[fn:15] 14-17: Noch schlimmer als die Bewohner von Sodom (vgl. [[file:Gen_19.org::v4][Gen 19,4-11]]), weil sie die Nachkommen Jakobs, der mit seinen Söhnen vom Pharao nach Ägypten eingeladen worden war ([[file:Gen_45.org::v17][Gen 45,17f]]), nicht nach den Regeln des Gastrechts behandelten, sondern zu Fronsklaven machten ([[file:Ex_1.org::v11][Ex 1,11-14]]).

[fn:16] [[file:Gen_19.org::v10][Gen 19,10f]]; [[file:Weish_17.org::v2][Weish 17,2]]; [[file:Ex_10.org::v21][Ex 10,21-23]]

[fn:17] Der «Gerechte» ist Lot.

[fn:18] [[file:Weish_16.org::v25][16,25]]

[fn:19] [[file:Weish_16.org::v17][16,17f]]

[fn:20] [[file:Weish_16.org::v22][16,22f]]

[fn:21] [[file:Jes_41.org::v10][Jes 41,10]] [[file:Sir_45.org::v2f][Sir 45,2f]]
