#+TITLE: Weish 18 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-04-06 Mo 18:22]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Weish 18.html

* Weish 18

<<verses>>

<<v1>>
1 Deinen Heiligen dagegen strahlte hellstes Licht. Die anderen hörten
ihre Stimme, ohne sie selbst zu sehen, und priesen sie glücklich,
mochten diese vorher noch so viel erduldet haben. [fn:1]

<<v2>>
2 Sie dankten ihnen, dass sie für das früher erlittene Unrecht keine
Rache nahmen, und baten um Verzeihung für ihr feindliches Verhalten.

<<v3>>
3 Statt jener Finsternis gabst du den Deinen eine flammende Feuersäule
als Führerin auf unbekanntem Weg, als freundliche Sonne auf ihrer
ruhmvollen Wanderung. [fn:2]

<<v4>>
4 Jene hingegen hatten es verdient, des Lichtes beraubt und in
Finsternis gefangen zu sein, weil sie einst deine Söhne eingeschlossen
und gefangen hielten, durch die das unvergängliche Licht des Gesetzes
der Welt gegeben werden sollte. [fn:3]\\
\\

<<v5>>
* Tod der Erstgeborenen - Tod in der Wüste: 18,5-25

5 Sie hatten beschlossen, die Kinder der Heiligen zu töten, und nur ein
einziges Kind wurde ausgesetzt und gerettet. Zur Strafe hast du ihnen
viele ihrer eigenen Kinder weggenommen und sie alle auf einmal in
gewaltiger Wasserflut vernichtet. [fn:4]

<<v6>>
6 Jene Nacht wurde unseren Vätern vorher angekündigt; denn sie sollten
zuversichtlich sein und sicher wissen, welchen eidlichen Zusagen sie
vertrauen konnten.

<<v7>>
7 So erwartete dein Volk die Rettung der Gerechten und den Untergang der
Feinde.

<<v8>>
8 Während du die Gegner straftest, hast du uns zu dir gerufen und
verherrlicht.

<<v9>>
9 Denn im Verborgenen feierten die frommen Söhne der Guten ihr
Opferfest; sie verpflichteten sich einmütig auf das göttliche Gesetz,
dass die Heiligen in gleicher Weise Güter wie Gefahren teilen sollten,
und sangen schon im Voraus die Loblieder der Väter.
^{[[#fn6][6]][[#fn7][7]]}

<<v10>>
10 Da hallte ihnen das wirre Geschrei der Feinde entgegen und sie hörten
die laute Klage über die toten Kinder. ^{[[#fn8][8]]}

<<v11>>
11 Das gleiche Urteil traf Herrn und Knecht; der Mann aus dem Volk und
der König hatten das gleiche Leid zu tragen.

<<v12>>
12 Durch die gleiche Todesart hatten alle zusammen unzählige Tote. Es
waren nicht genügend Lebende da, um sie zu begraben; denn mit einem
Schlag waren die besten Nachkommen vernichtet worden. ^{[[#fn9][9]]}

<<v13>>
13 Bisher waren sie durch die Künste ihrer Zauberer ungläubig geblieben;
jetzt aber mussten sie beim Untergang der Erstgeborenen bekennen: Dieses
Volk ist Gottes Sohn. ^{[[#fn10][10]]}

<<v14>>
14 Als tiefes Schweigen das All umfing und die Nacht bis zur Mitte
gelangt war, ^{[[#fn11][11]]}

<<v15>>
15 da sprang dein allmächtiges Wort vom Himmel, vom königlichen Thron
herab als harter Krieger mitten in das dem Verderben geweihte Land.
^{[[#fn12][12]][[#fn13][13]]}

<<v16>>
16 Es trug das scharfe Schwert deines unerbittlichen Befehls, trat hin
und erfüllte alles mit Tod; es berührte den Himmel und stand auf der
Erde. ^{[[#fn14][14]]}

<<v17>>
17 Plötzlich schreckten sie furchtbare Traumgesichte auf und ungeahnte
Ängste überfielen sie. ^{[[#fn15][15]]}

<<v18>>
18 Einer stürzte hier, ein anderer dort halb tot zu Boden und bekannte,
aus welchem Grund er sterben musste.

<<v19>>
19 Denn die erschreckenden Träume hatten es ihnen vorausgesagt; sie
sollten nicht umkommen, ohne zu wissen, warum sie so Schlimmes erlitten.

<<v20>>
20 Auch die Gerechten lernten eine Probe des Todes kennen: Eine große
Anzahl wurde in der Wüste dahingerafft; doch der Zorn hielt nicht lange
an. ^{[[#fn16][16]]}

<<v21>>
21 Ein Mann ohne Tadel sprang als Vorkämpfer ein mit der Waffe seines
heiligen Dienstes, mit Gebet und sühnendem Räucherwerk. Er trat dem Zorn
entgegen, machte dem Unheil ein Ende und zeigte so, dass er dein Diener
war. ^{[[#fn17][17]][[#fn18][18]]}

<<v22>>
22 Er überwand die Not nicht durch Körperkraft und nicht durch
Waffengewalt, sondern durch das Wort bezwang er den Strafenden, indem er
ihn an die eidlich bekräftigten Bündnisse mit den Vätern erinnerte.

<<v23>>
23 Denn als die Toten sich schon häuften, trat er dazwischen, hielt
seinen Ansturm auf und schnitt ihm den Weg zu den Lebenden ab.
^{[[#fn19][19]][[#fn20][20]]}

<<v24>>
24 Auf seinem langen Gewand war die ganze Welt dargestellt, auf den vier
Reihen der Edelsteine waren die ruhmreichen Namen der Väter
eingeschnitten und auf seinem Stirnband dein hoheitsvoller Name.
^{[[#fn21][21]]}

<<v25>>
25 Davor wich der Verderber voll Furcht zurück; denn es genügte schon
diese Probe des Zornes. ^{[[#fn22][22]]}\\
\\

^{[[#fnm1][1]]} ℘ 

^{[[#fnm2][2]]} ℘ 

^{[[#fnm3][3]]} ℘ 

^{[[#fnm4][4]]} ℘ 

^{[[#fnm5][5]]} Das «Kind» ist Mose (vgl. 11,14; Ex 2,1-10).

^{[[#fnm6][6]]} ℘ 2 Chr 30,21f

^{[[#fnm7][7]]} Später wurden beim Paschamahl die Psalmen 113 bis 118
gesungen (vgl. Mt 26,30).

^{[[#fnm8][8]]} ℘ Ex 12,29f

^{[[#fnm9][9]]} ℘ Num 33,4

^{[[#fnm10][10]]} ℘ 17,7; Ex 7,11-13; 8,3; 12,31f; Weish 5,5; Ex 4,22f

^{[[#fnm11][11]]} ℘ Ex 11,4; 12,23.29

^{[[#fnm12][12]]} ℘ Ps 107,20; 147,15.18

^{[[#fnm13][13]]} Das göttliche Wort, nämlich der Vernichtungsbeschluss
Gottes, wird hier personifiziert; in Offb 19,11-21 zieht Christus, der
«das Wort Gottes» heißt, vom Himmel zum Vernichtungskampf gegen die
feindlichen Könige aus.

^{[[#fnm14][14]]} ℘ Jes 55,11; Weish 5,20; Hebr 4,12

^{[[#fnm15][15]]} ℘ 17,3; Ijob 4,13f

^{[[#fnm16][16]]} ℘ Num 17,6-14

^{[[#fnm17][17]]} ℘ Ex 28,1; Num 17,16-26

^{[[#fnm18][18]]} 21-24: Gemeint ist der Hohepriester Aaron. Zu seinem
Gewand vgl. Ex 28,5.

^{[[#fnm19][19]]} ℘ Num 17,11-13

^{[[#fnm20][20]]} Ansturm: so nach Vg; G: Zorn (vgl. V. 20).

^{[[#fnm21][21]]} ℘ Ex 28,17-21; Sir 45,11; Ex 28,36-38; Sir 45,12

^{[[#fnm22][22]]} ℘ Ex 12,23

* Footnotes

[fn:1] [[file:Ex_10.org::v23][Ex 10,23]]

[fn:2] [[file:Weish_10.org::v17][10,17]]; [[file:Ex_13.org::v21][Ex 13,21f]]; [[file:Ex_40.org::v36][40,36-38]]; [[file:Ps_78.org::v14][Ps 78,14]]; [[file:Ps_105.org::v39][105,39]]

[fn:3] [[file:Weish_17.org::v2][17,2]]; [[file:Ps_119.org::v105][Ps 119,105]]; [[file:Spr_6.org::v23][Spr 6,23]]

[fn:4] [[file:Weish_11.org::v7][11,7]]; [[file:Ex_1.org::v15][Ex 1,15-17]]; [[file:Ex_12.org::v29][12,29f]]; [[file:Ps_78.org::v51][Ps 78,51]]; [[file:Ps_105.org::v36][105,36]]; [[file:Weish_10.org::v19][Weish 10,19]]; [[file:Ex_14.org::v27][Ex 14,27f]]
