#+TITLE: Weish 16 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2026-03-05 Do 14:23]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Weish 16.html

* Weish 16


<<verses>>

<<v1>>
* Frösche - Wachteln: 16,1-4

1 Darum wurden sie mit Recht durch ähnliche Tiere gezüchtigt und durch
eine Menge von Ungeziefer gequält. [fn:1]

<<v2>>
2 Während sie auf solche Weise gezüchtigt wurden, hast du deinem Volk
eine Wohltat erwiesen und mit den Wachteln seinem heftigen Verlangen
eine fremdartige Nahrung gegeben. [fn:2]

<<v3>>
3 Während jenen in ihrem Hunger die Esslust verging wegen der
Hässlichkeit der gegen sie gesandten Tiere, bekamen diese nach nur
kurzer Entbehrung sogar eine fremdartige Speise.

<<v4>>
4 Über jene Unterdrücker sollte unabwendbarer Hunger kommen; diese aber
sollten nur kurz spüren, wie ihre Feinde gequält wurden. [fn:3]\\
\\

<<v5>>
* Heuschrecken und Stechfliegen - giftige Schlangen: 16,5 - 14

5 Auch damals, als die schreckliche Wut wilder Tiere über sie
hereinbrach und sie durch die Bisse tückischer Schlangen umkamen,
dauerte dein Zorn nicht bis ans Ende. [fn:4]

<<v6>>
6 Zur Warnung wurden sie nur kurz in Schrecken versetzt und bekamen ein
Rettungszeichen, damit sie sich an die Vorschrift deines Gesetzes
erinnerten. [fn:5]

<<v7>>
7 Wer sich dorthin wandte, wurde nicht durch das gerettet, was er
anschaute, sondern durch dich, den Retter aller. [fn:6]

<<v8>>
8 Dadurch hast du unsere Feinde überzeugt, dass du es bist, der aus
allem Übel erlöst.

<<v9>>
9 Denn sie wurden durch die Bisse der Heuschrecken und der Stechfliegen
getötet, ohne dass es ein Heilmittel für sie gab; sie verdienten es ja,
durch solches Ungeziefer gezüchtigt zu werden. [fn:7] [fn:8]

<<v10>>
10 Deine Söhne aber wurden nicht einmal durch die Zähne Gift spritzender
Schlangen überwältigt; denn dein Erbarmen kam ihnen zu Hilfe und heilte
sie.

<<v11>>
11 Sie wurden gebissen, aber schnell wieder gerettet, damit sie sich an
deine Worte erinnerten; denn sie sollten nicht in tiefes Vergessen
versinken, sondern sich ungehindert deiner Wohltaten erfreuen.

<<v12>>
12 Weder Kraut noch Wundpflaster machte sie gesund, sondern dein Wort,
Herr, das alles heilt. [fn:9]

<<v13>>
13 Du hast Gewalt über Leben und Tod; du führst zu den Toren der
Unterwelt hinab und wieder herauf. [fn:10]

<<v14>>
14 Ein Mensch kann zwar in seiner Schlechtigkeit töten; doch den
entschwundenen Geist holt er nicht zurück und die weggenommene Seele
kann er nicht befreien. [fn:11]\\
\\

<<v15>>
* Hagel - Manna: 16,15-29

15 Unmöglich ist es, deiner Hand zu entfliehen. [fn:12]

<<v16>>
16 Denn die Frevler, die behaupten, dich nicht zu kennen, wurden durch
die Kraft deines Armes gezüchtigt: Ungewöhnliche Regengüsse,
Hagelschauer und schreckliche Wolkenbrüche peitschten auf sie nieder und
Feuer verzehrte sie. [fn:13]

<<v17>>
17 Das Seltsamste war, dass das Wasser, das sonst alles löscht, die
Kraft des Feuers noch verstärkte; denn die Natur kämpft für die
Gerechten. [fn:14]

<<v18>>
18 Das eine Mal wurde die Flamme gezähmt, damit sie nicht die Tiere
verzehrte, die gegen die Ruchlosen gesandt waren; diese sollten sehen
und erkennen, dass sie von Gottes Strafe verfolgt wurden. [fn:15] [fn:16]

<<v19>>
19 Das andere Mal brannte die Flamme mit ungewöhnlicher Kraft mitten im
Wasser, um die Erzeugnisse des schuldbeladenen Landes zu vernichten. [fn:17]

<<v20>>
20 Dein Volk dagegen nährtest du mit der Speise der Engel und
unermüdlich gabst du ihm fertiges Brot vom Himmel. Deine Gabe gewährte
jeden Genuss und entsprach jedem Geschmack; [fn:18]

<<v21>>
21 sie offenbarte deine zarte Liebe zu deinen Kindern. Sie erfüllte das
Verlangen eines jeden, der sie genoss, und verwandelte sich in alles,
was einer wollte.

<<v22>>
22 Schnee und Eis hielten dem Feuer stand und schmolzen nicht. Deine
Kinder sollten erkennen, dass nur die Früchte der Feinde vom Feuer
vernichtet wurden, das im Hagel brannte und in den Regengüssen blitzte, [fn:19] [fn:20]

<<v23>>
23 und dass es umgekehrt sogar seine eigene Kraft vergaß, damit die
Gerechten Nahrung hätten. [fn:21]

<<v24>>
24 Denn die Schöpfung, die dir, ihrem Schöpfer, dient, steigert ihre
Kräfte, um die Schuldigen zu bestrafen, und hält sie zurück, um denen
Gutes zu tun, die auf dich vertrauen. [fn:22]

<<v25>>
25 Darum diente sie auch damals deinem Geschenk, das alle ernährte, und
verwandelte sich in alles, was die Bittenden wünschten.

<<v26>>
26 Deine geliebten Söhne, Herr, sollten daraus lernen: Nicht die
verschiedenartigen Früchte ernähren den Menschen, sondern dein Wort
erhält alle, die dir vertrauen. [fn:23]

<<v27>>
27 Denn dasselbe, das vom Feuer nicht vernichtet wurde, schmolz
sogleich, wenn es ein flüchtiger Sonnenstrahl erwärmte. [fn:24]

<<v28>>
28 So sollte man erkennen, dass man, um dir zu danken, der Sonne
zuvorkommen und sich noch vor dem Aufgang des Lichtes an dich wenden
muss. [fn:25]

<<v29>>
29 Denn die Hoffnung des Undankbaren schmilzt wie winterlicher Reif und
verrinnt wie unnützes Wasser. [fn:26]\\
\\


* Footnotes

[fn:1] [[file:Weish_11.org::v15][11,15]]; [[file:Weish_12.org::v23][12,23-27]]; [[file:Ex_7.org::v26][Ex 7,26]] -[[file:Ex_8.org::v11][8,11]]; [[file:Ps_78.org::v45][Ps 78,45]]; [[file:Ps_105.org::v30][105,30]]

[fn:2] [[file:Ex_16.org::v13][Ex 16,13]]; [[file:Ps_78.org::v26][Ps 78,26f]]; [[file:Ps_105.org::v40][105,40]]

[fn:3] [[file:Weish_11.org::v8][11,8f]]

[fn:4] [[file:Num_21.org::v5][Num 21,5-9]]; [[file:Weish_18.org::v20][Weish 18,20]]

[fn:5] [[file:~/Documents/notes/Bibel/nt/Joh_3.org::v14][Joh 3,14f]]

[fn:6] [[file:Jes_45.org::v21][Jes 45,21]]

[fn:7] [[file:Ex_8.org::v12][Ex 8,12-28]]; [[file:Ex_10.org::v1][10,1-20]]; [[file:Ps_78.org::v45][Ps 78,45f]]; [[file:Ps_105.org::v34][105,34f]]

[fn:8] In Ex 10,17 wird die Heuschreckenplage als Tod
bezeichnet, da sie eine todbringende Hungersnot zur Folge hat. Der
Verfasser deutet und steigert diese Aussage, indem er die Bisse der
Heuschrecken selbst als todbringend bezeichnet. Im gleichen Sinn deutet
er die Stechmückenplage.

[fn:9] [[file:Ps_107.org::v20][Ps 107,20]]

[fn:10] [[file:1.Sam_2.org::v6][1 Sam 2,6]]

[fn:11] [[file:Ps_49.org::v8][Ps 49,8f]]; [[file:~/Documents/notes/Bibel/nt/Mt_16.org::v26][Mt 16,26]]

[fn:12] [[file:Tob_13.org::v2][Tob 13,2]]

[fn:13] [[file:Ex_9.org::v13][Ex 9,13-35]]

[fn:14] [[v22][16,22]]; [[file:Ex_9.org::v24][Ex 9,24]]

[fn:15] [[file:Weish_12.org::v27][12,27]]

[fn:16] Vielleicht ist das Feuer gemeint, das die Ägypter
anzündeten, um die Heuschreckenschwärme zu vernichten, wie es noch heute
geschieht.

[fn:17] [[v17][16,17]].[[v22][22]]

[fn:18] [[file:Ex_16.org][Ex 16]]; [[file:Num_11.org::v6][Num 11,6-9]]; [[file:Ps_78.org::v23][Ps 78,23-25]]; [[file:Ps_105.org::v40][105,40]]

[fn:19] [[v19][16,19]]

[fn:20] G vergleicht in Num 11,7 das Manna mit Eis (H mit
Bdelliumharz, in Ex 16,14 mit Reif).

[fn:21] [[file:Weish_19.org::v21][19,21]]

[fn:22] [[file:Weish_19.org::v18][19,18]]

[fn:23] [[file:Dtn_8.org::v3][Dtn 8,3]]; [[file:~/Documents/notes/Bibel/nt/Mt_4.org::v4][Mt 4,4]]; [[file:~/Documents/notes/Bibel/nt/Lk_4.org::v4][Lk 4,4]]

[fn:24] [[file:Ex_16.org::v21][Ex 16,21]]; [[file:Num_11.org::v8][Num 11,8]]

[fn:25] [[file:Ps_57.org::v9][Ps 57,9]]; [[file:Ps_92.org::v3][92,3]]

[fn:26] [[file:Weish_15.org::v10][15,10]]
