#+TITLE: Weish 7 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-11-04 Di 11:58]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Weish 7.html

* Weish 7

<<verses>>

<<v1>>
* Der sterbliche Mensch als Empfänger der Weisheit: 7,1-6

1 Auch ich bin ein sterblicher Mensch wie alle anderen, /\\
 Nachkomme des ersten, aus Erde gebildeten Menschen. Im Schoß der Mutter
wurde ich zu Fleisch geformt, / [fn:1]\\
\\

<<v2>>
2 zu dem das Blut in zehn Monaten gerann durch den Samen des Mannes /\\
 und die Lust, die im Beischlaf hinzukam.\\
\\

<<v3>>
3 Geboren atmete auch ich die gemeinsame Luft, /\\
 ich fiel auf die Erde, die Gleiches von allen erduldet, /\\
 und Weinen war mein erster Laut wie bei allen.\\
\\

<<v4>>
4 In Windeln und mit Sorgen wurde ich aufgezogen; /\\
\\

<<v5>>
5 kein König trat anders ins Dasein.\\
\\

<<v6>>
6 Alle haben den einen gleichen Eingang zum Leben; /\\
 gleich ist auch der Ausgang.\\
\\

<<v7>>
* Die Gottesgabe der Weisheit: 7,7-14

7 Daher betete ich und es wurde mir Klugheit gegeben; /\\
 ich flehte und der Geist der Weisheit kam zu mir. [fn:2] [fn:3]\\
\\

<<v8>>
8 Ich zog sie Zeptern und Thronen vor, /\\
 Reichtum achtete ich für nichts im Vergleich mit ihr. [fn:4]\\
\\

<<v9>>
9 Keinen Edelstein stellte ich ihr gleich; /\\
 denn alles Gold erscheint neben ihr wie ein wenig Sand /\\
 und Silber gilt ihr gegenüber so viel wie Lehm. [fn:5]\\
\\

<<v10>>
10 Ich liebte sie mehr als Gesundheit und Schönheit /\\
 und zog ihren Besitz dem Lichte vor; /\\
 denn niemals erlischt der Glanz, /\\
 der von ihr ausstrahlt. [fn:6]\\
\\

<<v11>>
11 Zugleich mit ihr kam alles Gute zu mir, /\\
 unzählbare Reichtümer waren in ihren Händen. [fn:7]\\
\\

<<v12>>
12 Ich freute mich über sie alle, /\\
 weil die Weisheit lehrt, sie richtig zu gebrauchen, /\\
 wusste aber nicht, dass sie auch deren Ursprung ist.\\
\\

<<v13>>
13 Uneigennützig lernte ich und neidlos gebe ich weiter; /\\
 ihren Reichtum behalte ich nicht für mich. [fn:8]\\
\\

<<v14>>
14 Ein unerschöpflicher Schatz ist sie für die Menschen; /\\
 alle, die ihn erwerben, erlangen die Freundschaft Gottes. /\\
 Sie sind empfohlen durch die Gaben der Unterweisung. [fn:9]\\
\\

<<v15>>
* Bitte um die Gabe der Lehre: 7,15-21

15 Mir aber gewähre Gott, nach meiner Einsicht zu sprechen /\\
 und zu denken, wie die empfangenen Gaben es wert sind; denn er ist der
Führer der Weisheit /\\
 und hält die Weisen auf dem rechten Weg.\\
\\

<<v16>>
16 Wir und unsere Worte sind in seiner Hand, /\\
 auch alle Klugheit und praktische Erfahrung.\\
\\

<<v17>>
17 Er verlieh mir untrügliche Kenntnis der Dinge, /\\
 sodass ich den Aufbau der Welt und das Wirken der Elemente verstehe, [fn:10]\\
\\

<<v18>>
18 Anfang und Ende und Mitte der Zeiten, /\\
 die Abfolge der Sonnenwenden und den Wandel der Jahreszeiten,

<<v19>>
19 den Kreislauf der Jahre und die Stellung der Sterne,\\
\\

<<v20>>
20 die Natur der Tiere und die Wildheit der Raubtiere, /\\
 die Gewalt der Geister und die Gedanken der Menschen, /\\
 die Verschiedenheit der Pflanzen und die Kräfte der Wurzeln. [fn:11]\\
\\

<<v21>>
21 Alles Verborgene und alles Offenbare habe ich erkannt; /\\
 denn es lehrte mich die Weisheit, die Meisterin aller Dinge. [fn:12]\\
\\

<<v22>>
* Das Wesen der Weisheit: 7,22 - 8,1

22 In ihr ist ein Geist, /\\
 gedankenvoll, heilig, einzigartig, mannigfaltig, zart, beweglich, /\\
 durchdringend, unbefleckt, klar, /\\
 unverletzlich, das Gute liebend, scharf, [fn:13]\\
\\

<<v23>>
23 nicht zu hemmen, wohltätig, menschenfreundlich, /\\
 fest, sicher, ohne Sorge, alles vermögend, alles überwachend /\\
 und alle Geister durchdringend, /\\
 die denkenden, reinen und zartesten.\\
\\

<<v24>>
24 Denn die Weisheit ist beweglicher als alle Bewegung; /\\
 in ihrer Reinheit durchdringt und erfüllt sie alles.\\
\\

<<v25>>
25 Sie ist ein Hauch der Kraft Gottes /\\
 und reiner Ausfluss der Herrlichkeit des Allherrschers; /\\
 darum fällt kein Schatten auf sie.\\
\\

<<v26>>
26 Sie ist der Widerschein des ewigen Lichts, /\\
 der ungetrübte Spiegel von Gottes Kraft, /\\
 das Bild seiner Vollkommenheit. [fn:14]\\
\\

<<v27>>
27 Sie ist nur eine und vermag doch alles; /\\
 ohne sich zu ändern, erneuert sie alles. Von Geschlecht zu Geschlecht
tritt sie in heilige Seelen ein /\\
 und schafft Freunde Gottes und Propheten; [fn:15]\\
\\

<<v28>>
28 denn Gott liebt nur den, /\\
 der mit der Weisheit zusammenwohnt. [fn:16]\\
\\

<<v29>>
29 Sie ist schöner als die Sonne /\\
 und übertrifft jedes Sternbild. /\\
 Sie ist strahlender als das Licht;\\
\\

<<v30>>
30 denn diesem folgt die Nacht, /\\
 doch über die Weisheit siegt keine Schlechtigkeit.\\
\\


* Footnotes

[fn:1] 1-6: Auch der weise König Salomo ist nur ein armseliger
Mensch, dem die Weisheit nicht angeboren ist.

[fn:2] [[file:Weish_8.org::v21][8,21]]

[fn:3] 7-14: Nur durch das Gebet (vgl. 8,21 - 9,19 und [[file:1.Kön_3.org::v6][1 Kön 3,6-9]]) kann Salomo die Weisheit als Geschenk von Gott erhalten.

[fn:4] [[file:Spr_8.org::v11][Spr 8,11]]

[fn:5] [[file:Spr_3.org::v14][Spr 3,14]]

[fn:6] [[v29][7,29f]]

[fn:7] [[file:1.Kön_3.org::v13][1 Kön 3,13]]; [[file:Spr_3.org::v16][Spr 3,16]]; [[file:Spr_8.org::v18][8,18]]

[fn:8] [[file:Weish_6.org::v22][6,22]]

[fn:9] [[v28][7,28]]

[fn:10] [[file:1.Kön_5.org::v9][1 Kön 5,9f]]

[fn:11] [[file:1.Kön_5.org::v13][1 Kön 5,13]]

[fn:12] [[file:Weish_8.org::v5][8,5f]]; [[file:Weish_9.org::v9][9,9]]

[fn:13] 22f: Es werden einundzwanzig (7 mal 3) Eigenschaften
der Weisheit aufgezählt.

[fn:14] [[file:~/Documents/notes/Bibel/nt/Hebr_1.org::v3][Hebr 1,3]]; [[file:~/Documents/notes/Bibel/nt/Kol_1.org::v15][Kol 1,15]]

[fn:15] [[file:Ps_104.org::v30][Ps 104,30]]

[fn:16] [[file:Sir_4.org::v14][Sir 4,14]]
