#+TITLE: Weish 3 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-07-27 So 11:58]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Weish 3.html

* Weish 3

<<verses>>

<<v1>>
* Das jenseitige Los der Guten und der Bösen: 3,1-12

1 Die Seelen der Gerechten sind in Gottes Hand /\\
 und keine Qual kann sie berühren.\\
\\

<<v2>>
2 In den Augen der Toren sind sie gestorben, /\\
 ihr Heimgang gilt als Unglück, [fn:1]\\
\\

<<v3>>
3 ihr Scheiden von uns als Vernichtung; /\\
 sie aber sind in Frieden. [fn:2]\\
\\

<<v4>>
4 In den Augen der Menschen wurden sie gestraft; /\\
 doch ihre Hoffnung ist voll Unsterblichkeit. [fn:3]\\
\\

<<v5>>
5 Ein wenig nur werden sie gezüchtigt; /\\
 doch sie empfangen große Wohltat. /\\
 Denn Gott hat sie geprüft /\\
 und fand sie seiner würdig.\\
\\

<<v6>>
6 Wie Gold im Schmelzofen hat er sie erprobt /\\
 und sie angenommen als ein vollgültiges Opfer.\\
\\

<<v7>>
7 Beim Endgericht werden sie aufleuchten /\\
 wie Funken, die durch ein Stoppelfeld sprühen. [fn:4] [fn:5]
\\
\\

<<v8>>
8 Sie werden Völker richten /\\
 und über Nationen herrschen /\\
 und der Herr wird ihr König sein in Ewigkeit. [fn:6]\\
\\

<<v9>>
9 Alle, die auf ihn vertrauen, /\\
 werden die Wahrheit erkennen /\\
 und die Treuen werden bei ihm bleiben in Liebe. /\\
 Denn Gnade und Erbarmen wird seinen Erwählten zuteil. [fn:7]\\
\\

<<v10>>
10 Die Frevler aber werden für ihre Pläne bestraft, /\\
 sie, die den Gerechten missachtet haben /\\
 und vom Herrn abgefallen sind.\\
\\

<<v11>>
11 Unglücklich sind alle, /\\
 die Weisheit und Belehrung verachten; /\\
 leer ist ihre Hoffnung, vergeblich sind ihre Mühen /\\
 und wertlos ihre Taten. [fn:8]\\
\\

<<v12>>
12 Ihre Frauen sind unverständig /\\
 und ihre Kinder böse, /\\
 fluchbeladen ist ihr Geschlecht. [fn:9]\\
\\

<<v13>>
* Kinderlose Gerechte und kinderreiche Frevler: 3,13 - 4,6

13 Selig ist die Kinderlose, die unschuldig blieb /\\
 und kein Lager der Sünde kannte; /\\
 sie wird gleich einer Mutter geehrt, /\\
 wenn die Seelen ihren Lohn empfangen. [fn:10]\\
\\

<<v14>>
14 Selig ist auch der Kinderlose, /\\
 der sich nicht frevelhaft verging /\\
 und gegen den Herrn nichts Böses plante; /\\
 besondere Gnade wird seiner Treue zuteil /\\
 und ein gar köstlicher Anteil am Tempel des Herrn. [fn:11] [fn:12]\\
\\

<<v15>>
15 Denn ruhmreich ist der Lohn guter Mühe /\\
 und unvergänglich die Wurzel der Klugheit.\\
\\

<<v16>>
16 Doch die Kinder von Ehebrechern verkümmern /\\
 und die Nachkommen einer sündigen Verbindung schwinden dahin. [fn:13]\\
\\

<<v17>>
17 Auch wenn sie lange leben, gelten sie nichts /\\
 und ehrlos ist am Ende ihr Alter.\\
\\

<<v18>>
18 Sterben sie früh, so haben sie keine Hoffnung /\\
 und keinen Trost am Tag des Gerichts;\\
\\

<<v19>>
19 denn schlimm ist das Ende eines schuldhaften Geschlechts.\\
\\


* Footnotes

[fn:1] Der Verfasser vermeidet für die Gerechten die Ausdrücke
«Tod» und «sterben» (vgl. V. [[v3][3a]]; [[file:Weish_4.org::v7][4,7]].[[file:Weish_4.org::v10][10f]].[[file:Weish_4.org::v16][16f]]); nur die Sünder lässt er
vom Tod und Sterben der Gerechten sprechen ([[file:Weish_2.org::v20][2,20]]). Der Tod, der durch
den Neid des Teufels in die Welt gekommen ist, ist für den Verfasser
zwar der leibliche Tod, aber nur insofern er zum ewigen Tod führt
([[file:Weish_4.org::v19][4,19f]]; [[file:Weish_17.org::v20][17,20]]), also der Tod der Sünder ([[file:Weish_2.org::v24][2,24]]).

[fn:2] [[file:Jes_57.org::v2][Jes 57,2]]

[fn:3] Wie in 3,1.3b.5a.6b handelt es sich um das jenseitige
Leben der Gerechten. Die Gerechten können auch noch nach dem Martyrium
die Hoffnung auf die Unsterblichkeit haben, weil die Auferstehung des
Leibes noch aussteht.

[fn:4] Dan 12,3; Mt 13,43

[fn:5] Beim Endgericht, wörtlich: In der Zeit ihrer
Heimsuchung.

[fn:6] 1 Kor 6,2

[fn:7] 4,15

[fn:8] Sir 34,1

[fn:9] 12,11

[fn:10] 13-4,6: Kinderlosigkeit gilt sonst im AT als Unglück
und Schande (Gen 30,23; 1 Sam 1,6f.15f; vgl. Lk 1,25) oder gar als
Strafe (Lev 20,20f); im Blick auf die ewige Vergeltung werden hier die
Kinderlosen, die Gott treu dienen, der Mutter zahlreicher Kinder gleich
geachtet. 13cd: Wörtlich: denn sie wird Frucht haben bei der Heimsuchung
der Seelen.

[fn:11] Jes 56,3

[fn:12] 14a: der Kinderlose, wörtlich: der Eunuch. 14e: ein
gar köstlicher, wörtlich: ein mehr beglückender (als wenn er Kinder
hätte).

[fn:13] (16-19) 4,3-6; Sir 41,5-7
