#+TITLE: Weish 11 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-12-06 Sa 14:50]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Weish 11.html


* Weish 11

<<verses>>

<<v1>>
1 Sie ließ alles gelingen, was sie unter der Führung des heiligen
Propheten unternahmen. [fn:1]

<<v2>>
2 Sie zogen durch eine unbewohnte Wüste und schlugen in unwegsamen
Gegenden ihre Zelte auf.

<<v3>>
3 Sie leisteten ihren Feinden Widerstand und wehrten ihre Gegner ab. [fn:2]

<<v4>>
4 Als sie dürsteten und dich anriefen, wurde ihnen Wasser aus schroffem
Fels gegeben, sodass sie ihren Durst stillen konnten aus hartem Gestein. [fn:3]\\
\\

<<v5>>
* Das Volk Gottes und seine Feinde - sieben Vergleiche: 11,5 - 19,22

* Das Wasser des Nil - das Wasser aus dem Felsen: 11,5-14

5 Denn was ihren Feinden zur Strafe wurde, das empfingen sie als Wohltat
in ihrer Not. [fn:4]

<<v6>>
6 Der ständig fließende Strom wurde durch schmutziges Blut getrübt. [fn:5]

<<v7>>
7 So wurden jene für den befohlenen Kindermord gestraft. Diesen aber
gabst du wider Erwarten reichlich Wasser, [fn:6]

<<v8>>
8 nachdem du ihnen vorher durch ihren Durst gezeigt hattest, wie ihre
Gegner von dir bestraft wurden. [fn:7]

<<v9>>
9 Denn als sie geprüft und, wenn auch nur milde, zurechtgewiesen wurden,
da erkannten sie, wie die Frevler im Zorn gerichtet und gepeinigt worden
waren. [fn:8]

<<v10>>
10 Sie hast du wie ein mahnender Vater auf die Probe gestellt, die
Frevler aber wie ein strenger König gerichtet und verurteilt. [fn:9]

<<v11>>
11 Fern von den Gerechten wurden sie ebenso geplagt wie damals, als sie
ihnen noch nahe waren;

<<v12>>
12 denn zweifaches Leid und Seufzen brachte ihnen die Erinnerung an das
Vergangene:

<<v13>>
13 Als sie nämlich hörten, dass ihre eigene Bestrafung jenen sogar zur
Wohltat geworden war, da erkannten sie das Wirken des Herrn.

<<v14>>
14 Den sie einst ausgesetzt und weggeworfen, den sie mit Hohn abgewiesen
hatten, den mussten sie am Ende von allem bestaunen, nachdem sie einen
viel schlimmeren Durst gelitten hatten als die Gerechten. [fn:10]\\
\\

<<v15>>
* Erste Einschaltung: Gottes Art zu strafen: 11,15 - 12,27

15 Zur Strafe für ihre frevlerische Torheit, in die sie sich verirrt
hatten, als sie vernunftloses Gewürm und armseliges Ungeziefer
verehrten, sandtest du ihnen eine Menge vernunftloser Tiere. [fn:11] [fn:12]

<<v16>>
16 Sie sollten erkennen: Man wird mit dem gestraft, womit man sündigt. [fn:13]

<<v17>>
17 Für deine allmächtige Hand, die aus ungeformtem Stoff die Welt
gestaltet hat, wäre es keine Schwierigkeit gewesen, eine Menge von Bären
gegen sie zu senden oder grimmige Löwen [fn:14] [fn:15]

<<v18>>
18 oder unbekannte, neu geschaffene, wuterfüllte Tiere, die Feuer
sprühenden Atem aushauchen oder zischenden Dampf ausstoßen oder
schreckliche Funken aus den Augen sprühen. [fn:16]

<<v19>>
19 Nicht nur ihre verderbliche Gewalt hätte sie zermalmen, schon ihr
Furcht erregender Anblick hätte sie vernichten können.

<<v20>>
20 Aber abgesehen davon hätten sie durch einen einzigen Hauch fallen
können, verfolgt von deinem Strafgericht und fortgeweht vom Sturm deiner
Macht. Du aber hast alles nach Maß, Zahl und Gewicht geordnet. [fn:17]

<<v21>>
21 Denn du bist immer imstande, deine große Macht zu entfalten. Wer
könnte der Kraft deines Arms widerstehen? [fn:18]

<<v22>>
22 Die ganze Welt ist ja vor dir wie ein Stäubchen auf der Waage, wie
ein Tautropfen, der am Morgen zur Erde fällt. [fn:19]

<<v23>>
23 Du hast mit allen Erbarmen, weil du alles vermagst, und siehst über
die Sünden der Menschen hinweg, damit sie sich bekehren. [fn:20]

<<v24>>
24 Du liebst alles, was ist, und verabscheust nichts von allem, was du
gemacht hast; denn hättest du etwas gehasst, so hättest du es nicht
geschaffen.

<<v25>>
25 Wie könnte etwas ohne deinen Willen Bestand haben, oder wie könnte
etwas erhalten bleiben, das nicht von dir ins Dasein gerufen wäre?

<<v26>>
26 Du schonst alles, weil es dein Eigentum ist, Herr, du Freund des
Lebens. [fn:21]
 

* Footnotes

[fn:1] [[file:Hos_12.org::v14][Hos 12,14]]

[fn:2] [[file:Ex_17.org::v8][Ex 17,8-16]]

[fn:3] [[file:Ex_17.org::v1][Ex 17,1-7]]; [[file:Ps_78.org::v15][Ps 78,15f]]; [[file:Ps_105.org::v41][105,41]]

[fn:4] Vg formuliert 5b etwas anders und fügt als V. 6 hinzu:
indem es ihnen an Getränk mangelte und die Israeliten freuten sich, als
sie Überfluss hatten. Die VV. 6-26 zählt dann Vg als VV. 7-27

[fn:5] [[file:Ps_78.org::v44][Ps 78,44]]; [[file:Ps_105.org::v29][105,29]]

[fn:6] [[file:Ex_1.org::v15][Ex 1,15-22]]

[fn:7] [[v4][11,4]]; [[file:Weish_16.org::v4][16,4]]

[fn:8] [[file:Weish_12.org::v2][12,21f]]

[fn:9] [[file:Dtn_8.org::v5][Dtn 8,5]]; [[file:Spr_3.org::v11][Spr 3,11f]]

[fn:10] [[file:Ex_2.org::v3][Ex 2,3]].[[file:Ex_2.org::v15][15]]; [[file:Ex_5.org::v23][5,23]]; [[file:Ex_20.org::v28][10,28]]

[fn:11] [[file:Weish_12.org::v23][12,23-27]]; [[file:Weish_15.org::v18][15,18]] - [[file:Weish_16.org::v1][16,1]]

[fn:12] Die Ägypter verehrten Krokodile, Schlangen, Eidechsen,
Frösche, Käfer, Fliegen, überhaupt den größten Teil der in Ägypten
heimischen Tierwelt.

[fn:13] [[file:Ri_1.org::v7][Ri 1,7]]

[fn:14] [[file:Gen_1.org::v2][Gen 1,2]]; [[file:Gen_12.org::v9][12,9]]

[fn:15] Den Ausdruck «ungeformter Stoff» übernimmt der
Verfasser aus der griechischen Philosophie, aber nicht im Sinn einer
ungeschaffenen Materie, er bezieht sich vielmehr auf [[file:Gen_1.org::v2][Gen 1,2]].

[fn:16] [[file:Ijob_41.org::v10][Ijob 41,10-14]]

[fn:17] [[file:Ijob_4.org::v9][Ijob 4,9]]; [[file:Sir_1.org::v9][Sir 1,9]]

[fn:18] [[file:2.Chr_20.org::v6][2 Chr 20,6]]

[fn:19] [[file:Jes_40.org::v15][Jes 40,15]]

[fn:20] [[file:Weish_12.org::v18][12,18]]; [[file:Ps_145.org::v9][Ps 145,9]]

[fn:21] [[file:Jona_4.org::v11][Jona 4,11]]
