:PROPERTIES:
:ID:       4bcccfac-6893-4c36-98cd-7111013dc5b0
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch der Weisheit* --
[[file:Weish_1.html][1]] ... [[file:Weish_15.html][15]]
[[file:Weish_16.html][16]] *17* [[file:Weish_18.html][18]]
[[file:Weish_19.html][19]]

--------------

* Weish 17
  :PROPERTIES:
  :CUSTOM_ID: weish-17
  :END:

<<verses>>

<<v1>>
**** Finsternis - Feuersäule: 17,1 - 18,4
     :PROPERTIES:
     :CUSTOM_ID: finsternis---feuersäule-171---184
     :END:
1 Groß und nicht zu ergründen sind deine Entscheide; darum verfiel in
Irrtum, wer sich nicht belehren ließ. ^{[[#fn1][1]][[#fn2][2]]}

<<v2>>
2 Denn die Frevler meinten, das heilige Volk knechten zu können; und
jetzt lagen sie da, Gefangene der Finsternis, Gefesselte einer langen
Nacht, eingeschlossen in den Häusern, von der ewigen Vorsehung verbannt.
^{[[#fn3][3]]}

<<v3>>
3 Sie glaubten, mit ihren geheimen Sünden unter der dunklen Decke der
Vergessenheit verborgen zu sein; da packte sie furchtbares Entsetzen.
Sie wurden durch Trugbilder aufgeschreckt und auseinander gejagt.
^{[[#fn4][4]]}

<<v4>>
4 Auch der geheimste Winkel, in den sie sich flüchteten, konnte sie
nicht vor Furcht bewahren; Schrecken erregendes Getöse umbrauste sie,
und düstere Gespenster mit finsteren Mienen tauchten auf.

<<v5>>
5 Keine Kraft irgendeines Feuers war stark genug, Licht zu bringen;
nicht einmal der strahlende Glanz der Gestirne vermochte es, diese
entsetzliche Nacht zu erhellen.

<<v6>>
6 Nur einen schaurigen Feuerherd, der sich von selbst entzündet hatte,
sahen sie aufglühen; verschwand die Erscheinung, so hielten sie, außer
sich vor Entsetzen, die Dinge, die sie sahen, für noch schlimmer.

<<v7>>
7 Da versagten die Gaukeleien der Zauberkunst und die Probe auf das
prahlerische Wissen fiel schmählich aus. ^{[[#fn5][5]]}

<<v8>>
8 Jene, die immer versprachen, Furcht und Verwirrung von der kranken
Seele zu bannen, krankten nun selber an einer lächerlichen Angst.

<<v9>>
9 Auch wenn nichts Schreckliches sie ängstigte, wurden sie durch
raschelndes Getier und zischelnde Schlangen aufgescheucht und vergingen
vor Furcht. Nicht einmal in die Luft wollten sie blicken, der man doch
nirgends entfliehen kann. ^{[[#fn6][6]]}

<<v10>>
10 Denn die Schlechtigkeit bezeugt selbst ihr feiges Wesen, wenn sie
gestraft wird. Unter dem Druck des Gewissens befürchtet sie immer das
Schlimmste. ^{[[#fn7][7]]}

<<v11>>
11 Furcht ist ja nichts anderes als der Verzicht auf die von der
Vernunft angebotene Hilfe.

<<v12>>
12 Je weniger man solche Hilfe erwartet, umso schlimmer erscheint es,
die Ursache der Qual nicht zu kennen.

<<v13>>
13 In Wahrheit hatte jene Nacht keine Gewalt; aus den Tiefen der
machtlosen Totenwelt war sie heraufgestiegen. Sie aber, die wie sonst
schlafen wollten,

<<v14>>
14 wurden bald durch Schreckgespenster aufgescheucht, bald durch
Mutlosigkeit gelähmt; denn plötzliche und unerwartete Furcht hatte sie
befallen.

<<v15>>
15 So wurde jeder dort, wo er zu Boden sank, ein Gefangener, der in
einen Kerker ohne Eisenfesseln eingeschlossen war. ^{[[#fn8][8]]}

<<v16>>
16 Ob Bauer oder Hirt oder ein Taglöhner, der einsam arbeitete, alle
wurden überrascht und mussten sich dem unentrinnbaren Zwang fügen, alle
wurden durch die gleiche Kette der Finsternis gefesselt.

<<v17>>
17 Das Pfeifen des Windes, der wohlklingende Gesang der Vögel auf den
Zweigen der Bäume, das Rauschen ungestüm strömender Wasser, das wilde
Donnern stürzender Felsen,

<<v18>>
18 das Laufen hüpfender Tiere, die man nicht sehen konnte, das laute
Gebrüll wilder Raubtiere, das aus den Schluchten der Berge
zurückgeworfene Echo: alles und jedes jagte ihnen lähmende Furcht ein.
^{[[#fn9][9]]}

<<v19>>
19 Die ganze Welt stand in strahlendem Licht und alle gingen ungehindert
ihrer Arbeit nach.

<<v20>>
20 Nur über jene breitete sich drückende Nacht aus, Bild der Finsternis,
die sie dereinst aufnehmen sollte. Doch mehr als unter der Finsternis
litten sie unter ihrer eigenen Angst. ^{[[#fn10][10]]}

^{[[#fnm1][1]]} ℘ Röm 11,33; Weish 5,6

^{[[#fnm2][2]]} 1-20: Malt die Qualen des bösen Gewissens aus.

^{[[#fnm3][3]]} ℘ Ex 1,11-14; 10,21-23; Ps 105,28

^{[[#fnm4][4]]} ℘ Ps 64,6f; Weish 18,17

^{[[#fnm5][5]]} ℘ 18,13; Ex 8,14f

^{[[#fnm6][6]]} ℘ Ps 53,6; Spr 28,1

^{[[#fnm7][7]]} ℘ 17,6; Gen 4,14

^{[[#fnm8][8]]} ℘ 17,2; 18,4

^{[[#fnm9][9]]} ℘ 17,9

^{[[#fnm10][10]]} ℘ Ijob 10,21f; Mt 22,13; Jud 13
