:PROPERTIES:
:ID:       3390e4e6-955e-49ae-bbae-a26567bebe5c
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch der Weisheit* --
[[file:Weish_1.html][1]] ... [[file:Weish_6.html][6]]
[[file:Weish_7.html][7]] *8* [[file:Weish_9.html][9]]
[[file:Weish_10.html][10]] ... [[file:Weish_19.html][19]]

--------------

* Weish 8
  :PROPERTIES:
  :CUSTOM_ID: weish-8
  :END:

<<verses>>

<<v1>>
1 Machtvoll entfaltet sie ihre Kraft von einem Ende zum andern /\\
 und durchwaltet voll Güte das All. ^{[[#fn1][1]]}\\
\\

<<v2>>
**** Die Weisheit als Lehrerin der Tugend: 8,2-8
     :PROPERTIES:
     :CUSTOM_ID: die-weisheit-als-lehrerin-der-tugend-82-8
     :END:
2 Sie habe ich geliebt und gesucht von Jugend auf, /\\
 ich suchte sie als Braut heimzuführen /\\
 und fand Gefallen an ihrer Schönheit. ^{[[#fn2][2]][[#fn3][3]]}\\
\\

<<v3>>
3 Im Umgang mit Gott beweist sie ihren Adel, /\\
 der Herr über das All gewann sie lieb.\\
\\

<<v4>>
4 Eingeweiht in das Wissen Gottes, /\\
 bestimmte sie seine Werke. ^{[[#fn4][4]]}\\
\\

<<v5>>
5 Ist Reichtum begehrenswerter Besitz im Leben, /\\
 was ist dann reicher als die Weisheit, die in allem wirkt?
^{[[#fn5][5]]}\\
\\

<<v6>>
6 Wenn Klugheit wirksam ist, /\\
 wer in aller Welt ist ein größerer Meister als sie?\\
\\

<<v7>>
7 Wenn jemand Gerechtigkeit liebt, /\\
 in ihren Mühen findet er die Tugenden. Denn sie lehrt Maß und Klugheit,
/\\
 Gerechtigkeit und Tapferkeit, /\\
 die Tugenden, die im Leben der Menschen nützlicher sind als alles
andere.\\
\\

<<v8>>
8 Wenn jemand nach reicher Erfahrung strebt: /\\
 sie kennt das Vergangene und errät das Kommende, sie versteht, die
Worte schön zu formen und Rätselhaftes zu deuten; /\\
 sie weiß im Voraus Zeichen und Wunder /\\
 und kennt den Ausgang von Perioden und Zeiten. ^{[[#fn6][6]]}\\
\\

<<v9>>
**** Die Weisheit als Lebensgefährtin: 8,9-18
     :PROPERTIES:
     :CUSTOM_ID: die-weisheit-als-lebensgefährtin-89-18
     :END:
9 So beschloss ich, sie als Lebensgefährtin heimzuführen; /\\
 denn ich wusste, dass sie mir guten Rat gibt /\\
 und Trost in Sorge und Leid. ^{[[#fn7][7]]}\\
\\

<<v10>>
10 Mit ihr werde ich Ruhm beim Volke haben /\\
 und trotz meiner Jugend vom Alter geehrt sein.\\
\\

<<v11>>
11 Ich werde als scharfsinniger Richter gelten /\\
 und in den Augen der Mächtigen Staunen erregen.\\
\\

<<v12>>
12 Schweige ich, so warten sie in Spannung, /\\
 spreche ich, so merken sie auf, /\\
 rede ich länger, so legen sie die Hand auf den Mund. ^{[[#fn8][8]]}\\
\\

<<v13>>
13 Mit ihr werde ich Unsterblichkeit erlangen /\\
 und ewigen Ruhm bei der Nachwelt hinterlassen.\\
\\

<<v14>>
14 Völker werde ich sorgsam leiten /\\
 und Nationen werden mir untertan sein. ^{[[#fn9][9]]}\\
\\

<<v15>>
15 Schreckliche Tyrannen werden mich fürchten, wenn sie von mir hören;
/\\
 in der Volksversammlung werde ich mich als tüchtig und im Krieg als
tapfer erweisen.\\
\\

<<v16>>
16 Komme ich nach Hause, /\\
 dann werde ich bei ihr ausruhen; denn der Umgang mit ihr hat nichts
Bitteres, /\\
 das Leben mit ihr kennt keinen Schmerz, /\\
 sondern nur Frohsinn und Freude. ^{[[#fn10][10]]}\\
\\

<<v17>>
17 Als ich dies bei mir überlegte und in meinem Herzen erwog, /\\
 dass das Leben mit der Weisheit Unsterblichkeit bringt,\\
\\

<<v18>>
18 die Freundschaft mit ihr reine Freude /\\
 und die Mühen ihrer Hände unerschöpflichen Reichtum, dass stete
Gemeinschaft mit ihr Klugheit bringt /\\
 und das Zwiegespräch mit ihr Ruhm -, /\\
 da ging ich auf die Suche nach ihr, um sie heimzuführen.
^{[[#fn11][11]]}\\
\\

<<v19>>
** Salomos großes Gebet: Das Walten der Weisheit in der Geschichte:
8,19 - 19,22
   :PROPERTIES:
   :CUSTOM_ID: salomos-großes-gebet-das-walten-der-weisheit-in-der-geschichte-819---1922
   :END:
*** Das Gebet um Weisheit: 8,19 - 9,19
    :PROPERTIES:
    :CUSTOM_ID: das-gebet-um-weisheit-819---919
    :END:
**** Einleitung: 8,19-21
     :PROPERTIES:
     :CUSTOM_ID: einleitung-819-21
     :END:
19 Ich war ein begabtes Kind und hatte eine gute Seele erhalten,

<<v20>>
20 oder vielmehr: gut, wie ich war, kam ich in einen unverdorbenen Leib.

<<v21>>
21 Ich erkannte aber, dass ich die Weisheit nur als Geschenk Gottes
erhalten könne - und schon hier war es die Klugheit, die mich erkennen
ließ, wessen Gnadengeschenk sie ist. Daher wandte ich mich an den Herrn
und sprach zu ihm aus ganzem Herzen: ^{[[#fn12][12]]}\\
\\

^{[[#fnm1][1]]} ℘ 1,7; 12,18; 15,1

^{[[#fnm2][2]]} ℘ Sir 15,2

^{[[#fnm3][3]]} 2-8: Salomo hat die Weisheit von Jugend auf geliebt,
weil sie mit Gott in innigster Verbindung steht, alle Güter gewährt, die
vier Kardinaltugenden lehrt, die alle anderen in sich enthalten, und so
zu einem rechtschaffenen Leben anleitet.

^{[[#fnm4][4]]} ℘ 9,4

^{[[#fnm5][5]]} ℘ 7,22; (5-7) 7,11-14

^{[[#fnm6][6]]} ℘ Sir 42,19; Spr 1,6

^{[[#fnm7][7]]} ℘ Spr 8,14

^{[[#fnm8][8]]} ℘ Ijob 29,21-23; 29,9

^{[[#fnm9][9]]} ℘ Spr 8,15f

^{[[#fnm10][10]]} ℘ Sir 15,6

^{[[#fnm11][11]]} ℘ Spr 8,18

^{[[#fnm12][12]]} ℘ Spr 2,6; Weish 7,7
