#+TITLE: Weish 4 
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+DATE: [2025-08-21 Do 15:27]
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Weish 4.html

* Weish 4

<<verses>>

<<v1>>
1 Besser ist Kinderlosigkeit mit Tugend; unsterblich ist ihr Ruhm, /\\
 sie steht in Ehren bei Gott und bei den Menschen.\\
\\

<<v2>>
2 Ist sie zugegen, ahmt man sie nach; /\\
 ist sie entschwunden, sehnt man sie herbei. /\\
 In der Ewigkeit triumphiert sie, /\\
 geschmückt mit dem Kranz, /\\
 Siegerin im Wettstreit um einen edlen Preis. [fn:1]\\
\\

<<v3>>
3 Doch die große Kinderschar der Frevler bringt keinen Nutzen; /\\
 sie ist ein unechtes Gewächs, /\\
 treibt keine Wurzeln in die Tiefe /\\
 und fasst keinen sicheren Grund. [fn:2]\\
\\

<<v4>>
4 Breitet es auch eine Zeit lang üppig seine Zweige aus, /\\
 so wird es doch vom Wind hin und her geschüttelt /\\
 und von der Gewalt der Stürme entwurzelt.\\
\\

<<v5>>
5 Die Äste, die noch schwach sind, werden geknickt; /\\
 ihre Frucht ist unbrauchbar, unreif und ungenießbar, /\\
 zu gar nichts geeignet.\\
\\

<<v6>>
6 Denn die Kinder eines sündigen Beischlafs /\\
 treten im Gericht als Zeugen auf /\\
 für die Schlechtigkeit ihrer Eltern.\\
\\

<<v7>>
* Der frühe Heimgang des Gerechten und das lange Leben der Frevler: 4,7-19

7 Der Gerechte aber, kommt auch sein Ende früh, /\\
 geht in Gottes Ruhe ein. [fn:3]\\
\\

<<v8>>
8 Denn ehrenvolles Alter besteht nicht in einem langen Leben /\\
 und wird nicht an der Zahl der Jahre gemessen.\\
\\

<<v9>>
9 Mehr als graues Haar bedeutet für die Menschen die Klugheit /\\
 und mehr als Greisenalter wiegt ein Leben ohne Tadel.\\
\\

<<v10>>
10 Er gefiel Gott und wurde von ihm geliebt; /\\
 da er mitten unter Sündern lebte, wurde er entrückt. [fn:4]\\
\\

<<v11>>
11 Er wurde weggenommen, /\\
 damit nicht Schlechtigkeit seine Einsicht verkehrte /\\
 und Arglist seine Seele täuschte.\\
\\

<<v12>>
12 Denn der Reiz des Bösen verdunkelt das Gute /\\
 und der Taumel der Begierde verdirbt den arglosen Sinn.\\
\\

<<v13>>
13 Früh vollendet, hat der Gerechte doch ein volles Leben gehabt;\\
\\

<<v14>>
14 da seine Seele dem Herrn gefiel, /\\
 enteilte sie aus der Mitte des Bösen. /\\
 Die Leute sahen es, ohne es zu verstehen; /\\
 sie nahmen es sich nicht zu Herzen, [fn:5]\\
\\

<<v15>>
15 dass Gnade und Erbarmen seinen Auserwählten zuteil wird, /\\
 Belohnung seinen Heiligen. [fn:6]\\
\\

<<v16>>
16 Der Gerechte, der entschlafen ist, /\\
 verurteilt die Frevler, die noch leben, /\\
 die früh vollendete Jugend /\\
 das hohe Alter des Ungerechten.\\
\\

<<v17>>
17 Die Frevler sehen das Ende des Weisen, /\\
 verstehen aber nicht, was der Herr mit ihm wollte /\\
 und warum er ihn in Sicherheit brachte.\\
\\

<<v18>>
18 Sie sehen es und gehen darüber hinweg; /\\
 doch der Herr lacht über sie. [fn:7]\\
\\

<<v19>>
19 Dann werden sie verachtete Leichen sein, /\\
 ewiger Spott bei den Toten. /\\
 Sie werden verstummen, /\\
 wenn er sie kopfüber hinabstürzt /\\
 und aus ihren Grundfesten reißt. /\\
 Sie werden völlig vernichtet und erleiden Qualen; /\\
 die Erinnerung an sie verschwindet. [fn:8]\\
\\

<<v20>>
* Die Bösen und die Guten im Endgericht: 4,20 - 5,23

20 Zitternd kommen sie zum Gericht über ihre Sünden; /\\
 ihre Vergehen treten ihnen entgegen und überführen sie. [fn:9]\\
\\


* Footnotes

[fn:1] [[file:Weish_5.org::v16][5,16]]

[fn:2] [[file:Sir_23.org::v25][Sir 23,25]]

[fn:3] [[file:Jes_57.org::v2][Jes 57,2]]

[fn:4] [[file:Gen_5.org::v24][Gen 5,24]]; [[file:Sir_44.org::v16][Sir 44,16]]; [[file:~/Documents/notes/Bibel/nt/Hebr_11.org::v5][Hebr 11,5]]

[fn:5] [[file:Jes_57.org::v1][Jes 57,1]]

[fn:6] [[file:Weish_3.org::v9][3,9]]

[fn:7] [[file:Ps_2.org::v4][Ps 2,4]]

[fn:8] [[file:Jes_14.org::v16][Jes 14,16-19]]; [[file:Ijob_18.org::v17][Ijob 18,17]]

[fn:9] [[v20][20]]-[[file:Weish_5.org::v23][5,23]]: Gegenstück zu [[file:Weish_1.org::v16][1,16]] - [[file:Weish_2.org::v24][2,24]]: Im Endgericht müssen
die Sünder in Gegenwart des von ihnen verachteten und verfolgten
Gerechten ihren Irrtum und ihr verfehltes Leben beklagen.
