:PROPERTIES:
:ID:       6d57d0c9-7132-48a9-b42d-8a0e5e933ef0
:END:
<<navbar>>
[[../index.html][Einheitsübersetzung der Heiligen Schrift (1980)
[Quadro-Bibel 5.0]]] -- *Das Buch Zefanja* -- *1* [[file:Zef_2.html][2]]
[[file:Zef_3.html][3]]

--------------

* Zef 1
  :PROPERTIES:
  :CUSTOM_ID: zef-1
  :END:

Das relativ kleine Buch weist drei Teile auf: Strafankündigung gegen
Juda und gegen die anderen Völker (1,2 - 2,15); Strafankündigung gegen
Jerusalem (3,1-8); Ankündigung der Bekehrung der Völker und des Heils
für Jerusalem (3,9-20). Das Buch lässt eine exilisch-nachexilische
Bearbeitung erkennen. Der Schlussabschnitt 3,16-20 ist sicher erst
längere Zeit nach dem Exil angefügt worden. Die Annahme einer bereits
früheren Überarbeitung legen 1,18; 2,7.9f; 3,8f nahe.\\
\\
Die Überschrift gibt als Zeit Zefanjas die Epoche des Königs Joschija
(641-609 v. Chr.) an. In dessen frühe Regierungsjahre passen auch die
als echt geltenden Texte. Während der langen Regierungszeit des Gott
untreuen Manasse (699-643 v. Chr.) trat ein religiöser und sozialer
Verfall im Südreich ein, der Gegenkräfte auf den Plan rief, die den
jungen Joschija zu einem reformwilligen König zu machen vermochten (ab
627 oder 622 v. Chr.). Mit ihnen muss Zefanja um 630 v. Chr. als Prophet
zusammengearbeitet haben.\\
\\
Von Zefanja ist außer den Angaben in 1,1 nichts Weiteres bekannt. Warum
seine Abstammung bis zum Urgroßvater zurück angegeben wird, bleibt
unklar. Er nimmt die Botschaft vom »Tag des Herrn« von Amos (Am 5,16-20)
und Jesaja (Jes 2,6-22) auf und gestaltet jenen »Tag« zu einem
universalen Ereignis aus (1,14-18; 2,1-3). Die Sequenz der Totenmesse,
das »Dies irae«, ist hauptsächlich von Zef 1,14-18 inspiriert. In seiner
Grundforderung nach Gerechtigkeit und Demut stimmt Zefanja ebenfalls mit
Amos und Jesaja überein; demgemäß verkündigt er das ideale Israel der
Zukunft, den »heiligen Rest«, als »demütiges und armes Volk, das seine
Zuflucht sucht beim Namen des Herrn« (3,12). Diese Stelle schlägt eine
Brücke zum Neuen Testament.\\
\\

<<verses>>

<<v1>>
** Überschrift: 1,1
   :PROPERTIES:
   :CUSTOM_ID: überschrift-11
   :END:
1 Wort des Herrn, das an Zefanja, den Sohn Kuschis, des Sohnes Gedaljas,
des Sohnes Amarjas, des Sohnes Hiskijas, erging in der Zeit, als
Joschija, der Sohn Amons, König von Juda war.\\
\\

<<v2>>
** Das Gericht über Juda und die Völker: 1,2 - 3,8
   :PROPERTIES:
   :CUSTOM_ID: das-gericht-über-juda-und-die-völker-12---38
   :END:
**** Das Gericht über Juda: 1,2-13
     :PROPERTIES:
     :CUSTOM_ID: das-gericht-über-juda-12-13
     :END:
2 Ich raffe alles vom Erdboden weg, /\\
 ich raffe es weg - Spruch des Herrn.\\
\\

<<v3>>
3 Mensch und Vieh raffe ich weg, /\\
 die Vögel des Himmels raffe ich weg und die Fische im Meer /\\
 [nämlich alles, was die Frevler zu Fall gebracht hat,] und ich rotte
die Menschen auf der Erde aus - /\\
 Spruch des Herrn.\\
\\

<<v4>>
4 Ich strecke meine Hand gegen Juda aus /\\
 und gegen alle Einwohner Jerusalems und ich rotte an diesem Ort die
Reste des Baalsdienstes aus, /\\
 samt den Namen der Götzenpriester, ^{[[#fn1][1]]}\\
\\

<<v5>>
5 alle, die sich auf den Dächern niederwerfen /\\
 vor dem Heer des Himmels, auch alle, die sich vor dem Herrn
niederwerfen, /\\
 zugleich aber bei ihrem Moloch schwören, ^{[[#fn2][2]][[#fn3][3]]}\\
\\

<<v6>>
6 und alle, die dem Herrn den Rücken kehren, /\\
 die ihn nicht suchen und nicht nach ihm fragen.\\
\\

<<v7>>
7 Schweigt vor Gott, dem Herrn! /\\
 Denn der Tag des Herrn ist nahe. Ja, der Herr hat ein Schlachtopfer
vorbereitet, /\\
 er hat die eingeladenen Gäste schon (dem Tod) geweiht. ^{[[#fn4][4]]}\\
\\

<<v8>>
8 Am Tag des Schlachtopfers des Herrn /\\
 rechne ich ab mit den großen Herren und den Königssöhnen /\\
 und allen, die fremdländische Kleider tragen;\\
\\

<<v9>>
9 an jenem Tag rechne ich ab mit jedem, /\\
 der über die Schwelle springt, mit allen, die das Haus ihres Herrn /\\
 mit Betrug und Gewalt anfüllen. ^{[[#fn5][5]]}\\
\\

<<v10>>
10 An jenem Tag - Spruch des Herrn - /\\
 hört man vom Fischtor her Geschrei und aus der Neustadt lautes Jammern
/\\
 und von den Hügeln her großes Getöse.\\
\\

<<v11>>
11 Jammert, ihr Bewohner der Senke! /\\
 Denn das ganze Krämervolk verstummt, /\\
 alle Geldwechsler sind ausgerottet. ^{[[#fn6][6]]}\\
\\

<<v12>>
12 In jener Zeit durchsuche ich Jerusalem mit der Laterne /\\
 und rechne ab mit den Herren, die dick geworden sind auf ihrer Hefe und
denken: /\\
 Der Herr tut weder Gutes noch Böses. ^{[[#fn7][7]][[#fn8][8]]}\\
\\

<<v13>>
13 Darum werden ihre Reichtümer geraubt /\\
 und ihre Häuser verwüstet. Sie werden Häuser bauen, aber nicht darin
wohnen; /\\
 sie werden Weinberge anlegen, aber den Wein nicht trinken.
^{[[#fn9][9]]}\\
\\

<<v14>>
**** Der Tag des Herrn: 1,14-18
     :PROPERTIES:
     :CUSTOM_ID: der-tag-des-herrn-114-18
     :END:
14 Der Tag des Herrn ist nahe, der gewaltige Tag, /\\
 er ist nahe, schnell kommt er herbei. Horch, der Tag des Herrn ist
bitter, /\\
 da schreit sogar der Kriegsheld auf. ^{[[#fn10][10]]}\\
\\

<<v15>>
15 Ein Tag des Zorns ist jener Tag, /\\
 ein Tag der Not und Bedrängnis, ein Tag des Krachens und Berstens, /\\
 ein Tag des Dunkels und der Finsternis, /\\
 ein Tag der Wolken und der schwarzen Nacht, ^{[[#fn11][11]]}\\
\\

<<v16>>
16 ein Tag des Widderhorns und des Kriegsgeschreis in den befestigten
Städten /\\
 und auf den hohen Zinnen.\\
\\

<<v17>>
17 Da jage ich den Menschen Angst ein, /\\
 sodass sie wie blind umherlaufen; /\\
 denn sie haben sich gegen den Herrn versündigt. Ihr Blut wird
hingeschüttet wie Schutt /\\
 und ihr fettes Mark wie Kot. ^{[[#fn12][12]]}\\
\\

<<v18>>
18 Weder ihr Silber noch ihr Gold kann sie retten /\\
 am Tag des Zornes des Herrn. Vom Feuer seines leidenschaftlichen Eifers
/\\
 wird die ganze Erde verzehrt. Denn er bereitet allen Bewohnern der Erde
ein Ende, /\\
 ein schreckliches Ende. ^{[[#fn13][13]]}\\
\\

^{[[#fnm1][1]]} ℘ 2 Kön 23,4-20

^{[[#fnm2][2]]} ℘ Dtn 4,19; 2 Kön 21,3-5; 1 Kön 11,7.33

^{[[#fnm3][3]]} Zu Moloch vgl. Lev 20,2 und die dortige Anmerkung; 2 Kön
16,3; 17,17; 21,6.

^{[[#fnm4][4]]} ℘ Hab 2,20; Offb 19,17f

^{[[#fnm5][5]]} der über die Schwelle springt: Übersetzung unsicher.
Gemeint ist wohl ein heidnischer Kultbrauch. Vielleicht ist die Rede von
Höflingen am Stufenthron des Königs oder von Kultdienern am Stufenthron
eines Götterbildes.

^{[[#fnm6][6]]} Senke: das Stadtviertel im Süden der Neustadt von
Jerusalem.

^{[[#fnm7][7]]} ℘ Jer 48,11; Ps 10,4; Jer 5,12

^{[[#fnm8][8]]} Wenn der junge Wein nicht abgelassen wird, verdirbt er
auf seiner Hefe.

^{[[#fnm9][9]]} ℘ Dtn 28,30-33; Am 5,11

^{[[#fnm10][10]]} ℘ (14-18) Am 5,18-20

^{[[#fnm11][11]]} ℘ Joël 2,2

^{[[#fnm12][12]]} ℘ Joël 2,1; Jer 9,21

^{[[#fnm13][13]]} ℘ Ez 7,19
