#+title:      Webpages
#+date:       [2023-12-18 Mo 08:15]
#+filetags:   :capture:
#+identifier: 20231218T081552
#+STARTUP: showall
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Webpages.html

* Wenn das Volk gefährlich wird -
:PROPERTIES:
:CREATED: [2025-02-15 Sa 20:52]
:SOURCE: https://multipolar-magazin.de/artikel/wenn-das-volk-gefaehrlich-wird
:END:

When quoting a passage from another document, it is customary to format this as a paragraph that is indented on both the left and the right margin. You can include quotations in Org mode documents like this:

#+BEGIN_QUOTE
/Ein Journalist warnt in einem neuen Buch davor, „falsch“ zu wählen. Mark Schieritz, Vize-Ressortchef für Politik bei der Hamburger ZEIT, fragt ganz offen, ob viele Bürger nicht vielleicht „zu dumm für die Demokratie“ seien. Die „liberale Ordnung“ solle deshalb vor solch irregeleitetem Volkswillen „geschützt“ werden. Walter van Rossum hat das Buch für Multipolar gelesen./
#+END_QUOTE

* Aporetic fonts version 1.1.0 | Protesilaos Stavrou
:PROPERTIES:
:CREATED: [2025-02-15 Sa 22:02]
:SOURCE: https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/
:END:

Diese Schriftart ist so ziemlich die schönste, die es für Emacs gibt. Entworfen von Protesilaos Stavrou, dem besten und eifrigsten Emacs Entwickler, den es gibt. Er ist nicht nur ein großartiger Lehrer für Emacs, sondern auch ein tiefsinniger Philosoph - in der Tradition seiner griechischen Vorfahren - er auf Zypern (im griechischen Teil) lebt.

Aus urheberrechtlichen Gründen musste er seine Schriftart umbenennen. Es gab auch kleine Änderungen: t, m, und 0.

#+BEGIN_QUOTE
/Customised build of the Iosevka typeface, with a consistent rounded style and overrides for almost all individual glyphs in both upright (roman) and slanted (italic) variants. This is the successor to my now-discontinued “Iosevka Comfy” fonts./
#+END_QUOTE

* Aporetic fonts version 1.1.0 | Protesilaos Stavrou
:PROPERTIES:
:CREATED: [2025-02-15 Sa 22:17]
:SOURCE: https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/
:END:

This release includes two stylistic corrections that pertain to Aporetic Serif and Aporetic Serif Mono. Customised build of the Iosevka typeface, with a consistent rounded style and overrides for almost all individual glyphs in both upright (roman) and slanted (italic) variants. This is the successor to my now-discontinued “Iosevka Comfy” fonts.

#+BEGIN_QUOTE
/The second change is to the letter m in both upright and slanted forms. Before, the m would have a top left serif, as intended, but not a bottom right tail. The tail is a feature of other glyphs that need to have such a style, like a, h, n, u: it imposes a proper rhythm together with the rest of the serif details. Now the m has its missing bottom right tail, making everything consistent./

(Zitat von [[https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/][Aporetic fonts version 1.1.0 | Protesilaos Stavrou]], [2025-02-15 Sa 22:17])
#+END_QUOTE

* Aporetic fonts version 1.1.0 | Protesilaos Stavrou
:PROPERTIES:
:CREATED: [2025-02-15 Sa 22:25]
:SOURCE: https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/
:END:
- SOURCE: https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/
- CREATED: [2025-02-15 Sa 22:25]

The first change is to the slanted (italic) form of the letter t. Before, it was mistakenly set to have a curved, upward-facing bottom stroke, which would clash with the flat bottom of i and l. Now the slanted t has a flat bottom as intended. The upright (roman) variants are always flat in this regard.

#+BEGIN_QUOTE
/Customised build of the Iosevka typeface, with a consistent rounded style and overrides for almost all individual glyphs in both upright (roman) and slanted (italic) variants. This is the successor to my now-discontinued “Iosevka Comfy” fonts./

(Zitat von [[https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/][Aporetic fonts version 1.1.0 | Protesilaos Stavrou]], [2025-02-15 Sa 22:25])
#+END_QUOTE

* Aporetic fonts version 1.1.0 | Protesilaos Stavrou
:PROPERTIES:
:CREATED: [2025-02-15 Sa 22:38]
:SOURCE: https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/
:END:
- SOURCE: https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/
- CREATED: [2025-02-15 Sa 22:38]

This release includes two stylistic corrections that pertain to Aporetic Serif and Aporetic Serif Mono.

#+BEGIN_QUOTE
/Customised build of the Iosevka typeface, with a consistent rounded style and overrides for almost all individual glyphs in both upright (roman) and slanted (italic) variants. This is the successor to my now-discontinued “Iosevka Comfy” fonts./

(Zitat von [[https://protesilaos.com/codelog/2025-02-12-aporetic-fonts-version-1-1-0/][Aporetic fonts version 1.1.0 | Protesilaos Stavrou]], [2025-02-15 Sa 22:38])
#+END_QUOTE

* Wenn das Volk gefährlich wird -
:PROPERTIES:
:CREATED: [2025-02-15 Sa 23:00]
:SOURCE: https://multipolar-magazin.de/artikel/wenn-das-volk-gefaehrlich-wird
:END:
- SOURCE: https://multipolar-magazin.de/artikel/wenn-das-volk-gefaehrlich-wird
- CREATED: [2025-02-15 Sa 23:00]

Im US-Präsidentschaftswahlkampf 2016 hielt Hillary Clinton eine Rede vor Verfechtern von Homosexuellenrechten. Dabei nannte sie „die Hälfte der Anhänger von Trump (…) rassistisch, schwulenfeindlich, fremdenfeindlich, islamfeindlich“. Mark Schieritz zufolge hätten diese Worte für große Turbulenzen in der Öffentlichkeit gesorgt und „die Dynamik des Wahlkampfs verändert“. Die Rede sei in die Geschichte eingegangen. Ihretwegen habe Clinton die Wahlen verloren. Tatsächlich ist von dieser Rede kaum mehr eine Spur zu finden, mit Sicherheit spielte sie beim Ausgang der Wahlen so gut wie keine Rolle. Allein Donald Trump hoffte, dass diese Beleidigungen Hillary Stimmen kosten könnten. 

#+BEGIN_QUOTE
/Ein Journalist warnt in einem neuen Buch davor, „falsch“ zu wählen. Mark Schieritz, Vize-Ressortchef für Politik bei der Hamburger ZEIT, fragt ganz offen, ob viele Bürger nicht vielleicht „zu dumm für die Demokratie“ seien. Die „liberale Ordnung“ solle deshalb vor solch irregeleitetem Volkswillen „geschützt“ werden. Walter van Rossum hat das Buch für Multipolar gelesen./

(Zitat von [[https://multipolar-magazin.de/artikel/wenn-das-volk-gefaehrlich-wird][Wenn das Volk gefährlich wird -]], [2025-02-15 Sa 23:00])
#+END_QUOTE

* Kanada-Wahl: Trudeau-Nachfolger Carney siegt - news.ORF.at
:PROPERTIES:
:CREATED: [2025-04-29 Di 10:47]
:SOURCE: https://orf.at/stories/3391965/
:END:

* Nach juristischer Schlappe: Prinz Harry will Versöhnung mit Familie - news.ORF.at
:PROPERTIES:
:CREATED: [2025-05-03 Sa 09:40]
:SOURCE: https://orf.at/stories/3392332/
:END:

* Nach juristischer Schlappe: Prinz Harry will Versöhnung mit Familie - news.ORF.at
:PROPERTIES:
:CREATED: [2025-05-03 Sa 10:18]
:SOURCE: https://orf.at/stories/3392332/
:END:

* Nach juristischer Schlappe: Prinz Harry will Versöhnung mit Familie - news.ORF.at
:PROPERTIES:
:CREATED: [2025-05-03 Sa 11:09]
:SOURCE: https://orf.at/stories/3392332/
:END:

* Fußball: Last-Minute-Tor crasht Bayerns Meisterfeier - sport.ORF.at
:PROPERTIES:
:CREATED: [2025-05-03 Sa 20:01]
:SOURCE: https://sport.orf.at/stories/3140905/
:END:
- SOURCE: https://sport.orf.at/stories/3140905/
- CREATED: [2025-05-03 Sa 20:01]

Juhuu, das klappt: ich habe diese Notiz vom =nyxt= browser, bookmarklets-mode ... gemacht. Das =org-capture-template= werde ich noch anpassen (z.B. habe ich "created" und "source" Angaben zweimal. Ist wohl übertrieben.)

#+BEGIN_QUOTE
/Bayern München hat seinen 34. Meistertitel praktisch sicher, muss die Feier nach einem Last-Minute-Schock aber noch etwas verschieben. Die Münchner drehten das Spiel bei RB Leipzig nach einem 0:2-Rückstand bis kurz vor Schluss in ein 3:2, ehe Yussuf Poulsen (94.) mit seinem Ausgleichstreffer in der Nachspielzeit zum großen Partycrasher avancierte. Für den ganz sicheren Titel hätte Bayern das Spiel gewinnen müssen./

(Zitat von [[https://sport.orf.at/stories/3140905/][Fußball: Last-Minute-Tor crasht Bayerns Meisterfeier - sport.ORF.at]], [2025-05-03 Sa 20:01])
#+END_QUOTE

* Medienkritik: Mehr als „trotziger Idealismus“ -
:PROPERTIES:
:CREATED: [2025-05-06 Di 12:06]
:SOURCE: https://multipolar-magazin.de/artikel/medienkritik-idealismus
:END:

* Medienkritik: Mehr als „trotziger Idealismus“ -
:PROPERTIES:
:CREATED: [2025-05-06 Di 12:06]
:SOURCE: https://multipolar-magazin.de/artikel/medienkritik-idealismus
:END:
- SOURCE: https://multipolar-magazin.de/artikel/medienkritik-idealismus
- CREATED: [2025-05-06 Di 12:06]



#+BEGIN_QUOTE
/Kritik an den etablierten Medien ist im Jahr 2025 fast schon Mainstream und längst in den Bestsellerlisten angekommen. Doch von welchem Standpunkt aus wird kritisiert? Eine Betrachtung anhand dreier aktueller Bücher./

(Zitat von [[https://multipolar-magazin.de/artikel/medienkritik-idealismus][Medienkritik: Mehr als „trotziger Idealismus“ -]], [2025-05-06 Di 12:06])
#+END_QUOTE

* Was sind die 7 Gaben des Heiligen Geistes? - YOUCAT
:PROPERTIES:
:CREATED: [2025-05-27 Di 08:12]
:SOURCE: https://youcat.org/de/credopedia/gaben-des-heiligen-geistes/
:CUSTOM_ID: h:c473c627-98a1-4444-9b2e-9c7db2805898
:END:


#+BEGIN_QUOTE
/Die Sieben Gaben des Heiligen Geistes

Der Heilige Geist, der den Jüngern von Jesus versprochen wurde, ist im Neuen Testament mit drei Wort präsent: dynamis (= Allmacht Gottes), energeia (= wirksame Kraft), pneuma (= lebendiger Atem). Im Heiligen Geist ist uns die Fülle der Gnade geschenkt. Die biblische Rede von den „Sieben Gaben des Heiligen Geistes“ präzisiert das, was durch das Geschenk des Heiligen Geistes im einzelnen Gläubigen an Begabungen sichtbar werden kann und möglich wird. Man spricht von Charisma oder Charismen (altgriech. = aus Güte geschenkte Gabe)./

(Zitat von [[https://youcat.org/de/credopedia/gaben-des-heiligen-geistes/][Was sind die 7 Gaben des Heiligen Geistes? - YOUCAT]], [2025-05-27 Di 08:12])
#+END_QUOTE

* Club-WM: Salzburg punktet auch gegen al-Hilal - sport.ORF.at
:PROPERTIES:
:CREATED: [2025-06-23 Mo 10:27]
:SOURCE: https://sport.orf.at/stories/3142689/
:END:
- SOURCE: https://sport.orf.at/stories/3142689/
- CREATED: [2025-06-23 Mo 10:27]



#+BEGIN_QUOTE
//

(Zitat von [[https://sport.orf.at/stories/3142689/][Club-WM: Salzburg punktet auch gegen al-Hilal - sport.ORF.at]], [2025-06-23 Mo 10:27])
#+END_QUOTE

* Club-WM: Salzburg punktet auch gegen al-Hilal - sport.ORF.at
:PROPERTIES:
:CREATED: [2025-06-23 Mo 10:27]
:SOURCE: https://sport.orf.at/stories/3142689/
:END:

* „Crystal-Meth-Pfarrer“: Drei Schuldsprüche - noe.ORF.at
:PROPERTIES:
:CREATED: [2025-10-23 Do 14:45]
:SOURCE: https://noe.orf.at/stories/3327034/
:END:

* [Stable Update] 2025-12-15 - Kernels, NVIDIA, Plasma, Cosmic, Firefox - Announcements / Stable Updates - Manjaro Linux Forum
:PROPERTIES:
:CREATED: [2025-12-19 Fr 08:50]
:SOURCE: https://forum.manjaro.org/t/stable-update-2025-12-15-kernels-nvidia-plasma-cosmic-firefox/183888/109
:END:

Am Desktop PC (Xfce, Nvidia) flackert die Taskbar, =conky=, manche Fenster. Auch andere User begegnen ähnlichen Problemen. Hier zwei Vroschläge:

#+BEGIN_QUOTE
/Had problems like others with 580 nvidia drivers (flickering).

However going back to 570xx with mhwd resulted in problems and after reboot I was only able to use command line with ctrl+alt+f6.

In the end was able to solve the problem and everything works with: “sudo pacman -S linux66-nvidia-570xx”/

(Zitat von [[https://forum.manjaro.org/t/stable-update-2025-12-15-kernels-nvidia-plasma-cosmic-firefox/183888/109][[Stable Update] 2025-12-15 - Kernels, NVIDIA, Plasma, Cosmic, Firefox - Announcements / Stable Updates - Manjaro Linux Forum]], [2025-12-19 Fr 08:50])
#+END_QUOTE

#+BEGIN_QUOTE
After the this stable update, opening or closing windows causes the window and panel to flicker or disappear. I’m using a GeForce RTX 3060 laptop GPU on Manjaro Xfce 4 / X11. Temporary work‑arounds which works for me:

    Downgrade the driver with mhwd to the 575xx version.
    Or go to Window Manager Tweaks > Compositor and disable Enable display compositing.
#+END_QUOTE

* Fallacy of Exact Words – Questions and Answers
:PROPERTIES:
:CREATED: [2026-04-29 Mi 08:26]
:SOURCE: https://www.faithbrowser.com/fallacy-of-exact-words/
:CUSTOM_ID: h:8f53699a-90a1-4f0b-a38b-71aadd5725bc
:END:



#+BEGIN_QUOTE
/Abdullah: Hey buddy, are you married?

Joe: Yeah, that’s my wife over there, with my kids.

Abdullah: Are you married?

Joe: Errr…I just told you.

Abdullah: No. You didn’t say, “I AM MARRIED” in those exact unequivocal unambiguous words.

Mr. Abdullah typifies the majority of Muslims today who are taught to demand exact words, especially in the context of the divinity of Jesus.

Here is the challenge that all Muslim apologists are trained to recite: “Show me a single unequivocal, unambiguous statement in the complete Bible where Jesus himself said, ‘I am God’ or ‘Worship Me.'”

I call it The Fallacy of Exact Words.

There is nowhere in the Bible where Jesus said unequivocally and unambiguously, “Hi. My name is Jesus.” Can we conclude that this means his name is not Jesus?

He also never said, “I am the Messiah.” Again, does this mean he is not the Messiah since he did not say it in those exact words?

This is how weak and shallow this faulty challenge is. /

(Zitat von [[https://www.faithbrowser.com/fallacy-of-exact-words/][Fallacy of Exact Words – Questions and Answers]], [2026-04-29 Mi 08:26])
#+END_QUOTE

* Die Journalisten sind gescheitert - du bist der Beweis - YouTube
:PROPERTIES:
:CREATED: [2026-08-20 Do 12:07]
:SOURCE: https://www.youtube.com/watch?v=gqjuv8eKsCU&t=1491s
:END:



#+BEGIN_QUOTE
//

(Zitat von [[https://www.youtube.com/watch?v=gqjuv8eKsCU&t=1491s][Die Journalisten sind gescheitert - du bist der Beweis - YouTube]], [2026-08-20 Do 12:07])
#+END_QUOTE

* keith haring bild von drei menschen zwei greifen durch ein loch im bauch des mittleren - Google Suche
:PROPERTIES:
:CREATED: [2026-09-25 Fr 08:33]
:SOURCE: https://www.google.com/search?hl=de&q=keith+haring+bild+von+drei+menschen+zwei+greifen+durch+ein+loch+im+bauch+des+mittleren&udm=50&fbs=ABfTbFUyxjQn9bne4DuflY2dNqqKupTsDwp6RXwpQFJxPysO9IZ-OcP6xq64A4yNP8lBdpbV1NcW6cxeRROTFTHTKwOqDjWNGJkd7gEr3KwTkPk0UoDBnxQ3J5HkgKbFwYmwvJAkynUczpEbvmxO-Tqt1mijF-0aynGVdqphSRSAxz6lE92I3-_xCjeB6NnNOZQg8lhk6m7Z&aep=10&ntc=1&sxsrf=APpeQntWNux-I_qZ_syFdx-90CDqJBRqWw%3A1790317678216&mstk=AUtExfAg3LFsytGsS85mV5shCA9Z9m0rIm9oROoGV0AKq7NRgFOx-uakXLiZugjXuZUkU7qSIg2GG_j6aJWabmxJLO9VmHyrrVbH_Z2trGIoj2oZXLYbBQgs3H9cz_aoTmBMU3i3NEtBrpaEaqnvMUa0_KE3rqyjBc4dsABfNVd1-bvwA1BY9arf4z5JuQfzMSim5hOBqCJnRCjqe5tLQsH9xsDVooe87V766R-W_VjmDi8eEftcbZW4YQhNBm_fCPwb0NZz0NrsoF2682cCldHp2UXTt6Gt8UnEHb93plh9X89bKnnOPmWHmbre1FzRdiqNMulZ35DozXYckQCPUOnhV4q9qC8zEYC0zhW5W2nPRKMad0njGDu-Uc0&aioh=3&csuir=1&mtid=0xS2aoSXL_OpkdUPjdbSkQ8
:END:



#+BEGIN_QUOTE
1. Die gelbe Figur (Mitte)

    Bedeutung: Optimismus, Lebenskraft und das Heilige.
    Kontext im Bild: Gelb steht bei Haring oft für unschuldige Energie oder den Menschen in seinem Urzustand (ähnlich wie sein berühmtes „Radiant Baby“, das oft gelb strahlt). Dass ausgerechnet die gelbe, optimistische Figur das schmerzhafte Loch im Bauch hat, zeigt die tiefe Verwundbarkeit des menschlichen Geistes durch Traumata. 
    Artnet News +4

2. Die rote Figur (Links)

    Bedeutung: Leidenschaft, Vitalität, aber auch Gefahr und Dringlichkeit.
    Kontext im Bild: Rot ist in Harings Farbsprache die aktivste und emotional geladenste Farbe. Sie symbolisiert hier das impulsive, kraftvolle Zugehen auf den anderen. Später in den 80er-Jahren (während der AIDS-Krise) nutzte Haring Rot auch verstärkt, um Blut, Lebensbedrohung und den Kampf ums Überleben darzustellen. 
    andipagallery.com +2

3. Die türkise / cyanblaue Figur (Rechts)

    Bedeutung: Spiritualität, Ruhe und Frieden.
    Kontext im Bild: Blau- und Türkistöne nutzte Haring traditionell für spirituelle oder friedliche Konzepte. Diese Figur bringt eine harmonisierende, heilende Energie in die Dreierkonstellation. 

4. Der violette Hintergrund

    Bedeutung: Das Unbekannte, Mystische oder die Transformation.
    Kontext im Bild: Ein dunkler, violetter Hintergrund hebt die leuchtenden Primär- und Sekundärfarben der Figuren extrem hervor. Violett schafft einen Raum, der außerhalb der realen Welt existiert – es verleiht der Szene eine fast rituelle oder universelle Gültigkeit.

Das Zusammenspiel: Ein „visuelles Esperanto“
Haring wollte Kunst für jeden Menschen zugänglich machen, unabhängig von Herkunft oder Bildung. Die bewusste Kombination aus der lebendigen roten Kraft und der spirituellen türkisen Ruhe, die sich im Inneren der verletzten gelben Mitte verbinden, erzählt ganz ohne Worte eine Geschichte von kollektiver Heilung, Diversität und Mitgefühl. Seine geschlechtsneutralen, einfarbigen Figuren transportieren so die Botschaft, dass alle Menschen – ungeachtet ihrer Hautfarbe oder Identität – im Kern gleich sind und einander beistehen müssen./

(Zitat von [[https://www.google.com/search?hl=de&q=keith+haring+bild+von+drei+menschen+zwei+greifen+durch+ein+loch+im+bauch+des+mittleren&udm=50&fbs=ABfTbFUyxjQn9bne4DuflY2dNqqKupTsDwp6RXwpQFJxPysO9IZ-OcP6xq64A4yNP8lBdpbV1NcW6cxeRROTFTHTKwOqDjWNGJkd7gEr3KwTkPk0UoDBnxQ3J5HkgKbFwYmwvJAkynUczpEbvmxO-Tqt1mijF-0aynGVdqphSRSAxz6lE92I3-_xCjeB6NnNOZQg8lhk6m7Z&aep=10&ntc=1&sxsrf=APpeQntWNux-I_qZ_syFdx-90CDqJBRqWw%3A1790317678216&mstk=AUtExfAg3LFsytGsS85mV5shCA9Z9m0rIm9oROoGV0AKq7NRgFOx-uakXLiZugjXuZUkU7qSIg2GG_j6aJWabmxJLO9VmHyrrVbH_Z2trGIoj2oZXLYbBQgs3H9cz_aoTmBMU3i3NEtBrpaEaqnvMUa0_KE3rqyjBc4dsABfNVd1-bvwA1BY9arf4z5JuQfzMSim5hOBqCJnRCjqe5tLQsH9xsDVooe87V766R-W_VjmDi8eEftcbZW4YQhNBm_fCPwb0NZz0NrsoF2682cCldHp2UXTt6Gt8UnEHb93plh9X89bKnnOPmWHmbre1FzRdiqNMulZ35DozXYckQCPUOnhV4q9qC8zEYC0zhW5W2nPRKMad0njGDu-Uc0&aioh=3&csuir=1&mtid=0xS2aoSXL_OpkdUPjdbSkQ8][keith haring bild von drei menschen zwei greifen durch ein loch im bauch des mittleren - Google Suche]], [2026-09-25 Fr 08:33])
#+END_QUOTE

* keith haring warum malt er so - Google Suche
:PROPERTIES:
:CREATED: [2026-09-25 Fr 08:38]
:SOURCE: https://www.google.com/search?hl=de&q=keith%20haring%20warum%20malt%20er%20so
:END:



#+BEGIN_QUOTE 
- Warum sein Stil so ist, wie er ist ::

  - Einfache Zeichensprache: Er reduzierte Figuren auf wenige, prägnante Linien und leuchtende Farben, damit sie jeder sofort verstehen und wiedererkennen konnte – ganz ohne Vorkenntnisse. 
    
  - Spontan und schnell: Er malte meistens direkt aus dem Gefühl heraus und ohne vorherige Skizzen. Das war wichtig für seine Aktionen in der New Yorker U-Bahn, wo er schnell arbeiten musste, bevor die Polizei kam. 
    
  - Einfluss von Comics: Schon als Kind brachten ihm Cartoons und Comics seines Vaters das Zeichnen bei, was seinen spielerischen, linearen Stil prägte. 
  
- Warum er so gemalt hat (Seine Ziele und Themen) ::

  - Kunst auf der Straße: Er nutzte leere Werbetafeln in der U-Bahn oder Hauswände, um den direkten Kontakt zu den Menschen im Alltag zu suchen, statt seine Werke nur in teuren Galerien zu verstecken. 
  
  - Politischer Aktivismus: Hinter den tanzenden Strichmännchen, Babys und Hunden verbargen sich oft ernste, politische Botschaften. Er machte auf Themen wie die Aids-Krise, Rassismus, Homophobie und nukleare Bedrohung aufmerksam. 
    
  - Lebensgefühl der 1980er: Seine dynamischen Linien sollten Energie, Leben, aber auch die Dringlichkeit seiner Zeit ausdrücken, da ihm bewusst war, dass ihm durch seine HIV-Infektion nur ein kurzes Leben blieb. Er starb 1990 im Alter von nur 31 Jahren. 


(Zitat von [[https://www.google.com/search?hl=de&q=keith%20haring%20warum%20malt%20er%20so][keith haring warum malt er so - Google Suche]], [2026-09-25 Fr 08:38])
#+END_QUOTE

