#+title:      Konferenz November
#+date:       [2024-11-26 Di 15:51]
#+filetags:   :schule:
#+identifier: 20241126T155100

* Begrüßung

* Tagesordnung
Danke dem Gesunde Jause Team

10.+11.12. normale Jausen Verkauf vor dem Siedeln; dann Notfallbetrieb (mit Kühlschrank)
QR Codes *mit* den Kindern einscannen (nachfragen); erinnern, bis wann die Pässe zu kaufen sind (bis 07:40). Vll könnten sich Lehrer einen Pass kaufen? Welche Klassen benötigen Zitronen für die Wasserkaraffe?

Elternabend: nicht so guter Besuch, eine Voranmeldung für die Musikklasse (sagt noch nix!)

Weihnachtsdekoration / Kranzweihe: 2 Schüler pro Klasse; 29.11. 09:45. Christbaum.

Weihrauch / Kerzen NUR unter AUFSICHT!

Elternsprechtag: am 27.11. (6 min Intervall); ab 15h00.

* Neubau / Übersiedlung
Die Container wurden am 11.11. pünktlich geliefert ... Ab dem 16.12. können sie bezogen werden. Container sind neu und der Fußboden sind empfindlich (Fußabstreifer). Die Firma lässt sich jeden "Kratzer" als Schaden bezahlen. Container Klassen haben Digiboards ohne (oder mit?) Whiteboard Flügel + Tischkamera.

Stauraum: Tische und Sesseln mitnehmen;

Zwischenlager: Keller des Sen-Heimes - Musik, BU, ... (für die 2 Jahre).

Zufahrt: von vorne bis Mitte / Ende Jänner; dann von hinten. Reservierte Plätze für Lehrer (nicht öffentlich).

Aufsicht: zusätzliche Container / Aufsicht durch Schulwart / Reinigungsdamen. 

Möbel: rot (wegschmeißen); orange (zwischenlagern); blau (verwenden).

Jeder Lehrer erhält einen Raum zum Ausräumen, wegschmeißen, etc: Liste! Va jeder sein Kasterl im Konferenzzimmer. Dies alles vor Weihnachten.

(drei Tage Verlängerung: L siedeln; S schulfrei) 10.01.2025: Bezug der Klassen; Unterricht laut Stundenplan. Gerne eine KV Stunde in der ersten Stunde - falls Bedürfnis besteht. Aufregung der Schüler, weil alles neu ... darauf Rücksicht nehmen.

* Benehmen der Schüler
... lässt zum Wünschen übrig! V.a. Pausenaufsicht! Religion / Freistunde (offene Tür, oder 2. Stock); KEIN Handy! ruhig arbeiten. Handy ausgeschaltet im Spint, sobald sie die Schule betreten. Handy in der Schule NEIN! (auch nicht für Kahoot) Was tun, wenn Tablet nicht aufgeladen ist? 

Beim Betreten der Schule - Handy aus! Konsequenz: Handy weg, in der Direktion abholen (am Ende des Schultages); bei mehrmaligem Vergehen: müssen die Eltern das Handy abholen. Vorbildwirkung der Lehrer.

Pause - es soll ruhiger werden - Schüler bleiben in ihrem Stock und Gang! 

* WCs und Klassen
Klassen in der letzten Stunde aufräumen und säubern; WCs im 2. Stock wurden absichtlich verstopft.

Vorschlag: eventuell die 1d statt der 2a in den Container? Nicht so kommunizieren, dass nur die Braven in die Container dürfen. 

* QMS
Prinzipiell übetroffen

* IKM Plus
betrifft welche Fächer? (D, E, M?)

* Kinderschutzrichtlinie
ist erstellt.

Aktuell: vier Mädchen ritzen sich, eine davon ist im Krankenhaus - hinschauen, sicher sind es mehr! Klasse, Sport, ... KV / Schulleitung melden.

Friedensbüro: 2 (von 3) Workshops sind bereits terminisiert. 

* Geistige Landesverteidigung
Extremismus = Ressortschwerpunkt

Vermittlung demokratischer Werte / Demokratie. Zeitenwende: Prozess dauert 20-30 Jahre. Österreich möchte bis 2032 wieder wehrfähig sein (Personalmangel, Spezialistenmangel). Politische Bildung nicht nur in Geschichte, betrifft alle Fächer. Mehr Wissen, Bildung, ... desto besser. 

** Islamismus
Scharia über unserem Gesetz / 5x mehr Delikte / immer jünger (13-19 Jahre); Anti-Semitismus; 

** Rechtsextremismus / Linksextremismus
Ungleichheit aufgrund von ... das Guthießen von Gewalt.

** Radikalisierung
pull - push; 

** Demokratie
ist prinzipiell kontrovers; 

** Meinungsfreiheit
Kinder sollen erfahren, dass es mehr als eine Meinung gibt.


* Allfälliges
Gesundheitskabarett: 4. Klassen, 10.12., 9h40

Schulschitag: 11.12.

"Schubu" digitale Sculbücher. Marius fragen!

13.12. Weihnachtsfeier (fragen wie das abläuft!), 13h30. Anmelden! Hui.
18.12. Vorspielabend 3c 19h00 Kirche
19.12. 17-19h00 Krippenausstellung
20.12. Weihnachtsgottesdienst 8h, danach Unterricht bis 11:20 (inklusive 1h Feier, in der 4. Stunde). 
Letzte Woche vor Weihnachten 4c Erste Hilfe Kurs Mo-Mi.
