#+title:      A Klasse 2025-29 Seekirchen
#+date:       [2024-09-08 So 21:40]
#+filetags:   :1a:sk:
#+identifier: 20240908T214000
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/1a Seekirchen.html

* Jahresplanung

[[denote:20240719T125948][Zeit für Religion 01]]

#+BEGIN: denote-links :regexp "_01_welt" :not-regexp nil :excluded-dirs-regexp "Mattsee" :sort-by-component nil :reverse-sort nil :id-only nil :include-date nil
- [[denote:20250906T002625][Feste feiern]]
- [[denote:20250906T002644][Hurra, wir feiern ein Fest!]]
- [[denote:20250906T002654][Im Rhythmus der Zeit]]
- [[denote:20250906T002704][Die Festkreise]]
- [[denote:20250906T002714][Maria, eine mutige Frau]]
- [[denote:20250906T002725][Weihnachtsspecial "Fürchtet euch nicht!"]]
#+END:


* Notizen, Tasks, Termine

* Stundenplanung

** Jesus und die Samariterin am Jakobsbrunnen

(Episode aus The Chosen - hoffentlich klappt das Internet in der Klasse!)

Joh 4 lesen.  + The Chosen Staffel 1 Episode 8

(Staffel 5 online verfügbar!)

Lebendiges Wasser - Gottes Liebe, Gottes Geist; Anbetung in Geist und Wahrheit.

Die große Frage - was erwartest du dir von Gott?
"Was willst du, dass ich dir tue?" - Frage von Jesus an Bartimäus.

Schüler sollen sich mit dieser Frage auseinandersetzen, sie an sich heran lassen. Und ihre Erwartungen formulieren. Aufschreiben. Die "Gefahr" ist, dass die Kinder sagen "nix!" - und meinen, damit den Auftrag erfüllt zu haben; "Können wir jetzt Kahoot spielen?" - So leicht lasse ich die Kinder nicht aus ihrer "Pflicht". Wer nichts von Gott erwartet, wird auch nichts von Gott erhalten. So wie der ältere Sohn im Gleichnis vom verlorenen Sohn. Er bleibt in seiner Welt der Gerechtigkeit; fragt nach nichts. Und ist dabei genauso unglücklich wie sein jüngerer Bruder als der die Schweine hütete.

Wie viel schöner ist doch das Leben - wenn du dich von Gottes Liebe berühren lässt?
 

** Das Leben Jesu

"Siehe, ich mache alles neu!" (Offb)

- Taufe Jesu
- Versuchung Jesu
- Bergpredigt
- Wunder, ...


** Mit der Bibel arbeiten

Kirche in Not - Bibelstelle ziehen und damit eine schöne Seite im Heft gestalten; ebenso mit dem Jahresheiligen - eventuell Informationen aus dem Internet notieren. Nachdenken und notieren, was die Bibelstelle und der Jahresheilige für dich bedeute könnte. Vorher - beten.

** Fastenzeit

Gebet / Umkehr / sieben Werke der Barmherzigkeit


** Gleichnisse Jesus
Gleichnis vom verlorenen Schaf / verlorenen Sohn.
Sämann - Perle - Schatz im Acker - Sauerteig - Senfkorn

[[file:~/Dokumente/LaTex_2/Kreinecker_ReichGottes/ReichGottes.pdf]]

* Reflexionen

** Dröscher Sonja

** Falger Maximilian

** Hinterleitner Valerie

** Kühleitner Lukas

** Mayr Luis
 
** Nöbauer Tobias
 
** Papp Csenge
 
** Sammer Maximilian

** Selimi Alina

** Stein Mira

** Strasser Simon

** Unger Manue

** Wagner Elena

** Winterreiter Michael

** Wuppinger Sophie

