#+title:      B Klasse 2023-27 Seekirchen
#+date:       [2024-09-08 So 21:43]
#+filetags:   :3b:sk:
#+identifier: 20240908T214359
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/3b Seekirchen.html

* Jahresplanung

[[denote:20240709T110253][Zeit für Religion 03]]

* Notizen, Tasks, Termine


* Stundenplanung

** Der verlorene Sohn

Lk 15 - wer bin ich in der Geschichte? Der Jüngere oder der Ältere?
Wofür stehen die Brüder? Was sagt uns Jesus über Gott?
Bild betrachten
Bildgeschichte zeichnen


** Fastenzeit

Was sind die Probleme unserer Zeit?
- Zusammenbruch der Familien: weniger (zu wenige) Kinder / Ehescheidungen
- Verlust des Heiligen / Gottes; wir haben Gott verloren, es gibt ein Sinnvakuum - wodurch füllen wir das?
- aus den Fugen geratener Kult des Ichs, Selbstoptimierung, Besitz, Zerstörung der Natur

Medien beschleunigt dies. Seit den 1950er Jahren der USA.

Religionen - welche Ideale? Ganz anders: Verzicht, Sexualmoral, Askese, ... kein Streben nach materiellen Gütern.

Jeder Mensch betet etwas an - es kommt darauf an, was er anbetet. 

** Menschenrechte

(2 Dokumente)
Präambel
"DIE Menschenrechte gibt es nicht" - wichtigste Punkte heraus arbeiten.

** Bibel

[[https://relpaed.plus/2025/10/16/bartimaeus/]]

Bartimäus - Dunkel vor den Augen / Dunkel im Herzen

Hab Mut - steh auf!

Möglichkeiten der Weiterarbeit:
- Mutmachworte
- Wer war in der Menschheitsgeschichte wirklich mutig?

HELL VOR AUGEN – HELL IM HERZEN
Jesus hört Bartimäus und ist beeindruckt von seinem Mut, seinem Glauben und seiner Entschlossenheit. Er bleibt stehen und sagt, die Menschen sollen Bartimäus zu ihm bringen. Dass Jesus sich wirklich mit Bartimäus unterhalten möchte, dem Bettler, dem Sünder und Ausgestoßenen, scheint die Menschen zu verwundern und ihnen die Augen zu öffnen. Denn statt Bartimäus weiterhin zu beschimpfen, ermutigen sie ihn, zu Jesus zu gehen. Das lässt Bartimäus sich nicht zweimal sagen. Er wirft seinen dreckigen Mantel in den Staub und geht eilig der Stimme von Jesus entgegen. Entschlossen bittet Bartimäus Jesus, wieder sehen sehen zu können. Er sehnt sich nach dem Licht in seinem Leben – vor Augen und im Herzen. Er sehnt sich nach Gemeinschaft und Freiheit. Und Jesus bringt dieses Licht zurück mit den Worten: „Geh, dein Glaube hat dir geholfen!“ Bartimäus ist so voller Begeisterung und Glück, dass er Freudensprünge macht. Denn er begreift: In seinem Leben wurde es wieder hell – vor Augen und im Herzen. Er kann wieder sehen und hat Freunschaft, Gemeinschaft und Freiheit gefunden, denn von diesem Tag an begleitet er Jesus auf seinem Weg.

Hell im Herzen

Jesus bringt Licht in Bartimäus‘ Herz. Er nimmt ihn an, hört ihm zu und wird sein Freund. Auch die Schülerinnen und Schüler können sich mit der Helligkeit im Herzen auseinandersetzen.

Sehend und blind im Herzen

Die Klasse überlegt gemeinsam, welche Menschen in der Geschichte wirklich blind und welche sehend waren und warum. Als Impuls kann das folgende Gedicht von Hubertus Halbfas (Die Bibel für kluge Kinder und ihre Eltern. Stuttgart 2014 S.220) dienen:

„Kann jeder sehen, der sehen kann? Es ist nicht so einfach,

wie du denkst. Wer meint,

er könnte es schon längst,

mög‘ bedenken dann und wann,

ob mit Aug und Herz er sehen kann.“

Lichtwörter sammeln

Die Schülerinnen und Schüler sammeln auf einem hellen Tonpapier Lichtwörter. Impulsfragen können dabei sein: Wie geht es dir, wenn es hell ist und die Sonne scheint? Wann fühlt sich dein Herz hell und leicht an? Wo spürst du dieses Gefühl in deinem Körper?

"Man sieht nur mit dem Herzen gut. Das Wesentliche ist für die Augen unsichtbar." (Der kleine Prinz - der Fuchs zum kleinen Prinzen)

** Warum stellen wir Fragen

[[denote:20260123T091818][Warum stellen wir Fragen]]


* Reflexionen

** Bauböck Jonas

** Bosin Valentin

** Breckner Mona

** Clausen Jonas

** Enzinger Sophia

** Gappmaier Pia

** Gerngross Eva

** Gollackner Hanna

** Gschwandtner Johannes

** Hofer Nico

** Idris Dalia

** Kessler Fabio

** Költringer Amelie

** Krempler Dominik

** Laimer Raphael

** Reichl Verena

** Roth Enna

** Schober Luisa

** Strohbichler Noah

** Thurner Maximilian

** Wagner Jasmin

** Wassermann Sophia

** Wieder Leonhard

** Wimmer Antonia

** Wirthenstätter Samuel

