#+title:      Das Wunder des Lebens
#+date:       [2024-09-09 Mo 21:52]
#+filetags:   :03:gemeinschaft:
#+identifier: 20240909T215228

* Arbeitsauftrag 1
Mögliche Beschreibungen, wie gläubige Menschen das menschliche Leben empfinden, könnten sein:

    - das Leben ist ein Geschenk Gottes
    - dass das menschliche Leben einen (tieferen) Sinn hat
    - das jedes Leben einzigartig ist
    - das menschliche Leben kein Zufall ist, …
    
* Arbeitsauftrag 2
Dieser Arbeitsauftrag regt zum Theologisieren an und kann sehr individuell ausfallen.
Eine mögliche Antwort könnte folgend lauten: „Dass Gott die Menschen liebt und möchte, dass es den Menschen gut geht.“

* Arbeitsauftrag 3
Dieser Arbeitsauftrag ist sehr persönlich und individuell.
Hier bietet es sich an die Schüler*innen zu zweit oder in Kleingruppen zusammenarbeiten zu lassen, um gemeinsam ihr eigenes Leben zu reflektieren.

* Arbeitsauftrag 4
In dieser Diskussion können die biologischen und theologischen Sichtweisen erörtert werden.
Auch hier bietet es sich an, der Frage: „Wem oder was verdanken wir unser Leben?“ in Kleingruppen zu besprechen und erst im zweiten Schritt die Ergebnisse in der Klasse zu diskutieren.

* Arbeitsauftrag 5
Bei diesem Arbeitsauftrag spielen Moraltheologie und ethische Fragen eine bedeutende Rolle. Auch die Frage, ab wann spricht man vom Leben (Befruchtung oder erst ab Geburt) könnte hier zum Thema gemacht werden.
Aus dem christlichen Gesichtspunkt hat das menschliche Leben von Beginn an eine unantastbare Würde und eine unsterbliche Seele.

* Arbeitsauftrag 6
Die Bearbeitung des Arbeitsauftrages erfordert ein fächerübergreifendes Denken. Hier könnte man den einzelnen Bildern eine Überschrift geben und den Zeitstreifen der Seitenspalte zur Hilfe nehmen.

    1. Bild: Samenzelle trifft auf Eizelle
    2. Bild: Beginn der Zellteilung
    3. Bild: erster Herzschlag
    4. Bild: Embryo am Utraschall 
    5. Bild: Geburt
    6. Bild: Kind entdeckt sein "ICH"
    7. Bild: Kind lernt gehen
    8. Bild: Kind lernt selbständig essen
    9. Bild: Kind entdeckt die Umgebung
    10. Bild: Pubertät beginnt
    11. Bild: erstes verliebt sein
    12. Bild: erwachsen sein


* Arbeitsauftrag 7
In der Diskussion sollte einerseits die biologische Ansicht (Gene, Alterungsprozess) aber auch die ethische Sichtweise (Charakterentwicklung) mitgedacht werden.


* Arbeitsauftrag 8
Die Reflexion über die Veränderung des eigenen Lebens anhand der Fotos kann für die Schüler*innen ein aufschlussreiches Erlebnis sein. Hier könnte man auch eine kreative Bearbeitung des Themas anschließen: Z.B: Gestalte ein Plakat mit den Fotos über die Entwicklung des eigenen Lebens bzw. der eigenen Persönlichkeit.

