#+title:      Gespräch mit 4c
#+date:       [2024-10-09 Mi 07:26]
#+filetags:   :4c:memo:
#+identifier: 20241009T072626

* Gedanken
Gestern hatte ich dem KV (Theresa) und der 4b ein Gespräch. Ursprünglich kam ich in die Klasse, weil mir gesagt wurde, die Klasse würde sich gerne für ihr schlechtes Verhalten mir gegenüber entschuldigen wollen.

Davon war schlussendlich nicht viel spür- und hörbar. Im "Gegenteil": die Schüler brachten Anregungen vor, wie der Unterricht besser verlaufen könnte. 

* Anregungen
- Namen merken und Schüler mit Namen anreden; durch ein Spiel habe ich mir alle Namen merken können.
- Mache ich mir einen Plan? Die letzten Stunden haben wir zweimal das Gleiche gemacht.
- Vielleicht Bibelgeschichten
- Weltreligionen wurden in der dritten Klasse erledigt - dieses Jahr nicht mehr bearbeiten.
- "Sie dürfen uns wirklich schimpfen!"


* Themen / Ideen

** Bibel
- Bibel lesen: ein Buch der Bibel komplett lesen (Rut, und andere kürzere Bücher im AT, ein kleiner Prophet; ein Evangelium; einen Brief des Apostel Paulus; Buch der Offenbarung)
- Überblick über die Heilsgeschichte
- Bibel nach einem Thema lesen: "Was sagt die Bibel zum Thema Freundschaft?

** Vieles ist möglich
Da warte ich auch auf Vorschläge von Seiten der Schüler.

** Kirchenführung
Pfarrkirche, Dom in Salzburg, Kapuzinerkloster, Benediktiner (liegt auf der Hand; Abtenau gehört zu St. Peter)
