#+title:      B Klasse 2022-26 Seekirchen
#+date:       [2024-09-08 So 21:42]
#+filetags:   :4b:sk:
#+identifier: 20240908T214223
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/4b Seekirchen.html

* Jahresplanung

[[denote:20240719T131544][Zeit für Religion 04]]

* Notizen, Tasks, Termine


* Stundenplanung

[[denote:20250907T162116][Lebensperspektiven und Lebensträume]]

[[denote:20250907T162137][Das Leben - eine einzigartige Geschichte]]

Zu Heiligen eine PPP erstellen:

[[denote:20250907T160742][Gottes_Nächsten_Selbst_Liebe]]

** Einführung / Ziele


** Wiederholung


** Themen



** Hefteintrag



* Klassenliste
#+Name: 2021-students
|-----------+--------------+----------------------+------+-----------+------+-----|
| First     | Last         | Name                 | Note | Mitarbeit | Heft | LZK |
|-----------+--------------+----------------------+------+-----------+------+-----|
| Dominik   | Auer         | [[Dominik Auer][Dominik Auer]]         |      |           |      |     |
| Markus    | Engel        | [[Markus Engel][Markus Engel]]         |      |           |      |     |
| Christoph | Grünwald     | [[Christoph Grünwald][Christoph Grünwald]]   |      |           |      |     |
| Daniel    | Grünwald     | [[Daniel Grünwald][Daniel Grünwald]]      |      |           |      |     |
| Elias     | Gutjahr      | [[Elias Gutjahr][Elias Gutjahr]]        |      |           |      |     |
| Paul      | Knoblechner  | [[Paul Knoblechner][Paul Knoblechner]]     |      |           |      |     |
| Lukas     | Lanzinger    | [[Lukas Lanzinger][Lukas Lanzinger]]      |      |           |      |     |
| Felix     | Leopolder    | [[Felix Leopolder][Felix Leopolder]]      |      |           |      |     |
| Alexander | Lienbacher   | [[Alexander Lienbacher][Alexander Lienbacher]] |      |           |      |     |
| Bernhard  | Lienbacher   | [[Bernhard Lienbacher][Bernhard Lienbacher]]  |      |           |      |     |
| Christian | Moisl        | [[Christian Moisl][Christian Moisl]]      |      |           |      |     |
| Elina     | Quehenberger | [[Elina Quehenberger][Elina Quehenberger]]   |      |           |      |     |
| Matea     | Remic        | [[Matea Remic][Matea Remic]]          |      |           |      |     |
| David     | Reschreiter  | [[David Reschreiter][David Reschreiter]]    |      |           |      |     |
| Lara      | Schmidt      | [[Lara Schmidt][Lara Schmidt]]         |      |           |      |     |
| Celina    | Schörghofer  | [[Celina Schörghofer][Celina Schörghofer]]   |      |           |      |     |
|-----------+--------------+----------------------+------+-----------+------+-----|
#+TBLFM: $4=vmean($5..$7);%.0f
#+TBLFM: $3='(concat "[[" $1 " " $2 "][" $1 " " $2 "]]")
#+TBLFM: $5='(identity remote(Mitarbeit,@@#$2))

#+BIND: org-export-filter-timestamp-functions (tmp-f-timestamp)
#+BIND: org-export-filter-strike-through-functions (tmp-f-strike-through)
#+BEGIN_SRC emacs-lisp :exports results :results none
  (defun tmp-f-timestamp (s backend info)
    (replace-regexp-in-string "&[lg]t;\\|[][]" "" s))
  (defun tmp-f-strike-through (s backend info) "")
#+END_SRC


#+BEGIN_SRC python :var table=2021-students :results output raw
  print('* Mitarbeit')
  for student in table:
      first = student[0]
      last = student[1]
      email = last + '.' + first + '@abtenau.schule'
      print('** ' + first + ' ' + last + '')
      print(':PROPERTIES:')
      print(':EMAIL: ' '[[mailto: ' + last + ' ' + first + ' <' + email + '>]]')
      print(':EXPORT_FILE_NAME: ' '~/Documents/exports/'  + first +  '_'  + last +  '.html')
      print(':ID: ' + first + '' + last + '')
      print(':END: ')
      print('#+Name: Note_' + first + '' + last + '')
      print('|-----------------------+-------+-------------+-----+-----------+------------|')
      print('| Datum                 | Topic | Heft / Buch | LZK | Mitarbeit | Gesamtnote |')
      print('|-----------------------+-------+-------------+-----+-----------+------------|')
      print('|                       |       |             |     |           |            |')
      print('#+TBLFM: $6=vmean($3..$5);%.0f')
      print('\n')
#+END_SRC

#+RESULTS:
* Mitarbeit



* Reflexionen

** Wie vorgehen?
:PROPERTIES:
:CAPTURED: [2025-11-03 Mo 16:49]
:DESCRIPTION: [[file:~/Documents/notes/20240908T214223--b-klasse-2022-26-seekirchen__4b_sk.org::*Stundenplanung][Stundenplanung]]
:END:
Ich bin ehrlich gesagt etwas ratlos. Die Schüler sind ziemlich schwierig - und das laut der Putzfrau schon seit der ersten Klasse. Sehr oft kommt das Argument: "Das ist eine Sportklasse. Da haben die Schüler und auch die Eltern ein sehr hohes Selbstbewusstsein, denken sie seien so toll. Und benehmen sich leider sehr daneben." 

Ich habe die Klasse selbständig arbeiten lassen, was nur bedingt geklappt hat. Die Kids schreien wie Affen, grunzen wie Schweine, es fliegen Patschen, Schuhe, ... Wenn mal eine Wasserflasche umfällt, wird meterweise Papier verwendet (was natürlich sehr viel Lärme macht). Wenn man da als Lehrer laut wird, gießt das nur Öl ins Feuer. Danach imitieren die Schüler den Lehrer, äffen ihn nach. Also sag ich oft nichts. 

Ich denke mir eben: "Ich hab diese Klasse eh nur ein Jahr, dann sind sie weg!" Was soll ich da noch ändern? Meine Kollegin, die am Ende des Jahres in Pension geht, hat diese Klasse sehr gerne abgegeben (wie alle anderen Sportklassen - 2b und 3b - auch).

Soll ich mit ihnen manchmal eine Lernstunde vor einer SA oder Test einfügen?

** Burschen 2. Reihe (Wand)
Überschwemmung auf Tisch, dauert ewig, bis Tisch trocken ist. Kein Unterricht möglich...
