#+title:      Neue Themen
#+date:       [2024-11-09 Sa 22:13]
#+filetags:   :schule:
#+identifier: 20241109T221305

* Gedanken
:PROPERTIES:
:CUSTOM_ID: h:9e14940c-f73e-4b5e-b514-87cf15c80135
:END:
F체r n채chste Woche suche ich noch nach Themen, leider f채llt mir derzeit gar nichts ein.

In den ersten und zweiten Klassen gibt es die Lernschiene; ... den "Sturm auf dem See" haben die ersten Klassen so gut wie fertig; jetzt kommt "Die Heiligen"

F체r die zweiten Klassen? "Hl. Blasius / hl. Rupert" ist eigentlich ein Thema der ersten Klasse.
- Rosenkranz?
- Bibel
- ...

Welche Themen habe ich in den Heften der dritten und vierten Klassen gesehen?
- Maria / Schutzmantel
- Sieben Sakramente
- Aufbau der Hl. Messe
- Ostern
- Weihnachten

Dritte Klassen:
- Weltreligionen
- Vielleicht hier weiter machen und gemeinsam den Islam und das Judentum erarbeiten


Vierten Klassen:
- das Buch der Offenbarung genauer weiter lesen (hat nur nicht so gut funktioniert in der 4c?); kein wirkliches Interesse


* Leopold's Ideen
RU - Geschichten (Was Gott erschaffen hat, Noah, Franziskus, Maria, ...)
