#+title:      Neue Themen nach Weihnachten
#+date:       [2024-12-26 Do 14:43]
#+filetags:   :schule:
#+identifier: 20241226T144325

* Themen

** Heilige Drei Könige
Wer sind die drei Sterndeuter?
Ihre Suche ...
Bedeutung der Namen?
Drei Alter / Länder (Kontinente)

Bedeutung der Geschenke

"Kehren auf einem neuen Weg nach Hause"


** Weihnachten / Gott wird Mensch
Erwartung des Messias

Prophezeiungen der Propheten

Erfüllung in Jesus

** Bibel
Themen / Bücher kennenlernen
Heilsgeschichte des Volkes Israel im Überblick

Propheten

Psalmen

** Welche Themen aus den Religionsbüchern?

** Hl. Apostel Paulus
Verfolgung der Christen
Steinigung des Stephanus
Bekehrung
Missionsreisen

** Ökumene / Kirchengeschichte

** Gebet

* Struktur der Stunde
Wie bete ich in der Stunde? Wie führe ich die Kinder zum Gebet?

Sich sammeln? In sich hinein hören, still werden, ... 

** Gebet mit YouCat Daily
Gebet / Lesung aus der Bibel / Gedanken und Betrachtung

** Zusammenfassung der letzten Stunde

** Arbeitszeit der Kinder

** Hefteintrag
