#+title:      Jahresplanung 04
#+date:       [2024-07-19 Fr 13:15]
#+filetags:   :Project:topic04:
#+identifier: 20240719T131544
#+CATEGORY: topic 04
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Jahresplanung 04.html

* Kap. 1 | Lebensperspektiven und Zukunftspläne

** Kompetenzbereich / Leitkompetenz

A Menschen und ihre Lebensorientierungen

A2 Sich mit den großen Fragen der Menschen auseinandersetzen können

** Kompetenzbeschreibung

Die Schüler:innen können Perspektiven für ihr Leben entwickeln und Zukunftspläne entwerfen.

** Anwendungsbereich / Unterrichtshinweise

Sehnsüchte und Lebensträume, persönliche und berufliche Ziele, Utopien und Dystopien

** Inhalte / Buch

- Eröffnung
- "Spiel des Lebens"
- Lebensperspektiven und Lebensträume
- Das Leben - eine einzigartige Geschichte
- Die Zukunft - meine Lebensziele
- Die Utopie - ein Zukunftsmodell
- Das Vertrauen - eine Entscheidungshilfe
- Kompetenzcheck

** Kompetenzniveau 1 / Übergreifende Themen

KN 1:

Übergreifende Themen:
Bildungs-, Berufs- und Lebensorientierung (1)
Entrepreneurship Education (2)


* Kap. 2 | In einer Gemeinschaft verbunden

** Kompetenzbereich / Leitkompetenz

B Gelehrte und gelebte Bezugsreligion

84 Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können

** Kompetenzbeschreibung

Die Schüler:innen können die Firmung als Befähigung und Beauftragung zum Mitwirken an den Grundvollzügen der Kirche erläutern.

** Anwendungsbereich / Unterrichtshinweise

AB:
Verkündigung - Liturgie - Diakonie - Gemeinschaft

UH:
Sakrament: Firmung - Entscheidung zur (Nicht-)Teilhabe; Möglichkeiten des Mitwirkens junger Menschen in der  Kirche, Compassion

** Inhalte / Buch

- In einer Gemeinschaft verbunden
- Erwachsen werden
- Ich bin bereit
- Ohne uns geht gar nichts
- In der Gemeinschaft mitwirken
- Kompetenzcheck

** Kompetenzniveau 1 / Übergreifende Themen

Die Schüler:innen können anhand von Beispielen aufzeigen, wie gefirmte Christen am kirchlichen Leben mitwirken.


* Kap. 3 | Entschieden Freiheit leben

** Kompetenzbereich / Leitkompetenz

A Menschen und ihre Lebensorientierungen
A1 Beziehung verantwortungsvoll gestalten können - zu sich selbst, zu anderen, zur Schöpfung

C Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur
C6 Unterschiedlichen Lebensweisen und Glaubensformen reflexiv begegnen können

** Kompetenzbeschreibung

Die Schüler können das Verhältnis von geltenden Normen und persönlichen Gewissensentscheidungen analysieren und anhand von Beispielen diskutieren.

Die Schüler:innen können lebensförderliche und lebensfeindliche Aspekte in Religionen und Weltanschauungen benennen und beurteilen.

** Anwendungsbereich / Unterrichtshinweise

AB:
Bildung des eigenen Gewissens

UH:
Orientierungskriterien bei Entscheidungen, Gruppendruck, sexualethische Fragestellungen, Gesetzesauslegung Jesu (z. B. Sabbatgebot)

AB:

UH:
Lebensgestaltung in Freiheit, Befähigung zur oder Verlust der Eigenverantwortung, Gewaltstrukturen in Ideologien und Missbrauch von Religion und Autorität, Fundamentalismus

** Inhalte / Buch

- Entschieden in Freiheit leben
- Entscheidungen treffen
- Was ist das Gewissen?
- Auf das Wohl des Menschen ausgerichtet
- Religion: befreiend oder unterdrückend?
- Die dunkle Seite des Glaubens
- Kompetenzcheck

** Kompetenzniveau 1 / Übergreifende Themen

KN 1:
Die Schüler:innen können Kriterien für Gewissensentscheidungen in Bezug auf ein gerechtes Zusammenleben anhand von Fallbeispielen diskutieren.

Übergreifende Themen:
Politische Bildung (7)

KN 1:
Die Schüler:innen können anhand von Kriterien Lebensförderliches und Lebensfeindliches von religiöser und weltanschaulicher Praxis beurteilen.

Übergreifende Themen:
Gesundheitsförderung (3)
Poltische Bildung (7)

* Kap. 4 | In der Kinst Gott und der Welt begegnen

** Kompetenzbereich / Leitkompetenz

** Kompetenzbeschreibung

** Anwendungsbereich / Unterrichtshinweise

** Inhalte / Buch

** Kompetenzniveau 1 / Übergreifende Themen


* Kap. 5 | Schau hin

** Kompetenzbereich / Leitkompetenz

** Kompetenzbeschreibung

** Anwendungsbereich / Unterrichtshinweise

** Inhalte / Buch

** Kompetenzniveau 1 / Übergreifende Themen


* Kap. 6 | Mehr als alles

** Kompetenzbereich / Leitkompetenz

** Kompetenzbeschreibung

** Anwendungsbereich / Unterrichtshinweise

** Inhalte / Buch

** Kompetenzniveau 1 / Übergreifende Themen


* Kap. 7 | Heiliger Geist, komme herab

** Kompetenzbereich / Leitkompetenz

** Kompetenzbeschreibung

** Anwendungsbereich / Unterrichtshinweise

** Inhalte / Buch

** Kompetenzniveau 1 / Übergreifende Themen


* Kap. 8 | Hinduismus und Buddhismus

** Kompetenzbereich / Leitkompetenz

** Kompetenzbeschreibung

** Anwendungsbereich / Unterrichtshinweise

** Inhalte / Buch

** Kompetenzniveau 1 / Übergreifende Themen
