#+title:      Jahresplanung 04
#+date:       [2024-07-19 Fr 13:15]
#+filetags:   :Project:topic04:
#+identifier: 20240719T131544

* Gemeinschaft | Gewissen - der inneren Stimme folgen (Kapitel 1)
September bis Oktober

** Thema/Inhalt
Gewissen – der inneren Stimme folgen (Kapitel 1)

    • Gewissen
    • Dilemma
    • Prophetie 
    • Nachhaltigkeit – Entwicklungsziele

** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können die Bedeutung eines Einsatzes für ein gerechtes Zusammenleben erkennen und konkrete Handlungsoptionen entwickeln.
Die Schülerinnen und Schüler können das Verhältnis von geltenden Normen und persönlichen Gewissensentscheidungen analysieren und anhand von Beispielen diskutieren.

** Hinweis/Alternativen
Schulgemeinschaft
Wie nachhaltig ist unsere Schule? 
Wie gehen wir in unserer Schulgemeinschaft miteinander um. 

** Basisseiten und Empfehlungen
*** [[denote:20240909T205227][Was ist gut und richtig?]]
*** [[denote:20240909T205419][Ein gutes Gewissen]]
*** [[denote:20240909T205442][Dem Gewissen folgen]]
*** [[denote:20240909T205456][Impuls: Ein Dilemma]]
*** Übergang: Der Ruf nach Veränderung
*** Prophetinnen und Propheten
*** Eine bessere Welt
*** Reflexion: Kann mich diese Gemeinschaft stärken?
*** Übungsteil


* Fragen | Sinn - Ziele im Leben finden (Kapitel 2)
November bis Februar

** Thema/Inhalt
Sinn – Ziele im Leben finden
 (Kapitel 2)

    • Beruf – Berufung
    • Sehnsüchte und Sorgen
    • Dystopien und Utopien
    • Tod 
    • Jenseitsvorstellungen

** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können Perspektiven für ihr Leben entwickeln und Zukunftspläne entwerfen. 
Die Schülerinnen und Schüler können die über den Tod hinausgehende christliche Hoffnung beschreiben.

** Hinweis/Alternativen
Fächerübergreifendes Arbeiten
Berufsorientierung – Berufsvorbereitung

** Basisseiten und Empfehlungen 
*** Was möchtest du einmal machen?
*** Vom Beruf zur Berufung
*** Sehnsüchte und Sorgen
*** Impuls: Ein Brief an mich selbst
*** Übergang: Dystopien und Utopien
*** Wie geht es mit unserer Welt weiter?
*** Was kommt nach dem Tod?
*** Unser Leben nach dem Tod?
*** Jenseitsvorstellungen in den Religionen
*** Reflexion: Können mich diese Fragen bewegen?
*** Übungsteil

* Glaube | Auferstehung - den Tod überwinden (Kapitel 3)
März bis April

** Thema/Inhalt
Auferstehung – den Tod überwinden 
(Kapitel 3)

    • Scheitern und Neubeginn 
    • Erwartungen
    • Jesus – Passion
    • Auferstehung 

** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können Leiden, Sterben und Auferstehung Jesu Christi als Hoffnungsbild für Menschen reflektieren.
Die Schülerinnen und Schüler können das vielfältige Wirken des Heiligen Geistes entdecken und charakterisieren.

** Hinweis/Alternativen
Kirchenjahr – Fastenzeit - Ostern
    • Abschied und Einsamkeit 
(Kap. 3.5, S. 58)
    • Verleugnung und Tod
(Kap. 3.6, S. 59)
    • Auferstehung und Befreiung
(Kap. 3.7, S. 60)

** Basisseiten und Empfehlungen
*** Scheitern und Neubeginn
*** Impuls: (Zu) hohe Erwartungen?
*** Übergang: Jesus, der gescheiterte Messias?
*** Jesus, gescheitert am Kreuz?
*** Ankunft und Aufruhr
*** Abschied und Einsamkeit
*** Verleugnung und Tod
*** Auferstehung und Befreiung
*** Aufbruch und Neuanfang
*** Reflexion: Kann mich dieser Glaube tragen?
*** Übungsteil


* Kirche | Firmung - ein Teil der Gemeinschaft werden (Kapitel 4)
April bis Mai

** Thema/Inhalt
Firmung – ein Teil der Gemeinschaft werden
(Kapitel 4)

    • Kirche – Aufgaben / gelebte Gemeinschaft
    • Empathie – das Miteinander
    • Sakrament der Firmung
    
** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können die Firmung als Befähigung und Beauftragung zum Mitwirken an den Grundvollzügen der Kirche erläutern.

** Hinweis/Alternativen
Kooperation mit Pfarre
Wenn sich in der 7. Schulstufe die Mehrheit der Schüler:innen auf das Sakrament der Firmung vorbereitet, könnte das Thema zur Unterstützung der pfarrlichen Firmvorbereitung erarbeitet werden.

** Basisseiten und Empfehlungen
*** Was bringt uns die Kirche?
*** Die Aufgaben der Kirche
*** Gelebte Gemeinschaft
*** Impuls: Empathie - Schlüssel für das Miteinander
*** Übergang: Kirche - bist du dabei?
*** Junge Menschen gestalten die Kirche
*** Das Sakrament der Firmung
*** Reflexion: Kann uns diese Kirche verbinden?
*** Übungsteil

* Welt | Kunst - das Leben ausdrücken (Kapitel 5)
Mai bis Juni

** Thema/Inhalt
Kunst – das Leben ausdrücken
(Kapitel 5)
    • Sinn-Zeichen
    • Mutmacher
    • Sinn-Täger
    • Vorstellungen und Bilder vom Ende
    • Religiöse Kunst
    • Religion prägt unsere Welt

** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können Kunst als Möglichkeit religiöser Weltdeutung verstehen und ihr eigenes kreatives Potential entfalten.


** Hinweis/Alternativen
Exkursion
Welche Art religiöser Kunst findet sich in meinem Wohnort / in meiner Pfarre / in der Umgebung meiner Schule?

** Basisseiten und Empfehlungen
*** Unsere Sinn-Zeichen
*** Impuls: Ästhetische Mutmacher
*** Tattoos - Der Körper als Sinn-Träger
*** Mit Kunst auf Sinn-Suche
*** Übergang: Vorstellungen vom Ende
*** Bilder vom Ende
*** Religiöse Kunst
*** Religion prägt unsere Welt
*** Reflexion: Wie prägt uns diese Welt?
*** Übungsteil

* Vielfalt | Asiatische Religionen - dem Kreislauf des Lebens folgen (Kapitel 6)
Mai bis Juni /oder vorverlegen auf November bis Februar/ 

** Thema/Inhalt
Asiatische Religionen – dem Kreislauf des Lebens folgen (Kapitel 6)

    • Religionen suchen Antworten
    • Religion – Freiheit oder Einschränkung
    • Hindu-Religionen
    • Buddhismus
    • Religiöse Vielfalt Asiens
    
** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler kennen Charakteristika asiatischer Glaubenstraditionen und können diese mit dem christlichen Glaubensverständnis vergleichen. 
Die Schülerinnen und Schüler können lebensförderliche und lebensfeindliche Aspekte in Religionen und Weltanschauungen benennen und beurteilen.

** Hinweis/Alternativen
Interreligiöser Dialog
Feste und Feiern in der religiösen Vielfalt über das Schuljahr hinweg ansprechen

** Basisseiten und Empfehlungen
*** Religionen suchen nach Antworten
*** Impuls: Religion - Freiheit oder Einschränkung?
*** Übergang: Buddha im Baumarkt
*** Hindu-Religionen und Buddhismus
*** Die vielen Götter der Hindu-Religionen
*** Samsara - das Leben als Kreislauf
*** Glaubensleben in den Hindu-Religionen
*** Siddharta Gautama - der erste Buddha
*** Vier Wahrheiten, acht Wege
*** Glaubensleben im Buddhismus
*** Die religiöse Vielfalt Asiens
*** Reflexion: Kann uns diese Vielfalt einen?
*** Übungsteil
