#+title:      Integrationskonferenz 1b
#+date:       [2024-10-10 Do 15:11]
#+filetags:   :memo:
#+identifier: 20241010T151140

Fr. Fussi & Fr. Posselt

* Gedanken
Mit jeder neuen Klasse - mehr Kompetenz

* SPF
drei Schüler dieser Klasse

** Allgemein
SPF betrifft keine Krise; sondern ist eine überdauernde Beeinträchtigung (körperlich, geistig, Sinne, Lernschwächen)
- ASO Lehrplan
- Lehrplan für Kinder mit erhöhtem Förderbedarf
- Lehrplan für SE (Verhalten); Debatte! Keine Bescheide mehr, sondern ein Festellen des Bedarfs. Frage: Verfällt ein bereits zuerkannter Bescheid? BD sagt JA; hm ...

Zuerkennung zum ganzen Kind.

Integration / Inklusion:
Kinder mit Behinderung werden in Schulen mit Kindern ohne Behinderung integriert.

15 Normale Kinder / und drei Kinder, für die ist der SP Lehrer zuständig - das ist falsch, und so denkt hier auch niemand.

Inklusion - geht von Diversität aus:
Jedes Kind ist einzigartig; drei benötigen einen eigenen Lehrplan. Ideal - umsetzbar?

Raumtrennung / immer alles gemeinsam: geht nicht immer, ist nicht immer gut.

Kinder mit SPF hat eigenen Lehrplan, aber auch Teilhabe am "normalen" Lehrplan. So weit es geht.

Als IL ists wichtig zu wissen, wann beginnt ein neues Thema? Kommunikation.
Vll ists dann besser, alleine zu arbeiten.

Tempo / Arbeitsstruktur
Individueller Förderplan; wo wurde gearbeitet? Ziele: was soll der Schüler am Ende der 4. Klasse können? 

Erziehung / Eltern: was bzgl Medikament Zuhause geschieht - geht uns nichts an. Aber als L.: Aber wir als Schule nehmen eine Veränderung wahr.


** Mirjam Götze
D und M (5. ASO)  anderer Lehrplan; wie läuft es in BU und Werken? Braucht sie dort auch besondere Unterstützung?

Wie ist der Einstieg gelungen?
Großes Glück mit der Zusammensetzung der Klasse! Wie sehr merkt man, welche Kinder Integrationskinder sind? Fällt nicht auf.

Zu Beginn war es in M gut / jetzt wird's kompliziert.

Sehr gute Mitarbeit, toll, auf MS Niveau. Sozial kompetent. Abstand zur Lerngruppe? Inhaltlich dabei, aber das Tempo!


** Noah Frey
Könnte eine Klasse wiederholen, soll Abschluss haben. Aber er ist in M in der vierten Stufe - und hat dann keinen Abschluss? Mit einer Prüfung? Damit er aufsteigen könnte?

D und M (4. ASO); kommt nur mit, wenn IL dabei ist - inhaltlich geht es, aber das Tempo! Sollte der IL Gas zu geben, kommt Noah ev. mit, aber verdaut hat er den Inhalt nicht.

Mirjam und Noah: Arbeitshaltung ist großartig, fühlen sich wohl. 

Wirkt manchmal müde? Nichts bemerkbar.


** Kainhofer Mirjam
ist MS Lehrplan / eher Verhalten.

Verhalten? Ankunft mit einem Unfall. Sie wollte an der Hand in die Kirche gehen und zurück. Zu Beginn: erst seit dieser Woche: "Mit ist fad, mag nicht!" Ist eigentlich: "Mir geht es nicht gut!"

Regelmäßige Medikamenteneinnahme? Es war diese Woche schlechter; Umstellung (Medikament führt zu weniger Essen); Arzt ansprechen: Dr. Flucher, ...

Ritalin / Concerta wirken verschieden auch mit Pubertät. Extrawürste sind bei ihr nicht gut. Wechsel? wichtige Rückmeldung; benötigt klare Struktur und sehr klare Anweisungen. Wo sind Geländer zum Anhalten / Sicherheit?

Viel Jause, weil / deshalb kein Medikament.

Ist wie Pipi Langstrumpf

Motorische Unruhe; (ADHS)

Für alle Kinder das gleiche - werde nicht allen gerecht. Sie spürt sich nicht so ... 

Themen sind lösbar.

Kontakt mit Mutter? M. soll nicht Richtung Extrawürste abbiegen; für sie gelten die gleichen Rechte für alle. ADHS. Hm, aber eigentlich dürfen nicht für alle Rechte wie für andere gelten, deshalb hat sie ja den SE.

Z.B. Verhaltensnote? Kann kein SZ haben. Von den Klassenregeln können wir mit Mirjam zB nur zwei Regeln versuchen umzusetzen.

Ihre Stärken positiv nutzen? zB sucht sie Aufmerksamkeit der Anderen. Klassendienste? Lernschiene? eine andere Schülerin unterstützen?

Gruppengröße, Form der MS, Teil einer größeren Gruppen und kann nicht immer heraus stechen.

Lernziel: kann andere was erklären; aber auch das Miteinander; Selbstreflexion; ich steche nicht heraus. Erfahrung: Grenzen anderer nicht respektieren, erfahre Ablehnung. Wie schütze ich die eigenen Körpergrenzen?

Sitzordnung - ändern. Mirjam ganz vorne. 


