#+title:      A Klasse 2025-29 Seekirchen
#+date:       [2024-09-08 So 21:40]
#+filetags:   :1a:sk:
#+identifier: 20240908T214000
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/1a Seekirchen.html

* Jahresplanung

[[denote:20240719T125948][Zeit für Religion 01]]

#+BEGIN: denote-links :regexp "_01_welt" :not-regexp nil :excluded-dirs-regexp "Mattsee" :sort-by-component nil :reverse-sort nil :id-only nil :include-date nil
- [[denote:20250906T002625][Feste feiern]]
- [[denote:20250906T002644][Hurra, wir feiern ein Fest!]]
- [[denote:20250906T002654][Im Rhythmus der Zeit]]
- [[denote:20250906T002704][Die Festkreise]]
- [[denote:20250906T002714][Maria, eine mutige Frau]]
- [[denote:20250906T002725][Weihnachtsspecial "Fürchtet euch nicht!"]]
#+END:


* Notizen, Tasks, Termine

* Stundenplanung

** Leben in Freiheit

Was ist Freiheit?

Schulpflicht - ein Zwang? Kann vor allem von den Kindern so erlebt werden. Doch was ist die Alternative? Wer passt auf euch auf, wenn ihr Zuhause seid? Wir wollen lieber mit gebildeten Bürgern zusammenleben. Vermittlung von Wissen und das Erlernen vom Zusammenleben in einer Gesellschaft.  Und - sind wir uns ehrlich: ohne Zwang geht vieles nicht. Homeschooling mag nett klingen - aber aus eigener Erfahrung (Corona): der Lernertrag ist minimal - und v.a. haben die Schüler darunter am meisten gelitten; weil sie ihre Freunde nicht in der Schule getroffen haben. Und Unterricht geschieht im Miteinander.

Die Schulpflicht ist der Weg, durch den die Kinder ihr Recht auf Bildung durchsetzen. Man könnte auch eine Bildungspflicht einführen. Mit Überprüfung: wer am Ende des Schuljahres alles kann, darf heim zu den Eltern. Wer nicht, ab in die Schule.

Wer stört - raus. Ich habe als Lehrer ein Recht darauf, ungestört zu unterrichten; und die Schüler haben ein Recht darauf, in Ruhe lernen zu können. Wer ist nicht schafft, sich 50 Minuten zu konzentrieren - raus. Der muss sich eben einen anderen Bildungsweg suchen. 

"Schulpflicht ist eine Pflicht der Eltern, die Kinder beschulen zu lassen. Für die Kinder ist es die Durchsetzung ihres Rechts auf Bildung. Wurde historisch eingeführt, um der Kinderarbeit beizukommen und zeigt sich noch heute in den Maßnahmen zur Durchsetzung der Schulpflicht, die ja vor allem die Eltern treffen (Bußgeld usw.). Klar ist das nicht unproblematisch, da das Recht der Kinder von ihnen als Zwang erlebt werden kann, aber diesen Widerspruch muss das Kind und die Schule aushalten.

Schulunlust bei Schüler:innen hat verschiedenste Gründe; einige liegen im Schulsystem, das den Kindern nicht immer das bieten kann, was sie bräuchten und demotivierende Erlebnisse schafft, andere liegen im Elternhaus, der sozialen Situation, psychischen Erkrankungen und nicht zuletzt einfach in Entwicklungsprozessen. Wie wir als Lehrer:innen im rigiden Schulsystem hierauf reagieren müssen, ist fallabhängig und nicht pauschal zu beantworten. "

"Was für ein Schmarrn. Ohne einen gewissen Zwang und Druck würden die wenigsten Kinder und Jugendlichen überhaupt die Schule besuchen, weil man schlichtweg andere Sachen zu dieser Zeit im Kopf hat. Da steht das Thema Bildung an letzter Stelle der Prioritäten. Bestes Beispiel hierfür war dieser Bullshit "Homeschooling".

Das Bildungssystem gehört dringend wieder reformiert, aber schon seit Ewigkeiten. Eine Abschaffung der Schulpflicht sollte dabei aber kategorisch ausgeschlossen werden. "

"Was Hänschen nicht lernt.... Es wäre ja noch schöner wenn Kids ihre unberechenbaren volatile Launen zur Legitimation für ihre Lernverweigerung instrumentalisieren dürften. Wenn sie sich jetzt der Schule verweigern, wird's ihnen das Leben später heimzahlen. Weil ihnen der erforderliche Weitblick für diese Erkenntnis fehlt, wird ihnen die Schule eben aufgezwungen. Und das ist auch gut so. Erst sehr viel später werden sie das einsehen und auch dafür dankbar sein. "

** Jesus erscheint seinen Jüngern (Joh 20)

"Der Friede sei mit euch!"

Der "ungläubige" Thomas. 

** Das Leben der Urchristen

** Sakramente / Taufe

* Reflexionen

** Dröscher Sonja

** Falger Maximilian

** Hinterleitner Valerie

** Kühleitner Lukas

** Mayr Luis
 
** Nöbauer Tobias
 
** Papp Csenge
 
** Sammer Maximilian

** Selimi Alina

** Stein Mira

** Strasser Simon

** Unger Manue

** Wagner Elena

** Winterreiter Michael

** Wuppinger Sophie

