#+title:      Neuer Vorwurf
#+date:       [2024-10-15 Di 08:49]
#+filetags:   :memo:
#+identifier: 20241015T084956

* Worum geht es?
Ich kam heute in die Schule und musste gleich zu Gabi. Es gibt einen neuen Vorwurf: ich hätte die gesamte Klasse / Schüler (2a)  als "dumm" bezeichnet. Das wäre in der gestrigen Stunde (Mo, 14.10.2024, 10:30-11:20, Lernschiene) vorgefallen. Ich kann mich nicht daran erinnern, dass ich dies je gesagt hätte. Ich weiß aber sehr genau, dass Christian und Daniel die gesamte Stunde ziemlich laut und unruhig waren.

Einer der beiden hat Physik gemacht und dabei zwei Batterien (eine große 4,5V Block Batterie und eine 1,5V AA Batterie) mit einander verbunden. Natürlich wurde die kleinere AA Batterie sehr heiß und begann sogar zu schmelzen. Der andere machte Englisch, mit einer mehr als unleserlichen Handschrift und störte dabei andere Schüler. Zumindest war er nicht sorgfältig bei der Arbeit. Ich konnte keinen einzigen Satz seiner Schrift entziffern.

Vielleicht hätte ich gesagt, dass man nicht zwei Batterien miteinander verbinden soll - dazu gibt es keinen einzigen Auftrag im Lernjob. Das sei gefährlich und ein dummes Verhalten, aber niemals hätte ich Schüler als dumm bezeichnet. Und Marlene war davon überhaupt nicht betroffen. Warum musste sich dann die Mutter von Marlene beschweren? Weil Marlene davon Zuhause erzählt hat; und wahrscheinlich hat sie von Daniel und Christian nichts erzählt. 

Der KV (Lena) spricht heute mit der Klasse.

* Wie lange noch?
Ich weiß schon nimmer, was ich noch sagen darf, was mir dann nicht im Mund umgedreht wird. Vor allem, wenn ich in Klassen bin, die wegen ihres Verhaltens "gefürchtet" sind.

Warum tue ich mir das noch an? Spaß und Freude macht mir meine Arbeit schon seit der Ankunft an der Schule nicht mehr. Es ist wie ein Kampf gegen Windmühlen.

Es bleibt mir nichts anderes übrig, als mich wieder für etwas zu entschuldigen, das ich nicht gesagt oder getan habe.

Ich bin in einer ziemlichen Zwickmühle, da ich weiß, wie sehr Gabi hinter mir steht. Und auf der anderen Seite wird mir vieles im Mund umgedreht und dadurch jeder Unterricht beinahe unmöglich gemacht. Jetzt aufgeben würde als "Sieg" meiner "Feinde" gesehen. Und einer finsteren Macht, die mich hier nicht haben will.



