#+title:      B Klasse 2023-27 Seekirchen
#+date:       [2024-09-08 So 21:43]
#+filetags:   :3b:sk:
#+identifier: 20240908T214359
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/3b Seekirchen.html

* Jahresplanung

[[denote:20240709T110253][Zeit für Religion 03]]

* Notizen, Tasks, Termine


* Stundenplanung

** Jesus sagt: "Ich bin ..."

- Ich bin das Brot des Lebens. (Joh 6,36) :: Jesus stillt den geistlichen Hunger und schenkt ewiges Leben. „Brot“ (6,35.52) nimmt nicht nur die „wunderbare Brotvermehrung“, d.h. die Speisung des Gottesvolkes mit den überreichen Lebensgaben Gottes auf (6,1-15), sondern auch die Brotrede, die beim Hunger des Volkes beginnt und über das Manna (6,49) bei der Eucharistie endet (6,52-58). Jesus gibt nicht nur etwas, sondern sich selbst - zum Leben der Welt.

- Ich bin das Licht der Welt. (Joh 8,12) :: Er bringt Wahrheit, Orientierung und vertreibt geistliche Finsternis. „Licht“ (8,12) bereitet nicht nur die Offenbarungsrede über die Blindheit des Unglaubens wie der Sünde und die Helligkeit des Glaubens wie der Liebe vor (8,12-59), sondern auch das Wunder der Heilung des Blindgeborenen (Joh 9). Jesus stößt diejenigen, die die Finsternis mehr lieben als das Licht (3,19; vgl. 1,5), nicht in die absolute Dunkelheit zurück, sondern spendet ihnen das Lebens-Licht Gottes.

- Ehe Abraham war, Ich Bin. (8,58)

- Ich bin die Tür. (Joh 10,7.9) :: Er ist der einzige Zugang zum Heil und zu Gott.
- Ich bin der Gute Hirte. (Joh 10,11) :: Er sorgt für seine Schafe, beschützt sie und gibt sein Leben für sie. "Tür" und "Hirte" (10,7.9.11) ist Jesus als derjenige, der Juden wie Heiden das Tor zum Reich Gottes öffnet und ihnen seine Gemeinschaft schenkt. Er öffnet nicht nur die Tür, sondern ist diese Tür, weil er das Heil nicht nur zeigt, sondern bringt.

- Ich bin die Auferstehung und das Leben. (Joh 11,25) :: Er überwindet den Tod und schenkt ewiges Leben. „Auferstehung“ und „Leben“ (11,25) ist Jesus als derjenige, der Lazarus aus dem Grabe holt und damit nicht nur die endzeitliche Auferstehung der Toten antezipiert, sondern die Gegenwart des Heiles mitten im Leben der Glaubenden verheißt: Der Tod hat schon jetzt keine Macht mehr über sie, weil Jesus die Glaubenden und Liebenden auf die Seite des Lebens zieht.

- Ich bin der Weg, die Wahrheit und das Leben. (Joh 14,6) :: Er ist der direkte Weg zum Vater. „Weg“ (14,6) ist Jesus als derjenige, der seine irdische Sendung durch den Weg ans Kreuz und über das Kreuz durch seinen Hinübergang zum Vater vollendet (vgl. 13,1f). Als „Weg“ ist Jesus „Wahrheit“, weil er nicht nur mit seinen Worten, sondern mit seinem ganzen Lebens-Geschick Zeugnis ablegt von der Liebe Gottes; als „Weg“ ist Jesus Leben, weil er zum Vater geht, um die Jünger durch seinen Tod und seiner Auferstehung Anteil nehmen zu lassen an jener Liebe zwischen dem Vater und dem Sohn, die zur Sendung Jesu geführt hat (3,16) und alles Heil in sich birgt

- Ich bin der Weinstock, ihr seid die Reben. (Joh 15,1.5) :: Er ist die Quelle der Lebenskraft, mit der die Gläubigen verbunden bleiben müssen. „Weinstock“ (15,1) ist Jesus als derjenige, der in Gemeinschaft mit den Jüngern, seinen „Freunden“ lebt (15,1); so wenig die Jünger, losgelöst von Jesus irgend etwas tun können, so sehr gibt Jesus ihnen die Lebenskraft, die sie brauchen.



* Reflexionen

** Bauböck Jonas

** Bosin Valentin

** Breckner Mona

** Clausen Jonas

** Enzinger Sophia

** Gappmaier Pia

** Gerngross Eva

** Gollackner Hanna

** Gschwandtner Johannes

** Hofer Nico

** Idris Dalia

** Kessler Fabio

** Költringer Amelie

** Krempler Dominik

** Laimer Raphael

** Reichl Verena

** Roth Enna

** Schober Luisa

** Strohbichler Noah

** Thurner Maximilian

** Wagner Jasmin

** Wassermann Sophia

** Wieder Leonhard

** Wimmer Antonia

** Wirthenstätter Samuel

