#+title:      Islam
#+date:       [2024-11-07 Do 09:45]
#+filetags:   :religion:
#+identifier: 20241107T094520

* Mohammed

* Die fünf Säulen

* Die Moschee

* Das Gebet

* Heilige Orte

* Symbole, Bräuche, Feste

* Lüge, Verstellung, etc

[[https://www.islaminstitut.de/2011/fatwa-zu-verschiedenen-arten-der-erlaubten-luege-im-islam/]]

Isabelle hat mir schon öfters gesagt, dass Lügen im Islam keine Sünde sei. Ich hab geglaubt, wollte es nun genau wissen und habe auf der obigen Internetseite nachgeschaut. Mir verschlägt es die Sprache und mir gehen so einige Lichter auf. Ich verstehe nun den Anspruch Jesu besser.

#+begin_quote
Allah sagte über die Vorbeugung: ‚Die Gläubigen sollen sich nicht Ungläubige zu Freunden nehmen anstelle der Gläubigen – und wer das tut, der hat nichts mehr mit Allah zu tun – es sei denn, dass ihr euch vorsichtig vor ihnen hütet.‘ (Sure 3,28).

Abu ad-Darda sagte: ‚Wir [Muslime] lächeln Menschen an, während wir diese im Herzen [innerlich] verfluchen. Das ist die Bedeutung der Rücksichtsnahme (oder Verstellung) [arab. al-mudara].‘
#+end_quote

Schließlich folgender Abschnitt zum Thema "Lüge":

#+begin_quote
Die Lüge [arab. al-kadhib]: Es ist bekannt, dass das Lügen [im Islam] verboten ist. Es wird jedoch in Fällen erlaubt, die einige muslimische Gelehrte gemäß der authentischen Überlieferungen definiert haben, um einen Vorteil zu erlangen: ‚Man darf im Krieg lügen, denn der Krieg ist ein Betrug. Man darf lügen, um Menschen miteinander zu versöhnen. Ein Ehepaar darf sich gegenseitig belügen, z. B. in Sachen der Liebe, um das weitere Zusammenleben zu ermöglichen.‘ Einige muslimische Gelehrte erlaubten das Lügen über diese [genannten drei Fälle] hinaus, und zwar, wenn man nur durch Lüge sein Ziel erreichen kann. Allerdings darf das Lügen hier keinem Menschen Schaden zufügen. Diese [Gelehrten] erlauben das Lügen auch, um einen Menschen vor etwas Bösem zu bewahren. Z. B. hat Allahs Prophet – Allahs Segen und Heil seien auf ihm – den Mördern von Ka’b b. al-Ashraf erlaubt, sagen zu können, was sie wollten. Auch Ibn Ilat hat die Einwohner Mekkas belogen [mit der Erlaubnis Muhammads], um an ihr Geld kommen zu können.“
#+end_quote

* Fragen
Deshalb stellen sich mir Fragen: wie kann es sein, dass man behauptet, Moslems und Christen (so wie Juden) würden an den selben Gott glauben. Bezüglich der Lüge teilen sich Juden und Christen die 10 Gebote. Juden wie Christen glauben wirklich an denselben Gott: gemeinsamer Glaube, gemeinsame Heilige Schrift, Jesus ist Jude, die ersten Apostel ebenso, Feste, Gebete, ... Aber wie steht es mit den Moslems?

Spontan denke ich eine Reflexion von Daniele Ganser, der seinen eigenen Vater damit konfrontiert hat: "Papa, es sind vor allem christliche Länder, die weltweit Kriege begonnen haben. Wie geht das mit dem Gebot zusammen: `Du sollst nicht töten'?" Für Hr. Ganser wird das Christentum damit komplett unglaubwürdig. Dass der Krieg ein Skandal ist - keine Frage. Die Tatsache, dass vor allem christliche Länder die letzten Kriege begonnen haben und dies ein Skandal darstellt - ja. Ebenso, dass auch muslimische Länder ihre Nachbarländer überfallen, sie erobern und sich der Islam sehr oft vor allem durch kriegerische Gewalt ausgebreitet hat.

