#+title:      Gespräch mit Gabriele
#+date:       [2024-11-06 Mi 10:39]
#+filetags:   :memo:
#+identifier: 20241106T103909

* Email
Gabi hat ein sehr positives Email an die Fachinspektorin geschickt; Marie-Luise wird demnächst zu Besuch kommen.

* Rückmeldung von Hanni
Hanni hat für mich während meiner Krankheit suppliert; da hätten die Schüler gesagt, sie würden in meiner Stunde va HÜ machen. Das sollte eigentlich nicht passieren. Okay - dann werde ich das in Zukunft unterbinden. Das ist weiterhin nicht so schlimm, eine Kleinigkeit, die sich rasch und ohne Probleme beenden lässt. Die Schüler sind mir ja eigentlich recht dankbar, dass ich ihnen hier entgegen komme. Aber okay ist es eigentlich nicht. Ich denke da aber schon an die (zahlreichen) Schüler der 3b, die nicht in den RU gehen und während dieser Zeit ihre HÜ erledigen.

Und ich werde (habe) Hanni bitten (gebeten), dass sie mir bei der Vorbereitung der Lernschiene hilft. Am Dienstag bleibt sie länger an der Schule (diese Woche war sie bis 15h00 hier). Was sich für mich nicht ausgeht, da ich bis 14h50 bleibe. Naja - ich hab mir vorgenommen, einige Mappen mit nach Hause zu nehmen und diese Mappen bei Papa im Büro zu vervielfältigen und eventuell auch einzuscannen (das geht auch Zuhause). 

* Gedanken
Was mich darin etwas erstaunt: die Kollegin geht direkt zur Direktorin. Warum nicht zuerst zu mir? Das hat bis jetzt nur Teresa (KV der 4c) oder Florian (KV der 1c) gemacht. In Golling kam so gut wie nie ein L zu mir. Dort habe ich unterrichtet und gut war es. Eventuell noch Erwin oder Manuela besprachen sich mit mir, aber auch nur, um mir wegen ihrer Klasse zu helfen. Sonst hat dort - so denke ich - "jeder sein Ding gemacht". Der KV der jetzigen 4a kam zu mir - Name fällt mir im Moment nicht ein.

Wie würde ich mich verhalten, wenn Schüler sich bei mir über einen Kollegen "beschweren" würden? Ich würde wohl eher direkt zum Kollegen gehen - wenn überhaupt. Zuerst einmal würde ich meinen Kollegen vor den Schülern verteidigen, kein schlechtes Wort über ihn kommen lassen. Und die Schüler vielmehr ermutigen, sich direkt an den betreffenden Kollegen zu wenden (oder max. an den KV).
