#+title:      B Klasse 2022-26 Seekirchen
#+date:       [2024-09-08 So 21:42]
#+filetags:   :4b:sk:
#+identifier: 20240908T214223
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/4b Seekirchen.html

* Jahresplanung

[[denote:20240719T131544][Zeit für Religion 04]]

* Notizen, Tasks, Termine


* Stundenplanung

** Jesus und die Samariterin am Jakobsbrunnen

(Episode aus The Chosen - hoffentlich klappt das Internet in der Klasse!)

Joh 4 lesen.  + The Chosen Staffel 1 Episode 8

(Staffel 5 online verfügbar!)

Lebendiges Wasser - Gottes Liebe, Gottes Geist; Anbetung in Geist und Wahrheit.

Die große Frage - was erwartest du dir von Gott?
"Was willst du, dass ich dir tue?" - Frage von Jesus an Bartimäus.

Schüler sollen sich mit dieser Frage auseinandersetzen, sie an sich heran lassen. Und ihre Erwartungen formulieren. Aufschreiben. Die "Gefahr" ist, dass die Kinder sagen "nix!" - und meinen, damit den Auftrag erfüllt zu haben; "Können wir jetzt Kahoot spielen?" - So leicht lasse ich die Kinder nicht aus ihrer "Pflicht". Wer nichts von Gott erwartet, wird auch nichts von Gott erhalten. So wie der ältere Sohn im Gleichnis vom verlorenen Sohn. Er bleibt in seiner Welt der Gerechtigkeit; fragt nach nichts. Und ist dabei genauso unglücklich wie sein jüngerer Bruder als der die Schweine hütete.

Wie viel schöner ist doch das Leben - wenn du dich von Gottes Liebe berühren lässt?
 

** Zehn Gebote

[[https://katholisch.de/glaube/unsere-bibel/wie-kann-ich-christlich-leben]]

PPP fertig stellen

Arbeitsmaterial?
[[https://www.die10besten.ch/]]

Z.B. Gefangener einer Marke (Kleidung) zu sein?

"... kein anderer Gott neben mir!" - Arbeit, Geld, Macht, Gesundheit, Erfolg, Sport, Handy, Laptop, PC, Konsole, ... ach ja und dann gibt es nicht Kirche, Jesus, Glaube.

Berg Sinai - Bund zuerst, die Liebe Gottes zu uns - dann die 10 Gebote; das goldene Kalb - als Folge: mehr Gebote und Gesetze (wie will Gott verehrt werden (Opfer)?). Diese Gesetze waren vor dem goldenen Kalb nicht geplant.

Goldenes Kalb: so ähnlich wie Sündenfall (hier geht es nicht darum, gutes von schlechtem Handeln zu unterscheiden; sondern um die Autorität, selbst festzulegen, was Gut und Böse ist. Das steht nur Gott zu. Der Mensch will selbst Gott sein.)

Hier - goldenes Kalb: Moses ist 40 Tage weg auf dem Berg; das Volk wird ungeduldig, unsicher; ist es durch Ägypten gewohnt, dass Götter bildhaft dargestellt werden. "Das ist dein Gott..." - den unsichtbaren Gott sichtbar machen, verfügbar, Ihn kontrollieren wollen, reduzieren auf unsere Vorstellung, ... seit diesem Zeitpunkt ist die Beziehung zwischen Gott und dem Volk angespannt.

Volk Israel war über Generationen ein Volk von Sklaven. Sie wissen nicht, wie man als Volk in FREIHET lebt. Muss es erst lernen. Durch eine lange Zeit, durch Gesetze, Regeln, ...


** The Chosen
Staffel 4, Episode 2 "Bekenntnisse" - Versöhnung zwischen Simon Petrus und Matthäus

* Reflexionen

** Wie vorgehen?
:PROPERTIES:
:CAPTURED: [2025-11-03 Mo 16:49]
:DESCRIPTION: [[file:~/Documents/notes/20240908T214223--b-klasse-2022-26-seekirchen__4b_sk.org::*Stundenplanung][Stundenplanung]]
:END:
Ich bin ehrlich gesagt etwas ratlos. Die Schüler sind ziemlich schwierig - und das laut der Putzfrau schon seit der ersten Klasse. Sehr oft kommt das Argument: "Das ist eine Sportklasse. Da haben die Schüler und auch die Eltern ein sehr hohes Selbstbewusstsein, denken sie seien so toll. Und benehmen sich leider sehr daneben." 

Ich habe die Klasse selbständig arbeiten lassen, was nur bedingt geklappt hat. Die Kids schreien wie Affen, grunzen wie Schweine, es fliegen Patschen, Schuhe, ... Wenn mal eine Wasserflasche umfällt, wird meterweise Papier verwendet (was natürlich sehr viel Lärme macht). Wenn man da als Lehrer laut wird, gießt das nur Öl ins Feuer. Danach imitieren die Schüler den Lehrer, äffen ihn nach. Also sag ich oft nichts. 

Ich denke mir eben: "Ich hab diese Klasse eh nur ein Jahr, dann sind sie weg!" Was soll ich da noch ändern? Meine Kollegin, die am Ende des Jahres in Pension geht, hat diese Klasse sehr gerne abgegeben (wie alle anderen Sportklassen - 2b und 3b - auch).

Soll ich mit ihnen manchmal eine Lernstunde vor einer SA oder Test einfügen?

** Burschen 2. Reihe (Wand)
Überschwemmung auf Tisch, dauert ewig, bis Tisch trocken ist. Kein Unterricht möglich...

** Adhero Savio

** Bamberger Anna

** Ebner Florian

** Eibl Iris

** Günther Markus

** Hager Chiara

** Handlechner Moritz

** Hofer Laura

** Lechner Jonas

** Mandl Leona

** Mayr David

** Mösl Noah

** Mühlbacher Lisa

** Müller Sebastian

** Neukamp Philipp

** Öhlböck Simon

** Petsche Anna

** Prossinger Samuel

** Reiter Sebastian

** Reitsamer Dominik

** Rinnerthaler Emily

** Scheipl Hannah

** Schernthanner Philip

** Stark Jana

** Strohmaier Luisa
