#+title:      B Klasse 2022-26 Seekirchen
#+date:       [2024-09-08 So 21:42]
#+filetags:   :4b:sk:
#+identifier: 20240908T214223
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/4b Seekirchen.html

* Jahresplanung

[[denote:20240719T131544][Zeit für Religion 04]]

* Notizen, Tasks, Termine


* Stundenplanung

** Das Leben Jesu

"Siehe, ich mache alles neu!" (Offb)

- Taufe Jesu (Bekehrung, ...)
- Versuchung Jesu 
- Bergpredigt
- Wunder, ...

** Bibel lesen
Da die Lesekompetenz an der Schule ziemlich schlecht ist, sollen wir im Unterricht vermehrt lesen. Ich werde mit den Schülern in der Bibel lesen. Je nach Klasse werde ich die Schüler fragen, was sie lesen wollen. Z.B. habe ich in der 1a aus dem AT gelesen (Arche Noach).


* Reflexionen

** Wie vorgehen?
:PROPERTIES:
:CAPTURED: [2025-11-03 Mo 16:49]
:DESCRIPTION: [[file:~/Documents/notes/20240908T214223--b-klasse-2022-26-seekirchen__4b_sk.org::*Stundenplanung][Stundenplanung]]
:END:
Ich bin ehrlich gesagt etwas ratlos. Die Schüler sind ziemlich schwierig - und das laut der Putzfrau schon seit der ersten Klasse. Sehr oft kommt das Argument: "Das ist eine Sportklasse. Da haben die Schüler und auch die Eltern ein sehr hohes Selbstbewusstsein, denken sie seien so toll. Und benehmen sich leider sehr daneben." 

Ich habe die Klasse selbständig arbeiten lassen, was nur bedingt geklappt hat. Die Kids schreien wie Affen, grunzen wie Schweine, es fliegen Patschen, Schuhe, ... Wenn mal eine Wasserflasche umfällt, wird meterweise Papier verwendet (was natürlich sehr viel Lärme macht). Wenn man da als Lehrer laut wird, gießt das nur Öl ins Feuer. Danach imitieren die Schüler den Lehrer, äffen ihn nach. Also sag ich oft nichts. 

Ich denke mir eben: "Ich hab diese Klasse eh nur ein Jahr, dann sind sie weg!" Was soll ich da noch ändern? Meine Kollegin, die am Ende des Jahres in Pension geht, hat diese Klasse sehr gerne abgegeben (wie alle anderen Sportklassen - 2b und 3b - auch).

Soll ich mit ihnen manchmal eine Lernstunde vor einer SA oder Test einfügen?

** Burschen 2. Reihe (Wand)
Überschwemmung auf Tisch, dauert ewig, bis Tisch trocken ist. Kein Unterricht möglich...

** Adhero Savio

** Bamberger Anna

** Ebner Florian

** Eibl Iris

** Günther Markus

** Hager Chiara

** Handlechner Moritz

** Hofer Laura

** Lechner Jonas

** Mandl Leona

** Mayr David

** Mösl Noah

** Mühlbacher Lisa

** Müller Sebastian

** Neukamp Philipp

** Öhlböck Simon

** Petsche Anna

** Prossinger Samuel

** Reiter Sebastian

** Reitsamer Dominik

** Rinnerthaler Emily

** Scheipl Hannah

** Schernthanner Philip

** Stark Jana

** Strohmaier Luisa
