#+title:      Kommentar Mk 10,46-52
#+date:       [2024-11-30 Sa 23:04]
#+filetags:   :bibel:schule:
#+identifier: 20241130T230436

* Was geschieht?
Jesus kommt anch Jericho; sie verlassen die Stadt. Am Straßenrand sitzt ein blinder Bettler, Bartimäus. Er schriet: "Jesus, Sohn Davids, erbarme dich meiner!" Die Menge will, dass er schweigt. Jesus lässt ihn rufen. Bartimäus läuft zu Jesus. "Was soll ich dir tun?" - "Ich will sehen!" - Jesus heilt ihn.

* Wer handelt wo, wann, wie und warum?

** Jesus
Er geht von Jericho hinauf nach Jerusalem (Passion). Sieht Bartimäus, geht zuerst vorüber. Lässt ihn rufen. Verhält sich dem Blinden gegenüber wie ein Sklave "Was soll ich dir tun?" - Stellt den Glauben bei Bartimäus fest - er ist geheilt. Akzeptiert, dass der Geheilte ihm nachfolgt.


** Bartimäus
Ein gläubiger Jude "Sohn Davids...!"; blind; hört von Jesus, glaubt, dass in Jesus Gott nahe kommt. Er glaubt, dass Jesus sich ihm erbarmen wird, ihn sehend macht.


** Die Jünger
Sie begleiten Jesus.

** Die Menge
Weist Bartmäus zuerst schroff ab - er stört? Dann macht sie Bartimäus Mut.

* Botschaft der Geschichte?
Höhepunkt der Wunder bei Markus:
- Nur hier hat der Kranke einen Namen.
- Nur hier darf der Geheilte Jesus nachfolgen.
- Krankheit ist eine Unordnung.
- Glaube ist nicht nur ein subjektives Vertrauen; sondern objektive Teilhabe an der lebendig ordnenden Festigkeit Gottes.
- Nur wenn der Christ von sich selbst weg auf Jesus blickt, wird er erlöst.
- So heilt der Glaube: im Blick auf Gott.


* "Dein Glaube hat dich gerettet."
Jesus heilt den Blinden nicht durch direkte Berührung, sondern dessen eigener Glaube. Jesus erbarmt sich -  das ist der Glaube des Bartimäus. Der Blinde glaubt an Gott, der ihm in Jesus nahekommt. Jesus ist der Anlass für diesen Glauben. In dem Blinden wird durch Jesus eine Kraft geweckt, die ihn wieder ganz macht.

Bartimäus steht auch für die späteren Jünger, die zwar von Jesus hören, ihn aber nicht gesehen haben. Im Glauben werden sie sehend.


* Was ist die befreiende Botschaft dieser Geschichte?
- Krankheit ist eine Unordnung.
- Glaube ist nicht nur ein subjektives Vertrauen; sondern objektive Teilhabe an der lebendig ordnenden Festigkeit Gottes.
- Nur wenn der Christ von sich selbst weg auf Jesus blickt, wird er erlöst.
- So heilt der Glaube: im Blick auf Gott.
- "Rabbuni" ... Aramäisch, eine heilige Sprache (auch der Engel). Bartimäus will durch diese Anrede jeden Einfluss der Dämonen ausschließen.
- ?
