#+title:      Vieles hat Leben in sich
#+date:       [2024-09-09 Mo 21:52]
#+filetags:   :03:gemeinschaft:
#+identifier: 20240909T215212

* Comic

** Arbeitsauftrag 1
Dieser Arbeitsauftrag bezieht sich auf den Comic, der das Thema dieser Seite „Über das Leben nachdenken“ aufgreift und zum Nachdenken anregen soll. Es soll darauf geachtet werden, dass den Gedanken der Schüler*innen genügend Freiraum gegeben wird und sie zum Philosophieren ermutigen.

** Arbeitsauftrag 2
Bei diesem Arbeitsauftrag ist ein Vorwissen (Band 1, Seite 32-33) erforderlich, denn die Sprechblasen greifen die Thematik von „Guten Gedanken und harten Fakten“ auf.

Gute Gedanken lassen sich nicht eindeutig beweisen und sind abhängig von den Umständen und Meinungen verschiedener Menschen.
Harte Fakten sind dagegen überprüfbare und beweisbare Tatsachen, die unabhängig von den Umständen und Meinungen der Menschen gültig sind.

Die Zuordnung der Sprechblasen könnte so aussehen:

Gute Gedanken (subjektiv):
 - Warum gibt es das Leben überhaupt?
 - Wer war der erste Mensch?
 - Ist es ein purer Zufall oder hat es einen Sinn, dass wir leben?
 - Warum lebe ich?

Harte Fakten (objektiv):
- Wie haben sich die unterschiedlichen Arten von Pflanzen und Tieren entwickelt?
- Seit wann gibt es Leben auf unserer Erde?
- Wie bin ich entstanden?

Könnten beiden zugeordnet werden – je nach Erklärungsansatz:
- Wann lebt etwas, wann nicht?
- Was ist der Ursprung allen Lebens?

** Arbeitsauftrag 3
Dieser Arbeitsauftrag soll individuell beantwortet werden. Allerdings wird es manchen Schülern schwer fallen zwei unterschiedliche Fragestellungen zum Thema „Leben“ zu finden.

** Arbeitsauftrag 4
Die Formulierung möglicher Antworten auf die Fragen, dürfte für die Schüler*innen der siebten Schulstufe nicht so schwer, die Zuordnung der Antworten in objektiv und subjektiv jedoch könnte für einige Schüler*innen sehr herausfordernd sein. Daher bietet sich bei diesem Arbeitsauftrag eine Gruppenarbeit als Methode an. Voraussetzung ist, dass die Begriffe „objektiv“ und „subjektiv“ für alle Schüler bekannt sind.

Objektiv:
Unabhängig von den Umständen und Meinungen der Menschen.
Subjektiv:
abhängig davon, was Menschen denken oder glauben.

* Vieles hat Leben in sich

** Arbeitsauftrag 1
In diesem Arbeitsauftrag wird das vernetzte Denken und der fächerübergreifende Unterricht gefördert.
Die Schüler*innen sollen das Wissen über „das Leben“ aus Biologie und Umweltkunde in eigenen Worten wiedergeben und somit einen Bezug zur religiösen Fragestellung dieses Themas herstellen.

Als Beispiele könnten genannt werden:
Herzschlag, Gehirn, Atmung,...

** Arbeitsauftrag 2
Bei diesem Arbeitsauftrag sind verschiedene Lösungen möglich. Die unterschiedliche Deutung der einzelnen Begriffe soll erneut die subjektiven „guten Gedanken“ des Themas sichtbar machen. Mögliche Zuordnungen der Begriffe könnte sein:

    1. Farbe:
    Mensch, Tier, Pflanze, Natur, Schöpfung, …
    2. Farbe:
    Geschichten, Bilder, Träume, …
    3. Farbe:
    Freundschaft, Gedanken, Computerspiele, …

Wichtiger Hinweis für die Schüler*innen ist, dass auch Wörter unbemalt bleiben oder mehrere Farben für einen Begriff gewählt werden dürfen.

** Arbeitsauftrag 3
Dieser Arbeitsauftrag bezieht sich auf die vorangegangene Aufgabenstellung.

Mögliche Wörter die unbemahlt bleiben könnten sind: das Gute/Böse, Himmel, Verstorbene, Stein

Werden die Schüler*innen hier zum Philosophieren angeregt, kann dieser Arbeitsauftrag stundenfüllend werden.

Eine mögliche Vertiefungsarbeit wäre, über die Begriffe zum Thema „Was hat Leben in sich“ zu philosophieren. Dazu sollten die Wörter auf Karten vorbereitet werden. Als Sozialform bietet sich ein Sesselkreis an in dessen Mitte am Boden die Wortkarten aufgelegt werden. Danach werden die Begriffe einzeln der Reihe nach im Plenum besprochen.

Der Anspruch sollte hierbei nicht sein alle Begriffe durchzuarbeiten, sondern die Schüler*innen zum Philosophieren ermutigen und deren Gedanken wertschätzend in der Klasse den Raum geben.

** Arbeitsauftrag 4
Bei diesem Arbeitsauftrag ist die persönliche Meinung der Schüler*innen gefragt. 
Auch mehrere Aussagen können für die Schüler*innen gleichzeitig richtig sein. Durch Impulsfragen kann kann sich dadurch eine philosophische Unterrichtseinheit ergeben.
