#+title:      Mit jedem redest du anders
#+date:       [2024-09-11 Mi 09:37]
#+filetags:   :02:gemeinschaft:
#+identifier: 20240911T093726

* Startseite

** Arbeitsauftrag 1
Bei diesem Arbeitsauftrag geht es um das Einfühlungsvermögen in die andere Person. Theo und Elena kommunizieren auf unterschiedliche Art und Weise. Für Elena reicht das „Daumenhoch“ als Bestätigung und Zustimmung Eis essen zu gehen. Theo aber würde dies gerne durch ausgesprochene Worte hören. Die Schüler*innen sollen erfahren, dass Kommunikation mehr als nur ausgesprochene Worte ist. Sie sollen achtsamer werden und auch nonverbale Kommunikation anhand von Gesten oder Mimik deuten lernen.
Einen Mehrwert würde es zusätzlich geben, wenn man hier auch Schüler*innen mit Beeinträchtigungen mitdenken würde. Bei manchen würde dann die eine oder andere Art der Kommunikation wegfallen (nicht sprechen können, Muskeln nicht bewegen können, …). Die Lehrkraft könnte auch die Diskussion in diese Richtung lenken, um möglichst vielschichtig in dieses Thema einsteigen zu können.

** Arbeitsauftrag 2
Dieser Arbeitsauftrag ist persönlich und individuell. Jede*r Schüler*in versteht etwas   anderes unter Kommunikation. Introvertierte werden eventuell nur wenig von sich preisgeben, während extrovertierte mehr von und über sich erzählen werden.

** Arbeitsauftrag 3
Auch dieser Arbeitsauftrag ist individuell und persönlich. Jede*r Schüler*in sollte sich mit der eigenen Kommunikation auseinandersetzen und sich bewusst machen, auf welche Art und Weise er*sie mit den Mitschülern*innen kommuniziert. In einem weiteren Schritt könnte man auch gemeinsam vergleichen und eventuelle Unterschiede und/oder Gemeinsamkeiten feststellen.

* Mit jedem redest du anders

** Arbeitsauftrag 1
Die Schüler*innen sollen erkennen, dass jede*r von uns in unterschiedlichsten Lebenssituationen unterschiedliche Sprachen (Wortwahl, Ton, Dialekt – Schriftsprache, …) verwendet. Das Gespräch kann auch dahin gelenkt werden, dass es durchaus wichtig ist, in verschiedenen Situationen unterschiedliche Sprechhaltungen einzunehmen.

** Arbeitsauftrag 2
Dieser Arbeitsauftrag zeigt Pauls Mutter in verschiedenen Situationen ihres Lebens:

    - Pauls Mutter als Verkäuferin :: Sie bedient ihre Kundschaft nahezu „überfreundlich“. Immerhin
      möchte sie den Rock auch verkaufen.
      
    - Pauls Mutter als Autofahrerin (in Eile) :: Wie viele Autofahrer*innen, die am Heimweg sind, ist
      Pauls Mutter nicht gerade freundlich. Im Schutz des eigenen Autos ist es auch leichter mit den
      anderen zu schimpfen – wenn diese es nicht hören. In den meisten Fällen ist bei einer Verkehrsüberlastung nicht ein einzelner Schuld daran. Sie möchte gerne, dass sie pünktlich nach Hause kommen.
      
    - Pauls Mutter als Mutter eines Kindergartenkindes :: Fürsorglich und liebend – wie Mütter dem
      Klischee entsprechend sein sollten, wenn sie ihrem Kind nach einem langen Arbeitstag begegnen.
      Ein wenig über die Sorgen des Kindes geplaudert und schon ist alles wieder ein klein wenig
      leichter.

    - Pauls Mutter als Mutter eines 12jährigen :: Sie bringt ihre Kritik direkt auf den Punkt, ohne
      Umschreibungen und ohne mit der Wimper zu zögern. Sie möchte Paul darauf hinweisen, dass die
      Unordnung in seinem Zimmer über ihre Toleranzgrenze hinausgeht und setzt klare Grenzen, was die
      Spielzeit am PC betrifft. Außerdem knüpft sie auch noch die Bedingung des Lernens daran.

** Arbeitsauftrag 3
Dieser Auftrag ist individuell zu beantworten. Den Schülern*innen soll aber bewusst werden, dass auch sie in verschiedene Rollen schlüpfen und sich dementsprechend verhalten und kommunizieren (mit der Familie, mit Lehrern*innen, mit Freunden*innen, …)
