#+title:      Oktober Konferenz
#+date:       [2024-10-23 Mi 13:08]
#+filetags:   :schule:
#+identifier: 20241023T130855

* Begrüßung

* Friedensbüro
- Resilienz
- Konflikt Kultur
- Mobbing

* Neubau der Schule
- Container 11.11.
- ab 16.12. beziehbar
- Vor weihnachten siedeln: Infrastruktur
- Klassen ab dem 7.1.
- EH (Kochen) in der SO
- ECDL 2: im EDV Raum der PTS
- Schulglocke in der Übergangszeit (in den Container)? Diskussion & Abstimmung
- In den Container gibt es keine Lautsprecher
- Dh. Lehrer / Aufsicht beendet Pause


* QMS
- Q-Handbuch
- IKM-Testungen
- 2.12. bis 20.01. Basismodule D,E,M (7./8. SS)
- Zyklusmodul D Zuhören 8. SS
- Reflexionsgespräche mit den Eltern
- Kinderschutzkonzept


* Elternabend
der 4. Klassen der VS; 20.11., 19H00
- Tanz, Musik, Chor
- verschiedene Schwerpunkte der Schule werden vorgestellt
- Sport
- Beurteilung
- IT
- Integrationsklasse


* Allfälliges
- Brandschutz ::
  Türen geschlossen! 
  Sammelplatz neu: Sportplatz / Schachlplatz
  Am Sammelplatz zwischen den Klassen abtrennen
  Es gibt zwei Methoden für die Evakuierung (Kontrolle der Klassen auf Vollständigkeit)
- Gesunde Jause ::
  Danke an alle LL; Frage - erst beim Läuten die Schüler gehen lassen? SuS kämen zu spät? (Andere dürfen schon? Die guten Sache  sind schon weg!) Abstimmung: am leichtesten wäre die Glocke. Jeder Schüler räumt ihre Teller weg (Teller und Löffel sind Biomüll)! Bitte anmelden, mit Name! Es haben schon Schüler anderen Schülern die Jause weggenommen. 
- Schulveranstaltungen ::
  Rundbrief (siehe Aushang); Keine privaten Konten für die Abwicklung von SV. Abrechnung erfolgt ausschließlich über das Schulkonto / Klassenkonto. Unterlagen und Vorlagen im öffentlichen Ordner unter "Schulveranstaltungen" gespeichert
- Lesemonat ::
  Mitte November bis Mitte Dezember
  KV kontrolliert die Listen und die Lektüre (keine Seitenzahlen notieren). Die Freude am lesen steht im Vordergrund, kein Leistungsdruck. Es muss jeder teilnehmen - Lehrer als Vorbild.
- Tag der Sbg Musikmittelschulen ::
  (14.11.) Flo;
- Erster Elternsprechtag ::
  (4.12.) Termine über SchoolFox. Intervalle 6min. Leibliches Wohl: 4b?
- Schubu Aktion ::
  Lizenzen bezahlt von LR Gutschi; Kostenfreies Material von SENECA und Canva (was ist das?)
- Vertragsänderungen ::
  werden erst im nächsten Monat abgerechnet; und im übernächsten Monat ausbezahlt.

