#+title:      Neues Buch von Jordan Peterson über Gott
#+date:       [2024-11-14 Do 15:37]
#+filetags:   :religion:
#+identifier: 20241114T153705

* Wie erleben wir?
Wir erleben nicht neutrale Fakten und bauen diese dann ein in eine narrative Struktur. Sondern unser Erleben hat bereits eine narrative Struktur. Z.B. unsere metaphorische Sprache bedingt schon, wie wir die Welt wahrnehmen.

Positiv: Peterson lässt einen Raum offen für den Literalsinn; in den 80er und 90er war Eugen Drewermann sehr bekannt, der die Bibel tiefenpsychologisch auslegte. Den Wortsinn hat er dabei (oft) negiert: z.B. gibt es nach Drewermann keine Wunder, keine tatsächliche Auferstehung Jesu, keine Jungfrauengeburt. Diese Thesen fanden sich z.B. im RU wieder. (Was nicht meine Lehre ist.)

* Über die Bibel
Gott handelt real in der Geschichte; Peterson erliegt knapp der Gnosis. 

* Ideen und Leib
Unsere Wahrnehmung der Welt ist sprachlich konstruiert. Wie wir sprechen bestimmt unser denken. Unser sprechen hat Auswirkung auf unseren Körper. Konzept "innen / außen" könnten wir nicht verstehen, wenn wir nicht einen Körper hätten, der ein innen und außen kennt. Oder das Konzept "oben unten", wenn wir uns nicht selbst in einem Raum bewegen würden, und vertikal ausgerichtet wären.

Wie sieht die Verbindung aus zwischen dem physiologisch-biologischen und dem kognitiven Bereich des Menschen (embodiment: cf. Wikipedia-Artikel [[https://de.wikipedia.org/wiki/Embodiment][Embodiment – Wikipedia]]). 
