#+title:      Eröffnungskonferenz
#+date:       [2024-09-09 Mo 10:34]
#+filetags:   :schule:
#+identifier: 20240909T103445

Ich bin sehr gut an dieser Schule aufgenommen worden.

* Begrüßung
Pause - 15min

Ab 1.10. kommt eine zusätzliche Kollegin: Christina Dullnig (BSP Mädchen)

Restliche offenen Stellen: Ausschreibung 16.09. (bis dahin keine MDLs)

* Danke
Für die tolle Jause
Stundenplanteam: Lydia, Alex, Thomas
Schulbücher: Thomas + Stephi
Eva + Christina:

Die neuen KVs ...

... und an alle.
 
* Persönliches
Jacqui für den Master
Ruhestände
Karenz

* Datenkontrolle
im Sokrates ...

* Krisenteam
Bitte in der Mappe nachschauen (bes. für uns Neue)

* Kustos:
Religion: Johanna Huber (heute nicht da) + ich (ausmachen)

* Schülerinnen:

Achtung
- unter Beobachtung: Hanan +

Integration:
- 1b: Frey Noah (D M), Miriam (D M), K Miriam (adhs, se)
- 2b: Marko, Emma, Philipp, Julian, Adisa
- 3b: Emil, Sebastian, Salomo
- 4b: Bernhard (auch in Reli), Bea, David, Celina
- ...

  Konferenz 1b ... 14h30


* S Zahlen
1a 20
1b 18
1c 25
...

* Klassenräume
1a in 4a
1b in 4b
1c in Matura Raum
1d in 4c

* Versäumnis
S die mehr als 2SW versäumen (ob am Stück oder insgesamt) und Mocsel Kinder sofort der Dir. melden. Dh wer viel fehlt - melden!

* RU Abmeldung
Keine Beeinflussung; einziger Grund: Gewissensgrund...
Nur in den ersten 5 Schultagen
Abmeldung gilt nur für ein Schuljahr; Widerruf ist jederzeit möglich.

Anmeldung als Freigegenstand und Benotung

1. Stunde RU - können S um halb 12 freihaben?


* Stundenplan
mit Sokrates vergleichen!
Kein Anrecht auf einen freien Tag;

Interessensfächer beginnen am 23.09.
Instrumentalfächer beginnen am 16.09.

KV Stunde: 1. Klassen, 2c, ...?

Kirche, Beginn 10h30: morgen Di; KVs mit ihren Klassen

RU ev.: Mi ungerade 8.+9. Stunde; RU orth.: jeden Fr 14:20-16:05; islamisch: jeden Fr 8.+9. Stunde

* Leistungsniveau
Einstufung der 6. Schulstufe bis zum 20.09.
3.+4. Klassen werden vom letzten Jahr übernommen
Kustos überprüfen Einstufung und tragen ein. (KVs auch?)

Einstufungskonferenz: 20.09. um 14:00

23.09.: Info an Eltern bzgl Einstufung

* Schulveranstaltungen
- schriftliche Bekanntgabe: 2 Wochen vorher; SL muss Begleitpersonen finden und genehmigen
- genauer Ablauf bis spätestens Mittwoch Mittag (Supplierung); Info an Eltern


* Pausenaufsicht
Lydia + Florian teilen ein

7:15-7:30 bis RK da ist; Aufsichten wirklich ernst nehmen + pünktlich!
Gangwechsel: S dürfen in der Pause Gang wechseln

* PH Fortbildung
Anmelden bis 15.09. - Jahreskonferenz!
Nachmeldung Dir. in CC mail: fortbildung@phsalzburg
15 UE / Schuljahr
erste Hilfe alle 5 Jahre
Friedensbüro - Schilf: "Mobbing Stoppen" 25.+26.09. 13:30 bis 18:00 - Verpflichtend!
Schikurs- und Schwimmbegleitung / Helferschein:

* Tablets:
kommen in der 3. SW
Schüler haben die Tablets eig. immer mit.
90 Euros

* Schulfreistellung
KV kann einen Tag, SL bis zu 5 Tage; BD darüber hinaus frei geben
2 Wochen vorher?

* Lehrmittelbeitrag
45 Euros (inkludiert: 3 Euro Bücherei; 15 Euro Werkbeitrag)
vierten Klassen: 30 Euros
JÖ+Topic: 24 Euro
[Krippe: 20 Euro (nur für Krippenbauer?)]

* Brandschutzordnung
unterschreiben

17.09. Räumungsübung (nicht an S weitergeben)

* Protokolle
bitte abgeben!

* C-Topf
PD - 23.+24. UE persönlich und schriftlich angeben
Wie ist das für RU? Fragen...

* Schulfreien Tage
schulautonom:
2.5.
30.5. nach Christi Himmelfahrt
heuer kein freier Tag nach Fronleichnam!
23.12. ist frei - vom Ministerium

* Parkscheine
Bitte verwenden!

* Pause

* Gesunde Jause
Eva plus Team: 2 Tage pro Woche "Gesunde Jause"
Vorstellung von Lisa

** Fortschritt
"Schule schafft Leben"; Zertifikat erarbeitet; erste Schule in Salzburg
Förderer der Gemeinde
Partner
Kühlschrank
Regal

** Update
Werbung, Flyer, Klassenforum
Verkauf: Di und Mi große Pause
Stempelkarte 10 Euro
Preisliste
Karaffen (mit Obst und Kräutern im Wasser) in den Klassen (KVs)? Glas in der Klasse ist etwas gefährlich? Eher nicht ... Karaffe muss aus Plastik sein.

** Konkrete Aufgaben
Jede Woche eine Liste zum Eintragen:
- Gemüse schneiden ("Gerät")
- Obst schälen
- Verkauf + Geschirrspüler einräumen
- Nacharbeit: Donnerstag, wenn was übrig bleibt; wäre zum Verteilen; 1a, 1b, etc ...

** Projekte

Erste Klassen
- Schule am Bauernhof (März, April)
- Jausenchecker als Lernjob; BU / Lernschiene

Zweite Klassen:
- Seminarbäuerinnen: wie kommt das Gras in den Burger?
- Exkursion: Salzwelten
- Réene Schroeder: Kräuzersalz

Dritte Klassen
- Käserei

Vierten Klassen
- Etikettenchecker
- Maria Fanninger: Land schafft Leben

Diese Projekte in die letzte SW verlegen? Max 2 Tage davon; vierte Klassen eher nicht; 

* Leiterbericht - Schulneubau
Einspruchsfrist 12.09.

Bau ab Oktober 2024 bis Herbst 2026

Übersiedeln + Einpacken...

Bitte keine SA in der ersten Woche nach den W-Ferien; S möglichst von Baustelle fernhalten.

Amtsverschwiegenheit + Datenschutz!

Immer in Rücksprache mit der Gemeinde!
"... Wenn nix dazwischen kommt ..." immer dazu sagen.
Niemals über SchoolFox.

Am Besten an die Gemeinde weiterleiten - das ist Job der Gemeinde. Diese baut die Schule.

Schulordnung:
- Bauarbeiter nur, wenn er den U nicht stört


* Lehrpläne Neu
Umsetzung der 13 übergreifende Themen
schulautonome Lehrpläne IF
Kompetenzraster D, E, M und Religion
"Pädagogik Paket" googlen
115 Lernaufgaben dazu

* Kinderschutzkonzept

* IKM Plus
geöffnet
Basis Module 7.+8. SS
02.12.-20.01. D E M
Fokus Module D (Lesen leicht)
02.12. - 14.02.
Zyklus Module (alle 3 Jahre: 2024,27,30) 02.12. - ...

* QMS
päd. Leitvorstellungen
SEP + Evaluierungen
2 Neue Themen: Sprachsensibler U + Förderung
Feedback 1x / Jahr
Q-Handbuch umgesetzt werden

* Termine:
10.09. 10h30 Kirche; zurück zur Schule. Unterrichtsende 11h20 (bis dahin warten)
10.09. 19h00 Klassenforum 1. Klassen 
11.09. U-Ende 11:20
11.09. 19:00 Klassenforum 2. Klassen
12.09. Wandertag (Ersatztermin 2. SW; Wetter?) Bitte in Liste eintragen
Do + Fr Kennenlerntage erste Klassen; 1b Workshop entfällt; Rocheralm 1c
Bis Fr Abmeldung vom RU

23.09. Wandertag; Termin für erste Konferenz wird noch bekannt gegeben; IF ab 30.09.
25.09.+26.09. 13h30-18h00 SCHILF verpflichtend.

10.10. Integrationskonferenz 14:30 (5. SS)

24.10. 2. Päd Konferenz
25.10. Lehrerausflug Pflege Betriebsgemeinschaft
26.10.-03.11. Herbstferien
11.12.2024: Schulschitag

Projekttage 2c 26.5.-28.5.2025

Schiwoche 13.1.-17.1.2025 zweite Klassen

Elternsprechtage:
- 4.12. 15h00-18h00
- 25.4. 15h00-18h00

* Allfälliges
BD - Umstellungen ab 1.1.2025 - neue Mailadressen - Lohnnachweis per Mail nicht mehr möglich.

BD Förderstundenabrechnungen wird in Zukunft kontrolliert - streng!
Teilnahme an SV ist keine Förderstunde - sondern eine EMDL!

Projekt Look Twice

Nachhilfeunterricht Ende September steht fest ob 10 Termine ab Oktober zustande kommen.

Info-Mappe

Kasten bei Johanna

Lernschiene: Start 2. Klasse - 25.09.; 1. Klasse - 21.10.

Infomail Polizei: Suchtmittel Vorkommnisse an der Schule; was ist ab wann erlaubt; was nicht erlaubt ist - müssen melden.

* Schulgottesdienste:

Inhalt vorbereiten - Rücksprache mit Johanna.
- erste Kl.: Anfang und Ende
- zweite Klassen: Weihnachten
- dritte Klassen: Ostern
- vierte Klassen: eigener Abschlussgottesdienst


* Schulsozialarbeit
PPP vorhanden
