#+title:      Notenkonferenz
#+date:       [2024-06-28 Fr 14:02]
#+filetags:   :schule:
#+identifier: 20240628T140224


* Begrüßung
Herzliches Danke für die letzte U-Periode! Wir hatten so viele Events:

- MINT Messe
- Charity Run: Dani geht seither Laufen!
- Theater auf der Burg: viele Spenden! Raika zahlt Tontechniker. Näheres bei Abschlusskonferenz. Großes Engagement der Kinder, Lehrer, ...; Riesiges Feedback der Gemeinde.

Danke für Planung; Organisation! BM lädt Theatergruppe auf Pizza und Getränk ein. GEll herzliches DANKE! Großes Danke von Gertraud an alle: Zusammenräumen, etc. Schulbetrieb wurde so gut es geht nicht gestört - danke. Vieles passierte wie nicht vorher gesehen. Gertraud: selber geflasht; wie gut die Viertklassler sind! Andre-Leon und Resi (eigentlich wollte GE die Szene kürzen oder weg?) waren enttäuscht, und dann haben sie beide die Szene so super gespielt!

Am Di nach der ersten Aufführung: haben sich von Auff. zu Auff. gesteigert. Danke fürs Werben. (Kurzfristiger Werben) Waas (?) Sebastian Rückmeldung: BM wollte zuerst nicht komen, jetzt ist er zweimal zum Theater. Und spendet ...

KK sind leistungsbereit ...

* Personelles
- Manu verlässt uns
- ich ebenso
- Christian geht nach Kuchl

- Religion: Simon Brändle (1+2); eine Frau ? (3+4);
- Clemens Skarbal (super), plus zwei andere; ...
- Zeidl Verena: E und Sport

Lfv work in progress

Dank an Fackonferenzen;

1a: Magdalena MINT
1b: Ellmauer Gertraud

Kinderschutzmappe anschauen

Leitfaden für neue Lehrerinnen: Zugänge; SA; Teams; ...

PH Kurs: 1.6. - 15.9.2024 

* Notenkonferenz

** 4a
- alle positiv; 2x 1.0; ...

** 4b
- kein NG, alle schaffen
1x 1.0 (Seidl Marlene)

** 4c
- 2x 1.0; 1x 1.07 (ein Gut)
- kein NG
- Danke für Verständnis von Zlatko (hat Lehrstelle bei Auto Jäger); hat sich sehr verändert.

** 3a
- NG niemand
- 1x 1.0
- LN Änderung: nichts
- VH Noten: 4x Z;
- Mario: WZ (von BM) - 18 unentschuldigte Stunden; 300 entschuldigte Fehlstunden


** 3b
- NG: niemand
- 2x 1.0
- LN: ab Fabian in E; auf Andrea D
- kein WZ
- Z: Tobi, Samuel, ..


** 3c
- NG: 1x Muffetin in D (Klausel)
- 2x 1.0
- LN: Yaren ab in E; Sally M auf
- WZ: Lotta Huber (D SA; Unterschrift fälschen)
- sehr viele Z


** 2a
- kein NG
- VN: ein paar Z
- LN Änderung: Zwillinge auf gestuft (M); Jakob: ab in E;


** 2b
- LN nix
- VN: Robin WZ (wiederholt gewalttätig)
- Leon / Felix (1a) / Lucian gebrochene Nase
- mehrere Z
- andere Raufereien; ...
- 1x 1.0


** 1a
- kein NG, viele (16) Genügend;
- 2x 1.0
- 5x Z
- 1x WZ (Korrekturen der Lehrerin geändert und die Note geändert)
- Felix: komplett fertig; Handlung im Affekt; hat ein Z. 

** 1b
- 1x 1.0
- ein paar Z


* Klassenraum Einteilung
- 4a: bleibt
- 4b + 4c bleiben
- 3a: bleibt
- 3b: in die Gruppenraum
- 2a: bleibt
- 2b: bleibt
- 2c: wo jetzige 2b
- 1a: jetzige 4a
- 1b: jetzige 4c


* Allfälliges
- Projekttage:
  - Mo: Matten und Stühle (4b + 4a?)
  - Di: Bühne und Deko (4c)
  - Mi: Generalprobe
  
- Ablauf: Donnerstag 07:45 Abmarsch in Kirche; 10h00 Feier; danach Essen Abfalter.
- Viertklassler vorne
- Dritt Klassler oben
- Martin betreut Nicht Kirchen Geher

- Alternativprogramm!

- Freitag: 07:45 alle da!
- 09:00 Konferenz
- Gutscheine für Kinder, die sich besonders sozial ausgezeichnet haben. Pro Klasse ein Schüler. Ist das eine gute Idee?
- Gutscheine für Klassenbeste: 1a 2x; 1b 1x; 2a 1x; 2b 1x; 3a 1x; 3b 2; 3c 2; .... (s.o.)
- Magdalena: Klassensprecher?

- alle L einen Laptop, wer noch nicht hat

- o365; Cloud löschen!

- PCs erneuern, Plätze abbauen, ...

- Gemeinde: KG Neubau; weniger üppig beim Budget; ... was noch nicht budgetiert ist.

- 4c: Tafel austauschen; ...

- Schulbuch macht Sylvia

- Material nicht mehr amazon, sondern lokal in Golling einkufen

- Julia: Kasten; ev. freimachen.

- 1. SW 2024 / 2025: Eröffnungskonferenz

- Planer Bestellung (Sandra)

- Schuljahr 2024/2025: Freitag GP; Pausenaufsicht klarstellen, Regeln klarstellen. Nicht in andere Klassen; nicht Stock wechseln; ...
  ODER: hinaus in den Hof?
  Wuzzler für den zweiten Stock?
  Pedalos, Stelzen; ... gibt es.

  Vertretung wenn bei Pausenaufsicht verhindert.
  Besprechung am Schulanfang? Bitte!

  Anliegen Schulwart: wer ist am Mo in der Schule? BU Kammerl: was kann ausgeräumt werden? Viele Klassenlektüren? BU Bücher sind schlecht verräumt. Oder im ersten Stock Gang ein Kasten für BU. Es gibt doch einen MINT Raum: Platz für BU?

- Martin: viele sehr alte Lacke (Sondermüll). Wohin?

- ein Mikrofon kaputt; eine Leinwand?

- 4c: ein Fenster kaputt (und noch zwei andere).

- Zlatko: einen Sessel kaputt; Notausgangschild / Vandalismus: keine Versicherung (600 Euro).

- Hanni: erfolgreiche OP.
