#+title:      Jahresplanung 01
#+date:       [2024-07-19 Fr 12:59]
#+filetags:   :Project:topic01:
#+identifier: 20240719T125948
#+CATEGORY: topic 01
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Jahresplanung 01.html

* Kap. 1 | Über das Leben nachdenken
September / Oktober

** Kompetenzbereich

A1+2: Menschen und ihre Lebensorientierungen

** Leitkompetenz

Al Beziehung verantwortungsvoll gestalten können - zu sich selbst, zu anderen, zur Schöpfung
A2 Sich mit den großen Fragen der Menschen auseinandersetzen können

** Kompetenzbeschreibung

Die Schüler:innen können sich in ihrer gottgeschenkten Einzigartigkeit wahrnehmen und wissen um die Bedeutung von (Selbst-) Vertrauen für ein gelingendes (Zusammen-) Leben.

** Inhalte / Buch

- "Zeit für Religion"
- "Spaziergang durch das Buch"
- (Das bin ich - das bist du)
- Über Leben nachdenken
- Einfach besonders - ich bin ich
- Auf dem Weg zum Ich
- Füreinander und Miteinander
- Große und kleine Fragen

** Kompetenzniveau, KN-SPF, Übergreifende Themen

- KN 1 + KN-SPF: Die Schüler:innen können ausdrücken, was sie einmalig macht und was ihr (Selbst-)Vertrauen stärkt.
- KN 1:  Die Schüler:innen können religiöse Antworten auf ihre existenziellen Fragen erforschen.
- KN-SPF: Die Schüler können anhand von Geschichten existentielle Fragen stellen und Antworten suchen.

Übergreifende Themen: 
Bildungs-, Berufs- und Lebensorientierung (1)
Sexualpädagogik (9)


* Kap. 2 | Himmel und Erde berühren sich 
Oktober / November

** Kompetenzbereich

B4 Gelehrte und gelebte Bezugsreligion

** Leitkompetenz

B4 Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können

** Kompetenzbeschreibung

Die Schüler:innen kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten.

** Inhalte / Buch

- Himmel und Erde berühren sich
- Das Unsichtbare entdecken
- Staunen und Achtsam werden
- Gefühle vor Gott bringen
- Mit Gott reden
- Das Vaterunser verstehen.

** Kompetenzniveau, KN-SPF, Übergreifende Themen

- KN 1 + KN-SPF:  Die Schüler:innen können die Bedeutung spiritueller und liturgischer Ausdrucksformen nachvollziehen.

Übergreifende Themen:
Sprachliche Bildung und Lesen (10) 


* Kap. 3 | Feste feiern
November / Dezember

** Kompetenzbereich

C5 Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur

** Leitkompetenz

C5  Medien, Kunst und Kultur im Kontext religiöser Weltwahrnehmung interpretieren, beurteilen und gestalten können

** Kompetenzbeschreibung
Die Schüler:innen können das Kirchenjahr mit seinen Festen als Rhythmus des Lebens verstehen und mitgestalten.

** Inhalte / Buch

- Feste feiern
- Hurra, wir feiern ein Fest!
- Im Rhythmus der Zeit
- Die Festkreise
- Maria, eine mutige Frau
- Weihnachtsspecial "Fürchtet euch nicht!"

** Kompetenzniveau, KN-SPF, Übergreifende Themen

KN 1 + KN-SPF: Die Schüler:innen können Feste des Kirchenjahrs benennen und dem Kalenderjahr zuordnen.


* Kap. 4 | Jesus: Gott geht mit
Jänner / Februar / März

** Kompetenzbereich

B3 Gelehrte und gelebte Bezugsreligion

** Leitkompetenz

B3 Grundlagen und Leitmotive des christlichen Glaubens kennen und für das eigene Leben deuten können.

** Kompetenzbeschreibung

Die Schüler:innen können Leben und Handeln Jesu in Grundlinien beschreiben und als Basis christlichen Glaubens kommunizieren.

** Inhalte / Buch

- Jesus: Gott geht mit
- Jesus begleitet mich
- Ein einzigartiges Leben
- Die Emmaus-Geschichte
- Wenn Gott Mensch wird
- Israel - das Land, in dem Jesus lebte

** Kompetenzniveau, KN-SPF, Übergreifende Themen

KN 1: Die Schüler:innen können anhand einer Jesuserzählung charakterisieren, wie in der Bibel historische Fakten und Glaubenszeugnis verbunden sind.

KN-SPF: Die Schüler können die Bedeutung der Bibel als Heilige Schrift und die Welt der Bibel entdecken.

Übergreifende Themen:
Sprachliche Bildung und Lesen (10)


* Kap. 5 | Das Buch der Bücher
März / April

** Kompetenzbereich

B3 Gelehrte und gelebte Bezugsreligion

** Leitkompetenz

Die Schüler:innen können Leben und Handeln Jesu in Grundlinien beschreiben und als Basis christlichen Glaubens kommunizieren.

** Kompetenzbeschreibung

Die Schüler:innen verfügen über erweiterte Grundkenntnisse zur Bibel und können sie als inspiriertes Zeugnis des Dialogs Gottes mit den Menschen deuten.

** Inhalte / Buch

- Osterspecial "Fürchtet euch nicht!"
- Das Buch der Bücher
- Ein Navigationssystem für die Bibel
- Das Neue Testament entsteht
- Vier Bücher, ein Held - die Evangelien
- Die Bibel - 2000 Jahre Kultur prägend

** Kompetenzniveau, KN-SPF, Übergreifende Themen

KN 1: Die Schüler:innen können anhand einer Jesuserzählung charakterisieren, wie in der Bibel historische Fakten und Glaubenszeugnis verbunden sind.

KN-SPF: Die Schüler können die Bedeutung der Bibel als Heilige Schrift und die Welt der Bibel entdecken.

Übergreifende Themen:
Sprachliche Bildung und Lesen (10)


* Kap. 6 | Versammelt in meinem Namen
Mai / Juni

** Kompetenzbereich

B4 Gelehrte und gelebte Bezugsreligion

** Leitkompetenz

B4 Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können

** Kompetenzbeschreibung

Die Schüler:innen können Taufe und Eucharistie als Ausdruck der Zugehörigkeit zur kirchlichen Gemeinschaft verstehen.

** Inhalte / Buch

- Versammelt in meinem Namen
- Leben in der Gemeinschaft
- Du bist mein geliebtes Kind
- Gemeinsam Essen - Gemeinsam Feiern
- Danken gehört zum Leben
- Den Glauben gemeinsam bekennen

** Kompetenzniveau, KN-SPF, Übergreifende Themen

KN 1: Die Schüler:innen können die Bedeutung spiritueller und liturgischer Ausdrucksformen nachvollziehen.
Die Schüler können das Glaubensbekenntnis als eine Ausdrucksform der Zugehörigkeit zur Kirche erläutern.

KN-SPF: Die Schüler können Zeichen von Taufe und Eucharistie benennen.

Übergreifende Themen:
Sprachliche Bildung und Lesen (10)


* Kap. 7 | Aufeinander zugehen
Juni / Juli

** Kompetenzbereich

C6 Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur

** Leitkompetenz

C6 Unterschiedlichen Lebensweisen und Glaubensformen reflexiv begegnen können

** Kompetenzbeschreibung

Die Schüler:innen können Gemeinsames und Unterscheidendes, Verbindendes und Trennendes von Konfessionen und Religionen benennen und sich damit respektvoll auseinandersetzen. 

** Inhalte / Buch

- Aufeinander zugehen
- So feiern wir
- Und was feierst du? Feste in den Religionen
- Gemeinsam vor Gott
- #Religion - Religion vernetzt
- Aneinander wachsen
- Unter einem gemeinsamen Dach

** Kompetenzniveau, KN-SPF, Übergreifende Themen

KN 1: Die Schüler:innen können Verbindendes und Unterscheidendes der Konfessionen und Religionen reflektieren.

KN-SPF: Die Schüler:innen können Verbindendes und Unterscheidendes der Religionen benennen.

Übergreifendes Thema:
Interkulturelle Bildung (5)
