#+title:      B Klasse 2022-26 Seekirchen
#+date:       [2024-09-08 So 21:42]
#+filetags:   :4b:sk:
#+identifier: 20240908T214223
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/4b Seekirchen.html

* Jahresplanung

[[denote:20240719T131544][Zeit für Religion 04]]

* Notizen, Tasks, Termine


* Stundenplanung

** Ostern / Auferstehung
YouTube Video von Johannes Hartl: [[https://www.youtube.com/watch?v=EEtOLeIrshI]] & 
[[https://www.youtube.com/watch?v=qVyiSLjKj80]] 
[[https://www.youtube.com/watch?v=QHEKYZYoCbY]]
[[https://www.youtube.com/watch?v=r7YJOBtnK5w]]

Jesus - mehr als ein Prophet? [[https://www.youtube.com/watch?v=2UGhH4EmBOY]]

Faktencheck zur Auferstehung
- Jesus hat nicht gelebt
- Jesus starb nicht am Kreuz
- Erscheinungen erfunden
- Berichte unglaubwürdig

Lesen: Joh 20

Außerbiblische Quellen:

*** Flavius Josephus

Als Testimonium Flavianum bezeichnet man den 93 n. Chr. verfassten Abschnitt im Buch 18, Verse 63–64 aus den Antiquitates Judaicae des Flavius Josephus:

#+begin_quote
"Um diese Zeit lebte Jesus, ein weiser Mann, wenn man ihn überhaupt einen Menschen nennen darf. Er vollbrachte nämlich ganz unglaubliche Taten und war der Lehrer aller Menschen, die mit Lust die Wahrheit aufnahmen. So zog er viele Juden und auch viele Heiden an sich. Dieser war der Christus. Und obgleich ihn Pilatus auf Betreiben der Vornehmsten unseres Volkes zum Kreuzestod verurteilte, wurden doch seine früheren Anhänger ihm nicht untreu. Denn er erschien ihnen am dritten Tage wieder lebend, wie gottgesandte Propheten dies und tausend andere wunderbare Dinge von ihm vorhergesagt hatten. Und bis auf den heutigen Tag besteht das Volk der Christen, die sich nach ihm nennen, fort.[7]"
#+end_quote

*** Tacitus

Tacitus war schon zu Lebzeiten nicht nur als erfolgreicher Politiker, sondern auch als römischer Historiker bekannt. Er schrieb 116–117 seine teilweise recht kaiserkritischen Annalen, deren Bücher 13–16 die Regentschaft Neros beschreiben: Auf die ruhigen Anfangsjahre (A. 13) sei mit dem Brand Roms 64 eine Tyrannei gefolgt (A. 14–16). Nero habe vergeblich versucht, den Verdacht, er selbst habe die Brandlegung befohlen, durch alle möglichen Anstrengungen zu beschwichtigen. In diesem Zusammenhang erwähnte Tacitus die Christen:

#+begin_quote
„Um das Gerücht aus der Welt zu schaffen, schob er die Schuld auf andere und verhängte die ausgesuchtesten Strafen über die wegen ihrer Verbrechen Verhassten, die das Volk ‚Chrestianer‘ nannte. Der Urheber dieses Namens ist Christus, der unter der Regierung des Tiberius vom Prokurator Pontius Pilatus hingerichtet worden war. Für den Augenblick war [so] der verderbliche Aberglaube unterdrückt worden, trat aber später wieder hervor und verbreitete sich nicht nur in Judäa, wo das Übel aufgekommen war, sondern auch in Rom, wo alle Greuel und Abscheulichkeiten der ganzen Welt zusammenströmen und gefeiert werden.“[30]
#+end_quote

*** Plinius der Jüngere

Plinius war seit etwa 111 als Statthalter in Bithynien (heute İzmit, Türkei) für Anzeigen aus der Bevölkerung gegen dort lebende Christen zuständig. In einem Briefwechsel mit Kaiser Trajan, den er später in seine zehnbändige Briefsammlung aufnahm (Plinius-Briefe), holte er sich rechtliche Bestätigung für sein Verfahren mit ihnen. In epistula X/96 beschrieb er seine Verhörmethoden, die ihm bekannt gewordenen christlichen Bräuche und seinen Eindruck von ihrem Glauben:[32]

#+begin_quote
„Denen, die bestritten, Christen zu sein oder gewesen zu sein, sprach ich die Formel vor und ließ sie die Götter anrufen und zu Deinem Standbild […] mit Weihrauch- und Weinspenden beten und außerdem Christus lästern. Daraufhin konnten sie meines Erachtens freigelassen werden. Denn zu all dem sollen sich wahre Christen nicht zwingen lassen. […]

Sie versicherten, ihre ganze Schuld oder ihr Irrtum habe darin bestanden, dass sie sich regelmäßig an einem bestimmten Tag vor Dämmerung versammelten, um Christus als Gott ein Lied darzubringen und sich durch Eid zu verpflichten – nicht etwa zu einem Verbrechen, sondern zur Unterlassung von Diebstahl, Raub, Ehebruch, Treulosigkeit, Unterschlagung von anvertrautem Gut.

Umso mehr hielt ich es für notwendig, von zwei sogenannten ‚Dienerinnen‘ die Wahrheit auch noch durch Folter zu erforschen. Ich fand nichts als absurden, maßlosen Aberglauben. […] Denn nicht nur über die Städte, auch über die Dörfer hat sich die Seuche dieses Aberglaubens verbreitet. Doch es scheint möglich, sie einzudämmen und auszutilgen.“
#+begin_quote


** Emmausjünger

Lk 24 lesen und Bildergeschichte zeichnen - Bezug zu Eucharistie herstellen


** Jesus erscheint seinen Jüngern (Joh 20)

"Der Friede sei mit euch!"

Der "ungläubige" Thomas. 

** Das Leben der Urchristen

** Sakramente / Taufe


* Reflexionen

** Wie vorgehen?
:PROPERTIES:
:CAPTURED: [2025-11-03 Mo 16:49]
:DESCRIPTION: [[file:~/Documents/notes/20240908T214223--b-klasse-2022-26-seekirchen__4b_sk.org::*Stundenplanung][Stundenplanung]]
:END:
Ich bin ehrlich gesagt etwas ratlos. Die Schüler sind ziemlich schwierig - und das laut der Putzfrau schon seit der ersten Klasse. Sehr oft kommt das Argument: "Das ist eine Sportklasse. Da haben die Schüler und auch die Eltern ein sehr hohes Selbstbewusstsein, denken sie seien so toll. Und benehmen sich leider sehr daneben." 

Ich habe die Klasse selbständig arbeiten lassen, was nur bedingt geklappt hat. Die Kids schreien wie Affen, grunzen wie Schweine, es fliegen Patschen, Schuhe, ... Wenn mal eine Wasserflasche umfällt, wird meterweise Papier verwendet (was natürlich sehr viel Lärme macht). Wenn man da als Lehrer laut wird, gießt das nur Öl ins Feuer. Danach imitieren die Schüler den Lehrer, äffen ihn nach. Also sag ich oft nichts. 

Ich denke mir eben: "Ich hab diese Klasse eh nur ein Jahr, dann sind sie weg!" Was soll ich da noch ändern? Meine Kollegin, die am Ende des Jahres in Pension geht, hat diese Klasse sehr gerne abgegeben (wie alle anderen Sportklassen - 2b und 3b - auch).

Soll ich mit ihnen manchmal eine Lernstunde vor einer SA oder Test einfügen?

** Burschen 2. Reihe (Wand)
Überschwemmung auf Tisch, dauert ewig, bis Tisch trocken ist. Kein Unterricht möglich...

** Adhero Savio

** Bamberger Anna

** Ebner Florian

** Eibl Iris

** Günther Markus

** Hager Chiara

** Handlechner Moritz

** Hofer Laura

** Lechner Jonas

** Mandl Leona

** Mayr David

** Mösl Noah

** Mühlbacher Lisa

** Müller Sebastian

** Neukamp Philipp

** Öhlböck Simon

** Petsche Anna

** Prossinger Samuel

** Reiter Sebastian

** Reitsamer Dominik

** Rinnerthaler Emily

** Scheipl Hannah

** Schernthanner Philip

** Stark Jana

** Strohmaier Luisa
