#+title:      Schlusskonferenz
#+date:       [2024-07-05 Fr 09:00]
#+filetags:   :schule:
#+identifier: 20240705T090015

Herzlichen Dank für die letzten Aktivitäten.

* KVs

* Dankeschön an alle - Schoko

* Charity Run + Burg
hat viel Geld eingebracht
Begeisterung im Ort ist groß

BO Messe, ...

Danke für Opferung der Freizeit; verbessert das schlechte Image - es passiert viel.

Danke für die wunderschöne Abschlussmesse

* Verabschiedung
Immer traurig; es ist immer noch nicht fix, wer kommt. 

- Christian
- Markus
- Manuela
- Matthias


* Sommerschule
2x 4. Klasslerinnen haben sich angemeldet - im MORG Grödig

* Abrechnungen neu

* Infos für Junglehrer auf Teams
Bitte lesen; ev. ergänzen
FÖ Unterricht
SV, ...
Umstufung, ...

* Klassenbücher ausdrucken
und unterschreiben

* Klassenkonferenz Protokolle fehlen
Bitte nachreichen

* Konferenzen Protokolle unterschreiben

* Schule wird ausgebaut
:PROPERTIES:
:CUSTOM_ID: h:4225749a-cdc2-49fb-b639-4cedb4d3e8c6
:END:
wegen Waldkindergarten
7h00 - ??
Spielplatz, abgezäunt, ist dann nur für KG

- wie wird das mit dem Bringen und Abholen der kleinen Kinder?

* Lehrfächerverteilung

* Unverbindliche Übungen
- Darstellendes Spiel (GE) 
- Chor
- Schülerliga
- Geräteturnen
- Boldern
- Erste Hilfe?


* Schülerzahlen
204
eine ao Schülerin: Isabella (Klasse von Lena)

* Schulbeginn
Mo, 07h45 (15min vorher) Beginn
Organisatorische Arbeiten
Schulbücher austeilen

bis 09:30 Unterricht

11:00 Eröffnungskonferenz
Fachkonferenzen
Wiederholungsprüfung


Dienstag: 07:45 Gottesdienst Abmarsch / 08:00 Gottesdienst
Danach org. Arbeiten
Schluss 11:30

Ab Mittwoch Unterricht nach Stundenplan, Wandertage, Projekttage

Almkanal 3a am Donnerstag

Erste Klassen:
Einführung in Schul-Email-Konto, etc (2 Stunden einplanen)

* Martha Seiwald
Seminar Bäuerin, stellt Projekte für Kinder vor
Imkerin / Blumen, Bienenwiese in der Schule; ... Schau-Bienen-Stock.

* Spintverteilung
Wer? Barbara.

* Eisrechnungen
der einzelnen Klassen bitte abgeben - EV zahlt.

* Halbzeittreffen
GH Göllhof, 7.8.2024, 18h00

* Lehrerausflug
Oktober: 27.9.-28.9.2024 oder 23.9.-24.9. (Ruperti)

Abstimmung: (Wetter?)
Mo-Di (Ruperti): 3
27.9.: 17 (15)

Schneibsteinhaus (?), mit Übernachtung (mit Jehnerbahn erreichbar)

Frau Gucci hat Budget erhöht: haben 1000 Euro zur Verfügung

* Allfälliges
Nina: was ist gestern passiert, dass Birgit nicht kommt? Fr. Kaserer stand da und wollte ein Gespräch; Vll. sollte man der Frau Kaserer informieren, dass dies unmöglich ist. Wir müssen uns bei Fr. Kaserer beschweren. (Erwin + Nina) Es kann nix wichtiger sein als die Abschlussfeier einer vierten Klasse. 

Frage: Was kam an Geld beim Charity Run (4950?) und Theater rein? Bitte eine Bestätigung an Eltern schicken; noch nicht alle haben eingezahlt.

Theater / Abrechnung: im Herbst.






