#+title:      Eröffnungskonferenz
#+date:       [2025-09-08 Mo 09:53]
#+filetags:   :sk:
#+identifier: 20250908T095347

* Begrüßung

Ich achte mein eigenes und fremdes Eigentum. (Neubau)

Letzte Stunde: Klasse aufräumen (Mist), Stühle auf den Tischen. Fenster zu.

* Eröffnungskonferenz

* Schülerzahlen

** 1a
15

** 1b
25

** 1c
19

** 1d
15

** 2a

** 2b

** 2c

** 2d

** 3a
20

** 3b
25

** 3c
20

** 3d
18

** 4a
24

** 4b
25

** 4c
24

* Jahresplanungen

An die Direktion schicken; auch Religion? In welcher Form? Bis wann?

* Keine Schulglocke

Nicht vor Unterrichtsende den Unterricht beenden; Schüler zu den Garderoben begleiten

* Pausenaufsicht

in der Früh / große Pause; pünktlich; in die Klassen schauen; genau nehmen.

* Webuntis & Co

Sofort, erste Stunde: Abwesenheiten eintragen; Stoff baldigst eintragen.

Fortbildung anmelden / PH Salzburg, KPH Lehrgänge

Buddys (Schüler helfen Schüler)

* Tag der offenen Tür

Lisa & Johanna (Datum siehe unten)

* Schulfolder

"Vital ... Brain"

* Allfälliges

Koordination:
E: Konstanze
D: Lisa
M: Matthias (KV 4b)
...
Kaffeemaschine: ? + Inge
...
Küche: Spüler ausräumen, aufräumen, Tische putzen (wo man gegessen hat), ...
...
Schulhandy: um Eltern anzurufen (Eva)
...
Religion: Inge (ich, werde von Inge eingelernt)
...
Entrepreneurship?
...

* Termine

Tag der offenen Tür

Elternsprechtag(e)

Schulgottesdienst:
Di: 08:00 Beginn "Orientierung Kompass"

Schulplaner - ausgeteilt (Kosten 7.10 Euro einsammeln, Klasse Anzahl Schulplaner)

