#+title:      Ideen für Themen
#+date:       [2025-10-28 Di 08:38]
#+filetags:   :school:
#+identifier: 20251028T083829

* Gott

Gott ist nicht ein "Ding", sondern die Ursache, dass die Welt existiert. Gott ist außerhalb von Raum und Zeit und Materie. Gott ist. Gott ist nicht hier in diesem Raum. Nein. Ist Gott in diesem Raum? Ja, da er die Ursache ist für alles, was hier existiert. 

Hl. Agustinus:
Gott ist höher als ich mir es vorstellen kann, Er ist mir näher, als ich es mir vorstellen kann. Er ist so hoch, dass ich ihn nicht erreichen kann, Er ist mir näher, ich kann mich nicht vor ihm verstecken. Verliebe dich in Gott.


* Jesus


* Bibel

Abraham, Isaak, Jakob, ... Moses ... lesen;

Ein Evangelium lesen; Apostelgeschichte; einen Brief; Buch der Offenbarung.

* Kirchenjahr, Feste

** Allerheiligen Allerseelen

- Leben nach dem Tod
- Hoffnung
- Sehnsucht nach dem Himmel
- Gebet für Verstorbene
- Vom Ego zu Gott; von der Autonomie zur Theonomie.
- Glücklich ist, wer nicht um sich selbst kreist, sondern für andere da ist, nach Werten strebt, ...


** Weihnachten
Advent = Ankunft
Zeit der Stille, Vorbereitung auf Weihnachten

Draußen wird es immer dunkler und kälter; drinnen wird es immer heller und wärmer (Adventskranz). 

Sehnsucht nach dem Messias; Hoffnung! Wir können Wochen ohne Nahrung, Tage ohne Wasser, Minuten ohne Sauerstoff überleben - aber wir können keinen Moment unseres Lebens ohne Hoffnung (über)leben. ([[file:Bibel/nt/Röm_5.org::v5][Röm 5,5]])

Heilige wie Hl. Nikolaus, Hl. Barbara helfen und begleiten uns auf dem Weg nach Bethlehem. Wie können wir das Leben unserer Mitmenschen heller machen? Brauch: für jede gute Tat legen wir Stroh in die Krippe. 

7 Tage vor Weihnachten: die 7 O Antiphonen. "O Weisheit, ..."

Hirtenspiele / Krippenspiele / Herbergssuche

Adventandachten

Rorate-Messen

Adventskalender

Lesungen aus den Propheten.


** Ostern


* Liturgie, Sakramente

* 10 Gebote, Ethik


* Gebet

* Heilige

