#+title:      D Klasse 2025-29 Seekirchen
#+date:       [2025-09-08 Mo 08:05]
#+filetags:   :1d:sk:
#+identifier: 20250908T080546
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/1d Seekirchen.html

* Jahresplanung

[[denote:20240719T125948][Zeit für Religion 01]]


* Webuntis
[[https://hypate.webuntis.com/WebUntis/#/basic/login]]

* Notizen, Tasks, Termine


* Stundenplanung

** Jesus und die Samariterin am Jakobsbrunnen

(Episode aus The Chosen - hoffentlich klappt das Internet in der Klasse!)

Joh 4 lesen.  + The Chosen Staffel 1 Episode 8

(Staffel 5 online verfügbar!)

Lebendiges Wasser - Gottes Liebe, Gottes Geist; Anbetung in Geist und Wahrheit.

Die große Frage - was erwartest du dir von Gott?
"Was willst du, dass ich dir tue?" - Frage von Jesus an Bartimäus.

Schüler sollen sich mit dieser Frage auseinandersetzen, sie an sich heran lassen. Und ihre Erwartungen formulieren. Aufschreiben. Die "Gefahr" ist, dass die Kinder sagen "nix!" - und meinen, damit den Auftrag erfüllt zu haben; "Können wir jetzt Kahoot spielen?" - So leicht lasse ich die Kinder nicht aus ihrer "Pflicht". Wer nichts von Gott erwartet, wird auch nichts von Gott erhalten. So wie der ältere Sohn im Gleichnis vom verlorenen Sohn. Er bleibt in seiner Welt der Gerechtigkeit; fragt nach nichts. Und ist dabei genauso unglücklich wie sein jüngerer Bruder als der die Schweine hütete.

Wie viel schöner ist doch das Leben - wenn du dich von Gottes Liebe berühren lässt?

** The Chosen 

Staffel 5; Episode 1 (Einzug in Jerusalem); Episode 2 (Pascha; Tempelreinigung)


* Reflexionen
So wie immer, kein normaler Unterricht möglich; es fliegen ständig Papierkugeln; natürlich war es keiner; komischerweise funtkioniert Internet nicht, das Tablet ist kauptt, man hat kein Federpenal mit, etc. Von Burschen kommen respektlose Bemerkungen. So wie letzte Stunde "Geiles Fuchs" "Fuchspennis".

** Braunstein Fabian

** Burda Felix

** Dezsi David-Andreas

** Fekete Anna

** Halilaj Tara

** Hillerzeder Julia

** Lugstein Greta

** Maxbauer Anna

** Mikalauskas Tadas

** Mösl Jakob

** Müller Sophia

** Rack Valentin

** Ruf David

** Sailer Marcel

** Stemeseder Ella
