#+title:      Fastenzeit
#+date:       [2025-12-05 Fr 12:07]
#+filetags:   :kirche:
#+identifier: 20251205T120706

* Wiederholung
Einen persönlichen Klagepsalm schreiben.

* Erarbeitung
Österliche Fastenzeit: wir sind auf dem Weg nach Ostern. Wir feiern die Auferstehung Jesu. Worum geht es bei der Auferstehung Jesu? „Ist aber Christus nicht auferweckt worden, dann ist unsere Verkündigung leer und euer Glaube sinnlos." (1. Kor 15,14f) Der Glaube an die Auferstehung Jesu ist die Grundlage für die christliche Botschaft als Ganze. Wenn man diese wegnimmt, dann ist der christliche Glaube tot. Es bleiben Jesus als eine religiöse Persönlichkeit (die gescheitert ist), alles bleibt im rein Menschlichen, Jesu Autorität reicht so weit, wie uns seine Botschaft einsichtig ist. Wir sind alleingelassen. Unser letzte Instanz ist unser eigenes Urteil. 

Was war geschehen? Für die Zeugen der Auferstehung war es nicht einfach zu sagen, die Realität der Auferstehung sprengte ihren Erfahrungshorizont. Jesu Auferstehung ist nicht das Lebendigmachen einer Leiche (so nahm es R. Bultmann an). Jesu Auferstehung ist der Ausbruch in eine neue Art des Lebens, jenseits von dem Gesetz von Werde und Sterbe. Es ist eine neue Art des Menschsseins, die alle angeht. Die Auferstehung Christi ist entweder unviversal, oder sie ist nicht. Jesus tritt durch die Auferstehung in die Weite Gottes. 

An einen gekreuzigten Messias hatte niemand geglaubt. Ebenso schwer konnten sich die Jünger die Auferstehung in der alten Welt vorstellen. Kreuz und Auferstehung in der Schrift finden und sie neu verstehen. So zum Glauben an Jesus als Sohn Gottes gelangen. Die Auferstehung war für die Jünger so real wie das Kreuz. Die Auferstehung Jesu ist wirklich. Er lebt, er hat zu uns gesprochen, er hat sich von uns berühren lassen. Jesus lebt von Gott her. Er gehört nicht mehr in diese Welt, und ist zugleich real da. Es ist etwas Paradoxes. 

Passt dies in unser modernes, naturwissenschaftliches Weltbid? Nein. Das NT sagt uns: es gibt eine Dimension mehr. Gott kann doch eine neue Art des Daseins schaffen, die Überwindung des Todes? 

 - Bekenntnistradition: „Der Herr ist wahrhaft auferstanden und ist dem Simon erschienen.“ (Lk 24,34); Röm 10,9!
 - Erzähltradition: Begegnungen mit dem Auferstandenen werden erzählt.

Jesus ist für unsere Sünden gestorben, gemäß der Schrift. An Jesus erfüllt sich die Schrift. Der Tod Jesu gehört zur Geschichte Gottes mit seinem Volk, er ist kein Zufall. Jesus stirbt für unsere Sünden: Jesu Tod ist Vollzug der Demut Gottes, der Liebe Gottes. Gott steigt herunter, um den Menschen zu erheben. Cf. viertes Lied vom Gottesknecht: ein Tod, der Versöhnung schafft. 

Das leere Grab sit kein Beweis der Auferstehung. Aber: ist Auferstehung mit dem Verbleiben des Leichnams im Grab vereinbar? Das leere Grab ist ist eine notwendige Bedingung für den Auferstehungsglauben.

Die Auferstehung Jesu ist ein Ereignis in der Geschichte, das den Raum der Geschichte sprengt. Der Mensch Jesus gehört nun mit seinem Leib der Sphäre Gottes zu. In der Auferstehung Jesu findet die menschliche Seele den Raum, in der Unsterblichkeit Sinn erhält als Mitsein mit Gott. Die Auferstehung ist ein neues Ereignis, anders als die Geburt und die Kreuzigung Jesu. Sie ist aber auch nicht außerhalb oder oberhalb der Geschichte. Nur ein Ereignis von radikal neuer Qualität konnte die apostolische Predigt ermöglichen, die nicht mit Spekulationen oder inneren, mystischen Erfahrungen zu erklären ist. Gott handelt leise. Gott gibt Freiheit, schenkt und erweckt Liebe.    

* Hefteintrag

