#+title:      Jesus der Gute Hirte
#+date:       [2025-05-21 Mi 09:52]
#+filetags:   :01:bibel:
#+identifier: 20250521T095233

* Osterevangelium lesen
Bibelthema - mit dem Tablet? Ein Versuch wäre es wert.

ERF Bibelserver: [[https://www.bibleserver.com/EU/Johannes10%2C27]]

Nächster Sonntag: Johannes 10,27-30: "Ich bin der gute Hirte" / "Ich gebe ihnen ewiges Leben und niemand kann sie meiner Hand entreißen."

Bild: [[file:~/Bilder/C_4.OsterSo.pdf]]


* Für Kinder:

Die Freundinnen und Freunde Jesu hatten erfahren: Gott hat Jesus auferweckt. Er ist nicht mehr nur an einem bestimmten Ort und zu einer bestimmten Zeit, sondern immer und überall den Freundinnen und Freunden nahe.

Nun erinnern sie sich an das, was sie mit Jesus erlebt und von ihm gehört haben. So auch diese Geschichte. Er hat sie ihnen im Jerusalemer Tempel erzählt: Wie ist Gott? Er ist wie ein guter Hirt. Er sorgt für die Menschen und schützt sie.

Die Freundinnen und Freunde Jesu verstehen: Gott hat Jesus auferweckt. Wer zu Christus gehört, der ist bei Gott geborgen. Gott lässt uns nicht allein. Gott ist für uns da.

Das dürfen wir auch heute glauben: Gott kennt jeden Menschen. Gott ist (für uns) da!

* Für Erwachsene:

Nicht um die Schafe geht es in diesem Evangelium, sondern um die Frage, was es heißt, an Jesus als den Christus zu glauben. Die kurze Antwort lautet: Ewig und unerschütterlich leben.

Die längere Antwort fragt zunächst einmal, wer Christus ist. Vater und Sohn sind ja nicht zwei Götter, sondern ein einziger. Wenn wir Gott mit der Anrede Vater versehen, meinen wir den Schöpfer, durch den alles aus dem Nichts geschaffen ist, der allerdings so völlig verschieden von der Welt ist, dass er unerreichbar, unerfahrbar und sogar undenkbar ist. Weil aber der ewige Gott aus unendlicher Liebe Mensch geworden ist, nennen wir den Mensch gewordenen Gott auch den Sohn. Der eine Gott ist Vater und Sohn zugleich.

Christus ist der Geist der Worte, dass Gott alle Menschen bedingungslos liebt. Auf diese Liebe ist immer Verlass, im Leben und im Sterben. Keine Macht der Welt, nicht einmal der Tod, kann uns herausreißen aus der Geborgenheit in Gottes Liebe. An Christus glauben heißt, sich ganz und gar auf dieses Wort der unüberbietbaren, alle Probleme übersteigenden Geborgenheit einzulassen. Oder anders gesagt: Das ewige Leben genießen.
