#+title:      Themen für Ostern
#+date:       [2025-04-15 Di 09:59]
#+filetags:   :schule:
#+identifier: 20250415T095936

* (1. Klasse) Osterevangelien
:PROPERTIES:
:CUSTOM_ID: h:5c0352da-5e1c-419e-bd3f-1ec2c44a1f7d
:END:
Ostern ist komischerweise etwas schwieriger im RU zu behandeln als die Leidensgeschichte Jesu, Wunder oder Weihnachten. Denn die Auferstehung Jesu passt nicht in unsere Erfahrungen, ist "etwas" komplett anderes. Und sie verändert unsere Sicht auf die Realität, mit ihr beginnt wirklich ein neues Leben.

In diesen Monaten bis zu den Ferien gebe ich noch einmal Vollgas; 

* (1. Klasse) Emmausjünger
:PROPERTIES:
:CUSTOM_ID: h:b53bb303-bbc2-49bf-a4f2-b0144d59b805
:END:
Text lesen / Zeichnungen / Bezug zu Hl. Messe herstellen


* (2. Klasse + 3. Klasse) Apostel Paulus
:PROPERTIES:
:CUSTOM_ID: h:0d7c3fa0-073e-4a27-b1a5-40c7a2af88c1
:END:
Hab ich den Paulus-Film?

** Bekehrung

** Briefe

** Bedeutung für die Kirche

* (2. Klasse + 3. Klasse) Apostelgeschichte
:PROPERTIES:
:CUSTOM_ID: h:a37e3bc3-d77e-46db-b8e5-e7036bef3974
:END:


* (3. Klasse) Tatsache der Auferstehung Jesu (YouCat - Firmung)
:PROPERTIES:
:CUSTOM_ID: h:845f8c5a-895d-43ad-b35f-b2bdc42a46c0
:END:
Dazu gibt es eine komplett ausgearbeitete Stunde, es gibt ein Video mit Johannes Hartl (eigentlich zwei).

Die wichtigste Botschaft der Welt - Ostern:
[[https://www.youtube.com/watch?v=qNOwBgww1vg]]

Ist Jesus wirklich auferstanden?
[[https://www.youtube.com/watch?v=EEtOLeIrshI]]

Die Auferstehung Jesu als historische Tatsache Teil 1
[[https://www.youtube.com/watch?v=qVyiSLjKj80]]

Die Auferstehung Jesu als historische Tatsache Teil 2
[[https://www.youtube.com/watch?v=QHEKYZYoCbY]]

Die wissenschaftlichen Details der Auferstehung; Soldaten als Zeugen; "Er sah und glaubte." Was sah er? Das Tuch, die Binden und das Schweißtuch, das auf dem Kopf Jesu gelegen hatte. Sah er ev. die Abdruck des Leibes Jesu auf dem Tuch? Wie lagen die Tücher?

"Der Friede sei mit euch!"

** Hat Jesus wirklich gelebt?
Darüber gibt es keine Zweifel mehr; es gibt genug außer biblische Dokumente (Josephus Flavius, Plinius der Ältere, ...; RB der ersten Klasse). 

** Ist Jesus wirklich am Kreuz gestorben?
Römische Soldaten wurden dafür bezahlt, Verurteilte zu töten; der Lanzenstich.

** War das Grab leer?
Das Grab wurde bewacht - die Soldaten bezahlten mit ihrem Leben, falls sie einschliefen; sie waren dafür trainiert, stundenlang zu wachen. Wenn die Apostel nach Pfingsten vom leeren Grab sprachen, dieses aber voll sei - hätte es jeder bemerkt.

Ein Messias, der am Kreuz stirbt - ist das wirklich die Erfolgsstory, die sich verängstigte Apostel ausdenken und dafür ihr Leben lassen wollen?

** Erscheinungen - echt?
Können 500 Jünger gleichzeitig eine Halluzination haben?

Wäre die Geschichte über die Auferstehung erfunden, hätten die Apostel wohl glaubwürdigere Zeugen ausgewählt als Frauen - denn gerade Frauen waren als Zeugen in einem Prozess nicht zugelassen. Gerade *weil* die ersten Zeugen Frauen waren, beweist die Wahrhaftigkeit der Berichte über die Begegnungen mit dem auferstandenen Herrn Jesus Christus.


** Glaube verbreitet rasch sich im Land der Augenzeugen zur Zeit der Augenzeugen
Wer also Zweifel hat, kann die Augenzeugen fragen.


* (4. Klasse) Pfingsten / Hl. Geist / Charismen

* Was finde ich den Schulbüchern?

* (4. Klasse) Glaube - Hoffnung - Liebe
:PROPERTIES:
:CUSTOM_ID: h:b49daa22-696e-422b-a556-30d13ee3e1c8
:END:
Nach der Schule - ohne RU - Firmung

Was macht ihr nachher, um in Glaube / Hoffnung / Liebe zu wachsen?

Quellen: YouCat, KKK, Bibel, (ev. Thomas von Aquin)

** Was ist eine Tugend?
Eine Tugend ist eine innere Haltung, eine positive Gewohnheit, eine für das Gute in Dienst genommene Leidenschaft.

Wir müssen uns verändern auf unserem Weg zu Gott - damit wir frei, in Freude und Leichtigkeit das Gute vollbringen können.

Arbeitsblatt: [[file:~/NMS_Golling/Philosophie/aristoteles-philosoph-104.pdf][Tugenden]]

Lösung: [[file:~/NMS_Golling/Philosophie/aristoteles-philosoph-106_Lösung.pdf][Tugenden Lösung]]
  
Was ist eine göttliche Tugend?
Glaube, Hoffnung, Liebe

Ist wie eine Pflanze - was machst du, damit diese Pflanze wächst?

Gleichnisse: Sämann - Samen fällt auf dem Weg, in die Dornen, auf felsigen Boden, auf fruchtbaren Boden.
Ev. ein AB, auf dem die Schüler zu Weg, Dornen, etc konkret eintragen, was z.B. ihre Sorgen sind?

Konkret: wie und wo engagiert ihr euch, damit ihr im Glauben, Hoffnung und Liebe wächst?

Die nächsten Stunden sind entweder in zwei Teilen oder zwei Stunden.

** Glaube
Vertrauen; Gott sein eigenes Leben anvertrauen; Wissen(?);

Der Glaube ist die Kraft, in der wir Gott zustimmen, seine Wahrheit anerkennen und uns persönlich an ihn binden. Der Weg zu Gott, der die Wahrheit ist. Jesus ist der Weg, die Wahrheit und das Leben, daher kann der Glaube keine beliebige Gläubigkeit an irgendetwas sein: der Glaube hat klare Inhalte (Credo); und der Glaube ist auch die vertrauende Beziehung zu Gott mit Herz und Verstand. Der Glaube wird in der Liebe wirksam.

Objekt des Glaubens
Gott / Offenbarung

Wie wachse ich konkret im Glauben?
Bibel lesen, Gebet, Sakramente


** Hoffnung
Objekt der Hoffnung?
Hoffnung auf das Heil, das ewige Leben bei Gott.

Die Hoffnung ist die Kraft, in der wir dauerhaft und stark das ersehnen, wozu wir auf der Erde sind: um Gott zu loben und ihm zu dienen; worin unser wahres Glück besteht: in Gott unsere Erfüllung zu finden; wo unsere endgültige Heimat ist: in Gott.

Hoffnung ist Vertrauen auf das , was Gott uns in der Schöpfung, den Propheten, besonders aber in Jesus Christus versprochen hat, auch wenn wir es noch nicht sehen. Damit wir in Geduld auf das Wahre hoffen können, ist uns Gottes Heiliger Geist geschenkt. 

Zwei Extreme: "Der Himmel ist nicht für mich, ich komme niemals in den Himmel." oder: "Ich komme ganz sicher in den Himmel, denn Gott vergibt mir so wie so."

Die Hoffnung gibt ein Ziel, also eine Kraft.
Gebet / Lobpreis und Dank, Beichte

Was ist das Ziel in deinem Leben?
Geld, Erfolg, Familie, ..?
sehr gut, aber diese sollen ausgerichtet sein auf das letzte Ziel: Himmel.

Was sagt der Katechismus?

Wie wachse ich in der Hoffnung?
Lobpreis?

** Liebe
Die Liebe ist die Kraft, in der wir, die wir von Gott zuerst geliebt wurden, uns Gott hingeben können, um uns mit ihm zu vereinigen und den anderen um Gottes willen so rückhaltlos und herzlich anzunehmen, wie wir uns selbst annehmen.

Jesus stellt die Liebe über alle Gesetze, ohne diese deshalb außer Kraft zu setzen. Zu Recht sagt daher Augustinus: "Liebe, und tu, was du willst." Was gar nicht so einfach ist, wie es klingt. Die Liebe ist deshalb die größte, alle anderen Kräfte beseelende und mit göttlichem Leben erfüllende Energie.

Nächstenliebe / Liebe zu Gott / zu sich selbst
