#+title:      D Klasse 2023-27 Seekirchen
#+date:       [2025-09-08 Mo 08:12]
#+filetags:   :3d:sk:
#+identifier: 20250908T081215
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/3d Seekirchen.html

* Jahresplanung

[[denote:20240709T110253][Zeit für Religion 03]]


* Webuntis
[[https://hypate.webuntis.com/WebUntis/#/basic/login]]

* Notizen, Tasks, Termine

WICHTIG - ANSAGEN!
[[mu4e:msgid:VI0PR02MB1210861DE7DF4BB6ABB1A0805C71B2@VI0PR02MB12108.eurprd02.prod.outlook.com][WG: Verlegung der Abfahrtsstelle der Linie 126 am Freitag, 12.06.2026 "Fest zum Sommerfest"]]


* Stundenplanung

** Arbeiten mit der Bibel 

Buch der Apokalypse (Offenbarung des Johannes)

oder: Apostelgeschichte / ein Brief des Apostel Paulus

[cite:@Bamm1968]

** Sakrament der Weihe

Videos von kathmedia, YouCat ab Nr. 249 (?)
Priester - Aufgaben, Gewand, Beruf / Berufung
Hierarchie der Kirchenämter / kein herrschen, sondern ein Dienst.
Warum keine Frau als Priester? (Frage im YouCat vorlesen)

Welche Autorität, Aufgaben, ... gibt Jesus den Zwölf? Was sagt er den Jüngern? Hat er mir die Autorität gegeben, die Sünden zu vergeben, zu lehren, zu leiten, zu urteilen, zu binden oder zu lösen, ...? Oder doch nur den Zwölf - also den Bischöfen und damit der Kirche? 

Wenn Jesus sagt "ihr" und damit sich direkt an die Zwölf wendet, dann gilt dieses Wort den Aposteln / Bischöfen / der Kirche. 

Und dann gibt es Stellen, an denen sich Jesus an die Jünger wendet. Diese Stellen gelten für mich.

Welche Kirche hält sich daran? die katholische Kirche.

** Sakramente

Wiederholung; Tabelle / Dokument erstellen

[[https://www.donbosco-magazin.eu/Kinder/Kinderwissen/Sakramente-Zeichen-der-Naehe-Gottes]]


** Zeit für Paulus

Buch S. 53 lesen
AB "Frag Paulus" 
Kapitel 4 ab S 54 lesen.

Generell: im Lehrerhandbuch (pdf Datei) gibt es genug Arbeitsmaterial. Beim anderen Buch (Religion für uns) sollte es online einiges geben (digi4school?).

Christenverfolgung - Buch S. 54 / 55
Kirche in Not (Christen in Not) 

* Reflexionen

** Altmann Kristin

** Eckschlager Amelie

** Ferao Mbelani Sidonia

** Kaltenbrunner Tobias

** Karas Zita

** Klinger Valerie

** Lerchner Gregor

** Mathwich Lina

** Nobis Levi

** Petrovic David

** Pöschl Andreas

** Seidl Raphael

** Selimi Ensar

** Stangl Emma

** Wessely Amelie

** Wessely Isabella

** Wirths Levi

** Zdraljevic Jovana
