#+title:      Klassenkonferenz 4b Seekirchen
#+date:       [2025-11-12 Mi 15:44]
#+filetags:   :4b:sk:
#+identifier: 20251112T154432

* Laura: ADHS
Beurteilung wie gehabt, wird leicht abgelenkt. Beim Test eventuell alleine sitzen / schreiben (Nebenraum). Gruppenarbeiten - Laura in den Nebenraum. Keine Medikamente.

* Klassensituation
Extrem anstrengend - va Burschen gegeneinander; B gegen M

Workshops - Philipp (Pippo) teilt aus (als Schutz), oft das Opfer. Fight - Flight - Freeze (Bippo). 

Viele Burschen machen andere klein (Jonas, am schwersten, lügt wie gedruckt, ...). Manche sehen es ein, aber keine Änderung.

Daher bitte aufschreiben - damit Matthias den Eltern was sagen kann; ev. kann jemand nicht mit. Savio: Savio, Jonas, David, Florian; einer fängt an, alle machen mit, ... wer fängt an, weiß man nicht? Man ermahnt drei, die anderen machen weiter, ... schaukelt sich auf.

Es betrifft ca ein Drittel.

Burschen extrem pubertär; null Interesse; ... die Mitläufer dürfen nicht gebremst werden; die Wilden sollen keinen bis kleinen Raum geben; ihr Verhalten hat hier keinen Platz, wird nicht entschuldigt.

** Maßnahmen: 
am NM rein zum Gespräch; können nicht auf Wientage mit; Mitläufer stärken, die dann die Klasse ändern; z.B. die Mitläufer raus in einem Fach; ...

Es geht nicht um "brav / nicht brav"; im Unterricht beschäftigen.  

** Bitte aufzeichnen
