#+title:      Konferenz Oktober
#+date:       [2025-10-14 Di 16:34]
#+filetags:   :mattsee:
#+identifier: 20251014T163400

* Begrüßung

* Schüler

** 3c Noah
Heilstättenschule - Rehab
Material schicken (va Hauptfächer)
2 Stunden Unterricht pro Tag

** 3a Nicolas (?)
war noch nie in der Schule
Verfahren für häuslichen Unterricht - Mutter soll sich erkundigen
dauert immer noch

** 4a Anne (?)
war (wieder) ein paar Tage in der Schule
S... Gedanken
benötigt persönliche Beaufsichtigung?
Vorfall mit einem Mitschüler vor ...
Warteliste für Heilstättenschule (ZDK)
Material schicken per Teams

** 2a B Saif, Adem, Lukas
Saif hat Adem gewürgt.
Adem hat sich bewusst nicht gewehrt, damit er nicht geschimpft wird; Adem ruft seinen großen Bruder (16), ... schon die ... Schule;

Eltern geschieden; sollte der 16j auftauchen - Polizei.
Saif in andere Klasse? (besser wäre Sonderschule)
Mattsee ist i-Schule, wir müssen Saif nehmen (laut BD Fr. Siegl); 

** Viele Schüler mit Lese / R-Schreibstörung (-schwäche)
Eltern müssen privat ihr Kind bei diesen Schwächen fördern; wie sollen Lehrer darauf Rücksicht nehmen, wenn die Eltern nicht fördern? 

** Schüler vergreifen sich in Sprache gg Lehrer
Bitte sofort zur Direktion gehen
Bsp.: Loic, Bergström (lügt) - respektieren Eltern, daher diese ins Boot holen;
bei anderen Schülern ist das schwieriger.

** Pause
z.B. beim Verkauf - drängeln; Pausenaufsicht "Jause"!
generell strenger sein; 
Seite 4. Klasse / Konsequenzen? / Hausschuhe? / ...

** Jakob K. (13j)
Darf von Zuhause aus Alk trinken? 

** Vorfall: Schülerin wurde in Umkleide eingesperrt
2 Stunden... weil auf Klo.


* Schulordnung / Handy
Siehe nächste Konferenz bzgl. Verhaltensvereinbarung 19.11.2025
Bei Handy Abnahme: Schüler selbst anrufen lassen
Z.B.: nur Lehrer, der es abgenommen hat, gibt es auch wieder zurück.

* KVs:
Sollte Lehrer nicht kommen - nach 10 Minuten in Direktion klopfen; 
Übersicht: Lesestörung, Asthma, R-Fehler, ... Teams-Folder?

* Spam E-Mail!
Bitte sehr gut aufpassen - KI macht kaum mehr R-Fehler; Adresse kontrollieren, Inhalt, ...

* Kopiereingrenzung
Wie viele Kopien in den Schulen?
Obertrum, etc. - über Apps, keine Kopien, 

Bis jetzt 2700 Kopien
Im Jahr 7000 eine ganze Schule

Gemeinsam mit Gemeinde festlegen, 

* Tag der offenen Tür
November 2025

eine kleine BIM

am Besten Schüler gesammelt mit Bus;

Führung durch Schüler, ...

Anwesenheit für ALLE Lehrer;

* Allfälliges
Stunden-Raster?

Skikurs

Schutzkonzept?


