#+title:      Kommunikation - sich mitteilen / Miteinander kommunizieren
#+date:       [2025-09-06 Sa 12:50]
#+filetags:   :02:gemeinschaft:
#+identifier: 20250906T125043

* Einstieg

** Bingo (Eröffnungsseite) 

spielen/erarbeiten.

** Bewegungsübungen: 

Durch die Klasse gehen und sich nach einem Signalton mit verschiedenen Körperteilen begrüßen (Fingerspitzen, Ellbogen, Rücken, Fußsohlen …).

** Bildbetrachtung „Strichmännchen-Akrobat“ von Keith Haring: 

Wie passt dieses Bild zum Thema Kommunikation? Was sagt es über Kommunikation aus? Das Wort Kommunikation an die Tafel schreiben, gemeinsam die Wortbedeutung klären und Synonyme für das Wort finden. 

Hilfestellung: https://synonyme.woxikon.de/synonyme/kommunikation.php

** DigiPoint (S. 11): „Die Zeit zu beginnen ist jetzt …“ 

Lied anhören und gemeinsam singen.

* Erarbeitung

** Einleitungstext im Buch (S. 8) lesen 

und die Fragen im Plenum oder in Gruppen besprechen. Eigene Frage zum Thema formulieren und in die freien Felder schreiben.

Eventuell:
Giraffe oder Wolf?

** Über Kommunikationsformen sprechen 

und Arbeitsauftrag „Mein Kommunikationstagebuch“ (S. 10) erfüllen.

** Gott ist immer „online“: 

Satzanfänge in den Sprechblasen im „Kugellager“ (S. 11) besprechen (siehe Methodenwerkstatt) und vollenden.

** DigiPoint (S. 10): 

Erklärvideo über soziale Medien ansehen – über Vor- und Nachteile diskutieren.

* Vertiefung / Abschluß

** Zur Fragestellung: Kommunizieren auch Tiere? 

Überraschende Informationen gibt es hier:
https://www.prosieben.at/tv/galileo/videos/201621-so-kurios-kommunizieren-tiere-clip

** Eigene Kommunikationsbilder entwerfen und gestalten:

Z. B. Bildausschnitte vom Bild (S. 9) vorbereiten, austeilen und weiter zeichnen lassen oder eigene Strichmännchen in unterschiedlichen Interaktionen entwerfen und zu einem Klassenbild zusammenfassen.

** Schulanfangsgottesdienst

mithilfe der Buchseiten vorbereiten und feiern (siehe Gottesdienstbausteine).
