#+title:      Schönheit von Gottes Schöpfung
#+date:       [2025-06-06 Fr 09:49]
#+filetags:   :schule:
#+identifier: 20250606T094907
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Schönheit in Gottes Schöpfung.html

* Thema
Schönheit in Gottes Schöpfung

Das Staunen lernen anhand der Schönheit des Universums

Die moderne Technik erlaubt es uns, die Schönheit des Universums noch mehr zu bestaunen. Trotz des größeren Wissens bleibt das Staunen z.B. bei den Wissenschaftlern.

* Mittel
Ausschnitt aus der Dokumentation "Arte James Webb Teleskop"

* Lehrer Schüler Gespräch
Was ist unser Platz im Universum?
Gibt es Leben auf anderen Planeten?
Was braucht es, das Leben entsteht?

Wir sind so klein im ganzen Universum - und Gott liebt uns.
Warum gibt es z.B. die Sterne? Damit wir uns freuen.
Gott ist gut.

Die Neugier der Wissenschaftler, ihre Demut, nicht alles zu wissen.

Wir staunen über Gottes Schöpfung, das sollte uns dazu führen, Gott zu loben.

* Nachbereitung
Die Schüler waren aufmerksam dabei und haben sich aktiv an dem Gespräch beteiligt.
Es kamen schöne und auch tiefgreifende Rückmeldungen von Seiten der Kinder.
