#+title:      Störungen erfolgreich managen (FB)
#+date:       [2025-03-28 Fr 13:55]
#+filetags:   :study:
#+identifier: 20250328T135512

* Ort & Zeit
PH Salzburg, Seminarraum D02.01
14:00-17:30

LV BEST01DS17 25S 4UE FB

* Mit Konflikten im Unterricht umgehen
schnell erfassen und damit umgehen lernen

Bsp.: S kommt zu spät und sagt lässig "Hallo" und setzt sich ohne ein Wort auf den Platz. Reagiere ich als L? Fast alle reagieren.

* Sich Vorstellen

* Weiter...
Nächstes Bsp.: Streit, verbal rüde. Schimpfwörter. Andere grinsen. lachen.

- Wie reagieren?
- Was löst das bei mir aus?
- Welche Reaktion wäre sinnvoll?
- Welche Intervention wäre sinnvoll?

* Erwartungen für heute
Kompetenzen wahrnehmen, Konflikte einschätzen, verstehen, moderieren, stoppen

eigenes Verhalten reflektieren

Konfliktarten, -dynamik (Theorie)

K. unter SuS
Autoritäten
Mobbing

Bsp.-interventionen einschätzen
Haltung:
Neue Autorität
Klassenraummanagement

* Konflikttypen
Woran denke ich beim Wort "Konflikt"?
Wie gehe ich damit um? Fight, Flight, Freeze
Umgang mit Konflikten?
Worauf springen sie an? Was lässt mich kalt? Was macht mich zornig?

Zum Thema Konflikt gibt es 3km Literatur.

* Wissen hilft
Wenn ich meinen Konflikttypus kenne, dann...

Bedürfnisse kennen und welchen Bedürfnissen gebe ich zu viel oder zu wenig Gewicht?
Welche Fallen gibt es? Konflikte werden überbewertet
Welche Ergänzungen

MACHT - Regeln - verhandlungen

VERHANDLUNGEN - Regeln - macht

Reaktionen besser einschätzen können

* Konfliktlösungskompetenz
- Ich fühle mich emotional betroffen
- Es gehört zu meiner Aufgabe im Job.

Im Unterricht bin ich der Chef, und muss Führungsverantwortung übernehmen.

Konflikte: verhindern, moderieren, deeskalieren, stoppen.

Konflikt: Emotionen, Beeinträchtigungen, ...

Das typische "Ich muss aufs Klo!" Lass ich es zu? Oder nicht?

Nicht jede Störung ist ein Konflikt.

Nicht überreagieren!

Auch mit Humor reagieren. Disziplinierungsmethoden vermeiden, manchmal genügen non-verbale Reaktionen. Gelbe, rote Karten (wie im Fußball).

Viele Konflikte entstehen nicht als Konfrontation gegen mich. - Bsp. Trainingsraum (mit Aufsicht). Tolle Idee. Bibliothek - Rückkehrprotokoll, S. schreibt auf, was er besser machen muss. S. gehen auch freiwillig. Konsequenz für Eltern: ins Boot holen. Wird die Auszeit zum Ritual? Gibt's Veränderungen bei den S.?

Konflikt: S lassen mich kaum ausreden, fallen mir ins Wort. Rede ich prinzipiell zu viel? Wissen die Schüler, wie sie mich auf die Palme bringen? 

* Worum geht es?
Konflikte / verschiedene Ebenen:
Sachebene, Machtebene, Beziehungsebene

Hinter einem Konflikt stehen Bedürfnisse - erkenne ich sie?

Anerkennung? Hohe Werte werden verteidigt (manchmal mit Gewalt); die Sachebene ist leicht erkennbar. Die wirkliche Ursache liegt tiefer; "Kannst du mir meine Grenzen aufzeigen?"

* Wie geht es?
Bedürfnisse / Interessen / Ziele knallen aufeinander (moderieren)

hitzig (deeskalieren) oder kalt (oder zur Sprache bringen, wenn zB eine Klasse verweigert)

Tendenz zur Eskalation (Dynamik stoppen)

Bsp. Frank - "So, jetzt noch einmal: wieder raus und mit freundlicher Begrüßung und Entschuldigung!" Auch den anderen gegenüber. (Kinder betteln um Struktur.) Auch wenn es unnötig ist, mache ich es trotzdem.

Wie ich reagiere, hängt von der Klasse, von Frank, etc ab. 

Öffentliche Diskussionen nicht günstig / oder gar Drohungen; selbst wenn ich meine Macht ausspiele, verliere ich.

Ausweg: Metakommunikation; dh nicht in den direkten Kampf treten, sondern zu moderieren und deeskalieren.

* Konflikte verhindern
strikte Trennung von Person und Verhalten

Zuhören, ruhig bleiben, durchatmen

Eigene Gefühle kontrollieren

* Mit welchem Status?
1: Freundlich und bestimmt "Was habt ihr denn auszutragen?"
2: bestimmt - Erwartung "Ich erwarte mir, ..."
3: Aufforderung "Ich möchte, dass ihr aufhört, dass ..."
4: Befehl "Hört sofort auf ..."
5: Macht "Stopp! Auseinander!"

Es gibt keinen richtigen Status; hängt ab, ich welchem Status der Schüler ist.

Persönliche Präsenz; man kann es üben - das ist tröstlich. 

* Bsp. "Könntest du lesen?" - "Sicher nicht!"
Lehrer fassungslos - Schüler duzt Lehrer - Vorlesen ist generell Überforderung. Deeskalation durch Druck herausnehmen. Orientierung, Stabilität, Halt geben. Berechenbares Verhalten von Seiten des Lehrers. 

* Übung Präsenz
Körperhaltung, gerade, Blickkontakt "So redest du nicht mit mir!"

Blickkontakt, feste und ruhige Stimme ändert.

* Wenn Unterricht nicht mehr möglich ist
L wird ignoriert; aus AB werden Papierflieger; Lärmpegel ist sehr hoch; "Thema ist Scheiße!" Frau Mayer sind wir schon los geworden, das schaffen wir mit ihnen auch nicht.

Reaktionen:
- Lehrer sitzt da und schaut, reagiert nicht.
- L. nimmt Notenliste und trägt Minus ein.
- L. steht mir der Klasse im Flur.
- Hände hoch, wenn ich bereit bin.
- Klassenbuch auf den Tisch dreschen. Oder mit der Hand auf den Tisch schlagen?
- Paradoxe Intervention (geht aber nur einmal)

Eigentlich braucht es ein Klassenlehrerteam - als Einzelkämpfer ist man verloren. Sich nicht scheuen, mit Kollegen bereden.

Bedeutung des Anfangs - einer Stunde; des Schuljahres; Rollenklärung; ...

Falle: Machtkampf mit der Klasse; SJ irgendwie durchstehen; "Ist ihr Problem..."

Fazit: dem Autoritätsverlust vorbeugen
- keine unsinnigen Vorgaben
- kein Machtkampf
- Differenziertes Vorgehen nicht "zu starke" Reaktionen bei "Kleinigkeiten"
- "Scheinkonflikte" als solche erkennen
- handeln statt reagieren
- Körpersprache: mit Klarheit stoppen
- mit Respekt Verbindung halten
- Weiterführung "neue Autorität"
- Rituale am Beginn der Stunde (RU: Gebet; Fantasiereise, ...)
- "Classroommanagement"


* Weiterführung "Neue Autorität"
Sieben Säulen:
- Präsenz &
- Selbstkontrolle & Eskalationsvorbeugung
- Unterstützungsnetzwerke
- ... & Gewaltloser Widerstand
- Gesten der Wertschätzung
- Transparenz
- Wiedergutmachung

Quelle: Steinkellner H., H. Ofner (2011)

* Hilfestellungen
PH: Supervision (kostenfrei)

* Umgang mit Emotionen
Wenn heiß - Ruhe - Intervention: Deeskalation; Zeit geben; 

Wenn kalt - Präsenz, Klarheit - Intervention: ...

* Bsp. Mobbing
S / Opfer erfahren furchtbares, meist auch außerhalb des Unterrichts; "nur Spaß"; Unterstützer für "Gewinner"; Machtkämpfe;

Konflikt wird zum Mobbing bei Schädigungsabsicht; Wiederholungen; Machtungleichgewicht; Hilflosigkeit.

(Was tun, wenn L. es nicht sieht, oder sehen will; und den Konflikt umdrehen?)

Mobbing muss gestoppt werden, nicht moderieren! Dh. nicht diskutieren, es werden keine Ausreden akzeptiert; es wird nicht ignoriert; nicht resigniert; ...

Stärkung des Opfers; als Lehrer bitte hinschauen; ...

Do's: Kaputte Schallplatte, Präsenz; Stopp; Konsens im Kollegium; 
