#+title:      Konferenz
#+date:       [2025-02-03 Mo 16:52]
#+filetags:   :schule:
#+identifier: 20250203T165239

* Notenkonferenz

* Interessensfächer

** Lehrplan
Für nächstes Schuljahr muss es bis Juni einen Lehrplan erstellt werden (pro IF)
Sollten alle mitarbeiten, wäre es zu viel - besser: nur Interessierte, selber organisieren.

** Was wird angeboten?
Es werden aber leider immer Schüler geben, die übrig bleiben und irgendwas wählen, mit dem geringsten Widerstand.

- English 1+2
- Biologie 1+2
- GW
- GS
- Forschen und Entdecken
- GZ 1+2
- ECDL
- Krippenbau
- Kunst + Kreativ
- Outdoor (Sport!)
- Geräteturnen
- Tanz
- Werken 1+2 (Werken 1 ist Voraussetzung für W2)
- Helping Hands
- Nähenwerkstatt
- Kochen (Freitag NM); Küche im Poly ist klein (nicht mehr als 10 pro Gruppe)
- Fotowerkstatt?
- Mutlimedia?
- Spanisch (2 Gruppen; 2wöchig)
- Französisch (ich; wie viele Gruppen? max. 15)
- Theater (wer? Flo)



* Schulbücher
Bis wann? Anfang März / vor Ostern.
NT für erste Klassen
Ev. Bibel?

* Gangaufsichten
Va Container -
Im Mädel WC Heizkörper auf 30 Grad - viele Mädels dort.
Jetzt viel Lärm; Schüler rennen; ...

Tischtennistische?
Wer stellt sie auf? Wer räumt sie auf? Kinder + Turnlehrer? Aufsichtslehrer. Als Zusatzangebot für jene Schüler, die im Turnsaal Pause machen?

* Verkehrslage
Zufahrtsstraße sollte nicht mehr für Eltern zugänglich sein. Beschwerde von umliegenden Bewohnern. Für die Sicherheit ist Gemeinde und Polizei zuständig. Besonders LKW sind gefährlich! Nur eine Frage der Zeit, bis ein Unfall passiert!

Wenn die Schule fertig ist, sind 17 Parkplätze geplant, bei mehr Lehrer an der Schule? geht sich doch aus?

* Gesunde Jause
Nach den Ferien wieder Verkauf; nur mehr belegte Brote plus Obst. 

* Nächster Termin
Dienstag, 25.02 (schon!?), 16h00; max 90 Minuten (durchgehend von 07:45!!!)
Eugen Würz, Friedensbüro; Resilienz für Lehrer; Supervision Angebote von Seiten der BD.

* Reiseabrechnung
Für Fortbildungen, muss vorher erledigt werden!

* Container allgemein
2c; es ist allgemein laut, Lichter wackeln; z.B. 2a.

Thermostat im EDV Raum 16 Grad; bleibt auf 16 Grad. 1a sehr heiß; 4c sehr kalt. Verbindungsgang?

Physikraum - leider heute viermal pro Stunde. 

* Ansuchen für kulturellen Förderung

* Allfälliges
Lesung, nach den Semesterferien; 21.2. Peter Fuschlberger mit Autor, 3 Euro pro Person. Infozettel.
Dritte Klassen um 08:30-...?
Vierte Klassen um 10:00-12:15?

Respektvolles Verhalten! Ruhe im Gang!

Helmut Pichler! Donnerstag!

Musik Aufnahmeprüfungen am Donnerstag 07:45-12:30




