#+title:      Heilige Drei Könige
#+date:       [2025-12-05 Fr 12:03]
#+filetags:   :weihnachten:
#+identifier: 20251205T120319


* Wiederholung
Kinder erzählen von ihren Ferien, eventuelle Erfahrungen beim Sternsingen aufpassen: Kinder werden über Geschenke wetteifern. Und die wenigsten werden bei den Sternsingern mitgewirkt haben. Fragen kann ich sie immer.

* Erarbeitung
Heilige drei Könige:
Text aus dem Evangelium Mt 2,1-12

Sterndeuter: 
 - Angehörige der persischen Priesterklasse; "Walter einer eigentlichen Religion"; Philosophie;
 - Inhaber; Ausüber eines übernatürlichen Wissens
 - Zauberer
 - Betrüger und Verführer

Das religiöse Suchen kann sich für Gott und Jesus öffnen - da spendet es Hoffnung und Heil. Wendet es sich gegen Gott, wird es dämonisch und zerstörerisch. Hier zeigt sich die Ambivalenz des Religiösen. 

Die Magier in Mt gehören den ersten beiden Möglichkeiten an: religiöses und oder philosophisches Wissen, das den Weg zur Erkenntnis Jesu öffnet. Weltall: Konjunktion von Jupiter und Saturn im Sternbild der Fische ("Stern") in den Jahren 7-6 v. Chr. Diese Magier könnten Sternkundige gewesen sein. Damit ein Stern auf einen neuen König verweist, muss es eine Verheißung gegeben haben. Zur Zeit Jesu gab es Erwartungen, dass aus Judäa der zukünftige Herr der Welt hervorgehen werde. Diese Menschen waren "Weise", Menschen der inneren Unruhe, der Hoffnung: auf der Suche nach dem Wahren, dem wahren Gott - also Philosophie im eigentlichen Sinn. Im Suchen nach Christus geht es um das Überschreiten jeder Wissenschaft. Ähnlich wie Abraham. Vgl. Ps 72,10 und Jes 60: aus den Magiern werden Könige (und damit die Kamele und Dromedare). Die drei Magier / Könige stellen die drei bekannte Kontinente dar: Europa, Afrika und Asien. Plus die drei Lebensalter: Jugend, Reife, Alter. Die drei Weisen sind ein Anfang - den Aufbruch der Menschheit auf Christus hin.   
Sie suchen Wahrheit; heute würden wir Wissenschaftler sagen. Auf jeden Fall sind es Menschen auf der Suche. 

Stern: 
gibt Orientierung; erfreut uns; weckt unser Staunen über die Größe des Weltalls; 
Zur Zeit Jesu, genauer: in den Jahren 7-6 v. Chr. gab es eine Konjunktion der Planeten Jupiter, Saturn und Mars (Johannes Kepler; wird auch von modernen Astronomen geteilt). Dieses Ereignis gab es auch im Jahre 1604, plus eine Supernova. In China entdeckte man im Jahre 4. v. Chr. einen hell leuchtenden Stern, der über längere Zeit hin sichtbar war. Jupiter steht für den babylonischen Hauptgott Marduk, Saturn für das Volk der Juden. 
Die drei Weisen müssen auch innerlich auf der Suche nach dem Stern gewesen sein. 

Der Kosmos spricht von Christus. Die Schöpfung gibt dem Menschen eine Ahnung vom Schöpfer - aber wir können sie nicht vollständig enträtseln. Die Hoffnung, dieser Gott möge sich zeigen. Der Mensch soll und kann diesem Gott entgegen gehen. 

Die Weisen kommen durch den Stern zunächst nur bis Judäa und gehen nach Jerusalem, denn nur dort kann der neue König geboren sein. Sie benötigen das Zeugnis der Heiligen Scrhiften, um endgültig den Weg zu finden. "König der Juden" ist heidnischer Ausdruck; Juden würden "König Israels" sagen. "Es erschrak ... ganz Jerusalem": verständlich - wenn es einen neuen König gibt, dann geht es Herodes an den Kragen; und dieser wird seinen Thron nicht kampflos überlassen, was nur Schlimmes für die Einwohner Jerusalems bedeuten kann. Gott stört die zufriedene Alltäglichkeit. Micha 5,1; 2 Sam 5,2. Das Große kommt aus dem irdisch Geringen. Warum erkennen zwar die Schriftgelehrten dies, ziehen daraus aber keine prakischen Konsequenzen? 

huldigen: 
verehren, sich niederwerfen. Die Weisen werden von großer Freude erfüllt: ihre Hoffnung bewahrheitet sich, sie finden und werden gefunden. Es fehlt Josef? Vll erinnert Mt an die Jungfrauengeburt Jesu und an seine Gottessohnschaft. Proskynese - Niederwerfen auf die Erde: nur vor dem Gott-König.   
Gaben: Gold (König; unser Herz), Weihrauch (Gott; unser Gebet), Myrrhe (Begräbnis; Heiland; was ist wund in uns?) Als die Frauen am Morgen Jesus salben wollen (dem Tod entegegenwirken), ist Jesus schon auferstanden: er braucht die Myrrhe nicht. Die Weisen gehen auf einem anderen Weg heim in ihr Land: die Begegnung mit Jesus verändert unser Leben.

*****

*WJT Köln 2005:*

JP2: Botschaft - "Wir sind gekommen, um ihn anzubeten (um ihm zu huldigen)" (Mt 2,2)
Könige ließen alles hinter sich, um dem Stern zu folgen; unbekannte, gefährliche Reise. Stern zog vor ihnen her: sie ließen sich vom Stern führen - Zeichen Gottes erkennen. Wer Gott folgt, erfährt eine echte und tiefe Freude. 

Dieses Kind ist anders: der eingeborene Sohn Gottes. Gott erniedrigt sich, wurde Mensch und starb am Kreuz Dankbarkeit gegenüber Gott?!

Bethlehem: Haus des Brotes Eucharistie. Das Weizenkorn stirbt und bringt Frucht. "Ich bin das Brot des Lebens". Weg der Armut Jesu: von der Krippe bis zur Verlassenheit am Kreuz welche Liebe Gottes zu uns. Derselbe Erlöser der Krippe und des Kreuzes ist in der Eucharistie gegenwärtig. Jesus ist im Fleisch, im Blut, in der Seele und in der Gottheit anwesend Er gibt sich uns als Speise, wir beten ihn an. 

Zögere nicht, ihm in der Liebe zu antworten. In der Eucharistie Jesus als unseren Schöpfer, Herrn und Heiland anerkennen und anbeten, symbolisiert durch die drei Gaben: 

 - Gold: die königliche Gottheit Jesu das Gold unseres Lebens - die Freiheit darbringen, Gottes Ruf folgen. 
 - Weihrauch: Jesus ist Priester des Neuen Bundes Weihrauch unseres Gebets.
 - Myrrhe: Jesus ist Prophet, der durch sein Blut die Menschen mit dem Vater versöhnt dankbare Zuneigung.
 
Wahre Anbeter Gottes sein - Gott hat die erste Stelle in meinem Leben. 

[[http://w2.vatican.va/content/john-paul-ii/de/messages/youth/documents/hf_jp-ii_mes_20040806_xx-world-youth-day.html][cf Botschaft JP2 für WJT Köln 2005]]

*****

*B16 Ansprache / Predigt*

Wenn die Weisen in Bethlehem ankommen, ist ihr äußerer Weg zu Ende, der innere Weg beginnt mit der Anbetung Jesu, welcher ihr ganzes Leben verändert: sie haben sich den neuen König sicher anders vorgestellt. Gott ist anders als wir ihn gewöhnlich uns vorstellen. Gottes Macht ist die wehrlose Macht seiner Liebe, die am Kreuz unterliegt und doch das Göttliche ist, Gottes Reich herauuführt. Gott ist anders wir müssen selbst anders werden, Gottes Art erlernen.

Jesus als König fordert von uns als Gabe: wir selbst, unser Leben. Sie müssen Menschen der Wahrheit, des Rechts, der Güte, des Verzeihens, der Barmherzigkeit werden. Frage: Womit diene ich der Gegenwart Gottes in der Welt? (nicht mehr: was bringt das mir?). Wer sich verliert, der findet sich. 

Was bedeutet das für mich? Gott gibt Beispiele. Die große Schar der Heiligen. Sie haben nicht nach ihrem Glück gesucht, sondern erforscht, wie sie sich hingeben können. Sie waren vom Licht Christi getroffen worden. so wird man glücklich, ein Mensch. 

Die wahre Revolution kommt von Gott her. Wer Gott weglässt und menschliche Maßstäbe absolut setzt Totalitarismus. Dies macht den Menschen nicht frei, sondern versklavt ihn. Die wahre Revolution geschieht in der radikalen Hinwendung zu Gott. 

Das wahre Antlitz Gottes: "Wer mich sieht, sieht den Vater!" (Joh 14,9) Also kein privater Jesus, sondern jener Jesus der Heiligen Schrift, der Kirche. Jesus ist gleichzeitig mit uns und vor uns. Kirche ist eine menschliche Familie UND die Familie Gottes, mit dem Weizen *und* dem Unkraut das ist tröstlich. Jesus hat die Sünder berufen. 

[[http://w2.vatican.va/content/benedict-xvi/de/speeches/2005/august/documents/hf_ben-xvi_spe_20050820_vigil-wyd.html][B16 WJT Köln 2005 Ansprache Vigil]]

******

Taufe Jesu (Mk 1,7-11)

Text lesen / versteckte Symbole entschlüsseln / "Du bist mein geliebter Sohn, an dem ich Gefallen gefunden habe." / Offenbarung der göttlichen Dreifaltigkeit.

eigene Taufe: Christen durch Salbung (Öl) - Christus, der Gesalbte. Symbol des Öls: Heilung, dringt ein, bleibt, schützt Haut, ... Hl. Geist, Gottes Gnade dringt ein, bleibt, heilt; macht mich fähig, am Gottesdienst teilzunehmen / teilzuhaben. Geschenk des Glaubens.

*Was ist Gnade?* Cf [[https://www.youtube.com/results?search_query=3mc+gnade][3MC YouTube "Gnade"]] 

-----

* Gott offenbart sich
:PROPERTIES:
:CUSTOM_ID: offenbarung
:END:

[[#01]]
Videos aus der Reihe "3MC" zum Thema Offenbarung

 - Warum offenbart sich Gott?
 - Wie hat Gott sich offenbart?
 - Wie wurde die Offenbarung weitergegeben? (Geschichte des Volkes Israel / Schrift / Tradition)
 - Wie ist die Bibel aufgebaut?
 - Wer hat bestimmt, welche Bücher in die Bibel aufgenommen wurden?

Hefteintrag: Zusammenfassung der Videos.

* Hefteintrag
(Text überlegen!): 

Geschichte vom vierten König vorlesen: Bilder einscannen.
Zusammenhang erkennen zwischen Weihnachten und Ostern: sonst verkommt Weihnachten zum "Kitsch". 
Warum ist Gott in Jesus Mensch geworden? Um uns zu erlösen. Weihnachten steht nicht für sich allein, sondern ist auf Ostern hingeordnet. Das Hochfest der Epiphanie (Heilige Drei Könige) ist das älteste Fest des Kirchenjahres. Was fällt den Schülern zum Thema "Stern" ein? Hier offenbart sich Gott der ganzen Welt; die Geburt, das Kommen der Hirten - da blieb noch alles irgendwie "geheim". 
