#+title:      Themen für Ostern
#+date:       [2025-04-15 Di 09:59]
#+filetags:   :schule:
#+identifier: 20250415T095936

* Osterevangelien
Ostern ist komischerweise etwas schwieriger im RU zu behandeln als die Leidensgeschichte Jesu, Wunder oder Weihnachten. Denn die Auferstehung Jesu passt nicht in unsere Erfahrungen, ist "etwas" komplett anderes. Und sie verändert unsere Sicht auf die Realität, mit ihr beginnt wirklich ein neues Leben.

In diesen Monaten bis zu den Ferien gebe ich noch einmal Vollgas; 

* Emmausjünger

* Tatsache der Auferstehung Jesu (YouCat - Firmung)
Dazu gibt es eine komplett ausgearbeitete Stunde, es gibt ein Video mit Johannes Hartl (eigentlich zwei).

Die wissenschaftlichen Details der Auferstehung; Soldaten als Zeugen; "Er sah und glaubte." Was sah er? Das Tuch, die Binden und das Schweißtuch, das auf dem Kopf Jesu gelegen hatte. Sah er ev. die Abdruck des Leibes Jesu auf dem Tuch? Wie lagen die Tücher?



** Hat Jesus wirklich gelebt?

** Ist Jesus wirklich am Kreuz gestorben?

** War das Grab leer?

** Erscheinungen - echt?

** Glaube verbreitet rasch sich im Land der Augenzeugen

* Apostel Paulus
Hab ich den Paulus-Film?

** Bekehrung

** Briefe

** Bedeutung für die Kirche

* Apostelgeschichte


* Pfingsten / Hl. Geist / Charismen

* Was finde ich den Schulbüchern?

* (4. Klasse) Glaube - Hoffnung - Liebe
Nach der Schule - ohne RU - Firmung

Was macht ihr nachher, um in Glaube / Hoffnung / Liebe zu wachsen?

** Was ist eine Tugend?
Was ist Eine göttliche Tugend?
Ist eine Gabe, verlangt "Training" (wie im Sport, Musik, ...).

Die nächsten Stunden sind entweder in zwei Teilen oder zwei Stunden.

** Glaube
- Objekt des Glaubens
- Wie wachse ich konkret im Glauben?

** Hoffnung
- Objekt der Hoffnung?
- Wie wachse ich in der Hoffnung?

** Liebe
- Objekt der Liebe?
- Wie wachse ich in der Liebe?
