#+title:      B Klasse 2025-29 Mattsee
#+date:       [2025-09-13 Sa 11:06]
#+filetags:   :1b:ms:
#+identifier: 20250913T110647
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/1b Mattsee.html

* Jahresplanung

[[denote:20250913T113018][Religion für uns 01]]

* Notizen, Tasks, Termine


* Stundenplanung


** Die letzte Woche Jesu in Jerusalem

- Palmsonntag
- Gründonnerstag
- Karfreitag
- Karsamstag
- Osternacht

Synoptiker für Einzug in Jerusalem und Letztes Abendmahl; Johannes für Fußwaschung, Abschiedsreden Jesu, Paraklet, neues Gebot Jesu, Jesu Gebet (Joh 17); 

Liturgie Palmsonntag, Gründonnerstag, Karfreitag; Keine Liturgie am Karsamstag. Osternacht. 

** Mit dem YouCat arbeiten

Juhuu - die YouCat sind angekommen; werde gleich einmal in der 1b damit anfangen; ebenso in der 4b. Einfach von Anfang an lesen - es kommen sicher Fragen. Die Schüler sollen die wichtigsten Sätze notieren. In den ersten und zweiten Klassen brauchen sie eventuell Unterstützung. Die 4b kann / soll selbst ein Thema auswählen.

Thema für alle Schüler - mein großes Anliegen: sie sollen lernen, intelligente Fragen zu stellen. Dazu braucht es Bildung und Wissen. Wer einem System intelligente Fragen stellen kann, wird auch intelligente Antworten erhalten. KI und ChatGPT erleichtern z.B. das Erledigen von Hausübungen, Erstellen von Texten, etc. Aber - woher weiß ich, dass diese Infos stimmen? Wie intelligent ist eine KI? Was hat eine KI nicht, was wir Menschen sehr wohl haben? Richtig: ein Bewusstsein, Gefühle, eine unsterbliche Seele. Leider gibt es zu viele Beweise, dass KI in Verbindung mit Robotern dem Menschen nicht wohlgesonnen sind. Sie sind bereit, den Menschen auszulöschen.

Keine Angst - unsere Hoffnung ist Jesus. 

* Reflexionen

** Achleitner Tobias 

** Altendorfer Elena 

** Altendorfer Fabian

** Angermayr Nico

** Baumann Natalie 

** Dirnberger Johannes 

** Dürager Nina

** Fischer Charlotte

** Hinterberger Maximilian 

** Keidel Amelie 

** Kobliha Benedikt

** Lindner Ella 

** Oberholzer Nicole 

** Reinfeld Eliah 

** Resch Tobias

** Ritsch Matthias

** Schwaiger David 
