#+title:      D Klasse 2023-27 Seekirchen
#+date:       [2025-09-08 Mo 08:12]
#+filetags:   :3d:sk:
#+identifier: 20250908T081215
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/3d Seekirchen.html

* Jahresplanung

[[denote:20240709T110253][Zeit für Religion 03]]


* Webuntis
[[https://hypate.webuntis.com/WebUntis/#/basic/login]]

* Notizen, Tasks, Termine


* Stundenplanung

** Der große Unbekannte - der Heilige Geist

Cf YouCat Firmbuch

- "Wer bin ich?" spielen
- Juden; modernste Religion (an einen Gott; Griechen, Römer, ...)
- Jesus: Gott - Vater; Hl. Geist.
- Bei der Taufe empfing Jesus nicht eine anonyme Energie, sondern hier wird seine Beziehung zu Gott sichtbar. Gott schenkt sich selbst, mehr oder weniger kann Gott nicht geben. 
- Hl. Geist ist Gott, wie Vater und Sohn. Er ist die Liebe. Er verbindet uns mit Christus und die Gläubigen untereinander.
- Wäre toll, wenn in unserem Herzen nur Liebe wäre.
- Versuche einmal, in deinem Zimmer für 5 Minuten nur still zu sein. Was steigt da in deinem Herzen auf? Lasse dies zu, auch die Leere. Dort will Gott wohnen.
- Gott hat uns so erschaffen, dass unser Herz mit nichts zufrieden ist, außer mit Gott.
- Joh 20 und Apg 2 lesen: er vertreibt die Angst; wir könne Dinge tun, die wir alleine nicht schaffen; Von Jesus erzählen.
- Früchte des Hl. Geistes
- Gebet zum Hl. Geist

** Ostern / Auferstehung
YouTube Video von Johannes Hartl: [[https://www.youtube.com/watch?v=EEtOLeIrshI]] & 
[[https://www.youtube.com/watch?v=qVyiSLjKj80]] 
[[https://www.youtube.com/watch?v=QHEKYZYoCbY]]
[[https://www.youtube.com/watch?v=r7YJOBtnK5w]]

Jesus - mehr als ein Prophet? [[https://www.youtube.com/watch?v=2UGhH4EmBOY]]

Faktencheck zur Auferstehung
- Jesus hat nicht gelebt
Außerbiblische Zeugnisse über Jesus

- Jesus starb nicht am Kreuz
Römischer Soldat weiß, was er zu tun hat.

- Erscheinungen erfunden
Für eine erfundene Geschichte ist kein Mensch bereit, sein Leben zu riskieren. Und Kreuzestod Jesu und Auferstehung ist als Geschichte nicht nur mittelmäßig cool.

- Berichte unglaubwürdig
Vom NT gibt es 5668 Handschriften, die frühesten stammen aus dem Jahre 50. (Vgl.: Julius Cäsar - über den gallischen Krieg - aus dem 10. / 11. Jahrhundert)

Lesen: Joh 20

Außerbiblische Quellen:

*** Flavius Josephus

Als Testimonium Flavianum bezeichnet man den 93 n. Chr. verfassten Abschnitt im Buch 18, Verse 63–64 aus den Antiquitates Judaicae des Flavius Josephus:

#+begin_quote
"Um diese Zeit lebte Jesus, ein weiser Mann, wenn man ihn überhaupt einen Menschen nennen darf. Er vollbrachte nämlich ganz unglaubliche Taten und war der Lehrer aller Menschen, die mit Lust die Wahrheit aufnahmen. So zog er viele Juden und auch viele Heiden an sich. Dieser war der Christus. Und obgleich ihn Pilatus auf Betreiben der Vornehmsten unseres Volkes zum Kreuzestod verurteilte, wurden doch seine früheren Anhänger ihm nicht untreu. Denn er erschien ihnen am dritten Tage wieder lebend, wie gottgesandte Propheten dies und tausend andere wunderbare Dinge von ihm vorhergesagt hatten. Und bis auf den heutigen Tag besteht das Volk der Christen, die sich nach ihm nennen, fort.[7]"
#+end_quote

*** Tacitus

Tacitus war schon zu Lebzeiten nicht nur als erfolgreicher Politiker, sondern auch als römischer Historiker bekannt. Er schrieb 116–117 seine teilweise recht kaiserkritischen Annalen, deren Bücher 13–16 die Regentschaft Neros beschreiben: Auf die ruhigen Anfangsjahre (A. 13) sei mit dem Brand Roms 64 eine Tyrannei gefolgt (A. 14–16). Nero habe vergeblich versucht, den Verdacht, er selbst habe die Brandlegung befohlen, durch alle möglichen Anstrengungen zu beschwichtigen. In diesem Zusammenhang erwähnte Tacitus die Christen:

#+begin_quote
„Um das Gerücht aus der Welt zu schaffen, schob er die Schuld auf andere und verhängte die ausgesuchtesten Strafen über die wegen ihrer Verbrechen Verhassten, die das Volk ‚Chrestianer‘ nannte. Der Urheber dieses Namens ist Christus, der unter der Regierung des Tiberius vom Prokurator Pontius Pilatus hingerichtet worden war. Für den Augenblick war [so] der verderbliche Aberglaube unterdrückt worden, trat aber später wieder hervor und verbreitete sich nicht nur in Judäa, wo das Übel aufgekommen war, sondern auch in Rom, wo alle Greuel und Abscheulichkeiten der ganzen Welt zusammenströmen und gefeiert werden.“[30]
#+end_quote

*** Plinius der Jüngere

Plinius war seit etwa 111 als Statthalter in Bithynien (heute İzmit, Türkei) für Anzeigen aus der Bevölkerung gegen dort lebende Christen zuständig. In einem Briefwechsel mit Kaiser Trajan, den er später in seine zehnbändige Briefsammlung aufnahm (Plinius-Briefe), holte er sich rechtliche Bestätigung für sein Verfahren mit ihnen. In epistula X/96 beschrieb er seine Verhörmethoden, die ihm bekannt gewordenen christlichen Bräuche und seinen Eindruck von ihrem Glauben:[32]

#+begin_quote
„Denen, die bestritten, Christen zu sein oder gewesen zu sein, sprach ich die Formel vor und ließ sie die Götter anrufen und zu Deinem Standbild […] mit Weihrauch- und Weinspenden beten und außerdem Christus lästern. Daraufhin konnten sie meines Erachtens freigelassen werden. Denn zu all dem sollen sich wahre Christen nicht zwingen lassen. […]

Sie versicherten, ihre ganze Schuld oder ihr Irrtum habe darin bestanden, dass sie sich regelmäßig an einem bestimmten Tag vor Dämmerung versammelten, um Christus als Gott ein Lied darzubringen und sich durch Eid zu verpflichten – nicht etwa zu einem Verbrechen, sondern zur Unterlassung von Diebstahl, Raub, Ehebruch, Treulosigkeit, Unterschlagung von anvertrautem Gut.

Umso mehr hielt ich es für notwendig, von zwei sogenannten ‚Dienerinnen‘ die Wahrheit auch noch durch Folter zu erforschen. Ich fand nichts als absurden, maßlosen Aberglauben. […] Denn nicht nur über die Städte, auch über die Dörfer hat sich die Seuche dieses Aberglaubens verbreitet. Doch es scheint möglich, sie einzudämmen und auszutilgen.“
#+begin_quote


** Emmausjünger

Lk 24 lesen und Bildergeschichte zeichnen - Bezug zu Eucharistie herstellen

* Reflexionen

** Altmann Kristin

** Eckschlager Amelie

** Ferao Mbelani Sidonia

** Kaltenbrunner Tobias

** Karas Zita

** Klinger Valerie

** Lerchner Gregor

** Mathwich Lina

** Nobis Levi

** Petrovic David

** Pöschl Andreas

** Seidl Raphael

** Selimi Ensar

** Stangl Emma

** Wessely Amelie

** Wessely Isabella

** Wirths Levi

** Zdraljevic Jovana
