#+title:      D Klasse 2025-29 Seekirchen
#+date:       [2025-09-08 Mo 08:05]
#+filetags:   :1d:sk:
#+identifier: 20250908T080546
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/1d Seekirchen.html

* Jahresplanung

[[denote:20240719T125948][Zeit für Religion 01]]


* Webuntis
[[https://hypate.webuntis.com/WebUntis/#/basic/login]]

* Notizen, Tasks, Termine

* Stundenplanung

** Arbeiten mit der Bibel

alte und neue Schätze der Kirche

Komisch - bis ins 20. Jahrhundert brauchte die Kirche nicht die "neuen" Schätze, oder? Warum jetzt? Weil sich die Welt so sehr verändert hat? Weil die Welt, die Gesellschaft, in der wir leben, nicht mehr so christlich geprägt ist, "wie früher"? Es ist nicht weise zu sagen, früher wäre alles besser gewesen. In den "guten, alten Tagen" hat man nicht so geredet, dass es früher besser war / oder dass es später besser werden wird. Woher willst du wissen, dass es früher besser war? Wie gesagt, dieser Satz zeugt nicht von Wissen. 

Firmung 

Bibel lesen - Berufung der ersten Jünger (Lk 5)

Evangelium - Berufung von Matthäus; Jesus ruft Sünder, nicht die Gerechten (Lesung Hosea).
Fronleichnam - Eucharistie

** Dreifaltigkeit

Bibel
Bild dreiblättriges Kleeblatt; Videos von Kathmedia


* Reflexionen

** Braunstein Fabian

** Burda Felix

** Dezsi David-Andreas

** Fekete Anna

** Halilaj Tara

** Hillerzeder Julia

** Lugstein Greta

** Maxbauer Anna

** Mikalauskas Tadas

** Mösl Jakob

Hat kein Tablet mit / nicht aufgelsaden; nuckelt an seiner Flasche; akzeptiert keine Anweisungen; 

** Müller Sophia

** Rack Valentin

** Ruf David

** Sailer Marcel

Stört wieder massiv; nuckelt an seiner Flasche; akzeptiert keine Anweisungen; 

** Stemeseder Ella


