#+title:      B Klasse 2024-28 Seekirchen
#+date:       [2025-09-08 Mo 08:15]
#+filetags:   :2b:sk:
#+identifier: 20250908T081510
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/2b Seekirchen.html

* Jahresplanung

[[denote:20240708T214317][Zeit für Religion 02]]

#+BEGIN: denote-links :regexp "_02_religionen" :not-regexp nil :excluded-dirs-regexp nil :sort-by-component nil :reverse-sort nil :id-only nil :include-date nil
- [[denote:20250906T125646][Das Judentum entdecken / Das Leben feiern]]
- [[denote:20250906T125657][Im Glauben an den einen Gott]]
- [[denote:20250906T125715][Höre Israel!]]
- [[denote:20250906T125724][Ein Teil von uns]]
#+END:



* Webuntis
[[https://hypate.webuntis.com/WebUntis/#/basic/login]]

* Notizen, Tasks, Termine


* Stundenplanung

** Jesus und die Samariterin am Jakobsbrunnen

(Episode aus The Chosen - hoffentlich klappt das Internet in der Klasse!)

Joh 4 lesen.  + The Chosen Staffel 1 Episode 8

(Staffel 5 online verfügbar!)

Lebendiges Wasser - Gottes Liebe, Gottes Geist; Anbetung in Geist und Wahrheit.

Die große Frage - was erwartest du dir von Gott?
"Was willst du, dass ich dir tue?" - Frage von Jesus an Bartimäus.

Schüler sollen sich mit dieser Frage auseinandersetzen, sie an sich heran lassen. Und ihre Erwartungen formulieren. Aufschreiben. Die "Gefahr" ist, dass die Kinder sagen "nix!" - und meinen, damit den Auftrag erfüllt zu haben; "Können wir jetzt Kahoot spielen?" - So leicht lasse ich die Kinder nicht aus ihrer "Pflicht". Wer nichts von Gott erwartet, wird auch nichts von Gott erhalten. So wie der ältere Sohn im Gleichnis vom verlorenen Sohn. Er bleibt in seiner Welt der Gerechtigkeit; fragt nach nichts. Und ist dabei genauso unglücklich wie sein jüngerer Bruder als der die Schweine hütete.

Wie viel schöner ist doch das Leben - wenn du dich von Gottes Liebe berühren lässt?

** The Chosen 

Staffel 5; Episode 1 (Einzug in Jerusalem); Episode 2 (Pascha; Tempelreinigung)

* Reflexionen



** Caillet Sophia

** Fischwenger Nico

** (Grünwald Raphael)

** Günther Anna

** Hartmann Viktorija

** Hoheneder-Ergün Moritz

** Holzer Leon

** Hörl Susanne

** Hutter Sarah

** Jaiteh Lamin

** Lottermoser Oliver

** Lugstein Julia

** Pötzelsberger Daniel

** Reitsamer Noah

** Scheipl Sebastian

** Schindler Gabriel

** Schneider David

** Stein Nora

** Steinberger Anna

** Struber Ennio

** Vielhaber Marlene

** Walkner Maximilian

** Wallner Emily

** Weiß Jakob

