#+title:      Mail an Brüder in Marchegg
#+date:       [2025-04-10 Do 18:03]
#+filetags:   :privat:
#+identifier: 20250410T180323

Lieber Brüder,

nach all zu langer Zeit melde ich mich wieder. Leider sind es keine guten Nachrichten. Ich will es relativ kurz halten. (Ist mir nicht gelungen.)

Dieses Schuljahr bin ich an einer neuen Schule, die Musikmittelschule in Abtenau. Vorher war ca. 8 Jahre an der Mittelschule Golling. In Abtenau wurde eine volle Stelle frei, kam mir entgegen. Beide Orte liegen im Tennengau, Bundesland Salzburg.

Gleich bei meiner Ankunft merkte ich, dass es eine angespannte Atmosphäre gibt, v.a. zwischen Direktorin und Kollegen. Aber ich konnte (noch) nicht herausfinden, woran es lag. Die ersten Gespräche mit der Direktorin waren einigermaßen okay, sie sagte mir, sie sei überzeugte Christin. Das hat mir zu Beginn imponiert und gab mir Mut.

Relativ bald kamen aber Beschwerden von den Eltern, v.a. über wirklich lächerliche Dinge: ich würde den Kindern meinen Glauben aufdrängen, da ich mit den Kindern ein Vaterunser oder ein Ave Maria bete.

Im Laufe der Monate wurden die Beschwerden häufiger, die Direktorin immer negativer mir gegenüber. Die Beschwerden kamen nie direkt zu mir, sondern immer über die Schulleitung. Und waren oft nur unbegründet und lächerlich. manchmal haben mir Kinder Aussagen in den Mund gelegt, die ich nie getätigt hatte; oder sie drehten mir Worte im Hals um.

Im November war es dann so arg, dass ich meine Fachinspektorin anrief. Sie versprach mir zu helfen, leider ging der Schuss nach hinten los. An dem Tag ihres Besuches wurde ich nach meinem Unterricht 2.5 Stunden von der Inspektorin und der Direktorin durch die Mangel gedreht.

Zu Weihnachten ging die Direktorin in Krankenstand und war bis Ende Februar nicht an der Schule. Gleich nach Weihnachten erklärte uns der Vizedirektor, dass er unglaubliche Sachen entdeckt hatte. Die Direktorin hat vor Weihnachten ihn und drei andere Kollegen des Mobbings bezichtigt und diese bei der Bildungsdirektion angezeigt / angeschwärzt. Stellte sich hinterher als falsch heraus, der Schaden war schon angerichtet.

Unsere Direktorin ist offensichtlich psychisch krank, leidet unter Verfolgungswahn, ist mit der Schulleitung sichtlich überfordert und erledigt das mit allerletzter Kraft. Sie verbreitet überall Chaos, redet fruchtbar mit Kollegen, vermischt Privates mit Schule, erzählt fast jedem Kollegen wie schwer alles ist, etc, ... Sie vergleicht sich mit Jesus, der auch gekreuzigt wurde. Meint, sie sei zur Direktorin berufen, obwohl jeder sieht und spürt, wie sie der Aufgabe nicht gewachsen ist. Sie sieht natürlich bei sich keine Schuld, macht immer alles richtig, hat auf alles eine Antwort, immer eine Ausrede parat, und Schuld haben immer die anderen.

Im letzten Gespräch am Dienstag (vorgestern), fragte mich die Direktorin, ob ich ihr glauben könne, dass sie es gut mir meint. Das musste ich verneinen; denn geholfen hat sie mir nicht, im Gegenteil. Mir wirft sie vor, seit ich da bin, seien alle Schüler viel schlimmer, und ich würde dem Ruf der Schule schaden. Außerdem legt sie mir nahe, ab Ostern in Krankenstand zu gehen, denn ich sei krank. Hä? Mein Hausarzt wird mich auslachen, wenn ich als kerngesunder Mensch ihm sage: "Meine Chefin verlangt, sie sollen mich krank schreiben."

Ich hab dann einen Kollegen gefragt, ob diese Aussagen denn stimmen können: er meinte - "Nein, denn du bist nicht am miesen Verhalten der Schüler schuld, und krank bist du auch nicht, krank ist sie selber, und sie schadet dem Ruf der Schule!"

So und jetzt kommt's: meine Vorgesetzten von der Kirche nehmen aber die Aussagen der Direktorin für voll, glauben mir nicht, was ich ihnen über unsere Situation an der Schule erzählt habe, ... und haben aufgrund der Aussagen der Direktorin entschieden, dass ich ab September nicht mehr in Abtenau unterrichten kann. Da es aber gleichzeitig keine offenen Stellen gibt - war es das. Ich muss mir eine neue Arbeit außerhalb der Schule suchen.

Hab noch keine Ahnung, wo und was ich finden werde. Als allerletzte Option wäre das O-Busfahrer, der Gehalt wäre so ähnlich wie jetzt als Lehrer.

Völlig unüblich sind meine Stunden in Abtenau auf Anweisung der Kirche bereits jetzt im April für September ausgeschrieben. Normalerweise geschieht das erst im Juni. Das lässt an der "heiligen" Kirche zweifeln, wenn Vertreter der Kirche mir sagen - wie die Fachinspektorin: "Ich hab schon riesigen Druck von oben, dass ich mich erst jetzt um dich kümmere. Und bevor ich den Job verliere, ..."

Ich hab jetzt die Personalvertretung eingeschaltet, die soll Einsicht in meinen Personalakt einsehen. Man hat mir versichert, dass es nix gibt, was eine Suspendierung (Kündigung) rechtfertigt. Ich will selber eigentlich nicht mehr an diese Schule zurück ...

Bitte betet fest für uns, meine Frau unterstützt mich wunderbar, wir beten gemeinsam. Mir geht's jetzt wirklich nicht gut, bin aber innerlich einigermaßen im Frieden, so gut es eben geht. Die Motivation für die restlichen Monate an der Schule ist nicht gerade groß. Ein unwürdiges und unglaubliches Schauspiel: sowohl die Situation an der Schule, als auch meine Lage. Es ist alles so absurd. Ich darf nicht zu viel daran denken, sonst beginne ich selber an meiner Wahrnehmung der Realität zu zweifeln. Inwiefern der Teufel seine Finger im Spiel hat, will nicht nicht beurteilen, das sollen andere tun; wäre gut möglich, als Religionslehrer steht man wie jeder Verkündiger der Frohen Botschaft in vorderster Linie und wird als Erster angegriffen. Und dort ist der Angriff immer am heftigsten. Bin mir dessen bewusst, aber manchmal ist man wirklich ohnmächtig. Man tut alles was man kann, und wenn dann der schärfste Angriff "aus den eigenen Reihen" kommt (Schulamt der Kirche, und man kann nichts dagegen tun, weil die andere Seite nicht willig ist, seine Sichtweise zu revidieren, dann...)

Vielleicht komme ich ja zwei Tage nächste Woche zu euch ...

Liebe Grüße,
im Gebet verbunden,
Matthias Fuchs
