#+title:      Konferenz Oktober
#+date:       [2025-10-08 Mi 16:00]
#+filetags:   :seekirchen:
#+identifier: 20251008T160055

* IKM Testung
Eig. müssten sich alle L anmelden können. Broschüren; 

* FB / WB Gespräche
Bitte in den nächsten Tagen melden (Formular ausfüllen).

(So wie FI ....)

* Tag der offenen Tür?
Mittwoch, sechste Stunde: Container Klassen leer räumen?

Datum? bis zur dritten Stunde. Falls mir Stunden entfallen, wo kann ich helfen?

* Schulforum
für alle KVs

* UÜ Schwimmen Freilassing
Geht nicht mehr - wir dürfen nur Schwimmer mitnehmen; ...

Achtung: 
Asylwerber (laufendes Verfahren, weiße Karte) dürfen das Bundesgebiet nicht verlassen
Mit grauer Aufenthaltskarte: geht
Ukrainer: ebenso

* Pausenaufsichten
Bitte pünktlich! EG Altbau / Container, meistens zu dritt (draußen, ...) / va Räume drinnen! 

* Klassenbücher (TA + Webuntis)
sind tagesaktuell zu führen

* SPF Anträge
bis Weihnachten stellen

* Abstinenz bei Schülern
Konferenz ... Kinder einem gesunden Stress aussetzen; 

* Info iKlassen
3.11. für iKlassen Lehrer (Henndorf)

* Konferenz Jänner "Krisen"
15.1. Krisenteam / ...
- Suizid
- Todesfall eines Schülers / in der Familie
- Amoklauf
- Amokdrohung
- Blackout
- Bombendrohung
- Brandfall
- ...


* Konferenz November
auf 12.11. verschieben, weil am 15.11. Martinsfest (weil einige kleine Kinder haben; Kindergarten)

* Konferenz Dezember
15.12. + Weihnachtsfeier

* VS Seekirchen
15.10. Fußball National Trainer?

* Termin
16.10. RTS Privat Fernsehen - keine sensible Daten im Konferenzzimmer liegen lassen

* JUZ Seekirchen
ab 11H30; egal welcher Termin

* Gruppenarbeit 

** Weihnachtsfeier
konkret

** Fasching
Dienstag nach SS Ferien

** Schulschlussfeier

** Teams (QMS)

** Schulneubaueröffnung

