#+title:      Werke der Barmherzigkeit
#+date:       [2025-06-17 Di 08:56]
#+filetags:   :theology:
#+identifier: 20250617T085614

(Dazu eine Planung / Stundenbild schreiben)
* Was ist mein Ziel? 
Die Schüler sollen die Bedeutung der Werke der Barmherzigkeit für ein gelungenes Miteinander erkennen und reflektieren, wie sie das im Alltag umsetzen können.

* Umsetzung
Die Schüler sollen mindestens drei Werke der Barmherzigkeit nennen können; eines der Werke auf eine Situation im Alltag übertragen, eine kleine barmherzige Aktion planen oder einen Tagebuch- oder Blogeintrag dazu schreiben.

[[file:~/MMS_Abtenau/Werke der Barmherzigkeit/Werke der Barmherzigkeit_Planung.odt]]

Was braucht es für ein gelungenes Zusammenleben? (10 Gebote, Regeln, ...) Wovon befreien uns die 10 Gebote? Wofür befreien uns die 10 Gebote?

Wenn Jesus wieder kommt, um die Menschen zu richten - wonach wird Jesus uns fragen? Nach den 10 Geboten - hast du gelogen? Bist du am Sonntag in die Kirche gegangen? - Wonach? ... Nächstenliebe ...

Interessanterweise finden wir in der Bibel, im NT, folgenden Text - AB.
Rückseite der Bibeltext Mt 25,34-40

[[file:~/MMS_Abtenau/Werke der Barmherzigkeit/Werke der Barmherzigkeit_Bibeltext.odt]]

Viele leben die sieben Werke der leiblichen Barmherzigkeit, ohne sie alle auf Anhieb aufzählen zu können:

  -  Dem Hungrigen zu essen geben,
  -  den Durstigen zu trinken geben,
  -  die Nackten zu bekleiden,
  -  die Fremden aufzunehmen,
  -  den Kranken beizustehen,
  -  die Gefangenen zu besuchen und
  (-  die Toten zu begraben.)

* Video - 7 Werke der Barmherzigkeit (18 Minuten)

Weniger bekannt sind die sieben geistigen Werke der Barmherzigkeit:

  - Dem Rat geben, der ihn braucht;
  - den lehren, der nichts weiß;
  - den korrigieren, der irrt;
  - den Traurigen trösten;
  - die Beleidigungen verzeihen;
  - die unangenehmen Menschen mit Geduld ertragen; und schließlich
  - beten.

* Hefteintrag / Arbeitsauftrag:

[[file:~/MMS_Abtenau/Werke der Barmherzigkeit/Werke der Barmherzigkeit_Arbeitsblatt.odt]]
