#+title:      Gesprächsnotizen
#+date:       [2025-02-18 Di 11:43]
#+filetags:   :memo:
#+identifier: 20250218T114330
#+STARTUP: fnadjust
#+STARTUP: showall

* Gabriele Kirchschlager

** Memo vom <2024-09-30 Mo>
Heute hat mich Gabi in der 4b besucht - wir haben gerade das Schöpfungsquiz gespielt. Sie blieb nicht lange. Und da ich die wahren Hintergründe ihrer Besuche kenne, bin ich beruhigter. Sie wird nur mehr eine Klasse besuchen, und dann werde ich mich noch mehr beruhigen können. Denn im Moment spüre ich noch eine sehr unangenehme Anspannung; ich fühle mich noch nicht wirklich wohl.

Aber sich auf eine neue Schule einstellen geht eben nicht so schnell.

** Memo vom <2024-10-10 Do>
Das Gespräch verlief so toll und gesegnet. Gabi hat mir aufs Neue versichert, wer sehr sie hinter mir steht und mich unterstützt.

Schneller als ich in Abtenau kam, waren die bösen Gerüchte über mich im Ort. Den genauen Inhalt dieser Gerüchte hat sie mir nicht gesagt - ich kann es mir aber vorstellen. Außerdem "trifft es immer die Gleichen". Und zweitens bringt es nichts, sich mit dem Negativen und Bösen auseinander zu setzen. Besser ist es, diesen Gerüchten keine Bühne und Chance zu bieten. 

Wir Lehrer sind nicht zur Unterhaltung hier, sondern wir begleiten die Kinder auf ihrem Lernweg. Ich muss mir Unterrichtsmethoden zurecht legen, sodass die Kinder ihren Lernerfolg erreichen.

Respekt muss ich erwarten und einfordern.

Den bösen Gerüchten keine Chance geben. Das heißt, wie kommuniziere ich (gewaltfrei) mit den Kindern, sodass "die Botschaft" ankommt. Die Frage lautet: "Was soll ankommen ?" und dann entsprechend reden. Falsch wäre: was will ich sagen? Denn dann könnte etwas gänzlich anderes ankommen.

Gabi hat mir zwei Ausbildungen zu diesem Thema vorgeschlagen - werde mich anmelden.

- "Störungen haben Vorrang!"
- Immer ganze Klasse im Blick haben
- Von einer Metaebene aus unterrichten; dann habe ich auch die Freiheit, auf Störungen zu reagieren.


** Memo vom <2024-10-15 Di>
Wow - was für ein Tag!

*** Gespräch mit Gabi (Direktorin)
Ich kam in Abtenau an, dachte an nichts besonderes, stellte mein Auto ab und wollte mein Handy einstecken. Da sah ich eine Nachricht von Gabi: "Komm wegen Klärung ins Büro." Mir lief es sofort heiß herunter; dann dachte ich: "Was kann das wieder sein?" Mir fiel gar nichts ein ...

Gabi begrüßte ich und stellte mir die Frage: "Was denkst du, was es diesmal ist?" "Keine Ahnung!" "E-Mail einer erbosten Mutter, die endlich Konsequenzen fordert, da du die Kinder als dumm bezeichnet hättest!"

Frechheit - hab ich nicht gesagt. Ich kann mich an eine Situation erinnern: zwei Schüler haben es wirklich bunt getrieben, eine Batterie beinahe zum schmelzen gebracht (das ist gefährlich, weil giftig!) und ihre E Aufgaben sehr schlecht und unleserlich geschrieben.

Als nach mehrmaligem Hinweis und Ermahnen keine Reaktion der beiden kam, hab ich zu dem Schüler mit der Batterie gesagt: "Eine schmelzende Batterie ist gefährlich. Was du hier machst, ist dumm."

Zwei Plätze weiter sitzt ein Mädchen, hat nichts damit zu tun und erzählt ihrer Mutter: "Herr Fuchs sagt, wir sind alle dumm!" 

*** Was soll ich jetzt noch tun?
Natürlich kann und werde ich wohl noch mehr aufpassen, was ich sage. Aber hat es Konsequenzen für die Schüler die sich an keine Anweisungen des Lehrers halten? Es kann nicht sein, dass die Schüler mir auf der Nase herum tanzen können, und wenn ich als Lehrer reagiere - mir meine Worte im Mund umdrehen. Ich müsste mich dann dafür entschuldigen und den Schülern "blüht nichts" - nein, sie werden wohl weitermachen wie bisher.

*** Gedanken
Gabi steht voll hinter mir; sie will mich länger in Abtenau halten. Irgendwann werde ich mich frei schwimmen. Halte ich bis dahin durch? Das ist die Frage. Denn jene Personen, die meine Feinde sind und mich nicht in Abtenau haben wollen, werden nicht locker lassen.

Soll ich mit dem Ortspfarrer reden? Will ich nicht, da dies eine Schulangelegenheit ist. Internes nach Außen tragen geht gar nicht.

"Mah, das macht keinen Spaß mehr! Keine Freude mehr!" - so hab ich reagiert. Und Gabi versteht mich total. Gott sei Dank hat Lena (KV) mich vor der Klasse verteidigt. Ist nicht ideal, da dies meine Position schwächt (ich brauche jemand anderen).

Aber - naja: Melanie meinte, ich solle am Donnerstag "business as usual" machen. Falls jemand fragen wollte, werde ich so ähnlich wie in der 3a reagieren: "Das macht man nicht, jemand das Wort im Mund verdrehen und ihm Worte in den Mund zu legen, die man nicht gesagt hat. Und dabei nur die halbe Geschichte erzählen. Warum soll ich mich für Dinge entschuldigen, die ich nicht gesagt habe? Es tut mir sehr leid, wenn jemand Dinge falsch verstanden hat. Sorry. Aber ich will auch Konsequenzen sehen für jene Schüler, die in der letzten Stunde am Montag offensichtlich gefährlich unterwegs waren, siehe Batterie."

** Memo vom <2024-11-06 Mi>

*** Email
Gabi hat ein sehr positives Email an die Fachinspektorin geschickt; Marie-Luise wird demnächst zu Besuch kommen.

*** Rückmeldung von Hanni
Hanni hat für mich während meiner Krankheit suppliert; da hätten die Schüler gesagt, sie würden in meiner Stunde va HÜ machen. Das sollte eigentlich nicht passieren. Okay - dann werde ich das in Zukunft unterbinden. Das ist weiterhin nicht so schlimm, eine Kleinigkeit, die sich rasch und ohne Probleme beenden lässt. Die Schüler sind mir ja eigentlich recht dankbar, dass ich ihnen hier entgegen komme. Aber okay ist es eigentlich nicht. Ich denke da aber schon an die (zahlreichen) Schüler der 3b, die nicht in den RU gehen und während dieser Zeit ihre HÜ erledigen.

Und ich werde (habe) Hanni bitten (gebeten), dass sie mir bei der Vorbereitung der Lernschiene hilft. Am Dienstag bleibt sie länger an der Schule (diese Woche war sie bis 15h00 hier). Was sich für mich nicht ausgeht, da ich bis 14h50 bleibe. Naja - ich hab mir vorgenommen, einige Mappen mit nach Hause zu nehmen und diese Mappen bei Papa im Büro zu vervielfältigen und eventuell auch einzuscannen (das geht auch Zuhause). 

*** Gedanken
Was mich darin etwas erstaunt: die Kollegin geht direkt zur Direktorin. Warum nicht zuerst zu mir? Das hat bis jetzt nur Teresa (KV der 4c) oder Florian (KV der 1c) gemacht. In Golling kam so gut wie nie ein L zu mir. Dort habe ich unterrichtet und gut war es. Eventuell noch Erwin oder Manuela besprachen sich mit mir, aber auch nur, um mir wegen ihrer Klasse zu helfen. Sonst hat dort - so denke ich - "jeder sein Ding gemacht". Der KV der jetzigen 4a kam zu mir - Name fällt mir im Moment nicht ein.

Wie würde ich mich verhalten, wenn Schüler sich bei mir über einen Kollegen "beschweren" würden? Ich würde wohl eher direkt zum Kollegen gehen - wenn überhaupt. Zuerst einmal würde ich meinen Kollegen vor den Schülern verteidigen, kein schlechtes Wort über ihn kommen lassen. Und die Schüler vielmehr ermutigen, sich direkt an den betreffenden Kollegen zu wenden (oder max. an den KV).


** Memo vom <2024-11-18 Mo>
Ich denke, dass an diesem Tag Marie-Luise an der Schule war; das war jener schreckliche Montag. Muss noch mal in meinen handschriftlichen Notizen nachschauen.

** Memo vom <2025-02-03 Mo>
*** Vorgehen der Direktorin
Bis zum Ende verlief die Konferenz relativ normal, sie war sehr lang. Bei der Klassenkonferenz der 3a traute ich mich nicht, meine Ideen bzgl "WZ" für Jakob, Philipp, Simon, etc. vorzubringen.

Dann erzählte Florian zum Schluss vom unglaublichen Vorgehen von Gabi gegen ihn selbst.

Florian hat E-Mails bzgl. Stundenreduktionen überprüft und hat dabei - völlig unschuldig - andere E-Mails angesehen. Dadurch entdeckte er, wie Gabi äußerst negativ über Florian an die BD und die Juristin der BD berichtet hatte (und über andere Kollegen ebenfalls). Die Vorwürfe waren alle haltlos. Im Krankenstand hat sie jede E-Mails der Schule bzw der Direktion gelesen. Und Florian auf die Finger geklopft. An einem Samstag war sie sogar in der Schule.

Zu diesem Zeitpunkt fiel mir ein Stein vom Herzen. Einerseits tat es mir schrecklich leid für Florian, andererseits sah ich, dass Gabi nicht nur mit mir, sondern auch mit anderen Kollegen ein komplett manipulatives Spiel spielte. Fruchtbar! Also hab ich meinen Mut zusammengenommen und von mir erzählt. Auch andere Kollegen berichteten von ihren Erfahrungen.

Eine rote Linie ist überschritten. Florian wird nicht mehr als Vizechef zur Verfügung stellen.

*** Was und wie sagen wir es Gabi?
Wir haben uns geeignet, uns bis zu den Ferien mit der Gewerkschaft zu treffen; und Gabi gleich nach den Ferien zur Rede zu stellen. Vielleicht - so hoffen wir - kommt sie selbst zur Einsicht, dass sie unter diesen Umständen nicht mehr die Schule leiten kann, nein: gar keine Schule mehr leiten kann.

*** Persönlich...
Wow! das war ein Hammer zum Schluss der Konferenz! Jetzt weiß ich, dass ich mich auf meine Kollegen verlassen kann. Falls sie zurückkommt, werde ich Grenzen setzen und keine Gespräche mit ihr haben.

** Memo vom [2025-02-18 Di 12:09]
:PROPERTIES:
:CAPTURED: [2025-02-18 Di 12:09]
:END:
Juppi, funktioniert.

** Memo vom <2024-11-27 Mi 12:00>
:PROPERTIES:
:CAPTURED: [2025-02-19 Mi 00:27]
:CUSTOM_ID: h:e5e8a631-43ae-4b78-82b6-b0ffcbdb2f32
:END:
Die Direktorin hat mich (wieder einmal!) zu einem Gespräch zitiert und mich zur "Schnecke gemacht". Weil ich es gewagt hätte, dass die Schüler in meiner Stunde Hausübung machen dürfen. Ein No-Go in ihren Augen; sie hat diese Sache komplett aufgebauscht. Und ich hätte (damit) ihr Vertrauen verletzt und meine "Chance verspielt".

Ich war danach (+bin es immer noch) total verzweifelt. Ich habe meine Inspektorin kontaktiert (hat sich hinterher als Fehler herausgestellt). Die Inspektorin hat mir am Telefon geholfen und hat ihren Besuch für den Montag, 02.12.2024, angekündigt. Das Wochenende war furchtbar.

** Memo vom <2024-12-02 Mo 13:10>
:PROPERTIES:
:CAPTURED: [2025-02-19 Mi 00:34]
:CUSTOM_ID: h:481007b9-b0f5-4c8e-994a-2272232450f9
:END:
Ich war so nervös. Die Inspektorin war in der 4b und der 3a - ich hab eigentlich nur mit der 3a gerechnet. Die beiden Stunden waren (natürlich) nicht gut. Leider.

Aber die wahren Tortur geschah nachher. Über zwei Stunden haben beide Damen (Direktorin und Inspektorin) auf mich eingeredet. Alles Negative wurde mir aufgezählt. Während meiner Ausbildung würde so eine Stunde mit "Nicht Genügend" beurteilt werden - ich wäre jetzt nicht einmal Lehrer.

Man sagte mir: da ist null Pädagogik, null Didaktik, Nichts! Nehme nichts wahr (kenne kaum die Namen), übersehe vieles! Lasse Störungen zu, etc. Die reine Katastrophe!

Die Krone setzte die Direktorin auf, als sie meinte, ich MÜSSE eine Therapie machen (da ich meine Aggressionen nicht im Griff hätte). Es gehe sie ja nichts an, aber wahrscheinlich würde ich meinen eigenen Kindern auch keine Grenzen setzen. Und ich wäre es, der ihr Vertrauen verletzte habe.

Ich bin verletzt durch ihr Verhalten, auch durch jenes der Inspektorin; sie hat wahrscheinlich alles , was ich ihr am Telefon gesagt habe, der Direktorin weitergegeben - oder das Gespräch am Monat zwischen ihr und mir.

Mich belastet das alles sehr, sehr! Ich kann mich nicht mehr entspannen ... am Wochenende. Diese Frau "sitzt in meinem Kopf"!

** Memo vom <2024-12-13 Fr 18:00>
:PROPERTIES:
:CAPTURED: [2025-02-19 Mi 00:49]
:END:
Letzten Sonntag <2024-12-08 So> war ich am Vormittag alleine in der Stadt beichten. Das ging zuerst nicht, da kein Priester da war. Der Pater kam gegen Ende der hl. Messe zurück. Nachdem ich alles erzählt hatte: "Da gibt's nix zu vergeben - nur zu segnen. Suchen Sie sich einen Freund! So wie die Jünger von Jesus immer zu zweit ausgesandt wurden. Auch Maria hat ihren Sohn um Rat gefragt."

Am Nachmittag schrieb ich mein Mail an die Direktorin. Und am Abend in die Hl. Messe - war sehr schön.

Am Montag <2024-12-09 Mo> war es okay, am Dienstag ebenso. Am Mittwoch auch?

Am Donnerstag hätte ich angeblich einem Erstklässler das Tablet so fest zugemacht haben, dass dieses kaputt gegangen ist.

Nach dem Mail war sie echt angefressen auf mich:
- Ich sag es geht mir gut - immer - was eine Lüge sein muss.
- Ich bin unehrlich zu ihr.
- Sie bestimmt, wann sie mich sehen will; nicht ich.
- Sie wird mir in Zukunft enger und mehr auf die Finger schauen.
- Ich bin ja nie an etwas schuld.

Mann, ich war echt fertig! Ich denke ans Aufhören! Habe mich nach Alternativen um gesehen. Am Heimweg dachte ich mir: "Nein, jetzt höre ich nicht auf. Ich weiß jetzt besser, wer Gabi ist. Muss lernen, gegen Dominas wie Gabi zu wehren!" Sie neigt zum Übertreiben und nutzt jede Möglichkeit, mich zu dominieren. Sie hat eine Wahrnehmungsstörung. Darf niemals für Bare Münze nehmen, was sie mir sagt.

Sie kümmert sich zwanghaft immer um ALLES, kann anderen Kollegen nicht vertrauen.

Bzgl. Tablet: hab mit Jacqui (KV) und dem Schüler gesprochen - alles halb so schlimm.


* Schüler

* Lehrerkollegen

* Eltern
