#+title:      Abschlussgottesdienst 4. Klassen
#+date:       [2025-05-12 Mo 08:52]
#+filetags:   :schule:
#+identifier: 20250512T085255
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Abschlussgottesdienst.html

* Termin
<2025-07-03 Do 18:00>

* Thema
Dankbarkeit - Ferien - Frieden

* Wer liest?

** 4a
Johann R. soll fragen

** 4b
Thomas fragt

** 4c
Ich frage


* Kyrietexte (?)
Gott, unser Vater, du hast uns geschaffen. Du hast uns Menschen und allen Lebewesen den
Lebensatem eingehaucht.

Kyrie eleison

Gott, unser Vater, du kennst unsere Sorgen und Ängste. Du gehst jeden Weg mit uns.

Christe eleison

Gott, unser Vater, du hast gesagt „Kommt alle zu mir, die ihr euch plagt und schwere Lasten zu
tragen habt. Ich werde euch Ruhe verschaffen.“ Du schenkst uns immer neue Kraft zum Leben.

Kyrie eleison

* Lesungen

** Gen 2,1-4
So wurden Himmel und Erde vollendet und ihr ganzes Gefüge. Am siebten Tag vollendete Gott das
Werk, das er geschaffen hatte, und er ruhte am siebten Tag, nachdem er sein ganzes Werk vollbracht
hatte.\\

Und Gott segnete den siebten Tag und erklärte ihn für heilig; denn an ihm ruhte Gott, nachdem er
das ganze Werk der Schöpfung vollendet hatte.\\

Das ist die Entstehungsgeschichte von Himmel und Erde, als sie erschaffen wurden.

** Joh 20,19-23
Am Abend dieses ersten Tages der Woche, als die Jünger aus Furcht vor den Juden die Türen
verschlossen hatten, kam Jesus, trat in ihre Mitte und sagte zu ihnen: Friede sei mit euch!\\

Nach diesen Worten zeigte er ihnen seine Hände und seine Seite. Da freuten sich die Jünger, dass
sie den Herrn sahen.\\

Jesus sagte noch einmal zu ihnen: Friede sei mit euch! Wie mich der Vater gesandt hat, so sende
ich euch. Nachdem er das gesagt hatte, hauchte er sie an und sprach zu ihnen: Empfangt den Heiligen Geist!

* Fürbitten
:PROPERTIES:
:CUSTOM_ID: h:6610fa6e-cef8-43db-8c45-cf08e74ac084
:END:

- Guter Gott, wir bitten für alle Schülerinnen und Schüler, Lehrerinnen und Lehrer. Schenke allen erholsame Ferien und immer wieder Momente zum Durchatmen und Innehalten. Gott, schicke uns deinen Wind.

- Für alle Jugendlichen und jungen Erwachsenen, die gerade entscheiden müssen, wie es mit ihrer schulischen oder beruflichen Zukunft weitergehen soll. Schenke ihnen den Mut, ihrem Herzen zu folgen und begleite sie immer auf ihrem Weg. Gott, schicke uns deinen Wind.

- Für alle Kinder und Jugendlichen, für die heute die Ferien beginnen. Schenke ihnen Momente, in denen sie sich leicht und frei wie eine Feder fühlen können. Gott, schicke uns deinen Wind.

- Guter Gott, manchmal fühlen wir uns schwer wie ein Stein, weil wir müde sind und uns alle Kräfte ausgehen. Bitte, lieber Gott, gib uns wieder Kraft und schicke uns deinen Wind.

- Guter Gott, dein Heiliger Geist weht. Er macht alles neu. Wir bitten dich, dass der Heilige Geist uns wieder neue Energie und frische Lebensfreude schenkt. Gott, schicke uns deinen Wind.

- Guter Gott, wir beten für alle Menschen, denen es gerade nicht so gut geht, weil sie über etwas traurig sind oder weil sie krank sind. Bitte erhöre ihre Gebete und mache sie wieder froh und gesund. Gott, schicke uns deinen Wind.

* Geschenk
Schlüsselanhänger

Wie wie viele müssen wir nachbestellen? 

