#+title:      Eröffnungskonferenz
#+date:       [2025-09-08 Mo 09:53]
#+filetags:   :sk:
#+identifier: 20250908T095347

* Begrüßung

Ich achte mein eigenes und fremdes Eigentum. (Neubau)

Letzte Stunde: Klasse aufräumen (Mist), Stühle auf den Tischen. Fenster zu.

* Eröffnungskonferenz

* Schülerzahlen

** 1a
15

** 1b
25

** 1c
19

** 1d
15

** 2a

** 2b

** 2c

** 2d

** 3a
20

** 3b
25

** 3c
20

** 3d
18

** 4a
24

** 4b
25

** 4c
24

* Jahresplanungen

An die Direktion schicken; auch Religion? In welcher Form? Bis wann?

* Keine Schulglocke

Nicht vor Unterrichtsende den Unterricht beenden; Schüler zu den Garderoben begleiten

* Pausenaufsicht

in der Früh / große Pause; pünktlich; in die Klassen schauen; genau nehmen.

* Webuntis & Co

Sofort, erste Stunde: Abwesenheiten eintragen; Stoff baldigst eintragen.

Fortbildung anmelden / PH Salzburg, KPH Lehrgänge

Buddys (Schüler helfen Schüler)

* Tag der offenen Tür

Lisa & Johanna (Datum siehe unten)

* Schulfolder

"Vital ... Brain"

* Allfälliges

Koordination:
E: Konstanze
D: Lisa
M: Matthias (KV 4b)
...
Kaffeemaschine: ? + Inge
...
Küche: Spüler ausräumen, aufräumen, Tische putzen (wo man gegessen hat), ...
...
Schulhandy: um Eltern anzurufen (Eva)
...
Religion: Inge (ich, werde von Inge eingelernt)
...
Entrepreneurship?
...

* Termine

Tag der offenen Tür

Elternsprechtag(e)

Schulgottesdienst:
Di: 08:00 Beginn "Orientierung Kompass"

Schulplaner - ausgeteilt (Kosten 7.10 Euro einsammeln, Klasse Anzahl Schulplaner)

Religionsabmeldung / -anmeldung

SEL Gespräche

Auskunftsgesetz: betrifft Gemeinde mit über 5000 EW - keine Schule hat mehr als 5000 Schüler; also nix. Auf jeden Fall: "Muss Rücksprache halten!" Va wer ist ao Schüler / i-Schüler / etc - das dürfen wir niemals sagen.

500 Jahre Bauernkriege - Land Salzburg Ausstellungen; Angebote für Klassen; ...

3.10. Schullauf 1500m

7.1. Aufnahmeprüfung (Sport); ärztliches Attest mitbringen; Ersatztermin?

* Wichtige Termine

Konferenzen 16:00-18:30
Ausnahme: Semester / Schluss (andere Zeiten)

8.10. Konferenz
20.10 19:00 Schulforum? (z.B. schulautonome freie Tage)

21.11. erster Elternsprechtag 14:00-18:00

3.12. VS-Schnuppertag

11.12. Konferenz + Weihnachtsfeier (Öffis - wenn Stadt, dann Zug; Ort? auch in der Stadt) - Liste!

13.1. Konferenz

26.1 - 30.1. Skikurs zweite Klassen

2.2. Semesterkonferenz 14:00-17:00

18.3. Konferenz (Schulbuch)

9.4. zweiter Elternsprechtag + 19:05 Schulforum

23.4. Konferenz

18.5. Konferenz

1.7. Schluss / Notenkonferenz 14:00-17:00

Dieses Schuljahr dauert eine Woche länger. 

* 
