#+title:      Johannes der Täufer
#+date:       [2025-12-05 Fr 12:01]
#+filetags:   :advent:
#+identifier: 20251205T120127


* Wiederholung
Brauchtum: Bräuche im Advent - Adventkranz, Barbarazweige, Adventkalender, Nikolaus, Weihrauch, Kerzen,...

Hören: Adventlieder, Lärm / Stille, Musikkapellen, Krampuss-Lärm, Knistern des Feuers, Christkindlmärkte, etc.
Sehen: Licht, Farben, Dunkelheit, Schnee, ...
Schmecken: Kekse, Punsch, ...
Riechen: Weihrauch, Kekseduft, ...
Tasten: Tannenzweige, Schnee, ...

* Erarbeitung
Johannes der Täufer - sein Leben / seine Botschaft
- Verkündigung seiner Geburt: Lk 1,5-25
- seine Geburt: Lk 1,57-80
- Leben in der Wüste: Joh 3
- seine Predigt: Lk 3,1-20
- Was sagt Jesus über Johannes: Mt 9,14-17; 11,2-19; Lk 7,18-35.
- sein Tod: Mk 6,14-29

Synoptiker und JohEv!

Bibelarbeit zu den Lesungen des 2. Adventsonntags[fn:1]

 - Jes 11,1-10
 - Ps 72 (71), 1-2.7-8.12-13.17  
 - Röm 15,4-9
 - Mt 3,1-12

Mit dem Evangelium am 2. Adventsonntag steigen wir einen Schritt weiter in die Vorbereitung auf die Erzählung von der Geburt des Christus ein. Am letzten Sonntag haben wir einen Text gehört, in dem der erwachsene Jesus zur Achtsamkeit mahnte. Heute gehen wir jetzt noch einen Schritt zurück in die Anfänge Jesus. Wir begegnen Johannes dem Täufer. Dem Vorläufer ... dem, der den Weg bereitet. 

Der Evangelist Lukas stellt hier die Predigt des Johannes als neuen Ruf zur Heimkehr aus dem Exil dar. Zunächst wird das Ereignis historisch eingeordnet, wie auch Exil und Heimkehr historisch einzuordnen sind, und wie Lukas im Kapitel zuvor schon die Geburt Jesu in einen großen weltpolitischen Horizont gestellt hat. Gleichzeitig ist vollkommen klar: Der "Herr der Welt", der Kaiser in Rom, ist nicht im Zentrum. Das eigentliche Zentrum ist auch nicht der Tempel in Jerusalem. Das Zentrum der Welt ist in der Wüste und dann am Jordan. 
In der Wüste ergeht das Wort Gottes an Johannes – wie damals an Mose. Was Gott gesagt hat, erzählt uns Lukas überraschenderweise nicht. 
Auf jeden Fall zieht Johannes an den Jordan und verkündet dort "eine Taufe der Umkehr zur Vergebung". Nicht Taufe und (!) Umkehr, wie die alte Einheitsübersetzung vereinfachte. Wie hängen aber Taufe, Umkehr und Vergebung zusammen? Auf jeden Fall scheint die Taufe nicht die Bedingung zur Umkehr und Sündenvergebung zu sein. Die eigentliche Predigt des Johannes wird von Lukas auch nicht zitiert. Seine Worte sind aber offensichtlich ähnlich denen des Propheten Jesaja (Jes 40,3-5):

Ein Weg soll sich öffnen nach Hause. 
Das Heil Gottes soll sichtbar werden.

Von Babylon aus ist der Blick frei nach Jerusalem. Vom Jordan aus ist der Blick frei nach Jerusalem. Das Heil Gottes schauen, kann 
ganz wörtlich heißen, den Tempel oder das Allerheiligste sehen können. Überträgt man das Bild ins Innere, öffnen sich noch weitere Perspektiven. Die innere Landschaft zu ebnen, damit man Gott sehen kann. Das ist der adventliche Impuls dieses Evangeliums. 

---

Fragen:
 1. Was sagt der Text über Jesus?
 2. Was sagt, tut Jesus?
 3. Was sagt, tut der Kranke, etc?
 4. Welche Eigenschaftswörter...?
 5. Was sagt der Text dir persönlich?

cf Skript von Fr. Kreinecker bzgl Fragen zu einem biblischen Text 

---
Ideen aus der heutigen Predigt:
Herkules und der Stall des Augias. - Augias besitzt 1000e Rinder, sein Stall wurde seit 30 Jahren nicht mehr gereinigt. Herkules leitet zwei Flüsse um und reinigt auf diese Weise den Stall. Augias lässt dies nicht gelten, denn nach seiner Meinung haben die Flüsse den Stall gereinigt, und nicht Herkules. Daraufhin tötet Herkules Augias. Die Olympischen Spiele beruhen auf dieser Geschichte. 

Der "Stall des Augias" steht für den Saustall der Sauställe - Dreck in der Politik und Wirtschaft, Korruption, etc ...

Wo gibt es in meinem Leben einen stinkenden Winkel? Der Advent ist nicht nur Besinnung und Stille, Kerzenlicht und Nikolaus, sondern war und ist immer schon eine Zeit der Umkehr.

Damit Gott zu mir kommen kann, muss mein Haus gereinigt werden.

* Hefteintrag
Johannes der Täufer in der Wüste - was würde er heute sagen?
Welche Ungerechtigkeiten würde Johannes heute anprangern?
Zeichne Johannes und schreibe daneben eine "scharfe" Predigt.

Szenen als Zeichnungen darstellen?

Bilder zum Ausmalen / Ergänzen? 
