#+title:      Allerheiligen Allerseelen
#+date:       [2025-11-05 Mi 08:57]
#+filetags:   :schule:
#+identifier: 20251105T085727

* Ursprung des Festes

* Ideen für den Unterricht

Das Fest richtet unser Herz und unser Leben auf das "Leben nach dem Tod, die Ewigkeit" aus. Es ist ein fest der Freude, des Lichtes und der Hoffnung. Die Sorge um das jenseitige Leben ist eine grundlegende Wesensart jeder Religion. Gerade im Christentum - Jesus hat den Tod besiegt und der Glaube an die Auferstehung Christi ist Quelle der Hoffnung. 

"Das Gedenken der Verstorbenen und die Sorge um ihr 'jenseitiges' Leben gehört zu den ältesten Quellen religiösen Verhaltens der Menschheit überhaupt. Für den christlichen Glauben ist die Hoffnung und die Zusage der Auferstehung tragend, dass unsere Toten in ihrem Sterben in die liebenden und vollendenden Hände Gottes gefallen sind. Mit dem im Spätmittelalter entstandenen Bild vom Fegefeuer als Reinigungsort für die sündigen Seelen hat sich in der katholischen Kirche eine besondere Sorge um das Heil der Verstorbenen entwickelt, für das man betete und Messen bezahlte. Das mit dem 2. Vatikanischen Konzil reformierte Totengedenken stellt dagegen den Glauben an die Auferstehung, an die verzeihende Liebe Gottes und an die heilsame Verbindung der Lebenden mit den Toten in den Vordergrund. Allerseelen ist darum wie Allerheiligen das Fest der ganzen Kirche, die Gemeinschaft der Lebenden und der Toten, die auf dem Weg zur endgültigen Vollendung sind."

** Was ist heilig?

** Symbol des Lichts

** Hoffnung

** Ewiges Leben

** Auferstehung

** Was ist (mir) wirklich wichtig - was nicht?

** "Alle wollen in den Himmel"

Doch bin ich bereit, mich dafür vorzubereiten? Oder "mache ich eh nur Gutes" - spreche mich quasi selber "heilig und gerecht". Dh ich brauche dann keinen Erlöser? Heilige haben die Barmherzigkeit Jesu empfangen, dh wie waren sich besonders bewusst, dass sie nichts ohne Jesus tun können. Sie haben sich ganz von Jesus ergreifen und lieben lassen, haben aber auch "was getan dafür". 
