#+title:      Schule einrichten
#+date:       [2025-01-07 Di 08:23]
#+filetags:   :schule:
#+identifier: 20250107T082318

* Allgemeines
Gabi auf unbestimmte Zeit abwesend wegen Krankheit.

Anwesenheit laut Stundenplan (und mehr)

Grüner Container: Sperrmüll

Schlüssel: für die (beiden) KVs - Klasse und Fenster
plus zusätzliche Schlüssel (auch für mich)

Durchgang zieht sehr - BM weiß Bescheid.

QMS - siehe Protokoll
Q-Handbuch
Lesemonat - für gut befunden; nächstes Jahr wieder.
FB bis 31.1.2025 noch Anm. möglich

Skitag (Raika): fährt noch jemand; 20.2. 3a+4a (Johann, Alex, Lorena und ...?); 1a+1c
Schulschirennen: 04.02. Sonnleitn? - Siegerehrung?

Faschingsdienstag, 04.03., Unterrichtsende um 12h20; Faschingskrapfen vom EV; Was ist erwünscht? Stationenbetrieb OK (1+2 / 3+4 Klassen) L als Bauarbeiter?

Nur kurze Zeit bis Notenkonferenz (nur 3 Wochen)

NEUE Pausenaufsicht! Siehe Aushang bei Tür. Wer kann morgen früh um halb 8 helfen?
Freitag: normaler Tag.

Vorsicht - Baustelle!

Schülerregeln im Container?
Türen / Container verziehen sich, WC Türen lassen sich schwer versperren; sind zwei Türen gegenüber offen, bleibt im Gang nur wenig Platz; ... Heizung? Regeln über Kasterl bei Türe; LÜFTEN! 3 Außentüren pro Tür 1000 Euro für einen Türknauf. Wahrscheinlich nicht im Budget. Dh Tür nach Betreten sofort versperren (mit Schlüssel)? 

* Allfälliges
Wer ist nächste Woche nicht da?
Morgen 3.-?. und Montag Stunde ist Bücherei belegt (betrifft 1d).

Felix (Eder) hat sich schwer verletzt; ob es technisch möglich ist, mit Rollstuhl? 

* Markus Haslauer (Sozial)
Bericht über seine Tätigkeiten

* Ab Freitag
Parken hinter dem Container

* Besprechung am Donnerstag
:PROPERTIES:
:CUSTOM_ID: h:d6cb257e-5abc-42cf-a5db-92ba0a90bfdd
:END:
Ablauf für Freitag
Pausenaufsicht neu - neue Gänge


* Altes Konferenzzimmer
Wer muss seine Kasten ausräumen?

* BU Kammerl
:PROPERTIES:
:CUSTOM_ID: h:abefd19a-8cdd-4aa3-ab69-1bd4fdcc7fef
:END:
ich

* EDV Kammerl

* Besprechungsraum?

* Küche

* Musikraum
ich.

* Bibeln (grün in den Kartons)
in die Klassen?
oder in mein Fach im Konferenzzimmer?

