#+title:      D Klasse 2023-27 Seekirchen
#+date:       [2025-09-08 Mo 08:12]
#+filetags:   :3d:sk:
#+identifier: 20250908T081215
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/3d Seekirchen.html

* Jahresplanung

[[denote:20240709T110253][Zeit für Religion 03]]


* Webuntis
[[https://hypate.webuntis.com/WebUntis/#/basic/login]]

* Notizen, Tasks, Termine


* Stundenplanung

** Aschermittwoch

[[denote:20260223T094328][Aschermittwoch Fastenzeit]]

Videos: kathmedia deutsch / Katholisch für Anfänger

40 Tage Fastenzeit - Vorbereitung auf Ostern
40 Tage - weil Jesus 40 Tage gefastet hat 
40 Tage, Wochen, Jahre: Zeit der Umkehr, Bekehrung, ...

Sintflut dauert 40 Tage
Moses bleibt 40 Tage auf dem Berg Sinai
Elija geht 40 Tage zum Berg Horeb (Sinai)
Das Volk Israel wandert 40 Jahre durch die Wüste (weil 40 Tage lang gemurrt hat)
König David regiert 40 Jahre (so wie Salomo?)

Fasten:
- aus Trauer über die vergangenen Sünden
- zur Stärkung des Willens (damit wir in den Versuchungen standhaft sind)

Vernunft und Wille sind auf das Wahre und Gute ausgerichtet
Unsere Gefühle sollen das Herz informieren, bewegen (Emotion)

Wenn die Gefühle aber über Hand nehmen, dann regieren sie; und nicht mehr daś Herz.

Dafür müssen wir den Willen stärken - daher Fasten.

Andere Mittel in der Fastenzeit: Beten, Almosen, Verzicht, Glauben stärken durch Bibellektüre, Bücher über Heilige, KKK, ...

Fasten / katholisch bedeutet:
- einmal satt essen, zweimal eine Jause
- Aschermittwoch und Karfreitag (zusätzlich): Verzicht auf Fleisch, Vergnügungen, Alkohol, ...

Lesungen Aschermittwoch:
- Joel 2,12-18
- Ps 51
- 2 Kor 5,20-21.6,1-2
- Mt 6,1-6.16-18

Warum hat Jesus gefastet? Er ging in die Wüste (Ort der Begegnung mit Gott), wird dort vom Teufel in Versuchung geführt - Jesus zeigt uns dadurch, wie wir diesen Versuchungen widerstehen können. Es sind die drei Versuchungen des Teufels:
- es gibt keinen Gott
- du bist ein guter Mensch (Stein in Brot)
- du hast viel Zeit 

Fasten soll schon auch ein wenig weh tun - es soll dich "etwas" kosten. Auf Schoko verzichten, wenn ich keine Schoko mag, ist nicht ehrlich und zielführend. Fasten ist keine Diät.

Ich faste und verzichte FÜR etwas; mein Herz, Geist, ... sollen frei werden für Gott. Im Laufe der Zeit verlieren wir den Fokus aus den Augen; wir belasten uns mit Dingen; die Fastenzeit soll uns freier machen für Gott (und den Mitmenschen). Von uns weg auf Gott hin.

Wie fasten andere Religionen? 

Glaube und Werke:
- nur der Glaube rettet uns; wir können uns den Himmel durch Werke nicht verdienen
- der Glaube muss in Werken der Liebe  sichtbar sein.

** Gemeinsam mit der Bibel arbeiten
Die Schüler entscheiden lassen, was sie lesen möchten (AT oder NT). Lesen und danach darüber reden, austauschen; Bezug zu Lebenswelt der Schüler herstellen.

Bsp. König David - Kampf mit Goliath - Hefteintrag: Bildergeschichte zeichnen.

Oder Offenbarung: Kapitel 1 und 4 lesen und ebenfalls eine Zeichnung ins Heft / Zettel.

Kirche in Not - Bibelstelle ziehen und damit eine schöne Seite im Heft gestalten; ebenso mit dem Jahresheiligen - eventuell Informationen aus dem Internet notieren. Nachdenken und notieren, was die Bibelstelle und der Jahresheilige für dich bedeute könnte. Vorher - beten.

Tor in den Himmel basteln ...

** Das Leben Jesu - die Taufe Jesu

Bibelstelle lesen
Eigene Taufe / Video kathmedia

** Warum stellen wir Fragen

[[denote:20260123T091818][Warum stellen wir Fragen]]

** Bartimäus
Mk 10,36-42 (?) lesen; "Was soll ich dir tun?" - Stell dir vor, Du bist Bartimäus. Was würdest Du Jesus sagen? (Interessanterweise sagen die meisten Kinder: "Gesundheit, Geld, 1000 Wünsche, ..." Kaum ein Kind denkt daran, dass es eigentlich wie Bartimäus blind ist. 

Sich in einen anderen hinein versetzen können; die gleiche Menge, die Bartimäus vorher ausgrenzt, ruft ihm nachher Mut machende Worte zu. 

Von Bartimäus kennen wir den Namen (warum?), und er ist der einzige Geheilte, dem Jesus erlaubt, dass er Ihm nachfolgt. Mit ihm nach Jerusalem hinauf geht. 

** Gleichnisse über das Reich Gottes
[[/home/matthias/MS_Seekirchen_Mattsee/Bibel_NT/Reich Gottes Gleichnisse/]]

[[file:~/MS_Seekirchen_Mattsee/Bibel_NT/Reich Gottes Gleichnisse/Handreichung Gleichnisse.pdf]]

Was sind Gleichnisse?
Warum spricht Jesus in Gleichnissen?
Schlüssel zum Verständnis der Gleichnisse 

Bibelstellen:
- Mk 4
- Mt 13; 20 (Weinberg); 21,23-27; 22; 25
- Lk 8; 10,25-37 (Samariter); 13,18-20; 15!; 16 (Verwalter, Lazarus); 18 (Richter und Witwe), (Pharisäer und Zöllner); 20 (Weinberg); 

* Reflexionen

** Altmann Kristin

** Eckschlager Amelie

** Ferao Mbelani Sidonia

** Kaltenbrunner Tobias

** Karas Zita

** Klinger Valerie

** Lerchner Gregor

** Mathwich Lina

** Nobis Levi

** Petrovic David

** Pöschl Andreas

** Seidl Raphael

** Selimi Ensar

** Stangl Emma

** Wessely Amelie

** Wessely Isabella

** Wirths Levi

** Zdraljevic Jovana
