#+title:      Wer ist Gott
#+date:       [2025-10-17 Fr 09:15]
#+filetags:   :theology:
#+identifier: 20251017T091544

* Hat Gott einen Leib?

[[https://www.reddit.com/r/Bible/comments/16fsojx/does_god_the_father_have_a_physical_body_like/?show=original]]

Alot of decent answers here. I would approach it from the Cosmological Argument angle and say that, in order to create the material universe, God would need to be immaterial. If the universe is composed of Space, Time, and Matter, God cannot be composed of those parts, otherwise where did his parts come from? These things cannot exist eternally in the past. (If time was Infinate in the past, we never would have arrived at today. Matter/ energy itself, for many physical and chemical reasons, cannot be past eternal, they must have been created at some point in the finite past.) Therefore God exists as the eternal, uncreated being and as creator, he is spaceless, timeless, and immaterial. The uncaused first cause, you might say.

He can, however, interact physically with creation. It is believed that the "Angel of the LORD" or "Angel of YHWH" in the OT is the pre-incarnate Jesus Christ. From the Trinitarian standpoint, he is the 2nd person of the Trinity, referred to as the Son. He later entered into creation as a combined entity (fully divine and now fully human/corporeal) named Jesus in order to be the nessassary sacrifice for the forgiveness of all sin (past, present, and future.) God himself died for the sins of his people, a price they could never pay. This makes Jesus the part of God that interacts physically, and not the part that is immaterial. He is the "imprint of Gods nature" (Hebrews 1:3).

According to John 1, all things were created through Jesus, the Word of God. So in a sense, you are correct. To create and interact with a physical world, God needs a physical body. Fully immaterial beings like spirits do not interact consistently or understandably with phycial matter unless they are incarnated beings, body AND soul together. (this is a hotly debated topic, and one i don't fully understand, so i won't get into it here.) For God who is outside creation, to step into creation requires a physcial form. That physical form, however, is Jesus, who himself is fully God. But he IS Gods physical form, and the only member of the Trinity that "needs" it.

Think of a wax stamp. God the Father is outside of time and space. He is like an immaterial stamp that can press itself into creation, causing deformations in the hot wax. Those deformations are in the shape of a man, who is the exact imprint of the immaterial creator, but represented physically, and able to be perceived and interacted with by the rest of the phycial world. That shape is inhabited by the 2nd person of the Trinity, able to live and breathe and die for the atonement of sins. That is the shape that rose again, perfected, and went to sit at the right hand of glory. (I cannot stress enough how much Hebrews is an amazing book.)

Final point: the trinity is considered a "mystery of God," something that, despite our best efforts, aproximations, and revelations, we will never fully understand. It is for God alone to understand how it all works. For us, he is one being in three persons, a Lover, Loved One, and a Spirit of Love. He is the Spaceless, timeless, immaterial, powerful, personal cause of creation who entered in and dwelt among his creation as the Man Christ Jesus who became the offering for the forgiveness of sins and who dwells within us as the 3rd person, the Holy Spirit, once we have accepted his free gift of salvation.

Hope this helps! This isn't a question that can be answered simply or quickly, but this is what I've come to understand in my studies.
