#+title:      C Klasse 2025-29 Mattsee
#+date:       [2025-09-13 Sa 11:07]
#+filetags:   :1c:ms:
#+identifier: 20250913T110721
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/1c Mattsee.html

* Jahresplanung

[[denote:20250913T113018][Religion für uns 01]]

* Notizen, Tasks, Termine


* Stundenplanung

** Jesus sagt: "Ich bin ..."

- Ich bin das Brot des Lebens. (Joh 6,36) :: Jesus stillt den geistlichen Hunger und schenkt ewiges Leben. „Brot“ (6,35.52) nimmt nicht nur die „wunderbare Brotvermehrung“, d.h. die Speisung des Gottesvolkes mit den überreichen Lebensgaben Gottes auf (6,1-15), sondern auch die Brotrede, die beim Hunger des Volkes beginnt und über das Manna (6,49) bei der Eucharistie endet (6,52-58). Jesus gibt nicht nur etwas, sondern sich selbst - zum Leben der Welt.

- Ich bin das Licht der Welt. (Joh 8,12) :: Er bringt Wahrheit, Orientierung und vertreibt geistliche Finsternis. „Licht“ (8,12) bereitet nicht nur die Offenbarungsrede über die Blindheit des Unglaubens wie der Sünde und die Helligkeit des Glaubens wie der Liebe vor (8,12-59), sondern auch das Wunder der Heilung des Blindgeborenen (Joh 9). Jesus stößt diejenigen, die die Finsternis mehr lieben als das Licht (3,19; vgl. 1,5), nicht in die absolute Dunkelheit zurück, sondern spendet ihnen das Lebens-Licht Gottes.

- Ehe Abraham war, Ich Bin. (8,58) :: First, just at the surface level, He's already claiming to be supernatural if He is saying he's existed for more than 2000 years. If He's not claiming to be divine, He's at least claiming to be some sort of angel or other supernatural creature. 

Second, the grammar there is clearly off, at least in the Greek. He says, regarding Abraham, "was" ("genesthai", aorist tense to say that Abraham "came into being" in the past), but regarding Himself, "am" ("eimi", present tense of the to be verb). That construction makes no sense unless He's trying to say something special here. If He only meant a surface-level declaration "I am immortal", it would still only be "Before Abraham was, I already was." We don't know what He said in Aramaic, but John's choice to express it in this way in Greek shows that John thought preserving the tenses in what was said was more important than making the text flow grammatically.

Third, as the parentheticals above hint at, He even uses different verbs. Abraham had a "genesis." There was a time when he was not, and then a time that he was. Jesus does not admit that He had a "genesis." He simply says "Millennia ago, I am," not "Millennia ago, I came to be." Again, this could be the result of translation, but John chose to clarify that different verbs apply to Abraham and Jesus' modes of existence, which shows John thought the distinction was important.

Fourth, you're right that the "I am" construction is not itself a declaration of divinity. It's just the same "I am" that could be used in any other context. In Luke 5:8, Peter says "I am a sinful man!"; he's neither claiming to be God nor blaspheming with a claim that God is a sinful man. But as the source you linked from Dr. Manning also says, some of the I ams are clearly intended in context to be a quote from YHWH in Exodus, especially when they don't grammatically follow as well--like "I am" instead of "It is I" (identifying Himself during the storm) or "I am he" (identifying himself to the mob).

Fifth, the response of the listeners is telling. When they thought He was merely insane or even diabolical, they did not threaten Him, only argued with Him. When He said "I am", they immediately became murderous. We have to assume that even if we can't prove it from the text alone, they interpreted His statement as blasphemous, and that they were in a far better position to judge context. 

- Ich bin die Tür. (Joh 10,7.9) :: Er ist der einzige Zugang zum Heil und zu Gott.
- Ich bin der Gute Hirte. (Joh 10,11) :: Er sorgt für seine Schafe, beschützt sie und gibt sein Leben für sie. "Tür" und "Hirte" (10,7.9.11) ist Jesus als derjenige, der Juden wie Heiden das Tor zum Reich Gottes öffnet und ihnen seine Gemeinschaft schenkt. Er öffnet nicht nur die Tür, sondern ist diese Tür, weil er das Heil nicht nur zeigt, sondern bringt.

- Ich bin die Auferstehung und das Leben. (Joh 11,25) :: Er überwindet den Tod und schenkt ewiges Leben. „Auferstehung“ und „Leben“ (11,25) ist Jesus als derjenige, der Lazarus aus dem Grabe holt und damit nicht nur die endzeitliche Auferstehung der Toten antezipiert, sondern die Gegenwart des Heiles mitten im Leben der Glaubenden verheißt: Der Tod hat schon jetzt keine Macht mehr über sie, weil Jesus die Glaubenden und Liebenden auf die Seite des Lebens zieht.

- Ich bin der Weg, die Wahrheit und das Leben. (Joh 14,6) :: Er ist der direkte Weg zum Vater. „Weg“ (14,6) ist Jesus als derjenige, der seine irdische Sendung durch den Weg ans Kreuz und über das Kreuz durch seinen Hinübergang zum Vater vollendet (vgl. 13,1f). Als „Weg“ ist Jesus „Wahrheit“, weil er nicht nur mit seinen Worten, sondern mit seinem ganzen Lebens-Geschick Zeugnis ablegt von der Liebe Gottes; als „Weg“ ist Jesus Leben, weil er zum Vater geht, um die Jünger durch seinen Tod und seiner Auferstehung Anteil nehmen zu lassen an jener Liebe zwischen dem Vater und dem Sohn, die zur Sendung Jesu geführt hat (3,16) und alles Heil in sich birgt

- Ich bin der Weinstock, ihr seid die Reben. (Joh 15,1.5) :: Er ist die Quelle der Lebenskraft, mit der die Gläubigen verbunden bleiben müssen. „Weinstock“ (15,1) ist Jesus als derjenige, der in Gemeinschaft mit den Jüngern, seinen „Freunden“ lebt (15,1); so wenig die Jünger, losgelöst von Jesus irgend etwas tun können, so sehr gibt Jesus ihnen die Lebenskraft, die sie brauchen.


** König David - ein Mann nach Gottes Herz

Samuel - Saul

David - Goliath

Saul - David: Konflikt

Davids Freundschaft mit Jonathan (Sohn von Saul)

** Der große Unbekannte - der Heilige Geist

Cf YouCat Firmbuch

- "Wer bin ich?" spielen
- Juden; modernste Religion (an einen Gott; Griechen, Römer, ...)
- Jesus: Gott - Vater; Hl. Geist.
- Bei der Taufe empfing Jesus nicht eine anonyme Energie, sondern hier wird seine Beziehung zu Gott sichtbar. Gott schenkt sich selbst, mehr oder weniger kann Gott nicht geben. 
- Hl. Geist ist Gott, wie Vater und Sohn. Er ist die Liebe. Er verbindet uns mit Christus und die Gläubigen untereinander.
- Wäre toll, wenn in unserem Herzen nur Liebe wäre.
- Versuche einmal, in deinem Zimmer für 5 Minuten nur still zu sein. Was steigt da in deinem Herzen auf? Lasse dies zu, auch die Leere. Dort will Gott wohnen.
- Gott hat uns so erschaffen, dass unser Herz mit nichts zufrieden ist, außer mit Gott.
- Joh 20 und Apg 2 lesen: er vertreibt die Angst; wir könne Dinge tun, die wir alleine nicht schaffen; Von Jesus erzählen.
- Früchte des Hl. Geistes
- Gebet zum Hl. Geist

Gaben des Hl. Geistes:
- AT: heiligmachende Gnade; jeder Christ erhält alle sieben Gaben
- NT: Charismen - zum Dienst am Nächsten; Gott teilt jedem nach Seinem Willen und Dienst zu.

[[denote:20250527T081402::#h:a29e5626-6de8-48af-a314-61054fe28cb8][Die 7 Gaben des Hl. Geistes::Die Bausteine für einer geistlich bewegte Kirche]]

[[denote:20260312T131256][Thomas von Aquin Gaben des Hl. Geistes]]


** Ostern / Auferstehung
YouTube Video von Johannes Hartl: [[https://www.youtube.com/watch?v=EEtOLeIrshI]] & 
[[https://www.youtube.com/watch?v=qVyiSLjKj80]] 
[[https://www.youtube.com/watch?v=QHEKYZYoCbY]]
[[https://www.youtube.com/watch?v=r7YJOBtnK5w]]

Jesus - mehr als ein Prophet? [[https://www.youtube.com/watch?v=2UGhH4EmBOY]]

Faktencheck zur Auferstehung
- Jesus hat nicht gelebt
- Jesus starb nicht am Kreuz
- Erscheinungen erfunden
- Berichte unglaubwürdig

Lesen: Joh 20

Außerbiblische Quellen:

*** Flavius Josephus

Als Testimonium Flavianum bezeichnet man den 93 n. Chr. verfassten Abschnitt im Buch 18, Verse 63–64 aus den Antiquitates Judaicae des Flavius Josephus:

#+begin_quote
"Um diese Zeit lebte Jesus, ein weiser Mann, wenn man ihn überhaupt einen Menschen nennen darf. Er vollbrachte nämlich ganz unglaubliche Taten und war der Lehrer aller Menschen, die mit Lust die Wahrheit aufnahmen. So zog er viele Juden und auch viele Heiden an sich. Dieser war der Christus. Und obgleich ihn Pilatus auf Betreiben der Vornehmsten unseres Volkes zum Kreuzestod verurteilte, wurden doch seine früheren Anhänger ihm nicht untreu. Denn er erschien ihnen am dritten Tage wieder lebend, wie gottgesandte Propheten dies und tausend andere wunderbare Dinge von ihm vorhergesagt hatten. Und bis auf den heutigen Tag besteht das Volk der Christen, die sich nach ihm nennen, fort.[7]"
#+end_quote

*** Tacitus

Tacitus war schon zu Lebzeiten nicht nur als erfolgreicher Politiker, sondern auch als römischer Historiker bekannt. Er schrieb 116–117 seine teilweise recht kaiserkritischen Annalen, deren Bücher 13–16 die Regentschaft Neros beschreiben: Auf die ruhigen Anfangsjahre (A. 13) sei mit dem Brand Roms 64 eine Tyrannei gefolgt (A. 14–16). Nero habe vergeblich versucht, den Verdacht, er selbst habe die Brandlegung befohlen, durch alle möglichen Anstrengungen zu beschwichtigen. In diesem Zusammenhang erwähnte Tacitus die Christen:

#+begin_quote
„Um das Gerücht aus der Welt zu schaffen, schob er die Schuld auf andere und verhängte die ausgesuchtesten Strafen über die wegen ihrer Verbrechen Verhassten, die das Volk ‚Chrestianer‘ nannte. Der Urheber dieses Namens ist Christus, der unter der Regierung des Tiberius vom Prokurator Pontius Pilatus hingerichtet worden war. Für den Augenblick war [so] der verderbliche Aberglaube unterdrückt worden, trat aber später wieder hervor und verbreitete sich nicht nur in Judäa, wo das Übel aufgekommen war, sondern auch in Rom, wo alle Greuel und Abscheulichkeiten der ganzen Welt zusammenströmen und gefeiert werden.“[30]
#+end_quote

*** Plinius der Jüngere

Plinius war seit etwa 111 als Statthalter in Bithynien (heute İzmit, Türkei) für Anzeigen aus der Bevölkerung gegen dort lebende Christen zuständig. In einem Briefwechsel mit Kaiser Trajan, den er später in seine zehnbändige Briefsammlung aufnahm (Plinius-Briefe), holte er sich rechtliche Bestätigung für sein Verfahren mit ihnen. In epistula X/96 beschrieb er seine Verhörmethoden, die ihm bekannt gewordenen christlichen Bräuche und seinen Eindruck von ihrem Glauben:[32]

#+begin_quote
„Denen, die bestritten, Christen zu sein oder gewesen zu sein, sprach ich die Formel vor und ließ sie die Götter anrufen und zu Deinem Standbild […] mit Weihrauch- und Weinspenden beten und außerdem Christus lästern. Daraufhin konnten sie meines Erachtens freigelassen werden. Denn zu all dem sollen sich wahre Christen nicht zwingen lassen. […]

Sie versicherten, ihre ganze Schuld oder ihr Irrtum habe darin bestanden, dass sie sich regelmäßig an einem bestimmten Tag vor Dämmerung versammelten, um Christus als Gott ein Lied darzubringen und sich durch Eid zu verpflichten – nicht etwa zu einem Verbrechen, sondern zur Unterlassung von Diebstahl, Raub, Ehebruch, Treulosigkeit, Unterschlagung von anvertrautem Gut.

Umso mehr hielt ich es für notwendig, von zwei sogenannten ‚Dienerinnen‘ die Wahrheit auch noch durch Folter zu erforschen. Ich fand nichts als absurden, maßlosen Aberglauben. […] Denn nicht nur über die Städte, auch über die Dörfer hat sich die Seuche dieses Aberglaubens verbreitet. Doch es scheint möglich, sie einzudämmen und auszutilgen.“
#+begin_quote


** Emmausjünger

Lk 24 lesen und Bildergeschichte zeichnen - Bezug zu Eucharistie herstellen

** YouCat

Thema Glaube / Gebet?


** Einführung / Ziele


** Wiederholung


** Themen


** Hefteintrag
Arbeitsweg


* Reflexionen

** Barnay Luis 

** Borisova Doroteya

** Burggraf Maximilian

** Grögler Luisa

** Huber Johanna 

** Janiba Theresa 

** Kreiseder Danie

** Maislinger Daniel 

** Quehenberger Paul

** Stemeseder Isabella 

** Strasser Johannes

** Stumvoll Sophia 

