#+title:      Konferenz Seekirchen
#+date:       [2025-11-12 Mi 16:08]
#+filetags:   :sk:
#+identifier: 20251112T160816

* Reisenkostenabrechnung
Heimadresse verknüpfen beim neuen Antrag; rechtzeitig Anträge für FB stellen

* Rückblick und Evaluation Tag der offenen Tür
eventuell kürzer (um 10h00 nix mehr los); z.B. 8h00 - 10h15

* Räumungsübung
alle Schüler waren in max. 3 Minuten draußen; manche L nicht (weil Alarm zu leise, auch im Container). Manche Schüler waren laut - ist schwierig wegen Durchsagen. 

Manche waren barfuß weil keine Hausschuhe. Hauptausgang mit Türschließer - aufspannen! Beide Türelemente. Nicht in jedem Stockwerk wurde eine Endkontrolle (alle Räume, Toiletten, ...) durchgeführt. In einer Klasse (2b, 4a, ...) wollten die Kinder Jause und Handy mitnehmen. 

Beim Sammelplatz waren zwei Klasse ohne Lehrer (1b, 4b) - durch zählen. LL schauen beim Sammelplatz: welche Klassen sind ohne Lehrer? Natürlich, in der Pause ... (L nach der Pause hat in dieser Klasse Unterricht). Randstunden (R): manche Schüler sind weg - wir wissen es nicht ... was tun? Schüler dürfen nur dann gehen, wenn der Reli-Lehrer kommt. Kompliziert. Oder: nach der letzten Stunde das Gebäude verlassen.

Container: Alarm war sehr leise - Schüler wollten wieder hinein, oder wollten nicht gehen. 

Fluchtwege waren nicht korrekt eingezeichnet. 

Am Ende: wer ist für welche Klasse verantwortlich?

Im Winter: Fluchträume? Kindergarten, Kirche, Gemeinde, ...

Amoklauf (Alarm + Durchsage "Code 100")
Treffpunkt - Gemeinde

- Flucht
- Verbarrikadieren
- Gegenangriff


* Schnuppern VS

* Adventkranzsegnung
in Vorbereitung, 28.11., 
8h45-9h15 (1. / 2. Klassen)
9h45-10h15 (3. / 4. Klassen)

Jede Klasse bringt einen Adventkranz (eine Kerze anzünden).

* Absage Weihnachtsfeier

* Faschingsdienstag
1. - 4. Stunde

* Sylvia kommt
Welches Kind hat sich verändert? ...

* Nächstes Schuljahr / Stundenplanung
Wer nicht volle LV hat, soll eine Bandbreite angeben, die Mitte soll mein Wunsch sein - bis Jänner! Welches Fach?

* Freundliches Grüßen
Kinder grüßen weniger, nicht mehr freundlich ... einschreiten; auch außerhalb der Schule. Initiative von mir aus; ... v.a. beim Betreten der Schule; ...

* Schulplaner
nur für 1. Klassen? wird dann teuer; wird er verwendet - kein Problem! Zum Organisieren ist besser und einfacher. Schulplaner für ALLE!

* Lehrerkalender digital?
Webuntis - Niemand kennt sich damit aus. Betroffene Schüler erhalten Info. (edividual? ganz schlecht). 

* Umbau - Klassenräume belegen?

* Zwei Afghanische Schüler
1d / ...?

* ONE NOTE Schulung
Anfänger / Fortgeschrittene

App für Linux? eig. nur Browser App.

* Instagram Liste
Schülerliste - wer NICHT auf Instagram darf (haben Eltern entschieden).
