#+title:      Ideen für Themen
#+date:       [2025-10-28 Di 08:38]
#+filetags:   :school:
#+identifier: 20251028T083829

* Allerheiligen Allerseelen

- Leben nach dem Tod
- Hoffnung
- Sehnsucht nach dem Himmel
- Gebet für Verstorbene
- Vom Ego zu Gott; von der Autonomie zur Theonomie.
- Glücklich ist, wer nicht um sich selbst kreist, sondern für andere da ist, nach Werten strebt, ...


* Bibel

Abraham, Isaak, Jakob, ... Moses ... lesen;

Ein Evangelium lesen; Apostelgeschichte; einen Brief; Buch der Offenbarung.

* Gott

Gott ist nicht ein "Ding", sondern die Ursache, dass die Welt existiert. Gott ist außerhalb von Raum und Zeit und Materie. Gott ist. Gott ist nicht hier in diesem Raum. Nein. Ist Gott in diesem Raum? Ja, da er die Ursache ist für alles, was hier existiert. 

Hl. Agustinus:
Gott ist höher als ich mir es vorstellen kann, Er ist mir näher, als ich es mir vorstellen kann. Er ist so hoch, dass ich ihn nicht erreichen kann, Er ist mir näher, ich kann mich nicht vor ihm verstecken. Verliebe dich in Gott.

  
