#+title:      Die 7 Gaben des Hl. Geistes
#+date:       [2025-05-27 Di 08:14]
#+filetags:   :theology:
#+identifier: 20250527T081402
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/Documents/references/Literatur.bib
#+SETUPFILE: ~/Documents/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/Documents/exports/Die sieben Gaben des Hl Geistes.html


* Literatur:

- Cantalamessa, Raniero: Komm, hl. Geist!
- Thomas von Aquin: Summa IaIIae, IIaIIae


* Was sind die 7 Gaben des Heiligen Geistes?

Was sind die 7 Gaben des Heiligen Geistes und werden sie in der Bibel beschrieben. Alle Erläuterungen findest du in diesem Artikel.


* Die Sieben Gaben des Heiligen Geistes

Der Heilige Geist, der den Jüngern von Jesus versprochen wurde, ist im Neuen Testament mit drei Wort präsent: dynamis (= Allmacht Gottes), energeia (= wirksame Kraft), pneuma (= lebendiger Atem). Im Heiligen Geist ist uns die Fülle der Gnade geschenkt. Die biblische Rede von den „Sieben Gaben des Heiligen Geistes“ präzisiert das, was durch das Geschenk des Heiligen Geistes im einzelnen Gläubigen an Begabungen sichtbar werden kann und möglich wird. Man spricht von Charisma oder Charismen (altgriech. = aus Güte geschenkte Gabe).


* Was sagt die Heilige Schrift?

Im neuen Testament gibt es gleich an verschiedenen Stellen Listen der „Gaben des Heiligen Geistes“, die sich zum Teil überschneiden – etwa Röm 12,6-8; 1 Kor 12,8-10; 1 Kor 12,28-31; Eph 4,7.11f.; 1 Petr 4,10-11. Traditionell ist in der Kirche die Rede von „sieben“ Gaben des Heiligen Geistes. YOUCAT 310: „Die sieben Gaben des Heiligen Geistes sind: Weisheit, Einsicht, Rat, Stärke, Erkenntnis, Frömmigkeit und Gottesfurcht. Damit „begabt“ der Heilige Geist Christen; d.h., er schenkt ihnen, über ihre natürlichen Anlagen hinaus, bestimmte Kräfte und gibt ihnen die Chance, zu speziellen Werkzeugen Gottes in dieser Welt zu werden.“


* Die kleine YOUCAT-Katechese

** Der geheime Bauplan der Kirche

In Neuburg an der Donau gibt es eine schöne alte Kirche, in der die Leute nur zur Decke schauen müssen, um die „Sieben Gaben des Heiligen Geistes“ zu entdecken. In einem kleinen Film erklärt Annemarie Strahl, was es mit dem merkwürdigen Gemälde auf sich hat. Ihre Erklärung ist schön und genau: Dargestellt wird der Heilige Geist, „wie er die Kirche erbaut ... Er ist da, wo in einem Deckengewölbe der Schlussstein steht, ohne den ein Gewölbe zusammenbricht. Unsere Kirche besteht nur deshalb, weil der Heilige Geist da ist und seine Gaben ausgießt ... Die Sieben Gaben fließen ja in sieben verschiedene Richtungen, und jeder, denke ich, hat eine Gabe oder mehrere Gaben gekriegt – ich glaube nicht, dass einer alle hat.“ Genau das steht auch in YOUCAT 119 auf die Frage: „Was tut der Heilige Geist in der Kirche?“ Antwort: „Der Heilige Geist baut die Kirche auf und treibt sie an. Er erinnert sie an ihre Mission. Er beruft Menschen in ihren Dienst und schenkt ihnen die nötigen Gaben. Er führt uns immer tiefer in die Gemeinschaft mit dem dreifaltigen Gott.“


** Viele Architekten verderben die Kirche

In Deutschland gibt es ein Sprichwort, das lautet: Viele Köche verderben den Brei. Der eine gibt noch ein bisschen Salz dazu. Der andere meint: Jetzt noch einen Löffel Honig! Der dritte sagt: Brei ohne Knoblauch? Geht ja gar nicht! Wetten, dass der Brei ungenießbar wird!? Genauso ungenießbar wird die Kirche, wenn selbsternannte Architekten meinen, die Kirche sei das, was wir Menschen aus ihr machen. Hier noch ein kluges Buch! Dort noch ein neues Gremium! Und hier eine fabelhafte Denkschrift! Ungeniert basteln sie an der Kirche herum, um ihre Kanten zu glätten und ihr Erscheinungsbild akzeptabler für die Zeitgenossen zu machen. Menschen können im Hören auf Gott sehr wohl der Kirche dienen. Die Kirche hat zuletzt aber nur einen Baumeister. Der ist unsichtbar, nur mit feinsten Sensorien zu erspüren, aber hochaktiv. „Der Heilige Geist ist es, der die Kirche als ganze in der Wahrheit hält und sie immer tiefer in die Erkenntnis Gottes führt. Es ist der Heilige Geist, der in den Sakramenten wirkt und die Heilige Schrift für uns lebendig macht.“ (YOUCAT 119) Und darauf kommt es an. Als Verein mit hohen Idealen, als menschliche Gemeinschaft, als Gruppe, als Partei – überhaupt als soziologisches Gebilde ist die Kirche uninteressant.

Dass es tatsächlich der Heilige Geist ist, der in der Kirche wirkt, geht allein aus der Tatsache hervor, dass es sie nach 2000 Jahren noch immer gibt. In ihrer langen Geschichte wurde mit der Kirche alles gemacht: Sie wurde verboten oder benutzt, in den Himmel gehoben oder verflucht, bestochen oder verfolgt, eingesperrt oder ausgeschlossen – und alle paar Jahre wurde sie für tot erklärt. Napoleon drohte einmal dem vatikanischen Unterhändler Consalvi: „Ist Ihnen klar, Eminenz, dass ich Ihre Kirche jederzeit zerstören kann?“ Consalvi antwortete: „Ist Ihnen klar, Majestät, dass nicht einmal wir Priester das in achtzehn Jahrhunderten fertiggebracht haben?“ Und noch etwas spricht für den geheimnisvollen geistlichen Architekten: „Die vielen Heiligen aller Epochen und Kulturen sind der sichtbare Beweis seiner Gegenwart.“ (YOUCAT 119). Als die Kirche vor 800 Jahren in Geld, Macht und Ruhm versank, waren es nicht Päpste und Prälaten, die sie vor dem Untergang bewahrten. Ein kleiner Mann namens Franziskus baute sie im Heiligen Geist wieder auf. Und als Rom vor 500 Jahren von der Reformation gerichtet und von Söldnerheeren geplündert wurden, zogen wieder nicht Päpste und Prälaten sie aus dem Dreck, sondern ein heiliger Narr Gottes, Philipp Neri, und ein heiliger Soldat Gottes: Ignatius von Loyola.


** Die Bausteine für einer geistlich bewegte Kirche

*** Weisheit (sapientia)

Die Kirche braucht zunächst die Gabe der Weisheit – oder (um einen anderen Begriff zu erwähnen) den „Geist der Unterscheidung“. In 1 Joh 4,1 heißt es: „Traut nicht jedem Geist, sondern prüft die Geister, ob sie aus Gott sind; denn viele falsche Propheten sind in der Welt aufgetreten.“ Darum sagen weise Christen oft: Lass mich beten und eine Nacht darüber schlafen, dann kann ich ein Urteil fällen.


*** Einsicht (intellectus)

Die Kirche braucht sodann die Gabe der Einsicht. Einsicht meint: Bleib nicht an der Oberfläche! Schau in die Tiefe! Erkenne, was Gott dir sagen oder zeigen will. Das „hörende Herz“ (1 Kön 3,9) das sich der weise König Salomo erbat, finden wir wieder bei den beiden Emmausjüngern, die sich mit düsteren Gedanken aus dem Staub machen, bis ein geheimnisvoller Dritter sich ihnen zugesellt. Beim Brotbrechen erst gehen den Verzweifelten die Augen auf. Ohne Einsicht würden wir niemals erkennen, „was kein Auge gesehen und kein Ohr gehört hat, was keinem Menschen in den Sinn gekommen ist: das Große das Gott denen bereitet hat, die ihn lieben. Denn uns hat es Gott enthüllt durch den Geist.“ (1Kor 2,9-10)

*** Guter Rat

Die Kirche braucht die Gabe des Rates. Denn oft sind wir ratlos – und unsere Ratlosigkeit bewirkt Kurzschlusshandlungen. Dann machen wir es - nicht Gott. Christsein lebt von Vertrauen und Geduld, vom Warten auf die Hand Gottes. Wenn die Stunde gekommen ist, wird uns deutlich werden, was das Richtige ist. Wir dürfen an das Wort denken, das Jesus seinen Jüngern mit auf den Weg gab für die Stunde, in der man sie vor Gericht ziehen würde: „Macht euch keine Sorgen, wie und was ihr reden sollt; denn es wird euch in jener Stunde eingegeben, was ihr sagen sollt. Nicht ihr werdet dann reden, sondern der Geist eures Vaters wird durch euch reden.“ (Mt 10, 19-20)


*** Stärke

Die Kirche braucht die Gabe der Stärke. Man kann auch sagen: Sie braucht Tapferkeit und prophetische Menschen. „Wer tapfer ist“, heißt es YOUCAT 303, „tritt dauerhaft für das einmal erkannte Gute ein, selbst wenn er im Extremfall dafür sogar das eigene Leben opfern müsste.“ Die wahren Diener Gottes halten sich an 2 Tim 4,2: „Verkünde das Wort, tritt dafür ein, ob man es hören will oder nicht.“ Von einem mutigen Widerstandskämpfer gegen Hitler, Robert Prinz von Arenberg, gibt es den Ausspruch: „Mehr als umbringen können sie mich nicht. Und selbst wenn sie mich umbringen, bringt mich das noch lange nicht um.“

*** Erkenntnis (scientia)

Die Kirche braucht zudem die Gabe der Erkenntnis. Damit ist nicht einfach die menschliche Vernunft gemeint, sondern jenes „Erkennen“, das von Jesus in der Geschichte von der Frau am Jakobsbrunnen (Joh 4) berichtet wird. Obwohl Jesus die Frau nicht kennt, ist er in der Lage, ihre innere Not zu erfassen und ihr den heilenden Weg zu weisen. In der Kirche finden wir diese Gabe der Erkenntnis oft bei klugen Beichtvätern und Menschen, die andere geistlich begleiten.


*** Frömmigkeit

Sodann braucht die Kirche die Gabe der Frömmigkeit. Fromm ist ein Mensch dann, wenn er Gott zum Mittelpunkt seines Denkens, Urteilens und Handelns gemacht hat. „Wenn man Gott erkannt hat“, heißt es in YOUCAT 34, „muss man ihn an die erste Stelle in seinem Leben setzen.“ Frömmigkeit ist ein anderes Wort für Hingabe an Gott. Von der Gnade Gottes sagt Tit 2,11-12: „Sie erzieht uns dazu, uns von der Gottlosigkeit und den irdischen Begierden loszusagen und besonnen, gerecht und fromm in dieser Welt zu leben.“


*** Gottesfurcht

Zuletzt braucht die Kirche die Gabe der Gottesfurcht. Für viele moderne Menschen ist sie etwas Fragwürdiges. Für die Heilige Schrift aber ist die Gottesfurcht der „Anfang der Erkenntnis, nur Toren verachten Weisheit und Zucht.“ (Spr 1,7) Gemeint ist einen Haltung, die von der unendlichen Erhabenheit Gottes über alles menschliche Denken und Handeln ausgeht. Der Gottesfürchtige stellt den Willen Gottes über seine persönlichen Pläne; er tut alles, um nach Gottes Geboten zu leben und sie nicht zu übertreten.


* Früchte des Heiligen Geistes

** LIEBE

Wo der Heilige Geist ist, da ist Liebe. Liebe ist mehr als ein Gefühl. Sonst hätten wir Liebe nur zu einem total süßen Baby. Aber wir sollen Liebe zu allen Babys haben, auch zu denen mit einem offenen Rücken. Wenn der Heilige Geist die Liebe Gottes in uns entfacht, dann ist das, wie wenn du den Stecker in die Steckdose tust. In dir sind alle Gefühle, die Gott selbst für das hat, was er schuf: die Menschen, die Tiere, die Blumen. Gott ist verrückt vor Liebe zu uns. Die göttliche Liebe ist keine Wenn-dann-Liebe, keine Liebe auf Zeit; sie „hört niemals auf“. Sie ist treu. Sie verwandelt alles, vor allem die Welt deiner Beziehungen. Mit Gottes Liebe in dir, schaust du alles mit neuen Augen an.


** FREUDE

Wo der Heilige Geist ist, da ist Freude. Stell dir ein Rockkonzert vor, bei dem alle jubeln, tanzen, die Arme in die Höhe reißen, in die Luft springen. Jesus hat den Tod besiegt. Wie cool ist das denn! Wir sind erlöst. Das Paradies wartet auf uns. Wir können tanzen vor Glück, auch wenn wir jetzt noch jede Menge Probleme an der Backe haben. Im Himmel, sagt man, tanzen die Engel.  Und es ist größerer Jubel über einen einzigen Menschen, der umkehrt und seinen Sündenquatsch hinter sich lässt, „als über 99 Gerechte“.


** FRIEDE

Wo der Heilige Geist ist, da ist Frieden. Alle innere Unruhe hört auf. Die Traurigkeit sinkt ab. Die Angst
schleicht sich davon. Du findest deine innere Balance, wirst von deinen Leidenschaften nicht wie ein Blatt im
Wind herumgetrieben. Andere suchen deine Nähe und Freundschaft, weil du in Harmonie bist mit dir selbst und
mit anderen Menschen, ja sogar mit Tieren. Der Friede in deinem Herzen macht dich total sympathisch.


** LANGMUT

Wo der Heilige Geist ist, da ist Langmut. Langmut heißt: Du hast einen gaaanz langen Mut. Wo andere in den Sack
hauen, holst du den Turbo raus. Strohfeuer war gestern. Wo du früher Luft hattest für 800 Meter, da läufst du jetzt Marathon. Rückschläge steckst du weg wie nichts. Der Heilige Geist macht dich zu einem Fighter, der niemals aufsteckt. Andere rätseln, woher du die Power hast. Du weißt es.


** FREUNDLICHKEIT

Wo der Heilige Geist ist, da ist Freundlichkeit. Du hältst einer Frau die Tür auf. Du lässt andere bei dir
abschreiben. Du übst heimlich mit einem, der immer den Volleyball-Aufschlag verhaut. Mutter Teresa schärfte
ihren Schwestern, die sich um die Sterbenden kümmerten, immer ein: „Es genügt nicht, dass ihr sie pflegt. ihr
müsst es mit einem Lächeln tun!“


** GÜTE

Wo der Heilige Geist ist, da ist Güte. Gott ist ganz gut. Das Gute zu tun, beamt uns in die Nähe Gottes. Wer immer wieder das Gute tut, wird automatisch „gütig“ – nämlich gewohnheitsmäßig gut zu anderen. Du redest
mit einem Penner, kaufst ihm eine Zeitschrift ab. Du hilfst einem Kind. Du sprichst einen Einsamen an. Du
hörst einem alten Menschen lange zu. Du kümmerst dich um die Sorgen anderer. Gütig zu leben, ist der Lifestyle Gottes. In der Nähe eines gütigen Menschen kann man aufatmen und aufblühen.


** TREUE

Wo der Heilige Geist ist, da ist Treue. Gott ist nicht mal so und mal so. Du kannst dich hundertprozentig auf ihn verlassen, auch wenn er deine Bitten manchmal anders erfüllt, als du dir es wünschst. Er ist dir treu, auch wenn du ihn und andere Menschen tausendmal verrätst. Der Heilige Geist hilft dir, dass dein Herz fest wird und du „treu bis in den Tod“ wirst – ein wahres Abbild des treuen Gottes. Kennst du Saint-Exupérys Buch vom kleinen Prinzen? Da steht ein wunderbarer Satz über die Treue: „Du bist zeitlebens für das verantwortlich, was du dir vertraut gemacht hast.“


** SANFTMUT

Wo der Heilige Geist ist, da ist Sanftmut. Du wirst, sagt diese Frucht des Heiligen Geistes, Mut haben, aber sanften Mut, also einen Mut, der nicht gewalttätig ist und im Kampf für eine gute Sache mehr zerstört, als dass er aufbaut, heilt und etwas Schönes erschafft. Du wirst also Mut haben, aber in Verbindung mit Liebe und Geduld. In liebevoller Geduld etwas Großes vollbringen – das ist die Verwegenheit, die Gott gefällt. Jesus erlöste die Welt durch einen besondere Art von Kühnheit: Er ging den Weg der Gewaltlosigkeit bis zum Kreuz.


** SELBSTBEHERRSCHUNG

Wo der Heilige Geist ist, da ist Selbstbeherrschung. Der Heilige Geist in dir bringt dich dazu, dass du ganz
du selbst sein kannst. Du wirst nicht länger besessen sein von Dingen, die dich gefangennehmen, Menschen,
die dich in Abhängigkeit brachten, Machthabern, die dich herumkommandieren. Du wirst nicht mehr von
Gier getrieben sein, bist nicht mehr der Sklave deiner Leidenschaften. Du wirst frei sein, das zu tun, was du
von Herzen gern tun möchtest: das Gute, wozu dich Gott erschaffen hat.


* Charismatische Bewegungen

Die Pfingstbewegung und die charismatische Bewegung gehen (in Anlehnung an die Briefe des Apostels Paulus im Neuen Testament) davon aus, dass jeder Christ Gaben des Heiligen Geistes hat. Die Gaben des Geistes sind mehr als natürliche Begabungen, sie sind ihnen aber nicht entgegengesetzt. Durch die Geistesgaben soll die Gemeinde (der Leib Jesu Christi) erbaut werden.

    „So auch ihr: da ihr euch bemüht um die Gaben des Geistes, so trachtet danach, dass ihr die Gemeinde erbaut und alles reichlich habt.“

– 1 Kor 14,12 EU

In der charismatischen Bewegung werden üblicherweise die folgenden Gaben zu den Gaben des Heiligen Geistes gezählt:

** Charismen

- Prophetie/Weissagung (Röm 12,6 EU, 1 Kor 12,28 EU)
- Zungenrede (1 Kor 12,10 EU; 12,28 EU)
- Auslegung der Zungenrede (1 Kor 12,10 EU)
- Krankenheilung (1 Kor 12,9 EU; 12,28 EU)
- Wundertaten (1 Kor 12,10 EU; 12,28 EU)
- Weisheit/Erkenntnis (1 Kor 12,8 EU)
- Unterscheidung der Geister (1 Kor 12,10 EU)
- Lehren/Predigt (Röm 12,7 EU, 1 Kor 12,28 EU)
- (Gemeinde-)Leitung (Röm 12,8 EU, 1 Kor 12,28 EU)
- Hirtendienst/Seelsorge
- Evangelisation
- Gebet
- Ermahnung (Röm 12,8 EU)

** Weitere Gaben des Geistes

Auch die folgenden Gaben werden manchmal ebenfalls zu den Gaben des Heiligen Geistes gezählt:

- Dienen (Diakonie)
- Geben
- Barmherzigkeit
- Glaube
- Leidensbereitschaft
- Keuschheit
- Ehelosigkeit
- Freiwillige Armut
- Gastfreundschaft
- Dämonenaustreibung
- Apostelamt
- Handwerk
- Musik
- Mission
- Kreativität





