#+title:      Gedanken zur heutigen Konferenz
#+date:       [2025-02-03 Mo 23:18]
#+filetags:   :schule:
#+identifier: 20250203T231815

* Vorgehen der Direktorin
Bis zum Ende verlief die Konferenz relativ normal, sie war sehr lang. Bei der Klassenkonferenz der 3a traute ich mich nicht, meine Ideen bzgl "WZ" für Jakob, Philipp, Simon, etc. vorzubringen.

Dann erzählte Florian zum Schluss vom unglaublichen Vorgehen von Gabi gegen ihn selbst.

Florian hat E-Mails bzgl. Stundenreduktionen überprüft und hat dabei - völlig unschuldig - andere E-Mails angesehen. Dadurch entdeckte er, wie Gabi äußerst negativ über Florian an die BD und die Juristin der BD berichtet hatte (und über andere Kollegen ebenfalls). Die Vorwürfe waren alle haltlos. Im Krankenstand hat sie jede E-Mails der Schule bzw der Direktion gelesen. Und Florian auf die Finger geklopft. An einem Samstag war sie sogar in der Schule.

Zu diesem Zeitpunkt fiel mir ein Stein vom Herzen. Einerseits tat es mir schrecklich leid für Florian, andererseits sah ich, dass Gabi nicht nur mit mir, sondern auch mit anderen Kollegen ein komplett manipulatives Spiel spielte. Fruchtbar! Also hab ich meinen Mut zusammengenommen und von mir erzählt. Auch andere Kollegen berichteten von ihren Erfahrungen.

Eine rote Linie ist überschritten. Florian wird nicht mehr als Vizechef zur Verfügung stellen.

* Was und wie sagen wir es Gabi?
Wir haben uns geeignet, uns bis zu den Ferien mit der Gewerkschaft zu treffen; und Gabi gleich nach den Ferien zur Rede zu stellen. Vielleicht - so hoffen wir - kommt sie selbst zur Einsicht, dass sie unter diesen Umständen nicht mehr die Schule leiten kann, nein: gar keine Schule mehr leiten kann.

* Persönlich...
Wow! das war ein Hammer zum Schluss der Konferenz! Jetzt weiß ich, dass ich mich auf meine Kollegen verlassen kann. Falls sie zurückkommt, werde ich Grenzen setzen und keine Gespräche mit ihr haben.
