#+title:      Caddy bye bye
#+date:       [2025-05-23 Fr 11:56]
#+filetags:   :emacs:
#+identifier: 20250523T115657
#+DESCRIPTION: This text was generated using the After Dark post archetype.
#+HUGO_CATEGORIES: privat
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_BASE_DIR: /home/matthias/flying-toasters/
#+AUTHOR: Matthias Fuchs

* Erinnerungen
Unser VW Caddy hat seinen Dienst getan und darf endlich in seinen wohlverdienten Ruhestand gehen. Dieses Auto hat uns die letzten beinahe 10 Jahren treu begleitet. Welch schöne Erinnerungen verbinden wir als Familie mit ihm!

Es hat uns so gut wie nie in Stich gelassen. Camping in Italien, Urlaub in Frankreich, mehrmals die kompletten Westalpen umrundet, Besuch der Schwiegereltern in der Nähe von Paris, Col de l'Arzelier, Triest, Genua, Nizza, Marseille, Wien, Marchegg, Mariazell, etc, ...

[Fotos einfügen]

* Kosten
Die letzten Services wurden immer teurer; wir mussten jedes Mal zwischen 1000 und 1700 Euro bezahlen. So auch dieses Mal; deshalb haben wir uns doch mit ein bisschen Wehmut dazu entscheiden müssen, den Caddy zu verkaufen (950 Euro). 

* Neues Auto
Seit dem 31.10.2024 steht ein neues Auto in der Garage: Dacia Duster Hybrid, BJ. 2024. Das Auto ist so cool; macht richtig Freude und ist wunderschön. Dem Hybridantrieb gegenüber war ich lange sehr skeptisch eingestellt. Doch der Verkäufer von Renault / Dacia in Straßwalchen hat ganze Arbeit geleistet.

[Fotos einfügen]

Ich habe spürbar Geld und Treibstoff gespart.


