#+title:      Notenkonferenz Seekirchen
#+date:       [2026-02-02 Mo 13:42]
#+filetags:   :schule:
#+identifier: 20260202T134250

* Begrüßung

* Notenkonferenz
Dazu gehen alle Lehrer einer Klasse in einen extra Raum; laut Erfahrung sollte das fix gehen.

** 1a

** 1b

** 1c

** 2a

** 2b

** 2c

** 3a

** 3b

** 3c

** 4a

** 4b

** 4c


* Allfälliges

** Konferenz im März - Schulbuchkonferenz 
Welches Buch / welche Reihe soll bestellt werden? Aufs Budget achten (besonders bei eBooks und eBooks-plus; Band 1 und Band 2). Arbeit mit Tablet - so manche Bücher (Papier) sind dann hinfällig. Darauf achten - Buchcode in School4you eintragen. Bsp.: KV mit Klasse in EDV Raum und Bücher eintragen.
 
** AO Schüler
Schreiben lernen / Anton App

** Schulnachrichten
Sind die Schüler / Fächer richtig zugeordnet, auch bei unverbindlichen Übungen. 

Bitte keine Klauseln berechnen - macht Gerry.

Bis Mittwoch Mittag sind Schulnachrichten fertig und unterschrieben.

** Eignungsprüfung
Wie ging es? Bis jetzt 7 fixe Anmeldungen; Christian Doppler Gymnasium hat viele zu viele zukünftige Fußballstars. Seekirchen ist Plan B. SMS Mattighofen (OÖ); ärztliche Bestätigung hat abgeschreckt, va jene weniger begabte.

** Skikurs
Super - 3x KH, 2x heimfahren. Alle 7 L waren sehr beschäftigt; es war sehr anstrengend. Handy ja / nein; va. wegen den Eltern (3x Zuhause melden; Katzenfoto dem Kind zeigen, da es sonst nicht schlafen kann), und nicht wegen den Schülern. Bitte am Forum Schulbeginn sagen (zweite Klassen). Skikurs - kein Handy mehr. 

Schulforum - kein Handy bei Wandertag, Skikurs und Sportwoche (1. - 3. Klasse; Ausnahme: 4. Klasse: Wien Woche -  aber da nur tagsüber). 

** SA Termine - 2. Semester
Bis Ende des Semesters

** SEL-Gespräche
Für 4. Klassen bis Ende März / Anfang April erledigen / erledigt.
Für 1. - 3. Klassen bitte Termine festlegen. 

** Einhaltung der Schulordnung
- Handy einsperren
- Ende der Pause / Schüler in den Klassen, Türen geschlossen; dh. der L ist verantwortlich und muss pünktlich in der Klasse sein.
- letzte Stunde / Sauberkeit
- Hausschuhe Pflicht!
- etc.

Und wenn die Handys gar nicht mit genommen werden? Oder: Handy im Spint? 

Burschen WC ab morgen wieder normal; ohne List; in den Pausen.

** Übersiedeln
am 11. April (oder 11.5.?); anschließend ein neuer Aufsichtsplan; ... 

** PH-DAV-Befassung

** LernApps

** IKM+
letzter Termin für Modul "Lesen leicht"; durchgeführt - (sehr) schlecht ausgefallen

** Faschingsdienstag
Alles klar - Name auf persisch - Feedback geben ob's klappt.

** Siedeln:
offene Fragen?

** Gemeinde - Eislaufplatz
Eine oder zwei Klassen an den BM?

** Alles Gute!
