#+title:      Thomas von Aquin Gaben des Hl. Geistes
#+date:       [2026-03-12 Do 13:12]
#+filetags:   :theology:
#+identifier: 20260312T131256

Latein - Englisch
[[https://aquinas.cc/la/en/~ST.I-II.Q68]]

Latein - Deutsch (Bibliothek der Kirchenväter
[[https://bkv.unifr.ch/de/works/sth/versions/summe-der-theologie]]

* I-II, Q. 68 Die Gaben des Hl. Geistes

** Erster Artikel. Die Gaben sind unterschieden von den Tugenden.

a) Es scheint, Tugenden und Gaben bedeuten dasselbe. Denn: I. Gregor (1. moral. 12.) sagt: „Sieben Söhne werden uns geboren, wenn vermittelst der Empfängnis des guten Gedankens die sieben Tugenden des heiligen Geistes in uns entstehen;“ und dann zählt er nach Isai. II. die sieben Gaben des heiligen Geistes auf. Also sind die Gaben des heiligen Geistes Tugenden. II. Augustin (1. de quaest. Evgl. 8.) schreibt: „Sieben Laster sind entgegen den sieben Tugenden des heiligen Geistes“ d. h. den sieben Gaben. Die sieben Laster aber stehen gegenüber den sieben gemeinhin so genannten Tugenden. III. Wo die Begriffsbestimmung die nämliche ist, da sind auch die bezeichneten Dinge selbst die gleichen. Die Begriffsbestimmung der Tugend aber kommt den Gaben zu; denn jede dieser Gaben ist eine „gute Eigenheit des Geistes, vermöge deren man recht lebt“. Und ebenso ist die Begriffsbestimmung der Gabe den eingegossenen Tugenden entsprechend: „Eine Gabe ist das Darbieten von etwas, was man nicht erstatten kann“ nach 4 “Top. 4. Also ist kein Unterschied zwischen Gaben und Tugenden. IV. Mehrere Gaben sind bereits Tugenden; wie die Weisheit, das Verständnis, die Wissenschaft; der Rat gehört zur Klugheit; die Gottergebenheit ist eine Untergattung der Gerechtigkeit; die Stärke ist eine Kardinaltugend. 

Auf der anderen Seite unterscheidet Gregor der Große (I. c.) die sieben Gaben des heiligen Geistes von den drei theologischen Tugenden; die nach ihm die drei Töchter Jobs bedeuten. Ebenso unterscheidet er sie (2. moral. 26.) von den vier Kardinaltugenden.

b) Ich antworte; was den Charakter des Namens anbetrifft, haben die Tugenden und Gaben keinen Gegensatz zu einander. Denn die Natur der Tugend ist es, den Menschen zu vollenden, dass er gut wirke. Die vom Namen angezeigte Natur der Gabe nimmt Bezug auf die Ursache, von der sie ist. Nichts steht aber dem entgegen, dass das, was von einem anderen gegeben ist, vollende die Seele, damit sie gut wirke; zumal einige Tugenden von Gott eingegossen sind. Also danach ist kein Anhaltspunkt gegeben, die Tugend von der Gabe zu unterscheiden. Und deshalb meinten einige, die Gaben seien tatsächlich nicht unterschieden von den Tugenden. Indes bleibt diesen die Schwierigkeit, zu erklären, warum einzelne Tugenden nur Gaben genannt werden und nicht alle; und warum die Furcht z.B. nicht unter den Tugenden aufgezählt sei. Andere also nahmen einen Unterschied an. Jedoch bezeichneten sie nicht in gebührender Weise die Ursache für die Unterscheidung, insofern dieselbe nämlich derart gemeinsam sein muss für die Tugenden, dass sie keineswegs auf die Gaben angewendet werden könne und umgekehrt. Sie berücksichtigten nämlich, dass von den Gaben vier der Vernunft angehören, die Weisheit, die Wissenschaft, das Verständnis, der Rat; und drei dem begehrenden Teile, die Stärke, die Gottergebenheit, die Furcht; — sie meinten deshalb, die Gaben vollendeten das freie Urteil, insofern dasselbe eine Fähigkeit der Vernunft sei; die Tugenden aber vollendeten es, insofern dasselbe als eine Fähigkeit des Willens sich darstelle; — denn nur zwei Tugenden fanden sie in der Vernunft, den Glauben und die Klugheit, die anderen fanden sie im begehrenden Vermögen. Sollten sie aber Recht haben, so müssten alle Tugenden im begehrenden Teile sein und alle Gaben in der Vernunft. Andere nun berücksichtigten, dass Gregor der Große (2. moral. 26.) sagt: „Das Geschenk des heiligen Geistes, welches im vernünftigen Geiste, der ihm unterworfen ist, die Klugheit, Mäßigkeit, Gerechtigkeit und Stärke herstellt, festigt diesen selben vernünftigen Geist gegen die einzelnen Versuchungen durch die sieben Gaben.“ Und demgemäß nahmen sie an, dass die Tugenden da sind, um gut zu wirken; die Gaben, um den Versuchungen zu widerstehen. Aber auch kraft der Tugenden widersteht man den Versuchungen, die zu dem, was den Tugenden entgegen ist, anleiten wollen; denn jegliches Wesen widersteht seiner Natur gemäß dem ihm Entgegenstehenden; wie Cant. 8. es von der heiligen Liebe heißt: „Viele Wasser konnten nicht auslöschen die Liebe.“ Deshalb meinten wieder andere, dass ja diese Gaben in der Schrift gelehrt würden als dem Herrn Jesu Christo eigentümlich und dass deshalb die Tugenden wohl die Vollendung gäben, um gut zu wirken; die Gaben aber Christo gleichförmig machten, zumal was sein heiliges Leiden betrifft, wo diese Gaben am meisten leuchteten. Aber auch das ist nichts. Denn der Herr selbst leitet uns an, Ihm gleichförmig zu werden gemäß der Demut und Sanftmut, also gemäß den Tugenden, indem Er sagt: „Lernet von mir, wie ich sanftmütig bin und demütig von Herzen;“ und gemäß der Liebe, zudem Er sagt (Joh. 18.): „Liebet euch gegenseitig, wie ich euch geliebt habe.“ Und diese Tugenden leuchteten ebenso im Leiden Christi. Und deshalb soll man bei der Unterscheidung zwischen Tugenden und Gaben vielmehr der Redeweise der heiligen Schrift folgen, welche uns über die Gaben belehrt; nicht aber unter dieser Benennung „Gaben“, sondern vielmehr unter dem Ausdrucke „Geister“. Denn so heißt es Isai. 11.: „Es wird ruhen auf Ihm der Geist der Weisheit und des Verständnisses“ etc. Daraus geht offenbar hervor, dass diese sieben in der erwähnten Stelle aufgezählt werden, insofern sie in uns sind infolge göttlichen Einhauchens. „Einhauchen“ aber drückt aus eine gewisse Bewegung, die von außen herkommt. Denn es ist zu erwägen, dass im Menschen ein doppeltes, in Tätigkeit setzendes Princip sich findet: das eine ist innen, die Vernunft; das andere außen, Gott. (Vgl. Kap. 9, Art. 4. u. 6.; ebenso Aristoteles cap. 8. lib. 7. magn. moral.) Notwendig aber ist es, dass Alles, was in Bewegung gesetzt wird, im gebührenden Verhältnisse stehen muss zur bewegenden Kraft; und das ist eben die Vollkommenheit des Beweglichen als solchen: die Verfassung, durch welche es in ein gutes Verhältnis gesetzt wird, dass es gebührend bewegt werde von der geeigneten bewegenden Kraft. Je höher also die bewegende Kraft steht, desto notwendiger ist es, dass das Bewegliche durch eine vollendetere Verfassung dieser Kraft entsprechend gestaltet werde; wie wir sehen, dass ein Schüler schon mehr vorbereitet sein muss, um von einem höher stehenden Lehrer Belehrung zu empfangen wie von einem nicht so hoch stehenden. Nun vollenden die Tugenden den Menschen wohl, insoweit er geeignet ist, von der Vernunft aus in ihm zu dem hin, was er wirkt, in Tätigkeit gesetzt zu werden; sei dies ein Wirken was in ihm bleibt oder was auf das Äußere sich richtet. Sonach müssen dem Menschen höhere Vollendungen gegeben werden, auf dass er in der gehörigen Verfassung sei, um von Gott her in Bewegung gesetzt zu werden. Und diese Vollendungen nun nennt man Gaben, nicht nur weil sie von Gott eingegossen werden, sondern weil durch sie der Mensch in die rechte Verfassung kommt, dass er ohne weiteres beweglich wird von seiten der göttlichen Eingebung, des göttlichen Einhauchens her; wie es Isai. 50. heißt: „Der Herr hat mir das Ohr geöffnet; ich aber widerspreche nicht, zurück bin ich nicht gegangen.“ Und Aristoteles sagt ebenfalls (l. c.): „Denen, die da bewegt werden durch göttlichen Antrieb, ist es nicht ersprießlich, Rat zu nehmen gemäß der menschlichen Vernunft, dass sie dem inneren Antriebe folgen; denn dieser kommt von einem höheren Princip,“ als die menschliche Vernunft es ist. Und danach sagen manche, die Gaben vollendeten den Menschen zu höheren Tätigkeiten hin als dies sind die Tätigkeiten der Tugenden.

c) I. Derartige Gaben werden manchmal Tugenden genannt gemäß der gewöhnlichen Auffassung der Tugend. Durch sie tritt jedoch etwas hinzu zum gemeinsamen Wesen der Tugenden, insofern sie gewisse göttliche Kräfte sind, die den Menschen zu dem Zwecke vollenden dass er leicht beweglich sei mit Rücksicht auf Gott. Deshalb setzt auch Aristoteles (7 Ethic. 1.) über die gewöhnliche Tugend hinaus eine gewisse heroische oder göttliche Tugend an, der gemäß in Tätigkeit gesetzt werden „göttliche“, gottbegeisterte Männer. II. Die Laster stehen den Tugenden entgegen, insoweit sie gegen das von der Vernunft bemessene Gute sind. Insoweit die Laster gegen den göttlichen Antrieb sich richten, sind sie den Gaben entgegengesetzt. Denn das Gleiche ist entgegengesetzt Gott und der Vernunft, deren Licht ja sich von Gott ableitet. III. Diese Begriffsbestimmung wird gegeben gemäß der gewöhnlichen„ gemeinen Auffassung von der Tugend. Eigentlich müsste es heißen, um die Tugenden von den Gaben zu unterscheiden: „kraft deren man recht lebt“ entsprechend jener Geradheit des Lebens, wie sie durch die Regel der Vernunft gekennzeichnet wird. Und die Gabe müsste definiert werden, um sie von der eingegossenen Tugend zu unterscheiden „was von Gott gegeben wird mit Beziehung auf die bewegende Kraft, die von Ihm ausgeht und die den Menschen folgsam macht gegenüber dem göttlichen Antriebe.“ IV. „Weisheit“ als Tugend der Vernunft ist jene, die und insoweit sie vom Urteile der Vernunft ausgeht; „Weisheit“ als Gabe ist jene, die und insoweit sie wirkt vom göttlichen Antriebe aus.


** Zweiter Artikel. Die Gaben sind dem Menschen zum Heile notwendig.

a) Dies scheint nicht der Fall zu sein. Denn: I. Die Gaben ordnen zu einer Vollendung hin, welche über die gewöhnliche Vollendung der Tugenden hinausgeht. Eine solche Vollendung aber fällt unter den Rat, nicht unter das Gebot. Also sind sie nicht notwendig. II. Durch die theologischen Tugenden verhält sich jemand gut zu den göttlichen Dingen, durch die moralischen ist das nämliche der Fall rücksichtlich der menschlichen Dinge. Also bedarf es, um das Heil zu erlangen, keiner besonderen Gaben. III. Gregor (2. moral. 26.) sagt: „Der heilige Geist giebt Weisheit gegen die Thorheit, Verständnis gegen die stumpfe Gleichgültigkeit, die Gabe des Rates gegen die Übereilung, Stärke gegen die Furcht, Wissenschaft gegen die Unwissenheit, Gottergebenheit gegen die Herzenshärte, Demut gegen den Stolz.“ Dies Alles aber kann auch hinreichenderweise entfernt werden durch die Tugenden. 

Auf der anderen Seite scheint die Weisheit die höchste Gabe zu sein, die am tiefsten stehende die Furcht. Beides aber ist notwendig zum Heile, nach Sap. 7.: „Niemanden liebt Gott außer den, der mit der Weisheit zusammenwohnt“; und Ekkli. 1.: „Wer ohne Furcht ist, wird nicht gerechtfertigt werden können.“ Also sind auch die dazwischen liegenden Gaben notwendig.

b) Ich antworte, dass die Gaben gewisse Vollendungen des Menschen sind, vermittelst deren dieser dazu geeignet wird, dass er mit Bereitwilligkeit dem göttlichen Antriebe folge. Wo also der Antrieb seitens der Vernunft nicht genügt, da ist notwendig der des heiligen Geistes; und folgegemäß eine Gabe. Die menschliche Vernunft aber ist von seiten Gottes in doppelter Weise vollendet: 1. durch natürliche Vollendung, gemäß der Leuchte der natürlichen Vernunft; — 2. durch eine gewisse übernatürliche Vollendung, vermittelst der theologischen Tugenden. (Kap. 26, Art. 1.) Obgleich nun diese letztere Vollendung größer und umfangreicher ist wie die erste, so wird doch die natürliche Vollendung in einer mehr vollkommenen Weise besessen wie die übernatürliche; denn die erste wird voll und ganz besessen, die letztere nur mangelhaft, da wir unvollkommen Gott kennen und lieben. Offenbar aber ist es, dass jegliches Ding, welches eine Natur oder eine Eigenschaft oder eine Tugend in vollkommener Weise hat, von sich selbst aus gemäß derselben wirken kann, immer vorausgesetzt natürlich das Einwirken Gottes als erster Ursache, der in jeder Natur und innerhalb jeglichen Willens wirkt. Was aber eine Natur oder eine Eigenschaft oder eine Tugend in unvollkommener Weise besitzt, das kann nicht von sich aus wirken, sondern muss von außen her in Tätigkeit gesetzt werden. So kann die Sonne, welche vollkommen lichtvoll ist, von sich aus erleuchten; der Mond aber, in dem die Natur des Lichtes nur unvollkommen sich findet, leuchtet nur, insoweit er selber von außen her erleuchtet ist. Der Arzt auch, der vollkommen die Arzneikunde kennt, kann von sich aus wirken; sein Schüler aber, dessen Unterricht noch nicht vollendet worden, kann nicht von sich aus wirken außer wenn er vorher von seinem Lehrer über den vorliegenden Fall belehrt worden ist. So kann also auch der Mensch mit Rücksicht auf das, was dem menschlichen Urteile unterliegt, in Anbetracht des seiner Natur entsprechenden Zweckes, vermittelst des Urteiles der Vernunft genügend von sich aus wirken und wird es in diesem Falle ein Zeichen überfließender Güte sein, wenn er dazu von Gott durch speciellen Antrieb unterstützt wird, so dass selbst nach den Philosophen nicht wer auch immer erworbene moralische Tugenden hatte, damit heroische odcr gottbegeisterte Tugenden besaß. Mit Rücksicht aber auf den letzten, den übernatürlichen Zweck, zu dem hin die Vernunft bewegt, insofern sie in etwa und unvollkommen vermittelst der theologischen Tugenden herangebildet und geformt ist, genügt diese von der Vernunft ausgehende Bewegung nicht, wenn nicht damit verbunden ist der Antrieb und die Bewegung des heiligen Geistes nach Röm. 8.: „Die durch den Geist Gottes getrieben werden, diese sind Söhne Gottes… und Erben;“ und nach Ps. 142.: „Dein Geist wird mich hinabführen in das rechte Land;“ weil nämlich zur Erbschaft jenes Landes der Seligen niemand gelangen kann außer bewegt und geführt vom heiligen Geiste. Um also jenen Zweck zu erreichen, bedarf es der Gaben des heiligen Geistes.

c) I. Diese Gaben überragen den gewöhnlichen Stand der Tugenden nicht mit Rücksicht auf die Art der Werke, wie etwa die Räte den Geboten vorangehen; sondern mit Rücksicht auf die Art und Weise zu wirken, insofern der Mensch von einem höheren Princip aus in Tätigkeit gesetzt wird. II. Durch die moralischen und theologischen Tugenden wird der Mensch nicht in der Weise vollendet für den letzten Zweck, dass er nicht fortwährend bedürfte, in Tätigkeit gesetzt zu werden vermittelst eines höheren Antriebes des heiligen Geistes. III. Der menschlichen Vernunft ist nicht Alles bekannt und nicht Alles möglich, mag sie als vervollkommnet durch die natürlichen oder durch die theologischen Tugenden angesehen werden. Deshalb kann sie nicht mit Rücksicht auf Alles die „Thorheit“ u. s. w. zurückweisen. Jener aber, dessen Weisheit und Macht Alles Untertan ist, macht uns infolge der Bewegung, die von Ihm ausgeht, sicher gegen alle Gefahren, die aus der „Thorheit“, „Unwissen heit“ etc. sich ergeben. Und deshalb wird gesagt, die Gaben des heiligen Geistes, die da bewirken, dass wir gebührend folgen seinem Antriebe, werden gegen dergleichen Mängel und Gefahren gegeben.


** Dritter Artikel. Die Gaben des heiligen Geistes sind Zustände.

a). Das Gegenteil stützt sich auf folgende Gründe: I. Ein Zustand schließt Dauer in sich. Denn er ist eine „schwer verrückbare Eigenschaft.“ Den Gaben aber ist es eigen, dass sie nur in Christo ruhen nach Isai. 11. Und Joh. 1, 33. heißt es: „Er, über welchen du siehst den Geist herabsteigen und bleiben über Ihm; Er tauft im heiligen Geiste;“ wozu Gregor (2. moral. 27.) bemerkt: „In alle Gläubigen kommt der heilige Geist, im Mittler allein bleibt Er stets in besonderer Weise.“ II. Die Gaben des heiligen Geistes vollenden den Menschen, insoweit er getrieben wird vom heiligen Geiste. Da verhält sich aber der Mensch wie ein Werkzeug. Insofern nun nicht dem Werkzeuge es zukommt, durch einen Zustand vollendet zu werden, sondern dem Haupteinwirkenden, ist die Gabe des heiligen Geistes kein Zustand im Menschen. III. Wie die Gaben des heiligen Geistes, so kommt auch die Gabe der Prophetie vom Einhauchen oder Einsprechen Gottes. Diese aber ist kein Zustand, wie Gregor (1. hom. in Ezech.) sagt, da der prophetische Geist dem Propheten nicht immer gegenwärtig ist. 

Auf der anderen Seite sagt der Herr zu seinen Aposteln und Jüngern (Joh. 14.): „Zu euch wird Er (der heilige Geist) kommen und bei euch wird Er bleiben und in euch wird Er sein.“ Der heilige Geist aber ist nicht im Menschen ohne seine Gaben. Also bleiben diese im Menschen und sind somit Zustände.

b) Ich antworte; durch die Gaben des heiligen Geistes wird der Mensch in die rechte Verfassung gesetzt, dass er dem Antriebe des heiligen Geistes folge. Offenbar nun vollenden die moralischen Tugenden den begehrenden Teil, insoweit derselbe von Natur geeignet ist, von der Vernunft aus in Bewegung gesetzt zu werden. So verhalten sich also die Gaben des heiligen Geistes zu dem Menschen, wie die Tugenden zum begehrenden Teile. Letztere aber sind Zustände. Also sind es auch die Gaben. Wie jene machen, dass man bereitwillig der Vernunft gehorcht, so diese, dass man gern dem heiligen Geiste gehorcht.

c) I. Gregor sagt gleich darauf (cap. 28.): „Rücksichtlich jener Gaben, die notwendig sind zum Heile, bleibt der heilige Geist in allen Auserwählten; nicht aber mit Rücksicht auf alle Gaben.“ Die sieben Gaben aber sind notwendig zum Heile. II. Jener Einwurf spricht von einem Werkzeuge, das nur getrieben wird, nicht aber selber treibt und wirkt. Der Mensch jedoch empfängt so das Einwirken des heiligen Geistes, dass er auch selber wirkt kraft seines freien Willens. Also bedarf er eines Zustandes. III. Die Prophetie ist nicht notwendig zum Heile, sondern dient zur Offenbarung des Geistes.


** Vierter Artikel. Die sieben Gaben werden zukömmlicherweise aufgezahlt.

a) Dies scheint nicht. Denn: I. Vier Gaben beziehen sich da auf die Vernunft, nämlich Weisheit, Wissenschaft, Verständnis, Rat, der mit zur Klugheit gehört. Nichts aber wird gesetzt mit Bezug auf die Kunst, die fünfte Tugend der Ver nunft. Ebenso steht da Gottergebenheit, die zur Gerechtigkeit gehört, und Stärke; nichts aber, was sich auf die Mäßigkeit bezöge. Also genügen die sieben Gaben nicht. II. Die Gottergebenheit oder Frömmigkeit ist ein Teil der Gerechtigkeit. Mit Rücksicht auf die Stärke aber wird diese selbst gesetzt und nicht ein Teil derselben oder eine Untergattung. Also musste auch Gerechtigkeit selber und nicht ein Teil derselben gesetzt werden. III. Mit Bezug auf die theologischen Tugenden stehen gar keine Gaben verzeichnet. Gerade aber insoweit der Mensch von Gott bewegt wird, bestehen Gaben. Also musste man mit Rücksicht auf die theologischen Tugenden vorzugsweise Gaben ansetzen. IV. Wie Gott gefürchtet wird, so wird Er auch geliebt und man hofft auf Ihn und ergötzt sich an Ihm. Also musste nicht nur die Furcht als Gabe gesetzt werden, sondern auch Liebe, Hoffnung und Freude. V. Zum Verständnisse wird die Weisheit gesetzt als leitende Richtschnur, zur Stärke der Rat, zur Gottergebenheit die Wissenschaft. Also musste auch zur Furcht eine leitende Richtschnur hinzugefügt werden. 

Auf der anderen Seite steht die Autorität der Schrift.

b) Ich antworte; da die Gaben dazu dienen, dass der Mensch bereitwilliger dem Antriebe des heiligen Geistes folge, wie die Tugenden dazu sind, dass er bereitwilliger der Vernunft gehorche, so sind in allen jenen Vermögen, welche Principien sein können für menschliche Tätigkeiten, nämlich in der Vernunft und im Begehrvermögen, ebenso Gaben, wie da Tugenden sich finden. Die Vernunft nun teilt sich in eine beschauliche und in eine auf das Tätigsein gerichtete. Bei beiden wird die Erfassung der Wahrheit berücksichtigt, die dazu gehört, um die Wahrheit zu finden und nach ihr zu urteilen. Mit Rücksicht auf die Erfassung der Wahrheit also wird die beschauliche (spekulative) Vernunft vollendet durch die Gabe des Verständnisses; die auf das Tätigsein nach außen hin gerichtete (praktische) Vernunft durch die des Rates. Für das Urteilen wird die erstere Vernunft vollendet durch die Weisheit, die zweitgenannte durch die Wissenschaft. Die begehrende Kraft nun wird, soweit es die Beziehungen zu anderen angeht, vollendet durch die Gottergebenheit (Frömmigkeit); soweit es die Beziehung zu sich selber angeht, durch die Stärke, nämlich gegenüber den Todesgefahren; und mit Bezug auf die Begierlichkeiten nach ungeordneten Ergötzungen besteht da die Gabe der Furcht, nach Prov. 15.: „Jeglicher entfernt sich vom Übel aus Furcht vor Gott;“ und Ps. 118.: „Durchbohre mit Furcht mein Fleisch; vor Deinen Ratschlüssen hatte ich Furcht.“ Und so erstrecken sich diese Gaben auf Alles, worauf die Tugenden sich richten.

c) I. Die Gaben des heiligen Geistes vollenden den Menschen, dass er recht lebe; damit hat aber die Kunst als rechte Richtschnur des äußeren Werkes nichts zu thun. Es kann auch zudem gesagt werden, beim Eingießen der heiligen Gaben gehöre die „Kunst“ dem heiligen Geiste selber an als dem Haupteinwirkenden; nicht aber den Menschen, die nur Werkzeuge sind und von Ihm bewegt werden. Der Tugend der Mäßigkeit entspricht die Furcht, dass jemand nämlich von den schlechten Ergötzungen sich entferne aus Furcht vor Gott und nicht bloß auf Grund des von der Vernunft gekennzeichneten Guten. II. Der Name „Gerechtigkeit“ wird beigelegt von der Geradheit der Vernunft aus. Und da kommt mehr der Charakter der Tugend in Betracht wie der einer „Gabe“. Der Name „Gottergebenheit“ oder Frömmigkeit schließt ein die Ehrfurcht vor dem Vater aller Dinge, vor Gott und sonach dann auch vor dem irdischen Vater und dem Vaterlande. Deshalb nennt man auch die Ehren, die man Gott erweist, Gottesdienst. Zukömmlicherweise also wird die Gottergebenheit, auf Grund deren man aus Ehrfurcht vor Gott allen Gutes erweist, als „Gabe“ bezeichnet. III. Dass der Mensch vom heiligen Geiste in Tätigkeit gesetzt werde, dies setzt voraus, dass er in irgend einer Weise mit dem heiligen Geiste eins sei; wie das Werkzeug vom Künstler nur bewegt ist, insoweit es von ihm berührt wird oder sonstwie mit ihm verbunden ist. Die erste Einigung des Menschen mit Gott nun vollzieht sich vermittelst der theologischen Tugenden. Dieselben also werden für die Gaben vorausgesetzt, wie gewissermaßen die Wurzeln derselben. Die Gaben setzen somit das von den theologischen Tugenden Gewirkte nur fort. IV. Liebe, Hoffnung, Freude haben zum Gegenstande das Gute. Da nun das höchste Gut Gott ist, so werden diese Namen übertragen auf die theologischen Tugenden, kraft deren die Seele mit Gott verbunden wird. Der Gegenstand der Furcht aber ist das Schlechte, was Gott in keiner Weise zukommt. Also schließt sie nicht die Verbindung mit Gott ein, sondern vielmehr eine Entfernung von gewissen Dingen auf Grund der Ehrfurcht vor Gott. Und deshalb ist die Furcht nicht der Name einer theologischen Tugend, wohl aber einer „Gabe“; denn eine solche „Gabe“ zieht mit höherer Gewalt vom Bösen ab wie die moralische Tugend. V. Durch die Weisheit wird geleitet die Vernunft und die Hinneigung des Menschen; und deshalb entsprechen der Weisheit zwei Gaben als von ihr zu leitende; — nämlich von seiten der Vernunft das Verständnis und von seiten der Hinneigung die Furcht. Denn der Grund, Gott zu fürchten, ist vor allem die Betrachtung der göttlichen hocherhabenen Majestät und diese wird betrachtet von der Weisheit. 


** Fünfter Artikel. Die Gaben des heiligen Geistes sind miteinander verbunden.

a) Dies ist zuerst: I. Dem Apostel zuwider (1. Kor. 12.), der da sagt: „Dem einen wird vom Geiste verliehen die Rede der Weisheit, dem anderen die Rede der Wissenschaft durch den nämlichen Geist.“ Weisheit und Wissenschaft aber sind Gaben des heiligen Geistes. Also sind dieselben nicht in derselben Person verbunden. II. Augustin (14. de Trin. 1.), der da schreibt: „Von der Wissenschaft sind nicht viele angefüllt, obgleich sie vollen Glauben haben.“ Den Glauben aber begleitet zum mindesten immer die Gabe der Furcht. Also sind nicht alle Gaben in ein und demselben miteinander verbunden. III. Gregor (1. moral.), der da sagt: „Die Weisheit ist geringer, wenn sie des Verständnisses ermangelt; und sehr unnütz ist das Verständnis, wenn es nicht von der Weisheit her seinen Bestand ableitet. Wertlos ist der Rat, wo Stärke fehlt; und zerrüttet ist im höchsten Grade die Stärke, wenn sie nicht ihre Stütze im Rate hat. Die Wissenschaft ist nichts, wenn sie den Nutzen der Gottergebenheit nicht in sich schließt; und sehr unnütz ist die Gottergebenheit, wenn sie der Unterscheidungsgabe, die vom Wissen kommt, ermangelt. Und die Furcht selber steht ebenso nicht auf zum guten Werke, wenn sie nicht alle diese Tugenden hat.“ Danach ergiebt sich, dass eine Gabe ohne die andere besessen werden kann. 

Auf der anderen Seite schickt Gregor diesen Worten vorher: „Das müssen wir bei den Gastmählern der Söhne erforschen, dass sie nämlich sich gegenseitig Speise bieten.“ Unter den sieben Söhnen Jobs aber versteht Gregor die sieben Gaben des heiligen Geistes. Also sind sie alle insgesamt immer verbunden.

b) Ich antworte, die Wahrheit könne hier aus dem vorher Gesagten festgestellt werden. Denn wie die moralischen Tugenden den Menschen vollenden mit Beziehung auf die Richtschnur der Vernunft, so die Gaben mit Beziehung auf den heiligen Geist, der da bewegt. Der heilige Geist aber wohnt in uns durch die heilige Liebe nach Röm. 5.: „Die Liebe Gottes ist ausgegossen in unsere Herzen durch den heiligen Geist, der uns verliehen worden;“ ähnlich wie die Vernnnft vollendet wird durch die Klugheit. Wie also alle moralischen Tugenden miteinander verbunden werden in der Klugheit, so haben die Gaben des heiligen Geistes ihre gegenseitige Verbindung in der heiligen Liebe. Wer somit die heilige Liebe hat, der hat alle Gaben des heiligen Geistes; und keine dieser Gaben kann besessen werden ohne die heilige Liebe.

c) I. Die Weisheit und Wissenschaft sind nicht nur Gaben, sondern auch Gnaden, die zum Besten anderer gegeben werden (gratis datae); und danach überfließen sie in dem, der sie hat, so dass dieser auch andere unterrichten kann. Und so erwähnt sie der Apostel, weshalb er treffend sagt: „Die Rede der Weisheit etc.“ Hier aber werden sie als „Gaben“ genommen, wonach jemand vorbereitet wird, dem Antriebe des heiligen Geistes zu folgen in der Kenntnis der göttlichen und menschlichen Dinge. Und so sind beide Gaben in allen, wo die Liebe wohnt. II. Augustin erklärt diese Stelle des Apostels; also spricht er in derselben Weise von der „Wissenschaft“. Deshalb fügt er hinzu: „Etwas Anderes nämlich ist es, nur zu wissen, was der Mensch glauben muss, um zum ewigen Leben zu gelangen; und etwas Anderes, zu wissen, wie diese Erkenntnis selber den Gläubigen nützt und wie sie gegen die Gottlosen verteidigt wird; dieses letztere Wissen nun meint hier der Apostel.“ III. Gregor will gerade beweisen, dass eine Gabe ohne die andere nichts nützt; wie auch eine Kardinaltugend ohne die andere nicht nützlich ist. (Vgl. oben.) Deshalb schickt er vorher: „Sehr wankt jede von diesen Tugenden, wenn sie nicht durch die andere gestützt wird.“ 


** Sechster Artikel. Die Gaben des heiligen Geistes bleiben im anderen Leben.

a) Dagegen spricht: I. Gregor (2. moral. 26.) mit den'Worten: „Der heilige Geist erzieht unseren Geist gegenüber allen Versuchungen durch die sieben Gaben.“ Im anderen Leben aber giebt es keine Versuchungen mehr: „Sie werden nicht mehr schaden oder töten auf meinem heiligen Berge,“ sagt Isaias 11. II. Die Gaben des heiligen Geistes sind Zustände. Diese aber bleiben nicht, wo sie ihre Tätigkeiten nicht mehr entwickeln können; sie wären ja sonst vergeblich da. Die Tätigkeiten mancher Gaben können nun nicht mehr im Himmel sich vollziehen; wie Gregor (1. moral. 15.) sagt: „Das Verständnis macht, dass man das Gehörte durchdringt; der Rat behütet vor Übereilung; die Stärke läßt nicht die Feinde fürchten; und die Gottergebenheit füllt das heilige Verlangen im Herzen an mit den Werken der Barmherzigkeit.“ Alles dies aber hat im Himmel keine Stelle mehr. III. Manche Gaben vollenden den Menschen für das beschauliche und manche für das tätig wirksame Leben. Letzteres aber hört mit dem Tode auf. Also sind diese Gaben fortan unnütz. Nicht alle Gaben bleiben somit in der Heimat. 

Auf der anderen Seite sagt Ambrosius (I. de Spir. S. 20.): „Jene himmlische Stadt Jerusalem wird durch kein Hindurchfließen eines irdischen Stromes abgewaschen; sondern der heilige Geist, der vom Lebensquell ausgeht, den wir hier nur mangelhaft, wie im Vorübergehen genießen, wird da in jenen himmlischen Kräften reichlicher überfluten, in glühender Liebe ausgehend, die sieben geistigen Tugenden.“

b) Ich antworte; von den Gaben können wir in doppelter Weise sprechen, einmal mit Rücksicht auf ihr inneres Wesen; und so werden sie in der Heimat in höchster Vollendung sein, wie Ambrosius eben sagte. Der Grund davon ist, dass die Gaben den menschlichen Geist vollenden, damit er der vom heiligen Geiste ausgehenden bewegenden Kraft bereitwillig folge; das aber wird in vorzüglicher Weise in der Heimat stattfinden, wann „Gott sein wird Alles in Allem,“ nach 1 Kor. 15., und wann der Mensch durchaus Gott unterworfen sein wird. Dann können die Gaben betrachtet werden mit Rücksicht auf die Materie oder den Gegenstand, worauf sie sich richten; und so richten sie jetzt ihre Tätigkeit auf etwas, worauf sie dieselbe dort nicht richten werden. Und danach bleiben die Gaben nicht in der Heimat; wie das auch mit den Kardinaltugenden der Fall sein wird. (Kap. 67, Art. 1.)

c) I. Gregor spricht da von den Gaben, wie sie dem gegenwärtigen Leben zukommen. Im Himmel werden wir durch die Gaben durchaus im Guten vollendet werden. II. Gregor setzt in die einzelnen Gaben immer zugleich etwas, was mit diesem Leben vorübergeht: „Die Weisheit erquickt den vernünftigen Geist mit der Hoffnung auf das Ewige und mit der Gewißheit,“ wovon die Gewißheit bleibt, die Hoffnung vorübergeht: „Das Verständnis dringt durch das Gehörte durch, erquickt das Herz und erleuchtet seine Finsternisse.“ Davon fällt das Gehör fort: „denn nicht mehr wird da der Mann seinen L. Mitbruder belehren“ (Jerem. 31.); die Erleuchtung des Verstandes bleibt. Der Rat behütet vor Übereilung,“ was hier im Leben nur notwendig ist „und füllt die Seele an mit dem Lichte der Vernunft,“ was dort notwendig erscheint. „Die Stärke fürchtet keine Gegner,“ was von hier gilt, „und speist den Geist mit froher Zuversicht,“ was für die Zukunft Geltung hat. „Die Wissenschaft überwindet das Fasten der Unkenntnis,“ das gilt nur für hier; was er aber hinzufügt, „im Bauche des Geistes,“ das kann figürlich verstanden werden von der Fülle des Wissens, was im Himmel sein wird. „Die Gottergebenheit füllt an das Innere des Herzens mit Werken der Barmherzigkeit,“ was nach den Worten zwar nur für das gegenwärtige Leben dient; jedoch die innigste Hinneigung zum Nächsten, die durch das „Innere, viscera, des Herzens“ angedeutet wird, bleibt in der Ewigkeit, wo die Gottergebenheit nicht mehr helfen, aber beglückwünschen wird den Nächsten. „Die Furcht drückt zusammen den Geist, dass er nicht anmaßend werde in seinem Stolze auf Grund des gegenwärtigen Glückes“ und „stärkt den Geist mit der Speise der Hoffnung,“ was Letzteres rücksichtlich der Hoffnung auf die Gegenwart geht, jedoch mit Rücksicht auf die Kräftigung auch auf die Zukunft gehen kann, wo man das Gehoffte erreicht hat. III. Dies gilt vom Gegenstande oder der Materie der Gaben hier auf Erden. 


** Siebenter Artikel. Die würde der Gaben entspricht der Aufeinanderfolge in der Aufzählung des Propheten.

a.) Dies scheint nicht der Fall zu sein. Denn: I. Die hauptsächliche Gabe scheint das zu betreffen, was Gott am meisten vom Menschen verlangt. Dies ist aber die Furcht nach Deut. 10.: „Und jetzt, Israel, was fordert Gott von dir Anderes als dass du Ihn fürchtest, den Herrn, deinen Gott?“ Und Malach. 1.: „Wenn ich der Herr bin, wo ist die Furcht vor mir?“ Also scheint die letzte Gabe, die Furcht, in der Würde die hauptsächlichste, die erste, zu sein. II. Die Gottergebenheit scheint gewissermaßen ein allumfassendes Gut zu sein nach 1. Trin. 4.: „Die Gottergebenheit oder Frömmigkeit ist zu Allem nütze.“ Ein allgemeines, d. i. allumfassendes Gut aber ist vorzuziehen einzelnen, besonderen Gütern. Also ist die Frömmigkeit, die pietas, die hauptsächlichste Gabe; und doch steht sie da nur an vorletzter Stelle. III. Die Wissenschaft vollendet das Urteil der Vernunft, der Rat gehört dem Untersuchen seitens der Vernunft an. Das Urteil aber steht höher als das Untersuchen. Also müsste die Wissenschaft vor dem Rate kommen. IV. Die Stärke gehört zum Begehren, die Wissenschaft zur Vernunft. Letztere aber steht an Würde höher wie die begehrende Kraft. Also dürfte nicht die Stärke vor der Wissenschaft aufgezählt werden. Sonach entspricht jene Aufeinanderfolge bei Isaias nicht der Würde dieser Gaben. 

Auf der anderen Seite sagt Augustin (I. de serm. Dom. in monte 4.): „Die siebengestaltete Tätigkeit des heiligen Geistes, von der Isaias spricht, scheint mir diesen Stufen (der acht Seligkeiten) zu entsprechen. Isaias fängt an von den würdevolleren; hier aber ist der Beginn bei den niedrigeren.“

b) Ich antworte; die Würde der einzelnen Gaben kann erwogen werden entweder schlechthin d. h. mit Rücksicht auf die ihnen eigene Tätigkeit oder nach einer gewissen Seite hin, nämlich mit Rücksicht auf die Art der Materie, auf die sie gerichtet sind. Die erste Betrachtung ist die, welche wir schon bei den Tugenden gemacht haben; insoweit nämlich die Gaben den Menschen vollenden für all jene Tätigkeit der Vermögen, für welche diese selben Vermögen bereits von seiten der Tugenden einigermaßen vollendet werden. Wie also die Tugenden in der Vernunft vorgezogen werden den moralischen Tugenden, und in diesen Tugenden die beschaulichen den auf das tätige Leben gerichteten, wie die Weisheit, das Verständnis und die Wissenschaft der Klugheit und der Kunst; — so werden bei den Gaben vorgezogen die Weisheit und das Verständnis, die Wissenschaft und der Rat der Gottergebenheit oder Frömmigkeit, der Stärke und der Furcht; und in diesen wird die Gottergebenheit vorgezogen der Stärke und diese der Furcht; wie auch die Gerechtigkeit voransteht der Stärke und diese der Mäßigkeit. Kommt es aber auf die Materie dieser Gaben an, so wird die Stärke und der Rat vorgezogen der Wissenschaft und der Gottergebenheit, weil die Stärke und der Rat sich auf das mit Schwierigkeiten Verbundene beziehen, die Gottergebenheit und die Wissenschaft aber auf das Gewöhnliche gerichtet sind. So also entspricht die Würde der Gaben ihrer Aufeinanderfolge beim Propheten; zum Teil schlechthin und ohne Ausnahme, wie die Weisheit und das Verständnis allen vorgezogen werden, zum Teil aber gemäß der vorliegenden Materie, wonach der Rat und die Stärke vorgezogen werden der Wissenschaft und der Gottergebenheit.

c) I. Die Furcht wird erfordert wie ein Beginn der durch die Gaben veranlaßten Vollendung, weil „der Anfang der Weisheit die Furcht Gottes ist;“ nicht weil sie würdevoller wäre. Denn zuerst entfernt man sich nach der Ordnung des Entstehens oder der Zeugung vom Schlechten, was nach Prov. 16. durch die Furcht geschieht, ehe man das Gute thut, was den anderen Gaben gedankt wird. II. Der Apostel vergleicht da die Gottergebenheit oder Frömmigkeit nicht mit den anderen Gaben, sondern mit der alleinigen körperlichen Übung, von der er vorher sagt, sie sei in etwa nützlich. III. Mit Rücksicht auf das Urteilen wird die Wissenschaft dem Rate vorgezogen; mit Rücksicht aber auf den Gegenstand oder die Materie der Rat dem Wissen. Denn Ratschlagen findet nur statt bei schwierigen Sachen, während Urteilen überall statthat. IV. Die „leitenden“ Gaben, die in der Vernunft sind, stehen freilich als würdevoller da wie jene Gaben, denen die Ausführung obliegt; wenn sie nämlich mit ihrer Beziehung zur Tätigkeit in Betracht gezogen werden, insoweit sie von dem Vermögen ausgehen, da die Vernunft den begehrenden Teil überragt, wie die Regel das Geregelte. Jedoch mit Rücksicht auf den Gegenstand oder die vorliegende Materie wird zur Stärke der Rat hinzugefügt und zur Gottergebenheit das Wissen; denn Rat und Stärke richten sich auf Schwieriges, Wissenschaft und Gottergebenheit auf Gewöhnliches. 


** Achter Artikel. Die Gaben stehen höher wie die Tugenden.

a) Das Gegenteil scheint zu sagen: I. Augustin (15. de Trin. 18.): „Nichts steht höher wie die Gabe der heiligen Liebe; sie allein scheidet zwischen den Söhnen des ewigen Reiches und den Söhnen der ewigen Verdammnis. Andere Geschenke noch teilt aus der heilige Geist; keines jedoch nützt ohne die heilige Liebe.“ Diese aber ist eine Tugend. II. Gregor der Große (2. moral. 26.): „Die Gabe des heiligen Geistes bildet vor allem Anderen in dem ihr unterworfenen Geiste heran die Gerechtigkeit, die Klugheit, die Stärke und die Mäßigkeit; und so schmückt sie den nämlichen Geist allsobald mit den sieben Tugenden,“ d. h. mit den Gaben, so dass „gegen die Thorheit die Weisheit, gegen die stumpfe Gleichgültigkeit das Verständnis, gegen die Übereilung der Rat, gegen die Furcht die Stärke, gegen die Unwissenheit die Wissenschaft, gegen die Herzenshärte die Gottergebenheit, gegen den Hochmut die Furcht Er giebt.“ Also stehen die Tugenden im Range höher als die Gaben; denn was seiner Natur nach früher ist, scheint wichtiger zu sein. III. Nochmals Gregor (1. moral. 18.): „Unser Gebet opfern wir auf, damit die Weisheit nicht das Herz erhebe; damit das Verständnis, wenn es gründlicher nachforscht, nicht irre; damit der Rat, wenn er sich vervielfacht, nicht verwirre; die Stärke, während sie Vertrauen einflößt, nicht in den Abgrund stürze; die Wissenschaft nicht aufblähe; die Gottergebenheit, während sie unter das, was strenges Recht wäre, hinabsteigt, nicht sich krümme; da mit die Furcht, wenn sie mehr als notwendig zittert, nicht in die Grube der Verzweiflung falle.“ Also kann man die Gaben schlecht gebrauchen, was bei den Tugenden nicht der Fall ist, „welche niemand“ nach Augustin (2. de lib. arb. 19.) „schlecht gebraucht.“ 

Auf der anderen Seite werden die Gaben den Tugenden zum Beistande gegeben gegen einzelne Mängel und scheinen so zu vollenden, was die Tugenden nicht fertig bringen können. Also stehen sie höher wie die Tugenden.

b) Ich antworte, es gebe drei Arten Tugenden: die theologischen, die moralischen und die in der Vernunft. Durch die theologischen Tugenden wird der Geist mit Gott verbunden; durch die in der Vernunft diese, nämlich die Vernunft, vollendet; und die moralischen Tugenden machen, dass das Begehren gehorche der Vernunft. Durch die Gaben des heiligen Geistes aber werden alle Kräfte der Seele in die richtige Verfassung gesetzt, dass sie Gottes bewegender Kraft untergeben sind. Somit stehen die Gaben zu den theologischen Tugenden im selben Verhältnisse wie die moralischen Tugenden zu denen in der Vernunft. Und wie die Tugenden in der Vernunft voranstehen den moralischen und die regelnde Richtschnur für dieselben sind, so stehen die theologischen Tugenden, durch die der Geist des Menschen mit dem heiligen Geiste geeint wird, voran den Gaben. Deshalb sagt Gregor (1. moral. 12.): „Zur Vollendung der Zehnzahl kommen die sieben Söhne nicht, wenn nicht Alles was sie thun in Glaube, Hoffnung und Liebe geschieht.“ Weil jedoch die Gaben dem Geiste die Vollendung geben mit Rücksicht auf den bewegenden heiligen Geist; so stehen sie voran allen anderen Tugenden, welche nur die menschliche Vernunft vollenden oder die anderen Kräfte, insoweit diese in Beziehung stehen zur Vernunft. In Beziehung aber auf eine höher stehende bewegende Kraft bedarf das Bewegliche einer größeren Vollkommenheit, um zu dieser Kraft in die richtige Verfassung zu treten.

c) I. Die heilige Liebe ist eine theologische Tugend und steht demnach höher wie die Gaben. II. Es ist etwas früher einmal in der Ordnung der Vollkommenheit und Würde, wie die Liebe Gottes früher ist als die des Nächsten; und so sind die Gaben früher wie die Tugenden der Vernunft und die moralischen, sie stehen aber den theologischen Tugenden nach; — dann in der Ordnung des Entstehens oder Erzeugens, wie die Liebe des Nächsten rücksichtlich der Tätigkeit vorher kommt als der Akt der Liebe Gottes; und so sind die moralischen Tugenden und die in der Vernunft früher wie die Gaben, denn wenn der Mensch sich gut verhält zur eigenen Vernunftregel, so kommt er dadurch in die Verfassung, dass er sich auch mit Bezug auf Gott gut verhält. III. Die Weisheit, das Verständnis u. dgl. sind Gaben des heiligen Geistes, insofern sie von der heiligen Liebe ihre Form und Vollendung erhalten, die da „nicht schlecht handelt.“ (1. Kor. 15.) Der Weisheit etc. also bedient niemand sich schlecht, insoweit sie Gaben des heiligen Geistes sind. Damit sie aber von der Vollendung der Liebe nicht sich entfernen, steht die eine der anderen bei. Und das will Gregor sagen. 


* II-II, Q. 8 - Gabe der Einsicht oder des Verständnis (intellectus)

** Erster Artikel. Das Verständnis ist eine Gabe des heiligen Geistes.

a) Das Gegenteil scheint festzustehen. Denn: I. Was vom heiligen Geiste als Gnadengabe kommt, das ist unterschieden vom Natürlichen. Das Verständnis aber ist ein Zustand, welcher mit der Natur der vernünftigen Seele gegeben ist. Also ist es keine Gabe des heiligen Geistes. II. Die göttlichen Gaben werden den Kreaturen mitgeteilt gemäß deren Verhältnissen und Seinsbedingungen, nach Dionysius (de div. nom. 4.). Die Art und Weise der menschlichen Natur aber ist es, dass sie nicht einfach und schlechthin die Wahrheit auffaßt (was zum Wesen des Verständnisses gehört), sondern nach und nach zu deren Kenntnis gelangt, indem sie vom Einen auf das Andere schließt (de div. nom. 7.). Also die Kenntnis Gottes, wie sie den Menschen verliehen wird, muss vielmehr die Gabe des schließenden Verstandes heißen wie die des Verständnisses. III. Verständnis heißt Verstehen; keine Gabe aber wird einfach Wollen genannt. 

Auf der anderen Seite heißt es Isai. 11.: „Es wird ruhen auf Ihm der Geist des Herrn, der Geist der Weisheit und des Verständnisses.“

b) Ich antworte, der Name „Verständnis“ bezeichne eine gewisse bis ins Innere dringende Kenntnis, vermöge deren man imstande ist, das Äußere zu leiten, „vorzustehen.“ Nun giebt es manches Sein, was im Innern eines Dinges verborgen ist, wozu der Sinn nicht vordringt. Denn unter den äußeren Eigenschaften, die man mit den Sinnen wahrnehmen kann, ist verborgen die Substanz oder die Natur des Dinges; unter den Worten ist verborgen ihre Bedeutung; unter Zeichen und Figuren das Bezeichnete; in den Ursachen ist verborgen die Wirkung. Mit Rücksicht auf dies Alles spricht man von „Verständnis“. Da nun die Kenntnis des Menschen vom Sinne, also gleichsam vom Äußerlichen beginnt, ist es offenbar, dass sie desto mehr ins Innere vordringen wird, je stärker das Licht der Vernunft durchleuchtet. Das natürliche Licht der Vernunft aber ist begrenzt und beschränkt. Der Mensch bedarf also eines übernatürlichen Lichtes, um darüber hinaus zu erkennen das, was er mit dem Lichte seiner natürlichen Vernunft nicht zu erkennen vermag. Und dieses übernatürliche Licht nennt man die Gabe des Verständnisses.

c) 1. Kraft des Lichtes des natürlichen Verständnisses werden nur die Allem gemeinsamen Grundprincipien verstanden, welche auf Grund der Natur bekannt sind. Weil aber der Mensch noch darüber hinaus hingeordnet ist zur übernatürlichen Seligkeit, so bedarf er eines weiteren Lichtes, um Höheres zu erkennen; und dieses Licht ist die Gabe des Verständnisses. II. Immerdar hat das Schließen der Vernunft vom Einen auf das Andere seinen Beginn in einem Verständnisse und mündet wieder in das, was man einfach versteht. Denn wir fangen an, zu schließen mit dem, was wir verstehen; und wir hören auf, wenn wir verstehen, was uns bis dahin unbekannt war. Die Gabe der Gnade nun geht nicht aus vom Lichte der Natur, sondern wird als dessen Vollendung hinzugefügt. Also heißt auch dieses hinzugefügte Licht mit Recht nicht so sehr „schließende Verstandeskraft“ wie „Verständnis“ oder Einsicht. Denn so verhält sich das übernatürliche hinzugefügte Licht zu dem, was übernatürlicherweise gekannt wird; wie sich verhält das natürliche Licht zu dem, was wir in erster Linie, im Beginne, erkennen. III. Das „Wollen“ bezeichnet einfach die Bewegung des Begehrens ohne irgendwelche weitere Bestimmung, die einen gewissen Vorzug in sich schlösse. „Verstehen“ aber will besagen ein durchdringendes, in die Tiefe gehendes Erkennen. Deshalb giebt es wohl eine übernatürliche Gabe, die „Verständnis“ genannt wird; keine aber, die „Wollen“ heißt.


** Zweiter Artikel. Die Gabe des Verständnisses ist zugleich mit dem Glauben.

a) Dementgegen scheint zu sein: I. Augustin (83 Qq. 14.): „Was verstanden wird,“ sagt er, „das wird durch das Begreifen des verstehenden eingeschlossen.“ Was aber geglaubt wird, das wird nicht begriffen, nach Philipp. 3.: „Nicht als ob ich bereits begriffen hätte oder schon vollkommen wäre.“ Also ist „Glauben“ nicht vereinbar mit „Verstehen“. II. Was verstanden wird, das wird von der Vernunft geschaut. Der Glaube aber geht auf das „Nichterscheinende“. III. Das Verständnis genießt höhere Gewißheit wie das Wissen. Wissen und Glauben aber können nicht in ein und demselben sein; also noch weniger Verstehen und Glauben. 

Auf der anderen Seite sagt Gregor (I. mor. 15.): „Das Verständnis erleuchtet die Vernunft mit dem, was gehört worden ist.“ Wer aber Glauben hat, kann im Geiste erleuchtet sein mit Rücksicht auf das Gehörte; weshalb es von den Schülern des Herrn (Luk. ult.) heißt: „Der Herr öffnete seinen Jüngern den Sinn, dass sie verständen die Schrift.“ Also kann das Verständnis zusammen sein mit dem Glauben.

b) Ich antworte, man müsse hier unterscheiden: 1. von seiten des Glaubens; 2. von seiten des Verständnisses. Von seiten des Glaubens ist nämlich das Eine an und für sich und direkt Gegenstand des Glaubens, was den menschlichen Geist durchaus überragt, wie dass Gott dreieinig, dass der Sohn Gottes Mensch geworden sei; — Anderes ist Gegenstand des Glaubens an zweiter Stelle, weil es zu diesem irgendwie Beziehung hat, wie Alles was in der Schrift enthalten ist. Von seiten des Verständnisses aber können wir Manches vollkommen auffassen, wie Jenes, dessen Wesen wir auffassen und die Wahrheit selber des ausgesprochenen Satzes, soweit er eben nur ein Satz ist; — und nach dieser Seite hin können wir nicht in diesem Wesen verstehen, was an und für sich, direkt, Gegenstand des Glaubens ist; wohl aber Anderes, was zum Glauben Beziehung hat. was also an zweiter Stelle Gegenstand des Glaubens ist. Dann wird etwas in unvollkommener Weise verstanden, wann nämlich wohl nicht das Wesen einer Sache oder die Wahrheit selber eines Satzes aufgefaßt wird, sondern nur dies, dass das, was nach außen hin erscheint, der Wahrheit nicht widerstreitet; insoweit der Mensch also dies versteht, auf Grund dessen, was äußerlich erscheint, sei nicht vom Glauben abzuweichen; und nach dieser Seite hin kann man hier auf Erden thatsächlich verstehen auch das, was an und für sich Gegenstand des Glaubens ist.

c) Die ersten drei Einwürfe gehen davon aus, dass man vollkommen versteht, was bei dem, was an sich Gegenstand des Glaubens ist, nicht statthat; der letztgenannte Grund betrifft das, was zum Glauben Beziehung hat.


** Dritter Artikel. Die Gabe des Verständnisses ist eine beschauliche und zugleich auf das Tätigsein gerichtete.

a) Diese Gabe ist eine rein beschauliche. Denn: I. „Das Verständnis durchdringt das Höhere,“ sagt Gregor l. c. Das Tätigsein aber berücksichtigt das Niedrigere, nämlich Einzelverhältnisse und besondere Umstände. II. Das Verständnis als Gabe des heiligen Geistes steht höher wie das Verständnis als Tugend in der Vernunft. Letztere aber hat zum Gegenstande nur das Notwendige. Also ist dies auch bei der Gabe des heiligen Geistes der Fall. Das Tätigsein aber beschäftigt sich nur mit dem, was sich auch anders verhalten kann und somit nicht notwendig ist. III. Die Gabe des Verständnisses erleuchtet den Geist mit Rücksicht auf das, was die natürliche Kraft der Vernunft überragt. Die Gegenstände der menschlichen Tätigkeit aber überragen nicht die natürliche Vernunft, die da zur Leiterin berufen ist für die menschliche Tätigkeit. 

Auf der anderen Seite heißt es im Ps. 110.: „Das gute Verständnis allen, die seine Gebote erfüllen.“

b) Ich antworte, die Gabe des Verständnisses erstrecke sich nicht bloß auf das, was an sich Gegenstand des Glaubens ist, sondern auch auf das, was zum Glauben in Beziehung steht. Die guten Tätigkeiten aber haben eine gewisse Beziehung zum Glauben, „der ja durch die Liebe wirkt.“ Also erstreckt sich die Gabe des Verständnisses auch auf die Gegenstände der menschlichen Tätigkeit; nicht als ob dies ihr leitender und maßgebender Gegenstand wäre, sondern insoweit ewige Gründe uns lenken und regeln im Handeln und zu deren Erwägung und Heranziehung die dem Höheren zugewandte Vernunft (Aug. de Trin. 12, 7.) bestimmt ist, welche eben ihre Vollendung findet in der Gabe des Verständnisses.

c) I. Soweit die Gegenstände menschlicher Tätigkeit auf die Regel des ewigen Gesetzes bezogen werden, und zum Zwecke haben die Seligkeit, besitzen sie jene Erhabenheit, dass die Gabe des Verständnisses sich mit ihnen beschäftigen kann. II. Das ist die Würde in der Gabe des Verständnisses, dass sie die ewigen notwendigen Gründe nicht nur erwägt, insoweit dieselben in sich bestehen; sondern auch insoweit sie eine gewisse Richtschnur der menschlichen Handlungen enthalten. Denn auf je mehr Dinge eine Erkenntniskraft sich erstreckt, desto höher steht sie. III. Das ewige Gesetz und des Menschen Vernunft bilden die Regel der menschlichen Tätigkeit. Das ewige Gesetz aber überragt die natürliche Vernunft. Die Kenntnis also, welche gemäß dem ewigen Gesetze die menschlichen Handlungen leiten soll, überragt die natürliche Vernunft und bedarf des übernatürlichen Lichtes der Gabe des heiligen Geistes. 


** Vierter Artikel. Die Gabe des Verständnisses haben alle, die im Stande der Gnade sind.

a) Dagegen spricht: I. Gregor (2. moral. 26.) schreibt: „Die Gabe des Verständnisses wird gegeben gegen die Stumpfheit des Geistes.“ Viele aber, die im Stande der Gnade sind, leiden noch an Stumpfheit des Geistes. II. Von dem, was zur Kenntnis gehört, ist einzig der Glaube zum Heile notwendig; denn „durch den Glauben wohnt Christus in uns“ Ephes. 5. Nicht alle aber, die den Glauben haben, besitzen die Gabe des Verständnisses; vielmehr müssen nach Augustin (15. de Trin. 27.), die den Glauben haben, beten, damit sie verstehen. Also ist die Gabe des Verständnisses nicht zum Heile notwendig. III. Was allen innewohnt, die im Stande der Gnade sind, wird ihnen niemals entzogen. Die Gabe des Verständnisses und andere Gaben des heiligen Geistes aber werden bisweilen mit Nutzen entzogen. Denn „manchmal, wenn der Geist auf Grund des Verständnisses erhabener Dinge sich zum Hochmut erhebt, wird er träge und stumpf selbst in den niedrigsten und wertlosesten Dingen;“ sagt Gregor (2. moral. 26.) 

Auf der anderen Seite heißt es Ps. 81.: „Sie wußten und verstanden es nicht; in Finsternissen wandeln sie.“ Keiner aber, der im Stande der Gnade ist, wandelt in Finsternissen, nach Joh. 8.: „Wer mir folgt, wandelt nicht in Finsternissen.“

b) Ich antworte, alle, die im Stande der Gnade sind, müssen die Geradheit des Willens haben, weil durch die Gnade der Wille des Menschen vorbereitet wird zum Guten, nach Augustin (de praed. sauct. 1.; retr. 1, 22.) Der Wille aber kann nur auf Grund irgend welcher Kenntnis der Wahrheit in der rechten Weise zum Guten hingeordnet werden; denn der Gegenstand des Willens ist das von der Vernunft aufgefaßte Gut. Wie aber durch die Gnadengabe der Liebe der heilige Geist den Willen regelt, dass er unmittelbar hingeordnet sei zum übernatürlichen Gute, so erleuchtet Er durch die Gabe des Verständnisses den menschlichen Geist, dass dieser eine übernatürliche Wahrheit erkenne, nach deren Richtschnur der Wille seinen Gegenstand erstreben soll. Wie also die Gnadengabe der heiligen Liebe in allen ist, welche im Stande der Gnade sind, so auch die Gabe des Verständnisses.

c) I. Die im Stande der Gnade sind, können an Stumpfheit des Geistes leiden mit Rücksicht auf Manches, was nicht zum Heile notwendig ist. Mit Beziehung auf das zum Heile Notwendige aber werden sie vom heiligen Geiste belehrt, nach 1. Joh. 27.: „Die Salbung des heiligen Geistes belehrt euch über Alles.“ II. Nicht alle, die Glauben haben, verstehen in vollkommener Weise das, was zu glauben vorgestellt wird; sie verstehen aber, dass es zu glauben sei und dass man davon nicht abweichen dürfe. III. Mit Rücksicht auf das zum Heile Notwendige wird den Heiligen nie die Gabe des Verständnisses genommen; wohl aber mit Rücksicht auf Anderes, damit von ihnen der Anlaß fern bleibe, hochmütig zu werden. 


** Fünfter Artikel. Keiner, der nicht im Stande der Gnade ist, hat die Gabe des Verständnisses.

a) Das Gegenteil scheint zu meinen: I. Augustin, denn zu Ps. 118. (concupivit anima mea desiderare) sagt er: „Es fliegt voran das Verständnis; und langsam oft kommt nach die schwächliche Hinneigung im Menschen.“ In allen aber, welche im Stande der Gnade sind, ist auf Grund der Liebe Bereitwilligkeit im Willen für das göttliche Gute; somit ist da keine schwächliche Hinneigung und demnach haben sie Verständnis ohne Gnade. II. Daniel, der Prophet (10.), der da sagt: „Des Verständnisses bedarf man im (prophetischen) Gesicht.“ Die Gabe der Weissagung kann aber bestehen ohne die heiligmachende Gnade. Denn Matth. 7. wird denen, welche sprechen: „In Deinem Namen haben wir geweissagt“ geantwortet: „Ich kenne euch nicht.“ Also kann die Gabe des Verständnisses bestehen, auch ohne die Gnade. III. Die Gabe des Verständnisses entspricht der Tugend des Glaubens, nach Isai. 7.: „Wenn ihr nicht glaubt, werdet ihr nicht verstehen.“ Der Glaube aber braucht nicht notwendig mit der Gnade verbunden zu sein. 

Auf der anderen Seite spricht der Herr bei Joh. 6.: „Ein Jeder, der vom Vater gehört und gelernt hat, kommt zu mir.“ Durch das Verständnis aber lernen wir und durchdringen wir das Gehörte. (Gregor 1. moral. 15.) Wer also die Gabe des Verständnisses hat, kommt zu Christo, was ohne die heiligmachende Gnade nicht angeht.

b) Ich antworte, die Gaben des heiligen Geistes vollenden die Seele (I., II. Kap. 68, Art. 1 u. 2), damit diese leicht in Tätigkeit zu setzen sei von seiten des heiligen Geistes. So wird also das Licht der Vernunft als die Gabe des Verständnisses aufgefaßt, dass dadurch die Vernunft leicht beweglich werde für den Anstoß, der vom heiligen Geiste ausgeht. Solche Tätigkeit oder Bewegung der Vernunft aber wird nur gedacht mit Rücksicht auf die Erfassung jener Wahrheit, welche auf den letzten Endzweck sich richtet. Wenn also die menschliche Vernunft nicht bis zu dem Punkte von seiten des heiligen Geistes in Tätigkeit gesetzt wird, dass sie die rechte Wertschätzung des letzten Endzweckes sich aneignet, so hat sie noch nicht die Gabe des Verständnisses erlangt; mag sie auch mit Hilfe des heiligen Geistes andere vorbereitende Wahrheiten erfassen. Eine rechte Wertschätzung des vorliegenden Zweckes nun hat allein jener, der sich rücksichtlich des Zweckes nicht täuscht, sondern demselben fest anhängt; und das geschieht, wenn der letzte Endzweck in Betracht kommt, einzig und allein kraft der heiligmachenden Gnade. Ohne Gnade also kann die Gabe des Verständnisses nicht bestehen.

c) I. Augustin spricht von einer irgend beliebigen Erleuchtung der Vernunft, welche jedoch die Höhe der Gabe des Verständnisses nicht erreicht. II. Das prophetische Licht an sich betrifft nicht die rechte Wertschätzung des letzten Endzweckes, sondern nur das, was dem Propheten geoffenbart wird. Einzig in der erstgenannten Erleuchtung aber besteht die Gabe des, Verständnisses. III. Der Glaube schließt bloß die Zustimmung ein; die Gabe des Verständnisses aber besagt ein Durchdringen der Wahrheit bis zum Endzwecke hin, was nur in Begleitung der Gnade statthat. 


** Sechster Artikel. Die Gabe des Verständnisses ist unterschieden von den anderen Gaben des heiligen Geistes in der Vernunft.

a) Das scheint nicht. Denn: I. Wenn die Gegensätze zu gewissen Dingen ein und dasselbe sind, so sind auch diese Dinge selbst nicht verschieden. Nun sagt Gregor (2. moral. 26.): „Der Weisheit steht entgegen die Thorheit, dem Verständnisse die Stumpfheit, dem Rate die Übereilung, dem Wissen die Unkenntnis.“ Stumpfheit, Übereilung, Unkenntnis aber ist nichts Anderes wie Thorheit. Also ist auch das Verständnis ein und dasselbe wie die übrigen Gaben. II. Das Verständnis als Tugend in der Vernunft unterscheidet sich von den anderen Tugenden in der Vernunft dadurch, dass seinen Gegenstand die von der Natur der Vernunft selbst dargebotenen allgemeinen Grundprincipien bilden. Darum handelt es sich aber bei der Gabe des Verständnisses nicht. Denn für den Bereich der Natur genügt der Zustand des natürlichen Verständnisses, für den Bereich des Übernatürlichen genügt der Glaube; sind ja doch die Glaubensartikel die Fundamentalprincipien für die übernatürliche Kenntnis. Also ist da von einem Unterschiede der Gabe des Verständnisses von den anderen Gaben des heiligen Geistes nicht die Rede. III. Alle andere Kenntnis ist entweder rein beschaulich oder auf das praktische Tätigsein gerichtet und läßt danach in sich einen Unterscheidungsgrund zu. Die Gabe des Verständnisses aber ist zugleich beschaulich und dient dem Handeln, läßt also von sich aus leinen Unterscheidungsgrund zu. 

Auf der anderen Seite wird die Gabe des Verständnisses mit und neben den anderen genannten Gaben des heiligen Geistes bei Isai. 11. aufgezählt.

b) Ich antworte, der Unterschied zwischen der Gabe des Verständnisses einerseits und der „Frömmigkeit“, der „Stärke“ und der „Furcht“ andererseits sei offenbar; denn diese drei letzteren sind in dem „begehrenden Teile“. Der Unterschied aber mit Rücksicht auf die Gaben der „Weisheit“, der „Wissenschaft“, des „Rates“ ist nicht so offenbar; denn diese drei sind ebenfalls in der Vernunft wie das Verständnis. Manche nun hielten dafür, diese letztgenannten zwei richteten sich auf das Tätigsein, das Verständnis aber sei rein beschaulich; so zwar, dass die Weisheit das endgültige Urteil fälle, während das Verständnis bloß durchdringe bis ins Innere. (I., II. Kap. 68, Art. 4.) Wer jedoch genau zusieht, findet, dass die Gabe des Verständnisses sich auch auf das tätige Leben erstreckt, wie bereits gesagt worden; und ebenso ist die Gabe der Wissenschaft beschaulich und dem Tätigsein zugleich dienend. Deshalb muss man anders sagen. Alle diese vier Gaben nämlich haben Beziehung zur übernatürlichen Kenntnis, die durch den Glauben vermittelt wird. „Der Glaube nun ist vom Hören.“ Derselbe bezieht sich zu allererst auf die erste, die Urwahrheit; dann auf manches Kreatürliche und endlich auf die Regelung der menschlichen Tätigkeiten, da er „durch die Liebe wirkt.“ Demnach muss 1. das Gehörte kraft des Verständnisses durchdrungen werden oder aufgefaßt; und dazu dient die Gabe des Verständnisses. Es muss 2. der Mensch darüber sich ein richtiges Urteil bilden, dass er nämlich urteile, er solle anhängen und vom Gegenteile sich entfernen. Dieses Urteil gehört mit Rücksicht auf die göttlichen Dinge der Gabe der Weisheit zu; mit Rücksicht auf das Kreatürliche der Gabe der Wissenschaft; mit Rücksicht auf die einzelne Tätigkeit der Gabe des Rates.

c) I. Dieser Unterschied entspricht durchaus den Worten Gregors. Denn der Stumpfheit steht entgegen das Scharfe; also der Scharfsinn, der dem Verständnisse entspricht. Ein Thor ist jener, der über den gemeinsamen Zweck des menschlichen Lebens ein verkehrtes Urteil hat; was der Weisheit widerspricht, welche über die allgemeine erste Ursache alles Seins recht urteilt. Die Unkenntnis schließt einen Mangel an Einzelkenntnissen in der Vernunft ein; und steht so entgegen der Wissenschaft, die in den Stand setzt, ein richtiges Urteil über die besonderen einzelnen Ursachen im Bereiche des Geschöpflichen zuhaben. Der Rat aber steht offenbar entgegen der Übereilung, die ohne vorgängiges Erwägen vorgeht. II. Der Glaube stimmt den ersten Grundprincipien der übernatürlichen Kenntnis zu; das Verständnis durchdringt das Gehörte. III. Nicht mit Rücksicht auf das Urteil, sondern auf die richtige Erfassung des Gehörten erstreckt sich die Gabe des Verständnisses, auf rein Beschauliches und auf das Tätigsein. 


** Siebenter Artikel. Der Gabe des Verständnisses entspricht die sechste Seligkeit.

a) Das Gegenteil erhellt aus Folgendem: I. Die Reinheit des Herzens gehört mehr der Hinneigung an, oder dem Affekte, wie der Vernunft. II. „Der Glaube reinigt ihre Herzen,“ sagt Petrus (Act. 15.); also nicht die Gabe des Verständnisses. III. Die Gaben des heiligen Geistes vollenden den Menschen im gegenwärtigen Leben. Die Anschauung Gottes aber macht selig. Also entspricht die sechste Seligkeit nicht der Gabe des Verständnisses. 

Auf der anderen Seite sagt Augustin (1. de serm. Dom. in monte 4.): „Die sechste Tätigkeit des heiligen Geistes, die da ist das Verständnis, entspricht den Reinen im Herzen, die da mit reinem Auge sehen können, was das Auge nicht gesehen hat.“

b) Ich antworte, in der sechsten Seligkeit sei das Eine in der Weise des Verdienstes hingestellt, das Andere in der Weise des Lohnes. Beides entspricht in etwa der Gabe des Verständnisses. Denn die eine Reinigkeit bereitet vor für die Anschauung Gottes und macht den Geist frei von ungeregelten Neigungen; diese Reinigkeit vollzieht sich vermittelst der Tugenden und Gaben im begehrenden Teile. Die andere Reinigkeit vollendet das Werk der ersten. Es ist dies die Loslösung der Vernunft von den Sinnesbildern und Irrtümern; damit nämlich das, was über Gott gesagt wird, man nicht auffasse nach Weise der körperlichen Phantasiebilder und gemäß der häretischen Verkehrtheiten; und diese Reinigkeit wird bewirkt durch die Gabe des Verständnisses. Ähnlich besteht auch ein doppeltes Schauen Gottes: Das eine ist vollkommen und vollzieht sich kraft des göttlichen Wesens; das andere aber ist unvollkommen und durch dasselbe sehen wir nicht was Gott dem Wesen nach ist, sondern was Er nicht ist. Und je vollkommener wir in diesem Leben Gott erkennen, desto mehr verstehen wir, dass Er Alles überragt, was mit der Vernunft begriffen wird. Beiderlei Schauen nun gehört der Gabe des Verständnisses an: das erste dem in der Heimat vollendeten Verständnisse; das andere der Gabe des angefangenen Verständnisses, wie es hier auf Erden besessen wird.

c) Damit sind die Einwürfe widerlegt. Denn die beiden ersten sprechen von der erstgenannten Reinigkeit; der dritte vom vollendeten Schauen Gottes. Die Gaben des heiligen Geistes aber vollenden uns hier gemäß einem gewissen Beginn und werden voll werden in der Heimat. 


** Achter Artikel. Unter den Früchten entspricht der Gabe des Verständnisses der „Glaube“.

a) Dies scheint nicht. Denn: I. Das Verständnis ist umgekehrt die Frucht des Glaubens, nach Isai. 7.: „Wenn ihr nicht glaubet, werdet ihr nicht verstehen“ (70. interpr.), wo wir in Vulgata haben: „Wenn ihr nicht glaubet, werdet ihr nicht dauern.“ II. Der Glaube ist das Erste in der Vernunft für die übernatürliche Erkenntnis; ist er doch das Fundament des ganzen übernatürlichen Baues. Also kann er nicht den Charakter einer Frucht haben. III. Eine größere Zahl von „Gaben“ gehört zur Vernunft wie zum begehrenden Teile. Unter den Früchten aber gehört nur eine zur Vernunft, nämlich der Glaube. Also entspricht diese Frucht ganz gleichermaßen der Weisheit oder dem Rate oder dem Wissen wie dem Verständnisse. 

Auf der anderen Seite ist der Zweck einer jeden Sache ihre Frucht. Nun ist der Zweck für die Gabe des Verständnisses in erster Linie ein gewisser hoher Grad von Sicherheit und Gewißheit im Glauben; und so aufgefaßt ist der Glaube die Frucht des Verständnisses, wie die Glosse zu Galat. 5. sagt: „Der Glaube als Frucht ist eine gewisse Sicherheit im Glauben.“ Also entspricht der „Glaube“ als Frucht der Gabe des Verständnisses.

b) Ich antworte, als Frucht des heiligen Geistes werde bezeichnet das Letzte und Ergötzliche, was in uns kraft des heiligen Geistes sich ergiebt. Das Letzte und Ergötzliche aber hat den Charakter des Zweckes, der den Gegenstand des Willens bildet. Was also das Letzte und Ergötzliche im Willen ist, das steht gewissermaßen als Frucht all des Anderen da, was den anderen Vermögen zugehört. Danach kann somit für eine Gabe oder für eineTugend, welche einem Vermögen zur Vervollkommnung dient, eine doppelte Frucht angenommen werden: die eine, welche dem betreffenden Vermögen selbst angehört; und die andere als die letzte, welche dem Willen zugehört, der da gemäß seinem Gegenstande, dem Zwecke, alle übrigen Vermögen in Tätigkeit setzt. So entspricht demgemäß der Gabe des Verständnisses als eigene Frucht im nämlichen Vermögen der Vernunft, der „Glaube;“ als letzte Frucht entspricht ihr die Freude, welche dem Willen zugehört.

c) I. Hier wird nicht die Tugend des Glaubens als solche genommen; sondern eine gewisse Sicherheit und Ruhe im Glauben ist die Frucht des Verständnisses. II. Der Glaube kann nicht so im allgemeinen dem Verständnisse vorangehen. Denn der Mensch könnte nicht den einzelnen vorgelegten Glaubenssätzen zustimmen, wenn er sie nicht in etwa verstände. Wohl aber folgt die Vollendung des Verständnisses dem Glauben als Tugend aufgefaßt; und der Glaube, insoweit er der Vernunft Ruhe und Sicherheit gewährt, folgt dann der Vollendung als Frucht. III. Soweit die Gabe des Verständnisses dient der praktischen Tätigkeit, folgt ihr keine Frucht. Denn nach dieser Seite hin ist der Zweck der Vernunft nicht in ihr selbst, wie dies beim reinen Beschauen der Fall ist, sondern ist etwas Anderes. Deshalb hat die Gabe des Rates gar keine Frucht, die ihr entspräche. Soweit aber die Gabe der Weisheit, der Wissenschaft, des Verständnisses zur beschaulichen Kenntnis sich wendet, entspricht ihnen nur eine Frucht: die Sicherheit im Glauben. Mehrere Früchte entsprechen dem begehrenden Teile; denn der Charakter des Endes, des Zweckes gehört vielmehr dem begehrenden Teile zu. 


* II-II, Q. 9 - Gabe der Erkenntnis oder Wissenschaft (scientia)

** Erster Artikel. Es giebt eine Gabe der Wissenschaft.

a) Das Gegenteil erhellt, wenn Folgendes erwogen wird: I. Eine Gabe des heiligen Geistes steht immer höher als die Natur. Die Wissenschaft aber ist nur eine Wirkung der natürlichen Vernunft; denn „der Beweis ist ein Syllogismus, der Wissen begründet“ heißt es 1.Poster. II. Die „Gaben“ sind allen im Stande der Gnade Befindlichen gemein sam. (I., II. Kap. 68, Art. 2 u. 6.) „Wissenschaft aber haben nicht viele Gläubigen, wenn sie auch Glauben besitzen“ sagt Augustin. (14. de Trin. 1.) III. Die „Gabe“ ist vollkommener wie die Tugend (I. c. Art. 8.). Eine Gabe also genügt für die Vollendung einer Tugend behufs der geeigneten Tätigkeit. Nun entspricht der Tugend des Glaubens die Gabe des Verständnisses. Also entspricht ihr nicht die Gabe der Wissenschaft; und es ist auch schwer zu sagen, welch anderer Tugend sie entsprechen sollte. Da also die Gaben zur Vollendung der Tugenden dienen behufs der geeigneten Tätigkeit, so ist offenbar die Gabe der Wissenschaft als solche zwecklos und bildet somit gar keine Gabe des heiligen Geistes. 

Auf der anderen Seite wird sie Isaias 11. unter den Gaben des heiligen Geistes aufgezählt.

b) Ich antworte, die Gnade sei vollendeter wie die Natur. Wo also der Mensch durch die Natur vollendet werden kann, da erweist sie sich nicht mangelhaft. Nun aber wird der Mensch, wenn er kraft der natürlichen Vernunftkraft gemäß seinem Verständnisse einer Wahrheit zustimmt, in zweifacher Weise mit Rücksicht auf diese Wahrheit vollendet: 1. weil er sie auffaßt; 2. weil er ein zuverlässiges Urteil über sie hat. Damit also die menschliche Vernunft der Wahrheit des Glaubens beistimme, wird zweierlei erfordert: 1. dass sie richtig das Gehörte auffaßt; und 2. dass sie ein zuverlässiges Urteil darüber besitzt, indem sie das zu Glaubende unterscheidet vom Nicht-zu-GIaubenden. Behufs des ersten Erfordernisses hat sie die Gabe des Verständnisses, behufs des zweiten die der Wissenschaft.

c) I. Je nach der verschiedenen Seinsweise der betreffenden vernünftigen Natur ist verschieden die Art der Gewißheit in der entsprechenden Kenntnis. Denn der Mensch gewinnt ein sicheres Urteil kraft des Schließens der Vernunft; und deshalb wird menschliche Wissenschaft durch Beweisgründe erworben. Gott aber hat durch einfaches Anschauen seiner selbst das zuverlässig sichere Urteil der Wahrheit. (I. Kap. 14, Art. 7.) Seine Wissenschaft also ist durchaus einfach und ohne Schließen. Und ihr ähnlich ist die Wissenschaft, welche als Gabe des heiligen Geistes bezeichnet wird. II. Einmal muss der Mensch wissen, was er zu glauben hat, und muss er somit unterscheiden das zu Glaubende vom Nicht-zu-Glaubenden. Danach haben alle Heiligen die Gabe der Wissenschaft. Dann giebt es eine Wissenschaft, wonach der Mensch noch des weiteren das zu Glaubende offenbaren, dazu anleiten, es verteidigen kann. Diese Wissenschaft nun ist eine zum Besten anderer verliehene Gnade; und wird nur manchen zu teil. Deshalb sagt Augustin gleich darauf: „Ein Anderes ist es zu wissen, was man zu glauben hat; ein Anderes, zu wissen, wie das Geglaubte den Frommen Beistand leistet und gegen die Gottlosen verteidigt wird.“ III. Die Gaben des heiligen Geistes sind vollendeter wie die moralischen Tugenden und die in der Vernunft; aber nicht vollendeter wie die theologischen Tugenden. Vielmehr haben sie Beziehung zu den letzteren und zu deren Vollendung wie zu ihrem Zwecke. Verschiedene Gaben können deshalb ganz wohl einer einzigen theologischen Tugend dienen. 


** Zweiter Artikel. Die Gabe der Wissenschaft berücksichtigt nicht das Göttliche.

a) Das scheint aber. Denn: I. „Durch das Wissen wird der Glaube,“ der sich doch mit göttlichen Dingen befaßt, „erzeugt, genährt, gestärkt und verteidigt“ sagt Augustin. (14. de Trin. 1.) II. Die Gabe der Wissenschaft steht höher wie die erworbenen Wissenschaften, von denen doch eine sich mit göttlichen Dingen befaßt, nämlich die Metaphysik. III. Nach Röm. 1. „wird durch die sichtbaren Dinge, die da gemacht worden, das Unsichtbare Gottes erschlossen.“ Befaßt sich also die Wissenschaft mit den sichtbaren Dingen, dann auch mit den göttlichen. 

Auf der anderen Seite sagt Augustin (l. c.): „Die Wissenschaft der göttlichen Dinge wird so recht eigentlich Weisheit genannt; der Kenntnis der menschlichen Dinge giebt man den Namen Wissenschaft.“

b) Ich antworte; ein Urteil über eine Sache wird in erster Linie gemäß der Ursache derselben gegeben und somit muss man gemäß der Ordnung in den Ursachen die Ordnung in den Urteilen ersehen. Wie nämlich die erste Ursache die Ursache der untergeordneten ist, so wird über die ungeordnete geurteilt kraft der ersten. Über die erste Ursache aber kann man nicht urteilen vermittelst einer anderen Ursache. Also ist das Urteil, welches kraft der ersten Ursache gefällt wird, das erste und vollkommenste. Im Bereiche dessen aber, wo etwas das Vollkommenste ist, wird der gemeinsame Name der Art angeeignet dem, was vom Vollkommensein vielmehr absteht; dem Vollkommensten selbst wird ein specieller Name zugeeignet; wie wir dies bei den Engeln z. B. sehen, wo der gemeinsame Namen dem niedrigsten Chöre, also dem mindest vollkommenen, als Eigenname beigelegt wird. Weil nun der Name „Wissenschaft“ die Gewißheit eines Urteils einschließt, so erhält das Urteil, welches kraft der ersten Ursache Gewißheit in sich hat, einen speciellen Namen, den der Weisheit. Denn weise wird in jedem Seinsbereiche derjenige genannt, welcher die höchste Ursache in jenem Seinsbereiche kennt und danach urteilt. Weise aber schlechthin, ohne Einschränkung heißt jener, der die schlechthin höchste Ursache kennt, nämlich Gott. Die Kenntnis der göttlichen Dinge also nennt man Weisheit; die Kenntnis der menschlichen nennt man Wissenschaft, wo der gemeinsame Name, welcher „Gewißheit“ besagt, dem Urteile zugeeignet wird, welches sich auf untergeordnete Ursachen stützt. Danach wird also unterschieden die Gabe der Wissenschaft von jener der Weisheit; denn sie befaßt sich nur mit menschlichen oder geschaffenen Dingen.

c) I. Der Glaube erstreckt sich auf Ewiges und Göttliches; er selbst aber ist etwas Zeitliches in der Seele des Glaubenden. Zu wissen also, was man glauben soll, gehört der Gabe der Wissenschaft an; zu wissen aber die geglaubten Sachen in ihrem eigenen Sein, wie sie sind, nämlich vermittelst einer gewissen Einigung mit selben, gehört der Gabe der Weisheit an. Die Gabe der Weisheit also entspricht mehr der Liebe, welche den Menschengeist mit Gott eint. II. Die Gabe der Wissenschaft besteht insoweit, als ihre Aufgabe beschränkt wird auf das Urteil, welches vermittelst der geschöpflichen Dinge gefällt wird. III. Sofern das, was in einer Wissenschaft Formalgrund ist, die leitende Stelle einnimmt, gehört es, wenn der Mensch vermittelst der geschaffenen Dinge Gott erkennt, vielmehr zur Wissenschaft als zur Weisheit; — und umgekehrt wenn wir vermittelst der göttlichen Dinge und Gründe urteilen über die Geschöpfe, so ist dies mehr Weisheit wie Wissenschaft.


** Dritter Artikel. Die Gabe der Wissenschaft ist an erster Stelle eine beschauliche, und erst an zweiter Stelle eine dem Tätigsein dienende.

a) Die Gabe der Wissenschaft scheint ganz und gar auf die Tätigkeit gerichtet zu sein. Denn: I. „Die Tätigkeit, durch welche wir die äußeren Dinge gebrauchen, wird der Wissenschaft zugeschrieben;“ sagt Augustin. (12. de Trin. 14.) Dies besagt aber, die Wissenschaft sei auf die Tätigkeit gerichtet. II. Gregor (1. moral. 15.) sagt: „Wertlos ist die Wissenschaft, welche der Frömmigkeit nichts nützt; und sehr unnütz ist die Frömmigkeit, welche der Unterscheidung von seiten der Wissenschaft ermangelt.“ Also ist die Wissenschaft nur auf das Tätigsein gerichtet. III. Die Gaben des heiligen Geistes sind allein in den Gerechten. Rein beschauliches Wissen aber können auch die Ungerechten haben, nach Jakob. 4.: „Der da weiß, das Gute zu thun und es nicht thut, für den ist dies Sünde.“ Also ist die Gabe der Wissenschaft eine rein dem Tätigsein dienende. 

Auf der anderen Seite sagt Gregor der Große (1. moral. 15.): „Die Wissenschaft bereitet an ihrem Tage ein Gastmahl, weil sie im Bauche des vernünftigen Geistes das Fasten der Unwissenheit überwindet.“ Die Unwissenheit aber wird sowohl durch das beschauliche wie durch das praktisch tätige Wissen entfernt. Also ist die Gabe der Wissenschaft eine der Beschauung und der Tätigkeit dienende.

b) Ich antworte, die Gabe der Wissenschaft habe ebensogut wie die des Verständnisses Beziehung zur Sicherheit und Gewißheit des Glaubens. Der Glaube aber besteht an erster leitender Stelle in der Beschauung, insofern selbiger der ersten Wahrheit anhängt. Weil aber die erste Wahrheit zugleich der letzte Endzweck ist, um dessentwillen wir tätig sind, deshalb erstreckt sich der Glaube als Richtschnur auch auf die Tätigkeit; „er ist tätig durch die Liebe.“ Gal. 5. In erster Linie also ist die Gabe der Wissenschaft eine beschauliche; denn vermittelst ihrer weiß der Mensch, was er zu glauben hat. An zweiter Stelle leitet sie auch unser Handeln; denn durch das, was wir glauben, haben wir die Richtschnur für unser Tätigsein.

c) I. Augustin spricht hier von der Wissenschaft im letztgenannten Sinne. Sie regelt wohl die Tätigkeit und die Frömmigkeit; aber sie thut das weder allein noch an erster Stelle. III. Nicht wer auch immer „versteht“, hat die Gabe des Verständnisses; sondern wer versteht infolge des Zustandes der Gnade. So haben auch nur jene die Gabe der Wissenschaft, die infolge des Einsprechens des heiligen Geistes, infolge der Gnade also, ein richtiges Urteil haben über das zu Glaubende und zu Thuende. Das ist jenes Wissen der Heiligen, von dem Sap. 10. gesagt wird: „Den Gerechten hat Gott geführt den rechten Weg … und hat ihm gegeben die Wissenschaft der Heiligen.“ 


** Vierter Artikel. Der Gabe der Wissenschaft entspricht die dritte Seligkeit.

a) Das wird bestritten. Denn: I. Das Übel ist die Ursache der Trauer, das Gute Ursache der Freude. Die Wissenschaft aber offenbart an erster Stelle das Gute; denn erst kraft des Guten wird das Übel erkannt. „Das Grade ist die Richtschnur für das Gerade und Krumme,“ sagt ja Aristoteles. (1. de anima.) Also kommt der Wissenschaft nicht die Trauer zu. II. Die Wahrheit wird von der Wissenschaft betrachtet. „Darin aber ist keine Bitterkeit und das Zusammenleben mit ihr bietet keinen Ekel.“ Sap. 8. III. Die Gabe der Wissenschaft ist an erster Stelle eine spekulative, beschauliche. „Die beschauliche Vernunft aber sagt nichts vom Erstreben und vom Fliehen;“ schreibt Aristoteles. (3. de anima.) Also ist da weder Trauer noch Freude anzusetzen. 

Auf der anderen Seite schreibt Augustin (de serm. Dom. in monte 4.): „Die Wissenschaft kommt den Traurigen zu, die da gelernt haben, mit welchen Übeln sie gebunden sind und was sie als das ihnen entsprechende Gut begehren sollen.“

b) Ich antworte, der Wissenschaft gehöre so recht eigentlich zu das rechte Urteil über die Kreaturen. Nun sind es die Kreaturen, welche den Anlaß bilden, dass der Mensch sich von Gott abwendet, nach Sap. 14.: „Die Kreaturen sind würdig geworden gehaßt zu werden.… Fallstricke sind sie für die Füße der Thoren,“ die da nämlich kein richtiges Urteil über sie haben, insofern sie meinen, man müsse sie als das vollkommene Gut betrachten und so den letzten Endzweck in sie setzen. Dieses Urteil nun wird den Menschen bekannt durch das rechte Urteil über die Kreaturen, wie es die Gabe der Wissenschaft an die Hand giebt. Und demnach entspricht die Trauer als Seligkeit der Gabe der Wissenschaft.

c) I. Die geschaffenen Güter regen nur dann zur geistigen Freude an, wenn sie auf das göttliche Gut bezogen werden, von woher so recht eigentlich die geistige Freude kommt. Unmittelbar also entspricht der geistige Friede und Jubel der Gabe der Weisheit. Der Gabe der Wissenschaft aber entspricht zuerst die Trauer infolge der vergangenen Irrtümer; und dann der Trost, insoweit der Mensch nun die Kreaturen hinordnet zum göttlichen Gute auf Grund des Urteils, das ihm die Wissenschaft an die Hand giebt. Die Trauer wird also hier als das Verdienst gesetzt, die folgende Tröstung als Lohn, der hier beginnt und im Jenseits vollendet wird. II. Der Mensch kann manchmal trauern über die Sache selber, deren Wahrheit er betrachtet. III. Der Gabe der Wissenschaft in ihrem beschaulichen Teile entspricht keine Seligkeit; denn nicht in der Betrachtung der Kreaturen ist die Seligkeit des Menschen, sondern in der Anschauung Gottes. Im gebührenden tätigen Gebrauche der Kreaturen aber besteht eine gewisse Seligkeit; denn ein solcher Gebrauch ist der Weg zur ewigen Seligkeit.


* II-II, Q. 19 - Gabe der Gottesfurcht

** Erster Artikel. Gott kann Gegenstand der Furcht sein.

a) Dies scheint nicht. Denn: I. Denn Gegenstand der Furcht ist ein in der Zukunft drohendes Übel; Gott aber ist die Güte selbst. II. Die Furcht steht der Hoffnung entgegen. Wir haben aber mit Rücksicht auf Gott Hoffnung. III. „Wir fürchten das, von woher uns Übel droht,“ heißt es (2 Rhet. c. 5.) bei Aristoteles. Kein Übel aber kommt von Gott, sondern nur von uns selber, nach Osea 13.: „Dein Verderben ist von dir, Israel: von mir allein kommt dein Beistand.“ 

Auf der anderen Seite sagt Jerem. 10.: „Wer wird Dich nicht fürchten, König der Völker;“ und Malach. 1.: „Wenn ich der Herr, wo ist die Furcht vor mir?“

b) Ich antworte, ähnlich wie die Hoffnung zum Gegenstande hat: 1. das Gute, was wir hoffen; und 2. den Beistand desjenigen, durch den man dieses Gute erreichen kann; — so habe die Furcht zum Gegenstande: 1. das Übel selbst; und 2. denjenigen, von dem das Übel kommen kann. Nur in der zweiten Weise kann Gott gefürchtet werden, denn von Ihm oder mit Rücksicht auf Ihn kann uns ein Übel kommen; Er selber ist ja nach keiner Seite hin ein Übel, sondern die reinste Güte. Von Ihm kann nun kommen das Übel der Strafe, das ja kein Übel schlechthin ist, sondern nur nach einer gewissen Seite hin; vielmehr ist die Strafe schlechthin betrachtet ein Gut. Denn Übel an sich ist nur, was vom Guten an sich, vom letzten Endzwecke, ausschließt; und das ist das Übel der Schuld. Die Strafe jedoch hängt ab von der Beziehung zum letzten Endzwecke, obgleich sie nach einer gewissen Seite hin eines beschränkten besonderen Gutes beraubt. Mit Rücksicht auf Gott aber kann uns das Übel der Schuld kommen; nicht von Ihm kann es ausgehen, insofern nämlich wir dadurch von Ihm getrennt werden. So kann also Gott Gegenstand der Furcht sein und muss es sein.

c) I. Gott ist nicht Gegenstand der Furcht, insoweit diese ein Übel flieht. II. In Gott ist Gerechtigkeit, womit Er die Sünder straft; es ist in Ihm Barmherzigkeit, kraft deren Er die Guten belohnt. Gemäß dem ersten Gesichtspunkte ersteht in uns die Furcht, gemäß dem zweiten die Hoffnung. III. Das Übel der Schuld ist nicht von Gott, sondern besteht viel mehr in uns, soweit wir von Gott uns entfernen. Das Übel der Strafe ist von Gott; aber soweit es etwas Gutes, nämlich die Wirkung der Gerechtigkeit ist; — als Strafe also, als Übel ist sie verdient durch unsere Sünden. Deshalb sagt Sap. 1.: „Gott hat den Tod nicht gemacht… sondern die Gottlosen haben den Tod mit ihren Worten und mit den Händen sich geholt.“ 


** Zweiter Artikel. Die Furcht wird eingeteilt in eine kindliche, anfängliche, knechtische und weltliche.

a) Diese Einteilung ist unzulässig. Denn: I. Damascenus (3. de orth. fide 15.) nimmt sechs Arten Furcht an, nämlich noch die Trägheit und das Erröten. II. Jede von diesen vier genannten Arten Furcht ist entweder gut oder schlecht. Die Furcht aber, soweit sie der Natur allein entspricht, ist weder gut noch schlecht; — denn sie ist im Teufel, der „glaubt und zittert“; und sie ist in Christo, der „anfing zu fürchten und Angst zu haben.“ Mark. 4. Diese also fehlt in der Aufzählung. III. Wie kindliche Furcht, so müsste auch eine Furcht der Gattin gegenüber dem Manne, nämlich die keusche Furcht, angesetzt sein. IV. Die knechtische, die weltliche, die anfängliche, alle diese drei Arten Furcht haben zum Gegenstande die Strafe. Also ist da kein Unterschied. V. Es giebt eine Begierlichkeit der Augen, welche auf die Güter der Welt geht; und eine des Fleisches, die auf das eigene Ergötzen sich richtet. Also muss auch die weltliche Furcht, welche auf die äußeren Güter sich richtet, unterschieden werden von der Menschenfurcht, kraft deren jemand Schaden für die eigene Person fürchtet. 

Auf der anderen Seite steht die Autorität des Petrus Lombardus. (34. dist. 3. Sent.)

b) Ich antworte; wir sprechen jetzt von der Furcht, insoweit wir kraft derselben in einer gewissen Weise Gott zu- oder von Ihm abgewendet werden. Denn bisweilen trennt sich der Mensch von Gott wegen eines Übels, das er fürchtet; und das ist die Menschen- oder die weltliche Furcht. Bisweilen hängt er Gott an wegen eines Übels, das er fürchtet. Wenn nämlich jemand Gott anhängt, weil er das Übel der Strafe fürchtet, so ist das knechtische Furcht; hängt er Ihm an, weil er das Übel der Schuld, die Sünde fürchtet, so ist das kindliche Furcht; denn Sache der Kinder ist es, die Beleidigungen des Vaters zu fürchten. Hängt er Gott an aus beiden Gründen zusammen, so ist es die anfängliche Furcht. Wie aber das Übel der Schuld gefürchtet werden kann, ist I., II. Kap. 42, Art. 3 erklärt worden.

c) I. Damascenus spricht von der Furcht, soweit sie eine sinnliche Leidenschaft ist; wir sprechen davon mit unmittelbarer Rücksicht auf Gott. II. Die der Natur entsprechende, die natürliche Furcht, wird vorausgesetzt vom moralisch Guten und Bösen; hier ist nur die Rede von der Furcht im moralischen Sinne, die von Gott ab- oder Ihm zuwendet. III. Die sklavische Furcht gründet sich auf die Macht des Herrn; die kindliche auf die Zuneigung des Kindes zum Vater oder der Gattin zum Gatten. Die kindliche und die keusche Furcht ist also dasselbe. Deshalb heißt es Rom. 3.: „Ihr habt erhalten den Geist der Gotteskindschaft, in welchem wir rufen: Abba, Vater;“ — und 2. Kor. 11.: „Ich habe euch verlobt einem einzigen Manne, eine keusche Jungfrau zu sein Christo.“ Beides kommt von der kindlichen oder keuschen Furcht. IV. Die Menschen- oder weltliche Furcht berücksichtigt das Übel der Strafe, unter dem Gesichtspunkte dass es von Gott abwendet, weil die Feinde Gottes übles drohen, wenn man Gott dient. Die knechtische Furcht richtet sich auf das Übel der Strafe, insoweit dadurch die Menschen zu Gott gezogen werden, an erster leitender Stelle; die anfängliche Furcht geht auf den nämlichen Gegenstand, aber so dass die Strafe bereits eine untergeordnete Stelle einnimmt und die Liebe die erste. V. Die äußeren Güter gehören zum Körper. Also ist die Strafe, welche der äußeren Güter beraubt, immer auch eine den Körper betreffende Strafe; und die Furcht, diese Güter zu verlieren, fällt mit der Furcht vor körperlichem Übel zusammen.


** Dritter Artikel. Die weltliche oder Menschenfurcht ist immer schlecht.

a.) Das scheint nicht. Denn: I. Die Menschenfurcht schließt ein die Ehrfurcht vor den Menschen. Luk. 18. aber werden jene getadelt, welche die Menschen nicht fürchten: „Der ungerechte Richter fürchtete weder Gott noch die Menschen.“ II. Die Menschenfurcht erstreckt sich auf die Strafen von seiten der weltlichen Gerichtsbarkeit; diese aber führen zum Guten, nach Röm. 13.: „Du willst keine Furcht vor der Gewalt? Thue Gutes und Lob wirst du von ihr erhalten.“ III. Es ist rein der Natur des Menschen entsprechend, den Schaden am eigenen Leibe und an seinem eigenen Besitze zu fürchten. Also ist solche Furcht nicht immer schlecht. 

Auf der anderen Seite sagt der Herr bei Matth. 10.: „Fürchtet nicht jene, die den Leib töten.“ Nur aber Schlechtes wird von seiten Gottes verboten.

b) Ich antworte, der Wesenscharakter aller moralischen Zustände hänge vom Gegenstande ab, Der dem Begehren eigens entsprechende Gegenstand nun ist das Endgut. Also vom eigens entsprechenden Zwecke erhalten die Bewegungen des begehrenden Teiles ihren Wesenscharakter. Wer z. B. die Geldgier als Liebe zur Arbeit bezeichnete, weil wegen der Geldgier die Menschen arbeiten, würde nicht recht bezeichnen. Denn die Geldgierigen suchen nicht als ihren Zweck die Arbeit, sondern nur als Zweckdienliches. Als Zweck betrachten sie den Reichtum, so dass mit Recht das Verlangen nach Reichtum Geldgier genannt wird und dies ist ein Übel. Demgemäß also wird Weltliebe genannt im eigentlichen Sinne jene, kraft deren jemand sich auf die Welt stützt als auf den letzten Endzweck; und so ist diese Liebe immer schlecht. Die Furcht aber entsteht aus der Liebe. Denn zu verlieren fürchtet der Mensch das, was er liebt. Die Menschen- oder weltliche Furcht also, die aus der Liebe zur Welt entsteht, ist immer schlecht.

c) I. Man kann die Menschen ehren, insofern in ihnen etwas von Gott Kommendes ist; nämlich Gnade oder Tugend oder wenigstens das Bild Gottes. Wer so die Menschen nicht ehrt, wird getadelt. Man kann aber auch die Menschen ehren oder fürchten, insoweit sie Gott entgegen sind; und so werden jene gelobt, die solche Menschen nicht ehren, nach Ekkli. 48.: In seinen Tagen fürchtete er nicht den Fürsten.“ II. Straft die weltliche Gerichtsbarkeit, um vom Bösen zurückzuziehen, so ist sie das Werkzeug Gottes, nach Röm. 13, 4. Danach also die menschliche Gewalt fürchten, gehört zur knechtischen oder anfänglichen Furcht. III. Dass der Mensch das Übel an seinem Leibe und Besitze flieht, das ist natürlich; dass er aber um dessentwillen von der Gerechtigkeit abweicht, das ist gegen die natürliche Vernunft: „Zu den Werken der Sünde soll sich niemand zwingen lassen,“ sagt Aristoteles (3 Ethic. 1.); „denn schlimmer ist es, dergleichen Sünden zu begehen wie irgend welche Strafen zu leiden.“ 


** Vierter Artikel. Die knechtische Furcht ist gut.

a) Dies ist nicht der Fall. Denn: I. Zu Röm. 8. sagt die Glosse (aus Prosper. c. 172. lib. Sent.): „Wer aus Furcht etwas thut, kann etwas thun, was an sich gut ist; er macht es aber nicht in guter Weise.“ Dessen tatsächlicher Gebrauch aber schlecht ist, das ist selber schlecht. II. Was aus der Sünde als der Wurzel kommt, ist schlecht. Zu Job 3.: Quare non in vulva mortuus sum, sagt Gregor (4. moral. 25.): „Wenn die aus der Sünde entspringende Strafe gefürchtet wird, dass sie nicht gegenwärtig werde, und das Antlitz Gottes, den man verloren, wird nicht gesucht; so ist diese Furcht aus Hochmut entsprungen, nicht aus Demut.“ III. Der heiligen Liebe steht entgegen die Liebe um zeitlichen Lohn; ebenso der keuschen Furcht die knechtische. Die Liebe um zeitlichen Lohn aber ist schlecht; also auch die entsprechende Furcht. 

Auf der anderen Seite ist die knechtische Furcht vom heiligen Geiste, also nicht schlecht; denn zu Röm. 8. sagt die Glosse (Aug. tract. 9. in ep. Johan.): „Der eine einige heilige Geist macht die knechtische und die kindliche Furcht.“

b) Ich antworte; von seiten des Knechtischen her ist die knechtische Furcht schlecht, da sie entgegensteht der Freiheit. Denn wer aus Liebe etwas thut, der thut es von sich selbst aus und nicht getrieben durch die Strafe von außen her. Also gegen die Liebe ist es, was Knechtisches in der knechtischen Furcht sich findet. Wäre also das Knechtische der Wesenscharakter dieser Furcht, so wäre dieselbe schlechthin und ohne weiteres schlecht; wie der Ehebruch schlecht ist, denn seinem Wesen nach ist er gegen die Liebe. Dieses Knechtische aber gehört nicht zum Wesen der knechtischen Furcht ebensowenig wie die Ungeformtheit das Wesen des ungeformten Glaubens bildet. Denn der Gegenstand der knechtischen Furcht ist die Strafe; zu welcher dieses Moment hinzutritt, dass das Gute, dem sie entgegensteht, entweder geliebt wird wie der letzte Endzweck und dass somit die Strafe gefürchtet wird wie das hauptsächliche Übel; und dies hat statt in jenem, der die heilige Liebe in keiner Weise besitzt; — oder dass sie auf den letzten Endzweck wie Zweckdienliches bezogen und somit nicht als Hauptübel gefürchtet wird; dies hat statt in jenem, der die heilige Liebe in sich besitzt. Denn der Wesenscharakter eines Zustandes wird dadurch nicht hinweggenommen, dass der letztere zu einem weiteren Zwecke hinbezogen wird; die knechtische Furcht also ist der Substanz oder dem Wesenscharakter nach gut; aber das Knechtische darin ist schlecht.

c) I. Jenes Wort Augustins bezieht sich auf denjenigen, der etwas aus knechtischer Furcht thut, insoweit diese knechtisch ist; der nämlich in nichts die Gerechtigkeit liebt, sondern nur und einzig die Strafe scheut. II. Nach ihrem inneren Wesenscharakter oder ihrer Substanz gemäß entsteht die Furcht nicht aus Hochmut; sondern nur das Knechtische in derselben, insoweit der Mensch seine Hinneigung nicht der Gerechtigkeit in Liebe unterwerfen will. III. Die Liebe um zeitlichen Lohn widerstreitet an sich der heiligen Liebe und ist deshalb immer schlecht. Die knechtische Furcht aber schließt in ihrer Substanz einzig und allein die Furcht vor der Strafe ein, sei es dass die Strafe als Hauptübel gefürchtet wird sei es dass dies nicht der Fall ist.


** Fünfter Artikel. Die knechtische Furcht und die kindliche sind nicht ein und dasselbe der Substanz nach.

a) Dem steht entgegen: I. Die kindliche Furcht verhält sich zur knechtischen wie der in Liebe geformte Glaube zum ungeformten; trotzdem der eine zusammen mit der Todsünde bestehen kann, der andere nicht. Es bleibt aber immer der inneren Substanz nach der eine nämliche Glaube. Also ist dies auch mit Rücksicht auf die knechtische und kindliche Furcht der Fall. II. Den nämlichen Gegenstand hat die knechtische und kindliche Furcht; nämlich Gott. Also ist es der nämliche Zustand. III. Die gleiche Hoffnung ist es, mit der wir die Seligkeit hoffen und andere, auch zeitliche Güter. Also ist es auch die gleiche Furcht, mit der wir die Trennung von Gott und Strafen von Ihm fürchten. Also ist die knechtische und kindliche Furcht ein und dieselbe der Substanz nach. 

Auf der anderen Seite unterscheidet beide als zwei Arten Furcht Augustin. (9. in 1. Joan.)

b) Ich antworte, das eigens entsprechende Objekt der Furcht sei das Übel. Also muss nach der Verschiedenheit der Übel auch ein Unterschied im Wesenscharakter der Furcht sich finden, da die Zustände sich in ihrem Wesen unterscheiden gemäß den Gegenständen. Das Übel der Strafe nun als Gegenstand der knechtischen Furcht ist wesentlich verschieden vom Übel der Schuld, dem Gegenstande der kindlichen. Also ist auch ein Unterschied vorhanden in der Substanz der entsprechenden Furcht.

c) 1. Der Gegenstand des geformten und ungeformten Glaubens ist der nämliche; der Unterschied ist etwas Äußerliches, nämlich die Anwesenheit und Abwesenheit der heiligen Liebe. Dies ist bei der Furcht nicht der Fall, da ist im Gegenstande ein wesentlicher Unterschied. II. Die Beziehung zu Gott ist verschieden bei beiden Arten Furcht. Die knechtische Furcht betrachtet Gott wie den Urheber der Strafe; die kindliche wie den Abschluß aller Vollendung, von dem sie scheut getrennt zu werden. So ist ja auch im Bereiche des Körperlichen es nicht die wesentlich gleiche Bewegung, die zur weißen Farbe hingeht oder die von ihr sich entfernt. III. Die Hoffnung nimmt Gott den Herrn als das Princip der seligen Anschauung und jedes anderen Gutes. Gott aber ist nicht die Ursache des Übels der Schuld, welches die kindliche Furcht fürchtet; wohl aber Urheber der Strafe, des Gegenstandes der knechtischen Furcht. 


** Sechster Artikel. Die knechtische Furcht bleibt mit der heiligen Liebe.

a) Dies wird bestritten. Denn: I. Augustin (in 1. Joan. tract. 9.) sagt: „Beginnt die Liebe in der Seele zu wohnen, so wird die Furcht fortgetrieben, die ihr den Platz bereitet hat.“ II. Röm. 5. wird gesagt: „Die heilige Liebe Gottes ist ausgegossen in unseren Herzen durch den heiligen Geist;“ und 2. Kor. 3.: „Wo der Geist des Herrn, da ist Freiheit.“ Also ist da nicht mehr knechtische Furcht. III. Die knechtische Furcht wird von der Selbstsucht verursacht, denn die Strafe vermindert das Gute des eigenen Selbst. Die heilige Liebe aber treibt aus die Selbstsucht; sie macht, dass man Gott liebt und sich verachtet, (Aug. 14. de civ. Dei ult.) Also verschwindet beim Eintreten der heiligen Liebe die knechtische Furcht. 

Auf der anderen Seite ist die knechtische Furcht eine Gabe des heiligen Geistes (Art. 4.); also wird sie nicht von der Liebe des heiligen Geistes hinweggenommen.

b) Ich antworte, die knechtische Furcht werde verursacht von der Liebe zu sich selbst; denn sie ist die Furcht vor der Strafe, und somit die Furcht vor Verminderung des eigenen Guten. Also kann die Furcht vor der Strafe in der gleichen Weise bestehen mit der heiligen Liebe wie die Liebe zu sich selbst mit der Liebe Gottes besteht. Denn gleichermaßen liebt und verlangt der Mensch Gutes für sich, wie er dessen Verlust fürchtet. Die Liebe zu sich selbst aber kann sein: 1. der heiligen Liebe entgegengesetzt, insofern jemand den letzten Endzweck in dem einzig seiner Person eigenen Guten sieht; — 2. in der heiligen Liebe eingeschlossen, insofern der Mensch sich in und wegen Gott liebt; — 3. verschieden zwar von der heiligen Liebe, aber nicht gerade ihr entgegengesetzt; insofern jemand wohl das eigene Gut, weil es sein eigen ist, liebt, aber nicht den letzten Endzweck darein setzt. So kann ich auch den Nächsten lieben; nicht gerade um Gottes willen, sondern aus Blutsverwandtschaft, Bequemlichkeit etc., was nicht mit der heiligen Liebe zusammenfällt, aber doch ihr nicht schroff gegenübersteht. So nun verhält es sich entsprechend mit der Furcht vor der Strafe. Denn die Trennung von Gott ist eine Strafe, welche die heilige Liebe im höchsten Grade flieht; das gehört also zur keuschen Furcht. Hier ist die Furcht vor Strafe eingeschlossen in der heiligen Liebe. Flieht aber jemand so das Übel, welches seinem eigenen beschränkten Gute entgegensteht, dass er darin schlechthin das Hauptübel und sonach im eigenen natürlichen Gute den letzten Endzweck sieht; so ist eine solche Furcht schroff entgegengesetzt der heiligen Liebe und besteht somit nicht mit ihr zusammen. Fürchtet schließlich jemand wohl den Verlust des eigenen Gutes, weil dasselbe ihm gehört und nicht auf Grund der Trennung von Gott; aber auch nicht in dem Grade, dass er in diesem eigenen Gute seinen letzten Endzweck erblickt und somit im Verluste desselben das Hauptübel; — so kann eine solche knechtische Furcht mit der heiligen Liebe bestehen und doch ist sie von ihr verschieden. Dabei ist jedoch zu bemerken, dass eine solche Furcht vor der Strafe, die darin nicht das Hauptübel erblickt, nicht eigentlich mehr eine knechtische als solche genannt wird. Somit bleibt die knechtische Furcht als präcis knechtische nicht mit der heiligen Liebe; sondern die innere Substanz nur bleibt, wie auch die Liebe zu sich selbst mit der heiligen Liebe bleibt.

c) Die Einwürfe sprechen von der knechtischen Furcht, insoweit sie präcis knechtisch ist. 


** Siebenter Artikel. Die Furcht ist der Anfang der Weisheit.

a) Dem widerspricht: I. Der Beginn eines Dinges ist bereits dieses Ding selbst. Die Furcht ist aber nicht etwas von der Weisheit; denn letztere ist in der Vernunft, die Furcht im begehrenden Teile. II. Nichts ist das Princip oder der Anfang seiner selbst: „Die Furcht Gottes selber ist aber die Weisheit.“ (Job 28.) III. Dem Beginne geht nichts voran. Der Furcht aber geht der Glaube voran. 

Auf der anderen Seite ist nach Ps. 110.: „die Furcht des Herrn der Anfang der Weisheit.“

b) Ich antworte; als Anfang der Weisheit kann etwas bezeichnet werden, weil es die Weisheit dem Wesen nach beginnt; oder mit Rücksicht, auf die Wirkung der Weisheit. So sind die Kunstprincipien, von denen als von ihrer Richtschnur die Kunst ausgeht der Beginn der Kunst ihrem Wesen nach; das Fundament aber des Baues ist der Anfang der Kunst, in soweit deren Wirkung in Betracht kommt. Die Weisheit nun selber wird von uns in anderer Weise betrachtet wie von den Philosophen. Denn für diese ist sie nur Kenntnis der ersten Ursachen alles Seins. Für uns aber ist sie die praktische Richtschnur für das tätige Leben, um zum letzten Endzwecke zu gelangen. So nun bilden den Beginn der Weisheit, soweit es auf deren Wesen ankommt, die Glaubensartikel; und danach ist der Glaube der Anfang der Weisheit. Mit Rücksicht auf die Wirkung aber ist der Anfang der Weisheit da, von wo die Weisheit anfängt zu wirken; und danach ist die Furcht der Beginn der Weisheit; anders freilich die knechtische Furcht und anders die kindliche. Denn die knechtische Furcht ist der Anfang der Weisheit wie von außen her vorbereitend; aus Furcht vor Strafe nämlich flieht man die Sünde und wird so geeignet für die Wirkung der Weisheit, nach Ekkli. 1.: „Die Furcht des Herrn vertreibt die Sünde.“ Die keusche Furcht aber ist Beginn der Weisheit wie die erste Wirkung der Weisheit. Denn da es zur Weisheit gehört, dass das menschliche Leben geregelt wird nach den in Gott befindlichen Seinsgründen, so muss von da her das Princip genommen werden, dass der Mensch Gott fürchte und Ihm gehorche. Und dann wird folgerichtig in allem Anderen geregelt sein die Furcht gemäß Gott.

c) I. Nicht mit Rücksicht auf das Wesen der Weisheit ist die Furcht ihr Beginn; da ist es der Glaube. II. Die Furcht Gottes ist für das ganze menschliche Leben was die Wurzel für den Baum ist. Deshalb heißt es Ekkli. 1.: „Die Wurzel der Weisheit ist Gott fürchten; ihre Äste dauern lange.“ Wie also die Wurzel der Kraft nach der ganze Baum ist, so ist die Furcht Gottes die Weisheit. III. Der Unterschied ist oben erklärt worden; er regelt sich nach Ekkli. 25.: „Die Furcht Gottes ist der Anfang der Liebe; der Anfang des Glaubens soll damit verbunden werden.“


** Achter Artikel. Die anfängliche Furcht unterscheidet sich der Substanz nach nicht von der kindlichen Furcht.

a) Dies scheint aber. Denn: I. Die kindliche Furcht ist verursacht von der Liebe. Die anfängliche Furcht aber ist bereits das Princip der Liebe selber, nach Elkli. 25.: „Die Furcht des Herrn ist der Anfang der Liebe.“ Also besteht da ein substantieller Unterschied. II. Die anfängliche Furcht hat Scheu vor der Strafe, welche Gegenstand der knechtischen Furcht ist. Also ist sie dasselbe wie die knechtische Furcht. III. Was in der Mitte liegt, ist unterschieden von den beiden Grenzpunkten. Die anfängliche Furcht aber liegt in der Mitte zwischen der knechtischen und kindlichen Furcht. Also ist sie unterschieden von beiden. 

Auf der anderen Seite machen die Unterschiede gemäß dem Unvollkommenen und Vollkommenen keinen Unterschied in der Substanz eines Dinges. Die anfängliche Furcht aber und die kindliche unterscheiden sich gemäß dem Unvollkommenen und Vollkommenen, nach Augustin. (Tract. 9. in 1. Joan.) Also.

b) Ich antworte; die anfängliche Furcht wird so genannt, weil sie der Anfang ist. Da aber sowohl die knechtische Furcht wie auch die kindliche in einer gewissen Weise den Anfang der Weisheit bilden, so kann jede von beiden die anfängliche heißen. So aber wird die anfängliche Furcht nicht betrachtet, insofern sie unterschieden wird von der knechtischen und der kindlichen; sondern danachwie sie dem Stande der Anfänger zukommt, in denen die kindliche Furcht angefangen wird durch den Beginn der heiligen Liebe. Noch nicht aber wohnt ihnen die kindliche Furcht vollkommen inne, weil sie noch nicht zur Vollendung der heiligen Liebe gelangt sind. So verhält sich also die anfängliche Furcht zur kindlichen wie die unvollkommene Liebe zur vollkommenen. Da nun bei dieser, der Liebe, kein substantieller Unterschied obwaltet, so auch nicht in der entsprechenden Furcht; es ist da nur ein Unterschied im Grade ein und desselben Zustandes.

c) I. Die Furcht als Anfang der Liebe ist die knechtische Furcht; welche die Thüre öffnet zur heiligen Liebe, wie Augustin (l. c.) sagt. Soll die anfängliche Furcht es aber sein, so ist sie nicht schlechthin und ohne weiteres der Beginn der Liebe, sondern nur mit Rücksicht auf den Stand der vollkommenen Liebe. II. Die anfängliche Furcht scheut nicht die Strafe als den ihr eigens entsprechenden Gegenstand, sondern insoweit sie mit sich verbunden hat etwas von der knechtischen Furcht, die ja der Substanz nach bleibt zugleich mit der heiligen Liebe; abgesehen freilich vom Moment des Knechtischen. Ihr Akt oder ihre Tätigkeit aber bleibt ebenfalls in unvollkommener Weise mit der heiligen Liebe zusammenbestehen in jenem, der Gutes thut nicht allein aus Liebe zur Gerechtigkeit, sondern auch aus Furcht vor der Strafe. Diese tatsächliche Äußerung der knechtischen Furcht hört erst auf mit der voll kommenen Liebe, „die da hinaustreibt die Furcht.“ (1. Joh. 4.) III. Die anfängliche Liebe liegt nicht in der Mitte zwischen der knechtischen und kindlichen Furcht, als ob die beiden letzteren Arten von Furcht nicht substantiell voneinander verschieden wären, nicht also wie etwas im Bereiche einer einigen Art in der Mitte liegt. Sie liegt vielmehr in der Mitte wie das Unvollkommene in der Mitte liegt zwischen dem Vollkommenen und dem Nichtsein (2 Metaph.), wo jedoch das Unvollkommene dasselbe ist der Substanz nach wie das Vollkommene und durchaus verschieden ist vom Nichtsein. 


** Neunter Artikel. Die Furcht Gottes ist eine Gabe des heiligen Geistes.

a) Dies wird geleugnet. Denn: I. Keine Gabe des heiligen Geistes kann zu einer Tugend im Gegensatze stehen; der heilige Geist wäre ja dann zu Sich selber im Gegensatze. Die Furcht aber steht im direkten Gegensatze zur Hoffnung. Also ist die Furcht keine Gabe des heiligen Geistes. II. Die heilige Furcht hat Gott zum Gegenstande. Also ist sie eine theologische Tugend. III. Die Furcht folgt aus der Liebe, einer theologischen Tugend. Also ist sie ebenfalls eine theologische Tugend. IV. „Die Furcht wird verliehen gegen den Hochmut,“ sagt Gregor. (2. moral. 26.) Dem Hochmut aber steht entgegen die Demut. Also gehört die Furcht zur Tugend der Demut. V. Die Gaben des heiligen Geistes sind vollendeter wie die Tugenden denn „sie werden den Tugenden zum Beistande gegeben,“ nach Gregor (l. c.) Die Hoffnung aber ist vollendeter wie die Furcht; denn sie hat zum Gegenstande das Gute und die Furcht das Übel. Also ist die Furcht keine Gabe des heiligen Geistes. 

Auf der anderen Seite zählt Isaias 11. sie unter den Gaben des heiligen Geistes auf.

b) Ich antworte, die Menschenfurcht sei keine Gabe des heiligen Geistes. Denn „sie war die Ursache, dass Petrus den Herrn verleugnete.“ (Aug. de gratia et lib. arbitr. 13.) Jene Furcht nun aber ist eine Gabe Gottes, von der es Matth. 10. heißt: „Jenen fürchtet, der da Seele und Leib in die Hölle stürzen kann.“ Die knechtische Furcht ist wohl vom heiligen Geiste; aber sie ist keine Gabe des heiligen Geistes. (Aug. de nat. et gratia 57.) Denn sie kann verbunden sein mit dem Willen zu sündigen; was bei den Gaben des heiligen Geistes nicht der Fall ist, da sie niemals ohne die heilige Liebe im Menschen sich finden. Die Furcht als Gabe des heiligen Geistes also ist die keusche Furcht oder die kindliche. Denn (I., II. Kap. 68, Art. 1 und 3) die Gaben des heiligen Geistes sind gewisse zuständliche Vollendungen der Seelenvermögen, kraft deren diese sich durchaus geeignet finden, leicht vom heiligen Geiste in Tätigkeit gesetzt zu werden; wie etwa durch die moralischen Tugenden die begehrenden Vermögen geeignet werden, leicht in Tätigkeit zu kommen durch die Anleitung von der Vernunft aus. Dazu aber, dass etwas in den Zustand gelange, leicht in Tätigkeit gesetzt werden zu können von einer bewegenden Kraft aus, wird zuerst erfordert, dass das betreffende Bewegliche oder das in Bewegung zu setzende Subjekt nicht der Bewegung widerstreite, weil ein solcher Widerstreit des Beweglichen mit Rücksicht auf die bewegende Kraft für die Bewegung ein Hindernis ist. Dies nun, die Hebung des Widerstreites im tätigen Subjekt, besorgt die kindliche Furcht, kraft deren wir vor Gott Ehrfurcht haben und davor zurückschrecken, uns selbst zu verführen. Deshalb hält die Furcht Gottes gewissermaßen die erste Stelle inne unter den Gaben des heiligen Geistes im Aufsteigen, die letzte im Hinabsteigen; nach Augustin. (serm. Dom. in monte 4.)

c) I. Die Hoffnung und die Furcht hängen innig miteinander zusammen und vollenden sich gegenseitig. Denn durch die Furcht fürchten wir nicht, dass uns das mangle, was wir kraft des göttlichen Beistandes zu erlangen hoffen; sondern wir fürchten, uns dem göttlichen Beistände zu entziehen. II. Der hauptsächliche und eigentliche Gegenstand der Furcht ist das Übel, was jemand flieht. Und so ist Gott nicht Gegenstand der Furcht. In dieser Weise, als erstrebenswertes Gut nämlich, ist Er unmittelbar der Gegenstand der theologischen Tugenden. Denn kraft der Tugend der Hoffnung stützen wir uns nicht allein deshalb auf den göttlichen Beistand, damit wir etwelche andere Güter erlangen, sondern an erster Stelle, damit wir Gott besitzen. III. Die Liebe ist wohl das Princip der Furcht. Aber daraus folgt nicht, die Furcht sei kein von der heiligen Liebe verschiedener Zustand. Denn die Liebe ist das Princip aller Zuneigungen der Seele; und doch wird die Seele durch verschiedene Zustände in ihren verschiedenen Neigungen vollendet. Die Liebe hat jedoch deshalb mehr den Charakter der Tugend, weil sie direkt auf das Gute sich richtet, worauf ja gemäß ihrem Wesen die Tugend überhaupt geht; und deshalb ist auch die Hoffnung eine wirkliche Tugend. Die Furcht aber richtet sich in erster Linie auf das Übel und dies erheischt Fliehen; sie ist also etwas weniger als eine theologische Tugend. IV. Die Furcht schließt das Princip des Hochmuts aus, welches ist „abfallen von Gott.“ (Ekkle. 10.) Denn sie lehrt, Gott zu fürchten und Ihm Untertan zu sein. Deshalb ist die Furcht nicht dasselbe wie die Demut, sondern deren Princip. Die Gaben des heiligen Geistes nämlich sind Principien der Tugenden in der Vernunft und der moralischen Tugenden; die theologischen Tugenden aber sind die Principien der Gaben. (I., II. Kap. 68 und 69.) V. Damit beantwortet.


** Zehnter Artikel. Das Wachstum in der heiligen Liebe schließt nicht ein das Minderwerden der Furcht.

a) Das Gegenteil wird behauptet von: I. Augustin: „Je mehr die heilige Liebe wächst, desto mehr nimmt ab die Furcht.“ (l. c.) II. Wächst die Hoffnung, so wird minder die Furcht. Die Hoffnung aber wächst mit der Liebe. III. Die Liebe eint, die Furcht trennt. Wächst also die Einigung, so wird minder die Trennung. 

Auf der anderen Seite sagt Augustin (83 Qq. 36.): „Die Furcht Gottes vollendet die Weisheit, welche an erster Stelle Gott den Herrn liebt und den Nächsten wie sich selbst.“

b) Ich antworte, die kindliche Furcht, welche fürchtet den Vater zu beleidigen und sich von Ihm zu trennen, müsse wachsen mit der heiligen Liebe, wie die Wirkung wächst mit dem Wachsen der Ursache. Denn je mehr jemand seinen Vater liebt, desto mehr hat er Furcht, ihn zu beleidigen. Die knechtische Furcht aber, welche nur auf die Strafe sich richtet, schwindet beim Eintreten der heiligen Liebe ganz, soweit es das rein Knechtische anbelangt; — sie bleibt allerdings der Substanz nach, jedoch mindert sich ihr Akt oder ihre t
tatsächliche Äußerung um so mehr als die heilige Liebe wächst. Denn je mehr jemand Gott liebt, desto weniger hat er acht auf die Strafe; weil er einerseits weniger achtet auf das ihm eigens gehörige Gute und weil er andererseits fester ist im Hoffen auf den ewigen Lohn und somit an die Strafe wenig denkt.

c) I. Augustin spricht von der Furcht vor der Strafe. II. Die Furcht vor Strafe wird minder mit dem Wachsen der Hoffnung, welche uns zuverlässiger die Erreichung des Guten kraft des göttlichen Beistandes erwarten läßt und so vor Gott mehr Ehrfurcht einflößt. III. Die kindliche Furcht schließt kein Trennen ein, sondern vielmehr eine gewisse Unterwürfigkeit unter Gott. Nur insofern besagt sie Trennung, als sie immer weniger es wagt, sich Gott gleich zu dünken und sich Ihm zu entziehen. Dasselbe findet sich in der Liebe, so dass das Wachstum der Liebe diese Furcht vermehrt. 


** Elfter Artikel. Die kindliche Furcht bleibt bestehen in der ewigen Heimat.

a) Das Gegenteil wird bewiesen: I. Prov. 1. heißt es: „Überfluss wird er genießen, kein Übel mehr fürchten.“ Die Furcht richtet sich aber immer auf ein Übel. II. 1. Joh. 3. wird gesagt: „Wenn Er, Gott, erscheinen wird, werden wir Ihm ähnlich sein.“ Gott aber fürchtet nichts. III. Die Hoffnung ist vollkommener wie die Furcht; sie bleibt aber nicht in der Heimat; also die Furcht noch weniger. 

Auf der anderen Seite steht der Ps. 18.: „Die heilige Furcht Gottes bleibt in Ewigkeit.“

b) Ich antworte, die knechtische Furcht, jene nämlich vor Strafe, bleibe keineswegs in der ewigen Seligkeit. Die kindliche Furcht aber wächst mit der heiligen Liebe und wird vollendet werden mit der Liebe. Sie wird sich aber nicht in der nämlichen Weise tatsächlich äußern im Himmel wie jetzt auf Erden. Um darin zur Klarheit zu gelangen, muss man berücksichtigen, dass der Gegenstand der Furcht ein möglicherweise eintreffendes Übel ist wie den Gegenstand der Hoffnung bildet ein Gut als möglich zu erreichen. Und da kleine Übel keine Furcht erregen, die Furcht aber eine Bewegung des Fliehens ist, so schließt die Furcht ein die Flucht vor einem schweren drohenden Übel. Wie aber für jedes Ding das Gute darin besteht, dass es seine durch die Ordnung des Ganzen angewiesene Stelle einhält, so ist es sein Übel, wenn es diese Stelle verläßt. Nun besteht die Ordnung der vernünftigen Kreatur darin, dass sie unter Gott sei und über den übrigen Kreaturen. Wie also das Übel der vernünftigen Kreatur darin besteht, dass sie sich der niedrigeren Kreatur durch die Liebe unterwirft; so auch ist es für sie ein Übel, wenn sie sich Gott nicht unterwirft, sondern in freventlichem Vornehmen Ihn verachtet. Dieses Übel ist für die vernünftige Kreatur, wenn ihre Natur betrachtet wird, stets ein mögliches in Ansehung ihres freien Willens, der von Natur zum Guten oder zum Bösen sich wenden kann; in den Seligen wird es freilich unmöglich, aber nur wegen der vollendeten Herrlichkeit, nicht auf Grund der Natur. Die Flucht also vor diesem Übel, was da ist: Gott nicht Untertan sein, wird vorhanden sein in der ewigen Heimat als möglich mit Rücksicht auf die Natur, als unmöglich mit Rücksicht auf die Seligkeit; — auf dem irdischen Pilgerwege dagegen ist sie immerdar möglich und zwar in jeder Beziehung. Deshalb sagt Gregor (17. moral. 17.) zu Job 27, 11.: „Die himmlischen Kräfte selber, welche Gott den Herrn unaufhörlich anschauen, zittern beim Anschauen Gottes; aber dieses nämliche Zittern, damit es nichts von Strafe an sich habe, ist nicht das Zittern der Furcht, sondern der Bewunderung;“ denn sie staunen über Gott, der über sie erhaben ist und völlig ihnen unbegreiflich. Auch Augustin (14. de civ. Dei 9.) schreibt: „Jene keusche Furcht, welche in die Ewigkeiten der Ewigkeiten hinein bleibt, wenn sie überhaupt im zukünftigen Leben ist, wird keine Furcht sein, der jenes Übel Schrecken einjagt, was da töten kann; sondern eine Furcht, die an jenem Guten festhält, was nicht mehr verloren werden kann. Wo nämlich die Liebe zum erlangten Gute unveränderlich ist; wahrlich, da ist, wenn dies so gesagt werden kann, die Furcht, welche sich vor dem Übel hütet, eine durchaus zuverlässige, nie wankende. Mit dem Namen der keuschen Furcht nämlich wollen wir jenen Willen ausdrücken, kraft dessen es für uns notwendig sein wird, nicht sündigen zu wollen; und zwar nicht etwa als ob unsere Schwäche durch beständige Sorge sich vor Sünde in acht nehmen müsste, sondern weil die feste Sicherheit der Liebe das Sündigen verhütet. Wenn aber da keinerlei solche Furcht etwa sein kann, so ist vielleicht die heilige Furcht deshalb als eine in Ewigkeit dauernde hingestellt, weil dies andauern wird, wohin diese keusche Furcht führt.“

c) I. Nicht die ruhige sichere Furcht ist da ausgeschlossen, sondern die ängstlich sorgende. II. „Die nämlichen Dinge,“ sagt Dionysius (cap. 9.), „sind Gott ähnlich und zugleich Gott unähnlich: ähnlich, weil sie nach ihrem Können den an sich in seiner ganzen Vollendung Unnachahmbaren nachahmen; un ähnlich, weil sie in ihrem minderen Sein nach endlos vielen Beziehungen hin vom Unvergleichlichen sich entfernen.“ Wenn also Gott die Furcht nicht zukommt (der keinen Höherstehenden hat, dem Er sich unterwerfe), so ist damit nicht gesagt, dass sie den Heiligen nicht zukomme. III. Die Hoffnung schließt in sich wesentlich einen Mangel ein, nämlich die Zukünftigkeit der Seligkeit, der natürlich wegfällt durch die Gegenwart der Seligkeit. Die Furcht aber schließt den die Natur notwendig begleitenden Mangel ein, dass sie, die Natur, endlos von Gott fernsteht; und dieser Mangel bleibt auch in den Seligen. Also bleibt irgendwie auch die Furcht.


** Zwölfter Artikel. Der Gabe der Furcht entspricht als Seligkeit die Armut des Geistes.

k) Dagegen wird geltend gemacht: I. Die Furcht ist der Anfang der Weisheit. Die heilige Armut aber ist die Vollendung, nach Matth. 9.: „Wenn du vollkommen sein willst, so gehe hin, verkaufe all das Deinige und gieb es den Armen.“ II. Nach Ps. 118, 120.: „Durchbohre mit Deiner Furcht mein Fleisch,“ entspricht die Abtötung des Fleisches mehr der Furcht; und somit als Seligkeit mehr die Trauer. III. Der Gabe der Furcht entspricht die Tugend der Hoffnung. Dieser aber kommt mehr zu die letzte Seligkeit: „Selig die Friedfertigen, denn sie werden Gottes Kinder genannt werden.“ Denn nach Röm. 5. „rühmen wir uns in der Hoffnung der Kinder Gottes.“ IV. Den Seligkeiten entsprechen die Früchte. Unter den Früchten aber ist keine, welche der Gabe der Furcht zukommt; also entspricht der Furcht auch keine Seligkeit. 

Auf der anderen Seite sagt Augustin (1. serm. Dom. in monte 4.): „Die Furcht Gottes entspricht den Demütigen, von denen gesagt wird: „Selig die Armen im Geiste.“

b) Ich antworte, die Armut des Geistes entspreche recht eigentlich der Furcht Gottes. Denn der kindlichen Fürcht gehört es an, Gott untertan zu sein; was also dieser Unterwürfigkeit folgt, das gehört der Gabe der Furcht an. Ist aber jemand Gott unterworfen, so hört er auf, in sich selbst oder in etwas Anderem seinen Stolz zu suchen; er will nur in Gott allein leben. Deshalb heißt es im Ps. 19.: „Diese in ihren Wagen, jene in ihren Pferden; wir aber wollen anrufen den Namen Gottes.“ Wer also Gott untertan ist, der ist nicht stolz auf sich selber; und nicht auf Ehre und Reichtum, was Alles eben zur Armut des Geistes gehört. Denn darunter ist zu verstehen (nach Augustin l. c.) das Zunichte werden des eigenen stolzen Geistes oder das Verzichten auf zeitliche Güter, was durch den Geist, d. h. kraft des eigenen Willens auf den Antrieb des heiligen Geistes hin, sich vollzieht. (Vgl. Ambrosius zu Luk. 6 und Hieronymus zu Matth. 5.)

c) I. Alle Seligkeiten gehören der Vollendung des geistigen Lebens an; denn „Seligkeit“ besagt etwas Vollendetes. In dieser Vollendung nun ist der Anfang die Verachtung der zeitlichen, äußerlichen Güter. Die Vollendung selbst aber besteht nicht in dem Verzicht auf zeitliche Güter. Die kindliche Furcht ist ja auch verbunden und zusammen mit der Weisheit. II. Der Unterwürfigkeit unter Gott, welche von der kindlichen Furcht kommt, ist mehr entgegengesetzt das Sich-groß-machen entweder in sich selbst oder in äußeren Gütern, wie das fleischliche Ergötzen; welches allerdings, wenn auch in mehr entfernter Weise, ebenfalls der Furcht entgegensteht. Denn wer Gott sich unterwirft und Ihm Ehrfurcht erweist, der freut sich eben in nichts Anderem als in Gott. Das fleischliche Ergötzen nämlich hat nicht den Charakter des Schweren, was zum Wesen der Furcht gehört wie auch zum Wesen des Sich-groß-machens. Deshalb entspricht die Seligkeit der geistigen Armut mehr der Gabe der Furcht als die Trauer. III. Die Hoffnung schließt eine Bewegung in sich ein auf etwas hin als den Abschluß; die Furcht jedoch eine Bewegung von etwas ab. Und deshalb entspricht die letzte Seligkeit besser der Hoffnung als Abschluß und Vollendung der geistigen Vollkommenheit. Die erste Seligkeit aber, welche im Entfernen der äußeren Güter besteht als eines Hindernisses für die Unterwürfigkeit unter Gott, entspricht der Furcht als dem Anfange der Weisheit. IV. Die Bescheidenheit, Genügsamkeit und Keuschheit, jene Früchte also, die einen mäßigen Gebrauch der äußeren Dinge einschließen, entsprechen der Gabe der Furcht.


* II-II, Q. 45 - Gabe der Weisheit

** Erster Artikel. Die Weisheit ist als eine Gabe des heiligen Geistes zu betrachten.

a) Dem widerspricht: I. Die Gaben des heiligen Geistes sind vollkommener wie die Tugenden. Die Tugend aber hat nur zum Guten wie zu ihrem Gegenstande und zu ihrem Endzwecke Beziehung; weshalb Augustin sagt (2. de lib. arbitr. 19.), „niemand bediene sich der Tugenden schlecht.“ Also um so mehr müssen die Gaben des heiligen Geistes nur zum Guten in Beziehung stehen. Die Weisheit kann aber auch schlecht sein, nach Jak. 3.: „Eine gewisse Weisheit ist irdisch, sinnlich, teuflisch.“ Also ist die Weisheit keine Gabe des heiligen Geistes. II. Nach Augustin (12. de Trin. 14.) „ist die Weisheit eine Kenntnis der göttlichen Dinge.“ Nun gehört eine solche Kenntnis, wie die natürliche Vernunft sie haben kann, zu jener Weisheit, die da eine Tugend in der Vernunft ist. Die übernatürliche Kenntnis der göttlichen Dinge aber gehört dem Glauben an. Also ist die Weisheit mehr Tugend wie Gabe des heiligen Geistes. III. Job 28. heißt es: „Siehe die Furcht des Herrn“ oder nach den siebenzig, gemäß denen Augustin citiert „die Hingebung, sie ist die Weisheit; und vom Bösen sich fernhalten, das ist Verständnis.“ Sowohl aber die Furcht wie auch die Hingebung, der timor wie die pietas, sind Gaben des heiligen Geistes. Also ist die Weisheit davon nicht unterschieden und darf nicht als eine besondere Gabe aufgezählt werden. 

Auf der anderen Seite heißt es bei Isai. 11.: „Und es wird ruhen auf ihm der Geist des Herrn, der Geist der Weisheit etc.“

b) Ich antworte, „dem Weisen gehöre es an, die höchste Ursache zu betrachten und vermittelst derselben über das Andere zu urteilen und Alles zu ordnen;“ sagt Aristoteles im Anfange der Metaphysik. Jener also, der die höchste Ursache in einem gewissen Seinsbereiche kennt und gemäß derselben innerhalb dieser Seinsart Alles beurteilen und regeln kann, der wird weise genannt in jenem bestimmt abgegrenzten Seinsbereiche; wie z. B. in der Medizin oder in der Baukunde. Jener aber, der die schlechthin und allseitig höchste Ursache betrachtet, nämlich Gott den Urgrund des All, ist schlechthin weise und urteilt und ordnet in Allem gemäß den göttlichen Regeln. Derartiges Urteil nun erreicht der Mensch durch den heiligen Geist, nach 1. Kor. 2.: „Der Geistige urteilt über Alles;“ denn „der Geist durchforscht Alles, auch die Tiefen der Gottheit.“ Also ist offenbar die Weisheit eine Gabe des heiligen Geistes.

c) I. Gut wird genannt etwas entweder schlechthin als wahrhaft und vollkommen gut; oder gemäß einer gewissen Ähnlichkeit, insofern etwas in der Schlechtigkeit vollkommen ist; und so spricht man von einem guten, vollendeten Räuber. (5 Metaph.) Und sowie in dem Bereiche des wahrhaft Guten eine höchste Ursache besteht, das höchste Gut oder der letzte Endzweck, wegen dessen Kenntnis jemand in Wahrheit weise ist; — so ist auch im Bereiche des Schlechten immer etwas, worauf das Übrige wie auf seinen letzten Endzweck Beziehung hat, durch dessen Kenntnis jemand weise wird, um schlecht zu handeln, nach Jerem. 4.: „Weise sind sie, damit sie schlecht handeln; und gut zu handeln wußten sie nicht.“ Wer nun vom gebührenden Zwecke sich abwendet, der muss sich einem ungebührenden zuwenden; denn jeder, welcher wirkt, nimmt sich einen Zweck vor. Wer also seinen Zweck sich vornimmt in den irdischen Gütern, der hat „irdische Weisheit;“ dessen Zweck die sinnlichen Freuden bilden, der hat „sinnliche Weisheit;“ wer aber im Vorrange vor anderen seinen Zweck sieht, der hat „teuflische Weisheit,“ denn „der Teufel ist der König aller Kinder des Stolzes.“ (Job 41.) II. Die Weisheit als Gabe des heiligen Geistes „kommt von oben“ (Jakob. 3, 14.); die Weisheit als Tugend in der Vernunft ist durch menschliche Mühe erworben. Ähnlich ist der Glaube verschieden von der Weisheit als Gabe des heiligen Geistes. Denn jener stimmt der göttlichen Wahrheit an und für sich zu; das Urteil aber, welches gemäß der göttlichen Wahrheit gefällt wird, gehört dieser, der Gabe der heiligen Weisheit, an. Die Weisheit also setzt den Glauben voraus; „denn jeder urteilt nur darüber gut, was er kennt.“ (1. Ethik.) III. Wie die Hingebung oder Frömmigkeit, welche auf die Gottesverehrung sich bezieht, den Glauben offenbar macht, denn kraft der Gottesverehrung bekennen wir den Glauben; so offenbart diese Hingebung oder Frömmigkeit auch die Weisheit. Ebenso wird dadurch dass jemand Gott fürchtet gezeigt, dass er weise ist. 


** Zweiter Artikel. Die Gabe der Weisheit ist in der Vernunft wie in ihrem Sitze.

a.) Das scheint nicht. Denn: I. Augustin sagt (de gratia N. testamenti ep. 120.): „Die Weisheit ist heilige Liebe;“ also ist sie im Willen; was auch Ekkli. 6, 23. angedeutet wird. II. Die Vernunft wird hinlänglich erleuchtet durch die Gabe des Verständnisses. Also ist da die Weisheit überflüssig. 

Auf der anderen Seite sagt Gregor (2. moral. 26,): „Die Weisheit steht entgegen der Thorheit,“ die in der Vernunft jedenfalls ihren Sitz hat.

b) Ich antworte, Weisheit will sagen eine gewisse Geradheit des Urteils gemäß den göttlichen Regeln. Eine solche Geradheit des Urteils kann nun eintreten: 1. auf Grund des vollkommenen Gebrauches der Vernunft; 2. auf Grund einer gewissen natürlichen Verwandtschaft mit dem, worüber zu urteilen ist. So urteilt über das, was auf die Keuschheit Bezug hat, gut und gerade: 1. wer die Moralwissenschaft vollkommen besitzt; 2. wer die Tugend der Keuschheit vollkommen hat. In der ersten Weise nun über die göttlichen Dinge ein rechtes Urteil haben, gehört der Gabe des Verständnisses an; in der zweiten Weise, also vermittelst einer gewissen natürlichen Verwandtschaft urteilen, dies ist Sache der Gabe der Weisheit; nach Dionysius (2. de div. nom.): „Hierotheus ist in göttlichen Dingen vollkommen; nicht nur weil er sie weiß, sondern weil er sie erfahren hat.“ Solche gewissermaßen natürliche Verwandtschaft aber wird begründet durch die heilige Liebe, nach 1. Kor. 6.: „Wer Gott anhängt; ist ein Geist mit Ihm.“ Die Gabe der Weisheit also hat wohl ihren Grund in der heiligen Liebe, also im Willen; ihr Wesen aber hat seinen Sitz in der Vernunft, deren Tätigkeit es ist, gut zu urteilen.

c) I. Augustinus spricht da von der Weisheit mit Bezug auf ihren Grund. Ekkli. 6. aber läßt kaum ein solches Verständnis zu. Denn wenn da gesagt wird: „Die Weisheit der Lehre ist gemäß ihrem Namen“ und man wollte das so erklären, dass sapientia von sapere (schmecken) kommt, also eine sapida scientia wäre, wonach der Wille als Sitz des Geschmackes, d. h. der Zuneigungen, der Sitz der Weisheit sein sollte, so würde dies eben nur für das Lateinische und schon nicht für das Griechische passen. Besser also ist es, da den Ausdruck „Name“ für „Ruf“, „Berühmtheit“ zu nehmen, wodurch die Weisheit empfohlen wird. II. Die Vernunft hat zwei Tätigkeiten: Auffassen und urteilen. Der ersten entspricht die Gabe des Verständnisses; der zweiten, zu urteilen nach den göttlichen Regeln, entspricht die Weisheit; und zu urteilen nach menschlichen Gründen kommt der Wissenschaft zu.


** Dritter Artikel. Die Gabe der Weisheit ist nicht rein beschaulich, sondern auch auf das Tätigsein gerichtet.

a) Dem steht entgegen: I. Die Gabe der Weisheit steht höher wie die Tugend der Weisheit in der Vernunft. Diese aber ist rein beschaulich. Also ist dies um so mehr die Gabe der Weisheit. II. Die auf das Tätigsein gerichtete, praktische Vernunft hat zum Gegenstande das Zufällige, Zeitliche. Die Weisheit richtet sich auf das Ewige, Notwendige. III. Gregor sagt (6. moral. ult.): „In der Beschauung wird das Princip des All, Gott, gesucht; im Willen aber arbeitet man unter dem schweren Bündel der Bedürfnisse.“ Der Weisheit nun gehört zu das Schauen des Göttlichen und dazu steht in keiner Beziehung das mühevolle Arbeiten; denn Sap. 8. heißt es: „Nicht hat irgend welche Bitterkeit das Zusammenleben mit ihr (der Weisheit); und keinen Ekel bringt hervor der Verkehr mit ihr.“ 

Auf der anderen Seite heißt es Koloss. 4.: „In Weisheit wandelt vor denen, die draußen sind.“ Dies hat aber Bezug auf das Tätigsein.

b) Ich antworte; nach Augustin (12. de Trin. 14.) dient der Betrachtung der Weisheit der höhere Teil, dem Wissen der niedere. „Die höhere Vernunft aber hat auf die ewigen Seinsgründe acht, um sie zu betrachten (das deutet auf den beschaulichen) und sie um Rat zu fragen“ (für das Tätigsein). (l. c. c. 7.) Also ist die Gabe der Weisheit nicht eine rein beschauliche.

c) I. Je höher eine Kraft ist, auf desto weiteren Umfang erstreckt sie sich. Weil also die Weisheit als Gabe des heiligen Geistes höher steht wie die Weisheit als Tugend in der Vernunft und mehr geeignet erscheint, die Seele mit Gott zu vereinen; deshalb ist es ihr eigen, nicht nur das Betrachten zu regeln, sondern auch die menschlichen Tätigkeiten. II. Das Göttliche ist an sich notwendig und ewig; aber es ist zugleich die Richtschnur für das Zeitliche und Zufällige. III. Vorher wird etwas an sich betrachtet als insoweit es zu Anderem in Beziehung steht. Der Weisheit also gehört zuerst an die Betrachtung des Göttlichen, das Schauen des Princips; und auf Grund dessen erst das Leiten des menschlichen Tätigseins gemäß den göttlichen Regeln. Nicht aber kommt Mühe und Bitterkeit in die menschliche Tätigkeit von diesen heiligen Regeln her; sondern vielmehr wird durch die Weisheit alle Bitterkeit des menschlichen Lebens in Süßigkeit verwandelt und die Arbeit in Erquickung und Ruhe.


** Vierter Artikel. Die Gabe der Weisheit kann nicht bestehen ohne die Gnade.

a) Sie kann zusammen mit der Todsünde in der Seele bleiben. Denn: I. Dessen, was man ohne Gnade nicht haben kann, rühmen sich die Heiligen, nach 2. Kor. 1.: „Unser Ruhm ist das Zeugnis unseres Gewissens.“ Der Weisheit aber soll man sich nicht rühmen, nach Jerem. 9, 25. II. Die Kenntnis göttlicher Dinge, welche ja in der Weisheit eingeschlossen ist, kann bestehen mit der Todsünde, nach Röm. 1.: „Die Wahrheit Gottes halten sie fest in der Ungerechtigkeit.“ III. Augustin (15. de Trin. 18.) schreibt über die Liebe: „Nichts ist hervorragender wie dieses Geschenk Gottes; es allein scheidet zwischen den Kindern des ewigen Reiches und den Kindern des Verderbens.“ Die Weisheit ist aber unterschieden von der Liebe. 

Auf der anderen Seite heißt es Sap. 1.: „In eine boshafte Seele tritt nicht ein die Weisheit und sie wohnt nicht in einem den Sünden ergebenen Körper.“

b) Ich antworte, die Weisheit als Gabe des heiligen Geistes bewirke die Geradheit des Urteils über göttliche Dinge oder, kraft der göttlichen Richtschnur, über Anderes gemäß einer gewissen zur Natur gewordenen Verwandtschaft oder Einigung mit dem Göttlichen. Da nun diese Einigung durch die Liebe vollzogen wird, so wird die Liebe von der Weisheit vorausgesetzt und kann somit letztere mit der Todsünde nicht zusammen bestehen.

c) I. Das ist zu verstehen von der irdischen Weisheit, von der die Heiligen bekennen, dass sie selbige nicht haben, nach Prov. 30.: „Die Weisheit der Menschen ist nicht mit mir.“ Der göttlichen Weisheit aber rühmen sie sich, nach 1. Kor. 1.: „Christus ist uns Weisheit geworden von Gott her.“ II. Da ist jene Weisheit gemeint, welche man durch Studium gewinnt; die kann mit der Todsünde bestehen. III. Die heilige Liebe wird von der Gabe der Weisheit vorausgesetzt; mag sie auch verschieden von ihr sein. 


** Fünfter Artikel. Alle, die im Stande der Gnade sind, besitzen die Gabe der Weisheit.

a) Dies scheint falsch. Denn: I. Mehr ist es, Weisheit haben, wie Weisheit hören. Nur Sache der vollkommenen Seelen aber ist es, Weisheit zu hören: „Unter den vollkommenen Seelen sprechen wir Weisheit;“ sagt Paulus. (1. Kor. 2.) Also. II. „Dem Weisen gehört es zu, dass sie urteilen,“ sagt Aristoteles (1 Metaph.); und bei Jakob. 3. heißt es vom Weisen: „urteilend ohne Heuchelei.“ Nur Sache der Vorsteher aber ist es, über andere zu urteilen und sie zu regeln. Also nicht alle, die im Stande der Gnade sind, haben die Gabe der Weisheit. III. „Weisheit wird verliehen gegen die Thorheit,“ schreibt Gregor. 12. moral. 26.) Viele aber, die getauft sind, sind von Natur stumpfsinnig oder dumm und haben trotzdem die Gnade. 

Auf der anderen Seite wird, wer ohne Todsünde ist, von Gott geliebt, weil er die heilige Liebe hat, kraft deren Gott liebt; denn „Gott liebt, die Ihn lieben.“ (Prov. 8.) Sap. 7. aber heißt es: „Gott liebt nur jenen, der mit der Weisheit zusammenwohnt.“ Also ist in allen, die im Stande der Gnade sind, die Gabe der Weisheit.

b) Ich antworte, da die Weisheit eine gewisse Geradheit im Urteilen über Göttliches, sei es um es zu betrachten sei es um als Richtschnur des Lebens zu dienen, einschließt, so seien je nach den verschiedenen Graden der Einigung mit Gott auch verschiedene Grade der Weisheit in den einzelnen. Manche nämlich erlangen diese Geradheit im Urteilen nach beiden Seiten hin nur in dem, was zum Heile notwendig ist; — und das fehlt niemandem, der im Stande der Gnade ist, wie l. Joh. 2. es heißt: „Die Salbung wird euch über Alles belehren.“ Denn wie die Natur im Notwendigen nicht mangelt, so auch um so weniger die Gnade. Andere erkennen rücksichtlich der reinen Betrachtung des Göttlichen Höheres und können es zudem anderen darlegen; ebenso können sie zudem mit Rücksicht auf die Leitung der menschlichen Tätigkeit nicht nur sich selbst leiten, sondern auch andere gemäß den Regeln der göttlichen Weisheit. Und dieser Grad der Weisheit ist nur einigen verliehen und zwar ist das mehr eine zum Besten anderer verliehene Gnade wie die heiligmachende; nach 1. Kor. 12.: „Anderen wird gegeben die Rede der Weisheit.“

c) I. Der Apostel spricht da von der Weisheit, die sich auf die Erkenntnis tieferer Geheimnisse erstreckt: „Wir sprechen Gottes Weisheit im Geheimnisse, die verborgen ist.“ II. Seine eigene Tätigkeit zum Heile hinleiten, ist Sache eines jeden.(Vgl. Dinys. ep. ad Demoph.) III. Die getauften Stumpfsinnigen etc. haben den Zustand der Weisheit; nicht aber dessen Gebrauch. 


** Sechster Artikel. Die siebente Seligkeit entspricht der Gabe der Weisheit.

a.) Dem widersprechen folgende Gründe: I. „Friedfertig sein“ und „Kind Gottes sein“ gehört Beides der heiligen Liebe an.“ Vom Frieden nämlich heißt es Ps. 118.: „Reicher Frieden denen, die Dein Gesetz lieben;“ und von der Kindschaft Gottes sagt Paulus (Röm. 5.): „Die Liebe Gottes ist ausgegossen in unseren Herzen durch den Geist, der uns gegeben worden,“ nämlich „den Geist der Gotteskindschaft, in welchem wir rufen: Abba, Vater.“ (Röm. 8.) II. Die nächste Wirkung der Weisheit ist die heilige Liebe, nach Sap. 7.: „Durch die Nationen hindurch überträgt sich die Weisheit in heilige Seelen und macht Freunde Gottes und Propheten.“ Friede und Gotteskindschaft sind nun jedenfalls erst entferntere Wirkungen, da sie einzig vermittelst der Liebe von der Weisheit ausgehen. Also muss die Seligkeit, welche der Weisheit entspricht, vielmehr die Liebe sein wie Friede und Gotteskindschaft. III. Jakob. 3. heißt es: „Die Weisheit von oben ist zuerst schamvoll, dann friedlich, bescheiden, leicht zu überreden, allem Guten zustimmend, voll von Barmherzigkeit und guten Früchten, urteilend ohne Heuchelei.“ Der Friede ist also nicht mit größerem Rechte die der Weisheit entsprechende Seligkeit wie die anderen Wirkungen. 

Auf der anderen Seite sagt Augustin (1. de serm. Dom. 4.): „Die Weisheit kommt den friedfertigen zu, in denen keine rebellische Bewegung ist, sondern Alles der Vernunft gehorcht.“

b) Ich antworte, sowohl das Verdienst wie der Lohn in der siebenten Seligkeit komme der Gabe der Weisheit entsprechend zu. Denn „friedfertig“ werden genannt, die in sich oder auch in anderen Frieden herstellen; und dies Beides geschieht dadurch, dass Alles der gebührenden Regel unterworfen und so Ordnung gemacht wird. „Frieden ist“ ja nach Augustin „die Ruhe der Ordnung“. Ordnen nun ist eben wesentlich Sache der Weisheit. „Kinder Gottes“ aber werden jene genannt, die und insoweit sie an der Ähnlichkeit mit dem Eingeborenen Sohne Gottes teilnehmen, nach Röm. 8.: „Die Er vorherwußte, dass sie gleich-förmig seien dem Bilde seines Sohnes.“ Der Sohn Gottes nun ist die erzeugte Weisheit. Wer also an der Gabe der Weisheit teilnimmt, der gelangt zur Gotteskindschaft.

I. Der Liebe kommt es zu, Frieden zu haben; ihn ordnend herzustellen ist Sache der Weisheit. Und der heilige Geist wird der Geist der Gotteskindschaft genannt, insoferne durch Ihn uns die Ähnlichkeit verliehen wird mit dem Sohne, „der erzeugten Weisheit“.

II. Da ist die Rede von der ungeschaffenen Weisheit, die zuerst sich mit uns vereint durch das Geschenk der heiligen Liebe und von da aus die Geheimnisse kennen lehrt, deren Erkenntnis die eingeflößte Weisheit ist. Die Gabe der Weisheit also ist nicht die Ursache der Liebe; sondern vielmehr deren Wirkung.

III. In der Regelung menschlicher Tätigkeit, welche ja Sache der Weisheit ist, kommt zuerst die Entfernung jener Übel, die der Weisheit entgegenstehen. Deshalb wird die Furcht „der Anfang der Weisheit“ genannt; denn sie lehrt die Übel vermelden. Und der Friede ist ihr Ende; denn da erscheint Alles in die gehörige Ordnung gebracht. Der Apostel Jakobus also giebt in durchaus zulässiger Weise an, dass die Weisheit, „welche von oben kommt“, die nämlich eine Gabe des heiligen Geistes ist, zuerst „schamhaft“ ist, weil sie das Verderben der Sünde vermeidet, dann „friedfertig“, was die letzte Wirkung der Weisheit ist und somit als Seligkeit dasteht. Alle jene Wirkungen aber, die nun folgen, machen in gebührender Ordnung nur offenbar, durch welche Mittelstufen hindurch die Weisheit zum Frieden führt. Denn der Mensch, der vermittelst der Scham von dem Verderben der Sünde zurücktritt, muss zuerst Maß halten in Allem, soweit es auf ihn ankommt; und dafür steht: „bescheiden“. Dann muss er in dem, wozu seine Kräfte nicht ausreichen, den Belehrungen der anderen sich fügen; deshalb steht: „leicht zu überreden“. Diese beiden Wirkungen tragen dazu bei, dass der Mensch zum Frieden in sich selbst gelangt. Damit er aber zum Frieden mit den anderen gelangt, muss er dem, was diese Gutes haben, nicht widerstreiten; deshalb steht: „dem Guten zustimmend“; — dann muss er Mitleid haben mit den Mängeln anderer; deshalb steht: „voll von Barmherzigkeit und guten Früchten“; — ferner, dass er in Liebe die anderen zu bessern weiß, wenn sie sündigen; deshalb steht: „urteilend ohne Heuchelei“; dass er nämlich nicht unter dem Vorwände zu bessern, seinen Haß befriedigen möchte. 


* II-II, Q. 52 - Gabe des Guten Rates

** Erster Artikel. Die Gabe des Rates ist eine Gabe des heiligen Geistes.

a) Dies ist nicht der Fall. Denn: I. Die Gaben des heiligen Geistes werden verliehen, um den Tugenden beizustehen. (Gregor. 2. moral. 27.) Um zu beraten aber genügt die Tugend der Klugheit oder speciell die des „guten Beratens“, die Eubulia. II. Die zum Besten anderer verliehenen Gnaden werden nicht allen gegeben; die Gaben des heiligen Geistes aber allen, die im Stande der Gnade sind. Die Gabe des Rates nun wird vom heiligen Geiste nur einzelnen verliehen, nach Makkab. 2.: „Siehe da Simon, euer Bruder, er hat guten Rat.“ Also handelt es sich hier nicht um eine der sieben Gaben des heiligen Geistes. III. Röm. 8. heißt es: „Die da vom Geiste Gottes getrieben werden, sie sind die Kinder Gottes.“ Denen aber, welche von einem anderen getrieben werden, kommt der Rat nicht zu. Da also die sieben Gaben des heiligen Geistes zumal den Kindern Gottes gebühren, „die empfangen haben den Geist der Gotteskindschaft,“ so gehört der Rat nicht zu den sieben Gaben des heiligen Geistes. 

Auf der anderen Seite steht die heilige Schrift, Isaias 11, 2.

b) Ich antworte; durch die Gaben des heiligen Geistes wird die Seele in die richtige Verfassung gebracht, um leicht vom heiligen Geiste in Tätigkeit oder in Bewegung gesetzt zu werden. Jegliche Kreatur aber setzt der Herr in Tätigkeit, wie es ihrer Seinsbeschaffenheit zukommt; wie Er die körperliche Kreatur vermittelst der Zeit und des Ortes bewegt, die rein geistige aber nur vermittelst der Zeit und nicht des Ortes. (Aug. 8. sup. Gen. ad litt. 28.) Nun ist es eigen der vernünftigen menschlichen Natur, dass sie vermittelst vernünftiger Untersuchung zum Tätigsein übergeht; und dieses Untersuchen heißt Beraten. Also bewegt der heilige Geist die menschliche Kreatur vermittelst des Rates; und danach giebt es eine Gabe des heiligen Geistes, die man „Rat“ nennt.

c) I. Soweit die Vernunft begreifen kann, leitet die Klugheit und was damit zusammenhängt, sei sie erworben oder von oben eingeflößt. Weil aber die menschliche Vernunft das Einzelne und Besondere, was da begegnen kann, nicht zu begreifen vermag, so „sind unsere Gedanken furchtsam und ungewiß unsere Voraussicht.“ (Sap. 9.) Also muss der Mensch in seinem Untersuchen von Gott unterstützt werden, der Alles begreift, und dies geschieht durch die Gabe des Rates; wie ja auch im Bereiche des Menschlichen man von den Weiseren sich Rats erholt. II. Es kann dies eine zum Besten anderer verliehene Gnade sein, dass jemand auch anderen guten Rat geben kann. Dass aber der Mensch guten Rats sich erfreut in dem zu seinem eigenen Heile Notwendigen, dies ist der Gabe des Rats gedankt; und diese ist in allen, die im Stande der Gnade sind. III. Die Kinder Gottes werden nach ihrer Weise, d. h. unter Wahrung ihres freien Willens, von Gott geführt. Insoweit also die Vernunft vom heiligen Geiste bewegt oder belehrt wird für die entsprechende Tätigkeit, gebührt den Kindern Gottes die Gabe des Rates. 


** Zweiter Artikel. Die Gabe des Rates entspricht der Tugend der Klugheit.

a) Dies wird geleugnet. Denn: I. „Das Niedrigere berührt in seinem höchsten Teile das höher Stehende,“ heißt es bei Dionysius (7. de div. nom.), wie der Mensch in seinem Höchsten den Engel berührt, nämlich in der Vernunft. Nun ist die Tugend der Klugheit tiefer wie die Gabe des heiligen Geistes; nicht aber ihr Höchstes, sondern ihr Niedrigstes ist das „gute Beraten“, ihr Höchstes ist ja das Vorschreiben. Also entspricht nicht dem „Beraten“ und somit nicht der Klugheit die Gabe des Rates. II. Bereits die Gabe der Wissenschaft steht der Klugheit bei. Also ist die Gabe des Rates für die Klugheit überflüssig. III. „Leiten“ gehört zur Klugheit. Zur Gabe des Rates aber gehört, dass der Mensch von Gott geleitet werde und nicht selber leite. 

Auf der anderen Seite beschäftigt sich die Gabe des Rates mit dem Zweckdienlichen. Darauf ist aber die Klugheit gerichtet.

b) Ich antworte, das niedrigere Princip werde vollendet dadurch, dass es vom höheren Princip in Tätigkeit gesetzt oder bewegt wird; wie z. B. der Körper dadurch dass ihn die Seele belebt. Die menschliche Vernunft steht aber offenbar zur göttlichen im Verhältnisse des niedrigeren Princips zum höheren; denn die göttliche Vernunft ist die höchste Regel für die menschliche Geradheit. Also wird die Klugheit, welche die Geradheit der Vernunft besagt, im höchsten Grade unterstütztund vollendet dadurch, dass sie vom heiligen Geiste geregelt und bewegt wird. Letzteres aber entspricht der Gabe des Rates. Also entspricht letztere der Klugheit.

c) I. Urteilen und Vorschreiben ist Sache des regelnden und bewegenden. Durch die göttlichen Gaben aber wird der Mensch geregelt und bewegt von seiten des heiligen Geistes. Also durfte die Gabe des Rates nicht dem Vorschreiben speciell oder dem Urteilen entsprechen, sondern dem Beraten; insofern der menschliche Geist bewegt wird durch den Rat eines anderen. II. Die Gabe der Wissenschaft entspricht als im Bereiche des Beschaulichen befindlich nicht direkt der Klugheit; wohl aber steht sie ihr bei. Die Gabe des Rates als auf den nämlichen Gegenstand gerichtet entspricht direkt. III. Daher eben weil der menschliche Geist von Gott her in Bewegung gesetzt wird, steht er als geeignet da, sich und andere zu leiten. 


** Dritter Artikel. Die Gabe des Rates bleibt im ewigen Heim.

a) Dies scheint unmöglich. Denn: I. Der Rat betrifft das Zweckdienliche. Im Himmel aber besitzt man den Endzweck. II. Das Beraten setzt Zweifeln voraus (3 Ethic. 3.); was im Himmel nicht statthat. III. Im ewigen Heim sind wir Gott gleichförmig (1. Joh. 3.), der keines Rates bedarf. (Röm. 2, 34.) 

Auf der anderen Seite sagt Gregor (17. moral. 8.): „Wenn eines jeden Volkes Schuld oder Gerechtigkeit vor dem Rate des himmlischen Hofes erscheint, dann sagt man, der diesem Volke vorgesetzte (Engel) hätte im Streite gesiegt oder sei unterlegen.“

b) Ich antworte, hier müsse erwogen werden, dass das Bewegliche in einer anderen Verfassung sei, während es noch in Bewegung; und in einer anderen, wenn es am Abschlusse angelangt ist. Und wenn nun der bewegende das Princip der Bewegung allein ist, so hört die Tätigkeit desselben mit Rücksicht auf das Bewegliche auf, sobald letzteres mit der Bewegung aufhört; wie die Tätigkeit des Baumeisters aufhört, wenn das Haus gebaut ist. Ist aber der bewegende nicht die Ursache der Bewegung allein, sondern auch die Ursache der Form selber, bis zu welcher die Bewegung geht; dann hört nicht die Tätigkeit des bewegenden mit der Bewegung des Beweglichen auf, auch nachdem die Form eingeprägt ist; wie z. B. die Sonne tätig bleibt im Erleuchten der Luft, auch nachdem diese erleuchtet worden ist. Und in dieser letzten Weise verursacht in uns Gott sowohl die Tugend wie die Kenntnis; nicht allein bis wir sie erlangt haben, sondern auch so lange wir darin verharren. Danach also verursacht Gott in den Seligen die Kenntnis des zu Thuenden; nicht als ob letztere darüber in Unkenntnis wären, sondern weil seine erleuchtende Tätigkeit beständig die Fortdauer der Kenntnis dessen, was zu thun ist, verursacht. Manches aber, was nicht notwendig zum Wesen der Seligkeit gehört, kennen weder die Engel noch die seligen Menschen; nämlich was sich auf die Leitung der Dinge gemäß der göttlichen Vorsehung erstreckt. Und da ist zu berücksichtigen, dass der Geist der Seligen in anderer Weise von Gott bewegt wird wie der Geist der noch Pilgernden. Denn der letztere wird in der Weise bewegt, dass die Ängstlichkeit des vorhergehenden Zweifelns beruhigt wird, während im Geiste der Seligen mit Rücksicht auf das, was sie nicht kennen, eben ein einfaches Nichtwissen ist ohne jegliche Unruhe, von dem dann die Engel durch die Erleuchtung seitens Gottes und vermittelst der höheren Engel gereinigt werden, nach Dionysius. (7. coel. hier.) Gott um Rat fragen bedeutet bei ihnen kein Untersuchen, um den Zweifel zu verscheuchen; sondern einfach ein Zuwenden zu Gott, wie Augustin (5. sup. Gen. ad litt. 19.) schreibt: „Die Engel befragen Gott über das Niedrigere.“ Und die Erleuchtung darin seitens Gottes wird „Rat“ genannt. Danach also ist in den Seligen die Gabe des Rates, insoweit die Fortdauer ihrer Kenntnis von seiten Gottes verursacht; und der Geist darüber, was er rücksichtlich des zu Thuenden nicht weiß, erleuchtet wird.

c) I. Auch in den Seligen sind einige Tätigkeiten, die zum Zwecke hingeordnet sind oder vielmehr, die von der Erreichung des Zweckes her ausgehen; wie dass sie Gott loben oder dass sie andere zu Gott ziehen, also z. B. die Gebete der Heiligen und die Dienste der Engel. Mit Bezug darauf haben sie die Gabe des Rates. II. Das Zweifeln gehört zur Gabe des Rates hier auf dem Pilgerwege; wie ja auch die Kardinaltugenden in der Heimat nicht durchaus die gleichen Tätigkeiten haben wie auf Erden. III. Der Rat ist in Gott wie im Gebenden. Die Heiligen sind Gott gleichförmig, insoweit sie denselben empfangen. 


** Vierter Artikel. Die fünfte Seligkeit entspricht der Gabe des Rates.

a) Dem steht entgegen: I. Alle Seligkeiten sind gewisse Tugendakte. Durch den Rat werden wir aber in allen Tugendakten geleitet. Also nicht mehr wie jede andere entspricht die Barmherzigkeit dem Rate. II. Vorschriften werden über das zum Heile Notwendige gegeben. Der Rat betrifft das zum Heile nicht Notwendige. Die Barmherzigkeit nun ist zum Heile notwendig, nach Jakob. 3.: „Ein Gericht ohne Barmherzigkeit wird ergehen über jenen, der nicht Barmherzigkeit geübt hat.“ Die Armut aber ist Gegenstand des Rates nur. Also ist die Armut vielmehr der Gabe des Rates entsprechend wie die Barmherzigkeit. III. Die Früchte folgen den Seligkeiten; denn sie enthalten die Annehmlichkeiten, welche im Tugendakte eingeschlossen sind. Unter den Früchten (Gal. 5.) aber entspricht keine der Gabe des Rates. Also entspricht ihr auch keine Seligkeit. 

Auf der anderen Seite sagt Augustin (1. de sserm. Dom. 4.): „Der Rat kommt den barmherzigen zu; denn das einzige Heilmittel, um aus so großen Gefahren befreit zu werden, besteht darin, zu geben und zu verzeihen den anderen.“

b) Ich antworte, der „Rat“ betreffe das zum Zwecke Nützliche. Die Barmherzigkeit aber ist im höchsten Grade zum Zwecke nützlich, nach 1. Tim. 4.: „Die Hingebung ist zu Allem nützlich.“ Also entspricht im besonderen der Gabe des Rates die Seligkeit der Barmherzigkeit; insoweit die Gabe des Rates dazu anleitet, nicht als ob sie die Barmherzigkeit selber übte.

c) I. In besonderer Weise leitet die Gabe des Rates zu Werken der Barmherzigkeit an. II. Mag es notwendig sein oder nicht, in Allem, was zum ewigen Leben Beziehung hat, leitet uns die Gabe des Rates; nicht jedes Werk der Barmherzigkeit aber ist zum Heile notwendig. III. Die „Frucht“ hat den Charakter des Letzten. Im Bereiche des Tätigseins aber ist das Letzte nicht im Gedanken, sondern im Wirken als dem Zwecke. Deshalb steht unter den Früchten keine, welche sich auf die praktisch tätige Erkenntnis richtete; sondern nur solche, welche auf die von der praktischen Kenntnis geleiteten Tätigkeiten sich richten; darunter befinden sich die Güte und das Wohlwollen, die der Barmherzigkeit entsprechen. 

* II-II, Q. 121 - Gabe der Frömmigkeit

** Erster Artikel. Die Hingebung oder Frömmigkeit (pietas) ist eine Gabe des heiligen Geistes.

a) Dies scheint nicht. Denn: I. Die Hingebung ist eine Tugend. (Kap. 101, Art. 3.) Die Tugenden aber sind unterschieden von den Gaben des heiligen Geistes. (I., II. Kap. 68, Art. 1.) II. Die Gaben des heiligen Geistes stehen voran den Tugenden. Unter den Teilen der Gerechtigkeit aber ist der hervorragendste die Tugend der Religion oder Gottesverehrung. Also muss diese vielmehr als Gabe des heiligen Geistes genannt werden. III. Die Gaben des heiligen Geistes bleiben im ewigen Heim. (I., II. 68, Art. 6.) Der Akt der Hingebung aber kann da nicht bleiben; denn „die Hingebung füllt das Innere an mit den Werken der Barmherzigkeit.“ (Nach 1. moral. 16.) 

Auf der anderen Seite steht die Stelle bei Isaias 11.

b) Ich antworte, die Gaben des heiligen Geistes seien gewisse Verfassungen oder Vorbereitungen in der Seele, kraft deren diese etwas vom heiligen Geiste leicht in Tätigkeit zu Setzendes wird. Nun bewegt und bestimmt uns auch u. a. der heilige Geist dazu, dass wir eine kindliche Hinneigung haben, nach Röm. 8, 15. Weil also der Hingebung es im eigentlichen Sinne zukömmt, dem Vater Verehrung und Dienste zu erweisen, so folgt, dass jene Hingebung, kraft deren wir Gott, als unserem Vater, Ehre und Dienst darbringen und zwar auf den Antrieb des heiligen Geistes hin, eine Gabe des heiligen Geistes ist.

c) I. Die Hingebung als Tugend dient dem Vater dem Fleische nach und ehrt ihn; die Hingebung als Gabe des heiligen Geistes thut dies Gott gegenüber als unserem Vater. II. Gott verehren als den Schöpfer und Ihm so einen Kult darbringen, wie dies die Tugend der Religion thut, steht voran der Hingebung dem fleischlichen Vater gegenüber und dieses Letztere ist die Tugend der Hingebung. Gott verehren aber als unseren Vater ist noch weit hervorragender wie Ihn verehren als Herrn und Schöpfer. Die Hingebung als Gabe des heiligen Geistes also steht höher wie die Tugend der Gottesverehrung oder der Religion; diese letztere aber steht höher wie die Tugend der Hingebung. III. Wie kraft der Tugend der Hingebung jemand nicht nur den Vater dem Fleische nach ehrt und ihm dient, sondern auch den blutsverwandten, soweit sie zum Vater gehören; — so erweist die Gabe der Hingebung nicht nur Gott als unserem Vater Ehre und Dienst, sondern auch den anderen Menschen, insoweit diese zu Gott gehören. Dahin gehört also: die Heiligen ehren; der heiligen Schrift, sei sie verstanden oder nicht verstanden nicht widersprechen; und Ähnliches. (Vgl. Aug. 2. de doctr. christ. 7.) Infolgedessen kommt die Gabe der Hingebung auch den notleidenden um des himmlischen Vaters willen zu Hilfe. Und obgleich, zumal nach dem letzten Gerichte, diese letztere Tätigkeit im ewigen Heim nicht statthaben wird; so doch diese erstere, nämlich Gott kindlich verehren; wie es Sap. 5. heißt. 


** Zweiter Artikel. Der Gabe der Hingebung entspricht die zweite Seligkeit.

a) Das Gegenteil erhellt aus Folgendem: I. Die Hingebung ist eine Gabe des heiligen Geistes, die zur Gerechtigkeit in Bezug steht. Dieser aber entspricht die vierte Seligkeit; oder auch die fünfte, denn die Werke der Barmherzigkeit gehören zur Hingebung. (S. ob.) II. Die Gabe der Hingebung wird geleitet durch die Gabe der Wissenschaft, welche zu ihr in der Aufzählung des Propheten hinzugefügt erscheint. Da also zur Wissenschaft die dritte Seligkeit gehört, so scheint zur Hingebung nicht die zweite gehören zu können. Denn das Leitende muss sich auf dasselbe richten, wie das Geleitete. III. Die Früchte entsprechen den Seligkeiten und Gaben. Unter den Früchten aber gehören die Güte und Wohltätigkeit mehr zur Hingebung wie die Sanftmut. Also entspricht der Hingebung nicht die zweite Seligkeit. 

Auf der anderen Seite sagt Augustin (1. de serm. Dom. in monte 4.): „Den sanftmüthigen entspricht die Hingebung.

b) Ich antworte, die Seligkeiten kommen mit den Gaben des heiligen Geistes überein 1. auf Grund der Ordnung, wie Augustin danach bestimmt, indem er die erste Seligkeit zuteilt der niedrigsten und letzten Gabe des heiligen Geistes, die zweite Seligkeit der nächstniedrigen Gabe des heiligen Geistes; also die Sanftmut zuteilt der Hingebung; — 2. auf Grund des inneren Wesens der Gaben und Seligkeiten; und danach muss man die Gaben den Seligkeiten anpassen gemäß den entsprechenden Gegenständen und Tätigkeiten. In dieser letzten Weise würde nun der Hingebung mehr entsprechen die vierte und fünfte Seligkeit wie die Sanftmut. Diese letztere aber hat eine gewisse Verwandtschaft mit der Gabe der Hingebung; denn durch die Sanftmut werden die Hindernisse für den Akt oder die Tätigkeit der Hingebung entfernt.

c) I. Damit beantwortet. II. Gemäß der inneren Eigentümlichkeit der Gaben und Seligkeiten muss die nämliche Seligkeit der Wissenschaft und Hingebung sprechen; gemäß der Ordnung in der Aufzählung aber und auch gemäß einer gewissen Verwandtschaft untereinander kann eine andere Seligkeit jeder von den beiden Gaben entsprechen. III. Die Güte und die Wohltätigkeit entsprechen in den Früchten direkt der Hingebung; die Sanftmut indirekt, wie eben gesagt. 

* II-II, Q. 139 - Gabe der Stärke

** Erster Artikel. Die Stärke ist eme Gabe des heiligen Geisten

a) Dagegen spricht Folgendes: I. Die Stärke ist eine Tugend; also keine Gabe des heiligen Geistes. II. Die Tätigkeiten der Gaben bleiben im Himmel; nicht aber die Tätigkeit der Stärke; „denn sie giebt Zuversicht gegen die Übel,“ deren keine im Himmel sind. III. Augustin sagt (2. de doctr. christ. 7.): „Sache der Stärke ist es, von aller Annehmlichkeit der vergänglichen Güter sich selbst zu trennen.“ Also entspricht die Gabe der Stärke vielmehr der Tugend der Mäßigkeit wie der Tugend der Stärke. 

Auf der anderen Seite steht Isaias 11.

b) Ich antworte, die Stärke besage eine gewisse Festigkeit der Seele. Diese aber erstreckt sich sowohl auf das Gute, was man thun, wie auf die Übel, die man ertragen soll; zumal wenn mit Beidem der Charakter des schwer Erreichbaren verknüpft ist. Kommt nun die der Natur entsprechende Weise in Betracht, so kann nach beiden Seiten hin der Mensch diese Festigkeit haben; dass er nämlich nicht vom Guten absteht wegen der auftauchenden Schwierigkeiten oder wegen eines bedeutenden Übels. Und danach besteht die Tugend der Stärke. Weiter aber wird die Seele des Menschen bewegt vom heiligen Geiste, dass er zum letzten Ende oder zum schließlichen Zwecke des angefangenen Werkes komme und allen entgegentretenden Gefahren entgehe; denn das übersteigt die menschliche Natur. Bisweilen nämlich liegt es nicht in der Macht des Menschen, dass er das Ende seines Werkes erreiche oder die Gefahren vermeide, da er oft vorher dem Tode unterliegt. Das wirkt aber dann der heilige Geist im Menschen, indem Er ihn zum ewigen Leben geleitet; d. h. zum letzten Endzwecke aller guten Werke und der Beendigung aller Gefahren. Und danach hat Bestand die Stärke als Gabe des heiligen Geistes; indem der heilige Geist eine gewisse Zuversicht der Seele einflößt, welche die gegenteilige Furcht zerstreut.

c) I. Die Stärke als Tugend festigt den Menschen, um alle Gefahren zu ertragen; aber sie giebt nicht die Zuversicht, schließlich allen zu entgehen. Dies gehört der Stärke als einer Gabe des heiligen Geistes an. II. Die Tätigkeit der Gabe der Stärke im Himmel ist eine andere wie die auf Erden; nämlich das Genießen der vollen Sicherheit vor allen Gefahren. III. Die Gabe der Stärke berücksichtigt die Tugend der Stärke nicht allein im Ertragen von Gefahren; sondern auch in Allem dem, was für das menschliche Thun schwer erreichbar ist. Und deshalb wird die Gabe der Stärke gelenkt von der Gabe des Rates. 


** Zweiter Artikel. Die vierte Seligkeit entspricht der Gabe der Stärke.

a) Es scheint dies nicht. Denn: I. Die Gabe der Stärke entspricht nicht der Tugend der Gerechtigkeit, sondern vielmehr die Gabe der Hingebung oder Pietät. Hungern aber und dürsten nach der Gerechtigkeit ist ein Akt der Gerechtigkeit. Also entspricht, die vierte Seligkeit vielmehr der Gabe der Hingebung oder Pietät, wie der Gabe der Stärke. II. Hunger und Durst nach der Gerechtigkeit ist die Sehnsucht nach dem Guten. Das aber gehört zur heiligen Liebe; welcher die Gabe der Weisheit, nicht die der Stärke entspricht. III. Die Früchte folgen den Seligkeiten; da zur Seligkeit das Ergötzen gehört. Unter den Früchten aber erscheint keine, welche der Stärke entspräche; also entspricht ihr auch keine Seligkeit. 

Auf der anderen Seite sagt Augustin (I. de serm. Dom. 4.): „Die Stärke kommt den hungernden und dürstenden zu; denn sie arbeiten im Verlangen nach den wahren Gütern und sehnen sich danach, ihre Liebe abzuwenden vom Irdischen und Körperlichen.“

b) Ich antworte, Augustin folge der Ordnung in der Aufzählung der Gaben und Seligkeiten; nimmt aber immer als Grundlage eine gewisse Ähnlichkeit. Und so teilt er die vierte Seligkeit der vierten Gabe zu. Es herrscht da auch tatsächlich eine gewisse Ähnlichkeit. Denn die Stärke besteht im schwer Erreichbaren. Es ist aber etwas sehr Schwieriges, dass jemand nicht nur tugendhafte Werke, Werke der Gerechtigkeit also, vollbringt; sondern dass er sie auch mit einer gewissen unersättlichen Sehnsucht vollbringt, was der Hunger und Durst nach der Gerechtigkeit bezeichnet.

c) I. „Gerechtigkeit“ kann hier nach Chrysostomus als die allgemeine Gerechtigkeit genommen werden, welche sich auf alle Tugendwerke erstreckt; und in diesen Tugendwerken richtet sich die Stärke auf das schwer Erreichbare. II. Die heilige Liebe ist die Wurzel aller Gaben und Tugenden. III. Die Geduld unter den Früchten entspricht der Gabe der Stärke und die Langmut.


