#+title:      Konferenz Seekirchen
#+date:       [2026-04-23 Do 16:20]
#+filetags:   :schule:
#+identifier: 20260423T162048

* Siedeln

Plätze im neuen Konferenzzimmer per Los verteilt. 

* Neubau - Pausenaufsicht

Ich - Mo 2x Garderobe (Früh + P2) + Mi P1 Neubau 1. Stock

Was dürfen Schüler in Garderobe (nicht)?

* Allfälliges

Snoozen oder vapen - was tun? Was können wir tun? Einheitliche Regelung? Wenn ein Schüler erwischt wird - wir können keine Anzeige machen (bei verbotenen Substanzen - laut Gesetz)?

Wenn wir eh keine Handhabe haben - dann können wir es eh bleiben lassen? Verbotene Substanz abnehmen und Eltern informieren; Eltern müssen die Substanzen abholen. Schlechtere Betragensnote + bei Fahrten nicht mitnehmen? Rüge durch KV und Direktion. 

Die Großen (Burschen) können oft ihr Geschäft nicht verrichten, weil die Kleinen oben drüber schauen.

* Hauptfächer

Manchmal werden Klassen geteilt - KV erstellt Raumplan für seine Klasse; ersichtlich, wann der Klassenraum leer ist - kann von jemand anderen genutzt werden. Sollte was kaputt sein - weiß man, wer es war.

Wann ist eine Klasse nicht ihrem Raum: Sport, Werken, Zeichnen, Kochen, (BU, PH, CH), ...?

Leider wird etwas kaputt, Dinge verschwinden, Kaugummis, ....: erstens ist es leichter, den "Schuldigen" zu finden, die Schüler räumen ihre Sachen weg, wenn Fremde kommen; und wer vom Sport zurück kommt, dann warten, bis der L ihre Klasse verlässt. 

* KEL Gespräche

2 pro Jahr verpflichtend / nur so wäre es regelmäßig; kann auch am Elternsprechtag sein. Nur KV, oder jeder Lehrer muss? einmal KV, das 2. Mal ein anderer Lehrer?

Oder wir bleiben beim Alten: 2 Elternsprechtage - und ein KEL pro Jahr. Das KEL ist ein Angebot.  

* IKM+ (D,E,M)

Dezember 2026 - Modul Lesen leicht - wer schwach im Lesen ist.

 
* Reisekostenabrechnungen

FB - 3 Wochen vorher angeben
+ Spesen: Öffis / Bef.zusch. priv. KFZ / km-Geld (nur bei Genehmigung durch Direktion)

* WebUntis: Bitte aktuell halten. 

* Allfälliges

** Mehrtägige SV

Absprache

** QMS Konferenz Mai

** Prozessblätter an Iris

** Gratulation an Kollegen wegen sportliche Erfolge

- Turn10 2x LM
- VB Mädchen 3.
- VB Burschen 5.
- FB Bezirksmeister SL
- Gütesiegel Sport Gold
- Expertschule
- BO Schule
- Kids save lifes
- Zert. Schulhunde Schule


** Wettkämpfe va im Mai

3 BM an drei Tagen an drei verschiedenen Orten ...

* Schulfremde Personen

Über Lift in die Schule (Musikum). 




