#+title:      Day 210: Speaking God's Word (2026)
#+date:       [2026-07-29 Mi 21:50]
#+filetags:   :bibel:
#+identifier: 20260729T215020

* Source 

#+begin_quote
Fr. Mike compares the messages of Isaiah and Ezekiel, one coming from a pre-exile time and the other from a post-exile time. Even though they are coming from two very different points in salvation history, they both are persistent in speaking the Word of God, and sharing his consolation with the people of Israel. Today's readings are Isaiah 41-42, Ezekiel 2-3, and Proverbs 12:1-4.
#+end_quote

https://bibleinayear.fireside.fm/day-210-2026

* Notes

** Isaiah 41-42
Fürchte dich nicht! Ich bringe dich zurück! - Jesaja sagt das VOR dem Exil.

Erstes Lied über den Knecht des Herrn; 

** Ezekiel 2-3

Menschensohn - über 90mal.

Gottes Geist erfasst Ezekiel. 

4mal die Vision Gottes; gibt mit seinem Leben Zeugnis über die Treue Gottes und der Untreue des Volkes Israel. Er wird im Auftrag Gottes "komische" Dinge tun. Sprich - ob sie hören wollen oder nicht. Du kannst kontrollieren, was du tust, aber nicht was andere tun. 

** Proverbs 12:1-4


