#+title:      Eröffnungskonferenz Mattsee
#+date:       [2026-09-14 Mo 11:08]
#+filetags:   :schule:
#+identifier: 20260914T110848

* Eröffnung

* Zwei neue Kollegem

Julian / Gregor

* Allfälliges

* Marktplatz Learn App

Budget pro Schule, wird es nicht genutzt - Geld ist weg. Achtung: Kosten oft pro Schüler!

* FB Anmeldung (20.09. ?)

* Vertrauenslehrer (für Schüler)

<2026-10-13 Di>-<2026-10-15 Do>

* Kinderschutz

* Brandbeauftragter?

* Standard / AHS

Einteilung in zwei Wochem: <2026-09-28 Mo>
Jetzt aber schon: welcher L welche Gruppe

* Entschuldigungen
Unverzüglich!

* Handyverbot
Snooze, AI Brille (sieht wie eine normale Brille aus, hat aber Kameras, kann aufnehmen, im Glas ist es wie ein Overhead Display, ...), Smartwatches, ...

* Parkplatz

* Schlüsselsystem
sondern nur mit Chips. 

* Bis Dezember
Was können wir noch übers Budget finanzieren? Budget aufbrauchen.

* Verhaltensregeln NEU

* Termine

** Londonreise
22 Schüler bleiben da;

** Herbstferien
Do, 24.09. + (Mo 26.10.) Di, 27.10. - Sa, 31.10. (bis Mo 2.11.)

** BO Tage
23.-25.11.2026

** Schulaotonom
7.12. Elternsprechtag
7.5. und 28.5. (Himmelfahrt und Fronleichnam)

** Skikurs 2. Klassen
14.12.-18.12.2026

** Weihnachten
24.12.-6.1.

** Semesterferien
Mo, 15.02. - Sa, 20.02. 

** Osterferien
Sa, 20.03. - Mo, 29.03. 

** Wienwoche (4.) + Sportwoche (3.) + Kennenlerntage (1.)
Nur die zweiten Klassen im Haus.
18.-21. Mai 2026

* Stundenplan
Englandwoche ist "etwas" zu früh; für Supplierungen.

** Pausenaufsicht
vorübergehend für morgen, bis morgen 10h00
4 Aufsichten für volle LV

- kein Stockwerk Wechsel
- raus gehen? nur wenn es trocken ist
- Aufsicht: draußen (einer der zwei, die unten Aufsicht haben)

** EDV Konto anlegen
aktivieren, besonders 1. Klassen.

** Sokrates
ab 29.9. nur mehr über ID Austria (Bildungsportal)
(Grund: in einer HTL [Sbg] wurden alle Noten gehackt bis zur Matura)

Teacher Assistent / ebenfalls über ID Austria: erst ab 2 SW, ca Dienstag
1 SW: entfällt, 1. SW, ...

** Microsoft Teams
alles angelegt (Lehrer / Direktor)
bis 27.9. Teams anlegen, nachher nicht mehr.
(System Namen? Fach Klasse Name des L.)

** Stammdaten
Vater *und* Mutter von jedem Schüler

** SchoolFox
alles aktuell
Einladungslinks für 1. Klassen
Stimmen die Schüler Namen?

** Homepage
Fotos? Wandertag!
Lehrerfotos (für die Kontaktliste)

** Lehrfächerverteilung
PT: heuer mehr Klassen - braucht öfter Turnsaal und Küche

Mo 7.8.9. Stunde Turnen PTS
(etc)
MS Mattsee: bestimmte Klassen werden zusammen gelegt
Mo kein NM Unterricht

D keine Doppelstunde mehr
Erste Klassen haben einmal Nachmittag (einmal früher aus)

Freitag keine sechste Stunde!

