#+title:      Notenkonferenz MS Mattsee
#+date:       [2026-01-29 Do 14:31]
#+filetags:   :schule:
#+identifier: 20260129T143134

* Begrüßung
Kaum Begrüßung - geht gleich los mit der Notenkonferenz.

* Notenkonferenz
Verhaltensnoten und eventuelle Nicht Genügend.

Gesetz - was sagt das Gesetz über Verhaltensnoten? Was können wir selbst bestimmen / festlegen? Eigentlich muss dies die Schule selbst erarbeiten.

Welche Maßnahmen bei vierte Klassen / Verhalten? Würde Wiedereinführung der V-Noten was ändern? (Ich hatte Verhaltensnoten bis zur Matura.)

** 1a
15 : 3

NG: nix

** 1b *
16 : 3

NG: 1 S mit 2x NG und 3x G
2 S mit nur SG

** 1c *
16 : 2

1 S mit 3x NG (SPF)

** 2a *
14 : 2

Was ist mit Lukas Schwarz? ein zufriedenstellend? Aufpassen! Bei Störungen immer reagieren. Adem und Lukas haben unter einander ein Problem. Und nicht mit den Lehrern. Eltern Schwarz hussen Kinder u. Eltern auf. Rufen andere Kinder an. etc. Beide Eltern müssen in die Schule kommen. Gespräch notwendig.

1 S 3x NG (SPF erweitert?)

** 2b
19 : 1 

1 S 2x NG

** 2c *
14 : 3

1 S 1x NG

** 3a
15 : 3 : 1 (Hussein; öfters, unbelehrbar - Eltern sind informiert)

NG: nix
viele SPF Kinder

** 3b
18 : 2

2 S mit 2x NG bzw 1x NG

** 3c
16 : 4

3 S mit 1x NG, 2x NG, ...

** 4a
3 S mit NG

Verhalten: 4 S waren wieder extrem lästig; drängeln beim Buffet; 

** 4b *
1 S mit 3x NG; in E nicht beurteilt.

** 4c
1 S mit 1 NG und 7x G

* Allfälliges

** Religionsnoten
X ... ohne Bekenntnis; falls er sich anmeldet - als Freigegenstand
S ... vom RU abgemeldet 
D ...  nicht durchgeführt - da RU nicht zustande gekommen ist. [neu!]

** Müll
Va nach der Mittagspause
Energy Getränke in der Klasse / Tisch; eigentlich sind Energy Drinks an der Schule verboten.

** Entwicklungsplan
Verhalten (muss öffentlich, Gang, Klasse, ... sein)
Krisenplan
?

** Fasching
[[file:~/Documents/org/tasks.org::#h:20260129T152744][Faschingskostüm MS Mattsee]]
Foto für Konferenzzimmer

** Schulwart
An mehreren Schulen; bitte nicht direkt ihn anrufen; immer über Direktion; egal, ob und wie viele den Schulwart anrufen - in Zukunft bitte über die Direktion.

** Teacher Assistent
Bitte eintragen! Sokrates - Frage 201; eintragen in TA.
Und WebUntis!

Bsp.: 16.12. Turnen Stoff eintragen! Zahlen Bingo Spiel.

** Umstufung
Zügig umstufen; plus Gespräch in der Fachgruppe.

** Bei Projekten
Bitte vorher mit Direktion absprechen; ob Termin passt.

** MS Mattsee ist keine Brennpunktschule
Macht ein schlechtes Bild nach außen; ist "too big"! Hilfe - ja! Ev. um Hilfe bitten. Wenn ich als Lehrer 3-4mal mit demselben Schüler ein Problem habe, dann habe ich ein Problem mit meinem Unterricht. Muss dann meinen Unterricht überarbeiten. 36 Stunden pro Lehrer im Jahr verplanen ist zu viel. Spontane Hilfe holen ist angebrachter. 

** Schulhomepage
Datenschutz anpassen; login Bereich und diverse Dinge in den geschützten Bereich geben (wie z.B. Klassenstundenpläne); Einverständniserklärung für Schüler und Lehrer (unterschreiben); Fotos von Lehrer am besten ein eigenes; bei Fotos aufpassen - keine Handzeichen (kein Peace Zeichen, etc ...).

** Lehrerausflug
Abstimmung bzgl. Termin. 

Ziel? 
- Proksch Haus Werfenweng (nur im Juni; im Mai nur Sa+So); oder 
- Passau
- Wien
- Wachau

Anreise privat.
