#+title:      Jahresplanung
#+date:       [2026-03-03 Di 10:18]
#+filetags:   :schule:
#+identifier: 20260303T101813

* Einleitung

Für das nächste Jahr plane ich mein Schuljahr ein wenig um; ich lege den Fokus vermehrt auf die Hl. Schrift und den YouCat. Ziel: eine lebendige Beziehung zu Jesus. Fundiertes Glaubenswissen; "Der Christ von morgen ist ein Mystiker, oder er ist kein Christ." (Karl Rahner) Dazu werde ich meine Planung natürlich noch genauer mit dem Lehrplan und den Religionsbüchern abgleichen.

In jedem Schuljahr werden die großen Feste des Kirchenjahres unter verschiedenen Aspekten angeschaut. 

Immer wieder werden wir Heilige kennenlernen. 

Kunst, Kunstwerke, Baustile der Kirchen, ... werden ihren Platz haben. Pop-Musik? Kinofilme? ... mit religiösem Inhalt?

Umgang mit Konflikten - Ungerechtigkeiten - ...

Immer wieder: Glaube - Hoffnung - Liebe (Tugenden); Tugenden; Gaben des Hl. Geistes; Früchte des Hl. Geistes. 

Gemeinsames Gebet, Lobpreis, ... Stille.
(Dazu sollte ich mir ein aktuelles, gutes Liederbuch besorgen.)

* Erste Klasse

** Schwerpunkt Bibel

Einführung; Entstehung; Gesamtüberblick über Heilsgeschichte
Themen: Schöpfung, Noach; Psalmen; Jesus; 

** YouCat

Beginn: Gott liebt mich - Berufung zur Heiligkeit
Taufe
Credo; Gebet

* Zweite Klasse

** Schwerpunkt Bibel

Gesamtüberblick über Heilsgeschichte
Themen: Abraham; Moses; Saul / David / Salomo; Jesus - Gleichnisse Reich Gottes; Erste Christen

** YouCat

Sakramente; va. Eucharistie

* Dritte Klasse

** Schwerpunkt Bibel

Gesamtüberblick über Heilsgeschichte
Themen: Whg Moses (10 Gebote); Ruth, Esther, Judith; Hiob; Exil; Paulus; 

** YouCat

Krankensalbung, Beichte
10 Gebote

* Vierten Klasse

** Schwerpunkt Bibel

Gesamtüberblick über Heilsgeschichte
Themen: Exil; Propheten; Briefe des Paulus; Apokalypse

** YouCat

Credo - was wissen wir über Gott? Glaube und Vernunft
Firmung, Ehe, Weihe
"Heiße Eisen" des Glaubens, Sexualität

** Philosophie

Ethik, Moral, Gott und die Welt, Vielfalt des Lebens (unbelebt, Pflanze, Tier, Mensch), Wer ist der Mensch?, Arbeit - Ethik - Politik, Metaphysik - Was ist das Sein?
