#+title:      Konferenz Seekirchen
#+date:       [2026-03-18 Mi 16:08]
#+filetags:   :schule:
#+identifier: 20260318T160819

* Begrüßung

* Schulbuchaktion

- Atlanten nur in einer Klassenstärke bestellt (weil teuer)
- Digital Budget erhöht (nur mehr 2.17 Euro übrig)
- DAZ Bücher noch bestellen

* Einsatz des Tablets im Unterricht

Funktioniert mit manchen Schülern (besonders Burschen - schauen z.B. Pornos) nicht. Daher ist oft das Buch besser. Immer Absprache mit Kustos. Bildungsnetzwerk - z.B. ZDF Mediathek ist gesperrt - wegen Vorgabe des Landes (Inhalt - Doku über Atombombe - weil Waffen).

* Schülerzugänge

- 2a: Emilia - sehr ruhig; war viel krank; sprachlich ein Problem (OP an den Ohren) - Aussprache; fühlt sich nicht unwohl; kommt vom Gymnasium
- Besim (Kosovo) + ...
- 1d: Florian (Kreativwerkstatt)
- Mutasa (?)

* Leon Trummer (2a - 2c)

Vom BvwGh hat Leon eine Androhung an Ausschluss bekommen (es reicht eine verbale Drohung).

Leon Trummer (2 Tage unauffällig; heute gab's wieder was) - Meldung an die Direktion (KV und Gudrun in CC, Mail an die Mutter), BD, ... Man kann auch Rettung und Polizei rufen. Welcher Lehrer braucht Unterstützung. Mit Absprache mit dem Lehrer. Es gibt schon wieder genug "Material" für eine Suspendierung. Zur verbalen Gewalt kommt jetzt körperliche Gewalt hinzu (hat einen Schüler dreimal in kurzer Zeit geschlagen, ...). In der 2c sitzen Klassenkollegen aus der VS. 

* Reisekostenantrag / Abrechnung

Früh genug stellen (so dass Gudrun sie bestätigen bzw bei Fehlern zurückschicken kann). Antrag / Rechnung ist fertig wenn genehmigt. 

Betreff: richtige Nummer (FB und SV)


* Sommerschule

Mittelschule Eugendorf; verpflichtend für AO Schüler, letzte zwei Ferienwochen; wer braucht noch eine Sommerschule? BFD Stunden (drei Schüler) - wer noch? 

Programm D, E, M. - Auch als Lehrer kann ich mich anmelden. Ev. Buddys zur Unterstützung.

* Kopftuchverbot

Gilt ab dem nächsten SJ; nicht in der Schule. Bis zum 14 Jahr. Ist unsere Pflicht, jeder Lehrer muss das Kind ermahnen. Wer es nicht tut, Meldung an die Direktion. Wer es nicht meldet - Kündigungsgrund (Frechheit). Ob das nicht Moslems ausnutzen.  

* Suspendierung und Ausschluss

"Gesetz wird geändert" Oje!

wird immer schwieriger - denn wenn ein S. suspendiert wird, muss er trotzdem 8-20 Stunden in die Schule; natürlich in jene Schule, von der er suspendiert wurde. Förderplan erstellen.

* Kinder mit Beeinträchtigung

Gutachten plus pädagogische Einschätzung des Lehrers

z.B. Autisten / ADHS / Rollstuhl, etc.
Zeitzugaben - aber nicht leichtere Aufgaben
Spezielle Software, größere Schrift, Vorlesen, 
Schulische Assistenz müssen Eltern beantragen

Diese spezielle Förderung - SPF beantragen - wird abgelehnt - dann kommt ev. Förderung. Wozu? Was? Pro SPF 2.5 Stunden; Gudrun erkämpfte 3 Stunden; ...

Weil Seekirchner so gut verdienen, erhält die Schule für SPF, etc. kein Geld für Förderungen. Laut Statistik Austria. 

* Wie fördert man sinnerfassendes Lesen?

Wie bringt man Kinder zum Lesen? Wie Lesen sinnvoll anwenden? (Frage nach bei Konrad Paul Liessmann).

[[https://www.derstandard.at/story/2000080877939/philosoph-konrad-paul-liessmann-bildung-macht-nicht-nur-spass]]

[[https://www.deutschlandfunk.de/bildung-als-provokation-konrad-paul-liessmann-ueber-ein-100.html]]

[[https://www.forschung-und-lehre.de/lehre/bildung-als-provokation-364/]]

[[https://www.derstandard.at/story/2000009122736/liessmann-das-kind-muss-perfektioniert-und-optimiert-werden]]

[[https://bildung-wissen.eu/wp-content/uploads/2014/10/liessmann_wiwo.pdf]]

[[https://condorcet.ch/2025/06/man-soll-die-kinder-nicht-dort-abholen-wo-sie-sind-sondern-zeigen-wo-sie-hinkommen-koennen/]]

[[https://www.telepolis.de/article/Die-besten-Kopisten-konnten-nicht-lesen-3410692.html]]


