:PROPERTIES:
:ID:       36daae02-52dd-45c4-b0e8-1248f400cbbe
:END:
#+title: Ewiges_Leben
* Source

Author: Wolfgang Beinert
Title: Ewiges_Leben
Year: 2012

* Summary
Das "Neue Lexikon der katholischen Dogmatik" sagt zu diesem Thema:

"Das E.L. ist das in Gott begründete Leben in Fülle, das aufgrund seiner Selbstmitteilung bereits irdisch anhebt und nach dem Tod vollendet wird." cite:Beinert2012 (S.206)

Israel hofft auf das Leben vor dem Tod.

Nach dem Tod kommen die Verstorbenen in eine schattenhafte Existenz in die scheol, einem Totenreich, das von Gott geschieden und vergessen angesehen wird und in dem die Toten Gott nicht mehr preisen können. Der Gott Israels ist ein Gott des Lebens, weshalb er mit diesem Totenreich nicht in Verbindung gebracht wird. In Srael gibt es keine Verehrung der Toten. Nur von Henoch und Elija wird erzählt, dass sie direkt zu Gott entrückt wurden.

Zwischen dem 8. Jhdt und dem 6. Jhdt entwickelt sich ein klarer Monotheismus, wodurch auch das Totenreich dem Machtbereich Gottes zugeordnet wird.

Der Tun-Ergehen-Zusammenhang gerät mit der Weisheitsliteratur in eine Krise: da das gute Handeln der Gerechten auf Erden nicht immer zu ihrem Wohlergehen führt. Durch den Einfluss des Hellenismus (Unsterblichkeit der Seele) veränder sich auch der Diskurs über das E.L. Durch die Märtyrer entwickelt sich der Glaube an die Auferstehung der Toten und auf die Beseitigung des Todes generell.

Im NT gibt es verschiedene Begriffe für das "Leben":
 - psyche: das irdische Leben, es ist bedroht und vergänglich
 - zoe: das Heilsgut Leben bleibt unzerstörbar, weniger durch Ewigkeit als durch Gottesgemeinschaft gekennzeichnet, welche schon im irdischen Leben erlangt werden kann.

Joh-Offb.: Buch des Lebens, Kranz des Lebens, Baum des Lebens, Wasser des Lebens.

Ob man in das E.L. eingehen kann, entscheidet sich am irdsichen Lebenswandel. E.L. und der Glaube an Tod und Auferstehung Jesu. Er hat sein Leben für uns hingegeben - damit hat er den Weg dorthin gebahnt und leitet ihn. Jesus gibt das Leben in Fülle. Brot des Lebens. So haben die Gläubigen das Leben im Namen Jesu. 
