#+title:      Die Welt der Gefühle
#+date:       [2024-09-11 Mi 09:33]
#+filetags:   :01:gemeinschaft:
#+identifier: 20240911T093358

* Startseite

** Arbeitsauftrag 1
Für alle Schüler*innen ist der Wechsel von der Volksschule in die Mittelschule oder gymnasiale Unterstufe mit positiven, aber auch negativen Gefühlen verbunden: Vorfreude, das Gefühl "groß zu werden" oder die Lust, endlich Neues zu lernen stehen Ängsten, Sorgen und Unsicherheiten gegenüber. Der Comic greift diese Thematik anhand einer typischen "Erwachsenenaussage" auf: "Jetzt beginnt der Ernst des Lebens" – ein Spruch, der oft an den Lebenswenden von Kindern und Jugendlichen gesprochen und/oder gehört wird. Die Aussagen der Leitfiguren greifen dabei übliche Erweiterungen auf: Alles wird schwerer, alles wird Neu – dabei ist dieses Gefühl für Kinder oft gar nicht mehr neu, vielmehr wiederholt sich die Erzählung vom Neuanfang in ihrem Leben ständig. Der Comic kann hier als Diskussionsanregung dienen, um eigenen Erfahrungen, Aussagen und Erwartungen (sowohl positiv, wie auch negativ) nachzugehen.

** Arbeitsauftrag 2
Dieser Arbeitsauftrag greift dem Comic erneut auf und konkretisiert die darin angesprochenen oder angedeuteten Gefühle. Mögliche Nennungen könnten beinhalten: Vorfreude, Angst, Aufregung, Unsicherheit, sich verloren fühlen, sich klein fühlen, sich alleine fühlen, Mut, Vertrauen...

** Arbeitsauftrag 3
Dieser Arbeitsauftrag ist sehr persönlich und individuell. Es bietet sich allerdings eine Besprechung und/oder Diskussion der Hintergründe an ("Warum ist das bei dir so?"), wobei allerdings behutsam darauf geachtet werden sollte, die zu Beginn ohnehin recht angespannte Gefühlslage der Kinder nicht zu überfordern.

** Arbeitsauftrag 4
In der Lebenswelt der Schüler*innen gibt es meistens zahlreiche Erfahrungen mit Neuanfängen. Nicht wenige Schüler*innen haben etwa Umzüge, Trennungen und Krankheiten, in jedem Fall aber einen persönlichen Neubeginn (Kindergarten, Volksschule, MS/Gymnasium) erlebt. Dieser Arbeitsauftrag regt nicht zu sehr zur Diskussion an, sondern fordert die Schüler*innen auf, möglichst viele Neuanfänge zu sammeln – ganz egal, ob sie diese selbst erlebt haben oder nicht (deshalb ist der Arbeitsauftrag auch dem Sachbezug "blau" zugeordnet). Mögliche Antworten könnten sein: Jobwechsel, Umzug, neue Freundschaft, Trennung der Eltern, neues Zimmer, Geburt von Geschwistern, Abschluss einer Schule/Ausbildung etc. – je größer die Zahl und je verschiedener die Ergebnisse, desto größer ist auch die Erkenntnis, dass es in vielen Bereichen des Lebens oft unerwartete oder noch unbedachte Neuanfänge gibt.

* Die Welt der Gefühle

** Arbeitsauftrag 1
Dieser Arbeitsauftrag ist sehr individuell und persönlich. Die "Gefühls-Landkarte" ist außerdem darauf ausgelegt, von den Schüler*innen selbst ausgemalt und illustriert zu werden – geben Sie ihnen dazu ausreichend Zeit und Gelegenheit! Die "Gefühls-Landkarte" kann außerdem immer wieder verwendet werden, um aktuelle Befindlichkeiten zu besprechen. Eine Zuordnung zu prototypischen Orten fällt den Kindern oft leichter als eine Antwort auf die Frage "Wie geht es dir?".

** Arbeitsauftrag 2
Der Fokus dieses Arbeitsauftrags sollte auf der Kommunikation der Schüler*innen untereinander liegen. Außerdem ist es wichtig, seine Position zu begründen und somit Erklärungen und Hintergründe für die eigenen Gefühle zu reflektieren.

** Arbeitsauftrag 3
Die "Gefühls-Landkarte" bietet im rechten Bereich Möglichkeiten, kreative Ergänzungen vorzunehmen. So können die Schüler*innen selbst "Gefühls-Orte" entwickeln und textlich bzw. grafisch ergänzen. Weitere Gefühlsorte könnten etwa sein: Das "Schattental", ein "Märchenwald", eine "Oase in der Wüste", das "Gefühlskarussell" (kann auch in der Karte als solches beschrieben werden), die "Blumenwiese der Hoffnung" usw. Die Erfindung von Gefühlsorten fällt den Schüler*innen mitunter nicht leicht. Eine Vorbereitung im Plenum kann unterstützen: z.B. zuerst verschiedene fehlende Gefühle sammeln und dann passende Orte/Gegenstände dazu finden. Das sprachliche Muster "Ort des/der Gefühl" (z.B. Tal der Trauer) kann bei der Formulierung helfen.
