#+title:      Warum habt ihr solche Angst?
#+date:       [2025-10-14 Di 10:39]
#+filetags:   :02:fragen:
#+identifier: 20251014T103949

* Wiederholung
Stillung des Seesturms durch Jesus. Das kleine Boot als Bild für die Kirche. Werde ich Jesus im Seesturm wecken? Oder lasse ich ihn schlafen, denn seine Nähe genügt mir? Was soll mir geschehen, wenn Jesus gegenwärtig ist? Jesus tadelt den Unglauben seiner Jünger - sind wir "besser" (=gläubiger) als sie?

* Erarbeitung
Fragen: 
 - Wovor hast du Angst? Kannst du dieses Gefühl beschreiben (Würgegriff, Dunkelheit, Strudel - der mich nach unten zieht, ein heilsamer Schmerz, ...)?
 - Angst kann auch unerkannte Energien und Kräfte im Menschen freisetzen - wo, zB?
 - Wie drückt sich Angst körperlich aus?
 - Was machst du, wenn du Angst hast?
 - Wie schützt du dich vor Angst?
 - Wo ist dein sicherer Ort, wo bist du geborgen?

*Didaktische Überlegungen:*
 1. Andocken an letzte Stunde / Whg / Aufzeichnungen
 2. Hinführung zu neuem Thema: Bilder, Situationen, etc beschreiben / zeigen / ... welches Gefühl, Zustand lösen sie bei dir aus? Wie fühlt sich das an? Kannst du es beschreiben?
 3. Erarbeitung durch Schüler: Was tust du gegen die Angst? Wie schützt du dich davor? Wo ist dein sicherer Ort? Was hilft dir?
 4. Verinnerlichung / Heftarbeit: Wir erstellen einen "Ratgeber in Angstsituationen".
 5. "Was habt ihr gelernt?" - offene Fragen.

Wir erstellen einen "Ratgeber in Angstsituationen".

Jesus im Seesturm: Jesus lässt mich nie im Stich. Die Bibelstelle lesen (RB 1, S. 12 / Mk 4,35-41). Das Bild gemeinsam bestrachten (S. 13) beschreiben Wie geht's den Jüngern, versetze dich in ihre Situation, was würdest du tun, ...? Was macht Jesus, wie geht's ihm? Wie verstehst du die Frage Jesu ("ihr Kleingläubigen!") Stell dir vor: die Jünger haben gerade davor erlebt, wie Jesus eine große Menschenmenge mit wenigen Broten und Fischen ernährt hat und jetzt, im Sturm, fürchten sie, dass ihr Boot untergeht? Aber: steht es mir zu, mich über die Jünger zu wundern? Bin ich besser als sie?

* Hefteintrag
Wie würdest du diese Szene malen?
