#+title:      Kann ich dir vertrauen?
#+date:       [2025-09-18 Do 09:01]
#+filetags:   :01:gemeinschaft:
#+identifier: 20250918T090153

* Schritt 1 - Regeln und Vertrauen?

Regeln in der Klasse, wie sie auch später noch thematisiert werden (siehe 1.6), dienen vor allem dazu, einen sicheren Rahmen für Nähe, Vertrautheit und Freundschaft in der Klasse zu schaffen. Es lohnt sich daher, die Regeln nicht als Selbstzweck zu sehen, sondern zu hinterfragen, warum es sie gibt.

- Regel 1 (Fair geht vor!) etwa sichert die Gleichbehandlung aller und beugt Ausgrenzung und Mobbing vor.

- Regel 2 (Es gibt gute und schlechte Geheimnisse!) dient u. a. der Differenzierung von Geheimnissen, die von Kindern oft unhinterfragt beachtet werden; 

- Regel 3 (Dein Körper gehört dir!) legt wichtige Persönlichkeitsrechte und eine Intimsphäre fest, vor allem im Hinblick auf die Veröffentlichung von Inhalten im Internet und den sozialen Medien.

- Regel 4 (Hilfe zu holen ist kein Petzen!) ermutigt Kinder, sich helfen zu lassen und Hilfe zu suchen, wenn sie in eine bedrohliche Situation gelangen.

- Regel 5 (Du bestimmst, was gut für dich ist!) gibt jedem Kind die Möglichkeit, seine Grenzen zu artikulieren („Herr seiner selbst zu sein“).

- Regel 6 (Nein heißt Nein!) ist verwandt mit der bekannten „Stop-Regel“ und gibt analog zu Regel 5 Kindern die Möglichkeit, Grenzen zu definieren und diese auch durchzusetzen.

- Regel 7 ermutigt dazu, in Krisensituationen Hilfe zu holen und über die Probleme zu reden.

* Schritt 2 - gute und schlechte Geheimnisse?

Beispiele für gute Geheimnisse könnten etwa sein: Geheimnisse, die andere vor Gefahren, Gewalt oder Einsamkeit schützen; Geheimnisse, die niemandem schaden; Geheimnisse, die zwei Menschen verbinden ...

Beispiele für schlechte Geheimnisse könnten etwa sein: Geheimnisse, die andere in
Gefahr bringen; Geheimnisse, die Verantwortung abschieben; Geheimnisse, die anderen schaden …

Sinnvoll ist es, die Unterscheidung zwischen Geheimnis und Erpressung herauszuarbeiten.

Was für ein Gefühl ist mit dem Geheimnis verbunden? Wem nützt es? Was kann man tun, wenn ein Geheimnis belastend ist? Mit wem könnte eine Person darüber sprechen? Wann ist ein Weitersagen Petzen und wann ist es Hilfeholen? Wichtig ist, den Kindern ihre Geheimnisse zu lassen und ohne Zuschreibungen neutral zu besprechen. Zu bedenken ist auch, dass es oft unterschiedliche Meinungen darüber gibt, ob es sich beim Weitersagen um Petzen oder Hilfeholen handelt. Wichtig ist das Gefühl der Geheimnisträgerin/des Geheimnisträgers und die Intention der Person, die um Geheimhaltung bittet oder sie verlangt.

* Schritt 3 - Erfahrungen hinter Regeln?

Hinter Regeln stecken oft schlechte Erfahrungen, die in weiterer Folge verhindert werden sollen (Prävention). Dieser Arbeitsauftrag zielt darauf ab, mit den Schülerinnen/Schülern gemeinsam darüber nachzudenken, welche dieser Erfahrungen hinter den einzelnen Regeln stecken könnten. Dabei soll es nicht darum gehen, die „richtigen“ Erfahrungen zu benennen oder aufzuzählen, sondern möglichst nahe an der Erfahrungswelt der Schüler*innen mit ihren Geschichten und Erzählungen zu bleiben. Die Lehrperson sollte hier einen Austausch über Erfahrungen anleiten, bei denen die jeweiligen Regeln hätten helfen können. Aus dieser Perspektive kann sich auch eine Erweiterung, Umformulierung oder Kritik der einzelnen Regeln ergeben.

* Hilfseinrichtungen?

Viele solcher Einrichtungen sind den Kindern bereits aus der Volksschule bekannt. Beispiele dafür könnten sein: Rat auf Draht, die Telefonseelsorge, die „Nummer gegen Kummer“ …

Als Personen könnten etwa die Eltern, Vertrauenslehrer*innen, Jungschar- oder
Jugendleiter*innen, Psychologinnen/Psychologen, Seelsorger*innen genannt werden. 

