#+title:      Über das Leben nachdenken
#+date:       [2025-09-05 Fr 23:58]
#+filetags:   :01:gemeinschaft:
#+identifier: 20250905T235812

* Einstieg

** Bildbetrachtung „Building Bridges“ von Lorenzo Quinn:

Beschreibe, was du siehst. Wie sehen die Hände aus? Welches Gefühl löst dieses Bild bei dir aus? 
(Verweis: Arbeit mit Bildern in der Methoden-Werkstatt).

** Bild nachstellen: 

Schüler stellen als Gemeinschaft das Bild nach, gehen einzeln durch die von ihnen geschaffene Skulptur und beschreiben ihre Wahrnehmungen.

** Handausdrücke: 

Die Schüler finden Begriffe, die den Ausdruck der Hände beschreiben. Schüleräußerungen an der Tafel sammeln und besprechen. (Diese Begrifflichkeiten können zum Bild im Buch geschrieben werden, ebenso kann ein Titel für das Bild ausgedacht und dazu notiert werden.)


* Erarbeitung

** Arbeit mit dem Titel der Skulptur: „Building Bridges“

Zeichen für die Fähigkeit des Menschen, zusammen zuhalten und Grenzen zu überwinden:

/Was kann dieser Titel mit der aktuellen Situation (neue Schule/neue Klasse) zu tun haben?/ 
/Welche Fähigkeiten besitzt du, die Zusammenhalten und Grenzen-Überwinden zum Ausdruck
bringen?/


** Aussage von Lorenzo Quinn:

„Die Hand hat so viel Kraft: die Kraft zu lieben, zu erschaffen, zu hassen, zu zerstören.“ 

Die Schüler*innen kommen über diese Aussage miteinander ins Gespräch und bringen ihre eigenen
Erfahrungen ein.

** Handübung: 

Was unterscheidet die Handpaare? In Zweier- oder Dreiergruppen die Begriffe/Aussagen des Bildes (Hoffnung, Liebe …) mit den eigenen Händen darstellen, fotografieren, einkleben und in Stichworten
die Unterschiede benennen.
(M1)


* Vertiefung / Abschluß

** Klassenplakat mit Händen gestalten: 

Umriss oder Abdruck der Hände so anordnen, dass der Zusammenhalt zum Ausdruck kommt.

** Gemeinsam eine Brücke bauen: 

Die Schüler*innen fertigen ein Tonmodell ihrer Hand an. Aus allen Händen der Klasse wird gemeinsam
eine Brücke gestaltet.

** Variante: 

Die Schüler*innen gestalten eine Brücke aus Papier. (M2) Diese Modelle können z. B. auch für einen Gottesdienst oder die Schulhausgestaltung verwendet werden.

** "Hände" von Carolin No: 

Lied anhören, sich darüber austauschen und eine eigene Strophe gestalten.

https://youtu.be/nmTgIevvQdk?feature=shared
