#+title:      Maria, eine mutige Frau
#+date:       [2025-09-06 Sa 00:27]
#+filetags:   :01:welt:
#+identifier: 20250906T002714

* Wiederholung
Wiederholung / Hinführung zum Kirchenjahr: Aufbau, Struktur, Bedeutung, ...

Auf den Weihnachtsfestkreis wird genauer eingegangen: das dreifache Kommen Jesu. Daraus ergeben sich drei verscchiedene Haltungen für den Advent. Wir staunen über Gottes Geheimnis, das Hervorgehen des Sohnes aus dem Vater. Wir danken Gott für das Kommen Jesu vor 2000 Jahren. Wir bereiten unsere Herzen durch Umkehr auf Kommen Jesu in uns vor. Wir erwarten voller Sehnsucht das (Wieder)kommen Jesu in Herrlichkeit am Ende der Zeiten.

* Erarbeitung
[[https://www.youtube.com/watch?v=J5uV_QY-uUA][Advent: Warum, woher, wie, was? - kathmedia]]

[[https://www.youtube.com/watch?v=SAeQMmpI9G8][Ein katholisches Halloween? Bräuche im Advent - kathmedia]]

P. Johannes erklärt in "coolen" Videos den katholischen Glauben. 

[[https://de.wikipedia.org/wiki/Kirchenjahr][Wikipedia: das Kirchenjahr]]

Rituale sind wichtig: Der kleine Prinz

Der Sonntag: ein Osterfest im Kleinen. 

Die Schüler sollen das Kirchenjahr neu entdecken: Wie ist es aufgeteilt? [[https://www.festjahr.de/de/]]

Und: warum ist es auf diese Weise strukturiert? Gott wird Mensch in Jesus (Weihnachten), um uns zu erlösen (Ostern). Daher ist das Kirchenjahr von Weihnachten auf Ostern hin ausgerichtet. Vor großen Festen gibt es Vorbereitungszeiten (Advent, Fastenzeit, Bitttage vor Christi Himmelfahrt). Nach den großen Festen gibt es mehrere Tage bzw Wochen des Feierns: Weihnachtszeit und Osterzeit. Die Zeit des Jahreskreises steht im Zeichen der Hoffnung (Farbe grün) und der Mission. 

Welche Bedeutung haben die liturgischen Farben? [[https://www.festjahr.de/de/die-farben.html]] [[http://www.medienwerkstatt-online.de/lws_wissen/vorlagen/showcard.php?id=5730]]

Welche Rangordnung haben die Feste?  

Advent - Wir "warten" auf Jesus; er kommt 4x.
- In Ewigkeit geht der Sohn aus dem Vater heraus. 
- Menschwerdung;
- jetzt; in den Sakramenten
- am Ende der Zeit in den Wolken

Lesungen des 1. Adventsonntags
- Jes 33,14-16: Gott ist unsere Gerechtigkeit. Gott erfüllt das Heilswort. Ein gerechter Spross sprießt für David auf. 
- 1 Thess 3,12-4,2: (ist der älteste Paulus-Brief); Gabe und Aufgabe gehören zusammen; "Gott zu gefallen"; den Alltag heiligen; so leben, dass die Gottesbeziehung immer stärker wird Barmherzigkeit und Nächstenliebe; 
- Lk 21,25-28.34-36: apokalyptische Vostellungen (Römer, Krieg von 66-70); Menschensohn in der Wolke Buch Exodus, Gotteserscheinungen; 

Symbole des Advents: Adventkranz, Kerze, Weihrauch, Farbe: violett, ...

Warum überhaupt "warten", warum die ganze Vorbereitung? Je wichtiger ein Fest oder ein Besuch, umso länger und intensiver ist die Vorbereitung. Jedes Fest benötigt eine gründliche Vorbereitung - es ist eben ein Fest, und nicht der Alltag. 

* Hefteintrag
Symbole des Advents und ihre Geschichte.
Was wäre für dich ein besinnlicher Advent?
Was würdest du dafür tun?
