#+title:      Der Anfang von Allem
#+date:       [2025-09-07 So 16:05]
#+filetags:   :03:gemeinschaft:
#+identifier: 20250907T160503

* Einstieg

** Bildbetrachtung „Frühling“ von Guiseppe Arcimboldo (S. 9): 

Beschreibe, was du siehst. Welche Pflanzen erkennst du? Überlege, warum der Künstler Köpfe aus Materialien wie Blumen etc. gestaltet haben könnte.

** Foto Click: 

Person A führt Person B blind zu einer Stelle im Raum. Dort darf Person B kurz die Augen öffnen und im Geist ein Foto machen. Danach geht es zu einer anderen „Sehenswürdigkeit“. Nach ein paar Minuten wechseln.


** Teil des Bildes werden (M1):

Die Schüler*innen suchen sich einen Platz im Bild und zeichnen sich dort dazu. Sie beschreiben, warum sie diesen Platz ausgewählt haben.

** Die Geschichte (S. 10) lesen

und das Wesentliche der Geschichte zusammenfassen. 

** Danke sagen: 

Die Schüler schreiben ihre Ideen in die Kästchen (siehe Arbeitsauftrag S. 11).

* Erarbeitung

** Kippbilder (M2): 

Was ist das Besondere an diesen Bildern? Die Schüler gestalten selbst ein solches Bild. Sie können es zeichnen, aber auch mit Naturmaterialien gestalten und dann fotografieren.

** Der Pinguin (S. 10): 

Die Schüler halten im Heft fest, was der Pinguin über die Menschen denken könnte.

** Feste des Dankes (S. 11): 

Die Schüler können im Internet recherchieren, welche Feste des Dankes es in den Religionen gibt und wie diese aussehen. Sie halten in ihrem Heft einige wichtige Informationen fest.

** Gott danken (S. 11): 

Die Schüler wiederholen gemeinsam, was ein Psalm ist und wie ein Psalm geschrieben wird. Danach gestalten sie ihren eigenen Psalm des Dankes.

* Vertiefung / Abschluß

** Klassenausstellung: 

Die selbst entworfenen Köpfe werden an einer Wand in der Klasse wie in einem Museum angeordnet. Die Schüler können sie in einem Rundgang betrachten und sich darüber austauschen.

** Dankeswand: 

Die Schüler gestalten in der Klasse eine Wand, an der sie Dankesworte, aber auch ihre selbst gestalteten Psalmentexte anbringen können.
