#+title:      Gespräch Silbergasser
#+date:       [2023-01-31 Di 14:47]
#+filetags:   :gabriel:schule:
#+identifier: 20230131T144719

<2023-01-31 Di 17:00-18:00> Gespräch mit Hr Silbergasser (MS Grödig)

* Gesprächsthemen
Vielleichz zuerst zuhören, nicht mit Gesetzestexten kommen; Spannungen mit den Lehrern hilft niemandem - das verunsichert Gabriel noch mehr (ist wie eine Scheidungssituation für ihn). 

** Englisch Mahnung
Kann gerechtfertigt sein nach dem Gesetz; aber: seit diesem Tag hat Gabriel jede Lernlust und -motivation verloren. Er ist hoffnungslos und ihm fehlt es sehr an Selbstvertrauen.

** Volksschule
nur die erste Klasse war regulär; 2. - 4. Klasse waren durch Corona "versaut". Zusätzlich hatte er und seine Klasse vier verschiedene Lehrerinnen. Haben Sie dies bedacht? Diesem Jahrgang fehlt es an Volksschulbildung, die andere Jahrgänge mitbringen. Das ist keine Ausrede, denn so ging es tausenden Kindern in Österreich. Das war eigentlich ein Verbrechen an diesen Kindern. Und Kinder wie Gabriel haben am meisten darunter gelitten. Sie bringen nicht die gleichen Voraussetzungen in die Mittelschule mit.

** Welche konkreten Fördermaßmahmen kennen Sie?
Medikamente, SBF / SE helfen nicht und das wollen wir nicht.

Wir sind ratlos. Gabriel lernt sehr viel - aber er kann das Gelernte bei einem Test kaum wiedergeben, anwenden. 

** Ist er reif genug für die Schule?
sollte er wiederholen? ... Vorher: Fördermaßnahmen, ... 

** Wie geht es Gabriel in der Klasse?
Hat er Freunde? Steht er abseits? Als wir für das letzte Gespräch in der Schule waren, kam er nicht zu uns. Seine Klassenkameraden haben ihm die Sicht verstellt, alle anderen gingen herum, er blieb sitzen, ... Mir kommt es nicht so vor, als ging es ihm gut, ... Fühlt er sich wirklich wohl? 

** iPad mag cool sein...
... für Gabriel ist's nicht hilfreich, weil Zuhause eine zu große Ablenkung, noch eine zusätzliche Baustelle und Kampf. 


* Hilfen für Gabriel
Was kommt von der Schule? (hier notieren...)

Neben Hr. Silbergasser war noch Hr. Zachner(?) - GW / M anwesend. Beide Lehrer haben gleich zu Beginn erklärt, dass sie das NG in E bei Gabriel nicht verstehen. Gabriel steht in allen Hauptfächern auf einem Genügend - er kann nicht negativ sein, da überall "as da ist". In GW erhält Gabriel sogar ein Sehr Gut! Im GW und GS Test hat Gabriel die beste Noten der Klasse.

In M macht Gabriel alle HÜ; die Lehrer sehen, wie sehr wir mit Gabriel lernen. Er ist manchmal anwesend, dann wieder weg - und manchmal so lala.

Beide Lehrer sind ratlos. Der ärztliche Befund könnte den Lehrern helfen - für einen SE (Verhalten). Wir wollen einen SPF für die Fächer nicht.

Für die schwache Lernmotivation soll Gabriel auf seine Stärken schauen (GW, GS, Biologie, ...). In M wird Gabriel kaum Motivation finden. Im Ganzen ist er auf einem guten Weg. Er schafft es, seine Schulsachen zu organisieren.

Wir haben den Wunsch deponiert, dass wir öfters über SchoolFox Rückmeldung von den Lehrern erhalten. Wir können jederzeit nachfragen - und einen Termin vereinbaren. 
