#+title:      Donnerstag 28 September 2023
#+date:       [2023-09-28 Do 11:03]
#+filetags:   :journal:Project:
#+identifier: 20230928T110311

* Thoughts
Huch, seit zu langer Zeit geht es mir wirklich nicht mehr gut. Das bemerke ich selbst, aber auch meine Umgebung (Freunde von Isabelle, etc). Leider spüren dies auch schon meine Familie (Isabelle, die Kinder, ...). Ich bin innerlich wie am Ende, ausgebrannt, kein Feuer mehr; sehr oft gereizt. Von meiner Arbeit enttäuscht, oder von einem ausbleibenden Erfolg enttäuscht.

In Parsch zB haben sich alle Schüler bis auf einen vom letzten Jahr vom RU abgemeldet. Heuer habe ich an dieser Schule nur mehr 4 Schüler der ganzen Schule, dh eine Doppelstunde alle zwei Wochen. Und letzte Stunde kam davon nur ein einziger Schüler: eigentlich dürfte es dann gar keinen Unterricht geben. Erst ab drei Schülern gibt es eine Stunde pto Woche.

Ich komme aus eigener Kraft nicht mehr weiter. Ich benötige dringend Hilfe von einem Arzt, Psycholgen oder Psychiater. Von Mi bis Do kommt Frau Lichtenegger nach Golling - sie werde ich fragen.

Auf jeden Fall muss ich wohl meinen Tagesablauf ändern: ich stehe zu früh auf und gehen zu spät schlafen, ich habe kaum Ruhezeiten. Fühle mich ständig unter Druck. Das Gebet und Bibellesen kommt völlig zu kurz. Sport ebenso. Es fehlt auch an qualitativer Zeit mit meinen Kindern - und mit Isabelle.

Dazu kommt der finanzielle Druck durch all die Rechnungen, Kredit, Versicherungen, etc.


* Tasks
Insofern am dies "tasks" nennen kann:

** TODO Zeit fürs Gebet und Bibellesen

** TODO Sport

** TODO Mehr Schlaf

** TODO Was kann ich tun, um meine (Grund)Stimmung zu heben?
Medikamente will ich nicht - die machen nur abhängig, siehe Gabriel.
