#+title:      Dienstag 15 Oktober 2024 21:37
#+date:       [2024-10-15 Di 21:37]
#+filetags:   :journal:
#+identifier: 20241015T213710

Wow - was für ein Tag!

* Gespräch mit Gabi (Direktorin)
Ich kam in Abtenau an, dachte an nichts besonderes, stellte mein Auto ab und wollte mein Handy einstecken. Da sah ich eine Nachricht von Gabi: "Komm wegen Klärung ins Büro." Mir lief es sofort heiß herunter; dann dachte ich: "Was kann das wieder sein?" Mir fiel gar nichts ein ...

Gabi begrüßte ich und stellte mir die Frage: "Was denkst du, was es diesmal ist?" "Keine Ahnung!" "E-Mail einer erbosten Mutter, die endlich Konsequenzen fordert, da du die Kinder als dumm bezeichnet hättest!"

Frechheit - hab ich nicht gesagt. Ich kann mich an eine Situation erinnern: zwei Schüler haben es wirklich bunt getrieben, eine Batterie beinahe zum schmelzen gebracht (das ist gefährlich, weil giftig!) und ihre E Aufgaben sehr schlecht und unleserlich geschrieben.

Als nach mehrmaligem Hinweis und Ermahnen keine Reaktion der beiden kam, hab ich zu dem Schüler mit der Batterie gesagt: "Eine schmelzende Batterie ist gefährlich. Was du hier machst, ist dumm."

Zwei Plätze weiter sitzt ein Mädchen, hat nichts damit zu tun und erzählt ihrer Mutter: "Herr Fuchs sagt, wir sind alle dumm!" 

* Was soll ich jetzt noch tun?
Natürlich kann und werde ich wohl noch mehr aufpassen, was ich sage. Aber hat es Konsequenzen für die Schüler die sich an keine Anweisungen des Lehrers halten? Es kann nicht sein, dass die Schüler mir auf der Nase herum tanzen können, und wenn ich als Lehrer reagiere - mir meine Worte im Mund umdrehen. Ich müsste mich dann dafür entschuldigen und den Schülern "blüht nichts" - nein, sie werden wohl weitermachen wie bisher.

* Gedanken
Gabi steht voll hinter mir; sie will mich länger in Abtenau halten. Irgendwann werde ich mich frei schwimmen. Halte ich bis dahin durch? Das ist die Frage. Denn jene Personen, die meine Feinde sind und mich nicht in Abtenau haben wollen, werden nicht locker lassen.

Soll ich mit dem Ortspfarrer reden? Will ich nicht, da dies eine Schulangelegenheit ist. Internes nach Außen tragen geht gar nicht.

"Mah, das macht keinen Spaß mehr! Keine Freude mehr!" - so hab ich reagiert. Und Gabi versteht mich total. Gott sei Dank hat Lena (KV) mich vor der Klasse verteidigt. Ist nicht ideal, da dies meine Position schwächt (ich brauche jemand anderen).

Aber - naja: Melanie meinte, ich solle am Donnerstag "business as usual" machen. Falls jemand fragen wollte, werde ich so ähnlich wie in der 3a reagieren: "Das macht man nicht, jemand das Wort im Mund verdrehen und ihm Worte in den Mund zu legen, die man nicht gesagt hat. Und dabei nur die halbe Geschichte erzählen. Warum soll ich mich für Dinge entschuldigen, die ich nicht gesagt habe? Es tut mir sehr leid, wenn jemand Dinge falsch verstanden hat. Sorry. Aber ich will auch Konsequenzen sehen für jene Schüler, die in der letzten Stunde am Montag offensichtlich gefährlich unterwegs waren, siehe Batterie."


