#+title:      Montag 30 September 2024 21:43
#+date:       [2024-09-30 Mo 21:43]
#+filetags:   :journal:
#+identifier: 20240930T214337

* Müdigkeit
Obwohl ich eigentlich nicht viel später schlafen gehe und nicht früher aufstehe - ich fahre nur eine gute Viertelstunde früher in die Arbeit: ich bin um einiges (!) müder als letztes Schuljahr. Das zeigt, wie sehr mich dieser Schulstart in einer neuen Schule belastet.

Leider habe ich z.B. in der Nacht von Sonntag auf heute Montag etwas zu wenig geschlafen, und sowohl bei der Hinfahrt als auch bei der Rückfahrt bin ich gerade noch einer gefährlichen Situation ausgewichen. In der Früh hab ich eine Schülerin beim Überqueren der Straße zu spät gesehen (wahrscheinlich hat auch die Schülerin nicht oder zu wenig geschaut; sie hat sich aber bei mir bedankt). Und bei der Rückfahrt wollte ich einen LKW nach einer Ortsdurchfahrt überholen, aber der LKW hat gas gegeben und das Überholen ging sich - auch wegen des Gegenverkehrs nicht mehr aus. Ich konnte wieder zurück in die Spur.

Vielleicht sollte ich mir doch zu Herzen nehmen: besonders auf der Straße von Golling bis Abtenau *nicht* zu überholen. Diese Straße ist einfach zu gefährlich; v.a. der Abschnitt durch das Lammertal, das heißt nach Oberscheffau, wenn es den Berg hinauf geht.

* Besuch der Direktorin
Heute hat mich Gabi in der 4b besucht - wir haben gerade das Schöpfungsquiz gespielt. Sie blieb nicht lange. Und da ich die wahren Hintergründe ihrer Besuche kenne, bin ich beruhigter. Sie wird nur mehr eine Klasse besuchen, und dann werde ich mich noch mehr beruhigen können. Denn im Moment spüre ich noch eine sehr unangenehme Anspannung; ich fühle mich noch nicht wirklich wohl.

Aber sich auf eine neue Schule einstellen geht eben nicht so schnell.

* Schlaf
Wegen der obigen Überlegungen werde ich jetzt bald ins Bett gehen.
