#+title:      Montag 17 Juni 2024 09:51
#+date:       [2024-06-17 Mo 09:51]
#+filetags:   :journal:
#+identifier: 20240617T095112

* Landschultage Rauris Gabriel
Heute ist Gabriel mit seiner Klasse (und der Parallelklasse 2m) auf Landschultage nach Rauris gefahren. Oh, er war die letzten Wochen so aufgeregt und hat sich riesig auf diesen Tag gefreut. Ich hoffe, er erlebt unvergessliche drei Tage in Rauris.

* Flugtickets England
Heute Nachmittag werden Isabelle und ich die Flugtickets für die Reise nach England kaufen. Hoffentlich finden wir günstige Tickets ab Salzburg. Für den Rückflug von Gabriel benötigen wir eine Flugbegleitung.

Ich hab ein Reisebüro hier in Golling gefunden. 

* Euro 2024
Fußball EM - wie gut, dass ich die Spiele nicht ansehe. 60' und Österreich ist 0:1 hinten - durch ein Eigentor von Maxi Wöber. Da spielt Österreich so gut mit, und bisher eine überragende Saison hinter sich. Und jetzt wird alles zunichte gemacht durch ein Eigentor! Beim Dreifachwechsel lässt Ragnick den gelb vorbestraften Mwene drinnen; nimmt Wöber, Gregoritsch und Grillitsch raus - und bringt Trauner, Arnautovic und Wimmer. Der Letztere bringt wirklich was mit.

Naja - ich bin nicht der Teamchef. Er muss es wissen - hoffentlich. Auf jeden Fall typisch Österreich: es geht um viel und Austria verliert. Typisch.

9 Minuten Nachspielzeit - vielleicht geht ja doch noch was? Zu hoffen wäre es. Nichts - es ist aus. Gegen Polen muss Österreich gewinnen - ein Unentschieden ist zu wenig.
