#+title:      Sonntag 28 Jänner 2024
#+date:       [2024-01-28 So 00:58]
#+filetags:   :journal:
#+identifier: 20240128T005809

* Thoughts
Gabriel ... lügt ... viel. Heute wieder einmal. Wegen einer Kleinigkeit. Er sagte mir, sein iPad sei bei Mama in der Arbeit. Hätte ich ihm geglaubt, hätte ich nicht nachgeschaut und Gabriel hätte während der Nacht mit dem iPad Videos geschaut. Er hat es zugegeben, mir das iPad zurückgegeben.

Das tut schon weh. Leider war ich dann ziemlich hart mit ihm; mir tut es hinterher im Herzen weh, wenn ich Gabriel die ganze Tragweite seiner Lüge klar mache. Denn mit solchen "kleinen" Lügen kann er jedes Vertrauen in ihn zerstören. (Ich weiß, meine Mama würde das alles nicht so eng sehen. So wie sie auch sexuelle Sachen unter oder an Kindern als "akzeptale Doktorspiele" gut heißt. Da stelle ich mir die Frage, ob sich Erwachsene an uns vergriffen haben - ohne dass wir es wussten?)

Ich wollte, dass Gabriel unbedingt noch heute Abend kommt und um Vergebung bittet, was er auch getan hat. Noch fühlt es sich nicht gut an. Vll dann morgen in der Früh. Ich will doch, dass es zwischen uns wieder gut läuft.

* Tasks

