#+title:      Sonntag  3 November 2024 23:05
#+date:       [2024-11-03 So 23:05]
#+filetags:   :journal:
#+identifier: 20241103T230556

* Dacia Duster
Seit dem 31.10.2024 dürfen wir einen nigel-nagel-neuen Dacia Duster unser eigen nennen. Das Auto ist wunderschön, großartig, ... Es bereitet uns wirklich sehr viel Freude.

Der Antrieb ist ein Hybrid - das bedeutet: das Auto "entscheidet" selbst, ob es elektrisch oder mit dem Benzin Motor fahren will (dh woher es seine Energie bezieht). Der Akku wird während der Fahrt durch den Motor oder beim Bremsen wieder aufgeladen. Der Akku ist im Betrieb zwischen 25% und 75% voll.

Das Fahren ist großartig, Isabelle und die beiden Kinder sind begeistert. Sie sagen, dass man sich wie in einem U-Boot oder Raumschiff fühlt. Noch riecht das Auto innen sehr neu.

Die Windschutzscheibe ist innen schon etwas dreckig, wird bald geputzt. In einer Waschstraße muss ich die Antenne abmonotieren.

Folgendes fehlt mir noch: ich benötige eine 2 Monat Vignette (sehr bald) und eine Parkuhr (Tankstelle?). 

* Der Tag der Abholung
An diesem Tag war recht viel los. Zuerst haben wir die beiden Allerheiligen Striezel bei der Bäckerei abgeholt. dann war Mittagessen. Und dann ging es los:

Wir fuhren sehr aufgeregt nach Straßwalchen; das neue Auto stand abgedeckt in der Verkaufshalle. Nach ein paar Unterschriften und dem Bezahlen der Anmeldung ging es los.

Die beiden Burschen durften mit dem Verkäufer die Abdeckung abnehmen. "Ooooh! Wow!" Dann hat mir Herr Skala das Wichtigste des Autos erklärt. Er ließ mich noch eine kleine Runde fahren, damit ich ein Gefühl für das Auto bekomme.

Dann ist Isabelle in die Arbeit gefahren; ich und die Kinder fuhren mit dem neuen Auto zuerst nach Thalgau zu Veronika und haben dort einen Striezel und ein Geschenk abgeliefert. Danach ging es weiter zu Omi und Opa. Dort haben wir einen weiteren Striezel erhalten. Meinen Eltern habe ich den neuen Dacia Duster gezeigt.

Zuhause gab's dann einen lustigen Film mit L. de Funes. Leider habe es Gabriel nicht erlaubt, auf Halloween Tour zu gehen. Stellte sich nachher heraus, dass Gabriel darüber nciht erfreut war. Nächtes jahr mach ich es besser.

* Autofahren macht Freude
Natürlich macht das Fahren mit dem neuen Auto sehr viel Freude. Jede Fahrt passe ich sehr gut auf; ....

Heute Sonntag habe ich dann die (neuen) Winterreifen auf den Caddy montiert. Der Dacia Duster wurde mit Winterreifen ausgeliefert (die wunderschönen und etwas größeren Sommereifen werden bei Omi und Opa eingelagert).

* Morgen beginnt wieder die Schule
Wird wahrscheinlich nicht easy - ist ähnlich für Schüler und Lehrer.

Ab ins Bett...
