#+title:      Dienstag 18 Juni 2024 13:06
#+date:       [2024-06-18 Di 13:06]
#+filetags:   :journal:
#+identifier: 20240618T130623

* Warum ...
... geht es mir nicht so gut? Bin ich traurig? Hab ich etwas (sehr) falsch gemacht? Bin ich einfach nur sehr, sehr erschöpft? Ich stelle im Moment alles in Frage: Liebe, Glaube, Hoffnung, ... Ich war beichten - aber es ändert sich nichts.

Warum hab ich den Eindruck, dass Jesus so weit weg ist? Als hätte ich Glaube verloren? Warum sehe ich vieles schwarz? 

* Wie ...
... kann ich das ändern? Kann ich es ändern? Kann das nur Gott alleine ändern? Was ist mein Beitrag dazu?

* Was ...
... will Gott von mir? Was denkt Jesus über mich? 

* Budget ...
... das ist echt ein Riesenproblem für mich. Mir bleiben noch 1700 Euros am Konto und ich muss noch Kredit, Versicherungen, Kirche, Handys, Internet und das Rückflug Ticket für Gabriel zahlen. Ist eigentlich zum Verzweifeln. Ich weiß hab nur das Geld, das ich habe. Mehr habe ich nicht. Isabelle kann udn will ich nicht fragen, denn sonst würde sie das alles zahlen müssen. Das geht einfach nicht. Also ...? Charly meinte, Rosnekranz beten hilft - das Konto auffüllen? Ehrlich? 
