#+title:      Montag  7 Oktober 2024 22:02
#+date:       [2024-10-07 Mo 22:02]
#+filetags:   :journal:
#+identifier: 20241007T220242

* Vorfall in der 4b
Der Unterricht war heute generell sehr turbulent; die Klasse ist dafür bekannt. "Da geht's einfach zu!" David und Celina sind bekannt, dass sie recht schnell aggressiv werden können. Besonders auf neue Situationen reagieren sie vehement. David z.B. testet sofort bei neuen Lehrern (zB in Supplierstunden) seine Grenzen aus.

* Was ist passiert?
Mehrere Schüler haben mir Fragen gestellt. Ich hab mich ganz kurz an einen Schüler zu meiner Linken gewandt, da hörte ich etwas. Und plötzlich verließ Celina die Klasse. Ich hab eine Schülerin nachgeschickt; nachdem Celina zurück gekommen ist, hab ich David in die Direktion geschickt.

Beide haben angegeben, ich hätte nicht auf ihre Rufe reagiert. Ich muss zugeben, dass ishc sie zwar gehört habe; es war allerdings generell sehr laut in der Klasse und ich hab - zugegebenermaßen - die Situation völlig falsch eingeschätzt.

* Gespräche danach
Ich hab in zwei Gesprächen mit Gabi und einem Gespräch mit Thomas die Situation noch einmal klären können. 

"Störungen haben Vorrang!" - Ich werde wahrscheinlich diese Situation nicht "heilen" können; am besten wird es sein, hin zu schauen und hin zu hören: welche Interessen haben die zwei Kinder? Wofür brennen sie? Berufswunsch? Mein Interesse zeigen ... Eigentlich bin ich ja ein angenehmer Zeitgenosse, denke ich.

* Telefont mit Charly
Besonders gefreut habe ich mich über das Telefonat mit Charly. Er hat mir sehr geholfen. Ich kann nicht immer alles sehen; und v.a. kann ich kein verhalten vorhersehen.

Charly hat mir total geholfen mit seinem Tipp: Beziehung (siehe oben). 

* Morgige Stunde (Dienstag, 8.10.2024)
Da muss ich mir was Interessantes einfallen lassen, um die gestrige G'schicht auszubessern. Allerdings sollen die Kinder auch beschäftigt sein. (Also iPads / Tablets funktionieren nicht so super.)

"Gewissen" hat sich erledigt. Ich frag mal Thomas, was er mit ihnen gemacht hat - v.a. was die Klasse interessiert; oder sind sie ohnehin für einiges zu haben?

Spiele? Episode aus "The Chosen"? (eher fad, oder?)

R.B. Seite 18 - 21:
Die beiden Doppelseiten durch lesen und erarbeiten und über eine der vorgestellten Personen einen Steckbrief bzw. Biografie erstellen (Heft). Präsentation?

- Dokumentation über Ruth Pfau? [[https://www.youtube.com/watch?v=7nXj5iaWSOA]]
- Oscar Romero (hier gibt es einen Film)? [[https://www.youtube.com/watch?v=R0w9RGtUq5w]]
