#+title:      Dienstag 23 April 2024 17:52
#+date:       [2024-04-23 Di 17:52]
#+filetags:   :journal:
#+identifier: 20240423T175215

* Gedanken
Wie sollen wir auf die Rebellion und das Verweigern von Gabriel reagieren? Er sagt fast prinzipiell zu allem "Nein!" was wir ihm sagen. Er engagiert sich kaum für die Schule. Letztens hat er auf die E HÜ und einen E Test vergessen und uns nix gesagt. Sein erstes Interesse scheint den Videospielen zu gelten. Wir reden ihm zu - scheinbar ohne Erfolg.

Und wenn wir zureden, dann ist seine Reaktion: "Ja, ja, rede du nur! Ich brauche euch nicht! Als Spar Mitarbeiter werde ich mehr verdienen als du, Mama!" Reiner Trotz und auch noch frech.

Sollen wir ihn fallen lassen? Warum tut Liebe so weh? Ist da Liebe, wenn man versucht, Schwierigkeiten vom Kind abzuhalten - oder ihn in die Mauer laufen lassen, weil das Kind nicht gehorchen will? Was tun, wenn das Kind nicht gehorchen will, sich verweigert? Nachgeben, aufgeben? Stark (streng) bleiben?

In der Pause: Gespräch mit Manuela - meine / unsere Erfahrung war auch ihre, über lange Zeit. Das Loslassen gehört zum Alltag dazu. Rebellion bei Kindern ebenfalls. Loslassen können tut weh, ist aber notwendig. Und manche Kinder müssen ihren Weg mit dem Kopf durch die Wand finden. 

* Zorn in der Familie
Heute im Auto haben wir mit einander darüber gesprochen, dass wir diesen ständigen Zorn, Streit, etc satt haben. Jeder ist auf jeden grantig. Bis Sonntag soll sich jeder ein Kompliment für jeden überlegen und ein Ding, wo er / sie in nächster Zeit besser werden will. Und: wir wollen gemeinsam regelmäßig beten - eventuell am Sonntag?

