#+title:      Freitag  4 April 2025
#+date:       [2025-04-04 Fr 16:22]
#+filetags:   :journal:
#+identifier: 20250404T162215

* Es ist das Ende als Reli-Lehrer
Heute hat mich während dem Klavierunterricht von Leopold meine Inspektorin angerufen. Eigentlich hab ich damit gerechnet, dass sie mich anruft. Und auch das Ergebnis und der Inhalt des Gesprächs war mir vor dem Anruf schon klar.

Es reicht nicht für eine Suspendierung, aber der Widerstand von allen Seiten ist einfach zu massiv. Ich schaffe es über längere Zeit nicht, Disziplin in den Klassen zu halten. Ich bin kein guter RL - sagen die Kollegen - ich bringe es nicht, bin nicht überzeugend. Ich bin als Lehrer zu gutmütig, zu freundlich. Oder zu zornig. Einfach "kein guter Lehrer".

Sollte ich ab Herbst wieder nach Abtenau kommen, werden sich zu viele Schüler vom RU abmelden. Und selbst wenn es nur Gerede ist, will dies das Schulamt nicht herausfordern.

Wir haben gesagt, ich habe alles getan, was ich kann, alles liege in den Händen Gottes. Das gilt auch, wenn uns Seine Antwort nicht passen sollte.

Soll ich kämpfen, wofür? Um dann wo als Lehrer zu arbeiten? Es gibt keine freie Stellen als RL mehr; oder es sind sehr viele, ganz kleine Stellen.

Was mich wütend und traurig macht: es setzen sich die Bösartigen, Hetzer durch - auch in der Kirche. Gabi sagt, sie mag mich - ha! Marie-Luise glaubt Gabi mehr als mir; schätzt Gabi komplett falsch ein. Und trifft auf  Grund dieser Infos ihre Entscheidungen. Und erhält Druck, weil sie das alles nicht früher gesehen hat. Und weil sie nicht ihren Job verlieren will, muss ich meinen verlieren.

Einerseits hab ich für mich bereits länger mit dem Gedanken gespielt, diesen Lehrerjob an den Nagel zu hängen. Jetzt - wo dies tatsächlich eintritt - ist es härter als ich dachte. Und macht - v.a. auf welche Art und Weise es zustande kommt - so wütend. Weil die Ursachen und Gründe so gar nicht greifbar sind, weil ich immer noch nicht weiß, welche Eltern (welcher Schüler) Widerstand leisten.

Vielleicht sollte ich doch - wenn ich dann eine Alternative gefunden habe - Pater Virgil aufsuchen. Für ihn als Pfarrer ist es wichtig zu wissen, wie das alles zustande gekommen ist.

Seit meiner Ankunft gab es nur Widerstand; und man hat mir unmissverständlich klar gemacht, dass viele Eltern (und Kollegen) einen Ethikunterricht bevorzugen - als einen konfessionellen RU.

Hat - geistlich gesehen - der Teufel gewonnen? Gibt es Momente im Leben Jesu, wo Jesus sich zurückzieht und nichts ausrichten kann? In seinem eigenen Heimatort Nazareth. Die Menschen dort wollten ihn vom Abhang hinab stürzen. Ich will mich nicht mit Jesus vergleichen - so wie Gabi das macht. Ich kann auch nicht einfach sagen: Schwamm drüber, ich vergesse was früher war, tu so als ob nichts gewesen wäre. Das kann ich nicht, und es klappt auch gar nicht, denn die Narben werden bleiben. Ich muss jetzt eine Kraftquelle finden, um meinen Liebestank aufzufüllen und wenigstens dieses Schuljahr noch zu überstehen (so lange ist es ja nicht mehr).

* Meine große Frage - was jetzt?
Einerseits muss ich einen ausreichend bezahlten Job finden (unter 2400 Euro netto geht gar nix), andererseits muss ich meine Emotionen, meine inneren Schwierigkeiten (Zorn?) in den Griff bekommen. Sonst kommt das alles im nächsten Job - bei ähnlichen Schwierigkeiten - wieder hoch.

* Die wichtigste Frage - was will Jesus (von, mit mir)?
Das weiß ich noch nicht.


