#+title:      Donnerstag 27 März 2025
#+date:       [2025-03-27 Do 09:52]
#+filetags:   :journal:
#+identifier: 20250327T095247

* [2025-03-27 Do 07:45] Was für eine Katastrophen-Stunde!

In der 3a war es katastrophal! Zwei Moslems saßen in der Stunde und wollten nicht weggehen. Es ist ständig laut, ich kann keinen Satz fertig sprechen, werde laufend unterbrochen. Wie ein Maschinengewehr schallt es "Herr Fuchs, Herr Fuchs, Herr Fuchs!"

Ich sagte: "In die Mitte der Seite ein Kreuz zeichnen." "Im rechten Winkel? Mit welcher Farbe?" Die Fragen werden zig-mal wiederholt. Und es werden weitere dumme Fragen gestellt.

Ich sagte: "Ihr stört noch einmal - alle schreiben!" Es wurde gestört - alle hatten zu schreiben. Hab Hefte eingesammelt.

Leider hab ich mich zu der Bemerkung hinreißen lassen, dass ich froh bin, euch bald nicht mehr zu sehen. Und dass ich ab Herbst womöglich nicht mehr da bin - Jubel!

Es interessiert mich nicht mehr - das ist nicht mehr "säen unter Tränen" - sondern "Perlen vor Schweine werfen"!

Warum lässt Jesus so was zu? Wozu dient das? Wem hilft das?

* [2025-03-27 Do 11:03] 3c wie in der 3a

Ich hatte gehofft, dass es in der 3c besser läuft als in der 3a - denkste! Wollte die Schöpfung machen, hätte geklappt. Aber nein! Hat gut angefangen, aber dann kamen wieder die gleichen dummen Fragen; oder jeder Satz, den ich sage, wird wie ein Papagei wiederholt. Ich werde mit "Fuchsi" angeredet...

Ich sagte: "Ihr schreibt eine DIN A4 Seite!" - "Unsere Heft sind nicht DIN A4, sondern A4 groß!" Und die Schüler meinen, sie stellen "nur Fragen"!

Ich hab es so satt. Ich gehe einmal davon aus, dass es in der 1d und besonders in der 2a auch so zugeht.


