#+title:      Dienstag 25 März 2025
#+date:       [2025-03-25 Di 09:15]
#+filetags:   :journal:
#+identifier: 20250325T091516

* [2025-03-25 Di 07:45] 4b

Gott ist gut - ich hab heute früh während der Pausenaufsicht gesehen, dass die vierten Klassen eine Schularbeit haben. Hat sich bestätigt, als ich in der 4b ankam. Hab die Schüler gefragt, ob sie noch lernen wollen. "Danke, Herr Fuchs! So nett!"

Die kommenden Stunden, wie werden sie verlaufen? Weiß ich nicht. Charly: "Natürlich macht RU Sinn! Einige Kinder wirst du schon erreichen! Gerade im RU kannst du mit den Kindern ins Gespräch kommen. Wenn Du für deinen Unterricht lebst, dann funktioniert es!"

Heute ist das Hochfest "Verkündigung des Herrn": [[https://schott.erzabtei-beuron.de/][Lesungen]] + [[https://www.perikopen.de/Gedenktage/8Dez_Lk1_26-38_Dorn.pdf][exegetischer Kommentar zum Evangelium]]


* [2025-03-25 Di 10:11] Mögliche Rückkehr von Gabi

Während der Pause haben Johann und Flo mit Thomas K. darüber gesprochen, ob und wie Gabi zurück kommen wird. Spätestens am Donnerstag werden wir es wissen, da die BD entscheiden kommen und wir mit ihr über den Direktor entscheiden müssen, sollte Gabi nicht zurück kommen.

Und sollte sie am Montag zurück kommen - wie wird das sein? Sie hat gesamte Kollegium gegen sich. Würde sie mit Strenge und "Gewalt" ihre Stellung gewinnen wollen, bleibt sie doch nicht länger als eine Woche. Gut ist, dass ihr Büro nicht mehr neben dem Konferenzzimmer ist.

Es wird spannend, keiner weiß, wie es werden wird. Alex meinte, dass Gabi sicher weiß, wie die Stimmung ist und deshalb gar nicht kommen wird.

Lisa (oder war es Theresa?) meinte, sie mache einfach ihren Job und fertig. Da hat sie Recht, die richtige Einstellung.


