#+title:      Mittwoch  9 April 2025
#+date:       [2025-04-09 Mi 22:48]
#+filetags:   :journal:
#+identifier: 20250409T224847

* Konferenz vom <2025-04-09 Mi 15:50-18:00>

Der Beginn war ja noch okay; einiges Persönliche hat Gabi abgelesen, man nimmt es nicht ernst. Da hat Gabi kurz und trocken erwähnt, dass ich ab Herbst nicht mehr da bin. Keine Reaktion - hab ich nicht verstanden. Was wussten die Kollegen schon? Oder wollten sie nicht reagieren - als Schutz für mich? Vielleicht fragen mich Kollegen noch ...

Gegen Ende kam Gabi auf die jetzige Situation zu sprechen; siehe Protokoll:

[[file:~/MMS_Abtenau/Konferenz_09.04.2025.odt]] - Zitat:

#+begin_quote
  /Nachdem KIGA sich bzgl. der problematischen Lage an der Schule im Anschluss an die Leiterdienstbesprechung im November an SQM Kaserer wandte, unterlag KIGA ihrer Weisung, alle Wahrnehmungen zu protokollieren und auch an Mag. Gerner zu schicken, damit das angeschaut werden kann. Danach wäre auf Euch zugegangen worden, doch aufgrund der  Erkrankung wurde alles ruhend gelegt und von KIGA sofort nach ihrer Erkrankung um euretwillen widerrufen./ 

  /Dies kann den Vertrauensbruch auf beiden Seiten nicht wieder gut machen. Vertrauen muss man sich erarbeiten. KIGA ist bereit für einen Neuanfang! Es braucht jedoch beide Seiten dafür, was der SL nicht unmöglich erscheint./
#+end_quote

Es ist unglaublich, unfassbar, traurig, macht zornig, sprachlos, etc. Gabi hat zumindest zugegeben, dass sie im November bereits krank, überfordert, und hat die Schule mit allerletzter Kraft geleitet. Hm, aber so leitet man keine Schule, da muss man als Direktorin auch die Konsequenzen ziehen und sich zurückziehen - und nicht wie Gabi darauf pochen, man sie dazu "berufen". 

Ich habe heute zum Schluss der Konferenz die Ansprache von Gabi kaum etwas verstanden - wir und Gabi haben an einander vorbei geredet; ich hoffe nur, dass diese Situation so schnell wie möglich beendet wird. Gabi hat auf alle eine Antwort, natürlich sind immer wir Schuld - wir sind ja nicht zu ihr gekommen und hätten nix gesagt.

Zum Schluss sagte Thomas K.: "Gut, dann werden wir eben in Zukunft reagieren und dir die Sachen direkt ins Gesicht sagen. Aber bitte nimm es dann nicht persönlich."

Dann kam eine halbe Predigt über Jesus, der für uns starb.

Wenn ich darüber nachdenke, dann macht es mich wirr.

