#+title:      Dienstag  1 April 2025
#+date:       [2025-04-01 Di 09:51]
#+filetags:   :journal:
#+identifier: 20250401T095121

* Gespräch mit Hanni

Hab Hanni von meinen Telefonaten mit Frau Doppler erzählt (ohne zu sagen, dass ich Marie-Luise über die Situation der Schule berichtet habe).

Ich habe dabei erfahren, dass die Kinder im Ort und dem Pfarrer erzählt haben, ich sei ab Herbst nicht mehr an der Schule.

Seit ich hier bin, werden mir nur Knüppel in die Beine geworfen. Ich mag nimmer! ich hab jede Freude am Unterrichten verloren. Heute ist es ganz arg, und ab morgen wird Gabi mit mir reden wollen (so denke ich), wovor ich mich sehr fürchte.

* [2025-04-01 Di 10:05] Ich bin ratlos

Ja, es geht mir seit meiner Ankunft an dieser Schule gar nicht gut; es gab halbwegs gute Zeiten (so wie die vergangene Zeit von Weihnachten bis letzte Woche, da Gabi nicht da war). Aber es gab und gibt auch viele, viele schmerzhafte Momente. Im Moment bin ich ohne Freude und Antrieb.

Viele und so ziemlich alle Beschwerden:
- sind anonym
- sind vom Inhalt her wirr
- es werden mir Worte im Mund verdreht
- werden immer weiter oben in der Hierarchie deponiert
- ...

Für mich macht es überhaupt keinen Sinn mehr, hier zu sein; ich meine - wenn die Kinder die Geschichte verbreiten, ich wäre ab Herbst nicht mehr an der Schule. Und sie das im Ort und dem Pfarrer erzählen. Sich Eltern direkt beim Rektor des Schulamtes beschweren? Was soll ich noch an dieser Schule?

Ich hab Schulamt, Pfarre, Eltern, Schüler (eventuell Kollegen) "gegen" mich?

Da muss ich eine Entscheidung treffen. Was gäbe es als Alternativen?
- Pastoral (Gehalt wird sehr niedrig sein)
- Nachhilfe
- Referent in Erwachsenenbildung
- Universität
- Museumspädagogik
- Beratung bei Lernschwächen
- Anderes Fach (Mathematik)
- [[https://de.wikipedia.org/wiki/Instruktionsdesign][Instructional Designer]] 
- Personalmanager
- Spezialist für Unternehmenskommunikation
- Erstellung von "digitalen educational content"
- Human Ressource
- Redakteur / Lektor für Schulbücher

Oder ganz was anderes wie Busfahrer; diese Idee entstand aber eher aus einer Not heraus. 

