#+title:      Freitag  8 August 2025
#+date:       [2025-08-08 Fr 14:14]
#+filetags:   :journal:
#+identifier: 20250808T141440

* [2025-08-08 Fr 14:14] Wanderung mit Leopold

Das war wohl nichts - wir wollten auf die Toni Lenz Hütte. Eigentlich hat es super begonnen, aber ... Mitten im Wald gibt es eine Stelle mit höheren Stufen. Leopolds Hose riss an dieser Stelle, sie war zu eng und zu klein.

Ich hab mich so sehr auf diese Tour gefreut, musste lange warten, da der Juli komplett verregnet war. Und dann hatte Isabelle vergessen, Hosen zu waschen. Und die einzige Hose, die übrig blieb, war zu klein.

Jetzt sollen Isabelle und Gabriel am Montag mitgehen, wird furchtbar, denn Isabelle ist unsportlich und Gabriel meckert nur.

* [2025-08-08 Fr 23:06] Neue geplante Wanderung mit Leopold

[[file:~/Documents/notes/journal/20250808T141440--freitag-8-august-2025__journal.org::*\[2025-08-08 Fr 14:14\] Wanderung mit Leopold][[2025-08-08 Fr 14:14] Wanderung mit Leopold]]

Am kommenden Montag <2025-08-11 Mo> gehen Leopold und ich noch einmal auf die Toni Lenz Hütte, hoffentlich klappt es diesmal. Wir werden es ja sehen, ob Isabelle und Gabriel mitgehen werden. 
