#+title:      Freitag 12 September 2025
#+date:       [2025-09-12 Fr 10:25]
#+filetags:   :journal:
#+identifier: 20250912T102559

* Ideen für einen Urlaub
in Lungau auf einer Alm

* [2025-09-12 Fr 10:26] Stundenverlauf

Bis jetzt verlaufen die Stunden einigermaßen gut. 

* [2025-09-12 Fr 21:21] Rückblick auf diesen Schultag

Die Stunden in den ersten Klassen war sehr gut, 2b leider schwierig. Gott sei Dank konnte ich vor der Stunde mit Julia sprechen (KV der Klasse). Sie sagt, eigentlich eine tolle Klasse. Ein paar stören eben. Kann gut sein, dass jene Störenfriede nicht in Religion gehen.

Ich hatte zwei Stunden in der 4a und eine in der 4b. Typisch vierte Klassen (sehr kluge Kinder), in der 4b sind va super Sportler. Ich hab sie nur ein Jahr - da lege ich die Messlatte nicht hoch. Ich hab sie nur ein Jahr, solle in cooles Jahr werden. Generell sehen sich die Sportklassen recht cool, als die "Besseren". 

Im Ganzen fühlt sich der Schulwechsel gut an, eine "neue", weil normale Schulwelt: Lehrer, Schüler, ... einfach alles. Die Kinder sind im Grunde super höflich, sehr gut erzogen, ... eine Wohltat und für mich - leider - etwas Neues.

* [2025-09-12 Fr 23:14] Bibelstellen des Tages

** [[file:~/Documents/notes/Bibel/nt/1.Tim_1.org::v1][1. Tim 1,1]]-[[file:~/Documents/notes/Bibel/nt/1.Tim_1.org::v2][2]].[[file:~/Documents/notes/Bibel/nt/1.Tim_1.org::v12][12]]-[[file:~/Documents/notes/Bibel/nt/1.Tim_1.org::v14][14]]

** [[file:~/Documents/notes/Bibel/at/Ps_16.org][Ps 16]]

** [[file:~/Documents/notes/Bibel/nt/Lk_6.org::v39][Lk 6,39]]-[[file:~/Documents/notes/Bibel/nt/Lk_6.org::v42][42]]

