#+title:      Sonntag 10 August 2025
#+date:       [2025-08-10 So 16:21]
#+filetags:   :journal:
#+identifier: 20250810T162153

* [2025-08-10 So 16:21] 50er Geburtstag Veronika

[[file:~/Documents/notes/journal/20250808T141440--freitag-8-august-2025__journal.org::*\[2025-08-08 Fr 23:06\] Neue geplante Wanderung mit Leopold][[2025-08-08 Fr 23:06] Neue geplante Wanderung mit Leopold]]

Das Fest gestern war eigentlich recht nett; schön zu sehen, wie sehr die "Voltis" Veronika bewundern.

Wer mich sehr traurig macht, ist mein Bruder Michael. Ihm geht's sichtlich nicht gut. Es war nicht okay, dass er ohne Bettina gekommen ist. Ob Bettina im Hintergrund eine Trennung von unserer Familie betreibt? Sie schätzt uns als Familie gar nicht.

Und Michael hat nicht gut ausgesehen; ob's in ihrer Ehe wohl gut geht? Bin mir nicht sicher.

Ob ich Michael kontaktieren soll? Ich weiß nicht.

Und im allgemeinen: es ist traurig zu sehen, wie wenig unsere Familie zusammen hält. Auf die Bemerkung einer Frau, wie süß Veronika als Baby war, an meinen Papa: damit konnte er nichts anfangen. Denn so eine Aussage konnte er nicht auf sich beziehen. Und mit Gefühlen kann er auch nichts anfangen. 
