#+title:      Donnerstag 11 Dezember 2025
#+date:       [2025-12-11 Do 13:47]
#+filetags:   :journal:
#+identifier: 20251211T134742

* [2025-12-11 Do 13:47] Gabriel Note BU

Ich bin ziemlich geknickt und enttäuscht. Gabriel hat auf den BU Test ein "Nicht Genügend". Um ehrlich zu sein - ich habe diese Note nicht erwartet. Wir haben mit Gabriel doch recht viel gelernt, viel Zeit investiert - ich habe auf meine Arbeitszeit verzichtet. In letzter Zeit habe ich doch auch bemerkt, dass Gabriel nicht mehr richtig für die Schule engagiert ist. 

In Englisch hat er ein tolles "Standard AHS Gut" nach Hause gebracht und in Deutsch ein "Standard Gut". Für Geografie und Geschichte erwarte ich mir nicht mehr viel. Chemie wird ebenfalls nicht toll - fürchte ich. Wenn ich sehe, wie demotiviert Gabriel "lernt".

Ich bin so unschlüssig, was ich machen soll: Gabriel weiterhin unterstützen? Oder ihn komplett fallen zu lassen? Er tut mir richtig leid! Für Handy und Videospiele verwendet er entschieden zu viel Zeit. Das muss weniger werden. 

Was mich v.a. nervt: natürlich ist das meine Schuld. Weil ich nicht methodisch genug mit Gabriel lerne, sagt Isabelle. Sollte immer neben ihm sitzen. Da will man nur das Beste und ist trotzdem immer der Buhmann der Familie. Ich will nicht mehr! Und doch ... ich kann Gabriel nicht fallen lassen. 

Es ist ja nur eine miese Note - aber es ist so frustrierend. Gabriel sagt (natürlich) nichts. Es reichen zwei Nicht Genügend, egal welches Fach, und Gabriel steigt nicht auf - oder hat keinen positiven Abschluss.  

* [2025-12-11 Do 14:05] Was denkt Isabelle?

[[file:~/Documents/notes/journal/20251211T134742--donnerstag-11-dezember-2025__journal.org::*\[2025-12-11 Do 13:47\] Gabriel Note BU][[2025-12-11 Do 13:47] Gabriel Note BU]]

Das ist für mich die große Unbekannte - was denkt Isabelle darüber? Ich weiß, dass sie sehr enttäuscht ist. Und hat mir die Schuld gegeben, weil ich nicht methodisch genug gelernt habe mit Gabriel, sagt sie. Sie macht ja scheinbar nie Fehler - sie macht immer alles "comme il faut". Wie mich das nervt, als gäbe es nur eine einzige Art, Dinge zu erledigen.

Ich werde bei der Heimfahrt anrufen ... mit Gabriel müssen wir neben Chemie auch Deutsch lernen. Nächste Woche hat er einen Test bzgl. Präpositionen.
