#+title:      Montag 10 August 2026 00:12
#+date:       [2026-08-10 Mo 00:12]
#+filetags:   :journal:
#+identifier: 20260810T001244

* [2026-08-10 Mo 00:12] Beruf und Politik

Mit "Politik" meine ich eher die persönliche politische Einstellung. Es wird in unserer Welt / Gesellschaft immer schwieriger, zu seiner Einstellung zu stehen. Wenn man z.B. eine rechte Partei wie die FPÖ unterstützt, dann muss man eben mit Gegenwind rechnen. Oder - wie es mir passiert ist - "weil man mich schätzt", sagt man mir klar und deutlich, dass anscheinend Reli-Lehrer und FPÖ nicht zusammen geht. Das sei gegen die Menschenwürde. Mit meinen Eltern, besonders mit meiner Mutter brauche darüber nicht reden. Meine Mutter wählt deshalb ÖVP, da eckt man nirgends an. 

In nächster Zeit ist ein Treffen unseres Jahrgangs von der KPH - und genau deshalb bin ich mir nicht sicher, ob ich hinfahre. Es wird ganz bestimmt darüber gesprochen werden, ob ich dabei bin oder nicht. Gehe ich hin, wird man mich persönlich darauf ansprechen. Gehe ich nicht hin, redet hinter meinem Rücken darüber und legt das gegen mich aus. 

Also ist es besser, ich gehe nicht hin, dann höre ich nicht, was man über mich redet. 

* [2026-08-10 Mo 00:22] Bible in a year

[[denote:20260809T183257][Day 221: Walking with Wise Men (2026)]]

Dieses tägliche Lesen in der Bibel gibt mir echt viel Kraft - seit 221 Tagen schon. Viel Notizen habe ich mir noch nicht gemacht, egal - muss ja nicht jeden Tag sein. 


