#+title:      Donnerstag 1 Oktober 2026 10:41
#+date:       [2026-10-01 Do 10:41]
#+filetags:   :journal:
#+identifier: 20261001T104123

* [2026-10-01 Do 10:41] Lehrer sein

Es ist so mühsam - besonders als Religionslehrer. Jeder hier trägt viel, ich kenne keinen, der nicht "jammert" oder "meckert". Komme ich den Schülern entgegen, habe ich Probleme mit der Disziplin. Mache ich Stoff - ist es zu katholisch und alle wollen nur mehr spielen. Fragt man die Kinder, was sie wollen, was sie interessiert - dann weiß doch jeder, was kommt: spielen, Filme, raus gehen, nichts machen, ...

M, E und D Lehrer geht es nicht besser - die Schüler lernen nichts und sind hauptsächlich faul. Es eskaliert ständig.

Und meine oft jüngeren Kollegen haben keine Familie und viel Zeit für Vorbereitungen - und doch ...

Und für meine Kollegen ist der Religionsunterricht nur mühsam, weil sie auf jene aufpassen müssen, die nicht Religion gehen - und das sind durch die Bank nur äußerst schwierige Schüler. Für sie wäre es am besten - Religionsunterricht gäbe es gar nicht.
 


