#+title:      Donnerstag 8 Jänner 2026
#+date:       [2026-01-08 Do 08:28]
#+filetags:   :journal:
#+identifier: 20260108T082836

* [2026-01-08 Do 08:28] Gestriger Tag in Seekirchen

Hui, das war gestern aufregend. Ich bin mit ziemlich viel Bauchweh nach Seekirchen gefahren - hab erwartet, ass Gudrun mich im Unterricht besuchen kommt. Ich hatte zuerst eine Supplierstunde in der 4B (E); die Schüler haben gut gearbeitet. Dann war ich in der 3d und vier Schüler waren sofort dabei beim Sternsingen. Zuerst haben wir die Sprüche geübt und haben dann fast alle Klassen im Altbau + die Direktion besucht. War so schön.

In der nächsten Stunde war ich in der 1d und dort war es zu Beginn etwas schwieriger, die Schüler zum Mitmachen zu animieren. Mit der 1d haben wir alle Klassen im Container besucht. Dann hatte ich noch zwei TEX Stunden mit der 3b - war etwas chaotisch; aber okay.

Heute bin ich in Mattsee. Da ich aber gestern den Stern in Seekirchen vergessen hatte - musste ich diesen in der Schule in Seekirchen abholen. Bei der Einfahrt nach Seekirchen kam ich ins Rutschen - es war wirklich glatt, eisig und voller Schnee. 

Beim Weiterfahren musste ich einen Berg hinauf, beim Wegfahren kam ich kaum vorwärts - so rutschig. Über den Obertrumer Berg fuhr ich vorsichtig - da geht's steil bergab und es ist eisig. Bei der Ankunft in Obertrum hab ich mich verfahren. Einmal durch den gesamten Ort. Aber jetzt bin ich gut in Mattsee angekommen.


