#+title:      Donnerstag 29 Jänner 2026
#+date:       [2026-01-29 Do 12:35]
#+filetags:   :journal:
#+identifier: 20260129T123527

* [2026-01-29 Do 12:35] Great Adventure Bible

Seit dem <2026-01-01 Do> lese ich die gesamte Bibel in einem Jahr. Dazu verwende ich die "Great Adventure Bible". Letztes Jahr habe ich mir im Dezember diese englische Bibel gekauft (und heuer im Januar die Premium Edition dazu - mit einem echten Ledereinband aus Ziegenleder). Heute ist der 29. Tag und ich bin laut Leseplan im Buch Exodus. Ich habe in meinem Leben niemals die gesamte Bibel gelesen. Ich denke als Kind oder Jugendlicher habe ich es bis zum Ende des Buches Genesis oder Exodus geschafft. Aber nie weiter; in all den letzten Jahren habe ich viele Teile / Bücher der Bibel gelesen; jedoch niemals von Anfang bis Ende.

Diese Bibel ist etwas Besonderes. Sie enthält einen "Zeitplan", wodurch die Bibel bzw. die Heilsgeschichte in 12 Abschnitte eingeteilt wird. Diesen Abschnitten werden 14 Bücher der Bibel zugeordnet, welche die gesamte Heilsgeschichte erzählen:

Alte Welt (Gen 1-11) - Türkis [Farbe der Erde im Weltall]
Patriarchen (Gen 12-50) - Burgund [Farbe des Blutes / Bund Gottes mit Abraham]
Auszug aus Ägypten (Exodus) - Rot [Rotes Meer]
Wanderung in der Wüste (Numeri) - Sandfarben [Wüste]
Eroberung und Richter (bis 1 Sam 1-8) - Grün [die grünen Hügel Kanaans]
Königreich (1 Sam 9-31; 2 Sam; 1 Kön 1-11) - Purpur [Farbe des Königs]
Geteiltes Königreich (ab 1 Kön 12-22; 2 Kön 1-16) - Schwarz [die dunkelste Epoche Israels]
Exil (2 Kön 17-25) - Hellblau [die Israeliten singen den Blues in Babylon]
Rückkehr aus dem Exil (Ezra; Nehemia) - Gelb [Israel sieht hellere Tage]
Aufstand der Makkabäer (1 Makk) - Orange [das Feuer, die Flammen der Öllampen im gereinigten Tempel]
Messianische Erfüllung (Lukas) - Gold [Gabe der Sterndeuter]
Die Kirche (Apostelgeschichte) - Weiß [die makellose Braut Christi]

Alle anderen Bücher werden diesen 14 Geschichtsbüchern zugeordnet. Ich habe dadurch eine neue Liebe zum Wort Gottes entdeckt. Das Lesen auf Englisch fordert auch mein Gehirn heraus. Der Podcast von Father Mike Schmitz ist super. (Ah wie kann ich Podcasts in Linux hören?)

Die KDE App Kasts ist bestens für Podcasts geeignet; hab den Podcast von Father Mike Schmitz gefunden und abonniert. Toll!

In der Mittagspause werde ich jetzt in der Bibel weiterlesen; um 14h30 ist dann die Notenkonferenz hier in Mattsee. 

 


